### ISSUE TITLE
32-bit arch support and WASM

### ISSUE THREAD

**Issue by ryanking13** [dmlc/xgboost#10015]
Hi, I'm one of the core developers of [Pyodide](https://github.com/pyodide/pyodide), which is porting the Python ecosystem to the browser using WebAssembly.
First of all, thank you for maintaining this project for a long time!

In Pyodide, we have been providing WebAssembly version of xgboost since 2022. WebAssembly is based on the 32bit architecture, so we've been having some trouble updating xgboost since it decided to drop 32bit arch support.

As an open-source maintainer, I understand the challenges of managing a project with a small resource, so I fully understand the decision to remove support for 32bit systems to reduce management costs. However, given that the use of Python in WebAssembly environments may become more prevalent in the future (at least I hope), it would be very happy if we could discuss how xgboost can support 32-bit arch or WASM in the long term.

**Comment by trivialfis** [comment]
Thank you for raising the issue, we weren't aware of web assembly is using 32bit space. The removal was due to R dropping requirement on 32 bit, and we thought that it was the last platform for 32bit.

Will restore the support (at best effort)

**Comment by hcho3** [comment]
@ryanking13 Would you be able to help debug issues with 32-bit builds?

**Comment by ryanking13** [comment]
Thank you for your positive responses!

> @ryanking13 Would you be able to help debug issues with 32-bit builds in the future? Most likely we won't be able to do full level of testing for 32-bit target (due to lack of manpower), so any help will be greatly appreciated.

Sure, I think I can help with debugging issues with 32-bit builds. I don't have any particular expertise in that area, but I should be able to help you analyze the issue.

**Comment by hcho3** [comment]
@ryanking13 Thanks! I will ping you if I need help. Also, we have yet to receive any bug reports from Pyodide users. Please send us bug reports whenever XGBoost fails to work with the 32-bit enviornment.
