### ISSUE TITLE
xgbregressor and spark.SparkXGBRegressor giving very different results

### ISSUE THREAD

**Issue by iamyihwa** [dmlc/xgboost#10012]
Hello 
I am getting very different results using xgbregressor and sparkxgbregressor. 

Any idea why this is happening and how I could fix it? 

I have not given seed for XGBRegressor when I initiated it, and I noticed that SparkXGBRegressor doesn't have a seed parameter. 

```
from xgboost.spark import SparkXGBRegressor 
from xgboost import XGBRegressor
```

version of xgboost == 2.0.3
Thanks in advance!

**Comment by wbo4958** [comment]
Hi @iamyihwa, could you give more details about the issue, better to have some repro code and faked data.

**Comment by trivialfis** [comment]
let's continue the discussion in https://github.com/Nixtla/mlforecast/issues/308 .
