### ISSUE TITLE
Complication error for R package installation

### ISSUE THREAD

**Issue by yjqiu** [dmlc/xgboost#1001]
I followed the instruction in website to install updated R packages, and I got the following error during complication.

In file included from xgboost_custom.cc:6:
src/common/random.h:32: error: ‘constexpr’ does not name a type
src/common/random.h:36: error: ‘constexpr’ does not name a type
xgboost_custom.cc: In member function ‘xgboost::common::CustomGlobalRandomEngine::result_type xgboost::common::CustomGlobalRandomEngine::operator()()’:
xgboost_custom.cc:62: error: ‘max’ is not a member of ‘xgboost::common::CustomGlobalRandomEngine’
make: **\* [xgboost_custom.o] Error 1
ERROR: compilation failed for package ‘xgboost’

**Comment by ykangxie** [comment]
Yes, I have the same problem on a linux server. I have no issues installing from CRAN at all, but installing from /dmcl/drat returns error like this.

**Comment by khotilov** [comment]
That "complication" is because of the old gcc compiler version which doesn't support the C++11 `constexpr` specifier. If it's Redhat or CentOS 6.x, you can install devtoolset-3 or 4 that has newer gcc.

**Comment by thirdwing** [comment]
@khotilov You are right. A compiler with C++11 support is required for the latest version of xgboost.
