### ISSUE TITLE
Global configuration could manage global number of threads

### ISSUE THREAD

**Issue by david-cortes** [dmlc/xgboost#10027]
XGBoost has a global configuration state:
https://xgboost.readthedocs.io/en/stable/parameter.html#global-configuration

Some places in the code try to retrieve a global number of threads, such as here:
https://github.com/dmlc/xgboost/blob/4dfbe2a8935ca45321e906ab8ee62b5d592d1fe8/src/gbm/gbtree_model.cc#L112

The default number of threads is determined from OpenMP, which is a reasonable thing to do:
https://github.com/dmlc/xgboost/blob/4dfbe2a8935ca45321e906ab8ee62b5d592d1fe8/src/common/threading_utils.cc#L100

But being a global configuration, would be more logical to allow users to modify it through the functions that are named as such.

It would make things better for the R interface, since currently there are workarounds like these which result in degraded performance for users:
https://github.com/dmlc/xgboost/blob/4dfbe2a8935ca45321e906ab8ee62b5d592d1fe8/src/gbm/gbtree_model.cc#L120

If it were a global option, should be possible to adopt a mechanism like LightGBM's which changes the number of configured threads before tests and examples, but doesn't have the lines that change the threads in the user-visible part of the examples, so that it executes with reduced threads on CRAN but doesn't suggest doing so to the user.

Example:
https://github.com/microsoft/LightGBM/blob/252828fd86627d7405021c3377534d6a8239dd69/R-package/R/lgb.Dataset.R#L783

**Comment by trivialfis** [comment]
After working on distributed systems, I'm a bit afraid of this global variable, it's global and it's thread local. This results in the fact that it needs special handling for distributed systems, and it fails without possible fix when user launches a new thread without setting the value again.

**Comment by david-cortes** [comment]
> After working on distributed systems, I'm a bit afraid of this global variable, it's global and it's thread local. This results in the fact that it needs special handling for distributed systems, and it fails without possible fix when user launches a new thread without setting the value again.

But a failure here would be no issue, since then it could just default back to OMP's config.

The idea would be to use this as a means to override the OMP config, so that it would check for this first, and then if it's not set, would look at the OMP config.

**Comment by trivialfis** [comment]
> since then it could just default back to OMP's config.

Depending on your perspective, this change of behavior can be considered a bug. In general, global variable are not very desirable.

> The idea would be to use this as a means to override the OMP config

I think booster local variable is fine. It's a bit inconvenient when writing tests and examples, but it's really a CRAN issue instead of a real world problem. We can workaround it by setting global OMP environment variable before running any test, XGBoost respects those variables. https://github.com/dmlc/xgboost/blob/4dfbe2a8935ca45321e906ab8ee62b5d592d1fe8/tests/python/test_openmp.py#L83

**Comment by trivialfis** [comment]
I think we can close this now that https://github.com/dmlc/xgboost/pull/10028 is merged.
