### ISSUE TITLE
[jvm-packages] Data format Issue: I am executing XGBoost on SPARK. I was able to train the model with input dataset as labeled point data format.However I am not able to predict.Please look into it

### ISSUE THREAD

**Issue by astrude** [dmlc/xgboost#1002]
Error message:

val model = XGBoost.train(trainingData_xgb, paramMap,10,nWorkers=50)

Above code has worked, following didn't

scala> val predTrain = model.booster.predict(trainingData_xgb,true,10)
<console>:80: error: type mismatch;
 found   : org.apache.spark.rdd.RDD[org.apache.spark.mllib.regression.LabeledPoint]
 required: ml.dmlc.xgboost4j.scala.DMatrix
       val predTrain = model.booster.predict(trainingData_xgb,true,10)

**Comment by CodingCat** [comment]
@astrude as it said in the REPL, 

```
:80: error: type mismatch;
found : org.apache.spark.rdd.RDD[org.apache.spark.mllib.regression.LabeledPoint]
required: ml.dmlc.xgboost4j.scala.DMatrix
```
here is the [API doc] (http://dmlc.ml/docs/scaladocs/xgboost4j-spark/index.html#ml.dmlc.xgboost4j.scala.spark.XGBoostModel), you need to transform your dataset into RDD[Vector] or DMatrix to call predict....

**Comment by astrude** [comment]
Tried to use the RDD input, asking for Dmatrix:

scala> model.booster.predict(finalRDD)
<console>:119: error: type mismatch;
 found   : org.apache.spark.rdd.RDD[Array[Double]]
 required: ml.dmlc.xgboost4j.scala.DMatrix
              model.booster.predict(finalRDD)

Can you please share the code to do the same?

Thanks in advance!

**Comment by CodingCat** [comment]
You are passing a RDD of Array, not Vector....


https://github.com/dmlc/xgboost/blob/master/jvm-packages/xgboost4j-example/src/main/scala/ml/dmlc/xgboost4j/scala/example/spark/DistTrainWithSpark.scala

**Comment by myloginid** [comment]
@CodingCat The above link results in a 404.. Can you point out the right example to convert a LabeledPoint to  DMatrix

**Comment by CodingCat** [comment]
Just go to example directory
