### ISSUE TITLE
XGBoostError: [15:33:38] C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\xgboost\xgboost-ci-windows\src\data\data.cc:277: All feature_types must be one of {int, float, i, q, c}.

### ISSUE THREAD

**Issue by samajo1** [dmlc/xgboost#10038]
# Define feature types for XGBoost DMatrix
        feature_types = [str(X_train[column].dtype) for column in X_train.columns]
        feature_types[X_train.columns.get_loc('Divorce')] = 'category'

        # Now you can proceed with model fitting using the encoded target variables
        for model_name, model in models.items():
            # Assuming XGBoost model is used
            dtrain = xgb.DMatrix(data=X_train, label=y_train_encoded, feature_types=feature_types, enable_categorical=True)
            model.fit(X_train, y_train_encoded)
            accuracy, precision, recall, f1_score, auc_roc = evaluate_model(model, X_test, y_test_encoded)
            summaries.append({
                'treatment': treatment,
                'model_name': model_name,
                'accuracy': accuracy,
                'precision': precision,
                'recall': recall,
                'F1_score': f1_score,
                'AUC/ROC': auc_roc
            })
    return pd.DataFrame(summaries)

---------------------------------------------------------------------------
XGBoostError                              Traceback (most recent call last)
Cell In[22], line 2
      1 #from classificatiomn_modelling import model_performance_summary
----> 2 model_summary = model_performance_summary(datas, models)
      3 print(model_summary)

File ~\PycharmProjects\pythonProject\divorce-prediction\divorce-prediction1\classification_modelling.py:80, in model_performance_summary(datas, models)
     77 # Now you can proceed with model fitting using the encoded target variables
     78 for model_name, model in models.items():
     79     # Assuming XGBoost model is used
---> 80     dtrain = xgb.DMatrix(data=X_train, label=y_train_encoded, feature_types=feature_types, enable_categorical=True)
     81     model.fit(X_train, y_train_encoded)
     82     accuracy, precision, recall, f1_score, auc_roc = evaluate_model(model, X_test, y_test_encoded)

File ~\PycharmProjects\pythonProject\divorce-prediction\venv\lib\site-packages\xgboost\core.py:730, in require_keyword_args.<locals>.throw_if.<locals>.inner_f(*args, **kwargs)
    728 for k, arg in zip(sig.parameters, args):
    729     kwargs[k] = arg
--> 730 return func(**kwargs)

File ~\PycharmProjects\pythonProject\divorce-prediction\venv\lib\site-packages\xgboost\core.py:883, in DMatrix.__init__(self, data, label, weight, base_margin, missing, silent, feature_names, feature_types, nthread, group, qid, label_lower_bound, label_upper_bound, feature_weights, enable_categorical, data_split_mode)
    881     self.feature_names = feature_names
    882 if feature_types is not None:
--> 883     self.feature_types = feature_types

File ~\PycharmProjects\pythonProject\divorce-prediction\venv\lib\site-packages\xgboost\core.py:1383, in DMatrix.feature_types(self, feature_types)
   1379 feature_types_bytes = [bytes(f, encoding="utf-8") for f in feature_types]
   1380 c_feature_types = (ctypes.c_char_p * len(feature_types_bytes))(
   1381     *feature_types_bytes
   1382 )
-> 1383 _check_call(
   1384     _LIB.XGDMatrixSetStrFeatureInfo(
   1385         self.handle,
   1386         c_str("feature_type"),
   1387         c_feature_types,
   1388         c_bst_ulong(len(feature_types)),
   1389     )
   1390 )

File ~\PycharmProjects\pythonProject\divorce-prediction\venv\lib\site-packages\xgboost\core.py:282, in _check_call(ret)
    271 """Check the return value of C API call
    272 
    273 This function will raise exception when error occurs.
   (...)
    279     return value from API calls
    280 """
    281 if ret != 0:
--> 282     raise XGBoostError(py_str(_LIB.XGBGetLastError()))

XGBoostError: [15:33:38] C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\xgboost\xgboost-ci-windows\src\data\data.cc:277: All feature_types must be one of {int, float, i, q, c}.

**Comment by trivialfis** [comment]
If you are using dataframes as input, there's no need to pass a custom feature type, XGB can extract the information from the DF directly.

**Comment by trivialfis** [comment]
Feel free to reopen if there are further questions.
