### ISSUE TITLE
Are There Ways to Identify Which Subsample of Data an XGBoost Tree Was Fitted On?

### ISSUE THREAD

**Issue by darren7753** [dmlc/xgboost#10046]
Hello. I'm interested in finding out if it's possible to determine which specific rows of samples (according to the subsample parameter) are randomly chosen for each tree's training. For instance, with a training set of 100 rows and a subsample rate of 0.7, I'm curious to know the exact 70 rows selected for the training of each tree. I've been searching for a solution everywhere but have had no luck. Thank you!

**Comment by hcho3** [comment]
Hi, currently XGBoost does not store the information of the subsample on which each tree is trained.
