### ISSUE TITLE
xgboost too slow

### ISSUE THREAD

**Issue by celestinoxp** [dmlc/xgboost#10044]
I'm using xgboost in Pycaret and I'm having difficulty tuning it. Pycaret is a framework for using little code and does everything in an automated way. I'm using a dataset with many columns around 3000 and 2500 rows. When using tune_model in pycaret with just 20 iterations the lightgbm and catboost models take about 20 minutes, but xgboost takes about an hour. I'm using the latest version of xgboost (nightly version), so I would like to ask you to analyze what could be happening...
the metrics are close to catboost and lightgbm I think this is normal, but the problem is really the speed...

To reproduce the issue
install the latest pycaret `pip install pycaret[full]`
install latest xgboost for windows (https://s3-us-west-2.amazonaws.com/xgboost-nightly-builds/list.html?prefix=master)
create a dataset with 3000 columns and 2500 rows (categorical, boolean, and numeric mixed types)

code to use 
pycret: xgboost = create_model('xgboost')
tuned_xgboost = tune_model(xgboost, n_iter=20)

**Comment by trivialfis** [comment]
seems like a relatively small dataset, could you please share how many categorical features and how many numerical features?

**Comment by celestinoxp** [comment]
dados_treino.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2537 entries, 16 to 2557
Columns: 3031 entries, data to dst_soma_n4_n5_anterior
dtypes: bool(13), category(5), datetime64[ns](1), float16(2573), float32(194), int16(27), int32(1), int8(88), object(129)
memory usage: 17.3+ MB

**Comment by celestinoxp** [comment]
@trivialfis i converted all object types to int and xgboost still slow too

```
<class 'pandas.core.frame.DataFrame'>
Index: 2537 entries, 16 to 2557
Columns: 3031 entries, data to dst_soma_n4_n5_anterior
dtypes: bool(13), category(5), datetime64[ns](1), float16(2573), float32(194), int16(27), int32(1), int64(129), int8(88)
memory usage: 17.3 MB
```

**Comment by celestinoxp** [comment]
@trivialfis I forgot some information, I'm using Windows 11, pandas 2.1.1

**Comment by celestinoxp** [comment]
![image](https://github.com/dmlc/xgboost/assets/41735311/c54660b2-69f2-48ff-85d2-a36e4519f39b)

2 minutes to create a model...

**Comment by celestinoxp** [comment]
gpu 0 or gpu 1 not used.... and cpu uses not all cpu cores..

![image](https://github.com/dmlc/xgboost/assets/41735311/42b31dcd-1c5e-46ac-be58-e8d66be469f8)

**Comment by moritzwilksch** [comment]
If your data is pretty sparse explicitly passing a `csr_matrix` instead of a dataframe or numpy array speeds things up considerably. This is something LightGBM handles automatically but XGBoost wants you to pass a sparse data structure. IDK whether this applies to training through `pycaret` or on GPU though.

**Comment by celestinoxp** [comment]
> If your data is pretty sparse explicitly passing a `csr_matrix` instead of a dataframe or numpy array speeds things up considerably. This is something LightGBM handles automatically but XGBoost wants you to pass a sparse data structure. IDK whether this applies to training through `pycaret` or on GPU though.

I'm not sure how to do this.... can pycaret do this automatically?

**Comment by celestinoxp** [comment]
I understand, I'll check if it already exists in Pycaret, I don't think so... I'll make a pull-request...
thanks for your help...
