### ISSUE TITLE
[jvm-packages] does xgboost4j-spark must buld under spark cluster?

### ISSUE THREAD

**Issue by leoli2012** [dmlc/xgboost#1004]
hi, all, for some reasons ,i have to  mvn  package on a single machine without spark cluster  to build xgboost4j, however ,everything is ok until package xgboost4j-spark, package  seems stoped to wait for  something..
16/03/17 08:07:56 INFO TaskSetManager: Starting task 0.0 in stage 0.0 (TID 0, localhost, partition 0,PROCESS_LOCAL, 1731242 bytes)
16/03/17 08:07:56 INFO Executor: Running task 0.0 in stage 0.0 (TID 0)
16/03/17 08:07:56 INFO CacheManager: Partition rdd_1_0 not found, computing it
program  seems in a waiting status.......so ,i guess, package must execed in spark cluster?

**Comment by leoli2012** [comment]
by the way,this machine is a Virtual machine.

**Comment by CodingCat** [comment]
would you post a more complete log? I would like to check whether your rabit tracker is started correctly

**Comment by CodingCat** [comment]
it's possible that due to the strange network configuration in your VM instance, rabit cannot start local socket

**Comment by leoli2012** [comment]
hi,this is my mvn debug log
[mvn_debug_package.txt](https://github.com/dmlc/xgboost/files/178974/mvn_debug_package.txt)

**Comment by CodingCat** [comment]
@leoli2012 thanks for attaching the log...so in the last few lines of your log

```
Tracker started, with env={DMLC_TRACKER_URI=192.168.235.130, DMLC_NUM_WORKER=4, DMLC_TRACKER_PORT=9092, DMLC_NUM_SERVER=0}
16/03/17 18:47:18 INFO RabitTracker$TrackerProcessLogger: 2016-03-17 18:47:18,177 INFO start listen on 192.168.235.130:9092
16/03/17 18:47:18 INFO SparkContext: Starting job: foreachPartition at XGBoost.scala:104
16/03/17 18:47:18 INFO DAGScheduler: Got job 0 (foreachPartition at XGBoost.scala:104) with 4 output partitions
16/03/17 18:47:18 INFO DAGScheduler: Final stage: ResultStage 0 (foreachPartition at XGBoost.scala:104)
16/03/17 18:47:18 INFO DAGScheduler: Parents of final stage: List()
16/03/17 18:47:18 INFO DAGScheduler: Missing parents: List()
16/03/17 18:47:18 INFO DAGScheduler: Submitting ResultStage 0 (MapPartitionsRDD[1] at mapPartitions at XGBoost.scala:57), which has no missing parents
16/03/17 18:47:18 INFO MemoryStore: Block broadcast_0 stored as values in memory (estimated size 4.4 KB, free 4.4 KB)
16/03/17 18:47:18 INFO MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 2.2 KB, free 6.7 KB)
16/03/17 18:47:18 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on localhost:38223 (size: 2.2 KB, free: 198.4 MB)
16/03/17 18:47:18 INFO SparkContext: Created broadcast 0 from broadcast at DAGScheduler.scala:1006
16/03/17 18:47:18 INFO DAGScheduler: Submitting 4 missing tasks from ResultStage 0 (MapPartitionsRDD[1] at mapPartitions at XGBoost.scala:57)
16/03/17 18:47:18 INFO TaskSchedulerImpl: Adding task set 0.0 with 4 tasks
16/03/17 18:47:18 WARN TaskSetManager: Stage 0 contains a task of very large size (1690 KB). The maximum recommended task size is 100 KB.
16/03/17 18:47:18 INFO TaskSetManager: Starting task 0.0 in stage 0.0 (TID 0, localhost, partition 0,PROCESS_LOCAL, 1731242 bytes)
16/03/17 18:47:18 INFO Executor: Running task 0.0 in stage 0.0 (TID 0)
16/03/17 18:47:18 INFO CacheManager: Partition rdd_1_0 not found, computing it
```

your Rabit tracker starts and never get any start signal from the workers....the result is that, it blocks the execution forever to wait for the workers to start....


Here is the log in the right track...after Rabit Tracker is started, the following lines shall appear in the log, which indicates that the tracker receives start signal from the workers

```
16/03/17 22:10:11 INFO RabitTracker$TrackerProcessLogger: 2016-03-17 22:10:11,681 DEBUG Recieve start signal from 192.168.0.196; assign rank 0
16/03/17 22:10:11 INFO RabitTracker$TrackerProcessLogger: 2016-03-17 22:10:11,681 DEBUG Recieve start signal from 192.168.0.196; assign rank 1
16/03/17 22:10:11 INFO RabitTracker$TrackerProcessLogger: 2016-03-17 22:10:11,682 DEBUG Recieve start signal from 192.168.0.196; assign rank 2
16/03/17 22:10:11 INFO RabitTracker$TrackerProcessLogger: 2016-03-17 22:10:11,690 DEBUG Recieve start signal from 192.168.0.196; assign rank 3

```

**Comment by CodingCat** [comment]
@tqchen It's the second time for me to meet this problem, is it a good solution to quit the tracker with a non-zero exit code if it didn't get any connection from the worker for x mins?

**Comment by tqchen** [comment]
hmm, it is a bit hard to use an exact timeout. The reason was the spark stage never get started right?

**Comment by CodingCat** [comment]
no, in @leoli2012 's case, it is due to the network configuration, the worker does not get back to the rabit tracker...just like my case several days ago (while that's due to a strange build)

**Comment by CodingCat** [comment]
I mean if a tracker is hanging there for x mins, and no worker gets back to it...we assume that it is an error....(even one worker gets back, we can take it as the correct behavior as the other workers might be started later due to the multi-wave of spark job)

**Comment by tqchen** [comment]
OK, I think we can add a timeout say 2mins. Usually user can use ctrl+c to kill the thing so.

**Comment by shaform** [comment]
I've also encountered this problem before. Interestingly, if I change `numWorkers = 4` to `numWorkers = 2`, then it can complete successfully.

**Comment by CodingCat** [comment]
numWorkers means that your rabit requires 4 parallel workers to train 4 trees.... it is possible that your CPU does not have more than 3 cores, in which case the rabit will wait for `4 - your cpu-core-number` workers to start...

**Comment by CodingCat** [comment]
with more details, spark maps each task to a cpu core by default, that means, if your cpu has n cores, you can at most start n parallel tasks...each task is a xgboost instance

**Comment by shaform** [comment]
Indeed! The machine I used to build xgboost-spark only has 2 cores.

**Comment by CodingCat** [comment]
ah.... i see....numWorkers is fixed mistakenly....it might be some leftover during debugging....surprisingly, travis CI provides more than 4 cores for test?

**Comment by CodingCat** [comment]
https://github.com/dmlc/xgboost/pull/1010 this patch shall fix the issue

**Comment by leoli2012** [comment]
hi,@CodingCat,
i added 2 cpu core to virtual machine, above issue was gone, but mvn package fail for another  reason in build xgboost-spark package  stage.
[mvn_package_log.txt](https://github.com/dmlc/xgboost/files/181651/mvn_package_log.txt)

**Comment by CodingCat** [comment]
`Tracker started, with env={}` is fishy...it seems that your Tracker cannot bind to local NIC

**Comment by leoli2012** [comment]
@CodingCat ， thanks for you help, my machine's python(version2.4) cause this issue. ,after update python to 2.7, i  mvn package successed.

**Comment by adamzjw** [comment]
@leoli2012  thanks to your posts, I figure out what happened when "Tracker started, with env={}" is return.

RabitTracker call Runtime to exec a command like "python ..." which is depended on env variable PATH. Setting the correct python version fixes this issues.
