### ISSUE TITLE
Mismatch of split_conditions loading via `json.load` and `load_model` 

### ISSUE THREAD

**Issue by mesejo** [dmlc/xgboost#10056]
There is a mismatch between manually loading the split_conditions via `json.load` and via `model.load_model`:

```python
import xgboost as xgb
import json

with open("model-single-tree.json") as infile:
    data = json.load(infile)
    json_trees = data["learner"]["gradient_booster"]["model"]["trees"]
    value = json_trees[0]["split_conditions"][0]
    print("Value via json load", value)

    model = xgb.XGBClassifier()
    model.load_model("model-single-tree.json")

    model_value = json.loads(model.get_booster().get_dump(dump_format="json")[0])["split_condition"]
    print("Value via model load", model_value)
```

**Output**
```bash
Value via json load -1.7919981
Value via model load -1.79199815
```

The file for the model can be found [here](https://gist.github.com/mesejo/24d3bc6bcdba2a97fc6079b31cdb711f). I noticed this behavior because I'm trying to implement a custom inference algorithm, and a data point is being misclassified due to this difference. The `5.0e-8` difference remains consistent after multiple executions of the script. 

**Additional Information**
xgboost version: '2.0.3'

**Comment by trivialfis** [comment]
The JSON parser is only guaranteed to be consistent within XGBoost due to serialization of binary floating to the decimal numbers. Consider using the UBJEON format.

**Comment by trivialfis** [comment]
That's the easiest way since there are existing implementations in various languages. Otherwise, you need to build/find a JSON parser with a compatible floating point serializer. See the citation of the serializer here https://github.com/dmlc/xgboost/blob/2e4ea5ecc060a7742edea03b35b61ad20303e623/src/common/charconv.cc#L4

**Comment by trivialfis** [comment]
Feel free to reopen if there are further questions.
