### ISSUE TITLE
make fails with error 'fopen64' was not declared in this scope while complinig by mingw64 5.3.0

### ISSUE THREAD

**Issue by DrAndrey** [dmlc/xgboost#1005]
I tried to compile last xgboost version on Windows 10 by mingw64 5.3.0. But I got error with 'fopen64'.
I downloaded Mingw64 from https://sourceforge.net/projects/mingw-w64/. Maybe I have to add some pathes in my environment? Now i just added path to binary files.

**Comment by thirdwing** [comment]
@tqchen This is not the first time Windows users meet `fopen64` error (https://github.com/dmlc/dmlc-core/blob/master/include/dmlc/base.h#L110-L112)

It seems some MinGW distribution doesn't define `fopen64` and even `fopen64` is defined, it is just redirect to `fopen`.

https://sourceforge.net/p/mingw-w64/code/HEAD/tree/trunk/mingw-w64-crt/stdio/fopen64.c

**Comment by tqchen** [comment]
Do you mind to open a PR to add this definition when minGW is defined?

**Comment by DrAndrey** [comment]
I found problem. It was conflict between mingw and cygwin. Xgboost was built perfectly by mingw64. Thank you!
