### ISSUE TITLE
No response using xgboost after uwsgi integration with flask

### ISSUE THREAD

**Issue by liudaolunboluo** [dmlc/xgboost#10072]
When I call xgb.DMatrix for the first time after my service has started, the thread always gets stuck at _LIB.XGDMatrixCreateFromDense and remains unresponsive, and then the second time I request it xgb.DMatrix returns a matrix of all zeros resulting in an exception in my reasoning, so what could be the cause?

xgboost   version is 1.7.6
uwsgi version is 2.0.23

**Comment by liudaolunboluo** [comment]
If I set uwsgi to threads=1, it blocks on every request

**Comment by liudaolunboluo** [comment]
If I set up 4 processes, 3 threads per process, then the first request gets stuck, the second and third requests are fine, the fourth request gets stuck again, and if I understand uwsgi correctly, the fourth request goes into a new process, which means that every time the uwsgi process executes XGDMatrixCreateFromDense for the first time it gets stuck, and then continuing to execute XGDMatrixCreateFromDense on that process returns a matrix of all 0s!

**Comment by hcho3** [comment]
Have you tried using `inplace_predict` instead? This function does not require the construction of DMatrix.

XGBoost internally uses OpenMP to use multiple threads when running prediction. I wonder if the use of OpenMP interferes with uwsgi.

**Comment by liudaolunboluo** [comment]
> Have you tried using `inplace_predict` instead? This function does not require the construction of DMatrix.
> 
> XGBoost internally uses OpenMP to use multiple threads when running prediction. I wonder if the use of OpenMP interferes with uwsgi.

I'm actually more interested in figuring out why this is happening, because it doesn't come back when I switch the program to start without uwsgi or switch to another machine, which means that it's not 100% reproducible, but it's 100% reproducible on the machine that had the problem.

**Comment by liudaolunboluo** [comment]
> inplace_predict

It's amazing, I don't get stuck and prediction errors when I call predict after my code calls inplace_predict first!

**Comment by liudaolunboluo** [comment]
I can be pretty sure that the problem is in the XGDMatrixCreateFromDense method, but after reading the source code I found that this method doesn't have any thread-unsafe operations, it's all about new object operations in each thread, so I'm very confused

**Comment by liudaolunboluo** [comment]
I defined clf = joblib.load(filepath) as a public variable in the py file, and even running inplace_predict gets stuck!

**Comment by hcho3** [comment]
I'm not sure why this is happening. Let's hope someone else might have a better insight.

**Comment by liudaolunboluo** [comment]
> I'm not sure why this is happening. Let's hope someone else might have a better insight.

Under what circumstances would XGDMatrixCreateFromDense return a matrix with all 0. 0.'s?

**Comment by liudaolunboluo** [comment]
The stuck places all have one thing in common they all use an ArrayAdapter, if you call a method that doesn't have an ArrayAdapter such as XGBoosterCreate, it won't get stuck!

**Comment by trivialfis** [comment]
ArrayAdapter is also used by inplace predict

**Comment by liudaolunboluo** [comment]
> inplace predict

yes，because  inplace predict is also get stuck

**Comment by liudaolunboluo** [comment]
Newly discovered, as long as the first access after uwsgi startup is not to access the interface related to these two methods, the second access will not be a problem.

**Comment by trivialfis** [comment]
Maybe it's `libgomp` running into issues with fork https://gcc.gnu.org/bugzilla/show_bug.cgi?id=58378 .

I don't think it's the array adapter to blame, it's more likely that when an array adapter is used by a public interface function, OpenMP is also used (create DMatrix, inplace predict, etc). Googling "libgomp fork safe" can find a lot of similar issues, (and we run into it before)

If you want to verify whether this is the case, you can try to disable OpenMP or use llvm/clang-based toolchain along with its libomp. Both require recompiling XGBoost though.

**Comment by liudaolunboluo** [comment]
> Maybe it's `libgomp` running into issues with fork https://gcc.gnu.org/bugzilla/show_bug.cgi?id=58378 .
> 
> I don't think it's the array adapter to blame, it's more likely that when an array adapter is used by a public interface function, OpenMP is also used (create DMatrix, inplace predict, etc). Googling "libgomp fork safe" can find a lot of similar issues, (and we run into it before)
> 
> If you want to verify whether this is the case, you can try to disable OpenMP or use llvm/clang-based toolchain along with its libomp (instead of `libgomp`). Both require recompiling XGBoost though.

Thank you very much for your reply, I'm sure it will be very helpful, I'd like to support how to turn off openMp in xgboost, I already know how to compile it, also I'm very curious, if the blocking is due to a fork, why does a subsequent call to XGDMatrixCreateFromDense from another thread in the same process return a matrix with all zeros!

**Comment by liudaolunboluo** [comment]
> Maybe it's `libgomp` running into issues with fork https://gcc.gnu.org/bugzilla/show_bug.cgi?id=58378 .
> 
> I don't think it's the array adapter to blame, it's more likely that when an array adapter is used by a public interface function, OpenMP is also used (create DMatrix, inplace predict, etc). Googling "libgomp fork safe" can find a lot of similar issues, (and we run into it before)
> 
> If you want to verify whether this is the case, you can try to disable OpenMP or use llvm/clang-based toolchain along with its libomp (instead of `libgomp`). Both require recompiling XGBoost though.

I'm more certain now that it might be a fork issue, because I configured lazy-apps = true, which would load the Flask app once for each worker instead of forking it from the main staff, and then there was no problem

**Comment by trivialfis** [comment]
You can look into the CMake file at the root of project directory, there's a list of options for compiling. Also, we have document for how to compile XGBoost.

As for 0 value, that might be the default value for floating point. However, when there's a concurrency issue (fork), I think there's very little meaning in interpreting any output and can safely assume it's random.

> I'm more certain now that it might be a fork issue,

That's good news, we can focus on that. Consider the llvm toolchain or disabling openmp should help. In general, XGBoost is not fork safe since neither CUDA nor libgomp is fork safe, and we don't test such use case.

**Comment by liudaolunboluo** [comment]
> You can look into the CMake file at the root of project directory, there's a list of options for compiling. Also, we have document for how to compile XGBoost.
> 
> As for 0 value, that might be the default value for floating point. However, when there's a concurrency issue (fork), I think there's very little meaning in interpreting any output and can safely assume it's random.
> 
> > I'm more certain now that it might be a fork issue,
> 
> That's good news, we can focus on that. Consider the llvm toolchain or disabling openmp should help. In general, XGBoost is not fork safe since neither CUDA nor libgomp is fork safe, and we don't test such use case.

Thank you very much for your reply, it's very helpful, if I understand it correctly, it's because uwsgi forked a sub-thread, and then this sub-thread called the method of xgboost's so-file, and if libgomp or openMP is used in this method, it may cause the first sub-thread to hang, and that's the reason why my program is blocking, and the only thing that confuses me is that the later forked sub-thread not only doesn't block, but also gets a value of 0 when creating the matrix, but the reasoning part is right again. The only thing I'm confused about is that the subsequent forked subthread not only doesn't block but also gets a value of 0 when the matrix is created, but the reasoning is correct. Can you give me some advice from the code point of view of the XGDMatrixCreateFromDense function that creates the matrix? Where in the code or causing this? I read the code and I suspect it is: collective::Allreduce<collective::Operation::kMax>(&info_.num_col_, 1); 
This line of code causes

**Comment by liudaolunboluo** [comment]
I think I've got it all figured out, first of all why some environments have problems and some don't, because the environment that doesn't have problems (running on K8S) limits the number of CPU cores to 0.25, which is less than 1, then openMP will only provide a thread that won't be enabled, which won't trigger the fork problem, and when I limit the number of CPU cores of the pod that has problems to 1, I'm not sure if I can get it to work. When I limit the CPU cores of the problematic pod to 1, the problem does not occur. Secondly why the matrix is, I read the XGDMatrixCreateFromDense code and found that openMP is used in simpleMatrinx for example:
#pragma omp parallel for reduction(+ : num_elements, num_rows) num_threads(ctx_.Threads())
    for (int i = 0; i < static_cast<int>(batches.size()); ++i) { // NOLINT
      num_elements += batches[i]->Import(missing);
      num_rows += batches[i]->Size();
    }
If there is a problem with openMP then no looping will take place I guess, that is, when doing matrix operations all values will be
