### ISSUE TITLE
Can't install xgboost on Mac OS X El Capitan

### ISSUE THREAD

**Issue by rostamsunrun** [dmlc/xgboost#1007]
I followed the instructions (https://xgboost.readthedocs.org/en/latest/build.html#building-on-osx) to install xgboost on Mac OS X El Capitan. But when I run `make` I get the following error. Any suggestions how to fix it? I think it might be because `ar` is too old on Mac (from 2005):

```
$ make
ar crv lib/libxgboost.a 
ar: no archive members specified
usage:  ar -d [-TLsv] archive file ...
    ar -m [-TLsv] archive file ...
    ar -m [-abiTLsv] position archive file ...
    ar -p [-TLsv] archive [file ...]
    ar -q [-cTLsv] archive file ...
    ar -r [-cuTLsv] archive file ...
    ar -r [-abciuTLsv] position archive file ...
    ar -t [-TLsv] archive [file ...]
    ar -x [-ouTLsv] archive [file ...]
make: *** [lib/libxgboost.a] Error 1

```

**Comment by KPdir** [comment]
I am trying to do the same right now and having problems but different ones. 
Check out this thread: https://github.com/dmlc/xgboost/issues/276 for details. You'll have to run ``` cp ./ make/config.mk && make config.mk``` from within the xgboost directory.

**Comment by rostamsunrun** [comment]
Sorry for responding late, I was out on a trip with limited internet access.
Thank you very much for responding to my questions. I tried to follow your thread, but here is the error I get when I run `make`

    $ make
    ar crv lib/libxgboost.a 
    ar: no archive members specified
    usage:  ar -d [-TLsv] archive file ...
	    ar -m [-TLsv] archive file ...
    	    ar -m [-abiTLsv] position archive file ...
	    ar -p [-TLsv] archive [file ...]
	    ar -q [-cTLsv] archive file ...
	    ar -r [-cuTLsv] archive file ...
	    ar -r [-abciuTLsv] position archive file ...
	    ar -t [-TLsv] archive [file ...]
	    ar -x [-ouTLsv] archive [file ...]
    make: *** [lib/libxgboost.a] Error 1

**Comment by rostamsunrun** [comment]
Hi,
Thanks for your response. Sorry for late follow up (I was on a trip with limited internet access).
I followed your thread and installed clang-omp using `brew install clang-omp` and modified my `config.mk` file to the following:

    # choice of compiler, by default use system preference.
    export CC = clang-omp
    export CXX = clang-omp++
    export MPICXX = clang-omp++
    
    # the additional link flags you want to add
    ADD_LDFLAGS =-fopenmp
    
    # the additional compile flags you want to add
    ADD_CFLAGS =-fopenmp
    
    # Whether enable openmp support, needed for multi-threading.
    USE_OPENMP = 1
    
    # whether use HDFS support during compile
    USE_HDFS = 0

    # whether use AWS S3 support during compile
    USE_S3 = 0
    
    # whether use Azure blob support during compile
    USE_AZURE = 0
    
    # Rabit library version,
    # - librabit.a Normal distributed version.
    # - librabit_empty.a Non distributed mock version,
    LIB_RABIT = librabit.a
    
    # path to libjvm.so
    LIBJVM=$(JAVA_HOME)/jre/lib/amd64/server

When I run `make`, all I get is:

    $ make
    make: Nothing to be done for `all'.

Do you know how to fix this?

**Comment by phunterlau** [comment]
@rostamsunrun please do `make clean` firstly.

**Comment by rostamsunrun** [comment]
Thanks. Here is the error message I get:
```
$ make clean
rm -f -rf build build_plugin lib bin *~ */*~ */*/*~ */*/*/*~ */*.o */*/*.o */*/*/*.o xgboost

```
```
$ make
clang-omp++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/learner.o src/learner.cc >build/learner.d
In file included from src/learner.cc:7:
In file included from include/xgboost/logging.h:11:
In file included from dmlc-core/include/dmlc/logging.h:10:
/usr/local/Cellar/clang-omp/2015-04-01/libexec/bin/../include/c++/v1/cstdio:100:10: fatal error: 
      'stdio.h' file not found
#include <stdio.h>
         ^
1 error generated.
make: *** [build/learner.o] Error 1

```
I followed the instructions in the link below and ran `pip install xgboost` with no error. I can now import xgboost in my python application and it's working fine. How is that possible? I have NOT installed xgboost (`make` never worked), but I have installed xgboost on python?
http://stackoverflow.com/questions/36038836/install-xgboost-on-mac-ld-library-not-found

**Comment by phunterlau** [comment]
seems like your xcode command-line tools is broken. please install it via xcode-select --install

**Comment by phunterlau** [comment]
p.s. pip install xgboost is an old version before the recent refactor. I will update the pip later.

**Comment by rostamsunrun** [comment]
Should I just go ahead and try installing xgboost (using code-select --install) over the one I have installed (using pip install xgboost). Won't there be any conflict between them?

**Comment by phunterlau** [comment]
please try compiling from github firstly. if it works, install it via setup.py, which overwrites the old one. if doesnt work, the old version from pip is good for now

**Comment by barbara73** [comment]
Hey, I had the same problems installing on mac OS X El Capitan.
I did:
brew install clang-imp
export CC=clang-omp
export CXX=clang-omp++
cd python-package
sudo python setup.py install
cd xgboost; cp make/minimum.mk ./config.mk; make -j4

The installation worked without errors.

But now I have this error message, when I try to run my project in Xcode:
dyld: Library not loaded: lib/libxgboost.so
  Referenced from: /Users/myname/Library/Developer/Xcode/DerivedData/SlidingWindow-guvagsoxbibapcgzroifyazijseu/Build/Products/Debug/SlidingWindow
  Reason: image not found

Does anyone know how to solve this??

The installation (as on installation guide - xgboost 0.4 documentation) on Yosemite worked without problems and I could run my project without errors.
