### ISSUE TITLE
`rank:pairwise` conflict with `ndcg_exp_gain` = `False`

### ISSUE THREAD

**Issue by xbanke** [dmlc/xgboost#10099]
If `ndcg_exp_gain` = `True`, the degress must be less or equal to 31.

Is there a way that totally compatible with version `1.7.6` if objective is `rank:pairwise`?

**Comment by trivialfis** [comment]
May I assume that you are using the NDCG metric with the pairwise objective?

**Comment by xbanke** [comment]
> May I assume that you are using the NDCG metric with the pairwise objective?

No, I have my own metric: correlation coefficient. So it does nothing with NDCG

**Comment by xbanke** [comment]
Thank you very much.
