### ISSUE TITLE
Docs on params and Python tutorial for regression

### ISSUE THREAD

**Issue by JacobHelwig** [dmlc/xgboost#10104]
Thank you for the great package.

I'm struggling to find a tutorial in python for doing regression with the library. Also, I am having trouble finding docs on the params argument, i.e., valid and default values for params. If I am not overlooking existing officially released resources, they would be great additions.

**Comment by hcho3** [comment]
> I am having trouble finding docs on the params argument, i.e., valid and default values for params

You may consult https://xgboost.readthedocs.io/en/latest/parameter.html, which documents the valid and default values for all parameters.

https://xgboost.readthedocs.io/en/latest/python/examples/index.html has examples for using XGBoost in Python for a variety of tasks.
