### ISSUE TITLE
An error occurred: jemalloc unsupported system page size

### ISSUE THREAD

**Issue by FuncJ** [dmlc/xgboost#10102]
Hello. I am trying to use Ansor for auto-tuning, and I have installed py-xgboost-1.7.3-py311hd43f75c_0.conda. However, when I run my tuning program, I encounter the error mentioned in the title. I am using PyTorch 2.0.0, TVM 0.14.0, and Python 3.11. All these projects are compiled in an aarch64 environment.

**Comment by trivialfis** [comment]
XGBoost doesn't use jemalloc. I don't think the error is related to XGBoost

**Comment by trivialfis** [comment]
Feel free to reopen if there's further info.
