### ISSUE TITLE
Running xgb.cv multithreaded causes Semaphore type handles to grow indefinitely

### ISSUE THREAD

**Issue by miguelbiron** [dmlc/xgboost#1013]
Hi,

First of all, thank you for building such a great ML tool. It's really awesome.

I'm currently running XGBoost R Package on Windows 7 64-bit. I'm using a grid search to tune the  hyperparameters, and for this I use `xgb.cv` inside a for loop. The problem is that, when I run this multithreaded, the process eventually hangs because it reaches the maximum number of handles of about 16.7 million. I investigated further and found out that those handles are of type Semaphore.

The issue disappears when I run this single-threaded (`nthread = 1`).

Below is an incomplete copy of the code I'm using.

Thank you.

```
for (i in 1:max_configs){
  cat(paste("\nFitting configuration", i, "\n"))
  temp = xgb.cv(data = as.matrix(subset(bal_train, select = -TARGET)),
                label = bal_train$TARGET,
                params = c(param, as.list(xgb_grid[i, ])),
                folds = folds_id,
                nrounds = 20000,
                verbose = 0,
                early.stop.round = estop,
                nthread = 4)

  nb_rounds[i] = length(temp$test.auc.mean) - estop
  auc_score[i] = temp$test.auc.mean[nb_rounds[i]]
  rm(temp)

  best_auc = max(auc_score[i], best_auc)
  cat(paste("\nBest AUC found so far:", best_auc))

}
```

**Comment by tqchen** [comment]
Seems have something to do with openmp not recycling resources in windows. But I am not entirely sure

@thirdwing Do you know anything related?

**Comment by thirdwing** [comment]
Just make sure one point. The CRAN version has OpenMP support, or user need to compile by themselves?

**Comment by tqchen** [comment]
CRAN also comes with openMP

**Comment by thirdwing** [comment]
Just to make which version of MinGW used. I will take a look.

On Sun, Mar 20, 2016 at 2:21 PM, Tianqi Chen <notifications@github.com>
wrote:

> CRAN also comes with openMP
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/xgboost/issues/1013#issuecomment-198979215>
>



-- 
Qiang Kou
qkou@umail.iu.edu
School of Informatics and Computing, Indiana University

**Comment by miguelbiron** [comment]
I don't know if this is useful, but I installed xgboost from the drat repo on 18/3/2016, and I'm using R 3.2.4 and RTools 3.3.

Best,
Miguel.

**Comment by thirdwing** [comment]
@miguelbiron Yes. I really need to know which compiler you are using.

Can you help to test it with Rtools 3.2?

**Comment by miguelbiron** [comment]
Sure, I'll do that tomorrow and let you know how it goes.

**Comment by miguelbiron** [comment]
@thirdwing same issue when compiling xgboost using RTools 3.2, handles keep exploding. I was checking and I believe that both RTools 3.2 and 3.3 use the same compiler (gcc 4.6.3).

**Comment by thirdwing** [comment]
OK. I will also let people who package the Rtools know about this.

**Comment by miguelbiron** [comment]
@thirdwing this also happens when running the code on a linux machine (Ubuntu 14.04 LTS, AWS EC2 instance). Although I don't know which is the exact equivalent to the semaphore handles of windows in unix, so I don't know what to measure.

**Comment by thirdwing** [comment]
Thank you for the test. I will look into it soon.
