### ISSUE TITLE
Model provides different results for different Python versions

### ISSUE THREAD

**Issue by Lks90a** [dmlc/xgboost#10141]
I have two python virtual environments, where just the Python version are different. I have the first with Python 3.7.9 and the second with Python 3.8. Xgboost 2.0.3 is installed on both, together with other libraries, all the same, the only difference is the python version.
For some reason, I'm having different predictions from the xgboost model when I train it on these different enviroments.
Already tried: set seed value to a fixed value (1), subsample to 1, colsample_bytree to 1.0, nthread to 1, and I keep getting different results for my models models in these two environments. I would appreciate if someone can bring some light in why this is happening.

**Comment by hcho3** [comment]
Hi, thank you for raising the issue. Could you please provide a reproducible example that I can run on my machine?

**Comment by trivialfis** [comment]
Feel free to reopen if there's further information.
