### ISSUE TITLE
[jvm-package] debian : java.lang.UnsatisfiedLinkError while running mvn package (ml.dmlc.xgboost4j.java.BoosterImplTest)

### ISSUE THREAD

**Issue by dnkamila** [dmlc/xgboost#1015]
I'm following installation step from [https://xgboost.readthedocs.org/en/latest/build.html](url). It's fine until "make -j4" step, but when running "mvn package" in folder xgboost/jvm-package, I got the following error

![selection_001](https://cloud.githubusercontent.com/assets/6870963/13904275/715416c6-eecd-11e5-9856-791b578a2cbc.png)

I'm already done the installation on ubuntu 14 and works fine. I don't know why it got the error above when running on debian 8

NB : I got warning message "setting local failed" when clonning from github, but I think it's not affect the installation, is it?

**Comment by CodingCat** [comment]
can you post more log here?

**Comment by CodingCat** [comment]
I mean not just the part containing errors but the part before the errors appear, from the current screenshot, I think the native library is not successfully built....

**Comment by dnkamila** [comment]
Hum, maybe here the error of native library

![selection_002](https://cloud.githubusercontent.com/assets/6870963/13904336/9ab234b0-eecf-11e5-8516-452192b5c9a2.png)

**Comment by dnkamila** [comment]
Here the full log from running "mvn package"

[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for ml.dmlc:xgboost4j:jar:0.5
[WARNING] 'build.plugins.plugin.version' for org.codehaus.mojo:exec-maven-plugin is missing. @ line 32, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] xgboost-jvm
[INFO] xgboost4j
[INFO] xgboost4j-spark
[INFO] xgboost4j-flink
[INFO] xgboost4j-example
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building xgboost-jvm 0.5
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- scalastyle-maven-plugin:0.8.0:check (checkstyle) @ xgboost-jvm ---
[WARNING] sourceDirectory is not specified or does not exist value=/home/kamila.dini/development/xgboost/jvm-packages/src/main/scala
[WARNING] testSourceDirectory is not specified or does not exist value=/home/kamila.dini/development/xgboost/jvm-packages/src/test/scala
Processed 0 file(s)
Found 0 errors
Found 0 warnings
Found 0 infos
Finished in 113 ms
[INFO] 
[INFO] --- maven-checkstyle-plugin:2.17:check (checkstyle) @ xgboost-jvm ---
[INFO] 
[INFO] --- scala-maven-plugin:3.2.2:compile (default) @ xgboost-jvm ---
[WARNING]  Expected all dependencies to require Scala version: 2.10.5
[WARNING]  ml.dmlc:xgboost-jvm:0.5 requires scala version: 2.10.5
[WARNING]  org.scala-lang:scala-compiler:2.10.5 requires scala version: 2.10.5
[WARNING]  org.scala-lang:scala-reflect:2.10.5 requires scala version: 2.10.5
[WARNING]  ml.dmlc:xgboost-jvm:0.5 requires scala version: 2.10.5
[WARNING]  org.scalatest:scalatest_2.10:2.2.6 requires scala version: 2.10.6
[WARNING] Multiple versions of scala libraries detected!
[INFO] No sources to compile
[INFO] 
[INFO] --- scala-maven-plugin:3.2.2:compile (compile) @ xgboost-jvm ---
[WARNING]  Expected all dependencies to require Scala version: 2.10.5
[WARNING]  ml.dmlc:xgboost-jvm:0.5 requires scala version: 2.10.5
[WARNING]  org.scala-lang:scala-compiler:2.10.5 requires scala version: 2.10.5
[WARNING]  org.scala-lang:scala-reflect:2.10.5 requires scala version: 2.10.5
[WARNING]  ml.dmlc:xgboost-jvm:0.5 requires scala version: 2.10.5
[WARNING]  org.scalatest:scalatest_2.10:2.2.6 requires scala version: 2.10.6
[WARNING] Multiple versions of scala libraries detected!
[INFO] No sources to compile
[INFO] 
[INFO] --- scala-maven-plugin:3.2.2:testCompile (test-compile) @ xgboost-jvm ---
[WARNING]  Expected all dependencies to require Scala version: 2.10.5
[WARNING]  ml.dmlc:xgboost-jvm:0.5 requires scala version: 2.10.5
[WARNING]  org.scala-lang:scala-compiler:2.10.5 requires scala version: 2.10.5
[WARNING]  org.scala-lang:scala-reflect:2.10.5 requires scala version: 2.10.5
[WARNING]  ml.dmlc:xgboost-jvm:0.5 requires scala version: 2.10.5
[WARNING]  org.scalatest:scalatest_2.10:2.2.6 requires scala version: 2.10.6
[WARNING] Multiple versions of scala libraries detected!
[INFO] No sources to compile
[INFO] 
[INFO] --- scalatest-maven-plugin:1.0:test (test) @ xgboost-jvm ---
Discovery starting.
Discovery completed in 47 milliseconds.
Run starting. Expected test count is: 0
DiscoverySuite:
Run completed in 160 milliseconds.
Total number of tests run: 0
Suites: completed 1, aborted 0
Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
No tests were executed.
[INFO] 
[INFO] --- maven-assembly-plugin:2.6:single (make-assembly) @ xgboost-jvm ---
[INFO] Assemblies have been skipped per configuration of the skipAssembly parameter.
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building xgboost4j 0.5
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- scalastyle-maven-plugin:0.8.0:check (checkstyle) @ xgboost4j ---
Processed 7 file(s)
Found 0 errors
Found 0 warnings
Found 0 infos
Finished in 773 ms
[INFO] 
[INFO] --- maven-checkstyle-plugin:2.17:check (checkstyle) @ xgboost4j ---
[INFO] 
[INFO] --- exec-maven-plugin:1.4.0:exec (native) @ xgboost4j ---
build java wrapper
g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -I/usr/local/jdk1.8/include -I./java -I/usr/local/jdk1.8/include/linux -shared -o jvm-packages/lib/libxgboost4j.so jvm-packages/xgboost4j/src/native/xgboost4j.cpp build/logging.o build/learner.o build/common/common.o build/metric/metric.o build/metric/rank_metric.o build/metric/elementwise_metric.o build/metric/multiclass_metric.o build/objective/multiclass_obj.o build/objective/objective.o build/objective/rank_obj.o build/objective/regression_obj.o build/data/sparse_page_dmatrix.o build/data/sparse_page_source.o build/data/sparse_page_writer.o build/data/simple_csr_source.o build/data/data.o build/data/sparse_page_raw_format.o build/data/simple_dmatrix.o build/tree/updater_prune.o build/tree/tree_updater.o build/tree/updater_histmaker.o build/tree/updater_refresh.o build/tree/updater_sync.o build/tree/updater_skmaker.o build/tree/updater_colmaker.o build/tree/tree_model.o build/gbm/gbtree.o build/gbm/gblinear.o build/gbm/gbm.o build/c_api/c_api.o build/c_api/c_api_error.o dmlc-core/libdmlc.a rabit/lib/librabit.a -pthread -lm  -fopenmp -lrt  -lrt
jvm-packages/xgboost4j/src/native/xgboost4j.cpp: In function ‘void setHandle(JNIEnv*, jlongArray, void*)’:
jvm-packages/xgboost4j/src/native/xgboost4j.cpp:27:47: error: no matching function for call to ‘JNIEnv_::SetLongArrayRegion(_jlongArray*&, int, int, long int*)’
   jenv->SetLongArrayRegion(jhandle, 0, 1, &out);
                                               ^
jvm-packages/xgboost4j/src/native/xgboost4j.cpp:27:47: note: candidate is:
In file included from jvm-packages/xgboost4j/src/native/./xgboost4j.h:2:0,
                 from jvm-packages/xgboost4j/src/native/xgboost4j.cpp:18:
/usr/local/jdk1.8/include/jni.h:1783:10: note: void JNIEnv_::SetLongArrayRegion(jlongArray, jsize, jsize, const jlong*)
     void SetLongArrayRegion(jlongArray array, jsize start, jsize len,
          ^
/usr/local/jdk1.8/include/jni.h:1783:10: note:   no known conversion for argument 4 from ‘long int*’ to ‘const jlong* {aka const long long int*}’
jvm-packages/xgboost4j/src/native/xgboost4j.cpp: In function ‘int XGBoost4jCallbackDataIterNext(DataIterHandle, int (*)(DataHolderHandle, XGBoostBatchCSR), DataHolderHandle)’:
jvm-packages/xgboost4j/src/native/xgboost4j.cpp:74:21: error: cannot convert ‘jlong* {aka long long int*}’ to ‘long int*’ in assignment
       cbatch.offset = jenv->GetLongArrayElements(joffset, 0);
                     ^
jvm-packages/xgboost4j/src/native/xgboost4j.cpp:100:63: error: no matching function for call to ‘JNIEnv_::ReleaseLongArrayElements(_jlongArray*&, long int*&, int)’
       jenv->ReleaseLongArrayElements(joffset, cbatch.offset, 0);
                                                               ^
jvm-packages/xgboost4j/src/native/xgboost4j.cpp:100:63: note: candidate is:
In file included from jvm-packages/xgboost4j/src/native/./xgboost4j.h:2:0,
                 from jvm-packages/xgboost4j/src/native/xgboost4j.cpp:18:
/usr/local/jdk1.8/include/jni.h:1714:10: note: void JNIEnv_::ReleaseLongArrayElements(jlongArray, jlong*, jint)
     void ReleaseLongArrayElements(jlongArray array,
          ^
/usr/local/jdk1.8/include/jni.h:1714:10: note:   no known conversion for argument 2 from ‘long int*’ to ‘jlong* {aka long long int*}’
Makefile:124: recipe for target 'jvm-packages/lib/libxgboost4j.so' failed
make: *** [jvm-packages/lib/libxgboost4j.so] Error 1
move native lib
mv: cannot stat 'lib/libxgboost4j.so': No such file or directory
complete
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ xgboost4j ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- scala-maven-plugin:3.2.2:compile (default) @ xgboost4j ---
[WARNING]  Expected all dependencies to require Scala version: 2.10.5
[WARNING]  ml.dmlc:xgboost4j:0.5 requires scala version: 2.10.5
[WARNING]  org.scala-lang:scala-compiler:2.10.5 requires scala version: 2.10.5
[WARNING]  org.scala-lang:scala-reflect:2.10.5 requires scala version: 2.10.5
[WARNING]  ml.dmlc:xgboost4j:0.5 requires scala version: 2.10.5
[WARNING]  org.scalatest:scalatest_2.10:2.2.6 requires scala version: 2.10.6
[WARNING] Multiple versions of scala libraries detected!
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ xgboost4j ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- scala-maven-plugin:3.2.2:compile (compile) @ xgboost4j ---
[WARNING]  Expected all dependencies to require Scala version: 2.10.5
[WARNING]  ml.dmlc:xgboost4j:0.5 requires scala version: 2.10.5
[WARNING]  org.scala-lang:scala-compiler:2.10.5 requires scala version: 2.10.5
[WARNING]  org.scala-lang:scala-reflect:2.10.5 requires scala version: 2.10.5
[WARNING]  ml.dmlc:xgboost4j:0.5 requires scala version: 2.10.5
[WARNING]  org.scalatest:scalatest_2.10:2.2.6 requires scala version: 2.10.6
[WARNING] Multiple versions of scala libraries detected!
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ xgboost4j ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/kamila.dini/development/xgboost/jvm-packages/xgboost4j/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ xgboost4j ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- scala-maven-plugin:3.2.2:testCompile (test-compile) @ xgboost4j ---
[WARNING]  Expected all dependencies to require Scala version: 2.10.5
[WARNING]  ml.dmlc:xgboost4j:0.5 requires scala version: 2.10.5
[WARNING]  org.scala-lang:scala-compiler:2.10.5 requires scala version: 2.10.5
[WARNING]  org.scala-lang:scala-reflect:2.10.5 requires scala version: 2.10.5
[WARNING]  ml.dmlc:xgboost4j:0.5 requires scala version: 2.10.5
[WARNING]  org.scalatest:scalatest_2.10:2.2.6 requires scala version: 2.10.6
[WARNING] Multiple versions of scala libraries detected!
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ xgboost4j ---

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running ml.dmlc.xgboost4j.java.BoosterImplTest
Mar 20, 2016 7:12:32 PM ml.dmlc.xgboost4j.java.NativeLibLoader smartLoad
SEVERE: failed to load library from both native path and jar
Mar 20, 2016 7:12:32 PM ml.dmlc.xgboost4j.java.DMatrix <clinit>
SEVERE: load native library failed.
Mar 20, 2016 7:12:32 PM ml.dmlc.xgboost4j.java.DMatrix <clinit>
SEVERE: java.io.FileNotFoundException: File /lib/libxgboost4j.so was not found inside JAR.
Tests run: 4, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 0.102 sec <<< FAILURE! - in ml.dmlc.xgboost4j.java.BoosterImplTest
saveLoadModelWithPath(ml.dmlc.xgboost4j.java.BoosterImplTest)  Time elapsed: 0.068 sec  <<< ERROR!
java.lang.UnsatisfiedLinkError: ml.dmlc.xgboost4j.java.XGBoostJNI.XGDMatrixCreateFromFile(Ljava/lang/String;I[J)I
	at ml.dmlc.xgboost4j.java.BoosterImplTest.saveLoadModelWithPath(BoosterImplTest.java:119)

testCV(ml.dmlc.xgboost4j.java.BoosterImplTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.UnsatisfiedLinkError: ml.dmlc.xgboost4j.java.XGBoostJNI.XGDMatrixCreateFromFile(Ljava/lang/String;I[J)I
	at ml.dmlc.xgboost4j.java.BoosterImplTest.testCV(BoosterImplTest.java:162)

testBoosterBasic(ml.dmlc.xgboost4j.java.BoosterImplTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.UnsatisfiedLinkError: ml.dmlc.xgboost4j.java.XGBoostJNI.XGDMatrixCreateFromFile(Ljava/lang/String;I[J)I
	at ml.dmlc.xgboost4j.java.BoosterImplTest.testBoosterBasic(BoosterImplTest.java:103)

saveLoadModelWithStream(ml.dmlc.xgboost4j.java.BoosterImplTest)  Time elapsed: 0.001 sec  <<< ERROR!
java.lang.UnsatisfiedLinkError: ml.dmlc.xgboost4j.java.XGBoostJNI.XGDMatrixCreateFromFile(Ljava/lang/String;I[J)I
	at ml.dmlc.xgboost4j.java.BoosterImplTest.saveLoadModelWithStream(BoosterImplTest.java:137)

Running ml.dmlc.xgboost4j.java.DMatrixTest
Tests run: 4, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 0.002 sec <<< FAILURE! - in ml.dmlc.xgboost4j.java.DMatrixTest
testCreateFromFile(ml.dmlc.xgboost4j.java.DMatrixTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.UnsatisfiedLinkError: ml.dmlc.xgboost4j.java.XGBoostJNI.XGDMatrixCreateFromFile(Ljava/lang/String;I[J)I
	at ml.dmlc.xgboost4j.java.DMatrixTest.testCreateFromFile(DMatrixTest.java:60)

testCreateFromDataIterator(ml.dmlc.xgboost4j.java.DMatrixTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.UnsatisfiedLinkError: ml.dmlc.xgboost4j.java.XGBoostJNI.XGDMatrixCreateFromDataIter(Ljava/util/Iterator;Ljava/lang/String;[J)I
	at ml.dmlc.xgboost4j.java.DMatrixTest.testCreateFromDataIterator(DMatrixTest.java:49)

testCreateFromDenseMatrix(ml.dmlc.xgboost4j.java.DMatrixTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.UnsatisfiedLinkError: ml.dmlc.xgboost4j.java.XGBoostJNI.XGDMatrixCreateFromMat([FIIF[J)I
	at ml.dmlc.xgboost4j.java.DMatrixTest.testCreateFromDenseMatrix(DMatrixTest.java:112)

testCreateFromCSR(ml.dmlc.xgboost4j.java.DMatrixTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.UnsatisfiedLinkError: ml.dmlc.xgboost4j.java.XGBoostJNI.XGDMatrixCreateFromCSR([J[I[F[J)I
	at ml.dmlc.xgboost4j.java.DMatrixTest.testCreateFromCSR(DMatrixTest.java:84)


Results :

Tests in error: 
  BoosterImplTest.saveLoadModelWithPath:119 ? UnsatisfiedLink ml.dmlc.xgboost4j....
  BoosterImplTest.saveLoadModelWithStream:137 ? UnsatisfiedLink ml.dmlc.xgboost4...
  BoosterImplTest.testBoosterBasic:103 ? UnsatisfiedLink ml.dmlc.xgboost4j.java....
  BoosterImplTest.testCV:162 ? UnsatisfiedLink ml.dmlc.xgboost4j.java.XGBoostJNI...
  DMatrixTest.testCreateFromCSR:84 ? UnsatisfiedLink ml.dmlc.xgboost4j.java.XGBo...
  DMatrixTest.testCreateFromDataIterator:49 ? UnsatisfiedLink ml.dmlc.xgboost4j....
  DMatrixTest.testCreateFromDenseMatrix:112 ? UnsatisfiedLink ml.dmlc.xgboost4j....
  DMatrixTest.testCreateFromFile:60 ? UnsatisfiedLink ml.dmlc.xgboost4j.java.XGB...

Tests run: 8, Failures: 0, Errors: 8, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] xgboost-jvm ........................................ SUCCESS [  3.835 s]
[INFO] xgboost4j .......................................... FAILURE [  3.180 s]
[INFO] xgboost4j-spark .................................... SKIPPED
[INFO] xgboost4j-flink .................................... SKIPPED
[INFO] xgboost4j-example .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.253 s
[INFO] Finished at: 2016-03-20T19:12:32+07:00
[INFO] Final Memory: 20M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project xgboost4j: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/kamila.dini/development/xgboost/jvm-packages/xgboost4j/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :xgboost4j

**Comment by CodingCat** [comment]
would you check if your g++ version is >= 4.6 (4.8 is recommended)?

**Comment by dnkamila** [comment]
My g++ version is 4.9

![selection_003](https://cloud.githubusercontent.com/assets/6870963/13904351/07275440-eed0-11e5-8484-305914604429.png)

**Comment by dnkamila** [comment]
Should I use g++ 4.8?

**Comment by tqchen** [comment]
Seems was due to different type in jni header which is a bit more strict. A quick solution is to switch oracle's JDK.  

If you you willing, we can also look into these errors, as they are mainly type mismatches that can be potentially. These errors are mainly due to pointer type definition mismatch, where most of them can simply get passed with force type conversion

**Comment by dnkamila** [comment]
@tqchen what do you mean by  "A quick solution is to switch oracle's JDK" and "force type conversion"? Should I change xgboost.cpp in xgboost/jvm-package/xgboost/src/native/xgboost.cpp which has conversion error?

**Comment by dnkamila** [comment]
Here the log from running ./xgboost/jvm-package/create_jni.sh

build java wrapper
g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -I/usr/local/jdk1.8/include -I./java -I/usr/local/jdk1.8/include/linux -shared -o jvm-packages/lib/libxgboost4j.so jvm-packages/xgboost4j/src/native/xgboost4j.cpp build/logging.o build/learner.o build/common/common.o build/metric/metric.o build/metric/rank_metric.o build/metric/elementwise_metric.o build/metric/multiclass_metric.o build/objective/multiclass_obj.o build/objective/objective.o build/objective/rank_obj.o build/objective/regression_obj.o build/data/sparse_page_dmatrix.o build/data/sparse_page_source.o build/data/sparse_page_writer.o build/data/simple_csr_source.o build/data/data.o build/data/sparse_page_raw_format.o build/data/simple_dmatrix.o build/tree/updater_prune.o build/tree/tree_updater.o build/tree/updater_histmaker.o build/tree/updater_refresh.o build/tree/updater_sync.o build/tree/updater_skmaker.o build/tree/updater_colmaker.o build/tree/tree_model.o build/gbm/gbtree.o build/gbm/gblinear.o build/gbm/gbm.o build/c_api/c_api.o build/c_api/c_api_error.o dmlc-core/libdmlc.a rabit/lib/librabit.a -pthread -lm  -fopenmp -lrt  -lrt
jvm-packages/xgboost4j/src/native/xgboost4j.cpp: In function ‘void setHandle(JNIEnv*, jlongArray, void*)’:
jvm-packages/xgboost4j/src/native/xgboost4j.cpp:27:47: error: no matching function for call to ‘JNIEnv_::SetLongArrayRegion(_jlongArray*&, int, int, long int*)’
   jenv->SetLongArrayRegion(jhandle, 0, 1, &out);
                                               ^
jvm-packages/xgboost4j/src/native/xgboost4j.cpp:27:47: note: candidate is:
In file included from jvm-packages/xgboost4j/src/native/./xgboost4j.h:2:0,
                 from jvm-packages/xgboost4j/src/native/xgboost4j.cpp:18:
/usr/local/jdk1.8/include/jni.h:1783:10: note: void JNIEnv_::SetLongArrayRegion(jlongArray, jsize, jsize, const jlong*)
     void SetLongArrayRegion(jlongArray array, jsize start, jsize len,
          ^
/usr/local/jdk1.8/include/jni.h:1783:10: note:   no known conversion for argument 4 from ‘long int*’ to ‘const jlong* {aka const long long int*}’
jvm-packages/xgboost4j/src/native/xgboost4j.cpp: In function ‘int XGBoost4jCallbackDataIterNext(DataIterHandle, int (*)(DataHolderHandle, XGBoostBatchCSR), DataHolderHandle)’:
jvm-packages/xgboost4j/src/native/xgboost4j.cpp:74:21: error: cannot convert ‘jlong* {aka long long int*}’ to ‘long int*’ in assignment
       cbatch.offset = jenv->GetLongArrayElements(joffset, 0);
                     ^
jvm-packages/xgboost4j/src/native/xgboost4j.cpp:100:63: error: no matching function for call to ‘JNIEnv_::ReleaseLongArrayElements(_jlongArray*&, long int*&, int)’
       jenv->ReleaseLongArrayElements(joffset, cbatch.offset, 0);
                                                               ^
jvm-packages/xgboost4j/src/native/xgboost4j.cpp:100:63: note: candidate is:
In file included from jvm-packages/xgboost4j/src/native/./xgboost4j.h:2:0,
                 from jvm-packages/xgboost4j/src/native/xgboost4j.cpp:18:
/usr/local/jdk1.8/include/jni.h:1714:10: note: void JNIEnv_::ReleaseLongArrayElements(jlongArray, jlong*, jint)
     void ReleaseLongArrayElements(jlongArray array,
          ^
/usr/local/jdk1.8/include/jni.h:1714:10: note:   no known conversion for argument 2 from ‘long int*’ to ‘jlong* {aka long long int*}’
Makefile:124: recipe for target 'jvm-packages/lib/libxgboost4j.so' failed
make: *** [jvm-packages/lib/libxgboost4j.so] Error 1
move native lib
mv: cannot stat 'lib/libxgboost4j.so': No such file or directory
complete

**Comment by dnkamila** [comment]
How do I convert "jlong" datatype in xgboost4j.cpp? There jlong and even jlongArray

**Comment by dnkamila** [comment]
Oh, and for your information, debian that I use is on 32 bit system

**Comment by CodingCat** [comment]
so...that is the problem....

**Comment by CodingCat** [comment]
@tqchen do we have any facilities to support 32-bits system?

**Comment by dnkamila** [comment]
So, is the case (64-bit system) happens to other language package (R and python)?

**Comment by tqchen** [comment]
@CodingCat Yes, this would requires a bit type tweaks. I will do that soon.

**Comment by dnkamila** [comment]
@tqchen @CodingCat  Thank you.. I will wait for that 32-bits system ^^

**Comment by dnkamila** [comment]
Hum, may I know when is the support for 32-bit system ready? Thanks in advance ^^ @CodingCat @tqchen
