### ISSUE TITLE
help installing xgboost with gpu

### ISSUE THREAD

**Issue by nipnipj** [dmlc/xgboost#10154]
Hello!
Is there a guide on how to install xgboost with gpu support? One that addresses its dependencies (such as cuda, nvcc, cmake) compatibility. 

I'm using linux mint 21.

**Comment by trivialfis** [comment]
- Install CUDA toolkit from https://developer.nvidia.com/cuda-downloads
- Install XGBoost using pip:
    + Create a virtual environment using Python: https://docs.python.org/3/library/venv.html
    + Install XGBoost in that environment: `pip install xgboost`.

**Comment by trivialfis** [comment]
Feel free to reopen if there are other questions.
