### ISSUE TITLE
[CI] Set up a nightly pipeline to test with dev versions of RAPIDS

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#10206]
Currently, XGBoost is tested with latest stable version of RAPIDS. As a result, the latest XGBoost may not be fully compatible with an upcoming version of RAPIDS. By the time RAPIDS releases a new version, it may end up packaging a version of XGBoost that's not fully compatible with the new RAPIDS version. See https://github.com/dmlc/xgboost/pull/10175 for an example.

We should set up a CI pipeline that tests XGBoost with development version of RAPIDS on a nightly basis.

**Comment by trivialfis** [comment]
Not entirely sure if we want to have nightly packages in the CI, we have very limited resources for handling sudden CI changes, maybe we need integration tests that are run before release instead of unit tests in CI?

**Comment by hcho3** [comment]
> issues can take time to resolve

I think it's better if we can find issues earlier rather than wait until the release.
