### ISSUE TITLE
Python package 'xgboost' is not installing on Window

### ISSUE THREAD

**Issue by viv1ag** [dmlc/xgboost#1022]
Please let me know how to rectify this issue:
![image](https://cloud.githubusercontent.com/assets/878291/13805866/ea744b14-eb7d-11e5-833d-c6f7c947375e.png)

When I am trying conda then following error is coming:
![image](https://cloud.githubusercontent.com/assets/878291/13805882/04ea4f02-eb7e-11e5-9027-9deb75ee0e23.png)

I have Window 7 Enterprises 64 bits, Python 2.7 & Anaconda 2 on my system.

**Comment by mrbeann** [comment]
Actually you can't install in this way.
see http://xgboost.readthedocs.org/en/latest/build.html

**Comment by viv1ag** [comment]
Can't we install without git? How?

**Comment by rdslater** [comment]
git is available for windows.
