### ISSUE TITLE
Tutorial on c-api distributed training of xgboost

### ISSUE THREAD

**Issue by limingyao100** [dmlc/xgboost#10223]
Due to work reasons, I hope to use xgboost's c-api to implement distributed training. However, after reading the tutorials, they are basically stand-alone versions or distributed versions that integrate ray and spark. What if I want to simply use c-api for distribution? Is there any relevant tutorial for this type of training?

**Comment by trivialfis** [comment]
No at the moment. It usually requires such frameworks for data and worker management.
