### ISSUE TITLE
Regression: ".weight" file support is broken

### ISSUE THREAD

**Issue by xb** [dmlc/xgboost#1023]
https://github.com/dmlc/xgboost/blame/c13570365541942f30539e33c6343026a3679fbf/doc/input_format.md#L34 says that the user could provide a ".weight" file when using the "xgboost" command line utility. However, it seems that this commit https://github.com/dmlc/xgboost/commit/46bcba7173b14202e3cee5c68fa718761ff6e9cc#diff-becff11c075385d91b299147cb1bd936L140 has killed the support for ".weight" files.

With the current head version, xgboost seems to produce the exact same result, with or without ".weight" files, which is not expected.

**Comment by pommedeterresautee** [comment]
Fixed
