### ISSUE TITLE
[jvm-package]how to dump model in test file  on xgboost spark platform?

### ISSUE THREAD

**Issue by leoli2012** [dmlc/xgboost#1024]
hi, for some reasons, i want know the model details(trees structure, leaf weigth...) after trainning,  i read the xgboost.scala.spark api, only found booster/predict/saveModelAsHadoopFile method, no dump model api.

**Comment by CodingCat** [comment]
http://dmlc.ml/docs/scaladocs/xgboost4j/index.html#ml.dmlc.xgboost4j.scala.Booster

you can call `XGBoostModel.booster` to get a `ml.dmlc.xgboost4j.scala.booster` instance 

then you can call `getModelDump` to dump model

**Comment by leoli2012** [comment]
@CodingCat , thanks for you help,i read this api, getModelDump(featureMap: String = null, withStats: Boolean = false),  not found how to dump a model as text file....however, i try to do in below way, but fail.
........
val numwork = 4
val gbdt_model = XGBoost.train(trainRDD, paramMap, numRound, nWorkers = numwork)
val boster = gbdt_model.booster
val model_dump = boster.getModelDump("/data/train_model_off_line_test_ctr/gbdt_model"), 
error log
include/dmlc/logging.h:245: [19:19:33] src/io/local_filesys.cc:149: Check failed: allow_null  LocalFileSystem: fail to open "/data/train_model_off_line_test_ctr/gbdt_model"
Exception in thread "main" ml.dmlc.xgboost4j.java.XGBoostError: [19:19:33] src/io/local_filesys.cc:149: Check failed: allow_null  LocalFileSystem: fail to open "/data/train_model_off_line_test_ctr/gbdt_model"

**Comment by alasdairtran** [comment]
The first parameter of `getModelDump ` is the path to the feature map, not the path to the model output. Assuming you don't have a feature map, set the first parameter to the default value of null. `getModelDump` will then return a string array. You can then save this array to disk.

**Comment by leoli2012** [comment]
@alasdairtran thanks.by the way, for the format of model dump file, i have a confuse about the tree struct ,could you like give me some advice?
0:[f7<11.1927] yes=1,no=2,missing=2
        1:[f13<11.6181] yes=3,no=4,missing=4
                3:leaf=-0.199531
                4:leaf=-0.0889432
        2:[f2<15.9937] yes=5,no=6,missing=6
                5:leaf=0.116667
                6:leaf=0.0666667
f7,f13...is the feature index? index number start from 0 or 1? what does the missing paramenter meaning?
