### ISSUE TITLE
Is the hessian right in multi:softprob?

### ISSUE THREAD

**Issue by SachaIZADI** [dmlc/xgboost#10258]
Hello,

I have a doubt about the factor `2.0f` in the hessian calculation for the `multi:softprob` objective
```
# src/objective/multiclass_obj.cu
const bst_float h = fmax(2.0f * p * (1.0f - p) * wt, eps);
```

I might be wrong but I believe the formula is just `const bst_float h = fmax(p * (1.0f - p) * wt, eps);` 

**Context:** I was playing around with `xgboost` ability to declare custom objective, and I tried to reimplement the `multi:softprob`.

- I compared my custom implementation in JAX (with autograd calculation) vs. the numpy implementation you provided in [this tutorial](https://github.com/dmlc/xgboost/blob/master/demo/guide-python/custom_softmax.py). The numpy implementation matches the source code in `src/objective/multiclass_obj.cu` 
- My JAX gradients are the same as in the numpy version, but my JAX hessian is always 2x smaller
- I might be missing something, bu I believe there's an error in the derivative of the gradients

Doign the derivative by hand I get the following:

```
# Definition of the gradients (so far so good)
target = labels[r]
p = softmax(predt[r, :])
grad[r, c] = p[r, c] - 1.0 if c == target else p[c]
# the gradient can be rewritten as:
grad[r, c] = p[r, c] - int(c == target)

# So taking the derivative (to get the hessian), via the chain rule gives:
∂grad[r, c] / ∂predt[r, c] =  (∂grad[r, c] / ∂p[r,c]) * (∂p[r, c] / ∂predt[r, c])
∂grad[r, c] / ∂predt[r, c] =  (∂{p[r, c] - int(c == target)} / ∂p[r,c]) * (∂{softmax(predt[r, :])[r,c]} / ∂predt[r, c])
# Softmax derivative : https://eli.thegreenplace.net/2016/the-softmax-function-and-its-derivative/
∂grad[r, c] / ∂predt[r, c] =  1.0 * (1.0 - p[r,c]) * p[r,c]

# V.S. the hessian in `multi:softprob` :
hess[r, c] = max((2.0 * p[c] * (1.0 - p[c]) * weights[r]).item(), eps)
```

Am I missing anything ?

Thanks a lot for your time, and thanks a lot for supporting this library that I'm using almost daily !!

**Comment by trivialfis** [comment]
It's an approximation to the Hessian with an upper bound on the error.

**Comment by SachaIZADI** [comment]
Thanks for your answer!

I know ([from the paper](https://arxiv.org/pdf/1603.02754)) that xgboost uses the diagonal of the hessian matrix (not the full matrix) to do a second-order Taylor approximation. 

But I believe that here you have an exact formula for the hessian values (without the `2.0f`), unless I'm missing anything?

**Comment by trivialfis** [comment]
I would like to write some document about this when other priorities are sorted out, for now, https://github.com/dmlc/xgboost/issues/10105 might be helpful

**Comment by SachaIZADI** [comment]
Thanks a lot for pointing to this similar issue. I'll close this one then!
