### ISSUE TITLE
XGBoost4j-spark Build fail because NPE

### ISSUE THREAD

**Issue by CrazyBinXXX** [dmlc/xgboost#10256]
Hello, recently I tried to build the xgboost-jvm locally, but was stucked "mvn package" in /jvm-package

Environment:
python 2.7
python3 3.11
java 1.8
spark 3.4.3

Code:
Master branch commit 9b465052cef6676090ff1dc2f9f8642a71d3bbc9

Reproduce:
1, Build Shared Library
2, cd jvm-packages, mvn package

Exception:
java.lang.NullPointerException
	at ml.dmlc.xgboost4j.java.RabitTracker.loadEnvs(RabitTracker.java:124)
	at ml.dmlc.xgboost4j.java.RabitTracker.startTrackerProcess(RabitTracker.java:176)
	at ml.dmlc.xgboost4j.java.RabitTracker.start(RabitTracker.java:197)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.startTracker(XGBoost.scala:493)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainDistributed(XGBoost.scala:526)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:210)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:34)

I have tried to print the log and found that "trackerProcess" is alive but "reader.readLine()" is null in "LoadEnvs" function. BTW I can successfully build if mvn -Dskiptests. Is there any step/dependency I skipped? Appreciate any advice!

**Comment by trivialfis** [comment]
Hi, could you please make sure python3 is the default Python?

**Comment by CrazyBinXXX** [comment]
Hi, I've tried to alias python=python3 and ensured that pythonExec is "python3" in "RabitTracker.java" but the exception still happened. I wonder does the code exec python in sudo mode? 

BTW I think python refers to python3 might be a little confusing. Shouldn't we replace "python" with "python3" in our .pom files and pythonExec default value?

**Comment by wbo4958** [comment]
@CrazyBinXXX, Can you hack startTrackerProcess to print the cmd in RabitTracker.java, and then run it in another terminal to see if it can work as expected?

``` scala
  private boolean startTrackerProcess() {
    try {
      String cmd = getRabitTrackerCommand();
      trackerProcess.set(Runtime.getRuntime().exec(cmd));
      loadEnvs(trackerProcess.get().getInputStream());
      return true;
    } catch (IOException ioe) {
      ioe.printStackTrace();
      return false;
    }
  }
```

**Comment by CrazyBinXXX** [comment]
Actually I've hacked it.

!!!!!!!!!!!!!!!!!BIN LOG!!!!!!!!!!!!!!!!!
python3  /var/folders/ql/ld6nvq6d02z974sl6y8p2t7m0000gn/T/tracker1198335420923130425.py  --log-level=DEBUG  --num-workers=2 
Process info: java.lang.UNIXProcess@2b62dddf
Process info: true
Process info: java.lang.UNIXProcess$ProcessPipeInputStream@6ecf25e
null

It seems to execute something in a temporary folder. I tried to execute it in another terminal and it gives me  "can't open file '/var/folders/ql/ld6nvq6d02z974sl6y8p2t7m0000gn/T/tracker1198335420923130425.py': [Errno 2] No such file or directory"

**Comment by wbo4958** [comment]
Try `python3 xgboost4j/src/main/resources/tracker.py --log-level=DEBUG --num-workers=2`

**Comment by wbo4958** [comment]
BTW, the recent PR https://github.com/dmlc/xgboost/pull/10112 will revise the whole Rabit part, where there will be no tracker.py anymore.

**Comment by CrazyBinXXX** [comment]
I finally solved it by a weird way --- running "cat /etc/hosts"

**Comment by wbo4958** [comment]
That's interesting.
