### ISSUE TITLE
xgboost 2.0.1 is breaking on rootless docker.

### ISSUE THREAD

**Issue by prafullat** [dmlc/xgboost#10250]
On rootless docker, path cgroup is readable only by root user.
![image](https://github.com/dmlc/xgboost/assets/63756/4b1703b4-af89-49b8-9555-f471e45f1796)

As such, if any non-root users even tries to import xgboost, it fails with permission error.
`Permission denied [/sys/fs/cgroup/cpu.max]`

Can you please check and avoid this error is this path is not accessible?
We are not able to use xgboost in the rootless docker container.

**Comment by hcho3** [comment]
@prafullat Can you post the full stack trace for the permission error?

**Comment by trivialfis** [comment]
Will try to reproduce once I get back to work. At the moment my guess is this line to be blamed https://github.com/dmlc/xgboost/blob/5e64276a9b95df57e6dd8f9e63347636f4e5d331/src/common/threading_utils.cc#L78

**Comment by trivialfis** [comment]
I have tried to launch an image with and without gosu, but couldn't reproduce the issue. @hcho3 might have more insight here.

**Comment by trivialfis** [comment]
Feel free to reopen if there is further information. Will try to fix it if there's a reproducer.

**Comment by zhangzzk** [comment]
I am having the exact issue with a non-root user importing the package:

`>>> import xgboost
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: status: Permission denied [/sys/fs/cgroup/cpu.max]
Aborted (core dumped)`

**Comment by trivialfis** [comment]
Could you please share how you installed docker (or any other environment)?

**Comment by zhangzzk** [comment]
Thank you for the quick reply.
Sorry I am a very beginner at this. I am a non-root user on a shared computing cluster and I am not the one setting up the environment. Could you perhaps give more specific instructions on the information I can provide?

**Comment by trivialfis** [comment]
> Could you perhaps give more specific instructions on the information I can provide?

Unfortunately, I want these instructions as well. ;-( Maybe you can share the result of `docker info` so that I can compare it with mine? @hcho3 might be able to provide more insights into the system setup.

**Comment by zhangzzk** [comment]
I think I am not running on a docker so `docker info` is not a valid command.

**Comment by trivialfis** [comment]
I will open a PR to catch all potential exceptions in that function.
