### ISSUE TITLE
Got Type Error when customize objective function.

### ISSUE THREAD

**Issue by Cai-SunShine** [dmlc/xgboost#10262]
Hi, I got some error when I customize my objective function. It is a multi-classification task, and I use a method named "sim loss" for this task.  My custom objective function is called `get_sim_grad_hessian`. When I run the `fit` process, it shows the error as `TypeError: only size-1 arrays can be converted to Python scalars`. 
I generate some mock data and I put my code below, you can directly run this.
```python
import numpy as np
import matplotlib.pyplot as plt
import xgboost as xgb
# define sim matrix
num_classes = 12
base,sim_ratio = 0.5, 0.3
sim_matrix = np.eye(num_classes)
for i in range(num_classes):
    for j in range(i + 1, num_classes):
        sim_matrix[i,j] = base**(np.abs(i-j)+1)

# this is my custom objective function, the return of this is 2 np.ndarray
def get_sim_grad_hessian(predt: np.ndarray, dtrain: xgb.DMatrix):
    """Compute the gradient of sim loss.

    Args:
        predt (np.ndarray): _description_
        dtrain (xgb.DMatrix): _description_

    Returns:
        Tuple of 2 np.ndarays: (grad, hessian)
        grad shape:(n_samples, n_classes)
        hessian shape:(n_samples, n_classes)
    """
    # if isinstance(dtrain,xgb.DMatrix):
    y = dtrain.get_label()
    
    num_classes = 12

    y = y.astype('int')
    y = np.eye(num_classes)[y]
    sample_nums = y.shape[0]
    proba = np.exp(predt)/np.sum(np.exp(predt)).reshape(-1,1)
    y_sim = y@sim_matrix
    grad = -y_sim + y_sim * proba

    hessian = np.zeros((sample_nums, num_classes))
    for i in range(sample_nums):
        tmp = np.diag(proba[i]) - np.matmul(proba[i].reshape(-1,1),proba[i].reshape(-1,1).T)
        tmp = y_sim[i].reshape(-1,1)*tmp
        hessian[i] = np.diagonal(tmp)
    # print(tmp.shape)
    print("grad shape:{}".format(grad.shape))
    print("hessian shape:{}".format(hessian.shape))
    return grad, hessian

# Next is my demo for test
n_samples = 1000
n_feats = 10
test_x = np.random.randn(n_samples,n_feats)
test_y = np.random.randint(0,num_class,n_samples)

predt = np.random.randn(n_samples,num_class)
proba = np.exp(predt)/np.sum(np.exp(predt)).reshape(-1,1)
y_sim = np.eye(num_class)[test_y]@sim_matrix

params = {'base_score':0.5,
            'booster':'gbtree',
            'learning_rate':0.01,
            'max_depth':3,
            'num_class':12}
num_round = 100
dtrain = xgb.DMatrix(test_x,label=test_y)

print("Training Model")
model_xgb_zone_3class_rssi = xgb.train(params, dtrain, num_round, obj = get_sim_grad_hessian)
```
It will occur error `TypeError: only size-1 arrays can be converted to Python scalars`. Are the shape of grad and hessian wrong? They are shape of `(n_samples, n_classes)`.  I don't know how to do, is there anyone can help me with that?
Thanks for reading my post!

**Comment by Cai-SunShine** [comment]
I found a demo for custom softmax [tutorial](https://github.com/dmlc/xgboost/blob/master/demo/guide-python/custom_softmax.py) in the xgboost official github, I run this script but also meet the same error `TypeError: only size-1 arrays can be converted to Python scalars`. My xgboost version is `1.7.6`.

**Comment by trivialfis** [comment]
HI, you are looking at the latest demo https://github.com/dmlc/xgboost/blob/f5882524814f2b0ce5df0a379ea3fc934acc624b/demo/guide-python/custom_softmax.py#L79 . Please refer to the document for versioned demo script https://xgboost.readthedocs.io/en/stable/python/examples/custom_softmax.html .

**Comment by SachaIZADI** [comment]
I had a similar issue, you need to `flatten` your gradient and hessian

**Comment by Cai-SunShine** [comment]
> HI, you are looking at the latest demo
> 
> https://github.com/dmlc/xgboost/blob/f5882524814f2b0ce5df0a379ea3fc934acc624b/demo/guide-python/custom_softmax.py#L79
> 
> . Please refer to the document for versioned demo script https://xgboost.readthedocs.io/en/stable/python/examples/custom_softmax.html .

Thanks! I solved this with the help of the link you recommend.

**Comment by Cai-SunShine** [comment]
> I had a similar issue, you need to `flatten` your gradient and hessian

Thanks for sharing😀
