### ISSUE TITLE
[python-package] DMatrix.get_float_info() throws "Unknown float field name"

### ISSUE THREAD

**Issue by libfun** [dmlc/xgboost#1026]
Hello,

I'm trying to write custom loss function of logloss with penalty, but I need to extract a feature vector from DMatrix in order to evaluate it. The problem is that I can not reach any feature inside DMatrix. Simple example is below:
```python
import numpy as np
import pandas as pd
import xgboost as xgb

df = pd.DataFrame(data=np.random.rand(100, 3), columns=['one', 'two', 'three'])
dm = xgb.DMatrix(df)
dm.get_float_info('one')
```
This code throws 
```
[16:59:20] dmlc-core/include/dmlc/./logging.h:241: [16:59:20] src/c_api/c_api.cc:299: Unknown float field name one
---------------------------------------------------------------------------
XGBoostError                              Traceback (most recent call last)
<ipython-input-6-24ff3999bcd2> in <module>()
----> 1 dm.get_float_info('one')

/home/libfun/vrt/lib/python3.4/site-packages/xgboost-0.4-py3.4.egg/xgboost/core.py in get_float_info(self, field)
    305                                                c_str(field),
    306                                                ctypes.byref(length),
--> 307                                                ctypes.byref(ret)))
    308         return ctypes2numpy(ret, length.value, np.float32)
    309 

/home/libfun/vrt/lib/python3.4/site-packages/xgboost-0.4-py3.4.egg/xgboost/core.py in _check_call(ret)
     95     """
     96     if ret != 0:
---> 97         raise XGBoostError(_LIB.XGBGetLastError())
     98 
     99 

XGBoostError: b'[16:59:20] src/c_api/c_api.cc:299: Unknown float field name one'
```

Even if you add explicit .set_float_info() it still throws same error:
```python
import numpy as np
import pandas as pd
import xgboost as xgb

df = pd.DataFrame(data=np.random.rand(100, 3), columns=['one', 'two', 'three'])
dm = xgb.DMatrix(df)
dm.set_float_info('one', df.one.values)
dm.get_float_info('one')
```

I'm using Python 3.4.3 with
numpy (1.10.4) 
pandas (0.18.0)
xgboost (0.4)

Xgboost is latest as of today - commit c13570365541942f30539e33c6343026a3679fbf.

**Comment by tqchen** [comment]
The float info is correctly restricted to DMatrix's meta information, namely label and weight

**Comment by tqchen** [comment]
One way to by pass this is simply use a closure so it sees the information you need

**Comment by libfun** [comment]
Could you please elaborate on how I can do this or point me in a right direction?

Thank you.

**Comment by tqchen** [comment]
```python
def get_loss(info):
    def myloss_function(pred, dmat):
        return pred - info,label
   return myloss_function


xgb.train(..., fobj = get_loss(info)
```

**Comment by libfun** [comment]
Thank you.

But am I able to use subsample < 1. with this solution? On each step pred vector will be shorter than info vector.

**Comment by tqchen** [comment]
yes, row subsampling actually do not really subsample the row data, but instead do the full gradient computation and use subsample during construction time, as gradient calculation is not bottleneck

**Comment by tqchen** [comment]
However, it is likely you cannot use cross validation, because that involves subsetting DMatrix

**Comment by libfun** [comment]
Thank you for your help.

**Comment by KOLANICH** [comment]
Could you document such a behavior of DMatrix, please?
