### ISSUE TITLE
Distributed XGBoost

### ISSUE THREAD

**Issue by tqchen** [dmlc/xgboost#103]
I always want to scale xgboost up further. A beta version has been made in in the unity branch here

 https://github.com/tqchen/xgboost/tree/unity/multi-node 

It is ready for test! So I open this issue to record possible tests, personally as a student I do not have full scale data and resources to test the version, maybe will ask friends who are interested and have resources on more testing

**Comment by tqchen** [comment]
Now XGBoost is backed using rabit https://github.com/tqchen/rabit
A hadoop example can be found at https://github.com/tqchen/xgboost/tree/unity/multi-node/hadoop

**Comment by tqchen** [comment]
Distributed version is now in master

**Comment by hanchensu** [comment]
Hi tianqi, recently I've been reading your distributed xgboost code and I can't understand some details of calculating the cut points of the histogram(mainly the code in utils/quantile.h);
Can you give me some reference materials about your approximate histogram algorithm to study?

**Comment by tqchen** [comment]
The quantile sketch was based on a data structure that I developed and it is a new result that was  not  yet published. Since this was mainly a data structure, you can view it as a black box and understand why it was used in other parts of algorithm. If you are interested in the data structure, send me an email and I can share the manuscript privately.

**Comment by tqchen** [comment]
A YARN master is added, xgboost  can now run as YARN application
