### ISSUE TITLE
Is there any way to load Dmatrix faster?

### ISSUE THREAD

**Issue by vincentccc** [dmlc/xgboost#10308]
` 

    start_time = time.perf_counter()
    array = np.array([1043.0, 1.0, 66.0]).reshape(1, 3)
    end_time = time.perf_counter()
    print("numpy time:", end_time - start_time)
    d_single_instance = xgb.DMatrix(
        array,
        feature_names=bst.feature_names,
    )
    end_time = time.perf_counter()
    print("make dmat time:", end_time - start_time)
    model.predict(d_single_instance)
    end_time = time.perf_counter()
    latency = end_time - start_time
    latencies.append(latency)`

In this code, DMatrix cost above 10ms, but other part cost less than 1ms, is there any way to solve this problem?

**Comment by trivialfis** [comment]
You can bypass the construction of `DMatrix` by using `inplace_predict`.

**Comment by vincentccc** [comment]
> You can bypass the construction of `DMatrix` by using `inplace_predict`.

It works! Thanks very much !!

**Comment by vincentccc** [comment]
> You can bypass the construction of `DMatrix` by using `inplace_predict`.

 May i ask another question. How to do this in gpu version, I found that it will still cost a lot when I use GPU. Is there any recommendation  about how to solve that? （may something like zero copy?)

**Comment by trivialfis** [comment]
GPU is optimized for throughput instead of latency, if you are putting a single sample there it won't be fast.

**Comment by vincentccc** [comment]
> GPU is optimized for throughput instead of latency, if you are putting a single sample there it won't be fast.

Thanks for your time to reply. I test using gpu, single sample inference latency  is much better than cpu, about(0.6ms vs 0.016ms)，but I didn't found any inplace gpu memory api, is there any way to do that?

**Comment by trivialfis** [comment]
It's the same API, with the booster object set to use cuda:
``` python
booster.set_param({"device": "cuda"})
# Make sure data is on GPU, otherwise XGBoost can't work on it "inplace"
X = cupy.array(X)
# or
X = cudf.DataFrame(X)
booster.inplace_predict(X)
```

**Comment by vincentccc** [comment]
> It's the same API, with the booster object set to use cuda:
> 
> ```python
> booster.set_param({"device": "cuda"})
> # Make sure data is on GPU, otherwise XGBoost can't work on it "inplace"
> X = cupy.array(X)
> # or
> X = cudf.DataFrame(X)
> booster.inplace_predict(X)
> ```

Thanks a lot!

**Comment by vincentccc** [comment]
I found that inplace_predict cost more than just use predict in gpu, like 18ms in inplace api, predict(Dmatrix) cost 0.06ms

**Comment by vincentccc** [comment]
> It's the same API, with the booster object set to use cuda:
> 
> ```python
> booster.set_param({"device": "cuda"})
> # Make sure data is on GPU, otherwise XGBoost can't work on it "inplace"
> X = cupy.array(X)
> # or
> X = cudf.DataFrame(X)
> booster.inplace_predict(X)
> ```

booster.set_param({"device": "cuda"})
# Make sure data is on GPU, otherwise XGBoost can't work on it "inplace"
X = cupy.array(X)
# or
X = cudf.DataFrame(X)
booster.inplace_predict(X)

**Comment by vincentccc** [comment]
> It's the same API, with the booster object set to use cuda:
> 
> ```python
> booster.set_param({"device": "cuda"})
> # Make sure data is on GPU, otherwise XGBoost can't work on it "inplace"
> X = cupy.array(X)
> # or
> X = cudf.DataFrame(X)
> booster.inplace_predict(X)
> ```

I found that inplace_predict cost more than predict, like predict(DMatrix) 0.06ms , inplace_predict(CUPY) cost 18ms，is there any hints about that?

**Comment by trivialfis** [comment]
If you are using a single sample, the overhead is unlikely in the actual prediction. For a single sample prediction, CPU is probably faster.

**Comment by trivialfis** [comment]
Feel free to reopen if there are further questions.
