### ISSUE TITLE
Missing surefire report of xgboost4j-spark

### ISSUE THREAD

**Issue by CrazyBinXXX** [dmlc/xgboost#10316]
I was trying to build the jvm-packages and it succeeds. However, I found there is no surefire report for  xgboost4j-spark though I do find logs about running those tests with 'mvn package'. In addition, neither the SNAPSHOT-test.jar was produced. I wonder is that expected or there is something going wrong and I need to fix?

**Comment by trivialfis** [comment]
cc @wbo4958
