### ISSUE TITLE
Hang inside NCCL.

### ISSUE THREAD

**Issue by trivialfis** [dmlc/xgboost#10312]
https://buildkite.com/xgboost/xgboost-ci-multi-gpu/builds/5027#018f9e76-44ae-4979-bd6d-c9aa5e0a617d

We ran into something like this before we moved into process-based multi-GPU training. The issue appears to be back now we have thread-based tests again.

**Comment by trivialfis** [comment]
CUDA is not quite friendly to valgrind, need a different method to debug this.

**Comment by trivialfis** [comment]
Not exactly an XGBoost issue, but we still need a workaround.

**Comment by trivialfis** [comment]
The fix requires a kernel driver that supports CTK12.5+.

**Comment by hcho3** [comment]
@trivialfis Should we use CTK 12.5 in our CI ?

**Comment by trivialfis** [comment]
@hcho3 It can prevent a flaky CPP MGPU test timeout error. Please help update the MGPU test CI when you are available.
