### ISSUE TITLE
[R] Docs for function arguments format second paragraph as code block

### ISSUE THREAD

**Issue by david-cortes** [dmlc/xgboost#10329]
In a previous PR for R documentation: https://github.com/dmlc/xgboost/pull/9906

The roxygen options were changed to use markdown mode in all docs.

After this change, some docs that have multiple paragraphs are incorrectly putting everything beyond the first paragraph into a code section, such as argument `base_margin` in `xgb.DMatrix`:
https://github.com/dmlc/xgboost/blob/9def441e9a1afc6a1b4852f394399093dbcf976c/R-package/man/xgb.DMatrix.Rd#L99

Changing back to non-markdown mode solves the issue (e.g. by adding `@noMd`), but it's unfortunately not possible to do this only for one function argument, only for a whole .Rd file, so not sure how to solve this.

The affected files can be found by searching for something like this in the `man/` folder:
```
\if{html}{\out{<div class="sourceCode">}}\preformatted{
```

CC @mayer79

**Comment by mayer79** [comment]
IMHO we should continue switching to the modern style. I can dedicate more time into this, but some help would be greatly appreciated (sooo much docu...). 

Formatting issues like the one you have identified can be fixed, I am pretty sure.

**Comment by trivialfis** [comment]
>  but some help would be greatly appreciated

Feel free to ping me if there's anything I can help.

**Comment by mayer79** [comment]
Fixed in #10733.
