### ISSUE TITLE
[jvm-packages] why the libgomp.so.1 file used  in xgboost4j-spark 

### ISSUE THREAD

**Issue by leoli2012** [dmlc/xgboost#1033]
i builded xgboost4j-spark in a virtual machine, gcc version is 4.8, then i run spark jon on my spark cluster, gcc version is 4.1.2, but log messages show below error info~
18:42:20 WARN TaskSetManager: Lost task 2.0 in stage 8.0 (TID 801, 192.168.2.216): java.lang.UnsatisfiedLinkError: /tmp/libxgboost4j1061727375559164064.so: libgomp.so.1: cannot open shared object file: No such file or directory.
i checked my cluster machine, most of my  machines  os in cluster  lack of libgomp.so.1 file.This file is a c lib file...

**Comment by CodingCat** [comment]
so...what's your problem?

**Comment by CodingCat** [comment]
xgboost4j-spark relies on xgboost which is a native lib further relying on libgomp....so.........

**Comment by suvendurinku** [comment]
I had the similar issue . That is resolved once I install " gcc" on  spark cluster  i.e.  both on spark master and worker node. 
apt-get install -y gcc
OR
yumt install -y gcc
based on your linux  flavor.
