### ISSUE TITLE
[jvm-packages] : How to get confusion matrix from XGBoost.crossValidation

### ISSUE THREAD

**Issue by dnkamila** [dmlc/xgboost#1036]
I wonder if I could get confusion matrix from XGBoost.crossValidation, because this method only return evaluation history. In R, we could get prediction class so we could generate confusion matrix by calling confusionMatrix(y, xgb.cv$pred). How to do this in java?

**Comment by CodingCat** [comment]
@dnkamila this is not contained in XGBoost for now....you may want to look at other frameworks' implementation (like deeplearning4j, weka) and  grab their code for your usage......

**Comment by dnkamila** [comment]
@CodingCat But how about get the prediction label from XGBoost.crossValidation? Could I get it?

**Comment by dnkamila** [comment]
Is prediction label from XGBoost.crossValidation actually equal to prediction label from applying train dataset that used to generate Booster model from XGBoost.train?

**Comment by CodingCat** [comment]
unfortunately...no....

**Comment by dnkamila** [comment]
So, the conclusion is for now I couldn't get prediction label from XGBoost.crossValidation like xgb.cv$pred in R right?

**Comment by CodingCat** [comment]
unfortunately....yes...I will discuss with @tqchen to see if it is worth adding in....

**Comment by dnkamila** [comment]
Thanks.. Actually I want to get precision and recall from the result (prediction label) of cross validation

**Comment by tqchen** [comment]
We can add a callback function to enable user to record things they like, like prediction, or other things
