### ISSUE TITLE
Feature: C# package

### ISSUE THREAD

**Issue by breezy-badger** [dmlc/xgboost#10375]
Hi,

The existing C#/dotnet package PicNet/XGBoost.Net is no longer maintained (and has not been for some years): https://github.com/PicNet/XGBoost.Net/commit/28902d9a9dddb3bd09fdcc42aafa191e96f10f3e
and no alternatives to that package exists.

Is there any plans to make an official C#/dotnet package using the existing C++ bindings?

**Comment by trivialfis** [comment]
I don't think there's anyone working on it. Feel free to ping me if anyone wants to revise the interface.

**Comment by trivialfis** [comment]
I don't think we will have an official package in the main repo in the near future. For others who have developed such a package, feel free to add references to the document.
