### ISSUE TITLE
Update the default CTK to 12.4.

### ISSUE THREAD

**Issue by trivialfis** [dmlc/xgboost#10370]
It should be able to work on all CTK 12.x versions. However, do know that once the default CTK is upgraded to 12, xgboost won't work on CTK 11.x.

**Comment by hcho3** [comment]
Latest gRPC is not compatible with CUDA 11.8 (https://github.com/tensorflow/tensorflow/issues/63356). 

TODO: Upgrade gRPC while upgrading CUDA to 12.4.

**Comment by trivialfis** [comment]
@hcho3 How difficult do you think it would be to upgrade the CTK version? Is it possible to upgrade without solving https://github.com/dmlc/xgboost/issues/10400 first?
