### ISSUE TITLE
Compatibility with latest Dask

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#10379]
Currently, some of the unit tests fail with latest Dask (https://github.com/dmlc/xgboost/pull/10125).

For now we've pinned the Dask version to `2024.1.1`. We should find out what's causing the issue with the latest Dask and make a fix in either Dask or XGBoost.

**Comment by trivialfis** [comment]
Specifically, after training and run prediction, the prediction might hang or raise a cancelled error.

**Comment by crusaderky** [comment]
About the CancelledError, see my comment on https://github.com/dask/dask/issues/11179

**Comment by trivialfis** [comment]
Closing since we have removed the pin.
