### ISSUE TITLE
[jvm-package] How could I apply multiple evaluation function (including custom evaluation) in XGBoost.crossValidation

### ISSUE THREAD

**Issue by dnkamila** [dmlc/xgboost#1038]
I could apply multiple defined evaluation function in XGBoost.crossValidation with `String[] metrics = {"merror", "mlogloss"}`. But how if I want add my custom evaluation function too? So I get 3 evaluation function in a go of XGBoost.crossValidation (merror, mlogloss, my custom evaluation function). Is it possible?

**Comment by CodingCat** [comment]
If I understand your question correctly, you can extend `IEvaluation` interface , [example](https://github.com/dmlc/xgboost/blob/master/jvm-packages/xgboost4j-example/src/main/java/ml/dmlc/xgboost4j/java/example/CustomObjective.java)

**Comment by dnkamila** [comment]
No, I mean output multiple evaluation including custom evaluation. If I try `XGBoost.crossValidation(data, ..., metrics, null, eval)` It only ouput the custom evaluation function (eval). Is it possible to ouput metrics (error and logloss) and eval in the same time?

**Comment by CodingCat** [comment]
hmmmm......no....the current implementation only supports to output one of them....
