### ISSUE TITLE
Two question in binary_classification demo: about dump.nice.txt and evaluation message

### ISSUE THREAD

**Issue by tornadomeet** [dmlc/xgboost#1039]
hello, all,

 Because it's the first time which i use xgboost, so just learn the demo in [binary_classification](https://github.com/dmlc/xgboost/tree/master/demo/binary_classification), two questions here:  
1. Refer to the readme, when dump the model, dump.nice.txt is saved ofr easier understand because of usage of feature mapping featmap.txt, but in my experiment, the context of  dump.nice.txt and  dump.raw.txt are the same, why?  
2. The readme doc said, the messages for evaluation are printed into stderr, but  when i use `../../xgboost mushroom.conf 2> log.txt`, nothing saved in log.txt, all mesage is print out on the screen, so does the evaluation info really saved to stdeer?   

thanks~

**Comment by pommedeterresautee** [comment]
Bug related to an old version, closing.
