### ISSUE TITLE
How XGBoost sample_weights alternate the Gain function formula?

### ISSUE THREAD

**Issue by geogreko** [dmlc/xgboost#10393]
In the case of sample_weights, are gradients (gi,hi) multiplied by the sample_weights when calculating the Gain function (similar to the objective function #10297)? 

Like:
 g_i * case_weight_i, 
h_i * case_weight_i, 

for all gradients in the gain function below? 

![image](https://github.com/dmlc/xgboost/assets/76202645/29929112-eff3-4a01-bc58-67ea370cba0d)

Picture taken from  the 2016 paper ‘XGBoost: A Scalable Tree Boosting System’ (eq.7)

**Comment by trivialfis** [comment]
Yes, all sample gradient are multiplied by the weight.

**Comment by trivialfis** [comment]
Feel free to reopen if there are further questions
