### ISSUE TITLE
[jvm-package] the memory usage of xgboost is limit to executor-memory of spark?

### ISSUE THREAD

**Issue by futurecam** [dmlc/xgboost#1041]
Hello,
I'm trying to run the xgboost on spark cluster, it works well (both yarn-client and local),but i'm afraid of  the memory usage because of the JNI and python part.
What's the memory usage apply by JNI(C++) and python part compare to RDD store size?Does it limit to executor-memory set to  spark?

I have a test on local mode of spark(1.6), where the parameter set like below:
--verbose --master local   \
--class ml.dmlc.xgboost4j.scala.example.spark.DistTrainWithSpark \
--num-executors 1 \
--conf spark.storage.memoryFraction=0.6 \
--conf spark.shuffle.spill=true  \
--driver-memory 6g \
--executor-memory 2g \
--executor-cores 1 \

but i get about 10g memory usage when running,it's more than the sum of drive-memory and executor-memory
and the train file is only about 3g (i have omited the predict process so test file is not load to memory)

**Comment by CodingCat** [comment]
@futurecam the memory applied by python shall be trivial, most of memory pressure comes from C++, 

the memory is not equal to executor-memory (which is on-heap), but the off-heap part, defined by `spark.memory.offHeap.enabled` and `spark.memory.offHeap.size`

**Comment by CodingCat** [comment]
@futurecam , I just looked at Spark's implementation,  `spark.memory.offHeap.enabled` and `spark.memory.offHeap.size` are only referred in various sorter of Spark....so essentially you cannot specify JNI memory usage via Spark

**Comment by futurecam** [comment]
@CodingCat,  thanks for reply!
It' s there a method to estimate the memory allocate by C++ if I know the train RDD size?

when the application is running(and also export MALLOC_ARENA_MAX=4 ) at local,I trace the memory usage by pmap -x 24961|sort -n -k3
and I get :

00007f8cefdcb000   12292   12292   12292 rw---    [ anon ]
00007f8ce5587000   43492   18680   18680 rw---    [ anon ]
00007f8cf4000000   32912   28024   28024 rw---    [ anon ]
0000000670000000   54272   53836   53836 rw---    [ anon ]
00007f8cb9579000  171180  130960  130960 rw---    [ anon ]
00007f8bc377c000 2097156 1856016 1856016 rw---    [ anon ]
000000000127d000 1970168 1968984 1968984 rw---    [ anon ]
0000000680000000 6291456 5416960 5416960 rw---    [ anon ]
total kB        11692220 9551452 9515604

There are about 6g memory not in java heap,I guess it maybe used by C++
and the train RDD size is about 3g

so can I estimate the memory allocate by C++ by 2*sizeof(train RDD size) ?

**Comment by CodingCat** [comment]
I haven't get a chance to profile the memory usage with details...maybe you can check with more datasets?

**Comment by tqchen** [comment]
Yes, usually it is twice the size. We can try enable disk options later
which gets to bigger dataset size

**Comment by CodingCat** [comment]
In his case, it's actually 3x of training size(rdd+c++), i think the idea case is 2x, 

one of the explanations is that the transient conversion from spark data structure to xgboost ones takes some

**Comment by futurecam** [comment]
@CodingCat, yes,I will test different dataset and list the result here. I'm trying produce large dataset and it will take me some time.

**Comment by futurecam** [comment]
@tqchen, just as @CodingCat says : "it's actually 3x of training size(rdd+c++)"
I'm not quite sure "twice the size" is mean the size only apply by C++ or (rdd+C++)
and the "disk options" is the external memory version?

**Comment by tqchen** [comment]
Yes, disk option is the external memory version
