### ISSUE TITLE
Parameters in documentation for cv() nonexistent in python module

### ISSUE THREAD

**Issue by mxbi** [dmlc/xgboost#1044]
I'm trying to use xgboost.cv() to crossvalidate my parameters and it seems that some of the [parameters in the documentation](https://xgboost.readthedocs.org/en/latest/python/python_api.html#xgboost.cv) aren't working when I use them in my code.

Specifically, when I try using stratified folds for the crossvalidation, I get:

```
Traceback (most recent call last):
  File "xgb.py", line 103, in <module>
    seed=4242)
TypeError: cv() got an unexpected keyword argument 'stratified'
```

and when trying to use `verbose_eval` (setting it to `True` or `9` both produce this error):

```
Traceback (most recent call last):
  File "xgb.py", line 103, in <module>
    seed=4242)
TypeError: cv() got an unexpected keyword argument 'verbose_eval'

```

However, both of these appear in the documentation:

```
verbose_eval (bool, int, or None, default None) – Whether to display the progress. If None, progress will be displayed when np.ndarray is returned. If True, progress will be displayed at boosting stage. If an integer is given, progress will be displayed at every given verbose_eval boosting stage.
stratified (bool) – Perform stratified sampling.
```

I'm running Python 3.5.1 with Anaconda 2.5.0 and xgboost version 0.4, and here is my code:

```
params = {}
params["objective"] = "binary:logistic"
params["booster"] = "gbtree"
params["eval_metric"] = "auc"
params["eta"] = 0.02
params["max_depth"] = 5
params["subsample"] = 0.7
params["colsample_bytree"] = 0.4

d_train = xgb.DMatrix(x_train, label=y_train)
clf = xgb.cv(params, d_train, 
            num_boost_round=100000, 
            nfold=10, 
            stratified=True, # Returns error
            metrics="auc", 
            early_stopping_rounds=100,
            verbose_eval=True, # Returns error
            seed=4242)
```

Are these parameters not available in the code or am I using them wrong? Apologies if I'm writing this in the wrong place or if I'm missing something obvious.

Thanks in advance!

**Comment by crazy449** [comment]
I got the same issue...

**Comment by cuixue** [comment]
I got the same issue too....

**Comment by ChrisParry** [comment]
I have the same issue, but with the folds parameter. Oddly enough, the same code runs perfectly on my workstation, but fails on an EC2 instance.

**Comment by mxbi** [comment]
@Data-drone @cuixue @ChrisParry I found that by compiling from git source the issue no longer occurs - this is likely an issue with the build available from PyPI, or the build available from the releases page.

**Comment by shgidi** [comment]
same issue here, @mxbi  how do you build from git source?

**Comment by phoenixbai** [comment]
It is a version issue. stratified and verbose_eval parameters are not supported in 0.4 version, but seems to be added around Feb, 2016. So it is supported in later version like 0.6.

**Comment by sl2902** [comment]
As I have time-series data, I wanted to turn off shuffle in the xgboost.cv(), but I received the following error
```
    early_stopping_rounds=25, verbose_eval=10, show_stdv=True, shuffle=False)
TypeError: cv() got an unexpected keyword argument 'shuffle'
```

 I am using xgboost version 0.6. scikit-learn 0.19, and I am running on Ubuntu 0.16.04.3. Python version 3.5.4.

**Comment by cinqs** [comment]
the version release number should really be carefully dealt with.

as is in `master`  branch, the  [*VERSION* file](https://github.com/dmlc/xgboost/blob/master/python-package/xgboost/VERSION) still shows *0.6*, but if you look into this [file](https://github.com/dmlc/xgboost/blob/master/python-package/xgboost/training.py) of line **292**, the parameter of `cv` named *shuffle* is clearly there. 

So I guess here is the problem of you version release number problem. and you should re-push your package to *PYPI* again with a new release number.

For those who really want to use the new feature of shuffle. I have two options for you:

1. use *numpy* [shuffle](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.shuffle.html) instead

2. compile and install the *xgboost* in your local machine instead of waiting for their updates.
