### ISSUE TITLE
Docs for 'contributing' are missing section to run R linter

### ISSUE THREAD

**Issue by david-cortes** [dmlc/xgboost#10455]
There is a section in the docs for running formatters locally:
https://xgboost.readthedocs.io/en/stable/contrib/coding_guide.html#running-formatting-checks-locally

which has instructions for running the Python linter and the C++ linter, but it doesn't have instructions for running the R linter which is checked in the CI jobs.

It doesn't seem to be a simple matter of executing the file `tests/ci_build/lint_r.R`, since it requires command line arguments to run.

Would be ideal to have instructions there about how to run the R linter too.

**Comment by trivialfis** [comment]
Apologies for the lack of the document. For now, please use the github CI as a reference: https://github.com/dmlc/xgboost/blob/2b400b18d5d4719422ff1e37bfdb22a55cc1eb78/.github/workflows/r_tests.yml#L48
