### ISSUE TITLE
[R package] S4 and S3 class systems use

### ISSUE THREAD

**Issue by khotilov** [dmlc/xgboost#1045]
There seem to be some issues with how these R class systems are being used. The `xgb.DMatrix` and `xgb.Booster` are defined as virtual S4 classes. But the objects produced by `xgb.DMatrix()` and `xgb.Booster()` are in fact S3 objects, since they are not created with `new(...)` but with `structure(..., class='...')`. This leads to some awkward situations. E.g., non-primitive functions (e.g.,`nrow`) could be dispatched onto those objects using S4-style code (via some S3 byways, I guess), but the dispatch of primitive functions (e.g., `dim`) cannot be implemented S4-style.

Here are some possible options:

1. convert everything to S3 system (I think I would be able to do it fairly easily)
1. implement proper use of S4 system by defining non-virtual classes and all the S4 shenanigans (but is there any real need for this more complex approach?)
1. continue developing on the top of this mixture of S3 and rudimentary S4 (IMO, that would be a hack)

@hetong007: were there any reasons behind the choice to use S4, like any plans for more complex class hierarchies or implementing some restrictions?

**Comment by hetong007** [comment]
Hi @khotilov , thank you very much for the catch. I was trying to make it safer, but now I admit that S4 was too complex for xgboost so far. An S3 can work well.

It would be great if you could open a PR to convert everything to S3 system :)

**Comment by khotilov** [comment]
Closed by #1050
