### ISSUE TITLE
[jvm-package] java.net.BindException: Cannot assign requested address: Service 'sparkDriver' when running mvn package

### ISSUE THREAD

**Issue by dnkamila** [dmlc/xgboost#1046]
I got the following error when running `mvn package`

![jvm-package spark error](https://cloud.githubusercontent.com/assets/6870963/14059945/b96f8938-f385-11e5-83dd-fb333190dd41.PNG)

Here the summary from running `mvn package`
![summary mvn package](https://cloud.githubusercontent.com/assets/6870963/14059946/be3f1f14-f385-11e5-99bc-4118784de732.PNG)

echo $SPARK_HOME, $SPARK_LOCAL_IP, and $SPARK_MASTER_IP produce empty string. I set $SPARK_LOCAL_IP and $SPARK_MASTER_IP to 127.0.0.1 but It produce another error from above (multiple spark run in jvm)

What should I do about this?

Thanks in advance..

**Comment by CodingCat** [comment]
it seems that your port `404x` is occupied by other processes ? or you have some problems in binding to `127.0.0.1`?
