### ISSUE TITLE
Couldn't trigger a new build for read the doc on the stable branch.

### ISSUE THREAD

**Issue by trivialfis** [dmlc/xgboost#10470]
XGBoost uses tagged versions for releases, in which case RTD prefers tags over branch updates. Without making a new release, we can't update to fix the build issue on the stable branch.

This is a tracking issue for fixing the stable build on read the doc.

**Comment by hcho3** [comment]
@trivialfis We can manually create `stable` branch to point to the head of `release_2.1.0`: https://github.com/readthedocs/readthedocs.org/pull/5417

**Comment by hcho3** [comment]
The `stable` version is now fixed: https://xgboost.readthedocs.io/en/stable/index.html
