### ISSUE TITLE
pip install xgboost==2.1.0 failing on AWS Glue Jobs/Endpoints

### ISSUE THREAD

**Issue by brifordwylie** [dmlc/xgboost#10472]
Description of Issue:
- xgboost==2.0.3 works fine
- xgboost==2.1.0 fails on pip install for AWS Glue Jobs 

My info so far:
Looking at the logs, I can see that it can't find a matching wheel so tries to build xgboost from scratch, and fails on not finding cmake. So looking at the wheels for the two versions...

Wheels:
 2.0.3
- xgboost-2.0.3-py3-none-manylinux2014_x86_64.whl
- xgboost-2.0.3-py3-none-manylinux2014_aarch64.whl

2.1.0
-xgboost-2.1.0-py3-none-manylinux_2_28_x86_64.whl
Uploaded Jun 20, 2024 Python 3 manylinux: glibc 2.28+ x86-64

-xgboost-2.1.0-py3-none-manylinux_2_28_aarch64.whl
Uploaded Jun 20, 2024 Python 3 manylinux: glibc 2.28+ ARM64

So the wheels for 2.1.0 require at least glibc 2.28, and when I run this on my AWS Glue job..

```
import os, subprocess

# Print out the glibc version
result = subprocess.run(['ldd', '--version'], stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
print(f"GLIBC version:\n{result.stdout}")
```

I get this output:
```
GLIBC version:
ldd (GNU libc) 2.26
```

So, shrug, I think the answer might be that AWS needs to update their GLIBC version for their standard AWS Glue/Spark setup.  :)

**Update:** I've also noticed this will affect Serverless AWS Endpoints, this is a more significant issue as AWS Endpoint are suppose to 'just work' 24/7 and if they have an 'unlocked' dependency on xgboost, those endpoints will now fail.

**Comment by trivialfis** [comment]
cc @hcho3 is there a way to work around this by pushing a binary with older glibc? Or AWS glue is just an odd platform?

**Comment by hcho3** [comment]
@trivialfis Yes, we can work around the issue by publishing a `manylinux2014` wheel. Given that there are substantial number of machines running older versions of glibc (See https://github.com/microsoft/vscode/issues/203375), let's maintain `manylinux2014` wheel for one more year. I will post a new issue to keep track of the end date for `manylinux2014`.

**Comment by hcho3** [comment]
@brifordwylie We've uploaded a new binary targeting the old Linux distros. Please try again with `pip install xgboost`.
