### ISSUE TITLE
Handling Special Values 

### ISSUE THREAD

**Issue by mahishah19** [dmlc/xgboost#10473]
Hello, 
However, I've found myself having to handle the problem of having multiple special values different times recently. If there is one special value say missing values I am aware XGBoost can itnernally handle such cases. But what about cases where there is a NA, -2 & a -5. Now the -2 & -5 have no numerical importance, but they mean something like -2 means can not calculate and -5 means insufficient data, etc. Can Xgboost handle such cases or can we do something where it can identify all these cases and handle missing values correctly?

**Comment by trivialfis** [comment]
No, XGBoost handles a single missing value. You can convert all the values that don't make sense in model training to nan in data preprocessing.

**Comment by trivialfis** [comment]
On the other hand, if that's categorical feature, and you consider those special values are useful categories, then you can try to encode it and use the categorical split in XGBoost.

**Comment by mahishah19** [comment]
Hello Jiaming, 
Thank you for your prompt answer. 

What if it is a numerical feature? Where there are some normal values and some special values? Any ideas around that?

**Comment by trivialfis** [comment]
Then no, there's no special handling for these types of values. You can remove them from the dataset (the value, not the entire sample).

**Comment by trivialfis** [comment]
Feel free to reopen if there are further questions.
