### ISSUE TITLE
CUDA crashes when running XGBoost on Windows VM without GPU

### ISSUE THREAD

**Issue by JonathanHolvey** [dmlc/xgboost#10479]
When running almost any Python XGBoost function on a Windows virtual machine without a GPU, the CPython interpreter is crashed by a fault in the CUDA driver. For example:

```python
import xgboost as xgb
xgb.set_config()  # Interpreter crashes here
```

The Windows event log identifies nvcuda64.dll as the library behind the crash, but provides no further details that might help investigate the issue.

I've tried disabling GPU support in CUDA with the environment variable `CUDA_VISIBLE_DEVICES=''`, but this doesn't help.

### Environment

OS: Windows 11 22H2  
XGBoost version: 2.0.3  
Python version: 3.10  
CUDA version: 12.1
GPU device: Microsoft Remote Display Adapter

**Comment by hcho3** [comment]
@JonathanHolvey Do you have the same issue with XGBoost 2.1.0 ?

**Comment by hcho3** [comment]
> Windows virtual machine

Is this a VM in a public cloud, or a VM in a hypervisor such as VirtualBox ?

**Comment by JonathanHolvey** [comment]
Yeah I have the same issue with XGBoost 2.1.0.

The VM is an Azure Virtual Machine.

**Comment by hcho3** [comment]
I tried reproducing the error on my end and I could not reproduce it.

Can you look at my setup and see how it differs from yours?

* AWS EC2
* Windows Server 2019
* CUDA driver installed in the AMI (machine image), but no GPU provisioned to the VM (c5a.2xlarge)

**Comment by JonathanHolvey** [comment]
My setup looks essentially the same, except it's in Azure, and I'm running a different edition of Windows:

- Azure Virtual Machine
- Windows 11 22H2
- CUDA driver installed in the machine image, but no GPU provisioned to the VM (Standard_b2ms)

**Comment by hcho3** [comment]
I'm quite not sure how to proceed. For now, can you install XGBoost using Conda? Conda will let you install CPU-only XGBoost. See https://xgboost.readthedocs.io/en/stable/install.html#conda

**Comment by JonathanHolvey** [comment]
After additional testing, I think this issue is particular to the environment I'm using. I created a fresh VM of the same type, installed Python, CUDA and XGBoost, and I couldn't reproduce the issue. There must be some other software or config on the production machines that's breaking CUDA.

Because of this, I'm happy to close this issue.

**Comment by hcho3** [comment]
Great, feel free to file a new issue if any issue arises.
