### ISSUE TITLE
[RFC] Dropping GPU support in the Windows native build of XGBoost

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#10484]
Currently, when Windows users run `pip install xgboost`, they obtain a binary wheel with the code for GPU algorithms enabled.
We included the GPU code in the binary believing that its presence doesn't affect users who don't have GPUs. But there appear to be cases where the GPU code breaks on machines without GPUs. See #10479. Given the available human-hours of the core developers, I don't think we are able to perform sufficient troubleshooting to prevent similar cases.

**Proposal**. Drop the GPU support in the Windows native build of XGBoost. Users who wish to use GPU would be directed to use WSL2 instead. This proposal is in line with other GPU libraries such as RAPIDS.

I am opening this issue to gauge the number of people who use NVIDIA GPUs with the Windows native build of XGBoost.

@dmlc/xgboost-committer

**Comment by trivialfis** [comment]
I don't think it's necessary to drop GPU support on Windows because of one specific platform has an edge case.

**Comment by hcho3** [comment]
I will try installing XGBoost on a few more Windows machines and see if it's successful.

**Comment by hcho3** [comment]
I suppose we can keep the native support for now.
