### ISSUE TITLE
xgboost with sklearn "fit" function: does it initialize every time when I call "fit"?

### ISSUE THREAD

**Issue by maybeluo** [dmlc/xgboost#1052]
Thanks for such a wonderful tools. I use xgboost in SKlearn and use the "fit" function continuously like this:
xgb = XGBClassifier(**param_list)
xgb.fit(dtrain)  # 1
xgb.fit(dvalid) # 2

Does the "fit" function in the # 2 trained based on the # 1, or every time I call "fit", the xgb just random initializes? I prefer the latter after taking a look at the source code, but I'm not sure.

Thanks.

**Comment by pommedeterresautee** [comment]
Bug related to an old version, closing.
