### ISSUE TITLE
New warning on CRAN.

### ISSUE THREAD

**Issue by trivialfis** [dmlc/xgboost#10545]
https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-gcc/xgboost-00check.html

The warning must be addressed before Aug 03.

**Comment by jameslamb** [comment]
I was just looking at this, there is that one:

```text
Result: WARN 
  Found the following significant warnings:
    ./include/xgboost/parameter.h:56:24: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
  See ‘/data/gannet/ripley/R/packages/tests-devel/xgboost.Rcheck/00install.out’ for details.
  * used C compiler: ‘gcc-14 (GCC) 14.1.0’
  * used C++ compiler: ‘g++-14 (GCC) 14.1.0’
```

But also these using `icc`:

```text
* checking whether package ‘xgboost’ can be installed ... [12m/16m] WARNING
Found the following significant warnings:
  /usr/lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/stl_tempbuf.h:263:8: warning: 'get_temporary_buffer<unsigned long>' is deprecated [-Wdeprecated-declarations]
  /usr/lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/stl_tempbuf.h:263:8: warning: 'get_temporary_buffer<std::pair<float, unsigned int>>' is deprecated [-Wdeprecated-declarations]
  /usr/lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/stl_tempbuf.h:263:8: warning: 'get_temporary_buffer<float>' is deprecated [-Wdeprecated-declarations]
  /usr/lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/stl_tempbuf.h:263:8: warning: 'get_temporary_buffer<xgboost::obj::ListEntry>' is deprecated [-Wdeprecated-declarations]
```

references:

* full list of check results: https://cran.r-project.org/web/checks/check_results_xgboost.html
* install: https://www.stats.ox.ac.uk/pub/bdr/Intel/xgboost.log
* `R CMD check`: https://www.stats.ox.ac.uk/pub/bdr/Intel/xgboost.out

**Comment by jameslamb** [comment]
For `{lightgbm}`, we received a similar warning from CRAN about template IDs in constructors.

I had success tonight replicating those in CI using the new container images from rhub:

* https://github.com/microsoft/LightGBM/pull/6523
* https://r-hub.github.io/containers/

**Comment by trivialfis** [comment]
Addressed in https://github.com/dmlc/xgboost/pull/9980 , will backport.

**Comment by trivialfis** [comment]
The checks for the patch release is on-going now: https://cran.r-project.org/web/checks/check_results_xgboost.html Closing this issue. The patch release includes:
- A part of https://github.com/dmlc/xgboost/pull/10465 .
- https://github.com/dmlc/xgboost/pull/9980

Thank you @jameslamb for sharing the test results, excellent that r-hub has a gcc trunk container.
