### ISSUE TITLE
Rebuilding Xgboost with Less Variables

### ISSUE THREAD

**Issue by DeluxeAnalyst** [dmlc/xgboost#1055]
I am running into a situation with xgboost I was hoping I could get some help on. 

It seems that when an xgboost model is built, it remembers the variable number (the variable position in the dataset) rather than remembering the variable name. If I were to build an xgboost model with 20 variables, but the algorithm only used 7 variables, it would remember those 7 variables as a function of the 20. For example, looking at the variable importance without feature names would yield something like this: Variable1, Variable18, Variable7, Variable 5, Variable20, Variable11, Variable15. 

When trying to predict with xgboost, the variables need to be in the same order as when the model was built, and all 20 must be present, even though the model only uses 7 because it appears that it just looks at the variables used in the model, and then grabs the correspond column number from the predicting data set. 

Is there a way around this, such that xgboost remembers the variable names instead of the position #? 

I find myself when scoring future data to only want to grab the variables the model actually uses, for example 30, rather than the full 900 I built the model with.

Hope this makes sense.

Thanks,

Nate

**Comment by DeluxeAnalyst** [comment]
Just an additional comment, I was able to find a workaround for this. 

Given my above example, I fed xgboost 20 variables, and it gave me a model using only 7 variables. 

I now have a new file of new data that only contains the 7 variables. My workaround was to manually create a blank file with 20 rows, and then populate the 7 columns worth of data based on the original positioning from when the model was built.

**Comment by DeluxeAnalyst** [comment]
Have there been any new features that solve this issue yet?

**Comment by pommedeterresautee** [comment]
There is no such feature and your workaround seems to be the best. In sparse matrix it costs you nothing.

**Comment by khotilov** [comment]
Another option is to refit a model with only the used features. It might result in a slightly different model, but in practice that shouldn't really matter.

It might be nice though to have an API method for trimming unused features from a model and returning indices of used ones.

**Comment by DeluxeAnalyst** [comment]
It would be nice if this could get added to some sort of a future improvement, it doesnt seem to make sense for an xgboost model to only remember the variable position # rather than the variable name. Every single other modeling technique out there functions using a variable name, so it seems reasonable for xgboost to function in the same way. 

@khotilov , Yes, generally its a similar model if you refit with only the final variables, but this isnt always the case, I run into some cases where it does noticeably impact the model.
