### ISSUE TITLE
Problem with "Scikit-Learn Wrapper interface for XGBoost." .XGBRegressor  

### ISSUE THREAD

**Issue by ding1747774835** [dmlc/xgboost#10550]
Is it normal that these parameters are all "None"? The default values ​​were not used when training the model, and the prediction results were greatly deviat
![Uploading question.jpg…]()
ed.

**Comment by trivialfis** [comment]
You pasted the wrong link, could you please update the issue and be more specific?

**Comment by trivialfis** [comment]
Feel free to reopen if there are further information.
