### ISSUE TITLE
src/tree/updater_histmaker.cc:301: Check failed: (istart) != (hist.size)

### ISSUE THREAD

**Issue by a4tunado** [dmlc/xgboost#1056]
Got an exception while training xgboost in distributed mode via spark on 32 workers with approx 5 million rows per worker.

Exception occures periodiaclly and depends on input data.

Here is all what I've got from worker node stderr:
`[18:41:18] dmlc-core/include/dmlc/logging.h:245: [18:41:18] src/tree/updater_histmaker.cc:301: Check failed: (istart) != (hist.size) 
terminate called after throwing an instance of 'dmlc::Error'
  what():  [18:41:18] src/tree/updater_histmaker.cc:301: Check failed: (istart) != (hist.size)`

**Comment by a4tunado** [comment]
Exception occur due to NaN appearance in the input file

**Comment by anaef** [comment]
Confirming the same issue, also on a large dataset, and also with NaN (which is used to denote missing data in the particular case).

**Comment by tqchen** [comment]
Let us elllaborate a bit. XGBoost works fine as long as nan is transformed as missing during DMatrix construction. It will work fine for dense data transformation, we likely want to add drop nan on sparse data format as well @CodingCat

**Comment by CodingCat** [comment]
I think one of the reasonable way is to set default missing value as nan?

**Comment by anaef** [comment]
@tqchen @CodingCat In my case, the code in question is using DMatrix, and the missing value is set to NAN. The client code is unchanged. The only change is the XGBoost library which has been updated to the current head of the repository. Looking into analyzing this further.
