### ISSUE TITLE
R 4.4 not loading package from GitHub 

### ISSUE THREAD

**Issue by Chandra-Goetsch** [dmlc/xgboost#10581]
Hi,
I am new to xgboost, but am an experienced R user. I am following the instructions here [https://xgboost.readthedocs.io/en/stable/R-package/xgboostPresentation.html](url) to install the GitHub version of xgboost and am getting an error.

Instructions:
`install.packages("drat", repos="https://cran.rstudio.com")
drat:::addRepo("dmlc")
install.packages("xgboost", repos="http://dmlc.ml/drat/", type = "source")`

Error: 
Warning in install.packages :
  unable to access index for repository http://dmlc.ml/drat/src/contrib:
  cannot open URL 'http://dmlc.ml/drat/src/contrib/PACKAGES'
Warning in install.packages :
  package ‘xgboost’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

My environment: 
Sys.info()
sysname  -  "Windows"        
release - "10 x64" 
version - "build 19045" 
machine - "x86-64" 
R version 4.4.0 (2024-04-24 ucrt)

I have Rtools 4.4 installed.

Just scanning through the issues here, I see that a major overall of the R package is underway (YAY!!!). However, if that is the case and it is not planned to have the GitHub version available in the meantime to new versions of R, I would highly recommend putting a note on the website to inform users.

Thanks so much.

**Comment by hcho3** [comment]
The instruction appears to be outdated. The URL `dmlc.ml` no longer exists. In the meanwhile, please consult https://xgboost.readthedocs.io/en/stable/build.html#building-r-package-from-source to install the R package from the source.

**Comment by Chandra-Goetsch** [comment]
Thanks for the quick reply. I will look at those instructions.
