### ISSUE TITLE
[jvm-packages]Compile my project with xgboost4j-0.5.jar failed:not found: object ml

### ISSUE THREAD

**Issue by bukysun** [dmlc/xgboost#1058]
I've compiled and package xgboost4j and xgboost4j-spark sucessfully with maven. And I added the created xgboost4j-0.5.jar and xgboost4j-spark-0.5.jar file into my own project but I failed to  compile my project with the error:
[ERROR] /Users/bhdata_rank/src/main/scala/xgboost_rank/xgboost_test.scala:3: error: not found: object ml
[ERROR] import ml.dmlc.xgboost4j.scala.spark.XGBoost
[ERROR]             ^
I use the intellij idea as IDE and maven to package. I add the .jar file through project structure->Module->dependencies->+jar or libraries.

**Comment by CodingCat** [comment]
I cannot reproduce it in my side 

![image](https://cloud.githubusercontent.com/assets/678008/14140523/6cced218-f647-11e5-95fa-53355129bfde.png)

**Comment by CodingCat** [comment]
I just re-read your question....if you added dependency in IntelliJ, and compile with maven 

that will not work.....they are two different software systems...so any dependency added in IntelliJ will not be recognized by maven....

you can either compile within IntelliJ, or publish xgboost4j in your local repo, added dependency in pom.xml and then build with maven (http://stackoverflow.com/questions/4955635/how-to-add-local-jar-files-in-maven-project)
