### ISSUE TITLE
win10, 64bit instalation -  A dynamic link library (DLL) initialization routine failed

### ISSUE THREAD

**Issue by gugatr0n1c** [dmlc/xgboost#1059]
On win10 64bit trying to install xgboost:

python: anaconda 3.5.1
using git bash
mingw

.dll is created, python instalation seems to woring as well but but trying import xgboost, got error below

sequence of instalation:

$ alias make='mingw32-make'

$ git clone --recursive https://github.com/dmlc/xgboost
$ cd xgboost
$ git submodule init
$ git submodule update

$ cp make/mingw64.mk config.mk
$ make  -j4

cd python-package  
python setup.py install 

in python
import xgboost

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\users\math.desktop-3d73v0b\xgboost\python-package\xgboost\__init__.py", line 11, in <module>
    from .core import DMatrix, Booster
  File "c:\users\math.desktop-3d73v0b\xgboost\python-package\xgboost\core.py", line 83, in <module>
    _LIB = _load_lib()
  File "c:\users\math.desktop-3d73v0b\xgboost\python-package\xgboost\core.py", line 77, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])
  File "C:\Anaconda3\lib\ctypes\__init__.py", line 425, in LoadLibrary
    return self._dlltype(name)
  File "C:\Anaconda3\lib\ctypes\__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 1114] A dynamic link library (DLL) initialization routine failed

any idea?

**Comment by gugatr0n1c** [comment]
woriking only with this mingw64:
http://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/4.9.1/threads-posix/seh/x86_64-4.9.1-release-posix-seh-rt_v3-rev2.7zmake

NOT working with latest tdc-gcc!

**Comment by kitman0804** [comment]
@gugatr0n1c How to install the mingw64 from your link?

**Comment by kitman0804** [comment]
@gugatr0n1c Thanks!

**Comment by jurg96** [comment]
same problem on win10 64. The library wasbuilt with mingw64

**Comment by MichaelGuarin0** [comment]
after download this mgw64 (http://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/4.9.1/threads-posix/seh/x86_64-4.9.1-release-posix-seh-rt_v3-rev2.7zmake) how do i run the steps above from this version of mgw64?

**Comment by NemoCpp** [comment]
have you import xgboost in git bash? I have the same issue in git bash, but normal in windows cmd.
try windows cmd
