### ISSUE TITLE
Release a CPU only wheel on PyPI

### ISSUE THREAD

**Issue by rbeilvert** [dmlc/xgboost#10596]
I am using XGBoost on CPU only and do not require the NCCL library

Until before XGBoost v2.1.0 I managed to installed the lib with pip and --no-binay option to compile the package without NCCL

Since v2.1.0, `nvidia-nccl-cu12` is installed from PyPI and its huge 190MB weight makes my app not fit on my Heroku server anymore.

Is there another way to avoid the installation of this dependency than to edit the pyproject.toml file from XGBoost locally and install it locally ?

**Comment by trivialfis** [comment]
Perhaps `pip install . --no-deps`?

**Comment by trivialfis** [comment]
Not sure if toml project allows a different dependencies profile that overrides the default one. So far the optional dependency configuration only allows additional dependencies.

**Comment by trivialfis** [comment]
Alternatively, you can consider conda, which has greater flexibility but the version update is a bit behind.

**Comment by rbeilvert** [comment]
> Perhaps `pip install . --no-deps`?

Not ideal as I have other packages in my requirements file for which I want to keep the dependencies, unless I create a specific Heroku buildpack for XGBoost install which sounds a bit overkill. 
I'd also have to check XGBoost's `pyproject.toml` anyway for any shenanigans every time I update its version 

Why not moving ["nvidia-nccl-cu12 ; platform_system == 'Linux' and platform_machine != 'aarch64'"](https://github.com/dmlc/xgboost/blob/213ebf7796b757448dfa2cfba532074696fa1524/python-package/pyproject.toml#L33C6-L33C86) down into [[project.optional-dependencies]](https://github.com/dmlc/xgboost/blob/213ebf7796b757448dfa2cfba532074696fa1524/python-package/pyproject.toml#L40C1-L40C32) ?

Having NCCL as a required dependency really penalizes CPU users

**Comment by hcho3** [comment]
It might be better to release a CPU-only package to PyPI, e.g. `xgboost-cpu`, for space-constrained environments.

**Comment by trivialfis** [comment]
I will leave it to @hcho to decide whether it's needed to maintain a fleet of packages (arm linux, x86 linux, windows, macos, arm macos, sdist) for a new pypi project.

It's a bit odd that pep517 has a way to turn on features in a package by having optional dependencies, but there's no way to turn off a feature.

**Comment by hcho3** [comment]
@trivialfis For `xgboost-cpu`, let's just maintain x86 linux and Windows. No need to complicate things.

**Comment by trivialfis** [comment]
Thank you for looking into this @hcho3 . Please note that the feature has been requested for Python https://discuss.python.org/t/help-packaging-optional-application-features-using-extras/14074/18 before and there are lots of discussions. It's not surprising since packages all want to provide as many features as possible in the default build. If we were to make a new project, we should prepare for deprecating/archiving that project as well if pep517 were to support these types of optional dependencies in the future.

**Comment by hcho3** [comment]
>  If we were to make a new project, we should prepare for deprecating/archiving that project as well if pep517 were to support these types of optional dependencies in the future.

I agree. We can archive `xgboost-cpu` once the Python ecosystem provides a way to optionally opt out of optional dependencies.

**Comment by hcho3** [comment]
@rbeilvert As a workaround, you can add the following URL to your `requirements.txt`:
```
https://files.pythonhosted.org/packages/5e/30/b4b1c071964acefeda3faade5b86e1bf2f428c5713404b212941942e835d/xgboost-2.1.0-py3-none-manylinux2014_x86_64.whl
```
This will install a variant of XGBoost 2.1.0 that doesn't require NCCL. Our plan is to upload this package under the name `xgboost-cpu` so that it's easy to locate and install.

**Comment by hcho3** [comment]
@trivialfis It turns out that I already did the necessary work to repackage XGBoost without GPU code in #10478 and #10483. So all it takes is the renaming of the package to `xgboost-cpu`.

**Comment by trivialfis** [comment]
It still needs to remove NCCL from pyproject right?

**Comment by hcho3** [comment]
> It still needs to remove NCCL from pyproject right?

This line removes NCCL from pyproject: https://github.com/dmlc/xgboost/blob/e9fbce9791469571481b59743bedf9d7d2a481a5/tests/buildkite/build-manylinux2014-x86_64.sh#L13

**Comment by hcho3** [comment]
The `xgboost-cpu` package is now available on PyPI: https://pypi.org/project/xgboost-cpu/
You can install it with `pip install xgboost-cpu`.

@rbeilvert @agossard-gpfw @yassinezaim-cp @kmodry @jmarichez @NicolasLegeay @mathieu-luciani @gtramoy @CyprienDuv
