### ISSUE TITLE
[CI] cupy tests are failing on windows.

### ISSUE THREAD

**Issue by trivialfis** [dmlc/xgboost#10610]
https://buildkite.com/xgboost/xgboost-ci-windows/builds/6091#0190c5f6-b72d-4ed0-bfc2-7470dcfc63c9

It seems the JIT is invoking nvcc, which failed to find a host compiler on the ci image.

**Comment by trivialfis** [comment]
@hcho3 Does the Windows image contain VC?

**Comment by hcho3** [comment]
@trivialfis It does.

**Comment by trivialfis** [comment]
Hmm, then I don't know what's the issue with nvcc. https://github.com/dmlc/xgboost/pull/10611 simply skips the tests, might not be ideal.

**Comment by hcho3** [comment]
Is it possible to disable the JIT build for cuPy?

**Comment by trivialfis** [comment]
The most relevant bit I can find is https://docs.cupy.dev/en/stable/reference/environment.html#envvar-NVCC for using different compiler backend (embedded jit vs. nvcc). I don't think one can remove the compiler.

**Comment by trivialfis** [comment]
Closing as it's unlikely that we will spend much effort in this.
