### ISSUE TITLE
[jvm-packages] SIGSEGV at libjvm.so jni_GetObjectClass

### ISSUE THREAD

**Issue by edi-bice** [dmlc/xgboost#1061]
I am running Spark 1.6.0 on YARN 2.7.1 (Hortonworks HDP 2.3.4.1-10). Built xgboost4j jar from latest from master as of yesterday or so. Pulling 80+M rows from Hive table, repartitioning to 10000, and running XGBoost.train on spark-shell launched as follows (9 nodes, 32G RAM each):

/usr/hdp/current/spark-client/bin/spark-shell --master yarn --deploy-mode client --num-executors 36 --executor-cores 1 --executor-memory 4g --conf "spark.executor.extraJavaOptions=-XX:+UseCompressedOops" --conf "spark.serializer=org.apache.spark.serializer.KryoSerializer" --jars xgboost-latest/jvm-packages/xgboost4j-spark/target/xgboost4j-spark-0.5-jar-with-dependencies.jar

A fatal error has been detected by the Java Runtime Environment:
SIGSEGV (0xb) at pc=0x00007f00ee83f61c, pid=10268, tid=139641109964544
JRE version: Java(TM) SE Runtime Environment (8.0_40-b25) (build 1.8.0_40-b25)
Java VM: Java HotSpot(TM) 64-Bit Server VM (25.40-b25 mixed mode linux-amd64 compressed oops)
Problematic frame:
V  [libjvm.so+0x6d161c]  jni_GetObjectClass+0xbc

**Comment by strunjas** [comment]
Hi,
Were you able to figure out the problem? I am getting exactly the same error .

**Comment by CodingCat** [comment]
Sorry about that, I didn't noticed this issue in my daily scanning of the list

it seems that you didn't register Booster class for kryo?

search `sparkConf.registerKryoClasses(Array(classOf[Booster]))` in https://github.com/dmlc/xgboost/tree/master/jvm-packages

**Comment by strunjas** [comment]
Thanks, that fixed the issue.

**Comment by edi-bice** [comment]
I do have that line in my code but I will retry

**Comment by tcarette** [comment]
I have the same problem at XGBoost.train on a dataset of 1.2M rows with about 4500 features. But the fix doesn't seem to work for me: I start my spark-shell in local mode on a 16Gb ram MacBook Pro with

`spark-shell  --jars xgboost4j-spark-0.7-jar-with-dependencies.jar --master local[*] --driver-memory 12G --conf "spark.serializer=org.apache.spark.serializer.KryoSerializer" --conf "spark.kryo.classesToRegister=ml.dmlc.xgboost4j.java.Booster"`

**Comment by treper** [comment]
This fix doesn't work for me either.I start spark-shell like this:
spark-shell --master local[4] --jars "spark-csv_2.10-1.5.0.jar,commons-csv-1.4.jar,xgboost4j-spark-0.5-jar-with-dependencies.jar"  --conf "spark.serializer=org.apache.spark.serializer.KryoSerializer" --conf "spark.kryo.classesToRegister=ml.dmlc.xgboost4j.scala.Booster"

**Comment by superbobry** [comment]
Managed to get the stacktrace

```
Stack: [0x00007ff33542a000,0x00007ff33552b000],  sp=0x00007ff335526a20,  free space=1010k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0x6e306c]  jni_GetObjectClass+0xbc
V  [libjvm.so+0x70a95d]  checked_jni_GetObjectClass+0xcd
C  [libxgboost4j6130086998137292242.so+0x7706f]  XGBoost4jCallbackDataIterNext+0x11f
C  [libxgboost4j6130086998137292242.so+0x8e235]  xgboost::NativeDataIter::Next()+0x15
C  [libxgboost4j6130086998137292242.so+0xaf39b]  xgboost::DMatrix::Create(dmlc::Parser<unsigned int>*, std::string const&)+0x1cb
C  0x00007ff335528880

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  ml.dmlc.xgboost4j.java.XGBoostJNI.XGDMatrixCreateFromDataIter(Ljava/util/Iterator;Ljava/lang/String;[J)I+0
j  ml.dmlc.xgboost4j.java.DMatrix.<init>(Ljava/util/Iterator;Ljava/lang/String;)V+47
j  ml.dmlc.xgboost4j.scala.DMatrix.<init>(Lscala/collection/Iterator;Ljava/lang/String;)V+19
j  ml.dmlc.xgboost4j.scala.spark.Watches$.apply(Lscala/collection/immutable/Map;Lscala/collection/Iterator;Lscala/Option;Ljava/lang/String;)Lml/dmlc/xgboost4j/scala/spark/Watches;+166
j  ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$buildDistributedBoosters$1.apply(Lscala/collection/Iterator;Lscala/collection/Iterator;)Lscala/collection/Iterator;+331
```

**Comment by superbobry** [comment]
#2885 adds debug logging for the above issue. Closing until someone else comes across this again.
