### ISSUE TITLE
XGBClassifier trained on sparse and applied to np.array

### ISSUE THREAD

**Issue by satyrmipt** [dmlc/xgboost#10616]
I'm working with pretrained XGBClassifier on inferece wich was:

1. trained on sparse data (text vectorized by tfidfvectorizer) 
2. was saved to s3 as pickle.dumps and restored as pickle.loads (the whole code is `pickle.loads(s3_resource.Object(BUCKET,key).get()['Body'].read())`)

and notice strange behavior:

1. predict method does not work, but predict_proba works well 
2. predict_proba works both for sparse and numpy.ndarray inputs and return correct results in the first case and strictly incorrect in the second case.

Questions:
1) Is there a way to return error when classifier.predict_proba is applied to data type it was not trained on? There is no any hint it was trained on sparse data or numpy.ndarray and results are so different. 
2) how can i revive predict method? 

XGBoost version is 2.0.3
Classifier lives in gpu (`device='gpu'` in the output below) and inputs are on cpu but i don't think it will impact results.

Code:
```
orig_clf_procedure=vect_class_dict["classificator"] # vect_class_dict store classificator and training params, we need the first one
sparse_vector=nb_vect_text.iloc[0] # read input data from pd.Series

print("pretrained classigicator:", orig_clf_procedure)

print(type(sparse_vector),           orig_clf_procedure.predict_proba(sparse_vector))
print(type(sparse_vector.toarray()), orig_clf_procedure.predict_proba(sparse_vector.toarray()))

print(type(sparse_vector),           orig_clf_procedure.predict(sparse_vector))
print(type(sparse_vector.toarray()), orig_clf_procedure.predict(sparse_vector.toarray()))

print(sparse_vector.toarray().shape)
```

Output:
```
pretrained classigicator: XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              device='gpu', early_stopping_rounds=None,
              enable_categorical=False,
              eval_metric=<function accuracy_score at 0x7f62b7b695a0>,
              feature_types=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.05, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=1,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=1100,
              n_jobs=None, num_parallel_tree=None, random_state=None, ...)
<class 'scipy.sparse._csr.csr_matrix'> [[0.81428134 0.18571869]]
<class 'numpy.ndarray'> [[0.9955726  0.00442739]]
<class 'scipy.sparse._csr.csr_matrix'> [0]
<class 'numpy.ndarray'> [0]
(1, 17339)
```

**Comment by trivialfis** [comment]
The predict proba calls predict internally.

The issue is likely that 0 being a valid data for XGBoost but missing for scipy sparse. If you call todense, scipy fills the matrix with 0s instead of NaN.

**Comment by trivialfis** [comment]
Feel free to reopen if there are further questions.
