### ISSUE TITLE
Callback for change weights after iteration (in R)

### ISSUE THREAD

**Issue by jaguerrerod** [dmlc/xgboost#10631]
Is there a way to change safely weights after each iteration based in some user custom logic?

**Comment by trivialfis** [comment]
I don't think so at the moment, you will have to write the iteration yourself (which is implemented in R anyway).

**Comment by jaguerrerod** [comment]
Do you refer to add at the end of this loop 
https://github.com/dmlc/xgboost/blob/411c8466bd383662a448a6a6be585c1b12b8c2e2/R-package/R/xgb.train.R#L431-L469
something like: setinfo(dtrain, 'weight', new_weights)?

**Comment by trivialfis** [comment]
> but how can I get predictions inside xgb.train.R without calling predict

Not sure what you mean by that, or why this is necessary. Please elaborate on it. Assuming by weights, you are talking about the sample weights, which doesn't affect prediction. It changes the training algorithm and the evaluation metric (weighted average), but has no impact on prediction itself.

**Comment by jaguerrerod** [comment]
This would be my use case:
A problem where the data is grouped by geographic area and the gradient boosting model consistently predicts some areas worse than others.
One approach is to fit a model and, based on the results, over-weight the 'difficult' regions, and do this several times.
What I want to do is introduce the process into the model fitting by doing upweighting after each iteration, evaluating all predictions by geographic area (the area is passed to dtrain with attr() and the performance of each area is assessed with a groupby on the absolute value of the prediction errors of the samples they include) and increasing the weight of the samples from the worst predicted areas.
It's the original idea of adaboost introduced into gradient boosting.

**Comment by trivialfis** [comment]
Thank you for the explanation, that would be interesting since the Hessian by itself is a form of weight. For additional weighting, you can do what you have described in https://github.com/dmlc/xgboost/issues/10631#issuecomment-2247737464 :
``` R
for (iteration in begin_iteration:end_iteration) {
    update.iter(bst, dtrain)
    predt <- predict(bst, ...)
    weight <- calc_weight(predt, y)
    setinfo(dtrain, "weight", weight) # This will be used by the next iteration.
}
```

**Comment by jaguerrerod** [comment]
Thanks,

so something like:
`predt <- predict(bst, dtrain, outputmargin = TRUE, iterationrange = c(1, 1))
`
should work fast as predict has the prediction in cache?
I think is the same logic used in **xgb.iter.eval()** using custom feval.

**Comment by trivialfis** [comment]
It should be, as long as it's still the same `dtrain` object.

**Comment by trivialfis** [comment]
Feel free to reopen if there are further questions.
