### ISSUE TITLE
Error importing xgboost in python (Windows 64 bit/ Anaconda)

### ISSUE THREAD

**Issue by thusithaC** [dmlc/xgboost#1065]
Hi devs,
I installed xgboost using mingw-64 as described, and everything went smooth. I installed the python modules using "python setup.py install" command. No errors again. But when I try to import the module I get the following error.  Would you have any ideas about why this might occur? 

Thanks,

> $ python
> Python 2.7.8 |Anaconda 2.1.0 (64-bit)| (default, Jul  2 2014, 15:12:11) [MSC v.1500 64 bit (AMD64)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
> Anaconda is brought to you by Continuum Analytics.
> Please check out: http://continuum.io/thanks and https://binstar.org
> >>> import xgboost
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "c:\Users\Thusitha\Anaconda\lib\site-packages\xgboost-0.4-py2.7.egg\xgboost\__init__.py", line 11, in <module>
>     from .core import DMatrix, Booster
>   File "c:\Users\Thusitha\Anaconda\lib\site-packages\xgboost-0.4-py2.7.egg\xgboost\core.py", line 15, in <module>
>     from .compat import STRING_TYPES, PY3, DataFrame, py_str
>   File "c:\Users\Thusitha\Anaconda\lib\site-packages\xgboost-0.4-py2.7.egg\xgboost\compat.py", line 35, in <module>
>     from sklearn.base import BaseEstimator
>   File "sklearn.py", line 7, in <module>
>     from .core import Booster, DMatrix, XGBoostError
> ValueError: Attempted relative import in non-package

**Comment by thusithaC** [comment]
I Updated python to 3.5, and moved to the xgaboost v4.0 stable. Things work fine now, using  mingw-64 compiler. Not sure what fixed it, the downgrade of xgaboost or moving to pytho 3.5

**Comment by gugatr0n1c** [comment]
same issue with... 

combination of mingw64 with gcc 4.9.1 is working, but latest with gcc 5.x.x is not working for me

**Comment by mkinet** [comment]
I have the same issue. 

I compiled both with mingw gcc 5.4.0 and mingw gcc 4.9.1 but I still I have the error above. The library seems to be installed, but the first import in __init__ fails.

Has anyone found the solution to this?

**Comment by mkinet** [comment]
I fixed the issue by adding permanently the mingw/bin directory into the PATH environment variable.

**Comment by zubairdotnet** [comment]
Which version did you install @mkinet?

**Comment by mkinet** [comment]
@zubairdotnet which version of what? xgboost or gcc?
