### ISSUE TITLE
Possible Null Pointer Dereference in src/data/sparse_page_source.h

### ISSUE THREAD

**Issue by dmc1778** [dmlc/xgboost#10650]
In [this](https://github.com/dmlc/xgboost/commit/628411a654ee3015ad2ab0031a49dbed4a410f75) commit, and the modified file ```src/data/sparse_page_source.h```, added lines 291 to 30:

```
*GlobalConfigThreadLocalStore::Get()] {
                   *GlobalConfigThreadLocalStore::Get() = config;
```
Is possibly a bug because it attempts to dereference the result of `GlobalConfigThreadLocalStore::Get()` without checking if the result is null or valid.

**Comment by hcho3** [comment]
@dmc1778 `GlobalConfigThreadLocalStore` is a thread-local storage. Have you encountered a case where a thread-local storage yields a null?

**Comment by dmc1778** [comment]
> @dmc1778 `GlobalConfigThreadLocalStore` is a thread-local storage. Have you encountered a case where a thread-local storage yields a null?

No, I statically detected this bug.

**Comment by trivialfis** [comment]
Feel free to reopen if there are further questions.
