### ISSUE TITLE
Parameter setting for global vs local eps in approximate tree building

### ISSUE THREAD

**Issue by thenomemac** [dmlc/xgboost#1067]
In the xgboost reference paper it states that "Users can freely choose between the methods" referring building approximate trees using histograms with a global histogram per tree vs a local histogram per split. However, the xgboost documentation doesn't mention this "local" vs "global" parameter anywhere. As I've shown from the copied documentation below, you can choose eta to set the number of bins in your histogram and you can choose "exact" vs "approx" to choose whether or not to use an approximate algorithm, but the parameter mentioned in the reference paper is not to be found? Can anyone shed some light on this?
 
> tree_method, string [default=’auto’]
> The tree constructtion algorithm used in XGBoost(see description in the reference paper)
> Distributed and external memory version only support approximate algorithm.
> Choices: {‘auto’, ‘exact’, ‘approx’}
> ‘auto’: Use heuristic to choose faster one.
> For small to medium dataset, exact greedy will be used.
> For very large-dataset, approximate algorithm will be choosed.
> Because old behavior is always use exact greedy in single machine, user will get a message when approximate algorithm is choosed to notify this choice.
> ‘exact’: Exact greedy algorithm.
> ‘approx’: Approximate greedy algorithm using sketching and histogram.
> sketch_eps, [default=0.03]
> This is only used for approximate greedy algorithm.
> This roughly translated into O(1 / sketch_eps) number of bins. Compared to directly select number of bins, this comes with theoretical ganrantee with sketch accuracy.
> Usuaully user do not have to tune this. but consider set to lower number for more accurate enumeration.
> range: (0, 1)

**Comment by tqchen** [comment]
By default global version is used. I will add an quick option for approximate local later
