### ISSUE TITLE
Custom subsampling in python

### ISSUE THREAD

**Issue by ytsaig** [dmlc/xgboost#1069]
This is a related to #374. I am interested in tweaking the subsampling to be more flexible, e.g., allowing for stratified sampling, bootstrap sampling, etc. Looking through the python API, it seems like subsampling is handled in the C++ code. However, since the DMatrix object gets passed in each iteration, at least with a custom objective, it's in principle possible to set subsample = 1.0 and do the subsampling directly on a DMatrix and pass a new DMatrix in each call to `_LIB.XGBoosterBoostOneIter()`. I am wondering if (a) it's a feasible approach, and (b) whether there is a way to modify the data in DMatrix without recreating it from a numpy array each time.

**Comment by ytsaig** [comment]
For those stumbling on a similar issue, (a) yes it is a feasible approach, though recreating the DMatrix object is expensive, and (b) doesn't seem like there is a way without hacking the C++ implementation.

**Comment by BenRollert** [comment]
I am interested in this as well. My approach right now is simply to ensemble multiple xgboost models using a metabagging approach with custom set indices.
