### ISSUE TITLE
[docs] [cmake] switch to 'cmake --build'?

### ISSUE THREAD

**Issue by jameslamb** [dmlc/xgboost#10699]
## Description

Many CI scripts and docs throughout this project use a pattern like this for CMake:

https://github.com/dmlc/xgboost/blob/43704549a2746fcf134a89b3153502a02a94a295/doc/build.rst?plain=1#L130-L133

Would you support a series of PRs (or maybe just one, depending on how involved it gets) changing all such cases to this pattern?

```shell
cmake -B build -S . -DUSE_CUDA=ON
cmake --build build --target all -j4
```

## Benefits of this work

* reduce friction in building
  - *(2 commands instead of 4)*
* makes it easier for users to change generators
  - *(e.g. to Ninja instead of GNU Make)*

## Approach

Replace all uses of `mkdir build && cd build && cmake ..` or similar with the corresponding 2 `cmake` commands (`cmake` followed by `cmake --build`).

## Notes

I did this in LightGBM a few months ago. We haven't received any complaints about it, and I've personally found it a bit easier to work with: https://github.com/microsoft/LightGBM/pull/6368

But won't be offended if you say "no thank you, we don't want this" 😅

**Comment by trivialfis** [comment]
Thank you for the suggestions, sounds good!
