### ISSUE TITLE
Dask XGBoost predictors takes a lot ot time when increasing max_depth from 6 to 7

### ISSUE THREAD

**Issue by ttopic** [dmlc/xgboost#10703]
Running dask xgboost on 2 DGX H100 under k8.

Training time at max_depth 7 is 96 secs on a 29M rows, 135 columns, some of them categoricals, dataset. At a max_depth of 6 is  76 secs.

However, while prediction time for 1.5M row test dataset at max_depth 6 is  60 secs, at a max depth of 7 it runs for over 12 hours without signs of stopping. No GPU activity is seen,  only CPU activity at prediction time.

Running environment: 
    numpy Version: 1.26.4
    cupy Version: 13.2.0
    Pandas Version: 2.2.2
    cudf Version: 24.06.01
    cuml Version: 24.06.01
    daskcudf Version: 24.06.01
    dask Version: 2024.5.1
    shap Version: 0.46.0
    XGBoost version:  2.0.3
    Dask ML version:  2023.3.24

Relevant code:

        %time dtrain = dxgb.DaskQuantileDMatrix(client, X_train, y_train, enable_categorical=True) # 

        params = {                 # https://xgboost.readthedocs.io/en/release_1.1.0/parameter.html
            'learning_rate': 0.05,
            'max_depth': 6,  # To make it faster you can lower the depth. Any number bigger than 6 takes too long to predict!
            'objective': 'reg:squarederror',
            'subsample': 0.95, # Subsample ratio of the training instances. 
            'validate_parameters': True,
            'disable_default_eval_metric':True, 
            'predictor':'gpu_predictor', # https://xgboost.readthedocs.io/en/release_1.1.0/gpu/index.html Trying to make sure presiction is done in the GPU
            'tree_method':'hist', # https://xgboost.readthedocs.io/en/release_1.1.0/gpu/index.html  Deprecated gpu_hist
            "max_cat_to_onehot": 5,   # It may be fundamental to set this parameter to 5
            'device':'cuda', 
        }

        print("\nEntering train")
        print(f"X_train size: {X_train.shape[0].compute()=:,.0f}")
        %time trained_model = xgb.dask.train(client, params, dtrain, num_boost_round=3000, evals=[(dtrain, "train")]) # , evals=[(dtrain, 'train')] # Took 13 - 15 min+ 3000 is the limit for num_boost_round
        print("Trained model type: ",type(trained_model))
        
        #print("\nSaving model")
        #%time trained_model['booster'].save_model("/data/rc/trained_model.json") # You have to save it in json mode because of categorical values.
        
        print("\nEntering prediction")
        print(f"X_test size: {X_test.shape[0].compute()=:,.0f}")
        trained_model['booster'].set_param({"device": "cuda"}) # https://xgboost.readthedocs.io/en/release_1.7.0/tutorials/dask.html#overview
        print("\nEntering inplace_predict")
        %time prediction = xgb.dask.inplace_predict(client, trained_model['booster'], X_test).astype('float32') # It doesn't look like it is using the GPU. Apparently it uses 1 - 3 workers CPUs
        predictionc=prediction.compute()
        wait(predictionc)

Is there a known issue?

**Comment by trivialfis** [comment]
Hi, could you please update to XGBoost 2.1? We workarounded an issue here https://github.com/dmlc/xgboost/pull/10632 and it's backported to 2.1.1.

**Comment by ttopic** [comment]
It worked beautifully with 2.1.1. Kudos! Thanks! @ @trivialfis

**Comment by trivialfis** [comment]
Aside, `gpu_predictor` was removed in 2.0. Simply setting the `device` attribute is sufficien for XGBoost. If you want the full pipeline including ETL in GPU, you can use the `to_backend` from dask collection, which migrates the dask data from CPU to the specified backend.

Feel free to reopen if there are further questions.
