### ISSUE TITLE
Allow installing the `py-xgboost-gpu` conda package on CPU-only machines

### ISSUE THREAD

**Issue by Yura52** [dmlc/xgboost#10715]
Hi! Currently, on a CPU-only machine, GPU-enabled XGBoost can be installed via pip, but not via conda. Is it possible to allow this for conda as well? The attempt to use conda leads to the following error:

```
error    libmamba Could not solve for environment specs
    Encountered problems while solving:
      - nothing provides __cuda needed by py-xgboost-gpu-2.0.3-py310h6bc6e9e_0
    
    The environment can't be solved, aborting the operation
```

My use case: I have a CPU-only machine where I need to create a Docker-like image with a conda environment. This image will then be used on machines with GPUs. However, I cannot add the py-xgboost-gpu conda package to this environment due to the above error. At the same time, some libraries requiring GPU, like GPU-enabled PyTorch, can be successfully installed on a CPU-only machine.

**Comment by trivialfis** [comment]
cc @hcho3 @jakirkham might have some insights into the issue.

**Comment by jameslamb** [comment]
> nothing provides __cuda

For this use case, you can tell `conda` to act as if there's CUDA available on the system by setting environment variable `CONDA_OVERRIDE_CUDA`. Like this:

```shell
CONDA_OVERRIDE_CUDA="12.2" \
conda install -c conda-forge py-xgboost-gpu
```

That environment variable is intended for exactly cases like the one you described. You can find docs on that here: https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-virtual.html#overriding-detected-packages

**Comment by trivialfis** [comment]
@jameslamb Thank you for sharing! Would you like to help add a brief note to the document? It's a really useful trick.

**Comment by jameslamb** [comment]
Sure! I'll put up a PR for that.
