### ISSUE TITLE
how can I use xgboost in java?

### ISSUE THREAD

**Issue by YouChouNoBB** [dmlc/xgboost#1072]
win8 64bit with eclipse, i like java more than python or R

**Comment by CodingCat** [comment]
you can check our jvm-packages https://github.com/dmlc/xgboost/tree/master/jvm-packages

**Comment by YouChouNoBB** [comment]
@CodingCat  in vs2013，reminds that xgboostjavawrapper(can not use) ,because can not find project file or website,how can i build it

**Comment by CodingCat** [comment]
xgboost4j (and xgboost) is not support in windows for now...the only way is to use it with mingw/cmake

they have a useful discussion at : https://github.com/dmlc/xgboost/issues/1063

**Comment by YouChouNoBB** [comment]
@CodingCat  thanks ,later i used a previous xgb-master version ,then i can use xgb in java
http://blog.csdn.net/bryan__/article/details/51036497
