### ISSUE TITLE
Gradients and hessians in multi-target models

### ISSUE THREAD

**Issue by RawabiAlwanin** [dmlc/xgboost#10722]
Hi,
I have a question about how gradients are combined in multi-target models using built in objectives like reg:squarederror? are they summed up? and in which file can find this gradients combination?

**Comment by trivialfis** [comment]
Mostly by extending scaler multiplication in gain calculation to vector product.

**Comment by trivialfis** [comment]
Feel free to reopen it if you have any more questions.
