### ISSUE TITLE
xgboost 2.1.0 linking error on Android device

### ISSUE THREAD

**Issue by pmorje** [dmlc/xgboost#10728]
I am trying use to xgboost 2.1.0 on an android device.
I have built libxgboost.so from source and downloaded on the android device. 
It complains about libomp.so not being linked. 

My question is: 
- do I build and link to libomp.so from within xgboost or 
- do I link to one of many  copies of libomp.so in c:/Users/ThisUser/AppData/Local/Android/Sdk/  like
c:/Users/ThisUser/AppData/Local/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/12.0.8/lib/linux/arm/libomp.so

I have done this with xgboost 1.7.3 and used libxgboost.so successfully on this android device 
because I believe xgboost 1.7.3 did not use libomp.so. 

Many thanks.

**Comment by trivialfis** [comment]
> do I build and link to libomp.so from within xgboost or

No, it's part of the compiler (clang), it's a runtime library.

> do I link to one of many copies of libomp.so

The compiler along with CMake should figure it out, as it's part of the compiler, just like `libc++`.

> because I believe xgboost 1.7.3 did not use libomp.so.

it did: https://github.com/dmlc/xgboost/blob/5371b8c080a4b076c7e01de148dbcb6046fdbddc/cmake/Utils.cmake#L278 

I think there might be a misconfiguration of the compiler in your setup.

**Comment by trivialfis** [comment]
Closing due to stalled. Feel free to reopen if there are further information.
