### ISSUE TITLE
Require CUDA 12+ to build from the source

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#10738]
We recently moved to CUDA 12.4 in our CI infra. Now is the time to require CUDA 12.0 for users building from the source?

https://github.com/dmlc/xgboost/blob/55aef8f546c2abecab7f2800265289e91bde7d00/CMakeLists.txt#L215-L217

**Comment by robertmaynard** [comment]
I believe we should support two major CUDA versions. That allows projects like CUML which provides CUDA 11 and CUDA 12 binaries to continue to leverage xgboost.

**Comment by hcho3** [comment]
@trivialfis I remember you saying that external memory will use some features available in CUDA 12.4. Can we make it so that XGBoost can still be built with CUDA 11.8 ?

**Comment by trivialfis** [comment]
Yes, it's optional. The external memory can use HMM if available. It requires the open kernel driver, I don't expect everyone to transition to it anytime soon.
