### ISSUE TITLE
python package error:ELF file OS ABI invalid

### ISSUE THREAD

**Issue by myotheone** [dmlc/xgboost#1073]
I compiled xgboost using gcc-4.8.2, it works fine.

however,when I try to run multi label classification,

it reports error: OSError: /opt/compiler/gcc-4.8.2/lib/librt.so.1: ELF file OS ABI invalid

file command of libxgboost.so: lib/libxgboost.so: ELF 64-bit LSB shared object, AMD x86-64, version 1 (SYSV), not stripped

file command of /opt/compiler/gcc-4.8.2/lib/librt.so.1:/opt/compiler/gcc-4.8.2/lib/librt-2.18.so: ELF 64-bit LSB shared object, AMD x86-64, version 1 (GNU/Linux), not stripped

**Comment by khotilov** [comment]
You have some strange mix of UNIX System V and Linux binaries. What exactly is your OS and your gcc?

**Comment by khotilov** [comment]
I'm realizing that my last comment might be received not as intended...
To clarify: my guess is that your gcc was build for a different system (it was built for a GNU/Linux target ABI), while the loader on your OS appears not to support this ABI.
