### ISSUE TITLE
rabit.tracker_print prints to ipython notebook console instead of notebook cell

### ISSUE THREAD

**Issue by alexeygrigorev** [dmlc/xgboost#1074]
I just installed xgb from the sources, and now all `verbose_eval` log messages disappeared, as if it's running in the silent mode. 

But after a while I noticed that it outputs the log messages to the console from which I'm running the jupyter notebook - and not to the notebook cell.

Could it be because of `rabit.tracker_print`? 

Possibly related to #1014

**Comment by tqchen** [comment]
should be fixed by #1102
