### ISSUE TITLE
[R] predict() should deal with data.frames with extra columns or different column order

### ISSUE THREAD

**Issue by mayer79** [dmlc/xgboost#10748]
I'd suggest that we invest some dedication to the predict() function with the new data.frame-API:

```r
library(xgboost)

fit <- xgboost(iris[2:5], y = iris$Sepal.Length, nrounds=10)

# This works: input is exactly as during training
predict(fit, head(iris[2:5]))  # 5.084347 4.748674 4.703810 4.839047 5.084347 5.426408

# This works, but the answer is wrong: column order shuffled
predict(fit, head(iris[5:2]))  # 4.715213 4.715213 4.715213 4.715213 4.715213 4.715213

# This gives fatal error (extra columns)
predict(fit, head(iris))
```

We can store feature names seen during training as metadata and use it to check/subset the data passed to `predict()`

@david-cortes

**Comment by david-cortes** [comment]
@mayer79 The method `predict.xgboost` has not been added yet. At the moment, what you are calling there is the old `predict.xgb.Booster`. So yes, `predict.xgboost` should do feature validation by default (`validate_features=TRUE`), but the function doesn't exist yet.

**Comment by mayer79** [comment]
Ahh, I see! We can add more and more logic later. E.g., check consistency of factor levels. Or treat ordered factors as numeric (not categoric).
