### ISSUE TITLE
[jvm-packages] About xgboost for spark

### ISSUE THREAD

**Issue by zgxnet** [dmlc/xgboost#1076]
It seems that XGBoost.train only picks the first booster trained from the first partition, and boosters from other partitions are simply ignored. Is this by design? If so, it seems that the spark version is a sampled training using the local version. If you use only one booster, why all the boosters are trained?

**Comment by CodingCat** [comment]
XGBoost relies on allreduce algorithm to sync the boosters

eventually all boosters are identical.....
