### ISSUE TITLE
Very large dataset

### ISSUE THREAD

**Issue by wnzhang** [dmlc/xgboost#108]
I ran xgboost on a large regression dataset.
feature number: 124
instance number: 31M
train file size: 33G

And I got the error: 
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

Is this because of the large size of training data?
Any solution?

Thanks

**Comment by AbhishekSinghVerma** [comment]
@tqchen Link provided by you above doesn't work anymore. Would you please refresh the link or else provide some verbal directive on what to search for?

**Comment by tqchen** [comment]
these are already merged to main brach

**Comment by tqchen** [comment]
see https://xgboost.readthedocs.org/en/latest/tutorial/aws_yarn.html
