### ISSUE TITLE
Using multiple custom eval metric

### ISSUE THREAD

**Issue by hwu84** [dmlc/xgboost#1080]
Right now, in R, it seems that we can only pass one custom eval function using feval parameter. Is there any way to use multiple eval function or output both custom eval function and default eval function such as "auc","error"?
Thanks

**Comment by khotilov** [comment]
No, it's not possible with the current R interface.

**Comment by uptownfunk** [comment]
Has this been handled yet? We would need to be able to specify multiple outputs like "auc", "error". We would also need to choose which one to use for random stopping.

**Comment by tonydifranco** [comment]
I would also like to see this added
