### ISSUE TITLE
Copy content of a xgb.DMatrix object in R

### ISSUE THREAD

**Issue by rladeira** [dmlc/xgboost#1083]
How can I copy the content of a xgb.DMatrix object in R? Since xgb.DMatrix object is just a pointer to a C++ class, normal assignment via "<-" symbol seems not to work for this purpose.

Currently,  I'm doing this in a very stupid way, using xgb.DMatrix.save to dump the content in a file, and then loading the content from the file into another xgb.DMatrix object.

**Comment by khotilov** [comment]
Use `slice` with the all the row indices to create a copy.

**Comment by rladeira** [comment]
It works perfectly. Thanks!
