### ISSUE TITLE
Split criteria and depth of tree

### ISSUE THREAD

**Issue by dnkamila** [dmlc/xgboost#1085]
In this library, we assign depth of tree. Can I use region instead? For example J = 5 mean 5 region (5 terminal nodes of tree). Why you choose depth of tree instead of region? And how the splitting stop? I tried code in xgb.plot.tree section from R Package 'xgboost' documentation with modification in max.depth :

`data(agaricus.train, package='xgboost')`
`train <- agaricus.train`
`bst <- xgboost(data = train$data, label = train$label, max.depth = 7, eta = 1, nthread = 2, nround = 2, objective = "binary:logistic")`
`xgb.plot.tree(agaricus.train$data@Dimnames[[2]], model = bst)`

And got tree with depth of 5. Why the tree not reach depth of 7? Actually how the split works?

Thanks in advance.

**Comment by pommedeterresautee** [comment]
XGboost stops splitting when it s not anymore necessary (when adding complexity to the trees doesn't bring improvement).
