### ISSUE TITLE
gitignore ignores file: indexed_recordio_split.cc and indexed_recordio_split.h

### ISSUE THREAD

**Issue by NewShawPercival** [dmlc/xgboost#10852]
If you download the repo and push it to another repo, you'll find dmlc-core/src/io/indexed_recordio_split.cc and dmlc-core/src/io/indexed_recordio_split.h are lost. I Checked it by inputting this command:
```
git check-ignore -v dmlc-core/src/io/indexed_recordio_split.cc
```
output:
```
.gitignore:30:*exe*     dmlc-core/src/io/indexed_recordio_split.cc
```

So there is a mistake in .gitignore line 30, ```*exe*```. I Think ```*exe``` is good

**Comment by trivialfis** [comment]
Thank you for sharing, opened a PR to fix it https://github.com/dmlc/xgboost/pull/10854 .
