### ISSUE TITLE
How to retrive best_ntree_limits or num_parallel_tree in a saved model?

### ISSUE THREAD

**Issue by hmchen-github** [dmlc/xgboost#10875]
I'd like to determine the `best_ntree_limits` when serving a saved model with C++ library, so that it can use the best trees. However, it seems those information is not saved in the .bst or .json file. The `num_parallel_tree` is not saved either, that I cannot use `num_parallel_tree * best_iteration` to calculate it. I am wondering what's the best way to get those?

Or, could you save those information in the model?

**Comment by trivialfis** [comment]
Why do you need the best tree limit? The best iteration should be sufficient for getting prediction and slicing models? There's an iteration range parameter in the predict method. In addition, you can slice the booster using boosting iteration.

The num_parallel_tree is saved JSON, but multiplying it directly to the best iteration is insufficient for multi-class/label models.

**Comment by trivialfis** [comment]
Feel free to reopen it if you have further questions.
