### ISSUE TITLE
PyPi metadata not filled in

### ISSUE THREAD

**Issue by baderbuddy** [dmlc/xgboost#1087]
Looking at xgboost on PyPi there are some holes in the metadata.

https://pypi.python.org/pypi/xgboost

The license is unknown and there are no classifiers. I think it'd be a huge value to add those to the next release to pypi.

**Comment by phunterlau** [comment]
@baderbuddy Thanks. I will update it when update the `pip` code too.

**Comment by jakirkham** [comment]
Please also add a license file to the PyPI package.

**Comment by jakirkham** [comment]
Please also add a license file to the PyPI package.

cc @beckermr

**Comment by beckermr** [comment]
Also, there is (I think) a bug in the python build system for OSX. I am currently patching it in the conda-forge xgboost recipe. I will make an issue.

**Comment by beckermr** [comment]
See https://github.com/dmlc/xgboost/issues/2093
