### ISSUE TITLE
Ability to set number of threads when calling xgboost4j Booster `inplace_predict`?

### ISSUE THREAD

**Issue by JGulbronson** [dmlc/xgboost#10874]
Apologies for asking here instead of https://discuss.xgboost.ai, that site seems to be giving a 500 for me for some reason.

I'm looking to understand if we have the ability to set the number of threads a `Booster` uses, specifically when doing prediction instead of training. I've tried setting it with `n_thread`, but I've also set it to negative values and it doesn't complain so I'm not sure it's correct. Happy to submit a PR updating the documentation on this once I find the right answer!

**Comment by trivialfis** [comment]
> Apologies for asking here instead of https://discuss.xgboost.ai/, that site seems to be giving a 500 for me for some reason.

@hcho3 It seems I can't access it either.


> I've tried setting it with n_thread, but I've also set it to negative values and it doesn't complain so I'm not sure it's correct.

The parameter name is `nthread`. Yes, you can set it to a negative value, in which case XGBoost uses all available threads.

**Comment by JGulbronson** [comment]
Sorry I think I used the one without the underscore. So all I need to do is
```
booster.setParam("nthread", 1)
```

To limit the `Booster` to a single thread? I think I'm struggling to understand the threading model, are those threads created per call to `predict`?

**Comment by trivialfis** [comment]
Yes, you can set the nthread prior to any prediction call, in place predict will pick it up. Please note that `setParam` is not thread-safe. Set it once before launching your threads.

> are those threads created per call to

Those threads are managed by OpenMP. On Linux, it uses the libgomp in GCC. I can't provide a definite answer to how it manages the threads.
