### ISSUE TITLE
XGBoost Windows installation error

### ISSUE THREAD

**Issue by uasthana15** [dmlc/xgboost#1089]
Hi,

I am using WIndows 7, trying to install XGBoost for python.
I am using GIT Bash to do so.
I have followed the steps on the following  page-
https://github.com/dmlc/xgboost/blob/master/doc/build.md#building-on-windows
I have the following make version in MinGW-
mingw32-make   bin  3.82.90-2-cvs-20120902
mingw32-make    doc 3.82.90-2-cvs-20120902
mingw32-make    lang 3.82.90-2-cvs-20120902
mingw32-make    lic 3.82.90-2-cvs-20120902
and the following g++ version-
mingw32-gcc-g++     bin  4.9.3-1 
mingw32-gcc-g++     dev  4.8.1-4 
mingw32-gcc-g++     doc  4.8.1-4 
mingw32-gcc-g++     man  4.9.3-1 

On executing the following commands-
`cp make/mingw64.mk config.mk; 
make -j4 `
I get the following error for the second command- 
`$ make -j4
g++ -m64 -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -MM -MT build/learner.o src/learner.cc >build/learner.d
g++ -m64 -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -MM -MT build/logging.o src/logging.cc >build/logging.d
g++ -m64 -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -MM -MT build/common/common.o src/common/common.cc >build/common/common.d
g++ -m64 -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -MM -MT build/c_api/c_api_error.o src/c_api/c_api_error.cc >build/c_api/c_api_error.d
cc1plus.exe: sorry, unimplemented: 64-bit mode not compiled in
Makefile:97: recipe for target 'build/common/common.o' failed
mingw32-make: *** [build/common/common.o] Error 1
mingw32-make: *** Waiting for unfinished jobs....
cc1plus.exe: sorry, unimplemented: 64-bit mode not compiled in
Makefile:97: recipe for target 'build/c_api/c_api_error.o' failed
mingw32-make: *** [build/c_api/c_api_error.o] Error 1
cc1plus.exe: sorry, unimplemented: 64-bit mode not compiled in
cc1plus.exe: sorry, unimplemented: 64-bit mode not compiled in
Makefile:97: recipe for target 'build/logging.o' failed
mingw32-make: *** [build/logging.o] Error 1
Makefile:97: recipe for target 'build/learner.o' failed
mingw32-make: *** [build/learner.o] Error 1
`
Please help me find the solution to this I can't seem to get pass this problem......!

**Comment by SoulEvill** [comment]
I was unable to install the latest version as well. hope someone could help me out. For now, I am use the version 0.40. If anyone need help with installation of this version, I am glad to help.

**Comment by thirdwing** [comment]
@uasthana15 You are using mingw32, please use mingw64.

**Comment by uasthana** [comment]
@thirdwing can you please elaborate on that I thought I was using mingw64 that is what is written on my bash window, and could you please provide a link to install it from.

@SoulEvill thanks any help is greatly appreciated, please let me know as to where I can start.

**Comment by uasthana15** [comment]
Working finally!! 
Following is a very helpful resource -
http://stackoverflow.com/questions/33749735/how-to-install-xgboost-package-in-python-windows-platform

Follow it right down to each hyphen
