### ISSUE TITLE
[FR] View of dmatrix instead of a full slice?

### ISSUE THREAD

**Issue by SteveBronder** [dmlc/xgboost#10891]
Looking at the code for slice (and thus called from `xgb.slice` in the R package) it appears to do a hard copy of the data. Is that right? It would be nice to have a `View` member function that gave a read only view of the DMatrix

https://github.com/dmlc/xgboost/blob/d9123a51ca497edc5cb504aab9b03e5d100aa986/src/data/simple_dmatrix.cc#L31

**Comment by trivialfis** [comment]
Yes, it's a copy. We are hoping the users can use the high-level interface `xgboost` and let external libraries handle data manipulation.

**Comment by SteveBronder** [comment]
That is reasonable. This came up for me because my data gets very near the max of my ram so placing all my memory into one DMatrix and sending views of it to xgboost runs for cross validation would be nice. 

If xgboost would be interested in something like this I'd be happy to give it a shot, but also understandable if that is out of scope

**Comment by trivialfis** [comment]
Thank you for volunteering! Unfortunately, I believe this is out of scope. The `DMatrix` object inside XGBoost is quite complicated and has multiple variants, it's unlikely that we can maintain a proper implementation of slice for all variants.

If you can use an external library for data split and cv, then you can consider the `QuantileDMatrix`, which is available in Python and the master branch of R package. It helps reduce the memory usage.
