### ISSUE TITLE
The tracker may not pick up the correct network interface.

### ISSUE THREAD

**Issue by trivialfis** [dmlc/xgboost#10897]
When using InfiniBand with dask, the XGBoost workers might not be able to use the correct network interface.

**Comment by trivialfis** [comment]
Ran some small tests yesterday, and the interface was correctly used by the workers.

**Comment by pentschev** [comment]
So are you saying that the IB interface get assigned by the XGB listeners?

**Comment by trivialfis** [comment]
@pentschev Apologies for missing the mail. Yes, I can see the tracker receiving the IB address.
