### ISSUE TITLE
Efficient DMatrix copy of np.array

### ISSUE THREAD

**Issue by gatapia** [dmlc/xgboost#109]
Calling fit/predict from python using a numpy array is extremely memory hungry.  It appears that another np.array is created and then a DMatrix is created.  This is causing memory usage to more than triple.

It would be great if a more conservative way of handling numpy arrays was implemented.  I tried using sparse arrays but this still caused huge memory spikes when converting to DMatrix.

**Comment by tqchen** [comment]
Will add support for native numpy datatypes(double, float) to avoid a few spikes during conversion,

**Comment by alexeygrigorev** [comment]
I wonder if there are any updates on the issue - has the support for numpy datatypes been added?

I'm trying to convert a large numpy array into a DMatrix and python dies with out of memory. Writing it into an svmlight light and reading it with DMatrix is an option, but it takes ages.

**Comment by jamesmf** [comment]
Has this been addressed? If not, does anyone have code as an example of the libsvm solution (or other suggestions)?

**Comment by dashiell** [comment]
It looks like it has still not been addressed.
