### ISSUE TITLE
Any Matlab wrapper for XGBoost?

### ISSUE THREAD

**Issue by cslxiao** [dmlc/xgboost#1090]
I wish to use XGBoost in Matlab. Is there any wrapper?

**Comment by barbara73** [comment]
I don't know if there is a wrapper for xgboost, but if you need a gradient boosting for large data I can highly recommend https://sites.google.com/site/carlosbecker/resources/gradient-boosting-boosted-trees
It's very fast and can handle very large data.

**Comment by RoyiAvital** [comment]
Any plan in the future to support MATLAB?

It would be really greta.
