### ISSUE TITLE
Variable Importance with co-occurence computation does not work

### ISSUE THREAD

**Issue by alexpenson** [dmlc/xgboost#1092]
The last line of the `xgb.importance` example gives no output:

```
data(agaricus.train, package='xgboost')

# Both dataset are list with two items, a sparse matrix and labels
# (labels = outcome column which will be learned).
# Each column of the sparse Matrix is a feature in one hot encoding format.
train <- agaricus.train

bst <- xgboost(data = train$data, label = train$label, max.depth = 2,
               eta = 1, nthread = 2, nround = 2,objective = "binary:logistic")

# train$data@Dimnames[[2]] represents the column names of the sparse matrix.
xgb.importance(train$data@Dimnames[[2]], model = bst)

# Same thing with co-occurence computation this time
xgb.importance(train$data@Dimnames[[2]], model = bst, data = train$data, label = train$label)
```

```
> sessionInfo()
R version 3.2.4 Revised (2016-03-16 r70336)
Platform: x86_64-apple-darwin15.4.0 (64-bit)
Running under: OS X 10.11.4 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] xgboost_0.4-3    ggplot2_2.1.0    data.table_1.9.7

loaded via a namespace (and not attached):
 [1] scales_0.4.0     colorspace_1.2-6 magrittr_1.5     Matrix_1.2-4     plyr_1.8.3.9000  tools_3.2.4      gtable_0.2.0     Rcpp_0.12.4      stringi_1.0-1    grid_3.2.4      
[11] stringr_1.0.0    munsell_0.4.3    lattice_0.20-33 
```

**Comment by khotilov** [comment]
It seems to be another case of breaking the common assumptions about sparse data values #1112 #899 . In addition, there seems to be an R bug in how a matrix is compared to vector. Will need to take a closer look at it later...

Besides, the real value of the extended table was in that it allowed to inspect the gains of individual splits for *continuous* features. You can still calculate it on your own as, e.g., 
`xgb.model.dt.tree(colnames(train$data), bst)[Feature!="Leaf"][, .(Gain=sum(Quality)), .(Feature, Split)][order(Feature, Split)]`
But all the "co-occurrence computation" stuff, frankly, I find unnecessary and confusing. Partial dependency plots are much better way to see relations b/w predictors and outcome.

**Comment by pommedeterresautee** [comment]
I agree with @khotilov , I added this code long time ago because I needed it at that time and thought may be other persons may use it. Now I think it s too specific and partial dependency plots would be better.
However, i never had the time to implement partial dependency plots the way it s explained by Friedman (his implementation should be more efficient that general one because it leverages the tree model).

**Comment by khotilov** [comment]
@pommedeterresautee : I don't know if that would be the same as Friedman's idea, but I was thinking about how permutation-based importance calculations could be made faster, and one of the key elements, I think, would be to take advantage of the fact that most features (when there are many) would appear only in a fraction of boosted trees. Same principle should be applicable to on-grid calculations for partial deps as well. That would need to be implemented in C++ to be truly useful though. I'm still thinking about the best way to do it.
