### ISSUE TITLE
xgboost.core.XGBoostError: [17:26:01] src/data/./row_block.h:144: Check failed: offset.back() == value.size() || value.size() == 0 

### ISSUE THREAD

**Issue by believe33158** [dmlc/xgboost#1093]
I use xgboost to train my data, but get the error like the title.  The error occurs in the line " dtrain = xgb.DMatrix('/Users/data/train.txt') ".  And the total error log is """   File "/Library/Python/2.7/site-packages/xgboost-0.4-py2.7.egg/xgboost/core.py", line 228, in **init**
    ctypes.byref(self.handle)))
  File "/Library/Python/2.7/site-packages/xgboost-0.4-py2.7.egg/xgboost/core.py", line 97, in _check_call
    raise XGBoostError(_LIB.XGBGetLastError())
xgboost.core.XGBoostError: [00:25:29] src/data/./row_block.h:144: Check failed: offset.back() == value.size() || value.size() == 0  """.
I have trained data  for some days successfully, but for this data for other days it occurs this error.
If anyone has met error like this please help me with the case,thanks!

**Comment by believe33158** [comment]
I have trained other data successfully, but for this data it occurs this error. Need you help , thank you!

**Comment by uplanning** [comment]
same issues, any suggestions? thank you!

**Comment by michaelbrundage** [comment]
I also ran into this from the command-line. The error for me was:

```
[11:56:38] rabit/include/rabit/../dmlc/./logging.h:245: [11:56:38] src/data/./row_block.h:144: Check failed: offset.back() == value.size() || value.size() == 0 
libc++abi.dylib: terminating with uncaught exception of type dmlc::Error: [11:56:38] src/data/./row_block.h:144: Check failed: offset.back() == value.size() || value.size() == 0 
```

where the values in brackets are local timestamps.

I tried editing the dmlc-core/src/data/row_block.h header to remove this check (not a good idea, of course, just seeing what would happen), rebuilt the dmlc-core submodule and then xgboost, but for some reason the error still repro'd. I guess some extra step must be required for xgboost to pick up on this change.

I reverted my local repo to commit c449dc6874818ba8e9cf00ed383bdb9b3b3b6358 and the error was still present. I revert to commit a6c35a8d748df8fa1e27c3a0bb527ea1513fd555 and the error changed:

```
54544186x220 matrix with 329167398 entries is loaded from train2_features.txt
30000 groups are loaded from train2_features.txt.group
terminate called after throwing an instance of 'std::runtime_error'
  what():  DMatrix: group data does not match the number of rows in features
```

This error message makes it clear it's user error in the .group file. With this additional information, I was able to delete the .group files (I wasn't using them anyway), and then that older version of xgboost ran without error:

```
54544186x220 matrix with 329167398 entries is loaded from train2_features.txt
54544186x220 matrix with 329167398 entries is saved to train2_features.txt.buffer
20001813x220 matrix with 115935941 entries is loaded from test2_features.txt
20001813x220 matrix with 115935941 entries is saved to test2_features.txt.buffer
boosting round 0, 6 sec elapsed
tree pruning end, 1 roots, 14 extra nodes, 0 pruned nodes ,max_depth=3
[0]	test-error:0.034130
boosting round 1, 14 sec elapsed
tree pruning end, 1 roots, 14 extra nodes, 0 pruned nodes ,max_depth=3
[1]	test-error:0.034130

updating end, 21 sec in all
```
and then with task=pred:
```
20001813x220 matrix with 115935941 entries is loaded from test2_features.txt.buffer
start prediction...
writing prediction to pred.txt
```

Then I brought xgboost back to the current master version (`git reset --hard origin/master`) to try it now that I've deleted the group files, but it failed again with the same original error. So, something broke in-between those two commits?

(I'd also suggest improving the text output of xgboost, especially in the face of errors. The older version emitted more useful information.)

**Comment by bhlangonijr** [comment]
I ran into the same exception. The issue was due to presence of `NaN` values in the input file which gone away after replacing them by something `!= NaN`

**Comment by zhonghaihua** [comment]
Hi, @bhlangonijr , I got this exception, but my data doesn't have `NaN` values. Any suggestions?

**Comment by bhlangonijr** [comment]
Hi @zhonghaihua. Without seeing your data is hard to tell but this is how I spotted the issue on my end (may sound stupid, but helped finding the actual data causing the exception):
- Split your input file in two parts (in linux I used `head -n[number_of_lines/2] input.txt > first_half.txt`)
- Run xgboost using the the partial file generated; if the error persists repeat this procedure splitting the file in two equal parts until no exception is thrown by xgboost. Then you get the previous chunk of the file throwing exceptions and keep narrowing down the parts until you end up with a fragment of the original file containing the line with the "bad" data.
I swear you can find the issue in at most `log2<number of lines in the original file>` steps. :D
Hope that helps.

**Comment by zhonghaihua** [comment]
Hi @bhlangonijr , Thanks for your suggestion, this is a good idea, I solve the problem.

**Comment by zhangyong14** [comment]
I got this error too, it was because there were some blanks in the beginning of the feature

**Comment by poson** [comment]
I found -inf ，nan in my dataframe，use “grep -v nan ”  "grep -v inf" to filter them
