### ISSUE TITLE
Calibration of Probability Model

### ISSUE THREAD

**Issue by ronmexico2718** [dmlc/xgboost#1094]
Suppose I train an xgboost model for binary classifications.  Also assume I have chosen my parameters intelligently.  When I run a predict on the training dataset, should the outputted probabilities be well calibrated?

For example, consider the following R pseudocode.  In the final glm fit below, should I expect the coefficient of logit_p_xg, in general, to be 1?

xg_model <- xgb.train(data=train_data_DMatrix, params=gbm_pars)
data$p_xg <- predict(xg_model, newdata=train_data_DMatrix)
data$logit_p_xg <- logit(data$p_xg)
glm_check <- glm(y ~ logit_p_xg, family=binomial(), data=train_data)

**Comment by walterreade** [comment]
In my experience (so, please take it as such), xgboost produces well calibrated models.

**Comment by khotilov** [comment]
I usually see rather good calibration. But in general there's no guarantee, and sometimes additional calibration might be necessary.

**Comment by pommedeterresautee** [comment]
for that purpose you can post calibrate the model (so no doubt of the calibration quality) :
https://en.wikipedia.org/wiki/Platt_scaling
