### ISSUE TITLE
cann't import xgboost package on Windows7

### ISSUE THREAD

**Issue by oleg001** [dmlc/xgboost#1096]
Hello. I installed python package (python version 2.7) some time ago and everything was ok. But after a time I run the import command 
## "import xgboost as xgb" and get the next error:

WindowsError                              Traceback (most recent call last)
<ipython-input-1-24bb4a39c975> in <module>()
      1 import sys
----> 2 import xgboost as xgb
      3 #import xgboost as xgb

R:\Program files\Anaconda\lib\site-packages\xgboost-0.4-py2.7.egg\xgboost__init__.py in <module>()
      9 import os
     10 
---> 11 from .core import DMatrix, Booster
     12 from .training import train, cv
     13 from . import rabit

R:\Program files\Anaconda\lib\site-packages\xgboost-0.4-py2.7.egg\xgboost\core.py in <module>()
     81 
     82 # load the XGBoost library globally
---> 83 _LIB = _load_lib()
     84 
     85 def _check_call(ret):

R:\Program files\Anaconda\lib\site-packages\xgboost-0.4-py2.7.egg\xgboost\core.py in _load_lib()
     75     if len(lib_path) == 0:
     76         return None
---> 77     lib = ctypes.cdll.LoadLibrary(lib_path[0])
     78     lib.XGBGetLastError.restype = ctypes.c_char_p
     79     return lib

R:\Program files\Anaconda\lib\ctypes__init__.pyc in LoadLibrary(self, name)
    441 
    442     def LoadLibrary(self, name):
--> 443         return self._dlltype(name)
    444 
    445 cdll = LibraryLoader(CDLL)

R:\Program files\Anaconda\lib\ctypes__init__.pyc in **init**(self, name, mode, handle, use_errno, use_last_error)
    363 
    364         if handle is None:
--> 365             self._handle = _dlopen(self._name, mode)
    366         else:
    367             self._handle = handle

WindowsError: [Error 127] 

I think some collision happens with new software, which i have installed since that period.
I tried to reinstall package, but it isn't help and the error is still remained.
I try to google the error, but without success.
Please, help me!

**Comment by YuYinCUG** [comment]
Did you solve this problem? I also got trouble with this problem.

**Comment by oleg001** [comment]
Hi!
Yeah, I solve my problem. As i supposed the problem was in some updated software during this time.
It was long time ago and I cann't reproduce exactly the solution, which help me.
Try to remember which packages/software did you install or update and downgrade it.
Good luck!
