### ISSUE TITLE
discrete features with unique values < max_bin but with some values having very low frequency?

### ISSUE THREAD

**Issue by lukezli** [dmlc/xgboost#10999]
How does xgboost using 'hist' method handle the case where max_bin = 128, and a feature can only have integer values [0,...100], but some values, say 0, only appear 0.01% of the time? Do the 0s ever get grouped with 1s, or do they maintain their own unique bin always?

Thanks!

**Comment by trivialfis** [comment]
It should main its unique bin. You can get the cut points from the QuantileDMatrix.

**Comment by trivialfis** [comment]
Feel free to reopen it if you have further questions.
