### ISSUE TITLE
Determine feature importances

### ISSUE THREAD

**Issue by dam-xx** [dmlc/xgboost#11]
Hi; could you please indicate me the way to determine the importance of each feature?  I'm using the Python interface and I could not find anything in the doc. Thanks!

**Comment by StevenLOL** [comment]
Hi, seems same code in feature_importances can also work for XGBRegressor, thought it is not a function of XGBRegressor.

**Comment by gautham20** [comment]
We can get the feature importance for XGBRegressor, With the following code.

```python
regr.booster().get_score(importance_type='weight')
```

Should be added as a function to XGBRegressor

**Comment by clarkzhao** [comment]
```python
regr.booster().get_fscore()
```
works as well
