### ISSUE TITLE
[Question] Is it possible to get the name of the output classes of an XGBClassifier?

### ISSUE THREAD

**Issue by dhombios** [dmlc/xgboost#11024]
XGBoost forum seems to be offline, being that the reason why I'm posting this question here

I'm using m2cgen to convert an XGBClassifier to C code, but this library doesn't include comments specifying the input feature names nor the output categories, which makes easy to forget what the model is expecting to receive or what it provides. To simplify model integration, I'm trying to generate comments specifying that information at the beginning of the generated code

That was easy for feature names, as they can be retrieved using get_booster().feature_names, but I can't find an equivalent method for getting the names of the classes that each element of the output probabilities vector represents

Is there any way to get that information from a trained model?

**Comment by trivialfis** [comment]
No, XGBoost accepts numeric labels `[0, 1 ... N]`, there's no name for labels. If there's a string representation of the classes, it's likely stripped by a label encoder before being passed to XGBoost, you need to find that encoder in your ETL pipeline.

**Comment by trivialfis** [comment]
For XGBoost, it's a must to encode 0 as negative and 1 as positive.

**Comment by trivialfis** [comment]
Feel free to reopen it if you have further questions.
