### ISSUE TITLE
[R] GC Torture test is very slow

### ISSUE THREAD

**Issue by david-cortes** [dmlc/xgboost#11030]
I'm not sure what changed recently, but this test suddently became very slow (~1 minute):
https://github.com/dmlc/xgboost/blob/5826b02d036deae8c232fb35654eb21f57490919/R-package/tests/testthat/test_gc_safety.R#L3

As it is right now, it accounts for more than half of the running time of tests. Perhaps it could be disabled by default and only run on some selected CI job.

**Comment by trivialfis** [comment]
Let me bisect it a little bit.

**Comment by trivialfis** [comment]
Yeah, let's remove it. The time is mainly spent inside R instead of XGBoost. I don't think the test is essential.
