### ISSUE TITLE
ERROR : XGBoostError: XGBoost Library (libxgboost.so) could not be loaded

### ISSUE THREAD

**Issue by jeetendraswami5** [dmlc/xgboost#11048]
Full Error:
```
[ERROR] XGBoostError: XGBoost Library (libxgboost.so) could not be loaded. Likely causes:

    OpenMP runtime is not installed (vcomp140.dll or libgomp-1.dll for Windows, libgomp.so for UNIX-like OSes)
    You are running 32-bit Python on a 64-bit OS Error message(s): ['libgomp.so.1: cannot open shared object file: No such file or directory']
```

Infrastructure: AWS Lambda Function (xgboost is getting imported via zip from s3) , xgboost version 0.90.
 - I am importing the XGBoost in the Lambda function and I get above error when I Try to run it.

- This error has started when I upgraded the Lambda Function Runtime version from Python 3.6 to Python 3.9

- I am importing the XGBoost from the zip I have kept in the S3 bucket and Lambda has a code to import it.

- I also tried packaging the libgomp.so.1 with the xgboost zip but that also did not worked.

**Comment by trivialfis** [comment]
Feel free to reopen if the issue persists.
