### ISSUE TITLE
Booster could have raw predictions for individual trees

### ISSUE THREAD

**Issue by david-cortes** [dmlc/xgboost#11049]
Booster's predict methods offer an iteration range parameter, and can output terminal node indices, but have no method to output per-tree scores for each observation.

Would be helpful to have such a method, for example when using the individual nodes as part of another model, or for better assessments of fit/prediction quality by iteration, or for custom tree drops (among others).

It's possible to get these currently, but it requires one predict call per tree, which is less efficient than having them in a single C-function call.
_edited for clarity_

**Comment by trivialfis** [comment]
> It's possible to get these currently, but it requires one predict all per tree, which is inefficient.

Please correct me if I'm wrong, it's not clear what's the exact feature request. If one were to get prediction for each tree, then we need to run a prediction call for these trees right? We can abstract the iteration inside XGBoost, but it wouldn't improve efficiency.

**Comment by david-cortes** [comment]
> > It's possible to get these currently, but it requires one predict all per tree, which is inefficient.
> 
> Please correct me if I'm wrong, it's not clear what's the exact feature request. If one were to get prediction for each tree, then we need to run a prediction call for these trees right? We can abstract the iteration inside XGBoost, but it wouldn't improve efficiency.

The request is to have an output of shape `[nrows, ntrees]`, where each column would have the raw score for an individual tree.

And yes, it of course would need to pass each observation down each individual tree, but it would be faster and more convenient than having to do it on a loop of one-by-one predictions with a single-tree iteration range when there are casts, copies and allocations along the way.

**Comment by trivialfis** [comment]
For convenience, it makes sense. I don't think there's much performance benefit though.

> do it on a loop of one-by-one predictions with a single-tree iteration range when there are casts, copies and allocations along the way

We might reduce the allocation, but copying and casting are still needed and are unlikely to be affected by the number of calls for the `predict` method. But these reduced allocations likely take less than, say 5% of the time used for prediction.

As for allocation, that's mostly from the R runtime, XGBoost has a cache for output prediction. If one is running multiple predictions with the same size of input (which is the case here), there's no extra allocation inside XGBoost needed. The allocation is for the R matrix returned by prediction. If the R allocation is really slow, we can wrap the iterations in C API.

**Comment by david-cortes** [comment]
Ok, guess efficiency gains would be different in language bindings other than R, so I'll be closing this issue.
