### ISSUE TITLE
xgboost not running in parallel

### ISSUE THREAD

**Issue by rladeira** [dmlc/xgboost#1106]
I recently reinstalled my operational system (ubuntu 14.04 LTS) and, strangely, xgboost is not able to run in parallel  anymore. Even though I set the nthreads parameter to the number of cores I have, the parallel processing is not working at all.

I have tested both R and python packages without success. Is there some dependency that I must install to be able to run the algorithm in parallel?

**Comment by edi-bice** [comment]
Did you rebuild xgboost? I noticed when using build.sh script it switches to building single-threaded xgboost if it runs into any problems at all. I now avoid that script and do make instead. That way I can see and fix the problems.

**Comment by dirceusemighini** [comment]
Hi @edi-bice I'm having problem to execute xgboost on multiple workstations, does this parallel means multiple threads or multiple workstations?

**Comment by edi-bice** [comment]
@dirceusemighini in this thread parallel means multiple threads

**Comment by dirceusemighini** [comment]
Thanks @edi-bice I can run xgboost in paralllel if I follow the instructions of https://github.com/dmlc/xgboost/issues/1106#issuecomment-245727917 although I can't make it to run with more than 1 nWorkers, as described [here](https://github.com/dmlc/xgboost/issues/1278)

**Comment by vkgpt11** [comment]
I am also facing the same issue. It is taking lots of time please suggest some solution.

**Comment by why-not** [comment]
I have compiled XGBoost with multi-threading enabled. But it still doesn't run in multiple threads (I set nthreads=-1 on an 8 core machine, no luck)

**Comment by hcho3** [comment]
@why-not You should set `nthread=0` to use all available cores.
