### ISSUE TITLE
[CI] 'DaskXGBClassifier' object has no attribute 'n_classes_'

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#11085]
Seeing this error from the latest CI runs:

```
assert cls.n_classes_ == 10
E           AttributeError: 'DaskXGBClassifier' object has no attribute 'n_classes_'. Did you mean: '__class__'?
```
https://github.com/dmlc/xgboost/actions/runs/12244160215/job/34155297086

**Comment by trivialfis** [comment]
That's new ... It's defined here: https://github.com/dmlc/xgboost/blob/4fd321c38f02a8c0d13fb7e1a031c53c83832397/python-package/xgboost/dask/__init__.py#L1751

**Comment by trivialfis** [comment]
I can really use some help with the latest dask ....

**Comment by hcho3** [comment]
I wonder if this has to do with latest scikit-learn. Let me try adding `scikit-learn<=1.5.2` to the CI and see if the failures go away.

**Comment by hcho3** [comment]
@trivialfis Yep, the CI breaks with the new scikit-learn.

**Comment by PeterPaton123** [comment]
FWIW: I also get scikit-learn related issues when calling XGBoostRegressor.load_model() on 1.6.0. The same code works when pinned to scikit-learn 1.5.2.

**Comment by trivialfis** [comment]
Fixed in the latest
