### ISSUE TITLE
what's the equation to calculate pred?

### ISSUE THREAD

**Issue by gusuperstar** [dmlc/xgboost#1109]
Hi @tqchen 

Given
objective="rank:pairwise"
eta = 0.1
gamma = 1.0
min_child_weight = 6
max_depth = 15
num_round = 12

the prediction path:

booster 0,  (leaf= - 0.0294118)
booster 1,  (leaf= - 0.0653785)
booster 2,  (leaf= 0.00467433)
booster 3,  (leaf= - 0.0662226)
booster 4,  (leaf= 0.0507554)
booster 5,  (leaf= - 0.00177127)
booster 6,  (leaf= - 0.0475963)
booster 7,  (leaf= 0.0439532)
booster 8,  (leaf= - 0.0116887)
booster 9,  (leaf= - 0.0140529)
booster 10, (leaf= - 0.0523157) 
booster 11, (leaf= - 0.0388263)
for pairwise ranking , the prediction value is 0.272119.

So ,could u introduce what's the equation to get the pred value from 12 trees? 
And, any difference if for binary classification or ndcg ranking?
Many thanks !

**Comment by gusuperstar** [comment]
@tqchen

**Comment by khotilov** [comment]
It's a sum of leaf values plus bias, which is 0.5 here.

**Comment by gusuperstar** [comment]
many thanks! @khotilov
