### ISSUE TITLE
Add support for Tweedie and Poisson regression for multi-output tasks

### ISSUE THREAD

**Issue by CodeCrux21** [dmlc/xgboost#11110]
**Description:**
Currently, XGBoost supports Tweedie and Poisson regression for single-output problems. However, there is no direct implementation or support for multi-output tasks for these objectives. Adding support for these regression types in multi-output settings would allow users to model complex datasets where multiple targets need to be predicted simultaneously.

**Motivation:**
- Multi-output regression is increasingly relevant for real-world applications (e.g., demand forecasting, insurance claims, energy consumption, etc.).
- Tweedie and Poisson objectives are widely used for their suitability in cases involving non-negative data, zero-inflated distributions, or mixed discrete-continuous outcomes.
- Extending these objectives to multi-output regression will make XGBoost more versatile and competitive.

**Proposed Solution:**
- Extend the implementation of the tweedie and poisson objectives to handle multi-output regression tasks.
- Ensure compatibility with existing XGBoost features like early stopping, evaluation metrics, and prediction interfaces.
- Additional Context:
- Multi-output regression is supported for objectives like reg:squarederror and reg:linear, so adding Tweedie and Poisson support should align with existing multi-output functionality.

**Environment:**
- XGBoost Version: x.x.x
- Python Version: x.x
- System Information: (Optional, add system details if needed)

**Comment by trivialfis** [comment]
Thank you for raising the issue.

Yes, it's our goal to support all objectives for multi-output. At the moment, it's a priority issue instead of a technical issue. Progress is being tracked at https://github.com/dmlc/xgboost/issues/9043 .

I will close this issue to focus the discussion in the linked thread.
