### ISSUE TITLE
Trouble compiling the master branch with GPU support

### ISSUE THREAD

**Issue by kiran-vj** [dmlc/xgboost#11128]
I am trying to compile the master branch with GPU support. But facing some out of scope errors for basic cuda runtime/driver api functions such as :

**1. xgboost/src/common/cuda_dr_utils.cc:25:5: error: 'cudaDriverEntryPointQueryResult' was not declared in this scope**

**2. error: 'cudaDriverEntryPointSuccess' was not declared in this scope; did you mean 'cudaGetDriverEntryPointFlags'**

**3. error: 'CU_DEVICE_ATTRIBUTE_HOST_NUMA_ID' was not declared in this scope; did you mean 'CU_DEVICE_ATTRIBUTE_PCI_BUS_ID'?**

But I am able to compile older versions (release_1.7) properly in the same environment.

CUDA Compiler Information: CUDA compiler identification is NVIDIA 11.7.64
I am also explicitly setting a CMAKE_CUDA_COMPILER in the cmake command to ensure it picks up the right one. 

Do I need to upgrade/modify my cuda installation?

**Comment by trivialfis** [comment]
Yes, please upgrade your CUDA installation to 12.4+.

**Comment by trivialfis** [comment]
CUDA 12.2 should work fine. For newer CUDA versions, we require an upstream version of cccl instead of the bundled one.

**Comment by trivialfis** [comment]
Feel free to reopen if there are other issues.
