### ISSUE TITLE
save_model with ntree_limit

### ISSUE THREAD

**Issue by brunodoamaral** [dmlc/xgboost#1114]
Training xgb with `early_stopping_rounds` parameter results in a model with `best_iteration` property.

However, upon saving the model for later use, with `save_model`, this information is lost and one cannot use it to call `predict` using the `ntree_limit` parameter.

My suggestion is to include the `ntree_limit` parameter in `save_model` function in order to save the desired round.

**Comment by pommedeterresautee** [comment]
scores are in the table, easy to retrieve the position of the min.

**Comment by khotilov** [comment]
@brunodoamaral `best_iteration` [is currently saved](https://github.com/dmlc/xgboost/blob/fb0fc0c580bbf4c3a2030aeabc644eeda103fcfa/python-package/xgboost/callback.py#L237) with a binary model as a model attribute which you can retrieve as `int(bst.attr('best_iteration'))`
