### ISSUE TITLE
xgb.plot.tree not plotting

### ISSUE THREAD

**Issue by dutch-irish** [dmlc/xgboost#1116]
Hi,

When I try to use xgb.plot.tree, I get a parser error and can't plot. For example, if I do:

`library(xgboost)`
`data(agaricus.train, package='xgboost')`
`train <- agaricus.train`
`bst <- xgboost(data = train$data, label = train$label, max.depth = 2,
               eta = 1, nthread = 2, nround = 2,objective = "binary:logistic")`
`xgb.plot.tree(agaricus.train$data@Dimnames[[2]], model = bst)`

I get a firefox tab containing:

`graph LR;0-0(odor=none)-->|>= -1.00136e-05|0-2>spore-print-color=green];0-0(odor=none
Cover: 1628.25`
...
`parse error with graph LR;0-0(odor=none)-->|>= -1.00136e-05|0-2>spore-print-color=green];
...
x is undefined`

[I took out some of the middle of the output to make it shorter].

I am running R 3.2.3, xgboost 0.4-3, firefox 45.0.1, on Fedora 23 (x86_64). I'd love some help solving this. Thanks!

**Comment by khotilov** [comment]
It's fixed in the github version: #970 
And please use search before submitting an issue.

**Comment by dutch-irish** [comment]
Sorry, I missed that thread. The solution from  #970  worked. Thanks so much!
