### ISSUE TITLE
Setting num_rounds param when used with sci-kit wrapper?

### ISSUE THREAD

**Issue by ralston3** [dmlc/xgboost#1117]
Is there any way to set the <code>num_rounds</code> parameter when fitting the booster using the scikit-learn wrapped implementation? I ask because when fitting on a particular training set, without an available <code>eval_set</code>, the training goes on for 2000+ rounds (which is going to lead to a terribly overfit model). I know that the <code>num_rounds</code> param is available when using (what I call) the _authentic_ booster (i.e. <code>xgb.train()</code>), but just wanted to ask if it could be set using the <code>XGBClassifier()</code> implementation.

**Comment by Far0n** [comment]
You are looking for the wrapper parameter **n_estimators**

**Comment by ralston3** [comment]
thanks!
