### ISSUE TITLE
Feature importance XGBoost vs Random Forest?

### ISSUE THREAD

**Issue by astrude** [dmlc/xgboost#1119]
There is a very important categorical variable which is coming out to be the least significant in XGBoost but most important in Random Forest. Why could this be happening? My XGBoost model is doing well in terms of Testset MSE in comparison to Random Forests, Only this importance is sort of peculiar? Thanks in advance

**Comment by pommedeterresautee** [comment]
Basically, when there are several correlated features, boosting will tend to choose one and use it in several trees (if necessary). Other correlated features won t be used a lot (or not at all).

It makes sense as other correlated features can't help in the split process anymore -> they don't bring new information regarding the already used feature. And the learning is done in a serial way.

Each tree of a Random forest is not built from the same features (there is a random selection of features to use for each tree). Each correlated feature may have the chance to be selected in one of the tree. Therefore, when you look at the whole modele it has used all features. The learning is done in parallel so each tree is not aware of what have been used for other trees.

If the explanation helped you, please close the issue.

Kind regards,
Michaël

**Comment by astrude** [comment]
Thanks for the response :) 
I'd like to share an interesting observation I've come across while SPARK Implementation of XGBoost Feature Importance. I am using a categorical variable which is the most significant and I am one hot encoding before feeding into XGBoost. 
Whenever I grow shallow trees and many of them, the categorical variable is coming out to be the most important variable like expected.
But just when I start growing deeper trees, my categorical variable importance is reducing drastically this i believe is because limited amount of variation in categorical variable in relative to continuous variables. Please share your thoughts, thanks in advance!

**Comment by pommedeterresautee** [comment]
When you grow too many trees, trees are starting to be look very similar (when there is no loss remaining to learn). Therefore the dominant feature will be an even more important.
Having shallow trees reinforce this trend because there are few possible important features at the root of a tree (shared features between trees are most of the time the one at the root of it).
So your results are not surprising.

In this case, you may have interesting results with random selection of columns (rate around 0.8).
Decreasing ETA may also help (keep more loss to explain after each iteration).

**Comment by astrude** [comment]
Hi,

Are you sure about the subsequent trees to be looking similar? Because to the best of my knowledge every subsequent tree in boosting would be based on the errors that are not explained by the previous trees thereby making them dissimilar/complementary trees. 

Also, I have reduced the ETA from 0.4 to smaller 0.2,0.1,0.0001 with the same depth and trees, I don't seem to see a significant improvement in feature importance values/order.

Can you please share the intuition behind the variable importance calculation in XGBoost? I have gone through the original code, I'm finding it difficult to read. All I got is the importance is calculated based on co-occurrence frequency with target variable. And there is very less documentation available on how its calculated. Would love to know how it's calculated.

Thanks for your time and patience, appreciate it! :)

**Comment by khotilov** [comment]
@astrude : 
if you believe this in an issue with xgboost, please provide a clear, coherent description of your issue and of your data, preferably with a reproducible example. If not, then please close the issue.

Currently implemented Xgboost feature importance rankings are either based on sums of their split gains or on frequencies of their use in splits.

Other than the mentioned earlier correlation-related effects, keep in mind that most tree-based models are biased towards high cardinality/continuous features. I notice fairly often that binomial features get somewhat low-balled by trees in mixed types data.

**Comment by astrude** [comment]
Thanks for your inputs, @khotilov @pommedeterresautee !
