### ISSUE TITLE
XGBoost installation in Anaconda 3.4, Windows 10

### ISSUE THREAD

**Issue by RobsonGit** [dmlc/xgboost#1120]
Hello,

I appreciate help on issue below.
I was trying to install XGBoost in Anaconda 3.4 (on Windows 10). After trying several methods mentioned on web to build the package, with mingw32 and Visual Studio among others, I finally found this webpage which helped me:
https://dnc1994.com/2016/03/installing-xgboost-on-windows/
This allowed me to create xgboost.exe and build the package finally with "python setup.py install". Unfortunately, after building the package, Anaconda still cannot import the XGBoost. I get the message:
**OSError                                   Traceback (most recent call last)
<ipython-input-2-8ecdb6c2117b> in <module>()
     12 from sklearn.cross_validation import train_test_split
     13 import random; random.seed(13)
---> 14 import xgboost as xgb
     15 
C:\Anaconda3\lib\site-packages\xgboost-0.4-py3.5.egg\xgboost\__init__.py in <module>()
      9 import os
     10 
---> 11 from .core import DMatrix, Booster
     12 from .training import train, cv
     13 from . import rabit

C:\Anaconda3\lib\site-packages\xgboost-0.4-py3.5.egg\xgboost\core.py in <module>()
     81 
     82 # load the XGBoost library globally
---> 83 _LIB = _load_lib()
     84 
     85 def _check_call(ret):

**
and more like this. Can aynone help me with this problem?
I didn't expect that installation of XGBoost can be such a huge problem...

Best regards

**Comment by phunterlau** [comment]
Can you put the ending 40 lines of your error message? From the current lines, I can guess it is because of the python path, but better to see the real error messages which show the true reason. P.S. Installing XGBoost is not a big deal, but when it comes to Windows, some extra work is needed.

**Comment by RobsonGit** [comment]
Hi,

 

Here is the full log (slightly different now as I was trying to reinstall several times, but still referring to the same issue). The last sentence is in Polish and says something like: "OSError: [WinError 1114] Procedure of loading the dll library (DLL) failed".
What is very strange is that when I removed Anaconda for a while and tried to install Enthopy Canopy the XGB seemed to work. But with Canopy I immediately went into further problems with other Python packages and multiprocessing issues (now I'm afraid I can go to the same problems with Anaconda even if I succeed with XGB installation in Anaconda).
 
 
OSError                                   Traceback (most recent call last)
<ipython-input-7-745aa3a2d734> in <module>()
----> 1 import xgboost as xgb
 
C:\Anaconda3\lib\site-packages\xgboost-0.4-py3.5.egg\xgboost\__init__.py in <module>()
      9 import os
     10 
---> 11 from .core import DMatrix, Booster
     12 from .training import train, cv
     13 from . import rabit
 
C:\Anaconda3\lib\site-packages\xgboost-0.4-py3.5.egg\xgboost\core.py in <module>()
     81 
     82 # load the XGBoost library globally
---> 83 _LIB = _load_lib()
     84 
     85 def _check_call(ret):
 
C:\Anaconda3\lib\site-packages\xgboost-0.4-py3.5.egg\xgboost\core.py in _load_lib()
     75     if len(lib_path) == 0:
     76         return None
---> 77     lib = ctypes.cdll.LoadLibrary(lib_path[0])
     78     lib.XGBGetLastError.restype = ctypes.c_char_p
     79     return lib
 
C:\Anaconda3\lib\ctypes\__init__.py in LoadLibrary(self, name)
    423 
    424     def LoadLibrary(self, name):
--> 425         return self._dlltype(name)
    426 
    427 cdll = LibraryLoader(CDLL)
 
C:\Anaconda3\lib\ctypes\__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    345 
    346         if handle is None:
--> 347             self._handle = _dlopen(self._name, mode)
    348         else:
    349             self._handle = handle
 
OSError: [WinError 1114] Procedura inicjowania biblioteki dołączanej dynamicznie (DLL) nie powiodła się

 

 

Best regards

**Comment by phunterlau** [comment]
@RobsonGit can you post your 'PYTHONPATH' env variable?

**Comment by RobsonGit** [comment]
@phunterlau 
Hello,
I have no such environmental variable in Windows. I was trying to set it but with no success - this however may be just the issue that I'm putting incorrect path. Can you please let me know what the path should be?
My installation folder for Anaconda is C:\Anaconda3 and xgboost was built in folder C:\Anaconda3\Lib\site-packages\xgboost\python-package. After building I could see the file xgboost.exe in C:\Anaconda3\Lib\site-packages\xgboost and additionally new folder appeared with name C:\Anaconda3\Lib\site-packages\xgboost-0.4-py3.5.egg
Thank you for your help.

Best regards

**Comment by RobsonGit** [comment]
Hello again,

 

Can you please help with my question regarding PYTHONPATH?

 

Regards

**Comment by mathkann** [comment]
Hi,
I faced a similar issue  on Anaconda 3.4 in Windows 10 ... then I read somewhere it might be due to the problem with the latest TDM-GCC ... I tried it with  http://www.drangon.org/mingw/ using the instructions  on http://stackoverflow.com/a/35119904/3075634 and it worked for me.

P.S: After downloading the zip file from  http://www.drangon.org/mingw/, please add it to your path.

**Comment by RobsonGit** [comment]
Thank you for response, mathkann.
I was trying to install xgboost this way previously already and unfortunately it did not work. I don't know what is going on but it seems that installation of xgboost in Anaconda in Windows 10 requires lots of luck. At this time I'm giving up with using xgboost in Python (thus Anaconda gets deleted as well). I'm quite disappointed to see this as previously I've heard Python is quickly developing. R seems to have big advantages in such basic area as package installation field when compared to Python (at least in Windows 10).
Closing the issue with no solution.

Best regards
