### ISSUE TITLE
R: NA results for RealCover and RealCover % in xgb.importance

### ISSUE THREAD

**Issue by vinhdizzo** [dmlc/xgboost#1124]
Hi,

I'm currently using the drat version of xgboost in R.  I'm following [this](http://xgboost.readthedocs.org/en/latest/R-package/discoverYourData.html?highlight=importance#feature-importance) example by passing in both the model matrix and the output vector into `xgb.importance` to get the `RealCover` and `RealCover %` columns in the resulting `data.table`.  However, I'm getting NA for both.  My function call is

```{r}
importanceRaw <- xgb.importance(colnames(xMat), model=bst, data=xMat[trainIndex, ], label=output_vector[trainIndex])
```
`xMat` is a dense matrix, `bst` came from `xgb.train`, and `output_vector` is a vector of 0's and 1's.  Thank you for your help!

**Comment by khotilov** [comment]
#1092 
Please use search next time.
