### ISSUE TITLE
using xgboost in c++ project without putting own main.cpp in xgboost-library

### ISSUE THREAD

**Issue by barbara73** [dmlc/xgboost#1127]
Hi, is there a way to use this library without putting my own main.cpp into xgboost package? If I include c_api.h, I always get an error, because it cannot find rabit.h and so on… Or do I have to include cli_main.cc?? I am using Xcode on MacOS.
thanks

**Comment by khotilov** [comment]
You can reuse parts of cli_main.cc and adapt them to your own project. xgboost depends on the submodules dmlc-core and rabit, so you would need to point to their include locations and to link to them.

**Comment by barbara73** [comment]
Thanks a lot problem solved
