### ISSUE TITLE
Question about setting prior probabilities: scale_pos_weight  vs. base_score 

### ISSUE THREAD

**Issue by hxd1011** [dmlc/xgboost#1129]
Hi, 

All can anyone tell me what's the difference between setting 

**scale_pos_weight vs. base_score** for an imbalanced data?

Thank you very much !

**Comment by khotilov** [comment]
base_score is just the score that boosting starts from
scale_pos_weight is a factor for weighting positive class cases during boosting
Also see #799 

And note that the "issues" section is not a really a place for general questions.
