### ISSUE TITLE
Distributed XGBoost YARN

### ISSUE THREAD

**Issue by gao8954** [dmlc/xgboost#1137]
# Container: container_1461296172622_0011_02_000001 on bigdata214_42222

LogType:stderr
Log Upload Time:Fri Apr 22 14:09:03 +0800 2016
LogLength:87
Log Contents:
Error: Could not find or load main class org.apache.hadoop.yarn.dmlc.ApplicationMaster
End of LogType:stderr

LogType:stdout
Log Upload Time:Fri Apr 22 14:09:03 +0800 2016
LogLength:0
Log Contents:
End of LogType:stdout

**Comment by gao8954** [comment]
jar包路径也指定了还是报这个错，咋整呢

**Comment by chengdianxuezi** [comment]
I have encountered this problem, Have you finally solved it ?
