### ISSUE TITLE
how to read the xgboost-gbdt sourece code?

### ISSUE THREAD

**Issue by leoli2012** [dmlc/xgboost#1144]
hi, guys, i want read the gbdt code in xgboost , but i don't know  where the main function file is and  which files are the gbdt algorithm file ......could you  give me some adivce? thanks

**Comment by tqchen** [comment]
- read the headers https://github.com/dmlc/xgboost/tree/master/include/xgboost which are heavily commented and gives relation of the modules.

- main file is in here https://github.com/dmlc/xgboost/blob/master/src/cli_main.cc
