### ISSUE TITLE
Does XGBoost contain a open-source license?

### ISSUE THREAD

**Issue by sachinvernekar** [dmlc/xgboost#1147]
Hi

I am working on an on-line challenge http://physionet.org/challenge/2016/
The challenge allows only open-source and free to distribute software.

On being asked if I could use XGBoost for the challenge, the reply was as follows

"As for xgboost, there does not appear to be any license for this
package (although a few files contain the not-especially-illuminating
statement "Copyright (c) 2014 by Contributors".)  If it is not free
and open source software, we cannot use it or distribute it."

Can you please let me know if XGBoost has any open-source license such as http://www.gnu.org/licenses/gpl-3.0.txt which the freedom to modify and redistribute?

Thanks
Sachin

**Comment by tqchen** [comment]
see https://github.com/dmlc/xgboost#license

**Comment by sachinvernekar** [comment]
Thank you very much!!!
Its opensource!! Now I can use this software for the challenge.
