### ISSUE TITLE
[jvm-packages] Xgboost4j on windows: cannot create jni because makefile does not find jdk/include folder

### ISSUE THREAD

**Issue by adverley** [dmlc/xgboost#1148]
Hello

I'm trying to build the jvm package of XgBoost. I followed the steps on the [IBM blog](https://www.ibm.com/developerworks/community/blogs/jfp/entry/Installing_XGBoost_For_Anaconda_on_Windows?lang=en) and now try to complete the installation in Java instead of Python. 

I run the create_jni.sh file manually from mingw64 because the mvn package command does not recognize the .sh file as a valid WIN32 application. When I enter the commands in the create_jni.sh file one by one in mingw, the terminal throws an error on the `make jvm` command:
![image](https://cloud.githubusercontent.com/assets/5717716/14799345/492969fe-0b3c-11e6-9378-36fc2be13245.png)

It can't find the include folder of my java_home although it looks like it is set correctly:
![image](https://cloud.githubusercontent.com/assets/5717716/14799371/660f3710-0b3c-11e6-80d4-6220b56779d6.png)

Any tips to solve this?

**Comment by CodingCat** [comment]
that ` ` (space) between `Program` and `Files` causes the error, the system takes File\Java\* as a command

**Comment by adverley** [comment]
That makes sense, thanks for showing me! Any way around this in the Unix-world? It doesn't look very handy to change my program Files folder name or reinstall java to c:/ :)

**Comment by CodingCat** [comment]
use the `\` tricks

![image](https://cloud.githubusercontent.com/assets/678008/14800085/947986f2-0b0d-11e6-9ec4-3418a8953192.png)

**Comment by CodingCat** [comment]
Sorry, 
![image](https://cloud.githubusercontent.com/assets/678008/14800097/a21d8d08-0b0d-11e6-8714-a66ea85985d9.png)

**Comment by adverley** [comment]
Thanks for the tip. I used the \trick to change the java_home variable in the makefile script. The script now searches for jni_md.h but can't find it:
![image](https://cloud.githubusercontent.com/assets/5717716/14809308/6e67ad16-0b8c-11e6-87a0-b4e57d237328.png)
This is because the jni_md.h is in the java_home/include/win32 directory. If I copy paste that content to the include folder, it throws this error among other similar errors:
![image](https://cloud.githubusercontent.com/assets/5717716/14809334/9cb19b8c-0b8c-11e6-9db7-4526cc3abd31.png)
At the end of the log, it says that the makefile failed at line 125 which looks like this:
![image](https://cloud.githubusercontent.com/assets/5717716/14809466/89190ef6-0b8d-11e6-9b01-e315dc8b8608.png)
Maybe there is still a problem with how I set my java path?

**Comment by CodingCat** [comment]
are you using 32-bits system?

**Comment by adverley** [comment]
I use a 64bit Windows system. I run Mingw64 by opening git bash in my xgboost directory. My make command is aliased by `mingw32-make` which I also used to execute the first `cp make/mingw64.mk config.mk; make -j4`command to build the dll. First time I did this, the compiler complained he was 32bit so I installed the 64 bit mingw and put that on my path, enabling a successful compilation. Long story short: I am reasonably sure I am running 64 bit but is there a way to be sure? 

`Make -v` tells me it is a x86_64-w64-mingw32 version. 

This is my complete screen log when trying the command:
![image](https://cloud.githubusercontent.com/assets/5717716/14832280/c84ec158-0bf9-11e6-9447-0e70e4072f95.png)

Thanks for the help already CodingCat :-)

**Comment by adverley** [comment]
In include/jni.h there is a line that tries to include jni_md.h but it is in the win32 folder so I changed the include statement as follows:
![image](https://cloud.githubusercontent.com/assets/5717716/14850989/0167acb0-0c7d-11e6-8eba-93f1f1742875.png)

Now the compiler complains about method calls in xgboost4j.cpp that are not available in the jni.h. You can see the errors in this [paste](http://pastebin.com/qHmaJ48r). Note that I use the latest version of java 8. These errors match with [this ](https://github.com/dmlc/xgboost/issues/1015) issue posted in this project. Is there already a solution for this?

**Comment by adverley** [comment]
I managed to build the .so file by doing the necessary casts in the xgboost4j.cpp file to match with jni.h method headers. I then placed the .so and .dll files in the main/resources directory and executed mvn package command. When I use the generated jars, I get a `UnsatisfiedLinkError: ml.dmlc.xgboost4j.java.XGBoostJNI.XGDMatrixCreateFromMat.` So the .dll files are included but there is still something going wrong.

**Comment by CodingCat** [comment]
it looks like your JDK is 32 bits?

**Comment by CodingCat** [comment]
we do not have support on 32 bits JDK right now

**Comment by adverley** [comment]
I only have 64bit jdk's so that's not the issue

**Comment by CodingCat** [comment]
when you say you put file under main/resources, you mean main/resources or main/resources/lib?

**Comment by CodingCat** [comment]
when you say you put compiled lib file under main/resources, 

do you mean 

(1) you have changed the pom.xml so that when you run `mvn package`, it will not run create_jni.sh automatically?

(2) you put the so file under main/resources, not the expected main/resources/lib ?

**Comment by adverley** [comment]
(1) Indeed, I disabled the execution of the create_jni.sh in the pom.xml file and run the commands manually. I have to say though that running the .sh file directly from git bash throws an error that the `make `command is not found. That's why I run the `make jvm` part manually. **Do I need the .so file on Windows?** 

(2) I put the .so and .dll files under main/resources/lib. It is picked up during the JAR creation because the xgboost jar can call the .dll file.

**Comment by CodingCat** [comment]
so, the current situation is that you passed all test when run mvn package, but cannot use the generated jar?

OK,

(1) would you post the output of `jar -tf path_to_your_jar`

(I don't think there is any problem in the output of (1), just to make sure of that, )


(2) I don't know how you make the conversions between the types, but if you changed the signatures of methods, you need to change it accordingly in ml.dmlc.xgboost4j.java.XGBoostJNI class, 

(the standard flow is  that you change the signature of methods in ml.dmlc.xgboost4j.java.XGBoostJNI first and then use `javah` to generate the cpp files)

**Comment by adverley** [comment]
I'll first answer your questions followed by the steps I followed so far. 
(0) I generated the JAR files but I skipped the tests in the `mvn package` process because the tests fail. 
(1) You can find the content of the jar [here](http://pastebin.com/uktedt5M).
(2) I don't change method headers. I only do casts in the xgboost4j.cpp file. You can find it [here](http://pastebin.com/aFiwReS1).

# The steps I followed so far
1. git clone --recursive https://github.com/dmlc/xgboost
2. install mingw64 and make sure it is 64bit version (x86_64 setting during setup)
3. put the installation folder of mingw64 on windows env path
4. go to xgboost directory and git bash there 
5. enter following commands in git bash: 
		`alias make='mingw32-make'`
		`cp make/mingw64.mk; make -j4`

	! This differs from the IBM blog that states you have to do
		`$ alias make='mingw32-make'`
		`$ cd dmlc-core`
		`$ make -j4`
		`$ cd ../rabit`
		`$ make lib/librabit_empty.a -j4`
		`$ cd ..`
		`$ cp make/mingw64.mk config.mk`
		`$ make -j4`
		
6. Edit the xgboost4j.cpp file: I make sure that all calls to the javahome/include/jni.h methods have the right arguments in xgboost4j.cpp. I also make sure all values returned by the methods in jni.h are compatible with the variables in the xgboost4j.cpp by doing casts. 
**The important thing to notice here is that I don't change method headers, I only do casts in the .cpp file. **
	For example:
		`cbatch.offset = (long int*) jenv->GetLongArrayElements(joffset, 0);` 
	You can find the edited file [here](http://pastebin.com/aFiwReS1).
7. Export java home in git bash: 	`export JAVA_HOME=$(C:/Program\ Files/Java/jdk1.8.0_91)`
8. Open the create_jni.sh file in /jvm-packages folder with a text editor 
9. Enter commands from create_jni.sh one by one in git bash
	!  `pushd `dirname $0` > /dev/null` command fails 
10. Make sure the generated files from previous step are present in jvm-packages/xgboost4j/source/main/resources
11. Go to the pom file and delete the execution of the create_jni.sh file 
12. Go to git bash and run following commands:

		Mvn clean

		export MAVEN_OPTS="-Xmx4g -XX:MaxPermSize=512M -XX:ReservedCodeCacheSize=512m"

		Mvn package -DskipTests -Dcheckstyle.skip=true
	! I skipped the tests and checkstyle because they fail
13. Check whether your JAR's are generated in the /target directory
14. Go to github xgboost issues and request help from CodingCat 

Is there a step I go horrendously wrong?

**Comment by CodingCat** [comment]
Let's try this

(1) remove all files except `xgboost.dll` in lib/ directory 

(2) move (not cp) lib/xgboost.dll to xgboost4j/source/main/resources

recompile

**Comment by CodingCat** [comment]
sorry, 

(1) remove all files except xgboost4j.dll in lib/ directory

(2) move (not cp) lib/xgboost4j.dll to xgboost4j/source/main/resources

**Comment by Craigacp** [comment]
I'm running into this exact issue, building on 64-bit Windows, with a 64-bit JVM, using mingw64. Unfortunately the MS ABI specifies that long is 4 bytes, and gcc inside mingw64 respects that, whereas a Java long is 8 bytes on all platforms. 

I could do the casts that @adverley mentioned earlier, but if XGBoost expects there to be 64 bit longs and I truncate them to 32 bit I'd expect a lot of bad things to happen. Does XGBoost compile properly with a 32 bit long? I suspect all the ming64 builds use a 32-bit long and presumably it's working for some people.

**Comment by adverley** [comment]
The casting did not work for me @Craigacp. I guess I got lost somewhere along the way.

**Comment by Craigacp** [comment]
Ok. I suspect this might require going through the codebase to figure out if anything requires a long to be 64 bits.

The mingw64 compiler is odd. Running a few tests gives:
sizeof(int) = 4, sizeof(long)=4, sizeof(long long)=8, sizeof(void *)=8
whereas the same code on my Ubuntu box and my Mac is 
sizeof(int)=4 sizeof(long)=8 sizeof(long long)=8 sizeof(void*)=8

**Comment by Craigacp** [comment]
@CodingCat do you want me to make a separate issue for the 32 bit long problem, or should this one be reopened?
