### ISSUE TITLE
effective learning curve calculation

### ISSUE THREAD

**Issue by hushchyn-mikhail** [dmlc/xgboost#115]
Is there any way to get learning curve?
I use predict() method to compute points for the learning curve. But this approach takes 
from 1 to num_round trees to make prediction for the each point.

**Comment by nikoltoll** [comment]
Solution with capture.output:

output <- capture.output(bst <- xgb.train(data=dtrain, max.depth=2, eta=0.01, subsample = .5, nthread = 1, nround=1000, watchlist=watchlist, objective = "binary:logistic"))
trainErr <- as.numeric(regmatches(output,regexpr("(^|\\d+)\\.\\d+",output)))   ##first number
testErr <- as.numeric(substr(output,nchar(output)-7,nchar(output)))               ##second number
plot(1:1000,trainErr, type = "l")
lines(1:1000,testErr, type = "l", col = "red")

**Comment by arogozhnikov** [comment]
@nikoltoll 
Relying on parsing output... seriously? I wouldn't expect such code to work year after.

Solution to this question is well-known - `staged_predict_proba`. 

This gives ability to compute learning curve for any metric for any trained model on any dataset.

This gives ability to compute stage predictions after folding / bagging / whatever. 

I have no idea why it is not implemented in current wrapper.

**Comment by terrytangyuan** [comment]
You are welcomed to submit a pull request for this.

**Comment by tqchen** [comment]
closing for now, we are revisiting the interface issues in the new major refactor #736 Proposal to getting staged predictions is welcomed

**Comment by mhmoudr** [comment]
has it been implemented? if not I am ok to work on a pull request.
