### ISSUE TITLE
No Feature Names in R for xgb.DMatrix

### ISSUE THREAD

**Issue by quartox** [dmlc/xgboost#1151]
Using the R package (installed from github last week), the xgb.DMatrix method does not return an object with feature names. This means that the trained model does not have feature names and xgb.importance requires feature names as input. I can see in source (https://github.com/dmlc/xgboost/blob/master/R-package/R/xgb.DMatrix.R) where feature names should be added to the attribute .Dimnames of xgb.DMatrix, but this does not work for me.

Minimal reproducible example:

```
library(xgboost)
data(agaricus.train,package='xgboost')
train <- agaricus.train
dtrain <- xgb.DMatrix(train$data,label=train$label)
print(attributes(dtrain))
print(dimnames(dtrain))
print(colnames(dtrain))
bst <- xgboost(data = dtrain, max.depth = 2, eta = 1, nthread = 2, nround = 2,objective = "binary:logistic")
print(xgb.importance(model=bst))
print(xgb.importance(model=bst,feature_names=colnames(train$data)))
```

**Comment by hxd1011** [comment]
yes, I have same problem and same fix: manually add colnames.

**Comment by khotilov** [comment]
The example is working as I would currently expect it to work. I'm not sure why are you stating that " the xgb.DMatrix method does not return an object with feature names". I see that `colnames(dtrain)` returns a vector of names that was sorted in the second element of `.Dimnames`. If you don't see a `.Dimnames` attribute in `dtrain` in this example (`str(dtrain)`), please update to the latest version from github.

As for the `xgb.importance`'s `feature_names` parameter, so far it was always necessary to manually set it. The `xgb.Booster` class doesn't store the names of model features. I was thinking about it, but it's not yet implemented.

**Comment by ahmedahmedov** [comment]
I am also having the same issue. Not only that, but also, it is impossible to see the content of an xgb.DMatrix - that is, it is impossible to print it. This is obviously not very handy if you want to analyze the input data. Basically, once you contstruct an xgb.DMatrix from either a dense or a sparse matrix, you lose all the metadata associated with it - no colnames, no printable data. It certainly sucks.

**Comment by khotilov** [comment]
Again: to have colnames in xgb.DMatrix, please update to the latest version from github.

The intent of `xgb.DMatrix` was to pass the data to xgboost, not to analyze it. Thus, there was no interface created for a user to get data out of a DMatrix. There is an issue #874 about discussing how to possibly memory-map a data.frame into a DMatrix, which would be a more transparent way, but there was not much progress yet.
