### ISSUE TITLE
Upload Python binary package to conda-forge

### ISSUE THREAD

**Issue by sinhrks** [dmlc/xgboost#1157]
conda-forge is a place to upload community led Python anaconda packages. Because XGBoost has some installation issues (especially on Windows), uploading binaries should help easier deployment.

- https://conda-forge.github.io/

I've prepared a recipe(compilation script) for xgboost and going to submit it to conda-forge if it looks useful. 

**Script**

it must be submitted to conda-forge repo, the below PR is reviewing purpose. Windows binary is not included yet as there seems to be a change after the latest release (0.47). Going to work on Windows after the next release. 

- https://github.com/sinhrks/staged-recipes/pull/1

**Comment by sinhrks** [comment]
Ah I overlooked conda package for Linux/Mac already exists in conda main repo, not conda-forge. Will fix it. 

- https://github.com/conda/conda-recipes/tree/master/python/xgboost

**Comment by jakirkham** [comment]
Let us know if you need help submitting. 😄

**Comment by rth** [comment]
> Ah I overlooked conda package for Linux/Mac already exists in conda main repo, not conda-forge. Will fix it.
>          https://github.com/conda/conda-recipes/tree/master/python/xgboost

@sinhrks True, but when I'm currently running `conda search xgboost` no packages are found, so submitting a recepe to conda-forge could be quite useful. I can also help if necessary (trying to get rid of the C++ compiler in my package dependencies...).

**Comment by stephanecollot** [comment]
Hi guys,
Thanks a lot for the conda-forge package, it helps!
I was wondering if you could make a version for Python 3.4? (There is only 2.7, 3.5 and 3.6 https://anaconda.org/conda-forge/xgboost/files)
I tried to make it myself with "conda build recipe", but I didn't succeed so far.

Thanks for your help

**Comment by jakirkham** [comment]
So conda-forge dropped Python 3.4 support shortly after Python 3.6 was released. Unfortunately it is too much of a strain on resources to maintain more than 3 Python versions at a time.
