### ISSUE TITLE
Win8+Py2.7: what is the missing part?

### ISSUE THREAD

**Issue by RamonYeung** [dmlc/xgboost#1165]
I install XGboost simple type 'pip install xgboost' at terminal. 

When comes to Windows platform, I have done the following steps and failed.
1. git clone recursively. 
2. add git submodule (BUT I don't think it helps anyway.)

when: 
```linux
cd python-package && python setup.py install
```
returns:
```linux
Traceback (most recent call last):
  File "setup.py", line 19, in <module>
    LIB_PATH = libpath['find_lib_path']()
  File "xgboost/libpath.py", line 45, in find_lib_path
    'List of candidates:\n' + ('\n'.join(dll_path)))
__builtin__.XGBoostLibraryNotFound: Cannot find XGBoost Libarary in the candicate path, did you install compilers and run build.sh in root path?
List of candidates:
D:\Anaconda2\Lib\site-packages\xgboost\python-package\xgboost\libxgboost.dll
D:\Anaconda2\Lib\site-packages\xgboost\python-package\xgboost\../../lib/libxgboost.dll
D:\Anaconda2\Lib\site-packages\xgboost\python-package\xgboost\./lib/libxgboost.dll
D:\Anaconda2\Lib\site-packages\xgboost\python-package\xgboost\../../windows/x64/Release/libxgboost.dll
D:\Anaconda2\Lib\site-packages\xgboost\python-package\xgboost\./windows/x64/Release/libxgboost.dll
```
when: 
```linux
cp make/mingw64.mk config.mk; mingw32-make -j4
```
returns: 
```linux
bash: mingw32-make: command not found
```

Master tqchen plz help me out. Thx!!

**Comment by RamonYeung** [comment]
```linux
bash: mingw32-make: command not found
```
fixed.

Anybody will come to this trouble because of **not having the right *PATH* global environment variable setting.**

**Comment by RamonYeung** [comment]
When you successfully build all the files clone from the origin master by using
```linux
cp make/mingw64.mk config.mk; mingw32-make -j4
```
type next row in the terminal
```linux
cd python-package && python setup.py install
```
which should do the job and allow you to go XGBoost!

**Comment by jqjjcp** [comment]
how can you sove the problem(__builtin__.XGBoostLibraryNotFound: Cannot find XGBoost Libarary in the candicate path, did you install compilers and run build.sh in root path?
List of candidates:)?many thx
