### ISSUE TITLE
error while building jvm-packages on windows and linux environment

### ISSUE THREAD

**Issue by ljzzju** [dmlc/xgboost#1167]
These are the steps how I build the project:
(1) git clone ******
     git submodule init
     git submodule update
(2) go into the parent folder and run command "make"
     everything seems ok
**$ make
g++ -m64 -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iincl
ude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -o
xgboost  build/cli_main.o build/learner.o build/logging.o build/common/common.o
build/c_api/c_api_error.o build/c_api/c_api.o build/data/simple_dmatrix.o build/
data/sparse_page_raw_format.o build/data/data.o build/data/simple_csr_source.o b
uild/data/sparse_page_writer.o build/data/sparse_page_source.o build/data/sparse
_page_dmatrix.o build/gbm/gbm.o build/gbm/gblinear.o build/gbm/gbtree.o build/me
tric/multiclass_metric.o build/metric/elementwise_metric.o build/metric/rank_met
ric.o build/metric/metric.o build/objective/regression_obj.o build/objective/ran
k_obj.o build/objective/objective.o build/objective/multiclass_obj.o build/tree/
tree_model.o build/tree/updater_colmaker.o build/tree/updater_skmaker.o build/tr
ee/updater_sync.o build/tree/updater_refresh.o build/tree/updater_histmaker.o bu
ild/tree/tree_updater.o build/tree/updater_prune.o dmlc-core/libdmlc.a rabit/lib
/librabit_empty.a  -pthread -lm  -fopenmp**

(3) Then I type "cp make/mingw64.mk config.mk" and "make jvm no_omp=0"
     as "make jvm no_omp=0" has ever existed in ./jvm-packages/create_jni.sh

**void ReleaseIntArrayElements(jintArray array,
          ^
jvm-packages/xgboost4j/src/native/xgboost4j.cpp: In function 'jint Java_ml_dmlc_
xgboost4j_java_XGBoostJNI_XGBoosterLoadRabitCheckpoint(JNIEnv_, jclass, jlong, j
intArray)':
jvm-packages/xgboost4j/src/native/xgboost4j.cpp:652:47: error: invalid conversio
n from 'int_' to 'const jint\* {aka const long int_}' [-fpermissive]
   jenv->SetIntArrayRegion(jout, 0, 1, &version);
                                               ^
In file included from jvm-packages/xgboost4j/src/native/./xgboost4j.h:2:0,
                 from jvm-packages/xgboost4j/src/native/xgboost4j.cpp:18:
D:\InstalledPrograms\jdk1.7/include/jni.h:1779:10: error:   initializing argumen
t 4 of 'void JNIEnv_::SetIntArrayRegion(jintArray, jsize, jsize, const jint_)' [
-fpermissive]
     void SetIntArrayRegion(jintArray array, jsize start, jsize len,
          ^
jvm-packages/xgboost4j/src/native/xgboost4j.cpp: In function 'jint Java_ml_dmlc_
xgboost4j_java_XGBoostJNI_RabitGetRank(JNIEnv_, jclass, jintArray)':
jvm-packages/xgboost4j/src/native/xgboost4j.cpp:725:44: error: invalid conversio
n from 'int_' to 'const jint\* {aka const long int_}' [-fpermissive]
   jenv->SetIntArrayRegion(jout, 0, 1, &rank);
                                            ^
In file included from jvm-packages/xgboost4j/src/native/./xgboost4j.h:2:0,
                 from jvm-packages/xgboost4j/src/native/xgboost4j.cpp:18:
D:\InstalledPrograms\jdk1.7/include/jni.h:1779:10: error:   initializing argumen
t 4 of 'void JNIEnv_::SetIntArrayRegion(jintArray, jsize, jsize, const jint_)' [
-fpermissive]
     void SetIntArrayRegion(jintArray array, jsize start, jsize len,
          ^
jvm-packages/xgboost4j/src/native/xgboost4j.cpp: In function 'jint Java_ml_dmlc_
xgboost4j_java_XGBoostJNI_RabitGetWorldSize(JNIEnv_, jclass, jintArray)':
jvm-packages/xgboost4j/src/native/xgboost4j.cpp:737:43: error: invalid conversio
n from 'int_' to 'const jint\* {aka const long int_}' [-fpermissive]
   jenv->SetIntArrayRegion(jout, 0, 1, &out);
                                           ^
In file included from jvm-packages/xgboost4j/src/native/./xgboost4j.h:2:0,
                 from jvm-packages/xgboost4j/src/native/xgboost4j.cpp:18:
D:\InstalledPrograms\jdk1.7/include/jni.h:1779:10: error:   initializing argumen
t 4 of 'void JNIEnv_::SetIntArrayRegion(jintArray, jsize, jsize, const jint_)' [
-fpermissive]
     void SetIntArrayRegion(jintArray array, jsize start, jsize len,
          ^
jvm-packages/xgboost4j/src/native/xgboost4j.cpp: In function 'jint Java_ml_dmlc_
xgboost4j_java_XGBoostJNI_RabitVersionNumber(JNIEnv_, jclass, jintArray)':
jvm-packages/xgboost4j/src/native/xgboost4j.cpp:749:43: error: invalid conversio
n from 'int_' to 'const jint\* {aka const long int_}' [-fpermissive]
   jenv->SetIntArrayRegion(jout, 0, 1, &out);
                                           ^
In file included from jvm-packages/xgboost4j/src/native/./xgboost4j.h:2:0,
                 from jvm-packages/xgboost4j/src/native/xgboost4j.cpp:18:
D:\InstalledPrograms\jdk1.7/include/jni.h:1779:10: error:   initializing argumen
t 4 of 'void JNIEnv_::SetIntArrayRegion(jintArray, jsize, jsize, const jint_)' [
-fpermissive]
     void SetIntArrayRegion(jintArray array, jsize start, jsize len,
          ^
Makefile:124: recipe for target 'jvm-packages/lib/libxgboost4j.so' failed
mingw32-make: **\* [jvm-packages/lib/libxgboost4j.so] Error 1**

The environment is:

**$ g++ -v
Using built-in specs.
COLLECT_GCC=c:\MinGW\bin\g++.exe
COLLECT_LTO_WRAPPER=c:/MinGW/bin/../libexec/gcc/x86_64-w64-mingw32/4.8.2/lto-wra
pper.exe
Target: x86_64-w64-mingw32
Configured with: ../../../src/gcc-4.8.2/configure --host=x86_64-w64-mingw32 --bu
ild=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --prefix=/mingw64 --with-sysr
oot=/c/mingw482/x86_64-482-posix-seh-rt_v3-rev4/mingw64 --with-gxx-include-dir=/
mingw64/x86_64-w64-mingw32/include/c++ --enable-shared --enable-static --disable
-multilib --enable-languages=ada,c,c++,fortran,objc,obj-c++,lto --enable-libstdc
xx-time=yes --enable-threads=posix --enable-libgomp --enable-libatomic --enable-
lto --enable-graphite --enable-checking=release --enable-fully-dynamic-string --
enable-version-specific-runtime-libs --disable-isl-version-check --disable-cloog
-version-check --disable-libstdcxx-pch --disable-libstdcxx-debug --enable-bootst
rap --disable-rpath --disable-win32-registry --disable-nls --disable-werror --di
sable-symvers --with-gnu-as --with-gnu-ld --with-arch=nocona --with-tune=core2 -
-with-libiconv --with-system-zlib --with-gmp=/c/mingw482/prerequisites/x86_64-w6
4-mingw32-static --with-mpfr=/c/mingw482/prerequisites/x86_64-w64-mingw32-static
 --with-mpc=/c/mingw482/prerequisites/x86_64-w64-mingw32-static --with-isl=/c/mi
ngw482/prerequisites/x86_64-w64-mingw32-static --with-cloog=/c/mingw482/prerequi
sites/x86_64-w64-mingw32-static --enable-cloog-backend=isl --with-pkgversion='x8
6_64-posix-seh-rev4, Built by MinGW-W64 project' --with-bugurl=http://sourceforg
e.net/projects/mingw-w64 CFLAGS='-O2 -pipe -I/c/mingw482/x86_64-482-posix-seh-rt
_v3-rev4/mingw64/opt/include -I/c/mingw482/prerequisites/x86_64-zlib-static/incl
ude -I/c/mingw482/prerequisites/x86_64-w64-mingw32-static/include' CXXFLAGS='-O2
 -pipe -I/c/mingw482/x86_64-482-posix-seh-rt_v3-rev4/mingw64/opt/include -I/c/mi
ngw482/prerequisites/x86_64-zlib-static/include -I/c/mingw482/prerequisites/x86_
64-w64-mingw32-static/include' CPPFLAGS= LDFLAGS='-pipe -L/c/mingw482/x86_64-482
-posix-seh-rt_v3-rev4/mingw64/opt/lib -L/c/mingw482/prerequisites/x86_64-zlib-st
atic/lib -L/c/mingw482/prerequisites/x86_64-w64-mingw32-static/lib '
Thread model: posix
gcc version 4.8.2 (x86_64-posix-seh-rev4, Built by MinGW-W64 project)**

The Above is the problems in Windows and the following is the one in Linux suse 11 sp3

I type command "make" in the parent folder and got the following errors:

**make
g++ -fPIC -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/data/data.o src/data/data.cc >build/data/data.d
g++ -fPIC -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/data/data.cc -o build/data/data.o
In file included from src/data/./sparse_page_source.h:12:0,
                 from src/data/data.cc:16:
dmlc-core/include/dmlc/threadediter.h: In lambda function:
dmlc-core/include/dmlc/threadediter.h:299:27: internal compiler error: Segmentation fault
Please submit a full bug report,
with preprocessed source if appropriate.
See http://gcc.gnu.org/bugs.html for instructions.
make: **\* [build/data/data.o] Error 1**

Could anyone help me please!

**Comment by pommedeterresautee** [comment]
Bug related to an old version, closing.
