### ISSUE TITLE
[jvm-packages] the error of spark4j-spark

### ISSUE THREAD

**Issue by youngjt** [dmlc/xgboost#1169]
**We just tried the xgboost4j-spark version of the xgboost on our cluster, and encountered the following problems:**

_(1)First time,the program can not be executed, nor it displays no error message.(Detailed error information, see Annex 3)_
16/xx/xx. 20:31:08 INFO TaskSetManager: Finished task 23.0 in stage 2.0 (TID 129) in 2449 ms on localhost (12/40)
16/xx/xx. 20:31:08 INFO TaskSetManager: Finished task 21.0 in stage 2.0 (TID 128) in 2520 ms on localhost (13/40)
16/xx/xx. 20:31:08 INFO TaskSetManager: Finished task 16.0 in stage 2.0 (TID 126) in 2523 ms on localhost (14/40)

_(2)Second time,the error message is OutOfMemoryError.(Detailed error information, see Annex 2)_
16/xx/xx 11:11:22 ERROR Executor: Exception in task 39.0 in stage 2.0 (TID 159)
java.lang.OutOfMemoryError: GC overhead limit exceeded

_(3)Third time,the error message is InvocationTargetException.(Detailed error information,
 see Annex 3)_
16/xx/xx07:10:01 ERROR LiveListenerBus: Listener EventLoggingListener threw an exception
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)

**The size of the data set we used is: the number of samples is about 2700000, the feature dimension of each sample is 400.**

_Specific settings for the spark-submit:_
TRAIN_PATH=/tmp/xxxx/tmp_60
TEST_PATH=/tmp/xxxxx/tmp_8
OUTPUT_PATH=/tmp/xxxxxx
numRound=100
nWorks=20
JARPATH=/home/xxxxx/xgboost/jvm-packages/xgboost4j-example/target
hadoop fs -rm -r $OUTPUT_PATH
spark-submit \ 
    --class ml.dmlc.xgboost4j.scala.example.spark.DistTrainWithSpark
    --master yarn-client \
    --num-executors 20 \
    --driver-memory 4g \
    --executor-cores 2 \
    --executor-memory 20g \
    --queue xxxxx \
$JARPATH/xgboost4j-example-0.5-jar-with-dependencies.jar $numRound $nWorks $TRAIN_PATH $TEST_PATH  $OUTPUT_PATH

[Annex-1.txt.txt](https://github.com/dmlc/xgboost/files/246884/Annex-1.txt.txt)
[Annex-2.txt.txt](https://github.com/dmlc/xgboost/files/246883/Annex-2.txt.txt)
[Annex-3.txt](https://github.com/dmlc/xgboost/files/246898/Annex-3.txt)

**Comment by CodingCat** [comment]
I look at the third file, it seems that the program has executed successfully, but in the last step where the log entries are not able to be  written to the java space through pipe....

one of the possible guesses is the GC effect, the other one is your program cannot write to stdout with the sufficient permission? would you give the driver more memory?

for the second file, can you repeat OutOfMemoryError in a steady way?

BTW, what's your hardware setup and your configuration of $nWorks?

**Comment by youngjt** [comment]
(1)Firstly,the error message which xgboost4j-spark have displayed is not stable.
(2)How can i give a good value to the parameter of nWorks which used in xgboost4j-spark?
BTW,There are 72 nodes in our cluster, and each node has 2 CPU, 64G memory

**Comment by CodingCat** [comment]
nWorkers stands for the max parallelism of your training process 

If you have 20 executors (2 cores per each), you can at most set it to 40....

**Comment by CodingCat** [comment]
what's your current setup ?

**Comment by youngjt** [comment]
We have made a very low level of error, the code of xgboost4j-spark is set to local mode. Code as follows:
val sparkConf = new SparkConf()# **.setMaster("local[*]").**setAppName("XGBoost-spark-example")

**Comment by Ning-Caroline** [comment]
@youngjt  how can u maven the xgboost4j-spark successfully？I got the error :Failed to execute goal on project xgboost4j-spark: Could not resolve dependencies for project ml.dmlc:xgboost4j-spark:jar:0.5: Could not find artifact ml.dmlc:xgboost4j:jar:0.5 in central (https://repo.maven.apache.org/maven2) .
and I could not find the lib in the central.
Besides,I run the create_jni.sh but also failed

**Comment by CodingCat** [comment]
xgboost4j-spark is not available in maven for now...

would you post the error info about create_jni.sh?

**Comment by Ning-Caroline** [comment]
@CodingCat line 19 in create_jni.sh : " make jvm no_omp=${dis_omp}" . just error but no more log. 
So now ,how can i use the xgboost4j ?

**Comment by CodingCat** [comment]
where did you run this command? you can simply run `mvn package` to build the library without the necessary to run create_jni.sh....
