### ISSUE TITLE
index of output leaf  for each tree in boosting trees

### ISSUE THREAD

**Issue by raabdesselam** [dmlc/xgboost#117]
Hello,
am looking to find the index of the leaf output for each tree when i predict with tree booster classifier. because i want to use it to generate new features according to this paper : http://quinonero.net/Publications/predicting-clicks-facebook.pdf
Example: 
output for tree1: [1,0,0]
output for tree2 [0,0,1]
output for tree3 [1,0,0]

please, can any one help me ?

**Comment by brianchan1024** [comment]
can not go to https://github.com/tqchen/xgboost/issues/105
