### ISSUE TITLE
model format compatibility/porting issue

### ISSUE THREAD

**Issue by ntfshard** [dmlc/xgboost#1170]
Hello

I have some porting/compatibility issue. A model file from R/windows doesn't work with xgboost/linux utility;
BTW both files works fine on the 'native platform';

R/windows - 0.4-3
xgboost/linux - 4af55518f2307bbcc32e13a7a703de5b697a01ed

PS linux 64 bit; R on windows 32 bit (in task manager)

[samples.zip](https://github.com/dmlc/xgboost/files/247550/samples.zip)

--M.

**Comment by pommedeterresautee** [comment]
Bug related to an old version, closing.
