### ISSUE TITLE
Large data set xgb.cv memory usage

### ISSUE THREAD

**Issue by saurabhbikram** [dmlc/xgboost#1171]
Hi

I am trying to run `xgb.cv` (via R) on a dataset of approx 16gb in size on a machine with 100gb of RAM. However, I keep getting this error

`terminate called after throwing an instance of 'std::bad_alloc' what():  std::bad_alloc`

What is the rule of thumb for dataset to RAM required ? Is there anything I can do to reduce memory requirement ? I already have the data in xgb.DMatrix format.

Update: I reduced the dimensionality of the dataset to reduce the size to 11gb and it seems to be running fine..using almost all of the 100gb RAM.

Update 2: The memory issue lies in `xgb.cv` since when I use the `xgboost` function, the memory usage is around 15gb which makes sense.

**Comment by khotilov** [comment]
Yes, that seems to be an issues with CV which creates multiple copies of data when using the slice method to create folds' train and test sets.
https://github.com/dmlc/xgboost/blob/b92e2252b0100f352fe2b8c86ea58a59f0edf6ef/src/c_api/c_api.cc#L328
