### ISSUE TITLE
Compiling issues on Windows with Git Bash

### ISSUE THREAD

**Issue by mpettis** [dmlc/xgboost#1174]
I followed the directions here: https://xgboost.readthedocs.io/en/latest/build.html#building-on-windows , but failed to build.

When I got to this step (via the troubleshooting section), I got:

    NAMERICA2+H182821@MN10LT9T6RH72 MINGW64 /c/github-projects/xgboost (master)
    $ git submodule update && make clean_all && make -j4
    ...
    /usr/bin/sh: /usr/bin/make: No such file or directory
    /usr/bin/sh: line 0: cd: /cygdrive/c/github-projects/xgboost: No such file or directory
    make: *** [dmlc-core/libdmlc.a] Error 1
    make: *** Waiting for unfinished jobs....
    g++ -m64 -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -c src/tree/updater_sync.cc -o build/tree/updater_sync.o
    make: *** Waiting for unfinished jobs....

So, in the makefile, it looks like it is trying to take an explicit path to `make`, which seems to defeat the purpose of defining the `makd` alias earlier in the process (also at the first link).  Also, it is trying to go to '/cygdrive/c/...', which doesn't exist in `Git Bash`, but '/c/...' does.

Thoughts on troubleshooting this welcome.  Thanks in advance.

**Comment by mpettis** [comment]
One add -- I found out that I had issues with things like `make` being picked up in my path from the Rtools package, which had precedence over the `mingw` toolset in my path.  So I did change my environement variables to put `mingw` tools ahead of Rtools, but I still get errors.  I'm following instructions now at: https://www.ibm.com/developerworks/community/blogs/jfp/entry/Installing_XGBoost_For_Anaconda_on_Windows?lang=en

And getting errors when trying to run `make -j4` in the `dmlc-core` directory:

    $ make -j4
    g++ -c -O3 -Wall -msse2  -Wno-unknown-pragmas -Iinclude  -std=c++0x -fopenmp -fPIC -DDMLC_USE_HDFS=0 -DDMLC_USE_S3=0 -DDMLC_USE_AZURE=0 -o io.o src/io.cc
    g++ -c -O3 -Wall -msse2  -Wno-unknown-pragmas -Iinclude  -std=c++0x -fopenmp -fPIC -DDMLC_USE_HDFS=0 -DDMLC_USE_S3=0 -DDMLC_USE_AZURE=0 -o data.o src/data.cc
    g++ -c -O3 -Wall -msse2  -Wno-unknown-pragmas -Iinclude  -std=c++0x -fopenmp -fPIC -DDMLC_USE_HDFS=0 -DDMLC_USE_S3=0 -DDMLC_USE_AZURE=0 -o recordio.o src/recordio.cc
    g++ -c -O3 -Wall -msse2  -Wno-unknown-pragmas -Iinclude  -std=c++0x -fopenmp -fPIC -DDMLC_USE_HDFS=0 -DDMLC_USE_S3=0 -DDMLC_USE_AZURE=0 -o config.o src/config.cc
    src/io.cc:1:0: warning: -fPIC ignored for target (all code is position independent)
     // Copyright by Contributors
     ^
    src/data.cc:1:0: warning: -fPIC ignored for target (all code is position independent)
     // Copyright by Contributors
     ^
    src/recordio.cc:1:0: warning: -fPIC ignored for target (all code is position independent)
     // Copyright by Contributors
     ^
    src/config.cc:1:0: warning: -fPIC ignored for target (all code is position independent)
     /*!
     ^
    In file included from src/data/././text_parser.h:11:0,
                     from src/data/./libsvm_parser.h:13,
                     from src/data/disk_row_iter.h:19,
                     from src/data.cc:12:
    include/dmlc/omp.h:9:17: fatal error: omp.h: No such file or directory
     #include <omp.h>
                     ^
    compilation terminated.
    Makefile:75: recipe for target 'data.o' failed
    mingw32-make: *** [data.o] Error 1
    mingw32-make: *** Waiting for unfinished jobs....
    In file included from c:\mingw\lib\gcc\mingw32\4.9.3\include\c++\cmath:44:0,
                     from c:\mingw\lib\gcc\mingw32\4.9.3\include\c++\random:38,
                     from c:\mingw\lib\gcc\mingw32\4.9.3\include\c++\bits\stl_algo.h:66,
                     from c:\mingw\lib\gcc\mingw32\4.9.3\include\c++\algorithm:62,
                     from src/recordio.cc:6:
    c:\mingw\include\math.h: In function 'float hypotf(float, float)':
    c:\mingw\include\math.h:635:30: error: '_hypot' was not declared in this scope
     { return (float)(_hypot (x, y)); }
                                  ^
    In file included from c:\mingw\lib\gcc\mingw32\4.9.3\include\c++\cmath:44:0,
                     from c:\mingw\lib\gcc\mingw32\4.9.3\include\c++\random:38,
                     from c:\mingw\lib\gcc\mingw32\4.9.3\include\c++\bits\stl_algo.h:66,
                     from c:\mingw\lib\gcc\mingw32\4.9.3\include\c++\algorithm:62,
                     from src/io/./input_split_base.h:15,
                     from src/io/line_split.h:15,
                     from src/io.cc:8:
    c:\mingw\include\math.h: In function 'float hypotf(float, float)':
    c:\mingw\include\math.h:635:30: error: '_hypot' was not declared in this scope
     { return (float)(_hypot (x, y)); }
                                  ^
    Makefile:75: recipe for target 'recordio.o' failed
    mingw32-make: *** [recordio.o] Error 1
    In file included from src/io.cc:10:0:
    src/io/single_file_split.h: In constructor 'dmlc::io::SingleFileSplit::SingleFileSplit(const char*)':
    src/io/single_file_split.h:33:32: error: 'fopen64' was not declared in this scope
           fp_ = fopen64(fname, "rb");
                                    ^
    In file included from src/io/cached_input_split.h:16:0,
                     from src/io.cc:13:
    include/dmlc/threadediter.h: At global scope:
    include/dmlc/threadediter.h:210:8: error: 'thread' in namespace 'std' does not name a type
       std::thread *producer_thread_;
            ^
    include/dmlc/threadediter.h:216:8: error: 'mutex' in namespace 'std' does not name a type
       std::mutex mutex_;
            ^
    include/dmlc/threadediter.h:222:8: error: 'condition_variable' in namespace 'std' does not name a type
       std::condition_variable producer_cond_;
            ^
    include/dmlc/threadediter.h:224:8: error: 'condition_variable' in namespace 'std' does not name a type
       std::condition_variable consumer_cond_;
            ^
    include/dmlc/threadediter.h: In constructor 'dmlc::ThreadedIter<DType>::ThreadedIter(size_t)':
    include/dmlc/threadediter.h:82:9: error: class 'dmlc::ThreadedIter<DType>' does not have any field named 'producer_thread_'
             producer_thread_(NULL),
             ^
    include/dmlc/threadediter.h: In member function 'virtual void dmlc::ThreadedIter<DType>::BeforeFirst()':
    include/dmlc/threadediter.h:168:22: error: 'mutex' is not a member of 'std'
         std::unique_lock<std::mutex> lock(mutex_);
                          ^
    include/dmlc/threadediter.h:168:22: error: 'mutex' is not a member of 'std'
    include/dmlc/threadediter.h:168:32: error: template argument 1 is invalid
         std::unique_lock<std::mutex> lock(mutex_);
                                    ^
    include/dmlc/threadediter.h:168:38: error: invalid type in declaration before '(' token
         std::unique_lock<std::mutex> lock(mutex_);
                                          ^
    include/dmlc/threadediter.h:168:39: error: 'mutex_' was not declared in this scope
         std::unique_lock<std::mutex> lock(mutex_);
                                           ^
    include/dmlc/threadediter.h:178:7: error: 'producer_cond_' was not declared in this scope
           producer_cond_.notify_one();
           ^
    include/dmlc/threadediter.h:182:5: error: 'consumer_cond_' was not declared in this scope
         consumer_cond_.wait(lock, [this]() {
         ^
    include/dmlc/threadediter.h:187:10: error: request for member 'unlock' in 'lock', which is of non-class type 'int'
         lock.unlock();
              ^
    include/dmlc/threadediter.h:189:17: error: 'producer_cond_' was not declared in this scope
         if (notify) producer_cond_.notify_one();
                     ^
    include/dmlc/threadediter.h: In member function 'void dmlc::ThreadedIter<DType>::Destroy()':
    include/dmlc/threadediter.h:236:7: error: 'producer_thread_' was not declared in this scope
       if (producer_thread_ != NULL) {
           ^
    include/dmlc/threadediter.h:239:23: error: 'mutex' is not a member of 'std'
           std::lock_guard<std::mutex> lock(mutex_);
                           ^
    include/dmlc/threadediter.h:239:23: error: 'mutex' is not a member of 'std'
    include/dmlc/threadediter.h:239:33: error: template argument 1 is invalid
           std::lock_guard<std::mutex> lock(mutex_);
                                     ^
    include/dmlc/threadediter.h:239:39: error: invalid type in declaration before '(' token
           std::lock_guard<std::mutex> lock(mutex_);
                                           ^
    include/dmlc/threadediter.h:239:40: error: 'mutex_' was not declared in this scope
           std::lock_guard<std::mutex> lock(mutex_);
                                            ^
    include/dmlc/threadediter.h:243:9: error: 'producer_cond_' was not declared in this scope
             producer_cond_.notify_one();
             ^
    include/dmlc/threadediter.h: In lambda function:
    include/dmlc/threadediter.h:295:26: error: 'mutex' is not a member of 'std'
             std::unique_lock<std::mutex> lock(mutex_);
                              ^
    include/dmlc/threadediter.h:295:26: error: 'mutex' is not a member of 'std'
    include/dmlc/threadediter.h:295:36: error: template argument 1 is invalid
             std::unique_lock<std::mutex> lock(mutex_);
                                        ^
    include/dmlc/threadediter.h:295:42: error: invalid type in declaration before '(' token
             std::unique_lock<std::mutex> lock(mutex_);
                                              ^
    include/dmlc/threadediter.h:295:43: error: 'mutex_' was not declared in this scope
             std::unique_lock<std::mutex> lock(mutex_);
                                               ^
    include/dmlc/threadediter.h:297:9: error: 'producer_cond_' was not declared in this scope
             producer_cond_.wait(lock, [this]() {
             ^
    include/dmlc/threadediter.h:325:16: error: request for member 'unlock' in 'lock', which is of non-class type 'int'
               lock.unlock();
                    ^
    include/dmlc/threadediter.h:326:11: error: 'consumer_cond_' was not declared in this scope
               consumer_cond_.notify_all();
               ^
    include/dmlc/threadediter.h:333:11: error: 'consumer_cond_' was not declared in this scope
               consumer_cond_.notify_all();
               ^
    include/dmlc/threadediter.h:343:25: error: 'mutex' is not a member of 'std'
             std::lock_guard<std::mutex> lock(mutex_);
                             ^
    include/dmlc/threadediter.h:343:25: error: 'mutex' is not a member of 'std'
    include/dmlc/threadediter.h:343:35: error: template argument 1 is invalid
             std::lock_guard<std::mutex> lock(mutex_);
                                       ^
    include/dmlc/threadediter.h:343:41: error: invalid type in declaration before '(' token
             std::lock_guard<std::mutex> lock(mutex_);
                                             ^
    include/dmlc/threadediter.h:343:42: error: 'mutex_' was not declared in this scope
             std::lock_guard<std::mutex> lock(mutex_);
                                              ^
    include/dmlc/threadediter.h:352:19: error: 'consumer_cond_' was not declared in this scope
           if (notify) consumer_cond_.notify_all();
                       ^
    include/dmlc/threadediter.h: In member function 'void dmlc::ThreadedIter<DType>::Init(std::function<bool(DType**)>, std::function<void()>)':
    include/dmlc/threadediter.h:355:3: error: 'producer_thread_' was not declared in this scope
       producer_thread_ = new std::thread(producer_fun);
       ^
    include/dmlc/threadediter.h:355:26: error: expected type-specifier
       producer_thread_ = new std::thread(producer_fun);
                              ^
    include/dmlc/threadediter.h:355:26: error: expected ';'
    include/dmlc/threadediter.h: In member function 'bool dmlc::ThreadedIter<DType>::Next(DType**)':
    include/dmlc/threadediter.h:362:20: error: 'mutex' is not a member of 'std'
       std::unique_lock<std::mutex> lock(mutex_);
                        ^
    include/dmlc/threadediter.h:362:20: error: 'mutex' is not a member of 'std'
    include/dmlc/threadediter.h:362:30: error: template argument 1 is invalid
       std::unique_lock<std::mutex> lock(mutex_);
                                  ^
    include/dmlc/threadediter.h:362:36: error: invalid type in declaration before '(' token
       std::unique_lock<std::mutex> lock(mutex_);
                                        ^
    include/dmlc/threadediter.h:362:37: error: 'mutex_' was not declared in this scope
       std::unique_lock<std::mutex> lock(mutex_);
                                         ^
    include/dmlc/threadediter.h:366:3: error: 'consumer_cond_' was not declared in this scope
       consumer_cond_.wait(lock, [this]() {
       ^
    include/dmlc/threadediter.h:374:10: error: request for member 'unlock' in 'lock', which is of non-class type 'int'
         lock.unlock();
              ^
    include/dmlc/threadediter.h:375:17: error: 'producer_cond_' was not declared in this scope
         if (notify) producer_cond_.notify_one();
                     ^
    include/dmlc/threadediter.h: In member function 'void dmlc::ThreadedIter<DType>::Recycle(DType**)':
    include/dmlc/threadediter.h:387:21: error: 'mutex' is not a member of 'std'
         std::lock_guard<std::mutex> lock(mutex_);
                         ^
    include/dmlc/threadediter.h:387:21: error: 'mutex' is not a member of 'std'
    include/dmlc/threadediter.h:387:31: error: template argument 1 is invalid
         std::lock_guard<std::mutex> lock(mutex_);
                                   ^
    include/dmlc/threadediter.h:387:37: error: invalid type in declaration before '(' token
         std::lock_guard<std::mutex> lock(mutex_);
                                         ^
    include/dmlc/threadediter.h:387:38: error: 'mutex_' was not declared in this scope
         std::lock_guard<std::mutex> lock(mutex_);
                                          ^
    include/dmlc/threadediter.h:392:15: error: 'producer_cond_' was not declared in this scope
       if (notify) producer_cond_.notify_one();
                   ^
    include/dmlc/threadediter.h: In instantiation of 'void dmlc::ThreadedIter<DType>::Destroy() [with DType = dmlc::io::InputSplitBase::Chunk]':
    src/io/cached_input_split.h:58:26:   required from here
    include/dmlc/threadediter.h:239:35: warning: unused variable 'lock' [-Wunused-variable]
           std::lock_guard<std::mutex> lock(mutex_);
                                       ^
    include/dmlc/threadediter.h: In instantiation of 'void dmlc::ThreadedIter<DType>::Recycle(DType**) [with DType = dmlc::io::InputSplitBase::Chunk]':
    src/io/cached_input_split.h:68:43:   required from here
    include/dmlc/threadediter.h:387:33: warning: unused variable 'lock' [-Wunused-variable]
         std::lock_guard<std::mutex> lock(mutex_);
                                     ^
    include/dmlc/threadediter.h: In instantiation of 'dmlc::ThreadedIter<DType>::Init(std::function<bool(DType**)>, std::function<void()>)::<lambda()> [with DType = dmlc::io::InputSplitBase::Chunk]':
    include/dmlc/threadediter.h:290:36:   required from 'struct dmlc::ThreadedIter<DType>::Init(std::function<bool(DType**)>, std::function<void()>) [with DType = dmlc::io::InputSplitBase::Chunk]::<lambda()>'
    include/dmlc/threadediter.h:354:3:   required from 'void dmlc::ThreadedIter<DType>::Init(std::function<bool(DType**)>, std::function<void()>) [with DType = dmlc::io::InputSplitBase::Chunk]'
    src/io/cached_input_split.h:160:6:   required from here
    include/dmlc/threadediter.h:343:37: warning: unused variable 'lock' [-Wunused-variable]
             std::lock_guard<std::mutex> lock(mutex_);
                                         ^
    Makefile:75: recipe for target 'io.o' failed
    mingw32-make: *** [io.o] Error 1

**Comment by thirdwing** [comment]
If you want to use the R package, please install from the drat repo

```r
install.packages("drat", repos="https://cran.rstudio.com")
drat:::addRepo("dmlc")
install.packages("xgboost", repos="http://dmlc.ml/drat/", type = "source")
```

**Comment by mpettis** [comment]
Thanks for the response @thirdwing .  It's not that I want to use the R package -- I want to use the python one, but I also have R and Rtools installed, which was interfering with the compiling process.

**Comment by thirdwing** [comment]
First, please tell us which version of MinGW you are using.

Second, please remove R and Rtools from PATH variable and try again. If you still met errors, please show us the full log.

Thanks

**Comment by khotilov** [comment]
You should be able to build the library with Rtools's gcc - see my post at #1049

**Comment by gatapia** [comment]
This is still happening.  I am trying to build dmlc-core and get the following:
```
$ make
g++ -m64 -c -O3 -Wall -msse2  -Wno-unknown-pragmas -Iinclude  -std=c++0x -DDMLC_ENABLE_STD_THREAD=0 -fopenmp -fPIC -DDMLC_USE_HDFS=0 -DDMLC_USE_S3=0 -DDMLC_USE_AZURE=0 -o io.o src/io.cc
src/io.cc:1:0: warning: -fPIC ignored for target (all code is position independent)
 // Copyright by Contributors
 ^
In file included from C:/dev/libs/TDM-GCC-64/x86_64-w64-mingw32/include/locale.h:12:0,
                 from C:/dev/libs/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/5.1.0/include/c++/clocale:42,
                 from C:/dev/libs/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/5.1.0/include/c++/x86_64-w64-mingw32/bits/c++locale.h:41,
                 from C:/dev/libs/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/5.1.0/include/c++/bits/localefwd.h:40,
                 from C:/dev/libs/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/5.1.0/include/c++/string:43,
                 from include/dmlc/base.h:154,
                 from src/io.cc:3:
C:/dev/libs/TDM-GCC-64/x86_64-w64-mingw32/include/stdio.h:450:83: error: 'FILE* std::fopen(const char*, const char*)' should have been declared inside 'std'
   FILE *fopen64(const char * __restrict__ filename,const char * __restrict__  mode);
                                                                                   ^
C:/dev/libs/TDM-GCC-64/x86_64-w64-mingw32/include/stdio.h:450:83: error: 'FILE* std::fopen(const char*, const char*)' conflicts with a previous declaration
C:/dev/libs/TDM-GCC-64/x86_64-w64-mingw32/include/stdio.h:449:17: note: previous declaration 'FILE* fopen(const char*, const char*)'
   FILE *__cdecl fopen(const char * __restrict__ _Filename,const char * __restrict__ _Mode) __MINGW_ATTRIB_DEPRECATED_SEC_WARN;
                 ^
Makefile:75: recipe for target 'io.o' failed
make: *** [io.o] Error 1
```
I have tried using Mingw64, Mingw64+TDM-GCC, TDM-GCC (without Mingw64), etc, etc.

Any plans to fix the MSVC build? This used to work out of the box for me.

Note: I even tried creating a new win 7 box on AWS and installing each dependency (Mingw, etc, etc) individually to ensure there were no conflicts.  So instructions at the moment do not even work on a clean win install.

**Comment by tqchen** [comment]
we have a pending issue on cmake https://github.com/dmlc/xgboost/pull/893 which has yet to be fixed for windows. if someone is willing to take a stab to continue the effort that would be great
