### ISSUE TITLE
Failure to build xgboost in mac - 'mutex' file not found & 'type_traits' file not found errors.

### ISSUE THREAD

**Issue by vamtosh** [dmlc/xgboost#1178]
Hi, 
I tried to install xgboost package through pip and it failed.
So I followed the steps in the installation guide - build.md

I tried these steps:
git clone --recursive https://github.com/dmlc/xgboost
cd xgboost; cp make/minimum.mk ./config.mk; make -j4

When I run make -j4, it results in an error:
fatal error: 'mutex' file not found & 
fatal error: 'type_traits' file not found

Unable to find proper solution for this issue. Please help.
Thanks

I have the following versions on my Mac:
**_gcc-5 (Homebrew gcc 5.3.0) 5.3.0

Python 3.5.1 :: Anaconda 4.0.0 (x86_64)

Apple LLVM version 4.2 (clang-425.0.24) (based on LLVM 3.2svn)
Target: x86_64-apple-darwin15.3.0_**

**Here is the full error.**
 c++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -DDISABLE_OPENMP -MM -MT build/logging.o src/logging.cc >build/logging.d
c++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -DDISABLE_OPENMP -MM -MT build/c_api/c_api.o src/c_api/c_api.cc >build/c_api/c_api.d
c++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -DDISABLE_OPENMP -MM -MT build/learner.o src/learner.cc >build/learner.d
c++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -DDISABLE_OPENMP -MM -MT build/c_api/c_api_error.o src/c_api/c_api_error.cc >build/c_api/c_api_error.d
In file included from src/c_api/c_api.cc:3:
In file included from include/xgboost/data.h:11:
In file included from dmlc-core/include/dmlc/data.h:14:
In file included from dmlc-core/include/dmlc/./io.h:360:
In file included from dmlc-core/include/dmlc/./serializer.h:21:
dmlc-core/include/dmlc/./type_traits.h:11:10: fatal error: 'type_traits' file
      not found
# include <type_traits>

```
     ^
```

1 error generated.
make: **\* [build/c_api/c_api.o] Error 1
make: **\* Waiting for unfinished jobs....
In file included from src/c_api/c_api_error.cc:7:
src/c_api/../common/thread_local.h:12:10: fatal error: 'mutex' file not found
# include <mutex>

```
     ^
```

1 error generated.
make: **\* [build/c_api/c_api_error.o] Error 1
In file included from src/learner.cc:8:
In file included from include/xgboost/learner.h:11:
In file included from rabit/include/rabit/rabit.h:28:
In file included from rabit/include/rabit/./internal/engine.h:10:
In file included from rabit/include/rabit/./internal/../serializable.h:12:
In file included from rabit/include/rabit/../dmlc/io.h:360:
In file included from rabit/include/rabit/../dmlc/./serializer.h:21:
rabit/include/rabit/../dmlc/./type_traits.h:11:10: fatal error: 'type_traits'
      file not found
# include <type_traits>

```
     ^
```

1 error generated.
make: **\* [build/learner.o] Error 1
In file included from src/logging.cc:9:
In file included from src/./common/sync.h:11:
In file included from rabit/include/rabit/rabit.h:28:
In file included from rabit/include/rabit/./internal/engine.h:10:
In file included from rabit/include/rabit/./internal/../serializable.h:12:
In file included from rabit/include/rabit/../dmlc/io.h:360:
In file included from rabit/include/rabit/../dmlc/./serializer.h:21:
rabit/include/rabit/../dmlc/./type_traits.h:11:10: fatal error: 'type_traits'
      file not found
# include <type_traits>

```
     ^
```

1 error generated.
make: **\* [build/logging.o] Error 1

**Comment by ozkansafak** [comment]
I'm having the same problem. 

>>>./build.sh
fatal error: 'type_traits' file not found

>>> pip install xgbost 
Command "python setup.py egg_info" failed with error code 1

>>> make -j4
fatal error: 'mutex' file not found
fatal error: 'type_traits' file not found


Please help. 

Mac OSX Yosemite 10.10.5

>>> pip --version
pip 8.1.2 from //anaconda/lib/python2.7/site-packages (python 2.7)
>>>  brew --version
Homebrew 0.9.9 (git revision aae4; last commit 2016-05-13)
Homebrew/homebrew-core (git revision 1b15; last commit 2016-05-14)

**Comment by phunterlau** [comment]
@ozkansafak  and @vamtosh pip install show have no problem: it is just an old version of xgboost. You might need to install `gcc` firstly on mac using `brew`.

As to compiling the multi-thread version of xgboost from github, please install `clang-omp` from `brew`, and add/change these 2 lines in `config.mk`

```
export CC = clang-omp
export CXX = clang-omp++
```

**Comment by ozkansafak** [comment]
Didn't work. :(


clang-omp is installed with this.
`brew install clang-omp`
Then 
`git clone --recursive https://github.com/dmlc/xgboost`
`cd xgboost`
`cp make/minimum.mk ./config.mk`
`make -j4`

```
In file included from rabit/include/rabit/./internal/../serializable.hfatal error: :12:
In file included from 'rabit/include/rabit/../dmlc/io.ht:y360p:
eIn file included from _rabit/include/rabit/../dmlc/./serializer.ht:r21a:
its' firabit/include/rabit/../dmlc/./type_traits.hl:e11 :n10o:t  fofatal error: und'
type_traits' file not found
#include <mutex>#include <type_traits>

         ^         ^

#include <type_traits>
#include <type_traits>
         ^
         ^
1 error generated.
1 error generated.
1 error generated.
make: *** [build/c_api/c_api_error.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [build/logging.o] Error 1
make: *** [build/learner.o] Error 1
1 error generated.
make: *** [build/c_api/c_api.o] Error 1```


Bad times :(

**Comment by thirdwing** [comment]
You might run into a very tricky part on Mac. Please do the followings to help troubleshooting.

(1) make a `test.cpp` with the content below:

```cpp
#include <type_traits>

int main()
{
}
```
(2) try to compile it using `clang++` or `g++`

(3) if it can't compile, try `clang++ -stdlib=libc++ test.cpp`

Please let me know the results.

**Comment by ozkansafak** [comment]
:(

```
[ozkansafak@MAC]:xgboost$ cat test.cpp
#include <type_traits>

int main()
{
}

[ozkansafak@MAC]:xgboost$ clang++ test.cpp 
test.cpp:1:10: fatal error: 'type_traits' file not found
#include <type_traits>
         ^
1 error generated.
[ozkansafak@MAC]:xgboost$ g++ test.cpp 
couldn't understand kern.osversion `14.5.0'
test.cpp:1:23: error: type_traits: No such file or directory
[ozkansafak@MAC]:xgboost$ clang++ -stdlib=libc++ test.cpp
Undefined symbols for architecture x86_64:
  "start", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[ozkansafak@MAC]:xgboost$ ```

**Comment by thirdwing** [comment]
@ozkansafak I am afraid I don't know what's wrong in your toolchain. The only suggestion I can give you now is to reinstall the Xcode.

**Comment by ozkansafak** [comment]
You're probably right. Will do and let you know on this thread.
Thanks for your time.
