### ISSUE TITLE
Error when building with  MinGW

### ISSUE THREAD

**Issue by taochenshh** [dmlc/xgboost#1179]
I got following errors when I try to build xgboost with MinGW on Windows:
g++: error: dmlc-core/libdmlc.a: No such file or directory
g++: error: rabit/lib/librabit_empty.a: No such file or directory
Makefile:120: recipe for target 'lib/libxgboost.dll' failed
mingw32-make: **\* [lib/libxgboost.dll] Error 1

How to solve this problem?

**Comment by phunterlau** [comment]
Seems like the problems mentioned here https://dnc1994.com/2016/03/installing-xgboost-on-windows/ try with TDM-GCC

**Comment by thirdwing** [comment]
@CTTC Please show the full log.

**Comment by tqchen** [comment]
I feel somehow we might need a more clear instruction, on which git shell to be used, and which version of minGW as indicated in the blogpost. Or simply redirect people to use the official Rtool, and add these instructions to the official documents.

@thirdwing any thoughts?
