### ISSUE TITLE
what's the result is when i use task=pred in rank task

### ISSUE THREAD

**Issue by zhanliqing** [dmlc/xgboost#1183]
hi, when i use objective=rank:pairwise to do rank problem ,the feature label is either 1 or 0, when i do task=pred ,it seems that the result is not in [0-1] 
it like 
 -0.218254
1.11047
-0.994121
1.00362
0.13353
0.615873
-0.120918
1.45411
0.622311
0.508032
1.01142
0.638866
0.856179
0.449561

so what is the result score is ?

**Comment by playmobil** [comment]
we met the same situation before, our experience is keep these 2 parameter output_margin=False, ntree_limit=0  not change!

**Comment by tqchen** [comment]
since only relative orders in rank, we only outputs the margin scores. You can simply sort your query use these scores.
