### ISSUE TITLE
why python and yarn-model doesn't produce the same training result?

### ISSUE THREAD

**Issue by playmobil** [dmlc/xgboost#1184]
Using same parameter and dataset, the model trained from python is different from yarn cluster(dmlc-core/tracker/dmlc-submit --cluster=yarn), 
I means the difference is auc, logloss which relative to predicting power, the yarn-model model is superior than python's always... 
anybody come across the same issue?

[updated] When I ran the same python program in our server side, previously i ran it on my MacOS, the result almost the same as yarn cluster!!! seems this issue settled ^0^ , but i still wonder why MacOS can't produce the accurate result? ?

**Comment by pommedeterresautee** [comment]
Not the same seed?
