### ISSUE TITLE
Feature importance in Python API does not account for improvement in fit

### ISSUE THREAD

**Issue by ytsaig** [dmlc/xgboost#1185]
The current python implementation of feature importance ([get_fscore()](https://github.com/dmlc/xgboost/blob/bab69919d2f91b082c8c533c82587a9886cf4cf2/python-package/xgboost/core.py#L1020) in Booster) seems to calculate relative importance by simply counting the number of splits for each feature. However, the typical definition of relative importance weighs each split by the squared improvement to the fit, e.g., [Friedman (2001), eq. 44](http://luthuli.cs.uiuc.edu/~daf/courses/optimization/papers/2699986.pdf). Without accounting for this improvement, the importance measure is not going to be very useful when growing large trees. 

Is this by design?

**Comment by pommedeterresautee** [comment]
This has been changed in recent versions.
