### ISSUE TITLE
when i do rank task, model is strange

### ISSUE THREAD

**Issue by zhanliqing** [dmlc/xgboost#1187]
hi,when i do rank task ,the label is  in [0.0 ，2.0 ，4.0 ，7.0] 

the conf file is  
booster="gbtree"
objective="rank:pairwise"
eta = 0.1 
gamma = 1 
min_child_weight = 0.1
max_depth = 6
eval_metric = "ndcg@10-"
eval_metric = "map"
num_round = 10 
save_period = 0 
data = "train.data"
eval[test] = "test.data"
eval_train=1
test:data= "test.data"

i use  
           xgboost train.conf 
to train,
and use 
        xgboost train.conf  task=dump model_in=0010.model name_dump=model.t 
to get a readable model, when i see the model , i find a strange thing, the first tree first branch is 
             booster[0]:
             0:[f11<4.00001] yes=1,no=2,missing=2

however , in train data ,the 11th value is eigher 1.0 or 2.0 or null , so ,the right branch will never be in ,is there something wrong? wish your reply  ,

the train data and model are in https://github.com/zhanliqing/xgboost_test

**Comment by zhanliqing** [comment]
oh , may be i misunderstood ,is the missing=2 means the sample has no 11th feature go to 2 branch ?  and if the sample has 11th feature and value < 4.00001 go  1 branch ?

**Comment by pommedeterresautee** [comment]
1 and 2 are GOTO instructions.
