### ISSUE TITLE
fix examples in xgb.plot.importance

### ISSUE THREAD

**Issue by jangorecki** [dmlc/xgboost#1193]
There is an attempt to load `ggplot2` namespace in examples [xgb.plot.importance.Rd#L37](https://github.com/dmlc/xgboost/blob/master/R-package/man/xgb.plot.importance.Rd#L37), code below is the results from examples.
As `ggplot2` is suggested dependency, it should not be required to run examples according to [R-exts](https://cran.r-project.org/doc/manuals/R-exts.html#Suggested-packages). This can be conditionally escaped with `requireNamespace`.
It is possible there are other cases of that issue in other examples, this one was to first that fails.

```
* checking examples ... ERROR
Running examples in ‘xgboost-Ex.R’ failed
The error most likely occurred in:

> base::assign(".ptime", proc.time(), pos = "CheckExEnv")
> ### Name: xgb.plot.importance
> ### Title: Plot feature importance bar graph
> ### Aliases: xgb.plot.importance
> 
> ### ** Examples
> 
> data(agaricus.train, package='xgboost')
> 
> #Both dataset are list with two items, a sparse matrix and labels
> #(labels = outcome column which will be learned).
> #Each column of the sparse Matrix is a feature in one hot encoding format.
> train <- agaricus.train
> 
> bst <- xgboost(data = train$data, label = train$label, max.depth = 2,
+                eta = 1, nthread = 2, nround = 2,objective = "binary:logistic")
[0] train-error:0.046522
[1] train-error:0.022263
> 
> #train$data@Dimnames[[2]] represents the column names of the sparse matrix.
> importance_matrix <- xgb.importance(train$data@Dimnames[[2]], model = bst)
> xgb.plot.importance(importance_matrix)
Error: ggplot2 package is required for plotting the importance
Execution halted
```

**Comment by jangorecki** [comment]
The same applies to `Ckmeans.1d.dp` package in the same call:
```
> importance_matrix <- xgb.importance(train$data@Dimnames[[2]], model = bst)
> xgb.plot.importance(importance_matrix)
Error: Ckmeans.1d.dp package is required for plotting the importance
Execution halted
```

**Comment by khotilov** [comment]
Do I understand it right that the same applies to tests as well?

**Comment by jangorecki** [comment]
Precisely speaking: no.
From `tools/R/check.R`:

> The suggested packages are required for a complete check.
 Checking can be attempted without them by setting the environment
variable _R_CHECK_FORCE_SUGGESTS_ to a false value.

The good practice is to escape tests with `requireNamespace` so they will only run when suggested dependency is present. So also the `_R_CHECK_FORCE_SUGGESTS_` can be used, otherwise this env var won't be useful. I can recommend to escape packages that you consider to be optional for passing the tests, and leave all others. Related discussion was recently raise by me on r-devel mailing list, it discuss the consequences of current state: https://stat.ethz.ch/pipermail/r-devel/2016-April/072526.html

**Comment by jangorecki** [comment]
another issue related to dependencies... `rmarkdown` pkg should be in suggested deps as it is required to build.
```
* creating vignettes ... ERROR
Warning in engine$weave(file, quiet = quiet, encoding = enc) :
  The vignette engine knitr::rmarkdown is not available, because the rmarkdown package is not installed. Please install it.
Warning in readLines(con) :
  incomplete final line found on 'discoverYourData.Rmd'
Error: processing vignette 'discoverYourData.Rmd' failed with diagnostics:
It seems you should call rmarkdown::render() instead of knitr::knit2html() because discoverYourData.Rmd appears to be an R Markdown v2 document.
Execution halted
```
