### ISSUE TITLE
when gcc version is more than 5, it need upload libgomp

### ISSUE THREAD

**Issue by moveforever** [dmlc/xgboost#1194]
As xgboost which is compiled by gcc 5.x need GOMP_4.0,  you need upload libgomp into yarn, when xgboost runs on yarn.

**Comment by thirdwing** [comment]
This is not a problem in xgboost. This is about GCC.

GOMP is the implementation of OpenMP for GCC and the version number is for OpenMP standard.

The latest version is 4.5.
