### ISSUE TITLE
xgboost installation in R

### ISSUE THREAD

**Issue by bhattchintan07** [dmlc/xgboost#1195]
I'm running follwing code on cloudera ready made vm image of hadoop with centos:

[cloudera@quickstart ~]$ cd xgboost
[cloudera@quickstart xgboost]$ make

and getting following error:

g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/learner.o src/learner.cc >build/learner.d
g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/learner.cc -o build/learner.o
In file included from dmlc-core/include/dmlc/logging.h:15,
                 from include/xgboost/logging.h:11,
                 from src/learner.cc:7:
dmlc-core/include/dmlc/./base.h:66: note: #pragma message: Will need g++-4.6 or higher to compile allthe features in dmlc-core, compile without c++0x, some features may be disabled
In file included from include/xgboost/./gbm.h:17,
                 from include/xgboost/learner.h:16,
                 from src/learner.cc:8:
include/xgboost/././data.h: In constructor ‘xgboost::DMatrix::DMatrix()’:
include/xgboost/././data.h:234: error: ‘nullptr’ was not declared in this scope
In file included from src/learner.cc:17:
src/./common/io.h: At global scope:
src/./common/io.h:30: error: expected ‘;’ before ‘override’
src/learner.cc:462: error: expected ‘;’ before end of line
src/learner.cc:462: error: expected ‘}’ before end of line
In file included from src/learner.cc:17:
src/./common/io.h: In constructor ‘xgboost::common::PeekableInStream::PeekableInStream(dmlc::Stream*)’:
src/./common/io.h:28: error: class ‘xgboost::common::PeekableInStream’ does not have any field named ‘strm_’
src/./common/io.h:28: error: class ‘xgboost::common::PeekableInStream’ does not have any field named ‘buffer_ptr_’
src/learner.cc: At global scope:
src/learner.cc:462: error: expected unqualified-id before end of line
src/learner.cc:462: error: expected ‘}’ before end of line
src/learner.cc:462: error: expected ‘}’ before end of line
src/learner.cc:462: error: expected declaration before end of line
make: *** [build/learner.o] Error 1

please provide me solution for the same.

**Comment by moveforever** [comment]
gcc version don't support c++0x, and you need g++4.6 or higher to compile.

**Comment by bhattchintan07** [comment]
@moveforever can u elaborate me in detail regarding what to do next?

**Comment by moveforever** [comment]
you can follow these steps:
1 input command: gcc --version
2 if your gcc version is less than gcc 4.6, you can install a new gcc whose version is higher than gcc4.6
3 when you finish steps above and install gcc sucessfully, you can remake.
That's all.

**Comment by bhattchintan07** [comment]
ok Thank you
