### ISSUE TITLE
why ApplicationMaster's UserGroupInformation.getCurrentUser().getShortUserName(); is different from Client's userName in xgboost-yarn

### ISSUE THREAD

**Issue by moveforever** [dmlc/xgboost#1196]
I ran xgboost on yarn. When ApplicationMaster's userName is different from Client's userName, it can't access to write hdfs. The wrong logs is as followed:

```
[18:19:40] src/io/hdfs_filesys.cc:183: Check failed: allow_null  HDFSFileSystem: fail to open 

664 main : command provided 1
665 main : user is mapred
666 main : requested yarn user is unbuntu

org.apache.hadoop.security.AccessControlException: Permission denied: user=mapred, access=WRITE, inode="/user/xxx/xgboost":ubuntu:drwxr-xr-x
```

**Comment by moveforever** [comment]
My solution is to chmod 777 the hdfs directory. It's stupid way to solve the problem.

**Comment by tqchen** [comment]
interesting. This have something to do with dmlc-core's access mode to libhdfs. I guess it is possible to change the behavior with environment variable. Please let us know if you have idea on a possible fix

**Comment by moveforever** [comment]
Now I have no idea, but when I fix it, I'll update at once.
