### ISSUE TITLE
Add OOB permutation importance for xgbTree

### ISSUE THREAD

**Issue by yanyachen** [dmlc/xgboost#1197]
It would be great if OOB permutation based feature importance is avaliable in xgboost.

The implementation of this method I have seen is in the R gbm package. But for now, the gbm::permutation.test.gbm can only compute importance using entire training dataset (not OOB).
I guess its result should not be that different from the current information gain based feature importance in xgboost.

Also, I guess the feature importance result may be highly related to the subsample parameter, I'm not sure if this have to be done in a bootstrap way. If so, then this may be related to #374 

I hope the team can add this feature, It will be a great tool for feature selection.

**Comment by khotilov** [comment]
The OOB feature importance option would only make sense for the random forest setting with num_parallel_tree, but I doubt it would make much sense for boosting. See also #1070. Overall, it seems like the xgboost random forest might need some specialized set of functionality to be fully useful.

What's more necessary for boosting, I think, is an ability to perform feature importance evaluation in a dataset separate from training. It could be done either by updating split gains for new data or it could also be a permutation-based approach. I had some brute force attempts in R for the latter, but a significantly faster implementation should in principle be possible for repeated prediction in data with single permuted (or some other way modified) columns. I'm still thinking over good ways to do it.

**Comment by yanyachen** [comment]
That's truly keen insight of RF and boosting. I agree with you. I mentioned because I saw this OOB permutation feature importance in the R gbm document. I thought I might miss some papers.

For the "feature importance on validation dataset" idea, I think it's valuable for finding features that has negative impact for performance. I think both of them can be done in R, though it will be slow especially the later one. A C++ level implementation would be great.
