### ISSUE TITLE
xgboost installation in R on cloudera vm image

### ISSUE THREAD

**Issue by bhattchintan07** [dmlc/xgboost#1201]
I'm running following commands:
[cloudera@quickstart ~]$ cd xgboost
[cloudera@quickstart xgboost]$ git submodule init
[cloudera@quickstart xgboost]$ git submodule update
[cloudera@quickstart xgboost]$ alias make='mingw32-make'
[cloudera@quickstart xgboost]$ cd dmlc-core
[cloudera@quickstart dmlc-core]$ make -j4

I'm getting following error:
bash: mingw32-make: command not found

please suggest me help for the same.

**Comment by thirdwing** [comment]
Are you on Windows?

**Comment by khotilov** [comment]
MinGW confusion aside, all you need to do to compile and install xgboost R package is to start R (after git submodule update) and 
```sh
setwd('wherever_you_have_cloned_to/R-package')
install.packages('.', repos=NULL, type="source", Ncpus=4)
```
If you are in Linux and are seeing some errors about missing symbols, the easiest fix would be to modify R-package/src/Makevars and change ENABLE_STD_THREAD=0 and repeat the above.
Also, depending on what Linux version you are running, your system default gcc might be too old, and you would need to install a newer gcc that supports C++11.

**Comment by bhattchintan07** [comment]
@thirdwing I'm running it on cent os.

**Comment by thirdwing** [comment]
But `alias make='mingw32-make'` is for Windows. You need to follow the Linux instruction.
