### ISSUE TITLE
Division by zero when calculating AUC

### ISSUE THREAD

**Issue by skirpichenko** [dmlc/xgboost#1206]
Hello,

The following code results in app crash:

import numpy as np
import xgboost as xgb
y = np.random.randint(0,2,size=(100,1))
y[50:] = 0
dmat = xgb.DMatrix(np.random.rand(100,2), label=y)
dtrain = dmat.slice(np.arange(50))
dtest = dmat.slice(np.arange(50, 100))
xgb.train({'objective':'binary:logistic','eval_metric':'auc'}, dtrain, 100, [(dtrain,'train'),(dtest,'test')])

The reason is the division by zero at the line 134 of src/metric/rank_metric.cc

Thanks,
Sergey

**Comment by pommedeterresautee** [comment]
Bug related to an old version, closing.
