### ISSUE TITLE
Question regarding agaricus.txt datasets in xgboost/demo/data/

### ISSUE THREAD

**Issue by howardx** [dmlc/xgboost#1207]
Hi All:

I'm trying to learn how to user this package with python by following examples in xgboost/demo/. I see that there is a series of great tutorials - thanks a lot!

I'm also trying to understand a little bit about the datasets that are being used - are the agaricus datasets taken from the UCI machine learning data repo? I looked at UCI's agaricus datasets and they look different from what you are using here. Is there a place where we can look at the column/feature names for agaricus train/test data?

Thanks in advance,
Howard

**Comment by howardx** [comment]
Hi All:

I just looked at the featmap.txt - and it seems there are 125 features, but in the train/test datasets there are not that many columns - how do we map the features to columns in dataset?

Also the values in most columns are in the format of ratios (a : b) - how do we interpret them?

Just want to see if I can further understand the data a little bit and then try to play with it with pandas/numpy and other packages like sci-kit learn, and maybe compare with xgboost.

Thanks again,
Howard

**Comment by tqchen** [comment]
the data is preprocessed from the UCI data by https://github.com/dmlc/xgboost/blob/master/demo/binary_classification/runexp.sh
