### ISSUE TITLE
XGBoost for regression - deviance objective instead of RMSE?

### ISSUE THREAD

**Issue by AdmiralWen** [dmlc/xgboost#1209]
Hello,

When we set XGBoost to perform linear regression (reg:linear), I understand that the default objective is to minimize the RMSE. Is this the only built-in option for performing regression? In other words, if we wish to directly minimize deviance (like we would in a GLM), is there a built-in option for this or would we have to write a custom objective function similar to what's being done [here](https://github.com/dmlc/xgboost/blob/master/R-package/demo/custom_objective.R)?

Thanks in advance.

**Comment by pommedeterresautee** [comment]
Bug related to an old version, closing.
