### ISSUE TITLE
XGBClassifier.predict_proba outputs incorrect array dimension!

### ISSUE THREAD

**Issue by yinniyu** [dmlc/xgboost#1215]
Hi, I'm using the following code to fit the xgb classifier:
clf = XGBClassifier(objective='multi:softprob', n_estimators=300, subsample=0.8, gamma=1.3)
clf.fit(training_d[features], training_d['outcome'], early_stopping_rounds=10, eval_set=[(training_d[features], training_d['outcome']),(validation_d[features], validation_d['outcome'])],
        eval_metric='mlogloss')
but when I use the predict_proba function;
predict1=np.array(clf.predict_proba(validation_d[features]))
it spits out the wrong dimension, the validation_d[features] is (6238, 37), and the prediction should be (6238,5), but predict1 gives me (5,12476). I can't figure out where the 12476 is coming from. 

Does anyone have similar issue? Thanks!

--Jenny

**Comment by KhaoticMind** [comment]
12476 = 6238 * 2

I'm getting this same behavior when using XGBClassifier from python. using the xgb native interface (objective = 'multi:softprob') and booster.predict I get correct results.

I'm running on commit 9c26566eb09733423f821f139938ff4105c3775d.

I can try to update to latest commit and see if the problem persists.

**Comment by KhaoticMind** [comment]
Ok! Found the issue!

The problem is here:

```
 if self.objective == "multi:softprob":
return class_probs
else:
classone_probs = class_probs
classzero_probs = 1.0 - classone_probs
return np.vstack((classzero_probs, classone_probs)).transpose()
```
self.object is not being updated on the fit method (where it detects the multi:softprob):

```
if self.n_classes_ > 2:
# Switch to using a multiclass objective in the underlying XGB instance
xgb_options["objective"] = "multi:softprob"
xgb_options['num_class'] = self.n_classes_
```

The simple fix should be update self.objective inside this if.
I will inplement it and do a PR latter/tomorrow.

**Comment by yinniyu** [comment]
Thank you!
