### ISSUE TITLE
Changing the DMatrix based on some column

### ISSUE THREAD

**Issue by rislam** [dmlc/xgboost#1217]
Is there any way so that we can change the DMatrix content after loading them using xgboost?

**Comment by tqchen** [comment]
no, dmatrix is made minimum for speedup the training, but not for data manipulation. Try to use other data processing tools like dataframe, numpy, before converting the final results to dmatrix

**Comment by khotilov** [comment]
@tqchen: are there any current design restrictions that could prevent implementing the functionality to change a single feature in a DMatrix, in a manner that would be faster than recreating the whole thing (at least in a non-distributed case)?

There are quite a few potential applications for which being able to quickly change the values of a single feature would be very beneficial, e.g., computing partial dependencies, or various permutation-based approaches to feature importance.

**Comment by tqchen** [comment]
@khotilov It is possible, with a bit deeper integration.

- It is hard with current DMatrix memory layout.
- It is possible by subclassing the https://github.com/dmlc/xgboost/blob/master/include/xgboost/data.h#L178 and change the certain column on the fly. 
- We can even directly expose say dataframe as a datasource, which re-uses the memory layout in dataframe and allow manipulations

**Comment by jahin** [comment]
@tqchen Thanks for the hints. Which one is the both convenient and fast to modify? Any instructions on the modification are highly appreciated.
