### ISSUE TITLE
 column of sparse matrix changes after calling of xgboost.DMatraix 

### ISSUE THREAD

**Issue by wxfighting** [dmlc/xgboost#1223]
I stored my training and test datasets in sci.sparse.matrix variables (X,y) and (X_,y_) respectively. When I print the shape of X and X_ in Python, it's OK that they both have 74094 columns.

But after I call:
train_data = xgboost.DMatrix(X, label=y, missing=0.0)
test_data = xgboost.DMatrix(X_, label=y_, missing=0.0)

train_data.num_col() is still 74094, but test_data.num_col() equals to 73998. It will raise an error if I predict on test_data with the model trained on train_data. 

Could you help fix this problem?

**Comment by khotilov** [comment]
I guess you were using CSR fomat - try CSC instead.

The problem with CSR is that when you have completely sparse columns at the end, you cannot figure out that they exist by just looking at CSR's indices and pointers. And XGDMatrixCreateFromCSR tries to guess the number of columns using just this information:
https://github.com/dmlc/xgboost/blob/9ef86072f45660f8d10c0b8cf349bbfbb69c4bdf/src/c_api/c_api.cc#L245
The CSC format is similarly vulnerable when there are completely sparse rows (see the example below).

@tqchen : would it make sense to make `XGDMatrixCreateFromCSR` and `XGDMatrixCreateFromCSC` more robust by adding the `num_col` and `num_row` parameters respectively to them?

```python
import numpy as np
import scipy.sparse
import xgboost as xgb
from scipy.sparse import rand

### CSR wide with empty columns at the end - problem

x = rand(100, 100000, density=0.002, format='csr', random_state=1)
x.data[:] = 1
x.indices.max() # 99993
x.shape
x.__dict__
# last 6 cols are empty
x.sum(axis=0)[0,-20:]

dm = xgb.DMatrix(x)
dm.num_row()
dm.num_col() # 99994


### CSR narrow - OK

x = rand(100000, 100, density=0.002, format='csr', random_state=1)
x.data[:] = 1
x.indices.max()
x.shape

dm = xgb.DMatrix(x)
dm.num_row()
dm.num_col()


### CSS wide - OK

x = rand(100, 100000, density=0.002, format='csc', random_state=1)
x.data[:] = 1
x.indices.max()
x.shape

dm = xgb.DMatrix(x)
dm.num_row()
dm.num_col()


### CSC narrow with empty rows at the end - problem

x = rand(100000, 100, density=0.002, format='csc', random_state=10)
x.data[:] = 1
x.indices.max() # 99995
x.shape
x.__dict__
# last 4 rows are empty
x.sum(axis=1)[-20:, 0]

dm = xgb.DMatrix(x)
dm.num_row() # 99996
dm.num_col()
```

**Comment by tqchen** [comment]
https://github.com/dmlc/xgboost/issues/1583
