### ISSUE TITLE
R package error in xgb.plot.tree

### ISSUE THREAD

**Issue by jeffwong-nflx** [dmlc/xgboost#1234]
I am attempting to run the example for xgb.plot.tree, which opens up an html page showing some text - ultimately ending with this error on the html page: 

Cannot read property '0' of undefined

`
data(agaricus.train, package='xgboost')
# Both dataset are list with two items, a sparse matrix and labels
# (labels = outcome column which will be learned).
# Each column of the sparse Matrix is a feature in one hot encoding format.

train <- agaricus.train

bst <- xgboost(data = train$data, label = train$label, max.depth = 2,
               eta = 1, nthread = 2, nround = 2,objective = "binary:logistic")
# agaricus.test$data@Dimnames[[2]] represents the column names of the sparse matrix.

xgb.plot.tree(agaricus.train$data@Dimnames[[2]], model = bst)
`

graph LR;0-0(odor=none)-->|>= -1.00136e-05|0-2>spore-print-color=green];0-0(odor=none
Cover: 1628.25
Gain: 4000.53)-->|< -1.00136e-05|0-1>stalk-root=club];0-1(stalk-root=club)-->|>= -1.00136e-05|0-4>Leaf];0-1(stalk-root=club
Cover: 924.5
Gain: 1158.21)-->|< -1.00136e-05|0-3>Leaf];0-2(spore-print-color=green)-->|>= -1.00136e-05|0-6>Leaf];0-2(spore-print-color=green
Cover: 703.75
Gain: 198.174)-->|< -1.00136e-05|0-5>Leaf];1-0(stalk-root=rooted)-->|>= -1.00136e-05|1-2>Leaf];1-0(stalk-root=rooted
Cover: 788.852
Gain: 832.545)-->|< -1.00136e-05|1-1>odor=none];1-1(odor=none)-->|>= -1.00136e-05|1-4>Leaf];1-1(odor=none
Cover: 768.39
Gain: 569.725)-->|< -1.00136e-05|1-3>Leaf];classDef greenNode fill:#A2EB86, stroke:#04C4AB, stroke-width:2px;classDef redNode fill:#FFA070, stroke:#FF5E5E, stroke-width:2px;class 0-1,0-3,0-5,1-1,1-3 greenNode;class 0-2,0-4,0-6,1-2,1-4 redNode
parse error with graph LR;0-0(odor=none)-->|>= -1.00136e-05|0-2>spore-print-color=green];0-0(odor=none
Cover: 1628.25
Gain: 4000.53)-->|< -1.00136e-05|0-1>stalk-root=club];0-1(stalk-root=club)-->|>= -1.00136e-05|0-4>Leaf];0-1(stalk-root=club
Cover: 924.5
Gain: 1158.21)-->|< -1.00136e-05|0-3>Leaf];0-2(spore-print-color=green)-->|>= -1.00136e-05|0-6>Leaf];0-2(spore-print-color=green
Cover: 703.75
Gain: 198.174)-->|< -1.00136e-05|0-5>Leaf];1-0(stalk-root=rooted)-->|>= -1.00136e-05|1-2>Leaf];1-0(stalk-root=rooted
Cover: 788.852
Gain: 832.545)-->|< -1.00136e-05|1-1>odor=none];1-1(odor=none)-->|>= -1.00136e-05|1-4>Leaf];1-1(odor=none
Cover: 768.39
Gain: 569.725)-->|< -1.00136e-05|1-3>Leaf];classDef greenNode fill:#A2EB86, stroke:#04C4AB, stroke-width:2px;classDef redNode fill:#FFA070, stroke:#FF5E5E, stroke-width:2px;class 0-1,0-3,0-5,1-1,1-3 greenNode;class 0-2,0-4,0-6,1-2,1-4 redNode
Cannot read property '0' of undefined

**Comment by pommedeterresautee** [comment]
Are you using the last version from Github?

**Comment by heroxbd** [comment]
This is a duplication of issue 970.  Please make a new release in CRAN.  Thanks.
