### ISSUE TITLE
Error raised when predicting or dumping count:poisson model

### ISSUE THREAD

**Issue by yangs16** [dmlc/xgboost#1236]
terminate called after throwing an instance of 'dmlc::ParamError'
  what():  Required parameter max_delta_step of float is not presented
Aborted

---

An easy fix is to add a config item after the line 265 in src/learner.cc, e.g.
cfg_["max_delta_step"] = common::ToString(0.7);

Thanks.

**Comment by khotilov** [comment]
https://github.com/dmlc/xgboost/blob/49bbd72d08b3913d80e52b44f2ae00ef33543377/src/learner.cc#L168 should have taken care of that.
Could you please show how to reproduce your error?

**Comment by yangs16** [comment]
Yes. But the Configure() is not called in  CLIDump2Text() and CLIPredict(). I guess the fix should be add a line after https://github.com/dmlc/xgboost/blob/49bbd72d08b3913d80e52b44f2ae00ef33543377/src/cli_main.cc#L271 and https://github.com/dmlc/xgboost/blob/49bbd72d08b3913d80e52b44f2ae00ef33543377/src/cli_main.cc#L297:

learner->Configure(param.cfg);

Hope this will help.

**Comment by yangs16** [comment]
Just noticed that the problem with the prediction has been fixed in commit <a href=https://github.com/dmlc/xgboost/commit/1dde863c98a40fbda4188f89892f0c8acce3c45c>1dde863</a>. I send another pull request to fix the problem with the model dump:
https://github.com/dmlc/xgboost/pull/1253
