### ISSUE TITLE
[jvm package] Early Stop in JAVA

### ISSUE THREAD

**Issue by dnkamila** [dmlc/xgboost#1237]
Hi, I wonder if early stop is implemented in java package and how to use it? Because I just found it in R, xgb.train(early.stop.round ...)

Thanks in advance

**Comment by dnkamila** [comment]
is there any update of it?

**Comment by nkg114mc** [comment]
Same question for me. Have the functionalities of xgboost for Java and Scala been completed as Python?

**Comment by CodingCat** [comment]
not yet
