### ISSUE TITLE
build in Redhat or centos

### ISSUE THREAD

**Issue by spacerunner9** [dmlc/xgboost#1240]
I am having compile issues when building in centos/redhat. 

Did anyone successfully build in centos/redhat and if yes, can you please share the versions and configuration.

**Comment by thirdwing** [comment]
Please provide more info, including the building errors.

I am quite sure it can compile on recent centos.

**Comment by khotilov** [comment]
@spacerunner9 : when reporting an issue, it's usually in reporter's court to share their versions, configuration, and the error details.

Anyway, if you are running version 6.x of those OS's, you would need either devtoolset-3 or 4 installed, since the system gcc is too old.
