### ISSUE TITLE
what's the point label in each iter?

### ISSUE THREAD

**Issue by leoli2012** [dmlc/xgboost#1242]
hi, i have read the xgboost paper, i know how to calculate the leaf score and  obj, but i don't know how to update the label in each iter when build new tree, is the same label used in all trees?

**Comment by khotilov** [comment]
Please provide more specific details. You question is not clear.

**Comment by tqchen** [comment]
There is no need to update the labels. Only the existing prediction is updated. gradient statistics is updated based on existing prediction and label.
