### ISSUE TITLE
[xgboost on yarn] ./xgboost: error while loading shared libraries: libhdfs.so.0.0.0: cannot open shared object file: No such file or directory #854

### ISSUE THREAD

**Issue by srdhuli** [dmlc/xgboost#1247]
I am getting same error that was posted in #854. [xgboost on yarn] ./xgboost: error while loading shared libraries: libhdfs.so.0.0.0: cannot open shared object file: No such file or directory.

Can some one provide me the solution for this error.

**Comment by coder-james** [comment]
set Enviroment Variable $LD_LIBRARY_PATH with libhdfs PATH

**Comment by antant-shenzhen-2013** [comment]
+1
