### ISSUE TITLE
where is the windows file?

### ISSUE THREAD

**Issue by tangzhao132** [dmlc/xgboost#1259]
I couldn't find the file '<repo_root>\windows\'  anyone could help me?

**Comment by DengYiping** [comment]
It is still under active development, just wait and see.

**Comment by vickimylove** [comment]
I can't ,either. Is it still active??I  can not see it. @DengYiping @tangzhao142

**Comment by vickimylove** [comment]
I can't ,either. Is it still active??I can not see it. @DengYiping @tangzhao132
