### ISSUE TITLE
make fails with error 'fopen64' was not declared in this scope

### ISSUE THREAD

**Issue by spinwards** [dmlc/xgboost#1260]
I am currently receiving the error reported in #625 on windows 10 using the MinGW-w64 environment recommended in that issue. In addition I tried building in msys2 (after running pacman -S mingw64/mingw-w64-x86_64-make) and in the current git bash distribution without success. 

It is worth noting the the latest distribution of git bash does not ship with make, so the instructions here: https://xgboost.readthedocs.io/en/latest/build.html#build-the-shared-library so not work.

**Comment by superbobry** [comment]
I can confirm that at least some version of mingw64 do not define fopen64, here's a [build log](https://ci.appveyor.com/project/superbobry/xgboost-jars/build/1.0.82) from Appveyor (scroll to the bottom).
