### ISSUE TITLE
[jvm-packages]handling missing values in Java/Spark

### ISSUE THREAD

**Issue by spacerunner9** [dmlc/xgboost#1261]
I am in process of scoring from a saved model. How can i pass missing values to spark/java packages while running the predict method. There is no option to pass parameter when predicting the model

Here is the code I am using

 ```
val featureVectors = sourceDF.map(row => {
    Vectors.dense(row.toSeq.toArray.map({
    case s: String => (if(s.equals("NA")) { 0 } else {s.toDouble}) // i need to do this since NA is not a double and would like to set as big int and while scoring I can assign the paramter missing=bigint
    case l: Long => l.toDouble
    case _ => 0.0
  }))
})
val loadedXGBooostModel = XGBoost.loadModelFromHadoopFile(modelPath)(sc)
val predicts = loadedXGBooostModel.predict(featureVectors)
```

**Comment by CodingCat** [comment]
@tqchen  is the similar functionality support in python/R binding?

**Comment by tqchen** [comment]
Yes, it is supported in creation of DMatrix

**Comment by tqchen** [comment]
see https://github.com/dmlc/xgboost/blob/master/python-package/xgboost/core.py#L236

**Comment by spacerunner9** [comment]
In XGBoostModel.scala if I set missing value as shown below will it work or this is something thats missing in JVMpackages.

```
/**
   * Predict result with the given testset (represented as RDD)
   */
  def predict2(testSet: RDD[Vector]): RDD[Array[Array[Float]]] = {
    import DataUtils._
    **val paramMap = List("missing" -> "-999").toMap
    _booster.setParams(paramMap)**
     val broadcastBooster = testSet.sparkContext.broadcast(_booster)
    testSet.mapPartitions { testSamples =>
      if (testSamples.hasNext) {
        val dMatrix = new DMatrix(new JDMatrix(testSamples, null))
        Iterator(broadcastBooster.value.predict(dMatrix))
      } else {
        Iterator()
      }
    }
  }
```

**Comment by CodingCat** [comment]
@spacerunner9 , it is not available in java package right now...hopefully, I will get a chance to work on it in the weekedn

**Comment by spacerunner9** [comment]
do you have fix for this. It's seems the issue is closed so wonder if I can participate in any testing
