### ISSUE TITLE
Question: Cost sensitive multi-class classification with XGBoost

### ISSUE THREAD

**Issue by mhnamaki** [dmlc/xgboost#1262]
Hi,
Is there anyway to do a cost-sensitive multi-class classification with XGBoost? 
There is a data-driven solution for that (duplicating the data of the important classes) but I prefer to use XGBoost methods in a more principled manner.

Thanks.

**Comment by tqchen** [comment]
XGBoost suppport data importance in DMatrix with keyword weight
