### ISSUE TITLE
xgboost import error windows

### ISSUE THREAD

**Issue by Rafi993** [dmlc/xgboost#1266]
When I import xgboost in windows I get the following error. During installation it did not throw error I use windows 7 64 bit.
![capture3](https://cloud.githubusercontent.com/assets/8092120/15955101/34c5c60e-2efc-11e6-9e5b-164436aefd6e.PNG)

**Comment by tqchen** [comment]
You need to add path to this dll(likely in your mingw folder) to env variable PATH

**Comment by Rafi993** [comment]
thank you :+1:
