### ISSUE TITLE
 Makefile:75: recipe for target 'io.o' failed error during installation on windows 10 64bit

### ISSUE THREAD

**Issue by dev705370** [dmlc/xgboost#1269]
I am trying to install xgboost on windows 10 64bit. 
When I am trying to build dmlc-core module with make -j4 command, I am getting Makefile:75: recipe for target 'io.o' failed error. I have attached the complete output.

g++ -c -O3 -Wall -msse2  -Wno-unknown-pragmas -Iinclude  -std=c++0x -fopenmp -fPIC -DDMLC_USE_HDFS=0 -DDMLC_USE_S3=0 -DDMLC_USE_AZURE=0 -o line_split.o src/io/line_split.cc
g++ -c -O3 -Wall -msse2  -Wno-unknown-pragmas -Iinclude  -std=c++0x -fopenmp -fPIC -DDMLC_USE_HDFS=0 -DDMLC_USE_S3=0 -DDMLC_USE_AZURE=0 -o recordio_split.o src/io/recordio_split.cc
g++ -c -O3 -Wall -msse2  -Wno-unknown-pragmas -Iinclude  -std=c++0x -fopenmp -fPIC -DDMLC_USE_HDFS=0 -DDMLC_USE_S3=0 -DDMLC_USE_AZURE=0 -o input_split_base.o src/io/input_split_base.cc
g++ -c -O3 -Wall -msse2  -Wno-unknown-pragmas -Iinclude  -std=c++0x -fopenmp -fPIC -DDMLC_USE_HDFS=0 -DDMLC_USE_S3=0 -DDMLC_USE_AZURE=0 -o io.o src/io.cc
src/io/line_split.cc:1:0: warning: -fPIC ignored for target (all code is position independent)
 // Copyright by Contributors
 ^
src/io/recordio_split.cc:1:0: warning: -fPIC ignored for target (all code is position independent)
 // Copyright by Contributors
 ^
src/io.cc:1:0: warning: -fPIC ignored for target (all code is position independent)
 // Copyright by Contributors
 ^
src/io/input_split_base.cc:1:0: warning: -fPIC ignored for target (all code is position independent)
 // Copyright by Contributors
 ^
In file included from C:/Program Files/mingw-w64/x86_64-5.3.0-posix-seh-rt_v4-rev0/mingw64/x86_64-w64-mingw32/include/locale.h:12:0,
                 from C:/Program Files/mingw-w64/x86_64-5.3.0-posix-seh-rt_v4-rev0/mingw64/x86_64-w64-mingw32/include/c++/clocale:42,
                 from C:/Program Files/mingw-w64/x86_64-5.3.0-posix-seh-rt_v4-rev0/mingw64/x86_64-w64-mingw32/include/c++/x86_64-w64-mingw32/bits/c++locale.h:41,
                 from C:/Program Files/mingw-w64/x86_64-5.3.0-posix-seh-rt_v4-rev0/mingw64/x86_64-w64-mingw32/include/c++/bits/localefwd.h:40,
                 from C:/Program Files/mingw-w64/x86_64-5.3.0-posix-seh-rt_v4-rev0/mingw64/x86_64-w64-mingw32/include/c++/string:43,
                 from include/dmlc/base.h:154,
                 from src/io.cc:3:
C:/Program Files/mingw-w64/x86_64-5.3.0-posix-seh-rt_v4-rev0/mingw64/x86_64-w64-mingw32/include/stdio.h:450:83: error: 'FILE\* std::fopen(const char_, const char_)' should have been declared inside 'std'
   FILE _fopen64(const char \* **restrict** filename,const char \* **restrict**  mode);
                                                                                   ^
C:/Program Files/mingw-w64/x86_64-5.3.0-posix-seh-rt_v4-rev0/mingw64/x86_64-w64-mingw32/include/stdio.h:450:83: error: 'FILE_ std::fopen(const char_, const char_)' conflicts with a previous declaration
C:/Program Files/mingw-w64/x86_64-5.3.0-posix-seh-rt_v4-rev0/mingw64/x86_64-w64-mingw32/include/stdio.h:449:17: note: previous declaration 'FILE\* fopen(const char_, const char_)'
   FILE _**cdecl fopen(const char \* __restrict** _Filename,const char \* __restrict__ _Mode) __MINGW_ATTRIB_DEPRECATED_SEC_WARN;
                 ^
g++ -c -O3 -Wall -msse2  -Wno-unknown-pragmas -Iinclude  -std=c++0x -fopenmp -fPIC -DDMLC_USE_HDFS=0 -DDMLC_USE_S3=0 -DDMLC_USE_AZURE=0 -o local_filesys.o src/io/local_filesys.cc
src/io/local_filesys.cc:1:0: warning: -fPIC ignored for target (all code is position independent)
 // Copyright by Contributors
 ^
g++ -c -O3 -Wall -msse2  -Wno-unknown-pragmas -Iinclude  -std=c++0x -fopenmp -fPIC -DDMLC_USE_HDFS=0 -DDMLC_USE_S3=0 -DDMLC_USE_AZURE=0 -o data.o src/data.cc
src/data.cc:1:0: warning: -fPIC ignored for target (all code is position independent)
 // Copyright by Contributors
 ^
In file included from C:/Program Files/mingw-w64/x86_64-5.3.0-posix-seh-rt_v4-rev0/mingw64/x86_64-w64-mingw32/include/locale.h:12:0,
                 from C:/Program Files/mingw-w64/x86_64-5.3.0-posix-seh-rt_v4-rev0/mingw64/x86_64-w64-mingw32/include/c++/clocale:42,
                 from C:/Program Files/mingw-w64/x86_64-5.3.0-posix-seh-rt_v4-rev0/mingw64/x86_64-w64-mingw32/include/c++/x86_64-w64-mingw32/bits/c++locale.h:41,
                 from C:/Program Files/mingw-w64/x86_64-5.3.0-posix-seh-rt_v4-rev0/mingw64/x86_64-w64-mingw32/include/c++/bits/localefwd.h:40,
                 from C:/Program Files/mingw-w64/x86_64-5.3.0-posix-seh-rt_v4-rev0/mingw64/x86_64-w64-mingw32/include/c++/string:43,
                 from include/dmlc/base.h:154,
                 from src/data.cc:2:
C:/Program Files/mingw-w64/x86_64-5.3.0-posix-seh-rt_v4-rev0/mingw64/x86_64-w64-mingw32/include/stdio.h:450:83: error: 'FILE_ std::fopen(const char_, const char_)' should have been declared inside 'std'
   FILE _fopen64(const char \* **restrict** filename,const char \* **restrict**  mode);
                                                                                   ^
C:/Program Files/mingw-w64/x86_64-5.3.0-posix-seh-rt_v4-rev0/mingw64/x86_64-w64-mingw32/include/stdio.h:450:83: error: 'FILE_ std::fopen(const char_, const char_)' conflicts with a previous declaration
C:/Program Files/mingw-w64/x86_64-5.3.0-posix-seh-rt_v4-rev0/mingw64/x86_64-w64-mingw32/include/stdio.h:449:17: note: previous declaration 'FILE\* fopen(const char_, const char_)'
   FILE _**cdecl fopen(const char \* __restrict** _Filename,const char \* __restrict__ _Mode) __MINGW_ATTRIB_DEPRECATED_SEC_WARN;
                 ^
Makefile:75: recipe for target 'io.o' failed
make: *_\* [io.o] Error 1
make: **\* Waiting for unfinished jobs....
In file included from include/dmlc/data.h:16:0,
                 from src/data.cc:5:
include/dmlc/./registry.h:218:22: warning: 'dmlc::**make_ParserFactoryReg_uint32_t_libsvm**' defined but not used [-Wunused-variable]
   static EntryType & **make_ ## EntryTypeName ## _ ## Name ## __ =      \
                      ^
include/dmlc/data.h:303:3: note: in expansion of macro 'DMLC_REGISTRY_REGISTER'
   DMLC_REGISTRY_REGISTER(::dmlc::ParserFactoryReg<IndexType>,           \
   ^
src/data.cc:136:1: note: in expansion of macro 'DMLC_REGISTER_DATA_PARSER'
 DMLC_REGISTER_DATA_PARSER(uint32_t, libsvm, data::CreateLibSVMParser<uint32_t>);
 ^
include/dmlc/./registry.h:218:22: warning: 'dmlc::__make_ParserFactoryReg_uint64_t_libsvm**' defined but not used [-Wunused-variable]
   static EntryType & **make_ ## EntryTypeName ## _ ## Name ## __ =      \
                      ^
include/dmlc/data.h:303:3: note: in expansion of macro 'DMLC_REGISTRY_REGISTER'
   DMLC_REGISTRY_REGISTER(::dmlc::ParserFactoryReg<IndexType>,           \
   ^
src/data.cc:137:1: note: in expansion of macro 'DMLC_REGISTER_DATA_PARSER'
 DMLC_REGISTER_DATA_PARSER(uint64_t, libsvm, data::CreateLibSVMParser<uint64_t>);
 ^
include/dmlc/./registry.h:218:22: warning: 'dmlc::__make_ParserFactoryReg_uint32_t_csv**' defined but not used [-Wunused-variable]
   static EntryType & **make_ ## EntryTypeName ## _ ## Name ## __ =      \
                      ^
include/dmlc/data.h:303:3: note: in expansion of macro 'DMLC_REGISTRY_REGISTER'
   DMLC_REGISTRY_REGISTER(::dmlc::ParserFactoryReg<IndexType>,           \
   ^
src/data.cc:139:1: note: in expansion of macro 'DMLC_REGISTER_DATA_PARSER'
 DMLC_REGISTER_DATA_PARSER(uint32_t, csv, data::CreateCSVParser<uint32_t>);
 ^
In file included from include/dmlc/./registry.h:14:0,
                 from include/dmlc/data.h:16,
                 from src/data.cc:5:
include/dmlc/././parameter.h:254:43: warning: 'dmlc::data::__make__CSVParserParamParamManager**' defined but not used [-Wunused-variable]
   static ::dmlc::parameter::ParamManager &**make** ## PType ## ParamManager__ = \
                                           ^
src/data.cc:93:1: note: in expansion of macro 'DMLC_REGISTER_PARAMETER'
 DMLC_REGISTER_PARAMETER(CSVParserParam);
 ^
Makefile:75: recipe for target 'data.o' failed
make: **\* [data.o] Error 1

**Comment by sandro-felicioni** [comment]
I think this is a duplicate post and a working solution has already been proposed here: https://github.com/dmlc/xgboost/issues/1267
