### ISSUE TITLE
[jvm-packages] XGBoost Spark hang when nWorkers is set to greater than 1

### ISSUE THREAD

**Issue by titicaca** [dmlc/xgboost#1276]
We tried to run xgboost on local spark 1.5.1 and 1.6.1, but got the following issue:

when we set the nWorkers greater than 1 on local Spark 1.6.1, it stuck, tasks cannot be executed. But when nWorkers = 1, it works. 

![image](https://cloud.githubusercontent.com/assets/1780746/16032326/27a35aca-3237-11e6-9bb8-78c94d44c394.png)

The most weird thing is that, on local Spark 1.5.1, if we set nWorker to 1 and 2, it can work. But when nWorker is greater than 2, it hangs.

Any idea about this problem? Should we limit nWorkers not greater than the number of nodes?

Our codes are as follows:

`

    val sparkConf = new SparkConf().setAppName("XGBoost-spark-example").setMaster("local")
        .set("spark.serializer", "org.apache.spark.serializer.KryoSerializer")
    sparkConf.registerKryoClasses(Array(classOf[Booster]))
    val sc = new SparkContext(sparkConf)
    val filepath = "."
    val data = sc.textFile(filepath + "dt.iris.data", 2)
    val splits = data.randomSplit(Array(0.8, 0.2), seed = 100L)
    val trainData = splits(0).map { line =>
      val parts = line.split(",")
      val label = parts(0).toDouble
      val features = Vectors.dense(parts.tail.map(x => x.toDouble))
      LabeledPoint(label, features);
    }
    val sep = ","
    val configMapStr = List(
      "objective" -> "multi:softmax",
      "objective" -> "multi:softmax",
      "num_class" -> 3,
      "eval_metric" -> "mlogloss",
      "eta" -> 0.3,
      "max_depth" -> 2,
      "gamma" -> 0,
      "subsample" -> 1,
      "colsample_bytree" -> 1,
      "min_child_weight" -> 1).toMap
    val model = XGBoost.train(trainData, configMapStr, 100, 1, null, null, false)

`

**Comment by CodingCat** [comment]
@titicaca the number of xgboost workers means that how many parallel trainers (Spark tasks) you want in xgboost, 

if you set it to 2, you have to ensure that your machine has at least two cores to run two parallel tasks (if you set a larger value of nthreads, it would be more than 2 cores)

**Comment by titicaca** [comment]
@CodingCat Thanks for the reply. But will it gets stuck when the number of tasks is greater than the total number of cores?  It seems the tasks are hanging by rabit init.

**Comment by CodingCat** [comment]
that's exactly the situation I described...rabit.init() hangs to wait for X trainers (tasks) to start

**Comment by titicaca** [comment]
Okay. Now I see. Thank you!

**Comment by xinyuwuhenZZ** [comment]
How could you run it? I run xgboos-spark on local spark-1.6.1, but I got those errors:

16/06/23 16:16:10 ERROR RabitTracker: load tracker library failed.
16/06/23 16:16:10 ERROR RabitTracker: java.io.FileNotFoundException: File /tracker.py was not found inside JAR.
Tracker started, with env={}
16/06/23 16:16:10 INFO RabitTracker$TrackerProcessLogger: /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'null': [Errno 2] No such file or directory
16/06/23 16:16:10 INFO RabitTracker$TrackerProcessLogger: Tracker Process ends with exit code 2
16/06/23 16:16:10 INFO XGBoostSpark: repartitioning training set to 1 partitions
16/06/23 16:16:10 INFO RabitTracker: Tracker Process ends with exit code 2
16/06/23 16:16:10 INFO XGBoostSpark: Rabit returns with exit code 2
Exception in thread "main" ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed

Any help would be appreciated!

**Comment by titicaca** [comment]
ERROR RabitTracker: java.io.FileNotFoundException: File /tracker.py was not found inside JAR.

Maybe you can check your jar and make sure you have the tracker.py inside.

**Comment by fc1plusx** [comment]
Hi, sorry to post on this closed issue (seems the most appropriate one). Still I'm not 100% sure about how to set numWorkers in the distributed scenario. Let's say I have a cluster with 3 machines, each with 4 cores. Should I use numWorkers = 12, numWorkers = 3, or numWorkers = 4? Thanks!

**Comment by CodingCat** [comment]
if you're sure about that you can run 12 tasks in parallel, you can set to 12,

**Comment by fc1plusx** [comment]
Many thanks for the quick reply! Unfortunately, I fear I'm not understanding your answer completely. I'm sure I've 4 cores per machine, and 3 machines in the cluster. Is there anything else I should worry about?

**Comment by CodingCat** [comment]
no

**Comment by xydrolase** [comment]
It would also work if you set `nthread` in XGBoost to 4, and configure `spark.task.cpus` in Spark to 4. Then, use `numWorkers = 3`, while launching 3 executors.

The level of parallelism is identical on paper, but in practice might be faster due to less Rabit synchronization etc.

**Comment by fc1plusx** [comment]
Thanks a lot! I tried your suggestion and indeed training seems slightly faster. I'm wondering if this is related only to less synchronisation code or also on the different number of partitions (I observed that data is repartitioned according to `numWorkers` before training starts).

**Comment by xydrolase** [comment]
It depends on how much data you used for your training set. By using 3 workers, yes you will have less partitions, so each partition ends up with more training samples. But you have have 4 cores for crunching the data in each partition. If there are many samples, XGBoost will switch to quantile sketching to speed up the computation. 

If you dataset is not gigantic, the speed-up you've noticed is most likely due to less synchronization between Rabit workers. Also, keep in mind that as you have more workers, the time for building each tree is determined by the slowest worker. If you have multiple worker nodes that have a large variance in computing power (or resources), the overall training time will be prolonged due to slower nodes. 

In your case, if you have three executors, you can subsample your training sample to about 1/3 of the original size, and train a model on a single node without using Spark, with 4 cores. It will give you an idea about how long does it take to train a model without synchronization, so that you can tune the parameters accordingly down the road.

**Comment by fc1plusx** [comment]
Many thanks for the explanation and the helpful suggestions!

**Comment by kamaldsingh** [comment]
even when i tried with nWorkers = 1 the training gets stuck for me.
