### ISSUE TITLE
Any guide on tuning performance of XGBoost-on-YARN?

### ISSUE THREAD

**Issue by hellocaffeine** [dmlc/xgboost#1282]
i have my Spark cluster of two nodes with 64+88 cores and 128+128G memory. my xgb training data is around 14G.
for now, i mainly tuning these parameters:
- spark.executor.memory
- spark.executor.instances
- spark.executor.cores
- spark.task.cpus
- spark.yarn.executor.memoryOverhead
- spark.storage.memoryFraction
- spark.driver.memory
- nthread
  but no matter how i tried, i just can't fully utilise all the cores. best scenario, all cores were used but with around 50% usage.
  can anyone give me a detailed guide on how to tuning the performance and maybe show me the best performance i can get? appreciate it!

**Comment by pommedeterresautee** [comment]
Please check the documentation
