### ISSUE TITLE
Error importing xgboost

### ISSUE THREAD

**Issue by llmercury** [dmlc/xgboost#1289]
_Following the official installation guide (http://xgboost.readthedocs.io/en/latest/build.html) and Cortajarena's tip (https://github.com/dmlc/xgboost/issues/1267), I successfully installed xgboost in my laptop. I am using Anaconda 4.0.0 with Python 3.5.1 on Windows 10._

_However, when I imported xgboost in jupyter notebook,_

import os
mingw_path = "C:\TDM-GCC-64\bin"
os.environ['PATH'] = mingw_path + ';' + os.environ['PATH']
import xgboost as xgb

_I got error message:_

OSError Traceback (most recent call last)
in ()
----> 1 import xgboost as xgb

C:\Users\Adminstrator\Anaconda3\lib\site-packages\xgboost-0.4-py3.5.egg\xgboost__init__.py in ()
9 import os
10 
---> 11 from .core import DMatrix, Booster
12 from .training import train, cv
13 from . import rabit # noqa

C:\Users\Administrator\Anaconda3\lib\site-packages\xgboost-0.4-py3.5.egg\xgboost\core.py in ()
110 
111 # load the XGBoost library globally
--> 112 _LIB = _load_lib()
113 
114

C:\Users\Administrator\Anaconda3\lib\site-packages\xgboost-0.4-py3.5.egg\xgboost\core.py in _load_lib()
104 if len(lib_path) == 0:
105 return None
--> 106 lib = ctypes.cdll.LoadLibrary(lib_path[0])
107 lib.XGBGetLastError.restype = ctypes.c_char_p
108 return lib

C:\Users\Administrator\Anaconda3\lib\ctypes__init__.py in LoadLibrary(self, name)
423 
424 def LoadLibrary(self, name):
--> 425 return self._dlltype(name)
426 
427 cdll = LibraryLoader(CDLL)

C:\Users\Administrator\Anaconda3\lib\ctypes__init__.py in init(self, name, mode, handle, use_errno, use_last_error)
345 
346 if handle is None:
--> 347 self._handle = _dlopen(self._name, mode)
348 else:
349 self._handle = handle

OSError: [WinError 1114] A dynamic link library (DLL) initialization routine failed.

_Did anyone else have the same problem? Any idea how to fix it?_

**Comment by winint** [comment]
I'm having the same problem, it seems libomp or something that libxgboost depends on throws an exception thus libxgboost dll does not load, there is another open issue that says only a specific mingw version is supported but i did not try it

**Comment by roch02** [comment]
Did you solve this problem?
