### ISSUE TITLE
libstdc++.so.6 not found `GLIBCXX_3.4.20' 

### ISSUE THREAD

**Issue by jintw** [dmlc/xgboost#1291]
I have installed xgboost successfully on a RedHat server. 
And the libstdc++.so.6 link to my gcc-5.2.0's libstdc++.so, but when other people, who use the server too, change the env, my xgboost will crash. Where I can change xgboost config, so it can directly use the gcc-5.2.0's libstdc++, not use the /usr/lib64/libstdc++.

我在一台服务器上装好了xgboost，但是环境经常被修改，主要是几个gcc的库，我想修改xgboost的配置 指定libstdc++

**Comment by thirdwing** [comment]
I don't think this is possible in xgboost side.

**Comment by tqchen** [comment]
chang your environment var locally in a bash will do.

**Comment by jintw** [comment]
Thank you.

**Comment by LancelotHolmes** [comment]
maybe you can try `conda install libgcc` which worked for many people from this [#1043](https://github.com/dmlc/xgboost/issues/1043)
