### ISSUE TITLE
[jvm-packages] Running Error of xgboost-spark

### ISSUE THREAD

**Issue by xinyuwuhenZZ** [dmlc/xgboost#1294]
I run xgboost-spark on local spark-1.6.1, but I got those errors:

16/06/23 16:16:10 ERROR RabitTracker: load tracker library failed.
16/06/23 16:16:10 ERROR RabitTracker: java.io.FileNotFoundException: File /tracker.py was not found inside JAR.
Tracker started, with env={}
16/06/23 16:16:10 INFO RabitTracker$TrackerProcessLogger: /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'null': [Errno 2] No such file or directory
16/06/23 16:16:10 INFO RabitTracker$TrackerProcessLogger: Tracker Process ends with exit code 2
16/06/23 16:16:10 INFO XGBoostSpark: repartitioning training set to 1 partitions
16/06/23 16:16:10 INFO RabitTracker: Tracker Process ends with exit code 2
16/06/23 16:16:10 INFO XGBoostSpark: Rabit returns with exit code 2
Exception in thread "main" ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed

I am wondering why it need to load tracker.py?
Any help would be appreciated!

**Comment by CodingCat** [comment]
Hi, it seems that you didn't download the rabit submodule, 

try `git pull && git submodule init && git submodule update && git submodule status` when clone the repo

**Comment by xinyuwuhenZZ** [comment]
I tried it, but did not work.

Directory：
drwxr-xr-x jvm-packages/
drwxr-xr-x rabit/
