### ISSUE TITLE
custom objective  for  mean absolute percentage error (MAPE)

### ISSUE THREAD

**Issue by gogolgrind** [dmlc/xgboost#1295]
Hello every one! For now I do some task about regression, and in this case I use [MAPE](https://en.wikipedia.org/wiki/Mean_absolute_percentage_error) metric.
I really need to try to use xgbost with custom objective (because other custom in my case has bad scores)  , but i don't understand how to implement same way as is in the [guide](https://github.com/dmlc/xgboost/blob/master/demo/guide-python/custom_objective.py)

E.g If I  compute some-how partial derivatives i get two component vector for grad and hess, but according to guide I must return n_sampe size array. Am i right?
Thank you for any help!

**Comment by pommedeterresautee** [comment]
Old question, no answer. Closing.
