### ISSUE TITLE
make train and test set problem

### ISSUE THREAD

**Issue by allanruin** [dmlc/xgboost#1297]
I use the script `mknfold.py` to split my total data into a training set and a test set. But when I load train and test data:

```
dtrain = xgb.DMatrix('data.libsvm.train')
dtest = xgb.DMatrix('data.libsvm.test')

param = {'max_depth':3, 'eta':1, 'silent':1, 'objective':'multi:softmax',
'num_class':8,'eval_metric':'merror'}
num_round = 2
watchlist  = [(dtest,'eval'), (dtrain,'train')]
bst = xgb.train(param, dtrain, num_round, watchlist)
```

I ran into error, got 

```
..., 'f98491', 'f98492', 'f98493']
expected f98494, f98495 in input data
Exception AttributeError: "'Booster' object has no attribute 'handle'" in
 <bound method Booster.__del__ of <xgboost.core.Booster object at 0x7f575576ccd0>> ignored
```

I inspected the size of `dtrain` and `dtest`, they are:

```
[10:13:33] 178535x98496 matrix with 2246848 entries loaded from data.libsvm.train
[10:13:33] 44570x98494 matrix with 561075 entries loaded from data.libsvm.test
178535 44570
```

We can see that `dtrain` has 98496 features, and `dtest` has 98494 features. I assumed that the  column size of DMatrix is based on the largest feature indice of all data in a file, so I got different  column size , which cause error.

Could you tell me how to solved this? Thank you

**Comment by stone8oy** [comment]
Did you solve the problem? If so ,could you please share! Thanks.

**Comment by adityagore** [comment]
I also ran in to similar problem. Has a solution been found yet?

**Comment by jenniyanjie** [comment]
I have the same problem..

**Comment by redpoint13** [comment]
Exception AttributeError: "'Booster' object has no attribute 'handle'" in <bound method Booster.__del__ of <xgboost.core.Booster object at 0x000000016586E8D0>> ignored

**Comment by JimmyCai** [comment]
I have the same problem. Any one solve the problem yet?

**Comment by oldmonk101** [comment]
Same issue for LTR "objective": "rank:pairwise"

**Comment by leic17** [comment]
I have the same problem. Any one solve the problem yet?

**Comment by Yevgeny86** [comment]
I have solved this.

In my case:
dtrain and dtest had different (num features).
make sure you have exactly the same number of features in both of them.

dtrain = xgb.DMatrix(X_train, y_train, missing=-99)
dtest = xgb.DMatrix(X_test, y_test, missing=-99)
