### ISSUE TITLE
XGBOOST hangs 

### ISSUE THREAD

**Issue by eran-aharonovich** [dmlc/xgboost#1298]
Hi,
XGBOOST hangs with a specific model I created after 2,750,000 calls to predict using R.
It's happened to me before with a different model after 300,000 calls to predict. 

Please find attached the saved XGBOOST model.

Thanks in advance

[GrupoBimbo_SALES_R_MODEL.txt](https://github.com/dmlc/xgboost/files/332909/GrupoBimbo_SALES_R_MODEL.txt)

**Comment by hetong007** [comment]
Now it is fixed by https://github.com/dmlc/xgboost/pull/1489
