### ISSUE TITLE
XGBoostLibraryNotFound when installing python library

### ISSUE THREAD

**Issue by joristork** [dmlc/xgboost#1300]
On Debian with kernel `4.6.0-1-amd64`, `gcc-6` and `g++-6` installed and working, I performed a fresh `git clone --recursive https://github.com/dmlc/xgboost` then `cd xgboost; make -j8` (no errors) then `cd python-package` and `python3 setup.py install` and I get the following error:

```
Traceback (most recent call last):
  File "setup.py", line 19, in <module>
    LIB_PATH = libpath['find_lib_path']()
  File "xgboost/libpath.py", line 45, in find_lib_path
    'List of candidates:\n' + ('\n'.join(dll_path)))
XGBoostLibraryNotFound: Cannot find XGBoost Libarary in the candicate path, did you install compilers and run build.sh in root path?
List of candidates:
/home/joris/xgboost/python-package/xgboost/libxgboost.so
/home/joris/xgboost/python-package/xgboost/../../lib/libxgboost.so
/home/joris/xgboost/python-package/xgboost/./lib/libxgboost.so
```

Using locate I cannot find any file named `libxgboost.so` on my system. I have tried the solutions detailed in the troubleshooting python installation doc. I've tried `python3 setup.py install --user` and `python3 setup.py develop --user`. I've tried `pip3 install xgboost` but that version is out-of-date.

**Comment by Timoux** [comment]
The same problem for me ...

**Comment by OakSuen** [comment]
I have the same problem

**Comment by kesjien** [comment]
One of the solutions which helped me was to degrade to gcc5. Was on mac.
brew install gcc5

**Comment by litaxc** [comment]
Same problem here.
and `brew install gcc5` didn't make it either.
