### ISSUE TITLE
Running Issue

### ISSUE THREAD

**Issue by guozhizou** [dmlc/xgboost#1306]
I am confused what mushroom.aws.conf do when submmit jobs, and what it likes?

../../dmlc-core/tracker/dmlc-submit --cluster=yarn --num-workers=2 --worker-cores=2\
    ../../xgboost mushroom.aws.conf nthread=2\
    data=s3://${BUCKET}/xgb-demo/train\
    eval[test]=s3://${BUCKET}/xgb-demo/test\
    model_dir=s3://${BUCKET}/xgb-demo/model

ths!

**Comment by khotilov** [comment]
It would be pretty obvious when you would look inside of mushroom.aws.conf
