### ISSUE TITLE
DMLC XGBoost on Spark does not seem to correctly train

### ISSUE THREAD

**Issue by smundhra** [dmlc/xgboost#1309]
Looking at the scource code at ml.dmlc.xgboost4j.scala.spark.XGBoost : method **buildDistributedBoosters** builds model by training on each partition and returns it to **train** method which simply then returns the first booster as **boosters.first()**
   Please correct me if I am wrong .

**Comment by CodingCat** [comment]
all boosters are the same after training due to allreduce

**Comment by smundhra** [comment]
Thanks for the super quick reply; I will try to go through source to understand that better.
After training the result is an RDD of Arr[Arr[Float]] .I understand that the results for all the data points on a single partition are collected as  arr of single valued array containg p values.
But I am unsure as to how I can map these probability values to original dataset.
Would appreciate your pointers on the same.

**Comment by CodingCat** [comment]
look at the example : https://github.com/dmlc/xgboost/blob/master/jvm-packages/xgboost4j-example/src/main/java/ml/dmlc/xgboost4j/java/example/CustomObjective.java
