### ISSUE TITLE
eta decay in R

### ISSUE THREAD

**Issue by Eric2333** [dmlc/xgboost#1310]
It seems that eta decay/dynamic eta is already available in python. But I am not sure how to do that in R. I've try to modify the xgb.train() function by moving
`handle <- xgb.Booster(params, append(watchlist, dtrain))`
 `bst <- xgb.handleToBooster(handle)`
into the nround loop and add `params$eta = params$eta * decay` before them. But when test the new function, the eval_metric output the same score for every round, maybe the modification makes the random seed reset?

**Comment by khotilov** [comment]
Dynamic parameter adjustment (not only eta) would be available through #1264 using callback-based interface when it would be merged in. You can also check it out as it is and give is some test runs if you want to.

**Comment by jdmlaureate** [comment]
For me it takes `eta_decay` as a param but doesn't seem to actually use it. Can anyone confirm if they got this working?

**Comment by khotilov** [comment]
@jdmlaureate see the example within `?xgb.train` documentation on how to use the `cb.reset.parameters()` callback as well as `?cb.reset.parameters`. There's no `eta_decay` parameter.
