### ISSUE TITLE
xgboost eat all the memory of the master node

### ISSUE THREAD

**Issue by wenmin-wu** [dmlc/xgboost#1311]
@tqchen Hi~ tianqi, sorry to disturb you again. I run the xgboost on yarn, but sometimes the xgboost process will eat all the memory of the machine which I submitted the job. I know the Spark can run in both `yan-cluster` and `yarn-client` mode. Which mode dose the xgboost run on yarn? and Is that is why the xgboost will eat all the memory?

**Comment by wenmin-wu** [comment]
I use the `top` command and find that the jvm launched by xgboost occupy too much virtual memory.
![xgboost-virt](https://cloud.githubusercontent.com/assets/9409333/16496082/d15c8a1c-3f22-11e6-8a8d-667c7c839fed.png)

**Comment by CodingCat** [comment]
you do not need to worry about virt, http://mugurel.sumanariu.ro/linux/the-difference-among-virt-res-and-shr-in-top-output/

**Comment by wenmin-wu** [comment]
@CodingCat Thanks for you reply! Because there are too many jobs run on the machine which I launch the xgboost, if this process occupy too much VIRT, it must influence other processes. I find that the xgboost run on local mode also occupy around 35G VIRT. I think it should not occupy this size of VIRT on distributed mode.
