### ISSUE TITLE
Exception from container-launch when running distributed demo

### ISSUE THREAD

**Issue by sparktsao** [dmlc/xgboost#1313]
I follow the article "Distributed XGBoost YARN on AWS" but met a issue of "Exception from container-launch" when run the distributed demo.

any one have idea how to go one step further to debug the issue?

```
16/06/28 07:58:59 INFO dmlc.ApplicationMaster: [DMLC] Task 1 exited with status 250 Diagnostics:Exception from container-launch.
Container id: container_1467084431684_0007_01_000003
Exit code: 250
Stack trace: ExitCodeException exitCode=250: 
    at org.apache.hadoop.util.Shell.runCommand(Shell.java:538)
    at org.apache.hadoop.util.Shell.run(Shell.java:455)
    at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:715)
    at org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.launchContainer(DefaultContainerExecutor.java:211)
    at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
    at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)


Container exited with a non-zero exit code 250
```

**Comment by sparktsao** [comment]
I have done 
make test/filesys_test
and seems it have problem when trying to access s3:

```
ubuntu@ip-172-31-41-90:~/xgboost/dmlc-core$ ./test/filesys_test ls /
/opt    4096    is_dir=1
/home   4096    is_dir=1
/disk   4096    is_dir=1
/vmlinuz        5815680 is_dir=0
/lost+found     16384   is_dir=1
/media  4096    is_dir=1
/var    4096    is_dir=1
/sys    0       is_dir=1
/usr    4096    is_dir=1
/sbin   4096    is_dir=1
/etc    4096    is_dir=1
/mnt    4096    is_dir=1
/root   4096    is_dir=1
/tmp    4096    is_dir=1
/proc   0       is_dir=1
/boot   4096    is_dir=1
/run    680     is_dir=1
/initrd.img     7266051 is_dir=0
/bin    4096    is_dir=1
/lib    4096    is_dir=1
/lib64  4096    is_dir=1
/srv    4096    is_dir=1
/dev    3920    is_dir=1
ubuntu@ip-172-31-41-90:~/xgboost/dmlc-core$ ./test/filesys_test ls s3://
[06:19:10] include/dmlc/logging.h:235: [06:19:10] src/io/s3_filesys.cc:755: Check failed: path.host.length() != 0 bucket name not specified in s3
terminate called after throwing an instance of 'dmlc::Error'
  what():  [06:19:10] src/io/s3_filesys.cc:755: Check failed: path.host.length() != 0 bucket name not specified in s3
Aborted (core dumped)
```

**Comment by sparktsao** [comment]
i can manually access hdfs but fail with the tool: ./test/filesys_test
```
ubuntu@ip-172-31-41-90:~/xgboost/dmlc-core$ hadoop fs -ls /tmp/temp-dmlc-yarn-application_1467189669261_0004
Found 4 items
-rwxrwxrwx   1 ubuntu supergroup      21416 2016-06-30 03:42 /tmp/temp-dmlc-yarn-application_1467189669261_0004/dmlc-yarn.jar
-rwxrwxrwx   1 ubuntu supergroup       2696 2016-06-30 03:42 /tmp/temp-dmlc-yarn-application_1467189669261_0004/launcher.py
-rwxrwxrwx   1 ubuntu supergroup        857 2016-06-30 03:42 /tmp/temp-dmlc-yarn-application_1467189669261_0004/mushroom.aws.conf
-rwxrwxrwx   1 ubuntu supergroup    2033116 2016-06-30 03:42 /tmp/temp-dmlc-yarn-application_1467189669261_0004/xgboost
ubuntu@ip-172-31-41-90:~/xgboost/dmlc-core$ ./test/filesys_test ls hdfs://tmp/temp-dmlc-yarn-application_1467189669261_0004
loadFileSystems error:
(unable to get stack trace for java.lang.NoClassDefFoundError exception: ExceptionUtils::getStackTrace error.)
hdfsBuilderConnect(forceNewInstance=0, nn=tmp, port=0, kerbTicketCachePath=(NULL), userName=(NULL)) error:
(unable to get stack trace for java.lang.NoClassDefFoundError exception: ExceptionUtils::getStackTrace error.)
[06:40:20] include/dmlc/logging.h:235: [06:40:20] src/io/hdfs_filesys.cc:95: Failed to load HDFS-configuration:
terminate called after throwing an instance of 'dmlc::Error'
  what():  [06:40:20] src/io/hdfs_filesys.cc:95: Failed to load HDFS-configuration:
Aborted (core dumped)
```

**Comment by sparktsao** [comment]
after fix the classpath issue with adding hadoop classpath --glob to CLASSPATH,
seems i dont have authentication to HDFS, and all the logs write to there?
```
ubuntu@ip-172-31-41-90:~/xgboost/dmlc-core$ ./test/filesys_test ls hdfs://
hdfsBuilderConnect(forceNewInstance=0, nn=, port=0, kerbTicketCachePath=(NULL), userName=(NULL)) error:
java.lang.IllegalArgumentException: Expected authority at index 7: hdfs://
        at java.net.URI.create(URI.java:852)
Caused by: java.net.URISyntaxException: Expected authority at index 7: hdfs://
        at java.net.URI$Parser.fail(URI.java:2848)
        at java.net.URI$Parser.failExpecting(URI.java:2854)
        at java.net.URI$Parser.parseHierarchical(URI.java:3102)
        at java.net.URI$Parser.parse(URI.java:3053)
        at java.net.URI.<init>(URI.java:588)
        at java.net.URI.create(URI.java:850)
[06:52:08] include/dmlc/logging.h:235: [06:52:08] src/io/hdfs_filesys.cc:95: Failed to load HDFS-configuration:
terminate called after throwing an instance of 'dmlc::Error'
  what():  [06:52:08] src/io/hdfs_filesys.cc:95: Failed to load HDFS-configuration:
Aborted (core dumped)
```

**Comment by sparktsao** [comment]
finally, we ask our AWS admin to rerun the xgboost distributed tutorial, then success.
we were wondering  if it's caused by our default VPC has complex subnetwork rounting made some internal request fail?

**Comment by sparktsao** [comment]
now i can run demo/distributed_training, and a dataset with 6G successfully,
but when i try to train with data size 160G(30M rows, 2000 columns), i still met message:

16/07/14 23:55:53 INFO dmlc.ApplicationMaster: Task 0 failed on container_1468536895752_0002_01_000002. See LOG at : http://ip-172-16-11-208.ec2.internal:8042/node/containerlogs/container_1468536895752_0002_01_000002/yarn

[23:55:52] rabit/include/rabit/./internal/../../dmlc/././logging.h:245: [23:55:52] src/io/s3_filesys.cc:792: Check failed: data.str() == "false" the returning list is truncated
terminate called after throwing an instance of 'dmlc::Error'
  what():  [23:55:52] src/io/s3_filesys.cc:792: Check failed: data.str() == "false" the returning list is truncated

any advises to debug?

**Comment by sparktsao** [comment]
it's due to the input data corrupts.
after remove all the bad formated lines, it works.

**Comment by shengshen** [comment]
@sparktsao I also encountered this error. Could you let me know your solution? 
my error as following:
hdfsBuilderConnect(forceNewInstance=0, nn=, port=0, kerbTicketCachePath=(NULL), userName=(NULL)) error:
java.lang.IllegalArgumentException: Expected authority at index 7: hdfs://
	at java.net.URI.create(URI.java:859)

**Comment by sparktsao** [comment]
@shengshen i am not quite sure the detail root cause.
My environment is complex, because i am not the root(admin) of the EC2,
We are wondering permission is the root cause. so the secret key and private key can not do something.
So i request the help to our EC2 account administrator use he account to run the demo.
and it works.
are you admin of your EC2 account? 

The other possible reason is the default subnet routing is too complex in my precious env,  it might block some traffic between computing nodes. 

by the way, now we can use EC2 EMR to run the distributed XGBoost, too. FYR.

**Comment by shengshen** [comment]
@sparktsao thank you for your message. Your solution about xgboost yarn on AWS is helpful. I have fixed my issue too. (when I set the full path of the hdfs, it works. You can see the detail:https://github.com/dmlc/xgboost/issues/1374)
So i will have a try about  xgboost yarn on AWS, just follow you. Wish a good luck~
