### ISSUE TITLE
About how to install xgboost on Windows 7 x64

### ISSUE THREAD

**Issue by BowieHsu** [dmlc/xgboost#1316]
I am a beginner of xgboost
it takes me one day to install xgboost on my PC with Windows7 x64 OS
Finally,under the guide from blog on csdn, I installed xgboost successfully.
The key components should be:
**1.TDM-GCC (x64)**
https://sourceforge.net/projects/tdm-gcc/files/TDM-GCC%20Installer/tdm64-gcc-5.1.0-2.exe/download
**(Make sure you selected the openmp when you install TDM-GCC)**
**After you installed TDM-GCC, you should enter the directory of it, which on my PC should be "C:\TDM-GCC-64\bin" rename the "mingw32-make.exe" to "make.exe"**
**2.Anaconda(x64)**
**3.Git Bash**
it's important to use Git Bash to install xgboost because cmd can not recognize "mkdir -p"

Now click Git Bash and type the order
`git clone --recursive https://github.com/dmlc/xgboost`
`cd xgboost` 
`git checkout 9a48a40` 
`git submodule init`
`git submodule update`
`cp make/mingw64.mk config.mk`
`cp make/mingw64.mk dmlc-core/config.mk`

`cd rabit`
`make lib/librabit_empty.a -j4`

`cd ../dmlc-core`
`make -j4`

`cd ..`
`make -j4`

**now you should have compile xgboost.dll successfully,check it under directory "../lib"
next step we install python package**
`using name space std`
`cd python package`
`python setup.py install`

**test xgboost python package**
`import xgboost as xgb`
`help(xgb)`

`cd ..` 
`cd demo` 
`cd guide-python`
`python basic_walkthrough.py`

the url of csdn blog [http://blog.csdn.net/bon_mot/article/details/51742869#0-tsina-1-68989-397232819ff9a47a7b7e80a40613cfe1](url)

enjoy it and have fun!

**Comment by tqchen** [comment]
It would be great if you can open a PR to the document to update the document to include the detailed instructions, thanks!

**Comment by Rafi993** [comment]
Hi @BowieHsu  and @tqchen  I have made those changes and created pull request

**Comment by bdore** [comment]
Successfull install here on win 10 x64.

1. Latest TDM-GCC didn't work. Received error message with TDM-GCC.Got it working after following this [https://github.com/dmlc/xgboost/issues/1059#issuecomment-203312001](url).

2. `using name space std` command in git bash was not found, didn't make any difference for me.

3  Had to edit my windows environment variable in order to install to my python environment. Otherwise it would just install to root.

Thanks for the help! It's working now!

**Comment by AndreMikulec** [comment]
The link above is broken.
csdn blog http://blog.csdn.net/bon_mot/article/details/51742869#0-tsina-1-68989-397232819ff9a47a7b7e80a40613cfe1

This link seems to work.
(The written language is in non-English, so human browsers may want to browse with Google Chrome and click 'Translate' )
http://blog.csdn.net/bon_mot/article/details/51742869

But "bdore commented(above): Successfull install here on win 10 x64; Latest TDM-GCC didn't work; used instead to make it compile; x86_64-4.9.1-release-posix-seh-rt_v3-rev2"

**Comment by mukesh-ranjan** [comment]
Hello Experts,

Hope you are doing well....
Need a help in upgrading xgboost 0.4a to xgboost0.47 (as in my current version xgboost.cv doesnt have elapsed time and some important parameter) on windows 10 64 bit python 2.7. I tried to update but i loop back to same version. Please let me know how to upgrade

**Comment by anuragupadhyaya** [comment]
It worked in one go... cheers and thanks alot :)

**Comment by jhli973** [comment]
make lib/librabit_empty.a -j4
bash: make: command not found

**Comment by Rajiv-B** [comment]
@jhli973 Probably you skipped the installation of TDM-GCC or forgot to rename the "mingw32-make.exe" to "make.exe". Check your environment variables to make sure that the path for TDM-GCC/bin is added in there.

**Comment by dshefman1** [comment]
@bdore What Windows environment variable did you edit. Mine is also trying to install to the root.

**Comment by bdore** [comment]
I don't quite remember but I think it was python's environment var. PYTHONPATH is that it?

**Comment by csaluja** [comment]
You have to add C:\TDM-GCC-64\bin (respective location for your TDM-GCC installation) to your environment PATH variable.

**Comment by csaluja** [comment]
You have to add TDM-GCC/bin to PATH variable
