### ISSUE TITLE
[jvm-packages] RabitTracker socket.error: [Errno 48] Address already in use

### ISSUE THREAD

**Issue by universewill** [dmlc/xgboost#1317]
I encounter this error when run mvn command under jvm-packages folder.
I notice that this problem is the same as #940 
Then i check the file dmlc-core/tracker/dmlc_tracker/tracker.py.
But i did not know how to modify the uri and port correctly.

**Comment by universewill** [comment]
I change the port 9091 to 8091, then the mvn command ended success.
Is this modify right?

**Comment by CodingCat** [comment]
as it says, Address already in use, that means the desired port (9091) has been occupied by another process, in usual, 9091 is occupied by some unsuccessful running instance of rabit, you just need to kill that instance manually
