### ISSUE TITLE
dmlc-core/include/dmlc/threadediter.h:299:27: internal compiler error: Segmentation fault

### ISSUE THREAD

**Issue by lihuibng** [dmlc/xgboost#1319]
g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/data/simple_csr_source.cc -o build/data/simple_csr_source.o
In file included from src/data/./sparse_page_source.h:12:0,
                 from src/data/data.cc:16:
dmlc-core/include/dmlc/threadediter.h: In lambda function:
dmlc-core/include/dmlc/threadediter.h:299:27: internal compiler error: Segmentation fault
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.7/README.Bugs> for instructions.
g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/data/simple_dmatrix.o src/data/simple_dmatrix.cc >build/data/simple_dmatrix.d
g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/data/simple_dmatrix.cc -o build/data/simple_dmatrix.o
Preprocessed source stored into /tmp/ccvIk5hG.out file, please attach this to your bugreport.
make: *** [build/data/data.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by khotilov** [comment]
Please use different gcc version #1162

**Comment by PseudoProgrammer** [comment]
i think the introduce to installing has some problem about gcc.please point out clearly which gcc would work!!!I have tried 4.4.6，4.6.3，4.7.3 with many different problem in installing, while introduction is written with "g++-4.6 or higher".Eventually, gcc 4.8.3 work.
