### ISSUE TITLE
Error creating xgb.DMatrix from sparse model matrix with all zeroes as last row (numerical columns only)

### ISSUE THREAD

**Issue by aichao** [dmlc/xgboost#1320]
Hi,

I'm running the R xgboost binary package version 0.4-3, which was built under R 3.1.3, on an OS X host. I'm experiencing an issue with constructing a xgb.DMatrix from a sparse model matrix that is created from data containing only numerical variables for which the last row(s) are all zeroes. Of course, I first triggered this issue not by calling xgb.DMatrix with the sparse model matrix but by calling xgboost (or xgb.train or xgb.cv) with the sparse model matrix. It should be noted that the issue does not occur if the equivalent dense model matrix is used. The console error message is:

```
Error in xgb.setinfo(dmat, names(p), p[[1]]) : 
  The length of labels must equal to the number of rows in the input data
```
However, if one were to examine the nrow of the input sparse model matrix and the length of the input labels, they will be the same.

I'ved searched your issues (both open and closed) and have not found anything similar reported previously. There is, however, a more or less recent (last 3 months) stackoverflow question:

[http://stackoverflow.com/questions/35852923/error-in-xgb-setinfodmat-namesp-p1-the-length-of-labels-must-equal-t](url)

The self-answer provided there hints at the issue, but does not fully investigate it.

The following simplified example, which is derived from one of your examples, also triggers the issue:

```
require("xgboost")
require("Matrix")
require("data.table")
require("vcd")

data(Arthritis)
df <- data.table(Arthritis, keep.rownames = F)
output_vector <- df[,Improved] == "Marked"

# setting last row to zero for all numerical columns
df[nrow(df),"Age"] <- 0

# using only numerical columns (i.e., only Age) and excluding intercept
mm <- model.matrix(Improved~Age-1, data=df)
# constructing from a dense model matrix does not result in an error
print("constructing with dense model matrix succeeds")
dtrain <- xgb.DMatrix(mm, label=output_vector, missing=NA)
# this is equivalent to smm <- sparse.model.matrix(Improved~Age-1, data=df)
smm <- Matrix(mm, sparse=TRUE)
# constructing from an equivalent sparse matrix does result in the error
print("constructing with sparse model matrix fails")
dtrain <- xgb.DMatrix(smm, label=output_vector)
```
Please note the following:

1. In the simplified example, the only numerical column is "Age" so only that column is used in the model matrix. However, the issue can be replicated with any number of numerical columns for which the last row contains all zeroes. This should not be construed as invalid data for regression as zero may very well be legitimate numerical data (may not indicate missing data), all numerical columns may very well have this value at once, and (by a minor miracle in, for instance, k-fold cv) that sample may very well be the last row in the training or test data. Of course, with categorical variables (or mixed categorical and numerical) then this case will never happen (given one hot encoding), which may explain why no one has run into this issue previously.
2. In your documentation of the function xgb.DMatrix, the input argument missing, which is only used when the input data is a dense matrix, has a default value of 0. As a side issue, I feel that this default value should instead be something like NA since 0 is a legitimate value for data (both categorical and numerical). In any case, in the simplified example above, the call using the dense model matrix explicitly sets this input to NA so that the value 0 is not construed as missing data.
3. The issue is not triggered if there are row(s) of all zeros that are not the last row(s). Therefore, a current workaround is to check the last row(s) for all zeros and then rotate (swap) them to the first row(s) if needed. Of course, another workaround is to construct with the dense model matrix. Still another workaround is not to exclude the intercept in the formula.

Not to be the one to debug your code, but I believe there is a potential bug within the function XGDMatrixCreateFromCSC_R that creates the XGDMatrix from the input sparse matrix. This code most probably truncates the end rows of the input if they are "empty" instead of preserving the nrow of the input sparse matrix.

Hope this helps. BTW, I really like this package.

**Comment by khotilov** [comment]
Yes, that is a similar issue as in #1223 
As I've mentioned in there, sparse matrix creation methods would need additional arguments to be able to handle situations like that.

**Comment by tqchen** [comment]
https://github.com/dmlc/xgboost/issues/1583
