### ISSUE TITLE
Low CPU usage while training

### ISSUE THREAD

**Issue by pradipto** [dmlc/xgboost#1337]
Hello,

I was running xgboost training on a 128-core server on a fairly large dataset (in GBs). Loading of the file and training is running fine but the CPUs are not being utilized fully. I have attached a snapshot below.

Would it be possible to know what might be happening and how xgboost is handling parallelization while training and prediction? Pointers to specific blocks/functions in source code is appreciated as well.

Thank you very much.
Pradipto

![xgboost-128-core](https://cloud.githubusercontent.com/assets/2465687/16667352/0e92e53e-445a-11e6-850b-2c6d2075efdd.png)

**Comment by ronroc** [comment]
I have also been training a ~12GB dataset on a 36 core server for past ~60 hrs and it's still running , I have also observed similar CPUs not being utilised fully. Any help or pointers would be great . Also I could not find any benchmarks for xgboost on large datasets, any references you might have on this
