### ISSUE TITLE
On "make" -> g++ error. How to install g++?

### ISSUE THREAD

**Issue by moxpower** [dmlc/xgboost#1339]
After following the installation, I get the error: "**/usr/bin/sh: g++: command not found**" after I type $make in Git Bash. This is because the g++.exe is missing in the respective bin folder. Do you know how I could get g++ into this folder?

I have another mingw64 "installation"(?) for R build tools, where g++ is configured. Just copying the file doesn't do the trick.

Thanks a lot!

**Comment by thirdwing** [comment]
Adding that into your `PATH` environment variable should be enough.
