### ISSUE TITLE
list(evals) error when using multi:softmax objective

### ISSUE THREAD

**Issue by linflyer** [dmlc/xgboost#1343]
Hi there,

I am just trying xgboost for my data set. My training file can be successfully loaded, but when I train the model I met the following error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../xgboost/python-package/xgboost/training.py", line 205, in train
    xgb_model=xgb_model, callbacks=callbacks)
  File ".../xgboost/python-package/xgboost/training.py", line 21, in _train_internal
    evals = list(evals)
TypeError: 'int' object is not iterable

My code is attached:
    data_file = os.path.join(working_dir, 'training-data.liblinear')
    dtrain = xgb.DMatrix(data_file)

```
param = {'max_depth':2, 'eta':1, 'silent':1, 'objective':'multi:softmax'}
num_round = 2
num_class= 10
bst = xgb.train(param, dtrain, num_round, num_class)
```

**Comment by rushter** [comment]
You should put `num_class` in `param` dict.

**Comment by linflyer** [comment]
Thank you very much! Now I have met the following error:

xgboost.core.XGBoostError: [17:19:30] src/objective/multiclass_obj.cc:75:
Check failed: label_error >= 0 && label_error < nclass
SoftmaxMultiClassObj: label must be in [0, num_class), num_class=10 but
found 10 in label.


I know the reason is that I have 10 classes labeled from 1 to 10, while the
program is expecting 0 to 9. How can I modify the DMatrix's label column
for that purpose? Many thanks!

Best,

linflyer

**Comment by Lah123** [comment]
What are your labels of your classes? It needs to start with 0 and then add up with steps of 1. I had the same problem and this solved it.

**Comment by sghanukota** [comment]
i am getting the same error, need help to resolve

**Comment by Trembles** [comment]
This error makes little sense, 

`LightGBMError: b'Label must be in [0, 4), but found 4 in label'`

My class labels are [1,2,3,4]
```
params = {   'boosting_type': 'gbdt',
    'objective': 'multiclass',
    'metric': 'multi_logloss',
    'num_class':4,
    'learning_rate': 0.1,
    'feature_fraction': 0.9,
    'bagging_fraction': 0.8,
    'bagging_freq': 5,
    'verbose': 10}

gbm = lgb.train(params,
                lgb_train,
                num_boost_round=2000,
                valid_sets=lgb_eval,
                early_stopping_rounds=50)
```

What is the correct setting for 'num_class' when using lgb.train in python?
Docs say,

> num_class, default=1, type=int, alias=num_classes
> only used in multi-class classification

**Comment by devendai** [comment]
has anybody solve it, yet? I am still getting the error like below.

Here is my code

```
dtrain = xgb.DMatrix(X_train, label=y_train)

nc = len(np.unique(y_train))

param = {'objective':'multi:softmax',
		'num_class': nc,
		'max_depth': 8, 
		'eta' :0.3,
		'eval_metric' : 'merror',    # evaluation metric
		'tree_method' : 'exact',
		'silent': 0, 
		'nthread': -1}
		
model = xgb.train(param,dtrain, 20)
```
Below is the error:

[13:04:41] d:\build\xgboost\xgboost-git\dmlc-core\include\dmlc\./logging.h:300: [13:0
4:41] D:\Build\xgboost\xgboost-git\src\objective\multiclass_obj.cc:75: Check failed:
label_error >= 0 && label_error < nclass SoftmaxMultiClassObj: label must be in [0, n
um_class), num_class=6 but found 37 in label.

As the error says, num_class is indeed 6. I found few more suggestions like use 'num_class = nc -1' or 'num_class = nc+1' but always getting the similar error. Is this a bug related to MultiClassObj? 

Could somebody suggest a solution? Thanks in advance.

**Comment by devendai** [comment]
I have an update. My dataset has 6 classes but the class values were not sequential. The values were 0, 1, 2, 23, 24, and 37 and when I was passing 6 as num_class it was failing. Now, I changed the values to 0, 1, 2, 3, 4, 5  and it is working.

**Comment by xavierjl70** [comment]
Error in xgb.iter.update(bst$handle, dtrain, iteration - 1, obj) : 
  [11:15:21] amalgamation/../src/objective/multiclass_obj.cc:75: Check failed: label_error >= 0 && label_error < nclass SoftmaxMultiClassObj: label must be in [0, num_class), num_class=2 but found 2 in label.
My NC =2. Number of class is my a binary.  I am still getting a error.
However, when I was creating my Matrix using " One-Hot  Encoding for factor variables.
I couldn't omit my dependent variable "COMPLIANT"
trainm <- sparse.model.matrix(COMPLIANT~ ., subset(training, select = - c(MEMBERKEY,SEX, TIN_DESC)))
my error is above.

**Comment by xavierjl70** [comment]
Thank you so much. It works

**Comment by xavierjl70** [comment]
Error in scale.default(bcsmdcare, center = min, scale = max - min) : 
  length of 'center' must equal the number of columns of 'x'
I am getting this error when i trying to scale my data to use Neural Network.
Does somebody  have similar issue?
Thank you

**Comment by xavierjl70** [comment]
I am running an auto.arima . however, I have to group by and loop.
by_StateCode <- group_by(p4pcrtcalsumm, StateCode, MeasureId)
fit1 = do(by_StateCode,tidy(auto.arima(RATE, seasonal= T, xreg=xi), data = p4pcrtcalsumm.
However, i am not able to predict or forecast. I am getting an error
frcst1 <- forecast(fits, h=10) or

mydata.pred1 <- do(by_StateCode,tidy(predict(fit1, n.ahead=10, data = p4pcrtcalsumm)))

error:
Error in ets(object, lambda = lambda, biasadj = biasadj, allow.multiplicative.trend = allow.multiplicative.trend, :
y should be a univariate time series

**Comment by rishabhojha98** [comment]
Error in xgb.iter.update(bst$handle, dtrain, iteration - 1, obj) : 
  [00:29:36] amalgamation/../src/objective/multiclass_obj.cc:78: Check failed: label_error >= 0 && label_error < nclass SoftmaxMultiClassObj: label must be in [0, num_class), num_class=2 but found 2 in label.

**Comment by rishabhojha98** [comment]
i tried passing num_class=3
