### ISSUE TITLE
how to compile xgboost to make it not rely on .so files when running?

### ISSUE THREAD

**Issue by zhixiangli** [dmlc/xgboost#1346]
I compile xgboost on my dev machine, and run it on hadoop mapred.

error occurred because of path not exist on hadoop.

for example

```
libpthread.so.0 => /lib64/tls/libpthread.so.0 (0x0000003f0b900000)
libc.so.6 => /lib64/tls/libc.so.6 (0x0000003f0b000000)
/lib64/ld-linux-x86-64.so.2 (0x0000003f0ae00000)
```

I am unfamiliar with C++, and I don't konw how to solve it..

thanks in advance~

**Comment by tqchen** [comment]
The most feasible solution is to ship the dependent libraries into the dev machine to local directories.
