### ISSUE TITLE
custom objective to predict parameters (like in density modelling)

### ISSUE THREAD

**Issue by cottrell** [dmlc/xgboost#1350]
Is it possible to use a custom objective function (for example https://github.com/tqchen/xgboost/blob/master/demo/guide-python/custom_objective.py)  to predict multiple parameters that are inputs into a density model? I have not yet found any example like this with xgboost. I see a a few dimensionality issues with whatever I tried but am wondering if there is something deeper that is stopping such an approach. I am assuming that the cost function (and its gradient stats) are still separable across instances. I think the custom objective and scorer would need to take the parameter inputs as predictions (possibly several parameters per instance). I tried spoofing the dimensionality mismatches with a multi-objective (2d) label matrix (Y) but that seems to hit some initial setup checks.

So to be clear I mean dealing with something like

```
def logobj(preds, dtrain):
    labels = dtrain.get_label()
    ...
```

where labels.shape = (m,) and preds.shape = (m, n) n>1. 

Happy to post this on elsewhere if Issues is not the place.

**Comment by pommedeterresautee** [comment]
Old question, no answer. Closing.
