### ISSUE TITLE
URL at _windows_folder_  404 This is not the web page you are looking for

### ISSUE THREAD

**Issue by AndreMikulec** [dmlc/xgboost#1353]
The python-package README.rst ( https://github.com/dmlc/xgboost/blob/master/python-package/README.rst ) says

```
For windows users, please use the Visual Studio project file under windows folder
```

When I click the URL at _windows_folder_

https://github.com/dmlc/xgboost/tree/master/windows

I get the following error.

```
404 This is not the web page you are looking for
```

**Comment by pommedeterresautee** [comment]
Old question, no answer. Closing.
