### ISSUE TITLE
xgb.XGBClassifier and xgb.train give very different results

### ISSUE THREAD

**Issue by JoshuaC3** [dmlc/xgboost#1354]
I have found that xgb.XGBClassifier fit and predict, and xgb.train + xgb.predict are giving hugely different answers.

I started off by using xgb.train + predict to get a quick look at how my data set trains. Things went well with a auc of 0.8 when comparing the prediction of the training y to the predicted yhat.

I then used the xgb.XGBClassifier, entered all of the same parameters and got back a score of 0.51 for auc on the y vs yhat. I then check all of the docs I can find on the sklearn parameters and the xgb parameters and double check and retrain the sklearn. Still it gives back a bad score of 0.51.

What is going on here? I understand that this is very likely a user error, but I exhausted all scenarios that I can think of. What information can I provide to help diagnose this issue?

**Comment by lesshaste** [comment]
Can you provide a minimal code example?

**Comment by JoshuaC3** [comment]
I can give code, however I think I know what the problem was. `xgb.train(objective='binary:logistic'),predict()` is equivalent to `xgb.XGBClassifier().predict_probab()`. Is this correct? I was using  `xgb.XGBClassifier().predict()` for my comparison of the two models and so my auc score was very different. I have changed to using .predict_probab and seems to be the same auc now. I think this issue could be marked as resolved.

**Comment by gaw89** [comment]
@JoshuaC3, you are correct that XGBClassifier().predict_proba() is the same as the Booster.predict() when using 'binary:logistic' objective.  However, I believe that XGBClassifier().predict_proba() will give you an array of 2*n_samples in a binary problem (with the first column in the array being the probability of 0 class and the second being the probability of 1 class).  Booster.predict() will give you a 1*n_samples vector where it is just the probability of the 1 class.  

You should be able to close this issue if you comment below.
