### ISSUE TITLE
[jvm-packages]Unclear from documentation how to train with categorical features using xgboost4j-spark

### ISSUE THREAD

**Issue by quartox** [dmlc/xgboost#1355]
I see that the xgboost4j-spark model is trained on an RDD[LabeledPoint], but it is unclear how to incorporate categorical features using LabeledPoint. Does the user create one-hot encoding for these features or is there another method?

**Comment by CodingCat** [comment]
you have to use unique value to represent each category in LabeledPoint.value

**Comment by quartox** [comment]
I do not recognize LabeledPoint.value from the [documenation](https://spark.apache.org/docs/1.6.2/api/scala/index.html#org.apache.spark.mllib.regression.LabeledPoint). Is this different from how I would create continuous values in the LabeledPoint?

If you have (or would be willing to write) example code showing how to create a LabeledPoint with both a continuous and categorical feature, that would really help me.

**Comment by quartox** [comment]
Reading this again I am wondering if you mean that we create a new feature column for each value of a categorical. Thus, if we have two features (one continuous and one categorical) we could use the following transform:
```
Continuous, Categorical -> Continuous, CategoryA, CategoryB
1, A -> 1, 1, 0
0, B -> 0, 0, 1
```
Is this correct?

**Comment by CodingCat** [comment]
see the discussions here https://github.com/dmlc/xgboost/issues/95

basicly , LabeledPoint is just a proxy to fetch the data from JVM to XGBoost \


and sorry for the typo, it is LabeledPoint.features
