### ISSUE TITLE
Makefile:97: recipe for target 'build/c_api/c_api.o' failed

### ISSUE THREAD

**Issue by eroszip** [dmlc/xgboost#1357]
**env**:win10(64bit) + mingw-w64
**errLog**:g++ -m64 -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -MM -MT build/c_api/c_api_error.o src/c_api/c_api_error.cc >build/c_api/c_api_error.d
g++ -m64 -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -MM -MT build/c_api/c_api.o src/c_api/c_api.cc >build/c_api/c_api.d
g++ -m64 -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -MM -MT build/data/simple_dmatrix.o src/data/simple_dmatrix.cc >build/data/simple_dmatrix.d
g++ -m64 -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -MM -MT build/data/sparse_page_raw_format.o src/data/sparse_page_raw_format.cc >build/data/sparse_page_raw_format.d
g++ -m64 -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -c src/c_api/c_api_error.cc -o build/c_api/c_api_error.o
g++ -m64 -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -c src/c_api/c_api.cc -o build/c_api/c_api.o
g++ -m64 -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -c src/data/simple_dmatrix.cc -o build/data/simple_dmatrix.o
g++ -m64 -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -c src/data/sparse_page_raw_format.cc -o build/data/sparse_page_raw_format.o
In file included from C:/Program Files/mingw-w64/x86_64-6.1.0-posix-seh-rt_v5-rev0/mingw64/x86_64-w64-mingw32/include/locale.h:12:0,
                 from C:/Program Files/mingw-w64/x86_64-6.1.0-posix-seh-rt_v5-rev0/mingw64/lib/gcc/x86_64-w64-mingw32/6.1.0/include/c++/clocale:42,
                 from C:/Program Files/mingw-w64/x86_64-6.1.0-posix-seh-rt_v5-rev0/mingw64/lib/gcc/x86_64-w64-mingw32/6.1.0/include/c++/x86_64-w64-mingw32/bits/c++locale.h:41,
                 from C:/Program Files/mingw-w64/x86_64-6.1.0-posix-seh-rt_v5-rev0/mingw64/lib/gcc/x86_64-w64-mingw32/6.1.0/include/c++/bits/localefwd.h:40,
                 from C:/Program Files/mingw-w64/x86_64-6.1.0-posix-seh-rt_v5-rev0/mingw64/lib/gcc/x86_64-w64-mingw32/6.1.0/include/c++/string:43,
                 from dmlc-core/include/dmlc/base.h:154,
                 from src/c_api/./c_api_error.h:9,
                 from src/c_api/c_api_error.cc:6:
C:/Program Files/mingw-w64/x86_64-6.1.0-posix-seh-rt_v5-rev0/mingw64/x86_64-w64-mingw32/include/stdio.h:462:83: error: 'FILE\* std::fopen(const char_, const char_)' should have been declared inside 'std'
   FILE _fopen64(const char \* **restrict** filename,const char \* **restrict**  mode);
                                                                                   ^
C:/Program Files/mingw-w64/x86_64-6.1.0-posix-seh-rt_v5-rev0/mingw64/x86_64-w64-mingw32/include/stdio.h:462:83: error: 'FILE_ std::fopen(const char_, const char_)' conflicts with a previous declaration
C:/Program Files/mingw-w64/x86_64-6.1.0-posix-seh-rt_v5-rev0/mingw64/x86_64-w64-mingw32/include/stdio.h:461:17: note: previous declaration 'FILE\* fopen(const char_, const char_)'
   FILE _**cdecl fopen(const char \* __restrict** _Filename,const char \* __restrict__ _Mode) __MINGW_ATTRIB_DEPRECATED_SEC_WARN;
                 ^~~~~
In file included from C:/Program Files/mingw-w64/x86_64-6.1.0-posix-seh-rt_v5-rev0/mingw64/x86_64-w64-mingw32/include/locale.h:12:0,
                 from C:/Program Files/mingw-w64/x86_64-6.1.0-posix-seh-rt_v5-rev0/mingw64/lib/gcc/x86_64-w64-mingw32/6.1.0/include/c++/clocale:42,
                 from C:/Program Files/mingw-w64/x86_64-6.1.0-posix-seh-rt_v5-rev0/mingw64/lib/gcc/x86_64-w64-mingw32/6.1.0/include/c++/x86_64-w64-mingw32/bits/c++locale.h:41,
                 from C:/Program Files/mingw-w64/x86_64-6.1.0-posix-seh-rt_v5-rev0/mingw64/lib/gcc/x86_64-w64-mingw32/6.1.0/include/c++/bits/localefwd.h:40,
                 from C:/Program Files/mingw-w64/x86_64-6.1.0-posix-seh-rt_v5-rev0/mingw64/lib/gcc/x86_64-w64-mingw32/6.1.0/include/c++/string:43,
                 from dmlc-core/include/dmlc/base.h:154,
                 from include/xgboost/data.h:10,
                 from src/c_api/c_api.cc:3:
C:/Program Files/mingw-w64/x86_64-6.1.0-posix-seh-rt_v5-rev0/mingw64/x86_64-w64-mingw32/include/stdio.h:462:83: error: 'FILE_ std::fopen(const char_, const char_)' should have been declared inside 'std'
   FILE _fopen64(const char \* **restrict** filename,const char \* **restrict**  mode);
                                                                                   ^
C:/Program Files/mingw-w64/x86_64-6.1.0-posix-seh-rt_v5-rev0/mingw64/x86_64-w64-mingw32/include/stdio.h:462:83: error: 'FILE_ std::fopen(const char_, const char_)' conflicts with a previous declaration
C:/Program Files/mingw-w64/x86_64-6.1.0-posix-seh-rt_v5-rev0/mingw64/x86_64-w64-mingw32/include/stdio.h:461:17: note: previous declaration 'FILE\* fopen(const char_, const char_)'
   FILE _**cdecl fopen(const char \* __restrict** _Filename,const char \* __restrict__ _Mode) __MINGW_ATTRIB_DEPRECATED_SEC_WARN;
                 ^~~~~
In file included from C:/Program Files/mingw-w64/x86_64-6.1.0-posix-seh-rt_v5-rev0/mingw64/x86_64-w64-mingw32/include/locale.h:12:0,
                 from C:/Program Files/mingw-w64/x86_64-6.1.0-posix-seh-rt_v5-rev0/mingw64/lib/gcc/x86_64-w64-mingw32/6.1.0/include/c++/clocale:42,
                 from C:/Program Files/mingw-w64/x86_64-6.1.0-posix-seh-rt_v5-rev0/mingw64/lib/gcc/x86_64-w64-mingw32/6.1.0/include/c++/x86_64-w64-mingw32/bits/c++locale.h:41,
                 from C:/Program Files/mingw-w64/x86_64-6.1.0-posix-seh-rt_v5-rev0/mingw64/lib/gcc/x86_64-w64-mingw32/6.1.0/include/c++/bits/localefwd.h:40,
                 from C:/Program Files/mingw-w64/x86_64-6.1.0-posix-seh-rt_v5-rev0/mingw64/lib/gcc/x86_64-w64-mingw32/6.1.0/include/c++/string:43,
                 from dmlc-core/include/dmlc/base.h:154,
                 from include/xgboost/data.h:10,
                 from src/data/simple_dmatrix.cc:7:
C:/Program Files/mingw-w64/x86_64-6.1.0-posix-seh-rt_v5-rev0/mingw64/x86_64-w64-mingw32/include/stdio.h:462:83: error: 'FILE_ std::fopen(const char_, const char_)' should have been declared inside 'std'
   FILE _fopen64(const char \* **restrict** filename,const char \* **restrict**  mode);
                                                                                   ^
C:/Program Files/mingw-w64/x86_64-6.1.0-posix-seh-rt_v5-rev0/mingw64/x86_64-w64-mingw32/include/stdio.h:462:83: error: 'FILE_ std::fopen(const char_, const char_)' conflicts with a previous declaration
C:/Program Files/mingw-w64/x86_64-6.1.0-posix-seh-rt_v5-rev0/mingw64/x86_64-w64-mingw32/include/stdio.h:461:17: note: previous declaration 'FILE\* fopen(const char_, const char_)'
   FILE _**cdecl fopen(const char \* __restrict** _Filename,const char \* __restrict__ _Mode) __MINGW_ATTRIB_DEPRECATED_SEC_WARN;
                 ^~~~~
In file included from C:/Program Files/mingw-w64/x86_64-6.1.0-posix-seh-rt_v5-rev0/mingw64/x86_64-w64-mingw32/include/locale.h:12:0,
                 from C:/Program Files/mingw-w64/x86_64-6.1.0-posix-seh-rt_v5-rev0/mingw64/lib/gcc/x86_64-w64-mingw32/6.1.0/include/c++/clocale:42,
                 from C:/Program Files/mingw-w64/x86_64-6.1.0-posix-seh-rt_v5-rev0/mingw64/lib/gcc/x86_64-w64-mingw32/6.1.0/include/c++/x86_64-w64-mingw32/bits/c++locale.h:41,
                 from C:/Program Files/mingw-w64/x86_64-6.1.0-posix-seh-rt_v5-rev0/mingw64/lib/gcc/x86_64-w64-mingw32/6.1.0/include/c++/bits/localefwd.h:40,
                 from C:/Program Files/mingw-w64/x86_64-6.1.0-posix-seh-rt_v5-rev0/mingw64/lib/gcc/x86_64-w64-mingw32/6.1.0/include/c++/string:43,
                 from dmlc-core/include/dmlc/base.h:154,
                 from include/xgboost/data.h:10,
                 from src/data/sparse_page_raw_format.cc:6:
C:/Program Files/mingw-w64/x86_64-6.1.0-posix-seh-rt_v5-rev0/mingw64/x86_64-w64-mingw32/include/stdio.h:462:83: error: 'FILE_ std::fopen(const char_, const char_)' should have been declared inside 'std'
   FILE _fopen64(const char \* **restrict** filename,const char \* **restrict**  mode);
                                                                                   ^
C:/Program Files/mingw-w64/x86_64-6.1.0-posix-seh-rt_v5-rev0/mingw64/x86_64-w64-mingw32/include/stdio.h:462:83: error: 'FILE_ std::fopen(const char_, const char_)' conflicts with a previous declaration
C:/Program Files/mingw-w64/x86_64-6.1.0-posix-seh-rt_v5-rev0/mingw64/x86_64-w64-mingw32/include/stdio.h:461:17: note: previous declaration 'FILE\* fopen(const char_, const char_)'
   FILE _**cdecl fopen(const char \* __restrict** _Filename,const char \* __restrict__ _Mode) __MINGW_ATTRIB_DEPRECATED_SEC_WARN;
                 ^~~~~
Makefile:97: recipe for target 'build/c_api/c_api_error.o' failed
make: *_\* [build/c_api/c_api_error.o] Error 1
make: **\* Waiting for unfinished jobs....
Makefile:97: recipe for target 'build/data/sparse_page_raw_format.o' failed
make: **\* [build/data/sparse_page_raw_format.o] Error 1
Makefile:97: recipe for target 'build/data/simple_dmatrix.o' failed
make: **\* [build/data/simple_dmatrix.o] Error 1
Makefile:97: recipe for target 'build/c_api/c_api.o' failed
make: **\* [build/c_api/c_api.o] Error 1

**Comment by AbhilashAwasthi01** [comment]
I am facing the same error. Did you find the solution ?

**Comment by AbhilashAwasthi01** [comment]
Okay now it is installed. Refer to this [tutorial] (https://dnc1994.com/2016/03/installing-xgboost-on-windows/) for installation but after checking out from git the XGBOOST repository. Do          
`cd xgboost`      
`git checkout 9a48a40` 

And then follow all the steps from the above tutorial.

**Comment by eroszip** [comment]
I have successfully solve the problem with your advice,thank you for your help。

At 2016-07-17 01:52:45, "Abhilash Awasthi" <notifications@github.com> wrote:


Okay now it is installed. Refer to this tutorial for installation but after checking out from git the XGBOOST repository. Do

cd xgboost

git checkout 9a48a40

And then follow all the steps from the above tutorial.
