### ISSUE TITLE
How to out probability in interval [0,1] of binary classificaion instead of 0 and 1.

### ISSUE THREAD

**Issue by yuan296103** [dmlc/xgboost#1359]
I wanna to predict the probability of binary classification, but the predict fucntion only gives me the 0 and 1 value. Then I tried predict_proba and it didn't work. Can somebody help to fix this issue?

gbm = xgb.XGBClassifier(max_depth=3, n_estimators=300, learning_rate=0.05, objective='binary:logistic').fit(train_X, train_y)
predictions = gbm.predict(test_X)

**Comment by abishekk92** [comment]
The XGBClassifier Object has a method `predict_proba` as defined in https://github.com/dmlc/xgboost/blob/master/python-package/xgboost/sklearn.py#L473.

**Comment by suntzu86** [comment]
``objective='reg:logistic'``, see "objective" under https://github.com/dmlc/xgboost/blob/master/doc/parameter.md#learning-task-parameters should work?

**Comment by junzis** [comment]
@yuan296103, I also encounter this problem while using the sklearn api wrapper. You should use xgb.XGBRegressor() instead. parameters can be the same as your current ones.

**Comment by geoHeil** [comment]
Same problem here http://datascience.stackexchange.com/questions/14527/xgboost-predict-probabilities did you stick with the regression objective?
