### ISSUE TITLE
[jvm-packages] xgboost4j  search: successful steps for mvn package?

### ISSUE THREAD

**Issue by colinsongf** [dmlc/xgboost#1367]
hello
i have problems for complie xgboost4j using mvn package, because of my wrong steps of maven setting.xml
would you like give me some advice or better offer me your mvn package successful steps
thank you in advance
best wishes

**Comment by CodingCat** [comment]
there is nothing to do with setting.xml, please tell what the problem is in your process.

**Comment by colinsongf** [comment]
i just want to  know how to build xgboost4j step by step , and a tutorial file is more better

**Comment by CodingCat** [comment]
you only need to run `mvn package` or `mvn package -DskipTests=true` (if you are 100% sure that your local environment is well configured)
