### ISSUE TITLE
Newbie question: xgboost very slow and gives poor result

### ISSUE THREAD

**Issue by lesshaste** [dmlc/xgboost#1375]
I am completely new to xgboost so thank you very much for any help in advance.

I have this simple script.

```
from sklearn.ensemble import ExtraTreesClassifier
from sklearn import cross_validation
import xgboost as xgb
import autosklearn.classification
import sklearn.datasets

digits = sklearn.datasets.load_digits()
X = digits.data
y = digits.target

# train a with ensemble

clf = ExtraTreesClassifier(n_estimators=50, max_depth=None, min_samples_split=1, random_state=0, verbose=True, n_jobs=-1)
print cross_validation.cross_val_score(clf, X, y, cv=5)

gbm = xgb.XGBClassifier(silent = True)
print cross_validation.cross_val_score(gbm, X, y, cv=5)
```

From this I get as the cross-validation scores

[ 0.95054945 0.9281768 0.96100279 0.98319328 0.93802817] (ExtraTreesClassifier)

[ 0.93131868 0.87569061 0.95264624 0.94677871 0.88169014] (xgboost)

That is xgboost does quite a lot worse than ExtraTreesClassifier which seems surprising.

What should I be doing to tune xgboost or is there some other problem with my approach?

When I try the same thing (see below for precise code) with the MNIST digits data set from kaggle I get

[ 0.96216538 0.96465548 0.96428146 0.96558295 0.9670081 ]

from ExtraTreesClassifier very quickly but xgboost took a *really* long time and eventually gave

[ 0.9323022 0.93157206 0.92796762 0.93271406 0.93854216]

which is worse again.

What am I doing wrong? Why is xgboost so slow and why is the result worse?

```
import pandas as pd
from sklearn.ensemble import ExtraTreesClassifier
from sklearn import cross_validation
import xgboost as xgb

# import data
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

# drop and get labels
labels = train.label.values
train = train.drop('label', axis=1)

# train a with ensemble
clf = ExtraTreesClassifier(n_estimators=50, max_depth=None, min_samples_split=1, random_state=0, verbose=False, n_jobs=-1)
#Print CV scores for ExtraTreesClassifier
print cross_validation.cross_val_score(clf, train, labels, cv=5)

gbm = xgb.XGBClassifier(nthread=4, silent=True)
#Print CV scores for xgboost
print cross_validation.cross_val_score(gbm, train, labels, cv=5)
```

**Comment by hetong007** [comment]
Parameter tuning is very important for a good performance. Visit our documentation for the available parameters: http://xgboost.readthedocs.io/en/latest//parameter.html
