### ISSUE TITLE
[xgboost4j-spark] scope of spark-mllib dependency should be provided

### ISSUE THREAD

**Issue by Earthson** [dmlc/xgboost#1377]
RT

**Comment by Earthson** [comment]
@CodingCat default scope will make sbt download all hadoop and spark dependencies.

**Comment by CodingCat** [comment]
ah, thx, would you send a PR to fix it?

**Comment by Earthson** [comment]
@CodingCat Ok, I'll prepare a PR. And I have a question: should I add spark dependency to xgboost4j-example when the scope is provided?

**Comment by CodingCat** [comment]
I think that's the only choice we have if we want to successfully build it?

**Comment by Earthson** [comment]
@CodingCat I don't know whether it is the only choice.

**Comment by CodingCat** [comment]
right now, xgboost4j-examples takes xgboost-spark as the dependency, 

if you do not use default scope in xgboost-spark, I remember that xgboost-example will not get the requested dependencies so that you have to make it directly depend on spark packages as well  (I might be wrong)

**Comment by Earthson** [comment]
I see:)
