### ISSUE TITLE
[jvm-packages] Building xgboost4j-flink 0.5 FAILURE,  why?

### ISSUE THREAD

**Issue by colinsongf** [dmlc/xgboost#1383]
[INFO] Building xgboost4j-flink 0.5
[INFO] ------------------------------------------------------------------------
Downloading: https://repo.maven.apache.org/maven2/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar
Downloading: https://repo.maven.apache.org/maven2/commons-net/commons-net/3.1/commons-net-3.1.jar
Downloading: https://repo.maven.apache.org/maven2/commons-codec/commons-codec/1.4/commons-codec-1.4.jar
Downloading: https://repo.maven.apache.org/maven2/org/apache/flink/flink-shaded-hadoop2/0.10.2/flink-shaded-hadoop2-0.10.2.jar
Downloading: https://repo.maven.apache.org/maven2/org/apache/flink/flink-core/0.10.2/flink-core-0.10.2.jar
Downloading: https://repo.maven.apache.org/maven2/org/apache/httpcomponents/httpcore/4.2/httpcore-4.2.jar
Downloading: https://repo.maven.apache.org/maven2/org/apache/httpcomponents/httpclient/4.2/httpclient-4.2.jar
Downloading: https://repo.maven.apache.org/maven2/net/java/dev/jets3t/jets3t/0.9.0/jets3t-0.9.0.jar
Downloading: https://repo.maven.apache.org/maven2/commons-el/commons-el/1.0/commons-el-1.0.jar
Downloading: https://repo.maven.apache.org/maven2/com/jamesmurty/utils/java-xmlbuilder/0.4/java-xmlbuilder-0.4.jar
Downloading: https://repo.maven.apache.org/maven2/commons-lang/commons-lang/2.6/commons-lang-2.6.jar
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/jackson/jackson-core-asl/1.8.8/jackson-core-asl-1.8.8.jar
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/jackson/jackson-mapper-asl/1.8.8/jackson-mapper-asl-1.8.8.jar
Downloading: https://repo.maven.apache.org/maven2/com/thoughtworks/paranamer/paranamer/2.3/paranamer-2.3.jar
Downloading: https://repo.maven.apache.org/maven2/org/xerial/snappy/snappy-java/1.0.5/snappy-java-1.0.5.jar
Downloading: https://repo.maven.apache.org/maven2/com/jcraft/jsch/0.1.42/jsch-0.1.42.jar
Downloading: https://repo.maven.apache.org/maven2/org/apache/zookeeper/zookeeper/3.4.6/zookeeper-3.4.6.jar
Downloading: https://repo.maven.apache.org/maven2/io/netty/netty/3.7.0.Final/netty-3.7.0.Final.jar
Downloading: https://repo.maven.apache.org/maven2/commons-daemon/commons-daemon/1.0.13/commons-daemon-1.0.13.jar
Downloading: https://repo.maven.apache.org/maven2/javax/xml/bind/jaxb-api/2.2.2/jaxb-api-2.2.2.jar
Downloading: https://repo.maven.apache.org/maven2/javax/xml/stream/stax-api/1.0-2/stax-api-1.0-2.jar
Downloading: https://repo.maven.apache.org/maven2/javax/activation/activation/1.1/activation-1.1.jar
Downloading: https://repo.maven.apache.org/maven2/org/apache/avro/avro/1.7.6/avro-1.7.6.jar
Downloading: https://repo.maven.apache.org/maven2/com/twitter/chill_2.10/0.5.2/chill_2.10-0.5.2.jar
Downloading: https://repo.maven.apache.org/maven2/com/twitter/chill-java/0.5.2/chill-java-0.5.2.jar
Downloading: https://repo.maven.apache.org/maven2/com/twitter/chill-avro_2.10/0.5.2/chill-avro_2.10-0.5.2.jar
Downloading: https://repo.maven.apache.org/maven2/com/twitter/chill-bijection_2.10/0.5.2/chill-bijection_2.10-0.5.2.jar
Downloading: https://repo.maven.apache.org/maven2/com/twitter/bijection-core_2.10/0.7.2/bijection-core_2.10-0.7.2.jar
Downloading: https://repo.maven.apache.org/maven2/com/twitter/bijection-avro_2.10/0.7.2/bijection-avro_2.10-0.7.2.jar
Downloading: https://repo.maven.apache.org/maven2/de/javakaffee/kryo-serializers/0.27/kryo-serializers-0.27.jar
Downloading: https://repo.maven.apache.org/maven2/joda-time/joda-time/2.5/joda-time-2.5.jar
Downloading: https://repo.maven.apache.org/maven2/org/joda/joda-convert/1.7/joda-convert-1.7.jar
Downloading: https://repo.maven.apache.org/maven2/org/apache/commons/commons-math3/3.5/commons-math3-3.5.jar
Downloading: https://repo.maven.apache.org/maven2/org/slf4j/slf4j-api/1.7.7/slf4j-api-1.7.7.jar
Downloading: https://repo.maven.apache.org/maven2/org/slf4j/slf4j-log4j12/1.7.7/slf4j-log4j12-1.7.7.jar
Downloading: https://repo.maven.apache.org/maven2/org/apache/flink/flink-scala/0.10.2/flink-scala-0.10.2.jar
Downloading: https://repo.maven.apache.org/maven2/org/apache/flink/flink-optimizer/0.10.2/flink-optimizer-0.10.2.jar
Downloading: https://repo.maven.apache.org/maven2/org/scalamacros/quasiquotes_2.10/2.0.1/quasiquotes_2.10-2.0.1.jar
Downloading: https://repo.maven.apache.org/maven2/org/apache/flink/flink-clients/0.10.2/flink-clients-0.10.2.jar
Downloading: https://repo.maven.apache.org/maven2/org/apache/flink/flink-runtime/0.10.2/flink-runtime-0.10.2.jar
Downloading: https://repo.maven.apache.org/maven2/io/netty/netty-all/4.0.27.Final/netty-all-4.0.27.Final.jar
Downloading: https://repo.maven.apache.org/maven2/org/javassist/javassist/3.18.2-GA/javassist-3.18.2-GA.jar
Downloading: https://repo.maven.apache.org/maven2/com/typesafe/akka/akka-actor_2.10/2.3.7/akka-actor_2.10-2.3.7.jar
Downloading: https://repo.maven.apache.org/maven2/com/typesafe/akka/akka-remote_2.10/2.3.7/akka-remote_2.10-2.3.7.jar
Downloading: https://repo.maven.apache.org/maven2/com/typesafe/akka/akka-slf4j_2.10/2.3.7/akka-slf4j_2.10-2.3.7.jar
Downloading: https://repo.maven.apache.org/maven2/org/clapper/grizzled-slf4j_2.10/1.0.2/grizzled-slf4j_2.10-1.0.2.jar
Downloading: https://repo.maven.apache.org/maven2/io/dropwizard/metrics/metrics-core/3.1.0/metrics-core-3.1.0.jar
Downloading: https://repo.maven.apache.org/maven2/com/github/scopt/scopt_2.10/3.2.0/scopt_2.10-3.2.0.jar
Downloading: https://repo.maven.apache.org/maven2/io/dropwizard/metrics/metrics-jvm/3.1.0/metrics-jvm-3.1.0.jar
Downloading: https://repo.maven.apache.org/maven2/io/dropwizard/metrics/metrics-json/3.1.0/metrics-json-3.1.0.jar
Downloading: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.4.0/jackson-annotations-2.4.0.jar
Downloading: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.4.2/jackson-databind-2.4.2.jar
Downloading: https://repo.maven.apache.org/maven2/org/eclipse/jetty/jetty-server/8.0.0.M1/jetty-server-8.0.0.M1.jar
Downloading: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jackson-core/2.4.2/jackson-core-2.4.2.jar
Downloading: https://repo.maven.apache.org/maven2/org/mortbay/jetty/servlet-api/3.0.20100224/servlet-api-3.0.20100224.jar
Downloading: https://repo.maven.apache.org/maven2/org/eclipse/jetty/jetty-continuation/8.0.0.M1/jetty-continuation-8.0.0.M1.jar
Downloading: https://repo.maven.apache.org/maven2/org/eclipse/jetty/jetty-http/8.0.0.M1/jetty-http-8.0.0.M1.jar
Downloading: https://repo.maven.apache.org/maven2/org/eclipse/jetty/jetty-io/8.0.0.M1/jetty-io-8.0.0.M1.jar
Downloading: https://repo.maven.apache.org/maven2/org/eclipse/jetty/jetty-util/8.0.0.M1/jetty-util-8.0.0.M1.jar
Downloading: https://repo.maven.apache.org/maven2/org/eclipse/jetty/jetty-security/8.0.0.M1/jetty-security-8.0.0.M1.jar
Downloading: https://repo.maven.apache.org/maven2/org/eclipse/jetty/jetty-servlet/8.0.0.M1/jetty-servlet-8.0.0.M1.jar
Downloading: https://repo.maven.apache.org/maven2/commons-fileupload/commons-fileupload/1.3.1/commons-fileupload-1.3.1.jar
Downloading: https://repo.maven.apache.org/maven2/org/apache/flink/flink-ml/0.10.2/flink-ml-0.10.2.jar
Downloading: https://repo.maven.apache.org/maven2/junit/junit/4.8.2/junit-4.8.2.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] xgboost-jvm ........................................ SUCCESS [  4.044 s]
[INFO] xgboost4j .......................................... SUCCESS [  7.881 s]
[INFO] xgboost4j-spark .................................... SUCCESS [ 17.507 s]
[INFO] xgboost4j-flink .................................... FAILURE [  0.483 s]
[INFO] xgboost4j-example .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 30.143 s
[INFO] Finished at: 2016-07-21T14:59:33+08:00
[INFO] Final Memory: 488M/2345M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project xgboost4j-flink: Could not resolve dependencies for project ml.dmlc:xgboost4j-flink:jar:0.5: The following artifacts could not be resolved: org.apache.flink:flink-core:jar:0.10.2, commons-collections:commons-collections:jar:3.2.2, org.apache.flink:flink-shaded-hadoop2:jar:0.10.2, commons-codec:commons-codec:jar:1.4, commons-net:commons-net:jar:3.1, commons-el:commons-el:jar:1.0, net.java.dev.jets3t:jets3t:jar:0.9.0, org.apache.httpcomponents:httpclient:jar:4.2, org.apache.httpcomponents:httpcore:jar:4.2, com.jamesmurty.utils:java-xmlbuilder:jar:0.4, commons-lang:commons-lang:jar:2.6, org.codehaus.jackson:jackson-core-asl:jar:1.8.8, org.codehaus.jackson:jackson-mapper-asl:jar:1.8.8, com.thoughtworks.paranamer:paranamer:jar:2.3, org.xerial.snappy:snappy-java:jar:1.0.5, com.jcraft:jsch:jar:0.1.42, org.apache.zookeeper:zookeeper:jar:3.4.6, io.netty:netty:jar:3.7.0.Final, commons-daemon:commons-daemon:jar:1.0.13, javax.xml.bind:jaxb-api:jar:2.2.2, javax.xml.stream:stax-api:jar:1.0-2, javax.activation:activation:jar:1.1, org.apache.avro:avro:jar:1.7.6, com.twitter:chill_2.10:jar:0.5.2, com.twitter:chill-java:jar:0.5.2, com.twitter:chill-avro_2.10:jar:0.5.2, com.twitter:chill-bijection_2.10:jar:0.5.2, com.twitter:bijection-core_2.10:jar:0.7.2, com.twitter:bijection-avro_2.10:jar:0.7.2, de.javakaffee:kryo-serializers:jar:0.27, joda-time:joda-time:jar:2.5, org.joda:joda-convert:jar:1.7, org.apache.commons:commons-math3:jar:3.5, org.slf4j:slf4j-api:jar:1.7.7, org.slf4j:slf4j-log4j12:jar:1.7.7, org.apache.flink:flink-scala:jar:0.10.2, org.apache.flink:flink-optimizer:jar:0.10.2, org.scalamacros:quasiquotes_2.10:jar:2.0.1, org.apache.flink:flink-clients:jar:0.10.2, org.apache.flink:flink-runtime:jar:0.10.2, io.netty:netty-all:jar:4.0.27.Final, org.javassist:javassist:jar:3.18.2-GA, com.typesafe.akka:akka-actor_2.10:jar:2.3.7, com.typesafe.akka:akka-remote_2.10:jar:2.3.7, com.typesafe.akka:akka-slf4j_2.10:jar:2.3.7, org.clapper:grizzled-slf4j_2.10:jar:1.0.2, com.github.scopt:scopt_2.10:jar:3.2.0, io.dropwizard.metrics:metrics-core:jar:3.1.0, io.dropwizard.metrics:metrics-jvm:jar:3.1.0, io.dropwizard.metrics:metrics-json:jar:3.1.0, com.fasterxml.jackson.core:jackson-databind:jar:2.4.2, com.fasterxml.jackson.core:jackson-annotations:jar:2.4.0, com.fasterxml.jackson.core:jackson-core:jar:2.4.2, org.eclipse.jetty:jetty-server:jar:8.0.0.M1, org.mortbay.jetty:servlet-api:jar:3.0.20100224, org.eclipse.jetty:jetty-continuation:jar:8.0.0.M1, org.eclipse.jetty:jetty-http:jar:8.0.0.M1, org.eclipse.jetty:jetty-io:jar:8.0.0.M1, org.eclipse.jetty:jetty-util:jar:8.0.0.M1, org.eclipse.jetty:jetty-security:jar:8.0.0.M1, org.eclipse.jetty:jetty-servlet:jar:8.0.0.M1, commons-fileupload:commons-fileupload:jar:1.3.1, org.apache.flink:flink-ml:jar:0.10.2, junit:junit:jar:4.8.2: Could not transfer artifact org.apache.flink:flink-core:jar:0.10.2 from/to central (https://repo.maven.apache.org/maven2): repo.maven.apache.org: Unknown host repo.maven.apache.org -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :xgboost4j-flink

**Comment by CodingCat** [comment]
` Failed to execute goal on project xgboost4j-flink: Could not resolve dependencies for project ml.dmlc:xgboost4j-flink:jar:0.5:...`

**Comment by colinsongf** [comment]
please close this issue, i have build xgboost4j sucessfully, the steps is as follows:
git clone --recursive https://github.com/dmlc/xgboost
git pull 
&& git submodule init && git submodule update && git submodule status
 cd xgboost; 

 make -j4
yum install gcc-c++

cd xgboost; make -j4
cd jvm-packages
./create_jni.sh
Mvn package
mvn -DskipTests=true package
