### ISSUE TITLE
[xgboost4j-spark] Doing rabit call after Finalize when save model

### ISSUE THREAD

**Issue by Earthson** [dmlc/xgboost#1384]
XGBoostModel is Serializable, so I save it directly, but failed.

@CodingCat 

```
[15:31:11] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 16 extra nodes, 0 pruned nodes, max_depth=6
[15:31:11] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 16 extra nodes, 0 pruned nodes, max_depth=6
[15:31:11] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 18 extra nodes, 0 pruned nodes, max_depth=5
==== serialized obj size 401108
==== the size of the object: 401108
==== serialized obj size 401108
==== serialized obj size 401108
==== the size of the object: 401108
Doing rabit call after Finalize

Process finished with exit code 255
```

**Comment by CodingCat** [comment]
I think it is related to https://github.com/dmlc/xgboost/pull/1334


@tqchen , would you check the author's comments there, and see if that is the case?

I think we might wish to get rid of involving rabit after training

**Comment by CodingCat** [comment]
and it is weird that this issue only appears in the recent days.....

**Comment by randomjohnnyh** [comment]
Having the same issue when predicting/saving, patch #1334 is only a partial workaround.

**Comment by Earthson** [comment]
@CodingCat This issue still exists after #1334 merged. This happens on XGBoostModel's serialization.

**Comment by Earthson** [comment]
It seems to be my fault. I put the XGBoostModel to RDD[XGBoostModel] and write it with rdd.saveAsObjectFile.
