### ISSUE TITLE
[jvm-packages] Does xgboost support DMatrix on Spark?

### ISSUE THREAD

**Issue by Alexkevin** [dmlc/xgboost#1385]
We are using xgboost on spark client, it is fast and efficiency.

Recently, we tried to apply xgboost in Learning to Rank (LR) project .

But we found xgboost(on spark) doesn't support DMatrix so that we couldn't use set_group function.

Do you guys will fix this ?

**Comment by CodingCat** [comment]
what do you mean by `does not support DMatrix`

https://github.com/dmlc/xgboost/blob/master/jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/DMatrix.java#L191

**Comment by Alexkevin** [comment]
@CodingCat  sorry for my poor english
I mean when I train a xgboost model on spark platform, can the format of trainingdata be DMatrix? 
I found it just support  the following format : org.apache.spark.rdd.RDD[org.apache.spark.mllib.regression.LabeledPoint]

**Comment by CodingCat** [comment]
LabeledPoint is essentially converted to DMatrix within xgboost-spark , we just automate this process for the user, 

if you want to operate on DMatrix directly, you can override the train method in https://github.com/dmlc/xgboost/blob/master/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala#L103 with a special interest in https://github.com/dmlc/xgboost/blob/master/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala#L73

**Comment by Alexkevin** [comment]
@CodingCat  Thanks for reply

It is a little bit difficult for beginners like me to override a new method 

Do you have any plan to deal with this issue?

**Comment by CodingCat** [comment]
it might be worth doing that, but I do not have the available slot right now  for that
