### ISSUE TITLE
Termination on AUC counting with all-same dataset 

### ISSUE THREAD

**Issue by Dronte** [dmlc/xgboost#1386]
Today using xgboost from python I got the following error in terminal:
Then the process terminates.

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  AUC: the dataset only contains pos or neg samples

```

I understand that counting AUC is not a good idea on all pos or all neg samples, but I wouldn't expect the process termination. May be error message in a log is enough?

**Comment by Laurae2** [comment]
You cannot compute AUC with all positive or all negative samples, as you will forcibly divide by 0 at the end. It also does not make sense to use AUC with all positive or all negative labels.

If you really need AUC without the termination, you can remove the CHECK part, set the sum_auc to a constant value, and recompile locally your edited xgboost.

**Comment by Dronte** [comment]
Laurae2, thanks for your answer.
I understand that computing AUC doesn't make sense with all positive or all negative examples and I ran into this situation by mistake. 
But I don't want xgboost to crash on that. 
I was using xgboost from ipython kernel with quite a lot data read from disk to memory and preprocessed.
When xgboost crashed the process I had to restart it and load data again, wich took me some time. 
I'd assume just printing error message in the log would be more convinient behaviour.

**Comment by Laurae2** [comment]
@Dronte: the major issue is if you allow AUC to be computed, you have a division by zero to do. And this is not possible.

Before running xgboost, do you have the possibility to check for whether there is a unique value only for the label, and if yes add an additional "junk" row with the opposite label? This would solve your issue, as you would have two classes and AUC would therefore be computable.

The other solution I provided before, is by modifying xgboost (remove CHECK and set sum_auc to a constant).

Another solution to that is to use a different metric.

Example, assuming SUM is your count of unique values of the labels and you are in Python, to select the argument:

`"auc" if SUM > 0 else "logloss"`

**Comment by khotilov** [comment]
@Laurae2: no one argues about the AUC validity and there's no real need for temporary workarounds. The error is justified as it makes one think about whether what they are doing is right. However, the issue simply is that the raised C++ exception is not converted into a Python/R exception, so it goes nuclear on the whole process. When you are running an interactive session and accidentally set all labels the same - it's no fun to crush for that reason - I've been there myself a few times.
