### ISSUE TITLE
[Python] last round out of sample predictions after cross validation

### ISSUE THREAD

**Issue by suntzu86** [dmlc/xgboost#1387]
Hi,
I was wondering if it could be possible to compute the average hold-out predictions in CV (really only want it on the final iteration).
I'm working in Python using the latest version on pypi: 0.4a30.

Right now, I think my only option here is to call `mknfolds()` 
https://github.com/dmlc/xgboost/blob/master/python-package/xgboost/training.py#L371
and manually go through CV, more or less replicating the `cv()` function but I returning `cvfolds` at the end so I can query it for predictions.

Are there any easier options?

**Comment by pommedeterresautee** [comment]
Has to be done as a post process

**Comment by suntzu86** [comment]
Ah yeah old issue.  The callback system makes this super easy if anyone else was interested:
```
def extract_cvfolds(cvfolds):
    def callback(env):
        cvfolds[:] = env.cvfolds

    return callback

# then the call to cv
cvfolds = []
xgboost.cv(..., callbacks=[extract_cvfolds(cvfolds)])
````
