### ISSUE TITLE
[Python] Could you make a new code release on pypi?

### ISSUE THREAD

**Issue by suntzu86** [dmlc/xgboost#1388]
Seems like there's been quite some new features since 0.4a30, released in Dec 2015. Would it be possible to deploy a new release on pypi?

**Comment by terrytangyuan** [comment]
@phunterlau Could you update it when you get a chance? Thanks

**Comment by phunterlau** [comment]
OK. Let me pack a build-on-the-fly version as before. I had couple of tries, but eventually rolled back to 0.4a30 because some of refactor code was too complicated to fit into a PyPI pack. Some recent code is good, and I will take another chance to have a try.

**Comment by terrytangyuan** [comment]
@phunterlau Sure, thanks. Please keep us posted.

**Comment by suntzu86** [comment]
marking this closed as this resulted in 0.6a2 on pypi 6 months ago
