### ISSUE TITLE
[Python] Is there any way to retrieve the model parameters from a Booster?

### ISSUE THREAD

**Issue by suntzu86** [dmlc/xgboost#1389]
Right now, Booster has a set_params method but no way to inspect what params are presently set. Particularly after loading a model from buffer or file (e.g., comparing present model against an older model), right now it's impossible to directly know what parameters were used in training.

I mean mostly the "params" object and num_boosting_rounds. But other effects like learning rates (or all callbacks? seems harder) could be useful too.

At the moment I have a subclass that saves/loads things appropriately into a pkl alongside the Booster object, but it'd be nice to be able to ask the Booster directly vs trying to ensure we never write to the Booster.

**Comment by pommedeterresautee** [comment]
Old question, no answer. Closing

**Comment by suntzu86** [comment]
We'd still be interested in a solution here; being able to "get" the things that we can "set" would be very useful.
