### ISSUE TITLE
Problem with building source code

### ISSUE THREAD

**Issue by samira-t** [dmlc/xgboost#1393]
Hi,

I have checked out the latest version of code. When I ran make -j4, I am getting the following error:

In file included from src/common/common.cc:7:

```
src/common/./thread_local.h: In static member function ‘static T* xgboost::common::ThreadLocalStore<T>::Get()’:
src/common/./thread_local.h:44: error: ‘nullptr’ was not declared in this scope
make: *** [build/common/common.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from src/c_api/c_api_error.cc:7:
src/c_api/../common/thread_local.h: In static member function ‘static T* xgboost::common::ThreadLocalStore<T>::Get()’:
src/c_api/../common/thread_local.h:44: error: ‘nullptr’ was not declared in this scope
make: *** [build/c_api/c_api_error.o] Error 1
In file included from src/c_api/c_api.cc:3:
include/xgboost/data.h: In constructor ‘xgboost::DMatrix::DMatrix()’:
include/xgboost/data.h:234: error: ‘nullptr’ was not declared in this scope
```

would you please help?

**Comment by randomjohnnyh** [comment]
You may need to upgrade your version of gcc, as nullptr is a C++11 feature. Check the output of "g++ -v"?

**Comment by samira-t** [comment]
Here is the output of g++ -v:
Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man
--infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla
--enable-bootstrap --enable-shared --enable-threads=posix
--enable-checking=release --with-system-zlib --enable-__cxa_atexit
--disable-libunwind-exceptions --enable-gnu-unique-object
--enable-languages=c,c++,objc,obj-c++,java,fortran,ada
--enable-java-awt=gtk --disable-dssi
--with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre
--enable-libgcj-multifile --enable-java-maintainer-mode
--with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib
--with-ppl --with-cloog --with-tune=generic --with-arch_32=i686
--build=x86_64-redhat-linux
Thread model: posix
gcc version 4.4.7 20120313 (Red Hat 4.4.7-11) (GCC)


--
Samira

**Comment by samira-t** [comment]
Here is the output:
`Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.4.7 20120313 (Red Hat 4.4.7-11) (GCC) 
`

**Comment by randomjohnnyh** [comment]
Upgrade to 4.8+, see devtoolset-2 on RH

**Comment by samira-t** [comment]
I have run sudo yum install devtoolset-2 and still see the same version. Do
you have any ideas how to upgrade the version?

--
Samira

**Comment by samira-t** [comment]
I tried to upgrade and here is teh result:
Package gcc-c++-4.4.7-11.el6.x86_64 already installed and latest version


--
Samira

**Comment by randomjohnnyh** [comment]
http://unix.stackexchange.com/questions/175851/how-to-permanently-enable-scl-centos-6-4
