### ISSUE TITLE
Got worse result with the  latest version

### ISSUE THREAD

**Issue by davutpolat** [dmlc/xgboost#1395]
Hi,

i just updated xgboost with latest one, ( my older version installed about 8 months ago) and i got worse result on same dataset ( objective is  reg:linear, tree_method=exact, oldest version does not support tree_method parameter).   anyone knows why  ?

**Comment by Laurae2** [comment]
Check whether the NA values are the same. 8 months ago, NA values were 0 when creating the xgb.DMatrix type, while it is now NA for NA. Check also whether you are using the same initial seed (in case).

Do you have a reproducible example? You can use verbose=2 when training XGBoost to print the tree/node count at each iteration. There, if you have a divergence straight at the beginning with the same exact parameters, it is likely the NA handling (old => 0 for NA, new => NA for NA) or a major/minor change in the splitting criterion in XGBoost.

**Comment by BlindApe** [comment]
Davut, what are all your parameters and number of features?

**Comment by davutpolat** [comment]
@BlindApe my parameters are : 

param = {}
param['tree_method'] = 'exact'
param['objective'] = 'reg:linear'
param['eta'] = 0.05
param['max_depth'] = 250
param['silent'] = 1
param['nthread'] = 11
param['subsample'] = 1.0
param['eval_metric'] = 'rmse'
param['min_child_weight'] = 50
param['colsample_bytree'] = 0.025


@Laurae2 

i didnt change NA values  it is : missing=np.NaN  and i dont have any missing value in my data

**Comment by khotilov** [comment]
It wouldn't surprise me that such somewhat extreme parameters (very high depth, but also very high min_child_weigh, and very sparse column-sampling) could lead to results that are unstable. Did you re-optimize your parameters? How many iterations? What's your data properties? By how much worse?

**Comment by davutpolat** [comment]
Actually depth is  25 not 250,  and i think my parameters fine,  dataset has many instances about 100M rows and about 150 column (mostly sparse), i am using scipy.sparse format (csr) , it is just %1 worse

**Comment by BlindApe** [comment]
As khotilov said these are  very extreme. 
Perhaps the problems are in parameters you didn't set: lambda, alpha, gamma... Could some of these change the default value in recent releases? lambda seems setting to 1 now (in gblinear is 0). Try to change to 0.
