### ISSUE TITLE
Up to date version (in R)

### ISSUE THREAD

**Issue by BlindApe** [dmlc/xgboost#1396]
I've installed the R version from 'our weekly updated drat repo':

install.packages("drat", repos="https://cran.rstudio.com")
drat:::addRepo("dmlc")
install.packages("xgboost", repos="http://dmlc.ml/drat/", type="source")

and sessionInfo says it is  xgboost_0.4-3

Installing fron cran I obtained version  xgboost_0.4-4 

How can I get the up to date dev version in R for Windows?

**Comment by thirdwing** [comment]
@BlindApe I just upload a new version to drat, please try again.

**Comment by terrytangyuan** [comment]
Are we still able to maintain CRAN version?
