### ISSUE TITLE
Handle multi-path in distributed XGboost?

### ISSUE THREAD

**Issue by sparktsao** [dmlc/xgboost#1398]
We are trying to feed >200G dataset into XGboost over yarn.
however we keep receive AWS s3 internal error when starting.

We are wondering what's the data plan to prepare large training data to XGboost distributed version by using AWS s3. Putting all data in the same folder seems will have s3 performance issue.
in the paper, the largest dataset is 2048 million. any advise to prepare the dataset?
large file with smaller number of file, or small file but the number of files is large?

From the code in DMLC-core, seems we can use multi-path:

```
void InputSplitBase::InitInputFileInfo(const std::string& uri) {
  // split by :
  const char dlm = ';';
  std::vector<std::string> file_list = Split(uri, dlm);
  std::vector<URI> expanded_list;
```

But we didn't success by just using

```
1) data=s3://A/;s3://B/
or
2) data='s3://A/;s3://B/'
or
3) data='s3://A/\;s3://B/'
```

any advise how to make it work?

and seems current path didn't do recursive down scanning the folder.
That means it cannot accept:

```
given s3://A/
```

and then scan:

```
s3://A/path1/file1.svm
s3://A/path1/file2.svm
s3://A/path1/file3.svm
s3://A/path2/file4.svm
s3://A/path2/file5.svm
s3://A/path2/file6.svm
```

I am wondering if XGboost already support multi-path or recursive as data input?
Many thanks

**Comment by pommedeterresautee** [comment]
Old question, old version, no answer. Closing
