### ISSUE TITLE
Problem saving cv predictions in multiclass model (dev version)

### ISSUE THREAD

**Issue by BlindApe** [dmlc/xgboost#1399]
In xgb.cv (from http://dmlc.ml/drat, updated today) I got this warning:

1: In pred[fd$index] <- pr :
  número de items para para sustituir no es un múltiplo de la longitud del reemplazo
(number of items to replace isn't a multiple of the length of replacement)

The problem seems related with saving the predictions in cv when training multiclass model.

**Comment by khotilov** [comment]
I had a few tests for multiclass but it looks like I've never committed them... so a bug crawled in.
I'll fix it later tonight.

**Comment by khotilov** [comment]
#1401 has it fixed
