### ISSUE TITLE
Windows Install Failing 

### ISSUE THREAD

**Issue by JohnPeng47** [dmlc/xgboost#1402]
Trying to run make on xg-boost folder. Followed instructions from Cortajarena https://github.com/dmlc/xgboost/issues/1267 and also made sure that my mingw64 installation is in a path without spaces. Ran the following:
git clone --recursive https://github.com/dmlc/xgboost
cd xgboost
git checkout 9a48a40
git submodule init
git submodule update
cp make/mingw64.mk config.mk
mingw32-make -j4

Output: 
g++ -m64 -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -MM -MT build/learner.o src/learner.cc >build/learner.d
g++ -m64 -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -MM -MT build/logging.o src/logging.cc >build/logging.d
g++ -m64 -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -MM -MT build/common/common.o src/common/common.cc >build/common/common.d
g++ -m64 -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -MM -MT build/c_api/c_api_error.o src/c_api/c_api_error.cc >build/c_api/c_api_error.d
g++ -m64 -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -c src/common/common.cc -o build/common/common.o
g++ -m64 -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -c src/logging.cc -o build/logging.o
g++ -m64 -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -c src/learner.cc -o build/learner.o
g++ -m64 -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -c src/c_api/c_api_error.cc -o build/c_api/c_api_error.o
g++ -m64 -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -MM -MT build/c_api/c_api.o src/c_api/c_api.cc >build/c_api/c_api.d
g++ -m64 -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -MM -MT build/data/simple_dmatrix.o src/data/simple_dmatrix.cc >build/data/simple_dmatrix.d
g++ -m64 -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -MM -MT build/data/sparse_page_raw_format.o src/data/sparse_page_raw_format.cc >build/data/sparse_page_raw_format.d
g++ -m64 -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -c src/c_api/c_api.cc -o build/c_api/c_api.o
g++ -m64 -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -c src/data/simple_dmatrix.cc -o build/data/simple_dmatrix.o
g++ -m64 -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -c src/data/sparse_page_raw_format.cc -o build/data/sparse_page_raw_format.o
g++ -m64 -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -MM -MT build/data/data.o src/data/data.cc >build/data/data.d
g++ -m64 -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -c src/data/data.cc -o build/data/data.o
g++ -m64 -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -MM -MT build/data/simple_csr_source.o src/data/simple_csr_source.cc >build/data/simple_csr_source.d
g++ -m64 -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -MM -MT build/data/sparse_page_writer.o src/data/sparse_page_writer.cc >build/data/sparse_page_writer.d
g++ -m64 -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -c src/data/simple_csr_source.cc -o build/data/simple_csr_source.o
g++ -m64 -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -c src/data/sparse_page_writer.cc -o build/data/sparse_page_writer.o
g++ -m64 -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -MM -MT build/data/sparse_page_source.o src/data/sparse_page_source.cc >build/data/sparse_page_source.d
g++ -m64 -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -c src/data/sparse_page_source.cc -o build/data/sparse_page_source.o
g++ -m64 -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -MM -MT build/data/sparse_page_dmatrix.o src/data/sparse_page_dmatrix.cc >build/data/sparse_page_dmatrix.d
g++ -m64 -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -MM -MT build/gbm/gbm.o src/gbm/gbm.cc >build/gbm/gbm.d
g++ -m64 -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -MM -MT build/gbm/gblinear.o src/gbm/gblinear.cc >build/gbm/gblinear.d
g++ -m64 -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -c src/data/sparse_page_dmatrix.cc -o build/data/sparse_page_dmatrix.o
g++ -m64 -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -c src/gbm/gbm.cc -o build/gbm/gbm.o
g++ -m64 -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -c src/gbm/gblinear.cc -o build/gbm/gblinear.o
g++ -m64 -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -MM -MT build/gbm/gbtree.o src/gbm/gbtree.cc >build/gbm/gbtree.d
g++ -m64 -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -MM -MT build/metric/multiclass_metric.o src/metric/multiclass_metric.cc >build/metric/multiclass_metric.d
g++ -m64 -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -c src/gbm/gbtree.cc -o build/gbm/gbtree.o
g++ -m64 -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -c src/metric/multiclass_metric.cc -o build/metric/multiclass_metric.o
g++ -m64 -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -MM -MT build/metric/elementwise_metric.o src/metric/elementwise_metric.cc >build/metric/elementwise_metric.d
g++ -m64 -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -c src/metric/elementwise_metric.cc -o build/metric/elementwise_metric.o
g++ -m64 -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -MM -MT build/metric/rank_metric.o src/metric/rank_metric.cc >build/metric/rank_metric.d
g++ -m64 -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -c src/metric/rank_metric.cc -o build/metric/rank_metric.o
g++ -m64 -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -MM -MT build/metric/metric.o src/metric/metric.cc >build/metric/metric.d
g++ -m64 -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -MM -MT build/objective/regression_obj.o src/objective/regression_obj.cc >build/objective/regression_obj.d
g++ -m64 -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -c src/metric/metric.cc -o build/metric/metric.o
g++ -m64 -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -c src/objective/regression_obj.cc -o build/objective/regression_obj.o
g++ -m64 -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -MM -MT build/objective/rank_obj.o src/objective/rank_obj.cc >build/objective/rank_obj.d
g++ -m64 -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -MM -MT build/objective/objective.o src/objective/objective.cc >build/objective/objective.d
g++ -m64 -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -c src/objective/rank_obj.cc -o build/objective/rank_obj.o
g++ -m64 -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -c src/objective/objective.cc -o build/objective/objective.o
g++ -m64 -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -MM -MT build/objective/multiclass_obj.o src/objective/multiclass_obj.cc >build/objective/multiclass_obj.d
g++ -m64 -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -MM -MT build/tree/tree_model.o src/tree/tree_model.cc >build/tree/tree_model.d
g++ -m64 -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -c src/objective/multiclass_obj.cc -o build/objective/multiclass_obj.o
g++ -m64 -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -MM -MT build/tree/updater_colmaker.o src/tree/updater_colmaker.cc >build/tree/updater_colmaker.d
g++ -m64 -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -c src/tree/tree_model.cc -o build/tree/tree_model.o
g++ -m64 -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -c src/tree/updater_colmaker.cc -o build/tree/updater_colmaker.o
In file included from src/tree/tree_model.cc:8:0:
src/tree/./param.h: In member function 'double xgboost::tree::TrainParam::CalcGain(double, double) const':
src/tree/./param.h:126:53: error: call of overloaded 'abs(double&)' is ambiguous
         return - 2.0 \* (ret + reg_alpha \* std::abs(w));
                                                     ^
In file included from C:/Users/johnpeng/mingw64/lib/gcc/x86_64-w64-mingw32/6.1.0/include/c++/ext/string_conversions.h:41:0,
                 from C:/Users/johnpeng/mingw64/lib/gcc/x86_64-w64-mingw32/6.1.0/include/c++/bits/basic_string.h:5402,
                 from C:/Users/johnpeng/mingw64/lib/gcc/x86_64-w64-mingw32/6.1.0/include/c++/string:52,
                 from dmlc-core/include/dmlc/io.h:9,
                 from include/xgboost/tree_model.h:10,
                 from src/tree/tree_model.cc:6:
C:/Users/johnpeng/mingw64/lib/gcc/x86_64-w64-mingw32/6.1.0/include/c++/cstdlib:172:3: note: candidate: long int std::abs(long int)
   abs(long __i) { return __builtin_labs(__i); }
   ^~~
In file included from C:/Users/johnpeng/mingw64/lib/gcc/x86_64-w64-mingw32/6.1.0/include/c++/cstdlib:75:0,
                 from C:/Users/johnpeng/mingw64/lib/gcc/x86_64-w64-mingw32/6.1.0/include/c++/ext/string_conversions.h:41,
                 from C:/Users/johnpeng/mingw64/lib/gcc/x86_64-w64-mingw32/6.1.0/include/c++/bits/basic_string.h:5402,
                 from C:/Users/johnpeng/mingw64/lib/gcc/x86_64-w64-mingw32/6.1.0/include/c++/string:52,
                 from dmlc-core/include/dmlc/io.h:9,
                 from include/xgboost/tree_model.h:10,
                 from src/tree/tree_model.cc:6:
C:/Users/johnpeng/mingw64/x86_64-w64-mingw32/include/stdlib.h:329:15: note: candidate: int abs(int)
   int __cdecl abs(int _X);
               ^~~
In file included from C:/Users/johnpeng/mingw64/lib/gcc/x86_64-w64-mingw32/6.1.0/include/c++/ext/string_conversions.h:41:0,
                 from C:/Users/johnpeng/mingw64/lib/gcc/x86_64-w64-mingw32/6.1.0/include/c++/bits/basic_string.h:5402,
                 from C:/Users/johnpeng/mingw64/lib/gcc/x86_64-w64-mingw32/6.1.0/include/c++/string:52,
                 from dmlc-core/include/dmlc/io.h:9,
                 from include/xgboost/tree_model.h:10,
                 from src/tree/tree_model.cc:6:
C:/Users/johnpeng/mingw64/lib/gcc/x86_64-w64-mingw32/6.1.0/include/c++/cstdlib:180:3: note: candidate: long long int std::abs(long long int)
   abs(long long __x) { return __builtin_llabs (__x); }
   ^~~
In file included from src/tree/tree_model.cc:8:0:
src/tree/./param.h: In member function 'double xgboost::tree::TrainParam::CalcGain(double, double, double, double) const':
src/tree/./param.h:138:51: error: call of overloaded 'abs(double&)' is ambiguous
       return - 2.0 \* (ret + reg_alpha \* std::abs(w));
                                                   ^
In file included from C:/Users/johnpeng/mingw64/lib/gcc/x86_64-w64-mingw32/6.1.0/include/c++/ext/string_conversions.h:41:0,
                 from C:/Users/johnpeng/mingw64/lib/gcc/x86_64-w64-mingw32/6.1.0/include/c++/bits/basic_string.h:5402,
                 from C:/Users/johnpeng/mingw64/lib/gcc/x86_64-w64-mingw32/6.1.0/include/c++/string:52,
                 from dmlc-core/include/dmlc/io.h:9,
                 from include/xgboost/tree_model.h:10,
                 from src/tree/tree_model.cc:6:
C:/Users/johnpeng/mingw64/lib/gcc/x86_64-w64-mingw32/6.1.0/include/c++/cstdlib:172:3: note: candidate: long int std::abs(long int)
   abs(long __i) { return __builtin_labs(__i); }
   ^~~
In file included from C:/Users/johnpeng/mingw64/lib/gcc/x86_64-w64-mingw32/6.1.0/include/c++/cstdlib:75:0,
                 from C:/Users/johnpeng/mingw64/lib/gcc/x86_64-w64-mingw32/6.1.0/include/c++/ext/string_conversions.h:41,
                 from C:/Users/johnpeng/mingw64/lib/gcc/x86_64-w64-mingw32/6.1.0/include/c++/bits/basic_string.h:5402,
                 from C:/Users/johnpeng/mingw64/lib/gcc/x86_64-w64-mingw32/6.1.0/include/c++/string:52,
                 from dmlc-core/include/dmlc/io.h:9,
                 from include/xgboost/tree_model.h:10,
                 from src/tree/tree_model.cc:6:
C:/Users/johnpeng/mingw64/x86_64-w64-mingw32/include/stdlib.h:329:15: note: candidate: int abs(int)
   int __cdecl abs(int _X);
               ^~~
In file included from C:/Users/johnpeng/mingw64/lib/gcc/x86_64-w64-mingw32/6.1.0/include/c++/ext/string_conversions.h:41:0,
                 from C:/Users/johnpeng/mingw64/lib/gcc/x86_64-w64-mingw32/6.1.0/include/c++/bits/basic_string.h:5402,
                 from C:/Users/johnpeng/mingw64/lib/gcc/x86_64-w64-mingw32/6.1.0/include/c++/string:52,
                 from dmlc-core/include/dmlc/io.h:9,
                 from include/xgboost/tree_model.h:10,
                 from src/tree/tree_model.cc:6:
C:/Users/johnpeng/mingw64/lib/gcc/x86_64-w64-mingw32/6.1.0/include/c++/cstdlib:180:3: note: candidate: long long int std::abs(long long int)
   abs(long long __x) { return __builtin_llabs (__x); }
   ^~~
Makefile:97: recipe for target 'build/tree/tree_model.o' failed
mingw32-make: **\* [build/tree/tree_model.o] Error 1
mingw32-make: **\* Waiting for unfinished jobs....

**Comment by ArtjomKorol** [comment]
Check this link: https://dnc1994.com/2016/03/installing-xgboost-on-windows/
you need to download Makefile_win file to the xboost folder and replace the one you have in there with it. Then it will work.

**Comment by RoXw** [comment]
I followed the procedure given in the link replaced the Makefile with Makefile_win but it dint work same error occured

**Comment by JohnPeng47** [comment]
I followed the steps you posted and got the new Makefile and was able to
successfully compile xgboost. However, when i tried to import xgboost in
python, i got the following error:

  File "<stdin>", line 1, in <module>
  File
"C:\Users\johnpeng\Anaconda2\lib\site-packages\xgboost-0.6-py2.7.egg\xgboost\__init__.py",
line 11, in <module>
    from .core import DMatrix, Booster
  File
"C:\Users\johnpeng\Anaconda2\lib\site-packages\xgboost-0.6-py2.7.egg\xgboost\core.py",
line 112, in <module>
    _LIB = _load_lib()
  File
"C:\Users\johnpeng\Anaconda2\lib\site-packages\xgboost-0.6-py2.7.egg\xgboost\core.py",
line 106, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])
  File "C:\Users\johnpeng\Anaconda2\lib\ctypes\__init__.py", line 443, in
LoadLibrary
    return self._dlltype(name)
  File "C:\Users\johnpeng\Anaconda2\lib\ctypes\__init__.py", line 365, in
__init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 127] The specified procedure could not be found

**Comment by ArtjomKorol** [comment]
Yeah, because there is no xboost.py module inside the installation, I don't know why. I addressed this issue have not got an answer. I actually spent a lot of time trying all the methods an it seems that at the moment there is no way to install xgboost on windows. If you want the older version you can check a youtube video "how to install xgboost" you will need to build it via Visual Studio. It will work but it lacks a lot of parameters and does not work with cross validation.

**Comment by JohnPeng47** [comment]
ok thanks for your help

**Comment by JohnPeng47** [comment]
I finished installing it on Ubuntu vm took like 10min honestly idk why i
didn't just do this from the start

**Comment by ArtjomKorol** [comment]
it's just not very convenient to run it on vm every time

**Comment by juliencohensolal** [comment]
"_ it seems that at the moment there is no way to install xgboost on windows_"

Agreed, it's pretty mind boggling to me, spent the last 2 days trying everything I could find on internet, to no avail.

**Comment by khotilov** [comment]
The fix for this gcc 6 issue was committed over a month ago #1308 
Please check out the head.

**Comment by EGQM** [comment]
I got the same error “OSError: [WinError 127]” on win10 with python3.5.
It seems like there is something wrong with libxgboost.dll.
