### ISSUE TITLE
what is the meaning of the value in the trained  tree model?

### ISSUE THREAD

**Issue by eroszip** [dmlc/xgboost#1403]
i have trained the uci mushroom database with  binary-classification,and then obtained the model.but i can not understand the meaning of leaf values? is there some difference with GBDT about leaf values in the classify field? meanwhile,for the trained model.each booster is the new function or the updated new additive model? please help!
![image](https://cloud.githubusercontent.com/assets/16421139/17129305/d44f960c-5344-11e6-9eda-dc07962695a2.png)
train parameters:
![image](https://cloud.githubusercontent.com/assets/16421139/17129070/85a6e876-5343-11e6-9029-5e4693832523.png)
and the result model as follows:
![image](https://cloud.githubusercontent.com/assets/16421139/17129096/ace259fc-5343-11e6-9480-ca54e166b1a5.png)

**Comment by earthwu** [comment]
yeah , I want to know this too

**Comment by hetong007** [comment]
You can get the classification probability if you put the leaf value through a sigmoid function.
