### ISSUE TITLE
how run xgboost4j-example target file .jar

### ISSUE THREAD

**Issue by colinsongf** [dmlc/xgboost#1404]
xgboost4j-example-0.5.jar
xgboost4j-example-0.5-jar-with-dependencies.jar

i have build successful, how run the above two jar files in centos linux

**Comment by CodingCat** [comment]
there are several classes in xgboost4j-example, each of which is an example https://github.com/dmlc/xgboost/tree/master/jvm-packages/xgboost4j-example/src/main/java/ml/dmlc/xgboost4j/java/example

and just run it as you run an normal java program

**Comment by colinsongf** [comment]
xgboost\jvm-packages\xgboost4j-example\src\main\scala\ml\dmlc\xgboost4j\scala\example
how run scala example?
are  these  xgboost4j-example-0.5.jar and
xgboost4j-example-0.5-jar-with-dependencies.jar useless?

**Comment by kirupagaran** [comment]
@colinsongf: Can you please tell me how you built the jar ?
