### ISSUE TITLE
Floating point precision

### ISSUE THREAD

**Issue by RAMitchell** [dmlc/xgboost#1410]
I have recently been experimenting with parallel methods for summing gradient pair statistics within xgboost. 

One thing I noticed was considerable variation in the result dependent on the choice of algorithm (e.g. a GPU parallel reduction vs. a CPU serial reduction). The first order gradient value could vary by upwards of 50% on a large dataset.

I believe this is a result of the non-associativity of floating point addition.

My question: 

Could this floating point error have a meaningful impact on the end result of the algorithm? Was the decision to use 32-bit floats an intentional design decision?

**Comment by tqchen** [comment]
we are using 32 bit float mainly for efficiency issues. That was actually especially true if you are using GPU, as most GPUs specializes in 32 bit floats.

For xgboost, the implementation of the sum statistics was stored in double while the statistics of each instances was stored in float

**Comment by RAMitchell** [comment]
Ah, I missed the fact that the summation was stored as a double within xgboost. I had originally thought it was 32 bit floating point but maybe the error was in acceptable bounds. I will have to do something similar using doubles for summation.

Thanks for your answer.
