### ISSUE TITLE
[xgboost4j-spark] Question about evalInfo

### ISSUE THREAD

**Issue by randomjohnnyh** [dmlc/xgboost#1412]
I have a question about this code, from https://github.com/dmlc/xgboost/blob/master/jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/XGBoost.java

``` java
      //evaluation
      if (evalMats != null && evalMats.length > 0) {
        String evalInfo;
        if (eval != null) {
          evalInfo = booster.evalSet(evalMats, evalNames, eval);
        } else {
          evalInfo = booster.evalSet(evalMats, evalNames, iter);
        }
        if (Rabit.getRank() == 0) {
          Rabit.trackerPrint(evalInfo + '\n');
        }
      }
      booster.saveRabitCheckpoint();
```

I may be misunderstanding, but is evalInfo only being printed for the first partition? This leads to misleading results if the partitions are not random. In that case, why is evalInfo computed for the other partitions? Also, why call saveRabitCheckpoint again here?

**Comment by CodingCat** [comment]
I think  it might be some leftover code in the early version of xgboost4j....I did not look at it carefully when working on the latest version...

I do not think `if (Rabit.getRank() == 0) {` and `booster.saveRabitCheckpoint();` are necessary ....
