### ISSUE TITLE
Request  for the parameter about pred_leaf

### ISSUE THREAD

**Issue by yxzf** [dmlc/xgboost#1413]
I submit xgboost through command line, I want to predict the leaf of  trees. I find in learner.cc, the function 

```
Predict(DMatrix* data, bool output_margin, std::vector<float> *out_preds, unsigned ntree_limit = 0, bool pred_leaf = false) 
```

has the parameter pred_leaf to predict leaf.

But in the https://github.com/dmlc/xgboost/blob/master/doc/parameter.md , there is no parameter about pred_leaf.

**Comment by pommedeterresautee** [comment]
Old question, no answer. Closing
