### ISSUE TITLE
Saving xgboost model with early stopping

### ISSUE THREAD

**Issue by Zoltrix** [dmlc/xgboost#1415]
When `early.stop.round` is set, the returned model object from `xgb.train` or `xgboost` will contain two extra attributes `bestScore` and `bestInd`. When saving this returned model object and reading it later, these two attributes will be gone:

```
data(agaricus.train, package='xgboost')
data(agaricus.test, package='xgboost')
train <- agaricus.train
test <- agaricus.test
bst <- xgboost(data = train$data, label = train$label, max.depth = 2, eta = 1, nthread = 2, nround = 100,objective = "binary:logistic", early.stop.round = 5, eval_metric="auc")
xgb.save(bst, 'xgb.model')
attributes(bst)
```

output of `attributes(bst)`:

```
$names
[1] "handle"    "raw"       "bestScore" "bestInd"  

$class
[1] "xgb.Booster"
```

Now load the model object:

```
bst <- xgb.load('xgb.model')
```

View the attributes:

```
$names
[1] "handle" "raw"   

$class
[1] "xgb.Booster"
```

**Comment by khotilov** [comment]
Please use the development version for accessing stored best iteration and score.

Also note that xgb.save/xgb.load are for saving/loading a binary dump that is universal among xgboost interfaces, and it can store internal xgboost attributes that are key-value pair strings. With early stopping enabled, one of them would be `best_iteration` (see `?cb.early.stop`) and it could be accessed using `xgb.attr`. However, xgb.save/xgb.load do not store R objects' fields or attributes. You would need to use the standard R's saving and loading methods to restore R objects as they were (it's ok with `xgb.Booster` object, as it stores a raw dump of its model in memory that could be restored after reading).
