### ISSUE TITLE
When the matrix has more than one class, the code fails

### ISSUE THREAD

**Issue by bbieniek** [dmlc/xgboost#1416]
Hi,

In the code of xgb.DMatrix.R, line 57, the code says:
`if (inClass == "dgCMatrix" || inClass == "matrix") {`

If the matrix has been created using for example the reshape package, the class function is going to return a vector of two values "cast_matrix" and "matrix".
I believe the code above should say:
` if ("dgCMatrix" %in% inClass || "matrix" %in% inClass ) {`

as in:
https://github.com/bbieniek/xgboost/blob/master/R-package/R/xgb.DMatrix.R

Thanks

**Comment by tqchen** [comment]
https://github.com/dmlc/xgboost/pull/1417
