### ISSUE TITLE
Question about XGBOOST4J-Spark verbose reporting

### ISSUE THREAD

**Issue by alexrozinov** [dmlc/xgboost#1418]
Is it possible to get a status update for XGBOOST4J when running it with Spark, something akin to seeing the current training epoch along with the current error? I'm used to seeing this in the python and R versions of XGBOOST. I know when running things in parallel this is more difficult but, is there a maybe a log that it can print to? 

Otherwise, when I look at the Spark job monitor, I see the pool of workers, but there isn't really any status update, in that the task monitor will stay at 0 out of X jobs done, and then suddenly jump to X and finish. It would be awesome to see a more detailed status update. Thanks for your help!

**Comment by CodingCat** [comment]
you shall be able to observe that from the executor logs for the task progress 

and in driver logs 

everything printed by rabit shall be also printed by JVM packages

**Comment by randomjohnnyh** [comment]
If you don't see them, it's possible you may have to configure log4j to show all INFO level debug messages.

**Comment by alexrozinov** [comment]
Thanks, fixed!
