### ISSUE TITLE
New CRAN Submission Candidate

### ISSUE THREAD

**Issue by tqchen** [dmlc/xgboost#1423]
As the 0.6 version taggged in https://github.com/dmlc/xgboost/pull/1422  

I would like to open an issue to coordinate a CRAN submission of XGBoost. A lot of new things has been added since 0.4 . We did not yet planned submission to CRAN due to the support of C++11 was a bit lagged behind. This seems no longer the issue and CRAN plans to switch to C++11 as default, so I am opening this thread to call for another CRAN submission
# Working Items
- [ ] Make sure R check cran pass in windows and linux @hetong007 
- [ ] Make sure compilation pass on solaris, I do not have a lot of resources in this, previously I relies on a VM to test if compilation pass. @thirdwing do you have any idea we can do this better ?
- [ ] Other outstanding items to see if there is anything we want to fix

**Comment by thirdwing** [comment]
The Rcpp team just uses a VM. The only good news is that next generation of Solaris Studio will be compatible with GCC.
