### ISSUE TITLE
No xgboost.py module in Windows installation

### ISSUE THREAD

**Issue by ArtjomKorol** [dmlc/xgboost#1424]
Hello,

After following this installation guide: https://dnc1994.com/2016/03/installing-xgboost-on-windows/
i have successful installed xgboost library, however there is simply no xboost.py module inside. These are the only files that are being installed, plus some egg-info files:

![image](https://cloud.githubusercontent.com/assets/1776521/17271104/f5ba85ce-567b-11e6-8e27-c3aed318a3ca.png)

also i've noticed that there is no more xgboost/windows directory in the package from: https://github.com/dmlc/xgboost so it's not possible to install it via Visual Studio.

pip install xgboost also does not work.

Can someone please explain what are the steps to install xgboost at his moment?

Thank you

**Comment by tqchen** [comment]
please follow the guide from the official document. this guide is a bit outdated
