### ISSUE TITLE
customized function in xgb

### ISSUE THREAD

**Issue by zhxwmessi** [dmlc/xgboost#1428]
I used huber function in xgb as a customized function, but xgb didn't converge. The output message is that the max_depth is 0,  which means that the tree never split. Why?
Does it mean that the  gain is always less than 0, or some other reason?

Here are the codes:
param_u_huber = 1e-5
def huber_grad_comp(pred, label):
    if abs(pred - label) <= param_u_huber:
        return (pred - label) / (param_u_huber \* label)
    elif pred > (param_u_huber + label):
        return 1.0 / label
    else:
        return -1.0 / label

def huber_hess_comp(pred, label):
    if abs(pred - label) <= param_u_huber:
        return 1.0 / (param_u_huber \* label)
    else:
        return 0.0

def huber_obj(preds, dtrain):
    labels = dtrain.get_label()
    grad = map(huber_grad_comp, preds, labels)
    hess = map(huber_hess_comp, preds, labels)
    return np.array(grad), np.array(hess)

**Comment by khotilov** [comment]
Cases that have zero hessian are basically excluded - that would be the cause for never-splitting.
One of the key features of xgboost is that it uses a second-order gradient boosting approach to speed up  the optimization, so it needs a double-differentiable loss. For huber-like regression, the log-cosh loss would be a close alternative.

**Comment by tqchen** [comment]
see https://github.com/dmlc/xgboost/issues/1825
