### ISSUE TITLE
upgrade from xgboost0.4a to xgboost0.47

### ISSUE THREAD

**Issue by mukesh-ranjan** [dmlc/xgboost#1432]
Hello Experts,

Hope you are doing well....
Need a help in upgrading xgboost 0.4a to xgboost0.47 (as in my current version xgboost.cv doesnt have elapsed time and some important parameter) on windows 10 64 bit python 2.7. I tried to update but i loop back to same version. Please let me know how to upgrade

**Comment by phunterlau** [comment]
please manually remove the `pip` installed xgboost 0.4a by deleting files like `./anaconda/lib/python2.7/site-packages/xgboost*`
