### ISSUE TITLE
Invalid vertex name raised in `xgb.plot.deepness`

### ISSUE THREAD

**Issue by terrytangyuan** [dmlc/xgboost#1434]
Someone sent me this via email:
@pommedeterresautee Could you take a look? I am able to reproduce under CRAN version. 

```
require(xgboost)
# load in the agaricus dataset
data(agaricus.train, package='xgboost')
data(agaricus.test, package='xgboost')
dtrain <- xgb.DMatrix(agaricus.train$data, label = agaricus.train$label)
dtest <- xgb.DMatrix(agaricus.test$data, label = agaricus.test$label)

param <- list(objective = "binary:logistic", booster = "gblinear",
              nthread = 2, alpha = 0.0001, lambda = 1)

watchlist <- list(eval = dtest, train = dtrain)
num_round <- 2
bst <- xgb.train(param, dtrain, num_round, watchlist)
ypred <- predict(bst, dtest)
labels <- getinfo(dtest, 'label')
cat('error of preds=', mean(as.numeric(ypred>0.5)!=labels),'\n')

xgb.plot.deepness(model=bst)
```

Errors:
```
Error in as.igraph.vs(graph, from) : Invalid vertex name(s)
In addition: Warning messages:
1: In data.table(ID = c(idBranch, idLeaf), Feature = c(featureBranch,  :
  Item 2 is of size 120 but maximum size is 121 (recycled leaving remainder of 1 items)
2: In data.table(ID = c(idBranch, idLeaf), Feature = c(featureBranch,  :
  Item 3 is of size 120 but maximum size is 121 (recycled leaving remainder of 1 items)
3: In data.table(ID = c(idBranch, idLeaf), Feature = c(featureBranch,  :
  Item 4 is of size 120 but maximum size is 121 (recycled leaving remainder of 1 items)
4: In data.table(ID = c(idBranch, idLeaf), Feature = c(featureBranch,  :
  Item 5 is of size 120 but maximum size is 121 (recycled leaving remainder of 1 items)
5: In data.table(ID = c(idBranch, idLeaf), Feature = c(featureBranch,  :
  Item 6 is of size 120 but maximum size is 121 (recycled leaving remainder of 1 items)
6: In data.table(ID = c(idBranch, idLeaf), Feature = c(featureBranch,  :
  Item 7 is of size 120 but maximum size is 121 (recycled leaving remainder of 1 items)
7: In data.table(ID = c(idBranch, idLeaf), Feature = c(featureBranch,  :
  Item 8 is of size 120 but maximum size is 121 (recycled leaving remainder of 1 items)
8: In as.igraph.vs(graph, from) : NAs introduced by coercion
```

**Comment by pommedeterresautee** [comment]
I have not checked yet but ` booster = "gblinear"` looks suspicious when you want to display tree deepness...

**Comment by terrytangyuan** [comment]
Oops, I didn't pay much attention to that. Perhaps we can add a check there to give more informative error.

**Comment by pommedeterresautee** [comment]
I don't know if it s a good idea. I mean R is not typed, we can add hundred of cases and check in the code to avoid these cases. But it is a lot of work and not sure it will be very useful. I mean, checking that the number if trees is a positive integers makes sense: easy to check + lots of possible errors + parameters used by all users. 

But checking that the model provided match our expectation to plot it: hard to check + few people will have this kind of error + require to adapt the checks for each modification of the core code.

However, if other contributora think it is useful, I ll do it.

**Comment by khotilov** [comment]
While the `xgb.plot.deepness` does check that the columns in a tree table
are as expected, the issue stems from `xgb.model.dt.tree` returning a
nonsensical tree table for a gblinear model. It would be fairly easy to add
an extra check to `xgb.model.dt.tree` to prevent it from trying to create a
tree table from a text dump that doesn't look like a tree booster dump.
