### ISSUE TITLE
[xgboost4j-spark] XGBoost has no way to detect numWorkers?

### ISSUE THREAD

**Issue by randomjohnnyh** [dmlc/xgboost#1436]
Is there any good way to detect the number of spark workers? Right now I'm thinking of using sc.getExecutorMemoryStatus.size-1. Also, XGBoost just stalls when the number of Spark workers is insufficient - is there no better behavior?

**Comment by CodingCat** [comment]
XGBoost imposes that all executors  must running at the same time for allreduce, so it does not support multi-wave job

for detecting spark workers, restful APIs would be helpful http://spark.apache.org/docs/1.6.2/monitoring.html

**Comment by jeisinge** [comment]
FYI, on Spark 2.1.0, you can get the number of cores via:
```
val sparkUI = sc.getClass.getMethod("ui").invoke(sc).asInstanceOf[Option[_]].get
val executorsListener = sparkUI.getClass.getMethod("executorsListener").invoke(sparkUI).asInstanceOf[org.apache.spark.ui.exec.ExecutorsListener]

val totalCores = executorsListener.synchronized { 
  executorsListener.executorToTaskSummary
    .filter { case (eid, taskSummary) => taskSummary.isAlive }
    .map { case (eid, taskSummary) => taskSummary.totalCores }
    .sum
}
```

Is that what numWorkers should be set to --- or, just the number of executors?
