### ISSUE TITLE
performance of xgboost vs gbdt in spark

### ISSUE THREAD

**Issue by FanBit** [dmlc/xgboost#1438]
I have a job which aims to give a appropriate rank order. The job can be viewed as a regression problem or a classification problem.
Previously, I used the gbdt in spark-mllib, whose performance(order result, evaluated by MAP/NDCG) is as good as what I expected.
However, now the xgboost in spark performance is very bad. It's evaluation is so poor that I wonder if there's any mistake I didn't aware of.
What I want to know is, if any one compare the two methods in spark? And your results?

**Comment by pommedeterresautee** [comment]
No code, Old question, no answer. Closing
