### ISSUE TITLE
Error installing xgboost with OpenMP-enabled compliers

### ISSUE THREAD

**Issue by zero-jack** [dmlc/xgboost#1442]
## Enviroment

- Mac OSX EI Capitan 10.11.6
- gcc version 6.1.0 (``brew install gcc``)
- gcc --version detailed

> Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1

> Apple LLVM version 7.3.0 (clang-703.0.31)
>
>Target: x86_64-apple-darwin15.6.0
>
>Thread model: posix
>
>InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

- python 3.5.2 ( ``pyenv install``  )
- xgboost (``git clone --recursive https://github.com/dmlc/xgboost``)

## Problem 

I want an OpenMP enabled xgboost and followed [OSX building instrution](https://xgboost.readthedocs.io/en/latest/build.html#building-on-osx) . When running ``make -j4``, the errors come as follow:
```


➜  ~ cd xgboost

➜  xgboost git:(master) cp make/config.mk ./config.mk


➜  xgboost git:(master) make -j4

c++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/learner.o src/learner.cc >build/learner.d
c++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/logging.o src/logging.cc >build/logging.d
c++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/c_api/c_api.o src/c_api/c_api.cc >build/c_api/c_api.d
c++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/c_api/c_api_error.o src/c_api/c_api_error.cc >build/c_api/c_api_error.d
clangclangclangclang: : error: : errorerror: : : unsupported option '-fopenmp'unsupported option '-fopenmp'error: unsupported option '-fopenmp'unsupported option '-fopenmp'



make: *** [build/c_api/c_api_error.o] Error 1

make: *** Waiting for unfinished jobs....

make: *** [build/c_api/c_api.o] Error 1

make: *** [build/logging.o] Error 1

make: *** [build/learner.o] Error 1
```

## Hope

Fix this problem

**Comment by rouseguy** [comment]
Please follow these instructions
https://www.ibm.com/developerworks/community/blogs/jfp/entry/Installing_XGBoost_on_Mac_OSX

**Comment by ghego** [comment]
I just stumbled on the same problem. The instruction links seems to be outdated wrt both brew and the current version of makefile in xgboost. I submitted a PR with a fix. Compiles ok on my mac

**Comment by phunterlau** [comment]
For the very latest version of Makefile, Mac OS X asks for gcc-5 for supporting open noIf you have gcc-6, please change the Makefile or the confit.mk for the right gcc. I may later on summit a PR, since this requirement is correlated with pip, it is not a straight forward easy fix.

**Comment by ghego** [comment]
Not sure about what you mean. the PR I submitted correctly installs both using setup.py and using pip with anaconda on mac

**Comment by zero-jack** [comment]
Is it necessary to install gcc using ``brew install gcc --without-multilib`` not ``brew install gcc``? What's the difference between them?

**Comment by wulh** [comment]
As @phunterlau said, i change the Makefile and config.mk(both) replacing gcc-5/g++-5 with gcc-6/g++-6, and it works.

**Comment by xiaokunx** [comment]
@zero-jack the original issue you reported is due to the fact that "gcc" in mac is just a wrapper/pointer to "clang", if you type "gcc --version" in your terminal
```bash
$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
whereas the real gcc install with XCode or brew is in different location
```
$ brew install gcc
Warning: gcc-6.1.0_1 already installed
$ which gcc-6
/usr/local/bin/gcc-6
```

therefore as @wulh  said, just edit the Makefile and config.mk(both) replacing gcc-5/g++-5 with gcc-6/g++-6 should work

**Comment by zero-jack** [comment]
@wulh @xiaokunx Thanks! Editing the Makefile and config.mk(both) replacing gcc-5/g++-5 with gcc-6/g++-6 does work.

**Comment by nsangwan** [comment]
In the latest version replacement has to be done in config.mk:

Open config.mk and uncomment these two lines
export CC = gcc
export CXX = g++

Depending on you g++ installation (5 or 6 or 7), change the above two lines into:
export CC = gcc-6
export CXX = g++-6

**Comment by avostryakov** [comment]
From the 2017 year, replace in config.mk:

export CC = gcc
export CXX = g++

on 

export CC = gcc-7
export CXX = g++-7

**Comment by simonhughes22** [comment]
gcc is not at version 7. If you run the brew install command you will install that version. So the config.mk update now becomes:

`export CC = gcc-7
export CXX = g++-7`

**Comment by NikIshmametev** [comment]
You should change in files config.mk and Makefile 

gcc and g++ 

on 

gcc-7 and g++-7

**Comment by lawwu** [comment]
Looks like as of 2018-08-31, brew install gcc installs version 8 so this is now gcc-8 and g++-8
