### ISSUE TITLE
Lua Wrapper to XGBoost

### ISSUE THREAD

**Issue by FuriouslyCurious** [dmlc/xgboost#1444]
Hi there,

I am interested in using XGBoost from inside Torch.  I will appreciate if you can provide a native Lua wrapper similar to Python one.

It will make the library much more accessible to Torch community.

Thanks!

**Comment by tqchen** [comment]
Currently there is no people working on this, but contribution is welcomed

**Comment by alex3s** [comment]
Yes, it would be great! being able to access XGBoost capabilities from Lua and Torch.
Currently what is the best option to do it? Using Command Line interface or C++ wrapper?

**Comment by hcho3** [comment]
I've added this as an item in the central feature request tracker.
