### ISSUE TITLE
mlogloss issue

### ISSUE THREAD

**Issue by panpur** [dmlc/xgboost#1447]
I'm comparing xgb.cv score of mlogloss with sklearn's log_loss function.
Most of the time the results are very close, e.g 2.40 vs 2.41

But there's 1 dataset that have quite different scores, 2.38 vs 3.57
So I thought there's an issue in xgb.cv

I'm attaching the script & data.
[test.zip](https://github.com/dmlc/xgboost/files/408832/test.zip)

**Comment by pommedeterresautee** [comment]
Old question, no answer. Closing
