### ISSUE TITLE
[xgboost4j-spark] Bug when training many models in the same session

### ISSUE THREAD

**Issue by randomjohnnyh** [dmlc/xgboost#1448]
When training multiple models in the same session, sometimes xgboost4j-spark reads the old cache file without realizing that the new input is different, resulting in exactly the same model.

In https://github.com/dmlc/xgboost/blob/master/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala, there is a line:

```
s"$appName-dtrain_cache-${TaskContext.getPartitionId()}"
```

One solution is to append another unique ID. Another would be to clear the cache files (this solution seems better).

**Comment by CodingCat** [comment]
resolved by https://github.com/dmlc/xgboost/pull/1493#partial-pull-merging
