### ISSUE TITLE
Fast one-off predictions

### ISSUE THREAD

**Issue by jxieeducation** [dmlc/xgboost#1449]
Hi everyone,

I want to use xgboost models at an environment that requires submilisecond predictions. However, these predictions come in one offs (so my DMatrix would only have 1 entry at a time). 

What are some optimizations that I can do to achieve the best possible latency? (Right now, it's clocking at around 5ms for 80 trees at depth 12 and I'd need something that clocks under 0.2ms)

**Comment by okke-formsma** [comment]
Python bindings for this functionality would also be greatly appreciated.

**Comment by tomliptrot** [comment]
And R!
