### ISSUE TITLE
Inconvenient behavior of early stopping callback

### ISSUE THREAD

**Issue by kiselev1189** [dmlc/xgboost#1450]
There is an issue concerning early stopping callback, that leads to some inconveniences.
It determines if the feval has to be maximized by just checking if the name of eval function starts with one of ('auc', 'map', 'ndcg') to detect metrics that are named like "auc@n", etc. This leads to some frustrating behaviour: for example, i want to minimize my custom metric that is called "mape" (Mean absolute percentage error), and regardless of value of maximize parameter in .train call it will be maximized. 

I have proposed a simple fix for this as a pull request.

**Comment by tqchen** [comment]
This is merged. thanks for the contribution
