### ISSUE TITLE
how to deal with missing value in JVM?

### ISSUE THREAD

**Issue by Alexkevin** [dmlc/xgboost#1452]
we all know xgboost can deal with missing value when we create dmatrix in python or r.

but how to set missing = NAN in java or scala?

I didn't find the constructor or method in java or scala can deal with that?

Anyone helps?

**Comment by CodingCat** [comment]
is https://github.com/dmlc/xgboost/blob/master/jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/DMatrix.java#L128 what you want?
