### ISSUE TITLE
Compile Issue with pre-submodule commit via install_github.

### ISSUE THREAD

**Issue by jsal13** [dmlc/xgboost#1457]
[compile_issues.txt](https://github.com/dmlc/xgboost/files/412157/compile_issues.txt)
We've use a specific commit (pre-submodule, so install_github still works) for production purposes, like so:

`devtools::install_github("dmlc/xgboost@0dc68b1", subdir = "R-package")`

But the compilation seems to fail (error log attached).

I've included information about the PC below.  Any help or suggestions would be appreciated!

PC INFO.
`Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                16
On-line CPU(s) list:   0-15
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             4
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            15
Model:                 6
Model name:            Intel(R) Xeon(R) CPU E5-2695 v4 @ 2.10GHz`

**Comment by hetong007** [comment]
Installing from a previous commit is not encouraged, since that might be a commit with errors. If local compilation is not possible, you can still install the latest version by

```
install.packages("drat", repos="https://cran.rstudio.com")
drat:::addRepo("dmlc")
install.packages("xgboost", repos="http://dmlc.ml/drat/", type="source")
```
