### ISSUE TITLE
Error Check failed: tree[nid].is_leaf()  while running

### ISSUE THREAD

**Issue by ducquangkstn** [dmlc/xgboost#1458]
Hi,  when i trained xgboost model, after few iteration, I got this error:  
[11:12:47] dmlc-core/include/dmlc/logging.h:235: [11:12:47] src/tree/./updater_basemaker-inl.h:272: Check failed: tree[nid].is_leaf
()  
terminate called after throwing an instance of 'dmlc::Error'  
  what():  [11:12:47] src/tree/./updater_basemaker-inl.h:272: Check failed: tree[nid].is_leaf()       

Can u explain?

**Comment by ducquangkstn** [comment]
I don't know why, but why i use 'tree_method':'exact' , i get no error at all.

**Comment by zqg** [comment]
i got the same error.

**Comment by TroyRetter** [comment]
This error can occur when training from a .LibSVM file if features labels are repeated on a line.
e.g.
2 1:34 5:93 1:59
