### ISSUE TITLE
[Python] Could we get a way to convert DMatrix back to ndarray or scipy csr?

### ISSUE THREAD

**Issue by suntzu86** [dmlc/xgboost#1462]
I've often found myself wishing I could access the data inside the DMatrix after creating it. For example, after slicing up a DMatrix for cross validation folds, I want to look at some of the columns in "dtest" for post-processing (e.g., doing `GROUP BY` type operations on my metrics based on data column(s)).

Right now the only way to do this is to reimplement `mknfold` and `cv` myself... not end of the world but rather hacky.

Could we get a way to either:
1) extract columns from a DMatrix into a numpy array
or
2) construct a numpy array (recarray? 2d array? whatever) or scipy.sparse.csr_matrix from DMatrix?

**Comment by pommedeterresautee** [comment]
The structure of Dmatrix is not built to make manipulation easy. 
Old question, no answer. Closing

**Comment by suntzu86** [comment]
But the structure of DMatrix is exactly that of scipy.sparse.csr_matrix. I guess bad things could happen if scipy changes their format (why would they... it's csr), but that's what version pinning is for?

Yeah I realize that DMatrix is structured for internal use/performance.

However, forcing users to maintain 2 copies of data (one numpy/scipy/other, one DMatrix) is unnecessarily awkward.
