### ISSUE TITLE
Error when using both prediction=T and booster='gblinear'

### ISSUE THREAD

**Issue by NamLQ** [dmlc/xgboost#1465]
Hi, I currently use xgboost R package version 0.4-4. There is an error when performing cv with prediction=T and booster='gblinear'. With prediction=F, there is no error.

> Error in predict.xgb.Booster(bst, ...) : 

>   [16:48:27] amalgamation/../src/gbm/gblinear.cc:177: Check failed: (ntree_limit) == (0) GBLinear::Predict ntrees is only valid for gbtree predictor

Here is the code:

> data(agaricus.train, package='xgboost')

> dtrain <- xgb.DMatrix(agaricus.train$data, label = agaricus.train$label)

> cv <- xgb.cv(data = dtrain, nrounds = 10, nthread = 2, nfold = 5, metrics = "auc",
             booster='gblinear', max_depth = 3, eta = 1, objective = "binary:logistic",
             early_stopping_rounds=NULL, prediction=T)

**Comment by yanyachen** [comment]
The problem is because the `cb.cv.predict` function will use ntreelimit parameter to compute the out-of-fold prediction, no matter which booster(tree or linear) xgboost was using.
https://github.com/dmlc/xgboost/blob/d5c143367daa37872870b31f460c38af07d35121/R-package/R/callbacks.R#L495
