### ISSUE TITLE
XgBoost error on running xgb.cv - could not find function xgb.cv

### ISSUE THREAD

**Issue by dguleria** [dmlc/xgboost#1466]
Need help - I am running xgb.cv with command below but i get error - Error: could not find function "xgb.cv"

xgboostcv <- xgb.cv(param= param, data  = datamatrix , label = datamatrix, nfold = cv.nfold, nrounds = cv.nround)

What Am I doing wrong here

**Comment by hetong007** [comment]
Please complete your question following the instructions in https://raw.githubusercontent.com/dmlc/xgboost/master/ISSUE_TEMPLATE.md.
