### ISSUE TITLE
R package licensing

### ISSUE THREAD

**Issue by Irkenev** [dmlc/xgboost#1472]
In the R package description the license is Apache License 2.0. However stringr is imported that is a GPL-2 licensed package. As far as I know, this import enforces xgboost to be GPL-2 also. Can you confirm this?
If this is the case, then it would be very nice, if the problematic dependencies were changed to Apache compatible ones. Thank you!

**Comment by tqchen** [comment]
see https://github.com/dmlc/xgboost/issues/1338

**Comment by Irkenev** [comment]
Duplicates #1338.
