### ISSUE TITLE
In OSX El Capitan CC/CXX flags mentioned in make/config.mk are not used.

### ISSUE THREAD

**Issue by sausax** [dmlc/xgboost#1476]
In OSX El Capitan, I uncommented CC/CXX variables in make/config.mk. But during compilation, always clang is picked. Also, brew installs gcc++-6 not gcc++-5. I manually edited make file and replaced gcc++-5 with gcc++-6 to make it work.

**Comment by phunterlau** [comment]
because in `Makefile` I have required `gcc-5` for a safe choice of Mac OS X installation since `brew install gcc --without-multilib` currently gives gcc-5 https://github.com/dmlc/xgboost/blob/master/Makefile#L46 you can manually change to gcc-6

**Comment by sausax** [comment]
I already did that, and it worked. Are you using El Capitan OS ? I think it might be a new change, latest version of brew installs gcc-6.

**Comment by lijingpeng** [comment]
I have the same problem and I fixed it by modify the Makefile and change gcc-5/g++-5 to gcc-6/g++-6. Since so many people use OSX El Capitan, I think we should add this tips to the official installation document.
