### ISSUE TITLE
amalgamation/../dmlc-core/src/io/local_filesys.cc:61: LocalFileSystem.GetPathInfo Error:No such file or directory

### ISSUE THREAD

**Issue by fakyras** [dmlc/xgboost#1480]
`dfull <- xgb.DMatrix(as.matrix(xg.M), label=xg.Y, missing=NaN)`
Error in xgb.DMatrix(as.matrix(xg.M), label = xg.Y, missing = NaN) : 
  [21:47:15] amalgamation/../dmlc-core/src/io/local_filesys.cc:61: LocalFileSystem.GetPathInfo 0.16388082504 Error:No such file or directory

Im getting interesting error. Tried with same dataset on different machines with same xgboost version. This is the first time it happened to me. 
Any clues what it could be?

xgboost installed from source
install hash: c529cac6ff5e5d9a3affb3d14af66d46537c5fd6
using R on win10

Edit:
found out the culprit - there was character column in dataset (int64 converted to character);

Interesting error nonetheless

**Comment by dmi3kno** [comment]
Agree. More explicit error would be helpful. Thanks, raddar!

**Comment by puneetjindal** [comment]
Is it resolved? I am getting the same error as following
"amalgamation/../dmlc-core/src/io/local_filesys.cc:86: LocalFileSystem.ListDirectory 3/10 error: No such file or directory"

**Comment by fakyras** [comment]
double check if you have provided all numeric type features to xgb.DMatrix function. Hope it helps

**Comment by nielsenmarkus11** [comment]
@fakyras suggestion corrected the problem for me... user error (doh) :)  Agree with @dmi3kno that a more explicit error would be helpful.

**Comment by tqchen** [comment]
Seems was due to the fact that xgboost recognize some of it as string and think it is a path. @khotilov  @hetong007 maybe a better input type recognition code?

**Comment by khotilov** [comment]
I've added a simple check in #2045 to print out, hopefully, a more clear error message.

**Comment by theastyanax** [comment]
Can you please explain how to "double check if you have provided all numeric type features to xgb.DMatrix function"

**Comment by Tommyixi** [comment]
@theastyanax You should call str(dataframe) and check each variables type is of numeric (eg: not factor). XGBoost won't work with categorical (factor) variables.

**Comment by sibijohn72** [comment]
Running xgboost on https://www.kaggle.com/dalpozz/creditcardfraud also returns this error. I have made sure that all the variable types are numeric.

**Comment by liangmuxin** [comment]
Try data.matrix(yourdata) inside DMatrix() instead of as.matrix(yourdata), it works on me.

**Comment by harryprince** [comment]
it seems the document needs to be improved, `xgboost` should throw the correct error for human in detail instead of the C++/C level error.

**Comment by hcho3** [comment]
@harryprince Can you make a more concrete proposal for generating better error message? Let's open a new issue so that we can keep track of it.
