### ISSUE TITLE
[jvm-packages]Compiling xgboost4j on Windows

### ISSUE THREAD

**Issue by Craigacp** [dmlc/xgboost#1491]
## Environment info

Operating System: Windows 7/10

Compiler: Mingw64 or MS Visual Studio 14

Package used (python/R/jvm/C++): JVM

`xgboost` version used: v0.60
## What have you tried?

First I tried to build xgboost using mingw64. This produced a binary with a 32-bit long, which isn't compatible with the 64-bit long used by Java on all platforms. The binary was compiled with ming set to 64 bits, but as ming conforms to the Windows x64 ABI (which requires long to be 32-bits, see https://msdn.microsoft.com/en-us/library/94z15h2c.aspx) this produces a binary which isn't compatible with the JVM wrapper.

Then on a different machine I tried to build it with Visual Studio. Once I'd generated the solution files and opened the project, I could build the standard dll, but there is no option for building the JNI wrapper.

Either way it seems like xgboost4j doesn't work on Windows. The issue is similar to #1148, but I think I've figured out the root cause (for mingw64 at least).

It looks like in mingw64 line 50 in include/xgboost/base.h typedefs bst_ulong as a 32-bit value. It should be using `unsigned long long` to make sure it's 64-bits on Windows, or the `uint64_t` type that's defined in dmlc which seems to have ifdefs to make it generate the correct type.

**Comment by Craigacp** [comment]
Looks like it also needs changing on line 28 of include/xgboost/c_api.h, and on line 44 the type `long` isn't specific enough, but `int64_t` works fine.

Oddly the uint64_t type isn't defined in the JNI wrapper, but if you add `#include <cstdint>` then it works a little better. There are a couple of other places which define things as `long` instead of a more precise type in the JNI wrapper and where the return type coming out of xgboost can be changed into jint from int.

**Comment by CodingCat** [comment]
@tqchen do we have any official plan on supporting  xgboost on windows ?

**Comment by Craigacp** [comment]
I've managed to get it to compile and pass tests on Windows now (for xgboost4j, I didn't test Spark or Flink). On Monday I'll check I didn't break anything in Linux or Mac by changing those types. Assuming that's true should I work up a pull request?

**Comment by CodingCat** [comment]
Yeah, that would be nice if you can file a PR

**Comment by Craigacp** [comment]
My patch required a couple of extra lines to make it work on MacOS (I had to ifdef the CSR struct as int64_t isn't compatible with Java on MacOS for some odd reason). Both the R and Python interfaces seem to work ok on Linux and Mac. I had to hack around in the Makefile to make Windows generate the right filename and then mess with the create_jni.bat, so I'll clean that up before making a PR.

**Comment by Craigacp** [comment]
Everything's in shape now, I'm just waiting for approval before I can make the PR.

**Comment by alaeddinms** [comment]
has this been approved? when do expect to add this back?

Thanks

**Comment by brajabp** [comment]
Thanks Craigacp for working on this issue. I am also waiting for xgboost4j implementation on Windows. Is there any workaround to make it work on 64-bit windows? Otherwise when this issue will be fixed, any eta?

**Comment by brajabp** [comment]
@Craigacp , @CodingCat : We are planning to use xgboost R-package for training in AWS EC2 and xgboost jvm-package for prediction in real production environment.

Later I came across https://github.com/komiya-atsushi/xgboost-predictor-java, which describes it as "Pure Java implementation of XGBoost predictor for online prediction tasks".

I am doing a quick test of this new library to evaluate and compare prediction results with xgboost jvm-package prediction results. In the mean time I want your suggestion about this library. How legitimate and reliable this library is?

**Comment by Craigacp** [comment]
@CodingCat is there a contributor agreement I'll need to sign?

**Comment by CodingCat** [comment]
@Craigacp no...

**Comment by Craigacp** [comment]
Ok, thanks.
