### ISSUE TITLE
boost on continuous predictions

### ISSUE THREAD

**Issue by tyokota** [dmlc/xgboost#1495]
The vignette on [boosting from predictions in R](https://github.com/dmlc/xgboost/blob/master/R-package/demo/boost_from_prediction.R) shows an example for probabilistic outcomes. I am trying to replicate the example with a continuous outcome. I would image that the parameter `outputmargin` in `predict()` should be set to FALSE. How would I then use the predictions for xgboost to pick up from?

In the example, the following is used:
`setinfo(dtrain, "base_margin", ptrain)`
This is specific to when the outcome is probabilistic?

**Comment by hetong007** [comment]
The `outputmargin` makes no difference for regression. 
The `setinfo` is important since it tells the continuing training process where to start.
