### ISSUE TITLE
Hard classification in Xgboost

### ISSUE THREAD

**Issue by vivek531** [dmlc/xgboost#1497]
I built a classifier with only 0 and 1 in my output space. And for training, I used objective as **multi:softprob**. Now when I am testing on the validation data, all my probabilities are more than 0.5,
How do I get the hard classification in this case. If I take the threshold to be .5, then all my validation data points would be classified as 1's. Please guide me here.

**Comment by pommedeterresautee** [comment]
Old question, no answer, closing
