### ISSUE TITLE
[jvm-packages]I am trying to use XGBoost4j but I am getting below mentioned error.

### ISSUE THREAD

**Issue by ragnar-lothbrok** [dmlc/xgboost#1498]
## Environment info
Operating System: Ubuntu 14.04

Compiler: Java 1.8 oracle

Package used (python/R/jvm/C++): jvm

1. after cloning from git hub -> cd xgboost/jvm-packages
2. mvn clean install -DskipTests [it successfully built jars]
3. I added spark jar in my java project and when I try to run it is showing 
Exception in thread "main" java.lang.UnsatisfiedLinkError: ml.dmlc.xgboost4j.java.XGBoostJNI.XGDMatrixCreateFromFile(Ljava/lang/String;I[J)I
	at ml.dmlc.xgboost4j.java.XGBoostJNI.XGDMatrixCreateFromFile(Native Method)
	at ml.dmlc.xgboost4j.java.DMatrix.<init>(DMatrix.java:83)
	at com.spark.lograthmicregression.ClickThroughRateAnalytics.main(ClickThroughRateAnalytics.java:55)

Thanks.

**Comment by CodingCat** [comment]
would you please confirm the native libraries are successfully built?

**Comment by ragnar-lothbrok** [comment]
Sorry I forgot to delete the issue. I was able to successfully set up when I found the document for Ubuntu. Also I am able to predict result using xgboost java.

But when I am using python[xgboost] with the same parameters and same data set. In general it should show same accuracy[+- 3%] but in xgboost java it is 6% more.

Python : 85%
xgboost java : 91%

Also when I am increasing  rounds in cross validation and tree depth it is getting better but in python it is not.  Can you please confirm if that can be possible??
