### ISSUE TITLE
Getting different accuracy in Python and Xgboost Java

### ISSUE THREAD

**Issue by ragnar-lothbrok** [dmlc/xgboost#1499]
Is it possible to get different accuracy in xgboost java module and Python?? I am using same parameters for both.

**Comment by CodingCat** [comment]
it should not 

please follow the issue template when report your issue,

**Comment by ragnar-lothbrok** [comment]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System: Ubuntu

Compiler: 
Java 1.8 oracle

Package used (python/R/jvm/C++): python and jvm



If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`)
2. Logs will be helpful (If logs are large, please upload as attachment).

If you are using python package, please provide : 

1. The python version and distribution : Python 2.7.6 (default, Jun 22 2015, 17:58:13)
2. The command to install `xgboost` if you are not installing from source : using pip
`xgboost` version used: xgboost (0.6a2)

## Steps to reproduce

1. Run script using python and run using java xgboost
2.
3.

## What have you tried?

1. Tried with python : https://github.com/ragnar-lothbrok/ctr-pred/blob/master/com/demo/prection_xgboost.py
2. Java : https://github.com/ragnar-lothbrok/spark-demo/blob/master/src/main/java/com/spark/lograthmicregression/ClickThroughRateAnalytics_XGboost.java

Increasing depth and round :
Java accuracy incresing [up to 91%]
Python constant up to 85%

**Comment by CodingCat** [comment]
not familiar with python stuffs, let me ping @terrytangyuan

but I think you can dump the model to see whether the trained model is exactly the same

**Comment by saj1919** [comment]
Anyone found out the reason behind this issue ??
I am also facing the same issue ... with Java I am getting 5-10% more accuracy than in Python.
Not sure why !!! This is another similar issue logged though closed issue still persist -> https://github.com/dmlc/xgboost/issues/1992

**Comment by ankurkhurana03** [comment]
I am facing the issue, could you help me with the resolution?
