### ISSUE TITLE
Can the variable in xgboost be initialized?

### ISSUE THREAD

**Issue by ushanbrisk** [dmlc/xgboost#1502]
I am using xgboost linear mode to do some optimization. 
The process needs call xgboost within a loop, so xgboost
will be called for many times. 
I am asking whether the initial value for variable can be initialized
or set by us to feed into xgboost, so that the optimized result 
can be utilized in the next xgboost optimization operation ?
Any ideas? Thank you very much.

**Comment by hetong007** [comment]
If you want to continue your training on a previous model, please check https://github.com/dmlc/xgboost/blob/master/R-package/demo/boost_from_prediction.R

**Comment by ushanbrisk** [comment]
got you, I tested it, it works, and found I need to add all the model in each iteration, so for the linear coefficients. Thank you very much!
