### ISSUE TITLE
8 threads is faster than 12 threads ?

### ISSUE THREAD

**Issue by StevenLOL** [dmlc/xgboost#1511]
## Environment info
Operating System:
ubuntu 15.04   16.04 
python 2.7

`xgboost` version used:
6 ?  by
``` 
pip install xgboost
```
If installing from source, please provide 

## Steps to reproduce

Create a regression problem with 50 or 70 features,  9M samples

Using XGBRegressor

```
    n_estimators=1000

    xlf = xgb.XGBRegressor(max_depth=10,
                        learning_rate=0.1,
                        n_estimators=n_estimators,
                        silent=True,
                        objective='reg:linear',
                        nthread=-1,
                        gamma=0.001,
                        min_child_weight=1,
                        max_delta_step=0,
                        subsample=0.85,
                        colsample_bytree=0.7,
                        colsample_bylevel=1,
                        reg_alpha=0,
                        reg_lambda=1,
                        scale_pos_weight=1,
                        seed=2016,
                        missing=None)
    xlf.fit(X_train, y_train, eval_metric='rmse', verbose = True, eval_set = [(X_test, y_test)],early_stopping_rounds=1,)
```

## What have you tried?

On a machine which support 12 threads ( nthread=-1)
1. adjust number of thread from 12 to 8 , and found the training speed is twice faster than 12

**Comment by tqchen** [comment]
It could be possible. Due to hyper threading setting in CPU cores. While they are able to support 12 threads, only 6 cores are available. 

In these settings, usually setting nthread to number of cores yields the best speedup

**Comment by phunterlau** [comment]
usually `nthread=-1` uses all hyperthreads (2x cores) instead of all cores, and CPUs with dynamic frequency boost may switch to a lower frequency when use all hyperthreads, which practically slows down the training. As Tianqi just mentioned, the best idea is nthread = the number of real cores.

**Comment by StevenLOL** [comment]
Thanks
