### ISSUE TITLE
multicore problem on 2 processors machine

### ISSUE THREAD

**Issue by pantofelek** [dmlc/xgboost#1512]
Hi,
I have problem with xgboost running as R package on my 2xXeon 2x4 cores (16 threads) machine. I obtain strange results, e.g. using function xgb.train with watchlist dval rmse goes down (0.32) below values obtained on other (1-processor) machines (0.44), and additionally bestInd is sometimes biased - not connected with the minimum of rmse. Of course, the final results are useless (rmse>0.7). 
Need help.
Thanks in advance.
## Environment info

Operating System:
Scientific Linux 7.2 (Nitrogen)
Compiler:
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4)
Package used (python/R/jvm/C++): R
xgboost version used: 0.4.4

If you are using R package, please provide
1. The R `sessionInfo()`

R version 3.3.1 (2016-06-21)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Scientific Linux 7.2 (Nitrogen)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8  
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8  
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C  
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.3.1
1. The command to install `xgboost` if you are not installing from source

install.packages('xgboost')
## Steps to reproduce

1.https://www.kaggle.com/bpavlyshenko/grupo-bimbo-inventory-demand/bimbo-xgboost-r-script-lb-0-457
2.
3.
## What have you tried?

1.checked openMP (libgomp-4.8.5-4.el7.x86_64)
2.switched off hyperthreading in BIOS
3.set nthread  to 8 or 1
4. loop of boosting from prediction - the results fast go down from 2-4 to 0.4-0.6 instead of rise to 3-300

**Comment by pommedeterresautee** [comment]
Old bug, no answer, closing
