### ISSUE TITLE
[jvm-packages]XGBoost4j.dll on Windows

### ISSUE THREAD

**Issue by alaeddinms** [dmlc/xgboost#1517]
What is the status of XGBoost4j.dll on Windows? How can we build it now if it has been added back?

**Comment by CodingCat** [comment]
it hasn't been added back

**Comment by alaeddinms** [comment]
Thanks for your reply. Do you know when it will be added back and what to do now?

Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>




On Sun, Aug 28, 2016 at 9:02 PM +0300, "Nan Zhu" <notifications@github.com<mailto:notifications@github.com>> wrote:


it hasn't been added back

-

**Comment by CodingCat** [comment]
I think it will be added back soon, @Craigacp is working on a PR which handles this https://github.com/dmlc/xgboost/issues/1491

**Comment by superbobry** [comment]
The current `master` works on Windows.
