### ISSUE TITLE
Model prediction[Xgboost4j java] taking more time  when trying to predict in Multi Threaded manner

### ISSUE THREAD

**Issue by ragnar-lothbrok** [dmlc/xgboost#1520]
[test_200.data.zip](https://github.com/dmlc/xgboost/files/441902/test_200.data.zip)

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System: Ubuntu

Compiler: Jdk1.8 Oracle

Package used (python/R/jvm/C++): jvm

`xgboost` version used: latest code

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`)
2. Logs will be helpful (If logs are large, please upload as attachment). [Time in seconds]
##############Thread-0 0.876
##############Thread-9 1.66
##############Thread-6 2.753
##############Thread-8 3.684
##############Thread-7 4.666
##############Thread-5 5.636
##############Thread-1 6.647
##############Thread-4 7.666
##############Thread-2 8.689
##############Thread-3 9.716

## Steps to reproduce

1. Loaded Model from file. Running prediction for 10k records in threaded environment. [Java Threads] 
Sample Code : 
private static void predictModel(DMatrix trainMat, DMatrix testMat) throws XGBoostError {
		List<Booster> list = new ArrayList<Booster>();
		for(int i=0;i<10;i++){
			list.add(XGBoost.loadModel("/home/file/001.model"));
		}
		for (int i = 0; i < 10; i++) {
			new Thread(new Runnable() {
				public void run() {
					try {
						long ms = System.currentTimeMillis();
						System.out.println(ms);
						float[][] predicts2 = list.get(0).predict(testMat);
						System.out.println("##############"+Thread.currentThread().getName()+" " + ((System.currentTimeMillis() - ms)/1000.0));
					} catch (XGBoostError e) {
						e.printStackTrace();
					}
				}
			}).start();
		}
	}

File atatched.
[001.model.zip](https://github.com/dmlc/xgboost/files/441878/001.model.zip)

**Comment by CodingCat** [comment]
how many cores do you have in your machine?

I think it is highly related to the limited number of cores (which might be much smaller than 10)

the latency records in in my 4-cores laptop:

```
##############Thread-2 0.116
##############Thread-4 0.118
##############Thread-5 0.119
##############Thread-7 0.105
##############Thread-1 0.12
##############Thread-9 0.098
##############Thread-0 0.127
##############Thread-3 0.133
##############Thread-8 0.119
##############Thread-6 0.133

```
