### ISSUE TITLE
[xgboost4j] support spark-2.0 and scala 2.11

### ISSUE THREAD

**Issue by Earthson** [dmlc/xgboost#1528]
RT

**Comment by CodingCat** [comment]
I will start working on this after this week, the current plan is to include the support to DataFrame/Dataset when bump up to spark-2.0

**Comment by dirceusemighini** [comment]
Hello, is there any plan to update xgboost4j to spark 2 and scala 2.11?

**Comment by CodingCat** [comment]
....it has been only support Spark 2 since last Sept
