### ISSUE TITLE
[jvm-packages] Large-scale dataset make executors `cannot find address`

### ISSUE THREAD

**Issue by yxzf** [dmlc/xgboost#1529]
I hava a dataset, which has more than 1000 partition. I set the "num-executor=40". 
From the source code, it will run ```trainingData.coalesce(numWorkers)```. 
However, from the log, many executors `cannot find address` and finally the job failed. I have test many times, the results are the same.

I test the same code with samller partition(5), the job succeeds. So I think the reason maybe coalesce function without shuffle. So I change the source code--> ```trainingData.coalesce(numWorkers, true)```
Then, the job succeeds. 
@CodingCat Do you know the reason
<img width="949" alt="12a3157c-1932-4af4-a4c9-1047bd5f2c20" src="https://cloud.githubusercontent.com/assets/9815568/18121003/ffd11a3c-6f94-11e6-946f-23759d907dbe.png">

```
val partitionedData = {
      if (numWorkers > trainingData.partitions.length) {
        logger.info(s"repartitioning training set to $numWorkers partitions")
        trainingData.repartition(numWorkers)
      } else if (numWorkers < trainingData.partitions.length) {
        logger.info(s"repartitioning training set to $numWorkers partitions")
        trainingData.coalesce(numWorkers)
      } else {
        trainingData
      }
    }
```

**Comment by yxzf** [comment]
I also set the num-executor=100, but still failed

**Comment by CodingCat** [comment]
I think you're right, we shall impose shuffle when creating training RDDs

**Comment by CodingCat** [comment]
addressed in https://github.com/dmlc/xgboost/issues/1529

**Comment by yxzf** [comment]
@CodingCat  Thank you for your response. Can you tell me the reason why shuffle should be done in here?
