### ISSUE TITLE
The indices value by predLeaf seem to be not right?

### ISSUE THREAD

**Issue by universewill** [dmlc/xgboost#1534]
The max depth of tree is 5. So the leaf number of one tree is no more than 16, I do not know why the results seem to be around 50...
## My python code is as follow:

print ('start predict the leaf indices')
leafindex = model.predict(data, ntree_limit=10, pred_leaf = True)
print leafindex.shape
print leaf index
## and the result is:

start predict the leaf indices
(270943, 10)
[[38 32 36 ..., 48 50 50]
 [52 48 46 ..., 38 50 50]
 [52 48 46 ..., 38 50 50]
 ...,
 [52 48 45 ..., 47 50 50]
 [52 48 45 ..., 47 50 50]
 [52 48 45 ..., 48 42 50]]

**Comment by universewill** [comment]
I dumps the model and find that the depth of the tree is actually 6,while the max_depth in my conf file is set to 5.

**Comment by convexquad** [comment]
@universewill The root node of the tree is at "depth 0", so the actual number of leaf nodes in a tree of depth 5 will be 2^5 = 32, and the total number of nodes (assuming the tree is full) will be 2^6 -1 = 63.

**Comment by universewill** [comment]
@convexquad I think it is more common that the depth of root node is regard as 0 ...

**Comment by joyang1** [comment]
@tqchen  Why xgboost4j predictLeaf  return 3 leaf indices? 
I use xgboost-0.80.jar
