### ISSUE TITLE
XGBoost use one-hot encoding to preproccess input data，what is the advantage of one-hot? why not map  features to an integer, such men are map to value 0,  female value 1.

### ISSUE THREAD

**Issue by landiaozixuan** [dmlc/xgboost#1536]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System:

Compiler:

Package used (python/R/jvm/C++):

`xgboost` version used:

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`)
2. Logs will be helpful (If logs are large, please upload as attachment).

If you are using python package, please provide

1. The python version and distribution
2. The command to install `xgboost` if you are not installing from source

If you are using R package, please provide

1. The R `sessionInfo()`
2. The command to install `xgboost` if you are not installing from source

## Steps to reproduce

1.
2.
3.

## What have you tried?

1.
2.
3.

**Comment by tqchen** [comment]
There is no guidelines on how feature preprocessing can be done, you can always do the remapping you like, and that job is not part of xgboost
