### ISSUE TITLE
xgboost not installing on centos

### ISSUE THREAD

**Issue by jkapila** [dmlc/xgboost#1537]
## Environment info

Operating System: CentOS 6.7 (Final
Compiler: gcc - 4.8.2
Package used (python):
`xgboost` version used:0.6a2

command
cd xgboost
make -j4
Error stack:
[centos@userds xgboost]$ make -j4
g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/learner.o src/learner.cc >build/learner.d
g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/logging.o src/logging.cc >build/logging.d
g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/c_api/c_api.o src/c_api/c_api.cc >build/c_api/c_api.d
g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/c_api/c_api_error.o src/c_api/c_api_error.cc >build/c_api/c_api_error.d
g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/c_api/c_api_error.cc -o build/c_api/c_api_error.o
g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/logging.cc -o build/logging.o
g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/c_api/c_api.cc -o build/c_api/c_api.o
g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/learner.cc -o build/learner.o
g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/common/common.o src/common/common.cc >build/common/common.d
g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/common/common.cc -o build/common/common.o
g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/data/data.o src/data/data.cc >build/data/data.d
g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/data/data.cc -o build/data/data.o
g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/data/simple_csr_source.o src/data/simple_csr_source.cc >build/data/simple_csr_source.d
g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/data/simple_csr_source.cc -o build/data/simple_csr_source.o
/tmp/ccvXgd4B.s: Assembler messages:
/tmp/ccvXgd4B.s:148: Error: expecting string instruction after `rep'
/tmp/ccvXgd4B.s:1796: Error: expecting string instruction after`rep'
/tmp/ccvXgd4B.s:4394: Error: expecting string instruction after `rep'
make: *** [build/data/simple_csr_source.o] Error 1
make: *** Waiting for unfinished jobs....
/tmp/cclcP5Rh.s: Assembler messages:
/tmp/cclcP5Rh.s:10009: Error: expecting string instruction after`rep'
/tmp/cclcP5Rh.s:15440: Error: expecting string instruction after `rep'
make: *** [build/c_api/c_api.o] Error 1
/tmp/cc8YRJOh.s: Assembler messages:
/tmp/cc8YRJOh.s:44: Error: expecting string instruction after`rep'
/tmp/cc8YRJOh.s:227: Error: expecting string instruction after `rep'
/tmp/cc8YRJOh.s:231: Error: expecting string instruction after`rep'
/tmp/cc8YRJOh.s:271: Error: expecting string instruction after `rep'
/tmp/cc8YRJOh.s:28394: Error: expecting string instruction after`rep'
make: **\* [build/learner.o] Error 1
/tmp/ccAD0HEm.s: Assembler messages:
/tmp/ccAD0HEm.s:82: Error: expecting string instruction after `rep'
make: **\* [build/data/data.o] Error 1

Also Tried:
1) ./build.sh; make -j4
2) Resinstalling gcc
3) cp make/config.mk . 
nano config.mk
export CC = gcc
export CXX = g++
export MPICXX = mpicxx

make -j4

The Problem still Persist... Kindly help asap...

**Comment by phunterlau** [comment]
From the version number 0.6a2, seems like you are using the pip install version instead of GitHub installlation. Have you tried using 'pip install xgboost' ?

**Comment by jkapila** [comment]
yes I have.... Infact that is the first thing I did.. I am trying to install xgboost with Anaconda Python stack.
When I use pip install xgboost, it is not able to build anything i.e c_api.o, learner.o, etc... 

Diving deeper i found anaconda comes with it older gcc.. So I updated that too and tried and then it gave the same output as you can see above..!!

Also i have tried reinstalling the gcc on centos and fresh installation of anaconda python, but nothing seems to help..

**Comment by phunterlau** [comment]
@jkapila seems like you want more than just the python lib, right? I can suggest installing from github by following the exact instruction. If any problems, please use the issue template for reporting. Thanks.
