### ISSUE TITLE
[jvm-packages] Predict per instance in spark is very slow

### ISSUE THREAD

**Issue by yxzf** [dmlc/xgboost#1538]
I have a dataset, one instance is like (user_id, label, features)
I want to record the final results like (user_id, label, predict)
So I have to predict one instance each time like this
```
 val outputRDD = dataFrame.rdd.map(line => {
      val userId = line(line.fieldIndex("user_id"));
      val featureAndSize = line.getString(line.fieldIndex("features")).trim().split(" ", -1)
      val size = Integer.parseInt(featureAndSize(0))
      val features = featureAndSize(1).trim().split(",", -1)
      val (indices, values) = features.filter(_.nonEmpty).map { feature =>
        val indexAndValue = feature.split(":")
        val index = indexAndValue(0).toInt
        val value = indexAndValue(1).toFloat
        (index, value)
      }.unzip

      val rowHeaders = Array[Long](0, values.length)
      val dMatrix = new DMatrix(rowHeaders, indices.toArray, values.toArray, JDMatrix.SparseType.CSR)
      val result_array =  model.booster.predict(dMatrix)(0)
      val predict = result_array(0)
    })
    Row(
          userId,
          line(line.fieldIndex("label")),
          "%f".format(predict))

```
The result shows that it is very very slow... It looks like that every time only one partition is processed. 
The same way I used for LR model in Spark is only one min.

Some one know why it is very slow, and have a better way ? @CodingCat 

Index  ▴	ID	Attempt	Status	Locality Level	Executor ID / Host	Launch Time	Duration	GC Time	Input Size / Records	Errors
0	1	0	RUNNING	RACK_LOCAL	41 / rz-data-hdp-dn1092.rz.sankuai.com	2016/09/02 21:02:08	1.1 h	0.1 s	0.0 B (hadoop) / 16970	
1	2	0	SUCCESS	RACK_LOCAL	46 / rz-data-hdp-dn0120.rz.sankuai.com	2016/09/02 21:02:08	13 min	1 s	38.6 MB (hadoop) / 519897	
2	3	0	RUNNING	RACK_LOCAL	24 / rz-data-hdp-dn0401.rz.sankuai.com	2016/09/02 21:02:08	1.1 h	0.3 s	0.0 B (hadoop) / 32172	
3	4	0	RUNNING	RACK_LOCAL	30 / rz-data-hdp-dn0147.rz.sankuai.com	2016/09/02 21:02:08	1.1 h	0.3 s	0.0 B (hadoop) / 28465	
4	5	0	RUNNING	RACK_LOCAL	33 / rz-data-hdp-dn0147.rz.sankuai.com	2016/09/02 21:02:08	1.1 h	0.3 s	0.0 B (hadoop) / 28434	
5	6	0	SUCCESS	RACK_LOCAL	29 / rz-data-hdp-dn0957.rz.sankuai.com	2016/09/02 21:02:08	2.8 min	0.9 s	38.6 MB (hadoop) / 518387	
6	7	0	RUNNING	RACK_LOCAL	21 / rz-data-hdp-dn0401.rz.sankuai.com	2016/09/02 21:02:08	1.1 h	0.3 s	0.0 B (hadoop) / 31865	
7	8	0	RUNNING	RACK_LOCAL	19 / rz-data-hdp-dn3560.rz.sankuai.com	2016/09/02 21:02:08	1.1 h	0.7 s	0.0 B (hadoop) / 241314	
8	9	0	RUNNING	RACK_LOCAL	37 / rz-data-hdp-dn3770.rz.sankuai.com	2016/09/02 21:02:08	1.1 h	0.3 s	0.0 B (hadoop) / 28807	
9	10	0	RUNNING	RACK_LOCAL	43 / rz-data-hdp-dn1092.rz.sankuai.com	2016/09/02 21:02:08	1.1 h	0.2 s	0.0 B (hadoop) / 17027	
10	11	0	RUNNING	RACK_LOCAL	39 / rz-data-hdp-dn1092.rz.sankuai.com	2016/09/02 21:02:08	1.1 h	0.2 s	0.0 B (hadoop) / 17085	
11	12	0	RUNNING	RACK_LOCAL	38 / rz-data-hdp-dn3770.rz.sankuai.com	2016/09/02 21:02:08	1.1 h	0.3 s	0.0 B (hadoop) / 28684	
12	13	0	SUCCESS	RACK_LOCAL	7 / rz-data-hdp-dn0706.rz.sankuai.com	2016/09/02 21:02:08	8.9 min	1.0 s	37.9 MB (hadoop) / 512480	
13	0	0	RUNNING	NODE_LOCAL	42 / rz-data-hdp-dn1092.rz.sankuai.com	2016/09/02 21:02:04	1.1 h	62 ms	0.0 B (hadoop) / 17084

**Comment by CodingCat** [comment]
AFAIK, XGBoost does not support online prediction for now 

if the purpose for you to record (userId, label, prediction) is just for evaluation, https://github.com/dmlc/xgboost/blob/master/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostModel.scala#L38 might be the choice?

**Comment by CodingCat** [comment]
I am working on DataFrame integration...after I finished, I think it is not a problem any more

**Comment by yxzf** [comment]
@CodingCat Thank you. Not just for evaluation, also need to dump the results into Hive. I'm looking forward the integration.

**Comment by CodingCat** [comment]
hmmm , I think you can grab the code in https://github.com/dmlc/xgboost/blob/master/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostModel.scala#L74

because the order is preserved within each partition, so you can generate the expected format conveniently

**Comment by yxzf** [comment]
@CodingCat I have tried to do like this. Label and predict can be got, but I do not how to record userid with them.
val data = dataFrame.rdd.map {
        line =>
          val featureAndSize = line.getString(line.fieldIndex("features")).trim().split(" ", -1)
          val size = Integer.parseInt(featureAndSize(0))
          val features = featureAndSize(1).trim().split(",", -1)
          val (indices, values) = features.filter(_.nonEmpty).map { feature =>
            val indexAndValue = feature.split(":")
            val index = indexAndValue(0).toInt
            val value = indexAndValue(1).toDouble
            (index, value)
          }.unzip
          val userId = line(line.fieldIndex("user_id"))
          val labelPoint = LabeledPoint(
            line.getInt(line.fieldIndex("label")).toDouble,
            Vectors.sparse(size, indices.toArray, values.toArray))
          (userId, labelPoint)
      }
      import DataUtils._
      data.mapPartitions { part =>
        if (part.hasNext) {
          val dMatrix = new DMatrix(part)
          val labels = dMatrix.getLabel
          val predicts = model.booster.predict(dMatrix)
          Iterator(predicts)
        }else {
          Iterator()
        }
      }

**Comment by CodingCat** [comment]
the basic idea is 

```scala
trainingRDD.mapPartition {
  partitionItr => 
     val (itr1, itr2) = partitionItr.duplicate
     val labelPointItr = transformToLabelPointItr(Itr1)
     val userIds = itr2.map(_.userId)
     val predResults = new DMatrix(labelPointItr)
     userIds.zip(predResults)
}
```

sorry for the pseudocode

**Comment by yxzf** [comment]
@CodingCat Thank you very much. I will try your method.

**Comment by haiy** [comment]
@CodingCat does the predict support dataframe input now?

**Comment by CodingCat** [comment]
@haiy yes, see https://github.com/dmlc/xgboost/blob/master/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostModel.scala#L299

**Comment by haiy** [comment]
Great ! Thanks so much!
