### ISSUE TITLE
Cannot import XGboost after compiling xgboost.dll and installing python packages

### ISSUE THREAD

**Issue by spidermanxyz98** [dmlc/xgboost#1539]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.
## Environment info

Operating System: Windows10 64-bit OS

Compiler: TDM-GCC-64

Package used (python/R/jvm/C++): Python

`xgboost` version used: 0.4

If installing from source, please provide: github 

The python version and distribution: Anaconda3 
## Steps to reproduce

I was following the steps from BowieHsu (https://github.com/dmlc/xgboost/issues/1316) to install xgboost on my laptop. I walked through all the steps in the instruction and it looked all good. I double checked the ~/xgboost/lib/ directory to make sure xgboost.dll was there. Also I saw xgboost-0.4-py3.5.egg-info folder in ~/Anaconda3/Lib/site-packages/ directory. It seems that I have successfully install xgboost. However, when I was trying to import xgboost in Anaconda prompt, I got an error saying "A dynamic link library (DLL) initialization routine failed":

[Anaconda3] C:\Users\sxl>python
Python 3.5.1 |Anaconda 2.5.0 (64-bit)| (default, Jan 29 2016, 15:01:46) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

> > > import xgboost as xgb
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "C:\Users\sxl\Anaconda3\lib\site-packages\xgboost-0.4-py3.5.egg\xgboost__init__.py", line 11, in <module>
> > >     from .core import DMatrix, Booster
> > >   File "C:\Users\sxl\Anaconda3\lib\site-packages\xgboost-0.4-py3.5.egg\xgboost\core.py", line 112, in <module>
> > >     _LIB = _load_lib()
> > >   File "C:\Users\sxl\Anaconda3\lib\site-packages\xgboost-0.4-py3.5.egg\xgboost\core.py", line 106, in _load_lib
> > >     lib = ctypes.cdll.LoadLibrary(lib_path[0])
> > >   File "C:\Users\sxl\Anaconda3\lib\ctypes__init__.py", line 425, in LoadLibrary
> > >     return self._dlltype(name)
> > >   File "C:\Users\sxl\Anaconda3\lib\ctypes__init__.py", line 347, in **init**
> > >     self._handle = _dlopen(self._name, mode)
> > > OSError: [WinError 1114] A dynamic link library (DLL) initialization routine failed

Any idea to solve this? Thanks!

**Comment by andreidi** [comment]
Same issue here !

**Comment by FlexDW** [comment]
I have the same issue, same versions of everything also. I tried installing an earlier version of TDM-GCC MinGW Compiler (4.8.1) because I read that it was an issue with the recent version. However, it still doesn't work.

**Comment by Lollifield** [comment]
Also same issue here, followed the steps by BowieHsu, and also tried https://www.ibm.com/developerworks/community/blogs/jfp/entry/Installing_XGBoost_For_Anaconda_on_Windows?lang=en
with no luck.
Any help would be greatly appreciated!
