### ISSUE TITLE
xgb.cv running out of memory; how much ram is needed?

### ISSUE THREAD

**Issue by vinhdizzo** [dmlc/xgboost#1541]
Hi,

I'm using xgboost (0.4-3 and 0.4-4) in R.  The system I'm running has 189GB of ram.  My `xgb.DMatrix` training object is about 23.5GB on disk.  Prior to loading the data in R, there are about 187GB of free memory:
```
$ free -g
             total       used       free     shared    buffers     cached
Mem:           189          1        187          0          0          0
-/+ buffers/cache:          1        187
Swap:            4          0          4
```

After loading the data using `xgb.DMatrix('/path/to/file')`, I have 142GB of free memory:
```
$ free -g
             total       used       free     shared    buffers     cached
Mem:           189         46        142          0          0         22
-/+ buffers/cache:         24        165
Swap:            4          0          4
```

However, when I run `xgb.cv` on the data (5-fold cross-validation), I run out of memory:
```
$ free -g
             total       used       free     shared    buffers     cached
Mem:           189        188          0          0          0          4
-/+ buffers/cache:        184          4
Swap:            4          0          4
```

I get the following error in R (xgboost 0.4-3) and then it closes out:
```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
```

For xgboost 0.4-4, memory goes to 0 but hasn't errored out yet.

Is it normal for `xgb.cv` to consume this much memory?  If so, what is the rule of thumb for the memory requirements to run `xgb.cv` for a data set of size=N GB?  Is this memory consumption specific to R?  Let me know if you have any advice.

Thank you.

**Comment by vinhdizzo** [comment]
Update: same error for xgboost 0.4-4.  Thanks.

**Comment by vinhdizzo** [comment]
I was able to increase the memory on the system to 256GB of ram.  I re-ran my `xgb.cv` code on my saved training `xgb.DMatrix` object.  I don't see free memory going to 0, but am getting the following kernel errors.  I inspected the free memory after each message.

```
Message from syslogd@my_hostname at Sep  6 10:33:48 ...
 kernel:BUG: soft lockup - CPU#0 stuck for 84s! [R:4757]

Message from syslogd@my_hostname at Sep  6 10:33:48 ...
 kernel:BUG: soft lockup - CPU#0 stuck for 84s! [R:4757]

$ free -g
             total       used       free     shared    buffers     cached
Mem:           252        236         15          0          0         33
-/+ buffers/cache:        202         49
Swap:            4          0          4

Message from syslogd@my_hostname at Sep  6 10:37:59 ...
 kernel:BUG: soft lockup - CPU#7 stuck for 93s! [R:4757]

$ free -g
             total       used       free     shared    buffers     cached
Mem:           252        237         14          0          0         33
-/+ buffers/cache:        203         48
Swap:            4          0          4

Message from syslogd@my_hostname at Sep  6 10:54:20 ...
 kernel:BUG: soft lockup - CPU#6 stuck for 82s! [R:4757]

free -g
             total       used       free     shared    buffers     cached
Mem:           252        243          8          0          0         33
-/+ buffers/cache:        210         42
Swap:            4          0          4

Message from syslogd@my_hostname at Sep  6 10:59:09 ...
 kernel:BUG: soft lockup - CPU#1 stuck for 119s! [R:4948]

Message from syslogd@my_hostname at Sep  6 10:59:09 ...
 kernel:BUG: soft lockup - CPU#4 stuck for 119s! [R:4944]

Message from syslogd@my_hostname at Sep  6 10:59:09 ...
 kernel:BUG: soft lockup - CPU#5 stuck for 119s! [R:4945]

Message from syslogd@my_hostname at Sep  6 10:59:09 ...
 kernel:BUG: soft lockup - CPU#3 stuck for 119s! [R:4946]

Message from syslogd@my_hostname at Sep  6 10:59:09 ...
 kernel:BUG: soft lockup - CPU#2 stuck for 119s! [R:4947]
```

R hasn't crashed yet.  On the R side, I haven't seen any verbose messages yet, so I assume it hasn't made it to the training routine yet.

Any thoughts?  Thanks again.

**Comment by vinhdizzo** [comment]
It appears memory did go down to 0, but training did start, despite being extremely slow (because of the lack of free memory?):
```
$ free -g
             total       used       free     shared    buffers     cached
Mem:           252        251          0          0          0         23
-/+ buffers/cache:        228         23
Swap:            4          0          4

Message from syslogd@usspesasld001 at Sep  6 11:12:18 ...
 kernel:BUG: soft lockup - CPU#6 stuck for 67s! [R:4757]

[0]     train-poisson-nloglik:0.596092+0.001590 test-poisson-nloglik:0.596198+0.006322
[1]     train-poisson-nloglik:0.592286+0.001610 test-poisson-nloglik:0.592403+0.006344
$ date
Tue Sep  6 11:50:27 CDT 2016
```

I inspected the `xgb.cv` code in R, and it appears cross-validation happens on the R side (not C side).  I guess this means the training are created another 5 times for 5-fold cross-validation.  From the first post, it appears the training data set takes up about 189-142=47 GB in memory.  This times 6 is 282 GB of ram, hence the 0 free memory.  I'm guessing the training is slow (40 minutes for one tree) because of the 0 free memory.

Is my understanding to all this about `xgb.cv` correct?  Thank you.

**Comment by AbhishekSinghVerma** [comment]
@vinhdizzo I am also R user of XGBoost. Is your `xgb.DMatrix` is dense or sparse matrix? If in case your data have lots of categorical variables then consider using `sparse.model.matrix()` from `Matrix` package than `model.matrix()`. It will save lots of memory during cross validation.

**Comment by khotilov** [comment]
The CV procedure, as implemented in both R and Python interfaces, creates all folds' train and test data at the same time and then synchronously runs boosting iterations within all the folds. That is memory wasteful, but allows to do early stopping. With just a few lines of R code you can easily create your own CV by wrapping `xgb.train` in a loop, where you would have control over resources. Or just use the CV wrappers from `caret` or `mlr`.

I thought about adding a simple and generic sequential CV method to xgboost, but in practice I was finding myself either using the current synchronous interface, or writing something custom-coded for a problem, or using the mentioned wrapper packages.

**Comment by vinhdizzo** [comment]
Thanks @khotilov for the clarification.

Thank you suggesting `caret` and `mlr` for doing CV in a more memory-efficient way, albeit at the expense of the possibility of early stopping.
