### ISSUE TITLE
[jvm-packages] Early stopping with XGBoost4J

### ISSUE THREAD

**Issue by qqilihq** [dmlc/xgboost#1544]
Is it currently possible to use early stopping with XGBoost4J? I have checked the API, but the only customizable parts beside the params `Map` seem to be `IEvaluation` and `IObjective`, and neither of them seems to do what I'm looking for.

**Comment by CodingCat** [comment]
it's not implemented yet, feel free to contribute a PR if you are interested in doing that

**Comment by fc1plusx** [comment]
+1: would be useful!
