### ISSUE TITLE
The xgboost4j jars built by 0.6 release are installed as 0.5

### ISSUE THREAD

**Issue by stickshift** [dmlc/xgboost#1550]
## Steps to reproduce
1. git clone --recursive -b v0.60 https://github.com/dmlc/xgboost
2. cd xgboost; make -j4
3. cd jvm-packages; mvn install -DskipTests

Jars installed in local Maven repo under ~/.m2/repository/ml/dmlc are 0.5 not 0.6.

**Comment by CodingCat** [comment]
yes, we forgot to update the pom.xml before release , sorry for the inconvenience

**Comment by stickshift** [comment]
I figured as much. Anyway to resolve it? Or just wait for 0.7 release?
Thanks!

Best,
Andy

**Comment by CodingCat** [comment]
you just need to update https://github.com/dmlc/xgboost/blob/master/jvm-packages/pom.xml#L9 and pom.xml files in the sub-directories
