### ISSUE TITLE
Setup Windows CI with CMake and Appveyor

### ISSUE THREAD

**Issue by tqchen** [dmlc/xgboost#1551]
Now that CMake system is inplace, I would like to call for a volunteer to help setup the Windows CI and AppVegor, so it is less likely to break things on windows build. Please reply to the issue if you are interested

**Comment by qmaruf** [comment]
I am interested though I've no previous experience on Windows CI and ApVeyor. Would really like to learn.

**Comment by tqchen** [comment]
Sounds good, you are more than welcomed to propose a PR on this

**Comment by qmaruf** [comment]
To propose a PR, I should have some basic knowledge. Any suggestion?

**Comment by headupinclouds** [comment]
I just noticed this discussion.  A fork of `xgboost` has been added to the [Hunter](https://github.com/ruslo/hunter) based package manager.  The author maintains a companion [site](https://github.com/ingenue/hunter) that runs build tests on a fairly wide range of platforms, using both [Travis CI](https://travis-ci.com) and [Appveyor](https://appveyor.com).

See:  https://github.com/ruslo/hunter/wiki/pkg.xgboost

This allows easy integration in C++ projects using a modern CMake package config interface.  To include `xgboost` in a project, you simply need to add the following lines in your CMakeLists.txt file (after a little boilerplate code that bootstraps the hunter setup), and all include file paths and library dependencies will be satisified.

```
hunter_add_package(xgboost)
find_package(xgboost CONFIG REQUIRED)
target_link_libraries(... xgboost::xgboost)
```

Travis:
https://travis-ci.org/ingenue/hunter/builds/146087074

Appveyor:
https://ci.appveyor.com/project/ingenue/hunter/build/1.0.686 

When used with the [Polly](https://github.com/ruslo/polly) toolchain repository, the `xgboost` package can be built on a number of platforms, including various flavors of: Windows, OS X, Linux, Android, iOS and Raspberry Pi.

This fork also contains some optional `boost::serialization` hooks (compile time option) which I have been using for compressed portable binary archives on mobile platforms.  Let me know if there is any interest in merging these CMake and/or boost changes upstream.  (I recall reading about a C++11 oriented refactoring that occurred shortly after this fork, so I might need to update this.)

I also have some wrapper interfaces I have been using on C++, which I will post online shortly.

Thanks for the great `xgboost` project.

**Comment by tqchen** [comment]
If possible, I would like to make the Appveyor build minimum without too much external dependencies. But it would be interesting to see if we can borrrow some of the build logic on Appveyor and setup the auto build

**Comment by headupinclouds** [comment]
Understood.  I'm happy to help with the local xgboost Appveyor file if it isn't too time critical.

> without too much external dependencies

The hunter package management mods to CMakeLists.txt can be disabled by default and enabled from the CMake command line.  (FWIW, Hunter itself is implemented entirely in CMake and the installation is bootstraped via CMake when it is enabled, so there is no real setup required.)  I will create an updated xgboost package for Hunter in the near future and can share a pointer here in case there is any interest.

**Comment by tqchen** [comment]
Sounds good, PR  is more than welcomed!
