### ISSUE TITLE
Bug in xgb.load with count:poisson objective in xgboost v0.6-0 R package?

### ISSUE THREAD

**Issue by carpenn** [dmlc/xgboost#1554]
In R xgboost v 0.6-0 I receive an error message when using the xgb.load routine having previously saved a model with the objective function count:poisson. 

Code works without error in xgboost version 0.4-4, suggesting it may be a bug?
## Environment info

R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)
`xgboost` version used: 0.6-0 (installed as per github help page instructions)
## Steps to reproduce

data(agaricus.train, package='xgboost')
data(agaricus.test, package='xgboost')
train <- agaricus.train
test <- agaricus.test
bst <- xgboost(data = train$data, label = train$label, max_depth = 2, 
               eta = 1, nthread = 2, nrounds = 2,objective = "count:poisson")
xgb.save(bst, 'xgb.model')
bst <- xgb.load('xgb.model')
## Resulting error message

Error in xgb.Booster(modelfile = modelfile) : 
  Required parameter max_delta_step of float is not presented

**Comment by tonydifranco** [comment]
I can also confirm this issue... all of the environment info is the same except that I installed xgboost from the drat repo.  when i switch back to the current cran xgboost version I do not receive the error.

**Comment by carpenn** [comment]
I can confirm that this issue is now resolved, having  compiled the latest code da2556f58a122efcf7034d955e21040843a3b8a1 and built the R package.

Many thanks to all contributors.
