### ISSUE TITLE
What is "cover" and why sometimes it is scaled down by 1e6?

### ISSUE THREAD

**Issue by zhijiang** [dmlc/xgboost#1555]
We have noticed that when the value of "cover" exceeds 1e6 it is scaled down by that number.  So in the same tree you will see cover less than 1e6 with cover less than 10 (like 5, which really should be 5e6).  What is the reason behind such downscale and if so, is there a way that can be used to make the scale consistent without relying on heuristics like if a number is less than 100 (a magic number), then it should be scaled up by 1e6?

**Comment by pommedeterresautee** [comment]
http://xgboost.readthedocs.io/en/latest/model.html
