### ISSUE TITLE
[jvm-packages] XGBoostModel  in xgboost4j-spark eval function crash

### ISSUE THREAD

**Issue by vaibhavkhanduja** [dmlc/xgboost#1556]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System:
OSX/MAC

Compiler:
Scala 10x

Package used (python/R/jvm/C++):
xgboost4j-spark

`xgboost` version used:

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`)
Latest checkout from source
2. Logs will be helpful (If logs are large, please upload as attachment).

If you are using python package, please provide

1. The python version and distribution
2. The command to install `xgboost` if you are not installing from source

If you are using R package, please provide

1. The R `sessionInfo()`
2. The command to install `xgboost` if you are not installing from source

## Steps to reproduce

1. Use the sample for spark provided as per: https://github.com/dmlc/xgboost/tree/master/jvm-packages
2.After the train is called, use eval function to get the model evaluation
 model.eval(testData, null, "error", false)

As per documentation of the eval function, a null argument would result in invoking default eval function but looking at the code it does not seem to do so. Thus a null pointer exception is received.

Further, any examples on the EvalTrait would also help.

## What have you tried?

1.
2.
3.

**Comment by CodingCat** [comment]
my mistake, will fix soon

**Comment by CodingCat** [comment]
it would be great if you can post a PR, as I'm currently working on other stuffs

**Comment by vaibhavkhanduja** [comment]
@CodingCat - When you say fix do you mean default Eval? Or just the comment?

**Comment by CodingCat** [comment]
I think fixing the comments is OK for now....

**Comment by vaibhavkhanduja** [comment]
I can do that .. 

At the same-time I was wondering if you could point me to example Eval ... python or c/c++ is find too ... I can try implementing for my use ..

**Comment by CodingCat** [comment]
you may look at https://github.com/dmlc/xgboost/blob/master/jvm-packages/xgboost4j-example/src/main/java/ml/dmlc/xgboost4j/java/example/CustomObjective.java#L118

**Comment by CodingCat** [comment]
OK, I will work on this tmr, to make it support default eval functions

**Comment by CodingCat** [comment]
resolved in https://github.com/dmlc/xgboost/pull/1574
