### ISSUE TITLE
[xgboost4j-spark][Question] More information needed for xgboost4j's distributed model

### ISSUE THREAD

**Issue by OverclockedTim** [dmlc/xgboost#1560]
Hi, I have two main questions about xgboost4j-spark's  distributed nature which I have unable determine from reading the docs and examples and would really appreciate if someone who knew could point me in the right direction:

1. What is the intended way of setting up xgboost4j-spark in a cluster such as a YARN based cluster on EMR? It appears that the xgboost4j-spark libraries access the native library through JNI, does that mean that a custom compiled version of the .so will need to be placed on every task node in the Spark cluster to be able to build the model across machines? 

2. What is the intended way of setting up xgboost4j-spark to be able to execute model predictions in a parallel way across the cluster? Is the intention that this just works so long as you have a properly partitioned RDD and the .so on every task node? Or do predictions always simply execute on the master node?

Thanks!

**Comment by CodingCat** [comment]
> What is the intended way of setting up xgboost4j-spark in a cluster such as a YARN based cluster on EMR? It appears that the xgboost4j-spark libraries access the native library through JNI, does that mean that a custom compiled version of the .so will need to be placed on every task node in the Spark cluster to be able to build the model across machines?

The native library will be compiled into jar, the only issue is that if your worker machines have different configurations, e.g. compiler version, with the machine where you compile xgboost4j-spark, you may meet some error when running the program

> What is the intended way of setting up xgboost4j-spark to be able to execute model predictions in a parallel way across the cluster? Is the intention that this just works so long as you have a properly partitioned RDD and the .so on every task node? Or do predictions always simply execute on the master node?

When you get a trained XGBoost model, say xgBoostModel, you can run local predictions through xgBoostModel.booster.prediction(...) or run parallel predictions through xgBoostModel.predict(rdd)
