### ISSUE TITLE
What does "-1.00136e-05" mean in the Tutorial document?

### ISSUE THREAD

**Issue by masonsydney** [dmlc/xgboost#1571]
Hi everybody,

I'm reading tutorials of XGBoost.
I got confusion that I don't know what does this value mean.
In the first line, there is a feature "TreatmentPlacebo", it should be a boolean type, its value is "0" or "1", but the split is "-1.00136e-05".
The "-1.00136e-05" means "0" or "1"?

## 3:              Age                     39             0.08705750         8   0.2857143

**Comment by masonsydney** [comment]
Could anybody answer me this question?

**Comment by khotilov** [comment]
It's sparse data, and gbtree algorithm treats sparse zeros as missing values. Such splits simply work as "missing" vs. "non-missing" splits.

**Comment by masonsydney** [comment]
@khotilov Thanks for your reply.
So does "-1.00136e-05" mean "non-missing" ?
In my result, I got "-1.00136e-05" too, but I cannot recognize it's true or false.
I printed out the paths of the tree, one of them is below:
"index:62" "pathID:1-0" "feature:FlagN" "Split:-1.00136e-005" "Yes:1-1" "No:1-2" "Miss:1-1" 
Does data above mean that If the condition "Flag is N" is true, go to "yes", otherwise it is False go to "No"?
Tips -> The feature "Flag" has two values (N, Y)

**Comment by masonsydney** [comment]
@khotilov In the data, it has normally path like
"index:12" "pathID:1-0" "feature:Age" "Split:45" "Yes:1-1" "No:1-2" "Miss:1-1" 
I can understand it that if condition "Age < 45" is true go to "yes", otherwise go to "No".
But I really hard to understand what "-1.00136e-05" mean.

**Comment by khotilov** [comment]
If your true and false are encoded in sparse format, gbtree would see those values as 1 and "missing", which means that when FlagN is true the split would go to No:1-2 (since it's not less than split value), and it would go to Miss:1-1 when FlagN is false.

**Comment by masonsydney** [comment]
@khotilov 
Sorry Vadim, maybe that mentioned example is incorrect.
The values of feature "Sex" are "Male" and "Female".
The data likes 
"index:62" "pathID:1-0" "feature:SexMale" "Split:-1.00136e-005" "Yes:1-1" "No:1-2" "Miss:1-1" 

How to explain the path?
If Sex == "Male" then goto "Yes" else goto "No". 
Is the understanding right?

**Comment by masonsydney** [comment]
@khotilov Thanks for your interpretation.  It is really useful for me.
