### ISSUE TITLE
Caching mechanism in UpdateSketchCol and UpdateHistCol may be useless

### ISSUE THREAD

**Issue by sdenel** [dmlc/xgboost#1580]
In src/tree/updater_histmaker.cc, UpdateSketchCol and UpdateHistCol have a "micro-caching" mechanism. Search after variable "kBuffer" to understand.
This mechanism does increase the length and the complexity of the code. Is there any evidence that it enhances the performance?

**Comment by tqchen** [comment]
yes, these improves the cache behaviour, see https://arxiv.org/abs/1603.02754

**Comment by sdenel** [comment]
@tqchen Thank you, I will read it carefully and come back to you with an answer asap.
