### ISSUE TITLE
Can anyone provide C# example?

### ISSUE THREAD

**Issue by alaeddinms** [dmlc/xgboost#1585]
Hi,

Can any one provide a C# example using the C++ dll API in C#?

Thanks,

Alaeddin

**Comment by pommedeterresautee** [comment]
Old question, no answer. Closing

**Comment by IvoTops** [comment]
http://www.picnet.com.au/blogs/guido/post/2016/12/06/introducing-xgboost-net-net-wrappers-for-the-awesome-xgboost-library/
