### ISSUE TITLE
General Documentation

### ISSUE THREAD

**Issue by tqchen** [dmlc/xgboost#159]
I am opening this issue to track the progress in general documentation improvements

List of issues
*   #158

**Comment by pommedeterresautee** [comment]
Question : what is the politic regarding demo code when a vignette explains the exact same code?

IMO, in this case, demo code is redundant, increase project complexity, not tested during compilation unlike the vignette which is generated and have therefore 0 added value to the project. So I think it should be deleted (only when 100% covered by a vignette of course).

What is your opinion?

Second question : do we have as an objective to convert all demo code to vignette? is there specific cases where demo is better?

**Comment by tqchen** [comment]
The reason why I want to keep a demo script was because the organization makes the example direction readable online from github, and directly runnable from console.

Rmarkdown seems to serve the readability issue, except that the css file could not be directly parsed by github, see https://github.com/tqchen/xgboost/blob/master/R-package/vignettes/discoverYourData.Rmd

I am open to the options, so long as the materials and links to the materials is organized and can be accessed like the organized demo page https://github.com/tqchen/xgboost/tree/master/R-package/demo

**Comment by tqchen** [comment]
Personally, I think demo and tutorial are different. 
* Tutorial (vignette) serves as introduction to new users who do not know what the toolkit can do, and want to explore
* An indexed list of demo codes are more like recipes for users who know what they want, and want to learn about a specific feature

Though the two could be combined if we can index the document carefully

**Comment by pommedeterresautee** [comment]
Something we don't have yet and would be nice for next version is a `NEWS` file for Cran like this one 
http://cran.r-project.org/web/packages/Ckmeans.1d.dp/NEWS
