### ISSUE TITLE
Not an issue per se; more of a suggestion.

### ISSUE THREAD

**Issue by Jeet1994** [dmlc/xgboost#1590]
Hello there, 

I was trying to install xgboost today on my windows computer, and God knows the hassle it was. With all the unclear instruction on its 'readthedocs' website (May be it was tough for me, but if you cannot explain it simply, why explain it at all, right?).

So, I went to see in stackoverflow and there was this guy who made everything so simple and with his step-by-step instructions, I could install and use it in no time.

Please have a look at this link : [Disco4ever's answer on installing xgboost on Windows](http://stackoverflow.com/a/35119904/3564318)

Please add this to your documentation if you see that this will make the user's life a little more simpler.

Thanks and regards.

**Comment by pommedeterresautee** [comment]
Old proposition, no answer. Closing

**Comment by Jeet1994** [comment]
I am waiting for the author's answer. :)
