### ISSUE TITLE
Different behavior on OSX vs Centos

### ISSUE THREAD

**Issue by damienrj** [dmlc/xgboost#1593]
I have been training models on both my laptop (OSX) and a server.  I have then been converting the models into PMML using https://github.com/jpmml/jpmml-sklearn and that has been working great. However when I do the same thing on my server running Centos the model trains correctly, but I can not convert the model to PMML. The error I am getting indicated that the that Booster binary object contains non-zero bytes in the "reserved" area.  Why would this happen for some OS/Architectures vs others?

**Comment by vruusmann** [comment]
Looks like you're using XGBoost `0.4` on your laptop, and XGBoost `0.6` on your server.

XGBoost `0.6` is using one int value in the "reserved" area to indicate if the `Learner` object has any attributes attached to it. The JPMML-XGBoost library has now been brought up-to-date with this change:
https://github.com/jpmml/jpmml-xgboost/commit/ec4bdc669d625dabb34fd63ae24f516d1092428c

This issue can be safely closed.

**Comment by damienrj** [comment]
I an using `6.0` on the laptop and `4.0` on the server, mostly because centos being run on the server doesn't support the required version of gcc yet that the new xgboost uses. 

That said, I will update the repo and try out the change and report back.

**Comment by damienrj** [comment]
I was now able to run the example in R at at https://github.com/jpmml/jpmml-xgboost, and did something similar in Python and both appear to convert correctly now!
