### ISSUE TITLE
[xgboost4j-spark] sparkXGBoostModel always returns 50 predictions regardless of input size

### ISSUE THREAD

**Issue by OverclockedTim** [dmlc/xgboost#1598]
I have a libsvm which I am attempting to do distributed predictions against. It is 879227 rows long. I have succesfully done predictions with my XGBoost model using both the command line and scala (non-spark) versions of the API. However, every time I try to use the spark API to execute in a distributed fashion, I get exactly 50 results back. This definitely seems like a bug to me, but it is possible that I do not understand the API?

My code:

val evalLabeledPointsRdd = MLUtils.loadLibSVMFile(sc,"/s3sync//eval.libsvm")
val evalVectorsRdd:RDD[Vector] = evalLabeledPointsRdd.map{r:LabeledPoint => r.features}
evalVectorsRdd.count
val predRdd = sparkXGBoostModel.predict(evalVectorsRdd,true)
predRdd.count

Results:

evalLabeledPointsRdd: org.apache.spark.rdd.RDD[org.apache.spark.mllib.regression.LabeledPoint] = MapPartitionsRDD[20] at map at MLUtils.scala:84
evalVectorsRdd: org.apache.spark.rdd.RDD[org.apache.spark.mllib.linalg.Vector] = MapPartitionsRDD[21] at map at <console>:119
res11: Long = 879227
predRdd: org.apache.spark.rdd.RDD[Array[Array[Float]]] = MapPartitionsRDD[22] at mapPartitions at XGBoostModel.scala:104
res12: Long = 50

Any help appreciated

**Comment by CodingCat** [comment]
@OverclockedTim , here is the reason, 

sparkXGBoostModel.predict() returns a RDD consisting of multiple partitions, each of which contains only one element. The type of this element is Array[Array[Float]] which means that the prediction result of each input entry is an Array[Float], and all inputs' results in the same partition are organized as an Array

so, 50 you see here is the number of partitions or say the number of tasks in your job....
