### ISSUE TITLE
Travis CI not finding latest xgboost version

### ISSUE THREAD

**Issue by FuriouslyCurious** [dmlc/xgboost#1602]
I have Travis CI running builds on my project, and setting up requirements which include xgboost version 0.6.  Command and output: 

```
pip install -r requirements.txt
Collecting xgboost==0.6 (from -r requirements.txt )

  Could not find a version that satisfies the requirement xgboost==0.6 (from -r requirements.txt ) (from versions: 0.4a12, 0.4a13, 0.4a14, 0.4a15, 0.4a18, 0.4a19, 0.4a20, 0.4a21, 0.4a22, 0.4a23, 0.4a24, 0.4a25, 0.4a26, 0.4a27, 0.4a28, 0.4a29, 0.4a30, 0.6a1, 0.6a2)

No matching distribution found for xgboost==0.6 (from -r requirements.txt )
```

Any ideas why Travis is not able to see xgboost 0.6?

**Comment by AbdealiJK** [comment]
https://pypi.python.org/pypi/xgboost/0.6 0.6 seems to have been either removed or never uploaded to pypi, hence it cannot be found.
https://pypi.python.org/pypi/xgboost/0.6a2 0.6a2 seems to be the current version.
