### ISSUE TITLE
Beyond random_split for time series

### ISSUE THREAD

**Issue by arevup** [dmlc/xgboost#1610]
Hi,

not sure if this is an appropriate post - if not, please excuse me.

Because of the structure in my data, a random_split does not make sense at all, as it would reveal too much information to the model that it should not have access to.

Instead, the best for our application would be to sample randomly for unique values in a certain column. This problem is well understood and we make sure not to crossvalidate parameters without paying attention to that. However, as the splitting of data seems intrinsic to the training of the model at each round, we would like to have a way to deal with that.

Would that be a reasonable goal, and what part of the implementation should we be messing with internally?

Thanks a lot for your help and the great work,

A

**Comment by khotilov** [comment]
It's not clear about what random_split you are asking here. Is it about train/test data splitting in time-series settings (if so, you can split your data however you find appropriate before feeding it into xgboost) or something else?
