### ISSUE TITLE
windows build fails

### ISSUE THREAD

**Issue by gatapia** [dmlc/xgboost#1611]
## Environment info
Operating System: Win (Windows 10 x64)
Compiler: Visual Studio 2015 / MSBuild 2015
Package used (python/R/jvm/C++): C++
1. The commit hash (`git rev-parse HEAD`) - 693ddb860eb...

### NOTE: This was working on Thursday 22nd of Sept so something on Fri-Sun broke the build.
1. git pull (get latest)
2. git submodule update (no submodule updates since last thursday)
3. Create VS solution file using: cmake.exe .. -G"Visual Studio 14 2015 Win64"
4. Rebuild using: msbuild.exe /t:Clean,Rebuild /p:Configuration=Release xgboost.sln

## What have you tried?
1. I tried using Visual Studio to build instead of MSBUild and same errors there

## Errors:
```
"c:\dev\libs\xgboost\build\xgboost.sln" (Clean;Rebuild target) (1) ->
"c:\dev\libs\xgboost\build\libxgboost.vcxproj.metaproj" (Rebuild target) (9:2) ->
"c:\dev\libs\xgboost\build\libxgboost.vcxproj" (Rebuild target) (10:2) ->
(ClCompile target) ->
  C:\dev\libs\xgboost\src\c_api\c_api.cc(268): error C2872: 'bst_ulong': ambiguous symbol [c:\dev\libs\xgboost\build
\libxgboost.vcxproj]
  C:\dev\libs\xgboost\src\c_api\c_api.cc(294): error C3016: 'i': index variable in OpenMP 'for' statement must have
signed integral type [c:\dev\libs\xgboost\build\libxgboost.vcxproj]
  C:\dev\libs\xgboost\src\c_api\c_api.cc(302): error C3016: 'i': index variable in OpenMP 'for' statement must have
signed integral type [c:\dev\libs\xgboost\build\libxgboost.vcxproj]
  C:\dev\libs\xgboost\src\c_api\c_api.cc(329): error C2872: 'bst_ulong': ambiguous symbol [c:\dev\libs\xgboost\build
\libxgboost.vcxproj]


"c:\dev\libs\xgboost\build\xgboost.sln" (Clean;Rebuild target) (1) ->
"c:\dev\libs\xgboost\build\xgboost.vcxproj.metaproj" (Rebuild target) (3:2) ->
"c:\dev\libs\xgboost\build\xgboost.vcxproj" (Rebuild target) (8:2) ->
  C:\dev\libs\xgboost\src\c_api\c_api.cc(268): error C2872: 'bst_ulong': ambiguous symbol [c:\dev\libs\xgboost\build
\xgboost.vcxproj]
  C:\dev\libs\xgboost\src\c_api\c_api.cc(294): error C3016: 'i': index variable in OpenMP 'for' statement must have
signed integral type [c:\dev\libs\xgboost\build\xgboost.vcxproj]
  C:\dev\libs\xgboost\src\c_api\c_api.cc(302): error C3016: 'i': index variable in OpenMP 'for' statement must have
signed integral type [c:\dev\libs\xgboost\build\xgboost.vcxproj]
  C:\dev\libs\xgboost\src\c_api\c_api.cc(329): error C2872: 'bst_ulong': ambiguous symbol [c:\dev\libs\xgboost\build
\xgboost.vcxproj]

    211 Warning(s)
    8 Error(s)
```

**Comment by tqchen** [comment]
@khotilov  Mind to push a fix? change bst_ulong to xgboost::bst_ulong,

change loop variable to omp_ulong, which will be defined for MSVC

**Comment by taoyizhi68** [comment]
@tqchen, just did what u said and build successed, thanks man.

**Comment by tqchen** [comment]
@taoyizhi68 can you propose a PR actually?

**Comment by khotilov** [comment]
I've pushed #1614. Let me know if that fixes the issue - I currently don't have VC++.

**Comment by taoyizhi68** [comment]
@tqchen, @khotilov I tried the PR https://github.com/dmlc/xgboost/pull/1614, and it worked fine :)

**Comment by gatapia** [comment]
Can confirm this is fixed in latest commit
