### ISSUE TITLE
The fit method in XGBRegressor (Sklearn API) doesn't support the sample_weight param

### ISSUE THREAD

**Issue by regispires** [dmlc/xgboost#1621]
The fit method in XGBRegressor (Sklearn API) doesn't support the sample_weight param.
It works in XGBClassifier, but not in XGBRegressor.
The following error occurs:

TypeError: fit() got an unexpected keyword argument 'sample_weight'

**Comment by alfredzj** [comment]
I have the same issue.. it seems we can use xgb.train instead.

**Comment by robin-lai** [comment]
i have the same issue

**Comment by paulaceccon** [comment]
Just use `scale_pos_weight`

**Comment by act5g** [comment]
I have the same isssue !

**Comment by vatsan** [comment]
Seems like the PR i submitted did not make it into the PYPI or the conda builds. If you build from source, you will have sample weight (see CL above).
