### ISSUE TITLE
Failed to write core dump. Core dumps have been disabled

### ISSUE THREAD

**Issue by universewill** [dmlc/xgboost#1625]
I run xgboost binary logistic classification on my mac book pro correctly,but get error when run multi classification.
Then i run "ulimit -c unlimited", the error remains.
My ide is idea.

--------
Here is the error:

>   
[15:41:44] 45946x55120 matrix with 4203387 entries loaded from ./data/age_aa
[15:41:44] 17188x55119 matrix with 1569941 entries loaded from ./data/age_ae
[15:41:44] dmlc-core/include/dmlc/logging.h:235: [15:41:44] src/metric/elementwise_metric.cc:28: Check failed: (preds.size()) == (info.labels.size()) label and prediction size not match, hint: use merror or mlogloss for multi-class classification
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000100d1af66, pid=3776, tid=4099
#
# JRE version: Java(TM) SE Runtime Environment (7.0_79-b15) (build 1.7.0_79-b15)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (24.79-b02 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.dylib+0x50ef66]
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/universe/Code/UserAttr/hs_err_pid3776.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#

Process finished with exit code 134

**Comment by universewill** [comment]
Here is the code:
`    val trainData = new DMatrix("./data/age_aa")
    val testData = new DMatrix("./data/age_ae")
    // define parameters
    val paramMap = List(
      "num_class" -> 4,
      "silent" -> 1,
      "eval_metric" -> "error",
      "eta" -> 0.3,
      "max_depth" ->3,
      "objective" ->"multi:softprob"
//      "objective" -> "binary:logistic"
    ).toMap
    // number of iterations
    val round = 10
    val watch = Map( "train" -> trainData, "eval" -> testData)
    // train the model
    val model = XGBoost.train(trainData, paramMap, round, watch)`

**Comment by CodingCat** [comment]
change `"eval_metric" -> "error"` to `"eval_metric" -> "merror"`

**Comment by gypsysunny** [comment]
i've run across the same issue. and i changed "eval_metric" -> "error" to "eval_metric" -> "merror", but still the same thing happened.

**Comment by gypsysunny** [comment]
sss
