### ISSUE TITLE
Why am I getting the same prediction results for all the test data?

### ISSUE THREAD

**Issue by alaeddinms** [dmlc/xgboost#1626]
Hi,

Why am I getting the same prediction results for all the test dataset?

I'm using the latest version of Python on Windows 10 and the latest code of everything. I tried both the binary classification and regression. 

My dataset is like the following but with 25,000 lines or instances:

0 1:1.346 2:1.346 3:1.34641 4:1.346 5:1.347 6:1.34731 7:0.974 8:0.673 9:1.346 10:1.346 11:1.346 12:1.346 
1 1:1.346 2:1.346 3:1.346 4:1.346 5:1.347 6:1.347 7:0.974 8:0.673 9:1.3469 10:1.346 11:1.3469 12:1.3465 
1 1:1.346 2:1.346 3:1.346 4:1.346 5:1.346 6:1.346 7:0.974 8:0.673 9:1.346 10:1.346 11:1.346 12:1.34653 

And I get results like:

0.7434511975104627
0.7434511975104627
0.7434511975104627
.
.
.

Thanks,

**Comment by khotilov** [comment]
Your examples of instances look very similar to each other. They are probably all falling into the same tree leaves.
