### ISSUE TITLE
Should python package raise MemoryError instead of std:bad_alloc?

### ISSUE THREAD

**Issue by mfeurer** [dmlc/xgboost#1629]
The python package re-raises the C++ error message in the function [_check_call in core.py](https://github.com/dmlc/xgboost/blob/master/python-package/xgboost/core.py#L115). I think it should try to map the error message to the corresponding python error message, which in this case would be the MemoryError.
## Environment info

Operating System: Ubuntu 14.04

Package used (python/R/jvm/C++): python

`xgboost` version used: xgboost==0.4a30

If you are using python package, please provide

python3.4, no distribution

pip install xgboost==0.4a30

**Comment by pommedeterresautee** [comment]
Old bug, no answer. Closing
