### ISSUE TITLE
how install xgboost in centos with gcc4.4.7

### ISSUE THREAD

**Issue by colinsongf** [dmlc/xgboost#1630]
## Environment info

Operating System:
centos 6.7
Compiler:
gcc4.4.7

Package used 
python

`xgboost` version used:0.6

i can not install devtoolset, because i am not superuser
please give me some advice about how to install xgboost python with gcc4.4.7

**Comment by khotilov** [comment]
You can check-out an older pre-mid-January version. 
Or, if feeling brave, try building a newer gcc from source.

**Comment by colinsongf** [comment]
hello, khotilov, thank you , i have installed older pre-mid-January version using gcc 4.4.7

**Comment by xydrolase** [comment]
You can download the appropriate RPMs for devtoolset, extract the RPM manually, set up the PATH and LD_LIBRARY_PATH environment variables properly. Then you can use a newer GCC to compile it.

**Comment by lockehamann** [comment]
Try:

**Comment by lockehamann** [comment]
Try:
prepare a centos 6.7 vm
install newer gcc
build xgboost with  -static-libstdc++
then you get a portable libxgboost.so
