### ISSUE TITLE
Did DMatrix initialized  with dense or sparse matrix lead to different result  

### ISSUE THREAD

**Issue by breakhearts** [dmlc/xgboost#1634]
I tried both R and python package. When i initialized DMatrix with dense

```
dmodel = xgb.DMatrix(model, label=Y.iloc[40000:].values, feature_names=dt.columns)
```

or sparse

```
dmodel = xgb.DMatrix(csc_matrix(model), label=Y.iloc[40000:].values, feature_names=dt.columns)
```

The training  accuracy is different, is that correct? And should I always use sparse matrix?

**Comment by khotilov** [comment]
> The training accuracy is different, is that correct? 

Yes. "Sparse" elements are treated as "missing" by the tree booster and as zeros by the linear booster.

> And should I always use sparse matrix?

Use whichever works better for you.

**Comment by adamwlev** [comment]
This was totally unexpected for me. Thanks for raising this @breakhearts
