### ISSUE TITLE
Is there any documentation of distributed XGBoost R package

### ISSUE THREAD

**Issue by luoruisichuan** [dmlc/xgboost#1641]
Hi, I am use xgboost R package for classification. And the dataset is very big,  I want to use xgboost R package on distributed system. Is there any documentation of distributed XGBoost R package?
I just find some documentation about how to build the  distributed system of xgboost, but have not found the corresponding R package script.

thanks for your help very much.

the following is the documentation of  distributed system of xgboost 
Distributed XGBoost YARN on AWS — xgboost 0.6 documentation  https://xgboost.readthedocs.io/en/latest/tutorials/aws_yarn.html)

**Comment by luoruisichuan** [comment]
I find some document about Distributed xgboost python training API (xgboost/tests/distributed at master · tqchen/xgboost · GitHub  https://github.com/tqchen/xgboost/tree/master/tests/distributed),
is there any document of R?
appreciate your help.
@tqchen

**Comment by khotilov** [comment]
Distributed training is not yet implemented within the R interface. 
But if you need it b/c of memory limitations and if you have a fast drive, you might try external memory processing (similar as in `demo/guide-python/external_memory.py` )

**Comment by luoruisichuan** [comment]
@khotilov thanks for your help. 
I use distributed training to improve the system computing capability especialy for large amount of dataset.
