### ISSUE TITLE
how to get the parameter importance after using Regressor.python-package

### ISSUE THREAD

**Issue by Wall-ee** [dmlc/xgboost#1643]
I was using xgboost python-package.
after  using 
xr=xgboost.XGBRegressor() 
xr.fit(x,y)

how to get the feature_importances_ of each parameter in x.
just like the method of adaboost in scikit-learn?

thanks a lot

**Comment by lopuhin** [comment]
@Wall-ee I think this issue is fixed in master, in the meantime you can use this code: https://github.com/dmlc/xgboost/blob/dd477ac903eb6f658d6fb2984763c3f8a4516389/python-package/xgboost/sklearn.py#L332

And this issue can probably be closed.

**Comment by Wall-ee** [comment]
than you ~
