### ISSUE TITLE
xgboost train's iteration AUC different from AUC of its predictions

### ISSUE THREAD

**Issue by mabbs90** [dmlc/xgboost#1648]
I have a question that I couldn't justify it for myself. The AUC value that I get from xgboost's iterations is different from the AUC value for the predictions coming from the model fit on the same data. I'd be appreciated if you can explain this to me:

```
require(xgboost)
require(pROC)

## load in the agaricus dataset
data(agaricus.train, package='xgboost')
data(agaricus.test, package='xgboost')
dtrain <- xgb.DMatrix(agaricus.train$data, label = agaricus.train$label, missing = NA)
dtest <- xgb.DMatrix(agaricus.test$data, label = agaricus.test$label, missing = NA)

param <- list(max.depth=2,
              eta=1,
              verbose = TRUE,
              objective="binary:logistic",
              eval_metric = 'auc')
nround = 5

## training the model for two rounds
bst <- xgb.train(param, dtrain, nround, nthread = 2, watchlist = list(train = dtrain))
## [0]  train-auc:0.958228
## [1]  train-auc:0.981413
## [2]  train-auc:0.997070
## [3]  train-auc:0.998757
## [4]  train-auc:0.999298

## predict using first full trees
ypred1 <- predict(bst, dtrain)
ypred1 <- ifelse(ypred1 >= 0.5, 1, 0)

auc(agaricus.train$label, ypred1)
## Area under the curve: 0.9931
```

## Environment info
Operating System: Windows 7
Package used (python/R/jvm/C++): R 
`xgboost` version used: xgboost_0.4-4

**Comment by khotilov** [comment]
AUC is supposed to be used with un-thresholded predictions, as this metric summarizes model's ability to discriminate between two classes across all the possible thresholds.

**Comment by mabbs90** [comment]
@khotilov I see! But wouldn't it kinda be misleading? because for a binary classification, you ultimately need to pick a threshold to turn the probabilities into class predictions, so for example in this case, no matter what threshold you use, you won't get the "thresholded-auc" of 0.999298. And in another question, they authors themselves said to threshold it using 0.5 if you want class-predictions. (even though it's up to us how we want to find our sweet spot between the precision and recall or FPR) 

But I completely see your point, and it totally makes sense.
