### ISSUE TITLE
Can not be install by pip. My python is 3.5

### ISSUE THREAD

**Issue by xiaoleihuang** [dmlc/xgboost#1655]
I can not install xgboost using pip. The pip is under anoconda:
/lib/python3.5/site-packages (python 3.5)

XGBoostLibraryNotFound: Cannot find XGBoost Libarary in the candicate path, did you install compilers and run build.sh in root path?
    List of candidates:
    /tmp/pip-build-2ju0xi8o/xgboost/xgboost/libxgboost.so
    /tmp/pip-build-2ju0xi8o/xgboost/xgboost/../../lib/libxgboost.so
    /tmp/pip-build-2ju0xi8o/xgboost/xgboost/./lib/libxgboost.so

The only method is python 2.*?

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-U0Frl6/xgboost/

Similar issue here #1300 

My gcc is gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-4)
Yeah... Old one, because the server is redhat...

**Comment by AbdealiJK** [comment]
I was just able to install xgboost with python 3.5

Could you specify the command you used ?
Are you using pip with the pypi server or git repo ?

My steps were:
```
git clone https://github.com/dmlc/xgboost.git
cd xgboost
git submodule init
git submodule update
cp make/minimum.mk ./config.mk
make -j4
cd python-package
pip install -e .
```

I had to use minimum.mk because I'm using a Mac.

**Comment by phunterlau** [comment]
I don't think the problem comes from python 3.5 but the old `gcc` version. Have you tried installing from `github` and see the output?  You can also try `pip install -v xgboost` for the compiling output.

**Comment by xiaoleihuang** [comment]
@phunterlau  @AbdealiJK 
Thank you for your help. Yeah... Indeed, I have an account of supercomputer resource, but no sudo permission, and their gcc version is quite out of date...
I used pip install --install-option=.... It works.

**Comment by nextofsearch** [comment]
@xiaoleihuang can you please elaborate how you solved the problem?
