### ISSUE TITLE
[jvm-packages] Executor JVM crashing when using xgboost4j-spark.

### ISSUE THREAD

**Issue by tanwanirahul** [dmlc/xgboost#1658]
## Environment info
Operating System: Ubuntu 14.04.3 LTS

Compiler: g++ (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4

Package used (python/R/jvm/C++): jvm/xgoost4j-spark

`xgboost` version used: 0.7

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`) 7ff742ebf7ec70c747f9aec004689fc727ba3304 (for exact changes, please checkout new_changes branch form https://github.com/tanwanirahul/xgboost.git )
2. Logs will be helpful (If logs are large, please upload as attachment).

## Steps to reproduce

1.  Run the XGBoost regression with the parameters - eta:0.1, objective:reg-linear, max_depth:5, subsample:0.8, round:100 with nWorkers = 12.

## What have you tried?

I have tried different JVM versions and distributions (oracle hotstop and open-jdk). The code didn't work on 1.8 and 1.7.

I am attaching the generated so file, hotspot crash report and logs. Please let me know if you would need more details on this. 

I am passing the following spark config params:

--deploy-mode cluster --conf "spark.executor.memory=40g" --conf "spark.driver.memory=16g"  --conf spark.eventLog.enabled=true --conf "spark.driver.extraJavaOptions=-Xss4096k  -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:ParallelGCThreads=2 -XX:-UseAdaptiveSizePolicy -XX:ConcGCThreads=2 -XX:-UseGCOverheadLimit  -XX:CMSInitiatingOccupancyFraction=75 -XX:NewSize=7g -XX:MaxNewSize=7g -XX:SurvivorRatio=3 -DnumPartitions=2" --conf "spark.executor.cores=6"  --num-executors 2 --conf "spark.speculation.quantile=0.5"  --conf "spark.locality.wait=0s" --conf "spark.speculation=true" --conf "spark.speculation.interval=300ms" --conf "spark.speculation.multiplier=2" --conf "spark.akka.frameSize=768" --conf "spark.driver.maxResultSize=3g" --conf "spark.executor.extraJavaOptions=-Xss10240k -XX:-UseAdaptiveSizePolicy -XX:+UseParallelGC -XX:+UseParallelOldGC -XX:ParallelGCThreads=6 -XX:NewSize=18g -XX:MaxNewSize=18g -XX:SurvivorRatio=2 -XX:+PrintAdaptiveSizePolicy -XX:+PrintGCDateStamps"

[attachements.tar.gz](https://github.com/dmlc/xgboost/files/524081/attachements.tar.gz)

**Comment by CodingCat** [comment]
I cannot reproduce it with JDK 7 + spark 2.0, 

from the log it seems that some exceptions are thrown when executing JNI code

Is the JDK version consistent among workers, driver and the machine where you compile the project?

**Comment by CodingCat** [comment]
a log in JDK 7 will also help

**Comment by tanwanirahul** [comment]
Yes, all the drivers and executors are on a single machine and the xgboost4j has been built on the same machine as well, using the same jdk,

**Comment by CodingCat** [comment]
I used almost the same environment except JDK 7, still cannot reproduce it
