### ISSUE TITLE
Support for installation using macports on OS X

### ISSUE THREAD

**Issue by saihttam** [dmlc/xgboost#1667]
In the installation guidelines and in other instructions around the web, the suggestion is to use homebrew for installing xgboost on OS X. However supporting macports should be pretty straight forward as well. 
I have been successful in installing xgboost with the following update to the Makefile, which checks when gcc-6 is not available, whether the equivalent macports version (gcc-mp-6) is available (lines 46-47 in Makefile):
`export CC = $(if $(shell which gcc-6),gcc-6,$(if $(shell which gcc-mp-6), gcc-mp-6, clang))`
`export CXX = $(if $(shell which g++-6),g++-6,$(if $(shell which g++-mp-6),g++-mp-6, clang++))`
In the installation instruction one could simply add that installing gcc-6 via maports (port gcc6) is also a viable option in that case.

**Comment by phunterlau** [comment]
@saihttam would you like to submit a PR for `Makefile` after testing and validating this idea? it would help macport users.
