### ISSUE TITLE
DMatrix to scipy.sparse or numpy.ndarray

### ISSUE THREAD

**Issue by rladeira** [dmlc/xgboost#1668]
Is it possible to convert a `DMatrix` object into a `numpy ndarray` or a `scipy.sparse` matrix?

I want to use the `fpreproc` param of `xgb.cv`, but I would need to perform this type of conversion to do anything useful.

Thanks in advance.

**Comment by pommedeterresautee** [comment]
Nope
https://github.com/dmlc/xgboost/issues/1462
