### ISSUE TITLE
Windows build not generating libxgboost.dll

### ISSUE THREAD

**Issue by gatapia** [dmlc/xgboost#1671]
## Environment info
Operating System: Windows 10
Compiler: Visual Studio 2015
`xgboost` version used: 2016-10-17 master branch

1. The commit hash (`git rev-parse HEAD`)
be90deb9b60759313a1a6e6e121209a929744c8e

Windows build succeeds but no `libxgboost.dll` is produced.  This means that `python setup.py install` also fails as this requires `libxgboost.dll`.

No errors in [build logs](http://ssl.picnet.com.au/xgboost/20161017/nightly_build_log.txt). 

**Note:** xgboost.exe is generated.

**Comment by EGQM** [comment]
I had the same problem.

**Comment by EGQM** [comment]
This is my solution. change the lines

add_executable(xgboost-bin ${SOURCES})
SET_TARGET_PROPERTIES(xgboost-bin PROPERTIES OUTPUT_NAME xgboost)
add_library(xgboost SHARED ${SOURCES})

target_link_libraries(xgboost-bin dmlccore rabit)
target_link_libraries(xgboost dmlccore rabit)

to

if(MSVC)
    add_executable(xgboost ${SOURCES})
    add_library(libxgboost SHARED ${SOURCES})

    target_link_libraries(xgboost dmlccore rabit)
    target_link_libraries(libxgboost dmlccore rabit)
else()
    add_executable(xgboost-bin ${SOURCES})
    SET_TARGET_PROPERTIES(xgboost-bin PROPERTIES OUTPUT_NAME xgboost)
    add_library(xgboost SHARED ${SOURCES})

    target_link_libraries(xgboost-bin dmlccore rabit)
    target_link_libraries(xgboost dmlccore rabit)
endif()

in the CMakeLists.txt file.

**Comment by gatapia** [comment]
@ECQM can you do a PR?  I can do one if you prefer

**Comment by EGQM** [comment]
@gatapia I have done the PR。

**Comment by tqchen** [comment]
https://github.com/dmlc/xgboost/pull/1674
