### ISSUE TITLE
Choice of parameter specification in xgb.DMatrix

### ISSUE THREAD

**Issue by mbconnor** [dmlc/xgboost#1677]
I was torn to file this under R or discussion.  Let me start off by saying xgboost is a really cool package and I've had a great time using it.

My issue is with the choice of parameter specification in xgb.DMatrix.  The choice of using a "data=" parameter that does not include the label itself is non-standard for R modeling functions.  In general, when specifying the data for modeling in an R function, "data=" implies the entire dataset that will be used.  In xgboost, "data=" implies only the feature space and not the label.

As you might expect, including the label in the data can lead to very strange results.  Worse still, it is not always obvious that the inclusion of the label in the data is causing an problems at all.  The model may fit, the label may or may not appear as an important feature depending on parameter specifications, and its very easy to continue on your way without ever noticing the problem.  There really ought to be more of a distinction made in the tutorial and help files (at the least).  In fact, I can't find anywhere where this divergence from standard syntax is mentioned.  Consider making a note of it, users of other R modeling packages will be grateful.

**Comment by pommedeterresautee** [comment]
there is a `label` parameter to include labels.
