### ISSUE TITLE
xgb.cv, prediction parameter not available in python?

### ISSUE THREAD

**Issue by haozhenWu** [dmlc/xgboost#1678]
Hi,
I am switching from xgboost R API to python API and it seems that python version does not have the option to get the prediction result from cross validation ? 
I am wondering if there is any way to achieve this in python version ?

Thank you very much.

**Comment by JoshuaC3** [comment]
This would be a very nice piece of added functionality. [Here ](http://stackoverflow.com/questions/40307635/get-out-of-fold-predictions-from-xgboost-cv-in-python/41049813?noredirect=1#comment73573400_41049813)is a github question about this. You can do this with sklearn's cvp but to have it built in to xgboost would be much more concise and would let you do other things not handled in sklearn.
