### ISSUE TITLE
[jvm-packages] Does anyone  maintain the xgboost4j-spark-0.5.jar in maven?

### ISSUE THREAD

**Issue by cnglen** [dmlc/xgboost#1680]
I found xgboost4j-spark in maven repo: 
-  3rd party: /ml/dmlc/xgboost4j-spark/0.5/xgboost4j-spark-0.5.jar

This version doesn't support missing value in train().

**Where can I get the latest version of xgboost4j-spark.jar?** 

I try to complile it myself, and I can  generate the jar file, but it doesn't work correctly.

**Comment by CodingCat** [comment]
no, it has been uploaded to maven central repo

would you provide more information about how it does not work correctly?
