### ISSUE TITLE
[jvm-packages]SparkWithDataFrame: java.lang.IllegalArgumentException: requirement failed: Column features must be of type org.apache.spark.ml.linalg.VectorUDT@3bfc3ba7 but was actually ArrayType(FloatType,true).

### ISSUE THREAD

**Issue by mindis** [dmlc/xgboost#1683]
Hi

xgboost 0.7
unmodified SparkWithDataFrame.scala

spark-submit --class ml.dmlc.xgboost4j.scala.example.spark.SparkWithDataFrame --master local[4] --driver-memory 20g xgboost4j-example-0.7-jar-with-dependencies.jar 5 5 agaricus.txt.train agaricus.txt.test model

throws error

Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: Column features must be of type org.apache.spark.ml.linalg.VectorUDT@3bfc3ba7 but was actually ArrayType(FloatType,true).
        at scala.Predef$.require(Predef.scala:224)
        at org.apache.spark.ml.util.SchemaUtils$.checkColumnType(SchemaUtils.scala:42)
        at org.apache.spark.ml.PredictorParams$class.validateAndTransformSchema(Predictor.scala:51)
        at org.apache.spark.ml.Predictor.validateAndTransformSchema(Predictor.scala:71)
        at org.apache.spark.ml.Predictor.transformSchema(Predictor.scala:116)
        at org.apache.spark.ml.PipelineStage.transformSchema(Pipeline.scala:70)
        at org.apache.spark.ml.Predictor.fit(Predictor.scala:89)
        at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainWithDataFrame(XGBoost.scala:151)
        at ml.dmlc.xgboost4j.scala.example.spark.SparkWithDataFrame$.main(SparkWithDataFrame.scala:60)
        at ml.dmlc.xgboost4j.scala.example.spark.SparkWithDataFrame.main(SparkWithDataFrame.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:729)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:185)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:210)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:124)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

Same error on cluster

full stack:

Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
16/10/19 15:59:58 INFO SparkContext: Running Spark version 2.0.0
16/10/19 15:59:58 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
16/10/19 15:59:59 INFO SecurityManager: Changing view acls to: mindaugz
16/10/19 15:59:59 INFO SecurityManager: Changing modify acls to: mindaugz
16/10/19 15:59:59 INFO SecurityManager: Changing view acls groups to:
16/10/19 15:59:59 INFO SecurityManager: Changing modify acls groups to:
16/10/19 15:59:59 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(mindaugz); groups with view permissions: Set(); users  with modify permissions: Set(mindaugz); groups with modify permissions: Set()
16/10/19 15:59:59 INFO Utils: Successfully started service 'sparkDriver' on port 33685.
16/10/19 15:59:59 INFO SparkEnv: Registering MapOutputTracker
16/10/19 15:59:59 INFO SparkEnv: Registering BlockManagerMaster
16/10/19 15:59:59 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-671ff1b7-3f7b-4b02-b998-9eb8e1626b38
16/10/19 15:59:59 INFO MemoryStore: MemoryStore started with capacity 10.5 GB
16/10/19 15:59:59 INFO SparkEnv: Registering OutputCommitCoordinator
16/10/19 16:00:00 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
16/10/19 16:00:00 INFO Utils: Successfully started service 'SparkUI' on port 4041.
16/10/19 16:00:00 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://10.128.24.65:4041
16/10/19 16:00:00 INFO SparkContext: Added JAR file:/nfs/science/globalscience/mindis/delete/xgboost/jvm-packages/xgboost4j-example/target/xgboost4j-example-0.7-jar-with-dependencies.jar at spark://10.128.24.65:33685/jars/xgboost4j-example-0.7-jar-with-dependencies.jar with timestamp 1476889200381
16/10/19 16:00:00 INFO Executor: Starting executor ID driver on host localhost
16/10/19 16:00:00 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 40546.
16/10/19 16:00:00 INFO NettyBlockTransferService: Server created on 10.128.24.65:40546
16/10/19 16:00:00 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 10.128.24.65, 40546)
16/10/19 16:00:00 INFO BlockManagerMasterEndpoint: Registering block manager 10.128.24.65:40546 with 10.5 GB RAM, BlockManagerId(driver, 10.128.24.65, 40546)
16/10/19 16:00:00 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 10.128.24.65, 40546)
16/10/19 16:00:01 INFO MemoryStore: Block broadcast_0 stored as values in memory (estimated size 107.7 KB, free 10.5 GB)
16/10/19 16:00:01 INFO MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 10.2 KB, free 10.5 GB)
16/10/19 16:00:01 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on 10.128.24.65:40546 (size: 10.2 KB, free: 10.5 GB)
16/10/19 16:00:01 INFO SparkContext: Created broadcast 0 from textFile at MLUtils.scala:99
16/10/19 16:00:02 INFO FileInputFormat: Total input paths to process : 1
16/10/19 16:00:02 INFO SparkContext: Starting job: reduce at MLUtils.scala:92
16/10/19 16:00:02 INFO DAGScheduler: Got job 0 (reduce at MLUtils.scala:92) with 2 output partitions
16/10/19 16:00:02 INFO DAGScheduler: Final stage: ResultStage 0 (reduce at MLUtils.scala:92)
16/10/19 16:00:02 INFO DAGScheduler: Parents of final stage: List()
16/10/19 16:00:02 INFO DAGScheduler: Missing parents: List()
16/10/19 16:00:02 INFO DAGScheduler: Submitting ResultStage 0 (MapPartitionsRDD[5] at map at MLUtils.scala:90), which has no missing parents
16/10/19 16:00:02 INFO MemoryStore: Block broadcast_1 stored as values in memory (estimated size 3.9 KB, free 10.5 GB)
16/10/19 16:00:02 INFO MemoryStore: Block broadcast_1_piece0 stored as bytes in memory (estimated size 2.2 KB, free 10.5 GB)
16/10/19 16:00:02 INFO BlockManagerInfo: Added broadcast_1_piece0 in memory on 10.128.24.65:40546 (size: 2.2 KB, free: 10.5 GB)
16/10/19 16:00:02 INFO SparkContext: Created broadcast 1 from broadcast at DAGScheduler.scala:1012
16/10/19 16:00:02 INFO DAGScheduler: Submitting 2 missing tasks from ResultStage 0 (MapPartitionsRDD[5] at map at MLUtils.scala:90)
16/10/19 16:00:02 INFO TaskSchedulerImpl: Adding task set 0.0 with 2 tasks
16/10/19 16:00:02 INFO TaskSetManager: Starting task 0.0 in stage 0.0 (TID 0, localhost, partition 0, PROCESS_LOCAL, 5487 bytes)
16/10/19 16:00:02 INFO TaskSetManager: Starting task 1.0 in stage 0.0 (TID 1, localhost, partition 1, PROCESS_LOCAL, 5487 bytes)
16/10/19 16:00:02 INFO Executor: Running task 0.0 in stage 0.0 (TID 0)
16/10/19 16:00:02 INFO Executor: Running task 1.0 in stage 0.0 (TID 1)
16/10/19 16:00:02 INFO Executor: Fetching spark://10.128.24.65:33685/jars/xgboost4j-example-0.7-jar-with-dependencies.jar with timestamp 1476889200381
16/10/19 16:00:02 INFO TransportClientFactory: Successfully created connection to /10.128.24.65:33685 after 40 ms (0 ms spent in bootstraps)
16/10/19 16:00:02 INFO Utils: Fetching spark://10.128.24.65:33685/jars/xgboost4j-example-0.7-jar-with-dependencies.jar to /tmp/spark-00f12da8-d8db-4e1e-90c7-ff5d68e521c9/userFiles-adb0ce66-9896-4b31-9ed8-08328bd47949/fetchFileTemp593037925043306245.tmp
16/10/19 16:00:03 INFO Executor: Adding file:/tmp/spark-00f12da8-d8db-4e1e-90c7-ff5d68e521c9/userFiles-adb0ce66-9896-4b31-9ed8-08328bd47949/xgboost4j-example-0.7-jar-with-dependencies.jar to class loader
16/10/19 16:00:03 INFO HadoopRDD: Input split: file:/nfs/science/globalscience/mindis/data/agaricus.txt.test:91805+91806
16/10/19 16:00:03 INFO HadoopRDD: Input split: file:/nfs/science/globalscience/mindis/data/agaricus.txt.test:0+91805
16/10/19 16:00:03 INFO deprecation: mapred.tip.id is deprecated. Instead, use mapreduce.task.id
16/10/19 16:00:03 INFO deprecation: mapred.tip.id is deprecated. Instead, use mapreduce.task.id
16/10/19 16:00:03 INFO deprecation: mapred.task.id is deprecated. Instead, use mapreduce.task.attempt.id
16/10/19 16:00:03 INFO deprecation: mapred.task.id is deprecated. Instead, use mapreduce.task.attempt.id
16/10/19 16:00:03 INFO deprecation: mapred.task.is.map is deprecated. Instead, use mapreduce.task.ismap
16/10/19 16:00:03 INFO deprecation: mapred.task.partition is deprecated. Instead, use mapreduce.task.partition
16/10/19 16:00:03 INFO deprecation: mapred.job.id is deprecated. Instead, use mapreduce.job.id
16/10/19 16:00:03 INFO MemoryStore: Block rdd_4_1 stored as values in memory (estimated size 271.9 KB, free 10.5 GB)
16/10/19 16:00:03 INFO BlockManagerInfo: Added rdd_4_1 in memory on 10.128.24.65:40546 (size: 271.9 KB, free: 10.5 GB)
16/10/19 16:00:03 INFO MemoryStore: Block rdd_4_0 stored as values in memory (estimated size 271.9 KB, free 10.5 GB)
16/10/19 16:00:03 INFO BlockManagerInfo: Added rdd_4_0 in memory on 10.128.24.65:40546 (size: 271.9 KB, free: 10.5 GB)
16/10/19 16:00:03 INFO Executor: Finished task 0.0 in stage 0.0 (TID 0). 1562 bytes result sent to driver
16/10/19 16:00:03 INFO Executor: Finished task 1.0 in stage 0.0 (TID 1). 1562 bytes result sent to driver
16/10/19 16:00:03 INFO TaskSetManager: Finished task 1.0 in stage 0.0 (TID 1) in 1240 ms on localhost (1/2)
16/10/19 16:00:03 INFO TaskSetManager: Finished task 0.0 in stage 0.0 (TID 0) in 1307 ms on localhost (2/2)
16/10/19 16:00:03 INFO TaskSchedulerImpl: Removed TaskSet 0.0, whose tasks have all completed, from pool
16/10/19 16:00:03 INFO DAGScheduler: ResultStage 0 (reduce at MLUtils.scala:92) finished in 1.322 s
16/10/19 16:00:03 INFO DAGScheduler: Job 0 finished: reduce at MLUtils.scala:92, took 1.704135 s
16/10/19 16:00:05 INFO SharedState: Warehouse path is 'file:/nfs/science/globalscience/mindis/delete/xgboost/jvm-packages/spark-warehouse'.
16/10/19 16:00:06 INFO MemoryStore: Block broadcast_2 stored as values in memory (estimated size 127.1 KB, free 10.5 GB)
16/10/19 16:00:06 INFO MemoryStore: Block broadcast_2_piece0 stored as bytes in memory (estimated size 14.3 KB, free 10.5 GB)
16/10/19 16:00:06 INFO BlockManagerInfo: Added broadcast_2_piece0 in memory on 10.128.24.65:40546 (size: 14.3 KB, free: 10.5 GB)
16/10/19 16:00:06 INFO SparkContext: Created broadcast 2 from textFile at MLUtils.scala:99
16/10/19 16:00:06 INFO FileInputFormat: Total input paths to process : 1
16/10/19 16:00:06 INFO SparkContext: Starting job: reduce at MLUtils.scala:92
16/10/19 16:00:06 INFO DAGScheduler: Got job 1 (reduce at MLUtils.scala:92) with 2 output partitions
16/10/19 16:00:06 INFO DAGScheduler: Final stage: ResultStage 1 (reduce at MLUtils.scala:92)
16/10/19 16:00:06 INFO DAGScheduler: Parents of final stage: List()
16/10/19 16:00:06 INFO DAGScheduler: Missing parents: List()
16/10/19 16:00:06 INFO DAGScheduler: Submitting ResultStage 1 (MapPartitionsRDD[14] at map at MLUtils.scala:90), which has no missing parents
16/10/19 16:00:06 INFO MemoryStore: Block broadcast_3 stored as values in memory (estimated size 3.9 KB, free 10.5 GB)
16/10/19 16:00:06 INFO MemoryStore: Block broadcast_3_piece0 stored as bytes in memory (estimated size 2.1 KB, free 10.5 GB)
16/10/19 16:00:06 INFO BlockManagerInfo: Added broadcast_3_piece0 in memory on 10.128.24.65:40546 (size: 2.1 KB, free: 10.5 GB)
16/10/19 16:00:06 INFO SparkContext: Created broadcast 3 from broadcast at DAGScheduler.scala:1012
16/10/19 16:00:06 INFO DAGScheduler: Submitting 2 missing tasks from ResultStage 1 (MapPartitionsRDD[14] at map at MLUtils.scala:90)
16/10/19 16:00:06 INFO TaskSchedulerImpl: Adding task set 1.0 with 2 tasks
16/10/19 16:00:06 INFO TaskSetManager: Starting task 0.0 in stage 1.0 (TID 2, localhost, partition 0, PROCESS_LOCAL, 5488 bytes)
16/10/19 16:00:06 INFO TaskSetManager: Starting task 1.0 in stage 1.0 (TID 3, localhost, partition 1, PROCESS_LOCAL, 5488 bytes)
16/10/19 16:00:06 INFO Executor: Running task 0.0 in stage 1.0 (TID 2)
16/10/19 16:00:06 INFO Executor: Running task 1.0 in stage 1.0 (TID 3)
16/10/19 16:00:06 INFO HadoopRDD: Input split: file:/nfs/science/globalscience/mindis/data/agaricus.txt.test:0+91805
16/10/19 16:00:06 INFO HadoopRDD: Input split: file:/nfs/science/globalscience/mindis/data/agaricus.txt.test:91805+91806
16/10/19 16:00:06 INFO MemoryStore: Block rdd_13_0 stored as values in memory (estimated size 271.9 KB, free 10.5 GB)
16/10/19 16:00:06 INFO BlockManagerInfo: Added rdd_13_0 in memory on 10.128.24.65:40546 (size: 271.9 KB, free: 10.5 GB)
16/10/19 16:00:06 INFO MemoryStore: Block rdd_13_1 stored as values in memory (estimated size 271.9 KB, free 10.5 GB)
16/10/19 16:00:06 INFO BlockManagerInfo: Added rdd_13_1 in memory on 10.128.24.65:40546 (size: 271.9 KB, free: 10.5 GB)
16/10/19 16:00:06 INFO Executor: Finished task 0.0 in stage 1.0 (TID 2). 1562 bytes result sent to driver
16/10/19 16:00:06 INFO Executor: Finished task 1.0 in stage 1.0 (TID 3). 1562 bytes result sent to driver
16/10/19 16:00:06 INFO TaskSetManager: Finished task 0.0 in stage 1.0 (TID 2) in 120 ms on localhost (1/2)
16/10/19 16:00:06 INFO TaskSetManager: Finished task 1.0 in stage 1.0 (TID 3) in 120 ms on localhost (2/2)
16/10/19 16:00:06 INFO TaskSchedulerImpl: Removed TaskSet 1.0, whose tasks have all completed, from pool
16/10/19 16:00:06 INFO DAGScheduler: ResultStage 1 (reduce at MLUtils.scala:92) finished in 0.126 s
16/10/19 16:00:06 INFO DAGScheduler: Job 1 finished: reduce at MLUtils.scala:92, took 0.150533 s
16/10/19 16:00:06 INFO SparkContext: Starting job: zipWithIndex at SparkWithDataFrame.scala:50
16/10/19 16:00:06 INFO DAGScheduler: Got job 2 (zipWithIndex at SparkWithDataFrame.scala:50) with 1 output partitions
16/10/19 16:00:06 INFO DAGScheduler: Final stage: ResultStage 2 (zipWithIndex at SparkWithDataFrame.scala:50)
16/10/19 16:00:06 INFO DAGScheduler: Parents of final stage: List()
16/10/19 16:00:06 INFO DAGScheduler: Missing parents: List()
16/10/19 16:00:06 INFO DAGScheduler: Submitting ResultStage 2 (MapPartitionsRDD[15] at map at MLUtils.scala:84), which has no missing parents
16/10/19 16:00:06 INFO MemoryStore: Block broadcast_4 stored as values in memory (estimated size 3.8 KB, free 10.5 GB)
16/10/19 16:00:06 INFO MemoryStore: Block broadcast_4_piece0 stored as bytes in memory (estimated size 2.1 KB, free 10.5 GB)
16/10/19 16:00:06 INFO BlockManagerInfo: Added broadcast_4_piece0 in memory on 10.128.24.65:40546 (size: 2.1 KB, free: 10.5 GB)
16/10/19 16:00:06 INFO SparkContext: Created broadcast 4 from broadcast at DAGScheduler.scala:1012
16/10/19 16:00:06 INFO DAGScheduler: Submitting 1 missing tasks from ResultStage 2 (MapPartitionsRDD[15] at map at MLUtils.scala:84)
16/10/19 16:00:06 INFO TaskSchedulerImpl: Adding task set 2.0 with 1 tasks
16/10/19 16:00:06 INFO TaskSetManager: Starting task 0.0 in stage 2.0 (TID 4, localhost, partition 0, PROCESS_LOCAL, 5494 bytes)
16/10/19 16:00:06 INFO Executor: Running task 0.0 in stage 2.0 (TID 4)
16/10/19 16:00:06 INFO BlockManager: Found block rdd_13_0 locally
16/10/19 16:00:06 INFO Executor: Finished task 0.0 in stage 2.0 (TID 4). 875 bytes result sent to driver
16/10/19 16:00:06 INFO TaskSetManager: Finished task 0.0 in stage 2.0 (TID 4) in 37 ms on localhost (1/1)
16/10/19 16:00:06 INFO TaskSchedulerImpl: Removed TaskSet 2.0, whose tasks have all completed, from pool
16/10/19 16:00:06 INFO DAGScheduler: ResultStage 2 (zipWithIndex at SparkWithDataFrame.scala:50) finished in 0.037 s
16/10/19 16:00:06 INFO DAGScheduler: Job 2 finished: zipWithIndex at SparkWithDataFrame.scala:50, took 0.069588 s
Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: Column features must be of type org.apache.spark.ml.linalg.VectorUDT@3bfc3ba7 but was actually ArrayType(FloatType,true).
        at scala.Predef$.require(Predef.scala:224)
        at org.apache.spark.ml.util.SchemaUtils$.checkColumnType(SchemaUtils.scala:42)
        at org.apache.spark.ml.PredictorParams$class.validateAndTransformSchema(Predictor.scala:51)
        at org.apache.spark.ml.Predictor.validateAndTransformSchema(Predictor.scala:71)
        at org.apache.spark.ml.Predictor.transformSchema(Predictor.scala:116)
        at org.apache.spark.ml.PipelineStage.transformSchema(Pipeline.scala:70)
        at org.apache.spark.ml.Predictor.fit(Predictor.scala:89)
        at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainWithDataFrame(XGBoost.scala:151)
        at ml.dmlc.xgboost4j.scala.example.spark.SparkWithDataFrame$.main(SparkWithDataFrame.scala:60)
        at ml.dmlc.xgboost4j.scala.example.spark.SparkWithDataFrame.main(SparkWithDataFrame.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:729)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:185)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:210)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:124)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
16/10/19 16:00:06 INFO SparkContext: Invoking stop() from shutdown hook
16/10/19 16:00:06 INFO SparkUI: Stopped Spark web UI at http://10.128.24.65:4041
16/10/19 16:00:06 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
16/10/19 16:00:06 INFO MemoryStore: MemoryStore cleared
16/10/19 16:00:06 INFO BlockManager: BlockManager stopped
16/10/19 16:00:06 INFO BlockManagerMaster: BlockManagerMaster stopped
16/10/19 16:00:06 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
16/10/19 16:00:06 INFO SparkContext: Successfully stopped SparkContext
16/10/19 16:00:06 INFO ShutdownHookManager: Shutdown hook called
16/10/19 16:00:06 INFO ShutdownHookManager: Deleting directory /tmp/spark-00f12da8-d8db-4e1e-90c7-ff5d68e521c9

**Comment by CodingCat** [comment]
it has clearly stated in the error information, you have to make the type of your feature column as Vector. you can generate it manually or with Vector Assembler
