### ISSUE TITLE
run xgboost on yarn error

### ISSUE THREAD

**Issue by zhangweijiqn** [dmlc/xgboost#1684]
Hi,
  I tried to run xgboost on yarn, but I tried many times and faild on the same problem. Can anybody help me to figure out what the problem is, the logs  from hadoop containers are: 

[10:21:01] rabit/include/rabit/./internal/../../dmlc/././logging.h:245: [10:21:01] src/io.cc:37: Please compile with DMLC_USE_HDFS=1 to use hdfs
terminate called after throwing an instance of 'dmlc::Error'
  what():  [10:21:01] src/io.cc:37: Please compile with DMLC_USE_HDFS=1 to use hdfs
## Environment info

Operating System:
ubuntu 14
Compiler:
G++
Package used (python/R/jvm/C++):
C++
`xgboost` version used:
latest
## What have you tried?
1. set USE_HDFS = 1, both make/config.conf and dmlc-core/make/config.mk

**Comment by moveforever** [comment]
The error information is :"DMLC_USE_HDFS=1 to use hdfs"
So when you compile xgboost, you fix HDFS=1 in file make/config.mk.

**Comment by zhangweijiqn** [comment]
As mentioned above, I've set USE_HDFS = 1 in both make/config.conf and dmlc-core/make/config.mk

**Comment by edwardzjl** [comment]
Have you solved your problem? I got the same one as yours.
