### ISSUE TITLE
.get_score(importance_type='gain') gives very strange results

### ISSUE THREAD

**Issue by adamwlev** [dmlc/xgboost#1688]
## Environment info

Operating System: Ubuntu
Compiler: not sure
Package used (python/R/jvm/C++): python
`xgboost` version used: v0.60

If installing from source, please provide 
1. The commit hash (`git rev-parse HEAD`) e79a803a3060bd4d75954e3a9dc2d893eb7a0a9b
2. Logs will be helpful (If logs are large, please upload as attachment). Don't have them.

If you are using python package, please provide
1. The python version and distribution. Python 2.7.12 :: Anaconda 2.4.1 (64-bit)
2. The command to install `xgboost` if you are not installing from source. Source
## Steps to reproduce
1. Not sure
   2.
   3.
## What have you tried?
1. Quite a thorough investigation
   2.
   3.

I am quite sure that .get_score(importance_type='gain') is broken. I am doing a regression problem and thought to use .get_score(importance_type='gain') because I am familiar with sklearn and I am pretty sure this is the methodology they use for feature importance. 

The trouble is that one of the most important features according to 'gain' is this one feature. I was surprised and then tried to predict with different values of the feature. To my surprise, there was no change in the predicted outcome at all. It was as if the feature was not actually important. I then checked a different measure of importance - 'weight' - and this feature was only used to split one time. In contrast the most import feature by 'weight' was used 1180 times. It seems as if the 'gain' option is broken.

**Comment by pommedeterresautee** [comment]
Old bug, no answer. Closing
