### ISSUE TITLE
Error in building xgboost in oracle linux

### ISSUE THREAD

**Issue by ShreyakTiwari** [dmlc/xgboost#1691]
Hi Team,

I am trying to build xgboost in oracle linux server 6.7 (gcc 4.8.0) by following these commands: 

git clone --recursive https://github.com/dmlc/xgboost
cd xgboost; make -j4

I am getting below error. Can you please let me know what i am missing here ? 

g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/learner.o src/learner.cc >build/learner.d
g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/logging.o src/logging.cc >build/logging.d
g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/c_api/c_api.o src/c_api/c_api.cc >build/c_api/c_api.d
g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/c_api/c_api_error.o src/c_api/c_api_error.cc >build/c_api/c_api_error.d
g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp src/c_api/c_api_error.cc -o build/c_api/c_api_error.o
g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp src/logging.cc -o build/logging.o
g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp src/c_api/c_api.cc -o build/c_api/c_api.o
g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp src/learner.cc -o build/learner.o
g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/common/common.o src/common/common.cc >build/common/common.d
g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp src/common/common.cc -o build/common/common.o
g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/data/data.o src/data/data.cc >build/data/data.d
g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp src/data/data.cc -o build/data/data.o
g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/data/simple_csr_source.o src/data/simple_csr_source.cc >build/data/simple_csr_source.d
g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp src/data/simple_csr_source.cc -o build/data/simple_csr_source.o
In file included from src/data/./sparse_page_source.h:12:0,
                 from src/data/data.cc:16:
dmlc-core/include/dmlc/threadediter.h: In lambda function:
dmlc-core/include/dmlc/threadediter.h:326:37: error: no matching function for call to ‘std::condition_variable::notify_all() const’
           consumer_cond_.notify_all();
                                     ^
dmlc-core/include/dmlc/threadediter.h:326:37: note: candidate is:
In file included from dmlc-core/include/dmlc/concurrency.h:15:0,
                 from src/data/./sparse_batch_page.h:22,
                 from src/data/data.cc:9:
/usr/local/gcc-4.8.0/include/c++/4.8.0/condition_variable:83:5: note: void std::condition_variable::notify_all() <near match>
     notify_all() noexcept;
     ^
/usr/local/gcc-4.8.0/include/c++/4.8.0/condition_variable:83:5: note:   no known conversion for implicit ‘this’ parameter from ‘const std::condition_variable_’ to ‘std::condition_variable_’
In file included from src/data/./sparse_page_source.h:12:0,
                 from src/data/data.cc:16:
dmlc-core/include/dmlc/threadediter.h:333:37: error: no matching function for call to ‘std::condition_variable::notify_all() const’
           consumer_cond_.notify_all();
                                     ^
dmlc-core/include/dmlc/threadediter.h:333:37: note: candidate is:
In file included from dmlc-core/include/dmlc/concurrency.h:15:0,
                 from src/data/./sparse_batch_page.h:22,
                 from src/data/data.cc:9:
/usr/local/gcc-4.8.0/include/c++/4.8.0/condition_variable:83:5: note: void std::condition_variable::notify_all() <near match>
     notify_all() noexcept;
     ^
/usr/local/gcc-4.8.0/include/c++/4.8.0/condition_variable:83:5: note:   no known conversion for implicit ‘this’ parameter from ‘const std::condition_variable_’ to ‘std::condition_variable_’
In file included from src/data/./sparse_page_source.h:12:0,
                 from src/data/data.cc:16:
dmlc-core/include/dmlc/threadediter.h:352:45: error: no matching function for call to ‘std::condition_variable::notify_all() const’
       if (notify) consumer_cond_.notify_all();
                                             ^
dmlc-core/include/dmlc/threadediter.h:352:45: note: candidate is:
In file included from dmlc-core/include/dmlc/concurrency.h:15:0,
                 from src/data/./sparse_batch_page.h:22,
                 from src/data/data.cc:9:
/usr/local/gcc-4.8.0/include/c++/4.8.0/condition_variable:83:5: note: void std::condition_variable::notify_all() <near match>
     notify_all() noexcept;
     ^
/usr/local/gcc-4.8.0/include/c++/4.8.0/condition_variable:83:5: note:   no known conversion for implicit ‘this’ parameter from ‘const std::condition_variable_’ to ‘std::condition_variable_’
make: **\* [build/data/data.o] Error 1
make: **\* Waiting for unfinished jobs....

**Comment by wangqi880** [comment]
i meet the same error!

system:centos
gcc:4.8

git clone --recursive https://github.com/dmlc/xgboost
cd xgboost; make -j4

error:
g++ -std=c++0x -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/data/data.o src/data/data.cc >build/data/data.d
g++ -c -std=c++0x -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -O3 -funroll-loops -msse2 -fPIC -fopenmp src/data/data.cc -o build/data/data.o
In file included from src/data/./sparse_page_source.h:12:0,
                 from src/data/data.cc:16:
dmlc-core/include/dmlc/threadediter.h: In lambda function:
dmlc-core/include/dmlc/threadediter.h:326:37: error: no matching function for call to ‘std::condition_variable::notify_all() const’
           consumer_cond_.notify_all();
                                     ^
dmlc-core/include/dmlc/threadediter.h:326:37: note: candidate is:
In file included from dmlc-core/include/dmlc/concurrency.h:15:0,
                 from src/data/./sparse_batch_page.h:22,
                 from src/data/data.cc:9:
/usr/local/include/c++/4.8.0/condition_variable:83:5: note: void std::condition_variable::notify_all() <near match>
     notify_all() noexcept;
     ^
/usr/local/include/c++/4.8.0/condition_variable:83:5: note:   no known conversion for implicit ‘this’ parameter from ‘const std::condition_variable*’ to ‘std::condition_variable*’
In file included from src/data/./sparse_page_source.h:12:0,
                 from src/data/data.cc:16:
dmlc-core/include/dmlc/threadediter.h:333:37: error: no matching function for call to ‘std::condition_variable::notify_all() const’
           consumer_cond_.notify_all();
                                     ^
dmlc-core/include/dmlc/threadediter.h:333:37: note: candidate is:
In file included from dmlc-core/include/dmlc/concurrency.h:15:0,
                 from src/data/./sparse_batch_page.h:22,
                 from src/data/data.cc:9:
/usr/local/include/c++/4.8.0/condition_variable:83:5: note: void std::condition_variable::notify_all() <near match>
     notify_all() noexcept;
     ^
/usr/local/include/c++/4.8.0/condition_variable:83:5: note:   no known conversion for implicit ‘this’ parameter from ‘const std::condition_variable*’ to ‘std::condition_variable*’
In file included from src/data/./sparse_page_source.h:12:0,
                 from src/data/data.cc:16:
dmlc-core/include/dmlc/threadediter.h:352:45: error: no matching function for call to ‘std::condition_variable::notify_all() const’
       if (notify) consumer_cond_.notify_all();
                                             ^
dmlc-core/include/dmlc/threadediter.h:352:45: note: candidate is:
In file included from dmlc-core/include/dmlc/concurrency.h:15:0,
                 from src/data/./sparse_batch_page.h:22,
                 from src/data/data.cc:9:
/usr/local/include/c++/4.8.0/condition_variable:83:5: note: void std::condition_variable::notify_all() <near match>
     notify_all() noexcept;
     ^
/usr/local/include/c++/4.8.0/condition_variable:83:5: note:   no known conversion for implicit ‘this’ parameter from ‘const std::condition_variable*’ to ‘std::condition_variable*’
make: *** [build/data/data.o] Error 1

**Comment by thirdwing** [comment]
Personally I think GCC 4.8.0 is not enough. Please upgrade your GCC.

**Comment by wuwenjie1992** [comment]
xgboost-0.6a2 use pip install same error 
change to g++-5
`which g++-5`
`export CXX=/usr/bin/g++-5`
`pip install xgboost`
