### ISSUE TITLE
Renaming of parameters

### ISSUE THREAD

**Issue by giuseppec** [dmlc/xgboost#1694]
Hi,

In http://xgboost.readthedocs.io/en/latest/parameter.html I saw that several parameters have been renamed, e.g., `num_rounds` instead of `nrounds`. 
Suggestion: You might also think of renaming `nthread` to `num_thread(s)` to be consistend. Just wanted to mention this now in order to avoid that `nthread` will be renamed later in an other version again. Parameter renamings are always a bit frustrating for other users/developers. 

Thx.

**Comment by pommedeterresautee** [comment]
Old proposition, no answer. Closing
