### ISSUE TITLE
colsample_bylevel has no effect if num_row > 2**15 and tree_method=approx

### ISSUE THREAD

**Issue by tks0123456789** [dmlc/xgboost#1699]
If num_row>2**15 and tree_method=approx, setting colsample_bylevel has no effects on results.
It produce the same tree regardless of the value of colsample_bylevel.
It should produce an error when colsample_bylevel \* num_col < 1, but didn't.

XGBoost : [016ab894](https://github.com/dmlc/xgboost/tree/016ab89484e7a6313a7de11160d0c3370fc5c35d)
OS: Ubuntu 14.04.4 LTS
Python: 2.7.6

```
import xgboost as xgb
from sklearn.datasets import make_classification

n = 2 ** 15
X, y = make_classification(n_samples=n+1, n_features=10, n_informative=5, n_redundant=5,
                           shuffle=True, random_state=123)

param = {'objective':'binary:logistic','tree_method':'approx',
         'eval_metric':'logloss','seed':123}

print('num_row:%d tree_method:%s' % (n+1, 'approx'))
dtrain = xgb.DMatrix(X, y)
for cs in [1, 0.1, 0.01]:
    print("colsample_bylevel:%.2f" % cs)
    param['colsample_bylevel'] = cs
    bst = xgb.train(param, dtrain, 1, [(dtrain, 'train')])
```

> num_row:32769 tree_method:approx
> colsample_bylevel:1.00
> [02:55:11] Tree method is selected to be 'approx'
> [02:55:11] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 116 extra nodes, 0 pruned nodes, max_depth=6
> [0]    train-logloss:0.505822
> colsample_bylevel:0.10
> [02:55:11] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 116 extra nodes, 0 pruned nodes, max_depth=6
> [0]    train-logloss:0.505822
> colsample_bylevel:0.01
> [02:55:11] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 116 extra nodes, 0 pruned nodes, max_depth=6
> [0]    train-logloss:0.505822

If num_row is 2 \* 15 or tree_method is exact, it works correctly, dirrerent trees and an error.

```
print('num_row:%d tree_method:%s' % (n, 'approx'))
dtrain = xgb.DMatrix(X[:n], y[:n])
for cs in [1, 0.1, 0.01]:
    print("colsample_bylevel:%.2f" % cs)
    param['colsample_bylevel'] = cs
    bst = xgb.train(param, dtrain, 1, [(dtrain, 'train')])
```

> num_row:32768 tree_method:approx
> colsample_bylevel:1.00
> [02:55:44] Tree method is selected to be 'approx'
> [02:55:44] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 118 extra nodes, 0 pruned nodes, max_depth=6
> [0] train-logloss:0.504609
> colsample_bylevel:0.10
> [02:55:44] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 114 extra nodes, 0 pruned nodes, max_depth=6
> [0]    train-logloss:0.546038
> colsample_bylevel:0.01
> [02:55:44] dmlc-core/include/dmlc/logging.h:235: [02:55:44] src/tree/updater_colmaker.cc:637: Check failed: (n) > (0) colsample_bylevel is too small that no feature can be included

```
print('num_row:%d tree_method:%s' % (n+1, 'exact'))
param['tree_method'] = 'exact'
dtrain = xgb.DMatrix(X, y)
for cs in [1, 0.1, 0.01]:
    print("colsample_bylevel:%.2f" % cs)
    param['colsample_bylevel'] = cs
    bst = xgb.train(param, dtrain, 1, [(dtrain, 'train')])
```

> num_row:32769 tree_method:exact
> colsample_bylevel:1.00
> [03:04:47] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 118 extra nodes, 0 pruned nodes, max_depth=6
> [0]    train-logloss:0.504607
> colsample_bylevel:0.10
> [03:04:47] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 114 extra nodes, 0 pruned nodes, max_depth=6
> [0]    train-logloss:0.546035
> colsample_bylevel:0.01
> [03:04:47] dmlc-core/include/dmlc/logging.h:235: [02:56:02] src/tree/updater_colmaker.cc:637: Check failed: (n) > (0) colsample_bylevel is too small that no feature can be included

**Comment by pommedeterresautee** [comment]
Old bug, no answer. Closing
