### ISSUE TITLE
Tracking CRAN check informations

### ISSUE THREAD

**Issue by hetong007** [dmlc/xgboost#170]
#### For commit version [ea5860d574](https://github.com/tqchen/xgboost/commit/ea5860d574126400933d0dd06f754932da99dd72):

When running `make Rpack`, `R CMD build xgboost/` will generate some `.o` files inside the tarball while they are not in the original directory `xgboost/` . So we have the following note:
```
* checking if this is a source package ... NOTE
Found the following apparent object files/libraries:
  src/src/gbm/gbm.o src/src/io/io.o src/src/tree/updater.o
  src/subtree/rabit/src/engine_empty.o src/wrapper/xgboost_wrapper.o
Object files/libraries should not be included in a source package.
```
I will try to figure out the reason and resolve it.

Another Note is
```
* checking installed package size ... NOTE
  installed size is  7.4Mb
  sub-directories of 1Mb or more:
    libs   7.0Mb
```
This is common among packages on CRAN: ftp://ftp.igh.cnrs.fr/pub/CRAN/web/checks/check_results_hanas_at_uw.edu.html. I think we put it aside first.

**Comment by hetong007** [comment]
It seems that the first NOTE is caused by some changes in cpp src. Somebody suggests me to check files like Makevars. The following references could be helpful.

[http://cran.r-project.org/doc/manuals/r-devel/R-exts.html#Compiling-in-sub_002ddirectories](http://cran.r-project.org/doc/manuals/r-devel/R-exts.html#Compiling-in-sub_002ddirectories)
[http://cran.r-project.org/doc/manuals/r-devel/R-exts.html#Configure-and-cleanup](http://cran.r-project.org/doc/manuals/r-devel/R-exts.html#Configure-and-cleanup)

@tqchen can you look into that? Thanks!

**Comment by tqchen** [comment]
This is because you R CMD install locally before and make Rpack did not manage to remove the .o during pack. I have updated the script have hopefully this will resolve the issue

**Comment by hetong007** [comment]
@tqchen Not really. I manually checked the processes before [`R CMD build xgboost`](https://github.com/tqchen/xgboost/blob/master/Makefile#L95) and there's no `.o` files.  In other words, these files are generated directly from `R CMD build`.

**Comment by tqchen** [comment]
That is strange...  I do not see the reason why cmd build will want to
generate .o files

Tianqi

On Thursday, February 12, 2015, Tong He <notifications@github.com> wrote:

> @tqchen <https://github.com/tqchen> Not really. I manually checked the
> processes before R CMD build xgboost
> <https://github.com/tqchen/xgboost/blob/master/Makefile#L95> and there's
> no .o files. In other words, these files are generated directly from R
> CMD build.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tqchen/xgboost/issues/170#issuecomment-74178135>.
>


-- 
Sincerely,
------------------------------------------------
Tianqi Chen
Computer Science & Engineering, University of Washington

**Comment by hetong007** [comment]
@tqchen I can reproduce this NOTE on my Ubuntu, CentOS and Fedora, with the following command:

```
git clone https://github.com/tqchen/xgboost && cd xgboost && make Rpack
```

**Comment by hetong007** [comment]
@tqchen I think I figure out where went wrong. It is OK now with `R CMD build --no-build-vignettes xgboost`. `R CMD build` will compile the vignette but may mistakenly compile other `.cpp` files as well.

**Comment by tqchen** [comment]
i see, can we go with --no-build-vignettes  then?

**Comment by hetong007** [comment]
#### For commit version [3adfe4ee](https://github.com/tqchen/xgboost/commit/3adfe4eedaee4dc2f66a6c018dce796b3d7e90a0):

I added the option `--no-build-vignettes`  to Makefile and got rid of the old NOTE about the compiled `.o` files.

However now I have the following new warning:

```
* checking package vignettes in ‘inst/doc’ ... WARNING
Package vignette without corresponding PDF/HTML:
   ‘xgboost.Rnw’
```

It could be solved by the idea of the example from [knitr](https://github.com/yihui/knitr/blob/7eb34104/inst/doc/Makefile). Basically it is calling `knitr` in R to precompile the vignettes and it is a workaround. Of course a direct solution from `R CMD build` is preferred. 

@pommedeterresautee Do you have any experiences on this situation? Thanks!

**Comment by hetong007** [comment]
#### For commit version [9784c471d5](https://github.com/tqchen/xgboost/commit/9784c471d580a09142f4575d26065547600bfdbb):

```
* checking R code for possible problems ... NOTE
xgb.importance: no visible binding for global variable ‘MissingNo’
xgb.importance: no visible binding for global variable ‘RealCover’
```

@pommedeterresautee Do you mind to fix it? And it would be great if you can check with `make Rpack` before opening an pull request. I will also check it before merge it next time :)

**Comment by pommedeterresautee** [comment]
Sorry, I did my best to avoid this situation but sometimes I have no access to Linux laptop to make a real check.

It is now fixed in pull request.

**Comment by hetong007** [comment]
@pommedeterresautee It is fixed, thanks.

**Comment by hetong007** [comment]
I think we are in good shapes for now, except for the issue on the `.o` files. I will 

1. Test the installation on Windows 7/Ubuntu 14.04/Fedora 20.
2. Generate vignettes and manually remove the `.o` files.
3. Submit to cran.

@pommedeterresautee please feel free to discuss any recent plan on the refinement. It is also possible to add them before the submission :)

**Comment by pommedeterresautee** [comment]
@hetong007 what do you mean by refinement? Improvement of the vignette text? I will proceed this weekend. In between, please let me know your opinion about the content of both texts.

**Comment by hetong007** [comment]
#### For commit version [8f0e99c3ce](https://github.com/tqchen/xgboost/commit/8f0e99c3ce51668374eca59e9fd5cdd69a0df4a6):

Since a vignette uses data from `vcd`, I import the entire `vcd`  package in the namespace.  Currently I have no solution for only importing the data from `vcd`, so import it entirely is a workaround.

I also removed `--no-build-vignettes` in `Makefile`. Now I think we can only take a two step strategy to make the tarball valid.

**Comment by wush978** [comment]
The `.Rbuildignore` should be the recommended way to exclude these *.o during building package tarballs as described in <http://cran.r-project.org/doc/manuals/r-release/R-exts.html#Building-package-tarballs>.

I create a file `R-package/.Rbuildignore` whose content is

```
\.o$
\.so$
\.dll$
```

After running the `make Rpack`, the tarball no longer contains the binary files even if I remove those `rm xxxx.o` in the `Makefile`. This approach is easier to maintain.

**Comment by hetong007** [comment]
@wush978 Hi Wush, Thanks for your suggestion! Now it works :)
