### ISSUE TITLE
User Error 1001: chunk-size in loop schedule must be positive

### ISSUE THREAD

**Issue by lightingghost** [dmlc/xgboost#1704]
## Environment info

Operating System:

> Windows 10

Compiler:

> Visual Studio 14 2015

Package used (python/R/jvm/C++):

> Python

If installing from source, please provide 
1. The commit hash (`git rev-parse HEAD`)

> f801c22710ac38835da3b172f8238a46a6d5708b
1. Logs will be helpful (If logs are large, please upload as attachment).

> User Error 1001: chunk-size in loop schedule must be positive

If you are using python package, please provide
1. The python version and distribution

> Python 3.5.2 :: Anaconda custom (64-bit)
1. The command to install `xgboost` if you are not installing from source

> python setup.py install
## Steps to reproduce

> using xgboost will produce the error message
## What have you tried?

1.
2.
3.

**Comment by se-l** [comment]
reporting same log for same platform / compiler. Python version 3.6.1 (64bit)
