### ISSUE TITLE
[bug][jvm-packages] inconsistent behaviour of DMatrix(filePath) and DMatrix(Iterator[LabelPoint])

### ISSUE THREAD

**Issue by CodingCat** [dmlc/xgboost#1711]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.
## Environment info

Operating System: existing in both Mac and Linux

Compiler: clang-3.9

Package used (python/R/jvm/C++): jvm and c++

`xgboost` version used: 0.6+

If installing from source, please provide 
1. The commit hash (`git rev-parse HEAD`)
2. Logs will be helpful (If logs are large, please upload as attachment).
## Steps to reproduce

the following  code snippet are used to reproduce the bug

``` scala
val map = Map("eta" -> "1", "max_depth" -> "6", "silent" -> "1",
      "objective" -> "binary:logistic")

    val model = XGBoost.train(trainingRDD, map, nWorkers = 4, round = 5)
    import DataUtils._
    val testMatrix1 = new DMatrix(testList.iterator)
    val testMatrix2 = new DMatrix(testPath)
    println(model.booster.evalSet(Array(testMatrix1), Array("test"), -1))
    println(model.booster.evalSet(Array(testMatrix2), Array("test"), -1))
```

output:

```
[-1]    test-error:0.000000
[-1]    test-error:0.518312
```

**Comment by CodingCat** [comment]
BTW, DMatrix(Iterator[LabelPoint]) exhibits the expected behavior

**Comment by CodingCat** [comment]
I am too busy to figure out what happens in DMatrix(path: String), call for contribution....

**Comment by xydrolase** [comment]
Does this issue persist in current build? 
If so I can look into it after finishing the Rabit tracker modifications.

**Comment by CodingCat** [comment]
yes, I just found it when writing some test cases....

**Comment by xydrolase** [comment]
Okay, will dive into it this week.

**Comment by damiencarol** [comment]
Same pb here :/
We made the same test with 0.40 and 0.7-SNAPSHOT
We have **differences between** `DMatrix(Iterator[LabelPoint]) ` and `new DMatrix(testPath)`

But for us, R make EXACTLY the same results as `new DMatrix(testPath)`.
We have difference but only for some cases (50K errors for 811K) .

**Comment by CodingCat** [comment]
@damiencarol  the same results as `new DMatrix(test)` or `DMatrix(Iterator[LabelPoint])`?

In my own test, `DMatrix(Iterator[LabelPoint])` shall present the correct result

**Comment by damiencarol** [comment]
nope for us. We made many tests with R environnement. And I can confirm that for us, R and `new DMatrix(test)` ar **OK**.

`DMatrix(Iterator[LabelPoint])` get use wrong results.

**Comment by CodingCat** [comment]
it's weird, in my test, DMatrix(testPath) just outputs the same results no matter what  the values of parameters are, it stays in `0.518312` for agaricus dataset

**Comment by damiencarol** [comment]
for us it's a pain in the ass. We don't understand why we have different results. I think we will switch to PMML for that pb

**Comment by CodingCat** [comment]
BTW, did you mean you test in 0.40 and still got the problematic results?

**Comment by damiencarol** [comment]
We tested in 0.40 with `DMatrix(float[] data, int nrow, int ncol)`
And we had the same wrong results as `DMatrix(Iterator[LabelPoint])` in 0.60

**Comment by CodingCat** [comment]
thanks, I will look into it

**Comment by damiencarol** [comment]
@CodingCat I could provide a part of the dataset and the model in PM if you want.

**Comment by xydrolase** [comment]
Can reproduce the difference between two constructors of `DMatrix`, but my results matched @damiencarol 's, `DMatrix(Iterator[LabelPoint])` gave a higher test-error.

**Comment by xydrolase** [comment]
Found the potential issue. 

I assume that in your example, `trainingRDD` was loaded using `MLUtils.loadLibSVMFile`.
This function, weirdly, assumes that the feature-index is one-based (and you can't change the offset.)

The LibSVM parser in `dmlc/dmlc-core` appears to assume the feature-index is zero-based.
See https://github.com/dmlc/dmlc-core/blob/bf321638b22d1d33bb36775e925f7b43b22db688/src/data/libsvm_parser.h#L71

So `DMatrix(dataPath: String)` would load a different dataset than `DMatrix(Iterator[LabelPoint])`.

I created a modified `agaricus.txt.test` by subtracting "1" from all feature index, so that feature index becomes zero based. And now the results match between two constructors.

[-1]   	test-error:0.000000
[-1]   	test-error:0.000000

In my case, my previous post reported that `DMatrix(Iterator[LabelPoint])` had higher test-error. That was because I loaded the **training dataset** using **`DMatrix(dataPath: String)`**.
So @CodingCat and @damiencarol , you got opposite results perhaps because you load training data differently.

**Comment by xydrolase** [comment]
I guess there's not much we can do here other than stating in the documentation, that `MLUtils.loadLibSVMFile` uses one-based-index, and `DMatrix(dataPath:String)` uses zero-based-index. 

Unless we copy and modify the implementation from MLUtils, and provide `XGBoost.loadLibSVMFile` with an argument `zeroBasedIndex = True`. I basically did this in our internal project to support loading LZO-compressed libsvm files.

**Comment by CodingCat** [comment]
@xydrolase Thanks for finding it out 

it seems that the standard LIBSVM format is 1-based, https://github.com/cjlin1/libsvm/blob/master/README#L64

so, let's just add warning in the comments (or more aggresively, deprecate) DMatrix(dataPath: String)....

**Comment by ungil** [comment]
In case it helps, I think #1249 may also be related to this issue.

**Comment by CodingCat** [comment]
I just found that we have identified this issue long before....while it phases out from my brain

https://github.com/dmlc/xgboost/pull/1326/files#diff-8f2ca3e1ad4875482e27430226a6160bR19
