### ISSUE TITLE
Undersampling via XGBoost (Imbalance Data)

### ISSUE THREAD

**Issue by Chroner2** [dmlc/xgboost#1717]
Hi all, I use XGBoost for a highly unbalanced Data were the Class of interest is only 2%. One of the solutions I tried (besides using the XGBoost functionalities), is to use undersampling. There are several techniques involving undersampling (i.e Random, Neighboring based). I was wondering if the XGBoost could inform which instances are regarded less informative of the majority group after X iterations, thus they could be removed and achieve relatively good results and favouring more the minority class.

**Comment by geoHeil** [comment]
Did you look at http://contrib.scikit-learn.org/imbalanced-learn/ which also supports SMOTE. It would be cool to integrate something like this into xgboost for better minority class handling.

**Comment by Chroner2** [comment]
Hello geoHeli, I agree with you, the functionalities now dealt with XGBoost are limited to the tree learning procedure. It would be nice to integrate some of these "imbalance-learn" functionalities in the XGBoost. Studies have shown on an imbalanced Data Set that they can achieve better predictions by boosting different undersampled Data instances. Possibly, in XGBoost, start with many trees on these different undersampled Data Sets and during the learning process average the scores between and process accordingly.
