### ISSUE TITLE
xgboost in sklearn pipeline

### ISSUE THREAD

**Issue by geoHeil** [dmlc/xgboost#1720]
How can the additional parameters e.g. early_stopping_rounds be passed to a sklearn pipeline in the fit step?
As `pipeline.fit(X_train, y_train, early_stopping_rounds=20, verbose=True)` will result in an error of the pipeline:
```
-- fitting xgboost pipeline
in fit_model
    pipeline.fit(X_train, y_train, early_stopping_rounds=20, verbose=True)
  File "/usr/local/lib/python3.5/site-packages/sklearn/pipeline.py", line 268, in fit
    Xt, fit_params = self._fit(X, y, **fit_params)
  File "/usr/local/lib/python3.5/site-packages/sklearn/pipeline.py", line 227, in _fit
    step, param = pname.split('__', 1)
ValueError: not enough values to unpack (expected 2, got 1)
```

Whereas these options work just fine if they are just passed directly to the xgboost estimato (without a pipeline)

**Comment by qthurier** [comment]
Did you find any workaround for that?

**Comment by moideen** [comment]
try prefixing your `fit_params` with the name of the xgboost estimator step in the pipeline, followed by two underscores. see: https://stackoverflow.com/questions/40329576/sklearn-pass-fit-parameters-to-xgboost-in-pipeline
