### ISSUE TITLE
JSON dump for trees

### ISSUE THREAD

**Issue by AbdealiJK** [dmlc/xgboost#1722]
The current "dump" format is a text file. This is neat and very useful for reading. It would be nice to also have a JSON output which is semi-readable. This helps to write a follow up script to parse the trees and do their own thing on top of that.

Currently the model binary file has the C data structures, so that's not very inter operable. For example, if I want a python script to calculate some basic thing I can't. And for the dump file, I'd need to make a parser like https://github.com/dmlc/xgboost/blob/6082184cd1ee831c2ac5e30394cd78b1714cd8c9/python-package/xgboost/core.py#L1088 - which is complicated.

JSON would help in this !

**Comment by tqchen** [comment]
Totally agree on this. I think the text dumper is a legacy issue that eventually need to be fixed by replacing it with json

**Comment by AbdealiJK** [comment]
@tqchen So does the person who implements this need to add a new option `dump_format` which can be `text` or `json` ?
Or can they replace the text dump with json dump completely ?

**Comment by tqchen** [comment]
Dump format make sense

**Comment by AbdealiJK** [comment]
Closing this as it's gotten merged.
