### ISSUE TITLE
plot_tree in very low resolution, nearly unreadable

### ISSUE THREAD

**Issue by slaughterhouse-give** [dmlc/xgboost#1725]
saving the tree results in an image of unreadably low resolution. There should be an option to specify image size or resolution.

Operating System:
linux
Compiler: GCC 4.4.6 20120305 (Red Hat 4.4.6-4)] on linux
Package used (python/R/jvm/C++):
python
`xgboost` version used:
0.4

If you are using python package, please provide

1. The python version and distribution
Python 3.3.0

## Steps to reproduce

with any trained model as bst:
 xgb.plot_tree(bst,num_trees=2)
plt.savefig('tree.png')

## What have you tried?

1. trees of different size & shape

**Comment by sakares** [comment]
Agree. however, I have worked around by using `pyplot.gcf` and set figure with inches scale. You can try it.

```
xgb.plot_tree(bst, num_trees=2)
fig = matplotlib.pyplot.gcf()
fig.set_size_inches(150, 100)
fig.save('tree.png')
```

**Comment by wenbo5565** [comment]
@sakares Thanks for sharing and this works. One thing may needs to be changed is from fig.save() to fig.savefig()
