### ISSUE TITLE
TypeError when using stratified sampling in CV

### ISSUE THREAD

**Issue by paulwasit** [dmlc/xgboost#1729]
I am trying to run this code:

```
prior = np.sum(y) / (1.*len(y))

xgb_params = {
    'seed': 0,
    'colsample_bytree': 0.7,
    'silent': 1,
    'subsample': 0.7,
    'learning_rate': 0.1,
    'objective': 'binary:logistic',
    'max_depth': 4,
    'num_parallel_tree': 1,
    'min_child_weight': 2,
    'eval_metric': 'auc',
    'base_score': prior
}

dtrain = xgb.DMatrix(train, label=y)
res = xgb.cv(xgb_params, dtrain, stratified=True)
```

This returns the following TypeError:

```
File "C:\Users\sebastien\Anaconda3\lib\site-packages\xgboost-0.6-py3.5.egg\xgboost\training.py", line 367, in cv
    cvfolds = mknfold(dtrain, nfold, params, seed, metrics, fpreproc, stratified, folds)

  File "C:\Users\sebastien\Anaconda3\lib\site-packages\xgboost-0.6-py3.5.egg\xgboost\training.py", line 239, in mknfold
    sfk = XGBStratifiedKFold(n_splits=nfold, shuffle=True, random_state=seed)

TypeError: __init__() got an unexpected keyword argument 'n_splits'
```

This only occurs with `stratified=True`. I am new to xgboost, so I am not sure if I should do something else, like using `folds` ?

I have found issue [#729](https://github.com/dmlc/xgboost/issues/729) that might be related, but I am not sure.

## Environment info
Operating System: **Windows 10**
Compiler: **MinGW**
Package used (python/R/jvm/C++): not sure what this means :/
`xgboost` version used: **0.6**
commit hash: 378eb7d7c866efec409173bee6af7bdce7554ff7
The python version and distribution: **python3.5** on **Anaconda**

**Comment by FrankRouter** [comment]
Have you installed scikit-learn package?

**Comment by paulwasit** [comment]
Yes, I have the version 0.17.1. It was bundled in the Anaconda installation.

**Comment by FrankRouter** [comment]
It's a compatible problem between scikit-learn 0.17 and 0.18. Upgrade could solve it.

**Comment by paulwasit** [comment]
Upgrade did indeed the trick. Thanks !
