### ISSUE TITLE
Distributed demo is missing steps 

### ISSUE THREAD

**Issue by finbarrtimbers** [dmlc/xgboost#1731]
## Steps to reproduce

1. Follow the steps of the distributed computing [demo](https://github.com/dmlc/xgboost/blob/84ae514d7e52e2437dbf9cfc3cbf3c7c221da90f/doc/tutorials/aws_yarn.md).

If you do this, then there are two, possibly linked, errors:
 
1. The URL will not work (i.e. if you visit the URL that `./yarn-ec2 -k mykey -i mypem.pem get-master xgboost` spits out, replacing "mykey" with the appropriate values, it does not return anything).
2. When you go to submit the job by using `dmlc-submit`, it raises an AssertionError:

 "AssertionError: Need to set HADOOP_HOME for YARN submission."

How do I fix this?

**Comment by AbdealiJK** [comment]
For the second issue, it's fairly straightforward. The HADOOP_HOME needs to be set.
If your hadoop binary is at: `/opt/apache/hadoop/hadoop/bin/hadoop` then your HADOOP_HOME is `/opt/apache/hadoop/hadoop/`

**Comment by finbarrtimbers** [comment]
While you are correct, I think that the underlying issue is that yarn-ec2 isn't installing hadoop, as yarn-ec2 script sets HADOOP_HOME. 

See this open PR for more details: https://github.com/tqchen/yarn-ec2/pull/1

**Comment by guotong1988** [comment]
We need to install hadoop by ourself ?

**Comment by finbarrtimbers** [comment]
Based on the recently merged commit from the linked PR for [`yarn-ec2`](https://github.com/tqchen/yarn-ec2/pull/1), I think that `yarn-ec2` should install hadoop for you.

**Comment by lesterlitch** [comment]
I think you have to be logged into the master node to run the submit job, where yarn-ec2 has set HADOOP_HOME.

However, for me it just hangs and never completes after 'All 2 nodes getting started'

**Comment by chrisplyn** [comment]
@lesterlitch I have same issue, did you get it fixed?
