### ISSUE TITLE
Documentation for updater_seq

### ISSUE THREAD

**Issue by AbdealiJK** [dmlc/xgboost#1732]
I notice in the gbtree.cc there is a parameter `updater_seq` which is set to `grow_colmaker,prune` by default. - https://github.com/dmlc/xgboost/blob/master/src/gbm/gbtree.cc#L43

I cannot see this in https://github.com/dmlc/xgboost/blob/master/doc/parameter.md

Is there any reason this has not been documented ? Is this not (yet) a recommended way of modifying what happens to the tree ?

For example: My specific case is I wanted to stop the pruning. By setting this config, the pruning did indeed stop. So, it seems to be a useful config to document.

**Comment by tqchen** [comment]
It was indented to be an internal parameter. But since you find it helpful to be documented, let us document this then. A PR is more than welcomed.
