### ISSUE TITLE
compilation failure after https://github.com/dmlc/xgboost/pull/1726/

### ISSUE THREAD

**Issue by i5han** [dmlc/xgboost#1736]
the source at commit hash 9c693f0f5f557b80e650a32d8f09c7d8b3ab7be9 builds fine but fails at commit hash b94fcab4dc90cfd6c0a80ac6dc3ea0ad154543a6 in windows 10 VS2015

@ 9c693f0f5f557b80e650a32d8f09c7d8b3ab7be9
![image](https://cloud.githubusercontent.com/assets/1888578/20017338/2b52f856-a2e9-11e6-91b3-eac044316091.png)

@ b94fcab4dc90cfd6c0a80ac6dc3ea0ad154543a6 
![image](https://cloud.githubusercontent.com/assets/1888578/20016975/be00e200-a2e7-11e6-88f0-314e3961a863.png)

## Environment info
Operating System:
Windows 10
Compiler:
Visual Studio 2015

`xgboost` version used:
master

1. The commit hash (`git rev-parse HEAD`)
b94fcab4dc90cfd6c0a80ac6dc3ea0ad154543a6

Steps to reproduce
1 Checkout master
2 run cmake -G"Visual Studio 14 2015 Win64"
3 open xgboost.sln in VS2015
4 run build soulution
5 build fails for xgboost and libxgboost

**Comment by AbdealiJK** [comment]
@gatapia You mentioned this has been fixed ? https://github.com/dmlc/xgboost/issues/1751#issuecomment-261139894
