### ISSUE TITLE
The xgboost.DMatrix function can not be silent by setting "silent=True"

### ISSUE THREAD

**Issue by woshizhaoheihei** [dmlc/xgboost#1742]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System: linux

Compiler: gcc

Package used (python/R/jvm/C++):

`xgboost` version used: latest

If you are using python package, please provide

1. The python version and distribution 
python 2.7

## Steps to reproduce

 I trained data by python api. However, I didnt want the function xgboost.DMatrix output anything.

## What have you tried?

1.  dtest2 = xgb.DMatrix(sys.argv[1],silent=True)
I set silent to be True.But there is info "[23:28:44] 1441x10 matrix with 11528 entries loaded from file_name". 
How can I close the output info.

**Comment by ungil** [comment]
I think it's related to this: #1216

**Comment by woshizhaoheihei** [comment]
@ungil  Yes! We are meeting the same problem.
