### ISSUE TITLE
[jvm-packages] add support of json-formatted dump model 

### ISSUE THREAD

**Issue by CodingCat** [dmlc/xgboost#1747]
A follow-up of merging of https://github.com/dmlc/xgboost/pull/1726

**Comment by xydrolase** [comment]
Is there a common specification for the JSON output? Or if the JSON-formatted in the referred PR will be the de facto format?

**Comment by xydrolase** [comment]
Never mind, the JSON dump was added to the C++ native code. I thought it was only added to the Python bindings.

**Comment by superbobry** [comment]
@CodingCat could you confirm that this is already supported?
