### ISSUE TITLE
[question] xgboost how to obtain probabilities

### ISSUE THREAD

**Issue by geoHeil** [dmlc/xgboost#1749]
How can I obtain probabilities for xgboost in order to perform a custom scoring with an != 0.5 cut-off?
I am using the sklearn wrapper`s predict_proba. Unfortunately the obtained for an objective of `binary:logistic` (e.g. XGBClassifier) do not really look like probabilities.

![](https://i.stack.imgur.com/xERKI.jpg)

**Comment by xydrolase** [comment]
It appears that you're training a classifier for binary classification. The implemetation of the `predict_proba()` method in the Python wrapper of XGBoost mimics the behavior of all classifiers implemented in sklearn, that you will get the probabilities for all classes. 

Use `clf.predict_proba(X)[:, 1]` to extract the probability that samples belong to the positive class.
