### ISSUE TITLE
Windows build broken: - error C4716: 'XGBoosterDumpModelWithFeatures': must return a value

### ISSUE THREAD

**Issue by gatapia** [dmlc/xgboost#1751]
## Environment info
Operating System: Win 10 x64
Compiler: VS 2015
`xgboost` version used: HEAD as of 2016-11-09 (broken since 2016-11-06)

If installing from source, please provide 
1. The commit hash (`git rev-parse HEAD`): 91b75f9b41ac2c8f4d591997518937ceeddf0817
2. Logs will be helpful (If logs are large, please upload as attachment).
Build logs http://ssl.picnet.com.au/xgboost/20161109/nightly_build_log.txt

## Steps to reproduce

1. git pull 
2. compile with VS 2015

## What have you tried?
1. praying

**Comment by EGQM** [comment]
It seems like that no one fixes this bug.

**Comment by i5han** [comment]
i have also reported the same issue

https://github.com/dmlc/xgboost/issues/1736

**Comment by gatapia** [comment]
This is now fixed (has been for a few days)
