### ISSUE TITLE
[jvm-packages] xgboost4j prediction Cached DMatrix entries

### ISSUE THREAD

**Issue by qingpingswiftsword** [dmlc/xgboost#1754]
I found that,  Cached DMatrix. What is a cached Dmatrix?  Why prediction could be fast?

/**
   * Create a new Booster with empty stage.
   *
   * @param params  Model parameters
   * @param cacheMats Cached DMatrix entries,
   *                  the prediction of these DMatrices will become faster than not-cached data.
   * @throws XGBoostError native error
   */
  Booster(Map<String, Object> params, DMatrix[] cacheMats) throws XGBoostError {
    init(cacheMats);
    setParam("seed", "0");
    setParams(params);
  }

**Comment by CodingCat** [comment]
look at here https://github.com/dmlc/xgboost/blob/b94fcab4dc90cfd6c0a80ac6dc3ea0ad154543a6/src/gbm/gbtree.cc#L227

**Comment by qingpingswiftsword** [comment]
Could you explain more details?

**Comment by qingpingswiftsword** [comment]
Before I read the code you recommended, I guessed that there is a cached dmatrix having the already known result. Only if the input sample is not in the cached dmatrix, we use the real predicition. Am I right? After I read the code, I think so.

**Comment by AbdealiJK** [comment]
Seems like that's true.

https://github.com/dmlc/xgboost/blob/b94fcab4dc90cfd6c0a80ac6dc3ea0ad154543a6/src/gbm/gbtree.cc#L129 shows the cached data structure.
