### ISSUE TITLE
[jvm-packages] UnsatisfiedLinkError in windows

### ISSUE THREAD

**Issue by razhong** [dmlc/xgboost#1755]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System:
windows server 2012

Compiler:
built libxgboost using visual studio version 12.
built jars using mvn
Package used (python/R/jvm/C++):java

`xgboost` version used:  source

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`)
$ git rev-parse HEAD
91b75f9b41ac2c8f4d591997518937ceeddf0817

2. Logs will be helpful (If logs are large, please upload as attachment).
Exception in thread "main" java.lang.UnsatisfiedLinkError: ml.dmlc.xgboost4j.java.XGBoostJNI.XGDMatrixCreateFromFile(Ljava/lang/String;I[J)I
	at ml.dmlc.xgboost4j.java.XGBoostJNI.XGDMatrixCreateFromFile(Native Method)
	at ml.dmlc.xgboost4j.java.DMatrix.<init>(DMatrix.java:83)
	at BasicWalkThrough.main(BasicWalkThrough.java:39)

If you are using python package, please provide

1. The python version and distribution
2. The command to install `xgboost` if you are not installing from source

If you are using R package, please provide

1. The R `sessionInfo()`
2. The command to install `xgboost` if you are not installing from source

## Steps to reproduce

1. download source and compile share lib in visual studio. copy lib to "jvm-packages\xgboost4j\src\main\resources\lib\"
2. build jvm package 
    mvn clean package -D skipTests -Dcheckstyle.skip=true
3. build and run BasicWalkThrough

## What have you tried?

1. tried the same steps today in mac and it worked
2.
3.

**Comment by CodingCat** [comment]
`UnsatisfiedLinkError ` means that your native library hasn't been built correctly, you may want to check what happened during native library compilation
