### ISSUE TITLE
[xgboost4j] how to integrate xgboost in spark pipeline?

### ISSUE THREAD

**Issue by geoHeil** [dmlc/xgboost#1758]
Xgboost4j`s api seems to be different than what ml usually would expect e.g. transform instead of predict for a dataset. 
How can I nontheless integrate xgboost4j into a spark-ml pipeline?
http://stackoverflow.com/questions/40522665/xgboost4j-spark-evaluate-requires-rdddouble-double

**Comment by CodingCat** [comment]
xgboost4j is just the java/scala wrapper of xgboost, to integrate with pipeline, you need to refer to xgboost4j-spark, see examples in https://github.com/dmlc/xgboost/blob/master/jvm-packages/xgboost4j-example/src/main/scala/ml/dmlc/xgboost4j/scala/example/spark/SparkModelTuningTool.scala
