### ISSUE TITLE
Error in xgb.DMatrix in R-package

### ISSUE THREAD

**Issue by nitingupta2** [dmlc/xgboost#1762]
xgb.DMatrix fails when label is passed.

```
> library(xgboost)
> data(agaricus.train, package='xgboost')
> train <- agaricus.train
> dtrain <- xgb.DMatrix(train$data, label=train$label)
Error in .Call("XGDMatrixNumCol_R", x, PACKAGE = "xgboost") : 
  "XGDMatrixNumCol_R" not available for .Call() for package "xgboost"

```

## Environment info
Operating System: Windows 10

Package used (python/R/jvm/C++): R-package

`xgboost` version used: 0.6

If you are using R package, please provide

1. The R `sessionInfo()`
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] xgboost_0.6-0

loaded via a namespace (and not attached):
[1] magrittr_1.5     Matrix_1.2-7.1   tools_3.3.2      stringi_1.1.2    grid_3.3.2       data.table_1.9.6 chron_2.3-47    
[8] lattice_0.20-34 

2. The command to install `xgboost` if you are not installing from source
After git cloning steps:
devtools::install('xgboost/R-package')

## Steps to reproduce
library(xgboost)
data(agaricus.train, package='xgboost')
train <- agaricus.train
dtrain <- xgb.DMatrix(train$data, label=train$label)

## What have you tried?
xgb.DMatrix doesn't give an error if label parameter is removed

**Comment by khotilov** [comment]
Somehow you seem to have an old xgboost.dll shared library packaged together with the new code. Try either to clean the old binaries and reinstall r-package, or clone and reinstall from scratch.

**Comment by nitingupta2** [comment]
Reinstalling from within R itself solved the problem. Thanks!
