### ISSUE TITLE
[jvm-packages] xgboost scoring parameter

### ISSUE THREAD

**Issue by geoHeil** [dmlc/xgboost#1763]
Generally, xgboost performs a 50% cut-off in case of binary classification. Is there a possibility to pass this cut-off as a configuration parameter to xgboost?

xgboost4j lets me obtain nice probabilities for both classes. It would be very convenient if the integrated scoring could be parameterized.
```
+-----+--------------------+--------------------+----------+
|label|            features|       probabilities|prediction|
+-----+--------------------+--------------------+----------+
|  0.0|[0.0,1.0,0.0,476....|[0.96766251325607...|       0.0|
|  0.0|[0.0,1.0,0.0,642....|[0.99599152803421...|       0.0|
```

**Comment by CodingCat** [comment]
for now, you can set `thresholds` parameter to scale the probabilities

**Comment by geoHeil** [comment]
How can I set the threshold via `XGBestimator`? getThresholds is only available in `XGBoostClassificationModel`
http://dmlc.ml/docs/scaladocs/xgboost4j-spark/index.html#ml.dmlc.xgboost4j.scala.spark.XGBoostEstimator

I would like to use xgboost4j in a pipeline and set different cut-off values for scoring.

**Comment by CodingCat** [comment]
You cannot set it via an estimator because this is essentially not a parameter belong to an estimator, whose responsibility is just to produce a model. 

regarding the pipeline, Spark ML package only supports produce models by calling fit() method of an estimator with different parameter combinations. 

The only way for you to tune a parameter  like this `in a pipeline` is to write a wrapper of Spark ML tuning tools like CrossValidator as well as the evaluators which evaluate based on the scaled probabilities 

A much simpler way for you is to discard the pipeline and do something like the following:

```scala

val xgbModel = xgbEstimator.fit(train)

for (thresholds <-thresholdsCandidates) {
   xgbModel.setThresholds(thresholds)
   val predResult = xgbModel.transform(testSet)
   evaluator.eval(predResult)
}
```

**Comment by geoHeil** [comment]
Thanks. I will go with that approach.

**Comment by geoHeil** [comment]
However, your suggestion `xgbModel.setThresholds(thresholds)` does not work, as the thresholds are not available to me / scalac cannot compile it.
It seems that only `loadModelFromHadoopFile` has access to it.

**Comment by CodingCat** [comment]
what do you mean by thresholds are not available to you?

**Comment by geoHeil** [comment]
![simplexgboost_scala_-_neverpayers_-____dropbox_masterthesis_thesis_researchcode_neverpayers__-_intellij_idea_2016_3_eap](https://cloud.githubusercontent.com/assets/1694964/20223205/be8f20c8-a838-11e6-9249-9e75d467837f.jpg)

I mean that the compiler tells me that I cannot resolve symbol setThresholds for the XGBoostModel.

**Comment by CodingCat** [comment]
fit() returns the base type of XGBoostRegressionModel and XGBoostClassificationModel

the only thing you need to do is to convert it

```scala
val clsModel = xgbModel.asInstance[XGBoostClassificationModel]
```

**Comment by geoHeil** [comment]
Thanks for pointing that out. Do I understand correctly, that this:
`Seq(0.2, 0.3, 0.4, 0.6, 0.7, 0.8)`
is wrong and I would need to set it to
`Array(Seq(0.2, 0.2, 0.2, 0.2, 0.2, 0.2), Seq(0.3, 0.3, 0.3, 0.3, 0.3, 0.3))` where the length of a `Seq` would be the length of all the records e.g. an individual weithght per record?

**Comment by CodingCat** [comment]
something like `Array(Array(0.2, 0.8), Array(0.4, 0.6))` is correct, the length of the nested array is the number of classes

**Comment by geoHeil** [comment]
Thank you very much.

**Comment by CodingCat** [comment]
`Array(Array(0.2, 0.8), Array(0.4, 0.6))` is the example of thresholdsCandidates

**Comment by geoHeil** [comment]
In case XGBEstimator is used in a pipeline / crossvalidation the code above will result in org.apache.spark.ml.tuning.CrossValidatorModel cannot be cast to `ml.dmlc.xgboost4j.scala.spark.XGBoostClassificationModel`. In case of crossvalidation the pipeline can be obtained via `cv.bestModel`, but how can I get hold of the estimator which is the last step in the pipeline?

**Comment by CodingCat** [comment]
all the provided code are just examples, in another word, they are partially pseudocode , so you need to make some minor adjustment to them 

You can read http://spark.apache.org/docs/latest/api/scala/index.html#org.apache.spark.ml.tuning.CrossValidatorModel, there is a method named `getEstimator`

**Comment by geoHeil** [comment]
Thanks again for that hint.
