### ISSUE TITLE
[windows] make fails

### ISSUE THREAD

**Issue by GubanovSergey** [dmlc/xgboost#1766]
## Environment info
Operating System:
windows 8.1
Compiler:
i386-pc-mingw32 (from git shell)

The commit hash (`git rev-parse HEAD`)
b9a9d2bf45010bd267a870df9ec02874385378e0
Logs will be helpful (If logs are large, please upload as attachment).
...
>cp make/mingw64.mk config.mk
>make
g++ -m64 -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-c
ore/include -Irabit/include -fopenmp -MM -MT build/learner.o src/learner.cc >build/learner.d
      0 [main] sh 4172 sync_with_child: child 1728(0x160) died before initialization with status code 0xC0000142
    373 [main] sh 4172 sync_with_child: *** child state waiting for longjmp
/usr/bin/sh: fork: Resource temporarily unavailable
make: *** [build/learner.o] Error 128

**Comment by AbdealiJK** [comment]
Seems like this is a windows and system specific issue:

http://stackoverflow.com/questions/7767573/git-8728-fork-child-1-died-waiting-for-longjmp-before-initial#8476532

There seems to be an issue with the msys/mingw from git. Apparently replacing the `msys-1.0.dll` fixes it ... http://web.archive.org/web/20130523160129/http://code.google.com/p/msysgit/issues/detail?id=122

Possibly updating the git installation will fix it. Or continue the discussion on git bug tracker ?
