### ISSUE TITLE
'predict' is not an exported object

### ISSUE THREAD

**Issue by larry77** [dmlc/xgboost#1777]
Dear All,
I try to use xgboost (R package) from either the caret or the xgboost framework.
Right now, there are some tiny issues (on the xgboost side, in my understanding) that make my life very hard.
See 
https://github.com/mlr-org/mlr/issues/1264

Essentially, there are problems to run an xgboost simulation with a stopping condition under mlr (under caret I have similar problems).
The development version of xgboost somehow fixes the watchlist problem, but then the simulation crashes because 'predict' is not exported.
Anything which can be done on your side to fix this?
Many thanks

Lorenzo

**Comment by dimagor** [comment]
I ran into the same issue with the github version. 
My current solution is to explicitly call ```xgboost::predict()```

**Comment by larry77** [comment]
OK, but can you be a bit more explicit and maybe provide an example using also mlr? Right not, predict is called by mlr under the hood in my original example.

**Comment by khotilov** [comment]
See https://github.com/mlr-org/mlr/issues/935#issuecomment-264530385, https://github.com/mlr-org/mlr/issues/1264#issuecomment-265062656
