### ISSUE TITLE
Is there any relation between nWorkers of rabit and executors of spark?

### ISSUE THREAD

**Issue by FanBit** [dmlc/xgboost#1779]
Using the xgboost on spark, I usually have to set the parameters of nWorkers of rabit and executors of spark. Is there any relation between them? 
For example, if the nWorkers param is set to be 100, then the executors should be 100, too?
Is the definition of worker in rabit the same as executor in spark?

**Comment by xydrolase** [comment]
`nWorker` is basically the number of distributed/parallel workers. Your dataset will be repartitioned into `nWorker` parts, and each worker trains on its own part. Finally, Rabit uses `Allreduce` to combine and synchronize between workers.

In terms of executors, it depends on the configurations.

 - `spark.executor.cores` controls how many cores each executor has
 - `spark.task.cpus` controls how many CPUs each task can use.

If you have 12 cores for an executor, and allocate 3 CPUs for each task, then within each executor you will have 4 tasks. Therefore in total you need 25 executors to make up for the 100 workers.

**Comment by xydrolase** [comment]
Of course in order to maximize the efficiency and utilize all the resources, set `nthread` to match `spark.task.cpus` so that within each task, the training is conducted in parallel.
