### ISSUE TITLE
[jvm-packages] XGBOOST4j JAR PACKAGE in LOCAL MAC OS , PUBLISH IN A LINUX MACHINE

### ISSUE THREAD

**Issue by qingpingswiftsword** [dmlc/xgboost#1782]
Is anyone know something about the problem of jar package in local mac os, then run in a linux machine? I encountered some problems with it. 
Caused by: java.lang.UnsatisfiedLinkError: ml.dmlc.xgboost4j.java.XGBoostJNI.XGBoosterCreate([J[J)I
       at ml.dmlc.xgboost4j.java.XGBoostJNI.XGBoosterCreate(Native Method)
       at ml.dmlc.xgboost4j.java.Booster.init(Booster.java:419)
       at ml.dmlc.xgboost4j.java.Booster.<init>(Booster.java:57)
       at ml.dmlc.xgboost4j.java.Booster.loadModel(Booster.java:72)
       at ml.dmlc.xgboost4j.java.XGBoost.loadModel(XGBoost.java:41)
       at com.dianping.credit.xgboost.XgboostPrediction.init(XgboostPrediction.java:24)
       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
       at

**Comment by CodingCat** [comment]
in general, you cannot build in mac and run in linux, because XGBoost4J will adjust suffix of the native lib file based on your OS

you can adjust the build script to workaround it

**Comment by CodingCat** [comment]
https://github.com/dmlc/xgboost/blob/master/jvm-packages/create_jni.sh#L13

set it to 'so'

**Comment by qingpingswiftsword** [comment]
Thanks a lot!

**Comment by qingpingswiftsword** [comment]
I changed the suffix into .so  however, still failed.

**Comment by CodingCat** [comment]
Are you sure the native lib was successfully compiled? Or say can you see a .so file in the jar?

**Comment by qingpingswiftsword** [comment]
Have you ever succeed? 
Tests in error: 
 BoosterImplTest.saveLoadModelWithPath:119 » UnsatisfiedLink ml.dmlc.xgboost4j....
 BoosterImplTest.saveLoadModelWithStream:137 » UnsatisfiedLink ml.dmlc.xgboost4...
 BoosterImplTest.testBoosterBasic:103 » UnsatisfiedLink ml.dmlc.xgboost4j.java....
 BoosterImplTest.testCV:162 » UnsatisfiedLink ml.dmlc.xgboost4j.java.XGBoostJNI...
 DMatrixTest.testCreateFromCSC:130 » UnsatisfiedLink ml.dmlc.xgboost4j.java.XGB...
 DMatrixTest.testCreateFromCSCEx:155 » UnsatisfiedLink ml.dmlc.xgboost4j.java.X...
 DMatrixTest.testCreateFromCSR:84 » UnsatisfiedLink ml.dmlc.xgboost4j.java.XGBo...
 DMatrixTest.testCreateFromCSREx:106 » UnsatisfiedLink ml.dmlc.xgboost4j.java.X...
 DMatrixTest.testCreateFromDataIterator:49 » UnsatisfiedLink ml.dmlc.xgboost4j....
 DMatrixTest.testCreateFromDenseMatrix:184 » UnsatisfiedLink ml.dmlc.xgboost4j....
 DMatrixTest.testCreateFromDenseMatrixWithMissingValue:223 » UnsatisfiedLink ml...
 DMatrixTest.testCreateFromFile:60 » UnsatisfiedLink ml.dmlc.xgboost4j.java.XGB...

Tests run: 12, Failures: 0, Errors: 12, Skipped: 0

**Comment by CodingCat** [comment]
Yes

**Comment by qingpingswiftsword** [comment]
But how to understand the error here?

**Comment by CodingCat** [comment]
As i asked, can you see a so file in jar?

**Comment by qingpingswiftsword** [comment]
we fail to Building xgboost4j 0.7 ,no jar package at all.

**Comment by CodingCat** [comment]
Ok, check the log before the test , there was sth wrong when compiling native lib,

**Comment by yangzhongj** [comment]
always failed , I will cry

**Comment by superbobry** [comment]
@yangzhongj can you please open a new issue if you're facing difficulties compiling xgboost4j. The compilation pipeline has been reworked a couple of months ago.
