### ISSUE TITLE
import xgboost OSError:version `GOMP_4.0' not found

### ISSUE THREAD

**Issue by yinshurman** [dmlc/xgboost#1786]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
compiled successfully,
anaconda envirnment ,
and  use "conda list"  can show "xgboost " .

but when import xgboost show the error: OSError: /home/yin/anaconda3/bin/../lib/libgomp.so.1: version `GOMP_4.0' not found (required by /home/yin/anaconda3/lib/python3.5/site-packages/xgboost-0.6-py3.5.egg/xgboost/libxgboost.so)

Operating System: Ubunutu kylin 16.10

Compiler:

Package used (python/R/jvm/C++): python

`xgboost` version used: latest

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`)
2. Logs will be helpful (If logs are large, please upload as attachment).

OSError: /home/yin/anaconda3/bin/../lib/libgomp.so.1: version `GOMP_4.0' not found (required by /home/yin/anaconda3/lib/python3.5/site-packages/xgboost-0.6-py3.5.egg/xgboost/libxgboost.so)

If you are using python package, please provide:

anaconda

1. The python version and distribution:  python 3.5.2
2. The command to install `xgboost` if you are not installing from source

If you are using R package, please provide

1. The R `sessionInfo()`
2. The command to install `xgboost` if you are not installing from source

## Steps to reproduce

1.
2.
3.

## What have you tried?

1.rebuild the xgboost,doesnt work

2.
3.

**Comment by AbdealiJK** [comment]
How are you rebuilding xgboost ?
Did you do a `make clean_all` and followed by `make -j` ?

**Comment by yinshurman** [comment]
hello,thanks for your cares,the problem has been resolved.the key point is that i installed anaconda and the libgomp.so.1 and libstdc++.so.6 file in anaconda seems out of time,lacking  GOMP_4.0 and some other files,but in Ubuntu 16.04 the  corresponding files is new enough ,the solution is to make some link files to  update the corresponding  files in anaconda

**Comment by AbdealiJK** [comment]
Ah, awesome. Do close the issue so that it doesn't come up as unresolved

**Comment by BaljeetSinghCheema** [comment]
@yinshurman would you  mind posting the solution steps!
thanx in advance

**Comment by yinshurman** [comment]
step 1 : use the following commands to check whether the libgomp.so.1 filie in anconda contains the required version GOMP_4.0 (replace the path by your own in all the steps) :
                   string  /home/yin/anaconda3/bin/../lib/libgomp.so.1 |grep GOMP
           ( if there is not  GOMP_4.0 version ,go to step 2, else  leave a comment  )
step 2: to check  libgomp.so.1 in your OS:
                    sudo find / -name libgomp.so.1*
step3: check the link in anaconda ：
                     ls -al   /home/yin/anaconda3/bin/../lib/libgomp.so.1
           if the link not link to the newest verison  in step 2 's list , then make a new link to update it by:
                      sudo rm -rf  /home/yin/anaconda3/bin/../lib/libgomp.so.1
                      sudo ln -s  <path of the newest version libgomp file in your OS >   <path in anaconda>
                      (for example    sudo ln -s /usr/.../libgomp.so.XXX     /home/yin/anaconda3/bin/..libgomp.so.1)
ps:without my computer at hands,I can't remember the concrete path ,but this method resolve my problems,in fact ,in my case, not only GOMP_4.0 but also some other files are not found(for example,this [https://github.com/dmlc/xgboost/issues/1700](url) ), this solution works well too.

**Comment by BaljeetSinghCheema** [comment]
Thank you so much @yinshurman

**Comment by AkashDevgun** [comment]
@yinshurman ....can you please tell me step by step i am not find out the solution for the following error:

import xgboost 
SError: /home/akash/anaconda2/bin/../lib/libgomp.so.1: version `GOMP_4.0' not found (required by /home/akash/anaconda2/lib/python2.7/site-packages/xgboost/./lib/libxgboost.so

**Comment by datorse** [comment]
Yes it works. These steps perfectly worked for libeemd and pyeemd package. Thanks

**Comment by jiqiujia** [comment]
Is there any way to update the libgomp lib in anaconda
After I make a symbolic file to a system one, it instead report an error about libstdc++.so.6.

**Comment by yinshurman** [comment]
Maybe you can try `conda install libgcc` ,which can resolve the problems like this,too @jiqiujia

**Comment by jiqiujia** [comment]
@yinshurman Thanks a lot. It works!

**Comment by jxlijunhao** [comment]
@yinshurman Thanks a lot. It works

**Comment by gyang274** [comment]
I fixed this by updating the anaconda gcc from 4.8.5 to 5.4.0 by

`conda install -c salford_systems gcc-5`

**Comment by Grumby** [comment]
**@yinshurman**  I had problems with libgomp.so.1  and   libstdc++.so.6 and it worked for both. Thank you.

**Comment by datamove** [comment]
`GOMP_4.0' not found
This is an error due to mismatch of versions xgboost was built with and versions in the conda environment whcih xgboost uses to at runtime. 
The easiest way to solve the problem and not break anything is to build xgboost explicitly with conda's libraries, for which the following needs to be done:
1. Start a fresh terminal
`export LD_LIBRARY_PATH=~/work/anaconda3/lib #or whatever your anaconda install path is`
2. make sure your default python is from anaconda distro:
`which python`
If not, add anaconda distro to PATH:
`export PATH=~/work/anaconda3/bin:$PATH`
3. Rebuild and reinstall xgboost
`cd ~/xgboost`
`make clean_all`
`make -j4`
`cd python-package`
`python setup.py install``
4. verify

you can now close the terminal, and start a new one, LD_LIBRARY_PATH need not persist, as conda's env. got required libraries.
