### ISSUE TITLE
Does it support multithreading?

### ISSUE THREAD

**Issue by jdxyw** [dmlc/xgboost#1793]
Hello,

I want to use the xgboost for online prediction. Does it support multithreading and thead-safe? Because I meet some strange segment fault, however it works well when the qps=1.

Best Regards,

**Comment by xadupre** [comment]
Hi,

I made some changes in my repo to allow that scenario (https://github.com/xadupre/xgboost). XGBoost can be called from multiple threads for predictions. I modified the API. The user makes two calls to the API, one to retrieve the size of two buffers he heeds to allocate, the other one to run the predictions. In multithreading, the users has to allocate two buffers per thread.

Xavier
