### ISSUE TITLE
Compare predicted value with a variable other than "label" in custom evaluation function

### ISSUE THREAD

**Issue by uptownfunk** [dmlc/xgboost#1795]
I am using feval in xgb.cv to calculate the value of a custom evaluation metric. The model outputs a predicted value which I can access through the "preds" argument of my custom eval. function. I can also access the original labels upon which the model is trained using getinfo(dtrain, "label"). However, if I have another column in my dataset that my model is not currently being trained on, which I would like to use to compare against "preds" I can't find a way to do this in the current setup.

**Comment by pommedeterresautee** [comment]
Use closure feature (supported on R, Scala and Python)
