### ISSUE TITLE
Create folds in xgb.cv putting groups of records in the same fold

### ISSUE THREAD

**Issue by uptownfunk** [dmlc/xgboost#1796]
The xgb.cv function creates folds of the data upon which it does k-fold CV.

We are working with signal data and we are trying to validate our models. The signal data files come in hour long chunks which we then analyze minute-by-minute, such that our final record which gets fed into xgboost has 1 minute / row. We have around 1000 hours of data. However, when we create our folds for validation, we want all the records from the same original hour long chunk to be in the same fold, otherwise we encounter grossly over-estimated validation metrics. Such that if rows 1:60 correspond to hour 1 of our data set, those 60 row should be in the same fold, to prevent leakage across folds. I cannot find a way to do this using the xgb.cv function.

**Comment by khotilov** [comment]
You can pass your pre-created folds indices through the `folds` parameter.

**Comment by uptownfunk** [comment]
Perfect, this is what I needed, thanks!

**Comment by oxsem** [comment]
Could you please let me know in which format are you passing these indices? Is that possible to have folds with different number of indices in it? Thank you!
