### ISSUE TITLE
Functions of utils.R not visible

### ISSUE THREAD

**Issue by BlindApe** [dmlc/xgboost#180]
I'm trying to use some of the functions in utils.R, but they aren't visible after I've loaded the xgboost package with require(xgboost).
All the rest of functions are visible, and when I type their name in prompt R show the code, but the utils return an error of function don't found.
Any help?
Thank you.

**Comment by tqchen** [comment]
The functions in utils.R was intended to be hidden. Do you have any particular function you want to use?

**Comment by BlindApe** [comment]
I'm playing with an alternative xgb.train with early stopping based in change of eval score. When I call xgb.Booster, xgb.iter.update, xgb.iter.eval, they aren't found.

**Comment by tqchen** [comment]
As I said, those functions were intended to be hidden behind, you can checkout the repo and make your own tweaks though, or modify https://github.com/tqchen/xgboost/blob/master/R-package/NAMESPACE

After you change the code, type R CMD INSTALL /path/to/xgboost/R-package

**Comment by BlindApe** [comment]
Thank you

**Comment by hetong007** [comment]
@BlindApe Do you mind to share why you want to use the functions from utils? If there's a scenario asking for some functions inside, we might consider to expose them in a proper way.

**Comment by BlindApe** [comment]
@hetong007 
Mainly for early stopping based in eval score and for skip random fold assignament in cases when rows aren't independent so is necessary all rows related are in same fold.
I'll post the new functions when I test them for you decide if it is interesting add the options to the official package.

**Comment by hetong007** [comment]
@BlindApe For the fandom fold assignment, do you mean the process in cross-validation? I could add an argument which enables users to pass their own indices for the k folds. 

For the early stopping, do you mean to stop the program when it reaches to a satisfying eval score?

**Comment by BlindApe** [comment]
Yes, process in cross-validation. This would be nice.

**Comment by hetong007** [comment]
@BlindApe Sorry for this late reply. I read your code in the email, and I think we can achieve it without touching `xgb*` files by the demo here: [Boost from prediction](https://github.com/tqchen/xgboost/blob/master/R-package/demo/boost_from_prediction.R).

We can wrap this `boost -> predict -> eval -> boost` cycle with a `while` so that we can still stop when we want to. You can run `xgb.train` with `nrounds=1` instead of `xgb.iter.eval`.

**Comment by BlindApe** [comment]
OK. It's a workaround. Thank you.
I got that my code run fine too.

**Comment by yihui** [comment]
You can always use the evil `:::` to access non-exported objects in an R package, e.g. `xgboost:::xgb.iter.eval`, but usually objects are hidden for reasons (e.g. they are subject to future changes), so I do not recommend you to really rely on `:::`. Used documented and exported API whenever possible.
