### ISSUE TITLE
[jvm-packages] JVM package should use explicit versions for pom dependencies

### ISSUE THREAD

**Issue by hoesler** [dmlc/xgboost#1802]
I successfully installed the XGBoost JVM package to my local maven repo and tried to use the libs in spark by starting spark-shell with `spark-shell --packages ml.dmlc:xgboost4j-spark:0.7`. This gave me the following error:
```
Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: org.scala-lang#scala-compiler; ${scala.version}: not found, unresolved dependency: org.scala-lang#scala-reflect;${scala.version}
```

Package resolution fails because Spark is unable to substitute `${scala.version}`. Replacing the variable with the explicit version number solves the problem.

I filed an issue for Spark first, but the people there answered that "Published POMs shouldn't contain variables to substitute" (https://issues.apache.org/jira/browse/SPARK-18542)

Thanks
Christoph

## Environment info
Operating System:
Mac OS X 10.11.6

Compiler:
Apple LLVM version 7.3.0
Apache Maven 3.3.9

Package used (python/R/jvm/C++):
jvm

`xgboost` version used:
0.7

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`)
80e70c56b9b7a939248aed072b25969c1f088fb4
2. Logs will be helpful (If logs are large, please upload as attachment).

If you are using python package, please provide

1. The python version and distribution
2. The command to install `xgboost` if you are not installing from source

If you are using R package, please provide

1. The R `sessionInfo()`
2. The command to install `xgboost` if you are not installing from source

## Steps to reproduce

1. mvn install
2. spark-shell --packages ml.dmlc:xgboost4j-spark:0.7
3.

## What have you tried?

1.
2.
3.

**Comment by CodingCat** [comment]
a further answer there says, `There's nothing wrong with vars, but, the artifact release process resolves them, for exactly reasons like this.`

I didn't see why scala.version cannot be resolved

**Comment by hoesler** [comment]
So what am I doing wrong here? I thought a simple `mvn install` should be sufficient for `spark-shell --packages ml.dmlc:xgboost4j-spark:0.7` to resolve them.
