### ISSUE TITLE
[XGBoost-Spark] error running binary classification on income classification dataset - labels are not correctly provided 

### ISSUE THREAD

**Issue by tanwanirahul** [dmlc/xgboost#1805]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System: Ubuntu

Compiler: 4.8.4

Package used (python/R/jvm/C++):

`xgboost` version used: 

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`) -- 7ff742ebf7ec70c747f9aec004689fc727ba3304
2. Logs will be helpful (If logs are large, please upload as attachment).

If you are using python package, please provide

1. The python version and distribution -- 2.7
2. The command to install `xgboost` if you are not installing from source

If you are using R package, please provide

1. The R `sessionInfo()`
2. The command to install `xgboost` if you are not installing from source

## Steps to reproduce

1. Run the XGBoost algo on [income classification dataset](https://archive.ics.uci.edu/ml/datasets/Adult) 
with the following config params: 

Map(alpha -> 0.0, min_child_weight -> 1.0, colsample_bylevel -> 1.0, subsample -> 1.0, lambda -> 1.0, max_depth -> 7, num_class -> 2, objective -> binary:logistic, max_delta_step -> 0.0, eta -> 0.1, colsample_bytree -> 1.0, gamma -> 0.5, nthread -> 1)

## What have you tried?

1. It does run if we change the objective to multi:softprob, however, running it with binary:logistic or binary:logitraw leads to an error.

Error: 16/11/23 07:55:01 WARN TaskSetManager: Lost task 1.0 in stage 88.0 (TID 114, 11.0.0.149): ml.dmlc.xgboost4j.java.XGBoostError: [07:55:01] src/objective/regression_obj.cc:90: Check failed: (preds.size()) == (info.labels.size()) labels are not correctly providedpreds.size=32560, label.size=16280

**Comment by tanwanirahul** [comment]
@CodingCat Please let me know if you would need more details.

**Comment by CodingCat** [comment]
luckily, I once used this dataset to test XGBoost....https://github.com/CodingCat/xgboost_test/tree/master/src/main/scala/me/codingcat/income

I cannot reproduce it with the code there,

**Comment by Adverpol** [comment]
Just hit the same, the solution, as I found in [this answer](https://stackoverflow.com/a/42154357/678022), is to remove `num_class` from the parameter list.
