### ISSUE TITLE
Sklearn API: Add option to extend a model

### ISSUE THREAD

**Issue by AbdealiJK** [dmlc/xgboost#1806]
In many cases it is useful to be able to build a model up to X number of trees and then do some analysis to understand the model and then again build a few more trees on top of it and again do some analysis.
It would be useful to be able to do this in xgboost especially in the distributed scenario where things are already slow because of the size of the data.

So, xgboost could have a `extend` config and when it is true, the model_in is taken and appropriate initializations are done by scoring on the training data. And more trees are built on top of it using the given data.

It would also be useful if users want to make first few trees on data1, and the next few trees on data2. (Something like row sub sampling but with pre-curated data)

**Comment by AbdealiJK** [comment]
I just realized that this is already possible by simply giving a `model_in` in the Training stage. In such cases, XGBoost already loads the model and builds on top of the model.
Awesome!
Closing this.

**Comment by damienrj** [comment]
This feature doesn't appear to exist for XGBClassifier and it would definitely be helpful for cases where you have a large amount of legacy code built around SKlearn.

**Comment by benwu232** [comment]
I modified the sklearn.py to add this option and save/load model functions same as the classical ones. See if it help :)

[https://github.com/benwu232/xgboost/blob/master/python-package/xgboost/sklearn.py](url)

**Comment by AwasthiMaddy** [comment]
Hi @benwu232 
I am not able to access the modified sklearn.py . The above link doesn't work.
Would it be possible to you to make it available?
