### ISSUE TITLE
When will xgboost 0.60 be available for R on Windows?

### ISSUE THREAD

**Issue by rfcv** [dmlc/xgboost#1808]
Still not supported, and unable to build. I read that it is because of xtd:::thread not being supported in Windows. Would love to be able to use new DART booster.

Operating System: Windows 7
Package used: R
`xgboost` version used: 0.60

**Comment by thirdwing** [comment]
The latest Rtools should have the support for std::thread.

Please have some patience.

**Comment by rfcv** [comment]
Thanks for the update @thirdwing

**Comment by thirdwing** [comment]
Hi, @rfcv 

I just uploaded a Windows version to https://github.com/dmlc/drat/blob/gh-pages/bin/windows/contrib/3.3/xgboost_0.6-0.zip

Can you try the following?

```
install.packages("drat", repos="https://cran.rstudio.com")
drat:::addRepo("dmlc")
install.packages("xgboost", repos="http://dmlc.ml/drat/")
```

**Comment by rfcv** [comment]
@thirdwing I was able to download and use xgboost 0.60 using the code you provided. I did a grid search to run through the dart booster parameters, and it seems to be working as intended.

**Comment by thirdwing** [comment]
That's great.
