### ISSUE TITLE
predict.xgb.Booster in R ignores colnames of newdata 

### ISSUE THREAD

**Issue by victor-moreno** [dmlc/xgboost#1809]
In R,  predict.xgb.Booster ignores colnames in newdata to match the features used in the model.
This issue can lead to serious errors if ignored. 
The user must ensure the newdata has exactly the same columns as in the train dataset.

#### Steps to reproduce

```
library(xgboost)

# sample from help
data(agaricus.train, package='xgboost')
set.seed(1)
bst <- xgboost(data = agaricus.train$data, label = agaricus.train$label, max_depth = 2, eta = 1, nthread = 2, nrounds = 2, objective = "binary:logistic")

auc<-function (x, y) (mean(rank(x)[y == 1]) - (sum(y) + 1)/2)/(length(x) - sum(y))

pr<-predict(bst, newdata = agaricus.train$data)
auc( pr, agaricus.train$label ) # 0.9814132

# importance
imp<-xgb.importance(colnames(agaricus.train$data), model = bst)
imp$Feature

# repeat model with important features only (n=4)
set.seed(1)
bst.i <- xgboost(data = agaricus.train$data[,imp$Feature], label = agaricus.train$label, max_depth = 2, eta = 1, nthread = 2, nrounds = 2, objective = "binary:logistic")

# predict in original dataset, wrong since colnames are not used to match features from model. No warning !!!
pr.i<-predict(bst.i, newdata = agaricus.train$data)
auc( pr.i, agaricus.train$label ) # 0.5317163 random prediction

# predict in dataset subsetted for features works correct
pr.i<-predict(bst.i, newdata = agaricus.train$data[,imp$Feature])
auc( pr.i, agaricus.train$label ) # 0.9814132 
```

#### ## Environment info
Operating System: OSX
Compiler: gcc-6
Package used:  R 3.3.2
`xgboost` version used: 0.6-0

R `sessionInfo()`
R version 3.3.2 (2016-10-31)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: OS X El Capitan 10.11.6

**Comment by khotilov** [comment]
xgboost relies only on the order of columns and it holds a user responsible to ensure the consistency. The R interface follows the same principle without any restrictions or warnings.

With that said, it should be possible on R's side to implement at least some warnings (not error) when column names are available and are inconsistent. But we would need to think about how to implement disabling such checks for the cases when it is not always necessary, e.g., when predict is called very frequently during training and there are many thousands of columns.

While `xgb.Booster` does not currently keep columns information, it might be a useful bookkeeping addition to keep column names with a model.

**Comment by khotilov** [comment]
A related issue for the python interface: #1605
