### ISSUE TITLE
[R] Add support for Drat Packages

### ISSUE THREAD

**Issue by pommedeterresautee** [dmlc/xgboost#181]
Right now, to install the last version of Xgboost on R you need to use devtools::install_github()

Unfortunately using that way means for the users not being notified of updates in the Github version. You just re execute the command when you feel it is required.

A new package just appeared in R, it's called Drat, information are available there:
http://dirk.eddelbuettel.com/code/drat.html

I let you read the description, but basically it means for xgboost users to use the github version as a CRAN version.

I think it makes sense to support such way to install Xgboost because we have lots of innovation in Github not existing in Cran. 

When an update will be pushed to Cran we will continue to have this gap between version very soon after: for instance I know that @tqchen is interested in out of core algorithm. It will probably request changes in the R API. Moreover, when the update will be pushed (I don t want to break things) I will probably rewrite the tree viz part to build something more useful. 

Until Xgboost package is stable, tools like Drat seems interesting.

My question is: do you want me to test + make required change if any + add information on how to use Drat install instead of devtools way in the README file?
We may wait pushing the update to Cran before making any major change.

Kind regards,
Michael

**Comment by tqchen** [comment]
It depends on how complicated the setup was. Since I think major changes will follow the CRAN release flow, while minor improvements might happen and user who needs the functionality and checkout the github version.

**Comment by pommedeterresautee** [comment]
Thinking to it, I don't feel it is so interesting anymore. Don t hesitate to re open the issue if you think it brings some concrete advantages to the project.

**Comment by tqchen** [comment]
@hetong007 @pommedeterresautee I think we like to revisit this issue, as we might want to provide some of the customized installation packages(e.g.  multi-threaded binary for OSX).

I have created https://github.com/dmlc/drat for R packages from DMLC. For now it will include mxnet and xgboost.

@hetong007  Can you take a look and see if we can push a version of current master to this repo?

**Comment by terrytangyuan** [comment]
Let's discuss this in the recent issue for major refactoring.
