### ISSUE TITLE
[jvm-package] Discussion on xgboost-spark

### ISSUE THREAD

**Issue by fromradio** [dmlc/xgboost#1810]
As we know, spark has driver and executor. In Hadoop, the 'driver' is always the local machine. Thus we usually do not worry about the compiling environment. But spark driver sometimes is out of control. And xgboost4j highly depends on the cpp library libxgboost.so, so we have to make sure that running machines supports cpp11. This is kind of simple for executor since we have only to use `addFile` function to put `libstdc++.so` into the running environment. But driver does not work that way. I have tried to use `addFile`, but driver still find `libstdc++.so` in the dir `/usr/lib64` or something like that. It is very hard for us to fix that since others might use lower version of cpp and we do not have the right to change the environment of the whole cluster.

Does anyone know how to let driver know where `libstdc++` is?

Does anyone has the plan to rewrite xgboost in java or make it cpp-independent? That will help a lot of people. And I will try my best to help.

**Comment by tqchen** [comment]
The fact is driver logic do not relies on libxgboost.so. So the question could instead be is it possible for xgboost4j simply not load libxgboost.so in the driver logic.

@CodingCat

**Comment by xydrolase** [comment]
xgboost4j-spark depends on libxgboost4j.so, which is compiled when you call `mvn compile`. 

I don't think providing `libstdc++.so` solves the whole problem. You also need GLIBC. 

With regard to driver and executor, you can run xgboost4j-spark in YARN cluster mode, under which the driver will be run inside the cluster as well.

**Comment by CodingCat** [comment]
It's hard to do so,  because driver and executor end code are in the same program....

**Comment by xydrolase** [comment]
And I don't think it will be worth it to reimplement XGBoost in Java/Scala, as you will basically end up with two versions that are hard to maintain to keep in sync down the road.

**Comment by CodingCat** [comment]
as @xydrolase said running in cluster mode ( YARN or standalone) is a solution

**Comment by fromradio** [comment]
Hi guys, I solve this problem via using `System.load` method to add the .so file (only libstdc++ needed). Packaging the libstdc++ would not work, libxgboost4j.so cannot find it. The Spark environment is set by another department in my company. I think I am using YARN cluster mode. But the driver still works a little different from executor. The user directory of executor is java.library.path but driver is not. The driver still searches the so in /usr/lib64 so I have to add it manually. 

BTW, I am trying to modify the jvm-package and add some features (like sample weight in xgboost4j-spark)   and I will publish it after I finish. Is there any code style request besides what the maven checkstyle requires?

**Comment by xydrolase** [comment]
Interesting. In my case one of our clusters has old GLIBC as well. Maybe I can give your method a shot to see whether it can resolve such issue on that specific cluster.

What do you mean by sample weight?

**Comment by fromradio** [comment]
Just like the xgboost4j's `setWeight` method, sometimes the weight of samples are not the same. Some samples are more important, vice versa. And the spark version does not support the method yet.

**Comment by xydrolase** [comment]
Good to know. Never used that though. So will you make the weights a separate DataFrame/RDD?
But I guess you will have to make sure that the weights have the same number of partitions, right?

I'm curious in general, if you have two RDDs of equal number of rows, how can you guarantee the order/index of the two, if you simply want to stack the columns of the two.

**Comment by fromradio** [comment]
I will use weights as an additional column I think. I do not know how to guarantee the index of two RDDs. 

Here I still have a little problem about xgboost4j-spark. I re-write the training part to force training on only one executor, the result is greet. But when I use the partition method the Spark Context is shut down before the training succeeds?

Here is the error:

```
16/11/25 10:57:16 ERROR ApplicationMaster: User class threw exception: ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed
ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.train(XGBoost.scala:177)
	at com.qiyi.PreviousMethod$.main(PreviousMethod.scala:108)
	at com.qiyi.PreviousMethod.main(PreviousMethod.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:542)
Exception in thread "Thread-62" java.lang.IllegalStateException: SparkContext has been shutdown
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1824)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1845)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1858)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1929)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:920)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:918)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:111)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:316)
	at org.apache.spark.rdd.RDD.foreachPartition(RDD.scala:918)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anon$3.run(XGBoost.scala:160)
```

I am using xgboost-0.6 since the cluster does not support scala-2.11 yet.

Do you know how to fix this?

**Comment by xydrolase** [comment]
Can you attach the log from within the executor also?

**Comment by fromradio** [comment]
Something like below:

```
LogType: stderr
LogLength: 591
Log Contents:
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/data6/yarn/local/filecache/28841/spark-assembly-1.6.1-hadoop2.5.0-cdh5.2.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/lib/zookeeper/lib/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
16/11/25 11:22:37 ERROR CoarseGrainedExecutorBackend: Driver 10.153.81.37:56698 disassociated! Shutting down.

LogType: stdout
LogLength: 0
Log Contents:
```

**Comment by xydrolase** [comment]
How many executors did you use in your training task? This is just the log for one of them, right?

**Comment by fromradio** [comment]
There are 4 in total and nWorkers parameter in train method is set 2.

**Comment by xydrolase** [comment]
So why not use 4 `nWorkers` then, if you have 4 executors?

**Comment by fromradio** [comment]
4 is used and the result is still the same.

**Comment by xydrolase** [comment]
Have you noticed other errors at executor level other than `Driver 10.153.81.37:56698 disassociated! Shutting down.`?

Did you use the same dataset for your training on one executor, and distributed training?
What exactly did you modify in your experiments?

**Comment by fromradio** [comment]
No, it seems that this is the only error on executor. The dataset is the same, just `agaricus` dataset. The only difference as I know is that I skip the repartition step in training and delete Rabbit in one executor training step.

Now, I want to test whether the Rabbit makes the procedure down.

**Comment by fromradio** [comment]
TrainingOnSingleNode:

```scala
@throws(classOf[XGBoostError])
  def trainDataOnSingleNode(trainingData: RDD[LabeledPoint], configMap: Map[String, Any],
      round: Int,
      obj: ObjectiveTrait = null, eval: EvalTrait = null,
      useExternalMemory: Boolean = false): XGBoostModel = {
    val nWorkers = 1
    implicit val sc = trainingData.sparkContext
    var overridedConfMap = configMap
    if (overridedConfMap.contains("nthread")) {
      val nThread = overridedConfMap("nthread")
      val coresPerTask = sc.getConf.get("spark.task.cpus", "1")
      require(nThread.toString <= coresPerTask,
        s"the nthread configuration ($nThread) must be no larger than " +
          s"spark.task.cpus ($coresPerTask)")
    } else {
      overridedConfMap = configMap + ("nthread" -> sc.getConf.get("spark.task.cpus", "1").toInt)
    }
    val boosters = buildSingleBooster(trainingData, overridedConfMap,
      nWorkers, round, obj, eval, useExternalMemory)
    val sparkJobThread = new Thread() {
      override def run() {
        // force the job
        boosters.foreachPartition(() => _)
      }
    }
    boosters.first()
  }
```

buildSingleBooster

```
private[spark] def buildSingleBooster(
      trainingData: RDD[LabeledPoint],
      xgBoostConfMap: Map[String, Any],
      numWorkers: Int, round: Int, obj: ObjectiveTrait, eval: EvalTrait,
      useExternalMemory: Boolean): RDD[Booster] = {
    import DataUtils._
    val partitionedData = trainingData
    val appName = partitionedData.context.appName
    // to workaround the empty partitions in training dataset,
    // this might not be the best efficient implementation, see
    // (https://github.com/dmlc/xgboost/issues/1277)
    partitionedData.mapPartitions {
      trainingSamples =>
        var booster: Booster = null
        if (trainingSamples.hasNext) {
          val cacheFileName: String = {
            if (useExternalMemory && trainingSamples.hasNext) {
              s"$appName-dtrain_cache-${TaskContext.getPartitionId()}"
            } else {
              null
            }
          }
          val trainingSet = new DMatrix(new JDMatrix(trainingSamples, cacheFileName))
          booster = SXGBoost.train(trainingSet, xgBoostConfMap, round,
            watches = new mutable.HashMap[String, DMatrix] {
              put("train", trainingSet)
            }.toMap, obj, eval)
        } else {
          throw new XGBoostError(s"detect the empty partition in training dataset, partition ID:" +
            s" ${TaskContext.getPartitionId().toString}")
        }
        Iterator(booster)
    }.cache()
  }
```

**Comment by xydrolase** [comment]
Just to clarify, you use the unmodified code when you run training with 2/4 executors, correct?

**Comment by fromradio** [comment]
Yes, I used the unmodified code to run training with 2/4 executors and 4/4 executors and both failed with same error. I am trying to print more infos now.

**Comment by fromradio** [comment]
I tracked Rabit and just get two logs:

```
16/11/25 14:36:17 DEBUG RabitTracker: Tracker started, with env={}
16/11/25 14:36:17 INFO RabitTracker: Tracker Process ends with exit code 1
```

**Comment by fromradio** [comment]
Error found. Caused by the wrong version of Python.

![n_ dd t yd8knwy2j0o5a](https://cloud.githubusercontent.com/assets/6701845/20619237/5fa3f5e2-b32e-11e6-9466-b28a19dbb7c5.png)

**Comment by xydrolase** [comment]
Good that you've figured it out. I ran into Python version issues before on one of our clusters.
I submitted a pull request #1612 to get rid of the Python dependency, but since XGBoost has now migrated to Spark 2.0 and Scala 2.11, it may not directly apply without modifications.

**Comment by CodingCat** [comment]
so, it seems that this one can be closed?

**Comment by liudragonfly** [comment]
Does the spark version support sample weight now?
