### ISSUE TITLE
Submit new R package to CRAN

### ISSUE THREAD

**Issue by terrytangyuan** [dmlc/xgboost#1812]
@hetong007 @tqchen @pommedeterresautee @khotilov 

I received some requests recently. Could anyone submit the latest version to CRAN (major changes are the callbacks I believe)?

**Comment by terrytangyuan** [comment]
Sorry I missed that issue. Thanks @hetong007.

**Comment by tqchen** [comment]
We will need a VM to get solaris checks pass,  @thirdwing  can you help on that?

**Comment by thirdwing** [comment]
I will try to find some time.

**Comment by thirdwing** [comment]
I just try a 32-bit Solaris VM. However, I can't install all the dependencies on that.

**Comment by hetong007** [comment]
@thirdwing  Do you have a list of those dependencies?

**Comment by thirdwing** [comment]
`NMF` can't be install one x86 VM. See https://cran.r-project.org/web/checks/check_results_NMF.html

We don't depend on this directly. This is a dependecy for DiagrameR

**Comment by thirdwing** [comment]
BTW, I can install `xgboost` on x86 Solaris.

**Comment by tqchen** [comment]
@thirdwing can you confirm the R check as-cran pass?

**Comment by thirdwing** [comment]
I can just install it. It seems impossible to do the check on x86 Solaris machine.

**Comment by khotilov** [comment]
The igraph depends on NMF , the DiagrammeR depends on igraph; and we call some functions from both DiagrammeR and igraph in some non-essential plotting methods. There are a few unit tests which call those  - is that why the check for solaris doesn't work? Could it make sense to disable those particular tests just for the CRAN release?

**Comment by thirdwing** [comment]
@khotilov Failure on x86 Solaris is somewhat acceptable by CRAN, since NMF hasn't been removed. I will try to get access to a real Solaris machine.

**Comment by ck37** [comment]
+1 to CRAN release, would be very helpful since the current version is from July 12.

**Comment by terrytangyuan** [comment]
Any updates on this? Have you sorted out the issue with raw test mismatch?

**Comment by hetong007** [comment]
As mentioned by @yixuan in https://github.com/dmlc/xgboost/pull/1826#issuecomment-264056624, this error can be observed when R compiles with `-O1` or `-O2`, and vanishes when using `-O0`.

I am considering about commenting out the related tests when submitting to CRAN.

**Comment by terrytangyuan** [comment]
Yeah I think we can submit it for now by commenting those out.

**Comment by hetong007** [comment]
I will do that in this weekend.

**Comment by thirdwing** [comment]
xgboost failed on solaris: https://www.r-project.org/nosvn/R.check/r-patched-solaris-x86/xgboost-00install.html

This is because the openmp support on CRAN machine.

Two solution: (1) disabled openmp; (2) add a separate autoconf script.

**Comment by hetong007** [comment]
The first solution would make the package much weaker on CRAN, thus not really benefits the CRAN users.
@thirdwing can you help with the second solution?

**Comment by thirdwing** [comment]
see my repo https://github.com/thirdwing/xgboost/commit/e1af62c9d199cd8bb191d61c79350dd922b58efb

It should work on Solaris and Linux. Not sure about Windows.

**Comment by tqchen** [comment]
i think it is fine to disable OpenMP on solaris because solaris is not used widely anyway. It is interesting that C++11 compiler in solaris is g++ instead of Solaris studio. We do need to make sure the checks pass in other OS

**Comment by thirdwing** [comment]
If you have `CXX_STD = CXX11`, the solaris will also use `g++`.

Actually I think it will be more complicated to disable openmp on only one OS.

**Comment by tqchen** [comment]
What I intended to say is that this is the problem of current CRAN's solaris build system. see also my comment in https://github.com/dmlc/xgboost/pull/1880  By default, it should be the build system's job to switch off openmp by not passing anything in SHLIB_OPENMP_CFLAGS . 

This happens in OSX automatically. Solaris have openmp support with solaris studio, but need to be able to disable it when c++11 is turned on. This is the problem of current build script, that affect every package with c++11 and openmp turned on

**Comment by yixuan** [comment]
The problem is due to the wrong flag to enable OpenMP. For Solaris Studio the flag for OpenMP is `-xopenmp`, but for GCC it is `-fopenmp`. From the CRAN check log it can be seen that `-xopenmp` was passed to GCC.

**Comment by thirdwing** [comment]
That is why we need a configure script

**Comment by yixuan** [comment]
Yep, and here is what I found: #1881 .

**Comment by hetong007** [comment]
Currently xgboost 0.6-2 is on. The version number "2" is the need for the post-submission bug fixing.

However after the fixes from @yixuan and @thirdwing , installation on Solaris is still broken: https://cran.r-project.org/web/checks/check_results_xgboost.html.

Another issue is that DiagrammeR 0.9 will be on CRAN. It is also left to be tested to see if this update breaks xgboost.

**Comment by tqchen** [comment]
@thirdwing Can you grab a VM to look into this?

The Sparc compilation error is due to lack of support of thread local in Sparc, which can be solved by optionally disable thread local macro here https://github.com/dmlc/xgboost/blob/master/src/common/thread_local.h#L22 to check solaris and simply define MX_TREAD_LOCAL to be empty

**Comment by tqchen** [comment]
The segfault of x86 solaris is more mysterious, and we might need a reproducible example to see what exactly happened.

**Comment by thirdwing** [comment]
I only have the x86 VM. I will have a try if possible.

**Comment by thirdwing** [comment]
@tqchen I can't reproduce the error on the X86 solaris VM.

**Comment by thirdwing** [comment]
From the CRAN checking log, the error on X86 Solaris is from https://github.com/dmlc/xgboost/blob/master/R-package/src/xgboost_R.cc#L88

It involves the usage of openmp, so maybe we can try to disable openmp on solaris.

**Comment by tqchen** [comment]
Let us do that

**Comment by tqchen** [comment]
Let us also fix the thread local issue by patching the fix i mentioned

**Comment by tqchen** [comment]
@thirdwing can you followup on this? I also noticed there is an error in windows, reporting conflicting defintition of fopen, do you know what happened there?

**Comment by thirdwing** [comment]
I am working on my own fork. The on Solaris doesn't support if ,which makes things much harder.

**Comment by hetong007** [comment]
@thirdwing just opened a new PR (pending) for solaris: https://github.com/dmlc/xgboost/pull/1912 .

For the error on old release windows, the [error message](https://www.r-project.org/nosvn/R.check/r-oldrel-windows-ix86+x86_64/xgboost-00install.html) is 
```
d:\compiler\gcc-4.6.3\bin\../lib/gcc/i686-w64-mingw32/4.6.3/../../../../i686-w64-mingw32/include/stdio.h:396:83: error: 'FILE* std::fopen(const char*, const char*)' should have been declared inside 'std'
d:\compiler\gcc-4.6.3\bin\../lib/gcc/i686-w64-mingw32/4.6.3/../../../../i686-w64-mingw32/include/stdio.h:396:83: error: declaration of 'FILE* std::fopen(const char*, const char*)'
d:\compiler\gcc-4.6.3\bin\../lib/gcc/i686-w64-mingw32/4.6.3/../../../../i686-w64-mingw32/include/stdio.h:395:17: error: conflicts with previous declaration 'FILE* fopen(const char*, const char*)'
```

I found several related previous issues:
- https://github.com/dmlc/xgboost/issues/1174#issuecomment-225014458
- https://github.com/dmlc/xgboost/issues/1267

Hope someone can shed light on it.

**Comment by thirdwing** [comment]
@hetong007 I suggest adding `Depends: R (>= 3.3.0)`, so we do not need to worry about old windows release.

**Comment by terrytangyuan** [comment]
There have been some updates and typo fixes to docs. Could you also
regenerate the docs before resubmitting the package?

**Comment by hetong007** [comment]
There are some plot-related errors on R 3.3.2 when checked by win-builder: https://win-builder.r-project.org/Oc7UhRHG4Y2w/00check.log (link will expire after roughly 72 hours).

However the check on R-devel is fine: https://win-builder.r-project.org/qG0ASTr2Yd45/00check.log

The errors, e.g. `Error: 'graph_from_data_frame' is not an exported object from 'namespace:igraph'`, are not reproducible on Linux. I will compile and check it on a windows machine later today to see if this is actually caused by win-builder.

**Comment by thirdwing** [comment]
Please also update this https://github.com/dmlc/xgboost/blob/master/R-package/vignettes/xgboost.Rnw#L24

**Comment by thirdwing** [comment]
You should use something like `xgboost.version <- packageDescription("xgboost")$Version`

**Comment by thirdwing** [comment]
We are getting closer. Now errors only come from Old Windows release and Sparc Solaris: https://cran.r-project.org/web/checks/check_results_xgboost.html

My opinions are as follow:

(1) We don't need to care much about old Windows release;

(2) Sparc Solaris failed in https://github.com/dmlc/xgboost/blob/master/R-package/tests/testthat/test_helpers.R#L86

The simplest solution is to disable this test on Solaris by detecting `Sys.info()[['sysname']]`.
