### ISSUE TITLE
Create function GetOneGradient() in ObjFunction

### ISSUE THREAD

**Issue by AbdealiJK** [dmlc/xgboost#1815]
I'm trying to make a plugin which reads some data record by record and calculates the gradient for each record. Due to other reasons, doing it on a batch is not easy, because it needs to be done at every tree level and so on.

In such cases, I realized that the ObjFunction's GetGradient() is insufficient, because an objective function may need a batch of items to create the gradients (For example LambdaRank). In such cases having a `GetOneGradient()` would be useful, and objective functions which cannot implement a gradient for a single item can simply throw a fatal error saying GetOneGradient cannot be implemented due to algorithm constraints.

Either this, or a flag which explains "only_batch_grad_calculation" or so which tells this information would be useful.

**Comment by pommedeterresautee** [comment]
Old proposition, no answer. Closing
