### ISSUE TITLE
Can't use custom objective with XGBoost v 0.60

### ISSUE THREAD

**Issue by zachmayer** [dmlc/xgboost#1820]
I'm trying to use a custom objective function with a fresh install of XGBoost 0.6, but I keep getting the following error:

`XGBoostError: unknown evaluation metric type: <function evalerror at 0x7fcf83127d70>`

Any suggestions?  Can anyone else get a custom objective to work with a fresh install from 4092e4b9c7c8650ba66d6a61c90fc06132d8a511 ?

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System: Ubuntu 14

Compiler: gcc

Package used (python/R/jvm/C++): python

`xgboost` version used: 0.6 (fresh install from github)

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`): 4092e4b9c7c8650ba66d6a61c90fc06132d8a511
2. Logs will be helpful (If logs are large, please upload as attachment).

If you are using python package, please provide

1. The python version and distribution 2.7, apt-get install python
2. The command to install `xgboost` if you are not installing from source:
I installed from source using the instructions in this repo

## Steps to reproduce

1. Start a new model
2. Provide the parameter ``
3. Try to run XGBoost

## What have you tried?

1. Uninstall & re-install
2. Install in a virtualenv

**Comment by tqchen** [comment]
@hetong007 can you verify this?

**Comment by tqchen** [comment]
@terrytangyuan can you take a look?

**Comment by terrytangyuan** [comment]
Will do when I get a chance. Thanks for reporting @zachmayer

**Comment by terrytangyuan** [comment]
@zachmayer it would be better if you can provide a reproducible example. I am not by my computer now but perhaps you can try run some code in tests, e.g. https://github.com/dmlc/xgboost/blob/master/tests/python/test_eval_metrics.py

**Comment by terrytangyuan** [comment]
Hi Zach, any updates yet? I cannot reproduce it. Could you post an example?
