### ISSUE TITLE
Inconsistent use of bst_float/float

### ISSUE THREAD

**Issue by AbdealiJK** [dmlc/xgboost#1821]
There is a lot of confusion in the code between use of bst_float/float/double.

The [split value is saved as a float](https://github.com/dmlc/xgboost/blob/da2556f58a122efcf7034d955e21040843a3b8a1/src/tree/param.h#L411), although the [feature values are saved as bst_float in data.h](https://github.com/dmlc/xgboost/blob/master/include/xgboost/data.h#L108).
[Weights and base margins are again saved and read as float](https://github.com/dmlc/xgboost/blob/master/include/xgboost/data.h#L68), but the datatype it's stored in [MetaInfo is bst_float](https://github.com/dmlc/xgboost/blob/master/include/xgboost/data.h#L52).

There seems to be many such cases where there is not a consistent use of bst_float/float. This doesn't make it easy to convert all the instances to another type. i.e. I can't set bst_float to double and expect it to work out of the box with the larger precision I want.

EDIT:
Earlier this issue talked also about how double was being intermixed with float/bst_float but as mentioned below, this is meaningful because of the required precision for sum stats vs single stats - Example: sum_grad vs grad.

**Comment by tqchen** [comment]
This is intentional to use double for sum statistics while use float for the statistics of single node

**Comment by tqchen** [comment]
To be specific, the aggregation is precision sensitive, while the single float value could be represented by float with no problem

**Comment by AbdealiJK** [comment]
@tqchen I agree with the point made by you and by @khotilov at https://github.com/dmlc/xgboost/pull/1824#issuecomment-263613484

But there are still instances where float has been used where bst_float should have been used. (Although they are the same, if I want to change bst_float to double for my specific case, there are many issues.

**Comment by AbdealiJK** [comment]
Edited the description of the issue. Now it is only about float vs bst_float.

**Comment by AbdealiJK** [comment]
Closing as this was fixed in https://github.com/dmlc/xgboost/commit/6f16f0ef5829965ba420ef6937617600d286820a
