### ISSUE TITLE
How to get predicting probabilities when customizing objective function for multi classification?

### ISSUE THREAD

**Issue by dingjunnan** [dmlc/xgboost#1822]
How to get predicting probabilities for each class when customizing objective function for multi classification? the code below just gives us prediction
`def logregobj(preds, dtrain):`
     `labels = dtrain.get_label()`
     `preds = 1.0 / (1.0 + np.exp(-preds))`
     `grad = preds - labels`
     `hess = preds * (1.0-preds)`
     `return grad, hess`

**Comment by pommedeterresautee** [comment]
Please check the documentation (it s an option)
