### ISSUE TITLE
C++ unittest cases

### ISSUE THREAD

**Issue by AbdealiJK** [dmlc/xgboost#1828]
I can see python and distributed test cases in the tests/ folder.
I wanted to know whether creating C++ unittests is something that you guys would like in the repo ?

I think it would be useful, to have both C++ and python tests as the C++ tests can test the internal working better rather than just the things exposed by the c_api.

It would be nice to have (wishlist? with the call-for-contributors label?) and would be something I would be interested in contributing.

**Comment by tqchen** [comment]
I am all for it if you are interested in contributing

**Comment by JohnStott** [comment]
If you both have a look at my pull request: https://github.com/dmlc/xgboost/pull/1710

You will see I have added basic c++ unit test functionality.  Unfortunately, the test had to be embedded inside the xgboost dll as most required tests within c++ wouldn't be possible as the required data is likely unavailable via the external interface. See my comments under that pull request you will see my thoughts and reasons.

**Comment by tqchen** [comment]
We could adopt gtest, as in other dmlc frameworks. e.g. https://github.com/dmlc/nnvm/tree/master/tests/cpp

**Comment by AbdealiJK** [comment]
I agree with the gtest approach.
In fact I have this Work In Progress commit which I guess would be a good first step to it https://github.com/AbdealiJK/xgboost/commit/6bdaefa1a21fb5e417a8d0d48e60ac01f99d8ded

**Comment by JohnStott** [comment]
I didn't even realise this was possible!  If I could use this for my validation code, this would be far superior :+1:
