### ISSUE TITLE
[mac] ld: symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by wenghb** [dmlc/xgboost#1839]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
make: *** [xgboost] Error 1
make: *** Waiting for unfinished jobs....
make: *** [lib/libxgboost.so] Error 1

## Environment info
Operating System:
MAC OS X Yosemite

Compiler:
gcc-6

Package used (python/R/jvm/C++):

`xgboost` version used:
clone from master

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`)
2f3958a45597750197de605bfe784763976650c1
2. Logs will be helpful (If logs are large, please upload as attachment).

If you are using python package, please provide

1. The python version and distribution
2. The command to install `xgboost` if you are not installing from source

If you are using R package, please provide

1. The R `sessionInfo()`
2. The command to install `xgboost` if you are not installing from source

## Steps to reproduce

1. brew install homebrew/versions/gcc6 --without-multilib
2. cp make/config.mk ./config.mk
3. make -j4

## What have you tried?

1.
2.
3.

**Comment by wenghb** [comment]
anyone can help me ?

**Comment by dingzj** [comment]
had same problem on El Captian, with newest gcc (6.3)

**Comment by KrisWu618** [comment]
make clean_all && make -j4 
works for me!! Thank you so much!

**Comment by TheodoreYin** [comment]
@dingzj Nice work!

**Comment by callzhang** [comment]
make clean_all && make -j4
works!!
I think it's due to unsuccessful compiling at first place.

**Comment by liuli1735** [comment]
make clean_all && make -j4
works for me, thx!

**Comment by bioinfo24091** [comment]
i have same issue been struggling to fix it
please advice 

```
ld: warning: ignoring file c4_model_archive.a, file was built for archive which is not the architecture being linked (x86_64): c4_model_archive.a
Undefined symbols for architecture x86_64:
  "_Bootstrapper_lookup", referenced from:
      _Viterbi_create in viterbi.o
      _Scheduler_create in scheduler.o
ld: symbol(s) not found for architecture x86_64
```

**Comment by Era2016** [comment]
@KrisWu618 , it shows "No rule to make target `clean_all` ", what should i do ?

**Comment by CicoZhang** [comment]
Is `make clean_all && make -j4` or `make clean all && make -j4`? Is the underline a must?
