### ISSUE TITLE
java.io.FileNotFoundException: File /lib/xgboost4j.dll was not found inside JAR.

### ISSUE THREAD

**Issue by kerwinjorbina** [dmlc/xgboost#1841]
I am trying for the first time to run a simple code using xgboost in Windows.

I have the error where the xgboost4j.dll file is not found inside the JAR. I was able to install the package of xgboost. Is there something I missed?

I have this as the code.

`import ml.dmlc.xgboost4j.java.DMatrix;
import ml.dmlc.xgboost4j.java.XGBoostError;

public class Main {

    public static void main(String[] args) {
        try{
            DMatrix dmat = new DMatrix("agaricus.txt.train");
        }
        catch (XGBoostError xgBoostError) {
            xgBoostError.printStackTrace();
        }
    }
}
`

**Comment by alexeygrigorev** [comment]
How did you build the jar? Did you run `make jvm`?

**Comment by kerwinjorbina** [comment]
I used mvn package and mvn install

**Comment by alexeygrigorev** [comment]
You should also do `make jvm` before that.

**Comment by joyang1** [comment]
@alexeygrigorev how I make jvm?
I installed jdk and set JAVA_HOME in my environment, but also have the same error  above.
My system is windows10.

**Comment by ghlozyx** [comment]
@alexeygrigorev How can I make jvm? I have the same problems with maven install.

**Comment by hcho3** [comment]
See https://xgboost.readthedocs.io/en/latest/jvm/index.html
