### ISSUE TITLE
Continue training from an existing model in R

### ISSUE THREAD

**Issue by tonyrajan** [dmlc/xgboost#1843]
Is there a way to continue training on a saved xgboost model in **R**? Can the model be updated so that the patterns of the new data is incorporated into the existing model? 
The python implementation provides command line parameter "model_in" for giving an existing model as input. Does a similar implementation exist in R as well?

**Comment by khotilov** [comment]
The answer is yes to all. Check the `xgb_model` parameter. Also, the recent addition in #1670 allows somewhat different way to update a model to new data (by updating existing trees).
