### ISSUE TITLE
Model deployment in C++

### ISSUE THREAD

**Issue by adendek** [dmlc/xgboost#1844]
Let's assume I created and trained some DNN model  (via python api) and then I want to deploy it into some standalone c++ project. 
How can I do it? Can you give me any advices?

**Comment by xydrolase** [comment]
Gradient boost trees are basically decision trees, which can be converted into many if-else statements. 

Once you train your model, you can dump the tree model, and convert it into customized C++ code with if-else statements checking the feature and split values. And finally, return the leaf value when you reaches the leaf.

**Comment by drag0** [comment]
@adendek - just create script that parses trees dump and generates one giant function with if-else statements. That's what I did and it works.

**Comment by adendek** [comment]
@drag0 Can you share the script with me? 
PS. Did you checked the time performance of your solution? In my project the timing is a crucial issue.

**Comment by drag0** [comment]
@adendek - I'll check my computer for that script tomorrow. As far as I remember it was really fast, it turned whole booster to one python function, it was a messy script because it was made in like 15 minutes. I'll ping you tomorrow here.

**Comment by adendek** [comment]
@drag0 what is the status of this script?

**Comment by drag0** [comment]
I'm going to send it to your email in couple of mins. Sorry, I forgot.

**Comment by byronliwei** [comment]
can you send this scipt to me? thank you. my email is byronliwei@gmain.com

**Comment by enissay14** [comment]
@drag0 I can use that script too! Thanks ( yassine dot landa at gmail dot com)

**Comment by yon100** [comment]
@drag0  I would highly appreciate receiving your script to gan.sagur@gmail.com. Thanks!!

**Comment by carsonyan** [comment]
Can you please share the script to me also :+1:  carsonwolf@gmail.com

**Comment by kaishengyao** [comment]
please share the script to me also  kaishengy@gmail.com
thanks a lot!

**Comment by drag0** [comment]
I'll push script code to GitHub today/tomorrow evening so you'll be able to use it. Sorry everyone for waiting so long.

**Comment by drag0** [comment]
Here it is guys: https://github.com/drag0/xgb2cpp

**Comment by enissay14** [comment]
@drag0 you rock! Thanks.

**Comment by xiaocongcsu** [comment]
Is there any other method to use xgboost classifier in C++ project? For the cpp model is too long to compile   in tx2. Thanks
