### ISSUE TITLE
Error when use callback cb.reset.parameters in xgb.cv

### ISSUE THREAD

**Issue by NamLQ** [dmlc/xgboost#1845]
I am using xgboost_0.6-0. There is an error when I use cb.reset.parameters in xgb.cv:
`Error in `*tmp*`$handle : object of type 'externalptr' is not subsettable`

## Environment info
Operating System: ubuntu 64bits 16.10 / 16.04

## The R `sessionInfo()`

> R version 3.3.2 (2016-10-31)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Ubuntu 16.10
> 
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
>  [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
> [10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] caret_6.0-73       lattice_0.20-34    ggplot2_2.2.0      Metrics_0.1.1     
> [5] Matrix_1.2-7.1     dplyr_0.5.0        xgboost_0.6-0      MatrixModels_0.4-1
> [9] data.table_1.10.0 
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_0.12.8        nloptr_1.0.4       plyr_1.8.4         iterators_1.0.8   
>  [5] tools_3.3.2        lme4_1.1-12        tibble_1.2         nlme_3.1-128      
>  [9] gtable_0.2.0       mgcv_1.8-16        foreach_1.4.3      DBI_0.5-1         
> [13] parallel_3.3.2     SparseM_1.74       stringr_1.1.0      stats4_3.3.2      
> [17] grid_3.3.2         nnet_7.3-12        R6_2.2.0           minqa_1.2.4       
> [21] reshape2_1.4.2     car_2.1-4          magrittr_1.5       scales_0.4.1      
> [25] codetools_0.2-15   ModelMetrics_1.1.0 MASS_7.3-45        splines_3.3.2     
> [29] assertthat_0.1     pbkrtest_0.4-6     colorspace_1.3-0   labeling_0.3      
> [33] quantreg_5.29      stringi_1.1.2      lazyeval_0.2.0     munsell_0.4.3

## Steps to reproduce

```
data(agaricus.train, package='xgboost')
data(agaricus.test, package='xgboost')

dtrain <- xgb.DMatrix(agaricus.train$data, label = agaricus.train$label)
dtest <- xgb.DMatrix(agaricus.test$data, label = agaricus.test$label)
watchlist <- list(eval = dtest, train = dtrain)

param <- list(max_depth = 2, eta = 1, silent = 1, nthread = 2)
bst <- xgb.cv(param, dtrain, nrounds = 2, watchlist, nfold=4)
# No error

my_etas <- list(eta = c(0.5, 0.1))
bst <- xgb.cv(param, dtrain, nrounds = 2, watchlist, nfold=4,
                 callbacks = list(cb.reset.parameters(my_etas)))
# Error in `*tmp*`$handle : object of type 'externalptr' is not subsettable
```

**Comment by khotilov** [comment]
Since you are passing a watchlist to `xgb.cv` (which has no `watchlist=` parameter) as an unnamed parameter, it internally becomes `label=watchlist`. While it's not right to do so, it still should be harmless in this case, and it also points to a bug in `cb.reset.parameters`. I'll submit a fix tomorrow. Thanks for reporting!
