### ISSUE TITLE
Build system discussion

### ISSUE THREAD

**Issue by RAMitchell** [dmlc/xgboost#1847]
I originally created a cmake build script to work on my GPU plugin for xgboost. Cmake is the only way to create a build system for CUDA that works for Linux and Windows as mingw is not supported. This seems to have been picked up by a fair few Windows users also as it allows compiling xgboost through visual studio.

The cmake build can be used with Python and CLI version so far. I would also like to extend this to R and Java if possible.  I have looked at R and it appears to heavily depend on gcc to build/install the package so it seems non-obvious how to do this.

So my question for the Java/R package maintainers is how can we modify the build/installation procedure such that a cmake build can be installed?

Additionally if we do this, how can the fragmentation of the build system/documentation be managed?

**Comment by macwilam** [comment]
This falls into the thread title but bot exactly your question. I hope it is ok to mention it here.

What about gcc6 vs gcc5 build problems. Currently xgboost builds with gcc6 as a default. However for this plugin we get an error:
/opt/cuda/include/host_config.h:119:2: error: #error -- unsupported GNU version! gcc versions later than 5 are not supported!

Even after I export CC and CXX for gcc5 I have many compilation errors:
17 errors detected in the compilation of "/tmp/tmpxft_000072ab_00000000-7_gpu_builder.cpp1.ii".
Most of them like:
xgboost/plugin/updater_gpu/src/find_split_sorting.cuh(300): error: no instance of overloaded function "cub::BlockScan ...
If you would like more info please let me know.
Im on archlinux x64. Up to date, cuda 8.04, cub 1.5.2.
On this system tensorflow builds and works without any problems.

I hope it is useful as this plugin seems to be very powerful. Thank you for you work.

**Comment by RAMitchell** [comment]
Hi, try using cub 1.6.4 (latest). I need to push an update to the build
documentation.

On 15/12/2016 12:39 am, "macwilam" <notifications@github.com> wrote:

This falls into the thread title but bot exactly your question. I hope it
is ok to mention it here.

What about gcc6 vs gcc5 build problems. Currently xgboost builds with gcc6
as a default. However for this plugin we get an error:
/opt/cuda/include/host_config.h:119:2: error: #error -- unsupported GNU
version! gcc versions later than 5 are not supported!

Even after I export CC and CXX for gcc5 I have many compilation errors:
17 errors detected in the compilation of "/tmp/tmpxft_000072ab_
00000000-7_gpu_builder.cpp1.ii".
Most of them like:
xgboost/plugin/updater_gpu/src/find_split_sorting.cuh(300): error: no
instance of overloaded function "cub::BlockScan ...
If you would like more info please let me know.
Im on archlinux x64. Up to date, cuda 8.04, cub 1.5.2.
On this system tensorflow builds and works without any problems.

I hope it is useful as this plugin seems to be very powerful. Thank you for
you work.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/dmlc/xgboost/issues/1847#issuecomment-267013056>, or mute
the thread

**Comment by esb797** [comment]
Initially, I built xgboost using MinGW, but to have GPU updater, I did it via CMake with Visual Studio. With this built, I found that the speed drops so much (3-4 times slower than the previous built with MinGW; also, CPU and GPU gave similar slow speed). So, I built using CMake with MinGW. However, GPU updater is not available when called from Python, meaning it's not built properly. I'm on Windows 10.

Since make doesn't work, I had to compile submodule separately as in this link (https://www.ibm.com/developerworks/community/blogs/jfp/entry/Installing_XGBoost_For_Anaconda_on_Windows?lang=en).

Any suggestions/comments/inputs are appreciated.

**Comment by RAMitchell** [comment]
Please confirm you built the project in release mode and not in debug mode through visual studio.

Cuda code cannot be built with mingw, only visual studio when using Windows.

**Comment by esb797** [comment]
I did built the project in release mode. I got errors and then it worked. The version of Visual Studio is Enterprise.

**Comment by esb797** [comment]
Is there a way to control memory allocation? Regardless of machines I use (GeForce or Tesla), it always allocates 8 MB:
"Allocated 8/total MB on GeForce (or Tesla) GPU."
