### ISSUE TITLE
[jvm-package] new dependencies

### ISSUE THREAD

**Issue by geoHeil** [dmlc/xgboost#1858]
The latest changes in the jvm-package result in a new dependency which is required. 

```
Error:Error while importing SBT project:<br/>...<br/><pre>[info] Resolving joda-time#joda-time;2.9.3 ...
[info] Resolving org.apache.thrift#libthrift;0.9.2 ...
[info] Resolving org.apache.thrift#libfb303;0.9.2 ...
[info] Resolving jline#jline;2.12.1 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.typesafe.akka#akka-actor_${scala.binary.version};2.3.11: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.typesafe.akka:akka-actor_${scala.binary.version}:2.3.11
[warn] 		  +- ml.dmlc:xgboost4j:0.7
[warn] 		  +- ml.dmlc:xgboost4j-spark:0.7 (/build.sbt#L18-32)
[warn] 		  +- at.ac.tuwien.thesis.heiler:neverpayers_2.11:0.0.1.SNAPSHOT
```

**Comment by geoHeil** [comment]
Strangely this problem went away after recompiling. Now the library is loaded even without further manually specifying this dependency.

**Comment by geoHeil** [comment]
Unfortunately, I need to reopen this issue:` ${scala.binary.version}` is not resolved properly in the published jar. This breaks the loading of transitive dependencies like AKKA.

**Comment by CodingCat** [comment]
I didn't get that why scala.binary.version is resolved for Spark packages but not Akka ones?

**Comment by geoHeil** [comment]
The thing is. Me neither. 
But the problem no longer occurs with the proposed fix.

I could observe these things:
  - this issue occurs when `"ml.dmlc" % "xgboost4j-spark" % xgboost,` is included in `build.sbt`
 - the `com.typesafe.akka#akka-actor_${scala.binary.version};2.3.11` cannot be resolved
 - strangely a depdendency requests / changes the scala version to 2.12 (even though I fixed it at 2.11)

**Comment by CodingCat** [comment]
would you identify which one requests 2.12???? (surprise me....)

and 

you're using sbt?

**Comment by geoHeil** [comment]
Indeed. I am using sbt. On monday I will be able to tell you which depdendency exactly caused the problem. 

https://github.com/dmlc/xgboost/tree/master/jvm-packages/xgboost4j-example which is a maven project works just fine and does not show these problems for the latest version.

**Comment by geoHeil** [comment]
I could track down the problem:

Expected all dependencies to require Scala version: 2.11.8
[WARNING]  com.typesafe.akka:akka-actor_2.11:2.3.11 requires scala version: 2.11.5
[WARNING] Multiple versions of scala libraries detected!

**Comment by geoHeil** [comment]
@CodingCat I finally found the source of the problem: sbt is not properly interpreting the properties defined in a non-default location (you are using the per maven profile section for that).

I tried to get some awareness at sbt but so far no one has responded.
