### ISSUE TITLE
[jvm-packages] when I use mvn package meet the error:

### ISSUE THREAD

**Issue by rainfalj** [dmlc/xgboost#1860]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System:windows

Compiler:mvn package  jvm java7
Package used (python/R/jvm/C++):

`xgboost` version used: 0.7  

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`)
2. Logs will be helpful (If logs are large, please upload as attachment).

If you are using python package, please provide

1. The python version and distribution
2. The command to install `xgboost` if you are not installing from source

If you are using R package, please provide

1. The R `sessionInfo()`
2. The command to install `xgboost` if you are not installing from source

## Steps to reproduce

1.
2.
3.

## What have you tried?

1.
2.
3.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[2] (regexp) Regexp                           Singleline: No trailing whitespace allowed.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[7] (regexp) Regexp                           Singleline: No trailing whitespace allowed.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[23] (sizes) LineLe                           ngth: Line is longer than 100 characters (found 104).
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[28,16] (modifier)                            ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[28,37] (naming) Me                           thodName: Method name 'XGBGetLastError' must match pattern '^[a-z][a-z0-9][a-zA-                           Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[30,16] (modifier)                            ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[30,34] (naming) Me                           thodName: Method name 'XGDMatrixCreateFromFile' must match pattern '^[a-z][a-z0-                           9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[32,9] (modifier) M                           odifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[32,27] (naming) Me                           thodName: Method name 'XGDMatrixCreateFromDataIter' must match pattern '^[a-z][a                           -z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[35] (sizes) LineLe                           ngth: Line is longer than 100 characters (found 101).
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[35,16] (modifier)                            ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[35,34] (naming) Me                           thodName: Method name 'XGDMatrixCreateFromCSREx' must match pattern '^[a-z][a-z0                           -9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[38] (sizes) LineLe                           ngth: Line is longer than 100 characters (found 101).
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[38,16] (modifier)                            ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[38,34] (naming) Me                           thodName: Method name 'XGDMatrixCreateFromCSCEx' must match pattern '^[a-z][a-z0                           -9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[41,16] (modifier)                            ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[41,34] (naming) Me                           thodName: Method name 'XGDMatrixCreateFromMat' must match pattern '^[a-z][a-z0-9                           ][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[44,16] (modifier)                            ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[44,34] (naming) Me                           thodName: Method name 'XGDMatrixSliceDMatrix' must match pattern '^[a-z][a-z0-9]                           [a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[46,16] (modifier)                            ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[46,34] (naming) Me                           thodName: Method name 'XGDMatrixFree' must match pattern '^[a-z][a-z0-9][a-zA-Z0                           -9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[48,16] (modifier)                            ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[48,34] (naming) Me                           thodName: Method name 'XGDMatrixSaveBinary' must match pattern '^[a-z][a-z0-9][a                           -zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[50,16] (modifier)                            ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[50,34] (naming) Me                           thodName: Method name 'XGDMatrixSetFloatInfo' must match pattern '^[a-z][a-z0-9]                           [a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[52,16] (modifier)                            ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[52,34] (naming) Me                           thodName: Method name 'XGDMatrixSetUIntInfo' must match pattern '^[a-z][a-z0-9][                           a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[54,16] (modifier)                            ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[54,34] (naming) Me                           thodName: Method name 'XGDMatrixSetGroup' must match pattern '^[a-z][a-z0-9][a-z                           A-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[56,16] (modifier)                            ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[56,34] (naming) Me                           thodName: Method name 'XGDMatrixGetFloatInfo' must match pattern '^[a-z][a-z0-9]                           [a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[58,16] (modifier)                            ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[58,34] (naming) Me                           thodName: Method name 'XGDMatrixGetUIntInfo' must match pattern '^[a-z][a-z0-9][                           a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[60,16] (modifier)                            ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[60,34] (naming) Me                           thodName: Method name 'XGDMatrixNumRow' must match pattern '^[a-z][a-z0-9][a-zA-                           Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[62,16] (modifier)                            ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[62,34] (naming) Me                           thodName: Method name 'XGBoosterCreate' must match pattern '^[a-z][a-z0-9][a-zA-                           Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[64,16] (modifier)                            ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[64,34] (naming) Me                           thodName: Method name 'XGBoosterFree' must match pattern '^[a-z][a-z0-9][a-zA-Z0                           -9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[66,16] (modifier)                            ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[66,34] (naming) Me                           thodName: Method name 'XGBoosterSetParam' must match pattern '^[a-z][a-z0-9][a-z                           A-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[68,16] (modifier)                            ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[68,34] (naming) Me                           thodName: Method name 'XGBoosterUpdateOneIter' must match pattern '^[a-z][a-z0-9                           ][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[70,16] (modifier)                            ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[70,34] (naming) Me                           thodName: Method name 'XGBoosterBoostOneIter' must match pattern '^[a-z][a-z0-9]                           [a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[73,16] (modifier)                            ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[73,34] (naming) Me                           thodName: Method name 'XGBoosterEvalOneIter' must match pattern '^[a-z][a-z0-9][                           a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[76,16] (modifier)                            ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[76,34] (naming) Me                           thodName: Method name 'XGBoosterPredict' must match pattern '^[a-z][a-z0-9][a-zA                           -Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[79,16] (modifier)                            ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[79,34] (naming) Me                           thodName: Method name 'XGBoosterLoadModel' must match pattern '^[a-z][a-z0-9][a-                           zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[81,16] (modifier)                            ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[81,34] (naming) Me                           thodName: Method name 'XGBoosterSaveModel' must match pattern '^[a-z][a-z0-9][a-                           zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[83,16] (modifier)                            ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[83,34] (naming) Me                           thodName: Method name 'XGBoosterLoadModelFromBuffer' must match pattern '^[a-z][                           a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[85,16] (modifier)                            ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[85,34] (naming) Me                           thodName: Method name 'XGBoosterGetModelRaw' must match pattern '^[a-z][a-z0-9][                           a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[87,16] (modifier)                            ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[87,34] (naming) Me                           thodName: Method name 'XGBoosterDumpModel' must match pattern '^[a-z][a-z0-9][a-                           zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[90,16] (modifier)                            ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[90,34] (naming) Me                           thodName: Method name 'XGBoosterGetAttr' must match pattern '^[a-z][a-z0-9][a-zA                           -Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[91,16] (modifier)                            ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[91,34] (naming) Me                           thodName: Method name 'XGBoosterSetAttr' must match pattern '^[a-z][a-z0-9][a-zA                           -Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[92,16] (modifier)                            ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[92,34] (naming) Me                           thodName: Method name 'XGBoosterLoadRabitCheckpoint' must match pattern '^[a-z][                           a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[93,16] (modifier)                            ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[93,34] (naming) Me                           thodName: Method name 'XGBoosterSaveRabitCheckpoint' must match pattern '^[a-z][                           a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[96,16] (modifier)                            ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[96,34] (naming) Me                           thodName: Method name 'RabitInit' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]                           *$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[97,16] (modifier)                            ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[97,34] (naming) Me                           thodName: Method name 'RabitFinalize' must match pattern '^[a-z][a-z0-9][a-zA-Z0                           -9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[98,16] (modifier)                            ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[98,34] (naming) Me                           thodName: Method name 'RabitTrackerPrint' must match pattern '^[a-z][a-z0-9][a-z                           A-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[99,16] (modifier)                            ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[99,34] (naming) Me                           thodName: Method name 'RabitGetRank' must match pattern '^[a-z][a-z0-9][a-zA-Z0-                           9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[100,16] (modifier)                            ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[100,34] (naming) M                           ethodName: Method name 'RabitGetWorldSize' must match pattern '^[a-z][a-z0-9][a-                           zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[101,16] (modifier)                            ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[101,34] (naming) M                           ethodName: Method name 'RabitVersionNumber' must match pattern '^[a-z][a-z0-9][a                           -zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[105,9] (modifier)                            ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[105,27] (naming) M                           ethodName: Method name 'RabitAllreduce' must match pattern '^[a-z][a-z0-9][a-zA-                           Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[107] (regexp) Rege                           xpSingleline: No trailing whitespace allowed.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] xgboost-jvm ........................................ SUCCESS [ 44.583 s]
[INFO] xgboost4j .......................................... FAILURE [  7.573 s]
[INFO] xgboost4j-spark .................................... SKIPPED
[INFO] xgboost4j-flink .................................... SKIPPED
[INFO] xgboost4j-example .................................. SKIPPED
[INFO] ------------------------------------

**Comment by CodingCat** [comment]
are you imposing some customized style checker? I cannot reproduce it

**Comment by CodingCat** [comment]
any update on this?

**Comment by xmbipb** [comment]
Also have the same errors. Win 10 64 Bit.
Why is not it possible to provide a JAR somewhere?

**Comment by Frank111** [comment]
@xmbipb I agree, it’s better to provide a JAR for windows OS
