### ISSUE TITLE
feature importance plot label overlap

### ISSUE THREAD

**Issue by xgdgsc** [dmlc/xgboost#1862]
## Environment info
Operating System:

Windows 10 x64

Compiler:

Package used (python/R/jvm/C++):

python

`xgboost` version used:

0.6

If you are using python package, please provide

1. The python version and distribution

python 3.5.2 in anaconda 64bit

2. The command to install `xgboost` if you are not installing from source

wheel package from http://www.lfd.uci.edu/~gohlke/pythonlibs/#xgboost .

## Steps to reproduce

1. Train a model using gb_classifier = xgb.XGBClassifier() , gb_classifier.fit()
2. xgb.plot_importance(gb_classifier ,  height=0.2)
3. see the image

![image](https://cloud.githubusercontent.com/assets/1189869/21077772/778cce3a-bf91-11e6-921b-2a4328e2053a.png)

The labels along y axis overlap badly. How can I fix the plot?

**Comment by AbdealiJK** [comment]
Get the fscores manually and use a complete feature filled plotting library to plot it better ... this is a very basic visualization meant for quickly seeing the results..

Reference: https://github.com/dmlc/xgboost/blob/master/python-package/xgboost/plotting.py#L14
