### ISSUE TITLE
xgboost CRAN version vs dev version AUC scores are very different

### ISSUE THREAD

**Issue by shashisingh** [dmlc/xgboost#1864]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System: CentOS 6.8

Compiler: gcc version 4.8.2 20140120 (Red Hat 4.8.2-15) (GCC) 

Package used (python/R/jvm/C++): R

`xgboost` version used: CRAN version (0.4-4) and dev version latest from github 

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`) 49bdb5c97fccd81b1fdf032eab4599a065c6c4f6
2. Logs will be helpful (If logs are large, please upload as attachment).

If you are using python package, please provide

1. The python version and distribution
2. The command to install `xgboost` if you are not installing from source

If you are using R package, please provide

1. The R `sessionInfo()`
2. The command to install `xgboost` if you are not installing from source

## Steps to reproduce (scenario)

I am working on a binary classification modeling problem. I am using xgboost trying to get better AUC score than other models like glm, SVM etc. that I have tried before on the same problem. I started with CRAN version of xgboost package and then made another attempt using latest checked out code from github. 

In my project, there are a few numeric variables and a significant number of categorical variables. I use model.matrix to convert categorical variables to numerical variables. The output of model.matrix is then converted to xgb.DMatrix and it is then used for xgb.cv and xgb.train functions. 

My cross validation AUC score (maximum test_auc_mean for 10000 rounds) with CRAN version was 0.77. But when I use the latest dev version, my max test_auc_mean score for 10K rounds reduces sharply to 0.71. These results are with linear booster. For tree booster, I see similar decline in test_auc_mean score when changing from CRAN to latest dev version of xgboost. During cross validation I am using a grid to try a set of parameter. An example of the grid for linear booster is shown below 

xgb_grid_linear <- expand.grid(
            eta = c(0.000001,0.00001,0.0001,0.001),
            alpha = c(0.01,0.10,0.50,1.00),
            lambda = c(0.0000206161,0.000206161,0.00206161,0.0206161)
          )
In addition to these parameters. I am using scale_pos_weight = (number_of_negative_cases)/(number_of_positive_cases) as suggested in the documentation. Reason to use scale_pos_weight is that the data is imbalanced (85% negatives versus 15% positives).

Any help/insight highly appreciated.

**Comment by Laurae2** [comment]
Make sure you are using the same value for missing values. CRAN and dev versions are different on this specific part (CRAN=0, dev=NA), and it causes headaches to users. This should be the reason you see such high difference.

In addition, if you use multithreading on gblinear, results are not reproducible (you must use nthread = 1).
