### ISSUE TITLE
Problem installing xgboost on python 3.5

### ISSUE THREAD

**Issue by MachineTeacher** [dmlc/xgboost#1884]
Hi

I'm trying to install xgboost-0.6a2 on my python 3.5 (over Anaconda), which runs on win 8.1 64 bit. The installation method is the traditional PIP, which is directed to the PyPI repository.
Here is the error message i'm getting:

> C:\Users\Yaron\Documents\Data_Science\Intsights_Assignment_python_35>pip install xgboost
> Collecting xgboost
>   Using cached xgboost-0.6a2.tar.gz
> No files/directories in c:\users\yaron\appdata\local\temp\pip-build-qsfrwo\xgboost\pip-egg-info (from PKG-INFO)

I guess a preliminary process is required, but i'm not sure what it is...
Please help : )

**Comment by jeffheaton** [comment]
Same issue

**Comment by creiser** [comment]
+1

**Comment by arijeet777** [comment]
+1

**Comment by fulyacelebi** [comment]
+1

**Comment by WUhailing** [comment]
+1

**Comment by ShiangYong** [comment]
This solution is simple and it worked for me http://stackoverflow.com/a/39811079

**Comment by rakshithvasudev** [comment]
Yes, https://stackoverflow.com/a/39811079 worked for me too.

**Comment by rohitpawar007489** [comment]
Yes it worked for me as well. Thanks for help

**Comment by misseuro** [comment]
works for me as well! Thanks!

**Comment by Albelt** [comment]
Thank your

**Comment by PremKumar135** [comment]
please someone explain the  steps to do it.. i have an error "cannot import name XGBClassifier

**Comment by sachinb4u** [comment]
+1

**Comment by bunmalik** [comment]
Pls any help to get it work for me with sealang and seasnake installation!

**Comment by dentiny** [comment]
It really works! Thanks for help!
