### ISSUE TITLE
Question on training xgboost by considering both ranking and classification

### ISSUE THREAD

**Issue by hurui1983** [dmlc/xgboost#1887]
Hi,

I have above question that if for a given data set, i want to optimize the pairwise ranking loss + pointwise classification loss, is there a way to do this? My understanding is that in order for Xgboost to train a pairwise ranking model, we need to have group info to group the train instances. so what i want is to minimize the sum loss of pairwise loss and point wise in the group and sum average all groups together. If it's not supported yet, any suggestions on possible solution to modify the original tool to support this?

**Comment by pommedeterresautee** [comment]
Pairwise means the algo compare pairs of documents, pointwise means the algo tries a kind of classification. It doesn t make sense to try to do it both.
