### ISSUE TITLE
why is xgboost-crossvalidation unable to help select best model?

### ISSUE THREAD

**Issue by gypsysunny** [dmlc/xgboost#1888]
Please see the example in xgboost/jvm-packages/xgboost4j-example/src/main/scala/ml/dmlc/xgboost4j/scala/example/CrossValidation.scala. I am not able to see any real cv funactionality and the returned value of crossValidation is just the changing process of error ratio. why cann't it return a best model or stuff like that?

thanks!

**Comment by pommedeterresautee** [comment]
Old question, no answer. Closing
