### ISSUE TITLE
dump_model and get_score output wrong values

### ISSUE THREAD

**Issue by DeepVoltaire** [dmlc/xgboost#1892]
There seems to be an issue with the model dumping. I trained a model with 50 trees and the dump showed 1209 trees. Many of those showed weird behaviour, e.g. they are just stumps or have very high or very low gain values. This in turn messes with the get_score function and outputs wrong values.

I tried reinstalling xgboost to the most recent version, but the bug remains.

**Comment by pommedeterresautee** [comment]
Old question, no answer, closing
