### ISSUE TITLE
Building with GPU plugin could make CPU mode slower

### ISSUE THREAD

**Issue by tks0123456789** [dmlc/xgboost#1893]
I built XGBoost with GPU plugin and ran [benchmarks](https://github.com/RAMitchell/boosting_tree_benchmarks/tree/master/xgboost) which I think were used to generate [CPU/GPU benchmarks](https://github.com/dmlc/xgboost/blob/master/plugin/updater_gpu/README.md#benchmarks).
I used the same parameter values except nthread=8.

I got similar result.
Dataset, i7-4790K, GTX1070, Speedup
Yahoo LTR, 3824, 629, 6.08
Higgs, 31798, 3681, 8.64

Then I built XGB without GPU plugin and ran the same benchmarks.
Dataset, i7-4790K, Speedup compared to the above i7-4790K
Yahoo LTR, 979, 3.91
Higgs, 16080, 1.98

I think building with gpu plugin somehow slow down cpu mode, but
I don't know how to fix this. Any ideas?

Benchmark results and logs are [here](https://github.com/tks0123456789/boosting_tree_benchmarks)

## Environment info
XGBoost   [cee4aaf](https://github.com/dmlc/xgboost/tree/cee4aafb93982a21e4fde10d202b3da1910934bf)
CPU	i7-4790K
MEM	32G
GPU	GTX 1070
Ubuntu	14.04.5LTS
VGA driver	367.57
gcc	4.8.4
cmake	3.7.1
CUDA	8.0
CUB	1.6.4

**Comment by tks0123456789** [comment]
It have been fixed by https://github.com/dmlc/xgboost/pull/1904. I confirmed that.
Thanks.

**Comment by RAMitchell** [comment]
You are correct. The cause was incorrect compiler options for the linux build. 

The benchmarks have been updated.
