### ISSUE TITLE
kaggle-higgs 

### ISSUE THREAD

**Issue by AlexYoung757** [dmlc/xgboost#1896]
when i run below code ，there is something wrong 
xgmat <- xgb.DMatrix(data, label = label, weight = weight, missing = -999.0)

the error is：
amalgamation/../dmlc-core/src/io/local_filesys.cc:66 LocalFileSystem.GetPathInfo 100001 Error:No such file or directory

this is the demo file higgs-pred

**Comment by puneetjindal** [comment]
My system has windows 10.
I am getting a similar error as following

"amalgamation/../dmlc-core/src/io/local_filesys.cc:86: LocalFileSystem.ListDirectory 3/10 error: No such file or directory"

**Comment by phunterlau** [comment]
What is your data path?

**Comment by AxenGitHub** [comment]
I have exactly the same problem. 
The data to be used for training is loaded in memory and the files are local to the source code.
Using Windows 10 with R 3.3.3

**Comment by chano88** [comment]
Same problem occured in 2017 Oct.
