### ISSUE TITLE
[jvm-package] xgboost4j spark pipeline persistence

### ISSUE THREAD

**Issue by geoHeil** [dmlc/xgboost#1900]
xgboost4j does not support sparks pipeline persistence
` java.lang.UnsupportedOperationException: Pipeline write will fail on this Pipeline because it contains a stage which does not implement Writable. Non-Writable stage: XGBoostClassificationModel
`
Is there any way to access the raw model (file)? / Is persistence supported in xgboost4j elsewhere?

**Comment by xydrolase** [comment]
You can always call `saveModelAsHadoopFile` on a `XGBoostModel` object to persist it.
And later load the dump file using `ml.dmlc.xgboost.scala.spark.loadModelFromHadoopfile`.

**Comment by geoHeil** [comment]
Is there a spark integration with pipeline persistence was not added yet? If not I might find some time to make a PR

**Comment by xydrolase** [comment]
Probably it's better to ask @CodingCat if it's on the roadmap or not.

**Comment by CodingCat** [comment]
...GitHub email notification just sucks

feel free to contribute it

**Comment by geoHeil** [comment]
@CodingCat I started to prepare something here https://github.com/geoHeil/xgboost/blob/sparkPipelinePersistence/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostModel.scala But am facing a problem 
`implicit sc: SparkContext`

cannot be resolved in the load / write context. Could you pass me a hint where to get hold of the sparkContext in `XGBoostModel`

**Comment by xydrolase** [comment]
`MLWriter` extends the trait `BaseReadWrite`, which provides an internal SparkContext object.
You can check out the implementation of `PipelineWriter` to see how it uses SparkContext.

**Comment by geoHeil** [comment]
https://github.com/dmlc/xgboost/pull/1906
