### ISSUE TITLE
Error with "reg:tweedie"

### ISSUE THREAD

**Issue by shahlaebrahimi** [dmlc/xgboost#1907]
Hello.
I installed XGBoost based on the instructions provided [here] for Anaconda 3.4 (Python 3.5) on Windows 10(https://www.ibm.com/developerworks/community/blogs/jfp/entry/Installing_XGBoost_For_Anaconda_on_Windows?lang=en). It seems that xgboost 0.6 is already installed but if I use "reg:tweedie", this error is reported:

`xgboost.core.XGBoostError: b'[23:08:27] src/objective/objective.cc:21: Unknown objective function reg:tweedie'`

It works well with "reg:linear". Also, there is some problem with determining feature importance. I use XGBRegressor.
Thanks in advance.
Best regards,

**Comment by pommedeterresautee** [comment]
Old question, no answer. Closing

**Comment by pallavbakshi** [comment]
Can you link the question or solution to this?

**Comment by khotilov** [comment]
The solution is to install xgboost code that is recent enough to have Tweedie (not from pypi).
