### ISSUE TITLE
Failed to compile xgboost in windows 10(64bit)

### ISSUE THREAD

**Issue by hisashi-tanaka** [dmlc/xgboost#1913]
Operating System:
Compiler:mingw32-make.exe
Package used:Python 3.5.1  Anaconda 2.4.1
`xgboost` version used:The newest in Git, but put 'git checkout 9a48a40'
 The command to install `xgboost` if you are not installing from source
git clone --recursive https://github.com/dmlc/xgboost
cd xgboost
git checkout 9a48a40
git submodule init
git submodule update
Then,
1.Install MinGW-W64
2.Set the path on my PC(windows10 64bit)
3.Compile
alias make='mingw32-make'
cp make/mingw64.mk config.mk
make -j4
Then I got an error as follows:
・・・・・(omitted)
In file included from C:/mingw64-w64/mingw64/lib/gcc/x86_64-w64-mingw32/6.2.0/include/c++/ext/string_conversions.h:41:0,
                 from C:/mingw64-w64/mingw64/lib/gcc/x86_64-w64-mingw32/6.2.0/include/c++/bits/basic_string.h:5402,
                 from C:/mingw64-w64/mingw64/lib/gcc/x86_64-w64-mingw32/6.2.0/include/c++/string:52,
                 from dmlc-core/include/dmlc/io.h:9,
                 from include/xgboost/tree_model.h:10,
                 from src/tree/tree_model.cc:6:
C:/mingw64-w64/mingw64/lib/gcc/x86_64-w64-mingw32/6.2.0/include/c++/cstdlib:180:3: note: candidate: long long int std::abs
(long long int)
   abs(long long __x) { return __builtin_llabs (__x); }
   ^~~
Makefile:97: recipe for target 'build/tree/tree_model.o' failed
mingw32-make: *** [build/tree/tree_model.o] Error 1
mingw32-make: *** Waiting for unfinished jobs....

I am novice at Python, and thanks for your advice in advance.

Hisashi Tanaka(hisatan)

**Comment by philipus** [comment]
have the same problem

**Comment by shenweichen** [comment]
i have the same problem,too

**Comment by philipus** [comment]
thanks!!!

**Comment by hisashi-tanaka** [comment]
Thanks for help and a bit progress, but unfortunately failed as follows:
(omitted)
a - build/tree/updater_prune.o
Makefile:128: recipe for target 'xgboost' failed
mingw32-make: *** [xgboost] Error 1
mingw32-make: *** Waiting for unfinished jobs....
g++: error: rabit/lib/librabit.a: No such file or directory
Makefile:120: recipe for target 'lib/libxgboost.dll' failed
mingw32-make: *** [lib/libxgboost.dll] Error 1

Please advice,thanks.

**Comment by khotilov** [comment]
With the commit 9a48a40, you are checking out a version of code dated Jun 5th. The fix for std::abs in newer gcc versions was submitted on Jun 29th #1308. If you really *have* to use the old code from Jun 5th, just add the modification from #1308 by hand.

**Comment by hisashi-tanaka** [comment]
Thanks!!!! Xgboost is installed.

**Comment by shenweichen** [comment]
Thanks,check out to the latest version,it solves the problem.

**Comment by pyd1data** [comment]
Thank you schenweichen, using #include <cmath> it worked perfectly!
