### ISSUE TITLE
subsample doesn't work in grow_gpu

### ISSUE THREAD

**Issue by tks0123456789** [dmlc/xgboost#1915]
@RAMitchell 
I tried setting subsample=0.1, and got out of memory error.

XGBoost: 7948d1c7998eeb205f13740c5a1bb3f381c37b6a (latest)
```
xgboost/xgboost xgb.conf tree_method=exact updater=grow_gpu subsample=0.1 data="../data/higgs.train" objective="binary:logistic"
[15:23:34] 10500000x28 matrix with 294000000 entries loaded from ../data/higgs.train
[15:23:34] boosting round 0, 0 sec elapsed
CUDA error: /home/tks/download/xgb/xgboost/plugin/updater_gpu/src/device_helpers.cuh(383): out of memory
```

It worked in older version(one commit before b49b33918300f892f207630234f76c83e9d07036).
XGBoost: cee4aafb93982a21e4fde10d202b3da1910934bf (10 days ago)
```
xgboost/xgboost xgb.conf tree_method=exact updater=grow_gpu subsample=0.1 data="../data/higgs.train" objective="binary:logistic"
[15:24:08] 10500000x28 matrix with 294000000 entries loaded from ../data/higgs.train
[15:24:08] boosting round 0, 2.38419e-07 sec elapsed
[15:24:26] Subsampling 10% of rows.
[15:24:36] Allocated 1227/7704 MB on GeForce GTX 1070
[15:24:39] [0]
[15:24:39] boosting round 1, 31.1215 sec elapsed
[15:24:42] [1]
[15:24:42] update end, 34.5417 sec in all
```

xgb.conf
```eta = 0.1
max_depth = 12
num_round = 2
min_child_weight=100
nthread=8
```
## Environment info
CPU	i7-4790K
MEM	32G
GPU	GTX 1070
Ubuntu	14.04.5LTS
VGA driver	375.26
gcc	4.8.4
cmake	3.7.1
CUDA	8.0
CUB	1.6.4

**Comment by RAMitchell** [comment]
This previous version incorrectly implemented the subsample parameter.

The entire dmatrix must be loaded regardless of the subsample parameter in this (correct) version. This is the intended behaviour.

If you run out of memory you need to use a smaller input matrix. See the GPU acceleration demo for an example of selecting a subset of a very large file.

**Comment by tks0123456789** [comment]
Thanks.
