### ISSUE TITLE
[jvm_package] how to set num_workers in estimator API

### ISSUE THREAD

**Issue by geoHeil** [dmlc/xgboost#1917]
How can I set `num_workers`
`val model = XGBoost.train(trainRDD, paramMap, numRound, nWorkers = 5, useExternalMemory = true)`
when using `XGBoostEstimator`, xgboosts integration in sparks pipelines.

**Comment by CodingCat** [comment]
set `nworkers` in paramMap

**Comment by CodingCat** [comment]
what do you mean by `num_workers`

**Comment by CodingCat** [comment]
https://github.com/dmlc/xgboost/blob/master/doc/parameter.md nthread?

**Comment by geoHeil** [comment]
https://github.com/dmlc/xgboost/blob/master/jvm-packages/xgboost4j-example/src/main/scala/ml/dmlc/xgboost4j/scala/example/spark/SparkWithDataFrame.scala
line 28 the number of rabit nodes. At least in the readme examples it is
used explicitly
Nan Zhu <notifications@github.com> schrieb am Fr. 30. Dez. 2016 um 01:52:

**Comment by CodingCat** [comment]
the number of rabit nodes equals to the number of tasks/partitions of training data, so `nWorkers = args(1)` does the job

**Comment by geoHeil** [comment]
So I do not need to configure this property as it should work automatically?


What about node discovery? Do I need to set this somewhere or are these set
up automatically based on spark workers nodes?
Nan Zhu <notifications@github.com> schrieb am So. 1. Jan. 2017 um 06:45:

**Comment by xydrolase** [comment]
Set `nworkers` in paramMap, and the XGBoostEstimator will pick it up.

**Comment by xydrolase** [comment]
If you do not set it, it will by default be set to 1. 

For some automatic configuration, you can perhaps read the Spark configuration `spark.executor.instances`, and set `nworkers` equal to this number.

**Comment by CodingCat** [comment]
@geoHeil , you do not need to do that, the magic is in https://github.com/dmlc/xgboost/blob/master/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala#L175. And it is not anything related to worker/executor nodes, it is only related to the expected number of partitions of your training data

`worker` as the name of configuration entry is kind of confusing, but it is to be consistent within the XGBoost Context

@xydrolase , nworkers is actually the number of partitions, so it shouldn't be anything related to Spark executor

**Comment by geoHeil** [comment]
Thanks for this clarification.

**Comment by xydrolase** [comment]
@CodingCat Sure, there is no direct connection between executor number and nworkers, and I reckon that.

I normally set up the distributed training by allocating multiple cores to an executor, and avoid having multiple tasks under the same executor, so that an executor can use all the cores of a specific node in the cluster, and runs only one task. The idea is to reduce the number of partitions, so that there are less synchronization between Rabit workers, which seem to cause slowdowns.
