### ISSUE TITLE
-msse2 prevents the compilation on ARM and other (non-x86) architectures

### ISSUE THREAD

**Issue by lazydroid** [dmlc/xgboost#1921]
Operating System: Raspbian on Raspberry PI
Package used (python/R/jvm/C++): Python
`xgboost` version used: latest from pip repository

## Steps to reproduce

1. sudo pip install xgboost
2. **unrecognized command line option ‘-msse2’**

## What have you tried?

1. remove '-msse2' from all Makefiles
2. recompile
3. enjoy!

**Comment by pommedeterresautee** [comment]
Old question, no answer. Closing
