### ISSUE TITLE
weights for non-leaf nodes 

### ISSUE THREAD

**Issue by ihadanny** [dmlc/xgboost#1930]
Is it possible to compute weights for non-leaf nodes as well? 
This will enable interpreting results according to their decision paths: http://blog.datadive.net/interpreting-random-forests/

**Comment by pommedeterresautee** [comment]
Purity scores are provided in the dump of the model

**Comment by ihadanny** [comment]
hey @pommedeterresautee , I don't understand - are "purity scores" the same as weights?

**Comment by pommedeterresautee** [comment]
http://xgboost.readthedocs.io/en/latest/model.html

**Comment by ihadanny** [comment]
Thanks for your patience and sorry to keep on insisting, but I don't think that is what needed to implement the above approach for interpreting XGB results in terms of value changes along the prediction path, as described in the [interpreter blog](http://blog.datadive.net/interpreting-random-forests/). 

The purity score you provide in the model is the gain in splitting the node, and it includes the regularization term! What I need is a weighted average of the weights of the leaf nodes, assuming the tree structure is constant. How do you suggest I'll get that from the dump of the model?

**Comment by khotilov** [comment]
@ihadanny If you really need those, they can be relatively easily computed using covers as weights when averaging values of branches for each node. There is a [function within core framework which computes them](https://github.com/dmlc/xgboost/blob/6bd1869026eb66a542ccd8573f1e4b098a8cf7c6/include/xgboost/tree_model.h#L564), but the text dump is for it is not implemented. 

BTW, the datadive-like interpretation of predictions was already implemented #2003 , and there is a better option in the works #2438 .
