### ISSUE TITLE
[R] CRAN checking error due to the update in DiagrammeR

### ISSUE THREAD

**Issue by thirdwing** [dmlc/xgboost#1934]
https://cran.r-project.org/web/checks/check_results_xgboost.html

There is some change in `DiagrammeR`. `xgboost` can't pass CRAN check. Actually this also breaks `mxnet`.

@hetong007

**Comment by khotilov** [comment]
I can take care of that tomorrow evening. I had to do similar adjustments in some of my personal code due to the changes in DiagrammeR.

**Comment by hetong007** [comment]
I have just made a PR for the fix.

**Comment by khotilov** [comment]
I see. That should be good enough for it to run, but the trees probably look horrible with just those changes. I can add some touchups tomorrow, or if you want to you might look into global attributes and attribute themes.

**Comment by hetong007** [comment]
Since the plot style is changed and needs to be fixed in a future submission, I reopened this issue to track the progress.
