### ISSUE TITLE
Different predictions between versions 0.4 and .6

### ISSUE THREAD

**Issue by kn3in** [dmlc/xgboost#1938]
First of all thank you for the awesome package!!!

A multi-class classification model trained in R package version 0.4;  
predictions using the model differ between versions 0.4 and 0.6
*only* if one of the features equals to zero (0.0) and the feature is zero
for at least one class.

Install version 0.4-4
```{r}
library(devtools)
install_version("xgboost", "0.4-4")
```

Example is a modification of a test in the R package
```{r}
library(xgboost)

## Make one feature == 0 for all samples in a class
iris[1:50, 1] <- 0.0

lb <- as.numeric(iris$Species) - 1
bst <- xgboost(data = as.matrix(iris[, -5]), label = lb,
               max_depth = 3, eta = 0.5, nthread = 2, nrounds = 5,
               objective = "multi:softprob", num_class = 3)
               
pred_v04 <- predict(bst, as.matrix(iris[, -5]))

## Save model and predictions result for version 0.4
save(bst, pred_v04, file = "IRIS_pred_and_model_v04.RData")
```

In new session install version 0.6
```
library(devtools)
install_version("xgboost", "0.6-4")
```

Get model and predictions for version 0.4
```
library(xgboost)
load("IRIS_pred_and_model_v04.RData")
iris[1:50, 1] <- 0.0
```

Re-predict using latest version and compare results
```
pred_v06 <- predict(bst, as.matrix(iris[, -5]))
all.equal(pred_v04, pred_v06)
[1] "Mean relative difference: 1.809"
```

* Setting only some of the feature values for the class to zero does *not* cause
difference. (i.e.  `iris[1:5, 1] <- 0.0` does nothing).

* Setting a feature to a non-zero value for a class does *not* cause difference either
(i.e. iris[1:50, 1] <- 0.1 does nothing)

* SessionInfo()
```
R version 3.3.1 (2016-06-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 15.10

locale:
 [1] LC_CTYPE=en_AU.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_AU.UTF-8        LC_COLLATE=en_AU.UTF-8
 [5] LC_MONETARY=en_AU.UTF-8    LC_MESSAGES=en_AU.UTF-8
 [7] LC_PAPER=en_AU.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_AU.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] xgboost_0.6-4

loaded via a namespace (and not attached):
[1] magrittr_1.5      Matrix_1.2-7.1    tools_3.3.1       stringi_1.1.2
[5] grid_3.3.1        data.table_1.10.0 lattice_0.20-34
```

**Comment by tqchen** [comment]
There is a specification change that changes the missing value spec to NA in 0.47 https://github.com/dmlc/xgboost/blob/master/NEWS.md#v047-20160114

The different behavior was due to this, to recover old behavior, manually set missing=0 during DMatrix construction

**Comment by kn3in** [comment]
Thank you!
Yay, you are right missing = 0 fixes it.
I've came across this while using caret wrapper with a model trained with xgboost v0.4-4, not sure if the current CRAN version got it but just in case here is the commit which switches to using NA as missing values
https://github.com/topepo/caret/commit/c060b14076ee7db5b70e05ca32edaeb96d74e7c8
K.
