### ISSUE TITLE
"various undefined errors"

### ISSUE THREAD

**Issue by guohaoqiang** [dmlc/xgboost#1943]
redhat

Compiler:
gcc4.8.4

my commit hash (`87e897f428c069904fd7183b69ed75fce67e1b6c`)

When compiled xgboost via "make", I got various "undefined ......",like:

build/data/data.o: In function `xgboost::data::SparsePage::Format::Create(std::string const&)':
data.cc:(.text+0xd8e): undefined reference to `std::__throw_bad_function_call()'
build/data/sparse_page_dmatrix.o: In function `xgboost::data::SparsePageDMatrix::InitColAccess(std::vector<bool, std::allocator<bool> > const&, float, unsigned long)':
sparse_page_dmatrix.cc:(.text+0x569e): undefined reference to `std::chrono::_V2::system_clock::now()'
sparse_page_dmatrix.cc:(.text+0x5e53): undefined reference to `std::chrono::_V2::system_clock::now()'
build/data/sparse_page_dmatrix.o: In function `dmlc::ThreadedIter<xgboost::data::SparsePage>::Init(std::function<bool ()(xgboost::data::SparsePage**)>, std::function<void ()()>)::{lambda()#1}::operator()() const':
sparse_page_dmatrix.cc:(.text._ZZN4dmlc12ThreadedIterIN7xgboost4data10SparsePageEE4InitESt8functionIFbPPS3_EES5_IFvvEEENKUlvE_clEv[_ZZN4dmlc12ThreadedIterIN7xgboost4data10SparsePageEE4InitESt8functionIFbPPS3_EES5_IFvvEEENKUlvE_clEv]+0x834): undefined reference to `std::__throw_bad_function_call()'
sparse_page_dmatrix.cc:(.text._ZZN4dmlc12ThreadedIterIN7xgboost4data10SparsePageEE4InitESt8functionIFbPPS3_EES5_IFvvEEENKUlvE_clEv[_ZZN4dmlc12ThreadedIterIN7xgboost4data10SparsePageEE4InitESt8functionIFbPPS3_EES5_IFvvEEENKUlvE_clEv]+0x839): undefined reference to `std::__throw_bad_function_call()'
build/data/sparse_page_source.o: In function `xgboost::data::SparsePageSource::Create(xgboost::DMatrix*, std::string const&)':
sparse_page_source.cc:(.text+0x2297): undefined reference to `std::chrono::_V2::system_clock::now()'
sparse_page_source.cc:(.text+0x2492): undefined reference to `std::chrono::_V2::system_clock::now()'
build/data/sparse_page_source.o: In function `xgboost::data::SparsePageSource::Create(dmlc::Parser<unsigned int>*, std::string const&)':
sparse_page_source.cc:(.text+0x42af): undefined reference to `std::chrono::_V2::system_clock::now()'
sparse_page_source.cc:(.text+0x4887): undefined reference to `std::chrono::_V2::system_clock::now()'
build/gbm/gbm.o: In function `xgboost::GradientBooster::Create(std::string const&, std::vector<std::shared_ptr<xgboost::DMatrix>, std::allocator<std::shared_ptr<xgboost::DMatrix> > > const&, float)':
gbm.cc:(.text+0x63f): undefined reference to `std::__throw_bad_function_call()'
build/gbm/gbtree.o: In function `std::_Function_handler<xgboost::GradientBooster* ()(std::vector<std::shared_ptr<xgboost::DMatrix>, std::allocator<std::shared_ptr<xgboost::DMatrix> > > const&, float), xgboost::gbm::{lambda(std::vector<std::shared_ptr<xgboost::DMatrix>, std::allocator<std::shared_ptr<xgboost::DMatrix> > > const&, float)#2}>::_M_invoke(std::_Any_data const&, std::vector<std::shared_ptr<xgboost::DMatrix>, std::allocator<std::shared_ptr<xgboost::DMatrix> > > const&, float)':
gbtree.cc:(.text+0x1792): undefined reference to `std::__detail::_Prime_rehash_policy::_M_next_bkt(unsigned long) const'
build/gbm/gbtree.o: In function `xgboost::gbm::GBTree::GBTree(float)':
gbtree.cc:(.text._ZN7xgboost3gbm6GBTreeC2Ef[_ZN7xgboost3gbm6GBTreeC5Ef]+0x12d): undefined reference to `std::__detail::_Prime_rehash_policy::_M_next_bkt(unsigned long) const'

I tried adding "-fstlc++" to CXXFLAGS, but it didn't work. I got above errors all the time.
Could anyone help me?
thanks.
![default](https://cloud.githubusercontent.com/assets/5676786/21749704/131f74fc-d5df-11e6-875c-6a76bab33417.PNG)

**Comment by ShiningSunZhenpeng** [comment]
I came into the same problem. Could you please tell me the solution you use? Thanks a lot.

**Comment by guohaoqiang** [comment]
Hi,
I think you might link wrong libs, or your complier didn’t match the libs.

Best,
hq


在 2017年3月1日，下午6:24，ShiningSunZhenpeng <notifications@github.com<mailto:notifications@github.com>> 写道：


I came into the same problem. Could you please tell me the solution you use? Thanks a lot.
