### ISSUE TITLE
Failed to make rabit on win 7

### ISSUE THREAD

**Issue by andyxjiang** [dmlc/xgboost#1951]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System: win 7 professional

Compiler: 

Package used (python/R/jvm/C++): 

`xgboost` version used: v0.6 (2016.07.29)

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`)：87e897f428c069904fd7183b69ed75fce67e1b6c
2. Logs will be helpful (If logs are large, please upload as attachment).
[compile log.txt](https://github.com/dmlc/xgboost/files/695154/compile.log.txt)
[git log.txt](https://github.com/dmlc/xgboost/files/695155/git.log.txt)

**Comment by thirdwing** [comment]
Please try to use a bash shell. We haven't test power shell for installation.

**Comment by andyxjiang** [comment]
I have tried on cygwin and it failed again. Could you guys give me some advice to deal with this problem? 
The log is as follow:
andyxjiang@andyxjiang-PC2 /cygdrive/c/Users/andyxjiang/Documents/GitHub/xgboost/  rabit
$ make
g++ -c -O3 -msse2 -Wall -Wextra -Wno-unused-parameter -Wno-unknown-pragmas -std=  c++0x -fPIC -o allreduce_base.o src/allreduce_base.cc
src/allreduce_base.cc:1:0: 警告：-fPIC 在目标机上被忽略 (所有代码都是与位置无关  的)
 /*!
 ^
In file included from src/./allreduce_base.h:18:0,
                 from src/allreduce_base.cc:14:
src/./../include/rabit/internal/utils.h: 在函数‘FILE* rabit::utils::FopenCheck(c  onst char*, const char*)’中:
src/./../include/rabit/internal/utils.h:158:38: 错误：‘fopen64’在此作用域中尚未  声明
   std::FILE *fp = fopen64(fname, flag);
                                      ^
make: *** [Makefile:52：allreduce_base.o] 错误 1

andyxjiang@andyxjiang-PC2 /cygdrive/c/Users/andyxjiang/Documents/GitHub/xgboost/  rabit

**Comment by thirdwing** [comment]
As we have said in the document

> XGBoost support both build by MSVC or MinGW.

The cygwin environment hasn't be test and support.

**Comment by khotilov** [comment]
I don't think the full rabit was ever supported on windows. 

To build a dummy rabit library:
```
make lib/librabit_empty.a -j4
```
