### ISSUE TITLE
colsample_bytree and colsample_bylevel select first columns only since 0.6

### ISSUE THREAD

**Issue by BartLJ** [dmlc/xgboost#1954]
I'm running xgboost 0.6-4 on MacOS.
If using colsample_bytree < 1 or colsample_bylevel < 1, the columns are not randomly picked, but only the first columns are selected.
It seems that the std:shuffle method in updater_colmaker.cc does not work correctly.
This works in xgboost 0.4-4 and fails to work from 0.6-0 onwards.

## Environment info
Operating System: macOS Sierra (10.12.2)

Compiler: Apple LLVM version 8.0.0 (clang-800.0.42.1)

Package used (python/R/jvm/C++): R

`xgboost` version used: 0.6-4

If you are using R package, please provide

1. The R `sessionInfo()`

R version 3.3.2 (2016-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS Sierra 10.12.2

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] magrittr_1.5      Matrix_1.2-7.1    tools_3.3.2       xgboost_0.6-4     stringi_1.1.2     grid_3.3.2       
[7] data.table_1.10.0 lattice_0.20-34 

2. The command to install `xgboost` if you are not installing from source
`install.packages("xgboost")`

## Steps to reproduce
```
require(xgboost)
train <- matrix(runif(20000), 1000, 20, dimnames=list(NULL, 1:20))
label <- rbinom(1000, 1, 0.5)
xgbtrain <- xgb.train(params=list(booster = "gbtree", colsample_bytree = 0.1),
                                             data = xgb.DMatrix(train, label = label),
                                               nrounds = 1)
xgb.importance(model = xgbtrain)
```
> Feature      Gain     Cover Frequency
1:       1 0.5064579 0.3592935 0.5106383
2:       0 0.4935421 0.6407065 0.4893617`

## What have you tried?

1. install xgboost version 0.4-4 and later:

it seems that above test works for version 0.4-4, but not anymore since 0.6-0:
```
require(xgboost)
train <- matrix(runif(20000),1000,20,dimnames=list(NULL,1:20))
label <- rbinom(1000,1,0.5)
xgbtrain <- xgb.train(params=list(booster = "gbtree", colsample_bytree = 0.1),
                                             data = xgb.DMatrix(train, label = label),
                                               nrounds = 1)
xgb.importance(model = xgbtrain)
```
> Feature      Gain     Cover Frequence
1:       2 0.5098488 0.3076663 0.5428571
2:      18 0.4901512 0.6923337 0.4571429

**Comment by BartLJ** [comment]
when manually compiling and installing xgboost from the latest sources with openmp-enabled gcc (`brew install gcc --without-multilib` as described in http://xgboost.readthedocs.io/en/latest/build.html#building-on-osx), above parameters work correctly.
It seems the problem is related to how the package has been built on CRAN.

**Comment by rfcv** [comment]
@BartLJ Should one use CRAN version 0.4.4 to not encounter this?

**Comment by BartLJ** [comment]
I tested with CRAN version 0.4-4 and this was the latest version which is still fine.

**Comment by tom-christie** [comment]
I just ran into this same problem with OS X and 0.6-4.
