### ISSUE TITLE
save the model under caret

### ISSUE THREAD

**Issue by gdupret** [dmlc/xgboost#1955]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System: Ubuntu 16.10

Compiler: gcc

Package used (python/R/jvm/C++): R

R version 3.3.2 (2016-10-31) -- "Sincere Pumpkin Patch"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

`xgboost` version used: 0.6-4

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`)
2. Logs will be helpful (If logs are large, please upload as attachment).

If you are using python package, please provide

1. The python version and distribution
2. The command to install `xgboost` if you are not installing from source

If you are using R package, please provide

1. The R `sessionInfo()`

R version 3.3.2 (2016-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.1 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] psm_0.0.1          matrixStats_0.51.0 assertthat_0.1     scales_0.4.1       ggplot2_2.2.1      digest_0.6.11      stringr_1.1.0      xgboost_0.6-4     
[9] dplyr_0.5.0       

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.8       lattice_0.20-34   plyr_1.8.4        grid_3.3.2        R6_2.2.0          gtable_0.2.0      DBI_0.5-1         magrittr_1.5     
 [9] stringi_1.1.2     lazyeval_0.2.0    data.table_1.10.0 Matrix_1.2-7.1    tools_3.3.2       munsell_0.4.3     colorspace_1.3-2  knitr_1.15.1     
[17] tibble_1.2  

2. The command to install `xgboost` if you are not installing from source

## Steps to reproduce

1. do parameter sweeping with caret for xgboost
2. save the caret train object to file
3. load the caret train object
4, xgb.save(caret_train$finalModel)

the R session crashes while executing xgb.save

## What have you tried?

1. the caret train object finalModel is a list containing additional fields. I removed these fields before calling xgb.save, but it still crashes

## Why do I need that?

I train the model in R, and I need to load the model using the python api for predictions.

**Comment by thirdwing** [comment]
Can you provide a small runnable script for this?

**Comment by gdupret** [comment]
I will work that out

best,

ged

**Comment by gdupret** [comment]
Here is the script.

Best,

ged

**Comment by thirdwing** [comment]
Hi, if you reply this email with attachment. I am afraid I can't see it.

Best,

**Comment by gdupret** [comment]
yes, I added a R script and two some small data files to reproduce the problem. https://dl.dropboxusercontent.com/u/7001766/crash_save.tgz

Best

**Comment by khotilov** [comment]
@gdupret  It's not specific to caret. If you save any xgboost model as an R object and then load it back, it would have neither an actual internal xgboost model in memory (only its saved raw binary dump) nor a valid handle/pointer to it. The `xgb.save` is currently not handling this use case properly. 

As a temporary workaround, you can do 
```R
bst <- xgboost:::xgb.Booster.check(xgb_tune$finalModel, saveraw = FALSE)
xgb.save(bst, fname = "model.xgb")
```

**Comment by gdupret** [comment]
indeed! Your workaround is what I needed. Thank you Vadim!
