### ISSUE TITLE
Incorrect handling of min_child_weight = 0 in updater_colmaker.cc

### ISSUE THREAD

**Issue by jokari69** [dmlc/xgboost#1957]
I spotted a significant difference in cv error in the first booster when setting min_child_weight =0 vs min_child_weight = 0.0001 as can be seen in the table below. My dataset contains around 2 million rows and max_depth = 3 and we can see that even without min_child_weight restrictions we have at least 50000 samples in each leave (as booster is same for min_child_weight = 0.0001 and = 50000)

min_child_weight       cv error
0.0000                         0.11451
0.0001                         0.11055
50000.0000                 0.11053

Looking at the code of updater_colmaker.cc i think it has something to do with the fact that the sum_hess is set to zero in the TStats during initializaition (with the Clear method) and therefore later comparison of the form sum_hess >= min_child_weight returns true when both are zero.
Restricting min_child_weight > 0 would be a simple solution i think.

xgboost: commit tag d23ea5ca7dd

**Comment by pommedeterresautee** [comment]
Old question, no answer. Closing
