### ISSUE TITLE
booster handle is invalid

### ISSUE THREAD

**Issue by franciszmy** [dmlc/xgboost#1958]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System: linux cent os 6+

Compiler:

Package used (python/R/jvm/C++): R

`xgboost` version used: 

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`)
2. Logs will be helpful (If logs are large, please upload as attachment).

If you are using python package, please provide

1. The python version and distribution
2. The command to install `xgboost` if you are not installing from source

If you are using R package, please provide

1. The R `sessionInfo()`

R version 3.3.1 (2016-06-21)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS release 6.8 (Final)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.3.1
2. The command to install `xgboost` if you are not installing from source

## Steps to reproduce

1. I saved a xgboost model in a RDS file, and read it to the R environment to use
2. When I read RDS file, xgboost can correctly get the model, but after I library(xgboost), the xgboost model got a message that booster handle is invalid. Then the predicted probability that I used by this model is different with the correct model produced.
3. I don't know what happened.

## What have you tried?

1.  
2.
3.

**Comment by khotilov** [comment]
It is normal that a model saved as R object would have invalid handle after reading it back. R has a primitive mechanism to add hooks that may initialize unserialized objects, but it would be rather awkward for users to deal with that stuff (e.g., see the `refhook` parameter in `?readRDS`). Thus, we restore the handle only during the operations which require it. That should also have no effect on predictions. To look into the different predictions issue that you are seeing, please provide some reproducible example.

**Comment by franciszmy** [comment]
I've found that this problem is caused by different xgboost version. I train the model with R 3.2 and xgboost 4.x . I can correctly use my model in 4.x version xgboost, but if I use R 3.3 and library a 6.x version xgboost in the environment, this model will be invalid and it will cause the problem I've mentioned.

**Comment by franciszmy** [comment]
I tried to attach my model and test dataset into a zip file,but it doesn't work. How can I get the model to you.

**Comment by khotilov** [comment]
You've mentioned that you had used an older version for the initial model. See if #1938 would help.
