### ISSUE TITLE
Unbalanced multiclass data

### ISSUE THREAD

**Issue by paulbir** [dmlc/xgboost#1965]
I have 3 classes with this distribution:

Class 0: 0.1169
Class 1: 0.7668
Class 2: 0.1163

I know that there is a parameter called "scale_pos_wieght". But how is it handled for multiclass case? And how can I properly set it?

Thanks.

**Comment by khotilov** [comment]
In multiclass case, scale_pos_wieght would be handled one-vs-all, which is not good. You can assign different class weights to your data rows in DMatrix instead.

**Comment by pommedeterresautee** [comment]
I close the issue because it is an old one.
Don t hesitate to reopen it if required.
