### ISSUE TITLE
Redundancy of Learner class

### ISSUE THREAD

**Issue by AbdealiJK** [dmlc/xgboost#1971]
I was going through parts of the code and found that the structure being used is Learner -> LearnerImpl and the Learner class has a variable gbm_ which is used for majority if not all functionality.

It seems all in all that Learner is a redundant class and it would be easier to directly reference GradientBooster and create GradientBooster directly. Possibly a refactoring could easily move the functionality of Learner into GradientBooster itself and reduce complexity of code.

**Comment by tqchen** [comment]
The original indention of having a learner is to de-couple the objective function and evaluation from gradient boosting process.  This allows de-couples the logic of gradient booster from evaluation and objective, which is helpful in our case.

This being said, there is a possibility of merging, but we need to carefully consider the possible APIs

**Comment by AbdealiJK** [comment]
@tqchen that's a valid abstraction - I never noticed that.

May be there is an easier way to implement this by making the objective and evaluation parts private to Gradient booster rather than making a new learner class maybe?

I am hoping this would simplify the architecture a little. What's your opinion?
