### ISSUE TITLE
Error installing xgboost for python

### ISSUE THREAD

**Issue by abdelkarim336** [dmlc/xgboost#1972]
Hey, I'm having an error when trying to use the "make -j4". I've tired the following instructions:
--------------
$ cd dmlc-core
$ make -j4
$ cd ../rabit
$ make lib/librabit_empty.a -j4
$ cd ..
$ cp make/mingw64.mk config.mk
$ make -j4
----------------------
 but still doesn't work.

Here's the error log:

g++: error: libgomp.spec: No such file or directory
Makefile:136: recipe for target 'lib/libxgboost.dll' failed
mingw32-make: *** [lib/libxgboost.dll] Error 1
mingw32-make: *** Waiting for unfinished jobs....
g++: error: libgomp.spec: No such file or directory
Makefile:144: recipe for target 'xgboost' failed
mingw32-make: *** [xgboost] Error 1
r - build/learner.o
r - build/logging.o
r - build/common/hist_util.o
r - build/common/common.o
r - build/c_api/c_api_error.o
r - build/c_api/c_api.o
r - build/data/simple_dmatrix.o
r - build/data/sparse_page_raw_format.o
r - build/data/data.o
r - build/data/simple_csr_source.o
r - build/data/sparse_page_writer.o
r - build/data/sparse_page_source.o
r - build/data/sparse_page_dmatrix.o
r - build/gbm/gbm.o
r - build/gbm/gblinear.o
r - build/gbm/gbtree.o
r - build/metric/multiclass_metric.o
r - build/metric/elementwise_metric.o
r - build/metric/rank_metric.o
r - build/metric/metric.o
r - build/objective/regression_obj.o
r - build/objective/rank_obj.o
r - build/objective/objective.o
r - build/objective/multiclass_obj.o
r - build/tree/updater_fast_hist.o
r - build/tree/tree_model.o
r - build/tree/updater_colmaker.o
r - build/tree/updater_skmaker.o
r - build/tree/updater_sync.o
r - build/tree/updater_refresh.o
r - build/tree/updater_histmaker.o
r - build/tree/tree_updater.o
r - build/tree/updater_prune.o

Thank you in advance

**Comment by thirdwing** [comment]
> g++: error: libgomp.spec: No such file or directory

I suggest you check the openmp support by your compiler.

**Comment by phunterlau** [comment]
please follow the issue template and provide more details about the system and environment
