### ISSUE TITLE
xgb.plot.multi.trees and xgb.plot.tree do not produce tree structure on my computer

### ISSUE THREAD

**Issue by hxy0135** [dmlc/xgboost#1973]
Hi,
I followed the post at https://www.r-bloggers.com/introduction-to-xgboost-r-package/
I can not print the tree structure of the model on my computer like they are shown on the blog since I downloaded the newest version.

## Environment ## info
**Operating System**: Windows server 2008 R2 Enterprise

**`xgboost` version used**: 0.6-4

**The R sessionInfo():**
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server 2008 R2 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] xgboost_0.6-4

loaded via a namespace (and not attached):
 [1] igraph_1.0.1       Rcpp_0.12.8        rstudioapi_0.6     magrittr_1.5       munsell_0.4.3      colorspace_1.3-2  
 [7] lattice_0.20-34    R6_2.2.0           brew_1.0-6         stringr_1.1.0      plyr_1.8.4         dplyr_0.5.0       
[13] visNetwork_1.0.3   Rook_1.1-1         tools_3.3.2        grid_3.3.2         data.table_1.10.0  gtable_0.2.0      
[19] DBI_0.5-1          influenceR_0.1.0   DiagrammeR_0.9.0   htmltools_0.3.5    yaml_2.1.14        lazyeval_0.2.0    
[25] digest_0.6.11      assertthat_0.1     tibble_1.2         Matrix_1.2-7.1     gridExtra_2.2.1    RColorBrewer_1.1-2
[31] ggplot2_2.2.1      htmlwidgets_0.8    viridis_0.3.4      rgexf_0.15.3       stringi_1.1.2      scales_0.4.1      
[37] XML_3.98-1.5       jsonlite_1.2      
> 
**2. The command to install `xgboost` if you are not installing from source**
install.package('xgboost')
**Steps to reproduce**
require(xgboost)

data(agaricus.train, package='xgboost')
data(agaricus.test, package='xgboost')
train <- agaricus.train
test <- agaricus.test

bst <- xgboost(data = train$data, label = train$label, max.depth = 2, 
               eta = 1, nthread = 2, nround = 2, objective = "binary:logistic")

xgb.plot.tree(feature_names = agaricus.train$data@Dimnames[[2]], model = bst)

Thank you.

**Comment by yavladys** [comment]
Could you please be more specific? What kind of error do you see in console?

**Comment by hxy0135** [comment]
yavladys,
Thank you for your reply.
For the issue, it may be fixed. Since I got an email form Tong He, one of teh authors of the package, he asked me to get new source code from GITHub. I got the source code, now the problem is to compile it. I tried many time to compile, I got error "the compile failed' and I do not know the reason of failure.

**Comment by yavladys** [comment]
@hxy0135  ,
I don't suggest you build library from source code and compile it by your own. It can be time consuming and annoying since there are many additional configurations you should make to get it done, especially under Windows. 

I suppose Tong He's point was about keeping last version of xgboost package. Why you don't just remove current package and install newest one by follow installation guide [here](http://xgboost.readthedocs.io/en/latest/R-package/xgboostPresentation.html)
And don't forget to install DiagrammeR package as well.

Please let me know if it helps.

**Comment by hxy0135** [comment]
yavladys, 
Thank you for the info. 
I used the following commands and I successfully installed the package. But the package version is 0.6-0, it is even older than the version in CRAN, which is -0.6-4. 
install.packages("drat", repos="https://cran.rstudio.com")
drat:::addRepo("dmlc")
install.packages("xgboost", repos="http://dmlc.ml/drat/", type = "source")

And it does not work for me(I installed DiagrammeR.), this time error from xgb.plot.tree() is:
"Error: 'create_nodes' is not an exported object from 'namespace:DiagrammeR'"

Thank you,

**Comment by yavladys** [comment]
@hxy0135,
keep calm, now problem is localized :)

Object` create_nodes` is really not exported from [namespace:DiagrammeR](https://github.com/rich-iannone/DiagrammeR/blob/master/NAMESPACE) as it's not used anymore, but `create_node_df` is.

So you really need to switch to 0.6.4 package version where `create_nodes` was replaced by `create_node_df`.

It's strange that [dmlc/drat](https://github.com/dmlc/drat/tree/gh-pages/bin/windows/contrib/3.2) doesn't contain latest version of package release. But ok, just try to install 0.6.4 from CRAN or manually [download](https://cran.r-project.org/web/packages/xgboost/index.html) and [install](http://stackoverflow.com/questions/14806705/manually-downloading-and-installing-packages-in-r) it:

**Comment by hxy0135** [comment]
yavladys,
I installed 0.6-4 as soon as it was released last month. then I got the problem with printing tree - it is not a tree like. please see the attached document.

![tree](https://cloud.githubusercontent.com/assets/9253484/22554053/cf168b2c-e92c-11e6-84d8-a2966869303a.jpg)

**Comment by yavladys** [comment]
Why not? There is a root, each node has exactly two branches, each leaf is assigned to response value etc.

Well, I agree that it's not the best visualization, but it's pretty understandable. Am I wrong?

**Comment by hxy0135** [comment]
I need to print tree like what I saw at https://www.r-bloggers.com/an-introduction-to-xgboost-r-package/ 
to present the rules to some Business leaders.

Thanks

**Comment by jimmy15923** [comment]
Hi, I have same problem as yours, could anyone give suggestion? otherwise, we need to use python to plot

**Comment by khotilov** [comment]
This was fixed in #1939 . Please use the latest code from github.

**Comment by jimmy15923** [comment]
Thanks for your reply, I am using 
other attached packages:
[1] xgboost_0.6-4    DiagrammeR_0.9.0 MASS_7.3-35  

But still got the image like hxy0135 posted, which is not align, how can I solve this problem to produce the image like
https://www.r-bloggers.com/an-introduction-to-xgboost-r-package/
Thank you~
