### ISSUE TITLE
src/data/data.cc:246: External memory is not enabled in mingw

### ISSUE THREAD

**Issue by philipus** [dmlc/xgboost#1975]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System: windows

Compiler: visual c++ and oracle java 

Package used (python/R/jvm/C++): jvm

`xgboost` version used: 0.7

I am wondering why the program is complaining about mingw when I compiled xgboost via cmake -> sln -> visual studio ??!!!

do I need to compile dmlc-core also???? via visual c++

**Comment by pommedeterresautee** [comment]
Old question, no answer. Closing
