### ISSUE TITLE
XGBoost GPU Plug-in Single Column Block Error

### ISSUE THREAD

**Issue by ravikkaushik** [dmlc/xgboost#1977]
The error shows up when the higgs dataset has rows over X. 
Below is the error, Could you please let me know what could be the issue and how I can fix it?

/home/ec2-user/xgboost_gpu/plugin/updater_gpu/src/gpu_builder.cu:191: Check failed: fmat.SingleColBlock() GPUMaker: must have single column block
Error: [22:20:58] /home/ec2-user/xgboost_gpu/plugin/updater_gpu/src/gpu_builder.cu:191: Check failed: fmat.SingleColBlock() GPUMaker: must have single column block

## Environment info
Operating System: Linux ipXXXX  4.4.35-33.55.amzn1.x86_64
P2 Instance - 8 K80 Accelerators, E5-2686 V4 Xeon 2.3GHz processors (2 * 16 Physical Cores)

Compiler:
NVIDIA-Linux-x86_64-352.99
cuda_8.0.44_linux

Package used (python/R/jvm/C++): python
`xgboost` version used: 0.6 (latest)

1. The python version and distribution
python 2.7
2. The command to install `xgboost` if you are not installing from source
make dmlc=../dmlc_core
updater_gpu uses cmake 3.7.2

Leveraged higgs from the UCI repoistory for testing.
Column 1 is label
Column 2-28 is independent variables

## Steps to reproduce

1. Tried on 500K, 1000K, 2000K, 3000K, 4000K and it worked. Anything over 5000K does not work and throws this error

/home/ec2-user/xgboost_gpu/plugin/updater_gpu/src/gpu_builder.cu:191: Check failed: fmat.SingleColBlock() GPUMaker: must have single column block
Error: [22:20:58] /home/ec2-user/xgboost_gpu/plugin/updater_gpu/src/gpu_builder.cu:191: Check failed: fmat.SingleColBlock() GPUMaker: must have single column block

2. Setup the weight parameter based on the wpos/wneg ratio
---------------python code ----------------
from time import gmtime, strftime

print(strftime("%Y-%m-%d %H:%M:%S", gmtime()))

test_size = 1000000

# path to where the data lies
dpath = '/home/ec2-user/higgs'

# load in training data, directly use numpy
dtrain = np.loadtxt( dpath+'/higgs_sample_train.csv', delimiter=',', skiprows=1, converters={28: lambda x:int(x=='s'.encode('utf-8')) } )
print ('finish loading from csv ')

label  = dtrain[:,:1]
data   = dtrain[:,1:28]
# rescale weight to make it same as test set

weight = [float(test_size) / len(label)] * len(label)

sum_wpos = sum( weight[i] for i in range(len(label)) if label[i] == 1.0  )
sum_wneg = sum( weight[i] for i in range(len(label)) if label[i] == 0.0  )

print ("wpos: " + str(sum_wpos) + " wneg: " + str(sum_wneg))
# print weight statistics
print ('weight statistics: wpos=%g, wneg=%g, ratio=%g' % ( sum_wpos, sum_wneg, sum_wneg/sum_wpos ))

# construct xgboost.DMatrix from numpy array, treat -999.0 as missing value
xgmat = xgb.DMatrix( data, label=label, missing = -999.0, weight=weight )

# setup parameters for xgboost
param = {}
# use logistic regression loss, use raw prediction before logistic transformation
# since we only need the rank
param['objective'] = 'binary:logistic'
# scale weight of positive examples
param['scale_pos_weight'] = sum_wneg/sum_wpos
param['eta'] = 0.1
param['max_depth'] = 6
param['eval_metric'] = 'logloss'
param['silent'] = 1
param['nthread'] = 16
param['updater'] = 'grow_gpu'
# you can directly throw param in, though we want to watch multiple metrics here
plst = list(param.items())+[('eval_metric', 'ams@0.15')]

watchlist = [ (xgmat,'train') ]
# boost 120 trees
num_round = 120
print ('loading data end, start to boost trees')
print(strftime("%Y-%m-%d %H:%M:%S", gmtime()))
bst = xgb.train( plst, xgmat, num_round, watchlist );
print(strftime("%Y-%m-%d %H:%M:%S", gmtime()))
# save out model
bst.save_model('higgs.model')
print ('finish training')
strftime("%Y-%m-%d %H:%M:%S", gmtime())

**Comment by RAMitchell** [comment]
Try setting tree method to exact. Xgboost may be trying to automatically select the approximate method. Let me know if it works and what your performance results are. Also note that the algorithm will only use 1 gpu at this time.

**Comment by ravikkaushik** [comment]
Thanks, Roy. It worked to some extent. By choosing tree_method = 'exact' it was able to train 5MM records.
However, now it is stalling for full dataset (11MM records) with the error
CUDA error: /home/ec2-user/xgboost_gpu/plugin/updater_gpu/src/device_helpers.cuh(383): out of memory

One additional error I fixed was 
modprobe: FATAL: Module nvidia-uvm not found.
CUDA error: /home/ec2-user/xgboost_gpu/plugin/updater_gpu/src/device_helpers.cuh(412): unknown error

by executing the command, 
$ sudo modprobe nvidia-uvm

CPU - X5 Xeon 2686 v4 (2 CPUs)
GPU - GK 210 (K80 accelerator)
The performance of GPU is still not comparable for CPU. Maybe, the CPUs are powerful??

![image](https://cloud.githubusercontent.com/assets/20494928/22116009/1d734a58-de3d-11e6-958f-4f935372dbca.png)

**Comment by windreamer** [comment]
We have found the same issue when trying to run XGBoost with two nodes with one GPU per node.
And we did set `tree_method = exact`
So no distributed GPU support for now?

**Comment by RAMitchell** [comment]
Multi-node with GPUs is at least 6 months away.
