### ISSUE TITLE
Python crashed every time I try to use xgboost

### ISSUE THREAD

**Issue by BearStrikesBack** [dmlc/xgboost#1984]
I used to have working XGBoost in December, but recently it started to crash every time I try to call any function from XGBoost package. I reinstalled package using [this binaries](http://www.picnet.com.au/blogs/guido/post/2016/09/22/xgboost-windows-x64-binaries-for-download/). It has installed successfully, but anyway each time I try to run it it crashes my python. 

## Environment info
Operating System: Win10 64
![123](https://cloud.githubusercontent.com/assets/12938236/22193550/3b979936-e14d-11e6-82ce-2ce7dac78360.png)
Package used (python):
`xgboost` version used: 0.6

I got the following message when I try to run XGBoost under PyCharm IDE:

> `"D:\Program Files\Python\python.exe" "D:/PythonProjects/Coursera/Algorithmic_Toolbox/RecycleBin/XGBOOST TEST.py"
> [09:03:58] c:\dev\libs\xgboost\dmlc-core\include\dmlc\./logging.h:235: [09:03:58] C:\dev\libs\xgboost\dmlc-core\src\io\local_filesys.cc:109: LocalFileSystem.ListDirectory ../data error: No such process
> 
> Process finished with exit code -1073740791 (0xC0000409)`

Actually, I have no idea why is it looking for xgboost in c:\dev\libs\ since I don't have such location and local copy of repository is placed in another folder. Prior to this I had version from [here](http://www.lfd.uci.edu/~gohlke/pythonlibs/) and it was looking for xgboost package in another place. Maybe something wrong with Windows Registry?

I also noticed, that using` import xgboost` I get no DeprecationWarning. When XGBoost worked in Dec, I got such message regarding `model_selection` and `sklearn\cross_validation`.

**Comment by BearStrikesBack** [comment]
I reinstalled xgboost using whl from [here](http://www.lfd.uci.edu/~gohlke/pythonlibs/#xgboost). I got following error trying to launch some basics of xgboots:

`"D:\Program Files\Python\python.exe" "D:/PythonProjects/Coursera/Algorithmic_Toolbox/RecycleBin/XGBOOST TEST.py"
D:\Program Files\Python\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
[23:55:36] d:\build\xgboost\xgboost-git\dmlc-core\include\dmlc\./logging.h:235: [23:55:36] D:\Build\xgboost\xgboost-git\dmlc-core\src\io\local_filesys.cc:104: LocalFileSystem.ListDirectory ../data error: No such process

Process finished with exit code -1073740791 (0xC0000409)`

The error is the same, but differrent locations. What can it be?

**Comment by phunterlau** [comment]
Looks like it's visiting some local file system but `../data` directory doesn't exist. Can you verify if it is because of path? The `DeprecationWarning` is very fine from `scikit-learn`

**Comment by louis925** [comment]
Same issue. The module can't deal with relative path properly. If I replace the `../data` with absolute path, then it works fine. Nevertheless, whenever it encounter a wrong path, it crashes the python kernel complete.
