### ISSUE TITLE
stop xgboost based on eval_metric

### ISSUE THREAD

**Issue by swagatoa** [dmlc/xgboost#1985]
I am trying to run xgboost for a problem with very noisy features and interested in stopping the number of rounds based on a custom eval_metric that I have defined.

Based on domain knowledge I know that when the eval_metric (evaluated on the training data) goes above a certain value xgboost is overfitting. And I would like to just take the fitted model at that specific number of rounds and not proceed further.

What would be the best way to achieve this ?

**Comment by khotilov** [comment]
You may create a custom callback function for that. Use the existing early stopping one as a starting example.

**Comment by swagatoa** [comment]
Does the xgboost package have a feature to add custom callback functions ? Or would this involve changing the source files then rebuilding the package ?
