### ISSUE TITLE
dumping and reloading models scrambles the feature order.

### ISSUE THREAD

**Issue by softwaremechanic** [dmlc/xgboost#1987]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System: Ubuntu 16.04

Compiler:

Package used (python/R/jvm/C++): python

`xgboost` version used: 0.6

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`)
2. Logs will be helpful (If logs are large, please upload as attachment).

If you are using python package, please provide

1. The python version and distribution: anaconda python 3.5
2. The command to install `xgboost` if you are not installing from source: pip install xgboost

If you are using R package, please provide

1. The R `sessionInfo()`
2. The command to install `xgboost` if you are not installing from source

## Steps to reproduce

1. Train a few models by sub-sampling the same dataset multiple times. 
2. Dump the model to files.(using sklearn.externals joblib)
3. Reload the model, and try to predict with the same columns/features.

Error; 
    ValueError: feature_names mismatch: ['technical_25', 'fundamental_0', 'technical_17', 'technical_10', 'technical_24', 'technical_3', 'technical_5', 'technical_20', 'technical_27', 'technical_29', 'technical_12', 'technical_2', 'technical_43', 'technical_28'] ['technical_12', 'technical_27', 'technical_29', 'technical_17', 'technical_25', 'technical_2', 'technical_3', 'technical_28', 'fundamental_0', 'technical_43', 'technical_10', 'technical_24', 'technical_20', 'technical_5']

A closer look will tell you  it is only the order that is changed. 

## What have you tried?

1. Re-ordering the columns passed to the predict function. It works for some model, but doesn't for other models.

**Comment by tnlin** [comment]
similar issue here
