### ISSUE TITLE
could you post a new release to pypi?

### ISSUE THREAD

**Issue by suntzu86** [dmlc/xgboost#1991]
Hi, [me again](https://github.com/dmlc/xgboost/issues/1388)
Could we get a new release for pypi? Seems like there have been some additions since 0.6a2 :)

**Comment by phunterlau** [comment]
I will update it when get back from my trip. Hopefully in early Feb.

**Comment by suntzu86** [comment]
Sounds great @phunterlau, thanks! Enjoy your trip (vacation?) :)

**Comment by proinsias** [comment]
Can we get a new release?
