### ISSUE TITLE
Release 0.6 does not build

### ISSUE THREAD

**Issue by samfux84** [dmlc/xgboost#1997]
## Environment info
Operating System:
CentOS 6.8

Compiler:
GCC 4.8.2

`xgboost` version used:
Release 0.6

[sfux@develop01 xgboost-0.60]$ make -j 4
Makefile:29: dmlc-core/make/dmlc.mk: No such file or directory
make: *** No rule to make target `dmlc-core/make/dmlc.mk'.  Stop.

I thought that release ares supposed to work without having to run additional git commands (otherwise I could clone the repo).

[sfux@develop01 xgboost-0.60]$ git submodule init
fatal: Not a git repository (or any of the parent directories): .git

**Comment by thirdwing** [comment]
You need to `git clone --recursive https://github.com/dmlc/xgboost`
