### ISSUE TITLE
XGBRegressor ignoring missing parameter

### ISSUE THREAD

**Issue by amambrini** [dmlc/xgboost#1999]
## Environment info
* Operating System: Ubuntu 16.04
* Package used (python/R/jvm/C++): Python 2.7.12
* `xgboost` version used: 0.6
* The python version and distribution: Python 2.7.12
* The command to install `xgboost` if you are not installing from source: `pip install xgboost`

## Steps to reproduce

Setting the missing parameter as -1, the regressor still accept to train on np.nan input
```
In [76]: X = [[i,np.nan] for i in range(0,100) for j in range(0,100)]
In [77]: y = [i*j for i in range(0,100) for j in range(0,100)]
In [78]: clf = XGBRegressor(missing=-1)
In [79]: clf.fit(X,y)
Out[79]: 
XGBRegressor(base_score=0.5, colsample_bylevel=1, colsample_bytree=1, gamma=0,
       learning_rate=0.1, max_delta_step=0, max_depth=3,
       min_child_weight=1, missing=-1, n_estimators=100, nthread=-1,
       objective='reg:linear', reg_alpha=0, reg_lambda=1,
       scale_pos_weight=1, seed=0, silent=True, subsample=1)
```

Moreover the models trained on missing value encoded as np.nan and missing values encoded as -1 are clearly different (while they should be the same given the same seed)
```
In [100]: clf_A = XGBRegressor(missing=-1, seed=42)
In [101]: clf_B = XGBRegressor(missing=np.nan, seed=42)
In [102]: X = [[i, np.nan] for i in range(0,100) for j in range(0,100)]
In [103]: clf_A.fit(X,y)
Out[103]: 
XGBRegressor(base_score=0.5, colsample_bylevel=1, colsample_bytree=1, gamma=0,
       learning_rate=0.1, max_delta_step=0, max_depth=3,
       min_child_weight=1, missing=-1, n_estimators=100, nthread=-1,
       objective='reg:linear', reg_alpha=0, reg_lambda=1,
       scale_pos_weight=1, seed=42, silent=True, subsample=1)
In [104]: X = [[i, np.nan] for i in range(0,100) for j in range(0,100)]
In [105]: clf_B.fit(X,y)
Out[105]: 
XGBRegressor(base_score=0.5, colsample_bylevel=1, colsample_bytree=1, gamma=0,
       learning_rate=0.1, max_delta_step=0, max_depth=3,
       min_child_weight=1, missing=None, n_estimators=100, nthread=-1,
       objective='reg:linear', reg_alpha=0, reg_lambda=1,
       scale_pos_weight=1, seed=42, silent=True, subsample=1)

In [107]: clf_A.predict([13,14])
Out[107]: array([ 643.41644287], dtype=float32)

In [108]: clf_B.predict([13,14])
Out[108]: array([ 2450.18505859], dtype=float32)
```

**Comment by Gunthard** [comment]
Your example returns the same prediction for me:

``` python
import numpy as np
from xgboost import XGBRegressor

X = [[i,np.nan] for i in range(0,100) for j in range(0,100)]
y = [i*j for i in range(0,100) for j in range(0,100)]

clf_A = XGBRegressor(missing=-1, seed=42).fit(X,y)
clf_B = XGBRegressor(missing=np.nan, seed=42).fit(X,y)

print clf_A.predict([13,14]), clf_B.predict([13,14])
>> [ 2450.18505859] [ 2450.18505859]
```

The missing parameter is not ignored. The data matrix is converted to a DMatrix object. DMatrix accepts dense and sparse data. Your python list data is interpreted as sparse data  where all -1 values are set to missing values as well.

Trying to create a DMatrix from a dense matrix with nan values and additional missing value != nan will cause an error:
``` python
from xgboost.core import DMatrix
DMatrix(np.array([[np.nan,np.nan], [-1, -1]]), missing=-1)
>> XGBoostError: [13:32:45] src/c_api/c_api.cc:315: Check failed: nan_missing There are NAN in the matrix, however, you did not set missing=NAN
```

**Comment by amambrini** [comment]
I am no sure I understand your point. Maybe I am misinterpreting what the missing parameters is. Let's see this example
```
X = [[i,j] for i in range(0,100) for j in range(0,100)]
y = [i*j for i in range(0,100) for j in range(0,100)]
clf = XGBRegressor(missing=-1)
clf.fit(X,y)

clf.predict([5, 3])
>> array([-112.00349426], dtype=float32)

clf.predict([5, np.nan])
>> array([ 524.71563721], dtype=float32)

clf.predict([5, -1])
>> array([-80.81938171], dtype=float32)
```

In my opinion if I set missing as -1 and then I pass a np.nan in predict, it should return an error. Also, even assuming both np.nan and -1 are considered missing values then why predicting over [5, -1] and [5, np.nan] returns different results?

**Comment by Nozdi** [comment]
On the other hand, everything works as it should if we use np.array not python objects:
```
X = [[i,j] for i in range(0,100) for j in range(0,100)]
y = [i*j for i in range(0,100) for j in range(0,100)]
clf = XGBRegressor(missing=-1)
clf.fit(X,y)

In [31]: clf.predict(np.array([[5, 3]]))
Out[31]: array([-112.00350189], dtype=float32)

In [32]: clf.predict(np.array([[5, np.nan]]))
...
XGBoostError

In [33]: clf.predict(np.array([[5, -1]]))
Out[33]: array([-82.91928101], dtype=float32)
```

**Comment by amambrini** [comment]
That's indeed a problem in DMatrix in dealing with python lists:
```
DMatrix(np.array([[np.nan,np.nan], [-1, -1]]), missing=-1)
>>> XGBoostError                              

DMatrix([[np.nan,np.nan], [-1, -1]], missing=-1)
>>> <xgboost.core.DMatrix at 0x7f07aa0e3ed0>
```
which is actually documented here [python list is not mentioned] https://github.com/dmlc/xgboost/blob/036ee55fe0f6b9038ab6b5667b2a16fd2a2958e9/python-package/xgboost/core.py#L231

Still, to be compatible with sklearn I think python list should be allowed. Therefore maybe casting data into a numpy array in case it is a python list here would solve it --> https://github.com/dmlc/xgboost/blob/036ee55fe0f6b9038ab6b5667b2a16fd2a2958e9/python-package/xgboost/sklearn.py#L481

It is not clear to me whether the same should be done in the fit method, probably yes.

**Comment by admu** [comment]
Caused by: java.lang.Exception: [15:45:15] /xgboost/src/c_api/c_api.cc:383: Check failed: nan_missing There are NAN in the matrix, however, you did not set missing=NAN
