### ISSUE TITLE
Did xgb.save and xgb.load change?

### ISSUE THREAD

**Issue by robertzk** [dmlc/xgboost#200]
We have been using a [fork of the xgboost package](https://github.com/feiyeye/xgboost) that we recently caught up to the latest master. However, older models whose binary was saved using xgb.save is no longer being correctly deserialized using xgb.load; instead, we see:

```
Error in xgb.Booster(modelfile = modelfile) : 
  BoostLearner: wrong model format
```

Is there any hope to salvage these binaries, or should we xgb.load from an older version of the package to load them? Did the serialization format change in a systematic way?

**Comment by tqchen** [comment]
I do not think this was due to format change, but this could due to the new support for using R's save function. @hetong007 should be able to look into this and what was going on

**Comment by hetong007** [comment]
Hi, @robertzk can you please provide more information? For example what is the process and where did this error appear. It would be great if you can provide a minimum reproducible example.

**Comment by tqchen** [comment]
Any updates on the issue? If we can have a reproducible example and hashtag of a version where if we save the model, the change breaks. @hetong007 or I can take a look at it. There is no intention break of backward compatibility since 3.0

**Comment by tqchen** [comment]
This appears to be my fault of tiny change of model structure that cause backward incompatibility. I have pushed a hack to fix the problem, so the old model can still be loaded
