### ISSUE TITLE
[jvm-packages] How to use a custom objective function

### ISSUE THREAD

**Issue by GeorgieJi** [dmlc/xgboost#2002]
Hi, I have a issue on the xgboost4j-spark about the function of customized objective function.
When I tried to add a customized objective function, like this
`        var xgBoostModelWithDF = XGBoost.trainWithDataFrame(trainingDF(0), paramMap,
          round = paramsArray(0).toInt, nWorkers = IntWorkerCount, useExternalMemory = true,obj = new ObjMobileRecommend.Object_,eval = new ObjMobileRecommend.EvalError)`

I got a error message:
`Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: parameter "obj_type" is not defined, you have to specify the objective type as classification or regression with a customized objective function`

Then I found out that probably I must add the parameter "obj_type" in the "paramMap". But I didn't know exactly what I need to assign. When I set it as "reg:linear", I can't get any linear output, but only real number, like "0.5".

How to solve it ? Thanks for any suggestions.

**Comment by yakimyakim** [comment]
Hey,
Did you manage? how?
Bgds

**Comment by superbobry** [comment]
@yakimyakim are you having exactly the same problem? Can you provide some details, please?

**Comment by yakimyakim** [comment]
In general we don't manage to use the custom objective in xgboost spark as we do in Python.
Tried several things and failed in all. Did you manage at the end? Did anybody?
