### ISSUE TITLE
how to set_group in ranking model?(In Python)

### ISSUE THREAD

**Issue by xd-kevin** [dmlc/xgboost#2005]
I have tried to set group in DMatrix with numpy.array and List, but both get the error:
 d:\build\xgboost\xgboost-git\dmlc-core\include\dmlc\./logging.h:235: [10:52:54] D:\Build\xgboost\xgboost-git\src\c_api\c_api.cc:342: Check failed: (src.info.group_ptr.size()) == (0) slice does not support group structure

So, how to fix this problem? Thank very much~

**Comment by xd-kevin** [comment]
may the cv function cannot get the group size?

**Comment by TheEdoardo93** [comment]
I've got the same problem now!
How do you solve that? @xd-kevin 

Thanks

**Comment by solensolen** [comment]
The same thing happened to me. It may have same reasons from DMatrix itself.

I solve the problem this way: 
when define the xgb.DMatrix,
Try not pass a DataFrame to xgb.DMatrix 's para "data" directly, use its value array instead.
