### ISSUE TITLE
base_margin not copied by XGDMatrixSliceDMatrix. Leads to loss of base_margin when performing cross-validation with xgb.cv() 

### ISSUE THREAD

**Issue by osofr** [dmlc/xgboost#2006]
On latest version of the R package. 

`base_margin` is not passed down to test / train data during cross-validation. 

On the other hand other setinfo attributes such as `weights` and `labels` are passed down and handled properly (split into test / train sets).

Most likely the problem occurs when calling `slice` in `xgb.cv`, which can be traced down to these lines, where we can see that `weights` and `labels` are copied, but not `base_margin`. Presumabely this is a very quick fix, would it be possible to add a line to copy base_margin?

https://github.com/dmlc/xgboost/blob/7078c41dad5c92da6a81afaecd49768c80c9242a/src/c_api/c_api.cc#L397-L405

**Comment by tqchen** [comment]
hmm, can you open a PR to fix this? Thanks!

**Comment by osofr** [comment]
I can try, but I hardly know any C++ :)

**Comment by owlas** [comment]
I just ran into this in the current version on pypi.

- Is this fix in the most recent release?
- Why was the issue reopened?

**Comment by khotilov** [comment]
It was fixed in the development but so far it got into neither pypi nor CRAN release.

**Comment by owlas** [comment]
@khotilov thanks. Is there a schedule for next pypi release?
