### ISSUE TITLE
[xgboost4j-spark]  transformLeaf get different results compared with predictLeaf

### ISSUE THREAD

**Issue by Brill-Wang** [dmlc/xgboost#2009]
Hi, When I call transform function(spark), I get probabilities column, but it is different output when I train the model locally.
What's the difference between the local output(1 float number) and probabilities(2 numbers for binary classification)? 

To avoid this question I test transformLeaf and predictLeaf functions, suppose that I can get same answer, but still not..

        val xgboostModel = XGBoost.loadModelFromHadoopFile("file:///home/Brill/QuixeyData/ADS/TrainingData/HDPModel")(sc)
        val svmData = spark.read.format("libsvm").load("/home/Brill/QuixeyData/ADS/TrainingData/test.svm")
        val preds = xgboostModel.booster.predictLeaf(new DMatrix("/home/Brill/QuixeyData/ADS/TrainingData/test.svm"))
        preds.foreach(v=> {
            v.foreach(c => print(c + " "))
            println('\n')
        })
        println(xgboostModel.transformLeaf(svmData).first())

I think they should get same result, but not.
When I debug into code, they all go into Booster.java predict(DMatrix data, outputMargin, treeLimit, predLeaf)  function, with same parameter, but get diff predicts.
I want to check the data in DMatrix, but I didn't see there is a way to get data in the DMatrix.

Is there any mistake I make?
Is there any way to see the data in DMatrix when debug?

**Comment by Brill-Wang** [comment]
Here's my test.svm
data
predLeaf result
transformLeaf result
first data is the test data
others are data generated from first data( take only parts of features)



0 1:3.0 3:-0.1155 6:0.1785 7:0.5 10:0.6666 18:0.0583 20:0.0614 25:0.25 28:0.0575 30:11.2899 38:0.2 41:19.0 49:1.0 50:1.0 51:0.5
48.0,42.0,44.0,48.0,42.0,49.0,42.0,42.0,41.0,41.0,44.0,44.0,43.0,43.0,38.0,46.0,47.0,41.0,43.0,42.0
52.0,45.0,42.0,52.0,44.0,50.0,45.0,43.0,46.0,45.0,61.0,62.0,56.0,54.0,52.0,68.0,63.0,50.0,54.0,52.0


0 38:0.2 41:19.0 49:1.0 50:1.0 51:0.5
47.0,41.0,41.0,47.0,41.0,49.0,42.0,41.0,41.0,41.0,41.0,41.0,41.0,43.0,38.0,45.0,47.0,41.0,43.0,42.0
47.0,41.0,41.0,47.0,41.0,50.0,42.0,41.0,42.0,44.0,42.0,42.0,41.0,45.0,42.0,45.0,63.0,43.0,54.0,42.0


0 1:3.0 3:-0.1155 6:0.1785 7:0.5 10:0.6666 18:0.0583 20:0.0614 25:0.25 28:0.0575 30:11.2899
49.0,43.0,45.0,49.0,45.0,51.0,43.0,45.0,43.0,41.0,46.0,46.0,47.0,43.0,38.0,51.0,48.0,41.0,43.0,44.0
53.0,47.0,47.0,53.0,47.0,53.0,47.0,48.0,48.0,47.0,57.0,58.0,54.0,55.0,52.0,61.0,51.0,47.0,47.0,50.0


0 1:3.0
49.0,43.0,45.0,49.0,45.0,51.0,43.0,45.0,43.0,41.0,46.0,46.0,47.0,43.0,38.0,51.0,48.0,41.0,43.0,44.0
49.0,43.0,45.0,49.0,45.0,51.0,43.0,45.0,43.0,41.0,45.0,45.0,47.0,43.0,38.0,50.0,48.0,41.0,43.0,44.0


0 3:-0.1155
49.0,43.0,45.0,49.0,45.0,51.0,43.0,45.0,43.0,41.0,46.0,46.0,47.0,43.0,38.0,51.0,48.0,41.0,43.0,44.0
49.0,43.0,45.0,49.0,45.0,51.0,43.0,45.0,43.0,41.0,46.0,46.0,47.0,43.0,38.0,51.0,48.0,41.0,43.0,44.0


0 7:0.5
49.0,43.0,45.0,49.0,45.0,51.0,43.0,45.0,43.0,41.0,46.0,46.0,47.0,43.0,38.0,51.0,48.0,41.0,43.0,44.0
49.0,43.0,45.0,49.0,45.0,51.0,43.0,45.0,43.0,41.0,46.0,46.0,47.0,43.0,38.0,51.0,48.0,41.0,43.0,44.0


0 18:0.0583 20:0.0614 25:0.25
49.0,43.0,45.0,49.0,45.0,51.0,43.0,45.0,43.0,41.0,46.0,46.0,47.0,43.0,38.0,51.0,48.0,41.0,43.0,44.0
53.0,48.0,45.0,53.0,45.0,53.0,43.0,48.0,47.0,41.0,46.0,46.0,50.0,43.0,38.0,51.0,48.0,47.0,43.0,50.0

**Comment by Brill-Wang** [comment]
I modify the data, change svmData(which load libsvm as dataframe the file to index + 1), get same result.
spark.read.format("libsvm").load("test1.svm")    ---     0 52:0.5  --  for transformLeaf
new DMatrix("test.svm")    ---    0  51:0.5   --  for  predictLeaf
DMatrix and spark-libsvm load data with different definition........

**Comment by CodingCat** [comment]
it is a known problem https://github.com/dmlc/xgboost/tree/master/jvm-packages (search `NOTE on LIBSVM Format:`)
