### ISSUE TITLE
xgboost 0.6 dosn't work on spyder

### ISSUE THREAD

**Issue by yoavtalmi** [dmlc/xgboost#2013]
I have been running xgboost in spyder for over a year, and recently updated xgboost from 0.4 to 0.6. since then when I ran xgboost in spyder I get the following error:
 "WindowsError: exception: access violation reading [#######]". 
However when I ran the same code in cmd, there is no problam.
this happened to me either with spyder 2 or spyder 3

* Spyder Version: 2 and 3
* Python Version: 2.7
* Operating system: windows 10

`xgboost` version used: 0.6

## What have you tried?

1. Building xgboost my self
2. Using Binaris builds
3. Use either spyder 2 or 3

**Comment by dyln** [comment]
same here. i have python 3.5

**Comment by tpjoe** [comment]
yup me too...
