### ISSUE TITLE
xgb.importance throws error with co-occurrence computation

### ISSUE THREAD

**Issue by dkincaid** [dmlc/xgboost#2015]
I'm getting an error when trying to use `xgb.importance` with the co-occurrence computation. Here is the error:

```
Error in `[.xgb.DMatrix`(data, , result[MissingNo == T, Feature], drop = FALSE) : 
  unused argument (drop = FALSE)
```

Here is the code I'm using to run it. The first `xgb.importance` line works fine. The second throws that error

```R
xgb_fit <- xgboost(data=train_matrix, params = xgb_params, nrounds = 100)

xgb.importance(model=xgb_fit, feature_names = colnames(train_matrix))

xgb.importance(model=xgb_fit, feature_names = colnames(train_matrix), data = train_matrix, label = train$class)
```

any ideas what I might be doing wrong or is there a bug?

**Comment by khotilov** [comment]
Co-occurrence computation was broken for quite awhile #1092, and I've turned it off in #1964
