### ISSUE TITLE
Documentation typo?

### ISSUE THREAD

**Issue by ANtlord** [dmlc/xgboost#2016]
I'm new of users of xgboost. I read the [documentation for python](https://github.com/dmlc/xgboost/blob/master/doc/python/python_intro.md#prediction) and I've noted in example undefined variable `xgmat` in `ypred = bst.predict(xgmat)`. Is there typo? Should `xgmat` be replaced by `dtest`?

**Comment by terrytangyuan** [comment]
yeah feel free to submit a PR
