### ISSUE TITLE
Xgboost random forest mode produces different posterior distribution compared to randomForest package

### ISSUE THREAD

**Issue by traversc** [dmlc/xgboost#2018]
Here's my code: 

```
library(randomForest)
library(xgboost)

load("mydata.Rdata")
xgboost(data = mat_train[,-1], label=mat_train[,1], max_depth = 5, num_parallel_tree = 100, subsample = 0.5, colsample_bytree =0.5, nrounds = 1, objective = "binary:logistic", nthread=10) -> xgfit
predict(xgfit, mat_test[,-1]) -> pr
hist(pr)
summary(pr)
```

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
 0.3671  0.3983  0.5071  0.5009  0.5961  0.6314

```

randomForest(mat_train[,-1], factor(mat_train[,1]), ntree=100) -> rf_fit
predict(rf_fit,newdata=mat_test[,-1], type="prob")[,2] -> pr
hist(pr)
summary(pr)

```
Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
 0.0000  0.0000  0.4500  0.5011  1.0000  1.0000

Basically, the RandomForest package produces a range from 0 to 1, whereas the xgboost package produces a range from ~0.36 to ~0.63.  Why is that?

**Comment by khotilov** [comment]
xgboost allows a configuration that works in a random forest-like manner, but it is not strictly a classic random forest. E.g., one difference is that it uses regression trees even for the classification task, so, for a single boosting round, it would likely result in an under-calibrated classifier. You would need to either implement your own calibration procedure or to run several boosting iterations when more probability-like predictions are needed. And I've noticed that you were using the default eta value; setting eta=1 should improve the situation as well.

**Comment by traversc** [comment]
Thanks for your response!  Is there any plan to implement the classic random forest?  Xgboost seems to be  faster than the other random forest packages available.

**Comment by khotilov** [comment]
I don't think there was any plan. 
Depending on your needs, you might take a look at ranger, Rborist and randomForestSRC.
