### ISSUE TITLE
GPU cuda out of memory with a sparse matrix from a svm

### ISSUE THREAD

**Issue by YaYaB** [dmlc/xgboost#2019]
I try to use xgboost with gpu on a dataset of several millions of rows and 30000 columns (features), it fails as it says it requires much more memory.

## Environment info
Operating System: Ubuntu 16.04

Compiler: cmake 3.7.2

Package used (python/R/jvm/C++): C++

`xgboost` version used: the latest obtained from the master branch using git clone
commit hash: 4fb7fdb240b389775534d2d7a1b7092fe6366e79

I have a sparse matrix containing 30000 columns in a svm file. When using the CPU version of xgboost I have no issue. However when using the GPU version I have the following error:
`CUDA error: build/xgboost/src/xgboost/plugin/updater_gpu/src/device_helpers.cuh(386): out of memory`

## What I have tried:

1. Do not use the full rows of my dataset, I obtained the same results ( `cuda out of memory`)
2. Reduce the number of features, it works in that case.
3. From this on I dug deeper and I plotted some information that you have below. Those are the computation of the allocation needed to launch xgboost gpu:
```
[12:16:29] 1x31390 matrix with 121 entries loaded from train.svm
[12:16:29] 100x31501 matrix with 21641 entries loaded from test.svm
[12:16:29] /src/xgbinputconns.cc:221: Successfully acquired data
[12:16:29] /src/xgblib.cc:284: initializing model
[12:16:29] /src/xgblib.cc:296: boosting round 0
firstsize_2 121
sizeof(T)_2 4
firstsize_2 121
sizeof(T)_2 4
firstsize_2 121
sizeof(T)_2 4
firstsize_2 31391
sizeof(T)_2 4
firstsize_2 121
sizeof(T)_2 4
firstsize_2 121
sizeof(T)_2 4
firstsize_2 121
sizeof(T)_2 4
firstsize_2 121
sizeof(T)_2 4
firstsize_2 121
sizeof(T)_2 2
firstsize_2 121
sizeof(T)_2 2
firstsize_2 1
sizeof(T)_2 2
firstsize_2 1
sizeof(T)_2 8
firstsize_2 65535
sizeof(T)_2 48
firstsize_2 1028587520
sizeof(T)_2 32
firstsize_2 1028587520
sizeof(T)_2 8
firstsize_2 1028587520
sizeof(T)_2 4
firstsize_2 121
sizeof(T)_2 4
firstsize_2 121
sizeof(T)_2 4
firstsize_2 255
sizeof(T)_2 1
firstsize_2 31390
sizeof(T)_2 4
firstsize_1 31390
sizeof(T)_1 4
45261379584
```
To obtain those, I did the following modification to the `build/xgboost/src/xgboost/plugin/updater_gpu/src/device_helpers.cuh` file between line 342 and line 390.
```
  template <typename T, typename SizeT>
  size_t get_size_bytes(dvec<T> *first_vec, SizeT first_size) {
    std::cout << "firstsize_1 " << first_size  << std::endl;
    std::cout << "sizeof(T)_1 " <<  sizeof(T) << std::endl;
    return align_round_up(first_size * sizeof(T));
  }

  template <typename T, typename SizeT, typename... Args>
  size_t get_size_bytes(dvec<T> *first_vec, SizeT first_size, Args... args) {
    std::cout << "firstsize_2 " << first_size  << std::endl;
    std::cout << "sizeof(T)_2 " << sizeof(T)  << std::endl;
    return align_round_up(first_size * sizeof(T)) + get_size_bytes(args...);
  }
```
And,
```
  template <typename... Args> void allocate(Args... args) {
    if (d_ptr != NULL) {
      throw std::runtime_error("Bulk allocator already allocated");
    }
    _size = get_size_bytes(args...);
    std::cout << " " << _size << std::endl;
    safe_cuda(cudaMalloc(&d_ptr, _size));

    allocate_dvec(d_ptr, args...);
  }
};
```

It tries to allocate  45GB of GPU memory but I do not have this much memory. Now I am stuck here, I do not know why the number 65535 (2^16 -1) suddenly appears. From this number it gives that `1028587520` is needed in memory.

**Comment by rain1024** [comment]
Sound like me. I work well with CPU version. But when I use xgboost with GPU, it has the error

```
CUDA error: d:\pycharmprojects\xgboost\plugin\updater_gpu\src\device_helpers.cuh(383): out of memory
```

**Comment by rcherukuri12** [comment]
if you get something like...you just batch and do incremental model building ..then it works fine

**Comment by yitang** [comment]
i'm having the same problem.

**Comment by RAMitchell** [comment]
The gpu_hist algorithm must statically allocate memory for histograms for every single column. For this reason you cannot use arbitrarily large numbers of columns. One thing you can do is reduce the max_bin parameter below its default of 256.

**Comment by yitang** [comment]
The data size is 7 million rows and 100 columns, and I have gtx 1080 ti 11GB ram. 

I will try to change max_bin and see if I have any luck.
