### ISSUE TITLE
regression prediction in python text get_dump() is off by 0.5

### ISSUE THREAD

**Issue by VXavierZ** [dmlc/xgboost#2025]
For regression (y is centered Gaussian like, from -4.0 to +4.0), when I try to parse the string trees, it seems the values in string trees are 0.5 less than the prediction returned from model.predict(). 

Is this true ? If so, is there a reason for this ? Seems a bug from binary classification.

parameters are as the following:

param = {}
param['nthread'] = 10
param['max_depth'] = 6
param['eta'] = 0.01
param['objective'] = 'reg:linear'
param['tree_method'] = 'exact'

**Comment by khotilov** [comment]
It's b/c default `base_score` value is 0.5. 
Setting it to average value of your y is usually a good idea.

**Comment by VXavierZ** [comment]
@khotilov thanks very much, I am still exploring xgboost.

**Comment by AbdealiJK** [comment]
This should probably be closed ?

**Comment by VXavierZ** [comment]
yes, doing it now. thanks.
