### ISSUE TITLE
Using "softprob" but the prediction doesn't give the probablities for all the classes

### ISSUE THREAD

**Issue by manishranjan0805** [dmlc/xgboost#2027]
I am using xgboost package in R and I am using "multi:softprob" as objective and "mlogloss" as metric to train the model but there are 2 issues with it:

1) The model is getting trained to reduce the merror not mlogloss

x <- xgb.train(objective="multi:softprob" , + eta=0.3, + metric="mlogloss", + max_depth = 7, + early_stopping_rounds = 3, + watchlist = list(train=xtraindata, test=xvaldata), + data = xtraindata , + label=tlabs , + nrounds = 100 , + subsample=0.95, + min_child_weight=0.65, + colsample_bytree = 0.95 , + colsample_bylevel=0.6, + gamma = 0.3 , + num_class=3)
Output: [1] train-merror:0.284415 test-merror:0.303313 Multiple eval metrics are present. Will use test_merror for early stopping. Will train until test_merror hasn't improved in 3 rounds.

Stopping. Best iteration: [27] train-merror:0.240571 test-merror:0.283862

**Shouldn't the above code reduce on mlogloss**

2) The predictions should be probabilities for all 3 classes but that isn't the case

pre <- predict(x,as.matrix(s2) ) head(pre) [1] 0.7143399 0.2327325 0.0529276 0.2522694 0.3322803 0.4154503
**The predictions are as above. Nothing is making sense to me now. Please Help ME!**

**Comment by khotilov** [comment]
The parameter is `eval_metric`.

And you are getting probabilities. If you want them as a matrix with three columns straight out of `predict`, use the `reshape=TRUE` argument.

**Comment by manishranjan0805** [comment]
@khotilov Thank you very much !
