### ISSUE TITLE
Bug with boost gblinear (ntree_limit) == (0)

### ISSUE THREAD

**Issue by rwarnung** [dmlc/xgboost#2029]
The problem that I report could be connected to [#1465](https://github.com/dmlc/xgboost/issues/1465)
I tried to use the weekly updated version but it is still there.

The issue is the following:
```
require(xgboost)
data = as.matrix(iris[,1:4])
target = ifelse(iris[,5]=="setosa",1,0)
model = xgboost(data,target, booster="gblinear", nrounds=82, max_depth=1, eta=0.05, lambda=154, lambda_bias=57.8, alpha=13.1, 
                colsample_bytree=0.5, subsample=0.8, min_child_weight=5, early_stopping_rounds=4, verbose=1,
                eval_metric="logloss",objective="binary:logistic")

p = predict(model, newdata = data)
```
gives the error

> Error in predict.xgb.Booster(model, newdata = data) : 
>   [13:13:06] amalgamation/../src/gbm/gblinear.cc:177: Check failed: (ntree_limit) == (0) GBLinear::Predict ntrees is only valid for gbtree predictor

Is this already known?

## Environment info
Operating System: Windows

Compiler: Rtools mingw_64

Package used (python/R/jvm/C++): R

`xgboost` version used: xgboost_0.6-0 installed via  install.packages("xgboost", repos = "http://dmlc.ml/drat/", type = "source")

1. The R `sessionInfo()`

```
R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] xgboost_0.6-0

loaded via a namespace (and not attached):
[1] magrittr_1.5      Matrix_1.2-6      tools_3.3.1       stringi_1.1.1     grid_3.3.1        data.table_1.10.4 lattice_0.20-33  
```

**Comment by khotilov** [comment]
This was fixed in #1929. However, it was merged on Jan6, a day after the most recent CRAN release. And the code in drat https://github.com/dmlc/drat/tree/gh-pages/src/contrib is very outdated (Aug19).

**Comment by rwarnung** [comment]
@khotilov thank you for your quick response. What a pity that the bug was only fixed one day too late ;) Strangely I can install the drat version but not the devel. 
I use it along the lines [here](http://xgboost.readthedocs.io/en/latest/build.html#r-package-installation):

setwd('wherever/you/cloned/it/xgboost/R-package/')
install.packages('.', repos = NULL, type="source")

it fails with

* installing *source* package 'xgboost' ...

   **********************************************
   WARNING: this package has a configure script
         It probably needs manual configuration
   **********************************************


** libs

> *** arch - i386
> cp -r ../../src .
> cp -r ../../rabit .
> cp -r ../../dmlc-core .
> cp -r ../../include .
> cp -r ../../amalgamation .
> C:/Rtools/mingw_32/bin/g++  -std=c++0x -I"C:/PROGRA~1/R/R-33~1.1/include" -DNDEBUG -I.//include -I.//dmlc-core/include -I.//rabit/include -I./ -DXGBOOST_STRICT_R_MODE=1 -DDMLC_LOG_BEFORE_THROW=0 -DDMLC_ENABLE_STD_THREAD=0 -DDMLC_DISABLE_STDIN=1 -DDMLC_LOG_CUSTOMIZE=1 -DXGBOOST_CUSTOMIZE_LOGGER=1 -DRABIT_CUSTOMIZE_MSG_ -DRABIT_STRICT_CXX98_    -I"d:/Compiler/gcc-4.9.3/local330/include" -DARMA_64BIT_WORD -fopenmp -pthread   -O2 -Wall  -mtune=core2 -c xgboost_R.cc -o xgboost_R.o
> xgboost_R.cc:2:26: fatal error: dmlc/logging.h: No such file or directory
>  #include <dmlc/logging.h>

Note that I don't have git installe here (I would have to ask my IT and it would take 2 weeks so forth ...).
Do you have any idea why this did not work? Do you plan to update the drat version or CRAN soon? Thank you!

**Comment by khotilov** [comment]
xgboost depends on code from the two low-level projects dmlc-core and rabit, which would be cloned when using the recursive option in git clone. However, to get them without git, simply follow the `dmlc-core @ ...` and `rabit @ ...` links from https://github.com/dmlc/xgboost , download each as zip, and unpack into the corresponding directories.

**Comment by rwarnung** [comment]
@khotilov thanks - it perfectly worked as you described!
