### ISSUE TITLE
XGBoost cannot read large number of files from AWS S3:  Error - failed: data.str() == "false" the returning list is truncated

### ISSUE THREAD

**Issue by ravikkaushik** [dmlc/xgboost#2030]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System: Linux ip-172-24-234-227 4.4.35-33.55.amzn1.x86_64

Compiler:
gcc version 4.8.3 20140911
Package used (python/R/jvm/C++):
C++

`xgboost` version used:
0.6

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`)
2. Logs will be helpful (If logs are large, please upload as attachment).

If you are using python package, please provide

1. The python version and distribution
2. The command to install `xgboost` if you are not installing from source

If you are using R package, please provide

1. The R `sessionInfo()`
2. The command to install `xgboost` if you are not installing from source
 <folder>/xgboost $ make JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.121-0.b13.29.amzn1.x86_64

## Steps to reproduce

1.  $ ./xgboost/dmlc-core/test/filesys_test s3://<bucket-name>/<folder> 
2.  dmlc-submit < submit yarn job >

## What have you tried?

1.  We tested on 757, each with size 550MB and it worked
2. It failed on 7437, each with size 550MB

**Comment by hvivani** [comment]
Just to add more information, when listing a bucket with large number of objects, this is the exception visible:
 src/io/s3_filesys.cc:792: Check failed: data.str() == "false" the returning list is truncated
terminate called after throwing an instance of 'dmlc::Error'
  what():  [16:18:17] src/io/s3_filesys.cc:792: Check failed: data.str() == "false" the returning list is truncated
End of LogType:stderr

As far as we can see, the error comes from:
https://github.com/dmlc/dmlc-core/blob/master/src/io/s3_filesys.cc#L834
where the XML structure being built is returned truncated. Mostly related to the large number of objects.
