### ISSUE TITLE
R xgb equivalent of python's n_estimators ?

### ISSUE THREAD

**Issue by htso** [dmlc/xgboost#2031]
I thought I must have missed something totally obvious. However, a few google/stackoverflow searches later, this' remained unanswered. So please give pointer.

For boosting tree models, the most important parameter is the number of trees to build. The python implementation of xgboost has this parameter `n_estimators`, which is explained in the API as the "Number of boosted trees to fit".

However, the R implementation seems to have no equivalent of `n_estimators`. 

Did I miss something here?

**Comment by ck37** [comment]
The function argument is `nrounds`.

**Comment by htso** [comment]
I eventually figured that out. Kind of strange same parameter has two different name. Can I propose a change?
