### ISSUE TITLE
Build Error in Windows 10

### ISSUE THREAD

**Issue by rz1988** [dmlc/xgboost#2049]
I have this error when trying to build the shared files on my windows 10 machine. 

$ make -j4
g++ -m64 -std=c++0x -Wall -Wno-unknown-pragmas -Iinclude -DDMLC_ENABLE_STD_THREA                                                                                                                            D=0  -Idmlc-core/include -Irabit/include -O3 -funroll-loops -msse2 -fopenmp -MM                                                                                                                             -MT build/common/common.o src/common/common.cc >build/common/common.d
g++ -m64 -std=c++0x -Wall -Wno-unknown-pragmas -Iinclude -DDMLC_ENABLE_STD_THREA                                                                                                                            D=0  -Idmlc-core/include -Irabit/include -O3 -funroll-loops -msse2 -fopenmp -MM                                                                                                                             -MT build/learner.o src/learner.cc >build/learner.d
g++ -m64 -std=c++0x -Wall -Wno-unknown-pragmas -Iinclude -DDMLC_ENABLE_STD_THREA                                                                                                                            D=0  -Idmlc-core/include -Irabit/include -O3 -funroll-loops -msse2 -fopenmp -MM                                                                                                                             -MT build/logging.o src/logging.cc >build/logging.d
g++ -m64 -std=c++0x -Wall -Wno-unknown-pragmas -Iinclude -DDMLC_ENABLE_STD_THREA                                                                                                                            D=0  -Idmlc-core/include -Irabit/include -O3 -funroll-loops -msse2 -fopenmp -MM                                                                                                                             -MT build/common/hist_util.o src/common/hist_util.cc >build/common/hist_util.d
cc1plus.exe: sorry, unimplemented: 64-bit mode not compiled in
Makefile:113: recipe for target 'build/common/hist_util.o' failed
mingw32-make: *** [build/common/hist_util.o] Error 1
mingw32-make: *** Waiting for unfinished jobs....
cc1plus.exe: sorry, unimplemented: 64-bit mode not compiled in
Makefile:113: recipe for target 'build/logging.o' failed
mingw32-make: *** [build/logging.o] Error 1
cc1plus.exe: sorry, unimplemented: 64-bit mode not compiled in
cc1plus.exe: sorry, unimplemented: 64-bit mode not compiled in
Makefile:113: recipe for target 'build/common/common.o' failed
mingw32-make: *** [build/common/common.o] Error 1
Makefile:113: recipe for target 'build/learner.o' failed
mingw32-make: *** [build/learner.o] Error 1

**Comment by ranaalisaeed** [comment]
i have the same problem, is there any solutions to this?

**Comment by feilx** [comment]
@rz1988 Have you solved this problem?

**Comment by SmarteDaten** [comment]
Did anyone solve the issue?

**Comment by hcho3** [comment]
You should use [mingw64](https://mingw-w64.org) instead.
