### ISSUE TITLE
Prediction before and after exporting model are not equal using R

### ISSUE THREAD

**Issue by laresbernardo** [dmlc/xgboost#2051]
## Environment info
Operating System: OS 10.12.1
Package used (python/R/jvm/C++): xgboost with R

If you are using R package, please provide

1. The R `sessionInfo()`:xgboost_0.6-4

## Steps to reproduce

```
#Having xgb1 as my resulting model:
pred <- predict(xgb1,dtest)
xgb.save(xgb1, fname="Modelo.14/Resultados/xgb1.model")
# Load binary model to R
xgb2 <- xgb.load("Modelo.14/Resultados/xgb1.model")
pred2 <- predict(xgb2, dtest)
# pred2 should be identical to pred
sum(abs(pred2-pred))
```
`[1] 13.86383`

It doesn't make any sense that the same model is having different results on the same xgb.DMatrix. Any ideas on why is this happening? Is it a bug?

**Comment by khotilov** [comment]
I just tried doing it for a few models and saw identical predictions after loading.
Could you please post a full reproducible example?

**Comment by laresbernardo** [comment]
Hey Vadim, thanks for your reply.

Here's the code:

`
############## 
# IMPORT DATA 
############## 

setwd("/Users/bernardo/Dropbox (ID)/CM Analisis/Model 2017/Funnel L2S Scoring")
df.train <- read.csv2('Modelo.15/Data/Data.15.clean.csv',stringsAsFactors=TRUE,na=as.factor("NULO"))

# Split data (train & test)
set.seed(1)
split <- sample.split(df.train$emitido, SplitRatio = 0.7) #Split 70/30
train <- subset(df.train, split == TRUE) #Training
test <- subset(df.train, split == FALSE) #Testing

###########################
# EXTREME GRADIENT BOOST
###########################

setDT(train)
setDT(test)

#Using one hot encoding
labels <- train$emitido #Target train
ts_label <- test$emitido #Target test
new_tr <- model.matrix(~.+0,data = train[,-c("emitido"),with=F]) #Predictores para train
new_ts <- model.matrix(~.+0,data = test[,-c("emitido"),with=F]) #Predictores para test

#convert factor to numeric (Done)
labels <- as.numeric(as.factor(labels))-1
ts_label <- as.numeric(as.factor(ts_label))-1

#Preparing matrix
dtrain <- xgb.DMatrix(data = new_tr,label = labels)
dtest <- xgb.DMatrix(data = new_ts,label = ts_label)

params <- list(
  booster = "gbtree", 
  objective = "binary:logistic", 
  eta=0.2, 
  gamma=0, 
  max_depth=6, 
  min_child_weight=1,
  subsample=1,
  colsample_bytree=1 
)

xgbcv <- xgb.cv(params = params,
                data = dtrain,
                nrounds = 100,
                nfold = 5, 
                showsd = T,
                stratified = T,
                print_every_n = 1, 
                early_stopping_rounds = 20,
                maximize = F,
                prediction = F)

#First default - model training
xgb1 <- xgb.train(
  params = params,
  data = dtrain,
  nrounds = 500, #Poner en defaul=bestn, pero si no llega a la mejor, ir subiéndole
  watchlist = list(val=dtest,train=dtrain),
  print_every_n = 1,
  early_stopping_rounds = 10,
  maximize = F,
  eval_metric = "error"
)

#Model prediction
(...)

#Export Model
xgb.save(xgb1, fname="Modelo.15/Resultados/xgb1.model")
# Check Exported Model
pred <- predict(xgb1,dtest)
# Load binary model to R
xgb2 <- xgb.load("Modelo.15/Resultados/xgb1.model")
pred2 <- predict(xgb2, dtest)
# pred2 should be identical to pred
sum(abs(pred2-pred))
#HERE IT DOESN'T SUM ZERO! 
`

Thanks again and hope you can detect my error then!

**Comment by laresbernardo** [comment]
This could also help. They are quite similar but not the same (weird!)

head(cbind(pred2,pred),10)

          pred2      pred
 [1,] 0.4592277 0.4418801
 [2,] 0.6649149 0.6633152
 [3,] 0.5355500 0.5366279
 [4,] 0.6931860 0.6909769
 [5,] 0.3453180 0.3444386
 [6,] 0.1047961 0.1127417
 [7,] 0.6598011 0.6692037
 [8,] 0.3942045 0.3971622
 [9,] 0.5208329 0.5224130
[10,] 0.3997675 0.3967815

**Comment by edi-bice** [comment]
Not sure where it, if at all, random numbers are used in prediction but it could be a case of different seeds.

**Comment by laresbernardo** [comment]
Actually @edi-bice I added a set.seed() so that it wouldn't be a problem (if it was) and received the same results!
Thanks for your reply. Any other suggestion?

**Comment by khotilov** [comment]
The early stopping strikes again... I'll submit a fix this weekend. 

Meanwhile, either explicitly specify the ntree limit from early stopping in a loaded model:
```R
pred2 <- predict(xgb2, dtest, ntreelimit = xgb1$best_ntreelimit)
```
or store & load as an R object:
```R
saveRDS(xgb1, 'xgb.model.rds')
xgb2 <- readRDS('xgb.model.rds')
xgb2 <- xgb.Booster.complete(xgb2)
pred2 <- predict(xgb2, dtest)
sum(abs(pred2-pred))
```

An unrelated observation: you've already got an estimate for nrounds in xgb.cv using dtrain data, why not to use it directly in xgb.test, without early stopping?

**Comment by laresbernardo** [comment]
Thanks @khotilov you rock! That was it.. so weird! Fixed :)
And thanks for the observation: true. Deleted that, got no sense at all ;)

**Comment by philave** [comment]
Is the issue solved? I mean does there exist a version of xgboost (newer than standard 0.6-4) which saves `best_ntreelimit` attribute together with xgb model?
In my case it’s difficult to use workarounds provided by @khotilov because R is used for training model which is later called in C++ code.
