### ISSUE TITLE
Question About R-package demo

### ISSUE THREAD

**Issue by moqiguzhu** [dmlc/xgboost#2055]
### Correlated code:
file:R-package/demo/caret-wrapper.R   line 27
`fitControl <- trainControl(method = "cv", number = 10, repeats = 2, search = "random")`

### Description
In this demo, we use `caret` for search hyperparameter space.
After reading some documents about `caret`, I think  `method=cv` should be `method=repeatedcv`.
According to `caret` documentation:
> number controls with the number of folds in K-fold cross-validation or number of resampling iterations for bootstrapping and leave-group-out cross-validation. repeats applied only to repeated K-fold cross-validation. Suppose that method = "repeatedcv", number = 10 and repeats = 3,then three separate 10-fold cross-validations are used as the resampling scheme. 

I also run the demo code and printed the model, the result is that cv is never repeats as supposed.

I also find a supporting link here
http://stats.stackexchange.com/questions/44343/in-caret-what-is-the-real-difference-between-cv-and-repeatedcv

@pluskid

**Comment by khotilov** [comment]
Right, `repeats` is only used in `repeatedcv`, `adaptive_cv` and `subsample` methods:
https://github.com/topepo/caret/blob/1553656d4c7e99bc1ad8efaf1b605bb92050d393/pkg/caret/R/train.default.R#L360 
Feel free to submit a PR.
