### ISSUE TITLE
[jvm-packages][spark] parallel model training

### ISSUE THREAD

**Issue by CodingCat** [dmlc/xgboost#2057]
we currently do not support train multiple models in the same cluster in parallel due to the communication issues in rabit (pyrabit)

@xydrolase have you ever tried to do this?

**Comment by edi-bice** [comment]
Wait - what? Never came across any caution against such a thing in the documentation. What happens if you do? I haven't noticed any glaring problems.

**Comment by CodingCat** [comment]
In some cases, the application may stop with a rabit fault, some potential native problem there....if your app does not stop unexpectedly that shall be fine...

**Comment by superbobry** [comment]
Does this limitation extend to the Scala rabit backend?

**Comment by CodingCat** [comment]
I am not sure, but I think it will....since the error is caused in native layer
