### ISSUE TITLE
having a hard time installing on windows

### ISSUE THREAD

**Issue by asimkievich** [dmlc/xgboost#206]
Hi there, I am having a hard time installing xgboost on Windows. I use Python (version 3.3), Anaconda Distribution.

Anaconda has the following directory:

c:\users\xxx\anaconda3\lib\site-packages\

there you can find sklearn, for example, and there I pasted all foldes under https://github.com/dmlc/xgboost

However, I cannot run the Makefile (error message is fatal error U1063: missing macro name before '-'.

I would really like to try out xgboost and would fully appreciate any hint on how to do so. Thanks.

**Comment by tqchen** [comment]
Use VS project https://github.com/dmlc/xgboost/tree/master/windows to build the dll for windows

**Comment by asimkievich** [comment]
Hi Tianqi,

first, thanks for making this available. Would you mind including a more
step by step explanation?

I click on your link and I see two directories and two files, as per the
screenshot below. What do I do next?

Sorry, not sure how you build a dll for windows but if you provide a hint I
will definitely do it.
Thanks.
Best,
A

[image: Inline image 1]

*Alejandro Simkievich*
CEO | *Statec *
M: +55 11 99634 6673
http://www.statec.com.br
skype: asimkievich
[image: Follow us on Linkedin]
<http://t.signauxdix.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs7fsZxlN8qC6PYfmKYvW2zGrQM56dTb1dvWBqC02?t=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2F3658897%3Ftrk%3Dprof-exp-company-name&si=5363976030388224&pi=a2ed89c4-1cd8-4fa9-bf17-af506933d78f>
Let's
connect!
<http://t.signauxdix.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs7fsZxlN8qC6PYfmKYvW2zGrQM56dTb1dvWBqC02?t=https%3A%2F%2Ftwitter.com%2FSTAtecBrasil&si=5363976030388224&pi=a2ed89c4-1cd8-4fa9-bf17-af506933d78f>
Follow
us!  Like us!

**Comment by tqchen** [comment]
open the project in visual studio, click to switch to x64 release, and build all. This will build the dll you want. And you will be able to use the examples in demo

**Comment by asimkievich** [comment]
thxs. did not have visual studio, downloading it now. hope i do not have to
bother you again.

*Alejandro Simkievich*
CEO | *Statec *
M: +55 11 99634 6673
http://www.statec.com.br
skype: asimkievich
[image: Follow us on Linkedin]
<http://t.signauxdix.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs7fsZxlN8qC6PYfmKYvW2zGrQM56dTb1dvWBqC02?t=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2F3658897%3Ftrk%3Dprof-exp-company-name&si=5363976030388224&pi=9e723f58-62cf-44e1-b0fe-c4f49940be3a>
Let's
connect!
<http://t.signauxdix.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs7fsZxlN8qC6PYfmKYvW2zGrQM56dTb1dvWBqC02?t=https%3A%2F%2Ftwitter.com%2FSTAtecBrasil&si=5363976030388224&pi=9e723f58-62cf-44e1-b0fe-c4f49940be3a>
Follow
us!  Like us!

**Comment by asimkievich** [comment]
Hi Tianqi,

I did as explained. I opened the project in VS studio, switched to x64 and
release, and built. I see the message as in screenshot below.

========== Build: 3 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

Is that all?

Can I now run xgboost in Python?

Thanks.
Best,

A

[image: Inline image 2]

*Alejandro Simkievich*
CEO | *Statec *
M: +55 11 99634 6673
http://www.statec.com.br
skype: asimkievich
[image: Follow us on Linkedin]
<http://t.signauxdix.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs7fsZxlN8qC6PYfmKYvW2zGrQM56dTb1dvWBqC02?t=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2F3658897%3Ftrk%3Dprof-exp-company-name&si=5363976030388224&pi=3c1c19b2-08f0-4aa6-a8a0-66c30dfabac8>
Let's
connect!
<http://t.signauxdix.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs7fsZxlN8qC6PYfmKYvW2zGrQM56dTb1dvWBqC02?t=https%3A%2F%2Ftwitter.com%2FSTAtecBrasil&si=5363976030388224&pi=3c1c19b2-08f0-4aa6-a8a0-66c30dfabac8>
Follow
us!  Like us!

**Comment by asimkievich** [comment]
PS: sorry to bother, I still get the error message below in Python 3.3.
Any hint?
Thanks.

:\Users\Alejandro\Anaconda3\python.exe
C:/Users/Alejandro/Documents/Kaggle/Otto/graphlab.py
Traceback (most recent call last):
  File "C:/Users/Alejandro/Documents/Kaggle/Otto/graphlab.py", line 28, in
<module>
    xg_train = xgb.DMatrix(train, label=labels)
AttributeError: 'module' object has no attribute 'DMatrix'

Process finished with exit code 1

*Alejandro Simkievich*
CEO | *Statec *
M: +55 11 99634 6673
http://www.statec.com.br
skype: asimkievich
[image: Follow us on Linkedin]
<http://t.signauxdix.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs7fsZxlN8qC6PYfmKYvW2zGrQM56dTb1dvWBqC02?t=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2F3658897%3Ftrk%3Dprof-exp-company-name&si=5363976030388224&pi=38611fb9-919e-4171-fba8-07442f653a88>
Let's
connect!
<http://t.signauxdix.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs7fsZxlN8qC6PYfmKYvW2zGrQM56dTb1dvWBqC02?t=https%3A%2F%2Ftwitter.com%2FSTAtecBrasil&si=5363976030388224&pi=38611fb9-919e-4171-fba8-07442f653a88>
Follow
us!  Like us!

**Comment by asimkievich** [comment]
Hi Tianqi,

It's working, I just need to point to the directory where the wrapper is in
the command below.
Thanks so much!
The good karma you create will come back to you!
Take care,
A

sys.path.append('../../wrapper')

*Alejandro Simkievich*
CEO | *Statec *
M: +55 11 99634 6673
http://www.statec.com.br
skype: asimkievich
[image: Follow us on Linkedin]
<http://t.signauxdix.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs7fsZxlN8qC6PYfmKYvW2zGrQM56dTb1dvWBqC02?t=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2F3658897%3Ftrk%3Dprof-exp-company-name&si=5363976030388224&pi=d1dfd70a-6569-4972-c7ac-ab4e5273ec8a>
Let's
connect!
<http://t.signauxdix.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs7fsZxlN8qC6PYfmKYvW2zGrQM56dTb1dvWBqC02?t=https%3A%2F%2Ftwitter.com%2FSTAtecBrasil&si=5363976030388224&pi=d1dfd70a-6569-4972-c7ac-ab4e5273ec8a>
Follow
us!  Like us!

**Comment by tqchen** [comment]
Thanks for using xgboost! Indeed your question makes me realize we should have more clear instruction in windows folder. Will do an update

**Comment by dagley11** [comment]
Struggling mightily with Windows 64-bit installation. 

I tried using MinGW-w64 and received a ' A subdirectory or file -p already exists' error.  Deleting directory and re-cloning did not solve.  Similar issues were discovered in this thread: https://www.kaggle.com/c/liberty-mutual-group-property-inspection-prediction/forums/t/15742/clear-instructions-to-install-xgboost-in-python/108483#post108483

My next step was to follow instructions listed here with Visual Basic Studio.  But https://github.com/dmlc/xgboost/tree/master/windows is down.  Please advise on next steps!

**Comment by tqchen** [comment]
@dagley11 this was due to the fact that mkdir command in windows was not compatible with those in linux. Can you remove the -p in  this line and try again https://github.com/dmlc/xgboost/blob/master/Makefile#L97

I will try to find another solution that works well later

**Comment by thirdwing** [comment]
The simplest solution is not using Windows CMD.

**Comment by tqchen** [comment]
@thirdwing Does sh comes by default together with ming-w64? If it is the case, we should encourage user to type ```sh ``` before type make

**Comment by cydal** [comment]
Hi there, I'm having a lot of trouble installing this on windows, the funny part is that I have actually done it multiple times before, I had installed xgboost on windows servers many times before following the otto installation guide, one thing I've noticed now is that the github link is different, clicking on the otto link now for github actually says 'page not available'. It's possible the problems I'm having now has to do with this. Anyway, when I open the project file in Visual studio, an error comes up saying "xgboost\dmlc-core\windows\test\test.vcxproj" could not be found.", now I ignore this and go ahead to build it but it says build 1 succeeded when it should say 3. Someone help please. I'm on windows 10 64 bit.
