### ISSUE TITLE
Different AUC score from sklearn.metrics function (binary:logistic)

### ISSUE THREAD

**Issue by segalou** [dmlc/xgboost#2064]
I'm using xgboost's sklearn wrapper for a binary classifcation task and then use sklearn.metrics' auc for scoring

for reproduce the issue, I will use breast_cancer dataset from sklearn for illustration.

```
df = load_breast_cancer().data
y = load_breast_cancer().target

X_train, X_test, y_train, y_test = train_test_split(df, y, test_size=0.33, random_state=7)

params={
    'n_estimators':500,
    'objective': 'binary:logistic',
    'learning_rate': 0.05,
    'gamma':0.1,
    'subsample':0.8,
    'colsample_bytree':0.3,
    'min_child_weight':3,
    'max_depth':6,
    'seed':1024,
    }

clf = XGBClassifier(**params)
clf.fit(X_train, y_train, \
        eval_set=[(X_train, y_train), (X_test, y_test)], \
                  eval_metric='auc', early_stopping_rounds = 50)
```
the output gives the result as :

`Stopping. Best iteration:
[168]   validation_0-auc:0.998853       validation_1-auc:0.997766`

but when I use auc scoring function by following code:
```
y_pred = clf.predict(X_test)
print metrics.roc_auc_score(y_test,y_pred)
```

the result is :
`0.957627118644`

if I use xgb directly. the auc result matches the sklearn.metrics output
anything wrong with my code?

## Environment info
Operating System: Windows 10
Compiler: MinGW-W64-builds-4.2.0
Package used (python/R/jvm/C++): Python
`xgboost` version used: 0.6

If you are using python package, please provide
1. The python version and distribution Anaconda python version 2.7

**Comment by Gunthard** [comment]
Hi,
you have to predict probabilities (clf.predict_proba) instead of classes to calculate the ROC AUC score:
``` python
y_pred = clf.predict_proba(X_test)[:,1]
print 'Last fitted model score:', roc_auc_score(y_test,y_pred)
>> Last fitted model score: 0.997503613191
```

And by he way, if you use early_stopping you have to refit the classifier with the number of trees from the best round.  Fit will return the model from the last iteration, not the best one. See docs for details.
``` python
print 'Best nr of trees:', clf.best_ntree_limit
clf.set_params(**{'n_estimators': clf.best_ntree_limit})
clf.fit(X_train, y_train)

y_pred = clf.predict_proba(X_test)[:,1]
print 'Best eval model score:', roc_auc_score(y_test,y_pred)
>> Best nr of trees: 169
>> Best eval model score: 0.99776639075
```
