### ISSUE TITLE
[jvm-packages] Issue running XGBoost Spark example

### ISSUE THREAD

**Issue by priyan-g** [dmlc/xgboost#2067]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System: OS X El Capitan

Compiler: Apple LLVM version 7.0.2 (clang-700.1.81)

Package used (python/R/jvm/C++): jvm

`xgboost` version used: 0.7
'spark' - 2.0.0
'scala' - 2.10.6

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`)
2. Logs will be helpful (If logs are large, please upload as attachment).

If you are using python package, please provide

1. The python version and distribution
2. The command to install `xgboost` if you are not installing from source

If you are using R package, please provide

1. The R `sessionInfo()`
2. The command to install `xgboost` if you are not installing from source

Reposting the question here as this is
## Steps to reproduce

1.  Compile and install of jvm-package
2. Running the XGBoost-Spark example

## What have you tried?
I am encountering a type mismatch problem at the following step when running the XGBoost-Spark

val model = XGBoost.train(trainData3, paramMap, round=2, nWorkers=2, useExternalMemory=true, missing=0.0f ) 

error: type mismatch org.apache.spark.rdd.RDD[org.apache.spark.mllib.regression.LabeledPoint] required: org.apache.spark.rdd.RDD[org.apache.spark.ml.feature.LabeledPoint]

It seems that val trainData3 = MLUtils.loadLibSVMFile(sc, inputTrainPath) earlier produces a mllib.regression.LabeledPoint rather than a ml.feature.LabelPoint that XGBoost expects.

To test my overall setup, I manually created a ml.feature.LabelPoint via

val trainRDD = sc.parallelize(Seq(
     |   LabeledPoint(1.0, new DenseVector(Array(2.0, 3.0, 4.0))),
     |   LabeledPoint(0.0, new DenseVector(Array(5.0, 5.0, 5.0))),
     ...
     ),4)
This as input to xgboost.train runs without any issues. trainRDD is a org.apache.spark.ml.feature.LabeledPoint

Any thoughts on why I am seeing this type mismatch? thanks!

**Comment by CodingCat** [comment]
wait....you mean you can compile the examples but cannot run with a type mismatch issue?

**Comment by priyan-g** [comment]
yes. 

    On Sunday, February 26, 2017 10:58 AM, Nan Zhu <notifications@github.com> wrote:
 

 wait....you mean you can compile the examples but cannot run with a type mismatch issue?—

**Comment by CodingCat** [comment]
can you post the complete log trace with the error? It is impossible for the scala compiler to let a program with type mismatch error go

**Comment by priyan-g** [comment]
Hi Nan,
Thanks for your response.  
I misspoke about the compile error. Sorry.   I do have compiler errors.
Error:(38, 31) type mismatch; found   : org.apache.spark.rdd.RDD[org.apache.spark.mllib.regression.LabeledPoint] required: org.apache.spark.rdd.RDD[org.apache.spark.ml.feature.LabeledPoint]    val model = XGBoost.train(trainRDD, paramMap, numRound, nWorkers = 5, useExternalMemory = true)
There are also errors stating nWorkers, useExternalMemory and saveModelToHadoop unresolved. I am wondering whether I missed out something in my XGBoost compile ? (scala 2-10.6, spark_2.11-2.0.0 xgboost4j-spark-0.7, Apple LLVM version 7.0.2 (clang-700.1.81)
I ran the same code in a spark-shell.  There again, I was able to see the type mismatch error. However, when I changed the trainRDD to below (type ml.feature.LabeledPoint)  it ran without any issue.
val trainRDD = sc.parallelize(Seq(
     |   LabeledPoint(1.0, new DenseVector(Array(2.0, 3.0, 4.0))),
     |   LabeledPoint(0.0, new DenseVector(Array(5.0, 5.0, 5.0))),
     ...
     ),4)
Any thoughts/suggestions you can provide much appreciated.
thanks--priyan
import ml.dmlc.xgboost4j.scala.Booster
import org.apache.spark.SparkConf
import org.apache.spark.SparkContext
import org.apache.spark.mllib.util.MLUtils
import ml.dmlc.xgboost4j.scala.spark.XGBoost





object XGboostSparkHello {
  def main(args: Array[String]): Unit = {
    if (args.length != 3) {
      println(
        "usage: program  num_of_rounds training_path model_path")
      sys.exit(1)
    }
    // if you do not want to use KryoSerializer in Spark, you can ignore the related configuration
    val sparkConf = new SparkConf().setMaster("local[*]").setAppName("XGBoost-spark-example")
      .set("spark.serializer", "org.apache.spark.serializer.KryoSerializer")
    sparkConf.registerKryoClasses(Array(classOf[Booster]))
    val sc = new SparkContext(sparkConf)
    val inputTrainPath = args(1)
    val outputModelPath = args(2)
    // number of iterations
    val numRound = args(0).toInt
    val trainRDD = MLUtils.loadLibSVMFile(sc, inputTrainPath)
    // training parameters
    val paramMap = List(
      "eta" -> 0.1f,
      "max_depth" -> 2,
      "objective" -> "binary:logistic").toMap
    // use 5 distributed workers to train the model
    // useExternalMemory indicates whether
    val model = XGBoost.train(trainRDD, paramMap, numRound, nWorkers = 5, useExternalMemory = true)
    // save model to HDFS path
    model.saveModelToHadoop(outputModelPath)
  }
} 

    On Sunday, February 26, 2017 12:58 PM, Nan Zhu <notifications@github.com> wrote:
 

 can you post the complete log trace with the error? It is impossible for the scala compiler to let a program with type mismatch error go—

**Comment by CodingCat** [comment]
so, it is not Spark example code, it is your own program, right?

Please update the issue title accordingly

and also, please check the example code `SparkWithRDD` where it has an explicit conversion

**Comment by priyan-g** [comment]
Thanks.  It is the Spark example code listed on
 https://github.com/dmlc/xgboost/tree/master/jvm-packages.  Not really my code.

 Thanks for the suggestion on using SparkWithRDD.  I tried out https://github.com/dmlc/xgboost/blob/master/jvm-packages/xgboost4j-example/src/main/scala/ml/dmlc/xgboost4j/scala/example/spark/SparkWithRDD.scala that includes a conversion that resolves the type mismatch problem.  That works!

Appreciate your help Nan.  I will update my ticket.
cheers--priyan



    On Sunday, February 26, 2017 5:01 PM, Nan Zhu <notifications@github.com> wrote:
 

 so, it is not Spark example code, it is your own program, right?Please update the issue title accordinglyand also, please check the example code SparkWithRDD where it has an explicit conversion—

**Comment by damienrj** [comment]
Would you mind sharing your code, I also couldn't get the spark example working for the same type mismatch error.
