### ISSUE TITLE
Dumpmodel has insufficient precision for dumping floats

### ISSUE THREAD

**Issue by adalsteinnpals** [dmlc/xgboost#2077]
When dumping the model the floats are dumped with a standard precision of 6, which is insufficient.
This creates inconsistencies if the dumped model would be compared to the model in the xgboost class.

It can be fixed like this in /src/tree/tree_model.cc

```
std::string RegTree::DumpModel(const FeatureMap& fmap,
                               bool with_stats,
                               std::string format) const {
  std::stringstream fo("");
  fo << std::setprecision(9);   // increase the precision
  for (int i = 0; i < param.num_roots; ++i) {
    DumpRegTree(fo, *this, fmap, i, 0, false, with_stats, format);
  }
  return fo.str();
}
}  // namespace xgboost
```

**Comment by happyphonon** [comment]
I got the same problem when I convert dumped file to a java file. The output produced by java code have different result as python code up to 1e-4.

**Comment by philipp-fischer** [comment]
I am having the same problem. Precision is not enough to recover the model from a dump.
What is the correct way to deal with it? Anyway I like the suggestion by @adalsteinnpals to increase the precision

**Comment by veereshbeeram** [comment]
I believe this ticket is now fixed via pull request: https://github.com/dmlc/xgboost/pull/3298
