### ISSUE TITLE
Documents for xgboost4j-spark is too brief

### ISSUE THREAD

**Issue by jzhusc** [dmlc/xgboost#2078]
Documents for xgboost4j-spark is too brief.
For example, I am find that ``XGBoostClassificationModel`` has a ``transform`` method that takes ``ParamMap``. But there is no explanation for this. Is that a map for hyper parameter like missing value or the model param.
Also ``predict`` can take ``missingValue`` but ``transform`` can't.
Anyone can help me with that?
Thank you!

**Comment by CodingCat** [comment]
transform is mllib api...get familiar with the basic usage of mllib would help

**Comment by jzhusc** [comment]
Thank you.
Actually my problem is that the missing value for ``transform`` is hard coded to 0.
The code is here
https://github.com/dmlc/xgboost/blob/e7fbc8591fa7277ee4c474b7371c48c11b34cbde/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostModel.scala#L254

is there any way to fix it?

**Comment by CodingCat** [comment]
right now no...you can call predict and compose the DF based on the results

**Comment by jzhusc** [comment]
I see, thanks a lot!
By the way, ``tree_method=exact`` is not supported in xgboost4j-spark, right? Just want to confirm.

**Comment by CodingCat** [comment]
why?

**Comment by jzhusc** [comment]
According to the parameter document.
https://github.com/dmlc/xgboost/blob/master/doc/parameter.md
the ``tree_method``
"Distributed and external memory version only support approximate algorithm."
@CodingCat

**Comment by jzhusc** [comment]
@tqchen I am really sorry to bother you but I find that distributed training has lower testing accuracy  (96% vs 99%) but almost the same training accuracy (99%) than single node training under the parameter setting. Is there any way to make ``tree_method=approx`` more exact? I tried to lower the ``sketch_eps`` and ``eta``. Thank you!

**Comment by xydrolase** [comment]
@jzhusc According to the model parameter, you could set `tree_method=exact`: https://github.com/dmlc/xgboost/blob/ab13fd72bd5f3d9a9062fd3aa257fc1710756494/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/BoosterParams.scala#L128

Did you notice in the output that XGBoost overrides your `tree_method` parameter?

**Comment by damienrj** [comment]
Some documentation is also broken.
https://github.com/dmlc/xgboost/issues/1998

**Comment by emla2805** [comment]
Correct me if I'm wrong, but the fact that `predict` can take missingValue but `transform` can't, means that `crossValidator` in mllib is not usable with XGBoost, right? Except if your missing value happens to be 0.

**Comment by CodingCat** [comment]
https://github.com/dmlc/xgboost/blob/master/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/GeneralParams.scala#L71
