### ISSUE TITLE
xgboost on windows working on and off

### ISSUE THREAD

**Issue by asimkievich** [dmlc/xgboost#208]
hi there, I installed XGBoost on Windows and it does work - however, not always.

I cannot entirely pinpoint why. Right now I am getting the error message below. However, when I open the project xgboost in VS studio, I see the first message.

any clues? Thanks.

========== Build: 0 succeeded, 0 failed, 3 up-to-date, 0 skipped ==========

Traceback (most recent call last):
  File "C:\Users\Alejandro\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2883, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-1f19b3eff4b8>", line 22, in <module>
    xg_train = xgb.DMatrix(train, label=labels)
AttributeError: 'module' object has no attribute 'DMatrix'

**Comment by tqchen** [comment]
If the effort is reported in that way, It usually means the path of xgboost was not added to the search path when you import xgb.

There are two ways to solve the problem, append the absolute path to the wrapper using sys.append before you import, or add path to the wrapper to the PYTHONPATH environment variable

Tianqi

**Comment by asimkievich** [comment]
Tianqi,

I believe I know that the problem is. The absolute path needs to be
appended BEFORE you import.  I was appending after the import and that was
most likely the problem.

Thanks again.
Best,

Alex

*Alejandro Simkievich*
CEO | *Statec *
M: +55 11 99634 6673
http://www.statec.com.br
skype: asimkievich
[image: Follow us on Linkedin]
<http://t.signauxdix.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs7fsZxlN8qC6PYfmKYvW2zGrQM56dTb1dvWBqC02?t=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2F3658897%3Ftrk%3Dprof-exp-company-name&si=5363976030388224&pi=018936b1-2bc3-4481-8a68-d5dbffabb447>
Let's
connect!
<http://t.signauxdix.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs7fsZxlN8qC6PYfmKYvW2zGrQM56dTb1dvWBqC02?t=https%3A%2F%2Ftwitter.com%2FSTAtecBrasil&si=5363976030388224&pi=018936b1-2bc3-4481-8a68-d5dbffabb447>
Follow
us!  Like us!

**Comment by sh1ng** [comment]
I've the same issue on Mac OS.
PYTHONPATH is configured
