### ISSUE TITLE
xgboost model feature map as an R object

### ISSUE THREAD

**Issue by sjain777** [dmlc/xgboost#2082]
Hi, in the R package, xgb.dump allows me to save the model Feature Map into a text file via "fmap". 
Is it possible to make an enhancement for storing the Feature Map as an internal R object? Thanks.

**Comment by khotilov** [comment]
A feature map is a file that describes features used in a model, and it is something you might potentially want to provide for `xgb.dump`, not something that `xgb.dump` saves as a result.

**Comment by sjain777** [comment]
Is it possible to provide a method for extracting the Feature Map from the xgb model as a data.frame? A feature map is required to create a PMML from the xgb model via r2pmml, and the ability to create this map directly from the xgb model would be very useful. Thanks!

**Comment by khotilov** [comment]
I'm not familiar with `r2pmml`, but it does seem to provide such a function for input data: https://github.com/jpmml/r2pmml/blob/b175c0e49c8595a73adf7e97249942db15c52680/R/xgboost.R#L12

And it's very easy to create such a fmap data.frame from feature names stored in a model's R object, e.g.
`data.frame(seq_along(bst$feature_names)-1, bst$feature_names, "q")`
Note that currently all the input features to xgboost must be numeric.

**Comment by sjain777** [comment]
thanks much for the syntax for creating the feature map from the bst object! That answers my question and the issue can be closed.

**Comment by sjain777** [comment]
Hello,

**Comment by sjain777** [comment]
Hello, I just now tried using `bst$feature_names` suggested in your reply above, but got back NULL. Could you please let me know what to do differently in order to get back the feature_names from the XGBOOST Model - `bst`? Thanks

Here 's my example: 

`require(xgboost)`
`data(agaricus.train, package='xgboost')`
`data(agaricus.test, package='xgboost')`
`dtrain <- xgb.DMatrix(agaricus.train$data, label = agaricus.train$label)`
`dtest <- xgb.DMatrix(agaricus.test$data, label = agaricus.test$label)`
`param <- list(max_depth=2, eta=1, silent=1, objective='binary:logistic')`
`watchlist <- list(eval = dtest, train = dtrain)`
`nround = 2`
`bst = xgb.train(param, dtrain, nround, nthread = 2, watchlist)`

`bst$feature_names`
NULL
