### ISSUE TITLE
xgb.cv randomly stalls

### ISSUE THREAD

**Issue by WhoisDavid** [dmlc/xgboost#209]
Hi there,
Thanks a lot for an excellent package !

I'm using xgboost on R 3.1.3 (Windows 7 and 8) with RStudio on an i7 (on 8 threads).
I've noticed that xgb.cv stalls quite often for unknown reasons. The CPU usage suddenly drops and nothing happens.
The only thing that I can do when it happens is kill the rsession.exe and start from fresh. Then running the exact same query (same parameters,same data, same seed) will work nicely.

Regarding the frequency, I'd say that happens every 5-10 runs so quite frequently.

Might be a threading issue but it's difficult to investigate.

Thanks,
David

**Comment by tqchen** [comment]
It would be great if you could provide a short snippet of code to reproduce this. Would even be better if that could be done

**Comment by WhoisDavid** [comment]
Thanks for the quick answer.
I'm not doing rocket science. Just simple cross-validation.
I guess the easier to reproduce is to loop on xgb.cv.
As I said, for me it happens randomly. Will stall once and then run fine.
Something like looping on parameters (nested loops in R = just for the eyes...) :

```R
tuning=list()
for(depth in seq(6, 16, by=2)){
 for(eta in seq(0.01, 0.1, length.out = 4)){
   print(paste(depth, eta, sep="-"))
   tuning_param = list("objective" = "multi:softprob",
                  "eval_metric" = "mlogloss",
                  "eta"=eta,
                  "max_depth"=depth,
                  "num_class" = 9,
                  "nthread" = 8)
    tuning.cv = xgb.cv(param=tuning_param, data = train_mat, label = train_class,  nfold = 8, nrounds=1500)  
    tuning.cv=tuning.cv[, lapply(.SD, as.numeric)]
    tuning.cv[, ':='(index=1:nrow(tuning.cv), eta=eta, depth=depth)]
    tuning.cv[which.min(test.mlogloss.mean + test.mlogloss.std)]
    tuning=c(tuning, list(tuning.cv[which.min(test.mlogloss.mean + test.mlogloss.std)]))
 }
} 
```
The data i'm using is from a running kaggle competition (otto-group).
Thanks a lot !

**Comment by hetong007** [comment]
@WhoisDavid Thanks for your code. When the program got stucked, the possible reasons are

1. There's some complicated computation ongoing behind.
2. There's a bug stopping the program.

To be more efficient, I use the following code which tests your code on a small random data set. On my side, the program sometimes stays at one step for 1~2 seconds and then it keeps running. Which means it is the first situation. Is this the same as what you observed? 

No matter which one it is, we need to solve it. Providing more information will help us locate the problem faster. 

```r
require(xgboost)

train_mat = matrix(rnorm(200*5),200,5)
train_class = sample(0:2,200,replace=TRUE)

tuning=list()
for(depth in seq(6, 16, by=2)){
    for(eta in seq(0.01, 0.1, length.out = 4)){
        print(paste(depth, eta, sep="-"))
        tuning_param = list("objective" = "multi:softprob",
                            "eval_metric" = "mlogloss",
                            "eta"=eta,
                            "max_depth"=depth,
                            "num_class" = 9,
                            "nthread" = 8)
        tuning.cv = xgb.cv(param=tuning_param, 
                           data = train_mat, 
                           label = train_class,  
                           nfold = 3, nrounds=1500)  
        tuning.cv=tuning.cv[, lapply(.SD, as.numeric)]
        tuning.cv[, ':='(index=1:nrow(tuning.cv), eta=eta, depth=depth)]
        tuning.cv[which.min(test.mlogloss.mean + test.mlogloss.std)]
        tuning=c(tuning, list(tuning.cv[which.min(test.mlogloss.mean + test.mlogloss.std)]))
    }
}
```

**Comment by WhoisDavid** [comment]
I think it's more than that. 
I'm travelling and can't test with your dummy data unfortunately. 
What i noticed:
1) in a normal run, it uses  around 90% of my CPU (an i7). When it "stalls", the usage of my cpu (an i7) drops to 15%-20%. Then it's like that for hours. I've let it run several hours and nothing moved. I then had to kill the program.
2) the other thing that hints at a bug is that the same code with the same seed will run in minutes if I rerun it. 

That's why I was thinking of a drop of communication between threads. To be fair, I haven't tried running this in a single thread. 

Also, note that the data I use is much bigger. From memory the train set has 168k observations, 93 features and 9 classes. Perhaps it's worth trying your code with more classes ?

Thanks a lot for investigating and again, I can't emphasize enough how great this library is!
David

**Comment by WhoisDavid** [comment]
@hetong007 I wasn't able to reproduce with your code. So it certainly has to do with the complexity of the data.
However, I can confirm it does not stall when running on 1 thread (I am running multiple instances with nthread=1 and it's been running for over a day now).
It really looks like some kind of deadlock. Maybe an issue with OpenMP.

If you have any idea of what I could do to help, happy to do so !

**Comment by tqchen** [comment]
@WhoisDavid It would be great if we could find out at which point of the program it stalls. It is likely to be somewhere near https://github.com/dmlc/xgboost/blob/master/src/tree/updater_colmaker-inl.hpp#L420.

Maybe I am asking too much from you on this, but if you could add things like utils::Printf("enter loop A\n"); and utils::Printf("exit loop A\n"); (After modification, install with command R CMD INSTALL R-package) around the possible omp blocks, and check at which block it stalls, we might get a better evidence of what is going on.

Tianqi

**Comment by WhoisDavid** [comment]
@tqchen I've done so. It appears it stalls a bit further than the line you mentioned in the ResetPosition method. See screenshot below.

Hope this helps ! 
David

![image](https://cloud.githubusercontent.com/assets/5764201/7092152/b113edfa-dfaf-11e4-9394-9c88d1422373.png)

**Comment by tqchen** [comment]
Thanks @WhoisDavid , I really appreciated it. 

All of parallelism in xgboost only involves omp and no lock, so there was less likely to be a deadlock in such case.. I have pushed a small boundary check on this for loop in case there is a boundary problem.

Another thing we can try is to remove the omp pragram thing at beginning of the loop to see if this was specifically caused by omp on that loop

How long does it take normally to reproduce the stall? I wish I could look into what was going on when it stalls but usually this requires debuggers such as gdb..

Thanks again

**Comment by WhoisDavid** [comment]
@tqchen  It stalled again on the latest version and no message on the console.
It's difficult to say how long it takes. Can be 20-30 min like it can be 2-3 hours. Usually it's not more than a few runs (5 to 15 xgb.cv).
On the "bright side" I was never able to finish a full run, it always stalled at some point so I'm about certain it will reproduce - just don't know when nor why !
I'll try and remove the pragram see what happens.

**Comment by WhoisDavid** [comment]
@tqchen My adventures continue... I removed the pragma. Now it stalls on another loop and I got an error message (see below) !
![image](https://cloud.githubusercontent.com/assets/5764201/7121293/e0b944cc-e213-11e4-96fa-27e4bf14a69c.png)

Does this help in anyway... ? I'll try and remove this other pragma.

**Comment by tqchen** [comment]
@WhoisDavid There has been some recent fix to the R module more on the memory checks since 0.4 . I am not sure if it would be related to what you experienced. If you have time, would you like to try again if the latest version in master branch still have the problem?

Thanks

**Comment by WhoisDavid** [comment]
@tqchen I ran the new version and had the same problem. 
Maybe I could send you some data and some code see if you ran into the same problem. Could I email these to you on your @cs.washington.edu address ?

**Comment by tqchen** [comment]
Sure, I tried to rerun the program you posted but did not reproduce the error
