### ISSUE TITLE
xgb.DMatrix in R hangs inside of mclapply

### ISSUE THREAD

**Issue by rmcgehee** [dmlc/xgboost#2094]
Hello,
I discovered a short script that causes xgboost (v 0.6-4) to hang if the user has previously called xgb.DMatrix, and then the user subsequently runs xgb.DMatrix again inside of an mclapply in R. I installed xgboost from CRAN on Linux / R v3.3.2. As I have been trying to train many models in parallel, I encounter this issue frequently.

Here is the script:

require(xgboost)
require(parallel)
data(agaricus.train, package='xgboost')
dtrain <- xgb.DMatrix(agaricus.train$data)
. <- mclapply(1:2, function(i)
    dtest <- xgb.DMatrix(agaricus.train$data)
  , mc.cores=2)
## Hang

Hope this helps,
--Robert

**Comment by khotilov** [comment]
It's a known gcc problem with using OpenMP multithreading (in here, while reading data into DMatrix) within unix forks (that's what mclapply is based on):
http://bisqwit.iki.fi/story/howto/openmp/#OpenmpAndFork
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=58378

When you plan to run anything multithreaded within mclapply, always set the number of threads to 1 prior to that. Also, just in case, don't be surprised that DMatrix or booster objects would not have valid handles after returning them from a parallel process.
