### ISSUE TITLE
What's wrong with docs page?

### ISSUE THREAD

**Issue by ysh329** [dmlc/xgboost#2099]
When I click **Packages** on [docs site](http://xgboost.readthedocs.io/en/latest/), the browser don't move?! Is there anything wrong with docs?
Besides, I found there is something wrong with search box(CAN'T SEARCH ANYTHING)? Do anyone else find that?

**Comment by tqchen** [comment]
hmm, seems something is wrong with the navi-bar. I am not expert in the html docs. maybe we could ask someone for help @kevinthesun can you help to take a look at the issue?

**Comment by kevinthesun** [comment]
I'm not working on this website. A quick check is chrome will report Bootstrap's jQuery version issue:

**Comment by ysh329** [comment]
@njwilson23 @kashif @tqchen My dear brothers, may anyone fix this problem? The search function can't be used, making users depressed when search some special APIs. :sob:

**Comment by hcho3** [comment]
Replacing `jquery.js` with [version 2.2.4](https://code.jquery.com/jquery-2.2.4.min.js) fixes the problem. So it all boils down to replacing the outdated `jquery.js` file.

How to re-produce:
* Use `wget` to download the index page and associate assets
```bash
wget -p http://xgboost.readthedocs.io/en/latest/
cd xgboost.readthedocs.io/en/latest/
```
* Replace `jquery.js` with version 2.2.4
```bash
wget -O _static/jquery.js https://code.jquery.com/jquery-2.2.4.min.js
```
* Run `SimpleHTTPServer`:
```bash
python -m SimpleHTTPServer
```
* On the web browser, browse to `http://localhost:[port number]`.

**Comment by ysh329** [comment]
@hcho3 Thanks, I tried as your showed me. However, after clicking **Python** term below Packages, it shows below:

![error response](https://user-images.githubusercontent.com/7320657/28993636-059eb398-79ee-11e7-9177-9d612d4d7887.png)

**Comment by hcho3** [comment]
@ysh329 The reproduction step was only to show how to fix the drop down menu. Since only the index page was downloaded to your computer, the python link would not work.

**Comment by hcho3** [comment]
Ultimately, the website administrator will need to change `jquery.js`. My post only proves that the change would certianly work if applied.

**Comment by ysh329** [comment]
@hcho3 I knew, Thanks! Besides, there's something wrong with search box.

**Comment by tqchen** [comment]
@hcho3 can you open an issue to change that? it is under folder of docs

**Comment by tqchen** [comment]
we can add wget script to https://github.com/dmlc/xgboost/blob/master/doc/conf.py to update the jquery @hcho3

**Comment by hcho3** [comment]
@tqchen I think I fixed the problem. See #2581. According to the [Sphinx documentation](http://www.sphinx-doc.org/en/stable/theming.html), any asset under the `static` directory gets included into the final build.

**Comment by hcho3** [comment]
@ysh329 The official documentation has now a working drop down menu.
