### ISSUE TITLE
gpu_acceleration, trying bosch.py.  Get: TypeError: __init__() got multiple values for keyword argument 'n_splits'

### ISSUE THREAD

**Issue by pseudotensor** [dmlc/xgboost#2102]
## Environment info
Operating System: Ubuntu 16.04 LTS with latest updates

Compiler: N/A

Package used (python/R/jvm/C++): pyhton 2.7, scikit-learn 0.18.1 from pip and also tried latest development version 0.19.dev0 (b5f2a387f5579857198803a4c86119451b1ff20e).

`xgboost` version used: latest development version (4a63f4ab43480adaaf13bde2485d5bfedd952520)

## Steps to reproduce

1. Run https://github.com/dmlc/xgboost/blob/master/demo/gpu_acceleration/bosch.py with data required as mentioned.

Result:

$ python bosch.py 
Traceback (most recent call last):
  File "bosch.py", line 32, in <module>
    cv = StratifiedKFold(y,n_splits=5)
TypeError: __init__() got multiple values for keyword argument 'n_splits'

## What have you tried?

1. Remove n_splits, then get error:

$ python bosch.py 
Traceback (most recent call last):
  File "bosch.py", line 32, in <module>
    cv = StratifiedKFold(y) #,n_splits=5)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/model_selection/_split.py", line 566, in __init__
    super(StratifiedKFold, self).__init__(n_splits, shuffle, random_state)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/model_selection/_split.py", line 274, in __init__
    % (n_splits, type(n_splits)))
ValueError: The number of folds must be of Integral type. [ 0.  0.  0. ...,  0.  0.  0.] of type <type 'numpy.ndarray'> was passed.

2. Found related issues: https://github.com/chrisclark/PythonForDataScience/issues/2 and https://github.com/dmlc/xgboost/issues/1729  but I already have latest scikit-learn.

3. Tried without any arguments in StratifiedKFold() and get:

$ python bosch.py 
Traceback (most recent call last):
  File "bosch.py", line 34, in <module>
    for i, (train, test) in enumerate(cv):
TypeError: 'StratifiedKFold' object is not iterable

So seems even though passes the cv = .. line that is a problem, still not correct with default arguments.

4. Seems different arguments taken: http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.StratifiedKFold.html , despite @adamist521 adamist521 statement: "cross_validation is included in model_selection module since sklearn …
2 contributors" .

That is, seems code is not correctly using StratifiedKFold inside sklearn.model_selection.  That is, one can have input "y" like quantity, one cannot.  etc.

5. All tests pass when running:  nosetests -v sklearn

6) Tried swapping:

#from sklearn.model_selection import StratifiedKFold
from sklearn.cross_validation import StratifiedKFold

but still same error:

$ python bosch.py 
/usr/local/lib/python2.7/dist-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
Traceback (most recent call last):
  File "bosch.py", line 33, in <module>
    cv = StratifiedKFold(y,n_splits=5)
TypeError: __init__() got an unexpected keyword argument 'n_splits'

7) What did "work" was to use:

#from sklearn.model_selection import StratifiedKFold
from sklearn.cross_validation import StratifiedKFold

and:

cv = StratifiedKFold(y) #,n_splits=5)

**Comment by vladfulgeanu** [comment]
The error on no. 6 is because `StratifiedKFold` from `sklearn.cross_validation` has the argument `n_splits` renamed to `n_folds`.
http://scikit-learn.org/stable/whats_new.html#version-0-18
