### ISSUE TITLE
Can I load my xgb(model) file in java from the model I saved in R?

### ISSUE THREAD

**Issue by foreverzhu** [dmlc/xgboost#2105]
## Environment info
Operating System: windows

Compiler:

Package used (python/R/jvm/C++): R

 Hi there 
   it's my first post.
  I am having a problem of understanding how the binary file worked.
I am currently working with several guys for building a realtime xgboost gbtree model  in R and trying to 
 use the result in java.

   here is the thing, I know that xgb.save can save the result as a binary text file.
since I am only guy know about R and know basically none in Java,
is there a way that my guys can just load or use the result I got from R .

 thanks

**Comment by khotilov** [comment]
Yes, just save it with `xgb.save` as a binary (not text) file, and then use `loadModel` method in Java.
