### ISSUE TITLE
github.com/dmlc/xgboost/tree/master/windows is NOT AVAILABLE

### ISSUE THREAD

**Issue by oxsem** [dmlc/xgboost#2107]
Hello,

I want to use VS in order to build the dll for windows, but http://github.com/dmlc/xgboost/tree/master/windows is not available. 
Is the link https://github.com/dmlc/dmlc-core/tree/c5c33124d2cc4a30ce8409d881c945c5bb04d06e/windows the right one for the .sln file? When using VS 2013 I get the error that projects in the solutions were not loaded correctly. Could you please guide me if I'm looking in wrong place? I'm using Windows 7 x64/Python 2.7 (WinPython-32bit interpreter).

Thank you,
Oksana

![vs2013](https://cloud.githubusercontent.com/assets/9165022/23917033/fbf6a496-08e5-11e7-9af6-67fdacdd078a.png)

**Comment by tqchen** [comment]
This is deprecated, please use follow the lastest isntruction in the doc
