### ISSUE TITLE
No way to free thread-local variables

### ISSUE THREAD

**Issue by Huffers** [dmlc/xgboost#2109]
XGboost allocates thread-local variables but doesn't provide any way to free their memory.

**This discourages the use of xgboost inside long running frameworks that launch a thread per request.**

I think the main problem is that the text dumps exported via the C API are kept in the thread-local store.

**Using xgboost v0.60**, I tested fitting and dumping a model with 10,000 nodes 51 times, one after another, each time in a separate thread, and found the process' working set increased by about 1.3 MB per iteration, with no end to the memory increase in sight.

I then tried adding a new C API method (XGBThreadLocalStoreFree) and calling that after each time I dumped the model, and I tried the same test again, and found that the memory usage stopped increasing after about 25 iterations.

See attached graph of my results.

![xgboostmemorygraph](https://cloud.githubusercontent.com/assets/26002523/23946434/50b03ce0-0972-11e7-978d-0b49fab774b8.PNG)

I'm not a C++ developer, so there's probably a better way of solving this than my "XGBThreadLocalStoreFree" method, but I'll open a pull request with this change in it for comments and review anyway.

**Comment by tqchen** [comment]
I think this is due to the problem of how we do thread local in DMLC. The old solution was mainly for portability for compilers which might not thread local object. We could try to patch it in a why that thread local actually get destructed when thread exit for compilers that supports it.

**Comment by tqchen** [comment]
We can move discussion to https://github.com/dmlc/dmlc-core/issues/230

**Comment by tqchen** [comment]
see if https://github.com/dmlc/xgboost/pull/2114 fixed the problem

**Comment by Huffers** [comment]
This doesn't seem to have made any difference - I think because xgboost has its own copy of thread_local.h in src\common. I copied just the "static thread_local T inst; return &inst;" lines from the dmlc-core\include\thread_local.h into the src\common\thread_local.h and that did fix the problem though.

So does the thread_local.h in src\common need to be updated to match the one in dmlc-core\include?

Thanks for looking into this so quickly by the way!

**Comment by tqchen** [comment]
oh i see, we should remove xgboost's own version of thread_local and switch to dmlc::ThreadLocalStore. Do you mind to submit a PR On this?

**Comment by Huffers** [comment]
I can have a go at that, but it might have to wait until Monday now...

**Comment by Huffers** [comment]
Pull request submitted!

**Comment by Huffers** [comment]
Closing as pull request has now been merged :-)
