### ISSUE TITLE
Request: Update Pypi distribution

### ISSUE THREAD

**Issue by ClimbsRocks** [dmlc/xgboost#2112]
Hi Team,

There's been a lot of awesome work on XGBoost over the past few months. Can we get an updated distribution on Pypi for the current codebase?

Thanks for all the improvements on this!

**Comment by phunterlau** [comment]
Planning for a precompiled version for mac and Linux users, by learning from the successful story of MXNet precompiled binary.

**Comment by ClimbsRocks** [comment]
@phunterlau awesome! Anywhere I can follow along? A quick search showed only https://github.com/dmlc/xgboost/issues/1263

**Comment by esdu** [comment]
:+1: that would be awesome.

**Comment by beckermr** [comment]
It looks like conda can distribute precompiled binaries for python on osx and linux at least. Follow along here https://github.com/conda-forge/staged-recipes/pull/2573.

**Comment by ClimbsRocks** [comment]
Bumping this to see if there's a place we can follow progress on a precompiled binary, or get a quick updated pip distribution in the meantime.

**Comment by beckermr** [comment]
The conda-forge package is posted and working if that will suit your needs

https://github.com/conda-forge/xgboost-feedstock

**Comment by ClimbsRocks** [comment]
Checking in again to see if there's any progress on an updated pypi distribution! There's been a ton of progress in the past half year. I'd love to see all of that available to everyone who uses pip to install this package.

**Comment by ClimbsRocks** [comment]
@beckermr thanks for the conda-forge version, but i'm trying to avoid using conda (it can get messy having two different package managers on a given machine which might have different versions of dependencies installed)

**Comment by abieler** [comment]
I second @ClimbsRocks. Updated pypi versions would be especially useful for people working on systems that are automatically deployed and install python dependencies via pip. (e.g. Heroku etc)
