### ISSUE TITLE
[jvm-package] xgboost4j-spark build failed on CentOS

### ISSUE THREAD

**Issue by WinterW** [dmlc/xgboost#2116]
I download latest code and compile, xgboost-jvm 、xgboost4j  is ok, but xgboost4j-spark failed.

## Environment info
Operating System:
CentOS release 6.8 (Final)
Linux localhost.localdomain 2.6.32-642.1.1.el6.x86_64 #1 SMP Tue May 31 21:57:07 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Compiler:
gcc version 4.8.2 20140120 (Red Hat 4.8.2-15) (GCC) 

Package used (python/R/jvm/C++):
jvm

`xgboost` version used:
d581a3d0e7fbc8e73dbeb6f81fdc1e101606737e

## Steps to reproduce
1. git clone https://github.com/dmlc/xgboost
2. cd xgboost/jvm-packages
3. mvn package
[build.txt](https://github.com/dmlc/xgboost/files/850275/build.txt)

**Comment by CodingCat** [comment]
@tqchen , is there any recent change in rabit? it seems to be related to rabit

**Comment by tqchen** [comment]
We have upgraded it to https://github.com/dmlc/rabit/commit/a764d45cfb438cc9f15cf47ce586c02ff2c65d0f but These are only dmlc header changes

**Comment by tqchen** [comment]
Maybe we can confirm if that is the cause of the problem

**Comment by CodingCat** [comment]
until so far, I haven't reproduced this problem in any of my systems....I will check it further tmr

**Comment by CodingCat** [comment]
would you please post the output when you run

python dmlc-core/tracker/dmlc_tracker/tracker.py --log-level=DEBUG --num-workers=(any number you like)

**Comment by WinterW** [comment]
I found the problem, my python version is 2.6.6 and have no argparse module installed. 
After update python to 2.7, the xgboost-spark can build success.
I have another question, the python of my spark cluster  is 2.6.6, and I hava no  privilege to change it.
Is the jar package still depend on  python when I run it on the spark cluster？ Do I have method to avoid it？

**Comment by geoHeil** [comment]
No there is an experimental tracker in scala.
WinterW <notifications@github.com> schrieb am Mo. 20. März 2017 um 05:19:

**Comment by hugstone** [comment]
@geoHeil , as @WinterW said "I have another question, the python of my spark cluster is 2.6.6, and I hava no privilege to change it.
Is the jar package still depend on python when I run it on the spark cluster？ Do I have method to avoid it？Can I pack argparse into jar direct？" , i am frustrated, for xgboost4j, is there any other way to package the argparse module to spark
