### ISSUE TITLE
AttributeError: 'Booster' object has no attribute 'handle'

### ISSUE THREAD

**Issue by DengMinghua** [dmlc/xgboost#2119]
## Environment info
Operating System: Windows 10 x64

Package used (python/R/jvm/C++): Python

`xgboost` version used: Latest (tried both pip and clone from Github)

python 3.5.2
"pip install xgboost"

## Steps to reproduce

my code is 

```
import pandas as pd
import xgboost as xgb
import operator
from matplotlib import pylab as plt

def convert(str):
	if (str == "high"):
		return 2.0
	if (str == "medium"):
		return 1.0
	return 0.0
def load():
    raw_data = pd.read_json("C:\\Users\\1\\Downloads\\train.json")
    raw_data["num_photos"] = raw_data["photos"].apply(len)
    raw_data["num_features"] = raw_data["features"].apply(len)
    features = ["bathrooms", "bedrooms", "price"]
    x_train = raw_data[features]
    y_train = list(map(convert,list(raw_data["interest_level"])))
    return x_train, y_train

x_train, y_train = load()
xgb_params = {
    "objective": "multi:softmax",
    "eval_metric": "rmse",
    "eta": 0.05,
    "max_depth": 6,
    "seed": 42,
    "silent": 0}
num_rounds = 100
dtrain = xgb.DMatrix(x_train, label=y_train)
gbdt = xgb.train(xgb_params, num_rounds)
importance = gbdt.get_fscore(fmap='xgb.fmap')
importance = sorted(importance.items(), key=operator.itemgetter(1))
df = pd.DataFrame(importance, columns=['feature', 'fscore'])
df['fscore'] = df['fscore'] / df['fscore'].sum()
plt.figure()
df.plot()
df.plot(kind='barh', x='feature', y='fscore', legend=False, figsize=(16, 10))
plt.title('XGBoost Feature Importance')
plt.xlabel('relative importance')

```
When xgb.train() is called, I got output

> Traceback (most recent call last):
>   File "C:\Users\1\Documents\Facebook AI Paper\kaggle\xgboost_test.py", line 31, in <module>
>     gbdt = xgb.train(xgb_params, num_rounds)
>   File "C:\Users\1\AppData\Local\Programs\Python\Python35\lib\site-packages\xgboost-0.6-py3.5.egg\xgboost\training.py", line 204, in train
>     xgb_model=xgb_model, callbacks=callbacks)
>   File "C:\Users\1\AppData\Local\Programs\Python\Python35\lib\site-packages\xgboost-0.6-py3.5.egg\xgboost\training.py", line 32, in _train_internal
>     bst = Booster(params, [dtrain] + [d[0] for d in evals])
>   File "C:\Users\1\AppData\Local\Programs\Python\Python35\lib\site-packages\xgboost-0.6-py3.5.egg\xgboost\core.py", line 657, in __init__
>     raise TypeError('invalid cache item: {}'.format(type(d).__name__))
> TypeError: invalid cache item: int
> Exception ignored in: <bound method Booster.__del__ of <xgboost.core.Booster object at 0x0000016A1D2B72E8>>
> Traceback (most recent call last):
>   File "C:\Users\1\AppData\Local\Programs\Python\Python35\lib\site-packages\xgboost-0.6-py3.5.egg\xgboost\core.py", line 669, in __del__
>     _LIB.XGBoosterFree(self.handle)
> AttributeError: 'Booster' object has no attribute 'handle'

## What have you tried?

1. I tried to compile the latest source code cloned from github,  and use the package I got from it. But the problem still existed.
2. I see a related issue https://github.com/dmlc/xgboost/issues/40, but it is out of date and dose not provide useful solution.

**Comment by oldmonk101** [comment]
Same issue here. I was trying LTR

**Comment by hannahlindsley** [comment]
Are you intending to not pass dtrain into the train function...?
