### ISSUE TITLE
Load xgboost model from plain text dump

### ISSUE THREAD

**Issue by cemhamami** [dmlc/xgboost#2127]
My issue is to find out whether there's functionality to load a dumped model from a plain text file.

For example, I'm training a model with gblinear and when I save the model with dump_model I get an output like this:
booster[0]:
bias:
-8.87178e-011
weight:
-0.0416415
-0.079841
...
Note that there'll always be one booster in the dump because I'm using gblinear.

My question is whether it's possible to also load the booster from a plain text file like this and continue training from there, or initialize a booster and set the initialization programmatically using the API. I've found save_dump and get_dump, but there's no load_dump, and if I try load_model on a dump file it fails with wrong file format error.

I cannot use the save_model to save to a binary file in the first place because the initial weights I have are from a completely different package.

**Comment by pommedeterresautee** [comment]
There is not such function yet.

**Comment by cemhamami** [comment]
Do you know of any workarounds for this?

**Comment by pommedeterresautee** [comment]
no :-(
