### ISSUE TITLE
cross_validation modeule reference

### ISSUE THREAD

**Issue by ghost** [dmlc/xgboost#2128]
When using Jupyter notebook I get the following message while loading xgboost. The devs are probably aware of that but just in case I thought I would report this.

/usr/lib/python3.5/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

**Comment by MaxPowerWasTaken** [comment]
What's the status of this issue? Current Pandas version is now 20.2

**Comment by donglixp** [comment]
the same warning

**Comment by gballardin** [comment]
Which version of xgboost are you using? I am having the same issue and trying to figure our if a newer version of xgboost could solve this issue.
