### ISSUE TITLE
Is XGBoost.trainWithRDD supported on Spark 1.6 / Scala 2.10 

### ISSUE THREAD

**Issue by myloginid** [dmlc/xgboost#2132]
## Environment info
Operating System: Build Mac OS Sierra / Test Centos 6.7
Compiler: mvn
Package used (python/R/jvm/C++): jvm
`xgboost` version used: f6f5003f79c90feb5dd01a8174cb6a6c61e6c4a7

## Steps to reproduce

1. Build xgboost4j-spark-0.7-jar-with-dependencies.jar and test on Spark 1.6, Scala 2.10

`scala> import ml.dmlc.xgboost4j.scala.{Booster, DMatrix}
import ml.dmlc.xgboost4j.scala.{Booster, DMatrix}

scala> import ml.dmlc.xgboost4j.scala.spark.{DataUtils, XGBoost}
import ml.dmlc.xgboost4j.scala.spark.{DataUtils, XGBoost}

scala>  import DataUtils._
import DataUtils._

scala> val trainRDD = trainData.map(lp => MLLabeledPoint(lp.label, new MLDenseVector(lp.features.toArray)))
scala.reflect.internal.Types$TypeError: bad symbolic reference. A signature in DataUtils.class refers to term linalg
in package org.apache.spark.ml which is not available.
It may be completely missing from the current classpath, or the version on
the classpath might be incompatible with the version used when compiling DataUtils.class.
That entry seems to have slain the compiler.  Shall I replay
your session? I can re-run each line except the last one.
[y/n]Replaying: import ml.dmlc.xgboost4j.scala.DMatrix
error:
     while compiling: <console>
        during phase: jvm
     library version: version 2.10.5
    compiler version: version 2.10.5
  reconstructed args: -classpath .: xgboost4j-spark-0.7-jar-with-dependencies.jar

  last tree to typer: Apply(constructor $read)
              symbol: constructor $read in class $read (flags: <method> <triedcooking>)
   symbol definition: def <init>(): $line307.$read
                 tpe: $line307.$read
       symbol owners: constructor $read -> class $read -> package $line307
      context owners: class iwC -> package $line307

== Enclosing template or block ==

Template( // val <local $iwC>: <notype>, tree.tpe=$line307.iwC
  "java.lang.Object", "scala.Serializable" // parents
  ValDef(
    private
    "_"
    <tpt>
    <empty>
  )
  // 5 statements
  ValDef( // private[this] val $iw: $line307.iwC
    private <local> <triedcooking>
    "$iw "
    <tpt> // tree.tpe=$line307.iwC
    <empty>
  )
  DefDef( // val $iw(): $line307.iwC
    <method> <stable> <accessor>
    "$iw"
    []
    List(Nil)
    <tpt> // tree.tpe=$line307.iwC
    $read$$iwC.this."$iw " // private[this] val $iw: $line307.iwC, tree.tpe=$line307.iwC
  )
  ValDef( // protected val $outer: $line307.$read
    protected <synthetic> <paramaccessor> <triedcooking>
    "$outer "
    <tpt> // tree.tpe=$line307.$read
    <empty>
  )
  DefDef( // val $outer(): $line307.$read
    <method> <synthetic> <stable> <expandedname>
    "$line307$$read$$iwC$$$outer"
    []
    List(Nil)
    <tpt> // tree.tpe=$line307.$read
    $read$$iwC.this."$outer " // protected val $outer: $line307.$read, tree.tpe=$line307.$read
  )
  DefDef( // def <init>(arg$outer: $line307.$read): $line307.iwC
    <method> <triedcooking>
    "<init>"
    []
    // 1 parameter list
    ValDef( // $outer: $line307.$read
      <param> <triedcooking>
      "$outer"
      <tpt> // tree.tpe=$line307.$read
      <empty>
    )
    <tpt> // tree.tpe=$line307.iwC
    Block( // tree.tpe=Unit
      // 3 statements
      If( // tree.tpe=Unit
        Apply( // final def eq(x$1: Object): Boolean in class Object, tree.tpe=Boolean
          "$outer"."eq" // final def eq(x$1: Object): Boolean in class Object, tree.tpe=(x$1: Object)Boolean
          null
        )
        Throw( // tree.tpe=Nothing
          Apply( // def <init>(): NullPointerException in class NullPointerException, tree.tpe=NullPointerException
            new NullPointerException."<init>" // def <init>(): NullPointerException in class NullPointerException, tree.tpe=()NullPointerException
            Nil
          )
        )
        Assign( // tree.tpe=Unit
          $read$$iwC.this."$outer " // protected val $outer: $line307.$read, tree.tpe=$line307.$read
          "$outer" // $outer: $line307.$read, tree.tpe=$line307.$read
        )
      )
      Apply( // def <init>(): Object in class Object, tree.tpe=Object
        $read$$iwC.super."<init>" // def <init>(): Object in class Object, tree.tpe=()Object
        Nil
      )
      Assign( // tree.tpe=Unit
        $read$$iwC.this."$iw " // private[this] val $iw: $line307.iwC, tree.tpe=$line307.iwC
        Apply( // def <init>(arg$outer: $line307.iwC): $line307.iwC, tree.tpe=$line307.iwC
          new $line307.iwC."<init>" // def <init>(arg$outer: $line307.iwC): $line307.iwC, tree.tpe=(arg$outer: $line307.iwC)$line307.iwC
          This("$iwC")class iwC extends Serializable in package $line307, tree.tpe=$line307.iwC
        )
      )
      ()
    )
  )
)

== Expanded type of tree ==

TypeRef(TypeSymbol(class $read extends Serializable))

uncaught exception during compilation: java.lang.AssertionError
Stopping spark context.
<console>:14: error: not found: value sc
              sc.stop()
              ^
Exception in thread "main" java.lang.AssertionError: assertion failed: Tried to find '$line307' in '/tmp/spark-f77b358d-1d4a-4080-ab6d-4120a7a4e760/repl-00b6ec29-fc23-46af-9b40-22a66f0136c0' but it is not a directory
    at scala.reflect.io.AbstractFile.subdirectoryNamed(AbstractFile.scala:254)
    at scala.tools.nsc.backend.jvm.BytecodeWriters$class.getFile(BytecodeWriters.scala:31)
    at scala.tools.nsc.backend.jvm.BytecodeWriters$class.scala$tools$nsc$backend$jvm$BytecodeWriters$$getFile(BytecodeWriters.scala:37)
    at scala.tools.nsc.backend.jvm.BytecodeWriters$ClassBytecodeWriter$class.writeClass(BytecodeWriters.scala:89)
    at scala.tools.nsc.backend.jvm.GenASM$AsmPhase$$anon$4.writeClass(GenASM.scala:67)
    at scala.tools.nsc.backend.jvm.GenASM$JBuilder.writeIfNotTooBig(GenASM.scala:459)
    at scala.tools.nsc.backend.jvm.GenASM$JPlainBuilder.genClass(GenASM.scala:1413)
    at scala.tools.nsc.backend.jvm.GenASM$AsmPhase.run(GenASM.scala:120)
    at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1583)
    at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1557)
    at scala.tools.nsc.Global$Run.compileSources(Global.scala:1553)
    at org.apache.spark.repl.SparkIMain.org$apache$spark$repl$SparkIMain$$compileSourcesKeepingRun(SparkIMain.scala:644)
    at org.apache.spark.repl.SparkIMain$ReadEvalPrint.compileAndSaveRun(SparkIMain.scala:1118)
    at org.apache.spark.repl.SparkIMain$ReadEvalPrint.compile(SparkIMain.scala:1074)
    at org.apache.spark.repl.SparkIMain$Request.compile$lzycompute(SparkIMain.scala:1279)
    at org.apache.spark.repl.SparkIMain$Request.compile(SparkIMain.scala:1274)
    at org.apache.spark.repl.SparkIMain.interpret(SparkIMain.scala:851)
    at org.apache.spark.repl.SparkIMain.interpret(SparkIMain.scala:800)
    at org.apache.spark.repl.SparkILoop.reallyInterpret$1(SparkILoop.scala:857)
    at org.apache.spark.repl.SparkILoop.interpretStartingWith(SparkILoop.scala:902)
    at org.apache.spark.repl.SparkILoop.command(SparkILoop.scala:814)
    at org.apache.spark.repl.SparkILoop$$anonfun$org$apache$spark$repl$SparkILoop$$replay$1.apply(SparkILoop.scala:693)
    at org.apache.spark.repl.SparkILoop$$anonfun$org$apache$spark$repl$SparkILoop$$replay$1.apply(SparkILoop.scala:691)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at org.apache.spark.repl.SparkILoop.org$apache$spark$repl$SparkILoop$$replay(SparkILoop.scala:691)
    at org.apache.spark.repl.SparkILoop.crashRecovery(SparkILoop.scala:635)
    at org.apache.spark.repl.SparkILoop.innerLoop$1(SparkILoop.scala:664)
    at org.apache.spark.repl.SparkILoop.org$apache$spark$repl$SparkILoop$$loop(SparkILoop.scala:670)
    at org.apache.spark.repl.SparkILoop$$anonfun$org$apache$spark$repl$SparkILoop$$process$1.apply$mcZ$sp(SparkILoop.scala:997)
    at org.apache.spark.repl.SparkILoop$$anonfun$org$apache$spark$repl$SparkILoop$$process$1.apply(SparkILoop.scala:945)
    at org.apache.spark.repl.SparkILoop$$anonfun$org$apache$spark$repl$SparkILoop$$process$1.apply(SparkILoop.scala:945)
    at scala.tools.nsc.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:135)
    at org.apache.spark.repl.SparkILoop.org$apache$spark$repl$SparkILoop$$process(SparkILoop.scala:945)
    at org.apache.spark.repl.SparkILoop.process(SparkILoop.scala:1064)
    at org.apache.spark.repl.Main$.main(Main.scala:31)
    at org.apache.spark.repl.Main.main(Main.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
    at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
    at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)`

## What have you tried?

1. Tried to compile for Spark 1.6, Scala 2.10 by changing pom jvm-packages and xgboost4j

`jvm-packages git:(master) ✗ mvn package -Dmaven.test.skip=true
[WARNING] Some problems were encountered while building the effective model for ml.dmlc:xgboost4j:jar:0.7
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] xgboost-jvm
[INFO] xgboost4j
[INFO] xgboost4j-spark
[INFO] xgboost4j-flink
[INFO] xgboost4j-example
[INFO] ------------------------------------------------------------------------
[INFO] Building xgboost-jvm 0.7
[INFO] ------------------------------------------------------------------------
[WARNING] sourceDirectory is not specified or does not exist 
[INFO] --- scala-maven-plugin:3.2.2:compile (default) @ xgboost-jvm ---
[WARNING]  Expected all dependencies to require Scala version: 2.10.1
[WARNING]  ml.dmlc:xgboost-jvm:0.7 requires scala version: 2.10.1
[WARNING]  org.scala-lang:scala-compiler:2.10.1 requires scala version: 2.10.1
[WARNING]  org.scala-lang:scala-reflect:2.10.1 requires scala version: 2.10.1
[WARNING]  ml.dmlc:xgboost-jvm:0.7 requires scala version: 2.10.1
[WARNING]  org.scalatest:scalatest_2.10:3.0.0 requires scala version: 2.10.6
[WARNING] Multiple versions of scala libraries detected!
[INFO] No sources to compile
[INFO]
[INFO] --- scala-maven-plugin:3.2.2:compile (scala-compile-first) @ xgboost-jvm ---
[WARNING]  Expected all dependencies to require Scala version: 2.10.1
[WARNING]  ml.dmlc:xgboost-jvm:0.7 requires scala version: 2.10.1
[WARNING]  org.scala-lang:scala-compiler:2.10.1 requires scala version: 2.10.1
[WARNING]  org.scala-lang:scala-reflect:2.10.1 requires scala version: 2.10.1
[WARNING]  ml.dmlc:xgboost-jvm:0.7 requires scala version: 2.10.1
[WARNING]  org.scalatest:scalatest_2.10:3.0.0 requires scala version: 2.10.6
[WARNING] Multiple versions of scala libraries detected!
[INFO] No sources to compile
[INFO]
[INFO] --- scala-maven-plugin:3.2.2:add-source (scala-compile-first) @ xgboost-jvm ---
[INFO] Add Source directory: 
[INFO] Add Test Source directory: 
[INFO]
[INFO] --- scala-maven-plugin:3.2.2:compile (compile) @ xgboost-jvm ---
[WARNING]  Expected all dependencies to require Scala version: 2.10.1
[WARNING]  ml.dmlc:xgboost-jvm:0.7 requires scala version: 2.10.1
[WARNING]  org.scala-lang:scala-compiler:2.10.1 requires scala version: 2.10.1
[WARNING]  org.scala-lang:scala-reflect:2.10.1 requires scala version: 2.10.1
[WARNING]  ml.dmlc:xgboost-jvm:0.7 requires scala version: 2.10.1
[WARNING]  org.scalatest:scalatest_2.10:3.0.0 requires scala version: 2.10.6
[WARNING] Multiple versions of scala libraries detected!
[INFO] No sources to compile
[INFO]
[INFO] --- scala-maven-plugin:3.2.2:testCompile (test-compile) @ xgboost-jvm ---
[INFO]
[INFO] --- scalatest-maven-plugin:1.0:test (test) @ xgboost-jvm ---
Discovery starting.
Discovery completed in 33 milliseconds.
Run starting. Expected test count is: 0
DiscoverySuite:
Run completed in 76 milliseconds.
[INFO] --- maven-assembly-plugin:2.6:single (make-assembly) @ xgboost-jvm ---
[INFO] Assemblies have been skipped per configuration of the skipAssembly parameter.
[INFO] ------------------------------------------------------------------------
[INFO] Building xgboost4j 0.7
[INFO] ------------------------------------------------------------------------
Downloading: https://repo1.maven.org/maven2/com/typesafe/akka/akka-testkit_2.10/2.3.11/akka-testkit_2.10-2.3.11.pom
Downloaded: https://repo1.maven.org/maven2/com/typesafe/akka/akka-testkit_2.10/2.3.11/akka-testkit_2.10-2.3.11.pom (3 KB at 0.2 KB/sec)
Downloading: https://repo1.maven.org/maven2/com/typesafe/akka/akka-testkit_2.10/2.3.11/akka-testkit_2.10-2.3.11.jar
Downloaded: https://repo1.maven.org/maven2/com/typesafe/akka/akka-testkit_2.10/2.3.11/akka-testkit_2.10-2.3.11.jar (249 KB at 185.2 KB/sec)
[INFO]
[INFO] --- scalastyle-maven-plugin:0.8.0:check (checkstyle) @ xgboost4j ---
Processed 13 file(s)
Found 0 errors
Found 0 warnings
Found 0 infos
Finished in 892 ms
[INFO]
[INFO] --- maven-checkstyle-plugin:2.17:check (checkstyle) @ xgboost4j ---
[INFO]
[INFO] --- exec-maven-plugin:1.6.0:exec (native) @ xgboost4j ---
build java wrapper
g++-6 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -O3 -funroll-loops -msse2 -fPIC -DDISABLE_OPENMP -I/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/include -I./java -I/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/include/darwin -shared -o jvm-packages/lib/libxgboost4j.so jvm-packages/xgboost4j/src/native/xgboost4j.cpp build/learner.o build/logging.o build/c_api/c_api.o build/c_api/c_api_error.o build/common/common.o build/common/hist_util.o build/data/data.o build/data/simple_csr_source.o build/data/simple_dmatrix.o build/data/sparse_page_dmatrix.o build/data/sparse_page_raw_format.o build/data/sparse_page_source.o build/data/sparse_page_writer.o build/gbm/gblinear.o build/gbm/gbm.o build/gbm/gbtree.o build/metric/elementwise_metric.o build/metric/metric.o build/metric/multiclass_metric.o build/metric/rank_metric.o build/objective/multiclass_obj.o build/objective/objective.o build/objective/rank_obj.o build/objective/regression_obj.o build/tree/tree_model.o build/tree/tree_updater.o build/tree/updater_colmaker.o build/tree/updater_fast_hist.o build/tree/updater_histmaker.o build/tree/updater_prune.o build/tree/updater_refresh.o build/tree/updater_skmaker.o build/tree/updater_sync.o dmlc-core/libdmlc.a rabit/lib/librabit_empty.a -pthread -lm
move native lib /Users/manishmaheshwari/Documents/manishm/projects/mycoderepo/xgboost/jvm-packages
complete
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ xgboost4j ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO]
[INFO] --- scala-maven-plugin:3.2.2:compile (default) @ xgboost4j ---
[WARNING]  Expected all dependencies to require Scala version: 2.10.1
[WARNING]  com.typesafe.akka:akka-actor_2.10:2.3.11 requires scala version: 2.10.4
[WARNING] Multiple versions of scala libraries detected!
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- scala-maven-plugin:3.2.2:compile (scala-compile-first) @ xgboost4j ---
[WARNING]  Expected all dependencies to require Scala version: 2.10.1
[WARNING]  com.typesafe.akka:akka-actor_2.10:2.3.11 requires scala version: 2.10.4
[WARNING] Multiple versions of scala libraries detected!
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- scala-maven-plugin:3.2.2:add-source (scala-compile-first) @ xgboost4j ---
[INFO] Add Source directory: /Users/manishmaheshwari/Documents/manishm/projects/mycoderepo/xgboost/jvm-packages/xgboost4j/src/main/scala
[INFO] Add Test Source directory: /Users/manishmaheshwari/Documents/manishm/projects/mycoderepo/xgboost/jvm-packages/xgboost4j/src/test/scala
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ xgboost4j ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- scala-maven-plugin:3.2.2:compile (compile) @ xgboost4j ---
[WARNING]  Expected all dependencies to require Scala version: 2.10.1
[WARNING]  com.typesafe.akka:akka-actor_2.10:2.3.11 requires scala version: 2.10.4
[WARNING] Multiple versions of scala libraries detected!
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ xgboost4j ---
[INFO] Not copying test resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ xgboost4j ---
[INFO] Not compiling test sources
[INFO]
[INFO] --- scala-maven-plugin:3.2.2:testCompile (test-compile) @ xgboost4j ---
[INFO]
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ xgboost4j ---
[INFO] Tests are skipped.
[INFO]
[INFO] --- scalatest-maven-plugin:1.0:test (test) @ xgboost4j ---
Discovery starting.
Discovery completed in 568 milliseconds.
Run starting. Expected test count is: 20
RabitTrackerConnectionHandlerTest:
RabitTrackerConnectionHandler
*** RUN ABORTED ***
  java.lang.NoSuchMethodError: scala.Predef$.$conforms()Lscala/Predef$$less$colon$less;
  at ml.dmlc.xgboost4j.scala.rabit.RabitTrackerConnectionHandlerTest$$anonfun$1.apply(RabitTrackerConnectionHandlerTest.scala:58)
  at ml.dmlc.xgboost4j.scala.rabit.RabitTrackerConnectionHandlerTest$$anonfun$1.apply(RabitTrackerConnectionHandlerTest.scala:52)
  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  at org.scalatest.FlatSpecLike$$anon$1.apply(FlatSpecLike.scala:1682)
  at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
  at ml.dmlc.xgboost4j.scala.rabit.RabitTrackerConnectionHandlerTest.withFixture(RabitTrackerConnectionHandlerTest.scala:44)
  at org.scalatest.FlatSpecLike$class.invokeWithFixture$1(FlatSpecLike.scala:1679)
  ...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] xgboost-jvm ........................................ SUCCESS [  2.611 s]
[INFO] xgboost4j .......................................... FAILURE [ 16.627 s]
[INFO] xgboost4j-spark .................................... SKIPPED
[INFO] xgboost4j-flink .................................... SKIPPED
[INFO] xgboost4j-example .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 19.354 s
[INFO] Finished at: 2017-03-22T20:57:08+08:00
[INFO] Final Memory: 28M/448M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.scalatest:scalatest-maven-plugin:1.0:test (test) on project xgboost4j: There are test failures -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command`

Any ideas?

PS - Apologies for the formatting. Selecting format as code does not fix the format somehow.

**Comment by CodingCat** [comment]
No, it does not support 1.6

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by priyakhokher** [comment]
Is it not supported at all now ? because I have spark 2.3.0 and scala 2.11, and my xgboost runs build is successful but when i try to reproduce this: https://docs.azuredatabricks.net/_static/notebooks/xgboost-simple-example.html
I get error: value trainWithRDD is not a member of object ml.dmlc.xgboost4j.scala.spark.XGBoost

I have googled a lot and did not find any solution

**Comment by hcho3** [comment]
There has been a revamping of interface for version 0.80. Use 0.72 to use trainWithRDD
