### ISSUE TITLE
Couldn't see xgboost4j.scala.spark  

### ISSUE THREAD

**Issue by lserlohn** [dmlc/xgboost#2137]
I am using XGBoost with Scala 11.6 and Spark 2.1.  I downloaded the repository and complied it following the instruction. I have no problem pass local test, but during spark [local] test, I saw the job launched and there was stages finished but no return, and spark job didn't exit. I am not sure if there is problem on it.

   Now turn to programming using XGBoost library. I added the xgboost4j-0.7-jar-with-dependencies.jar as private library to my Intellij. It was loaded, and I can use

import ml.dmlc.xgboost4j.scala._

but when I tried to the example code, the IDE couldn't resolve the train function:

val model = XGBoost.train(trainRDD, paramMap, numRound, nWorkers = 5, useExternalMemory = true)

I checked docutments, it seems that I should import from ml.dmlc.xgboost4j.scala.spark, but there is no spark subdomain in ml.dmlc.xgboost4j.scala, in my IDE.

under ml.dmlc.xgboost4j.scala, I can only see:
XGboost, Booster, DMatrix, EvalTrait, ObjectTrait, rabit

Is there something I missed, or my XgBoost Spark version haven't been built well?_

**Comment by RhariharanExpedia** [comment]
It's certainly worth re-cloning to be sure you have all the files and confirming that your compile was completely successful. 

I'm fairly new to this as well, but did you also publish the compiled binaries to a place where IntelliJ could pick them up?

**Comment by Frank111** [comment]
In my experience, xgboost-spark can't run in Windows OS, there is no .dll library in xgboost4j-0.7-jar-with-dependencies.jar

**Comment by superbobry** [comment]
@Frank111 it can if you build on Windows. There're also [unofficial prebuilt JARs](https://github.com/criteo-forks/xgboost-jars) for all three major OS.

@lserlohn can you try with the latest `master` and reopen the issue if the problem persists?
