### ISSUE TITLE
Specifying number of iterations to use in prediction - R

### ISSUE THREAD

**Issue by chibberto** [dmlc/xgboost#214]
Hi, I have a question very similar to https://github.com/dmlc/xgboost/issues/63 . Would it be feasible to enter a parameter like ntreelimit for prediction when using the gblinear booster as well as the gbtree booster?

**Comment by tqchen** [comment]
for gblinear, unfortunately it was not possible. This was because gblinear
re-uses the one linear weight to save memory.

Tianqi

**Comment by chibberto** [comment]
Ok, thanks for looking into this. Really like the package!
