### ISSUE TITLE
Supporting comments in input and output data

### ISSUE THREAD

**Issue by denkorzh** [dmlc/xgboost#2140]
That would be very nice to support comments (tags) in input data for CLI mode and make it possible to output comments and predictions separated by some delimiter as [Vowpal Wabbit does](https://github.com/JohnLangford/vowpal_wabbit/wiki/Tutorial#getting-predictions).

As [LIBSVM FAQ states](http://www.csie.ntu.edu.tw/~cjlin/libsvm/faq.html#f306), now this data format supports comments as follows:
`1 1:2 2:1 # your comments`

**Comment by pommedeterresautee** [comment]
Data are stored on disk in any format, it is up to you to load it in a Matrix and then apply Xgboost to it.
What format file are you referring to?

Kind regards,
Michaël

**Comment by pommedeterresautee** [comment]
On most supported language, storing the data on disk is up to the user (therefore there is no format).
CLI is the only exception as far as I know and I am not sure it is a priority right now.
Would you be interested in making a PR?
