### ISSUE TITLE
Multiple CUDA GPU support 

### ISSUE THREAD

**Issue by gjmulder** [dmlc/xgboost#2142]
Thanks muchly @RAMitchell for xgboost GPU support!

I have successfully got a GTX 1080 card running the bosch.py demo. The entire data set fits in the 8GB of RAM on the 1080:

[17:12:06] Allocated 6627/7988 MB on GeForce GTX 1080
Fold : [0]      eval-auc:0.711866, Boost Time 26.4033908844

I happen to have a second 1080 in the gaming PC I am using. Is there any way to run a second (independent of the first) xgboost CUDA instance? When I run a second concurrent instance it seems to also be running on the first GPU.

**Comment by RAMitchell** [comment]
Hi, not at this time but multi-GPU support is a feature I hope to implement soon.

**Comment by gjmulder** [comment]
If I can help test in any way, please ask...

**Comment by gjmulder** [comment]
Thanks for adding support.

**Comment by patelprateek** [comment]
any updates if multi gpu on single machine is supported , i do see n_gpu parameter , but doesn't seem to take any effect as i see still single gpu being utilized. Any pointers on how to enable this ?
