### ISSUE TITLE
[jvm-packages] How to see xgboost bestModel paragram

### ISSUE THREAD

**Issue by Frank111** [dmlc/xgboost#2144]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System:
redhat 6.5（with spark-2.1.0）
Compiler:

Package used (python/R/jvm/C++):
Package: jvm, xgboost4j-spark

`xgboost` version used:
lastest xgboost version used(download at 2017/3/16)

I want to see best model after cross validator fit，but there is no useful info. In my experience, i used decision tree model and i can get best model paragram , following my test code，res0 is decision tree result，and res2 is xgboost result

```
import org.apache.spark.ml.{Pipeline, PipelineModel}
import ml.dmlc.xgboost4j.scala.spark.{XGBoostClassificationModel, XGBoostEstimator}
import org.apache.spark.ml.evaluation._
import org.apache.spark.ml.tuning.{CrossValidator, ParamGridBuilder}
import org.apache.spark.ml.feature.VectorAssembler
import org.apache.spark.ml.regression.{DecisionTreeRegressionModel, DecisionTreeRegressor}
import scala.collection.mutable
import scala.util.Random


  // xgboost parameters
    def get_param(): mutable.HashMap[String, Any] = {
      val params = new mutable.HashMap[String, Any]()
      params += "eta" -> 0.1
      params += "max_depth" -> 4
      params += "min_child_weight" -> 4
      params += "num_round" -> 20
      params += "silent" -> 1
      params += "objective" -> "binary:logistic"
      params += "booster" -> "gbtree"
      params += "gamma" -> 0.0
      params += "colsample_bylevel" -> 1

      return params
    }

    val r = new Random(0)
    val training = spark.createDataFrame(
      Seq.fill(10000)(r.nextInt(2)).map(i => (i, i))
    ).toDF("feature", "label")

    val test = spark.createDataFrame(
      Seq.fill(10000)(r.nextInt(2)).map(i => (i, i))
    ).toDF("feature", "label")

    val assembler = new VectorAssembler()
      .setInputCols(Array("feature"))
      .setOutputCol("features")

    //    decision tree test
    val dtEstimator = new DecisionTreeRegressor()
      .setLabelCol("label")
      .setFeaturesCol("features")
      .setPredictionCol("prediction")

    val dtParamGrid = new ParamGridBuilder()
      .addGrid(dtEstimator.maxDepth, Array(5,20))
      .addGrid(dtEstimator.maxBins, Array(10,30))
      .build()


    val pipelineDT = new Pipeline()
      .setStages(Array(assembler, dtEstimator))

    val cvDT = new CrossValidator()
      .setEstimator(pipelineDT)
      .setEvaluator(new RegressionEvaluator()
        .setLabelCol("label")
        .setPredictionCol("prediction")
        .setMetricName("rmse")
      )
      .setEstimatorParamMaps(dtParamGrid)
      .setNumFolds(5)

    val dtCVModel = cvDT.fit(training)
    val dtBestModel = dtCVModel.bestModel.asInstanceOf[PipelineModel].stages(1).asInstanceOf[DecisionTreeRegressionModel]
    dtBestModel.extractParamMap()
    /*
res0: org.apache.spark.ml.param.ParamMap =
{
        dtr_374dff2d7188-cacheNodeIds: false,
        dtr_374dff2d7188-checkpointInterval: 10,
        dtr_374dff2d7188-featuresCol: features,
        dtr_374dff2d7188-impurity: variance,
        dtr_374dff2d7188-labelCol: label,
        dtr_374dff2d7188-maxBins: 10,
        dtr_374dff2d7188-maxDepth: 5,
        dtr_374dff2d7188-maxMemoryInMB: 256,
        dtr_374dff2d7188-minInfoGain: 0.0,
        dtr_374dff2d7188-minInstancesPerNode: 1,
        dtr_374dff2d7188-predictionCol: prediction,
        dtr_374dff2d7188-seed: 926680331
}
    */


    // xgboost test
    val xgbEstimator = new XGBoostEstimator(get_param().toMap)
      .setFeaturesCol("features")

    // grid
    val xgbParamGrid = new ParamGridBuilder()
      .addGrid(xgbEstimator.round, Array(10, 30))
      .addGrid(xgbEstimator.maxDepth, Array(5,8))
      .addGrid(xgbEstimator.minChildWeight, Array(0.5,1.0))
      .build()

    val pipelineXGB = new Pipeline()
      .setStages(Array(assembler, xgbEstimator))

    // cv
    val cvXGB = new CrossValidator()
      .setEstimator(pipelineXGB)
      .setEvaluator(new RegressionEvaluator()
        .setLabelCol("label")
        .setPredictionCol("prediction")
        .setMetricName("rmse")
      )
      .setEstimatorParamMaps(xgbParamGrid)
      .setNumFolds(5)

    val xgbCVModel = cvXGB.fit(training)
    val xgbBestModel = xgbCVModel.bestModel.asInstanceOf[PipelineModel].stages(1).asInstanceOf[XGBoostClassificationModel]
    xgbBestModel.extractParamMap()
    /*
res2: org.apache.spark.ml.param.ParamMap =
{
        XGBoostClassificationModel_f143165f6ace-featuresCol: features,
        XGBoostClassificationModel_f143165f6ace-labelCol: label,
        XGBoostClassificationModel_f143165f6ace-outputMargin: false,
        XGBoostClassificationModel_f143165f6ace-predictionCol: prediction,
        XGBoostClassificationModel_f143165f6ace-rawPredictionCol: probabilities,
        XGBoostClassificationModel_f143165f6ace-use_external_memory: false
}
    */
```

**Comment by Frank111** [comment]
@geoHeil do you know how to do it?

**Comment by geoHeil** [comment]
@frank111 I contributed the basic persistence implementation.

For that
https://github.com/dmlc/xgboost/blob/master/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostModel.scala#L312
sparks pipeline reader and writer were implemented.

I currently do not know why it doesn't work with the cross validator.
In case you were using sbt and not maven as a build system, please delete
sbt cache to really make sure you are using the latest xgboost with the
persistence merged.

As you will see above in this thread currently I am unable to debug this
issue due to not being able to compile xgboost.
When this is fixed I can have a look at your problem.

For me neither on arch Linux nor osx with neither python 3.6 nor 3.5.3 the
compilation works due to jni problems
https://gist.github.com/geoHeil/17ea7fa96f402f10a9a90517406330f6
Frank111 <notifications@github.com> schrieb am Sa. 25. März 2017 um 07:48:

**Comment by Frank111** [comment]
@geoHeil Thanks for your replay, i think this problem can repair with https://github.com/dmlc/xgboost/issues/2115

**Comment by geoHeil** [comment]
@Frank111 could you specify useful information? So far I believe xgboost will not print out any nice summary statistics you just should be able to obtain the model with the *best* parameters. Is this what you want?

**Comment by Frank111** [comment]
@geoHeil  I just want to know what is the best parameters after cross validation，you can see the best parameters of decisionTree  is following

```
        dtr_374dff2d7188-maxBins: 10,
        dtr_374dff2d7188-maxDepth: 5,
```

**Comment by geoHeil** [comment]
```
val cv = new CrossValidator()
    .setEstimator(simplPipe)
    .setEvaluator(new BinaryClassificationEvaluator()
      .setLabelCol("target")
      .setRawPredictionCol("prediction"))
    .setEstimatorParamMaps(simplePipeParams)
    .setNumFolds(numberOfFolds)
    .setSeed(gSeed.toLong)

val cvModel = cv.fit(train)
cvModel
    .getEstimatorParamMaps
    .zip(cvModel.avgMetrics)
    .foreach(println)

val pipelineModel: Option[PipelineModel] = cvModel.bestModel match {
    case p: PipelineModel => Some(p)
    case _ => None
}

val realModel: Option[XGBoostClassificationModel] = pipelineModel
    .flatMap {
      _.stages.collect { case t: XGBoostClassificationModel => t }
        .headOption
}
```

As `realModel` is a `XGBoostClassificationModel` you have access to all the regular parameters and should see which ones were the best ones.

**Comment by Frank111** [comment]
@geoHeil Can you give me your all the code, i still can not get best parameters. Thanks!

**Comment by geoHeil** [comment]
@Frank111 but when you hold `XGBoostClassificationModel` you can access all of it attributes, i.e. parameters. What would you like to see?

**Comment by Frank111** [comment]
@geoHeil Following grid, include parameter round maxDepth minChildWeight，there should be  eight combinations, in best model, i want to see which one is the best parameter combinations. i don't know how to see is，in DecisionTreeModel ，i can see is by  dtBestModel.extractParamMap().

```
    // grid
    val xgbParamGrid = new ParamGridBuilder()
      .addGrid(xgbEstimator.round, Array(10, 30))
      .addGrid(xgbEstimator.maxDepth, Array(5,8))
      .addGrid(xgbEstimator.minChildWeight, Array(0.5,1.0))
      .build()
```

**Comment by geoHeil** [comment]
You should be able to get hold of the booster https://github.com/dmlc/xgboost/blob/master/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassificationModel.scala#L35 and then https://github.com/dmlc/xgboost/blob/master/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/BoosterParams.scala should be available to you.

**Comment by Frank111** [comment]
@geoHeil Sorry, i am stupid, i still can not understand how to do this， can you write a test code, show best model parameters.Thank you！

**Comment by geoHeil** [comment]
Will https://github.com/dmlc/xgboost/issues/1763 help you? This helped me
originally.

Frank111 <notifications@github.com> schrieb am Di., 4. Apr. 2017 um
13:39 Uhr:

**Comment by Frank111** [comment]
@geoHeil Thank you, i think it will not help me. I can't find parameters {num_round max_depth min_child_weight ……}, can you please test it ?

```
scala> xgbCVModel.bestModel.asInstanceOf[PipelineModel].stages(1).asInstanceOf[XGBoostClassificationModel].params.foreach(println)
XGBoostClassificationModel_5991369c602a__featuresCol
XGBoostClassificationModel_5991369c602a__labelCol
XGBoostClassificationModel_5991369c602a__outputMargin
XGBoostClassificationModel_5991369c602a__predictionCol
XGBoostClassificationModel_5991369c602a__rawPredictionCol
XGBoostClassificationModel_5991369c602a__thresholds
XGBoostClassificationModel_5991369c602a__use_external_memory
```

**Comment by CodingCat** [comment]
num_round max_depth min_child_weight are params of estimators,

**Comment by CodingCat** [comment]
pseudo code:

```scala
bestModel.parent.asInstanceOf[XGBooostEstimator].params
```

would help

**Comment by Frank111** [comment]
@CodingCat According to your advice, i can finally get best model parameters of CV model ,i used
`cvModel.bestModel.parent.asInstanceOf[XGBoostEstimator].extractParamMap().toSeq.foreach(println)`
but when i used pipeline include XGBoostEstimator , it will be error , because  at this time   xgbCVModel.bestModel.parent is Pipeline Estimator, can you give me some advice ?
```
scala> xgbCVModel.bestModel.parent.asInstanceOf[XGBoostEstimator].asInstanceOf[XGBoostEstimator]
java.lang.ClassCastException: org.apache.spark.ml.Pipeline cannot be cast to ml.dmlc.xgboost4j.scala.spark.XGBoostEstimator

```

**Comment by geoHeil** [comment]
What if you don't use the parent? Is cvmodel a single estimator or a list
i.e pipeline with multiple steps. If yes you need to extract a single
element to be casted.
Frank111 <notifications@github.com> schrieb am Sa. 8. Apr. 2017 um 16:43:

**Comment by Frank111** [comment]
@geoHeil At first i used 
`xgbCVModel.bestModel.asInstanceOf[PipelineModel].stages(1).asInstanceOf[XGBoostClassificationModel].extractParamMap()`
and return it
```
res2: org.apache.spark.ml.param.ParamMap =
{
        XGBoostClassificationModel_f143165f6ace-featuresCol: features,
        XGBoostClassificationModel_f143165f6ace-labelCol: label,
        XGBoostClassificationModel_f143165f6ace-outputMargin: false,
        XGBoostClassificationModel_f143165f6ace-predictionCol: prediction,
        XGBoostClassificationModel_f143165f6ace-rawPredictionCol: probabilities,
        XGBoostClassificationModel_f143165f6ace-use_external_memory: false
}
```
because it is XGBoostClassificationModel, not a XGBoostEstimator ,and can not get params.

**Comment by CodingCat** [comment]
I do not think you can get params from PipelineModel

a potential solution is to access Estimator through stage() of PipelineModel

**Comment by Frank111** [comment]
@CodingCat  yes, i have tried, the type of following have to be XGBoostClassificationModel
`xgbCVModel.bestModel.asInstanceOf[PipelineModel].stages(1).asInstanceOf[XGBoostClassificationModel]`

**Comment by CodingCat** [comment]
so this approach works or not?

**Comment by Frank111** [comment]
It does not work ,there is no params in result.
```
res2: org.apache.spark.ml.param.ParamMap =
{
        XGBoostClassificationModel_f143165f6ace-featuresCol: features,
        XGBoostClassificationModel_f143165f6ace-labelCol: label,
        XGBoostClassificationModel_f143165f6ace-outputMargin: false,
        XGBoostClassificationModel_f143165f6ace-predictionCol: prediction,
        XGBoostClassificationModel_f143165f6ace-rawPredictionCol: probabilities,
        XGBoostClassificationModel_f143165f6ace-use_external_memory: false
}
```

**Comment by Frank111** [comment]
It works well by the same approach in spark classification model of ML library, for example decision tree , random forest and so on.

**Comment by CodingCat** [comment]
which works well, 

`xgbCVModel.bestModel.asInstanceOf[PipelineModel].stages(1).asInstanceOf[XGBoostClassificationModel]` 

or 

directly from pipelineModel?

**Comment by Frank111** [comment]
this
`xgbCVModel.bestModel.asInstanceOf[PipelineModel].stages(1).asInstanceOf[XGBoostClassificationModel]
`
following is my decision tree model params
```
    val dtBestModel = dtCVModel.bestModel.asInstanceOf[PipelineModel].stages(1).asInstanceOf[DecisionTreeRegressionModel]
    dtBestModel.extractParamMap()
```

and result , you can see params :  maxBins is 10,  maxDepth is 5

```
res0: org.apache.spark.ml.param.ParamMap =
{
        dtr_374dff2d7188-cacheNodeIds: false,
        dtr_374dff2d7188-checkpointInterval: 10,
        dtr_374dff2d7188-featuresCol: features,
        dtr_374dff2d7188-impurity: variance,
        dtr_374dff2d7188-labelCol: label,
        dtr_374dff2d7188-maxBins: 10,
        dtr_374dff2d7188-maxDepth: 5,
        dtr_374dff2d7188-maxMemoryInMB: 256,
        dtr_374dff2d7188-minInfoGain: 0.0,
        dtr_374dff2d7188-minInstancesPerNode: 1,
        dtr_374dff2d7188-predictionCol: prediction,
        dtr_374dff2d7188-seed: 926680331
}

```

**Comment by CodingCat** [comment]
yes, this is expected, because in the current implementation, we take all params as estimator params, in another word, you cannot get params from a Model object

**Comment by Frank111** [comment]
ok i am looking forward to repair this issue in future releases, and also another one https://github.com/dmlc/xgboost/issues/2115

**Comment by CodingCat** [comment]
did you set ML's model params explicitly? from Spark's impl, I cannot find any code which can propagate the params from estimator to model, (maybe I missed something since I only went through it)

**Comment by Frank111** [comment]
sorry ,i can't understand "did you set ML's model params explicitly?" , i also cannot find how to implement it in spark source code.

**Comment by CodingCat** [comment]
I mean, if you directly train a model through a pipeline, it will get the params in a model object (not the default value)?

I have this question because I didn't find anything which propagate the params from estimators to models in Spark ML source code

**Comment by Frank111** [comment]
I will give you my test code, due to the test data is very simple, so it is maybe the best params is the default value , but in my practical project code , i am sure ,it will show the best params.

```
import org.apache.spark.ml.{Pipeline, PipelineModel}
import org.apache.spark.ml.evaluation._
import org.apache.spark.ml.tuning.{CrossValidator, ParamGridBuilder}
import org.apache.spark.ml.feature.VectorAssembler
import org.apache.spark.ml.regression.{DecisionTreeRegressionModel, DecisionTreeRegressor}
import scala.collection.mutable
import scala.util.Random

   val r = new Random(0)
    val training = spark.createDataFrame(
      Seq.fill(10000)(r.nextInt(2)).map(i => (i, i))
    ).toDF("feature", "label")

    val test = spark.createDataFrame(
      Seq.fill(10000)(r.nextInt(2)).map(i => (i, i))
    ).toDF("feature", "label")

    val assembler = new VectorAssembler()
      .setInputCols(Array("feature"))
      .setOutputCol("features")

    //    decision tree test
    val dtEstimator = new DecisionTreeRegressor()
      .setLabelCol("label")
      .setFeaturesCol("features")
      .setPredictionCol("prediction")

    val dtParamGrid = new ParamGridBuilder()
      .addGrid(dtEstimator.maxDepth, Array(5,20))
      .addGrid(dtEstimator.maxBins, Array(10,30))
      .build()


    val pipelineDT = new Pipeline()
      .setStages(Array(assembler, dtEstimator))

    val cvDT = new CrossValidator()
      .setEstimator(pipelineDT)
      .setEvaluator(new RegressionEvaluator()
        .setLabelCol("label")
        .setPredictionCol("prediction")
        .setMetricName("rmse")
      )
      .setEstimatorParamMaps(dtParamGrid)
      .setNumFolds(5)

    val dtCVModel = cvDT.fit(training)
    val dtBestModel = dtCVModel.bestModel.asInstanceOf[PipelineModel].stages(1).asInstanceOf[DecisionTreeRegressionModel]
    dtBestModel.extractParamMap()
    /*
res0: org.apache.spark.ml.param.ParamMap =
{
        dtr_374dff2d7188-cacheNodeIds: false,
        dtr_374dff2d7188-checkpointInterval: 10,
        dtr_374dff2d7188-featuresCol: features,
        dtr_374dff2d7188-impurity: variance,
        dtr_374dff2d7188-labelCol: label,
        dtr_374dff2d7188-maxBins: 10,
        dtr_374dff2d7188-maxDepth: 5,
        dtr_374dff2d7188-maxMemoryInMB: 256,
        dtr_374dff2d7188-minInfoGain: 0.0,
        dtr_374dff2d7188-minInstancesPerNode: 1,
        dtr_374dff2d7188-predictionCol: prediction,
        dtr_374dff2d7188-seed: 926680331
}
    */
```

**Comment by CodingCat** [comment]
thanks, I will investigate it further, it seems that XGBoost4J-Spark is not working well when coming to pipelineModel and cross validation model

**Comment by CodingCat** [comment]
I just got a chance to look at this, why you want to do 

```scala
val pipelineDT = new Pipeline()
      .setStages(Array(assembler, dtEstimator))
```

where you repeatedly transform the same columns into vector?

**Comment by CodingCat** [comment]
ok, I will work on a PR to resolve this issue

**Comment by CodingCat** [comment]
https://github.com/dmlc/xgboost/pull/2214 should resolve the issue
