### ISSUE TITLE
save_model doesn't save feature names

### ISSUE THREAD

**Issue by laudney** [dmlc/xgboost#2151]
After I train a booster with a DMatrix with feature names, call save_model and later load_model, feature names are gone.

**Comment by KOLANICH** [comment]
@dmlc

**Comment by KOLANICH** [comment]
>From now on, the issue tracker is reserved for actionable items such as feature proposals discussion, roadmaps, and bug tracking.

@tqchen, I guess this is a feature proposal proposing saving feature names into model files too. For now I have to save them into a separate json file alongside with types and other metadata like hyperparams.

**Comment by hcho3** [comment]
It's quite tricky to find a place inside the binary format to save feature_names. I think we could use `leaf_vector_` field to store extra information.

**Comment by KOLANICH** [comment]
Or we can break the compatibility and roll out a new format with extendable structure. Or just use bson or msgpack.

**Comment by hcho3** [comment]
One idea I had is to serialize an extensible data format into a set of bytes and save it inside `leaf_vector_`.

**Comment by hcho3** [comment]
> Or we can break the compatibility

This is not a decision to be made lightly. Let me bring this up with other maintainers.

**Comment by tqchen** [comment]
Feature names are additional data that is not part of the core models. For data with a lot of features, saving feature name can cause quite a lot of space issues, so the current decision is not to serialize them. Addtional wrapping is welcomed(e.g. just pickle an object containing the model and the features)

**Comment by KOLANICH** [comment]
>Addtional wrapping is welcomed(e.g. just pickle an object containing the model and the features)

pickle is prohably the worst choice here. I use https://github.com/KOLANICH/AutoXGBoost.py .
