### ISSUE TITLE
'dmlc-core/libdmlc.a' failed when complie xgboost

### ISSUE THREAD

**Issue by anddelu** [dmlc/xgboost#2152]
I make the latest xgboost for anaconda python 2.7 in windows 10 and met the following error messages:
/usr/bin/sh: -c: line 0: syntax error near unexpected token `('
/usr/bin/sh: -c: line 0: `cd dmlc-core; C:/Program Files (x86)/mingw64/bin/make libdmlc.a config=C:/xgboost/config.mk; cd C:/xgboost'
Makefile:101: recipe for target 'dmlc-core/libdmlc.a' failed
make: *** [dmlc-core/libdmlc.a] Error 1
make: *** Waiting for unfinished jobs....

I once make xgboost successful. This time I want to update the latest xgboost so I used the same steps while I met the errors. I have try other ways to and still not solve it. The attached file is the full error message.

[errors.txt](https://github.com/dmlc/xgboost/files/871470/errors.txt)

**Comment by zhangyis16** [comment]
I am the same error with you

**Comment by PINGYANG-PY** [comment]
same here, on amzn1.x86_64

**Comment by khotilov** [comment]
Such issue was fixed recently #2619

@PINGYANG-PY you seem to have have Amazon linux, not windows, so it cannot really be the same issue. Use the latest source, and raise an issue if problem persists and you cannot find a solution.
