### ISSUE TITLE
Error when Installing on Windows 8.1 Python

### ISSUE THREAD

**Issue by wenbo5565** [dmlc/xgboost#2158]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System:
Windows 8.1
Compiler:
Visual Studio 2013
Package used (python/R/jvm/C++):
Python
`xgboost` version used:

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`)
2. Logs will be helpful (If logs are large, please upload as attachment).

If you are using python package, please provide

1. The python version and distribution
2. The command to install `xgboost` if you are not installing from source

If you are using R package, please provide

1. The R `sessionInfo()`
2. The command to install `xgboost` if you are not installing from source

## Steps to reproduce
Hi, I was trying to install xgboost by following steps at http://stackoverflow.com/questions/33749735/how-to-install-xgboost-package-in-python-windows-platform

I was stuck at step 3 when running cmake .. G"Visual Studio 12 2013 Win64". The error I get is 

```
CMake Error at CMakeLists.txt:76 (add_subdirectory):
  The source directory

    D:/xgboost_dir/dmlc-core

  does not contain a CMakeLists.txt file.
```

-- Configuring incomplete, errors occurred!

I was calling cmake from build directory.

Thank you.

## What have you tried?

1.
2.
3.

**Comment by wenbo5565** [comment]
This issue is resolved by running in the local cloned xgboost directory

```
git submodule init
git submodule update
```

**Comment by guoyuhaoaaa** [comment]
@wenbo5565 can you tell the reason why type "git submodule init" and "git submodule update" can solve this problem?? Thank you so much

**Comment by wenbo5565** [comment]
@guoyuhaoaaa  I am not sure the reason. Possibly I found this solution on google. You could try if you can find more details there.
