### ISSUE TITLE
How does the distributed version (xgboost4j-spark) work? 

### ISSUE THREAD

**Issue by JiadingGai** [dmlc/xgboost#2160]
IMHO, the distributed version should evenly distribute the work (#obs or #feats) across nodes of cores; Then, while calculating an optimal split, each node computes its own local optimal; Followed by a gather operation across nodes to return the global optimal split.  

However, the actual code seems partitioning the entire training dataset into _k_ equal sized chunks, where _k_ is the number of worker nodes. Then, each node trains its own xgbooster in a "pleasingly" parallel fashion (no communication among nodes). The training concludes with selecting the best xgbooster or, even simpler, the first xgbooster. Is that a correct way to summarize the distributed strategy? If so, would you say that the distributed version would never deliver better model performance than the OpenMP version.

**Comment by CodingCat** [comment]
No, you misunderstood the code

The workers will communicate through rabit

**Comment by mhmoudr** [comment]
@CodingCat, I am reviewing this part of the code, and want a clarification whether this communication that you have mentioned introduce a result of many (one for each partition) identical models or no? as I am not sure how the strategy of picking up the first boosted and throw away the rest will work.

In reference to this line:
https://github.com/dmlc/xgboost/blob/master/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala#L312

**Comment by CodingCat** [comment]
the models are synced via allreduce algorithm for each iteration, pick the first is just because RDD has no API called second(), third().....

**Comment by CodingCat** [comment]
and the communication is through native code, which is implemented in Rabit library being referred by XGBoost,

**Comment by mhmoudr** [comment]
In term of the RDD not having an API for second or third, basically given the limited number of boosters (should be the same number of workers) it is safe to collect the result into an array using `.collect()` then you will have full access to them by their indexes. 

PS: Just be aware that collect will move those boosters into the driver memory, while in RDD they are still on each executor(s) memory.

on the other hand still I have the question to be answered, which is "Are those boosters expected to be identical, so it is safe to pick up any? or are we expecting differences between them?" then what is the logic for selecting one vs merging them into one model?

**Comment by CodingCat** [comment]
they will be identical, so no need to merge, as all split points are based on a "SYNCED" histogram

**Comment by yvirin-apixio** [comment]
If they are identical, what is the point of DISTRIBUTED training?

**Comment by CodingCat** [comment]
isn't the question that if distributed training will lead to inconsistent model everywhere eventually, why we need distributed training?

**Comment by yvirin-apixio** [comment]
@CodingCat So early stopping is not implemented in the distributed version of training, correct?

**Comment by yvirin-apixio** [comment]
In general it seems like the implementation of the distributed algorithm for learning is hidden. Can someone point me to the code which actually is implementing the distributed synchronization of the histograms?
