### ISSUE TITLE
[Python] XGBoost hangs when run in parallel with pathos/multiprocessing

### ISSUE THREAD

**Issue by rhiever** [dmlc/xgboost#2163]
Over at the [TPOT project](https://github.com/rhiever/tpot), we've been using XGBoost as one of the estimators that TPOT considers using during its optimization step. We recently added multiprocessing support via [pathos](https://github.com/uqfoundation/pathos), which is built on top of Python's `multiprocessing` module.

Shortly thereafter, we started running into issues where XGBoost freezes when run in parallel with `pathos`. After some tweaking, we discovered that this issue only occurs when `nthread!=1` in XGBoost, and by default, `nthread=-1` in XGBoost.

For now, we've fixed this issue by forcing XGBoost to always use `nthread=1` in TPOT. However, we'd like to figure out why XGBoost hangs when run with `pathos` and `nthread!=1`. Any ideas or pointers?

**Comment by Data-drone** [comment]
has anyone had a look?

**Comment by khotilov** [comment]
If you are using `multiprocess`'s forking, that issue might be related to the known gcc problem of OpenMP within unix forks, .e.g
http://bisqwit.iki.fi/story/howto/openmp/#OpenmpAndFork
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=58378

**Comment by ogrisel** [comment]
[Loky](https://github.com/tomMoral/loky) was created to avoid this family of problems for Python 2.7+ and 3.3+. Under Python 3.4+ you can also use the `spawn` start method of multiprocessing.

**Comment by vatsan** [comment]
@ogrisel 
What's the license on Loky (couldn't find one of the GitHub repo)? The spawn method doesn't quite help as I believe XGBoost is initializing multi-processing and i am unable override it later. FWIW i am not even on Pathos, i am using plain-old multiprocessing that's included with Python 3.5 (I am on CentOS).

**Comment by vatsan** [comment]
FWIW, I was able to get past this issue following the suggestion in this thread (https://bugs.python.org/issue18999).

I initialized my Pool like so:

>>> from multiprocessing import pool, get_context
>>> forkserver = get_context('forkserver')
>>> p = forkserver.Pool()

Thanks @ogrisel for your original bugreport (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=58378) and the comment about 'forkserver' on that thread.
