### ISSUE TITLE
[jvm-packages][spark] How to catch JNI exceptions in spark XGBoost estimator

### ISSUE THREAD

**Issue by titicaca** [dmlc/xgboost#2166]
Spark executors are killed when errors occur in xgboost.so, even though the scala exceptions are catched in the scala part. 

Are there some ways to catch the JNI exceptions in spark XGBoost estimator?

**Comment by CodingCat** [comment]
no, see [here](http://stackoverflow.com/questions/4138168/what-happens-when-i-throw-a-c-exception-from-a-native-java-method)

**Comment by tqchen** [comment]
Actually we can do that. Depending on whether you want to solve the problem.

The exception in c++ is catched by C API, and will return a -1 error to the caller. As long as JNI can check for the error code, and throw XGGetLastError(), the exception can fall back to scala side. This is how we achieve exception handling in python

**Comment by tqchen** [comment]
see https://github.com/dmlc/xgboost/blob/master/python-package/xgboost/core.py#L127

**Comment by CodingCat** [comment]
it's different, as stated the link I posted, we can use return value to indicate something wrong happened, but we cannot know what are the problems which are only known by native code

**Comment by tqchen** [comment]
The native code tries to catch exceptions, translate the message to string and return error code. but indeed it is not as graceful as the trace within jvm

**Comment by CodingCat** [comment]
yeah, that's what I am saying, we are actually doing the same thing with python in JVM https://github.com/dmlc/xgboost/blob/72451457120ac9d59573cf7580ccd2ad178ef908/jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/JNIErrorHandle.java#L48,
