### ISSUE TITLE
Scipy csr vs. csc sparse matrix

### ISSUE THREAD

**Issue by abieler** [dmlc/xgboost#2170]
python 3.5.2 / xgb version 0.6 / 64bit linux

Executing the script from the link below generates errors when using scipy csr sparse
matrices but works with csc matrices. It produces errors of the form:
"expected f13379, f13378, f13377 in input data" for the predict function after training

To reproduce the bug download the script and data from the link below and execute it.
Setting the CSR flag to True or False switches between csr or csc matrices.

https://www.dropbox.com/s/raum1c3wa9m69lm/xgb_bug.zip?dl=1

The error depends on the specific train/test split, but fails fairly often in the csr case.
(Therefore the for loop in the code)

Best,
Andre

**Comment by khotilov** [comment]
This was fixed in #1606. Please check out the latest code from github. The current pypi package is too old.
