### ISSUE TITLE
Faster way to get predictions at every n tree

### ISSUE THREAD

**Issue by lcapalleja** [dmlc/xgboost#2175]
This is more of a feature request for the python package.

Right now we are able to get predictions at specific number of trees using xgboost.Booster.predict() parameter, ntree_limit. However, getting all of the predicts at every n from 1 to n_estimators is very slow and the best implementation I have found so far is in the REP package (where they even comment on how slow this method is).

https://github.com/yandex/rep/blob/master/rep/estimators/xgboost.py#L346

Sklearn already has a .staged_predict() that is orders of magnitude faster.

http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.GradientBoostingRegressor.html#sklearn.ensemble.GradientBoostingRegressor.staged_predict

There should be a way to get these results without having to call xgboost.Booster.predict() n_estimators times. Each tree should only be applied once and the resulting prediction appended to a list/array of previous step's predictions.

Having quicker access to this is useful for evaluating hyper-parameter performance since it gives a more detailed picture of training than just getting the 'best' n_estimators. For example graphs like the ones below may be produced to compare different model performances or performance for the same model over different time-slices.

![title](https://datarobot.wpengine.com/wp-content/uploads/2014/04/gbrt4-300x194.png)

![title](http://i.snag.gy/4Z16QF.jpg)

**Comment by ppallesen** [comment]
I think the problem you are posting can be solved with a recursive update of the prediction (pred_i=pred_{i-1}+predTree{i} ). The problem is also slowing down the watchlist https://github.com/dmlc/xgboost/issues/2211

**Comment by khotilov** [comment]
Unless I'm missing something, you can store evaluation results during training in `evals_result`: see [evals_result.py demo](https://github.com/dmlc/xgboost/blob/72451457120ac9d59573cf7580ccd2ad178ef908/demo/guide-python/evals_result.py)

**Comment by lcapalleja** [comment]
This does not let me predict and evaluate an arbitrary set of known X/Y. It only provides results for the training sets. To give some context, the reason I want finer control over what I am predicting/evaluating is to perform cross-validation across sets of factors and times.

**Comment by lcapalleja** [comment]
@tqchen, has this feature been implemented?

**Comment by tqchen** [comment]
Sorry, we are in a stage of triaging issues and this issue gets closed aggressively. The goal is to make sure that the issues get to attend to(which they are not at the moment due to the number of issues that are open

**Comment by hcho3** [comment]
Consolidating to #3439. A new issue should be opened if you or others decide to actively work on implementing this feature.

**Comment by joshbrowning2358** [comment]
Has this issue been resolved?  I'd be happy to take a look and submit a PR, but was curious why it was closed if it hasn't been implemented (and just wanted to make sure it hasn't been done before I start working on it).

**Comment by trivialfis** [comment]
We have some basic support for cached prediction using DMatrix, but not exposed through scikit-learn estimator interface.
