### ISSUE TITLE
[jvm-pacakges] xgboost4j monotone constraints help?

### ISSUE THREAD

**Issue by chappers** [dmlc/xgboost#2176]
Hi all, 

I'm intending on extending xgboost4j to accept monotone constraints. Just wondering if there is any pointers or suggestions for doing this?

For example in https://github.com/dmlc/xgboost/issues/1514 it mentions that: 
> Currently only supported exact greedy algorithm on multi-core. Not yet available in distributed version

What are the implications of this in xgboost4j?

**Comment by CodingCat** [comment]
when you file issues regarding xgboost4j, would you please add [jvm-pacakges] in the title so that I can quickly locate them?

**Comment by CodingCat** [comment]
if the params are available in native code, it should not have any barrier to use in xgboost4j

however, if you want to use in xgboost4j-spark, then it needs distributed version support in native code

**Comment by chappers** [comment]
Thanks, I'm looking at spark, so I guess I'll have to think carefully how/if I proceed
