### ISSUE TITLE
Help with Xgboost

### ISSUE THREAD

**Issue by 634671436** [dmlc/xgboost#2177]
Win10 + Mingw64 +Git bash

when I first try to put the following on git bash:

cd dmlc-core
make -j4
cd ../rabit
make lib/librabit_empty.a -j4
cd ..
cp make/mingw64.mk config.mk
make -j4

but when i input:
cd dmlc-core
make -j4

something wrong accure:

e>::Next() [with DType = dmlc::data::RowBlockContainer<unsigned int>]'
src/data.cc:160:1:   required from here
include/dmlc/threadediter.h:387:33: warning: unused variable 'lock' [-Wunused-variable]
make: *** [Makefile:83: data.o] Error 1

**Comment by dPacc** [comment]
Im facing the same problem as well
