### ISSUE TITLE
feature importance v2

### ISSUE THREAD

**Issue by asimkievich** [dmlc/xgboost#218]
hi there, 

there is an issue on feature importance, and you mention that in python you can dump a text to see which features are used.

Could you please be more explicit and write the statement to dump the text (in python)?

Reason: I engineered tons of features (more than 4000) but I am sure that many are useless. I would like to keep the 500 or so more improtant, to speed up execution and iteration - and also to use in other models.

Sklearn has such a feature but it takes forever. thanks!

**Comment by tqchen** [comment]
python interface have a way to get importance 

https://github.com/dmlc/xgboost/blob/master/wrapper/xgboost.py#L512

**Comment by asimkievich** [comment]
As always, thanks so much Tianqi. If you ever decide to commercialize this
product, count on me about positive word of mouth.

trying it out now, feel free to close the issue - hope I am implementing
correctly. I copied your function and added:

print(get_fscore()) at the end of the script.

*Alejandro Simkievich*
CEO | *Statec *
M: +55 11 99634 6673
http://www.statec.com.br
skype: asimkievich
[image: Follow us on Linkedin]
<http://t.signauxdix.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs7fsZxlN8qC6PYfmKYvW2zGrQM56dTb1dvWBqC02?t=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2F3658897%3Ftrk%3Dprof-exp-company-name&si=5363976030388224&pi=027327f0-7f8d-41a4-8f63-03dff23ad080>
Let's
connect!
<http://t.signauxdix.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs7fsZxlN8qC6PYfmKYvW2zGrQM56dTb1dvWBqC02?t=https%3A%2F%2Ftwitter.com%2FSTAtecBrasil&si=5363976030388224&pi=027327f0-7f8d-41a4-8f63-03dff23ad080>
Follow
us!  Like us!

**Comment by tqchen** [comment]
thanks.

**Comment by tqchen** [comment]
xgboost will remain as a good open source tool for big data analytics and we hope to build things better for even larger scale problems in distributed setting.  We do have friend companies such as Dato that takes xgboost and incorporate it as a more user friendly data processing pipeline.

**Comment by asimkievich** [comment]
Thanks Tianqi. I met Carlos Guestrin at Strata in San Jose and have
remained in touch ever since. My goal is to build vertical-specific
applications in the space ( e.g for retail, etc) particularly involving nlp
and computer vision.
