### ISSUE TITLE
getting LocalFileSystem: fail to open "xgboost.model"

### ISSUE THREAD

**Issue by Bryant-zhu** [dmlc/xgboost#2182]
Hi there 
   I was doing a project using R to building xgboost model 
 it's all goes well in my Windows local laptop in R.

 after I put my code in linux server  and install basically all the packages I need,
  I keep getting the error that  when I running this code 

xgboost(data = dtrain,max.depth = 6, eta = 0.5, nthread = 6, nround = 50,objective = "reg:linear",verbose = 0)

> Error in xgb.save(env$bst, sprintf(save_name, env$iteration)) : 
>   [10:46:20] amalgamation/../dmlc-core/src/io/local_filesys.cc:154: Check failed: allow_null  LocalFileSystem: fail to open "xgboost.model"

it is quite rare which I could not find any info that is helpful.

**Comment by khotilov** [comment]
Thanks for reporting! 
`save_period = 0` setting is currently set as default in `xgboost()`, which leads to an attempt to save a model at the end of a run. And when you have no write permission for a directory, you would get this error. The default setting has to be changed to `save_period = NULL`, to be the same as in `xgb.train()`. I'll do that later. Meanwhile, you can explicitly set it to NULL as a temporary workaround.

**Comment by alexWhitworth** [comment]
This change does not appear to be pushed to CRAN despite both versions being `0.6-4`. It appears that [1ad168e](https://github.com/khotilov/xgboost/commit/1ad168efcca668713c1468f37de75fc52cae539b) did not update the package version and the update was not pushed to CRAN:

Dev-version of [`xgboost()`](https://github.com/khotilov/xgboost/blob/master/R-package/R/xgboost.R) --> `function(... save_period = NULL, ...)`
CRAN version [`xgboost()`](https://github.com/cran/xgboost/blob/master/R/xgboost.R) (via Github mirror) --> `function(... save_period = 0, ...)`

**Comment by hetong007** [comment]
There will be a new version to CRAN recently. Please follow https://github.com/dmlc/xgboost/issues/2960.

**Comment by ldesousa** [comment]
I am getting this exception when I call `xgb.save` with version 0.71.1. All working directories are owned by my user. I did not have this issue with version 0.6.4.1. Any clues on how to get more useful information?

**Comment by dselivanov** [comment]
same here
