### ISSUE TITLE
[jvm-packages] How can a C++ program use a xgboost model trained by xgboost4j. 

### ISSUE THREAD

**Issue by algorithmdog** [dmlc/xgboost#2185]
I wanted to train a xgboost model by xgboost4j-spark, and use the model for prediction in a C++ server program. But it failed due to the below code in the red circle.

![error](https://cloud.githubusercontent.com/assets/2755653/24908721/b0b3a726-1ef3-11e7-8666-cc8d9553a7eb.png)

The code is from https://github.com/dmlc/xgboost/blob/6f16f0ef5829965ba420ef6937617600d286820a/src/gbm/gbm.cc

**Comment by CodingCat** [comment]
how you saved the model?

**Comment by jichao6758** [comment]
I have the same problem，I used func saveModelAsHadoopFile

**Comment by algorithmdog** [comment]
@CodingCat thank you for your response. I saved my model using the following code

 if (save_path != ""){
      model.saveModelAsHadoopFile(save_path)
 }

**Comment by CodingCat** [comment]
saveModelAsHadoopFile can only be consumed by xgboost4j-spark, if you want to cross-languages consuming, you have to call https://github.com/dmlc/xgboost/blob/72451457120ac9d59573cf7580ccd2ad178ef908/jvm-packages/xgboost4j/src/main/scala/ml/dmlc/xgboost4j/scala/Booster.scala#L149

**Comment by zmingshi** [comment]
I am just faced the same problem and it works now.
1. First, I suggest that you could compile the xgboost as an dynamic library and use it online in your c++ server, which is what we do now.  Including the source code from xgboost in your server may be difficult. 

2. Train model on Spark has no problem.  Just notice Spark does the internal conversion, and does not accept formats that are 0-based.  This is very important which can cause feature index mismatch.

source code of loadLibSVMFile in Spark is as bellow:
``` scala
def loadLibSVMFile(
      sc: SparkContext,
      path: String,
      numFeatures: Int,
      minPartitions: Int): RDD[LabeledPoint] = {
    val parsed = sc.textFile(path, minPartitions)
      .map(_.trim)
      .filter(line => !(line.isEmpty || line.startsWith("#")))
      .map { line =>
        val items = line.split(' ')
        val label = items.head.toDouble
        val (indices, values) = items.tail.filter(_.nonEmpty).map { item =>
          val indexAndValue = item.split(':')
          val index = indexAndValue(0).toInt - 1  // Convert 1-based indices to 0-based.
          val value = indexAndValue(1).toDouble
          (index, value)
        }.unzip
        .......
```

**Comment by algorithmdog** [comment]
@CodingCat thank you. I will have a try.

**Comment by algorithmdog** [comment]
It works. Thank @CodingCat and @zmingshi
