### ISSUE TITLE
[Help] param.h  line 470, NeedReplace function

### ISSUE THREAD

**Issue by davutpolat** [dmlc/xgboost#2188]
body of  method is as follow , 

  inline bool NeedReplace(bst_float new_loss_chg, unsigned split_index) const {
    if (this->split_index() <= split_index) {
      return new_loss_chg > this->loss_chg;
    } else {
      return !(this->loss_chg > new_loss_chg);
    }
  }

cant we just write this as follow ?

return new_loss_chg > this->loss_chg

it only matters  when ((this->split_index() > split_index) && (this->loss_chg == new_loss_chg))
in this case, what matters ?  as far as i understand, this method is used for updating and node entry
 if suggested feature  has better loss change.  why feature id matters when loss change is equal to current node's loss change?

**Comment by davutpolat** [comment]
@tqchen Could you help me on this issue?

**Comment by tqchen** [comment]
This is mainly for breaking the tie, when there are two features with identical loss change
