### ISSUE TITLE
[Help] unsinged split index variable in SplitEntry struct

### ISSUE THREAD

**Issue by davutpolat** [dmlc/xgboost#2189]
in param.h  line 451

struct SplitEntry {
  /*! \brief loss change after split this node */
  bst_float loss_chg;
  /*! \brief split index */
  **unsigned sindex;**
  /*! \brief split value */
  bst_float split_value;
  /*! \brief constructor */
  SplitEntry() : loss_chg(0.0f), sindex(0), split_value(0.0f) {}
...

we got sindex as unsigned variable, and for comparing it with col_batch index (which is signed integer in nature) from updater classes, we need call split_index()  method at line  519. 

 inline unsigned split_index() const { return sindex & ((1U << 31) - 1U); }

in this method we need to make most significant bit 0 for safe comparisons. Why  dont we just make sindex signed integer, is there any reason we keep it unsigned.

I am experimenting some changes  on xgboost, and encountered this and need to know why it is unsigned. 

Regards,
Davut

**Comment by davutpolat** [comment]
@tqchen Could you help me on this issue?

**Comment by tqchen** [comment]
There is no specific reason why it is unsigned
