### ISSUE TITLE
Sklearn_examples problem

### ISSUE THREAD

**Issue by ManSoSec** [dmlc/xgboost#219]
Hello xgboost developers,

When I run the iris example proposed here : 
https://github.com/dmlc/xgboost/blob/master/demo/guide-python/sklearn_examples.py

I receive the following error :
xgb_model = xgb.XGBClassifier().fit(X[train_index],y[train_index])
  File "../xgboost-master/wrapper/xgboost.py", line 795, in __init__
    super().__init__(max_depth, learning_rate, n_estimators, silent, objective="binary:logistic")
TypeError: super() takes at least 1 argument (0 given)

Would you please help me ?

Thanks

**Comment by tqchen** [comment]
The fix is now merged. Please try again

**Comment by ManSoSec** [comment]
Thanks. It's okay now.
