### ISSUE TITLE
[python] Different scores are outputted from different methods of DMatrix loading testing data, but testing data is the same.

### ISSUE THREAD

**Issue by heavendai** [dmlc/xgboost#2193]
I have trained a  model (gbtree booster, binary:logistic) by XGBoost, and then I wanted predict all unsupervised samples one by one. But I found it that I got different scores from batching predict mathod.  The codes are as follow:
```
def predict_v1(model_file, pred_file):
    bst = xgb.Booster(model_file=model_file)
    dtest = xgb.DMatrix(pred_file)#, missing=0)
    res = bst.predict(dtest)
    sys.stdout.write("\n".join([str(x) for x in res]))
    
def predict_v2(model_file, pred_file):
    bst = xgb.Booster(model_file=model_file)
    lines = open(pred_file, 'r').readlines()
    ndim = 100
    for line in lines: 
        Id, fea_vec = line.strip().split('\t')
        narray = libsvm2nparray(fea_vec, ndim) 
        dtest = xgb.DMatrix(narray)#, missing=0)
        res = bst.predict(dtest)#, ntree_limit=0)
        sys.stdout..write("%s\t%s\n" % (udwid, res[0]))

def libsvm2nparray(fea_str, ndim): 
    _dict = {x:0.0 for x in range(ndim)} 
    terms = fea_str.split(' ')
    for term in terms:
        ind, val = term.split(':')
        if int(ind) in _dict: 
            _dict[int(ind)] = float(val)
    return np.array([_dict.values()])
```
Btw, I got a different result from all above methods while I parsed the feature vectors by sklearn.datasets.load_svmlight_file and scipy.sparse.csc_matrix, through I debug missing value and ntree_limit param.

could you give me a hand? @tqchen Thanks a lot.

`xgboost` version used:
the last version.

**Comment by tqchen** [comment]
You will need to check if the data loaded by load_svmlight differs from the DMatrix version. Normal libsvm format assumes first index starts from 1, and some loader might substract indices by one while xgboost don't

**Comment by heavendai** [comment]
Hi, @tqchen . Thanks for your reply.
I have already tried to different first index starts (from 0 and 1) for the testing data. I still got different results by predict_v1 and predict_v2 functions for the same testing data and the same model.

**Comment by khotilov** [comment]
@heavendai : from xgboost's point of view, sparse data is not equivalent to dense data with zeros in place of sparse elements. Sparse elements are treated by xgboost as if they were "missing" values.

**Comment by heavendai** [comment]
@khotilov : thanks for your reply. I agree to missing value different from zeros in sparse elements. I have tried to replace -1 (0) to missing value and the results are all different from load file method. Could you tell me how to deal with the sparse matrix line by line for missing value like load file method? Thx again.
