### ISSUE TITLE
Variable Importance Question

### ISSUE THREAD

**Issue by dbfowler** [dmlc/xgboost#2194]
I am running the latest version of XGBoost in R and upon printing the xgb.importance() for my final model, I found only 178 of my 198 original columns had reported Feature/Gain/Cover/Frequency. 

After looking into the source code for xgb.importance I learned that xgb.dump extracts all the split decisions from the model then summarises accordingly. 

I am currently working on the theory that the omission of these 20 variables indicates that they were *NEVER* used for a split decision in the model and hence have no reportable importances. Is there any other reason this could happen or some way to look into the issue further? I am unfortunately unable to share my data or code due to privacy issues so any conjecture would be much appreciated!

**Comment by khotilov** [comment]
Your theory is correct.
