### ISSUE TITLE
how to get the relation between feature variable and prediction variable in R package

### ISSUE THREAD

**Issue by luoruisichuan** [dmlc/xgboost#2196]
In xgboost R package, we can get the importance with the following code
"importance_matrix <- xgb.importance(names, model = xgb)",
I am currently working to get the relation between feature variable and prediction variable,
for instance, with the increasing of feature variable a, the prediction variable increse, too,  and so on.
How to get the relation between feature variable and prediction variable  in R package?
thanks for your help very much!
@khotilov 

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System:

Compiler:

Package used (python/R/jvm/C++):

`xgboost` version used:

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`)
2. Logs will be helpful (If logs are large, please upload as attachment).

If you are using python package, please provide

1. The python version and distribution
2. The command to install `xgboost` if you are not installing from source

If you are using R package, please provide

1. The R `sessionInfo()`
2. The command to install `xgboost` if you are not installing from source

## Steps to reproduce

1.
2.
3.

## What have you tried?

1.
2.
3.

**Comment by pommedeterresautee** [comment]
This feature is not yet implemented directly in the package. In R you can find several packages to do it.
