### ISSUE TITLE
Xgboost installing problem.

### ISSUE THREAD

**Issue by UWGabrielXu** [dmlc/xgboost#2200]
`make clean_all && make -j4`

```
dmlc-core/include/dmlc/thread_local.h:40:12: error: thread-local storage is not supported for the current target
    static thread_local T inst;
           ^
1 error generated.
make: *** [build/c_api/c_a

```

Any idea about this error?

**Comment by daronjp** [comment]
I'm running into the same error.

**Comment by daronjp** [comment]
@JerryGuangXu I found that `brew install gcc5` fixed it for me.

**Comment by denadai2** [comment]
I suggest you: https://www.ibm.com/developerworks/community/blogs/jfp/entry/Installing_XGBoost_on_Mac_OSX?lang=en

**Comment by zigeuner** [comment]
I had to explicitly use the gcc-7 compiler after installing it with brew install --upgrade gcc.  

Excerpt from manually altered config.mk:
# choice of compiler, by default use system preference.
export CC = gcc-7
export CXX = g++-7

The system /usr/bin/gcc appears to use the Apple clang compiler, which doesn't work for this application

**Comment by liangti** [comment]
I just face exactly the same issue and now successfully install xgboost. What I did is git the xgboost in the root (~/) instead of any other path, then make -j8 not -j4, and this issue disappear... Now sure whether this is the reason but you just can try it out.
