### ISSUE TITLE
[Help] - Advice on how to modify code for research

### ISSUE THREAD

**Issue by dancaspi** [dmlc/xgboost#2201]
Hey,
I am researching methods of improving tree based predictions. I have various schemes I would like try for fitting leaf scores. What would be the recommended approach to modify the source code such that I could **use the generated trees** but modify the eventual leaf scores? My preference would be to use only R/Python ,  even at the cost of speed (as this is mainly theoretical as this point). If this is not possible, I could also modify the underlying C/C++ code, but prefer to test new hypothesis without recompiling the source code.

thanks,
Dan

**Comment by tqchen** [comment]
You can use the predict leaf id to get the leaf indices, and refit the leaf indices in what ever way you like
