### ISSUE TITLE
[jvm-packages][question] How to get leafs num of tree?

### ISSUE THREAD

**Issue by WinterW** [dmlc/xgboost#2207]
https://github.com/tqchen/xgboost/blob/master/R-package/demo/predict_leaf_indices.R#L31
According to the link, max is not the real max.
when I get a gbdt model and a LR model,  I can  only use it to predict an known dataset (can't be used for a new data), because the new data's leaf index may be greater than the dataset's max index.
**So, I want get the true leafs number of tree.**
**Another question, why the max is not the real max?** 
A dataset for train to get a model, ervery leafs should have a data at least.
In my opinion, the max index of the dataset shoud be the real leaf num of tree.
But after test, I dump the model, the max index of the dataset is less than node num.
**the predictleaf api return a index which is node's index of tree, I want get leaf's index. how can I get it?**

**Comment by CodingCat** [comment]
it's a jvm problem?

**Comment by WinterW** [comment]
I'm using xgboost4j-spark, How to get leafs num of tree?
In xgboost4j-spark, the predict result's max index is not the tree's max index which I can't understand.
The R-package code is just an example, because I didn't find similar code in  xgboost4j-spark.
This is not a probelm, just a question. expect you help.

**Comment by khotilov** [comment]
@WinterW this part of the predict_leaf_indices.R demo is odd: it uses the number of columns of the built-in `trees` dataset as a maximum loop index - which seems like a bug - but that comment seems to state as if it was done on-purpose... I would suggest to take a look at the examples of the `xgb.create.features` function, which @pommedeterresautee has added after committing that part of the demo. And keep in mind that this is just one of possible examples of using leaf predictions. How you would decide to use them and to ensure that your process would properly handle new data is mostly in your court.

**Comment by CodingCat** [comment]
@tqchen
