### ISSUE TITLE
Sklearn.grid_search error in python

### ISSUE THREAD

**Issue by TomekTarczynski** [dmlc/xgboost#221]
Hi,

I was trying to use XGBClassifier from wrapper together with sklearn.grid_search and I've encountered few problems:
- Parameter n_estimators can't be used in grid_search. As far as I understand the code it is because set_params changes value of n_estimators instead of n_rounds. Change of the name of field n_rounds into n_estimators fixes the problem. The other solution is to overload set_params method
- Grid_search at some point tries to create XGBClassifier object using params obtained using get_params method. Get_params method returns dictionary in which there is key 'objective'. Init method of XGBClassifier doesn't support such parameters and due to that error occurs. I've fixed that by adding objective parameter to init (it doesn't have to be used).

**Comment by tqchen** [comment]
Thanks, I think it is reasonable to overload the set_params method. Can you submit a PR on this?
