### ISSUE TITLE
Train model in R and problem of using it in C

### ISSUE THREAD

**Issue by fimmugit** [dmlc/xgboost#2210]
I am having problem of using a model trained in R to do prediction in C. When tracing in debug mode all the way to the end of the prediction (see C code below), the 'out_len' variable seemed to get garbage value and the 'f' variable was unreadable .

So I am not sure if the model I saved in R is in a compatible/readable format in C. and why the two variables were not assigned the correct values.

## Environment info
Operating System:
Windows 8.1

Compiler:

Package used (python/R/jvm/C++):
R3.3.3

`xgboost` version used:
0.6-4
If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`)
2. Logs will be helpful (If logs are large, please upload as attachment).

If you are using python package, please provide

1. The python version and distribution
2. The command to install `xgboost` if you are not installing from source

If you are using R package, please provide

1. The R `sessionInfo()`
> sessionInfo()
R version 3.3.3 (2017-03-06)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 8.1 x64 (build 9600)

locale:
[1] LC_COLLATE=Chinese (Simplified)_China.936 
[2] LC_CTYPE=Chinese (Simplified)_China.936   
[3] LC_MONETARY=Chinese (Simplified)_China.936
[4] LC_NUMERIC=C                              
[5] LC_TIME=Chinese (Simplified)_China.936    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] pROC_1.9.1       DiagrammeR_0.9.0 xgboost_0.6-4   

loaded via a namespace (and not attached):
 [1] igraph_1.0.1       Rcpp_0.12.10       rstudioapi_0.6     magrittr_1.5      
 [5] munsell_0.4.3      colorspace_1.3-2   viridisLite_0.2.0  lattice_0.20-34   
 [9] R6_2.2.0           brew_1.0-6         stringr_1.2.0      plyr_1.8.4        
[13] dplyr_0.5.0        visNetwork_1.0.3   Rook_1.1-1         tools_3.3.3       
[17] grid_3.3.3         data.table_1.10.4  gtable_0.2.0       DBI_0.6-1         
[21] influenceR_0.1.0   htmltools_0.3.5    yaml_2.1.14        lazyeval_0.2.0    
[25] digest_0.6.12      assertthat_0.2.0   tibble_1.3.0       Matrix_1.2-8      
[29] gridExtra_2.2.1    RColorBrewer_1.1-2 ggplot2_2.2.1      htmlwidgets_0.8   
[33] viridis_0.4.0      rgexf_0.15.3       stringi_1.1.5      scales_0.4.1      
[37] XML_3.98-1.6       jsonlite_1.4      

2. The command to install `xgboost` if you are not installing from source

## Steps to reproduce

library(xgboost)
library(DiagrammeR)
library(pROC)

d1=read.table("training.txt", sep="\t")
d2=read.table("testing.txt", sep="\t")
bst <- xgboost(data = as(as.matrix(d1[,-1]),"sparseMatrix"), label = d1[,1], 
                    max_depth = 2, eta = 1, nthread = 2, nrounds = 2, 
                    objective = "binary:logistic")
pred <- predict(bst,  as(as.matrix(d2[,-1]),"sparseMatrix"))
auc <- roc(d2[,1],pred)
print(paste('AUC score:', auc$auc))
#xgb.plot.tree(model = bst)
importance_matrix <- xgb.importance(model = bst)
print(importance_matrix)
xgb.plot.importance(importance_matrix = importance_matrix)
xgb.dump(model=bst, fname="xgb.model.txt", dump_format ="text")

## What have you tried?

The new data (named 'test')used for prediction in C is pre-processed into a float array of length=rows x cols. Here's the C code:

                DMatrixHandle h_test;
		myDll.XGDMatrixCreateFromMat((float *)test, rows, cols, -1, &h_test);

		BoosterHandle h_booster;
		int ret = myDll.XGBoosterCreate(NULL, 0, &h_booster);
		ret = myDll.XGBoosterLoadModel(h_booster, "xgb.model.txt");

		bst_ulong out_len;
		const float *f;
		ret = myDll.XGBoosterPredict(h_booster, h_test, 0, 0, &out_len, &f);

		for (unsigned int i = 0; i < out_len; i++)
			print("Predicted val %d: %.2f\n", i, f[i]);

**Comment by khotilov** [comment]
The binary model needs to be saved using `xgb.save`, not `xgb.dump`.

**Comment by fimmugit** [comment]
Hi, I changed to xgb.save to save the model in R and call the XGBoosterLoadModel in C the same way as before. The problem is still there: the out_len still returns garbage and F is still unreadable.  

    On Wednesday, April 19, 2017 11:12 PM, Vadim Khotilovich <notifications@github.com> wrote:
 

 The binary model needs to be saved using xgb.save, not xgb.dump.—

**Comment by khotilov** [comment]
Another not so good thing is that you were training your model using sparse data, but then running predictions from dense data while using -1 as a missing value indicator. In such situation, 0 needs to be used as a missing value indicator.

If you still would be having issues, please provide a fully reproducible example using some dummy data.
