### ISSUE TITLE
Inefficent implimentation of watchlist

### ISSUE THREAD

**Issue by ppallesen** [dmlc/xgboost#2211]
The watchlist seems to be implimented such that the predictions on the watchlist is preformed by calculating the predictions of all the trees for each boosting interation. This gives a O(n_iter²) cost. I think a more effiencient approach would be to calculate the predictions on the watchlist recursivly, such that pred_i = pred_{i-1}+predTree_i (potentially more complex to take care of DART-booster, ect).
Am I wrong? And is there a reason why this is not implimented in this way allready?

**Comment by khotilov** [comment]
Such caching does exist for watchlist data - see [gbtree.cc source](https://github.com/dmlc/xgboost/blob/e38bea3cdfdde3f1b33343f72db59da06043c73a/src/gbm/gbtree.cc#L485).

However, the's some inefficiency with this caching implementation in multiclass setting, where it adds O(num_class^2) cost #1689. You wouldn't usually notice it though unless you've got a few dozen classes in a not too large dataset.

**Comment by ppallesen** [comment]
Great looking at the implimentation of watchlist this catching is not used, only used for the trainingset. Instead the predictions are evaluated by calculating all the trees for each iteration. Do you think it is easy to use the catching in watchlist as well?

**Comment by ppallesen** [comment]
Sorry I can see my version is not up to date. Next time I will check that first. Thanks
