### ISSUE TITLE
typo in Dart description

### ISSUE THREAD

**Issue by ranigb** [dmlc/xgboost#2212]
In the tutorial for DART it says:

> Rasmi et al. proposed a new method ...

However, this is a typo since Rashmi (and not Rasmi) is the first name of the author. IMHO, it should be either 

> Vinayak et al. proposed a new method 
or, since there are only two authors on this paper:

> Vinayak and Gilad-Bachrach proposed a new method

**Comment by tqchen** [comment]
can you open a PR to fix this?

**Comment by marugari** [comment]
Sorry, it's my fault.

**Comment by hcho3** [comment]
I've opened a PR to fix it. Thanks!
