### ISSUE TITLE
how to use XGBoost External Memory Version with numpy

### ISSUE THREAD

**Issue by loseryao** [dmlc/xgboost#2215]
i want to use XGBoost External Memory Version,but my data is in numpy,now i only  kown the way to useXGBoost External Memory Version like this "dtrain = xgb.DMatrix('../data/agaricus.txt.train#dtrain.cache')",
but my like this "dtrain = xgb.DMatrix(feature_train.values, label=target_train.values)",so how to use XGBoost External Memory Version with numpy?

**Comment by deFang** [comment]
https://github.com/dmlc/xgboost/blob/master/demo/guide-python/external_memory.py
before that,  convert numpy.ndarray or pd.Dataframe data into libsvm dataformat (dump_svmlight_file method)
