### ISSUE TITLE
Installing XGBoost on Ubuntu 16.04

### ISSUE THREAD

**Issue by RiaanZoetmulder** [dmlc/xgboost#2218]
Hello,

I am trying to install xgboost with gpu support on my ubuntu 16.04 pc.
Here is what I have tried:

1) Installing with pip, then running the instruction at: https://github.com/dmlc/xgboost/tree/master/plugin/updater_gpu

I have done so by cd-ing into the build directory and running the following command: 
cmake .. -DPLUGIN_UPDATER_GPU=ON -DCUB_DIRECTORY=~/Documents/cub-1.6.4
I then proceeded to make the file. Didn't work.

2) uninstalling all of xgboost
cloning the xgboost repository via: git clone --recursive https://github.com/dmlc/xgboost
I then followed the instructions here : https://github.com/dmlc/xgboost/tree/master/plugin/updater_gpu

Same error.

3) cloning the repository again (after having uninstalled it). Building it from scratch, then running the instructions to install the gpu plugin.

In all cases I got the same error, appears to have something to do with certain math functions being defined already. 

I have of course downloaded the cub library and I have put it in my Documents folder.

My Cuda version (after running nvcc --version)  is 7.5.

Here is the full error message:

-- Configuring done
-- Generating done
-- Build files have been written to: /home/riaan/xgboost/build
[  5%] Built target rabit
[  6%] Building NVCC (Device) object CMakeFiles/updater_gpu.dir/plugin/updater_gpu/src/updater_gpu_generated_gpu_builder.cu.o
/usr/include/c++/4.9/tr1/cmath(424): error: function "acosh(float)" has already been defined

/usr/include/c++/4.9/tr1/cmath(442): error: function "asinh(float)" has already been defined

/usr/include/c++/4.9/tr1/cmath(461): error: function "atanh(float)" has already been defined

/usr/include/c++/4.9/tr1/cmath(477): error: function "cbrt(float)" has already been defined

/usr/include/c++/4.9/tr1/cmath(495): error: function "copysign(float, float)" has already been defined

/usr/include/c++/4.9/tr1/cmath(516): error: function "erf(float)" has already been defined

/usr/include/c++/4.9/tr1/cmath(532): error: function "erfc(float)" has already been defined

/usr/include/c++/4.9/tr1/cmath(550): error: function "exp2(float)" has already been defined

/usr/include/c++/4.9/tr1/cmath(566): error: function "expm1(float)" has already been defined

/usr/include/c++/4.9/tr1/cmath(608): error: function "fdim(float, float)" has already been defined

/usr/include/c++/4.9/tr1/cmath(628): error: function "fma(float, float, float)" has already been defined

/usr/include/c++/4.9/tr1/cmath(646): error: function "fmax(float, float)" has already been defined

/usr/include/c++/4.9/tr1/cmath(664): error: function "fmin(float, float)" has already been defined

/usr/include/c++/4.9/tr1/cmath(685): error: function "hypot(float, float)" has already been defined

/usr/include/c++/4.9/tr1/cmath(703): error: function "ilogb(float)" has already been defined

/usr/include/c++/4.9/tr1/cmath(721): error: function "lgamma(float)" has already been defined

/usr/include/c++/4.9/tr1/cmath(737): error: function "llrint(float)" has already been defined

/usr/include/c++/4.9/tr1/cmath(753): error: function "llround(float)" has already been defined

/usr/include/c++/4.9/tr1/cmath(772): error: function "log1p(float)" has already been defined

/usr/include/c++/4.9/tr1/cmath(789): error: function "log2(float)" has already been defined

/usr/include/c++/4.9/tr1/cmath(805): error: function "logb(float)" has already been defined

/usr/include/c++/4.9/tr1/cmath(823): error: function "lrint(float)" has already been defined

/usr/include/c++/4.9/tr1/cmath(839): error: function "lround(float)" has already been defined

/usr/include/c++/4.9/tr1/cmath(855): error: function "nearbyint(float)" has already been defined

/usr/include/c++/4.9/tr1/cmath(871): error: function "nextafter(float, float)" has already been defined

/usr/include/c++/4.9/tr1/cmath(905): error: function "remainder(float, float)" has already been defined

/usr/include/c++/4.9/tr1/cmath(923): error: function "remquo(float, float, int *)" has already been defined

/usr/include/c++/4.9/tr1/cmath(941): error: function "rint(float)" has already been defined

/usr/include/c++/4.9/tr1/cmath(957): error: function "round(float)" has already been defined

/usr/include/c++/4.9/tr1/cmath(973): error: function "scalbln(float, long)" has already been defined

/usr/include/c++/4.9/tr1/cmath(989): error: function "scalbn(float, int)" has already been defined

/usr/include/c++/4.9/tr1/cmath(1011): error: function "tgamma(float)" has already been defined

/usr/include/c++/4.9/tr1/cmath(1027): error: function "trunc(float)" has already been defined

/home/riaan/xgboost/include/xgboost/././feature_map.h(66): warning: type qualifier on return type is meaningless

33 errors detected in the compilation of "/tmp/tmpxft_00000957_00000000-7_gpu_builder.cpp1.ii".
CMake Error at updater_gpu_generated_gpu_builder.cu.o.cmake:266 (message):
  Error generating file
  /home/riaan/xgboost/build/CMakeFiles/updater_gpu.dir/plugin/updater_gpu/src/./updater_gpu_generated_gpu_builder.cu.o

CMakeFiles/updater_gpu.dir/build.make:976: recipe for target 'CMakeFiles/updater_gpu.dir/plugin/updater_gpu/src/updater_gpu_generated_gpu_builder.cu.o' failed
make[2]: *** [CMakeFiles/updater_gpu.dir/plugin/updater_gpu/src/updater_gpu_generated_gpu_builder.cu.o] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/updater_gpu.dir/all' failed
make[1]: *** [CMakeFiles/updater_gpu.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Hoping you know what is wrong! @RAMitchell

**Comment by RAMitchell** [comment]
Thanks for this.

Have had this issue from a few users, will look into it.

**Comment by ricky-return42** [comment]
How do you remove xgboost and do it all over again? I am currently experiencing the same issue. Thanks for the help!

**Comment by theamazingdrew** [comment]
I tried installing it this evening and it crashed as well. Ubunt 16.04, i7-6800, gtx1060 with the lastest cuda-8

(xgbgpu) d@robo:~/Downloads/xgboost/build$ make
Scanning dependencies of target rabit
[  1%] Building CXX object CMakeFiles/rabit.dir/rabit/src/allreduce_base.cc.o
[  2%] Building CXX object CMakeFiles/rabit.dir/rabit/src/allreduce_robust.cc.o
[  3%] Building CXX object CMakeFiles/rabit.dir/rabit/src/engine.cc.o
[  4%] Building CXX object CMakeFiles/rabit.dir/rabit/src/c_api.cc.o
[  5%] Linking CXX static library librabit.a
[  5%] Built target rabit
[  6%] Building NVCC (Device) object CMakeFiles/updater_gpu.dir/plugin/updater_gpu/src/updater_gpu_generated_gpu_hist_builder.cu.o
/usr/lib/gcc/x86_64-linux-gnu/5/include/mwaitxintrin.h(36): error: identifier "__builtin_ia32_monitorx" is undefined

/usr/lib/gcc/x86_64-linux-gnu/5/include/mwaitxintrin.h(42): error: identifier "__builtin_ia32_mwaitx" is undefined

/home/d/Downloads/xgboost/include/xgboost/./feature_map.h(66): warning: type qualifier on return type is meaningless

/home/d/Downloads/xgboost/plugin/updater_gpu/src/common.cuh(136): error: expected a "{" introducing a lambda body

/home/d/Downloads/xgboost/plugin/updater_gpu/src/common.cuh(136): error: expected a ")"

/home/d/Downloads/xgboost/plugin/updater_gpu/src/common.cuh(140): warning: parsing restarts here after previous syntax error

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(31): error: expected a "{" introducing a lambda body

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(31): error: expected a ")"

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(185): error: expected a "{" introducing a lambda body

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(185): error: expected a ")"

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(196): warning: parsing restarts here after previous syntax error

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(203): error: expected a "{" introducing a lambda body

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(203): error: expected a ")"

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(209): warning: parsing restarts here after previous syntax error

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(220): error: expected a "{" introducing a lambda body

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(220): error: expected a ";"

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(224): warning: parsing restarts here after previous syntax error

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(258): error: expected a "{" introducing a lambda body

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(258): error: expected a ")"

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(278): warning: parsing restarts here after previous syntax error

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(298): error: expected a "{" introducing a lambda body

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(298): error: expected a ")"

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(321): warning: parsing restarts here after previous syntax error

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(322): error: identifier "parent_sum" is undefined

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(322): error: identifier "left" is undefined

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(323): error: identifier "node_idx" is undefined

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(323): error: identifier "loss_chg" is undefined

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(323): error: identifier "missing_left" is undefined

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(323): error: identifier "fvalue" is undefined

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(323): error: identifier "fidx" is undefined

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(326): error: identifier "idx" is undefined

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(254): warning: variable "colsample" was declared but never referenced

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(335): error: expected a declaration

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(336): error: this declaration has no storage class or type specifier

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(336): error: function "dh::throw_on_cuda_error" cannot be defined in the current scope

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(336): error: expected a ")"

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(339): error: name followed by "::" must be a class or namespace name

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(341): error: identifier "gpu_gpair" is undefined

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(341): error: expected a ";"

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(345): error: identifier "Node" is undefined

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(345): error: expected a ";"

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(348): warning: parsing restarts here after previous syntax error

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(350): error: identifier "tmp" is undefined

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(350): error: identifier "nodes" is undefined

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(353): error: name followed by "::" must be a class or namespace name

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(354): error: identifier "is_dense" is undefined

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(355): error: "this" may only be used inside a nonstatic member function

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(357): error: "this" may only be used inside a nonstatic member function

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(361): error: name followed by "::" must be a class or namespace name

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(362): error: identifier "position" is undefined

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(363): error: identifier "Node" is undefined

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(363): error: identifier "d_nodes" is undefined

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(363): error: identifier "nodes" is undefined

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(364): error: identifier "gidx_fvalue_map" is undefined

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(365): error: identifier "device_matrix" is undefined

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(366): error: identifier "info" is undefined

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(368): error: expected a "{" introducing a lambda body

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(368): error: expected a ")"

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(390): warning: parsing restarts here after previous syntax error

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(390): error: expected a ";"

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(390): error: expected a declaration

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(393): error: name followed by "::" must be a class or namespace name

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(394): error: identifier "position" is undefined

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(395): error: identifier "position_tmp" is undefined

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(396): error: identifier "Node" is undefined

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(396): error: identifier "d_nodes" is undefined

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(396): error: identifier "nodes" is undefined

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(397): error: identifier "gidx_feature_map" is undefined

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(398): error: identifier "gidx_fvalue_map" is undefined

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(399): error: identifier "device_matrix" is undefined

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(403): error: expected a "{" introducing a lambda body

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(403): error: expected a ")"

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(418): warning: parsing restarts here after previous syntax error

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(421): error: expected a "{" introducing a lambda body

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(421): error: expected a ")"

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(445): warning: parsing restarts here after previous syntax error

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(445): error: expected a ";"

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(446): error: expected a declaration

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(448): error: this declaration has no storage class or type specifier

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(448): error: identifier "position_tmp" is undefined

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(449): error: expected a declaration

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(491): warning: parsing restarts here after previous syntax error

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(494): error: this declaration has no storage class or type specifier

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(494): error: expected a ";"

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(505): warning: parsing restarts here after previous syntax error

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(507): error: expected a declaration

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(514): warning: parsing restarts here after previous syntax error

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(515): error: expected a declaration

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(521): warning: parsing restarts here after previous syntax error

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(524): error: this declaration has no storage class or type specifier

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(524): error: expected a ";"

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(526): error: this declaration has no storage class or type specifier

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(526): error: identifier "hmat_" is undefined

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(527): error: this declaration has no storage class or type specifier

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(529): error: this declaration has no storage class or type specifier

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(529): error: no instance of overloaded function "thrust::sequence" matches the specified type

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(529): error: identifier "hist_node_segments" is undefined

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(529): error: expected a ")"

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(532): error: this declaration has no storage class or type specifier

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(532): error: identifier "h_feature_segments" is undefined

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(534): error: this declaration has no storage class or type specifier

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(534): error: expected a ";"

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(536): error: this declaration has no storage class or type specifier

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(537): error: expected a declaration

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(539): error: this declaration has no storage class or type specifier

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(539): error: variable "position" has already been defined

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(539): error: expected a ";"

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(540): error: this declaration has no storage class or type specifier

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(540): error: identifier "gpair" is undefined

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(541): error: this declaration has no storage class or type specifier

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(541): error: a value of type "int *" cannot be used to initialize an entity of type "int"

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(541): error: expected a ")"

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(542): error: this declaration has no storage class or type specifier

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(542): error: variable "hist" has already been defined

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(542): error: expected a ";"

/home/d/Downloads/xgboost/plugin/updater_gpu/src/gpu_hist_builder.cu(543): error: expected a declaration

Error limit reached.
100 errors detected in the compilation of "/tmp/tmpxft_00001274_00000000-7_gpu_hist_builder.cpp1.ii".
Compilation terminated.
CMake Error at updater_gpu_generated_gpu_hist_builder.cu.o.cmake:266 (message):
  Error generating file
  /home/d/Downloads/xgboost/build/CMakeFiles/updater_gpu.dir/plugin/updater_gpu/src/./updater_gpu_generated_gpu_hist_builder.cu.o


CMakeFiles/updater_gpu.dir/build.make:70: recipe for target 'CMakeFiles/updater_gpu.dir/plugin/updater_gpu/src/updater_gpu_generated_gpu_hist_builder.cu.o' failed
make[2]: *** [CMakeFiles/updater_gpu.dir/plugin/updater_gpu/src/updater_gpu_generated_gpu_hist_builder.cu.o] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/updater_gpu.dir/all' failed
make[1]: *** [CMakeFiles/updater_gpu.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by RAMitchell** [comment]
Which version of g++ are you using? 5 might be too recent, try 4.8.

**Comment by joshpeng** [comment]
@RAMitchell I got the same error as @theamazingdrew when trying to build on an AWS p2.xlarge instance. 
When I run ```make``` a second or third time I then get these errors:

```
[  5%] Built target rabit
[  6%] Building NVCC (Device) object CMakeFiles/updater_gpu.dir/plugin/updater_gpu/src/updater_gpu_generated_gpu_builder.cu.o
/home/josh/xgboost/include/xgboost/././feature_map.h(66): warning: type qualifier on return type is meaningless

/home/josh/xgboost/include/xgboost/././feature_map.h(66): warning: type qualifier on return type is meaningless

/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
                                          ^
CMake Error at updater_gpu_generated_gpu_builder.cu.o.cmake:266 (message):
  Error generating file
  /home/josh/xgboost/build/CMakeFiles/updater_gpu.dir/plugin/updater_gpu/src/./updater_gpu_generated_gpu_builder.cu.o


CMakeFiles/updater_gpu.dir/build.make:895: recipe for target 'CMakeFiles/updater_gpu.dir/plugin/updater_gpu/src/updater_gpu_generated_gpu_builder.cu.o' failed
make[2]: *** [CMakeFiles/updater_gpu.dir/plugin/updater_gpu/src/updater_gpu_generated_gpu_builder.cu.o] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/updater_gpu.dir/all' failed
make[1]: *** [CMakeFiles/updater_gpu.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```
I am on g++-4.8.

**Comment by RAMitchell** [comment]
The seems related to tensorflow/tensorflow#1066

**Comment by joshpeng** [comment]
@RAMitchell Unfortunately it still doesn't seem to work. I tried all 3 flags suggested by that link as follows:
```
make CXXFLAGS='-D_MWAITXINTRIN_H_INCLUDED -D_FORCE_INLINES -D__STRICT_ANSI__'
make CXXFLAGS='-D_MWAITXINTRIN_H_INCLUDED -D_FORCE_INLINES'
make CXXFLAGS='-D_MWAITXINTRIN_H_INCLUDED
```
Still receiving the exact same error. Hm. Is there another way to pass in those flags?

**Comment by RAMitchell** [comment]
You are still working on an Amazon p2 instance? I will have to try it myself.

**Comment by joshpeng** [comment]
Thanks, yes, brand new p2.xlarge instance on Ubuntu 16.04. Only thing installed prior to xgboost was Anaconda 4.3.1 for Python2

**Comment by theamazingdrew** [comment]
I explicitly installed mine in a virtual environment for python that did
*not* have tensorflow, because I didn't want a dependency collision with
GPU XGBoost and Tensorflow. So I have one venv for tensorflow and one venv
for xgboost gpu.

And I got the error I got (even though the venv didn't have xgboost). And I
don't have tensorflow installed outside of its virtual environment.
