### ISSUE TITLE
Compilation errors when disabling OpenMP

### ISSUE THREAD

**Issue by junshi15** [dmlc/xgboost#2219]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System:
Centos or RHEL 6.5

Compiler:
gcc 4.9.2 from devtoolset-3

Package used (python/R/jvm/C++):
c++

`xgboost` version used:
master branch as of April 21, 2017
dbaa5d0bdf7684b3e6aeea7d6bb139c6ede3f2a7

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`)
dbaa5d0bdf7684b3e6aeea7d6bb139c6ede3f2a7

2. Logs will be helpful (If logs are large, please upload as attachment).
g++ -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -O3 -funroll-loops -msse2 -fPIC -DDISABLE_OPENMP -MM -MT build/learner.o src/learner.cc >build/learner.d
g++ -c -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -O3 -funroll-loops -msse2 -fPIC -DDISABLE_OPENMP src/learner.cc -o build/learner.o
In file included from /opt/rh/devtoolset-3/root/usr/include/c++/4.9.2/parallel/tags.h:36:0,
                 from /opt/rh/devtoolset-3/root/usr/include/c++/4.9.2/parallel/algorithmfwd.h:34,
                 from /opt/rh/devtoolset-3/root/usr/include/c++/4.9.2/parallel/algorithm:35,
                 from include/xgboost/./base.h:52,
                 from include/xgboost/logging.h:13,
                 from src/learner.cc:7:
/opt/rh/devtoolset-3/root/usr/lib/gcc/x86_64-redhat-linux/4.9.2/include/omp.h:71:39: error: conflicting declaration of ‘void omp_set_num_threads(int)’ with ‘C’ linkage
 extern void omp_set_num_threads (int) __GOMP_NOTHROW;
                                       ^
In file included from include/xgboost/./base.h:10:0,
                 from include/xgboost/logging.h:13,
                 from src/learner.cc:7:
dmlc-core/include/dmlc/omp.h:22:13: note: previous declaration with ‘C++’ linkage
 inline void omp_set_num_threads(int nthread) {}
             ^
In file included from /opt/rh/devtoolset-3/root/usr/include/c++/4.9.2/parallel/tags.h:36:0,
                 from /opt/rh/devtoolset-3/root/usr/include/c++/4.9.2/parallel/algorithmfwd.h:34,
                 from /opt/rh/devtoolset-3/root/usr/include/c++/4.9.2/parallel/algorithm:35,
                 from include/xgboost/./base.h:52,
                 from include/xgboost/logging.h:13,
                 from src/learner.cc:7:
/opt/rh/devtoolset-3/root/usr/lib/gcc/x86_64-redhat-linux/4.9.2/include/omp.h:71:39: error: declaration of ‘void omp_set_num_threads(int) throw ()’ has a different exception specifier
 extern void omp_set_num_threads (int) __GOMP_NOTHROW;

If you are using python package, please provide

1. The python version and distribution
2. The command to install `xgboost` if you are not installing from source

If you are using R package, please provide

1. The R `sessionInfo()`
2. The command to install `xgboost` if you are not installing from source

## Steps to reproduce

1. git clone --recursive https://github.com/dmlc/xgboost.git
2. cd xgboost
3. make config=make/minimum.mk

## What have you tried?

1. make -j8 works, i.e. enabling openMP works.
2. but I have to disable openMP since the build will be targeted at a cluster which does not have libgomp installed.
3.

**Comment by junshi15** [comment]
Same error on Ubuntu 14.04, so it is not a problem specific to Centos 6.5. It seems -DDISABLE_OPENMP does not work properly.

**Comment by mmalohlava** [comment]
It seems like `dmlc-core` overriding methods from `omp.h` by forgetting to setup proper method signatures. I attached a quick patch which unblock at least my g++4 based compilation chain (via dock cross).
[01_dmlc_core_imports.patch.txt](https://github.com/dmlc/xgboost/files/1050634/01_dmlc_core_imports.patch.txt)

**Comment by DCBoland** [comment]
@mmalohlava I had the same issue compiling on OS X. This patch (applied to `0db37c0`) resolved the issue. Thanks!

**Comment by danielfppps** [comment]
@mmalohlava Works for me on Ubuntu 16.04 LTS using gcc 4.9.4. Thanks!

**Comment by junshi15** [comment]
@mmalohlava Sorry for the delay, I missed your email. 
Yes, it works now. Thanks for the fix. Is there a PR for this?

**Comment by mmalohlava** [comment]
@junshi15 yes, it is here: https://github.com/dmlc/dmlc-core/pull/281

**Comment by junshi15** [comment]
thanks. I am closing this issue.
