### ISSUE TITLE
Wrong? behaviour in prediction for a 'singular' case

### ISSUE THREAD

**Issue by BlindApe** [dmlc/xgboost#222]
In a model dump I have for a booster the line:

5:[f93<99] yes=11,no=12,missing=12

but when a case with f93 = 99 reach this point is sent to node 11 instead of 12.

The variable f93 takes in the training data these values:

 -9999 -1  0  1  2  3  4  5  6  7  8  9 10 11 99

(missing is assigned to -9999)

so 99 in this case is the max value for f93 in all the data.

Do you think it is a problem with the text dump and the splitting point wasn't 99 but 99.5? The rest of splitting points are selected to midpoints but in this case the max value is used.

**Comment by tqchen** [comment]
This was because in such boundary case, 99+eps was assigned to the split value, where eps= 1e-5 a small value. So the printed result should have been  something like 99.00001.

I think I will change the behavior of such boundary case to assign larger value than 99+eps

**Comment by tqchen** [comment]
I pushed a change in latest version, now the boundary should be somewhere around 99 * 2, please see fi it works

**Comment by BlindApe** [comment]
Thank you Tianqui, 
If I undestand this only affect to the model dump in text file. The prediction in case the splitting point was 99.00001 is correct.

I can't check it because the model was saved in a previous version and now I can't load again. (This is an open issue).

**Comment by tqchen** [comment]
I see, I will close the issue for now. Currently I have no idea on what was happening in issue #200 (there was no intention break of backward compatibility since 0.3), if there is a simple code to produce it from different versions(providing hash tag of the verison) maybe @hetong007 or I will take  alook.

**Comment by BlindApe** [comment]
I have the model saved (6Mb) if you want I send you by mail. (The code use a lot of data). The behavior is the same with all old models saved.

**Comment by tqchen** [comment]
I pushed a fix of the code, see #200

**Comment by BlindApe** [comment]
OK. Thank you. Works!

But I load the old model and do a new dump to text and the line in booster remainds:

5:[f93<99] yes=11,no=12,missing=12

So I misunderstood something...

Why if f93 is 99 the prediction returns the  leaf at the bottom of node 11 instead of the leaf of 12?

Is internal '99' splitting point really 99.00001?

**Comment by tqchen** [comment]
I think so, what i meant is if you train a new model again on the same data, the model will be f93 < 99 * 2

But for old models, i guess it was still 99.00001

**Comment by BlindApe** [comment]
... but if the max value of data is 99, define a splitting point greater than 99 makes not sense, so you can't assign a value for the right leaf so there aren't cases to estimate.

I think if you have o1, o2, o3, o4 differents values, you use the midpoints o1o2 for split on o2, o2o3 for split on o3 so for split on o4 the logic point is o3o4 not 2*o4.

In this case '99' must be in the right leaf for every splitting. (The only exception could be if you split on missing value but I don't know if you done).

**Comment by tqchen** [comment]
This was because missing value presented in the data, and the algorithm decided that splitting on missing value vs non-missing was better than other solutions

**Comment by BlindApe** [comment]
Thanks. It's what I thought.

**Comment by BlindApe** [comment]
I've now a new case could be related with this.
In a node the split is defined by the value 122002 (Saw in tree dump). A case with exactly this value should go to the right branch (left is defined '<'), but when using predict with this case, it sent to the left branch.
(In this case 122002 isn't an extrem value of variable)
Any tips about?

**Comment by tqchen** [comment]
hmm, could due to inadequate dump information that ignores the trailing points in the float.

**Comment by BlindApe** [comment]
The dump only uses two decimals and could explain it, but in this case the variable is integer so split points should be integer or middle point of two integers.
