### ISSUE TITLE
Query: Is there a way to select on which GPU your model runs on?

### ISSUE THREAD

**Issue by setuc** [dmlc/xgboost#2224]
On a multi-gpu system, is there a way in which you can pass a parameter on which GPU or CUDA device the xgboost model runs on? If we were to modify the code where would we start? As is does XGboost allow for plugin parameters? Any ideas  @RAMitchell

**Comment by RAMitchell** [comment]
About to release a new version :) Wait a day or two.

**Comment by setuc** [comment]
super...will wait to see....excited :+1:
