### ISSUE TITLE
[jvm-packages] Can't provide weights in xgboost4j-scala

### ISSUE THREAD

**Issue by ebernhardson** [dmlc/xgboost#2226]
There doesn't seem to be any method for providing weights in xgboost4j-scala. Support exists in xgboost4j, but there is nowhere in the transformation from Dataset or RDD to DMatrix to provide this information. This is likely because it looks like upstream spark.ml also doesn't have any support for weights, but perhaps something could be worked out.

**Comment by CodingCat** [comment]
https://github.com/dmlc/xgboost/issues/2122

**Comment by zhangsssss** [comment]
@CodingCat If that could be implemented soon it would be awesome:) We do need this feature in our production code.

**Comment by CodingCat** [comment]
duplicate with #2122
