### ISSUE TITLE
Fix Travis R Build

### ISSUE THREAD

**Issue by tqchen** [dmlc/xgboost#2228]
There seems to be problem again with openmp flag on OSX in our travis R build @thirdwing @khotilov @hetong007  can you help to take a look?

https://travis-ci.org/dmlc/xgboost/jobs/224704191

**Comment by thirdwing** [comment]
This is caused by R 3.4.0.

I want to know if we enabled `openmp` on OSX by default or not? @hetong007 @khotilov

**Comment by khotilov** [comment]
Unfortunately, I currently don't have access to any OSX machine and I've never used xgboost on a Mac. My understanding though was that OpenMP was not enabled in CRAN OSX builds as SHLIB_OPENMP_CXXFLAGS was not set in there by default. Now it seems to be set for R 3.4.

**Comment by thirdwing** [comment]
OK. I am afraid I need to upgrade to OSX 10.11 to install R 3.4.0.

I will figure out this later.

KK
