### ISSUE TITLE
xgboost in C++ example code

### ISSUE THREAD

**Issue by courosh** [dmlc/xgboost#2230]
Is there example code for using xgboost in C++?

**Comment by headupinclouds** [comment]
Here is a small C++ project I put together with a test lib + app that should help clarify the C++ API at least.

https://github.com/elucideye/xgboostcpp

Note that this is using an older fork of xgboost in the [hunter package manager](https://github.com/ruslo/hunter) that includes a few modifications, which may not be quite what you need, but it should server as a starting point at least.

* uses the older xgboost OpenMP implementation/fork
* added hunter package management
* cereal portable binary archive output
* boost portable binary archive (compressed)

At the time, I believe there were endian and 32 vs 64 bit issues with the built in serialization.  The above serialization (intrusive) was added to address these issues and to help reduce model size by skipping unnecessary structure fields in some cases.  The test app is fairly limited and is currently configured for basic regression, so this is more of a code sample at this point.

I plan to update the xgboost hunter package to take advantage of the new API at some point.
