### ISSUE TITLE
List based ranking metrics don't take record weights into account

### ISSUE THREAD

**Issue by ebernhardson** [dmlc/xgboost#2231]
List based metrics, such as ndcg, precision, and map, don't take the weight of the records into account when calculating the metric.

I'm not sure there is a defined way to take the weight into account on a per-record basis, but all of these metrics use EvalRankList to retrieve the mean value across all groups. What we could do is calculate the mean weight of records per group and return a weighted mean of all groups. In the case of no weights provided the mean weight per group will be 1.0, and the weighted mean will be the same as the current unweighted mean implementation.

I'm willing to work up a patch for this, but wanted to make sure this is something desired, or if there is perhaps another way to weight these list-wise metrics.

**Comment by ebernhardson** [comment]
I'm not sure there is a defined way to take the weight into account on a per-record basis, but all of these metrics use EvalRankList to retrieve the mean value across all groups. What we could do is calculate the mean weight of records per group and return a weighted mean of all groups.

I'm willing to work up a patch for this, but wanted to make sure this is something desired, or if there is perhaps another way to weight these list-wise metrics.

**Comment by Downchuck** [comment]
Does your read match mine as well, that weighting only applies to single-machine mode?
