### ISSUE TITLE
[xgboost4j-spark] how to limit number of executors / rabit nodes

### ISSUE THREAD

**Issue by junshi15** [dmlc/xgboost#2232]
I tried this example, but with a much larger dataset (30Gb, about 400 partitions).
https://github.com/dmlc/xgboost/blob/master/jvm-packages/xgboost4j-example/src/main/scala/ml/dmlc/xgboost4j/scala/example/spark/SparkWithDataFrame.scala

the spark command is roughly:
spark-submit --master yarn --deploy-mode cluster 
    --num-executors 10  \
    --executor-memory 12g --conf spark.yarn.executor.memoryOverhead=14096 \
    --jars xgboost4j-spark-0.7-jar-with-dependencies.jar\
    --class ml.dmlc.xgboost4j.scala.example.spark.MyApp \
      xgboost4j-example-0.7-jar-with-dependencies.jar \
      -trainPath hdfs:///path/to/train/data \
      -modelPath hdfs:///path/to/local/data \
      -numRounds 3 \
      -numWorkers 10
Note numRounds and numWorkers correspond to "numRound" and "nWorkers" in the original code. I just added an argument parser.

After submitted the job, the driver requested about 400 executors, one executor per partition. Is this expected? Why number of executors is not set to 10?

**Comment by CodingCat** [comment]
it's a yarn or spark problem...xgboost cannot control how many executors you start...I do not know why it requests 400 executors but not tasks (given that you have passed in num-executors and assuming your default executor-cores is 1)

**Comment by junshi15** [comment]
you are right, spark.dynamicAllocation.enabled was set to true. Disabling it resolved the issue.
