### ISSUE TITLE
Choice  of default missing value

### ISSUE THREAD

**Issue by chrissly31415** [dmlc/xgboost#224]
There seems to be a bug in the R predict function, when a sample has a feature with the value of exactly = 0, it might take the wrong path within the tree.
A workaround which fixes the problem is  to use something like data[tdata == 0] <- 1E-15 for the respective dataframe before prediction.

Best regards,
Christoph

**Comment by chrissly31415** [comment]
Actually, I think the problem is related to the default value of the missing parameter which seems to be 0 for the xgboost and the predict function. A better default would be missing=NA.

**Comment by tqchen** [comment]
missing = 0 was a choice for consistency with python and backward compatibility.  In general such choice won't affect predictive accuracy(0 was used as a special value to be able to go both directions)

**Comment by chrissly31415** [comment]
thanks, I understand, I was just having difficulties to retrace predictions from a regression model dump due to the fact that numerically nearly identical samples  gave  different predictions.

**Comment by tqchen** [comment]
i.c. the choice of missing=0 was due to some legacy reasons. I think I am happy to change it to NA if enough people thinks this is a reasonable thing to do. In the meanwhile, you can manually specify it.

**Comment by LiuSai-Dream** [comment]
what if my missing value is -1? how to set the missing values? I looked into the xgboost_main.cpp, found no Param to deal with missing values.  
Thx!

**Comment by tqchen** [comment]
When you specify data as libsvm format, simply ignore the missing value and only specify the feature index of observed features
