### ISSUE TITLE
Trace the path of records through the trees and output formulation.

### ISSUE THREAD

**Issue by uptownfunk** [dmlc/xgboost#2246]
More of a feature request than an issue here.

What I would like to do is for each record that I score, I would like to be able to print out the complete formula that goes into calculating the score. I imagine that this is dependent on the path through the trees a record takes and that this would be different for each record. 

I know the outputted probabilities are a combination of the results from each individual tree, with some modified weights, which are then summed up and transformed (or somehow aggregated) into a single prediction score. What I would like is to be able to print out that formulation. e.g. if x_1 is a row of data I am trying to score, I would like to know how that score is produced e.g. score_for_x1 = weight1*feature1+ weight2 * feature2, or some such formulation (it may not necessarily be a linear combination)

Also if I could get the path each record took through each individual tree, that would be very helpful as well.

We are getting requested to produce "reason codes" that explain why each record got the score that it did and this was one thought that came to mind.

Thanks!

**Comment by edi-bice** [comment]
take a look at the pred_leaf parameter in the predict method
