### ISSUE TITLE
XGLinear  get different predict result each time.

### ISSUE THREAD

**Issue by yingxu9871** [dmlc/xgboost#2249]
Operating System: Win7 64
Package used (python/R/jvm/C++): Python 2.7.13 [MSC v.1500 64 bit (AMD64)] on win32 
`xgboost` version used: 0.6

## Steps to reproduce
1. param['booster']='gblinear' 
2. bst = xgb.train(param, xg_train, num_round, watchlist ); 
3. bst.predict( xg_train)

## Issue
Use the same data and run above commands to train and predict data twice, you get different predict value, the difference is between 0.001 to 0.01. 
We expect the predict result are the same. 

## Note
when we set param['nthread'] = 1, the issue doesn't exist any more.

**Comment by Laurae2** [comment]
Multithreaded xgboost is not expected to provide identical results because of racing conditions, so the only solution you have is to use one thread.
