### ISSUE TITLE
XGboost get same result regardless of different random seed

### ISSUE THREAD

**Issue by yingxu9871** [dmlc/xgboost#2250]
## Environment info
Operating System: Win7 64
Package used (python/R/jvm/C++): Python 2.7.13 [MSC v.1500 64 bit (AMD64)] on win32
xgboost version used: 0.6

## Steps to reproduce

1. bst = xgb.train(param, xg_train, num_round, watchlist ); 
2. param['seed'] = 123 
3. bst.predict( xg_train) 

## Issue
Use the same data and run above commands to train and predict data twice with different random seed set in step2, we get same predict result. 

As my understanding, user need to set same random seed in order to get same result or it will get different result.  So now I am confused why we need random seed here.

**Comment by RAMitchell** [comment]
Try using the subsample or colsample parameters and see if you still get the same result with different seeds.
