### ISSUE TITLE
could xgboost spark cluster model support watchList or train(with OldModel inited)?

### ISSUE THREAD

**Issue by buptzzl** [dmlc/xgboost#2254]
as we all known,  xgboost support watchList to do evaluation on each round. 
1, Does xgboost spark  cluster model  support this very useful feature? 
2, otherwise, I'm also come up with a middle-way solutation: 
Given setting number-rounds,  If there is a new interface: xgboost.train(xx, initedby-pre-round-model), then I cound train the model  one-round-by-one， and evaluated at each round's model.

**Comment by CodingCat** [comment]
would you mind add [jvm-packages] in the title when you ask about xgboost4j so that I can quickly identify that?

we are working on it, maybe through rabit communication layer...
