### ISSUE TITLE
Access additional information in objective function

### ISSUE THREAD

**Issue by CLevasseur** [dmlc/xgboost#2255]
I am trying to get access to additional information while computing the objective function.

I expected `DMatrix.set_float_info()` to allow me to do that, unfortunately DMatrix.get_float_info handles `label`, `weight` and `base_margin` only, and crashes for any other key.

The code that crashes: https://github.com/dmlc/xgboost/blob/master/src/c_api/c_api.cc#L488

Would be great if it were possible to add custom fields in the DMatrix object, using set_float_info or any other method. Objective functions could then optimize metrics that need more than labels, predictions and weights.

**Comment by pommedeterresautee** [comment]
This is discussed in other issues. You can include these info in your custom loss directly (through closure). It has been decided that attaching anything to the DMatrix object was not a good strategy.
