### ISSUE TITLE
who can help me?

### ISSUE THREAD

**Issue by luoyexuge** [dmlc/xgboost#2259]
git clone --recursive https://github.com/dmlc/xgboost
cd xgboost; cp make/minimum.mk ./config.mk; make -j4

cd  jvm-package；mvn package   happened  errors：

] Failed to execute goal org.scalastyle:scalastyle-maven-plugin:0.8.0:check (checkstyle) on project xgboost-jvm: Execution checkstyle of goal org.scalastyle:scalastyle-maven-plugin:0.8.0:check failed: A required class was missing while executing org.scalastyle:scalastyle-maven-plugin:0.8.0:check: scala/xml/Node

who  can  help me？

**Comment by Bhuvanamitra** [comment]
try updating maven with 'mvn install -U' command
I got a similar problem and could build successfully by force updating maven.
