### ISSUE TITLE
How to use C/C++ language to predict ? Can you give a example?

### ISSUE THREAD

**Issue by XiongXiaojun** [dmlc/xgboost#2262]
I trained a model using the python language, but I need to use the C language to read the model and predict. However, I don't find the demo about c/c++.

**Comment by headupinclouds** [comment]
I took me a little while to sort through the C++ side of things a couple years ago.  Here is a small project and console app I put together to help demonstrate the C++ API (this is a WIP refactoring of some code I have been using in internal projects that includes some boost + cereal serialization options and half precision storage to reduce serialization for mobile applications): 

https://github.com/elucideye/xgboostcpp

Relates to: https://github.com/dmlc/xgboost/issues/2230 and https://gitter.im/dmlc/xgboost?at=556869f69f3a9b7b0609dcb1

This uses the [hunter package manager](https://github.com/ruslo/hunter) and the copmanion [polly](https://github.com/ruslo/polly) toolchains to support cross platform builds easily.  I've added some initial CI testing for: Android, iOS, OS X, Linux and MSVC and a small regression problem GTest using the scikit "Boston housing data". 

I hope it helps.
