### ISSUE TITLE
Mac installation error with gcc-6

### ISSUE THREAD

**Issue by tyrant0604** [dmlc/xgboost#2270]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.
according to this tutorial 
https://www.ibm.com/developerworks/community/blogs/jfp/entry/Installing_XGBoost_on_Mac_OSX?lang=en
with this "brew install gcc --without-multilib", the installation of default version of gcc is gcc-7 and xgboost can't be compiled. Then gcc-7 is replaced by gcc-6 with "brew install gcc@6".
I have tried for many times, it's always the following error info.

## Environment info
Operating System:
Darwin APPLE.local 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64

Compiler:
/usr/local/bin/g++-6 -c -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -O3 -funroll-loops -msse2 -fPIC -fopenmp src/tree/updater_prune.cc -o build/tree/updater_prune.o
In file included from dmlc-core/include/dmlc/timer.h:21:0,
                 from src/tree/updater_fast_hist.cc:7:
dmlc-core/include/dmlc/./logging.h: In instantiation of 'dmlc::LogCheckError dmlc::LogCheck_GT(const X&, const Y&) [with X = long unsigned int; Y = int]':
src/tree/updater_fast_hist.cc:298:7:   required from 'bool xgboost::tree::FastHistMaker<TStats, TConstraint>::Builder::UpdatePredictionCache(const xgboost::DMatrix*, std::vector<float>*) [with TStats = xgboost::tree::GradStats; TConstraint = xgboost::tree::NoConstraint]'
src/tree/updater_fast_hist.cc:87:61:   required from 'bool xgboost::tree::FastHistMaker<TStats, TConstraint>::UpdatePredictionCache(const xgboost::DMatrix*, std::vector<float>*) const [with TStats = xgboost::tree::GradStats; TConstraint = xgboost::tree::NoConstraint]'
src/tree/updater_fast_hist.cc:937:1:   required from here
dmlc-core/include/dmlc/./logging.h:91:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
dmlc-core/include/dmlc/./logging.h:76:9:
     if (x op y) return LogCheckError();                           \
         ~~~~~~
dmlc-core/include/dmlc/./logging.h:91:24:
 DEFINE_CHECK_FUNC(_GT, >)

dmlc-core/include/dmlc/./logging.h:76:11: note: in definition of macro 'DEFINE_CHECK_FUNC'
     if (x op y) return LogCheckError();                           \
            ^~
/usr/local/bin/g++-6 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/tree/updater_refresh.o src/tree/updater_refresh.cc >build/tree/updater_refresh.d
/usr/local/bin/g++-6 -c -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -O3 -funroll-loops -msse2 -fPIC -fopenmp src/tree/updater_refresh.cc -o build/tree/updater_refresh.o

Package used (python/R/jvm/C++):
anaconda Command line client (version 1.6.0)
python 3.6

`xgboost` version used:

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`):98ea46153223ce3539da1e8e18d9858f3d88639c
2. Logs will be helpful (If logs are large, please upload as attachment).

If you are using python package, please provide

1. The python version and distribution
2. The command to install `xgboost` if you are not installing from source

If you are using R package, please provide

1. The R `sessionInfo()`
2. The command to install `xgboost` if you are not installing from source

## Steps to reproduce

1.
2.
3.

## What have you tried?

1.
2.
3.

**Comment by SimonAB** [comment]
until this is fixed, you can revert to gcc-6 in homebrew using:
`brew switch gcc 6.3.0_1`
