### ISSUE TITLE
train with xgb_model option crashes

### ISSUE THREAD

**Issue by clockwiser** [dmlc/xgboost#2272]
When using xgb_model to try a continuous training, it crashes with a segmentation error.

## Environment info
Operating System:
ubuntu 16.04
Compiler:
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

Package used (python/R/jvm/C++):
python
`xgboost` version used:
newest from github, or pip installed 0.6a2

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`)
"98ea46153223ce3539da1e8e18d9858f3d88639c"
2. Logs will be helpful (If logs are large, please upload as attachment).
No related log. Segmentation error and crashes with no other messages. 
If you are using python package, please provide

1. The python version and distribution
2.7
2. The command to install `xgboost` if you are not installing from source
pip install xgboost
If you are using R package, please provide

1. The R `sessionInfo()`
2. The command to install `xgboost` if you are not installing from source

## Steps to reproduce

1. Train xgboost to get booster without xgb_model option.
bst = xgb.train(......)
2. Save the booster to a local file.
bst.save_model("xgb.model")
3. Load file to the booster
bst2 = xgb.Booster(model_file='xgb.model')
4. Train again with xgb_model option and crashes.

## What have you tried?

1. Tried pip version and github version, but same problem.
2.
3.

**Comment by ernest-s** [comment]
I had the same issue. But later I found out that I had given the num_classes parameter as 3 whereas in the dataset I had 6 classes. When I changed the value from 3 to 6, I was able to run the model.
