### ISSUE TITLE
potential issue about need_prune function

### ISSUE THREAD

**Issue by SauceCat** [dmlc/xgboost#2283]
Based on the documentation, the gain for a split is represented as:  

<img src='https://i.stack.imgur.com/kBsh8.png'>

Doesn't it mean that the gain should be at least twice larger than **gamma**? (Because of the factor 1/2) But when I check the source code, it only requires the gain to be larger than **gamma**.
```cpp
/*! \brief given the loss change, whether we need to invoke pruning */
inline bool need_prune(double loss_chg, int depth) const {
  return loss_chg < this->min_split_loss;
}
```
I am very confused. Did I make some mistakes in understanding the code? Or requiring the gain to be larger than **gamma** instead of twice larger than **gamma** is just a kind of approximation? 
Any help is appreciated!

**Comment by khotilov** [comment]
See #665

**Comment by SauceCat** [comment]
Thank you so much @khotilov
