### ISSUE TITLE
xgboost in R and Python are different

### ISSUE THREAD

**Issue by f496328mm** [dmlc/xgboost#2284]
python
http://imgur.com/Z9qB7B3

R
http://imgur.com/bu5RN3D   

i use xgboost by iris data

xgboost in python is better than r

xgb in python, round is 1 times, but
xgb in r, round is 7 times

and, testing error and training error, python is better than r 
------------------------------------------------------------------------------
my xgb version of r and python is 0.6

why xgboost in python and r are different ???

thank you
謝謝

**Comment by f496328mm** [comment]
https://github.com/f496328mm/xgb_python_vs_r

**Comment by Laurae2** [comment]
You can't compare both because you are not using the same folds for R and Python. Also, you have the RNG which is different.
