### ISSUE TITLE
xgboost split_info differs for sparse and dense binary features

### ISSUE THREAD

**Issue by Zelazny7** [dmlc/xgboost#2285]
The split info output from xgboost models trained on sparse, binary data matrix does not match the output when trained on a dense matrix:

### Reproducible example:

```
library(xgboost)

data(iris)

sparse <- sparse.model.matrix(Petal.Length~.-1, data=iris)
dense <- model.matrix(Petal.Length~.-1, data=iris)

head(sparse)

6 x 6 sparse Matrix of class "dgCMatrix"
  Sepal.Length Sepal.Width Petal.Width Speciessetosa Speciesversicolor Speciesvirginica
1          5.1         3.5         0.2             1                 .                .
2          4.9         3.0         0.2             1                 .                .
3          4.7         3.2         0.2             1                 .                .
4          4.6         3.1         0.2             1                 .                .
5          5.0         3.6         0.2             1                 .                .
6          5.4         3.9         0.4             1                 .                .

head(dense)

  Sepal.Length Sepal.Width Petal.Width Speciessetosa Speciesversicolor Speciesvirginica
1          5.1         3.5         0.2             1                 0                0
2          4.9         3.0         0.2             1                 0                0
3          4.7         3.2         0.2             1                 0                0
4          4.6         3.1         0.2             1                 0                0
5          5.0         3.6         0.2             1                 0                0
6          5.4         3.9         0.4             1                 0                0

all.equal(dense, as.matrix(sparse), check.attributes=F)
```

The matrices are identical except for one being sparse and the other dense. There are three binary indicator columns in each matrix. The other values are numeric.

### Train an xgboost model on each

```
train_sparse <- xgb.DMatrix(sparse, label=iris$Petal.Length)
train_dense <- xgb.DMatrix(dense, label=iris$Petal.Length)

set.seed(100)
mod_sparse <- xgboost(train_sparse, nrounds=1)

set.seed(100)
mod_dense <- xgboost(train_dense, nrounds=1)

xgb.model.dt.tree(colnames(sparse), mod_sparse)
xgb.model.dt.tree(colnames(dense), mod_dense)
```

Each model is trained with the same settings and the same seed. The output for the sparse matrix is so:

```
 xgb.model.dt.tree(colnames(sparse), mod_sparse)
   Tree Node  ID           Feature        Split Yes  No Missing    Quality Cover
1:    0    0 0-0       Petal.Width          0.8 0-1 0-2     0-1 385.787000   150
2:    0    1 0-1              Leaf           NA  NA  NA      NA   0.282941    50
3:    0    2 0-2 Speciesversicolor -9.53674e-07 0-3 0-4     0-3  22.069500   100
4:    0    3 0-3              Leaf           NA  NA  NA      NA   1.485880    50
5:    0    4 0-4              Leaf           NA  NA  NA      NA   1.105880    50
```

Notice the split for `Speciesversicolor`. It is this very small negative value: -9.53674e-07. If I build a larger tree, the split_info for binary indicator columns is **Always** this value.

Compare this to the output for a dense matrix where the split value is 0.5 which is what should be expected.

```
xgb.model.dt.tree(colnames(dense), mod_dense)
   Tree Node  ID           Feature Split Yes  No Missing    Quality Cover
1:    0    0 0-0       Petal.Width   0.8 0-1 0-2     0-1 385.787000   150
2:    0    1 0-1              Leaf    NA  NA  NA      NA   0.282941    50
3:    0    2 0-2 Speciesversicolor   0.5 0-3 0-4     0-3  22.069500   100
4:    0    3 0-3              Leaf    NA  NA  NA      NA   1.485880    50
5:    0    4 0-4              Leaf    NA  NA  NA      NA   1.105880    50
```

## Environment info
Operating System: os x El Capitan 10.11

Compiler: NA

Package used (python/R/jvm/C++): R

`xgboost` version used:  xgboost_0.6-0

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`)
2. Logs will be helpful (If logs are large, please upload as attachment).

If you are using python package, please provide

1. The python version and distribution
2. The command to install `xgboost` if you are not installing from source

If you are using R package, please provide

installed from CRAN

sessionInfo():

R version 3.3.1 (2016-06-21)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] xgboost_0.6-0     onehot_0.1.1.9000 Matrix_1.2-7.1   

loaded via a namespace (and not attached):
[1] magrittr_1.5      tools_3.3.1       Rcpp_0.12.10      stringi_1.1.3     grid_3.3.1       
[6] data.table_1.10.0 lattice_0.20-34  

## Steps to reproduce

1. Train any model using a sparse matrix with binary features
2. dump the model or convert to DT
3. See that split values are very small negative numbers

## What have you tried?

1. I have tried running on different OSs. Confirmed it also happens on Windows 7 with R 3.4
2. 
3.

**Comment by volker48** [comment]
Yeah, I noticed the same thing and opened #2737. Did you figure anything out? I've been looking at the C API and I can't figure out why this is happening.

**Comment by khotilov** [comment]
https://github.com/dmlc/xgboost/search?utf8=%E2%9C%93&q=sparse+dense+missing&type=Issues
I'm also adding it to FAQ https://github.com/dmlc/xgboost/pull/2732/commits/0604851f28529a4eace2922cd797572912dc9c38
