### ISSUE TITLE
[jvm-package] spark log only show train-auc, without test-auc

### ISSUE THREAD

**Issue by cnglen** [dmlc/xgboost#2289]
17/05/09 00:06:55 INFO RabitTracker$TrackerProcessLogger: 2017-05-09 00:06:55,014 INFO [703]	train-auc:0.992958
17/05/09 00:06:55 INFO RabitTracker$TrackerProcessLogger: 2017-05-09 00:06:55,930 INFO [704]	train-auc:0.992974

Does this should happen?

**Comment by CodingCat** [comment]
It's in training phase?

**Comment by cnglen** [comment]
Yes, in the training phase, 

> XGBoostEstimator.fit(dataset: Dataset[_]): XGBoostModel

In python's API : xgb.cv outputs  "train-auc=..., test-auc=...". I just found xgb.cv is supported in python's API.

One more questions, how can i do feature selection in xgboost4j-spark? I think the booster.getFeatureScore() only count's the number of used in spliting for each feature, Not the feature importane of gain.

Thanks.

**Comment by CodingCat** [comment]
that's by design 

we only monitor training set, https://github.com/dmlc/xgboost/blob/master/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala#L134

no...xgboost4j-spark does not have this feature
