### ISSUE TITLE
successfully built and installed but can't import

### ISSUE THREAD

**Issue by dyln** [dmlc/xgboost#2291]
after 2 days of struggle i have managed to build and install xgboost with exact codes at installation guide.
it looks well:  `pip list` and `conda list` shows `xgboost (0.6)`.
but when i try to run a code from Spyder:
`from xgboost import XGBClassifier`
IPhython console returns:
```
Traceback (most recent call last):

  File "<ipython-input-4-9b31cfdb821c>", line 1, in <module>
    from xgboost import XGBClassifier

  File "/Users/canereren/Documents/workspace/Machine Learning A-Z /Part 10 - Model Selection & Boosting/Section 49 - XGBoost/xgboost.py", line 30, in <module>
    from xgboost import XGBClassifier

ImportError: cannot import name 'XGBClassifier'
```
weirdly, i can import if i type manually from python console in terminal

python ver: 3.6 anaconda
spyder ver: 3.14
osx 10.12.4

please help, please....

**Comment by phunterlau** [comment]
Can you check the PATH in the notebook?

**Comment by dyln** [comment]
it is working now, after xcode update.

**Comment by rajumsds** [comment]
@dyln what did you do to work?

**Comment by Jerryzhuht** [comment]
@dyln  Met the same problem(Also the student of Machine Learning A-Z lol) but wondering how to solve it. I didn't install Xcode on my mac.

**Comment by ashimagarg** [comment]
I am facing the same problem. What did you to solve the problem? 
Please help..

**Comment by manichandrasekaran** [comment]
@dyln  how did you resolve the problem? I am facing the same problem. Successfully installed but cannot import the packages

**Comment by taymourniazi** [comment]
same here can you please explain

**Comment by dyln** [comment]
@rajumsds  @manichandrasekaran @taymourniazi i have updated the xcode to latest version as i said.

**Comment by adeepmalmotra** [comment]
@dyln  how to update the xcode in windows?
