### ISSUE TITLE
xgboost building error - Makefile:117: recipe for target 'build/data/simple_dmatrix.o' failed

### ISSUE THREAD

**Issue by cpn28** [dmlc/xgboost#2294]
Hi all.

I am trying to build an xgboost lib and during the process the following error is occured:

**Makefile:117: recipe for target 'build/data/simple_dmatrix.o' failed
mingw32-make: *** [build/data/simple_dmatrix.o] Error 1
mingw32-make: *** Waiting for unfinished jobs....**

Entire log file is here:
[xgb_building_log.txt](https://github.com/dmlc/xgboost/files/999397/xgb_building_log.txt)

I am using Windows 8.1 and Python 2.7. The instalation is guided by [article](https://www.ibm.com/developerworks/community/blogs/jfp/entry/Installing_XGBoost_For_Anaconda_on_Windows?lang=ru).

The error is happening than I run the comand:
![2017 05 14 17-01-11](https://cloud.githubusercontent.com/assets/28687264/26034549/0936f3ac-38c7-11e7-8eff-97be5033c00f.jpg)

I have no idea how this can be fixed. Please help!

**Comment by jlguerreiro** [comment]
Hi,

I am having the exact same problem. I'm using Windows 7 and Python 2.7.
Does anyone have a way to fix it?

**Comment by se-l** [comment]
including same:
[build_log.txt](https://github.com/dmlc/xgboost/files/1015363/build_log.txt)

tried with compilers:
tdm64-gcc-5.1.0-2
x86_64-5.3.0-posix-seh-rt_v4-rev0
x86_64-6.3.0-posix-seh-rt_v5-rev2
x86_64-7.1.0-posix-seh-rt_v5-rev0

Makefile:117: recipe for target 'build/data/sparse_page_raw_format.o' failed
mingw32-make: *** [build/data/sparse_page_raw_format.o] Error 1
Makefile:117: recipe for target 'build/data/simple_dmatrix.o' failed
mingw32-make: *** [build/data/simple_dmatrix.o] Error 1
Makefile:117: recipe for target 'build/data/data.o' failed
mingw32-make: *** [build/data/data.o] Error 1

also followed hints:
[here](https://www.ibm.com/developerworks/community/blogs/jfp/entry/Installing_XGBoost_For_Anaconda_on_Windows?lang=en)
[here](https://www.ibm.com/developerworks/community/blogs/jfp/entry/Installing_XGBoost_For_Anaconda_on_Windows?lang=en)
[issue 1267](https://github.com/dmlc/xgboost/issues/1267)

believe once it showed less errors with x86_64-7.1.0-posix-seh-rt_v5-rev0 and separate dmlc and rabit compilation, but import in python 3.6.1 failed as described [here: dynamic link library missing](https://github.com/dmlc/xgboost/issues/1059)

any hints much appreciated and thanks to contributors working on this a lot
