### ISSUE TITLE
Anaconda install xgboost version 0.6 bugs

### ISSUE THREAD

**Issue by titmy** [dmlc/xgboost#2299]
XGboost.plot_importance is missing a max_num_features parameter. 

AttributeError: Unknown property max_num_features
plot_importance(booster, ax, height, xlim, ylim, title, xlabel, ylabel, importance_type, grid, **kwargs)

**Comment by 000Nelson000** [comment]
I got the exact same issue.

**Comment by mingwandroid** [comment]
Despite the title of the documentation [webpage](http://xgboost.readthedocs.io/en/latest/python/python_api.html#module-xgboost.plotting) ("Python API Reference - xgboost 0.6 documentation"), it does not contain the documentation for the 0.6 release of `xgboost`. Instead it *seems* to contain the documentation for the latest git master branch.

The 0.6 release of `xgboost` was made on [Jul 29 2016](https://github.com/dmlc/xgboost/releases/tag/v0.60):

```
This is a stable release of 0.6 version

@tqchen tqchen released this on Jul 29 2016 · 245 commits to master since this release
```

The commit that  added `plot_importance()`'s `max_num_features`was made on [Jan 16 2017](https://github.com/dmlc/xgboost/commit/a7d28337669cf51eec40086b7e0ab362df5b0316):

As a further check, let's inspect the 0.60 release tarball:

```
pushd /tmp
curl -SLO https://github.com/dmlc/xgboost/archive/v0.60.tar.gz
tar -xf v0.60.tar.gz 
grep num_features xgboost-0.60/python-package/xgboost/plotting.py
# .. silence.
```

Therefore this seems to be a documentation bug with the `xgboost` project.

**Comment by AuroraLHT** [comment]
I got the same issue. Have try build it directly from the source code and installing it via conda.

**Comment by KseniaErshova** [comment]
Same thing, max_num_features doesn't work even after pip install -U xgboost.

**Comment by zjplab** [comment]
I checked the code in the folder named py-xgboost-0.60-py36np112h982e225_0, the plot_importance function is stated as:
`plot_importance(booster,` ax, height, xlim, ylim, title, xlabel, ylabel, importance_type, grid, **kwargs)`
no argument for max_num_features at all
