### ISSUE TITLE
[jvm-packages] xgboost spark training hangs when not all tasks run at the same time

### ISSUE THREAD

**Issue by Seanspt** [dmlc/xgboost#2307]
## Environment info

AWS EMR emr-5.5.0 with hadoop and spark installed
1 master, 2 core, 3 task isntances. Master and core instances are c3.xlarge, task instances are m3.xlarge

Package used (python/R/jvm/C++): jvm

`xgboost` version used: 08a3d56065741d1e9673588cb78496edfd4e1255

## Steps to reproduce
1.
```bash
 spark-shell --num-executors 8 --executor-cores 4 --conf spark.shuffle.service.enabled=false --conf spark.dynamicAllocation.enabled=false --jars $XGBOOST_JARS
```
2.
```scala
scala> val df = spark.sqlContext.read.format("libsvm").load("s3://$MyBucket//agaricus.txt.train")
df: org.apache.spark.sql.DataFrame = [label: double, features: vector]          

scala> import ml.dmlc.xgboost4j.scala.spark.XGBoostEstimator
import ml.dmlc.xgboost4j.scala.spark.XGBoostEstimator

scala> val paramMap = Map[String, Any]("objective" -> "binary:logistic", "nworkers" -> 33)
paramMap: scala.collection.immutable.Map[String,Any] = Map(objective -> binary:logistic, nworkers -> 33)

scala> val est = new XGBoostEstimator(paramMap)
est: ml.dmlc.xgboost4j.scala.spark.XGBoostEstimator = XGBoostEstimator_2791e76ab309

scala> est.fit(df)
Tracker started, with env={DMLC_NUM_SERVER=0, DMLC_TRACKER_URI=10.0.0.52, DMLC_TRACKER_PORT=9091, DMLC_NUM_WORKER=33}
[Stage 2:>                                                        (0 + 32) / 33]
```
## Tried
Set nworkers to 8*4 = 32.

**Comment by CodingCat** [comment]
can you add [jvm-packages] in the title when you ask about jvm questions?

**Comment by CodingCat** [comment]
in total you have 12 cores????

**Comment by Seanspt** [comment]
In emr cluster, core and task nodes are available for running tasks.
2 core nodes of c3.xlarge have 8 vCPUs (4 each), and 3 task nodes have 24 vCPUs (8 each).

So in total there are 32 vCores in my cluster, so as shown in the Hadoop Resource Manager WebUI.

**Comment by Seanspt** [comment]
The paramMap used is as following.
```scala
val paramMap = Map[String, Any]("objective" -> "binary:logistic", "nworkers" -> 33)
```

**Comment by CodingCat** [comment]
So your program is waiting for 33 tasks to start at the same time since it needs allreduce to sync stat

**Comment by Seanspt** [comment]
Yes. 
Is it possible to make ONE round of boosting as an action in spark and start training with a partition regardless of the stat of others, after which is done, the core would be available to other partitions. So work could be done, even if there are not enough cores.

**Comment by CodingCat** [comment]
no, that's not how allreduce algorithm works

**Comment by Seanspt** [comment]
Ok thanks, I'll close the issue then.

**Comment by kushNumberTheory** [comment]
@Seanspt i am able to start my tracker. But i always get warning of

WARN XGBoostSpark: Unable to read total number of alive cores from REST API.Health Check will be ignored.
java.io.IOException: Server returned HTTP response code: 500 for URL: 

Whats the  issue?
Also i always get Warning of

 WARN servlet.ServletHandler:
javax.servlet.ServletException: Could not determine the proxy server for redirection

**Comment by CodingCat** [comment]
it does not matter, something wrong with your driver rest api, it should not affect the running

**Comment by kushNumberTheory** [comment]
@CodingCat 
XGBoost Spark uses spark over rabit. Basically spark handles all distributed task and work.
Rabit will reduce overhead of allocating yarn resources again. Also it wont do reduce operation everytime.
What's the use of nWorkers in trainWithDataFrame API.
Does it handle distribution of data ? If yes,then what spark does in this case?
If it is more than 1, then it will create seperate instance for every executor or conatainer?
From the code , it repartition the data on the basis of workers, why we do that as spark handle distribution and parallelism?
I have read code and gone through rabit journal also... but its so confusing, WHY do we need rabit when we have spark?
