### ISSUE TITLE
install error : "error: unknown type name 'ISerializable'; did you mean 'Serializable'?"

### ISSUE THREAD

**Issue by ohnabe** [dmlc/xgboost#231]
I would like to install "xgboost"  in my Mac(OSX 10.10.2).
I ran "devtools::install_github('dmlc/xgboost',subdir='R-package')" , but failed with below error messages.

--------------------
../..//subtree/rabit/src/engine_empty.cc:37:30: error: unknown type name 'ISerializable'; did you mean 'Serializable'?
  virtual int LoadCheckPoint(ISerializable *global_model,
                             ^~~~~~~~~~~~~
                             Serializable
...
5 errors generated.
make: *** [../..//subtree/rabit/src/engine_empty.o] Error 1
ERROR: compilation failed for package ‘xgboost’
--------------------

My R version is R version 3.1.3 (2015-03-09) -- "Smooth Sidewalk"
Copyright (C) 2015 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin13.4.0 (64-bit)

How do i fix it?
Best regards,

**Comment by ahara** [comment]
I've the same error under Ubuntu 14.04 (64-bit) and R 3.1.3.

It looks that it's caused by one of the last commits because command below works fine.

```
devtools::install_github('dmlc/xgboost#230',subdir='R-package')
```

**Comment by tqchen** [comment]
Sorry about this issue, the newest commit fixed it
