### ISSUE TITLE
Windows Install/Build issue - learner.o, c_api.o, mutex, build/logging...

### ISSUE THREAD

**Issue by Berowne** [dmlc/xgboost#2310]
Difficulty building XGBoost in Windows... 

## Environment info
Operating System: Windows 7

Compiler:
C:\...\mingw-w64\4.0.2\mingw64\bin\make.exe

Package used (python/R/jvm/C++):
Python 2.7.11 

`xgboost` version used:
dmlc/xgboost 0.6a2

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`)
a607f697e37035a16a9d42496ec2b5f2e1affe41

2. Logs will be helpful (If logs are large, please upload as attachment).
**Problem mingw32-make fails after creating alias. alias make='mingw32-make'
-O3 -funroll-loops -msse2 -fopenmp src/learner.cc -o build/learner.o
In file included from src/c_api/c_api_error.cc:6:0:
dmlc-core/include/dmlc/thread_local.h:76:8: error: 'mutex' in namespace 'std' does not name a type
   std::mutex mutex_;

Makefile:117: recipe for target 'build/c_api/c_api.o' failed
mingw32-make: *** [build/c_api/c_api.o] Error 1

If you are using python package, please provide

1. The python version and distribution. 
Python 2.7.11 from anaconda 4.1.1 and ipython 4.2.0
2. The command to install `xgboost` if you are not installing from source
XXX Source.

## Steps to reproduce

1. read http://xgboost.readthedocs.io/en/latest/build.html
2. setup git proxy and download via git
3. git init/update
4. setup make alias
5. try MAKE.

## What have you tried?

1. MAKEING XGBoost
2. WHY is it so hard
3. PIP Install would be nice, perhaps fork for GPU/NOGPU? 
[urgh.txt](https://github.com/dmlc/xgboost/files/1010200/urgh.txt)

**Comment by metacube-shivang** [comment]
Facing the same issue... :(

**Comment by khotilov** [comment]
It looks like your gcc compiler is too old. Run `gcc -v` to see the version. For gcc you need minimum v4.8.
make.exe is not a compiler, it is a build tool.
