### ISSUE TITLE
Multiclassification training process

### ISSUE THREAD

**Issue by naxokite** [dmlc/xgboost#2313]
Hi all, I would like to ask about a more detailed explanation about the training process for multi class target variables (such as[ this one](http://homes.cs.washington.edu/~tqchen/pdf/BoostedTree.pdf) for binary).
if the target variable has 3 levels, I understand it trains 3 binary "one vs other" boosters in each iteration but I would like to understand both the interaction between these booster's training both inside the same iteration and between iterations.
While in round X, once one of the 3 is trained, do these leaf scores get used for the other 2 (label training order would influence a lot) or no? Are the objective functions of those trees binary? (not mlogloss but logloss for this binary class only)? When next round begins, each booster receives scores from every single tree trained before or just the ones corresponding to its own class? (related to the obj function being binary or not)

I couldn't find any detailed documentation around so if any is available please share.

Thanks a lot in advance.

Best.

**Comment by naxokite** [comment]
Why is this closed? You could have answered when you entered to close this.

**Comment by hcho3** [comment]
Since I feel that this is useful question for many people, I migrated your post to the forum: https://discuss.xgboost.ai/t/multiclassification-training-process/29

**Comment by tqchen** [comment]
Answered in the forum
