### ISSUE TITLE
[jvm-packages] Distributed training accuracy issue

### ISSUE THREAD

**Issue by mdymczyk** [dmlc/xgboost#2318]
I failed to find any benchmarks/notes on how the training accuracy is affected in a distributed setting, are there any?

I've been running some tests on the Airlines dataset and in a distributed setting I'm getting an order of magnitude worse results (single node ~4% error, distributed ~20% error rate with the same parameters). Is this to be expected or should the accuracy be more or less the same?

Some info:

* building XGBoost from [this commit]( https://github.com/dmlc/xgboost/commit/6bf968efe6e430615578a90eb56ea455b3a2ff2e)
* gcc version 5.4.0 on Ubuntu
* `Rabit.getWorldSize()` returns a proper cluster size, I see lots of logs saying that workers are starting/finishing the job
* DMatrix creation is done after `Rabit.init(rt.getEnv())`
* I'm simply running `XGBoost.train(matrix, ...)` on each node

I tried running XGBoost-Spark tests but all of them are running on a really small dataset which can be easily trained to a 0% error rate even when using only part of it.

**Comment by CodingCat** [comment]
can you test with airline data with xgboost-spark? I once tried that and didn't find too much accuracy skew

**Comment by mdymczyk** [comment]
Sure might try over the weekend or early next week if I find some time.

**Comment by mdymczyk** [comment]
@CodingCat right, seems the distributed version should work fine - at least those were the results I got. Seems my `XGBoost.train()` is working in single node mode even though `Rabit.getWorldSize()` returns 2, `Rabit.allreduce()` works fine, and was properly initialized but that's a different issue (I didn't have while running Spark tests).
