### ISSUE TITLE
Different predictions for Python and C API

### ISSUE THREAD

**Issue by ptrblck** [dmlc/xgboost#2322]
Hi,

there seems to be a difference between the predictions from the Python API (using XGBClassifier) vs. the C API (xgboost.learner->Predict()).

I developed a XGBClassifier model in python and tried to deploy it to a C++ application on a RPi.
The trained model was saved using
``` 
model = XGBClassifier(
        learning_rate=0.1,
        n_estimators=150,
        max_depth=5,
        min_child_weight=1,
        gamma=0
        ... )

model.fit(dtrain, target, eval_metric='auc')
model._Booster.save_model(model_file)
 ```

This model was loaded into the C++ application by using
```
std::unique_ptr<dmlc::Stream> fi(
                dmlc::Stream::Create("PATH_TO_MODEL", "r"));
    learner->Load(fi.get());
```

The feature matrix was calculated separately in python and C++, therefore differs a little bit, probably due to rounding errors.

The C++ application is predicting the feature matrix with
```
DMatrixHandle feat;
int sucess = XGDMatrixCreateFromMat( (float *)fullFeatureList.data(), rows, cols, NAN, &feat);

std::vector<float> preds;
learner->Predict(static_cast<std::shared_ptr<xgboost::DMatrix>*>(feat)->get(), false, &preds, 150);
```

These features as well as the predictions are saved to log files to compare it afterwards with the python solution.

The attached python file compares the predictions from C++ with predictions from python.

First, the features calculated in C++, its corresponding predictions, the features calculated in Python and the model, are loaded.

After that, the model is used to calculate predictions for the C++ features and Python features.
These predictions are compared to the predictions calculated in the C++ application.

Even though the C++ features differ a bit from the Python features, the model predicts almost the same probabilities. (Plotting both predictions shows more or less the same line).
However, the C++ predictions are way off. 

![xgb_bug](https://cloud.githubusercontent.com/assets/11662379/26252953/004523b0-3cb2-11e7-8076-c3c7d8397736.png)

This issue seems not to come from the possible rounding errors in both feature matrices (c++ vs. python), because the XGBClassifier predicts almost the same probabilities for both of them.

I also tried to load the trained model in C++, calculated predictions, which were still off, saved the model and loaded it into python, where the model seems to work flawlessly.

The .zip file contains:
- python code (find_the_bug.py)
- features calculated in C++ (cpp_features.txt)
- features calculated in Python (py_features.npy)
- probabilities calculated in the C++ application (cpp_probs.txt)
- xgb model used for prediction (xgb_test.model)

The python script repeats the abovementioned tests.
[bug.zip](https://github.com/dmlc/xgboost/files/1014587/bug.zip)

Let me know, if you need more information regarding this issue.

Greets,
Piotr

## Environment info
Operating System: Ubuntu 16.04 LTS

Compiler: Python 2.7 / GCC 5.4

Package used (python/R/jvm/C++): Python, C++

`xgboost` version used: 0.6

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`): 98ea46153223ce3539da1e8e18d9858f3d88639c

If you are using python package, please provide

1. The python version and distribution: Python 2.7, Anaconda
2. The command to install `xgboost` if you are not installing from source: pip install xgboost

**Comment by p-siegel** [comment]
I have the same issue!

**Comment by ptrblck** [comment]
Issue can be closed, since I found a bug in the C++ solution regarding the length of my feature vector.
Now, the predictions are exactly the same again.

**Comment by snailcoder** [comment]
@p-siegel What's your data format in training? libsvm or dense matrix? XGBoost FAQ says
"“Sparse” elements are treated as if they were “missing” by the tree booster, and as zeros by the linear booster. For tree models, it is important to use consistent data formats during training and scoring."

After I make the format of training and testing data consistent, Python and C++ solution give the same predictions!
