### ISSUE TITLE
Feature importances for multiclass wth linear booster

### ISSUE THREAD

**Issue by jakehoare** [dmlc/xgboost#2331]
The R code below predicts a variable with 3 categories based on 2 predictor variables.
The output has 6 rows: features from 1 to 6 and their associated weights. I expected 2 rows, which is the case with tree booster.

How do I interpret the 6 rows of output in terms of the importances of the 2 predictor variables?
Is there somehow a weight for each predictor variable for each class?

I tried asking on [stackoverflow ](http://stackoverflow.com/questions/43973476/xgboost-multiclass-predicton-with-linear-booster) but no reply so far.

```
y <- c(0, 1, 2, 0, 1, 2)        # target variable with numeric encoding
x1 <- c(1, 3, 5, 3, 5, 7)
x2 <- rnorm(n = 6, sd = 1) + x1
df <- data.matrix(data.frame(x1, x2, y))

xgb <- xgboost(data = df[, c("x1", "x2")], label = df[, "y"],
           params = list(booster = "gblinear", objective = "multi:softmax", num_class = 3),
           save_period = NULL, nrounds = 1)

imp <- xgb.importance(model = xgb)
```

**Comment by khotilov** [comment]
The 6 = 3 * 2 numbers are linear coefficients of 3 linear submodels corresponding to the 3 classes in a multinomial logistic regression. The ordering is broken in the current CRAN release. With the fix that I've committed yesterday, the order should be proper as follows: 
b_x1_y0, b_x1_y1, b_x1_y2, b_x2_y0, b_x2_y1, b_x2_y2
Technically, they are not importances that would allow you to rank features, unless your columns were normalized to be on the same scale.

And, apparently, the xgb.importance for multiclass gblinear is broken in the recent code. I'll fix that...

For gbtree, when you are not specifying for multiclass case which trees to include into the calculation of importance, you are clumping all the classes together, which might or might not be what you need.

**Comment by jakehoare** [comment]
That's useful thanks, just what I was looking for
