### ISSUE TITLE
problem about categorical variables to Numeric 

### ISSUE THREAD

**Issue by yangl326-Dylan** [dmlc/xgboost#2335]
i have read the article here http://xgboost.readthedocs.io/en/latest/R-package/discoverYourData.html#one-hot-encoding. 
it suggest to using one-hot encoding method to transform categorical variables to Numeric. for example,feature Sex into is_male[0,1] and is_female[0,1]. if i transform Sex male to 0, and transform Sex female to 1， and not add the feature number. what's the difference between this two methods. I know the second one may be ordered among these feature values, so if this affect the result of the training model?

**Comment by khotilov** [comment]
Please check the in the "Encoding categorical features" section in the [vignette](https://github.com/dmlc/xgboost/blob/master/R-package/vignettes/discoverYourData.Rmd) which I've modified earlier to be more clear about this concept. I didn't realize that there was another discoverYourData under doc/R-package/
