### ISSUE TITLE
Windows7 "Error: unknown evaluation metric type: mlogloss"

### ISSUE THREAD

**Issue by darraghdog** [dmlc/xgboost#234]
Hi,
I can run xgboost on R when I set the "eval_metric" = "logloss"; however when I set it "eval_metric" = "mlogloss" is gives the error seen in subject. I am workingon the kaggle otto challenge, which is multiclass -  I presume working with the logloss evaluation metric would give me a suboptimal score. I am working on a Windows 7 4 core, more details of the operating system attached in the picture. 

The package versions I have are : > packageVersion("devtools") : [1] ‘1.7.0’ > packageVersion("xgboost") : [1] ‘0.3.3’. 
I tried sourcing the package from the github and the CRAN archive. For reference I paste below the log from installing xgboost package in R. 

> install.packages("~/R/win-library/3.1/xgboost_0.3-3.tar.gz", repos = NULL, type = "source")
Installing package into ‘C:/Users/Think/Documents/R/win-library/3.1’
(as ‘lib’ is unspecified)
* installing *source* package 'xgboost' ...
** package 'xgboost' successfully unpacked and MD5 sums checked
** libs

*** arch - i386
g++ -m32 -I"C:/PROGRA~1/R/R-31~1.2/include" -DNDEBUG -DXGBOOST_CUSTOMIZE_MSG_ -DXGBOOST_CUSTOMIZE_PRNG_ -DXGBOOST_STRICT_CXX98_ -DRABIT_CUSTOMIZE_MSG_ -DRABIT_STRICT_CXX98_ -I.    -I"d:/RCompile/CRANpkg/extralibs64/local/include"  -fopenmp   -O2 -Wall  -mtune=core2 -c xgboost_R.cpp -o xgboost_R.o
gcc -m32 -I"C:/PROGRA~1/R/R-31~1.2/include" -DNDEBUG -DXGBOOST_CUSTOMIZE_MSG_ -DXGBOOST_CUSTOMIZE_PRNG_ -DXGBOOST_STRICT_CXX98_ -DRABIT_CUSTOMIZE_MSG_ -DRABIT_STRICT_CXX98_ -I.    -I"d:/RCompile/CRANpkg/extralibs64/local/include"     -O3 -Wall  -std=gnu99 -mtune=core2 -c xgboost_assert.c -o xgboost_assert.o
g++ -m32 -I"C:/PROGRA~1/R/R-31~1.2/include" -DNDEBUG -DXGBOOST_CUSTOMIZE_MSG_ -DXGBOOST_CUSTOMIZE_PRNG_ -DXGBOOST_STRICT_CXX98_ -DRABIT_CUSTOMIZE_MSG_ -DRABIT_STRICT_CXX98_ -I.    -I"d:/RCompile/CRANpkg/extralibs64/local/include"  -fopenmp   -O2 -Wall  -mtune=core2 -c wrapper/xgboost_wrapper.cpp -o wrapper/xgboost_wrapper.o
g++ -m32 -I"C:/PROGRA~1/R/R-31~1.2/include" -DNDEBUG -DXGBOOST_CUSTOMIZE_MSG_ -DXGBOOST_CUSTOMIZE_PRNG_ -DXGBOOST_STRICT_CXX98_ -DRABIT_CUSTOMIZE_MSG_ -DRABIT_STRICT_CXX98_ -I.    -I"d:/RCompile/CRANpkg/extralibs64/local/include"  -fopenmp   -O2 -Wall  -mtune=core2 -c src/io/io.cpp -o src/io/io.o
g++ -m32 -I"C:/PROGRA~1/R/R-31~1.2/include" -DNDEBUG -DXGBOOST_CUSTOMIZE_MSG_ -DXGBOOST_CUSTOMIZE_PRNG_ -DXGBOOST_STRICT_CXX98_ -DRABIT_CUSTOMIZE_MSG_ -DRABIT_STRICT_CXX98_ -I.    -I"d:/RCompile/CRANpkg/extralibs64/local/include"  -fopenmp   -O2 -Wall  -mtune=core2 -c src/gbm/gbm.cpp -o src/gbm/gbm.o
g++ -m32 -I"C:/PROGRA~1/R/R-31~1.2/include" -DNDEBUG -DXGBOOST_CUSTOMIZE_MSG_ -DXGBOOST_CUSTOMIZE_PRNG_ -DXGBOOST_STRICT_CXX98_ -DRABIT_CUSTOMIZE_MSG_ -DRABIT_STRICT_CXX98_ -I.    -I"d:/RCompile/CRANpkg/extralibs64/local/include"  -fopenmp   -O2 -Wall  -mtune=core2 -c src/tree/updater.cpp -o src/tree/updater.o
In file included from src/tree/updater.cpp:8:0:
src/tree/./updater_colmaker-inl.hpp: In member function 'void xgboost::tree::ColMaker<TStats>::Builder::UpdateSolution(const xgboost::ColBatch&, const std::vector<xgboost::bst_gpair>&, const xgboost::IFMatrix&, const xgboost::BoosterInfo&) [with TStats = xgboost::tree::GradStats]':
src/tree/./updater_colmaker-inl.hpp:465:9:   instantiated from 'void xgboost::tree::ColMaker<TStats>::Builder::FindSplit(int, const std::vector<int>&, const std::vector<xgboost::bst_gpair>&, xgboost::IFMatrix*, const xgboost::BoosterInfo&, xgboost::tree::RegTree*) [with TStats = xgboost::tree::GradStats]'
src/tree/./updater_colmaker-inl.hpp:91:9:   instantiated from 'void xgboost::tree::ColMaker<TStats>::Builder::Update(const std::vector<xgboost::bst_gpair>&, xgboost::IFMatrix*, const xgboost::BoosterInfo&, xgboost::tree::RegTree*) [with TStats = xgboost::tree::GradStats]'
src/tree/./updater_colmaker-inl.hpp:37:7:   instantiated from 'void xgboost::tree::ColMaker<TStats>::Update(const std::vector<xgboost::bst_gpair>&, xgboost::IFMatrix*, const xgboost::BoosterInfo&, const std::vector<xgboost::tree::RegTree*>&) [with TStats = xgboost::tree::GradStats]'
src/tree/updater.cpp:34:1:   instantiated from here
src/tree/./updater_colmaker-inl.hpp:425:9: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
src/tree/./updater_colmaker-inl.hpp:465:9:   instantiated from 'void xgboost::tree::ColMaker<TStats>::Builder::FindSplit(int, const std::vector<int>&, const std::vector<xgboost::bst_gpair>&, xgboost::IFMatrix*, const xgboost::BoosterInfo&, xgboost::tree::RegTree*) [with TStats = xgboost::tree::GradStats]'
src/tree/./updater_colmaker-inl.hpp:91:9:   instantiated from 'void xgboost::tree::ColMaker<TStats>::Builder::Update(const std::vector<xgboost::bst_gpair>&, xgboost::IFMatrix*, const xgboost::BoosterInfo&, xgboost::tree::RegTree*) [with TStats = xgboost::tree::GradStats]'
src/tree/./updater_colmaker-inl.hpp:37:7:   instantiated from 'void xgboost::tree::ColMaker<TStats>::Update(const std::vector<xgboost::bst_gpair>&, xgboost::IFMatrix*, const xgboost::BoosterInfo&, const std::vector<xgboost::tree::RegTree*>&) [with TStats = xgboost::tree::GradStats]'
src/tree/updater.cpp:34:1:   instantiated from here
src/tree/./updater_colmaker-inl.hpp:421:17: warning: variable 'batch_size' set but not used [-Wunused-but-set-variable]
g++ -m32 -I"C:/PROGRA~1/R/R-31~1.2/include" -DNDEBUG -DXGBOOST_CUSTOMIZE_MSG_ -DXGBOOST_CUSTOMIZE_PRNG_ -DXGBOOST_STRICT_CXX98_ -DRABIT_CUSTOMIZE_MSG_ -DRABIT_STRICT_CXX98_ -I.    -I"d:/RCompile/CRANpkg/extralibs64/local/include"  -fopenmp   -O2 -Wall  -mtune=core2 -c subtree/rabit/src/engine_empty.cc -o subtree/rabit/src/engine_empty.o
g++ -m32 -shared -s -static-libgcc -o xgboost.dll tmp.def xgboost_R.o xgboost_assert.o ./wrapper/xgboost_wrapper.o ./src/io/io.o ./src/gbm/gbm.o ./src/tree/updater.o ./subtree/rabit/src/engine_empty.o -fopenmp -Ld:/RCompile/CRANpkg/extralibs64/local/lib/i386 -Ld:/RCompile/CRANpkg/extralibs64/local/lib -LC:/PROGRA~1/R/R-31~1.2/bin/i386 -lR
installing to C:/Users/Think/Documents/R/win-library/3.1/xgboost/libs/i386

*** arch - x64
g++ -m64 -I"C:/PROGRA~1/R/R-31~1.2/include" -DNDEBUG -DXGBOOST_CUSTOMIZE_MSG_ -DXGBOOST_CUSTOMIZE_PRNG_ -DXGBOOST_STRICT_CXX98_ -DRABIT_CUSTOMIZE_MSG_ -DRABIT_STRICT_CXX98_ -I.    -I"d:/RCompile/CRANpkg/extralibs64/local/include"  -fopenmp   -O2 -Wall  -mtune=core2 -c xgboost_R.cpp -o xgboost_R.o
gcc -m64 -I"C:/PROGRA~1/R/R-31~1.2/include" -DNDEBUG -DXGBOOST_CUSTOMIZE_MSG_ -DXGBOOST_CUSTOMIZE_PRNG_ -DXGBOOST_STRICT_CXX98_ -DRABIT_CUSTOMIZE_MSG_ -DRABIT_STRICT_CXX98_ -I.    -I"d:/RCompile/CRANpkg/extralibs64/local/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c xgboost_assert.c -o xgboost_assert.o
g++ -m64 -I"C:/PROGRA~1/R/R-31~1.2/include" -DNDEBUG -DXGBOOST_CUSTOMIZE_MSG_ -DXGBOOST_CUSTOMIZE_PRNG_ -DXGBOOST_STRICT_CXX98_ -DRABIT_CUSTOMIZE_MSG_ -DRABIT_STRICT_CXX98_ -I.    -I"d:/RCompile/CRANpkg/extralibs64/local/include"  -fopenmp   -O2 -Wall  -mtune=core2 -c wrapper/xgboost_wrapper.cpp -o wrapper/xgboost_wrapper.o
g++ -m64 -I"C:/PROGRA~1/R/R-31~1.2/include" -DNDEBUG -DXGBOOST_CUSTOMIZE_MSG_ -DXGBOOST_CUSTOMIZE_PRNG_ -DXGBOOST_STRICT_CXX98_ -DRABIT_CUSTOMIZE_MSG_ -DRABIT_STRICT_CXX98_ -I.    -I"d:/RCompile/CRANpkg/extralibs64/local/include"  -fopenmp   -O2 -Wall  -mtune=core2 -c src/io/io.cpp -o src/io/io.o
g++ -m64 -I"C:/PROGRA~1/R/R-31~1.2/include" -DNDEBUG -DXGBOOST_CUSTOMIZE_MSG_ -DXGBOOST_CUSTOMIZE_PRNG_ -DXGBOOST_STRICT_CXX98_ -DRABIT_CUSTOMIZE_MSG_ -DRABIT_STRICT_CXX98_ -I.    -I"d:/RCompile/CRANpkg/extralibs64/local/include"  -fopenmp   -O2 -Wall  -mtune=core2 -c src/gbm/gbm.cpp -o src/gbm/gbm.o
g++ -m64 -I"C:/PROGRA~1/R/R-31~1.2/include" -DNDEBUG -DXGBOOST_CUSTOMIZE_MSG_ -DXGBOOST_CUSTOMIZE_PRNG_ -DXGBOOST_STRICT_CXX98_ -DRABIT_CUSTOMIZE_MSG_ -DRABIT_STRICT_CXX98_ -I.    -I"d:/RCompile/CRANpkg/extralibs64/local/include"  -fopenmp   -O2 -Wall  -mtune=core2 -c src/tree/updater.cpp -o src/tree/updater.o
In file included from src/tree/updater.cpp:8:0:
src/tree/./updater_colmaker-inl.hpp: In member function 'void xgboost::tree::ColMaker<TStats>::Builder::UpdateSolution(const xgboost::ColBatch&, const std::vector<xgboost::bst_gpair>&, const xgboost::IFMatrix&, const xgboost::BoosterInfo&) [with TStats = xgboost::tree::GradStats]':
src/tree/./updater_colmaker-inl.hpp:465:9:   instantiated from 'void xgboost::tree::ColMaker<TStats>::Builder::FindSplit(int, const std::vector<int>&, const std::vector<xgboost::bst_gpair>&, xgboost::IFMatrix*, const xgboost::BoosterInfo&, xgboost::tree::RegTree*) [with TStats = xgboost::tree::GradStats]'
src/tree/./updater_colmaker-inl.hpp:91:9:   instantiated from 'void xgboost::tree::ColMaker<TStats>::Builder::Update(const std::vector<xgboost::bst_gpair>&, xgboost::IFMatrix*, const xgboost::BoosterInfo&, xgboost::tree::RegTree*) [with TStats = xgboost::tree::GradStats]'
src/tree/./updater_colmaker-inl.hpp:37:7:   instantiated from 'void xgboost::tree::ColMaker<TStats>::Update(const std::vector<xgboost::bst_gpair>&, xgboost::IFMatrix*, const xgboost::BoosterInfo&, const std::vector<xgboost::tree::RegTree*>&) [with TStats = xgboost::tree::GradStats]'
src/tree/updater.cpp:34:1:   instantiated from here
src/tree/./updater_colmaker-inl.hpp:425:9: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
src/tree/./updater_colmaker-inl.hpp:465:9:   instantiated from 'void xgboost::tree::ColMaker<TStats>::Builder::FindSplit(int, const std::vector<int>&, const std::vector<xgboost::bst_gpair>&, xgboost::IFMatrix*, const xgboost::BoosterInfo&, xgboost::tree::RegTree*) [with TStats = xgboost::tree::GradStats]'
src/tree/./updater_colmaker-inl.hpp:91:9:   instantiated from 'void xgboost::tree::ColMaker<TStats>::Builder::Update(const std::vector<xgboost::bst_gpair>&, xgboost::IFMatrix*, const xgboost::BoosterInfo&, xgboost::tree::RegTree*) [with TStats = xgboost::tree::GradStats]'
src/tree/./updater_colmaker-inl.hpp:37:7:   instantiated from 'void xgboost::tree::ColMaker<TStats>::Update(const std::vector<xgboost::bst_gpair>&, xgboost::IFMatrix*, const xgboost::BoosterInfo&, const std::vector<xgboost::tree::RegTree*>&) [with TStats = xgboost::tree::GradStats]'
src/tree/updater.cpp:34:1:   instantiated from here
src/tree/./updater_colmaker-inl.hpp:421:17: warning: variable 'batch_size' set but not used [-Wunused-but-set-variable]
g++ -m64 -I"C:/PROGRA~1/R/R-31~1.2/include" -DNDEBUG -DXGBOOST_CUSTOMIZE_MSG_ -DXGBOOST_CUSTOMIZE_PRNG_ -DXGBOOST_STRICT_CXX98_ -DRABIT_CUSTOMIZE_MSG_ -DRABIT_STRICT_CXX98_ -I.    -I"d:/RCompile/CRANpkg/extralibs64/local/include"  -fopenmp   -O2 -Wall  -mtune=core2 -c subtree/rabit/src/engine_empty.cc -o subtree/rabit/src/engine_empty.o
g++ -m64 -shared -s -static-libgcc -o xgboost.dll tmp.def xgboost_R.o xgboost_assert.o ./wrapper/xgboost_wrapper.o ./src/io/io.o ./src/gbm/gbm.o ./src/tree/updater.o ./subtree/rabit/src/engine_empty.o -fopenmp -Ld:/RCompile/CRANpkg/extralibs64/local/lib/x64 -Ld:/RCompile/CRANpkg/extralibs64/local/lib -LC:/PROGRA~1/R/R-31~1.2/bin/x64 -lR
installing to C:/Users/Think/Documents/R/win-library/3.1/xgboost/libs/x64
Warning in file.copy(files, dest, overwrite = TRUE) :
  problem copying .\xgboost.dll to C:\Users\Think\Documents\R\win-library\3.1\xgboost\libs\x64\xgboost.dll: Permission denied
** R
** data
** demo
** inst
** preparing package for lazy loading
Note: the specification for S3 class "AsIs" in package 'RJSONIO' seems equivalent to one from package 'jsonlite': not turning on duplicate class definitions for this class.
Creating a generic function from function 'getinfo' in package 'xgboost'
Creating a generic function for 'predict' from package 'stats' in package 'xgboost'
Creating a generic function from function 'setinfo' in package 'xgboost'
Creating a generic function from function 'slice' in package 'xgboost'
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
*** arch - i386
Note: the specification for S3 class "AsIs" in package 'RJSONIO' seems equivalent to one from package 'jsonlite': not turning on duplicate class definitions for this class.
*** arch - x64
Note: the specification for S3 class "AsIs" in package 'RJSONIO' seems equivalent to one from package 'jsonlite': not turning on duplicate class definitions for this class.
* DONE (xgboost)
![screenhunter_61 apr 11 08 01](https://cloud.githubusercontent.com/assets/7209588/7100548/080404f8-e021-11e4-8d71-fbccb495511e.jpg)

**Comment by tqchen** [comment]
Use the lastest version from github. see instruction here https://github.com/dmlc/xgboost/tree/master/R-package

**Comment by darraghdog** [comment]
When I try to install from : devtools::install_github('dmlc/xgboost',subdir='R-package')
I get the below error when running xgboost()....

 Error in .Call("XGDMatrixNumRow_R", dmat, PACKAGE = "xgboost") : 
  "XGDMatrixNumRow_R" not available for .Call() for package "xgboost"

**Comment by pommedeterresautee** [comment]
Do you have the last version fo devtools?
Just installed the package on Windows 8 64 bits for tests, and it works.

Another solution (the one I use all the time) is to clone the code on windows, then create a project in RStudio, set RPackage as the main folder, and push the button build of RStudio. Tied too, and it works. No devtools to take care of, if you choose this way.

Kind regards,
Michaël

**Comment by tqchen** [comment]
Since there was no updates in this issue, I am closing it for now
