### ISSUE TITLE
Set_base_margin for multiclass

### ISSUE THREAD

**Issue by TomekTarczynski** [dmlc/xgboost#235]
Is it possible in XGBoost to boost from prediction in multiclass problem? I've tried this in python (I've modified script boost_from_prediction) but for multiclass it seems that it doesnt work and I'm not sure whether this is python issue or XGBoost. I manage to calculate predictions with output margin, but during set_base_margin I encounter following error:

"df2.set_base_margin(pred)
Traceback (most recent call last):

  File "<ipython-input-9-d1557edf45e5>", line 1, in <module>
    df2.set_base_margin(pred)

  File "D:\Xgboost\xgboost.py", line 226, in set_base_margin
    self.set_float_info('base_margin', margin)

  File "D:\Xgboost\xgboost.py", line 177, in set_float_info
    c_array(ctypes.c_float, data), len(data))

  File "D:\Xgboost\xgboost.py", line 86, in c_array
    return (ctype * len(values))(*values)

TypeError: only length-1 arrays can be converted to Python scalars"

Should I just convert 2D array into 1D array and pass it?

**Comment by tqchen** [comment]
Yes, this is something we overlooked when designing the interface, you should be able to set_margin with flattened array.

But be aware that the prediction you get must be obtained with ```output_margin=True```

**Comment by tqchen** [comment]
I am supposing the question is answered, and close this issue for now.

**Comment by jaysonpryde** [comment]
hi there... I am encountering the same error. I did np.flatten(), but I am having XGBoostError: label set cannot be empty when I call the xgb.train. There were no problems when I do the set_base_margin for both dtrain and dtest. Can you kindly help me out here? Thanks in advance!

**Comment by jaysonpryde** [comment]
I reinstalled xgboost (0.4 version). I am having this error now ... src/learner.cc:460: Check failed: (preds.size()) == (base_margin.size()) base_margin.size does not match with prediction size

**Comment by jaysonpryde** [comment]
I tried to flatten it again using np.flatten()... I got the original error XGBoostError: [18:56:18] src/metric/multiclass_metric.cc:26: Check failed: (info.labels.size()) != (0) label set cannot be empty... Can you kindly help me out here?

**Comment by syllogismos** [comment]
@jaysonpryde instead of np.flatten() flatten it using `reshape(-1,1)`

so `pred = pred.reshape(-1, 1)`

I found this issue when I also faced the same issue, I added more details in this stackoverflow answer http://stackoverflow.com/questions/41042599/how-to-boost-on-an-existing-xgboost-model-from-its-last-iteration-without-starti/41043439#41043439
