### ISSUE TITLE
[jvm-packages] problems with tracker while building xgboost-spark4j

### ISSUE THREAD

**Issue by encore137** [dmlc/xgboost#2352]
## Environment info
Operating System:
Windows 7(64 bit)
**gcc**
gcc version 4.8.1 (rev5, Built by MinGW-W64 project)
**mingw32-make**
GNU Make 3.99.90
Built for Windows32
Copyright (C) 1988-2012 Free Software Foundation, Inc
Package used (python/R/jvm/C++):
jvm
`xgboost` version used:
0.7

I have problems while building xgboost-spark4j package.
According to logs the main problem is tracker.
it shows something like this:
**Tracker started, with env={}**
i tried different version of python(2.7.13, 3.5, 3.6) but the problem is the same.
Added full logs.
[logCleanInstall2713.txt](https://github.com/dmlc/xgboost/files/1035320/logCleanInstall2713.txt)
[log2713_1.txt](https://github.com/dmlc/xgboost/files/1035321/log2713_1.txt)
[log36.txt](https://github.com/dmlc/xgboost/files/1035322/log36.txt)

**Comment by encore137** [comment]
Some new info:
**This happens because script tracker.py crashes**
Traceback (most recent call last):
  File "tracker.py", line 480, in <module>
    main()
  File "tracker.py", line 475, in main
    start_rabit_tracker(args)
  File "tracker.py", line 437, in start_rabit_tracker
    rabit = RabitTracker(hostIP=get_host_ip(args.host_ip), nslave=args.num_workers)
  File "tracker.py", line 147, in __init__
    sock.bind((hostIP, port))
  File "C:\Users\ilya.rabotaev\AppData\Local\Continuum\Anaconda2\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 10013] ╤фхырэр яюя√Єър фюёЄєяр ъ ёюъхЄє ьхЄюфюь,
Exception AttributeError: "'RabitTracker' object has no attribute 'sock'" in <bound method RabitTracker.__del__ of <__mai
n__.RabitTracker object at 0x0000000002561BE0>> ignored

**Some problems with socket connection i guess(no permissions).**
But when i run it with another host-ip:

**python tracker.py --num-workers 2 --host-ip 127.0.0.1**

it shows:

2017-05-29 19:22:14,075 INFO start listen on 127.0.0.1:9091
DMLC_TRACKER_ENV_START
DMLC_TRACKER_URI=127.0.0.1
DMLC_NUM_SERVER=0
DMLC_TRACKER_PORT=9091
DMLC_NUM_WORKER=2
DMLC_TRACKER_ENV_END

and hangs.
@CodingCat is it normal?
When i change the host-ip in ml.dmlc.xgboost4j.java RabitTracker to another ip (not that spark starts its driver) in method **startTrackerProcess**  i get the same situation - it hangs:

Discovery starting.
Discovery completed in 483 milliseconds.
Run starting. Expected test count is: 35
XGBoostDFSuite:
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
17/05/29 19:13:54 INFO SparkContext: Running Spark version 2.1.0
17/05/29 19:13:55 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
17/05/29 19:13:55 INFO SecurityManager: Changing view acls to: ilya.rabotaev
17/05/29 19:13:55 INFO SecurityManager: Changing modify acls to: ilya.rabotaev
17/05/29 19:13:55 INFO SecurityManager: Changing view acls groups to:
17/05/29 19:13:55 INFO SecurityManager: Changing modify acls groups to:
17/05/29 19:13:55 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(ilya.rabotaev); groups with view permissions: Set(); users  with modify permissions: Set(ilya.rabotaev); groups with modify permissions: Set()
17/05/29 19:13:55 INFO Utils: Successfully started service 'sparkDriver' on port 63637.
17/05/29 19:13:55 INFO SparkEnv: Registering MapOutputTracker
17/05/29 19:13:55 INFO SparkEnv: Registering BlockManagerMaster
17/05/29 19:13:55 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
17/05/29 19:13:55 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
17/05/29 19:13:55 INFO DiskBlockManager: Created local directory at C:\Users\ilya.rabotaev\AppData\Local\Temp\blockmgr-1ab4e9e6-bc5e-4405-8ef3-7cde06ccf405
17/05/29 19:13:55 INFO MemoryStore: MemoryStore started with capacity 897.6 MB
17/05/29 19:13:55 INFO SparkEnv: Registering OutputCommitCoordinator
17/05/29 19:13:56 INFO Utils: Successfully started service 'SparkUI' on port 4040.
17/05/29 19:13:56 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://10.100.177.46:4040
17/05/29 19:13:56 INFO Executor: Starting executor ID driver on host localhost
17/05/29 19:13:56 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 63658.
17/05/29 19:13:56 INFO NettyBlockTransferService: Server created on 10.100.177.46:63658
17/05/29 19:13:56 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
17/05/29 19:13:56 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 10.100.177.46, 63658, None)
17/05/29 19:13:56 INFO BlockManagerMasterEndpoint: Registering block manager 10.100.177.46:63658 with 897.6 MB RAM, BlockManagerId(driver, 10.100.177.46, 63658, None)
17/05/29 19:13:56 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 10.100.177.46, 63658, None)
17/05/29 19:13:56 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 10.100.177.46, 63658, None)
Tracker started, with env={DMLC_NUM_SERVER=0, DMLC_TRACKER_URI=127.0.0.1, DMLC_TRACKER_PORT=9091, DMLC_NUM_WORKER=4}

**Comment by CodingCat** [comment]
can you try scala-based tracker by setting 

"tracker_conf" to TrackerConf(60 * 60 * 1000, "scala")

?

**Comment by encore137** [comment]
@CodingCat 
i changed file jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/**GeneralParams.scala**, line 105:

**trackerConf -> TrackerConf(60 * 60 * 1000, "scala")**

Now i see this (seems that Scala tracker is used):

XGBoostDFSuite:
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
17/05/30 10:44:01 INFO SparkContext: Running Spark version 2.1.0
17/05/30 10:44:02 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
17/05/30 10:44:02 INFO SecurityManager: Changing view acls to: ilya.rabotaev
17/05/30 10:44:02 INFO SecurityManager: Changing modify acls to: ilya.rabotaev
17/05/30 10:44:02 INFO SecurityManager: Changing view acls groups to:
17/05/30 10:44:02 INFO SecurityManager: Changing modify acls groups to:
17/05/30 10:44:02 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(ilya.rabotaev); groups with view permissions: Set(); users  with modify permissions: Set(ilya.rabotaev); groups with modify permissions: Set()
17/05/30 10:44:02 INFO Utils: Successfully started service 'sparkDriver' on port 49647.
17/05/30 10:44:02 INFO SparkEnv: Registering MapOutputTracker
17/05/30 10:44:02 INFO SparkEnv: Registering BlockManagerMaster
17/05/30 10:44:02 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
17/05/30 10:44:02 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
17/05/30 10:44:02 INFO DiskBlockManager: Created local directory at C:\Users\ilya.rabotaev\AppData\Local\Temp\blockmgr-cb4dfae7-4f0a-4b47-b4e5-514ad47b95cc
17/05/30 10:44:02 INFO MemoryStore: MemoryStore started with capacity 897.6 MB
17/05/30 10:44:03 INFO SparkEnv: Registering OutputCommitCoordinator
17/05/30 10:44:03 INFO Utils: Successfully started service 'SparkUI' on port 4040.
17/05/30 10:44:03 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://10.100.177.46:4040
17/05/30 10:44:03 INFO Executor: Starting executor ID driver on host localhost
17/05/30 10:44:03 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 49668.
17/05/30 10:44:03 INFO NettyBlockTransferService: Server created on 10.100.177.46:49668
17/05/30 10:44:03 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
17/05/30 10:44:03 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 10.100.177.46, 49668, None)
17/05/30 10:44:03 INFO BlockManagerMasterEndpoint: Registering block manager 10.100.177.46:49668 with 897.6 MB RAM, BlockManagerId(driver, 10.100.177.46, 49668, None)
17/05/30 10:44:03 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 10.100.177.46, 49668, None)
17/05/30 10:44:03 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 10.100.177.46, 49668, None)
[INFO] [05/30/2017 10:44:08.851] [RabitTracker-akka.actor.default-dispatcher-2] [akka://RabitTracker/user/Handler] Tracker listening @ 10.100.177.46:49612
[INFO] [05/30/2017 10:44:08.851] [RabitTracker-akka.actor.default-dispatcher-2] [akka://RabitTracker/user/Handler] Worker connection timeout is 1 hour.

and still nothing happens.

**Comment by encore137** [comment]
after time is out it shows:

- test consistency and order preservation of dataframe-based model *** FAILED ***
  ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed
  at ml.dmlc.xgboost4j.scala.spark.XGBoost$.postTrackerReturnProcessing(XGBoost.scala:320)
  at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainWithRDD(XGBoost.scala:298)
  at ml.dmlc.xgboost4j.scala.spark.XGBoostEstimator.train(XGBoostEstimator.scala:121)
  at ml.dmlc.xgboost4j.scala.spark.XGBoostEstimator.train(XGBoostEstimator.scala:36)
  at org.apache.spark.ml.Predictor.fit(Predictor.scala:96)
  at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainWithDataFrame(XGBoost.scala:189)
  at ml.dmlc.xgboost4j.scala.spark.XGBoostDFSuite$$anonfun$2.apply$mcV$sp(XGBoostDFSuite.scala:79)
  at ml.dmlc.xgboost4j.scala.spark.XGBoostDFSuite$$anonfun$2.apply(XGBoostDFSuite.scala:57)
  at ml.dmlc.xgboost4j.scala.spark.XGBoostDFSuite$$anonfun$2.apply(XGBoostDFSuite.scala:57)
  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
  ...

[INFO] [05/30/2017 12:05:45.176] [RabitTracker-akka.actor.default-dispatcher-6] [akka://RabitTracker/user/Handler] Tracker listening @ 10.100.177.46:54332
[INFO] [05/30/2017 12:05:45.176] [RabitTracker-akka.actor.default-dispatcher-6] [akka://RabitTracker/user/Handler] Worker connection timeout is 2 minutes.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] xgboost-jvm ........................................ SUCCESS [  3.921 s]
[INFO] xgboost4j .......................................... SUCCESS [ 14.477 s]
[INFO] xgboost4j-spark .................................... FAILURE [02:27 min]
[INFO] xgboost4j-flink .................................... SKIPPED
[INFO] xgboost4j-example .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:46 min
[INFO] Finished at: 2017-05-30T12:05:46+03:00
[INFO] Final Memory: 29M/613M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.scalatest:scalatest-maven-plugin:1.0:test (test) on project xgboost4j-spark: There are test failures -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :xgboost4j-spark

**Comment by CodingCat** [comment]
it looks like you have some problem in the communication for the processes running in your local host....have you ever tried to run some simple socket program in your host? even can you ping yourself?

**Comment by foocraft** [comment]
I am having a similar hanging issue on Windows but not on Linux. After the boosters are built in XGBoost.scala in the spark package, the logs clearly show the job is finished, but it seems that waiting for the tracker to indicate that it finished never happens on Windows.

The code I suspect is here in: `xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala`:
```scala
    val sparkJobThread = new Thread() {
      override def run() {
        // force the job
        boosters.foreachPartition(() => _)
      }
    }
    sparkJobThread.setUncaughtExceptionHandler(tracker)
    sparkJobThread.start()
    val isClsTask = isClassificationTask(params)
    val trackerReturnVal = tracker.waitFor(0L)
    logger.info(s"Rabit returns with exit code $trackerReturnVal")
    postTrackerReturnProcessing(trackerReturnVal, boosters, overridedConfMap, sparkJobThread,
      isClsTask)
```
The tests are hanging in Windows, and not in linux, as well.

**Comment by encore137** [comment]
@CodingCat 
i wrote a simple socket programm using akka. Everything is ok, no problems in processes communication.
i see that tracker always returns **TrackerStatus.FAILURE(3)**. i still can't understand why it happens:(

it looks very fishy, that in **RabitTracker.scala** in **waitFor(line153)** **futureCompleted** is always an empty List(). Is it normal?

**Comment by encore137** [comment]
@foocraft i get this errors on Windows too. Did you try to run it (re build shared lib and package jvm-packages) on Unix?

**Comment by foocraft** [comment]
I didn't try cross compiling for Windows on Linux, however, I did try recompiling xgboost4j.dll on Windows using Visual Studio 2017 for Win64 and using tdm-gcc. Both of them yield the same result which is: *after the spark job finishes, the train method doesn't return yet*. I suspect the `waitFor` call as you mentioned, but still don't understand why the wait doesn't yield on Windows, but works fine on Linux.

**Comment by encore137** [comment]
found one strange thing in ml.dmlc.xgboost4j.scala.spark.XGBoost, trainWithRDD:

```
val isClsTask = isClassificationTask(params)
    **val trackerReturnVal = tracker.waitFor(0L) // makes tracker wait for the infinite time**
    logger.info(s"Rabit returns with exit code $trackerReturnVal")
    postTrackerReturnProcessing(trackerReturnVal, boosters, overridedConfMap, sparkJobThread,
      isClsTask)
```

according to RabitTracker.scala 0L value makes tracker wait infinitely:

```
def waitFor(atMostMillis: Long): Int = {
    if (**atMostMillis <= 0**) {
      waitFor(Duration.Inf)
    } else {
      waitFor(Duration.fromNanos(atMostMillis * 1e6))
    }
  }
```
I changed 0L to 60000L and it goes further to another waitFor where the futureCompleted is always empty List(). Some strange things happen here.

**Comment by encore137** [comment]
@CodingCat 
it seems that workers do not start at all. Can you explain where(line in code) they are started? can't find it.
i see the RabitTrackerHandler actor starts, WorkerDependencyResolver actor start but no RabitWorkerHandler.
i see this code:
```
case Tcp.Connected(remote, local) =>
      log.info(s"Incoming connection from worker @ ${remote.getAddress.getHostAddress}")
      // revoke timeout if all workers have connected.
      val workerHandler = context.actorOf(RabitWorkerHandler.props(
        remote.getAddress.getHostAddress, numWorkers, self, sender()
      ), s"ConnectionHandler-${UUID.randomUUID().toString}")
      val connection = sender()
      connection ! Tcp.Register(workerHandler, keepOpenOnPeerClosed = true)

      actorRefToHost.put(workerHandler, remote.getAddress.getHostName)
  }
```
 in handleTcpEvents

but the only tcpEvent that is handled by RabitTrackerHandler is Tcp.Bound(when tracker is starting)

**Comment by foocraft** [comment]
Hi @encore137, is there any update on this issue? Have you been able to build without the tests hanging on Windows?

**Comment by encore137** [comment]
@foocraft, no result on Windows, decided to move to Unix, everything is fine on Ubuntu 17.04.

**Comment by foocraft** [comment]
@CodingCat I think in this case, this issue should be opened and described as a windows-only issue for now.
