### ISSUE TITLE
multi CPU performance problem

### ISSUE THREAD

**Issue by fayeshine** [dmlc/xgboost#2353]
I have 4 CPU, 4890v2, 15 cores per CPU.
However，I have not experienced faster computation speed using 60 threads.
What should be the potential reason for this?
@terrytangyuan @tqchen

**Comment by holyglenn** [comment]
Can you be more specific about the setting of your testing? Are they NUMA nodes, are they distributed, when did the speedup stop, how large of a dataset did you use? and the configuration?

**Comment by fayeshine** [comment]
@holyglenn ,not NUMA, not distributed, one mainboard, 4 CPU, e7 4890v2, total 60 physical cores. Running at 60 thread, No speedup compared to one i7 6900K pocessor. dataset have 100 features, 400M samples, param: 6000 trees, depth 10, eta 0.02, no other change. I see 6000% CPU usage on top, but the speed have not improved.

**Comment by fayeshine** [comment]
one single 6900K, 31s per iter; on 4 CPU, 15thread: 39s,  60thread: 35s,

**Comment by stolorz** [comment]
Which xgboost version have you used? If it was 0.6x, could you also measure speed using xgboost version 0.4x?

**Comment by fayeshine** [comment]
0.60 @stolorz

**Comment by khotilov** [comment]
OS? Compiler?

**Comment by edi-bice** [comment]
@fayeshine Are you running in distributed mode? If that is the case I'm having similar issues. Otherwise single node, such as demo/kaggle-higgs/speedtest.py show definite improvements from single threaded to 16 on a similar machine to yours (4 E5-2690V4 CPUs with 14 cores each).

**Comment by edi-bice** [comment]
Never mind. But I'm glad I looked up my CPU details for my earlier comments. Apparently specifying too many threads (via nthread parameter) seems to be detrimental. Once I lowered it from 64 to 16 it showed improved performance even in distributed mode (YARN). Each training iteration (not speedtest, my own) dropped from 20 to 4 seconds.

**Comment by edi-bice** [comment]
It's interesting though. In my dev cluster which is XEN virtualized and each node has 8 virtual cores, specifying 16 threads did not have the same detrimental effect as doing the same in the bare metal servers in prod. Trying to figure out via "ps -T -p <pid>" the actual number of threads and getting 24 in the dev case (I do specify num-cores=3 when submitting via YARN), so it is as if it succeeds in lowering my 16 threads specified in launch parameters down to the actual max virtual cores x job cores. Just a guess though as I don't yet know how YARN submission parameters are mapped to processes and threads.
