### ISSUE TITLE
[jvm-packages] sbt instead of Maven

### ISSUE THREAD

**Issue by superbobry** [dmlc/xgboost#2358]
Have you considered using sbt for building the JARs? It would allow to workaround Scala binary incompatibility issue and automatically  painlessly) build xgboost4j and other packages for multiple versions of Scala.

**Comment by CodingCat** [comment]
what's the concrete problem you met when using maven to build current code base?

**Comment by superbobry** [comment]
I am currently working on automatically building JARs for xgboost. Since xgboost is a Scala project, the resulting JARs are tied to the Scala release they were built with (2.11 by default). Therefore, the artifact names should (by convention) have binary tag, e.g. `xgboost4j_2.11` instead of just `xgboost4j`. 

You can do that in Maven using some find/sed magic (Spark does [exactly that](https://github.com/apache/spark/blob/master/dev/change-scala-version.sh)). However, since xgboost4j is a relatively small project, it might be easier to switch to sbt and get the binary tag behaviour out of the box. Bonus: it would [cross build](http://www.scala-sbt.org/release/docs/Cross-Build.html) the artifacts automatically.

**Comment by CodingCat** [comment]
I assume that using sbt to read pom.xml (like what Spark is doing) will achieve the same goal?

I do not want to change the build chain by replacing something regarding the existing users' convenience

if you are interested, would you mind giving it a try?

**Comment by superbobry** [comment]
Yep, I think this should be possible. I'll have a look.

**Comment by superbobry** [comment]
I've started working on his using [`sbt-pom-reader`](https://github.com/sbt/sbt-pom-reader). To my surprise, the project does not build with sbt. The reason for that is 2.10/2.11 conflict in one of the `xgboost4j-flink` dependencies. After some digging I've discovered that this is caused by a [broken](https://mvnrepository.com/artifact/org.apache.flink/flink-ml_2.11/0.10.2) `flink-ml` release. I'll submit a fix for that in the ->sbt branch.

**Comment by superbobry** [comment]
In the end, I've convinced myself that the POM reader plugin (#2743) is just too much of a burden for a small project like XGBoost. I've ported all the POM files in <1 hour (#2767) and, while there a few rough edges, it is mostly compatible feature-wise with the Maven build.
