### ISSUE TITLE
OpenMP not working in R on Mac OS X

### ISSUE THREAD

**Issue by eithompson** [dmlc/xgboost#2359]
## Environment info
Operating System: OS X Sierra 10.12.5

Compiler: gcc 7.1.0 (and a 5 version I had previously - forgot which one)

Package used (python/R/jvm/C++): R

`xgboost` version used: 0.6.4.5 

If installing from source, please provide 

commit hash: 8e2a1ff2bfd29f0d08c117d617fc0837eb6796cc

If you are using R package, please provide

sessionInfo():
`R version 3.4.0 (2017-04-21)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.5

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] xgboost_0.6.4.5

loaded via a namespace (and not attached):
[1] compiler_3.4.0    magrittr_1.5      Matrix_1.2-9      tools_3.4.0       stringi_1.1.5    
[6] grid_3.4.0        data.table_1.10.4 lattice_0.20-35  `

## Steps to reproduce/what have you tried?

1. Installed gcc using `brew reinstall gcc --without-multilib`
2. Followed directions [here](http://xgboost.readthedocs.io/en/latest/build.html#building-on-osx) (though the "NOTE" directions seem outdated - the makefile in xgboost doesn't mention any gcc-5 or gcc-6.)
3. Edited ~/.R/Makevars to point to 7.1.0 similar to the instructions [here](https://stackoverflow.com/a/38514224/4646107) and then installed from source as in [here](http://xgboost.readthedocs.io/en/latest/build.html#installing-the-development-version).

Before, I had gcc 5 and that also did not work. In both cases, throughout the installation, there are plenty of error messages like "warning: Warning: OpenMP is not available, project will be
      compiled into single-thread code. Use OpenMP-enabled compiler to get benefit of
      multi-threading".

I have also tried editing the Makefile as follows before installing:

`
OS := $(shell uname)
ifeq ($(OS), Darwin)
ifndef CC
export CC = /usr/local/Cellar/gcc/7.1.0
endif
`

but to no avail. I understand that people have had some issues with this in the past. Have recent changes made previous solutions not work?

**Comment by thirdwing** [comment]
Can you show your `~/.R/Makevars`?

**Comment by eithompson** [comment]
Sure. I basically followed the template (here)[https://stackoverflow.com/questions/35709524/how-to-make-r-package-xgboost-parallel-in-os-x-with-openmp-compilation/38514224#38514224].


CC=/usr/local/Cellar/gcc/7.1.0/bin/gcc-7
CXX=/usr/local/Cellar/gcc/7.1.0/bin/g++-7
SHLIB_CXXLD=/usr/local/Cellar/gcc/7.1.0/bin/g++-7
FC=/usr/local/Cellar/gcc/7.1.0/bin/gfortran-7
F77=/usr/local/Cellar/gcc/7.1.0/bin/gfortran-7
MAKE=make -j8

SHLIB_OPENMP_CFLAGS=-fopenmp
SHLIB_OPENMP_CXXFLAGS=-fopenmp
SHLIB_OPENMP_FCFLAGS=-fopenmp
SHLIB_OPENMP_FFLAGS=-fopenmp

**Comment by eithompson** [comment]
@thirdwing Hey, any update on this?

**Comment by Zex** [comment]
hi @eithompson , I'm not using R, but this works for me

https://github.com/Zex/xgboost/blob/sandbox/config/make/config.mk#L20-L24

**Comment by Oakwilde** [comment]
Apparently there has been a change in xgboost so that in R on a Mac it will not load. Seems like an OpenMP problem that has just surfaced. Suggestions? Thanks
