### ISSUE TITLE
MQ2008.rar cannot be downloaded because the file was moved

### ISSUE THREAD

**Issue by szdr** [dmlc/xgboost#2362]
To run xgboost/demo/rank/wgetdata.sh, MQ2008.rar would be downloaded.
Recently, the file has been moved and it cannot be downloaded with the script.
(The detail is [here](https://www.microsoft.com/en-us/research/project/letor-learning-rank-information-retrieval/?from=http%3A%2F%2Fresearch.microsoft.com%2Fen-us%2Fum%2Fbeijing%2Fprojects%2Fletor%2Fletor4.0%2Fdata%2Fmq2008.rar).)

Unfortunately, MQ2008.rar is hosted on [OneDrive](https://onedrive.live.com/?cid=8feadc23d838bda8&id=8FEADC23D838BDA8%21107&authkey=%21ACnoZZSZVfHPJd0), and we cannot get the link.

README.md and wgetdata.sh should be updated, but I don't know a good way.

**Comment by wulongfeng** [comment]
I google it and found the following website, hope this helps~
http://www.bigdatalab.ac.cn/benchmark/bm/dd?data=MQ2008
