### ISSUE TITLE
not-yet-implemented method for cbind2(<xgb.DMatrix>, <dgCMatrix>)

### ISSUE THREAD

**Issue by amarchin** [dmlc/xgboost#2365]
I am trying to use the `xgb.create.features` (R api) with an `xgb.DMatrix` object and I got the message:

    Errore: not-yet-implemented method for cbind2(<xgb.DMatrix>, <dgCMatrix>).
     ->>  Ask the package authors to implement the missing feature.

So I am just writing you to ask for the the feature implementation :)

**Comment by khotilov** [comment]
The `data` input to this function must be either `matrix` or `dgCMatrix`. It's not possible to add columns to an `xgb.DMatrix`.
