### ISSUE TITLE
how to write a c++ xgboost predictor

### ISSUE THREAD

**Issue by wugh** [dmlc/xgboost#2371]
Hi, all 

I write a xgboost predictor which build tree from xgboost dump file.
But I can not get same result as the python api.
## Train Model
```
def xgb_train(train_file, save_file, eval_file=None, num_round=10, param=None):
    if param is None:
        param = {
            'silent': 1,
            'objective': 'reg:logistic',
            'nthread': 32,
            'eval_metric': ['auc'],
        }

    dtrain = xgb.DMatrix(train_file, missing=np.nan)
    if eval_file is not None:
        deval = xgb.DMatrix(eval_file, missing=np.nan)
        eval_list = [(dtrain, 'train'), (deval, 'eval')]
    else:
        eval_list = [(dtrain, 'train')]

    bst = xgb.train(param, dtrain, num_round, eval_list)
    bst.save_model(save_file)
    bst.dump_model(save_file + ".raw")
xgb_train("train_data_path", "mode_name")
```
this code will generate two model file, one binary(mode_name), the other is raw text (model_name.raw).
I use model_name.raw to build tree in c++, and use binary model in python.

## Python Way
```
import xgboost as xgb
click_bst = xgb.Booster(model_file='binary_model_path')
feature_matrix = np.zeros((1, 60))
# here omit some code to generate feature matrix
xgb_matrix = xgb.DMatrix(feature_matrix, missing=np.nan)
click_bst.predict(xgb_matrix)
```

## C++ way
I build tree according to `text dump model`, then find leaf node for each tree based on `feature_matrix`, finally add all leaf node value to get the predict score.
But I found the score is quiet different to python result.
[Here is my c++ code](https://gist.github.com/wugh/25c156009cb02ce94d1c268ffd5c2db7).

I would like to know is it correct to add all leaf value to get the predict when my objective function is `reg:logistic`.

**Comment by yangl326-Dylan** [comment]
i have the same problem, do you know the reason?

**Comment by wugh** [comment]
@yangl326-Dylan I have find the problem.
You need to set the basic score to 0 if you use reg:logistic.
and Do sigmoid after sum all the score in the leaf.

**Comment by lwm345** [comment]
yes   
is the problem solved?
