### ISSUE TITLE
xgboost python does not display information even when silent = False

### ISSUE THREAD

**Issue by Wenchao-Yang** [dmlc/xgboost#2372]
I am using xgboost to train a model. I want it to print out some info about training process. However, it does not give me anything even if silent = False.

```
import xgboost as xgb
xgbc = xgb.XGBClassifier(
   gamma=0.1, learning_rate=0.05, max_delta_step=0, max_depth=8,
   min_child_weight=6, missing=None, n_estimators=250, nthread=8,
   objective='binary:logistic', reg_alpha=0, reg_lambda=1,
   scale_pos_weight=1, seed=0, silent=False, subsample=0.9)
xgbc.fit(X, y)
```

## Environment info
Operating System: OSX Yosemite Version 10.10.4

Package used (python/R/jvm/C++): python

`xgboost` version used: 0.6

1. The python version and distribution
2.7.9 (v2.7.9:648dcafa7e5f, Dec 10 2014, 10:10:46) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]

2. The command to install `xgboost` if you are not installing from source
I followed the instructions on this website in the section "Building on OSX":
http://xgboost.readthedocs.io/en/latest/build.html

**Comment by edi-bice** [comment]
try verbose_eval=True

**Comment by hiramf** [comment]
also missing output. 
verbose_eval=True returns unexpected keyword argument

using Python 3 on Windows 10 in Jupyter

**Comment by yclicc** [comment]
I had the same issue: No output was printed to the Jupyter notebook but there was output in the console window where I launched Jupyter.

**Comment by HuaGuo1992** [comment]
The same problem. Have you fixed it ?
