### ISSUE TITLE
Problem installing on Red Hat

### ISSUE THREAD

**Issue by MartinBarron** [dmlc/xgboost#238]
I hoping somone might help me with the error I get below.  I get it when I initially try to install the file.  

$ make
g++ -c -Wall -O3 -msse2  -Wno-unknown-pragmas -fPIC -fopenmp -o updater.o src/tree/updater.cpp
In file included from src/tree/././../utils/../sync/../../subtree/rabit/include/./rabit_serializable.h:12,
                 from src/tree/././../utils/../sync/../../subtree/rabit/include/rabit.h:20,
                 from src/tree/././../utils/../sync/sync.h:9,
                 from src/tree/././../utils/io.h:8,
                 from src/tree/././model.h:15,
                 from src/tree/./updater.h:11,
                 from src/tree/updater.cpp:5:
src/tree/././../utils/../sync/../../subtree/rabit/include/././dmlc/io.h: In constructor ‘dmlc::ostream::ostream(dmlc::Stream*, size_t)’:
src/tree/././../utils/../sync/../../subtree/rabit/include/././dmlc/io.h:153: error: class ‘dmlc::ostream’ does not have any field named ‘basic_ostream’
src/tree/././../utils/../sync/../../subtree/rabit/include/././dmlc/io.h:153: error: expected ‘(’ before ‘<’ token
src/tree/././../utils/../sync/../../subtree/rabit/include/././dmlc/io.h:153: error: no matching function for call to ‘dmlc::ostream::OutBuf::OutBuf()’
src/tree/././../utils/../sync/../../subtree/rabit/include/././dmlc/io.h:173: note: candidates are: dmlc::ostream::OutBuf::OutBuf(size_t)
src/tree/././../utils/../sync/../../subtree/rabit/include/././dmlc/io.h:171: note:                 dmlc::ostream::OutBuf::OutBuf(const dmlc::ostream::OutBuf&)
src/tree/././../utils/../sync/../../subtree/rabit/include/././dmlc/io.h:153: error: expected ‘{’ before ‘<’ token
src/tree/././../utils/../sync/../../subtree/rabit/include/././dmlc/io.h: In constructor ‘dmlc::istream::istream(dmlc::Stream*, size_t)’:
src/tree/././../utils/../sync/../../subtree/rabit/include/././dmlc/io.h:216: error: class ‘dmlc::istream’ does not have any field named ‘basic_istream’
src/tree/././../utils/../sync/../../subtree/rabit/include/././dmlc/io.h:216: error: expected ‘(’ before ‘<’ token
src/tree/././../utils/../sync/../../subtree/rabit/include/././dmlc/io.h:216: error: no matching function for call to ‘dmlc::istream::InBuf::InBuf()’
src/tree/././../utils/../sync/../../subtree/rabit/include/././dmlc/io.h:233: note: candidates are: dmlc::istream::InBuf::InBuf(size_t)
src/tree/././../utils/../sync/../../subtree/rabit/include/././dmlc/io.h:231: note:                 dmlc::istream::InBuf::InBuf(const dmlc::istream::InBuf&)
src/tree/././../utils/../sync/../../subtree/rabit/include/././dmlc/io.h:216: error: expected ‘{’ before ‘<’ token
make: *** [updater.o] Error 1

**Comment by tqchen** [comment]
pushed fix on this, please check if you can compile the newest version in github

**Comment by LiuSai-Dream** [comment]
I just install on red hat just now, with gcc 4.9

**Comment by MartinBarron** [comment]
Worked for me as well.  Thanks so much!
