### ISSUE TITLE
XGBoost is 10x slower when the index of sparse data is 10x larger

### ISSUE THREAD

**Issue by tobegit3hub** [dmlc/xgboost#2381]
It may be the issue about performance.

We have tried XGBoost with the official example code and data. Here is the script of training.

```
import xgboost as xgb
# read in data
dtrain = xgb.DMatrix('demo/data/agaricus.txt.train')
dtest = xgb.DMatrix('demo/data/agaricus.txt.test')
# specify parameters via map
param = {'max_depth':2, 'eta':1, 'silent':1, 'objective':'binary:logistic' }
num_round = 2
bst = xgb.train(param, dtrain, num_round)
# make prediction
preds = bst.predict(dtest)
```

And we modify the training data by adding the much larger index, just like this.

```
1 1:1 10:1 11:1 21:1 30:1 34:1 36:1 40:1 41:1 53:1 58:1 65:1 69:1 77:1 86:1 88:1 92:1 95:1 102:1 105:1 117:1 124:1 10000000:1
0 3:1 10:1 20:1 21:1 23:1 34:1 36:1 39:1 41:1 53:1 56:1 65:1 69:1 77:1 86:1 88:1 92:1 95:1 102:1 106:1 116:1 120:1
0 1:1 10:1 19:1 21:1 24:1 34:1 36:1 39:1 42:1 53:1 56:1 65:1 69:1 77:1 86:1 88:1 92:1 95:1 102:1 106:1 116:1 122:1
```

It took ~20 seconds when the index was up to `10000000` and took ~200 seconds when the index was `100000000:1`. Because the data is sparse and we don't expect it will be much slower when the index is larger.

## Environment info
Operating System: 

`Mac OSX`

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`)
2. Logs will be helpful (If logs are large, please upload as attachment).

`2d9052bc7dfc4d40e915820e0bede05c626b588d`

If you are using python package, please provide

1. The python version and distribution
2. The command to install `xgboost` if you are not installing from source

`Python 2.7.13`

## Steps to reproduce

1. Clone the xgboost project.
2. Edit the training data by adding `10000000:1` at the end of the first line.
3. Copy the training script above and run.

**Comment by khotilov** [comment]
xgboost doesn't do feature hashing. So it has dense vectors in a few places which are storing all feature ids in the range. Constructing, initializing and manipulating 100M vectors multiple times is not cheap.

**Comment by tobegit3hub** [comment]
That makes sense. Thanks @khotilov 😃 

It would be great if `XGBoost` can support this later.
