### ISSUE TITLE
I am testing the .net wrapper and i want to know if why i am getting an error.  

### ISSUE THREAD

**Issue by Tak-Au** [dmlc/xgboost#2385]
The error I am getting is 
**Additional information: value 0for Parameter num_class should be greater equal to 1**

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using XGBoost;

`namespace ConsoleApplication6
{
    class Program
    {
        static void Main(string[] args)
        {

            var gbm = new XGBClassifier(objective: "multi:softprob",numClass:3);
            var X = new []{
            new []{1f,2f},
            new []{2f,5f},
            new []{2f,3f}
            };            
            var Y = new[] { 0f, 1f,2f };
            gbm.Fit(X, Y);
        }
    }
}`

**Comment by khotilov** [comment]
Because you didn't really set `num_class` here.
