### ISSUE TITLE
NA-values in xgb.model.dt.tree

### ISSUE THREAD

**Issue by martinju** [dmlc/xgboost#2387]
Hi

Can anyone please explain to me what row 5 and 11 in the below tree dump output form xgb.model.dt.tree ran in R means?
The model works fine, and seems to give predictions even when sent to this node.

(Unfortunatly I have not been able to reproduce this issue with data and a simple model that I can share.)

    Tree Node   ID Feature        Split  Yes   No Missing    Quality      Cover
 1:    0    0  0-0      83       5500  0-1  0-2     0-1 12.0680000 258513.000
 2:    0    1  0-1      82      3.02557  0-3  0-4     0-3 16.0114000 102400.000
 3:    0    2  0-2      81 -9.53674e-07  0-5  0-6     0-5  0.3093830 156114.000
 4:    0    3  0-3      29    0.0224791  0-7  0-8     0-7  5.2478900  72692.200
 5:    0    4  0-4      NA           NA 0-NA 0-NA    0-NA         NA         NA
 6:    0    5  0-5    Leaf           NA   NA   NA      NA -0.0580025 149515.000
 7:    0    6  0-6     185 -9.53674e-07 0-11 0-12    0-11 10.7916000   6598.750
 8:    0    7  0-7    Leaf           NA   NA   NA      NA -0.0579613  36262.500
 9:    0    8  0-8      82      1.99732 0-13 0-14    0-13  0.6875210  36429.800
10:    0    9  0-9    Leaf           NA   NA   NA      NA  0.0000000      0.000
11:    0   10 0-10      NA           NA 0-NA 0-NA    0-NA         NA         NA
12:    0   11 0-11      82      2.89552 0-17 0-18    0-18  0.8333360   2226.750

Any help, pointers or suggestions are welcome!

**Comment by khotilov** [comment]
Could you please post the `xgb.dump` output for tree 0?

**Comment by martinju** [comment]
I am sorry for the late reply, I totally forgot about this.  Below is the full output form xgb.dump for tree 0. Note that output I shared from xgb.model.dt.tree was just the 12 first rows, not the complete tree.

booster[0]
0:[f83<5500] yes=1,no=2,missing=1
	1:[f82<3.02557] yes=3,no=4,missing=3
		3:[f29<0.0224791] yes=7,no=8,missing=7
			7:leaf=-0.0579613
			8:[f82<1.99732] yes=13,no=14,missing=13
				13:leaf=-0.0577227
				14:[f83<270500] yes=19,no=20,missing=20
					19:[f29<0.0225631] yes=23,no=24,missing=23
						23:leaf=0
						24:leaf=-0.0559908
					20:[f79<1.5] yes=25,no=26,missing=26
						25:leaf=-0.0577555
						26:leaf=-0.0568263
		4:[f82<nan] yes=9,no=10,missing=10
			9:leaf=0
			10:[f82<nan] yes=15,no=16,missing=16
				15:leaf=0
				16:[f82<nan] yes=21,no=22,missing=22
					21:leaf=0
					22:[f82<nan] yes=27,no=28,missing=28
						27:leaf=0
						28:[f82<nan] yes=29,no=30,missing=30
							29:leaf=0
							30:[f82<nan] yes=31,no=32,missing=32
								31:leaf=0
								32:[f82<nan] yes=33,no=34,missing=34
									33:leaf=0
									34:leaf=-0.0567347
	2:[f81<-9.53674e-07] yes=5,no=6,missing=5
		5:leaf=-0.0580025
		6:[f185<-9.53674e-07] yes=11,no=12,missing=11
			11:[f82<2.89552] yes=17,no=18,missing=18
				17:leaf=-0.0561353
				18:leaf=-0.0540607
			12:leaf=-0.058194

I am running the latest version on xgboost from CRAN.
I guess the issues are with the fXX<nan. What does that mean?

**Comment by khotilov** [comment]
Could you also please show your xgb parameters and the extremal values of `table(yourdata[, 83] , useNA='ifany')`? And try installing the recent code from github - there were some NaN-related fixes, at least for sparse data, since the last CRAN release.

**Comment by martinju** [comment]
Variable 83 is a continuous variable with more than a million unique values, so table would not make much sense. Here is the summary of the variable
summary(mydata[, 83] , useNA='ifany')
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
   0.00    1.58    3.69          7.44     9.59       52.51   92418 

Or do you mean variable 82? That gives
table(mydata[, 82] , useNA='ifany')

      0       1 
    1520139   39929 


My parameters where

$eta
[1] 0.02921759

$max_depth
[1] 9

$min_child_weight
[1] 4

$gamma
[1] 0.03540335

$subsample
[1] 0.6620931

$colsample_bytree
[1] 0.6

$lambda
[1] 1

$alpha
[1] 0.1

$scale_pos_weight
[1] 1

$max_delta_step
[1] 9

$objective
[1] "binary:logistic"

$eval_metric
[1] "auc"

$silent
[1] 1


I tried installing the latest code from github following the guide here: http://xgboost.readthedocs.io/en/latest/build.html#r-package-installation 
but got the error: 
* installing *source* package ?xgboost? ...
sh: 1: ./configure: not found
ERROR: configuration failed for package ?xgboost?

This happened both when trying to install from the command line and from within R.

**Comment by khotilov** [comment]
The reason for using table was to see NA's and NaN's separately (which `summary` clumps together into NA's). Then what is `sum(is.nan(mydata[,83]))`? f82 in the dump (0-based index) is column 83 in R.

What OS do you have, and what does `ls -l` show within `R-package/`? Are you able to install from source other any packages that use configure script, e.g., glmnet?

**Comment by martinju** [comment]
I see. There are no nan's in my data: > 
sum(is.nan(mydata[,83]))
[1] 0

I am on Linux, Ubuntu 16.04. I tried installing glmnet by downloading the source and installing it via R CMD INSTALL and that worked perfectly fine. I do not have administration rights on the instance though. Maybe that is the problem with xgboost source installation?

Anyway, I succesfully installed xgboost 0.6.4.6. on a windows instance and reran the xgb.model.dt.tree, which gave exactly the same output as before; as did xgb.dump (except that numbers like -9.53000e-07 now are shown as -9.53000e-007).

**Comment by khotilov** [comment]
Could you try to isolate the problem, e.g., minimal amount of variables and rows when it still occurs? What if column 83 is your only variable?

I really have no ideas right now about why this installation error might happen on your ubuntu machine...

**Comment by martinju** [comment]
Just a quick update: It seems the problem has to do with the xgbDMatrix I am using when fitting the model. In the model which returned the 0-NA/nan tree output, the xgbDMatrix was loaded from a binar file saved using xgb.Dmatrix.save. 

Whe recreating the xgbDMatrix within the current R session and rerunning the model the error does not occur, the model fit seems to exactly the same though. 

Currently I can not rule out completely that the original xgbDMatrix was created with an older version of xgboost, but I do not think so. May be that be an issue? I don't have time just now to dig further. Any ideas of what I should check and look for?

**Comment by khotilov** [comment]
It would be really hard to trace the root of such issue without being able to fully reproduce it.

**Comment by martinju** [comment]
Hi again. 

I found some time to dig further into this. The problem seems not to be related to saving/loading of the xgbDMatrix as I previously suggested, nor my data in particular, but rather having NA's in the data.

The code snippet shows two very similar model fittings, one working and one that does not work.


## Code

```

require(xgboost)
library(Matrix)

data(agaricus.train, package='xgboost')
train <- agaricus.train

train$data <- as.data.frame(as.matrix(train$data)[1:50,1:5])
colnames(train$data) <- paste("X",1:5,sep="")

lab <- train$label[1:50]

#### Keeps the NA when creating the model matrix object
options(na.action="na.pass")
Xmodel.matrix <- sparse.model.matrix(as.formula("~."),data=train$data)
xgbDMatrix <- xgb.DMatrix(data=Xmodel.matrix,label = lab)

xgbFit <- xgb.train(data=xgbDMatrix,
                    nrounds = 2,
                    objective = "binary:logistic")

#### All of this works fine

xgb.model.dt.tree(model = xgbFit) # Natural output
matrix(xgb.dump(model = xgbFit),ncol=1) # Natural output
predict(xgbFit,newdata=xgbDMatrix) # Natural output


#### Introducing NA in the xgb.DMatrix
train$data[1:5,5] <- NA
Xmodel.matrixNA <- sparse.model.matrix(as.formula("~."),data=train$data)
xgbDMatrixNA <- xgb.DMatrix(data=Xmodel.matrixNA,label = lab)

xgbFitNA <- xgb.train(data=xgbDMatrixNA,
                    nrounds = 2,
                    objective = "binary:logistic")

#### This does not work 
xgb.model.dt.tree(model = xgbFitNA) # wierd output
matrix(xgb.dump(model = xgbFitNA),ncol=1) # wierd output
predict(xgbFitNA,newdata=xgbDMatrix) # Natural output
```

I hope this allows you to figure out the problem with this and be able to fix it.

**Comment by martinju** [comment]
@khotilov Have you or other had any chance to look into this? As suggested in the last comment xgb.model.df.tree and xgb.dump seems gives erroneous output when there are NA's in the training data, while prediction still works fine.

**Comment by martinju** [comment]
Hi again.

The CRAN version of xgboost 0.6.4 still gives the buggy nan behavior, but currently everything works fine in xgboost version 0.6.4.6. So apparently, this was fixed at some point. Thank you for this fix. I am closing this issue now.
