### ISSUE TITLE
Can't import xgboost in conda

### ISSUE THREAD

**Issue by iamtodor** [dmlc/xgboost#2391]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System:
```
~ $ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```

Compiler:
`gcc version 4.8.5 (GCC)`

```
~ $ sudo update-alternatives --config gcc
There are 3 choices for the alternative gcc (providing /usr/bin/gcc).

  Selection    Path              Priority   Status
------------------------------------------------------------
  0            /usr/bin/gcc-6     60        auto mode
  1            /usr/bin/gcc-4.8   60        manual mode
  2            /usr/bin/gcc-5     1         manual mode
* 3            /usr/bin/gcc-6     60        manual mode
```
Package used (python/R/jvm/C++):

`xgboost` version used: 0.6a2

If installing from source, please provide `downloaded from https://pypi.python.org/pypi/xgboost/`

1. The commit hash (`git rev-parse HEAD`)
`c486211efa29b95771c74f5d8701ca4a`
2. Logs will be helpful (If logs are large, please upload as attachment).

If you are using jvm package, please 

1. add [jvm-packages] in the title to make it quickly be identified
2. the gcc version and distribution

If you are using python package, please provide

1. The python version and distribution
```
(mercedes) xgboost-0.6a2 $ python
Python 3.6.1 |Anaconda custom (64-bit)| (default, May 11 2017, 13:09:58) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
```

2. The command to install `xgboost` if you are not installing from source

If you are using R package, please provide

1. The R `sessionInfo()`
2. The command to install `xgboost` if you are not installing from source

## Steps to reproduce

1. 
2.
3.

## What have you tried?

1. I have a problem related to conda+xgboost. I have got an error:
```---------------------------------------------------------------
OSError                       Traceback (most recent call last)
<ipython-input-2-bf6d598e8de8> in <module>()
     19 from mlxtend.regressor import StackingRegressor
     20 
---> 21 import xgboost as xgb

/home/iamtodor/anaconda3/lib/python3.6/site-packages/xgboost/__init__.py in <module>()
      9 import os
     10 
---> 11 from .core import DMatrix, Booster
     12 from .training import train, cv
     13 from . import rabit                   # noqa

/home/iamtodor/anaconda3/lib/python3.6/site-packages/xgboost/core.py in <module>()
    110 
    111 # load the XGBoost library globally
--> 112 _LIB = _load_lib()
    113 
    114 

/home/iamtodor/anaconda3/lib/python3.6/site-packages/xgboost/core.py in _load_lib()
    104     if len(lib_path) == 0:
    105         return None
--> 106     lib = ctypes.cdll.LoadLibrary(lib_path[0])
    107     lib.XGBGetLastError.restype = ctypes.c_char_p
    108     return lib

/home/iamtodor/anaconda3/lib/python3.6/ctypes/__init__.py in LoadLibrary(self, name)
    424 
    425     def LoadLibrary(self, name):
--> 426         return self._dlltype(name)
    427 
    428 cdll = LibraryLoader(CDLL)

/home/iamtodor/anaconda3/lib/python3.6/ctypes/__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    346 
    347         if handle is None:
--> 348             self._handle = _dlopen(self._name, mode)
    349         else:
    350             self._handle = handle

OSError: /home/iamtodor/anaconda3/lib/python3.6/site-packages/zmq/backend/cython/../../../../.././libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/iamtodor/anaconda3/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so)
```

At first try, I downloaded xgboost via pip and I can't use it in terminal: 
1) python
2) import xgboost 
I got the same error
After that, I have downloaded sources and install it via `python setup.py install` and terminal works.
But, I need to use it within conda environment, so I activated it and I have done the same `python setup.py install`, here is the logs: https://gist.github.com/iamtodor/76170150c254f8c9c1204d7fb100dca7

I hope I describe my issue as clear as possible. If I have missed something or you need more details, please ask me, I will provide it as soon as possible

**Comment by iamtodor** [comment]
Also, I would add: I have taken a look at this thread and specific comment https://github.com/dmlc/xgboost/issues/1043#issuecomment-255603019 but it gives me nothing, doesn't work

**Comment by iamtodor** [comment]
Here the the output of versions `GLIBCXX_3.4.*`
```
(mercedes) xgboost $ strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_DEBUG_MESSAGE_LENGTH
```

**Comment by iamtodor** [comment]
Here is the output from the https://anaconda.org/salford_systems/libgcc-6
```
~ $ conda install -c clinicalgraphics libgcc-6=6.2.0
Fetching package metadata ...........
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /home/iamtodor/anaconda3:
#
libgcc-6                  6.2.0                         2    clinicalgraphics
~ $ 
```

**Comment by iamtodor** [comment]
Output from the environment
```
~ $ strings ~/anaconda3/envs/mercedes/lib/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_DEBUG_MESSAGE_LENGTH
```

**Comment by iamtodor** [comment]
The only thing, that I have figured out is the final string from the whole error was:
`OSError: /home/iamtodor/anaconda3/lib/python3.6/site-packages/zmq/backend/cython/../../../../.././libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/iamtodor/anaconda3/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so)`
It mean conda tried to call correct version from the kernel, not from environment, that was in my case `mercedes`. 
I'm really not confident what was solve the problem. I mean does conda finds right version inside kernel or it starts to look for correct version inside environment.

I hope this thread helps someone.
If you have something to add - I would really appreciate it to reach better understanding what was the problem.

**Comment by hendra-herviawan** [comment]
Please use

conda install -c anaconda libgcc

**Comment by iamtodor** [comment]
conda - bad solution. better use https://virtualenv.pypa.io/en/stable/
