### ISSUE TITLE
Cuda 8.0 - grow_gpu - GPU plugin exception

### ISSUE THREAD

**Issue by hypknowsys** [dmlc/xgboost#2392]
Hi all,

I successfully compiled XGBoost

Unfortunately checking the benchmark fails with 
 dmlc-core/include/dmlc/logging.h:300: [16:28:44] plugin/updater_gpu/src/updater_gpu.cu:40: GPU plugin exception: plugin/updater_gpu/src/exact/../common.cuh(204): invalid device function

What I did:

1. clone xgboost with  git clone --recursive https://github.com/dmlc/xgboost
2. export PATH=/usr/local/cuda-8.0/bin:$PATH
3. cd xgboost/
4. make PLUGIN_UPDATER_GPU=ON

(I also tried - under build - with cmake -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-8.0 .. -DPLUGIN_UPDATER_GPU=ON with the same result)
 Afterwards I build up the environment (tested anaconda with python 3.5 and python 3.6, also python 3.5) including numpy and scikit-learn.

5. cd python-package/
6. python setup.py  install
7. cd ../xgboost/plugin/updater_gpu/
8. python benchmark/benchmark.py --algorithm all

Benchmark fails with the error mentioned above. 

I am using Linux Ubuntu 16.04 - 4.4.0-38-generic // GCC 5.4.0 20160609 // CUDA 8.0 375.26

Commit hash is 85b2fb3eeeccf24a980a0d73cb608c8219aa47da

Does someone have an idea. Thanks you,

Henner 
[complete_log.txt](https://github.com/dmlc/xgboost/files/1058381/complete_log.txt)

**Comment by jemaw** [comment]
I'm facing the same problem on Arch Linux:

4.11.3-1-ARCH // gcc-5 (GCC) 5.4.0 // Cuda 8.0, V8.0.61

**Comment by RAMitchell** [comment]
@teju85 @vinaydes can you take a look please.

**Comment by pseudotensor** [comment]
@hypknowsys Do you get the same result with commit hash 2d9052bc7dfc4d40e915820e0bede05c626b588d prior to some updates to grow_gpu?

**Comment by vinaydes** [comment]
@hypknowsys What GPU are you running on?

**Comment by hypknowsys** [comment]
@vinaydes We are running NVIDIA Quadro M6000 24GB

**Comment by pseudotensor** [comment]
That only has compute_52.  You should change the compute_60 to compute_52.

**Comment by jemaw** [comment]
changing compute_60 in CMakelists.txt to my compute capability fixed it for me. At the moment the  [readme](https://github.com/dmlc/xgboost/tree/master/plugin/updater_gpu) only mentions that the compute capability has to be >= 3.5, I think adding this tip would be helpful.

**Comment by RAMitchell** [comment]
Our next pr should have it autodetecting compute capability

**Comment by hypknowsys** [comment]
Hi all, 

compute_52 fixed the issue. 

What I did (as suggested from @pseudotensor ) 

git clone --recursive https://github.com/dmlc/xgboost
cd xgboost 
- changed compute_60 to compute_52 (for a better overview about your GPU compute capability have a look into https://developer.nvidia.com/cuda-gpus ) 
mkdir build
cd build
cmake .. -DPLUGIN_UPDATER_GPU=ON -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-8.0 
make 

Remark: make PLUGIN_UPDATER_GPU=ON under xgboost did not work for me !!! 


Afterwards you should be able to make python setup.py install


Thanks to everybody.

Henner

**Comment by iFe1er** [comment]
Hi

Thanks a lot! The solution also work perfectly for me. 
 I am Ubuntu 14.04 + Nvidia Titan X with python 2.7 (virtualenv). Just modify the compute_60 to compute_52 in the CMakelists.txt, and re-make the files,  and then everything work fine!

**Comment by teju85** [comment]
@hypknowsys we have a PR for making sure that most of the popular (currently maxwell/pascal) GPU architectures are covered during the build process.
It's here: https://github.com/dmlc/xgboost/pull/2390
This doesn't require one to pass specific gpu architectures for building. (so, the default build instructions on the updater_gpu README page should be good enough)
Can you please confirm if this works for you?

Regards,
Thejaswi

**Comment by pseudotensor** [comment]
@teju85 We also fix this in the latest PR with multi-GPU capability (follows dmlc/mshadow's cmake/Cuda.cmake that works great), but we had to temporarily disable it for xgboost because your new grow_gpu crashes with a device error when using compute_61 that many of us have these days.  Any luck fixing that?  Until then, we will use a hard-coded compute.

**Comment by hypknowsys** [comment]
@teju85 Did not work: 

-- Performing Test COMPILER_SUPPORTS_CXX0X - Success
CMake Error at CMakeLists.txt:85 (add_subdirectory):
  The source directory

    /home/hgraubitz_dev/Work/170609-XGBoost-GPU/xgboost/dmlc-core

  does not contain a CMakeLists.txt file.


-- Configuring incomplete, errors occurred!


What I did:

1. git clone https://github.com/teju85/xgboost.git
2. cd xgboost/
3. mkdir build
4. cd build/
5. cmake .. -DPLUGIN_UPDATER_GPU=ON -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-8.0

**Comment by teju85** [comment]
@hypknowsys in your first step above you are missing a '--recursive' option for clone.
It appears like that is the reason for the failure you are observing.

**Comment by teju85** [comment]
@pseudotensor 
@vinaydes too tried it on a '61' capable GPU and was able to run it successfully.
Can you send me repro's to debug further?

**Comment by pseudotensor** [comment]
Ya, it seems intermittent for me.  I'll keep my PR with the auto-compute value and see what people find out.

**Comment by hypknowsys** [comment]
@teju85 sorry for missing the --recursive option: your clone is working perfectly for me. 

It autodetects my compute capacity. Thanks.

**Comment by icyblade** [comment]
I have similar exceptions. In my case(Tesla K80), specifying `GPU_COMPUTE_VER="37"` do the trick:

    cmake .. -DPLUGIN_UPDATER_GPU=ON -DGPU_COMPUTE_VER="37"

**Comment by RAMitchell** [comment]
@icyblade out of curiosity does -DGPU_COMPUTE_VER="35" also work? Thanks for posting this.

**Comment by icyblade** [comment]
@RAMitchell `-DGPU_COMPUTE_VER="35"` works, but as Tesla K80 has 3.7 compute capability, I think `-DGPU_COMPUTE_VER="37"` is better.
