### ISSUE TITLE
[jvm-packages] Kryo serializer test fails on Windows

### ISSUE THREAD

**Issue by superbobry** [dmlc/xgboost#2394]
## Environment info
Operating System: Windows on Appveyor

Compiler: VS2015

`xgboost` version used: 37c27ab8e8220c107f6586e580d07f6d6ab37bd8

## Steps to reproduce

Listed in the Appveyor script [here](https://github.com/criteo-forks/xgboost-jars/blob/master/appveyor.yml).

Here is a link to the failing build: https://ci.appveyor.com/project/superbobry/xgboost-jars/build/1.0.167

## What have you tried?

Nothing, because the error message does not give any hints, it's just "ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed".

**Comment by CodingCat** [comment]
looks like the tracker is not bind correctly 

`Tracker started, with env={}`

**Comment by CodingCat** [comment]
it fails consistently?

**Comment by superbobry** [comment]
I've tried two times. Can try more, if you want.

**Comment by CodingCat** [comment]
so....our current windows build does not test jvm packages?????

**Comment by CodingCat** [comment]
i checked the code, would you mind trying a fix:

1. change https://github.com/CodingCat/xgboost/blob/master/jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/RabitTracker.java#L142 to public 
2. encapsulate https://github.com/dmlc/xgboost/blob/master/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala#L285 and following lines in a try/finally block and call tracker.stop() in finally block?

**Comment by superbobry** [comment]
> so....our current windows build does not test jvm packages?????

Nope, because building libhdfs for Windows is a PITA. If we could migrate to libhdfs3 (see dmlc/dmlc-core#267) things would be much much simpler.

> would you mind trying a fix:

Will do yep.

**Comment by superbobry** [comment]
@CodingCat magically, the Kryo test passes with the two changes you've mentioned, even though they look completely unrelated to Kryo. I did [two](https://ci.appveyor.com/project/superbobry/xgboost-jars/build/1.0.209) [runs](https://ci.appveyor.com/project/superbobry/xgboost-jars/build/1.0.208) and both were successful.

After I reverted the changes, however, the test failed [two](https://ci.appveyor.com/project/superbobry/xgboost-jars/build/1.0.206) [times](https://ci.appveyor.com/project/superbobry/xgboost-jars/build/1.0.207).

**Comment by CodingCat** [comment]
it's not magic actually....it looks like in windows the previous binding of tracker is not released after the exception while linux does that.....as a result, in windows kryo test cannot bind tracker to the address

would you mind posting a PR containing the fix?
