### ISSUE TITLE
Can't Load Saved Model

### ISSUE THREAD

**Issue by gaw89** [dmlc/xgboost#2399]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System:
RHEL 64 Bit

Latest pip install of xgboost

## Steps to reproduce

I built and saved an xgboost model on my Windows desktop in Python 2.7.  I subsequently loaded this file to a server to run it in production.  When I run the command from the shell, it runs with no issues:

`$ /apps/gw-dashboard/python/gw-env/bin/python /storage/apps/gw-dashboard/project/python/prod_model.py &>> /apps/gw-dashboard/project/logs/log.txt`

However, when I try to schedule this exact same command through cron, I get this:

[09:26:02] include/dmlc/logging.h:235: [09:26:02] src/io/local_filesys.cc:149: Check failed: allow_null  LocalFileSystem: fail to open "xgb.6.7.17.model"
Traceback (most recent call last):
  File "/storage/apps/gw-dashboard/project/python/prod_model.py", line 117, in <module>
    model.load_model('xgb.6.7.17.model')
  File "/apps/gw-dashboard/python/gw-env/lib/python2.7/site-packages/xgboost/core.py", line 996, in load_model
    _check_call(_LIB.XGBoosterLoadModel(self.handle, c_str(fname)))
  File "/apps/gw-dashboard/python/gw-env/lib/python2.7/site-packages/xgboost/core.py", line 127, in _check_call
    raise XGBoostError(_LIB.XGBGetLastError())
xgboost.core.XGBoostError: [09:26:02] src/io/local_filesys.cc:149: Check failed: allow_null  LocalFileSystem: fail to open "xgb.6.7.17.model"

## What have you tried?

1. I tried setting the PATH variable in my crontab to /apps/gw-dashboard/python/gw-env/bin
2. I tried using:
`model = xgb.Booster(model_file='../models/xgb.6.7.17.model')`
instead of:
`model = xgb.Booster()
model.load_model('../models/xgb.6.7.17.model')`

## Next Idea to Try
I will try converting it to an XGBClassifier instead and then save/load it using the Sklearn tools, but this still is an issue.  Why does it work from the shell, but not from cron?

**Comment by edi-bice** [comment]
Lots of stuff works from shell but not from cron. Different environments, etc.

**Comment by gaw89** [comment]
@edi-bice, good point.  That seems to definitely be part of the reason.  I wonder if there's a way to fix this on the XGBoost side of things though?  I would try, but I don't know C++ (yet).

**Comment by edi-bice** [comment]
You've specified the model file as a relative path - relative to what? I bet cron and your interactive shell end up in different "current" directories when running your code

**Comment by gaw89** [comment]
For anyone who's interested in a resolution to this issue, I was successfully able to recreate the interactive shell environment within cron by using:
`. $HOME/.profile;`
In my crontab before the command to run the prediction script. 

I also changed all the relative paths to be hardcoded as suggested by @edi-bice.  

I am closing this issue.
