### ISSUE TITLE
I do not know if my process is right?

### ISSUE THREAD

**Issue by LiuSai-Dream** [dmlc/xgboost#240]
Below is the output of my regression task for reference, I set num_round=40, but in the dump.raw.txt, there are only two booster, I have no idea if it is right, and prediction values in pred.txt  are basis same too. Maybe somewhere goes wrong, but I donot know.

and my conf file is:
![image](https://cloud.githubusercontent.com/assets/8444464/7131653/638bc1ae-e2b4-11e4-8a8f-f0a83008af2a.png)

############################################################
351071x162 matrix with 42382165 entries is loaded from part-xgboost-reg-train.buffer
boosting round 0, 1 sec elapsed
tree prunning end, 1 roots, 46 extra nodes, 92 pruned nodes ,max_depth=7
[0]
boosting round 1, 2 sec elapsed
tree prunning end, 1 roots, 74 extra nodes, 72 pruned nodes ,max_depth=7
[1]
boosting round 2, 3 sec elapsed
tree prunning end, 1 roots, 54 extra nodes, 94 pruned nodes ,max_depth=7
[2]
boosting round 3, 4 sec elapsed
tree prunning end, 1 roots, 60 extra nodes, 60 pruned nodes ,max_depth=7
[3]
boosting round 4, 5 sec elapsed
tree prunning end, 1 roots, 66 extra nodes, 82 pruned nodes ,max_depth=7
[4]
boosting round 5, 6 sec elapsed
tree prunning end, 1 roots, 60 extra nodes, 92 pruned nodes ,max_depth=7
[5]
boosting round 6, 7 sec elapsed
tree prunning end, 1 roots, 56 extra nodes, 70 pruned nodes ,max_depth=7
[6]
boosting round 7, 8 sec elapsed
tree prunning end, 1 roots, 44 extra nodes, 86 pruned nodes ,max_depth=7
[7]
boosting round 8, 9 sec elapsed
tree prunning end, 1 roots, 50 extra nodes, 94 pruned nodes ,max_depth=7
[8]
boosting round 9, 10 sec elapsed
tree prunning end, 1 roots, 30 extra nodes, 106 pruned nodes ,max_depth=7
[9]
boosting round 10, 11 sec elapsed
tree prunning end, 1 roots, 26 extra nodes, 98 pruned nodes ,max_depth=6
[10]
boosting round 11, 12 sec elapsed
tree prunning end, 1 roots, 34 extra nodes, 116 pruned nodes ,max_depth=7
[11]
boosting round 12, 13 sec elapsed
tree prunning end, 1 roots, 28 extra nodes, 118 pruned nodes ,max_depth=7
[12]
boosting round 13, 14 sec elapsed
tree prunning end, 1 roots, 46 extra nodes, 104 pruned nodes ,max_depth=7
[13]
boosting round 14, 15 sec elapsed
tree prunning end, 1 roots, 14 extra nodes, 126 pruned nodes ,max_depth=7
[14]
boosting round 15, 16 sec elapsed
tree prunning end, 1 roots, 44 extra nodes, 122 pruned nodes ,max_depth=7
[15]
boosting round 16, 17 sec elapsed
tree prunning end, 1 roots, 22 extra nodes, 108 pruned nodes ,max_depth=7
[16]
boosting round 17, 18 sec elapsed
tree prunning end, 1 roots, 34 extra nodes, 78 pruned nodes ,max_depth=7
[17]
boosting round 18, 19 sec elapsed
tree prunning end, 1 roots, 26 extra nodes, 112 pruned nodes ,max_depth=7
[18]
boosting round 19, 20 sec elapsed
tree prunning end, 1 roots, 22 extra nodes, 114 pruned nodes ,max_depth=7
[19]
boosting round 20, 21 sec elapsed
tree prunning end, 1 roots, 22 extra nodes, 122 pruned nodes ,max_depth=7
[20]
boosting round 21, 22 sec elapsed
tree prunning end, 1 roots, 22 extra nodes, 104 pruned nodes ,max_depth=7
[21]
boosting round 22, 23 sec elapsed
tree prunning end, 1 roots, 28 extra nodes, 92 pruned nodes ,max_depth=7
[22]
boosting round 23, 24 sec elapsed
tree prunning end, 1 roots, 12 extra nodes, 108 pruned nodes ,max_depth=5
[23]
boosting round 24, 24 sec elapsed
tree prunning end, 1 roots, 24 extra nodes, 106 pruned nodes ,max_depth=5
[24]
boosting round 25, 25 sec elapsed
tree prunning end, 1 roots, 22 extra nodes, 90 pruned nodes ,max_depth=6
[25]
boosting round 26, 26 sec elapsed
tree prunning end, 1 roots, 18 extra nodes, 102 pruned nodes ,max_depth=6
[26]
boosting round 27, 27 sec elapsed
tree prunning end, 1 roots, 20 extra nodes, 98 pruned nodes ,max_depth=7
[27]
boosting round 28, 28 sec elapsed
tree prunning end, 1 roots, 18 extra nodes, 86 pruned nodes ,max_depth=6
[28]
boosting round 29, 29 sec elapsed
tree prunning end, 1 roots, 24 extra nodes, 56 pruned nodes ,max_depth=7
[29]
boosting round 30, 30 sec elapsed
tree prunning end, 1 roots, 24 extra nodes, 72 pruned nodes ,max_depth=7
[30]
boosting round 31, 31 sec elapsed
tree prunning end, 1 roots, 0 extra nodes, 108 pruned nodes ,max_depth=0
[31]
boosting round 32, 32 sec elapsed
tree prunning end, 1 roots, 0 extra nodes, 108 pruned nodes ,max_depth=0
[32]
boosting round 33, 33 sec elapsed
tree prunning end, 1 roots, 0 extra nodes, 108 pruned nodes ,max_depth=0
[33]
boosting round 34, 34 sec elapsed
tree prunning end, 1 roots, 0 extra nodes, 108 pruned nodes ,max_depth=0
[34]
boosting round 35, 35 sec elapsed
tree prunning end, 1 roots, 0 extra nodes, 108 pruned nodes ,max_depth=0
[35]
boosting round 36, 35 sec elapsed
tree prunning end, 1 roots, 0 extra nodes, 116 pruned nodes ,max_depth=0
[36]
boosting round 37, 36 sec elapsed
tree prunning end, 1 roots, 0 extra nodes, 116 pruned nodes ,max_depth=0
[37]
boosting round 38, 37 sec elapsed
tree prunning end, 1 roots, 0 extra nodes, 116 pruned nodes ,max_depth=0
[38]
boosting round 39, 38 sec elapsed
tree prunning end, 1 roots, 0 extra nodes, 116 pruned nodes ,max_depth=0
[39]

updating end, 39 sec in all
430236x162 matrix with 51615454 entries is loaded from part-xgboost-reg-test.buffer
start prediction...
writing prediction to pred.txt
booster[0]:
0:[f159<0.01295] yes=1,no=2,missing=1
        1:[f149<0.00765] yes=3,no=4,missing=3
                3:[f33<0.05545] yes=7,no=8,missing=7
                        7:leaf=-0.0496326
                        8:[f48<6.1252] yes=17,no=18,missing=18
                                17:[f12<3778.28] yes=35,no=36,missing=36
                                        35:leaf=-0.0441964
                                        36:leaf=0.0330357
                                18:[f144<11.949] yes=37,no=38,missing=38
                                        37:leaf=0.0125
                                        38:leaf=-0.0484151
                4:[f39<0.0065] yes=9,no=10,missing=9
                        9:[f33<0.0309] yes=19,no=20,missing=19
                                19:leaf=-0.048603
                                20:leaf=-0.0454217
                        10:[f23<0.13785] yes=21,no=22,missing=22
                                21:[f12<61264.8] yes=43,no=44,missing=44
                                        43:leaf=-0.0445594
                                        44:leaf=0.0125
                                22:leaf=0.00535714
        2:[f67<0.01225] yes=5,no=6,missing=5
                5:[f151<0.01975] yes=11,no=12,missing=11
                        11:leaf=-0.0472281
                        12:[f161<0.0488] yes=25,no=26,missing=26
                                25:leaf=-0.0449317
                                26:[f70<10.9156] yes=51,no=52,missing=52
                                        51:[f129<0.00385] yes=93,no=94,missing=93
                                                93:leaf=0.04
                                                94:leaf=-0.0296875
                                        52:leaf=-0.0348814
                6:[f63<0.14845] yes=13,no=14,missing=13
                        13:[f150<8.20115] yes=27,no=28,missing=28
                                27:leaf=0.0203125
                                28:[f30<2.7771] yes=55,no=56,missing=56
                                        55:leaf=0.0125
                                        56:[f147<0.04655] yes=99,no=100,missing=100
                                                99:leaf=-0.0424591
                                                100:leaf=0.0125
                        14:[f91<0.33015] yes=29,no=30,missing=29
                                29:[f72<95.5679] yes=57,no=58,missing=57
                                        57:[f70<2.63855] yes=101,no=102,missing=102
                                                101:leaf=0.02625
                                                102:[f72<2.07175] yes=137,no=138,missing=138
                                                        137:leaf=-0.00597826
                                                        138:leaf=-0.0367106
                                        58:leaf=0.04
                                30:leaf=0.028125
booster[1]:
0:[f159<0.01275] yes=1,no=2,missing=1
        1:[f155<0.00975] yes=3,no=4,missing=3
                3:[f33<0.05515] yes=7,no=8,missing=7
                        7:[f149<0.00315] yes=15,no=16,missing=15
                                15:leaf=-0.0447438
                                16:[f39<0.05145] yes=33,no=34,missing=33
                                        33:leaf=-0.0443433
                                        34:[f104<262.591] yes=61,no=62,missing=62
                                                61:leaf=0.0397209
                                                62:[f22<8911.58] yes=99,no=100,missing=100
                                                        99:leaf=-0.0387343
                                                        100:leaf=0.0348092
                        8:[f144<11.949] yes=17,no=18,missing=18
                                17:leaf=0.0325
                                18:[f48<6.1252] yes=35,no=36,missing=36
                                        35:[f22<8.69695] yes=63,no=64,missing=63
                                                63:leaf=0.0287426
                                                64:leaf=-0.035403
                                        36:leaf=-0.0434951
                4:[f157<0.01825] yes=9,no=10,missing=9
                        9:leaf=-0.0437044
                        10:[f54<0.7479] yes=21,no=22,missing=22
                                21:leaf=0.0274302
                                22:[f80<831.925] yes=39,no=40,missing=39
                                        39:[f39<0.01045] yes=71,no=72,missing=71
                                                71:leaf=-0.0421241
                                                72:[f22<7.79065] yes=117,no=118,missing=118
                                                        117:leaf=0.0258214
                                                        118:leaf=-0.0356713
                                        40:[f102<40.9502] yes=73,no=74,missing=74
                                                73:leaf=0.0365735
                                                74:[f74<10.7832] yes=119,no=120,missing=119
                                                        119:leaf=-0.0362363
                                                        120:leaf=0.0237987
        2:[f67<0.01135] yes=5,no=6,missing=5
                5:[f149<0.01155] yes=11,no=12,missing=11
                        11:[f48<0.89065] yes=23,no=24,missing=24
                                23:leaf=0.0273614
                                24:[f108<5.65325] yes=41,no=42,missing=42
                                        41:leaf=0.0273614
                                        42:[f74<162.058] yes=75,no=76,missing=75
                                                75:leaf=-0.0430381
                                                76:[f28<9.8355] yes=123,no=124,missing=123
                                                        123:leaf=0.0237782
                                                        124:leaf=-0.0396175
                        12:[f161<0.0488] yes=25,no=26,missing=26
                                25:leaf=-0.0408049
                                26:[f30<152123] yes=45,no=46,missing=46
                                        45:[f37<0.00375] yes=79,no=80,missing=79
                                                79:[f37<0.00365] yes=129,no=130,missing=129
                                                        129:leaf=-0.028224
                                                        130:leaf=0.0382441
                                                80:leaf=-0.0374718
                                        46:leaf=0.0127044
                6:[f63<0.14845] yes=13,no=14,missing=13
                        13:[f150<8.20115] yes=27,no=28,missing=28
                                27:leaf=0.0187891
                                28:[f76<2.3105] yes=49,no=50,missing=50
                                        49:[f142<927.15] yes=83,no=84,missing=84
                                                83:leaf=0.0285383
                                                84:leaf=-0.0349287
                                        50:leaf=-0.0383029
                        14:[f158<5379.04] yes=29,no=30,missing=30
                                29:[f71<0.26435] yes=51,no=52,missing=51
                                        51:[f25<0.0792] yes=87,no=88,missing=87
                                                87:[f139<0.0783] yes=141,no=142,missing=141
                                                        141:leaf=-0.0334302
                                                        142:leaf=0.00605245
                                                88:leaf=0.0161004
                                        52:[f26<8.7292] yes=89,no=90,missing=90
                                                89:leaf=-0.032687
                                                90:leaf=0.0425961
                                30:[f10<55.1856] yes=53,no=54,missing=54
                                        53:leaf=-0.0209605
                                        54:leaf=0.0428575

**Comment by tqchen** [comment]
check the model_in parameter when you do the dump. I guess you specified it to be 0002.model. By default models during all boosting rounds are outputed

**Comment by LiuSai-Dream** [comment]
you are right, but how to specify all models, I have 50 models by setting num_round=50.

**Comment by tqchen** [comment]
you can simply change model_in=0050.model

**Comment by LiuSai-Dream** [comment]
I have tried, it worked, Thx, and it is really quick, good.
