### ISSUE TITLE
cv memory leak

### ISSUE THREAD

**Issue by edi-bice** [dmlc/xgboost#2400]
Hortonworks HDP 2.5
28 nodes, 8 cores, 60Gb
RedHat 6.9
gcc version 6.3.1
python
fd19b7a188a8b048f372827650b1111d4f8b1fa5
Python 2.7.13

## Steps to reproduce
nohup ~/xgboost/dmlc-core/tracker/dmlc-submit --cluster=yarn --num-workers=25 --worker-cores=4 --worker-memory 20g /opt/rh/python27/root/usr/bin/python mycv.py

## mycv.py
data = xgb.DMatrix('hdfs://xxx/user/yyy/data.libsvm', missing=-1)
for params in ParameterGrid(param_grid):
    cvres = cv(params, dtrain, num_boost_round=num_round, nfold=3, metrics='auc', maximize=True, seed=123456, verbose_eval=True, fpreproc=fpreproc, callbacks=[xgb.callback.print_evaluation(show_stdv=True), xgb.callback.early_stop(50), xgb.callback.reset_learning_rate(lrs)])

Never been able to evaluate more than a handful of parameter combinations (<1day) before the whole thing comes to a halt due to one of the YARN containers running out of memory. Grafana shows linear memory consumption increase (free mem linear decrease while cached is steady)

![image](https://user-images.githubusercontent.com/1819450/26978240-cf1ff308-4cf8-11e7-9513-538ad0aa5d88.png)

## failed yarn container log
[19:55:56] XGBoost distributed mode detected, will split data among workers
[19:55:56] Load part of data 2 of 25 parts
17/06/08 19:55:58 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
17/06/08 19:55:58 WARN shortcircuit.DomainSocketFactory: The short-circuit local reads feature cannot be used because libhadoop cannot be loaded.
[20:00:31] 2544436x212 matrix with 289224149 entries loaded from hdfs://xxx/user/yyy/data.libsvm
[20:02:44] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 14 extra nodes, 0 pruned nodes, max_depth=7
...
[04:06:28] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 228 extra nodes, 2 pruned nodes, max_depth=7
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

**Comment by khotilov** [comment]
I'm not exactly sure what is happening when DMatrix.slice is called in a distributed setting, but your problem might be related to that. The cv wrapper creates several partial copies of folds' DMatrix data using the slice method, and then trains folds' models at the same time, iteration-by-iteration. I would suggest rolling your own CV procedure where each fold would be trained separately. You would loose the early stopping though.

**Comment by edi-bice** [comment]
Thanks @khotilov - that is what I did indeed.
