### ISSUE TITLE
feature ordering matters "A LOT"

### ISSUE THREAD

**Issue by nimashahbazi** [dmlc/xgboost#2406]
## Environment info
Operating System:
Mac OS Sierra 10.12.3

Package used (R):
`xgboost` version used:
0.6-4

If you are using R package, please provide

1. The R `sessionInfo()`
R version 3.4.0 (2017-04-21)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.3

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] xgboost_0.6-4     data.table_1.10.4 dplyr_0.7.0       readr_1.1.1      

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.11     lattice_0.20-35  assertthat_0.2.0 grid_3.4.0       R6_2.2.1         magrittr_1.5     rlang_0.1.1      stringi_1.1.5    Matrix_1.2-9    
[10] tools_3.4.0      glue_1.0.0       hms_0.3          compiler_3.4.0   tibble_1.3.3    

## Steps to reproduce

1. I am using xgboost for my the latest competition (Sberbank) on kaggle, But the problem I faced on Mac is when I re-order the features the accuracy dropped A LOT! for example from .45 to .42 in RMSLE accuracy, which is soooo weird. I dont have the problem on Python or Linux with the latest version (the problem is only for Mac).
I have tried to re-install R or using older version of Xgboost, but the problem still appears!
I am completely familiar with Xgboost and won 2 competitions using it.

**Comment by samehif** [comment]
i have the same problem but even in Linux (Ubuntu) and using python. i raised an issue https://github.com/dmlc/xgboost/issues/2406 that was closed by claiming that this is a feature.
