### ISSUE TITLE
help!!! xgboost installation problem in win10

### ISSUE THREAD

**Issue by hanamiqi** [dmlc/xgboost#2412]
i tried to install xgboost in my laptop(w10 enterprise edition x64 os), and i used git bash and mingw64 to build xgboost, and the installation steps i followed are as follows
1: open gitbash and execute **git clone --recursive https://github.com/dmlc/xgboost**, which run successfully
2: execute **cd xgboost; git submodule init; git submodule update**, run successfully
3: execute**cp make/mingw64.mk config.mk**, run successfully
4: execute**make -j4**, the error came out as follows

**Administrator@WINDOWS-3172320 MINGW64 ~/xgboost (master)
$ make -j4
g++ -m64 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fopenmp -MM -MT build/common/common.o src/common/common.cc >build/common/common.d
g++ -m64 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fopenmp -MM -MT build/c_api/c_api_error.o src/c_api/c_api_error.cc >build/c_api/c_api_error.d
g++ -m64 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fopenmp -MM -MT build/c_api/c_api.o src/c_api/c_api.cc >build/c_api/c_api.d
g++ -m64 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fopenmp -MM -MT build/data/data.o src/data/data.cc >build/data/data.d
g++ -m64 -c -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fopenmp src/c_api/c_api_error.cc -o build/c_api/c_api_error.o
g++ -m64 -c -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fopenmp src/common/common.cc -o build/common/common.o
g++ -m64 -c -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fopenmp src/c_api/c_api.cc -o build/c_api/c_api.o
g++ -m64 -c -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fopenmp src/data/data.cc -o build/data/data.o
In file included from src/c_api/c_api_error.cc:6:0:
dmlc-core/include/dmlc/thread_local.h:76:8: error: 'mutex' in namespace 'std' does not name a type
   std::mutex mutex_;
        ^
dmlc-core/include/dmlc/thread_local.h: In member function 'void dmlc::ThreadLocalStore<T>::RegisterDelete(T*)':
dmlc-core/include/dmlc/thread_local.h:71:22: error: 'mutex' is not a member of 'std'
     std::unique_lock<std::mutex> lock(mutex_);
                      ^
dmlc-core/include/dmlc/thread_local.h:71:22: error: 'mutex' is not a member of 'std'
dmlc-core/include/dmlc/thread_local.h:71:32: error: template argument 1 is invalid
     std::unique_lock<std::mutex> lock(mutex_);
                                ^
dmlc-core/include/dmlc/thread_local.h:71:39: error: 'mutex_' was not declared in this scope
     std::unique_lock<std::mutex> lock(mutex_);
                                       ^
dmlc-core/include/dmlc/thread_local.h:73:10: error: request for member 'unlock' in 'lock', which is of non-class type 'int'
     lock.unlock();
          ^
In file included from src/common/common.cc:6:0:
dmlc-core/include/dmlc/thread_local.h:76:8: error: 'mutex' in namespace 'std' does not name a type
   std::mutex mutex_;
        ^
dmlc-core/include/dmlc/thread_local.h: In member function 'void dmlc::ThreadLocalStore<T>::RegisterDelete(T*)':
dmlc-core/include/dmlc/thread_local.h:71:22: error: 'mutex' is not a member of 'std'
     std::unique_lock<std::mutex> lock(mutex_);
                      ^
dmlc-core/include/dmlc/thread_local.h:71:22: error: 'mutex' is not a member of 'std'
dmlc-core/include/dmlc/thread_local.h:71:32: error: template argument 1 is invalid
     std::unique_lock<std::mutex> lock(mutex_);
                                ^
dmlc-core/include/dmlc/thread_local.h:71:39: error: 'mutex_' was not declared in this scope
     std::unique_lock<std::mutex> lock(mutex_);
                                       ^
dmlc-core/include/dmlc/thread_local.h:73:10: error: request for member 'unlock' in 'lock', which is of non-class type 'int'
     lock.unlock();
          ^
Makefile:138: recipe for target 'build/c_api/c_api_error.o' failed
make: *** [build/c_api/c_api_error.o] Error 1
make: *** Waiting for unfinished jobs....
Makefile:138: recipe for target 'build/common/common.o' failed
make: *** [build/common/common.o] Error 1
In file included from src/c_api/c_api.cc:7:0:
dmlc-core/include/dmlc/thread_local.h:76:8: error: 'mutex' in namespace 'std' does not name a type
   std::mutex mutex_;
        ^
dmlc-core/include/dmlc/thread_local.h: In member function 'void dmlc::ThreadLocalStore<T>::RegisterDelete(T*)':
dmlc-core/include/dmlc/thread_local.h:71:22: error: 'mutex' is not a member of 'std'
     std::unique_lock<std::mutex> lock(mutex_);
                      ^
dmlc-core/include/dmlc/thread_local.h:71:22: error: 'mutex' is not a member of 'std'
dmlc-core/include/dmlc/thread_local.h:71:32: error: template argument 1 is invalid
     std::unique_lock<std::mutex> lock(mutex_);
                                ^
dmlc-core/include/dmlc/thread_local.h:71:39: error: 'mutex_' was not declared in this scope
     std::unique_lock<std::mutex> lock(mutex_);
                                       ^
dmlc-core/include/dmlc/thread_local.h:73:10: error: request for member 'unlock' in 'lock', which is of non-class type 'int'
     lock.unlock();
          ^
Makefile:138: recipe for target 'build/c_api/c_api.o' failed
make: *** [build/c_api/c_api.o] Error 1**

who can tell me how to fix this problem, thank you very much!!!

**Comment by khotilov** [comment]
What is your compiler version (output of gcc -v)?

**Comment by shabazbpatel** [comment]
I suggest using Docker for this purposes. You can install it on windows 10 as given in description [here](https://docs.docker.com/docker-for-windows/install/). 
You can work using xgboost library along with other essential data science libraries using Docker.  This [Dockerfile](https://hub.docker.com/r/datmo/xgboost/~/dockerfile/) can be used for the process. Else, you can also try using [datmo](https://datmo.com) in order setup environment and track machine learning projects for making it reproducible.

**Comment by shivang-g** [comment]
I know this is an old issue, but in case someone else stumbles across this issue, it's possibly related to minGW installation settings. **Short answer:** Try making xgboost with an older, stable version of minGW, like 5.3.0, and with "posix" thread model.

**Long answer** (with additional tips):

- I followed this tutorial: https://www.ibm.com/developerworks/community/blogs/jfp/entry/Installing_XGBoost_For_Anaconda_on_Windows

- Pay special attention to the MinGW-W64 installation settings in the screenshot. Based on some other suggestions, and the default version of minGW at the time, I had the following settings, which **did not work** for me (I'm on Windows 8.1, 64-bit):
==> MinGW version = 7.2.0
==> Architecture = x86_64
==> Threads = win32

Once I used the settings from the screenshot, the installation finally worked! **Working settings:**
==> MinGW version = 5.3.0
==> Architecture = x86_64
==> Threads = posix

- Another thing that you should keep in mind: The directories where you install MinGW and checkout XGBoost should not contain any spaces, anywhere in their complete path. 

For example: 
-- Use this: "C:\my-files\repositories\open-source\xgboost"
-- instead of this: "C:\my files\repositories\open source\xgboost"
-- Same goes for minGW. 

- I also had added "\your-path\mingw-w64\x86_64-5.3.0-posix-seh-rt_v4-rev0\mingw64\bin" to the user classpath.

Hope this will help.
