### ISSUE TITLE
Modification for macOS installation guide.

### ISSUE THREAD

**Issue by kimdwkimdw** [dmlc/xgboost#2415]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System: macOS Sierra

Compiler: gcc@6, gcc@7, llvm

Package used (python/R/jvm/C++):

`xgboost` version used: 0.6

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`)
0db37c05bdcd56885a6eef2e1158b9c77eddefbe

2. Logs will be helpful (If logs are large, please upload as attachment).

## Steps to reproduce

1. With gcc@6 or gcc@7,
2. Try original instruction
```
cd xgboost; cp make/config.mk ./config.mk; make -j4
```

## What have you tried?

1. gcc@6
2. gcc@7
3. llvm

Documentation needs update.

**Comment by kimdwkimdw** [comment]
I've added PR for this,

https://github.com/dmlc/xgboost/compare/master...kimdwkimdw:patch-1

**Comment by geoHeil** [comment]
@kimdwkimdw Why would you recommend LLVM over gcc7?

**Comment by kimdwkimdw** [comment]
@geoHeil
Check it out. https://clang.llvm.org/comparison.html

And Apple choose LLVM as their default compiler in Xcode

I love ```Clang is much faster and uses far less memory than GCC.```
