### ISSUE TITLE
R non-response problem after training many times independently 

### ISSUE THREAD

**Issue by achm6174** [dmlc/xgboost#242]
Hello all,

My problem is, I am doing grid search and looking for a optimized parameters list for a small data set.
However, I realize after a day running the script, R session becomes non-response at some time and no further results were print out. The code is as follow:

    count=1
    while(T){
        print(count)
        count = count+1
        max_depth = sample(seq(3,15,1),1)
        #eta = sample(seq(1,3,1)/10,1)
        min_child_weight = sample(seq(2,10,1),1)
        max_delta_step =  sample(seq(0,4,1),1) 
        subsample = sample(seq(5,9,1)/10,1)
        colsample_bytree = sample(seq(5,9,1)/10,1)
        cv.nround = 100
      
        while(T){
        rm(bst.cv)
        
            cv.nround = cv.nround*2
            print(paste(max_depth,min_child_weight,max_delta_step,subsample,colsample_bytree))
        
            # Set necessary parameter
            param <- list("objective" = "multi:softprob",
                          "eval_metric" = "mlogloss",
                          "num_class" = 9,
                          "nthread" = 8,
                          "max_depth" = max_depth ,
                          "eta" = 0.3,
                          "min_child_weight" = min_child_weight,
                          "max_delta_step" = max_delta_step,
                          "subsample" = subsample,
                          "colsample_bytree" = colsample_bytree)
        
            bst.cv = xgb.cv(param=param, data = x, label = y, 
                            nfold = 3, nrounds=cv.nround, verbose = 0)
            gc()
            nround = (1:dim(as.matrix(bst.cv))[1])[as.matrix(bst.cv)[,3]==min(as.matrix(bst.cv)[,3])]  
        
        
            if(nround<cv.nround*0.9){
              break
            }
        }
      
        totalError = min(as.matrix(bst.cv)[,3])
         
        if (totalError < smallestError) {
            smallestError = totalError
            best_para = c(nround,max_depth,min_child_weight,max_delta_step,subsample,colsample_bytree,totalError)
        }
    }

And it stop at some count, around 50 ~ 100. Are there anything I miss that will cause this problem? I have tried to rm the object create during the loop but it does not success

btw thanks for all the contributor for the brilliant work on xgboost, this is one of the best library in gradient boosting.

**Comment by tqchen** [comment]
This seems to be related to #209 .  We are still investigating the possible cause of the stall. It would be great if you can provide the size of the data, your enviroment(linux, windows) and how long it takes to reproduce the stall

**Comment by achm6174** [comment]
Hello Tianqi,

My machine is i7-4770, win 7, 8Gb gam, I tried on small data set (2000,100) and larger one (100000,100), the problem exist for both data set.

I think the problem is related to memory as run this three lines

    while(T){
        bst = xgboost(param=param, data = x[trind,], label = y, nrounds=nround)
        gc()
    }

I realize the memory usage is strictly increasing, which may related to the problem here http://cran.r-project.org/doc/manuals/R-FAQ.html#Why-is-R-apparently-not-releasing-memory_003f.

My current solution to temporary solve that problem, is to close the rsession and reopen after some counts of training and save/load the object using save, load using the following script: 
    
    while(TRUE){
        system("Rscript xgboost_optimize_2.R") # will stop at some count
    }
