### ISSUE TITLE
Installing distributed xgboost will manipulate the huge dataset ?

### ISSUE THREAD

**Issue by yananchen1989** [dmlc/xgboost#2420]
I have a dataset about 40G and my mac only has 16G memory. I want to run xgboost on my dataset.
It seems that mac can not load it directly into memory. 
Using the distributed xgboost will handle the 40G dataset on my mac ? Any advice about how to handle my dataset ? Thanks.
(I have already transform the original csv file to libsvm format, but the size is still over 40GB ).

**Comment by volker48** [comment]
You could try external memory mode https://github.com/dmlc/xgboost/blob/master/doc/how_to/external_memory.md. I'm not sure if you are using Python, R, or XGBoost command line mode but from Python you specify your input file slightly differently to use external memory `dtrain = xgb.DMatrix('../data/agaricus.txt.train#dtrain.cache')`.

**Comment by yananchen1989** [comment]
Thanks. Using external memory has good efficiency.

**Comment by volker48** [comment]
Happy to hear it worked for you.
