### ISSUE TITLE
Ruby implementation

### ISSUE THREAD

**Issue by dvisockas** [dmlc/xgboost#2427]
Hey,

After connecting multiple xgboost models to ruby applications I thought that direct ruby implementation would reduce a lot of work for ruby developers that want to use xgboost.

The questions:
- Is ruby implementation planned at some time? (Couldn't find any issues with "ruby")
- If not, could I try to implement it in ruby and expect some help?

Cheers :fireworks:

**Comment by tqchen** [comment]
There is no ruby binding  as I awared, you are more than welcomed to implement one

**Comment by ilyacherevkov** [comment]
+1

**Comment by superbobry** [comment]
@dvisockas do you suggest implementing both learning and inference or just the latter? If it's the latter, then you might want to have a look at [dmlc/treelite](https://github.com/dmlc/treelite). It doesn't have Ruby bindings as well at the moment, but implementing them could be an easier task.

**Comment by dvisockas** [comment]
@superbobry I was suggesting implementing both parts, since there is not that much use from the inference if you can't train the model. But I can see where your thoughts are going ;)

**Comment by superbobry** [comment]
I can imagine using an XGBoost app in a Ruby webapp, in that case training can be done by e.g. Python or just CLI.

**Comment by exviva** [comment]
FYI @hwartig and I started working on an implementation of xgboost-ruby, we're actually live-coding it on YouTube! ;)

You can subscribe to our channel to cheer us on :) https://www.youtube.com/channel/UCGg-4QjH4IzMiYfyo9mpItw.

**Comment by exviva** [comment]
To close the loop on this, we've published a gem that can read a trained model and do predictions: https://rubygems.org/gems/xgboost. Here's the repo: https://github.com/PairOnAir/xgboost-ruby.
