### ISSUE TITLE
Explanation of the dumped model 

### ISSUE THREAD

**Issue by yananchen1989** [dmlc/xgboost#2429]
I have dump my model to txt and check the trees to understand.
I guess gain is the gain info of this split. But I don't know what's the meaning of `cover, leaf`
```
booster[12]:
0:[f65<-9.53674e-07] yes=1,no=2,missing=1,gain=0.253055,cover=4.40637
	1:leaf=0.281915,cover=1.12855
	2:[f126<-9.53674e-07] yes=3,no=4,missing=3,gain=0.170787,cover=3.27782
		3:leaf=0.0457934,cover=2.07315
		4:leaf=-0.335547,cover=1.20467
```
Besides, if leaf is the output of this three. Our final prediction mechanism is sum up all the leaf values for a given entry, say f = sum(leaf1+leaf2+....leafn) (n is the number of boosting trees). and is the prob for classification is just: p = sigmoid(f) = 1 / (1+exp(-f)) ?

**Comment by pommedeterresautee** [comment]
You can check https://github.com/dmlc/xgboost/issues/364
Please, close the issue if it answers your question.

Kind regards,
Michaël
