### ISSUE TITLE
DMatrix.slice() method is very slow

### ISSUE THREAD

**Issue by yananchen1989** [dmlc/xgboost#2433]
I have a svm format file with 40GB and my mac's memory only has 16GB. I use external memory method to load data. There are 8 million entries in the whole dataset and I want to use slice() to extract some of them. But it always crashed or very slow. Any good way to improve it ?
```
dall = xgb.DMatrix('./train_max_libsvm_.txt#dtrain.cache')
num_boost_round= 30
params = {"objective": "binary:logistic", "eta": 0.01, "max_depth": 10, "seed": 42, "subsample":0.7,
              "eval_metric":'auc', "scale_pos_weight":9.2}
row_cnt = int(dall.num_row())
col_cnt = int(dall.num_col())

sample_cnt = int(row_cnt*0.8)
all_index = range(0, row_cnt)
train_index = random.sample(all_index, sample_cnt)
test_index = list(set(all_index) - set(train_index))

dtest = dall.slice(test_index)
dtrain = dall.slice(train_index)
```

**Comment by khotilov** [comment]
DMatrix.slice() results are in-memory data, not file-backed. I would suggest split your file before loading into xgboost.

**Comment by yananchen1989** [comment]
Thanks very much.
