### ISSUE TITLE
Issues while running pytest after building the xgboost python-package code on ubuntu 16.04

### ISSUE THREAD

**Issue by snehlatamohite** [dmlc/xgboost#2439]
## Environment info
Operating System:
Ubuntu 16.04 X86

Compiler: C++11

If you are using python package, please provide

1. python 3.5 

'xgboost` version used:
git cloned master branch 

What I have tried or steps to reproduce - 
If installing from source, please provide 

1. git clone --recursive https://github.com/dmlc/xgboost
2. make -j4
2. apt-get install gfortran libopenblas-dev liblapack-dev make
3. pip install nose numpy pytest
4. python setup_pip.py install
5. python setup.py install
6. Run pytest from xgboost folder.  - We are getting 1 error and 12 warnings after running tests. I have attached the logs. 
7.Also when tried to run "make test" for running CPP tests , we are getting below error - 
root@43804845890a:/xgboost# make test
g++ -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -DDISABLE_OPENMP -I/include/ -o build_tests/cpp/helpers.o -c tests/cpp/helpers.cc
In file included from tests/cpp/helpers.cc:1:0:
tests/cpp/./helpers.h:12:25: fatal error: gtest/gtest.h: No such file or directory
 #include <gtest/gtest.h>
                         ^
compilation terminated.
tests/cpp/xgboost_test.mk:42: recipe for target 'build_tests/cpp/helpers.o' failed
make: *** [build_tests/cpp/helpers.o] Error 1

**Comment by snehlatamohite** [comment]
[xgboost_python_test _failure.txt](https://github.com/dmlc/xgboost/files/1094352/xgboost_python_test._failure.txt)

**Comment by sowani** [comment]
@snehlatamohite Have you installed gtest? You can try "apt-get install libgtest-dev".

**Comment by snehlatamohite** [comment]
@sowani 
Thanks for reply. 

I have installed libgtest-dev and built gtest using below steps.
cd /usr/src/gtest
sudo cmake CMakeLists.txt
 sudo make
sudo cp *.a /usr/lib
 
Then re-configure GTEST_PATH in make/config.mk 

After doing above steps I could able to run CPP test successfully. 

We still have issue with pytest, please guide.

**Comment by kirk86** [comment]
@snehlatamohite I still face issues even after following all the steps you mentioned. Whenever I issue the `cmake ..` command I get the following error:
```
 Could not find the GTest library. Looked in  system search paths.
CMake Warning at dmlc-core/test/unittest/CMakeLists.txt:36 (message):
  Google Test not found
```

**Comment by sowani** [comment]
@kirk86 Latest build scripts for xgboost on ppc64le are also available at
https://github.com/ppc64le/build-scripts/tree/master/xgboost (cpu-only and
with-gpu versions), Could you please give it a try and let us know if that
works for you?

Thanks,
Atul.

**Comment by kirk86** [comment]
@sowani thanks, I did tried most of the things there although I'm not using ubuntu.
I have gtest installed in the following directories:
```
 tree /usr/lib/ | grep libgtest*
├── libgtest.a
├── libgtest_main.a
├── libgtest_main.so
├── libgtest.so
```
```
ll /usr/include/gtest/
total 368
drwxr-xr-x   3 root root  4096 Jun 17 15:43 .
drwxr-xr-x 468 root root 61440 Jun 17 22:23 ..
-rw-r--r--   1 root root 11523 Sep 28  2016 gtest-death-test.h
-rw-r--r--   1 root root 85459 Sep 28  2016 gtest.h
-rw-r--r--   1 root root  9186 Sep 28  2016 gtest-message.h
-rw-r--r--   1 root root 77062 Sep 28  2016 gtest-param-test.h
-rw-r--r--   1 root root 20042 Sep 28  2016 gtest-param-test.h.pump
-rw-r--r--   1 root root 15145 Sep 28  2016 gtest_pred_impl.h
-rw-r--r--   1 root root 36806 Sep 28  2016 gtest-printers.h
-rw-r--r--   1 root root  2324 Sep 28  2016 gtest_prod.h
-rw-r--r--   1 root root  9952 Sep 28  2016 gtest-spi.h
-rw-r--r--   1 root root  6509 Sep 28  2016 gtest-test-part.h
-rw-r--r--   1 root root 10459 Sep 28  2016 gtest-typed-test.h
drwxr-xr-x   3 root root  4096 Jun 17 15:43 internal
```
```
ll /usr/src/gtest/
total 32
drwxr-xr-x 5 root root  4096 Jun 17 18:02 .
drwxr-xr-x 3 root root  4096 Jun 17 15:43 ..
drwxr-xr-x 3 root root  4096 Jun 17 18:02 build
drwxr-xr-x 2 root root  4096 Jun 17 15:43 cmake
-rw-r--r-- 1 root root 10481 Sep 28  2016 CMakeLists.txt
drwxr-xr-x 2 root root  4096 Jun 17 15:43 src
```
And yest still when I run `cmake` it can't find the google test.

**Comment by sowani** [comment]
@kirk86 I think the build scripts are not picking up appropriate paths
here. One way to force build to pick these headers and libraries is to pass
-I <path/to/gtest/include/files> and -L </path/to/gtest/libs> to build
scripts. Second way could be to check where builds script is expecting
these files and tell gtest build/install script to install these files at
that path.

**Comment by kirk86** [comment]
@sowani Cool, thanks. I'll try that out and report back!
