### ISSUE TITLE
Metal 2 support for GPU acceleration

### ISSUE THREAD

**Issue by virl** [dmlc/xgboost#2440]
In upcoming macOS High Sierra, Apple will introduce Metal 2 API, which will allow even laptop users to utilize high-end video cards in eGPU enclosures. Also Apple working on modular Mac Pro, which will have standard PCI-E expansion slots for video cards (and iMac Pro available in December will have top-notch GPU too).

Considering all this, macOS GPU support for Metal 2 compute API will be welcomed by machine learning developers that use Macs as development environment.

**Comment by sgcinaiims** [comment]
True that.. i started programming on java then i got introduced to swift. The simplicity with performance got me addicted to swift. I had only small data set till today so i was happy with accelerate library. I am thinking of writing RNN or start using ANN as my main ml [although SVM is more than enough for my current data structure.. will try new possibilities] once the apple releases the linear solvers for metal2.. fingers crossed.

**Comment by virl** [comment]
@sgcinaiims Instead of Java (both for XGBoost4J and Deeplearning4J) you can use Kotlin. It's 100% compatible with all Java libs and as language even better than Swift.

**Comment by sgcinaiims** [comment]
@virl sure i will check it out.. thank you.
