### ISSUE TITLE
Relationship between xgboost version and seed values.

### ISSUE THREAD

**Issue by victorrebli** [dmlc/xgboost#2447]
Hello for everyone.
I have a problem and I wonder if this is normal.
I had 2 xgboost models, each model with a different seed,  acting as ensembles and I got an x evaluation metric.
I upgraded the xgboost version and ran the models again, but now the metrics got worse, much worse.

Is this a normal xgboost behavior?

**Comment by pommedeterresautee** [comment]
If the new version is very different from the one you were using, it makes sense the behavior has changed, even if you kept the same seed.
What do you mean by much worse?

**Comment by victorrebli** [comment]
With the 2 models, i was getting a score(rmsle) of  31007 in kaggle competition, after that i upgrade i started getting the score of  0.32400.

**Comment by pommedeterresautee** [comment]
have you tried new seeds to check if this is only related to seeding?
