### ISSUE TITLE
Can we use get_score() to select the features ?

### ISSUE THREAD

**Issue by yananchen1989** [dmlc/xgboost#2453]
I have 1100 features and I use `fscores = model.get_score(importance_type='weight')` to get the dict from feature to feature to its score. Since the input file is svm format, where features are represented by numbers from 0 to 1099. So the feature name like f1, f2 ... in the fscore dict is correspond to feature 1 and feature 2 .... ?
Besides, I find that only 400 features are used to split tress which occur in the dict ? Can we think that the 400 features are more important ? Then, can we consider get rid of other features according to the dict ?

**Comment by pommedeterresautee** [comment]
XGBoost uses only the features which helps in building trees, so it is normal it doesn't use all features.
Removing the non used features may have an impact on the model. It s a way to perform "feature selection". They are indeed more useful that the features not used at all.
https://en.wikipedia.org/wiki/Feature_selection

If it answers your question, please close the issue.

Kind regards,
Michaël
