### ISSUE TITLE
Make->CMake migration

### ISSUE THREAD

**Issue by superbobry** [dmlc/xgboost#2459]
The repo currently has two build systems which are partially overlapping: Makefile-based and CMake based. To some extent this also applies to submodules: rabit and dmlc-core. Clearly this is no good. The build should be consistent, otherwise it would be confusing both for the users and developers.

Having worked on a cross-platform XGBoost build I strongly prefer CMake, which (usually) is more robust in that setting. However, if core developers/other contributors prefer Makefiles, I'd be fine with that too. And one more thing: the options are surely not mutually exclusive. We can agree on using CMake for core build logic and Makefiles for all the wiring (although going that way could cause some issues on vanilla Windows).

Here's a sketch of Makefile-based build features currently absent in the CMake build:

1. Configurable rabit backend.
2. Gtest support.

What do you think?

**Comment by RAMitchell** [comment]
I support the eventual deprecation of the makefile build system in favour of cmake.

**Comment by superbobry** [comment]
@RAMitchell I've spotted that GPU plugin already uses GTest. Can you generalize it to all of the XGBoost tests?

**Comment by RAMitchell** [comment]
I will look into it.

**Comment by tqchen** [comment]
i think we will be keeping both atm. I like cmake, and I am all for a full fledged cmake support. but sometim s it is good to have makefile as an alternative

**Comment by tqchen** [comment]
To summarize my points:
- It seems to be easy to maintain Makefile system (at least for linux users)
- We would advocate CMake for windows users, and it would be great if CMake covers linux case as well
- If the cost of maintenance is minimum(around 100-200 lines of Makefile), i prefer to maintain the make build system, but we can remove that if it becomes a burden eventually

**Comment by mmalohlava** [comment]
Any updates on this issue? It would be more user friendly to have a single build system (=cmake) instead of two parallel build systems which are slightly different.

**Comment by superbobry** [comment]
I think we would have to go with two build systems for reasons @tqchen outlined above, so I'm afraid there isn't much room for updates.

**Comment by edi-bice** [comment]
Having two different build systems is super confusing. I've been building and rebuilding XGboost for some time now, and while hunting down performance differences between my environments, I noticed that building the JVM package rebuilds the core library as well which I had built using make. Clearly the library build from cmake did not produce the same library as make due to differences in compiler and linker settings trying to get XGboost to use MKL. Yes, it's all possible in theory but harder than necessary in practice. No sense in making everything that much more complicated for 99% of the users for the sake of 1%.

**Comment by superbobry** [comment]
> Yes, it's all possible in theory but harder than necessary in practice. No sense in making everything that much more complicated for 99% of the users for the sake of 1%.

Sorry, could you clarify the final point, please: are you referring to maintaining two build systems or something else?

**Comment by edi-bice** [comment]
@superbobry Yes I was referring to maintaining two build systems. Not that I've contributed to it myself so I shouldn't be talking but if the reason to keep make around is only to support platforms cmake doesn't support then we're really talking about 1% of platforms out there [.](https://open.cdash.org/index.php?project=CMake)
