### ISSUE TITLE
some questions about using gbdt in xgboost to generate new features

### ISSUE THREAD

**Issue by nelsonwhf** [dmlc/xgboost#246]
Hi!Chen,I am reading the paper "Practical Lessons from Predicting Clicks on Ads at Facebook",and trying to generate new features with gbdt as the paper said. When I am using the predict_leaf_indices.R script, I find the output is like 
> leafs<-predict(bst,dtrain,predleaf=TRUE)
> head(leafs)
     [,1] [,2]
[1,]    6    4
[2,]    5    4
[3,]    5    4
[4,]    6    4
[5,]    4    3
[6,]    5    4
I can know the leaf index of each tree from this, but how can I know how many leafs each tree have?
for example,if one locates on the 1st leaf of the first tree and locates on the 4th leaf of the second tree,and I know the  first tree has 3 leafs and the second tree has 5 leaf,then I can get a new feature (1,0,0,0,0,0,1,0), but now it seems that I don't know know how many leafs each tree have.

**Comment by tqchen** [comment]
You will need to create a feature map to map them into consecutive index.
Which was not hard to do in python. I assume it should not be hard in R as well.

**Comment by nelsonwhf** [comment]
@tqchen forgive me if it is a stupid question :)
for example,I have trained bst (a gbdt model with two subtrees) and dtrain (one train instance ),then I use predict(bst,dtrain,predleaf=TRUE),and I get : 6 4
then I know the instance is on the 6th leaf of the first subtree and the 4th leaf of the second subtree,but when I transform them to a feature vector, I don't know the max index of the first subtree and the max index of the second subtree. So I don't know the dimension of the feature I should get

**Comment by tqchen** [comment]
Yes, I understand, normally in python what you can do is create a map that maps these features into index. This is just like what you will do after you get categorical features that are not necessarily continuous. Another way was simply take the max of the index you get in each dimension.

**Comment by tqchen** [comment]
I am closing this issue since I think the question is answered
