### ISSUE TITLE
GPU Plugin: Unable to build using plugin on Ubuntu 14.04

### ISSUE THREAD

**Issue by ManrajGrover** [dmlc/xgboost#2464]
I've been trying to install XGBoost with GPU plugin for a long time now but the build is failing (See logs for more information). The steps mentioned in the documentation are somewhat unclear. Should one build the plugin separately or together with xgboost (See [this](https://github.com/dmlc/xgboost/tree/master/plugin/updater_gpu#build) for more information)? I've tried building it using `make` and it fails at particular point. 

## Environment info
Operating System: `Ubuntu 14.04`

Compiler: `gcc version 5.4.1 20160904 (Ubuntu 5.4.1-2ubuntu1~14.04) `
`Cuda compilation tools, release 8.0, V8.0.61`

Package used (python/R/jvm/C++): `python`

`xgboost` version used: `0.6`

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`) d01a31088beabab82b79d0b8c6794d0b223aa3a0
2. Logs will be helpful (If logs are large, please upload as attachment).
[logs_with_err.txt](https://github.com/dmlc/xgboost/files/1108470/logs_with_err.txt)

## Steps to reproduce

Followed steps mentioned [here](https://github.com/dmlc/xgboost/tree/master/plugin/updater_gpu#using-make)

## What have you tried?

1. Tried using [nccl](https://github.com/NVIDIA/nccl) officially provided by NVIDIA but failed to make the xgboost build.
2. Tried changing GCC versions (although should not affect things)
3. Upgraded CUDA to 8.0

**Comment by pseudotensor** [comment]
Can you try latest HEAD?  If you tried make in past, wouldn't work.  make will work now.  Are your logs for make or cmake?

**Comment by ManrajGrover** [comment]
@pseudotensor The logs were of `make` command. I just pulled and tried latest HEAD and it worked! Thank you for your help.

I've also tried running the benchmarks and it worked as expected. Now, when I try running my code, it threw illegal memory access error. Please find the logs attached below.

```
[16:30:41] dmlc-core/include/dmlc/./logging.h:300: [16:30:41] plugin/updater_gpu/src/updater_gpu.cu:40: GPU plugin exception: plugin/updater_gpu/src/exact/../device_helpers.cuh(338): an illegal memory access was encountered


Stack trace returned 10 entries:
[bt] (0) /home/enuser/virtualenvs/ds/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/libxgboost.so(_ZN4dmlc15LogMessageFatalD2Ev+0x39) [0x7f40a22c19d9]
[bt] (1) /home/enuser/virtualenvs/ds/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/libxgboost.so(_ZN7xgboost4tree8GPUMaker6UpdateERKSt6vectorINS_9bst_gpairESaIS3_EEPNS_7DMatrixERKS2_IPNS_7RegTreeESaISB_EE+0x237) [0x7f40a2458b5f]
[bt] (2) /home/enuser/virtualenvs/ds/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/libxgboost.so(_ZN7xgboost3gbm6GBTree13BoostNewTreesERKSt6vectorINS_9bst_gpairESaIS3_EEPNS_7DMatrixEiPS2_ISt10unique_ptrINS_7RegTreeESt14default_deleteISB_EESaISE_EE+0x83f) [0x7f40a23815ef]
[bt] (3) /home/enuser/virtualenvs/ds/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/libxgboost.so(_ZN7xgboost3gbm6GBTree7DoBoostEPNS_7DMatrixEPSt6vectorINS_9bst_gpairESaIS5_EEPNS_11ObjFunctionE+0xa60) [0x7f40a23829d0]
[bt] (4) /home/enuser/virtualenvs/ds/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/libxgboost.so(_ZN7xgboost11LearnerImpl13UpdateOneIterEiPNS_7DMatrixE+0x22b) [0x7f40a22cfbdb]
[bt] (5) /home/enuser/virtualenvs/ds/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/libxgboost.so(XGBoosterUpdateOneIter+0x27) [0x7f40a22d7287]
[bt] (6) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7f41305f0adc]
[bt] (7) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x1fc) [0x7f41305f040c]
[bt] (8) /home/enuser/virtualenvs/ds/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(_ctypes_callproc+0x48e) [0x7f41308075fe]
[bt] (9) /home/enuser/virtualenvs/ds/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(+0x15f9e) [0x7f4130808f9e]
```

Parameters used were:

```
'n_gpus': 1
'gpu_id': 1
'tree_method': 'gpu_exact'
```

On checking the GPU memory usage, it was just ` 573MiB /  6077MiB` with XGBoost taking only `262 MiB`. Is there any upper limit to GPU usage? If no, any fix for this? I couldn't find any relevant issues on Github for this.

**Comment by RAMitchell** [comment]
Can you please provide a script and the source of the data so we can reproduce the error.

**Comment by ManrajGrover** [comment]
@RAMitchell Please find the zip file containing script and dataset attached. Let me know if link does not work. :smile: 

https://filetea.me/n3w6kdqSxsYRx6hr0IhIrNzbw

**Comment by RAMitchell** [comment]
404 error

**Comment by ManrajGrover** [comment]
@RAMitchell Please find the updated Google Drive link here: https://goo.gl/w91UD4
The system has only one GPU (GeForce GTX 980 Ti).

**Comment by ManrajGrover** [comment]
@RAMitchell Any update on this?
