### ISSUE TITLE
Check failed: label_correct PoissonRegression: label must be nonnegative

### ISSUE THREAD

**Issue by Lah123** [dmlc/xgboost#2467]
Hi! 

I'm using a windows 10 laptop with R and xgboost version 0.6-4. I'm getting a weird error when running the following code.

 ```
 xgb_params <- list("objective" = "count:poisson",
                     "eval_metric" = "rmse")
  regression <- xgboost(data = training_fold, 
                        label = y_training_fold, 
                        nrounds = 10,
                        params = xgb_params)
```

Error in xgb.iter.update(bst$handle, dtrain, iteration - 1, obj) : 
amalgamation/../src/objective/regression_obj.cc:190: Check failed: label_correct PoissonRegression: label must be nonnegative

But when I look at the summary of the label it states: 
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
 0.1129  0.3387  0.7000  1.0987  1.5265  4.5405     287 

How can I fix this? I tried to remove the NA's, but that did not help. 

Thanks in advance!

**Comment by khotilov** [comment]
This error would happen when any label value is not non-negative, including NA. Please double-check that you did in fact remove rows with NA values. If the problem persists, please provide a minimal reproducible example.
