### ISSUE TITLE
USE_HDFS broken after cmake introduction?

### ISSUE THREAD

**Issue by edi-bice** [dmlc/xgboost#2468]
I'm building xgboost latest master using the same old settings needed to compile and link it with HDFS

cd xgboost/dmlc-core/
vim make/config.mk
USE_OPENMP = 1
USE_HDFS = 1 
cd ..
cp make/config.mk .
vim config.mk
USE_HDFS = 1 

Now I keep getting the following error and I suspect it's the introduction of cmake

[14:28:52] /root/xgboost/dmlc-core/include/dmlc/logging.h:300: [14:28:52] /root/xgboost/dmlc-core/src/io.cc:37: Please compile with DMLC_USE_HDFS=1 to use hdfs

Has anyone built xgboost recently with HDFS support and where is the equivalent cmake setting?

**Comment by edi-bice** [comment]
appears to be a user/environment issue - closing

**Comment by hzliang** [comment]
@edi-bice  I get the same problem, how do you solve it? Thank you

**Comment by superbobry** [comment]
Note that the JVM build does not use `*.mk` and relies on the constants in `create_jni.py`.

**Comment by hzliang** [comment]
I implement it using another way, I first save the model file by xgboost.booster.saveModel("local"), then use hdfs java api to upload the model to hdfs, so I can download the file from the node that I can access in my company cluster.

**Comment by edi-bice** [comment]
@hzliang please edit the jvm-packages/create_jni.py file @superbobry mentioned and change USE_HDFS to ON - by default it is OFF.

**Comment by edi-bice** [comment]
@hzliang if you're not building for the JVM, look at xgboost/dmlc-core/make/config.mk and change USE_HDFS to 1

**Comment by hzliang** [comment]
@edi-bice Thank you for your replying. Yes, I compile it success using USE_HDFS = 1 or USE_HDFS=ON, but I run xgboost on yarn(use spark-submit), saving model using  xgboost.booster.savemodel("hdfs://xxx xxx"), but throw exception: Please compile with DMLC_USE_HDFS=1 to use hdfs, the hadoop classpath maybe wrong?

**Comment by edi-bice** [comment]
@hzliang Not sure about spark-submit as I use "dmlc-submit --cluster=yarn" but here's what I had to do in the launcher to get it to find HDFS headers/libs

diff --git a/tracker/dmlc_tracker/launcher.py b/tracker/dmlc_tracker/launcher.py
index 20fdcfe..f2b6b7d 100755
--- a/tracker/dmlc_tracker/launcher.py
+++ b/tracker/dmlc_tracker/launcher.py
@@ -22,7 +22,8 @@ def main():
         sys.exit(0)

     hadoop_home = os.getenv('HADOOP_HOME')
-    hdfs_home = os.getenv('HADOOP_HDFS_HOME')
+    #hdfs_home = os.getenv('HADOOP_HDFS_HOME')
+    hdfs_home = "/usr/hdp/2.5.0.0-1245/usr"

**Comment by edi-bice** [comment]
@hzliang and here some changes for cmake (not sure why any more, it's possible it is a Hortonworks Hadoop thing)

diff --git a/cmake/Modules/FindHDFS.cmake b/cmake/Modules/FindHDFS.cmake
index 17f5a4f..370a679 100644
--- a/cmake/Modules/FindHDFS.cmake
+++ b/cmake/Modules/FindHDFS.cmake
@@ -12,7 +12,7 @@ exec_program(hadoop ARGS version OUTPUT_VARIABLE Hadoop_VERSIO

 \# currently only looking in HADOOP_HOME
 find_path(HDFS_INCLUDE_DIR hdfs.h PATHS
\-  $ENV{HADOOP_HOME}/include/
\+  $ENV{HADOOP_HDFS_HOME}/include/
   \# make sure we don't accidentally pick up a different version
   NO_DEFAULT_PATH
 )
@@ -28,9 +28,9 @@ endif()
 message(STATUS "Architecture: ${arch_hint}")

 if ("${arch_hint}" STREQUAL "x64")
\-  set(HDFS_LIB_PATHS $ENV{HADOOP_HOME}/lib/native)
\+  set(HDFS_LIB_PATHS $ENV{HADOOP_HDFS_HOME}/lib/native)
 else ()
\-  set(HDFS_LIB_PATHS $ENV{HADOOP_HOME}/lib/native)
\+  set(HDFS_LIB_PATHS $ENV{HADOOP_HDFS_HOME}/lib/native)
