### ISSUE TITLE
Releasing 0.4

### ISSUE THREAD

**Issue by tqchen** [dmlc/xgboost#247]
There has been lots of changes since 0.3 and I think it is reasonable time for making a 0.4 release version. There are several things we need to do to prepare a clean release

 - [ ] @pommedeterresautee @hetong007 can you double check if the R package so far can be installed on all platforms, and pass cran check (it is good to keep the standard)
 - [ ] Take a look at current documents, I have done some movements to move the documents to the doc folder, see if there is anything we can do to improve it
 - [x] Review the pending pull request and pull them in if necessary.
 - [ ] Change the version number in R DESCRIPTION and python to reflect the version 0.40

Thanks

**Comment by pommedeterresautee** [comment]
No issue after re installation in Windows.

**Comment by hetong007** [comment]
@pommedeterresautee There's one `NOTE` in the CRAN check:

```
* checking R code for possible problems ... NOTE
xgb.plot.importance: no visible global function definition for ‘ggplot’
xgb.plot.importance: no visible global function definition for ‘aes’
xgb.plot.importance: no visible global function definition for
  ‘geom_bar’
xgb.plot.importance: no visible global function definition for
  ‘coord_flip’
xgb.plot.importance: no visible global function definition for ‘xlab’
xgb.plot.importance: no visible global function definition for ‘ylab’
xgb.plot.importance: no visible global function definition for
  ‘ggtitle’
xgb.plot.importance: no visible global function definition for ‘theme’
xgb.plot.importance: no visible global function definition for
  ‘element_text’
xgb.plot.importance: no visible global function definition for
  ‘element_blank’
```

Do you mind to fix it? Thank you.

**Comment by pommedeterresautee** [comment]
I have made a PR but I have no access to Linux box right now. I don't think there will be surprise but if you can't check I will do myself in 2 weeks.

Kind regards,
Michaël
