### ISSUE TITLE
【jvm packages】Why I get the prediction all 0 when I reload the model?

### ISSUE THREAD

**Issue by lycrechal** [dmlc/xgboost#2472]
val model=xgb.fit(trainingdf)
val outputModelPath = "---"
model.saveModelAsHadoopFile(outputModelPath)

val model2=XGBoost.loadModelFromHadoopFile(outputModelPath)
val predictions = model2.transform(testdf)
predictions.show()

My code just like that.
If I train the model and then predict I can get the correct answer(the prediction not all 0)
But If I save the model and load it,and then I do the predict, at this time, all the predictions show 0

**Comment by CodingCat** [comment]
is it related to https://github.com/dmlc/xgboost/pull/2172?

**Comment by lycrechal** [comment]
Thanks for your answer. @CodingCat But I think may be it can not solve my question.
I don't know why the model would be changed if I reload it?

**Comment by CodingCat** [comment]
it should not, what I refer to is a bug fix 

I was asking if you fall into the situation described there....

**Comment by lycrechal** [comment]
Sorry, Longtime no reply to you. The situation just a little similar

**Comment by CodingCat** [comment]
are you using multi classes?

**Comment by lycrechal** [comment]
Yes

**Comment by CodingCat** [comment]
then that's the problem, you can pick up the changes in that PR to fix the issue

**Comment by lycrechal** [comment]
OK, I will have a try. Sincerely thanks to you.

**Comment by lycrechal** [comment]
By the way, Do you know how to retrain the xgboost model in spark?
