### ISSUE TITLE
Unable to pass attribute "booster" to XGBClassifier (python)

### ISSUE THREAD

**Issue by ikamensh** [dmlc/xgboost#2486]
## Environment info
Operating System:
Ubuntu

`xgboost` version used: python 0.6
>>> xgboost.__version__
'0.6'

If you are using python package, please provide

1. The python version and distribution
2. The command to install `xgboost` if you are not installing from source
ikamenshchikov@giskard-remote:~/MLBootCampV$ python3 -V
Python 3.5.3
pip3 install xgboost

## Steps to reproduce

1. XGBClassifier(booster = 'gbtree', objective='binary:logistic')
```
TypeError: __init__() got an unexpected keyword argument 'booster'
```

## What have you tried?

1. passing arguement as constructor
2. passing arguement with parameters (clf.train(params,..
```
Invalid parameter booster for estimator XGBClassifier. Check the list of available parameters w
ith `estimator.get_params().keys()
```
3. checked 'estimator.get_params().keys():
```
dict_keys(['min_child_weight', 'learning_rate', 'objective', 'subsample', 'reg_alpha', 'gamma', 'missing', 
'n_estimators', 'silent', 'reg_lambda', 'max_depth', 'colsample_bytree', 'max_delta_step', 'colsample_bylev
el', 'base_score', 'scale_pos_weight', 'seed', 'nthread'])
```

booster is not among them!

**Comment by yukw777** [comment]
I'm seeing this issue as well.

**Comment by morganmcg1** [comment]
Yes I am also having this issue

**Comment by bananamashine** [comment]
I'm struggling too and this is pretty important one so i bump this thread

**Comment by khotilov** [comment]
The pypi package is too old (the python package version version is currently meaningless). Install the latest code from github.

**Comment by transposition** [comment]
I have built the latest xgboost of vesion 0.6a2, but  still not support "booster"

**Comment by FrugoFruit90** [comment]
I have the same issue 😢  
Interestingly, it works on CentOS (where I try to do hyperparameter optimization), but not on Windows

**Comment by diwadd** [comment]
I having the same issue with xgboost 0.7 under Mint Linux.
