### ISSUE TITLE
Scaling matters?

### ISSUE THREAD

**Issue by cjiang3** [dmlc/xgboost#2491]
Hello,

I used xgboost and it generated very different result when I simply divide the features say by 10 or 100. Should that happen in theory or just my dataset?

**Comment by pommedeterresautee** [comment]
Trees are known to be relatively not sensitive to feature scaling (compared to linear models for instance).
Trees are also known for being unstable (different split at the root and the whole tree will have a different structure).
From what I have seen, scaling may have an impact, but not huge, on the accuracy of the model.
You need to have in mind that even multi threading can impact slightly the accuracy of the model.
