### ISSUE TITLE
Retrain Xgboost Model

### ISSUE THREAD

**Issue by lycrechal** [dmlc/xgboost#2495]
Hello everbody. I have some questions. If I train a xgboost model, and I save it. How can I use new trainingdata to train the saved model. And what is the best way to save the model. I don't know how to write? Thanks all.

**Comment by hcho3** [comment]
I am not sure if I understood your question correctly; are you looking for a way to incrementally update the model given the new data? Currently, XGBoost does not support incremental training. If you have new batch of training data, you'd need to combine it with old training data and re-train a new model from scratch.

Incremental trees are something one of us might look at in the future, but for now there is no plan for its support.

**Comment by lycrechal** [comment]
OK, Thanks for your help!

**Comment by Liwink** [comment]
@lycrechal If you want to continue to train a stored xgb model, you can try parameter `xgb_model` in Python like this:

```python
"""
## https://github.com/dmlc/xgboost/pull/493
## the param structure for xgboost is set here
"""
num_round = 10
tmpFile = None
for i in range(10):
        print ('Epoch %d: Training xgboost' % i); sys.stdout.flush()
        bst = xgb.train(param, dtrain, num_round/10, watchlist, xgb_model=tmpFile );
        tmpFile = modelFile + ".intermediate"
        print ('Epoch %d: Saving model to %s' %(i, tmpFile)); sys.stdout.flush()
        bst.save_model(tmpFile)
        del bst
```
