### ISSUE TITLE
 [jvm-packages]  spark4j can not find libxgboost4j.so on some executors

### ISSUE THREAD

**Issue by antant-shenzhen-2013** [dmlc/xgboost#2497]
## Environment info
Operating System: centos 7

Compiler: gcc
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4)

`xgboost` version used: 0.7

![spark-xgboost bugs](https://user-images.githubusercontent.com/5409502/27952523-22c2bfec-633b-11e7-86cf-dc3135249697.png)

**Comment by superbobry** [comment]
Are you building `master`? This shouldn't be the case after 2cb51f7097df44f7f2993d47865b0090194e2dc4.

**Comment by antant-shenzhen-2013** [comment]
thx. now I fetch the latest commit and build successfully.  BUT when training with dataframe, it pop up some other errors.  

> java.lang.NoClassDefFoundError: Could not initialize class ml.dmlc.xgboost4j.java.XGBoostJNI

the jar I submit to spark contains such class as i checked. 
Am I missing sth, any suggestion?

![image](https://user-images.githubusercontent.com/5409502/28048949-bc7b909e-6626-11e7-99a4-995a498b9973.png)

**Comment by superbobry** [comment]
Have you built the library in the same environment it is running in? Could you lookup `libxgboost4j.so` in the build directory and do `ldd` on it?

**Comment by antant-shenzhen-2013** [comment]
built on centOS 7.x, BUT there are versions 6.x and 7.x in the cluster.
do not know whether it matters or not.

can find libxgboost4j.so and ld on it
![image](https://user-images.githubusercontent.com/5409502/28099072-b27c4a40-66ec-11e7-94ab-d1e7cb2627a7.png)

**Comment by superbobry** [comment]
6.x and 7.x have different libc versions. If you want to run on both, you'd need to compile on 6.x.

You've called `ld` instead of `ldd`. Could you call `ldd` and post just the output?

**Comment by antant-shenzhen-2013** [comment]
i see.

> 
> ldd libxgboost4j.so
> 
> 	linux-vdso.so.1 =>  (0x00007fff56fcf000)
> 	libjvm.so => /usr/lib/jvm/jre/lib/amd64/server/libjvm.so (0x00007fb47bdf3000)
> 	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fb47badb000)
> 	libm.so.6 => /lib64/libm.so.6 (0x00007fb47b7d9000)
> 	libgomp.so.1 => /lib64/libgomp.so.1 (0x00007fb47b5c2000)
> 	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fb47b3ab000)
> 	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fb47b18f000)
> 	libc.so.6 => /lib64/libc.so.6 (0x00007fb47adce000)
> 	/lib64/ld-linux-x86-64.so.2 (0x00007fb47d142000)
> 	libdl.so.2 => /lib64/libdl.so.2 (0x00007fb47abc9000)

**Comment by superbobry** [comment]
Okay, nothing very suspicious. Can you try compiling at 6.x?

**Comment by antant-shenzhen-2013** [comment]
tried, but not build successfully.

>  [ 96%] Built target xgboost
> [100%] Built target xgboost4j
> building Java wrapper
> cd ..
> mkdir -p build
> cd build
> cmake .. -DUSE_S3:BOOL=OFF -DUSE_OPENMP:BOOL=ON -DPLUGIN_UPDATER_GPU:BOOL=OFF -DUSE_AZURE:BOOL=OFF -DUSE_HDFS:BOOL=OFF -DJVM_BINDINGS:BOOL=ON
> cmake --build . --config Release
> cd demo/regression
> /usr/local/bin/python mapfeat.py
> /usr/local/bin/python mknfold.py machine.txt 1
> copying native library
> mkdir -p xgboost4j/src/main/resources/lib
> cp ../lib/libxgboost4j.so xgboost4j/src/main/resources/lib
> copying pure-Python tracker
> cp ../dmlc-core/tracker/dmlc_tracker/tracker.py xgboost4j/src/main/resources
> copying train/test files
> mkdir -p xgboost4j-spark/src/test/resources
> cd ../demo/regression
> Traceback (most recent call last):
>   File "create_jni.py", line 112, in <module>
>     run("{} mknfold.py machine.txt 1".format(sys.executable))
>   File "/usr/lib64/python2.6/contextlib.py", line 34, in __exit__
>     self.gen.throw(type, value, traceback)
>   File "create_jni.py", line 34, in cd
>     yield path
>   File "create_jni.py", line 111, in <module>
>     run("{} mapfeat.py".format(sys.executable))
> ValueError: zero length field name in format
> [ERROR] Command execution failed.
> org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)

**Comment by antant-shenzhen-2013** [comment]
compiled successfully on CentOS 6 and Java 7.  BUT when training the model, it block so many hours without processing. 

>  [Stage 24:>                                                    (0 + 320) / 1000]

**Comment by superbobry** [comment]
How do you validate that no processing is happening? Idle CPU for the executor processes?

**Comment by CodingCat** [comment]
how many cores do you have in your cluster, and what's the value you pass to the numWorkers parameter?

**Comment by antant-shenzhen-2013** [comment]
once I set numWorkers  equal to num of cores, it works.
thx.

**Comment by xiaomeibb** [comment]
make sure you have install all soft  like g++;   I had this problem ,because some servers didn`t have g++
确保每台机器上都有必要的软件。我曾经遇到这个问题是因为我在部分机器上没有安装g++。如果你不能确认你的机器是否有所有需要的软件，请在所有机器上尝试编译jvm-package，这样它就会提示你缺少的软件。
