### ISSUE TITLE
Record/Save the training progress

### ISSUE THREAD

**Issue by yzliao** [dmlc/xgboost#250]
Is it possible to record the training progress? Currently, the training results for each update are printed. Is it possible to save them into a file? It will be very helpful to plot the error and to figure out if the model is overfitted.

**Comment by tqchen** [comment]
Do you mean the distributed version or python/R? It is possible to do so in python/R, we are planning to add log options to distributed version as well

**Comment by yzliao** [comment]
I mean python/R since this is the version I am using now.

**Comment by tqchen** [comment]
Yes, I think it is possible.  I think xgb.cv returns the validation history. On the other hand, the train function simply writes the history to stderr in python, I think we can change that by optionally passing in a holder(list) of the result, if you are interested, you can make a PR on that

**Comment by yzliao** [comment]
Great, I will have a try then

**Comment by yzliao** [comment]
Should we close this issue since it has been merged?
