### ISSUE TITLE
I am able to import xgboost as : import xgboost as xgb  ; but not able to see any attribute for xgboost , and whenever i am using XGBClassifier or Dmatrix , on windows, it says no attribute found. Please help !

### ISSUE THREAD

**Issue by lktyagi88** [dmlc/xgboost#2500]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System:

Compiler:

Package used (python/R/jvm/C++):

`xgboost` version used:

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`)
2. Logs will be helpful (If logs are large, please upload as attachment).

If you are using jvm package, please 

1. add [jvm-packages] in the title to make it quickly be identified
2. the gcc version and distribution

If you are using python package, please provide

1. The python version and distribution
2. The command to install `xgboost` if you are not installing from source

If you are using R package, please provide

1. The R `sessionInfo()`
2. The command to install `xgboost` if you are not installing from source

## Steps to reproduce

1.
2.
3.

## What have you tried?

1.
2.
3.

**Comment by superbobry** [comment]
@lktyagi88 please fill in the form in the issue with relevant details in order for the others to help you.

**Comment by pseudotensor** [comment]
If you just enter python interactive interpreter and do import xgboost and then help(xgboost) what do you see?  You may have an xgboost.py file sitting around that overrides the module.
