### ISSUE TITLE
[R-package] OpenMP is not available

### ISSUE THREAD

**Issue by qubz** [dmlc/xgboost#2503]
## Environment info
**Operating System:**
ProductName:	Mac OS X
ProductVersion:	10.12.5
BuildVersion:	16F73

**Compiler:**
brew llvm

**Package used (python/R/jvm/C++):**
R

`xgboost` version used:
0.6.4.6

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`)
`be1f76a06acbacb9d925cccb338fae82fb9d2743`

If you are using R package, please provide

1. The R `sessionInfo()`

`> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.5`

`Matrix products: default
BLAS: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib`

`locale:
[1] en_AU.UTF-8/en_AU.UTF-8/en_AU.UTF-8/C/en_AU.UTF-8/en_AU.UTF-8`

`attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     `

`loaded via a namespace (and not attached):
[1] compiler_3.4.0`

2. The command to install `xgboost` if you are not installing from source
`R-package qubz$ R CMD INSTALL .`
## Steps to reproduce

`brew install llvm`
`cd /usr/local/lib`
`ln -s /usr/local/Cellar/llvm/LLVM_VERSION/lib/libomp.dylib libomp.dylib`
`export CC=/usr/local/Cellar/llvm/LLVM_VERSION/bin/clang`
`export CXX=/usr/local/Cellar/llvm/LLVM_VERSION/bin/clang++`

Set `CC` and `CCX` in both `Makefile` and `make/config.mk`
`cd xgboost; cp make/config.mk ./config.mk; make -j4` 

**NOTE: building from source successfully builds a multithreaded version:**
`$ bash build.sh`
`make: Nothing to be done for all'.`
`Successfully build multi-thread xgboost`

`cd R-package`
`R CMD INSTALL .`
`...checking whether OpenMP will work in a package... no`
`Warning: OpenMP is not available, project will be compiled into
      single-thread code. Use OpenMP-enabled compiler to get benefit of multi-threading....`

## What have you tried?

1. brew's llvm
2. brew's gcc7
3. drat repo build instructions
4. `install.packages(...)` alternative install method through R in the directory after building from source 

[error_log.txt](https://github.com/dmlc/xgboost/files/1134217/error_log.txt)

**Comment by qubz** [comment]
#2415

**Comment by qubz** [comment]
#2415

**Comment by gabsens** [comment]
have you solved the `...checking whether OpenMP will work in a package... no` issue ?

**Comment by qubz** [comment]
Nope. I just saw the issue you commented on #2631 and gave it another shot. No joy. Looks like the maintainers are doing other stuff as of late regarding macOS compile issues.

**Comment by shkmik** [comment]
Could compile and install (R CMD INSTALL .) multithreaded version after manually setting "ac_pkg_openmp=yes" in xgboost/R-package/configure:1676 (hash: be1f76a06acbacb9d925cccb338fae82fb9d2743). 

Before installed R 3.4.1, clang4, configured ~/.R/Makevars

**Comment by gabsens** [comment]
@shkmik you manually coerced the OpenMP test

```
#include <omp.h>
int
main ()
{
 return omp_get_num_threads ();
  ;
  return 0;
}
```

to always be true. Doesn't sound like a proper installation to me... Do you have proofs that the resulting xgboost package supports multithreading ?

**Comment by gabsens** [comment]
Ok, your hack seems to work. Seems like the people who maintain the R package messed up when editing the code that checks for OpenMP (it's pasted from [here](https://stat.ethz.ch/pipermail/r-devel/2010-September/058488.html)).

I did something a bit different from @shkmik : I just removed [this](https://github.com/dmlc/xgboost/blob/master/R-package/configure#L1693) if block in `R-package/configure`. The resulting R package supports multithreading, you can confirm by running this piece of code 

```
require(xgboost)
 x = matrix(rnorm(100*10000), 10000, 100)
 y = x %*% rnorm(100) + rnorm(1000)

  system.time({
       bst = xgboost(data = x, label = y, nthread = 1, nround = 100, verbose = FALSE)
     })


system.time({
       bst = xgboost(data = x, label = y, nthread = 4, nround = 100, verbose = FALSE)
   })
```

Check the activity monitor as well if you want.

**Comment by aaronpolhamus** [comment]
@gabsens I tried this and it still seems to be running single-threaded mode. any other tips? I uninstalled using `remove.packages` in he GUI, but I'm worried that since I did the initial build, which was single-threaded with `R CMD INSTALL .` that the make is stuck with single-threaded setting.

**Comment by borisclemencon** [comment]
Still struggling with having xgboost working parallel with R 3.5.1 and OS X 10.12.6. It seems to be openMP OK when compiling C code, but when compiling in R, cannot find the ```-fopenmp``` option.

**Makevars**

```
cat ~/.R/Makevars 
```

```
CC=gcc-7
CXX=g++-7
CXX1X=g++-7
CXX11=g++-7
CXX14=g++-7
CXX17=g++-7

SHLIB_OPENMP_CFLAGS=-fopenmp
SHLIB_OPENMP_CXXFLAGS=-fopenmp
SHLIB_OPENMP_FCFLAGS=-fopenmp
SHLIB_OPENMP_FFLAGS=-fopenmp
```

I tried gcc-8 too without success.

**Experiments:**

- Compile C code: ```xgboost$ make -j4``` => seems to work, ```-fopenmp``` compiler option is included:
```
g++-7 -c -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp src/common/common.cc -o build/common/common.o
```
- From source: ```R-package$ R CMD INSTALL .``` => ```checking whether OpenMP will work in a package... no```
```
g++-7 -std=gnu++11 -I"/usr/local/Cellar/r/3.5.1/lib/R/include" -DNDEBUG -I../..//include -I../..//dmlc-core/include -I../..//rabit/include -I../../ -DXGBOOST_STRICT_R_MODE=1 -DDMLC_LOG_BEFORE_THROW=0 -DDMLC_ENABLE_STD_THREAD=1 -DDMLC_DISABLE_STDIN=1 -DDMLC_LOG_CUSTOMIZE=1 -DXGBOOST_CUSTOMIZE_LOGGER=1 -DRABIT_CUSTOMIZE_MSG_ -DRABIT_STRICT_CXX98_  -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/include   -fPIC  -g -O2 -c xgboost_R.cc -o xgboost_R.o
```

Any idea?

**Comment by hcho3** [comment]
@borisclemencon Try using CMake:
```
mkdir build
cd build
cmake .. -DCMAKE_C_COMPILER=gcc-7 -DCMAKE_CXX_COMPILER=g++-7 -DR_LIB=ON
make
make install
```
The last `make install` may fail. If that happens, run
```
# still inside build/
cd R-package
mv src/libxgboost.dylib src/xgboost.so
R CMD INSTALL .
```

**Comment by borisclemencon** [comment]
Holly cow! it worked. Big up to hcho3! Can you give more explainations?

**Comment by hcho3** [comment]
@borisclemencon So far I didn't have much success with modifying `Makevars`, since it gets overwritten by the `configure` script in `R-package`. When it comes to applying custom build options, it's IMO much easier to use CMake, which will generate `configure` and other build files in the R package (hence `R-package` directory gets generated under the `build/`)

**Comment by hcho3** [comment]
On a side note, issues like this makes me hugely prefer CMake over GNU Make for any new projects: much easier to incorporate custom build flags and multiple targets and platforms.

**Comment by borisclemencon** [comment]
Great! FYI, in my case, came generated a lib called ```xgboost.dylib```. I had to change your script a little:

     mv src/xgboost.dylib src/xgboost.so

Thanks
