### ISSUE TITLE
[jvm packages] How to train multiple independent Xgboost model parallelly in spark ?

### ISSUE THREAD

**Issue by kamushin** [dmlc/xgboost#2505]
I want to read multiple train-data files in a dir, and training multiple models for each data file.
Since xgboost model has `SparkContext` as part of the class, and `SparkContext` is not **Serializable**, I can't put xgboost model and dataFormat into a `RDD`. 
How to train multiple independent Xgboost model parallelly in spark ?

**Comment by superbobry** [comment]
Could you give a bit more details on what you want to do? Specifically, why do you need the model to be serializable? Do you plan to train a model per partition?

**Comment by kamushin** [comment]
@superbobry Yes, I want to train a model per partition.

**Comment by superbobry** [comment]
Then you don't need to use xgboost4j-spark, since the data is already distributed and you don't need a separate distributed training for the partition data. Try using `XGBoost` from xgboost4j (note lack of -spark suffix).

**Comment by kamushin** [comment]
Thx.

**Comment by kamushin** [comment]
@superbobry I've noticed that `XGBoost` from xgboost4j read data from local file system and store model to local file system. How can I use xgboost4j with Spark and HDFS?

**Comment by LucasEstevam** [comment]
Also interested in this. Apparently xgboost4j-spark is not supposed to be run in parallel in the same cluster? Would be very useful for tuning.

**Comment by superbobry** [comment]
@kamushin I think you can use HDFS with `xgboost4j` if you compile it with HDFS support (see `USE_HDFS` in [`create_jni.py`](https://github.com/dmlc/xgboost/blob/master/jvm-packages/create_jni.py)).

@LucasEstevam are you referring to #2449 or a different issue?

**Comment by LucasEstevam** [comment]
@superbobry Yes. I'm wondering if anyone has any working sample code of running e.g. cross validation in parallel.
