### ISSUE TITLE
Building R library with G++5.4 brings in the nullptr error (similar to issue 1393)

### ISSUE THREAD

**Issue by ocschwar** [dmlc/xgboost#2506]
The internet says the g++ command lines need to add "'-std=c++11' to solve the issue, and I'm trying to find where in the R library build setup I have to put it in. 

## Environment info
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

Compiler:

omri@SERVER2:~/xgboost/R-package$ g++ --version
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

Package used (python/R/jvm/C++):

R

1. The commit hash (`git rev-parse HEAD`)
omri@SERVER2:~/xgboost/R-package$ git rev-parse HEAD
be1f76a06acbacb9d925cccb338fae82fb9d2743

2. Logs will be helpful (If logs are large, please upload as attachment).
omri@SERVER2:~/xgboost/R-package$ R CMD INSTALL .
* installing to library ‘/home/omri/R/x86_64-pc-linux-gnu-library/3.3’
* installing *source* package ‘xgboost’ ...
configure: creating ./config.status
config.status: creating src/Makevars
** libs
g++  -I/usr/share/R/include -DNDEBUG -I../..//include -I../..//dmlc-core/include -I../..//rabit/include -I../../ -DXGBOOST_STRICT_R_MODE=1 -DDMLC_LOG_BEFORE_THROW=0 -DDMLC_ENABLE_STD_THREAD=1 -DDMLC_DISABLE_STDIN=1 -DDMLC_LOG_CUSTOMIZE=1 -DXGBOOST_CUSTOMIZE_LOGGER=1 -DRABIT_CUSTOMIZE_MSG_ -DRABIT_STRICT_CXX98_    -fopenmp  -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-6WVosl/r-base-3.3.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c xgboost_R.cc -o xgboost_R.o
In file included from xgboost_R.cc:2:0:
../..//dmlc-core/include/dmlc/logging.h: In constructor ‘dmlc::LogCheckError::LogCheckError()’:
../..//dmlc-core/include/dmlc/logging.h:66:25: error: ‘nullptr’ was not declared in this scope
   LogCheckError() : str(nullptr) {}
                         ^
../..//dmlc-core/include/dmlc/logging.h: In destructor ‘dmlc::LogCheckError::~LogCheckError()’:
../..//dmlc-core/include/dmlc/logging.h:68:33: error: ‘nullptr’ was not declared in this scope
   ~LogCheckError() { if (str != nullptr) delete str; }
                                 ^
../..//dmlc-core/include/dmlc/logging.h: In member function ‘dmlc::LogCheckError::operator bool()’:
../..//dmlc-core/include/dmlc/logging.h:69:34: error: ‘nullptr’ was not declared in this scope
   operator bool() {return str != nullptr; }
                                  ^
In file included from xgboost_R.cc:2:0:
../..//dmlc-core/include/dmlc/logging.h: In destructor ‘dmlc::LogMessageFatal::~LogMessageFatal()’:
../..//dmlc-core/include/dmlc/logging.h:289:17: error: ‘nullptr’ was not declared in this scope
     if (msgs != nullptr) {
                 ^
xgboost_R.cc: In function ‘SEXPREC* XGBoosterSetAttr_R(SEXP, SEXP, SEXP)’:
xgboost_R.cc:419:33: error: ‘nullptr’ was not declared in this scope
   const char *v = isNull(val) ? nullptr : CHAR(asChar(val));
                                 ^
/usr/lib/R/etc/Makeconf:139: recipe for target 'xgboost_R.o' failed
make: *** [xgboost_R.o] Error 1

If you are using R package, please provide

1. The R `sessionInfo()`

> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.2 LTS

**Comment by ocschwar** [comment]
Editing Makevars.in to add that flag resolved the issue for me. But I don;t know how to DTRT and leave it compatible with Windows and Mac, so I'll leave this as a ticket rahter than a pull request.

**Comment by ocschwar** [comment]
`omri@SERVER2:~/xgboost/R-package$  git diff
diff --git a/R-package/src/Makevars.in b/R-package/src/Makevars.in
index 26aa538..d35b215 100644
--- a/R-package/src/Makevars.in
+++ b/R-package/src/Makevars.in
@@ -10,7 +10,7 @@ XGB_RFLAGS = -DXGBOOST_STRICT_R_MODE=1 -DDMLC_LOG_BEFORE_THROW=0\
            -DDMLC_LOG_CUSTOMIZE=1 -DXGBOOST_CUSTOMIZE_LOGGER=1\
            -DRABIT_CUSTOMIZE_MSG_ -DRABIT_STRICT_CXX98_
 
-PKG_CPPFLAGS=  -I$(PKGROOT)/include -I$(PKGROOT)/dmlc-core/include -I$(PKGROOT)/rabit/include -I$(PKGROOT) $(XGB_RFLAGS)
+PKG_CPPFLAGS= -std=c++11 -I$(PKGROOT)/include -I$(PKGROOT)/dmlc-core/include -I$(PKGROOT)/rabit/include -I$(PKGROOT) $(XGB_RFLAGS)
 PKG_CXXFLAGS= @OPENMP_CXXFLAGS@ $(SHLIB_PTHREAD_FLAGS)
 PKG_LIBS = @OPENMP_CXXFLAGS@ $(SHLIB_PTHREAD_FLAGS)
 OBJECTS= ./xgboost_R.o ./xgboost_custom.o ./xgboost_assert.o ./init.o\
`

**Comment by ocschwar** [comment]
`omri@SERVER2:~/xgboost/R-package$  git diff
diff --git a/R-package/src/Makevars.in b/R-package/src/Makevars.in
index 26aa538..d35b215 100644
--- a/R-package/src/Makevars.in
+++ b/R-package/src/Makevars.in
@@ -10,7 +10,7 @@ XGB_RFLAGS = -DXGBOOST_STRICT_R_MODE=1 -DDMLC_LOG_BEFORE_THROW=0\
            -DDMLC_LOG_CUSTOMIZE=1 -DXGBOOST_CUSTOMIZE_LOGGER=1\
            -DRABIT_CUSTOMIZE_MSG_ -DRABIT_STRICT_CXX98_
 
-PKG_CPPFLAGS=  -I$(PKGROOT)/include -I$(PKGROOT)/dmlc-core/include -I$(PKGROOT)/rabit/include -I$(PKGROOT) $(XGB_RFLAGS)
+PKG_CPPFLAGS= -std=c++11 -I$(PKGROOT)/include -I$(PKGROOT)/dmlc-core/include -I$(PKGROOT)/rabit/include -I$(PKGROOT) $(XGB_RFLAGS)
 PKG_CXXFLAGS= @OPENMP_CXXFLAGS@ $(SHLIB_PTHREAD_FLAGS)
 PKG_LIBS = @OPENMP_CXXFLAGS@ $(SHLIB_PTHREAD_FLAGS)
 OBJECTS= ./xgboost_R.o ./xgboost_custom.o ./xgboost_assert.o ./init.o\
`

**Comment by khotilov** [comment]
Some things are odd here... Note that src/Makevers.in already has `CXX_STD = CXX11` defined, which should be enough. Also, while your R is 64 bit, compiler is not using the `-m64` flag. Was your R installation customized in any way? Could you please post the output of the following commands:
`gcc -v`
```grep CXX `R RHOME`/etc/Makeconf | grep -v '^#'```
`diff src/Makevars.in src/Makevars`

**Comment by ocschwar** [comment]
omri@SERVER2:~$ cd xgboost/R-package/
omri@SERVER2:~/xgboost/R-package$ gcc -v 
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.4' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4)

**Comment by ocschwar** [comment]
omri@SERVER2:~/xgboost/R-package$  grep CXX `R RHOME`/etc/Makeconf | grep -v '^#'
CXX = g++
CXXCPP = $(CXX) -E
CXXFLAGS = -g -O2 -fdebug-prefix-map=/build/r-base-6WVosl/r-base-3.3.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g $(LTO)
CXXPICFLAGS = -fpic
CXX1X = g++
CXX1XFLAGS = -g -O2 -fdebug-prefix-map=/build/r-base-6WVosl/r-base-3.3.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g
CXX1XPICFLAGS = -fpic
CXX1XSTD =  
OBJCXX = 
SHLIB_CXXFLAGS = 
SHLIB_CXXLD = $(CXX)
SHLIB_CXXLDFLAGS = -shared
SHLIB_CXX1XLD = $(CXX1X) $(CXX1XSTD)
SHLIB_CXX1XLDFLAGS = -shared
SHLIB_OPENMP_CXXFLAGS = -fopenmp
R_XTRA_CXXFLAGS = 
ALL_CXXFLAGS = $(R_XTRA_CXXFLAGS) $(PKG_CXXFLAGS) $(CXXPICFLAGS) $(SHLIB_CXXFLAGS) $(CXXFLAGS)
ALL_OBJCXXFLAGS = $(PKG_OBJCXXFLAGS) $(CXXPICFLAGS) $(SHLIB_CXXFLAGS) $(OBJCXXFLAGS)
	$(CXX) $(ALL_CPPFLAGS) $(ALL_CXXFLAGS) -c $< -o $@
	$(CXX) $(ALL_CPPFLAGS) $(ALL_CXXFLAGS) -c $< -o $@
	@$(CXX) -M $(ALL_CPPFLAGS) $< > $@
	@$(CXX) -M $(ALL_CPPFLAGS) $< > $@
	$(OBJCXX) $(ALL_CPPFLAGS) $(ALL_OBJCXXFLAGS) -c $< -o $@
	$(OBJCXX) $(ALL_CPPFLAGS) $(ALL_OBJCXXFLAGS) -c $< -o $@

**Comment by ocschwar** [comment]
omri@SERVER2:~/xgboost/R-package$  diff src/Makevars.in src/Makevars
14,15c14,15
< PKG_CXXFLAGS= @OPENMP_CXXFLAGS@ $(SHLIB_PTHREAD_FLAGS)
< PKG_LIBS = @OPENMP_CXXFLAGS@ $(SHLIB_PTHREAD_FLAGS)
---
> PKG_CXXFLAGS= $(SHLIB_OPENMP_CFLAGS) $(SHLIB_PTHREAD_FLAGS)
> PKG_LIBS = $(SHLIB_OPENMP_CFLAGS) $(SHLIB_PTHREAD_FLAGS)

**Comment by khotilov** [comment]
So, was your R installation modified in any way? I'm asking since your system Makeconf doesn't properly define CXX1XSTD, and that's why the `CXX_STD = CXX11` setting in xgboost has no effect. It might also be related to this: https://bugs.r-project.org/bugzilla3/show_bug.cgi?id=17189

E.g., for comparison, here is the relevant piece of /usr/lib64/R/etc/Makeconf from the same R version 3.3.2 on a RHEL 6.8 server:
```
CXX = g++ -m64
CXXCPP = $(CXX) -E
CXXFLAGS = -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic $(LTO)
CXXPICFLAGS = -fpic
CXX1X = g++ -m64
CXX1XFLAGS = -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic
CXX1XPICFLAGS = -fpic
CXX1XSTD =  -std=c++0x
OBJCXX =
SHLIB_CXXFLAGS =
SHLIB_CXXLD = $(CXX)
SHLIB_CXXLDFLAGS = -shared
SHLIB_CXX1XLD = $(CXX1X) $(CXX1XSTD)
SHLIB_CXX1XLDFLAGS = -shared
SHLIB_OPENMP_CXXFLAGS = -fopenmp
R_XTRA_CXXFLAGS =
```

**Comment by ocschwar** [comment]
Oh! The one thing I did was pin the r-base packages to Ubuntu 17.

**Comment by ocschwar** [comment]
THis is all I did to make the change, which makes it a mix of 16.04 and 17.04

`more /etc/apt/preferences.d/pin 
Package: r-base-core
Pin: release n=xenial
Pin-Priority: -10

Package: r-base-core
Pin: release n=zesty
Pin-Priority: 900
`

**Comment by khotilov** [comment]
It looks like 17.04 uses GCC 6.3 which has the default language standard of -std=c++14, so it doesn't need an extra -std=c++11 flag to compile C++11 code. That's probably why your R package was built with no such special flag defined.

**Comment by ocschwar** [comment]
Oh!. Wow, thank you! It would have taken me ages to figure this out on my own.
