### ISSUE TITLE
[jvm-packages] java/scala in the package name is a bad idea

### ISSUE THREAD

**Issue by superbobry** [dmlc/xgboost#2519]
Using java/scala in the package name has a subtle side-effect, it makes it is impossible to import anything from Java/Scala standard library if you're one level up, e.g. 

```scala
package ml.dmlc.xgboost4j

import scala.collections.JavaConverters._
// ^^^ symbol not found
```

since `ml.dmlc.xgboost4j.scala` package does not indeed have `collections` sub-package.

N. B. Spark solves this issue by defaulting to Scala and putting Java classes in `spark.api.java`.

**Comment by CodingCat** [comment]
Does __root__ work?

**Comment by superbobry** [comment]
Oh, magic, it does. Sorry for opening an issue on a documented Scala feature.
