### ISSUE TITLE
GHistIndexMatrix row_ptr type

### ISSUE THREAD

**Issue by RAMitchell** [dmlc/xgboost#2520]
@hcho3 I notice that the type of the row_ptr in this struct is an unsigned. Should this be a 64-bit type? We are looking at potentially using this struct for matrices with more than 2^32 elements and I believe it would fail in this case.

Can you please look at this this in your next PR?

**Comment by hcho3** [comment]
@RAMitchell I will be reviewing the pull request by @pseudotensor and suggest additional changes to accommodate 64-bit indices. Thanks!
