### ISSUE TITLE
XGBClassifier with no booster parameter?

### ISSUE THREAD

**Issue by clockwiser** [dmlc/xgboost#2523]
xgboost version: 0.6a2
os : ubuntu 16.04 lts

Error happens when use XGBClassifier with booster parameter.
TypeError: __init__() got an unexpected keyword argument 'booster'

It is inconsistent to the documents.
http://xgboost.readthedocs.io/en/latest/python/python_api.html

**Comment by zhedongzheng** [comment]
The same problem on mac os (installed by pip)
