### ISSUE TITLE
Leakage of parameters across models

### ISSUE THREAD

**Issue by pseudotensor** [dmlc/xgboost#2525]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System: Ubuntu 16.04

Package used (python/R/jvm/C++): python

`xgboost` version used: c85bf9859e32694e753603eb2e55dd79c36ad02d

python 3.6.1 with pyenv.

## Steps to reproduce

Below "hang" means only uses 1 thread even if didn't specify nthread so should have used all cores available.  Leaks nthread from prior model.

Run attached script as python -m nose testhang.py .  You'll need about 128GB virtual memory and 64GB real memory to run this.

[testhang.zip](https://github.com/dmlc/xgboost/files/1153772/testhang.zip)

Hangs in larger data test (takes a little bit to generate data, but once "normal updater" is printed, it should use multi-core system almost right away and be done in seconds. Instead, it hangs.  If I attach gdb to it, I get the attached back trace, so it is is hanging just inside an OpenMP call.
[gdb.txt](https://github.com/dmlc/xgboost/files/1153764/gdb.txt) .

If one specifies nthread in the large job, it runs fine with multiple processes, otherwise it runs with nthread 1 that was pulled from a prior model.  nthread should default to all procs if not specified, but instead somehow internal state is shared across models.

## What have you tried?

1. Looking through code and seeing why would hang.  Not sure.
2. Debugging in nsight (script originated as gpu related, but no gpu stuff used in script now).
3. I've tried to isolate it with as little code as possible.  It only seems to hang if there are multiple instances of .train() in the same overall python call. 
4. Can change all "exact" to "hist" the hang doesn't seem to be there.
5. Originally all the small tests (i.e. all but test_large) were gpu_exact or gpu_hist, and the test_large exact would still hang (i.e. only use 1 core)

I'm looking for suggestions as to how else to isolate this and for any confirmation that others see it.

**Comment by khotilov** [comment]
Setting `nthread` parameter changes the global OpenMP setting when [configuring the Learner](https://github.com/dmlc/xgboost/blob/48f3003302c323475af957b164ac24a564babb6c/src/learner.cc#L194). It's not tied to a model.

I've run your script with a twice smaller large test (32G memory) and it has finished OK in 300sec. I've seen previously on linux a few times that running was coming to almost grinding halt when swapping kicked in.

**Comment by pseudotensor** [comment]
This is run on 264GB system, not swapping.  Train should complete in a few seconds with multiple threads.

nthread is passed along with param inside train().  A follow-up train has its own param, so why should it use any param values from before?  Each train should only use the given param and otherwise use the same defaults every time, otherwise one has uncontrolled behavior unless one passes every single parameter every single train, which is silly.

**Comment by khotilov** [comment]
I tried to run your script earlier today on a linux machine with 64G, and it didn't hang.  It took about 12min total for single thread and slightly more than three times faster for 8 threads.

Consider the current "nthread" parameters not as a model parameter, but as a switch to change the global openmp state (having a separate method to change it would have been a cleaner approach for that though). I agree that moving from the global state and explicitly controlling num_threads  would be a better option, but I wouldn't call the current behavior as uncontrolled, and I doubt that the hangs that you saw have any relationship to this.

**Comment by pseudotensor** [comment]
Sorry, there is some confusion.  I said "Below "hang" means only uses 1 thread even if didn't specify nthread so should have used all cores available. Leaks nthread from prior model."  So by hang I am just talking about that train using the old nthread.

Yes, it's poor design to have params include "nthread" yet it affects the global state.  Are there any other things like that?  I presume alot, because I've had the need to put xgb.train in python subprocesses in order for them not to conflict or cause subsequent calls to literally hang forever (different use of hang here).
