### ISSUE TITLE
Questions regarding XGBoost Model

### ISSUE THREAD

**Issue by axisbold** [dmlc/xgboost#2535]
Hi all,

I have some questions regarding the XGBoost model and functionality:
- I read the XGBoost documentation and understand how a split is done, but I'm still wondering how does the algorithm decide which feature will be used at a particular step?
- What is the initial score of the leafs of the first tree? Is it just a random assignment?
- Does anyone have a document which describes the whole XGBoost algorithm in pseudocode?

Thanks for your replies :)

Cheers

**Comment by hcho3** [comment]
* XGBoost simply computes possible gains for all (feature_id, threshold) combinations and chooses the best one.
* Leaf weights are determined completely by the loss values of left and right child instance sets, so they are not random assignments.
* I have written a self-contained summary of gradient boosting in my [quals paper](https://github.com/dmlc/xgboost/files/1167976/quals.pdf). See page 5 for the full pseudocode. Please be mindful of that pseudocode hides a lot of gory implementation details.

Hope it helps!

**Comment by axisbold** [comment]
Thanks, the paper helps a lot! :)
