### ISSUE TITLE
[jvm-packages]xgboost4j-spark has different result with xgboost

### ISSUE THREAD

**Issue by wangzhilong** [dmlc/xgboost#2544]
i train a model，respectively use xgboost4j-spark and xgboost。
same train_data, train_params。
but get different auc, the auc useing xgboost4j-spark model is lower than local xgboost.

**Comment by CodingCat** [comment]
It is as expected, distributed training will make candidate proposal less accurate

**Comment by wangzhilong** [comment]
I read code: xgboost4j-spark calls xgboost4j , and xgboost4j calls c++ code with JNI.
i don't understand why distributed training will make candidate proposal less accurate.
@CodingCat

**Comment by CodingCat** [comment]
http://www.kdd.org/kdd2016/papers/files/rfp0697-chenAemb.pdf section 3.2

please add [jvm-packages] in your title when asking about jvm stuffs (which has been EXPLICITLY stated in the issue template)

**Comment by CodingCat** [comment]
for save/load model issues, it might be caused by 0/1-based issues (https://github.com/dmlc/xgboost/tree/master/jvm-packages)

**Comment by GuohuaZhuang** [comment]
Why let this issue to close? I have the same problem. I dump tree model and find it is caused by 0/1-based as its feature index is wrong. Then how to solve it when I train model use xgboost-spark, but use the trained model to predict in local?

**Comment by wangzhilong** [comment]
in local , you also need to convert  feature index 1-based to 0-based.

**Comment by GuohuaZhuang** [comment]
thanks, @wangzhilong . Maybe convert feature index is the only method now. 
I want to change MLUtils.loadLibSVMFile source code and recompile the loadLibSVMFile part to make it support 0-based. Do you have any better advise?

**Comment by wangzhilong** [comment]
that's what I thought before, 
you'd better don't do that,  because you will have to change many places. 
and online use model, the index usually start form 0.
