### ISSUE TITLE
Continue training model more than once (R)

### ISSUE THREAD

**Issue by snawara** [dmlc/xgboost#2545]
Hi all,

I was trying to train a model, train again with some other data, and then train again with further new data. I found my error could be reproduced by slightly modifying the original code for updating a model:
```
library(xgboost)
library(data.table)
library(mlbench)

# predicting the outcome of a diabetes test
data(PimaIndiansDiabetes2)
dt <- PimaIndiansDiabetes2
str(dt)
setDT(dt)
fnames <- colnames(dt)[-9]

set.seed(1)
tr <- sample.int(nrow(dt), 0.7*nrow(dt))
dtrain <- xgb.DMatrix(as.matrix(dt[tr, -9, with=F]), label = as.numeric(dt$diabetes[tr])-1)
dtest <- xgb.DMatrix(as.matrix(dt[-tr, -9, with=F]), label = as.numeric(dt$diabetes[-tr])-1)
wl <- list(train = dtrain, test = dtest)

param <- list(max_depth = 2, eta = 0.05, nthread = 2, subsample = 0.5, min_child_weight = 5, 
              objective = "binary:logistic", eval_metric = "auc",
              base_score = mean(getinfo(dtrain,"label")))

bst <- xgb.train(param, dtrain, 50, wl)
# some significant overfitting is happening...

# Refresh the model within the same training data (without pruning)
rparam <- modifyList(param, list(process_type='update', updater='refresh', refresh_leaf=TRUE))
rbst <- xgb.train(rparam, dtrain, nrounds = bst$niter, watchlist = wl, xgb_model = bst)
rbst2 <- xgb.train(rparam, dtrain, nrounds = rbst$niter, watchlist = wl, xgb_model = rbst)

```
https://github.com/dmlc/xgboost/pull/1670

Here is the error at the last line, you can also see that rbst$niter is 50, not zero (the xgb.attr method is used in xgb.train to check for this):
```
> rbst2 <- xgb.train(rparam, dtrain, nrounds = rbst$niter, watchlist = wl, xgb_model = rbst)
Error in xgb.train(rparam, dtrain, nrounds = rbst$niter, watchlist = wl,  : 
  nrounds cannot be larger than 0 (nrounds of xgb_model)
> rbst$niter
[1] 50
> as.numeric(xgb.attr(rbst, "niter")) + 1
[1] 50
```
Here is my sessionInfo:
```

> sessionInfo()
R version 3.4.0 Patched (2017-05-14 r72674)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] mlbench_2.1-1     data.table_1.10.4 xgboost_0.6-4    

loaded via a namespace (and not attached):
[1] compiler_3.4.0  magrittr_1.5    Matrix_1.2-10   tools_3.4.0    
[5] stringi_1.1.5   grid_3.4.0      lattice_0.20-35
```

To be honest I am not sure what the update process is really doing at this point, so perhaps I misunderstand something. Is this a bug, or expected behavior?

**Comment by khotilov** [comment]
Thanks for reporting. That seems to be a bug: for some reason, the "niter" attribute information gets lost during the second update. I'll look into it later.

**Comment by snawara** [comment]
Hi khotilov,

Thanks for letting me know. It looks like this process is stripping all attributes for the second round (the resulting bst only has handle and raw):

```
handle <- xgb.Booster.handle(params, append(watchlist, dtrain), xgb_model)
bst <- xgb.handleToBooster(handle)
```
I was actually thinking perhaps this had something to do with JIT compilation getting activated by default:

>    * The JIT ('Just In Time') byte-code compiler is now enabled by
>      default at its level 3. This means functions will be compiled on
>      first or second use and top-level loops will be compiled and then
>      run.  (Thanks to Tomas Kalibera for extensive work to make this
>      possible.)  

https://stat.ethz.ch/pipermail/r-announce/2017/000612.html, but running `compiler::enableJIT(0)` at the top of the script did not fix the problem. Maybe that helps...

**Comment by frbl** [comment]
Hi @khotilov, thanks for looking into this! Are you sure this is fixed? I'm running into the exact same issue. Here is an M(N)WE:

``` R
set.seed(12345)
library('data.table')
library('xgboost')

## Create simulation function
give_me_data <- function(nobs, delta = 0.05) {
  X_mat <- data.table(A = rnorm(nobs, 0, 1), B = rnorm(nobs, 0, 1))
  probs <- pmax(as.numeric(X_mat$A > 0) - 2*delta, 0) + delta
  X_mat <- as.matrix(X_mat)
  Y_vals <- rbinom(nobs, 1, probs)
  return(list(X_mat = X_mat, Y_vals = Y_vals))
}

nobs <- 20
niter <- 100
test_nobs <- 200

## Create a training set
data <- give_me_data(nobs)

## Create a test set
test_data <- give_me_data(test_nobs)

params <- list(objective = 'binary:logistic', nthread = 1)
dtrain <- xgb.DMatrix(data = data$X_mat, label = data$Y_vals)

previous_model <- xgb.train(
  data       = dtrain,
  params     = params,
  nrounds    = 200,
  xgb_model  = NULL
)

## Calculate result
result <- predict(previous_model, newdata = test_data$X_mat, type='response')

## Still works here, predictions look fine
print(result)

params <- modifyList(params, list(process_type = 'update', updater = 'refresh', refresh_leaf = TRUE))

## Update niter times
for (i in 1:niter) {
  data <- give_me_data(nobs)

  dtrain <- xgb.DMatrix(data = data$X_mat, label = data$Y_vals)
  previous_model <- xgb.train(
    data       = dtrain,
    params     = params,
    nrounds    = 200,
    xgb_model  = previous_model,
  )

  result <- predict(previous_model, newdata = test_data$X_mat, type='response')
  print(result)
  print(i)
}

## It works for the first iteration, then I get
## Error in xgb.train(data = dtrain, params = params, nrounds = 10, xgb_model = previous_model,: nrounds cannot be larger than 0 (nrounds of xgb_model)
```
[gist](https://gist.github.com/frbl/5acb8570d01ffccad3b780972f701fd9#file-xgboost_failing_update-r)

And my session info:
```
> sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-apple-darwin17.0.0 (64-bit)
Running under: macOS High Sierra 10.13

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vec
ib.framework/Versions/A/libBLAS.dylib
LAPACK: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/v
cLib.framework/Versions/A/libLAPACK.dylib

locale:
[1] en_US.utf-8/en_US.utf-8/en_US.utf-8/C/en_US.utf-8/en_US.utf-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] xgboost_0.6.4.6   data.table_1.10.4 nvimcom_0.9-34

loaded via a namespace (and not attached):
[1] compiler_3.4.2  magrittr_1.5    Matrix_1.2-11   tools_3.4.2
[5] stringi_1.1.5   grid_3.4.2      lattice_0.20-35
```
As you can see, I'm running the `drat` version (`0.6.4.6`). 

Any ideas?

Best,
Frank

**Comment by khotilov** [comment]
@frbl Your drat package was from https://github.com/dmlc/drat/tree/gh-pages/bin/macosx/el-capitan/contrib/3.4 I guess, which was build on Jun 30th, while the fix was merged on Aug 9th. 

The degeneration of gblinear seems to happen after that tiny training sample batch hits a situation of perfect separation (just try fitting a usual glm for each data). I am not exactly sure why the intercept blows up in this case when using the coefficients of a previous model as initial coefficients for a new one, but some regularization e.g. lambda=0.2 would help to keep things under control. Also: process_type, updater, refresh_leaf have no effect for gblinear.

And perhaps you are aware of that, but with 200 rounds at high default learning rates,  you are not doing online learning with batches of 20 cases, but are badly overfitting each batch.

**Comment by frbl** [comment]
> @frbl Your drat package was from https://github.com/dmlc/drat/tree/gh-pages/bin/macosx/el-capitan/contrib/3.4 I guess, which was build on Jun 30th, while the fix was merged on Aug 9th.
My bad, I was not aware of the drat system and read on the webpage that it updated weekly. I'll try running from master in that case.

> The degeneration of gblinear seems to happen after that tiny training sample batch hits a situation of perfect separation (just try fitting a usual glm for each data). I am not exactly sure why the intercept blows up in this case when using the coefficients of a previous model as initial coefficients for a new one, but some regularization e.g. lambda=0.2 would help to keep things under control. Also: process_type, updater, refresh_leaf have no effect for gblinear.
Ok, thanks, I'll look into that!

> And perhaps you are aware of that, but with 200 rounds at high default learning rates, you are not doing online learning with batches of 20 cases, but are badly overfitting each batch.
Yeah, well the 200 was just a random number in this case. It is still online training on the 20 observations, but indeed highly overfitting, right?
