### ISSUE TITLE
Own Data loading Error in Regression in R?

### ISSUE THREAD

**Issue by Gautamshahi** [dmlc/xgboost#2552]
Hi,

I am trying to load my own data for regression. I divided my data using Mapfeat.py and mkfold.py and kept that data in my local working directory of RTSUDIO (C:\Users\Gautam\Documents\R\win-library\3.4\xgboost\data) but when i am executing the command in RStudio its giving error.

![image](https://user-images.githubusercontent.com/3966230/28638552-d0a28dc8-7262-11e7-91e1-bd7214c13c77.png)
![image](https://user-images.githubusercontent.com/3966230/28638571-e09672d0-7262-11e7-9028-5bf0d060c5c4.png)

**Comment by khotilov** [comment]
I would suggest learning some basics of R first, and learning to manipulate your data and to be aware of data formats. Here it is not a proper place for this.
