### ISSUE TITLE
[jvm-packages] Publishing JARs

### ISSUE THREAD

**Issue by superbobry** [dmlc/xgboost#2553]
At the moment XGBoost does not publish any artifacts to Maven Central/jCenter, and therefore has no release process for the JVM bindings. A couple of month ago I've developed [a pipeline](https://github.com/criteo-forks/xgboost-jars) for assembling xgboost4j and xgboost4j-spark with binaries for OS X, Linux (CentOS6+) and Windows. I think we can build on that to make the JVM bindings officially *releasable*.

Possible workflow: cross-compilation is a pain, therefore I suggest to 
* create a separate repo solely for doing pre-release builds (triggered on tag);
* configure three separate builds -- one per platform on Travis and Appveyor; 
* configure automatic deployment of the artifacts to some temporary storage (could be GiHub releases or S3 or any of the [supported](https://docs.travis-ci.com/user/deployment) deployment platforms;
* do a bash script to be run locally, which would download&merge per-platform artifacts for the latest tag and deploy the resulting JARs to Maven Central/jCenter.

Open questions:
* Is it safe to assume x64 or we need two sets of binaries?
* What set of features to target? 
   * OpenMP (yes/no)
   * HDFS/Azure/S3 (yes/no)
   * GPU plugin (yes/no)
   * LZ4 plugin (yes/no)
* Which Scala version? or first do #2358 and do cross-version releases.
* Maven Central vs jCenter? I personally prefer jCenter because it's easier to manage.

What do you think?

**Comment by CodingCat** [comment]
where is our last discussion (I cannot find it)? I asked whether we need to leak credentials to repo to publish automatically

**Comment by superbobry** [comment]
I've personally only used jCenter, I think you can do proper ACL there with [teams](https://bintray.com/docs/usermanual/interacting/interacting_bintrayorganizations.html#_teams_and_permissions). Each member of the team with proper permission would be able to do releases.

As for GitHub releases, we can create a bot account and generate [personal access tokens](https://github.com/settings/tokens) for Appveyor and Travis, see e.g. [this](https://docs.travis-ci.com/user/deployment/releases/).

**Comment by superbobry** [comment]
Should I close this as a duplicate of #1807?
