### ISSUE TITLE
Data corruption when creating a a DMatrix with label being a non-contiguous ndarray

### ISSUE THREAD

**Issue by colinmorris** [dmlc/xgboost#2554]
## Environment info
Operating System: Ubuntu 16.04

Compiler: gcc 5.4.0

Package used (python/R/jvm/C++): python

`xgboost` version used:

commit hash: 00eda28b3c6270f2434b09f4ea46fe9ee6c16c53
`xgboost.__version__`: 0.6
python version: 2.7.12

## Steps to reproduce

```python
import numpy as np
import xgboost as xgb

np.random.seed(1337)
n = 3
yy = np.random.randint(0, 2, (n, 2)).astype(np.float32)
y = yy.T[0]
# y.flags.C_CONTIGUOUS and y.flags.F_CONTIGUOUS are both False
# Either of the below two calls will make y contiguous, and fix the error.
#y = y.copy()
#y = np.ascontiguousarray(y)
x = np.random.rand(n, 5)
print "{} <- array passed in as label".format(y)
dm = xgb.DMatrix(x, label=y)
labels = dm.get_label()
print "{} <- result of calling get_label() on DMatrix".format(labels)
```

output:

    [ 1.  0.  1.] <- array passed in as label
    [ 1.  1.  0.] <- result of calling get_label() on DMatrix

This is the simplest repro I could come up with. The actual use case where I found this involved passing in an array of labels that was the result of indexing a `np.recarray` by a field name (which results in a non-contiguous array). The error message during training that led me down this path was:

    xgboost.core.XGBoostError: [02:16:43] src/objective/regression_obj.cc:108: label must be in [0,1] for logistic regression

(The labels being used by the DMatrix indeed included some crazy values outside that range, which I assume leaked in from other columns of the recarray I had indexed)

## What have you tried?

As noted in the code above, an easy workaround is just to make the label array contiguous before passing it in, e.g. by calling `np.ascontiguousarray`. But if you don't know to do this, it can really trip you up. I had a heck of a time debugging this - also, I was lucky that the corruption resulted in labels outside [0, 1]. If that weren't the case, I might not even have noticed.

**Comment by khotilov** [comment]
Yeah, as a minimum, it should throw an error for non-contiguous input...
