### ISSUE TITLE
Monotonic behaviour

### ISSUE THREAD

**Issue by druhinpal** [dmlc/xgboost#2555]
I have been using xgboost for my modelling.
I have multiple features as independent variables. There is one feature x with which the dependent variable(y) should monotonically increase with x. I have tried using monotone_constraints in my params where I have set x as +1 and others as 0 . But still after scoring I did not see the monotonic trend as was expected. Can someone help me with this since I am blocked on this?

**Comment by ccmien** [comment]
what kind of tree_method did you use?

**Comment by druhinpal** [comment]
default

**Comment by tqchen** [comment]
monotonicity only ganrantee that prediction is monotone with one feature given that all other features are unchanged.

**Comment by druhinpal** [comment]
I get it.
But is there any way to enforce this factor that irrespective of the other features, y should monotonically increase with one of the features?
