### ISSUE TITLE
dump feature map in Python

### ISSUE THREAD

**Issue by yzliao** [dmlc/xgboost#256]
In the Python documentation, the feature map can be dumped as

```Python
# dump model with feature map
bst.dump_model('dump.raw.txt','featmap.txt')
```

I tried this commend and got following error:
```shell
 -- Finished training
 -- Testing error: 1.9717.
can not open file "featmap.txt"
```

I looked the code (xgboost.py, xgboost_wrapper.cpp) and found that the functions are defined as following:

```Python
def dump_model(self, fo, fmap='', with_stats=False):
        """
        Dump model into a text file.

        Parameters
        ----------
        fo : string
            Output file name.
        fmap : string, optional
            Name of the file containing feature map names.
        with_stats : bool (optional)
            Controls whether the split statistics are output.
        """
        if isinstance(fo, string_types):
            fo = open(fo, 'w')
            need_close = True
        else:
            need_close = False
        ret = self.get_dump(fmap, with_stats)
        for i in range(len(ret)):
            fo.write('booster[{}]:\n'.format(i))
            fo.write(ret[i])
        if need_close:
            fo.close()

    def get_dump(self, fmap='', with_stats=False):
        """
        Returns the dump the model as a list of strings.
        """
        length = ctypes.c_ulong()
        sarr = xglib.XGBoosterDumpModel(self.handle, c_str(fmap),
                                        int(with_stats), ctypes.byref(length))
        res = []
        for i in range(length.value):
            res.append(str(sarr[i]))
        return res
```

```C++
const char** XGBoosterDumpModel(void *handle, const char *fmap, int with_stats, bst_ulong *len){
    utils::FeatMap featmap;
    if (strlen(fmap) != 0) {
      featmap.LoadText(fmap);
    }
    return static_cast<Booster*>(handle)->GetModelDump(featmap, with_stats != 0, len);
  }
```

For me, it looks like 
1. `fmap` is not only a file name and it serves for other purposes.
2. `featMap.LoadText(fmap)` seems weird to me since I expect the function to write feature map to `fmap`, not load from it.

**Comment by tqchen** [comment]
feature map was provided as a hint for what type the feature is. Such hint was not included during xgboost learning, so that was why a fmap needs to be passed in. 

However, I agree that featmap was not very well documented, it is only mentioned here https://github.com/dmlc/xgboost/tree/master/demo/binary_classification

**Comment by tqchen** [comment]
Feature map was only for generating intuitive tree outputs, so it can be optional(then the name of feature will be displayed as fid)

**Comment by yzliao** [comment]
Thank you! So my understanding is that `featmap.txt` is an input file, not the output file. If it is, then I see may confusion. 

In addition, should we add a new option to turn off printing for `get_fscore()`?

**Comment by tqchen** [comment]
sounds like a good idea. I guess get_fscore should not do the printing at all. We can also add another function importance, which is more consistent with existing functions in R and other toolkits and redirect get_fscore to it

**Comment by yzliao** [comment]
Great. Then I will firstly create a PR to add an option to disable print. I will see how R functions work on `get_fscore`

**Comment by tqchen** [comment]
what i mean is add a function with name ```importance```

**Comment by yzliao** [comment]
Just want to make sure that I understand it correctly. Do you mean that adding a Python function with the same functionality of the R function `xgb.importance`

**Comment by tqchen** [comment]
yes, and redirect get_fscore to importance

**Comment by tqchen** [comment]
the importance module in R contains some visualization module by @pommedeterresautee which might be hard in python. We can start with a solution that works in python first, then adds more interesting things

**Comment by yzliao** [comment]
Okay, I will look at the R code at first. Regarding `get_fscore` right now, should I add the control variable for printing?

**Comment by tqchen** [comment]
i think we can simply remove the printing
