### ISSUE TITLE
[jvm-packages] Harness RabitTracker logs

### ISSUE THREAD

**Issue by xydrolase** [dmlc/xgboost#2560]
Currently both the Java and Scala implementation of RabitTracker logs messages sent by workers via the "print" command to `stderr`. 

For distributed training sessions on Spark/YARN, these messages, which typically are per-tree evaluation metrics (AUC, training error etc.), end up in the YARN log files. These messages currently cannot be harnessed by the Spark driver, making it difficult to: 
 - redirect the training log to a designated directory for reproducibility considerations; and
 - visualize the training metrics for diagnostics.

It would be helpful for `IRabitTracker` interface to expose a method to accept either a `java.util.List` or an `OutputStreamWriter` to capture such messages. And the user of XGBoost can provide the container or the writer object via `trainWithDataFrame` or `trainWithRDD` method. 

@CodingCat What's your take on this feature request, and do you have any preference between `List` and `OutputStreamWriter`? If you like the idea, I will submit a PR to implement it. Thanks.

**Comment by superbobry** [comment]
Can we redirect stderr to commons-logging?

**Comment by CodingCat** [comment]
can we simply have a separate logging file for xgboost4j (ensuring that the file is generated in the application's working directory)?

@superbobry not sure if commons-logging will work since it should pick up the Spark's log4j instance by default

**Comment by xydrolase** [comment]
@CodingCat You mean the working directory from where the user submits the Spark program? What would be a better way to configure the log file name etc?

**Comment by CodingCat** [comment]
@xydrolase I mean the working directory of the driver (client/cluster mode) and executors (do we print anything in executor?) 

we can fix the log file name since it is easier for monitoring...

**Comment by xydrolase** [comment]
@CodingCat The executor has its own log too. And one of the executor/worker sends the log to the Rabit tracker, so that it shows up on the driver's log. 

So for the driver level log file name, would it be hard-coded in xgboost4j?

**Comment by CodingCat** [comment]
I am thinking about that what if the user would like to interactively watch metrics, instead of a long-term monitoring, maybe we should make it as configurable to the user.

Regarding file name, hardcoded name is OK in my opinion,
