### ISSUE TITLE
XGBoost tends to produce better scores when single-threaded

### ISSUE THREAD

**Issue by facadev** [dmlc/xgboost#2566]
Is it an expected consequence of parallelization? If the best result is desired, should I use nthread=1 if I don't care performace that much?

**Comment by pommedeterresautee** [comment]
This is known and it is related to the fact that in multi thread the workers are not fully synchronized for performance matters. In general, when the model is highly complex (lots of rounds) it doesn't matter a lot. When the model is simple the effect is obvious.

**Comment by khotilov** [comment]
@pommedeterresautee perhaps, you were assuming 'distributed' not 'multithreaded' in your response?

@facadev if you are using exact gbtree algorithms, multithreaded running should not generally change the scoring performance (disregarding the randomness from sampling).

**Comment by facadev** [comment]
To clarify a little bit, with seed set, I run the same code on a single-core machine and a multi-core one, the scores on the single-core are better 80% of the times (multiple models are trained). And the train and test datasets are both fixed, so there should be no randomness of sampling in this scenario.

I only tweak max_depth and eta, with col_sampling and other params untouched.

**Comment by khotilov** [comment]
Ah, so it was on **different machines**... Then there might be some differences b/c the systems are different, not b/c of different thread number.

On the same multi-core machine, the results should be identical when running with the same random seed but different `nthread` settings. Column sampling is the source of randomness in your case.

P.S.: Please note that the issue template is there for a reason. Please use it next time to avoid guessing games.

**Comment by facadev** [comment]
A bit confused with your latest reply...

Same seed, same code, all parameters kept default (except eta and max_depth), run on two machines that differ only in number of cores. I see no randomness in the context. Could you please elaborate more on that?

PS. Regarding the template, definitely I will next time. :)

**Comment by khotilov** [comment]
@facadev What are your machines, any details? 

gbtree booster is default, and you didn't mention changing it. Regression trees are used in gradient boosting.

**Comment by facadev** [comment]
@khotilov Yes for regression I use reg:linear + gblinear combination. So the randomness comes from multi-threaded parameter updates in gradient boosting, is that right?

**Comment by khotilov** [comment]
Huh... there goes your "other params untouched".

gblinear uses lock-free parallelization - see my comment at #2367 . In some cases it might slightly help with predicitve performance, but sometimes it might make things slightly worse - all depends on your data.

Also, I have a version of gblinear in the works that provides an option for thread-consistent stagewise-like algorithm, I just need to clean it up.

**Comment by facadev** [comment]
Fingers crossed.

**Comment by facadev** [comment]
@khotilov Thanks for the insight, and especially patience! :D
