### ISSUE TITLE
xgBoostModel.booster.saveModel("/modelPath") has no result

### ISSUE THREAD

**Issue by nedved1990** [dmlc/xgboost#2570]
Hi Guys:
I use distributed XGBoost on spark to train my model, but i occur some problem while I save my model.
I want to save a binary model which can be used for C++ version of xgboost, that I can use it for the online scoring.
At first, I try: 

**> xgBoostModel.saveModelAsHadoopFile("/result")**

But the model can't use for the C++ version of XGBoost.
Secondly, I try:

**>  xgBoostModel.booster.saveModel("file:///usr/local/app/xgboost/binary/result")**

But there is no result under this path.

So i want to ask for help. Is there any way for me to save a binary model Which can be loaded by C++ or Python?

**Comment by CodingCat** [comment]
please add [jvm-packages] in your title when you ask about jvm-package questions, which is clearly stated in the issue template

**Comment by CodingCat** [comment]
the output of saveModelAsHadoopFile can only be consumed by xgboost-4j spark package

**Comment by nedved1990** [comment]
Hi @CodingCat :
Sorry I forget to add  [jvm-packages] in my title. 
I already solve this problem by the other ways. I use FSDataOutputStream to save my model. Here is the code:
**```
val hadoopConf = sc.hadoopConfiguration
 val fileSystem = FileSystem.get(hadoopConf)
val path3 = new Path(modelSerializePath+"/xgboostBinaryModel")
 val outputSteam: FSDataOutputStream = fileSystem.create(path3,true)
xgBoostModel.booster.saveModel(outputSteam)
```**
Ask @CodingCat previous question, I pretty sure that file:///usr/local/app/xgboost/binary/result didn't generated. I want to know the reason why it can't generated model by using PATH?
