### ISSUE TITLE
Built and Installed, but can't import

### ISSUE THREAD

**Issue by dshefman1** [dmlc/xgboost#2575]
I have been working on this all day. I managed to build and install xgboost with exact codes at installation guide "Building on Windows" (http://xgboost.readthedocs.io/en/latest/build.html#). I installed xgboost using "python setup.py install" from the python-package folder. All seems to be well.
Conda list shows xgboost (0.6). I have attached the log file when I run "python setup.py install"
[xgboost_install_log.txt](https://github.com/dmlc/xgboost/files/1198945/xgboost_install_log.txt)

### However, when I try to run "import xgboost as xgb" in Spyder, I get the following error:

```
import xgboost as xgb
Traceback (most recent call last):

  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-2-745aa3a2d734>", line 1, in <module>
    import xgboost as xgb

  File "C:\Users\dsheffie\Desktop\Anaconda\Machine Learning A-Z\Part 10 - Model Selection & Boosting\Section 49 - XGBoost\xgboost.py", line 36
    from xgboost import
                        ^
SyntaxError: invalid syntax
```

### when I try to run "import xgboost as xgb" in jupyter notebook I get the following error:
---------------------------------------------------------------------------
```
OSError                                   Traceback (most recent call last)
<ipython-input-1-745aa3a2d734> in <module>()
----> 1 import xgboost as xgb

C:\ProgramData\Anaconda3\lib\site-packages\xgboost-0.6-py3.5.egg\xgboost\__init__.py in <module>()
      9 import os
     10 
---> 11 from .core import DMatrix, Booster
     12 from .training import train, cv
     13 from . import rabit                   # noqa

C:\ProgramData\Anaconda3\lib\site-packages\xgboost-0.6-py3.5.egg\xgboost\core.py in <module>()
    113 
    114 # load the XGBoost library globally
--> 115 _LIB = _load_lib()
    116 
    117 

C:\ProgramData\Anaconda3\lib\site-packages\xgboost-0.6-py3.5.egg\xgboost\core.py in _load_lib()
    107     if len(lib_path) == 0:
    108         return None
--> 109     lib = ctypes.cdll.LoadLibrary(lib_path[0])
    110     lib.XGBGetLastError.restype = ctypes.c_char_p
    111     return lib

C:\ProgramData\Anaconda3\lib\ctypes\__init__.py in LoadLibrary(self, name)
    423 
    424     def LoadLibrary(self, name):
--> 425         return self._dlltype(name)
    426 
    427 cdll = LibraryLoader(CDLL)

C:\ProgramData\Anaconda3\lib\ctypes\__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    345 
    346         if handle is None:
--> 347             self._handle = _dlopen(self._name, mode)
    348         else:
    349             self._handle = handle

OSError: [WinError 1114] A dynamic link library (DLL) initialization routine failed
```

## Environment info
Operating System: Windows 10
Compiler:  tdm64-gcc-5.1.0-2
Package used (python/R/jvm/C++): python 3.5.3
spyder version: 3.2.0
`xgboost` version used: 0.6

**Comment by hcho3** [comment]
Try appending `C:\path\to\xgboost\python-package` to the environment variable `PYTHONPATH`. See [this](https://stackoverflow.com/a/4855685) for instructions on editing environment variables.

**Comment by dshefman1** [comment]
As per your recommendation, I created an environment variable PYTHONPATH (it did not exist before) with the path C:\Users\dsheffie\xgboost\python-package. I tried in both local and system variables. I still get the same error.
![image](https://user-images.githubusercontent.com/25602097/28982925-4e077242-790c-11e7-8420-53d3741cc3aa.png)

**Comment by hcho3** [comment]
Can you try re-booting the system? The new environment variable may not have taken full effect.

**Comment by khotilov** [comment]
@dshefman1 Make sure that spyder uses the same python environment as the python that you ran "python setup.py install" with. From the log of that command, note the site-packages location of where the xgboost module was installed. Then run "import sys; sys.path" within spyder and check whether the module search paths include that site-packages directory where xgboost was installed to.

**Comment by dshefman1** [comment]
hcho3: Even after re-booting I still get the same error.

**Comment by dshefman1** [comment]
khotilov: 
From the log of "python setup.py install" I see that the location is...
'c:\programdata\anaconda3\lib\site-packages\xgboost-0.6-py3.5.egg'
When I run "import sys; sys.path" in spyder, the search paths include
'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\xgboost-0.6-py3.5.egg'. (see output below):
```
import sys; sys.path
Out[3]: 
['',
 'C:\\Users\\dsheffie\\xgboost\\python-package',
 'C:\\ProgramData\\Anaconda3\\python35.zip',
 'C:\\ProgramData\\Anaconda3\\DLLs',
 'C:\\ProgramData\\Anaconda3\\lib',
 'C:\\ProgramData\\Anaconda3',
 'C:\\ProgramData\\Anaconda3\\lib\\site-packages',
 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\Sphinx-1.6.2-py3.5.egg',
 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\xgboost-0.6-py3.5.egg',
 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\win32',
 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\dsheffie\\.ipython']
```

**Comment by khotilov** [comment]
Ok, that looks good.

In your error log I see
```
....\Part 10 - Model Selection & Boosting\Section 49 - XGBoost\xgboost.py", line 36
    from xgboost import
```
i.e., you have a file named xgboost.py which seems to attempt importing itself. Rename this file.

**Comment by dshefman1** [comment]
@khotilov 
Now when I run "import xgboost as xgb" in spyder, the error is similar to the error I get in jupyter notebook:

```
import xgboost as xgb
Traceback (most recent call last):

  File "<ipython-input-2-745aa3a2d734>", line 1, in <module>
    import xgboost as xgb

  File "C:\Users\dsheffie\xgboost\python-package\xgboost\__init__.py", line 11, in <module>
    from .core import DMatrix, Booster

  File "C:\Users\dsheffie\xgboost\python-package\xgboost\core.py", line 115, in <module>
    _LIB = _load_lib()

  File "C:\Users\dsheffie\xgboost\python-package\xgboost\core.py", line 109, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])

  File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 425, in LoadLibrary
    return self._dlltype(name)

  File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)

OSError: [WinError 1114] A dynamic link library (DLL) initialization routine failed
```

**Comment by khotilov** [comment]
Some TDM-GCC versions are known to have issues with anaconda python. I would suggest uninstalling it and switching to mingw64.

- Download mingw64 from https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/7.1.0/threads-posix/seh/ . E.g., I've just got the `x86_64-7.1.0-release-posix-seh-rt_v5-rev1.7z` archive file
- Extract contents of the archive using 7-Zip into somewhere (preferably, without spaces within directory names). E.g., I have it placed under `c:\tools\mingw64`
- Go to mingw64\bin directory and create a copy of `mingw32-make.exe` to `make.exe`
- Either add C:\tools\mingw64\bin (or whereveryouputit\bin) to the windows PATH environment variable (in front of all other locations). Or, if you don't plan on using it often and don't want to clutter your system PATH, run `export PATH=/c/tools/mingw64/bin:$PATH` within your Git bash terminal (or any other bash terminal for windows) right before building xgboost.
- Start Git bash and verify that you can run `gcc -v` and it shows the right version & location
- Might make sure that the following modules are installed:
```
conda install -y numpy scipy pandas matplotlib nose scikit-learn graphviz python-graphviz
```
- Go to the xgboost root directory and run:
```sh
make clean_all
make -j4
# which should produce the shared library:
ls -l lib/xgboost.dll
# install the python package
cd python-package
python setup.py install
cd ..
# run the tests
nosetests tests/python
```
Unless you want to always pick up the latest xgboost.dll that you build while working on xgboost development, you don't really need to set the PYTHONPATH variable.
