### ISSUE TITLE
[jvm-packages] How the predict each Decision tree of the XGBoost model? 

### ISSUE THREAD

**Issue by nedved1990** [dmlc/xgboost#2576]
Hi guys:
    I want to implement the xgboost+lr model. But it occurs some questions.
    Here is the basic concept of GBDT+LR : http://quinonero.net/Publications/predicting-clicks-facebook.pdf

    I want to ask how to generate the features from xgboostModel.
    The most important thing includes two part:
    1. Which API can read the each iteration(Decision tree) of XGBoost?
    2. Which API can read the leaves' value of the Decision Tree?

    Thank you !

**Comment by superbobry** [comment]
Hi @nedved1990, I believe you can find the answers in the [docs](http://xgboost.readthedocs.io/en/latest/jvm/java_intro.html).

**Comment by nedved1990** [comment]
Thanks for helping @superbobry !
But what i really want is the leaf numbers of each iteration of Decision Tree.

**Comment by superbobry** [comment]
I think the only way to do that is to take the model dump and parse it. See `dump_model` [here](http://xgboost.readthedocs.io/en/latest/python/python_intro.html) for a Python example.

**Comment by WinterW** [comment]
def toString(model: XGBoostModel ) = {
    val predString = model.booster.getModelDump()
    predString.mkString("|")
  }
 def dumpLeafNum(model:XGBoostModel, path:String) = {
    val modelDumpString = toString(model)
    val treeArray = modelDumpString.split('|')
    val reg = """\d+\:""".r
    val leafNumArray = treeArray.map{x =>
      reg.findAllIn(x).toArray.map(_.filter(_ != ':').toInt + 1).max
    }
    leafNumArray
  }
