### ISSUE TITLE
[jvm-packages] spark4j can not find libxgboost4j.so

### ISSUE THREAD

**Issue by universewill** [dmlc/xgboost#2577]
I run xgboost on spark on yarn. And encounter this error:

libgomp.so.1: 无法打开共享对象文件: 没有那个文件或目录
java.lang.NoClassDefFoundError: Could not initialize class ml.dmlc.xgboost4j.java.XGBoostJNI

---

I read the solution of #2497 , and adjust the setting of num-executors and executor-cores ,also the nWorkers parameter of xgboost model. But still cannot get this through.

For example, i submit as following, and set nWorkers=6 in the code:

/usr/local/spark-2.1.0-bin-hadoop2.7/bin/spark-submit \
  --class TestXgbSpark \
  --master yarn-cluster \
  --num-executors 6 \
  --driver-memory 10g \
  --executor-memory 10g \
  --executor-cores 1 \
  --jars ${jars} \
  --properties-file /home/dev/spark/app.conf \
  $base/target/xgboost-1.0-SNAPSHOT.jar

However, still get the same error.

**Comment by universewill** [comment]
@CodingCat   Could you give some help here? Many thanks!

**Comment by universewill** [comment]
I checked the libxgboost4j.so, and it seems ok:

root@tracker:~/xgboost/lib# ldd libxgboost4j.so
	linux-vdso.so.1 =>  (0x00007fffc2563000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fcb372d0000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fcb36fca000)
	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007fcb36dbb000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fcb36b9d000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fcb367d4000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fcb37a23000)

**Comment by superbobry** [comment]
Could you attach the whole error? It could be that you're facing libc/libc++ ABI mismatch.

**Comment by edumucelli** [comment]
@universewill Take a look at #2578 I have faced the same issue, and found out the solution.
