### ISSUE TITLE
XGBoostError: Invalid Input: 'hist'

### ISSUE THREAD

**Issue by xitman47** [dmlc/xgboost#2582]
Hello!

Please, help, I got this message: **"XGBoostError: Invalid Input: 'hist', valid values are: {'approx', 'auto', 'exact'}"**.

**Python, Amazon r4.2xlarge (Ubuntu), gcc 6, xgboost 0.6a2**.
I used command **"conda install -c conda-forge xgboost=0.6a2"** to install xgboost on Anaconda.

P.s. If I use {'approx', 'auto', 'exact'} everything works.

Thanks!

**Comment by hcho3** [comment]
It is likely that you installed an old version of XGBoost. We recommend that you compile XGBoost from the source.

**Comment by xitman47** [comment]
Thank you, I dunno how it could happen... I will try to not install via Anaconda, will report in a while.

**Comment by xitman47** [comment]
This repo helped me - [Xgboost on Amazon](https://gist.github.com/persiyanov/1d5499fd10802fa309d803359039a93b).
Still dunno how old version was installed... 

Thanks!

**Comment by sl2902** [comment]
I am running xgboost version 0.6 on Ubuntu 16.04.3on AWS, and I received the same error

Is there a difference between using pip install versus compiling from source? If I compile from source, how do I create the libxgboost.so file in the virtual environment where I've got xgboost currently running
