### ISSUE TITLE
Parameter for tree number

### ISSUE THREAD

**Issue by LeonCgh** [dmlc/xgboost#2586]
Hi, I read though the document again and google the question. It seems I cannot set up tree numbers unless I use scikit learn API. But I need do ranking learning and set up tree_method specifically. Unfortunately scikit API does not support that. Is there a parameter hiding from the document?

Thanks.

**Comment by pommedeterresautee** [comment]
You want tree_method (the message) or tree number (the title) ? You use scikit or something else ? Your question is not very clear.

**Comment by LeonCgh** [comment]
From this webpage
https://github.com/dmlc/xgboost/blob/master/doc/parameter.md  tree number
parameter is not provided. I know that from scikit api tree number can be
set but object parameter is not provided.

I want to do rank job and want to tune tree numbers as well.

So my question is if I used xgboost in this way:

import xgboost as xgb# read in datadtrain =
xgb.DMatrix('demo/data/agaricus.txt.train')dtest =
xgb.DMatrix('demo/data/agaricus.txt.test')# specify parameters via
mapparam = {'max_depth':2, 'eta':1, 'silent':1,
'objective':'binary:logistic' }num_round = 2bst = xgb.train(param,
dtrain, num_round)# make predictionpreds = bst.predict(dtest)

How Can I pass tree number into xgboost?

Thanks,

Leon.
