### ISSUE TITLE
[jvm-packages]some question about the "predictLeaves"

### ISSUE THREAD

**Issue by nedved1990** [dmlc/xgboost#2588]
Hi:
I meet a big problem when I use "predictLeaves" to predict the leaf node index.
The result of this API didn't return the real predict leaf index.
I already check by input the sample into the API. For example, when f28 = 1 , f28<0 yes to 1, no to 2, the result will return to node 1.
Is there a bug for this API?

**Comment by superbobry** [comment]
Could you provide the model you've used for prediction and the relevant code fragment?

**Comment by nedved1990** [comment]
Hi @superbobry . Here is my model and relevant code fragment.
Model:
        1:leaf=-0.129412,cover=3.25
        2:leaf=-0,cover=1
0:[f187<0.000299] yes=1,no=2,missing=1,gain=1.1633,cover=4.23643
        1:leaf=-0.119912,cover=3.23643
        2:leaf=-0,cover=1
0:[f187<0.000299] yes=1,no=2,missing=1,gain=1.0088,cover=4.20001
        1:leaf=-0.111758,cover=3.20001
        2:leaf=-0,cover=1
0:[f187<0.000299] yes=1,no=2,missing=1,gain=0.882333,cover=4.14633
        1:leaf=-0.104649,cover=3.14633
        2:leaf=-0,cover=1
0:[f187<0.000299] yes=1,no=2,missing=1,gain=0.777066,cover=4.07995
        1:leaf=-0.0983629,cover=3.07995
        2:leaf=-0,cover=1
0:[f221<2] yes=1,no=2,missing=2,gain=0.693848,cover=4.00458
        1:leaf=-0,cover=1.19336
        2:leaf=-0.0951405,cover=2.81121

predictLeaves' result(20 samples):
1.0 1.0 1.0 1.0 1.0 1.0 
1.0 1.0 1.0 1.0 1.0 1.0 
1.0 1.0 1.0 1.0 1.0 1.0 
2.0 2.0 2.0 2.0 2.0 2.0 
2.0 2.0 2.0 2.0 2.0 2.0 
2.0 2.0 2.0 2.0 2.0 2.0 
1.0 1.0 1.0 1.0 1.0 2.0 
1.0 1.0 1.0 1.0 1.0 2.0 
2.0 2.0 2.0 2.0 2.0 1.0 
1.0 1.0 1.0 1.0 1.0 2.0 
1.0 1.0 1.0 1.0 1.0 2.0 
2.0 2.0 2.0 2.0 2.0 2.0 
1.0 1.0 1.0 1.0 1.0 2.0 
1.0 1.0 1.0 1.0 1.0 2.0 
1.0 1.0 1.0 1.0 1.0 2.0 
1.0 1.0 1.0 1.0 1.0 2.0 
1.0 1.0 1.0 1.0 1.0 2.0 
2.0 2.0 2.0 2.0 2.0 1.0 
1.0 1.0 1.0 1.0 1.0 2.0 
1.0 1.0 1.0 1.0 1.0 2.0 

code:
```
 val paramMap = List(
      "booster"-> parameter.getBooster, //default gbtree
      "gamma"->parameter.getGamma, //default 0
      "min_child_weight"->parameter.getMin_child_weight, //default 1
      "lambda"->parameter.getLambda, //default 1
      "alpha"->parameter.getAlpha, //default 1
      "eval_metric"->parameter.getEval_metric, //regression is rmse, classification is error
      "eta" -> parameter.getEta(),
      "max_depth" -> maxDepth, //default 6
      "num_class" -> num_class,
      "objective" -> "binary:logistic").toMap

    val xgBoostModel = XGBoost.train(
      train, paramMap, numRound.toInt, nWorkers = parameter.getnWorkers().toInt, useExternalMemory = false)
    println("train finish")

    // xgboost-spark appends the column containing prediction results

    //predict the testDF
    //val predictions = xgBoostModel.transform(testDF)
    //predictions.show(150)

    val feature = rawData.map{line=>
      line.features
    }
    //xgBoostModel.asInstanceOf[XGBoostClassificationModel]
    val leaf = xgBoostModel.predictLeaves(feature)
    val raw = leaf.collect()


    println("raw")
    for(i<-0 until raw.length){
      var tmp = raw(i)
      for(j<-0 until tmp.length){
        var tmp1 = tmp(j)
        for(k<- 0 until tmp1.length){
          print(tmp1(k)+" ")
        }
        println()
      }
    }
```

**Comment by nedved1990** [comment]
@superbobry sample is below:
0 27:1.0 161:1.0 190:267.0 191:4.83333 194:1.0 195:1.0 196:1.0 197:1.0 198:1.0 199:1.0 200:1.0 201:1.0 202:1.0 203:1.0 204:1.0 205:1.0 206:1.0 207:1.0 208:1.0 209:1.0 210:1.0 211:1.0 212:1.0 213:1.0 214:1.0 215:1.0 216:1.0 217:1.0 218:1.0 219:1.0 220:1.0 221:1.0 222:1.0 223:1.0 229:1.0 230:1.0 233:1.0 235:1.0 236:1.0 237:1.0 238:1.0 239:1.0 240:1.0 241:1.0 243:1.0 244:1.0 245:1.0 246:1.0 247:1.0 248:1.0 249:1.0 250:1.0 251:1.0 252:1.0 253:1.0 256:1.0 257:1.0 258:1.0 259:1.0 262:1.0 263:1.0 265:1.0 266:1.0 267:1.0 268:1.0 269:1.0 270:1.0 275:1.0 276:1.0 277:1.0 280:1.0 281:1.0 282:1.0 284:1.0 285:1.0 287:1.0 288:1.0 289:1.0 291:1.0 292:1.0 294:1.0 295:1.0 296:1.0 297:1.0 298:1.0 299:1.0 300:1.0 301:1.0 302:1.0 304:1.0 305:1.0 309:1.0 310:1.0 311:1.0 312:1.0 314:1.0 315:1.0 316:1.0 318:1.0 319:1.0 320:1.0 321:1.0 322:1.0 323:1.0 325:1.0 326:1.0 327:1.0 328:1.0 329:1.0 330:1.0 331:1.0 332:1.0 333:1.0 334:1.0 336:1.0 337:1.0 338:1.0 339:1.0 340:1.0 341:1.0 342:1.0 343:1.0 344:1.0 345:1.0 346:1.0 347:1.0 348:1.0 349:1.0 350:1.0 351:1.0 352:1.0 353:1.0 354:1.0 355:1.0 356:1.0 357:1.0 358:1.0 359:1.0 360:1.0 361:1.0 362:1.0 363:1.0 364:1.0 365:1.0 366:1.0 367:1.0 368:1.0 369:1.0 370:1.0 371:1.0 372:1.0 373:1.0 374:1.0 375:1.0 376:1.0 377:1.0 378:1.0 379:1.0 
0 21:1.0 55:1.0 120:1.0 128:1.0 130:1.0 190:5028.0 191:4.65609 194:1.0 195:1.0 196:1.0 197:1.0 198:1.0 199:1.0 200:1.0 201:1.0 202:1.0 203:1.0 204:1.0 205:1.0 206:1.0 207:1.0 208:1.0 209:1.0 210:1.0 211:1.0 212:1.0 213:1.0 214:1.0 215:1.0 216:1.0 217:1.0 218:1.0 219:1.0 220:1.0 221:1.0 222:1.0 223:1.0 229:1.0 230:1.0 233:1.0 235:1.0 236:1.0 237:1.0 238:1.0 239:1.0 240:1.0 241:1.0 243:1.0 244:1.0 245:1.0 246:1.0 247:1.0 248:1.0 249:1.0 250:1.0 251:1.0 252:1.0 253:1.0 256:1.0 257:1.0 258:1.0 259:1.0 262:1.0 263:1.0 265:1.0 266:1.0 267:1.0 268:1.0 269:1.0 270:1.0 275:1.0 276:1.0 277:1.0 280:1.0 281:1.0 282:1.0 284:1.0 285:1.0 287:1.0 288:1.0 289:1.0 291:1.0 292:1.0 294:1.0 295:1.0 296:1.0 297:1.0 298:1.0 299:1.0 300:1.0 301:1.0 302:1.0 304:1.0 305:1.0 309:1.0 310:1.0 311:1.0 312:1.0 314:1.0 315:1.0 316:1.0 318:1.0 319:1.0 320:1.0 321:1.0 322:1.0 323:1.0 325:1.0 326:1.0 327:1.0 328:1.0 329:1.0 330:1.0 331:1.0 332:1.0 333:1.0 334:1.0 336:1.0 337:1.0 338:1.0 339:1.0 340:1.0 341:1.0 342:1.0 343:1.0 344:1.0 345:1.0 346:1.0 347:1.0 348:1.0 349:1.0 350:1.0 351:1.0 352:1.0 353:1.0 354:1.0 355:1.0 356:1.0 357:1.0 358:1.0 359:1.0 360:1.0 361:1.0 362:1.0 363:1.0 364:1.0 365:1.0 366:1.0 367:1.0 368:1.0 369:1.0 370:1.0 371:1.0 372:1.0 373:1.0 374:1.0 375:1.0 376:1.0 377:1.0 378:1.0 379:1.0 
0 9:1.0 140:1.0 142:1.0 190:674.0 191:2.21895 194:1.0 195:1.0 196:1.0 197:1.0 198:1.0 199:1.0 200:1.0 201:1.0 202:1.0 203:1.0 204:1.0 205:1.0 206:1.0 207:1.0 208:1.0 209:1.0 210:1.0 211:1.0 212:1.0 213:1.0 214:1.0 215:1.0 216:1.0 217:1.0 218:1.0 219:1.0 220:1.0 221:1.0 222:1.0 223:1.0 229:1.0 230:1.0 233:1.0 235:1.0 236:1.0 237:1.0 238:1.0 239:1.0 240:1.0 241:1.0 243:1.0 244:1.0 245:1.0 246:1.0 247:1.0 248:1.0 249:1.0 250:1.0 251:1.0 252:1.0 253:1.0 256:1.0 257:1.0 258:1.0 259:1.0 262:1.0 263:1.0 265:1.0 266:1.0 267:1.0 268:1.0 269:1.0 270:1.0 275:1.0 276:1.0 277:1.0 280:1.0 281:1.0 282:1.0 284:1.0 285:1.0 287:1.0 288:1.0 289:1.0 291:1.0 292:1.0 294:1.0 295:1.0 296:1.0 297:1.0 298:1.0 299:1.0 300:1.0 301:1.0 302:1.0 304:1.0 305:1.0 309:1.0 310:1.0 311:1.0 312:1.0 314:1.0 315:1.0 316:1.0 318:1.0 319:1.0 320:1.0 321:1.0 322:1.0 323:1.0 325:1.0 326:1.0 327:1.0 328:1.0 329:1.0 330:1.0 331:1.0 332:1.0 333:1.0 334:1.0 336:1.0 337:1.0 338:1.0 339:1.0 340:1.0 341:1.0 342:1.0 343:1.0 344:1.0 345:1.0 346:1.0 347:1.0 348:1.0 349:1.0 350:1.0 351:1.0 352:1.0 353:1.0 354:1.0 355:1.0 356:1.0 357:1.0 358:1.0 359:1.0 360:1.0 361:1.0 362:1.0 363:1.0 364:1.0 365:1.0 366:1.0 367:1.0 368:1.0 369:1.0 370:1.0 371:1.0 372:1.0 373:1.0 374:1.0 375:1.0 376:1.0 377:1.0 378:1.0 379:1.0 
0 24:1.0 144:1.0 146:1.0 148:1.0 156:1.0 157:1.0 159:1.0 161:1.0 188:0.0018 189:0.0016 190:115871.0 191:3.49825 192:2.0 200:1.0 206:1.0 209:1.0 251:1.0 256:1.0 257:1.0 259:1.0 275:1.0 284:1.0 285:1.0 287:1.0 302:1.0 305:1.0 
0 22:1.0 133:1.0 145:1.0 171:1.0 175:1.0 188:3.0E-4 189:2.0E-4 190:108342.0 191:4.64809 192:1.0 195:1.0 196:1.0 197:1.0 198:1.0 200:1.0 201:1.0 203:1.0 204:1.0 205:1.0 206:1.0 207:1.0 208:1.0 209:1.0 211:1.0 212:1.0 214:1.0 215:1.0 216:1.0 218:1.0 230:1.0 233:1.0 235:1.0 237:1.0 240:1.0 241:1.0 246:1.0 248:1.0 250:1.0 251:1.0 252:1.0 256:1.0 257:1.0 258:1.0 259:1.0 262:1.0 265:1.0 266:1.0 274:1.0 275:1.0 277:1.0 280:1.0 281:1.0 282:1.0 284:1.0 285:1.0 287:1.0 288:1.0 289:1.0 290:1.0 291:1.0 292:1.0 293:1.0 294:1.0 298:1.0 302:1.0 304:1.0 310:1.0 311:1.0 314:1.0 315:1.0 316:1.0 318:1.0 319:1.0 326:1.0 327:1.0 329:1.0 330:1.0 331:1.0 332:1.0 333:1.0 334:1.0 337:1.0 339:1.0 340:1.0 346:1.0 348:1.0 349:1.0 350:1.0 353:1.0 364:1.0 374:1.0 375:1.0 378:1.0 379:1.0 380:22.0 381:2.0 
0 22:1.0 134:1.0 135:1.0 137:1.0 138:1.0 145:1.0 147:1.0 148:1.0 154:1.0 156:1.0 157:1.0 172:1.0 182:1.0 183:1.0 186:1.0 187:1.0 188:4.0E-4 189:4.0E-4 190:3065160.0 191:4.09263 192:3.0 195:1.0 196:1.0 197:1.0 200:1.0 201:1.0 202:1.0 204:1.0 206:1.0 207:1.0 209:1.0 210:1.0 211:1.0 215:1.0 230:1.0 233:1.0 235:1.0 236:1.0 240:1.0 241:1.0 243:1.0 245:1.0 251:1.0 256:1.0 257:1.0 258:1.0 259:1.0 262:1.0 265:1.0 266:1.0 267:1.0 268:1.0 269:1.0 270:1.0 275:1.0 277:1.0 282:1.0 284:1.0 285:1.0 287:1.0 289:1.0 291:1.0 292:1.0 302:1.0 304:1.0 309:1.0 315:1.0 318:1.0 331:1.0 332:1.0 333:1.0 334:1.0 
0 25:1.0 147:1.0 190:6984.0 191:3.84759 192:1.0 195:1.0 196:1.0 197:1.0 200:1.0 201:1.0 202:1.0 204:1.0 206:1.0 209:1.0 211:1.0 212:1.0 214:1.0 215:1.0 229:1.0 230:1.0 235:1.0 236:1.0 237:1.0 239:1.0 240:1.0 241:1.0 243:1.0 245:1.0 250:1.0 251:1.0 256:1.0 257:1.0 259:1.0 262:1.0 265:1.0 267:1.0 268:1.0 269:1.0 270:1.0 275:1.0 277:1.0 282:1.0 284:1.0 285:1.0 287:1.0 291:1.0 301:1.0 302:1.0 304:1.0 305:1.0 311:1.0 314:1.0 315:1.0 325:1.0 326:1.0 327:1.0 329:1.0 330:1.0 331:1.0 332:1.0 333:1.0 334:1.0 337:1.0 339:1.0 340:1.0 343:1.0 346:1.0 348:1.0 349:1.0 364:1.0 374:1.0 375:1.0 378:1.0 379:1.0 380:21.0 381:1.0 
0 8:1.0 59:1.0 64:1.0 65:1.0 67:1.0 116:1.0 188:2.0E-4 189:4.0E-4 190:1139623.0 191:4.91549 192:3.0 195:1.0 197:1.0 200:1.0 202:1.0 204:1.0 206:1.0 209:1.0 215:1.0 230:1.0 233:1.0 240:1.0 241:1.0 243:1.0 245:1.0 251:1.0 256:1.0 257:1.0 258:1.0 259:1.0 262:1.0 265:1.0 266:1.0 267:1.0 268:1.0 269:1.0 270:1.0 275:1.0 277:1.0 282:1.0 284:1.0 285:1.0 287:1.0 288:1.0 291:1.0 302:1.0 304:1.0 305:1.0 331:1.0 332:1.0 333:1.0 334:1.0 380:26.0 381:1.0 
1 17:1.0 113:1.0 188:0.0016 189:0.0018 190:2706480.0 191:2.57706 192:3.0 195:1.0 196:1.0 197:1.0 200:1.0 201:1.0 202:1.0 204:1.0 206:1.0 207:1.0 208:1.0 209:1.0 211:1.0 214:1.0 215:1.0 222:1.0 230:1.0 232:1.0 233:1.0 235:1.0 236:1.0 237:1.0 238:1.0 239:1.0 240:1.0 241:1.0 243:1.0 245:1.0 251:1.0 256:1.0 257:1.0 258:1.0 259:1.0 262:1.0 265:1.0 267:1.0 268:1.0 269:1.0 270:1.0 275:1.0 277:1.0 282:1.0 284:1.0 285:1.0 287:1.0 288:1.0 292:1.0 293:1.0 294:1.0 295:1.0 296:1.0 297:1.0 298:1.0 300:1.0 302:1.0 304:1.0 305:1.0 311:1.0 313:1.0 326:1.0 327:1.0 329:1.0 330:1.0 331:1.0 332:1.0 333:1.0 334:1.0 337:1.0 339:1.0 340:1.0 346:1.0 348:1.0 349:1.0 364:1.0 374:1.0 375:1.0 378:1.0 379:1.0 380:26.0 381:1.0 382:3.0 
0 4:1.0 46:1.0 47:1.0 83:1.0 85:1.0 90:1.0 190:4723.0 191:3.61638 195:1.0 196:1.0 197:1.0 200:1.0 201:1.0 204:1.0 208:1.0 209:1.0 211:1.0 212:1.0 214:1.0 215:1.0 216:1.0 218:1.0 229:1.0 230:1.0 235:1.0 236:1.0 237:1.0 238:1.0 240:1.0 241:1.0 250:1.0 251:1.0 256:1.0 257:1.0 258:1.0 259:1.0 262:1.0 275:1.0 281:1.0 282:1.0 291:1.0 298:1.0 302:1.0 304:1.0 305:1.0 315:1.0 326:1.0 327:1.0 329:1.0 330:1.0 331:1.0 332:1.0 333:1.0 334:1.0 337:1.0 339:1.0 340:1.0 346:1.0 348:1.0 349:1.0 354:1.0 364:1.0 374:1.0 375:1.0 378:1.0 379:1.0 380:18.0 381:1.0 
0 4:1.0 43:1.0 44:1.0 90:1.0 188:1.0E-4 189:2.0E-4 190:218818.0 191:3.9874 192:3.0 195:1.0 196:1.0 197:1.0 200:1.0 201:1.0 202:1.0 204:1.0 206:1.0 209:1.0 211:1.0 214:1.0 215:1.0 216:1.0 218:1.0 219:1.0 230:1.0 233:1.0 235:1.0 236:1.0 239:1.0 240:1.0 241:1.0 243:1.0 245:1.0 251:1.0 256:1.0 257:1.0 258:1.0 259:1.0 262:1.0 265:1.0 267:1.0 268:1.0 269:1.0 270:1.0 275:1.0 277:1.0 282:1.0 284:1.0 285:1.0 287:1.0 291:1.0 301:1.0 302:1.0 304:1.0 305:1.0 326:1.0 327:1.0 329:1.0 330:1.0 331:1.0 332:1.0 333:1.0 334:1.0 336:1.0 337:1.0 338:1.0 339:1.0 340:1.0 346:1.0 348:1.0 349:1.0 350:1.0 351:1.0 353:1.0 356:1.0 357:1.0 358:1.0 361:1.0 364:1.0 374:1.0 375:1.0 378:1.0 379:1.0 380:40.0 381:1.0 
0 22:1.0 134:1.0 135:1.0 137:1.0 138:1.0 145:1.0 147:1.0 148:1.0 154:1.0 156:1.0 157:1.0 172:1.0 182:1.0 183:1.0 186:1.0 187:1.0 188:4.0E-4 189:4.0E-4 190:3065160.0 191:4.09263 192:3.0 195:1.0 197:1.0 200:1.0 201:1.0 202:1.0 204:1.0 206:1.0 208:1.0 209:1.0 211:1.0 215:1.0 230:1.0 236:1.0 240:1.0 241:1.0 243:1.0 244:1.0 245:1.0 250:1.0 251:1.0 256:1.0 257:1.0 258:1.0 259:1.0 262:1.0 265:1.0 266:1.0 267:1.0 268:1.0 269:1.0 270:1.0 275:1.0 277:1.0 284:1.0 285:1.0 287:1.0 288:1.0 298:1.0 301:1.0 302:1.0 304:1.0 305:1.0 331:1.0 332:1.0 333:1.0 334:1.0 380:23.0 381:1.0 382:1.0 
0 23:1.0 139:1.0 140:1.0 141:1.0 190:63287.0 191:4.93216 192:3.0 195:1.0 196:1.0 197:1.0 198:1.0 200:1.0 204:1.0 206:1.0 207:1.0 209:1.0 211:1.0 214:1.0 215:1.0 217:1.0 221:1.0 230:1.0 233:1.0 235:1.0 236:1.0 240:1.0 241:1.0 243:1.0 245:1.0 246:1.0 247:1.0 248:1.0 250:1.0 251:1.0 256:1.0 257:1.0 258:1.0 259:1.0 267:1.0 269:1.0 270:1.0 275:1.0 282:1.0 284:1.0 285:1.0 287:1.0 289:1.0 291:1.0 292:1.0 301:1.0 302:1.0 304:1.0 305:1.0 328:1.0 331:1.0 332:1.0 333:1.0 334:1.0 339:1.0 344:1.0 347:1.0 348:1.0 349:1.0 370:1.0 380:19.0 381:2.0 
0 25:1.0 138:1.0 146:1.0 147:1.0 153:1.0 154:1.0 186:1.0 188:1.0E-4 189:1.0E-4 190:11909.0 191:4.67536 192:3.0 195:1.0 197:1.0 198:1.0 200:1.0 201:1.0 202:1.0 206:1.0 208:1.0 209:1.0 210:1.0 212:1.0 214:1.0 215:1.0 218:1.0 230:1.0 240:1.0 241:1.0 243:1.0 245:1.0 246:1.0 248:1.0 250:1.0 251:1.0 256:1.0 257:1.0 259:1.0 262:1.0 263:1.0 265:1.0 266:1.0 267:1.0 269:1.0 270:1.0 275:1.0 281:1.0 284:1.0 285:1.0 287:1.0 291:1.0 298:1.0 301:1.0 302:1.0 304:1.0 305:1.0 306:1.0 307:1.0 308:1.0 309:1.0 310:1.0 311:1.0 312:1.0 315:1.0 316:1.0 318:1.0 319:1.0 326:1.0 327:1.0 329:1.0 330:1.0 331:1.0 332:1.0 333:1.0 334:1.0 337:1.0 339:1.0 340:1.0 346:1.0 348:1.0 349:1.0 350:1.0 353:1.0 364:1.0 374:1.0 375:1.0 378:1.0 379:1.0 380:27.0 381:2.0 
0 22:1.0 136:1.0 150:1.0 151:1.0 152:1.0 153:1.0 154:1.0 190:21775.0 191:4.63348 192:1.0 195:1.0 197:1.0 198:1.0 200:1.0 206:1.0 209:1.0 210:1.0 211:1.0 212:1.0 218:1.0 219:1.0 229:1.0 230:1.0 231:1.0 240:1.0 241:1.0 243:1.0 245:1.0 246:1.0 247:1.0 248:1.0 250:1.0 251:1.0 256:1.0 257:1.0 259:1.0 275:1.0 284:1.0 285:1.0 287:1.0 291:1.0 302:1.0 304:1.0 305:1.0 309:1.0 310:1.0 311:1.0 315:1.0 316:1.0 318:1.0 319:1.0 348:1.0 349:1.0 350:1.0 353:1.0 354:1.0 356:1.0 357:1.0 361:1.0 368:1.0 369:1.0 375:1.0 377:1.0 380:29.0 
0 12:1.0 65:1.0 83:1.0 85:1.0 189:3.0E-4 190:110036.0 191:3.84146 192:3.0 195:1.0 197:1.0 198:1.0 200:1.0 205:1.0 206:1.0 207:1.0 209:1.0 210:1.0 211:1.0 212:1.0 215:1.0 230:1.0 240:1.0 241:1.0 243:1.0 245:1.0 246:1.0 248:1.0 250:1.0 251:1.0 256:1.0 257:1.0 259:1.0 265:1.0 266:1.0 275:1.0 284:1.0 285:1.0 287:1.0 289:1.0 290:1.0 291:1.0 292:1.0 301:1.0 302:1.0 304:1.0 309:1.0 310:1.0 311:1.0 315:1.0 316:1.0 318:1.0 319:1.0 331:1.0 332:1.0 333:1.0 334:1.0 380:30.0 381:2.0 
0 17:1.0 109:1.0 188:1.0E-4 189:1.0E-4 190:221462.0 191:4.40128 192:3.0 195:1.0 197:1.0 199:1.0 200:1.0 201:1.0 204:1.0 205:1.0 206:1.0 208:1.0 209:1.0 211:1.0 212:1.0 214:1.0 230:1.0 240:1.0 241:1.0 243:1.0 245:1.0 250:1.0 251:1.0 256:1.0 257:1.0 259:1.0 262:1.0 265:1.0 266:1.0 267:1.0 269:1.0 270:1.0 275:1.0 277:1.0 281:1.0 282:1.0 284:1.0 285:1.0 287:1.0 291:1.0 298:1.0 302:1.0 305:1.0 310:1.0 311:1.0 313:1.0 314:1.0 315:1.0 316:1.0 318:1.0 319:1.0 326:1.0 327:1.0 329:1.0 330:1.0 331:1.0 332:1.0 334:1.0 337:1.0 339:1.0 340:1.0 346:1.0 348:1.0 349:1.0 364:1.0 374:1.0 375:1.0 378:1.0 379:1.0 380:18.0 381:1.0 
1 22:1.0 134:1.0 135:1.0 137:1.0 138:1.0 145:1.0 147:1.0 148:1.0 154:1.0 156:1.0 157:1.0 172:1.0 182:1.0 183:1.0 186:1.0 187:1.0 188:4.0E-4 189:4.0E-4 190:3065160.0 191:4.09263 192:3.0 195:1.0 196:1.0 197:1.0 200:1.0 201:1.0 202:1.0 204:1.0 205:1.0 206:1.0 207:1.0 209:1.0 211:1.0 212:1.0 213:1.0 214:1.0 215:1.0 216:1.0 217:1.0 218:1.0 219:1.0 220:1.0 221:1.0 222:1.0 230:1.0 235:1.0 236:1.0 237:1.0 238:1.0 240:1.0 241:1.0 243:1.0 245:1.0 251:1.0 256:1.0 257:1.0 258:1.0 259:1.0 267:1.0 268:1.0 269:1.0 270:1.0 275:1.0 277:1.0 280:1.0 281:1.0 282:1.0 284:1.0 285:1.0 287:1.0 291:1.0 292:1.0 293:1.0 294:1.0 301:1.0 302:1.0 304:1.0 305:1.0 310:1.0 311:1.0 315:1.0 316:1.0 318:1.0 319:1.0 322:1.0 325:1.0 326:1.0 327:1.0 329:1.0 330:1.0 331:1.0 332:1.0 333:1.0 334:1.0 337:1.0 339:1.0 340:1.0 341:1.0 346:1.0 348:1.0 349:1.0 353:1.0 354:1.0 356:1.0 357:1.0 361:1.0 363:1.0 364:1.0 365:1.0 367:1.0 370:1.0 374:1.0 375:1.0 377:1.0 378:1.0 379:1.0 380:15.0 381:1.0 
0 26:1.0 160:1.0 188:1.0E-4 189:1.0E-4 190:4577.0 191:4.93462 192:1.0 195:1.0 197:1.0 200:1.0 201:1.0 202:1.0 204:1.0 205:1.0 206:1.0 207:1.0 208:1.0 209:1.0 211:1.0 215:1.0 219:1.0 229:1.0 230:1.0 233:1.0 239:1.0 240:1.0 241:1.0 243:1.0 244:1.0 245:1.0 250:1.0 251:1.0 256:1.0 257:1.0 259:1.0 262:1.0 265:1.0 266:1.0 267:1.0 268:1.0 269:1.0 270:1.0 275:1.0 277:1.0 280:1.0 281:1.0 282:1.0 284:1.0 285:1.0 287:1.0 288:1.0 290:1.0 291:1.0 298:1.0 301:1.0 302:1.0 305:1.0 331:1.0 332:1.0 333:1.0 334:1.0 348:1.0 349:1.0 356:1.0 357:1.0 358:1.0 361:1.0 375:1.0 380:29.0 381:1.0 
0 9:1.0 70:1.0 71:1.0 73:1.0 93:1.0 190:110265.0 191:4.86178 192:3.0 195:1.0 196:1.0 197:1.0 198:1.0 200:1.0 201:1.0 204:1.0 205:1.0 206:1.0 207:1.0 208:1.0 209:1.0 211:1.0 212:1.0 215:1.0 218:1.0 219:1.0 230:1.0 233:1.0 235:1.0 236:1.0 238:1.0 240:1.0 241:1.0 243:1.0 245:1.0 246:1.0 247:1.0 248:1.0 250:1.0 251:1.0 256:1.0 257:1.0 258:1.0 259:1.0 262:1.0 263:1.0 265:1.0 266:1.0 275:1.0 277:1.0 281:1.0 282:1.0 284:1.0 285:1.0 287:1.0 290:1.0 291:1.0 292:1.0 293:1.0 295:1.0 298:1.0 299:1.0 302:1.0 304:1.0 310:1.0 311:1.0 313:1.0 316:1.0 319:1.0 331:1.0 332:1.0 333:1.0 334:1.0 348:1.0 349:1.0 350:1.0 356:1.0 357:1.0 361:1.0 375:1.0 379:1.0 380:43.0 381:2.0

**Comment by zhangmengzju** [comment]
the default missing value is float.NaN, not 0
