### ISSUE TITLE
Error in install.packages : type == "both" cannot be used with 'repos = NULL'

### ISSUE THREAD

**Issue by alfords** [dmlc/xgboost#259]
While installing the package in R, I always get following error info:

Error in install.packages : type == "both" cannot be used with 'repos = NULL'

Any tips to fix it? Thanks.

**Comment by tqchen** [comment]
interesting, please use the devtools command here https://github.com/dmlc/xgboost/tree/master/R-package

**Comment by alfords** [comment]
Hi Tianqi, 

I've installed rtools in window, and tried to use this command: 
devtools::install_github('dmlc/xgboost',subdir='R-package')

But got another error:  
Error in loadNamespace(name) : there is no package called 慸evtools?

Thanks.

**Comment by tqchen** [comment]
you need to install devtools first, thanks

**Comment by alfords** [comment]
> devtools::install_github('dmlc/xgboost',subdir='R-package')

Downloading github repo dmlc/xgboost@master
Error in loadNamespace(name) : there is no package called 慼ttr?

i guess it is not required TTR package. thanks.

**Comment by tqchen** [comment]
maybe it was needed for devtools

**Comment by alfords** [comment]
thanks. i tried another way to install the xgboost_0.3-3.tar.gz on CRAN

**Comment by alfords** [comment]
the package was installed. but got another issue:

Error: unknown evaluation metric type: mlogloss

according to the Q&A on following page,  
https://www.kaggle.com/c/otto-group-product-classification-challenge/forums/t/12947/achieve-0-50776-on-the-leaderboard-in-a-minute-with-xgboost

i checked my devtools version, which is 1.7.
and i am using Windows 7 and R 3.2.0

any tips to fix it? thanks.

**Comment by tqchen** [comment]
You do need to install the version on github to use this. If devtools do not work for you, try to clone the repo, and type R CMD INSTALL R-package

**Comment by alfords** [comment]
thanks so much for the helpful tips. the package is working now.

**Comment by erielestrada** [comment]
try
install.packages("path", repos = NULL, type = "source")

I installed from a local file,  path is, well, the path, between "", repos can be null if you install locally, so I changed the value of argument type, and that's it.

you should also check https://stat.ethz.ch/R-manual/R-devel/library/utils/html/install.packages.html

**Comment by vishy730** [comment]
Hi, have downloaded zip file from this location, https://github.com/ropensci/plotly/releases/tag/0.3
and tried teh above steps.. with type=source.. neither it gave error nor installed..
I am using windows server 2012 and latest R and Rstudio versions
