### ISSUE TITLE
how to set early_stopping_round in command line

### ISSUE THREAD

**Issue by PseudoProgrammer** [dmlc/xgboost#2590]
I use command line to implement xgboost，like "./xgboost model_output=......"
how to set early_stopping_round in command line，i can't find solution through google？
waiting for answer online，thank you！

**Comment by pommedeterresautee** [comment]
You can set conf file as here https://github.com/dmlc/xgboost/tree/master/demo/rank and use the options as here http://xgboost.readthedocs.io/en/latest//parameter.html#command-line-parameters
