### ISSUE TITLE
Unable clone help!

### ISSUE THREAD

**Issue by jeehyun100** [dmlc/xgboost#2595]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System:
ubuntu 16.04
Compiler:

Package used (python/R/jvm/C++):

`xgboost` version used:

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`)
4f7fb12585dfee57c7cb5bd7abd13f6a939aaa06
2. Logs will be helpful (If logs are large, please upload as attachment).
remote: Counting objects: 3142, done.
remote: Total 3142 (delta 0), reused 0 (delta 0), pack-reused 3142
Receiving objects: 100% (3142/3142), 900.20 KiB | 430.00 KiB/s, done.
Resolving deltas: 100% (2039/2039), done.
Checking connectivity... done.
Submodule path 'rabit': checked out 'a764d45cfb438cc9f15cf47ce586c02ff2c65d0f'
Unable to checkout 'f3937a96fdec78a73446aaaa114c112ff31f5503' in submodule path 'cub'

If you are using python package, please provide

1. The python version and distribution : 3.5
2. The command to install `xgboost` if you are not installing from source

## Steps to reproduce

1.  git clone --recursive https://github.com/dmlc/xgboost
Submodule path 'dmlc-core': checked out 'b5bec5481df86e8e6728d8bd80a61d87ef3b2cd5'
Cloning into 'nccl'...
remote: Counting objects: 652, done.
remote: Total 652 (delta 0), reused 0 (delta 0), pack-reused 652
Receiving objects: 100% (652/652), 1.38 MiB | 493.00 KiB/s, done.
Resolving deltas: 100% (411/411), done.
Checking connectivity... done.
Submodule path 'nccl': checked out '018ff75f78e4d3616051fdcd3da7cf64249b6d59'
Cloning into 'rabit'...
remote: Counting objects: 3142, done.
remote: Total 3142 (delta 0), reused 0 (delta 0), pack-reused 3142
Receiving objects: 100% (3142/3142), 900.20 KiB | 430.00 KiB/s, done.
Resolving deltas: 100% (2039/2039), done.
Checking connectivity... done.
Submodule path 'rabit': checked out 'a764d45cfb438cc9f15cf47ce586c02ff2c65d0f'
Unable to checkout 'f3937a96fdec78a73446aaaa114c112ff31f5503' in submodule path 'cub'

**Comment by RAMitchell** [comment]
Should be fixed in #2591

**Comment by earthling4** [comment]
This doesn't seem to be fixed.  Seeing this now
