### ISSUE TITLE
R session error

### ISSUE THREAD

**Issue by FingerDrill** [dmlc/xgboost#2598]
I'm using R in AWS r4.large instance. I have set my rstudio server in it with [AMI of Louis Aslett.](http://www.louisaslett.com/RStudio_AMI/)
I'm new to data science and entered competition on kaggle (instacart competition).

I have encountered with error during xgb.cv.
**" R Session Error : The previous R session was abnormally terminated due to an unexpected crash. You may have lost workspace data as a result of this crash."**

**Every time I execute my code, this error takes place.**

## **What I did below :** 

I've studied about parameter tuning in [this tutorial](https://www.hackerearth.com/practice/machine-learning/machine-learning-algorithms/beginners-tutorial-on-xgboost-parameter-tuning-r/tutorial/)

**I applied the tutorial to my data with customized evaluation metric function :**
**It calculates mean f1 score.**
```
xgb_eval_f1 <- function (yhat, dtrain) {
  require(ModelMetrics)
  y <-  getinfo(dtrain, "label")
  dt <- data.table(user_id=attr(dtrain, 'user_id'), purch=y, pred=yhat)
  f1 <- mean(dt[,.(f1score=f1Score(purch, pred, cutoff=0.2)), by=user_id]$f1score)
  return (list(metric = "f1", value = f1))
}
```

**For finding best nround, I used xgb.cv function.**
```
dtrain <- xgb.DMatrix(data = as.matrix(train %>% select(-user_id, -reordered)),
                      label = train$reordered)
attr(dtrain, 'user_id') <- train$user_id
params_d <- list(booster = "gbtree",
                 objective = "reg:logistic",
                 eta = 0.3,
                 gamma = 0,
                 max_depth = 6,
                 min_child_weight = 1,
                 subsample = 1,
                 colsample_bytree=1)


xgbcv <- xgb.cv(params = params_d, data=dtrain,
                nrounds = 100, 
                nfold = 5,
                showsd=T, 
                feval = xgb_eval_f1,
                stratified = T,
                print_every_n = 10,
                early_stopping_rounds = 15,
                maximize = T)
```

**data size of dtrain :** 
`dim: 8474661 x 30  info: label  colnames: yes`

If you need more information, please tell me.

**sessionInfo() :**

R version 3.4.0 (2017-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.2 LTS

Matrix products: default
BLAS: /usr/lib/openblas-base/libblas.so.3
LAPACK: /usr/lib/libopenblasp-r0.2.18.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] xgboost_0.6-4 dplyr_0.7.2  

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.11      lattice_0.20-35   assertthat_0.2.0  grid_3.4.0       
 [5] R6_2.2.1          magrittr_1.5      stringi_1.1.5     rlang_0.1.1      
 [9] data.table_1.10.4 bindrcpp_0.2      Matrix_1.2-10     tools_3.4.0      
[13] glue_1.1.1        compiler_3.4.0    pkgconfig_2.0.1   bindr_0.1        
[17] tibble_1.3.1

**Comment by FingerDrill** [comment]
Sorry for my mistake. Customized function does not fit for my structure. I'll check it

**Comment by FingerDrill** [comment]
I changed my function to below :
```
xgb_eval_f1 <- function (yhat, dtrain) {
  require(ModelMetrics)
  y <-  getinfo(dtrain, "label")
  dt <- data.table(user_id=attr(dtrain, 'user_id'), purch=y, pred=yhat)
  f1 <- mean(dt[,.(f1score=f1Score(purch, pred, cutoff=0.2)), by=user_id]$f1score)
  return (list(metric = "f1", value = f1))
}
```
But still error exists. Please someone save me!

**Comment by hetong007** [comment]
To check if it is a memory problem, you can use a small subset of the data to train.

If the problem stays, please provide a script and a small dataset to reproduce.
