### ISSUE TITLE
[jvm-packages] I can not disable training logging with training parameter choices.

### ISSUE THREAD

**Issue by parmezzan** [dmlc/xgboost#2601]
Operating System: Windows
Package used jvm
`xgboost` version used: 0.7
The commit hash: 00eda28b3c6270f2434b09f4ea46fe9ee6c16c53

## Issue
I cannot prevent these types of training logs (iteration printing): 
"[620]	test-rmse:0.023242	train-rmse:0.018132"

I have tried 
"verbose",0
"silent",1
"silent",2
"silent","True"

**Comment by Adnation** [comment]
I am facing the same issue with xgboost cv.
