### ISSUE TITLE
[jvm-packages]blocking problem about xgboost on spark

### ISSUE THREAD

**Issue by GrayMissing** [dmlc/xgboost#2604]
## Environment info

Compiler:  gcc 6.4.0 (centos6 && mac os)

Package used (python/R/jvm/C++): jvm

`xgboost` version used: master

spark version: 2.2.0 and 2.1.0

## Problem
I have a question about parameter **nWorker**, some old doc said 0 means the default partition number of data, but the newest code has limit it has to be greater than 0, and when I change the nWorker greater than 8, it seems blocked.

## Log

17/08/15 14:44:55 INFO DAGScheduler: Submitting 10 missing tasks from ResultStage 1 (ZippedPartitionsRDD2[11] at zipPartitions at XGBoost.scala:117)
17/08/15 14:44:55 INFO TaskSchedulerImpl: Adding task set 1.0 with 10 tasks
17/08/15 14:44:55 INFO TaskSetManager: Starting task 0.0 in stage 1.0 (TID 8, localhost, executor driver, partition 0, ANY, 6327 bytes)
17/08/15 14:44:55 INFO TaskSetManager: Starting task 1.0 in stage 1.0 (TID 9, localhost, executor driver, partition 1, ANY, 6327 bytes)
17/08/15 14:44:55 INFO TaskSetManager: Starting task 2.0 in stage 1.0 (TID 10, localhost, executor driver, partition 2, ANY, 6327 bytes)
17/08/15 14:44:55 INFO TaskSetManager: Starting task 3.0 in stage 1.0 (TID 11, localhost, executor driver, partition 3, ANY, 6327 bytes)
17/08/15 14:44:55 INFO TaskSetManager: Starting task 4.0 in stage 1.0 (TID 12, localhost, executor driver, partition 4, ANY, 6327 bytes)
17/08/15 14:44:55 INFO TaskSetManager: Starting task 5.0 in stage 1.0 (TID 13, localhost, executor driver, partition 5, ANY, 6327 bytes)
17/08/15 14:44:55 INFO TaskSetManager: Starting task 6.0 in stage 1.0 (TID 14, localhost, executor driver, partition 6, ANY, 6327 bytes)
17/08/15 14:44:55 INFO TaskSetManager: Starting task 7.0 in stage 1.0 (TID 15, localhost, executor driver, partition 7, ANY, 6327 bytes)
17/08/15 14:44:55 INFO Executor: Running task 2.0 in stage 1.0 (TID 10)
17/08/15 14:44:55 INFO Executor: Running task 5.0 in stage 1.0 (TID 13)
17/08/15 14:44:55 INFO Executor: Running task 7.0 in stage 1.0 (TID 15)
17/08/15 14:44:55 INFO Executor: Running task 0.0 in stage 1.0 (TID 8)
17/08/15 14:44:55 INFO Executor: Running task 6.0 in stage 1.0 (TID 14)
17/08/15 14:44:55 INFO Executor: Running task 1.0 in stage 1.0 (TID 9)
17/08/15 14:44:55 INFO Executor: Running task 4.0 in stage 1.0 (TID 12)
17/08/15 14:44:55 INFO Executor: Running task 3.0 in stage 1.0 (TID 11)
17/08/15 14:44:55 INFO ShuffleBlockFetcherIterator: Getting 8 non-empty blocks out of 8 blocks
17/08/15 14:44:55 INFO ShuffleBlockFetcherIterator: Getting 8 non-empty blocks out of 8 blocks
17/08/15 14:44:55 INFO ShuffleBlockFetcherIterator: Getting 8 non-empty blocks out of 8 blocks
17/08/15 14:44:55 INFO ShuffleBlockFetcherIterator: Getting 8 non-empty blocks out of 8 blocks
17/08/15 14:44:55 INFO ShuffleBlockFetcherIterator: Getting 8 non-empty blocks out of 8 blocks
17/08/15 14:44:55 INFO ShuffleBlockFetcherIterator: Getting 8 non-empty blocks out of 8 blocks
17/08/15 14:44:55 INFO ShuffleBlockFetcherIterator: Getting 8 non-empty blocks out of 8 blocks
17/08/15 14:44:55 INFO ShuffleBlockFetcherIterator: Getting 8 non-empty blocks out of 8 blocks
17/08/15 14:44:55 INFO ShuffleBlockFetcherIterator: Started 0 remote fetches in 4 ms
17/08/15 14:44:55 INFO ShuffleBlockFetcherIterator: Started 0 remote fetches in 4 ms
17/08/15 14:44:55 INFO ShuffleBlockFetcherIterator: Started 0 remote fetches in 6 ms
17/08/15 14:44:55 INFO ShuffleBlockFetcherIterator: Started 0 remote fetches in 5 ms
17/08/15 14:44:55 INFO ShuffleBlockFetcherIterator: Started 0 remote fetches in 5 ms
17/08/15 14:44:55 INFO ShuffleBlockFetcherIterator: Started 0 remote fetches in 5 ms
17/08/15 14:44:55 INFO ShuffleBlockFetcherIterator: Started 0 remote fetches in 4 ms
17/08/15 14:44:55 INFO ShuffleBlockFetcherIterator: Started 0 remote fetches in 5 ms

**Comment by GrayMissing** [comment]
I already know why. It seems spark can only start task concurrently depend on parallelism num limit which can be fetch by sc.defaultParallelism

**Comment by CodingCat** [comment]
with xgboost4j-spark, you have to start one-wave job, that means if you have 40 cores available, you can only start no more than 40 workers of xgboost
