### ISSUE TITLE
xgb dump significant figures for leaf preds

### ISSUE THREAD

**Issue by dylanneenan** [dmlc/xgboost#2608]
Hi guys,

I am looking to use the model dump to reconstruct all trees in another environment for scoring purposes.

I'm seeing a slight discrepancy when using the 'predict' function vs. the model dump - i believe the source of this is rounding errors, as leaf predictions are truncated to 6sf in the dump.

Is it possible to include an option to increase the number of floating point digits in the dump?

Alternatively is there any 'hack' solution i can do - not sure whereabouts in the source code i can adjust this...

Thanks.  Using R.

example:
[1] "0:[Petal_Length<3.95] yes=1,no=2,missing=1,gain=26.2465,cover=135" "1:leaf=0.0**224811**,cover=52"
[3] "2:leaf=0.0289524,cover=83"

But a leaf one prediction is 
0.5**22481143474579**)

**Comment by pommedeterresautee** [comment]
MMmhhhh interesting, there is no such conversion in the C++ code
https://github.com/dmlc/xgboost/blob/6f16f0ef5829965ba420ef6937617600d286820a/src/tree/tree_model.cc#L18

**Comment by dylanneenan** [comment]
Hm the noise is in the order of 10^-5 to 10^-7 (as one would expect) so I'm not hugely concerned. Thanks for your help

**Comment by pommedeterresautee** [comment]
FYI https://github.com/dmlc/xgboost/issues/2077

**Comment by pommedeterresautee** [comment]
Also: https://github.com/dmlc/xgboost/pull/1726
