### ISSUE TITLE
Mac OS X: Missing __Unwind_Resume

### ISSUE THREAD

**Issue by abhisheksimhadri** [dmlc/xgboost#261]
Followed the steps below:

OS X:

For users who want OpenMP support using Homebrew, run brew update (ensures that you install gcc-4.9 or above) and brew install gcc --without-multilib. Once it is installed, edit Makefile by replacing:
export CC  = gcc
export CXX = g++
with

export CC  = gcc-4.9
export CXX = g++-4.9
Then run bash build.sh normally.

For users who want to use High Performance Computing for Mac OS X, download the GCC 4.9 binary tar ball and follow the installation guidance to install them under /usr/local. Then edit Makefile by replacing:
export CC  = gcc
export CXX = g++
with

export CC  = /usr/local/bin/gcc
export CXX = /usr/local/bin/g++
Then run bash build.sh normally. 

Running build.sh gives the following error:

g++-4.9 -Wall -O3 -msse2  -Wno-unknown-pragmas -fPIC -o xgboost updater.o gbm.o io.o main.o subtree/rabit/lib/librabit.a dmlc_simple.o -pthread -lm  
Undefined symbols for architecture x86_64:
  "__Unwind_Resume", referenced from:
      xgboost::tree::CreateUpdater(char const*) in updater.o
      xgboost::utils::Printf(char const*, ...) in updater.o
      xgboost::utils::Assert(bool, char const*, ...) in updater.o
      xgboost::utils::Check(bool, char const*, ...) in updater.o
      xgboost::utils::Error(char const*, ...) in updater.o
      rabit::utils::Assert(bool, char const*, ...) in updater.o
      rabit::TrackerPrintf(char const*, ...) in updater.o
      ...
  "start", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make: *** [xgboost] Error 1
-----------------------------
Building multi-thread xgboost failed
Start to build single-thread xgboost
rm -f -rf updater.o gbm.o io.o main.o dmlc_simple.o xgboost   wrapper/libxgboostwrapper.so  *.o  */*.o */*/*.o *~ */*~ */*/*~
cd subtree/rabit; make clean; cd ..
rm -f ./allreduce_base.o ./allreduce_robust.o ./engine.o ./engine_empty.o ./engine_mock.o ./rabit_wrapper.o ./engine_base.o ./engine_mpi.o lib/librabit.a lib/librabit_mpi.a lib/librabit_empty.a lib/librabit_mock.a lib/librabit_base.a  *~ src/*~ include/*~ include/*/*~ wrapper/*~
g++-4.9 -c -Wall -O3 -msse2  -Wno-unknown-pragmas -fPIC -DDISABLE_OPENMP  -o updater.o src/tree/updater.cpp
g++-4.9 -c -Wall -O3 -msse2  -Wno-unknown-pragmas -fPIC -DDISABLE_OPENMP  -o gbm.o src/gbm/gbm.cpp
g++-4.9 -c -Wall -O3 -msse2  -Wno-unknown-pragmas -fPIC -DDISABLE_OPENMP  -o io.o src/io/io.cpp
g++-4.9 -c -Wall -O3 -msse2  -Wno-unknown-pragmas -fPIC -DDISABLE_OPENMP  -o main.o src/xgboost_main.cpp
cd subtree/rabit;make lib/librabit.a; cd ../..
g++-4.9 -c -O3 -msse2 -fPIC -Wall -Wextra -Wno-unused-parameter -Wno-unknown-pragmas -pedantic   -o allreduce_base.o src/allreduce_base.cc
src/allreduce_base.cc: In function 'size_t rabit::engine::ParseUnit(const char*, const char*)':
src/allreduce_base.cc:138:46: warning: format '%lu' expects argument of type 'long unsigned int*', but argument 3 has type 'uint64_t* {aka long long unsigned int*}' [-Wformat=]
   int n = sscanf(val, "%lu%c", &amount, &unit);
                                              ^
src/allreduce_base.cc:138:46: warning: format '%lu' expects argument of type 'long unsigned int*', but argument 3 has type 'uint64_t* {aka long long unsigned int*}' [-Wformat=]
g++-4.9 -c -O3 -msse2 -fPIC -Wall -Wextra -Wno-unused-parameter -Wno-unknown-pragmas -pedantic   -o allreduce_robust.o src/allreduce_robust.cc
g++-4.9 -c -O3 -msse2 -fPIC -Wall -Wextra -Wno-unused-parameter -Wno-unknown-pragmas -pedantic   -o engine.o src/engine.cc
ar cr lib/librabit.a allreduce_base.o allreduce_robust.o engine.o
g++-4.9 -c -Wall -O3 -msse2  -Wno-unknown-pragmas -fPIC -DDISABLE_OPENMP  -o dmlc_simple.o src/io/dmlc_simple.cpp
g++-4.9 -Wall -O3 -msse2  -Wno-unknown-pragmas -fPIC -DDISABLE_OPENMP  -o xgboost updater.o gbm.o io.o main.o subtree/rabit/lib/librabit.a dmlc_simple.o -pthread -lm  
Undefined symbols for architecture x86_64:
  "__Unwind_Resume", referenced from:
      xgboost::tree::CreateUpdater(char const*) in updater.o
      xgboost::utils::Printf(char const*, ...) in updater.o
      xgboost::utils::Assert(bool, char const*, ...) in updater.o
      xgboost::utils::Check(bool, char const*, ...) in updater.o
      xgboost::utils::Error(char const*, ...) in updater.o
      rabit::utils::Assert(bool, char const*, ...) in updater.o
      rabit::TrackerPrintf(char const*, ...) in updater.o
      ...
  "start", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make: *** [xgboost] Error 1
Successfully build single-thread xgboost

**Comment by tqchen** [comment]
Seems it was due to missing of some linker library in MAC.  I did not encounter this before, but if you google ```__Unwind_Resume``` OSX, you can find possible solution to the problem

**Comment by nsecord** [comment]
I am having exactly the same problem as mentioned here and can't seem to find a solution.  I've loaded gcc/g++ 4.9 from the [HPC site](http://hpc.sourceforge.net)  and followed Phil Culliton's suggestions on Kaggle for building but to no avail.  

I've googled <code>__Unwind_Resume</code> OS X as you suggest but have not found anything useful that could help.  There is a suggestion somewhere to point the linker to g++ (already the case) and use -fexceptions  but that makes no difference.  

Any other suggestions?  I'd really like to give this a try.

**Comment by tqchen** [comment]
Seems this have things to do with GCC version. You may want to add -L linker path to the gcc/lib g++/lib. I do not have a MAC now so unfortunately I cannot test it out

**Comment by nsecord** [comment]
I've tried that but it doesn't help.  When I do <code>gcc -print-search-dirs</code> everything seems to be pointing to the right place so flags should not be necessary.  A little frustrating ...

**Comment by aykutfirat** [comment]
I used -mmacosx-version-min=10.9 in MakeFile:
export LDFLAGS= -pthread -lm  -mmacosx-version-min=10.9

and it worked.

**Comment by nsecord** [comment]
@aykutfirat Just saw your comment and tried with the -mmacosx-version-min=10.9 flag and it worked for me too.  Thanks very much!!

**Comment by srodriguex** [comment]
I couldn't resolve this issue in my system so I use the pip install xgboost and forget about it.

**Comment by henryhjyin** [comment]
I encounter the same problem on my mac,  which is "ld: symbol(s) not found for architecture x86_64'. And the command "make -stdlib=libstdc++" worked

**Comment by willettk** [comment]
Some of the legacy issues might be related to versioning. I had a previous version of XGBoost installed on my MBP (OS 10.11.6); after I installed the new version of gcc to support multi-threading, I got similar error messages for `undefined signals in architecture`. Neither the `-mmacosx-version-min=10.9` nor the `make -stdlib=libstdc++` solutions worked, but I deleted the repo and did a fresh install. It built without problems after that.

**Comment by kamushin** [comment]
After add `export LDFLAGS= -pthread -lm -mmacosx-version-min=10.9` to Makefile
Using `make clean` before make again. Hope it will be useful.

**Comment by pseudotensor** [comment]
Randomly got this as well.  It's doesn't happen every time, but it happened once so far.  Ubuntu 16.04 linux.

  import xgboost as xgb
  File "/home/jon/.pyenv/versions/3.6.1/lib/python3.6/site-packages/xgboost-0.6-py3.6.egg/xgboost/__init__.py", line 11, in <module>
    from .core import DMatrix, Booster
  File "/home/jon/.pyenv/versions/3.6.1/lib/python3.6/site-packages/xgboost-0.6-py3.6.egg/xgboost/core.py", line 115, in <module>
    _LIB = _load_lib()
  File "/home/jon/.pyenv/versions/3.6.1/lib/python3.6/site-packages/xgboost-0.6-py3.6.egg/xgboost/core.py", line 109, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])
  File "/home/jon/.pyenv/versions/3.6.1/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/home/jon/.pyenv/versions/3.6.1/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/jon/.pyenv/versions/3.6.1/lib/python3.6/site-packages/xgboost-0.6-py3.6.egg/xgboost/libxgboost.so: undefined symbol: _Unwind_Resume, version GCC_3.0
