### ISSUE TITLE
Build fails if there are spaces in path to make

### ISSUE THREAD

**Issue by limexp** [dmlc/xgboost#2618]
Build fails if there are spaces in path to make.
```$(MAKE)``` needed to be replaced with ```"$(MAKE)"``` in Makefile. 
https://github.com/dmlc/xgboost/blob/332b26df957efc58afb954cb01a6a39a9630e166/Makefile#L141
https://github.com/dmlc/xgboost/blob/332b26df957efc58afb954cb01a6a39a9630e166/Makefile#L144
https://github.com/dmlc/xgboost/blob/332b26df957efc58afb954cb01a6a39a9630e166/Makefile#L236
https://github.com/dmlc/xgboost/blob/332b26df957efc58afb954cb01a6a39a9630e166/Makefile#L237

## Environment info
Operating System: Windows x64
Compiler: mingw64

By default MinGW-w64 will be installed into the "Program Files" folder. Build fails because of spaces in path to make.

### Build log

```
cd dmlc-core; C:/Program Files/mingw-w64/x86_64-7.1.0-posix-seh-rt_v5-rev2/mingw64/bin/mingw32-make libdmlc.a config=C:/Users/dsfirst/xgboost/config.mk; cd C:/Users/dsfirst/xgboost
/usr/bin/sh: C:/Program: No such file or directory
cd rabit; C:/Program Files/mingw-w64/x86_64-7.1.0-posix-seh-rt_v5-rev2/mingw64/bin/mingw32-make lib/librabit_empty.a USE_SSE=; cd C:/Users/dsfirst/xgboost
/usr/bin/sh: C:/Program: No such file or directory
...
g++: error: dmlc-core/libdmlc.a: No such file or directory
g++: error: rabit/lib/librabit_empty.a: No such file or directory

```

**Comment by khotilov** [comment]
Thanks! #2619 is merged.
