### ISSUE TITLE
Early Stopping not exists in python

### ISSUE THREAD

**Issue by hycis** [dmlc/xgboost#262]
I realise train function does not have early_stopping_rounds as the parameter as explain in the wiki
train(..., evals=evals, early_stopping_rounds=10)
Do you have plans to update train with early_stopping_rounds?

**Comment by tqchen** [comment]
It is supported
https://github.com/dmlc/xgboost/blob/master/wrapper/xgboost.py#L544

You may need to re-install the most recent version from github

**Comment by hycis** [comment]
Oh i see, yap, i think i was using the old version. Thanks.
