### ISSUE TITLE
make xgboost easy to use

### ISSUE THREAD

**Issue by hy2014** [dmlc/xgboost#2622]
now we find it hard to use xgboost, we cannot find jar dependency on mvnrepository.com

hope to build cross platform jar by using maven, just like snappy.jar 
```
native/
    Linux/
        amd64/
        i386/
    Mac/
        i386/
        x86_64/
    Windows/
        amd64/
        x86/
```
so people can use it on any platform.

**Comment by superbobry** [comment]
Hy @hy2014, there're already two issues on that: #1807 and #2553.

**Comment by CodingCat** [comment]
duplicate
