### ISSUE TITLE
xgboost4j  run error!

### ISSUE THREAD

**Issue by TinghaoFeng** [dmlc/xgboost#2624]
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000358868982b, pid=21794, tid=140304142284544
#
# JRE version: Java(TM) SE Runtime Environment (7.0_55-b13) (build 1.7.0_55-b13)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (24.55-b03 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libc.so.6+0x8982b]  memcpy+0x15b
#
# Core dump written. Default location: /data/iflyrd/develop/thfeng/gbdt_engine/core or core.21794
#
# An error report file with more information is saved as:
# /data/iflyrd/develop/thfeng/gbdt_engine/hs_err_pid21794.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.sun.com/bugreport/crash.jsp
#

libxgboost.so maybe wrong

**Comment by superbobry** [comment]
Hi, could you please ad a bit of Markdown to your issue, so it is easier to read?

On a related note: we are seeing segfaults as well, but I have not yet figured out the cause.

**Comment by CodingCat** [comment]
closed, no enough info
