### ISSUE TITLE
Windows7 package installation issue

### ISSUE THREAD

**Issue by fengfengyuyu** [dmlc/xgboost#263]
I've installed RTools at `C:\Rtools`
and appended `C:\Rtools\bin` to system PATH
but still get the following error when I try to install this package:

>devtools::install_github('dmlc/xgboost',subdir='R-package')
>Downloading github repo dmlc/xgboost@master
>Installing xgboost
>"C:/PROGRA~1/R/R-31~1.3/bin/x64/R" --vanilla CMD INSTALL  \
>  "C:/Users/Administrator/AppData/Local/Temp/RtmpyUX5JZ/devtools3e8837c516d7/dmlc-xgboost->94fac10/R-package"  \
>  --library="C:/Program Files/R/R-3.1.3/library" --install-tests 

>* installing *source* package 'xgboost' ...
>** libs

>*** arch - i386
>警告: 运行命令'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-31~1.3/etc/i386/Makeconf" -f >"C:/PROGRA~1/R/R-31~1.3/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' >SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="xgboost.dll" '的状态是127
>ERROR: compilation failed for package 'xgboost'
>* removing 'C:/Program Files/R/R-3.1.3/library/xgboost'
>Error: Command failed (1)

What am I doing wrong here?

**Comment by tqchen** [comment]
It might still have something to do with RTools's path, check if you can type ```make``` in the command line.

Another way for you to try the installation was to clone the repo and type 
```
R CMD INSTALL R-packacge
```

**Comment by fengfengyuyu** [comment]
Thanks, by using a older version of RTools solves my problem.
