### ISSUE TITLE
OS X compilation instructions out of date, use homebrew gcc compiled without multilib flag

### ISSUE THREAD

**Issue by capers** [dmlc/xgboost#2631]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System: OS X 10.12

Compiler: gcc 7.2.0 (Homebrew)

Package used (python/R/jvm/C++): Python

`xgboost` version used: 0.60

## Steps to reproduce

1. Clone xgboost repo as directed in Installation instructions
2. Follow Building on OS X directions with OpenMP (brew install gcc --without-multilib)
3. Compilation will fail due to the new gcc formula removing this option. See here for more info

https://github.com/Homebrew/homebrew-core/commit/3479e6239d3cd6b181229acb026d8424a035d045#diff-baf58e557d0debf0bd219be97ec02ab8

## What have you tried?

1. Setting environmental variables for CC and CXX to use compilers installed from brew install gcc (7.2.0) allows the package to build correctly.

**Comment by gabsens** [comment]
Which CC and CXX values did you use ?

**Comment by qubz** [comment]
> Which CC and CXX values did you use ?
+1

**Comment by gabsens** [comment]
I suggest the people that maintain Xgboost have a look at this https://github.com/Homebrew/homebrew-core/pull/16751

`--without-multilib` is not supported anymore because it is reportedly useless.

**Comment by capers** [comment]
@gabsens I set CC and CXX to the homebrew installed versions of gcc 7.2.0 in /usr/local/bin

**Comment by damienrj** [comment]
Have only gotten the install to work using the methods from the following [thread](https://github.com/dmlc/xgboost/issues/1501).
```
brew install gcc@5
pip install xgboost
```
