### ISSUE TITLE
Fix bug of installation in win64 (with anaconda) problem

### ISSUE THREAD

**Issue by muyuan11** [dmlc/xgboost#2634]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System:
win7 64
Compiler:

Package used (python/R/jvm/C++):

`xgboost` version used:
0.6
If installing from source, please provide 

## What have you tried?

1. in win 64 , git and compile is ok
2 copy dll to  xgboost\python-package\build\lib\xgboost
3. at last step (in anaconda prompt): python setup.py install , always found ' xgboost.dll  not  found ' error msg and stop install

I checked  setup.py , then found it include libpath.py ( to find  dll file)
and check  libpath.py , found error in line 36 ( in libpath.py)

        dll_path = [os.path.join(p, 'xgboost.dll') for p in dll_path]

yes,  the   'xgboost.dll' is error , it should be 'libxgboost.dll'
so ,
fix line 36 to :    
`dll_path = [os.path.join(p, 'libxgboost.dll') for p in dll_path] `
and all thing done. then   python setup.py install ,everythin is ok. sample code is passed .

so  please fix this bug in  xgboost v0.6 for win64  in python package

**Comment by jonrtaylor** [comment]
solution above fixed my install problem. edit line 36 and problem resolves.

**Comment by khotilov** [comment]
The build was changed to produce xgboost.dll on windows instead of libxgboost.dll in June/July: #2461 #2539 
So, it would be interesting to understand why do you still have libxgboost.dll produced. Are you using the recent code?
