### ISSUE TITLE
Hi , will there be drop in prediction quality between standalone vs spark distributed version?

### ISSUE THREAD

**Issue by sgatamex** [dmlc/xgboost#2635]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System:

Compiler:

Package used (python/R/jvm/C++):

`xgboost` version used:

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`)
2. Logs will be helpful (If logs are large, please upload as attachment).

If you are using jvm package, please 

1. add [jvm-packages] in the title to make it quickly be identified
2. the gcc version and distribution

If you are using python package, please provide

1. The python version and distribution
2. The command to install `xgboost` if you are not installing from source

If you are using R package, please provide

1. The R `sessionInfo()`
2. The command to install `xgboost` if you are not installing from source

## Steps to reproduce

1.
2.
3.

## What have you tried?

1.
2.
3.

**Comment by sgatamex** [comment]
@CodingCat  , I am running the xgboost-spark using below parameters
   spark.xgb.eta=0.03f
   spark.xgb.max_depth=8
   spark.xgb.objective=reg:linear
   spark.xgb.min_child_weight=5
   spark.xgb.subsample=0.8f
   spark.xgb.silent=1
   spark.xgb.reg_alpha=0.00182f
   spark.xgb.nthread=4
  spark.xgb.gamma=0.000f
  spark.xgb.num_rounds=700
 spark.xgb.num_workers=10
 spark.xgb.reg_lambda=1.515f
 spark.xgb.useExternalMemory=true

I am getting 4% error in standalone mode and around 23% in distributed version .

My data is in libsvm format with <label> index+1:value 

What could be the reason for this?

**Comment by pommedeterresautee** [comment]
The way standalone version and distributed one works are different.
Standalone uses an exact method to find the perfect split where disrtibuted version of XGBoost will use a sketch approx.
More info there: https://arxiv.org/abs/1603.02754

the difference in score is very high and seems related to something else.

**Comment by sgatamex** [comment]
@pommedeterresautee  what could be the possible reason , below is my code 
package ml.dmlc.xgboost4j.scala.example.spark

/**
  * Created by sgupt288 on 8/23/17.
  */

import scala.collection.mutable.HashMap
import ml.dmlc.xgboost4j.scala.{Booster, DMatrix}
import ml.dmlc.xgboost4j.scala.spark.{DataUtils, XGBoost}
import org.apache.spark.{SparkConf, SparkContext}
import org.apache.spark.mllib.util.MLUtils
import org.apache.spark.ml.linalg.{DenseVector => MLDenseVector}
import org.apache.spark.ml.feature.{VectorAssembler, LabeledPoint => MLLabeledPoint}
import org.apache.spark.sql.SparkSession
import org.apache.spark.sql.types.{FloatType, StringType, StructField, StructType}
object SparkLibSVM {
  def main(args: Array[String]): Unit = {
    val sparkConf = new SparkConf().setAppName("XGBoost-spark-example")
      .set("spark.serializer", "org.apache.spark.serializer.KryoSerializer")
    sparkConf.registerKryoClasses(Array(classOf[Booster]))
    implicit val sc = new SparkContext(sparkConf)
    val sparkSession = SparkSession.builder().config(sparkConf).getOrCreate()
    val propFile=sparkSession.sparkContext.textFile(args(0))
    var invMap = new HashMap[String,String]()

    for(x<-propFile.collect())
    {
      val keyValues = x.split("=")
      invMap+=keyValues(0) -> keyValues(1)

    }

    val inputTrainPath = invMap.get("spark.xgb.train_path").get.toString
    val inputTestPath = invMap.get("spark.xgb.test_path").get.toString
    val outputModelPath = invMap.get("spark.xgb.output_model_path").get.toString
    val nWorkers =invMap.get("spark.xgb.num_workers").get.toString.toInt
    // number of iterations
    val numRound = invMap.get("spark.xgb.num_rounds").get.toString.toInt

    val num_cols = invMap.get("spark.xgb.num_cols").get.toString.split(",")
    val all_cols = invMap.get("spark.xgb.all_cols").get.toString.split(",")


    val fields = all_cols.map(fieldName =>
      if (num_cols.contains(fieldName.toLowerCase))
        {
          StructField(fieldName, FloatType, nullable = true)
        }
      else
        {
          StructField(fieldName, StringType, nullable = true)
        }

    )

    var cs = new StructType(fields)

    val df = sparkSession.read.schema(cs).csv(inputTrainPath)
    val dftemp=df.na.fill(0.0)

    val assembler = new VectorAssembler()
      .setInputCols(num_cols.take(num_cols.size-1))
      .setOutputCol("features")

    val train_DF = assembler.transform(dftemp)
    val train = train_DF.withColumn("label", dftemp("target_amount").cast("double")).select("label", "features")

    val paramMap = List(
      "eta" -> invMap.get("spark.xgb.eta").get.toString.toFloat,
      "max_depth" -> invMap.get("spark.xgb.max_depth").get.toString.toInt,
      "objective" -> invMap.get("spark.xgb.objective").get.toString,
      "min_child_weight"->invMap.get("spark.xgb.min_child_weight").get.toString.toInt,
      "subsample"->invMap.get("spark.xgb.subsample").get.toString.toFloat,
      "silent"->invMap.get("spark.xgb.silent").get.toString.toInt,
      "reg_alpha"->invMap.get("spark.xgb.reg_alpha").get.toString.toFloat,
      "reg_lambda"->invMap.get("spark.xgb.reg_lambda").get.toString.toFloat,
      "nthread" ->invMap.get("spark.xgb.nthread").get.toString.toInt,
      "gamma"->invMap.get("spark.xgb.gamma").get.toString.toFloat).toMap

    val xgboostModel = XGBoost.trainWithDataFrame(
      train, paramMap, numRound, nWorkers = nWorkers,
      useExternalMemory = invMap.get("spark.xgb.useExternalMemory").get.toString.toBoolean)

    // save model to HDFS path
    xgboostModel.booster.saveModel(outputModelPath)
  }

}

**Comment by pommedeterresautee** [comment]
https://github.com/dmlc/xgboost/issues/2643
