### ISSUE TITLE
get the best tree

### ISSUE THREAD

**Issue by yzliao** [dmlc/xgboost#264]
With a given `early_stopping_rounds`, the training process stops when the testing/validation error does not reduce. However, the returned model is not the best model (the one has the minimum validation error). Is there a way to get the model with the minimum validation error?

**Comment by tqchen** [comment]
once you know the best round, you can do prediction with the first n trees, see

https://github.com/dmlc/xgboost/blob/master/demo/guide-python/predict_first_ntree.py

**Comment by yzliao** [comment]
This is good to know. I did not realize that before. So can I add a new variable for ``train()`` that allows us to get the best iteration?

**Comment by tqchen** [comment]
You can get the best iteration from bst.best_iteration  https://github.com/dmlc/xgboost/blob/master/wrapper/xgboost.py#L661

maybe we need a bit more document on early stop to make it more visible

**Comment by yzliao** [comment]
Awesome!  Thank you @tqchen
