### ISSUE TITLE
[jvm-packages] Model Accuracy Between Standalone and Distributed version is very high

### ISSUE THREAD

**Issue by sgatamex** [dmlc/xgboost#2643]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System: Linux

Compiler: 

Package used (python/R/jvm/C++):jvm

`xgboost` version used:0.6

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`)
2. Logs will be helpful (If logs are large, please upload as attachment).

If you are using jvm package, please 

1. add [jvm-packages] in the title to make it quickly be identified
2. the gcc version and distribution

If you are using python package, please provide

1. The python version and distribution
2. The command to install `xgboost` if you are not installing from source

If you are using R package, please provide

1. The R `sessionInfo()`
2. The command to install `xgboost` if you are not installing from source

Hi ,

I am trying the standalone version of xgboost and  ratio of Mean Absolute error / actual error is 4.71  %  for our data set.   The spark - version has this ratio around 23%.

I am using following code to train the model

`val trainDF = sparkSession.sqlContext.read.format("libsvm")
      .option("inferSchema", "true")
      .load(inputTrainPath)
    //val testDF = sparkSession.sqlContext.read.format("libsvm").load(inputTestPath)
    // start training

    val paramMap = List(
      "eta" -> invMap.get("spark.xgb.eta").get.toString.toFloat,
      "max_depth" -> invMap.get("spark.xgb.max_depth").get.toString.toInt,
      "objective" -> invMap.get("spark.xgb.objective").get.toString,
      "min_child_weight"->invMap.get("spark.xgb.min_child_weight").get.toString.toInt,
      "subsample"->invMap.get("spark.xgb.subsample").get.toString.toFloat,
      "silent"->invMap.get("spark.xgb.silent").get.toString.toInt,
      "reg_alpha"->invMap.get("spark.xgb.reg_alpha").get.toString.toFloat,
      "reg_lambda"->invMap.get("spark.xgb.reg_lambda").get.toString.toFloat,
      "nthread" ->invMap.get("spark.xgb.nthread").get.toString.toInt,
      "gamma"->invMap.get("spark.xgb.gamma").get.toString.toFloat,
      "colsample_bytree"->invMap.get("spark.xgb.colsample_bytree").get.toString.toFloat).toMap

    val xgboostModel = XGBoost.trainWithDataFrame(
      trainDF, paramMap, numRound, nWorkers = nWorkers,
      useExternalMemory = invMap.get("spark.xgb.useExternalMemory").get.toString.toBoolean)

    // save model to HDFS path
    xgboostModel.booster.saveModel(outputModelPath)`

the various parameters are as follows

   spark.xgb.eta=0.03f
  2 spark.xgb.max_depth=8
  3 spark.xgb.objective=reg:linear
  4 spark.xgb.min_child_weight=5
  5 spark.xgb.subsample=0.8f
  6 spark.xgb.silent=1
  7 spark.xgb.reg_alpha=0.00182f
  8 spark.xgb.nthread=4
  9 spark.xgb.gamma=0.000f
  
 spark.xgb.train_path=train path
 12 spark.xgb.num_rounds=700
 13 spark.xgb.num_workers=200
 14 spark.xgb.output_model_path=output path
 15 spark.xgb.reg_lambda=1.515f
 16 spark.xgb.useExternalMemory=false
 17 spark.xgb.colsample_bytree=0.8f

libSVM format is 

21401.85 1:163640.0 2:1.0 3:1.0 4:75.0 5:1.0 6:1.0 7:76898.0 8:91898.0 9:724200.0 10:33869.0 11:33869.0 12:135000.0 13:83.0 14:1.0 15:0.0 16:0.0 17:0.0 18:0.0 19:0.0 20:0.0 21:0.0 22:0.0 23:134.0 24:136.0 25:1.0 26:1.0 27:0.0 28:0.0 29:7.0 30:0.0 31:0.0 32:0.0 33:0.0 34:0.0 35:0.0 36:0.0 37:0.0 38:0.0 39:0.0 40:952.73 41:0.0 42:0.0 43:0.0 44:0.0 45:0.0 46:139.0 47:0.0 48:0.0 49:0.0 50:0.0 51:0.0 52:1881.0 53:1716.0 54:2173.0 55:1244.0 56:2296.0 57:2021.0 58:3827.0 59:602.0 60:596.0 61:735.0 62:1739.0 63:849.0 64:-146.0 65:-43.0 66:96.0 67:1.0 68:1.0 69:1.0 70:1.0 71:1.0 72:1.0 73:1.0 74:1.0 75:1.0 76:1.0 77:1.0 78:1.0 79:1.0 80:1798.0 81:1944.0 82:1708.0 83:1770.0 84:2158.0 85:2924.0 86:2214.0 87:599.0 88:665.0 89:1237.0 90:1294.0 91:1923.0 92:1711.0 93:1904.0 94:1853.0 95:2714.0 96:2150.0 97:1675.0 98:644.0 99:1023.0 100:1107.0 101:1888.0 102:2212.0 103:2027.0 104:1764.0 105:1679.0 106:1586.0 107:1391.0 108:1817.0 109:1639.0 110:-199.0 111:-2.0 112:0.0 113:132.0 114:-116.0 115:-18.0 116:0.0 117:43.0 118:-28.0 119:-1.0 120:1.0 121:31.0 122:5.0 123:3.0 124:21.0 125:21.0 126:17.0 127:23.0 128:35.0 129:27.0 130:12.0 131:8.0 132:7.0 133:13.0 134:13.0 135:10.0 136:1170.0 137:1203.0 138:913.0 139:853.0 140:1366.0 141:1081.0 142:2928.0 143:194.0 144:256.0 145:431.0 146:874.0 147:284.0 148:8522.0 149:6322.0 150:3021.0 151:0.622 152:0.701 153:0.4202 154:0.6857 155:0.5949 156:0.5349 157:0.7651 158:0.3223 159:0.4295 160:0.5864 161:0.5026 162:0.3345 163:0.5237 164:0.5581 165:0.4333 166:0.0 167:0.0 168:0.0 169:0.0 170:0.0 171:0.0 172:0.0 173:194.0 174:0.0 175:0.0 176:874.0 177:0.0 178:0.0 179:0.0 180:0.0 181:0.0 182:0.0 183:0.0 184:0.0 185:1.0 186:0.0 187:0.0 188:1.0 189:0.0 190:136.0 191:111.0 192:69.0 193:94.0 194:144.0 195:99.0 196:81.0 197:123.0 198:0.0 199:88.0 200:71.0 201:156.0 202:3.0 203:2.0 204:2.0 205:2.0 206:2.0 207:2.0 208:2.0 209:2.0 210:0.0 211:2.0 212:1.0 213:3.0 214:24.0 215:0.0 216:91.0 217:43.0 218:144.0 219:56.0 220:0.0 221:0.0 222:0.0 223:0.0 224:0.0 225:0.0 226:1.0 227:0.0 228:3.0 229:1.0 230:3.0 231:1.0 232:0.0 233:0.0 234:0.0 235:0.0 236:0.0 237:0.0 238:0.0 239:0.0 240:0.0 241:0.0 242:0.0 243:0.0 244:0.0 245:0.0 246:0.0 247:0.0 248:0.0 249:0.0 250:0.0 251:0.0 252:0.0 253:0.0 254:0.0 255:0.0 256:0.0 257:0.0 258:0.0 259:0.0 260:0.0 261:0.0 262:0.0 263:0.0 264:913.0 265:0.0 266:0.0 267:198.0 268:80.0 269:0.0 270:81.0 271:0.0 272:0.0 273:0.0 274:0.0 275:0.0 276:1.0 277:0.0 278:0.0 279:2.0 280:1.0 281:0.0 282:1.0 283:0.0 284:0.0 285:0.0 286:621.0 287:672.0 288:187.0 289:439.0 290:673.0 291:548.0 292:119.0 293:105.0 294:51.0 295:153.0 296:136.0 297:78.0 298:6.0 299:9.0 300:2.0 301:9.0 302:14.0 303:8.0 304:1.0 305:3.0 306:1.0 307:6.0 308:5.0 309:1.0 310:0.0 311:0.0 312:0.0 313:0.0 314:0.0 315:0.0 316:0.0 317:0.0 318:0.0 319:0.0 320:0.0 321:0.0 322:1.0 323:1.0 324:1.0 325:1.0 326:1.0 327:1.0 328:1.0 329:1.0 330:1.0 331:1.0 332:1.0 333:1.0 334:0.0 335:1012500.0 336:260000.0 337:0.0 338:0.0 339:0.0 340:250000.0 341:0.0 342:11.0 343:8.0 344:0.0 345:0.0 346:0.0 347:2.0 348:0.0 349:0.0071 350:0.0073 351:0.0 352:0.0 353:0.0 354:0.01
14969.68 1:356.0 2:0.0 3:1.0 4:441.0 5:1.0 6:1.0 7:19445.0 8:19445.0 9:59779.0 10:5854.0 11:5854.0 12:7318.0 13:0.0 14:0.0 15:0.0 16:0.0 17:0.0 18:0.0 19:0.0 20:0.0 21:0.0 22:0.0 23:83.0 24:83.0 25:1.0 26:0.0 27:0.0 28:0.0 29:83.0 30:0.0 31:0.0 32:0.0 33:0.0 34:0.0 35:0.0 36:0.0 37:0.0 38:0.0 39:0.0 40:1205.5 41:0.0 42:0.0 43:0.0 44:0.0 45:0.0 46:139.0 47:1.0 48:0.0 49:0.0 50:0.0 51:0.0 52:718.0 53:1396.0 54:805.0 55:1183.0 56:1401.0 57:927.0 58:1260.0 59:838.0 60:708.0 61:3940.0 62:1124.0 63:795.0 64:-43.0 65:-41.0 66:-58.0 67:1.0 68:1.0 69:1.0 70:1.0 71:1.0 72:1.0 73:1.0 74:1.0 75:1.0 76:1.0 77:1.0 78:1.0 79:1.0 80:1057.0 81:1100.0 82:994.0 83:1292.0 84:1164.0 85:1093.0 86:1049.0 87:773.0 88:2324.0 89:2532.0 90:959.0 91:973.0 92:1128.0 93:1129.0 94:1170.0 95:1196.0 96:1008.0 97:935.0 98:1828.0 99:1924.0 100:1953.0 101:1071.0 102:1162.0 103:1069.0 104:1052.0 105:1512.0 106:1466.0 107:1444.0 108:1026.0 109:1257.0 110:-199.0 111:-2.0 112:0.0 113:132.0 114:-116.0 115:-18.0 116:0.0 117:43.0 118:-28.0 119:-1.0 120:1.0 121:31.0 122:2.0 123:3.0 124:12.0 125:19.0 126:10.0 127:27.0 128:20.0 129:12.0 130:18.0 131:15.0 132:10.0 133:22.0 134:29.0 135:16.0 136:434.0 137:864.0 138:430.0 139:627.0 140:830.0 141:439.0 142:572.0 143:449.0 144:449.0 145:2336.0 146:444.0 147:431.0 148:7338.0 149:3185.0 150:1479.0 151:0.6045 152:0.6189 153:0.5342 154:0.53 155:0.5924 156:0.4736 157:0.454 158:0.5358 159:0.6342 160:0.5929 161:0.395 162:0.5421 163:0.5067 164:0.4956 165:0.4865 166:0.0 167:0.0 168:0.0 169:0.0 170:0.0 171:0.0 172:0.0 173:0.0 174:0.0 175:0.0 176:0.0 177:0.0 178:0.0 179:0.0 180:0.0 181:0.0 182:0.0 183:0.0 184:0.0 185:0.0 186:0.0 187:0.0 188:0.0 189:0.0 190:12.0 191:63.0 192:21.0 193:195.0 194:72.0 195:30.0 196:8.0 197:0.0 198:19.0 199:64.0 200:88.0 201:10.0 202:1.0 203:4.0 204:2.0 205:13.0 206:6.0 207:2.0 208:1.0 209:0.0 210:4.0 211:7.0 212:9.0 213:1.0 214:7.0 215:6.0 216:0.0 217:37.0 218:0.0 219:8.0 220:0.0 221:0.0 222:0.0 223:29.0 224:0.0 225:0.0 226:1.0 227:1.0 228:0.0 229:4.0 230:0.0 231:1.0 232:0.0 233:0.0 234:0.0 235:2.0 236:0.0 237:0.0 238:0.0 239:0.0 240:0.0 241:0.0 242:0.0 243:0.0 244:0.0 245:0.0 246:0.0 247:0.0 248:0.0 249:0.0 250:0.0 251:0.0 252:0.0 253:0.0 254:0.0 255:0.0 256:0.0 257:0.0 258:0.0 259:0.0 260:0.0 261:0.0 262:0.0 263:0.0 264:0.0 265:0.0 266:0.0 267:0.0 268:0.0 269:0.0 270:0.0 271:0.0 272:0.0 273:0.0 274:0.0 275:0.0 276:0.0 277:0.0 278:0.0 279:0.0 280:0.0 281:0.0 282:0.0 283:0.0 284:0.0 285:0.0 286:166.0 287:29.0 288:165.0 289:0.0 290:251.0 291:121.0 292:118.0 293:0.0 294:193.0 295:107.0 296:100.0 297:122.0 298:3.0 299:1.0 300:2.0 301:0.0 302:4.0 303:2.0 304:3.0 305:0.0 306:2.0 307:1.0 308:1.0 309:1.0 310:0.0 311:0.0 312:0.0 313:0.0 314:0.0 315:0.0 316:0.0 317:0.0 318:0.0 319:0.0 320:0.0 321:0.0 322:0.0 323:0.0 324:0.0 325:0.0 326:0.0 327:0.0 328:0.0 329:0.0 330:0.0 331:0.0 332:0.0 333:0.0 334:7145.0 335:9580.0 336:13230.0 337:5808.0 338:26983.0 339:10665.0 340:10651.0 341:5.0 342:6.0 343:6.0 344:4.0 345:19.0 346:11.0 347:10.0 348:0.0115 349:0.0115 350:0.0115 351:0.0115 352:0.0115 353:0.0115 354:0.0115
48.03 1:489775.0 2:1.0 3:0.0 4:121.0 5:0.0 6:0.0 7:31.0 8:31.0 9:70000.0 10:32.0 11:32.0 12:0.0 13:35.0 14:1.0 15:0.0 16:0.0 17:0.0 18:0.0 19:0.0 20:0.0 21:0.0 22:0.0 23:244.0 24:268.0 25:1.0 26:1.0 27:0.0 28:0.0 29:66.0 30:0.0 31:0.0 32:0.0 33:0.0 34:0.0 35:0.0 36:0.0 37:0.0 38:0.0 39:0.0 40:0.0 41:0.0 42:0.0 43:0.0 44:0.0 45:0.0 46:1.0 47:359.0 48:0.0 49:0.0 50:0.0 51:0.0 52:0.0 53:0.0 54:0.0 55:0.0 56:0.0 57:0.0 58:0.0 59:0.0 60:0.0 61:0.0 62:0.0 63:48.0 64:0.0 65:0.0 66:-1.0 67:0.0 68:0.0 69:0.0 70:0.0 71:0.0 72:0.0 73:0.0 74:0.0 75:0.0 76:0.0 77:0.0 78:1.0 79:0.0 80:0.0 81:0.0 82:0.0 83:0.0 84:0.0 85:0.0 86:0.0 87:0.0 88:0.0 89:0.0 90:24.0 91:0.0 92:0.0 93:0.0 94:0.0 95:0.0 96:0.0 97:0.0 98:0.0 99:0.0 100:16.0 101:0.0 102:0.0 103:0.0 104:0.0 105:0.0 106:0.0 107:8.0 108:0.0 109:4.0 110:-199.0 111:-2.0 112:0.0 113:132.0 114:-116.0 115:-18.0 116:0.0 117:43.0 118:-28.0 119:-1.0 120:1.0 121:31.0 122:0.0 123:11.0 124:0.0 125:0.0 126:0.0 127:0.0 128:0.0 129:0.0 130:0.0 131:0.0 132:0.0 133:0.0 134:0.0 135:1.0 136:0.0 137:0.0 138:0.0 139:0.0 140:0.0 141:0.0 142:0.0 143:0.0 144:0.0 145:0.0 146:0.0 147:47.0 148:47.0 149:0.0 150:0.0 151:0.0 152:0.0 153:0.0 154:0.0 155:0.0 156:0.0 157:0.0 158:0.0 159:0.0 160:0.0 161:0.0 162:0.9792 163:0.0 164:0.0 165:0.9792 166:0.0 167:0.0 168:0.0 169:0.0 170:0.0 171:0.0 172:0.0 173:0.0 174:0.0 175:0.0 176:0.0 177:0.0 178:0.0 179:0.0 180:0.0 181:0.0 182:0.0 183:0.0 184:0.0 185:0.0 186:0.0 187:0.0 188:0.0 189:0.0 190:0.0 191:0.0 192:0.0 193:0.0 194:0.0 195:0.0 196:0.0 197:0.0 198:0.0 199:0.0 200:0.0 201:0.0 202:0.0 203:0.0 204:0.0 205:0.0 206:0.0 207:0.0 208:0.0 209:0.0 210:0.0 211:0.0 212:0.0 213:0.0 214:0.0 215:0.0 216:0.0 217:0.0 218:0.0 219:0.0 220:0.0 221:0.0 222:0.0 223:0.0 224:0.0 225:0.0 226:0.0 227:0.0 228:0.0 229:0.0 230:0.0 231:0.0 232:0.0 233:0.0 234:0.0 235:0.0 236:0.0 237:0.0 238:0.0 239:0.0 240:0.0 241:0.0 242:0.0 243:0.0 244:0.0 245:0.0 246:0.0 247:0.0 248:0.0 249:0.0 250:0.0 251:0.0 252:0.0 253:0.0 254:0.0 255:0.0 256:0.0 257:0.0 258:0.0 259:0.0 260:0.0 261:0.0 262:0.0 263:0.0 264:0.0 265:0.0 266:0.0 267:0.0 268:0.0 269:0.0 270:0.0 271:0.0 272:0.0 273:0.0 274:0.0 275:0.0 276:0.0 277:0.0 278:0.0 279:0.0 280:0.0 281:0.0 282:0.0 283:0.0 284:0.0 285:0.0 286:0.0 287:0.0 288:0.0 289:0.0 290:0.0 291:0.0 292:0.0 293:0.0 294:0.0 295:0.0 296:0.0 297:0.0 298:0.0 299:0.0 300:0.0 301:0.0 302:0.0 303:0.0 304:0.0 305:0.0 306:0.0 307:0.0 308:0.0 309:0.0 310:0.0 311:0.0 312:0.0 313:0.0 314:0.0 315:0.0 316:0.0 317:0.0 318:0.0 319:0.0 320:0.0 321:0.0 322:0.0 323:0.0 324:0.0 325:0.0 326:0.0 327:0.0 328:0.0 329:0.0 330:0.0 331:0.0 332:0.0 333:0.0 334:0.0 335:0.0 336:0.0 337:0.0 338:0.0 339:0.0 340:0.0 341:0.0 342:0.0 343:0.0 344:0.0 345:0.0 346:0.0 347:0.0 348:0.0 349:0.0 350:0.0 351:0.0 352:0.0 353:0.0 354:0.0

After model is trained , i load the model in a Java Map Reduce job and predict individual row . Is this a problem ?

What shd i do ? please help.

**Comment by CodingCat** [comment]
did you convert between 0-based and 1-based in your libsvm formatted data?


https://github.com/dmlc/xgboost/tree/master/jvm-packages search "NOTE on LIBSVM Format"

**Comment by sgatamex** [comment]
@CodingCat : yes  the data is  in 1 based during distributed training as shown below just a sample
14969.68 1:356.0 2:0.0 3:1.0 4:441.0 5:1.0 6:1.0 7:19445.0 8:19445.0 9:59779.0 10:5854.0 11:5854.0 12:7318.0 13:0.0 14:0.0 15:0.0 16:0.0 17:0.0 18:0.0 19:0.0 20:0.0 21:0.0 22:0.0 23:83.0 24:83.0

after training , we save the model on hdfs and then load the model in java map reduce job.

in This job, we create a dmatrix and call booster.predict method , is this the correct way of predicting? We are getting same result  using this method  for a model which is trained in satndalone version but when we use a distributed model the accuracy is bad as compare to standalone version

**Comment by CodingCat** [comment]
you have to convert your data to 0-based in prediction

**Comment by sgatamex** [comment]
@CodingCat  , even after converting test data to 0 based libSVM data , i am still getting 22% in distributed

**Comment by tqchen** [comment]
This is due to the fact that in the distributed job, DMatrix loading by default only load shard of the data. So you will need to either(use xgboost-spark's method of data ingestion), or give hdfs address of entire DMatrix.

**Comment by sgatamex** [comment]
@tqchen , it means prediction actually depends upon the complete data set rows ,, its not like that each row can be individually predicted using the trained model.

**Comment by tqchen** [comment]
It is mainly limitation of the DMatrix loading mechanism, when launched in the spark env. It thinks it is in distributed env, so the load function takes a "global view" instead of "local view"
 If you directly use xgboost4j in mapreduce without launching rabit tracker, there is no such problem

**Comment by sgatamex** [comment]
@tqchen  "If you directly use xgboost4j in mapreduce without launching rabit tracker, there is no such problem"  this is exactly what i am doing so ideally problem lies somewhere else then.

**Comment by sgatamex** [comment]
@tqchen  How much difference is normally observed between distributed vs standalone version? What else should i try to bring down the error % ?

**Comment by sgatamex** [comment]
@tqchen , plz help as this is really confusing now.

**Comment by tqchen** [comment]
hmm, if you are not using rabit, each one should be loading the entire data provided. As long as you remember to close and flush the file

**Comment by sgatamex** [comment]
@tqchen , so prediction will always use the complete test data not the chunk of data available to the mapper. Do i need to consider prediction in standalone version?

Is there something wrong in the train code which i have written?

**Comment by tqchen** [comment]
If you want to do training, you cannot simply distributed the data because the trainer need to synchronize, and you need to use xgboost spark for that

**Comment by sgatamex** [comment]
@tqchen  correct , i am doing trianing using  xgboost spark  only but prediction is in mapreduce job.

**Comment by tqchen** [comment]
There can be difference between the distributed version with different workers as distributed verison uses an approximate algorithm, this is especially true when dataset is small.

**Comment by sgatamex** [comment]
@tqchen hmm i also thought so. If data set is small , increasing numWorkers may results in less accurate results. is this so?

Shd i expect variation in results if i keep changing the numWorkers? but in my view these variations shd not be very high as it is coming in my case cli distributed is giving 8% and Spark  version giving around 18%. 

i am stuck now as not able to further improve the code .

**Comment by sgatamex** [comment]
@CodingCat @tqchen  : Thank you so much for your advice but i have tried all the settings  and i am not able to get past the 17% error in xgboost-spark version and getting almost 9% in distributed CLI version .

What should i try now?

**Comment by sgatamex** [comment]
@tqchen : I resolved it by flooring and capping in the input data .. i don't k now why but removing outliers from the data , did the trick.

**Comment by hzliang** [comment]
@sgatamex how do you removing outliers from the data?
