### ISSUE TITLE
C++ API: Gain and Cover parameters

### ISSUE THREAD

**Issue by andrey-gelman** [dmlc/xgboost#2653]
To estimate importance of features we can look at gain and cover parameters in xgb.importance in R API, but we cannot find analogous functionality in C++ API.

How these parameters can be accessed from within C++ API?

**Comment by pommedeterresautee** [comment]
You will need to recompute these values from the text dump of a model.
You can find commands to make a text dump here: https://github.com/dmlc/xgboost/blob/master/demo/binary_classification/README.md
