### ISSUE TITLE
DumpModel stringstream precision problem

### ISSUE THREAD

**Issue by earthwu** [dmlc/xgboost#2659]
hello, in file src/tree/tree_model.cc line 150 std::stringstream fo(""); 
`  std::stringstream fo("");
  for (int i = 0; i < param.num_roots; ++i) {
    DumpRegTree(fo, *this, fmap, i, 0, false, with_stats, format);
  }
  return fo.str();`
use stringstream output the model text info，the stringstream default precision is 6,  when in  bst_float cond = tree[nid].split_cond();  cond is 100000.5 the output split_thresholds is 100000, thus when we decode the tree dump raw txt and use the tree info online predict the result will wrong. maybe you should reset the stringstream precision.   thanks! @pluskid @tqchen
英文可能有些中式英文，问题是这样的，在将模型dump成可视化文件时，在文件src/tree/tree_model.cc的150行中，使用了stringstream，但stringstream默认精度是6，因此当split_cond的值是7位时，后面的小数点部分会被省略掉，比如split_cond是100000.5时会输出100000，这样就会导致可视化文件和实际二进制文件不一致，当我们自己实现在线预测函数的时候，去解析可视化文件的内容就得到了错误的阈值，所以是不是这里应该把默认精度调到最大会更合适一些

**Comment by khotilov** [comment]
https://github.com/dmlc/xgboost/pull/1726#issuecomment-308935742 #2268 #1204  #1750 #2077 #2608
Please use github search before creating a new issue.
