### ISSUE TITLE
"exp(p+max_delta_step)" in poisson regression hessian: what is the purpose?

### ISSUE THREAD

**Issue by j-mark-hou** [dmlc/xgboost#2661]
https://github.com/dmlc/xgboost/blob/d581a3d0e7fbc8e73dbeb6f81fdc1e101606737e/src/objective/regression_obj.cc#L185

On line 185, the hessian of the poisson regression is adjusted essentially by uniformly multiplying it exp(max_delta_step), as the hessian of the poisson log likelihood is just exp(p). 

It seems like using exp(p+max_delta_step) instead of exp(p) would make it so that, instead of the update being sum(grad)/[sum(hess)+l2_reg], it would be sum(grad)/[sum(hess)*exp(max_delta_step)+l2_reg].  If there's an issue with the hessians being close to 0, it doesn't seem like multiplying it by 2 or whatever is going to solve that problem.  furthermore, the update gets capped further downstream at max_delta_step anyways, so overall I'm not sure I understand the purpose that doing this serves.

**Comment by futurecam** [comment]
are there anyone know this? I'm also confused about why add max_delta_step to second gradient in poisson regression....
