### ISSUE TITLE
can not release gpu memory after trained on ipython notebook

### ISSUE THREAD

**Issue by aguang1201** [dmlc/xgboost#2663]
## Environment info
Operating System:
ubuntu 16.04

Compiler:
cmake

Package used (python/R/jvm/C++):
python

`xgboost` version used:
xgboost0.6 with GPU(GTX 1080Ti)

If installing from source, please provide 
yes.
git clone --recursive [https://github.com/dmlc/xgboost.git](https://github.com/dmlc/xgboost.git)

If you are using jvm package, please 
no.

If you are using python package, please provide
python2.7
sudo python setup.py install

If you are using R package, please provide
no

Description:
When xgboost was training, GPU worked well.But when training finished, GPU memory was not released automatically. I had to release GPU memory with command: sudo kill -9 SID

**Comment by RAMitchell** [comment]
Can you show your python script.

Python is garbage collected so often doesn't delete the booster instance. See if manually deleting the booster instance in python helps.

**Comment by aguang1201** [comment]
sorry I'm make a mistake.please forget it.
