### ISSUE TITLE
when train xgboost model  with same data  in different  format (csr_matrix/numpy array) ,I get different model!

### ISSUE THREAD

**Issue by baibaiw5** [dmlc/xgboost#2673]
## Environment info
Operating System:Linux

Compiler:c++5.2

Package used (python):

`xgboost` version used: 0.6

## Steps to reproduce
when i train xgboost model with the same data, but in different format(csr_matrix/numpy array),I got different model. Why the model is different?
1:xgb.DMatrix(sparse.csr_matrix(X_test.values))
2:xgb.DMatrix(X_test.values)

besides,when the model is train with csr_matrix, When I predict the model with the same data if  different format (csr_matrix/numpy array), I got different result... Dose it mean that only predict on csr_matrix format where trained on csr_matrix format?
1:bst.predict(xgb.DMatrix(sparse.csr_matrix(X_test.values)))
2:bst.predict(xgb.DMatrix(X_test.values))

**Comment by pommedeterresautee** [comment]
Did you set the seed?

**Comment by baibaiw5** [comment]
@pommedeterresautee  
Yes ,I has set the same seed when I train the models
