### ISSUE TITLE
xgboost for prediction

### ISSUE THREAD

**Issue by hrdxwandg** [dmlc/xgboost#2675]
when i use xgboost4j for prediction，i find a question:
i use two ways to load test file.
1)DMatrix testMat = new DMatrix(fArray, nrow, ncol);
fArray is the feature value array 

2）DMatrix testMat = new DMatrix("data/xgboost/test.train");
the parameter is test file path and the file is libsvm format

after i do predcition operation,i find the prediction score is different.and the second way is the same with the way i use c++/shell interface like in demo package.

what's the difference between the two way of loading test file.especially how shoud i do in the firsrt way to get correct result? thank sincerely

**Comment by pommedeterresautee** [comment]
Have you checked that both testMat have the same properties? (by comparing rows for instance)

**Comment by hrdxwandg** [comment]
first thak you for your reply.

i checke the row properties, it is the same in both testMat.
what else properties should i check.

i get the code from following class for the two way of loading test file:
https://github.com/dmlc/xgboost/blob/master/jvm-packages/xgboost4j/src/test/java/ml/dmlc/xgboost4j/java/DMatrixTest.java

i want to use the first way in my project, because the test instance is produced from RAM not from disk file.

**Comment by laohumultimedia** [comment]
i face the same problem. I Use libsvm format to train, when distribution the feature is numpy array, but the prediction is totally wrong.
