### ISSUE TITLE
GPU Debian NCCL build error

### ISSUE THREAD

**Issue by wydwww** [dmlc/xgboost#2687]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System:
Debian 9.1
Compiler:
gcc (Debian 6.3.0-18) 6.3.0 20170516
CUDA Version 8.0.61
Package used (python/R/jvm/C++):
no
`xgboost` version used:
latest from source
If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`)
e6a9063344e429a3417adbfdfd9746664c9005a2
2. Logs will be helpful (If logs are large, please upload as attachment).
ywang@ip-192-168-2-200:~/xgboost/build$ make -j
[  3%] Building NVCC (Device) object nccl/CMakeFiles/nccl.dir/src/nccl_generated_reduce_scatter.cu.o
[  3%] Building NVCC (Device) object nccl/CMakeFiles/nccl.dir/src/nccl_generated_all_reduce.cu.o
[  4%] Building NVCC (Device) object nccl/CMakeFiles/nccl.dir/src/nccl_generated_broadcast.cu.o
[  6%] Building NVCC (Device) object nccl/CMakeFiles/nccl.dir/src/nccl_generated_reduce.cu.o
[  7%] Building NVCC (Device) object nccl/CMakeFiles/nccl.dir/src/nccl_generated_libwrap.cu.o
[  9%] Building NVCC (Device) object nccl/CMakeFiles/nccl.dir/src/nccl_generated_core.cu.o
[ 10%] Building NVCC (Device) object nccl/CMakeFiles/nccl.dir/src/nccl_generated_all_gather.cu.o
[ 25%] Built target dmlccore
[ 32%] Built target rabit
In file included from /usr/local/cuda/include/cuda_runtime.h:78:0,
                 from <command-line>:0:
/usr/local/cuda/include/host_config.h:119:2: error: #error -- unsupported GNU version! gcc versions later than 5 are not supported!
 #error -- unsupported GNU version! gcc versions later than 5 are not supported!
  ^~~~~
In file included from /usr/local/cuda/include/cuda_runtime.h:78:0,
                 from <command-line>:0:
/usr/local/cuda/include/host_config.h:119:2: error: #error -- unsupported GNU version! gcc versions later than 5 are not supported!
 #error -- unsupported GNU version! gcc versions later than 5 are not supported!
  ^~~~~
In file included from /usr/local/cuda/include/cuda_runtime.h:78:0,
                 from <command-line>:0:
/usr/local/cuda/include/host_config.h:119:2: error: #error -- unsupported GNU version! gcc versions later than 5 are not supported!
 #error -- unsupported GNU version! gcc versions later than 5 are not supported!
  ^~~~~
In file included from /usr/local/cuda/include/cuda_runtime.h:78:0,
                 from <command-line>:0:
/usr/local/cuda/include/host_config.h:119:2: error: #error -- unsupported GNU version! gcc versions later than 5 are not supported!
 #error -- unsupported GNU version! gcc versions later than 5 are not supported!
  ^~~~~
In file included from /usr/local/cuda/include/cuda_runtime.h:78:0,
                 from <command-line>:0:
/usr/local/cuda/include/host_config.h:119:2: error: #error -- unsupported GNU version! gcc versions later than 5 are not supported!
 #error -- unsupported GNU version! gcc versions later than 5 are not supported!
  ^~~~~
In file included from /usr/local/cuda/include/cuda_runtime.h:78:0,
                 from <command-line>:0:
/usr/local/cuda/include/host_config.h:119:2: error: #error -- unsupported GNU version! gcc versions later than 5 are not supported!
 #error -- unsupported GNU version! gcc versions later than 5 are not supported!
  ^~~~~
In file included from /usr/local/cuda/include/cuda_runtime.h:78:0,
                 from <command-line>:0:
/usr/local/cuda/include/host_config.h:119:2: error: #error -- unsupported GNU version! gcc versions later than 5 are not supported!
 #error -- unsupported GNU version! gcc versions later than 5 are not supported!
  ^~~~~
[ 87%] Built target objxgboost
CMake Error at nccl_generated_broadcast.cu.o.Release.cmake:222 (message):
  Error generating
  /home/ywang/xgboost/build/nccl/CMakeFiles/nccl.dir/src/./nccl_generated_broadcast.cu.o

CMake Error at nccl_generated_libwrap.cu.o.Release.cmake:222 (message):
  Error generating
  /home/ywang/xgboost/build/nccl/CMakeFiles/nccl.dir/src/./nccl_generated_libwrap.cu.o

nccl/CMakeFiles/nccl.dir/build.make:77: recipe for target 'nccl/CMakeFiles/nccl.dir/src/nccl_generated_broadcast.cu.o' failed
make[2]: *** [nccl/CMakeFiles/nccl.dir/src/nccl_generated_broadcast.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
nccl/CMakeFiles/nccl.dir/build.make:91: recipe for target 'nccl/CMakeFiles/nccl.dir/src/nccl_generated_libwrap.cu.o' failed
make[2]: *** [nccl/CMakeFiles/nccl.dir/src/nccl_generated_libwrap.cu.o] Error 1
CMake Error at nccl_generated_reduce_scatter.cu.o.Release.cmake:222 (message):
  Error generating
  /home/ywang/xgboost/build/nccl/CMakeFiles/nccl.dir/src/./nccl_generated_reduce_scatter.cu.o

nccl/CMakeFiles/nccl.dir/build.make:105: recipe for target 'nccl/CMakeFiles/nccl.dir/src/nccl_generated_reduce_scatter.cu.o' failed
make[2]: *** [nccl/CMakeFiles/nccl.dir/src/nccl_generated_reduce_scatter.cu.o] Error 1
CMake Error at nccl_generated_reduce.cu.o.Release.cmake:222 (message):
  Error generating
  /home/ywang/xgboost/build/nccl/CMakeFiles/nccl.dir/src/./nccl_generated_reduce.cu.o

nccl/CMakeFiles/nccl.dir/build.make:98: recipe for target 'nccl/CMakeFiles/nccl.dir/src/nccl_generated_reduce.cu.o' failed
make[2]: *** [nccl/CMakeFiles/nccl.dir/src/nccl_generated_reduce.cu.o] Error 1
CMake Error at nccl_generated_all_gather.cu.o.Release.cmake:222 (message):
  Error generating
  /home/ywang/xgboost/build/nccl/CMakeFiles/nccl.dir/src/./nccl_generated_all_gather.cu.o

nccl/CMakeFiles/nccl.dir/build.make:63: recipe for target 'nccl/CMakeFiles/nccl.dir/src/nccl_generated_all_gather.cu.o' failed
make[2]: *** [nccl/CMakeFiles/nccl.dir/src/nccl_generated_all_gather.cu.o] Error 1
CMake Error at nccl_generated_core.cu.o.Release.cmake:222 (message):
  Error generating
  /home/ywang/xgboost/build/nccl/CMakeFiles/nccl.dir/src/./nccl_generated_core.cu.o

nccl/CMakeFiles/nccl.dir/build.make:84: recipe for target 'nccl/CMakeFiles/nccl.dir/src/nccl_generated_core.cu.o' failed
make[2]: *** [nccl/CMakeFiles/nccl.dir/src/nccl_generated_core.cu.o] Error 1
CMake Error at nccl_generated_all_reduce.cu.o.Release.cmake:222 (message):
  Error generating
  /home/ywang/xgboost/build/nccl/CMakeFiles/nccl.dir/src/./nccl_generated_all_reduce.cu.o

nccl/CMakeFiles/nccl.dir/build.make:70: recipe for target 'nccl/CMakeFiles/nccl.dir/src/nccl_generated_all_reduce.cu.o' failed
make[2]: *** [nccl/CMakeFiles/nccl.dir/src/nccl_generated_all_reduce.cu.o] Error 1
CMakeFiles/Makefile2:367: recipe for target 'nccl/CMakeFiles/nccl.dir/all' failed
make[1]: *** [nccl/CMakeFiles/nccl.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

## Steps to reproduce
I followed the GPU tutorial
1. git clone --recursive https://github.com/dmlc/xgboost
2. cd xgboost; mkdir build; cd build
3. cmake .. -DUSE_CUDA=ON
4. make -j

## What have you tried?

1. There are not same issues, because the GPU build script was just modified
2. #2592 not worked

**Comment by RAMitchell** [comment]
Have you tried an older version of gcc as suggested by the compiler warnings?

**Comment by wydwww** [comment]
@RAMitchell Thanks for your response! Yes, I downgraded the gcc to 4.9 but not worked. Log now is:

ywang@ip-192-168-2-200:~/xgboost/build$ make -j
[  3%] Building NVCC (Device) object nccl/CMakeFiles/nccl.dir/src/nccl_generated_all_gather.cu.o
[  4%] Building NVCC (Device) object nccl/CMakeFiles/nccl.dir/src/nccl_generated_reduce_scatter.cu.o
[  6%] Building NVCC (Device) object nccl/CMakeFiles/nccl.dir/src/nccl_generated_libwrap.cu.o
[  6%] Building NVCC (Device) object nccl/CMakeFiles/nccl.dir/src/nccl_generated_reduce.cu.o
[  7%] Building NVCC (Device) object nccl/CMakeFiles/nccl.dir/src/nccl_generated_all_reduce.cu.o
[  9%] Building NVCC (Device) object nccl/CMakeFiles/nccl.dir/src/nccl_generated_core.cu.o
[ 10%] Building NVCC (Device) object nccl/CMakeFiles/nccl.dir/src/nccl_generated_broadcast.cu.o
[ 18%] Built target rabit
[ 32%] Built target dmlccore
[ 87%] Built target objxgboost
/usr/local/cuda/include/cuda_fp16.h(3068): error: more than one instance of overloaded function "isinf" matches the argument list:
            function "std::isinf(float)"
            function "isinf(float)"
            argument types are: (float)

/usr/local/cuda/include/cuda_fp16.h(3079): error: more than one instance of overloaded function "isinf" matches the argument list:
            function "std::isinf(float)"
            function "isinf(float)"
            argument types are: (float)

/usr/local/cuda/include/cuda_fp16.h(3068): error: more than one instance of overloaded function "isinf" matches the argument list:
            function "std::isinf(float)"
            function "isinf(float)"
            argument types are: (float)

/usr/local/cuda/include/cuda_fp16.h(3079): error: more than one instance of overloaded function "isinf" matches the argument list:
            function "std::isinf(float)"
            function "isinf(float)"
            argument types are: (float)

/usr/local/cuda/include/cuda_fp16.h(3068): error: more than one instance of overloaded function "isinf" matches the argument list:
            function "std::isinf(float)"
            function "isinf(float)"
            argument types are: (float)

/usr/local/cuda/include/cuda_fp16.h(3079): error: more than one instance of overloaded function "isinf" matches the argument list:
            function "std::isinf(float)"
            function "isinf(float)"
            argument types are: (float)

/usr/local/cuda/include/cuda_fp16.h(3068): error: more than one instance of overloaded function "isinf" matches the argument list:
            function "std::isinf(float)"
            function "isinf(float)"
            argument types are: (float)

/usr/local/cuda/include/cuda_fp16.h(3079): error: more than one instance of overloaded function "isinf" matches the argument list:
            function "std::isinf(float)"
            function "isinf(float)"
            argument types are: (float)

/usr/local/cuda/include/cuda_fp16.h(3068): error: more than one instance of overloaded function "isinf" matches the argument list:
            function "std::isinf(float)"
            function "isinf(float)"
            argument types are: (float)

/usr/local/cuda/include/cuda_fp16.h(3079): error: more than one instance of overloaded function "isinf" matches the argument list:
            function "std::isinf(float)"
            function "isinf(float)"
            argument types are: (float)

/usr/local/cuda/include/cuda_fp16.h(3068): error: more than one instance of overloaded function "isinf" matches the argument list:
            function "std::isinf(float)"
            function "isinf(float)"
            argument types are: (float)

/usr/local/cuda/include/cuda_fp16.h(3079): error: more than one instance of overloaded function "isinf" matches the argument list:
            function "std::isinf(float)"
            function "isinf(float)"
            argument types are: (float)

2 errors detected in the compilation of "/tmp/tmpxft_00001855_00000000-15_libwrap.compute_61.cpp1.ii".
CMake Error at nccl_generated_libwrap.cu.o.Release.cmake:282 (message):
  Error generating file
  /home/ywang/xgboost/build/nccl/CMakeFiles/nccl.dir/src/./nccl_generated_libwrap.cu.o


nccl/CMakeFiles/nccl.dir/build.make:91: recipe for target 'nccl/CMakeFiles/nccl.dir/src/nccl_generated_libwrap.cu.o' failed
make[2]: *** [nccl/CMakeFiles/nccl.dir/src/nccl_generated_libwrap.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
2 errors detected in the compilation of "/tmp/tmpxft_00001859_00000000-15_all_gather.compute_61.cpp1.ii".
CMake Error at nccl_generated_all_gather.cu.o.Release.cmake:282 (message):
  Error generating file
  /home/ywang/xgboost/build/nccl/CMakeFiles/nccl.dir/src/./nccl_generated_all_gather.cu.o


/usr/local/cuda/include/cuda_fp16.h(3068): error: more than one instance of overloaded function "isinf" matches the argument list:
            function "std::isinf(float)"
            function "isinf(float)"
            argument types are: (float)

/usr/local/cuda/include/cuda_fp16.h(3079): error: more than one instance of overloaded function "isinf" matches the argument list:
            function "std::isinf(float)"
            function "isinf(float)"
            argument types are: (float)

nccl/CMakeFiles/nccl.dir/build.make:63: recipe for target 'nccl/CMakeFiles/nccl.dir/src/nccl_generated_all_gather.cu.o' failed
make[2]: *** [nccl/CMakeFiles/nccl.dir/src/nccl_generated_all_gather.cu.o] Error 1
2 errors detected in the compilation of "/tmp/tmpxft_0000184f_00000000-15_broadcast.compute_61.cpp1.ii".
2 errors detected in the compilation of "/tmp/tmpxft_00001874_00000000-15_core.compute_61.cpp1.ii".
CMake Error at nccl_generated_broadcast.cu.o.Release.cmake:282 (message):
  Error generating file
  /home/ywang/xgboost/build/nccl/CMakeFiles/nccl.dir/src/./nccl_generated_broadcast.cu.o


nccl/CMakeFiles/nccl.dir/build.make:77: recipe for target 'nccl/CMakeFiles/nccl.dir/src/nccl_generated_broadcast.cu.o' failed
make[2]: *** [nccl/CMakeFiles/nccl.dir/src/nccl_generated_broadcast.cu.o] Error 1
CMake Error at nccl_generated_core.cu.o.Release.cmake:282 (message):
  Error generating file
  /home/ywang/xgboost/build/nccl/CMakeFiles/nccl.dir/src/./nccl_generated_core.cu.o


nccl/CMakeFiles/nccl.dir/build.make:84: recipe for target 'nccl/CMakeFiles/nccl.dir/src/nccl_generated_core.cu.o' failed
make[2]: *** [nccl/CMakeFiles/nccl.dir/src/nccl_generated_core.cu.o] Error 1
2 errors detected in the compilation of "/tmp/tmpxft_0000184d_00000000-15_reduce_scatter.compute_61.cpp1.ii".
CMake Error at nccl_generated_reduce_scatter.cu.o.Release.cmake:282 (message):
  Error generating file
  /home/ywang/xgboost/build/nccl/CMakeFiles/nccl.dir/src/./nccl_generated_reduce_scatter.cu.o


nccl/CMakeFiles/nccl.dir/build.make:105: recipe for target 'nccl/CMakeFiles/nccl.dir/src/nccl_generated_reduce_scatter.cu.o' failed
make[2]: *** [nccl/CMakeFiles/nccl.dir/src/nccl_generated_reduce_scatter.cu.o] Error 1
2 errors detected in the compilation of "/tmp/tmpxft_0000184e_00000000-15_reduce.compute_61.cpp1.ii".
CMake Error at nccl_generated_reduce.cu.o.Release.cmake:282 (message):
  Error generating file
  /home/ywang/xgboost/build/nccl/CMakeFiles/nccl.dir/src/./nccl_generated_reduce.cu.o


nccl/CMakeFiles/nccl.dir/build.make:98: recipe for target 'nccl/CMakeFiles/nccl.dir/src/nccl_generated_reduce.cu.o' failed
make[2]: *** [nccl/CMakeFiles/nccl.dir/src/nccl_generated_reduce.cu.o] Error 1
2 errors detected in the compilation of "/tmp/tmpxft_00001851_00000000-15_all_reduce.compute_61.cpp1.ii".
CMake Error at nccl_generated_all_reduce.cu.o.Release.cmake:282 (message):
  Error generating file
  /home/ywang/xgboost/build/nccl/CMakeFiles/nccl.dir/src/./nccl_generated_all_reduce.cu.o


nccl/CMakeFiles/nccl.dir/build.make:70: recipe for target 'nccl/CMakeFiles/nccl.dir/src/nccl_generated_all_reduce.cu.o' failed
make[2]: *** [nccl/CMakeFiles/nccl.dir/src/nccl_generated_all_reduce.cu.o] Error 1
CMakeFiles/Makefile2:367: recipe for target 'nccl/CMakeFiles/nccl.dir/all' failed
make[1]: *** [nccl/CMakeFiles/nccl.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by RAMitchell** [comment]
What is the cmake log if you disable GPU?

**Comment by wydwww** [comment]
@RAMitchell I can successfully build with `Building on Ubuntu/Debian` without GPU tutorial and run the python test code `test_basic.py` under /tests folder after installed python package.
```
Ran 12 tests in 22.560s

OK
```

**Comment by RAMitchell** [comment]
Okay please try to build the cmake version without GPU.
```
mkdir build
cd build
cmake .. 
make -j
```

This will tell us if there is a problem with cmake or specifically with nvcc. One possible cause is that cmake is not recognising that you have installed a new compiler. You can change the CXX environment variable as described here: https://cmake.org/Wiki/CMake_FAQ#How_do_I_use_a_different_compiler.3F

**Comment by wydwww** [comment]
@RAMitchell I deleted the whole xgboost folder and started again and it worked! Thanks for your time, it's my mistake.
