### ISSUE TITLE
[jvm-packages] Building under Windows x64

### ISSUE THREAD

**Issue by obones** [dmlc/xgboost#2688]
Hello,

I'm trying to use xgboost under my Windows x64 installation of Spark which is proving a bit harder than I initially thought.
I read the docs saying that I have to build from sources here:
http://xgboost.readthedocs.io/en/latest/jvm/

As it wasn't clear enough for me (I'm new to Java and maven), I went to this page:
https://www.quora.com/How-do-I-install-and-use-XGBoost4J-in-Spark

And I decided to use msys2 as the build environment.
With two minor modifications in rabit and the makefile, I was able to get a libxgboost.dll file built.
However, I feel this may have been wasted time because another xgboost documentation page leads me to prebuilt binaries for windows here: http://www.picnet.com.au/blogs/guido/post/2016/09/22/xgboost-windows-x64-binaries-for-download/

Anyway, I tried the maven step with this command:
`mvn -clean -DskipTests install package`

using the mvn binary from the IntelliJ (2017.2.3) installation that I use for my scala development.

This gave me an immediate failure because it does not know the "lean" lifecycle phase.
Fiddling around I came up with `-cclean` instead of `-clean` but I'm not sure what this does.

After having added python and cmake to my msys2 install, I was finally able to get things moving, but I'm getting this error:

```
  Could NOT find JNI (missing: JAVA_AWT_LIBRARY JAVA_JVM_LIBRARY
  JAVA_INCLUDE_PATH JAVA_INCLUDE_PATH2 JAVA_AWT_INCLUDE_PATH)
```

My JAVA_HOME is set to this: 
` export JAVA_HOME=/C/Program\ Files/Java/jdk1.8.0_131`

where jni.h can be found in the include folder.

So right now, I'm a bit lost as to where to go next.

Also, I'm wondering what would happen if I was to submit my program to a linux based cluster. I mean, would I need to recompile all this for a linux target?

**Comment by superbobry** [comment]
The JVM package build instructions are a bit of date. The build is done via CMake and uses Visual Studio 2015 on Windows. There is no need for Cygwin or MSYS2.

If you just need the binaries, you can look at prebuilt ones available [here](https://github.com/criteo-forks/xgboost-jars).

> Also, I'm wondering what would happen if I was to submit my program to a linux based cluster. I mean, would I need to recompile all this for a linux target?

Yes, you would need to recompile.

**Comment by obones** [comment]
Ah that explains a lot.
Thanks for the link towards prebuilt binaries, this will help a lot, even if I may have to rebuild them myself to target Java 1.8, Spark 2.1.1 and Scala 2.11

You mention that I would need to recompile and that makes perfect sense. But I have one more question: In Spark, I create a "uber jar" with my program and its dependencies to have it submitted to the cluster. Do you have any links to how to create such a jar that would support both Windows and Linux clusters at once?

**Comment by superbobry** [comment]
> Do you have any links to how to create such a jar that would support both Windows and Linux clusters at once?

I am by no means an expert in cross-compilation, but IIUC it should be possible for Windows/Linux. We needed OS X, so the solution for us was to build all three independently and then merge the resulting JARs with platform-specific binaries into one.

**Comment by obones** [comment]
What I intend to do is to have a scala class that uses xgboost and package jars for both Windows and Linux in my "uber jar".
From your last sentence I understand that it is possible so I'll investigate how to do this.

**Comment by superbobry** [comment]
JVM would automatically load the right shared library on each platform. You just need to make sure they are bundled in the xgboot4j JAR.

**Comment by obones** [comment]
Thanks for your answers, it works just fine.
