### ISSUE TITLE
I have the solution how to build on arch linux, let's discuss

### ISSUE THREAD

**Issue by kootenpv** [dmlc/xgboost#2689]
So I was not able for the life of me to build `xgboost`, until I made a change in the Makefile

In the Makefile:

```
-lib/xgboost.dll lib/libxgboost.so lib/libxgboost.dylib: $(ALL_DEP)
+lib/libxgboost.so: $(ALL_DEP)
```

Only then did `make lib/libxgboost.so` work.

Then I could just do a simple `python setup.py install`

I understand this is not the OS independent solution, but at least it points into the direction?

**Comment by sl2902** [comment]
I am trying to compile xgboost from source, but I am stuck at the first step: as listed here https://github.com/dmlc/xgboost/blob/master/doc/build.md

I have created a virtual env on AWS, and I was able to install xgboost via pip install, but this doesn't let me taking advantage of GPU support. So, if I decided to follow the instruction in the document, but I am not sure how to build shared library. If I start from scratch, from which directory should I be running the make command. I am on Ubuntu 16.04.3. Can you help?
