### ISSUE TITLE
Very odd behavior with predict function

### ISSUE THREAD

**Issue by DeluxeAnalyst** [dmlc/xgboost#2690]
I am trying to score a new model, and trying to predict with it is giving me some weird behaviour. Because of the size of the data, I am putting the data into a sparse matrix and then using xgboost to predict from that. 

(To do the below, i took a smaller sample of data). 

When I use the predict function on the sparse matrix, it is giving me different predictions than when I predict on a normal matrix. Please see the screenshot below, you can see that the predictions are different in both cases, why would this be happening? The top predictions are supposed to be the correct ones, coming from the non-sparse matrix. 

![image](https://user-images.githubusercontent.com/14318891/30225668-e4a4a6b4-9498-11e7-814d-7a408955a8ae.png)

**Comment by hetong007** [comment]
More info is needed, as:
- what type of matrix is used in training
- is `x` modified when transformed by `data.matrix`
etc.

Please provide a script along with a small dataset to reproduce the behavior.

**Comment by DeluxeAnalyst** [comment]
I wasnt able to come up with a reproducible example. The original training set was also a data.matrix. I have done this with a different model and everything worked fine, so im not sure whats going on with this one, especially when I compare the columns between a data.matrix and the sparse matrix they pass an identical() test. 

You can probably close, I am just going to go back and build the original model on a sparse matrix format and that should fix it.

**Comment by Laurae2** [comment]
@DeluxeAnalyst Sparse matrices in R uses `0` as `NA` by default and will become `0` when transformed back to a matrix (0 -> NA (trained on NA) -> 0 (predicting on 0?) ).
