### ISSUE TITLE
nvcc fatal   : Unsupported gpu architecture 'compute_60' when building with GPU support

### ISSUE THREAD

**Issue by terry-li-hm** [dmlc/xgboost#2699]
## Environment info
Operating System: ubuntu 16.04

Driver Version: 384.66

## Steps to reproduce

The following are showed when I run `make -j`:

[  1%] Building NVCC (Device) object nccl/CMakeFiles/nccl.dir/src/nccl_generated_core.cu.o
[  3%] Building NVCC (Device) object nccl/CMakeFiles/nccl.dir/src/nccl_generated_all_reduce.cu.o
[  4%] Building NVCC (Device) object nccl/CMakeFiles/nccl.dir/src/nccl_generated_reduce.cu.o
[  6%] Building NVCC (Device) object nccl/CMakeFiles/nccl.dir/src/nccl_generated_libwrap.cu.o
[  7%] Building NVCC (Device) object nccl/CMakeFiles/nccl.dir/src/nccl_generated_all_gather.cu.o
[  9%] Building NVCC (Device) object nccl/CMakeFiles/nccl.dir/src/nccl_generated_broadcast.cu.o
[ 10%] Building NVCC (Device) object nccl/CMakeFiles/nccl.dir/src/nccl_generated_reduce_scatter.cu.o
[ 18%] Built target rabit
[ 32%] Built target dmlccore
nvcc fatal   : Unsupported gpu architecture 'compute_60'
CMake Error at nccl_generated_all_gather.cu.o.cmake:207 (message):
  Error generating
  /home/terry/xgboost/build/nccl/CMakeFiles/nccl.dir/src/./nccl_generated_all_gather.cu.o

nccl/CMakeFiles/nccl.dir/build.make:98: recipe for target 'nccl/CMakeFiles/nccl.dir/src/nccl_generated_all_gather.cu.o' failed
make[2]: *** [nccl/CMakeFiles/nccl.dir/src/nccl_generated_all_gather.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
nvcc fatal   : Unsupported gpu architecture 'compute_60'
CMake Error at nccl_generated_core.cu.o.cmake:207 (message):
  Error generating
  /home/terry/xgboost/build/nccl/CMakeFiles/nccl.dir/src/./nccl_generated_core.cu.o

nccl/CMakeFiles/nccl.dir/build.make:77: recipe for target 'nccl/CMakeFiles/nccl.dir/src/nccl_generated_core.cu.o' failed
make[2]: *** [nccl/CMakeFiles/nccl.dir/src/nccl_generated_core.cu.o] Error 1
[ 87%] Built target objxgboost
nvcc fatal   : Unsupported gpu architecture 'compute_60'
CMake Error at nccl_generated_broadcast.cu.o.cmake:207 (message):
  Error generating
  /home/terry/xgboost/build/nccl/CMakeFiles/nccl.dir/src/./nccl_generated_broadcast.cu.o

nccl/CMakeFiles/nccl.dir/build.make:105: recipe for target 'nccl/CMakeFiles/nccl.dir/src/nccl_generated_broadcast.cu.o' failed
make[2]: *** [nccl/CMakeFiles/nccl.dir/src/nccl_generated_broadcast.cu.o] Error 1
nvcc fatal   : Unsupported gpu architecture 'compute_60'
nvcc fatal   : Unsupported gpu architecture 'compute_60'
nvcc fatal   : Unsupported gpu architecture 'compute_60'
CMake Error at nccl_generated_libwrap.cu.o.cmake:207 (message):
  Error generating
  /home/terry/xgboost/build/nccl/CMakeFiles/nccl.dir/src/./nccl_generated_libwrap.cu.o

nccl/CMakeFiles/nccl.dir/build.make:63: recipe for target 'nccl/CMakeFiles/nccl.dir/src/nccl_generated_libwrap.cu.o' failed
make[2]: *** [nccl/CMakeFiles/nccl.dir/src/nccl_generated_libwrap.cu.o] Error 1
CMake Error at nccl_generated_reduce.cu.o.cmake:207 (message):
  Error generating
  /home/terry/xgboost/build/nccl/CMakeFiles/nccl.dir/src/./nccl_generated_reduce.cu.o

nccl/CMakeFiles/nccl.dir/build.make:84: recipe for target 'nccl/CMakeFiles/nccl.dir/src/nccl_generated_reduce.cu.o' failed
make[2]: *** [nccl/CMakeFiles/nccl.dir/src/nccl_generated_reduce.cu.o] Error 1
CMake Error at nccl_generated_all_reduce.cu.o.cmake:207 (message):
  Error generating
  /home/terry/xgboost/build/nccl/CMakeFiles/nccl.dir/src/./nccl_generated_all_reduce.cu.o

nccl/CMakeFiles/nccl.dir/build.make:91: recipe for target 'nccl/CMakeFiles/nccl.dir/src/nccl_generated_all_reduce.cu.o' failed
make[2]: *** [nccl/CMakeFiles/nccl.dir/src/nccl_generated_all_reduce.cu.o] Error 1
nvcc fatal   : Unsupported gpu architecture 'compute_60'
CMake Error at nccl_generated_reduce_scatter.cu.o.cmake:207 (message):
  Error generating
  /home/terry/xgboost/build/nccl/CMakeFiles/nccl.dir/src/./nccl_generated_reduce_scatter.cu.o

nccl/CMakeFiles/nccl.dir/build.make:70: recipe for target 'nccl/CMakeFiles/nccl.dir/src/nccl_generated_reduce_scatter.cu.o' failed
make[2]: *** [nccl/CMakeFiles/nccl.dir/src/nccl_generated_reduce_scatter.cu.o] Error 1
CMakeFiles/Makefile2:367: recipe for target 'nccl/CMakeFiles/nccl.dir/all' failed
make[1]: *** [nccl/CMakeFiles/nccl.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

## What have you tried?

While there are similar cases for Caffe online, I failed to find the same case for XGBoost. By googling with very limited knowledge I guess the crux is that 1080 Ti (the GPU I am using) does not have Compute Capability 6.0. But I have no idea on how to fix this.

Your help it much appreciated!

**Comment by RAMitchell** [comment]
Are you using cuda 7.5?  Try updating to 8.0.

**Comment by CraveInfinity** [comment]
`$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176
`

still have the same issue? and cuda-9

**Comment by aliyesilkanat** [comment]
Have the same issue on Cuda-9
