### ISSUE TITLE
Can I add more features of data for training continuation?

### ISSUE THREAD

**Issue by fcbruce** [dmlc/xgboost#2701]
As title, can I append some features to train a new model base on an old model?  

For example, I trained a model with features [A, B, C, D, E] as an old model. After some months, I collect more data and features and want to update the model. I continue to train a new model with features [A, B, C, D, E, F] base on the old one.

I noticed I can pass the parameter `xgb_model` for training continuation, such as (python)
```
bst = xgb.train(params, d_train, num_round, watch_list, early_stopping_rounds=early_stopping, xgb_model=old_model_path)
```
The code can run, but I'm not sure that appending features is correct on algorithm.

**Comment by pommedeterresautee** [comment]
Why would you do that? Learning on the whole dataset, including new data will give you the best model because it will use all data available from scratch.

**Comment by fcbruce** [comment]
@pommedeterresautee many causes. Maybe the whole dataset is too large or the data shift. Iteration with new data for adapting to the change of actual data.

**Comment by pommedeterresautee** [comment]
Ok but you should start with all features.

**Comment by fcbruce** [comment]
@pommedeterresautee Aha! It makes sense! I got it! Thx!
