### ISSUE TITLE
[jvm-packages] Running on Spark under Windows x64

### ISSUE THREAD

**Issue by obones** [dmlc/xgboost#2705]
Following the discussion in Issue #2688, I was able to get binaries for xgboost to use in my Windows x64 Spark setup.

I was able to compile my test program just fine, and have the following code to call xgboost:

        val numRound = 10
        val numWorkers = 4
        val paramMap = List(
          "eta" -> 0.023f,
          "max_depth" -> 10,
          "min_child_weight" -> 3.0,
          "subsample" -> 1.0,
          "colsample_bytree" -> 0.82,
          "colsample_bylevel" -> 0.9,
          "base_score" -> 0.005,
          "eval_metric" -> "auc",
          "seed" -> 49,
          "silent" -> 1,
          "objective" -> "binary:logistic").toMap

        XGBoost.trainWithDataFrame(
          sourceData,
          paramMap,
          round = numRound,
          nWorkers = numWorkers,
          useExternalMemory = true,
          labelCol = labelColName)

However, when I run it, it stops with the following error:

```
java.io.IOException: Cannot run program "python": CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:450)
	at java.lang.Runtime.exec(Runtime.java:347)
	at ml.dmlc.xgboost4j.java.RabitTracker.startTrackerProcess(RabitTracker.java:132)
	at ml.dmlc.xgboost4j.java.RabitTracker.start(RabitTracker.java:155)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.startTracker(XGBoost.scala:255)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainDistributed(XGBoost.scala:318)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostEstimator.train(XGBoostEstimator.scala:135)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostEstimator.train(XGBoostEstimator.scala:36)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:96)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainWithDataFrame(XGBoost.scala:191)

```

Well, the error message is quite clear, but it leads me to the following questions:

What is the use of python here?
Is it possible not to use python, as it is not available by default under Windows?
If not, how do I specify the python binary location?

For the last question, adding its location in the PATH environment variable is not a viable solution because of length limitation for environment variables under Windows.

**Comment by obones** [comment]
Ok, I found this page:
http://blog.quirk.es/2009/11/setting-environment-variables-in-java.html

And using it as an inspiration, it allows me to add the folder where python is to the PATH environment variable.

However, I also discovered the `tracker_conf` parameter that can be set in the `paramMap` value which I set to this value:

        val trackerConf = new TrackerConf(0, "scala")

While this allows to bypass the error about python not having been found, it triggers a new error:

`Exception in thread "main" java.lang.NoClassDefFoundError: akka/actor/ActorSystem$`

What am I missing here?

**Comment by obones** [comment]
Ok, answering myself here, I need to add the akka.io/actor dependency to my project, even if it's only xgboost using it. This in turn triggers an issue where the binaries I'm using are not targeting the same scala version as my project does, but I should be able to manage that.

**Comment by superbobry** [comment]
When using a local JAR you should specify all its dependencies manually. Alternatively, you could use `*-with-dependencies.jar`, which packages `xgboost4j` along with all its dependencies in a single JAR.
