### ISSUE TITLE
xgboost4j，how to get the trees

### ISSUE THREAD

**Issue by appvin** [dmlc/xgboost#2709]
As we all know, xgboost+LR can do well in Click-Through Rate Prediction,but it seems like that there is no method to get all the trees or the leaves which can be done in python for .apply()
thanks for help

**Comment by superbobry** [comment]
You would have to parse the model dump.

**Comment by d0evi1** [comment]
you can see .apply() method's implements，have a try: 
 
model.booster.predict(dataMatrix, true, 0)

**Comment by appvin** [comment]
@d0evi1 thanks for that
