### ISSUE TITLE
[jvm-packages]how to set nworkers when run spark[yarn-cluster]

### ISSUE THREAD

**Issue by xueyuan1990** [dmlc/xgboost#2712]
I use tag:0.6 version
 val xgboostModel = XGBoost.train(trainData, paramMap, numRound, nWorkers , useExternalMemory = true)
I just don't know how to set nWorkers  value. Because I don't know the executor nums and cores when they are dynamic allocation.
Who can help?

**Comment by superbobry** [comment]
Dynamic allocation scenario is not yet supported, see discussion in #2697.
