### ISSUE TITLE
xgboost plugins and the R bindings

### ISSUE THREAD

**Issue by kadrach** [dmlc/xgboost#2721]
I'm trying to add a custom objective function via the plugin system, following this [example](https://github.com/dmlc/xgboost/tree/master/plugin/example).

Using the example at verbatim, I can compile xgboost with the added objective "mylogistic", and can see this via the CLI (Don't really use the CLI - but changing the binary classification example to use the added objective "works", and if I configure that demo with a nonexistent objective I get a list of existing ones, including "mylogistic").

However the R package does not seem to include the added "mylogistic" objective.

I don't know enough about how xgboost and the R package are compiled to even have a remote idea of why this would be happening.

Am I missing a step here? Or is the example incomplete, or is this usecase not supported at this stage?

**Comment by kadrach** [comment]
Manually adding `$(PKGROOT)/build_plugin/example/custom_obj.o` to `R-package/src/Makevars` seems to do the trick, but I need to build the shared library separately first.

**Comment by pommedeterresautee** [comment]
I think that s the only way. I close the issue for now.

**Comment by khotilov** [comment]
@kadrach You would need to include your code into the amalgamation https://github.com/dmlc/xgboost/blob/master/amalgamation/xgboost-all0.cc

**Comment by kadrach** [comment]
@khotilov Thank you. Is there a pluggable way of achieving this?
