### ISSUE TITLE
[jvm_packages] what does every element in return of XGBoostModel.predict mean?

### ISSUE THREAD

**Issue by psy2013GitHub** [dmlc/xgboost#2725]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System:

Compiler:

Package used (python/R/jvm/C++):

`xgboost` version used:

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`)
2. Logs will be helpful (If logs are large, please upload as attachment).

If you are using jvm package, please 

1. add [jvm-packages] in the title to make it quickly be identified
2. the gcc version and distribution

If you are using python package, please provide

1. The python version and distribution
2. The command to install `xgboost` if you are not installing from source

If you are using R package, please provide

1. The R `sessionInfo()`
2. The command to install `xgboost` if you are not installing from source

## Steps to reproduce

1.   val model = XGBoost.train(trainRDD, params, .... )
2.   val eval_score = model.eval(testRDD, "MyEval", new MyEval())
3.   according to the code in https://github.com/dmlc/xgboost/blob/master/jvm-packages/xgboost4j-example/src/main/java/ml/dmlc/xgboost4j/java/example/CustomObjective.java, it seems that 
"predicts[i][0] > 0 means lable=1" and "predicts[i][0] <= 0 means lable=0", right?
 see:
https://github.com/dmlc/xgboost/blob/1190dc62a79c0a7fc5164c03f6c7ff6b87629971/jvm-packages/xgboost4j-example/src/main/java/ml/dmlc/xgboost4j/java/example/CustomObjective.java#L117-L134

## What have you tried?

1. 
2.
3.

**Comment by psy2013GitHub** [comment]
@CodingCat what do you think ；）

**Comment by sethah** [comment]
Haven't you answered your own question?
