### ISSUE TITLE
XGBoost for processing multiple partition files

### ISSUE THREAD

**Issue by EvanzzzZ** [dmlc/xgboost#2729]
Is there any support in xgboost that can handle multiple input files ? If the data is extremely large, usually they come as multiple partitions of files.

The way that distributed xgboost working is different workers loaded different partition of the file by parsing the same big file. Is there any support if there are already multiple chunks of partition files. 

I saw there is support for retrieving data from s3 bucket by passing directory path. But the doc is not clear about how this work.

**Comment by superbobry** [comment]
I think you might be able to do this with Spark: load them into a [single RDD](https://stackoverflow.com/questions/24029873/how-to-read-multiple-text-files-into-a-single-rdd) or DataFrame and run distributed XGBoost.

**Comment by EvanzzzZ** [comment]
I think the spark xgboost currently only support scala and java ?
Besides using RDD, which more like a preprocessing of the data, is there any way or is it possible to add support that xgboost can evenly allocate the workers to the partitions of data, and do auto parsing, and then each worker has its own partition so that the algorithm can do distributed tree construction after that.

**Comment by EvanzzzZ** [comment]
@superbobry Do you think this is a good feature to have to improve xgboost?

**Comment by CodingCat** [comment]
xgboost supports pure yarn based distributed training

**Comment by EvanzzzZ** [comment]
Just found that xgboost actually read multiple files given the dir path.
