### ISSUE TITLE
best_iteration is not saved

### ISSUE THREAD

**Issue by yzliao** [dmlc/xgboost#273]
I trained a model and saved it for prediction. When I loaded it again, the system raised an error that  `AttributeError: 'Booster' object has no attribute 'best_iteration'`. 

Here is my code:
```Python
bst = xgb.Booster({'nthread':4}) #init model
bst.load_model("result.model" ) # load model
y_prob = bst.predict(xg_valid,ntree_limit=bst.best_iteration)
```

**Comment by tqchen** [comment]
best_iteration was some side information returned by training function that won't be saved during save_model.  I think it is OK to make it remain this way

**Comment by yzliao** [comment]
The potential issue I think is that if the model is saved for future prediction, the model used will not be the best one since either best_iteration or validation history is saved with the model.

**Comment by yzliao** [comment]
In my own case, I am doing grid search with 100+ models, which are saved for prediction. Since I am saving all the training history (training error, validation error), I can trace back to the iteration with min iteration. If I do not save the history, basically I cannot find the best model among 100+ models since they all have been overfitted.

**Comment by tqchen** [comment]
I understand your concern. There is a tradeoff between unified model format (between R, cxx, and python) and saving extra information.
This piece additional information can be saved as validation history as you claimed (which was not hard)

**Comment by yzliao** [comment]
I see. Okay then. Thank you for the quick response.
