### ISSUE TITLE
n_jobs is not accepted as an argument of XGBClassifier

### ISSUE THREAD

**Issue by big-doug** [dmlc/xgboost#2730]
According to its documentation, xgboost has an n_jobs parameter. However, when I attempt to set n_jobs, I get this error:

    TypeError: __init__() got an unexpected keyword argument 'n_jobs'

Same issue for some other parameters like random_state. I assumed this might be an update issue, but it seems I have the latest version (0.6a2, installed with pip).

Operating System: Linux
Package used (python/R/jvm/C++): python

**Comment by khotilov** [comment]
The Pypi xgboost package is over a year old. Please install from the source.

**Comment by cs94njw** [comment]
On version 0.7.post3 I have the same problem.

**Comment by SylwiaOliwia2** [comment]
I have the same issue as well (on `0.7.post3`).

**Comment by vasulakkaraju** [comment]
still have the same issue on version 0.7.1 any fix for this?

**Comment by hcho3** [comment]
`n_jobs` should be accepted by `XGBClassifier`, according to [line 397 of sklearn.py](https://github.com/dmlc/xgboost/blob/v0.71/python-package/xgboost/sklearn.py#L397), version 0.7.1. Make sure you have the correct version installed.
