### ISSUE TITLE
[jvm-packages] Test fails with "SEVERE: usr_paths" (ml.dmlc.xgboost4j.java.NativeLibLoader addNativeDir)

### ISSUE THREAD

**Issue by gtsoukas** [dmlc/xgboost#2733]
I have successfully build and tested xgboost jvm-packages on a recent Ubuntu but fail to do so on a corporate linux with probably some outdated pieces of software. Here is what i tried:

```
$JAVA_HOME/bin/java -version

java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

cmake -version
cmake version 3.9.2

git clone --recursive https://github.com/dmlc/xgboost

cd xgboost
git rev-parse HEAD

c09204fa70c665ad8c1e265b391847e8bc6e1dc0

cd jvm-pakcages
mvn package
```

Test fail with the following output:

> Sep 20, 2017 9:35:46 AM ml.dmlc.xgboost4j.java.NativeLibLoader addNativeDir
> SEVERE: usr_paths
> Sep 20, 2017 9:35:46 AM ml.dmlc.xgboost4j.java.DMatrix <clinit>
> SEVERE: Failed to load native library
> java.io.IOException: Failed to get field handle to set library path
>         at ml.dmlc.xgboost4j.java.NativeLibLoader.addNativeDir(NativeLibLoader.java:185)
>         at ml.dmlc.xgboost4j.java.NativeLibLoader.smartLoad(NativeLibLoader.java:146)
>         at ml.dmlc.xgboost4j.java.NativeLibLoader.initXGBoost(NativeLibLoader.java:40)
>         at ml.dmlc.xgboost4j.java.XGBoostJNI.<clinit>(XGBoostJNI.java:34)
>         at ml.dmlc.xgboost4j.java.DMatrix.<init>(DMatrix.java:68)
>         at ml.dmlc.xgboost4j.scala.DMatrix.<init>(DMatrix.scala:31)
>         at ml.dmlc.xgboost4j.scala.ScalaBoosterImplSuite$$anonfun$4.apply(ScalaBoosterImplSuite.scala:98)
>         at ml.dmlc.xgboost4j.scala.ScalaBoosterImplSuite$$anonfun$4.apply(ScalaBoosterImplSuite.scala:97)
>         at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
>         at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
>         at org.scalatest.Transformer.apply(Transformer.scala:22)
>         at org.scalatest.Transformer.apply(Transformer.scala:20)
>         at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
>         at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
>         at org.scalatest.FunSuite.withFixture(FunSuite.scala:1560)
>         at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:183)
>         at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
>         at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
>         at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
>         at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:196)
>         at org.scalatest.FunSuite.runTest(FunSuite.scala:1560)
>         at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
>         at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
>         at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
>         at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
>         at scala.collection.immutable.List.foreach(List.scala:381)
>         at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
>         at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
>         at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
>         at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:229)
>         at org.scalatest.FunSuite.runTests(FunSuite.scala:1560)
>         at org.scalatest.Suite$class.run(Suite.scala:1147)
>         at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1560)
>         at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
>         at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
>         at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
>         at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:233)
>         at org.scalatest.FunSuite.run(FunSuite.scala:1560)
>         at org.scalatest.Suite$class.callExecuteOnSuite$1(Suite.scala:1210)
>         at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1257)
>         at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1255)
>         at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
>         at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
>         at org.scalatest.Suite$class.runNestedSuites(Suite.scala:1255)
>         at org.scalatest.tools.DiscoverySuite.runNestedSuites(DiscoverySuite.scala:30)
>         at org.scalatest.Suite$class.run(Suite.scala:1144)
>         at org.scalatest.tools.DiscoverySuite.run(DiscoverySuite.scala:30)
>         at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
>         at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$1.apply(Runner.scala:1340)
>         at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$1.apply(Runner.scala:1334)
>         at scala.collection.immutable.List.foreach(List.scala:381)
>         at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1334)
>         at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1011)
>         at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1010)
>         at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1500)
>         at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1010)
>         at org.scalatest.tools.Runner$.main(Runner.scala:827)
>         at org.scalatest.tools.Runner.main(Runner.scala)
> 
> *** RUN ABORTED ***
>   java.lang.ExceptionInInitializerError:
>   at java.lang.J9VMInternals.ensureError(J9VMInternals.java:134)
>   at java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:123)
>   at ml.dmlc.xgboost4j.java.DMatrix.<init>(DMatrix.java:68)
>   at ml.dmlc.xgboost4j.scala.DMatrix.<init>(DMatrix.scala:31)
>   at ml.dmlc.xgboost4j.scala.ScalaBoosterImplSuite$$anonfun$4.apply(ScalaBoosterImplSuite.scala:98)
>   at ml.dmlc.xgboost4j.scala.ScalaBoosterImplSuite$$anonfun$4.apply(ScalaBoosterImplSuite.scala:97)
>   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
>   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
>   at org.scalatest.Transformer.apply(Transformer.scala:22)
>   at org.scalatest.Transformer.apply(Transformer.scala:20)
>   ...
>   Cause: java.lang.RuntimeException: java.io.IOException: Failed to get field handle to set library path
>   at ml.dmlc.xgboost4j.java.XGBoostJNI.<clinit>(XGBoostJNI.java:37)
>   at ml.dmlc.xgboost4j.java.DMatrix.<init>(DMatrix.java:68)
>   at ml.dmlc.xgboost4j.scala.DMatrix.<init>(DMatrix.scala:31)
>   at ml.dmlc.xgboost4j.scala.ScalaBoosterImplSuite$$anonfun$4.apply(ScalaBoosterImplSuite.scala:98)
>   at ml.dmlc.xgboost4j.scala.ScalaBoosterImplSuite$$anonfun$4.apply(ScalaBoosterImplSuite.scala:97)
>   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
>   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
>   at org.scalatest.Transformer.apply(Transformer.scala:22)
>   at org.scalatest.Transformer.apply(Transformer.scala:20)
>   at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
>   ...
>   Cause: java.io.IOException: Failed to get field handle to set library path
>   at ml.dmlc.xgboost4j.java.NativeLibLoader.addNativeDir(NativeLibLoader.java:185)
>   at ml.dmlc.xgboost4j.java.NativeLibLoader.smartLoad(NativeLibLoader.java:146)
>   at ml.dmlc.xgboost4j.java.NativeLibLoader.initXGBoost(NativeLibLoader.java:40)
>   at ml.dmlc.xgboost4j.java.XGBoostJNI.<clinit>(XGBoostJNI.java:34)
>   at ml.dmlc.xgboost4j.java.DMatrix.<init>(DMatrix.java:68)
>   at ml.dmlc.xgboost4j.scala.DMatrix.<init>(DMatrix.scala:31)
>   at ml.dmlc.xgboost4j.scala.ScalaBoosterImplSuite$$anonfun$4.apply(ScalaBoosterImplSuite.scala:98)
>   at ml.dmlc.xgboost4j.scala.ScalaBoosterImplSuite$$anonfun$4.apply(ScalaBoosterImplSuite.scala:97)
>   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
>   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
>   ...
> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Summary:
> [INFO]
> [INFO] xgboost-jvm ........................................ SUCCESS [  5.088 s]
> [INFO] xgboost4j .......................................... FAILURE [02:59 min]

Please find the full log from mvn package attached.
[xgboost4j_test_error.txt](https://github.com/dmlc/xgboost/files/1316993/xgboost4j_test_error.txt)

Thank you so much for providing this great software.

**Comment by superbobry** [comment]
Could you specify which distribution is used as corporate Linux and which JVM version it bundles?

**Comment by gtsoukas** [comment]
It seems that that I have a different Java version in my PATH environment variable than in the JAVA_HOME environment variable.

After updating PATH with the more recent Java from JAVA_HOME *xgboost4j* is successful, so I will set this issue to solved and open a new one for a failure occurring in the *xgboost4j-spark* step.

https://github.com/dmlc/xgboost/issues/2736

For the record, here is the system information (SLES11 SP4):
```
uname -a
Linux xxxxxxxx 3.0.101-84-default #1 SMP Tue Oct 18 10:32:51 UTC 2016 (15251d6) x86_64 x86_64 x86_64 GNU/Linux

lsb_release -a
LSB Version:    core-2.0-noarch:core-3.2-noarch:core-4.0-noarch:core-2.0-x86_64:core-3.2-x86_64:core-4.0-x86_64:desktop-4.0-amd64:desktop-4.0-noarch:graphics-2.0-amd64:graphics-2.0-noarch:graphics-3.2-amd64:graphics-3.2-noarch:graphics-4.0-amd64:graphics-4.0-noarch
Distributor ID: SUSE LINUX
Description:    SUSE Linux Enterprise Server 11 (x86_64)
Release:        11
Codename:       n/a


java -version

java version "1.7.0"
Java(TM) SE Runtime Environment (build pxa6470_27sr3fp50-20160720_02(SR3fp50))
IBM J9 VM (build 2.7, JRE 1.7.0 Linux amd64-64 Compressed References 20160630_309914 (JIT enabled, AOT enabled)
J9VM - R27_Java727_SR3_20160630_1516_B309914
JIT  - tr.r13.java_20160629_120282
GC   - R27_Java727_SR3_20160630_1516_B309914_CMPRSS
J9CL - 20160630_309914)
JCL - 20160719_01 based on Oracle jdk7u111-b13
```
