### ISSUE TITLE
how to use xgboost in android or ios platform?

### ISSUE THREAD

**Issue by panmin** [dmlc/xgboost#2734]
how to bulid .so or .a for android or ios  platform?

**Comment by superbobry** [comment]
Do you want training or just inference, if the latter, have a look at [treelite](https://github.com/dmlc/treelite).

**Comment by panmin** [comment]
i want training,can you give me an example that use xgboost in android or ios platform?

**Comment by panmin** [comment]
@superbobry  if i use treelite ,how to use it in android or ios platform?

**Comment by superbobry** [comment]
I suggest continuing the conversation in dmlc/treelite#6.

**Comment by superbobry** [comment]
Ooops, sorry, haven't spotted the other question.

Sadly, I can't help with training on iOS/Android, but I imagine you might not want that as training is very computationally intensive.
