### ISSUE TITLE
[jvm-packages]  label and prediction not match 

### ISSUE THREAD

**Issue by xueyuan1990** [dmlc/xgboost#2735]
`xgboost` version used: v0.6

when do prediction , I need to get the (userid,prediction) pair,and you don't provide this ,so I do it by myself 
_________________________
```
 import scala.collection.JavaConverters._
import ml.dmlc.xgboost4j.java.Rabit
import ml.dmlc.xgboost4j.scala.DMatrix
import ml.dmlc.xgboost4j.scala.spark.{XGBoost, XGBoostModel}
import org.apache.spark.TaskContext
import org.apache.spark.mllib.evaluation.BinaryClassificationMetrics
import org.apache.spark.mllib.linalg.SparseVector
import org.apache.spark.mllib.regression.LabeledPoint
import org.apache.spark.rdd.RDD

//userid is the label

  def predict(xgboostModel: XGBoostModel, testSet: RDD[LabeledPoint]): RDD[(Long, Float)] = {
    testSet.cache()
   logger.info("input label" + testSet.map(_.label.toLong).collect().mkString(","))

    import ml.dmlc.xgboost4j.scala.spark.DataUtils._
    val _booster = xgboostModel.booster
    val broadcastBooster = SparkApp.sc.broadcast(_booster)
    val res = testSet.repartition(partition_num).mapPartitions { testSamples =>
      if (testSamples.hasNext) {
        val rabitEnv = Array("DMLC_TASK_ID" -> TaskContext.getPartitionId().toString).toMap
        Rabit.init(rabitEnv.asJava)
        val dMatrix = new DMatrix(testSamples, null)
        val labels = dMatrix.getLabel  //get label
        val scores = broadcastBooster.value.predict(dMatrix)  //get score
        var label_score = new ArrayBuffer[(Long, Float)]
        for (i <- 0 until labels.length) {
          label_score += ((labels(i).toLong, scores(i)(0)))
        }
        Rabit.shutdown()
        Iterator(label_score.toArray)
      } else {
        Iterator()
      }
    }.flatMap(r => r)
    res.cache()
    logger.info("output label = " + res.map(_._1).collect().mkString(","))
    res
  }
```
the input label is

866190025413180,863274037713929,861578031108080,868800020840207,868564029652563,868746023706384,862842032737845,861868032295089,861643039639401,861643036795123
the output label is 
866190012448768,863274065199104,861578022879232,868800010387456,868564055621632,868746054860800,862842018332672,861868000280576,861643051368448,861643051368448
I have know why. Because the Double type has accuracy problem. But how can I  get the right label?
Thanks for your help

**Comment by xueyuan1990** [comment]
I have know why. Because the Double type has accuracy problem. But how can I do the get the right label

**Comment by sethah** [comment]
You're asking why they don't have the same ordering anymore? You've done a `repartition` on the RDD, so that completely jumbles the ordering. 

I think this issue should be closed. cc @superbobry

**Comment by superbobry** [comment]
@xueyuan1990 the reordering is indeed caused by `repartition` as @sethah noticed. However, even if there was no reordering you'd probably have issues with precision because labels [are assumed to be floats](https://github.com/dmlc/xgboost/blob/master/jvm-packages/xgboost4j/src/main/scala/ml/dmlc/xgboost4j/LabeledPoint.scala#L30) in XGBoost.
