### ISSUE TITLE
Different split_condition in dumped model with same data if input is sparse

### ISSUE THREAD

**Issue by volker48** [dmlc/xgboost#2737]
## Environment info
Operating System: OS X

Compiler: g++-7

Package used (python/R/jvm/C++): Python

`xgboost` version used: c09204fa70c665ad8c1e265b391847e8bc6e1dc0

If you are using python package, please provide

1. The python version and distribution: Python 3.6.2
2. The command to install `xgboost` if you are not installing from source: pip install -e

## Steps to reproduce

1. Train booster on dense one hot encoded features. `booster_dense = xgb.train({'objective':'binary:logistic'}, xgb.DMatrix(x_train_dense, y_train), num_boost_round=10)`
2. Call `get_dump(dump_format='json')` and look at split decision. All split_condition should be .5.
3. Train booster on sparse CSR matrix of same OHE features.
4. Call `get_dump(dump_format='json')` now all split_conditions are -9.53674e-07, which is a value that doesn't exist in features. All features are either 0 or 1 so this would cause every split to take the `no` path.

Here is a minimal example that demonstrates the issue https://gist.github.com/volker48/268e1c4cdb220c5c94f750f11ea07e1d

**Comment by khotilov** [comment]
see #2285
