### ISSUE TITLE
[jvm-packages] create_jni.py rebuilds lib/libxgboost.so

### ISSUE THREAD

**Issue by edi-bice** [dmlc/xgboost#2738]
I built the xgboost shared library against Intel MKL, and then proceeded to create the JNI library only to find out the that create_jni.py rebuilds the xgboost shared library. I've tried to add the same compiler and linker switches to the cmake build system but it's not nearly as easy as it is for make.

Is it possible to create the JNI library without rebuilding the shared library?

**Comment by superbobry** [comment]
Were you using `make` for the first build?

**Comment by edi-bice** [comment]
@superbobry Yes I was. Had added the Intel MKL Link Line Advisor output to the CCFLAGS and LDFLAGS lines in the Makefile. Couldn't figure out where to do the same sort of thing for Cmake. Eventually figured it out.

--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -10,7 +10,12 @@ if(PLUGIN_UPDATER_GPU)
   find_package(CUDA REQUIRED)
 endif()

-set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")
+set(MKL_C_FLAGS "-DMKL_ILP64 -m64 -I/opt/intel/mkl/include")
+set(MKL_CXX_FLAGS ${MKL_C_FLAGS})
+set(MKL_EXE_LINKER_FLAGS "-L/opt/intel/mkl/lib/intel64 -Wl,--no-as-needed -lmkl
+set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS} ${MKL_CXX_FLAGS}")
+set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} ${MKL_EXE_LINKER_FL
+set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${MKL_EXE_LINKER_FLAGS}")

**Comment by superbobry** [comment]
Alternatively, you could've set CFLAGS and CPPLAGS env. variables before building the JVM package.

**Comment by khotilov** [comment]
@edi-bice do you mind asking why do you want to link to MKL? As far as I can tell, XGBoost does not currently do any calculations that would benefit from it.

**Comment by edi-bice** [comment]
@khotilov I was linking R, numpy/scipy etc. against MKL and it spilled into XGBoost. Wasn't sure about linear algebra but XGBoost does use OpenMP which Intel MKL supports and I thought would provide some benefits.

**Comment by edi-bice** [comment]
I suppose it makes more sense that either build system (make or cmake) does not assume anything and build from scratch.
