### ISSUE TITLE
XGBoost installation error in Windows 10 with python-package

### ISSUE THREAD

**Issue by ebonat** [dmlc/xgboost#2739]
## Environment info
Operating System: Windows 10

Procedures:

1. Get the python-package repository from https://github.com/dmlc/xgboost/tree/master/python-package in put it in C:\XGBoost\python-package.

2. Run: python C:\XGBoost\python-package\setup.py install

3. Got the following error:

Traceback (most recent call last):
  File "C:\XGBoost\python-package\setup.py", line 19, in <module>
    LIB_PATH = [os.path.relpath(libfile, CURRENT_DIR) for libfile in libpath['find_lib_path']()]
  File "C:\XGBoost\python-package\xgboost/libpath.py", line 49, in find_lib_path
    'List of candidates:\n' + ('\n'.join(dll_path)))
XGBoostLibraryNotFound: Cannot find XGBoost Library in the candidate path, did you install compilers and run build.sh in root path?
List of candidates:
C:\XGBoost\python-package\xgboost\xgboost.dll
C:\XGBoost\python-package\xgboost\../../lib/xgboost.dll
C:\XGBoost\python-package\xgboost\./lib/xgboost.dll
C:\Users\Ernest\AppData\Local\Continuum\xgboost\xgboost.dll
C:\XGBoost\python-package\xgboost\../../windows/x64/Release/xgboost.dll
C:\XGBoost\python-package\xgboost\./windows/x64/Release/xgboost.dll

Where is the xgboost.dll file?

Thank you for your help.

-Ernest

**Comment by khotilov** [comment]
Please follow the installation instructions from https://xgboost.readthedocs.io/en/latest/build.html
Also see https://github.com/dmlc/xgboost/issues/2575#issuecomment-320383167
