### ISSUE TITLE
After successful build that is after creating xgboost.exe and libxgboost.dll: ERROR "Cannot find XGBoost Library in the candidate path, did you install compilers and run build.sh in root path" is coming while running setup.py

### ISSUE THREAD

**Issue by adarshpatankar28** [dmlc/xgboost#2741]
Operating System:
Windows 7
Compiler:
mingw64
Package used (python/R/jvm/C++):
python 2.7

1. Traceback (most recent call last):
File "C:\XGBoost\python-package\setup.py", line 19, in 
LIB_PATH = [os.path.relpath(libfile, CURRENT_DIR) for libfile in libpath'find_lib_path']
File "C:\XGBoost\python-package\xgboost/libpath.py", line 49, in find_lib_path
'List of candidates:\n' + ('\n'.join(dll_path)))
XGBoostLibraryNotFound: Cannot find XGBoost Library in the candidate path, did you install compilers and run build.sh in root path?
List of candidates:
C:\XGBoost\python-package\xgboost\xgboost.dll
C:\XGBoost\python-package\xgboost../../lib/xgboost.dll
C:\XGBoost\python-package\xgboost./lib/xgboost.dll
C:\Users\Ernest\AppData\Local\Continuum\xgboost\xgboost.dll
C:\XGBoost\python-package\xgboost../../windows/x64/Release/xgboost.dll
C:\XGBoost\python-package\xgboost./windows/x64/Release/xgboost.dll

**Comment by khotilov** [comment]
How did you manage to build libxgboost.dll on windows instead of xgboost.dll? Are you using the recent code?
