### ISSUE TITLE
support qid format like ranklib for ranking task

### ISSUE THREAD

**Issue by liuliang01** [dmlc/xgboost#2748]
for ranking problem, we have group files for split query-session. 
But the group file seams only for single machine, not for row split distributed environment. 
Can we add one 'qid' column like ranklib ?

src-code：src/data/data.cc
// backward compatiblity code.
  if (!load_row_split) {
    MetaInfo& info = dmat->info();
    if (MetaTryLoadGroup(fname + ".group", &info.group_ptr) && !silent) {
      LOG(CONSOLE) << info.group_ptr.size() - 1
                   << " groups are loaded from " << fname << ".group";
    }

**Comment by superbobry** [comment]
👍 This, unlike the current group data format, would allow distributing ranking on Spark.
