### ISSUE TITLE
Any guide on choose parameters  ? 

### ISSUE THREAD

**Issue by StevenLOL** [dmlc/xgboost#275]
I download the latest xgboost , and work on a multi-class (50 classes) classification problem based on  demo at ./xgboost-master/demo/multiclass_classification/train.py

After 50 round , error on the training set(16K x 200) hits 0.000%  but  error on the evaluation data(6K x 200) is 91%.

Then I split the training set into training and eval set (8K each) , and retrain the system, get the same result, to say very low error% on the training set and very high error% on the evaluation set.

Similar result (very high error% on evaluation set ) obtained by using XGBClassifier 

xgb.XGBClassifier()
xgb.fit(....)

I wonder if there are any guide on tuning parameters rather than GridSearch?

**Comment by tqchen** [comment]
this is an ongoing  note: https://github.com/dmlc/xgboost/blob/master/doc/param_tuning.md

**Comment by StevenLOL** [comment]
Thanks

**Comment by sdenel** [comment]
@tqchen The link is dead, I suppose the new one is: https://github.com/dmlc/xgboost/blob/master/doc/how_to/param_tuning.md
