### ISSUE TITLE
[HELP] XGBOOST-CUDA Error when compilling

### ISSUE THREAD

**Issue by wa1618i** [dmlc/xgboost#2750]
Ubuntu 16.04LTS: 
so after git cloning recursive, i did:
cd xgboost...cmake -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-9.0
it generates error:
lemma@lemma:~/xgboost$cmake -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-9.0
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Detecting C compile features
-- Detecting C compile features - failed
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Detecting CXX compile features
-- Detecting CXX compile features - failed
CMake Error at CMakeLists.txt:3 (include):
  include could not find load file:

    cmake/Utils.cmake

-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
CMake Error at CMakeLists.txt:6 (set_default_configuration_release):
  Unknown CMake command "set_default_configuration_release".

-- Configuring incomplete, errors occurred!
See also "/home/lemma/xgboost/build/CMakeFiles/CMakeOutput.log".
See also "/home/lemma/xgboost/build/CMakeFiles/CMakeError.log".

and then:
mkdir build...cd build...cmake -DUSE_CUDA=ON ..
it generates error:
lemma@lemma:~/xgboost/build$ cmake -DUSE_CUDA=ON ..
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Detecting C compile features
-- Detecting C compile features - failed
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Detecting CXX compile features
-- Detecting CXX compile features - failed
CMake Error at CMakeLists.txt:3 (include):
  include could not find load file:

    cmake/Utils.cmake

-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
CMake Error at CMakeLists.txt:6 (set_default_configuration_release):
  Unknown CMake command "set_default_configuration_release".

-- Configuring incomplete, errors occurred!
See also "/home/lemma/xgboost/build/CMakeFiles/CMakeOutput.log".
See also "/home/lemma/xgboost/build/CMakeFiles/CMakeError.log".

Some said that gcc 5 is too high so i downgrade by the following steps:
sudo nano make/config.mk
export CC = gcc-4.8
export CXX = g++-4.8
...still not helpful.

Cuda compilation tools, release 7.5, V7.5.17
NVIDIA-SMI 384.81                 Driver Version: 384.81
CuDNN v-6.0 and CUDA-8.0

**Comment by RAMitchell** [comment]
What are your CC/CXX flags set to normally? Changing these flags in make/config.mk will have no effect on the cmake build. You will have to change these in such a way that cmake knows about it.

**Comment by RAMitchell** [comment]
I am marking this closed as no response.
