### ISSUE TITLE
XGBoost Regression Accuracies Worst with gpu_hist, Slower with gpu_exact

### ISSUE THREAD

**Issue by saj1919** [dmlc/xgboost#2754]
I wanted to run xgb faster .. so I chose to go with gpu.
But I am getting disappointing results and accuracies. I thought same parameters would work and I have to just change the `tree_update` method. But not the case.

Following parameters are used commonly for all experiments.
```
params = {}
params["objective"] = "reg:linear"
params["booster"] = "gbtree"
params["eval_metric"] = "rmse"
params["eta"] = 0.05
params["subsample"] = 0.25
params["silent"] = 0
params["max_depth"] = 15
params["alpha"] = 0.001
params["min_child_weight"] = 10
param_list = list(params.items())
num_rounds = 100
```
Keeping above constant, I just changed the tree_method. 
Following are the results. 

```
Time : 30 sec.
params["tree_method"] = “gpu_hist" 
[0]	train-rmse:0.473405
[10]	train-rmse:0.283467
[20]	train-rmse:0.169742
[30]	train-rmse:26.6116
[40]	train-rmse:1039.72
[50]	train-rmse:627.03
[60]	train-rmse:441.193
[70]	train-rmse:303.379
[80]	train-rmse:1226.3
[90]	train-rmse:1257.13
[99]	train-rmse:897.348
```

```
Time : 1.5 min
params["tree_method"] = "hist" 
[0]	train-rmse:0.473405
[10]	train-rmse:0.283465
[20]	train-rmse:0.169748
[30]	train-rmse:0.101671
[40]	train-rmse:0.060921
[50]	train-rmse:0.036541
[60]	train-rmse:0.021971
[70]	train-rmse:0.013288
[80]	train-rmse:0.008154
[90]	train-rmse:0.005174
[99]	train-rmse:0.003641
```

```
Time : 5 mins
params["tree_method"] = “gpu_exact" 
[0]	train-rmse:0.473404
[10]	train-rmse:0.283459
[20]	train-rmse:0.169736
[30]	train-rmse:0.101651
[40]	train-rmse:0.060896
[50]	train-rmse:0.036505
[60]	train-rmse:0.021923
[70]	train-rmse:0.013223
[80]	train-rmse:0.008062
[90]	train-rmse:0.005052
[99]	train-rmse:0.003485
```

```
Time : 10 mins
params["tree_method"] = "exact"
[0]	train-rmse:0.473405
[10]	train-rmse:0.283465
[20]	train-rmse:0.169747
[30]	train-rmse:0.101668
[40]	train-rmse:0.060916
[50]	train-rmse:0.036533
[60]	train-rmse:0.021957
[70]	train-rmse:0.013269
[80]	train-rmse:0.00813
[90]	train-rmse:0.005141
[99]	train-rmse:0.003601
```

Now, not sure why 'gpu_exact' is slower than 'hist' and 'gpu_hist' not even converging.
Can someone explain and suggest ??
With gpu are there other parameters to be tuned ??

## Environment
aws, p2.xlarge
ubuntu
python 2.7

**Comment by RAMitchell** [comment]
It looks like you have discovered a bug. Can you please provide a minimal reproducible script and dataset and I will take a look.

**Comment by saj1919** [comment]
Hey, I will try to get some sample dataset (as I can not share complete dataset due to confidentiality) and script to reproduce the error. I will share soon. But in-between, any idea how and why it is happening?

**Comment by vladT0** [comment]
I have very similar issue, with options 'gpu_hist' it is working very fast, but gave me wrong results.

**Comment by snakers4** [comment]
Same here for me:
- AUC Score (Train): 0.978461
- AUC Score (Test): 0.498591 (essentially guessing by luck) - both for `gpu_hist` and `gpu_exact`, though `gpu_exact` requires much more GPU RAM

Params I use both for CPU and GPU

```
xgb1 = XGBClassifier(
 learning_rate = 0.1,
 n_estimators=100,
 max_depth=5,
 tree_method = 'gpu_exact',    
 min_child_weight=1,
 gamma=0,
 subsample=0.8,
 colsample_bytree=0.8,
 objective= 'binary:logistic',
 nthread=7,
 scale_pos_weight=1,
 silent = False,
 seed=27)
```

**Comment by patelprateek** [comment]
did you guys find a fix , i ran into the same issue , what version of cuda and xgboost are you running ?

**Comment by mayer79** [comment]
I stumbled over similar behaviour with XGBoost v 80.1 (R-Package) and CUDA 9.1. 

For certain combinations of the parameters, the GPU version does not seem to converge. In below example, e.g. set `min_child_weight = 0` and `lambda = 0` to see the effect vs CPU.
```
library(xgboost)

set.seed(11)
N <- 100000
p <- 2

X <- matrix(runif(N * p), ncol = p)
y <-  X[, 1] + X[, 2]

tr <- sample.int(N, N * 0.75)
dtrain <- xgb.DMatrix(X[tr,], label = y[tr])
dtest <- xgb.DMatrix(X[-tr,], label = y[-tr])
wl <- list(train = dtrain, test = dtest)

param <- list(objective = 'reg:linear', eval_metric = 'rmse', learning_rate = 0.05,
              tree_method = 'gpu_hist', lambda = 0,  min_child_weight = 0)

bst_gpu <- xgb.train(param, dtrain, watchlist = wl, nrounds = 50)

# Now without GPU
param[["tree_method"]] <- NULL
bst_cpu <- xgb.train(param, dtrain, watchlist = wl, nrounds = 50)

```

**Comment by hcho3** [comment]
@RAMitchell

**Comment by hcho3** [comment]
@mayer79 #3793 should fix it.
