### ISSUE TITLE
Failed to install xgboost on Ubuntu16.04

### ISSUE THREAD

**Issue by FengZiYjun** [dmlc/xgboost#2756]
## Environment info
Operating System: Ubuntu 16.04

Compiler:  g++ 5.4.0 

Package used (python/R/jvm/C++): Installation error before any package used

`xgboost` version used: The version I clone by "git clone --recursive https://github.com/dmlc/xgboost"

## Steps to reproduce

1. git clone --recursive https://github.com/dmlc/xgboost
2. cd xgboost
3. make -j4

## What have you tried?

1. upgrade g++ and gcc - useless
2.
3.

**Comment by superbobry** [comment]
Please provide the compilation log.
