### ISSUE TITLE
Stratified distributed DMatrix

### ISSUE THREAD

**Issue by edi-bice** [dmlc/xgboost#2758]
I have very few positive class samples but plenty of negative ones. Even after downsampling positives it needs to run in distributed mode. Running it on 10 nodes works okay but running it on 30 fails with "Check failed: !auc_error AUC: the dataset only contains pos or neg samples". Is there any way to control how DMatrix is distributed among the workers so that each one gets some positive class samples?

**Comment by superbobry** [comment]
If you're using Spark/Flink bindings, please add [jvm-packages] to the issue title.

**Comment by edi-bice** [comment]
@superbobry No, using python bindings and dmlc-submit to YARN cluster

**Comment by khotilov** [comment]
Split finding and AUC estimates would be rather poor when worker nodes get very few positive samples. From what you described, there seems to be ~100-200 of positive samples. Distributed training is not a good choice for that. I would just downsample to a manageable size.

**Comment by edi-bice** [comment]
Actually an order of magnitude more but I appreciate your comment. Would you happen to know how DMatrix is distributed among all the workers? Is each row picked randomly or are contiguous rows (chunks) assigned to each worker?  Any shuffling? I load the DMatrix data from LIBSVM format and that is in chronological order.
