### ISSUE TITLE
data format bug？

### ISSUE THREAD

**Issue by xxyy1** [dmlc/xgboost#2760]
python v0.6
data format：

0 1:514_ 2:2 3:2097152 4:9 5:-1 6:-1 7:0 8:0 9:0 10:0 11:0 12:0 13:0 14:Chrome 15:2
0 1:514_ 2:2 3:2097152 4:9 5:-1 6:-1 7:0 8:0 9:0 10:0 11:0 12:0 13:0 14:Safari 15:2

when run：
train_dm = xgb.DMatrix("0928/30")   ERROR：
XGBoostError: b'[14:23:35] src/data/./row_block.h:144: Check failed: offset.back() == value.size() || value.size() == 0 '

I find the error from the word “Safari” ，when i replace to other word ，this ok

数据格式，第十四列出错

**Comment by khotilov** [comment]
xgboost can only read data with numeric values
