### ISSUE TITLE
Trying to Install xgboost on my virtual env but getting error:  Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-a2yx42fo/xgboost/

### ISSUE THREAD

**Issue by tingli81** [dmlc/xgboost#2761]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System:
Mac OS version 10.12.6
Compiler:

Package used (python/R/jvm/C++):
Python
`xgboost` version used:
the latest using sudo pip install
If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`)
2. Logs will be helpful (If logs are large, please upload as attachment).

If you are using jvm package, please 

1. add [jvm-packages] in the title to make it quickly be identified
2. the gcc version and distribution

If you are using python package, please provide

1. The python version and distribution
2. The command to install `xgboost` if you are not installing from source
sudo pip install xgboost

If you are using R package, please provide

1. The R `sessionInfo()`
2. The command to install `xgboost` if you are not installing from source

## Steps to reproduce
Hi I tried installing XG boost on my virtual environment and I keep getting an error.  I saw another post and it said to install xcode and gcc and clang which I tried to follow.  I still get the following error.

~/Documents/Machine_Learning » sudo pip install xgboost  ting@Tings-MacBook-Pro

The directory '/Users/ting/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/ting/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting xgboost
  Downloading xgboost-0.6a2.tar.gz (1.2MB)
    100% |████████████████████████████████| 1.2MB 944kB/s
    Complete output from command python setup.py egg_info:
    rm -f -rf build build_plugin lib bin *~ */*~ */*/*~ */*/*/*~ */*.o */*/*.o */*/*/*.o xgboost
    clang-omp++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/learner.o src/learner.cc >build/learner.d
    /bin/sh: clang-omp++: command not found
    make: *** [build/learner.o] Error 127
    make: *** Waiting for unfinished jobs....
    clang-omp++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/logging.o src/logging.cc >build/logging.d
    /bin/sh: clang-omp++: command not found
    make: *** [build/logging.o] Error 127
    -----------------------------
    Building multi-thread xgboost failed
    Start to build single-thread xgboost
    rm -f -rf build build_plugin lib bin *~ */*~ */*/*~ */*/*/*~ */*.o */*/*.o */*/*/*.o xgboost
    clang-omp++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/learner.o src/learner.cc >build/learner.d
    /bin/sh: clang-omp++: command not found
    make: *** [build/learner.o] Error 127
    make: *** Waiting for unfinished jobs....
    clang-omp++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/logging.o src/logging.cc >build/logging.d
    /bin/sh: clang-omp++: command not found
    make: *** [build/logging.o] Error 127
    Successfully build single-thread xgboost
    If you want multi-threaded version
    See additional instructions in doc/build.md
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-a2yx42fo/xgboost/setup.py", line 29, in <module>
        LIB_PATH = libpath['find_lib_path']()
      File "/private/tmp/pip-build-a2yx42fo/xgboost/xgboost/libpath.py", line 45, in find_lib_path
        'List of candidates:\n' + ('\n'.join(dll_path)))
    XGBoostLibraryNotFound: Cannot find XGBoost Libarary in the candicate path, did you install compilers and run build.sh in root path?
    List of candidates:
    /private/tmp/pip-build-a2yx42fo/xgboost/xgboost/libxgboost.so
    /private/tmp/pip-build-a2yx42fo/xgboost/xgboost/../../lib/libxgboost.so
    /private/tmp/pip-build-a2yx42fo/xgboost/xgboost/./lib/libxgboost.so

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-a2yx42fo/xgboost/

1.
2.
3.

## What have you tried?

1.
2.
3.

**Comment by phunterlau** [comment]
Oh, the pip installation requires clang-omp, please install the latest gcc from brew and install from GitHub instead for now

**Comment by lenguyenthedat** [comment]
Try GCC5, works for me. More info: https://medium.com/@lenguyenthedat/installing-xgboost-on-os-x-1f63c1ed042

(Same error with GGC6)

**Comment by tingli81** [comment]
That seemed to do the trick.  Thanks a lot!
