### ISSUE TITLE
cannot compile with CUDA for R

### ISSUE THREAD

**Issue by LaithYZumot** [dmlc/xgboost#2763]
Operating System:  WIN 10 64 with CUDA 8 and 9

IN: git bash with as is checkin/out-

1. git clone --recursive https://github.com/dmlc/xgboost
2. cd xgboost
3. git submodule init
4. git submodule update

then 
IN: Visual C++ 2015 x64 Native Build tools command prompt

1. mkdir build
2. cd build
3. cmake .. -G"Visual Studio 14 2015 Win64" -DR_LIB=ON
4. cmake --build . --target install --config Release

builds and installs successfully with some warnings due to type conversions

but...

1. - cmake .. -G"Visual Studio 14 2015 Win64" -DR_LIB=ON -DUSE_CUDA=ON -DGPU_COMPUTE_VER=61
-- Found OpenMP_C: -openmp
-- Found OpenMP_CXX: -openmp
-- Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0 (found suitable version "9.0", minimum required is "7.5")
Error: unexpected end of input
Execution halted
-- Found R: C:/Program Files/R/R-3.4.1/bin/x64/R.exe
-- LIBR_CORE_LIBRARY C:/xgboost/build/R.lib
-- Configuring done
-- Generating done
-- Build files have been written to: C:/xgboost/build

then fails to build

2. - cmake --build . --target install --config Release
...
....
  Building Custom Rule C:/xgboost/nccl/CMakeLists.txt
  CMake is re-running because C:/xgboost/build/nccl/CMakeFiles/generate.stamp is out-of-date.
    the file 'C:/xgboost/build/nccl/CMakeFiles/nccl.dir/src/nccl_generated_all_gather.cu.obj.depend'
    is newer than 'C:/xgboost/build/nccl/CMakeFiles/generate.stamp.depend'
    result='-1'
CUSTOMBUILD : error : unexpected end of input [C:\xgboost\build\nccl\nccl.vcxproj]
  Execution halted
  -- Found R: C:/Program Files/R/R-3.4.1/bin/x64/R.exe
....
"C:\xgboost\build\install.vcxproj" (default target) (1) ->
"C:\xgboost\build\ALL_BUILD.vcxproj" (default target) (3) ->
"C:\xgboost\build\gpuxgboost.vcxproj" (default target) (5) ->
"C:\xgboost\build\nccl\nccl.vcxproj" (default target) (6) ->
(CustomBuild target) ->
  CUSTOMBUILD : error : unexpected end of input [C:\xgboost\build\nccl\nccl.vcxproj]

    299 Warning(s)
    1 Error(s)

......

so what exactly am i doing wrong? could it be an issue with CUDA version ( it gives same error if CUDA 8 used)

**Comment by LaithYZumot** [comment]
turns our havign rstudio installed causes a conflict.. removed it and reinstalled R 3.4.1 on root drive solved this but other problems such as 'cicc' died with status 0xC0000005 (ACCESS_VIOLATION) occured.

**Comment by khotilov** [comment]
I don't get it... how exactly could rstudio interfere here? 

At this time, I would advise to really pay attention to whether cmake finds R in a location that you would expect. The search procedure on windows is currently rather dumb: it reads hard-coded windows registry key https://github.com/dmlc/xgboost/blob/9a81c74a7bd8db06c2f2ccb28b88ffeecf4c0309/cmake/modules/FindLibR.cmake#L126
`-DLIBR_EXECUTABLE=c:/asd/zxc/R.exe` could be passed to cmake with the R.exe that you want it to use.

To see the details of the error during cmake generation, use cmake's options  --debug-output --trace and save the output into a file.
I didn't yet install and try CUDA 9, so CUDA 8 would be the safest bet.
