### ISSUE TITLE
Crash when xgb.cv is run for some time with GPU support

### ISSUE THREAD

**Issue by thusithaC** [dmlc/xgboost#2769]
Hi, 

I'm running with GPU support on, and the system crashes *sometimes* with the following message. (Logs attached)
python': malloc(): smallbin double linked list corrupted

Configuration: 
        'gpu_id': 0,
        'max_bin': 16,
        'tree_method': 'gpu_hist',

## Environment info
Operating System:
Ubuntu 16.04.1
Compiler:
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5) 

nvcc: NVIDIA (R) Cuda compiler driver
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61

Package used (python/R/jvm/C++):
python
`xgboost` version used:
xgboost-0.6-py3.6.

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`)
9a81c74a7bd8db06c2f2ccb28b88ffeecf4c0309
2. Logs will be helpful (If logs are large, please upload as attachment).

If you are using jvm package, please 

1. add [jvm-packages] in the title to make it quickly be identified
2. the gcc version and distribution

If you are using python package, please provide

1. The python version and distribution
Anaconda, Python 3.6
2. The command to install `xgboost` if you are not installing from source
(from source)

## Steps to reproduce
Extremely difficult, happens randomly after a long run. 

## What have you tried?

Any advice? Not sure what to try even. 

[error.txt](https://github.com/dmlc/xgboost/files/1359996/error.txt)

**Comment by RAMitchell** [comment]
According to the stack trace the issue originated from gnu parallel sort during the AUC metric calculation. Does the error still occur if you use the 'error' evaluation metric instead of AUC?

**Comment by thusithaC** [comment]
Well, I think I'm one of those affected by the not so rare AMD Ryzen bug where when stressed, programs segfault randomly. I bricked my mobo trying to get a new version of the BIOS. Finally got the RMA and tested the code after disabling opcache and SMT. So far so good.. Have been running the same code close to an hour and no segfaults yet :)
