### ISSUE TITLE
Save the best model through all the learning

### ISSUE THREAD

**Issue by erogol** [dmlc/xgboost#277]
Is there any way to save the best eval-loss model through all the learning steps? I tried to use Eraly-Stopping but I guess it just compares the best value in the given window instead of the best model loss.

**Comment by yzliao** [comment]
Hi, @erogol  I had the similar issue before. To predict by using the best tree, you can use following command:

```python
ypred = bst.predict(xgmat,ntree_limit=bst.best_iteration)
```

Please note that when you save the model, `bst.best_iteration` will not be saved. My approach is dumping the training history to txt file and then find the best iteration number from the history.

**Comment by tqchen** [comment]
There is a recent change to make xgboost pickable. I think this will save everything in the booster class. So you can try to pickle the xgb.Booster instead of using save_model, note that the saved model will not be readable by other versions(R, CLI)

**Comment by yzliao** [comment]
Good to know. Thank you @tqchen
