### ISSUE TITLE
External memory not working

### ISSUE THREAD

**Issue by EvanzzzZ** [dmlc/xgboost#2770]
I am trying the external memory feature on xgboost, I am using the a machine with 200 gb memory to run part of the data set which is 80g. After finishing writing cache file to the disk, it looks like it still loads all the data in the memory, and the memory drain out very soon. And the machine became not responding. 

Is there anything I missed? I just add '#' after the file path.

Tried it with another data set around 90g, and that works. 
The difference here is, the 90g data set have multiple partitions files, while the 80g data is one big file.
Will this affect the external memory feature ?

**Comment by superbobry** [comment]
Are you using R/Python or JVM?

**Comment by EvanzzzZ** [comment]
Sorry, using python

**Comment by khotilov** [comment]
What are your xgboost parameters, particularly, the `tree_method`?

**Comment by EvanzzzZ** [comment]
Using 'auto'. It will use 'approximate' based on the size of data set.
