### ISSUE TITLE
Possible bug in DMatrix.__init__

### ISSUE THREAD

**Issue by pavellevap** [dmlc/xgboost#2771]
https://github.com/dmlc/xgboost/blob/9a81c74a7bd8db06c2f2ccb28b88ffeecf4c0309/python-package/xgboost/core.py#L286

https://github.com/dmlc/xgboost/blob/9a81c74a7bd8db06c2f2ccb28b88ffeecf4c0309/python-package/xgboost/core.py#L291

Hi
There should be `label` and `weight` instead of `data`, isn't it?

**Comment by khotilov** [comment]
Yes, it looks so.
