### ISSUE TITLE
XGBoostError: src/predictor/predictor.cc:55: Unknown predictor type gpu_predictor'

### ISSUE THREAD

**Issue by felipeeeantunes** [dmlc/xgboost#2783]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System: Windows 10 64Bits 

Compiler: 

Package used (python/R/jvm/C++): Python

`xgboost` version used: 0.16

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`): ff9180cd73f21c21b8852b010dd664966bb00970
2. Logs will be helpful (If logs are large, please upload as attachment).

If you are using jvm package, please 

1. add [jvm-packages] in the title to make it quickly be identified
2. the gcc version and distribution

If you are using python package, please provide

1. The python version and distribution: 3.5 Anaconda
2. The command to install `xgboost` if you are not installing from source

If you are using R package, please provide

1. The R `sessionInfo()`
2. The command to install `xgboost` if you are not installing from source

## Steps to reproduce

space ={
    'booster '    : 'gbtree',       
    'objective'   : 'binary:logistic',
    'eval_metric' : 'auc',
    'max_depth'   : hp.choice("max_depth",        np.arange(4, 7,    dtype=int)),  
    'tree_method' : 'gpu_exact',
    'alpha'            : hp.uniform('alpha', 1e-6, 1e-4 ),
    'lambda'           : hp.uniform('lambda', 1e-6, 1e-4 ),
    'subsample'        : hp.uniform('subsample',0.6, 0.9),
    'min_child_weight ': hp.uniform('min_child_weight', 0.6, 0.8),
    'learning_rate'    : hp.uniform('learning_rate', 1e-3, 1e-2),
    
    'seed'            : hp.randint('seed',2000000)
   }
xgb_params = sample(space)
gbm_model = xgb.train(
                        xgb_params,
                        xgb_train,
                        num_boost_round=10,
                        # metrics='mlogloss',
                        # valid_names=None,
                        # fobj=None,
                        # init_model=None,
                        # feature_name='auto',
                        # categorical_feature='auto',
                        # early_stopping_rounds=None,
                        # evals_result=None,
                        verbose_eval=False
                        # learning_rates=None,
                        # keep_training_booster=False,
                        # callbacks=None)
                         )

## What have you tried?

1. Reinstall from source
2. Change gpu_exact to gpu_hist
3. Google it

**Comment by 3v1l91l** [comment]
It seems that though cmake setting "PLUGIN_UPDATER_GPU" is deprecated it is still used in 
make/config.mk to determine if plugin/updater_gpu/plugin.mk should be added.

As a workaround try 
`$ cmake .. -DPLUGIN_UPDATER_GPU=ON`

**Comment by lorenzoridolfi** [comment]
I'm having the same issue with Fedora 26. I cloned xgboost from git  and I got the same problem. I did run CMAKE with -DPLUGIN_UPDATER_GPU=ON. Everything compiled ok.
 
When I run the benchmark.py in the tests folder, I got this message:

Training with 'gpu_hist'
[11:33:29] /root/xgboost/dmlc-core/include/dmlc/./logging.h:300: 
[11:33:29] /root/xgboost/src/predictor/predictor.cc:55: Unknown predictor type gpu_predictor

Best regards,
Lorenzo

**Comment by RAMitchell** [comment]
The error 'Unknown predictor type gpu_predictor' indicates that XGBoost has not been installed with GPU support. If you are able to successfully compile with GPU support please check that this was installed correctly and that there are no other existing versions of XGBoost on your system.
