### ISSUE TITLE
CMake calls incorrect CC/CXX in nccl when compiling GPU R package

### ISSUE THREAD

**Issue by SteveBronder** [dmlc/xgboost#2787]
## Summary

Attempting to install from source with GPU support on Ubuntu 17.04 with cuda-8.0 fails due to 
```
/usr/include/host_config.h:119:2: error: #error -- unsupported GNU version! gcc versions later than 5 are not supported!
 #error -- unsupported GNU version! gcc versions later than 5 are not supported!
```
when building files in nccl even after switching through compilers earlier and later than 5

## Environment info
Operating System: Ubuntu 17.04 64-bit

Compiler:
gcc/g++ 4.7, 4.8, 4.9, and 6.3
nvcc: 8.0
Built on Sun_Sep__4_22:14:01_CDT_2016
Cuda compilation tools, release 8.0, V8.0.44

Package used (python/R/jvm/C++): R

`xgboost` version used: Development

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`)
`78c4188cec31425f708d238160ea3afb67a7250a
`
2. Logs will be helpful (If logs are large, please upload as attachment).
https://gist.github.com/SteveBronder/1eac271dc892fbe1c9669e22f4b0d737

## Steps to reproduce
```
git clone --recursive https://github.com/dmlc/xgboost
cd xgboost
mkdir build
cd build
cmake .. -DUSE_CUDA=ON -DR_LIB=ON
make install -j
```
## What have you tried?

1. Multiple compilers, setting my global and local gcc/g++ to < 5
2. I've tried searching through where CC/CXX could be overwritten later, but have not seen anywhere.

If this is a U2K error (user to keyboard) I apologize

**Comment by khotilov** [comment]
CUDA 8.0 does not support gcc >= 6.  CUDA 9.0 supports gcc 6.3, but it wasn't really tested with xgboost yet.

Did you try passing something like `-DCUDA_HOST_COMPILER=/usr/bin/gcc-4.9` to cmake.

**Comment by SteveBronder** [comment]
Yes awesome!! Now that it compiles I'm getting a separate error during the R install process. Will make a separate issue for that
