### ISSUE TITLE
How to manually Calculate the probability generated by predict function?

### ISSUE THREAD

**Issue by kizgel** [dmlc/xgboost#2792]
Recently, I have used `xgboost` package in `python` to do some machine learning tasks, and an issue occurred: many predict probabilities are almost the same. After some searches, `max_depth` may be so small or some reasons else. But now, I am very curious about another question: how the probability generated by `predict ` function.

## Environment info
Operating System: Windows 7

Compiler: spyder

Package used (python/R/jvm/C++): python 

`xgboost` version used: 0.6

I will use `iris' data to explain what I have tried.

## Steps to reproduce

1. do binary classification, so change some codes.
```
from sklearn import datasets
iris = datasets.load_iris()
data = iris.data[:100]
label = iris.target[:100]
```
2. train and test data
```
from sklearn.cross_validation import train_test_split
train_x, test_x, train_y, test_y = train_test_split(data, label, random_state=0)
```
3. establish `xgboost` model
```
import xgboost as xgb
dtrain=xgb.DMatrix(train_x,label=train_y)
dtest=xgb.DMatrix(test_x)

params={'booster':'gbtree',
	'objective': 'binary:logistic',
	'eval_metric': 'auc',
	'max_depth':4,
	'lambda':10,
	'subsample':0.75,
	'colsample_bytree':0.75,
	'min_child_weight':2,
	'eta': 0.025,
	'seed':0,
	'nthread':8,
     'silent':1}

watchlist = [(dtrain,'train')]


bst=xgb.train(params,dtrain,num_boost_round=100,evals=watchlist)


ypred=bst.predict(dtest)

y_pred = (ypred >= 0.5)*1

from sklearn import metrics

print 'ACC: %.4f' % metrics.accuracy_score(test_y,y_pred)
print 'Recall: %.4f' % metrics.recall_score(test_y,y_pred)
print 'F1-score: %.4f' %metrics.f1_score(test_y,y_pred)
print 'Precesion: %.4f' %metrics.precision_score(test_y,y_pred)
metrics.confusion_matrix(test_y,y_pred)
```

And the output is very nice, no sample is classified wrongly.

Next, I want to know **How to Calculate the probability generated by predict function**?

## What have you tried?

1. from `predict` function, I can know every leaf of 100 trees 
```
ypred_leaf = bst.predict(dtest, pred_leaf=True)
print ypred_leaf
```

```
[[1 1 1 ..., 1 1 1]
 [2 2 2 ..., 2 2 2]
 [1 1 1 ..., 1 1 1]
 ..., 
 [1 1 1 ..., 1 1 1]
 [2 2 2 ..., 2 2 2]
 [1 1 1 ..., 1 1 1]]
```
2. from each tree, I can get the leaf value
`xgb.to_graphviz(bst, num_trees=0)`

```
if f3 < 0.75:
   leaf = -0.019697
else:
   leaf = 0.0214286
```

And the features are renamed as f1, f2 and so on, Does the f(i) begin from 0 or 1? 
3. output `predict` score
`print ypred` 

```
[ 0.20081411  0.80391562  0.20081411  0.80391562  0.80391562  0.80391562
  0.20081411  0.80391562  0.80391562  0.80391562  0.80391562  0.80391562
  0.80391562  0.20081411  0.20081411  0.20081411  0.20081411  0.20081411
  0.20081411  0.20081411  0.20081411  0.80391562  0.20081411  0.80391562
  0.20081411]
```

So, my question is: according to the leaf value, how do I calculate the predicted values, like `ypred`?

**Comment by kizgel** [comment]
And I already have done some google and read some issues, for binary classification tasks, it may be calculated by equation: `1+(1+exp(value))`. 

But `1+(1+exp(-0.019697))` !=` 0.20081411`, so what does the leaf value means and how to manually calculate the probabilities?

**Comment by khotilov** [comment]
Leaf values from all the trees need to be added together before the logistic transform. Technically, there is also a `logit(base_score)` term, but it is zero with the default base_score=0.5
