### ISSUE TITLE
xgboost failling to install from repo

### ISSUE THREAD

**Issue by SaucePan1** [dmlc/xgboost#2793]
Hi, I´m following the instalation guide but I get the following error.

~>cp make/mingw64.mk config.mk; make -j4
cp: target "-j4" must exist
Usage: cp [-acfimpPqrRSv] file1 [file2 ...] target

Any idea on how to solve this?

--------------------------------------

Operating System:  Windows 10 Enterprise

**Comment by khotilov** [comment]
Something seems messed up with your system. What shell are you rining it from? And where is `cp` from?
```
where cp
which cp
```
