### ISSUE TITLE
xgboost weight:   does scale_pos_weight and  case_weight work at the same time? 

### ISSUE THREAD

**Issue by wuhuiIOS** [dmlc/xgboost#2797]
xgboost weight:   does scale_pos_weight and  case_weight work at the same time? 

if not, which is prioritized？

**Comment by khotilov** [comment]
They work at the same time. For positive cases, weight would be `scale_pos_weight * case_weight`

**Comment by khotilov** [comment]
One more thing: they work at the same time when computing the objective. However, the `hist` updater is currently using only `case_weight` when building its histograms.
