### ISSUE TITLE
The fit method in XGBRegressor (Sklearn API) doesn't support the xgb_model param

### ISSUE THREAD

**Issue by HarkDev** [dmlc/xgboost#2801]
While trying to FIT a previously trained model using the Sklearn API of XGBClassifier i got the following error:

`TypeError: fit() got an unexpected keyword argument 'xgb_model'`

But on the XGBoost documentation for the XGBClassifier it states:

> xgb_model (str) – file name of stored xgb model or ‘Booster’ instance Xgb model to be loaded before training (allows training continuation).
> http://xgboost.readthedocs.io/en/latest/python/python_api.html

This is how to reproduce the error:
```
# File to save the model
xgb_file = 'xgb_trained.xgb'

# Instantiate the model
model = XGBClassifier()

# Fit the model
model.fit(x, y)

# Save the model
model._Booster.save_model(xgb_file)

# Fit the model passing 
model.fit(new_x, new_y, xgb_model=xgb_file)
```

The last line throws the following error:

> TypeError: fit() got an unexpected keyword argument 'xgb_model'

**Comment by khotilov** [comment]
This was added recently. Please use the current xgboost code from github.

**Comment by HarkDev** [comment]
No pip package to upgrade yet?
