### ISSUE TITLE
I Can Determine Feature Importance, Can I determine WHY They're Important?

### ISSUE THREAD

**Issue by jaradc** [dmlc/xgboost#2802]
My question is more conceptual in nature. We can determine which features are most important but is there a way we can determine if they positively or negatively help predict the response variable (y) ?

For example, the code below shows that feature `f19` has the highest F Score. It could be high because of what it predicts OR doesn't predict... but we don't know why it's important.

**Is there a common technique to determine why a feature is important with XGBoost (or decision trees in general)?**

## Example Code

```
from xgboost import XGBClassifier, plot_importance
from sklearn.datasets import make_classification
import matplotlib.pyplot as plt
X,y = make_classification(random_state=68)
xgb = XGBClassifier()
xgb.fit(X, y)
plot_importance(xgb)
plt.show()
```

**Comment by bbennett36** [comment]
Check out SHAP. I'm on mobile so I can't get you any links but just Google
SHAP xgboost. The creator of SHAP just pushed some new code for it I think
and he also has a package where you can get all the info you are looking
for.

**Comment by bbennett36** [comment]
@jaradc Here you go
https://github.com/slundberg/shap
Paper - https://arxiv.org/pdf/1706.06060.pdf
https://github.com/dmlc/xgboost/pull/2438
