### ISSUE TITLE
Error running foreach loop with xgboost

### ISSUE THREAD

**Issue by martinju** [dmlc/xgboost#2812]
Hi

Is it possible to run xgboost inside a parallelized foreach-loop? The reason I want to do this instead of increasing the nthread parameter is that some performance tests (on different data, with more cores and with the hist-approach) suggets I do not get a speed increase when using more than about half my physical cores. 

The below simple working example reproduces the error and fails with "Error in unserialize(socklist[[n]]) : error reading from connection"

```
library(xgboost)
library(foreach)
library(doParallel)

data(agaricus.train, package='xgboost')
train <- xgb.DMatrix(agaricus.train$data,label=agaricus.train$label)

cl <- makeCluster(2)
registerDoParallel(cl)
  
  xgb.mod <- foreach(j =1:2,.packages="xgboost") %dopar% {
    set.seed(11111)
    mod <- xgb.train(data = train,
                     nrounds = 10,
                     verbose = 2,
                     nthread = 1)
  }
```

Is what I try to do at all possible, or would I need to run multiple R sessions or so?

I am on windows, and have tried with both the development version and the CRAN-version of xgboost. Using the doMC-package on Linux gave a similar error.

Here is my R session info:
```
  > sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Norwegian Bokmål_Norway.1252  LC_CTYPE=Norwegian Bokmål_Norway.1252    LC_MONETARY=Norwegian Bokmål_Norway.1252
[4] LC_NUMERIC=C                             LC_TIME=Norwegian Bokmål_Norway.1252    

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] doParallel_1.0.11 iterators_1.0.8   foreach_1.4.3     xgboost_0.6-4    

loaded via a namespace (and not attached):
 [1] compiler_3.4.2      magrittr_1.5        Matrix_1.2-11       tools_3.4.2         yaml_2.1.14         codetools_0.2-15   
 [7] stringi_1.1.5       grid_3.4.2          data.table_1.10.4-2 lattice_0.20-35    
> 
```

**Comment by khotilov** [comment]
The DMatrix has to be created within foreach. `train` contains simply a pointer, and not to a memory mapped file, so you cannot share it between processes.

**Comment by khotilov** [comment]
To clarify: my response above was based on the fact that the OP's OS was Windows, which doesn't have forking.

On linux/mac, a fork cluster would have access to parent's memory address space, and would be able to use a DMatrix defined outside of foreach (which would save memory). It would need to be started as either
```R
cl <- makeCluster(2, type = "FORK")
registerDoParallel(cl)
```
or 
```R
registerDoParallel(cores = 2) # defaults to FORK on non-windows
```
Keep in mind that with fork-parallelization one would most likely be limited to using `nthread = 1` (due to a known bug in gcc's OpenMP implementation), while nthread > 1 would be ok with PSOCK. Also, any code that is dependent on fork cluster-specific features would not work in windows.
