### ISSUE TITLE
For the bad case, can I know the key features that makes it bad ?

### ISSUE THREAD

**Issue by loverszhaokai** [dmlc/xgboost#2815]
My model works well on training and new data. 

When there is a bad case, can I know the **features** that make the case bad ?

**Comment by bbennett36** [comment]
https://github.com/slundberg/shap
https://arxiv.org/pdf/1706.06060.pdf - Paper on SHAP
#2438

Also, would look into the "gain" metric for feature importance. That should also have the info you need. From my understanding It's essentially how much "accuracy" the feature adds when that feature is present in a split.  
  
You can also print out the tree graphs to see how they are making the decisions and look at the value thresholds when it's making it "bad".

**Comment by loverszhaokai** [comment]
@bbennett36, Thanks for your SHAP. 
> When there is a bad case, can I know the features that make the case bad ?
Can I know which leaves that make the case bad ? I there any feature support this ?
