### ISSUE TITLE
GPU crash in compressed iterator line 195

### ISSUE THREAD

**Issue by pseudotensor** [dmlc/xgboost#2824]
@RAMitchell 
```
X = [[1],[1],[1],[1],[1] ,[1] ,[1] ,[1] ,[1] ,[1]]
y = [  7.58581800e-02,   5.00000000e-01 ,  9.99447221e-01,   4.53978687e-05,    9.99954602e-01,   9.99447221e-01 ,  9.24141820e-01 ,  9.24141820e-01,    9.93307\
149e-01 ,  5.00000000e-01]
params = {'tree_method': 'gpu_hist'}
import xgboost as xgb
model = xgb.XGBRegressor(**params)
model.fit(X,y)
```
[19:19:51] /home/jon/h2o4gpu/xgboost/dmlc-core/include/dmlc/././logging.h:300: [19:19:51] /home/jon/h2o4gpu/xgboost/src/tree/updater_gpu_hist.cu:301: GPU plugin exception: /home/jon/h2o4gpu/xgboost/src/tree/../common/device_helpers.cuh(96): an illegal memory access was encountered

Stack trace returned 10 entries:
[bt] (0) /home/jon/.pyenv/versions/3.6.1/lib/python3.6/site-packages/xgboost/libxgboost.so(_ZN4dmlc15LogMessageFatalD1Ev+0x3c) [0x7fc1528f1bbc]
[bt] (1) /home/jon/.pyenv/versions/3.6.1/lib/python3.6/site-packages/xgboost/libxgboost.so(_ZN7xgboost4tree12GPUHistMaker6UpdateERKSt6vectorINS_6detail18bst_gpair_internalIfEESaIS5_EEPNS_7DMatrixERKS2_IPNS_7RegTreeESaISD_EE+0x15e) [0x7fc152b25f0e]
[bt] (2) /home/jon/.pyenv/versions/3.6.1/lib/python3.6/site-packages/xgboost/libxgboost.so(_ZN7xgboost3gbm6GBTree13BoostNewTreesERKSt6vectorINS_6detail18bst_gpair_internalIfEESaIS5_EEPNS_7DMatrixEiPS2_ISt10unique_ptrINS_7RegTreeESt14default_deleteISD_EESaISG_EE+0x9ce) [0x7fc152997aae]
[bt] (3) /home/jon/.pyenv/versions/3.6.1/lib/python3.6/site-packages/xgboost/libxgboost.so(_ZN7xgboost3gbm6GBTree7DoBoostEPNS_7DMatrixEPSt6vectorINS_6detail18bst_gpair_internalIfEESaIS7_EEPNS_11ObjFunctionE+0xb50) [0x7fc152998ed0]
[bt] (4) /home/jon/.pyenv/versions/3.6.1/lib/python3.6/site-packages/xgboost/libxgboost.so(_ZN7xgboost11LearnerImpl13UpdateOneIterEiPNS_7DMatrixE+0x22b) [0x7fc1529a5dfb]
[bt] (5) /home/jon/.pyenv/versions/3.6.1/lib/python3.6/site-packages/xgboost/libxgboost.so(XGBoosterUpdateOneIter+0x27) [0x7fc1528e3ae7]
[bt] (6) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7fc17616be40]
[bt] (7) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x2eb) [0x7fc17616b8ab]
[bt] (8) /home/jon/.pyenv/versions/3.6.1/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2cf) [0x7fc1763adc4f]
[bt] (9) /home/jon/.pyenv/versions/3.6.1/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x8c19) [0x7fc1763a4c19]

Traceback (most recent call last):
  File "xgb.crash3.py", line 94, in <module>
    model.fit(X,y)
  File "/home/jon/.pyenv/versions/3.6.1/lib/python3.6/site-packages/xgboost/sklearn.py", line 294, in fit
    verbose_eval=verbose, xgb_model=xgb_model)
  File "/home/jon/.pyenv/versions/3.6.1/lib/python3.6/site-packages/xgboost/training.py", line 204, in train
    xgb_model=xgb_model, callbacks=callbacks)
  File "/home/jon/.pyenv/versions/3.6.1/lib/python3.6/site-packages/xgboost/training.py", line 74, in _train_internal
    bst.update(dtrain, i, obj)
  File "/home/jon/.pyenv/versions/3.6.1/lib/python3.6/site-packages/xgboost/core.py", line 1003, in update
    dtrain.handle))
  File "/home/jon/.pyenv/versions/3.6.1/lib/python3.6/site-packages/xgboost/core.py", line 130, in _check_call
    raise XGBoostError(_LIB.XGBGetLastError())
xgboost.core.XGBoostError: b'[19:19:51] /home/jon/h2o4gpu/xgboost/src/tree/updater_gpu_hist.cu:301: GPU plugin exception: /home/jon/h2o4gpu/xgboost/src/tree/../common/device_helpers.cuh(96): an illegal memory access was encountered\n\n\nStack trace returned 10 entries:\n[bt] (0) /home/jon/.pyenv/versions/3.6.1/lib/python3.6/site-packages/xgboost/libxgboost.so(_ZN4dmlc15LogMessageFatalD1Ev+0x3c) [0x7fc1528f1bbc]\n[bt] (1) /home/jon/.pyenv/versions/3.6.1/lib/python3.6/site-packages/xgboost/libxgboost.so(_ZN7xgboost4tree12GPUHistMaker6UpdateERKSt6vectorINS_6detail18bst_gpair_internalIfEESaIS5_EEPNS_7DMatrixERKS2_IPNS_7RegTreeESaISD_EE+0x15e) [0x7fc152b25f0e]\n[bt] (2) /home/jon/.pyenv/versions/3.6.1/lib/python3.6/site-packages/xgboost/libxgboost.so(_ZN7xgboost3gbm6GBTree13BoostNewTreesERKSt6vectorINS_6detail18bst_gpair_internalIfEESaIS5_EEPNS_7DMatrixEiPS2_ISt10unique_ptrINS_7RegTreeESt14default_deleteISD_EESaISG_EE+0x9ce) [0x7fc152997aae]\n[bt] (3) /home/jon/.pyenv/versions/3.6.1/lib/python3.6/site-packages/xgboost/libxgboost.so(_ZN7xgboost3gbm6GBTree7DoBoostEPNS_7DMatrixEPSt6vectorINS_6detail18bst_gpair_internalIfEESaIS7_EEPNS_11ObjFunctionE+0xb50) [0x7fc152998ed0]\n[bt] (4) /home/jon/.pyenv/versions/3.6.1/lib/python3.6/site-packages/xgboost/libxgboost.so(_ZN7xgboost11LearnerImpl13UpdateOneIterEiPNS_7DMatrixE+0x22b) [0x7fc1529a5dfb]\n[bt] (5) /home/jon/.pyenv/versions/3.6.1/lib/python3.6/site-packages/xgboost/libxgboost.so(XGBoosterUpdateOneIter+0x27) [0x7fc1528e3ae7]\n[bt] (6) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7fc17616be40]\n[bt] (7) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x2eb) [0x7fc17616b8ab]\n[bt] (8) /home/jon/.pyenv/versions/3.6.1/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2cf) [0x7fc1763adc4f]\n[bt] (9) /home/jon/.pyenv/versions/3.6.1/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x8c19) [0x7fc1763a4c19]\n'
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  /home/jon/h2o4gpu/xgboost/src/tree/updater_gpu_hist.cu(258): an illegal memory access was encountered

**Comment by RAMitchell** [comment]
Should be fixed in #2825
