### ISSUE TITLE
xgboost4j-spark local running on mac, stuck at last round

### ISSUE THREAD

**Issue by yeditor** [dmlc/xgboost#2829]
i'm running my xgboost4j-spark on local mac(just for verification). 
however it stuck on last round and when i play keyboard interrupt, it will print out result for last round, try on scala2.10+spark1.6 and scala2.11+spark2.1, just the same

log information………………………………………………………………………………………………
[18:44:27] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 30 extra nodes, 0 pruned nodes, max_depth=5
[4]	train-auc:0.708009
[5]	train-auc:0.712943
[18:44:27] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 30 extra nodes, 0 pruned nodes, max_depth=5
[6]	train-auc:0.712925
[18:44:28] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 30 extra nodes, 0 pruned nodes, max_depth=5
[7]	train-auc:0.712487
[18:44:28] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 30 extra nodes, 0 pruned nodes, max_depth=5
[18:44:29] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 32 extra nodes, 0 pruned nodes, max_depth=5
[8]	train-auc:0.730142
17/10/25 18:47:21 INFO RabitTracker$TrackerProcessLogger: Traceback (most recent call last):
17/10/25 18:47:21 INFO RabitTracker$TrackerProcessLogger:   File "/var/folders/4s/y_v1zckd511f2w8kvt1n7sq00000gn/T/tracker6381941480094325877.py", line 475, in <module>
17/10/25 18:47:21 INFO RabitTracker$TrackerProcessLogger:     main()
17/10/25 18:47:21 INFO RabitTracker$TrackerProcessLogger:   File "/var/folders/4s/y_v1zckd511f2w8kvt1n7sq00000gn/T/tracker6381941480094325877.py", line 470, in main
17/10/25 18:47:21 INFO RabitTracker$TrackerProcessLogger:     start_rabit_tracker(args)
17/10/25 18:47:21 INFO RabitTracker$TrackerProcessLogger:   File "/var/folders/4s/y_v1zckd511f2w8kvt1n7sq00000gn/T/tracker6381941480094325877.py", line 441, in start_rabit_tracker
17/10/25 18:47:21 INFO RabitTracker$TrackerProcessLogger:     rabit.join()
17/10/25 18:47:21 INFO RabitTracker$TrackerProcessLogger:   File "/var/folders/4s/y_v1zckd511f2w8kvt1n7sq00000gn/T/tracker6381941480094325877.py", line 331, in join
17/10/25 18:47:21 INFO RabitTracker$TrackerProcessLogger:     self.thread.join(100)
17/10/25 18:47:21 INFO RabitTracker$TrackerProcessLogger:   File "/Users/yuanyuan/anaconda2/envs/mypython/lib/python3.5/threading.py", line 1058, in join
17/10/25 18:47:21 INFO RabitTracker$TrackerProcessLogger:     self._wait_for_tstate_lock(timeout=max(timeout, 0))
17/10/25 18:47:21 INFO RabitTracker$TrackerProcessLogger:   File "/Users/yuanyuan/anaconda2/envs/mypython/lib/python3.5/threading.py", line 1070, in _wait_for_tstate_lock
17/10/25 18:47:21 INFO RabitTracker$TrackerProcessLogger:     elif lock.acquire(block, timeout):
17/10/25 18:47:21 INFO RabitTracker$TrackerProcessLogger: KeyboardInterrupt
17/10/25 18:47:21 INFO RabitTracker: Tracker Process ends with exit code 1
17/10/25 18:47:21 INFO RabitTracker$TrackerProcessLogger: Tracker Process ends with exit code 1
17/10/25 18:47:21 INFO XGBoostSpark: Rabit returns with exit code 1
Exception in thread "main" ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.train(XGBoost.scala:142)
	at xgb_spark_lr$.main(xgb_spark_lr.scala:64)
	at xgb_spark_lr.main(xgb_spark_lr.scala)
[9]	train-auc:0.734740

code……………………………………………………………………………………………………
`import ml.dmlc.xgboost4j.scala.spark.XGBoost
import org.apache.log4j.{Level, Logger}
import org.apache.spark.mllib.util.MLUtils
import org.apache.spark.mllib.regression.LabeledPoint
import org.apache.spark.mllib.linalg.Vectors
import org.apache.spark.SparkConf
import org.apache.spark.SparkContext

object xgb_spark_lr {
  def main(args: Array[String]): Unit = {
    Logger.getLogger("org.apache.spark").setLevel(Level.ERROR)
    Logger.getLogger("org.eclipse.jetty.server").setLevel(Level.OFF)
    val conf = new SparkConf().setAppName("simple").setMaster("local")
    val sc = new SparkContext(conf)
    val train = MLUtils.loadLibSVMFile(sc,"train_inputpath")
    val test = MLUtils.loadLibSVMFile(sc,"test_inputpath")

    val traindata = train.map { x =>
      val f = x.features.toArray
      val v = x.label
      LabeledPoint(v, Vectors.dense(f))
    }

    val testdata = train.map { x =>
      val f = x.features.toArray
      Vectors.dense(f)
    }

    val numRound = 10

    val paramMap = List(
      "eta" -> 0.08f,
      "max_depth" ->5,
      "silent" -> 0,
      "objective" -> "binary:logistic",
      "lambda"->2.5,
      "eval_metric" -> "auc",
      "colsample_bytree" -> 0.5,
      "subsample" -> 0.5,
      "nthread" -> 1
    ).toMap
    println(paramMap)

    traindata.map(_.features).foreach(println)
    val model = XGBoost.train(traindata, paramMap, numRound, nWorkers = 1, null, null, useExternalMemory = false)

    val result = model.predictLeaves(testdata)
    result.take(10).foreach(println)

    sc.stop();
  }
}

`
what is the matter?

**Comment by sethah** [comment]
If you use the Scala rabit tracker, then can you verify that it fails on its own (after some timeout interval) without pressing Ctrl-C?

I actually had some networking issues running the Spark package in local mode on a mac. The workers could not connect to the rabit tracker at <user>-MBP.local/10.0.0.10. It has no problem connecting to localhost/127.0.0.1, though.
