### ISSUE TITLE
[jvm-packages] Early stopping incorrectly splits data for ranking tasks

### ISSUE THREAD

**Issue by ebernhardson** [dmlc/xgboost#2832]
The new early stopping code in jvm-packages splits the dataset into test/train groups on a per-row basis. Because we have to provide the group data in a separate Seq[Seq[Int]] the group data is no longer correct after the test/train split. This prevents the usage of early stopping for ranking tasks.

Something like issue #2748 may provide a good way to support this in the future, although i still think users might want to make the choice between a completely arbitrary split (breaking up groups between test/train) and keeping whole groups in either test or train side of the split.

**Comment by superbobry** [comment]
Good catch! I agree that a good first step to address this is to get rid of the `Seq[Seq[Int]]` hack. As for groupwise sampling, this should be possible afterwards, because we would be able to repartition with groups in mind and then either accept or reject the whole group.
