### ISSUE TITLE
early-stopping info lost when model is saved to file?

### ISSUE THREAD

**Issue by kuo000** [dmlc/xgboost#284]
After I train a model with early stopping (early stopping does work) and save the model to file, the best_score and best_iteration attributes are gone when I load the model (BTW, I use Python.) afterwards.  Did I miss anything, or this might be a bug in saving a model trained with early stopping?

Thanks.

**Comment by tqchen** [comment]
Please see #273

**Comment by kuo000** [comment]
OK. I see. Thanks for the quick response. I'll try saving the train/valid history if I need to.
