### ISSUE TITLE
colsample_bylevel parameter does not affect

### ISSUE THREAD

**Issue by davutpolat** [dmlc/xgboost#2848]
i am using sparse data format and have 7000 sparse features, and got the parameters below.

param = {}
param['objective'] = 'reg:linear'
param['eta'] = 0.05
param['max_depth'] = 12
param['silent'] = 1
param['nthread'] = 32
param['subsample'] = 1.0
param['eval_metric'] = 'rmse'
param['min_child_weight'] = 25
param['colsample_bylevel'] = 0.001
param['colsample_bytree'] = 1.0
param['num_parallel_tree'] = 1
param['seed'] = 202

when i change colsample_bylevel parameter to 0.01, 0.1, 1.0 the results never changed. what am i missing ?

**Comment by BlindApe** [comment]
Hi Davut,
Seems related with #2047
set in param: 'tree_method' = exact

**Comment by Laurae2** [comment]
@BlindApe @davutpolat is not using `tree_method = hist` according to his parameters. Seems to be a more strange issue than mines.

**Comment by BlindApe** [comment]
@Laurae2 given the number of features probably xgboost 'auto' mode set to 'approx' that could have similar effect than 'hist' in subsampling columns.

**Comment by Laurae2** [comment]
@BlindApe `approx` uses the default `exact` code (with very minor differences) while `hist` uses a fully separate code during training. In `approx`, column sampling works properly (if you take my example in #2047, running it with `approx` or `exact` must yield the same results: different result per training, but same result whether you use `approx` or `exact`).
