### ISSUE TITLE
Pycharm shows ModuleNotFoundError: No module named 'xgboost',but ipython is correct

### ISSUE THREAD

**Issue by GuanglinZhou** [dmlc/xgboost#2853]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System:
Ubuntu 16.04LTS
Compiler:
Pycharm
Package used (python/R/jvm/C++):

python3.6.3
`xgboost` version used:
0.6
When I import xgboost in pycharm ,it shows that 
![screenshot from 2017-11-01 10-13-22](https://user-images.githubusercontent.com/20653159/32279514-56ab9a08-beef-11e7-8808-409f662da833.png)

when i use ipython,in works:
![Uploading Screenshot from 2017-11-01 10-13-22.png…]()

how can i solve it?Thanks

**Comment by yesanton** [comment]
Still no solution?

**Comment by Robert201806** [comment]
You should configure pycharm.
Settings--> Project-->Project Structure-->Add Content Root-->select <the/path/to/xgboost/python-package>(located where your xgboost is built) -->OK

**Comment by Robert201806** [comment]
This seems like that pycharm's project inerpreter configure does not load  system site packages.
I use pyvenv instead of virtualenv to build a virtual envirement, as 'pyvenv --system-site-packages env_xgb'.
It works for me.
