### ISSUE TITLE
Xgboost is not installing on aws instance on Linux

### ISSUE THREAD

**Issue by Alex19427** [dmlc/xgboost#2860]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System: Linux instance at aws 

Compiler: 

Package used (python/R/jvm/C++): Python2.7

`xgboost` version used: 0.60

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`)
2. Logs will be helpful (If logs are large, please upload as attachment).

If you are using jvm package, please 

1. add [jvm-packages] in the title to make it quickly be identified
2. the gcc version and distribution

If you are using python package, please provide

1. The python version and distribution
2. The command to install `xgboost` if you are not installing from source

If you are using R package, please provide

1. The R `sessionInfo()`
2. The command to install `xgboost` if you are not installing from source

## Steps to reproduce
1. Python2.7
2. anaconda2 - conda version 4.3.30
3.

## What have you tried?

1.pip install xgboost
2. conda install py-xgboost
And Many more commands but no use.

[Xgboost_logs.txt](https://github.com/dmlc/xgboost/files/1445814/Xgboost_logs.txt)

**Comment by Oreki47** [comment]
Did you sudo? Also what version of Linux are you using? I have worked with Ubuntu 14.04 and it worked out just fine. See this post:

https://oreki47.blog/2017/10/05/ec2-ml-environment-setup/
