### ISSUE TITLE
xgboost on yarn(单机hadoop)部署的问题

### ISSUE THREAD

**Issue by webzjuyujun** [dmlc/xgboost#2869]
17/11/09 19:09:59 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
17/11/09 19:09:59 INFO dmlc.ApplicationMaster: Start AM as user=yujun
17/11/09 19:09:59 INFO dmlc.ApplicationMaster: Try to start 0 Servers and 1 Workers
17/11/09 19:09:59 INFO client.RMProxy: Connecting to ResourceManager at /0.0.0.0:8030
17/11/09 19:09:59 INFO impl.NMClientAsyncImpl: Upper bound of the thread pool size is 500
17/11/09 19:09:59 INFO impl.ContainerManagementProtocolProxy: yarn.client.max-cached-nodemanagers-proxies : 0
17/11/09 19:09:59 INFO dmlc.ApplicationMaster: [DMLC] ApplicationMaster started
17/11/09 19:10:01 INFO impl.AMRMClientImpl: Received new token for : yujun-pc:34731
17/11/09 19:10:01 INFO dmlc.ApplicationMaster: {run_hdfs_prog.py=resource { scheme: "hdfs" port: -1 file: "/tmp/temp-dmlc-yarn-application_1510224989769_0003/run_hdfs_prog.py" } size: 1522 timestamp: 1510225798413 type: FILE visibility: APPLICATION, mushroom.hadoop.conf=resource { scheme: "hdfs" port: -1 file: "/tmp/temp-dmlc-yarn-application_1510224989769_0003/mushroom.hadoop.conf" } size: 76 timestamp: 1510225798438 type: FILE visibility: APPLICATION, xgboost=resource { scheme: "hdfs" port: -1 file: "/tmp/temp-dmlc-yarn-application_1510224989769_0003/xgboost" } size: 1878857 timestamp: 1510225798467 type: FILE visibility: APPLICATION, dmlc-yarn.jar=resource { scheme: "hdfs" port: -1 file: "/tmp/temp-dmlc-yarn-application_1510224989769_0003/dmlc-yarn.jar" } size: 21299 timestamp: 1510225798486 type: FILE visibility: APPLICATION}
17/11/09 19:10:01 INFO dmlc.ApplicationMaster: {PYTHONPATH=${PYTHONPATH}:., DMLC_NUM_SERVER=0, DMLC_NODE_HOST=yujun-pc, DMLC_ROLE=worker, DMLC_HDFS_OPTS=-Xmx128m, DMLC_TRACKER_URI=127.0.1.1, CLASSPATH=${CLASSPATH}:./*:$HADOOP_CONF_DIR:/home/yujun/software/hadoop-2.7.3/share/hadoop/common//hadoop-nfs-2.7.3.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common//hadoop-common-2.7.3-tests.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common//hadoop-common-2.7.3.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common//:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//hamcrest-core-1.3.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//jets3t-0.9.0.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//jsr305-3.0.0.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//snappy-java-1.0.4.1.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//commons-cli-1.2.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//jsch-0.1.42.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//protobuf-java-2.5.0.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//jackson-jaxrs-1.9.13.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//api-util-1.0.0-M20.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//commons-logging-1.1.3.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//servlet-api-2.5.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//httpclient-4.2.5.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//jersey-core-1.9.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//curator-framework-2.7.1.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//xmlenc-0.52.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//jackson-core-asl-1.9.13.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//jackson-xc-1.9.13.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//stax-api-1.0-2.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//log4j-1.2.17.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//curator-client-2.7.1.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//commons-codec-1.4.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//java-xmlbuilder-0.4.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//api-asn1-api-1.0.0-M20.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//htrace-core-3.1.0-incubating.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//jetty-6.1.26.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//commons-io-2.4.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//guava-11.0.2.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//jackson-mapper-asl-1.9.13.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//slf4j-api-1.7.10.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//commons-digester-1.8.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//jetty-util-6.1.26.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//apacheds-kerberos-codec-2.0.0-M15.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//activation-1.1.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//junit-4.11.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//slf4j-log4j12-1.7.10.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//commons-beanutils-core-1.8.0.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//httpcore-4.2.5.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//jsp-api-2.1.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//commons-math3-3.1.1.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//apacheds-i18n-2.0.0-M15.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//paranamer-2.3.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//mockito-all-1.8.5.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//commons-configuration-1.6.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//curator-recipes-2.7.1.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//hadoop-auth-2.7.3.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//jaxb-api-2.2.2.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//jaxb-impl-2.2.3-1.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//netty-3.6.2.Final.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//commons-net-3.1.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//gson-2.2.4.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//commons-httpclient-3.1.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//zookeeper-3.4.6.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//jersey-json-1.9.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//jersey-server-1.9.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//xz-1.0.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//asm-3.2.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//commons-collections-3.2.2.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//avro-1.7.4.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//jettison-1.1.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//hadoop-annotations-2.7.3.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//commons-compress-1.4.1.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//commons-beanutils-1.7.0.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//commons-lang-2.6.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/common/lib//:/home/yujun/software/hadoop-2.7.3/share/hadoop/hdfs//hadoop-hdfs-2.7.3.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/hdfs//hadoop-hdfs-nfs-2.7.3.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/hdfs//hadoop-hdfs-2.7.3-tests.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/hdfs//:/home/yujun/software/hadoop-2.7.3/share/hadoop/hdfs/lib//leveldbjni-all-1.8.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/hdfs/lib//jsr305-3.0.0.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/hdfs/lib//commons-cli-1.2.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/hdfs/lib//protobuf-java-2.5.0.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/hdfs/lib//commons-logging-1.1.3.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/hdfs/lib//servlet-api-2.5.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/hdfs/lib//jersey-core-1.9.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/hdfs/lib//xmlenc-0.52.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/hdfs/lib//jackson-core-asl-1.9.13.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/hdfs/lib//log4j-1.2.17.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/hdfs/lib//commons-codec-1.4.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/hdfs/lib//htrace-core-3.1.0-incubating.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/hdfs/lib//jetty-6.1.26.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/hdfs/lib//commons-io-2.4.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/hdfs/lib//guava-11.0.2.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/hdfs/lib//jackson-mapper-asl-1.9.13.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/hdfs/lib//jetty-util-6.1.26.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/hdfs/lib//xml-apis-1.3.04.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/hdfs/lib//xercesImpl-2.9.1.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/hdfs/lib//netty-all-4.0.23.Final.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/hdfs/lib//commons-daemon-1.0.13.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/hdfs/lib//netty-3.6.2.Final.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/hdfs/lib//jersey-server-1.9.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/hdfs/lib//asm-3.2.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/hdfs/lib//commons-lang-2.6.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/hdfs/lib//:/home/yujun/software/hadoop-2.7.3/share/hadoop/yarn//hadoop-yarn-server-common-2.7.3.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/yarn//hadoop-yarn-server-sharedcachemanager-2.7.3.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/yarn//hadoop-yarn-registry-2.7.3.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/yarn//hadoop-yarn-client-2.7.3.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/yarn//hadoop-yarn-api-2.7.3.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/yarn//hadoop-yarn-server-applicationhistoryservice-2.7.3.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/yarn//hadoop-yarn-applications-distributedshell-2.7.3.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/yarn//hadoop-yarn-server-web-proxy-2.7.3.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/yarn//hadoop-yarn-server-resourcemanager-2.7.3.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/yarn//hadoop-yarn-common-2.7.3.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/yarn//hadoop-yarn-applications-unmanaged-am-launcher-2.7.3.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/yarn//hadoop-yarn-server-nodemanager-2.7.3.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/yarn//hadoop-yarn-server-tests-2.7.3.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/yarn//:/home/yujun/software/hadoop-2.7.3/share/hadoop/yarn/lib//leveldbjni-all-1.8.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/yarn/lib//jsr305-3.0.0.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/yarn/lib//commons-cli-1.2.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/yarn/lib//protobuf-java-2.5.0.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/yarn/lib//jackson-jaxrs-1.9.13.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/yarn/lib//commons-logging-1.1.3.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/yarn/lib//servlet-api-2.5.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/yarn/lib//jersey-core-1.9.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/yarn/lib//jackson-core-asl-1.9.13.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/yarn/lib//jackson-xc-1.9.13.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/yarn/lib//javax.inject-1.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/yarn/lib//stax-api-1.0-2.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/yarn/lib//log4j-1.2.17.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/yarn/lib//commons-codec-1.4.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/yarn/lib//jetty-6.1.26.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/yarn/lib//commons-io-2.4.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/yarn/lib//guava-11.0.2.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/yarn/lib//jackson-mapper-asl-1.9.13.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/yarn/lib//jersey-guice-1.9.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/yarn/lib//jetty-util-6.1.26.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/yarn/lib//aopalliance-1.0.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/yarn/lib//activation-1.1.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/yarn/lib//zookeeper-3.4.6-tests.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/yarn/lib//guice-servlet-3.0.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/yarn/lib//guice-3.0.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/yarn/lib//jaxb-api-2.2.2.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/yarn/lib//jaxb-impl-2.2.3-1.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/yarn/lib//netty-3.6.2.Final.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/yarn/lib//zookeeper-3.4.6.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/yarn/lib//jersey-client-1.9.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/yarn/lib//jersey-json-1.9.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/yarn/lib//jersey-server-1.9.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/yarn/lib//xz-1.0.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/yarn/lib//asm-3.2.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/yarn/lib//commons-collections-3.2.2.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/yarn/lib//jettison-1.1.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/yarn/lib//commons-compress-1.4.1.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/yarn/lib//commons-lang-2.6.jar:/home/yujun/software/hadoop-2.7.3/share/hadoop/yarn/lib//, DMLC_MAX_ATTEMPT=3, DMLC_NUM_WORKER=1, DMLC_CPU_VCORES=2, LD_LIBRARY_PATH=/usr/local/cuda/lib64:/usr/local/lib:$HADOOP_HDFS_HOME/lib/native:$JAVA_HOME/jre/lib/amd64/server, DMLC_MEMORY_MB=1024, DMLC_NUM_ATTEMPT=0, DMLC_TRACKER_PORT=9091, DMLC_TASK_ID=0}
17/11/09 19:10:01 INFO impl.NMClientAsyncImpl: Processing Event EventType: START_CONTAINER for Container container_1510224989769_0003_01_000002
17/11/09 19:10:01 INFO impl.ContainerManagementProtocolProxy: Opening proxy : yujun-pc:34731
17/11/09 19:10:01 INFO dmlc.ApplicationMaster: onContainerStarted Invoked
17/11/09 19:10:02 INFO dmlc.ApplicationMaster: [DMLC] Task 0 exited with status 250 Diagnostics:Exception from container-launch.
Container id: container_1510224989769_0003_01_000002
Exit code: 250
Stack trace: ExitCodeException exitCode=250: 
	at org.apache.hadoop.util.Shell.runCommand(Shell.java:582)
	at org.apache.hadoop.util.Shell.run(Shell.java:479)
	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:773)
	at org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.launchContainer(DefaultContainerExecutor.java:212)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Container exited with a non-zero exit code 250

17/11/09 19:10:02 INFO dmlc.ApplicationMaster: Task 0 failed on container_1510224989769_0003_01_000002. See LOG at : http://yujun-pc:8042/node/containerlogs/container_1510224989769_0003_01_000002/yujun
17/11/09 19:10:02 INFO impl.NMClientAsyncImpl: Processing Event EventType: STOP_CONTAINER for Container container_1510224989769_0003_01_000002
17/11/09 19:10:02 INFO impl.ContainerManagementProtocolProxy: Opening proxy : yujun-pc:34731
17/11/09 19:10:02 INFO dmlc.ApplicationMaster: onContainerStopped Invoked
17/11/09 19:10:04 INFO impl.NMClientAsyncImpl: Processing Event EventType: START_CONTAINER for Container container_1510224989769_0003_01_000003
17/11/09 19:10:04 INFO impl.ContainerManagementProtocolProxy: Opening proxy : yujun-pc:34731
17/11/09 19:10:04 INFO dmlc.ApplicationMaster: onContainerStarted Invoked
17/11/09 19:10:05 INFO impl.NMClientAsyncImpl: Processing Event EventType: START_CONTAINER for Container container_1510224989769_0003_01_000004
17/11/09 19:10:05 INFO impl.ContainerManagementProtocolProxy: Opening proxy : yujun-pc:34731
17/11/09 19:10:05 INFO dmlc.ApplicationMaster: onContainerStarted Invoked

**Comment by webzjuyujun** [comment]
USE_HDFS = 1  has set

**Comment by superbobry** [comment]
Can you add a log from the container?
