### ISSUE TITLE
xgb.train return a tuple, not a Booster

### ISSUE THREAD

**Issue by ChrisBg** [dmlc/xgboost#287]
I trained 2 similar GBT models with the same params, same datasets ... on 2 different google cloud instances.
The codes really are identical but on one of instances, code doesn't run and the function xgb.train return a tuple not a Booster.
Please would you have an explanation and/or a solution ?
Thank you in advance

PS: I'm using the Python xgboost module.

**Comment by tqchen** [comment]
I have no idea on what was happening on the other machine. It would  be great if you can provide more details or dig into xgb.train 's steps to see where it goes wrong

https://github.com/dmlc/xgboost/blob/master/wrapper/xgboost.py#L576

**Comment by tqchen** [comment]
I am closing this issue for now. please reopen if yoy have any updates on this

**Comment by ChrisBg** [comment]
Hi,

Sorry no time to investiguate  more my problems.
Once again thnak you to your reply

Christophe

2015-05-27 2:40 GMT+02:00 Tianqi Chen <notifications@github.com>:

**Comment by pommedeterresautee** [comment]
FYI, on Kaggle Forum I see the same issue with Google instances (may be from you?).
