### ISSUE TITLE
GPU install fails ubuntu 16.04

### ISSUE THREAD

**Issue by simonm3** [dmlc/xgboost#2870]
ubuntu 16.04
gcc version 4.8
cuda 8.0.44
python 3.6.2

ubuntu@ip-172-31-13-214:~/xgboost/build$ make -j
[  1%] Building NVCC (Device) object nccl/CMakeFiles/nccl.dir/src/nccl_generated_reduce_scatter.cu.o
Scanning dependencies of target rabit
[  3%] Building NVCC (Device) object nccl/CMakeFiles/nccl.dir/src/nccl_generated_core.cu.o
[  4%] Building NVCC (Device) object nccl/CMakeFiles/nccl.dir/src/nccl_generated_all_reduce.cu.o
[  6%] Building NVCC (Device) object nccl/CMakeFiles/nccl.dir/src/nccl_generated_reduce.cu.o
[  7%] Building NVCC (Device) object nccl/CMakeFiles/nccl.dir/src/nccl_generated_broadcast.cu.o
Scanning dependencies of target objxgboost
[  9%] Building NVCC (Device) object nccl/CMakeFiles/nccl.dir/src/nccl_generated_all_gather.cu.o
Scanning dependencies of target dmlccore
[ 10%] Building NVCC (Device) object nccl/CMakeFiles/nccl.dir/src/nccl_generated_libwrap.cu.o
[ 12%] Building CXX object dmlc-core/CMakeFiles/dmlccore.dir/src/data.cc.o
[ 13%] Building CXX object CMakeFiles/rabit.dir/rabit/src/allreduce_robust.cc.o
[ 15%] Building CXX object CMakeFiles/rabit.dir/rabit/src/allreduce_base.cc.o
[ 16%] Building CXX object dmlc-core/CMakeFiles/dmlccore.dir/src/recordio.cc.o
[ 18%] Building CXX object CMakeFiles/rabit.dir/rabit/src/engine.cc.o
[ 20%] Building CXX object dmlc-core/CMakeFiles/dmlccore.dir/src/config.cc.o
[ 21%] Building CXX object dmlc-core/CMakeFiles/dmlccore.dir/src/io/local_filesys.cc.o
[ 23%] Building CXX object dmlc-core/CMakeFiles/dmlccore.dir/src/io/recordio_split.cc.o
[ 24%] Building CXX object dmlc-core/CMakeFiles/dmlccore.dir/src/io/line_split.cc.o
[ 27%] Building CXX object dmlc-core/CMakeFiles/dmlccore.dir/src/io.cc.o
[ 26%] Building CXX object dmlc-core/CMakeFiles/dmlccore.dir/src/io/input_split_base.cc.o
[ 29%] Building CXX object CMakeFiles/rabit.dir/rabit/src/c_api.cc.o
[ 30%] Building CXX object CMakeFiles/objxgboost.dir/src/common/common.cc.o
[ 32%] Building CXX object CMakeFiles/objxgboost.dir/src/data/data.cc.o
[ 33%] Building CXX object CMakeFiles/objxgboost.dir/src/c_api/c_api.cc.o
[ 38%] Building CXX object CMakeFiles/objxgboost.dir/src/gbm/gbtree.cc.o
[ 35%] Building CXX object CMakeFiles/objxgboost.dir/src/gbm/gbm.cc.o
[ 36%] Building CXX object CMakeFiles/objxgboost.dir/src/data/simple_csr_source.cc.o
[ 40%] Building CXX object CMakeFiles/objxgboost.dir/src/data/sparse_page_raw_format.cc.o
[ 41%] Building CXX object CMakeFiles/objxgboost.dir/src/common/hist_util.cc.o
[ 43%] Building CXX object CMakeFiles/objxgboost.dir/src/data/simple_dmatrix.cc.o
[ 44%] Building CXX object CMakeFiles/objxgboost.dir/src/data/sparse_page_writer.cc.o
[ 46%] Building CXX object CMakeFiles/objxgboost.dir/src/c_api/c_api_error.cc.o
[ 47%] Building CXX object CMakeFiles/objxgboost.dir/src/predictor/cpu_predictor.cc.o
[ 64%] Building CXX object CMakeFiles/objxgboost.dir/src/predictor/predictor.cc.o
[ 63%] Building CXX object CMakeFiles/objxgboost.dir/src/learner.cc.o
[ 66%] Building CXX object CMakeFiles/objxgboost.dir/src/objective/objective.cc.o
[ 49%] Building CXX object CMakeFiles/objxgboost.dir/src/tree/tree_model.cc.o
[ 69%] Building CXX object CMakeFiles/objxgboost.dir/src/metric/metric.cc.o
[ 52%] Building CXX object CMakeFiles/objxgboost.dir/src/data/sparse_page_dmatrix.cc.o
[ 52%] Building CXX object CMakeFiles/objxgboost.dir/src/data/sparse_page_source.cc.o
[ 53%] Building CXX object CMakeFiles/objxgboost.dir/src/logging.cc.o
[ 55%] Building CXX object CMakeFiles/objxgboost.dir/src/gbm/gblinear.cc.o
[ 78%] Building CXX object CMakeFiles/objxgboost.dir/src/tree/updater_prune.cc.o
[ 56%] Building CXX object CMakeFiles/objxgboost.dir/src/metric/rank_metric.cc.o
[ 63%] Building CXX object CMakeFiles/objxgboost.dir/src/objective/regression_obj.cc.o
[ 63%] Building CXX object CMakeFiles/objxgboost.dir/src/objective/rank_obj.cc.o
[ 58%] Building CXX object CMakeFiles/objxgboost.dir/src/objective/multiclass_obj.cc.o
[ 80%] Building CXX object CMakeFiles/objxgboost.dir/src/tree/updater_refresh.cc.o
[ 67%] Building CXX object CMakeFiles/objxgboost.dir/src/metric/multiclass_metric.cc.o
[ 70%] Building CXX object CMakeFiles/objxgboost.dir/src/tree/updater_skmaker.cc.o
[ 72%] Building CXX object CMakeFiles/objxgboost.dir/src/tree/updater_colmaker.cc.o
[ 81%] Building CXX object CMakeFiles/objxgboost.dir/src/tree/updater_histmaker.cc.o
[ 73%] Building CXX object CMakeFiles/objxgboost.dir/src/tree/tree_updater.cc.o
[ 75%] Building CXX object CMakeFiles/objxgboost.dir/src/tree/updater_fast_hist.cc.o
[ 76%] Building CXX object CMakeFiles/objxgboost.dir/src/metric/elementwise_metric.cc.o
[ 83%] Building CXX object CMakeFiles/objxgboost.dir/src/tree/updater_sync.cc.o
[ 84%] Linking CXX static library librabit.a
[ 84%] Built target rabit
[ 86%] Linking CXX static library libdmlccore.a
[ 86%] Built target dmlccore
[ 86%] Built target objxgboost
Scanning dependencies of target nccl
[ 87%] Linking CXX static library libnccl.a
[ 87%] Built target nccl
[ 89%] Building NVCC (Device) object CMakeFiles/gpuxgboost.dir/src/tree/gpuxgboost_generated_updater_gpu_hist_experimental.cu.o
[ 90%] Building NVCC (Device) object CMakeFiles/gpuxgboost.dir/src/tree/gpuxgboost_generated_updater_gpu.cu.o
[ 92%] Building NVCC (Device) object CMakeFiles/gpuxgboost.dir/src/predictor/gpuxgboost_generated_gpu_predictor.cu.o
[ 93%] Building NVCC (Device) object CMakeFiles/gpuxgboost.dir/src/tree/gpuxgboost_generated_updater_gpu_hist.cu.o
Scanning dependencies of target gpuxgboost
[ 95%] Linking CXX static library libgpuxgboost.a
[ 95%] Built target gpuxgboost
Scanning dependencies of target runxgboost
[ 96%] Building CXX object CMakeFiles/runxgboost.dir/src/cli_main.cc.o
[ 98%] Linking CXX executable ../xgboost
libgpuxgboost.a(gpuxgboost_generated_gpu_predictor.cu.o): In function `std::_Function_handler<xgboost::Predictor* (), xgboost::predictor::{lambda()#1}>::_M_invoke(std::_Any_data const&)':
tmpxft_0000317c_00000000-4_gpu_predictor.compute_61.cudafe1.cpp:(.text+0x920): undefined reference to `xgboost::Predictor::Create(std::string)'
libgpuxgboost.a(gpuxgboost_generated_gpu_predictor.cu.o): In function `xgboost::predictor::GPUPredictor::Init(std::vector<std::pair<std::string, std::string>, std::allocator<std::pair<std::string, std::string> > > const&, std::vector<std::shared_ptr<xgboost::DMatrix>, std::allocator<std::shared_ptr<xgboost::DMatrix> > > const&)':
tmpxft_0000317c_00000000-4_gpu_predictor.compute_61.cudafe1.cpp:(.text._ZN7xgboost9predictor12GPUPredictor4InitERKSt6vectorISt4pairISsSsESaIS4_EERKS2_ISt10shared_ptrINS_7DMatrixEESaISB_EE[_ZN7xgboost9predictor12GPUPredictor4InitERKSt6vectorISt4pairISsSsESaIS4_EERKS2_ISt10shared_ptrINS_7DMatrixEESaISB_EE]+0x1c): undefined reference to `xgboost::Predictor::Init(std::vector<std::pair<std::string, std::string>, std::allocator<std::pair<std::string, std::string> > > const&, std::vector<std::shared_ptr<xgboost::DMatrix>, std::allocator<std::shared_ptr<xgboost::DMatrix> > > const&)'
collect2: error: ld returned 1 exit status
CMakeFiles/runxgboost.dir/build.make:170: recipe for target '../xgboost' failed
make[2]: *** [../xgboost] Error 1
CMakeFiles/Makefile2:150: recipe for target 'CMakeFiles/runxgboost.dir/all' failed
make[1]: *** [CMakeFiles/runxgboost.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Duanxiaoer** [comment]
I also meet this issue, any way to fix it?
