### ISSUE TITLE
[JVM-PACKAGE] A question about "how to print test-auc"

### ISSUE THREAD

**Issue by nedved1990** [dmlc/xgboost#2871]
Hi:
I have a question about  "how to print test-auc".
Here is my predict funtion:

**val xgBoostModel = XGBoost.trainWithDataFrame(
      trainDF, paramMap, numRound.toInt, nWorkers = parameter.getnWorkers().toInt, useExternalMemory = false)**

![image](https://user-images.githubusercontent.com/19920727/32604710-97ae1878-c589-11e7-8376-87af3d44de0e.png)
How can I print the "**test-auc**"?

**Comment by superbobry** [comment]
You need to set `trainTestRatio` to a value other than 1.

**Comment by nedved1990** [comment]
@superbobry Thanks for your answear!
I try to reset my params, it changes like below:
 **var paramMap = List(
      "booster"-> parameter.getBooster, //default gbtree
      "gamma"->parameter.getGamma.toInt, //default 0
      "min_child_weight"->parameter.getMin_child_weight.toDouble, //default 1
      "lambda"->parameter.getLambda.toDouble, //default 1
      "alpha"->parameter.getAlpha.toDouble, //default 1
      "eval_metric"->parameter.getEval_metric, //regression is rmse, classification is error
      "eta" -> parameter.getEta().toDouble,
      "max_depth" -> maxDepth, //default 6
      "trainTestRatio" -> 0.1,
      "objective" -> parameter.getObjective).toMap**

But it still doesn't work. Is that something I neglect?

**Comment by nedved1990** [comment]
@superbobry 
In addition:
I use xgboost-on-spark.
Thanks.

**Comment by superbobry** [comment]
Are you using the `master` version? Also, is your input a data frame or an RDD?

**Comment by nedved1990** [comment]
@superbobry 
Yes, I use master version.
And my input is data frame.

**Comment by superbobry** [comment]
Hmm, the call looks legit to me. Can you double check that the version you're using has ``trainTestRatio`` PR #2710?
