### ISSUE TITLE
 [jvm-packages] xgboost fails during initialization on IBM Java

### ISSUE THREAD

**Issue by linight** [dmlc/xgboost#2879]
xgboost fails during initialization on IBM Java. The reason: 

> ml.dmlc.xgboost4j.java.NativeLibLoader#addNativeDir

 is trying to access field 

> java.lang.ClassLoader#usr_paths

which is absent in IBM Java.
## Console Output

```
0 [main] ERROR ml.dmlc.xgboost4j.java.NativeLibLoader  - usr_paths
0 [main] ERROR ml.dmlc.xgboost4j.java.Booster  - load native library failed.
0 [main] ERROR ml.dmlc.xgboost4j.java.Booster  - java.io.IOException: Failed to get field handle to set library path
Exception in thread "main" java.lang.UnsatisfiedLinkError: ml/dmlc/xgboost4j/java/XGBoostJNI.XGBoosterCreate([J[J)I
	at ml.dmlc.xgboost4j.java.Booster.init(Booster.java:448)
	at ml.dmlc.xgboost4j.java.Booster.<init>(Booster.java:57)
	at ml.dmlc.xgboost4j.java.Booster.loadModel(Booster.java:95)
	at ml.dmlc.xgboost4j.BoosterHelper.loadModel(BoosterHelper.java:19)
	at hex.genmodel.algos.xgboost.XGBoostMojoReader.readModelData(XGBoostMojoReader.java:25)
	at hex.genmodel.ModelMojoReader.readAll(ModelMojoReader.java:149)
	at hex.genmodel.ModelMojoReader.readFrom(ModelMojoReader.java:34)
	at xbt.Main.main(Main.java:58)
```

## Environment info

CentOS 7 x86_64

`uname -a`
Linux localhost.localdomain 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 20 20:32:50 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

`xgboost` version used:
xgboost4j-0.7

`java -version`
java version "1.8.0"
Java(TM) SE Runtime Environment (build pxa6480sr3fp12-20160919_01(SR3 FP12))
IBM J9 VM (build 2.8, JRE 1.8.0 Linux amd64-64 Compressed References 20160915_318796 (JIT enabled, AOT enabled)
J9VM - R28_Java8_SR3_20160915_0912_B318796
JIT  - tr.r14.java.green_20160818_122998
GC   - R28_Java8_SR3_20160915_0912_B318796_CMPRSS
J9CL - 20160915_318796)
JCL - 20160914_01 based on Oracle jdk8u101-b13

## Workaround

Add it somewhere on application startup.
```
NativeLibraryLoaderChain.loaderChain(
    NativeLibrary.nativeLibrary("xgboost4j"),
    NativeLibrary.nativeLibrary("xgboost4j_gpu")
).load();

Class nativeLibLoaderClass = NativeLibLoader.class;
final Field initializedField = nativeLibLoaderClass.getDeclaredField("initialized");
initializedField.setAccessible(true);
initializedField.set(null, Boolean.TRUE);
   
final Field originalLoadPathField = nativeLibLoaderClass.getDeclaredField("ORIGINAL_LOAD_PATH");
originalLoadPathField.setAccessible(true);

Field modifiersField = Field.class.getDeclaredField("modifiers");
modifiersField.setAccessible(true);
modifiersField.setInt(originalLoadPathField, originalLoadPathField.getModifiers() & ~Modifier.FINAL);
originalLoadPathField.set(null, Boolean.TRUE);
```

**Comment by superbobry** [comment]
I the workaround specific to IBM JVM?

**Comment by linight** [comment]
@superbobry checked it on Oracle Java 8 too, it works

**Comment by linight** [comment]
Added console output

**Comment by superbobry** [comment]
Thanks! I'm not sure we need to modify usr_paths at all, because JVM has an API for loading a library directly from a file on disk. 

Also, while we're at it, I wonder if we can delegate the loading to an existing library, e.g. [native-lib-loader](https://github.com/scijava/native-lib-loader) and let it take care of compatibility issues.
