### ISSUE TITLE
xgboost4j-spark : Bigger Dataset than executor memory

### ISSUE THREAD

**Issue by SundeepMehta** [dmlc/xgboost#2884]
Does Xgboost-spark requires all the data to be in memory across nodes i.e. RDD/Partitions ? I have close to 5 TB data/180 million records containing feature vector on HDFS will I be able to train the model ?

I have physical RAM of 200 GB across 4 nodes cluster with 10 TB of disk

**Comment by superbobry** [comment]
Have you tried it? XGBoost support out-of-core learning so I'd say xgboost4j could handle 5Tb (we actually tried it on 1Tb internally w/o any Spark tuning).
