### ISSUE TITLE
xgboost-spark complie and yarn cluster env problem

### ISSUE THREAD

**Issue by lxmly** [dmlc/xgboost#2890]
Does the newest version  of xgboost-spark  require that the env of  the machines in yarn cluster is g++4.8 or higher? 

I complie xgboost-jvm in local linux machine, and running it on yarn cluster failed. Our cluster machines' gcc version is lower than 4.8, but upgrading all of the machines‘ gcc version is impossible. The spark version is 2.1.0.

I also complie low xgboost-jvm version v0.60 on cluster machine, but run failed too.

**Comment by superbobry** [comment]
I think this is not related to the Spark version, but rather to the XGBoost itself. @khotilov can you comment?

**Comment by khotilov** [comment]
@lxmly we don't know what error you are seeing while trying to run on a machine with older gcc, and whether those are different linux systems to your local machine. But if the systems are similar enough and GLIBC versions are compatible, try shipping some of the shared libraries from your local machine that xgboost depends on (see with `ldd libxgboost.so`) together with libxgboost.so.
