### ISSUE TITLE
Please update python package with new Makefile

### ISSUE THREAD

**Issue by mrkn** [dmlc/xgboost#2893]
On macOS, I can install xgboost python library from source, but I cannot by pip command.
The reason is that Makefile in the python package version 0.6a2 uses g++-5 and clang-omp++. Both compilers are obsoleted now.

Updating the python package with the latest Makefile should resolve the installation problem by pip command.

**Comment by EXPEpchaurasia** [comment]
+1

**Comment by mrkn** [comment]
#2889 is a related issue.

**Comment by phunterlau** [comment]
A new pip installation is being prepared under the official release, and the Makefile will be consistent to the github.
