### ISSUE TITLE
Makefile:141: recipe for target 'build/learner.o' failed

### ISSUE THREAD

**Issue by suraj021** [dmlc/xgboost#2894]
## Environment info
Operating System: Ubuntu 64bit
Compiler: g++11

If installing from source, please provide 
1. the gcc version : 5.5

If you are using python package, please provide
1. The python version: 3.6

## Steps to reproduce

1. cd xgboost
2. make 
3.

## What have you tried?

1. Installed g++ 7

Log:
suraj021@srjbora:~/xgboost$ make
Makefile:31: MAKE [make] - checked OK
g++ -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/learner.o src/learner.cc >build/learner.d
g++ -c -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp src/learner.cc -o build/learner.o
In file included from dmlc-core/include/dmlc/registry.h:14:0,
                 from include/xgboost/./gbm.h:11,
                 from include/xgboost/learner.h:16,
                 from src/learner.cc:9:
dmlc-core/include/dmlc/./parameter.h: In member function ‘virtual void dmlc::parameter::FieldEntry<float>::Set(void*, const string&) const’:
dmlc-core/include/dmlc/./parameter.h:962:25: error: ‘stof’ is not a member of ‘std’
       this->Get(head) = std::stof(value);
                         ^
dmlc-core/include/dmlc/./parameter.h: In member function ‘virtual void dmlc::parameter::FieldEntry<double>::Set(void*, const string&) const’:
dmlc-core/include/dmlc/./parameter.h:983:25: error: ‘stod’ is not a member of ‘std’
       this->Get(head) = std::stod(value);
                         ^
Makefile:141: recipe for target 'build/learner.o' failed
make: *** [build/learner.o] Error 1

**Comment by JiayuanGuo** [comment]
Hi Suraj, have u find out how to solve? I'm facing the same issue

**Comment by suraj021** [comment]
Using "g++ (Ubuntu 5.5.0-1ubuntu1) 5.4.1 20171010" as default.
