### ISSUE TITLE
benchmark.py doesn't run with gpu_hist/gpu_exact

### ISSUE THREAD

**Issue by foslabs** [dmlc/xgboost#2895]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System: centos 7.4
Compiler:gcc 4.9.2
Package used (python/R/jvm/C++): python
`xgboost` version used: 0.6 (self build)

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`) 70a4c419e966fea9418bc09dfec19e41215f7fb2
2. Logs will be helpful (If logs are large, please upload as attachment).
Training with 'gpu_hist'
Traceback (most recent call last):
  File "tests/benchmark/benchmark.py", line 66, in <module>
    run_benchmark(args)
  File "tests/benchmark/benchmark.py", line 53, in run_benchmark
    xgb.train(param, dtrain, args.iterations, evals=[(dtest, "test")])
  File "/usr/lib/python2.7/site-packages/xgboost/training.py", line 205, in train
    xgb_model=xgb_model, callbacks=callbacks)
  File "/usr/lib/python2.7/site-packages/xgboost/training.py", line 76, in _train_internal
    bst.update(dtrain, i, obj)
  File "/usr/lib/python2.7/site-packages/xgboost/core.py", line 806, in update
    _check_call(_LIB.XGBoosterUpdateOneIter(self.handle, iteration, dtrain.handle))
  File "/usr/lib/python2.7/site-packages/xgboost/core.py", line 127, in _check_call
    raise XGBoostError(_LIB.XGBGetLastError())
  File "/usr/lib/python2.7/site-packages/xgboost/core.py", line 127, in _check_call
    raise XGBoostError(_LIB.XGBGetLastError())
xgboost.core.XGBoostError: Invalid Input: 'gpu_hist', valid values are: {'approx', 'auto', 'exact'}

If you are using jvm package, please 

1. add [jvm-packages] in the title to make it quickly be identified
2. the gcc version and distribution

If you are using python package, please provide

1. The python version and distribution: 2.7
2. The command to install `xgboost` if you are not installing from source

If you are using R package, please provide

1. The R `sessionInfo()`
2. The command to install `xgboost` if you are not installing from source

## Steps to reproduce

1.  cd xgboost
2.  python tests/benchmark/benchmark.py
3.

## What have you tried?

1. python tests/benchmark/benchmark.py --tree_method=hist
2. check the source codes of /usr/lib/python2.7/site-packages/xgboost/core.py line 127
3.

**Comment by LeoLee1** [comment]
As far as I know, "xgboost.core.XGBoostError: Invalid Input: 'gpu_hist', valid values are: {'approx', 'auto', 'exact'}" is related with xgboost in GPU server. First you should use gpu server and build xgboost lib with the below command. 
From the command line on Linux starting from the xgboost directory:

$ mkdir build
$ cd build
$ cmake .. -DUSE_CUDA=ON
$ make -j

And then you can execute benchmark.py. Lastly I recommend that you use python3.6. I got some errors with python2.7 when I execute the benchmark.py.

**Comment by foslabs** [comment]
Closed. not sure which step was wrong in installation. after a long weekend, and rebuilt with a change in in-relevant location; the gpu_hist etc. shows up in the tree_method.
