### ISSUE TITLE
 [jvm-packages]  error: not found: value ml   

### ISSUE THREAD

**Issue by PaulBenjamin** [dmlc/xgboost#2897]
I have installed xgboost in my mac following the installation guide from XGBoost site [https://xgboost.readthedocs.io/en/latest/build.html#building-on-osx](url) and also using this guide [https://www.ibm.com/developerworks/community/blogs/jfp/entry/Installing_XGBoost_on_Mac_OSX?lang=en](url) 
The installation is successully built.
My goal for the time being (I am a complete newby) is to use xgboost in Scala-Spark scripts.
When I try to  try to import the ml packages from scala from the shell (or when I try to run a SCALA script as [this one](http://bailiwick.io/2017/08/21/using-xgboost-with-the-titanic-dataset-from-kaggle/) )I find the following error.

scala> import ml.dmlc.xgboost4j.scala.spark.{XGBoostEstimator, XGBoostClassificationModel}
<console>:23: error: not found: value ml
       import ml.dmlc.xgboost4j.scala.spark.{XGBoostEstimator, XGBoostClassificationModel}
              ^

Or 

## Environment info
Operating System: macOS Sierra 10.12.6
gcc -6

I have set the JAVA_HOME at /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/

Can anybody help to fix this please?

Thanks a lot!

**Comment by superbobry** [comment]
The xgboost4j JAR is not in the classpath. See e.g. [this](https://alvinalexander.com/scala/scala-how-add-jar-file-scala-repl-classpath-command-line) blog post on how to add JARs to the Scala REPL classpath.

**Comment by PaulBenjamin** [comment]
I have tried the solutions from the post and it works perfectly, 

Thanks a lot.
