### ISSUE TITLE
[jvm-packages] XGBoost4J won't compile on Windows 8/8.1

### ISSUE THREAD

**Issue by logicators** [dmlc/xgboost#2899]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System: Windows 8.1

Compiler: CMake 3.10.0

Package used (python/R/jvm/C++): jvm

`xgboost` version used: 0.7

I followed instructions on http://xgboost.readthedocs.io/en/latest/jvm/#resources. All dependencies seem fine but "mvn package" keeps failing. I reinstalled CMake, MS build tools, and even installed the new visual studio community edition without any luck. Here is what I get:

C:\common_libs\xgboost\jvm-packages>mvn package
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for ml.dmlc:xgboost4j:jar:0.7
[WARNING] 'build.plugins.plugin.version' for org.codehaus.mojo:exec-maven-plugin is missing. @ line 54, column 19
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] xgboost-jvm
[INFO] xgboost4j
[INFO] xgboost4j-spark
[INFO] xgboost4j-flink
[INFO] xgboost4j-example
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building xgboost-jvm 0.7
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- scalastyle-maven-plugin:0.8.0:check (checkstyle) @ xgboost-jvm ---
[WARNING] sourceDirectory is not specified or does not exist value=C:\common_libs\xgboost\jvm-packages\src\main\scala
[WARNING] testSourceDirectory is not specified or does not exist value=C:\common_libs\xgboost\jvm-packages\src\test\scala
Processed 0 file(s)
Found 0 errors
Found 0 warnings
Found 0 infos
Finished in 96 ms
[INFO]
[INFO] --- maven-checkstyle-plugin:2.17:check (checkstyle) @ xgboost-jvm ---
[INFO]
[INFO] --- jacoco-maven-plugin:0.7.9:prepare-agent (default) @ xgboost-jvm ---
[INFO] argLine set to -javaagent:C:\\Users\\Hassan\\.m2\\repository\\org\\jacoco\\org.jacoco.agent\\0.7.9\\org.jacoco.agent-0.7.9-runtime.jar=destfile=C:\\common_libs\\xgboost\\jvm
-packages\\target\\jacoco.exec
[INFO]
[INFO] --- scala-maven-plugin:3.2.2:compile (default) @ xgboost-jvm ---
[WARNING]  Expected all dependencies to require Scala version: 2.11.8
[WARNING]  ml.dmlc:xgboost-jvm:0.7 requires scala version: 2.11.8
[WARNING]  org.scala-lang:scala-compiler:2.11.8 requires scala version: 2.11.8
[WARNING]  org.scala-lang.modules:scala-xml_2.11:1.0.4 requires scala version: 2.11.4
[WARNING] Multiple versions of scala libraries detected!
[INFO] No sources to compile
[INFO]
[INFO] --- scala-maven-plugin:3.2.2:compile (scala-compile-first) @ xgboost-jvm ---
[WARNING]  Expected all dependencies to require Scala version: 2.11.8
[WARNING]  ml.dmlc:xgboost-jvm:0.7 requires scala version: 2.11.8
[WARNING]  org.scala-lang:scala-compiler:2.11.8 requires scala version: 2.11.8
[WARNING]  org.scala-lang.modules:scala-xml_2.11:1.0.4 requires scala version: 2.11.4
[WARNING] Multiple versions of scala libraries detected!
[INFO] No sources to compile
[INFO]
[INFO] --- scala-maven-plugin:3.2.2:add-source (scala-compile-first) @ xgboost-jvm ---
[INFO] Add Source directory: C:\common_libs\xgboost\jvm-packages\src\main\scala
[INFO] Add Test Source directory: C:\common_libs\xgboost\jvm-packages\src\test\scala
[INFO]
[INFO] --- scala-maven-plugin:3.2.2:compile (compile) @ xgboost-jvm ---
[WARNING]  Expected all dependencies to require Scala version: 2.11.8
[WARNING]  ml.dmlc:xgboost-jvm:0.7 requires scala version: 2.11.8
[WARNING]  org.scala-lang:scala-compiler:2.11.8 requires scala version: 2.11.8
[WARNING]  org.scala-lang.modules:scala-xml_2.11:1.0.4 requires scala version: 2.11.4
[WARNING] Multiple versions of scala libraries detected!
[INFO] No sources to compile
[INFO]
[INFO] --- scala-maven-plugin:3.2.2:testCompile (test-compile) @ xgboost-jvm ---
[WARNING]  Expected all dependencies to require Scala version: 2.11.8
[WARNING]  ml.dmlc:xgboost-jvm:0.7 requires scala version: 2.11.8
[WARNING]  org.scala-lang:scala-compiler:2.11.8 requires scala version: 2.11.8
[WARNING]  org.scala-lang.modules:scala-xml_2.11:1.0.4 requires scala version: 2.11.4
[WARNING] Multiple versions of scala libraries detected!
[INFO] No sources to compile
[INFO]
[INFO] --- scalatest-maven-plugin:1.0:test (test) @ xgboost-jvm ---
←[36mDiscovery starting.←[0m
←[36mDiscovery completed in 170 milliseconds.←[0m
←[36mRun starting. Expected test count is: 0←[0m
←[32mDiscoverySuite:←[0m
←[36mRun completed in 263 milliseconds.←[0m
←[36mTotal number of tests run: 0←[0m
←[36mSuites: completed 1, aborted 0←[0m
←[36mTests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0←[0m
←[33mNo tests were executed.←[0m
[INFO]
[INFO] --- jacoco-maven-plugin:0.7.9:report (report) @ xgboost-jvm ---
[INFO] Skipping JaCoCo execution due to missing classes directory.
[INFO]
[INFO] --- maven-assembly-plugin:2.6:single (make-assembly) @ xgboost-jvm ---
[INFO] Assemblies have been skipped per configuration of the skipAssembly parameter.
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building xgboost4j 0.7
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- scalastyle-maven-plugin:0.8.0:check (checkstyle) @ xgboost4j ---
Processed 14 file(s)
Found 0 errors
Found 0 warnings
Found 0 infos
Finished in 1103 ms
[INFO]
[INFO] --- maven-checkstyle-plugin:2.17:check (checkstyle) @ xgboost4j ---
[INFO]
[INFO] --- jacoco-maven-plugin:0.7.9:prepare-agent (default) @ xgboost4j ---
[INFO] argLine set to -javaagent:C:\\Users\\Hassan\\.m2\\repository\\org\\jacoco\\org.jacoco.agent\\0.7.9\\org.jacoco.agent-0.7.9-runtime.jar=destfile=C:\\common_libs\\xgboost\\jvm
-packages\\xgboost4j\\target\\jacoco.exec
[INFO]
[INFO] --- exec-maven-plugin:1.6.0:exec (native) @ xgboost4j ---
CMake Error at CMakeLists.txt:2 (project):
  Failed to run MSBuild command:

    MSBuild.exe

  to get the value of VCTargetsPath:

    Microsoft (R) Build Engine version 4.7.2053.0
    [Microsoft .NET Framework, version 4.0.30319.42000]
    Copyright (C) Microsoft Corporation. All rights reserved.

    Build started 11/23/2017 10:20:09 PM.
    Project "C:\common_libs\xgboost\build\CMakeFiles\3.10.0-rc5\VCTargetsPath.vcxproj" on node 1 (default targets).
    C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\x64\Microsoft.Cpp.x64.Targets(514,5): error MSB8008: Specified platform toolset (v140) is not installed or invalid.
Please make sure that a supported PlatformToolset value is selected. [C:\common_libs\xgboost\build\CMakeFiles\3.10.0-rc5\VCTargetsPath.vcxproj]
    Done Building Project "C:\common_libs\xgboost\build\CMakeFiles\3.10.0-rc5\VCTargetsPath.vcxproj" (default targets) -- FAILED.

    Build FAILED.

    "C:\common_libs\xgboost\build\CMakeFiles\3.10.0-rc5\VCTargetsPath.vcxproj" (default target) (1) ->
    (Pl-- Configuring incomplete, errors occurred!
See also "C:/common_libs/xgboost/build/CMakeFiles/CMakeOutput.log".
atformPrepareForBuild target) ->
      C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\x64\Microsoft.Cpp.x64.Targets(514,5): error MSB8008: Specified platform toolset (v140) is not installed or invalid
. Please make sure that a supported PlatformToolset value is selected. [C:\common_libs\xgboost\build\CMakeFiles\3.10.0-rc5\VCTargetsPath.vcxproj]

        0 Warning(s)
        1 Error(s)

    Time Elapsed 00:00:00.83

  Exit code: 1

building Java wrapper
cd ..
mkdir -p build
cd build
cmake .. -DUSE_OPENMP:BOOL=ON -DUSE_HDFS:BOOL=OFF -DUSE_AZURE:BOOL=OFF -DUSE_S3:BOOL=OFF -DPLUGIN_UPDATER_GPU:BOOL=OFF -DJVM_BINDINGS:BOOL=ON -G"Visual Studio 14 Win64"
Traceback (most recent call last):
  File "create_jni.py", line 88, in <module>
    run("cmake .. " + " ".join(args) + maybe_generator)
  File "create_jni.py", line 51, in run
    subprocess.check_call(command, shell=True, **kwargs)
  File "C:\Users\Hassan\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cmake .. -DUSE_OPENMP:BOOL=ON -DUSE_HDFS:BOOL=OFF -DUSE_AZURE:BOOL=OFF -DUSE_S3:BOOL=OFF -DPLUGIN_UPDATER_GPU:BOOL=OFF -DJVM_BINDINGS:BOOL=O
N -G"Visual Studio 14 Win64"' returned non-zero exit status 1.
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
        at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:804)
        at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:751)
        at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:313)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] xgboost-jvm ........................................ SUCCESS [  5.085 s]
[INFO] xgboost4j .......................................... FAILURE [  3.356 s]
[INFO] xgboost4j-spark .................................... SKIPPED
[INFO] xgboost4j-flink .................................... SKIPPED
[INFO] xgboost4j-example .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.630 s
[INFO] Finished at: 2017-11-23T22:20:10+00:00
[INFO] Final Memory: 29M/2058M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:exec (native) on project xgboost4j: Command execution failed. Process exited with an error: 1 (Exit value:
1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :xgboost4j

**Comment by superbobry** [comment]
The current build script assumes Visual Studio 2015. You can try replacing 

```
' -G"Visual Studio 14 Win64"'
```

with 

```
' -G"Visual Studio 15 Win64"'
```

if you have the 2017 version.

**Comment by logicators** [comment]
Appreciate your quick response!

I just downgraded to Visual Studio 2015, cleaned xgboost directory and downloaded again, and tried mvn package again. Now getting a different error:

C:\common_libs>git clone --recursive https://github.com/dmlc/xgboost
Cloning into 'xgboost'...
remote: Counting objects: 21940, done.
remote: Total 21940 (delta 0), reused 0 (delta 0), pack-reused 21939
Receiving objects: 100% (21940/21940), 7.80 MiB | 11.80 MiB/s, done.
Resolving deltas: 100% (12909/12909), done.
Checking connectivity... done.
Submodule 'cub' (https://github.com/NVlabs/cub) registered for path 'cub'
Submodule 'dmlc-core' (https://github.com/dmlc/dmlc-core) registered for path 'dmlc-core'
Submodule 'nccl' (https://github.com/dmlc/nccl) registered for path 'nccl'
Submodule 'rabit' (https://github.com/dmlc/rabit) registered for path 'rabit'
Cloning into 'cub'...
remote: Counting objects: 32266, done.
Receiving objects: 100% (32266/32266), 16.15 MiB | 15.05 MiB/s, done.eceiving objects: 100% (32266/32266), 15.06 MiB | 15.05 MiB/s

Resolving deltas: 100% (28315/28315), done.
Checking connectivity... done.
Submodule path 'cub': checked out 'b20808b1b04ec3d6a625e51fbc1eb76f337754ad'
Cloning into 'dmlc-core'...
remote: Counting objects: 4525, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4525 (delta 0), reused 2 (delta 0), pack-reused 4520
Receiving objects: 100% (4525/4525), 1.07 MiB | 0 bytes/s, done.
Resolving deltas: 100% (2673/2673), done.
Checking connectivity... done.
Submodule path 'dmlc-core': checked out 'b5bec5481df86e8e6728d8bd80a61d87ef3b2cd5'
Cloning into 'nccl'...
remote: Counting objects: 657, done.
emote: Total 657 (delta 0), reused 0 (delta 0), pack-reused 657
Receiving objects: 100% (657/657), 1.38 MiB | 1.16 MiB/s, done.
Resolving deltas: 100% (413/413), done.
Checking connectivity... done.
Submodule path 'nccl': checked out 'faeac8333cec3ed7474dc9f1c35088dcd6eea60b'
Cloning into 'rabit'...
remote: Counting objects: 3145, done.
remote: Total 3145 (delta 0), reused 0 (delta 0), pack-reused 3145R
Receiving objects: 100% (3145/3145), 900.62 KiB | 807.00 KiB/s, done.
Resolving deltas: 100% (2041/2041), done.
Checking connectivity... done.
Submodule path 'rabit': checked out 'a764d45cfb438cc9f15cf47ce586c02ff2c65d0f'

C:\common_libs>cd xg*

C:\common_libs\xgboost>cd jv*

C:\common_libs\xgboost\jvm-packages>mvn package
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for ml.dmlc:xgboost4j:jar:0.7
[WARNING] 'build.plugins.plugin.version' for org.codehaus.mojo:exec-maven-plugin is missing. @ line 54, column 19
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] xgboost-jvm
[INFO] xgboost4j
[INFO] xgboost4j-spark
[INFO] xgboost4j-flink
[INFO] xgboost4j-example
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building xgboost-jvm 0.7
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- scalastyle-maven-plugin:0.8.0:check (checkstyle) @ xgboost-jvm ---
[WARNING] sourceDirectory is not specified or does not exist value=C:\common_libs\xgboost\jvm-packages\src\main\scala
[WARNING] testSourceDirectory is not specified or does not exist value=C:\common_libs\xgboost\jvm-packages\src\test\scala
Processed 0 file(s)
Found 0 errors
Found 0 warnings
Found 0 infos
Finished in 96 ms
[INFO]
[INFO] --- maven-checkstyle-plugin:2.17:check (checkstyle) @ xgboost-jvm ---
[INFO]
[INFO] --- jacoco-maven-plugin:0.7.9:prepare-agent (default) @ xgboost-jvm ---
[INFO] argLine set to -javaagent:C:\\Users\\Hassan\\.m2\\repository\\org\\jacoco\\org.jacoco.agent\\0.7.9\\org.jacoco.agent-0.7.9-runtime.jar=destfile=C:\\common_libs\\xgboost\\jvm
-packages\\target\\jacoco.exec
[INFO]
[INFO] --- scala-maven-plugin:3.2.2:compile (default) @ xgboost-jvm ---
[WARNING]  Expected all dependencies to require Scala version: 2.11.8
[WARNING]  ml.dmlc:xgboost-jvm:0.7 requires scala version: 2.11.8
[WARNING]  org.scala-lang:scala-compiler:2.11.8 requires scala version: 2.11.8
[WARNING]  org.scala-lang.modules:scala-xml_2.11:1.0.4 requires scala version: 2.11.4
[WARNING] Multiple versions of scala libraries detected!
[INFO] No sources to compile
[INFO]
[INFO] --- scala-maven-plugin:3.2.2:compile (scala-compile-first) @ xgboost-jvm ---
[WARNING]  Expected all dependencies to require Scala version: 2.11.8
[WARNING]  ml.dmlc:xgboost-jvm:0.7 requires scala version: 2.11.8
[WARNING]  org.scala-lang:scala-compiler:2.11.8 requires scala version: 2.11.8
[WARNING]  org.scala-lang.modules:scala-xml_2.11:1.0.4 requires scala version: 2.11.4
[WARNING] Multiple versions of scala libraries detected!
[INFO] No sources to compile
[INFO]
[INFO] --- scala-maven-plugin:3.2.2:add-source (scala-compile-first) @ xgboost-jvm ---
[INFO] Add Source directory: C:\common_libs\xgboost\jvm-packages\src\main\scala
[INFO] Add Test Source directory: C:\common_libs\xgboost\jvm-packages\src\test\scala
[INFO]
[INFO] --- scala-maven-plugin:3.2.2:compile (compile) @ xgboost-jvm ---
[WARNING]  Expected all dependencies to require Scala version: 2.11.8
[WARNING]  ml.dmlc:xgboost-jvm:0.7 requires scala version: 2.11.8
[WARNING]  org.scala-lang:scala-compiler:2.11.8 requires scala version: 2.11.8
[WARNING]  org.scala-lang.modules:scala-xml_2.11:1.0.4 requires scala version: 2.11.4
[WARNING] Multiple versions of scala libraries detected!
[INFO] No sources to compile
[INFO]
[INFO] --- scala-maven-plugin:3.2.2:testCompile (test-compile) @ xgboost-jvm ---
[WARNING]  Expected all dependencies to require Scala version: 2.11.8
[WARNING]  ml.dmlc:xgboost-jvm:0.7 requires scala version: 2.11.8
[WARNING]  org.scala-lang:scala-compiler:2.11.8 requires scala version: 2.11.8
[WARNING]  org.scala-lang.modules:scala-xml_2.11:1.0.4 requires scala version: 2.11.4
[WARNING] Multiple versions of scala libraries detected!
[INFO] No sources to compile
[INFO]
[INFO] --- scalatest-maven-plugin:1.0:test (test) @ xgboost-jvm ---
←[36mDiscovery starting.←[0m
←[36mDiscovery completed in 176 milliseconds.←[0m
←[36mRun starting. Expected test count is: 0←[0m
←[32mDiscoverySuite:←[0m
←[36mRun completed in 278 milliseconds.←[0m
←[36mTotal number of tests run: 0←[0m
←[36mSuites: completed 1, aborted 0←[0m
←[36mTests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0←[0m
←[33mNo tests were executed.←[0m
[INFO]
[INFO] --- jacoco-maven-plugin:0.7.9:report (report) @ xgboost-jvm ---
[INFO] Skipping JaCoCo execution due to missing classes directory.
[INFO]
[INFO] --- maven-assembly-plugin:2.6:single (make-assembly) @ xgboost-jvm ---
[INFO] Assemblies have been skipped per configuration of the skipAssembly parameter.
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building xgboost4j 0.7
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- scalastyle-maven-plugin:0.8.0:check (checkstyle) @ xgboost4j ---
Processed 14 file(s)
Found 0 errors
Found 0 warnings
Found 0 infos
Finished in 1123 ms
[INFO]
[INFO] --- maven-checkstyle-plugin:2.17:check (checkstyle) @ xgboost4j ---
[INFO]
[INFO] --- jacoco-maven-plugin:0.7.9:prepare-agent (default) @ xgboost4j ---
[INFO] argLine set to -javaagent:C:\\Users\\Hassan\\.m2\\repository\\org\\jacoco\\org.jacoco.agent\\0.7.9\\org.jacoco.agent-0.7.9-runtime.jar=destfile=C:\\common_libs\\xgboost\\jvm
-packages\\xgboost4j\\target\\jacoco.exec
[INFO]
[INFO] --- exec-maven-plugin:1.6.0:exec (native) @ xgboost4j ---
CMake Error at CMakeLists.txt:2 (project):
  Failed to run MSBuild command:

    C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe

  to get the value of VCTargetsPath:

    Microsoft (R) Build Engine version 14.0.23107.0
    Copyright (C) Microsoft Corporation. All rights reserved.

    Build started 11/23/2017 11:37:50 PM.
    Project "C:\common_libs\xgboost\build\CMakeFiles\3.10.0-rc5\VCTargetsPath.vcxproj" on node 1 (default targets).
    C:\common_libs\xgboost\build\CMakeFiles\3.10.0-rc5\VCTargetsPath.vcxproj(14,2): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that
 the path in the <Import> declaration is correct, and that the file exists on disk.
    Done Building Project "C:\common_libs\xgboost\build\CMakeFiles\3.10.0-rc5\VCTargetsPath.vcxproj" (default targets) -- FAILED.

    Build FAILED.

    "C:\common_libs\xgboost\build\CMakeFiles\3.10.0-rc5\VCTargetsPath.vcxproj" (default target) (1) ->
      C:\common_libs\xgboost\build\CMakeFiles\3.10.0-rc5\VCTargetsPath.vcxproj(14,-- Configuring incomplete, errors occurred!
See also "C:/common_libs/xgboost/build/CMakeFiles/CMakeOutput.log".
2): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on di
sk.

        0 Warning(s)
        1 Error(s)

    Time Elapsed 00:00:00.23


  Exit code: 1



building Java wrapper
cd ..
mkdir -p build
cd build
cmake .. -DUSE_OPENMP:BOOL=ON -DUSE_HDFS:BOOL=OFF -DUSE_AZURE:BOOL=OFF -DUSE_S3:BOOL=OFF -DPLUGIN_UPDATER_GPU:BOOL=OFF -DJVM_BINDINGS:BOOL=ON -G"Visual Studio 14 Win64"
Traceback (most recent call last):
  File "create_jni.py", line 88, in <module>
    run("cmake .. " + " ".join(args) + maybe_generator)
  File "create_jni.py", line 51, in run
    subprocess.check_call(command, shell=True, **kwargs)
  File "C:\Users\Hassan\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cmake .. -DUSE_OPENMP:BOOL=ON -DUSE_HDFS:BOOL=OFF -DUSE_AZURE:BOOL=OFF -DUSE_S3:BOOL=OFF -DPLUGIN_UPDATER_GPU:BOOL=OFF -DJVM_BINDINGS:BOOL=O
N -G"Visual Studio 14 Win64"' returned non-zero exit status 1.
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
        at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:804)
        at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:751)
        at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:313)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] xgboost-jvm ........................................ SUCCESS [  5.103 s]
[INFO] xgboost4j .......................................... FAILURE [  2.750 s]
[INFO] xgboost4j-spark .................................... SKIPPED
[INFO] xgboost4j-flink .................................... SKIPPED
[INFO] xgboost4j-example .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.052 s
[INFO] Finished at: 2017-11-23T23:37:50+00:00
[INFO] Final Memory: 34M/2324M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:exec (native) on project xgboost4j: Command execution failed. Process exited with an error: 1 (Exit value:
1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :xgboost4j

**Comment by logicators** [comment]
Update: I originally installed build tools for Visual Studio 2015 instead of full community edition which didn't work. I now installed the full community edition and am able to compile xgboost4j (xgboost4j-spark and later targets are still failing, but that's probably expected since I don't have spark on this machine). I will perform further tests and close this issue if everything seems fine.

Please consider updating installation instructions at "http://xgboost.readthedocs.io/en/latest/jvm/#resources". They don't include Visual Studio as a per-requisite which causes confusion.
