### ISSUE TITLE
pip package library is out-of-date

### ISSUE THREAD

**Issue by cinqs** [dmlc/xgboost#2902]
## Environment info
Operating System: CentOS 7

Compiler:

Package used (python/R/jvm/C++): python

`xgboost` version used: 0.6a2

If you are using python package, please provide

1. The python version and distribution: python 2.7
2. The command to install `xgboost` if you are not installing from source: pip install xgboost

## Steps to reproduce

1. pip install xgboost
2. import xgboost as xgb
3. xgb.plot_importance(bst, max_num_features = 5)

this gives me that

```python
    AttributeError: Unknown property max_num_features
```
## What have you tried?

1. compile from source from github and install from compiled whl file

So, please update the pip library.

**Comment by cinqs** [comment]
https://pypi.python.org/pypi/xgboost/0.6a2

this package is clearly out-of-date with your api document.

**Comment by phunterlau** [comment]
A precompiled pip installation is under preparation. It is coming soon.

**Comment by cinqs** [comment]
thanks and can you please aware that the version of the package should be well documented, and made clear. thanks

**Comment by hcho3** [comment]
@cinqs The issue is that the API document shows the features of the latest version, not the stable version. I'd propose having multiple versions of documentation (latest, 0.6a2, and so forth).
For an example, see [the treelite documentation](http://treelite.readthedocs.io/en/latest/)

**Comment by hcho3** [comment]
@phunterlau Tianqi has added me as a maintainer of PyPI package. I'm thinking of setting up a build script (something similar to [this](https://github.com/hcho3/treelite-wheels)) to build binary wheels for major platforms (Windows, Mac OS X, Linux) and upload them to PyPI.

**Comment by cinqs** [comment]
@hcho3 that's correct and organizing documentation with version specified is common used today.

and if want you are referring at is a CI process, you could try [Jenkins](https://jenkins.io/index.html) for automating the procedures. 

And could you please give a notice anywhere to let use know the PyPI project is updated, and then I could close this issue. Thanks

All the best.

**Comment by hcho3** [comment]
@cinqs I will make an annoucement when we make a new release on PyPI
