### ISSUE TITLE
Installing python package from source fails when using pip

### ISSUE THREAD

**Issue by kristofve91** [dmlc/xgboost#2906]
## Environment info
Operating System: Ubuntu 17.04

Compiler: gcc 6.3.0

Package used (python/R/jvm/C++): python (version 3.6.1)

`xgboost` version used: source (commit c55f14668e5a62d84727730c1b9537f29842112c)

If you are using python package, please provide

1. The python version and distribution
2. The command to install `xgboost` if you are not installing from source

## Steps to reproduce

Using python 3.6.1 on a virtualenv:
1. `git clone --recursive https://github.com/dmlc/xgboost`
2. `cd xgboost`
3. `make -j8`
4. `cd python-package`
5. `pip install .`

## Error log:
```python
Processing /home/kve/lib/xgboost/python-package
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-jmtktue5-build/setup.py", line 19, in <module>
        LIB_PATH = [os.path.relpath(libfile, CURRENT_DIR) for libfile in libpath['find_lib_path']()]
      File "/tmp/pip-jmtktue5-build/xgboost/libpath.py", line 49, in find_lib_path
        'List of candidates:\n' + ('\n'.join(dll_path)))
    XGBoostLibraryNotFound: Cannot find XGBoost Library in the candidate path, did you install compilers and run build.sh in root path?
    List of candidates:
    /tmp/pip-jmtktue5-build/xgboost/libxgboost.so
    /tmp/pip-jmtktue5-build/xgboost/../../lib/libxgboost.so
    /tmp/pip-jmtktue5-build/xgboost/./lib/libxgboost.so
    /home/kve/.virtualenvs/p36/xgboost/libxgboost.so
```

The `libxgboost.so` file was successfully created in step 3, but is not moved over to the temporary build folder.

## Notes

1. The installation method using `python setup.py install` works without any problems.
2. The `pip install` method is necessary to enable autocompletion for XGBoost in IDEs like PyCharm, and is generally seen as the recommended way to install packages. 

## Workaround

After creating a folder in the root directory of my virtualenv and copying `libxgboost.so` to it, the `pip install .` command was executed succesfully. This should not be the way how it works, however, as every non-executable part of installed packages should be contained in the `site-packages` folder.

**Comment by baolinji** [comment]
python setup.py install

**Comment by kristofve91** [comment]
As I said earlier, that command does work but it has some disadvantages compared to the `pip install .` approach, like no autocomplete in PyCharm or a less robust uninstalling mechanism. The first point could be argued as being a bug in PyCharm, but I think both installation mechanisms should be available for use and work without problems.

**Comment by hcho3** [comment]
@kristofve91 It appears that `setup.py` is unable to locate the shared library when it runs from a temporary directory. Let me take a look at it and get back to you.

ps. I took over the maintenance of xgboost PyPI package yesterday. I plan to release binary wheels on PyPI in the near future, so that you may simply use `pip3 install xgboost` to install pre-built libraries.
