### ISSUE TITLE
got an error OSError: [WinError -529697949] when predict, gpu mode

### ISSUE THREAD

**Issue by why2012** [dmlc/xgboost#2907]
## Environment info
Operating System:
win10
Compiler:
vs2015
Package used (python/R/jvm/C++):
python
`xgboost` version used:
0.6

only got this error in gpu mode, and depend on training data

D:\Miniconda3\lib\site-packages\xgboost-0.6-py3.6.egg\xgboost\core.py in predict(self, data, output_margin, ntree_limit, pred_leaf, pred_contribs, approx_contribs)
   1048                                           ctypes.c_uint(ntree_limit),
   1049                                           ctypes.byref(length),
-> 1050                                           ctypes.byref(preds)))
   1051         preds = ctypes2numpy(preds, length.value, np.float32)
   1052         if pred_leaf:

OSError: [WinError -529697949] Windows Error 0xe06d7363

**Comment by zeegithubsc** [comment]
Getting same error. Has been trying it from last 3 days but no success.

OS-Windows 10,
Cuda - Cuda 9.0. 
Graphics card - Nvidia 1050 ti,
xgboost built using VS 2015,
Python version - python 3.5

I have also tried building using other cuda and VS versions but they all either fail in similar manner or build itself fails. I can provide more details if someone is working on this ticket.

**Comment by mattiasliljenzin** [comment]
Same here. Did you guys manage to find a solution?

**Comment by RAMitchell** [comment]
I can take a look at this if someone can provide a minimal reproducible example.

**Comment by Nyquis** [comment]
I can consistenly repoduce this issue and it appears even for extremely small data sets. It seems that it is exclusively linked with the gpu flag.

Here is ta minimal example where it occurs:
`from xgboost import XGBClassifier
c=XGBClassifier(**{'tree_method':'gpu_exact'})
c.fit(np.array([[0,2],[4,5]]),np.array([4,5])
`

I get the following message:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\users\rich\documents\python\xgboost compile\xgboost\python-package\xgboost\skle
arn.py", line 506, in fit
    verbose_eval=verbose, xgb_model=None)
  File "c:\users\rich\documents\python\xgboost compile\xgboost\python-package\xgboost\trai
ning.py", line 204, in train
    xgb_model=xgb_model, callbacks=callbacks)
  File "c:\users\rich\documents\python\xgboost compile\xgboost\python-package\xgboost\trai
ning.py", line 74, in _train_internal
    bst.update(dtrain, i, obj)
  File "c:\users\rich\documents\python\xgboost compile\xgboost\python-package\xgboost\core
.py", line 895, in update
    dtrain.handle))
OSError: [WinError -529697949] Windows Error 0xe06d7363

**Comment by RAMitchell** [comment]
The seems related to #3162

Can someone confirm if this error still occurs with the latest fix.

**Comment by Nyquis** [comment]
I just cloned the repo and recompiled the library. The issue still persists.

**Comment by zzzzzzzzzzzzz** [comment]
Windows 7
VS 2015
CUDA 9.1
xgb 0.7
python 3.5

Got something that looks similar to this error, though I'm not sure if it's just because of huge dataset or something else (also I'm able to make slice which the model will be able to learn). If it's huge dataset issue, then I expected something more comprehensive.
I'm facing this error both using cpu and gpu for training.

```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-5-2cfb0ee29400> in <module>()
     27 dtest = xgb.DMatrix(X_test_lat, label=y_test_lat)
     28 cpu_res = {}
---> 29 xgb.train(param, dtrain, num_round, evals=[(dtest, 'test')], evals_result=cpu_res)
     30 print("CPU Training Time: %s seconds" % (str(time.time() - tmp)))

Q:\Dmitriy\Miniconda3\lib\site-packages\xgboost-0.7-py3.6.egg\xgboost\training.py in train(params, dtrain, num_boost_round, evals, obj, feval, maximize, early_stopping_rounds, evals_result, verbose_eval, xgb_model, callbacks, learning_rates)
    202                            evals=evals,
    203                            obj=obj, feval=feval,
--> 204                            xgb_model=xgb_model, callbacks=callbacks)
    205 
    206 

Q:\Dmitriy\Miniconda3\lib\site-packages\xgboost-0.7-py3.6.egg\xgboost\training.py in _train_internal(params, dtrain, num_boost_round, evals, obj, feval, xgb_model, callbacks)
     72         # Skip the first update if it is a recovery step.
     73         if version % 2 == 0:
---> 74             bst.update(dtrain, i, obj)
     75             bst.save_rabit_checkpoint()
     76             version += 1

Q:\Dmitriy\Miniconda3\lib\site-packages\xgboost-0.7-py3.6.egg\xgboost\core.py in update(self, dtrain, iteration, fobj)
    893         if fobj is None:
    894             _check_call(_LIB.XGBoosterUpdateOneIter(self.handle, ctypes.c_int(iteration),
--> 895                                                     dtrain.handle))
    896         else:
    897             pred = self.predict(dtrain)

OSError: [WinError -529697949] Windows Error 0xe06d7363
```
