### ISSUE TITLE
XGBoosterLoadModel fail when load model trained in python

### ISSUE THREAD

**Issue by xiaocongcsu** [dmlc/xgboost#2908]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System:ubuntu 14.04

Compiler:gcc  4.8.4

Package used (python/R/jvm/C++):python and C++

`xgboost` version used:master branch

## Steps to reproduce

1.compile the source of master branch to get the libxgboost.so,librabit.so,libdmlccore.a.
2.set up a new peoject
3.CMakeList.txt to link the .so

    set(XGBOOST "/home/xiaocong/xgboost/lib/libxgboost.so")
    set(RABIT "/home/xiaocong/xgboost/rabit/lib/librabit.so")
    set(DMLC "/home/xiaocong/xgboost/dmlc-core/libdmlc.a")

    target_link_libraries (${PROJECT_NAME} ${SEEKER_D_LIBS} ${PCL_LIBRARIES}   
    ${VTK_LIBRARIES}  ${OpenCV_LIBS} ${XGBOOST} ${RABIT}  xgboost)

load model code:

      BoosterHandle h_booster;
      XGBoosterCreate(NULL, 0, &h_booster);
      XGBoosterLoadModel(h_booster,modelFile.c_str());

// predict

      DMatrixHandle h_test;
      XGDMatrixCreateFromMat((float *)test_array, test_rows, test_cols, -1, &h_test);

      bst_ulong out_len;
      const float *f;
      XGBoosterPredict(h_booster, h_test, 0,0,&out_len,&f);

error:

    [21:53:18] dmlc-core/include/dmlc/./logging.h:300: [21:53:18] src/learner.cc:297: Check failed: fi->Read(&name_obj_[0], len) == len (4387427 vs. 825636918) BoostLearner: wrong model format

//predictions are all 0.5

    prediction[0]=0.5
    prediction[1]=0.5
    prediction[2]=0.5
    prediction[3]=0.5
    prediction[4]=0.5
    prediction[5]=0.5
    prediction[6]=0.5
    prediction[7]=0.5
    prediction[8]=0.5
    prediction[9]=0.5
    prediction[10]=0.5

## What have you tried?

1.try other functions in c_api.h.everything is ok，like predict and save model.so the compile and link was successful.

        int cols=3,rows=5;
	float train[rows][cols];
	for (int i=0;i<rows;i++)
  		for (int j=0;j<cols;j++)
      		  train[i][j] = (i+1) * (j+1);

	float train_labels[rows];
	for (int i=0;i<rows;i++)
    		train_labels[i] = 1+i*i*i;

	// convert to DMatrix
	DMatrixHandle h_train[1];
	XGDMatrixCreateFromMat((float *) train, rows, cols, -1, &h_train[0]);

	// load the labels
	XGDMatrixSetFloatInfo(h_train[0], "label", train_labels, rows);

	// read back the labels, just a sanity check
	bst_ulong bst_result;
	const float *out_floats;
	XGDMatrixGetFloatInfo(h_train[0], "label" , &bst_result, &out_floats);
	for (unsigned int i=0;i<bst_result;i++)
   		std::cout << "label[" << i << "]=" << out_floats[i] << std::endl;

// create the booster and load some parameters

    BoosterHandle h_booster;
    XGBoosterCreate(h_train, 1, &h_booster);
    XGBoosterSetParam(h_booster, "booster", "gbtree");
    XGBoosterSetParam(h_booster, "objective", "reg:linear");
    XGBoosterSetParam(h_booster, "max_depth", "5");
    XGBoosterSetParam(h_booster, "eta", "0.1");
    XGBoosterSetParam(h_booster, "min_child_weight", "1");
    XGBoosterSetParam(h_booster, "subsample", "0.5");
    XGBoosterSetParam(h_booster, "colsample_bytree", "1");
    XGBoosterSetParam(h_booster, "num_parallel_tree", "1");

    // perform 200 learning iterations
    for (int iter=0; iter<200; iter++)
        XGBoosterUpdateOneIter(h_booster, iter, h_train[0]);

// predict

    const int sample_rows = 5;
    float test[sample_rows][cols];
    for (int i=0;i<sample_rows;i++)
        for (int j=0;j<cols;j++)
            test[i][j] = (i+1) * (j+1);
    DMatrixHandle h_test;
    XGDMatrixCreateFromMat((float *) test, sample_rows, cols, -1, &h_test);
    bst_ulong out_len;
    const float *f;
    XGBoosterPredict(h_booster, h_test, 0,0,&out_len,&f);

    for (unsigned int i=0;i<out_len;i++)
        std::cout << "prediction[" << i << "]=" << f[i] << std::endl;

    for (unsigned int i=0;i<out_len;i++)
        std::cout << "prediction[" << i << "]=" << f[i] << std::endl;
    XGDMatrixFree(h_train[0]);
    XGDMatrixFree(h_test);
    XGBoosterFree(h_booster);

**Comment by aldanor** [comment]
Seems like a simple `booster.dump_model()` and then `booster.load_model()` (both done in Python) fail as well, with `BoostLearner: wrong model format` error.

Has the model format changed in v0.7 or something?

**Comment by huangynn** [comment]
I have the same situation. 

when load model in python 

model._Booster.dump_model('./baxi_dadou.xgb')
booster = Booster()
booster.load_model('./baxi_dadou.xgb')
XGBoostError: [22:34:03] src/learner.cc:297: Check failed: fi->Read(&name_obj_[0], len) == len (41891 vs. 1030188649) BoostLearner: wrong model format

when load model in c++
LOG_IF(FATAL, 0 != XGBoosterLoadModel(handler_, file.c_str()))
                   << "Can not xgboost model from " << file;

![image](https://user-images.githubusercontent.com/12636388/37319544-7957c202-26aa-11e8-833e-ebf82185da02.png)

core dump

**Comment by hcho3** [comment]
@huangynn @aldanor According to [Python API doc](http://xgboost.readthedocs.io/en/latest/python/python_api.html), `dump_model()` generates _human-readable string representation_ of the model, which is useful for analyzing the model. If you want to save your model to use it for prediction task, you should use `save_model()` instead. **The `load_model()` function will not accept a text file generated by `dump_model()`.**

**Comment by aldanor** [comment]
@hcho3 it’s really unfortunate that you cannot save model to anything but a file. For example, in order to store 1000 models, I have to write and then read 1000 physical files, that just sounds wrong. Could `save_model()` and `load_model()` maybe save/load from bytestrings? In C++, it’s almost the same thing, you’ll just save/load to ostringstream/istringstream.

**Comment by khotilov** [comment]
@aldanor it is common to assume that "saving" means "saving to a file". To copy to a memory buffer, use `save_raw()` in python (used during pickling), `XGBoosterGetModelRaw` in C-API, and see https://github.com/dmlc/xgboost/blob/d5992dd88101abf2345095181504d003b4fc2c04/src/c_api/c_api.cc#L796 for the underlying C++ mechanics. R also allows getting a raw memory dump, and I'm fairly sure Java/Scala interfaces have it too.

**Comment by huangynn** [comment]
@hcho3 thank you, I've found that~ but I think there should be a function used for load  human-readable model. Something like save_raw, load_raw, save_readable, load_readable.

**Comment by AndrewHannigan** [comment]
@huangynn I disagree.  If the intention is to load the model later, you should be writing a machine-readable file.  There are additional details in the machine-readable file that you may not care about seeing in human readable file but which are necessary for loading model.
