### ISSUE TITLE
Suggestion: Add PR (Precision recall) evaluation for your eval_metrics 

### ISSUE THREAD

**Issue by eranop** [dmlc/xgboost#2910]
There's not much to elaborate.
We've gotten so used to the AUC ROC curves which will give a misguiding result for unbalanced data.

Precision Recall solves this and should be added to your eval_metrics.

**Comment by pommedeterresautee** [comment]
These metrics can easily be defined outside of Xgboost package (indeed they are in mlr or scikit). Closing this issue.
