### ISSUE TITLE
Monotonic Constraints in R are not applied

### ISSUE THREAD

**Issue by paulsendavidjay** [dmlc/xgboost#2913]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System: CENTOS 7

Package used (python/R/jvm/C++): R

`xgboost` version used: 6.4.6

If you are using R package, please provide

1. The R `sessionInfo()`
R version 3.3.3 (2017-03-06)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  splines   stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Matrix_1.2-8    gbm_2.1.3       lattice_0.20-34 survival_2.40-1 pdp_0.6.0       xgboost_0.6.4.6

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.11.4    grid_3.3.3        plyr_1.8.4        gtable_0.2.0      magrittr_1.5      scales_0.4.1     
 [7] ggplot2_2.2.1     rlang_0.1.1       stringi_1.1.5     lazyeval_0.2.0    data.table_1.10.4 tools_3.3.3      
[13] munsell_0.4.3     colorspace_1.3-2  knitr_1.16        gridExtra_2.2.1   tibble_1.3.1     

2. The command to install `xgboost` if you are not installing from source
install.packages("xgboost", repos = "http://dmlc.ml/drat/", type = "source")

# COMMENT
The following R code replicates the example given in the monotonic constraints tutorial. 
gbm package monotonic constraints are shown using plot.gbm() and pdp::partial() functions to demonstrate parity.
xgboost pdp's do not show parity. This demonstration is consistent with findings in another set of data that led to this example.

```{r}
######################################################
# XGBOOST MONOTONICITY TEST
# install.packages("pdp") # for generating partial dependencies across model objects
# install.packages("gbm")
# install.packages("Matrix")

library(xgboost)
library(gbm)
library(Matrix)
library(pdp) 

# INITIALIZE VALUES
n <- 1000
set.seed(111)
x1 <- runif(n)
x2 <- runif(n)

# CREATE Y USING FORMULA IN TUTORIAL 
# http://xgboost.readthedocs.io/en/latest/tutorials/monotonic.html
# y=5x1+sin(10πx1)−5x2−cos(10πx2)+N(0,0.01)
v1 <- 5*x1
v2 <- sin(10*pi*x1)
v3 <- -5*x2
v4 <- -1*cos(10*pi*x2)
set.seed(111)
noise <- rnorm(n, 0, 0.01)

y <- v1 + v2 + v3 + v4 + noise

df <- data.frame(y, x1, x2)
monotonic_constraints = c(1,-1)

sparse_matrix <- sparse.model.matrix(~ . -1, 
                                     data = df)

sparse_matrix@Dimnames[[2]]
# [1] "y"  "x1" "x2"

#############################
# RUN XGBOOST MODEL
set.seed(1)
bst <- xgboost(data = sparse_matrix[,2:3],
               label = y,
               max.depth = 3,
               eta = 1,
               missing = 9999901,
               nthread = 4,
               monotone_constraints = monotonic_constraints,
               nround = 100,
               objective = "reg:linear",
               save_period = NULL)

# PLOT USING PARTIAL()
plot(partial(bst,
             pred.var = "x1",
             train = df,
             grid.resolution = 100, trim.outliers = FALSE, prob = TRUE, rug = TRUE, plot = TRUE))
```
_Should be positive_
![image](https://user-images.githubusercontent.com/6913879/33512619-b5671156-d6e8-11e7-977d-ab0d9acce5f2.png)

```{r}
plot(partial(bst,
             pred.var = "x2",
             train = df,
             grid.resolution = 100, trim.outliers = FALSE, prob = TRUE, rug = TRUE, plot = TRUE))
```
_Should be negative_
![image](https://user-images.githubusercontent.com/6913879/33512615-a25c15b6-d6e8-11e7-940e-de18d8a1fcf4.png)

```{r}
#############################
# COMPARE TO GBM PACKAGE
test.gbm <- gbm(y ~ .,
                  data = df, 
                  var.monotone = monotonic_constraints, 
                  distribution = "gaussian", 
                  bag.fraction = 0.66, 
                  shrinkage = 0.05, 
                  n.minobsinnode = 50, 
                  n.trees = 100,
                  cv.folds = 5, 
                  keep.data = FALSE)

# PLOT USING PLOT.GBM
plot(test.gbm, "x1") 
```
_is positive_
![image](https://user-images.githubusercontent.com/6913879/33461581-eb5f99ba-d5e7-11e7-8b57-3c47c7b33e6d.png)

```{r}
plot(test.gbm, "x2") # is negative
```
_is negative_
![image](https://user-images.githubusercontent.com/6913879/33461585-f309046c-d5e7-11e7-8398-5f89bb249063.png)

```{r}
# PLOT USING PARTIAL() - CONFIRM PARTIAL IS PLOTTING APPROPRIATELY
plot(partial(test.gbm,
             pred.var = "x1",
             train = df,
             grid.resolution = 100, trim.outliers = FALSE, prob = TRUE, rug = TRUE, plot = TRUE, n.trees = 100))
```
_is positive_
![image](https://user-images.githubusercontent.com/6913879/33461597-02801c28-d5e8-11e7-9f1c-8ea61019a426.png)
```{r}
plot(partial(test.gbm,
             pred.var = "x2",
             train = df,
             grid.resolution = 100, trim.outliers = FALSE, prob = TRUE, rug = TRUE, plot = TRUE, n.trees = 100))
```
_is negative_
![image](https://user-images.githubusercontent.com/6913879/33461603-0ea85e5c-d5e8-11e7-9eee-0cd5323450b4.png)

**Comment by khotilov** [comment]
Do not pass `y` with your sparse_matrix data matrix to xgboost. What the constraint `c(1,-1)` does here is that it imposes a positive constraint on y, a negative one on x1, and an implicit positive constraint on x2.

**Comment by paulsendavidjay** [comment]
Thanks. I edited the data input as you suggest, updating above code and plots. PDPs are still not in the correct direction.

**Comment by khotilov** [comment]
```R
set.seed(1)
bst <- xgboost(data = sparse_matrix[,2:3],
               label = y,
               max.depth = 3,
               eta = 0.1,
               nthread = 4,
               monotone_constraints = monotonic_constraints,
               nround = 100,
               objective = "reg:linear")
plot(partial(bst,
             pred.var = "x1",
             train = df[,2:3],
             grid.resolution = 100, trim.outliers = FALSE, prob = TRUE, rug = TRUE, plot = TRUE))
plot(partial(bst,
             pred.var = "x2",
             train = df[,2:3],
             grid.resolution = 100, trim.outliers = FALSE, prob = TRUE, rug = TRUE, plot = TRUE))
```
![image](https://user-images.githubusercontent.com/1613551/33512778-5a41cf4c-d6fb-11e7-9037-5f6dc6ad3ffa.png)
![image](https://user-images.githubusercontent.com/1613551/33512779-6389283e-d6fb-11e7-8941-e14b69269790.png)

**Comment by paulsendavidjay** [comment]
@khotilov , thank you.
