### ISSUE TITLE
Setting n_gpus > 1 fails.  Used NCCL to compile

### ISSUE THREAD

**Issue by robhawkins** [dmlc/xgboost#2915]
## Environment info
OS: Ubuntu 16.04, gcc 5.4.0, python 3.6.3 (anaconda), xgboost=source/latest

commit hash: 9fbeeea46e1d00547090d5bd7236fba8854b0869

Logs: see below

## Steps to reproduce
1. Install NCCL
    * Follow Nvidia's [guide](http://docs.nvidia.com/deeplearning/sdk/nccl-install-guide/index.html#debian) for 16.04.  It doesn't mention where to download one needed .deb file, so:
    * Download `nvidia-machine-learning-repo-ubuntu1604_1.0.0-1_amd64.deb` from [here](http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64/), assuming you have 16.04
    * Complete the steps in the guide
2. Follow the [build instructions](http://xgboost.readthedocs.io/en/latest/build.html#building-with-gpu-support) and add the USE_NCCL parameter
    * `cmake .. -DUSE_CUDA=ON -DUSE_NCCL=ON`
3. In the code, supply the appropriate parameters as [mentioned on this page](http://xgboost.readthedocs.io/en/latest/gpu/) and [this issue](https://github.com/dmlc/xgboost/issues/2819#issuecomment-341791611)

        params = {'tree_method':'gpu_hist', 'n_gpus': 2, 'eta': 0.01, ' subsample': 0.7,
                      'colsample_bytree': 0.8, 'max_depth':3, 'min_child_weight':3,
                      'objective': 'binary:logistic', 'seed':0} 

        cv_xgb = xgb.cv(params = params, dtrain = train_dmat,
                       num_boost_round = 3000, nfold = 5, metrics = ['error'],
                       early_stopping_rounds = 100)

If I set n_gpus to more than 1, I get this error:

`Check failed: device_ordinals.size() == 1 (2 vs. 1) XGBoost must be compiled with NCCL to use more than one GPU`

I did reinstall the python XGBoost tools from source after rebuilding XGBoost with NCCL turned on.

## What have you tried?

1. Tried rebuilding and reinstalling both XGBoost and python tools
2. Restarted Jupyter Notebook

**Comment by meetdave06** [comment]
I am also facing the same issue. I successfully rebuilt XGBoost with NCCL on. And also re-installed python-package from source. Still, it doesn't work and throws the same error

`Check failed: device_ordinals.size() == 1 (3 vs. 1) XGBoost must be compiled with NCCL to use more than one GPU`

Any resolution?

**Comment by civilinformer** [comment]
Did you do a make clean in the parent directory first? Did you make sure the python package was completely uninstalled (could take several attempts to uninstall it). Also make sure you are installing into the right python installation, e.g., picking the right venv.
