### ISSUE TITLE
xgboost4j-spark with NaN input caused error

### ISSUE THREAD

**Issue by jiang1983** [dmlc/xgboost#2917]
when I input data with NaN value to xgboost4j-spark caused error below:
[16:17:10] dmlc-core/include/dmlc/logging.h:235: [16:17:10] src/tree/updater_histmaker.cc:301: Check failed: (istart) != (hist.size) 
terminate called after throwing an instance of 'dmlc::Error'
  what():  [16:17:10] src/tree/updater_histmaker.cc:301: Check failed: (istart) != (hist.size) 

How can I train with dataset contains NaN value?

**Comment by hrxu01** [comment]
I might meet same error!

**Comment by superbobry** [comment]
Are you using the master version?

**Comment by jiang1983** [comment]
@CodingCat

**Comment by jiang1983** [comment]
@superbobry  yes,the input is LabledPoint with NaN value in features
