### ISSUE TITLE
no difference between missing value with 0 or with-999

### ISSUE THREAD

**Issue by 176coding** [dmlc/xgboost#2921]
Hi, all, I tried 4 experience to see the differences between missing value with 0 or with-999
I used libsvm data format, and there were some features with value=0, so I tried:

1. no feature value=0 in libsvm dataset + dmatrix with missing value=-999
2. no  feature value=0 in libsvm dataset + dmatrix with missing value=0
3. with feature value=0 in libsvm dataset + dmatrix with missing value=-999
4. with feature value=0 in libsvm dataset + dmatrix with missing value=0

but there were no difference from the log result, why?

**Comment by Laurae2** [comment]
libsvm dataset have missing values by default, so these missing values are already defined in the sparse dataset (missing values are already missing in the dataset). You can't override it without changing your dataset to a dense file (such as CSV).
