### ISSUE TITLE
Failure to run xgboost program in spark

### ISSUE THREAD

**Issue by momo1986** [dmlc/xgboost#2922]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System:Linux

Compiler:gcc

Package used (python/R/jvm/C++):

`xgboost` version used:xgboost4j-0.7.jar,xgboost-spark-4j-07.jar

Hello, guys
I used the xgboost-spark packages in my server. The jars-packages is imported.

> spark-submit --class com.xianjinkd.riskcontrol.access.algorithm.XgboostNew --jars /home/yanjun/xgboost/jvm-packages/xgboost4j-spark/target/xgboost4j-spark-0.7.jar,/home/yanjun/xgboost/jvm-packages/xgboost4j/target/xgboost4j-0.7.jar --master local[4] XgboostNew.jar file:///home/yanjun/sparkproject/XgboostTrain/train_unicode.txt ile:///home/yanjun/sparkproject/XgboostTrain/test_unicode.txt
> start running example to start from a initial prediction
> 17/12/04 11:39:14 ERROR NativeLibLoader: failed to load library from both native path and jar
> 17/12/04 11:39:14 ERROR DMatrix: Failed to load native library
> java.io.FileNotFoundException: File /lib/libxgboost4j.so was not found inside JAR.
> 	at ml.dmlc.xgboost4j.java.NativeLibLoader.createTempFileFromResource(NativeLibLoader.java:121)
> 	at ml.dmlc.xgboost4j.java.NativeLibLoader.loadLibraryFromJar(NativeLibLoader.java:64)
> 	at ml.dmlc.xgboost4j.java.NativeLibLoader.smartLoad(NativeLibLoader.java:152)
> 	at ml.dmlc.xgboost4j.java.NativeLibLoader.initXGBoost(NativeLibLoader.java:40)
> 	at ml.dmlc.xgboost4j.java.XGBoostJNI.<clinit>(XGBoostJNI.java:34)
> 	at ml.dmlc.xgboost4j.java.DMatrix.<init>(DMatrix.java:68)
> 	at com.xianjinkd.riskcontrol.access.algorithm.XgboostNew.main(XgboostNew.java:18)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:606)
> 	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:738)
> 	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)
> 	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
> 	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
> 	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
> Exception in thread "main" java.lang.ExceptionInInitializerError
> 	at ml.dmlc.xgboost4j.java.DMatrix.<init>(DMatrix.java:68)
> 	at com.xianjinkd.riskcontrol.access.algorithm.XgboostNew.main(XgboostNew.java:18)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:606)
> 	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:738)
> 	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)
> 	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
> 	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
> 	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
> Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: File /lib/libxgboost4j.so was not found inside JAR.
> 	at ml.dmlc.xgboost4j.java.XGBoostJNI.<clinit>(XGBoostJNI.java:37)
> 	... 11 more
> Caused by: java.io.FileNotFoundException: File /lib/libxgboost4j.so was not found inside JAR.
> 	at ml.dmlc.xgboost4j.java.NativeLibLoader.createTempFileFromResource(NativeLibLoader.java:121)
> 	at ml.dmlc.xgboost4j.java.NativeLibLoader.loadLibraryFromJar(NativeLibLoader.java:64)
> 	at ml.dmlc.xgboost4j.java.NativeLibLoader.smartLoad(NativeLibLoader.java:152)
> 	at ml.dmlc.xgboost4j.java.NativeLibLoader.initXGBoost(NativeLibLoader.java:40)
> 	at ml.dmlc.xgboost4j.java.XGBoostJNI.<clinit>(XGBoostJNI.java:34)
> 	... 11 more

It said, "java.io.FileNotFoundException: File /lib/libxgboost4j.so was not found inside JAR.". How can I resolve the issue?
Thanks & Regards!
Momo

**Comment by superbobry** [comment]
Have you compiled the JAR on Linux? Can you do

```
jar tf xgboost4j-0.7.jar
```

**Comment by momo1986** [comment]
@superbobry , I have tried the method, the problem still exists

**Comment by superbobry** [comment]
Sorry for not being clear. This is not a method of solving the problem, but rather a method of diagnosing it. Can you post the output of the command in this issue?

**Comment by momo1986** [comment]
I have added libxgboost4j.so in jar-package and reexport, still exists the problem
