### ISSUE TITLE
Proposal: 0.7 release of XGBoost

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#2925]
Recently, it came to our attention that the python package of XGBoost on PyPI is quite outdated [1,2,3,4,5]. The last release (0.6) came out in July 29, 2016. Not only the package is outdated, `pip install` often fails because of compilation issues.

As a new maintainer of the PyPI package, I propose the following to rectify the situation.

1. Make a new release, **0.7** using today's commit.
2. Regularly publish minor updates, e.g. 0.7.1, 0.7.2, and so forth. Minor updates shall accommodate bug fixes and minor changes.
3. Publish major updates, e.g. 0.8, 0.9, etc. whenever new major features are added.
4. Provide **pre-built binary wheels** on PyPI, so that ` pip install` does not involve compilation. My plan is to first provide binary wheels for CPU-only code. The GPU module would be provided as a separate wheel, and it will have to wait until a GPU-capable build system is set up.
5. (optional) Create a "nightly build" for each new commit in master.

Over next two weeks, I will be seeking feedback for this decision.

[1] #2906
[2] #2893
[3] #2887
[4] #1501
[5] #2902

**Comment by tqchen** [comment]
Sounds great

**Comment by Seanspt** [comment]
jvm-packages provides great integration with spark and the dataframe-based apis are easy to use.
Will these features be included in the coming release?
And it would be great to have it in maven central repository.

**Comment by cinqs** [comment]
Any progress so far, please? nevertheless I built my own version, I am still watching your new releases. Still under discussion?

**Comment by hcho3** [comment]
@cinqs Sorry for the delay. I've gone ahead and made a pull request to make the 0.7 release. Once the PR is merged, I'll upload the binary wheels.

**Comment by hcho3** [comment]
Today, the 0.7 release is out and ready. I'm now working to upload binary wheels. Universal Linux binaries (as documented in [PEP 513](https://www.python.org/dev/peps/pep-0513/)) are quite challenging to get right.

**Comment by aldanor** [comment]
Could sdist be uploaded as well (so we can build it on conda-forge).

**Comment by hcho3** [comment]
See #2996.

**Comment by munro** [comment]
One of the major first steps to alleviating the troubles people trying to do `pip install -r requirements.txt` could be making `python setup.py install` compile the package.  Then from there we could cut releases & include prebuilt binaries.

Once that is done, then at people could immediately start installing whatever hash of xgboost via requirements.txt (or fork which would be really nice).

```
# requirements.txt
git+https://github.com/dmlc/xgboost.git@SOME_HASH#egg=xgboost&subdirectory=python-package
```

I created a ticket for implementing this here #3069

**Comment by michael-robbins** [comment]
How's this going? Would be awesome to get some prebuilt wheels uploaded for py3!
