### ISSUE TITLE
updater_gpu_hist.cu(673): an illegal memory access was encountered

### ISSUE THREAD

**Issue by ccoocode** [dmlc/xgboost#2930]
## Environment info
Operating System:Ubuntu 16.04.3 LTS
Package used: python 2.7.13
`xgboost` version used: 0.6
cuda version:V8.0.61

param = {'booster':'gbtree','max_depth': 100, 'eta': 0.05, 'silent': 1, 'objective': 'multi:softmax', \
                 'num_class':18,'tree_method':'gpu_hist','gpu_id'=0}
[17:53:58] 1269635x99491 matrix with 69583530 entries loaded from /data2/wgs2/PycharmProjects/meipai-medias-tagging-v1.0.0/data/meipai.mv.tag1.classify.feature.train
dtrain is a 1269635x99491 matrix

My problem is when i run # xgb.train(param, dtrain) method, i get an error:

xgboost.core.XGBoostError: [17:54:06] /data2/wgs2/tool/xgboost/src/tree/updater_gpu_hist.cu:521: GPU plugin exception: /data2/wgs2/tool/xgboost/src/tree/updater_gpu_hist.cu(673): an illegal memory access was encountered

Stack trace returned 10 entries:
[bt] (0) /data2/wgs2/anaconda2/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/libxgboost.so(_ZN4dmlc15LogMessageFatalD2Ev+0x29) [0x7fe16a23dfd9]
[bt] (1) /data2/wgs2/anaconda2/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/libxgboost.so(_ZN7xgboost4tree12GPUHistMaker6UpdateERKSt6vectorINS_6detail18bst_gpair_internalIfEESaIS5_EEPNS_7DMatrixERKS2_IPNS_7RegTreeESaISD_EE+0x253) [0x7fe16a465ca3]
[bt] (2) /data2/wgs2/anaconda2/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/libxgboost.so(_ZN7xgboost3gbm6GBTree13BoostNewTreesERKSt6vectorINS_6detail18bst_gpair_internalIfEESaIS5_EEPNS_7DMatrixEiPS2_ISt10unique_ptrINS_7RegTreeESt14default_deleteISD_EESaISG_EE+0x9bd) [0x7fe16a26806d]
[bt] (3) /data2/wgs2/anaconda2/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/libxgboost.so(_ZN7xgboost3gbm6GBTree7DoBoostEPNS_7DMatrixEPSt6vectorINS_6detail18bst_gpair_internalIfEESaIS7_EEPNS_11ObjFunctionE+0x477) [0x7fe16a268da7]
[bt] (4) /data2/wgs2/anaconda2/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/libxgboost.so(_ZN7xgboost11LearnerImpl13UpdateOneIterEiPNS_7DMatrixE+0x34e) [0x7fe16a280e4e]
[bt] (5) /data2/wgs2/anaconda2/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/libxgboost.so(XGBoosterUpdateOneIter+0x27) [0x7fe16a3bc937]
[bt] (6) /data2/wgs2/anaconda2/lib/python2.7/lib-dynload/_ctypes.so(ffi_call_unix64+0x4c) [0x7fe17cbde57c]
[bt] (7) /data2/wgs2/anaconda2/lib/python2.7/lib-dynload/_ctypes.so(ffi_call+0x1f5) [0x7fe17cbddcd5]
[bt] (8) /data2/wgs2/anaconda2/lib/python2.7/lib-dynload/_ctypes.so(_ctypes_callproc+0x3e6) [0x7fe17cbd5376]
[bt] (9) /data2/wgs2/anaconda2/lib/python2.7/lib-dynload/_ctypes.so(+0x9db3) [0x7fe17cbccdb3]

terminate called after throwing an instance of 'thrust::system::system_error'
  what():  function_attributes(): after cudaFuncGetAttributes: an illegal memory access was encountered

**Comment by StudyExchange** [comment]
@ccoocode Do you resolve this problem?
