### ISSUE TITLE
[jvm-packages] Booster.loadModel() should be public static, not just static

### ISSUE THREAD

**Issue by logicators** [dmlc/xgboost#2932]
Hi,

I am serializing models using booster.saveModel(outputStream) which seems to work fine. But I am unable to load these models later since the loadModel() method is not public.

## Environment info
Operating System:

Compiler:

Package used (python/R/jvm/C++):

`xgboost` version used:

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`)
2. Logs will be helpful (If logs are large, please upload as attachment).

If you are using jvm package, please 

1. add [jvm-packages] in the title to make it quickly be identified
2. the gcc version and distribution

If you are using python package, please provide

1. The python version and distribution
2. The command to install `xgboost` if you are not installing from source

If you are using R package, please provide

1. The R `sessionInfo()`
2. The command to install `xgboost` if you are not installing from source

## Steps to reproduce

1.
2.
3.

## What have you tried?

1.
2.
3.

**Comment by CodingCat** [comment]
looks like a problem, do you mind filing a PR for this?
