### ISSUE TITLE
Core dumped: src/common/hist_util.cc:140: Check failed: cbegin != cend

### ISSUE THREAD

**Issue by pseudotensor** [dmlc/xgboost#2943]
@hcho3 @RAMitchell 
```
import xgboost as xgb
import numpy as np
nan = np.nan
params = {'missing': nan, 'tree_method': 'hist'}
model = xgb.XGBRegressor(**params)

Xuse = [[6.18827160e+05,1.73000000e+02],[  6.37345679e+05     ,         nan], [  6.38888889e+05  ,            nan], [  6.28086420e+05           ,   nan]]
yuse = [ 1000000.,        0.,        0.,   500000.]
wuse = [0, 0, 1, 0]

model.fit(Xuse, yuse, sample_weight = wuse)
```

Fails with hist or gpu_hist.  If I remove the sample_weight, it runs without error.

**Comment by hcho3** [comment]
This is interesting. Could be because zero-weight instances arw simply removed from the row set.

**Comment by pseudotensor** [comment]
This still isn't fixed.  Still happens quite often and reduced repro example is give above.

**Comment by hcho3** [comment]
@pseudotensor In the example you provided, **the quantile sketcher fails to produce any quantile for the second feature**. The histogram tree updater fails to function without a proper list of quantiles for each feature. With three zero-weight instances, there isn't enough information to extract appropriate quantiles.

> Still happens quite often and reduced repro example is give above.
Does this problem occur in a real-world dataset? If so, we may have to add a "fail-safe" mode to the histogram updater: whenever the quantile sketcher fails, simply do an exhaustive scan to get quantiles.

**Comment by pseudotensor** [comment]
Yes, but often (in my case) as a product of other operations on some real data set.  If there's a way to know ahead of time if this will happen, that's another solution.  But best to have a back-up.

**Comment by hcho3** [comment]
I'd suggest that we add a check in the quantile extraction code that performs an exhaustive scan for features without quantiles. It might be tricky to handle edge cases, such as effectively empty columns (due to zero weights).

**Comment by pseudotensor** [comment]
Sounds good.  Rory said you are available for xgboost things currently?  We hit this still sometimes.  Would be nice if fixed.

**Comment by hcho3** [comment]
@pseudotensor Treelite is my main line of work at this moment, but I do work on XGBoost as my bandwidth allows.

**Comment by hcho3** [comment]
Will try to tackle when refactoring quantile sketch code

**Comment by pseudotensor** [comment]
Ya, in limit of constant columns as one of the inputs, this is error.
