### ISSUE TITLE
[jvm-packages] train and test metrics are exactly the same even when trainTestRatio is set to 0.75 when training with spark

### ISSUE THREAD

**Issue by gaofan0905** [dmlc/xgboost#2945]
## Environment info
Operating System: Mac

Compiler:
gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

Package used (python/R/jvm/C++):JVM

`xgboost` version used: 0.7

## Steps to reproduce

I am call training the data using spark with following code:

    val trainedModel = XGBoost.trainWithDataFrame(
      trainingData,
      trainingParams,
      // num of trees in the model
      round = treeNum,
      // the number of xgboost workers, make it equals to number of trainingData RDD
      // so that when doing the group ranking, the groupData won't be messed up
      nWorkers = partitionNum,
      useExternalMemory = true)
with following default params

  // default training parameters
  val DEFAULT_TRAIN_PARAM: Map[String, Any] = List(
    "eta" -> 0.1f,
    "max_depth" -> 10,
    "silent" -> 1,
    "objective" -> "reg:linear",
    "trainTestRatio" -> "0.75"
  ).toMap

But in the training output, the train_rmse and test_rmse are always the same no matter how many rounds it runs
[INFO] [12/12/2017 17:27:40.819] [RabitTracker-akka.actor.default-dispatcher-9] [akka://RabitTracker/user/Handler] [962]	train-rmse:0.087132	test-rmse:0.087132
[INFO] [12/12/2017 17:27:40.828] [RabitTracker-akka.actor.default-dispatcher-9] [akka://RabitTracker/user/Handler] [963]	train-rmse:0.087132	test-rmse:0.087132
[INFO] [12/12/2017 17:27:40.838] [RabitTracker-akka.actor.default-dispatcher-9] [akka://RabitTracker/user/Handler] [964]	train-rmse:0.087131	test-rmse:0.087131
[INFO] [12/12/2017 17:27:40.847] [RabitTracker-akka.actor.default-dispatcher-2] [akka://RabitTracker/user/Handler] [965]	train-rmse:0.087131	test-rmse:0.087131
[INFO] [12/12/2017 17:27:40.859] [RabitTracker-akka.actor.default-dispatcher-11] [akka://RabitTracker/user/Handler] [966]	train-rmse:0.087130	test-rmse:0.087130
[INFO] [12/12/2017 17:27:40.874] [RabitTracker-akka.actor.default-dispatcher-9] [akka://RabitTracker/user/Handler] [967]	train-rmse:0.087130	test-rmse:0.087130
[INFO] [12/12/2017 17:27:40.885] [RabitTracker-akka.actor.default-dispatcher-11] [akka://RabitTracker/user/Handler] [968]	train-rmse:0.087129	test-rmse:0.087129
[INFO] [12/12/2017 17:27:40.894] [RabitTracker-akka.actor.default-dispatcher-9] [akka://RabitTracker/user/Handler] [969]	train-rmse:0.087129	test-rmse:0.087129
[INFO] [12/12/2017 17:27:40.904] [RabitTracker-akka.actor.default-dispatcher-2] [akka://RabitTracker/user/Handler] [970]	train-rmse:0.087128	test-rmse:0.087128
[INFO] [12/12/2017 17:27:40.914] [RabitTracker-akka.actor.default-dispatcher-2] [akka://RabitTracker/user/Handler] [971]	train-rmse:0.087127	test-rmse:0.087127
[INFO] [12/12/2017 17:27:40.926] [RabitTracker-akka.actor.default-dispatcher-9] [akka://RabitTracker/user/Handler] [972]	train-rmse:0.087126	test-rmse:0.087126
[INFO] [12/12/2017 17:27:40.942] [RabitTracker-akka.actor.default-dispatcher-10] [akka://RabitTracker/user/Handler] [973]	train-rmse:0.087125	test-rmse:0.087125
[INFO] [12/12/2017 17:27:40.952] [RabitTracker-akka.actor.default-dispatcher-10] [akka://RabitTracker/user/Handler] [974]	train-rmse:0.087124	test-rmse:0.087124
[INFO] [12/12/2017 17:27:40.962] [RabitTracker-akka.actor.default-dispatcher-10] [akka://RabitTracker/user/Handler] [975]	train-rmse:0.087123	test-rmse:0.087123
[INFO] [12/12/2017 17:27:40.974] [RabitTracker-akka.actor.default-dispatcher-11] [akka://RabitTracker/user/Handler] [976]	train-rmse:0.087123	test-rmse:0.087123
[INFO] [12/12/2017 17:27:40.983] [RabitTracker-akka.actor.default-dispatcher-2] [akka://RabitTracker/user/Handler] [977]	train-rmse:0.087123	test-rmse:0.087123
[INFO] [12/12/2017 17:27:40.998] [RabitTracker-akka.actor.default-dispatcher-10] [akka://RabitTracker/user/Handler] [978]	train-rmse:0.087122	test-rmse:0.087122
[INFO] [12/12/2017 17:27:41.011] [RabitTracker-akka.actor.default-dispatcher-10] [akka://RabitTracker/user/Handler] [979]	train-rmse:0.087121	test-rmse:0.087121
[INFO] [12/12/2017 17:27:41.022] [RabitTracker-akka.actor.default-dispatcher-2] [akka://RabitTracker/user/Handler] [980]	train-rmse:0.087120	test-rmse:0.087120
[INFO] [12/12/2017 17:27:41.032] [RabitTracker-akka.actor.default-dispatcher-2] [akka://RabitTracker/user/Handler] [981]	train-rmse:0.087118	test-rmse:0.087118
[INFO] [12/12/2017 17:27:41.041] [RabitTracker-akka.actor.default-dispatcher-2] [akka://RabitTracker/user/Handler] [982]	train-rmse:0.087117	test-rmse:0.087117
[INFO] [12/12/2017 17:27:41.051] [RabitTracker-akka.actor.default-dispatcher-2] [akka://RabitTracker/user/Handler] [983]	train-rmse:0.087117	test-rmse:0.087117
[INFO] [12/12/2017 17:27:41.068] [RabitTracker-akka.actor.default-dispatcher-2] [akka://RabitTracker/user/Handler] [984]	train-rmse:0.087116	test-rmse:0.087116
[INFO] [12/12/2017 17:27:41.080] [RabitTracker-akka.actor.default-dispatcher-9] [akka://RabitTracker/user/Handler] [985]	train-rmse:0.087115	test-rmse:0.087115
[INFO] [12/12/2017 17:27:41.089] [RabitTracker-akka.actor.default-dispatcher-2] [akka://RabitTracker/user/Handler] [986]	train-rmse:0.087113	test-rmse:0.087113
[INFO] [12/12/2017 17:27:41.100] [RabitTracker-akka.actor.default-dispatcher-2] [akka://RabitTracker/user/Handler] [987]	train-rmse:0.087112	test-rmse:0.087112
[INFO] [12/12/2017 17:27:41.115] [RabitTracker-akka.actor.default-dispatcher-10] [akka://RabitTracker/user/Handler] [988]	train-rmse:0.087111	test-rmse:0.087111
[INFO] [12/12/2017 17:27:41.133] [RabitTracker-akka.actor.default-dispatcher-2] [akka://RabitTracker/user/Handler] [989]	train-rmse:0.087111	test-rmse:0.087111
[INFO] [12/12/2017 17:27:41.152] [RabitTracker-akka.actor.default-dispatcher-11] [akka://RabitTracker/user/Handler] [990]	train-rmse:0.087110	test-rmse:0.087110
[INFO] [12/12/2017 17:27:41.163] [RabitTracker-akka.actor.default-dispatcher-10] [akka://RabitTracker/user/Handler] [991]	train-rmse:0.087110	test-rmse:0.087110
[INFO] [12/12/2017 17:27:41.174] [RabitTracker-akka.actor.default-dispatcher-11] [akka://RabitTracker/user/Handler] [992]	train-rmse:0.087109	test-rmse:0.087109
[INFO] [12/12/2017 17:27:41.184] [RabitTracker-akka.actor.default-dispatcher-11] [akka://RabitTracker/user/Handler] [993]	train-rmse:0.087108	test-rmse:0.087108
[INFO] [12/12/2017 17:27:41.193] [RabitTracker-akka.actor.default-dispatcher-11] [akka://RabitTracker/user/Handler] [994]	train-rmse:0.087108	test-rmse:0.087108
[INFO] [12/12/2017 17:27:41.211] [RabitTracker-akka.actor.default-dispatcher-9] [akka://RabitTracker/user/Handler] [995]	train-rmse:0.087107	test-rmse:0.087107
[INFO] [12/12/2017 17:27:41.222] [RabitTracker-akka.actor.default-dispatcher-2] [akka://RabitTracker/user/Handler] [996]	train-rmse:0.087107	test-rmse:0.087107
[INFO] [12/12/2017 17:27:41.233] [RabitTracker-akka.actor.default-dispatcher-9] [akka://RabitTracker/user/Handler] [997]	train-rmse:0.087106	test-rmse:0.087106
[INFO] [12/12/2017 17:27:41.242] [RabitTracker-akka.actor.default-dispatcher-11] [akka://RabitTracker/user/Handler] [998]	train-rmse:0.087105	test-rmse:0.087105
[INFO] [12/12/2017 17:27:41.252] [RabitTracker-akka.actor.default-dispatcher-2] [akka://RabitTracker/user/Handler] [999]	train-rmse:0.087104	test-rmse:0.087104
[INFO] [12/12/2017 17:27:41.256] [RabitTracker-akka.actor.default-dispatcher-11] [akka://RabitTracker/user/Handler] Received shutdown signal from 0
17/12/12 17:28:16 INFO MemoryStore: Block rdd_9_0 stored as values in memory (estimated size 8.1 KB, free 908.2 MB)

## What have you tried?

1. I debug the code step by step and I can see in following code, testPoints and trainPoints are correctly generated.

private object Watches {

  def apply(
      params: Map[String, Any],
      labeledPoints: Iterator[XGBLabeledPoint],
      baseMarginsOpt: Option[Array[Float]],
      cacheFileName: String): Watches = {
    val trainTestRatio = params.get("trainTestRatio").map(_.toString.toDouble).getOrElse(1.0)
    val seed = params.get("seed").map(_.toString.toLong).getOrElse(System.nanoTime())
    val r = new Random(seed)
    val testPoints = mutable.ArrayBuffer.empty[XGBLabeledPoint]
    val trainPoints = labeledPoints.filter { labeledPoint =>
      val accepted = r.nextDouble() <= trainTestRatio
      if (!accepted) {
        testPoints += labeledPoint
      }

      accepted
    }
    val trainMatrix = new DMatrix(trainPoints, cacheFileName)
    val testMatrix = new DMatrix(testPoints.iterator, cacheFileName)
    r.setSeed(seed)
    for (baseMargins <- baseMarginsOpt) {
      val (trainMargin, testMargin) = baseMargins.partition(_ => r.nextDouble() <= trainTestRatio)
      trainMatrix.setBaseMargin(trainMargin)
      testMatrix.setBaseMargin(testMargin)
    }

    // TODO: use group attribute from the points.
    if (params.contains("groupData") && params("groupData") != null) {
      trainMatrix.setGroup(params("groupData").asInstanceOf[Seq[Seq[Int]]](
        TaskContext.getPartitionId()).toArray)
    }
    new Watches(train = trainMatrix, test = testMatrix)
  }
}

**Comment by CodingCat** [comment]
Did you try python based tracker?

**Comment by gaofan0905** [comment]
Seems on mac, I can only use scala tracker otherwise the trainning will fail after several rounds. Also  the results are still the same.

```
17/12/12 17:55:49 INFO BlockManager: Found block rdd_2_0 locally
[0]	train-rmse:0.339433	test-rmse:0.339433
[1]	train-rmse:0.308551	test-rmse:0.308551
[2]	train-rmse:0.281026	test-rmse:0.281026
[3]	train-rmse:0.256532	test-rmse:0.256532
[4]	train-rmse:0.234807	test-rmse:0.234807
[5]	train-rmse:0.215558	test-rmse:0.215558
[6]	train-rmse:0.198562	test-rmse:0.198562
[7]	train-rmse:0.183604	test-rmse:0.183604
[8]	train-rmse:0.170492	test-rmse:0.170492
[9]	train-rmse:0.159022	test-rmse:0.159022
[10]	train-rmse:0.149043	test-rmse:0.149043
[11]	train-rmse:0.140431	test-rmse:0.140431
[12]	train-rmse:0.132988	test-rmse:0.132988
[13]	train-rmse:0.126550	test-rmse:0.126550
[14]	train-rmse:0.121117	test-rmse:0.121117
[15]	train-rmse:0.116436	test-rmse:0.116436
[16]	train-rmse:0.112472	test-rmse:0.112472
[17]	train-rmse:0.109123	test-rmse:0.109123
[18]	train-rmse:0.106252	test-rmse:0.106252
[19]	train-rmse:0.103898	test-rmse:0.103898
[20]	train-rmse:0.101903	test-rmse:0.101903
[21]	train-rmse:0.100203	test-rmse:0.100203
[22]	train-rmse:0.098788	test-rmse:0.098788
[23]	train-rmse:0.097611	test-rmse:0.097611
[24]	train-rmse:0.096592	test-rmse:0.096592
[25]	train-rmse:0.095752	test-rmse:0.095752
[26]	train-rmse:0.095027	test-rmse:0.095027
[27]	train-rmse:0.094410	test-rmse:0.094410
[28]	train-rmse:0.093920	test-rmse:0.093920
[29]	train-rmse:0.093497	test-rmse:0.093497
[30]	train-rmse:0.093137	test-rmse:0.093137
[31]	train-rmse:0.092824	test-rmse:0.092824
[32]	train-rmse:0.092544	test-rmse:0.092544
[33]	train-rmse:0.092307	test-rmse:0.092307
[34]	train-rmse:0.092123	test-rmse:0.092123
[35]	train-rmse:0.091952	test-rmse:0.091952
[36]	train-rmse:0.091799	test-rmse:0.091799
[37]	train-rmse:0.091673	test-rmse:0.091673
[38]	train-rmse:0.091535	test-rmse:0.091535
[39]	train-rmse:0.091423	test-rmse:0.091423
[40]	train-rmse:0.091337	test-rmse:0.091337
[41]	train-rmse:0.091216	test-rmse:0.091216
[42]	train-rmse:0.091135	test-rmse:0.091135
[43]	train-rmse:0.091053	test-rmse:0.091053
[44]	train-rmse:0.090978	test-rmse:0.090978
[45]	train-rmse:0.090909	test-rmse:0.090909
[46]	train-rmse:0.090840	test-rmse:0.090840
[47]	train-rmse:0.090780	test-rmse:0.090780
[48]	train-rmse:0.090732	test-rmse:0.090732
[49]	train-rmse:0.090685	test-rmse:0.090685
17/12/12 17:55:50 INFO MemoryStore: Block rdd_9_0 stored as values in memory (estimated size 656.0 B, free 908.2 MB)
17/12/12 17:55:50 INFO BlockManagerInfo: Added rdd_9_0 in memory on 172.29.16.27:62700 (size: 656.0 B, free: 908.5 MB)
17/12/12 17:55:50 WARN Executor: 2 block locks were not released by TID = 0:
[rdd_9_0, rdd_2_0]
17/12/12 17:55:50 INFO Executor: Finished task 0.0 in stage 0.0 (TID 0). 2413 bytes result sent to driver
17/12/12 17:55:50 INFO TaskSetManager: Finished task 0.0 in stage 0.0 (TID 0) in 2695 ms on localhost (executor driver) (1/1)
17/12/12 17:55:50 INFO TaskSchedulerImpl: Removed TaskSet 0.0, whose tasks have all completed, from pool
17/12/12 17:55:50 INFO DAGScheduler: ResultStage 0 (foreachPartition at XGBoost.scala:339) finished in 2.715 s
17/12/12 17:55:50 INFO DAGScheduler: Job 0 finished: foreachPartition at XGBoost.scala:339, took 2.925865 s
17/12/12 17:55:53 INFO BlockManagerInfo: Removed broadcast_1_piece0 on 172.29.16.27:62700 in memory (size: 16.1 KB, free: 908.5 MB)
17/12/12 17:55:53 INFO RabitTracker: Tracker Process ends with exit code 1
17/12/12 17:55:53 INFO XGBoostSpark: Rabit returns with exit code 1
Exception in thread "main" ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.postTrackerReturnProcessing(XGBoost.scala:382)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainDistributed(XGBoost.scala:347)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostEstimator.train(XGBoostEstimator.scala:139)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostEstimator.train(XGBoostEstimator.scala:36)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:96)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainWithDataFrame(XGBoost.scala:194)
	at com.coupang.dmlc.xgboost.XGBoostTrain$.main(XGBoostTrain.scala:102)
	at com.coupang.dmlc.xgboost.XGBoostTrain.main(XGBoostTrain.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:743)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
17/12/12 17:55:53 INFO SparkContext: Invoking stop() from shutdown hook
17/12/12 17:55:53 INFO SparkUI: Stopped Spark web UI at http://172.29.16.27:4040
17/12/12 17:55:53 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
```

**Comment by gaofan0905** [comment]
Is it because the watch class in spark is using "test" instead of "eval"? In python code, we are using train/eval to construct the watch list.

```
private class Watches private(val train: DMatrix, val test: DMatrix) {

  def toMap: Map[String, DMatrix] = Map("train" -> train, "test" -> test)
    .filter { case (_, matrix) => matrix.rowNum > 0 }

  def size: Int = toMap.size

  def delete(): Unit = {
    toMap.values.foreach(_.delete())
  }

  override def toString: String = toMap.toString
} 
```

**Comment by gaofan0905** [comment]
@CodingCat, I did some research, if useExternalMemory is set to true, then in the following code

```
private object Watches {

  def apply(
      params: Map[String, Any],
      labeledPoints: Iterator[XGBLabeledPoint],
      baseMarginsOpt: Option[Array[Float]],
      cacheFileName: String): Watches = {
 ...
    val trainMatrix = new DMatrix(trainPoints, cacheFileName)
    val testMatrix = new DMatrix(testPoints.iterator, cacheFileName)
 ...
    new Watches(train = trainMatrix, test = testMatrix)
  }
}
```
trainMatrix and testMatrix will use the same cacheFileName, I guese what is happening is that trainMatix is created with real train data and create a cache file, and testMatix is created using the cache file instead of real test point data. 
I tried following 

    val trainMatrix = new DMatrix(trainPoints, String.valueOf(cacheFileName) + "_train")
    val testMatrix = new DMatrix(testPoints.iterator, String.valueOf(cacheFileName) + "_test")

and it works at lease for the training purpose. Not sure if this is the correct fix.

**Comment by superbobry** [comment]
@gaofan0905 good catch! This does sound like the cause of the issue and it's not on purpose. I will fix ASAP.

**Comment by CodingCat** [comment]
got it, I think in the original code, user cannot create a cache file in test phase.....
