### ISSUE TITLE
Failure 

### ISSUE THREAD

**Issue by momo1986** [dmlc/xgboost#2947]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System:Linux(CentOS6.5)

Compiler:gcc/g++

Package used (python/R/jvm/C++):jvm

`xgboost` version used:0.7

gcc-version: 7.1.0
cmake-version:3.10.0
## Steps to reproduce

1. make -j4(Successfully)
2.mvn -DskipTests install(Failure in xgboost4j compiling)

## What have you tried?

1.Set cmake
2.export CXX=clang-omp++

This is log:

> -- Found OpenMP_C: -fopenmp  
> -- Found OpenMP_CXX: -fopenmp  
> -- Found OpenMP_C: -fopenmp  
> -- Found OpenMP_CXX: -fopenmp  
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /usr/local/xgboost/build
> [  1%] Building CXX object CMakeFiles/rabit.dir/rabit/src/allreduce_base.cc.o
> In file included from /usr/local/xgboost/rabit/src/./../include/rabit/internal/../../dmlc/./logging.h:15,
>                  from /usr/local/xgboost/rabit/src/./../include/rabit/internal/../../dmlc/io.h:14,
>                  from /usr/local/xgboost/rabit/src/./../include/rabit/internal/../serializable.h:12,
>                  from /usr/local/xgboost/rabit/src/./../include/rabit/internal/engine.h:10,
>                  from /usr/local/xgboost/rabit/src/./allreduce_base.h:19,
>                  from /usr/local/xgboost/rabit/src/allreduce_base.cc:14:
> /usr/local/xgboost/rabit/src/./../include/rabit/internal/../../dmlc/././base.h:105: note: #pragma message: Will need g++-4.6 or higher to compile allthe features in dmlc-core, compile without c++0x, some features may be disabled
> In file included from /usr/local/xgboost/rabit/src/./../include/rabit/internal/../../dmlc/io.h:14,
>                  from /usr/local/xgboost/rabit/src/./../include/rabit/internal/../serializable.h:12,
>                  from /usr/local/xgboost/rabit/src/./../include/rabit/internal/engine.h:10,
>                  from /usr/local/xgboost/rabit/src/./allreduce_base.h:19,
>                  from /usr/local/xgboost/rabit/src/allreduce_base.cc:14:
> /usr/local/xgboost/rabit/src/./../include/rabit/internal/../../dmlc/./logging.h: In constructor ?.mlc::LogCheckError::LogCheckError()?.
> /usr/local/xgboost/rabit/src/./../include/rabit/internal/../../dmlc/./logging.h:66: error: ?.ullptr?.was not declared in this scope
> /usr/local/xgboost/rabit/src/./../include/rabit/internal/../../dmlc/./logging.h: In destructor ?.mlc::LogCheckError::~LogCheckError()?.
> /usr/local/xgboost/rabit/src/./../include/rabit/internal/../../dmlc/./logging.h:68: error: ?.ullptr?.was not declared in this scope
> /usr/local/xgboost/rabit/src/./../include/rabit/internal/../../dmlc/./logging.h: In member function ?.mlc::LogCheckError::operator bool()?.
> /usr/local/xgboost/rabit/src/./../include/rabit/internal/../../dmlc/./logging.h:69: error: ?.ullptr?.was not declared in this scope
> In file included from /usr/local/xgboost/rabit/src/./../include/rabit/internal/../../dmlc/io.h:14,
>                  from /usr/local/xgboost/rabit/src/./../include/rabit/internal/../serializable.h:12,
>                  from /usr/local/xgboost/rabit/src/./../include/rabit/internal/engine.h:10,
>                  from /usr/local/xgboost/rabit/src/./allreduce_base.h:19,
>                  from /usr/local/xgboost/rabit/src/allreduce_base.cc:14:
> /usr/local/xgboost/rabit/src/./../include/rabit/internal/../../dmlc/./logging.h: In destructor ?.mlc::LogMessageFatal::~LogMessageFatal()?.
> /usr/local/xgboost/rabit/src/./../include/rabit/internal/../../dmlc/./logging.h:289: error: ?.ullptr?.was not declared in this scope
> gmake[2]: *** [CMakeFiles/rabit.dir/rabit/src/allreduce_base.cc.o] Error 1
> building Java wrapper
> cd ..
> mkdir -p build
> cd build
> cmake .. -DUSE_OPENMP:BOOL=ON -DUSE_HDFS:BOOL=OFF -DUSE_AZURE:BOOL=OFF -DUSE_S3:BOOL=OFF -DPLUGIN_UPDATER_GPU:BOOL=OFF -DJVM_BINDINGS:BOOL=ON
> cmake --build . --config Release
> gmake[1]: *** [CMakeFiles/rabit.dir/all] Error 2
> gmake: *** [all] Error 2
> Traceback (most recent call last):
>   File "create_jni.py", line 89, in <module>
>     run("cmake --build . --config Release")
>   File "create_jni.py", line 51, in run
>     subprocess.check_call(command, shell=True, **kwargs)
>   File "/root/anaconda3/envs/tensorflow/lib/python3.6/subprocess.py", line 291, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command 'cmake --build . --config Release' returned non-zero exit status 2.
> [ERROR] Command execution failed.
> org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
> 	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
> 	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
> 	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:804)
> 	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:751)
> 	at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:313)
> 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
> 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
> 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
> 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
> 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
> 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
> 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
> 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
> 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
> 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
> 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:606)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Summary:
> [INFO] 
> [INFO] xgboost-jvm ........................................ SUCCESS [  7.834 s]
> [INFO] xgboost4j .......................................... FAILURE [  5.489 s]
> [INFO] xgboost4j-spark .................................... SKIPPED
> [INFO] xgboost4j-flink .................................... SKIPPED
> [INFO] xgboost4j-example .................................. SKIPPED
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 13.619 s
> [INFO] Finished at: 2017-12-14T03:13:07+08:00
> [INFO] Final Memory: 23M/55M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:exec (native) on project xgboost4j: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
> [ERROR] 
> [ERROR] After correcting the problems, you can resume the build with the command
> [ERROR]   mvn <goals> -rf :xgboost4j

Which step can I try to resolve the problem, mostly is to enable c++11 feature in cmake, it is very important.

**Comment by Craigacp** [comment]
Why are you compiling it with clang instead of gcc?
