### ISSUE TITLE
0.7 release of XGBoost on CRAN

### ISSUE THREAD

**Issue by spedygiorgio** [dmlc/xgboost#2948]
I wonder whether there will be a new "official" cran release of the R Package. This issue is similar to #2902

**Comment by hcho3** [comment]
One point in commit history will be designated as 0.7, so yes, we'd also need a release on CRAN. I am in charge of the Python package; for the R package, we'll need to recruit others who are more knowledgeable.

**Comment by khotilov** [comment]
That would depend on #2319

**Comment by thirdwing** [comment]
The segfault on 32-bit Windows is quite annoying. We need someone with more time to solve this.
