### ISSUE TITLE
in xgb.train() early stopping dependent on non-empty watch list and verbose>0

### ISSUE THREAD

**Issue by by321** [dmlc/xgboost#295]
It seems in xgb.train(), the early stopping feature requires a non-empty watch list and thus verbose>0, since verbose==0 clears the watch list.

These are two separate issues and should work independently of each other.

**Comment by hetong007** [comment]
@by321 Thank you for pointing this out. I just remove the command clearing the watchlist with the [latest commit](https://github.com/dmlc/xgboost/commit/458585b5fdb61787e9e33d4bcdc97b2ab87dde97).

**Comment by hetong007** [comment]
I am closing this issue for no further comment.
