### ISSUE TITLE
Anaconda does not connect to the internet

### ISSUE THREAD

**Issue by nadheera1231** [dmlc/xgboost#2952]
HI!

Whenever I try to update or install a new package via Anaconda, I get the following connection failed error with navigator and terminal.

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/r/win-64/repodata.json><br>Elapsed: -<br><br>An HTTP error occurred when trying to retrieve this URL.<br>HTTP errors are often intermittent, and a simple retry will get you on your way.<br>ProxyError(MaxRetryError("HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /r/win-64/repodata.json (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000028111B0DE80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)))",),)<br>

**Comment by khotilov** [comment]
This is not related to xgboost.
