### ISSUE TITLE
[GPU] How do I interpret "Labels are too large" error

### ISSUE THREAD

**Issue by SteveBronder** [dmlc/xgboost#2953]
This is not a bug, just not sure what this error means.

```r
  Error in xgb.iter.update(bst$handle, dtrain, iteration - 1, obj) : 
  [20:22:08] /home/blah/xgboost/src/tree/updater_gpu_hist.cu:286: GPU plugin exception:
 [20:22:08] /home/blah/xgboost/src/tree/updater_gpu_common.cuh:35: 
Check failed: abs_max < std::pow(2.0f, 16.0f) (79071.6 vs. 65536)
 Labels are too large for this algorithm. Rescale to less than 2^16.
```

Which labels? My y variable? The absolute max of any cell in my data is 360, so I'm not sure how to interpret this.

To make this a feature request, a more meaning full error message may be nice here.

Thank you for your time.

**Comment by SteveBronder** [comment]
Also you can see the function which it fails [here](https://github.com/dmlc/xgboost/blob/master/src/tree/updater_gpu_common.cuh#L68)

**Comment by khotilov** [comment]
It's not really labels, but most likely some gradients ("residuals") blow up. Which objective are you using? Does it happen right at 1st iteration or later?

**Comment by RAMitchell** [comment]
I reverted to using doubles for histogram summation in the latest version so this warning should no longer occur. The downside is gpu_hist will run slowly on gpus older than pascal.

**Comment by SteveBronder** [comment]
@khotilov it was happening with the `reg:gamma` objective on a binary target variable. So yes very large "residuals", was just goofing around with different objectives to see what would happen.

@RAMitchell that's cool and good, though this comes from me doing something pretty statistically bad. I'm not sure if switching to doubles is necessary where a more meaningful error message may suffice.

But that's up to you guys. You can leave this issue open if you would like to change the error message, otherwise you can close the issue at your leisure.
