### ISSUE TITLE
Use preprocessor to disable #define fopen64 std::fopen when built with mingw32-w64

### ISSUE THREAD

**Issue by KOLANICH** [dmlc/xgboost#2958]
In https://github.com/dmlc/xgboost/issues/1049 @yunzhou have found a solution to make it build using mingw32-w64 (the one which is sometimes used with anaconda). It was to comment out the line

```cpp
#define fopen64 std::fopen
```

It's a shame that this have not beed implemented yet. It took me a lot of time to find this solution.

**Comment by KOLANICH** [comment]
@tqchen, is this fix applied?

**Comment by hcho3** [comment]
#2977 added installation instruction for MinGW.

**Comment by KOLANICH** [comment]
This doesn't help, I still have to apply the patch mentioned in head post. I personally prefer it to be applied automatically with C++ preprocessor.

**Comment by hcho3** [comment]
@KOLANICH Let me open a new issue for MinGW support then. Currently, CI tests for Windows target do build XGBoost with MinGW, so I thought the issue was solved.

**Comment by hcho3** [comment]
@KOLANICH Can you post the exact version and variant of the compiler you are using in issue #3436?
