### ISSUE TITLE
Error when calling xgboost-spark 's XGBoost.trainWithDataFrame

### ISSUE THREAD

**Issue by momo1986** [dmlc/xgboost#2962]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System:

Compiler:

Package used (python/R/jvm/C++):jvm

`xgboost` version used:0.7

Hi guys, 
I use xgboost-spark in eclipse, however, I met problem:
Looks like I have error when calling "XGBoost.trainWithDataFrame", red slash is a sign.
![image](https://user-images.githubusercontent.com/34225874/34243808-7d4bd232-e65d-11e7-93ca-040c3fbe083d.png)
Does any one have idea how to fix the problem?
Thanks & Regards!

**Comment by superbobry** [comment]
What is the type of trainingSet?

**Comment by momo1986** [comment]
@superbobry ,it is Dataset<Row>

**Comment by momo1986** [comment]
@superbobry ,it is Dataset<Row>

**Comment by momo1986** [comment]
@superbobry ,it is Dataset<<Row>>

**Comment by momo1986** [comment]
@superbobry , it is Dataset"Row"

**Comment by momo1986** [comment]
@superbobry , I use XGBoost.trainWithRDD， problem still exists:
![image](https://user-images.githubusercontent.com/34225874/34251392-e8ab33c0-e67a-11e7-84cd-d81b6c9e262c.png)

**Comment by momo1986** [comment]
@superbobry ， how can I fix the problem?

**Comment by superbobry** [comment]
Can you post the compilation error?

**Comment by momo1986** [comment]
@superbobry ， It is just "Description	Resource	Path	Location	Type
**The method trainWithDataFrame(Dataset<?>, Map<String,Object>, int, int, ObjectiveTrait, EvalTrait, boolean, float, String, String) in the type XGBoost is not applicable for the arguments (Dataset<Row>, Map<String,Object>, int, int, null, null, boolean, float, String, String)	XgboostNew.java**	/riskcontrol/src/main/java/com/xianjinkd/riskcontrol/access/algorithm	line 154	Java Problem". Compilation error.

**Comment by momo1986** [comment]
@superbobry ， do you have any idea, how can I fix the problem?

**Comment by momo1986** [comment]
Can anyone give some comments？

**Comment by jajimenezf** [comment]
which Spark version are you using? it seems it's not working on the latest version, you should try on Spark 2.0.0 or 2.1.0
