### ISSUE TITLE
BUG: gpu_predictor in R

### ISSUE THREAD

**Issue by martinju** [dmlc/xgboost#2965]
Hi!

I seem to have stumbled upon a bug when predicting with the gpu version of xgboost (in R).

Runinng the following example in R:

```

require(xgboost)
# load in the agaricus dataset
data(agaricus.train, package='xgboost')
data(agaricus.test, package='xgboost')
dtrain <- xgb.DMatrix(agaricus.train$data, label = agaricus.train$label)
dtest <- xgb.DMatrix(agaricus.test$data, label = agaricus.test$label)
# note: for customized objective function, we leave objective as default
param <- list(max_depth=2, eta=0.1, nthread = 8, silent=1,tree_method="hist",predictor="gpu_predictor",
              objective = "binary:logistic")
watchlist <- list(eval = dtest)
num_round <- 5

bst <- xgb.train(param, dtrain, num_round,
                 print_every_n=100,verbose = 1)

set.seed(123)
head(predict(bst,dtest))

set.seed(123)
head(predict(bst,dtest))

set.seed(123)
head(predict(bst,dtest))

```
Gives different predictions every time I run the code. Fixing the seed does not matter either, so there is no randomness involved at the R end at least.
```
> set.seed(123)
> head(predict(bst,dtest))
[1] 0.4284496 0.5864953 0.4284496 0.4284496 0.3037330 0.5104644
> 
> set.seed(123)
> head(predict(bst,dtest))
[1] 0.3597708 0.6679642 0.3597708 0.3597708 0.1598736 0.5209196
> 
> set.seed(123)
> head(predict(bst,dtest))
[1] 0.29639199 0.74048442 0.29639199 0.29639199 0.07665042 0.53135645

```

Changing predictor to "cpu_predictor" (the default when using method="hist") gives consistent result as it should
```
require(xgboost)
# load in the agaricus dataset
data(agaricus.train, package='xgboost')
data(agaricus.test, package='xgboost')
dtrain <- xgb.DMatrix(agaricus.train$data, label = agaricus.train$label)
dtest <- xgb.DMatrix(agaricus.test$data, label = agaricus.test$label)
# note: for customized objective function, we leave objective as default
param <- list(max_depth=2, eta=0.1, nthread = 8, silent=1,tree_method="hist",predictor="cpu_predictor",
              objective = "binary:logistic")
watchlist <- list(eval = dtest)
num_round <- 5

bst <- xgb.train(param, dtrain, num_round,
                 print_every_n=100,verbose = 1)

set.seed(123)
head(predict(bst,dtest))
head(predict(bst,dtest))
head(predict(bst,dtest))
```

```
> set.seed(123)
> head(predict(bst,dtest))
[1] 0.4284496 0.5864953 0.4284496 0.4284496 0.3037330 0.5104644
> head(predict(bst,dtest))
[1] 0.4284496 0.5864953 0.4284496 0.4284496 0.3037330 0.5104644
> head(predict(bst,dtest))
[1] 0.4284496 0.5864953 0.4284496 0.4284496 0.3037330 0.5104644

```

I am on Ubuntu Linux, and the same occurs on two different GPUs (Pascal and GTX 1060), and on different data sets. It seems to me that the GPU prediction adds a constant to the prediction (on log-odds scale) every time it is called. Training the model with hist_gpu and then predicting with cpu_predictor works fine, but not with gpu_predictor, so the bug seems to be related entirely to gpu_predictor. Please let me know if others see the same behavior. I hope this rather serious bug could be fixed.

In the meanwhile, the workaround is to set predictor="cpu_predictor" when using the gpu-version of xgboost.

Btw, I am on xgboost version 0.647. Let me know if you need any other information from me.

**Comment by RAMitchell** [comment]
Can you verify this bug still occurs on the very latest version of XGBoost from github.

I fixed a similar bug recently.

**Comment by martinju** [comment]
Ah, I should have tested that first. Everything seems fine with the very last version from github. Thank you :) 
I am closing this now.
