### ISSUE TITLE
Booster.get_score() results in empty

### ISSUE THREAD

**Issue by rosefun** [dmlc/xgboost#2968]
## Environment info
Operating System: Windows8.1;  py35; xgboost unknown

Compiler:

Package used (python/R/jvm/C++):python

`xgboost` version used:

## Steps to reproduce

```
import xgboost as xgb
from xgboost import plot_importance
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split

dtest = xgb.DMatrix(X_test)
ans = model.predict(dtest)


plot_importance(model)
plt.show()
```
##The issue

```
  File "XGBoost_test.py", line 73, in <module>
    plot_importance(model)
  File "E:\Anaconda3\lib\site-packages\xgboost\plotting.py", line 73, in plot_im
portance
    raise ValueError('Booster.get_score() results in empty')
ValueError: Booster.get_score() results in empty

```

**Comment by cinqs** [comment]
I was able to re-produce your issue when the *model* is not trained at all.

so basically your model will have to be trained before the model could know the importance of the features.

you can either use `xgb.train()` or `bst.update()` apis to train. Or you need to follow the *get started* tutorials first
