### ISSUE TITLE
Distributed XGBoost Yarn Error

### ISSUE THREAD

**Issue by kuo000** [dmlc/xgboost#297]
Hi Tianqi, 

I moved this issue from the Google Group. Thanks for helping all along. I redirected the standard output (from running run_yarn.sh) and posted it here:

mkdir: `/user/charles.kuo/data': File exists
put: `/user/charles.kuo/data/agaricus.txt.train': File exists
put: `/user/charles.kuo/data/agaricus.txt.test': File exists
2015-05-08 14:39:45,286 INFO start listen on 192.168.1.100:9091
15/05/08 14:39:46 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
15/05/08 14:39:46 INFO client.RMProxy: Connecting to ResourceManager at tpe-nn-3-1/192.168.1.100:8032
15/05/08 14:39:47 INFO dmlc.Client: jobname=DMLC[nworker=1]:xgboost.dmlc,username=charles.kuo
15/05/08 14:39:47 INFO dmlc.Client: Submitting application application_1430990900546_0124
15/05/08 14:39:47 INFO impl.YarnClientImpl: Submitted application application_1430990900546_0124
2015-05-08 14:39:58,112 INFO @tracker All of 1 nodes getting started
Application application_1430990900546_0124 finished with state FINISHED at 1431067205645

Available queues:
root.alec_dot_tu
root.default
root.hugo_dot_lee
root.yarn
root.charles_dot_kuo

"tpe-nn-3-1" is our server's name. Even though there was this line saying "Application application_14309... finished with state FINISHED at 14310...", the job appeared FAILED on Hue (the web interface), and the script run_yarn.sh never finished (because it's still waiting for the hadoop run, I guess.).

BTW, my hadoop server manager hasn't replied, but it looks our hadoop cluster is running fine...

**Comment by tqchen** [comment]
It would be great if you can run 
```
yarn logs -applicationId [appId you have] 
```
This will gives the log from the worker side.

**Comment by kuo000** [comment]
Hi Tianqi,

Attached you can find the log from my failed xgboost run.

I need to check one thing before we go further: I turned off USE_HDFS for
compilation (by modifying the config file). Is using HDFS support during
compiling necessary for the program to function correctly?


Chia-Li (Charles) Kuo

**Comment by tqchen** [comment]
Hi Kuo, HDFS is necessary for the program to function correctly as the error message indicates. So please compile with USE_HDFS=1

**Comment by kuo000** [comment]
Hi Tianqi,

I tried using HDFS support during compiling, but got the following error message: 
> /usr/bin/ld: cannot find -lhdfs

upon running the first g++ compiling command in xgboost:
`g++ -Wall -O3 -msse2  -Wno-unknown-pragmas -fPIC -fopenmp -o xgboost updater.o gbm.o io.o main.o subtree/rabit/lib/librabit.a /home/charles.kuo/wormhole/dmlc-core/libdmlc.a -pthread -lm   -fopenmp -L/usr/lib/native -L/usr/lib/jvm/java-7-oracle/jre/lib/amd64/server -lhdfs -ljvm -Wl,-rpath=/usr/lib/jvm/java-7-oracle/jre/lib/amd64/server`


Those g++ commands in the `dmlc-core` directory seem to have compiled the object files successfully. BTW, my `hdfs.h` file resides in `/opt/cloudera/parcels/CDH-5.4.0-1.cdh5.4.0.p0.27/include`.

Should I specify any path for g++?

**Comment by tqchen** [comment]
Please  make sure you make clean the dmlc-core before you make it. 

Seems there was some problem with missing libhdfs.a and libhdfs.so in the CDH distribution. See https://github.com/dmlc/wormhole/pull/1 

@loadingvx seems to provide a solution for this. You can to put libhdfs.a under /usr/lib/native or add link path to the libhdfs.a

**Comment by tqchen** [comment]
In the solution, it is likely that you want to add libhdfs.a to the final command(instead of linking libhdfs.so) and remove -lhdfs so you do not need to deploy libhdfs into your server.

**Comment by kuo000** [comment]
I just tried to `locate libhdfs.a` and find the file on our system at `/opt/cloudera/parcels/CDH-5.3.3-1.cdh5.3.3.p0.5/lib/hadoop/lib/native/libhdfs.a`.

I reset my HADOOP_HOME to `/opt/cloudera/parcels/CDH-5.3.3-1.cdh5.3.3.p0.5/lib/hadoop` (it used to be a alias). Now from the link command: 
`g++ -Wall -O3 -msse2  -Wno-unknown-pragmas -fPIC -fopenmp -fPIC -shared -o wrapper/libxgboostwrapper.so wrapper/xgboost_wrapper.cpp updater.o gbm.o io.o subtree/rabit/lib/librabit.a /home/charles.kuo/wormhole/dmlc-core/libdmlc.a -pthread -lm   -fopenmp -L/opt/cloudera/parcels/CDH-5.3.3-1.cdh5.3.3.p0.5/lib/hadoop/lib/native -L/usr/lib/jvm/java-7-oracle/jre/lib/amd64/server -lhdfs -ljvm -Wl,-rpath=/usr/lib/jvm/java-7-oracle/jre/lib/amd64/server` the error message I got is:

> /usr/bin/ld: /opt/cloudera/parcels/CDH-5.3.3-1.cdh5.3.3.p0.5/lib/hadoop/lib/native/libhdfs.a(hdfs.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/opt/cloudera/parcels/CDH-5.3.3-1.cdh5.3.3.p0.5/lib/hadoop/lib/native/libhdfs.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status


Now that I have `libhdfs.a`, would things work if I simply removed `-lhdfs` from the above `g++` command. If so, which file should I modify? I searched over a couple Makefiles but didn't find this command (I was searching for the term `-lhdfs` in different Makefiles...)

**Comment by loadingvx** [comment]
https://github.com/dmlc/dmlc-core/pull/2
https://github.com/dmlc/wormhole/pull/1
https://github.com/dmlc/xgboost/pull/248

Thess were my tricks,  Your can have a try.
 
!! but this only allows you to successfully compile xgboost.dmlc !!
but libxgboostwrapper.so compile ok, failed while import.

The best way is recompile libhdfs.so.

**Comment by loadingvx** [comment]
Please ignore my poor English .....

**Comment by kuo000** [comment]
Thanks, loadingvx. I'll dig into your posts and give my problem a try (robably tomorrow though).

I'll get back to report my progress.

**Comment by tqchen** [comment]
@loadingvx Can you still make a patch on this? I think we can add a FLAG DMLC_STATIC_LIB that will be included in xgboost Makefile. 

We can change wormhole makefile to only build xgboost

Since only xgboost.dmlc will be used in distributed version for now and it is good to have people being able to do it easily in CDH distribution.

**Comment by loadingvx** [comment]
ok. I'll try.

**Comment by tqchen** [comment]
Thanks!

**Comment by kuo000** [comment]
Hi liangchengming,

I spent some time digging your previous posts, but I'm still not sure what I should do...

My current understanding is that I need `libhdfs.a` in my `$(HADOOP_HDFS_HOME)/lib/native` (which I do), and I'll need to make some changes to https://github.com/dmlc/dmlc-core/blob/master/make/dmlc.mk#L25 or some other makefiles to avoid linking the `libhfds.so`...

Sorry. My knowledge of `gcc` and the entire Linux system is rather limited. Any help from here? Thanks.

**Comment by loadingvx** [comment]
@kuo000 , make sure you compile libdmlc.a with USE_HDFS and try this:

cd repo/xgboost
g++ -Wall -O3 -msse2  -Wno-unknown-pragmas -fPIC -fopenmp -o xgboost updater.o gbm.o io.o main.o subtree/rabit/lib/librabit.a -pthread -lm  -lrt -fopenmp -L/usr/java/jdk1.7.0_71/jre/lib/amd64/server -ljvm -Wl,-rpath=[yourJVM]  ../../dmlc-core/libdmlc.a  [your-hadoop-home]/lib/native/libhdfs.a

change 'yourJVM' and 'your-hadoop-home'  yourself.

**Comment by loadingvx** [comment]
and also  [-L/usr/java/jdk1.7.0_71/jre/lib/amd64/server] to your  JavaPath.

**Comment by kuo000** [comment]
@loadingvx Thanks for helping.

This looks a bit weird. My compile command for xgboost is as the following and actually worked fine:
`g++ -Wall -O3 -msse2  -Wno-unknown-pragmas -fPIC -fopenmp -o xgboost updater.o gbm.o io.o main.o subtree/rabit/lib/librabit.a /home/charles.kuo/wormhole/dmlc-core/libdmlc.a -pthread -lm   -fopenmp -L/opt/cloudera/parcels/CDH-5.3.3-1.cdh5.3.3.p0.5/lib/hadoop/lib/native -L/usr/lib/jvm/java-7-oracle/jre/lib/amd64/server -lhdfs -ljvm -Wl,-rpath=/usr/lib/jvm/java-7-oracle/jre/lib/amd64/server`.

It was the command for `libxgboostwrapper.so` that threw an error. My command looked like:
`g++ -Wall -O3 -msse2  -Wno-unknown-pragmas -fPIC -fopenmp -fPIC -shared -o wrapper/libxgboostwrapper.so wrapper/xgboost_wrapper.cpp updater.o gbm.o io.o subtree/rabit/lib/librabit.a /home/charles.kuo/wormhole/dmlc-core/libdmlc.a -pthread -lm   -fopenmp -L/opt/cloudera/parcels/CDH-5.3.3-1.cdh5.3.3.p0.5/lib/hadoop/lib/native -L/usr/lib/jvm/java-7-oracle/jre/lib/amd64/server -lhdfs -ljvm -Wl,-rpath=/usr/lib/jvm/java-7-oracle/jre/lib/amd64/server`.

I tried removing `-lhdfs` and added `/opt/cloudera/parcels/CDH-5.3.3-1.cdh5.3.3.p0.5/lib/hadoop/lib/native/libhdfs.a`, but still had no luck. The error message was:
> /usr/bin/ld: /opt/cloudera/parcels/CDH-5.3.3-1.cdh5.3.3.p0.5/lib/hadoop/lib/native/libhdfs.a(hdfs.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/opt/cloudera/parcels/CDH-5.3.3-1.cdh5.3.3.p0.5/lib/hadoop/lib/native/libhdfs.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make[1]: *** [wrapper/libxgboostwrapper.so] Error 1

**Comment by loadingvx** [comment]
No prefect plan for this
try this:

g++ -Wall -O3 -msse2 -Wno-unknown-pragmas -fPIC -fopenmp -fPIC -shared -o wrapper/libxgboostwrapper.so wrapper/xgboost_wrapper.cpp updater.o gbm.o io.o subtree/rabit/lib/librabit.a /home/charles.kuo/wormhole/dmlc-core/libdmlc.a  /opt/cloudera/parcels/CDH-5.3.3-1.cdh5.3.3.p0.5/lib/hadoop/lib/native/libhdfs.a -pthread -lm -fopenmp -L/opt/cloudera/parcels/CDH-5.3.3-1.cdh5.3.3.p0.5/lib/hadoop/lib/native -L/usr/lib/jvm/java-7-oracle/jre/lib/amd64/server -ljvm -Wl,-rpath=/usr/lib/jvm/java-7-oracle/jre/lib/amd64/server.

libxgboostwrapper.so can be compiled but still useless, invalid for python to import.
I tried this many times, the only way you can compile a useful "so" is to recompile libhdfs.so with -fPIC.
xgboost and libxgboostwrapper.so  are equal, try use xgboost instead.

**Comment by loadingvx** [comment]
though I compiled xgboost.dmlc with hdfs, I never got it run successfully on company's yarn-cluster. 
we give up on xgboost, that's a pity.  let me know if you made any new progresses. 
The hadoop-cdh you are  using just like mine, does not support a second develop on it unless you recompile it from the bottom with -fPIC added into hadoop-hdfs/Makefile.

**Comment by kuo000** [comment]
@loadingvx Thanks for trying to help all along.

I tried the command before (removing `-lhdfs` and adding `/opt/cloudera/parcels/CDH-5.3.3-1.cdh5.3.3.p0.5/lib/hadoop/lib/native/libhdfs.a`), but it did not work...

I think we are in really similar situations. I could generate `xgboost.dmlc` and submitted a xgboost job to my team's hadoop cluster, but it never ran successfully...

I'll need to give up on keeping trying XGBoost for now as well. It's a shame. (XGBoost has become one of my first go-to tools (plus some in scikit-learn) when I want to try some supervised ML tasks) But given the size of the dataset I currently work with at my company, I should be able to do pretty much everything on a single workstation. So I don't really need hadoop now.

**Comment by tqchen** [comment]
@kuo000  @loadingvx May I get the log of the failure? I would like to know if it is due to the bad libhdfs library, or the problem of package itself.

 It would be great if you could help on this. Specifically, if you can type
```
make test/filesys_test
```
in dmlc-core repo, and play a bit with
```
yarn/run_hdfs_prog.py test/filesys_test 
```.
To see if it can successfully access hdfs.

I really appreciate it.

Thanks

**Comment by tqchen** [comment]
I have noticed that there seems to be a package called ```hadoop-libhdfs``` (yum installation), I do not know if missing this package will cause the problem.

**Comment by kuo000** [comment]
@tqchen Sure. I'm more than willing to help with my failure experience.

But I'll have to do this a couple days later, as I'm quite occupied this whole week. Just keep this issue open, and I'll try your suggested commands and report back here.

Thanks.

**Comment by tqchen** [comment]
closing for now, for CDH, see also https://github.com/dmlc/dmlc-core/issues/10, seems have a proposed solution
