### ISSUE TITLE
Exception ignored in: <bound method DMatrix.__del__ of <xgboost.core.DMatrix object

### ISSUE THREAD

**Issue by KOLANICH** [dmlc/xgboost#2972]
## Environment info

Package used: python

`xgboost` version used: 7c6673cb9ef7f68f92075123dc78e9661ce3d4e5

The python version: 3.4.2

## Steps to reproduce

1. get xgboost from github
2. build the lib (I have added some parameters into each makefile: -O3, -mtune and enabled autovectorization)
3. ```strip -s ./lib/libxgboost.so```
4. build a wheel
5. install the wheel (I have experienced a problem: the library has not been copied, instead a file lib appeared in the dir, I had to delete that file manually, create a folder and copy there the .so file)
6. add into the end of ```./tests/python/test_basic.py```
```python
unittest.main()
```
7. python ./tests/python/test_basic.py

The tests have been passed, but there are strange messages in the log:

```python
Exception ignored in: <bound method DMatrix.__del__ of <xgboost.core.DMatrix object at 0xremoved>>
Traceback (most recent call last):
  File "<removed>/xgboost/core.py", line 368, in __del__
    if self.handle is not None:
AttributeError: 'DMatrix' object has no attribute 'handle'
```

**Comment by aldanor** [comment]
I've hit this as well, in a Jupyter notebook, reproduced by having a cell like this

```python
xgb.DMatrix(np.array([[]]))  # created and instantly destroyed
```

**Comment by hannahlindsley** [comment]
I'm hitting the same issue.

**Comment by khotilov** [comment]
@KOLANICH Those are from the intentional checks within `test_dmatrix_numpy_init` to make sure that some unintended inputs to DMatrix raise a ValueError:
```
$ nosetests tests/python/test_basic.py:TestBasic.test_dmatrix_numpy_init
Exception ignored in: <bound method DMatrix.__del__ of <xgboost.core.DMatrix object at 0x0000000006EE3630>>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\xgboost-0.7-py3.5.egg\xgboost\core.py", line 368, in __del__
    if self.handle is not None:
AttributeError: 'DMatrix' object has no attribute 'handle'
Exception ignored in: <bound method DMatrix.__del__ of <xgboost.core.DMatrix object at 0x0000000006EE3630>>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\xgboost-0.7-py3.5.egg\xgboost\core.py", line 368, in __del__
    if self.handle is not None:
AttributeError: 'DMatrix' object has no attribute 'handle'
Exception ignored in: <bound method DMatrix.__del__ of <xgboost.core.DMatrix object at 0x0000000006EE3630>>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\xgboost-0.7-py3.5.egg\xgboost\core.py", line 368, in __del__
    if self.handle is not None:
AttributeError: 'DMatrix' object has no attribute 'handle'
Exception ignored in: <bound method DMatrix.__del__ of <xgboost.core.DMatrix object at 0x0000000006EE3630>>
Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\xgboost-0.7-py3.5.egg\xgboost\core.py", line 368, in __del__
    if self.handle is not None:
AttributeError: 'DMatrix' object has no attribute 'handle'
.
----------------------------------------------------------------------
Ran 1 test in 0.064s

OK
```
@aldanor  I cannot reproduce that (but I do find it odd that it allows creating a zero-columns DMatrix). Any more details?
![image](https://user-images.githubusercontent.com/1613551/35259218-22b72480-ffca-11e7-9c4d-f0dbcb9bc740.png)

@hannahlindsley we cannot help without any details on what specifically you were running.
