### ISSUE TITLE
[jvm-packages] Can not find the libgomp.so.1 file used in xgboost4j-spark

### ISSUE THREAD

**Issue by universewill** [dmlc/xgboost#2974]
My gcc version is gcc 版本 4.4.7 20120313 (Red Hat 4.4.7-11) (GCC).

I run xgboost-spark on spark cluster, and it always run into libgomp.so.1 error. The same as #1033.
I find that the failed executors don't have /usr/lib64/libgomp.so.1 and /usr/lib64/libgomp.so.1.0.0 file. However, i have no authority to install or modify the gcc on spark cluster nodes and workers.

Is there any way to solve this problem?
Can the libgomp file or lib be packaged into the xgboost jar instead, so that the spark program doesn't require executors have their own libgomp?

**Comment by hcho3** [comment]
@laaron2008 You should install libgomp1 package.
