### ISSUE TITLE
Interoperability with sklearn.tree.export_graphviz

### ISSUE THREAD

**Issue by KOLANICH** [dmlc/xgboost#2981]
For now we cannot draw a tree this way.

**Comment by KOLANICH** [comment]
???

**Comment by hcho3** [comment]
From now on, the issue tracker is reserved for actionable items such as feature proposals discussion, roadmaps, and bug tracking. For Q&A and discussion, please start a new thread at https://discuss.xgboost.ai/.

**Comment by hcho3** [comment]
I've added this as an item in the central feature request tracker.
