### ISSUE TITLE
XGBoost4J early stopping behavior seems strange

### ISSUE THREAD

**Issue by gkoundry** [dmlc/xgboost#2982]
When I tried to use early stopping in XGBoost4J I came across two issues:
- the current logic seems to be "stop when the first eval score increase is seen regardless of what numEarlyStoppingRounds is set to".  It would stop for some datasets after three trees no matter what parameters I used.
- it doesn't seem to have different behavior for "higher is better" metrics like AUC

**Comment by superbobry** [comment]
Hi @gkoundry, yes, the implementation of early stopping is pretty basic, it only works for losses for now. As for the first point, it sounds like a bug. I'll try to reproduce it tomorrow.
