### ISSUE TITLE
[jvm-packages] Support for GPU in Spark package

### ISSUE THREAD

**Issue by troszok** [dmlc/xgboost#2983]
Is there a way to enable GPU support in Spark package? 

When I tried to force GPU tree method I am getting: 
```
Exception in thread "main" java.lang.IllegalArgumentException: XGBoostEstimator_d9a9bf44f8ae parameter tree_method given invalid value gpu_hist
```

I also found in the documentation:
```
This plugin currently works with the CLI, python and R - see installation guide for details.
```
But I see some issues related to xgboost4j-jvm (for example: https://github.com/dmlc/xgboost/issues/2324) so people are using it.
 
Is it planned anytime soon or if there is a way to enable it?

**Comment by RAMitchell** [comment]
I have added the call for contribution label. Would appreciate it if someone else could take this on!

**Comment by mhmoudr** [comment]
This ticket has been closed, but I cannot see any PR linked to it, isn't there a planned support for GPUs in JVM packages?

**Comment by hcho3** [comment]
@mhmoudr See #3499. Basically, the GPU algorithms need to support distributed (multi-node) training. Currently, the GPU algorithms only work on a single node.
