### ISSUE TITLE
the result of custom_logloss is not same with default objective 'binary:logistic' 

### ISSUE THREAD

**Issue by sym60123** [dmlc/xgboost#2995]
Here‘s my custom_logloss code
```
def custom_loss(preds, dtrain):
        labels = dtrain.get_label()
        grad = preds - labels
        hess = preds * (1.0 - preds)
        return grad, hess
```
Here‘s xgb_logloss code：
```
struct LogisticRegression {
  static float PredTransform(float x) { return common::Sigmoid(x); }
  static bool CheckLabel(float x) { return x >= 0.0f && x <= 1.0f; }
  static float FirstOrderGradient(float predt, float label) { return predt - label; }
  static float SecondOrderGradient(float predt, float label) {
    const float eps = 1e-16f;
    return std::max(predt * (1.0f - predt), eps);
  }
```
Although I have **adjusted** the super parameters, my code is still poor  in the same data（trainset/testset） ，and **The strange thing** is parameter ’num_boost_round‘  ，with the increase of the Rounds number  to a limit，there is no change in the result ！
Here it is：
```
Rounds1000:
train_set:
accuracy_rate: 0.976357316266
recall_rate: 0.994120307553
test_set:
accuracy_rate: 0.854285635466
recall_rate: 0.412375894713
Rounds1200:
train_set:
accuracy_rate: 0.976357316266
recall_rate: 0.994120307553
test_set:
accuracy_rate: 0.854285635466
recall_rate: 0.412375894713
Rounds1300:
train_set:
accuracy_rate: 0.976357316266
recall_rate: 0.994120307553
test_set:
accuracy_rate: 0.854285635466
recall_rate: 0.412375894713
Rounds1500:
train_set:
accuracy_rate: 0.976357316266
recall_rate: 0.994120307553
test_set:
accuracy_rate: 0.854285635466
recall_rate: 0.412375894713
```
I want to know why？my code is wrong ？What's the reason？
Thanks for your help！

**Comment by sym60123** [comment]
@tqchen  Can you help me? Thanks a lot.

**Comment by pommedeterresautee** [comment]
I think you have forgotten to apply the sigmoid first.

**Comment by sym60123** [comment]
Thanks for  your help! 
My label is probability.More specifically,my custom_loss is 'objective=binary:logistic'.
My code comes from here:
(https://github.com/dmlc/xgboost/issues/15)

**Comment by pommedeterresautee** [comment]
The message you pointed is quite old and the code is not updated.
Please look the current code of demo.py there : https://github.com/dmlc/xgboost/blob/master/demo/guide-python/custom_objective.py
As said in the message from @tqchen, you should read the NOTE below the source code. It is about margin vs log prob issue.

Kind regards,
Michaël
