### ISSUE TITLE
Make a PyPI release of v0.7 please?

### ISSUE THREAD

**Issue by aldanor** [dmlc/xgboost#2996]
Dear xgboost maintainers (@hcho3, @tqchen?), would you please upload the v0.7 sdist release to PyPI? (so that we could then update conda-forge recipe as well).

Thanks!

**Comment by hcho3** [comment]
Here it is: https://pypi.python.org/pypi/xgboost/0.7

**Comment by hcho3** [comment]
Binary wheels will be made available as well.

**Comment by aldanor** [comment]
@hcho3 Thanks. I was just trying to build a conda package (with `0.7.post1`), however `Makefile` now seems to be missing from `python-package/xgboost/`, and `build-python.sh` tries to call `make` commands and fails. Am I missing something?

**Comment by aldanor** [comment]
Also, there's `xgboost/lib/libxgboost.so` in the sdist. Should it be there? (in sdist, not wheel)

**Comment by aldanor** [comment]
So because of the above problems, it goes like this (this is on OS X):

```
make: *** No rule to make target `clean'.  Stop.  # <--- because there's no Makefile
make: Nothing to be done for `lib/libxgboost.so'.  # <--- note libxgboost.so from the sdist
Successfully build multi-thread xgboost  # not really...
Traceback (most recent call last):
  File "setup_pip.py", line 37, in <module>
    LIB_PATH = libpath['find_lib_path']()
  File "xgboost/libpath.py", line 49, in find_lib_path
    'List of candidates:\n' + ('\n'.join(dll_path)))
XGBoostLibraryNotFound: Cannot find XGBoost Library in the candidate path, did you install compilers and run build.sh in root path?
List of candidates:
/work/xgboost/libxgboost.dylib  # <--- note that it's .dylib, not .so
/work/xgboost/../../lib/libxgboost.dylib
/work/xgboost/./lib/libxgboost.dylib
```

**Comment by aldanor** [comment]
Just a note:

> I can install xgboost 0.7 on my Ubuntu laptop using pip3 install xgboost

I think that's because your pip wasn't actually trying to build anything (because you packaged a Linux build of `libxgboost.so` in the sdist).

**Comment by hcho3** [comment]
Let me take a look at it. I will have to release `0.7.post2` to address the issue.

**Comment by aldanor** [comment]
By the way, one word of advice, for `build-python.sh` (and possibly other shell scripts as well), add a

```sh
set -e
```

at the start of the script. (you can read more about it [here](http://www.davidpashley.com/articles/writing-robust-shell-scripts/))

This way, if any command fails, the whole script will fail (unlike what happens above, `make` fails but the build script goes on and reports that the library has been successfully built).

**Comment by hcho3** [comment]
The `0.7.post2` release is available. It turns out that the packaging logic makes certain assumptions that are no longer true. I had to manually edit a few files to make it work.

**Comment by aldanor** [comment]
@hcho3 That's great, thanks. I'm now able to build xgboost library from the latest sdist.

However now there's a different problem (on OS X):

Here's the final step of building the library, from the log:

```sh
clang++ -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   
    -I/work/xgboost/dmlc-core/include -Irabit/include -I/include 
    -O3 -funroll-loops -msse2 -fPIC -fopenmp -shared 
    -o lib/libxgboost.so build/learner.o build/logging.o
    ...
```

Note the `-o lib/libxgboost.so`.

It then fails because it can't find a `.dylib` library:

```python
Traceback (most recent call last):
  File "setup.py", line 37, in <module>
    LIB_PATH = libpath['find_lib_path']()
  File "xgboost/libpath.py", line 49, in find_lib_path
    'List of candidates:\n' + ('\n'.join(dll_path)))
XGBoostLibraryNotFound: Cannot find XGBoost Library in the candidate path, did you install compilers and run build.sh in root path?
List of candidates:
/work/xgboost/libxgboost.dylib
/work/xgboost/../../lib/libxgboost.dylib
/work/xgboost/./lib/libxgboost.dylib
/env/xgboost/libxgboost.dylib
Traceback (most recent call last):
...
```

**Comment by hcho3** [comment]
I don't have a Mac machine on me. Can you see if this package works?
[xgboost-0.7.post3.tar.gz](https://github.com/dmlc/xgboost/files/1596325/xgboost-0.7.post3.tar.gz)
The `build-python.sh` script should now detect Mac and use `libxgboost.dylib` instead of `libxgboost.so`.

**Comment by aldanor** [comment]
@hcho3 Almost there, thanks!

I managed to actually build it (almost entirely), there's just a few minor hiccups when trying to build a conda package on Python 3 (due to it trying to byte-compiling Python code), basically Python2-style print statements in three rabit files:

```python
byte-compiling env/lib/python3.6/site-packages/xgboost/rabit/guide/basic.py to basic.cpython-36.pyc
  File "env/lib/python3.6/site-packages/xgboost/rabit/guide/basic.py", line 20
    print '@node[%d] before-allreduce: a=%s' % (rank, str(a))
                                           ^
SyntaxError: invalid syntax

byte-compiling env/lib/python3.6/site-packages/xgboost/rabit/guide/broadcast.py to broadcast.cpython-36.pyc
  File "env/lib/python3.6/site-packages/xgboost/rabit/guide/broadcast.py", line 18
    print '@node[%d] before-broadcast: s=\"%s\"' % (rank, str(s))
                                               ^
SyntaxError: invalid syntax

byte-compiling env/lib/python3.6/site-packages/xgboost/rabit/test/local_recover.py to local_recover.cpython-36.pyc
  File "env/lib/python3.6/site-packages/xgboost/rabit/test/local_recover.py", line 16
    print '[%d] restart from version %d' % (rank, version)
                                       ^
SyntaxError: invalid syntax
```

(Other than that, it did build `xgboost.dylib` and it was picked up properly)

**Comment by aldanor** [comment]
If the above are fixed, I will submit PR with changes to xgboost feedstock on conda-forge (once you push the latest tarball to PyPI) if that's ok.

**Comment by hcho3** [comment]
I've fixed the three Python files you mentioned: 
[xgboost-0.7.post3.tar.gz](https://github.com/dmlc/xgboost/files/1596618/xgboost-0.7.post3.tar.gz)

**Comment by aldanor** [comment]
@hcho3 The build finished, fine on both Linux and OS X: https://github.com/conda-forge/xgboost-feedstock/pull/6.

I will wait for this version of tarball to be uploaded to PyPI, then we can release a conda package. By the way, would it make sense to just tag a 0.7.1 release so as to reduce possible confusion with all the .post versions?

**Comment by hcho3** [comment]
@aldanor The tarball is now on PyPI. As for 0.7.1 release, I'd prefer to wait until I submit a PR to update the packaging logic.
