### ISSUE TITLE
does command line version support early stop?

### ISSUE THREAD

**Issue by yitang** [dmlc/xgboost#3001]
Hi, does command line version support early stop? I tried to add early stop parameters but it doesn't work.

the reason I'm working on CLI version is because I found xgb has RAM leaks in converting numpy array to DMatrix. Maybe it's my setup's probelm.

Thanks,

**Comment by pommedeterresautee** [comment]
As indicated here, parameters can be provided through a conf file.
https://github.com/dmlc/xgboost/blob/master/demo/binary_classification/README.md

**Comment by yitang** [comment]
@pommedeterresautee I can't find early stop parameters, so xgboost cli doesn't support early-stop?

**Comment by aohaili** [comment]
@yitang

**Comment by aohaili** [comment]
see https://github.com/dmlc/xgboost/issues/448

![image](https://user-images.githubusercontent.com/7114005/36625975-d9c24d4a-1964-11e8-9cf6-dfabaaee02cf.png)
