### ISSUE TITLE
[jvm-packages] Solutions for SIGSEGV when JBooster is shared by multiple SBoosters

### ISSUE THREAD

**Issue by Yunni** [dmlc/xgboost#3012]
In the current implementation, there is `ml.dmlc.xgboost4j.java.Booster`(JBooster) and `ml.dmlc.xgboost4j.scala.Booster`(SBooster). JBooster is a package-private var inside SBooster
https://github.com/dmlc/xgboost/blob/9747ea2acb6285273a3272ef0da261391a1fc454/jvm-packages/xgboost4j/src/main/scala/ml/dmlc/xgboost4j/scala/Booster.scala#L28
Because the finalize() method is overriden in SBooster to reclaim native resources https://github.com/dmlc/xgboost/blob/9747ea2acb6285273a3272ef0da261391a1fc454/jvm-packages/xgboost4j/src/main/scala/ml/dmlc/xgboost4j/scala/Booster.scala#L207

there could be a potential issue which cause transient SIGSEGV when developers extend jvm-packages.
```
val a = new SBooster(jbooster)
val b = new SBooster(jbooster)
a.toByteArray() // Crash sometimes because b is finalized by garbage collector
```
Per discussion with @CodingCat in #3005, here are potential solutions:

(1) We kept a warning message in the scaladoc and relying on developers' responsibility to keep 1-1 mapping between JBooster and SBooster.
- Pros: Since the SBooster constructor is package private, developers are unlikely to extend the class in such a way and hit this issue.
- Cons: Developer could be unaware of this rule, and it's hard to catch the problem when it happens.

(2) Remove the overriden SBooster.finalize() and relying on JBooster.finalize() to reclaim the native resources.
- Pros: The native resource initialization and reclaiming is centralized in JBooster, so it will be safe for multiple SBoosters to share the same JBooster. (The piece of code above won't crash)
- Cons: Even if SBooster is reclaimed, the native resources are still alive until JBooster is reclaimed.

(3) Use a boolean flag or data structure to enforce 1-1 mapping between JBooster and SBooster.
- Pros: Developer will get explicit error message if they violate the 1-1 mapping.
- Cons: Significantly increase the complexity of the code.

**Comment by CodingCat** [comment]
@superbobry
