### ISSUE TITLE
More meaningful "feature names mismatch" message

### ISSUE THREAD

**Issue by KOLANICH** [dmlc/xgboost#3016]
For now it just shows 2 collections of james of features. I guessit should show their difference.

**Comment by KOLANICH** [comment]
???

**Comment by hcho3** [comment]
I'm not convince that showing the difference would be any more "meaningful" than showing the full content of the two lists.

**Comment by KOLANICH** [comment]
Because now I have to diff them to get a hint on what's wrong. And if there are lots of columns, and only few columns mismatch just showing 2 arrays means that a problematic column is just drowned in a sea of correct columns. Showing a diff would spot it instantly.

**Comment by hcho3** [comment]
I think currently the error message already shows the diff: https://github.com/dmlc/xgboost/blob/master/python-package/xgboost/core.py#L1401-1407

**Comment by KOLANICH** [comment]
That's strange. I remember thet in I had to do it manually. Thank you anyway.
