### ISSUE TITLE
[jvm-packages] can not compile successfully

### ISSUE THREAD

**Issue by antant-shenzhen-2013** [dmlc/xgboost#3019]
## Environment info
Operating System:  centOS 6

Compiler: 
gcc (GCC) 4.9.2 20150212 (Red Hat 4.9.2-6)

Package used (python/R/jvm/C++): jvm

`xgboost` version used: 0.7

## Steps to reproduce

1. mvn clean package

 

> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/luwl/xgboost/build
> [  1%] Building CXX object CMakeFiles/objxgboost.dir/src/c_api/c_api.cc.o
> In file included from /home/luwl/xgboost/include/xgboost/data.h:10,
>                  from /home/luwl/xgboost/src/c_api/c_api.cc:3:
> /home/luwl/xgboost/dmlc-core/include/dmlc/base.h:105: note: #pragma message: Will need g++-4.6 or higher to compile allthe features in dmlc-core, compile without c++0x, some features may be disabled
> In file included from /home/luwl/xgboost/dmlc-core/include/dmlc/./io.h:14,
>                  from /home/luwl/xgboost/dmlc-core/include/dmlc/data.h:14,
>                  from /home/luwl/xgboost/include/xgboost/data.h:11,
>                  from /home/luwl/xgboost/src/c_api/c_api.cc:3:
> /home/luwl/xgboost/dmlc-core/include/dmlc/././logging.h: In constructor ‘dmlc::LogCheckError::LogCheckError()’:
> /home/luwl/xgboost/dmlc-core/include/dmlc/././logging.h:66: error: ‘nullptr’ was not declared in this scope
> /home/luwl/xgboost/dmlc-core/include/dmlc/././logging.h: In destructor ‘dmlc::LogCheckError::~LogCheckError()’:
> /home/luwl/xgboost/dmlc-core/include/dmlc/././logging.h:68: error: ‘nullptr’ was not declared in this scope
> /home/luwl/xgboost/dmlc-core/include/dmlc/././logging.h: In member function ‘dmlc::LogCheckError::operator bool()’:
> /home/luwl/xgboost/dmlc-core/include/dmlc/././logging.h:69: error: ‘nullptr’ was not declared in this scope
> In file included from /home/luwl/xgboost/dmlc-core/include/dmlc/./io.h:14,
>                  from /home/luwl/xgboost/dmlc-core/include/dmlc/data.h:14,
>                  from /home/luwl/xgboost/include/xgboost/data.h:11,
>                  from /home/luwl/xgboost/src/c_api/c_api.cc:3:
> /home/luwl/xgboost/dmlc-core/include/dmlc/././logging.h: In destructor ‘dmlc::LogMessageFatal::~LogMessageFatal()’:
> /home/luwl/xgboost/dmlc-core/include/dmlc/././logging.h:289: error: ‘nullptr’ was not declared in this scope
> In file included from /home/luwl/xgboost/dmlc-core/include/dmlc/././parameter.h:25,
>                  from /home/luwl/xgboost/dmlc-core/include/dmlc/./registry.h:14,
>                  from /home/luwl/xgboost/dmlc-core/include/dmlc/data.h:16,
>                  from /home/luwl/xgboost/include/xgboost/data.h:11,
>                  from /home/luwl/xgboost/src/c_api/c_api.cc:3:
> /home/luwl/xgboost/dmlc-core/include/dmlc/./././optional.h: At global scope:
> /home/luwl/xgboost/dmlc-core/include/dmlc/./././optional.h:26: error: ‘constexpr’ does not name a type
> /home/luwl/xgboost/dmlc-core/include/dmlc/./././optional.h:31: error: expected constructor, destructor, or type conversion before ‘const’
> /home/luwl/xgboost/dmlc-core/include/dmlc/./././optional.h:109: error: only declarations of constructors can be ‘explicit’
> /home/luwl/xgboost/dmlc-core/include/dmlc/./././optional.h:115: error: a function call cannot appear in a constant-expression

**Comment by superbobry** [comment]
Are you sure you're compiling with gcc 4.9.2?

**Comment by atlas555** [comment]
you need check create_jni.py gcc vesion

**Comment by antant-shenzhen-2013** [comment]
I follow [this link](https://gist.github.com/stephenturner/e3bc5cfacc2dc67eca8b) to upgrade gcc, g++ etc.

> [luwl@nfjd-data-complile01-9142 jvm-packages]$ which gcc
/opt/rh/devtoolset-2/root/usr/bin/gcc
[luwl@nfjd-data-complile01-9142 jvm-packages]$ gcc --version
gcc (GCC) 4.8.2 20140120 (Red Hat 4.8.2-15)
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[luwl@nfjd-data-complile01-9142 jvm-packages]$ which g++
/opt/rh/devtoolset-2/root/usr/bin/g++
[luwl@nfjd-data-complile01-9142 jvm-packages]$ g++ --version
g++ (GCC) 4.8.2 20140120 (Red Hat 4.8.2-15)
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by superbobry** [comment]
Please make sure to set CC and CXX to the right values.

**Comment by antant-shenzhen-2013** [comment]
fixed, thx.
