### ISSUE TITLE
xgboost messages should not be output into stdout/stderr but available as iterator for python module

### ISSUE THREAD

**Issue by KOLANICH** [dmlc/xgboost#3020]
This may be helpful to show them in a way not destroying CLI.

**Comment by KOLANICH** [comment]
???

**Comment by KOLANICH** [comment]
It's not quite about suppression.
If I use tqdm, or any other cli gui framework, they are usually assume that only they can output into console, because they manipupate cursor position and delete the output emiting control codes or calling API. Violating this assumption destroys cli. So these frameworks have a funtion to output messages in the way without destroying cli: passing the text to them, so they correct own output with respect to the text you output.

xgboost outputs directly, there is no way to pass output to frameworks output functions.

**Comment by tqchen** [comment]
There is something related to this in R's implementation, where the logging is hijacked and send to R's console, maybe some direction along that would be helpful

**Comment by hcho3** [comment]
@tqchen @KOLANICH `LOG(INFO)` can be re-directed to a custom callback function by defining the function `dmlc::CustomLogMessage::Log()`. The project I recently started ([dmlc/treelite](https://github.com/dmlc/treelite/blob/master/src/logging.cc)) precisely does this.
1. Have an interface in C API to register custom callback function for all logging outputs. Something like:
```cpp
int XGBRegisterLogCallback(void (*callback)(const char*))
```
2. Python package should register a callback function by calling C API.
3. Define the function `dmlc::CustomLogMessage::Log()` to make use of the callback.

Let me go ahead and file a PR to re-direct `LOG(INFO)` to Python module
