### ISSUE TITLE
R Docs num_parallel_tree marked as "Experimental"

### ISSUE THREAD

**Issue by TigerTigerWoods** [dmlc/xgboost#3023]
Hi,

The R xgBoost documentation says:

_num_parallel_tree Experimental parameter. number of trees to grow per
round. Useful to test Random Forest through Xgboost (set colsample_bytree < 1,
subsample < 1 and round = 1) accordingly. Default: 1_

Please can you explain what "Experimental" means in this case?
Thanks.

**Comment by pommedeterresautee** [comment]
It has been activated to compare XGBoost doing boosting Vs doing random forest. 
This is not a feature used a lot.

**Comment by TigerTigerWoods** [comment]
Thanks for the quick response. 

So it's more that the technique is experimental rather than the code behind it is experimental?

**Comment by pommedeterresautee** [comment]
Basically yes. At the beginning the option was not public (hidden in the C++ part) and it has been decided to make it public and to mark it as experimental.
I close the issue.
