### ISSUE TITLE
Wrong information about GPU memory allocation

### ISSUE THREAD

**Issue by QtRoS** [dmlc/xgboost#3031]
When I use GPU version it says something weird in output:
`[17:41:55] Allocated 0MB on [0] GeForce GTX 1080, 4572MB remaining.
[17:43:11] Allocated 0MB on [0] GeForce GTX 1080, 4255MB remaining.
[17:44:19] Allocated 0MB on [0] GeForce GTX 1080, 3883MB remaining.
[17:45:34] Allocated 0MB on [0] GeForce GTX 1080, 3607MB remaining.
[17:46:50] Allocated 0MB on [0] GeForce GTX 1080, 3497MB remaining.`

Actually it consumes memory, but says that 0MB used.

## Environment info
Operating System: Ubuntu 17.10

Compiler: GCC

Package used (python/R/jvm/C++):

`xgboost` version used: 0.7

## Steps to reproduce

1. Run any task on GPU.

## What have you tried?

I checked source code and found this line in device_helpers.cuh in function: `allocate`. I think that somehow size in megabytes was passed to this function and conversion to megabytes is redundant.

**Comment by RAMitchell** [comment]
Not all memory allocations get printed to the console. There are many minor memory allocations going on throughout the program so we just print major bulk allocations.

**Comment by QtRoS** [comment]
But this looks little bit strange for end user...
