### ISSUE TITLE
How to load model trained in CLI to R/Python?

### ISSUE THREAD

**Issue by khrisanfov** [dmlc/xgboost#3032]
Is it possible?
I am trying like this
```
library(xgboost)
model <- xgb.load("1000.model")
```
but it does not work

**Comment by khrisanfov** [comment]
@tqchen why it closed? You have added this functionality?

**Comment by hcho3** [comment]
You should be able to load the model from CLI into Python/R.

From now on, the issue tracker is reserved for actionable items such as feature proposals discussion, roadmaps, and bug tracking. For Q&A and discussion, please start a new thread at https://discuss.xgboost.ai/.
