### ISSUE TITLE
Incomplete/Inaccurate OS-X installation instructions

### ISSUE THREAD

**Issue by mweber-ovt** [dmlc/xgboost#3036]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System:  OS-X High Sierra

Compiler:  GCC5

Package used (python/R/jvm/C++): python

`xgboost` version used: 0.7 post3

If you are using python package, please provide

1. The python version and distribution:  Python 3.6 (Anaconda)
2. The command to install `xgboost` if you are not installing from source
`pip install xgboost`

## Steps to reproduce

There is an issue with the OS-X installation instructions:
`pip install xgboost` will not necessarily use the gcc5 compiler but the newest compiler on the system, whatever that may be, and fail.
Likewise, building with the provided makefile from source, the system default compiler will be used, and not gcc5

## What have you tried?

The issue is resolved by
`env CC=gcc-5 CXX=g++-5 pip install xgboost`
Suggest to update the installation instructions accordingly.
Credit to @davidread

**Comment by antontarasenko** [comment]
I had the same problem. I found the answer here:

* https://github.com/dmlc/xgboost/tree/master/python-package#macos

It was updated due to #3003.

But the docs are not up-to-date:

* https://xgboost.readthedocs.io/en/latest/build.html

**Comment by hcho3** [comment]
@antontarasenko I proposed a PR today to fix the doc build.
