### ISSUE TITLE
[jvm-packages] Location of dtrain_cache files

### ISSUE THREAD

**Issue by obones** [dmlc/xgboost#3038]
I'm using xgboost in a Spark environment and while it works just fine, I find that it creates lots of "dtrain_cache" files in the current directory.
In some cases, that directory is not writable which causes the training to fail. 
I believe it should be possible to specify the location where those files are created, but I could not find it in the documentation.

Here is a sample code that I use:

    val xgModel = XGBoost.trainWithDataFrame(
      sourceData.withColumn(labelColNormalizedName, labelColNormalized),
      paramMap,
      round = numRound,
      nWorkers = numWorkers,
      useExternalMemory = true,
      labelCol = labelColNormalizedName)

With this I get files created that follow this naming scheme:

    MyProgram-%d-dtrain_cache-%d
    MyProgram-%d-dtrain_cache-%d.col.meta
    MyProgram-%d-dtrain_cache-%d.col.page
    MyProgram-%d-dtrain_cache-%d.row.page
    MyProgram-%d-dtest_cache-%d
    MyProgram-%d-dtest_cache-%d.row.page

Looking at the source, it seems that it comes from `SparsePageSource::Create` but I can't find the link between this method and the `XGBoost.trainWithDataFrame` method and its params.
Any hints would be most welcome.

**Comment by Yunni** [comment]
Do you mind try patching #3022 and see if it solves your problem?

**Comment by obones** [comment]
Thanks for this, I tried patching this code into my fork and got it compiled using appveyor.
I also pulled all the latest changes but what I get as the end result is a crashing java.exe
I don't know if it comes from your code, I'll have to investigate a bit further to figure this out.

**Comment by obones** [comment]
Ok, I created a branch to be able to apply the required changes to the sources that were working back in August, you can see the result here:
https://github.com/dmlc/xgboost/compare/master...obones:0.7_working

I get the exact same crash in the JVM
Looking further at how the code behaves, I see two files being created in the current directory:

    C
    C.row.page

And I get nothing in the temp folder.
To me, it looks like the code tried to create the files from the given filename (c:\windows\temp\cache...) but stopped when it saw the colon marker typical of drive letters under Windows.
And I even suspect that this leads to the crash because many threads will try to write to the same file at the same time.

Going back to the release that I created 3 days ago, based on the master branch, I also get the same files created along with the already mentioned JVM crash.
I thus suspect that it comes from the same situation, where the colon is interpreted as a path separator instead of a drive indicator under Windows.

Could anyone point to a place where I could fix this?

**Comment by Yunni** [comment]
> To me, it looks like the code tried to create the files from the given filename (c:\windows\temp\cache...) but stopped when it saw the colon marker typical of drive letters under Windows.

We use the API `Files.createTempDirectory` which relies on `java.io.tmpdir` to get the base path. It's hard to believe that `Files.createTempDirectory` has a bug on parsing colon.

 > And I even suspect that this leads to the crash because many threads will try to write to the same file at the same time.

Each thread/executor writes to a different file prefixed by Spark stageId and taskId.

To debug the problem, would you please provide us with the commit hash of XGB library, the source code you are running and the stack trace on both the driver and executor?

**Comment by obones** [comment]
> We use the API Files.createTempDirectory which relies on java.io.tmpdir to get the base path. It's hard to believe that Files.createTempDirectory has a bug on parsing colon.
And this works just fine, it returns this value:

    C:\users\obones\AppData\Local\Temp

But what I suspect is that this gets split on a colon later on, thus leading to the creation of the `C.row.page` file.

I went back to [sparse_page_source.cc](https://github.com/dmlc/xgboost/blob/13e7a2cff0f08d9c4a659409887687f1ce6bb632/src/data/sparse_page_source.cc) and looked at the code for `SparsePageSource::Create`.
I find line 104 very intriguing because it splits `cache_info` on a colon and later on, line 107 uses the first item of the resulting array as the name of the `Stream` to create at line 162.

I was not able to debug it yet, but I wonder what happens if `cache_info` was to contain a colon as I suspect it does when given the above temp folder location.

If my analysis is correct, this would clearly explain the creation of the `C.row.page` file.

> To debug the problem, would you please provide us with the commit hash of XGB library, the source code you are running and the stack trace on both the driver and executor?

My branch is based on 39adba51c55b211441cc93a859beb72d008279de with just my changes to call `File.createTempFile`
But I can't give you any stack trace for the crash because it's Windows itself that shows up a dialog box saying "java.exe has crashed", nothing shows up on the standard or error output.

**Comment by Yunni** [comment]
@obones I think you're right. The native code is trying to use `:` as a delimiter. I will try to make a fix for it.

**Comment by obones** [comment]
Thanks for looking at this, please let me know if I can be of any help.

**Comment by CodingCat** [comment]
@Yunni you want to fix this?

**Comment by obones** [comment]
Why was this closed? Is there a fix available?

**Comment by hcho3** [comment]
This issue was closed due to the current triaging. We try to aggressive close issues from now on so opened issues like this can get attended to. I went ahead and re-opened it.

**Comment by obones** [comment]
Thanks for the explanation

**Comment by tqchen** [comment]
The dmatrix file is mainly due to external memory mode enabled. We do need the job to contain a writable place in order to enable this @CodingCat

**Comment by CodingCat** [comment]
I feel that the right approach to fix this issue is to use another char as the delimiter in native code as ":" is so error-prone in windows https://github.com/dmlc/xgboost/blob/master/src/data/sparse_page_source.cc#L195

@tqchen  what do you think?

**Comment by tqchen** [comment]
can you confirm it is indeed a splitter issue? seems @obones says that there is no local temp folder for his spark worker

**Comment by CodingCat** [comment]
I think @obones met the problem that multiple threads write to the same file leading to JVM crash

as he said

```
And this works just fine, it returns this value:

C:\users\obones\AppData\Local\Temp
But what I suspect is that this gets split on a colon later on, thus leading to the creation of the C.row.page file.
```

**Comment by obones** [comment]
Yes, that's exactly it, the path given by `Files.createTempDirectory` is indeed correct.
But because it gets split on a colon, all threads end up writing in the same file, leading to the JVM crash.
Maybe an unprintable character would be ok? Something like `0x1C`, the file separator?

**Comment by hcho3** [comment]
@obones #3869 should fix the issue. The trick is to ignore the drive letter when splitting on `:`.
