### ISSUE TITLE
AttributeError: 'Booster' object has no attribute 'best_iteration'

### ISSUE THREAD

**Issue by hujiewang** [dmlc/xgboost#304]
Here is my code:
self.booster_ = xgb.train(self.param, X, self.n_iter, wl, early_stopping_rounds=10)
self.booster_.predict(X,self.booster_.best_iteration)

Have no idea why it didn't work

**Comment by tqchen** [comment]
Make sure you install the most recent version from the github. You can trace into the xgb.train function to see what happens.

**Comment by wshenx** [comment]
@hujiewang I encountered this problem too. By increasing `num_boost_round`, I solved it!

**Comment by tqchen** [comment]
I see, this seems to be a problem in python interface

**Comment by tqchen** [comment]
please check if the latest version solves the problem

**Comment by oldmonk101** [comment]
Issue still happening for LTR. "objective": "rank:pairwise"
