### ISSUE TITLE
Why does setting more "nthread" cause performance decreasing?

### ISSUE THREAD

**Issue by hanyueyue** [dmlc/xgboost#3042]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System:
Linux

Compiler:
g++

Package used (python/R/jvm/C++):
c++

`xgboost` version used:
master branch

## Steps to reproduce

1. Set the param using  XGBoosterSetParam(h_booster, "nthread", "1");

## What have you tried?

1. when I change the nthread number from 1 to 8, the predict time increases from 37ms to 341ms. BTW, I only use one test data to predict.

Why does this happen? I think using more nthread should improve the performance.

The code is like below:
int main()
{
    BoosterHandle h_booster;
    XGBoosterCreate(0, 0, &h_booster);
    XGBoosterLoadModel(h_booster,"xgboost.model.file");
    XGBoosterSetParam(h_booster, "nthread", "1"); //change the number here
    ............
    ............
    DMatrixHandle h_test;
    XGDMatrixCreateFromCSR(indptr, indices, data, size, dataLen, &h_test);
    bst_ulong out_len;
    const float *f;
    XGBoosterPredict(h_booster, h_test, 0, 0, &out_len, &f); //the predict cost time changes according to nthread
    XGDMatrixFree(h_test);
    XGBoosterFree(h_booster);
    return 1;
}

**Comment by hanyueyue** [comment]
Can anyone know about this?

**Comment by hcho3** [comment]
@hanyueyue Could you send us a fully reproducible script (data file, model file, C source code etc.) that I can run to test? Thanks!

**Comment by hanyueyue** [comment]
@hcho3 The code is here. 
Step1: compile the code. command: g++ -I xgboost/include -I xgboost/rabit/include main.cpp xgboost/lib/libxgboost.a xgboost/rabit/lib/librabit.a xgboost/dmlc-core/libdmlc.a -fopenmp -Wall

Step2: run "./a.out"
the result is like:
xgboosterPredict mlCost : 38.336(ms) #This is the cost time.
prediction[0]=0.0382311 #This is the predict value.

Step3: Modify the nthread number in the source code. You'll find that bigger nthread causes more cost time.

Hope to get your reply. Thanks.

[test.zip](https://github.com/dmlc/xgboost/files/1774364/test.zip)

**Comment by khotilov** [comment]
@hanyueyue you are running predict for a matrix with a single row of what looks like 14182434 features. The prediction is parallelized by rows, so it wouldn't help with a single row. Moreover, since it requires allocating a data structure with 14182434*nthread elements, the more threads you use, the longer it takes. Also note that xgboost is not optimized for the case when there are many empty columns (e.g., when hashing column indices with very large hash capacity).

**Comment by hanyueyue** [comment]
@hcho3 Thank you so much.

**Comment by hcho3** [comment]
@hanyueyue I agree with @khotilov. Multithreading does not help in your case because you have only a single example to predict.

**Comment by dwroy** [comment]
I got the same problem when using  predict #3237
