### ISSUE TITLE
Hist in xgboost (RStudio)

### ISSUE THREAD

**Issue by skw1990** [dmlc/xgboost#3052]
Hi, 

May I know if hist is currently supported in R for xgboost? I hit this error message whilst running the code.

![image](https://user-images.githubusercontent.com/7208012/35191197-d83c3d2a-feaf-11e7-852b-a0a571015fdb.png)

Also, my xgboost version is up-to-date.

Thanks.

**Comment by Laurae2** [comment]
@skw1990 Which exact version/commit of xgboost are you using?

**Comment by skw1990** [comment]
xgboost_0.6-4 ....

**Comment by Laurae2** [comment]
From source or CRAN? Try from source directly. `hist` works fine from source, not from CRAN.
