### ISSUE TITLE
Quality Metric with L1 Regularization

### ISSUE THREAD

**Issue by pford221** [dmlc/xgboost#3056]
Hello -

This is a statistical question related to the **Quality** metric that is produced, for example, in R's implementation via `xgb.model.dt.tree()` function. I'm familiar with how Quality is computed in the absence of the L1 regularization term, `alpha`, but I can't figure out how it's done in its presence. My understanding is that the regularization term in the objective function with L1 regularization and L2 regularization is the following where w_j is the prediction for each node j:

(1/2) * lambda * (w_j^2) + alpha * |w_j| 

Introducing an absolute value into the equation makes the math quite a bit more difficult.

Thanks,
Patrick

**Comment by hcho3** [comment]
General questions should be directed to https://discuss.xgboost.ai/.
