### ISSUE TITLE
[jvm-packages] Scala RabitTracker tests failed 

### ISSUE THREAD

**Issue by CodingCat** [dmlc/xgboost#3059]
@xydrolase  would you take a look at the build in master branch, looks like the test in RabitTracker failed

**Comment by xydrolase** [comment]
Sure. Will do.

**Comment by CodingCat** [comment]
thanks

**Comment by xydrolase** [comment]
Do you have a link to the failed tests? I just pulled the latest `master` branch, and all tests passed on my Mac laptop.

**Comment by Yunni** [comment]
The tests will fail when MacOS is connected to VPN. Hope this helps.

**Comment by superbobry** [comment]
Probably due to `hostname` changes?

**Comment by CodingCat** [comment]
@xydrolase  https://travis-ci.org/dmlc/xgboost/jobs/331376540

@Yunni  for the VPN issue it is due to the weird configuration in Uber's laptop, when you connect with VPN, bind to 127.0.0.1 will have a lot of issues
