### ISSUE TITLE
[jvm-packages] Failed to build xgboost-spark on Windows7 with MSVS 2017

### ISSUE THREAD

**Issue by chrisplyn** [dmlc/xgboost#3070]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System:
Windows7
Compiler:
MSVS 2017
Package used (python/R/jvm/C++):
jvm
`xgboost` version used:
0.8
If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`)
2. Logs will be helpful (If logs are large, please upload as attachment).
[log.txt](https://github.com/dmlc/xgboost/files/1665809/log.txt)

If you are using jvm package, please 

1. add [jvm-packages] in the title to make it quickly be identified
2. the gcc version and distribution

If you are using python package, please provide

1. The python version and distribution
2. The command to install `xgboost` if you are not installing from source

If you are using R package, please provide

1. The R `sessionInfo()`
2. The command to install `xgboost` if you are not installing from source

## Steps to reproduce

1.cd jvm-packages
2. mvn install 
3.

## What have you tried?

1.
2.
3.

**Comment by superbobry** [comment]
Please provide logs or at least the error message during `mvn install`. Otherwise, it is impossible to tell what went wrong during the build/installation.
