### ISSUE TITLE
[jvm-packages] XGBoostEstimator rounds, seems that it does not change

### ISSUE THREAD

**Issue by albertcere** [dmlc/xgboost#3072]
**When changing "round" from paramMap from XGBEstimator, as it is a value from params as shown in http://dmlc.ml/docs/scaladocs/xgboost4j-spark/index.html#ml.dmlc.xgboost4j.scala.spark.XGBoostEstimator, it always shows one tree. If I use XGBoost object and set in its `XGBoost.trainWithDataFrame(..., round = n, ...)` it already works. Checked by using `booster.getModelDump()`**

## Environment info
Operating System: Ubuntu 16.04
Package used: JVM
`xgboost` version used: Latest version ( 84ab74f )
gcc: 5.4
Scala: 2.11
Environment: IntelliJ + SBT

## Steps to reproduce

1. Use with XGBoost and check, **WORKS**.
``` scala
val model = XGBoost.trainWithDataFrame(..., round = n, ...)
model.booster.getModelDump().foreach(println)
```
2. Use XGBoostEstimator, set paramMap an check, **DOESN'T WORK**.
``` scala
val paramMap = List(
  ... ,
  "num_rounds" -> 3,
  ...
).toMap
val xgbEstim = new XGBoostEstimator(paramMap)
  .setFeaturesCol(...)
  .setLabelCol(...)
val model = xgbEstim.fit(data)
model.booster.getModelDump().foreach(println)
```

**Comment by albertcere** [comment]
@CodingCat

**Comment by srivatsan88** [comment]
I see exact same issue with XGBoostEstimator.  num_rounds setting does not seem to work.  I am using XGboost4j 0.7 and Spark 2.2. 

XGBoost.trainWithDataFrame is working fine.

**Comment by tqchen** [comment]
close due to inactive status, general questions are now welcomed a https://discuss.xgboost.ai/
