### ISSUE TITLE
GPU model does not release memory

### ISSUE THREAD

**Issue by pavithrasv** [dmlc/xgboost#3083]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System: Ubuntu 16.04

Compiler: 

Package used (python/R/jvm/C++): python

`xgboost` version used: 0.7

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`) 14c6392381c3b63996af4bd9bb13840dd20e78bf
2. Logs will be helpful (If logs are large, please upload as attachment).

If you are using jvm package, please 

1. add [jvm-packages] in the title to make it quickly be identified -
2. the gcc version and distribution -

If you are using python package, please provide

1. The python version and distribution 2.7.12

## Steps to reproduce

Snippet of the code i run:

```
model = XGBClassifier(max_depth=6,
                      learning_rate=0.5,
                      tree_method='gpu_hist',
                     objective= 'multi:softprob')

model.fit(X=x_train,
              y=y_train,
              early_stopping_rounds=2,
              eval_set=[(x_val, y_val)],
              eval_metric=['mlogloss', 'merror'])                    
```

I am using https://www.kaggle.com/crowdflower/twitter-airline-sentiment/data for training.

## What have you tried?

1. Disabled tree_method option and the model trained successfully. 
2. Searched for solutions only extensively. I found this related issue #3045.

**Comment by RAMitchell** [comment]
See #3045

**Comment by brainnoise** [comment]
I did have a look at that issue. There the kernel crashes only when the training is run more than once. I however see the issue even when i run it just once with gpu option enabled. So, I am not sure how model.__del__() can be used here.
Thank you!

**Comment by axiomoixa** [comment]
I have the same problem with xgboost 0.7

After training, the memory is not released
```
Fri Mar  9 13:14:50 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.111                Driver Version: 384.111                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:37:00.0 Off |                    0 |
| N/A   69C    P0    45W / 250W |  11550MiB / 16276MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P100-PCIE...  Off  | 00000000:86:00.0 Off |                    0 |
| N/A   70C    P0    43W / 250W |  11245MiB / 16276MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      4926      C   ...icrosoft/ropen/3.4.3/lib64/R/bin/exec/R   299MiB |
|    0     33460      C   /usr/lib/rstudio-server/bin/rsession       11241MiB |
|    1     33460      C   /usr/lib/rstudio-server/bin/rsession       11235MiB |
+-----------------------------------------------------------------------------+

```

**Comment by tqchen** [comment]
close due to the fact that we are not able to act on this for now, new discussions are welcomed at https://discuss.xgboost.ai/

**Comment by hcho3** [comment]
Recent discussion: #4482
