### ISSUE TITLE
export booster datastructure

### ISSUE THREAD

**Issue by dksahuji** [dmlc/xgboost#3084]
I have trained boosted trees. I can dump the model and see the trees in a readable format. I have a use case where I need the tree datastructure similar to the one  given by scikit GBDT(non xgboost version). I have searched all over internet but couldnt find how to return the datastructure. 

Is there a way to achieve what I want to do?

I am using python interface.

**Comment by superbobry** [comment]
I don't think there is currently a way to convert XGBoost booster to scikit-learn format. You could probably parse the model dump and assemble the GBDT structure of scikit-learn manually.
