### ISSUE TITLE
how to cite this project?

### ISSUE THREAD

**Issue by tankle** [dmlc/xgboost#309]
how to cite this project in paper?

**Comment by tqchen** [comment]
It is a bit shame that we are working so hard on improving the project and do not yet a publication on it. Please use the github link for now.

Thanks!

**Comment by kilojoules** [comment]
+1

**Comment by rilut** [comment]
I've only found this arXiv preprint http://arxiv.org/abs/1603.02754
Maybe @tqchen have the answer :smile:

**Comment by katrinleinweber** [comment]
You could also apply https://guides.github.com/activities/citable-code/ or https://www.software.ac.uk/blog/2013-09-02-encouraging-citation-software-introducing-citation-files ;-)

**Comment by hcho3** [comment]
XGBoost has been published at KDD 2016: https://dl.acm.org/citation.cfm?id=2939785

**Comment by katrinleinweber** [comment]
So, should that citation be used, or the 1st [Reference](https://github.com/dmlc/xgboost#reference) to the arXiv version? And, would a PR with a `CITATION` files be merged?

**Comment by hcho3** [comment]
The arXiv is a preprint, so you should use the KDD paper. Yes, a `CITATION` file would be a good idea.
