### ISSUE TITLE
source directory .../xgboost-0.7.source/dmlc-core does not contain a CMakeLists.txt file

### ISSUE THREAD

**Issue by vss888** [dmlc/xgboost#3095]
This is the error I get when I attempt to compile xgboost:

```
  The source directory

    /home/.../bin/xgboost-0.7.source/dmlc-core

  does not contain a CMakeLists.txt file.

```

> ## Environment info
> Operating System:

RHEL 7.3

> Compiler:

My path contains gcc-6.4.0 but xgboost insists on using gcc-4.8.5 pre-installed with the OS.

> Package used (python/R/jvm/C++):

Whatever I downloaded from https://github.com/dmlc/xgboost/archive/v0.7.tar.gz

> `xgboost` version used:

 

v0.7

> If installing from source, please provide 
> 
> 1. The commit hash (`git rev-parse HEAD`)
> 2. Logs will be helpful (If logs are large, please upload as attachment).

1. I do not use git. I hope that by downloading the source code from https://github.com/dmlc/xgboost/archive/v0.7.tar.gz I get a self-sufficient set of source code.

2. This is the output of cmake:

$ cmake ${SOURCEDIR} -DUSE_CUDA=ON -DCMAKE_INSTALL_PREFIX:PATH=${BIN}/${PROG}
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenMP_C: -fopenmp (found version "3.1")
-- Found OpenMP_CXX: -fopenmp (found version "3.1")
-- Found OpenMP: TRUE (found version "3.1")
-- Setting build type to 'Release' as none was specified.
CMake Error at CMakeLists.txt:108 (add_subdirectory):
  The source directory

    /home/.../bin/xgboost-0.7.source/dmlc-core

  does not contain a CMakeLists.txt file.

-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found CUDA: /usr/local/cuda-9.0 (found suitable version "9.0", minimum required is "8.0")
CUDA 9.0 detected, adding Volta compute capability (7.0).
-- Configuring incomplete, errors occurred!
See also "/home/.../xgboost-0.7.build/CMakeFiles/CMakeOutput.log".
See also "/home/.../xgboost-0.7.build/CMakeFiles/CMakeError.log".

> If you are using jvm package, please 
> 
> 1. add [jvm-packages] in the title to make it quickly be identified
> 2. the gcc version and distribution
> 
> If you are using python package, please provide
> 
> 1. The python version and distribution
> 2. The command to install `xgboost` if you are not installing from source

> If you are using R package, please provide
> 
> 1. The R `sessionInfo()`
> 2. The command to install `xgboost` if you are not installing from source
> 

## Steps to reproduce

1. Download the source code from https://github.com/dmlc/xgboost/archive/v0.7.tar.gz
2. Attempt to run cmake like this: cmake ${SOURCEDIR} -DUSE_CUDA=ON -DCMAKE_INSTALL_PREFIX:PATH=${BIN}/${PROG}

I am guessing that I can only compile xgboost if I check out the source code using git, while downloading a specific release is not sufficient to be able to compile the code. Is it a correct guess? 

Thank you very much for your help.

**Comment by vss888** [comment]
Confirmed: if the source code is checked out using git, cmake works without problems.

**Comment by shawnthu** [comment]
> Confirmed: if the source code is checked out using git, cmake works without problems.

what does this mean? How can i do it?

**Comment by hcho3** [comment]
See the Installation Guide from https://xgboost.readthedocs.org

**Comment by shawnthu** [comment]
> See the Installation Guide from https://xgboost.readthedocs.org

I just downloaded the compressed source code of latest release version, it prompted that
`The source directory

    /home/.../bin/xgboost-0.7.source/dmlc-core

  does not contain a CMakeLists.txt file.
`
does it mean i should git clone dmlc-core into the corresponding directory?

**Comment by WorgenZhang** [comment]
"git clone --recursive https://github.com/dmlc/xgboost.git" helps me.
