### ISSUE TITLE
Custom Objective Function from examples disagrees with default.

### ISSUE THREAD

**Issue by oxinabox** [dmlc/xgboost#3096]
https://github.com/dmlc/xgboost/blob/master/demo/guide-python/custom_objective.py
shows defining a custom function that is the logistic regression objective.
Using it thus should be roughly equivelent to not specifying an objective,
since the default is `'binary:logistic'`

This does not seem to be the case.

## Environment info
Operating System: Linux

Package used: python

`xgboost` version used: `xgb.__version__ == '0.7.post3'`

1. The python version and distribution
Python 3.3

2. The command to install `xgboost` if you are not installing from source
`pip3 install xboost`

## Steps to reproduce
This is a simplified version of https://github.com/dmlc/xgboost/blob/master/demo/guide-python/custom_objective.py

```python
#!/usr/bin/python
import numpy as np
import xgboost as xgb

np.random.seed(2) #Reproducable training data
Xs = np.random.rand(5,2)
Ys = np.logical_and(Xs[:,1]>0.2,  Xs[:,0]>0.3)

print("Xs", Xs)
print("Ys", Ys)

dtrain = xgb.DMatrix(Xs, Ys)

# note: for customized objective function, we leave objective as default
# note: what we are getting is margin value in prediction
# you must know what you are doing
param = {'max_depth': 2, 'eta': 1, 'silent': 1}

# user define objective function, given prediction, return gradient and second order gradient
# this is log likelihood loss
def logregobj(preds, dtrain):
    labels = dtrain.get_label()
    preds = 1.0 / (1.0 + np.exp(-preds))
    grad = preds - labels
    hess = preds * (1.0 - preds)
    return grad, hess


# training with customized objective, we can also do step by step training
# simply look at xgboost.py's implementation of train
bst = xgb.train(param, dtrain, obj=logregobj)
print("custom", bst.predict(dtrain))
dst = xgb.train(param, dtrain)
print("default", dst.predict(dtrain))

```

### Output:

```
Xs [[ 0.4359949   0.02592623]
 [ 0.54966248  0.43532239]
 [ 0.4203678   0.33033482]
 [ 0.20464863  0.61927097]
 [ 0.29965467  0.26682728]]
Ys [False  True  True False False]
custom [-0.40514001 -0.40514001 -0.40514001 -0.40514001 -0.40514001]
default [  4.96542430e-04   1.00032711e+00   9.98583794e-01   4.36608680e-04
   2.93712132e-04]
```

It is expected that the custom line and the default line should be at least similar.
But it seems the custom line is actually returning the same value for all inputs.

## What have you tried?
A whole bunch of stuff, that I ended up with this MWE.

**Comment by khotilov** [comment]
The default objective is 'reg:linear'.
```python
param['objective'] = 'binary:logistic'
dst = xgb.train(param, dtrain)
print("default", dst.predict(dtrain, output_margin=True))
```
```
default [-0.40531313 -0.40531313 -0.40531313 -0.40531313 -0.40531313]
```

**Comment by oxinabox** [comment]
Ah my bad, I had gotten used the the Sklearn classify method.
I screwed up in translating it to the normal  API  form.

Note however: those results are not identical.
They differ by 0.00017312.

In my less minimized example, they differ by a whole lot more: between 0.01 and 0.05.

```
Xs = np.zeros((16,58))
Xs[[0,0,0,1,1,1,2,2,2,2,2,3,3,3,3,4,4,4,5,5,5,6,6,6,6,6,7,7,7,8,8,8,9,9,9,10,10,10,10,10,11,11,11,12,12,12,12,13,13,13,14,14,14,15,15,15,15,15],[33,40,43,32,44,56,32,35,45,50,56,32,35,45,56,44,46,51,32,44,56,32,35,45,50,56,32,49,50,40,44,51,32,44,56,32,35,45,50,56,32,49,50,32,43,50,56,32,35,45,32,44,56,32,35,45,50,56]]+=1
Xs[[0,3,7,11,12],[43,45,32,32,43]]+=1
Ys = np.array([1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0])

dtrain = xgb.DMatrix(Xs, Ys)
```

In my real case, they seem to differ enough that classifications go one way instead of the other.


Is this attributable to different rounding errors?

**Comment by khotilov** [comment]
> Is this attributable to different rounding errors?

Practically, yes. The built in objective operates with floats and has a tiny eps adjustment when the hessian gets too small https://github.com/dmlc/xgboost/blob/84ab74f3a56739829b03161fb9c249f3a760a518/src/objective/regression_loss.h#L45
