### ISSUE TITLE
when installing, coming into error: clang: error: unsupported option '-fopenmp' 

### ISSUE THREAD

**Issue by jeremy-dai** [dmlc/xgboost#3102]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System: macOS High Sierra

Compiler: gcc -dumpversion
4.2.1

Package used (python/R/jvm/C++): python

`xgboost` version used: xgboost-0.7.post3.tar.gz

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`)
2. Logs will be helpful (If logs are large, please upload as attachment).

If you are using jvm package, please 

1. add [jvm-packages] in the title to make it quickly be identified
2. the gcc version and distribution

If you are using python package, please provide

1. The python version and distribution
Python 3.5.3 :: Anaconda 4.4.0 (x86_64)
2. The command to install `xgboost` if you are not installing from source
pip install xgboost

I get:
$ pip install xgboost
Collecting xgboost
  Using cached xgboost-0.7.post3.tar.gz
    Complete output from command python setup.py egg_info:
    ++ pwd
    + oldpath=/private/var/folders/kk/s62ph0w57qvg01wx495b7nqw0000gn/T/pip-build-5aZMnp/xgboost
    + cd ./xgboost/
    + [[ darwin17 == \d\a\r\w\i\n* ]]
    + LIB_XGBOOST=libxgboost.dylib
    + make lib/libxgboost.dylib -j4
    Makefile:31: MAKE [/Library/Developer/CommandLineTools/usr/bin/make] - checked OK
    c++ -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -I/private/var/folders/kk/s62ph0w57qvg01wx495b7nqw0000gn/T/pip-build-5aZMnp/xgboost/xgboost/dmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/learner.o src/learner.cc >build/learner.d
    c++ -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -I/private/var/folders/kk/s62ph0w57qvg01wx495b7nqw0000gn/T/pip-build-5aZMnp/xgboost/xgboost/dmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/logging.o src/logging.cc >build/logging.d
    c++ -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -I/private/var/folders/kk/s62ph0w57qvg01wx495b7nqw0000gn/T/pip-build-5aZMnp/xgboost/xgboost/dmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/c_api/c_api.o src/c_api/c_api.cc >build/c_api/c_api.d
    c++ -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -I/private/var/folders/kk/s62ph0w57qvg01wx495b7nqw0000gn/T/pip-build-5aZMnp/xgboost/xgboost/dmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/c_api/c_api_error.o src/c_api/c_api_error.cc >build/c_api/c_api_error.d
    clang: error: unsupported option '-fopenmp'
    clang: error: unsupported option '-fopenmp'
    make: *** [build/logging.o] Error 1
    make: *** Waiting for unfinished jobs....
    make: *** [build/learner.o] Error 1
    clang: error: unsupported option '-fopenmp'
    clang: error: unsupported option '-fopenmp'
    make: *** [build/c_api/c_api_error.o] Error 1
    make: *** [build/c_api/c_api.o] Error 1
    + echo -----------------------------
    -----------------------------
    + echo 'Building multi-thread xgboost failed'
    Building multi-thread xgboost failed
    + echo 'Start to build single-thread xgboost'
    Start to build single-thread xgboost
    + make clean
    Makefile:31: MAKE [/Library/Developer/CommandLineTools/usr/bin/make] - checked OK
    rm -f -rf build build_plugin lib bin *~ */*~ */*/*~ */*/*/*~ */*.o */*/*.o */*/*/*.o #xgboost
    rm -f -rf build_tests *.gcov tests/cpp/xgboost_test
    cd R-package/src; rm -f -rf rabit src include dmlc-core amalgamation *.so *.dll; cd /private/var/folders/kk/s62ph0w57qvg01wx495b7nqw0000gn/T/pip-build-5aZMnp/xgboost/xgboost
    /bin/sh: line 0: cd: R-package/src: No such file or directory
    + make lib/libxgboost.dylib -j4 USE_OPENMP=0
    Makefile:31: MAKE [/Library/Developer/CommandLineTools/usr/bin/make] - checked OK
    Makefile:43: /private/var/folders/kk/s62ph0w57qvg01wx495b7nqw0000gn/T/pip-build-5aZMnp/xgboost/xgboost/dmlc-core/make/dmlc.mk: No such file or directory
    make: *** No rule to make target `/private/var/folders/kk/s62ph0w57qvg01wx495b7nqw0000gn/T/pip-build-5aZMnp/xgboost/xgboost/dmlc-core/make/dmlc.mk'.  Stop.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/kk/s62ph0w57qvg01wx495b7nqw0000gn/T/pip-build-5aZMnp/xgboost/setup.py", line 37, in <module>
        LIB_PATH = libpath['find_lib_path']()
      File "/private/var/folders/kk/s62ph0w57qvg01wx495b7nqw0000gn/T/pip-build-5aZMnp/xgboost/xgboost/libpath.py", line 49, in find_lib_path
        'List of candidates:\n' + ('\n'.join(dll_path)))
    __builtin__.XGBoostLibraryNotFound: Cannot find XGBoost Library in the candidate path, did you install compilers and run build.sh in root path?
    List of candidates:
    /private/var/folders/kk/s62ph0w57qvg01wx495b7nqw0000gn/T/pip-build-5aZMnp/xgboost/xgboost/libxgboost.dylib
    /private/var/folders/kk/s62ph0w57qvg01wx495b7nqw0000gn/T/pip-build-5aZMnp/xgboost/xgboost/../../lib/libxgboost.dylib
    /private/var/folders/kk/s62ph0w57qvg01wx495b7nqw0000gn/T/pip-build-5aZMnp/xgboost/xgboost/./lib/libxgboost.dylib
    /System/Library/Frameworks/Python.framework/Versions/2.7/xgboost/libxgboost.dylib
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/kk/s62ph0w57qvg01wx495b7nqw0000gn/T/pip-build-5aZMnp/xgboost/

**Comment by hcho3** [comment]
This bug occurs because the default `gcc` installed on macOS is actually `clang` without OpenMP.
I suggest that you install GCC 7 with homebrew:
```
# from xgboost directory
brew install gcc@7
```
Then tell CMake to use GCC 7:
```
mkdir build
cd build
cmake .. -DCMAKE_C_COMPILER=gcc-7 -DCMAKE_CXX_COMPILER=g++-7
make -j4
```
