### ISSUE TITLE
Distributed on shared clusters or non-homogenous machines

### ISSUE THREAD

**Issue by AbdealiJK** [dmlc/xgboost#3104]
One of the issues I've faced when running xgboost is that if I have a shared cluster with 10 jobs running at any time... XGBoost behaves very badly. 

In the sense, if I have 50 machines and 10 jobs (for map reduce or other xgboost jobs)  are running at any point of time... If I run a new xgboost job the job has the following issues:

 - the slowest machine in the allocated machines is bottle neck

If the slowest machine takes 1 minute to create a tree, and all other machines take only 10sec to create a tree, xgboost will wait for the slowest machine to decide the 1st split criteria. 
Are there any thoughts on modifying this behaviour so that it runs on shared cluster setups or even for non-homogenous clusters in some way?

**Comment by AbdealiJK** [comment]
Any thoughts on this one ?

**Comment by tqchen** [comment]
this is an open-ended question, we do  not have actionable items yet on this, so let us move it to https://discuss.xgboost.ai/.
