### ISSUE TITLE
Update Documentation: what is the effect of setting sample weights?

### ISSUE THREAD

**Issue by FrederikLauber** [dmlc/xgboost#3112]
Hello,

this is a request to update the documentation to make it more clear what setting a sample weight will do.

While the obvious interaction (weighting one event to another) is clear, other effects are not clear. For example:

Does scaling all weights by a factor of x change anything within xgboost? The answer is yes because AFAIK factors like min_child_weight are tied to the total integrated weight which changes by multiplying a factor in.

What is the relation between sample size and integrated sample weight?
I am looking for a raw signal for that I have a lot of simulation within a very often recorded event for which I have a high weight (my weights are basically the rate how often this event is seen) but with fewer samples.
Example:
Signal 10^6 events, integrated weight 1mHz
Background: 10^3 events, integrated weight 30Hz
At the moment, I am scaling the weights of both signal and background to 1 before feeding them into xgboost but I am not sure if this is the right way to go.

Please, update the documentation so we can get a bit more inside how the sample weight will actually change the results.

**Comment by tqchen** [comment]
This is a question that can be asked at https://discuss.xgboost.ai/, after sufficient discussion, we would be welcoming a PR to improve the docs
