### ISSUE TITLE
Gradient boosting for regression - bad results with gpu_hist method

### ISSUE THREAD

**Issue by PlayMen** [dmlc/xgboost#3113]
## Environment info
Operating System: **Linux from Oracle**

Compiler: **GCC 5.4.0**

Package used (python/R/jvm/C++): **python**

`xgboost` version used: **0.6**

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`) **7c6673cb9ef7f68f92075123dc78e9661ce3d4e5**
2. Logs will be helpful (If logs are large, please upload as attachment). **N/A**

If you are using python package, please provide

1. The python version and distribution - **miniconda 3.6**
2. The command to install `xgboost` if you are not installing from source - **python setup.py develop --user**

## Steps to reproduce

mv xgboost_hist_regress.txt xgboost_hist_regress.py

1. Run script with gpu_hist method - change it in code
2. Run script with cpu_hist method - change it in code
3. See different results

[xgboost_hist_regress.txt](https://github.com/dmlc/xgboost/files/1723374/xgboost_hist_regress.txt)

Dataset: https://archive.ics.uci.edu/ml/datasets/yearpredictionmsd

CPU output:
[ 1991.38269043  1999.25146484  1998.71606445 ...,  2003.87854004
  2001.29663086  2000.38952637]
MAE:  6.42201901365
MSE:  83.3333276985

GPU:
[ 0.5  0.5  0.5 ...,  0.5  0.5  0.5]
MAE:  1997.99575828
MSE:  3992104.81405

GPU: cuda 9.0, Tesla V100
CPU: Intel(R) Xeon(R) Platinum 8168 CPU @ 2.70GHz, 2x24, 63GB RAM

**Comment by fattyJake** [comment]
Similar problem here.

**Comment by hcho3** [comment]
@PlayMen @fattyJake Closing for now. Feel free to re-open this issue if you manage to re-produce the problem with the latest master.

**Comment by OlegKremnyov** [comment]
Works with 7.x now
