### ISSUE TITLE
Check failed: tree[nid].is_leaf()

### ISSUE THREAD

**Issue by EvanzzzZ** [dmlc/xgboost#3114]
Hi, when I trained xgboost model, after few iteration, I got this error:
[11:12:47] src/tree/./updater_basemaker-inl.h:272: Check failed: tree[nid].is_leaf
()
terminate called after throwing an instance of 'dmlc::Error'
what(): [11:12:47] src/tree/./updater_basemaker-inl.h:272: Check failed: tree[nid].is_leaf()

Any clue about why this might happened?

**Comment by hcho3** [comment]
@EvanzzzZ Can you post a script that reproduces the issue?

**Comment by EvanzzzZ** [comment]
I don't have a script right now but I am running binary:logistic at scale.
