### ISSUE TITLE
Issue with Pip Install

### ISSUE THREAD

**Issue by Andreilys** [dmlc/xgboost#3118]
Downloading via pip install xgboost on my mac with python 3.5.4 I encounter this error:

    ++ pwd
    + oldpath=/private/tmp/pip-build-w_r84zub/xgboost
    + cd ./xgboost/
    + [[ darwin17 == \d\a\r\w\i\n* ]]
    + LIB_XGBOOST=libxgboost.dylib
    + make lib/libxgboost.dylib -j4
    Makefile:31: MAKE [/Applications/Xcode.app/Contents/Developer/usr/bin/make] - checked OK
    c++ -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -I/private/tmp/pip-build-w_r84zub/xgboost/xgboost/dmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/learner.o src/learner.cc >build/learner.d
    c++ -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -I/private/tmp/pip-build-w_r84zub/xgboost/xgboost/dmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/logging.o src/logging.cc >build/logging.d
    c++ -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -I/private/tmp/pip-build-w_r84zub/xgboost/xgboost/dmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/c_api/c_api.o src/c_api/c_api.cc >build/c_api/c_api.d
    c++ -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -I/private/tmp/pip-build-w_r84zub/xgboost/xgboost/dmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/c_api/c_api_error.o src/c_api/c_api_error.cc >build/c_api/c_api_error.d
    clang: error: unsupported option '-fopenmp'clang: error: unsupported option '-fopenmp'clang: error: unsupported option '-fopenmp'clang: error: unsupported option '-fopenmp'

    make: *** [build/logging.o] Error 1
    make: *** Waiting for unfinished jobs....
    make: *** [build/c_api/c_api.o] Error 1
    make: *** [build/learner.o] Error 1
    make: *** [build/c_api/c_api_error.o] Error 1
    + echo -----------------------------
    -----------------------------
    + echo 'Building multi-thread xgboost failed'
    Building multi-thread xgboost failed
    + echo 'Start to build single-thread xgboost'
    Start to build single-thread xgboost
    + make clean
    Makefile:31: MAKE [/Applications/Xcode.app/Contents/Developer/usr/bin/make] - checked OK
    rm -f -rf build build_plugin lib bin *~ */*~ */*/*~ */*/*/*~ */*.o */*/*.o */*/*/*.o #xgboost
    rm -f -rf build_tests *.gcov tests/cpp/xgboost_test
    cd R-package/src; rm -f -rf rabit src include dmlc-core amalgamation *.so *.dll; cd /private/tmp/pip-build-w_r84zub/xgboost/xgboost
    /bin/sh: line 0: cd: R-package/src: No such file or directory
    + make lib/libxgboost.dylib -j4 USE_OPENMP=0
    Makefile:31: MAKE [/Applications/Xcode.app/Contents/Developer/usr/bin/make] - checked OK
    Makefile:43: /private/tmp/pip-build-w_r84zub/xgboost/xgboost/dmlc-core/make/dmlc.mk: No such file or directory
    make: *** No rule to make target `/private/tmp/pip-build-w_r84zub/xgboost/xgboost/dmlc-core/make/dmlc.mk'.  Stop.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-w_r84zub/xgboost/setup.py", line 37, in <module>
        LIB_PATH = libpath['find_lib_path']()
      File "/private/tmp/pip-build-w_r84zub/xgboost/xgboost/libpath.py", line 49, in find_lib_path
        'List of candidates:\n' + ('\n'.join(dll_path)))
    XGBoostLibraryNotFound: Cannot find XGBoost Library in the candidate path, did you install compilers and run build.sh in root path?
    List of candidates:
    /private/tmp/pip-build-w_r84zub/xgboost/xgboost/libxgboost.dylib
    /private/tmp/pip-build-w_r84zub/xgboost/xgboost/../../lib/libxgboost.dylib
    /private/tmp/pip-build-w_r84zub/xgboost/xgboost/./lib/libxgboost.dylib
    /Users/andreilyskov/anaconda/xgboost/libxgboost.dylib

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-w_r84zub/xgboost/

**Comment by AbdealiJK** [comment]
Seems like you're not using GNU `gcc` and are using `clang`.

Check http://xgboost.readthedocs.io/en/latest/build.html#building-on-macos
It states:

First, make sure you obtained `gcc-5` (newer version does not work with this method yet).
> Note: installation of gcc can take a while (~ 30 minutes)

```
brew install gcc5
```
You might need to run the following command with sudo if you run into some permission errors:

```
pip install xgboost
```

**Comment by shahabraji** [comment]
I have the same issue, and I already have gcc5 installed.

    $ brew list
    gcc@5	gmp	libmpc	mpfr

**Comment by birdsotter** [comment]
I am having the same issue on Mac OSX 10.13.3. I have followed the [Installation Guide](http://xgboost.readthedocs.io/en/latest/build.html#building-on-macos) and get this error:

    Complete output from command python setup.py egg_info:
    ++ pwd
    + oldpath=/private/var/folders/8p/6wts225s6250n72h9vddjgfw0000gn/T/pip-build-14lmuaz3/xgboost
    + cd ./xgboost/
    + [[ darwin17 == \d\a\r\w\i\n* ]]
    + LIB_XGBOOST=libxgboost.dylib
    + make lib/libxgboost.dylib -j4
    Makefile:31: MAKE [/Library/Developer/CommandLineTools/usr/bin/make] - checked OK
    c++ -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -I/private/var/folders/8p/6wts225s6250n72h9vddjgfw0000gn/T/pip-build-14lmuaz3/xgboost/xgboost/dmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/logging.o src/logging.cc >build/logging.d
    c++ -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -I/private/var/folders/8p/6wts225s6250n72h9vddjgfw0000gn/T/pip-build-14lmuaz3/xgboost/xgboost/dmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/learner.o src/learner.cc >build/learner.d
    c++ -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -I/private/var/folders/8p/6wts225s6250n72h9vddjgfw0000gn/T/pip-build-14lmuaz3/xgboost/xgboost/dmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/c_api/c_api.o src/c_api/c_api.cc >build/c_api/c_api.d
    c++ -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -I/private/var/folders/8p/6wts225s6250n72h9vddjgfw0000gn/T/pip-build-14lmuaz3/xgboost/xgboost/dmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/c_api/c_api_error.o src/c_api/c_api_error.cc >build/c_api/c_api_error.d
    clangclang: : errorerror: clang: error: unsupported option '-fopenmp'unsupported option '-fopenmp'
    
    : unsupported option '-fopenmp'
    clang: error: unsupported option '-fopenmp'
    make: *** [build/c_api/c_api_error.o] Error 1
    make: *** Waiting for unfinished jobs....
    make: *** [build/c_api/c_api.o] Error 1
    make: *** [build/learner.o] Error 1
    make: *** [build/logging.o] Error 1
    + echo -----------------------------
    -----------------------------
    + echo 'Building multi-thread xgboost failed'
    Building multi-thread xgboost failed
    + echo 'Start to build single-thread xgboost'
    Start to build single-thread xgboost
    + make clean
    Makefile:31: MAKE [/Library/Developer/CommandLineTools/usr/bin/make] - checked OK
    rm -f -rf build build_plugin lib bin *~ */*~ */*/*~ */*/*/*~ */*.o */*/*.o */*/*/*.o #xgboost
    rm -f -rf build_tests *.gcov tests/cpp/xgboost_test
    cd R-package/src; rm -f -rf rabit src include dmlc-core amalgamation *.so *.dll; cd /private/var/folders/8p/6wts225s6250n72h9vddjgfw0000gn/T/pip-build-14lmuaz3/xgboost/xgboost
    /bin/sh: line 0: cd: R-package/src: No such file or directory
    + make lib/libxgboost.dylib -j4 USE_OPENMP=0
    Makefile:31: MAKE [/Library/Developer/CommandLineTools/usr/bin/make] - checked OK
    Makefile:43: /private/var/folders/8p/6wts225s6250n72h9vddjgfw0000gn/T/pip-build-14lmuaz3/xgboost/xgboost/dmlc-core/make/dmlc.mk: No such file or directory
    make: *** No rule to make target `/private/var/folders/8p/6wts225s6250n72h9vddjgfw0000gn/T/pip-build-14lmuaz3/xgboost/xgboost/dmlc-core/make/dmlc.mk'.  Stop.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/8p/6wts225s6250n72h9vddjgfw0000gn/T/pip-build-14lmuaz3/xgboost/setup.py", line 37, in <module>
        LIB_PATH = libpath['find_lib_path']()
      File "/private/var/folders/8p/6wts225s6250n72h9vddjgfw0000gn/T/pip-build-14lmuaz3/xgboost/xgboost/libpath.py", line 49, in find_lib_path
        'List of candidates:\n' + ('\n'.join(dll_path)))
    XGBoostLibraryNotFound: Cannot find XGBoost Library in the candidate path, did you install compilers and run build.sh in root path?
    List of candidates:
    /private/var/folders/8p/6wts225s6250n72h9vddjgfw0000gn/T/pip-build-14lmuaz3/xgboost/xgboost/libxgboost.dylib
    /private/var/folders/8p/6wts225s6250n72h9vddjgfw0000gn/T/pip-build-14lmuaz3/xgboost/xgboost/../../lib/libxgboost.dylib
    /private/var/folders/8p/6wts225s6250n72h9vddjgfw0000gn/T/pip-build-14lmuaz3/xgboost/xgboost/./lib/libxgboost.dylib
    /usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/xgboost/libxgboost.dylib
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/8p/6wts225s6250n72h9vddjgfw0000gn/T/pip-build-14lmuaz3/xgboost/

**Comment by hcho3** [comment]
Hi all:

I have just uploaded the new pip package on PyPI. You should be able to install by typing
```
pip3 install xgboost==0.7.post4
```

**Comment by birdsotter** [comment]
Thanks, Philip, good to know. I eventually managed to install using Anaconda.

**Comment by itaifrenkel** [comment]
@hcho3 Could you please tag this specific commit using a git tag ? Some environments require installing from source, and keeping exact compatibility with pip versions without a github tag is difficult. thanks!

**Comment by hcho3** [comment]
@itaifrenkel The version 0.7.post4 is exactly same as 0.7, except for the packaging logic. There should not be any issue with compatibility.
