### ISSUE TITLE
[jvm-packages] Installation issues during mvn package on spark module

### ISSUE THREAD

**Issue by dexara** [dmlc/xgboost#3127]
Operating System: Windows 10
Package used (python/R/jvm/C++): jvm
`xgboost` version used: whatever the latest is, pulled 5 days ago

I apologise if this is the wrong place for these types of questions, if I could be passed onto where to ask these kinds of question that'd be great. This is fairly long, summary is at the bottom 

I'm trying to install/use xgboost for the first time, and have limited/no prior experience with a number of the steps involved in installation from source. Essentially the end product that I'm looking for is to end up with a jar/s that I can put into another **Java** project (that's not using maven), i.e we're not interested in spark/flink for now.  **QUESTION 1**: I assume this is possible? The wording in the [jvm package installation guide](http://xgboost.readthedocs.io/en/latest/jvm/) and in [this question](https://stackoverflow.com/questions/43204056/i-built-a-library-with-maven-how-do-i-find-its-jar-so-that-i-can-use-it-without) suggests it is. But best to ask just in case...

My current issues I'm sure are more down to a misunderstanding on my part of exactly the process I'm doing (having never used maven before this, for example, and having limited knowledge of lower level OS processes etc). 

I've resolved a bunch of problems already in the installation process that were to do with system/user environment variables (I'm on a work pc, no admin rights) clashing after having installed git, maven and cmake. When running `mvn package` or `mvn install` I can now get to this stage: 

![capture1](https://user-images.githubusercontent.com/36707308/36499841-66d13a5c-173a-11e8-8aff-48dd39f2e8a9.PNG)

The spark stage fails while running tests and produces a fair few hundred lines of error code which I won't post in it's entirety unless asked for in a reply, but here's the first of them: 

![capture2](https://user-images.githubusercontent.com/36707308/36500190-86c3d080-173b-11e8-8731-842bab149049.PNG)

**QUESTION 2**: I've never used spark/flink/hadoop etc before, and am not intending to right now. Is it assumed that I have these/support for these installed on my system, even when I don't actually want to use them? I've attempted to remove the spark/flink/example modules from the master pom file under xgboost/jvm_packages/pom.xml to avoid doing their work, which leads to completed maven packaging/installation. 

But then we get onto this part of the installation. 

![capture3](https://user-images.githubusercontent.com/36707308/36500642-b8086330-173c-11e8-8dd2-cfdce7dfe1f5.PNG)

Best I can guess, having done the initial installation, there is now a sort of self referential process to build the final jar. Even without doing this final step, I am now able to include the newly-created "xgboost4j-0.8-SNAPSHOT-jar-with-dependencies.jar" under _.../xgboost/jvm-packages/xgboost4j/target/_ OR _.../.m2/repository/ml/dmlc/xgboost4j/0.8-SNAPSHOT/_. The import for e.g DMatrix resolves and I can have a statement like `DMatrix d = new DMatrix("");` without complaints, however the project (as expected, having not yet done the final step) cannot run, spewing out this exception: 

[17:16:17] C:\[redacted]\xgboost\dmlc-core\include\dmlc/logging.h:300: [17:16:17] C:\[redacted]\xgboost\dmlc-core\src\io\local_filesys.cc:66: LocalFileSystem.GetPathInfo temp Error:No such file or directory
Exception in thread "main" ml.dmlc.xgboost4j.java.XGBoostError: [17:16:17] C:\[redacted]\xgboost\dmlc-core\src\io\local_filesys.cc:66: LocalFileSystem.GetPathInfo temp Error:No such file or directory
	at ml.dmlc.xgboost4j.java.XGBoostJNI.checkCall(XGBoostJNI.java:48)
	at ml.dmlc.xgboost4j.java.DMatrix.<init>(DMatrix.java:68)
	at Other.RandomTestCode.main(PHDCode.java:93)

But back to including the dependency, I assume it is meant to be added to the parent pom.xml, located in  _.../xgboost/jvm-packages/_ as opposed to the pom.xml in _.../xgboost/jvm-packages/xgboost4j/_ (however I've tried both anyway). 

**QUESTION 3**: Having added this dependency, I assume I'm now supposed to re package/install the project? 

If I do this, I end up with this error, i.e it can't find the dependency we just added:

![capture4](https://user-images.githubusercontent.com/36707308/36501270-9581e6d6-173e-11e8-9eb6-86c322c59ead.PNG)

## In summary

I want to end up essentially having a jar that I can include in an existing (non-maven) java project. Mvn package is failing at the spark module stage. Do I need to complete all five stages, or are just the xgboost-jvm and xgboost4j modules enough for what I want? If not, do I need to have whatever it is the spark/flink needs to run installed to build those modules (and why is this not including in the installation guide...), or is the error I'm getting something else entirely (can post more of the error if needed, in it's entirety it's thousands of lines)? Assuming we get past this stage, can someone explain in more detail than the (very sparse) jvm-package installation instructions what I need to do with the extra dependency we have to add? 

Thank you very much if you made it through all that. Again, apologies if this is the wrong place for these kinds of questions, but I'm at the end of my wits/temper/patience essentially.

**Comment by superbobry** [comment]
This does not directly answer your questions, but you can assemble a cross-platform JAR using [`download_last_release.py`](https://github.com/criteo-forks/xgboost-jars/blob/master/download_latest_release.py) from criteo-forks/xgboost-jars.

**Comment by dexara** [comment]
Ah OK cool, so that'll get me the actual xgboost code in a jar, but missing its dependencies? E.G when including "xgboost4j-0.7-criteo-20171220.jar" that was generated after running download_last_release.py, the DMatrix import resolves but running gives 

`Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory`

which is obviously top of the DMatrix class.

Thanks

**Comment by Craigacp** [comment]
If you run "mvn package assembly:single" it should generate a XGBoost4j jar with dependencies in the xgboost4j/target folder. Then put that jar file wherever you need it.
