### ISSUE TITLE
SHAP values / predcontrib=TRUE fails in R-package

### ISSUE THREAD

**Issue by jdb78** [dmlc/xgboost#3138]
There seems to be a problem with SHAP values in the R package. Everything works smoothly for me in python.

When executing the first example in 
https://github.com/dmlc/xgboost/blob/master/R-package/R/xgb.plot.shap.R
xgb.plot.shap(agaricus.test$data, model = bst, features = "odor=none")
throws an error:
`Error in matrix(ret, ncol = 1, dimnames = dnames) : length of 'dimnames' [2] not equal to array extent` in the `predict.xgb.Booster` function.

I looked into what the call `ret <- .Call(XGBoosterPredict_R, object$handle, newdata, option[1], as.integer(ntreelimit))` in the `predict.xgb.Booster` function returns and it is only the direct predictions and not the SHAP values.

## Environment info
Operating System: Windows 10
Compiler: gcc
Package used : R installed from source
`xgboost` version used: current development version 0.7.0

**Comment by khotilov** [comment]
It works in Appveyor continuous integration (examples are checked during CRAN check), it works for me. So, most likely, you are loading an outdated library.
