### ISSUE TITLE
Monotonic constraints for Calibration

### ISSUE THREAD

**Issue by marugari** [dmlc/xgboost#3142]
XGBoost (monotonic constraints) seems useful for Probability calibration.

https://github.com/marugari/xgboost/blob/calibration/python-package/xgboost/sklearn.py#L640

https://github.com/marugari/Notebooks/blob/master/XGBoost_Calibration.ipynb

**Comment by tqchen** [comment]
Community discussions are welcomed at https://discuss.xgboost.ai/!
