### ISSUE TITLE
xgboost loading libsvm data, the feature numbers of Dmatrix and original data are out of sync

### ISSUE THREAD

**Issue by xixi2715** [dmlc/xgboost#3145]
I used xgboost in python, the code is folowing:
```
import xgboost as xgb
import numpy as np

dtrain = xgb.DMatrix('/Users/yinfengzhao/PycharmProjects/xgboost/demo/data/agaricus.txt.train')
print dtrain.feature_names

param = {'max_depth':3, 'eta':1, 'silent':1, 'objective':'binary:logistic' }
num_round = 50
bst = xgb.train(param, dtrain, num_round)
bst.save_model('demo.model')
```
the link of `agaricus.txt.train` is https://github.com/dmlc/xgboost/blob/master/demo/data/agaricus.txt.train. This data contains 126 features, but `dtrain.feature_names` print 127 columns of feature. Is there something wrong with xgboost when it loads libsvm data? The feature numbers of Dmatrix and original data are out of sync.

**Comment by khotilov** [comment]
The libsvm format in xgboost allows having a 0-indexed column. Even if the 0:x column was not present in data, DMatrix would still have an empty first column (which is harmless).
