### ISSUE TITLE
java.lang.NoSuchMethodError: org.apache.spark.scheduler.LiveListenerBus.listeners()Ljava/util/concurrent/CopyOnWriteArrayList

### ISSUE THREAD

**Issue by deniska2010** [dmlc/xgboost#3151]
Hi!
I'm trying to run the following code to train my Xgboost model:
```
val indexerAfterIF = stringIndexer(dataNotAnomalies)
val dataNotAnomaliesWithDoubleOkveds = indexerAfterIF.transform(dataNotAnomalies)
val trackerConf = new TrackerConf(0L, "scala")
    val numRound = 500
    val numWorkers = 10
    // training parameters
    val paramMap = List(
      "eta" -> 0.2f,
      "max_depth" -> 4,
      "min_child_weight" -> 3.0,
      "subsample" -> 0.55,
      "colsample_bytree" -> 0.56,
      "eval_metric" -> "mlogloss",
      "tracker_conf" -> trackerConf,
      "silent" -> 1,
      "objective" -> "multi:softmax",
      "num_class" -> nClasses,
      "lambda" -> 3.3000000000000003,
      "gamma" -> 4.7,
      "alpha" -> 0.9
    ).toMap
 val xgBoostModelWithDF = {
      XGBoost
        .trainWithDataFrame(dataNotAnomaliesWithDoubleOkveds,
          paramMap,
          round = numRound,
          nWorkers = numWorkers,
          useExternalMemory = true)
    }
```

But I got the following error:

`Exception in thread "main" java.lang.NoSuchMethodError: org.apache.spark.scheduler.LiveListenerBus.listeners()Ljava/util/concurrent/CopyOnWriteArrayList; at org.apache.spark.SparkParallelismTracker.safeExecute(SparkParallelismTracker.scala:75) at org.apache.spark.SparkParallelismTracker.execute(SparkParallelismTracker.scala:102) at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainDistributed(XGBoost.scala:350) at ml.dmlc.xgboost4j.scala.spark.XGBoostEstimator.train(XGBoostEstimator.scala:139) at ml.dmlc.xgboost4j.scala.spark.XGBoostEstimator.train(XGBoostEstimator.scala:36) at org.apache.spark.ml.Predictor.fit(Predictor.scala:96) at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainWithDataFrame(XGBoost.scala:199)` 

my spark version is 2.2.0

**Comment by mumuyanyan** [comment]
have you solved the problem?
i have the same problem as you.
Thank you.

**Comment by deniska2010** [comment]
@mumuyanyan 
Unfortunately,no...

**Comment by hcho3** [comment]
Closing this for now. You may want to consider using Spark 2.3. Feel free to re-open if the problem persists.
