### ISSUE TITLE
Accelerated Gradient Boosting

### ISSUE THREAD

**Issue by zachmayer** [dmlc/xgboost#3155]
I just read a cool paper on arxiv and thought it might be of interest to the XGBoost team: https://arxiv.org/pdf/1803.02042.pdf

**Comment by RAMitchell** [comment]
I had been working on something very close to this in this PR: https://github.com/dmlc/xgboost/pull/3018

We should be able to implement this pretty easily through this existing code.

**Comment by hcho3** [comment]
Thanks a lot! I'll go ahead and read the paper.
@RAMitchell  Let me know if you'd need help or input from me.
