### ISSUE TITLE
Can't Build GPU XGBoost with CMake for R in Windows

### ISSUE THREAD

**Issue by JordiPosthumus** [dmlc/xgboost#3159]
Hi Folks

First time caller here, having a hard time getting xgboost with gpu support working for R.
It falls over when I run this line:
_cmake .. -G"Visual Studio 14 2015 Win64" -DUSE_CUDA=ON -DR_LIB=ON_
with the error: 
_-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_C_COMPILER could be found._

### Environment info
Operating System: Windows 10

Compiler: Visual C++ 2015

Package used (python/R/jvm/C++): R

`xgboost` version used: Latest

If installing from source, please provide 

### The commit hash (`git rev-parse HEAD`)

a1b48afa41f888a256ff2645c4153d3d796bfb9c

### Logs will be helpful (If logs are large, please upload as attachment).

Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler:  
Build flags: 
Id flags:  

The output was:
1
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 3/9/2018 11:03:08 PM.
Project "C:\Users\jordi\Downloads\xgboost\build\CMakeFiles\3.11.0-rc2\CompilerIdC\CompilerIdC.vcxproj" on node 1 (default targets).
PrepareForBuild:
  Creating directory "Debug\".
  Creating directory "Debug\CompilerIdC.tlog\".
InitializeBuildStatus:
  Creating "Debug\CompilerIdC.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64\CL.exe /c /nologo /W0 /WX- /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\" /Fd"Debug\vc140.pdb" /Gd /TC /errorReport:queue CMakeCCompilerId.c
  CMakeCCompilerId.c
Link:
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64\link.exe /ERRORREPORT:QUEUE /OUT:".\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\CompilerIdC.lib" /MACHINE:X64 Debug\CMakeCCompilerId.obj
LINK : fatal error LNK1158: cannot run 'rc.exe' [C:\Users\jordi\Downloads\xgboost\build\CMakeFiles\3.11.0-rc2\CompilerIdC\CompilerIdC.vcxproj]
Done Building Project "C:\Users\jordi\Downloads\xgboost\build\CMakeFiles\3.11.0-rc2\CompilerIdC\CompilerIdC.vcxproj" (default targets) -- FAILED.

Build FAILED.

"C:\Users\jordi\Downloads\xgboost\build\CMakeFiles\3.11.0-rc2\CompilerIdC\CompilerIdC.vcxproj" (default target) (1) ->
(Link target) -> 
  LINK : fatal error LNK1158: cannot run 'rc.exe' [C:\Users\jordi\Downloads\xgboost\build\CMakeFiles\3.11.0-rc2\CompilerIdC\CompilerIdC.vcxproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.74

### The R `sessionInfo()`

R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

### The command to install `xgboost` if you are not installing from source
git clone --recursive https://github.com/dmlc/xgboostcd xgboost
git submodule init
git submodule update
cd xgboost

### Steps to reproduce

mkdir build
cd build
cmake .. -G"Visual Studio 14 2015 Win64" -DUSE_CUDA=ON -DR_LIB=ON

### this gives the error:

-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_C_COMPILER could be found.

CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_CXX_COMPILER could be found.

-- Configuring incomplete, errors occurred!
See also "C:/Users/jordi/Downloads/xgboost/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/jordi/Downloads/xgboost/build/CMakeFiles/CMakeError.log".

### What have you tried?

Everything I could find on here and Stackoverflow.

Thanks in advance for any and all feedback, I'm a noob here.

**Comment by khotilov** [comment]
Are you using VS2015 x64 Native Tools command prompt when running cmake?

**Comment by JordiPosthumus** [comment]
Hi Khotilov

I’m running that from the windows prompt, pulled up by CMD. 

Should I be using the VS2015 x64 Native Tools command prompt? Apologies, I’ve never heard of that before. How would I invoke it?

**Comment by JordiPosthumus** [comment]
I'm now running everything in the native tools prompt VS2015 x64.

And when executing:
 
_install.packages('.', repos = NULL, type="source")_

I get:

...
cp -r ../../include .
cp -r ../../amalgamation .
c:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.3/include" -DNDEBUG -I.//include -I.//dmlc-core/include -I.//rabit/include -I./ -DXGBOOST_STRICT_R_MODE=1 -DDMLC_LOG_BEFORE_THROW=0 -DDMLC_ENABLE_STD_THREAD=0 -DDMLC_DISABLE_STDIN=1 -DDMLC_LOG_CUSTOMIZE=1 -DXGBOOST_CUSTOMIZE_LOGGER=1 -DRABIT_CUSTOMIZE_MSG_ -DRABIT_STRICT_CXX98_ -DDMLC_CXX11_THREAD_LOCAL=0      -fopenmp -pthread   -O2 -Wall  -mtune=generic -c xgboost_R.cc -o xgboost_R.o
c:/Rtools/mingw_32/bin/g++: not found
make: *** [xgboost_R.o] Error 127
...

Am working through this.

**Comment by JordiPosthumus** [comment]
OK, solved the g++ not found issue by reinstalling Rtools to the folder where it seems to have been expected. 

Still working through it.

**Comment by JordiPosthumus** [comment]
Thanks for the help so far guys, but I'm back where I started. Running: 

cmake .. -G"Visual Studio 14 2015 Win64" -DUSE_CUDA=ON -DR_LIB=ON

In either the windows prompt or the VS2015 Native Tools Command Prompt both still give the exact same error:

-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_C_COMPILER could be found.

CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_CXX_COMPILER could be found.

**Comment by khotilov** [comment]
What does running `cl` from the VS2015 Native Tools Command Prompt show?
This SO might be relevant: https://stackoverflow.com/questions/45228238/qt-5-8-msvc-2015-compile-error
I would just uninstall everything related to Visual Studio and install it again afresh.

**Comment by JordiPosthumus** [comment]
Running CL in the VS2015 native prompt gives this:

Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

usage: cl [ option... ] filename... [ /link linkoption... ]

**Comment by khotilov** [comment]
Could you also run `where rc` in the same terminal? rc.exe is a part of windows SDK, and based on the error, it might be not correctly installed.

**Comment by JordiPosthumus** [comment]
OK so I ran: where rc and got:
_INFO: Could not find files for the given pattern(s)._

Sounds like we are zooming in on the issue !

**Comment by JordiPosthumus** [comment]
Now running: 
_cmake .. -G"Visual Studio 14 2015 Win64" -DUSE_CUDA=ON -DR_LIB=ON_

Returns:

-- The C compiler identification is MSVC 19.0.24215.1
-- The CXX compiler identification is MSVC 19.0.24215.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenMP_C: -openmp (found version "2.0")
-- Found OpenMP_CXX: -openmp (found version "2.0")
-- Found OpenMP: TRUE (found version "2.0")
-- Found PythonInterp: C:/Program Files (x86)/Microsoft Visual Studio/Shared/Python36_64/python.exe (found version "3.6.3")
-- Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0 (found suitable version "8.0", minimum required is "8.0")
-- LIBR_HOME [/registry]
-- LIBR_EXECUTABLE [/registry/bin/x64/R.exe]
-- LIBR_INCLUDE_DIRS [/registry/include]
-- LIBR_LIB_DIR [/registry/bin/x64]
-- LIBR_CORE_LIBRARY []
CMake Error at cmake/modules/FindLibR.cmake:44 (message):
  LIBR_LIB_DIR was not set!
Call Stack (most recent call first):
  cmake/modules/FindLibR.cmake:154 (create_rlib_for_msvc)
  CMakeLists.txt:165 (find_package)

-- Configuring incomplete, errors occurred!
See also "C:/Users/jordi/Downloads/xgboost/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/jordi/Downloads/xgboost/build/CMakeFiles/CMakeError.log".

**Comment by JordiPosthumus** [comment]
Khotilov, I found your response to this issue in another thread:
https://github.com/dmlc/xgboost/issues/3081

_The root cause seems to be that the published 3.4.3 R version has issues handling spaces in the argument of -e. Either removing the space or using a different R version, e.g., 3.4.3patched, makes it work right:_

But I'm not entirely sure what "removing the space" means 'coz I don't know which space it refers to.  I would prefer to do that than mess with my R install at the moment. Any tips ?

**Comment by JordiPosthumus** [comment]
I'm getting the same _LIBR_LIB_DIR was not set!_ error with R3.4.2

[CMakeOutput.log](https://github.com/dmlc/xgboost/files/1813079/CMakeOutput.log)

**Comment by khotilov** [comment]
Did you try adding LIBR_EXECUTABLE as a parameter to cmake?
`-DLIBR_EXECUTABLE="C:/Program Files/R/R-3.4.3/bin/x64/R.exe"`

**Comment by JordiPosthumus** [comment]
Thanks Khotilov, that seems to have helped.  Running:
_cmake .. -G"Visual Studio 14 2015 Win64" -DUSE_CUDA=ON -DR_LIB=ON_ 

Gives:
-DLIBR_EXECUTABLE="C:/Program Files/R/R-3.4.3/bin/x64/R.exe"
-- Found OpenMP_C: -openmp
-- Found OpenMP_CXX: -openmp
-- Found OpenMP: TRUE
-- LIBR_HOME [C:/Program Files/R/R-3.4.3]
-- LIBR_EXECUTABLE [C:/Program Files/R/R-3.4.3/bin/x64/R.exe]
-- LIBR_INCLUDE_DIRS [C:/Program Files/R/R-3.4.3/include]
-- LIBR_LIB_DIR [C:/Program Files/R/R-3.4.3/bin/x64]
-- LIBR_CORE_LIBRARY []
 * [C:/Program Files/R/R-3.4.3/bin/x64/R.dll] Found PE+ image
-- Found LibR: C:/Program Files/R/R-3.4.3
-- Found R: C:/Program Files/R/R-3.4.3/bin/x64/R.exe
-- LIBR_CORE_LIBRARY C:/Users/jordi/Downloads/xgboost/build/R.lib
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/jordi/Downloads/xgboost/build

Now I must confess that I have no idea how to load the R package.  Tried a few things, and this seemed to come the closest: 

1. Copied the contents of R-package to a folder called new xgboost.
2. Zipped that new xgboost folder.
3. Then used RStudio to install that new xgboost.zip, and it appears to install correctly. At least, it gave no error.

But when I type library(xgboost) it says:
_Error in library(xgboost) : ‘xgboost’ is not a valid installed package_

Thanks for all your help and apologies for being a n00b.  Hopefully this thread helps somebody else !

**Comment by hcho3** [comment]
Closing for the lack of activity in last 90 days. Future Q&A's and discussions should be re-directed to https://discuss.xgboost.ai/.
