### ISSUE TITLE
Question regarding RegTree::FVec::Fill

### ISSUE THREAD

**Issue by flashhack** [dmlc/xgboost#3160]
`xgboost` version used: v0.7 (2017.12.30)

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`) 89371340154a774c4226c4432a642bb1da446d24

In tree_mode.h
```
inline void RegTree::FVec::Fill(const RowBatch::Inst& inst) {
  for (bst_uint i = 0; i < inst.length; ++i) {
    if (inst[i].index >= data.size()) continue;
    data[inst[i].index].fvalue = inst[i].fvalue;
  }
}
```

When setting the fvalue of data in FVec, should we also set the flag(indicating missing value) to 0? Because both **Init** and **Drop** set the flag to -1. And I didn't see other code set the flag to non -1. 

One use case is in CPUPredictor::PredValue
```
    p_feats->Fill(inst);
    for (size_t i = tree_begin; i < tree_end; ++i) {
      if (tree_info[i] == bst_group) {
        int tid = trees[i]->GetLeafIndex(*p_feats, root_index);
        psum += (*trees[i])[tid].leaf_value();
      }
    }
    p_feats->Drop(inst);
```

Seems all flags in p_feats will be -1.

Did I miss something?

**Comment by khotilov** [comment]
Missing values are literally "missing" (sparse elements) in those sparse vectors.

**Comment by flashhack** [comment]
Indeed, for features that do not exist, default missing is the correct behavior. But the real question is, for the non missing values set in the Fill function, shall we also set the flag to non missing?

**Comment by khotilov** [comment]
`FVec::Entry` is a union, so setting the fvalue is the same as setting the flag. The assumption is that we would never encounter the float value with the same representation as integer -1.

**Comment by flashhack** [comment]
I see, that makes sense given the assumption. Thanks for the explanation!
