### ISSUE TITLE
Compiling Xgboost 0.7 on Ubuntu Linux with statical linking

### ISSUE THREAD

**Issue by Horsmann** [dmlc/xgboost#3163]
Hi,

I am trying to compile xgboost (0.7) on an Ubuntu linux system with `statical` linking. I need statical linking because I can't be sure that all dynamic libraries are necessarily available on the target system where I want to use xgboost. 

When compiling with dynamical linking the binary works - so no problem here. Just with statical linking I get a `segmentation fold` when starting the binary. Here are my changes to the config.mk and Makefile:

config.mk
```
export CC = gcc
export CXX = g++
# export MPICXX = mpicxx

# the additional link flags you want to add
ADD_LDFLAGS = -static
```

Makefile
```
ifeq ($(UNAME), Windows)
        XGBOOST_DYLIB = lib/xgboost.dll
        JAVAINCFLAGS += -I${JAVA_HOME}/include/win32
else
ifeq ($(UNAME), Darwin)
        XGBOOST_DYLIB = lib/libxgboost.dylib
        CFLAGS += -fPIC
else
        XGBOOST_DYLIB = lib/libxgboost.a
#       XGBOOST_DYLIB = lib/libxgboost.so        # use the .a file for static linking
        CFLAGS += -fPIC
endif
endif
```

When running `make clean`, `make -j 4` I get the following `warnings` which do not explain why the binary does not work.
```
/usr/lib/gcc/x86_64-linux-gnu/5/libgomp.a(target.o): In Funktion `gomp_target_init':
(.text+0xba): Warnung: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
rabit/lib/librabit.a(allreduce_base.o): In Funktion `rabit::engine::AllreduceBase::ConnectTracker() const':
allreduce_base.cc:(.text+0xbd2): Warnung: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
```

Does anyone has an idea why the compiled binary is not working? Dynamic linking works just fine. I managed to compile the binary for OSX with statical linking it just does not work on Linux. 
I am thankful for suggestions :)

**Comment by hcho3** [comment]
I think `-static` will try to statically include standard C/C++ library (`libc`/`libstdc++`). Is this what you want? Most likely, you should remove `static` from `config.mk` and run `make all`. The executable `xgboost` already embeds `libdmlc.a`, `libxgboost.a`, and `librabit.a`.
