### ISSUE TITLE
Discussion: Custom objective function (penalty matrix)

### ISSUE THREAD

**Issue by BU-1** [dmlc/xgboost#3165]
What is the best way to incorporate a cost/loss/penalty matrix into the objective function in `xgboost`? I am working on a multi-class classification problem in R where the cost of a false-positive is much higher than a false-negative. Other packages such as `rpart` and `C5.0` allow you to input a cost matrix but I can't figure out how this works with `xgboost`. Open to any other suggestions as well!

Thanks!

**Comment by tqchen** [comment]
general discussions are now encouraged at https://discuss.xgboost.ai/.
