### ISSUE TITLE
Memory leak when an error occurs

### ISSUE THREAD

**Issue by horgh** [dmlc/xgboost#3166]
## Environment info
Operating System: Ubuntu Trusty (in Docker with Ubuntu Artful host)

Compiler: gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.4) 

Package used (python/R/jvm/C++): C

`xgboost` version used: Git master at d5f1b74ef5b33ebb64863f66fd976d6c6efe0667

## Steps to reproduce

1. Cause any kind of error when using the C API
2. Run program under valgrind

Sample program that demonstrates the issue:

```c
#define _POSIX_C_SOURCE 200809L

#include <stdio.h>
#include <xgboost/c_api.h>

int main(void)
{
    char const * const fname = "/tmp/does-not-exist";
    int const silent = 0;
    DMatrixHandle dmh = {0};
    if (XGDMatrixCreateFromFile(fname, silent, &dmh) != 0) {
        fprintf(stderr, "XGDMatrixCreateFromFile(): %s\n", XGBGetLastError());
        return 1;
    }

    if (XGDMatrixFree(dmh) != 0) {
        fprintf(stderr, "XGDMatrixFree(): %s\n", XGBGetLastError());
        return 1;
    }

    return 0;
}
```

## What have you tried?

1. Nothing other than causing the issue and tracking down the source

## Valgrind output
```
==50== 1,238 bytes in 1 blocks are definitely lost in loss record 1 of 1
==50==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==50==    by 0x55F4C34: backtrace_symbols (backtracesyms.c:71)
==50==    by 0x4EAE821: dmlc::LogMessageFatal::~LogMessageFatal() (logging.h:288)
==50==    by 0x5064C12: dmlc::io::InputSplitBase::InitInputFileInfo(std::string const&) (in /will/code/xgboost/lib/libxgboost.so)
==50==    by 0x5065B3D: dmlc::io::InputSplitBase::Init(dmlc::io::FileSystem*, char const*, unsigned long) (in /will/code/xgboost/lib/libxgboost.so)
==50==    by 0x503D2D5: dmlc::InputSplit::Create(char const*, unsigned int, unsigned int, char const*) (in /will/code/xgboost/lib/libxgboost.so)
==50==    by 0x50501D8: dmlc::Parser<unsigned int>* dmlc::data::CreateLibSVMParser<unsigned int>(std::string const&, std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&, unsigned int, unsigned int) (in /will/code/xgboost/lib/libxgboost.so)
==50==    by 0x504AADF: dmlc::Parser<unsigned int>* dmlc::data::CreateParser_<unsigned int>(char const*, unsigned int, unsigned int, char const*) (in /will/code/xgboost/lib/libxgboost.so)
==50==    by 0x4EEF793: xgboost::DMatrix::Load(std::string const&, bool, bool, std::string const&) (data.cc:207)
==50==    by 0x4EC6B5A: XGDMatrixCreateFromFile (c_api.cc:210)
==50==    by 0x400820: main (main.c:11)
```

## Source of the leak
In `LogMessageFatal::~LogMessageFatal()` in `dmcl-core/include/dmlc/logging.h`, `backtrace_symbols()` is called. Its memory is not freed.

I realize this is in a submodule. As far as I can tell, this was fixed in dmlc/dmlc-core@c553350aafc701a7a501d40f3445e9b5657812ad, so we'd need to update the submodule to that.

However, this problem also exists in dmlc/rabit's included version: https://github.com/dmlc/rabit/blob/master/include/dmlc/logging.h (which we also have as a submodule).

Thank you!

**Comment by tqchen** [comment]
The submodule is updated, the rabit should be built with the dmlc-core version in the xgboost repo
