### ISSUE TITLE
address 0xb0, cause 'memory not mapped' in R

### ISSUE THREAD

**Issue by YaohuiZeng** [dmlc/xgboost#317]
I got the following error when using 'xgb.train' in R. Would anyone also happen to have this error? The 'xgb.myTrain' is the function I wrote to customize 'xgb.train', basically passing parameter settings, running 'xgb.train', saving stdout information about training and test errors into log file.

 *** caught segfault ***
address 0xb0, cause 'memory not mapped'

Traceback:
 1: .Call("XGBoosterCreate_R", cachelist, PACKAGE = "xgboost")
 2: xgb.Booster(params, append(watchlist, dtrain))
 3: xgb.train(params = para, data = dtr, nround = nround, watchlist = watchlist,     verbose = 1)
 4: xgb.myTrain(para.comb, nround = 10, logfilename = logfile)

**Comment by tqchen** [comment]
Make sure you install the latest version from the github, if you still find problem, please provide a snippet of code that reproduces the error.

**Comment by YaohuiZeng** [comment]
I figured out the issue. Interestingly, that issue occurs only if I load a RData file which contains the training and test sets (preprocessed as xgb.DMatrix and saved in RData file before training the model). However, if I don't load the data sets from RData file but just do the preprocessing before model training in the normal way, then the issue would not show up. I am not sure why that's the case. Anyway.Thanks for reply, @tqchen.

**Comment by hetong007** [comment]
@YaohuiZeng currently an `xgb.DMatrix` object is not an R object, it is just a pointer. So what in your RData file is just a piece of memory address, but not the data itself. To correctly save it, you can use the `xgb.DMatrix.save` function: https://github.com/dmlc/xgboost/blob/master/R-package/R/xgb.DMatrix.save.R, and use `xgb.DMatrix` to load it: https://github.com/dmlc/xgboost/blob/master/R-package/R/xgb.DMatrix.R

**Comment by YaohuiZeng** [comment]
@hetong007, ah, I see. Thank you very much for pointing out it. That's very helpful.

**Comment by ck37** [comment]
I'm getting this error  as well, with this output:

```r
 *** caught segfault ***
address (nil), cause 'memory not mapped'

Traceback:
 1: .Call("XGBoosterUpdateOneIter_R", booster, as.integer(iter),     dtrain, PAC
KAGE = "xgboost")
 2: xgb.iter.update(bst$handle, dtrain, i - 1, obj)
 3: xgb.train(params, dtrain, nrounds, watchlist, verbose = verbose,     print.every.n = print.every.n, early.stop.round = early.stop.round,     maximize = maximize, save_period = save_period, save_name = save_name)
 4: xgboost(data = xgmat, objective = "reg:linear", nround = ntrees,     max_depth = max_depth, minchildweight = minobspernode, eta = shrinkage,     early.stop.round = early.stop.round, verbose = 0, nthread = 1)
 5: SL.xgboost(..., ntrees = ntrees, max_depth = max_depth, shrinkage = shrinkage,     minobspernode = minobspernode)
 6: SL.xgb.13(Y = c(117.380323121518, 122.846225328539, 117.854685049902, 124.972310550021, 114.351691600038, 98.7041636072618, 117.299910105567, 126.272386925369, 97.5343104716037, 98.6629235892849, 124.455353351043, 113.620720324029, 116.357786651898, 102.068510420198, 116.705249504941, 121.407949885206,
etc.
```
Running it again I got a similar error (" address 0x10, cause 'memory not mapped' ") and debug output.

I'm using XGBoost in parallel (across 16 cores) as part of a SuperLearner, with this creation code:
```r
SL.xgboost = function(Y, X, newX, family, obsWeights, id, ntrees = 1000,
                      max_depth=4, shrinkage=0.1, minobspernode=10,
                      early.stop.round=NULL, ...) {
  # TODO: Convert to an xgboost compatible data matrix, using the sample weights.
  #xgmat = xgb.DMatrix(as.matrix(X), label=Y, weight = obsWeights)
  # We are not using sample weights currently:
  xgmat = xgb.DMatrix(as.matrix(X), label=Y)
  
  # TODO: support early stopping, which requires a watchlist. See ?xgb.train
  
  if (family$family == "gaussian") {
    # We restrict xgboost to 1 thread so that SL can control parallelization.
    model = xgboost(data=xgmat, objective="reg:linear", nround = ntrees, max_depth = max_depth, minchildweight = minobspernode, eta = shrinkage, early.stop.round=early.stop.round, verbose=0, nthread = 1)
  }

  pred = predict(model, newdata=data.matrix(newX))
  fit = vector("list", length = 0)
  class(fit) = c("SL.xgboost")
  out = list(pred = pred, fit = fit)
  return(out)
}
```
xgb.13 is configured as: ntrees = 1000, max_depth=2, shrinkage = 0.2, minobspernode=10. I have also gotten the error for xgb.14.

Any ideas? I am not don't any substantial loading or unloading of the data.  Maybe it's just an out of memory error? My system has 256GB of ram though, so it shouldn't run out too quickly, but with 16 parallel processes maybe it is.
