### ISSUE TITLE
Please check my implementations

### ISSUE THREAD

**Issue by KOLANICH** [dmlc/xgboost#3170]
Hello. I have created a compiler translating xgboost models into python if-else code: https://github.com/KOLANICH/pyxgboost

To do it I have created a [Kaitai Struct description of the file format](https://github.com/KOLANICH/kaitai_struct_formats/tree/xgboost/scientific/data_science/dmlc/xgboost) (I wanna you using and developing it it instead of a custom manually coded parser because it'd be easier for everyone: we will have the parsers for all the languages supported by Kaitai Struct automatically and the ksy description is the docs itself, BTW Rust is also supported) used and generated [parsers](https://github.com/KOLANICH/pyxgboost/tree/master/pyxgboost/kaitai) from it.

Then I [walk the parsed tree and create python AST](https://github.com/KOLANICH/pyxgboost/blob/master/pyxgboost/__init__.py#L9L48) which is then [transformed into source](https://github.com/KOLANICH/pyxgboost/blob/master/pyxgboost/compiler.py#L20L22).

I have dug into the code enough to understand file format but since I'm not very familiar with xgboost source code at the moment I started dealing with inference I found it is easier to ask than to dig myself.

I have not implemented because it is not very clear for me (not very easily found with searching the source code for variable names):
* multiple roots in trees
* multiclass classification
* usage of additional info for trees
* influences of different boosters on inference code

Also the AST is built not according the xgboost sources but according to my guesses on that how it works.

Could you check my code and clarify the mechanics at high level, please?

**Comment by hcho3** [comment]
> I wanna you using and developing it it instead of a custom manually coded parser because it'd be easier for everyone: we will have the parsers for all the languages supported by Kaitai Struct automatically and the ksy description is the docs itself.

This is an interesting suggestion. Why don't you file a separate issue to adopt Kaitai Struct in XGBoost? 

As for compiling XGBoost models into if-else code, you may want to take a look at [dmlc/treelite](https://github.com/dmlc/treelite).
