### ISSUE TITLE
Documentation not clear

### ISSUE THREAD

**Issue by qichaolan** [dmlc/xgboost#3175]
V0.7 has a new feature as below:
* Ability to adjust tree model's statistics to a new dataset without changing tree structures.

But I can't find any documentation to introduce how to use it, can you please point me for that?

**Comment by hcho3** [comment]
This line was added by PR #2295. I think it was introduced as a necessary component of the PR. @khotilov could you explain how this feature is used in the feature contribution prediction?

**Comment by qichaolan** [comment]
Thanks @hcho3, my understanding is that this feature could help to improve model's performance without re-growing of a new forest/tree, because it says 'without changing tree structures', so my thought is to feed a new dataset to adjust model's prediction(the score on each leaf node), correct?

**Comment by khotilov** [comment]
It was introduced in here: #1670 
Also see https://github.com/dmlc/xgboost/issues/2970#issuecomment-354684604 for some more explanations.
I agree it was not well documented.

**Comment by qichaolan** [comment]
@khotilov thanks a lot, this is an really cool feature.
