### ISSUE TITLE
Use xgboost to score for single row

### ISSUE THREAD

**Issue by zer0n** [dmlc/xgboost#318]
For scoring in production, the predictor should operate on a data row, not a matrix (like in https://github.com/dmlc/xgboost/blob/master/wrapper/xgboost.py#L970).

**Comment by tqchen** [comment]
This function exists in cxx side, but was not yet exposed. I agree that it is a good idea to add it.

**Comment by tqchen** [comment]
For now, converting a single row into matrix was an option to use the prediction in your case.

**Comment by zer0n** [comment]
I've tried the above approach and the speed is horrendous. 

This
```
cls.predict(X)
```

is about 400x faster than

```
[cls.predict(x) for x in X]
```

where `X` is a numpy array.

I can try to add this functionality to the Python code. Can you give me a pointer to the function in the cxx?  Any other pointers to help me understand the code quickly would be nice.

**Comment by tqchen** [comment]
It is here https://github.com/dmlc/xgboost/blob/master/src/learner/learner-inl.hpp#L362
You may want to modify https://github.com/dmlc/xgboost/blob/master/wrapper/xgboost_wrapper.cpp to add this function. Checkout how original predict is implemented

**Comment by zer0n** [comment]
A silly question, does xgboost only predict on sparse instances?

When a numpy array is passed to the wrapper's predict function, does the function convert the array to a CSR matrix?

**Comment by tqchen** [comment]
Yes, there should not me that much overhead on this though. Dense matrix is also possible(actually easier), but this will mean change of the gbm interface
