### ISSUE TITLE
[jvm-packages] xgboostj-spark fails with error "value 0 for Parameter num_class should be greater equal to 1"

### ISSUE THREAD

**Issue by lev112** [dmlc/xgboost#3186]
## Environment info
Operating System: CentOs 7

Compiler: `gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16)`

Package used (python/R/jvm/C++): jvm - spark

`xgboost` version used: `0.7`

If installing from source, please provide 

1. The commit hash: `v0.7`
2. Logs:

> ml.dmlc.xgboost4j.java.XGBoostError: value 0 for Parameter num_class should be greater equal to 1
> 	at ml.dmlc.xgboost4j.java.XGBoostJNI.checkCall(XGBoostJNI.java:48)
> 	at ml.dmlc.xgboost4j.java.Booster.update(Booster.java:124)
> 	at ml.dmlc.xgboost4j.java.XGBoost.train(XGBoost.java:182)
> 	at ml.dmlc.xgboost4j.scala.XGBoost$.train(XGBoost.scala:64)
> 	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$buildDistributedBoosters$1.apply(XGBoost.scala:141)
> 	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$buildDistributedBoosters$1.apply(XGBoost.scala:115)
> 	at org.apache.spark.rdd.ZippedPartitionsRDD2.compute(ZippedPartitionsRDD.scala:89)
> 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
> 	at org.apache.spark.rdd.RDD$$anonfun$8.apply(RDD.scala:336)
> 	at org.apache.spark.rdd.RDD$$anonfun$8.apply(RDD.scala:334)
> 	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1038)
> 	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1029)
> 	at org.apache.spark.storage.BlockManager.doPut(BlockManager.scala:969)
> 	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1029)
> 	at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:760)
> 	at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:334)
> 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:285)
> 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
> 	at org.apache.spark.scheduler.Task.run(Task.scala:108)
> 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)

## Steps to reproduce

1.  use those params:
```
Map(alpha -> 1.0,
 colsample_bylevel -> 1.0,
 silent -> 1,
 subsample -> 0.7,
 lambda -> 0.0,
 max_depth -> 5,
 num_class -> 2,
 objective -> multi:softprob,
 eval_metric -> logloss,
 num_round -> 100,
 eta -> 0.3,
 colsample_bytree -> 0.9,
 booster -> gbtree,
 gamma -> 0.3,
 ntreelimit -> 1000)
```
to train `XGBoostEstimator`

----
I suspect that the problem is from this line:
https://github.com/dmlc/xgboost/blob/v0.7/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostEstimator.scala#L104

`num_class` is removed there from the params that are passed down to the model

**EDIT**: updated to the parameter map that cause the issue

**Comment by lev112** [comment]
@CodingCat can you please take a look at this issue?
I think it might be related to your PR https://github.com/dmlc/xgboost/pull/2068

**Comment by CodingCat** [comment]
cannot reproduce it in the latest version
