### ISSUE TITLE
Question about version numbers / tags.

### ISSUE THREAD

**Issue by mingwandroid** [dmlc/xgboost#3189]
I built XGBoost (libxgboost, py-xgboost and r-xgboost) for the Anaconda Distribution recently.

I made a bit of a mistake with the versioning I think because I released it as version 0.7, whereas the one I built a year ago was version 0.60, numerically 7 is < 60 so our solver is preferring 0.60.

What is the *correct* version number here? I see differences between 'series' and 'tags' over at https://github.com/dmlc/xgboost/releases

Is the 0.7 versioned release a mistake that I should correct by changing it to 0.70 or should 0.60 really have been 0.6.0?

**Comment by hcho3** [comment]
Hmm, apparently, some conventions (notably [this](https://setuptools.readthedocs.io/en/latest/setuptools.html#specifying-your-project-s-version)) treats `0.7` as older than `0.60`.
This is an oversight of my part; it should have been `0.70` to satisfy those conventions.

Would releasing a minor release `0.71` fix the issue? I don't think rewriting the repo history is a good idea, so it is infeasible to rename the `0.7` tag .

**Comment by mingwandroid** [comment]
Sure! 0.71 would be just great.

**Comment by hcho3** [comment]
I've filed PRs for release 0.71: #3199, #3200

**Comment by mingwandroid** [comment]
Thank you.
