### ISSUE TITLE
Documentation Does Not Explain What Predictions Represent

### ISSUE THREAD

**Issue by DarioS** [dmlc/xgboost#3193]
The R package documentation has many ambiguities. For example, `?predict.xgb.Booster` shows a help document which doesn't even explain what the numbers generated are, only how many of them are calculated ("... a vector of length `nrows(newdata)`"). Are they probabilities? Probabilities of what specifically? I'd expect such basic information to be in the documentation. Unexpectedly, the first example in the Examples section returns one of only six distinct values, although it is making predictions for 1611 samples. Why is there not more variety?

```
> table(round(pred, 3))
0.011 0.052 0.286 0.709 0.924 
   34   694    98    19   766
```

There's also no explanation of what valid values passed as `...` are, which is used differently for both `predict` and `predict.xgb.booster`, implied by the Usage section.

**Comment by hcho3** [comment]
>The R package documentation has many ambiguities

Would you be willing to provide a suitable clarification? You can file a pull request, or if that's not feasible, post a clarification here and I'll file a PR on your behalf.

**Comment by hcho3** [comment]
Closing for the lack of activity in last 90 days. Feel free to reopen if you have concrete suggestions.
