### ISSUE TITLE
[jvm-package] xgboost train fail

### ISSUE THREAD

**Issue by nedved1990** [dmlc/xgboost#3196]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System: centos 7

Compiler: 4.8.6

Package used (python/R/jvm/C++):

`xgboost` version used: 0.7

jdk used: 1.7

I occur the xgboost error when I train a data set with 8G*100dimention. My nWorkers is 8.
Here is my log:
[hs_err_pid57621.log](https://github.com/dmlc/xgboost/files/1841113/hs_err_pid57621.log)

Thank you for your help!

**Comment by nedved1990** [comment]
@CodingCat

**Comment by CodingCat** [comment]
it's more like a native layer compatibility issue, are you using different compiler in the machine built the library and the actual runtime machine
