### ISSUE TITLE
ubuntu install make -j4 error /bin/sh: 1: g++: Permission denied 

### ISSUE THREAD

**Issue by fstien** [dmlc/xgboost#3197]
Hi, I'm on ubuntu 16.04 trying to build xgboost. After running 'make -j4' I get the following error message: 

Makefile:31: MAKE [make] - checked OK
g++ -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/logging.o src/logging.cc >build/logging.d
g++ -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/learner.o src/learner.cc >build/learner.d
g++ -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/predictor/predictor.o src/predictor/predictor.cc >build/predictor/predictor.d
g++ -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/predictor/cpu_predictor.o src/predictor/cpu_predictor.cc >build/predictor/cpu_predictor.d
/bin/sh: 1: g++: Permission denied
/bin/sh: 1: g++: Permission denied
Makefile:141: recipe for target 'build/logging.o' failed
make: *** [build/logging.o] Error 127
make: *** Waiting for unfinished jobs....
Makefile:141: recipe for target 'build/learner.o' failed
make: *** [build/learner.o] Error 127
/bin/sh: 1: g++: Permission denied
/bin/sh: 1: g++: Permission denied
Makefile:141: recipe for target 'build/predictor/cpu_predictor.o' failed
make: *** [build/predictor/cpu_predictor.o] Error 127
Makefile:141: recipe for target 'build/predictor/predictor.o' failed
make: *** [build/predictor/predictor.o] Error 127

Any ideas ? thanks.

**Comment by hcho3** [comment]
It looks like you have a problem with file permissions. Make sure you have write access to the directory.
