### ISSUE TITLE
Failure to build xgboost\build\gpuxgboost.vcxproj on Windows 10

### ISSUE THREAD

**Issue by pgyrya** [dmlc/xgboost#3198]
## Environment info
Operating System: Windows 10

Compiler: Cmake with Microsoft Visual Studio 15, 2017 compiler choice; 

Package used: Python 3.6.4 (ultimately wish to use it with GPU support, not able to get past build)

`xgboost` version used: latest master branch as of Mar 24, 2018

## Problem
I am installing xgboost with GPU support on Windows machine with NVIDIA GeForce 1080 Ti graphics card.

The following command compiles:
`C:\Users\pavel\Downloads\Git\xgboost\build>cmake .. -G"Visual Studio 15 2017 Win64" -DUSE_CUDA=ON`

The next command fails miserably, see logs below:
`cmake --build . --target xgboost --config Release`

I have tried referring to various versions of Cuda (8.0, 9.0,9.1) using the below command, however the above error persists. 

`Set CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0` 

Am I the only one with this problem?
Any ideas how I can solve it effectively?

Thank  you,
P
## Relevant  Logs:

```
Project "C:\Users\pavel\Downloads\Git\xgboost\build\xgboost.vcxproj" (1) is building "C:\Users\pavel\Downloads\Git\xgboost\build\gpuxgboost.vcxproj" (4) on node 1 (default targets).
PrepareForBuild:
  Creating directory "gpuxgboost.dir\Release\".
  Creating directory "C:\Users\pavel\Downloads\Git\xgboost\build\Release\".
  Creating directory "gpuxgboost.dir\Release\gpuxgboost.tlog\".
InitializeBuildStatus:
  Creating "gpuxgboost.dir\Release\gpuxgboost.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
ComputeCustomBuildOutput:
  Creating directory "C:\Users\pavel\Downloads\Git\xgboost\build\CMakeFiles\gpuxgboost.dir\src\common\Release\".
  Creating directory "C:\Users\pavel\Downloads\Git\xgboost\build\CMakeFiles\gpuxgboost.dir\src\objective\Release\".
  Creating directory "C:\Users\pavel\Downloads\Git\xgboost\build\CMakeFiles\gpuxgboost.dir\src\predictor\Release\".
  Creating directory "C:\Users\pavel\Downloads\Git\xgboost\build\CMakeFiles\gpuxgboost.dir\src\tree\Release\".
CustomBuild:
  Building NVCC (Device) object CMakeFiles/gpuxgboost.dir/src/common/Release/gpuxgboost_generated_host_device_vector.cu.obj
  Failed to run C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/bin (The system cannot find the file specified.

  ).
  CMake Error at gpuxgboost_generated_host_device_vector.cu.obj.Release.cmake:219 (message):
    Error generating
    C:/Users/pavel/Downloads/Git/xgboost/build/CMakeFiles/gpuxgboost.dir/src/common/Release/gpuxgboost_generated_host_device_vector.cu.obj


C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1. [C:\Users\pavel\Downloads\Git\xgboost\build\gp
uxgboost.vcxproj]
Done Building Project "C:\Users\pavel\Downloads\Git\xgboost\build\gpuxgboost.vcxproj" (default targets) -- FAILED.
```
![image](https://user-images.githubusercontent.com/31545921/37861345-20c1d6c0-2f0e-11e8-9b9a-91c9359bb744.png)

**Comment by pgyrya** [comment]
Note I also found an article mentioning supported Visual Studio compilers [here](), and tried switching to different command prompts:

a) Native x64

b) Cross-tools x86_64

The primary error message changed, yet I still can't compile:
```
ComputeCustomBuildOutput:
  Creating directory "C:\Users\pavel\Downloads\Git\xgboost\build\CMakeFiles\gpuxgboost.dir\src\common\Release\".
  Creating directory "C:\Users\pavel\Downloads\Git\xgboost\build\CMakeFiles\gpuxgboost.dir\src\objective\Release\".
  Creating directory "C:\Users\pavel\Downloads\Git\xgboost\build\CMakeFiles\gpuxgboost.dir\src\predictor\Release\".
  Creating directory "C:\Users\pavel\Downloads\Git\xgboost\build\CMakeFiles\gpuxgboost.dir\src\tree\Release\".
CustomBuild:
  Building NVCC (Device) object CMakeFiles/gpuxgboost.dir/src/common/Release/gpuxgboost_generated_host_device_vector.cu.obj
  CMake Error at gpuxgboost_generated_host_device_vector.cu.obj.Release.cmake:219 (message):
    Error generating
    C:/Users/pavel/Downloads/Git/xgboost/build/CMakeFiles/gpuxgboost.dir/src/common/Release/gpuxgboost_generated_host_device_vector.cu.obj


C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1. [C:\Users\pavel\Downloads\Git\xgboost\build\gp
uxgboost.vcxproj]
Done Building Project "C:\Users\pavel\Downloads\Git\xgboost\build\gpuxgboost.vcxproj" (default targets) -- FAILED.
```

**Comment by pgyrya** [comment]
I ended up loading pre-compiled version from [Guido Tapia's unofficial repository](http://www.picnet.com.au/blogs/guido/2016/09/22/xgboost-windows-x64-binaries-for-download/), which seems to have worked on my Windows machine.

**Comment by BMcDonie** [comment]
FYI
For others that only have VS 15 2017 and do not wish to install VS 14 2015:
 - Open VS 2017, Select "Tools", "Get Tools and Features", go to the "Individual components" tab and select the "VC++ 2015.3 v14.00 (v140) toolset for desktop".  I also have the "Desktop development with C++" installed under Workloads (not sure if that is required).

**Comment by tqchen** [comment]
New discussions about installations are welcomed at https://discuss.xgboost.ai/
