### ISSUE TITLE
early_stop_round and verbose=0

### ISSUE THREAD

**Issue by wmo** [dmlc/xgboost#320]
Feature early_stop_round only works with verbose being turned on. 
When verbose=0 you get following error and warning, and execution is halted.

1> Error in xgb.train(data = train_Xy, params = multiparamlist, nrounds = a_nrounds,  :
2> For early stopping you need at least one set in watchlist.
3> In addition: Warning message: In xgb.train(data = train_Xy, params = multiparamlist, nrounds = a_nrounds,  :
4> watchlist is provided but verbose=0, no evaluation information will be printed
5> Execution halted 

Line 3: "you need at least one set in watchlist" is wrong, I am using a watchlist, I just turned verbose off.
Line 4: this warning contradicts the prior error: "watchlist is provided but verbose=0"

More info:  search for post titled "Using the new 'early_stop_round' feature with verbose=0"
in the xgboost-user group (google groups).

**Comment by jseabold** [comment]
duplicate of or related to #295?

**Comment by wmo** [comment]
Related indeed.

**Comment by hetong007** [comment]
Thank you for pointing this out. I just remove the command clearing the watchlist with the [latest commit](https://github.com/dmlc/xgboost/commit/458585b5fdb61787e9e33d4bcdc97b2ab87dde97). Please check whether it fixs the issue.

**Comment by hetong007** [comment]
@wmo Is there any update on this issue?

**Comment by wmo** [comment]
In short: tested new version. Success! 
(thanks for fixing it) 


The nitty gritty detail: 

# Part 1: setup test-case with OLD code 

First test with verbose on, then verbose off. 

## verbose on -> no issue 

    > source("xgb_new.R") 
    [0] tst-mlogloss:1.950793   trn-mlogloss:1.906450
    [1] tst-mlogloss:1.786014   trn-mlogloss:1.692291
    [2] tst-mlogloss:1.659854   trn-mlogloss:1.522996
    [3] tst-mlogloss:1.551988   trn-mlogloss:1.382117
    [4] tst-mlogloss:1.459176   trn-mlogloss:1.264832
    [5] tst-mlogloss:1.387517   trn-mlogloss:1.161972
    [6] tst-mlogloss:1.320321   trn-mlogloss:1.072032
    [7] tst-mlogloss:1.265263   trn-mlogloss:0.993583
    [8] tst-mlogloss:1.216034   trn-mlogloss:0.921553
    [9] tst-mlogloss:1.171120   trn-mlogloss:0.857077

    nte,ntr,ete,etr,200,1800,0.28, 0.06833333
    Warning message:
    In xgb.train(data = train_Xy, params = multiparamlist, nrounds = a_nrounds,  :
    Only the first data set in watchlist is used for early stopping process.

## verbose off -> not ok! 

    > source("xgb_new.R") 
    Error in xgb.train(data = train_Xy, params = multiparamlist, nrounds = a_nrounds,  : 
      For early stopping you need at least one set in watchlist.
    In addition: Warning message:
    In xgb.train(data = train_Xy, params = multiparamlist, nrounds = a_nrounds,  :
      watchlist is provided but verbose=0, no evaluation information will be printed



# PART 2: install new version  of xgb.train.R

    git clone https://github.com/dmlc/xgboost
    cd xgboost/
    git checkout 458585b5fdb61787e9e33d4bcdc97b2ab87dde97 ./R-package/R/xgb.train.R
    vi ./R-package/R/xgb.train.R # visually verify that change is made
    bash build.sh
    make Rpack
    R CMD INSTALL xgboost 


# PART 3: rerun test

But first verify changed code is present within R: 

    library(xgboost) 
    print(xgb.train)

-> source change is present ! 

Re-execute test case: 

    > source("xgb_new.R")
    IN TRIAL MODE!
    [0] tst-mlogloss:1.950793   trn-mlogloss:1.906450
    [1] tst-mlogloss:1.786014   trn-mlogloss:1.692291
    [2] tst-mlogloss:1.659855   trn-mlogloss:1.522996
    [3] tst-mlogloss:1.551988   trn-mlogloss:1.382117
    [4] tst-mlogloss:1.459176   trn-mlogloss:1.264832
    [5] tst-mlogloss:1.387517   trn-mlogloss:1.161972
    [6] tst-mlogloss:1.320321   trn-mlogloss:1.072032
    [7] tst-mlogloss:1.265264   trn-mlogloss:0.993583
    [8] tst-mlogloss:1.216034   trn-mlogloss:0.921553
    [9] tst-mlogloss:1.171120   trn-mlogloss:0.857077

    nte,ntr,ete,etr,200,1800,0.28, 0.06833333
    Warning message:
    In xgb.train(data = train_Xy, params = multiparamlist, nrounds = a_nrounds,  :
      watchlist is provided but verbose=0, no evaluation information will be printed

**Conclusion** : the fix solves the reported problem!

**Comment by hetong007** [comment]
Thank you for bringing this result :)
