### ISSUE TITLE
[jvm-packages] xgboostj-spark: allow additional params to be set in XGBoostEstimator

### ISSUE THREAD

**Issue by LiranPo** [dmlc/xgboost#3202]
Issue: currently, "data frame" params for the `XGBoostEstimator` (e.g., the feature col name, label col name etc.) do not include the `rawPredictionCol` param, which can only be set directly in `XGBoostClassificationModel`. Consider having a `def setRawPredictionCol` in `XGBoostEstimator`, which would fail validation if this is not a classification model. This `rawPredictionCol` param would then be copied to the generated `XGBoostClassificationModel`. This is more in line with the way other estimators work (e.g., LogisticRegressionEstimator).

Operating System: CentOs 7

Compiler: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16)

Package used (python/R/jvm/C++): jvm - spark

`xgboost` version used: 0.7

The commit hash: `v0.7`

**Comment by CodingCat** [comment]
feel free to open an PR

**Comment by hcho3** [comment]
Consolidating to #3439. This issue should be re-opened if someone decides to actively work on implementing this feature.
