### ISSUE TITLE
Strange thing happpen when installing with Windows Binaries

### ISSUE THREAD

**Issue by jinyy0822** [dmlc/xgboost#3204]
Hi, guys

I'm trying to install gpu enabled version xgboost, and I followed exact step from [this instructions].(http://www.picnet.com.au/blogs/guido/2016/09/22/xgboost-windows-x64-binaries-for-download/)

`git clone https://github.com/dmlc/xgboost.git xgboost_install_dir`
`copy libxgboost.dll (downloaded from this page) into the xgboost_install_dir\python-package\xgboost\ directory`
`cd xgboost_install_dir\python-package\`
`python setup.py install`

And now after I run all those steps, I successfully installed xgboost into a egg folder called "xgboost-0.7-py3.5.egg", under which there is two subfolder "EGG-INFO" and xgboost, but there isn't a folder in my python site-packages called xgboost...like this:

*     /site-packages
*         /xgboost-0.7-py3.5.egg
*             /EGG-INFO
*             /xgboost

 I tried to copy paste the xgboost folder into site-package, but the benchmark program still fails. Did I miss something? 

Here is the command log [command.log](https://github.com/dmlc/xgboost/files/1850061/command.log)

## Environment info
Operating System: Windows 10 x64

Package used (python/R/jvm/C++): python 3.5.2 x64

`xgboost` version used: 0.7

Please help me! I just spend most all my money on nvidia 1080ti and I really hope that I can implement this...

**Comment by jinyy0822** [comment]
anyone?

**Comment by tqchen** [comment]
installations questions are now welcomed at https://discuss.xgboost.ai/
