### ISSUE TITLE
[jvm-packages] Tree visualization shows leaf = -0.1 only

### ISSUE THREAD

**Issue by vulauet** [dmlc/xgboost#3205]
Hi guys,
I've trained several models using the jvm-packages, then used python package to plot trees (120 trees each model), and the images of about 20 first trees of each model always show leaf = -0.1 (as in the attached image). Is this a bug or how do I interpret it? 

![image](https://user-images.githubusercontent.com/9205705/37942743-d4c98c3e-319e-11e8-9a83-1c76c4f95f6a.png)

Sample model
(https://github.com/dmlc/xgboost/files/1850128/sample.model.tar.gz)

## Environment info
Operating System: Linux Mint 18.3 Cinnamon 64-bit, Linux Kernel 4.10.0-38-generic

Compiler: gcc version 5.4.0 20160609

Package used (python/R/jvm/C++): xgboost4j-0.7, python 2.7.12 xgboost0.7.post3

**Comment by hcho3** [comment]
I tried creating a text dump of your model and I get leaf=-0.1 for first 20 trees as well.

**Comment by hcho3** [comment]
You should leave them alone.
