### ISSUE TITLE
How to pass additional argument to custom objective function?

### ISSUE THREAD

**Issue by peeyman** [dmlc/xgboost#3210]
I want to write a custom objective function which can accept prediction of the other models as arguments. To be more precise, I want something like the following as header:

`def customObjective(preds, dtrain, otherArgs):`

Or is it possible to pass those predictions in dtrain and extract them inside?

Thank you in advance.

**Comment by Laurae2** [comment]
See https://github.com/Microsoft/LightGBM/issues/1292
