### ISSUE TITLE
Question about ThresholdL1

### ISSUE THREAD

**Issue by qianrenliang** [dmlc/xgboost#3211]
I dont understand why use
      if (sum_gradient > reg_alpha), return sum_gradient - reg_alpha
     if (sum_gradient < -reg_alpha), return sum_gradient + reg_alpha
refer to : 
template <typename T1, typename T2>
XGBOOST_DEVICE inline static T1 ThresholdL1(T1 w, T2 lambda) {
  if (w > +lambda)
    return w - lambda;
  if (w < -lambda)
    return w + lambda;
  return 0.0;
}

**Comment by qianrenliang** [comment]
I understand...

**Comment by xjqbest** [comment]
can you explain...  I'm confused about it too
可以解释一下么，我也没搞懂...
