### ISSUE TITLE
Provide instructions on how to remove XGBoost Python package after build and installation from source

### ISSUE THREAD

**Issue by fantauzzi** [dmlc/xgboost#3219]
I have built and installed the Python package [as per instructions](http://xgboost.readthedocs.io/en/latest/build.html#python-package-installation),  except I run this command for installation (because the provided one stops with an error):

`python setup.py install --user`

I am unable to remove the package with pip3, as I get:

```
-> pip3 uninstall  xgboost
Not uninstalling xgboost at /home/fanta/.local/lib/python3.5/site-packages/xgboost-0.7-py3.5.egg, outside environment /home/fanta/.local/python3.5

```

Please consider adding to the Installation Guide  instructions to uninstall, and to update, the Python package, after build and installation from source.

**Comment by hcho3** [comment]
Try running `python -m pip uninstall xgboost`.
