### ISSUE TITLE
Clarification on int_constraints_list

### ISSUE THREAD

**Issue by cassieqiao** [dmlc/xgboost#3220]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System: R Studio Server Pro

Compiler:

Package used (python/R/jvm/C++): 

`xgboost` version used: this particular branch

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`)
2. Logs will be helpful (If logs are large, please upload as attachment).

If you are using jvm package, please 

1. add [jvm-packages] in the title to make it quickly be identified
2. the gcc version and distribution

If you are using python package, please provide

1. The python version and distribution
2. The command to install `xgboost` if you are not installing from source

If you are using R package, please provide

1. The R `sessionInfo()`
2. The command to install `xgboost` if you are not installing from source

## Steps to reproduce

https://github.com/BlueTea88/xgboost/blob/int_cont/R-package/demo/interaction_constraints.R

## What have you tried?

I followed your example and I assume int_constraints_list = list(c('V1','V2'),c('V3','V4','V5')) means V1 can only interact with V2 and vice versa. Same idea for V3, V4 and V5. But I got results like below. Basically, the constraints are not applied. Can you clarify it? Thanks.

> temp.int
[[1]]
[1] "V3" "V5"

[[2]]
[1] "V3" "V4"

[[3]]
[1] "V4" "V5"

[[4]]
[1] "V3" "V4" "V5"

[[5]]
[1] "V1" "V3" "V4" "V5"

[[6]]
[1] "V2" "V3" "V4" "V5"

[[7]]
[1] "V3" "V4" "V5" "V6"

[[8]]
[1] "V4" "V5" "V8"

[[9]]
[1] "V4" "V5" "V7"

[[10]]
[1] "V2" "V4" "V5"

Best,
Cassie

**Comment by BlueTea88** [comment]
Please try the xgboost version from my experimental branch below:
https://github.com/BlueTea88/xgboost/tree/int_cont

Cheers,
Andrew

**Comment by cassieqiao** [comment]
Thank you Andrew!

After cloning to the branch, it works as expected.
