### ISSUE TITLE
Is there any possible incorporate the multi target regression models in xgboost?

### ISSUE THREAD

**Issue by bifeng** [dmlc/xgboost#3226]
I have found that multi-target or multi-response regression  is very common and useful. Such as the past kaggle contest like [See click predict fix](https://www.kaggle.com/c/see-click-predict-fix) and [Online Product Sales](https://www.kaggle.com/c/online-sales).

I just want to know is proper to incorporate some multi-target regression models in xgboost or not. Or any suggestions?

**Comment by tqchen** [comment]
you can just build one xgboost model for each target new questions are welcomed at https://discuss.xgboost.ai/.
