### ISSUE TITLE
colsample_bytree can not be set

### ISSUE THREAD

**Issue by gunakkoc** [dmlc/xgboost#3230]
XGBoost does not work if I set "colsample_bytree" parameter to a value other than '1'. The following error is produced:

> src/tree/updater_colmaker.cc:163: Check failed: param.colsample_bytree > 0U (0 vs. 0) colsample_bytree cannot be zero.

If I omit "colsample_bytree" or set it to '1' everything works fine.

I am using python 3.6 and I have installed XGBoost via conda. My OS is Ubuntu 16.04.4

**Comment by hcho3** [comment]
Which locale is your operating system running in? Some locales use commas instead of periods to designate decimal points.

Ps. If you have future questions, feel free to raise them in https://discuss.xgboost.ai/.

**Comment by sramirez-stratio** [comment]
I got the same problem, I think it's not related to locales as the param value is of double type. 

This is the shape of the input feature in XGBoost train:

 params : scala.Predef.Map[scala.Predef.String, scala.Any]

**Comment by WegDamit** [comment]
Looks like a bug in the code:
```c       
 unsigned n = std::max(static_cast<unsigned>(1),
                              static_cast<unsigned>(param_.colsample_bytree * feat_index_.size()));
        std::shuffle(feat_index_.begin(), feat_index_.end(), common::GlobalRandom());
        CHECK_GT(param_.colsample_bytree, 0U) 
               << "colsample_bytree cannot be zero.";
```
colsample_bytree is a float, values between 0 and 1, and the check assumes an unsigned int.
so the float will always be 0 and the check fails...

(from https://github.com/dmlc/xgboost/blob/release_0.72/src/tree/updater_colmaker.cc)

i think the check should be on the product...

**Comment by hcho3** [comment]
@WegDamit Thanks for the report. This is likely be a bug. Will have to check if `param_.colsample_bytree` is being implicitly being casted to zero. At any rate, it may be better to simply check the size of `feat_index_`.

**Comment by hcho3** [comment]
@sramirez-stratio It's silly to apply locales to parameter values. We should look into using the C locale.

**Comment by WegDamit** [comment]
changing the locale to en_US or C and using a value of 0.8 helped, as using a value of "0,8".
But it affects only colsample_bytree not e.g. "learning_rate"...?

**Comment by hcho3** [comment]
Related: dmlc/dmlc-core#323

**Comment by hcho3** [comment]
Merging dmlc/dmlc-core#455 will fix this issue, I think.
