### ISSUE TITLE
Memory leak in xgb.DMatrix [R]

### ISSUE THREAD

**Issue by parsons-kyle-89** [dmlc/xgboost#3235]
There appears that repeatedly calling `xgb.DMatrix` causes R to use more and more memory as measured by `top` until R crashes.  This is despite the fact that when R reports it's own memory usage (say with `pryr`), it reports a constant memory usage.  

## Environment info
Operating System: Ubuntu 16.04.4 LTS

Compiler: gcc 5.4.0

Package used R:

`xgboost` version used: 0.6.4.1 (CRAN release), latest `drat` release, and commit with hash `4109818b3229f99e300a9da82b6326fa82e855fd`.

R sessionInfo:
R version 3.4.3 (2017-11-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.4 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_3.4.3

Installed with `install.package("xgboost")`.
Also installed with 
```
install.packages("drat", repos="https://cran.rstudio.com")
drat:::addRepo("dmlc")
install.packages("xgboost", repos="http://dmlc.ml/drat/", type = "source")
```
Also installed by cloning the github repo and running
```
git clone --recursive https://github.com/dmlc/xgboost
cd xgboost
git submodule init
git submodule update
cd R-package
R CMD INSTALL .
```

## Steps to reproduce
The following code causes the R to use more and more memory until it crashes.  The growing memory usage can be observed by simultaneously running `top` or `htop`.

```
library(xgboost)

n = 10000
data = matrix(rnorm(n^2,0,1), n, n)
label = sample(c(0,1),n,replace = TRUE)

i = 0 
while (TRUE) {
  message = paste0('round ', i)
  writeLines(message)
  i = i + 1 
  
  train = xgb.DMatrix(data = data,
                      label = label)
}

```

## What have you tried?

Nothing beyond identification of the bug.

**Comment by khotilov** [comment]
To me, this looks like an example of the fragility of automatic garbage collection in R. With your example, I see the memory consumption raising and then hovering close to the top for a while (as if the garbage collector being able to do its janitor job for at least some time), and then a sudden crash happens (as if the GC has missed its opportunity to run, and R tips over the memory limit with the large allocations required to create a DMatrix with this data). However, the memory consumption stays low and constant if I force R to run `gc()` within the the while loop. I don't really see what could be done here on the xgboost's side.

**Comment by parsons-kyle-89** [comment]
You're right.  Thanks for the eyes.  I believe there's a more complex memory issue happening when you throw `xgb.train` into the mix.  I might try to write up a post about that soon.
