### ISSUE TITLE
the more nthread set for predict the slower my server get

### ISSUE THREAD

**Issue by dwroy** [dmlc/xgboost#3237]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System: centos7    vps 32cpu  64g

Compiler: gcc 7

Package used (python/R/jvm/C++): C++

`xgboost` version used: 7.0

I use c++ with xgboost for online predict,

I set thread  use  omp_set_num_threads(n)  and  XGBoosterSetParam(booster, "nthread", n);

but the more thread I set, I slower XGBoosterPredict gets

**Comment by dwroy** [comment]
each request for xgboost server contains about 100 samples, I parse the feature into a 100 * 21  double float array, and use XGDMatrixCreateFromMat(vecs, 100 ,  21 , 0, &dmat) to get Matrix. then use XGBPredict to get the results

**Comment by dwroy** [comment]
I duplicate 1 model for each thread, and set param nthread=1 for every model, uses about 15 threads running prediction.

**Comment by lv-zhaoyu** [comment]
请问这个问题解决了吗
