### ISSUE TITLE
RealCover still present in documentation / vignettes.

### ISSUE THREAD

**Issue by spinza** [dmlc/xgboost#3239]
Co-occurence computation was removed with [this commit](https://github.com/khotilov/xgboost/commit/5a8d55b2af0e550554d0fa4432cc4c888347b7ce) but is still present in docs:
Here:
https://github.com/dmlc/xgboost/blob/5c9f01d0a974edabfde0adda07f436c72a2b10e5/doc/R-package/discoverYourData.md
And here:
https://github.com/dmlc/xgboost/blob/98ea46153223ce3539da1e8e18d9858f3d88639c/R-package/vignettes/discoverYourData.Rmd

**Comment by spinza** [comment]
That is off topic here.

**Comment by SilviuMarchidanu** [comment]
Sorry I understand , no other way of getting in contact.

**Comment by hcho3** [comment]
Consolidating to #3439. This issue should be re-opened if someone decides to actively work on fixing the document.
