### ISSUE TITLE
Partially Load dMatrix Binary File with Given Indices?

### ISSUE THREAD

**Issue by liujxing** [dmlc/xgboost#3241]
Is it possible to load dMatrix binary file from disk partially, by loading only rows with specified indices? If that is not supported, how can I externally parse the binary file by finding the portion of data corresponding to a given row index?

**Comment by tqchen** [comment]
for now, this is not supported, the only way to achieve this so far is to load everything into memory and then slice

**Comment by tqchen** [comment]
new discussion questions are welcomed at https://discuss.xgboost.ai/
