### ISSUE TITLE
Python kernel killed after booster.update or booster.boost are called

### ISSUE THREAD

**Issue by liujxing** [dmlc/xgboost#3243]
I was using xgboost 0.7 in ipython notebook, and I was trying to use booster.update or booster.boost to fit the model for a single iteration. After calling the method, I used booster.predict to check if my booster gives improved predictions. Then the kernel always died after I call booster.predict in here.

**Comment by hcho3** [comment]
Closing for now. If you still have problem with XGBoost installation, please post a new question at https://discuss.xgboost.ai/.
