### ISSUE TITLE
Monotonic constraints for multi-class classification

### ISSUE THREAD

**Issue by shaswatshah** [dmlc/xgboost#3248]
Can we do multinomial monotonic constraints?
If we can specify monotonic constraints in the context of one vs all for each class in the multinomial classification, that would be useful in a lot of contexts. For example, consider this problem for course selection.
- If someone has already taken CS_101, they are more likely to take CS_102
- If someone has already taken CALC_102, they are unlikely to take CALC_101 and so on..

In most of these cases, it is possible to express the set of monotonic constraints as a collection of one-vs-all constraints for each of the possible classes.

What would be best way to accomplish this?

**Comment by tqchen** [comment]
This is an open-ended problem and we cannot act on this for in a short period, such discussions are more than welcomed at https://discuss.xgboost.ai/
