### ISSUE TITLE
Roadmap: Bi-monthly release cycles for core lib

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#3252]
In the interest of keeping the stable releases up-to-date with the latest master, I'd like to commit to a regular release cycle for the core lib. I propose a **bi-monthly release schedule**. Here are some time estimates for the upcoming releases:

* Version 0.72: June 1, 2018
* Version 0.73: August 1, 2018
* Version 0.74: October 1, 2018

(Some of these versions may jump to 0.80, if there's any "major" event.)

Some points of discussion

* **Is bi-monthly cycle reasonable interval?** I thought of 3 months first, but I didn't want too much a gap between stable release and latest master.
* **Code freezing and backports.** @CodingCat suggests that a new branch be created each time a release is made (see discussion in #3200). The release branch will be "frozen" and almost no commits will be added to that branch. Should any backports and post-fixes need to be added, they will be manually cherry-picked into the release branch.
* **Version 1.0 in horizon?** IMHO, a good time for this is when the GPU support becomes mature. @RAMitchell and I are working to set up a Jenkins CI server for the GPU code.
* **Binary wheel builds** This has been put off for a while. I hope for the day when users can download pre-built binaries with `pip install xgboost`. Many issue posts today involve installation problems.
* **Versioned docs** We need a way to expose XGBoost docs according to stable release versions.

**Comment by mingwandroid** [comment]
We'd like to be more regimented in our builds of XGBoost; getting releases out as soon after you declare them ready as possible so a regular cadence would suit us well. Bi-monthly sounds fine to me from a packager's perspective too.

**Comment by RAMitchell** [comment]
Sounds great @hcho3

**Comment by CodingCat** [comment]
it looks good to me....and I will work on publishing to maven for jvm-package, I think I can make it before the next release

**Comment by terrytangyuan** [comment]
Sounds good to me!

**Comment by tqchen** [comment]
This sounds good. The backporting could take some efforts, and I think one possible way is only promise backporting up to one or two versions

**Comment by tqchen** [comment]
We should still use tags and keep that official. To keep things minimum, maybe what we can do is to keep backport branch up to one version.  Say after 0.8 release,  the 0.8 branch is kept until 0.9 release and it can be deleted on 1.0 release.

**Comment by mingwandroid** [comment]
Sorry to go tangential..  0.80 and 0.90 releases I hope? ;-) After 1.0 dropping this two digit minor version should be entirely possible.

**Comment by hcho3** [comment]
@tqchen I agree. Here is my idea of how things will work in the future:

![versioning_system](https://user-images.githubusercontent.com/2532981/39010631-0764a98a-43c4-11e8-800a-dc2ff49e5d3d.png)

* A tag is created for every release
* Each release branch will have a few commits for backports. Each backport commit is a copy of a commit from the master (the copy being made by `git cherry-pick`).
* Release branches are kept around for a while: 0.71 and 0.72 branches will be around until 0.80, for example.
