### ISSUE TITLE
XGBoost Spark Sample Weight Support

### ISSUE THREAD

**Issue by qingyuanxingsi** [dmlc/xgboost#3258]
Can you support sample weight configuration like python(C++) xgboost library, maybe a **setWeightCol** api??

**Comment by Nirvanada** [comment]
Just specify a column named "weight" in DataFrame

**Comment by yanboliang** [comment]
@qingyuanxingsi We are working on [xgboost-spark refactor](), we'd provide API ```setWeightCol``` in the new implementation. If you are using the current API, like @Nirvanada , you can specify the name of weight column as ```weight```, it should work.

**Comment by qingyuanxingsi** [comment]
So version 0.8 is ok?? And if I'm using a VectorAssembler instance, I should include the "weight" column in the input columns??

**Comment by yanboliang** [comment]
Yeah, your requirement should work well in the next major release. If you are using ```VectorAssembler```, don't include ```weight``` column in input columns, as ```VectorAssembler``` is used to assemble features column, weight column is separate one.

**Comment by qingyuanxingsi** [comment]
@yanboliang Good! Got it!Much thanks!
