### ISSUE TITLE
[jvm-packages] Unknown metric function ndcg-

### ISSUE THREAD

**Issue by fubincom** [dmlc/xgboost#3259]
## Environment info
Operating System:
Mac

Package used (python/R/jvm/C++):
jvm
`xgboost` version used:
0.7.0

I saw website https://github.com/dmlc/xgboost/blob/master/doc/parameter.md where mentioned that I could use "ndcg-" as a parameter for eval_metric. But when I used it, I got following error logs:
[11:39:24] /Users/zll/IdeaProjects/game/xgboost/src/metric/metric.cc:21: Unknown metric function ndcg-
But if I change to ndcg, everything could be fine. So, could I use ndcg- for training my model?

**Comment by yangl326-Dylan** [comment]
hi 
did you fix the problem？

**Comment by fubincom** [comment]
@yangl326-Dylan not yet, but you could set 2 as the positive label, and 1 (default value) would denote as the negative label.

**Comment by hcho3** [comment]
Closing this for the lack of activity in last 90 days. Any future discussions are welcome at https://discuss.xgboost.ai/.
