### ISSUE TITLE
gblinear predicts NaNs for non-NaN input

### ISSUE THREAD

**Issue by pseudotensor** [dmlc/xgboost#3261]
[gblinear_predictsnans.zip](https://github.com/dmlc/xgboost/files/1934886/gblinear_predictsnans.zip)

**Comment by pseudotensor** [comment]
@RAMitchell

**Comment by RAMitchell** [comment]
Can you remove the h2o dependency please:
```
ImportError: No module named 'h2oaicore'
```
One thing we can check for here is linear separability in the input problem. If the problem is trivially solvable by logistic regression then the coefficients will trend to infinity and can be a source of NaNs.

**Comment by pseudotensor** [comment]
Thanks.  I updated the zip above.

**Comment by pseudotensor** [comment]
It seems there should be a way to avoid things going to infinity in certain cases without  a hard switch to another solver.

**Comment by RAMitchell** [comment]
@pseudotensor I'm still unable to open the pickle file:
```
Traceback (most recent call last):
  File "nan.py", line 77, in <module>
    (model, X, y, sample_weight, params, scaler, kwargs) = pickle.load(open("7583ea11-551a-43f5-979f-c294ee53d4df_xgbobj.dat", "rb"))
ImportError: No module named 'h2oaicore'
```

> It seems there should be a way to avoid things going to infinity in certain cases without a hard switch to another solver.

I can definitely build in a guard against this but let's confirm the problem first.

**Comment by pseudotensor** [comment]
[gblinear_predictsnans_new.zip](https://github.com/dmlc/xgboost/files/1935412/gblinear_predictsnans_new.zip)

Ok, this should be striped of any imports.  Let me know.

**Comment by RAMitchell** [comment]
This seems to be a result of the custom objective function being used. Switching to "reg:linear" solves it.

I haven't seen this before, do you have a source for it?

```
def custom_objective_fair(actual, pred):
    c = 2
    x = pred - actual
    c_denom = c / (np.abs(x) + c)
    grad = c_denom * x
    hess = c_denom ** 2
    return grad, hess
```

**Comment by pseudotensor** [comment]
[makenan.zip](https://github.com/dmlc/xgboost/files/1968713/makenan.zip)

This makes NaN output for predictions from non-NaN input.

**Comment by pseudotensor** [comment]
I browsed through the model object and notice that the fit produced feature importances that are all nan.  I presume these feature importances are the coefficients themselves?  If so, then the fit produced all nan coefficients, so it's no surprise the predict produced nans.

```
assert np.isfinite(model.feature_importances_).any(), "Got non-finite feature importances from fit"
```

**Comment by pseudotensor** [comment]
The below code shows nan's are in the actual biases and weights from gblinear during fit.
```
# Check that biases and coefficients from fit are not nan or inf
    booster = model.get_booster()
    dump = booster.get_dump()[0]
    assert not ('\nnan\n' in dump or '\n-nan\n' in dump or '\ninf\n' in dump or '\n-inf\n' in dump), "Got non-finite weights from fit: %s" % str(dump)
```

```
AssertionError: Got non-finite weights from fit: bias:
-nan
-nan
-nan
weight:
nan
nan
nan
-nan
-nan
-nan
nan
nan
nan
-nan
-nan
-nan
nan
nan
nan
-nan
-nan
-nan
nan
nan
nan
-nan
-nan
-nan
nan
```
etc.

**Comment by RAMitchell** [comment]
@pseudotensor I can't reproduce your result because the labels from the pickle file have type 'None'.

I tried generating some labels and the results look fairly normal:

```import pickle
import pandas as pd
import xgboost as xgb
from random import randint
(model, X, y, sample_weight_eval_set, params, scaler, kwargs) = pickle.load(open("pickle.pkl", "rb"))

model = xgb.XGBClassifier(base_score=0.5, booster='gblinear', colsample_bylevel=1,
       colsample_bytree=1, coordinate_selection='cyclic', debug_verbose=2,
       early_stopping_rounds=20, early_stopping_threshold=0.01,
       eval_metric='mlogloss', gamma=0, gpu_id=0, learning_rate=1,
       max_bin=1, max_delta_step=0, max_depth=0, max_leaves=0,
       min_child_weight=1, min_lambda_fraction=0.0001,
       monotonicity_constraints=False, n_estimators=500, n_gpus=0,
       n_jobs=1, n_lambda=20, nthread=None, num_class=3, num_classes=3,
       objective='multi:softprob', random_state=11835857,
       reg_alpha=5.0000000000000002e-05, reg_lambda=0.0001,
       scale_pos_weight=1, seed=None, silent=False, subsample=1,
       tolerance=0.01, tree_method='auto', updater='coord_descent')
y =[randint(0,2) for p in range(0,X.shape[0])]
model.fit(X,y)
preds=model.predict_proba(X, y, **kwargs)
print("preds")
print(preds)
```
```
Preds
...
[ -5.33847523e+00  -2.38344693e+00  -9.02415562e+00]
 [ -1.42113388e+00   7.69711733e-01   1.59543514e+00]
 [  8.87633514e+00  -3.64232922e+00  -1.12374353e+01]
 [ -2.77958512e+00   1.26352110e+01  -9.98290730e+00]
 [ -1.02403126e+01   9.76840878e+00  -6.67989373e-01]
 [ -5.54171705e+00   1.18449140e+00   3.32589746e+00]]
```

**Comment by pseudotensor** [comment]
[gblinearnan.zip](https://github.com/dmlc/xgboost/files/1985797/gblinearnan.zip)

This is a super clean version that fails for me in the way stated.  I used dmlc e1f57b4417146b3a11e14619b00851c67dffa0a3 .

**Comment by RAMitchell** [comment]
This was caused by the second-order gradient approaching 0 in the multiclass objective. Correcting means your example no longer generates NaNs but training is still not very stable due to the large number of classes. I will change my recommendation to use learning rate of 0.5 for safety :)

**Comment by pseudotensor** [comment]
Still getting nan-outs, just less frequently.  Will post repro.

**Comment by pseudotensor** [comment]
[nanpreds.zip](https://github.com/dmlc/xgboost/files/2812185/nanpreds.zip)

A new clean case.  It's been about 9 months.  Any chance this can get fixed?  We see it all the time.

@RAMitchell @trivialfis 

Thanks.

**Comment by pseudotensor** [comment]
For the above, nothing odd about the coefficients themselves.  Min is overall (among all classes) -0.163164 and max is 0.176556 .  This case is 100% reproducible on different types of GPU machines (not surprising as this uses CPUs).  But we've seen it happen on GPU cases too.

**Comment by trivialfis** [comment]
I'm not sure how to load the pickled data:

>   File "failclean.py", line 5, in <module>
    data = pickle.load(open("data.pkl", "rb"))
_pickle.UnpicklingError: state is not a dictionary

**Comment by pseudotensor** [comment]
Hi, Sorry, I deleted, it wasn't good case.  I was passing nan data into glm.

**Comment by hcho3** [comment]
Feel free to post a new issue if a similar issue arises again.
