### ISSUE TITLE
changing cost function in xgboost

### ISSUE THREAD

**Issue by benyaminelc90** [dmlc/xgboost#3262]
I'm using the newest version of xgboost package in python 2.7 and based on my problem, I'm going to change xgboost cost function to use my own defined cost function. Couple of questions:
1. In which part of the xgboost package should I find and change the cost function?
2. After changing the cost function, how can I add the updated code to the xgboost package to use the new training function instead of xgboost's pre-defined function?

**Comment by gxlzj** [comment]
see examples here: https://github.com/dmlc/xgboost/blob/master/demo/guide-python/custom_objective.py

**Comment by hcho3** [comment]
Any future discussions are welcome at https://discuss.xgboost.ai/.
