### ISSUE TITLE
Is there a way to determine the version of a xgboost library?

### ISSUE THREAD

**Issue by ungil** [dmlc/xgboost#3265]
Is there an API call or other mechanism to find out what version is being used?

**Comment by ungil** [comment]
Thanks for the suggestion, unfortunately it doesn't work for my use case. I am writing an interface to xgboost from common lisp (https://gitlab.common-lisp.net/cungil/xgboost) and it would be nice to be able to check that the libxgboost.so library used does match the version of the API implemented.

**Comment by hcho3** [comment]
@ungil For now, you can read the VERSION file in `python` directory: https://github.com/dmlc/xgboost/blob/master/python-package/xgboost/VERSION
