### ISSUE TITLE
Treating missing values for categorical variables in XGBoost

### ISSUE THREAD

**Issue by kapil-stp84** [dmlc/xgboost#3267]
I have a categorical variable which i am converting to dummy variables using One-hot encoding. However, the missing values in this categorical variable creates an additional dummy variable. How does XGBoost address these missing values? Can we continue using the additional dummy variable?

--convert categorical factor into one-hot encoding. For eg, assume Segment factor has 5 different categories viz... A, B, C, D E 
Segment_Flag <- model.matrix(~Segment-1,train_data)

The above gives me values such as:

Segment | SegmentA | SegmentB | SegmentC | SegmentD | SegmentE
-- | -- | -- | -- | -- | --
0 | 0 | 1 | 0 | 0 | 0
0 | 1 | 0 | 0 | 0 | 0
0 | 1 | 0 | 0 | 0 | 0
0 | 0 | 0 | 1 | 0 | 0
0 | 0 | 0 | 0 | 0 | 1
0 | 0 | 0 | 0 | 1 | 0
1 | 0 | 0 | 0 | 0 | 0
1 | 0 | 0 | 0 | 0 | 0

If you notice a separate dummy variable (first one)  is getting created for Null Values. 

I have read the question on github & understand how the missing values are treated. Below link is what i have looked at.
What are the ways of treatng missing values in XGboost? #21
https://github.com/dmlc/xgboost/issues/21

My query is slightly different.

**Comment by tqchen** [comment]
you can just set missing value as nan. The additional dummy variable also works. New questions are now welcomed at https://discuss.xgboost.ai/
