### ISSUE TITLE
what is the meaning of probabilities in the ml.dmlc.xgboost4j.scala.spark.XGBoost

### ISSUE THREAD

**Issue by heitaoq** [dmlc/xgboost#3271]
the result of my model: I don't know the meaning of the  probabilities, it is a vector . it is confused me.
CONSOLE# |label| features| probabilities|prediction|
CONSOLE# +-----+--------------------+--------------------+----------+
CONSOLE# | 0.0|[6.96490723789804...|[0.99447655677795...| 0.0|
CONSOLE# | 0.0|[6.96490723789804...|[0.99444460868835...| 0.0|
CONSOLE# | 0.0|[1.09763146077557...|[0.99271130561828...| 0.0|
CONSOLE# | 0.0|[1.09763146077557...|[0.99287420511245...| 0.0|
CONSOLE# | 0.0|[1.09763146077557...|[0.99267888069152...| 0.0|
CONSOLE# | 0.0|[1.09763146077557...|[0.99222505092620...| 0.0|
CONSOLE# | 0.0|[1.09763146077557...|[0.99282979965209...| 0.0|
CONSOLE# | 0.0|[1.63716518353888...|[0.99474602937698...| 0.0|
CONSOLE# | 0.0|[1.63716518353888...|[0.99474138021469...| 0.0|
CONSOLE# | 0.0|[1.63716518353888...|[0.99487847089767...| 0.0|
CONSOLE# | 0.0|[1.63716518353888...|[0.99489271640777...| 0.0|
CONSOLE# | 0.0|[1.63716518353888...|[0.99468421936035...| 0.0|
CONSOLE# | 0.0|[1.63716518353888...|[0.99497640132904...| 0.0|
CONSOLE# | 0.0|[1.63716518353888...|[0.99486529827117...| 0.0|
CONSOLE# | 0.0|[1.63716518353888...|[0.99521017074584...| 0.0|
CONSOLE# | 0.0|[1.63716518353888...|[0.99509263038635...| 0.0|
CONSOLE# | 0.0|[4.05539878686833...|[0.99283981323242...| 0.0|
CONSOLE# | 0.0|[4.25565421763934...|[0.99398571252822...| 0.0|
CONSOLE# | 0.0|[9.39390812442050...|[0.99349820613861...| 0.0|
CONSOLE# | 0.0|[9.39390812442050...|[0.99340665340423...| 0.0|
CONSOLE# +-----+--------------------+--------------------+--------

**Comment by yanboliang** [comment]
It should be the predicted class conditional probabilities.

**Comment by heitaoq** [comment]
the length of probabilities vector is the num of the predicted class ???

**Comment by yanboliang** [comment]
Yep.

**Comment by heitaoq** [comment]
Thank you very much
