### ISSUE TITLE
xgboost early stopping for linear booster again broken in R package?

### ISSUE THREAD

**Issue by rwarnung** [dmlc/xgboost#3274]
## Environment info
Operating System: Windows >= 8 x64 (build 9200)

Package used (python/R/jvm/C++): R package

`xgboost` version used: xgboost_0.6.4.1

installed via 

`install.packages("xgboost", repos="http://cran.rstudio.com", type = "source")`

If you are using R package, please provide

1. The R `sessionInfo()`

> R version 3.5.0 (2018-04-23) Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows >= 8 x64 (build 9200)
> 
> Matrix products: default
> 
> locale: [1] LC_COLLATE=English_United States.1252 
> LC_CTYPE=English_United States.1252    [3] LC_MONETARY=English_United
> States.1252 LC_NUMERIC=C                           [5]
> LC_TIME=English_United States.1252    
> 
> attached base packages: [1] stats     graphics  grDevices utils    
> datasets  methods   base     
> 
> other attached packages: [1] xgboost_0.6.4.1
> 
> loaded via a namespace (and not attached): [1] compiler_3.5.0     
> magrittr_1.5        Matrix_1.2-14       tools_3.5.0        
> yaml_2.1.18         [6] stringi_1.1.7       grid_3.5.0         
> data.table_1.10.4-3 lattice_0.20-35

I use the current `xgboost` version from CRAN.
The following code gives an error related to early stopping with the linear booster:

    require(xgboost)
    data = as.matrix(iris[,1:4])
    target = ifelse(iris[,5]=="setosa",1,0)
    model = xgboost(data,target, booster="gblinear", nrounds=82, max_depth=1, eta=0.05, lambda=154, lambda_bias=57.8, alpha=13.1, 
                    colsample_bytree=0.5, subsample=0.8, min_child_weight=5, early_stopping_rounds=4, verbose=1,
                    eval_metric="logloss",objective="binary:logistic")
    
    p = predict(model, newdata = data)

>  p = predict(model, newdata = data) Error in predict.xgb.Booster(model, newdata = data) :    [21:21:29]
> amalgamation/../src/gbm/gblinear.cc:179: Check failed: (ntree_limit)
> == (0) GBLinear::Predict ntrees is only valid for gbtree predictor

I reported this bug about a year [ago on github](https://github.com/dmlc/xgboost/issues/2029)

I just can't recall what I did to make it run last time.
What works is to copy the folder from the repository of the last R version to the current one. But this is really bad and I would like to use in on rstudio.cloud as well.

I really appreciate your work on the package. I would love to use it in the future. Thank you!

**Comment by SixiangHu** [comment]
From the sessionInfo output, looks like you are still using 0.6.4?

> other attached packages: [1] xgboost_0.6.4.1

Thinking the early stopping issue may be fixed in 0.7 (also available in CRAN i think).  Hence a package upgrade?

**Comment by rwarnung** [comment]
@SixiangHu  thanks for pointing that out. At the moment I try it on rstudio.cloud in order not to mess up my local working set-up. There the installation via

`install.packages("xgboost", repos="http://cran.rstudio.com", type = "source")`

did not work.
I go the error 

> g++: internal compiler error: Killed (program cc1plus)
> Please submit a full bug report,
> with preprocessed source if appropriate.
> See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
> make: *** [amalgamation/xgboost-all0.o] Error 4
> /opt/R/3.4.4/lib/R/etc/Makeconf:166: recipe for target 'amalgamation/xgboost-all0.o' failed

So maybe I thought that I had updated but I haven't. 
Now I have to find out, why I can not install xgboost on rstudio.cloud
Thank you!

**Comment by jeremiedb** [comment]
I ran through a similar error while building a Ubuntu 16.04 docker image from Windows (was not `xgboost-all0.o'` that failed) using cmake: 

```
git clone --recursive https://github.com/dmlc/xgboost && \
	cd xgboost && mkdir build && cd build && \
	cmake .. -DUSE_CUDA=OFF -DR_LIB=ON && make install -j
```

However the following building approach works, but I can't tell why the cmake is now crashing while it worked fined few weeks ago. 

```
git clone --recursive https://github.com/dmlc/xgboost && \
	cd xgboost && cd R-package && R CMD INSTALL .
```

**Comment by hcho3** [comment]
Installation questions are now welcomed at https://discuss.xgboost.ai/
