### ISSUE TITLE
'XGBRegressor' object has no attribute 'n_jobs' 

### ISSUE THREAD

**Issue by comlaterra** [dmlc/xgboost#3280]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System: NGinx Docker

Package used (python/R/jvm/C++): python

`xgboost` version used: 0.6a2

If installing from source, please provide 

RUN conda install --quiet --yes 'pandas'
RUN conda install -c conda-forge xgboost=0.6a2
RUN conda install --yes scikit-learn

Python 

If you are using python package, please provide

1. The python version and distribution: 3
2. The command to install `xgboost` if you are not installing from source

```RUN apt-get update \
  && apt-get -y install python3 python3-pip python3-dev build-essential  \
  && pip3 install --upgrade virtualenv && virtualenv venv 

RUN apt-get update --fix-missing && apt-get install -y wget bzip2 ca-certificates \
    libglib2.0-0 libxext6 libsm6 libxrender1 \
    git mercurial subversion

RUN echo 'export PATH=/opt/conda/bin:$PATH' > /etc/profile.d/conda.sh && \
    wget --quiet https://repo.continuum.io/miniconda/Miniconda3-4.3.14-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p /opt/conda && \
    rm ~/miniconda.sh

RUN apt-get install -y curl grep sed dpkg && \
    TINI_VERSION=`curl https://github.com/krallin/tini/releases/latest | grep -o "/v.*\"" | sed 's:^..\(.*\).$:\1:'` && \
    curl -L "https://github.com/krallin/tini/releases/download/v${TINI_VERSION}/tini_${TINI_VERSION}.deb" > tini.deb && \
    dpkg -i tini.deb && \
    rm tini.deb && \
    apt-get clean

ENV PATH /opt/conda/bin:$PATH

RUN conda install --quiet --yes 'pandas'
RUN conda install -c conda-forge xgboost=0.6a2
RUN conda install --yes scikit-learn```
```

## Steps to reproduce

Using a pickle without `nthreads` parameter:

```

xgb = pickle.load("...", "rb"))
xgb.predict(input)


```

Any idea what I can do to fix it?

**Comment by hcho3** [comment]
You are using outdated version of XGBoost. The latest version is 0.71.
