### ISSUE TITLE
Roadmap: improve developer documentation

### ISSUE THREAD

**Issue by RAMitchell** [dmlc/xgboost#3283]
It would be helpful to update developer documentation in the following areas:
- Explain code coverage
- Explain how to locally run CI tests e.g. lint, static analysis, google tests, python tests, R tests etc.

**Comment by hcho3** [comment]
Consolidating to #3439. A new issue should be opened if someone decides to actively work on writing the document.

**Comment by thvasilo** [comment]
I've written a [small guide here](https://discuss.xgboost.ai/t/how-to-run-tests/444/3) but it's quite hacky as it requires changing CMakeLists.txt. If there's a proper way to get Gtests to play nice and compile/run the tests I can do the write-up for the main repo.
