### ISSUE TITLE
ignoring negative weights in regression

### ISSUE THREAD

**Issue by pmendiol** [dmlc/xgboost#3285]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System:

Compiler:

Package used (python/R/jvm/C++): python

`xgboost` version used: 0.6

If you are using python package, please provide

1. The python version and distribution: 2.7.11  
2. The command to install `xgboost` if you are not installing from source

Is it possible to ignore all the negative weights like in TMVA BDT (IgnoreNegWeightsInTraining option) in xgboost? The only parameter I can see dealing with negative weights in xgboost is scale_pos_weight option but I'm not sure how to ignore such negative weights. Thanks!!

**Comment by hcho3** [comment]
For now, you should replace all negative weights with zero weights, so that corresponding data points would be ignored.
