### ISSUE TITLE
[jvm-packages] Does XGBoost spark supports prediction on baseMargin?

### ISSUE THREAD

**Issue by alice2008** [dmlc/xgboost#3289]
I checked the XGBoostModel.scala code and `predict` function is only accept `RDD[MLVector]`([Link](https://github.com/dmlc/xgboost/blob/e1f57b4417146b3a11e14619b00851c67dffa0a3/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostModel.scala#L203)). I wonder if XGBoost spark support prediction on top of `baseMargin` (as train did in XGBoost.trainWithDataFrame)? If so, could someone provide a link? It seems do not make much sense train accepting `baseMargin` but prediction does not. Thanks!

**Comment by yanboliang** [comment]
@alice2008 You've got a good point here, we are working on xgbosst-spark refactor, after it finishes, it should support set ```baseMarginCol``` when model prediction/transform. thanks!

**Comment by tqchen** [comment]
closing this for now as there is ongoing effort, we can move things to the tracking issue
