### ISSUE TITLE
How to suppress the printout of xgb.DMatrix in python wrapper?

### ISSUE THREAD

**Issue by ChenglongChen** [dmlc/xgboost#329]
The printout of xgb.DMatrix is useful for checking if features/weights/group are loaded correctly. But since I have put xgb.DMatrix in a for-loop, such printout can be a bit mess. So, is there a way to suppress it?

**Comment by tqchen** [comment]
There is a parameter called silent in the wrapper, which was not exposed. I have added it to the new python interface

**Comment by ChenglongChen** [comment]
@tqchen , thanks for pointing that out. It works.
