### ISSUE TITLE
How to find 's3://my-bucket/xgb-demo/model/0002.model'?

### ISSUE THREAD

**Issue by juWuBabaaaa** [dmlc/xgboost#3290]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System:

Compiler:

Package used (python/R/jvm/C++):

`xgboost` version used:

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`)
2. Logs will be helpful (If logs are large, please upload as attachment).

If you are using jvm package, please 

1. add [jvm-packages] in the title to make it quickly be identified
2. the gcc version and distribution

If you are using python package, please provide

1. The python version and distribution
2. The command to install `xgboost` if you are not installing from source

If you are using R package, please provide

1. The R `sessionInfo()`
2. The command to install `xgboost` if you are not installing from source

## Steps to reproduce

1.
2.
3.

## What have you tried?

1.  I tried plot_model in demo/distributed training.
2.
3.

**Comment by hcho3** [comment]
You should create a S3 bucket by logging into your own AWS account. Then upload your model into the bucket.
