### ISSUE TITLE
How to fetch several attributes from XGBClassifier?

### ISSUE THREAD

**Issue by Ani24may** [dmlc/xgboost#3292]
i am unable to fetch the threshold ,impuity values,estimator tree from xgbclassifier. In gradient boosting we have something called estimators which contains the information of each tree and nodes along with its threshold,score and everything and i am unbale to fetch those information from xgboost.

**Comment by tqchen** [comment]
Please ask questions on https://discuss.xgboost.ai/ XGBoost tree do not have these attributes exposed
