### ISSUE TITLE
error LNK1181	无法打开输入文件“Release\gpuxgboost.lib”	xgboost	C:\Users\95890\Documents\GitHub\xgboost\build\LINK	1	

### ISSUE THREAD

**Issue by weizhenzhao** [dmlc/xgboost#3299]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System:

Compiler:

Package used (python/R/jvm/C++):

`xgboost` version used:

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`)
2. Logs will be helpful (If logs are large, please upload as attachment).

If you are using jvm package, please 

1. add [jvm-packages] in the title to make it quickly be identified
2. the gcc version and distribution

If you are using python package, please provide

1. The python version and distribution
2. The command to install `xgboost` if you are not installing from source

If you are using R package, please provide

1. The R `sessionInfo()`
2. The command to install `xgboost` if you are not installing from source

## Steps to reproduce

1. I still got this error with the newest master version
2. 
![image](https://user-images.githubusercontent.com/13706689/39712058-3f9e9af6-5254-11e8-8394-934305511317.png)

3.I 've try more than four times 

git clone --recursive https://github.com/dmlc/xgboost
mkdir build
cd build
cmake .. -G"Visual Studio 15 2017 Win64"

and compile the generated code in visual studio got error in the above picture
and it only success the first time of compile in visual stuido ,
after that any compile is failed

## What have you tried?

1.
2.
3.

**Comment by hcho3** [comment]
You may want to look at http://www.picnet.com.au/blogs/guido/2016/09/22/xgboost-windows-x64-binaries-for-download/ to obtain compiled binaries of XGBoost.
