### ISSUE TITLE
how to interpret the result from binary:logitraw ?

### ISSUE THREAD

**Issue by fyears** [dmlc/xgboost#330]
I am doing a binary classification with result_a (0 in train) and result_b (1 in train). I am expecting to get the probability of being result_b for each line of X_test.

I use `objective='binary:logitraw', eval_metric='auc'`, however, the prediction returns a matrix of 10000 __* 2__ ,for a X_test with 10000 rows.

How should I interpret the result?

Here is the output:

```
array([[-0.62289798, -0.62402767],
       [-0.65141809, -0.64892763],
       [-0.65141809, -0.64892763],
       ..., 
       [-0.06447762, -0.07959807],
       [-0.30191213, -0.30507147],
       [-0.30191213, -0.30507147]], dtype=float32)
```

Thank you.

**Comment by tqchen** [comment]
you want to set not set num_class for binary classification task, it will return margin value of logistic trasnformation

**Comment by fyears** [comment]
Well... Ok... When I **unset** `num_class=2` then it works as expected. Thank you.
