### ISSUE TITLE
c++ xgboost XGBoosterLoadModelFromBuffer  XGBoosterGetModelRaw

### ISSUE THREAD

**Issue by jiangwei1995** [dmlc/xgboost#3303]
xgboost Serialize and Desrialize, Is it right to write this ?

 uint64_t out_len_model;
  const char *out_dptr = nullptr;
  XGBoosterGetModelRaw(h_booster, &out_len_model, &out_dptr);

  std::cout << "out_len_model:" << out_len_model << std::endl;

  for (int j = 0; j < out_len_model; ++j) {
    std::cout << out_dptr[j];
  }

  char b[out_len_model];
  std::copy(out_dptr, out_dptr + out_len_model, b);
  std::cout<< "b:";
  for (int j = 0; j < out_len_model; ++j) {
    std::cout << b[j];
  }
  std::cout<<"."<<std::endl;
  BoosterHandle h_booster1;
  XGBoosterLoadModelFromBuffer(h_booster1, &b, out_len_model);

**Comment by tqchen** [comment]
XGBoosterGetModelRaw gets the binary seralized data, the usage seems to be accurate. New questions are welcomed at https://discuss.xgboost.ai/

**Comment by jiangwei1995** [comment]
@tqchen Thank you. It's been settled.

**Comment by kavon** [comment]
This example is not quite right from my experience, as it leads to segfaults when loading. 

You need to initialize `h_booster1` before loading using `XGBoosterCreate`, etc.
