### ISSUE TITLE
Unexpected behaviour in predict_proba with output_margin = True

### ISSUE THREAD

**Issue by Toekan** [dmlc/xgboost#3308]
Hi, 

When using output_margin=True for predict_proba with objective = 'binary:logistic' I got an unexpected output. The probability for class 0 is calculated by 1 - prob_class_1, as seen in the code:

https://github.com/dmlc/xgboost/blob/9a8211f668ddf46d04af898f3a63bf377767b580/python-package/xgboost/sklearn.py#L580

It seems to me that this is not what you want when you ask for the raw output, so the log-odds? In my case, the base score was 0.5, so I expected the log-odds for class 0 and class 1 to be the same number with opposite signs? Or am I missing something?

Thanks!

**Comment by hcho3** [comment]
Yes, I think for raw output (`output_margin=True`), the quoted line is invalid. Can you come up with a toy example where the said line causes problems?

**Comment by hcho3** [comment]
#3343 has been merged. Thank you all!
