### ISSUE TITLE
How can I specify multi-column when using xgboost4j-spark's trainWithDataframe

### ISSUE THREAD

**Issue by SteveYanzhi** [dmlc/xgboost#3314]
![image](https://user-images.githubusercontent.com/26478715/39957497-7bc32a08-5626-11e8-8169-3d62e59fa9cf.png)

**Comment by SteveYanzhi** [comment]
I don't know how to specify multi-column

**Comment by yanboliang** [comment]
@SteveYanzhi If you use xgboost-spark, you need to assemble all your feature columns into one, and then set that column name as ```featureCol```. You can use [```VectorAssembler```](https://spark.apache.org/docs/latest/ml-features.html#vectorassembler) in Spark MLlib to assemble you features as one column of Vector type.

**Comment by tqchen** [comment]
general questions are now welcomed at https://discuss.xgboost.ai/
