### ISSUE TITLE
K80 GPU vs CPU different results, GPU slower than CPU, and crash

### ISSUE THREAD

**Issue by LSOFT123** [dmlc/xgboost#3315]
Hi,

I've just build XGBoost from GIT source (it built fine) to test GPU support under my K80 (on Google VM).
I've used exactly the same data as for CPU test and results are really weird.
With CPU: RMSE 0.23 after all iterations
'objective': 'reg:logistic',
'eval_metric': 'rmse',
'tree_method': "hist",

With GPU: RMSE 0.26 after all iterations. Duration is higher than CPU (comparable but higher)
'objective': 'gpu:reg:logistic',
'eval_metric': 'rmse',
'tree_method': "gpu_hist"
I've checked with nvidia-smi and GPU is used (around 8GB memory use)

After this test, if I run again an XGBoost on new data, it crashes.

XGBoost 0.71
Operating System: Linux Ubuntu 16.04 LTS
Python 3.6

**Comment by se-l** [comment]
Does it also crash with thrust: illegal memory access ?

**Comment by hcho3** [comment]
Can you re-run your example with the pre-built binary wheel from PyPI:
```bash
pip3 install xgboost     # should download xgboost-0.72-py2.py3-none-manylinux1_x86_64.whl
```
The binary wheel supports GPU algorithms on machines with NVIDIA GPUs.
