### ISSUE TITLE
Distributed version of xgboost：can a distributed version of xgboost be run on docker  or  kubernetes ?

### ISSUE THREAD

**Issue by AnberLu** [dmlc/xgboost#3318]
the distributed version of xgboost can be run on docker or kubernetes ?

**Comment by joesanford** [comment]
Yes, many docker images are on docker hub that come with this library pre-installed.

**Comment by AnberLu** [comment]
@joesanford  The xgboost images I looked for on dockerhub seem to be standalone versions. According to my understanding, the distributed version of xgboost must rely on frameworks such as yarn or mpi,  I haven't seen kubernetes or docker distributed yet.

**Comment by jmweiner** [comment]
I have successfully run the Spark version of xgboost in a DC/OS environment (Docker and Mesos). If you want to run a distributed version, you may want to look at Spark.

**Comment by AnberLu** [comment]
@jmweiner   thank u

**Comment by tqchen** [comment]
Close as original question is answered, new community discussions are now welcomed at https://discuss.xgboost.ai/
