### ISSUE TITLE
Updated dmlc-core submodule blocks R CRAN submission

### ISSUE THREAD

**Issue by hetong007** [dmlc/xgboost#3322]
With https://github.com/dmlc/xgboost/pull/3221, we have `dmlc-core` updated.

This change updated several headers, thus introduces the following `NOTE` to the CRAN check:

```
  Files which contain pragma(s) suppressing diagnostics:
    'src/dmlc-core/include/dmlc/any.h'
    'src/dmlc-core/include/dmlc/concurrency.h'
    'src/dmlc-core/include/dmlc/concurrentqueue.h'
    'src/dmlc-core/include/dmlc/logging.h'
```

I'm submitting R package 0.71.1 to CRAN with the old `dmlc-core` headers. However it is just a one-time compromise. 

@hcho3  Do you see these pragmas temporarily or stable? Thanks.

**Comment by hcho3** [comment]
@hetong007 The updated `dmlc-core` has an important usability improvement for R users (see #2849), so we should find a way to keep the latest `dmlc-core`.

As for the pragmas, here are the PRs that introduced them: [#236](https://github.com/dmlc/dmlc-core/pull/236), [#357](https://github.com/dmlc/dmlc-core/pull/357), [#243](https://github.com/dmlc/dmlc-core/pull/243). They all appear to be there to remove gratuitous compiler warnings. Does CRAN completely disallow removal of warnings?

**Comment by hcho3** [comment]
@hetong007 And I understand that MXNet also has R binding, and MXNet I think has pretty recent version of `dmlc-core`. We should find out how MXNet-R gets around this problem.

**Comment by hetong007** [comment]
I am with the latest `dmlc-core`, just the pragmas may block CRAN submission in the future. 

Now CRAN mark pragmas suppressing diagnostics as `NOTE`, but still won't allow a submission with this `NOTE`.

On the MXNet side, the R package has never been submitted to CRAN, since it actually has other severe issues (GPU compatibility, etc).

**Comment by hcho3** [comment]
I see two ways to move forward:

1. Submit a PR to remove pragma's. This may increase gratuitous compiler warnings on some platforms.

OR

2. Write a script that removes pragma's before CRAN submission.

**Comment by RAMitchell** [comment]
As an aside, will it be possible to submit GPU enabled binaries to CRAN? We are now producing linux binaries that can run seamlessly on GPU or non-GPU systems via Jenkins CI.

**Comment by hetong007** [comment]
@RAMitchell To have a GPU version submitted to CRAN, we may need to:

1. Have the GPU version as a separate package, i.e. `xgboost-gpu`
2. Prepare pre-built windows .dll and include in the submission package
3. make on linux as usual, and make on windows linking to the prepared .dll file(s)
4. And, most importantly, pass CRAN check on solaris (the latest 0.71.1 just [got an error](https://cran.r-project.org/web/checks/check_results_xgboost.html)).

This is just a sketch, and I've no experience submitting packages with pre-built binaries to CRAN.

**Comment by RAMitchell** [comment]
I'd like to avoid having separate packages. GPU compiled binaries run safely on systems without a GPU - they will only crash if you try to use a GPU algorithm.

We can produce windows binaries easily enough when we get Jenkins CI running for windows.

@terrytangyuan maybe you can give some advice here. I see H2O4GPU passes all of the cran checks: https://cran.r-project.org/web/checks/check_results_h2o4gpu.html. Surely we are not compiling GPU binaries for solaris?

**Comment by hcho3** [comment]
@hetong007 I looked at the five headers and all the offending #pragma's start with one of the following keywords:
```
#pragma GCC diagnostic ...
#pragma clang diagnostic ...
#pragma warning ...
```
It should be possible to write a little script that removes all lines containing these keywords. The script can be run every time `make Rpack` is run.

**Comment by hcho3** [comment]
With #3329, the command `R CMD CHECK --as-cran xgboost_0.71.1.tar.gz` now passes.

**Comment by hetong007** [comment]
It seems the maintainance effort will be minor. Thanks!

Generally speaking, the maintainance effort for the script depends on the development in `dmlc-core`, and how often we update it. Of course another factor is how often CRAN updates its policy :) 

Hope all these are at a manageable pace.

**Comment by hcho3** [comment]
I don't think we'd update the dmlc-core submodule too often. Maybe we can update it when we reach 1.0. The script would only need to be revised when someone submits a PR to update the submodule.

**Comment by terrytangyuan** [comment]
@RAMitchell h2o4gpu is a bit different since it doesn't include binaries when submitting to CRAN. Users are responsible to install the correct wheels and tests on CRAN are basically skipped.
