### ISSUE TITLE
Rabit C API pointed to by submodule in master and 0.71 missing recent fixes

### ISSUE THREAD

**Issue by davechallis** [dmlc/xgboost#3328]
I'm working on some new bindings to XGboost using the C API, and building them from a fresh checkout of XGBoost's `master` or `0.71` tag fails with:

    xgboost/rabit/include/rabit/c_api.h:35:1: error: unknown type name 'RABIT_EXTERN_C'
    xgboost/rabit/include/rabit/c_api.h:35:11: error: expected identifier or '('

On further investigation, this is because both `master` and the `0.71` tag contain `rabit` as a submodule pointing at https://github.com/dmlc/rabit/tree/a764d45cfb438cc9f15cf47ce586c02ff2c65d0f .

This is missing a lot of fixes that are in `rabit/master`, including this one (https://github.com/dmlc/rabit/commit/0b406754fa6c5d90e54d55f992045bde45f447ea#diff-d513b1282a73bf588d02ec8dd60216da), which fixes the build issue I'm having.

So I can fix the above by checking out XGboost, then doing a submodule update to pull the latest change from Rabit, then building, but it would be useful it builds worked from a fresh XGboost checkout (i.e. if the rabit submodule pointed to a more recent rabit branch/tag).

**Comment by hcho3** [comment]
Would you be able to prepare a PR that update `rabit`?
