### ISSUE TITLE
problem using custom evaluation metric (R)

### ISSUE THREAD

**Issue by mharb75** [dmlc/xgboost#333]
I'm trying to implement quadratic weighted kappa as the evaluation metric when calling xgb.cv. The custom defined function is:

```
evalerror <- function(preds, dtrain) {
  library(Metrics)
  labels <- getinfo(dtrain, "label")
  err <- ScoreQuadraticWeightedKappa(as.numeric(labels),as.numeric(preds))
  return(list(metric = "kappa", value = err))
}
```
which seems to do the job when called from the command line:
```
> evalerror(yhat, xgb.DMatrix(X, label = y))
$metric
[1] "kappa"

$value
[1] 0.8017744
```
However, when this's passed to the xgb.cv parameters (eval_metric = evalerror), I get the following error:

 Error: unknown evaluation metric type: function (preds, dtrain) 
{
    library(Metrics)
    labels <- getinfo(dtrain, "label")
    err <- ScoreQuadraticWeightedKappa(as.numeric(labels), as.numeric(preds))
    return(list(metric = "kappa", value = err))
}

**Comment by hetong007** [comment]
You need to pass it to the `feval` parameter of `xgb.cv`.

**Comment by mharb75** [comment]
That did the job. Thanks!

**Comment by hetong007** [comment]
@mharb75 Actually it is related to this issue https://github.com/dmlc/xgboost/issues/279. I will improve the interface.
