### ISSUE TITLE
[jvm-packages] check list for xgboost4j-spark refactoring

### ISSUE THREAD

**Issue by CodingCat** [dmlc/xgboost#3336]
- [x] API changes
- [x] parameter sync
- [x] add validation logic in parameter translator
- [x] Make ```XGBoostRegressor``` support setting ```group``` when training ranking model.
- [x] Make ```XGBoostClassificationModel``` and ```XGBoostRegressionModel``` support ```predictLeaf```, ```predictContrib``` and ```treeLimit```. 
- [ ] Copy data from Spark DataFrame to XGBoost4j by Arrow. (postponed)
- [x] backport PRs happened when refactoring

@yanboliang can you complete this list according to our discussion?

**Comment by yanboliang** [comment]
@CodingCat Sure, will do it asap. Thanks.

**Comment by CodingCat** [comment]
Hi, @yanboliang there is a release on June 1st, so we may have an understanding on how much work are left and decide whether we can catch up with the coming release

**Comment by yanboliang** [comment]
@CodingCat I will add followings as to-do works:
Must have:
[ ] Make ```XGBoostRegressor``` support setting ```group```.
[ ] Make ```XGBoostClassifier``` and ```XGBoostRegressor``` support ```predictLeaf```.
Good to have:
[ ] Copy data from Spark DataFrame to XGBoost4j by Arrow.

So I think it's hard to catch 0.72 on June 1st. BTW, I think the change to XGBoost-Spark is major one, it's better to get in when we bump version to 0.8? Thanks.

**Comment by CodingCat** [comment]
Hi, @yanboliang I have updated it in the thread, regarding arrow, it's a very big feature, we can put it later and we can talk about it in our next discussion

**Comment by CodingCat** [comment]
added a new item on backport PRs happened when refactoring

**Comment by hcho3** [comment]
Closing as completed
