### ISSUE TITLE
Is this include path valid?

### ISSUE THREAD

**Issue by antonovvk** [dmlc/xgboost#3340]
Hi!
I'm building xgboost tests with external building system (Bazel), all is fine except for this line:

https://github.com/dmlc/xgboost/blob/480e3fd764e10ec11bf69fa77a9af50632a10f64/tests/cpp/tree/test_param.cc#L2

It looks like one extra step back in folder structure is required.

**Comment by hcho3** [comment]
I wonder why CI tests didn't catch this problem. I've filed #3344 to fix it. Thanks!

**Comment by hcho3** [comment]
Looks like #3317 already addresses the problem. I'll go ahead and merge it.
