### ISSUE TITLE
[jvm-packages] How can I can run big data based xgboost-spark on yarn?

### ISSUE THREAD

**Issue by honey0920** [dmlc/xgboost#3345]
I have  run the spark example in the official documents using sbt tools, with no error. 
gcc version here is 4.8.2.
I can run it when the data is not too big. But when the data is 17G(kdd12 in https://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/binary.html), jvm out of memory occurs. 
`--master yarn \
--class XgboostR \
--num-executors 10 \
--executor-cores 2 \
--executor-memory 50g \`

That's my spark conf, it seems the executor memory is enough. what's worse, when I use 2G dataset, I still have OOM error. I am really troubled.

By the way, does the parameter nWorks affect the performance?

**Comment by tqchen** [comment]
general questions are now welcomed at https://discuss.xgboost.ai/
