### ISSUE TITLE
[jvm-packages] spark job failed due to too many features?

### ISSUE THREAD

**Issue by alice2008** [dmlc/xgboost#3348]
We noticed that XGBoost spark job running is quite unstable for dataset has many features (>50K features per record). I wonder if this is because of the native synchronization mechanism embedded in the XGBoost library, i.e. all partition need to load the full feature map and start calculating the candidates to find the best split? In this case, if candidates pool is too huge (>50K), it could potentially lead to failure.

The other question I have is: is it allowed for workers to fail and restart in synchronization? Currently we set `'spark.task.maxFailures': 1`. Is it okay to bump to 3 attempts perhaps.

**Comment by yanboliang** [comment]
> We noticed that XGBoost spark job running is quite unstable for dataset has many features (>50K features per record). I wonder if this is because of the native synchronization mechanism embedded in the XGBoost library, i.e. all partition need to load the full feature map and start calculating the candidates to find the best split? In this case, if candidates pool is too huge (>50K), it could potentially lead to failure.

Yes, each partition need to load the full feature map, what do you mean by unstable? What symptom did you encounter? Can you share the error log?

**Comment by CodingCat** [comment]
regarding spark.task.maxFailures, no....the assumption in xgboost4j-spark is that, if one of the workers failed, you have to restart the training

to avoid starting everything from scratch, you can set checkpoint_path and checkpoint_interval to have checkpoint built during your training (https://github.com/dmlc/xgboost/blob/master/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/CheckpointManager.scala#L127-L141)

**Comment by hcho3** [comment]
Any future discussions should be taken to https://discuss.xgboost.ai/.

Alternatively, you may choose to open a new issue to report a bug. For the report, please include an example script that we maintainers can run to re-produce the bug.
