### ISSUE TITLE
Feature request: Add a Rust API

### ISSUE THREAD

**Issue by gregsifr** [dmlc/xgboost#3351]
This is a feature request to add a Rust API to xgboost.

**Comment by hcho3** [comment]
It shouldn't be too difficult to call C functions from Rust. Every feature of XGBoost is exposed as C API functions, on which every other language bindings (Python, R, JVM, Julia) depend.

**Comment by davechallis** [comment]
I've recently started working on this, have the C API bindings just about working, then will start on some higher level functionality.

**Comment by hcho3** [comment]
Consolidating to #3439. Feel free to create a new issue if you have any update on Rust API.

**Comment by davechallis** [comment]
Happy for this to be re-opened, have made some progress on this here: https://github.com/davechallis/rust-xgboost

API is still very unstable (changing as I find out about parts of XGBoost that were previously unknown to me), but here's how some basic functionality currently looks: https://github.com/davechallis/rust-xgboost/blob/master/examples/basic/src/main.rs

**Comment by tqchen** [comment]
@davechallis Can you open a separate PR with list of actionable items? So that you can track it as a owner

**Comment by davechallis** [comment]
@tqchen Good idea, I'll try and get that together when I can. There are still quite a few things I'm experimenting with to work out the best way forward, but after that I should have a better idea of a roadmap to getting the API release.

**Comment by hcho3** [comment]
@davechallis How is your progress with Rust binding?

**Comment by davechallis** [comment]
@hcho3 Going well so far - I've got a 0.1.0 release ready, just trying to solve some packaging issue, then it should be ready. Just got back from holiday, so will hopefully try and work on that this weekend.

**Comment by liufuyang** [comment]
Is this Rust API still maintained? Also there is no official document on https://xgboost.readthedocs.io/ to show how to use it in Rust.
