### ISSUE TITLE
solution to using pip failed with 'Command "python setup.py egg_info" failed with error code 1 in ***'

### ISSUE THREAD

**Issue by pldawn** [dmlc/xgboost#3354]
My OS is centOS 3.10.0.
When I use `pip install xgboost`, I fail with 'Command "python setup.py egg_info" failed with error code 1 in ***' , look #3118 
So I try to build from source following the guide [https://xgboost.readthedocs.io/en/latest/build.html](url). After `git clone **; cd xgboost`, when I type in `make -4j` I get the error message 'g++: internal compiler error: Killed (program cc1plus)' that appears in the pip install failure message.
Then I try to type in just `make`, it succeed. `make -4j` means allowing 4 make jobs at once, so gcc@5 is needed and your os should support OpenMP. Otherwise, just use `make`.
I guess command `pip install xgboost` types in `make -4j` by default, so many people fail.

**Comment by hcho3** [comment]
I think parallel compilation failed because of memory shortage. Can you see how much memory is consumed by `make -j4`?

**Comment by hcho3** [comment]
Closing for now. For Linux systems, we began to distribute pre-built binary wheels. You may install it by running
```
pip3 install xgboost
```
