### ISSUE TITLE
Error in installing xgboost in R

### ISSUE THREAD

**Issue by shilparai** [dmlc/xgboost#336]
I am trying to download xgboost using the below code, but it is giving me an error. I have also installed RTools,but it did not work. Any solution to this problem?

devtools::install_github('dmlc/xgboost',subdir='R-package')

Downloading github repo dmlc/xgboost@master
Installing xgboost
"C:/R-31~1.0/bin/i386/R" --no-site-file --no-environ --no-save --no-restore CMD INSTALL  \
  "C:/Users/g538411/AppData/Local/Temp/RtmpCkrGCo/devtools2bcc7b0c3c50/dmlc-xgboost-733d23a/R-package"  \
  --library="C:/R-3.1.0/library" --install-tests 

* installing *source* package 'xgboost' ...
** libs

*** arch - i386
Warning: running command 'make -f "Makevars.win" -f "C:/R-31~1.0/etc/i386/Makeconf" -f "C:/R-31~1.0/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="xgboost.dll" ' had status 127
ERROR: compilation failed for package 'xgboost'
* removing 'C:/R-3.1.0/library/xgboost'
Error: Command failed (1)

**Comment by pommedeterresautee** [comment]
Which version of Rtools?

**Comment by shilparai** [comment]
I have tried below two versions of RTools, have downloaded from http://cran.r-project.org/bin/windows/Rtools/

Rtools33.exe	R 3.2.x and later
Rtools32.exe	R 3.1.x to 3.2.x

**Comment by pommedeterresautee** [comment]
Ok I use 3.2

Have you tried to install something else on R from github using devtools. Just to know if it is xgboost related or not.

Kind regards,
Michaël

**Comment by shilparai** [comment]
No, I have never used anything to install from github using devtools.
So is there any solution to it?

**Comment by hetong007** [comment]
Do you mind to update your devtools by

```r
install.packages('devtools')
```

and then try to install xgboost again?

**Comment by shilparai** [comment]
It is working now \m/..
Thanks a lot...:)

**Comment by MichaelSwanRu** [comment]
1. Download  xgboost manually:
Package ‘xgboost’ was removed from the CRAN repository.
Formerly available versions can be obtained from the archive: 
(https://cran.r-project.org/src/contrib/Archive/xgboost)

2. Try to install:
install.packages("D:/xgboost_0.3-3.tar.gz", repos = NULL, type = "source")

Warning: running command 'make -f "Makevars.win" ...  had status 127

3.
install.packages("DiagrammeR")
install.packages("data.table")
install.packages("Ckmeans.1d.dp")
install.packages("vcd")

4. Install Rtools33.exe

5. install.packages('devtools')
'https://cran.rstudio.com/bin/windows/contrib/3.2/devtools_1.8.0.zip'

5. install.packages("D:/xgboost_0.3-3.tar.gz", repos = NULL, type = "source")

Profit

**Comment by pommedeterresautee** [comment]
The version on Cran is really old. Many bugs fixed since, and new feature added. 
@hetong007 is working on making xgboost back on Cran right now. Hope it will happen soon...
