### ISSUE TITLE
obj function reg:linear versus reg:gamma

### ISSUE THREAD

**Issue by colawhite** [dmlc/xgboost#3360]
This may not be the best place to ask this question but I am really curious to find the answer.
Has anyone used xgboost with reg:gamma object function?
I examine the training curve that shows rmse across multiple trees.

An interesting observation is that gamma object function produces much smaller improvement in the first 10 trees.
My understanding is that xgboost is trying to find the best split and the first 10 trees should incur the largest improvement in RMSE. Other obj functions (linear, poisson, etc.) do not have the same phenomenon.

I have the same observation on multiple data sets.
Is this expected? or perhaps I am doing something wrong?

Thank you for reading.

**Comment by tqchen** [comment]
The new discussions are now welcomed at https://discuss.xgboost.ai/
