### ISSUE TITLE
Feature importance results sensitive to feature order

### ISSUE THREAD

**Issue by hooyeh** [dmlc/xgboost#3362]
I'm using the xgboost R package (version 0.71.1) under R 3.5.0 with Windows 10. The problem I'm working on is regression with continuous features.

In my features, I have one (x11) that is a monotone transformation of another feature (x1). When I have column subsampling turned off, I still get different feature importance results depending on where x11 is. With x11 being the first one among all the features, its gain is 0.72 and x1 doesn't show up. With it as the last one, it doesn't even show up in the list and x1 has a gain of 0.61. 

x11 was added because it is believed that this transformation should help, so x11 and x1 should not be a tie in terms of their effects on loss reduction (and the gains of the two features prove that). So it doesn't make any sense that the feature order matters so much here. This issue was raised before but one time it was claimed that it's a feature (https://github.com/dmlc/xgboost/issues/2414) and another time Tianqi said it only affects the results when there's a tie (https://github.com/dmlc/xgboost/issues/1256). Responses in neither satisfactorily address my concerns here.

**Comment by hcho3** [comment]
Can you post a script here to demonstrate "different feature importance results"?

**Comment by tqchen** [comment]
Since this is a general question, let us move the discussion to https://discuss.xgboost.ai/ 

Unfortunately, feature importance will indeed be sensitive to order of features, this is because when there are duplicated features, the selection algorithm will favor the features that occured first

**Comment by hooyeh** [comment]
@hcho3 I'll have to post the data to demonstrate this problem and unfortunately I can't do that. @tqchen The features I have are not duplicated features, they are definitely highly collinear because one is a monotone transformation of the other, but it is expected the transformed one would perform better, which is proven by some other algorithms. I was surprised xgboost was not able to pick up that subtle but important difference. In my mind, it is a deficiency that needs to be addressed.

**Comment by tqchen** [comment]
Again I would be happy to continue discuss this at the forum :)  https://discuss.xgboost.ai/
This behavior have something to do with trees
