### ISSUE TITLE
execinfo.h execinfo.h is not a standard header

### ISSUE THREAD

**Issue by hetong007** [dmlc/xgboost#3365]
Including `execinfo.h` fails compilation on Solaris for xgboost R-package.

I am opening this issue to track progress on a new CRAN submission to fix it.

@hcho3 @khotilov Do you see a quick workaround to take if off, or is it better to manually include it as part of the package?

**Comment by hcho3** [comment]
@hetong007 The `execinfo.h` header does't get included unless the `DMLC_LOG_STACK_TRACE` macro is defined. Here is the relevant snippet that defines `DMLC_LOG_STACK_TRACE`:
```cpp
/*!
 * \brief Whether to print stack trace for fatal error,
 * enabled on linux when using gcc.
 */
#if (defined(__GNUC__) && !defined(__MINGW32__)\
     && !(defined __MINGW64__) && !(defined __ANDROID__))
#if (!defined(DMLC_LOG_STACK_TRACE))
#define DMLC_LOG_STACK_TRACE 1
#endif
#if (!defined(DMLC_LOG_STACK_TRACE_SIZE))
#define DMLC_LOG_STACK_TRACE_SIZE 10
#endif
#endif
```
(Taken from [dmlc-core/include/dmlc/base.h](https://github.com/dmlc/dmlc-core/blob/master/include/dmlc/base.h#L47).)

We'll have to tighten the test so that `DMLC_LOG_STACK_TRACE` is not defined on Solaris. I'll file a PR.

**Comment by hcho3** [comment]
Here are the relevant PRs: dmlc/dmlc-core#408, dmlc/rabit#59. Once these PRs get merged, we should update the corresponding submodules.

**Comment by hetong007** [comment]
That sounds great! 
Do we have a schedule to update the submodules? I see https://github.com/dmlc/rabit/pull/59 is broken though.

**Comment by hcho3** [comment]
@hetong007 It looks like CI tests on rabit are broken. I'll take a look next week. Do you have write access to rabit?

As for updating the submodules, let's update them as soon as the fixes are in.

**Comment by hetong007** [comment]
I don't have write access to it. In this case, I will file a manual submission to CRAN for now.

**Comment by hcho3** [comment]
@hetong007 The fix has been now merged into both submodules. I've added a commit to #3372 to upgrade the submodules.
