### ISSUE TITLE
Booster.get_score()  not matching  XGBClassifier.feature_importances_

### ISSUE THREAD

**Issue by ShaniCohen** [dmlc/xgboost#3367]
`xgboost` version used: 0.6
python 3.6

I built 2 xgboost models with the same parameters: the first using Booster object, and the second using XGBClassifier implementation.
According to Booster.get_score(), feature importance order is:   f2 --> f3 --> f0 --> f1
(default importance_type='weight'. yet, same order is recevided for 'gain' and 'cover) 
But XGBClassifier.feature_importances_ order is:   f2 --> f3 --> f1 --> f0

Can anyone please help me to understand why the results are different?

thanks in advance
```
from sklearn.model_selection import train_test_split
import numpy as np
import xgboost as xgb
from sklearn import datasets
from xgboost.sklearn import XGBClassifier


iris = datasets.load_iris()
X = iris.data
y_mc = iris.target

MAX_DEPTH = 3
LEARNING_RATE = 0.1
SILENT = 1
SEED = 88
OBGECTIVE = 'multi:softprob'
NUM_CLASS = len(np.unique(y_mc))
NUM_BOOST_ROUND = 20

X_train, X_test, y_mc_train, y_mc_test = train_test_split(X, y_mc, test_size=0.2, random_state=22)

# xgboost
dtrain = xgb.DMatrix(X_train, label=y_mc_train)
dtest = xgb.DMatrix(X_test, label=y_mc_test)
params = {'max_depth': MAX_DEPTH, 'eta': LEARNING_RATE, 'silent': SILENT, 'seed': SEED,
          'objective': OBGECTIVE, 'num_class': NUM_CLASS}
watchlist = [(dtest, 'test'), (dtrain, 'train')]
bst = xgb.train(params=params, dtrain=dtrain, num_boost_round=NUM_BOOST_ROUND, evals=watchlist)
scores = bst.get_score()

# scikit-learn implementation
model = XGBClassifier(max_depth=MAX_DEPTH, learning_rate=LEARNING_RATE, random_state=SEED, objective=OBGECTIVE,
                      num_boost_round=NUM_BOOST_ROUND)
model.fit(X_train, y_mc_train)
feature_importances = model.feature_importances_
```

**Comment by sosata** [comment]
Are you sure that you are sorting the scores that you get from *get_score()* before comparing them to the ones that you get from *feature_importances_*? *get_score()* returns importance values in a dictionary format ({'f0': value, 'f1': value, ...}) but the features can be in random order.

**Comment by tqchen** [comment]
New discussions are now welcomed at https://discuss.xgboost.ai/
