### ISSUE TITLE
[jvm-packages] I cannot get xgboost4j package with the repository https://raw.githubusercontent.com/CodingCat/xgboost/maven-repo/"

### ISSUE THREAD

**Issue by jamesliu** [dmlc/xgboost#3368]
sbt package

Errors:
=====
sbt.ResolveException: unresolved dependency: ml.dmlc#xgboost4j;0.80: not found
unresolved dependency: ml.dmlc#xgboost4j-spark;0.80: not found
        at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:313)
        at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
        at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)

build.sbt
======
lazy val xgboostDependencies = Seq(
  "ml.dmlc" % "xgboost4j" % "0.80",
  "ml.dmlc" % "xgboost4j-spark" % "0.80"
)

libraryDependencies ++= xgboostDependencies.map(_ % "provided")

resolvers += "GitHub Repo" at "https://raw.githubusercontent.com/CodingCat/xgboost/maven-repo/"

**Comment by jamesliu** [comment]
@CodingCat 
What is the latest version number I should assign?
Thanks,
James

**Comment by CodingCat** [comment]
0.72-SNAPSHOT, but that branch hasn't been synced with the master branch, will do it this evening

**Comment by lev112** [comment]
this doesn't work for xgboost4j-spark 0.72 as well
(xgboost4j 0.72 works fine)

```
[warn] 	module not found: ml.dmlc#xgboost4j-spark;0.72
...
[warn] ==== maven-central: tried
[warn]   https://maven-central-asia.storage-download.googleapis.com/repos/central/data/ml/dmlc/xgboost4j-spark/0.72/xgboost4j-spark-0.72.pom
[warn] ==== sonatype-snapshots: tried
[warn]   https://oss.sonatype.org/content/repositories/snapshots/ml/dmlc/xgboost4j-spark/0.72/xgboost4j-spark-0.72.pom
[warn] ==== cloudera-repo-releases: tried
[warn]   https://repository.cloudera.com/artifactory/repo/ml/dmlc/xgboost4j-spark/0.72/xgboost4j-spark-0.72.pom
[warn] ==== GitHub Repo: tried
[warn]   https://raw.githubusercontent.com/CodingCat/xgboost/maven-repo/ml/dmlc/xgboost4j-spark/0.72/xgboost4j-spark-0.72.pom
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: ml.dmlc#xgboost4j-spark;0.72: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		ml.dmlc:xgboost4j-spark:0.72 

```

**Comment by CodingCat** [comment]
can you try again?

**Comment by jamesliu** [comment]
0.72 is OK to me.
Thanks,
James
