### ISSUE TITLE
[jvm-packages] mvn clean install creates a huge amount of exceptions in test! Help!

### ISSUE THREAD

**Issue by USCYuandaDu** [dmlc/xgboost#3373]
Hi guys,

Most exceptions are from the test in xgboost4j-spark. And I think it is related to the spark.  

## Environment info
Operating System: win7

Compiler: vs2015, anaconda, spark 2.2, mvn latest version 

Package used (python/R/jvm/C++): jvm
 
gcc versoin: gcc (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0

## Steps to reproduce

1. go into the xgboost\jvm-packages
2. set HADOOP_HOME=C:\hadoop-common-2.2.0-bin-master
3. set JAVA_HOME=C:\java8\jdk1.8
4. mvn clean install

## What have you tried?
1.  When I skip the test cases, it works. (mvn -DskipTests clean install) 
2. Most exceptions are related to the spark, so I checked the spark-shell and everything looks normal

The error log is attatched
[error log.txt](https://github.com/dmlc/xgboost/files/2086596/log.txt)

**Comment by yanboliang** [comment]
It seams ```Rabit``` doesn't work well. Can you check if ```Rabit``` was installed correctly?

**Comment by tqchen** [comment]
New discussions about installations are welcomed at https://discuss.xgboost.ai/
