### ISSUE TITLE
Meaning of feature importance score

### ISSUE THREAD

**Issue by FabHan** [dmlc/xgboost#338]
Do they have an interpretable semantics? How are they calculated? Does higher mean better?

To clarify, I'm using `cls.booster().get_fscore()` to get the scores.

**Comment by FabHan** [comment]
Also, `get_fscore()` returns fewer features than the number of features in the training data. I have 98 features and `get_fscores()` return scores of 71 features.

**Comment by tqchen** [comment]
The higher the better, get_fscore returns number of occurance of features in the ensemble

**Comment by FabHan** [comment]
Does it use their levels in the tree as weights?

Also, do you have an explanation for the situation in my second question?

Thanks.

**Comment by tqchen** [comment]
that means these feature never get selected into the trees
