### ISSUE TITLE
[jvm-packages] Spark XGBoostModel inference doesn't work with Structured Streaming

### ISSUE THREAD

**Issue by mengxr** [dmlc/xgboost#3382]
## Environment info

Package used (python/R/jvm/C++): jvm + spark

## Steps to reproduce

1. Train a XGBoostModel and then pass a streaming DataFrame to model.transform().
2. See the following error:
~~~
org.apache.spark.sql.AnalysisException: Queries with streaming sources must be executed with writeStream.start();;
...
	at org.apache.spark.sql.Dataset.rdd(Dataset.scala:2998)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostModel.produceRowRDD(XGBoostModel.scala:253)
...
...
~~~

To make transform() compatible with Structured Streaming, we should wrap the predict function as a UDF instead of calling `.rdd.mapPartitions`, which doesn't work in streaming mode. Not sure if this is an easy change due to blockwise operations.

**Comment by mengxr** [comment]
cc: @CodingCat

**Comment by CodingCat** [comment]
ack , looking into it

**Comment by mengxr** [comment]
any updates?

**Comment by amywang718** [comment]
At the moment we have a workaround that overwrites the internal transformInternal function. The following works today as a hack for regression models:
```
private def transformInternal(dataset: Dataset[_]): DataFrame = {
  val bBooster = dataset.sparkSession.sparkContext.broadcast(_booster)
  
  def asXGB_(v: Vector) = v match { 
    case v: DenseVector => XGBLabeledPoint(0.0f, null, v.values.map(_.toFloat)) 
    case v: SparseVector => XGBLabeledPoint(0.0f, v.indices, v.values.map(_.toFloat))
  }
  
  val xgbScore = (s: Vector) => { 
    val dMatrix = new DMatrix(Seq(asXGB_(s)).iterator) 
    val pred = bBooster.value.predict(dMatrix) 
    pred(0) 
  }
  
  val xgbUdf = udf(xgbScore)
  
  val df = dataset.withColumn(_originalPredictionCol, xgbUdf(col($(featuresCol))))
  bBooster.unpersist(blocking = false)
  df 
}
```

**Comment by CodingCat** [comment]
> I took a look at the implementation. Do you need Rabit.init() for each partition? 

yes, that's due to a dependency to Rabit in DMatrix

the other reason to stick with perPartition model is that, XGBoost does not support per-instance prediction very well, the cost of creating a DMatrix for each instance is super high

**Comment by yanboliang** [comment]
@CodingCat It seems the dependency to Rabit in DMatrix and low performance of per-instance prediction make too much developers/users confused. At least, I was confused when I did API refactor. What do you think of adding annotation in the code to clarify them?

**Comment by mengxr** [comment]
Is it possible to make the streaming-compatible implementation an option user can choose? We can improve the performance once we have the vectorized UDF in Scala.

**Comment by mengxr** [comment]
@tqchen Any resolution on this issue?

**Comment by CodingCat** [comment]
ah, let's reopen this one, I haven't got a chance to think about it

**Comment by CodingCat** [comment]
@mengxr I read your proposal in SPARK JIRA.  We have started planning how to implement Arrow-based DMatrix in XGBoost ....

how about having an offline sync next week ( @yanboliang, are you still having fun next week) ?

**Comment by CodingCat** [comment]
@mengxr https://github.com/dmlc/xgboost/pull/3464 this is merged

**Comment by mengxr** [comment]
Thanks!
