### ISSUE TITLE
how to rebuild in centos6.x

### ISSUE THREAD

**Issue by yuguosen** [dmlc/xgboost#3391]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System:cerntos

Compiler:

Package used (python/R/jvm/C++):jvm

`xgboost` version used:0.8

gcc is too low in centos6.x(4.4.7) for this project (5+)   but  production environment is centos 6,so i want to rebuild this project ,how to do it with an  easiest way?

**Comment by cassiuscai** [comment]
@yuguosen  I have this work done. Just following the steps in this guide https://github.com/cassiuscai/knowledge-base/blob/master/xgboost-compile/centos.md

**Comment by cassiuscai** [comment]
You need prepare the build toolchain include:
- GCC 4.8+
- CMAKE 3.0+
- Python 2.7+

If you need to build jvm packages
- JDK 1.8+
- Maven 3.0+
is also required
