### ISSUE TITLE
xgboost does a premature early stop when using a correct ndcg@xx- metric

### ISSUE THREAD

**Issue by kretes** [dmlc/xgboost#3397]
When specifying a metric ndcg@60- in evals as last metric xgboost uses it for early stopping however it stops after specified rounds nevermind training progress.

output:
```
[0]	test-ndcg@60-:0.5	validation-ndcg@60-:0.5	train-ndcg@60-:0.5	somedataset-ndcg@60-:0.5
Multiple eval metrics have been passed: 'somedataset-ndcg@60-' will be used for early stopping.

Will train until somedataset-ndcg@60- hasn't improved in 3 rounds.
[1]	test-ndcg@60-:0.5	validation-ndcg@60-:0.5	train-ndcg@60-:0.5	somedataset-ndcg@60-:0.5
[2]	test-ndcg@60-:0.63093	validation-ndcg@60-:0.5	train-ndcg@60-:0.5	somedataset-ndcg@60-:0.63093
[3]	test-ndcg@60-:0.63093	validation-ndcg@60-:0.5	train-ndcg@60-:0.5	somedataset-ndcg@60-:0.63093
Stopping. Best iteration:
[0]	test-ndcg@60-:0.5	validation-ndcg@60-:0.5	train-ndcg@60-:0.5	somedataset-ndcg@60-:0.5
```
As you can see it uses 'somedataset-ndcg@60-' as early stopping metric, but it stops too early saying that iteration [0] was the best athough from iteration [2] the metric has gone up from 0.5 to 0.63.

Everything works as expected with  'ndcg@60' as a metric but the one with '-' is more correct, see http://xgboost.readthedocs.io/en/latest//parameter.html#learning-task-parameters

It works as expected when I explicitly add maximize=True to xgb.train() method.

I guess the bug comes from the fact that here xgboost is making a split on '-' and it doesn't fit the corrected metric name:
https://github.com/dmlc/xgboost/blob/master/python-package/xgboost/callback.py#L195

our params:
```
{
     "max_depth": 6,
     "tree_method": "hist",
     "subsample": 0.5,
     "colsample_bytree": 1,
     "objective": "rank:pairwise",
     "eval_metric": ["ndcg@60-"],
     "silent": 0,
     "seed": 42,
     "booster": "gbtree"
    }
```

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System:
linux
Compiler:

Package used (python/R/jvm/C++):
python
`xgboost` version used:
0.72

If you are using python package, please provide

1. The python version and distribution: 3.5.2
2. The command to install `xgboost` if you are not installing from source
pip

**Comment by kretes** [comment]
@tqchen I saw this massive issue closing and I can understand the reasons behind it - one should concentrate on the most important things. 

Here this issue is a bug indeed not a discussion, although a minor one.

**Comment by ericxsun** [comment]
I met the same error, while using self-defined feval function.

```
def eval_f1(predictions, data):
    labels = data.get_label()
    tp, fp, fn, tn = cal_cm(labels, predictions)
    p = tp * 1.0 / (tp + fp)
    r = tp * 1.0 / (tp + fn)
    f1 = p * r * 2 / (p + r)

    return 'f1', f1
```
&
```
params = ....
 params['eval_metric'] = ['error', 'auc']
xgb.train(params, train_X_y, 300, eval_list, early_stopping_rounds=30, feval=eval_f1)
```

Log:
```
...
Multiple eval metrics have been passed: 'eval-f1' will be used for early stopping.
....
[30]	train-error:0.10999	train-auc:0.947616	eval-error:0.111185	eval-auc:0.94635	train-f1:0.818907	eval-f1:0.817117
Stopping. Best iteration:
[0]	train-error:0.130154	train-auc:0.919468	eval-error:0.130307	eval-auc:0.919385	train-f1:0.786085	eval-f1:0.786137
```
