### ISSUE TITLE
Segmentation fault in get_fscore()

### ISSUE THREAD

**Issue by FabHan** [dmlc/xgboost#340]
```
In [22]: booster.get_fscore('fmap.txt')
*** stack smashing detected ***: python terminated
[1]    38593 segmentation fault (core dumped)
```

Here's the contents of my `fmap.txt` file:

```
0 my_f0 int
1 my_f1 int
...
232 my_f232 int
233 my_f233 int

```

**Comment by tqchen** [comment]
It would be great if you can provide a complete script and data(or) to reproduce the error

**Comment by tqchen** [comment]
I am closing this for now. Please reopen the issue if you have any updates

**Comment by ShiehShieh** [comment]
Hi, I have the same problem as FabHan:
when I called this function on my Ubuntu, the error message is as follows:

    In [50]: clf.get_fscore('columns.txt')
    [1]    30155 segmentation fault (core dumped)  ipython

and this is on my Mac:

    In [23]: clf.get_fscore('columns.txt')
    [1]    37290 segmentation fault  ipython --pylab

the file format of the fmap.txt is the same as [https://github.com/dmlc/xgboost/tree/master/demo/binary_classification](https://github.com/dmlc/xgboost/tree/master/demo/binary_classification)

        params = {
            'max_depth': 8,
            'eta': 0.1,
            'colsample_bytree': 0.5,
            'min_child_weight': 2,
            'silent': 1,
            'nthread': 2,
            } # The same problem occurred when I use default setting. (i.e. params = {})
    num_round = 10
    x_train = xgb.DMatrix(x_train, label=np.log1p(y_train))
    x_test = xgb.DMatrix(x_test)
    evallist  = [(x_train,'eval')] # TODO get more data.
    clf = xgb.train(params, x_train, num_round, evals=evallist, early_stopping_rounds=10)
    clf.get_fscore('columns.txt')

However, if I omit the 'fmap'(i.e. columns.txt) and use 'clf.get_fscore()' only, the function will not crash. But I need to map the feature id to feature name so as to evaluate the feature importance.
