### ISSUE TITLE
Python list function work differently on strings

### ISSUE THREAD

**Issue by wenduowang** [dmlc/xgboost#3407]
The code below may fail when the input to list() function is string type, e.g. list('abcda') = ['a', 'b', 'c', 'd', 'a'], resulting in duplicate values, thus ValueError: feature_names must be unique.

xgboost/python-package/xgboost/core.py line 741, 780
feature_names = list(feature_names)
feature_types = list(feature_types)

**Comment by hcho3** [comment]
@wenduowang Can you submit a PR that checks whether feature_names and feature_types are single strings?
