### ISSUE TITLE
Incorrect handling of scipy.sparse matrices?

### ISSUE THREAD

**Issue by jseabold** [dmlc/xgboost#341]
After much digging, it looks like there's an issue on predicting with scipy.sparse matrices. I think my training worked, but now I'll need to go back and check everything. Any other ideas on trying to debug this? Anything I'm missing?

Using the underlying dense array.
```
In [149]: model.predict_proba(X_test_subset.tocsr()[:5, :].A)
Out[149]:
array([[ 0.16795158,  0.83204842],
       [ 0.1645692 ,  0.8354308 ],
       [ 0.19039142,  0.80960858],
       [ 0.18842077,  0.81157923],
       [ 0.21735471,  0.78264529]], dtype=float32)
```

Scoring with a CSR matrix.

```
In [150]: model.predict_proba(X_test_subset.tocsr()[:5, :])
Out[150]:
array([[ 0.40842509,  0.59157491],
       [ 0.40842509,  0.59157491],
       [ 0.40842509,  0.59157491],
       [ 0.40842509,  0.59157491],
       [ 0.40842509,  0.59157491]], dtype=float32)
```

I'll try updating scipy...

```
In [164]: from scipy import __version__

In [165]: print(__version__)
0.14.1
```

**Comment by jseabold** [comment]
Upgrading scipy did not change anything.

**Comment by tqchen** [comment]
I would suggest go back to the old API and see what is going on, specifcally the one in the basic_walthrough.py

**Comment by jseabold** [comment]
Ah, it has something to do with how missing values are handled in sparse matrices with `DMatrix`.

```
In [57]: model._Booster.predict(DMatrix(X_test_subset.tocsc()[:5, :], missing=np.nan))
Out[57]: array([ 0.94607931,  0.95592064,  0.52279431,  0.93196493,  0.95121199], dtype=float32)

In [58]: model._Booster.predict(DMatrix(X_test_subset.tocsc()[:5, :].A, missing=np.nan))
Out[58]: array([ 0.16589592,  0.12011375,  0.14782116,  0.12367617,  0.11791431], dtype=float32)
```

What does a default missing value of 0 mean?

```
In [59]: model._Booster.predict(DMatrix(X_test_subset.tocsc()[:5, :].A, missing=0.0))
Out[59]: array([ 0.94607931,  0.95592064,  0.52279431,  0.93196493,  0.95121199], dtype=float32)

In [60]: model._Booster.predict(DMatrix(X_test_subset.tocsc()[:5, :], missing=0.0))
Out[60]: array([ 0.94607931,  0.95592064,  0.52279431,  0.93196493,  0.95121199], dtype=float32)
```

**Comment by jseabold** [comment]
You can replicate this with `basic_walkthrough.py`

```
In [2]: dtrain1 = xgb.DMatrix(npymat, label=labels, missing=np.nan)

In [3]: dtrain2 = xgb.DMatrix(npymat, label=labels)

In [4]: bst.predict(dtrain1)
Out[4]:
array([ 0.01241208,  0.01241208,  0.01241208, ...,  0.01241208,
        0.01241208,  0.01241208], dtype=float32)

In [5]: bst.predict(dtrain2)
Out[5]:
array([ 0.92392391,  0.28583017,  0.28583017, ...,  0.05169873,
        0.05169873,  0.05169873], dtype=float32)
```

**Comment by tqchen** [comment]
missing is the special value for dense matrix when feed into xgboost. Basically every value that equals missing is treated as missing and the matrix will be converted into a sparse matrix that only contains non-missing entries before prediction.

**Comment by jseabold** [comment]
It sounds like the use of sparse matrices is only a convenience to indicate missingness rather than a way to save space if I actually have some sparse (as in many zeros) features. This was not at all obvious to me.

What are the implications for training if I pass in already sparse matrices? The same logic?

It's not necessarily the case for me that sparsity and missingness are the same thing. Ie., I might have a big sparse matrix with entries specifically encoded as `-99` or `nan` to indicate missingness as distinct from a value I know is zero.

```
1, 0, 0, 0, 1.5
0, 1, 0, 0, 2.3
0, 0, 0, 1, nan
0, 0, 1, 0, 1.2
```

If I pass this as a sparse matrix to the scikit-learn API, it sounds like the `missing` parameter is ignored, zeros are treated as missing values, and then something (?) happens to the `np.nan` values in training? I assume they're always treated as the `no` branch in the tree

```
In [110]: np.nan < 1.5
Out[110]: False

In [111]: np.nan > 1.5
Out[111]: False
```

I'm basically trying to figure out if I need to go back and redo work, and it sounds like I do since my assumptions for training weren't right.

**Comment by tqchen** [comment]
The missing was only used  when input was dense, and ignored in sparse case(maybe we should put an warning on this).  When there are a lot of 0 in sparse matrix, this will save the space as well as computation.  

But current algorithm was not designed to handle missing entry in sparse matrix, and they should be dropped beforehand.

**Comment by tqchen** [comment]
The thing was, most of the time, each column will either contain missing value or contain a lot of 0 (1-hot encoding).  So long as the "missing" in that column only contains one meaning(0 or missing) and the DMatrix is consistently constructed, then the algorithm will behave correctly and efficiently.

**Comment by 121onto** [comment]
Bump.

**Comment by 121onto** [comment]
I agree with @jseabold that xgboost's behavior is undesirable.  Scipy's sparse matrix class handles NaNs in a reasonable way.  @tqchen, why not follow their lead?  Here is an example:

```
>>> import numpy as np
>>> import scipy.sparse as sp
>>> X_train = np.array([[ 1., -1.,  np.nan],
...     [ 2.,  0.,  0.],
...     [ 0.,  1., -1.]])
>>> sp.csr_matrix(X_train)
<3x3 sparse matrix of type '<type 'numpy.float64'>'
	with 6 stored elements in Compressed Sparse Row format>
>>> sparse.nnz
6
>>> sparse[0,2]
nan
```

Sparse matrices are useful when storing dummy variables, with many zero values.  It would be nice if we could benefit from the space saving advantages of sparse arrays and yet still support missing variables.  

For context, here is what xgboost does to initialize a matrix from a sparse matrix:

```
class DMatrix(object):
    def __init__(self, data, label=None, missing=0.0,
                 weight=None, silent=False, feature_names=None):

    ...
    elif isinstance(data, scipy.sparse.csr_matrix):
            self._init_from_csr(data)
    ...

    def _init_from_csc(self, csc):
        """
        Initialize data from a CSC matrix.
        """
        if len(csc.indices) != len(csc.data):
            raise ValueError('length mismatch: {} vs {}'.format(len(csc.indices), len(csc.data)))
        self.handle = ctypes.c_void_p()
        _check_call(_LIB.XGDMatrixCreateFromCSC(c_array(ctypes.c_ulong, csc.indptr),
                                                c_array(ctypes.c_uint, csc.indices),
                                                c_array(ctypes.c_float, csc.data),
                                                len(csc.indptr), len(csc.data),
                                                ctypes.byref(self.handle)))
```

Note that the missing parameter is not used.  A value of np.nan is treated just like any other value (whatever that means) and zeros are treated like missing values.

In contrast, xgboost seems to use the missing parameter when initializing a matrix from a numpy array:

```
    elif isinstance(data, np.ndarray):
            self._init_from_npy2d(data, missing)
    ...
    def _init_from_npy2d(self, mat, missing):
        """
        Initialize data from a 2-D numpy matrix.
        """
        if len(mat.shape) != 2:
            raise ValueError('Input numpy.ndarray must be 2 dimensional')
        data = np.array(mat.reshape(mat.size), dtype=np.float32)
        self.handle = ctypes.c_void_p()
     _check_call(_LIB.XGDMatrixCreateFromMat(data.ctypes.data_as(ctypes.POINTER(ctypes.c_float)),
                                                mat.shape[0], mat.shape[1],
                                                ctypes.c_float(missing),
                                                ctypes.byref(self.handle)))
```

**Comment by tqchen** [comment]
@121onto I agree this is confusing. This was rooted from the original design idea to support sparse matrices, which naturally extends to missing as missing can be treated as the entries not presented.

As a solution for now now, if you fill the missing nan value with zero. 
It will behave correctly in the desirable way and give you accurate prediction, despite this may sounds a bit strange

As you suggested, sparse matrix is used to support dummy variables, where a lot of zeros are occured. It is equivalent to treat these zeros as "missing". Normally, you won't have both zero and missing in one column. (in dummy you have zero, in dense column you might have missing). So that treatment won't mix the two incorrectly.
