### ISSUE TITLE
[jvm-packages] buildGroups is unnecessarily expensive

### ISSUE THREAD

**Issue by a-johnston** [dmlc/xgboost#3412]
Added in https://github.com/dmlc/xgboost/pull/3387, the method relies on a loop followed by two `Seq.apply` calls:
```scala
while (i < groups.length) {
    if (groups(i) != groups(i - 1)) {
...
```
which for lazily generated sequences (when I checked, `groups` was an instance of `scala.collection.immutable.Stream$Cons`) is quadratic. This behavior can be seen by comparing the running times of the following accesses:
```scala
val s = Stream.continually(0).toSeq
s(0)
s(1000000)
s(100000000)
```
(I ctrl-C'd before that last one finished on my machine)

The method `buildGroups` should do a single pass and not rely on index access.

**Comment by CodingCat** [comment]
@a-johnston are you interested in filing a PR?

**Comment by a-johnston** [comment]
Yep, in progress
