### ISSUE TITLE
[jvm-packages] Is there a way to get private _booster in XGBoostClassificationModel in xgboost4j-spark 0.8?

### ISSUE THREAD

**Issue by 18321171817** [dmlc/xgboost#3421]
I just upgrade the jvm-package from 0.7 to 0.8, but the api has changed a lot. I used to call the getter function in 0.7 to get the private _booster variable in 0.7. In version 0.8, it seems there is no getter function in XGBoostClassificationModel. Is there anyway to get the private _booster variable? 
Reference #985

**Comment by CodingCat** [comment]
@yanboliang I think it is not that bad to expose this, 

if the user has usage scenario beyond save the model and load in other lang binding, the exportToLocal method is not enough

**Comment by yanboliang** [comment]
Send out #3428
