### ISSUE TITLE
Does early stopping consider a given window for the objective decrease or it refreshed by any recent improvement?

### ISSUE THREAD

**Issue by erogol** [dmlc/xgboost#343]
I guess early stopping only considers the recent values for  the objective values improvement. For instance if I define early_stopping_rounds=3 then the run will continue in the following situation:

loss: 1
loss: 3
loss: 2
loss: 4
loss: 3
...

However it should stop since there is no improvement for the best result in the windows of 3.

**Comment by hetong007** [comment]
It only considers the most recent results. In my personal experiences on xgboost, the oscillation is usually not indicating the stopping point. Sometimes it is because `eta` is too large so that it is more difficult to find the minimum.
