### ISSUE TITLE
[jvm-packages]XGBoostClassifier and XGBoostClassificationModel conversion

### ISSUE THREAD

**Issue by 18321171817** [dmlc/xgboost#3433]
_val sparkSession = SparkSession.builder().config(sc.getConf).getOrCreate()
val xgboostModel = new XGBoostClassifier(paramMap)
      .setNumRound(numRound)
      .setNumWorkers(nWorkers)
      .setEvalMetric("auc")
      .setUseExternalMemory(externalMemory)
      .setMissing(-999.0f)
xgboostModel.fit(sparkSession.createDataFrame(samples))_

Above is the code I used to generate a XGBoostClassifier class instance, now i want to call low-level APIs on native booster, such as "getFeatureScore". The XGBoostClassficationModel class now does provide a "nativeBooster", but I can't figure out a way to convert a XGBoostClassifier class instance to a XGBoostClassficationModel class instance...Or is there any better way to achieve the goal?

**Comment by CodingCat** [comment]
the return value of fit() should be what you are looking for
