### ISSUE TITLE
PyPI 0.72 artifacts overwritten with same version number

### ISSUE THREAD

**Issue by StephenWithPH** [dmlc/xgboost#3449]
https://pypi.org/project/xgboost/#files shows that `xgboost-0.72-py2.py3-none-manylinux1_x86_64.whl` was uploaded on 20180704:

![screen shot 2018-07-05 at 17 31 46](https://user-images.githubusercontent.com/2990492/42354100-55225608-8079-11e8-985d-3e736270cdd0.png)

I believe you unintentionally overwrote the 0.72 release artifacts from the 6/1 release (https://github.com/dmlc/xgboost/releases/tag/v0.72).

This breaks tools that expect semantically-versioned artifacts to remain unchanged:

```
THESE PACKAGES DO NOT MATCH THE HASHES FROM Pipfile.lock!. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    xgboost==0.72 from https://files.pythonhosted.org/packages/76/ec/ffab3d5e20b93a7223f07e9bb0eb5f58570a47931be2a506c35b9b37c773/xgboost-0.72-py2.py3-none-manylinux1_x86_64.whl#sha256=374c92f0cc6aee622fdef0f7a09ce6248b3c59397461407d002897273f4f202e:
        Expected sha256 44c2a0e26e3914bd136537d0a7cb9049a17a4fc5630a834b470c9471eef98123
             Got        374c92f0cc6aee622fdef0f7a09ce6248b3c59397461407d002897273f4f202e
```

If possible, please cut a 0.72.1 release to restore order in the force.

FYI- I couldn't find evidence in the publicly-viewable build logs from the two commits on 7/4 to show where a build server uploaded these artifacts. I did find a hint that this might be a manual operation: https://github.com/dmlc/xgboost/blob/master/python-package/prep_pip.sh#L10-L11

**Comment by hcho3** [comment]
> I believe you unintentionally overwrote the 0.72 release artifacts from the 6/1 release.

I don't think this is the case, because I am adding a pre-built binary wheel in addition to the existing source tarball. Both the wheel and source tarball use the identical source of truth. You can avoid the hash problem by disabling the download of binary wheels.

> I did find a hint that this might be a manual operation.

This is correct.

**Comment by StephenWithPH** [comment]
Can you speak at all to the screenshot from PyPI? It shows that `xgboost-0.72-py2.py3-none-manylinux1_x86_64.whl` was uploaded on *Jul 4, 2018*.

The hash (also on PyPI) for that is `374c92f0cc6aee622fdef0f7a09ce6248b3c59397461407d002897273f4f202e`.

The prior hash for this artifact was `44c2a0e26e3914bd136537d0a7cb9049a17a4fc5630a834b470c9471eef98123` and had been stable since no later than `Sat, 2 Jun 2018 08:53:17 -0700` until no earlier than `Thu, 28 Jun 2018 14:33:09 -0700`. (Looking at my build metadata).

FYI- we're using [Pipenv](https://docs.pipenv.org/) in the most vanilla way possible; it raised the error that the contents of the pinned `0.72` version PyPI package had changed.

**Comment by hcho3** [comment]
> Can you speak at all to the screenshot from PyPI? It shows that xgboost-0.72-py2.py3-none-manylinux1_x86_64.whl was uploaded on Jul 4, 2018.

The binary wheel was uploaded on July 4, 2018. Prior to that, only source tarball was available and the binary wheel had not been ready (because it was not done testing then).

> The prior hash for this artifact was 44c2a0e26e3914bd136537d0a7cb9049a17a4fc5630a834b470c9471eef98123

There are now **two** artifacts instead of one, and the hash for the source tarball remains the same as before.

**Comment by hcho3** [comment]
@StephenWithPH However, since `pip` by default favors binary wheels over source tarball, I can see how `xgboost==0.72` would appear to have different hash. Would you be okay if I went ahead and renamed the wheel to `xgboost-0.72.1-py2.py3-none-manylinux1_x86_64.whl`?

**Comment by StephenWithPH** [comment]
> There are now two artifacts instead of one, and the hash for the source tarball remains the same as before.

> ...

> since pip by default favors binary wheels over source tarball

It's all starting to make sense! Thank you for connecting the dots.

Regarding...

> Would you be okay if I went ahead and renamed the wheel to xgboost-0.72.1-py2.py3-none-manylinux1_x86_64.whl?

**yes**. If I'm thinking through this correctly, that will result in pulling the unchanged `0.72` tarball again.

Let me know when you do so, and I can test how `Pipenv` handles it.

**Comment by hcho3** [comment]
@StephenWithPH It looks like the best way out is to release 0.72.1 for good ("If possible, please cut a 0.72.1 release to restore order in the force."). We will consider version 0.72 as "broken" and take it down from PyPI. I apologize for breaking your build, and from now on, all artifacts for a single version will be made available on the same day. We will make a new release whenever a new artifact is added.

**Comment by ianlini** [comment]
Why did you delete 0.72? I think the original 0.72 binary is totally OK. There is no need to delete 0.72 and add 0.72.1.
The error message from Pipfile is normal, and it can be solved by updating the hash in the lock file. I think updating hash is easier than updating version.
Besides, we cannot expect the package maintainer to upload all files at the same moment for a release. It's impossible, so the mechanism in Pipfile should support this kind of file change.

**Comment by StephenWithPH** [comment]
@hcho3 
>looks like the best way out is to release 0.72.1 for good
We took 0.72.1 this morning, and all is well.

Thank you for chasing this down so quickly.
