### ISSUE TITLE
Test MetaInfo.LoadQid Failed after I updated the xgboost code. 

### ISSUE THREAD

**Issue by USCYuandaDu** [dmlc/xgboost#3450]
Hi,
when I run the test case, it failed. 

unknown file: Failure
C++ exception with description "[10:49:23] src/data/./row_block.h:177: Check failed: offset.back() == value.size() || value.size() == 0 

Stack trace returned 10 entries:
[bt] (0) 0   xgboost_test                        0x000000010790a788 dmlc::StackTrace() + 2936
[bt] (1) 1   xgboost_test                        0x0000000107909879 dmlc::LogMessageFatal::~LogMessageFatal() + 121
[bt] (2) 2   xgboost_test                        0x000000010859c39c dmlc::data::RowBlockContainer<unsigned int, float>::GetBlock() const + 636
[bt] (3) 3   xgboost_test                        0x00000001085afc81 dmlc::data::ThreadedParser<unsigned int, float>::Next() + 193
[bt] (4) 4   xgboost_test                        0x0000000107cecbd9 xgboost::data::SimpleCSRSource::CopyFrom(dmlc::Parser<unsigned int, float>*) + 249
[bt] (5) 5   xgboost_test                        0x0000000107c9e0bd xgboost::DMatrix::Create(dmlc::Parser<unsigned int, float>*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 1613
[bt] (6) 6   xgboost_test                        0x0000000107c98393 xgboost::DMatrix::Load(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 34707
[bt] (7) 7   xgboost_test                        0x00000001078f9884 MetaInfo_LoadQid_Test::TestBody() + 3124
[bt] (8) 8   xgboost_test                        0x000000010861e7ee void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) + 126
[bt] (9) 9   xgboost_test                        0x00000001085e495b void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) + 123

" thrown in the test body.
[  FAILED  ] MetaInfo.LoadQid (94 ms)

**Comment by USCYuandaDu** [comment]
@hcho3 @tqchen

**Comment by USCYuandaDu** [comment]
The rest of test cases were passed.

**Comment by hcho3** [comment]
Try running `git submodule update --init --recursive`.

**Comment by USCYuandaDu** [comment]
@hcho3 Thank you，but I'm in the fork,  
```» git remote -v                                                                                          
origin	https://github.com/USCYuandaDu/xgboost.git (fetch)
origin	https://github.com/USCYuandaDu/xgboost.git (push)
upstream	https://github.com/dmlc/xgboost.git (fetch)
upstream	https://github.com/dmlc/xgboost.git (push)
```
so what I did before was
```
 git fetch upstream
git merge upstream/master
```
Any idea about this ? 
Bests,
Yuanda

**Comment by USCYuandaDu** [comment]
@hcho3  I've tried 
```
git fetch --recurse-submodules upstream
```
But It stills now work

**Comment by hcho3** [comment]
Can you clone the xgboost repo fresh and run tests?
`git clone --recursive https://github.com/dmlc/xgboost`

**Comment by USCYuandaDu** [comment]
@hcho3 Yeah, I've tried this, It works. So the problem is on my side. But I've added some codes on my fork, so I want to update it. Do you know how to fetch recursively?

**Comment by hcho3** [comment]
If you did `git merge upstream/master`, you should be able to run `git submodule update`.

Can you run `git log --stat` and search the commit that added the qid format support?

**Comment by USCYuandaDu** [comment]
Yes, when I merged and typed git submodule update nothing happened.
And I could find the commit 
```
commit 0cf88d036fb46c59926568340ac8d7b38d4c3ec6
Author: liuliang01 <liu_bright@foxmail.com>
Date:   Sun Jul 1 04:24:03 2018 +0800
```

**Comment by USCYuandaDu** [comment]
I reset the previous commit, but it stills not work, it's weird.

**Comment by hcho3** [comment]
For now, you can manually set the the commit of dmlc-core submodule as follows:
```
cd dmlc-core
git fetch origin master
git checkout 459ab734d15acd68fd437abf845c7c1730b5a38f
```

Future discussion is welcome at the user forum https://discuss.xgboost.ai/.
