### ISSUE TITLE
[jvm_packages] `weight_col` for spark is not working as expected for ranking tasks  

### ISSUE THREAD

**Issue by ngoyal2707** [dmlc/xgboost#3454]
`weight` for ranking task is supposed to be weight by `group` as per this PR: https://github.com/dmlc/xgboost/pull/3379.

But the current way of ingesting `weight_col` in spark APIs is as column in dataframe, so it expects to provide weights by instance. The [python APIs to provide weight](https://xgboost.readthedocs.io/en/latest/python/python_api.html#xgboost.DMatrix.set_weight) is different and expects to be directly provided weights as numpy array. So the [source code](https://github.com/dmlc/xgboost/blob/master/src/objective/rank_obj.cc#L96) expects `len(weight) == ngroups`, otherwise the loop will be logically incorrect.  

One way to solve it could be:

1) Change `weight` to be passed as `param` rather than with `DF`, which was how old `group_data` was working. But that will require changing the APIs and might not be backward compatible with current way. And also is not good for non-ranking tasks which actually require per-instance weighing.
Also passing list of millions cardinality as param may be kinda weird. 

@hcho3 , @CodingCat any other suggestions?  

The current workaround for me is very hacky, where I each loop over each paritions myself and add `weight_col` such that, first `ngroups` entry in each partition are correct and rest are `dummy`. And then I will make sure [this](https://github.com/dmlc/xgboost/blob/master/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala#L255) never gets called.

**Comment by CodingCat** [comment]
> Change weight to be passed as param rather than with DF, which was how old group_data was working

this is to be very error-prone once there is a shuffle and that's why we have the new version of group_data passing mechanism, 

I think we could call [setWeight](https://github.com/dmlc/xgboost/blob/aa90e5c6cec2a9a4d1e18ecb7f3d5b9108dfaaa6/jvm-packages/xgboost4j/src/main/scala/ml/dmlc/xgboost4j/scala/DMatrix.scala#L116) when we [build the group info for DMatrix](https://github.com/dmlc/xgboost/blob/aa90e5c6cec2a9a4d1e18ecb7f3d5b9108dfaaa6/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala#L354) to resolve the issue (didn't think with many details)

**Comment by a-johnston** [comment]
Hi, I ran into this same issue and came to the same possible solution of calling `setWeight` @CodingCat suggested in the above post. I think it would work but there is ambiguity around per-group weights when dealing with a per-instance weight column. Should an error be raised if the weights aren't all equal for instances in the same group? Should the first weight be used irrespective of the other weights? Should the positive label instance weight be used?

If you have a particular opinion on how it should be implemented, I can go ahead and add the logic for it. Personally, I'm partial to the first option (raising an error if weights within a group aren't equal) as it would force the user to be aware of how their data is being used.

**Comment by CodingCat** [comment]
fixed in https://github.com/dmlc/xgboost/pull/4118
