### ISSUE TITLE
[jvm_packages]Can you add watchlist features to XGBoost4j-Spark

### ISSUE THREAD

**Issue by 18321171817** [dmlc/xgboost#3457]
I noticed that in XGBoost4j-Spark source code, the train method of the XGBoostClassifier class doesn't have the watchlist features. While in XGBoost4j, the watchlist features is implemented. Do you have plans to add it to the XGBoost4j-Spark package? Also, any plans to add cross validation to XGBoost4j-Spark?

**Comment by hcho3** [comment]
The watchlist feature is already in the feature request list #3439.

**Comment by hcho3** [comment]
If you'd like a detailed discussion on the proposed feature, feel free to post at https://discuss.xgboost.ai/. We appreciate your contribution.

**Comment by hcho3** [comment]
I went ahead and migrated your post to https://discuss.xgboost.ai/t/jvm-packages-watchlist-feature-for-xgboost4j-spark/39, since it may be interest to other people.

**Comment by hcho3** [comment]
@18321171817 There is a watchlist feature in the works: #3544.

**Comment by hcho3** [comment]
Actually never mind. The linked PR was watchlist for XGBoost4J, not XGBoost4J-Spark.
