### ISSUE TITLE
how to use custom objective with XGBoostRegressor of spark?

### ISSUE THREAD

**Issue by yuezZYMSQTD** [dmlc/xgboost#3468]
In version 0.7, I can use XGBoost.trainWithDataFrame with parameter obj where the type of obj is ml.dmlc.xgboost4j.scala.ObjectiveTrait. But in the newest version, I can only use XGBoostRegressor().setObjective(value: String) where the type is string. How can I use custom objective with XGBoostRegressor of spark in the newest version? My input has to be a DataFrame/DataSet.

**Comment by hcho3** [comment]
@yanboliang @CodingCat How does the user set the variable `$(customObj)` in https://github.com/dmlc/xgboost/blob/2f8764955cb139d65646dc21710f11e92e6dfd68/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostRegressor.scala#L181 ?

**Comment by yanboliang** [comment]
@yuezZYMSQTD You can use the old way to set custom obj in the newest version. Suppose you have implemented own objective and eval as [this example](https://github.com/dmlc/xgboost/blob/master/jvm-packages/xgboost4j-example/src/main/scala/ml/dmlc/xgboost4j/scala/example/CustomObjective.scala), you can use the following way to set custom obj and eval: 
```
val paramMap = Map("eta" -> "1", "max_depth" -> "6", "silent" -> "1", "num_round" -> 5, "custom_obj" = new LogRegObj, "custom_eval" = new EvalError)
val xgb = new XGBoostClassifier(paramMap)
val model = xgb.fit(trainingDF)
```
Or after [this PR](https://github.com/dmlc/xgboost/pull/3486) merged, you can also use the following way:
```
val xgb = new XGBoostClassifier().setCustomObj(new LogRegObj).setCustomEval(new EvalError)
val model = xgb.fit(trainingDF)
```

**Comment by hcho3** [comment]
@yanboliang Thanks for the update!

@yuezZYMSQTD If you have questions in the future, feel free to post at the user forum https://discuss.xgboost.ai/.

**Comment by yuezZYMSQTD** [comment]
thanks
