### ISSUE TITLE
Can not install R pacage

### ISSUE THREAD

**Issue by StevenLOL** [dmlc/xgboost#347]
##1) can not install xgboost R in cran
Removed from cran
##2) can not install via devtools::install_github('dmlc/xgboost',subdir='R-package')
Because devtools depends on reversions , reversions depends xml2 which was unable to installed.

##3) can pack local files and install?

**Comment by hetong007** [comment]
One solution is
1. Clone the current repository and set your workspace to `xgboost/R-package/`
2. Run `R CMD INSTALL --build .` in terminal to get the tarball.
3. Run `install.packages('path_to_the_tarball',repo=NULL)` in R to install.

Anyway the most convenient solution is still find a way to install `devtools`.

**Comment by StevenLOL** [comment]
Thanks

**Comment by startakovsky** [comment]
@hetong007 @StevenLOL I am experiencing issues installing.... I ran your stuff on `trusty_boost`.

**Comment by hetong007** [comment]
Can you give more hint on the issue? Like what is your command, what is your operating system and what is the error message.

**Comment by startakovsky** [comment]
Okay basically I was redirected here from another site with the issue that xml2 is not there. I am trying to install rversions in order to install devtools.
