### ISSUE TITLE
API usage error: want to use plotting API but failed and it raised an ImportError

### ISSUE THREAD

**Issue by zhongqin0820** [dmlc/xgboost#3471]
Environment:
- Ubuntu 16.04
- Python 2.7 or Python 3.5
- Pip 10.0.1

Issues:
When i use plotting API, it raised an `ImportError : You must install matplotlib to plot ...`

But I have already installed it.

**Comment by hcho3** [comment]
> But I have already installed it.

Make sure to use the right `pip` to install `matplotlib`. Run the following:
```
python2 -m pip install matplotlib    # if you are using Python 2
python3 -m pip install matplotlib    # if you are using Python 3
```

Future questions are welcome at the forum https://discuss.xgboost.ai/.

**Comment by zhongqin0820** [comment]
Thanks, @hcho3 .
I definitely install matplotlib under both of the python version. But i didn't install other related dependencies.
Anyway, already solved this via:
```bash
sudo apt-apt install python-tk # in python 3 install python3-tk
pip2 install python-tk graphviz #in python 3 use pip3 to install
```
