### ISSUE TITLE
change input data at each 'step'

### ISSUE THREAD

**Issue by rspadim** [dmlc/xgboost#3475]
hi guys, could be possible change input data each 'epoch' (each new tree)?

my idea is create an denoise autoencoder, or something like it, where i can predict noise(X) = X

today i'm doing this https://github.com/xiaozhouwang/kaggle-porto-seguro/blob/master/code/fea_eng0.py without noise

i have X, and train X[ -1 feature] = X[feature removed], doing this many times i create an "autoencoder"

**Comment by hcho3** [comment]
You may set `subsample` to sample the training data in each boosting iteration. Let's take further discussion to the forum https://discuss.xgboost.ai/.

**Comment by rspadim** [comment]
done https://discuss.xgboost.ai/t/create-dynamic-input-data/60

thanks, but i think it's more related to dynamic input data instead of subsample, let's see =) ideas are wellcome
