### ISSUE TITLE
Cmake fails when trying to turn on multi GPU, Windows 10

### ISSUE THREAD

**Issue by yeweinan** [dmlc/xgboost#3476]
Hi Everyone,

The command I'm using:
cmake .. -G "Visual Studio 15 2017 Win64" -DUSE_CUDA=ON -DUSE_NCCL=ON 
-DNCCL_ROOT="c:/dev/nccl"

The nccl is from https://developer.nvidia.com/nccl, version NCCL 2.2.12 O/S agnostic and CUDA 9.2. 

Error:  Could NOT find Nccl (missing: NCCL_LIBRARY)

**Comment by RAMitchell** [comment]
We just switched to nccl 2 which does not support Windows - so multi-GPU will not be possible on Windows. At some point I will add a better error message.
