### ISSUE TITLE
Buffer file couldn't be generated in version 0.40

### ISSUE THREAD

**Issue by nyz** [dmlc/xgboost#348]
If I run the demo, i.e. regression, it would hang at stage of .buffer file generation. 
And if file .buffer was there, xgboost load the buffer file and train successfully.
And there isn't the same issue in version 0.32. So there is ugly workaround that generate .buffer with v0.32 and continue train with v0.40

**Comment by tqchen** [comment]
I just tested this and it runs fine on my side.

**Comment by tqchen** [comment]
I was testing the most recent version on the master by the way. It would be great if you can share which version you are using, and what was the script (system) you used to regenerate the error

**Comment by nyz** [comment]
Sure. This always happen in my PC for versions after release 0.32

Script: demo/regression/runexp.sh
xgboost: release 0.40 (and most recent version so far)
OS: Mac OS 10.9.4
g++: i686-apple-darwin11-llvm-g++-4.2 (GCC) 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)

**Comment by nyz** [comment]
And yes, I've just tested it in ubuntu, it works fine.
I should be env related. Could you tell me what's the result if you tested xgboost in Mac OS.

**Comment by tqchen** [comment]
Unfortunately I do not have a Mac machine, so I cannot run any tests for now. It would be great if you can do some investigation on this and give more information

Thanks!

**Comment by nyz** [comment]
Unfortunately, I've got not progress of on this issue. Anyway, I'm only a user rather than a developer of xgboost. But I've heard xgboost was developed for Mac OS as well.

**Comment by tqchen** [comment]
I have to apology for this. I do not have OSX machine around and cannot dig
into this issue soon. Have you tried the python or r version? Do they have
the same problem?

**Comment by tqchen** [comment]
OK, here are something you can try to give more information on this. Basically we need to know where it hangs :)

Add some printf in between the steps in here, recompile the programs and see at which point  the function hangs
https://github.com/dmlc/xgboost/blob/master/src/io/simple_dmatrix-inl.hpp#L94
