### ISSUE TITLE
path is on mount '***:', start on mount 'C:' when building python package on Windows on the drive different from the one python is installed

### ISSUE THREAD

**Issue by KOLANICH** [dmlc/xgboost#3480]
The bug is only relevant to the systems having Windows paths.

```
Traceback (most recent call last):
  File "setup.py", line 19, in <module>
    LIB_PATH = [os.path.relpath(libfile, CURRENT_DIR) for libfile in libpath['find_lib_path']()]
  File "setup.py", line 19, in <listcomp>
    LIB_PATH = [os.path.relpath(libfile, CURRENT_DIR) for libfile in libpath['find_lib_path']()]
  File "***\Anaconda3\lib\ntpath.py", line 586, in relpath
    path_drive, start_drive))
ValueError: path is on mount '***:', start on mount 'C:'
```

The bisection showed to 88488fdbb9d915e8cc166fd620fcd4c2fe4bd1f1 .

**Comment by hcho3** [comment]
Can you print out the value of `libpath['find_lib_path']()`?

**Comment by KOLANICH** [comment]
@hcho the first address is discovered correctly : `../../lib/xgboost.dll`, the secod address is from PATH and for me it is from Anaconda installed on non-system drive. I propose to replace the loop by using the first address only.

**Comment by hcho3** [comment]
@KOLANICH Indeed, on Windows, `relpath` will fail if the source and destination directories are on different drives. I'll file a pull request to filter out items from `LIB_PATH` for which `relpath` would fail.

**Comment by KOLANICH** [comment]
>I'll file a pull request to filter out items from LIB_PATH for which relpath would fail.


I guess we don't need lool at all, we only need the lib built with the python module, but the code may also capture the system lib.

**Comment by hcho3** [comment]
@KOLANICH I went ahead and filed a pull request to fix the issue. Thanks!

**Comment by hcho** [comment]
Hi, 

I really don’t know what is going on.
Did you guys send email or message to wrong person?

**Comment by hcho3** [comment]
@hcho Sorry it was by mistake.

**Comment by KOLANICH** [comment]
It's me to excuse since it is I who have confused @`hcho` with you.
