### ISSUE TITLE
Dotnet Can't find libxgboost.so

### ISSUE THREAD

**Issue by andreispark** [dmlc/xgboost#3482]
Hello, I'm not sure if this is the correct place to post this, but perhaps you guys can help me.

I have a Dotnet Core application that I am running on a Linux environment, and it utilizes the xgboost library. I am running debian natively on Windows,  The output of /etc/os-release is as follows :

PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

I compiled xgboost from source following the make instructions, and I placed the libxgboost.so in /usr/local/lib and set the LD_LIBRARY_PATH to point to that location.  I can run my application perfectly fine, and everything works as expected. However If someone tries running the application on a different computer, and tries utilizing the  libxgboost.so library I made, the application fails. They are placing it in the same folder and setting their path appropriately. For some reason, dotnet fails to find the libxgboost.so . But if they download and make xgboost from source and replace the libxgboost.so file that I gave them, with the one they made from source, then the application functions correctly again and dotnet can find the xgboost library. 

The other computer I am testing on, is running the exact same environment as me, as has the same libraries installed.

I tried compiling xbgoost statically as described in this issue https://github.com/dmlc/xgboost/issues/3163, but this suffered the same limitations. 

I need to be able to pass around the libxgboost.so library like I can with the self contained dotnet application, without needing to have to compile xgboost from source on every new system. 

Thanks Again for all the help,

**Comment by hcho3** [comment]
I think it is possible to add an option in CMake to build static lib (`.a`) instead of shared lib (`.so`). Let me take a look at it. Then you can attach the static XGBoost lib to your application.

**Comment by andreispark** [comment]
I followed issue #3163 and compiled a static libxgboost.a and libxgboost.so and placed both in my /usr/local/lib, The issue with running it in another machine is that it requires the c and c++ run times to support xgboost. I updated gcc and g++ on both machines so that they match, then I compiled the static libxgboost.so and libxgboost.a files and it now works! 

Thanks for the help

**Comment by hcho3** [comment]
> it requires the c and c++ run times

So the version for glibc causes incompatibility? That's a bit concerning.
