### ISSUE TITLE
Inconsistency of feature importance between Python and R implementations

### ISSUE THREAD

**Issue by jqmp** [dmlc/xgboost#3484]
I've noticed that the Python and R implementations of feature importance behave a bit differently.  The Python `get_score(importance_type='gain')` function returns each feature's *average* gain over all of its splits, while the R `xgb.importance` function's `"Gain"` column gives each's feature's *total* gain.

I'm not an expert, but intuitively, the total gain seems much more useful as a measure of importance.  (Would you prefer a feature that gets used a single time with gain 100; or 100 times, each with gain 10?)  I'd be happy to submit a PR introducing an `importance_type='total_gain'` argument to `get_score`.  What do you think?

For what it's worth, this is what I see in the git history:
* [Dec 28, 2014](https://github.com/dmlc/xgboost/commit/3694772bde99af6b7df88e849ee5e09acea83c12): R implementation is added, returning total gain; however, the documentation implies that it returns average gain.
* [Apr 21, 2016](https://github.com/dmlc/xgboost/pull/1135/commits/a1e2b0652f718e883a4e97cd9beaf1e750c1da7b): Python implementation is added, returning average gain.  (Perhaps based on the R documentation?)
* [Jan 21, 2017](https://github.com/dmlc/xgboost/commit/2b5b96d760b43a6d37bc605c8e2c34f8a0471dd2?diff=split): R documentation is updated to make it clear that it returns total gain.

Thanks!

**Comment by hcho3** [comment]
> I'd be happy to submit a PR introducing an importance_type='total_gain' argument to get_score. What do you think?

Yes, can you file a pull request to specify the type of importance?

**Comment by jqmp** [comment]
Sure, I'll do that this week.
