### ISSUE TITLE
gblinear parameters

### ISSUE THREAD

**Issue by papinisan** [dmlc/xgboost#3492]
Few questions about gblinear:
1. Is there a parameter for feature subsetting like "colsample_bytree" for gblinear?
2. Is gblinear with default parameters functioning like an elastic net?
3. What are the range of values for alpha and lambda, they are not listed in https://xgboost.readthedocs.io/en/latest/parameter.html.
Thanks!

**Comment by hcho3** [comment]
Migrated to https://discuss.xgboost.ai/t/gblinear-parameters/69. Discussion and general questions will be directed to the user forum.

**Comment by hcho3** [comment]
I left my answer at https://discuss.xgboost.ai/t/gblinear-parameters/69/2.
