### ISSUE TITLE
xgboost hist

### ISSUE THREAD

**Issue by USCYuandaDu** [dmlc/xgboost#3496]
Hi @hcho3,
I'm happy to find that you are the author of hist updater, I have a question here. 
My classmates said that the hist is suitable for single worker. So my question is does hist suitable for nworker > 1 ? Can you explain whether hist updater has any limit? Thanks!
Bests,
Yuanda

**Comment by hcho3** [comment]
Hi Yuanda:

The hist updater currently does not support distributed training, so it is only suitable for a single node.

Ps. We recently created a policy to forward all general discussions to the user forum https://discuss.xgboost.ai/. Feel free to post any follow up questions there.
