### ISSUE TITLE
[jvm-packages] xgb-spark save and load model from hdfs

### ISSUE THREAD

**Issue by yuezZYMSQTD** [dmlc/xgboost#3497]
In version 0.72 when I finish the training with xgb-spark, I want to save the model to hdfs. I tried the codes below but it failed.
```
val model = new XGBoostRegressor(paramMap).setFeaturesCol("features").setLabelCol("label").fit(dataTrain)

model.save("hdfs://...")
```
I also tried the code below, but I could not load it.
```
model.nativeBooster.saveModel("hdfs://...")

val modelLoad = XGBoostRegressionModel.load("hdfs://...")
```

What is right way to save model to hdfs and load it from hdfs?

In version 0.7, I can succeed when using the following code.
```
val model = XGBoost.trainWithDataFrame(dataTrain, paramMap, ...)
model.saveModelAsHadoopFile("hdfs://...")(sc)

val modelLoad = XGBoost.loadModelFromHadoopFile("hdfs://...")(sc)
```

**Comment by hcho3** [comment]
Let's take future discussions at https://discuss.xgboost.ai/t/jvm-packages-xgb-spark-save-and-load-model-from-hdfs/74/4.
