### ISSUE TITLE
[xgboost-spark] How does the distributed models work?

### ISSUE THREAD

**Issue by USCYuandaDu** [dmlc/xgboost#3504]
Hi all, 
I'm wonder why only chooses the first model here?
https://github.com/dmlc/xgboost/blob/a725272e19748a5f3ddd7eeeff7c766660e38a06/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala#L271

And I can not see any synchronize on these models, so I think we just pick random one from these different models?

Bests,
Yuanda

**Comment by USCYuandaDu** [comment]
@hcho3 @CodingCat

**Comment by hcho3** [comment]
Our policy is to direct all questions to the user forum https://discuss.xgboost.ai/. The issue tracker should be kept for bug reports and feature additions.

**Comment by WngMen** [comment]
I have the same problem about this，why take the first booster only？
