### ISSUE TITLE
[BUG REPORT] invalid predictions when predict multi-times after set_base_margin for dmatrix

### ISSUE THREAD

**Issue by zengxy** [dmlc/xgboost#3505]
I'm currently use python packages for xgboost. And I found that the predict values are wrong when I predict multi times after use set_base_margin for dmatrix. Just see the following test code.
```
import numpy as np
import xgboost as xgb
from sklearn.datasets import load_iris

param = {'max_depth': 1, 'eta': 1, 'silent': 1, 'objective': 'multi:softprob', 'num_class': 3}
iris = load_iris()
dtrain = xgb.DMatrix(iris.data, label=iris.target)
dtest = xgb.DMatrix(np.array([[1, 2, 3, 4], [1, 2, 3, 4], [0, 1, 2, 3]]))


dtrain.set_base_margin([0.0, 0.0, 0.0])
dtest.set_base_margin([0.0, 0.0, 0.0])

m = xgb.train(params=param, dtrain=dtrain, num_boost_round=1)

for line in m.get_dump():
    print(line)

for i in range(3):
    print(f"Predict for the {i+1} time: \n", m.predict(dtest, output_margin=True))
```
Here is the output of  above code:
```
0:[f2<2.45000005] yes=1,no=2,missing=1
	1:leaf=1.43540668
	2:leaf=-0.733496368

0:[f2<2.45000005] yes=1,no=2,missing=1
	1:leaf=-0.717703402
	2:leaf=0.366748124

0:[f3<1.6500001] yes=1,no=2,missing=1
	1:leaf=-0.647482097
	2:leaf=1.34328353

Predict for the 1 time: 
 [[-0.73349637  0.36674812  1.3432835 ]
 [-0.73349637  0.36674812  1.3432835 ]
 [ 1.4354067  -0.7177034   1.3432835 ]]
Predict for the 2 time: 
 [[-0.73349637  0.36674812  1.3432835 ]
 [-1.4669927   0.73349625  2.686567  ]
 [ 2.8708134  -1.4354068   2.686567  ]]
Predict for the 3 time: 
 [[-0.73349637  0.36674812  1.3432835 ]
 [-2.200489    1.1002444   4.0298505 ]
 [ 4.30622    -2.1531103   4.0298505 ]]
```

It seems that it output a margin by plus current predicted values to old ones every time I call predict for all but the first instance. 

While if i comment the two lines of  `set_base_margin`, I got the right answer. Output result is follwing.
```
0:[f2<2.45000005] yes=1,no=2,missing=1
	1:leaf=1.43540668
	2:leaf=-0.733496368

0:[f2<2.45000005] yes=1,no=2,missing=1
	1:leaf=-0.717703402
	2:leaf=0.366748124

0:[f3<1.6500001] yes=1,no=2,missing=1
	1:leaf=-0.647482097
	2:leaf=1.34328353

Predict for the 1 time: 
 [[-0.23349637  0.8667481   1.8432835 ]
 [-0.23349637  0.8667481   1.8432835 ]
 [ 1.9354067  -0.2177034   1.8432835 ]]
Predict for the 2 time: 
 [[-0.23349637  0.8667481   1.8432835 ]
 [-0.23349637  0.8667481   1.8432835 ]
 [ 1.9354067  -0.2177034   1.8432835 ]]
Predict for the 3 time: 
 [[-0.23349637  0.8667481   1.8432835 ]
 [-0.23349637  0.8667481   1.8432835 ]
 [ 1.9354067  -0.2177034   1.8432835 ]]
```

It can reproduce stable on my laptop (`ubuntu 16.04 + python3.6 + xgboost 0.72.1 numpy 1.14.5 `). 
I think maybe it's caused by not clear the result cache when predict multi-times and you can check it.

**Comment by RAMitchell** [comment]
I can't reproduce this on the current master branch on Ubuntu or Windows. Did you try the latest from source or the version on pip?

**Comment by zengxy** [comment]
@RAMitchell I use the latest version 0.72.1 on pip and haven't try to build from source.

**Comment by hcho3** [comment]
@zengxy You should try using the latest version. The bug exists for 0.72.1 but disappears for the latest. You can get an (unofficial) build of the master at [this link](https://xgboost-ci.net/job/xgboost/job/master/102/artifact/dist/linux_cuda8.0_omp_py2.7/py/dist/xgboost-0.72-py2.py3-none-any.whl).

**Comment by hcho3** [comment]
It looks like the OP's script triggered an undefined behavior by using an incorrectly sized array for `set_base_margin()`. Since there are 3 data points and num_class=3, we'd need 3*3=9 entries in the base margin. I'll file a PR to check the length of base margin.

**Comment by hcho3** [comment]
Also `set_base_margin()` should be moved after the `train()`, unless you want to set base margins for all training data (~150 data points).

**Comment by zengxy** [comment]
I thought that `base_margain` is to indicate the bias of each class, so it is expected to be with a length of class_num. Thanks a lot and I'll have a try.
