### ISSUE TITLE
xgboost gpu predictor running slower relative to cpu 

### ISSUE THREAD

**Issue by patelprateek** [dmlc/xgboost#3508]
Re creating this issue since it was closed without being resolved by @RAMitchell 
I am training some gradient boosted trees using xgboost library. When i use the tree method : gpu_hist, i definitely see a 10x speedup for training. Another 4x speedup for using multiple gpus on a signle machine.

The issue I am running into right now is the prediction (using the gpu_predictor) is almost 1.5-2x slower than the cpu_predictor. Is this supposed to be like that ? I assumed the prediction/scoring can also be easily parallelized across all the boosted trees. Has any one faced similar issues ? Another issue i observe is that after training the on gpus , i still see memory not free'd on the gpus. Is this a known issue , do i need to delete the booster/model and run evaluation/prediction separately

Even after deleting the booster and reading back serialized model and doing some warmpup to run prediction , the prediction is much slower than cpu , this after removing the memory copy overhead.
What exactly is optimized in gpu predictor as opposed to cpu predictor ? I am trying different dataset size and the result is pretty consistent with gpu predictor always being worse than cpu predictor. training takes about 2-3 minutes whereas prediction is taking 30 minutes , i don't think this is something expected. any workarounds

**Comment by hcho3** [comment]
I've re-opened the previous issue. Let's keep discussion there.
