### ISSUE TITLE
error occurred when calling copy function use loaded model

### ISSUE THREAD

**Issue by Ying456123** [dmlc/xgboost#3509]
The code is as follows:
``` python
import xgboost as xgb
import numpy as np

class BoosterCountPoissonExample():
    def __init__(self):
        data = np.random.rand(5, 10)  # 5 entities, each contains 10 features
        label = np.random.randint(2, size=5)  # binary target
        self.dtrain = xgb.DMatrix(data, label=label)

    def get_model_joblib(self):
        print("get model by joblib")
        param = {'max_depth': 2, 'eta': 1, 'silent': 1, 'objective': 'count:poisson'}
        plst = param.items()
        model = xgb.train(plst, self.dtrain)
        model_cp_1 = model.copy()
        print("before dump model, copy")

        from sklearn.externals import joblib
        path_name = "/Users/Jane/Desktop/model.pkl"
        joblib.dump(model, path_name)

        model_load = joblib.load(path_name)
        model_cp_2 = model_load.copy()
        print("after dump model, copy")

        return model

test = BoosterCountPoissonExample()
test.get_model_joblib()
```

Before dump the model, copy function works well. However, If I dump and then load the model,  I will get the following message when calling copy:
AssertError:read can not have position excceed buffer length. 
Below is the screen shot.
![image](https://user-images.githubusercontent.com/24699537/43239275-2b434f80-90c4-11e8-89ae-282b849fde1c.png)
Could you please help on this? Thanks a lot. :)

**Comment by Ying456123** [comment]
**Environment Info**
Operating System: macOS Version 10.13.4
Package used (python/R/jvm/C++): Python
xgbooost version: 0.6
The python version and distribution: Python 3.6.1 |Anaconda 4.4.0 (x86_64)|
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin

**Comment by hcho3** [comment]
@Ying456123 I managed to re-produce the bug on my Macbook Pro. Let me take a look at it.

**Comment by hcho3** [comment]
Looks like I get the same error when I replace `joblib` with `pickle`:
```python
print("get model by joblib")
param = {'max_depth': 2, 'eta': 1, 'silent': 1, 'objective': 'count:poisson'}
plst = param.items()
model = xgb.train(plst, self.dtrain)
model_cp_1 = model.copy()
print("before dump model, copy")

import pickle
path_name = "./model.pkl"
with open(path_name, 'wb') as f:
  pickle.dump(model, f)

with open(path_name, 'rb') as f:
  model_load = pickle.load(f)
model_cp_2 = model_load.copy()
print("after dump model, copy")
```

**Comment by hcho3** [comment]
@pseudotensor FYI, this is another example where `pickle` is giving trouble with XGBoost. I plan to look at it this weekend.

**Comment by hcho3** [comment]
@Ying456123 I submitted a pull request to fix the issue.

@pseudotensor I fixed this particular problem, but you previously said that there were other parameters that were truncated by pickling. Can you give me some examples?

**Comment by Ying456123** [comment]
@hcho3 Thanks a lot for your immediate reply. I will try the pickle with new code. 👍
