### ISSUE TITLE
java.lang.UnsatisfiedLinkError:  /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.7' not found

### ISSUE THREAD

**Issue by skywalker2256** [dmlc/xgboost#3511]
Compile environment
gcc version: 6.1.0

I bulid xgboost-spark.
Can I run on gcc 4.4.7 version cluster? Thank you!

**Comment by hcho3** [comment]
I left my answer at https://discuss.xgboost.ai/t/java-lang-unsatisfiedlinkerror-usr-lib64-libstdc-so-6-version-cxxabi-1-3-7-not-found.
