### ISSUE TITLE
[jvm-packages]Booster.predict gives different result than XGBoostModel.predict

### ISSUE THREAD

**Issue by mliu60** [dmlc/xgboost#3526]
Hi, I'm trying to train XGBoost on Spark and use the Booster object to label online traffic. However, I noticed that prediction given by XGBoostModel.predict differs from prediction given by Booster.predict. Is this the expected behavior or is it a bug? Here are the code snippet I used for training, evaluation and online labeling.
Code snippet used for training:
```        
SparkConf conf = new SparkConf().setAppName(jobName);
        conf.set("spark.serializer", "org.apache.spark.serializer.KryoSerializer");
        Class[] boosters = {ml.dmlc.xgboost4j.scala.Booster.class};
        conf.registerKryoClasses(boosters);
        SparkContext sc = new SparkContext(conf);
        XGBoostModel model = train(sc);
        evaluate1(sc, model);
        evaluate2(sc, model);
```
```    
private static XGBoostModel train(SparkContext sc) throws XGBoostError {
        JavaRDD<LabeledPoint> trainRDD =
            MLUtils.loadLibSVMFile(sc, inputTrainPath).toJavaRDD().
                map((lp) -> new LabeledPoint(lp.label(), new DenseVector(lp.features().toArray())));

        java.util.Map<String, Object> jparamMap = new java.util.HashMap<>();
        jparamMap.put("eta", eta);
        jparamMap.put("max_depth", maxDepth);
        jparamMap.put("objective", objective);

        // use absolutely black magic to convert a Java Map to a Scala Immutable Map
        Map<String, Object> paramMap = JavaConverters
            .mapAsScalaMapConverter(jparamMap)
            .asScala()
            .toMap(Predef.conforms());

        // Return the trained model.
        return XGBoost.trainWithRDD(
            JavaRDD.toRDD(trainRDD),
            paramMap,
            numRound,
            numWorker,
            null, // can specify a custom objective (type ObjectiveTrait)
            null, // can specify a custom evaluation metric (type EvalTrait)
            false,
            missing);
    }
```
Predict new data points using XGBoostModel:
```    
private static void evaluate1(SparkContext sc, XGBoostModel model) {
        JavaRDD<DenseVector> testSet = MLUtils.loadLibSVMFile(sc, hdfsTestPath).toJavaRDD()
            .map((lp) -> new DenseVector(lp.features().toArray()));
        JavaRDD<float[]> predictions = model
            .predict(JavaRDD.toRDD(testSet), missing).toJavaRDD();
        predictions.map((pred) -> Arrays.toString(pred))
            .saveAsTextFile(outputPredPath + "1");
    }
```
Predict new data points using Booster:
```    
private static void evaluate2(SparkContext sc, XGBoostModel model) throws XGBoostError {
        DMatrix testSet = new DMatrix(localTestPath);
        JavaSparkContext.fromSparkContext(sc)
            .parallelize(Arrays.asList(model.booster().predict(testSet, false, 0)))
            .map((pred) -> Arrays.toString(pred))
            .saveAsTextFile(outputPredPath + "2");
    }
```
Thanks for your help.

**Comment by CodingCat** [comment]
so.....it is a known issue, 

if you train model with spark, it will assume the libsvm file is 1-based indexed. 

however, xgboost itself will assume the libsvm is 0-based indexed. 

as a result, your model will assume your testset is 0-based when dealing with a 1-based file....

the issue happened....

I just wrote a better explanation about this in a PR I sent hours ago https://github.com/dmlc/xgboost/pull/3524

**Comment by CodingCat** [comment]
please add [jvm-packages] in your title to help me identify the issue is to jvm-packages , thanks

**Comment by hcho3** [comment]
@CodingCat I recently added an option in dmlc-core to read CSV files using 1-based indexing: dmlc/dmlc-core#401. So you can do something like
```java
DMatrix testSet = new DMatrix('./test_set.csv?format=libsvm& indexing_mode=1');
```

**Comment by CodingCat** [comment]
@hcho3 , let me patch it

**Comment by hcho3** [comment]
@CodingCat We just need to update the dmlc-core submodule to 81f34b55cb3b1c3a4ba7ad5a95ccde21008088e0.

**Comment by CodingCat** [comment]
@hcho3 but the default behavior would still be take it as 0-based?

**Comment by mliu60** [comment]
@CodingCat Thanks. I'm aware of that issue, so I converted my test file to 0 indexed, but they still gives different scores.

**Comment by hcho3** [comment]
@CodingCat Yes, the default is 0-based to keep backward compatibility. The thing is that you can find both 0-based and 1-based LIBSVM files in the wild.

**Comment by CodingCat** [comment]
@hcho3 yeah, I mean in this case, we not only need to update dmlc-core submodule but also need to patch language bindings to make take LIBSVM as 1-based optionally?

**Comment by hcho3** [comment]
@mliu60 Can you post a re-producible example?

**Comment by mliu60** [comment]
@hcho3 
Here is the code I used
`package com.sift;

import java.io.IOException;
import java.util.Arrays;

import ml.dmlc.xgboost4j.java.XGBoostError;
import ml.dmlc.xgboost4j.scala.Booster;
import ml.dmlc.xgboost4j.scala.DMatrix;
import ml.dmlc.xgboost4j.scala.spark.XGBoost;
import ml.dmlc.xgboost4j.scala.spark.XGBoostModel;
import org.apache.hadoop.conf.Configuration;
import org.apache.hadoop.fs.FileSystem;
import org.apache.hadoop.fs.Path;
import org.apache.spark.SparkConf;
import org.apache.spark.SparkContext;
import org.apache.spark.api.java.JavaRDD;
import org.apache.spark.api.java.JavaSparkContext;
import org.apache.spark.ml.feature.LabeledPoint;
import org.apache.spark.ml.linalg.DenseVector;
import org.apache.spark.mllib.util.MLUtils;
import scala.Predef;
import scala.collection.JavaConverters;
import scala.collection.immutable.Map;

public class XGBoostDebug {

    private static final String inputTrainPath =
        "/user/ubuntu/training_pipeline/feature_vector/mliu_evaluate3_short/" +
            "training/xgbpaymentabuseglobalGLOBAL/vectors";
    private static final String hdfsTestPath =
        "/user/ubuntu/training_pipeline/feature_vector/mliu_evaluate3_short/" +
            "training/xgbpaymentabuseglobalGLOBAL/vectors";
    private static final String localTestPath = "xgbpaymentabuseglobalGLOBAL/vectors";
    private static final String outputModelPath =
        "/user/ubuntu/training_pipeline/feature_vector/mliu_evaluate3_short/" +
            "training/xgbpaymentabuseglobalGLOBAL/model";
    private static final String outputPredPath =
        "/user/ubuntu/training_pipeline/feature_vector/mliu_evaluate3_short/" +
            "training/xgbpaymentabuseglobalGLOBAL/scores";

    private static final String jobName = "Debug XGBoost";
    private static final double eta = 0.19;
    private static final int maxDepth = 10;
    private static final int numRound = 16;
    private static final int numWorker = 8;
    private static final float missing = Float.NaN;
    private static final String objective = "binary:logistic";


    public static void main(String[] args) throws Exception {
        SparkConf conf = new SparkConf().setAppName(jobName);
        conf.set("spark.serializer", "org.apache.spark.serializer.KryoSerializer");
        Class[] boosters = {ml.dmlc.xgboost4j.scala.Booster.class};
        conf.registerKryoClasses(boosters);
        SparkContext sc = new SparkContext(conf);
        XGBoostModel model = train(sc);
        evaluate1(sc, model);
        evaluate2(sc, model);
        evaluate3(sc, model);
    }

    private static XGBoostModel train(SparkContext sc) throws XGBoostError {
        JavaRDD<LabeledPoint> trainRDD =
            MLUtils.loadLibSVMFile(sc, inputTrainPath).toJavaRDD().
                map((lp) -> new LabeledPoint(lp.label(), new DenseVector(lp.features().toArray())));

        java.util.Map<String, Object> jparamMap = new java.util.HashMap<>();
        jparamMap.put("eta", eta);
        jparamMap.put("max_depth", maxDepth);
        jparamMap.put("objective", objective);

        // use absolutely black magic to convert a Java Map to a Scala Immutable Map
        Map<String, Object> paramMap = JavaConverters
            .mapAsScalaMapConverter(jparamMap)
            .asScala()
            .toMap(Predef.conforms());

        // Return the trained model.
        return XGBoost.trainWithRDD(
            JavaRDD.toRDD(trainRDD),
            paramMap,
            numRound,
            numWorker,
            null, // can specify a custom objective (type ObjectiveTrait)
            null, // can specify a custom evaluation metric (type EvalTrait)
            false,
            missing);
    }

    private static void evaluate1(SparkContext sc, XGBoostModel model) {
        JavaRDD<DenseVector> testSet = MLUtils.loadLibSVMFile(sc, hdfsTestPath).toJavaRDD()
            .map((lp) -> new DenseVector(lp.features().toArray()));
        JavaRDD<float[]> predictions = model
            .predict(JavaRDD.toRDD(testSet), missing).toJavaRDD();
        predictions.map((pred) -> Arrays.toString(pred))
            .saveAsTextFile(outputPredPath + "1");
    }

    private static void evaluate2(SparkContext sc, XGBoostModel model) throws XGBoostError {
        DMatrix testSet = new DMatrix(localTestPath);
        JavaSparkContext.fromSparkContext(sc)
            .parallelize(Arrays.asList(model.booster().predict(testSet, false, 0)))
            .map((pred) -> Arrays.toString(pred))
            .saveAsTextFile(outputPredPath + "2");
    }

    private static void evaluate3(SparkContext sc, XGBoostModel model)
        throws IOException, XGBoostError {
        FileSystem fs = FileSystem.get(new Configuration());
        model.booster().saveModel(fs.create(new Path(outputModelPath)));
        Booster booster = ml.dmlc.xgboost4j.scala.XGBoost.loadModel(fs.open(new Path(outputModelPath)));
        DMatrix testSet = new DMatrix(localTestPath);
        JavaSparkContext.fromSparkContext(sc)
            .parallelize(Arrays.asList(booster.predict(testSet, false, 0)))
            .map((pred) -> Arrays.toString(pred))
            .saveAsTextFile(outputPredPath + "3");
    }
}
`

**Comment by hcho3** [comment]
@mliu60 Can you re-produce this issue with the mushroom dataset (found [here](https://github.com/dmlc/xgboost/tree/master/demo/binary_classification))? Alternatively, can you post the data snippet and the model? (We'll try to figure out something if your data is confidential)

**Comment by CodingCat** [comment]
@mliu60 @hcho3  we actually have a test case guarding this case https://github.com/dmlc/xgboost/blob/master/jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassifierSuite.scala#L27

curious if it's caused by something else

**Comment by hcho3** [comment]
@CodingCat In this case, updating dmlc-core submodule should be sufficient, since `indexing_mode` is being passed as a URL string to the dmlc-core LIBSVM parser.

**Comment by mliu60** [comment]
@hcho3 Thanks for the update. So after you merge your patch, should I use Booster on one indexed format or zero indexed format.

**Comment by hcho3** [comment]
@mliu60 You said

> Thanks. I'm aware of that issue, so I converted my test file to 0 indexed, but they still gives different scores.

Did you feed the 1-based file into `loadLibSVMFile()`?

I'd say that it may be easier to stick with 1-based indexing, if you plan to use Spark.

**Comment by mliu60** [comment]
@hcho3 I used 1-indexed file for training and evaluation using XGBoostModel. But I used 0-indexed file for evaluation using Booster. When evaluating using XGBoostModel, I loaded the 1-indexed file using `loadLibSVMFile`. When evaluating using Booster, I loaded the 0-indexed file directly into `DMatrix`. Hope this helps.

**Comment by mliu60** [comment]
@CodingCat @hcho3 Also if I initialize `DMatrix` using raw float array, should I pass in a 1-indexed array and leave the 0th entry empty?

**Comment by mliu60** [comment]
@hcho3 Just to make sure, `new DenseVector(lp.features().toArray())` will convert all feature vectors to 0-indexed, so my trained XGBoost model will be 0-indexed, correct?

**Comment by hcho3** [comment]
> When evaluating using XGBoostModel, I loaded the 1-indexed file using loadLibSVMFile. When evaluating using Booster, I loaded the 0-indexed file directly into DMatrix

Then it should work. I suspect there's another problem other than indexing. Can you post an example we can look at?

Keep in mind that you can always use raw float array to side-step the problem with 0-based vs. 1-based indexing.

**Comment by mliu60** [comment]
@hcho3 I'm using a version published at early June, not the most up-to-date version. Is that a problem?

**Comment by hcho3** [comment]
I think this is a bug. Can you post your data and model?

**Comment by CodingCat** [comment]
in Spark version code, you set

```java
private static final float missing = Float.NaN;
```

and pass it to predict function, so that DMatrix is created by taking this as missing value

but in your booster code

you didn't set anything for missing and by default it is zero

=> not 100% sure as didn't check every detail, you can give it a try

**Comment by mliu60** [comment]
@CodingCat I double checked, the predict method in Booster does not have a missing value parameter, so is it a bug then? And the `DMatrix` constructor does not support passing a path and missing value.

**Comment by CodingCat** [comment]
.....in your own code 

```java
JavaRDD<float[]> predictions = model
            .predict(JavaRDD.toRDD(testSet), missing).toJavaRDD();
```

**Comment by mliu60** [comment]
@CodingCat `XGBoostModel.predict` do support missing value, but `Booster.predict` does not.

**Comment by hcho3** [comment]
@mliu60 Can you run the same example with #3535 applied?

**Comment by CodingCat** [comment]
@mliu60 can you just try to change 

```java
private static final float missing = Float.NaN;
```

to 

```
private static final float missing = 0.0;
```

see how it works?

**Comment by mliu60** [comment]
Fixing the missing value works, thx a lot guys!
