### ISSUE TITLE
xgboost每次运行到这里就一直卡在这边，请问是不是触发了死循环啊

### ISSUE THREAD

**Issue by weishixuan** [dmlc/xgboost#3528]
![1532874412620](https://user-images.githubusercontent.com/23482645/43367378-8c27ddb8-937e-11e8-9fde-fc47872bad82.jpg)

**Comment by hcho3** [comment]
Can you post this in English?

**Comment by tqchen** [comment]
please post normal questions in https://discuss.xgboost.ai/
