### ISSUE TITLE
[jvm-packages] parameter objective given invalid value reg:tweedie

### ISSUE THREAD

**Issue by wangzhilong** [dmlc/xgboost#3537]
when set the parameter `objective` as `reg:tweedie`,  get an error:

``` shell
ERROR ApplicationMaster: User class threw exception: java.lang.IllegalArgumentException: XGBoostEstimator_2a6312d81a4f parameter objective given invalid value reg:tweedie.
```

in the code, [https://github.com/dmlc/xgboost/blob/master/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/LearningTaskParams.scala](https://github.com/dmlc/xgboost/blob/master/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/LearningTaskParams.scala)

``` python
private[spark] object LearningTaskParams {
  val supportedObjective = HashSet("reg:linear", "reg:logistic", "binary:logistic",
    "binary:logitraw", "count:poisson", "multi:softmax", "multi:softprob", "rank:pairwise",
    "reg:gamma")
```

`reg:tweedie` was not in supported list, why?

**Comment by hcho3** [comment]
@CodingCat Is `reg:tweedie` not supported in distributed version?

**Comment by CodingCat** [comment]
as long as it uses approx tree to train it should support.....

that's the problem, sometimes the new object func is added and I didn't capture the PR and this list has been outdated
