### ISSUE TITLE
Connect Error when trying to use xgboost4j-spark

### ISSUE THREAD

**Issue by valek** [dmlc/xgboost#3538]
Hi there !

and thanks for this wonderfull work.

I'm currently trying master branch and I have the following problem :
* when I try to use XGboost-spark i get this :
```
retry connect to ip(retry time 1): [192.168.2.61]
retry connect to ip(retry time 2): [192.168.2.61]
retry connect to ip(retry time 3): [192.168.2.61]
retry connect to ip(retry time 4): [192.168.2.61]
```

I have also the same problem if I don't skip the tests while building.
Any idea on the reason ?

Thanks !
Julien

**Comment by valek** [comment]
Still the same problem with 0.8 version 

I believe I have a problem with my network configuration ? Do I need to do something specific to configure this ?

**Comment by valek** [comment]
Poke @CodingCat may be ? ( as you seem to be one of the main dev of the xgboost4j package )

**Comment by hcho3** [comment]
What kind of cluster are you using now? Did you set up the cluster yourself or are you using a service? To avoid troubles with network configuration, consider using managed service such as [Amazon EMR](https://aws.amazon.com/emr/details/spark/).

**Comment by dreamsuifeng** [comment]
@hcho3 
I have met the same problem on spark2.2 with xgboost4j-spark 0.8
can I set the DMLC_WORKER_CONNECT_RETRY by some method that I don't konw to increase the retry times?
Sometime rerun the job can avoid the problem. But I want to get the model training every day,
I don't want to check the train precess every day.

can u help me plz?

**Comment by hcho3** [comment]
I think you can set DMLC_WORKER_CONNECT_RETRY as environment variable. How is your cluster set up? Do workers have ports open to each other? Also, ensure that you have enough executors in your Spark cluster; training job will fail if any executor dies or preempted.
