### ISSUE TITLE
'XGBClassifier' object has no attribute 'DMatrix'

### ISSUE THREAD

**Issue by suissemaxx** [dmlc/xgboost#3549]
Working with

- Mac OS X 10.11.6
- Conda 4.5.9
- Python environment 3.6.3 
- pip installed XGBoost 0.72.1

all of a sudden I get this error:

> 'XGBClassifier' object has no attribute 'DMatrix'

in this line of code:

`dtrain = xgb.DMatrix(X_train, y_train, feature_names=columns)`

I imported with:

`import xgboost as xgb`
`from xgboost import XGBClassifier`

and could sucessfully use xgboost in my Jupyter notebook on the same project for quite a while without problems. All of a sudden with no apparent code changes it yields the error.

How can I fix this?

(Btw: Thanks for making xgboost available. Very much appreciated!)

**Comment by hcho3** [comment]
I left my answer at https://discuss.xgboost.ai/t/xgbclassifier-object-has-no-attribute-dmatrix/123. We have a policy of keeping the issue tracker for bug reports. General questions should be posted at the user forum https://discuss.xgboost.ai/.
