### ISSUE TITLE
Shared lib very large (~ 100 MB) due to static linking of NCCL2

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#3554]
@RAMitchell @teju85 
I just noticed that, because of static linking of NCCL2, the GPU-enabled shared lib `libxgboost.so` becomes quite large (~100 MB). This is a problem, since there is a 60MB limit for binary wheels on PyPI: http://ilostmynotes.blogspot.com/2016/04/externally-hosting-pypi-python-packages.html

Is there a way to reduce the size of shared lib, e.g. by dynamic linking of NCCL2? If static linking is necessary, we'll have to self-host the binary wheel on S3.

**Comment by RAMitchell** [comment]
Suggest we upload a version without nccl to pypi for now. We could add this line to the Jenkins build matrix:
`[ "enabled": true,  "os" : "linux", "withGpu": true, "withNccl": False,  "withOmp": true, "pythonVersion": "2.7", "cudaVersion": "8.0" ],`

Would be good to investigate the causes of such large binaries. This seems unreasonably large.

**Comment by trivialfis** [comment]
Got curious. Tried to use dynamic linking, libxgboost.so is just 37M, while libnccl_static.a by itself is 77M.

**Comment by hcho3** [comment]
I guess I'll upload a wheel without NCCL to PyPI. We can self-host multi-GPU-enabled wheels.

**Comment by hcho3** [comment]
Checkout out the artifact `dist/linux_cuda8.0_nonccl_omp_py2.7/py/dist/xgboost-0.72-py2.py3-none-any.whl` at https://xgboost-ci.net/blue/organizations/jenkins/xgboost/detail/PR-3567/21/artifacts.
