### ISSUE TITLE
Is training an XGBoost model on a GPU limited by the GPU's memory or can datasets bigger than the GPU's VRAM be trained on the GPU?

### ISSUE THREAD

**Issue by gregsifr** [dmlc/xgboost#3558]
I've searched for the above question and was not able to find any answers so I have posted this question to [stackoverflow](https://stackoverflow.com/questions/51699557/is-training-an-xgboost-model-on-a-gpu-limited-by-the-gpus-memory)

The reason why this question is important is that not everyone has a GPU and it is helpful to understand how important a GPU's VRAM is prior to making a purchase.

**Comment by hcho3** [comment]
@gregsifr I left my answer at https://discuss.xgboost.ai/t/is-training-an-xgboost-model-on-a-gpu-limited-by-the-gpus-memory-or-can-datasets-bigger-than-the-gpus-vram-be-trained-on-the-gpu/126/2. Hope it helps.

Let's post all questions at the user forum https://discuss.xgboost.ai/. The issue tracker is to keep track of active bugs.
