### ISSUE TITLE
url in ranking demo not working anymore

### ISSUE THREAD

**Issue by Shiki-H** [dmlc/xgboost#3559]
Microsoft moved all of its letor datasets onto OneDrive so the original script `wgetdata.sh` under `demo/rank` would not work anymore. I did find an alternative link [here](http://www.bigdatalab.ac.cn/benchmark/bm/dd?data=MQ2008) but I am not sure if this is a good solution.

**Comment by hcho3** [comment]
It may be better to host it ourselves. Let me upload it to S3 and update the link.

**Comment by Shiki-H** [comment]
@hcho3 Cool. Thanks for the help. Closing the issue now
