### ISSUE TITLE
Is Normalization necessary?

### ISSUE THREAD

**Issue by frankzhangrui** [dmlc/xgboost#357]
I am not quite sure how xgboost works in theory. But since xgboost is a tree based classifier, is it ok to assume that no normalization of features is needed?

**Comment by tqchen** [comment]
no you do not have to normalize the features

**Comment by loretoparisi** [comment]
@tqchen Reading your great [Introduction to Boosted Trees](https://homes.cs.washington.edu/~tqchen/pdf/BoostedTree.pdf) it's not clear to me why feature scaling it's not necessary in mathematical terms.
