### ISSUE TITLE
In the Windows environment, if you do not install Visual Studio, you cannot use xgboost correctly

### ISSUE THREAD

**Issue by liubin123456** [dmlc/xgboost#3571]
@hcho3  I can use xgboost to get the results correctly on a Windows computer with Visual Studio installed, but when I switch to another Windows computer without Visual Studio, I can't get the result correctly. I want to ask: Is it necessary to call xgboost? Visual Studio library, if so, what do you need? My code is written in java. Looking forward to your answer!

**Comment by hcho3** [comment]
> I can't get the result correctly

Can you be more specific? No, Visual Studio should not be needed to run the compiled XGBoost.

**Comment by hcho3** [comment]
Actually, XGBoost (compiled by Visual Studio) has dependency on vcomp140.dll. So either you'll have to install Visual C++ redistributable or manually copy vcomp140.dll.

**Comment by hcho3** [comment]
Feel free to post future questions at the user forum https://discuss.xgboost.ai.

**Comment by liubin123456** [comment]
Hi we built "xgboost4j.dll" and the corresponding jar on windows platform successfully. The ''jar" package runs very well on every computer where the visual studio is installed.But if the visual studio isn't installed on the computer(windows platform),the java project is failed to build and shows the exception:can't find dependent libraries xgboost4jXXXXXXX.dll(XXXXXXX is random number).Why the visual studio is needed for xgboost4j.dll? Could you explain it for us ?Looking forward your reply.

**Comment by liubin123456** [comment]
@hcho3 Hi we built "xgboost4j.dll" and the corresponding jar on windows platform successfully. The ''jar" package runs very well on every computer where the visual studio is installed.But if the visual studio isn't installed on the computer(windows platform),the java project is failed to build and shows the exception:can't find dependent libraries xgboost4jXXXXXXX.dll(XXXXXXX is random number).Why the visual studio is needed for xgboost4j.dll? Could you explain it for us ?Looking forward your reply.

**Comment by hcho3** [comment]
@liubin123456 See my previous reply. You'll need to find vcomp140.dll and include it in your JAR.
