### ISSUE TITLE
Is Jenkins working correctly?

### ISSUE THREAD

**Issue by trivialfis** [dmlc/xgboost#3585]
Hi, the current build for #3548 on Jenkins failed and I really have no clue on what's happening. The PR  builds on Travis and I have good faith in Appveyor since it hasn't fail for a while now.  But on Jenkins, the build log shows that all those macros even comments in dmlc-core got messed up.

https://xgboost-ci.net/blue/organizations/jenkins/xgboost/detail/PR-3548/60/pipeline/59

Raw build log:

https://xgboost-ci.net/blue/rest/organizations/jenkins/pipelines/xgboost/branches/PR-3548/runs/60/nodes/59/steps/72/log/?start=0

I don't think the problem is in my code since I counldn't modify dmlc-core in any way even if I want to.  Can someone shed some light on this? Thank you very much.

**Comment by hcho3** [comment]
Let me look into it. I have physical access to the machine, so I can try compiling it manually.

**Comment by hcho3** [comment]
It builds fine on the machine. This may be the workspace problem, something like one we had with FindGTest. I cleared the workspace and restarted the test.

**Comment by hcho3** [comment]
Erasing the workspace did the trick. Your PR now compiles successfully. Once the tests pass, we can merge it.

**Comment by RAMitchell** [comment]
Would be nice if we could automatically clear the workspace. I looked into this briefly before but it was not obvious how to do it.

**Comment by trivialfis** [comment]
Does the workspace has git? If so maybe we can do a git reset followed by a git clean?
