### ISSUE TITLE
compilation of master branch fails in alpine (docker)

### ISSUE THREAD

**Issue by WegDamit** [dmlc/xgboost#3587]
Observed the following error today (14.8), but same process worked yesterday (13.8.):

`g++ -c -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp src/predictor/cpu_predictor.cc -o build/predictor/cpu_predictor.o
In file included from src/common/./host_device_vector.h:14:0,
                 from src/common/host_device_vector.cc:11:
src/common/./span.h:437:22: error: 'ptrdiff_t' has not been declared
   template <class U, ptrdiff_t OtherExtent,
src/common/./span.h:440:49: error: 'OtherExtent' was not declared in this scope
               detail::IsAllowedExtentConversion<OtherExtent, Extent>::value>>
                                                 ^~~~~~~~~~~
src/common/./span.h:440:68: error: template argument 1 is invalid
               detail::IsAllowedExtentConversion<OtherExtent, Extent>::value>>
                                                                    ^
src/common/./span.h:441:47: error: 'OtherExtent' was not declared in this scope
   XGBOOST_DEVICE constexpr Span(const Span<U, OtherExtent>& _other)   // NOLINT
                                               ^~~~~~~~~~~
src/common/./span.h:441:58: error: template argument 2 is invalid
   XGBOOST_DEVICE constexpr Span(const Span<U, OtherExtent>& _other)   // NOLINT
                                                          ^
src/common/./span.h: In constructor 'constexpr xgboost::common::Span<T, Extent>::Span(const int&)':
src/common/./span.h:442:38: error: request for member 'size' in '_other', which is of non-class type 'const int'
       __span_noexcept : size_(_other.size()), data_(_other.data()) {}
                                      ^~~~
src/common/./span.h:442:60: error: request for member 'data' in '_other', which is of non-class type 'const int'
       __span_noexcept : size_(_other.size()), data_(_other.data()) {}
`

the important part of the build (from dockerfile)
` git clone --recursive https://github.com/dmlc/xgboost && \
    sed -i '/#define DMLC_LOG_STACK_TRACE 1/d' /src/xgboost/dmlc-core/include/dmlc/base.h && \
    sed -i '/#define DMLC_LOG_STACK_TRACE 1/d' /src/xgboost/rabit/include/dmlc/base.h && \
    ln -s locale.h /usr/include/xlocale.h && \
    cd /src/xgboost &&  make -j4`

(stolen  from this [Dockerfile](https://github.com/Nexosis/alpine-xgboost/blob/master/Dockerfile), referred from StackOverflow (sry, no link),   referred from [3157](https://github.com/dmlc/xgboost/issues/3157) ...)

i think the commit [2c502784fffeb4aa35734d70ede47c98a8639fc2](https://github.com/dmlc/xgboost/commit/2c502784fffeb4aa35734d70ede47c98a8639fc2) is the culprit, as it add an  include for the span.h mentioned in the error message.

Reverting is an option, 
but what's the reason for that include and 
how does this break the build on alpine/musl?

**Comment by hcho3** [comment]
Which version of GCC are you using?

@trivialfis Does your span class implementation comply with C++11 standard?

**Comment by hcho3** [comment]
@WegDamit Also, can you try compiling branch release_0.80? This should help us isolate the cause

**Comment by trivialfis** [comment]
To my knowledge, yes. But I will look into it.

**Comment by trivialfis** [comment]
I think I know the problem now.  Will make a fix. Sorry for the mistake.

**Comment by WegDamit** [comment]
great, thanks.
fix worked. 
compile and build went fine.

So just for future reference:
This was inside an alpine 3.8.0 docker,  it's gcc (Alpine 6.4.0) 6.4.0
