### ISSUE TITLE
[R] Parameter nround(s) in documentation

### ISSUE THREAD

**Issue by jakob-r** [dmlc/xgboost#3591]
The parameter to set the maximum number of boosting iterations is defined as `nrounds` in the R-Package.
However in the documentation they are multiple instances of where it is just used as `nround`.
This works because R is doing [argument matching](https://cran.r-project.org/doc/manuals/R-lang.html#Argument-matching). 
Of course one can rely on it but it's not the best way and a bit confusing for beginners. That's why it should be `nrounds` everywhere.

**Comment by hcho3** [comment]
Thanks for your report. Yes, the documentation should be updated. We'll gladly consider a pull request that fixes the typo.
