### ISSUE TITLE
distributed xgboost mpi examples

### ISSUE THREAD

**Issue by sebastiangonsal** [dmlc/xgboost#3596]
Is there an example of running distributed xgboost on mpi

**Comment by hcho3** [comment]
The official documentation currently doesn't provide an example. Try posting at the user forum https://discuss.xgboost.ai/ to see anyone else has tried it. Again, contribution is welcome.

**Comment by hcho3** [comment]
Consolidating to #3439. This issue should be re-opened when someone decides to write a tutorial with MPI.
