### ISSUE TITLE
Windows Compile fails to find jni.h with VS2015 RC	

### ISSUE THREAD

**Issue by o1lo01ol1o** [dmlc/xgboost#360]
Hi guys,
  Compiling most recent xgboost pull on windows 8.1 with VS2015 RC generates the following:
Cannot open include file: 'jni.h': No such file or directory	xgboostjavawrapper	

VS automatically updated the compiler info as it detected it was set for an earlier version of VS (I tried without success to build with VS 2010 last night and moved to VS2015RC today).  Is the java wrapper necessary if I just want to use the python bindings?
Thanks

**Comment by tqchen** [comment]
You only need to build xgboost wrapper
