### ISSUE TITLE
Feature request: XGB-spark: Do train/test-split by column-values

### ISSUE THREAD

**Issue by pekaalto** [dmlc/xgboost#3607]
Hi,

Now we can already `setTrainTestRatio` in spark-xgb which is great. Currently, this splits all examples independently to train or test data. 

However, many times there is some additional column what should be used in splitting train and test.

For example, assume that we are predicting purchase price and we have multiple observations per 
one customer. Then we would like to do train/test split so that all observations from one customer end up in train or test respectively.  This would be to avoid unwanted leakage between train and test.

So would it be possible add option to do `setSplitTrainTrestBy(mycol)`, where mycol could be a boolean column in the `DataFrame`.  Then we would simply do the train-test split by values in this column.

Another option to solve this problem would be to allow user to provide testData in the constructor or as a Param.

Thanks.

**Comment by hcho3** [comment]
Consolidating to the feature request tracker #3439. Feel free to re-open this issue when anyone starts working on this.
