### ISSUE TITLE
use_buffer is not working

### ISSUE THREAD

**Issue by chfe910** [dmlc/xgboost#3609]
The buffer file is not generated even if I set use_buffer=1 in the pred task.
And I also tried to save binary file as 'test.txt.buffer' manually by DMatrix.save_binary. Unfortunately, it still load instances from the original test file 'test.txt'.
If I delete the original test file 'test.txt', it will raise 'No such file' exception.
BTW, I clone the repo and build from root dir recently.
Could anyone help me on this? Thanks in advance!

**Comment by chfe910** [comment]
Yes, I'm using CLI. Is that the problem?

**Comment by chfe910** [comment]
Do you mean "test:data=mau_instances/test.txt.buffer" ? It's also not working. It raise "unsupported file version" exception.

**Comment by hcho3** [comment]
I can't reproduce the problem using latest master. Can you post the full log? When using Python to save binary buffer files, ensure that you are using the same version as the `xgboost` executable, by setting `PYTHONPATH`:
```
PYTHONPATH=/path/to/xgboost/python-package python3 ...
```

**Comment by hcho3** [comment]
I also tried creating binary buffers with version 0.72 and running training with version 0.80. I was still unable to re-produce the problem.
