### ISSUE TITLE
How does xgboost predict according to the trained model? 

### ISSUE THREAD

**Issue by yan9liu** [dmlc/xgboost#361]
I train a model with the objective "rank:pairwise", and want to apply the model to our online ranking system. So I dump the trained model into its raw text format, by which I get the c++ code with plenty of "if ... else ..." compatible with our system. The model has 100 trees, and I simply accumulate the scores outputed by each tree as the final score. I also tried "y(t)=y(t-1)+eta*f(t)". However, these scores are not same as the socres predicted by xgboost with parameter "task=pred", not only in absolute values, but also in relative order. I want to know how does xgboost predict according to the trained model, especially with the objective "rank:pairwise"? thank you!

**Comment by tqchen** [comment]
This is what xgboost does. But you might want to learn the missing direction, which treats the missing value differently by default. 

Since you are building a scoring system, one possible way is simply link with xgboost library and build a wrapper to your system(we also have a java wrapper)?
