### ISSUE TITLE
Tree method is selected to be 'hist', which uses a single updater grow_fast_histmaker.

### ISSUE THREAD

**Issue by hlbkin** [dmlc/xgboost#3611]
Hi.

Running latest 0.8 version built from wheels.

Is it valid for "tree_method": "hist" to use only single updater? Would adding "prune" to updaters manually make quality better in general? (out of sample)

Thnx

**Comment by hcho3** [comment]
The 'hist' updater internally calls 'prune' updater. The reason for doing this is that 'hist' updater knows about modification made by 'prune' updater. This is an implementation detail. If you're really curious about it, shoot me an e-mail to schedule a short video chat.
