### ISSUE TITLE
[xgboost4j-spark] the updateCheckpoint(...) in CheckpointManager is wrong

### ISSUE THREAD

**Issue by weitian** [dmlc/xgboost#3613]
Here is the code pieces:

  private[spark] def updateCheckpoint(checkpoint: Booster): Unit = {
    val fs = FileSystem.get(sc.hadoopConfiguration)
    val prevModelPaths = getExistingVersions.map(version => new Path(getPath(version)))
    val fullPath = getPath(checkpoint.getVersion)
    logger.info(s"Saving checkpoint model with version ${checkpoint.getVersion} to $fullPath")
    checkpoint.saveModel(fullPath)
    prevModelPaths.foreach(path => fs.delete(path, true))
  }

checkpoint.saveModel(fullPath) saves model to local disk, 
but prevModelPaths is HDFS.

This is a regression from v0.72, it used to have saveModelAsHadoopFile(...)

**Comment by CodingCat** [comment]
thanks for reporting this

it's a bug, we need a wrapper to wrap booster binaries and save it to HDFS

**Comment by CodingCat** [comment]
or we should as simple as using checkpoint.save(stream) to resolve it
