### ISSUE TITLE
LabeledPoint

### ISSUE THREAD

**Issue by moseshu** [dmlc/xgboost#3617]
where is the  LabeledPoint class? I did't not find it in package ml.dmlc.xgboost4j

**Comment by hcho3** [comment]
Here it is: https://xgboost.readthedocs.io/en/latest/jvm/scaladocs/xgboost4j/index.html#ml.dmlc.xgboost4j.LabeledPoint

**Comment by moseshu** [comment]
thank you so much.I found it. do you have the xgboost algorithm which is implemented only by  java or scala? Because I don't know C language

**Comment by hcho3** [comment]
No, we don't. The algorithm has been implemented in C++ to maximize performance.
