### ISSUE TITLE
Xgboost error with GPU on Ubuntu16.04

### ISSUE THREAD

**Issue by QiujieDong** [dmlc/xgboost#3625]
I installed xgboost with GPU on Ubuntu16.04 according to https://xgboost.readthedocs.io/en/latest/build.html, but when I run the code, I get an error:
**terminate called after throwing an instance of 'thrust::system :: xgboost with GPU on Ubuntu16.04
What(): function_attributes(): after cudaFuncGetAttributes: invalid device function**

When I only use xgboost with CPU on Ubuntu16.04, the program works fine.
I want to know how to solve the problem. Thank you.

**lspci | grep -i nvidia**
01:00.0 VGA compatible controller: NVIDIA Corporation GK107 [GeForce GT 630 OEM] (rev a1)
01:00.1 Audio device: NVIDIA Corporation GK107 HDMI Audio Controller (rev a1)

**sudo dpkg --list | grep nvidia-***
ii  nvidia-384                                  384.130-0ubuntu0.16.04.1                     amd64        NVIDIA binary driver - version 384.130
ii  nvidia-opencl-icd-384                       384.130-0ubuntu0.16.04.1                     amd64        NVIDIA OpenCL ICD
ii  nvidia-prime                                0.8.2                                        amd64        Tools to enable NVIDIA's Prime
ii  nvidia-settings                             361.42-0ubuntu1                              amd64        Tool for configuring the NVIDIA graphics driver

 **nvcc -V**
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61

cuDNN :V5.1

**Comment by hcho3** [comment]
Did you compile XGBoost yourself, or did you run `pip install xgboost`?

**Comment by QiujieDong** [comment]
I installed xgboost with GPU on Ubuntu16.04 according to https://xgboost.readthedocs.io/en/latest/build.html.

I don not use pip install xgboost.

**Comment by hcho3** [comment]
I think the problem is that your card is relatively old. You should change the line
https://github.com/dmlc/xgboost/blob/4ed8a882405dc5bbfb6cb099a075b8dcdeedecc2/cmake/Utils.cmake#L65
to
```cmake
      set(flags "21;35;50;52;60;61") 
```
and re-compile XGBoost. Let me know how it goes.

**Comment by QiujieDong** [comment]
@hcho3 
Re-compile means I run again:
cmake .. -DUSE_CUDA=ON
make -j
cd python-package
sudo python setup.py install

**Comment by QiujieDong** [comment]
@hcho3 

qiujiedong@qiujiedong:~/anaconda3/lib/python3.6/site-packages/xgboost/build$ make -j
[  7%] Built target rabit
[ 23%] Built target dmlc
[ 25%] Building NVCC (Device) object CMakeFiles/gpuxgboost.dir/src/tree/gpuxgboost_generated_updater_gpu_hist.cu.o
[ 26%] Building NVCC (Device) object CMakeFiles/gpuxgboost.dir/src/common/gpuxgboost_generated_hist_util.cu.o
[ 27%] Building NVCC (Device) object CMakeFiles/gpuxgboost.dir/src/common/gpuxgboost_generated_host_device_vector.cu.o
[ 29%] Building NVCC (Device) object CMakeFiles/gpuxgboost.dir/src/linear/gpuxgboost_generated_updater_gpu_coordinate.cu.o
[ 30%] Building NVCC (Device) object CMakeFiles/gpuxgboost.dir/src/objective/gpuxgboost_generated_regression_obj_gpu.cu.o
[ 32%] Building NVCC (Device) object CMakeFiles/gpuxgboost.dir/src/predictor/gpuxgboost_generated_gpu_predictor.cu.o
[ 33%] Building NVCC (Device) object CMakeFiles/gpuxgboost.dir/src/tree/gpuxgboost_generated_updater_gpu.cu.o
nvcc fatal   : Unsupported gpu architecture 'compute_21'
CMake Error at gpuxgboost_generated_hist_util.cu.o.Release.cmake:219 (message):
  Error generating
  /home/qiujiedong/anaconda3/lib/python3.6/site-packages/xgboost/build/CMakeFiles/gpuxgboost.dir/src/common/./gpuxgboost_generated_hist_util.cu.o


nvcc fatal   : Unsupported gpu architecture 'compute_21'
nvcc fatal   : Unsupported gpu architecture 'compute_21'
CMake Error at gpuxgboost_generated_host_device_vector.cu.o.Release.cmake:219 (message):
  Error generating
  /home/qiujiedong/anaconda3/lib/python3.6/site-packages/xgboost/build/CMakeFiles/gpuxgboost.dir/src/common/./gpuxgboost_generated_host_device_vector.cu.o


CMake Error at gpuxgboost_generated_updater_gpu_hist.cu.o.Release.cmake:219 (message):
  Error generating
  /home/qiujiedong/anaconda3/lib/python3.6/site-packages/xgboost/build/CMakeFiles/gpuxgboost.dir/src/tree/./gpuxgboost_generated_updater_gpu_hist.cu.o


[ 94%] Built target objxgboost
CMakeFiles/gpuxgboost.dir/build.make:6247: recipe for target 'CMakeFiles/gpuxgboost.dir/src/tree/gpuxgboost_generated_updater_gpu_hist.cu.o' failed
make[2]: *** [CMakeFiles/gpuxgboost.dir/src/tree/gpuxgboost_generated_updater_gpu_hist.cu.o] Error 1
make[2]: *** 正在等待未完成的任务....
CMakeFiles/gpuxgboost.dir/build.make:922: recipe for target 'CMakeFiles/gpuxgboost.dir/src/common/gpuxgboost_generated_hist_util.cu.o' failed
make[2]: *** [CMakeFiles/gpuxgboost.dir/src/common/gpuxgboost_generated_hist_util.cu.o] Error 1
CMakeFiles/gpuxgboost.dir/build.make:1720: recipe for target 'CMakeFiles/gpuxgboost.dir/src/common/gpuxgboost_generated_host_device_vector.cu.o' failed
make[2]: *** [CMakeFiles/gpuxgboost.dir/src/common/gpuxgboost_generated_host_device_vector.cu.o] Error 1
nvcc fatal   : Unsupported gpu architecture 'compute_21'
CMake Error at gpuxgboost_generated_updater_gpu_coordinate.cu.o.Release.cmake:219 (message):
  Error generating
  /home/qiujiedong/anaconda3/lib/python3.6/site-packages/xgboost/build/CMakeFiles/gpuxgboost.dir/src/linear/./gpuxgboost_generated_updater_gpu_coordinate.cu.o


nvcc fatal   : Unsupported gpu architecture 'compute_21'
CMake Error at gpuxgboost_generated_regression_obj_gpu.cu.o.Release.cmake:219 (message):
  Error generating
  /home/qiujiedong/anaconda3/lib/python3.6/site-packages/xgboost/build/CMakeFiles/gpuxgboost.dir/src/objective/./gpuxgboost_generated_regression_obj_gpu.cu.o


CMakeFiles/gpuxgboost.dir/build.make:2786: recipe for target 'CMakeFiles/gpuxgboost.dir/src/linear/gpuxgboost_generated_updater_gpu_coordinate.cu.o' failed
make[2]: *** [CMakeFiles/gpuxgboost.dir/src/linear/gpuxgboost_generated_updater_gpu_coordinate.cu.o] Error 1
CMakeFiles/gpuxgboost.dir/build.make:3639: recipe for target 'CMakeFiles/gpuxgboost.dir/src/objective/gpuxgboost_generated_regression_obj_gpu.cu.o' failed
make[2]: *** [CMakeFiles/gpuxgboost.dir/src/objective/gpuxgboost_generated_regression_obj_gpu.cu.o] Error 1
nvcc fatal   : Unsupported gpu architecture 'compute_21'
CMake Error at gpuxgboost_generated_gpu_predictor.cu.o.Release.cmake:219 (message):
  Error generating
  /home/qiujiedong/anaconda3/lib/python3.6/site-packages/xgboost/build/CMakeFiles/gpuxgboost.dir/src/predictor/./gpuxgboost_generated_gpu_predictor.cu.o


CMakeFiles/gpuxgboost.dir/build.make:4493: recipe for target 'CMakeFiles/gpuxgboost.dir/src/predictor/gpuxgboost_generated_gpu_predictor.cu.o' failed
make[2]: *** [CMakeFiles/gpuxgboost.dir/src/predictor/gpuxgboost_generated_gpu_predictor.cu.o] Error 1
nvcc fatal   : Unsupported gpu architecture 'compute_21'
CMake Error at gpuxgboost_generated_updater_gpu.cu.o.Release.cmake:219 (message):
  Error generating
  /home/qiujiedong/anaconda3/lib/python3.6/site-packages/xgboost/build/CMakeFiles/gpuxgboost.dir/src/tree/./gpuxgboost_generated_updater_gpu.cu.o


CMakeFiles/gpuxgboost.dir/build.make:5347: recipe for target 'CMakeFiles/gpuxgboost.dir/src/tree/gpuxgboost_generated_updater_gpu.cu.o' failed
make[2]: *** [CMakeFiles/gpuxgboost.dir/src/tree/gpuxgboost_generated_updater_gpu.cu.o] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/gpuxgboost.dir/all' failed
make[1]: *** [CMakeFiles/gpuxgboost.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by hcho3** [comment]
Can you change the line
https://github.com/dmlc/xgboost/blob/4ed8a882405dc5bbfb6cb099a075b8dcdeedecc2/cmake/Utils.cmake#L65
to
```cmake
      set(flags "20;35;50;52;60;61") 
```
(replacing 21 with 20)

**Comment by QiujieDong** [comment]
@hcho3 

Yes . I have changed  ,then re-compile xgboost.

function(format_gencode_flags flags out)
  # Set up architecture flags
  if(NOT flags) 
    if((CUDA_VERSION_MAJOR EQUAL 9) OR (CUDA_VERSION_MAJOR GREATER 9))
      set(flags "35;50;52;60;61;70")
    else()
      set(flags "21;35;50;52;60;61")
    endif()
  endif()

**Comment by QiujieDong** [comment]
The problem occurs when I run ：make -j

**Comment by hcho3** [comment]
@QiujieDong It appears that the XGBoost code does not work with your GPU. Consider upgrading your GPU to compute capability 3.5 or higher. Alternatively, you can use cloud providers (e.g. AWS) that provide GPU-capable instances.

**Comment by hcho3** [comment]
I will go ahead and document the compute capability requirement.
