### ISSUE TITLE
Cannot supply my own folds for xgb.cv

### ISSUE THREAD

**Issue by Tumpsh** [dmlc/xgboost#3629]
When I try to supply my own list of vectors containing indices for folds, the same way you would get from a function like rBayesianOptimization::KFold, I am getting the error: 

 Error in slice.xgb.DMatrix(dall, unlist(folds[-k])) : 
  [16:42:25] amalgamation/../src/c_api/c_api.cc:532: Check failed: static_cast<xgboost::bst_ulong>(ridx) < batch.Size() (2504 vs. 2472) 

The only difference I can think of between my folds and the list in KFold is that my folds have different numbers of elements in each of them

**Comment by hcho3** [comment]
Can you post the code you used to make folds?

**Comment by Tumpsh** [comment]
Actually, I had an error in my code. I just figured it out after a long time, and I assumed it was a bug since I saw a similar error in other posts here. It worked fine, after I fixed my own issue! Sorry about that

**Comment by hcho3** [comment]
No problem. Thanks for your interest in XGBoost.
