### ISSUE TITLE
xgb.cv prediction parameter with early stopping

### ISSUE THREAD

**Issue by BlindApe** [dmlc/xgboost#363]
The prediction = TRUE with early.stop.round set doesn't work. 
I think the problem is the 'break' of line 224.
Replacing 'for' at line 184 with 'while' loop: (while i <= nrounds & ! earlyStopflag)
and deleting 'break' could fix the problem.

**Comment by hetong007** [comment]
Can you post a reproducible code? I can run the following code

```r
require(xgboost)
data(agaricus.train)
dtrain = xgb.DMatrix(agaricus.train$data, label = agaricus.train$label)
cv.res = xgb.cv(data = dtrain, nround=100, nthread = 2, nfold = 5, early.stop.round = 5,
                         max.depth = 3, eta = 1, objective = "binary:logistic", 
                         prediction = TRUE, maximize = FALSE)
```

**Comment by BlindApe** [comment]
If you check your example cv.res$pred is all 0
If you want prediction parameter works you need to disable early.stop.round.

**Comment by hetong007** [comment]
Thank you for catching that! It is fixed in the latest commit.

**Comment by BlindApe** [comment]
Thank you!
Now, with prediction out of loop, is more efficient.
If you could change in:
res = xgb.iter.eval(fd$booster, fd$watchlist, i - 1, feval, prediction)
(i-1) with (bestInd - 1) when early.stop.round, the result would be more accurate.

**Comment by hetong007** [comment]
Originally the prediction was only executed at the last round, and this caused the bug. On the other hand it means there's actually no efficiency improvement.

I revised the code, now if it ends at `nround` then the prediction is made in the last round, otherwise it is made with the model at `bestInd` rounds. Thank you for your suggestion :)

**Comment by BlindApe** [comment]
Thank you, Tong.
