### ISSUE TITLE
[jvm-packages] xgboost4j 0.80 early stopping

### ISSUE THREAD

**Issue by xuchaoqun** [dmlc/xgboost#3631]
In class XGBoost.java, method 'train', the early stopping logic is too simple, if any criterion value is greater than that before, stop it.  But when evalMetric is 'auc', the stop condition must be reversed. So this code has not been finished yet?
```
        boolean decreasing = true;
        float[] criterion = metrics[metrics.length - 1];
        for (int shift = 0; shift < Math.min(iter, earlyStoppingRound) - 1; shift++) {
          **decreasing &= criterion[iter - shift] <= criterion[iter - shift - 1];**
        }

        if (!decreasing) {
          Rabit.trackerPrint(String.format(
                  "early stopping after %d decreasing rounds", earlyStoppingRound));
          break;
        }
```

**Comment by CodingCat** [comment]
I think we need a parameter passed in that paramBag to indicate which direction we prefer when doing early stopping
