### ISSUE TITLE
feature numbering starting from 0

### ISSUE THREAD

**Issue by alex3s** [dmlc/xgboost#3638]
featmap.txt has features numbered 0 to 125:

0	cap-shape=bell	i
125 habitat=woods i

but the train and test data has features numbered up to 126

For example row 3207 in agaricus.txt.train
0 4:1 7:1 14:1 21:1 29:1 34:1 36:1 39:1 49:1 54:1 55:1 65:1 69:1 75:1 82:1 88:1 92:1 95:1 102:1 106:1 119:1 126:1

This seems to result incorrectly name the features when performing task=dump of an otherwise correctly performing model.

**Comment by hcho3** [comment]
It looks like `mapfeat.py` produces a LIBSVM file with 1-based indexing: https://github.com/dmlc/xgboost/commit/a894ab6898f5ed525ca7dec89a79ea1fa7f49f5a

**Comment by alex3s** [comment]
I think the solution could be to include 

`0	target	int`

in the agaricus demo featmap.txt

So the whole file will look like this:

```
0	target	int
1	cap-shape=bell i
:
125	habitat=woods i

```
I have tested it on other datasets, it works this way, for me at least! :+1:

**Comment by hcho3** [comment]
Target is not a feature, so I don't think we should include in the feature map. Let me submit a pull request to produce LIBSVM file with 0-based indexing, so that feature index starts with 0.
