### ISSUE TITLE
How does xgboost predict method compute the value by the trained trees?

### ISSUE THREAD

**Issue by FeiYeYe** [dmlc/xgboost#364]
```
require(xgboost)
# load in the agaricus dataset
data(agaricus.train, package='xgboost')
data(agaricus.test, package='xgboost')
dtrain <- xgb.DMatrix(agaricus.train$data, label = agaricus.train$label)
dtest <- xgb.DMatrix(agaricus.test$data, label = agaricus.test$label)

param <- list(max.depth=2,eta=1,silent=1, objective="reg:linear")
nround = 2

# training the model for two rounds
bst = xgb.train(param, dtrain, nround, nthread = 2)
xgb.dump(bst, "~/tmp/xgboost.dumped.trees")

### predict using first full trees
ypred1 = predict(bst, dtest)
> head(ypred1)                                
[1] 0.08585283 0.94223028 0.08585283 0.08585283 0.02808681 0.94223028
```

I have difficulty deriving 0.08585283 for the very first test sample of ```agaricus.test$data``` using the dumped tree files. Should I just walk through each tree using the first row of ```agaricus.test$data``` and sum them up? like ```0.490741-0.9226```?

@hetong007 @tqchen Can you shed some light on this?

```
booster[0]
0:[f28<-1.00136e-05] yes=1,no=2,missing=1
  1:[f55<-1.00136e-05] yes=3,no=4,missing=3
    3:leaf=0.42844
    4:leaf=-0.427938
  2:[f108<-1.00136e-05] yes=5,no=6,missing=5
    5:leaf=-0.485704
    6:leaf=0.490741
booster[1]
0:[f59<-1.00136e-05] yes=1,no=2,missing=1
  1:[f66<-1.00136e-05] yes=3,no=4,missing=3
    3:leaf=0.0137908
    4:leaf=0.790517
  2:leaf=-0.9226
```

The first test data
```
> agaricus.test$data[1,c(29, 56, 60, 67, 109)]                
                     odor=none                stalk-root=club 
                             0                              1 
             stalk-root=rooted stalk-surface-below-ring=scaly 
                             0                              0 
       spore-print-color=green                                
                             0                                
```

**Comment by tqchen** [comment]
Note there is a missing direction here, which was defaults to 0. So the
value 0 goes to the missing branch, and value 1 was classified normally

On Thu, Jun 25, 2015 at 1:37 PM, Fei Ye <notifications@github.com> wrote:

> require(xgboost)
> # load in the agaricus dataset
> data(agaricus.train, package='xgboost')
> data(agaricus.test, package='xgboost')
> dtrain <- xgb.DMatrix(agaricus.train$data, label = agaricus.train$label)
> dtest <- xgb.DMatrix(agaricus.test$data, label = agaricus.test$label)
>
> param <- list(max.depth=2,eta=1,silent=1, objective="reg:linear")
> nround = 2
>
> # training the model for two rounds
> bst = xgb.train(param, dtrain, nround, nthread = 2)
> xgb.dump(bst, "~/tmp/xgboost.dumped.trees")
>
> ### predict using first full trees
> ypred1 = predict(bst, dtest)
> > head(ypred1)
> [1] 0.08585283 0.94223028 0.08585283 0.08585283 0.02808681 0.94223028
>
> I have difficulty deriving 0.08585283 for the very first test sample using
> the dumped tree files. Should I just walk through each tree using the first
> row of the test data and sum them up?
>
> @hetong007 <https://github.com/hetong007> @tqchen
> <https://github.com/tqchen> can you shed some light on this?
>
> booster[0]
> 0:[f28<-1.00136e-05] yes=1,no=2,missing=1
>   1:[f55<-1.00136e-05] yes=3,no=4,missing=3
>     3:leaf=0.42844
>     4:leaf=-0.427938
>   2:[f108<-1.00136e-05] yes=5,no=6,missing=5
>     5:leaf=-0.485704
>     6:leaf=0.490741
> booster[1]
> 0:[f59<-1.00136e-05] yes=1,no=2,missing=1
>   1:[f66<-1.00136e-05] yes=3,no=4,missing=3
>     3:leaf=0.0137908
>     4:leaf=0.790517
>   2:leaf=-0.9226
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/xgboost/issues/364>.
>



-- 
Sincerely,
------------------------------------------------
Tianqi Chen
Computer Science & Engineering, University of Washington

**Comment by FeiYeYe** [comment]
Do you mean feature value 0 is interpreted as missing? If so, the first sample of the test data shall stop at leaf 3 with value 0.42844 for the first tree, and stop at leaf 3 with value 0.0137908 for the second tree, how do I come up with the predicted value 0.08585283?

**Comment by FeiYeYe** [comment]
Oh i see the base_score is defaulted to 0.5, that makes sense. How do encode the missing branch split default value to be something other than 0?

**Comment by ParthaT123** [comment]
Hi,

My use case is objective = "binary:logistic" and eta = 0.5 or less than 1.

My tree is 

booster[0]
0:[order.1<12.2496] yes=1,no=2,missing=2,gain=1359.61,cover=7215.25
	1:[access.1<0.196687] yes=3,no=4,missing=4,gain=3.19685,cover=103.25
		3:leaf=-0,cover=1
		4:leaf=0.898305,cover=102.25
	2:[team<6.46722] yes=5,no=6,missing=6,gain=753.317,cover=7112
		5:leaf=0.893333,cover=55.25
		6:leaf=-0.943396,cover=7056.75
booster[1]
0:[issu.1<6.4512] yes=1,no=2,missing=2,gain=794.308,cover=5836.81
	1:[team<3.23361] yes=3,no=4,missing=4,gain=18.6294,cover=67.9586
		3:leaf=0.609363,cover=21.4575
		4:leaf=1.28181,cover=46.5012
	2:[case<6.74709] yes=5,no=6,missing=6,gain=508.34,cover=5768.85
		5:leaf=1.15253,cover=39.2126
		6:leaf=-0.629773,cover=5729.64

Will the procedure for predicting will same as the above example?

**Comment by zweicoder** [comment]
Is there any programmatic way to parse the trees? It looks like we can only parse the string of the trees right now

**Comment by rainness** [comment]
@FeiYeYe , I am still confused about how to get the prediction value of 0.08585283 through the dumped tree, can you tell me how?

> Oh I see, the base_score is defaulted to 0.5, that part makes sense to me. Now I can correctly compute the prediction value based on the dumped tree file and input features. How to encode the missing branch split default value to be something other than 0? I tried some options but none seems to change the output of dumped tree for me:

**Comment by ddzr** [comment]
@rainness 

Hello, I was also trying to figure out this. Below is my naive thought. 

The first sample of the test data should stop at leaf 4 with value -0.427938 for the first tree. As mentioned above, 'there is a missing direction here, which was defaults to 0. So the
value 0 goes to the missing branch', f28=0 would be considered as missing, so it should go to 1:[f55<-1.00136e-05] due to [f28<-1.00136e-05] missing=1. Then as f55 =1, the first sample of test data should go to leaf 4 due to [f55<-1.00136e-05] no=4. 

The first sample of test data would stop at leaf 3 with value 0.0137908 for the second tree. Summing up all the scores would lead to 0.5 (base score)-0.427938+0.0137908 = 0.085853.
