### ISSUE TITLE
 [jvm-packages] Confusion about param map keywords

### ISSUE THREAD

**Issue by vincent-grosbois** [dmlc/xgboost#3641]
Hello!
After upgrade XGBoost we have integrated this (https://github.com/dmlc/xgboost/pull/3387/) PR

However, it seems that now some parameters are parsed differently, and might require to be sent with 2 keywords in the parameter maps.
For instance : 
- for number of workers, "num_workers", "nWorkers" and "numWorkers" seem to all be parsed at some point. As I understand, the correct way should now be "numWorkers" (as parsed here: https://github.com/dmlc/xgboost/blob/1c08b3b2eaf356a448c156271c394692dc698065/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/GeneralParams.scala#L38), but it seems that the C++ code parses the old "num_workers" keyword, which is still present in every test. It seems that it will bug if I don't send both.
 - same with "num_round" and "numRound", the examples still have "num_round" but the scala parser parses "numRound"

Can anybody confirm this is not the intended behavior? Or am I missing something?

**Comment by CodingCat** [comment]
please add [jvm-packages] in your title when you ask questions about that package, it will help me to identify these questions

please read the paragraph after the code example: https://xgboost.readthedocs.io/en/latest/jvm/xgboost4j_spark_tutorial.html#training

**Comment by vincent-grosbois** [comment]
Thanks for the quick response!
indeed it seems that the official keyword is "num_workers" for instance. Yet the GeneralParams.scala class will parse "numWorkers" right? What is it used for?

**Comment by CodingCat** [comment]
both are supported 

you can use the underscore style (xgboost style) and you can also use setters such as setNumWorkers


the magic is in 

https://github.com/dmlc/xgboost/blob/1c08b3b2eaf356a448c156271c394692dc698065/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/GeneralParams.scala#L224-L247
