### ISSUE TITLE
Getting margin scores with 'XGBClassifier.predict(output_margin=True)' doesn't work as intended

### ISSUE THREAD

**Issue by Sonchiwon** [dmlc/xgboost#3648]
From v0.72 'XGBClassifier.predict_proba()' has been changed not to accept 'output_margin'.
(https://github.com/dmlc/xgboost/blob/96826a35155d42f78cd4253b3d134a208dbbaccb/NEWS.md#v072-20180601)

And 'https://github.com/dmlc/xgboost/pull/3343' suggests 
> **If users want to output margin, they can just use predict(data, output_margin=True)**.

but 'XGBClassifier.predict()' is not suitable to get margin scores because it just selects indexes in each row. 
```
...
        if len(class_probs.shape) > 1:
            column_indexes = np.argmax(class_probs, axis=1)
        else:
            column_indexes = np.repeat(0, class_probs.shape[0])
            column_indexes[class_probs > 0.5] = 1
...
```

I agree for

> XGBClassifier.predict_proba is to predict class probabilities, so it doesn't make sense to support output_margin. 

, but to check raw margins before they are transformed to probabilities, I reverted https://github.com/dmlc/xgboost/pull/3343/commits/a776be5591f2d11d5d436679cd40450c358b8e31 in my project temporarily. 

So please consider to add new method dedicated for 'output_margin=True' in 'XGBClassifier'.

For your reference I attached a test code in below to describe this issue.
```
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
import numpy as np

# split data into X and y of iris dataset
iris = load_iris()
X = iris.data
Y = iris.target
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.33, random_state=7)
model = XGBClassifier().fit(X_train, y_train)

# make predictions for test data
y_pred = model.predict(X_test, output_margin=False)
print(y_pred)
#out : [2 1 0 1 1 0 1 1 0 1 2 1 0 2 0 2 2 2 0 0 1 2 1 1 2 2 1 1 2 2 2 1 0 2 1 0 0 0 0 2 2 1 2 2 1 0 1 1 2 0]
y_pred = model.predict(X_test, output_margin=True)
print(y_pred)
#out : [2 1 0 1 1 0 1 1 0 1 2 1 0 2 0 2 2 2 0 0 1 2 1 1 2 2 1 1 2 2 2 1 0 2 1 0 0 0 0 2 2 1 2 2 1 0 1 1 2 0]
#Same with 'output_margin=False'
```

**Comment by hcho3** [comment]
This is indeed a bug. We'll need to revise `XGBClassifier.predict()` for `output_margin=True`.

**Comment by hcho3** [comment]
See if #3651 fixes your problem

**Comment by Sonchiwon** [comment]
I've checked #3651 works well on my project and above 'iris' example also.

Thank you for your fast response!

**Comment by Sonchiwon** [comment]
I have a question for the #3651.
I'm beginner of python but familiar to other S/W programming languages.

If #3651 is merged, `XGBClassifier.predict()` has two 'types' of returning.
Below is the variation of the 'iris' sample code and it shows two 'types' of returning for calling 'XGBClassifier.predict()'.

```
y_pred = model.predict(X_test[0:1, :], output_margin=False)
print(y_pred) # [2]
y_pred = model.predict(X_test[0:1, :], output_margin=True)
print(y_pred) # [[-2.0260496 -1.5309823  2.7310572]]
```

I know that python permits every types for returning in a function.
But in this case, clients of XGBoost library should be aware of parameter 'output_margin' to process the returning value(s).
It needs branching S/W routine by returning type(==value of output_margin) and the branching propagates up to start point of using 'XGBClassifier.predict()'.

I hope below sudo example will be helpful to describe my concern to you.

```
def wrapper_lowlevel(output_margin):
    in_lowlevel = XGBClassifier.predict(output_margin)
    if output_margin: # Or checking instance type of returning
        ....
    else:
        ....
    return in_lowlevel

def wrapper_midlevel(output_margin):
    in_midlevel = wrapper_lowlevel(output_margin)
    if output_margin: # Or checking instance type of returning
        ....
    else:
        ....
    return in_midlevel

def client_api(output_margin)
    result = wrapper_midlevel(output_margin)
    if output_margin: # Or checking instance type of returning
        ....
    else:
        ....
    return result
```
When an external project imports `client_api`,  same branched processing can be necessary.

So how about to add new function for `output_margin`?

**Comment by hcho3** [comment]
> XGBClassifier.predict() has two 'types' of returning

No, there is only one return type: `numpy.ndarray`. The `output_margin` parameter only changes the dimension of the returned array. Since the return type is always `numpy.ndarray`, no branching on the part of the client would be necessary.

**Comment by Sonchiwon** [comment]
Ok, I got it.
Thank you for your kind description.
