### ISSUE TITLE
Request : Enable PDF Export of Documentation (https://xgboost.readthedocs.io/)

### ISSUE THREAD

**Issue by Gokkulnath** [dmlc/xgboost#3650]
Currently  the documentation can be exported as HTML  pages only. It would be great if PDF option is enabled, which would become handy for reference.

~Gokkul

**Comment by hcho3** [comment]
I enabled PDF export option in ReadTheDocs. PDF should be available shortly.

**Comment by Gokkulnath** [comment]
@hcho3  Thanks a lot !
