### ISSUE TITLE
Multiclass with max_depth = 1, nround = 1, why the results are not binary?

### ISSUE THREAD

**Issue by minkim88** [dmlc/xgboost#3655]
I've got a really basic question here.
Since xgboost is based on CART algorithm, it uses binary recursive partitioning.

Knowing this, if I set max_depth = 1, nround = 1, there should be only one tree with two child nodes.
This means that in a **multi-class** classification, even if there are 4 classes, the predictions should will **binary**.

However, when I try this in R, the prediction **results are multi-class**. How is this possible with one tree with two terminal nodes?

I'm sorry if this is a stupid question, I'm fairly new to data science.

**Comment by hcho3** [comment]
For multi-class classification, XGBoost produces `[number of classes] * [number of iterations]` trees. So in your case, you actually have 4 decision trees not one. Each of the 4 trees produces a margin score for the corresponding class, and the class with the highest margin score is chosen as most likely.

**Comment by hcho3** [comment]
Feel free to post at https://discuss.xgboost.ai/ if you have other questions.

**Comment by minkim88** [comment]
Thanks for the reply!!
