### ISSUE TITLE
Check failed: Loss::CheckLabel(y) label must be in [0,1] for logistic regression

### ISSUE THREAD

**Issue by Venkat-Rajgopal** [dmlc/xgboost#3662]
Is this a bug with train function `xgboost()` ? The train labels are updated as `numeric` but still i see the same error that the labels must be [0,1] for log reg. 

### What i have tried.
First method.
```
train.y <- as.factor(train.y)

levels(train.y)[levels(train.y) =='klar'] <- 0
levels(train.y)[levels(train.y) =='trüb'] <- 1
train.y <- as.numeric(train.y)
```
### alternative
Second method.  
`train.y <- as.numeric(as.factor(train.y))`
```
> class(train.y)
[1] "numeric"
```
```
# convert dataset into Dmatrix
dtrain <- xgb.DMatrix(data =as.matrix(train.x), label= train.y)

# train model 
model.xgb <- xgboost(data = dtrain, # the data   
                     max.depth = 3,
                     nround = 50, # boosting iterations
                     objective = "binary:logistic")  # the objective function
```

### Error
```
Error in xgb.iter.update(bst$handle, dtrain, iteration - 1, obj) : 
  [12:55:32] amalgamation/../src/objective/regression_obj.cc:98: Check failed: Loss::CheckLabel(y) label must be in [0,1] for logistic regression
```

How can i get around this ? 

Thanks

**Comment by trivialfis** [comment]
What the error saying is the value of label should be in close interval [0, 1]. Perhaps there's a label in your data that doesn't fall into this interval?

**Comment by Venkat-Rajgopal** [comment]
Made a small change as `train.y <- as.numeric(as.factor(train.y)) - 1 ` Since `as.numeric(as.factor(train.y))` produced vector of 1 and 2.
