### ISSUE TITLE
dump_model function doesn't have "dump_format" argument in pip build ver 0.80

### ISSUE THREAD

**Issue by Idodox** [dmlc/xgboost#3671]
The dump_model function is listed in the v0.80 documentation and it appears to be correctly defined in the git repo.

however, when installing the latest 0.80 version of the package through pip the "dump_model" function doesn't have the "dump_format" argument. It appears to be an older version of the function.

I've force-reinstalled the package to make sure it wasn't a local problem - same result.

**Comment by hcho3** [comment]
I think you are looking at the doc for the latest (master) version. In the doc for 0.80, `dump_model()` method doesn't have parameter `dump_format`. See https://xgboost.readthedocs.io/en/release_0.80/python/python_api.html#xgboost.Booster.dump_model
