### ISSUE TITLE
xgb.importance doesn't work with data.table 1.9.5

### ISSUE THREAD

**Issue by Couvade** [dmlc/xgboost#368]
Hi guys,

When data.table 1.9.5 is installed (current development version) there is an issue where the "==" operator doesn't appear to be supported if it is a vector on the RHS, it suggests using %in% instead.

Sorry I don't know how to use github to commit the change but I'm hacking around it in my local version by changing the == to %in%  in xgb.model.dt.tree:

Old code
```R
	yes <- allTrees[!is.na(Yes), Yes]
	set(allTrees, i = which(allTrees[, Feature] != "Leaf"), j = "Yes.Feature", 
			value = allTrees[ID == yes, Feature])
	set(allTrees, i = which(allTrees[, Feature] != "Leaf"), j = "Yes.Cover", 
			value = allTrees[ID == yes, Cover])
	set(allTrees, i = which(allTrees[, Feature] != "Leaf"), j = "Yes.Quality", 
			value = allTrees[ID == yes, Quality])
	no <- allTrees[!is.na(No), No]
	set(allTrees, i = which(allTrees[, Feature] != "Leaf"), j = "No.Feature", 
			value = allTrees[ID == no, Feature])
	set(allTrees, i = which(allTrees[, Feature] != "Leaf"), j = "No.Cover", 
			value = allTrees[ID == no, Cover])
	set(allTrees, i = which(allTrees[, Feature] != "Leaf"), j = "No.Quality", 
			value = allTrees[ID == no, Quality])
	allTrees
```

New code
```R
	yes <- allTrees[!is.na(Yes), Yes]
	set(allTrees, i = which(allTrees[, Feature] != "Leaf"), j = "Yes.Feature", 
			value = allTrees[ID %in% yes, Feature])
	set(allTrees, i = which(allTrees[, Feature] != "Leaf"), j = "Yes.Cover", 
			value = allTrees[ID %in% yes, Cover])
	set(allTrees, i = which(allTrees[, Feature] != "Leaf"), j = "Yes.Quality", 
			value = allTrees[ID %in% yes, Quality])
	no <- allTrees[!is.na(No), No]
	set(allTrees, i = which(allTrees[, Feature] != "Leaf"), j = "No.Feature", 
			value = allTrees[ID %in% no, Feature])
	set(allTrees, i = which(allTrees[, Feature] != "Leaf"), j = "No.Cover", 
			value = allTrees[ID %in% no, Cover])
	set(allTrees, i = which(allTrees[, Feature] != "Leaf"), j = "No.Quality", 
			value = allTrees[ID %in% no, Quality])
	allTrees
```

**Comment by hetong007** [comment]
@Couvade Thank you for pointing this out. Generally if you want to commit to another repository, you can

1. Fork it to your account 
2. Do your work on the code
3. Open a pull request back to the original repository.

It is very welcome :)

**Comment by pommedeterresautee** [comment]
Can you please check it works with 1.94? (I think it will )

Moreover what about using .() instead of %in%?
I think it will use binary search that way instead of vector search. (I just discovered this syntax that's why I didn't used it in xgboost yet ).

From my understanding vector search is better for small dt. So benchmark is required to validate this approach.

Kind regards,
Michaël

**Comment by pommedeterresautee** [comment]
Ok PR is merged. Close the issue.
