### ISSUE TITLE
Unexpectedly results by scaling the weight vector

### ISSUE THREAD

**Issue by qwerasd903** [dmlc/xgboost#3684]
Hi! 

I am using a sample weight vector as one of my training parameters. However, I found that when I scale the weights to a different level (the relative weight between each sample is still the same), the results (like AUC) will also be different. If you scale the weights to very small (say 10^(-3)), the AUC will even be only 0.5. This doesn't make sense to me, as I expect only the relative weight should matter. You can use whatever scale you want as your absolute weight.

Is this normal in XGBosst? If so, what would be the best way to put the scale of the weights?

Jay

**Comment by qwerasd903** [comment]
I have checked it. The prediction also changes. It seems the average weight needs to get as close as 1 in order to get the best prediction.

**Comment by hcho3** [comment]
@qwerasd903 Can you post a small example that I can run?

**Comment by qwerasd903** [comment]
Hi the examples are attached. example.py uses the weights whose average value is 1. While example_small_wt uses the weights which are very small and will get AUC = 0.5.

The example will also plot the score distribution of validation samples and you can see it is very different between two examples.

[example.zip](https://github.com/dmlc/xgboost/files/2375830/example.zip)

**Comment by khotilov** [comment]
@qwerasd903 When you scale the weights, the min_child_weight, alpha, and lambda parameters need to be scaled as well. In addition, in your example.py, you are changing the relative weight of two classes - it might potentially be not what you want.
