### ISSUE TITLE
[jvm-packages] Loading locally trained models into XGBoost4J-Spark?

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#3689]
I've seen a few people asking about a way to load locally trained model into XGBoost4J-Spark. In version 0.72, you could write
```scala
val model = XGBoost.loadModel("./my_model.model")
val classification_model = new XGBoostClassificationModel(model)
```
which uses the constructor `new XGBoostClassificationModel(booster: Booster)`. However, version 0.80+ no longer supports construction of `XGBoostClassificationModel` from `Booster` object.

**Comment by CodingCat** [comment]
we intentionally limit the access to native booster in 0.8. The workaround is to have a bridge class under package `ml` and use the constructor at https://github.com/dmlc/xgboost/blob/release_0.80/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassifier.scala#L208-L211

**Comment by hcho3** [comment]
@CodingCat Does the current XGBoost codebase have such bridge class?

**Comment by CodingCat** [comment]
no, it is supposed to be created by the user so that they can have the flexibility to make it either as an singleton object or a class or a trait to be extended....

**Comment by hcho3** [comment]
Is there a reference or tutorial for creating ML bridge class? I'd like to update XGBoost4J-Spark tutorial to show how to load locally-trained models.

**Comment by CodingCat** [comment]
no...I am not sure if we really want to do that...because for scala coders, this is a very common trick to workaround the package-access limitation

**Comment by hcho3** [comment]
Got it. Closing it now

**Comment by dreamsuifeng** [comment]
> Got it. Closing it now
hi，I have met the same problem. Do you have any solution?

**Comment by hcho3** [comment]
@dreamsuifeng You should write a bridge class, as discussed earlier.

**Comment by dreamsuifeng** [comment]
> @dreamsuifeng You should write a bridge class, as discussed earlier.
I'm a newer of scala, could you give me a base code? thank you

**Comment by hcho3** [comment]
@abhinavm24 The code was only valid for version 0.72

**Comment by abhinavm24** [comment]
Sorry, I intended to say how you created the bridge class to import the local model and score it in spark.

**Comment by abhinavm24** [comment]
Sorry, @hcho3. I intended to say, how you created the bridge class to import the local model and score it in spark.

**Comment by abhinavm24** [comment]
Can someone please share the bridge class that can be used to load the R xgboost classification model to Spark?

@hcho3 @CodingCat

**Comment by borisclemencon** [comment]
> we intentionally limit the access to native booster in 0.8. The workaround is to have a bridge class under package `ml` and use the constructor at https://github.com/dmlc/xgboost/blob/release_0.80/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassifier.scala#L208-L211

It seems that training a xgb model in python or R, and loading it for inference in Spark is a frequent pattern. Is it possible to open the constructor like in 0.72 for future versions?

**Comment by CodingCat** [comment]
bridge class https://github.com/CodingCat/XGBoostExperiments/blob/master/xgboost_exp_0.80/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassificationModelBridge.scala

**Comment by borisclemencon** [comment]
Thanks! However, when I train a model in R, and load it in Spark, the predictions does not correspond and the parameters are all reset to default in Spark. Any idea? 
https://github.com/dmlc/xgboost/issues/4104

**Comment by linetor** [comment]
When I want to use XGBoostClassificationModelBridge.scala, I got error like 

` too many arguments for constructor XGBoostClassificationModel: (uid: String)ml.dmlc.xgboost4j.scala.spark.XGBoostClassificationModel`

Anyone have any idea for using local model for spark?
