### ISSUE TITLE
# min example for the bug of generatePartialDependenceData

### ISSUE THREAD

**Issue by SebastianHapp** [dmlc/xgboost#3691]
# plotPartialDependence does not work for regression tasks

Dear all,

I encountered the following issue using the generatePartialDependenceData.
It seems to me that classification problems work, whereas regression problems do not.

Pls find below the reproducible example generated from the iris dataset.
Do you have any ideas for this bug?

Thanks in advance,
Sebastian

min example for the bug of generatePartialDependenceData
classification toy example with iris dataset

lrn = makeLearner("classif.rpart", predict.type = "prob")
fit = train(lrn, iris.task)
pd = generatePartialDependenceData(fit, iris.task, "Petal.Width")
plotPartialDependence(pd, data = getTaskData(iris.task))

regression toy example with iris dataset

t_data <- as.data.frame(as.data.table(lapply(iris, function(x){as.numeric(x)})))
tsk <- makeRegrTask(data = t_data, target = "Sepal.Length")
lrn <- makeLearner("regr.xgboost", predict.type = "response", eta = 0.1, 
                   max_depth = 8, min_child_weight = 20, 
                   subsample = 0.75, colsample_bytree = 0.75, 
                   nrounds = 2, nthread = cl_n, objective = "reg:linear", 
                   eval_metric = "rmse")
fit = train(lrn, tsk)
pd = generatePartialDependenceData(fit, tsk, "Petal.Width")
plotPartialDependence(pd, data = getTaskData(iris.task))

**Comment by hcho3** [comment]
I'm getting error
```
Error in predict.xgb.Booster(m, newdata = data.matrix(.newdata), ...) : 
  Feature names stored in `object` and `newdata` are different!
```

Is this what you mean by regression problems not working?

**Comment by SebastianHapp** [comment]
Yes. When debugging the process you see that the problem comes from the function "makeDesign" which changes column order.

  library(R.utils)
  makeDesign2 <- mmpf:::makeDesign;
  mymakeDesign <- function(data, vars, n=n, uniform = TRUE, points, int.points) {makeDesign2(data, vars, n, uniform = uniform, points, int.points)[colnames(data)]};
  reassignInPackage("makeDesign", pkgName="mmpf", mymakeDesign);   

solves the problem.

**Comment by hcho3** [comment]
@SebastianHapp Since the bug originates from an external package (mmpf), I'm not sure what we can do.

**Comment by hcho3** [comment]
So no change is required on the part of XGBoost then?

**Comment by SebastianHapp** [comment]
yes, you are right! I will close the issue and address this in the mle section!
