### ISSUE TITLE
[jvm-packages] xgboost4j-spark crossvalidation

### ISSUE THREAD

**Issue by dwscu** [dmlc/xgboost#3694]
hello,I get train data from hbase,and use spark mllib to cross validate xgboost.but I have a problem,when I use rdd.persist, the auc value is near 0.5; and if I do not use rdd.persist, the auc value is 0.7

**Comment by hcho3** [comment]
Can you post your script?

**Comment by dwscu** [comment]
> Can you post your script?

[xgboost_cv.zip](https://github.com/dmlc/xgboost/files/2377634/xgboost_cv.zip)

in line 42, comment or uncomment it ,i get very different result

**Comment by CodingCat** [comment]
any change on TrueNegative and FalseNegative, etc.?

**Comment by dwscu** [comment]
> any change on TrueNegative and FalseNegative, etc.?

sorry for reply later,There are few change on TrueNegative and FalseNegative.But it seems when I use rdd.persist,the model is under fitting,and when I not use rdd.persist,the model is over fitting.
