### ISSUE TITLE
[jvm-packages] xgboost4j-spark 0.72: model transform when booster is dart

### ISSUE THREAD

**Issue by David082** [dmlc/xgboost#3700]
Hi there,

The DART booster note says:
Specify ntree_limit when predicting with test sets
By default, bst.predict() will perform dropouts on trees. To obtain correct results on test sets, disable dropouts by specifying a nonzero value for ntree_limit.

But I haven't seen ntree_limit when using model.transform() in xgboost4j-spark 0.72.
So, how can I use the dart boost for predict in spark?

**Comment by CodingCat** [comment]
please upgrade to 0.8 and set `treeLimit` in classification/regression model
