### ISSUE TITLE
Prediction for some samples does not follow the json that is obtained by get_dump()

### ISSUE THREAD

**Issue by Nirmal-Neel** [dmlc/xgboost#3702]
![booster_98](https://user-images.githubusercontent.com/32963085/45546105-ed60f080-b839-11e8-81de-45344d2ff43e.JPG)
This is the 99th booster of my model which I obtained from the get_dump() function.
When I perform model._Booster.predict(X_test, pred_leaf=True), then for the 99th estimator it gives output as 8. That means, for that estimator, output node number is 8, which is -0.094418548 here.

My input data is:
[cylinders] := 4.0 
[displacement] := 98.0 
[horsepower] := 63.0 
[weight] := 2051.0
[acceleration] := 17.0 
[model year] := 77.0
[origin] := 1.0 

So in the estimator, the first condition is model_year < 80, which is true. So it goes to true node.
Then second condition is horsepower < 69, which is also true. So again it goes to true node.
Then third condition is horsepower <  64, which is again true. So it should give true node value as 0.0231908988, whose node id is 7.

Then why model._Booster.predict(X_test, pred_leaf=True) function giving 8 as output for that estimator?

**Comment by hcho3** [comment]
Can you post a script that reproduce this error?

**Comment by Nirmal-Neel** [comment]
Manual steps are involved in this case.
1) Getting the leaf predictors from the model.
2) Dumping all predictors to a json file using dump_model() function.
3) For a given sample performing manual calculation using the json file as given above to get the predictions of each predictor.
4) Comparing the true leaf node's ID with the IDs fetched from the model in step 1.

In step 4, some IDs do not match.

**Comment by hcho3** [comment]
Thanks for describing your steps. It would be nice if you can share your model and dataset so that we can start fixing the bug.

**Comment by Nirmal-Neel** [comment]
[model.zip](https://github.com/dmlc/xgboost/files/2384735/model.zip)

The zip file contains
1) The model (model.bin)
2) The dataset (auto-mpg.csv)
3) A jupyter notebook to show the flow (test.ipynb and test.html)
4) The dumped json file (model.json)

For the dataset if you perform train_test_split with random_state = 101 then you will find the previously mentioned error with 23rd test sample and 99th predictor.

**Comment by hcho3** [comment]
I'm going off to a 3-day vacation, but I'll look at it afterwards.

**Comment by Nirmal-Neel** [comment]
Thanks and happy vacation.

**Comment by Nirmal-Neel** [comment]
Is it true that the JSON file can not be used for prediction? Do you have any update?

**Comment by hcho3** [comment]
@Nirmal-Neel I injected some diagnostic code and found out that **the C++ code has different set of split points than the JSON dump**:

`RegTree::GetLeafIndex()` from include/xgboost/tree_model.h:
```
node_id = 0, split_index = 5, fvalue = 77
    fvalue = 77, split_value = 79.5
    ==> fvalue < split_value, go to left child node 1
node_id = 1, split_index = 2, fvalue = 63
    fvalue = 63, split_value = 68.5
    ==> fvalue < split_value, go to left child node 3
node_id = 3, split_index = 2, fvalue = 63
    fvalue = 63, split_value = 63
    ==> fvalue >= split_value, go to right child node 8
```

The JSON model dump:
```
node_id = 0, split_index = 5, fvalue = 77.0
    fvalue = 77.0, split_value = 80
    ==> fvalue < split_value, go to left child node 1
node_id = 1, split_index = 2, fvalue = 63.0
    fvalue = 63.0, split_value = 69
    ==> fvalue < split_value, go to left child node 3
node_id = 3, split_index = 2, fvalue = 63.0
    fvalue = 63.0, split_value = 64
    ==> fvalue < split_value, go to left child node 7
```

**Comment by hcho3** [comment]
It turns out the JSON dump was formatted incorrectly. For integer features, the JSON dump will show rounded-up values of thresholds. So 79.5 is replaced with 80, 68.5 is replaced with 69 and so forth. The threshold value 63.0 in node 3 was rounded up as well, when it shouldn't have been.

I will submit a patch so that integer thresholds don't get rounded up.

**Comment by hcho3** [comment]
See #3717.

**Comment by Nirmal-Neel** [comment]
Thank you. I will check it and will confirm you.
