### ISSUE TITLE
updater='grow_gpu_hist' produces unstable results on equivalent but not identical sparce matrices

### ISSUE THREAD

**Issue by mrgutkun** [dmlc/xgboost#3707]
Here's a notebook with reproduction: [xgboost-unstable-grow-gpu-hist-reproduction.zip](https://github.com/dmlc/xgboost/files/2389979/xgboost-unstable-grow-gpu-hist-reproduction.zip)

Here's the data: [reproduction_data.zip](https://github.com/dmlc/xgboost/files/2389960/reproduction_data.zip)

Does not reproduce on 0.72, but does reproduce on 0.80 and some pretty recent commit that I lost id of;  I assume this reproduces on current master, but will edit after verifying.

**Comment by hcho3** [comment]
Do you see the same problem with CPU hist?

**Comment by mrgutkun** [comment]
No; `grow_histmaker`, `grow_fast_histmaker`, `grow_local_histmaker`, `grow_colmaker` and `grow_gpu` each give me identical results at those two datasets, and their 0th epoch merrors are all identical.
`grow_skmaker` is not stable even on the same dataset, although occasionally its 0th epoch matches with those above.
Incidentally, Is there a complete list of updaters somewhere? [Docs](https://github.com/dmlc/xgboost/blob/master/doc/parameter.rst) list some, but all cpu updaters and no gpu updaters.

**Comment by thvasilo** [comment]
> Incidentally, is there a complete list of updaters somewhere? Docs list some but not all cpu updaters and none of the gpu updaters.

Good point @mrgutkun,  currently it's not clear what's the distinction between the `updater` and `tree_method` parameters.

**Comment by hcho3** [comment]
@thvasilo The `tree_method` parameter is supposed to cover 90% of use cases. The `updater` parameter is an "expert" parameter that's less well documented. The documentations says
```
This is an advanced parameter that is usually set automatically, depending on some other parameters.
```

So usually it is sufficient to set `tree_method`.

**Comment by hcho3** [comment]
Oops clicked wrong button.

**Comment by thvasilo** [comment]
Thanks for the clarification @hcho3. Out of curiosity are there sanity checks in place that would stop/inform users of passing contradicting values to these parameters?

**Comment by hcho3** [comment]
@thvasilo #3849 clarifies the behavior of `tree_method` and `updater`.

**Comment by trivialfis** [comment]
Closing in favour of https://github.com/dmlc/xgboost/issues/5023
