### ISSUE TITLE
[jvm-packages] `native/xgboost4j.cpp` missing get and set attr methods

### ISSUE THREAD

**Issue by a-johnston** [dmlc/xgboost#3711]
There are stubs in [`native/xgboost4j.h`](https://github.com/dmlc/xgboost/blob/0988fb191f6aacde50020b2d5e94c92df2ac4e58/jvm-packages/xgboost4j/src/native/xgboost4j.h#L228) but no definitions. Similarly, wrapper methods could be added to the java/scala booster objects. I haven't looked much into this yet but I think it's just a lesser used feature of the python/native/R libs that was missed for the jvm packages.

**Comment by hcho3** [comment]
@a-johnston Would you be interested in adding them?

**Comment by CodingCat** [comment]
resolved by https://github.com/dmlc/xgboost/pull/4336
