### ISSUE TITLE
early stopping criteria not working with eval_metric "aucpr" 

### ISSUE THREAD

**Issue by ankurkhurana03** [dmlc/xgboost#3712]
The metrics aucpr should increase for the convergence, whereas the metrics required for early stopping criteria should be minimized;

**Comment by hcho3** [comment]
Try setting `maximize=True` when calling `xgboost.train()`.

**Comment by ankurkhurana03** [comment]
thanks, that worked!

**Comment by imranahmed96** [comment]
@hcho3 Thank-you for the lightning-fast reply! Perfect, that sounds great! :smile:

**Comment by PhilipMay** [comment]
I think this is still a bug that should be fixed. The `maximize = True` thing is just a workaround.
But this is still a bug imo.

With auc early_stopping is working correctly (it tries to maximaize) I see no reason why this should
not be the case with aucpr.

**Comment by batmax2015** [comment]
@hcho3 is the change already available?

**Comment by hcho3** [comment]
@batmax2015 The change is not part of the stable 0.81 release. You should use the latest source in the mean time.

**Comment by johntiger1** [comment]
Still not working for me (for auc-pr)
