### ISSUE TITLE
[python-package] DMatrix.slice does not propagate feature_names

### ISSUE THREAD

**Issue by JovanVeljanoski** [dmlc/xgboost#3714]
Hi, 

I noticed today that in a case such as the following:
```
dtrain = xgboost.DMatrix(data = pandas_dataframe)
dval    = dtrain.slice(indices)
```

`dval` has the default feature names ('f0', 'f1', 'f2', etc..), and does not inherit those from `dtrain`. 
I checked the source code, and at first glance the feature names should be passed to the output of `DMatrix.slice`, but in practice this does not happen. 

An easy work around from the user side is to just do:
```
dval.feature_names = dtrain.feature_names
```
but by looking at the source code, this is supposed to be the default behaviour of `DMatrix.slice`.

I am using xgboost version 0.80 installed via conda from conda-forge. 

Thanks!

**Comment by hcho3** [comment]
#3766 should fix it. Thanks!
