### ISSUE TITLE
[jvm-packages] How the XGBoostEstimator generate the probabilities?

### ISSUE THREAD

**Issue by TangShuangshuo** [dmlc/xgboost#3718]
I generate a pmml model file using XGBoostEstimator in scala. I want to load the pmml file and write a predictive function in C++. But I'm not clear how to predict the result. According to the file, I sum the arrived leaf score of all trees and get a.  Next I pass the a to the sigmoid funtion, eg, b = 1/(1 + exp(a)). However, b differs from the probabilities. Can anyone elaborate on the prediction process? The params and the pmml file as follows:
val paramMap = List(
  "ntree_limit" ->1,
  "num_round" -> 1,
  "booster" -> "gbtree",
  "objective" -> "binary:logistic",
  "base_score"->0.5
).toMap

the pmml files:
https://github.com/TangShuangshuo/spark2pmll/blob/master/gbdt.pmml9

**Comment by TangShuangshuo** [comment]
In fact, I add the base score(0.5). According to the pmml file, if I provide the data with feature “9004”=0, "2506"=0, then I reach node 4 which score is -0.5438435. There are 1 tree in all. That is to say, the sum of leaf score is -0.5438435. Then I add the base score(0.5), then score=-0.5438435 + 0.5=-0.0438435. Then pass the score to sigmoid, 1 / (1 + exp(-(-0.0438435)))=0.48904. However, the output column probabilities is [0.6200730800628662,0.3799269199371338]. Is there anything wrong with me? Is there any way to output rawPrediction?

**Comment by hcho3** [comment]
Can you save XGBoostEstimator into a model file so that it can be loaded from Python? Please call model.get_dump() from Python and post the output.

**Comment by hcho3** [comment]
Also there is distinction between feature value 0 and missing value. Maybe your original input contains missing values, not 0s?

**Comment by TangShuangshuo** [comment]
There is no missing values, I print a sample.
|label|1004                |1007               |1009               |1013                |8005              |8007              |8008|10013             |1514|8004|8012|2502|2503|2504|2505|2506|2507|2508|2509|9001|9004|10005|10006|10007|10008|10009|10010|10011|10012|1004_index|1004_Vec          |1007_index|1007_Vec         |1009_index|1009_Vec     |1013_index|1013_Vec     |8005_index|8005_Vec     |8007_index|8007_Vec     |8008_index|8008_Vec     |10013_index|10013_Vec    |vectorFeature                                                                                                                                              |probabilities                          |prediction|
+-----+--------------------+-------------------+-------------------+--------------------+------------------+------------------+----+------------------+----+----+----+----+----+----+----+----+----+----+----+----+----+-----+-----+-----+-----+-----+-----+-----+-----+----------+------------------+----------+-----------------+----------+-------------+----------+-------------+----------+-------------+----------+-------------+----------+-------------+-----------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------+----------+
|1    |13533035807390868163|6627214347076536788|7277620126963242199|14246401412233225735|982172615075650808|873996356351234391|NA  |402788895916821208|819 |9   |1   |0   |0   |0   |3   |0   |0   |3   |1   |0   |0   |-1   |-1   |-1   |-1   |-1   |-1   |-1   |-1   |885.0     |(1460,[885],[1.0])|114.0     |(127,[114],[1.0])|0.0       |(1,[0],[1.0])|0.0       |(6,[0],[1.0])|2.0       |(9,[2],[1.0])|2.0       |(3,[2],[1.0])|0.0       |(9,[0],[1.0])|0.0        |(8,[0],[1.0])|(57,[0,1,9,18,19,28,36,37,38,42,45,46,49,50,51,52,53,54,55,56],[1.0,1.0,1.0,1.0,1.0,1.0,819.0,9.0,1.0,3.0,3.0,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0])|[0.6200730800628662,0.3799269199371338]|0.0       |

**Comment by hcho3** [comment]
I see. Try importing the model from Python.

**Comment by TangShuangshuo** [comment]
I also want to ask if the column probabilities is transformed by the rawPrediction with sigmoid under my current parameters,or there may be other ways of transformation?

**Comment by hcho3** [comment]
It should be sigmoid for binary classification. Can you post the dump you get after importing the model into Python?

**Comment by hcho3** [comment]
See https://xgboost.readthedocs.io/en/latest/jvm/xgboost4j_spark_tutorial.html#interact-with-other-bindings-of-xgboost for instructions

**Comment by hcho3** [comment]
For 0.72 version, run `model.booster.saveModel()`

**Comment by hcho3** [comment]
Any updates?

**Comment by TangShuangshuo** [comment]
This answer should meet with my questio. https://github.com/jpmml/jpmml-sparkml-xgboost/issues/1.
I've tested that it gives wrong predictions when my data contains category features, and gives correct predictions when it doesn't.
