### ISSUE TITLE
Upgrade of Travis CI Builds and Testcases

### ISSUE THREAD

**Issue by tqchen** [dmlc/xgboost#372]
I have updated the Travis CI Builds: https://travis-ci.org/dmlc/xgboost
Now the Build Matrix checks the code style and runs tests on both R and python sides. I spent a day to fix all the lint errors, resulting current state of repo.

I want to call for volunteers to contribute more testcases to [tests](https://github.com/dmlc/xgboost/tree/master/tests). This helps us to make sure xgboost is backward compatible in various ways in future improvements, and make it better overtime

**Comment by AbdealiJK** [comment]
It would also be nice to add C++ tests which directly test the C++ functions with unittests.
What's your opinion on that ?
