### ISSUE TITLE
how can I extract the feature weights of the gblinear booster

### ISSUE THREAD

**Issue by dwy904** [dmlc/xgboost#3722]
I am trying to extract the `weights` of my input features from a `gblinear` booster. But it seems like it's impossible to do it in python.

I am wondering if there's any way to extract them.

**Comment by hcho3** [comment]
@dwy904 Did you try using `get_dump()` or `dump_model()`?

**Comment by dwy904** [comment]
Here is what I got.

> model_ranke. get_dump()

```
['bias:\n9.55492e+08\nweight:\n0.288463\n0.151129\n0.00716773\n31.5678\n-1.86324\n0.160523\n2.6101\n-0.0675516\n-7.74334e-10\n0.240564\n0.518223\n-2.97623\n-1.05936\n1.29177\n-0.597921\n1755.24\n-3.80193\n-3.40322\n372.426\n0.0564985\n0.0504407\n0.772678\n1.65475\n1.73482\n0.0058949\n-0.0397106\n-22.6941\n-0.82854\n712.713\n-0.138361\n1.21099\n-0.597615\n-1.56131\n-2.138\n0.13256\n-0.0376063\n-2.89459\n-2.41698\n0.653052\n']```

**Comment by dwy904** [comment]
One more question, is the sequence of the `model_rank.get_dump()` command exactly the same as the sequence of the command, `model_rank.feature_names`? except for the `bias` term.

**Comment by hcho3** [comment]
I think so.

**Comment by dwy904** [comment]
Thank you so much!
