### ISSUE TITLE
[jvm-packages] Support feature names in jvm packages

### ISSUE THREAD

**Issue by zengxy** [dmlc/xgboost#3725]
I found that in python API, one can set feature names, and when `get_dump` is used, these `feature_names` are used to build a `FeatureMap` object in c by calling `XGBoosterDumpModelExWithFeatures` to avoid getting default feature names `f0, f1, f2...`

While in jvm packages, there isn't the stub `XGBoosterDumpModelExWithFeatures`. And one can only
get a dumpped model with meaningful feature names by calling `getModelDump(featureMap)`, which actually call `XGBoosterDumpModelEx` and use `Map(featureIndex, featureName)` extracted from file `featureMap`.  I think it's not very practical and setting `featureNames` in java will help more.

Anyone of you think it's necessary and I can help to add it.

**Comment by CodingCat** [comment]
feel free to file a PR , thx

**Comment by zengxy** [comment]
ok. I'll haive a try.
