### ISSUE TITLE
Using OMP with Rcpp in Rstudio in windows

### ISSUE THREAD

**Issue by amaa11** [dmlc/xgboost#3726]
Dear all,
I wonder if it is possible to use OMP with Rcpp in windows using Rstudio. I wrote a simple code, but when I compile it, it gives me a warring message telling me that all pragmas lines are ignored.
Any idea about how to fix it??
Regards

**Comment by amaa11** [comment]
@choushishi
@ahmedahmedov

**Comment by hcho3** [comment]
Try installing Rtools.

**Comment by khotilov** [comment]
How is this issue related to xgboost? 
But make sure you have OpenMP flags enabled in Makevars.win, like in https://github.com/dmlc/xgboost/blob/master/R-package/src/Makevars.win
