### ISSUE TITLE
Memory error loading model

### ISSUE THREAD

**Issue by cnll0075** [dmlc/xgboost#3729]
Hello, 

I am trying to load a 15 MB xgboost model on a AWS EC2 m5d-12xlarge with 192 GB memory and 250 GB hard drive. However, I am getting "terminate called after throwing an instance of 'std::bad_alloc' what():  std::bad_alloc". This makes no sense to me; clearly I'm not running out of memory. I tried varying nthreads but it did not help.

 Loading this model on my local machine is almost instant.

Thanks for any help.

**Comment by hcho3** [comment]
Since you are using EC2, can you generate an AMI so that we can try to re-produce the bug?

**Comment by cnll0075** [comment]
Thanks for the prompt response! This is a company AMI (private) so I'm not sure if you will be able to find it. But it is built upon the Deep Learning ami provided by AWS on a Ubuntu instance.

**Comment by hcho3** [comment]
@cnll0075 What you can do is to create a fresh new instance from Deep Learning AMI, install XGBoost, and try to reproduce the problem. Then you should create a new AMI and make it public. (We'll have to find another way if you are not allowed to share your model.)

**Comment by cnll0075** [comment]
By the way, I was able to run xgboost on this instance for a 60GB dataset and trained the model for over 3500 runs. I saved the model afterwards. It is during loading that's giving me problems.

**Comment by hcho3** [comment]
@cnll0075 That's really weird. Would be nice if we can fix this.

**Comment by cnll0075** [comment]
Hi, I sudo apt-get upgrade the instance, and now the model is loading fine. I guess I will never know what was causing the problem before, but thanks for your help!

**Comment by hcho3** [comment]
No problem.
