### ISSUE TITLE
API Refactor to Support Error Handling

### ISSUE THREAD

**Issue by tqchen** [dmlc/xgboost#373]
I just pushed two commits that refactors the C API of xgboost in  cc767add881b5cc91376f67d01a5e164c5a0fadb  and a735f8cb766e7c7e487cc26878f403844a413deb 

This is a huge change to the API, for a good direction. Now xgboost should be able to handle error gracefully in most interface including python. Which resolves the issue #356 

Current statge:
- Python and R upgrade done, @jseabold sorry you might need another rebase :)
   - But we now  do not crash the python console during error
- [x] Java interface migration @yanqingmen please look into that and make a PR on this
    - Current java interface breaks because I did not updated the JNI wrapper, but I feel we should introduce it as soon as possible.
- [ ] Julia update, @antinucleon 
    - Since julia interface checkout a specific tag, it will still run correctly, but consider switch to the new interface when you consider update

**Comment by yanqingmen** [comment]
ok，@tqchen , i‘ll do modification and make a PR
