### ISSUE TITLE
[jvm-packages] how to get jar-with-dependencies in version 0.81

### ISSUE THREAD

**Issue by dwscu** [dmlc/xgboost#3735]
I use maven to package the xgboost4j-spark,but it doesn't build xgboost4j-0.81-jar-with-dependencies.jar.Anyone else has the same question?

**Comment by hcho3** [comment]
Did you run `mvn package`? For now, you should get pre-built 0.81 JAR by specifying repository
```xml
<repository>
  <id>XGBoost4J-Spark Snapshot Repo</id>
  <name>XGBoost4J-Spark Snapshot Repo</name>
  <url>https://raw.githubusercontent.com/CodingCat/xgboost/maven-repo/</url>
</repository>
```
and dependency
```
<dependency>
    <groupId>ml.dmlc</groupId>
    <artifactId>xgboost4j</artifactId>
    <version>0.81-SNAPSHOT</version>
</dependency>
<dependency>
    <groupId>ml.dmlc</groupId>
    <artifactId>xgboost4j-spark</artifactId>
    <version>0.81-SNAPSHOT</version>
</dependency>
```

**Comment by dwscu** [comment]
> Did you run `mvn package`? For now, you should get pre-built 0.81 JAR by specifying repository
> 
> ```
> <repository>
>   <id>XGBoost4J-Spark Snapshot Repo</id>
>   <name>XGBoost4J-Spark Snapshot Repo</name>
>   <url>https://raw.githubusercontent.com/CodingCat/xgboost/maven-repo/</url>
> </repository>
> ```
> 
> and dependency
> 
> ```
> <dependency>
>     <groupId>ml.dmlc</groupId>
>     <artifactId>xgboost4j</artifactId>
>     <version>0.81-SNAPSHOT</version>
> </dependency>
> <dependency>
>     <groupId>ml.dmlc</groupId>
>     <artifactId>xgboost4j-spark</artifactId>
>     <version>0.81-SNAPSHOT</version>
> </dependency>
> ```

ok,thanks,I'll try this.
