### ISSUE TITLE
Add Bootstrap Subsampling

### ISSUE THREAD

**Issue by BlindApe** [dmlc/xgboost#374]
Summary of Goal:
Current xgboost uses subsample without replacement. Would be great to support subsample with replacement(bootstrap)

This can be done by making use of weight in the data,  mentioned in the later post

**Comment by tqchen** [comment]
I do not understand your question exactly. When num_parallel_tree is used, you cans set subsample= p, which is randomly take in a instance with probability p

**Comment by BlindApe** [comment]
Yes, but in original RF the sampling is done with replacement, so one instance can be selected more than once. 
This give RF a different approach than boosting: bootstrapping reconstruct better low frequency regions in data. 
I suppose this subsampling with replacement probably need several changes in xgboost data structure, but other way of simmulating this is using current weights:
For each tree when parallel_tree is selected, sampling with replacement the row index, count the frequency of each row, assign this counts as weights.
I've found xgboost parallel trees very powerful and think with bootstrapping this could be a 'killer' algorithm.

**Comment by tqchen** [comment]
I think your idea of using weights is the correct way of doing so. This will require some modification to the code but seems to be a valid improvement. Let us keep this issue open and add it to feature todo list

**Comment by BlindApe** [comment]
Thank you Tianqi.
Thinking a bit more, if real weights are present in data the weight for each iteration should be the product of real weight and sampling frequency weights obviously.
With bootstrapping is usual subsample = 1 (giving the magic number of 63,2 % of rows represented in sample with differents weights), but probably subsample < 1 or even > 1 (for upsampling) could be interesting.
