### ISSUE TITLE
Unable to import XGBoost submodules if file name is "xgboost.py"

### ISSUE THREAD

**Issue by Nikronic** [dmlc/xgboost#3740]
Hello

I know this not a serious problem, but if you want to do import like this
 `from xgboost import XGBClassifier`
, and if your python file name is `xgboost.py`, you will get error as this:
 `ImportError: cannot import name 'XGBClassifier'`

my environment:
```Windows 10 version 1803
Python 3.6.6
IPython 6.4.0
Anaconda python kernel

**Comment by hcho3** [comment]
This is due to limitation of how Python locates modules. You should rename your Python script or move it to another directory.
