### ISSUE TITLE
Test time, let some features disabled. 预测的时候，让某些特征失效。（对我很重要，THANK YOU VERY MUCH）

### ISSUE THREAD

**Issue by guotong1988** [dmlc/xgboost#3745]
比如我有100个特征，有个word2vec特征，预测的时候，我发现了word2vec词典外的词进来了(out-of-vocabulary)，假设训练的时候，没有out-of-vocabulary。
这时我把这个word2vec的特征值设为0，可以使这个特征相当于失效了吗，仅仅其他99个特征起作用。
如果不是设0，有办法实现吗？

If I use wordvec as one feature, When out-of-vocab happens at test time, I set the wordvec feature value to 0 to disable the feature for the model. Is it possible?

**Comment by hcho3** [comment]
See my reply at https://discuss.xgboost.ai/t/test-time-let-some-features-disabled-thank-you-very-much/301.
