### ISSUE TITLE
get_fscore does not return the 0 importance features, is it ok?

### ISSUE THREAD

**Issue by guotong1988** [dmlc/xgboost#3753]
python xgboost 0.80

The list returned by `get_fscore` does not contains the 0 importance features.

**Comment by hcho3** [comment]
Can you post an example?

**Comment by guotong1988** [comment]
I can not post it here, as it is a lot of code of many files.
I print all the features of the input and print the features return by `get_fscore. Then I find the feature numbers do not equal.

**Comment by hcho3** [comment]
Yes, currently XGBoost will not include features that have not been used anywhere, i.e. zero importance features:
https://github.com/dmlc/xgboost/blob/2405c59352b05379d9e01ca10bea1d68b2f840e6/python-package/xgboost/core.py#L1415-L1437

I'll update the documentation to clarify this behavior.
