### ISSUE TITLE
Ability to define probability per feature when using feature sub-sampling.

### ISSUE THREAD

**Issue by thvasilo** [dmlc/xgboost#3754]
In the discussion forum the ability to define the probability of each feature being selected when col_sample is being used has been requested a few times recently [1].

I'm opening this issue to discuss whether the contributors consider this feature important enough to be included in the main distribution, and to work on the design and implementation if we agree on starting development.

[1] https://discuss.xgboost.ai/t/sampsize-by-strata-in-subsample/281

**Comment by oren0e** [comment]
Hi,
Is there any progress or ETA regarding this feature addition?
