### ISSUE TITLE
batch update possibility for the gblinear booster

### ISSUE THREAD

**Issue by dwy904** [dmlc/xgboost#3760]
I have a question regarding parameters update within the xgb linear booster. In this case, I will be only using the `gblinear`.

I have split my original dataset into multiple chunks due to the size issue. I am wondering if I can load one chunk of data at a time and update my `gblinear` model incrementally using the parameter `xgb_model` during the training process.

By doing this, will the performance of the model be so much different from training the `gblinear` modeling by loading the entire original dataset?

Here is a simple example

```python
import pandas as pd
import pickle
import xgboost as xgb
import numpy as np
import os

path_directory = '/home/project'
file_names = os.listdir(path_directory)

# batch update process
for iter, file_name in enumerate(file_names):
    data = pd.read_csv(file_name)
    dtrain = xgb.DMatrix(data.drop(['response'], axis = 1), data['response'].values)
    param = {'booster': 'gblinear'}
    if iter == 0:
        model_xgb = xgb.train(param,  dtrain,  2500, 
                              early_stopping_rounds = 500, verbose_eval = 100)
    else:
        model_xgb = xgb.train(param, dtrain, 2500, early_stopping_rounds = 500, 
                              verbose_eval = 100, xgb_model = model_xgb_previous)
    model_xgb_previous = model_xgb.copy()

# dump the final model
pickle.dump(model_xgb, open(path_directory + "/model_xgb" , "wb"))
```

**Comment by RAMitchell** [comment]
Try loading the dmatrix using external memory. I believe it does exactly what you want.

**Comment by dwy904** [comment]
There will be some feature work that I have to do inside my notebook before converting it to `DMatrix `.

**Comment by dwy904** [comment]
> Try loading the dmatrix using external memory. I believe it does exactly what you want.

That would be on possible solution if no feature modification is needed from the original dataset, but there will be some feature work that I have to do inside my notebook before converting it to `DMatrix `. 

And I am wondering if the performance of the model be so much different from training the gblinear modeling by loading the entire original dataset.

**Comment by hcho3** [comment]
>  I am wondering if the performance of the model be so much different from training the gblinear modeling by loading the entire original dataset.

Yes, since `xgb_model` is not designed for this use case. It is to be used with identical training data between successive calls to `train()`.

I think what you can do is to process your batches first and save them as multiple libsvm files. (Use `sklearn.datasets.dump_svmlight_file.) Then use external memory with entire directory:
```python
dtrain = DMatrix('/path/to/directory#cacheprefix')
```

**Comment by dwy904** [comment]
Can I use external memory training for `rank:ndcg` task. How can I setup the parameter `group_id` in this case.

**Comment by hcho3** [comment]
See https://xgboost.readthedocs.io/en/latest/tutorials/input_format.html#query-id-columns.

**Comment by dwy904** [comment]
Thank you. Do the query ids has to be unique when comparing to different batch files?

For example, I have to batch files and each of them contains 5 different queries. When I setup the query id for the batche files. Can I use query id 1 throught 5 twice `query id 1 - 5 for batch_1 and query id 1 - 5 for batch_2` or I have to setup a unique query id for each query `query id 1 - 5 for batch_1 and query id 6 - 10 for batch_2`.

**Comment by hcho3** [comment]
Query IDs have to be unique globally. So you'd use query id 1 - 5 for batch_1 and query id 6 - 10 for batch_2
