### ISSUE TITLE
[jvm-package] jvm-packages/xgboost4j/src/native/./xgboost4j.h:2:17: fatal error: jni.h: No such file or directory

### ISSUE THREAD

**Issue by saksim** [dmlc/xgboost#3778]
Environment:
Linux CENTOS 6.5
gcc++ 4.8.2
maven 3.5.4
java 1.8.0_181
spark cluster: 1.6.1
scala 2.10

Hello,all!
Actually I am a newcomer in xgboost in Spark. I got lots of dramatical mistakes during past two weaks (https://github.com/dmlc/xgboost/issues/3770). Finally, I believe the root reason why I get wrong is the missing of "libxgboost4j.so" file.

Thus, I cross through the directory to ../xgboost/jvm-packages and mannually run "./create_jni.sh". The interesting mistake occurs as follows【The reason why I call it interesting is due to the fact that I certainly set the JAVA_HOME not only in '~/.bashrc_profile', but also in '~/.bashrc'. In addition, the file "/etc/bashrc" and "/etc/profile" also have been set. Just like the issue https://github.com/dmlc/xgboost/issues/1011 did】:

[root@weiweiLinux jvm-packages]# ./create_jni.sh 
build java wrapper
g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -I/include -I./java -I/include/linux -shared -o jvm-packages/lib/libxgboost4j.so jvm-packages/xgboost4j/src/native/xgboost4j.cpp build/learner.o build/logging.o build/c_api/c_api.o build/c_api/c_api_error.o build/common/common.o build/data/data.o build/data/simple_csr_source.o build/data/simple_dmatrix.o build/data/sparse_page_dmatrix.o build/data/sparse_page_raw_format.o build/data/sparse_page_source.o build/data/sparse_page_writer.o build/gbm/gblinear.o build/gbm/gbm.o build/gbm/gbtree.o build/metric/elementwise_metric.o build/metric/metric.o build/metric/multiclass_metric.o build/metric/rank_metric.o build/objective/multiclass_obj.o build/objective/objective.o build/objective/rank_obj.o build/objective/regression_obj.o build/tree/tree_model.o build/tree/tree_updater.o build/tree/updater_colmaker.o build/tree/updater_histmaker.o build/tree/updater_prune.o build/tree/updater_refresh.o build/tree/updater_skmaker.o build/tree/updater_sync.o dmlc-core/libdmlc.a rabit/lib/librabit.a -pthread -lm  -fopenmp -lrt  -lrt
In file included from jvm-packages/xgboost4j/src/native/xgboost4j.cpp:18:0:
jvm-packages/xgboost4j/src/native/./xgboost4j.h:2:17: fatal error: jni.h: No such file or directory
 #include <jni.h>
                 ^
compilation terminated.
make: *** [jvm-packages/lib/libxgboost4j.so] Error 1
move native lib
mv: cannot stat `lib/libxgboost4j.so': No such file or directory
complete

Does anyone know the reason?
Best Wishes

**Comment by hcho3** [comment]
Does `${JAVA_HOME}/include` directory exist?

**Comment by saksim** [comment]
> Does `${JAVA_HOME}/include` directory exist?

YES,It does! The result as follows :

[root@weiweiLinux ~]# ls ${JAVA_HOME}
bin  COPYRIGHT  include  javafx-src.zip  jre  lib  LICENSE  man  README.html  release  src.zip  THIRDPARTYLICENSEREADME-JAVAFX.txt  THIRDPARTYLICENSEREADME.txt
[root@weiweiLinux ~]# ls ${JAVA_HOME}/include
classfile_constants.h  jawt.h  jdwpTransport.h  jni.h  jvmticmlr.h  jvmti.h  linux

**Comment by hcho3** [comment]
> g++ -std=c++0x -Wall -O3 -msse2 -Wno-unknown-pragmas -funroll-loops -Iinclude -Idmlc-core/include -Irabit/include -fPIC -fopenmp -I/include -I./java [...]

See the second to last word `-I/include`, which corresponds to line
https://github.com/dmlc/xgboost/blob/4a8d63b6c8711fb839c71e26c659936252df1eb5/Makefile#L46

So for some reason `${JAVA_HOME}` is empty. Maybe run
```bash
JAVA_HOME=/path/to/java ./create_jni.sh
```
or 
```bash
JAVA_HOME=/path/to/java make jvm
```
?

**Comment by saksim** [comment]
> > g++ -std=c++0x -Wall -O3 -msse2 -Wno-unknown-pragmas -funroll-loops -Iinclude -Idmlc-core/include -Irabit/include -fPIC -fopenmp -I/include -I./java [...]
> 
> See the second to last word `-I/include`, which corresponds to line
> [xgboost/Makefile](https://github.com/dmlc/xgboost/blob/4a8d63b6c8711fb839c71e26c659936252df1eb5/Makefile#L46)
> 
> Line 46 in [4a8d63b](/dmlc/xgboost/commit/4a8d63b6c8711fb839c71e26c659936252df1eb5)
> 
>  export JAVAINCFLAGS = -I${JAVA_HOME}/include -I./java 
> So for some reason `${JAVA_HOME}` is empty. Maybe run
> 
> ```shell
> JAVA_HOME=/path/to/java ./create_jni.sh
> ```
> 
> or
> 
> ```shell
> JAVA_HOME=/path/to/java make jvm
> ```
> 
> ?

YES! It actually makes sense!!

[root@weiweiLinux jvm-packages]# JAVA_HOME=/usr/weiweiLinux/jdk1.8.0_181 ./create_jni.sh
build java wrapper
g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -I/usr/qudian/jdk1.8.0_181/include -I./java -I/usr/qudian/jdk1.8.0_181/include/linux -shared -o jvm-packages/lib/libxgboost4j.so jvm-packages/xgboost4j/src/native/xgboost4j.cpp build/learner.o build/logging.o build/c_api/c_api.o build/c_api/c_api_error.o build/common/common.o build/data/data.o build/data/simple_csr_source.o build/data/simple_dmatrix.o build/data/sparse_page_dmatrix.o build/data/sparse_page_raw_format.o build/data/sparse_page_source.o build/data/sparse_page_writer.o build/gbm/gblinear.o build/gbm/gbm.o build/gbm/gbtree.o build/metric/elementwise_metric.o build/metric/metric.o build/metric/multiclass_metric.o build/metric/rank_metric.o build/objective/multiclass_obj.o build/objective/objective.o build/objective/rank_obj.o build/objective/regression_obj.o build/tree/tree_model.o build/tree/tree_updater.o build/tree/updater_colmaker.o build/tree/updater_histmaker.o build/tree/updater_prune.o build/tree/updater_refresh.o build/tree/updater_skmaker.o build/tree/updater_sync.o dmlc-core/libdmlc.a rabit/lib/librabit.a -pthread -lm  -fopenmp -lrt  -lrt
move native lib
complete

**Comment by saksim** [comment]
[root@weiweiLinux jvm-packages]# find / -name "libxgboost4j.so"
/usr/weiweiLinux/project/xgboostv2/jvm-packages/xgboost4j/src/main/resources/lib/libxgboost4j.so

**Comment by saksim** [comment]
> > g++ -std=c++0x -Wall -O3 -msse2 -Wno-unknown-pragmas -funroll-loops -Iinclude -Idmlc-core/include -Irabit/include -fPIC -fopenmp -I/include -I./java [...]
> 
> See the second to last word `-I/include`, which corresponds to line
> [xgboost/Makefile](https://github.com/dmlc/xgboost/blob/4a8d63b6c8711fb839c71e26c659936252df1eb5/Makefile#L46)
> 
> Line 46 in [4a8d63b](/dmlc/xgboost/commit/4a8d63b6c8711fb839c71e26c659936252df1eb5)
> 
>  export JAVAINCFLAGS = -I${JAVA_HOME}/include -I./java 
> So for some reason `${JAVA_HOME}` is empty. Maybe run
> 
> ```shell
> JAVA_HOME=/path/to/java ./create_jni.sh
> ```
> 
> or
> 
> ```shell
> JAVA_HOME=/path/to/java make jvm
> ```
> 
> ?

Thanks for your help!!!
