### ISSUE TITLE
Check failed: ntree_limit == 0U (331 vs. 0) GBLinear::Predict ntrees is only valid for gbtree predictor

### ISSUE THREAD

**Issue by mtaboga** [dmlc/xgboost#3789]
I think this might be a bug.
I am running xgboost 0.80 under python 3.6 and windows7 (anaconda distribution)
My code is:

    clf = xgb.XGBRegressor(
            booster=boost,
            nthread=4,
            objective='reg:linear',
            n_estimators=nEst,
            learning_rate=lr,
            max_depth=depth,
            reg_alpha=alpha, #default=0 l1 regularization on weights
            reg_lambda=lamb, #default=1 L2 regularization on weights
            subsample=sub, #default=1
            colsample_bylevel=colsample, #default=1
            seed=42
            )

    clf.fit(
            xt, yt,
            eval_set=[(xv, yv)],
            eval_metric="rmse",          
            early_stopping_rounds=20 
            )  

     yTest=clf.predict(xTest)

When `boost='gbtree'` everything works fine but when `boost='gblinear'` I get the following error:
` File "D:/Dropbox/kanalytics/aws9.py", line 217, in <module>
    yTest=clf.predict(xTest)

  File "C:\Users\Manu\AppData\Local\conda\conda\envs\py36\lib\site-packages\xgboost-0.80-py3.6.egg\xgboost\sklearn.py", line 397, in predict
    validate_features=validate_features)

  File "C:\Users\Manu\AppData\Local\conda\conda\envs\py36\lib\site-packages\xgboost-0.80-py3.6.egg\xgboost\core.py", line 1216, in predict
    ctypes.byref(preds)))

  File "C:\Users\Manu\AppData\Local\conda\conda\envs\py36\lib\site-packages\xgboost-0.80-py3.6.egg\xgboost\core.py", line 165, in _check_call
    raise XGBoostError(_LIB.XGBGetLastError())

XGBoostError: b'[11:01:05] C:\\dev\\libs\\xgboost\\src\\gbm\\gblinear.cc:101: Check failed: ntree_limit == 0U (331 vs. 0) GBLinear::Predict ntrees is only valid for gbtree predictor'`

**Comment by hcho3** [comment]
@mtaboga Indeed, this is a bug. Thanks for reporting it. I think #3445 introduced it. I'll prepare a fix soon.

**Comment by hcho3** [comment]
@RAMitchell We may want to disable early stopping for `gblinear`, since the saved model only remembers the coefficients in the last iteration. It isn't possible to fetch the coefficients for the arbitrary n-th round. What do you think?

**Comment by RAMitchell** [comment]
As a mechanism for stopping training to prevent overfitting you are right that it doesn't work. 

I still use early stopping though to tell when my model has converged completely, otherwise you are just spending boosting iterations doing nothing.

**Comment by hcho3** [comment]
@RAMitchell Should we warn the user that the saved model gives you the final iteration, not the best iteration? For instance, if early stopping stops training at 200th iteration and returns 190th as the best, the `weight` variable gives you the coefficients for the 200th, not 190th. Alternatively, we can save a separate `weight` vector for each iteration, at the cost of extra space and computation.

**Comment by kelvin-l** [comment]
@hcho3 is this bug `GBLinear::Predict ntrees is only valid for gbtree predictor` still existing? I was running xgboost with linear booster recently and got this error.

**Comment by hcho3** [comment]
@kelvin-l Yes, it still exists.

**Comment by nahidalam** [comment]
Is this issue fixed yet? Looks like setting `ntree_limit = 0` during the prediction will fix it? But is there a way to do it in Sagemaker batch-transform job?

**Comment by BaoshengHeTR** [comment]
By the way, what is the difference by using `gblinear` and logisticregression. I have the same result for the two methods.
