### ISSUE TITLE
Compile failed under xgboost file

### ISSUE THREAD

**Issue by haitongwan** [dmlc/xgboost#3796]
The error message:
src/io/hdfs_filesys.h:10:18: fatal error: hdfs.h: No such file or directory
 #include <hdfs.h>
                  ^
compilation terminated.

I can't find the "hdfs.h" file in the source code.How can I solve this problem?
I am looking forward to your reply.

**Comment by hcho3** [comment]
Did you set `USE_HDFS` compilation option?

**Comment by hcho3** [comment]
Make sure you installed HDFS library on your system. Alternatively, please set `USE_HDFS` to 0 in `make/config.mk`.

**Comment by haitongwan** [comment]
> Make sure you installed HDFS library on your system. Alternatively, please set `USE_HDFS` to 0 in `make/config.mk`.

Thank you very much for your timely reply. I want to deploy distributed xgboost on hadoop-2.2.0. Do you have deployment documents?

**Comment by hcho3** [comment]
This link may be useful: https://xgboost.readthedocs.io/en/latest/jvm/xgboost4j_spark_tutorial.html#building-a-ml-pipeline-with-xgboost4j-spark

**Comment by haitongwan** [comment]
> Make sure you installed HDFS library on your system. Alternatively, please set `USE_HDFS` to 0 in `make/config.mk`.

I set it according to what you said, but it can't work yet.

The error message:
Error: Could not find or load main class org.apache.hadoop.yarn.dmlc.Client
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/q/python27/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/q/python27/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/q/xgboost-packages/xgboost/dmlc-core/tracker/dmlc_tracker/yarn.py", line 113, in run
    subprocess.check_call(cmd, shell=True, env=env)
  File "/home/q/python27/lib/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)

**Comment by haitongwan** [comment]
> This link may be useful: https://xgboost.readthedocs.io/en/latest/jvm/xgboost4j_spark_tutorial.html#building-a-ml-pipeline-with-xgboost4j-spark

I only have the Hadoop environment now, and I want to realize the deployment of distributed xgboost in this environment.

**Comment by hcho3** [comment]
I think your Hadoop installation is somehow incomplete. Consider using pre-built JARs from Maven Central: https://xgboost.readthedocs.io/en/latest/jvm/xgboost4j_spark_tutorial.html#building-a-ml-pipeline-with-xgboost4j-spark
