### ISSUE TITLE
XGBoostError: sklearn needs to be installed in order to use this module

### ISSUE THREAD

**Issue by warmcuddles** [dmlc/xgboost#3798]
119                  base_score=0.5, seed=0, missing=None):
    120         if not SKLEARN_INSTALLED:
--> 121             raise XGBoostError('sklearn needs to be installed in order to use this module')
    122         self.max_depth = max_depth
    123         self.learning_rate = learning_rate

XGBoostError: sklearn needs to be installed in order to use this module

windows 8.1 32 bit

**Comment by hcho3** [comment]
As the error says, please install scikit-learn package if you'd like to use `XGBClassifier` and `XGBRegressor`.

**Comment by warmcuddles** [comment]
@hcho3 actually I recently upgraded my sklearn to 20.0 from 18.1
and that is causing the error 
I had to downgrade my scikit-learn to make it work again
and in sklearn version 18.1 it works but notebook gives warning "(This module will be removed in 0.20. "This module will be removed in 0.20.", DeprecationWarning)"

So my question now is how to make it run in sklearn ver 20.0 without getting above error
Thanks :+1:

**Comment by hcho3** [comment]
Can you post the script you were running before you got the error?

**Comment by hcho3** [comment]
For the record, I also use scikit-learn 0.20 myself and never encountered this problem.

**Comment by warmcuddles** [comment]
I'll have to again download sklearn 0.20 to actually show the error but here's the warning from sklearn 0.18 
DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20. "This module will be removed in 0.20.", DeprecationWarning)

xgboost‑0.80‑cp36‑cp36m‑win32.whl

I used above mentioned file to download xgboost, however I even tried to uninstall it and install xgboost‑0.80‑cp37‑cp37m‑win32.whl this version of xgboost but problem was same

120 if not SKLEARN_INSTALLED:
--> 121 raise XGBoostError('sklearn needs to be installed in order to use this module') (Note : In sklearn 0.20)

**Comment by hcho3** [comment]
Any updates?

**Comment by hcho3** [comment]
@warmcuddles Any updates? Can you install with `pip install xgboost==0.81`?
