### ISSUE TITLE
Visualization Analysis module for python 

### ISSUE THREAD

**Issue by tqchen** [dmlc/xgboost#380]
The xgboost R package contain a nice visualization module by @pommedeterresautee that allows user to explore the feature importance and the underlying patterns learned. It would be great if it is also supported in python. Possibly using matplotlib

**Comment by ajkl** [comment]
I will give this a shot if now one has picked it up yet ?

**Comment by tqchen** [comment]
That would be great.

**Comment by delijati** [comment]
I played a little bit around with it here is a snippet of what i have done so far.


```python

import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline


def plot_model(model, names):
    score = model.get_fscore()
    #plain
    #print score
    # percentage
    score = {k: (v / float(sum(score.values()))) * 100. for k, v in score.items()}
    print score, '\n'
    # threshold presentage 2%
    score = {k: v for k, v in score.items() if v >= 2.0}
    print score, '\n'
    # sorted
    score = sorted(score.items(), key=lambda v: v[1], reverse=True)    
    
    fmap = {'f%s' % i : names[i] for i in range(len(names))}
    score = [(fmap[x[0]], x[1]) for x in score]
    print score

    widthscale = len(score)/4 
    figsize = (8*widthscale,6) # fig size in inches (width,height)
    fig = plt.figure(figsize=figsize) # set the figsize

    ind = np.arange(len(score))
    plt.bar(ind, [x[1] for x in score])
    plt.xticks(ind, [x[0] for x in score])
    fig.autofmt_xdate()
    plt.show()

plot_model(model, cat_train.keys())
```

**Comment by tqchen** [comment]
The python package has been moved to https://github.com/dmlc/xgboost/tree/master/python-package/xgboost, we can add a plot.py here.

**Comment by sinhrks** [comment]
I've prepared an example of importance and tree plotting, and willing to make a PR if these looks useful.

https://gist.github.com/sinhrks/cc9a88f74074fc296e12

**Comment by tqchen** [comment]
@sinhrks sorry for the delayed reply. This looks very nice. Can you create a PR on this? @pommedeterresautee If you have time, please do an round of review in terms of interface, would be great if python and R interface have some level of consistency.

Thanks!
