### ISSUE TITLE
is embedding features suitable for gbdt model?

### ISSUE THREAD

**Issue by yangl326-Dylan** [dmlc/xgboost#3800]
A word embedding, for example, 200 dim, is this a good features for gbdt model?

**Comment by thvasilo** [comment]
You can definitely use that, but whether it will be better than using a sparse representation of your text features will depend on the problem.

Also for this kinds of open ended questions I'd suggest using the [project's forum](https://discuss.xgboost.ai/), the issue tracker should really be used to report code bugs or other technical issues related to the codebase.
