### ISSUE TITLE
Binary Pre-build Release

### ISSUE THREAD

**Issue by tqchen** [dmlc/xgboost#381]
Mentioned that there are some extent of difficulty for windows and mac users to build the project. @hetong007 proposed to pack binary prebuild in our major release.  We can consider the options
- Pack pre-build for major release by attaching files to the release
- Continuously build release using some CI

The latter will requires some machine or service to host the build and might be harder to do. This issue is opened to track the discussion on this thread

**Comment by hetong007** [comment]
One of the most convenient and reliable way to build (and even check) the binary is to use the function `devtools::build_win`. The function compiles the package and sends it to http://win-builder.r-project.org/ for a "non-official" check. After half-an-hour I (as the maintainer in DESCRIPTION) will recieve an email containing a link to the compiled binary zip file and the check.log.

Actually the checking environment is very close to the official check, this is also a good way to do a pre-check for any pacakge that is about to be submitted to CRAN. 

For MAC users, I don't know any similar service yet.

**Comment by pommedeterresautee** [comment]
Why not going back in Cran? 

From my understanding the package has been removed because of crashes on Windows but now there is no such thing, isn't it?

I am sure I miss something but I don't know what.

Kind regards,
Michaël

**Comment by hetong007** [comment]
Well, we had the crashes and we were warned to fix it by a deadline. We missed it and got [Ripleyed](https://twitter.com/hadleywickham/status/276022791839571968) and "No further submissions will be considered". 

It isn't impossible to get it back on cran, but I think one can only do so if he/she knows another R core member well, and of course we have no crash/error/warning in `xgboost`.

**Comment by tqchen** [comment]
The Mac R package do not come with openMP by default, so maybe it is not a
bad idea for doing it for MAC

**Comment by tqchen** [comment]
For windows, let us consider https://github.com/krlmlr/r-appveyor appvegor, which is a CI for windows and support generating artifacts, which can be downloaded by user to get the latest version binary. @hetong007  can you look into this?

**Comment by hetong007** [comment]
Here are the two results by `devtools::build_win` of 141f9ebf4b2f1c2ebbbf10ed2008f53af906b2e1:

- By R 3.2.1: http://win-builder.r-project.org/EBwi0VcnnLxd
- By R devel: http://win-builder.r-project.org/oy9Np7SrcRa6

We can have a sense of what kind of result we will get from `00check.log`, and the windows binary pack as well. Currently the result seems fine, only some NOTEs about the R code. I will fix them soon.

**Comment by hetong007** [comment]
On the commit a1c7104d7f7a797794ed6ecc73f76c9582dd562b:

- By R 3.2.1: http://win-builder.r-project.org/z7pVJJhXGqDM
- By R devel: http://win-builder.r-project.org/XDG1gg0g0XuT

There's no notes, except for the *Possibly mis-spelled words in DESCRIPTION*, which I think is OK. 

@tqchen Do you mind to test this commit on Solaris? Thank you. If it passes the check, I think we are good for CRAN.

**Comment by hetong007** [comment]
On the commit b1dec917c7fe17f9d95f26ce1b47735c225dafd5:

- By R 3.2.1: http://win-builder.r-project.org/Ps5MbQW0MQiW
- By R devel: http://win-builder.r-project.org/y5360kI6757j

Seems now solaris, windows and ubuntu are happy with xgboost. I will email Hadley soon for a re-CRAN chance.

**Comment by hetong007** [comment]
Update: I have re-submitted this commit https://github.com/dmlc/xgboost/commit/3a091fa30265e51f4e1b6e72960b78bbe7d5e597 to CRAN. I have modified DESC so there's no mis-spelled word in the check.

**Comment by hetong007** [comment]
We are ON CRAN again! https://cran.r-project.org/web/packages/xgboost/index.html

Actually it is very late in my timezone and I am actually commenting by my phone. Please update the NEWS and the README.MDs if you are awake (I am pretending sleeping).
