### ISSUE TITLE
Custom metric does not work as expected

### ISSUE THREAD

**Issue by sbushmanov** [dmlc/xgboost#3815]
I have `xgboost` version 0.8 built from sources with gcc and GPU support.

I have built custom metric defined as follows:

```
def rmsle(y, y0):
    assert len(y) == len(y0)
    return np.sqrt(np.mean(np.power(np.log1p(y+1)-np.log1p(y0+1), 2)))

def metricRMSLE(preds,dtrain):
    labels = dtrain.get_label()
    return 'RMSLE',rmsle(labels,preds)
```
When I run:

```
cv_result = xgb.cv(params, dtrain, feval=metricRMSLE, num_boost_round=num_rounds
                   , nfold=5, seed=random_state,callbacks=[xgb.callback.early_stop(50)])
```

I've got:

```
Multiple eval metrics have been passed: 'test-rmse' will be used for early stopping.

Will train until test-rmse hasn't improved in 50 rounds.
[0]	train-RMSLE:4.5545+0.0019959	train-rmse:8.50454e+06+24785.8	test-RMSLE:4.55498+0.00872151	test-rmse:8.5046e+06+100340
[50]	train-RMSLE:0.9502+0.000694694	train-rmse:5.69948e+06+13158	test-RMSLE:0.952315+0.00393536	test-rmse:5.73494e+06+82427.6
```

whereas I expected `test-RMSLE` to be used for early stopping.

Is this a bug or I'm doing something wrong defining custom  eval metric?

(before updating to 0.8, in `xgboost 0.6`, I had  `test-RMSLE` used for early stopping indeed)

**Comment by hcho3** [comment]
Can you set parameter disable_default_eval_metric=0 and try again?

**Comment by hcho3** [comment]
Note that `disable_default_eval_metric` is not part of 0.80 release. Make sure to compile from source using the latest master.

**Comment by sbushmanov** [comment]
@hcho3 

I have done:

```
git clone --recursive https://github.com/dmlc/xgboost
cd xgboost
git checkout master
```

and

`git clone --depth=1 --recursive https://github.com/dmlc/xgboost`

and then built as usual.

Both of which gave me:

`unexpected keyword argument 'disable_default_eval_metric'`

Could you please advise me where am I wrong?

Thanks in advance and sorry for the lame question!

**Comment by hcho3** [comment]
disable_default_eval_metric should go into the param dictionary:
```
params = {'disable_default_eval_metric': 1, ... }
bst = xgboost.train(params, ...)
```

**Comment by sbushmanov** [comment]
I tried with `xgb.cv()`, no warnings, but still default metric is used for early stopping:
`Multiple eval metrics have been passed: 'test-rmse' will be used for early stopping.
`

**Comment by hcho3** [comment]
Did you put `disable_default_eval_metric` in `params` variable? See https://xgboost.readthedocs.io/en/latest/parameter.html#general-parameters

**Comment by hcho3** [comment]
Also, make sure to remove `eval_metric` from `params`.

**Comment by sbushmanov** [comment]
@hcho3 

My code for `xgb.cv` is as follows:

```
def xgb_evaluate(min_child_weight,
                 colsample_bytree,
                 max_depth,
                 subsample,
                 gamma,
                 alpha):

    params['min_child_weight'] = int(min_child_weight)
    params['colsample_bytree'] = max(min(colsample_bytree, 1), 0)
    params['max_depth'] = int(max_depth)
    params['subsample'] = max(min(subsample, 1), 0)
    params['gamma'] = max(gamma, 0)
    params['alpha'] = max(alpha, 0)


    cv_result = xgb.cv(params, dtrain, num_boost_round=num_rounds, nfold=5, feval=metricRMSLE, verbose_eval=100, show_stdv=False,
             seed=random_state,
             callbacks=[xgb.callback.early_stop(50)])

    return -cv_result['test-rmsxle-mean'].values[-1]

num_rounds = 3000
random_state = 2016
num_iter = 25
init_points = 5
params = {
    'eta': 0.01,
    'silent': 1,
    'verbose_eval': True,
    'seed': random_state,
    'disable_default_eval_metric=1':1
}

xgbBO = BayesianOptimization(xgb_evaluate, {'min_child_weight': (1, 20),
                                            'colsample_bytree': (0.3, 1),
                                            'max_depth': (5, 15),
                                            'subsample': (0.3, 1),
                                            'gamma': (0, 10),
                                            'alpha': (0, 10),
                                            })

xgbBO.maximize(init_points=init_points, n_iter=num_iter)
```

The message is: 
`Multiple eval metrics have been passed: 'test-rmse' will be used for early stopping.
`
whereas I expected the evaluation metric to be the custom one: `test-RMSLE`

**Comment by hcho3** [comment]
```python
'disable_default_eval_metric=1':1
```

Please fix this to
```python
'disable_default_eval_metric':1
```

**Comment by sbushmanov** [comment]
@hcho3 
Thank you for catching the error, now it's working as expected!!!
