### ISSUE TITLE
xgb.importance feature index

### ISSUE THREAD

**Issue by ajkl** [dmlc/xgboost#383]
Is there a reason why the feature index starts from 0 for xgb.importance ? Its confusing as everything else (including the dimnames) is 1-base indexed. Is this a bug or a design choice ? I feel its a bug because when I compared the results of rel.inf from R/gbm I get features which are offsetted by 1 position of what i get with xgb.importance.

> print(importance)
            Feature        Gain      Cover  Frequence
1:              Age 0.634746089 0.64783711 0.65789474
2: TreatmentPlacebo 0.254338394 0.11228359 0.09210526
3:          SexMale 0.067907579 0.09042141 0.13157895
4:      AgeDiscret6 0.015399753 0.04195634 0.03947368
5:      AgeDiscret4 0.013106997 0.04791023 0.02631579
6:      AgeDiscret3 0.012446229 0.04741315 0.02631579
7:      AgeDiscret5 0.002054958 0.01217817 0.02631579

> xgb.importance(model = bst)
   Feature        Gain      Cover  Frequence
1:       3 0.634746089 0.64783711 0.65789474
2:       0 0.254338394 0.11228359 0.09210526
3:       2 0.067907579 0.09042141 0.13157895
4:       7 0.015399753 0.04195634 0.03947368
5:       5 0.013106997 0.04791023 0.02631579
6:       4 0.012446229 0.04741315 0.02631579
7:       6 0.002054958 0.01217817 0.02631579

>sparse_matrix@Dimnames[[2]]
[[2]]
 [1] "TreatmentPlacebo" "TreatmentTreated" "SexMale"          "Age"              "AgeDiscret3"      "AgeDiscret4"      "AgeDiscret5"      "AgeDiscret6"      "AgeDiscret7"     
[10] "AgeCatYoung"

**Comment by pommedeterresautee** [comment]
Hi @ajkl 

I understand your comment.
There is a reason why it starts with 0, the indices you see in importance are from model dump.
As you know, XGBoost is written in C++, and indices in C/C++ starts with 0.

So we need to choose between 1 (R) and 0 (original indice).

It seems to me much more important to keep the link with original indices from the model dump than complying with the R language standart.

If I answered your question, please close this issue.

Kind regards,
Michael

**Comment by ajkl** [comment]
Hi Michael,
Thanks for the reply. 
But if xgb.importance is just part of the R package (? correct me if I am wrong) then shouldnt we be following the R way of indexing ? It might become messier if you use the output indexes from xgb.importance to index the features. 

Consider this example from the R-package basic_walkthrough demo - 

```
> print(xgb.importance(feature_names = train$data@Dimnames[[2]], filename_dump = "dump.raw.txt"))
                   Feature       Gain     Cover Frequence
1:               odor=none 0.67615484 0.4978746       0.4
2:         stalk-root=club 0.17135352 0.1920543       0.2
3:       stalk-root=rooted 0.12317241 0.1638750       0.2
4: spore-print-color=green 0.02931922 0.1461960       0.2
```

```
> xgb.importance(model=bst)
   Feature       Gain     Cover Frequence
1:      28 0.67615484 0.4978746       0.4
2:      55 0.17135352 0.1920543       0.2
3:      59 0.12317241 0.1638750       0.2
4:     108 0.02931922 0.1461960       0.2
> xgb.importance(model=bst)$Feature
[1] "28"  "55"  "59"  "108"
```

Now if you use the Feature column to index the feature names, you get wrong feature names
```
> train$data@Dimnames[[2]][as.numeric(xgb.importance(model=bst)$Feature)]
[1] "odor=musty"                  "stalk-root=bulbous"          "stalk-root=rhizomorphs"      "spore-print-color=chocolate"
```

so you have to add 1 every time to get the right ones
```
> train$data@Dimnames[[2]][as.numeric(xgb.importance(model=bst)$Feature)+1]
[1] "odor=none"               "stalk-root=club"         "stalk-root=rooted"       "spore-print-color=green"
```

**Comment by tqchen** [comment]
There are two ways to tackle the problem.
- (1) When convert R's matrix to DMatrix, use 1 based offset so the matrix is converted to data where index starts from 1 internally.
    -  This will break backward compatibility of the model, but do not suffer from problem listed in next option.
- (2) Add the index returned by importance by 1
   - This will also make user confuse in certain cases(when data are loaded from libsvm file, where feature index are explicitly specified, as opposed to implicitly indicated by column index) 

So both solution have some subtle problem here. I would prefer not to change the behavior of the function for now. If we get most user and developer agree on going for option 1 and break backward compatibility, I would prefer that fix as opposed to option 2.

This being said, I think it is important to make people know the indexing issue when using importance function. Document it clearly in the functions and provide guidance on how user should make use these features(possibly give a warning when feature_names is not presented indicating the index starts from 0)

**Comment by ajkl** [comment]
Most of R-packages have C code but they still follow the 1-indexing style of R. 
It is ok to break backward compatibility if its for a good reason or if you are fixing a real issue. It can be announced in the next release notes.
I agree with @tqchen that option 1 is nicer compared to the hacky option 2.

**Comment by tqchen** [comment]
There are other issues like doing prediction using python/java/c from a model trained from R module. Which will also create confusion if the model is loaded from same csv. So there is a tradeoff between cross language compatibility and internal consistency with language. 

Let us definitely add a clear documentation on this first.

**Comment by ajkl** [comment]
I see what you are saying. I am not sure how many people do cross-language modelling/prediction tasks. But in that case that definitely would be an issue.
We should start with adding this in the man page for the package.

**Comment by pommedeterresautee** [comment]
As this only concern the importance function, may be put information only in the function documentation is OK? (Instead of the package "man page" general presentation )

**Comment by ajkl** [comment]
My bad. I meant function man page. You are right :-)
