### ISSUE TITLE
How GPU memory is allocated on multi-GPU system?

### ISSUE THREAD

**Issue by Bluesn0w** [dmlc/xgboost#3830]
from #2019, I saw someone says that the gpu_hist algorithm must statically allocate memory for histograms for every single column. However, I wonder how the memory is allocated across multiple GPUs? In addition, whether xgboost copies entire dataset from ram to GPU or just in batches like how Tensorflow works? I originally thought that the memory of all GPUs will be treated as a pool, then allocate evenly. However, it does not look like so. Below is my experiment on my dataset.  (1000+ features, 5.3 million rows, 38G on Google Bigquery and around 12G stored in pickle).

**Test 1:** 4 X K80 (4X12G GPU RAM in total)  - Google n1-highmem-32CPU-208G Ram:
Not able to run even when max bin =32. Ipython Notebook will just show kernel died, and below messages are showing if I just run the python code directly in bash shell:

terminate called after throwing an instance of 'thrust::system::system_error'
  what():  /workspace/src/predictor/../common/device_helpers.cuh(523): out of memory

**Test 2:** 1 X P100 (1X17.1G GPU Ram in total) - Google n1-highmem-16CPU-104G (reduced due  to GPU limit) Ram:

Ran with max_bin=64. GPU Memory allocation in NVTOP shows as below:

Device 0 [Tesla P100-PCIE-16GB] PCIe GEN 3@16x RX: 4.000 MB/s TX: 3.000 MB/s
 GPU 1328MHz MEM 715MHz  TEMP  55°C FAN N/A% POW 131 / 250 W
 GPU-Util[|||||||||||||||||||||||||||||||||||||||||||||||||99%] MEM-Util[||||||||||||||||||||||||||||||||||||||||16.5G/17.1G] Encoder[                    0%] Decoder[                    0%]

  PID USER GPU    TYPE            MEM Command
 1389 root   0 Compute  16520MB 96.8% python3.6

**Test 3:** 2 X P100 (2X17.1G GPU Ram in total) - Google n1-highmem-32CPU-208G (reduced due  to GPU limit) Ram:

Ran with max_bin=64. ( GPU Memory allocation in NVTOP shows as below:
 Device 0 [Tesla P100-PCIE-16GB] PCIe GEN 3@16x RX: 635.0 MB/s TX: 331.0 MB/s
 GPU 1328MHz MEM 715MHz  TEMP  43°C FAN N/A% POW  88 / 250 W
 GPU-Util[|||||||||||||||||||||||||||||||||||||||||||||||  90%] MEM-Util[||||||||||||||||||||||||||||||||||||||||14.9G/17.1G] Encoder[                    0%] Decoder[                    0%]

 Device 1 [Tesla P100-PCIE-16GB] PCIe GEN 3@16x RX: 413.0 MB/s TX: 413.0 MB/s
 GPU 1328MHz MEM 715MHz  TEMP  45°C FAN N/A% POW  86 / 250 W
 GPU-Util[||||||||||||||||||||||||||||||||||||||||||||     85%] MEM-Util[||||||                                   2.0G/17.1G] Encoder[                    0%] Decoder[                    0%]

  PID USER GPU    TYPE            MEM Command
 1673 root   0 Compute  14911MB 87.3% python3.6
 1673 root   1 Compute   2033MB 11.9% python3.6

From the tests above, I believe xgboost loaded entire datasets from RAM into the GPU RAM, because there is almost no RX/TX when it is running on 1 P100 and the total memory for 2 P100 adds up to 17G which equals to the total in 1 P100. However, I wonder how it is determined on the memory allocation? With 4 K80, total memory is much higher than 1 P100 or 2 P100s. I feel the error pops up when the device 0 memory got over loaded. 

As a side question, I am looking for any suggestions if I can get xgboost work with dataset assuming my memory can hold them? I saw there is way to do incremental training like tensorflow at (https://stackoverflow.com/questions/38079853/how-can-i-implement-incremental-training-for-xgboost). However, can I run X rounds on 1 portion and another X rounds on another portion? If I am not mistaken, should it be run only 1 round in each portion, then loop multiple times through entire dataset (N epochs). If so, is there any way to get a loss/accuracy on entire loop/epoch? On the other side, do you think XGboost on Spark may be better to handle large dataset but process on CPU?

Look forward to hearing more. Thank you!

**Comment by trivialfis** [comment]
If I remember right, Tensorflow takes over the entire GPU by default and implement their own memory management system.
There's no canonical way to manage device memory in XGBoost, algorithms allocate there memory as they see fit,  so the implementation might change whenever needed.

**Comment by hcho3** [comment]
Also, Tensorflow uses an algorithm called Stochastic Gradient Descent, where a small batch is taken at a time to update the weights in the neural network. What's cool about SGD is that you only need  to load a small batch at a time. Gradient boosted trees unfortunately don't use SGD; all data must be in memory all the time.

**Comment by hcho3** [comment]
In the future, we may want to look info implementing tree algorithms that can be fit on streaming data: https://homes.cs.washington.edu/~pedrod/papers/kdd00.pdf
Streaming algorithms can largely remove the memory limit.

**Comment by Bluesn0w** [comment]
Thank you both!

Based on my test, it seems that the GPU 0 always takes the majority of the data. However, when the data size grows, it does not allocate enough of the data to the other GPUs, so the 1st device will be out of memory (Test 1 that K80 has 12GB memory and it failed at the end). Do you think there might be any work round solution? If the data can be hold inside of the GPU memory pool (evenly distributed across), then the solution can be extending number of GPUs in the system in the short term before Streaming algorithm is added.

**Comment by trivialfis** [comment]
@Bluesn0w For the imbalanced GPU usage, I think it's a solved problem in master branch now.

**Comment by trivialfis** [comment]
> Based on my test, it seems that the GPU 0 always takes the majority of the data. 

@Bluesn0w Hi, have you tried building the latest 0.81 release 
https://github.com/dmlc/xgboost/releases/tag/v0.81
or master branch?

**Comment by Bluesn0w** [comment]
Will take a try today and keep you posted! Thank you!!

**Comment by Bluesn0w** [comment]
@trivialfis and @hcho3, I just compiled the master (I don't think you made precompiled multi GPU supported 0.81 wheel this time if I am not mistaken). I ran the same code and confirmed that the data is allocated evenly with the latest version. In addition, the 4XK80 will no longer crush. Instead, I think it can hold more data than 2XP100 now.

Thank you for making this happen! Please feel free to close this.


**Test 1:** 2 X P100 (2X17.1G GPU Ram in total) - Google n1-highmem-32CPU-208G  Ram:
 Device 0 [Tesla P100-PCIE-16GB] PCIe GEN 3@16x RX: 61.00 MB/s TX: 1.000 MB/s
 GPU 1328MHz MEM 715MHz  TEMP  42°C FAN N/A% POW 120 / 250 W
 GPU-Util[||||||||||||||||||||||||90%] MEM-Util[||||||||||||||    8.5G/17.1G] Encoder[       0%] Decoder[       0%]

 Device 1 [Tesla P100-PCIE-16GB] PCIe GEN 3@16x RX: 234.0 MB/s TX: 53.00 MB/s
 GPU 1328MHz MEM 715MHz  TEMP  41°C FAN N/A% POW 122 / 250 W
 GPU-Util[||||||||||||||||||||||||93%] MEM-Util[||||||||||||||    8.5G/17.1G] Encoder[       0%] Decoder[       0%]

  PID USER GPU    TYPE            MEM Command
10368 root   0 Compute   8465MB 49.6% python3.6
10368 root   1 Compute   8465MB 49.6% python3.6


**Test 2:** 4 X K80 (4X12G GPU RAM in total) - Google n1-highmem-32CPU-208G Ram:

 Device 0 [Tesla K80] PCIe GEN 3@16x RX: N/A TX: N/A
 GPU 875MHz  MEM 2505MHz TEMP  39°C FAN N/A% POW 110 / 149 W
 GPU-Util[||||||||||||||||||||||||96%] MEM-Util[||||||||||        4.2G/12.0G] Encoder[       0%] Decoder[       0%]

 Device 1 [Tesla K80] PCIe GEN 3@16x RX: N/A TX: N/A
 GPU 875MHz  MEM 2505MHz TEMP  42°C FAN N/A% POW 121 / 149 W
 GPU-Util[||||||||||||||||||||||||94%] MEM-Util[||||||||||        4.2G/12.0G] Encoder[       0%] Decoder[       0%]

 Device 2 [Tesla K80] PCIe GEN 3@16x RX: N/A TX: N/A
 GPU 875MHz  MEM 2505MHz TEMP  48°C FAN N/A% POW 128 / 149 W
 GPU-Util[||||||||||||||||||||||||93%] MEM-Util[||||||||||        4.2G/12.0G] Encoder[       0%] Decoder[       0%]

 Device 3 [Tesla K80] PCIe GEN 3@16x RX: N/A TX: N/A
 GPU 875MHz  MEM 2505MHz TEMP  40°C FAN N/A% POW 112 / 149 W
 GPU-Util[||||||||||||||||||||||||93%] MEM-Util[||||||||||        4.2G/12.0G] Encoder[       0%] Decoder[       0%]

  PID USER GPU    TYPE            MEM Command
 2589 root   3 Compute   4182MB 34.9% python3.6
 2589 root   0 Compute   4182MB 34.9% python3.6
 2589 root   1 Compute   4182MB 34.9% python3.6
 2589 root   2 Compute   4182MB 34.9% python3.6

**Comment by trivialfis** [comment]
@Bluesn0w Thanks for the testing. Cheers.

**Comment by hcho3** [comment]
@Bluesn0w Yoy can get Multi-GPU builds from https://s3-us-west-2.amazonaws.com/xgboost-wheels/list.html?prefix=multigpu/. The wheels were too big to upload to PyPI.

**Comment by Bluesn0w** [comment]
@hcho3 got it! thanks! didn't realize you created a folder for that, so I only saw the other ones.
