### ISSUE TITLE
GPU utilization is zero with customized objective function

### ISSUE THREAD

**Issue by ch11y** [dmlc/xgboost#3832]
Hello, I am using customized objective function for regression. However the GPU utilization (TELSA P100) is zero for most of the time. Does XGBoost invoke GPU (or solely CPU instead) for the gradient and hessian calculation for customized objective function?

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.26                 Driver Version: 396.26                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:02:00.0 Off |                    0 |
| N/A   33C    P0    31W / 250W |   6791MiB / 16280MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P100-PCIE...  Off  | 00000000:82:00.0 Off |                    0 |
| N/A   35C    P0    33W / 250W |   6531MiB / 16280MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla P100-PCIE...  Off  | 00000000:85:00.0 Off |                    0 |
| N/A   36C    P0    31W / 250W |   6623MiB / 16280MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla P100-PCIE...  Off  | 00000000:86:00.0 Off |                    0 |
| N/A   37C    P0    33W / 250W |   7113MiB / 16280MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

**Comment by hcho3** [comment]
No, since the customized objective function is not written in CUDA and thus cannot run on GPU.

**Comment by ch11y** [comment]
Thank you for your instant reply. :+1:  Is there a way to hack it to run in CUDA?

**Comment by hcho3** [comment]
You will have to write a new objective function in CUDA and put it under `src/objective`.
