### ISSUE TITLE
Not able to verify my XGBoost load model, C-Code

### ISSUE THREAD

**Issue by harishvk27** [dmlc/xgboost#3837]
The question revolves around loading model file stored in text format.

I have written a python-to-c code which reads model and generates appropriate code.

My code is giving me wrong predictions, i am using XGBoost for multi-class classification with softprob.

I see the python prediction is differing from what C-code ( mycode ) is predicting. To confirm where the problem is.. i wanted to load the text formatted model file using libXGBoost.. but XGBoosterLoadModel() fails to load my text model file.. Following issue discusses this.. according to which i don't have a way to load text model file.
https://github.com/dmlc/xgboost/issues/2908

Now my question is how can i validate where the issue is?.
(1) Since i can't load text model file i can't really use libXGBoost to load text model file and confirm. Any suggestions on how can i go about?.
(2) Is there any tool utility which can convert binary/json model file to C code?.

-thanks
harish

**Comment by hcho3** [comment]
(1) Do you have the binary (non human-readable) model file saved somewhere? That's the file XGBoost generates. The function `XGBoosterLoadModel()` expects binary files, not text files.
(2) See [dmlc/treelite](https://github.com/dmlc/treelite), which generates C code from the binary model file.

**Comment by harishvk27** [comment]
Thanks. I tried using treelite.. have some issues.. will work with treelite.. for now. XGBoost doesn't seem to be the issue, closing on this.
