### ISSUE TITLE
[jvm-packages] Distributed xgboost should have an option to provide train/test separately.

### ISSUE THREAD

**Issue by clamoris** [dmlc/xgboost#3839]
Currently there is no way to provide custom train/test to Watches in distributed xgboost. There should be a way, either by providing split method or actual dataframes (directly or as Watches object) to set them because random is not always applicable.

Thanks.

**Comment by CodingCat** [comment]
coming next version 

duplicate with https://github.com/dmlc/xgboost/issues/3439
