### ISSUE TITLE
[jvm-packages] PySpark Wrapper: reg_lambda/lambda

### ISSUE THREAD

**Issue by tabrisnow** [dmlc/xgboost#3846]
Hi,

I am trying to access reg_lambda directly within the pySpark wrapper. I am able to set it with reg_lambda within the object declaration XGBoostRegressor(), but it is not possible to use it as xgboost.lambda, because lambda is a reserve word (?).

```
xgboost.lambda = 10

  File "<ipython-input-108-997093ef4404>", line 1
    xgboost.lambda = 10
                 ^
SyntaxError: invalid syntax
```
 But xgboost.alpha = 0.0 runs successfully.

**Comment by hcho3** [comment]
@tabrisnow PySpark wasn't merged to master yet, as far as I remember.

**Comment by CodingCat** [comment]
we don't support pyspark officially
