### ISSUE TITLE
the last feature is always missing from dumped model structure, how and why?

### ISSUE THREAD

**Issue by phoenixbai** [dmlc/xgboost#385]
Hi,

I am using xgboost for multi-class (4) classification problem. 

I have used 18 features to train the model using gbtree, and after dumping the trained model, I am able to find only 17 features corresponding from f0-f16, missing the last column.

I permutated the feature orders, and tried again, and still, only the last column is totally missing, never used once in anywhere in the boosting trees (that is, in total 10000 trees in my case).

I gave the featmap, and tried again, the same thing happened.

I tried with python interface as well as C interface. The result is consistent, with the last feature column missing always.

And I tried with data in both with svm format and comma-separated csv format, the results are still the same.

here is a slice of my training data:

<quote>
1 1:0.7270782171130703 2:1 3:0.72 4:11 5:1 6:0 7:0.7222222222222222 8:0.8181818181818182 9:0.73 10:640000 11:0.52 12:0.2324 13:9 14:1 15:0 16:0 17:0.11444092 18:0.041306373
1 1:0.3783786636650636 2:0 3:0.55 4:7 5:1 6:0 7:1.1818181818181819 8:1.4285714285714286 9:0.66 10:640000 11:0.65 12:0.442 13:10 14:1 15:0 16:0 17:0.11433411 18:0.028711427
1 1:0.6562135883284987 2:0 3:0.59 4:9 5:1 6:0 7:1.1355932203389831 8:1.1111111111111112 9:0.68 10:640000 11:0.67 12:0.44 13:10 14:1 15:0 16:0 17:0.11682129 18:0.020767836
1 1:0.5094741507557576 2:0 3:0.62 4:8 5:1 6:0 7:1.0483870967741935 8:1.25 9:0.67 10:640000 11:0.65 12:0.3758 13:10 14:1 15:0 16:0 17:0.2456665 18:0.024499971
1 1:0.7083912298081438 2:0 3:0.67 4:10 5:1 6:0 7:0.7313432835820896 8:1 9:0.69 10:640000 11:0.49 12:0.3502 13:10 14:1 15:0 16:0 17:0.013336182 18:0.046733383
1 1:0.6800423610572308 2:0 3:0.71 4:8 5:1 6:0 7:0.971830985915493 8:1.25 9:0.78 10:640000 11:0.69 12:0.3838 13:10 14:1 15:0 16:0 17:0.096710205 18:0.07017295
1 1:-1 2:0 3:-1 4:-1 5:1 6:0 7:-1 8:-1 9:-1 10:640000 11:-1 12:-1 13:-1 14:1 15:-1 16:-1 17:-1 18:-1
1 1:-1 2:0 3:-1 4:-1 5:1 6:0 7:-1 8:-1 9:-1 10:640000 11:-1 12:-1 13:-1 14:1 15:-1 16:-1 17:-1 18:-1
1 1:-1 2:0 3:-1 4:-1 5:-1 6:0 7:-1 8:-1 9:-1 10:-1 11:-1 12:-1 13:-1 14:-1 15:-1 16:-1 17:-1 18:-1
1 1:-1 2:0 3:-1 4:-1 5:1 6:0 7:-1 8:-1 9:-1 10:640000 11:-1 12:-1 13:-1 14:1 15:-1 16:-1 17:-1 18:-1
</quote>

And at last, I tried to add one more column with zero to the end of each line, and this time, it throws "AssertError:inconsistent col data" error. 

So, what could be the problem here? Anyone ever encounter with similar issue?

Please help, thanks

**Comment by tqchen** [comment]
It is possible for the dumped model to miss some of the features, simply because of they are not selected. Please check if there are duplication or similar columns in your data, in which case if two columns have same effect, the feature with smaller index will be selected.

**Comment by phoenixbai** [comment]
Yeah, I thought that too, so I permute the orders of the features in the input data and used featmap to corresponds to each feature, and dumped the model again, and what I found is that, every single time, the missing column is always the last one, so this is odd.

Could you guide me as to how I could debug this?

**Comment by tqchen** [comment]
Please check in the https://github.com/dmlc/xgboost/blob/master/src/tree/updater_colmaker-inl.hpp#L561 if every fid is touched.

What I meant is consider the case you have two identical columns, or two columns identical under transformation of scaling and translations. xgboost will always select the first one, thus the second one is missing.

**Comment by phoenixbai** [comment]
If I provide with only one feature as input, it throws error like this:

<code>colsample_bytree=1 is too small that no feature can be included</code>

So, it cannot due to identical or similar columns right?

**Comment by tqchen** [comment]
OK. Please check which version you are using, this should be a problem that is fixed in the most recent version in github

**Comment by phoenixbai** [comment]
version is xgboost-0.4 , which I am reading from README.md under root directory. 
Is it the version problem?
