### ISSUE TITLE
AWS YARN Guide is very very broken 

### ISSUE THREAD

**Issue by newnovice01** [dmlc/xgboost#3857]
This is very outdated - https://github.com/tqchen/yarn-ec2 

Please update.

**Comment by hcho3** [comment]
> outdated

Can you be more specific?

> Please update

Can you suggest a concrete step of action (or submit a draft pull request)?

**Comment by newnovice01** [comment]
https://github.com/tqchen/yarn-ec2/issues/6

**Comment by newnovice01** [comment]
./yarn-ec2 -k mykey -i mypem.pem launch xgboost
Setting up security groups...
Searching for existing cluster xgboost...
Launching instances...
ERROR:boto:400 Bad Request
ERROR:boto:<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidParameterValue</Code><Message>User data is limited to 16384 bytes</Message></Error></Errors><RequestID>42229824-0907-48a4-85d6-b8e571b92282</RequestID></Response>

**Comment by newnovice01** [comment]
> Can you suggest a concrete step of action?

As a simple next step if one of the dev's step thru that guide, 
1. there are lots of old instance types. 
2. Old AMI id's that do not support ENA's. 
3. All URL's are old and point to dead 404 links.

**Comment by hcho3** [comment]
@newnovice01 Thanks. It may be easier to re-write the whole tutorial.

**Comment by thvasilo** [comment]
I'd like to point out the [security vulnerability](https://github.com/tqchen/yarn-ec2/issues/5) in that guide, apart from being outdated.

My recommendation for users is to launch a YARN cluster using EMR or some other method and then simply download and build XGBoost at the master.

**Comment by newnovice01** [comment]
We should update this guy - https://xgboost.readthedocs.io/en/latest/tutorials/aws_yarn.html 

So everyone doesn't just blindly follows it and expectes it to work.

**Comment by hcho3** [comment]
@newnovice01 I will go ahead and take it down for now.
