### ISSUE TITLE
Add parameters to the plotting function to control the node shape

### ISSUE THREAD

**Issue by pjgao** [dmlc/xgboost#3858]
It is very convenient and beautiful to plot decision tree in `sklearn`:
```python
from sklearn.tree import export_graphviz
from sklearn.tree import DecisionTreeRegressor
import pydotplus
from IPython .display import Image 
def print_graph(clf, feature_names): 
    """Print decision tree.""" 
    graph = export_graphviz( clf,
                            label= "root" , 
                            proportion= True , 
                            impurity= False , 
                            out_file= None , 
                            feature_names=feature_names, 
                            #class_names={ 0 : "D" , 1 : "R" }, 
                            filled= True , 
                            rounded= True )
    graph = pydotplus.graph_from_dot_data(graph) 
    return Image (graph.create_png())

from sklearn.datasets import load_boston
d = load_boston()
dtr = DecisionTreeRegressor()
dtr.fit(pd.DataFrame(d['data'][:10,:10],columns=d['feature_names'][:10]),d['target'][:10])
print_graph(dtr,d['feature_names'][:10])
```
![regresiontree](https://user-images.githubusercontent.com/22350313/47947338-a21fb000-df55-11e8-81cb-2d61e02c4e55.png)

I can use `xgb.to_graphviz` plot the tree in xgboost too:
```python
import xgboost as xgb
import pandas as pd

clf = xgb.XGBRegressor(n_estimators=10)
clf.fit(pd.DataFrame(d['data'],columns=d['feature_names']),d['target'])
xgb.to_graphviz(clf)
```
![xgbtree](https://user-images.githubusercontent.com/22350313/47947302-3a696500-df55-11e8-929b-7abc302fcee2.png)

You can see the differences in these two plots:
1. xgboost plot node type is **not so beautiful**, It can **hardly displayed** because of the node shape is circle when graph is complex.  The node type should be **configurable**,  it will be better if adding a parameter in `to_graphviz` to control the node type in the plot.
2. xgboost plot don't have **sample data info** and **regression value** in every split.  

I just modify from [source code](https://github.com/dmlc/xgboost/blob/master/python-package/xgboost/plotting.py)

> ```python
> # line 166
> def to_graphviz(booster, fmap='', num_trees=0, rankdir='UT',
>                 yes_color='#0000FF', no_color='#FF0000', **kwargs): 
> # line 215
> node = _parse_node(graph, text)
> # line 127
> def _parse_node(graph, text):
> # line 132
>         graph.node(node, label=match.group(2), shape='circle')
> # line 137
>         graph.node(node, label=match.group(2), shape='box')
> ```
> 

to:

```python
# line 166
def to_graphviz(booster, fmap='', num_trees=0, rankdir='UT',
                yes_color='#0000FF', no_color='#FF0000',conditionNodeParams={},leafNodeParams={}, **kwargs):
 # line 215
node = _parse_node(graph, text,conditionNodeParams=conditionNodeParams,leafNodeParams= leafNodeParams)
# line 127
def _parse_node(graph, text,conditionNodeParams,leafNodeParams):
# line 132
        graph.node(node, label=match.group(2), **conditionNodeParams)
# line 137
        graph.node(node, label=match.group(2),**leafNodeParams)

```  

Now using the modified code, without params
```python
plotting.to_graphviz(clf)
```
![modifiedxgbplot](https://user-images.githubusercontent.com/22350313/47947495-689c7400-df58-11e8-99d7-598778f91081.png)  

adding params to control node types:
```python
cNodeParams = {'shape':'box',
               'style':'filled,rounded',
               'fillcolor':'#78bceb'
              }
lNodeParams = {'shape':'box',
               'style':'filled',
               'fillcolor':'#e48038'
              }
plotting.to_graphviz(clf,conditionNodeParams=cNodeParams,leafNodeParams=lNodeParams,**{'size':str(15)})
```
![modifiedxgbplotparams](https://user-images.githubusercontent.com/22350313/47947497-6d612800-df58-11e8-91cd-4349239cba62.png)

**Comment by trivialfis** [comment]
@hcho3  That seems nice.  I myself never understand how to make these nice plots. :(

**Comment by trivialfis** [comment]
@pjgao Would you like to make a PR for this?

**Comment by trivialfis** [comment]
@pjgao Nicely done. :)

**Comment by qkaver** [comment]
@pjgao @hcho3  I'm also very confused how to get sample data info like the decision tree above.How can i get the number of sample in every single leaf?      :(

**Comment by hcho3** [comment]
@qkaver Currently, the XGBoost model doesn't save the number of samples. #3452 is aimed at fixing that.
