### ISSUE TITLE
Dynamic multiclass classification problem

### ISSUE THREAD

**Issue by thiyangt** [dmlc/xgboost#3861]
I have a multi-class problem.  I have to define class weight for each class label for each instance. For example for the first observation my class labels is as follow: [0.2, 0.4. 0.4], where 0.2 is the probability of belonging to first class, 0.4 is the probability of belonging to second class and 0.4 is the probability of belonging to second class. Likewise I have a this type of vector for each instance. Is there a way to include this information in the xgboost algorithm.

**Comment by hcho3** [comment]
As of now, no. XGBoost assumes that each data point has a single label. Multi-label regression would be a new feature addition.

**Comment by thiyangt** [comment]
Thank you very much for the response
