### ISSUE TITLE
Set up continuous integration for Windows GPU target

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#3868]
This is a reminder to myself to set up CI for Windows GPU target. Goal: by next release.

**Comment by hcho3** [comment]
@trivialfis Good news: Windows now have a first-class support for SSH server. See https://winscp.net/eng/docs/guide_windows_openssh_server. I just tried it and found it very easy to set up. With SSH, the Jenkins master can spawn Windows slave workers on demand.

**Comment by trivialfis** [comment]
@RAMitchell would be glad to hear about this. :)

**Comment by hcho3** [comment]
Blocking issue: #4197

**Comment by hcho3** [comment]
Closing in favor of #3868.
