### ISSUE TITLE
using booster='gblinear' will trigger GPU(R-xgboost 0.81)? 

### ISSUE THREAD

**Issue by joegaotao** [dmlc/xgboost#3874]
When I test gblinear and I found the default model would trigger GPU usage while I didn't specify any GPU parameters.

from R-package demo with minor change
```
library('xgboost')

# Simulate N x p random matrix with some binomial response dependent on pp columns
set.seed(111)
N <- 1000000
p <- 50
pp <- 25
X <- matrix(runif(N * p), ncol = p)
betas <- 2 * runif(pp) - 1
sel <- sort(sample(p, pp))
m <- X[, sel] %*% betas - 1 + rnorm(N)
y <- rbinom(N, 1, plogis(m))

tr <- sample.int(N, N * 0.75)
dtrain <- xgb.DMatrix(X[tr,], label = y[tr])
dtest <- xgb.DMatrix(X[-tr,], label = y[-tr])
wl <- list(train = dtrain, test = dtest)

param <- list(objective = 'reg:linear', subsample = 0.5,  nthread = 10L, 
  booster = "gblinear", lambda = 1e-4, updater = "coord_descent", feature_selector = "random")
pt <- proc.time()
bst_gpu <- xgb.train(param, dtrain, watchlist = wl, nrounds = 50)
proc.time() - pt
```
I found GPU has a process (gpu_id = 0)and memory usage

I just compile R-xgboost (0.81) with multi-GPU.

```
git clone --recursive https://github.com/dmlc/xgboost
mkdir build
cd build
cmake .. -DUSE_CUDA=ON -DUSE_NCCL=ON -DNCCL_ROOT=/usr/local/nccl -DR_LIB=ON
make install -j4
```

**Comment by trivialfis** [comment]
Yes.  If XGBoost is compiled with CUDA support, it will try to run objective functions on GPU (1 GPU by default).  This reminds me that, I might need to add a switch to that.

**Comment by joegaotao** [comment]
OK,  I find there is a src/gpu_coord_descent.cu, and `updater = "gpu_coord_descent"` also makes GPU works, but the [xgboost doc](https://xgboost.readthedocs.io/en/latest/parameter.html#parameters-for-linear-booster-booster-gblinear) seems to miss that specification, maybe should add it to the doc?

**Comment by trivialfis** [comment]
I would love to organize the doc a bit.  It will also provide a good mental model for me to keep going.  Thanks for reminding.
