### ISSUE TITLE
rank:ndcg rusult is different with my own calculation

### ISSUE THREAD

**Issue by jjyock** [dmlc/xgboost#3875]
i use eval_metrics is ndcg@20 ,and i get the test-ndcg@20:0.818406 finally. but i try to calculate the predict result in test set. i get a totally different value 0.547。 this is my way, the score is 5,4,3,2,1,0 and the rank_pred is sorted by pred values in descending way. rank_true is the right rank, can you tell me how xgb get the test-ndcg?? thank you so much 
`
t.loc[:,'log(i+1)']=np.log2(t['rank_pred']+1)
t.loc[:,'dg'] = (2**t['score']-1)/t['log(i+1)']
t.loc[:,'ilog']=np.log2(t['rank_true']+1)
t.loc[:,'idg']=(2**t['score']-1)/t['ilog']
t['dg'].sum()/t['idg'].sum()
`

**Comment by jjyock** [comment]
i  read the code and i find the xgb maybe cal the ndcg use (2*rel-1)/log(i+1),but i calculate the test data, the result is also different with the iteration result.

**Comment by hcho3** [comment]
Try using metric `ndcg@20-` instead.

**Comment by hcho3** [comment]
@jjyock Any updates?
