### ISSUE TITLE
[jvm-packages] CPU Utilization across multi node clusters with xgboost4j

### ISSUE THREAD

**Issue by muralimadhanagopal** [dmlc/xgboost#3879]
Hi, I tried this algorithm on 200mb dataset across 3 node cluster. Each node has 2 cpu with 20 cores each, 40 cores in total. The cpu utlization on one node was 98%, going to 2 nodes reduced cpu utilization in each node to 50% and with 3 nodes cpu utlization dropped to 35% on each node.  So training time does not linearly scale with cpu resources across nodes. 

1. Do we need a bigger dataset to maximize utlization?
2. GBM is able to max out cores, why cant xgboost do the same?

**Comment by hcho3** [comment]
When you say GBM, which package are you referring to? Do you mean the R package?

**Comment by muralimadhanagopal** [comment]
Gradient Boosting Machines algorithm

**Comment by muralimadhanagopal** [comment]
on python

**Comment by muralimadhanagopal** [comment]
How and why does the nodes have to synchronize between tree build? That seems to be reason for low utlization. Where is it done in code, want to understand it better, thanks!

**Comment by CodingCat** [comment]
200 mb with 3 nodes does not make sense...distributed comes with cost for syncing histogram (about why, reading kdd paper about xgboost, weighted sketching part)

**Comment by muralimadhanagopal** [comment]
Thanks Nan. why would it need to sync the histogram? I just downloaded the source code, can you point me where its doing it? I would expect the job to just finish faster as we add nodes.

**Comment by CodingCat** [comment]
In distributed setting, each tree on each node is split based on the global information about your dataset, otherwise, You cannot get a “unified tree” for this iteration, read hist_maker.cc

**Comment by muralimadhanagopal** [comment]
ok thanks Nan, when would it make sense to go to multi node, if your dataset is huge and exceeds memory of one node?

**Comment by CodingCat** [comment]
Yes, the basic guidance is that you need to ensure that you spent most of
time in dealing with all training instances in your partition
