### ISSUE TITLE
xgboost Installation problem in R

### ISSUE THREAD

**Issue by sbarkakati** [dmlc/xgboost#388]
Hi I am trying to install xgboost using below code , but getting an error as shown below. Just to let you know that I have installed Rtools in my machine. Could anyone please advise what I am missing here?

install.packages('devtools')
devtools::install_github('dmlc/xgboost',subdir='R-package')

Below is the error log:
> devtools::install_github('dmlc/xgboost',subdir='R-package')
Downloading github repo dmlc/xgboost@master
Installing xgboost
"C:/PROGRA~1/R/R-32~1.0/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore CMD INSTALL  \
  "C:/Users/barkakatis/AppData/Local/Temp/Rtmp63HY5A/devtools17101fa128ee/dmlc-xgboost-167544d/R-package"  \
  --library="C:/Users/barkakatis/Documents/R/win-library/3.2" --install-tests 

* installing *source* package 'xgboost' ...
** libs

*** arch - i386
Warning: running command 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-32~1.0/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-32~1.0/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="xgboost.dll" ' had status 127
ERROR: compilation failed for package 'xgboost'
* removing 'C:/Users/barkakatis/Documents/R/win-library/3.2/xgboost'
Error: Command failed (1)

**Comment by pommedeterresautee** [comment]
Do you have [Rtools](https://cran.r-project.org/bin/windows/Rtools/) installed?

**Comment by sbarkakati** [comment]
yes I installed Rtools and it worked.. Thank youSantanu 


     On Wednesday, 22 July 2015, 11:46, Michaël Benesty <notifications@github.com> wrote:
   

 Do you have Rtools installed?—
