### ISSUE TITLE
n_jobs=-1 doesn't work when passing XGBoostClassifier to xgboost.cv

### ISSUE THREAD

**Issue by nathaneastwood** [dmlc/xgboost#3880]
If I pass the following classifier to `xgboost.cv`, the `njobs=-1` parameter is not picked up and the function is not fit in a parallelised way

```
xgb1 = XGBClassifier(
    learning_rate=0.1,
    n_estimators=1000,
    max_depth=5,
    min_child_weight=1,
    gamma=0,
    subsample=0.8,
    colsample_bytree=0.8,
    objective='multi:softmax',
    num_class=4,
    njobs=-1,
    scale_pos_weight=1,
    random_state=seed
)
xgb.cv(xgb1.get_xgb_params(), train, ...)
```

However the following does work

```
xgb1 = XGBClassifier(
    learning_rate=0.1,
    n_estimators=1000,
    max_depth=5,
    min_child_weight=1,
    gamma=0,
    subsample=0.8,
    colsample_bytree=0.8,
    objective='multi:softmax',
    num_class=4,
    nthreads=-1,
    scale_pos_weight=1,
    random_state=seed
)
xgb.cv(xgb1.get_xgb_params(), train, ...)
```

And the function is fit in a parallelised fashion. I am running `xgboost==0.80` on `Python 3.7.1`.

**Comment by hcho3** [comment]
Did you mean to use `n_jobs`?

**Comment by nathaneastwood** [comment]
Sorry, that is what I used. But it still wasn’t picked up. I copy and pasted my `nthreads` codes and wrote `njobs` instead of `n_jobs`

**Comment by nathaneastwood** [comment]
Oddly this is working now, maybe I did use `njobs` instead of `n_jobs` without realising. I'll reopen this issue if it happens again.
