### ISSUE TITLE
xgboost\core.py:1024: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working

### ISSUE THREAD

**Issue by KOLANICH** [dmlc/xgboost#3881]
>xgboost\core.py:1024: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working

https://github.com/dmlc/xgboost/blob/19ee0a357964f4c0a7cef6c00da2e8478e360974/python-package/xgboost/core.py#L1024

**Comment by trivialfis** [comment]
@KOLANICH Addressed in  #3909. Thanks!
