### ISSUE TITLE
HDFS includes and libraries NOT found when compiling spark xgboost with USE_HDFS on

### ISSUE THREAD

**Issue by goodturing** [dmlc/xgboost#3882]
The error info is as follow: 
-- Architecture: x64
-- HDFS_LIB_PATHS: /lib/native
CMake Error at dmlc-core/cmake/Modules/FindHDFS.cmake:64 (message):
  HDFS includes and libraries NOT found.(HDFS_INCLUDE_DIR-NOTFOUND,
  HDFS_LIB-NOTFOUND)
Call Stack (most recent call first):
  dmlc-core/CMakeLists.txt:32 (find_package)

But I can't find any libhdfs anywhere

**Comment by hcho3** [comment]
Did you install Apache Hadoop?

**Comment by goodturing** [comment]
Yes. I had. Hadoop and HDFS path are as follows: /usr/local/Cellar/hadoop/3.1.1//bin/hdfs; /usr/local/Cellar/hadoop/3.1.1//bin/hadoop . But I can't find hdfs lib path. Could you tell me how to set or compile hdfs ? Thank you very much.

**Comment by hcho3** [comment]
@goodturing Did you use Homebrew to install Hadoop? I tried it and the Homebrew formula doesn't seem to include libhdfs. For best results, please download the source from [Apache website](https://hadoop.apache.org/releases.html) and compile.

**Comment by hcho3** [comment]
@goodturing For your information, here are the steps for compiling from the source:
```
# Compile HDFS native library from source
cd
wget http://mirrors.advancedhosters.com/apache/hadoop/common/hadoop-3.1.1/hadoop-3.1.1-src.tar.gz
tar xvf hadoop-3.1.1-src.tar.gz
cd hadoop-3.1.1-src/hadoop-hdfs-project/hadoop-hdfs-native-client
CC=gcc-8 CXX=g++-8 mvn compile -Pnative   # Use Homebrew GCC

# Create HDFS home under the home directory
cd
mkdir hdfs_home
cd hdfs_home
mkdir -p lib/native
# Copy libhdfs.so
cp -rv ~/hadoop-3.1.1-src/hadoop-hdfs-project/hadoop-hdfs-native-client/target/native/target/usr/local/lib/ ./lib/native/
# Copy hdfs.h
cp -rv ~/hadoop-3.1.1-src/hadoop-hdfs-project/hadoop-hdfs-native-client/src/main/native/libhdfs/include/hdfs/ ./include/

# Now build XGBoost with libhdfs
cd /path/to/xgboost
mkdir build
cd build
HADOOP_HDFS_HOME=${HOME}/hdfs_home CC=gcc-8 CXX=g++-8 cmake .. -DUSE_HDFS=ON
make
```

**Comment by goodturing** [comment]
Yes, I installed hadoop by brew. Then I fall back to Hadoop 2.7.7. This problem has been solved. But I encountered another problem.

ld: warning: ignoring file /WKS/hadoop-2.7.7/lib/native/libhdfs.a, file was built for archive which is not the architecture being linked (x86_64): /WKS/hadoop-2.7.7/lib/native/libhdfs.a
Undefined symbols for architecture x86_64:
  "_hdfsCloseFile", referenced from:
      dmlc::io::HDFSStream::~HDFSStream() in libdmlc.a(hdfs_filesys.cc.o)
      dmlc::io::HDFSStream::~HDFSStream() in libdmlc.a(hdfs_filesys.cc.o)
  "_hdfsConfGetStr", referenced from:
      dmlc::io::FileSystem::GetInstance(dmlc::io::URI const&) in libdmlc.a(io.cc.o)
  "_hdfsConnect", referenced from:
      dmlc::io::HDFSFileSystem::HDFSFileSystem(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) in libdmlc.a(hdfs_filesys.cc.o)
      dmlc::io::HDFSFileSystem::ResetNamenode(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) in libdmlc.a(hdfs_filesys.cc.o)
  "_hdfsDisconnect", referenced from:
      dmlc::io::HDFSFileSystem::~HDFSFileSystem() in libdmlc.a(hdfs_filesys.cc.o)
      dmlc::io::HDFSFileSystem::~HDFSFileSystem() in libdmlc.a(hdfs_filesys.cc.o)
      dmlc::io::HDFSFileSystem::~HDFSFileSystem() in libdmlc.a(hdfs_filesys.cc.o)
      dmlc::io::HDFSFileSystem::ResetNamenode(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) in libdmlc.a(hdfs_filesys.cc.o)
      dmlc::io::HDFSStream::~HDFSStream() in libdmlc.a(hdfs_filesys.cc.o)
      dmlc::io::HDFSStream::~HDFSStream() in libdmlc.a(hdfs_filesys.cc.o)
  "_hdfsFreeFileInfo", referenced from:
      dmlc::io::HDFSFileSystem::GetPathInfo(dmlc::io::URI const&) in libdmlc.a(hdfs_filesys.cc.o)
      dmlc::io::HDFSFileSystem::ListDirectory(dmlc::io::URI const&, std::vector<dmlc::io::FileInfo, std::allocator<dmlc::io::FileInfo> >*) in libdmlc.a(hdfs_filesys.cc.o)
  "_hdfsGetPathInfo", referenced from:
      dmlc::io::HDFSFileSystem::GetPathInfo(dmlc::io::URI const&) in libdmlc.a(hdfs_filesys.cc.o)
  "_hdfsListDirectory", referenced from:
      dmlc::io::HDFSFileSystem::ListDirectory(dmlc::io::URI const&, std::vector<dmlc::io::FileInfo, std::allocator<dmlc::io::FileInfo> >*) in libdmlc.a(hdfs_filesys.cc.o)
  "_hdfsOpenFile", referenced from:
      dmlc::io::HDFSFileSystem::Open(dmlc::io::URI const&, char const*, bool) in libdmlc.a(hdfs_filesys.cc.o)
  "_hdfsRead", referenced from:
      dmlc::io::HDFSStream::Read(void*, unsigned long) in libdmlc.a(hdfs_filesys.cc.o)
  "_hdfsSeek", referenced from:
      dmlc::io::HDFSStream::Seek(unsigned long) in libdmlc.a(hdfs_filesys.cc.o)
  "_hdfsTell", referenced from:
      dmlc::io::HDFSStream::Tell()    in libdmlc.a(hdfs_filesys.cc.o)
  "_hdfsWrite", referenced from:
      dmlc::io::HDFSStream::Write(void const*, unsigned long) in libdmlc.a(hdfs_filesys.cc.o)
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[2]: *** [../xgboost] Error 1
make[1]: *** [CMakeFiles/runxgboost.dir/all] Error 2
make: *** [all] Error 2
building Java wrapper
cd ..
mkdir -p build
cd build
cmake .. -DUSE_OPENMP:BOOL=OFF -DUSE_HDFS:BOOL=ON -DUSE_AZURE:BOOL=OFF -DUSE_S3:BOOL=ON -DPLUGIN_UPDATER_GPU:BOOL=OFF -DJVM_BINDINGS:BOOL=ON
cmake --build . --config Release
Traceback (most recent call last):
  File "create_jni.py", line 89, in <module>
    run("cmake --build . --config Release")
  File "create_jni.py", line 51, in run
    subprocess.check_call(command, shell=True, **kwargs)
  File "/anaconda3/lib/python3.7/subprocess.py", line 328, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cmake --build . --config Release' returned non-zero exit status 2.
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)

**Comment by hcho3** [comment]
Did you compio Hadoop 2.7.7 from source? Don't use the binary tarball, since it contains Linux binaries and doesn't work with Mac OSX.

As an aside, if you plan to deploy your application to a Spark cluster, it may be best to use a Linux machine instead.

**Comment by goodturing** [comment]
Yes I used binary tarball directly. I am used to view/edit codes on mac, Maybe I should use linux machine. Thanks a lot.
