### ISSUE TITLE
Is it possible to load a spark-trained model in non-spark environment, or vice versa?

### ISSUE THREAD

**Issue by FredYao** [dmlc/xgboost#3883]
I have tried XGBoost4j and XGBoost4j-spark to persist trained models. However, the persisted models have different formats. The model persisted using XGBoost4j is a single file, while the one persisted using XGBoost4j-spark is a folder containing two subfolders: data and metadata. 

Is it possible to load a XGBoost4j-spark model in a non-spark environment, or load XGBoost4j model in a spark environment? Thanks!

**Comment by hcho3** [comment]
See https://xgboost.readthedocs.io/en/latest/jvm/xgboost4j_spark_tutorial.html#interact-with-other-bindings-of-xgboost

**Comment by FredYao** [comment]
@hcho3 , thank you for pointing out the details. It works for me! I will close the issue.
