### ISSUE TITLE
Invalid Parameter format for num_feature expect int but value='4294967258'

### ISSUE THREAD

**Issue by newnovice01** [dmlc/xgboost#3884]
[18:18:13] start ip-172-31-20-145:1
[18:18:13] Load part of data 1 of 4 parts
[18:18:45] Load part of data 1 of 4 parts
terminate called after throwing an instance of 'dmlc::ParamError'
  what():  Invalid Parameter format for num_feature expect int but value='4294967258'

This is with training of Criteo TB dataset for 1 day's worth in libsvm format. I was also using 1 days worth of data for test. 

https://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/binary.html#criteo

**Comment by hcho3** [comment]
@newnovice01 This is a limitation of XGBoost: number of features cannot exceed `INT_MAX` (2147483647). For now, I will have the program throw exception when number of features is too big. We do want to remove the limitation eventually, however.
