### ISSUE TITLE
Installation problem on MacOSX

### ISSUE THREAD

**Issue by AlexUnderMicrocontRoll** [dmlc/xgboost#389]
Could you please clarify what you mean with change the header. do you mean this file Rconfig.h??
and what should be changend exactly. Still can't import xgboost into python projects

**Comment by tqchen** [comment]
I think it means in the instruction  change line 9 in xgboost/src/utils/omp.h 
```
#include <libiomp/omp.h> /* instead of #include <omp.h> */` 
```

**Comment by AlexUnderMicrocontRoll** [comment]
thanks for reply. At the end it was a foolish usage :D but now my scripts a running.
