### ISSUE TITLE
[jvm-packages] there is no such aritfactId

### ISSUE THREAD

**Issue by Demon888** [dmlc/xgboost#3898]
There is no such artifactId with this version in mvn repository. 
```xml
<groupId>net.alchim31.maven</groupId>
<artifactId>maven-site-plugin</artifactId>
<version>3.0</version>
```
The pom file lies in "xgboost/jvm-packages/pom.xml". Please give the right one.

**Comment by hcho3** [comment]
@Demon888 Do you have any suggestion?

**Comment by Demon888** [comment]
For now, I do not. I should understand the project architecture first.
