### ISSUE TITLE
xgboost in R (latest version) "Error in .Call("XGCheckNullPtr_R", bst$handle, PACKAGE = "xgboost") :"

### ISSUE THREAD

**Issue by darraghdog** [dmlc/xgboost#390]
Hi, 
I'm running into an issue with the latest version of xgboost R package. I downloaded today to take advantage of the early stopping in R with cross validation. I downloaded the package using "devtools::install_github('dmlc/xgboost',subdir='R-package')". I am on a win7 PC. 
The function is fine for iterating through round however it fails when writing out the model, with the error "Error in .Call("XGCheckNullPtr_R", bst$handle, PACKAGE = "xgboost") :". I ran this over one of the R demos and I got the same result.
Do you have any ideas on this issue ? 
Thanks,
Darragh.

> require(xgboost)
> # load in the agaricus dataset
> data(agaricus.train, package='xgboost')
> data(agaricus.test, package='xgboost')
> dtrain <- xgb.DMatrix(agaricus.train$data, label = agaricus.train$label)
> dtest <- xgb.DMatrix(agaricus.test$data, label = agaricus.test$label)
> watchlist <- list(eval = dtest, train = dtrain)
> ###
> # advanced: start from a initial base prediction
> #
> print('start running example to start from a initial prediction')
[1] "start running example to start from a initial prediction"
> # train xgboost for 1 round
> param <- list(max.depth=2,eta=1,nthread = 2, silent=1,objective='binary:logistic')
> bst <- xgb.train( param, dtrain, 1, watchlist )
[0]	eval-error:0.042831	train-error:0.046522
Error in .Call("XGCheckNullPtr_R", bst$handle, PACKAGE = "xgboost") : 
  "XGCheckNullPtr_R" not available for .Call() for package "xgboost"

**Comment by darraghdog** [comment]
Just an extra note... This was working for me previously with an xgboost version about 2 months old.

**Comment by tqchen** [comment]
This can mean hat latest version is not compiled and the xgboost dll was a bit outdated, while you installed the R script to the most up to date version.

Please check if the devtools correctly compiles and installs the dll. You can also try directly uninstall the previous version, clear the temp files, and retry again

**Comment by darraghdog** [comment]
Thanks Tianqi, I removed the package, deleted the xgboost folder and reinstalled. Now xgb.cv and xgboost functions are working.
