### ISSUE TITLE
Function to extract gradient of objective relative to query datapoint

### ISSUE THREAD

**Issue by scottfleming** [dmlc/xgboost#3911]
I'd love it if there were a way to extract the gradient for a differentiable objective on a particular data point. For example, let's say I have 

xgb_train = xgb.DMatrix(X_train, label=y_train)
xgb_test_sample = xgb.DMatrix(X_test[0, :], label=y_test[0])
xgb_model = xgb.train(params, xgb_train)  
# ^^^where params['objective'] = 'binary:logistic', for example

Then what I want is something like: 

xgb_model.get_gradient(xgb_test_sample)

which would return the gradient of the objective relative to that sample (the idea being that it gives you something about which features in the model you should change and the direction in which you should change them if you wanted to maximally increase the model's output).

Does something like that already exist and I'm just missing it? I looked briefly but didn't find anything.

Huge thanks for an awesome package!

**Comment by trivialfis** [comment]
> Does something like that already exist and I'm just missing it?
I don't think so.  Gradient computation is not exposed in C APIs.

**Comment by hcho3** [comment]
@scottfleming You can look at the C++ definition of gradient computation: https://github.com/dmlc/xgboost/blob/dc2bfbfde144ada58c6992f0315e27064a5f8ea6/src/objective/regression_loss.h#L55
