### ISSUE TITLE
Data format for pairwise ranking in XGBOOST

### ISSUE THREAD

**Issue by anuragreddygv323** [dmlc/xgboost#3915]
I want to know if the pairwise loss which implements labdaMART does incorporate delta ndcg, which gives more weightage to the pairs in the top of the ranking list.

Data format

0 qid: 1 ... features   
0 qid: 1 ...features
0 qid:1 ...features
1 qid:1 ..features

0 qid: 2... features 
0 qid: 2 ...features
1 qid:2 ...features
0 qid:2 ..features

by mentioning the individual groups in the exact order of the real world experiment, does xgboost optimizes for pairwise loss with **LAMDArank weights** considering the rank and also the preference label ?

**Comment by hcho3** [comment]
Have you considered using `rank:ndcg` instead of `rank:pairwise`?

**Comment by anuragreddygv323** [comment]
if I use rank:ndcg vs rank:pariwise, how is the data format change ?

**Comment by hcho3** [comment]
The format is the same.

**Comment by anuragreddygv323** [comment]
Weighing each pairwise loss by the diference in NDCG resulting from swapping the positions of the two listings making up the pair.  is prioritized the rank optimization of the booked listing towards the top of the search result list, instead of the bo om. For example, improving the rank of a booked listing from position 2 to 1 would get priority over moving a booked listing from position 10 to 9.

how to implement this ?

**Comment by anuragreddygv323** [comment]
> The format is the same.

it computes the pairs automatically in the case of pairwise loss ?

**Comment by hcho3** [comment]
`rank:ndcg` should optimize ranking so as to optimize the overall NDCG measure. The NDCG measure is discounted over the list position, so it favors moving a relevant listing from 2 to 1, as supposed to moving a relevant listing from 10 to 9.

> it computes the pairs automatically in the case of pairwise loss ?

Yes. You can read the code at https://github.com/dmlc/xgboost/blob/93f63324e62c9e04269d17bc6505137a18dcc900/src/objective/rank_obj.cc#L41.

**Comment by anuragreddygv323** [comment]
Thanks!
