### ISSUE TITLE
Should we remove the locking bot

### ISSUE THREAD

**Issue by KOLANICH** [dmlc/xgboost#3922]
Locking an issue prevents authors of the messages in it from editing them, for example fixing the links.

**Comment by hcho3** [comment]
Threads are locked only after 90 days of inactivity, and only if they are already closed. Can you think of a scenario where someone wants to edit such threads?

**Comment by hcho3** [comment]
I will bring this to discussion among the current maintainers.

**Comment by hcho3** [comment]
Got it. Will discuss this with current maintainers (there are 12 of them).

Some background: The locking bot was adopted with consensus among the maintainers. The idea was that it was difficult for us maintainers to respond to comments added to issues closed long ago: https://www.henryzoo.com/blog/2018/05/06/an-issue-with-issues.html

**Comment by hcho3** [comment]
@trivialfis What do you think?

**Comment by trivialfis** [comment]
@hcho3 I think 90 days is long enough.  If there's information in the issue important enough that needs to be updated, the information should belong to the documentation or something similar to wiki.

**Comment by hcho3** [comment]
@trivialfis Since all old threads have been locked, I will update `lock.yml` to add explanatory comment.
