### ISSUE TITLE
Using customized subset of features when growing tree for different depths

### ISSUE THREAD

**Issue by ch11y** [dmlc/xgboost#3923]
This might not be an issue. Please let me know if I need to move this question.

Does XGBoost have a plan to make user define a customized features sets for splitting at each depth? It might be a pretty useful feature for many applications.

when depth = 1, only using [f1, f2, f3]
when depth = 2, only using [f1, f2]
when depth = 3, only using [f2, f3]

**Comment by hcho3** [comment]
No, we don't have a plan now. But we'll consider a pull request to implement it. There is already feature interaction constraints, so the proposed feature shouldn't be too hard to implement.

**Comment by ch11y** [comment]
Thank you.

**Comment by hcho3** [comment]
By any chance, would you be interested in implementing it?

**Comment by ch11y** [comment]
Yes. I am very interested in this feature.

**Comment by hcho3** [comment]
Great! When do you plan to start working on it?

**Comment by ch11y** [comment]
I think I can work on it during every weekend probably.

**Comment by hcho3** [comment]
That's nice to hear. A good place to start is to look at the implementation for feature interaction constraints: https://github.com/dmlc/xgboost/blob/dc2bfbfde144ada58c6992f0315e27064a5f8ea6/src/tree/split_evaluator.cc#L346

This is one of three **split evaluator**, which assigns scores of candidate splits. By assigning negative infinity score for all splits with forbidden features at each level, you can restrict the choice of splits in each level.

**Comment by hcho3** [comment]
I opened a new issue to discuss a possible implementation of user-defined split evaluator: #4230
