### ISSUE TITLE
rename num_boost_round to n_estimators

### ISSUE THREAD

**Issue by KOLANICH** [dmlc/xgboost#3925]
It is a hyperparam which is not in a hyperparams dict, and since we need it also to be tuned, saved and restored, I guess it is more convenient to have an alias the same as in sklearn. 

It could look like
```python
def train(params, dtrain, n_estimators=None, ..., num_boost_round=10):
   if n_estimators:
      num_boost_round=n_estimators
```

Or it may be even better to put it into hyperparams dict.

BTW in lots of places in the docs it is called just `num_round`

**Comment by trivialfis** [comment]
I don't think the `num_boost_round` has the same meaning as `n_estimators`.  `num_boost_round` essentially means how many trees/forests you want to **add**.  `n_estimators` doesn't carry such information.

> lots of places in the docs it is called just num_round

That's a weird parameter used in various interface including cli.
