### ISSUE TITLE
[jvm-packages] Early Stopping Broken with xgboost4j-spark 0.81

### ISSUE THREAD

**Issue by mingyang** [dmlc/xgboost#3927]
# Issue
Early stopping kicks in after **the very first iteration** with xgboost4j-spark 0.81. In other words, it stops **before** the eval metric turns around, and **doesn't wait** for `num_early_stopping_rounds` rounds, either.

# Environment
Spark local mode
```
spark-shell --master local[2] --driver-memory 10g --packages ml.dmlc:xgboost4j-spark:0.81
```

# To Reproduce the Issue
## Code
```
import ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier

val train = spark.read.format("libsvm").load("file:///path/to/iris_binary.txt")
train.groupBy("label").count().show()
// +-----+-----+
// |label|count|
// +-----+-----+
// |  0.0|  100|
// |  1.0|   50|
// +-----+-----+

val xgbParam = Map(
      "objective" -> "binary:logistic",
      "max_depth" -> 3,
      "num_round" -> 1000,
      "num_workers" -> 2,
      "eval_metric" -> "logloss",       // "eval_metric" -> "auc",  "maximize_evaluation_metrics" -> "true", doesn't work either
      "maximize_evaluation_metrics" -> "false",
      "training_metric" -> "true",
      "train_test_ratio" -> 0.8,
      "num_early_stopping_rounds" -> 10,
      "silent" -> 0
)

val xgbClassifier = new XGBoostClassifier(xgbParam).setFeaturesCol("features").setLabelCol("label")

val xgbModel = xgbClassifier.fit(train)
```
## Data File
[iris_binary.txt](https://github.com/dmlc/xgboost/files/2605904/iris_binary.txt)
## Log
[xgboost4j-spark-0.81-early-stopping.log](https://github.com/dmlc/xgboost/files/2605911/xgboost4j-spark-0.81-early-stopping.log)

**Comment by CodingCat** [comment]
https://github.com/dmlc/xgboost/pull/3928 should fix the problem, you can grab the code and compile locally, I will release a 0.82-SNAPSHOT soon

**Comment by CodingCat** [comment]
fixed by https://github.com/dmlc/xgboost/pull/3928
