### ISSUE TITLE
Change name of objective:linear_regression

### ISSUE THREAD

**Issue by thvasilo** [dmlc/xgboost#3929]
Inspired from [this issue](https://discuss.xgboost.ai/t/boosted-tree-for-regression/456) on the discussion board, right now we are calling the squared error objective linear regression which, as was the case in the linked issue is confusing to the users, especially I assume when combined with the fact that XGBoost offers a linear learner as well.

So I'm curious on the community's opinion on (eventually, after a couple of deprecating releases) changing the naming of the "reg:linear" objective to something like "reg:squarederror".

**Comment by hcho3** [comment]
I agree. `reg:linear` is a misnomer, since we are not really performing linear regression. We are really performing regression task with squared loss. `reg:squarederror` sounds better.

**Comment by CodingCat** [comment]
I would suggest first deprecating and then replacing

**Comment by thvasilo** [comment]
Cool, @hcho3 could you add this to the roadmap so we don't lose track? We can discuss the timing of deprecation/replacement in terms of releases.
