### ISSUE TITLE
DMatrix takes csv header into account when counting number of rows

### ISSUE THREAD

**Issue by mateuszkaleta** [dmlc/xgboost#3933]
# Environment:
- Windows 10
- Anaconda 3.5.1
- python=3.6.6
- xgboost==0.81

# Issue

I'm trying to load a CSV file into a xgb.DMatrix object.  The file has a header and a few rows.

## Current behaviour:
- dmatrix.num_row() = len(data) + 1 (especially important if you point DMatrix not to a file, but to a directory)
- DMatrix ignores header when defining feature names
- dmatrix.get_label() returns additional '0' at the beginning (for each file)

## Expected behaviour:
- dmatrix.num_row() = len(data) (header is ignored when counting rows)
- dmatrix.feature_names is defined according to the header ('feature_a', 'feature_b' for the following example)
- dmatrix.get_label() returns [1, 0, 1] for the following example

## Example:

```
import xgboost as xgb


if __name__ == '__main__':

    with open('sample.csv', 'w') as output:
        output.write('feature_a,feature_b,label\r')
        output.write('0.3,1.2,1\r')
        output.write('2.4,5.2,0\r')
        output.write('0.3,-1.2,1')

    dmatrix = xgb.DMatrix('sample.csv?format=csv&label_column=2')
    print('Num row: %d' % dmatrix.num_row())
    print('Label: {}'.format(dmatrix.get_label()))
```

### Output:
```
[13:12:47] 4x2 matrix with 8 entries loaded from sample.csv?format=csv&label_column=2
Num row: 4
Label: [0. 1. 0. 1.]
```

**Comment by hcho3** [comment]
Currently, the DMLC parser for CSV is limited and does not recognize the header. Consider using Pandas for proper CSV parsing. I may want to document this limitation.

**Comment by mateuszkaleta** [comment]
Okay, I hope I'll find time to implement this and make a proper pull request some day. Thanks.

**Comment by hcho3** [comment]
@mateuszkaleta Sorry for inconvenience. If you do choose to implement this feature some time, you should change [dmlc-core](https://github.com/dmlc/dmlc-core) package.

**Comment by mateuszkaleta** [comment]
No worries, I'll handle it somehow - you guys are doing a great job here anyway :).
