### ISSUE TITLE
Incorrect default scorer for objective='reg:linear'

### ISSUE THREAD

**Issue by david-waterworth** [dmlc/xgboost#3939]
The code below fails with an unsupported type 'continuous' exception implying that GridSearchCV is using a classification scorer to try and score each fit. Setting 'GridSearchCV(...,scoring='neg_mean_squared_error')' solves the issue.

from the documentation of GridSearchCV, the default for scoring states 'If None, the estimator’s default scorer (if available) is used.', so this implies that the default scorer for XGBClassifier is ignoring objective='reg:linear'?

```
parameters = {'max_depth': [1],
              'n_estimators': [1]}
xgb_model = xgb.XGBClassifier(objective='reg:linear',n_jobs=1,silent=False)
xg_reg = GridSearchCV(xgb_model, 
                      param_grid=parameters,
                      cv=2, 
                      verbose=100,
                      n_jobs=1)
xg_reg.fit(X_train, y_train)
```

**Comment by thvasilo** [comment]
Hello @david-waterworth, shouldn't you be using XGBRegressor if your are performing regression?

**Comment by david-waterworth** [comment]
Thanks, yes I was using the wrong class!
