### ISSUE TITLE
xgboost installation for R with clear instructions

### ISSUE THREAD

**Issue by alben123** [dmlc/xgboost#394]
Hi,

Devtools link is not working and i'm not able to follow the work around given,

please help to give step by step instructions for non technical people to follow. 

Thanks in Advance
Alben

**Comment by tqchen** [comment]
Please give more details about what happens in your devtool installation, the output of the command, and the environment you are installing the toolkit

**Comment by alben123** [comment]
Hi Tqchen,

Thank you very much for the response

After installing devtools and Rtools (setting the path), it is still
throwing an error saying..

"Error in Curl :: curl_fetch_memory(URL, handle=handle)"

Moreover, when i tried workaround, I am not able to follow this work around
given

1) clone the repository and set the workspace to ...
2) run R cmd install ....
3) run install.packages('path...

Regards
Alben

**Comment by tqchen** [comment]
You can try the alternative, 

* download https://github.com/dmlc/xgboost/archive/master.zip
* unzip it on the root of the folder
* run ```R cmd install R-package```

there might be error message reporting some packages missing, please install these packages and try again

**Comment by pommedeterresautee** [comment]
Seems related: 
http://stackoverflow.com/questions/31311872/error-while-using-install-github-devtools-timeout-issue

```R
options(download.file.method = "wininet")
library("devtools")
...
```

**Comment by tqchen** [comment]
You can now install xgboost from CRAN https://github.com/dmlc/xgboost/tree/master/R-package
