### ISSUE TITLE
Loading data type of DMatrix

### ISSUE THREAD

**Issue by veronicaCode** [dmlc/xgboost#3940]
Will xgb.DMatrix support input python list in the future?

**Comment by trivialfis** [comment]
@veronicaCode 
Internally `xgboost.DMatrix` converts list into `scipy.sparse.csr_matrix`.  So one can say that it's supported.
But List by itself doesn't have properties like `shape`, so it's not clear whether one is passing data with 1 feature of `len(data)` rows, or 1 row with `len(data)` features, which might lead to buggy code.  Do you think it's a better practice to specify it at the user's end?
