### ISSUE TITLE
PyPi metadata requires_dist issue

### ISSUE THREAD

**Issue by fizwit** [dmlc/xgboost#3941]
pytables is in pypi metadata: requieres_dist but it is an incorrect package name.  Maybe it should be pytable.

**Comment by trivialfis** [comment]
@fizwit Hi, can you show me a pointer to it?  I grep the whole repository and search https://pypi.org/project/xgboost/ without seeing a mention of it.  I'm not familiar with pip uploading process.
@hcho3 Is there anything related to pypi but not included in this repo?

**Comment by fizwit** [comment]
I create automated software to update Python package versions and expect to find Python packages in PyPi. PyTables is a valid Python package name, but it is not in PyPi.  It must be downloaded from github. closing
