### ISSUE TITLE
Is the xgboost documentation wrong ? (early stopping rounds and best and last iteration)

### ISSUE THREAD

**Issue by lyxthe** [dmlc/xgboost#3942]
The xgboost documentation says that in the scikit-learn api wrapping xgboost, when early_stopping_round = x, the model will train until it didn't improve for x consecutive rounds then it "returns the model from the last iteration (not the best one)"

but when I test the predict of my model without precising ntree_limit parameter, it seems that it is in fact the best iteration that is used not the last one.

Is there an error in the xgboost documentation on the scikit-learn api section ?

**Comment by lyxthe** [comment]
To be more precise, the documentation is quite inconsistent in the scikit-learn api section since the fit paragraph tells that when early stopping rounds occures, the last iteration is returned not the best one, but when call the predict and with ntree_limit specified, then ntree_limit is equals to best_ntree_limit.

Thus, when reading the fit part, one could think that it is needed to specify what is the best iter when calling the predict, but when reading the predict part, then the best iter is given by default, it is the last iter that you have to specify if needed.

**Comment by hcho3** [comment]
Fixed in #3967.
