### ISSUE TITLE
[xgboost4j-spark] version 0.8+,  different with old version

### ISSUE THREAD

**Issue by wangzhilong** [dmlc/xgboost#3958]
In latest version 0.82, can't find some function, like `XGBoost`、`XGBoostModel`, etc.

Replace, it's  `XGBoostClassifier`、`XGBoostClassifierModel`、`XGBoostRegressor`、`XGBoostRegressorModel`。

I feel more convenient with old Interface.

**Comment by CodingCat** [comment]
You can still use 0.72...
