### ISSUE TITLE
Xgboost-spark unstable

### ISSUE THREAD

**Issue by xuchaoqun** [dmlc/xgboost#3959]
we use version 0.80, ‘XGBoostClassifier’ to train, ‘auc’ to evaluate, but if set ‘numWorkers’ > 1, the auc result is unstable(test several times with same params, the ‘auc’ result may be different, and not awalys different). if set ‘numWorkers’ = 1 and same params, the ‘auc’ result always same. I don't know why.

**Comment by CodingCat** [comment]
Read XGBoost KDD paper, it’s because of the approximate algorithm in distributed setting

**Comment by xuchaoqun** [comment]
> Read XGBoost KDD paper, it’s because of the approximate algorithm in distributed setting

Thanks, but how can we set params to get a stable 'auc' result when use distribute train?
