### ISSUE TITLE
linear test doesn't really use GPU

### ISSUE THREAD

**Issue by pseudotensor** [dmlc/xgboost#3961]
https://github.com/dmlc/xgboost/blob/master/tests/python-gpu/test_gpu_linear.py#L19

This sets the updater to coord_descent, and I notice when doing tests on bigger data that the GPU has memory allocated but usage is very low during the test.  However, if I set updater to gpu_coord_descent, then the GPU memory is allocated *and* the usage is at least 30% or so for the otherwise identical run.

@RAMitchell

**Comment by trivialfis** [comment]
@pseudotensor You are right, will make a fix.
