### ISSUE TITLE
xgboost4j-spark inconsistency in maxBin/maxBins param name

### ISSUE THREAD

**Issue by kevinykuo** [dmlc/xgboost#3962]
Should the param name here really be `maxBins`?

https://github.com/dmlc/xgboost/blob/b53a5a262c74987d85c54fd3d41bc6d28e5e1d60/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/BoosterParams.scala#L158-L159

**Comment by CodingCat** [comment]
no, we need to respect xgboost native layer (https://xgboost.readthedocs.io/en/latest/parameter.html) to make a correct conversion between underscore-style and camel case
