### ISSUE TITLE
CRAN check warnings and notes for 0.71.2

### ISSUE THREAD

**Issue by hetong007** [dmlc/xgboost#3963]
Check results for all platforms can be viewed at: https://cran.r-project.org/web/checks/check_results_xgboost.html

The warning happens on both Fedora and Debian with gcc with the following information:

> checking whether package ‘xgboost’ can be installed ... [143s/124s] WARNING
> Found the following significant warnings:
>   ./dmlc-core/include/dmlc/./parameter.h:997:25: warning: catching polymorphic type ‘const class std::out_of_range’ by value [-Wcatch-value=]
>   ./dmlc-core/include/dmlc/./parameter.h:1022:25: warning: catching polymorphic type ‘const class std::out_of_range’ by value [-Wcatch-value=]
>   ./dmlc-core/include/dmlc/././parameter.h:997:25: warning: catching polymorphic type ‘const class std::out_of_range’ by value [-Wcatch-value=]
>   ./dmlc-core/include/dmlc/././parameter.h:1022:25: warning: catching polymorphic type ‘const class std::out_of_range’ by value [-Wcatch-value=]
> See https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-gcc/xgboost-00install.html for details.

The note exists on both Fedora and Debian with the following information:

> checking use of SHLIB_OPENMP_*FLAGS in Makefiles ... NOTE
>   src/Makevars.win: incorrect macro SHLIB_OPENMP_CFLAGS included in PKG_CXXFLAGS
>   src/Makevars.win: SHLIB_OPENMP_CFLAGS is included in PKG_LIBS but linking is by C++
> Use of these macros is discussed in sect 1.2.1.1 of ‘Writing R
> Extensions’. The macros for different languages may differ so the
> matching macro must be used in PKG_CXXFLAGS (etc) and match that used
> in PKG_LIBS (except for Fortran: see the manual).

Link to section 1.2.1.1 of 'Writing R Extensions': https://cran.r-project.org/doc/manuals/r-release/R-exts.html#OpenMP-support

Prof. Brian Ripley also emailed us about it:

> These packages use SHLIB_PTHREAD_FLAGS in src/Makevars{,.in} but it is 
> only documented for Windows.  If you expect to use pthreads on a 
> Unix-alike, include -pthread (see 'Writing R Extensions').
> 
> Please correct as soon as practicable.

**Comment by hcho3** [comment]
@hetong007 The dmlc-core warnings should have been fixed by dmlc/dmlc-core#412.

**Comment by hcho3** [comment]
Fixed by #3988
