### ISSUE TITLE
Parameter 'updater' inconsistent

### ISSUE THREAD

**Issue by xuchaoqun** [dmlc/xgboost#3966]
In doc https://xgboost.readthedocs.io/en/release_0.80/parameter.html, param 'updater'would be adjusted to grow_histmaker,prune, but in code,  updater only can be set as grow_colmaker,prune. why?
![image](https://user-images.githubusercontent.com/11348272/49488649-7ceace00-f882-11e8-8fb9-3e100af5a8fa.png)
![image](https://user-images.githubusercontent.com/11348272/49488701-b91e2e80-f882-11e8-9ec3-c5e1916ba3ba.png)

**Comment by hcho3** [comment]
@xuchaoqun This was fixed in version 0.81: https://github.com/dmlc/xgboost/blob/release_0.81/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/GeneralParams.scala#L227
