### ISSUE TITLE
updated filename from libdmlccore.a to libdmlc.a

### ISSUE THREAD

**Issue by wguanicedew** [dmlc/xgboost#3968]
when trying to compile xgboost 8.1 with cmake. I got this error below. 
In xgboost 8.1, it seems libdmlc.a is created, instead of libdmlccore.a in the old versions. But the install script is not changed, it's still using the old libdmlccore.a.

[ 95%] Built target objxgboost
Scanning dependencies of target runxgboost
[ 96%] Building CXX object CMakeFiles/runxgboost.dir/src/cli_main.cc.o
[ 98%] Linking CXX executable xgboost
[ 98%] Built target runxgboost
Scanning dependencies of target xgboost
[100%] Linking CXX shared library lib/libxgboost.so
[100%] Built target xgboost
[ 65%] Performing install step for 'XGBoost'
Error copying file (if different) from "dmlc-core/libdmlccore.a" to "/tmp/wguan/hgam-h023/build/CMakeFiles/XGBoostBuild/lib".
make[2]: *** [src/XGBoost-stamp/XGBoost-install] Error 1

[wguan@lxplus011 build]$ ls src/XGBoost/dmlc-core/libdmlc.a 
src/XGBoost/dmlc-core/libdmlc.a

**Comment by hcho3** [comment]
Which "install script" are you using? The official documentation recommends using CMake directly:
```
mkdir build
cd build
cmake ..
make
```

**Comment by trivialfis** [comment]
@wguanicedew Any updates?

**Comment by wguanicedew** [comment]
Hi,
I found the issue is on our code. I made it work.
Thanks. I will close this one.
