### ISSUE TITLE
How to use monotone constraints in ml.dmlc.xgboost4j.scala.spark.XGBoost?

### ISSUE THREAD

**Issue by cancermqiao** [dmlc/xgboost#3969]
Hi, all,
I have tried to pass it as a member of paramMap,like this:
```scala
val paramMap = List(
              "eta" -> 0.1,
              "max_depth" -> 2,
              "objective" -> "reg:linear",
              "monotone_constraints" -> "(1, -1)").toMap
 
val model_with_constrained = XGBoost.trainWithDataFrame(xgb_train, paramMap, round=1000, nWorkers=2)
```
But it doesn't work. My package version is 0.72. 
HELP,PLEASE!

**Comment by hcho3** [comment]
@CodingCat Does XGBoost4J-Spark support monotonic constraints?

**Comment by CodingCat** [comment]
no...`To use monotonic constraints, be sure to set the tree_method parameter to one of exact, hist, and gpu_hist.`....

**Comment by hcho3** [comment]
@CodingCat Got it. For now, I will add a sentence saying that XGBoost4J-Spark doesn't support monotonic constraints.
