### ISSUE TITLE
Can not install xgboost on Mac(OS X 10.10.4)

### ISSUE THREAD

**Issue by lenguyenthedat** [dmlc/xgboost#397]
I'm running OS X 10.10.4 with 

    $ gcc --version
    Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
    Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
    Target: x86_64-apple-darwin14.4.0
    Thread model: posix

When I run `make`, I received this error:

    $ make
    g++ -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -fopenmp -fPIC -fPIC -o xgboost updater.o gbm.o io.o main.o subtree/rabit/lib/librabit.a dmlc_simple.o -pthread -lm
    clang: warning: argument unused during compilation: '-pthread'
    ld: library not found for -lgomp
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make: *** [xgboost] Error 1

**Comment by lenguyenthedat** [comment]
I'm not sure if the above works for other system - only tested working on my mac.

**Comment by tqchen** [comment]
See https://github.com/dmlc/xgboost/blob/master/doc/build.md
