### ISSUE TITLE
Decision tree class refactor

### ISSUE THREAD

**Issue by RAMitchell** [dmlc/xgboost#3972]
I propose a refactor of the regression tree class with the following objectives in mind:

- Reduce code complexity. This class is very complicated and difficult to understand/use for new contributors.
- Increase safety. It is very easy to get a segfault with the current class. With good encapsulation and object-oriented programming I believe misuse can be entirely prevented.
- Use this class on the GPU. We currently have significant code duplication in GPU algorithms as we had to build our own data structures usable on the GPU.

To do this we can do it in two phases:
- First refactor to reduce redundancy and cleanup without affecting backwards compatibility
- Propose and evaluate any further changes needed affecting backwards compatibility, discuss how we can achieve this with minimal disruption to users. e.g. continuing support for the old format for a limited time

**Comment by hcho3** [comment]
@trivialfis RFC will be up in a day. Sorry for the delay. I have been arranging a move to California lately.

**Comment by hcho3** [comment]
@RAMitchell Can we close this issue, now that we merged #3989, #3995, #4008, #4015, and #3825 ?

**Comment by RAMitchell** [comment]
There is still a little more to do. My idea was to make all of the internal vectors inside the regression tree private so that we can only access it through safe public methods, preventing misuse of the class. All of the ground work is done I just need to spend a little time finishing it off.

**Comment by RAMitchell** [comment]
This was a little more complicated than I thought, I'm going to close this for now.
