### ISSUE TITLE
Suggestion on adding performance

### ISSUE THREAD

**Issue by tbs17** [dmlc/xgboost#3977]
Hi there,

Thanks for sharing the script. I'm also working on a 5-class classification. The performance i get is unlike the binary classification above 80%. it's more like 50-60%. How about yours? how do you judge the performance? what metrics do you use? Thank you!

**Comment by hcho3** [comment]
Did you mean to post it somewhere else?

**Comment by hcho3** [comment]
Closing for now

**Comment by tbs17** [comment]
Sorry for late responding! You can either post it in the same script or
start a new script. It would be great if you can also post about how to
turn parameters to get good performance. Thank you!

**Comment by trivialfis** [comment]
@tbs17 Hi, this thread is from XGBoost.  Are you sure you are replying in the correct thread?
