### ISSUE TITLE
xgboost using single GPU with error XGBoost must be compiled with NCCL to use more than one GPU

### ISSUE THREAD

**Issue by bastia1989** [dmlc/xgboost#3978]
System info:

Debian 4.9.130-2 (2018-10-27)

cuda compilation tools, release 10.0, V10.0.130

xgboost: 0.81

python: 3.5.3

The code example:

    gbm_param_grid = {'learning_rate': [.01, .05, .075, 0.1, 0.3, 0.5, 0.75, 1],
                      'n_estimators': np.arange(10, 160, 10),
                      'subsample': [0.5, 0.7, 0.9, 1],
                      'max_depth': [3, 4, 5, 6, 7, 8, 9, 10],
                      'min_child_weight': np.arange(0.1, 5, 0.1),
                      'gamma': [i/10.0 for i in range(0,5)]                  
                      }
     
    
    # 3 things: 1. extra parameters 2. weights on positives 3. new CVs
     
    gbm = xgb.XGBClassifier(objective='binary:logistic', tree_method='gpu_hist')
    skf = StratifiedKFold(n_splits=10, shuffle=True)
    X_test, y_test = X, y
    fit_dict = {"eval_set":[(X_test, y_test)],
              "early_stopping_rounds":5,
              "eval_metric":"logloss","verbose":5}
    
    grid_result = GridSearchCV(estimator=gbm, param_grid=gbm_param_grid, fit_params=fit_dict, scoring='roc_auc', cv=skf.split(X, y))
    grid_result.fit(X, y)
Error message:

    xgboost.core.XGBoostError: b'[06:06:57] /workspace/src/tree/updater_gpu_hist.cu:908: Exception in gpu_hist: [06:06:57] /workspace/src/tree/../common/device_helpers.cuh:854: Check failed: device_ordinals.size() == 1 (0 vs. 1) XGBoost must be compiled with NCCL to use more than one GPU.\n\nStack trace returned 10 entries:\n[bt] (0) 

I don't understand why xgboost supposes I am using multiple-gpu?

============================================================

The xgboost module is installed by `pip3 install xgboost`. From the document I suppose this is the correct way to install single-GPU supported version, right?

**Comment by trivialfis** [comment]
Let me look into this.

**Comment by trivialfis** [comment]
@bastia1989 
> Check failed: device_ordinals.size() == 1 (0 vs. 1)

It seems XGBoost couldn't find any GPU on your system, the 0 in `(0 vs. 1)` means there is 0 GPU found.  Could you try to verify your CUDA installation?

**Comment by trivialfis** [comment]
We have not yet test XGBoost against CUDA 10.0.  Will try to do that later.

**Comment by bastia1989** [comment]
> We have not yet test XGBoost against CUDA 10.0. Will try to do that later.

Thanks for the reply. Yes, I am using a gcloud instance created from the latest image so with the latest CUDA . The GPU device is K80.

**Comment by trivialfis** [comment]
@bastia1989 I'm afraid that you might have to wait for a while before I can get to this or you can try if CUDA 9.2 is possible.  I'm currently trying to tackle a mutli-gpu bug #3984 .  Until I get that done I don't want to upgrade to install CUDA 10 since making CUDA work for me is always been a tricky task.

**Comment by trivialfis** [comment]
@bastia1989 Compiled from source with CUDA-10 and passed the tests.  I guess there's something funny in CUDA's ABI.  Until we have CUDA-10 on test farm I think compiling from source is required.
