### ISSUE TITLE
if support input a data dir for training data and eval data

### ISSUE THREAD

**Issue by seven-xu** [dmlc/xgboost#3979]
Thanks for participating in the XGBoost community! We use https://discuss.xgboost.ai for any general usage questions and discussions. The issue tracker is used for actionable items such as feature proposals discussion, roadmaps, and bug tracking.  You are always welcomed to post on the forum first :)

Issues that are inactive for a period of time may get closed. We adopt this policy so that we won't lose track of actionable issues that may fall at the bottom of the pile. Feel free to reopen a new one if you feel there is an additional problem that needs attention when an old one gets closed.

For bug reports, to help the developer act on the issues, please include a description of your environment, preferably a minimum script to reproduce the problem.

For feature proposals, list clear, small actionable items so we can track the progress of the change.

**Comment by hcho3** [comment]
Yes, you can simply specify the full path of the directory containing multiple LIBSVM/CSV files.

**Comment by seven-xu** [comment]
if you mean i should use the jvm-package version, i use the shell dmlc_yarn.py now, can you give me a demo? thanks

**Comment by hcho3** [comment]
Wherever a file name is to be specified for data files, you can put in directories.

**Comment by seven-xu** [comment]
it works by use the directory directly， i got the error because of i use the /xxx/*， thank you for my help！
