### ISSUE TITLE
Instance weights for learning to rank

### ISSUE THREAD

**Issue by anuragreddygv323** [dmlc/xgboost#3981]
I am training a learning to rank model with label, group id, query id and features

my objective is to maximize rank:ndcg@10.

I want to give weights for each label while training in dataframe instead of Libsvvm format.

How can I give it ?

**Comment by hcho3** [comment]
You can specify a weight column using `setWeightCol ()`: https://github.com/dmlc/xgboost/blob/1c08b3b2eaf356a448c156271c394692dc698065/jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostRegressorSuite.scala#L118
