### ISSUE TITLE
Constraints in the features contribution calculation?

### ISSUE THREAD

**Issue by PaoloCordella** [dmlc/xgboost#3992]
Hi,

Is there a way to enforce constraints in the features contribution calculation resulting from predcontrib = TRUE in predict function? (for example to enforce some features to have positive contributions)

Please note I’m already using monotonicity constraints in the xgboost training.

Thanks

**Comment by hcho3** [comment]
I don’t think it is supported

**Comment by hcho3** [comment]
Current implementation of monotonicity constraints only ensures that the target variable is monotonic. No guarantee exists for feature contributions.
