### ISSUE TITLE
[jvm-packages] Upgrade spark to 2.4.0?

### ISSUE THREAD

**Issue by rongou** [dmlc/xgboost#3996]
Some of the features in Spark 2.4 might be useful for xgboost4j-spark (e.g. barrier mode). Can we upgrade the dependency to 2.4.0? I tried it with https://github.com/dmlc/xgboost/pull/3990 and everything seems to work, not sure if anything else is needed.

**Comment by CodingCat** [comment]
it looks like 2.4.1 would be available next month, let's resume this by upgrading to that version
