### ISSUE TITLE
Instance weighting in Python

### ISSUE THREAD

**Issue by mttk** [dmlc/xgboost#400]
Hi,

I'm using python & pandas/numpy with xgboost. 

I read the data with `pd.read_csv`, then convert it to a numpy array and pass the data to `xgb.DMatrix` and `xgb.train`. There is no change whether I put a train.csv.weight file or not (obviously, since I assumed that the source file data was lost in the process).

I can't find documentation on attaching instance weights other than with command line runs, is this possible from python? And how?

thanks!

**Comment by tqchen** [comment]
You can explicitly load data into numpy and construct the DMatrix with weight parameters. https://github.com/dmlc/xgboost/blob/master/wrapper/xgboost.py#L134

**Comment by mttk** [comment]
Perfect, thanks, missed that somehow.
