### ISSUE TITLE
xgboost 0.47 g

### ISSUE THREAD

**Issue by jake221** [dmlc/xgboost#4003]
![xgboost0 47 fi4 2](https://user-images.githubusercontent.com/18079288/50071365-7f4b1180-020c-11e9-9f2c-952c88c7b78d.PNG)

**Comment by jake221** [comment]
Hi, 
I was trying to import xgboost plugin into our products of our company. Considering the restrict of the glibc version of our environment, we import a very old version of xgboot 0.47. However, it still failed because the glibc of our environment is too low (gcc 2.11.3, suse linux). And I want to ask what is the minimal glibc version for xgboost 0.47. GLIBC 2.15 as described in the logs?

**Comment by hcho3** [comment]
0.47 version is very old, so you won't be able to get a good answer here. Consider statically linking a libc library. I heard good things about [musl](https://www.musl-libc.org/)

**Comment by CodingCat** [comment]
@jake221 you need at least 2.12 (which has been a very old version) . if you can get glibc 2.12, you can use the latest version (0.81)

@hcho3 good headshot!
