### ISSUE TITLE
Document load_rabit_checkpoint, save_rabit_checkpoint better

### ISSUE THREAD

**Issue by KOLANICH** [dmlc/xgboost#4007]
* [ ] add some words about what exactly it does and about use cases.
   <details>
   <summary>For example I wonder if it is suitable for crossvalidation:</summary>I may want to fit hyperparams for each tree separately and sequentially: fit hyperparams for the first tree, fit the first tree, freeze it, find hyperparams for the second tree above it, fit the second tree, freeze 2 first trees and start searching hyperparams for the third tree (have anyone tried it? does it work better than same hyperparams for all the trees?)... .
 </details>

* [ ] provide examples

**Comment by hcho3** [comment]
@KOLANICH These two methods are for serializing models in distributed learning. In the end, they all end up using the same code as `save_model()` / `load_model()` method.
