### ISSUE TITLE
slice method of xgboost.DMatrix will change feature_names.

### ISSUE THREAD

**Issue by lyhue1991** [dmlc/xgboost#4009]
I find when use the slice method of xgb.DMatrix , the output DMatrix will change feature_names.
This behaviour is very strange. I think it should be fixed.

```python
import numpy as np
import pandas as pd
import xgboost as xgb

data = pd.DataFrame(np.random.randn(5,3),columns = list('abc'))
dtrain = xgb.DMatrix(data)
dslice = dtrain.slice([0,1,2])
print(dtrain.feature_names)
print(dslice.feature_names)
```
the results is like this:

>[u'a', u'b', u'c']
>['f0', 'f1', 'f2']

**Comment by hcho3** [comment]
Which version of XGBoost are you using?

**Comment by lyhue1991** [comment]
@hcho3 
> Which version of XGBoost are you using?
0.80

**Comment by hcho3** [comment]
The bug has been already fixed. You should upgrade to version 0.81.
