### ISSUE TITLE
Multiclass prediction error 'XGCheckNullPtr_R'

### ISSUE THREAD

**Issue by Smikee** [dmlc/xgboost#401]
Hi, I'm using "objective" = "multi:softprob", currently testing on iris dataset. However, the training phase has not been successful with the error:
Error in .Call("XGCheckNullPtr_R", bst$handle, PACKAGE = "xgboost") : 
  "XGCheckNullPtr_R" not available for .Call() for package "xgboost"

It's curious that several minutes before (the R was restored due to instability, there was an error with num_class -- already fixed) everything went well.  At this stage, I had a problem with interpretation of results from prediction - only one value was returned for each observation. In addition, despite inserting only testing set into predict() function, predicted values were returned both for training and testing set. I'm using xgboost 0.4.-0. Moreover, 'mlogloss' evaluation metric is not working either.

Here is my code:

data <- iris
subsample <- sample(1:150,100) #training sample
test <- setdiff(1:150,subsample) #testing sample

data_num <- data
data_num$Species <- as.numeric(data_num$Species)-1
xgmat <- xgb.DMatrix(as.matrix(data_num[subsample,1:4]), label = (data_num[subsample,5]))

param <- list("booster" = 'gbtree',
              "objective" = "multi:softprob",
              "num_class" = 3,
              "silent" = 0,
              "eval_metric" = "merror", 
              "nthread" = 16,
              "eta" = 0.3,
              "gamma" = 0,
              "max_depth" = 6,
              "min_child_weight" = 10,
              "max_delta_step" = 0.1,
              "colsample_by_tree" = 1,
              "subsample" = 0.5,
              "silent" = 0)
watchlist <- list("train" = xgmat)
nround = 110
bst <- xgb.train(param, xgmat, nround, watchlist)

xgmat_testing <- xgb.DMatrix(as.matrix(data_num[test,1:4]), label = data_num$Species[test])
predicted <- predict(bst, xgmat_testing,outputmargin=TRUE)

Thanks for suggestions.
Michal

**Comment by tqchen** [comment]
Could be related to #390

**Comment by tqchen** [comment]
You can  try the solution listed at issue #390

**Comment by Smikee** [comment]
Thanks, I missed that thread in closed issues. In addition, I noticed that the predicted probabilites in testing phase are returned as a vector of concantenated posteriors for each class, thus my problem is solved :).
