### ISSUE TITLE
Infrequent feature causes a crash during distributed training

### ISSUE THREAD

**Issue by sshrdp** [dmlc/xgboost#4016]
Using XGBoost4J-Spark bindings, I'm trying to train a model with one-hot encoded categorical features. 
I think if one of the workers don't get any example with a particular feature it will cause a crash.
This is the error log:
Last 4096 bytes of stderr :
terminate called after throwing an instance of 'dmlc::Error'
  what():  [23:09:55] /xgboost/include/xgboost/../../src/common/span.h:402: Check failed: _count >= 0 

libxgboost4j4085242285937315775.so(dmlc::StackTrace()+0x19d) [0x7f4028681d6d]
libxgboost4j4085242285937315775.so(xgboost::common::Span<xgboost::Entry const, -1l>::Span(xgboost::Entry const*, long)+0x5f0) [0x7f40286caf00]
libxgboost4j4085242285937315775.so(+0x1e9793) [0x7f40287c8793]
libxgboost4j4085242285937315775.so(xgboost::tree::GlobalProposalHistMaker<xgboost::tree::GradStats>::CreateHist(std::vector<xgboost::detail::GradientPairInternal<float>, std::allocator<xgboost::detail::GradientPairInternal<float> > > const&, xgboost::DMatrix*, std::vector<unsigned int, std::allocator<unsigned int> > const&, xgboost::RegTree const&)+0x995) [0x7f40287d6925]
libxgboost4j4085242285937315775.so(xgboost::tree::HistMaker<xgboost::tree::GradStats>::Update(std::vector<xgboost::detail::GradientPairInternal<float>, std::allocator<xgboost::detail::GradientPairInternal<float> > > const&, xgboost::DMatrix*, xgboost::RegTree*)+0x2d9) [0x7f40287d8e79]
libxgboost4j4085242285937315775.so(xgboost::tree::HistMaker<xgboost::tree::GradStats>::Update(xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*, xgboost::DMatrix*, std::vector<xgboost::RegTree*, std::allocator<xgboost::RegTree*> > const&)+0xa3) [0x7f40287ca933]
libxgboost4j4085242285937315775.so(xgboost::gbm::GBTree::BoostNewTrees(xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*, xgboost::DMatrix*, int, std::vector<std::unique_ptr<xgboost::RegTree, std::default_delete<xgboost::RegTree> >, std::allocator<std::unique_ptr<xgboost::RegTree, std::default_delete<xgboost::RegTree> > > >*)+0x809) [0x7f40287055a9]
libxgboost4j4085242285937315775.so(xgboost::gbm::GBTree::DoBoost(xgboost::DMatrix*, xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*, xgboost::ObjFunction*)+0x885) [0x7f4028706035]
libxgboost4j4085242285937315775.so(xgboost::LearnerImpl::UpdateOneIter(int, xgboost::DMatrix*)+0x3e0) [0x7f4028713560]
libxgboost4j4085242285937315775.so(XGBoosterUpdateOneIter+0x35) [0x7f4028688185]

**Comment by CodingCat** [comment]
can anyone of you provide a small dataset which can reproduce the issue

**Comment by CodingCat** [comment]
https://github.com/dmlc/xgboost/pull/4045 should address this
