### ISSUE TITLE
GPU memory is not released after training with {'predictor':'cpu_predictor'}

### ISSUE THREAD

**Issue by vss888** [dmlc/xgboost#4018]
It seems reasonable to claim that there is no justifiable reason not to **release GPU memory after training if xgboost is used with `predictor='cpu_predictor'`** (please, correct me if I am wrong), and so I was wondering if you could, please, put it on the list of features to be implemented.

It would make the process of hyper-parameter optimization much more efficient since the bottle neck (at least in my use case) is the available GPU memory, and so if GPU memory is released after training, many more models could be trained/tested in parallel using the same GPU.

This is related to issues [3045](https://github.com/dmlc/xgboost/issues/3045) and [3083](https://github.com/dmlc/xgboost/issues/3083).

**Comment by trivialfis** [comment]
@vss888 This requires us to design and implement a global GPU memory management system inside XGBoost, which is never a trivial thing to do, especially when memory can be distributed across multiple GPUs.  Alternatively we add a `ReleaseMemory` method to every components inside XGBoost, which is definitely not preferred with such amount of boilerplate code.

The methods used in deep learning framework which has a distributable computation graph does not apply on tree boosting algorithms.  More thoughts are needed.

**Comment by trivialfis** [comment]
I tried to see how bad the situation is in master branch,  with a dataset of shape (200000, 3000), taking up 2GB GPU memory during training, but with only 159 MB left after deleting trained model (in Python `del model`).  Are you sure that your bottle net lies in memory usage?

**Comment by vss888** [comment]
@trivialfis Plus, I can not delete a model until all the predictions are finished, and so the GPU memory would remain allocated.

One possible solution would be to create a `def release_gpu_memory(self, model)` in python, which would simply create a new model with `predictor='cpu_predictor'` and then somehow enforce deletion of the old model.

**Comment by redpoint13** [comment]
has there been any progress or new options?

**Comment by jonimatix** [comment]
Yes this is a teething problem

**Comment by RAMitchell** [comment]
Lets continue this discussion in #4668. I think this needs to be a priority for us.

**Comment by seanthegreat7** [comment]
For those who look for a quick workaround till you fix it properly check [my solution here](https://stackoverflow.com/questions/56298728/how-do-i-free-all-memory-on-gpu-in-xgboost)
