### ISSUE TITLE
xgboost  AttributeError: 'module' object has no attribute 'DMatrix' on Mac

### ISSUE THREAD

**Issue by sh1ng** [dmlc/xgboost#403]
I've tried workarounds from https://github.com/dmlc/xgboost/issues/208

**Comment by jakubLangr** [comment]
Bump! I have the same issue. Mac Yosemite using dockerized versions from ipython/scipystack + custom install of XGB.

**Comment by sh1ng** [comment]
@jakubLangr  In my case(maverick) I had script name xgboost.py, renaming solved the issue.

**Comment by jakubLangr** [comment]
ah okay, you mean the `mv setup.py xgboost.py` or the script that I am running? I am using IPython so I wonder how would that work.

**Comment by sh1ng** [comment]
Second case, try to run pure 'hello xgboost' from a console first.

**Comment by jakubLangr** [comment]
Ah okay so that is a workaround, but the trouble is that in my set up that is not very practical. Indeed, the only way I could get this to run was very hacky and did not work.
`1. create xgboost.py` in the root file that 
2.
- imports xgboost
- this file calls a pythonized version of the notebook
But I still get the same error as before.

Any ideas?

**Comment by sh1ng** [comment]
rename your script from xgboost.py to xgboost_sample.py

**Comment by jakubLangr** [comment]
Still the same error. So why exactly do you think we are getting this error?

**Comment by sh1ng** [comment]
in my case it was a name conflict. I'm no good at python, so might be I have to do something when name of a running script and wrapper/module are equaled. 

Have you tried a workaround from original issue?

**Comment by jakubLangr** [comment]
Yes, I have. Now I have managed to solve the issue, but I am not sure how exactly as I have tried many things. In the end, renaming was not necessary. But I have tried playing around with the filepaths quite a bit. Working setup was:
- git pull in the project folder
- .ipynb run from top level of project folder

**Comment by nmooman** [comment]
Rename the file name! You might have named xgboost.py in the same dir!
