### ISSUE TITLE
Remove makefile from documentation.

### ISSUE THREAD

**Issue by trivialfis** [dmlc/xgboost#4031]
Currently the makefile are only preserved for CRAN build (correct me if I'm wrong).  So as long as the build is not CRAN related, we can omit those makefiles, and possibly the `build.sh` on top level source tree.  Can me at least drop those instructions from documentation?

**Comment by hcho3** [comment]
@trivialfis We should recommend the use of CMake whenever possible. To my knowledge, everything can be done in CMake, except for installing XGBoost from CRAN (the R packaging system).

**Comment by trivialfis** [comment]
@hcho3 Great,  I have been trying to rewrite the CMake scripts.  Will make a PR for comments soon.  Combined with new linter, we can strip the makefile into absolute minimum.

**Comment by hcho3** [comment]
Addressed by #4219
