### ISSUE TITLE
Move linter to Jenkins.

### ISSUE THREAD

**Issue by trivialfis** [dmlc/xgboost#4032]
Currently the linter is a good hack, but not reliable due to the fact that clang-tidy doesn't deal well with CUDA source code.  On Travis our linter script renames all cu files into cc files and perform clang-tidy checks, which leads to incorrect results, see the end of:

https://travis-ci.org/dmlc/xgboost/jobs/473251478

Now we have CUDA runtime on Jenkins thanks to @hcho3 , where we can use clang-tidy without such hack.  The correct clang-tidy results I generated is attached.

[log-tidy.txt](https://github.com/dmlc/xgboost/files/2716218/log-tidy.txt)

**Comment by trivialfis** [comment]
Regenerated with both host and device checking:
[log-tidy.txt](https://github.com/dmlc/xgboost/files/2716251/log-tidy.txt)

**Comment by trivialfis** [comment]
Requirement:
 - clang-tidy >= 7
 - A **huge** refactor of current code base.
 - Extra script on CMake to obtain the compile database.

@RAMitchell @hcho3 Do you think it's worthy?

**Comment by RAMitchell** [comment]
You dont have to refactor the lint errors all in one go. What if you set up the system on jenkins but allow it to pass even with errors, spend a couple of weeks fixing lint issues, then make it mandatory. 

I think this is very much worth doing.
