### ISSUE TITLE
[python-package] does objective = 'rank:ndcg' works fine in XGBRanker?

### ISSUE THREAD

**Issue by myotheone** [dmlc/xgboost#4039]
XGBRanker docstring says:
objective : string
            Specify the learning task and the corresponding learning objective.
            **Only "rank:pairwise" is supported currently.**
So does rank:ndcg works fine in XGBRanker?

**Comment by myotheone** [comment]
docstring need to be updated

**Comment by hcho3** [comment]
@myotheone @trivialfis Agreed that the docstring should be updated. I'll open a PR to fix it.
