### ISSUE TITLE
Silent error when passing incorrect configuration parameter name

### ISSUE THREAD

**Issue by DoanHuuJacques** [dmlc/xgboost#4043]
When calling Learner::Configure() with a list of key-value pairs, no exception is thrown if one of the key is incorrect/unknown
For instance, configuring with {'three_method': 'hist'} doesn't raise any exception and it's just ignored.

I don't know if such silent behavior is expected in case of unknown parameter

**Comment by trivialfis** [comment]
@DoanHuuJacques It's expected.  I plan to add some validations in the future, but before being there we need to go through some refactors first.

**Comment by DoanHuuJacques** [comment]
@trivialfis,
Hi, do you mean that you would add some parameter name check in the future (after the refactoring you mentioned)? Is it correct?
thanks

Jacques

**Comment by trivialfis** [comment]
@DoanHuuJacques Yes.  Hopefully after #3980 and #3984 .

**Comment by DoanHuuJacques** [comment]
@trivialfis,
cool
Thanks
Jacques
