### ISSUE TITLE
colsample_bytree does not take full effect in fast-histo

### ISSUE THREAD

**Issue by CodingCat** [dmlc/xgboost#4047]
I am investigating performance issue in distributed fast histogram #4011 when we set colsample_bytree, I found that in fast histogram algorithm, we still initialize data with full set of columns even with the parameter set

check https://github.com/dmlc/xgboost/blob/master/src/common/hist_util.cc#L37-L58, we are iterate over batch's index that means everything

but in approx, we traverse over all features in work_set https://github.com/dmlc/xgboost/blob/master/src/common/hist_util.cc#L37-L58, and this work_set is the sampled column set produced in 

https://github.com/dmlc/xgboost/blob/master/src/common/hist_util.cc#L37-L58

https://github.com/dmlc/xgboost/blob/master/src/tree/updater_histmaker.cc#L130 (workset is essentially a copy of fwork_set in this line, see https://github.com/dmlc/xgboost/blob/master/src/tree/updater_histmaker.cc#L130)

@RAMitchell @hcho3 @trivialfis  need more eyes on this before I take action on it

**Comment by trivialfis** [comment]
@CodingCat A little bit occupied these few weeks.  Can this wait?

**Comment by CodingCat** [comment]
@trivialfis I can go ahead to file a PR and we can discuss there?

**Comment by trivialfis** [comment]
Great!

**Comment by CodingCat** [comment]
check https://github.com/dmlc/xgboost/issues/4077
