### ISSUE TITLE
[jvm-packages] Fix early stopping with xgboost4j-spark

### ISSUE THREAD

**Issue by mingyang** [dmlc/xgboost#4050]
In the `python-package`(see [here](https://github.com/dmlc/xgboost/blob/master/python-package/xgboost/callback.py#L246)), training stops if the current iteration is `earlyStoppingSteps` away from the *best iteration*. 

Current spark implementation ([here](https://github.com/dmlc/xgboost/blob/c055a3260988b63d61dbec088e8f8d6af2d34e9c/jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/XGBoost.java#L231)) looks for *any* two consecutive steps that move in the "right" direction, regardless of whether global optimum has been reach.

Should the spark version be consistent with the python implementation?

**Comment by yanboliang** [comment]
I think @mingyang has a good point here, the XGBoost ```python-package``` behavior is consistent with [scikit-learn] (https://scikit-learn.org/stable/auto_examples/ensemble/plot_gradient_boosting_early_stopping.html). Let me give a fix. Thanks.

**Comment by mingyang** [comment]
@yanboliang Any updates on this issue?

**Comment by yanboliang** [comment]
@mingyang I just sent out #4176 , please feel free to comment there.
