### ISSUE TITLE
Creation of Large DMatrix is taking time. Any Optimizations?

### ISSUE THREAD

**Issue by thehellmaker** [dmlc/xgboost#4051]
Hi All,
I creating a DMatrix of size (1, 50000). It is taking approximately about 18ms to do this. I have a strict requirement of keeping this to <3ms. I need to respond back in realtime from a http server and DMatrix creation itself is taking 18ms.

I have evaluated the following options
1. Instead of a numpy array use Scipy.sparse. But since the sparse matrix bloats it to a dense matrix it didn't make a difference in time.
2. Precreate a Pool of DMatrix of size (1,50000) and replace the elements on request for specific elements that way i dnt have to create the matrix for every request. But DMatrix doesn't have data manipulation options for optimization reasons. 

Are there any ways to speed this up without have to re-engineer the features?

**Comment by trivialfis** [comment]
I'm afraid there's not much you can do without modifying the source code.  But if you do want to optimize it I would be happy to help. :)

**Comment by thehellmaker** [comment]
Would love to take it up. But before that we evaluated XGBoost4J in a JVM rather than Python and that seems to be working in < 2ms. DMatrix creation isn't taking time. Is this just JVM being more efficient than python vm? or is there more to it?

**Comment by trivialfis** [comment]
Previously I did some testing.  Converting from other data type to numpy.float32 (used by XGBoost) takes up a huge portion of creation time.  Have you checked your input data type?

**Comment by trivialfis** [comment]
@thehellmaker Any update?
