### ISSUE TITLE
[feature proposal] Load best model after early stopping

### ISSUE THREAD

**Issue by PhilipMay** [dmlc/xgboost#4052]
Could you please implement a way to load the best model after ealy stopping? LightGBM is also doing this by default. See here: https://lightgbm.readthedocs.io/en/latest/Python-Intro.html#early-stopping

That would be a great improvement to my hyperparameter optimization workflow.

Thanks
Philip

**Comment by trivialfis** [comment]
Seems to be a nice feature.  Will look into this in the future.  @hcho3 WDYT?

**Comment by hcho3** [comment]
@trivialfis @PhilipMay Can you clarify what you mean? Currently, the scikit-learn interface automatically uses the best iteration when predicting:

https://github.com/dmlc/xgboost/blob/1fc37e47497239a7bc52e0e9949004c891fe36b6/python-package/xgboost/sklearn.py#L419-L421

**Comment by PhilipMay** [comment]
@hcho3 This is very interesting. So with the scikit-learn interface it should work the way I would like it to work (load or use best model). But what about the situation where you use the Booster class and do not use the scikit-learn interface? In the Booster class it just says:

> Limit number of trees in the prediction; defaults to 0 (use all trees).

See here: https://github.com/dmlc/xgboost/blob/1fc37e47497239a7bc52e0e9949004c891fe36b6/python-package/xgboost/core.py#L1190

For me this means that it does not use the best model from early stopping.

**Comment by hcho3** [comment]
Yes, it appears that currently you need to use the scikit-learn interface to do what you want. (And use `pickle` to save `XGBClassifier` / `XGBRegressor` objects.) It would be nice to add `num_iteration` option to `save_model()` function so that you can truncate the model at the time of serializing.

**Comment by PhilipMay** [comment]
> Yes, it appears that currently you need to use the scikit-learn interface to do what you want. (And use `pickle` to save `XGBClassifier` / `XGBRegressor` objects.) It would be nice to add `num_iteration` option to `save_model()` function so that you can truncate the model at the time of serializing.

Yes - and it would be nice to bring scikit-learn interface and the Booster interface to a consistent state where they both bring the best results form early stopping by default.

**Comment by hcho3** [comment]
The issue is that only the scikit-learn interface saves the best number of round; the Booster object does not save it. As I said, it would be cleaner to simply truncate the model at the time of serializing (`save_model()`) to achieve consistency.
