### ISSUE TITLE
Watchlist results extraction

### ISSUE THREAD

**Issue by orenov** [dmlc/xgboost#406]
So basically I've constructed quite complex cv approach using different subsets of my data. I need to evaluate my results on all this data to understand how my model performs on different subsets, For this task I'm using watch list option in xgb.train. 
But one annoying thing that I can't figure how to extract watch list results from xgb.train to do auto tuning based on this results and feed best model in to the next process. In general I need to use dominating strategy for choosing right model. I just need only best params and scores...

So I'm interested is such option exist in xgboost package? I've tried xgb.cv, but it's not the right thing I need, and no watchlist argument. Usual fold-approach is not for me.

Thank you.

**Comment by hetong007** [comment]
Hi, thanks for the suggestion. We currently don't have it in `xgb.cv` yet. 

If you're using the R pacakge, one possible workaround is to use the `sink` function in R, so that you can save the output to a local file, then read them in R again after the training process.
