### ISSUE TITLE
Prediction output different when outputmargin is used

### ISSUE THREAD

**Issue by brebbles** [dmlc/xgboost#4061]
I have run a tree-based model using `binary:logistic` running `V0.81.0.1` and am arriving at different slightly different probabilities depending on my prediction parameters.

I suspect this may be due to rounding somewhere in background and suspect it is probably a known issue, but my issue is that I arrive at slightly different numbers when I use `outputmargin = FALSE` compared to when I use `outputmargin = TRUE` and then convert via the logistic function

**Outputting the probability directly**
```
> print(predict(xgbModel, as.matrix(xgbData), outputmargin = FALSE), digits = 20) 
 [1] 0.11935223639011383
``` 
**Outputting the margin before conversion**
```
> print(predict(xgbModel, as.matrix(xgbData), outputmargin = TRUE), digits = 20) 
[1] -1.99857854843139648
```
When this number is converted via the logistic function I get a probability of `0.11935224612` - so the difference occurs at 8 digits in.  Is this a known issue that is possibly to rectify or is it just something that might only be happening on my end?

**Comment by hcho3** [comment]
XGBoost uses 32-bit floating point type, so only the first 8 decimal digits are accurate.
