### ISSUE TITLE
Why XGBoost4J-Spark 0.8+ can't support discol

### ISSUE THREAD

**Issue by Liuhaoge** [dmlc/xgboost#4062]
In a distributed setting, the implicit updater sequence value can only be adjusted to grow_histmaker,prune.  But why can't adjust updater to discol, it has no problem theoretically.

**Comment by hcho3** [comment]
Distcol updater has not been tested with Spark, so it is not enabled. Besides, it is suspected that distcol is broken (#1832). We’ll probably deprecate and remove this feature soon.
