### ISSUE TITLE
Feature importance should be supported for DART booster

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#4065]
As reported in https://discuss.xgboost.ai/t/feature-importance-not-support-for-booster-type-dart/605, currently feature importance function rejects DART models. This should be rectified.

**Comment by RAMitchell** [comment]
The best way to achieve this IMO is to merge the dart booster and gbtree booster. This will affect backwards compatibility.

**Comment by hcho3** [comment]
@RAMitchell The issue is that I disabled feature importance for GBLinear (see #3747), but in the process I accidentally disabled it for DART as well. In particular, this snippet is wrong:

https://github.com/dmlc/xgboost/blob/1fc37e47497239a7bc52e0e9949004c891fe36b6/python-package/xgboost/core.py#L1452-L1454

For now, we could add the check `self.booster != 'dart'`.

**Comment by hcho3** [comment]
@trivialfis Thanks!

**Comment by NaderNazemi** [comment]
Has this been resolved ?
I am still getting an error. 
Thank you

**Comment by hcho3** [comment]
@NaderNazemi Yes, it is resolved. If you are experiencing an error, please file a new issue.
