### ISSUE TITLE
[jvm-package] How to use early-stop

### ISSUE THREAD

**Issue by zhujuan0528** [dmlc/xgboost#4067]
I can see there's a method with early-stop as a parameter
```
public static Booster train(
          DMatrix dtrain,
          Map<String, Object> params,
          int round,
          Map<String, DMatrix> watches,
          float[][] metrics,
          IObjective obj,
          IEvaluation eval,
          int earlyStoppingRound)
```
but whatever i set the earlystoppinground, the console print "early stopping after * ascending rounds"
It might because I didn't set metrics.
this is my parameters:
```
HashMap<String, Object> params = new HashMap<String, Object>();
params.put("eta", 0.01);
params.put("max_depth", 7);
params.put("silent", 1);
params.put("gamma", 0.2);
params.put("eval_metric", "auc");
params.put("objective", "binary:logistic");

HashMap<String, DMatrix> watches = new HashMap<String, DMatrix>();
watches.put("train", trainMat);
watches.put("test", testMat);
round = 1150;
XGBoost.train(trainMat, params, round, watches, null, null, null ,20);

```
So how can I set the parameters to make the training early-stop?
My English is limited so forgive about my grammar

**Comment by hcho3** [comment]
@zhujuan0528 Which version of XGBoost are you using? Make sure you are using version 0.81, since there was a bug in early stopping in older versions (see #3808).

**Comment by CodingCat** [comment]
check https://xgboost.readthedocs.io/en/latest/jvm/xgboost4j_spark_tutorial.html#early-stopping

**Comment by sihao007** [comment]
I use 0.81 and get the same problem,run just 1 round and break,who can show a demo code

**Comment by hcho3** [comment]
@sihao007 The 0.82 release should fix early stopping in XGBoost4J-Spark: https://github.com/dmlc/xgboost/releases/tag/v0.82
