### ISSUE TITLE
How does xgb or lgb takes care of categorical values that are unseen in train, please help to understand or refer any link.

### ISSUE THREAD

**Issue by suresh-chinta** [dmlc/xgboost#4068]
Thanks for participating in the XGBoost community! We use https://discuss.xgboost.ai for any general usage questions and discussions. The issue tracker is used for actionable items such as feature proposals discussion, roadmaps, and bug tracking.  You are always welcomed to post on the forum first :)

Issues that are inactive for a period of time may get closed. We adopt this policy so that we won't lose track of actionable issues that may fall at the bottom of the pile. Feel free to reopen a new one if you feel there is an additional problem that needs attention when an old one gets closed.

For bug reports, to help the developer act on the issues, please include a description of your environment, preferably a minimum script to reproduce the problem.

For feature proposals, list clear, small actionable items so we can track the progress of the change.

**Comment by trivialfis** [comment]
Nothing fancy.  Everything here is converted into numerical values.

**Comment by suresh-chinta** [comment]
Thank you, if I label encode categorical, then, if the numeric label value in test is greater and unseen during training, while predicting, how the predict function going to interpret it. If there was no rule identified during training for this numeric value being less than or greater than. Thank you

**Comment by trivialfis** [comment]
I don't know how to explain ...  If you use the `tree model` then everything is based on plain old decision trees,  XGBoost just use gradient info to stack many of them together.

There's an introduction to decision tree, which might help a little:
https://xgboost.readthedocs.io/en/latest/tutorials/model.html

**Comment by hcho3** [comment]
@suresh-chinta Currently XGBoost does not let you use categorical values that were unseen at training time. The reason is that categorical values have to be [one-hot encoded](https://hackernoon.com/what-is-one-hot-encoding-why-and-when-do-you-have-to-use-it-e3c6186d008f), so you get K binary variables to represent K possible categorical values.
