### ISSUE TITLE
Model Serialization and Endianness

### ISSUE THREAD

**Issue by DoanHuuJacques** [dmlc/xgboost#4072]
I run XGBoost dans save the model on Big Endian platform (eg: SUSE/PPC64 Big Endian).
This native serialisation cannot be reloaded on Little Endian platforms (eg: Win64/Linux64 on Intel).
Indeed, when looking at how XGBoost saves the model via Learner::Save() method, the internal C structures are serialized as is with endianness awareness by using helper function from serializer.h
I expect to have a neutral model binary format regardless of the running platform/chipset.

Would you confirm that issue?
Thanks

**Comment by trivialfis** [comment]
@DoanHuuJacques We expect solving it by #3980 .  But not much progress has been made so far.  See https://github.com/hcho3/xgboost-json-schema/pull/5

**Comment by DoanHuuJacques** [comment]
@trivialfis 
JSON format is actually a better/substainable option than raw binary format. Would you confirm that the current serialisation is not endianness aware?
Thanks

**Comment by trivialfis** [comment]
@DoanHuuJacques It's **not** endianness aware.  @hcho3 received similar report before I think. :)

**Comment by DoanHuuJacques** [comment]
@trivialfis , @hcho3 
Hi,
Is there an ETA for the JSON serialisation support?
Is backward compatibility of current binary format supported? typically, can a runtime 0.81 load a serialized model 0.72?
Thanks

**Comment by trivialfis** [comment]
> Is there an ETA for the JSON serialisation support?

Not yet.

> Is backward compatibility of current binary format supported?

Yes.  Binary format should linger around.

**Comment by trivialfis** [comment]
I believe the endianness issue is resolved in dmlc-core.

**Comment by DoanHuuJacques** [comment]
@trivialfis 
would you mind elaborating a bit on how the endianness has been resolved in dmlc-core? Do you have a pull request related to this fix
Thanks

**Comment by hcho3** [comment]
@trivialfis Can you point me to a relevant pull request?

@DoanHuuJacques @trivialfis submitted a series of pull requests recently to implement JSON serialization. I believe this will solve the problem with endianness.

**Comment by DoanHuuJacques** [comment]
thanks @hcho3 for the information
I'm aware that @trivialfis  is working on JSON serialization and it seems that this feature is still under development (not yet merged)

**Comment by trivialfis** [comment]
@hcho3 https://github.com/dmlc/dmlc-core/pull/406 https://github.com/dmlc/xgboost/issues/3916#issuecomment-443111346

**Comment by trivialfis** [comment]
The JSON format is still experimental until floating point printing/parsing with rigorous roundtip tests  in #5046 is merged.

**Comment by hcho3** [comment]
@trivialfis dmlc/dmlc-core#406 only fixes serialization of standard STL containers. It does not fix https://github.com/dmlc/xgboost/blob/2fdb34ed2ea5fbe4d690332d4658cc34260c0edc/src/learner.cc#L504

**Comment by trivialfis** [comment]
@hcho3 Yup.  Updated the above comment.  Sorry for the noise here.

**Comment by hcho3** [comment]
@trivialfis I will review JSON pull requests so that we can finally make serialization endian-independent.

**Comment by trivialfis** [comment]
@hcho3 Thanks for providing so many help here.  We can finally have a working pipeline.

**Comment by trivialfis** [comment]
JSON is merged as experimental feature.
