### ISSUE TITLE
Issues with the Feature Interaction Constraints

### ISSUE THREAD

**Issue by kgoyal40** [dmlc/xgboost#4075]
I've been running some experiments with the feature interaction constraints and ran into something odd. If the 'interaction_constraints' parameter is passed as a blank list [ ], the performance of the model drops compared to a model without this parameter (keeping everything else the same). Why is the model changing based on a blank list?

Happy to provide more details.

Thanks

**Comment by khotilov** [comment]
An empty interaction_constraints list means "no features are allowed to interact with any other". That forces building univariate trees, which may lead to worse performance.

**Comment by kgoyal40** [comment]
Hey Thanks for the comment. I have a follow up question:
Let say I have 6 features (1,2,3,4,5,6) and pass on the interaction parameter as [[1,2,3]], does it mean that 1,2,3 will only interact with each other and 4,5,6 are not allowed to interact with any other?

**Comment by hcho3** [comment]
@kgoyal40 Yes, that is correct.

Let **S** the set of features used in all the ancestor nodes of the proposed split (plus itself). The proposed split is admitted whenever at least one set in the interaction constraint is a superset of **S**. Since `{4,5,6}` is not a subset of `{1,2,3}`, features 4, 5, 6 in your example won't be able to interact with each other. In addition, you cannot ever use features 4, 5, 6, since they don't appear anywhere in the constraints `[[1,2,3]]`.

**Comment by kgoyal40** [comment]
Hey, Thanks for the reply. I have another query. What happens when you give two sets with one (or more) common feature(s)? My results show that the performance is worse compared to one feature set at a time.

**Comment by hcho3** [comment]
See https://discuss.xgboost.ai/t/feature-interaction-constraint-overlap/506/2?u=hcho3

**Comment by kgoyal40** [comment]
@hcho3 Thanks but that doesn't answer my question? I want to understand how common features are utilized in the algorithm.

**Comment by hcho3** [comment]
@kgoyal40 The linked post discusses the scenario where two constraint sets share common features, e.g. ``[[0, 1, 2, 3], [1, 2, 3, 4]]``.

**Comment by rahul-c1** [comment]
Thanks for explaining this. I am using the xgboost library in R (version 0.81.0.1 from CRAN) and trying to understand the functionality by reconciling the example provided under the demo files [https://github.com/dmlc/xgboost/blob/master/R-package/demo/interaction_constraints.R](interaction_constraints.R) to the description mentioned in [https://xgboost.readthedocs.io/en/latest/tutorials/feature_interaction_constraint.html](interaction_constraints) . I am observing that number of interaction terms remain the same as opposed to what is mentioned in the demo comments. On similar lines, even though the constraints are provided as list(c('V1','V2'),c('V3','V4','V5')), looking at the output of xgb.model.dt.tree, it doesn't appear that the constraints are being enforced. Based on the feature description, I assumed the constraint(c('V1','V2')) indicates that variables V1 and V2 are allowed to interact with each other but with no other variable. However, looking at the output of xgb.model.dt.tree, I see interactions of V1 and V2 with other variables. Could I be misunderstanding how this constraint is enforced?

**Comment by hcho3** [comment]
@rahul-c1 

>  looking at the output of xgb.model.dt.tree, I see interactions of V1 and V2 with other variables.

Can you be more specific? How did you tell that there are interactions?

**Comment by rahul-c1** [comment]
yes, I am just running the example https://github.com/dmlc/xgboost/blob/master/R-package/demo/interaction_constraints.R as is without making any changes. 
Constraints are provided in the script and a comment in the file highlights that without interaction constraints we get many more interaction terms but I don't see a difference in the number of interaction terms being returned by the function defined in the file (with vs without interaction_constraints parameter) 

 `# Fit model without interaction constraints`

`bst2 = xgboost(data = train, label = y, max_depth = 4,
               eta = 0.1, nthread = 2, nrounds = 1000)`
...
..

`bst2_tree <- xgb.model.dt.tree(colnames(train), bst2)`
`bst2_interactions <- treeInteractions(bst2_tree, 4)  _Comment: much more interactions_`

**Comment by hcho3** [comment]
@rahul-c1 I just tried running the `interaction_constraints.R` example with XGBoost (0.81.0.1) and could not reproduce the issue. Here are the outputs I got:

`bst_interactions`:
```
[[1]]
[1] "V3" "V5"

[[2]]
[1] "V3" "V4"

[[3]]
[1] "V1" "V2"

[[4]]
[1] "V4" "V5"

[[5]]
[1] "V3" "V4" "V5"
```

`bst2_interactions`:
[bst2.txt](https://github.com/dmlc/xgboost/files/2854605/bst2.txt)

**Comment by kgoyal40** [comment]
I notice another issue. The fitting run time without feature interaction constraints is less than with feature interaction constraints, for most cases. This seems counter-intuitive as feature interaction constraints would result in less comparisons (and splits).  Am I missing something?

Thanks

**Comment by hcho3** [comment]
@kgoyal40 Enforcing interaction constraints require extra bookkeeping, to ensure that splits don’t choose wrong features. Hence the extra run time.

**Comment by pford221** [comment]
Hi @hcho3. Just a quick follow-up thought about the performance. I understand the overhead of having to keep track of things, but as soon as the first split is made for a particular tree, wouldn't this reduce the candidate features from which the algorithm tests to find the next best split? For instance, if the interaction constraints were defined as `[[0, 1, 2], [3,4,5]]` and a tree splits on feature index 1, then future splits for that tree can only be made on feature index 0, 1, or 2. So wouldn't that actually speed up the search algorithm?

**Comment by hcho3** [comment]
@pford221 Interesting point. The current implementation does not take advantage of feature interaction constraints when choosing features to enumerate. Would you be interested in filing a pull request?

**Comment by pford221** [comment]
@hcho3 As much I'd like to help, I reviewed the commit associated with interaction features and noticed that it requires quite a bit of C++ code and I would be out of my element there. I could handle any upstream changes in R or Python but just don't have any experience with C.

**Comment by hcho3** [comment]
@pford221 I opened #4217 to keep track of the proposed change. Thanks!

**Comment by hcho3** [comment]
@kgoyal40 @pford221 In pull request #4341, XGBoost now uses feature interaction constraints to preemptively narrow the search space for split candidates.

**Comment by pford221** [comment]
Awesome work @sperlingxx and @hcho3! Thanks so much.

**Comment by hcho3** [comment]
@pford221 No problem. Why don't you try it out and see if you get any performance improvement.

**Comment by kgoyal40** [comment]
Thanks !!

**Comment by kgoyal40** [comment]
Hey, I want to raise another issue. I've been running some experiment on XGBoost which uses feature interaction constraints. I use a dataset which has 9 features and a binary target. with feature interaction constraint of [[0, 5, 8], [3, 1, 6], [7, 4, 2]], I do a cross validation using following parameters

max_depth = [4,6,8], n_estimators = np.arange(10, 120, 5), eta = 0.1, verbosity = 1, eval_metric = 'rmse', tree_method = 'hist'.

I assumed that since my maximum size of a subsist of interaction list is 3, the max depth of any of trees shouldn't exceed this value. But, through cross validation the parameters which are being selected are:

'eta': 0.1, 'eval_metric': 'logloss', 'interaction_constraints': [[0, 5, 8], [3, 1, 6], [7, 4, 2]], 'max_depth': 8, 'n_estimators': 10, 'objective': 'binary:logistic', 'tree_method': 'hist', 'verbosity': 1}

How can we have trees with depth 8 when our interaction only allows a maximum depth of 3? Am I missing something?

**Comment by hcho3** [comment]
Most likely, the 3 features were used multiple times to fit depth-8 trees.
