### ISSUE TITLE
[jvm-packages] Train XGBoost in Spark, cpu usage is too low

### ISSUE THREAD

**Issue by linetor** [dmlc/xgboost#4081]
Spark version: 2.3.2
yarn cluster

data number : 2,591,753
feature : 100

XGBoost param:
"max_depth" -> 15,
"objective" -> "binary:logistic",
"num_round" -> 450,
"numClass" -> 60

I use EMR(Spark 2.3.2) and xgboost 0.8.1 in AWS. I wonder why cpu consumption is too low. Is it proper situation?

First, I used 8 instance by using r4.8xlarge. I thought it took too long time for training.
So I checked AWS instance's status. And each node's cpu average usage was below 10%(about 6%)
First part is CPU usage
![2019-01-23 1 46 21](https://user-images.githubusercontent.com/10512442/51729489-462d7900-20b7-11e9-8439-c0482f3e7507.png)

In this time, executor's status is below

Num-executors: 8(node number) * 11(executor number at one node) - 1(for drive) : 87
Executor-core : 3
spark.task.cpus : 3
Executor-memory : 6g
Executor-memory-overhead  : 12g

Second, at same node, I change options for executor(large executor: small number of executor). And cpu usage is increased(About 36%)

Num-executors: 8(node number) * 2(executor number at one node) : 16
Executor-core : 16
spark.task.cpus : 16
Executor-memory : 35g
Executor-memory-overhead  : 65g

Is it proper situation? I somtimes see spark use 80 ~ 90 % cpu usage for data handling. Comparing to it, xgboost cpu usage seems to be low. Is there any tunning point for more cpu usage?

And Is it proper memory setting that Executor-memory-overhead= Executor-memory * 2 ?

Thanks

**Comment by thvasilo** [comment]
I see that r4.8xlarge has 32vCPUs. So if you only run 11 executors at one node I wouldn't expect large utilization. When you increase the number of CPU used in your second example it's expected that you get higher utilization.

Let me recommend again that for a problem of this size you should be using the local fast_hist version of the algorithm, using a cluster is overkill. I assume this is a production use-case but you might want to give it a try.

Also be aware of [GBT's limitations](https://github.com/dmlc/xgboost/issues/4079) when it comes to having many classes in your data.

**Comment by CodingCat** [comment]
2,591,753 can be handled by 1 - 2 nodes...cpu utilization is limited because of the communication overhead among workers.....

**Comment by linetor** [comment]
Thanks for all response.

@thvasilo What is the  local fast_hist version? I googled that word. But didn't show. Is it benchmark for xgboost?

@CodingCat Yes. It is too small data for current cluster. And this is my current situation.
Total data is about 150,000,000 and have 10 categories . And it's all text data. 
Before xgboost training , I run LDA model for extracting feature(100 dimension) . And each category need to be divided  to under 100 labels(One category has about 800~900 labels)  because spark of limitation classification model's labels  is under 100 labels.
So one model's data is over 50,000,000 for 100 labels  and other model(current model) is 2,591,753 for 60 labels. And I want to run this process on one cluster. So my cluster is a little big.

 So I wonder why small data'(2,591,753)s training time need to long. So I guess it's reason seems to be cpu usage. In data processing of spark data processing(like join  or filter), I find cpu usage is about 70~80%,. 
And when I use not distributing xgboost library, cpu usage is high.

So I want to know  tips of how to use more cpu usage when I use spark-xbgoost

Thanks

**Comment by thvasilo** [comment]
Fast hist is one of the tree growing methods available. For now it's only available for the non-distributed version, but it's being worked on for distributed mode.

Quoting the [docs](https://xgboost.readthedocs.io/en/latest/parameter.html#parameters-for-tree-booster):

```
tree_method string [default= auto]

    The tree construction algorithm used in XGBoost. See description in the reference paper.
    Distributed and external memory version only support tree_method=approx.
    Choices: auto, exact, approx, hist, gpu_exact, gpu_hist
        auto: Use heuristic to choose the fastest method.
            For small to medium dataset, exact greedy (exact) will be used.
            For very large dataset, approximate algorithm (approx) will be chosen.
            Because old behavior is always use exact greedy in single machine, user will get a message when approximate algorithm is chosen to notify this choice.
        exact: Exact greedy algorithm.
        approx: Approximate greedy algorithm using quantile sketch and gradient histogram.
        hist: Fast histogram optimized approximate greedy algorithm. It uses some performance improvements such as bins caching.
        gpu_exact: GPU implementation of exact algorithm.
        gpu_hist: GPU implementation of hist algorithm.


```

**Comment by CodingCat** [comment]
@linetor cpu utilization is low because your cpu is hanging for i/o (xgboost is syncing stats of each workers), 

when you have small chunks of data to process, cpu doesn't spend much time on calculating a tree, but there is still the overhead for establishing connections, waiting for parent and children to sync data (as the communication topology in xgboost is a binary tree). When you have more workers, the tree is higher, the overhead is increasing and the ratio of cpu time/ io time is lower...

**Comment by CodingCat** [comment]
@linetor you just use less workers if you don't have much data, we have many internal use cases that less workers significantly speedup the training

**Comment by linetor** [comment]
@thvasilo Thanks for your sharing. I will check it bu  the non-distributed version.

@CodingCat Ok, I understand why cpu utilization is low. I think I need to count data number and optimize spark process for more efficient utilization of cluster. Thanks for your detail explanation

I think I find what I want.
