### ISSUE TITLE
cannot import name 'labelEncoder' from 'sklearn.preprocessing'

### ISSUE THREAD

**Issue by maphany** [dmlc/xgboost#4089]
Thanks for participating in the XGBoost community! We use https://discuss.xgboost.ai for any general usage questions and discussions. The issue tracker is used for actionable items such as feature proposals discussion, roadmaps, and bug tracking.  You are always welcomed to post on the forum first :)

Issues that are inactive for a period of time may get closed. We adopt this policy so that we won't lose track of actionable issues that may fall at the bottom of the pile. Feel free to reopen a new one if you feel there is an additional problem that needs attention when an old one gets closed.

For bug reports, to help the developer act on the issues, please include a description of your environment, preferably a minimum script to reproduce the problem.

For feature proposals, list clear, small actionable items so we can track the progress of the change.

**Comment by hcho3** [comment]
@maphany Please give us more details: what you tried, the script you were running etc. Without details, your issue may be closed early.

**Comment by hcho3** [comment]
Also this may be of interest to you: scikit-learn/scikit-learn#1613

**Comment by maphany** [comment]
Hi,
I am running python in Anaconda.

Here is my line of code: from sklearn.preprocessing import labelEncoder

I am trying to import Encoder to encode categorical variables. But I keep
getting this error:

from sklearn.preprocessing import labelEncoder
Traceback (most recent call last):

  File "<ipython-input-11-c8ba4564c5da>", line 1, in <module>
    from sklearn.preprocessing import labelEncoder

ImportError: cannot import name 'labelEncoder' from 'sklearn.preprocessing'
(/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/__init__.py)

Thank you! I tried updating Anaconda in terminal to no avail.
