### ISSUE TITLE
[Roadmap] external memory support for tree_method='hist'

### ISSUE THREAD

**Issue by CodingCat** [dmlc/xgboost#4093]
in the [doc](https://xgboost.readthedocs.io/en/latest/parameter.html) we mentioned that Distributed and external memory version only support tree_method=approx

but is it valid now? what's the problem with external memory + hist? I tested but didn't see any issue, did I miss anything?

**Comment by CodingCat** [comment]
@hcho3

**Comment by CodingCat** [comment]
hmmm....looks like the training converged too early....but didn't get the idea why it is related to external memory or the row.page has some problem....

**Comment by trivialfis** [comment]
There's open issue related to external memory #4037.  I'm still struggling to understand it...

**Comment by CodingCat** [comment]
@hcho3 , yes, our data size makes external memory a must-have......but I am a bit confused which part makes hist does not work with external memory....

@trivialfis what I observed is that when I setup external memory with hist tree_method, the metrics (train/test) doesn't change after 5 - 6 iterations, though the training still moves forward.....

**Comment by CodingCat** [comment]
I have started looking into why external memory version of hist is messed up with accuracy

**Comment by hcho3** [comment]
@CodingCat Is this issue blocking?

**Comment by CodingCat** [comment]
no, it just means you need more memory to use distributed hist,

**Comment by rongou** [comment]
@CodingCat Is this still an issue? As part of my work on gpu external memory support, I tested `hist` on the Higgs dataset and got identical AUC metrics. The external memory version is actually slightly faster.

|Mode|Time(seconds)|AUC|
|---|---:|---:|
|`hist`|1309.64|0.8393|
|`hist` external memory|1228.53|0.8393|

**Comment by CodingCat** [comment]
I didn’t test it for a while...last time what I saw is the metrics stays
the same since the first few iteration

Maybe it has been fixed in some changes regarding dmatrix, etc.

**Comment by PeterPanonGit** [comment]
@rongou In my experiments external memory seems to run much slower than the in-memory counterpart regardless of the tree_method I use. However in your benchmark it seems that hist and hist external memory speed is almost the same. Could you post a script that we can use to re-produce your benchmark?

**Comment by rongou** [comment]
@PeterPanonGit I don't have the script anymore, but I wasn't doing anything special, just the standard approach for enabling external memory. Since in external memory mode a lot of data is written out to disk and read back, the speed of your disk might be a factor. Are you on a local desktop with a late model SSD? In the cloud environment I/O might be more constrained.

**Comment by PeterPanonGit** [comment]
@rongou I used an SSD but external memory version is still ~3x slower than in memory version. Maybe my SSD is not good. Is there a way to check how much time is spent on disk I/O and how much time is spend on in-memory computation?

**Comment by rongou** [comment]
There should be some logging output when the files are written out, before tree construction starts.

**Comment by trivialfis** [comment]
Closing in favor of https://github.com/dmlc/xgboost/issues/7354 .
