### ISSUE TITLE
External Memory

### ISSUE THREAD

**Issue by BlindApe** [dmlc/xgboost#410]
I would like to know what External Memory exactly is. I only found this reference:

https://github.com/dmlc/xgboost/blob/master/doc/external_memory.md

but didn't help me too much.

**Comment by tqchen** [comment]
external memory means the algorithm save some data data into disk and directly operates on it. This means xgboost can scale to problem where the dataset do not fit into the RAM on single machine

**Comment by AbdealiJK** [comment]
@tqchen I would like more clarification on this.
When running on a dataset with `in memory + col distributed` I got some results which were the same as the `in memory + single machine` results.
But when doing the `external memory + col distributed` version, I get different results.

You mentioned that the algorithm is different in https://github.com/dmlc/xgboost/issues/344#issuecomment-109362329, but I can't find any documentation about the algorithm difference.

Could you please elaborate on this ? I can create a pull request to add that if/when I understand it :)

**Comment by AbdealiJK** [comment]
For : `in memory + single machine` and `external memory + single machine` I get the same results though ...

PS: I am using the v0.60 code base.
