### ISSUE TITLE
R crashing from fatal error

### ISSUE THREAD

**Issue by jmpanfil** [dmlc/xgboost#4100]
I am currently using version 0.71.2 in R 3.4.3. When trying to run the xgboost model, R experiences a fatal error and crashes. No error messages are output to the console. The last message before crashing is the usual message stating which method is being used. I cannot share my data but here are some details. The dataset is ~9.5 million rows by 1700 columns. The set is about 20% dense (non-zero), so about 3 billion non-zero elements. Due to the number of non-zero elements, I cannot convert to a sparse matrix using the Matrix package, because that package does not support 64 bit long vectors. The dataset is about 120 GB in matrix form. I am using an xgb.DMatrix object for the model input. I am running on a machine with 400GB RAM. Without error messages, I am not sure how to debug this issue.

**Comment by hcho3** [comment]
@jmpanfil I think you are running out of memory. You should use sparse matrix for training. See my reply at https://discuss.xgboost.ai/t/alternatives-for-matrix-sparsematrix/635 for possible alternatives.
