### ISSUE TITLE
[jvm-packages] potential checkpoint issues

### ISSUE THREAD

**Issue by yaozhang2016** [dmlc/xgboost#4103]
To community users and developers,

I am using checkpoint during training for distributed scala spark version, however saw two potential issues:

1. I can see checkpointed models in specified LOCAL path, with names like 100.model, 200.model,…; however my checkpoint interval is 50, which looks like model name numbers always look like 2*x.model, where x=checkpointinterval

2. the re-start training will not continue by picking-up latest file *.model, it will always re-starts from the beginning, just like ignoring *.model files in checkpointPath.

Version info: pre-compiled scala spark xgb version 0.81-criteo-20180821 on CDH 2.3.1
Since this version is not compiled with HDFS on, so it only accepts local file path. All above discussion is based on .setCheckpointPath(localPath).

Thanks
Yao

**Comment by CodingCat** [comment]
1 is expected as version number is updated for [twice] (https://github.com/dmlc/xgboost/blob/ae3bb9c2d55f4d1e21df0ad0fcf936044aae783a/jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/XGBoost.java#L184-L212)


for 2, if your version cannot pickup HDFS path, are you sure your driver can access the local path? (e.g. if your application is run in yarn-cluster mode)

**Comment by yaozhang2016** [comment]
@CodingCat 
My spark app runs in default(client mode), I tried a hdfs location in setCheckpointPath, but an error of local file system came out. This why I used a local path and did see *.model files added in training, but when app was broken and re-start, app just ignored its previously saved *.model files and overwrote them in a brand new training. 
However I can use sparkContext to set hdfs location as checkpoint location for RDD, dataframe.  

Thanks
Yao

**Comment by CodingCat** [comment]
why you have to use a local path? can you check if patch https://github.com/dmlc/xgboost/pull/3614/files is in your version?

**Comment by yaozhang2016** [comment]
@CodingCat, 

   I just checked my jar's source code, I don't have your 3614 patch. Looks like the actual jvm-package is from commit b53a5a262c74987d85c54fd3d41bc6d28e5e1d60 at Aug 17, 2018. Is there newly pre-compiled version available? 

Thanks
Yao

**Comment by CodingCat** [comment]
Check https://xgboost.readthedocs.io/en/latest/jvm/xgboost4j_spark_tutorial.html#refer-to-xgboost4j-spark-dependency

You are supposed to refer dependency from maven

**Comment by yaozhang2016** [comment]
Thanks, maven central artifacts are blocked by company.

**Comment by CodingCat** [comment]
you can try to compile by yourself then, just run mvn package -DskipTests
