### ISSUE TITLE
Lose parameters when writing xgboost model in R and loading in Spark bridge

### ISSUE THREAD

**Issue by borisclemencon** [dmlc/xgboost#4104]
## Description

I trained a xgboost model with R (0.80.1) and I want to load it and infer in Spark 2.3 with xgboost4j-spark 0.80.6. When loading the file like this:

```scala
package ml

import ml.dmlc.xgboost4j.scala.XGBoost
import ml.dmlc.xgboost4j.scala.spark.XGBoostClassificationModel

import scala.collection.mutable

/**
  * XGBoostClassificationModel factory to load a pre-trained XGBoostClassificationModel model
  */
object ExternalXgboostModelLoader {
  val numClasses = 2
  val modelCache = mutable.Map.empty[String, XGBoostClassificationModel]

  ///////////////////////////////// PROBLEM HERE ? /////////////////////////////////
  private def buildModel(path:String):XGBoostClassificationModel = {
    val booster = XGBoost.loadModel(path)
    new XGBoostClassificationModel(path, numClasses, booster)
  }
  ///////////////////////////////// PROBLEM HERE ? /////////////////////////////////

  /**
    * Load a pre-trained xgboost model from S3 or HDFS. The path has been
    * obtained by
    *
    * ```
    * sc.addFile(s3Path)
    * val localPath = SparkFiles.get("{model_file_name}")
    * ```
    *
    * @param localPath local path to the pre-trained model
    * @return load pre-trained model
    */
  def apply(localPath: String): XGBoostClassificationModel = {
    modelCache.getOrElseUpdate(localPath, buildModel(localPath))
  }
}
```

... all the parameters from my original model trained in R are reset to default:

```scala
val modelPath = "s3://xxx"
sc.addFile(modelPath) // Add model file (S3, HDFS, local)
val fileName = Paths.get(modelPath).getFileName.toString
val localPath = SparkFiles.get(fileName)
val model = ExternalXgboostModelLoader(localPath)

model.getEta  // 0.3 instead of 0.03
model.getAlpha // 0.0 instead of 0.01
model.getColsampleBytree // 1.0 instead of 0.7
model.getNumRound // 1 instead of ~950
```
Any idea?

## Config
- I am using xgboost 0.80.1 in R, and xgboost4j-spark 0.80.6
- Spark 2.3.1

**Comment by CodingCat** [comment]
explanations are

1. those parameters from R are from XGBoost domain

2. the parameters returned by getEta/getAlpha, etc. is from Spark domain

3. you can save a Spark pipeline for XGBoost with parameters and load it back with the previously set values (since all you do is within Spark domain)

4. you cannot save a XGBoost model and load it back from Spark with the expectation to get parameters from XGBoost domain, though you can still do the prediction 

5. the only way to connect these two domains (at least for now) is to construct the trainers by passing parameters.....

**Comment by hcho3** [comment]
@borisclemencon This is limitation of current model serialization format: all training parameters are lost, and only the final tree outputs are preserved.

**Comment by hcho3** [comment]
@CodingCat The JSON serialization proposal includes a way to preserve the state of every object (credit to @trivialfis). Would it help in this case?
