### ISSUE TITLE
xgboost for GPU hangs on AllReduce and CPU Barrier 

### ISSUE THREAD

**Issue by sh1ng** [dmlc/xgboost#4107]
Could be nccl issue, but I'd like to get a confirmation.
https://github.com/NVIDIA/nccl/issues/176

**Comment by trivialfis** [comment]
Yes.  I encountered this after rewriting the build script.  Tried to track down the related part of NCCL but those CPU barrier code is removed in latest brand.  Will summit a workaround soon.

**Comment by sh1ng** [comment]
Could you point me to a commit that fixes it? We can update our fork.
