### ISSUE TITLE
[jvm-package] Max Leaves == Max Depth ?

### ISSUE THREAD

**Issue by venky177** [dmlc/xgboost#4111]
Is this expected ?

https://github.com/dmlc/xgboost/blob/ae3bb9c2d55f4d1e21df0ad0fcf936044aae783a/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/BoosterParams.scala#L65

**Comment by CodingCat** [comment]
it's a typo, sorry.....

and @rongou has fixed that in the master branch
