### ISSUE TITLE
[jvm-package]  Incorrect number of weights and groups in ranking test.

### ISSUE THREAD

**Issue by trivialfis** [dmlc/xgboost#4117]
While working on #4115, @hcho3 pointed out the test in scala ranking is incorrect: https://github.com/dmlc/xgboost/pull/4115#issuecomment-461905073

The number of groups should be equal to number of weights but my added check shows otherwise:
https://travis-ci.org/dmlc/xgboost/jobs/490661939#L1557

@CodingCat Could you make a separated PR so that I can rebase on?

**Comment by CodingCat** [comment]
ack doing it today

**Comment by trivialfis** [comment]
Thanks!
