### ISSUE TITLE
How a trained model with  xgboost4j-spark becomes a web service

### ISSUE THREAD

**Issue by zyq11223** [dmlc/xgboost#4119]
I've used xgboost4j-spark trained a xgboost model, and spark ml trained a LR model. But in product i have to pass the results which were predicted by the model to the web service.  Could you mind tell me how to deploy the trained xgboost model as a web service ? And extract the results from spark dataframe is very slow, so it can not solve the problem . Appreciate!

**Comment by zyq11223** [comment]
@CodingCat

**Comment by zyq11223** [comment]
@tqchen

**Comment by hcho3** [comment]
@zyq11223 Consider using [dmlc/treelite](https://github.com/dmlc/treelite). If you are looking for managed solutions, you can look into using [Amazon SageMaker](https://aws.amazon.com/sagemaker/). See [this example](https://github.com/awslabs/amazon-sagemaker-examples/blob/master/advanced_functionality/xgboost_bring_your_own_model/xgboost_bring_your_own_model.ipynb) for deploying pre-trained XGBoost model as web endpoint.

**Comment by hcho3** [comment]
Closing this for now. Feel free to post at https://discuss.xgboost.ai/
