### ISSUE TITLE
early stopping with scikit-learn grid search

### ISSUE THREAD

**Issue by lancerts** [dmlc/xgboost#412]
Hi, i'm wondering if it's possible to add in the early stopping feature into the scikit-wrapper which is very useful.
Here is the same request i've found.
https://www.kaggle.com/c/liberty-mutual-group-property-inspection-prediction/forums/t/15235/xgboost-sklearn-api-gridsearch-early-stopping
If can be made officially here, it will be great!

**Comment by tqchen** [comment]
The early stopping has been in the most recent version of master

**Comment by tyokota** [comment]
Sorry, where would I input `early_stopping_rounds` ?

**Comment by tyokota** [comment]
where do I set early_stopping_rounds?

fit_param = {'early_stopping_rounds': 100}

**Comment by jontonsoup** [comment]
@tyokota did you figure this out? Thanks!
