### ISSUE TITLE
Handling empty datasets.

### ISSUE THREAD

**Issue by trivialfis** [dmlc/xgboost#4120]
Currently empty datasets are not well handled in XGBoost.  As far as I know there are three different situations where empty datasets might appear:

1. The input dataset (for training, prediction, evals ...) is empty due to all entries are `NAN`. #4083
2. There are more GPUs than data rows, so some GPUs don't have assigned data. #3984 
3. After sampling.

As suggested by @pseudotensor , for the first case, we might want to add a dummy updater/predictor that returns a wild guess and probably with a warning message.

For the second case, I got stuck for not having access to this kind of monster machine. :)

@hcho3 @CodingCat @RAMitchell I'm looking for suggestions to solve the first case (second case is also welcome but not urgent) .  Is there other alternative solution?  Do we make it blocking for the next release?  Or we just make a check to prevent segfault so that we can unblock it for now, and fix it more profoundly after next release?

**Comment by hcho3** [comment]
@trivialfis I think the first case is related to #4085 and #2943. The cause is that the quantile sketcher fails to create a sketch for columns filled with `NAN` or identical constant values. Can I take a shot at it this week? If it doesn't go well, we'll have to put a band-aid and return after 0.82 release.

**Comment by pseudotensor** [comment]
There many other ways one should go back to a dummy model.  E.g., even if there is no valid eval set (e.g. all NaNs), one can still predict the "average" model.  It's not only about constant columns or many missings, etc.  LightGBM has done a good job lately about fixing all these types of issues.

**Comment by hcho3** [comment]
@pseudotensor Are you aware of other failure modes other than shown in #4085, #2943, and #4083 ?

**Comment by trivialfis** [comment]
GPU Hist is well prepared for empty dataset now.
