### ISSUE TITLE
support checkpoint path point to GCS

### ISSUE THREAD

**Issue by chenqin** [dmlc/xgboost#4122]
Currently setting checkpoint path to gs:// will cause executor throw exception not knowing file system starts with gs://. The way to reproduce is to start a spark xgboost job in GCP via spark k8s operator  
`
spec:
  jars:
    - local:///opt/spark/jars/gcs-connector-latest-hadoop2.jar
  hadoopConf:
    "xxx.checkpoint_path": "gs:///dir"
    ...
    "fs.gs.impl": "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem"
    "fs.AbstractFileSystem.gs.impl": "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS"
    "fs.gs.project.id": x
    "fs.gs.system.bucket": x
    "google.cloud.auth.service.account.enable": true
    #"google.cloud.auth.service.account.json.keyfile": /mnt/secrets/key.json
  sparkConf:
    "spark.task.cpus": 1
  mode: cluster
  type: Scala
  image: "gcr.io/spark-operator/spark:v2.4.0-gcs-prometheus"
  imagePullPolicy: Always

`

**Comment by hcho3** [comment]
@chenqin The feature request for Google Cloud Storage has been around for a while: dmlc/dmlc-core#14. XGBoost delegates all file I/O to dmlc-core.

**Comment by CodingCat** [comment]
Can you post the stacktrace? If it is purey from jvm, it mostly because of misconfiguration in your hdfs
