### ISSUE TITLE
xgboost4j-java cannot load xgboost model trained by xgboost4j-spark

### ISSUE THREAD

**Issue by zyq11223** [dmlc/xgboost#4124]
Are there any ways to solve the issue? 
I trained a xgboost model with xgboost4j-spark. And I want load it with xgboost4j java api -XGBoost.loadModel(). 
Appreciate!

**Comment by hcho3** [comment]
See https://xgboost.readthedocs.io/en/latest/jvm/xgboost4j_spark_tutorial.html#interact-with-other-bindings-of-xgboost.
