### ISSUE TITLE
Monotonic constraint XGBClassifier & plot_tree interpretation

### ISSUE THREAD

**Issue by selectasterisk** [dmlc/xgboost#4129]
I am trying to constraint all the features (continuous and categorical) to be monotonically increasing w.r.t the target variable. It is my understanding that this is possible in XGBoost.

Following the instructions on the tutorial page, I used the following in my model parameters.

`params_constrained['monotone_constraints'] = '('+''.join(['1,' for x in range(data_train.shape[1])])[:-1]+')'
`
Training the model, I noticed that the model outputs different evaluation metrics, implying something was done. To be more specific, I am using XGBClassifier for a binary classification problem with         `'objective': 'binary:logistic',`n_jobs=-1`, `n_estimators:150`. The data I am training on is in `sparse_matrix` format.

When I inspected the splits using `plot_tree`, I noticed that the leaves do not have positives only output. Further, I am a bit confused by what is feature is splitting on. Double checking my mappings, it does seem like the three features that it is doing splits are categorical values. But I am not confused by what the actual split is. Since it is a binary value, it should either be 0 or 1. Splitting on `f315< -9.535674316e-07` would imply that it would always go to the `No` branch.

Below is a screenshot of what I described above.
![image](https://user-images.githubusercontent.com/39502715/52615218-406ebc00-2e49-11e9-9ca9-531d48e60b3f.png)

Another screenshot of plot_tree, but a split with a continuous variable at the bottom. There are values for that continuous variable that is less than 2003.5
![image](https://user-images.githubusercontent.com/39502715/52615726-07cfe200-2e4b-11e9-8af4-62196863e920.png)

I have two questions: 
1) What is the interpretation of the categorical value's split in the picture above? is `-9.535674316e-07` an overflow of some kind?
2) Is the type of monotonic constraint where every feature, and every feature interaction is positively correlated (monotonically increasing) with the target variable possible in the XGBoost framework?

**Comment by hcho3** [comment]
1. The split `f315 < -9.535674316e-07` will be false for all non-missing values. Note that you can get to "yes" branch if the feature 315 has a missing value. In effect, the split is distinguishing between missing and non-missing values. It is likely that 0 is encoded as missing value. This kind of split is pretty common for trees splitting on binary variables.
2. Monotonic constraints apply to individual variables, not interactions. You can create interaction terms (`x1*x2`) and impose monotonic constraints on the interaction terms.

**Comment by selectasterisk** [comment]
Ah interesting. I have some follow up questions:

1) Yes, I believe the missing values are encoded as zero if they did not appear (a bag of words if you will). I've read that adding an additional value during preprocessing for categorical variables indicating that they are missing will result in a model that is what we'd expect. per https://github.com/dmlc/xgboost/issues/3267 . In cases like these, is the default branch for the variable when it is missing still learned, or is it defaulting to the left branch? (and an extension: was the split on `9.535674316e-07` learned as well? it seems to appear in many places in the model from scanning)

2) Does this mean that it only makes sense when we use decision stumps? Since it is possible to get a non-monotonic output, when we hold all variables fixed save for `f249` as an example. (e.g. `f315` is not missing, but `f249` is). 

3) What does it mean for monotonic constraints to apply to individual variables in this case? Is there an intuitive example that you can provide?

**Comment by hcho3** [comment]
> 1. is the default branch for the variable when it is missing still learned, or is it defaulting to the left branch?

The default direction is learned as well. And yes, the threshold is also learned.

> Since it is possible to get a non-monotonic output, when we hold all variables fixed save for `f249` as an example. (e.g. `f315` is not missing, but `f249` is).

I don't think I follow you here. The plotted tree in your example doesn't contain any split using `f249`, so you'd get the same value for all possible values of `f249` (with other variables being fixed).

> 3\. What does it mean for monotonic constraints to apply to individual variables in this case? Is there an intuitive example that you can provide?

See https://xgboost.readthedocs.io/en/latest/tutorials/monotonic.html. We can enforce whether the target should monotonically increase or decrease as a given input variable is increased or decreased.

**Comment by selectasterisk** [comment]
> I don't think I follow you here. The plotted tree in your example doesn't contain any split using `f249`, so you'd get the same value for all possible values of `f249` (with other variables being fixed).
The confusion might of been caused by there being two plotted trees, so my apologies for that. I am referring to the first diagram, the node on the right on the second level. Depending on whether `f249` is present, it could either influence the output to be smaller or bigger, but not monotonically increasing, as an example. I suppose this is due to what the split learns, and not actually about the values themselves for this split?

Is what is meant by monotonically increasing just that the split leaf node will always be smaller than the right leaf node?  (since the sign on the decision will always be `<`) e.g. Referring to the second diagram, if all variables are held constant save for `f204`, if `f204=2003`, then we'd get a smaller  output, than if `f204=2004`?

**Comment by hcho3** [comment]
> Depending on whether `f249` is present, it could either influence the output to be smaller or bigger, but not monotonically increasing, as an example

In the right subtree, the internal node has the split `f249 < -9.53674316e-07`, which evaluates to false for all non-missing values. Since `f249` is a binary variable, the split actually does the right thing: value 0 (encoded as missing) goes to the left, and value 1 goes to the right. So the tree is monotonically increasing with respect to the binary variable `f249`.

> Is what is meant by monotonically increasing just that the split leaf node will always be smaller than the right leaf node?

More precisely, the choice of leaf outputs is constrained so that we get monotonicity behavior. Note that, for example, the left child leaf of `f204 < 2003.5` was deliberately chosen to be smaller than the right child leaf.

**Comment by selectasterisk** [comment]
I think this is clear to me now. Thanks!
