### ISSUE TITLE
[jvm-packages] Feature Constraints param in XGBoost4J-Spark

### ISSUE THREAD

**Issue by akhilbatra898** [dmlc/xgboost#4131]
I am training xgboost model on the spark in distributed manner. I want to use `interaction_constraint` and `monotone_comnstraint`, but I am unable to find a way to do so.

I am aware that it is supported in in-memory python, but It will be helpful if it is supported in spark.

**Comment by hcho3** [comment]
@CodingCat Do we have distributed `hist` in 0.82-SNAPSHOT?

**Comment by CodingCat** [comment]
Yes,

**Comment by hcho3** [comment]
@akhilbatra898 You should try using 0.82-SNAPSHOT. The 0.82 release is currently in the work

**Comment by akhilbatra898** [comment]
@hcho3 

Is there any documentation how to use feature constraints in spark. As per my understanding one cannot pass them along with general params.

**Comment by CodingCat** [comment]
you can...check https://github.com/dmlc/xgboost/blob/master/jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostGeneralSuite.scala#L126

**Comment by akhilbatra898** [comment]
Hi @CodingCat 

I tried the examples from test case. Apparantly initialising Classifier like[ this](https://github.com/dmlc/xgboost/blob/1dac5e24108890c946c5a4673f0d1fa4d6125943/jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostGeneralSuite.scala#L122) ignores extra params like interaction constraints and monotone constraints and only use general params for training.


Can you check?

**Comment by CodingCat** [comment]
which versiok are you using?

**Comment by akhilbatra898** [comment]
I have tried on both 0.82 and 0.81 snapshot

**Comment by CodingCat** [comment]
I validated by instrumenting in https://github.com/dmlc/xgboost/blob/master/src/tree/split_evaluator.cc#L240-L247 

and https://github.com/dmlc/xgboost/blob/master/src/tree/split_evaluator.cc#L413-L421


I can see the specified constraints is well received in native layer

Can you compile the latest master branch and try?
