### ISSUE TITLE
colsample_bytree still locale dependant.

### ISSUE THREAD

**Issue by vbogach** [dmlc/xgboost#4132]
Despite #3230 was closed, this issue still remains if number delimiter is set to space (i.g. 123 456 789).

Way to represent:
1. Install Ubuntu 18.04 LTS.
2. Go to Settings -> Region & Language, set Formats to Russia (Российская Федерация).
3. Same as #3230.

**Comment by hcho3** [comment]
@vbogach I think you should always use the American notation (`.` as delimiter).
