### ISSUE TITLE
Deprecate `num_roots` parameter

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#4133]
The parameter `num_roots` is not documented in the [parameter list](https://xgboost.readthedocs.io/en/latest/parameter.html). The parameter was probably added on an experimental basis, to enable multi-root decision trees. The fast quantile updater (`tree_method=hist`) does not support this parameter. I'd suggest that we deprecate this parameter and eventually remove it.

@trivialfis

**Comment by trivialfis** [comment]
Agree.

**Comment by hcho3** [comment]
Will submit a pull request soon
