### ISSUE TITLE
DMatrix does not parse libsvm txt format when # comment is present

### ISSUE THREAD

**Issue by kkonevets** [dmlc/xgboost#4135]
For example, libsvm format is this one
https://sourceforge.net/p/lemur/wiki/RankLib%20File%20Format/

When # comment is present at the end of line DMatrix crashes on loading. Error is unreadable at all

**Comment by trivialfis** [comment]
@hcho3 Could you take a look at https://github.com/dmlc/dmlc-core/pull/514 ?

**Comment by trivialfis** [comment]
@hcho3 Any update? :)
