### ISSUE TITLE
Custom Objective Function

### ISSUE THREAD

**Issue by kgoyal40** [dmlc/xgboost#4137]
Hi,

I was wondering if there is a way to pass on additional parameters to the customized objective function. at each step, my model would depend on the tree structure above. At every split, I need to pass on features already selected in the tree as a parameter. Please let me know if something like this is possible.

Thanks

**Comment by Denisevi4** [comment]
There is a forum for discussions https://discuss.xgboost.ai/

Also, would be helpful to know exactly what you're trying to do.

**Comment by kgoyal40** [comment]
Hi,

At every split, i am trying to add a regularization term which depends on the interaction between the previously selected features and the feature being considered currently.

Thanks

**Comment by hcho3** [comment]
@kgoyal40 I don't think it is possible to pass additional parameters to custom objective function. However, you can use [Feature Interaction Constraints](https://xgboost.readthedocs.io/en/latest/tutorials/feature_interaction_constraint.html).

**Comment by hcho3** [comment]
I opened a new issue to discuss a possible implementation of user-defined split evaluator: #4230
