### ISSUE TITLE
[jvm-package] XGBoost4j-Spark has random failures

### ISSUE THREAD

**Issue by FredYao** [dmlc/xgboost#4143]
I tried to train a XGBoost model using Spark. The raw data size is small, 100MB. Here is my param:

`
val xgbParam = Map(
			"eta" -> 0.2f,
			"max_depth" -> 6,
			"objective" -> "binary:logistic",
			"num_round" -> 300,
			"subsample" -> 0.9f,
			"gamma" -> 0.25f,
			"colsample_bytree" -> 1.0f,
			"tracker_conf" -> TrackerConf(30000L, "scala"),
			"nthread" -> 2,
			"num_workers" -> 4,
			"verbosity" -> 3
		)
`
I ran my training scripts multiple times, some of them ran smoothly and ended up with a trained model, other times reported errors like:

`
2019-02-14 15:13:07 INFO  XGBoostSpark:293 - Rabit returns with exit code 3
Failed to fit the pipeline on given data, ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed
[INFO] [02/14/2019 15:13:07.936] [RabitTracker-akka.actor.default-dispatcher-4] [akka://RabitTracker/user/Handler] Message [ml.dmlc.xgboost4j.scala.rabit.handler.RabitTrackerHandler$InterruptTracker] from Actor[akka://RabitTracker/temp/$a] to Actor[akka://RabitTracker/user/Handler#240075463] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
`

There was no other useful information printed out for debug. Does anybody know what could cause those random failures? Maybe data was skew? Or maybe the resource (e.g., num_workers, nthread, num-executors, executor-memory) is not set properly?

Thanks!

**Comment by CodingCat** [comment]
please use python tracker, scala tracker is experimental and out of maintenance for a while

**Comment by FredYao** [comment]
@CodingCat , thanks, let me try to use Python tracker.

**Comment by FredYao** [comment]
@CodingCat , I know the default tracker requires Python 2.7+. The cluster I am using has several python versions (2.6, 2.7, etc) installed. But the default was set to 2.6. So that's why I explicitly defined the tracker to "scala". Is it possible to explicitly set the python version in XGBoost?

**Comment by CodingCat** [comment]
I am not sure about this, if you know the installation path of python, you can setup PATH env?
