### ISSUE TITLE
Fail to do multithreading if tensorflow is imported before xgboost

### ISSUE THREAD

**Issue by ywchan2005** [dmlc/xgboost#4145]
xgboost uses only a single cpu core (with nthread=-1 for DMatrix or n_jobs=-1 for XGBClassifier and XGBRegressor) when tensorflow is imported before xgboost. If import order is reversed, that is tensorflow is imported after xgboost, xgboost is able to use all cpu cores with the same setting.

problematic import order causing xgboost to use only one single cpu
```
import tensorflow
import xgboost
```

import order making xgboost works normally
```
import xgboost
import tensorflow
```

the rest of the code for training is the same for both cases and pasted here for reference

_XGBClassifier_
```
m = xgb.XGBClassifier( n_jobs=-1 )
m.fit( x, y )
```

_XGBRegressor_
```
m = xgb.XGBRegressor( n_jobs=-1 )
m.fit( x, y )
```

_DMatrix_
```
dtrain = xgb.DMatrix( x, label=y )
m = xgb.train( params={ 'objective': 'reg:linear', 'nthread': -1 }, dtrain=dtrain )
```

xgboost version: 0.81
tensorflow version: 1.12
python version: 3.6
dockerfile base image: continuumio/anaconda3 (debian 9.5)

**Comment by hcho3** [comment]
Which operating system are you using? Are you seeing this issue on multiple OSes?

**Comment by ywchan2005** [comment]
> Which operating system are you using? Are you seeing this issue on multiple OSes?

i'm used only continuumio/anaconda3 dockerfile (debian 9.5)

**Comment by hcho3** [comment]
@ywchan2005 Can you upload your dockerfile? I wonder if it's a OS specific issue.

**Comment by ywchan2005** [comment]
i've compared two dockers, one with continuumio/anaconda3 as base image and one with fedora as base image. it's confirmed that anaconda environment causes the problem, while xgboost works well in fedora environment.

two dockerfiles are attached for reference
[Dockerfile.anaconda.zip](https://github.com/dmlc/xgboost/files/2871524/Dockerfile.anaconda.zip)
[Dockerfile.fedora.zip](https://github.com/dmlc/xgboost/files/2871525/Dockerfile.fedora.zip)

**Comment by hcho3** [comment]
@ywchan2005 It turns out that we (XGBoost maintainers) do not maintain the conda distribution of XGBoost. The Pip package is the only official channel of distribution. So I'm not sure how we can help here.
