### ISSUE TITLE
Eliminate extra dataset copy in Python.

### ISSUE THREAD

**Issue by trivialfis** [dmlc/xgboost#4150]
During construction of DMatrix, Python wrapper might duplicate the dataset because it's not contiguous or not of the right data type. But we can handle these situations inside c++ code to avoid constructing an extra copy of dataset.

My goal is not to share the underlying buffer with Python data structure, but to eliminate the extra copies constructed during conversion inside Python wrapper.

**Comment by hcho3** [comment]
Fixed in #4147
