### ISSUE TITLE
[RFC] Ending Python 2 support

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#4154]
Given that [Python 2](https://www.python.org/dev/peps/pep-0373/#update) will reach its end of life at the end of this year, we should drop Python 2 support. That is, contributors would no longer be required to write Python code that's compatible with Python 2.7. Also, Python distributions of XGBoost on PyPI will be Python 3 exclusive.

A good time to make this change would be release 0.90.

**Comment by hcho3** [comment]
@CodingCat Does the Python tracker in XGBoost4J-Spark require Python 2.x?

**Comment by trivialfis** [comment]
I want to bring this up long time ago.  :smile: https://pythonclock.org/

**Comment by CodingCat** [comment]
@hcho3 I thought it was only tested with python 2, but we can double check travis’s environment to confirm

**Comment by hcho3** [comment]
Opened vote thread in #4379
