### ISSUE TITLE
XGBoost 0.81.0.1 gpu_id > 0 fails although nvidia-smi finds 4 gpus

### ISSUE THREAD

**Issue by jpbowman01** [dmlc/xgboost#4160]
I have just installed XGBoost 0.81.0.1 on a brand new DGX workstation running CUDA 10.  It runs out of R with tree_method="gpu_hist" successfully with no gpu_id specified or gpu_id = 0, but not with gpu_id = 1 (or greater) despite nvidia-smi finding all four GPU cards.  

Reproducible example follows:

library(xgboost)
data(agaricus.train, package='xgboost')
data(agaricus.test, package='xgboost')

dtrain <- xgb.DMatrix(agaricus.train$data, label = agaricus.train$label)
dtest <- xgb.DMatrix(agaricus.test$data, label = agaricus.test$label)
watchlist <- list(train = dtrain, eval = dtest)
param <- list(max_depth = 2, eta = 1, silent = 1, nthread = 2, 
tree_method="gpu_hist",  objective = "binary:logistic", eval_metric = "auc", gpu_id=0)

bst <- xgb.train(param, dtrain, nrounds = 2, watchlist)
[1]     train-auc:0.958228      eval-auc:0.960373
[2]     train-auc:0.981413      eval-auc:0.979930

param <- list(max_depth = 2, eta = 1, silent = 1, nthread = 2, 
tree_method="gpu_hist", objective = "binary:logistic", eval_metric = "auc", gpu_id=1)

bst <- xgb.train(param, dtrain, nrounds = 2, watchlist)
Error in xgb.iter.update(bst$handle, dtrain, iteration - 1, obj) :
  [10:59:50] /home/jbowma1/xgboost/src/common/host_device_vector.cu:355: Check failed: distribution_.IsEmpty() || distribution.IsEmpty()

Stack trace returned 10 entries:
[bt] (0) /usr/lib/R/library/xgboost/libs/xgboost.so(dmlc::StackTrace[abi:cxx11](unsigned long)+0x8b) [0x7f8f97326e9b] [bt] (1) /usr/lib/R/library/xgboost/libs/xgboost.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x3e) [0x7f8f9732777e] [bt] (2) /usr/lib/R/library/xgboost/libs/xgboost.so(xgboost::HostDeviceVectorImpl<float>::Reshard(xgboost::GPUDistribution const&)+0xad) [0x7f8f9751730d] [bt] (3) /usr/lib/R/library/xgboost/libs/xgboost.so(+0x2fdde7) [0x7f8f97557de7] [bt] (4) /usr/lib/R/library/xgboost/libs/xgboost.so(xgboost::obj::RegLossObj<xgboost::obj::LogisticClassification>::GetGradient(xgboost::HostDeviceVector<float> const&, xgboost::MetaInfo const&, int, xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*)+0x5c0) [0x7f8f975664a0] [bt] (5) /usr/lib/R/library/xgboost/libs/xgboost.so(
>

This example has been reproduced by Alex Kozlov of NVIDIA in a different environment:

"I reproed the issue on a nvcr.io/nvidia/rapidsai/rapidsai:0.5-cuda10.0-base-ubuntu18.04-gcc7-py3.7 container"

XGBoostError: b'[19:43:12] /rapids/xgboost/src/common/host_device_vector.cu:373: Check failed: distribution_.IsEmpty() \n\nStack trace returned 10 entries:\n[bt] (0) /conda/envs/rapids/lib/python3.7/site-packages/xgboost-0.80-py3.7.egg/xgboost/./lib/libxgboost.so(dmlc::StackTrace[abi:cxx11]()+0x53) [0x7f95cf639bd3]\n[bt] (1) /conda/envs/rapids/lib/python3.7/site-packages/xgboost-0.80-py3.7.egg/xgboost/./lib/libxgboost.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x39) [0x7f95cf63a469]\n[bt] (2) /conda/envs/rapids/lib/python3.7/site-packages/xgboost-0.80-py3.7.egg/xgboost/./lib/libxgboost.so(xgboost::HostDeviceVector<float>::Reshard(xgboost::GPUSet) const+0xfd) [0x7f95cf85190d]\n[bt] (3) /conda/envs/rapids/lib/python3.7/site-packages/xgboost-0.80-py3.7.egg/xgboost/./lib/libxgboost.so(xgboost::obj::GPURegLossObj<xgboost::obj::LinearSquareLoss>::GetGradient(xgboost::HostDeviceVector<float> const&, xgboost::MetaInfo const&, int, xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*)+0x295) [0x7f95cf87a105]\n[bt] (4) /conda/envs/rapids/lib/python3.7/site-packages/xgboost-0.80-py3.7.egg/xgboost/./lib/libxgboost.so(xgboost::LearnerImpl::UpdateOneIter(int, xgboost::DMatrix*)+0x1ce) [0x7f95cf6c8f0e]\n[bt] (5) /conda/envs/rapids/lib/python3.7/site-packages/xgboost-0.80-py3.7.egg/xgboost/./lib/libxgboost.so(XGBoosterUpdateOneIter+0x48) [0x7f95cf62e2a8]\n[bt] (6) /conda/envs/rapids/lib/python3.7/lib-dynload/../../libffi.so.6(ffi_call_unix64+0x4c) [0x7f964201eec0]\n[bt] (7) /conda/envs/rapids/lib/python3.7/lib-dynload/../../libffi.so.6(ffi_call+0x22d) [0x7f964201e87d]\n[bt] (8) /conda/envs/rapids/lib/python3.7/lib-dynload/_ctypes.cpython-37m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7f9642234f3e]\n[bt] (9) /conda/envs/rapids/lib/python3.7/lib-dynload/_ctypes.cpython-37m-x86_64-linux-gnu.so(+0x13974) [0x7f9642235974]\n\n'

My installation was:

git clone --recursive https://github.com/dmlc/xgboost
cd xgboost
git submodule init
git submodule update
mkdir build
cd build
cmake .. -DUSE_CUDA=ON -DR_LIB=ON 

make install -j

followed by the install of the R package in the XGBoost/build directory.  I am not intending to use NCCL, so did not install it.

**Comment by trivialfis** [comment]
@jpbowman01 Currently we can't change the used gpu for dataset, see: https://github.com/dmlc/xgboost/issues/3794

**Comment by jpbowman01** [comment]
Reading through #3794 and testing confirms that this is the same issue, so I'll close this.
