### ISSUE TITLE
Multi-GPU/Multi-GPU-Node support for prediction

### ISSUE THREAD

**Issue by thealaskalife** [dmlc/xgboost#4166]
Hi Guys,
We are trying to deploy XGBoost for prediction in real business scenario with GPU. However we found that only GPU0 can be used. We are wondering if there is a plan to support Multi-GPU and Multi-Node prediction?

**Comment by RAMitchell** [comment]
Can you provide a script of what you are trying to do and what you expect to happen?

**Comment by hcho3** [comment]
Prediction with multiple GPUs should be available starting from version 0.81.
