### ISSUE TITLE
GPU Support for Feature Interaction Constraints

### ISSUE THREAD

**Issue by laceyg** [dmlc/xgboost#4169]
Is there any active work or plan to support [Feature Interaction Constraints](https://xgboost.readthedocs.io/en/latest/tutorials/feature_interaction_constraint.html) on GPUs with ```gpu_hist``` and ```gpu_exact```?  Is there anything fundamental about this feature that would violate a parallel implementation?

**Comment by hcho3** [comment]
> Is there anything fundamental about this feature that would violate a parallel implementation?

This is more due to the fact that we have separate code path for GPU and CPU implementations of the training algorithm. The feature interaction constraints require `SplitEvaluator` class, which is only available from the CPU implementation currently.

**Comment by trivialfis** [comment]
@laceyg Closing as now interaction constraint supports `gpu_hist`, and `gpu_exact` is deprecated.
