### ISSUE TITLE
XGBClassifier (python wrapper) setting eval_set causes "'Booster' object has no attribute 'best_score'" crash

### ISSUE THREAD

**Issue by gatapia** [dmlc/xgboost#417]
The following code crashes:

    xgb = XGBClassifier()
    xgb.fit(np.random.rand(100, 10), np.random.binomial(1, 0.8, 100),
      eval_set=[(np.random.rand(100, 10), np.random.binomial(1, 0.8, 100))])

With the following error:

    xgboost.pyc in fit(self, X, y, sample_weight, eval_set, eval_metric, early_stopping_rounds, verbose)
       1269                             for k, v in eval_results.items()}
       1270             self.eval_results_ = eval_results
    -> 1271             self.best_score_ = self._Booster.best_score
       1272             self.best_iteration_ = self._Booster.best_iteration
       1273
    AttributeError: 'Booster' object has no attribute 'best_score'

**Comment by tqchen** [comment]
Thanks for reporting this. I pushed a fix to this https://github.com/dmlc/xgboost/commit/5f9f42292c82afea411a3939e58544ef4cc723d2 , can you check if this fixed the problem?

**Comment by gatapia** [comment]
Yes, fixed, thanks!!

**Comment by tqchen** [comment]
To prevent such embarrassing things from happening again, it would be great if we can have a more tests here https://github.com/dmlc/xgboost/tree/master/tests/python to check possible cases of interest. 

It would be great if you can contribute some of these for sklearn wrapper based on your experience :)  Hope I am not asking too much from you.

**Comment by gatapia** [comment]
I'm still checking this issue and it appears that an custom eval_metric/set
do not change the output of the model.  The model trained is always the
same regardless of the custom evaluation function.  Is there something I'm
missing here or could this be a bug?

**Comment by tqchen** [comment]
custom eval is only  evaluation function that related to the output of watchlist, it is should not be confused with custom objective function, which will change the behavior of the model trained

**Comment by gatapia** [comment]
My misunderstanding, thanks for the clarification
