### ISSUE TITLE
Predicting with XGB in multiple processes freezes (Python)

### ISSUE THREAD

**Issue by MvdSteeg90** [dmlc/xgboost#4171]
I ran into a problem when trying to use multiprocessing around XGBClassifier. One problem is that the number of threads it calls does not correspond to n_jobs or nthread (even outside of multiprocessing), leading to thread explosion, but more importantly, **if the XGBClassifier has been used anywhere in the main process, it will cause multiprocessing to freeze**.

See below code for an example:

```
from multiprocessing import Pool
from xgboost import XGBClassifier
import numpy as np
import pickle

n_samples = 1000
x = np.random.rand(n_samples, 10)
y = np.random.randint(0, 2, n_samples)
load = False
predict_after_load = False
n_jobs = 1

if load:
    with open('xgb_example.p', 'rb') as rf:
        xgb = pickle.load(rf)
        
    if predict_after_load:
        xgb.predict(x)
else:
    xgb = XGBClassifier(n_jobs=n_jobs)
    xgb.fit(x, y)
    with open('xgb_example.p', 'wb') as wf:
        pickle.dump(xgb, wf)

with Pool(4) as p:
    result = np.vstack(p.map(xgb.predict_proba, np.array_split(x, 10)))
```

This code snippet works. However, changing `n_jobs` to e.g. `2` will break it. However, if you first fit a model with `n_jobs = 2`, and then start a new process with `load = True`, it will work, because the `XGBClassifier` has not been used in that process. However, if you then set `predict_after_load` to True,, the multiprocessing will freeze again, because the model gets used in the main process.

This is very clearly undesirable behavior. I've tried things like deepcopying the model in the worker jobs, or calling `xgb._Booster.copy()` but that doesn't seem to help any.

XGBs built-in multithreading is nice, but there are usecases where they need to be ran inside child processes because the bottleneck lies elsewhere (e.g. preprocessing/vectorizing). I've also posted on the forums, so for more information see https://discuss.xgboost.ai/t/predicting-from-multiple-jobs-threading-issues/661/4

I hope this issue can be fixed! Until then, is there any feasible work-around? I need to be able to call predict both in the main process and in multiprocessing (for different use cases).

**Comment by hcho3** [comment]
@MvdSteeg90 I left my reply in the forum.
