### ISSUE TITLE
[jvm-pacakges] Question About the implementation of xgboost4j-spark code

### ISSUE THREAD

**Issue by wangdaiyin** [dmlc/xgboost#4172]
[Question]: 
About the variable `distributedBoostersAndMetrics`, which is generated in Spark, 
![image](https://user-images.githubusercontent.com/10666762/53167571-3ac86180-3613-11e9-9807-96db02c04bb8.png)
I understand as follows: 
First,  obtain partitionedData through the repartitionForTraining method, the number of partitions depends nWorkers;
Then, for each partition, build a distributed booster according to the training data in this partition ; finally, obtain `nWorker` boosters. 
Is my understanding correct? If not, how to understand correctly？ If yes, I have  the following two question: 
1."why is it only using the partial training data in each partition to build booster instead of all training data？ 
2."why the final boost model is obtained by `distributedBoostersAndMetrics.first()`", 
 ![image](https://user-images.githubusercontent.com/10666762/53167632-6fd4b400-3613-11e9-9475-5282c9f4de03.png)

**Comment by wangdaiyin** [comment]
the above code is located in ml.dmlc.xgboost4j.scala.spark.XGBoost.scala

**Comment by CodingCat** [comment]
there is synchronization mechanism for data sketches and histograms in native layer, so all models across workers are consistent check https://github.com/dmlc/xgboost/blob/master/src/tree/updater_histmaker.cc

**Comment by wangdaiyin** [comment]
OK，i get it，thanks
