### ISSUE TITLE
AUC decreased 0.04 after switching to hist method

### ISSUE THREAD

**Issue by Liuhaoge** [dmlc/xgboost#4182]
I updated the xgboost few weeks age and set the tree_method into "hist" in order to use the monotonic constraints, and I didn't modified other parameters. Yet although the constraints worked, the AUC decreased about 0.04. Can the latest version solve this reduction?

**Comment by hcho3** [comment]
@Liuhaoge Were you using monotonic constraints before?

**Comment by Liuhaoge** [comment]
@hcho3 No, not in distributed environment, I used monotonic constraints only after I switched into "hist". It's the monotonic constraints the reason of the reduction of AUC?

**Comment by hcho3** [comment]
@Liuhaoge Yes, monotonic constraints tend to reduce model fitness, since you are restricting the choice of possible split candidates.
