### ISSUE TITLE
Bug when using `model.predict(dtest, pred_contribs=True, pred_interactions=True)`

### ISSUE THREAD

**Issue by kyoungrok0517** [dmlc/xgboost#4183]
Hi, I'm having trouble using `pred_contribs` and `pred_interactions` features. The phenomenon are:
* Use `pred_contribs` only : It works.
* Use `pred_contribs` and `pred_interactions` : Encounter `ValueError: cannot reshape array of size 42070 into shape (10,0,601,601)` <- 10 is # of samples.
* Use `pred_interactions` only : Encounter std::bad_alloc error (in Ubuntu, just hangs in Windows)

I'm attaching the model and test dmatrix here
* [model](https://www.dropbox.com/s/muaj65cwn5sa3tv/model_2-gram_2019-02-21T02-46-52.pkl?dl=0)
* [dtest](https://www.dropbox.com/s/bfwdf28rn8yfeug/dtest.dmatrix?dl=0)

**Comment by trivialfis** [comment]
@kyoungrok0517 `dtest` is removed?

**Comment by kyoungrok0517** [comment]
Oh, sorry I just recovered the file so please check.

**Comment by trivialfis** [comment]
@kyoungrok0517 Let me take a look

**Comment by trivialfis** [comment]
@kyoungrok0517 Could you share the shape, sparsity of your dataset?  And perhaps some used parameters so that I can generate my own script?

**Comment by kyoungrok0517** [comment]
Sure, first here are the parameters.
```json
{
    "alpha": 0.001,
    "colsample_bytree": 0.4,
    "gamma": 0.001,
    "max_delta_step": 10,
    "max_depth": 10,
    "min_child_weight": 40.0,
    "subsample": 1.0
}

{
    "missing": 0.0,
    "verbosity": 1,
    "nthread": 0,
    "learning_rate": 0.01,
    "n_gpus": -1,
    "tree_method": "gpu_hist",
    "objective": "multi:softprob",
    "num_class": 7,
    "eval_metric": "mlogloss",
    "seed": 2019
}
```

**Dataset Details**
* target is one of 0-6 (seven classes)
* \# of features is 600, which are from 600-dimensional word embedding
  * all floats, dense features (most of them are filled with some value)
* test set(`dtest`) contains 40,000 samples
* I share the dtest as `.hdf5` format [here](https://www.dropbox.com/s/t1rfw4cd7286rgj/dtest.hdf5?dl=0). The data can be accessed like:
```python
with h5py.File('dtest.hdf5', 'r') as f:
    X = f['X'][()]
    y = f['y'][()]
```

**Comment by trivialfis** [comment]
@kyoungrok0517 For `bad_alloc` from `pred_interactions`, that's expected.  Reading from Python API's doc,  xgboost will return a matrix with shape: `(nsample, nfeats + 1, nfeats + 1)`,  reading from source code it's of size: `rows * num_classes * columns * columns`.  Using 0.2 portion of your dataset as test set, this size would be (with 32-bit float) **86 GB**.

**Comment by trivialfis** [comment]
I will look into the other one tomorrow.

**Comment by kyoungrok0517** [comment]
Wow... I didn’t realize that. Hope to see the answer for the second one soon :) thanks!

**Comment by kyoungrok0517** [comment]
One more question: Is using ` approx_contribs=True, pred_interactions=True` combination actually computes interactions using 'approximated' contribution score? If not then the required computation will be too huge

**Comment by trivialfis** [comment]
@kyoungrok0517 Sorry for the delay.  I think you need to do it in two passes, one for contribs anther for interactions.

**Comment by trivialfis** [comment]
> computes interactions using 'approximated' contribution score

@kyoungrok0517 It might be better to ask author of SHAP.

**Comment by kyoungrok0517** [comment]
@trivialfis Seems like there's some complication deriving interaction features. I'll talk to the author of SHAP about this. Thank you!
