### ISSUE TITLE
Different prediction for MacOS High Sierra Vs Linux

### ISSUE THREAD

**Issue by Devarsh-UTD** [dmlc/xgboost#4185]
I am using Xgboost in python, when using the same set of parameters on MacOS and Linux, it is giving me very different prediction results. I came across a link that mentions somewhat similar problem in R but didn't find any solutions. Initially I tried upgrading to 0.81 on macOS and Linux, but the issue still persists.  I would like to know if this issue has been fixed or is it still being worked upon. If it is fixed, how exactly shall I fix it.  Below is the set of parameters I have used.

###                           'silent': 1}

Any help would be highly appreciated.
Thank you

**Comment by hcho3** [comment]
Are you running predictions with the same model? If you are training separate models on two machines, you won't get the same model (in general) even if the training parameters are the same.

To test, save your model on the Linux machine, copy it over to the Mac OSX machine, and run it there.

**Comment by Devarsh-UTD** [comment]
Thank you for the prompt reply.
Yes, I am training separate models. Kindly forgive me, if I am wrong. But if I keep everything same it should ideally give me similar results, no matter what the platform is?. Also, if I wanna get as much similar predictions irrespective of the platform , what shall I do?

**Comment by Devarsh-UTD** [comment]
It also makes me conclude that the MACOS implementation of XGBOOST is better than the Linux one.
Will this conclusion be logical?

**Comment by hcho3** [comment]
> But if I keep everything same it should ideally give me similar results, no matter what the platform is?

We do not make such guarantee. In particular, different platforms may implement random number generation differently.

> Also, if I wanna get as much similar predictions irrespective of the platform , what shall I do?

You should train one model, save it, and re-use the trained model on multiple machines.

> It also makes me conclude that the MACOS implementation of XGBOOST is better than the Linux one.

See my explanation above. Platforms have different implementations for standard C++ libraries, such as random number generation.

**Comment by Devarsh-UTD** [comment]
Thank you.
