### ISSUE TITLE
xgb.cv seems to ignore early_stopping rounds

### ISSUE THREAD

**Issue by JovanVeljanoski** [dmlc/xgboost#4186]
Hi, 

I am using `xgb.cv` and it works great. However today I noticed that if I want to use the `early_stopping_rounds`, it is not obeyed. My guess is that algorithm is somehow using the train scores instead of the test scores to decide when to stop. But with my tests I could not conclude this with certainty. 

Below I include a reproducible example, so you can see what I have tried, and that score (binary cv error) seems to be decreasing still, and it is stopped pre-maturely.  Any help with this would be highly appreciated. 

I installed the latest version of `xgboost` from conda-forge (0.81).

```
import numpy as np
import pandas as pd
import xgboost as xgb
from sklearn import metrics
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split

# Load the data
X, y = load_breast_cancer(return_X_y=True)

# Split in train and test sets
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size=0.1, random_state=42)

# Add them into the format for xgboost native API
dtrain = xgb.DMatrix(data=Xtrain, label=ytrain)
dtest = xgb.DMatrix(data=Xtest, label=ytest)

# Initial guess of the parameters
params = {'learning_rate': 0.1,
          'gamma': 0,
          'max_depth': 5, 
          'min_child_weight': 1, 
          'subsample': 1, 
          'colsample_bytree': 0.5,
          'colsample_bylevel': 1,
          'colsample_bynode': 1,
          'reg_alpha': 0,
          'reg_lambda': 1,
          'tree_method': 'auto',
          'scale_pos_weight': 1, 
          'objective': 'binary:logistic',
          'eval_metric': ['error'],
          'seed': 42,
#           'nthread': 4, 
          'silent': 1,
         }

# Just checking that this works, and reasonably fast so, so we can test this thing in action.
cv_res = xgb.cv(params, dtrain, num_boost_round=1000, nfold=5, stratified=True, maximize=False,
                early_stopping_rounds=10, verbose_eval=False, show_stdv=False, seed=42, shuffle=False)

print(cv_res['train-error-mean'].min(), cv_res['test-error-mean'].min())
print(cv_res)
```

**Comment by hcho3** [comment]
@JovanVeljanoski You should set `verbose_eval` to `True` and see the progress of `test-error`. When I ran your example, training ran up to 26 and the CV table display the 17th iteration, the best iteration.

In the documentation, note that the last entry of the table returned by `xgboost.cv` always corresponds to the best iteration.
