### ISSUE TITLE
xgb.plot.importance clustering of features

### ISSUE THREAD

**Issue by ajkl** [dmlc/xgboost#419]
Is there any real value to cluster-color the plot for the feature influence ?
The plot are normalized on a scale of 100, I think thats good enough to highlight the difference.
My concern is it adds an additional Ckmeans.1d.dp package dependency. 

If color gradient is what we are looking for, we can easily add it using ggplot.

something like -
```
ggplot(dt, aes(x = var, y = rel.inf, fill=rel.inf)) + 
  geom_bar(stat = "identity") +
  coord_flip() +
  scale_fill_gradient(low="#FF8888",high="#FF0000") +
  theme(axis.text.x=element_text(colour="black"),
        axis.text.y=element_text(colour="blue")) +
  theme(text = element_text(size = 20)) 
```

**Comment by pommedeterresautee** [comment]
The idea behind this Viz is to represent pattern of features and help in understanding the model.
Having the cluster information through colors renforce this information. However, I agree we can live without. We can also live without Viz at all :-)

The gradient colors would probably make beautiful Viz, but may not help in understanding information. From the little I know in Viz, it should be as simple as possible, so no need to add colors which doesn't have a meaning.

On the other side, I am not sure to get what is the issue of having one more dependency if it is automatically installed through Cran? Did you experience issues in installing this dependency? If it is the case, then we can try to fix that.

BTW, having ggplot adds several dependencies having themselves their own dependencies and so on.

Kind regards,
Michael

**Comment by ajkl** [comment]
My example was based on ggplot because its already being used in xgb.plot.importance, and the point was not to show off colors but to demonstrate we can achieve the visual distinction using ggplot. Adding an additional dependency just for the visual color distinction feels somewhat an overkill. I was just trying to see if we can optimize it to keep it simple, was not suggesting to use the code snippet i shared :)

**Comment by pommedeterresautee** [comment]
Can you please be more specific about what kind of optimization you are looking for?

**Comment by ajkl** [comment]
I was just thinking out loud if the clustering technique to provide the visual distinctinction (which we somewhat already have with the bars) is needed and if its not completely necessary then we can avoid 1 package dependency. Avoiding external package dependencies where ever possible is also a form of optimization. But I see your reasons are fair too. So you can close the issue if you like.
A tidbid from my experience with gbm - I recently learnt this trick. Include a noise/random variable in the features and it gives a good estimate on what features are important. Anything thats below the noise variable in the gbm importance bar plot are not that influential.

**Comment by pommedeterresautee** [comment]
Regarding the noise feature I thought first it doesn't matter because, unlike RF, in boosting the first features are very high compared to the others (for interpretation purpose I mean).

Reading your comment I realized how nice feature it would be to make **automatic** feature reduction! 
Have you used it? If yes, did you find it useful on real task?

**Comment by ajkl** [comment]
On real datasets my experience has been good on the noise feature, after initial bunch or really high influence variables the lower ones are hard to separate. And this issue started with that in mind, that if we already get a separation which is clear enough do we really need to have the clustering?
Automatic feature reduction sounds interesting but I havent ever tried it on any real world datasets.
