### ISSUE TITLE
can specify feature list for one tree construction or specify maximum feature use frequency?

### ISSUE THREAD

**Issue by lw00245** [dmlc/xgboost#4191]
can specify feature list for one tree construction or specify maximum feature use frequency?

i want to limit one feature maximum usage nums to make the tree not only rely on some features,
or can i specify some feature list to construct tree in gbdt?

**Comment by trivialfis** [comment]
@lw00245 Sorry but I don't quite understand what you are trying to ask.  Let me make some guesses.

> specify feature list for one tree construction

Are you trying to say that you want to supply a different list of selected features for each boosted tree?
- No.  You can't.  One way to do that is boosting one tree at a time and interleave boosting with your feature engineering procedures.

> limit one feature maximum usage nums

Are you trying to say that, after selecting a feature for specified times as split condition, this feature should not be considered afterward?
- No again, we currently don't do the counting.  But this feature can be discussed. :)

**Comment by lw00245** [comment]
> @lw00245 Sorry but I don't quite understand what you are trying to ask. Let me make some guesses.
> 
> > specify feature list for one tree construction
> 
> Are you trying to say that you want to supply a different list of selected features for each boosted tree?
> 
> * No.  You can't.  One way to do that is boosting one tree at a time and interleave boosting with your feature engineering procedures.
> 
> > limit one feature maximum usage nums
> 
> Are you trying to say that, after selecting a feature for specified times as split condition, this feature should not be considered afterward?
> 
> * No again, we currently don't do the counting.  But this feature can be discussed. :)

yeah  all you guess are right,  i hope there will be some call backs which can specify feature list for construct each boost tree,

**Comment by hcho3** [comment]
I opened a new issue to discuss a possible implementation of user-defined split evaluator: #4230
