### ISSUE TITLE
Continue xgboost spark incremental training 

### ISSUE THREAD

**Issue by zyq11223** [dmlc/xgboost#4192]
Appreciate !!
@CodingCat
Could you mind telling me that why xgboost4j python supports incremental learning with an existed ? And xgboost4j python has the interface which can train incrementally .Thanks !

And another questions. I used xgbModel.booster.update API of xgboost spark , it just updates one tree , and with trying to set related params (
xgbModel.booster.setParam("process_type", "update")
xgbModel.booster.setParam("updater", "refresh")
xgbModel.booster.setParam("refresh_leaf", "1")
).
It just also can not update all the trees of the existed model. Are there some api or interface that could solve it ?
Appreciate!!
@hcho3

**Comment by CodingCat** [comment]
don't spam issue list, thanks!

**Comment by zyq11223** [comment]
> don't spam issue list, thanks!

ok, sorry .  I need your help
