### ISSUE TITLE
Cannot use pip to install a local build of xgboost

### ISSUE THREAD

**Issue by kkraus14** [dmlc/xgboost#4195]
Pip currently doesn't follow / materialize relative symlinks as expected: https://github.com/pypa/pip/issues/3500

This prevents running `pip install /path/to/xgboost/python-package`. There also seems to be paths based on where you run the install command from, but I will open a follow-up issue for that.

**Comment by hcho3** [comment]
@kkraus14 I think you can run `pip install bdist_wheel` to create a wheel and then run `pip install xgboost-0.82-*.whl`.

**Comment by hcho3** [comment]
Let's see if we can eliminate symlinks. Given the current way of building wheel artifacts, symlinks may no longer be necessary.

**Comment by hcho3** [comment]
Having symlinks help us create PyPI-compatible wheels, so that `pip install xgboost` can either use pre-compiled libraries under `lib/` or compile from sources under `src/`. So removing symlinks is not practical.
