### ISSUE TITLE
Cannot compile XGBoost on Windows

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#4197]
I just tried compiling XGBoost on a Windows machine and getting this error:
```
"C:\Users\Administrator\Desktop\xgboost\build\xgboost.sln" (default target) (1) ->                                       
"C:\Users\Administrator\Desktop\xgboost\build\gpuxgboost.vcxproj.metaproj" (default target) (4) ->                       
"C:\Users\Administrator\Desktop\xgboost\build\gpuxgboost.vcxproj" (default target) (12) ->                               
   (CustomBuild target) ->                                                                                                 
CUSTOMBUILD : nvcc error : 'cicc' died with status 0xC0000005 (ACCESS_VIOLATION)
[C:\Users\Administrator\Desktop\xgboost\build\gpuxgboost.vcxproj]
```

I'm using EC2 instance (p2.xlarge) with CUDA 8.0, Visual Studio 2015, and Windows 2008 R2.

Compilation command:
```
mkdir build
cd build
cmake .. -G"Visual Studio 14 2015 Win64" -DUSE_CUDA=ON
msbuild xgboost.sln /p:Configuration=Release /m
```

@RAMitchell @mt-jones @trivialfis @rongou

**Comment by hcho3** [comment]
This is part of effort #3868

**Comment by hcho3** [comment]
I'll be focusing on the 0.82 release for the time being. This means that the Python wheel for Windows won't be available right away.

**Comment by RAMitchell** [comment]
I will have a look in the next couple of days

**Comment by hcho3** [comment]
@RAMitchell Hmm, I tried using another Windows EC2 image I had, and XGBoost compiles successfully on that machine. This should be good enough for 0.82 release.
