### ISSUE TITLE
Using ntree_limit for XGBRegressor.predict() 

### ISSUE THREAD

**Issue by yychenca** [dmlc/xgboost#420]
It's great that the newer version of xgboost.py hadded early stopping to XGBRegressor and XGBClassifer. However when trying to apply best iteration for prediction I realized the predict function didn't accept ntree_limit as a parameter. Here's my workaroud:

    def predict(self, data, ntree_limit=0):
        # pylint: disable=missing-docstring,invalid-name
        test_dmatrix = DMatrix(data, missing=self.missing)
        return self.booster().predict(test_dmatrix, ntree_limit = ntree_limit)

Let me know if that makse sense to you.

Thanks,

Chris Chen

**Comment by tqchen** [comment]
Yes, this makes perfect sense to me, you can also add output_margin, which is another option possible for booster model. 
Please open a PR on this.

**Comment by mkurnikov** [comment]
AFAIK, sklearn API doesn't permit to add additional parameters to predict(self, X) method. It will break all Pipeline machinery, and other stuff. Also, possibility of creating special method, for example, predict_best(self, X) isn't an option either for aforementioned reasons. 

I see it as an additional parameter to fit() method, like predict='best' / 'last' and validations for enabled early_stopping inside. Is it OK to implement it this way?

**Comment by tqchen** [comment]
does this also involve the default parameter? I think we want to have
predict support these, add default, and specify default prediction behavior
in constructor of the model.

**Comment by mkurnikov** [comment]
I'm not sure that I understand you correctly. Do you mean predict(self, X, ntree_limit='best'), so ntree_limit would have default value 'best'? 
It will work for a direct calling of XGBRegressor().predict(), but I mostly use sklearn classifiers as part of nested Pipeline objects, which aren't able to forward additional arguments down the heirarchy.

**Comment by tqchen** [comment]
I mean implement the predict with ntree limit with a default value that is
stored in the Model. So predict function allows user to specify these
optional parameters in normal use case. In pipeline, predict is called with
default parameter for ntree limit. Which defaults to behavior stored in the
object
