### ISSUE TITLE
Wish-List: support lme4 extensions

### ISSUE THREAD

**Issue by bachlaw** [dmlc/xgboost#421]
It would be great to perform multilevel modeling using xgboost to resolve the fixed effects level of the equation.  lme4 has an extensions framework that allows other, non-linear methods to run the grouping variable assignment process on top of the underlying regression method.  See, for example, R package blmer.

**Comment by walterreade** [comment]
+1

**Comment by 121onto** [comment]
Not 100% on what this comment is about.  Am I correct that you can do fixed effects with xgboost (assuming they enter linearly) by transforming you data before and after fitting?

```{python}
geo_means = train.groupby('geo').transform(np.mean)
time_means = train.groupby('time').transform(np.mean)
overall_means = train.groupby('const').transform(np.mean)

train_within = train - geo_means - time_means + overall_means
# de-mean test

dtrain_within = DMatrix(train_within.drop('label',axis=1,inplace=True).values, label=train_within['label'].values)
model = xgb.train(params,dtrain_within,...)
predictions = model.predict(dtest_within)

# add means back to predictions
```

**Comment by tqchen** [comment]
https://github.com/dmlc/xgboost/issues/749
