### ISSUE TITLE
calc again

### ISSUE THREAD

**Issue by jkingfu** [dmlc/xgboost#4210]
snode_[nid].weight,snode_[nid].root_gain alway dup process stat, but have in parent left_sum and right_sum

in src/tree/updater_colmaker.cc InitNewNode

**Comment by hcho3** [comment]
The duplicate computation is to take account of the scaling by `learning_rate`.

**Comment by jkingfu** [comment]
const MetaInfo& info = fmat.Info();
      // setup position
      const auto ndata = static_cast<bst_omp_uint>(info.num_row_);
      #pragma omp parallel for schedule(static)
      for (bst_omp_uint ridx = 0; ridx < ndata; ++ridx) {
        const int tid = omp_get_thread_num();
        if (position_[ridx] < 0) continue;
        stemp_[tid][position_[ridx]].stats.Add(gpair[ridx]);
      }   
      // sum the per thread statistics together
      for (int nid : qexpand) {
        GradStats stats;
        for (auto& s : stemp_) {
          stats.Add(s[nid].stats);
        }   
        // update node statistics
        snode_[nid].stats = stats;
      }   
      // calculating the weights
      for (int nid : qexpand) {
        bst_uint parentid = tree[nid].Parent();
        snode_[nid].weight = static_cast<float>(
            spliteval_->ComputeWeight(parentid, snode_[nid].stats));
        snode_[nid].root_gain = static_cast<float>(
            spliteval_->ComputeScore(parentid, snode_[nid].stats, snode_[nid].weight));
      } 

in above code, no refer learning_rate, please detail

**Comment by hcho3** [comment]
Please see #4015.
