### ISSUE TITLE
GBLinear model dump has wrong bias value

### ISSUE THREAD

**Issue by AtR1an** [dmlc/xgboost#4215]
Hello XGBoost-Team,

I stumbled across an oddity related to the linear booster.
As I test I created a dataset that follows y = 3*x + 1 and trained a linear model.
A plot of the predicted values shows that the model perfectly learned the function, however, if I look at the model dump, I get a bias value of approximately 0.5 which is strange since the predictions are correct.

This behavior appears both for the Python as well as the Java API.
Python example:

```
import xgboost as xgb
import numpy as np

x = np.linspace(-100, 100, num=1000).reshape([1000, 1])
y = 3 * x + 1

dtrain = xgb.DMatrix(x, label=y)

param = {'booster': 'gblinear'}

bst = xgb.train(param, dtrain, num_boost_round=1000)

print(bst.get_dump())
```

Am I misunderstanding something?

Kind regards,

AtR1an

**Comment by hcho3** [comment]
There is a parameter called `base_score`, which adds the same number to all predictions. By default, `base_score` is set to 0.5. Try setting this parameter to 0; you should then get bias 1.
