### ISSUE TITLE
Use feature interaction constraints to narrow search space for split candidates.

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#4217]
See https://github.com/dmlc/xgboost/issues/4075#issuecomment-469751693. In the split finding step, we currently enumerate all features:
https://github.com/dmlc/xgboost/blob/5f34078fba1b489009ed80899961c50229070732/src/tree/updater_quantile_hist.cc#L542-L554
The feature interaction constraints kick in only after we evaluate all split candidates.

We should take advantage of feature interaction constraints (if given) and preemptively narrow the search space in feature dimension. TODO: evaluate possible speedup.

**Comment by sperlingxx** [comment]
I am trying to fix it in #4341
