### ISSUE TITLE
[jvm-packages] Spylon-kernel java.lang.ClassCastException: ml.dmlc.xgboost4j.scala.Booster cannot be cast to ml.dmlc.xgboost4j.scala.Booster

### ISSUE THREAD

**Issue by TarasDerevianko** [dmlc/xgboost#4218]
I was using https://jar-download.com/artifacts/ml.dmlc/xgboost4j-spark/0.82/source-code for run scala spark xgboost example https://github.com/dmlc/xgboost/blob/master/jvm-packages/xgboost4j-example/src/main/scala/ml/dmlc/xgboost4j/scala/example/spark/SparkTraining.scala on yarn cluster

spark.version = 2.4.0
scala version = 2.11.6 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_181).
spylon-kernel = 0.4.1 

1. config and start spark context

> %%init_spark
> launcher.master = "yarn"
> launcher.conf.set("spark.app.name", "scalaXgbTest")
> launcher.num_executors = 3
> launcher.executor_cores = 7
> launcher.conf.spark.task.cpus = 6
> launcher.driver_memory = '4g'
> launcher.executor_memory = '4g'
> launcher.verbose = 'true'
> launcher.conf.set("spark.executor.heartbeatInterval", "6000s")
> launcher.conf.set("spark.yarn.scheduler.heartbeat.interval-ms", "10000s")
> launcher.conf.set("spark.network.timeout", "10000s")
> launcher.conf.set("spark.yarn.executor.memoryOverhead", "8192")
> launcher.conf.set("spark.sql.catalogImplementation", "hive")
> launcher.jars = ["xgboost-maven-0.82/xgboost4j-spark-0.82.jar", "xgboost-maven-0.82/xgboost4j-0.82.jar"]

2. import library 

> import ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier
> import org.apache.spark.ml.feature.{StringIndexer, VectorAssembler}
> import org.apache.spark.sql.types.{DoubleType, StringType, StructField, StructType}

3. load and transform data (Iris dataset (https://archive.ics.uci.edu/ml/datasets/iris))

> val inputPath = "/tmp/td/tmp/iris.data.txt"
>   val schema = new StructType(Array(
>   StructField("sepal length", DoubleType, true),
>   StructField("sepal width", DoubleType, true),
>   StructField("petal length", DoubleType, true),
>   StructField("petal width", DoubleType, true),
>   StructField("class", StringType, true)))
> val rawInput = spark.read.schema(schema).csv(inputPath)
> 
> // transform class to index to make xgboost happy
> val stringIndexer = new StringIndexer()
>   .setInputCol("class")
>   .setOutputCol("classIndex")
>   .fit(rawInput)
> val labelTransformed = stringIndexer.transform(rawInput).drop("class")
> 
> // compose all feature columns as vector
> val vectorAssembler = new VectorAssembler().
>   setInputCols(Array("sepal length", "sepal width", "petal length", "petal width")).
>   setOutputCol("features")
> val xgbInput = vectorAssembler.transform(labelTransformed).select("features",
>   "classIndex")

4. define xgboost parameters and fit model

> val Array(train, eval1, eval2, test) = xgbInput.randomSplit(Array(0.6, 0.2, 0.1, 0.1))
>   val xgbParam = Map(
>     "eta" -> 0.1f,
>     "max_depth" -> 2,
>     "objective" -> "multi:softprob",
>     "num_class" -> 3,
>     "num_round" -> 100,
>     "num_workers" -> 2,
>     "timeoutRequestWorkers" -> 6000L,
>     "eval_sets" -> Map("eval1" -> eval1, "eval2" -> eval2))
> 
> val xgbClassifier = new XGBoostClassifier(xgbParam).
>   setFeaturesCol("features").
>   setLabelCol("classIndex")
> val xgbClassificationModel = xgbClassifier.fit(train)

I get the following error after ~1m
`Tracker started, with env={DMLC_NUM_SERVER=0, DMLC_TRACKER_URI=XXX.XXX.XX.XX, DMLC_TRACKER_PORT=9093, DMLC_NUM_WORKER=2}
java.lang.ClassCastException: ml.dmlc.xgboost4j.scala.Booster cannot be cast to ml.dmlc.xgboost4j.scala.Booster
  at ml.dmlc.xgboost4j.scala.spark.XGBoost$.ml$dmlc$xgboost4j$scala$spark$XGBoost$$postTrackerReturnProcessing(XGBoost.scala:499)
  at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$1.apply(XGBoost.scala:404)
  at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$1.apply(XGBoost.scala:381)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.immutable.List.foreach(List.scala:392)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
  at scala.collection.immutable.List.map(List.scala:296)
  at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainDistributed(XGBoost.scala:380)
  at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:196)
  at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:48)
  at org.apache.spark.ml.Predictor.fit(Predictor.scala:118)
  ... 37 elided`

**Comment by CodingCat** [comment]
XGBoost does not support 2.4 now

**Comment by TarasDerevianko** [comment]
what versions of spark support xgboost4j-spark 0.82?

what versions of spark support xgboost4j-spark 0.81?

**Comment by hcho3** [comment]
@CodingCat So only Spark 2.3.x is supported?

**Comment by CodingCat** [comment]
Yes, both 2.3.x...once 2.4.1 is released, i will do cross version support

**Comment by hcho3** [comment]
@CodingCat If there is a significant difference between 2.3.x and 2.4.x, we should set up a CI pipeline to perform checks.

**Comment by CodingCat** [comment]
Yes, I noticed several issues when users mixed 2.3 and 2.4 models (haven’t look into details)

That’s what I mean by “cross version support” and want to address in that scope
