### ISSUE TITLE
[jvm-packages] missing parameter problems in xgboost-spark

### ISSUE THREAD

**Issue by adobay** [dmlc/xgboost#4227]
features that are not presented in the sparse feature matrix are treated as ‘missing’ on xgboost-spark, while spark ml vectorAssembler determines dense or sparse on storage cost. so for rows of dense,its 'missing' is NaN, for rows of sparse, its NaN and 0.

**Comment by hcho3** [comment]
Can you post a small example where this become a problem?

**Comment by adobay** [comment]
import org.apache.spark.ml.feature.VectorAssembler
val vectorAssembler = new VectorAssembler().
  setInputCols(Array("sepal length", "sepal width", "petal length", "petal width")).
  setOutputCol("features")
val xgbInput = vectorAssembler.transform(labelTransformed).select("features", "classIndex")

this is the example on https://xgboost.readthedocs.io/en/latest/jvm/xgboost4j_spark_tutorial.html.
after transform, in xgbInput, some rows will be denseVector, some rows will be sparseVector.
the same data in the two different formats will produce different result.

**Comment by hcho3** [comment]
@adobay Try setting `missing` parameter to 0.

@CodingCat This thread reminds me of #3634. Can we add a note about missing value handling to the XGBoost4J-Spark tutorial?

**Comment by CodingCat** [comment]
it might be a problem in terms of usability

but how the same data is interpreted differently by VectorAssembler?

**Comment by adobay** [comment]
this is the compressed code in spark ml:
def compressed: Vector = {
    val nnz = numNonzeros
    // A dense vector needs 8 * size + 8 bytes, while a sparse vector needs 12 * nnz + 20 bytes.
    if (1.5 * (nnz + 1.0) < size) {
      toSparseWithSize(nnz)
    } else {
      toDense
    }
  }

my suggestion is that XGBoost4J-Spark read sparseVector just like denseVector, read in 0, not as missing.

**Comment by adobay** [comment]
@CodingCat @hcho3

**Comment by CodingCat** [comment]
With the above code, how spark can interpret the same data into, sometimes dense and sometimes sparse?

**Comment by adobay** [comment]
//for each row, vectorAssembler call the assembleFunc
val assembleFunc = udf { r: Row =>
      VectorAssembler.assemble(lengths, keepInvalid)(r.toSeq: _*)
    }.asNondeterministic()

//the last row creates Sparse or Dense vector depending how many non-zero values 
private[feature] def assemble(lengths: Array[Int], keepInvalid: Boolean)(vv: Any*): Vector = {
   ...
    //the last row...
    Vectors.sparse(featureIndex, indices.result(), values.result()).compressed
  }

**Comment by CodingCat** [comment]
let me ask in this way , you said

```
the same data in these two different formats will produce different results because of different 'missing' parameters.
e.g.
[0, 10, 0, 8]
sparseVector will be [missing, 10, missing, 8]
denseVector will be [0, 10, 0, 8]
```

this is not true, [0,10,0,8] can only be interpreted as dense, right?
