### ISSUE TITLE
xgb.rabit.finalize() for distributed training

### ISSUE THREAD

**Issue by hiyangbo** [dmlc/xgboost#4229]
Hi folks,

I am thinking about using following python code to do xgboost training.
Can someone educate me if I miss anything here?
Basically the idea is to shard the data and each worker takes their own piece of data and then use rabit to finalize. 
Looks too simple to me so I am wondering what's the advantage of xgboost4j-spark compared to the simple version?
     
        xgb.rabit.init()
        rabit.start(num_workers)
        bst = xgb.train(bst_param, dtrain, num_round, evals=xgb_evals, verbose_eval=True)
        xgb.rabit.finalize()

    if is_master_node:
      bst.save_model(LOCAL_XGBOOST_MODEL_FILE)

**Comment by CodingCat** [comment]
Xgb-spark is made for reducing your overhead of transforming data, so you can write a single spark job for both preprocessing and learning...plus the benefits from Spark ML API

And it covers all distributed headaches for you (you do not need to care about how to use rabit)

**Comment by thvasilo** [comment]
Agree with @CodingCat here, unless you're solving a research problem it's very likely you'll want to do some data pre-processing before. If you absolutely want to avoid Spark and your data is already ready for training, you could use S3 or HDFS to store your data in a distributed filesystem, then train with XGB as normal, no need to do your own sharding or worry about rabit.
