### ISSUE TITLE
[RFC] Custom (user-defined) split evaluator

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#4230]
Previous works on monotonic constraints and feature interaction constraints created a general framework for evaluating split candidates (#3335, #3429, #3466).

It would be nice to allow the user to write a custom method for split evaluation. See #4137, #4191, #3923.

This thread is a place-holder for discussing ideas.

**Comment by hcho3** [comment]
@trivialfis I recall you saying that split evaluator should be replaced with something simpler in https://github.com/hcho3/xgboost-json-schema/issues/3#issuecomment-446516684. Any comments on this proposal?

**Comment by trivialfis** [comment]
@hcho3 let me see if I can work out something that fits both CPU and CUDA.  I spent a whole day trying to fix the broken CUDA on my machine...

**Comment by hcho3** [comment]
https://discuss.xgboost.ai/t/how-to-tell-xgboost-model-that-2-features-are-related-and-should-not-be-interpreted-stand-alone/1172?u=hcho3

**Comment by trivialfis** [comment]
I don't think we will support this kind of customization as this is deep in the core of XGBoost.
