### ISSUE TITLE
External memory cache files are not updated between runs

### ISSUE THREAD

**Issue by thvasilo** [dmlc/xgboost#4237]
Encountered this while trying to test external memory training for [this issue](https://discuss.xgboost.ai/t/model-does-not-train-on-data-in-external-memory/712) on the discussion board.

I was trying to train on RCV1 which by originally has the +1/-1 labels, causing XGB to crash with an error.
I fixed this and pointed to the new file, however the cache files where unchanged, so when I tried to train I got the same error.

This is because the cache files had already been created from my previous run, and when I ran the algo again, they were not generated again. I assume this is expected behavior, but thought we might want to mention that in the tutorial or something to avoid having users train on stale data (or even the wrong dataset) in case they re-use the same cache file names.

Meaning that once you run:

`dtrain = xgb.DMatrix("data/rcv1/data.test#dtrain.cache")`

then running 

`dtrain = xgb.DMatrix("data/another-dataset/data.test#dtrain.cache")` on a separate run will result in training on the old (RCV1) data unless the dtrain.cache files are deleted.

Are the external memory cache files supposed to be removed automatically at training end?

**Comment by trivialfis** [comment]
@thvasilo After digging a lot into XGBoost,  I'm still not familiar with external memory ... I will try having a complete understanding of it before next release hits.

**Comment by RAMitchell** [comment]
I ran into this problem also when I was playing with external memory. You have to manually delete the cache files between runs, otherwise it will silently continue to use previous cache files and produce incorrect results with no warning (!!).

I can see two ways of solving this:
- generate unique cache files for each run
- cleanup cache files in the dmatrix destructor

Option two is preferred so we don't fill up the systems memory. We should be very careful when deleting files though.

**Comment by rongou** [comment]
This is a "feature" to avoid generating the cache files over and over as they are pretty expensive to write out for large datasets. It's this line here: https://github.com/dmlc/xgboost/blob/095de3bf5f9febba9908637197873630021c733a/src/data/data.cc#L265

We can get rid of that line, but I'm not sure if existing users might expect that caching behavior. A few possible solutions:
1. Don't cache the row pages between runs.
1. Add some configuration parameter to keep/delete caches.
1. Somehow be smart and make sure the source data files haven't changed. For example, maybe we can keep some kind of hash of the source data in `MetaInfo`, or check the timestamps of source data and cache files.

My vote is 1. What do you guys think?

@thvasilo @trivialfis @RAMitchell

**Comment by thvasilo** [comment]
Is option 1 to delete the cache files at the end of training?

Is it possible to create cache files that are named after the input
dataset, ideally under the same directory?

--

**Comment by RAMitchell** [comment]
I came across this too some time ago. What kind of performance penalty will be talking about to regenerate the cache files vs. not?

I think current behaviour to keep the files is quite unusual. I would expect most apps that I use to clean up temporary files and not leave a bunch of potentially large files around.

Deleting them seems the way to go.

**Comment by rongou** [comment]
If we simply delete that line I mentioned, the files will be left on disk after training, but next time you train again they'll be regenerated.

With the current behavior, you can create different cache files by specifying a different path, e.g.
* `dataset1.libsvm#cache1`
* `dataset2.libsvm#cache2`
* ...

@sriramch might have some numbers on how long it takes to write out a large dataset.

**Comment by sriramch** [comment]
in part, it depends on where the cache files are being written to. if it is being written to tmpfs, it is faster compared to writing them to a spinning disk. that said, from what i could dig from my old notes, it was ~ 27s (to generate the cache files) for the higgs dataset (near dense), while it was ~20s to generate the cache file for the mortgage set (which is quite sparse) for ~ 140m rows.

**Comment by RAMitchell** [comment]
Did we come up with a consensus here? I would like to delete cache files at the end of each run and remove the `CacheExist` line.

**Comment by rongou** [comment]
Sounds good to me.
