### ISSUE TITLE
Create C API doc and tutorial

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#4240]
I have seen multiple users asking for an example of C API usage. Documentation would be useful for people wanting to use XGBoost from a C++ program.

- [x] Generate API doc for C API functions
- [ ] Add an option in CMake to build a static library instead of shared
- [x] Create a tutorial with an end-to-end example
- [x] Export proper cmake install targets
- [x] Remove all deprecated functions

**Comment by trivialfis** [comment]
@hcho3 For exposing C APIs:

- [ ] Export proper cmake install targets.
- [ ] Remove all deprecated functions.

**Comment by hcho3** [comment]
@trivialfis Do we want to add an option to build a static library? Is it possible to build static libs with CUDA?

**Comment by trivialfis** [comment]
Haven't try it yet.  What's the benefit of using static library?

**Comment by hcho3** [comment]
You can statically link XGBoost with your application, so that you can distribute one binary instead of two.

**Comment by trivialfis** [comment]
@hcho3 I think it's possible, but there are always surprises.  Just replace `add_library(xgboost SHARED)` with `add_library(xgboost STATIC)` and remove `-fPIC` flags.  I think this is mostly for Windows users and I don't have access to a Windows machine for now, so will leave it to others who can test it.

**Comment by hcho3** [comment]
Will keep track of progress on static library in #4483
