### ISSUE TITLE
tag v0.82 missing update version numbers commit 

### ISSUE THREAD

**Issue by jsnchen** [dmlc/xgboost#4243]
Just built xgboost with gpu support using tag v0.82. 
However, the python package version is still showing 0.81.

Looks like the tag is cut before the version number commit:
https://github.com/dmlc/xgboost/commit/2f218fc4be980dd341012c99e7baf3b7e970daa3

**Comment by hcho3** [comment]
@jsnchen Yeah, sorry about that. It’s a mistake on my part. Unfortunately, there is nothing I can do, since history rewriting is not allowed.

**Comment by hcho3** [comment]
You can use release_0.82 branch, which has correct version number. Alternatively, you can use pre-built Python wheels.

**Comment by jsnchen** [comment]
Thanks.  I have used the release branch to build.
