### ISSUE TITLE
0.82 feature_importances_ function of sklearn wrapper

### ISSUE THREAD

**Issue by freelectron** [dmlc/xgboost#4256]
`XGBClassifier` class  of `xgboost.sklearn` cannot call `importance_type` property in the new release. 
So basically, I can not do 

``` python
xgb = xgboost.XGBClassifier(**some_params)
xgb.fit(X,Y)
xgb.feature_importances_
```
it gives: 

 File "....../python3.7/site-packages/xgboost/sklearn.py", line 525, in feature_importances_
    score = b.get_score(importance_type=self.importance_type)
AttributeError: 'XGBClassifier' object has no attribute 'importance_type'

Probably a quick fix.
Thanks for everything.

**Comment by hcho3** [comment]
That's weird, since `importance_type` attribute is set here:
https://github.com/dmlc/xgboost/blob/b833b642eca0cc4e3975958ba093d0d8cd25c4ea/python-package/xgboost/sklearn.py#L169

**Comment by hcho3** [comment]
I just tried it on my machine and was not able to re-produce it. Can you re-install XGBoost by running `pip install xgboost==0.82`?

**Comment by freelectron** [comment]
hm, you are right. I am sorry for wasting your time. it was indeed an issue with my xbgoost build. 
Thanks!
