### ISSUE TITLE
Result not reproducible in different machine

### ISSUE THREAD

**Issue by hetong007** [dmlc/xgboost#426]
It is reproducible by the following code :

```r
require(xgboost)

set.seed(42)
x = matrix(rnorm(10000), 2000, 5)
y = rnorm(2000)

set.seed(42)
m1 = xgboost(data = x, label = y, nrounds = 5, nthread = 1)

set.seed(43)
m1 = xgboost(data = x, label = y, nrounds = 5)
```

Two observations:

1. On different machines, the results under the same seed setting are different.
2. Changing the seed doesn't change the result.

**Comment by sh1ng** [comment]
I've notice the same issue with python 
on mac os and linux(ubuntu)

**Comment by sjain777** [comment]
Hi, was this problem resolved, or is it still the case that results are different on different machines even with the same seed? Thanks
