### ISSUE TITLE
[jvm-packages] missing LabeledPoint.java

### ISSUE THREAD

**Issue by benjamincitrin** [dmlc/xgboost#4261]
I am using the pure Java packages, not Scala/Spark/Flink.  

DataBatch.java heavily relies on an import: 
`import ml.dmlc.xgboost4j.LabeledPoint;`

However, LabeledPoint.java does not exist.  My fix was to manually create a LabeledPoint.java file

**Comment by benjamincitrin** [comment]
`package ml.dmlc.xgboost4j;

import java.io.Serializable;

/**
 * Labeled data point for training examples.
 * Represent a sparse training instance.
 */
public class LabeledPoint implements Serializable {
  /** Label of the point */
  public float label;
  /** Weight of this data point */
  public float weight = 1.0f;
  /** Feature indices, used for sparse input */
  public int[] indices = null;
  /** Feature values */
  public float[] values;

  public LabeledPoint() {}


public LabeledPoint(float ffloat, int[] intArray, float[] floatArray) {
	System.out.println("test");
	fromSparseVector(ffloat, intArray, floatArray);
}


/**
   * Create Labeled data point from sparse vector.
   * @param label The label of the data point.
   * @param indices The indices
   * @param values The values.
   */
  public static LabeledPoint fromSparseVector(float label, int[] indices, float[] values) {
	  
    LabeledPoint ret = new LabeledPoint();
    ret.label = label;
    ret.indices = indices;
    ret.values = values;
    assert indices.length == values.length;
    return ret;
  }

  /**
   * Create Labeled data point from dense vector.
   * @param label The label of the data point.
   * @param values The values.
   */
  public static LabeledPoint fromDenseVector(float label, float[] values) {
    LabeledPoint ret = new LabeledPoint();
    ret.label = label;
    ret.indices = null;
    ret.values = values;
    return ret;
  }
  
}`

**Comment by benjamincitrin** [comment]
package ml.dmlc.xgboost4j;

import java.io.Serializable;

/**
 * Labeled data point for training examples.
 * Represent a sparse training instance.
 */
public class LabeledPoint implements Serializable {
  /** Label of the point */
  public float label;
  /** Weight of this data point */
  public float weight = 1.0f;
  /** Feature indices, used for sparse input */
  public int[] indices = null;
  /** Feature values */
  public float[] values;

  public LabeledPoint() {}


public LabeledPoint(float ffloat, int[] intArray, float[] floatArray) {
	System.out.println("test");
	fromSparseVector(ffloat, intArray, floatArray);
}


/**
   * Create Labeled data point from sparse vector.
   * @param label The label of the data point.
   * @param indices The indices
   * @param values The values.
   */
  public static LabeledPoint fromSparseVector(float label, int[] indices, float[] values) {
	  
    LabeledPoint ret = new LabeledPoint();
    ret.label = label;
    ret.indices = indices;
    ret.values = values;
    assert indices.length == values.length;
    return ret;
  }

  /**
   * Create Labeled data point from dense vector.
   * @param label The label of the data point.
   * @param values The values.
   */
  public static LabeledPoint fromDenseVector(float label, float[] values) {
    LabeledPoint ret = new LabeledPoint();
    ret.label = label;
    ret.indices = null;
    ret.values = values;
    return ret;
  }
  
}

**Comment by benjamincitrin** [comment]
Not sure if this should remain open or closed, so please mark accordingly

**Comment by hcho3** [comment]
The XGBoost Java package uses LabeledPoint.scala, so no need to write LabeledPoint.java
