### ISSUE TITLE
Suppression of Rabit output in xgboost4j

### ISSUE THREAD

**Issue by harrybraviner** [dmlc/xgboost#4263]
I've found that the logging of the performance from every training round fills up my screen and prevents me from spotting important messages that happen elsewhere in my code. This is particularly severe in problems where I train multiple boosters (e.g. for K-fold cross validation). I have not discovered any option that suppresses this output at present, and inspection of `Booster.java` suggests that no option does so (since the `Rabit.trackerPrint` is not wrapped in any test, nor does it get passes the parameter map, so there's no way it can be doing any test internally).

Further, the `"silent" -> "1"` entries in the scala tests suggest that being able to suppress this output is intended. I've open a PR (#4262) with a fix for this, allowing either silencing of output or limiting it to once every `n` training iterations.

**Comment by CodingCat** [comment]
fixed by https://github.com/dmlc/xgboost/pull/4262
