### ISSUE TITLE
Mark CUDA 10.1 as unsupported.

### ISSUE THREAD

**Issue by trivialfis** [dmlc/xgboost#4264]
Issue is the same in  #4223.  Spliter of NVCC might have some problems with pointers, running this in `HostDeviceVectorImpl::Copy`:

``` c++
      LOG(DEBUG) << "other->Distribution(): " << other->Distribution();
      LOG(DEBUG) << "other.Distribution(): " << (*other).Distribution();
```
returns different result.  The bug should be reproducible by simply running unittests with CUDA 10.1 on Ubuntu 18.10.  Instead of working around it like the last time I did, I think it's more appropriate to explicitly mark CUDA 10.1 is not being supported, or at least we need to mark the nvcc included in CUDA 10.1 is not supported.

Sadly, it's currently the only version that doesn't break my machine ... @RAMitchell WDYT?

**Comment by RAMitchell** [comment]
Yes we may have to wait for another cuda update. Do what you think is best.

**Comment by hcho3** [comment]
@trivialfis I was about to include CUDA 10.1 as one of the targets in my upcoming PR for CI refactor. Should we leave it out for the time being?

**Comment by trivialfis** [comment]
@hcho3 yes.  Let's skip this version.

**Comment by rongou** [comment]
This problem seems to be specific to gcc. I tried clang-7, it seems to work fine.

**Comment by trivialfis** [comment]
@rongou I'm not sure how did you compile XGBoost with clang, assuming you are referring to the non-apple clang.  There was a type deduction in dmlc core logging facility which tricks clang-7.

**Comment by rongou** [comment]
@trivialfis not sure, I built the jvm packages with cuda enabled using clang-7 and it seems to run fine. What is the logging issue? Maybe it only affects cli or python?

**Comment by trivialfis** [comment]
@rongou Drap to the bottom of `clang-tidy` test: https://xgboost-ci.net/blue/organizations/jenkins/xgboost/detail/PR-4149/12/pipeline

The type of `&std:free` can not be deduced.  Same with `clang`.  The problem might be in `std::free` implementation if you are using `libc++` instead of `libstdc++`.  ; )

**Comment by rongou** [comment]
Yeah I installed libc++ when I installed clang-7. I guess clang uses it by default? If you are using clang-tidy, maybe it's not a crazy idea to go all in with clang.

Anyway, the CUDA bug should be fixed in the next patch update, if all goes well.

**Comment by jamesdalg** [comment]
If it's possible, can someone post some detailed documentation as to how to work around this issue with visual studio 2017 and cmake, with any version that works currently?

**Comment by rongou** [comment]
You can use CUDA 10.0: https://developer.nvidia.com/cuda-10.0-download-archive
