### ISSUE TITLE
xgboost under anaconda

### ISSUE THREAD

**Issue by dmiljkovic** [dmlc/xgboost#427]
Hi there,

I am using Anaconda python distribution. What would be procedure to install xgboost under Anaconda.

Thanks

Dejan

**Comment by tqchen** [comment]
It should be the same procedure as normal installations I assume

**Comment by msampathkumar** [comment]
You may try pip, which is available in Anaconda Package. 

Tool > Open Command Prompt
<pre>C:\Anaconda3\Scripts>dir pip*
.....
02/12/2015  11:02 PM                94 pip-script.py
02/12/2015  11:02 PM            74,752 pip.exe
               2 File(s)         74,846 bytes
               0 Dir(s)  228,624,748,544 bytes free</pre>

**Comment by gblasius** [comment]
I am using Anaconda python on Mac OS X.   The instructions were sufficient.

**Comment by shashankchaudhry** [comment]
Same here, I was using anaconda on Mac OS X too. I just followed the given instructions and faced no issues.

**Comment by WangHanbin** [comment]
`pip install xgboost` works well for me. Followed the given instructions maybe faced some **Permission deny** issues, it depends on the way you installed Anaconda.

**Comment by viv1ag** [comment]
Please let me know how to rectify this issue:
![image](https://cloud.githubusercontent.com/assets/878291/13805866/ea744b14-eb7d-11e5-833d-c6f7c947375e.png)

When I am trying conda then following error is coming:
![image](https://cloud.githubusercontent.com/assets/878291/13805882/04ea4f02-eb7e-11e5-9027-9deb75ee0e23.png)

I have Window 7 Enterprises 64 bits, Python 2.7 & Anaconda 2 on my system.

**Comment by PeterJacob** [comment]
@viv1ag I have exactly the same problem.

**Comment by petermartigny** [comment]
Same issue on Windows 10, @viv1ag

**Comment by phunterlau** [comment]
we don't maintain a pip or conda installation for Windows, as mentioned in the installation instruction. Please use github installation instead.

**Comment by jxlijunhao** [comment]
conda install -c aterrel xgboost=0.4.0

**Comment by billtrowbridge** [comment]
Conda installation is available now.

> conda install py-xgboost
or
> conda install r-xgboost

for python or R respectively
