### ISSUE TITLE
Can I have an example for xgboost run on kubernets

### ISSUE THREAD

**Issue by AmberCheng** [dmlc/xgboost#4270]
I cannnot run a distribute example on kubernets...

**Comment by hcho3** [comment]
@AmberCheng See https://github.com/kubeflow/examples/tree/master/xgboost_ames_housing

**Comment by AmberCheng** [comment]
> @AmberCheng See https://github.com/kubeflow/examples/tree/master/xgboost_ames_housing

Hi,  thanks for your reply. However I find that this example does not look like a distribute training. It more likes a standalone one, as I read the content in the yaml file.

**Comment by hcho3** [comment]
My bad.

**Comment by hcho3** [comment]
@AmberCheng There is now a proposal for the XGBoost operator in Kuberflow: kubeflow/community#247.

**Comment by hcho3** [comment]
@AmberCheng We now have a tutorial for running distributed XGBoost training on Kubernetes cluster: https://xgboost.readthedocs.io/en/latest/tutorials/kubernetes.html
