### ISSUE TITLE
`ngroup=0` when using `xgb_model.pred(pred_interactions=True)`

### ISSUE THREAD

**Issue by kyoungrok0517** [dmlc/xgboost#4276]
Related: https://github.com/slundberg/shap/issues/464

---

**Problem**
I get the following error when I use `pred_interactions=True` to get the feature interaction. The error occurs when reshaping the result array, and I suspect this is because the `ngroup` (2nd axis of `(35255,0,601,601)`) becomes 0, which seems to be an error. 

```sh
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-14-6baa08e16bb5> in <module>()
----> 1 preds = model.predict(dtest, pred_contribs=True, approx_contribs=True, pred_interactions=True)

~/anaconda/lib/python3.6/site-packages/xgboost/core.py in predict(self, data, output_margin, ntree_limit, pred_leaf, pred_contribs, approx_contribs, pred_interactions, validate_features)
   1237                     preds = preds.reshape(nrow, data.num_col() + 1, data.num_col() + 1)
   1238                 else:
-> 1239                     preds = preds.reshape(nrow, ngroup, data.num_col() + 1, data.num_col() + 1)
   1240             elif pred_contribs:
   1241                 ngroup = int(chunk_size / (data.num_col() + 1))

ValueError: cannot reshape array of size 148317785 into shape (35255,0,601,601)
```

**Comment by kyoungrok0517** [comment]
Here's necessary files for testing.

* [Model](https://www.dropbox.com/s/m0nd7scqtr1xhvr/model_dense.pkl?dl=0)
* [Data](https://www.dropbox.com/s/m0nd7scqtr1xhvr/model_dense.pkl?dl=0)
* [Script](https://www.dropbox.com/s/s5bbvymko251l2q/SHAP_Analysis_For_Report.py?dl=0)

**How to run**
`python SHAP_Analysis_For_Report.py ./model_dense.pkl ./test.dmatrix`

**Comment by rnarukulla2** [comment]
I have the same error while I am loading the xgboost model which is built using CLI interface. Can some one body help

**Comment by hcho3** [comment]
Related: https://discuss.xgboost.ai/t/scala-spark-xgboost-v0-81-shap-problem/817/3

**Comment by kyoungrok0517** [comment]
So the devs are not interested in this problem?

**Comment by hcho3** [comment]
@kyoungrok0517 Sorry I didn't have a chance to look at this. We have a backlog of issues currently, and are trying to address them when we are able to. A little patience would be appreciated.

**Comment by hcho3** [comment]
@kyoungrok0517  And I apologize for not giving you any update for more 2 months. I will look at this issue over this weekend.

**Comment by hcho3** [comment]
@kyoungrok0517 Quick update: One thing I notice is that your script enables `pred_contribs=True`, `approx_contribs=True`, `pred_interactions=True`. Only one of them should have been enabled, but somehow XGBoost does not produce error for this. I will see if the problem stays when using `pred_interactions=True` exclusively.

**Comment by kyoungrok0517** [comment]
Yes please try pred_interactions=True. I’ having a problem with that
setting.

2019년 5월 31일 (금) 오후 6:14, Philip Hyunsu Cho <notifications@github.com>님이 작성:

**Comment by hcho3** [comment]
@kyoungrok0517 Interesting, so I changed your script from
```python
# interactions
shap_params = {
    'pred_contribs': True,
    'approx_contribs': True,
    'pred_interactions': True
}
preds = model.predict(dtest, **shap_params)
```
to
```python
# interactions
shap_params = {
    'pred_interactions': True,
    'approx_contribs': True
}
preds = model.predict(dtest, **shap_params)
```
and I don't get `ngroup = 0` error any more. In about 20 minutes on C5.9xlarge machine, the modified script completes running.

I filed #4522 to fix the issue. Specifically, you will get  an error when both `pred_contribs` and `pred_interactions` are set.

**Comment by kyoungrok0517** [comment]
I see. Thanks for the response!

2019년 5월 31일 (금) 오후 7:26, Philip Hyunsu Cho <notifications@github.com>님이 작성:
