### ISSUE TITLE
Provide Dockerfile for building xgboost, so that a user doesn't have to figure out the required build environment

### ISSUE THREAD

**Issue by bali0019** [dmlc/xgboost#4289]
As of now, building Xgboost is really a cumbersome task. Not only is build environment fully documented, but also requires few things (cmake, maven, python) to be available for the build. 
By providing a Dockerfile for build environment, we won't just make it easy to build xgboost anywhere, but also document dependencies and versions required for the build. 
After that, the future iterations can be to use docker-compose for running integration tests, which will help tremendously for finding bugs ahead in the process.

**Comment by hcho3** [comment]
@bali0019 We already have a Docker image for continuous integration: https://github.com/dmlc/xgboost/blob/master/tests/ci_build/Dockerfile.gpu.
Sample CI output: https://xgboost-ci.net/blue/organizations/jenkins/xgboost/detail/PR-4281/4/pipeline

**Comment by bali0019** [comment]
@hcho3 just to make sure, does it build jvm packages as well? Also, why are these build components under test?

**Comment by hcho3** [comment]
@bali0019 Everything related to continuous integration is stored under `tests/` directory. For the Docker image used in the JVM packages, see https://github.com/dmlc/xgboost/blob/c18a3660faea9d9351ffc6a01ee1d8f50559d9bf/jvm-packages/dev/build-docker.sh

**Comment by hcho3** [comment]
@CodingCat Do you have a Dockerfile for the image `codingcat/xgbrelease:latest`?

**Comment by bali0019** [comment]
@hcho3, yes, i did see that, but there is no Dockerfile where i can simple do mount a local host path to run docker container to build jvm packages. if it is, I apologise, but we need to atleast have a good readme for build environment, happy to contribute.

**Comment by bali0019** [comment]
@hcho3 thanks for the reply !

**Comment by hcho3** [comment]
@bali0019 I agree that we should clearly document the existence of Docker images. Optionally, we can also upload pre-built Docker images to Docker Hub.

**Comment by CodingCat** [comment]
I don't have docker files but only updated images....

you can directly run dev/build-docker.sh under jvm-packages folder to build xgboost for linux environment

**Comment by hcho3** [comment]
Will be addressed in #4380
