### ISSUE TITLE
predict use best_iteration(if any instead) of last one

### ISSUE THREAD

**Issue by VladimirOvsyannikovEvision** [dmlc/xgboost#429]
Looks like the behavior has been changed. And model(result of train) contains trees up to best_result not up to round or best iteration + early_stopping_rounds.

**Comment by tqchen** [comment]
this seems to be related to issue #428 and #420

**Comment by VladimirOvsyannikovEvision** [comment]
I'm not using sklearn wrapper.

**Comment by tqchen** [comment]
I see, You can always use predict with ntree_limit to get prediction of whatever round you like
