### ISSUE TITLE
[jvm-package] Inconsistent predictions using XGBoost4j-Spark with model trained in R

### ISSUE THREAD

**Issue by greg-rychlewski** [dmlc/xgboost#4294]
Hi,

I'm using an XGBoost model trained in R to make predictions using the xgboost4j-spark package. 

When I compare the probability predictions made by R with the ones made with xgboost4j-spark they always differ when one of the features is missing.

I'm not sure if this is a bug in the package or if some of the missing value parameters need to be adjusted. Right now I'm using the default missing value options (R's predict function defaults to NA, it looks like xgboost4j-spark's transform function defaults to NaN).

Here are the relevant parts of the code I'm using:

```
val input = assembler
      .setHandleInvalid("keep")
      .transform(data)

val model = new XGBoostClassificationModelBridge("test", 2, modelPath)
      .xgbClassificationModel
val predictions = model.transform(input)
```

I'm using version 0.82 of xgboost4j-spark with spark 2.4.0.

**Comment by greg-rychlewski** [comment]
I did some more digging and found that I can get the correct probability in spark when I access the booster directly and pass in a dmatrix created from a float array:

`val data = Array(
 0.0,0.0,56.39,353.0,306.0,218793.63,0.0,99999.0,0.0,15.07,99999.0,0.0,0.0,265177.16,11.0,-2.0,-2.0,200.0,6459.0,4276.1366,2.0,1809.72,80000.0,0.0,5.3,346238.0,-4.0,999.0,305.0,305.0,0.0,1.0,50.0,0.0,82.0,999.0,0.0,165.0,999.0,26.0,150000.0,-1.0,23.0,0.0,0.0,0.0,0.0,Double.NaN).map(_.toFloat)
    val dMatrix = new DMatrix(data, nrow = 1, ncol = 48, missing = Float.NaN )
    val predict_dmatrix = bst.predict(dMatrix)
    predict_dmatrix.foreach( x => println(x.map(_.toDouble).mkString) )
\\ output = 9.949778177542612E-5 (correct)`

When I convert the same array to a dense vector and use it to create a dataframe so that I can use the mllib transform method, I get the incorrect probability:

` val v = Vectors.dense(data.map(_.toDouble))
    val df = spark.createDataFrame(Seq((0, v))).toDF("id", "features")
    val predict_df = model.transform(df)
    predict_df.show(false) 
 \\ output = 1.8168642418459058E-4 (incorrect)`

**Comment by CodingCat** [comment]
there is a bug when handling NaN in spark, https://github.com/dmlc/xgboost/pull/4309/files should fix the issue
