### ISSUE TITLE
Python wheel for linux increased from 16.6MB to 114MB (!) between 0.81 and 0.82

### ISSUE THREAD

**Issue by kdebrab** [dmlc/xgboost#4295]
The Python manylinux wheel for XGBoost increased from 16.6MB for 0.81 to 114MB (!) for 0.82. One can check this by comparing https://pypi.org/project/xgboost/0.82/#files with https://pypi.org/project/xgboost/0.81/#files.

Looking at the release notes, I didn't see an explanation for this dramatic increase, so maybe it was not on purpose...

**Comment by RAMitchell** [comment]
Our python wheels now come with all GPU algorithms. Let us know if you have a specific complaint about the size of the binary.
