### ISSUE TITLE
FutureWarning: Series.base is deprecated and will be removed in a future version

### ISSUE THREAD

**Issue by justincart** [dmlc/xgboost#4300]
I am using python3.7.2 with xgboost 0.81 and got a lot of the following error messages:

/Users/jianhuitian/Documents/Programs/Anaconda3/anaconda3/lib/python3.7/site-packages/xgboost/core.py:587: FutureWarning: Series.base is deprecated and will be removed in a future version
if getattr(data, ‘base’, None) is not None

How to get rid of this annoying issue?

**Comment by thvasilo** [comment]
I did a quick grep of the repo and cannot find the offending line `if getattr(data, ‘base’, None) is not None`, or any relevant reference to `Series.base` which originates from Pandas.

Not sure where why this warning pops up.

**Comment by jrathgeber** [comment]
Same issue

**Comment by astrowonk** [comment]
Getting the same warning. 

The code is [here](https://github.com/dmlc/xgboost/blob/82dca3c108502b6912f2135c3120a24a3ec55045/python-package/xgboost/core.py#L591):

`        if getattr(data, 'base', None) is not None and \
           data.base is not None and isinstance(data, np.ndarray) \
           and isinstance(data.base, np.ndarray) and (not data.flags.c_contiguous):
            self.set_float_info_npy2d(field, data)
            return
`

**Comment by hdinh** [comment]
Here's the code that produces this for me, it seems to be a combination of passing a pandas Series as the sample_weight.

```
import pandas as pd
import numpy as np
from xgboost import XGBClassifier

X = np.array([[0], [0], [1]])
y = np.array([0, 0, 1])
w = pd.Series([1, 1, 1])
clf = XGBClassifier()
clf.fit(X, y, w)
```

Looks like it's happening for pandas>=0.23.0 because the pandas `Series.base` property has been deprecated:
https://github.com/pandas-dev/pandas/blob/master/pandas/core/base.py#L779
from https://github.com/pandas-dev/pandas/issues/20419

**Comment by yangjx12** [comment]
A simple way, ignore the warning.

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)dd

**Comment by H4dr1en** [comment]
> 
> 
> A simple way, ignore the warning.
> 
> import warnings
> warnings.simplefilter(action='ignore', category=FutureWarning)

Ignoring warnings should never be a solution

**Comment by T0T4R4** [comment]
A simple way is for the contributors of this package to keep up with Pandas updates....

**Comment by trivialfis** [comment]
Suggestions are welcomed. :-)

**Comment by hcho3** [comment]
#4337 should eliminate FutureWarning

**Comment by XsongyangX** [comment]
Hi there, I am facing this same issue right now with the latest stable release of xgboost (0.9). I'm using an older version of python than the one used by OP. I have 3.6.8.

There is another warning message that keeps popping up. I will create a different issue for this. 
![image](https://user-images.githubusercontent.com/10444460/63137240-5e0d1180-bfa3-11e9-8882-37bec8a01dd2.png)

**Comment by hcho3** [comment]
@XsongyangX 0.90 version was released on May 20, and the fix was made on July 4. So the next release will not have the warning.

**Comment by trivialfis** [comment]
Sorry, wrong click.
