### ISSUE TITLE
[jvm-packages] xgboost spark 0.7 use resnet image feature crash

### ISSUE THREAD

**Issue by jt120** [dmlc/xgboost#4305]
I use xgboost 0.7 and spark 2.1.0 to train CTR model

when I add image feature, 300 double numbers to feature, the spark crash, screen scroll show some code like below:
```
/* 10255 */ boolean isNullA301;
/* 10256 */ int primitiveA301;
/* 10257 */ {
/* 10258 */
/* 10259 */ boolean isNull301 = i.isNullAt(301);
/* 10260 */ int value301 = isNull301 ? -1 : (i.getInt(301));
/* 10261 */ isNullA301 = isNull301;
/* 10262 */ primitiveA301 = value301;
/* 10263 */ }
/* 10264 */ i = b;
/* 10265 */ boolean isNullB301;
/* 10266 */ int primitiveB301;
```
what's this? seems some code auto generate, any advice for debug this problem?

P.S. 
I can train same model with same feature in python version xgboost, so I think it may be a problem of spark xgboost lib

**Comment by hcho3** [comment]
Can you try using XGBoost4J-Spark 0.82?

**Comment by jt120** [comment]
> XGBoost4J-Spark 0.82

thks，I will

**Comment by jt120** [comment]
> Can you try using XGBoost4J-Spark 0.82?

I will try, and send result here, tks
