### ISSUE TITLE
children right leaves saved as zeros?

### ISSUE THREAD

**Issue by gnodabb** [dmlc/xgboost#4314]
I am currently trying to understand if this is normal behavior. When I create or load a model that has been trained using the parameter 'tree_method':'gpu_hist' then it appears that the model format is inconsistent with other behaviors. The children right leaves appear to be stored as `0`, while the children left leaves are `-1`. Additionally, when using 'tree_method':'gpu_exact', the right and left leaves are saved as `-1`.

First, I would like someone to verify that I am seeing expected behavior.
Second, is this expected behavior. And if so, why?

Thank you for your time.

windows 10
GTX 1080
xgboost 0.72 in a conda env

**Comment by RAMitchell** [comment]
Thanks for filing an issue. Please verify if the issue exists on the latest source, the xgboost GPU algorithms have changed a lot since 0.72. Also provide a simple script that shows the behaviour that you're experiencing and we can take a look.

**Comment by gnodabb** [comment]
I have verified this same behavior on 0.83.dev0
I will simplify a small script and upload soon.

**Comment by gnodabb** [comment]
Here is my script:

`import os
import xgboost as xgb
import numpy as np
import shap

# initialize random data for small training size.
np.random.seed(0)
X_train = np.random.rand(1000, 15)
X_test = np.random.rand(500,15)

y_train = np.zeros((1000, 1))
y_test = np.zeros((500, 1))

y_train[:500] = 1
y_test[:250] = 1

dtrain = xgb.DMatrix(X_train, label=y_train)
dtest = xgb.DMatrix(X_test, label=y_test)

# Set initial parameters to train on the gpu using gpu_hist tree method
param_hist = {'max_depth':5, 'silent':1, 'objective':'binary:logistic', 'tree_method':'gpu_hist'}
num_round = 1
# Train
bst_h = xgb.train(param_hist, dtrain, num_round)

# I am currently trying to fix the crash on the following line. 
# I have a pull request with the shap team. However, I need to verify that this is expected xgboost behavior.
# explainerh = shap.TreeExplainer(bst_h)

# The reason for the crash is because xgboost is denoting left leaves as '-1' but right leaves as '0'
xgb_loader_hist = shap.explainers.tree.XGBTreeModelLoader(bst_h)
print('Left Leaves on GPU hist:')
print(xgb_loader_hist.node_cleft[0])
print('Right Leaves on GPU hist:')
print(xgb_loader_hist.node_cright[0])

param = {'max_depth':5, 'silent':1, 'objective':'binary:logistic'}
num_round = 1
# Train
bst = xgb.train(param, dtrain, num_round)

xgb_loader = shap.explainers.tree.XGBTreeModelLoader(bst)
print('\nLeft Leaves:')
print(xgb_loader.node_cleft[0])
print('Right Leaves:')
print(xgb_loader.node_cright[0])`

Output:
`Left Leaves on GPU hist:[ 1  3  5  7  9 -1 -1 11 13 15 17 19 21 23 25 27 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
Right Leaves on GPU hist:
[ 2  4  6  8 10  0  0 12 14 16 18 20 22 24 26 28  0  0  0  0  0  0  0  0  0  0  0  0  0]

Left Leaves:
[ 1  3  5  7  9 11 -1 -1 13 15 17 -1 -1 19 21 23 25 27 29 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
Right Leaves:
[ 2  4  6  8 10 12 -1 -1 14 16 18 -1 -1 20 22 24 26 28 30 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]`
