### ISSUE TITLE
About the return values of  xgboostModel.transformLeaf function ?

### ISSUE THREAD

**Issue by zyq11223** [dmlc/xgboost#4325]
About the return values of  xgboostModel.transformLeaf(trainRDD) ?   the value is  the value of leaf nodes or  the index of leaf nodes ? 
Solving the CTR issue with XGboost4j-spark and sparkml lr , does it need to do one hot encoder with the leaves' values of  xgboostModel.transformLeaf(trainRDD) , then take it as input of logistic regression algorithm ??
请原谅我，需要用中文表述一下我的两个问题，通过 Xgboost4j-spark 和 sparkml 中的 LR 算法，做 CTR 预估，是否需要对xgboost模型输出的叶子节点进行 Onehot,然后将 Onehot 后的结果作为 LR 算法的输入？？
xgboost model 输出的transformLeaf 输出的是叶子节点的值，还是叶子节点的索引呢？

**Comment by hcho3** [comment]
transformLeaf returns index of leaf nodes. Yes, you will want to perform one hot encoding if you are using output of transformLeaf as input to logistic regression
