### ISSUE TITLE
Finally, I use spark `VectorIndexer` and `OneHotEncoderEstimator` to perform one-hot encoding.

### ISSUE THREAD

**Issue by zyq11223** [dmlc/xgboost#4326]
Finally, I use spark `VectorIndexer` and `OneHotEncoderEstimator` to perform one-hot encoding.

_Originally posted by @holysoros in https://github.com/dmlc/xgboost/issues/3847#issuecomment-440513396_

Would you mind explain it detail ? Thank you

**Comment by hcho3** [comment]
See https://spark.apache.org/docs/latest/ml-features.html#onehotencoderestimator

**Comment by zyq11223** [comment]
I mean, how to do one hot encoder to the vector of the dataframe in spark. The vector is produced by xgboost. transformLeaf().

**Comment by zyq11223** [comment]
> See https://spark.apache.org/docs/latest/ml-features.html#onehotencoderestimator

I mean, how to do one hot encoder to the vector of the dataframe in spark. The vector is produced by xgboost. transformLeaf().
