### ISSUE TITLE
[jvm-packages] java.lang.UnsatisfiedLinkError for jvm-packages

### ISSUE THREAD

**Issue by bali0019** [dmlc/xgboost#4338]
I have been getting the following exception on ubuntu 16.04. It builds fine without any exception and I am using gcc 5.4.0. Any tips what could cause this?
And yes `libxgboost4j.so` is generated and placed under resources folder of `xgboost4j` inside `jvm-packages` I also ensure my final xgboost4j jar file contains `libxgboost4j.so`

Also, works fine for all unit tests, but i get the below exception when I deploy it on a spark cluster with gcc-5.4.0 running

`ErrorInXGBoostTraining: ExecutorLost during XGBoost Training: java.lang.UnsatisfiedLinkError: ml.dmlc.xgboost4j.java.XGBoostJNI.XGDMatrixCreateFromDataIter(Ljava/util/Iterator;Ljava/lang/String;[J)I`

**Comment by hcho3** [comment]
I wonder it has to do with GLIBC dependency.

@CodingCat What's the GLIBC version requirement for XGBoost4J-Spark?

**Comment by CodingCat** [comment]
It requires very low version, should be 2.12, any higher ones should be compatible

**Comment by hcho3** [comment]
@bali0019 Can you describe your cluster environment (OS, GLIBC)?

**Comment by hcho3** [comment]
Closing for now
