### ISSUE TITLE
[jvm-packages] XGBoost4j can't load the native library on Java 12

### ISSUE THREAD

**Issue by Craigacp** [dmlc/xgboost#4342]
XGBoost fails to load the JNI library when running on Java 12. It loads with a warning on Java 9 through 11.

In 12 the ability to modify fields on the ClassLoader was turned off - https://bugs.openjdk.java.net/browse/JDK-8210522. And so in 12 you get:
```
[04/08/19 16:59:50:371] SEVERE NativeLibLoader.addNativeDir usr_paths
[04/08/19 16:59:50:371] SEVERE DMatrix.<clinit> load native library failed.
[04/08/19 16:59:50:372] SEVERE DMatrix.<clinit> java.io.IOException: Failed to get field handle to set library path
Exception in thread "main" java.lang.UnsatisfiedLinkError: ml.dmlc.xgboost4j.java.XGBoostJNI.XGDMatrixCreateFromCSREx([J[I[FI[J)I
	at ml.dmlc.xgboost4j.java.XGBoostJNI.XGDMatrixCreateFromCSREx(Native Method)
	at ml.dmlc.xgboost4j.java.DMatrix.<init>(DMatrix.java:122)
```

whereas in 11 it prints:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by ml.dmlc.xgboost4j.java.NativeLibLoader (file:/local/Repositories/Tribuo/Classification/XGBoost/target/mlrg-classification-xgboost-3.0.0-SNAPSHOT-jar-with-dependencies.jar) to field java.lang.ClassLoader.usr_paths
WARNING: Please consider reporting this to the maintainers of ml.dmlc.xgboost4j.java.NativeLibLoader
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
and execution continues. In Java 8 it executes without a warning.

**Comment by CodingCat** [comment]
yes...expected, xgboost4j's jvm support is essentially following Spark's......

**Comment by Craigacp** [comment]
If I can work out a fix that doesn't break Java 8 will you accept it?

**Comment by CodingCat** [comment]
> If I can work out a fix that doesn't break Java 8 will you accept it?

more than happy

**Comment by Craigacp** [comment]
Ok. I've got a rough fix which rearranges the calls in smartLoad and catches the exceptions differently as the loading from a tmp file still works. It's unclear to me what the utility of the smartLoad call is vs just creating a tmp file, as on Linux at least it always creates a tmp file.

**Comment by CodingCat** [comment]
I think mac/linux is necessary, for windows....we have essentially drop it from official release so I am not worrying too much

regarding JDK, I think JDK 11 is good, as from Spark 3 (next version) they are targeting this version

it's great if you can put the test in Travis CI and skip Flink/Spark test when using anything beyond JDK 8 for now

**Comment by hcho3** [comment]
@Craigacp @CodingCat I'm planning to add Java build workers to Jenkins by this weekend. Can we list the JDK versions we'd like to test on?

**Comment by CodingCat** [comment]
JDK 8 & 11 (skip Spark/Flink for now) is good

**Comment by Craigacp** [comment]
Ok. I have internal users who want Windows so I'll test that too.

As for JDKs I'd recommend looking at the LTS releases (currently 8 and 11) and the current release (currently 12, 13 is out in September). That way you can catch things before they land in an LTS release. BTW while I do work for Oracle, I'm in the research labs so I don't work on Java itself.

Any comment on why the smartLoad method tries to end run around the JVM? I looked through the commit history but that chunk is added in one go without an explanation as to why it's better than the original native loader which uses a temp file.

**Comment by CodingCat** [comment]
what do you mean by `original native loader `?

that smartload has been there for a while (earlier than I am involved)....but from what I can tell, in all of my environments, it goes to 

https://github.com/dmlc/xgboost/blob/master/jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/NativeLibLoader.java#L150-L156

**Comment by Craigacp** [comment]
Well NativeLibLoader used to only do the load from the jar, and now it has this hook in it to check if it's in the dev build, add that to the library path and then load from that. I've removed that hook in the pull request (#4351) as it's the root cause of the JDK12 issue, and also gets rid of the warning printed on JDK 9, 10, 11.

**Comment by CodingCat** [comment]
fixed by https://github.com/dmlc/xgboost/pull/4351
