### ISSUE TITLE
Some headers are looking for headers in ../../src/common, causing build problem in C++ project

### ISSUE THREAD

**Issue by abdul-rehman0** [dmlc/xgboost#4359]
I have a c++ project in which I would like to use xgboost, I did the following steps:

    git clone --recursive https://github.com/dmlc/xgboost
    cd xgboost
    mkdir build
    cd build

    cmake ..
    make -j8
    make install
    cd ..
    cp -r include/xgboost/ /usr/local/include/
    cp -r rabit/include/rabit/ /usr/local/include/
    cp lib/libxgboost.so /usr/local/lib

This is my test code:

    #include <xgboost/learner.h>
    #include <gtest/gtest.h>

    TEST(XGBoostTest, learner_test) {
      std::unique_ptr<Learner> learner(Learner::Create({}));
    }

I am getting compilation errors due to missing headers:

    [build] /usr/local/include/xgboost/data.h:20:10: fatal error: ../../src/common/span.h: No such file or directory
    [build]  #include "../../src/common/span.h

there is an header <xgboost/data.h> which contains includes as following:

    #include "../../src/common/span.h"
    #include "../../src/common/group_data.h"
    #include "../../src/common/host_device_vector.h"

**Comment by trivialfis** [comment]
@abdul-rehman0 For now you need to make your c++ project as part of XGBoost since we don't have C++ APIs.  You can also try to use C APIs,  see the example in : https://github.com/dmlc/xgboost/tree/master/demo/c-api

If you want to use cmake for C APIs, you can try my branch in: https://github.com/dmlc/xgboost/pull/4323 and change back to master when it's merged.

**Comment by abdul-rehman0** [comment]
@trivialfis Thanks, is there any plan for C++ APIs? Meanwhile I will try to use your branch.

**Comment by trivialfis** [comment]
@abdul-rehman0 Just don't pull the rabit change in that branch yet.  I need some time to deal with rabit.

**Comment by trivialfis** [comment]
BTW, we don't have any plan for c++ APIs yet.  Too many TODOs.

**Comment by hcho3** [comment]
@abdul-rehman0 Note that all C++ functions of XGBoost are internal and subject to changes. So for stability, you should use C API functions.
