### ISSUE TITLE
[Rabit] One dmlc-core.

### ISSUE THREAD

**Issue by trivialfis** [dmlc/xgboost#4360]
@chenqin @RAMitchell @hcho3 

It was suggested that we can duplicate dmlc-core in #4352 but I disagree with the choice.  The problem is in c++'s hairy linkage specification.  If we have out-of-sync `dmlc-core` in two places, the behaviour is undefined.  Specifically with two functions having the same signature linker will choose one of them and discard the other.  I made a demonstration program for others to verify.  Will upload soon.

**Comment by trivialfis** [comment]
Uploaded in https://github.com/trivialfis/xgbissues

**Comment by trivialfis** [comment]
@CodingCat

**Comment by trivialfis** [comment]
We need to come up with a solution for the upgraded rabit.

**Comment by CodingCat** [comment]
Ok...then we should think about how to resolve the issue @RAMitchell raised

1. Take the pain, update dmlc, upgrade submodule in Rabit, upgrade submodule(rabit) in XGBoost

2. let’s forget about rabit, keep rabit as an independent project for whoever else wants

**Comment by trivialfis** [comment]
@CodingCat 

For 1. Indeed painful.
For 2. If we fix a bug in our cloned rabit,  we still want to port the fix to original rabit right?  That's just copying files in disguise...

CMake has a feature called `External project`,  that will fit normal development. But it also makes packaging for R CRAN (which uses amalgamation) and Python PIP difficult.

**Comment by chenqin** [comment]
Rabit is a bit of everything but mostly flexible interface (sync/checkpoint/restore) Take an example, I can totally see running GPU direct implementation behind Rabit as possibility.

I think easiest thing we can do is to split dmlc-core headers used in rabit and rename (to avoid confusion in xgboost we had seen before) this will cut dependency between dmlc-core with rabit at cost of rabit needs to sync with dmlc-core from time to time to avoid xgboost rabit upgrade issue. It leaves rabit a bit more work and makes entire flow smooth.

The downside is clearly if dmlc-core headers changed like io.h rabit can only find out when it upgrade.(I think i can do a dummy script and auto sync with dmlc-core master with a bit naming hacking.

**Comment by CodingCat** [comment]
@trivialfis I am actually proposing accept more and more diversity of cloned rabit and the original rabit, if people wants to fix there, fine..and we can do whatever beneficial to xgboost in, as an example, src/communication/

**Comment by trivialfis** [comment]
@CodingCat I think @chenqin is doing a lots of work on rabit that I cannot do myself, and it seems jvm package has tons of work to occupy your hand, so merging rabit into XGBoost won't advance it.  My suggestion is add an option to rabit's build system for using existing `dmlc-core` instead of another git submodule.

**Comment by chenqin** [comment]
https://github.com/dmlc/rabit/pull/91

**Comment by trivialfis** [comment]
Closed by https://github.com/dmlc/rabit/pull/91 .
