### ISSUE TITLE
scikit-learn XGBRegressor doesn't work with objective function rg:squarederror   

### ISSUE THREAD

**Issue by scigeek72** [dmlc/xgboost#4362]
Thanks for participating in the XGBoost community! We use https://discuss.xgboost.ai for any general usage questions and discussions. The issue tracker is used for actionable items such as feature proposals discussion, roadmaps, and bug tracking.  You are always welcomed to post on the forum first :)

Issues that are inactive for a period of time may get closed. We adopt this policy so that we won't lose track of actionable issues that may fall at the bottom of the pile. Feel free to reopen a new one if you feel there is an additional problem that needs attention when an old one gets closed.

For bug reports, to help the developer act on the issues, please include a description of your environment, preferably a minimum script to reproduce the problem.

For feature proposals, list clear, small actionable items so we can track the progress of the change.

**Comment by trivialfis** [comment]
Could you please share your xgb version?  And I believe it's `reg` not `rg`.

**Comment by scigeek72** [comment]
I am trying to run a GRIDSEARCHCV (sklearn) on XGBRegressor. Documentation on the parameter says that if regression, then `objective = reg:squarederror`.(see https://github.com/dmlc/xgboost/tree/master/demo/regression) However, whenever I am trying to run the search, I am getting an error saying `XGBoostError: b'[13:39:54] src/objective/objective.cc:23: Unknown objective function reg:squarederror`.

I am not sure how to get around this problem. For the sake of completeness, below is the piece of code I am using for this purpose.

```
cv_params = {
             'n_estimators' : np.arange(100, 1201, 100),
             'max_depth' : np.arange(2, 10)
             }

xgbr_params = {'objective':'reg:squarederror','n_jobs':-1,'random_state':4444,'min_child_weight':1,
              'eta':0.3,'subsample':0.8,'gamma':0.5,'colsample_bytree':0.8}


opt_xgbr = GridSearchCV(xgb.XGBRegressor(**xgbr_params)
                              ,param_grid=cv_params,scoring='r2',cv=5,n_jobs=-1,return_train_score=True, verbose=3
```

**Comment by scigeek72** [comment]
xgboost version 0.82

**Comment by scigeek72** [comment]
xgboost version 0.82

**Comment by trivialfis** [comment]
That's a change in master branch and will be included in next release.  For 0.82,  use `reg:linear` instead.
