### ISSUE TITLE
Releasing Internal Patches to OSS community

### ISSUE THREAD

**Issue by sjang92** [dmlc/xgboost#4363]
Hi, we maintain a set of internal patches that introduce the following functionalities:
- Label-wise weight remapping (vs. instance-wise weight remapping)
- normalized entropy as evaluation metric

We're wondering if these features would be valuable for the open-source community.
If so, we can send in PRs for these changes. 

We do not have CLA set-up yet.
Please let me know if this is something you'd want, and we can work accordingly. 

Thank you!

**Comment by hcho3** [comment]
@sjang92 Yes, your contribution is more than welcome. We do not require CLA; you only need to comply with Apache 2.0 license (so no patent claims etc).

One question:

> Label-wise weight remapping

Is this different from `scale_pos_weight` parameter?

**Comment by hcho3** [comment]
Any updates?

**Comment by sjang92** [comment]
Hi, sorry about the late response.

Yeah, we allow the input LibSVM files to contain multiple non-binary integer labels, and during training time each non-negative label is remapped to pos label with their weights mapped separately.

Let me see how I can package our patches and send them upstream

**Comment by trivialfis** [comment]
@sjang92  Closing for now.  Feel free to open an issue/PR for wanted changes.
