### ISSUE TITLE
the job of “dmlc-submit” seemed that the job won't finish even after the model had been generated several hours ago

### ISSUE THREAD

**Issue by jackyhawk** [dmlc/xgboost#4366]
As my cmd is like this:
./dmlc-submit --cluster=yarn --num-workers=800 --worker-cores=2 --worker-memory=6g ./xgboost ./xgb2019_on_yarn.conf nthead=1 -f /data/common/xgblibhdfs/lib/libhdfs.so.0.0.0 data=hdfs://wx/user/tjxgboost-features/xgb-model/2019_04_14_02/libsvm/train 'eval[test]=hdfs://wx/user/tjxgboost-features/xgb-model/2019_04_14_02/libsvm/eval' model_dir=hdfs://wx/user/tjxgboost-features/xgb-model/2019_04_14_02/libsvm 

it seemed that the job won't finish even after the model had been generated several hours ago.
and when the job finished successfully, it would print one line like this:
Application application_1553321127743_592324 finished with state FINISHED at 1555200417035

and when it won't finish, how can i got the applicationId and then just kill the job by the applicationId automatically

Thanks very much

**Comment by hcho3** [comment]
https://github.com/dmlc/dmlc-core/pull/525 may fix the problem
