### ISSUE TITLE
[jvm-packages] xgboost4j.cpp 'JNI_OnLoad' redefinition error when building 32-bit Windows native library

### ISSUE THREAD

**Issue by benjamincitrin** [dmlc/xgboost#4371]
I am trying to create xgboost4j.dll in a 32-bit environment.  XGBoost v0.83 on Windows 7 32-bit with Visual Studio 2017.  My error occurs when running mvn install:

________________________________________________
`C:\Users\IEUser\test3\xgboost\jvm-packages>mvn install
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for
ml.dmlc:xgboost4j:jar:0.83-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.codehaus.mojo:exec-maven-plugin
 is missing. @ line 54, column 19
[WARNING] Reporting configuration should be done in <reporting> section, not in
maven-site-plugin <configuration> as reportPlugins parameter.
[WARNING]
[WARNING] Some problems were encountered while building the effective model for
ml.dmlc:xgboost4j-example:jar:0.83-SNAPSHOT
[WARNING] Reporting configuration should be done in <reporting> section, not in
maven-site-plugin <configuration> as reportPlugins parameter.
[WARNING]
[WARNING] Some problems were encountered while building the effective model for
ml.dmlc:xgboost4j-spark:jar:0.83-SNAPSHOT
[WARNING] Reporting configuration should be done in <reporting> section, not in
maven-site-plugin <configuration> as reportPlugins parameter.
[WARNING]
[WARNING] Some problems were encountered while building the effective model for
ml.dmlc:xgboost4j-flink:jar:0.83-SNAPSHOT
[WARNING] Reporting configuration should be done in <reporting> section, not in
maven-site-plugin <configuration> as reportPlugins parameter.
[WARNING]
[WARNING] Some problems were encountered while building the effective model for
ml.dmlc:xgboost-jvm:pom:0.83-SNAPSHOT
[WARNING] Reporting configuration should be done in <reporting> section, not in
maven-site-plugin <configuration> as reportPlugins parameter. @ line 249, column
 32
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten t
he stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support buildin
g such malformed projects.
[WARNING]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] XGBoost JVM Package                                                [pom]
[INFO] xgboost4j                                                          [jar]
[INFO] xgboost4j-spark                                                    [jar]
[INFO] xgboost4j-flink                                                    [jar]
[INFO] xgboost4j-example                                                  [jar]
[INFO]
[INFO] ------------------------< ml.dmlc:xgboost-jvm >-------------------------
[INFO] Building XGBoost JVM Package 0.83-SNAPSHOT                         [1/5]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- scalastyle-maven-plugin:0.8.0:check (checkstyle) @ xgboost-jvm ---
[WARNING] sourceDirectory is not specified or does not exist value=C:\Users\IEUs
er\test3\xgboost\jvm-packages\src\main\scala
[WARNING] testSourceDirectory is not specified or does not exist value=C:\Users\
IEUser\test3\xgboost\jvm-packages\src\test\scala
Processed 0 file(s)
Found 0 errors
Found 0 warnings
Found 0 infos
Finished in 141 ms
[INFO]
[INFO] --- maven-checkstyle-plugin:2.17:check (checkstyle) @ xgboost-jvm ---
[INFO]
[INFO] --- scala-maven-plugin:3.2.2:compile (default) @ xgboost-jvm ---
[WARNING]  Expected all dependencies to require Scala version: 2.11.12
[WARNING]  ml.dmlc:xgboost-jvm:0.83-SNAPSHOT requires scala version: 2.11.12
[WARNING]  org.scala-lang:scala-compiler:2.11.12 requires scala version: 2.11.12

[WARNING]  org.scala-lang.modules:scala-xml_2.11:1.0.5 requires scala version: 2
.11.7
[WARNING] Multiple versions of scala libraries detected!
[INFO] No sources to compile
[INFO]
[INFO] --- scala-maven-plugin:3.2.2:compile (scala-compile-first) @ xgboost-jvm
---
[WARNING]  Expected all dependencies to require Scala version: 2.11.12
[WARNING]  ml.dmlc:xgboost-jvm:0.83-SNAPSHOT requires scala version: 2.11.12
[WARNING]  org.scala-lang:scala-compiler:2.11.12 requires scala version: 2.11.12

[WARNING]  org.scala-lang.modules:scala-xml_2.11:1.0.5 requires scala version: 2
.11.7
[WARNING] Multiple versions of scala libraries detected!
[INFO] No sources to compile
[INFO]
[INFO] --- scala-maven-plugin:3.2.2:add-source (scala-compile-first) @ xgboost-j
vm ---
[INFO] Add Source directory: C:\Users\IEUser\test3\xgboost\jvm-packages\src\main
\scala
[INFO] Add Test Source directory: C:\Users\IEUser\test3\xgboost\jvm-packages\src
\test\scala
[INFO]
[INFO] --- scala-maven-plugin:3.2.2:compile (compile) @ xgboost-jvm ---
[WARNING]  Expected all dependencies to require Scala version: 2.11.12
[WARNING]  ml.dmlc:xgboost-jvm:0.83-SNAPSHOT requires scala version: 2.11.12
[WARNING]  org.scala-lang:scala-compiler:2.11.12 requires scala version: 2.11.12

[WARNING]  org.scala-lang.modules:scala-xml_2.11:1.0.5 requires scala version: 2
.11.7
[WARNING] Multiple versions of scala libraries detected!
[INFO] No sources to compile
[INFO]
[INFO] --- scala-maven-plugin:3.2.2:testCompile (test-compile) @ xgboost-jvm ---

[WARNING]  Expected all dependencies to require Scala version: 2.11.12
[WARNING]  ml.dmlc:xgboost-jvm:0.83-SNAPSHOT requires scala version: 2.11.12
[WARNING]  org.scala-lang:scala-compiler:2.11.12 requires scala version: 2.11.12

[WARNING]  org.scala-lang.modules:scala-xml_2.11:1.0.5 requires scala version: 2
.11.7
[WARNING] Multiple versions of scala libraries detected!
[INFO] No sources to compile
[INFO]
[INFO] --- scalatest-maven-plugin:1.0:test (test) @ xgboost-jvm ---
Discovery starting.
Discovery completed in 168 milliseconds.
Run starting. Expected test count is: 0
DiscoverySuite:
Run completed in 238 milliseconds.
Total number of tests run: 0
Suites: completed 1, aborted 0
Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
No tests were executed.
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ xgboost-jvm ---
[INFO] Installing C:\Users\IEUser\test3\xgboost\jvm-packages\pom.xml to C:\Users
\IEUser\.m2\repository\ml\dmlc\xgboost-jvm\0.83-SNAPSHOT\xgboost-jvm-0.83-SNAPSH
OT.pom
[INFO]
[INFO] -------------------------< ml.dmlc:xgboost4j >--------------------------
[INFO] Building xgboost4j 0.83-SNAPSHOT                                   [2/5]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- scalastyle-maven-plugin:0.8.0:check (checkstyle) @ xgboost4j ---
Processed 14 file(s)
Found 0 errors
Found 0 warnings
Found 0 infos
Finished in 1221 ms
[INFO]
[INFO] --- maven-checkstyle-plugin:2.17:check (checkstyle) @ xgboost4j ---
[INFO]
[INFO] --- exec-maven-plugin:1.6.0:exec (native) @ xgboost4j ---
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 6.1.7601.
-- C:/Users/IEUser/test3/xgboost/dmlc-core/cmake/build_config.h.in -> C:/Users/I
EUser/test3/xgboost/dmlc-core/include/dmlc/build_config.h
-- C:/Users/IEUser/test3/xgboost/cmake/build_config.h.in -> C:/Users/IEUser/test
3/xgboost/include/xgboost/build_config.h
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/IEUser/test3/xgboost/build
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Program Files\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTarg
ets\Microsoft.Cpp.Platform.targets(65,5): error MSB8020: The build tools for Vis
ual Studio 2010 (Platform Toolset = 'v100') cannot be found. To build using the
v100 build tools, please install Visual Studio 2010 build tools.  Alternatively,
 you may upgrade to the current Visual Studio tools by selecting the Project men
u or right-click the solution, and then selecting "Retarget solution". [C:\Users
\IEUser\test3\xgboost\build\ZERO_CHECK.vcxproj]
building Java wrapper
cd ..
mkdir -p build
cd build
cmake .. -DUSE_S3:BOOL=OFF -DUSE_OPENMP:BOOL=ON -DUSE_CUDA:BOOL=OFF -DUSE_AZURE:
BOOL=OFF -DUSE_HDFS:BOOL=OFF -DJVM_BINDINGS:BOOL=ON -G"Visual Studio 15 2017"
cmake --build . --config Release
Traceback (most recent call last):
  File "create_jni.py", line 96, in <module>
    run("cmake --build . --config Release")
  File "create_jni.py", line 51, in run
    subprocess.check_call(command, shell=True, **kwargs)
  File "C:\Python27\lib\subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cmake --build . --config Release' returned
 non-zero exit status 1
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit
value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.
java:404)
    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166
)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:804)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:751)
    at org.codehaus.mojo.exec.ExecMojo.execute (ExecMojo.java:313)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBui
ldPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.ja
va:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.ja
va:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.ja
va:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (
LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (
LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreaded
Builder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleSt
arter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.jav
a:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessor
Impl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launche
r.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:2
29)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launc
her.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356
)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for XGBoost JVM Package 0.83-SNAPSHOT:
[INFO]
[INFO] XGBoost JVM Package ................................ SUCCESS [  4.687 s]
[INFO] xgboost4j .......................................... FAILURE [  3.213 s]
[INFO] xgboost4j-spark .................................... SKIPPED
[INFO] xgboost4j-flink .................................... SKIPPED
[INFO] xgboost4j-example .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.362 s
[INFO] Finished at: 2019-04-15T07:39:10-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:exec (n
ative) on project xgboost4j: Command execution failed.: Process exited with an e
rror: 1 (Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionE
xception
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

[ERROR]   mvn <goals> -rf :xgboost4j`
________________________________________________

As shown, the error occurs during the 
`cmake .. -DUSE_S3:BOOL=OFF -DUSE_OPENMP:BOOL=ON -DUSE_CUDA:BOOL=OFF -DUSE_AZURE: BOOL=OFF -DUSE_HDFS:BOOL=OFF -DJVM_BINDINGS:BOOL=ON -G"Visual Studio 15 2017"
cmake --build . --config Release`
command in the create_juni.py.  

I tried running `cmake --build . --config Release` from the build directory and discovered there is an error in the xgboost solution involving xgboost4j.cpp and jni.h:

![image](https://user-images.githubusercontent.com/11984692/56154494-a5987800-5f86-11e9-972e-4266ca1470bc.png)

![image](https://user-images.githubusercontent.com/11984692/56154532-b812b180-5f86-11e9-9623-df153a4e3fcb.png)

What can I do to fix the JNI_OnLoad redefinition error?  Thank you.

**Comment by hcho3** [comment]
@CodingCat I don't think we support 32-bit architecture, do we?

**Comment by CodingCat** [comment]
no...too many things are unknown for 32-bits jvm...

I will close this issue as we we don't support it

**Comment by benjamincitrin** [comment]
Okay, thanks for your replies

**Comment by benjamincitrin** [comment]
Turns out the fix is to update the JNI_OnLoad return type to jint __stdcall in xgboost4j.cpp to:
`// overrides JNI on load
jint __stdcall JNI_OnLoad(JavaVM *vm, void *reserved) {
  global_jvm = vm;
  return JNI_VERSION_1_8;   
}`

For what it's worth, I am now successfully running the xgboost4j.dll on a 32-bit environment.
