### ISSUE TITLE
Forbid negative Hessian values

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#4372]
Currently, each tree updater tests if each data point has negative Hessian value and ignores the data point with negative Hessian. This complicates the updater code. We should have extra validation steps so as to ensure that all Hessian values are non-negative. The updater code then can be simplified by removing the Hessian check.

**Comment by hcho3** [comment]
Would regularization cause data points to be ignored?

**Comment by trivialfis** [comment]
@hcho3 Good point.
