### ISSUE TITLE
set_base_margin

### ISSUE THREAD

**Issue by kgoyal40** [dmlc/xgboost#4376]
Hi,

I am trying to calculate the predictions manually but combining results of multiple residual trees. For each tree, I am using the set_base_margin feature to train the tree. My question is, would it be okay to sum the predictions (using output_margin = True) for each tree and then take a logit transform for probabilities?

Also, since each residual tree is a regression tree (with the margin values as targets), do i need to change the target variable in dtrain as well? 

Thanks

**Comment by hcho3** [comment]
See my answer at https://discuss.xgboost.ai/t/output-margin-and-leaf-probabilities/798
