### ISSUE TITLE
pyspark errors on training

### ISSUE THREAD

**Issue by phillyfan1138** [dmlc/xgboost#4378]
I'm using xgboost4j-0.80.jar, xgboost4j-spark-0.80.jar, and the link to xgboost provided in [this post](https://github.com/dmlc/xgboost/issues/1698#issuecomment-420629409).  

I can load and define a model just fine:

```
spark.sparkContext.addPyFile("sparkxgb.zip")
from sparkxgb import XGBoostClassifier

model=XGBoostClassifier(
    featuresCol="features", 
    labelCol="origin_idx", 
    predictionCol="prediction"
)
```
When I try to train the model I receive the following error:

java.lang.NoSuchMethodError: org.codehaus.jackson.map.ObjectMapper.readTree(Ljava/net/URL;)Lorg/codehaus/jackson/JsonNode

I'm on Spark 2.3.

Thanks!

**Comment by hcho3** [comment]
Double check if you are using correct Scala version (2.11). Also, print out the dependency tree (run `mvn dependency:tree -Dverbose -Dincludes=commons-collections`) and see if there's any conflicting package versions

**Comment by ZhenyiLin** [comment]
I met an exactly same issue, I guess it is because I'm using SPARK2-2.3.0.cloudera2, while Upstream XGBoost is not guaranteed to work with third-party distributions of Spark, such as Cloudera Spark.

**Comment by phillyfan1138** [comment]
Interesting!  I'm on cloudera as well.  The fact that its complaining about an old version of jackson makes me think that the problem is fixable.  I just haven't found the solution yet.

**Comment by CodingCat** [comment]
No official support on anything other than apache spark, no official support on pyspark (coming in 1.0 release)

Why there is jackson issue? Jackson itself brings some breaking changes, leading to spark doesn’t have cross-version binary compatibility, then when we compile xgboost with spark, it also suffers from that...cloudera is very likely to mask the change of jackson cross their own spark version and therefore becomes binary inconsistent with apache spark which is what xgb compiled against...so...yeah, hard to resolve...

**Comment by ZhenyiLin** [comment]
Tested 0.82 version in local mode Apache Spark 2.3.3, not see Jackson readTree issue anymore.
