### ISSUE TITLE
[VOTE] Ending Python 2.x support in next release (0.83)

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#4379]
Given that Python 2 will reach its end of life at the end of this year, we should drop Python 2 support. That is, contributors would no longer be required to write Python code that's compatible with Python 2.7. Also, Python distributions of XGBoost on PyPI will be Python 3 exclusive.

Indicate your support by replying "+1" to this thread. I want to get 4-5 votes from the committers to proceed with this decision. (Others, feel free to voice support with +1 reply as well, although only committers will have binding votes.)

@dmlc/xgboost-committer

**Comment by terrytangyuan** [comment]
Definitely +1

**Comment by trivialfis** [comment]
+1.  

We need to upgrade Python on test farm then.

**Comment by RAMitchell** [comment]
+1

**Comment by CodingCat** [comment]
+1

**Comment by hcho3** [comment]
+1

**Comment by pommedeterresautee** [comment]
+1

**Comment by tqchen** [comment]
+1

**Comment by hcho3** [comment]
With 7 votes from committers, it is decided that **the upcoming release (0.83) will support Python 3 exclusively.** I filed #4381 to migrate pylint to Python 3, and #4380 will use Python 3 exclusively for all CI tests. Thanks!

**Comment by CAM-Gerlach** [comment]
Given the major status of this project and the major importance of this project to the scientific Python community, you should consider adding your name and logo to [Python3Statement.org](https://python3statement.org/) of projects planning to drop support for Python 2 on or before Jan 1 2020, to maximize public visibility of your support timeline in a central location, and help send the message that remaining Python 2 users should start transitioning now to minimize the pain later. To add XGBoost, you can just [submit a simple PR](https://github.com/python3statement/python3statement.github.io/pulls) to the Python3Statement repo with your name and logo—a SVG or transparent PNG of this would be ideal:

![image](https://user-images.githubusercontent.com/17051931/57117419-e8e63b00-6d29-11e9-90d9-a09e931b7cfe.png)

Or, if you like, I can create a PR for you there and @hcho3 can sign off, if you want. Thanks!

**Comment by hcho3** [comment]
@CAM-Gerlach Yes, we'd love to put our logo there. Can you go ahead and create a PR on our behalf? I'll sign it off.

**Comment by CAM-Gerlach** [comment]
@hcho3 Sure; I'll go ahead and tag you there. Thanks!

**Comment by CAM-Gerlach** [comment]
@hcho3 Particularly since it is ending Python 2 support before 2020, it would be really nice to have the project in the timeline. What date should I put for the beginning of Python 3 support (or has it always supported Python 3 since the first release in 2014)? I couldn't find any info on this in the obvious places (Trove classifiers, .travis.yml/appveyor.yml, release notes, readme, etc).

Also, is there an approx release date for 0.90 (it doesn't have to be exact, just the likely date of release assuming Spark 2.4.3 drops on as planned on or about May 5 (which it looks it will) and implementing the remaining items for #4389 go according to plan; due to the long time span of the charge, a difference of up to a couple weeks from the actual won't really be visible.

**Comment by hcho3** [comment]
@CAM-Gerlach XGBoost has been tested with Python 3.x for a long while. At PyPI, we have been distributing "universal" wheels of XGBoost that are both Python 2 and 3 compatible. See https://pypi.org/project/xgboost/#files.

Only change with 0.90 release is that we will no longer make guarantee about supporting Python 2. We hope to make 0.90 by middle of May, assuming we can address the items in the Roadmap.

**Comment by CAM-Gerlach** [comment]
> XGBoost has been tested with Python 3.x for a long while. 

Okay, so about what rough timeframe should I put down for that, then?

**Comment by hcho3** [comment]
At least since Nov 2015, based on this commit: https://github.com/dmlc/xgboost/commit/25c4fbd0cb5cbb8ad06533f5a6d147559d424563. This commit adds a compatibility layer to support Python 2 and 3.
