### ISSUE TITLE
Google Season of Docs application?

### ISSUE THREAD

**Issue by thvasilo** [dmlc/xgboost#4384]
I just noticed [this](https://developers.google.com/season-of-docs/) because Apache Flink applied for the project. It's an effort by Google to get technical writers to contribute to open source projects. Deadline is unfortunately on April 23rd which is soon, just thought the community might be interested in applying.

**Comment by hcho3** [comment]
Interesting idea. Unfortunately, none of us have shovel-ready ideas right now. We'll try next time.

**Comment by hcho3** [comment]
FYI, I am serving as a mentor for Google Summer of Code: #4242. This will keep me plenty busy.
