### ISSUE TITLE
XGBRegressor: wildly different .predict() values after upgrading to 0.82

### ISSUE THREAD

**Issue by dlhvelasco** [dmlc/xgboost#4392]
Hello. Not exactly sure how I can make my problem reproducible, but here's something weird I've noticed a few times:

I have two conda envs, `envA` running `xgboost 0.81` and `envB` running `0.82`.
I have a fixed training dataset where I fit an XGBRegressor (scikit) on, then predict values on a fixed test dataset, random seeds fixed. Then I take the score, lets say RMSE, for the predictions.
Finally, I then use the model to predict on an fixed, unlabeled, external dataset.

When I do the workflow above using `envA`, I'm getting an RMSE of somewhere like 10 units.
Same with `envB`, RMSE of around 10 units.

Now, when I predict on the external dataset using the model trained with `envA`, I get a range of 50-250 units (which is what I'm expecting).
However, when I predict on the external dataset using `envB`, I'm getting a range of 40-60 units-- which is weird, since I made sure that everything (all datasets, all parameters) was fixed. 
As for the parameters, I made sure to only use params that were both present in `0.81` and `0.82`.

Any thoughts on why this difference might have occurred? Thanks.

Note: using python 3.6.7, scikit-learn 0.20.3 for both

**Comment by hcho3** [comment]
Can you run get_dump() on both models and compare them?

In general, we do not guarantee that training would be reproducible between different versions. To get reproducible results, you should save the trained models as files, using save_model() and load them using load_model().

**Comment by trivialfis** [comment]
@dlhvelasco Could you share some more details like used parameters?

**Comment by dlhvelasco** [comment]
@hcho3 , I'll get back to you on the get_dump() for both models since I'm currently using the sklearn wrapper. I also have been saving/loading both models as pickles (.pkl) files.

@trivialfis Sure, here's what I used for both xgbregressors:
`xgb = XGBRegressor(random_state=42, n_jobs=8, max_depth=11, min_child_weight=1, gamma=0.01, subsample=0.8, learning_rate=0.05, reg_alpha=0, reg_lambda=1, n_estimators=2500)`

**Comment by hcho3** [comment]
Any updates?

**Comment by dlhvelasco** [comment]
Right, sorry for the delay. The issue seems to have fixed itself after I remade the two conda envs. 
Must have been an issue on my end. Thanks again.

Closing this issue.
