### ISSUE TITLE
travis xgboost.core.XGBoostError: XGBoost Library (libxgboost.so) could not be loaded.

### ISSUE THREAD

**Issue by danielSoler93** [dmlc/xgboost#4394]
Hi,

I'm trying to use travis with xgboost and its giving me the next error (https://travis-ci.com/danielSoler93/ModTox/jobs/194851834) with the following configuration (https://github.com/danielSoler93/ModTox/blob/master/.travis.yml).

I've seen some similar issues which have been solved but didn't help my situation. I would appreciate some help as I've been stuck for a couple of days.

Thanks

**Comment by hcho3** [comment]
@danielSoler93 See tensorforce/tensorforce#303. Can you reduce the number of Python modules you are loading? There is a system-wide limit on how many *.so files you can load that use TLS (Thread-Local Storage).

**Comment by hcho3** [comment]
@danielSoler93 Any updates?

**Comment by danielSoler93** [comment]
Sorry, I've been extremely busy with a couple of other things let me give it a try today and I'll get back to you. Thanks for the help

**Comment by danielSoler93** [comment]
@hcho3 I've solved the issue by changing the order of the imports as stated in the reference you sent me.  Thanks to give me a hand

**Comment by Brajen259** [comment]
@hcho3 I am getting a similar error while importing xgboost. I am using dmlc xgboost on hadoop. How to reduce the number of python files ?
