### ISSUE TITLE
Implement bart.

### ISSUE THREAD

**Issue by trivialfis** [dmlc/xgboost#4398]
Hi all,

## Introduction
Recently I have been reading **[Bayesian Additive Regression Tree](https://arxiv.org/pdf/0806.3286.pdf)** and started to implement it on top of XGBoost.  It's a tree ensemble model with MCMC(modified gibbs) sampling for structure learning.  Recent years some variances have been proposed, mostly tuning the sampling method to get higher performance or lower computation cost.  Currently I'm still trying to get a grasp for the original version.

Although XGBoost itself is a gradient boosting framework, but exception like random forest is also implemented in the library.  I would like to know the interest in this subject.  If the algorithm is accepted as part of XGBoost, I will try to implement it as a plugin for initial support.

## Existing implementation
The algorithm has been implemented many times as R package:
- [bart machine](https://github.com/cran/bartMachine)
- [bart](https://github.com/cran/BART.git)
- [bart bma](https://github.com/BelindaHernandez/BART-BMA.git)
- and the original implementation.

Also one WIP Python project:
- [bartpy](https://github.com/JakeColtman/bartpy)

I don't quite understand the R packages' source code so am only familiar with bartpy.

## My plan
Even though currently I'm still at "trying to do it", but already have over 1000 lines of code added so it's not trivial.  If the model is accepted I will first submit a naive implementation that can be reviewed.

@tqchen @hcho3 @RAMitchell @CodingCat

**Comment by hcho3** [comment]
@trivialfis This is interesting. I will need to give myself some time to review the paper.

I think you should do either 1) write a RFC to explain your (software) design, in the form similar to dmlc/tvm#2889 OR 2) write a draft pull request that can be easily reviewed.
