### ISSUE TITLE
Gradient and Hessian of RMSLE

### ISSUE THREAD

**Issue by med96** [dmlc/xgboost#4402]
I'm trying to implement the RMSLE custom function to train XGBoost, but I'm getting a constant training and validation error.

Here is my function:

    def RMSLE(ypred, dtrain):
    y = dtrain.get_label()
    return np.sqrt(np.mean((np.log1p(ypred) - np.log1p(y)) ** 2))

    #### Returns GRADIENT, HESSIAN of the RMSLE function

    def RMSLEobj(ypred, dtrain):
        y = dtrain.get_label()
        N = len(y)
        grad = (1/(N * RMSLE(ypred, dtrain) )) * (np.log1p(ypred) - np.log1p(y)) / (1 + y)
        hess = ( ( 1/ (ypred + 1) * (y + 1) * N )  - grad ** 2) / RMSLE(ypred, dtrain)
        return grad, hess

Can someone help me figure it out?

Thanks in advance!

**Comment by trivialfis** [comment]
@med96 Can you specify XGBoost version and complete parameters set you used?  I tried to use default parameter on my local branch and didn't see any error.

**Comment by trivialfis** [comment]
@med96 Any update?  Could you provide a reproducible script without using pickle?

Don't close this for now.
