### ISSUE TITLE
Problem that gamma cannot live with gpu_exact

### ISSUE THREAD

**Issue by panranyang** [dmlc/xgboost#4405]
Here's some information of my computer.
CUDA version: 8.0.44
Driver version:390.87
GPU:  GTX 1080  * 2

my code is like: 

params={'tree method': 'gpu_exact', 'objective': 'reg:linear', 'max_depth': 6, 'eta': 0.1, 'lambda‘: 2}
xgboost.train(params, train_data, train_rounds)

It can works fine but when gamma in params( params['gamma'] = 5, I get 

Kernel error:
In: /workspace/include/xgboost/./../../src/common/span.h, 	line: 489
	T &xgboost::common::Span<T, Extent>::operator[](long) const [with T = xgboost::detail::GradientPairInternal<float>, Extent = -1L]
	Expecting: _idx >= 0 && _idx < size()
Traceback (most recent call last):
  File "benchmark_tree.py", line 94, in <module>
    main()
  File "benchmark_tree.py", line 90, in main
    run_benchmark(args)
  File "benchmark_tree.py", line 69, in run_benchmark
    xgb.train(param, dtrain, args.iterations, evals=[(dtest, "test")])
  File "/usr/anaconda/lib/python2.7/site-packages/xgboost/training.py", line 216, in train
    xgb_model=xgb_model, callbacks=callbacks)
  File "/usr/anaconda/lib/python2.7/site-packages/xgboost/training.py", line 74, in _train_internal
    bst.update(dtrain, i, obj)
  File "/usr/anaconda/lib/python2.7/site-packages/xgboost/core.py", line 1110, in update
    dtrain.handle))
  File "/usr/anaconda/lib/python2.7/site-packages/xgboost/core.py", line 178, in _check_call
    raise XGBoostError(_LIB.XGBGetLastError())
xgboost.core.XGBoostError: [18:13:30] /workspace/src/tree/updater_gpu.cu:602: grow_gpu exception: [18:13:30] /workspace/include/xgboost/./../../src/common/common.h:41: /workspace/src/tree/../common/device_helpers.cuh: 274: unspecified launch failure

Stack trace returned 10 entries:
[bt] (0) /usr/anaconda/xgboost/libxgboost.so(dmlc::StackTrace(unsigned long)+0x47) [0x7fa83b5cafc7]
[bt] (1) /usr/anaconda/xgboost/libxgboost.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x1d) [0x7fa83b5cb42d]
[bt] (2) /usr/anaconda/xgboost/libxgboost.so(dh::ThrowOnCudaError(cudaError, char const*, int)+0x123) [0x7fa83b79d153]
[bt] (3) /usr/anaconda/xgboost/libxgboost.so(xgboost::tree::Dense2SparseTree(xgboost::RegTree*, dh::DVec<xgboost::tree::DeviceNodeStats> const&, xgboost::tree::TrainParam const&)+0x75) [0x7fa83b81ed65]
[bt] (4) /usr/anaconda/xgboost/libxgboost.so(xgboost::tree::GPUMaker::Update(xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*, xgboost

If tree_method='exact'，code can work fine with gamma.

**Comment by trivialfis** [comment]
@RAMitchell This is awkward,  everything I try to reproduce this bug my machine freeze ...

**Comment by trivialfis** [comment]
Closing as we decided to deprecate gpu_exact and encourage the use of gpu_hist, which is more efficient.
