### ISSUE TITLE
[jvm-packages] SparkMLlibPipeline example in xgboost4j-example causes error "rabit::Init is already called in this thread"

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#4406]
I ran spark-submit on two Spark examples in xgboost4j-example as follows:
```
spark-submit --class ml.dmlc.xgboost4j.scala.example.spark.SparkTraining  \
  --master 'local[8]' \
  ./target/xgboost4j-tester-1.0-SNAPSHOT-jar-with-dependencies.jar \
  /workspace/jvm-packages/xgboost4j-tester/iris.csv
spark-submit --class ml.dmlc.xgboost4j.scala.example.spark.SparkMLlibPipeline  \
  --master 'local[8]' \
  ./target/xgboost4j-tester-1.0-SNAPSHOT-jar-with-dependencies.jar  \
  /workspace/jvm-packages/xgboost4j-tester/iris.csv  \
  /workspace/jvm-packages/xgboost4j-tester/native_model  \
  /workspace/jvm-packages/xgboost4j-tester/pipeline_model
```

The first spark-submit ran successfully, but the second spark-submit crashes with error
```
rabit::Init is already called in this thread
```

See the full log at https://xgboost-ci.net/blue/organizations/jenkins/xgboost/detail/PR-4401/15/pipeline/204#step-249-log-1296.

**Comment by CodingCat** [comment]
we have a bug in calling rabit.init() in spark, 

I believe even you only run the second test, SparkMLlibPipeline, it also failed

**Comment by hcho3** [comment]
@CodingCat Was this bug around for a while?

**Comment by CodingCat** [comment]
@hcho3 I think so, I am verifying that, because we usually will not evaluate the dataframe containing predictions for twice so it is not triggered......

**Comment by CodingCat** [comment]
this bug was introduced in https://github.com/dmlc/xgboost/commit/2d875ec0197d5a83e7d585daf472b8201aa97c51

**Comment by CodingCat** [comment]
working on a fix

**Comment by hcho3** [comment]
@CodingCat Thanks!

**Comment by CodingCat** [comment]
Rabit part fix: https://github.com/dmlc/rabit/pull/92
