### ISSUE TITLE
[BLOCKING][jvm-packages] upgrade and test with spark 2.4.3

### ISSUE THREAD

**Issue by CodingCat** [dmlc/xgboost#4409]
well....some issues happened in the recent release of Spark, essentially 

2.4.1 has a serious bug

2.4.2 has some issue in scala support (we may not be affected, tho)

2.4.3 is coming

so let's wait for more days to upgrade to 2.4.3 and ensure everything is OK

**Comment by hcho3** [comment]
> 2.4.1 has a serious bug

Any link?

**Comment by CodingCat** [comment]
http://apache-spark-developers-list.1001551.n3.nabble.com/Spark-2-4-2-td27040.html#a27048

**Comment by hcho3** [comment]
@CodingCat For now, I can add a test with Spark 2.4.2

**Comment by CodingCat** [comment]
@hcho3 , yeah, I think we can just test with 2.4.2 (drop the original 2.4.1 test)
