### ISSUE TITLE
Error in python custom objective demo?

### ISSUE THREAD

**Issue by hcz28** [dmlc/xgboost#4410]
In the custom objective demo,
https://github.com/dmlc/xgboost/blob/77c03538b0db2e3608ef07ddcf9b48325584dbee/demo/guide-python/custom_objective.py#L21
it seems that the parameter pred means the untransformed margin value. However, when the custom objective func is called at
https://github.com/dmlc/xgboost/blob/77c03538b0db2e3608ef07ddcf9b48325584dbee/python-package/xgboost/core.py#L1112
the pred is calculated by
https://github.com/dmlc/xgboost/blob/77c03538b0db2e3608ef07ddcf9b48325584dbee/python-package/xgboost/core.py#L1111
which means it gives the transformed prediction result.
So is there anything wrong? Does the pred means the raw margin or transformed value?

**Comment by hcho3** [comment]
> which means it gives the transformed prediction result.

No, that line gives untransformed margin.
