### ISSUE TITLE
Update gaming example in documentation

### ISSUE THREAD

**Issue by sararob** [dmlc/xgboost#4418]
The gaming example used to introduce decision trees on [this page](https://github.com/dmlc/xgboost/blob/master/doc/tutorials/model.rst) claims men are 20x more likely to like computer games than women. I know it's just an example, but it's subtly sexist and incorrect. According to [this report](http://www.theesa.com/wp-content/uploads/2018/05/EF2018_FINAL.pdf), 45% of gamers in the US are women. I'm suggesting updating the example to be more accurate (would only require updating the images) or choosing an example that doesn't use age or gender.

I've drafted updates for the first 2 images on that page, but wanted to get feedback before submitting a PR:

<img width="649" alt="Screen Shot 2019-04-29 at 5 51 59 PM" src="https://user-images.githubusercontent.com/3814898/56933125-7b7da480-6ab4-11e9-9963-8a9638cb4d90.png">
<img width="1664" alt="Screen Shot 2019-04-29 at 7 25 34 PM" src="https://user-images.githubusercontent.com/3814898/56933156-a962e900-6ab4-11e9-8be1-ee9173787653.png">

**Comment by hcho3** [comment]
@sararob Thanks for the new diagrams. Can you file a pull request at https://github.com/dmlc/web-data? The images that should be replaced are:
* xgboost/model/cart.png
* xgboost/model/twocart.png

**Comment by sararob** [comment]
Thanks for the fast response! Should I also replace the last 2 images on that page since they use the same example?

**Comment by hcho3** [comment]
Yes

**Comment by tqchen** [comment]
Thanks @sararob for bringing this up. This was completely my mistake and I do hope to fix this ASAP. I did a parallel fix without checking this issue. But we would be more than happy to incorporate your example and perhaps rename the title to be less factual, e.g. about a hypothetical computer game X.

**Comment by sararob** [comment]
@tqchen thanks for putting in a fix so quickly. I really like your new example of "likes computer game X" since a specific game could appeal more to certain age groups. I'm happy to provide input / contribute to new examples in the future. Thanks again! Feel free to close.
