### ISSUE TITLE
Question about thread number

### ISSUE THREAD

**Issue by daiyl0320** [dmlc/xgboost#444]
I just predict a few single inst with xgboost online prediction. but the cpu is about up to 400%. I debug it and found that it is because xgboost would start thread. I use SetParam("nthread", "0") but it did not work. why? 

thx.

**Comment by pommedeterresautee** [comment]
Can you try 1 instead 0?
Is there reasons you want to limit the number of cpu core used?

**Comment by daiyl0320** [comment]
I tried 1 ,4 ,10，it also did not work....i build xgboost without openmp and the online prediction works well. but i guess it will lost performance during training.

**Comment by pommedeterresautee** [comment]
Yeah, parallel training and the xgboost matrix format are the two main reasons why xgboost has so good performance.

Can you explain why you don't want parallel prediction? May be there is something else to do than disabling all parallel execution?

**Comment by tqchen** [comment]
nthread=1 should work for such case. 

We do need a better API for predicting few cases in the future

**Comment by daiyl0320** [comment]
I use online prediction interface: Predict(const SparseBatch::Inst &inst, std::vector<float>* preds) 
I did not use the matrix interface cause the data to be predicted is coming one by one. So I think the when we do online prediction, we would not set up parallel prediction.

I do use learner.SetParam("nthread", "1"), it did not work. ~.~

thanks

**Comment by jasmineol** [comment]
@tqchen , I use online prediction interface: Predict(const SparseBatch::Inst &inst, std::vector* preds), cuz in my module the data to be predicted is coming one by one. but i found the time token is more than 20ms in usual situation, my module is a real-time module, so i hope it can predict very quickly. which param can i set to reach this target? thanks!

**Comment by nareshsankapelly** [comment]
Looks like setting OMP_NUM_THREADS to 1 is the only way to solve this.
