### ISSUE TITLE
[jvm-packages] xgboost training has been stuck.No information output

### ISSUE THREAD

**Issue by charmby** [dmlc/xgboost#4441]
hi,I training a model with xgboost.
After loading the sample，my training job  is stuck. like this
![image](https://user-images.githubusercontent.com/6927947/57197127-f0aa1780-6f95-11e9-97c8-fd30db4d4136.png)
![image](https://user-images.githubusercontent.com/6927947/57197131-fef83380-6f95-11e9-9385-88363b6b4b86.png)
![image](https://user-images.githubusercontent.com/6927947/57197183-a83f2980-6f96-11e9-8e74-0702b3a75989.png)
The stage's DAG like this.
![image](https://user-images.githubusercontent.com/6927947/57197192-cc026f80-6f96-11e9-94a9-0b73dab70025.png)
The thread dump for one of the executors show the following.
![image](https://user-images.githubusercontent.com/6927947/57197212-256a9e80-6f97-11e9-81be-8fe0edb85fd7.png)

There is no executor  log and driver log after hung.
![image](https://user-images.githubusercontent.com/6927947/57197065-4cc06c00-6f95-11e9-81ff-ddea62225a86.png)

The main code snippets
```
 val xgbClassifier = new XGBoostClassifier(runParams).
            setFeaturesCol(SampleSchemaField.FEATURES_COL_NAME).
            setLabelCol(SampleSchemaField.LABEL)
        val xgbClassificationModel: XGBoostClassificationModel = xgbClassifier.fit(trainExamples)
```
Sample size is 7.5G and The number is about 60 million.

this maven dependency for me.
```
<dependency>
            <groupId>ml.dmlc</groupId>
            <artifactId>xgboost4j-spark</artifactId>
            <version>0.81</version>
 </dependency>
 <spark.version>2.3.2</spark.version>
<java.version>1.7</java.version>
<scala.version>2.11.8</scala.version>
```
Can anyone answer this questions?
Thank you so much

**Comment by CodingCat** [comment]
what's `runParams` in your code and how many cores you allocate to your spark application?

**Comment by charmby** [comment]
> what's `runParams` in your code and how many cores you allocate to your spark application?

Thank you very much for your reply.this is my runParams.
```
>>>>>Training run params : Map(alpha -> 0.1, min_child_weight -> 1, lambda_bias -> 0, silent -> 1, num_workers -> 100, subsample -> 1, lambda -> 2, max_depth -> 6, objective -> binary:logistic, eval_metric -> logloss, num_round -> 200, eta -> 0.1, booster -> gbtree, gamma -> 0, nthread -> 1, frac_test -> 0.2)
```
and spark conf
```
--driver-memory 15G --executor-memory 14G --num-executors 100 --executor-cores 1 --conf spark.yarn.executor.memoryOverhead=8192
--conf spark.default.parallelism=128 --conf spark.sql.shuffle.partitions=1024 --conf spark.closure.serializer=org.apache.spark.serializer.KyroSerializer --conf spark.io.compression.codec=lz4 --conf spark.executor.extraJavaOptions=-XX:+UseConcMarkSweepGC --conf spark.core.connection.ack.wait.timeout=300 --conf spark.dynamicAllocation.enabled=false
```

**Comment by charmby** [comment]
Who met this problem？Could you give me some advice？

**Comment by CodingCat** [comment]
double check your code, why you set num_workers as 100 but got 200 tasks in foreachPartitiom stage?

**Comment by charmby** [comment]
> double check your code, why you set num_workers as 100 but got 200 tasks in foreachPartitiom stage?
num_workers =100，but spark config args --num-executors 200

**Comment by CodingCat** [comment]
8 days ago, you told that `--num-executors 100`, now you say `--num-executors 200`?

and num of executors will not change the number of tasks, 

based on what you said 8 days ago, your xgb app needs 200 workers to train but your app only has 100 cores....this is the reason your app stuck
