### ISSUE TITLE
Early Stop in Python (IndexError: list index out of range)

### ISSUE THREAD

**Issue by michal-demecki-profil-software** [dmlc/xgboost#4443]
https://github.com/dmlc/xgboost/blob/5de7e12704b38d81a46471e02a791d4c586a7286/python-package/xgboost/callback.py#L225

While using `TimeSeriesSplit` as cv for `GridSearchCV`,  `early_stop.callback` function may receive empty `evaluation_result_list`.
When it occur error is raised (`IndexError: list index out of range`)

**Comment by trivialfis** [comment]
@michal-demecki-profil-software Thanks for the issue.  Could you make a reproducible example?

**Comment by trivialfis** [comment]
@michal-demecki-profil-software Any update?

**Comment by jier** [comment]
I have one reproducable error
`xgb_params = {"objective": "rank:pairwise", "eta": 0.0001, "max_depth": 7, "seed": 0, "verbosity": 0,\
                    "eval_metric": "ndcg@5", "nthread": -1, "subsample":0.5, "colsample_bytree":0.5,
                    "min_child_weight":1,"reg_lambda":1, "reg_alpha":0,"max_delta_step":0.5,"scale_pos_weight":0.3,
                    "colsample_bylevel":0.5, "n_jobs":-1,"min_split_loss":15}
        num_rounds = 10000


        dtrain = xgb.DMatrix(pd.DataFrame(X_TRAIN[features_to_train]), label=Y_TRAIN)
        dtrainb = xgb.DMatrix(pd.DataFrame(X_TRAIN[features_to_train]), label=Y_TRAIN_B)

        if locally:

            eval_result = {}
            eval_resultb = {}
            dtest = xgb.DMatrix(X_TEST[features_to_train], label=Y_TEST)
            watchlist = [(dtest, 'eval_click'),(dtrain,'train_click')]
            dtestb = xgb.DMatrix(X_TEST_B[features_to_train], label=Y_TEST_B)
            watchlistb = [(dtestb, 'eval_book'),(dtrainb,'train_book')]
            gbdt = xgb.train(xgb_params, dtrain, num_rounds,watchlist, maximize=False, early_stopping_rounds=num_rounds*0.1,\
                            evals_result=eval_result)
            gbdtb = xgb.train(xgb_params, dtrainb, num_rounds,watchlistb, maximize=False, early_stopping_rounds=num_rounds*0.1,\
                            evals_result=eval_resultb)
            label = dtest.get_label()
            dtest_origin = xgb.DMatrix(X_TEST[features_to_train], label=Y_TEST)
            dtest_originb = xgb.DMatrix(X_TEST_B[features_to_train],label=Y_TEST_B)
            ypred_click = gbdt.predict(dtest_origin, ntree_limit=num_rounds)
            ypred_book = gbdtb.predict(dtest_originb, ntree_limit=num_rounds)
            importance = gbdt.get_fscore()
            importance = sorted(importance.items(), key=operator.itemgetter(1))
            print("Importance click ", importance)
            print("--------------------------------")
            importanceb = gbdtb.get_fscore()
            importanceb = sorted(importanceb.items(), key=operator.itemgetter(1))
            print("Importance book ", importanceb)
            print('Error of clicking ypred_click=%f'% (np.sum((ypred_click> 0.5) != label)/float(len(label))))
            print('Error of booking ypred_book=%f'% (np.sum((ypred_book> 0.5) != label)/float(len(label))))
        else:
            gbdt = xgb.train(xgb_params, dtrain, num_rounds, maximize=False, early_stopping_rounds=num_rounds)
            gbdtb = xgb.train(xgb_params, dtrainb, num_rounds, maximize=False, early_stopping_rounds=num_rounds)
`
In this else statement I get the same error. I try to read a really  big test-set

**Comment by hcho3** [comment]
@jier Can you post the dataset `X_TRAIN`?

**Comment by jier** [comment]
train = pd.read_csv("../training_set_VU_DM.csv", nrows=10000)
X_TEST = pd.read_csv("../test_set_VU_DM.csv")
Both dataset contains at least million rows, pd stands for pandas. So my purpose was just to investigate if the xgboost could train on this small train-set and fit on the huge test-set. Both dataset are modified from the original Kaggle competition: Expedia Hotel Ranking problem.
