### ISSUE TITLE
[jvm-packages] Why not support positional metrics like ndcg@5?

### ISSUE THREAD

**Issue by shishaochen** [dmlc/xgboost#4444]
Currently, allowed eval metrics are listed at [LearningTaskParams.scala](https://github.com/dmlc/xgboost/blob/master/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/LearningTaskParams.scala#L114).
```scala
  val supportedEvalMetrics = HashSet("rmse", "mae", "logloss", "error", "merror", "mlogloss",
    "auc", "aucpr", "ndcg", "map", "gamma-deviance")
```
Here comes the problem, metric names like "ndcg@5" is illegal when set in Spark APIs.
Why not support positional metrics in XGBoost Spark? Thanks a lot!

**Comment by CodingCat** [comment]
a PR is welcome

**Comment by CodingCat** [comment]
resolved in master branch
