### ISSUE TITLE
Allowing dynamic linking of NCCL

### ISSUE THREAD

**Issue by jakirkham** [dmlc/xgboost#4445]
Appears that [NCCL's static library is used](  https://github.com/dmlc/xgboost/blob/ade3f302373cf630f5115aca26cb40ea9cac78ac/cmake/modules/FindNccl.cmake#L36 ) when building xgboost. Am curious if it would be reasonable to allow users to dynamically link instead or as an alternative to static linking.

**Comment by hcho3** [comment]
@jakirkham Static linking is used here so that multi-GPU training works "out of the box". Many users will install XGBoost by running `pip install xgboost`, without necessarily installing NCCL first. Is there a scenario where dynamic linking would be necessary?

**Comment by trivialfis** [comment]
@hcho3  Actually I would like to do that.  We stay with static by default, but add an option for dynamic linking.  To me, the reason is the same with dmlc-core, see  #4360 .

**Comment by hcho3** [comment]
@trivialfis I see that dynamic linking of NCCL may be desirable when XGBoost is used as a dependency to another application (via CMake exported target). Especially when that application itself is using NCCL.

**Comment by trivialfis** [comment]
Code bloat is fine, it's nothing close to DL library.  The problem is it leads to undefined behaviour when we have functions with same signature but different implementation.

**Comment by hcho3** [comment]
@trivialfis Meaning two versions of NCCL co-existing?

**Comment by trivialfis** [comment]
@hcho3 See https://github.com/trivialfis/xgbissues/tree/master/%234360

**Comment by hcho3** [comment]
@trivialfis I don't think that link is exactly applicable to the case of NCCL, since we are not including the NCCL source code. We are importing the static library pre-compiled by NVIDIA.

**Comment by trivialfis** [comment]
The example above imports statically compiled version of `lib.h` in middle user, `lib.h` can be nccl,  `middleuser.cc` can be XGBoost.  And `finaluser.cc` can be users of XGBoost.

**Comment by hcho3** [comment]
Got it. So to prevent undefined behavior, we want to de-duplicate dependencies, including dmlc-core and NCCL.

**Comment by trivialfis** [comment]
@hcho3

**Comment by trivialfis** [comment]
Yes.  That would be my reason.

**Comment by jakirkham** [comment]
Another use case for shared libraries is in package management. Namely we are able to create smaller packages and better track relationships between them by building shared libraries and creating explicit dependencies between upstream and downstream packages that need these shared libraries.
