### ISSUE TITLE
Dynamic linking to CUDA runtime libraries

### ISSUE THREAD

**Issue by jakirkham** [dmlc/xgboost#4450]
It appears that the CUDA runtime libraries from cudatoolkit are getting statically linked. IIUC this is something that CMake itself is doing.

Previously one could use [`CUDA_USE_STATIC_CUDA_RUNTIME`]( https://cmake.org/cmake/help/v3.3/module/FindCUDA.html ) to configure whether static linkage is used or not. However that variable no longer seems to have an effect when switching to CUDA as a language. As a result CMake will statically link by default. There is some discussion in issue [cmake#17559]( https://gitlab.kitware.com/cmake/cmake/issues/17559 ) about how this should be fixed in CMake and how it might be worked around short-term.

IDK if it would be reasonable for xgboost to adopt a workaround like this, but it would be useful as an end user. Also wanted to bring it up for awareness and discussion.

**Comment by trivialfis** [comment]
@jakirkham Thanks for bringing this up.  I think I'm gonna leave it to CMake's default.

The static runtime is useful here.  Default pip package is compiled with CUDA support, but it also runs on platforms that don't have GPU support.  Static library acts as a stub for these platforms.  It's an 800K binary so it should be fine for packaging.

**Comment by jakirkham** [comment]
Thanks for the follow-up.

Yeah, that seems reasonable. It's also probably better to look into getting this option back into CMake.

Feel free to close this issue.
