### ISSUE TITLE
Recipe for target 'data.o' failed

### ISSUE THREAD

**Issue by yz-nju** [dmlc/xgboost#4456]
I failed to compile xgboost in 64-bit windows with both git-bash and mingw32-make. I followed the steps in https://xgboost.readthedocs.io/en/latest/build.html#building-on-windows, but always fail when compile dmlc-core/src/data.cc

<details>
<summary>click to see details</summary>
<pre><code>
g++ -c -O3 -Wall -Wno-unknown-pragmas -Iinclude -std=c++0x -fPIC -DDMLC_USE_HDFS=0 -DDMLC_USE_S3=0 -DDMLC_USE_AZURE=0  -msse2 -o data.o src/data.cc
src/data.cc:1:0: warning: -fPIC ignored for target (all code is position independent)
 // Copyright by Contributors
 ^
In file included from src/data/./libsvm_parser.h:19:0,
                 from src/data/disk_row_iter.h:19,
                 from src/data.cc:12:
src/data/././text_parser.h: In instantiation of 'dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*)::<lambda()>::<lambda()> [with IndexType = long long unsigned int; DType = long long int]':
src/data/././text_parser.h:135:37:   required from 'struct dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*)::<lambda()> [with IndexType = long long unsigned int; DType = long long int]::<lambda()>'
src/data/././text_parser.h:124:7:   required from 'dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*)::<lambda()> [with IndexType = long long unsigned int; DType = long long int]'
src/data/././text_parser.h:123:70:   required from 'struct dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = long long unsigned int; DType = long long int]::<lambda()>'
src/data/././text_parser.h:123:22:   required from 'bool dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = long long unsigned int; DType = long long int]'
src/data/././text_parser.h:46:20:   required from 'bool dmlc::data::TextParserBase<IndexType, DType>::ParseNext(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = long long unsigned int; DType = long long int]'
src/data.cc:258:1:   required from here
src/data/././text_parser.h:125:51: error: redeclaration of 'const int& nthread'
         size_t nstep = (chunk.size + nthread - 1) / nthread;
                                                   ^
src/data/././text_parser.h:125:36: note: 'const int& nthread' previously declared here
         size_t nstep = (chunk.size + nthread - 1) / nthread;
                                    ^
src/data/././text_parser.h:127:37: error: redeclaration of 'const int& tid'
         size_t send = std::min((tid + 1) * nstep, chunk.size);
                                     ^
src/data/././text_parser.h:126:38: note: 'const int& tid' previously declared here
         size_t sbegin = std::min(tid * nstep, chunk.size);
                                      ^
src/data/././text_parser.h:130:17: error: redeclaration of 'const int& tid'
         if (tid + 1 == nthread) {
                 ^
src/data/././text_parser.h:126:38: note: 'const int& tid' previously declared here
         size_t sbegin = std::min(tid * nstep, chunk.size);
                                      ^
src/data/././text_parser.h:130:21: error: redeclaration of 'const int& nthread'
         if (tid + 1 == nthread) {
                     ^
src/data/././text_parser.h:125:36: note: 'const int& nthread' previously declared here
         size_t nstep = (chunk.size + nthread - 1) / nthread;
                                    ^
src/data/././text_parser.h:135:42: error: redeclaration of 'const int& tid'
         ParseBlock(pbegin, pend, &(*data)[tid]);
                                          ^
src/data/././text_parser.h:126:38: note: 'const int& tid' previously declared here
         size_t sbegin = std::min(tid * nstep, chunk.size);
                                      ^
src/data/././text_parser.h: In instantiation of 'dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*)::<lambda()> [with IndexType = long long unsigned int; DType = long long int]':
src/data/././text_parser.h:123:70:   required from 'struct dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = long long unsigned int; DType = long long int]::<lambda()>'
src/data/././text_parser.h:123:22:   required from 'bool dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = long long unsigned int; DType = long long int]'
src/data/././text_parser.h:46:20:   required from 'bool dmlc::data::TextParserBase<IndexType, DType>::ParseNext(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = long long unsigned int; DType = long long int]'
src/data.cc:258:1:   required from here
src/data/././text_parser.h:124:26: sorry, unimplemented: non-trivial designated initializers not supported
       this->omp_exc_.Run([&] {
                          ^
src/data/././text_parser.h:124:26: sorry, unimplemented: non-trivial designated initializers not supported
src/data/././text_parser.h:124:26: sorry, unimplemented: non-trivial designated initializers not supported
src/data/././text_parser.h:124:26: sorry, unimplemented: non-trivial designated initializers not supported
src/data/././text_parser.h:124:26: sorry, unimplemented: non-trivial designated initializers not supported
src/data/././text_parser.h: In instantiation of 'dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*)::<lambda()>::<lambda()> [with IndexType = unsigned int; DType = long long int]':
src/data/././text_parser.h:135:37:   required from 'struct dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*)::<lambda()> [with IndexType = unsigned int; DType = long long int]::<lambda()>'
src/data/././text_parser.h:124:7:   required from 'dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*)::<lambda()> [with IndexType = unsigned int; DType = long long int]'
src/data/././text_parser.h:123:70:   required from 'struct dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = unsigned int; DType = long long int]::<lambda()>'
src/data/././text_parser.h:123:22:   required from 'bool dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = unsigned int; DType = long long int]'
src/data/././text_parser.h:46:20:   required from 'bool dmlc::data::TextParserBase<IndexType, DType>::ParseNext(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = unsigned int; DType = long long int]'
src/data.cc:258:1:   required from here
src/data/././text_parser.h:125:51: error: redeclaration of 'const int& nthread'
         size_t nstep = (chunk.size + nthread - 1) / nthread;
                                                   ^
src/data/././text_parser.h:125:36: note: 'const int& nthread' previously declared here
         size_t nstep = (chunk.size + nthread - 1) / nthread;
                                    ^
src/data/././text_parser.h:127:37: error: redeclaration of 'const int& tid'
         size_t send = std::min((tid + 1) * nstep, chunk.size);
                                     ^
src/data/././text_parser.h:126:38: note: 'const int& tid' previously declared here
         size_t sbegin = std::min(tid * nstep, chunk.size);
                                      ^
src/data/././text_parser.h:130:17: error: redeclaration of 'const int& tid'
         if (tid + 1 == nthread) {
                 ^
src/data/././text_parser.h:126:38: note: 'const int& tid' previously declared here
         size_t sbegin = std::min(tid * nstep, chunk.size);
                                      ^
src/data/././text_parser.h:130:21: error: redeclaration of 'const int& nthread'
         if (tid + 1 == nthread) {
                     ^
src/data/././text_parser.h:125:36: note: 'const int& nthread' previously declared here
         size_t nstep = (chunk.size + nthread - 1) / nthread;
                                    ^
src/data/././text_parser.h:135:42: error: redeclaration of 'const int& tid'
         ParseBlock(pbegin, pend, &(*data)[tid]);
                                          ^
src/data/././text_parser.h:126:38: note: 'const int& tid' previously declared here
         size_t sbegin = std::min(tid * nstep, chunk.size);
                                      ^
src/data/././text_parser.h: In instantiation of 'dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*)::<lambda()> [with IndexType = unsigned int; DType = long long int]':
src/data/././text_parser.h:123:70:   required from 'struct dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = unsigned int; DType = long long int]::<lambda()>'
src/data/././text_parser.h:123:22:   required from 'bool dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = unsigned int; DType = long long int]'
src/data/././text_parser.h:46:20:   required from 'bool dmlc::data::TextParserBase<IndexType, DType>::ParseNext(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = unsigned int; DType = long long int]'
src/data.cc:258:1:   required from here
src/data/././text_parser.h:124:26: sorry, unimplemented: non-trivial designated initializers not supported
       this->omp_exc_.Run([&] {
                          ^
src/data/././text_parser.h:124:26: sorry, unimplemented: non-trivial designated initializers not supported
src/data/././text_parser.h:124:26: sorry, unimplemented: non-trivial designated initializers not supported
src/data/././text_parser.h:124:26: sorry, unimplemented: non-trivial designated initializers not supported
src/data/././text_parser.h:124:26: sorry, unimplemented: non-trivial designated initializers not supported
src/data/././text_parser.h: In instantiation of 'dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*)::<lambda()>::<lambda()> [with IndexType = long long unsigned int; DType = int]':
src/data/././text_parser.h:135:37:   required from 'struct dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*)::<lambda()> [with IndexType = long long unsigned int; DType = int]::<lambda()>'
src/data/././text_parser.h:124:7:   required from 'dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*)::<lambda()> [with IndexType = long long unsigned int; DType = int]'
src/data/././text_parser.h:123:70:   required from 'struct dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = long long unsigned int; DType = int]::<lambda()>'
src/data/././text_parser.h:123:22:   required from 'bool dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = long long unsigned int; DType = int]'
src/data/././text_parser.h:46:20:   required from 'bool dmlc::data::TextParserBase<IndexType, DType>::ParseNext(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = long long unsigned int; DType = int]'
src/data.cc:258:1:   required from here
src/data/././text_parser.h:125:51: error: redeclaration of 'const int& nthread'
         size_t nstep = (chunk.size + nthread - 1) / nthread;
                                                   ^
src/data/././text_parser.h:125:36: note: 'const int& nthread' previously declared here
         size_t nstep = (chunk.size + nthread - 1) / nthread;
                                    ^
src/data/././text_parser.h:127:37: error: redeclaration of 'const int& tid'
         size_t send = std::min((tid + 1) * nstep, chunk.size);
                                     ^
src/data/././text_parser.h:126:38: note: 'const int& tid' previously declared here
         size_t sbegin = std::min(tid * nstep, chunk.size);
                                      ^
src/data/././text_parser.h:130:17: error: redeclaration of 'const int& tid'
         if (tid + 1 == nthread) {
                 ^
src/data/././text_parser.h:126:38: note: 'const int& tid' previously declared here
         size_t sbegin = std::min(tid * nstep, chunk.size);
                                      ^
src/data/././text_parser.h:130:21: error: redeclaration of 'const int& nthread'
         if (tid + 1 == nthread) {
                     ^
src/data/././text_parser.h:125:36: note: 'const int& nthread' previously declared here
         size_t nstep = (chunk.size + nthread - 1) / nthread;
                                    ^
src/data/././text_parser.h:135:42: error: redeclaration of 'const int& tid'
         ParseBlock(pbegin, pend, &(*data)[tid]);
                                          ^
src/data/././text_parser.h:126:38: note: 'const int& tid' previously declared here
         size_t sbegin = std::min(tid * nstep, chunk.size);
                                      ^
src/data/././text_parser.h: In instantiation of 'dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*)::<lambda()> [with IndexType = long long unsigned int; DType = int]':
src/data/././text_parser.h:123:70:   required from 'struct dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = long long unsigned int; DType = int]::<lambda()>'
src/data/././text_parser.h:123:22:   required from 'bool dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = long long unsigned int; DType = int]'
src/data/././text_parser.h:46:20:   required from 'bool dmlc::data::TextParserBase<IndexType, DType>::ParseNext(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = long long unsigned int; DType = int]'
src/data.cc:258:1:   required from here
src/data/././text_parser.h:124:26: sorry, unimplemented: non-trivial designated initializers not supported
       this->omp_exc_.Run([&] {
                          ^
src/data/././text_parser.h:124:26: sorry, unimplemented: non-trivial designated initializers not supported
src/data/././text_parser.h:124:26: sorry, unimplemented: non-trivial designated initializers not supported
src/data/././text_parser.h:124:26: sorry, unimplemented: non-trivial designated initializers not supported
src/data/././text_parser.h:124:26: sorry, unimplemented: non-trivial designated initializers not supported
src/data/././text_parser.h: In instantiation of 'dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*)::<lambda()>::<lambda()> [with IndexType = unsigned int; DType = int]':
src/data/././text_parser.h:135:37:   required from 'struct dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*)::<lambda()> [with IndexType = unsigned int; DType = int]::<lambda()>'
src/data/././text_parser.h:124:7:   required from 'dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*)::<lambda()> [with IndexType = unsigned int; DType = int]'
src/data/././text_parser.h:123:70:   required from 'struct dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = unsigned int; DType = int]::<lambda()>'
src/data/././text_parser.h:123:22:   required from 'bool dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = unsigned int; DType = int]'
src/data/././text_parser.h:46:20:   required from 'bool dmlc::data::TextParserBase<IndexType, DType>::ParseNext(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = unsigned int; DType = int]'
src/data.cc:258:1:   required from here
src/data/././text_parser.h:125:51: error: redeclaration of 'const int& nthread'
         size_t nstep = (chunk.size + nthread - 1) / nthread;
                                                   ^
src/data/././text_parser.h:125:36: note: 'const int& nthread' previously declared here
         size_t nstep = (chunk.size + nthread - 1) / nthread;
                                    ^
src/data/././text_parser.h:127:37: error: redeclaration of 'const int& tid'
         size_t send = std::min((tid + 1) * nstep, chunk.size);
                                     ^
src/data/././text_parser.h:126:38: note: 'const int& tid' previously declared here
         size_t sbegin = std::min(tid * nstep, chunk.size);
                                      ^
src/data/././text_parser.h:130:17: error: redeclaration of 'const int& tid'
         if (tid + 1 == nthread) {
                 ^
src/data/././text_parser.h:126:38: note: 'const int& tid' previously declared here
         size_t sbegin = std::min(tid * nstep, chunk.size);
                                      ^
src/data/././text_parser.h:130:21: error: redeclaration of 'const int& nthread'
         if (tid + 1 == nthread) {
                     ^
src/data/././text_parser.h:125:36: note: 'const int& nthread' previously declared here
         size_t nstep = (chunk.size + nthread - 1) / nthread;
                                    ^
src/data/././text_parser.h:135:42: error: redeclaration of 'const int& tid'
         ParseBlock(pbegin, pend, &(*data)[tid]);
                                          ^
src/data/././text_parser.h:126:38: note: 'const int& tid' previously declared here
         size_t sbegin = std::min(tid * nstep, chunk.size);
                                      ^
src/data/././text_parser.h: In instantiation of 'dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*)::<lambda()> [with IndexType = unsigned int; DType = int]':
src/data/././text_parser.h:123:70:   required from 'struct dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = unsigned int; DType = int]::<lambda()>'
src/data/././text_parser.h:123:22:   required from 'bool dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = unsigned int; DType = int]'
src/data/././text_parser.h:46:20:   required from 'bool dmlc::data::TextParserBase<IndexType, DType>::ParseNext(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = unsigned int; DType = int]'
src/data.cc:258:1:   required from here
src/data/././text_parser.h:124:26: sorry, unimplemented: non-trivial designated initializers not supported
       this->omp_exc_.Run([&] {
                          ^
src/data/././text_parser.h:124:26: sorry, unimplemented: non-trivial designated initializers not supported
src/data/././text_parser.h:124:26: sorry, unimplemented: non-trivial designated initializers not supported
src/data/././text_parser.h:124:26: sorry, unimplemented: non-trivial designated initializers not supported
src/data/././text_parser.h:124:26: sorry, unimplemented: non-trivial designated initializers not supported
src/data/././text_parser.h: In instantiation of 'dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*)::<lambda()>::<lambda()> [with IndexType = long long unsigned int; DType = float]':
src/data/././text_parser.h:135:37:   required from 'struct dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*)::<lambda()> [with IndexType = long long unsigned int; DType = float]::<lambda()>'
src/data/././text_parser.h:124:7:   required from 'dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*)::<lambda()> [with IndexType = long long unsigned int; DType = float]'
src/data/././text_parser.h:123:70:   required from 'struct dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = long long unsigned int; DType = float]::<lambda()>'
src/data/././text_parser.h:123:22:   required from 'bool dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = long long unsigned int; DType = float]'
src/data/././text_parser.h:46:20:   required from 'bool dmlc::data::TextParserBase<IndexType, DType>::ParseNext(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = long long unsigned int; DType = float]'
src/data.cc:258:1:   required from here
src/data/././text_parser.h:125:51: error: redeclaration of 'const int& nthread'
         size_t nstep = (chunk.size + nthread - 1) / nthread;
                                                   ^
src/data/././text_parser.h:125:36: note: 'const int& nthread' previously declared here
         size_t nstep = (chunk.size + nthread - 1) / nthread;
                                    ^
src/data/././text_parser.h:127:37: error: redeclaration of 'const int& tid'
         size_t send = std::min((tid + 1) * nstep, chunk.size);
                                     ^
src/data/././text_parser.h:126:38: note: 'const int& tid' previously declared here
         size_t sbegin = std::min(tid * nstep, chunk.size);
                                      ^
src/data/././text_parser.h:130:17: error: redeclaration of 'const int& tid'
         if (tid + 1 == nthread) {
                 ^
src/data/././text_parser.h:126:38: note: 'const int& tid' previously declared here
         size_t sbegin = std::min(tid * nstep, chunk.size);
                                      ^
src/data/././text_parser.h:130:21: error: redeclaration of 'const int& nthread'
         if (tid + 1 == nthread) {
                     ^
src/data/././text_parser.h:125:36: note: 'const int& nthread' previously declared here
         size_t nstep = (chunk.size + nthread - 1) / nthread;
                                    ^
src/data/././text_parser.h:135:42: error: redeclaration of 'const int& tid'
         ParseBlock(pbegin, pend, &(*data)[tid]);
                                          ^
src/data/././text_parser.h:126:38: note: 'const int& tid' previously declared here
         size_t sbegin = std::min(tid * nstep, chunk.size);
                                      ^
src/data/././text_parser.h: In instantiation of 'dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*)::<lambda()> [with IndexType = long long unsigned int; DType = float]':
src/data/././text_parser.h:123:70:   required from 'struct dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = long long unsigned int; DType = float]::<lambda()>'
src/data/././text_parser.h:123:22:   required from 'bool dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = long long unsigned int; DType = float]'
src/data/././text_parser.h:46:20:   required from 'bool dmlc::data::TextParserBase<IndexType, DType>::ParseNext(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = long long unsigned int; DType = float]'
src/data.cc:258:1:   required from here
src/data/././text_parser.h:124:26: sorry, unimplemented: non-trivial designated initializers not supported
       this->omp_exc_.Run([&] {
                          ^
src/data/././text_parser.h:124:26: sorry, unimplemented: non-trivial designated initializers not supported
src/data/././text_parser.h:124:26: sorry, unimplemented: non-trivial designated initializers not supported
src/data/././text_parser.h:124:26: sorry, unimplemented: non-trivial designated initializers not supported
src/data/././text_parser.h:124:26: sorry, unimplemented: non-trivial designated initializers not supported
src/data/././text_parser.h: In instantiation of 'dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*)::<lambda()>::<lambda()> [with IndexType = unsigned int; DType = float]':
src/data/././text_parser.h:135:37:   required from 'struct dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*)::<lambda()> [with IndexType = unsigned int; DType = float]::<lambda()>'
src/data/././text_parser.h:124:7:   required from 'dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*)::<lambda()> [with IndexType = unsigned int; DType = float]'
src/data/././text_parser.h:123:70:   required from 'struct dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = unsigned int; DType = float]::<lambda()>'
src/data/././text_parser.h:123:22:   required from 'bool dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = unsigned int; DType = float]'
src/data/././text_parser.h:46:20:   required from 'bool dmlc::data::TextParserBase<IndexType, DType>::ParseNext(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = unsigned int; DType = float]'
src/data.cc:258:1:   required from here
src/data/././text_parser.h:125:51: error: redeclaration of 'const int& nthread'
         size_t nstep = (chunk.size + nthread - 1) / nthread;
                                                   ^
src/data/././text_parser.h:125:36: note: 'const int& nthread' previously declared here
         size_t nstep = (chunk.size + nthread - 1) / nthread;
                                    ^
src/data/././text_parser.h:127:37: error: redeclaration of 'const int& tid'
         size_t send = std::min((tid + 1) * nstep, chunk.size);
                                     ^
src/data/././text_parser.h:126:38: note: 'const int& tid' previously declared here
         size_t sbegin = std::min(tid * nstep, chunk.size);
                                      ^
src/data/././text_parser.h:130:17: error: redeclaration of 'const int& tid'
         if (tid + 1 == nthread) {
                 ^
src/data/././text_parser.h:126:38: note: 'const int& tid' previously declared here
         size_t sbegin = std::min(tid * nstep, chunk.size);
                                      ^
src/data/././text_parser.h:130:21: error: redeclaration of 'const int& nthread'
         if (tid + 1 == nthread) {
                     ^
src/data/././text_parser.h:125:36: note: 'const int& nthread' previously declared here
         size_t nstep = (chunk.size + nthread - 1) / nthread;
                                    ^
src/data/././text_parser.h:135:42: error: redeclaration of 'const int& tid'
         ParseBlock(pbegin, pend, &(*data)[tid]);
                                          ^
src/data/././text_parser.h:126:38: note: 'const int& tid' previously declared here
         size_t sbegin = std::min(tid * nstep, chunk.size);
                                      ^
src/data/././text_parser.h: In instantiation of 'dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*)::<lambda()> [with IndexType = unsigned int; DType = float]':
src/data/././text_parser.h:123:70:   required from 'struct dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = unsigned int; DType = float]::<lambda()>'
src/data/././text_parser.h:123:22:   required from 'bool dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = unsigned int; DType = float]'
src/data/././text_parser.h:46:20:   required from 'bool dmlc::data::TextParserBase<IndexType, DType>::ParseNext(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = unsigned int; DType = float]'
src/data.cc:258:1:   required from here
src/data/././text_parser.h:124:26: sorry, unimplemented: non-trivial designated initializers not supported
       this->omp_exc_.Run([&] {
                          ^
src/data/././text_parser.h:124:26: sorry, unimplemented: non-trivial designated initializers not supported
src/data/././text_parser.h:124:26: sorry, unimplemented: non-trivial designated initializers not supported
src/data/././text_parser.h:124:26: sorry, unimplemented: non-trivial designated initializers not supported
src/data/././text_parser.h:124:26: sorry, unimplemented: non-trivial designated initializers not supported
In file included from include/dmlc/threadediter.h:20:0,
                 from src/data/parser.h:12,
                 from src/data.cc:10:
F:/tdm-gcc/lib/gcc/x86_64-w64-mingw32/5.1.0/include/c++/thread:133:7: error: 'std::thread::thread(_Callable&&, _Args&& ...) [with _Callable = dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = long long unsigned int; DType = long long int]::<lambda()>; _Args = {}]', declared using local type 'dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = long long unsigned int; DType = long long int]::<lambda()>', is used but never defined [-fpermissive]
       thread(_Callable&& __f, _Args&&... __args)
       ^
F:/tdm-gcc/lib/gcc/x86_64-w64-mingw32/5.1.0/include/c++/thread:133:7: error: 'std::thread::thread(_Callable&&, _Args&& ...) [with _Callable = dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = unsigned int; DType = long long int]::<lambda()>; _Args = {}]', declared using local type 'dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = unsigned int; DType = long long int]::<lambda()>', is used but never defined [-fpermissive]
F:/tdm-gcc/lib/gcc/x86_64-w64-mingw32/5.1.0/include/c++/thread:133:7: error: 'std::thread::thread(_Callable&&, _Args&& ...) [with _Callable = dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = long long unsigned int; DType = int]::<lambda()>; _Args = {}]', declared using local type 'dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = long long unsigned int; DType = int]::<lambda()>', is used but never defined [-fpermissive]
F:/tdm-gcc/lib/gcc/x86_64-w64-mingw32/5.1.0/include/c++/thread:133:7: error: 'std::thread::thread(_Callable&&, _Args&& ...) [with _Callable = dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = unsigned int; DType = int]::<lambda()>; _Args = {}]', declared using local type 'dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = unsigned int; DType = int]::<lambda()>', is used but never defined [-fpermissive]
F:/tdm-gcc/lib/gcc/x86_64-w64-mingw32/5.1.0/include/c++/thread:133:7: error: 'std::thread::thread(_Callable&&, _Args&& ...) [with _Callable = dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = long long unsigned int; DType = float]::<lambda()>; _Args = {}]', declared using local type 'dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = long long unsigned int; DType = float]::<lambda()>', is used but never defined [-fpermissive]
F:/tdm-gcc/lib/gcc/x86_64-w64-mingw32/5.1.0/include/c++/thread:133:7: error: 'std::thread::thread(_Callable&&, _Args&& ...) [with _Callable = dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = unsigned int; DType = float]::<lambda()>; _Args = {}]', declared using local type 'dmlc::data::TextParserBase<IndexType, DType>::FillData(std::vector<dmlc::data::RowBlockContainer<IndexType, DType> >*) [with IndexType = unsigned int; DType = float]::<lambda()>', is used but never defined [-fpermissive]
Makefile:92: recipe for target 'data.o' failed
mingw32-make: *** [data.o] Error 1
</code></pre>
</details>

Can you please let me know what's going on and how I can resolve this?

Thanks a lot.

**Comment by yz-nju** [comment]
I find that the problem appears since commit ee773cd (Add OMPException class and use it for text\_parser (#445)) of submodule dmlc. When I rollback to commits 958c22b of dmlc, I can successfully compile both dmlc and xgboost.

**Comment by hcho3** [comment]
Looks like your compiler doesn't fully support C++11?
