### ISSUE TITLE
Not printing even with verbosity>0 and predict crashes silently

### ISSUE THREAD

**Issue by AMNeves** [dmlc/xgboost#4460]
Environment info:
Operating system : Windows 10
Python Version : 3.7  (Anaconda)
Xgb verson : 0.82

Hey, im facing a strange issue. I can train the model and predict the testing set fine with the code below:

```
train_size = 500_000
X, y, X_test , y_test  = data.load(train_size, normalize=False, balance=False) 

# Build a forest and compute the feature importances
forest = xgb.XGBClassifier(colsample_bytree=0.5483193137202504, 
                        gamma=0.1, 
                        gpu_id=0, 
                        learning_rate=0.6783980222181293,
                        max_depth=6,
                        min_child_weight=1,
                        n_estimators=1500,
                        nthread=4,
                        objective='multi:softmax', 
                        predictor='gpu_predictor', 
                        tree_method='gpu_hist', verbosity=2)

forest.fit(X, y)
y_pred = forest.predict(X_test)
```

I can get the output of style: `Kappa: 0.5943037988043391`
After this I load more data with about 18 million points to make a full prediction:

`
X, y, shape = data.load_prediction(DS_FOLDER, normalize=False)
y_pred = forest.predict(X)
`

This second predict never finishes, and never gives out an error, it just ends. The script ends and theres is nothing, I can't debug it!
 
XGBoost is also not printing any training information.
I am running the script on a cmd terminal.
I cannot give you a script to replicate as my dataset is about 40 gb.

**Comment by hcho3** [comment]
Please set `eval_metric` when calling `fit()`, to display training information.

As for the silent crashing of `predict()`, I suspect you may be running out of memory. To avoid out-of-memory error, you can use set `predictor='cpu_predictor'` to predict with 18 million data points:
```python
forest.get_booster().set_param('predictor', 'cpu_predictor')
forest.predict(X)
```

**Comment by AMNeves** [comment]
> 
> 
> Please set `eval_metric` when calling `fit()`, to display training information.
> 
> As for the silent crashing of `predict()`, I suspect you may be running out of memory. To avoid out-of-memory error, you can use set `predictor='cpu_predictor'` to predict with 18 million data points:
> 
> ```python
> forest.get_booster().set_param('predictor', 'cpu_predictor')
> forest.predict(X)
> ```
 I see! i may change it to batch predict, anyway shouldnt the method throw an OOM exception or an error?

**Comment by hcho3** [comment]
Unfortunately, OOM errors are difficult, because OS may kill the process before an exception can be thrown.

**Comment by AMNeves** [comment]
I checked memory usage with a cpu predictor, 8.076 mb, my GPU has 8GB total and about 6 free at time of the run.
It could also be using the integrated GPU wihch appears as GPU 0. Either way, issue fixed I thought it was a bug or a missing feature.



> Unfortunately, OOM errors are difficult, because OS may kill the process before an exception can be thrown.

Also, sugestion, could try to calculate potential memory use from the dataset only before running and issue a warning. By using known heuristics from previous tests maybe. But this would be a low priotity feature I guess.
I suggest adding a note on the docs about OOM silent errors with predict for new people heh!
