### ISSUE TITLE
[Question] Why is `reg_alpha` called "l1 regularization"?

### ISSUE THREAD

**Issue by mayer79** [dmlc/xgboost#4464]
According to the original XGBoost paper, `reg_alpha` penalizes the number of leaves and thus seems independent of the node values w. 
Why is it called "l1 regularization"? 

For `reg_lambda`, the term "l2 regularization" makes sense as it penalizes w^2, so one would think that "l1 regularization" would penalize |w|.

**Comment by hcho3** [comment]
In
https://github.com/dmlc/xgboost/blob/17df5fd296aaff18123c53a777f24111b3dd7336/src/tree/split_evaluator.cc#L137-L139

we have a penalty term that penalizes |w|, and it uses `reg_alpha`.

**Comment by mayer79** [comment]
Oh, this is very good to know. Thus, the number of leaves - as described in the original paper - is not implemented?

**Comment by hcho3** [comment]
You should use `max_leaves` and `max_depth`

**Comment by mayer79** [comment]
Right but these are constraints, not penalties. I was referring to formula (2) in the paper that defines the penalty term as lambda times sum of w^2 plus alpha times the number of leaves |T| (cannot add screenshot).

**Comment by hcho3** [comment]
Yes, in practice we put a hard constraint on the depth and number of leaves.
