### ISSUE TITLE
[Question] reg_lambda and regression

### ISSUE THREAD

**Issue by mayer79** [dmlc/xgboost#4465]
The parameter `reg_lambda` pulls leaf values towards 0. What is the intention of doing so for regression targets with mean far away from zero? It seems to introduce mean biased predictions that would be corrected by subsequent boosting rounds, eventually leading to slower convergence. 

Would it make sense to mean center the target first in order to get rid of this effect resp. could this be a motivation to boost from average? (My question focuses on squared loss objective but could be generalized to other losses).

**Comment by hcho3** [comment]
The motivation for pushing leaf values toward 0 is to prevent over-confident predictions. I agree that in regression setting, we may want to start boosting from the average to speed up convergence. There is a discussion about boosting from average: #4321
