### ISSUE TITLE
save_period parameter

### ISSUE THREAD

**Issue by BlindApe** [dmlc/xgboost#447]
I would like this parameter available in R wrapper. I work with very heavy models that require a lot of hours / days and this would be very nice.
I think only requires introduce a check point in main loop in xgb.train (line 196):

if (i %% save_period == 0) {save(bst, file = 'temp_bst.RData')}

**Comment by tqchen** [comment]
This sounds like a good proposal. @BlindApe @hetong007 Can you look into this?

**Comment by hetong007** [comment]
Hi @BlindApe , sorry for the late reply. This feature is added as two arguments `save_period` and `save_name` in `xgboost` and `xgb.train`.

**Comment by BlindApe** [comment]
Thank you, Tong. 
I'll use in my new project and give you the feedback.

**Comment by BlindApe** [comment]
I forgot give you my feedback: this works fine!
