### ISSUE TITLE
[spark-2.4.0, xgboost-0.82] Running xgboost training in threads crashes the executors

### ISSUE THREAD

**Issue by skale1990** [dmlc/xgboost#4472]
I'm trying to evaluate xgboost training by spawning some threads in threadpool. 

a. When i execute training with single thread, things work well.
b. When I execute training with 5 threads with same data as of #a then also it works well.
c. When i increase the threads to 9, xgboost model creation crash the executor with below trace - 

`java classes where applicable
[12:51:18] Tree method is automatically selected to be 'approx' for distributed training.
[12:51:20] Tree method is automatically selected to be 'approx' for distributed training.
[12:51:49] Tree method is automatically selected to be 'approx' for distributed training.
[12:52:45] Tree method is automatically selected to be 'approx' for distributed training.
Doing rabit call after Finalize`

**Comment by CodingCat** [comment]
try set tree_method to `hist`, (but don't set use_external_memory to true)

**Comment by CodingCat** [comment]
wait, what do you mean by `spawning some threads in threadpool.`?

**Comment by skale1990** [comment]
@CodingCat We are creating the threadpool having n (configurable parameter) threads on the driver. In each thread, we basically do following steps-
a. Connect to external Database and fetch the historical data
b. Do data preprocessing and engineering
c. train the xgboost model (xgboost-spark4j) 
d. evaluate the model

Please let me know if you need any other information

**Comment by CodingCat** [comment]
why you need to create threadpool instead of just spawning n Spark tasks?

**Comment by skale1990** [comment]
There are certain business decisions that has to be taken post executing all these threads. Apart from these there is a constraint on number of connection to the external database while fetching these data. We thought choosing this approach will help us to control the number of connection as well as to take certain business decisions collectively for all the threads.

**Comment by CodingCat** [comment]
I don't think we have tested such use cases and if Rabit's design is naturally supporting such usage pattern

I would suspect there are some race condition introduced by your multi-threading strategy

I didn't see this problem when spawning Spark tasks

**Comment by skale1990** [comment]
@CodingCat I think, this particular exception is quite normal in the xgboost arena. I went through few bugs that were raised having same stack trace - https://github.com/dmlc/xgboost/pull/1334

I'm unsure, why this race condition happening with 9 threads but not with 5 threads.

**Comment by CodingCat** [comment]
again, XGBoost currently does not have tested with parallel model training in the same Spark application, regardless it is quite normal or not

race condition happens with more threads is very commonly seen, as the natural of race condition is an unexpected execution order of threads. with More threads, there are more chances to have an unexpected order
