### ISSUE TITLE
Ability to drop references to underlying DMatrix objects while keeping the booster object alive

### ISSUE THREAD

**Issue by vladpetric** [dmlc/xgboost#4482]
Our DMatrix objects consume a lot of memory. Because the booster class keeps a reference to the DMatrix objects used for training and validation (evals), they never get released (destructed) while the booster object is alive.

We confirmed this by running our test setup under gdb. We observed that C++ shared_ptr references to DMatrix objects grow, but because we keep the Python booster objects around, the shared_ptr references don't decrease to zero.

We'd like to be able to use the boosters without necessarily keeping around the DMatrixes used to train it.

Thank you!

Version: 0.82 (pip installed)
Python: 3.6

**Comment by trivialfis** [comment]
@RAMitchell related to #4354 .  WDYT?

**Comment by vladpetric** [comment]
It certainly seems related to #4354 , though I should say that this is more about how DMatrixes are used and reference-counted, rather than how they are implemented.

**Comment by trivialfis** [comment]
@vladpetric You are right and I agree with your proposal, booster and DMatrix should be decoupled.  But that requires a thorough inspection of current code base, so putting it into the DMatrix refactor plan seems appropriate.

**Comment by vladpetric** [comment]
Thanks!

**Comment by ivinogra** [comment]
I can confirm that this hack will allow deleting a DMatrix (from python):
```
m = xgb.train(params, dmatrix, **more_params)
pd.to_pickle(m, YOUR_PATH)
del m
del dmatrix
m = pd.read_pickle(YOUR_PATH)
```
It is also necessary to `del more_params['evals']` if this parameter was used, and accordingly for other parameters. While DMatrix code is being refactored, is it reasonable to note in the comments to the code that releasing a DMatrix may require deleting any boosters that have trained on it?

**Comment by trivialfis** [comment]
@ivinogra I'm not sure yet.

**Comment by trivialfis** [comment]
Done.
