### ISSUE TITLE
Static libxgboost.a library target for CMake build on Linux

### ISSUE THREAD

**Issue by thekvs** [dmlc/xgboost#4483]
XGBoost compiled with running `make` from the source root produces shared **and** static libraries (i.e. `./lib/libxgboost.a` and `./lib/libxgboost.so`), while if we use `cmake` + `make` build procedure we only have shared version of libxgboost. Sometimes it is very convenient to have statically built library.

**Comment by RAMitchell** [comment]
PRs are welcome.

**Comment by trivialfis** [comment]
Closed via https://github.com/dmlc/xgboost/pull/5397 .
