### ISSUE TITLE
pip3 install xgboost doesn't install libgomp.so in 0.90 on travis

### ISSUE THREAD

**Issue by MarvinT** [dmlc/xgboost#4489]
TravisCI has updated my repo to xgboost 0.90 (from 0.82) and I'm getting an error
```
~/virtualenv/python3.6.3/lib/python3.6/site-packages/xgboost/core.py in _load_lib()
    150             'libgomp.so for UNIX-like OSes)\n' +
    151             '  * You are running 32-bit Python on a 64-bit OS\n' +
--> 152             'Error message(s): {}\n'.format(os_error_list))
    153     lib.XGBGetLastError.restype = ctypes.c_char_p
1;32m    154     lib.callback = _get_log_callback_func()
XGBoostError: XGBoost Library (libxgboost.so) could not be loaded.
Likely causes:
  * OpenMP runtime is not installed (vcomp140.dll or libgomp-1.dll for Windows, libgomp.so for UNIX-like OSes)
  * You are running 32-bit Python on a 64-bit OS
Error message(s): ["/usr/lib/x86_64-linux-gnu/libgomp.so.1: version `GOMP_4.0' not found (required by /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so)", "/usr/lib/x86_64-linux-gnu/libgomp.so.1: version `GOMP_4.0' not found (required by /home/travis/virtualenv/python3.6.3/xgboost/libxgboost.so)"]
```

Hopefully current solution: (still waiting for travis build to complete)
```
apt-get install libgomp1 
```

I'm not sure if the pip installed binaries are supposed to include all the libraries or why this changed from 0.82 to .90, but I just wanted to raise the issue and let people know.

**Comment by trivialfis** [comment]
@MarvinT Should work,  I just did:
>  dpkg -S /usr/lib/x86_64-linux-gnu/libgomp.so.1

and dkpg returned:
> libgomp1:amd64: /usr/lib/x86_64-linux-gnu/libgomp.so.1

**Comment by trivialfis** [comment]
@MarvinT Any update on this?  How's it doing?

**Comment by MarvinT** [comment]
Sorry, this is the new error I'm getting:
```
XGBoostError: XGBoost Library (libxgboost.so) could not be loaded.
Likely causes:
  * OpenMP runtime is not installed (vcomp140.dll or libgomp-1.dll for Windows, libgomp.so for UNIX-like OSes)
  * You are running 32-bit Python on a 64-bit OS
Error message(s): ["/usr/lib/x86_64-linux-gnu/libgomp.so.1: version `GOMP_4.0' not found (required by /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so)", "/usr/lib/x86_64-linux-gnu/libgomp.so.1: version `GOMP_4.0' not found (required by /home/travis/virtualenv/python3.6.3/xgboost/libxgboost.so)"]
```
Here's a travis build if you want to see the configuration:
https://travis-ci.com/MarvinT/morphs/jobs/202333691

**Comment by trivialfis** [comment]
@MarvinT I don't have Ubuntu 14, but it might be the used gcc version mismatched.  We now build XGBoost with GCC 5.3.1, previously GCC 4.8.

**Comment by hcho3** [comment]
@trivialfis I wonder if it’s possible to bundle older libgomp when building with GCC 5.3.1

**Comment by MarvinT** [comment]
Yeah, sorry I don't have much time to follow this for you atm, I think I'm just going to downgrade to 0.82. I was just letting you guys know that this is an issue on the default ```pip install xgboost``` on travis

**Comment by hcho3** [comment]
@trivialfis I didn’t expect this issue when we upgraded GCC version in #4306

**Comment by hcho3** [comment]
@MarvinT Ubuntu 14.04 has reached its end of life last month. You should consider changing the Travis CI setting to use later version of Ubuntu.

**Comment by trivialfis** [comment]
@MarvinT Travis is moving to Ubuntu 16:

https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment

**Comment by MarvinT** [comment]
hmm, I'm surprised the default for me was still 14.04. I guess its a very slow rollout...
