### ISSUE TITLE
Question about homebrew

### ISSUE THREAD

**Issue by gblasius** [dmlc/xgboost#449]
I'm trying to build XGBoost for my Apple Mac per your instructions ("Build XGBoost in OS X with OpenMP"), using command line: brew install gcc --without-multilib and am receiving error messages: 

######################################################################## 100.0%
==> ../configure --build=x86_64-apple-darwin14.4.0 --prefix=/usr/local/Cellar/gc
==> make bootstrap
gcc/valtrack.o differs
gcc/vtable-verify.o differs
make[2]: *** [compare] Error 1
make[1]: *** [stage3-bubble] Error 2
make: *** [bootstrap] Error 2
Warning: It appears you have MacPorts or Fink installed.
Software installed with other package managers causes known problems for
Homebrew. If a formula fails to build, uninstall MacPorts/Fink and try again.

#######################################################################

Not sure if the install has failed or not and what I should be doing to correct.   No clue as to what Fink is.

**Comment by phunterlau** [comment]
I suspect someone else who used your computer installed Fink or MacPorts which are package management software for Mac. Some one had solved this problem, for example http://stackoverflow.com/questions/7751427/prevent-warning-about-macports-fink-installation 

And the instruction of "Build XGBoost in OS X with OpenMP" is kind of outdated. One can use `brew install gcc49` and it will compile the multi-thread version with no problem.
