### ISSUE TITLE
xgb.plot.tree throws an error

### ISSUE THREAD

**Issue by victorz-ca** [dmlc/xgboost#4493]
Using xgbbost 0.82.1 updated from CRAN.
Following example in [https://xgboost.readthedocs.io/en/latest/R-package/xgboostPresentation.html](url), and I get the following error.

> xgb.plot.tree(bstSparse)
Error in xgb.plot.tree(bstSparse) : 
  model: Has to be an object of class xgb.Booster

For reference, the object bstSparse does have class xgb.Boost:
> attributes(bstSparse)
$names
[1] "handle"         "raw"            "niter"          "evaluation_log"
[5] "call"           "params"         "callbacks"      "feature_names" 
[9] "nfeatures"     

$class
[1] "xgb.Booster"

**Comment by hcho3** [comment]
Please spell out the parameter: `xgb.plot.tree(model = bst)`
