### ISSUE TITLE
Visual Studio Community 2019 build error with `cmake --build .`

### ISSUE THREAD

**Issue by thekvs** [dmlc/xgboost#4495]
Is this version supported? I am trying to follow steps described [here](https://xgboost.readthedocs.io/en/latest/build.html#building-on-windows) but with the latest Visual Studio Community 2019 compilation fails:

```
$ cmake --build .
Microsoft (R) Build Engine version 16.1.76+g14b0a930a7 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(376,5): error MSB8013: This project doesn't contain the Configuration and Platform combination of Debug|x64. [C:\Users\User\work\xgboost\build\ZERO_CHECK.vcxproj]
```

**Comment by hcho3** [comment]
Can you open the sln file and run Build Solution ?

**Comment by thekvs** [comment]
Yes, that seems to work. Building from command line isn't supported?

**Comment by thekvs** [comment]
Btw, I was to build xgboost from command line with: `MSBuild.exe xgboost.sln`. [This](http://cmake.3232098.n2.nabble.com/Different-behavior-between-building-using-quot-cmake-build-quot-and-building-in-Visual-Studio-td7598940.html) discussion seems to be relevant to the question.

**Comment by hcho3** [comment]
I think you can also run
```
cmake --build . --config Release
```
