### ISSUE TITLE
[jvm-packages] Suspicious "split_condition" values on sparse features

### ISSUE THREAD

**Issue by raskr** [dmlc/xgboost#4506]
env:
- xgboost4j-spark 0.8.1

I have trained a `XGBoostRegressor` with `.setMissing(Float.NaN)`.  In the case of the input is `spark.ml.linag.SparseVector`, the dumped tree structure was as follows:
``` json
{ "nodeid": 152, "depth": 7, "split": "vec39", "split_condition": -0.247928366, "yes": 299, "no": 300, "missing": 300, "children": [
  { "nodeid": 299, "depth": 8, "split": "latitude", "split_condition": 33.59, "yes": 591, "no": 592, "missing": 592, "children": [
    { "nodeid": 591, "depth": 9, "split": "ic10", "split_condition": 2.00000095, "yes": 1165, "no": 1166, "missing": 1166, "children": [
      { "nodeid": 1165, "leaf": 0.333333373 },
      { "nodeid": 1166, "leaf": -0.0545454584 }
    ]},
    { "nodeid": 592, "depth": 9, "split": "ic338", "split_condition": 2.00000095, "yes": 1167, "no": 1168, "missing": 1168, "children": [
      { "nodeid": 1167, "leaf": 0.150000006 },
      { "nodeid": 1168, "leaf": -0.450491816 }
    ]}
  ]},
```
Here, feature names starting with `ic` are multi-hot encoded sparse dimensions taking (0|1). However, those "split_conditions" values look like suspicious values **(2.00000095), which leads to constant (useless) branches**.
Next, I converted the input type  `SparseVector` to `DenseVector`, then the model dump was:
``` json
{ "nodeid": 128, "depth": 7, "split": "ic438", "split_condition": 0.999998987, "yes": 255, "no": 256, "missing": 256, "children": [
  { "nodeid": 255, "depth": 8, "split": "ic205", "split_condition": 0.999998987, "yes": 507, "no": 508, "missing": 508, "children": [
    { "nodeid": 507, "depth": 9, "split": "ic454", "split_condition": 0.999998987, "yes": 1001, "no": 1002, "missing": 1002, "children": [
      { "nodeid": 1001, "leaf": -0.450724632 },
      { "nodeid": 1002, "leaf": -0 }
    ]},
```
With this model, predictions would change for (0|1) inputs as I expects, but memory/time resources while training were badly spoiled. Is this behavior of XGBoost correct? or I'm doing something wrong?
Thanks!

**Comment by hcho3** [comment]
Yes, the behavior is expected, since the split is distinguishing between missing values and non-missing values

**Comment by raskr** [comment]
> split is distinguishing between missing values and non-missing values

I understood that, in this setting, XGB distinguishes the value is NaN or not correctly.
But when I set `.setMissing(0)` with SparseVector, I have also seen the same result (`"split_condition": 2.00000095`). Is this a expected behavior?

**Comment by CodingCat** [comment]
(1) yes, it’s expected, when you have sparse vector, you already implicitly assume 0 is the missing value, setMissing doesn’t change anything


(2) no, you cannot, if you use dense vector to represent something, that means you are treating 0 as meaningful value. You are essentially asking how to get the same model with totally different training set...so the answer is you cannot

**Comment by raskr** [comment]
> (1) yes, it’s expected, when you have sparse vector, you already implicitly assume 0 is the missing value

If so, I think `split_condition` should be 0, not 2.00000095.
Later I tried features whose whole values are 0/1, then **all** the split point were `"split_condition": 2.00000095` (i.e., the tree is a single straight path actually). In this case I do not understand the reason why SparseVector exists.

**Comment by CodingCat** [comment]
SparseVector exits because you have enough number of 0 in a row to make vector assembler believe it is saving memory space to represent it with sparse vector

**Comment by raskr** [comment]
I'm sorry, I overlooked `missing` branch. Therefore, if the value is missing, go to designated branch. Otherwise  go to "yes" branch because the 0/1 values are always under 2.00000095...
