### ISSUE TITLE
[R] bugs in creation of stratified folds

### ISSUE THREAD

**Issue by JaakobKind** [dmlc/xgboost#4509]
Dear xgboost developers,
I have found two issues in the R version of xgb.cv when I try to use stratified folds:
1. If I pass a DMatrix, attribute label that is passed to generate.cv.folds iS NULL and hence function xgb.createFolds is not called. Hence, the folds that are created are not stratified.

2. As a workaround, I redundantly pass the labels in attribute label of function xgb,cv. Then function xgb.createFolds is called, but the folds that I get a still not stratified. The reason seems to be this line "y <- label[rnd_idx]" in function  generate.cv.folds, which permutes the labels in a way that is known to function xgb.cv.

[cvbug.txt](https://github.com/dmlc/xgboost/files/3226505/cvbug.txt)

**Comment by JaakobKind** [comment]
Additional information: 
1. I am using version 0.82.1 of xgboost
2. There is one word missing in the above issue description. The last sentence should read "The reason seems to be this line "y <- label[rnd_idx]" in function generate.cv.folds, which permutes the labels in a way that is not known to function xgb.cv."
3. The attached file cvbug.txt contains R code that can be used to reproduce the error.

**Comment by hcho3** [comment]
Thanks for the report. We appreciate the reproducible example. We will look at this issue at some point, on a best effort basis.

**Comment by hcho3** [comment]
Looking at this now

**Comment by hcho3** [comment]
> 1. If I pass a DMatrix, attribute label that is passed to generate.cv.folds iS NULL and hence function xgb.createFolds is not called. Hence, the folds that are created are not stratified.

I will file a small pull request to fix this.

> 2. As a workaround, I redundantly pass the labels in attribute label of function xgb,cv. Then function xgb.createFolds is called, but the folds that I get a still not stratified. The reason seems to be this line "y <- label[rnd_idx]" in function generate.cv.folds, which permutes the labels in a way that is known to function xgb.cv.

Indeed, XGBoost shuffles the order of data points prior to constructing stratified folds, so you get different results compared to just calling `xgb.createFolds()` directly. However, I don't agree with this sentence

> the folds that I get a still not stratified

since XGBoost is still building stratified folds (after shuffling the data order).

**Comment by hcho3** [comment]
See #4631
