### ISSUE TITLE
Xgboost doesn't check the dimensions of train and test

### ISSUE THREAD

**Issue by daxiongshu** [dmlc/xgboost#451]
I know this sounds really silly and it should be the user's responsibility to check that but I could really appreciate it that xgboost checks if the train and test have same dimension on the feature's axis and prints a warning message or just aborts when they don't. This has bugged me several times when I forgot to check..

**Comment by gdupret** [comment]
I agree this would be helpful to catch obvious errors

**Comment by hetong007** [comment]
@tqchen do u think we can check it at the level of `DMatrix`?

**Comment by tqchen** [comment]
Yes, I think we can do it at level of boosted tree learners. Or the python/r packages, with an optional to enable it.

**Comment by hetong007** [comment]
@tqchen I prefer to check it in `DMatrix`, since sometimes the input is not a `matrix` object and R cannot check it. And maybe we don't need to "disable" it, because if we can, we want to check it everytime.
