### ISSUE TITLE
Windows GPU Build Issues

### ISSUE THREAD

**Issue by gatapia** [dmlc/xgboost#4514]
Current windows GPU build failing with the following error:
```
"c:\dev\libs\xgboost\build_64_gpu\xgboost.sln" (Clean;Rebuild target) (1) ->
"c:\dev\libs\xgboost\build_64_gpu\ALL_BUILD.vcxproj.metaproj" (Rebuild target) (13:2) ->
"c:\dev\libs\xgboost\build_64_gpu\runxgboost.vcxproj.metaproj" (Rebuild target) (4:4) ->
"c:\dev\libs\xgboost\build_64_gpu\runxgboost.vcxproj" (Rebuild target) (11:4) ->
(Link target) -> 
  objective.obj : error LNK2019: unresolved external symbol "int __cdecl xgboost::obj::__dmlc_registry_file_tag_regression_obj_gpu__(void)" (?__dmlc_registry_file_tag_regression_obj_gpu__@obj@xgboost@@YAHXZ) referenced in function "void __cdecl xgboost::obj::`dynamic initializer for '__reg_file_tag_regression_obj_gpu__''(void)" (??__E__reg_file_tag_regression_obj_gpu__@obj@xgboost@@YAXXZ) [c:\dev\libs\xgboost\build_64_gpu\runxgboost.vcxproj]
  objective.obj : error LNK2019: unresolved external symbol "int __cdecl xgboost::obj::__dmlc_registry_file_tag_hinge_obj_gpu__(void)" (?__dmlc_registry_file_tag_hinge_obj_gpu__@obj@xgboost@@YAHXZ) referenced in function "void __cdecl xgboost::obj::`dynamic initializer for '__reg_file_tag_hinge_obj_gpu__''(void)" (??__E__reg_file_tag_hinge_obj_gpu__@obj@xgboost@@YAXXZ) [c:\dev\libs\xgboost\build_64_gpu\runxgboost.vcxproj]
  objective.obj : error LNK2019: unresolved external symbol "int __cdecl xgboost::obj::__dmlc_registry_file_tag_multiclass_obj_gpu__(void)" (?__dmlc_registry_file_tag_multiclass_obj_gpu__@obj@xgboost@@YAHXZ) referenced in function "void __cdecl xgboost::obj::`dynamic initializer for '__reg_file_tag_multiclass_obj_gpu__''(void)" (??__E__reg_file_tag_multiclass_obj_gpu__@obj@xgboost@@YAXXZ) [c:\dev\libs\xgboost\build_64_gpu\runxgboost.vcxproj]
  C:\dev\libs\xgboost\xgboost.exe : fatal error LNK1120: 3 unresolved externals [c:\dev\libs\xgboost\build_64_gpu\runxgboost.vcxproj]

    1890 Warning(s)
    4 Error(s)

Time Elapsed 00:13:02.30
```

This is the build command:
`"C:\Program Files (x86)\MSBuild\14.0\Bin\amd64\msbuild.exe" /t:Clean,Rebuild /p:Configuration=Release xgboost.sln`

**Comment by hcho3** [comment]
What version of Visual Studio are you using? I suggest that you use Visual Studio 2015 or newer.

**Comment by gatapia** [comment]
I am using MSBuild v14. Which is part of VS 2015.

**Comment by hcho3** [comment]
We have an automated testing system that ensures that XGBoost can be compiled with Visual Studio: https://xgboost-ci.net/blue/organizations/jenkins/xgboost-win64/detail/master/19/pipeline/37/

Can you post the CMake command you used to generate `xgboost.sln`?

**Comment by gatapia** [comment]
This is the CMAKE command
`C:\dev\tools\cmake-3.14.4-win64-x64\bin\cmake.exe .. -G"Visual Studio 14 2015 Win64" -DUSE_CUDA=ON"`

**Comment by gatapia** [comment]
Also are you publishing your windows binaries, if you are then I dont need to maintain mine.

**Comment by hcho3** [comment]
Yes: https://pypi.org/project/xgboost/#files

**Comment by gatapia** [comment]
In that case I'll close this

**Comment by hcho3** [comment]
@gatapia I now realize you were maintaining Windows binaries for XGBoost since year September 2016. I'd like to thank you for your effort

**Comment by gatapia** [comment]
No worries, awesome product, least I could do.

**Comment by hcho3** [comment]
@gatapia FYI, we also distribute nightly builds (as part of continuous integration) in xgboost-ci.net, e.g. https://xgboost-ci.net/blue/organizations/jenkins/xgboost-win64/detail/master/21/artifacts
