### ISSUE TITLE
GPU memory bad_alloc: can't I avoid this without downsizing the data?

### ISSUE THREAD

**Issue by kyoungrok0517** [dmlc/xgboost#4515]
I'm quite new to this xgboost library, and sometimes get confused in the way it deals with data. Recently I'm dealing with bigger data using the same GPU, and confronting `bad_alloc` error. Can't I partially load the data and reload while training instead of loading the full data at once? Now I realize there is no option like `batch_size`...

**Comment by hcho3** [comment]
XGBoost differs from deep learning frameworks in that you are not able to use mini-batches in training.

However, There is an on-going work to enable external memory with GPU training, so stay tuned.

**Comment by hcho3** [comment]
@kyoungrok0517 FYI, #4526 should let you train on GPUs with data bigger than GPU memory.
