### ISSUE TITLE
xgboost installation issue - Python Windows

### ISSUE THREAD

**Issue by Vikrant79** [dmlc/xgboost#452]
Hi,
I have installed the xgboost using the instruction given for Python windows. I have used VS2013 to build the solution. Everything was successand i saw the below message.
Build: 3 succeeded, 0 failed, 0 up-to-date, 0 skipped =========

I searched for xgboost app and xgboost.dll file location and mapped it in the script as below - 
import sys
sys.path.append('C:\\Users\\Vikrant\\xgboost\\windows\\x64\\Release\\xgboost')
But still I amnot able to load xgboost. I below error when i try to import xgboost

import xgboost as xgb
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-51-745aa3a2d734> in <module>()
----> 1 import xgboost as xgb

ImportError: No module named xgboost

I am attaching all the screenshots. Please help
![vs build result](https://cloud.githubusercontent.com/assets/13698551/9422508/39724c34-484a-11e5-849b-b80db82087d2.png)
![python script](https://cloud.githubusercontent.com/assets/13698551/9422509/3d294c24-484a-11e5-9aa7-9788621e7310.png)
![xgboost file location](https://cloud.githubusercontent.com/assets/13698551/9422510/40369d9a-484a-11e5-90a9-ab6375a33960.png)

**Comment by tqchen** [comment]
You also do not need to add path to the dll, instead, add path to the python-package https://github.com/dmlc/xgboost/tree/master/python-package

**Comment by Vikrant79** [comment]
Thanks a lot Tianqi. That really worked :-). You are awesome.

**Comment by tqchen** [comment]
glad it works out for you. However, the most common approach is to install it using the setup script, which should be fixed soon for windows.

**Comment by mukesh-ranjan** [comment]
Hi vikrant,

can add the snapshot of further step which solved ur problem.

Thanks & Regards
Mukesh R.
