### ISSUE TITLE
[jvm-packages] XGBoostRegressionModel's native booster returns more number of feature weights than actual features provided.

### ISSUE THREAD

**Issue by neeleshkshukla** [dmlc/xgboost#4520]
I am using xgboost4j-spark 0.82. While retrieving feature importance, I found more weights that actual features.

val xgbRegressor = new XGBoostRegressor(xgbParam)
        .setNumRound(100)
        .setFeaturesCol("features")
        .setLabelCol(y)

def getFeatureImportance(trainedModel: XGBoostRegressionModel): collection.mutable.Map[String, Double] ={
trainedModel.nativeBooster.getFeatureScore()
}

I have provided 2011 features but feature weights returned for f2017, f2014 and so on.

 number of "features" :: 2011
19/05/31 10:46:00 INFO SparkLogging$: feature index out of range :: 2017 (f2017)
19/05/31 10:46:00 INFO SparkLogging$: feature index out of range :: 2014 (f2014)
19/05/31 10:46:00 INFO SparkLogging$: feature index out of range :: 2016 (f2016)
19/05/31 10:46:00 INFO SparkLogging$: feature index out of range :: 2019 (f2019)
19/05/31 10:46:00 INFO SparkLogging$: feature index out of range :: 2013 (f2013)

**Comment by CodingCat** [comment]
can you check the maximum size in your input dataframe feature column (in sparsevector)

**Comment by Daniel8hen** [comment]
Hi @CodingCat , sorry to get in-between you guys, but wanted to ask something specific (and if you want me - I'll open another PR for it).
Today, per https://github.com/dmlc/xgboost/blob/90f683b25be28150487dead9a695b20dc464d0b4/jvm-packages/xgboost4j/src/main/scala/ml/dmlc/xgboost4j/scala/Booster.scala#L271
the relevant options for getFeature score are: gain, cover, total gain, total cover.

Can you provide an example of how to use it in XGBoost4J (Spark)? I'm having difficulties getting feature score per other scores (and just using the getter without arguments for now).

Thank you,
Daniel

**Comment by neeleshkshukla** [comment]
Okay, let me explore the sparse vector.

**Comment by Daniel8hen** [comment]
@neeleshkshukla @CodingCat maybe addding support to feature names instead of f123 , f2017, f1, etc. could be a solver here? wdyt? @CodingCat plus the note I wrote above, it could be great have the ability to use these as well. Thanks!!

**Comment by neeleshkshukla** [comment]
> Hi @CodingCat , sorry to get in-between you guys, but wanted to ask something specific (and if you want me - I'll open another PR for it).
> Today, per
> 
> https://github.com/dmlc/xgboost/blob/90f683b25be28150487dead9a695b20dc464d0b4/jvm-packages/xgboost4j/src/main/scala/ml/dmlc/xgboost4j/scala/Booster.scala#L271
> 
> 
> the relevant options for getFeature score are: gain, cover, total gain, total cover.
> Can you provide an example of how to use it in XGBoost4J (Spark)? I'm having difficulties getting feature score per other scores (and just using the getter without arguments for now).
> 
> Thank you,
> Daniel

Yes with Spark, I am also not able to use those option. We need to use native booster which doesn't have access to them. @CodingCat Can we add support for different methods in Spark as well.

**Comment by neeleshkshukla** [comment]
> @neeleshkshukla @CodingCat maybe addding support to feature names instead of f123 , f2017, f1, etc. could be a solver here? wdyt? @CodingCat plus the note I wrote above, it could be great have the ability to use these as well. Thanks!!

In a simple case, it works that I have tried. I have a preprocessing pipeline which 1-hot encodes the features. Not sure giving feature name will work in that case. Let me give it a try as well.

**Comment by Daniel8hen** [comment]
@neeleshkshukla is right, I think that the support for Spark would be super helpful! If you'd like, @CodingCat , once you'll have the support, I'll review + write a tutorial for users in Spark as I use it kinda a lot.
Thanks!

**Comment by neeleshkshukla** [comment]
Tested with different data and Sparse/Dense vectors. Seems like not an issue with XGBoost. Need to be investigated at Spark's Vector Assembler level.
