### ISSUE TITLE
Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by VGuette** [dmlc/xgboost#453]
Hello,
I try to install xgboost on Anaconda 3 with the command pip install xgboost.
I have the following error: SyntaxError: Missing parentheses in call to 'print'
It occurs on line 13 in setup.py, when 'print output' is called.
If it's easy to correct it could be wonderful! :)

**Comment by tqchen** [comment]
This can be fixed by adding parentheses to the line, can you open a PR on this? Thanks!

**Comment by VGuette** [comment]
Thanks for your rapid answer! 
I'm really sorry I'm quite a newbie, I tried to open a PR but I haven't really understood how it works yet and I don't want to do mistakes. I try to do this as soon as I have understood.
Thanks!

**Comment by VGuette** [comment]
Ok, I opened the PR!
Thanks.
