### ISSUE TITLE
[jvm-packages] `missing` parameter not propagated from XGBoostClassifier to XGBoostClassificationModel

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#4530]
From https://discuss.xgboost.ai/t/jvm-packages-v0-90-sparse-vector-prediction-issue-on-missing-values/903:

> model.transform() failed with “java.lang.RuntimeException: you can only specify missing value as 0.0 (the currently set value NaN) when you have SparseVector or Empty vector as your feature format”. Looks like missing is set correctly in XGBoostClassifier, but it is not passed to XGBoostClassificationModel.

**Comment by hcho3** [comment]
@CodingCat Is there a way to set missing value for prediction (`transform()`)?

**Comment by CodingCat** [comment]
replied in the discussion forum
