### ISSUE TITLE
Fetch parameters in custom objective defined in param map

### ISSUE THREAD

**Issue by qingyuanxingsi** [dmlc/xgboost#4533]
If I want to use certain parameters defined in param map in my customized objective function,how to do it?

The [example code](https://github.com/dmlc/xgboost/blob/master/jvm-packages/xgboost4j-example/src/main/scala/ml/dmlc/xgboost4j/scala/example/CustomObjective.scala) do not have any parameters.

**Comment by qingyuanxingsi** [comment]
Anyone reply??I posted it [here](https://discuss.xgboost.ai/t/fetch-parameters-in-custom-objective-defined-in-param-map/909) but got no reply!

**Comment by hcho3** [comment]
I left my reply.
