### ISSUE TITLE
[jvm-packages] Outdated parameter validation check for xgboost4j-spark?

### ISSUE THREAD

**Issue by nedStackAdapt** [dmlc/xgboost#4536]
Is the parameter check for 

 if ((paramName == "booster" && paramValue != "gbtree") ||
        (paramName == "updater" && paramValue != "grow_histmaker,prune" &&
          paramValue != "hist")) {
        throw new IllegalArgumentException(s"you specified $paramName as $paramValue," +
          s" XGBoost-Spark only supports gbtree as booster type" +
          " and grow_histmaker,prune or hist as the updater type")

on line 246 of xgboost/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/params/GeneralParams.scala 

outdated?

I compiled my own version of the code, and passed in "updater" -> "grow_local_histmaker,prune".  The code ran just fine and produced better results on my test set.  Also my brief scanning through the code didn't seem like the Java version had this parameter restriction.

If it is outdated, perhaps we can remove it?

If it is not outdated, what is happening when I pass in "grow_local_histmaker,prune"?

Thank you.

**Comment by hcho3** [comment]
@nedStackAdapt Personally, I'm not sure how much confidence we should put into `grow_local_histmaker`, since it's seldom used and thus tested.
