### ISSUE TITLE
[RFC] Optimize configurations in Learner.

### ISSUE THREAD

**Issue by trivialfis** [dmlc/xgboost#4542]
Currently the configuration steps in Learner is bloated in both size and complexity.  I think we have all come to agreement that it needs better organization.  Other than simplifying future maintenance, there are other benefits on this:

- Parameter validation, the configuration happens in both initialization and during each update so copies of parameters are stored in various places, including both `Learner` and `GradientBooster`.  So we don't know exactly when a parameter should be used nor which copy is actually used.

- Smooth out the path for our plan of transitioning to JSON format since one big issue is keeping compatibility, and I want the JSON format to be a fresh start.

To do so, we need to draft a testing suit for current binary model IO so that later refactoring won't break the existing model.  Then we need to decide what style of parameters management we want:
- A global one like most of other gbm libraries, all parameters stored in one `config` class, then we pass it through the whole library.
- Many local parameter structs just like current XGBoost.

Personally I don't have a preference.

I am struggling whether should JSON happen first or optimization for Learner.  But parameter validation is definitely coming after we reorganize those configurations.

@RAMitchell @CodingCat @hcho3

**Comment by trivialfis** [comment]
One funny thing, I tried to move tree updater configuration into GBM, the `Learner.SLOW_CheckMultiBatch` test gave me a dead lock in `col_maker`.

**Comment by trivialfis** [comment]
During many previous fixes and refactoring PRs including #4553,  I came to realize that how should we proceed on parameter validations.  There are two fundamental problems in current XGBoost internal parameters handling:

- The semantic of `Configure` and `Init` is not clear, and they depend on each others.  In many places one has to allocate memory for components (Init) to do further configurations, example are gbm asking updaters to configure themselves.  But it's also not possible to do `Init` without first configuring stuffs out, example like creating updaters after selecting tree methods.
- Some configurations has to be done after seeing the DMatrix, like `num_feature`, `n_gpus`(to be deprecated).  While our abstract `Configure` is not prepared for this, it has no parameter for DMatrix.
- Most of the configurations can be changed during each boost iteration.  Our configuration is also not prepared for this.  It doesn't know whether those string parameters are changed or not, so we just plug some partial configuration into `Update` or `DoBoost`.

My proposal is, 
- Firstly we clear up the semantic of `Init` and `Configure`.  There should be no public `Init` method.  All initialization should be a part of `Configure`.  And the configuration should be capable of detecting whether parameters has changed, like comparing new and old `dmlc::Parameter`.
- List all parameters that are dependent on `DMatrix`, then move them into `DMatrix` or just deprecate them.  Algorithms should not be dependent on those data distributions parameters.  Since `n_gpus` is about to be deprecated by @RAMitchell .  I think this is doable.  One particular exception is `Predictor`, we can just allocate both `cpu_predictor` and `gpu_predictor`, and choose to use one of them during iteration without deleting the other.
- Configure for every iteration.

**Comment by RAMitchell** [comment]
Clearing up config/init methods is a solid plan. These methods are [often considered](https://softwareengineering.stackexchange.com/questions/334970/are-init-methods-a-code-smell) a 'code smell' and mean that we can't be sure if an object is safe to use or what state it might be in.

**Comment by RAMitchell** [comment]
Another thing that may help improve clarity is parameter structs being immutable. It's very hard to tell what's going on if they read state in from external parameter dicts then change the value. Some examples: num_class, updater.

**Comment by trivialfis** [comment]
@RAMitchell 

> parameter structs being immutable.

I totally agree.  But let me get configuration right first.  Fixing its bugs is exhausting and wasting time.

**Comment by trivialfis** [comment]
Will leave further development to parameters validation.
