### ISSUE TITLE
[JVM-Package] Consider updating kryo to 2.22 in xgboost4j

### ISSUE THREAD

**Issue by phillyfan1138** [dmlc/xgboost#4548]
When I use xboost4j in Spark 2.3.0 or 2.3.3, I get the following warning message:

Warning: Local jar /root/.ivy2/jars/com.esotericsoftware.reflectasm_reflectasm-1.07.jar does not exist, skipping.

When connecting over Livy, this warning becomes and error and I can't continue.  I believe that this issue is due to Kryo 2.21 and is fixed in Kryo 2.22.

**Comment by CodingCat** [comment]
is there any references to this error?

**Comment by phillyfan1138** [comment]
The error is 

ERROR spark.SparkContext: Error initializing SparkContext.
java.io.FileNotFoundException: File file:[myhome]/.ivy2/jars/com.esotericsoftware.reflectasm_reflectasm-1.07.jar does not exist

**Comment by CodingCat** [comment]
I mean why it is related to 2.21 v.s. 2.22?

**Comment by phillyfan1138** [comment]
Great question!  I had thought I had read that this issue was fixed in 2.22 but I can't find where I read it now.  

Have you had this warning show in testing?  I'd be happy to run a test against several versions of kryo to see if it helps.

**Comment by phillyfan1138** [comment]
I was able to get around the error by adding kryo 2.22 to my spark-defaults.conf:

```
spark.jars.packages=ml.combust.mleap:mleap-spark-extension_2.11:0.13.0,ml.combust.mleap:mleap-xgboost-spark_2.11:0.13.0,ml.dmlc:xgboost4j-spark:0.82,com.esotericsoftware.kryo:kryo:2.22
```

So it does seem like kryo 2.22 would fix the issue.

**Comment by phillyfan1138** [comment]
And I just confirmed in a docker image using apache spark:

./spark-shell --packages=ml.combust.mleap:mleap-spark-extension_2.11:0.13.0,ml.combust.mleap:mleap-xgboost-spark_2.11:0.13.0,ml.dmlc:xgboost4j-spark:0.82,com.esotericsoftware.kryo:kryo:2.22

Does not give me the warning.

**Comment by CodingCat** [comment]
sure, welcome to file a PR for this

**Comment by phillyfan1138** [comment]
Opened a PR.
