### ISSUE TITLE
XGBModel.predict() documentation conflicting with implementation

### ISSUE THREAD

**Issue by jniemin** [dmlc/xgboost#4549]
Using version 0.90 and documentation states that `XGBModel.predict()` data parameter is `DMatrix

```
Parameters
        ----------
        data : DMatrix
            The dmatrix storing the input.
```

But when checking actual code first line of `predict()` take data passes to it and converts it to `DMatrix`

```
test_dmatrix = DMatrix(data, missing=self.missing, nthread=self.n_jobs)
```

**Comment by trivialfis** [comment]
Fixed in  #4592.
