### ISSUE TITLE
Early stopping returns minimum value if the eval_metric is AUCPR 

### ISSUE THREAD

**Issue by Vivekreddyd** [dmlc/xgboost#4550]
Hello Team,

I’m performing xgboost with eval_metric as ‘aucpr’ and early_stopping_rounds = 20.

When performing early stopping the model returns only the minimum value and early stopping stops if the value does not decrease in 20 iterations, but the case should be opposite. Can you please check the issue.

Thanks,
Vivek.

**Comment by hcho3** [comment]
@Vivekreddyd Which version of XGBoost are you using? The issue you are mentioning has been fixed starting with version 0.82, and AUCPR will be maximized in early stopping.
