### ISSUE TITLE
Xgboost load_model, save_model specifications

### ISSUE THREAD

**Issue by Yuan-Chang-UT** [dmlc/xgboost#4551]
Hi,

I'm trying to translate another format of gradient boosting trees to xgboost models. The only way to make an xgboost model without training one seems to be load_model from the proprietary format file you can get from save_model. Are there any specs on the file save_model exports so that I can translate my other model into a file that can be loaded via load_model?

Thank you.

**Comment by hcho3** [comment]
There is no formal spec, however you can inspect the serialization logic in https://github.com/dmlc/treelite/blob/master/src/frontend/xgboost.cc.

In the long term, we would like to adopt JSON as serialization format.

**Comment by Yuan-Chang-UT** [comment]
I see the logic in there for loading models, do you know where the logic is for saving models? As my goal is to given a model of another format, save it as a xgboost model. @hcho3 

Thanks so much for your help

**Comment by Yuan-Chang-UT** [comment]
@hcho3 https://github.com/dmlc/xgboost/blob/ea4441775405b97d99ebc6b997b726b64564723b/src/learner.cc#L389

is that it?

**Comment by trivialfis** [comment]
@Yuan-Chang-UT Yes.

**Comment by trivialfis** [comment]
@Yuan-Chang-UT Feel free to open new issues  for further questions.
