### ISSUE TITLE
Segmentation fault Error when i compile the src with GPU support

### ISSUE THREAD

**Issue by moabaom** [dmlc/xgboost#4557]
Environment  : 
Ubuntu 18.4 , CUDA 10.0, cmake 3.15.0-rc1

~/xgboost/build$ make -j 4

Scanning dependencies of target dmlc
Scanning dependencies of target rabit
Scanning dependencies of target objxgboost
[  1%] Building CXX object CMakeFiles/rabit.dir/rabit/src/allreduce_base.cc.o
[  2%] Building CXX object CMakeFiles/rabit.dir/rabit/src/allreduce_robust.cc.o
[  4%] Building CXX object dmlc-core/CMakeFiles/dmlc.dir/src/build_config.cc.o
[  5%] Building CXX object src/CMakeFiles/objxgboost.dir/c_api/c_api.cc.o
/home/mo/xgboost/dmlc-core/src/build_config.cc:14:6: warning: #warning "Redefining fopen64 with std::fopen" [-Wcpp]
     #warning "Redefining fopen64 with std::fopen"
      ^~~~~~~
[  6%] Building CXX object dmlc-core/CMakeFiles/dmlc.dir/src/config.cc.o
[  8%] Building CXX object dmlc-core/CMakeFiles/dmlc.dir/src/data.cc.o
[  9%] Building CXX object dmlc-core/CMakeFiles/dmlc.dir/src/io.cc.o
[ 10%] Building CXX object CMakeFiles/rabit.dir/rabit/src/engine.cc.o
[ 12%] Building CXX object CMakeFiles/rabit.dir/rabit/src/c_api.cc.o
[ 13%] Linking CXX static library librabit.a
[ 13%] Built target rabit
[ 15%] Building CXX object dmlc-core/CMakeFiles/dmlc.dir/src/recordio.cc.o
[ 16%] Building CXX object src/CMakeFiles/objxgboost.dir/c_api/c_api_error.cc.o
[ 17%] Building CXX object src/CMakeFiles/objxgboost.dir/common/common.cc.o
[ 19%] Building CXX object dmlc-core/CMakeFiles/dmlc.dir/src/io/line_split.cc.o
[ 20%] Building CXX object dmlc-core/CMakeFiles/dmlc.dir/src/io/recordio_split.cc.o
[ 21%] Building CXX object dmlc-core/CMakeFiles/dmlc.dir/src/io/indexed_recordio_split.cc.o
[ 23%] Building CXX object src/CMakeFiles/objxgboost.dir/common/hist_util.cc.o
[ 24%] Building CXX object dmlc-core/CMakeFiles/dmlc.dir/src/io/input_split_base.cc.o
[ 26%] Building CXX object dmlc-core/CMakeFiles/dmlc.dir/src/io/filesys.cc.o
[ 27%] Building CXX object dmlc-core/CMakeFiles/dmlc.dir/src/io/local_filesys.cc.o
[ 28%] Building CXX object src/CMakeFiles/objxgboost.dir/common/host_device_vector.cc.o
[ 30%] Building CXX object src/CMakeFiles/objxgboost.dir/data/data.cc.o
[ 31%] Building CXX object src/CMakeFiles/objxgboost.dir/data/simple_csr_source.cc.o
[ 32%] Building CXX object src/CMakeFiles/objxgboost.dir/data/simple_dmatrix.cc.o
[ 34%] Building CXX object src/CMakeFiles/objxgboost.dir/data/sparse_page_dmatrix.cc.o
[ 35%] Linking CXX static library libdmlc.a
[ 35%] Built target dmlc
[ 36%] Building CXX object src/CMakeFiles/objxgboost.dir/data/sparse_page_raw_format.cc.o
[ 38%] Building CXX object src/CMakeFiles/objxgboost.dir/data/sparse_page_source.cc.o
[ 39%] Building CXX object src/CMakeFiles/objxgboost.dir/data/sparse_page_writer.cc.o
[ 41%] Building CXX object src/CMakeFiles/objxgboost.dir/gbm/gblinear.cc.o
[ 42%] Building CXX object src/CMakeFiles/objxgboost.dir/gbm/gbm.cc.o
[ 43%] Building CXX object src/CMakeFiles/objxgboost.dir/gbm/gbtree.cc.o
[ 45%] Building CXX object src/CMakeFiles/objxgboost.dir/learner.cc.o
[ 46%] Building CXX object src/CMakeFiles/objxgboost.dir/linear/linear_updater.cc.o
[ 47%] Building CXX object src/CMakeFiles/objxgboost.dir/linear/updater_coordinate.cc.o
[ 49%] Building CXX object src/CMakeFiles/objxgboost.dir/linear/updater_shotgun.cc.o
[ 50%] Building CXX object src/CMakeFiles/objxgboost.dir/logging.cc.o
[ 52%] Building CXX object src/CMakeFiles/objxgboost.dir/metric/elementwise_metric.cc.o
[ 53%] Building CXX object src/CMakeFiles/objxgboost.dir/metric/metric.cc.o
[ 54%] Building CXX object src/CMakeFiles/objxgboost.dir/metric/multiclass_metric.cc.o
[ 56%] Building CXX object src/CMakeFiles/objxgboost.dir/metric/rank_metric.cc.o
[ 57%] Building CXX object src/CMakeFiles/objxgboost.dir/objective/hinge.cc.o
[ 58%] Building CXX object src/CMakeFiles/objxgboost.dir/objective/multiclass_obj.cc.o
[ 60%] Building CXX object src/CMakeFiles/objxgboost.dir/objective/objective.cc.o
[ 61%] Building CXX object src/CMakeFiles/objxgboost.dir/objective/rank_obj.cc.o
[ 63%] Building CXX object src/CMakeFiles/objxgboost.dir/objective/regression_obj.cc.o
[ 64%] Building CXX object src/CMakeFiles/objxgboost.dir/predictor/cpu_predictor.cc.o
[ 65%] Building CXX object src/CMakeFiles/objxgboost.dir/predictor/predictor.cc.o
[ 67%] Building CXX object src/CMakeFiles/objxgboost.dir/tree/split_evaluator.cc.o
[ 68%] Building CXX object src/CMakeFiles/objxgboost.dir/tree/tree_model.cc.o
[ 69%] Building CXX object src/CMakeFiles/objxgboost.dir/tree/tree_updater.cc.o
[ 71%] Building CXX object src/CMakeFiles/objxgboost.dir/tree/updater_colmaker.cc.o
[ 72%] Building CXX object src/CMakeFiles/objxgboost.dir/tree/updater_histmaker.cc.o
[ 73%] Building CXX object src/CMakeFiles/objxgboost.dir/tree/updater_prune.cc.o
[ 75%] Building CXX object src/CMakeFiles/objxgboost.dir/tree/updater_quantile_hist.cc.o
[ 76%] Building CXX object src/CMakeFiles/objxgboost.dir/tree/updater_refresh.cc.o
[ 78%] Building CXX object src/CMakeFiles/objxgboost.dir/tree/updater_skmaker.cc.o
[ 79%] Building CXX object src/CMakeFiles/objxgboost.dir/tree/updater_sync.cc.o
[ 80%] Building CUDA object src/CMakeFiles/objxgboost.dir/common/common.cu.o
[ 82%] Building CUDA object src/CMakeFiles/objxgboost.dir/common/hist_util.cu.o
[ 83%] Building CUDA object src/CMakeFiles/objxgboost.dir/common/host_device_vector.cu.o
[ 84%] Building CUDA object src/CMakeFiles/objxgboost.dir/linear/updater_gpu_coordinate.cu.o
[ 86%] Building CUDA object src/CMakeFiles/objxgboost.dir/metric/elementwise_metric.cu.o
Segmentation fault (core dumped)
src/CMakeFiles/objxgboost.dir/build.make:634: recipe for target 'src/CMakeFiles/objxgboost.dir/linear/updater_gpu_coordinate.cu.o' failed
make[2]: *** [src/CMakeFiles/objxgboost.dir/linear/updater_gpu_coordinate.cu.o] Error 139
make[2]: *** Waiting for unfinished jobs....
Segmentation fault (core dumped)
src/CMakeFiles/objxgboost.dir/build.make:621: recipe for target 'src/CMakeFiles/objxgboost.dir/common/host_device_vector.cu.o' failed
make[2]: *** [src/CMakeFiles/objxgboost.dir/common/host_device_vector.cu.o] Error 139
Segmentation fault (core dumped)
src/CMakeFiles/objxgboost.dir/build.make:608: recipe for target 'src/CMakeFiles/objxgboost.dir/common/hist_util.cu.o' failed
make[2]: *** [src/CMakeFiles/objxgboost.dir/common/hist_util.cu.o] Error 139
Segmentation fault (core dumped)
src/CMakeFiles/objxgboost.dir/build.make:647: recipe for target 'src/CMakeFiles/objxgboost.dir/metric/elementwise_metric.cu.o' failed
make[2]: *** [src/CMakeFiles/objxgboost.dir/metric/elementwise_metric.cu.o] Error 139
CMakeFiles/Makefile2:261: recipe for target 'src/CMakeFiles/objxgboost.dir/all' failed
make[1]: *** [src/CMakeFiles/objxgboost.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by trivialfis** [comment]
You should report the bug to CUDA, not XGBoost.

**Comment by RAMitchell** [comment]
Cuda 10.0 had some bugs, try upgrading to 10.1 and see if that fixes your problem.
