### ISSUE TITLE
ValueError: Unable to parse node: 0:

### ISSUE THREAD

**Issue by renqipan** [dmlc/xgboost#4561]
Plot tree encounter errors. How to fix the problems.
![image](https://user-images.githubusercontent.com/50622344/59480774-8342ae00-8e94-11e9-86f5-568acf46406c.png)
![image](https://user-images.githubusercontent.com/50622344/59480791-96557e00-8e94-11e9-9993-708adc17989f.png)

**Comment by trivialfis** [comment]
Maybe try to remove space in feature names.  If it doesn't work please share a reproducible dataset.

**Comment by renqipan** [comment]
the dataset is too big, and it cann't be upload here.  Can I send you the original dataset by email?  I do need your help. thank you


> Maybe try to remove space in feature names. If it doesn't work please share a reproducible dataset.

**Comment by trivialfis** [comment]
@renqipan Can you isolate some failing samples first?  If not I will look into it after sorting out some floating PRs.

**Comment by renqipan** [comment]
sorry. I can not solve the problem

**Comment by renqipan** [comment]
Dear Jiaming Yuan,

   I have proposed an issue on xgboost in github, and you have gaven reply. the website is:

    https://github.com/dmlc/xgboost/issues/4561

I think you must be an expert in xgboost. Can you give me a favour? Can you tell me how to plot the decision tree diagram . the dataset is available in the attachment. Thank you for your kindness.

Best wishes,

Yours sincerely,

Renqi Pan



                                                          

在 2019-06-14 11:36:31，"Jiaming Yuan" <notifications@github.com> 写道：


@renqipan Can you isolate some failing samples first? If not I will look into it after sorting out some floating PRs.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

从网易163邮箱发来的云附件
dataset.tar.xz (26.43M, 2019年6月29日 15:16 到期)
下载

**Comment by trivialfis** [comment]
@renqipan Thanks for the dataset.  Will look into this.

**Comment by trivialfis** [comment]
I'm lowering down the dot file construction into c++, which might take some time.

**Comment by yosefit86** [comment]
I changed num_trees form 0 to 2 and it worked!!!!!!

but I don't know this is a true result or not????
import matplotlib.pyplot as plt

xgb.plot_tree(xg_reg,num_trees=2)# first run num_trees seted to  zero
plt.rcParams['figure.figsize'] = [500, 100]
plt.show()

wish to helped

**Comment by trivialfis** [comment]
I fixed in master branch, in above referenced PR .
