### ISSUE TITLE
no printing when using gpu_hist

### ISSUE THREAD

**Issue by panranyang** [dmlc/xgboost#4564]
I tried to change the value of silent and verbosity, but still there's nothing to print when tree_method is gpu_hist. I'm sure printing works fine when I used hist.

My CUDA version : 9.2.148
gpu version :396.37
gpu: gtx1080

**Comment by trivialfis** [comment]
What output are you expecting?

**Comment by panranyang** [comment]
Like 
tree pruning end, 1roots, xx extra nodes, xx pruned nodes, max_depth=x

**Comment by trivialfis** [comment]
@panranyang They have different implementation, see

https://github.com/dmlc/xgboost/blob/master/src/tree/updater_gpu_hist.cu

for GPU Hist.
