### ISSUE TITLE
[jvm-package] looser throw specifier for ‘virtual xgboost::data::SimpleDMatrix::~SimpleDMatrix() noexcept (false)’

### ISSUE THREAD

**Issue by cyzhangchenya** [dmlc/xgboost#4567]
XGBoost base version: 0.72
Git cherry-pick: https://github.com/dmlc/xgboost/pull/3697/commits/d95c2b2591eaa773df44bb9ecf03561e45bdc53b
Dev environment: Red Hat Enterprise Linux Workstation 7.3

Cloned `dmlc-core` and `rabbit` to the `xgboost` repository.
Run `./build.sh`.

Exception trace:
In file included from src/data/data.cc:10:0:
src/data/./simple_dmatrix.h:20:7: error: looser throw specifier for ‘virtual xgboost::data::SimpleDMatrix::~SimpleDMatrix() noexcept (false)’
 class SimpleDMatrix : public DMatrix {
       ^
In file included from src/data/data.cc:5:0:
include/xgboost/data.h:297:11: error:   overriding ‘virtual xgboost::DMatrix::~DMatrix() noexcept (true)’
   virtual ~DMatrix() = default;
           ^
make: *** [build/data/data.o] Error 1

Should I include some additional commits to make the cherry-picked one work?

**Comment by CodingCat** [comment]
Run mvn package -DskipTests?

**Comment by cyzhangchenya** [comment]
fyi. Root directory: `ls`
amalgamation  CITATION         cub        include                 jvm-packages  nccl            rabit      tests
appveyor.yml  cmake            demo       ISSUE_TEMPLATE.md       LICENSE       NEWS.md         README.md
build         CMakeLists.txt   dmlc-core  Jenkinsfile             make          plugin          R-package
build.sh      CONTRIBUTORS.md  doc        Jenkinsfile-restricted  Makefile      python-package  src

`cd jvm-package` --> `mvn package -DskipTests`:
...
[ 44%] Building CXX object CMakeFiles/objxgboost.dir/src/data/data.cc.o
In file included from /home/cyzhang/IdeaProjects/xgboost-github/xgboost-upstream/src/data/data.cc:10:0:
/home/cyzhang/IdeaProjects/xgboost-github/xgboost-upstream/src/data/./simple_dmatrix.h:20:7: error: looser throw specifier for ‘virtual xgboost::data::SimpleDMatrix::~SimpleDMatrix() noexcept (false)’
 class SimpleDMatrix : public DMatrix {
       ^
In file included from /home/cyzhang/IdeaProjects/xgboost-github/xgboost-upstream/src/data/data.cc:5:0:
/home/cyzhang/IdeaProjects/xgboost-github/xgboost-upstream/include/xgboost/data.h:297:11: error:   overriding ‘virtual xgboost::DMatrix::~DMatrix() noexcept (true)’
   virtual ~DMatrix() = default;
           ^
gmake[2]: *** [CMakeFiles/objxgboost.dir/src/data/data.cc.o] Error 1
gmake[1]: *** [CMakeFiles/objxgboost.dir/all] Error 2
gmake: *** [all] Error 2
building Java wrapper
Traceback (most recent call last):
cd ..
mkdir -p build
  File "create_jni.py", line 89, in <module>
cd build
    run("cmake --build . --config Release")
  File "create_jni.py", line 51, in run
    subprocess.check_call(command, shell=True, **kwargs)
cmake .. -DUSE_S3:BOOL=OFF -DUSE_OPENMP:BOOL=ON -DPLUGIN_UPDATER_GPU:BOOL=OFF -DUSE_AZURE:BOOL=OFF -DUSE_HDFS:BOOL=OFF -DJVM_BINDINGS:BOOL=ON
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
cmake --build . --config Release
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cmake --build . --config Release' returned non-zero exit status 2
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:804)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:751)
    at org.codehaus.mojo.exec.ExecMojo.execute (ExecMojo.java:313)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for XGBoost JVM Package 0.72:
[INFO] 
[INFO] XGBoost JVM Package ................................ SUCCESS [  2.721 s]
[INFO] xgboost4j .......................................... FAILURE [01:01 min]
[INFO] xgboost4j-spark .................................... SKIPPED
[INFO] xgboost4j-flink .................................... SKIPPED
[INFO] xgboost4j-example .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:04 min
[INFO] Finished at: 2019-06-14T21:03:20-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:exec (native) on project xgboost4j: Command execution failed.: Process exited with an error: 1 (Exit value: 1) -> [Help 1]

The reason why I ran `./build.sh` at the root directory: 
`libxgboost.a` and `libxgboost.so` can be created under `lib` and `xgboost` can be created under root.

btw. It is not related to the cherry-picked commit because I set the head back to:
`commit 5c152d730c8fb562702f77e40a3687ff2ec577b6`, branch `release_0.72`. 
The issue still persists.

**Comment by cyzhangchenya** [comment]
Sorry, I just saw @trivialfis's commit. Will try now.

**Comment by cyzhangchenya** [comment]
Hi @CodingCat @trivialfis: 

Our base version is `release_0.72`. 

After adding the latest commit change:
```
class SparsePageDMatrix : public DMatrix {
 public:
  explicit SparsePageDMatrix(std::unique_ptr<DataSource>&& source,
                             std::string  cache_info)
      : source_(std::move(source)), cache_info_(std::move(cache_info)) {
  }

  virtual ~SparsePageDMatrix() = default;

  MetaInfo& Info() override {
    return source_->info;
  }
```

The issue still persists:
In file included from src/data/data.cc:10:0:
src/data/./simple_dmatrix.h:20:7: error: looser throw specifier for ‘virtual xgboost::data::SimpleDMatrix::~SimpleDMatrix() noexcept (false)’
 class SimpleDMatrix : public DMatrix {
       ^
In file included from src/data/data.cc:5:0:
include/xgboost/data.h:297:11: error:   overriding ‘virtual xgboost::DMatrix::~DMatrix() noexcept (true)’
   virtual ~DMatrix() = default;
           ^
make: *** [build/data/data.o] Error 1

**Comment by trivialfis** [comment]
What compiler are you using?

**Comment by CodingCat** [comment]
Please try the latest version, in theory, we do not support ancient versions like 0.72 anymore

**Comment by cyzhangchenya** [comment]
@trivialfis  
gcc version 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC) 

@CodingCat 
Sorry for asking about the ancient version! We are supporting xgboost at LinkedIn and we are quite lagging behind from the latest one. The current support version is 0.72 at the company and we have teams who are in urgent need to use https://github.com/dmlc/xgboost/commit/d95c2b2591eaa773df44bb9ecf03561e45bdc53b. 

Our plan for next quarter is to bump up to 0.82 and hopefully 0.90 very soon.

**Comment by trivialfis** [comment]
@cyzhangchenya I think that's a compiler bug in old gcc that fails to deduce exception specification.  If it's urgent can you try working around it by writing the destructor for both `DMatrix` and `SimpleDMatrix` yourself with `= default` removed?  I don't want to add the workaround to master branch since auto deduction is the recommanded way in c++11.

**Comment by cyzhangchenya** [comment]
@trivialfis Some follow-up questions:
- Do you also see this on a clean build of v0.72 and could you share your compiler version, and the exception specification (if any)? We are trying to understand what might be the root cause of this exception.
- Do you have any recommendation or anything we need to pay attention to when writing the destructors for both `DMatrix` and `SimpleMatrix`? We haven't got many opportunities to dive into the C++ code of xgboost.

**Comment by CodingCat** [comment]
Try dev/build-docker.sh in jvm folder (you can also check docket image
there)

It is used for release, I didn’t see this problem in my side

**Comment by cyzhangchenya** [comment]
@CodingCat 
###Experiment 1
```
[cyzhang@cyzhang-ld1 dev]$ ./build-docker.sh
++ pwd
+ sudo docker run --rm -m 4g -e JAVA_OPTS=-Xmx6g --attach stdin --attach stdout --attach stderr --volume /home/cyzhang/IdeaProjects/xgboost-github/xgboost-upstream/jvm-packages/dev/../:/xgboost codingcat/xgbrelease:latest /xgboost/jvm-packages/dev/build.sh
Unable to find image 'codingcat/xgbrelease:latest' locally
latest: Pulling from codingcat/xgbrelease
02901d68ac03: Pull complete 
582217d81109: Pull complete 
10da23fb2227: Pull complete 
8e677a448ce3: Pull complete 
c29065970c11: Pull complete 
cdb60c45b7aa: Pull complete 
cdb1cab35de6: Pull complete 
10ec9d0558da: Pull complete 
02383dbb078f: Pull complete 
c5eec01faeec: Pull complete 
81009679c808: Pull complete 
d98161ad54ac: Pull complete 
0e04829ef0c5: Pull complete 
d4ebcf05484d: Pull complete 
b6a2d1b17c08: Pull complete 
502ceeb2a120: Pull complete 
Digest: sha256:c76b670b187e6d0b6c668f9b2b4bb610493da799bb98ca840f14bbfe338d043d
Status: Downloaded newer image for codingcat/xgbrelease:latest
docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"/xgboost/jvm-packages/dev/build.sh\": stat /xgboost/jvm-packages/dev/build.sh: no such file or directory": unknown.
```
```
[cyzhang@cyzhang-ld1 dev]$ pwd
/home/cyzhang/IdeaProjects/xgboost-github/xgboost-upstream/jvm-packages/dev
[cyzhang@cyzhang-ld1 dev]$ ls
build-docker.sh  build.sh  change_version.sh
```
```
[cyzhang@cyzhang-ld1 xgboost-upstream]$ ls
amalgamation  CITATION         cub        include                 jvm-packages  Makefile  python-package  src
appveyor.yml  cmake            demo       ISSUE_TEMPLATE.md       lib           nccl      rabit           tests
build         CMakeLists.txt   dmlc-core  Jenkinsfile             LICENSE       NEWS.md   README.md
build.sh      CONTRIBUTORS.md  doc        Jenkinsfile-restricted  make          plugin    R-package
```
```
[cyzhang@cyzhang-ld1 xgboost-upstream]$ git log
commit 5c152d730c8fb562702f77e40a3687ff2ec577b6 (HEAD -> li-0.11, tag: li-0.11u-base, upstream/release_0.72, origin/li-0.11u)
Author: Philip Hyunsu Cho <chohyu01@cs.washington.edu>
Date:   Thu Sep 27 23:06:14 2018 -0700

    Separate out restricted and unrestricted tasks (#3736)
```
I cannot run `./build.sh` from `xgboost-upstream` to have `libxgboost.a` and `libxgboost.so` be created under `lib` and `xgboost` be created under `xgboost-upstream` as described above.

###Experiement 2
Following the installation guide https://xgboost.readthedocs.io/en/latest/build.html:
```
[cyzhang@cyzhang-ld1 IdeaProjects]$ git clone --recursive https://github.com/dmlc/xgboost
Cloning into 'xgboost'...
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 29011 (delta 0), reused 1 (delta 0), pack-reused 29006
Receiving objects: 100% (29011/29011), 11.94 MiB | 26.23 MiB/s, done.
Resolving deltas: 100% (16735/16735), done.
Submodule 'cub' (https://github.com/NVlabs/cub) registered for path 'cub'
Submodule 'dmlc-core' (https://github.com/dmlc/dmlc-core) registered for path 'dmlc-core'
Submodule 'rabit' (https://github.com/dmlc/rabit) registered for path 'rabit'
Cloning into '/home/cyzhang/IdeaProjects/xgboost/cub'...
remote: Enumerating objects: 32671, done.        
remote: Total 32671 (delta 0), reused 0 (delta 0), pack-reused 32671        
Receiving objects: 100% (32671/32671), 16.51 MiB | 32.45 MiB/s, done.
Resolving deltas: 100% (28643/28643), done.
Cloning into '/home/cyzhang/IdeaProjects/xgboost/dmlc-core'...
remote: Enumerating objects: 5640, done.        
remote: Total 5640 (delta 0), reused 0 (delta 0), pack-reused 5640        
Receiving objects: 100% (5640/5640), 1.42 MiB | 9.42 MiB/s, done.
Resolving deltas: 100% (3416/3416), done.
Cloning into '/home/cyzhang/IdeaProjects/xgboost/rabit'...
remote: Enumerating objects: 8, done.        
remote: Counting objects: 100% (8/8), done.        
remote: Compressing objects: 100% (7/7), done.        
remote: Total 3337 (delta 0), reused 2 (delta 0), pack-reused 3329        
Receiving objects: 100% (3337/3337), 962.56 KiB | 9.17 MiB/s, done.
Resolving deltas: 100% (2169/2169), done.
Submodule path 'cub': checked out 'b20808b1b04ec3d6a625e51fbc1eb76f337754ad'
Submodule path 'dmlc-core': checked out '3943914eed66470bd010df581e29e4dca4f7df6f'
Submodule path 'rabit': checked out 'a429748e244f67f6f144a697f3aa1b1978705b11'
[cyzhang@cyzhang-ld1 IdeaProjects]$ cd xgboost
[cyzhang@cyzhang-ld1 xgboost]$ mkdir build
[cyzhang@cyzhang-ld1 xgboost]$ cd build
[cyzhang@cyzhang-ld1 build]$ ls
[cyzhang@cyzhang-ld1 build]$ cd ..
[cyzhang@cyzhang-ld1 xgboost]$ ls
amalgamation  CITATION        CONTRIBUTORS.md  dev        include            jvm-packages  Makefile  python-package  R-package
appveyor.yml  cmake           cub              dmlc-core  Jenkinsfile        LICENSE       NEWS.md   rabit           src
build         CMakeLists.txt  demo             doc        Jenkinsfile-win64  make          plugin    README.md       tests
[cyzhang@cyzhang-ld1 xgboost]$ cd build
[cyzhang@cyzhang-ld1 build]$ cmake ..
-- The CXX compiler identification is GNU 4.8.5
-- The C compiler identification is GNU 4.8.5
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- CMake version 3.5.2
CMake Error at CMakeLists.txt:13 (message):
  GCC version must be at least 5.0!

-- Configuring incomplete, errors occurred!
See also "/home/cyzhang/IdeaProjects/xgboost/build/CMakeFiles/CMakeOutput.log".
```
Do we have a requirement on GCC version being 5.0 for the latest release?

###Experiement 3
If I switch to `release-0.72`, I can `cmake ..` successfully. 
However, when running `make -j4`, I still see the same exception of `SimpleDMatrix`:
```
Scanning dependencies of target rabit
Scanning dependencies of target dmlc
Scanning dependencies of target objxgboost
[  1%] Building CXX object CMakeFiles/rabit.dir/rabit/src/allreduce_base.cc.o
[  3%] Building CXX object CMakeFiles/rabit.dir/rabit/src/allreduce_robust.cc.o
[  5%] Building CXX object dmlc-core/CMakeFiles/dmlc.dir/src/recordio.cc.o
[  6%] Building CXX object CMakeFiles/objxgboost.dir/src/tree/updater_fast_hist.cc.o
[  8%] Building CXX object dmlc-core/CMakeFiles/dmlc.dir/src/config.cc.o
[ 10%] Building CXX object dmlc-core/CMakeFiles/dmlc.dir/src/data.cc.o
[ 11%] Building CXX object dmlc-core/CMakeFiles/dmlc.dir/src/io.cc.o
[ 13%] Building CXX object CMakeFiles/rabit.dir/rabit/src/engine.cc.o
[ 15%] Building CXX object CMakeFiles/rabit.dir/rabit/src/c_api.cc.o
[ 16%] Building CXX object dmlc-core/CMakeFiles/dmlc.dir/src/build_config.cc.o
/home/cyzhang/IdeaProjects/xgboost/dmlc-core/src/build_config.cc:14:6: warning: #warning "Redefining fopen64 with std::fopen" [-Wcpp]
     #warning "Redefining fopen64 with std::fopen"
      ^
[ 18%] Building CXX object CMakeFiles/objxgboost.dir/src/tree/updater_histmaker.cc.o
[ 20%] Linking CXX static library librabit.a
[ 20%] Built target rabit
[ 22%] Building CXX object dmlc-core/CMakeFiles/dmlc.dir/src/io/line_split.cc.o
[ 23%] Building CXX object CMakeFiles/objxgboost.dir/src/tree/updater_colmaker.cc.o
[ 25%] Building CXX object dmlc-core/CMakeFiles/dmlc.dir/src/io/recordio_split.cc.o
[ 27%] Building CXX object CMakeFiles/objxgboost.dir/src/tree/tree_updater.cc.o
[ 28%] Building CXX object dmlc-core/CMakeFiles/dmlc.dir/src/io/indexed_recordio_split.cc.o
[ 30%] Building CXX object dmlc-core/CMakeFiles/dmlc.dir/src/io/input_split_base.cc.o
[ 32%] Building CXX object CMakeFiles/objxgboost.dir/src/tree/updater_prune.cc.o
[ 33%] Building CXX object dmlc-core/CMakeFiles/dmlc.dir/src/io/filesys.cc.o
[ 35%] Building CXX object dmlc-core/CMakeFiles/dmlc.dir/src/io/local_filesys.cc.o
[ 37%] Building CXX object CMakeFiles/objxgboost.dir/src/tree/tree_model.cc.o
[ 38%] Building CXX object CMakeFiles/objxgboost.dir/src/tree/updater_sync.cc.o
[ 40%] Building CXX object CMakeFiles/objxgboost.dir/src/tree/updater_skmaker.cc.o
[ 42%] Linking CXX static library libdmlc.a
[ 42%] Built target dmlc
[ 44%] Building CXX object CMakeFiles/objxgboost.dir/src/tree/updater_refresh.cc.o
[ 45%] Building CXX object CMakeFiles/objxgboost.dir/src/objective/rank_obj.cc.o
[ 47%] Building CXX object CMakeFiles/objxgboost.dir/src/objective/regression_obj.cc.o
[ 49%] Building CXX object CMakeFiles/objxgboost.dir/src/objective/objective.cc.o
[ 50%] Building CXX object CMakeFiles/objxgboost.dir/src/objective/multiclass_obj.cc.o
[ 52%] Building CXX object CMakeFiles/objxgboost.dir/src/c_api/c_api.cc.o
[ 54%] Building CXX object CMakeFiles/objxgboost.dir/src/c_api/c_api_error.cc.o
[ 55%] Building CXX object CMakeFiles/objxgboost.dir/src/common/hist_util.cc.o
[ 57%] Building CXX object CMakeFiles/objxgboost.dir/src/common/host_device_vector.cc.o
[ 59%] Building CXX object CMakeFiles/objxgboost.dir/src/common/common.cc.o
[ 61%] Building CXX object CMakeFiles/objxgboost.dir/src/data/sparse_page_raw_format.cc.o
[ 62%] Building CXX object CMakeFiles/objxgboost.dir/src/data/sparse_page_source.cc.o
[ 64%] Building CXX object CMakeFiles/objxgboost.dir/src/data/simple_csr_source.cc.o
[ 66%] Building CXX object CMakeFiles/objxgboost.dir/src/data/data.cc.o
[ 67%] Building CXX object CMakeFiles/objxgboost.dir/src/data/simple_dmatrix.cc.o
In file included from /home/cyzhang/IdeaProjects/xgboost/src/data/data.cc:10:0:
/home/cyzhang/IdeaProjects/xgboost/src/data/./simple_dmatrix.h:20:7: error: looser throw specifier for ‘virtual xgboost::data::SimpleDMatrix::~SimpleDMatrix() noexcept (false)’
 class SimpleDMatrix : public DMatrix {
       ^
In file included from /home/cyzhang/IdeaProjects/xgboost/src/data/data.cc:5:0:
/home/cyzhang/IdeaProjects/xgboost/include/xgboost/data.h:297:11: error:   overriding ‘virtual xgboost::DMatrix::~DMatrix() noexcept (true)’
   virtual ~DMatrix() = default;
           ^
In file included from /home/cyzhang/IdeaProjects/xgboost/src/data/simple_dmatrix.cc:11:0:
/home/cyzhang/IdeaProjects/xgboost/src/data/./simple_dmatrix.h:20:7: error: looser throw specifier for ‘virtual xgboost::data::SimpleDMatrix::~SimpleDMatrix() noexcept (false)’
 class SimpleDMatrix : public DMatrix {
       ^
In file included from /home/cyzhang/IdeaProjects/xgboost/src/data/simple_dmatrix.cc:7:0:
/home/cyzhang/IdeaProjects/xgboost/include/xgboost/data.h:297:11: error:   overriding ‘virtual xgboost::DMatrix::~DMatrix() noexcept (true)’
   virtual ~DMatrix() = default;
           ^
[ 69%] Building CXX object CMakeFiles/objxgboost.dir/src/data/sparse_page_dmatrix.cc.o
make[2]: *** [CMakeFiles/objxgboost.dir/src/data/data.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/objxgboost.dir/src/data/simple_dmatrix.cc.o] Error 1
make[1]: *** [CMakeFiles/objxgboost.dir/all] Error 2
make: *** [all] Error 2
```
I also could not build the docker as suggested due to the same exception in `Experiment 1`:
```
[cyzhang@cyzhang-ld1 dev]$ ./build-docker.sh
++ pwd
+ sudo docker run --rm -m 4g -e JAVA_OPTS=-Xmx6g --attach stdin --attach stdout --attach stderr --volume /home/cyzhang/IdeaProjects/xgboost/jvm-packages/dev/../:/xgboost codingcat/xgbrelease:latest /xgboost/jvm-packages/dev/build.sh
[sudo] password for cyzhang: 
docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"/xgboost/jvm-packages/dev/build.sh\": stat /xgboost/jvm-packages/dev/build.sh: no such file or directory": unknown.
[cyzhang@cyzhang-ld1 dev]$ pwd
/home/cyzhang/IdeaProjects/xgboost/jvm-packages/dev
[cyzhang@cyzhang-ld1 dev]$ ls
build-docker.sh  build.sh  change_version.sh
```

**Comment by trivialfis** [comment]
> Do you also see this on a clean build of v0.72

@cyzhangchenya No, I have never seen this before.  Currently XGBoost is tested with 5.3 .  I think 0.72 was tested with 4.8, so I don't know why it fails on your side.  Based on the error message you provided, you can try replacing both default destructors with:

`virtual ~DMatrix() noexcept (true) {}` and `virtual ~SimpleDMatrix() noexcept (true) {}`.

**Comment by cyzhangchenya** [comment]
Adding `virtual ~SimpleDMatrix() noexcept (true) {}` to `/src/data/simple_dmatrix.h`, together with https://github.com/dmlc/xgboost/pull/4568/commits/f1f73deeca856c162aaa2ff0036f7bdc6b368a22, I am able to run `./build.sh` from root to have `libxgboost.a` and `libxgboost.so` be created under `lib` and `xgboost` is also created.

Navigating to `jvm-packages`, I can run `./create_jni.py` successfully.

Appreciate both of your prompt suggestions. 👍 @CodingCat @trivialfis

**Comment by CodingCat** [comment]
@cyzhangchenya so regarding upgrade, recommend to jump 0.9 directly, we have a bug in 0.82 which messed up prediction dataframe in some cases,
