### ISSUE TITLE
Multi-GPU not faster than only one GPU

### ISSUE THREAD

**Issue by panranyang** [dmlc/xgboost#4573]
I tired benchmark_tree.py and my own dataset,  n_gpu=1 worked even better than  n_gpu=2.
I'm sure that tow gpus working together when n_gpu=2  by nvidia-smi.
I'm just wondering if it worked normally or I got something wrong.

My CUDA version : 9.2.148
xgboost version: 0.82
python: 2.7.10
GPU version :396.37
GPU: gtx1080 * 2

**Comment by trivialfis** [comment]
@panranyang It's possible, see comment in https://xgboost.readthedocs.io/en/latest/gpu/index.html#single-node-multi-gpu
