### ISSUE TITLE
question about bst.dump_model, what's the value after 'leaf=' mean?

### ISSUE THREAD

**Issue by wenmin-wu** [dmlc/xgboost#458]
Hello!
  I have dumped the model after I have trained. I found some lines like:
"
227:leaf=0.0938776
228:leaf=-0.0333333
"
 what does the value after "leaf=" mean? It means the predicted value of this value or the weight of this path?

**Comment by tqchen** [comment]
see http://xgboost.readthedocs.org/en/latest/model.html It is the score in the leaf
