### ISSUE TITLE
how to set eval_set and eval_group when fitting the XGBRanker model?

### ISSUE THREAD

**Issue by cmcai0104** [dmlc/xgboost#4581]
I'm not understand the state of eval_group in fit function that  
> A list that contains the group size corresponds to each (X, y) pair in eval_set.

When I set eval_set to be list of (X, y) pair, eval_group to be the list of length of each group, return Error: the length of eval_set must be match with the length of eval_group.

But when I set eval_set to be list of (X, y)pair where X and y is one group of X and y, it also does not work.

**Comment by hcho3** [comment]
Take a look at the demo [here](https://github.com/dmlc/xgboost/blob/986fee60229c77920e93ae3b374c2e674faee78d/demo/rank/rank_sklearn.py). In particular, pay attention to the lines
https://github.com/dmlc/xgboost/blob/986fee60229c77920e93ae3b374c2e674faee78d/demo/rank/rank_sklearn.py#L33-L34

**Comment by cmcai0104** [comment]
> Take a look at the demo [here](https://github.com/dmlc/xgboost/blob/986fee60229c77920e93ae3b374c2e674faee78d/demo/rank/rank_sklearn.py). In particular, pay attention to the lines
> https://github.com/dmlc/xgboost/blob/986fee60229c77920e93ae3b374c2e674faee78d/demo/rank/rank_sklearn.py#L33-L34

Thank you for you replay!

And I have one more question. How to set eval_set and eval_group when I want to useing RandomizedSearchCV. I want to train a lamdbamart ranking model.
