### ISSUE TITLE
TypeError: can not initialize DMatrix from DMatrix

### ISSUE THREAD

**Issue by renqipan** [dmlc/xgboost#4582]
xg_class= xgb.XGBClassifier(objective ='reg:logistic', colsample_bytree = 0.3, learning_rate = 0.1, max_depth = 8, alpha = 10, n_estimators = 10)
weight_train=weight_train*10**4
weight_test=weight_test*10**4
import numpy as np
weight_train=np.asarray(weight_train)
weight_test=np.asarray(weight_test)
dtest = xgb.DMatrix(data=X_test,weight=weight_test)
xg_class.fit(X_train, y_train,sample_weight=weight_train)
#the next line occur errors
preds=xg_class.predict(dtest) 

TypeError: can not initialize DMatrix from DMatrix

**Comment by hcho3** [comment]
For `XGBClassifier.predict()`, you should pass the NumPy array directly:
```python
preds=xg_class.predict(X_test)
```

The docstring incorrectly stated that DMatrix should be passed; #4592 fixes it.
