### ISSUE TITLE
AttributeError: 'Booster' object has no attribute 'predict_proba'

### ISSUE THREAD

**Issue by renqipan** [dmlc/xgboost#4583]
import numpy as np
weight_train=np.asarray(weight_train)
weight_test=np.asarray(weight_test)
y_test=np.asarray(y_test)
y_train=np.asarray(y_train)
data_dmatrix = xgb.DMatrix(data=X_train,label=y_train,weight=weight_train)
params = {"objective":"reg:logistic",'colsample_bytree': 0.3,'learning_rate': 0.1,
                'max_depth': 8, 'alpha': 10,"eval_metric":"error"}
cv_results = xgb.cv(dtrain=data_dmatrix, params=params, nfold=3,num_boost_round=10,early_stopping_rounds=5, as_pandas=True, seed=123)
xg_reg = xgb.train(params=params, dtrain=data_dmatrix, num_boost_round=10,)
dtest = xgb.DMatrix(data=X_test,weight=weight_test)
dtest = xgb.DMatrix(data=X_test,weight=weight_test)
y_preds=xg_reg.predict(dtest)
#next line occurs errors
probs =xg_reg.predict_proba(X_test)
AttributeError: 'Booster' object has no attribute 'predict_proba'

**Comment by hcho3** [comment]
`predict_proba()` method only exists for the scikit-learn interface (`XGBClassifier` / `XGBRegressor`). Please use `xg_reg.predict()` instead.

**Comment by zdwhite** [comment]
@hcho3 
This is a non helpful response. Could you possibly explain how to do that given the current problem?
