### ISSUE TITLE
Make GBTree reusable

### ISSUE THREAD

**Issue by narayananunny** [dmlc/xgboost#4586]
Currently the implementation of GBTree in the gbtree.cc without being exposed through an include file. This makes inheriting and extending GBTree very difficult. The only other option is to modify gbtree.cc in place which is not very neat when trying to use xgboost as a library. Could gbtree.cc be restructured so that its interface is exposed through a header file.

**Comment by trivialfis** [comment]
We don't have a c++ interface yet.  If you want to add your code, please try making it part of XGBoost or a plugins.
