### ISSUE TITLE
Basic tree algos distributed

### ISSUE THREAD

**Issue by xiaozhongtian** [dmlc/xgboost#4595]
Hello,
I have seen the tutorial that with the parameters in sci-kit learn like API

- `n_estimators` = `num_parallel_tree`

- `learning_rate` =`1 `

- `colsample_bynode` and `subsample` = `0.8 `

- `booster`  = `'gbtree'`
can construct the `RandomForest` in sci-kit learn but in distributed version.

And can I do the same thing with the different combination of the parameters  to construct the
`DecisionTreeClassifier` ,`AdaBoostClassifier` , `ExtraTreesClassifier`?

I can't use the sci-kit learn because of the problem of the memory in the single machine.

**Comment by trivialfis** [comment]
You can use single tree with one boosting round to train a decision tree.  AdaBoost is not supported.  For the last one, check out tutorial for random forest in doc.

**Comment by xiaozhongtian** [comment]
Thanks for your responds.
Is the `num_iterations`  the parameter corresponding to the boosting round?
I can set it `n_estimators = 1` and  `num_iterations=1` to construct the DecisionTree?

**Comment by thvasilo** [comment]
` num_iterations` determines the boosting rounds yes. This means that if you set that to one, your model will train a single tree.
