### ISSUE TITLE
TPOT using XGBoost WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.

### ISSUE THREAD

**Issue by fcoppey** [dmlc/xgboost#4599]
Hello,

I get this warning when using XGBoost in TPOT Pipeline, any idea why? TPOT developers say they do not set reg:linear.

**Comment by trivialfis** [comment]
Fixed in master branch.

**Comment by vladimirkovacevic** [comment]
When I install XGBoost on Mac with:
```pip install xgboost```
I'm keep getting this message. Can you suggest what to do to remove it?

**Comment by trivialfis** [comment]
Use `reg:squarederror` or build from master branch.  See document about objective parameter.

**Comment by KhaaQ** [comment]
I installed XGBoost Few days before and I was facing the same problem.
The answer is given in the error message. I changed Regressor model parameter: objective = 'reg:lineaqr' to 'reg:squarederror'.
example:
xg_reg = xgb.XGBRegressor(objective ='reg:squarederror', colsample_bytree = 0.3, learning_rate = 0.1, max_depth = 5, alpha = 10, n_estimators = 10)

And now its not giving any warning.
