### ISSUE TITLE
Forcing certain columns while others remain random

### ISSUE THREAD

**Issue by mpekalski** [dmlc/xgboost#460]
I asked this question on Kaggle.com forum, https://www.kaggle.com/c/springleaf-marketing-response/forums/t/16141/xgboost-python-wrapper-questions/90544#post90544, but was encuraged to ask it here. :)

Is there is a way of forcing xgboost to use certain columns while also specifying colsample_bytree parameter? So, the algorithm would take some columns I want and then randomly make a draw from the remaining ones for each tree it builds. My understanding it that for each tree different draw is taking place.

**Comment by tqchen** [comment]
Unfortunately currently it is not obvious to do so. If you like to hack the code, you can do it in column select part in here https://github.com/dmlc/xgboost/blob/master/src/tree/updater_colmaker-inl.hpp#L165
