### ISSUE TITLE
[jvm-packages] Add option to treat 0's as 0's in sparse vectors instead of missing values?

### ISSUE THREAD

**Issue by nedStackAdapt** [dmlc/xgboost#4601]
Many tree packages don't have a missing value branch on their tree nodes (e.g. Spark).  It is often useful to translate from XGBoost results to a different tree package.

Currently, XGBoost treats zeros in sparse vectors as missing values.  Is it possible to add an option to treat 0's as 0's instead of as missing values for sparse vectors?  That way data specified as sparse vectors will have no missing values... just 0's?  This will allow for translating the resulting trees into different packages.  It would be a very useful option, I think.

**Comment by CodingCat** [comment]
I think you are talking about XGBoost-Spark

are you saying that you do not like Spark's VectorAssembler's behavior that treat 0 as the only accepted missing value option, and you want XGBoost to revert that behavior by translating SparseVector to DenseVector?

**Comment by nedStackAdapt** [comment]
You are right that I'm mostly referring to XGBoost-Spark, but I don't think I'm saying that... let me be more specific with an example.

We create an input vector that has a lot of dummy-coded features, so just 0/1 values but many coordinates of them.  Spark stores this as a Sparse Vector, to save memory, which is good because there are many coordinates of 0/1 values.  When putting this vector into XGBoost, it treats the 0's as missing values and uses the missing value branch.  This makes it hard to translate the results of XGBoost back to Spark or a different tree software, because they don't have missing value branches.

I'd still like to store things as a Sparse Vector because it saves large amounts of memory.  But, it would be nice to have XGBoost treat the 0's in the sparse vector (which are actually missing coordinates, because Sparse Vectors don't store 0's) as 0's instead of missing values.  That would allow translating the trees back to Spark.

So, I'm not saying translating Sparse Vector to Dense Vector -- that consumes a lot of memory.  I'm saying treat the missing coordinates in Sparse Vector as 0's, not missing values, if that makes sense?

**Comment by CodingCat** [comment]
that's the same thing, you don't want 0 to be taken as missing values, then you need to save it in somewhere to feed to XGBoost <= translating sparse to dense

1. As I said , spark's vector assembler only takes 0 as missing value, when it comes to XGBoost training phase, all those 0s have been removed from input

2. XGBoost by default treats NaN as the missing value, but because of 1, it will treat 0s as missing value as well

3. since 2 is very confusing, we require users to set missing value option in xgboost as 0 if they are using sparse vector since 0.9 otherwise the training / prediction will fail

**Comment by nedStackAdapt** [comment]
I understand a bit more... let me say it another way then...

The XGBoost option I'd be asking for is to treat the missing values as 0's in XGBoost without actually increasing the memory storage.

**Comment by CodingCat** [comment]
> I understand a bit more... let me say it another way then...
> 
> The XGBoost option I'd be asking for is to treat the missing values as 0's in XGBoost without actually increasing the memory storage.

I don't think we can do that, essentially it comes XGBoost treats a missing value as non-missing , then it confuses the all logic in handling missing values in XGBoost, more specifically

when we create a DMatrix, we treat 0 as missing value, later after we feed DMatrix to XGBoost, we have to leak this concrete value taken as missing to core training algorithm, which is expected to take those values back by manipulating all data files....


we can ask @hcho3 @RAMitchell @trivialfis for more ideas

**Comment by nedStackAdapt** [comment]
I don't understand the XGBoost code base very well, but is it possible to do something like change the dereference operator of BatchIterator to insert the 0's for missing values right before use by the algorithm?

Something perhaps here in data.h line 316?

  const SparsePage& operator*() const {
    CHECK(impl_ != nullptr);
    return *(*impl_);
  }

Just a thought...

**Comment by CodingCat** [comment]
how you ` insert the 0's for missing values ` `without actually increasing the memory storage.`?

**Comment by nedStackAdapt** [comment]
It would increase it just for the one row that is currently getting processed, as opposed to for the whole dataset, if that makes sense?

So, as the algorithm is iterating over the rows gathering statistics, only the current row getting processed would have the increased memory usage?

**Comment by trivialfis** [comment]
>  BatchIterator to insert the 0's for missing values right before use by the algorithm?

Let's not do that.

>  one row that is currently getting processed,

Tree algorithm doesn't necessarily process data row by row, actually I believe the whole dataset is loaded into updaters unless external memory is used.

So if I understand correctly, the 0s are removed in spark, but you want them somehow restored in XGBoost?

**Comment by nedStackAdapt** [comment]
> So if I understand correctly, the 0s are removed in spark, but you want them somehow restored in XGBoost?

Yeah, so they don't get treated as missing values but as 0's.  But to do that without blowing up memory usage...

> Tree algorithm doesn't necessarily process data row by row, actually I believe the whole dataset is loaded into updaters unless external memory is used.

Ok, I need to read more to understand how the tree updaters work.

**Comment by trivialfis** [comment]
I don't think we can implement that.  There's no way to distinguish actual missing values from zeros.

**Comment by hcho3** [comment]
@nedStackAdapt The first-class support for sparse data with missing values is one of strengths of XGBoost. Other tree packages (e.g. scikit-learn) will force you to impute missing values first before training, whereas XGBoost can handle missing values natively.

So there will always be some difference between XGBoost models and models created by other packages.

**Comment by nedStackAdapt** [comment]
@hcho3 I understand and value the missing value handling in XGBoost, its top notch.  The only issue in this case is that the values are not actually missing -- they are just 0's.  The 0's don't get stored in the sparse vector only to save memory, not because they are missing values.

But I understand if it is too hard to disambiguate these things in the XGBoost code.  Thanks for thinking about it.

**Comment by trivialfis** [comment]
@nedStackAdapt I don't know how spark works, but I think implementing a sparse vector is quite simple.

To me your issue is in sparse vector doesn't support compressing values other than zeros, not in machine learning libraries...  So maybe a better solution would be improving the vector class.

**Comment by nedStackAdapt** [comment]
@trivialfis Ok, then I wasn't communicating clearly.  There are no missing values in my dataset.  It is just big with lots of 0 values, so it is stored as a sparse vector to save memory.  

But the 0 values get treated as missing values in XGBoost... That's the issue.

**Comment by trivialfis** [comment]
I will try to see if it's possible for XGBoost to eliminate copying data under some conditions.

**Comment by trivialfis** [comment]
@nedStackAdapt Got it.  Thanks for the clarification.  Let us think about solutions other than restoring 0 for categorical data.  It's quite difficult for XGBoost to do that right now.

**Comment by zhangxiubo** [comment]
My understanding is that when training with sparse input matrix and a special "missing" value is specified (say Float.NaN), XGBoost will first go through the non-zero entries of the sparse matrix and remove any entries that takes that value from the sparse data structure; afterwards, any "empty" entries in the training matrix will be consider as missing values.

I'd image if there is only a couple of non-missing zero values, one would be able to circumvent this behaviour by explicitly setting their values to `0.0` in the sparse matrix.

As @nedStackAdapt mentioned, for sparse matrices, the semantics is typically that the "empty" entries represents `0`s, not missing values. To solve this issue, I wonder if we can ask the user to explicitly declare a value that would like XGBoost to consider as missing without removing them from the sparse matrix's internal structure?
