### ISSUE TITLE
xgb.train(): Segmentation fault, core dumped

### ISSUE THREAD

**Issue by chenxuanhanhao** [dmlc/xgboost#4603]
Program received signal SIGSEGV, Segmentation fault.
0x00002aaaaaab6b26 in elf_machine_rela (reloc=0x2aaafe5ea298, reloc=0x2aaafe5ea298, skip_ifunc=0,
    reloc_addr_arg=0x2aaafe62ff08, version=0x30, sym=0x2aaafe5e9620, map=0x555556ccb830)
    at ../sysdeps/x86_64/dl-machine.h:279
279	      struct link_map *sym_map = RESOLVE_MAP (&sym, version, r_type);

**Comment by trivialfis** [comment]
@chenxuanhanhao Could you provide a reproducible script?  And also OS, compiler, XGBoost version/commit. 

I don't understand why would training failed during system dynamic linking.

**Comment by trivialfis** [comment]
I don't think this is related to XGBoost.
