### ISSUE TITLE
How to load model saved in text format to XGboost booster?

### ISSUE THREAD

**Issue by peeyushpashine123** [dmlc/xgboost#4606]
I am reconstructing model from pmml by creating a text dump. Now I need to use this text dump to be loaded in the model and as I understand booster can load only binary dump. what is the workaround? I have seen the issue [3291](https://github.com/dmlc/xgboost/issues/3291).

**Comment by trivialfis** [comment]
No workaround yet.  The dumped model is for presentation purposes.

**Comment by peeyushpashine123** [comment]
@trivialfis Is there any way to internally convert the parameters/attributes directly to binary format? lets say I have all the information that I am saving in text format, instead of that I want to save directly to binary format.
