### ISSUE TITLE
Issue 4228 Reopened

### ISSUE THREAD

**Issue by rothn** [dmlc/xgboost#4611]
Same issue as described in:
https://github.com/dmlc/xgboost/issues/4228

Reproducible example:
feature name: "foo_bar == 2"

**Comment by hcho3** [comment]
@rothn #4228 was fixed in the latest master. You can compile and run by
```
git clone --recursive https://github.com/dmlc/xgboost
cd xgboost
mkdir build
cd build
cmake ..
make
cd ..
```

**Comment by rothn** [comment]
Sorry, just realized that although the commit is dated in March, the merge only happened 17 hours ago.
