### ISSUE TITLE
XGBoost crashes in Windows 10 due to incompatible DLL dependencies

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#4616]
In https://discuss.xgboost.ai/t/xgboost-crash-on-windows-10/984?u=hcho3, a user reports that the official Python distribution of XGBoost crashes on Windows 10 Pro. Currently, we only test XGBoost against Windows Server editions.

@trivialfis @RAMitchell @rongou @sriramch Have you ever run into issues when installing XGBoost on Windows using `pip install xgboost`?

~TODO: Add Windows 10 Pro to Jenkins CI. Since AWS only provides Server editions of Windows, we'll need to use VirtualBox.~

**Comment by RAMitchell** [comment]
Haven't encountered this myself but haven't been doing a lot of work on Windows lately.

**Comment by hcho3** [comment]
Update: I did not manage to reproduce the issue. Here are the steps I took:

1. Make a fresh installation of Windows 10 Education Edition inside VirtualBox.
2. Install Miniconda.
3. Activate the conda environment and install NumPy and SciPy:
```cmd
conda activate
conda install numpy scipy
```
4. Install XGBoost.
```cmd
pip install xgboost
```
5. Run the following script:
```python
import xgboost

dtrain = xgboost.DMatrix('agaricus.txt.train')
dtest = xgboost.DMatrix('agaricus.txt.test')

params = {'booster': 'gbtree', 'objective': 'binary:logistic',
          'learning_rate': 1.0, 'gamma': 1.0, 'min_child_weight': 1.0,
          'max_depth': 3, 'eval_metric': 'auc'}

bst = xgboost.train(params, dtrain, num_boost_round=10,
                    evals=[(dtrain, 'train'), (dtest, 'test')])

print(bst.predict(dtest))
```

The script managed to run without crashing.

**Comment by hcho3** [comment]
Closing for now.
