### ISSUE TITLE
xgb.DMatrix returns a "can not open file 'H'" error when passed a matrix.

### ISSUE THREAD

**Issue by deanmckee007** [dmlc/xgboost#462]

**Comment by hetong007** [comment]
Can you please provide a reproducible example of code?

**Comment by deanmckee007** [comment]
library(readr)
train <- read_csv("train.csv", n_max=60000)
y = train$target
xgtrain = xgb.DMatrix(as.matrix(train), label = y, missing = NA)

*This time it gave an 'can not open file "     2" '   error
*The data are available at https://www.kaggle.com/c/springleaf-marketing-response/data

**Comment by deanmckee007** [comment]
I'm using xgboost_0.4-2

**Comment by hetong007** [comment]
Please try use `data.matrix` to transform a `data.frame` object into a `matrix`.

**Comment by deanmckee007** [comment]
Nice work, sir.  Thank  you.

**Comment by tqchen** [comment]
@hetong007 since dataframe is common, consider add a special check to produce a nice error message
