### ISSUE TITLE
ONNX export is now available in onnxmltools

### ISSUE THREAD

**Issue by sandys** [dmlc/xgboost#4626]
hi guys,
xgboost export is now available (and exposed) in Onnxmltools repo - https://github.com/onnx/onnxmltools/pull/318

I am aware that xgboost has a RFC for a new export format, however given that onnx is supporting xgboost - will the xgboost project considering adopting ONNX as *one* of the officially supported export formats ?

**Comment by hcho3** [comment]
Sure, we can add a link to your repository in [this page](https://github.com/dmlc/xgboost/tree/master/demo). Thanks for writing the convertor.

Side note: #3980 defines a new **serialization** format, i.e. round-trip (save and then load) will preserve all data internal to XGBoost models. So it is different from export formats, where round-trip ability is not a concern.

**Comment by sandys** [comment]
@hcho3 I would like to resurface this issue now - since 1.0 has been released. 

xgboost has chosen to provide support to a readable format in JSON. This is a great thing, however it has chosen to go with a **proprietary JSON format** instead of something like ONNX.
https://xgboost.readthedocs.io/en/latest/tutorials/saving_model.html?highlight=json

I would like to highlight that ONNX has both Microsoft and Facebook supporting it officially (including Pytorch, etc).

ONNX has already built out fairly good support for xgboost **already**. You can see the xgboost ONNX converter here - https://github.com/onnx/onnxmltools/tree/master/onnxmltools/convert/xgboost

Microsoft has recently opensourced high performance ONNX serving runtime - https://cloudblogs.microsoft.com/opensource/2020/01/21/microsoft-onnx-open-source-optimizations-transformer-inference-gpu-cpu/ (including GPU)

The stewardship of ONNX has moved to the Linux Foundation - https://lfai.foundation/press-release/2019/11/14/lf-ai-welcomes-onnx/
ONNX is also proposed to be added to LLVM MLIR https://github.com/onnx/onnx/issues/2499

I would like to reiterate request for adding official ONNX support. There are open json optimisation issues (https://github.com/dmlc/xgboost/pull/5046). Given the maturity of onnx tools towards xgboost already, i personally believe that the ONNX team will be happy to do this on xgboost behalf.

**Comment by trivialfis** [comment]
I am aware of this onnx convertor, it's based on model dump which is a JSON format.   The JSON format is still a very good IR for transforming to other languages.

**Comment by trivialfis** [comment]
We chose JSON because it's easy to parse, hence easy to be reused.  The performance issue you mentioned exists also in onnx.  It's about fast round-trip floating point parsing and printing.  Having said that we definitely like more tools available.  So contribution are welcomed. :-)

**Comment by sandys** [comment]
Thanks for replying.

Sorry for asking - will you guys be switching to ONNX to be a superior long
term investment instead of pickle for example  ?

You will be able to leverage a far larger ecosystem with a lot of resources
and tooling.

Pickle is production ready, but has compatibility issues with versions,etc.
JSON will take time to mature. ONNX will allow deployment either locally or
on cloud services.

**Comment by hcho3** [comment]
We are already deprecating the use of pickle in favor of JSON serialization. We developed an in-house JSON format because we wanted to be able to **save a “complete snapshot” of XGBoost objects**. ONNX only saves the trees so is not a substitute for this use case.

**Comment by hcho3** [comment]
See https://github.com/dmlc/xgboost/issues/4855 to understand the distinction between model and snapshot. Snapshot captures all details of internal objects, including training hyperparameters.

**Comment by trivialfis** [comment]
The question is whether should we have native support for onnx I think.  Here is my two cents.  If we were to support onnx, it should be based on existing JSON serialization.  So there's no “switch” , only adding a new “backend layer”.

**Comment by trivialfis** [comment]
If you don't mind writing C++, you can directly use to in memory JSON object to export the model to onnx without parsing/generating again.

**Comment by trivialfis** [comment]
Thanks for the work on this, let's focus on future plans on https://github.com/dmlc/xgboost/issues/5392 .
