### ISSUE TITLE
Plugin example not working for python

### ISSUE THREAD

**Issue by wagnew3** [dmlc/xgboost#4627]
The plugin example (https://github.com/dmlc/xgboost/tree/master/plugin/example) does not work. When I compile from source as a python package after following instructions for the plugin example I get the error "xgboost.core.XGBoostError: b'[03:34:57] /home/willie/xgboost/src/objective/objective.cc:23: Unknown objective function mylogistic\n\n".

**Comment by hcho3** [comment]
@wagnew3 Were you using CMake when compiling XGBoost? The instruction in the plugin example seems to be assuming the use of plain Makefile.
