### ISSUE TITLE
[jvm-packages] spark hangs when training is run in quick succession

### ISSUE THREAD

**Issue by thesuperzapper** [dmlc/xgboost#4628]
I am getting an infinite hang when I run the following code a few times in quick succession:
```
import ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier

val dataPath = "__SPARK_HOME_LOCATION__/data/mllib/sample_binary_classification_data.txt"
val data = spark.read.format("libsvm").option("vectorType", "dense").load(dataPath)
val xgbClassifier = new XGBoostClassifier()

xgbClassifier.fit(data).transform(data).show()
```

**Steps to reproduce:**
1. open spark-shell with xgboost jars
2. Run the above code
3. quickly rerun the last line until a hang happens

**Other information:**
When the hang happens I only get the tracker message, and nothing after that, I have to kill the spark job. (If I wait between runs, they always succeed. )
```
Tracker started, with env={DMLC_NUM_SERVER=0, DMLC_TRACKER_URI=XXX.XXX.XXX.XXX, DMLC_TRACKER_PORT=9096, DMLC_NUM_WORKER=2}
```

**My environment:**
* XGBoost Master
* Spark 2.4.3
* (Happens in both: __Zeppelin__ and __Spark-Shell__)

**Comment by CodingCat** [comment]
Currently, parallel training for multiple models is not supported

**Comment by thesuperzapper** [comment]
@CodingCat

In this case, I am letting each training finish, so it's only one model.

However, you're almost certainly right about the cause. That is, I think there is some "cool down" after training each model, in which you can't train another without hanging.

**Comment by thesuperzapper** [comment]
@CodingCat 
After further investigation,  this crash is caused by running the same training within **exactly 60sec** of the last time you ran it.

**Steps to reproduce:**
1. Download Spark 2.4.3 [from here](https://www-us.apache.org/dist/spark/spark-2.4.3/spark-2.4.3-bin-hadoop2.7.tgz), and extract it.
2. Download the following jars from maven:
  * https://repo1.maven.org/maven2/ml/dmlc/xgboost4j/0.90/xgboost4j-0.90.jar
  * https://repo1.maven.org/maven2/ml/dmlc/xgboost4j-spark/0.90/xgboost4j-spark-0.90.jar
  * https://repo1.maven.org/maven2/com/typesafe/akka/akka-actor_2.11/2.3.11/akka-actor_2.11-2.3.11.jar
  * https://repo1.maven.org/maven2/com/typesafe/config/1.2.1/config-1.2.1.jar
3. Run:
```
./spark-2.4.3-bin-hadoop2.7/bin/spark-shell --master local[1] --jars ./xgboost4j-0.90.jar,./xgboost4j-spark-0.90.jar,./akka-actor_2.11-2.3.11.jar,./config-1.2.1.jar
```
4. Run the following code:
```
import ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier

val dataPath = "./spark-2.4.3-bin-hadoop2.7/data/mllib/sample_binary_classification_data.txt"
val data = spark.read.format("libsvm").option("vectorType", "dense").load(dataPath)
val xgbClassifier = new XGBoostClassifier()
```
5. Run the following code:
```
xgbClassifier.fit(data).transform(data).show()
```
6. Wait less than **exactly 60sec**.
7. Run the following code:
```
xgbClassifier.fit(data).transform(data).show()
```
8. ..Crash/Hang..

**Note:**
* This also happens with the Scala Rabit tracker.
* I have tested this on multiple servers/computers running Ubuntu and RedHat.

**Comment by thesuperzapper** [comment]
@CodingCat are you able to reproduce this?

**Comment by chenqin** [comment]
Can you try adding rabit.Shutdown() after calling 
```
xgbClassifier.fit(data).transform(data).show()
```

**Comment by leafjungle** [comment]
I got the same problem: 

org.apache.spark.rdd.RDD.foreachPartition(RDD.scala:956)
ml.dmlc.xgboost4j.scala.spark.XGBoost$$anon$2.run(XGBoost.scala:295)

the spark application hang here for more than 24hours, even I just have 10 train data and set iteration as 2.  I am not sure what it is waiting for.

**Comment by a-johnston** [comment]
I understand that this issue is regarding successive training runs and not parallel but @CodingCat can you give some brief context for why parallel training runs are not supported? Ideally I would like to allocate N workers for each of M parallel training calls (given a cluster allocated to have N*M available workers) to better scale tuning as it there's a sharp falloff in benefit from adding more workers to a single training job. However, bar this, this issue seems like it could be a blocker for even purely sequential tuning which IMO would be a pretty significant issue.

**Comment by trivialfis** [comment]
Closing as barrier mode is now used in the spark package. Feel free to reopen if the issue persists with the latest branch.

**Comment by austinzh** [comment]
Same issue still happen with spark 3.2.2 and xgboost 1.6.1 
@trivialfis 
New observation:
In the same test replace `xgbClassifier.fit(data).transform(data).show()` with `xgbClassifier.fit(data)`
Then I can run without any failure.
@trivialfis  any inside?

**Comment by trivialfis** [comment]
You are correct that prediction doesn't need communication. A PR for the proposed fix would be really appreciated!

**Comment by wbo4958** [comment]
@austinzh will you put up a PR to fix it?

**Comment by austinzh** [comment]
Sure. Let me take it.

**Comment by austinzh** [comment]
For folks has simulor issue.
A quick fix can achieve by run this before your training job.
```
    val spark = org.apache.spark.sql.SparkSession.builder().getOrCreate()
    val nWorker = spark.sparkContext.defaultParallelism
    spark.range(0, nWorker).rdd.barrier.mapPartitions { x => { ml.dmlc.xgboost4j.java.Rabit.shutdown(); x } }.collect()
```

**Comment by austinzh** [comment]
@wbo4958 Any doc or tips about setup a development environment for xgboost4j ?
I am using mac with intellij or vscode.

**Comment by wbo4958** [comment]
@trivialfis since the PR is merged. could you help to close this issue?
