### ISSUE TITLE
Deprecate XGBRegressor.save_model() / XGBClassifier.save_model()

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#4639]
Many methods of `XGBClassifier` relies on the existence of certain fields, such as `self.objective`, `self.missing`, and `self.n_classes_` (these fields exist to ensure interoperability with scikit-learn) and these fields are **not** preserved by the call to `XGBClassifier.save_model()`, as the binary serialization format is not aware of these fields. See #4517, where `XGBClassifier.save_model()` breaks `predict_proba()` for multi-class classifiers.

We should deprecate  `XGBRegressor.save_model()` / `XGBClassifier.save_model()` / `XGBRanker.save_model()` method, because its name is really misleading. Instead, we should re-name it to `export_model_for_external_binding()`.

**Comment by trivialfis** [comment]
I would like to first understand the difference between languages.  I think I might have a chance to join the development of JVM package in near future, so can we hold this off a bit and give me a chance to understand what's the best way to save the model?

**Comment by trivialfis** [comment]
@hcho3 I made the differences clear between model IO and memory based serialization in https://github.com/dmlc/xgboost/pull/4732  and with a RFC here: #4855 .  Feel free to reopen as I'm currently tracking down all related issues can be resolved by JSON PR.

**Comment by hcho3** [comment]
@trivialfis Does your RFC address the Python objects used specifically for scikit-learn binding? We may want to port these objects into the C++ core if we want to aim cross-language compatibility.

**Comment by trivialfis** [comment]
@hcho3 We can add extra code in scikit learn interface for restoring these objects.

**Comment by hcho3** [comment]
@trivialfis What I mean is that semantics of the extra Python objects are lost when the model is serialized and then deserialized into, say, XGBoost4J-Spark.

**Comment by trivialfis** [comment]
@hcho3 Let me try a fix.

**Comment by trivialfis** [comment]
@hcho3 After we have JSON IO, we can append extra fields into the model like `scikit-learn-model`.  This won't effect internal model IO as core C++ doesn't look beyond what's needed.  Just to note that Python JSON implementation has a fast parser but a slow generator.

**Comment by trivialfis** [comment]
Attributes in booster are still lost, but has nothing to do with skl now.  Closing.
