### ISSUE TITLE
[jvm-packages] support for older versions of spark

### ISSUE THREAD

**Issue by thesuperzapper** [dmlc/xgboost#4641]
I believe we can continue to support older versions of Spark in xgboost4j, as most of the things we "require" from versions later than spark 2.2 can easily be ported into this codebase or replaced with other things.

The worst offender is the usage of `org.apache.spark.ml.param.shared` which is effectively dropping support for Spark 2.2 because of a few lines of code defining some parameters and getters/setters. 

I think we should aim to support Spark 2.2 and later with XGBoost 1.0, as many businesses have extremely large clusters running older versions of Spark.

At very least we should support Spark 2.3+

**Comment by CodingCat** [comment]
No, 2.3 is end of life in very soon, 2.4 is the only version we will support before 3.0
