### ISSUE TITLE
Why doesn't XGBoost Core Data Structure include predict_probas method?

### ISSUE THREAD

**Issue by zdwhite** [dmlc/xgboost#4642]
Problem Scope:

I'm working with "medium" sized data. So just large enough to fit in local memory and handle computations with out doing much in the way of memory swapping.

My problem is a pretty basic binary logistic regression that I'd like to utilize GPU and XGboost's dmatrix data structure for making prediction models on my data. The output of which I care about is the predicted probabilities as I want to use them for a scoring function.

Issue:
However you run into a snag that the XGB core doesn't support the predict_probas() method and thus one has to use the Scikitlearn API. Normally this really isn't much of a problem except using the scikit learn API I lose the functionality of XGB's Dmatrix which is a problem as my kernel crashes during fitting.

Could the predict_probas be implemented into the core?

**Comment by hcho3** [comment]
@zdwhite For binary logistic regression, you should set `objective` parameter to `binary:logistic`. Then `predict()` function will give you probability outputs (that is, probability for the positive class).

**Comment by zdwhite** [comment]
> 
> 
> @zdwhite For binary logistic regression, you should set `objective` parameter to `binary:logistic` (not `reg:logistic`. Then `predict()` function will give you probability outputs (that is, probability for the positive class).

Thanks for the response, I was indeed using binary:logistic. However, I felt a bit sheepish after fiddling with it and noticing the values I was getting were indeed probabilities. When reading the docs this wasn't spelled out directly, and was so use to Sklearn's output. 

My mistake.
