### ISSUE TITLE
Getting the feature's matrix in a custom eval metric function

### ISSUE THREAD

**Issue by oren0e** [dmlc/xgboost#4644]
Hi,

I was wondering how can I get access to the features themselves in the custom function of the evaluation metric I am writing. The thing is that I am predicting something (binary variable _y_) but I want to evaluate on the following:
I sum up the _amount_ feature for predicted y = 1, then do the same for true y = 1, and then calculate some sort of percentage error from these two quantities. I want this percentage to be as low as possible.

Can it be done?

**Comment by hcho3** [comment]
Currently, this is not possible, since there is no method to peek inside the `dtrain` object to obtain feature values.

**Comment by yejinru** [comment]
I found that the order of dtrain.get_label() is the same as the original data.
Maybe you can define a global array to store the features map. Then you can feature it in order.

**Comment by trivialfis** [comment]
The feature inside dmatrix is exactly the same with user provided data, just stored as csr.  I believe this can be done by using the original data.
