### ISSUE TITLE
scikit-learn XGBRegressor doesn't work with custom evaluation function that is passed with feval. Is there a solution?

### ISSUE THREAD

**Issue by sharpant** [dmlc/xgboost#4649]
In the below code that uses sci-kit learn, ```XGBRegressor``` does not read ```feval``` input. I found this by debugging the code. Is there a way to make ```XGBRegressor``` read custom evaluation function?

```
multixg = MultiOutputRegressor(XGBRegressor(objective='reg:squarederror',booster='gbtree',
colsample_bytree = 1, nthread=8,learning_rate = 0.5,subsample=1,
disable_default_eval_metric=1, max_depth = 4, gamma=0, reg_lambda=0,
n_estimators=10, verbosity=2,feval=customeval1)) 

# first custom eval function
def customeval1(preds, y_train):
    error=mahalanobis(x=preds,data=y_train) #y_train has two columns for two outcomes
    return 'customeval', error

# evaluation metric to model correlation between outcomes
def mahalanobis(x=None, data=None, cov=None):
    x_minus_mu = x - np.array(np.mean(data)) 
    if not cov:
        cov = np.cov(data.values.T)
    inv_covmat = sp.linalg.inv(cov)
    left_term = np.dot(x_minus_mu, inv_covmat)
    mahal = np.einsum('ij,ji->i', left_term,x_minus_mu.T)  #finding diagonal
    return np.mean(mahal)
```

**Comment by sharpant** [comment]
Following up to check if this a known issue or if there is a solution? Thanks.

**Comment by hcho3** [comment]
That's not where the custom evaluation function should go. You should set `eval_metric` in `fit()` instead: https://xgboost.readthedocs.io/en/latest/python/python_api.html#xgboost.XGBRegressor.fit

Example:
```python
clf.fit(X, y, eval_set=[(X_val, y_val)], eval_metric= customeval1)
```

**Comment by sharpant** [comment]
@hcho3 Thanks for the note. However, I have tried that before. I get this error: `fit() got an unexpected keyword argument 'eval_set'` If I only keep `eval_metrics`, even then I get an error `fit() got an unexpected keyword argument 'eval_metric'` Is .fit defined for `MultiOutputRegressor`? I am using `XGBRegressor` within `MultiOutputRegressor` if you see my code in the initial note. Could you please tell me how to use `eval_metric` within `MultiOutputRegressor`?

**Comment by hcho3** [comment]
@sharpant Where did you get `MultiOutputRegressor` class? You'd need to modify the code inside `MultiOutputRegressor` so that it would call `XGBRegressor.fit()` with `eval_metric` keyword. Or can you call `XGBRegressor.fit()` directly?

**Comment by sharpant** [comment]
@hcho3 I got `MultiOutputRegressor` from here: https://scikit-learn.org/stable/modules/generated/sklearn.multioutput.MultiOutputRegressor.html

This is my revised code where i am using `customeval1` with `fit()` based on your recommendation:

`multixg = MultiOutputRegressor(XGBRegressor(objective='reg:squarederror',booster='gbtree',
colsample_bytree = 1, nthread=8,learning_rate = 0.5,subsample=1,
disable_default_eval_metric=1, max_depth = 4, gamma=0, reg_lambda=0,
n_estimators=10, verbosity=2))`

`multixg.fit(X_train, y_train,eval_set=[(X_test1, y_test1)],eval_metric=customeval1)`

I get the error: `TypeError: fit() got an unexpected keyword argument 'eval_set'`

I am not sure how I can call `XGBRegressor.fit()` directly because I have two outcomes. Any thoughts?

**Comment by hcho3** [comment]
Unfortunately, your use case is currently not supported, since we need to pass extra arguments (`eval_set` and `eval_metric`) and `MultiOutputRegressor` does not recognize these extra arguments.

**Comment by sharpant** [comment]
Oh I see. Unfortunate to know. Could this be a roadmap feature that can be implemented going forward? Thanks!

**Comment by hcho3** [comment]
@sharpant I took a look at the code for `MultiOutputRegressor`, and it looks like just fitting one estimator per target. So maybe you can run XGBRegressor 2 times?
```python
clf1 = XGBRegressor(...)
clf2 = XGBRegressor(...)

clf1.fit(X, y[:,0], eval_set=..., eval_metric=...)
clf2.fit(X, y[:,1], eval_set=..., eval_metric=...)
```

**Comment by sharpant** [comment]
@hcho3 - I want to model correlation between outcomes with my custom eval function that uses mean mahalanobis distance (as can be seen in my initial code above). Hence doing it one at a time will not leverage the correlation between outcomes :(

**Comment by hcho3** [comment]
@sharpant 
> Hence doing it one at a time will not leverage the correlation between outcomes :(

But that's what `MultiOutputRegressor` is doing:
```python
        self.estimators_ = Parallel(n_jobs=self.n_jobs)(
            delayed(_fit_estimator)(
                self.estimator, X, y[:, i], sample_weight)
            for i in range(y.shape[1]))
```
(from https://github.com/scikit-learn/scikit-learn/blob/1495f69242646d239d89a5713982946b8ffcf9d9/sklearn/multioutput.py#L166-L169)

So even if you could use `MultiOutputRegressor`, it will not achieve what you want, I'm afraid.

**Comment by sharpant** [comment]
@hcho3 Yes, while MultiOutputRegressor makes predictions one at a time, the custom eval function will find the mean mahalanobis distance between the two predictions and two outcome columns. Hence, trees will be split based on the custom eval function (leveraging outcome correlation), but the prediction for each outcome will happen separately which is not an issue. Code for custom eval function is reproduced below:

`def customeval1(preds, y_train):`
    `error=mahalanobis(x=preds,data=y_train)` #y_train has two columns for two outcomes
    `return 'customeval', error`

evaluation metric to model correlation between outcomes
`def mahalanobis(x=None, data=None, cov=None):`
    `x_minus_mu = x - np.array(np.mean(data))` 
   ` if not cov:
        cov = np.cov(data.values.T)`
   `inv_covmat = sp.linalg.inv(cov)`
    `left_term = np.dot(x_minus_mu, inv_covmat)`
    `mahal = np.einsum('ij,ji->i', left_term,x_minus_mu.T)`  #finding diagonal
    `return np.mean(mahal)`

So I think using the custom eval function to make tree splits (leveraging outcome correlation) should be possible while each outcome is predicted independent of the other outcome. Do you agree?

**Comment by hcho3** [comment]
> So I think using the custom eval function to make tree splits (leveraging outcome correlation) should be possible while each outcome is predicted independent of the other outcome. Do you agree?

No, I don't think you can use correlation between two targets. Scikit-learn's `MultiOutputRegressor` breaks down target matrix `y` into individual target vectors (`y[:,i]`) and passes to `XGBRegressor.fit()`. So XGBoost will see only one target at a time, and your custom evaluation function will not see two targets.

**Comment by hcho3** [comment]
@sharpant Have you looked into using deep learning frameworks such as MXNet or PyTorch? There, you should have freedom to set up multiple targets and define a loss function that incorporates two targets simultaneously.

**Comment by sharpant** [comment]
Oh I see. Thanks for the info. I want to use tree-based methods as they are better at giving feature importance measures directly, while deep-learning methods require measurement of weights which is a more indirect way of measuring feature importance. Partial dependences with features can also be more easily found with tree-based methods.

My idea to implement a custom eval function with xgboost in Python was inspired from this link on multivariate random forest in R: https://rdrr.io/cran/IntegratedMRF/man/Node_cost.html This however is not efficiently implemented for large datasets in R. As xgboost is known to be better than randomforest, I was looking for such an implementation with xgboost in R or Python. Thanks for your help.

**Comment by hcho3** [comment]
@sharpant 

> I want to use tree-based methods as they are better at giving feature importance measures directly, while deep-learning methods require measurement of weights which is a more indirect way of measuring feature importance. Partial dependences with features can also be more easily found with tree-based methods.

I agree. In addition, computing SHAP is much faster for tree-based models compared to neural nets.
(You can compute SHAP for neural nets but it's going to be very slow)

Currently, I'm working on the [Accelerated Failure Time loss](https://en.wikipedia.org/wiki/Accelerated_failure_time_model) for survival analysis, and as part of that work, I added mechanism to add multiple label fields (`y_lower` and `y_upper` to indicate [censored data](https://en.wikipedia.org/wiki/Censoring_(statistics)). It may be useful for eventually adding multi-label regression as well. The difference here would be that AFT would still predict one single target (time to event), whereas multi-label regression would predict multiple targets.

**Comment by sharpant** [comment]
Thanks for the info and help!

**Comment by sharpant** [comment]
> > So I think using the custom eval function to make tree splits (leveraging outcome correlation) should be possible while each outcome is predicted independent of the other outcome. Do you agree?
> 
> No, I don't think you can use correlation between two targets. Scikit-learn's `MultiOutputRegressor` breaks down target matrix `y` into individual target vectors (`y[:,i]`) and passes to `XGBRegressor.fit()`. So XGBoost will see only one target at a time, and your custom evaluation function will not see two targets.
> 
> In short, `MultiOutputRegressor` fits one model for one target at a time.

@hcho3 - I realized that the inverse correlation matrix `S(inv)` in the formula of [mahalanobis](https://en.wikipedia.org/wiki/Mahalanobis_distance) distance will always be fixed for the observed y (two columns/ouptuts) of the training data. I can find the inverse correlation matrix for the two output columns, treat that matrix as a constant and pass it to the function that finds mahalanobis distance. As long as `preds` in the below function returns predictions for both outcomes, it should be fine even if Scikit-learn's MultiOutputRegressor breaks down target matrix y into individual target vectors `(y[:,i])` and passes to `XGBRegressor.fit()`

`def customeval1(preds, S):`
    `error=mahalanobis(x=preds,data=S)` #S is a 2x2 matrix which is a constant
    `return 'customeval', error`

Not sure if `preds` can return more than one prediction (for two outcomes)? Thanks!

**Comment by JJumSSu** [comment]
@sharpant  Hi, I'm also trying to figure out the way of doing multi-output regression. Were you able to do the multi-output regression by your proposed method?

**Comment by sharpant** [comment]
@JJumSSu My proposed method is currently not supported with `MultiOutputRegressor`. It does not take extra arguments `eval_set` and `eval_metric`. Hopefully that can be implemented in the future. 
You can check out this link https://scikit-learn.org/stable/modules/generated/sklearn.multioutput.RegressorChain.html for a more indirect way of doing multioutput regression (FYI- @hcho3 )
