### ISSUE TITLE
pipy install macosx doesnt support multicore

### ISSUE THREAD

**Issue by ikrenyi1** [dmlc/xgboost#465]
I've installed xgboost with pip install on mac osx mavericks but this way xgboost doesn't appear to support multicore usage. Is there a way to fix this?

**Comment by tqchen** [comment]
This was because the default toolchain in mac do not support multi-core, checkout the build instruction in document for multi-threaded build

**Comment by phunterlau** [comment]
@ikrenyi1 if your mac has brew, please install gcc 4.9 by using `brew install gcc49` and replace the default gcc with gcc 4.9. We also have a static link multiple thread pre-build lib, please check later when the next release is ready.

**Comment by nerdcha** [comment]
`brew install gcc` now gives you 5.2.0, which is `gcc-5` on the Darwin command line. Is there a particular reason to keep using 4.9, or is it just that the xgb docs haven't been updated?

**Comment by phunterlau** [comment]
@mengdong has mentioned in another issue about Makefile needs changes for gcc 5 https://github.com/dmlc/xgboost/issues/276#issuecomment-141471002
