### ISSUE TITLE
Params alpha & lambda for gbtree

### ISSUE THREAD

**Issue by Far0n** [dmlc/xgboost#466]
Hello,

I have a question concerning the parameters alpha & lambda: Why do they influence the results, if booster='gbtree'? According to the documentation they should only affect the linear model.

**Comment by tqchen** [comment]
This appears to be a mistake in the document, lambda and alpha are also parameters for trees, in terms of L2 and L1 norm of leaf weights. see http://xgboost.readthedocs.org/en/latest/model.html

Thanks for reporting this, do you mind open a PR to correct the parameter doc.

Thanks!

**Comment by Far0n** [comment]
done :)

**Comment by walterreade** [comment]
It doesn't appear these parameters are support in the sklearn wrapper. Happy to do a PR unless anyone has already started that.
