### ISSUE TITLE
Install of xgboost reverts IPython version

### ISSUE THREAD

**Issue by grfiv** [dmlc/xgboost#467]
I am trying to run an IPython notebook with xgboost on an AWS standard Ubuntu instance.

1) pip install xgboost fails
2) install from git changes my IPython version from 3.2.1  to 1.2.1 and I can't change it back to anything useful

I wouldn't believe me either but here's the log:

Last login: Sat Sep  5 00:24:52 2015 from c-174-62-169-49.hsd1.ma.comcast.net
ubuntu@ip-172-31-0-129:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty
ubuntu@ip-172-31-0-129:~$ ipython --version
3.2.1                                      <<<<<<<<<<<<==================
ubuntu@ip-172-31-0-129:~$ sudo -H pip install xgboost
Downloading/unpacking xgboost
  Could not find a version that satisfies the requirement xgboost (from versions: 0.4a12, 0.4a13)
Cleaning up...
No distributions matching the version for xgboost
Storing debug log for failure in /root/.pip/pip.log
ubuntu@ip-172-31-0-129:~$ git clone https://github.com/dmlc/xgboost.git
Cloning into 'xgboost'...
remote: Counting objects: 11301, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 11301 (delta 0), reused 0 (delta 0), pack-reused 11293
Receiving objects: 100% (11301/11301), 3.70 MiB | 4.19 MiB/s, done.
Resolving deltas: 100% (7497/7497), done.
Checking connectivity... done.
ubuntu@ip-172-31-0-129:~$ cd xgboost; ./build.sh
g++ -c -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -fopenmp -fPIC -o updater.o src/tree/updater.cpp
g++ -c -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -fopenmp -fPIC -o gbm.o src/gbm/gbm.cpp
g++ -c -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -fopenmp -fPIC -o io.o src/io/io.cpp
g++ -c -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -fopenmp -fPIC -o main.o src/xgboost_main.cpp
cd subtree/rabit;make lib/librabit.a; cd ../..
make[1]: Entering directory `/home/ubuntu/xgboost/subtree/rabit'
g++ -c -O3 -msse2 -fPIC -Wall -Wextra -Wno-unused-parameter -Wno-unknown-pragmas -pedantic   -o allreduce_base.o src/allreduce_base.cc
g++ -c -O3 -msse2 -fPIC -Wall -Wextra -Wno-unused-parameter -Wno-unknown-pragmas -pedantic   -o allreduce_robust.o src/allreduce_robust.cc
g++ -c -O3 -msse2 -fPIC -Wall -Wextra -Wno-unused-parameter -Wno-unknown-pragmas -pedantic   -o engine.o src/engine.cc
ar cr lib/librabit.a allreduce_base.o allreduce_robust.o engine.o
make[1]: Leaving directory `/home/ubuntu/xgboost/subtree/rabit'
g++ -c -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -fopenmp -fPIC -o dmlc_simple.o src/io/dmlc_simple.cpp
g++ -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -fopenmp -fPIC -fPIC -o xgboost updater.o gbm.o io.o main.o subtree/rabit/lib/librabit.a dmlc_simple.o -pthread -lm -lrt
g++ -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -fopenmp -fPIC -fPIC -shared -o wrapper/libxgboostwrapper.so wrapper/xgboost_wrapper.cpp updater.o gbm.o io.o subtree/rabit/lib/librabit.a dmlc_simple.o -pthread -lm -lrt 
Successfully build multi-thread xgboost
ubuntu@ip-172-31-0-129:~/xgboost$ cd python-package/; sudo python setup.py install
running install
running bdist_egg
running egg_info
creating xgboost.egg-info
writing requirements to xgboost.egg-info/requires.txt
writing xgboost.egg-info/PKG-INFO
writing top-level names to xgboost.egg-info/top_level.txt
writing dependency_links to xgboost.egg-info/dependency_links.txt
writing manifest file 'xgboost.egg-info/SOURCES.txt'
reading manifest file 'xgboost.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.sh'
warning: no files found matching '*' under directory 'xgboost/wrapper'
warning: no files found matching '*' under directory 'xgboost/windows'
warning: no files found matching '*' under directory 'xgboost/subtree'
warning: no files found matching '*' under directory 'xgboost/src'
warning: no files found matching '*' under directory 'xgboost/multi-node'
writing manifest file 'xgboost.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/xgboost
copying xgboost/sklearn.py -> build/lib.linux-x86_64-2.7/xgboost
copying xgboost/core.py -> build/lib.linux-x86_64-2.7/xgboost
copying xgboost/__init__.py -> build/lib.linux-x86_64-2.7/xgboost
copying xgboost/plotting.py -> build/lib.linux-x86_64-2.7/xgboost
copying xgboost/training.py -> build/lib.linux-x86_64-2.7/xgboost
copying xgboost/__init__.pyc -> build/lib.linux-x86_64-2.7/xgboost
copying xgboost/build-python.sh -> build/lib.linux-x86_64-2.7/xgboost
copying xgboost/core.pyc -> build/lib.linux-x86_64-2.7/xgboost
copying xgboost/plotting.pyc -> build/lib.linux-x86_64-2.7/xgboost
copying xgboost/sklearn.pyc -> build/lib.linux-x86_64-2.7/xgboost
copying xgboost/training.pyc -> build/lib.linux-x86_64-2.7/xgboost
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/xgboost
copying build/lib.linux-x86_64-2.7/xgboost/sklearn.py -> build/bdist.linux-x86_64/egg/xgboost
copying build/lib.linux-x86_64-2.7/xgboost/sklearn.pyc -> build/bdist.linux-x86_64/egg/xgboost
copying build/lib.linux-x86_64-2.7/xgboost/core.pyc -> build/bdist.linux-x86_64/egg/xgboost
copying build/lib.linux-x86_64-2.7/xgboost/core.py -> build/bdist.linux-x86_64/egg/xgboost
copying build/lib.linux-x86_64-2.7/xgboost/plotting.pyc -> build/bdist.linux-x86_64/egg/xgboost
copying build/lib.linux-x86_64-2.7/xgboost/__init__.py -> build/bdist.linux-x86_64/egg/xgboost
copying build/lib.linux-x86_64-2.7/xgboost/plotting.py -> build/bdist.linux-x86_64/egg/xgboost
copying build/lib.linux-x86_64-2.7/xgboost/training.py -> build/bdist.linux-x86_64/egg/xgboost
copying build/lib.linux-x86_64-2.7/xgboost/training.pyc -> build/bdist.linux-x86_64/egg/xgboost
copying build/lib.linux-x86_64-2.7/xgboost/__init__.pyc -> build/bdist.linux-x86_64/egg/xgboost
copying build/lib.linux-x86_64-2.7/xgboost/build-python.sh -> build/bdist.linux-x86_64/egg/xgboost
installing package data to build/bdist.linux-x86_64/egg
running install_data
copying /home/ubuntu/xgboost/python-package/xgboost/../../wrapper/libxgboostwrapper.so -> build/bdist.linux-x86_64/egg/xgboost
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying xgboost.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying xgboost.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying xgboost.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying xgboost.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying xgboost.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying xgboost.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating dist
creating 'dist/xgboost-0.4-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing xgboost-0.4-py2.7.egg
creating /usr/local/lib/python2.7/dist-packages/xgboost-0.4-py2.7.egg
Extracting xgboost-0.4-py2.7.egg to /usr/local/lib/python2.7/dist-packages
Adding xgboost 0.4 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/xgboost-0.4-py2.7.egg
Processing dependencies for xgboost==0.4
Searching for scipy==0.16.0
Best match: scipy 0.16.0
Adding scipy 0.16.0 to easy-install.pth file

Using /usr/local/lib/python2.7/dist-packages
Searching for numpy==1.8.2
Best match: numpy 1.8.2
Adding numpy 1.8.2 to easy-install.pth file

Using /usr/lib/python2.7/dist-packages
Finished processing dependencies for xgboost==0.4
ubuntu@ip-172-31-0-129:~/xgboost/python-package$ ipython --version
1.2.1                      <<<<<<<<<<<<==================
ubuntu@ip-172-31-0-129:~/xgboost/python-package$

**Comment by phunterlau** [comment]
@grfiv can you try deleting the old pip installation from your site-package directory `print xgboost.__file__` (xgboost-0.4a13.dist-info and xgboost directories), install numpy, scipy firstly, and install xgboost from pip again?

Before 0.4a14, pip install xgboost needs numpy and scipy installed. Some recent change has fixed this problem (PR #502). Please redo the installation from pip.
