### ISSUE TITLE
[jvm-packages] I cannot get xgboost4j and xgboost4j_2.12 packages with the repository "https://raw.githubusercontent.com/CodingCat/xgboost/maven-repo/" 

### ISSUE THREAD

**Issue by marccina** [dmlc/xgboost#4678]
Using this [readme](https://github.com/dmlc/xgboost/tree/master/jvm-packages#access-snapshot-version) on branch 'master' 
(*we would like to use jvm packages for scala 2_12*)

# SBT
sbt compile

# ERRORS
[error] unresolved dependency: ml.dmlc#xgboost4j_2.12;1.0.0-SNAPSHOT: not found
[error] unresolved dependency: ml.dmlc#xgboost4j-spark_2.12;1.0.0-SNAPSHOT: not found

# build.sbt
val xgboostVersion = "1.0.0-SNAPSHOT"

resolvers += "GitHub Repo" at "https://raw.githubusercontent.com/CodingCat/xgboost/maven-repo/"

libraryDependencies ++= Seq(
  "ml.dmlc" % "xgboost4j_2.12" % xgboostVersion,
  "ml.dmlc" % "xgboost4j-spark_2.12" % xgboostVersion
)

Using this repository, we have same issue (404 not found) using 0.90 version for xgboost4j package : https://raw.githubusercontent.com/CodingCat/xgboost/maven-repo/ml/dmlc/xgboost4j/0.90/xgboost4-0.90.pom

**Comment by CodingCat** [comment]
1.0.0-SNAPSHOT hasn't been released

**Comment by marccina** [comment]
Thanks for your reply.

Just what about 0.90 version ? I found only 0.72 version on this repo.
Is it the snapshot repository ? 
(Sorry but I don't understand the jvm-package readme :) )

**Comment by onurzdg** [comment]
> 1.0.0-SNAPSHOT hasn't been released

When will this be released?
