### ISSUE TITLE
[BLOCKING] Per-node sync slows down distributed training with 'hist'

### ISSUE THREAD

**Issue by CodingCat** [dmlc/xgboost#4679]
looks like latest branch has per-node sync again https://github.com/dmlc/xgboost/blob/4ef6d216b9989f0ea7101fcbecefe25f6125c195/src/tree/updater_quantile_hist.cc#L615-L617

**Comment by CodingCat** [comment]
and the grads is also synced per node 

https://github.com/dmlc/xgboost/blob/4ef6d216b9989f0ea7101fcbecefe25f6125c195/src/tree/updater_quantile_hist.cc#L643 (only needed for root actually , check https://github.com/dmlc/xgboost/pull/4140)

**Comment by trivialfis** [comment]
Seems the optimization PR didn't make a clean rebase.

**Comment by CodingCat** [comment]
more discussion at https://github.com/dmlc/xgboost/pull/4716

**Comment by hcho3** [comment]
Re-opening this, since #4716 fixed correctness but did not address performance. @thvasilo points out that syncing for every nodes leads to significant slow-down due to extra communication.

**Comment by thvasilo** [comment]
Copying from the other issue:  While the second per-node sync seems straightforward to fix (see [this WIP](https://github.com/thvasilo/xgboost/commit/8196a16e5732b579addb5e5b7ac3339bd0545758#diff-10aac201acca00858b390ff0d679434fR655)) getting rid of the [first loop](https://github.com/dmlc/xgboost/blob/f0064c07ab70f1c770bb0e9eb64fe85afb3a3d73/src/tree/updater_quantile_hist.cc#L616) could entail changes to how we build and use the `hist_` container (of HistCollection type) which would require a lot of effort to untangle.

**Comment by hcho3** [comment]
@thvasilo Note that this issue is not present in release 0.90. I believe #4529 introduced it. A proper fix would need to first analyze #4529 in detail and selectively revert the parts that cause per-node sync. In 0.90, `hist` performs per-level sync (unless `grow_policy` is specifically set to `lossguide`).
