### ISSUE TITLE
the problem of installing xgboost on ubuntu

### ISSUE THREAD

**Issue by tomdyq** [dmlc/xgboost#468]
I git clone xgboost. Then I enter into xgboost directory and  type the command "make“. It shows the following errors:
![image](https://cloud.githubusercontent.com/assets/5807893/9697288/3d4b19e6-53ba-11e5-8d52-d0628bbb30c7.png)

**Comment by tqchen** [comment]
seems your compiler do not support sse, consider, remove that flag for now

**Comment by tomdyq** [comment]
Thanks. I remove the "-msse2" in the file "Makefile". 
![image](https://cloud.githubusercontent.com/assets/5807893/9697315/538c4012-53bb-11e5-873c-49d5cc61ab91.png)

Then enter "make". It also shows the following errors;
![image](https://cloud.githubusercontent.com/assets/5807893/9697316/82e6721a-53bb-11e5-89a4-b98649ee99bb.png)

**Comment by tqchen** [comment]
you want to remove the -msse in all subsequent Makefiles

**Comment by tomdyq** [comment]
I search the file “Makefile” but I do not find any other "msse2".

**Comment by tqchen** [comment]
could be in some .mk files

**Comment by tomdyq** [comment]
The problem is solved. Thank you very much!
