### ISSUE TITLE
Continue training with XGBClassifier() 

### ISSUE THREAD

**Issue by roycechan** [dmlc/xgboost#4691]
I trained a XGBClassifier for 10 rounds. Is it possible to continue training later?

Here's how I saved the model after 10 rounds:
`
joblib.dump(bst, 'model/xgbmodel.pkl.z')
`

When i try to train it subsequently

`
bst2 = joblib.load('model/xgbmodel.pkl.z')
bst2.fit(X_train,y_train,
        eval_set=[(X_train, y_train), (X_test, y_test)],
        eval_metric='mlogloss',
        early_stopping_rounds = 5,
        verbose=True,
        xgb_model = bst2)
`

I get this error: 

/opt/anaconda3/lib/python3.7/site-packages/xgboost/training.py in _train_internal(params, dtrain, num_boost_round, evals, obj, feval, xgb_model, callbacks)
     36     if xgb_model is not None:
     37         if not isinstance(xgb_model, STRING_TYPES):
38             xgb_model = xgb_model.save_raw()
     39         bst = Booster(params, [dtrain] + [d[0] for d in evals], model_file=xgb_model)
     40         nboost = len(bst.get_dump())

AttributeError: 'XGBClassifier' object has no attribute save_raw

**Comment by hcho3** [comment]
Try:
```python
bst2 = joblib.load('model/xgbmodel.pkl.z')
bst2.fit(X_train,y_train, eval_set=[(X_train, y_train), (X_test, y_test)], eval_metric='mlogloss', early_stopping_rounds = 5, verbose=True, xgb_model = bst2.get_booster())
```

**Comment by kaixinbuyu** [comment]
@hcho3 did you test that continue training with GPU?
I have google all the internet but found no example about continue training with GPU.
Is continue training with GPU impossible?

I tried to continue train with old model by "xgb_model=xx".
1.With CPU params(hist), continue training runs ok. [as the test script in the test package.]
2.But with GPU params(gpu_hist),It crashed with error "Check failed: devices.Size() != 0 (0 vs. 0) :"
