### ISSUE TITLE
Dose XGBRanker  objective=‘rank:pairwise’.  consider the NDCG in loss?

### ISSUE THREAD

**Issue by fly12357** [dmlc/xgboost#4694]
Can I use  XGBRanker objective=‘rank:pairwise’ for a ranking problem without considering the ndcg? Just like Ranknet.

**Comment by trivialfis** [comment]
XGBoost implements `LambdaMart`, NDCG is only one of the measurements, you can switch to others supported in XGBoost like map or pairwise.  But I think NDCG will return the best result.

**Comment by fly12357** [comment]
Thanks for your reply. But, I still confused about the "pairwise: method.   

In "From RankNet to LambdaRank to LambdaMART: An Overview" the lambda gradient is:
![image](https://user-images.githubusercontent.com/40494145/61676252-d29aba80-ad2d-11e9-831b-1fd55b08dd62.png)

According to the above formulation, I guess 

The menthod "rank:ndcg" implemented in the Xgboost means the delta Z is the "NDCG" measurement.
In menthod "rank:map" the delta Z is the "MAP" measurement.

I am not sure about the what the delta Z means in the "rank: pairwise".

**Comment by fly12357** [comment]
Thanks for your reply. But, I still confused about the "pairwise: method.

In "From RankNet to LambdaRank to LambdaMART: An Overview" the lambda gradient is:

![image](https://user-images.githubusercontent.com/40494145/61676661-691bab80-ad2f-11e9-9805-7f9b52845b6b.png)

According to the above formulation, I guess

The menthod "rank:ndcg" implemented in the Xgboost means the delta Z is the "NDCG" measurement.
In menthod "rank:map" the delta Z is the "MAP" measurement.

I am not sure about the what the delta Z means in the "rank: pairwise".

**Comment by trivialfis** [comment]
@fly12357 There is not `Z` in pairwise.  Should be just 1.

**Comment by trivialfis** [comment]
Actually that sounds weird.  I don't fully understand the ranking implementation yet.  Should work on it in the future after sorting out existing PRs.  Feel free to look into the corresponding implementation.

**Comment by fly12357** [comment]
> Actually that sounds weird. I don't fully understand the ranking implementation yet. Should work on it in the future after sorting out existing PRs. Feel free to look into the corresponding implementation.

Thanks for your reply. I agree with your point that in rank:pairwise there is no z (It is a simple GBrank).  And I found that  the problems "Selection of objective "rank:ndcg" results in lower NDCG than "rank:pairwise" #4177 has discussed this issue.

**Comment by trivialfis** [comment]
Keep this tracked in #4177
