### ISSUE TITLE
question about deprecation of passing lists to DMatrix

### ISSUE THREAD

**Issue by Ying456123** [dmlc/xgboost#4695]
@scwilkinson @trivialfis
I saw the pr: https://github.com/dmlc/xgboost/pull/3970 . Just want to know why this code will bring the 10% prediction difference? Could you provide the failed case if possible so I can add to my testcase?
```
try: 
     csr = scipy.sparse.csr_matrix(data) 
     self._init_from_csr(csr) 
 except: 
```
Because an application I maintained will deal with user's input record, and then  use a unified format to construct DMatrix with this input record. I've always been feeding the input record into a list, and then feed this list to DMatrix. Now I need to change a format, **is it ok  if I change it to numpy.ndarray?** Waiting for your reply, and  thanks a lot.

**Comment by trivialfis** [comment]
It's OK to change it to numpy.ndarray.

**Comment by trivialfis** [comment]
@Ying456123
