### ISSUE TITLE
Parallel xgboost slows down when using more than 8 threads

### ISSUE THREAD

**Issue by snawara** [dmlc/xgboost#4703]
I did some benchmarking with parallel xgboost on [this kaggle dataset](https://www.kaggle.com/c/ieee-fraud-detection/data)  (+ feature engineering and data split resulting in 676 features and ~500k rows in the train data) using an AMD 2990wx (32c/64t) cpu and the following system:

```
R version 3.5.2 (2018-12-20)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Linux Mint 19.1

Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

xgboost_0.71.2
```
Here are the xgboost parameters:

```
list(max.depth         = 12,  
     eta               = 0.01,  
     min_child_weight  = .5,  
     subsample         = 1,  
     colsample_bytree  = 1,  
     colsample_bylevel = 1,  
     lambda            = 0.1,  
     alpha             = 0.1,  
     gamma             = 0.1,  
     max_delta_step    = 0,  
     scale_pos_weight  = 1/20,
     num_parallel_tree = 1,
     booster           = "gbtree",
     tree_method       = "hist",
     rate_drop         = 0.1, 
     skip_drop         = 0.5,
     max_bin           = 256/4,
     grow_policy       = "depthwise")

```

Here is how long it took to do 100 rounds for various values of nthread:

```
 nthread  t_elapsed
 1        226.036  
 2        136.685  
 3        106.568  
 4        90.421   
 8        63.47    
 16       66.153   
 24       79.797   
 32       102.543  
 48       147.152 
```
Can anyone explain why xgboost is slowing down after 8 threads?

**Comment by snawara** [comment]
I ran this again with tree_method = "exact". Now it plateaued at ~16 threads:

```
nthread t_elapsed
 1       3107.099
 2       1989.971
 4       1441.895
 8       1246.827
16       1081.080
24        954.541
32       1048.985
48       1050.347
```
![parBench](https://user-images.githubusercontent.com/21176904/61832881-432dfe00-ae38-11e9-8caf-6257f06157e1.png)

Any ideas?

**Comment by hcho3** [comment]
I notice that you are using 0.71.2 version of XGBoost. Can you try again with 0.82.1 ?

**Comment by snawara** [comment]
> I notice that you are using 0.71.2 version of XGBoost. Can you try again with 0.82.1 ?

Now I ran it on R 3.6.1 and xgboost_0.82.1:
```

nthread t_elapsed
1       125.951  
2       76.494   
4       48.612   
8       30.855   
16      23.822   
24      25.655   
32      29.346   
48      45.975   
```
It looks like 2x faster with the new version, great job! But I still see the same strange pattern:

![parBench](https://user-images.githubusercontent.com/21176904/61835636-3e6e4780-ae42-11e9-8d5d-7e751e940aa4.png)

**Comment by hcho3** [comment]
We've been working to improve the performance on multi-core CPUs. Expect additional improvements when 0.90 is uploaded to CRAN. Alternatively, you can compile XGBoost from the latest source and get improvements now.
