### ISSUE TITLE
parameter gamma doesn't work at all when using gpu_hist

### ISSUE THREAD

**Issue by panranyang** [dmlc/xgboost#4707]
I use "hist" and "gpu_hist" to train my model. When gamma=15 for both, "hist" return a model whose sum of features' fscore is 0, which means all nodes were pruned.While "gpu_hist" return a normal model. Then I use gamma=0 for "hist", the result becomes normal. Though I use gamma=1e4 for "gpu_hist", the result is still just like gamma=0.

I  just wonder if "gamma" does not work with "gpu_hist" or if I use wrong parameter when using "gpu_hist"

GPU: GTX1080
xgboost version: 0.82
GPU driver version:396.37
CUDA version: 9.2.148

**Comment by RAMitchell** [comment]
It doesn't currently because it doesn't use the pruner. This can possibly be fixed.

**Comment by panranyang** [comment]
Thank you!
