### ISSUE TITLE
Install R package from Github using devtools

### ISSUE THREAD

**Issue by pommedeterresautee** [dmlc/xgboost#4710]
Documentation still says that it is not possible to use `devtools` to install XGBoost because of submodules.
It should not be the case anymore, as devtools is now relying on `remotes` package for Github installation, and `remotes` officially supports submodules.
They even cite XGBoost installation in their readme.

Unfortunately... there is a bug on `remotes` reported there https://github.com/r-lib/remotes/issues/233 which basically makes remotes not able to see `.gitmodules` file when the R package is in a subfolder of the repo.
And simple fix doesn't seem to work (the issue above is their oldest opened one, making me think it's a tricky bug as `remotes` is a major package for the R community and well maintained).

Installing XGBoost from `devtools` would be a very nice feature for new comers experiencing a bug already fixed on master, or wanting to use a new feature.

I am wondering if there are things we can do to workaround remote limitation?

**Comment by hcho3** [comment]
The submodules are still presenting problems, since r-lib/remotes always fetches the HEAD of every submodule, even though XGBoost refers to a specific commit of each submodule. This causes build failure.
