### ISSUE TITLE
Imbalanced Dataset - Documentation Ambiguity

### ISSUE THREAD

**Issue by keshavramaswamy** [dmlc/xgboost#4711]
Hi, 

I have a suggestion to make (happy to do a PR) based on my understanding of the probability output given by xgBoost.

(https://xgboost.readthedocs.io/en/latest/tutorials/param_tuning.html#handle-imbalanced-dataset) has a section for how to use tune the parameters when we require the 'right probabilities' in imbalanced dataset problems. 

I feel that the documentation should also add a caveat that using xgBoost (atleast binary:logistic as the objective) does not necessarily guarantee that the outputs would be actually 'true probabilities' and that calibration may be required.

Refer this issue : https://github.com/dmlc/xgboost/issues/2312#issuecomment-303421042_
"..This documentation statement does not give a definitive guarantee that the outputs would be true probabilities. And there's no explicit calibration in xgboost. Any post-processing you would deem needed is up to you...." 

I feel that unless we add in explicitly that xgBoost may not produce calibrated probabilities, the section on parameter tuning with the heading,'If you care about predicting the right probability' can indicate to users that xgBoost can indeed give the right probabilities (especially when they are not aware of the concept of probability calibration and the need to use calibration plots)

I am willing to submit a PR if this makes sense. 

Thanks for the wonderful library and the ongoing development!

**Comment by hcho3** [comment]
Yes, feel free to submit a pull request. We will review it.
