### ISSUE TITLE
XGBoost4J-Spark crashes with imbalanced data

### ISSUE THREAD

**Issue by sramirez** [dmlc/xgboost#4713]
Hi!

I'm using XGBoost4j-Spark in its version 0.90. When fitting a model with a binary highly imbalanced dataset with xgboost I got the following error:

2019/07/22 14:53:21:699 ERROR ml.dmlc.xgboost4j.java.RabitTracker: Uncaught exception thrown by worker:
    at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$2$$anon$1.run(XGBoost.scala:452)

After some research, I found it is provoked by a lack of instances from the minority class in one or more spark partitions. In our case, we launched the cluster with 120 cores, and partitioned the dataset into the same number. Right now, we check this assertion for each subset of data and raise an exception whenever we found some partition lacks some class information, but obviously it is not a plausible solution for our task.

Any help or suggestion will be more than welcomed!

**Comment by sperlingxx** [comment]
Hi @sramirez , this problem has been fixed by PR #4645 .
