### ISSUE TITLE
[jvm-packages] train model on spark is unstable

### ISSUE THREAD

**Issue by merleyc** [dmlc/xgboost#4728]
Hi,
I want to understand the reason I get different models, consequently different AUC values, each time I run xgboost (v. 0.90) on spark.
I am aware about these two issues but didn't reply my question: [3959](https://github.com/dmlc/xgboost/issues/3959) and [2573](https://github.com/dmlc/xgboost/issues/2573) .
If I understood correctly, the approximate algorithm to split points use quantiles. So it sorts the the values of each feature separately and divide them in x-quantiles. Since I am always given the same data, I expected to create the same model since the sort phase should be the same considering I don't expect to have randomness from spark side.

My code:
```
from sparkxgb import XGBoostClassifier
df = spark.read.format('parquet').load('hdfs://file.parquet')
(trainingData, testData) = df.randomSplit([0.9, 0.1], seed = RANDOM_SEED)
# to remove any possible randomness from spark side:
trainingData = trainingData.coalesce(executors_per_node*nodes*cores_per_executor)
trainingData.cache() # Data contains 546040147 rows

executors_per_node = 14
nodes = cores_per_executor = 4

xgboost = XGBoostClassifier(
	featuresCol="features",
	labelCol="label", 
	numRound=100,
	maxDepth=8,
	maxLeaves=256,
	alpha=0.9,
	eta=0.1,
	gamma=0.1,
	subsample=1.0,
	reg_lambda=1.0,
	scalePosWeight=2.0,
	minChildWeight=30.0,
	treeMethod='hist',
	objective='reg:squarederror',
	growPolicy='lossguide',
	numWorkers=executors_per_node*nodes*cores_per_executor,
	nthread=1
)

model = xgboost.fit(trainingData)
```

May someone please help explaining the reason of this model randomness please?
Thanks a lot!

**Comment by hcho3** [comment]
@merleyc 

> the sort phase should be the same considering I don't expect to have randomness from spark side

This is not true. See https://discuss.xgboost.ai/t/jvm-packages-is-scala-spark-xgboost-0-81-model-training-reproducible/623/3?u=hcho3.

**Comment by merleyc** [comment]
Hi @hcho3,
Thanks for sharing this link!
From your link:
> In distributed Spark, this is not necessarily true, since we don’t know how the data gets coalesced, reduced, collected, etc. Spark will manage a lot of such data movements, and we cannot control them. Please keep in mind that addition is not associative in floating-point arithmetic: a + (b+c) is not necessarily equal to (a + b) + c.

I believe I am treating in my code the case where the data gets coalesced but I am assuming once I call xgboost.fit() the data won't be changed by spark. This is the reason I thought the randomness came from Xgboost and not spark. However I'm new in spark so I am probably wrong. Will investigate further but please feel free to direct me to the right path.
I still need to understand where it is the difference that is making my models different. If I run 3times, I got different models and different AUC values (0.7820199, 0.7778367, 0.7781070).

For the ones are reading this post, I also found [this affirmative](https://github.com/dmlc/xgboost/blob/master/doc/faq.rst) "This could happen, due to non-determinism in floating point summation order and multi-threading. Though the general accuracy will usually remain the same."

Thanks!
