### ISSUE TITLE
Automatically find available GPUs

### ISSUE THREAD

**Issue by RAMitchell** [dmlc/xgboost#4735]
As discussed in #4693, there is a desire to automatically find available GPUs in a distributed setting. This significantly improves usability of our distributed GPU solution. In the case of the Python dask demo it removes the dependency on the third-party library GPUtil. It also provides a way to run on Spark until GPU scheduling arrives in 3.0 (??).

The implementation of #4693 has a couple of problems. It depends on the user enabling exclusive process via the nvidia-smi command line utility, otherwise multiple processes are likely to select the same device. It also is in conflict with our deprecated single machine multi-GPU support, which expects "gpu_id" to be the same for each thread.

I propose the following:
- Change the gpu_id parameter to accept a string with default value "auto", indicating that xgboost should find a device with no running process. Otherwise accept a device index.
- Statically link xgboost with nvml and use a function like ([nvmlDeviceGetComputeRunningProcesses](https://docs.nvidia.com/deploy/nvml-api/group__nvmlDeviceQueries.html#group__nvmlDeviceQueries_1g46ceaea624d5c96e098e03c453419d68)) to find available GPUs

The above cannot happen until we deprecate the "n_gpus" parameter (#4531). We expect to do this sometime in September.

Also consider that we will introduce a dependency on nvml. I don't expect this to be a burden because nvml is distributed with the cuda toolkit, so a user compiling with cuda is guaranteed to have this. The static library size is 53kb on my machine, which is trivial given that our binary is now more than 100mb.

@tgravescs  @wbo4958 @trivialfis @rongou

**Comment by trivialfis** [comment]
How many number of versions should we keep the deprecated code?  Currently we don't have any release yet.

**Comment by RAMitchell** [comment]
Given that the next release may be 1.0, breaking changes will be expected anyway.

**Comment by trivialfis** [comment]
@RAMitchell Can we remove the code right after 1.0?  It's just natural that we have at least one release for staging, which also give us time to make proper cleanup.  Those are not small changes ...

**Comment by RAMitchell** [comment]
I think it will take too long if we wait until after 1.0. We have a few people working on the code base now, it will make all of our lives easier the sooner it gets done.

**Comment by tgravescs** [comment]
I haven't looked much at nvml, it looks like nvmlDeviceGetComputeRunningProcesses will return the information about what processes are using what GPUs, but how do you guarantee 2 process won't still try to use the same GPU?  ie, I have 2 processes that both at the same time run nvmlDeviceGetComputeRunningProcesses, it returns say GPU id 2 is free on both of them, then both start to use it.  I'm assuming NVML doesn't show a process until it allocates memory or runs a kernel.

**Comment by rongou** [comment]
Also this only works if every process uses nvml to check the availability. If someone launches, say, a tensorflow job, it'll gladly take over all the gpus, even if xgboost is already running on them.

I think proper gpu allocation needs to happen at the cluster manager level. Anything we do at the individual process level is only going to be a hack.

**Comment by RAMitchell** [comment]
> but how do you guarantee 2 process won't still try to use the same GPU? ie, I have 2 processes that both at the same time run nvmlDeviceGetComputeRunningProcesses, it returns say GPU id 2 is free on both of them, then both start to use it

nvml is actually able to set exclusive process, but only with root permissions, making this impractical.

We could get around this using rabit for synchronisation so each process gets a unique device in each iteration. This could even be done without nvml but we would have no knowledge of some compute process outside of the current xgboost was running (such as another xgboost or tensorflow). 


>Also this only works if every process uses nvml to check the availability. If someone launches, say, a tensorflow job, it'll gladly take over all the gpus, even if xgboost is already running on them.

> I think proper gpu allocation needs to happen at the cluster manager level. Anything we do at the individual process level is only going to be a hack.

Agreed that proper management should be deferred to the cluster.

I think this is convenience feature that provides benefits in common cases, where the cluster is not shared, xgboost is the only running application and complex scheduling is not required. The question is if it's worth us implementing and supporting this. It certainly simplifies the dask demo.

Maybe the way to go is just define "gpu_id":"auto" to assign each process a unique GPU without regard to what else is running and document this behaviour?

**Comment by rongou** [comment]
What happens if you launch 4 workers but only find 3 GPUs? Just crash?

If we only launch one xgboost job at a time, we can use the Rabit rank to derive the gpu id, as I mentioned before:
```python
GPUS_PER_NODE = 4
gpu_id = xgb.rabit.get_rank() % GPUS_PER_NODE
```
The number of gpus per node can also be a parameter the user sets.

We basically have a spectrum of options with different assumptions, from
* one job at a time, exclusive access -> get gpu ids by rank

to

* assume nothing -> rely on cluster manager to allocate gpus

and pretty everything in between.

I guess the question is really what assumptions we want to make and what the most common usage scenarios are.

**Comment by RAMitchell** [comment]
> What happens if you launch 4 workers but only find 3 GPUs? Just crash?

Yep, just crash with an informative error. The power user may of course manually specify the device indices for each process, automatic GPU discovery is not intended to cover all use cases.

GPU selection would happen internally in C++ code rather than in python, and I do not want a parameter for number of GPUs per node. We will make the assumption that if there are 4 xgboost processes launched on a node and GPU algorithms are used, there should be 4 GPUs available.

**Comment by rongou** [comment]
Actually we can get the number of gpus via `AllVisible()`. I'm not saying we do it in python, but the approach is the same:
```cpp
gpu_id = rabit::GetRank() % GPUSet::AllVisible().Size()
```
assuming the cluster is homogeneous.

**Comment by wbo4958** [comment]
Seems there is a case that gpu_id = rabit::GetRank() % GPUSet::AllVisible().Size() can't handle.

for example, Two PCs, each has two GPUs,
we launch two spark workers in each PC. Now, just submit 4 xgboost workers

there may be a situation, the two workers in same PC can get rank o and 2.

So in this case, seems same gpu will be allocated.

**Comment by rongou** [comment]
You are right. I was thinking more for the mpi case where the ranks are contiguous on each node. There is no such guarantee for Spark (probably not Dask either). We need to use rabit allreduce to figure out the device assignment, maybe something like this:

for each worker:
  allocate array a of size rabit::GetWorldSize()
  set all values to 0
  a[rabit::GetRank()] = hash(hostname())
  allreduce(a, sum)
  gpu_id = count # of entries in a before my rank that has the same host hash

**Comment by RAMitchell** [comment]
I think we did something similar in order to set up the nccl communication group. Something like what @rongou described should be fine, just use rabit communication to discover the arrangement of GPUs and workers so that each worker has a unique GPU.

**Comment by tgravescs** [comment]
So just to be clear this solution only works on non-shared cluster, correct? ie if you have 2 xgboost apps on the same nodes this wouldn't work.

**Comment by RAMitchell** [comment]
Correct, I think it is out of scope for us to deal with this case.

**Comment by rongou** [comment]
I guess it's only guaranteed to work in a non-shared cluster. In a shared cluster, if a second worker gets allocated to the same GPU, it may run out of GPU memory and crash, then Spark would schedule another task (probably on the same node?), which would crash again. This continues until either the first job finishes, or Spark fails the whole job. Since Rabit can recover from node failures, perhaps it'd work out in the end.

**Comment by trivialfis** [comment]
I want to get this resolved first for dask.  May I ask is there any one working on it?

**Comment by tgravescs** [comment]
What are the requirements for dask?  Does dask assume it is the only application on the node?

**Comment by trivialfis** [comment]
@tgravescs From its document, dask is not aware of GPUs.  Pretty similar to the current status of Spark I think.

**Comment by RAMitchell** [comment]
@trivialfis I'm not working on this, what's your proposal?

**Comment by tgravescs** [comment]
that makes sense for dask, the main question as to whether this will work is if you can guarantee that dask is the only application using the GPU's on a host. And possibly only 1 "Worker".  I don't know enough about Dask to know if it has "workers" at all.

**Comment by trivialfis** [comment]
> Correct, I think it is out of scope for us to deal with this case.

I think for spark side, we will wait for Spark 3.0.  On dask side, `dask_cuda` is the solution.
