### ISSUE TITLE
Multi Dimension Output Regression Available?

### ISSUE THREAD

**Issue by JJumSSu** [dmlc/xgboost#4740]
Hi, I'm currently trying to do the task of multiple output regression where my target y has dimensions of more than 1. Is there a feature implemented that I can use to do multiple 
output regression?

If not, how can I modify the pre-existing code to do multi-dimension output regression? I realized that there is a custom objective function which I can define and use to split the trees by multiple dimension criterion. Can I use this feature to fit one model for multi-dimension output? 

I noticed that I can use SKLEARN's "multioutputregressor" function, but this isn't what I need.(since it breaks down the output into a single dimension and fits seperate models accordingly)

Any ideas?

**Comment by trivialfis** [comment]
Currently we don't support multiple outputs.  Even we were to implement the feature, I think sklearn's method will be adopted.

**Comment by JJumSSu** [comment]
Oh I see, adopting the sklearn's method means that the multi-output will not be dependent on each other just like the "multioutputregressor" wrapper?

**Comment by JJumSSu** [comment]
I was wondering, is it because of some other theoretical reason that it is difficult to implement the multi output regression function on XGBOOST just like that of a RandomForestRegressor in Sklearn? It's just out of my curiosity. Thank you for your reply @trivialfis

**Comment by trivialfis** [comment]
@JJumSSu I'm not sure.  Multi output regression is certainly something interesting, but I can't prioritize it for now.  If you have some ideas on how to do it I would be happy to help.

**Comment by JJumSSu** [comment]
Okay, Thanks for your reply.
