### ISSUE TITLE
GPU does no support objective `reg:squarederror`

### ISSUE THREAD

**Issue by michal-demecki-profil-software** [dmlc/xgboost#4746]
Simple Regression on freshly compiled master with GPU support does not work properly.

> XGBoostError: [13:16:33] /workspace/src/objective/objective.cc:23: Unknown objective function reg:squarederror

```
xgboost.__version__
Out[1]: '1.0.0-SNAPSHOT'
```
CUDA version: 
`Cuda compilation tools, release 10.0, V10.0.130`

Reproduction code:
```
model = xgboost.XGBRegressor()
model.fit(
    X_train, y_train,
    eval_set=[(X_test, y_test)],
    eval_metric=['rmse'], 
    verbose=1)
```

**Comment by trivialfis** [comment]
@michal-demecki-profil-software How did you compile XGBoost, also how did you install it?

Running on 2a4df8e29f7b004cc2e991e7c0052b003bd3413f

I can't reproduce.

```
import numpy as np
import xgboost as xgb

x = np.random.rand(100, 100).astype(np.float32)
y = np.random.rand(100).astype(np.float32)

x_e = np.random.rand(10, 100).astype(np.float32)
y_e = np.random.rand(10).astype(np.float32)

model = xgb.XGBRegressor()
model.fit(x, y, eval_set=[(x_e, y_e)], eval_metric=['rmse'])
```

**Comment by trivialfis** [comment]
@michal-demecki-profil-software Also could you try CUDA 10.1 or 9.2.  I think there was some bugs in 10.0.
