### ISSUE TITLE
CPU predictor crashes when training with data stored in GPU memory. 

### ISSUE THREAD

**Issue by firestarman** [dmlc/xgboost#4751]
We are working on the GPU training pipeline, to load data into GPU memory and choose `gpu_hist` to run the training locally, non-distributed.

After some basic investigation, found that the first `PredictRaw` in `Learner` will use `cpu_predcitor`, then it crashes at line 71 in file https://github.com/dmlc/xgboost/blob/master/src/predictor/cpu_predictor.cc 

And the crash happens only when parallel is enabled. Error message just before crash is followed

> double free or corruption (out)
double free or corruption (!prev)
double free or corruption (!prev)

What' more interesting is it can pass after even only adding a log print as below,
` 69         }`
 `70         for (int k = 0; k < kUnroll; ++k) {`
 **`71           LOG(WARNING) << "debug == tid = " << tid;`**
 `72           inst[k] = batch[i + k];`
` 73         }`

I think running parallel here may be too fast for GPU -> CPU case, since it may need a little time to copy the batch data from GPU to CPU memory, what's more the sync is lazy per code below from file https://github.com/dmlc/xgboost/blob/master/src/common/host_device_vector.cu . 
`  const std::vector<T>& ConstHostVector() {`
`    LazySyncHost(GPUAccess::kRead);`
`    return data_h_;`
`  }`

Any idea to fix it ? or to fix why cpu_predictor is used when doing the first `PredictRaw` even specifying the tree method as 'gpu_hist'.

**Comment by trivialfis** [comment]
@firestarman There's similar feedback recently.  I think they are working on a fix.

**Comment by trivialfis** [comment]
Seems I need to look into it later.

**Comment by trivialfis** [comment]
Partially fixed in #4745 .  Still need to address choosing predictor.

**Comment by trivialfis** [comment]
@rongou @RAMitchell With `n_gpus` being removed, I'm just gonna add a mutex lock here to prevent racing.
