### ISSUE TITLE
AttributeError: module 'xgboost' has no attribute 'dask'

### ISSUE THREAD

**Issue by Chertoganov** [dmlc/xgboost#4756]
File "dask_simple_demo.py", line 68, in <module>
    main()
  File "dask_simple_demo.py", line 56, in main
    models = xgb.dask.run(client, train, X, y)
AttributeError: module 'xgboost' has no attribute 'dask'

**Comment by RAMitchell** [comment]
Please check you do not have an older xgboost version installed via conda or pip.

**Comment by Chertoganov** [comment]
I uninstalled xgboost and installed it again and then it happend again
python dask_gpu_demo.py
Traceback (most recent call last):
  File "dask_gpu_demo.py", line 42, in <module>
    main()
  File "dask_gpu_demo.py", line 38, in main
    xgb.dask.run(client, train, X, y, available_devices)
AttributeError: module 'xgboost' has no attribute 'dask'

**Comment by Chertoganov** [comment]
:(

**Comment by RAMitchell** [comment]
I cannot reproduce this on the latest master xgboost. You will have to do some python debugging on your side, the most likely issue is with the installation.

**Comment by trivialfis** [comment]
Which version of xgb are you using?

**Comment by Chertoganov** [comment]
>>> import xgboost as xgb
>>> xgb.__version__
'0.90'

**Comment by Chertoganov** [comment]
>>> import xgboost as xgb
>>> xgb.__version__
'0.90'

пн, 12 авг. 2019 г. в 05:26, Jiaming Yuan <notifications@github.com>:

**Comment by hcho3** [comment]
The Dask demo is not compatible with 0.90 version, since Dask integration was added after the 0.90 release. Can you compile XGBoost from source?
