### ISSUE TITLE
reload model with predictor=gpu_predictor cause error "gpu_predictor.cu:387: Check failed: devices.Size() != 0 (0 vs. 0) : "

### ISSUE THREAD

**Issue by kaixinbuyu** [dmlc/xgboost#4758]
1.reload model with predictor=**cpu_predictor**,  "xgb_model=bst_last_model". no error.

2.reload model with predictor=**gpu_predictor**,  "xgb_model=bst_last_model". cause error:
 "gpu_predictor.cu:387: Check failed: devices.Size() != 0 (0 vs. 0) : "

(the training process works ok.)

`Traceback (most recent call last):
  File "/home/go/workspace/workspace_go/src/yunteng/dataeen/client/ml/main_train_xgboost.py", line 1124, in <module>
    main()
  File "/home/go/workspace/workspace_go/src/yunteng/dataeen/client/ml/main_train_xgboost.py", line 1114, in main
    predict()
  File "/home/go/workspace/workspace_go/src/yunteng/dataeen/client/ml/main_train_xgboost.py", line 410, in predict
    pred = model.predict(X_test)
  File "/home/go/software/anaconda3/lib/python3.7/site-packages/xgboost-1.0.0_SNAPSHOT-py3.7.egg/xgboost/core.py", line 1297, in predict
    ctypes.byref(preds)))
  File "/home/go/software/anaconda3/lib/python3.7/site-packages/xgboost-1.0.0_SNAPSHOT-py3.7.egg/xgboost/core.py", line 176, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: [21:54:32] /home/go/software/xgboost/xgboost/src/predictor/gpu_predictor.cu:387: Check failed: devices.Size() != 0 (0 vs. 0) : 
Stack trace:
  [bt] (0) /home/go/software/anaconda3/lib/python3.7/site-packages/xgboost-1.0.0_SNAPSHOT-py3.7.egg/xgboost/./lib/libxgboost.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x32) [0x7ff5cf2d6ee2]
  [bt] (1) /home/go/software/anaconda3/lib/python3.7/site-packages/xgboost-1.0.0_SNAPSHOT-py3.7.egg/xgboost/./lib/libxgboost.so(xgboost::predictor::GPUPredictor::PredictBatch(xgboost::DMatrix*, xgboost::HostDeviceVector<float>*, xgboost::gbm::GBTreeModel const&, int, unsigned int)+0x552) [0x7ff5cf5335d2]
  [bt] (2) /home/go/software/anaconda3/lib/python3.7/site-packages/xgboost-1.0.0_SNAPSHOT-py3.7.egg/xgboost/./lib/libxgboost.so(xgboost::gbm::GBTree::PredictBatch(xgboost::DMatrix*, xgboost::HostDeviceVector<float>*, unsigned int)+0x9a) [0x7ff5cf366e3a]
  [bt] (3) /home/go/software/anaconda3/lib/python3.7/site-packages/xgboost-1.0.0_SNAPSHOT-py3.7.egg/xgboost/./lib/libxgboost.so(xgboost::LearnerImpl::Predict(xgboost::DMatrix*, bool, xgboost::HostDeviceVector<float>*, unsigned int, bool, bool, bool, bool)+0xe4) [0x7ff5cf37b534]
  [bt] (4) /home/go/software/anaconda3/lib/python3.7/site-packages/xgboost-1.0.0_SNAPSHOT-py3.7.egg/xgboost/./lib/libxgboost.so(XGBoosterPredict+0x124) [0x7ff5cf2c9e24]
  [bt] (5) /home/go/software/anaconda3/lib/python3.7/lib-dynload/../../libffi.so.6(ffi_call_unix64+0x4c) [0x7ff5fc541ec0]
  [bt] (6) /home/go/software/anaconda3/lib/python3.7/lib-dynload/../../libffi.so.6(ffi_call+0x22d) [0x7ff5fc54187d]
  [bt] (7) /home/go/software/anaconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7ff5fc8eff7e]
  [bt] (8) /home/go/software/anaconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-x86_64-linux-gnu.so(+0x139b4) [0x7ff5fc8f09b4]`

Is GPU memory not released,or GPU handler locked caused the error?
So I added model.__del()__,gc.collect(),not work as well.

**Comment by trivialfis** [comment]
Will take a look.

**Comment by trivialfis** [comment]
@kaixinbuyu Do you still have a reproducible script?
