### ISSUE TITLE
安装xgboost，make时报错

### ISSUE THREAD

**Issue by 1448514557** [dmlc/xgboost#4766]
src/tree/tree_model.cc: In constructor ‘xgboost::GraphvizGenerator::GraphvizGenerator(const xgboost::FeatureMap&, const string&, bool’:
src/tree/tree_model.cc:465:55: error: invalid initialization of non-const reference of type ‘std::stringstream& {aka std::basic_stringstream<char>&}’ from an rvalue of type ‘<brace-enclosed initializer list>’
       TreeGenerator(fmap, with_stats), ss_{SuperT::ss_} {
                                                       ^
make: *** [build/tree/tree_model.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by trivialfis** [comment]
Use cmake + gcc>=5.3 please.

**Comment by 1448514557** [comment]
ok ，thanks
