### ISSUE TITLE
Calculation by following the dump.txt literally does not correspond to the code output

### ISSUE THREAD

**Issue by Traeyee** [dmlc/xgboost#4770]
I try to understand the dump.txt, so I calculated by my hands then compared the result to the code output. Here's the code:

```
import numpy as np
import xgboost as xgb

arr = np.array([[1, None, 2], [2, 3, 4], [None, 0, 1]])
labels = np.array([1, 2, 8])
print(arr)
dm = xgb.DMatrix(arr, labels)
params = {'max_depth': 1, 'eta': 0.1, 'gamma': 0.0, 'objective': 'reg:linear', 'eval_metric': 'rmse'}
bst = xgb.train(params, dm, num_boost_round=2)
bst.dump_model("dump.txt")
rst = bst.predict(xgb.DMatrix(arr))
for score in rst:
    print(score)
```

the code output:
```
0.6288889
0.6288889
1.23125
```

the dump.txt:
```
booster[0]:
0:[f0<4.00000095] yes=1,no=2,missing=2
        1:leaf=0.0666666701
        2:leaf=0.375
booster[1]:
0:[f0<4.00000095] yes=1,no=2,missing=2
        1:leaf=0.0622222237
        2:leaf=0.356250018
```

Just take the 1st sample as the example, [1, None, 2]->1, code ouputs 0.6288889. But if I follow the dump.txt, for booster[0], it was 1:leaf=0.0666666701, then for booster[1], it was 1:leaf=0.0622222237, so final result will be 0.0666666701 + 0.0622222237 = 0.12888889380000002, not 0.6288889!
So is it right to sum all the booster leaf output to make the result? If not, it contradicted my understanding to xgboost

**Comment by trivialfis** [comment]
@Traeyee Which version are you using?

**Comment by Traeyee** [comment]
> @Traeyee Which version are you using?

0.82

**Comment by shenshanlaoma** [comment]
you should transform score to probalility.
https://github.com/dmlc/xgboost/issues/4682#issuecomment-514725667

**Comment by hcho3** [comment]
Take a look at https://discuss.xgboost.ai/t/xgboost-learning-to-rank-model-to-predictions-core-function/93/2?u=hcho3. You should add 0.5 to the sum of leaf outputs.

**Comment by hcho3** [comment]
@shenshanlaoma The OP is performing regression task, so score is not probability.

**Comment by trivialfis** [comment]
Oops.  Missed that. ;-0
