### ISSUE TITLE
Kernel dies when using GPU_hist

### ISSUE THREAD

**Issue by Thiyagu07** [dmlc/xgboost#4772]
Thanks for participating in the XGBoost community! We use https://discuss.xgboost.ai for any general usage questions and discussions. The issue tracker is used for actionable items such as feature proposals discussion, roadmaps, and bug tracking.  You are always welcomed to post on the forum first :)

Issues that are inactive for a period of time may get closed. We adopt this policy so that we won't lose track of actionable issues that may fall at the bottom of the pile. Feel free to reopen a new one if you feel there is an additional problem that needs attention when an old one gets closed.

For bug reports, to help the developer act on the issues, please include a description of your environment, preferably a minimum script to reproduce the problem.

For feature proposals, list clear, small actionable items so we can track the progress of the change.

**Comment by Thiyagu07** [comment]
When I tried to use the GPU using the tree_method parameter, the Kernel always dies. I was able to run the code using the updater='grow_gpu'. However, I cannot use the Gamma parameter when I use the updater parameter

**Comment by trivialfis** [comment]
Could you provide your xgboost version and a reproducible example?  Also gamma is not supported by GPU.

**Comment by Thiyagu07** [comment]
I have attached the code for your reference. The train samples, I just used 200 rows of data and even then it failed.

I see the following error in the terminal as well
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  parallel_for failed: out of memory



`### Copying the best values from the XGBOOST_without_timesplit hyperopt run of 100

params={'colsample_bytree': 0.7340260740827114,
 'gamma': 0.05313631310894701,
 'learning_rate': 0.125,
 'max_depth': 3.0,
 'min_child_weight': 30.0,
 'n_estimators': 800.0,
 'subsample': 1.0}

params={'n_estimators': int(params['n_estimators']), 'max_depth': int(params['max_depth']),
            'learning_rate':(params['learning_rate']),
            'min_child_weight':(params['min_child_weight'])
            
            }
XGboost=MultiOutputRegressor(xgb.XGBRegressor(**params,tree_method='gpu_hist',objective='reg:squarederror'))
XGboost.get_params
model_xgb=XGboost.fit(X_train.iloc[:200,],Y_train.iloc[:200,])

**Comment by trivialfis** [comment]
I currently don't have a convenient machine by my side, but here is a guess, 800 estimators means you are boosting forests with each iteration adding 800 trees...

**Comment by trivialfis** [comment]
Try removing that parameter.

**Comment by Thiyagu07** [comment]
The number of estimators does not change for the whole training, When I remove that  tree_method parameter, then I dont use the GPU. I was able to run it without that parameter. But, I also want to use my GPU to speed up the learning

**Comment by trivialfis** [comment]
Yes.  Please try removing `n_estimator` parameter, so that it can use it's default value, which is 1.

**Comment by Thiyagu07** [comment]
It still shows the same error that the kernel died.

When I use the tree_method='gpu_exact', the model runs without any issues

**Comment by trivialfis** [comment]
Will look into it.  How many columns does your input have?  What's your GPU model?

**Comment by trivialfis** [comment]
@Thiyagu07 How many output columns do you have?  If it's too many, you can train one output at a time.

**Comment by trivialfis** [comment]
Closing as this is memory limitation.
