### ISSUE TITLE
the node number of the tree, thx for your reply

### ISSUE THREAD

**Issue by hywchina** [dmlc/xgboost#4776]
When I use XGB tree model, in a tree, the node number of the tree is continuous, some are discontinuous, may I ask why?

**Comment by trivialfis** [comment]
@hywchina Could you give an example output?  Also a reproducible script with used XGBoost version?

**Comment by hywchina** [comment]
![tree1](https://user-images.githubusercontent.com/16551666/63094257-6ca2fb00-bf9a-11e9-9a86-66c821aa9632.jpeg)
1. booster[104]:node4 is a leaf, and the nodes number are discontinuous;

![tree2](https://user-images.githubusercontent.com/16551666/63094416-e9ce7000-bf9a-11e9-8ea5-9f7b9f86bfe6.png)
2. booster[39]:node19 is a leaf, but the nodes number are continuous;

booster[104] and booster[39] from different trees 

thank you very much

**Comment by trivialfis** [comment]
@hywchina I'm not sure I follow, did you mean the node number being a continuous sequence like `1, 2, 3, ..., 7, 8, 9`?

That's related to how the tree updater split (and prune) each node.  Splitting at `1` then the two children will be `2, 3`.  Then split at `2`, `4, 5` will become children of `2`.  The children of `3` will become `6, 7`, assuming depth-wise splitting scheme.  If pruner is used, the deleted node number will be reused for later splits.
