### ISSUE TITLE
[jvm-packages] Remove Python Rabit Tracker

### ISSUE THREAD

**Issue by thesuperzapper** [dmlc/xgboost#4781]
Given we have the opportunity to make some breaking changes in 1.0, I think we should remove the python based Rabit tracker, and only use the Scala based one. The reason for this is the Scala one has many more features, with things like timeouts. 

Here are some links:
* [Spark TrackerConf Docs](https://xgboost.readthedocs.io/en/latest/jvm/scaladocs/xgboost4j-spark/ml/dmlc/xgboost4j/scala/spark/TrackerConf.html)
* [Scala RabitTracker Code](https://github.com/dmlc/xgboost/blob/master/jvm-packages/xgboost4j/src/main/scala/ml/dmlc/xgboost4j/scala/rabit/RabitTracker.scala)

At very least, we should default to the Scala one (given how much better it is) as a breaking change in 1.0.

**Comment by CodingCat** [comment]
I don’t think we should default to scala one which is much less battle tested 

For timeout feature, we have implemented in spark layer where the application will fail if it cannot get enough resources within the given period

**Comment by thesuperzapper** [comment]
@CodingCat in my experience, with issue [4628#issuecomment-510367032](https://github.com/dmlc/xgboost/issues/4628#issuecomment-510367032), the python tracker will just hang forever. But the Scala tracker will actually time out (Regardless of what we decide, we should investigate the 60sec issue)

**Comment by trivialfis** [comment]
Or can we port it into C++ and deprecate both?
