### ISSUE TITLE
Master branch is not compiling properly

### ISSUE THREAD

**Issue by merleyc** [dmlc/xgboost#4784]
Hi,

When trying to compile xgboost in master branch, I am getting this error in _xgboost/build/CMakeFiles/**CMakeError.log**_:
> Determining if the C compiler works failed with the following output:
> Change Dir: <path>xgboost/build/CMakeFiles/CMakeTmp
> 
> Run Build Command(s):/usr/bin/gmake cmTC_5a949/fast
> /usr/bin/gmake -f CMakeFiles/cmTC_5a949.dir/build.make CMakeFiles/cmTC_5a949.dir/build
> gmake[1]: Entering directory `<path>xgboost/build/CMakeFiles/CMakeTmp'
> CMakeFiles/cmTC_5a949.dir/build.make:67: *** missing separator.  Stop.
> gmake[1]: Leaving directory `<path>xgboost/build/CMakeFiles/CMakeTmp'
> gmake: *** [cmTC_5a949/fast] Error 2 

**Steps to reproduce using CentoOS 7:**
1. I have enabled gcc7 using this command: . /opt/rh/devtoolset-7/enable  
2. **gcc --version**
gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
3. **which gcc**
/opt/rh/devtoolset-7/root/usr/bin/gcc
4. export CXX='/opt/rh/devtoolset-7/root/usr/bin/gcc'
export CCC='/opt/rh/devtoolset-7/root/usr/bin/gcc'
5. make clean_all; make -j8

I am using master branch:
**git log**

> commit 7b5cbcc8468448245a1c2ab698d07cb05be75e94
> Author: Nan Zhu <CodingCat@users.noreply.github.com>
> Date:   Wed Aug 14 10:57:47 2019 -0700
> …

**Comment by trivialfis** [comment]
CXX is c++ compiler, should be set to g++.  CCC is not a recognized variable, should be CC

**Comment by trivialfis** [comment]
And above variables should be set before running cmake.

**Comment by merleyc** [comment]
The 'CCC' was a typo from my side while writing this issue.
But starting over in a new terminal and setting the g++ as you suggested, the compilation worked and I see the new jars. Thanks, @trivialfis !!
However,  while doing a quick test I got this error:

> Traceback (most recent call last):
>   File "<path>xgboost_tune-local-omp_MC.py", line 192, in <module>
>     model = run_train(te2, i)
>   File "<path>xgboost_tune-local-omp_MC.py", line 164, in run_train
>     nthread=cores_per_executor
>   File "<path>/spark/spark-2.4.0-bin-hadoop2.7/python/pyspark/__init__.py", line 110, in wrapper
>     return func(self, **kwargs)
>   File "<path>spark-ebe1346b-fef3-4fd0-bc1f-3e49e43a80c9/userFiles-8fb09ebc-f1ca-4a19-81e4-e66978067ca2/sparkxgb_0.83.zip/sparkxgb/xgboost.py", line 113, in __init__
>   File "<path>/spark/spark-2.4.0-bin-hadoop2.7/python/pyspark/ml/wrapper.py", line 67, in _new_java_obj
>     return java_obj(*java_args)
>   File "<path>/miniconda3/envs/sparkConda/lib/python3.7/site-packages/py4j/java_gateway.py", line 1554, in __call__
>     answer, self._gateway_client, None, self._fqn)
>   File "<path>/spark/spark-2.4.0-bin-hadoop2.7/python/pyspark/sql/utils.py", line 63, in deco
>     return f(*a, **kw)
>   File "<path>/miniconda3/envs/sparkConda/lib/python3.7/site-packages/py4j/protocol.py", line 328, in get_return_value
>     format(target_id, ".", name), value)
> **py4j.protocol.Py4JJavaError: An error occurred while calling None.ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.**
> : java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: scala/runtime/java8/JFunction1$mcZI$sp
>         at ml.dmlc.xgboost4j.scala.spark.params.GeneralParams.$init$(GeneralParams.scala:74)
>         at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.<init>(XGBoostClassifier.scala:47)
>         at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.<init>(XGBoostClassifier.scala:52)
>         at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)


My test code is:
```
import pyhdfs
fs = pyhdfs.HdfsClient(hosts='...', user_name='...')

os.environ['PYSPARK_SUBMIT_ARGS'] = '--jars <path>/.m2/repository/ml/dmlc/xgboost4j-spark_2.12/1.0.0-SNAPSHOT/xgboost4j-spark_2.12-1.0.0-SNAPSHOT.jar,<path>/.m2/repository/ml/dmlc/xgboost4j_2.12/1.0.0-SNAPSHOT/xgboost4j_2.12-1.0.0-SNAPSHOT.jar pyspark-shell'

from pyspark import SparkConf, SparkContext
from pyspark.sql import SQLContext

conf = SparkConf() ...
sc = SparkContext(conf=conf,master='local[*]')
spark = SQLContext(sc)
sc.addPyFile('<path>/spark/spark-2.4.0-bin-hadoop2.7/python/lib/sparkxgb_0.83.zip')

train_data = spark.read.format('parquet').load('hdfs:data.parquet')
xgboost = XGBoostClassifier(...)
model = xgboost.fit(train_data)

```

**Comment by hcho3** [comment]
Make sure you are using Java 8.
