### ISSUE TITLE
Add "num_feature" option when reading from a CSR matrix

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#4790]
Currently, the number of columns (features) is inferred when parsing a LIBSVM file. In distributed setting, a host may infer an incorrect number if its portion of data (shard) lacks the last feature. For example, if we have two hosts with the following data shards, the second host will infer wrong number of columns:

Host 1 (infers `num_column=2`)
```
1 1:1
0 1:1
```

Host 2 (infers **`num_column=1`**)
```
0 0:1
1 0:1
```

Fix: Add `num_feature` argument when reading from CSR

**Comment by trivialfis** [comment]
I'm not familiar with the issue.  Can be broadcast the maximum value?

**Comment by hcho3** [comment]
Actually, I don't think this is actually an issue, since XGBoost already performs an all-reduce to compute the true number of features:
https://github.com/dmlc/xgboost/blob/9700776597cb2a6099ae60877a808ad51eb18940/src/data/data.cc#L229-L232
