### ISSUE TITLE
Set up test for cudf.

### ISSUE THREAD

**Issue by trivialfis** [dmlc/xgboost#4792]
After merging the cudf PR,  I need some help for setting up corresponding Python test on Jenkins since on the one hand cudf doesn't support pip, but on the other hand our Jenkins test farm doesn't use conda.

Could you please help?  @mt-jones @hcho3

**Comment by hcho3** [comment]
Can you run `conda install cudf` and see what dependencies it pulls?

**Comment by trivialfis** [comment]
@hcho3 I'm not too sure.  I built cudf from scratch to avoid conda ...  How's XGBoost doing on conda?  Do we need some specialization on Jenkins?

**Comment by hcho3** [comment]
We should create a virtual conda environment so that conda packages don't interfere with system-wide packages managed by pip.

**Comment by hcho3** [comment]
@trivialfis Can you provide the installation command for CUDF using `conda`?

**Comment by trivialfis** [comment]
@hcho3 Yes.  Use that instruction.  Thanks!

**Comment by hcho3** [comment]
@trivialfis Expect a small pull request in a day or two. It will modify the Dockerfiles so as to use `conda` instead of pip.

**Comment by trivialfis** [comment]
@hcho3. Did you mean the whole Jenkins or just CUDF test?

**Comment by hcho3** [comment]
@trivialfis I'm debating between two options, actually:
1. Change the whole Jenkins environment as to use conda instead of pip
2. Create a separate conda environment for CUDF tests only. Other tests will keep the same environments (i.e. packages will be installed with pip).

What's your take on this?

**Comment by trivialfis** [comment]
@hcho3 I myself uses pip exclusively since that's where most people get to know XGBoost (I think)?  So I vote for using pip for most of cases if it doesn't create burden on your side.  I would like to hear back from @RAMitchell .

**Comment by RAMitchell** [comment]
Whatever is easiest for you @hcho3

**Comment by hcho3** [comment]
@trivialfis @RAMitchell I just found out that CUDF requires compute capability 6.0+ and the current Jenkins GPU worker (P2 instance type) does not meet the requirement. I ran
```cuda
#include <iostream>

int main(void) {
  cudaDeviceProp p;
  cudaGetDeviceProperties(&p, 0);
  std::cout << p.major << "." << p.minor << std::endl;
  return 0;
}
```
and got
```
3.7
```

We will need to change the type of Jenkins worker to [P3 instances](https://aws.amazon.com/ec2/instance-types/p3/) which has fancier GPUs.

**Comment by rongou** [comment]
@hcho3 yes cuDF requires Pascal or better, P2 is Kepler, which is two generations behind. For now your only options is P3. When G4 comes online, it might be a cheaper option.

**Comment by trivialfis** [comment]
Interesting.  Half of my PR was written on a compute 50 laptop.

**Comment by rongou** [comment]
Did you override `CMAKE_CUDA_FLAGS`? By default it doesn't generate code for anything below Pascal: https://github.com/rapidsai/cudf/blob/branch-0.10/cpp/CMakeLists.txt#L65

**Comment by trivialfis** [comment]
@rongou Probably.  I put up a long fight.
