### ISSUE TITLE
Prediction result does not match of xgboost 0.82 vs 0.90 (on 5.4 ML Databricks Runtime)

### ISSUE THREAD

**Issue by nkr-jgr** [dmlc/xgboost#4796]
Hi

My prediction results from 0.82 librariy of xgboost doesn't match with the results when i am using Databricks 5.4 ML runtime inbuilt XGBoost library which is 0.90.

Please assist me with the same.
Let me know if any further information are required to resolve my query.

**Comment by hcho3** [comment]
@nkr-jgr Can you reproduce the problem without Databricks? If so, can you post your data and script so that we can try to reproduce the problem?

**Comment by CodingCat** [comment]
0.82 has an issue in prediction when there is an upstream shuffle, we have fixed in 0.9
