### ISSUE TITLE
glibc version problem, the glibc in my system is 2.5, xgboost4j JVM crash occurs

### ISSUE THREAD

**Issue by wenmin-wu** [dmlc/xgboost#480]
Dear all,
    The xgboost4j works well in my own computer(my own computer's glibc version is 2.19). But, I want to run it in a node of my company where the glibc version is 2.5. I run `. scripts/travis_java_script.sh ` in that computer. The JUnit tests can't pass. Even though I ingored the Test in the package progress, the packaged jar file can't work either. 
    
![qq 20150910100234](https://cloud.githubusercontent.com/assets/9409333/9778467/35be5e9e-57a3-11e5-95e1-8f3e9c914aa2.png)

    I want to know how can fix this problem without update the glibc version.

**Comment by tqchen** [comment]
this might need an update of the libc, or simply install a customize compiler on user side
