### ISSUE TITLE
Parse pre-sharded data files in distributed mode (Rabit initialized)

### ISSUE THREAD

**Issue by ericangelokim** [dmlc/xgboost#4812]
When Rabit is initialized, the current DMatrix initialization from file expects all data files to be present and shards the data. However, customers may shard/distribute files with no replication to hosts, which would lead to two levels of sharding. DMatrix should be initialized with a flag to prevent excessive sharding.

Current behavior:
```
Host 0 gets first 1/3 of foobar.libsvm
Host 1 gets middle 1/3 of foobar.libsvm
Host 2 gets last 1/3 of foobar.libsvm
```

Proposed behavior (with the proposed flag enabled):
```
Host 0 gets foobar/partition0.libsvm
Host 1 gets foobar/partition1.libsvm
Host 2 gets foobar/partition2.libsvm
```

This is advantageous on file systems such as S3, where we can maximize the read bandwidth by reading from separate files in parallel.

At a quick glance, we should be able to add a boolean flag from the Python bindings to prevent splitting by row, even if Rabit is initialized:

https://github.com/dmlc/xgboost/blob/master/src/c_api/c_api.cc#L162

**Comment by trivialfis** [comment]
XGBoost supports multiple distributed frameworks.  I think this is best handled by one of them.
