### ISSUE TITLE
Making sure to have right mapping between predictors and output for dask interface.

### ISSUE THREAD

**Issue by trivialfis** [dmlc/xgboost#4814]
Dask makes small partitions for data objects.  Currently XGBoost collects those partitions into local workers based on `rabit.get_rank()`.  But I am not sure that's the correct way of collecting partitions.  It's possible that we end up collecting different portions of whole dataset.

Quoting from the document of [internal design](https://docs.dask.org/en/latest/dataframe-design.html#partitions)
```
When our index is sorted and we know the values of the divisions of our partitions, then we can be clever and efficient with expensive algorithms (e.g. groupby’s, joins, etc…).
```

Say for example if I loaded a dataset, split it up into predictors and labels and do some processing to each of them separately.  It's not promised that they will have the same number of total partitions, nor the order of partitions stays the same.

@RAMitchell

**Comment by mrocklin** [comment]
Please let me know if you all want to discuss XGBoost + Dask interactions in the future.  There are probably things that we could find to do on the Dask side that would make the XGBoost experience here more pleasant.

**Comment by trivialfis** [comment]
@mrocklin Thanks for reaching out.

Currently I took your suggestion for attaching a `_xgboost_data` field to each `worker` in  #4819 .  But the memory is not managed by dask and it's tricky to manage it ourselves since we might have computation still pending in the future.

Another problem is mentioned above.  We have multiple inputs, predictors, weights, labels, they are all row-wise mapped.  If I use `map_partitions`, I have to make sure that the right partitions for each input got selected to the right workers.  For now I need to join the dataframes into one, map partition, and then split it up then hook them to workers.  It increases the peak memory usage and is quite slow.

But other that these, I find it quite enjoyable to watch the web interface.  I might add a call back function to XGBoost for dask so that I can get more information about the training procedure.

**Comment by trivialfis** [comment]
@mrocklin Digging into the dask_xgboost actually revealed many useful techniques.  Will come back once I know more.
