### ISSUE TITLE
XGBoost runs slower when compiled by Clang

### ISSUE THREAD

**Issue by liqinggd** [dmlc/xgboost#4820]
I compiled XGBoost with Clang 9, the compile command is:
```
mkdir build
cd build
cmake ../ -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=/usr/lib/llvm-9/bin/clang -DCMAKE_CXX_COMPILER=/usr/lib/llvm-9/bin/clang++
make -j
```
I run the binary_classification demo in `demo/binary_classification` with single thread, However, I find the training speed is about 50% slower than GCC 5.4.0, this result shock me.

Have you enabled some optimization when compiled by GCC, how can I fix this overhead when compiled by Clang?

My machine is Intel(R) Xeon(R) CPU E3-1270 v6 @ 3.80GHz
My OS is Ubuntu 16.04

**Comment by trivialfis** [comment]
@liqinggd Possible.  We have been using gcc all these years.  Some optimizations are in `include/xgboost/base.h`.  Some are scattered over other places like `hist_util.cc` and OpenMP parameters.

**Comment by liqinggd** [comment]
@trivialfis Thanks for your answer. I found than if I increase the inline-threshold in Clang can improve the performance, but the binary size is too big than gcc, finally I changed the compiler from clang to gcc.
