### ISSUE TITLE
Tree method for `grow_local_histmaker`.

### ISSUE THREAD

**Issue by trivialfis** [dmlc/xgboost#4822]
@hcho3 I'm curious if this is used/tested.  I can't find corresponding `tree_method` in our configuration.  ~Or the updater is hidden due to some bugs before?~

**Comment by hcho3** [comment]
I think it was implemented as part of the original XGBoost paper by @tqchen. I don't think it's being used anywhere, unless the user manually sets `updater_seq`.

**Comment by trivialfis** [comment]
It's not tested either.  A bit worrying.
