### ISSUE TITLE
parameter.rst: Parameters for Tree Booster tree_method missing gpu_exact

### ISSUE THREAD

**Issue by raybellwaves** [dmlc/xgboost#4823]
I believe the documentation for parameters for tree booster is missing the choice 'gpu_exact' in `tree_method`.
https://github.com/dmlc/xgboost/blob/master/doc/parameter.rst#parameters-for-tree-booster

I stumbled across this via a typo

```
XGBoostError: Invalid Input: 'gpu-hist', valid values are: {'approx', 'auto', 'exact', 'gpu_exact', 'gpu_hist', 'hist'}
```

**Comment by trivialfis** [comment]
It's removed in master branch.  Please use `gpu_hist` instead.  It's much more efficient.

**Comment by raybellwaves** [comment]
Thanks
