### ISSUE TITLE
xgb.plot.shap using shap_contrib values fails

### ISSUE THREAD

**Issue by avanwouwe** [dmlc/xgboost#4828]
When calling xgb.plot.shap using data calculated with a previous run of xgb.plot.shap in this way:
  
`  xgb.plot.shap(shap_contrib = prev$shap_contrib, data = prev$data)
`

.. I get "shap_contrib is not compatible with the provided data".

When looking at the code, I get the impression that there is an error in line 123.  Should this:

`        (!is.matrix(shap_contrib) || nrow(shap_contrib) != nrow(data) || ncol(shap_contrib) != ncol(data)+1))
`

..not really be this:
 
`            (!is.matrix(shap_contrib) || nrow(shap_contrib) != nrow(data) || ncol(shap_contrib) != ncol(data)))
`

i.e. without the "+1" at the end? If I remove it, the function works for me.

**Comment by trivialfis** [comment]
@avanwouwe Please provide your XGBoost version and a reproducible script.
