### ISSUE TITLE
Compiling in Visual Studio Issue

### ISSUE THREAD

**Issue by penguin2121** [dmlc/xgboost#483]
Hello,

I am trying to compile xgboost in visual studio 2015 (I also tried 2013 express) on a windows 10 64 bit PC.  I download the files in the windows folder, open the solution file, then when prompted I upgrade the files to the current version of visual studio (I did this in both 2015 and 2013), I change to Release and x64, and then I try to build the solution.  I get 18 errors: all basically say things like "Cannot open source file: '..\..\src\gbm\gbm.cpp': No such file or directory".  They are all different .cpp fies it can't find.

What should I do differently?

Thanks!

![errors](https://cloud.githubusercontent.com/assets/13374790/9806857/5c4aa5a2-57ff-11e5-9efe-6c0a31fa70ed.jpg)

**Comment by penguin2121** [comment]
I also have Windows 10 64 bit...is that a possible issue?

**Comment by penguin2121** [comment]
Anyone know what to do?  I've encountered a few other forums where people have had this issue, but no solutions.

Thanks!

**Comment by penguin2121** [comment]
Hello, I figured it out.  What I was doing wrong was only copying out the "Windows" folder from the folders provided.  You need to copy all folders and their relationships to one another before you compile (i.e. you need the src folder).

**Comment by tqchen** [comment]
Glad that it works out for you.
