### ISSUE TITLE
[jvm-packages] retry-able xgboost4j-spark booster

### ISSUE THREAD

**Issue by chenqin** [dmlc/xgboost#4831]
This document discuss how we enable xgb-spark trainer resilient to single point of failure, more detail here https://github.com/dmlc/xgboost/issues/4753

**Changes**

1.  pass addational rabit init parameters into local rabit agent, as following prototype shows
This would allow end user opt-in rabit recovery while disable spark checkpoint.

![1](https://user-images.githubusercontent.com/1184534/64232874-ab481900-cea7-11e9-8eb3-fd90db7de424.PNG)

2.  allow configuration file accept additional rabit parameters, which currently is limited whitelist. This would allow user fine tune settings like ( ring based allreduce in rabit, detailed synchornization logging, channel wise buffer size etc) 

![2](https://user-images.githubusercontent.com/1184534/64233119-3a553100-cea8-11e9-9c9f-f9d40beab5bb.PNG)

3. honor user choice and wait for failed worker retry
![3](https://user-images.githubusercontent.com/1184534/64233311-b51e4c00-cea8-11e9-886a-25eb1b12631e.PNG)

4. tests
testing distributed failure recovery in single machine is tricky. We can build jvm with librabit_mock which accept mock string and instrument crash. We only have one executor and each task don't have proper failure isolation and share same process often. so we need to enable DMLC not failure flag to avoid mocked test failure actually exit program and throw exceptions.

**Implications**
- when user opt-in rabit recovery, spark checkpoint will no longer enabled. So it means if entire spark job failed due to tracker/driver die or other reasons, we need to retrain from beginning.

- when xgb worker die, partitioned rdd might lost. This will trigger spark redo previous stage. Thanks to effort of having a determined partitioning scheme, rerun shall not give different partitioned datasets. The issue is how can we prevent rerun or allow rerun while rest of trainers in paused state. 

We can do 

1) write to externalshuffleservice 
2) over-provision certain percentage of resources so redo tasks run and bring up failed trainer.

@CodingCat

**Comment by trams** [comment]
I like this very much! I would like to try it and to test it if possible

**Comment by chenqin** [comment]
> I like this very much! I would like to try it and to test it if possible
Thanks! please review and provide some feedback https://github.com/dmlc/xgboost/pull/4966

**Comment by trams** [comment]
Thank you, @chenqin for your work on this. I am very excited that you started publishing your changes. I am looking forward to new pull requests!
