### ISSUE TITLE
Should I use custom eval metric if I set weights for samples using setWeightCol?

### ISSUE THREAD

**Issue by LindaNiu** [dmlc/xgboost#4834]
I set sample weights for my samples using setWeightCol, and then I use setEvalMetric("auc") to evaluate my model on test dataset. 
But it just hit me that if the source code of auc in Spark XGBoost take weight into account?  Or should I define a custom eval metric? I tried to find source code but failed. Thanks a lot for solving my problem : )

**Comment by hcho3** [comment]
Yes, AUC takes data weights into account.
