### ISSUE TITLE
xgboost out-of-core operation got closed while training

### ISSUE THREAD

**Issue by shawn07023** [dmlc/xgboost#4839]
Hi, as title, I am using out-of-core operation to train my model due to a large data set, which cannot fit into my memory.
Problem 1:
First of all, I transfer the data into Libsvm format. Then follow the instructions of out-of-core operation and start run. Then, my python's console is somewhat restart itself.
It can be solved if I re-run several times to get into the training process but it's pretty annoying to do that over and over again.

Problem 2:
I found out that even I use out-of-core operation. The memory is still increasing after building a new tree. Eventually, console restarts again due to out of memory.
However, I remember the first time that I use this operation that the memory would be the same during the training process. I went online to see some related info. about this. I saw that the official manual states that if my cpu core is 8 and the nthread is 32. I should use nthread as 16 instead of 32.
I am not sure if this is problem.

My code is listed below:

x_train_df = TrainFileName + '#dtrain.cache'
x_test_df = TestFileName + '#dtest.cache'
params = {
    'eval_metric' :'rmse',
    'booster':'gbtree',
    'objective':'reg:linear',   
    'gamma':0,
    'lambda':0,
    'subsample':0.78,
    'colsample_bytree':0.8,
    'min_child_weight':5,
    'silent':0,
    'eta':0.08,
    'max_depth':10,
}
xg_test = xgb.DMatrix(x_test_df)
xg_train = xgb.DMatrix(x_train_df)
model = xgb.train(params, xg_train, 60, obj = huber_approx_obj , evals = [(xg_train, "training"), (xg_test, "testing")])

Thanks

**Comment by trivialfis** [comment]
@shawn07023 Could you please provide a reproducible script?

**Comment by trivialfis** [comment]
Also XGBoost version,  some bugs are fixed in master branch.
