### ISSUE TITLE
continue training of the existing model

### ISSUE THREAD

**Issue by alizzz** [dmlc/xgboost#484]
Is there a method to continue training a model? For example, let's say I have trained a model for 100 rounds, but then decided that I can go to 150. Do I have to train it again for the 150, or there is a way to train another 50 round starting from already trained model (let's assume that all other parameters, including the data, remain the same).
This is similar functionality that gbm offers with gbm.more(...) method.

**Comment by hetong007** [comment]
Please check the following:
python: https://github.com/dmlc/xgboost/blob/master/demo/guide-python/boost_from_prediction.py
R: https://github.com/dmlc/xgboost/blob/master/R-package/demo/boost_from_prediction.R

**Comment by Far0n** [comment]
I guess he means something like this: https://github.com/Far0n/xgboost/commit/c768a042cba117547a10aa7682f7e6fd60cec6ea

**Comment by Quares** [comment]
Would be great to see this feature augmented to the R implementation
