### ISSUE TITLE
xgboost c api(predict) is not thread safe

### ISSUE THREAD

**Issue by weidong8405** [dmlc/xgboost#4841]
i use the xgboost's api(XGBoosterPredic) and call the function in different thread, i find that not safe, i saw some discuss before, but it has long time from now, so i want to know if xgboost predict api can support multi thread case now?

**Comment by trivialfis** [comment]
@weidong8405 Not much progress is on prediction right now, since the CPU Predictor natively support multi-threaded prediction with openmp.

**Comment by weidong8405** [comment]
@trivialfis  yes i know the api support multi thread, but in the industry inference, the api will be called multi thread, the thread manager will not control by the openmp
The question is the predict api can be called in multi thread? not internal multi thread

**Comment by trivialfis** [comment]
@weidong8405 No.  You can't.  XGBoost has a cache for prediction.

**Comment by poseidon1214** [comment]
you can use c11 **local_thread**

**Comment by trivialfis** [comment]
The cache is used is various places during training, so going out of sync between threads might cause troubles.  You are welcomed to look into it.

**Comment by trivialfis** [comment]
One solution would be user providing their own memory buffer.  I incline to create a C API that wraps host device vector for external use.  So that user can pass in a memory buffer created by XGBoost.  @hcho3 @RAMitchell

**Comment by trivialfis** [comment]
Thread safe prediction added.
