### ISSUE TITLE
Memory leak in subsequent model fitting?

### ISSUE THREAD

**Issue by GuidoBartoli** [dmlc/xgboost#4843]
Hi,
I created a XGBoost model with data subsampling (`subsample < 1`) and I implemented a loop to train it using different `random_state` values and choose the best performing initialization.

This is the simplified Python code:
```
# setup train_x, train_y, eval_set, eval_metric #
accuracies = []
best = None
for i in range(100):
    variation = xgb.XGBClassifier(random_state=i, n_jobs=-1)
    variation.fit(train_x, train_y, eval_set=eval_set, eval_metric=eval_metric)
    accuracy = 1 - variation.evals_result()['validation_1']['error'][-1]
    if best is None or accuracy > max(accuracies):
        best = variation
    accuracies.append(accuracy)
```

It works as expected, but I noticed that if I monitor the RAM during the process, the usage continues to grow after each iteration even if I assigned a new XGBClassifier to the same variation variable. Python should free the unreferenced memory location every time and maintain the memory usage constant, right?

This is the screenshot of System Monitor Resources:
![memory](https://user-images.githubusercontent.com/16103676/64523864-8adfea80-d2fd-11e9-85c6-b2e01edca355.jpg)
Computation starts at the first CPU spike at 100% on the left and a new iteration starts at each drop in CPU usage while RAM usage steps up accordingly, but never goes down.

Is this a bug in resource deallocation inside `XGBClassifier` or am I missing something?

Many thanks in advance,
Cheers

**Comment by hcho3** [comment]
Can you try inserting `del best` under the condition `if best_model is None or accuracy > max(accuracies)`, so as to explicitly remove the object?

**Comment by GuidoBartoli** [comment]
Thanks for the suggestion! However I cannot delete `best`, because it is needed in the code following the snippet... maybe you are referring to the temporary `variation`?

I modified the code like this:
```
# setup train_x, train_y, eval_set, eval_metric #
accuracies = []
best = None
for i in range(100):
    variation = xgb.XGBClassifier(random_state=i)
    variation.fit(train_x, train_y, eval_set=eval_set, eval_metric=eval_metric)
    accuracy = 1 - variation.evals_result()['validation_1']['error'][-1]
    if best is None or accuracy > max(accuracies):
        best = variation
    accuracies.append(accuracy)
    del variation
```
But unfortunately RAM usage continues... :(
![memory](https://user-images.githubusercontent.com/16103676/64592470-642cbd00-d3ac-11e9-8440-11556981e4a4.jpg)

**Comment by hcho3** [comment]
Can you post a toy dataset so that I can reproduce it too

**Comment by GuidoBartoli** [comment]
Sure, I prepared a small HDF5 dataset together with toy.py script to replicate this behaviour. It is not as evident as in the large dataset, however the RAM keeps growing in this case, too.

[toy.zip](https://github.com/dmlc/xgboost/files/3596117/toy.zip)

Let me know if you need more information.

**Comment by GuidoBartoli** [comment]
Hi, any news about this potential issue?

Regards

**Comment by trivialfis** [comment]
Not yet.  Marked as blocking.  Thanks for the patience.

**Comment by GuidoBartoli** [comment]
I made some other tests and I can confirm that this issue is still present even when Exact Greedy algorithm is used instead of Fast Histograms.

**Comment by trivialfis** [comment]
Sorry for the long wait.  I'm refactoring the IO logic right now.  Will start squashing bugs once it's sorted out.

**Comment by trivialfis** [comment]
@GuidoBartoli How many classes do you have?

**Comment by trivialfis** [comment]
I ran the following and did not observe the leak on master branch f24be2efb479872da2613b40fbf04a77f961d250:

``` python
import xgboost as xgb
import numpy as np

kRows = 200000
kCols = 1000
kClasses = 8

train_x = np.random.randn(kRows, kCols)
train_y = np.random.randint(0, kClasses, size=kRows)
print(train_y.shape)

eval_x = np.random.randn(kRows, kCols)
eval_y = np.random.randint(0, kClasses, size=kRows)
print(eval_y.shape)

eval_set = [(train_x, train_y), (eval_x, eval_y)]
eval_metric = 'mlogloss'

accuracies = []
best = None
for i in range(100):
    # tested with slow default tree_method `approx' and faster `hist'
    # and `gpu_hist'
    variation = xgb.XGBClassifier(random_state=i, n_jobs=12)
    variation.fit(train_x, train_y, eval_set=eval_set, eval_metric=eval_metric)
    print(variation.evals_result())
    accuracy = 1 - variation.evals_result()['validation_1']['error'][-1]
    if best is None or accuracy > max(accuracies):
        best = variation
    accuracies.append(accuracy)
    del variation
```

**Comment by GuidoBartoli** [comment]
> @GuidoBartoli How many classes do you have? We use one stack of trees for each class. If you have lots of classes, then the memory consumed by trees can be significant.

I tried with binary classification, you can take a look at code and dataset in the provided toy example.

**Comment by GuidoBartoli** [comment]
> I ran the following and did not observe the leak on master branch [f24be2e](https://github.com/dmlc/xgboost/commit/f24be2efb479872da2613b40fbf04a77f961d250):
> 
> ```python
> import xgboost as xgb
> import numpy as np
> 
> kRows = 200000
> kCols = 1000
> kClasses = 8
> 
> train_x = np.random.randn(kRows, kCols)
> train_y = np.random.randint(0, kClasses, size=kRows)
> print(train_y.shape)
> 
> eval_x = np.random.randn(kRows, kCols)
> eval_y = np.random.randint(0, kClasses, size=kRows)
> print(eval_y.shape)
> 
> eval_set = [(train_x, train_y), (eval_x, eval_y)]
> eval_metric = 'mlogloss'
> 
> accuracies = []
> best = None
> for i in range(100):
>     # tested with slow default tree_method `approx' and faster `hist'
>     # and `gpu_hist'
>     variation = xgb.XGBClassifier(random_state=i, n_jobs=12)
>     variation.fit(train_x, train_y, eval_set=eval_set, eval_metric=eval_metric)
>     print(variation.evals_result())
>     accuracy = 1 - variation.evals_result()['validation_1']['error'][-1]
>     if best is None or accuracy > max(accuracies):
>         best = variation
>     accuracies.append(accuracy)
>     del variation
> ```

Ok, I'll try this snippet on my machine and I'll let you know my findings, thanks!

**Comment by GuidoBartoli** [comment]
Hi trivialfis,
I used the following code adapted from your snippet (I installed only numpy, scikit and xgboost).
I tried various combinations of dataset size, jobs, histograms, but in every case the memory keeps growing. However, at regular intervals there is an usage drop, but not to the starting amount, you can see it in the attached screenshot. At the moment on my machine I cannot recompile the latest master branch to reproduce this behavior, can you try this exact code on that version?

```
import xgboost as xgb
import numpy as np

samples = 50000
features = 100
classes = 2
variations = 100
histograms = False
n_jobs = 4

print('Generating dataset ({}x{}x{})...'.format(samples, features, classes))
train_x = np.random.randn(samples, features)
train_y = np.random.randint(0, classes, size=samples)
eval_x = np.random.randn(samples, features)
eval_y = np.random.randint(0, classes, size=samples)
eval_set = [(train_x, train_y), (eval_x, eval_y)]
if classes == 2:
    objective = 'binary:logistic'
    eval0 = 'error'
    eval1 = 'logloss'
else:
    objective = 'multi:softmax'
    eval0 = 'merror'
    eval1 = 'mlogloss'
eval_metric = [eval0, eval1]
kwargs = {'tree_method': 'hist', 'grow_policy': 'depthwise'} if not histograms else {}

accuracies = []
best = None
for i in range(variations):
    print('Training variation #{}/{}...'.format(i, variations))
    variation = xgb.XGBClassifier(random_state=i, n_jobs=n_jobs)
    variation.fit(train_x, train_y, eval_set=eval_set, eval_metric=eval_metric, verbose=False)
    accuracy = 1 - variation.evals_result()['validation_1'][eval0][-1]
    if best is None or accuracy > max(accuracies):
        best = variation
    accuracies.append(accuracy)
    print('> Accuracy = {}'.format(accuracy))
    del variation
```

![XGB2](https://user-images.githubusercontent.com/16103676/67486900-2f7b7900-f66d-11e9-9785-48e0d8b7d467.jpg)

**Comment by hcho3** [comment]
@GuidoBartoli 

> At the moment on my machine I cannot recompile the latest master branch to reproduce this behavior, can you try this exact code on that version?

You can install the nightly build by running
pip3 install https://s3-us-west-2.amazonaws.com/xgboost-nightly-builds/xgboost-1.0.0_SNAPSHOT+96cd7ec2bbdec1addf81b1ca2adb13c9155e32f3-py2.py3-none-manylinux1_x86_64.whl

**Comment by GuidoBartoli** [comment]
Ok, thanks, I installed the 1.0.0_SNAPSHOT version in my virtual environment using pip.
I run the previous snippet on that version, but unfortunately I see a similar behavior.
I took another screenshot of the memory usage after 33 variations.
![XGB3](https://user-images.githubusercontent.com/16103676/67489332-afa3dd80-f671-11e9-8166-e92bc5f77310.jpg)

**Comment by trivialfis** [comment]
Will take a look again.  Thanks for the follow up.
________________________________

**Comment by trivialfis** [comment]
@GuidoBartoli And looked.  Switching to my laptop helps.  The magic is here:  notice the `gc`, it forces Python to collect memory.

``` python
import xgboost as xgb
import numpy as np
import gc

samples = 50000
features = 100
classes = 2
variations = 100
histograms = False
n_jobs = 4

print('Generating dataset ({}x{}x{})...'.format(samples, features, classes))
train_x = np.random.randn(samples, features)
train_y = np.random.randint(0, classes, size=samples)
eval_x = np.random.randn(samples, features)
eval_y = np.random.randint(0, classes, size=samples)
eval_set = [(train_x, train_y), (eval_x, eval_y)]

if classes == 2:
    objective = 'binary:logistic'
    eval0 = 'error'
    eval1 = 'logloss'
else:
    objective = 'multi:softmax'
    eval0 = 'merror'
    eval1 = 'mlogloss'
eval_metric = [eval0, eval1]
kwargs = {'tree_method': 'hist', 'grow_policy': 'depthwise'} if not histograms else {}

print('classes:', classes)

accuracies = []
best = None
for i in range(variations):
    print('Training variation #{}/{}...'.format(i, variations))
    variation = xgb.XGBClassifier(random_state=i, n_jobs=n_jobs)
    variation.fit(train_x, train_y, eval_set=eval_set, eval_metric=eval_metric, verbose=False)
    accuracy = 1 - variation.evals_result()['validation_1'][eval0][-1]
    if best is None or accuracy > max(accuracies):
        best = variation
    accuracies.append(accuracy)
    print('> Accuracy = {}'.format(accuracy))
    del variation
    gc.collect()
```

**Comment by GuidoBartoli** [comment]
Awesome, that was it! :trophy: 
And there is more: with forced garbage collection, "del variation" is not needed anymore, since a new instance is assigned to the same variable and Python recycles the memory occupied by the previous one (as expected in my first comment in this issue).

Many thanks! :+1:

**Comment by trivialfis** [comment]
For anyone who encounter this issue, it's mitigated and expected to be part of 1.1.
