### ISSUE TITLE
Help！ Windows Error 0xe06d7363

### ISSUE THREAD

**Issue by lwsdegithub** [dmlc/xgboost#4847]
Had you guys met this error? I can not get a solution from the "close issues". 
I don't know how to solve it.

**Comment by lwsdegithub** [comment]
OSError: [WinError -529697949] Windows Error 0xe06d7363
This is the details.

**Comment by lwsdegithub** [comment]
Ok, I konw why. 
I ues the XGBClassifier, but I foget to let my label to be 0 and 1

**Comment by trivialfis** [comment]
No idea how's changing label can throw an OSError.  But closing as it's resolved.
