### ISSUE TITLE
[Feature Request] DMatrix sort features by name

### ISSUE THREAD

**Issue by luranhe** [dmlc/xgboost#4848]
### Request
When initializing a DMatrix from data, if the data comes with named columns, would it be possible to sort the columns by name before the rest of the initialization?

### Rationale
Feature names are not stored on model save/load.  But it might be nice if I could, say, change the order of named columns in my pandas dataframe and have everything still work as expected, right?

**Comment by trivialfis** [comment]
You can sort the columns in pandas, save the sorted `df.columns` and use it later.  XGBoost doesn't need to handle what pandas excels.
