### ISSUE TITLE
LibSVM format question

### ISSUE THREAD

**Issue by randombishop** [dmlc/xgboost#485]
What is the right way to encode null values ? 

From my understanding, not specifying a feature in libsvm means its value is zero, but what if i have real zeros that are different than nulls ?

**Comment by randombishop** [comment]
Just found this ; https://github.com/dmlc/xgboost/issues/21
I guess i just have to put zeros in the libsvm file, then the rest will be handled as missing ?

**Comment by tqchen** [comment]
Yes. You can also treat zero as missing if that column do not contain missing values.
