### ISSUE TITLE
[wip] json format support of learner and model payload

### ISSUE THREAD

**Issue by chenqin** [dmlc/xgboost#4852]
make rabit checkpoint (learner and tree) json format, helps with front end visualization(zoom in and zoom out with "debugger" as new tree were added in fly) as well as backward compatibility moving forward.

detail discussion here
https://github.com/dmlc/xgboost/pull/4808#discussion_r323065856
master ticket
https://github.com/dmlc/xgboost/issues/3980

**Comment by trivialfis** [comment]
I have a WIP PR doing it.  It will take some time.

**Comment by chenqin** [comment]
got it.
