### ISSUE TITLE
[jvm-packages] expose rabit configuration to user

### ISSUE THREAD

**Issue by chenqin** [dmlc/xgboost#4861]
I would like to start a discussion on if and how we expose rabit configurations to xgb-spark/flink users. Some use cases are,
- allow user opt-in rabit_boostrap_cache within xgboost4-spark configuraiton setting
- allow user opt-in verbose rabit allreduce/broadcast, checkpointing logs 
- allow user opt-in ring-scatter/ all gather based allreduce ( for large trees)
- allow user tune default rabit network buffer size (default is 256MB)
- support mocking to allreduce/broadcast operations for testing benefit

https://github.com/dmlc/rabit/blob/master/src/allreduce_base.cc#L43-L58
![image](https://user-images.githubusercontent.com/1184534/64990009-b7f34680-d883-11e9-880c-fd2997b70618.png)

cc @CodingCat @hcho3

**Comment by trivialfis** [comment]
Firstly I would like to know how many of these are necessarily environment variables?  Can they be  function parameters?  Or use a RPC protocol?

**Comment by chenqin** [comment]
Good call, env variables initial used to read hadoop default setting. And it was applied to things not necessarily should exists in envs. I would suggest remove from envs and ask caller specifically pass down as arguments so we can log in debug mode.

```
// initialization function
bool AllreduceBase::Init(int argc, char* argv[]) {
  // setup from enviroment variables
  // handler to get variables from env
  for (size_t i = 0; i < env_vars.size(); ++i) {
    const char *value = getenv(env_vars[i].c_str());
    if (value != NULL) {
      this->SetParam(env_vars[i].c_str(), value);
    }
  }
  // pass in arguments override env variable.
  for (int i = 0; i < argc; ++i) {
    char name[256], val[256];
    if (sscanf(argv[i], "%[^=]=%s", name, val) == 2) {
      this->SetParam(name, val);
    }
  }
```

**Comment by chenqin** [comment]
https://github.com/dmlc/rabit/pull/106

**Comment by chenqin** [comment]
https://github.com/dmlc/xgboost/pull/4876
