### ISSUE TITLE
Issue with libxgboost.so while building demo/c-api

### ISSUE THREAD

**Issue by pallabkarmakar** [dmlc/xgboost#4865]
Hi Team,

I am working on C/C++ project where I need to use XGboost. I have compiled Xgboost V0.90 successfully in mu linux system. After installation I can see Xgboost binary and lib/xgboost.so . Now I am trying to use the same at demo C/C++ program. I am trying to build xgboost/demo/c-api using make. But during build i am getting following error.

gcc -std=c99 -O3 -I…/…/include -I…/…/dmlc-core/include -I…/…/rabit/include -L…/…/lib -o c-api-demo c-api-demo.c -lxgboost
/usr/bin/ld: skipping incompatible /usr/lib/…/lib/libc.so when searching for -lc
…/…/lib/libxgboost.so: undefined reference to std::__throw_regex_error(std::regex_constants::error_type)@GLIBCXX_3.4.15' ../../lib/libxgboost.so: undefined reference tostd::__throw_bad_function_call()@GLIBCXX_3.4.14’
…/…/lib/libxgboost.so: undefined reference to std::__detail::_Prime_rehash_policy::_M_next_bkt(unsigned long) const@GLIBCXX_3.4.18' ../../lib/libxgboost.so: undefined reference totypeinfo for std::regex_error@GLIBCXX_3.4.15’
…/…/lib/libxgboost.so: undefined reference to __cxa_thread_atexit@CXXABI_1.3.7' ../../lib/libxgboost.so: undefined reference tostd::__detail::_Prime_rehash_policy::_M_need_rehash(unsigned long, unsigned long, unsigned long) const@GLIBCXX_3.4.18’
…/…/lib/libxgboost.so: undefined reference to `std::chrono::_V2::system_clock::now()@GLIBCXX_3.4.19’
collect2: error: ld returned 1 exit status
make: *** [c-api-demo] Error 1

I need some help to resolve this. Could any one help me.

**Comment by trivialfis** [comment]
How did you compile xgboost?  Could you please share your compilation options, compiler version?  And I see the error message there is an incompatible libc?  Could that be a reason?

**Comment by pallabkarmakar** [comment]
@trivialfis I did compile Xgboost using cmake. Below are the steps i followd to compile.
git clone --branch v0.90 --recursive https://github.com/dmlc/xgboost
cd xgboost/
mkdir build
cd build/
cmake ..
make -j4

My compilation version is :
gcc (GCC) 4.8.5

**Comment by pallabkarmakar** [comment]
-bash-4.1$ strings xgboost/lib/libxgboost.so | grep GLIBCXX
GLIBCXX_3.4.18
GLIBCXX_3.4.14
GLIBCXX_3.4.10
GLIBCXX_3.4.19
GLIBCXX_3.4.11
GLIBCXX_3.4.15
GLIBCXX_3.4.9
GLIBCXX_3.4

**Comment by trivialfis** [comment]
@pallabkarmakar I don't think gcc-4.8 has c++11 regex?

**Comment by pallabkarmakar** [comment]
@trivialfis Thanks for your reply.

But while I am compiling Xgboost using cmake , it was asking to have at least 4.8 or higher. 
Anyway I changed Makefile as "gcc -std=c99" to "g++ -std=c++11" . It gone through the compilation with following message.
g++ -std=c++11 -O3 -I../../include -I../../dmlc-core/include -I../../rabit/include -L../../lib -o c-api-demo c-api-demo.c -lxgboost
/usr/bin/ld: skipping incompatible /usr/lib/../lib/libm.so when searching for -lm
/usr/bin/ld: skipping incompatible /usr/lib/../lib/libc.so when searching for -lc


But it generates executable "c-api-demo". But while running the same got following error.
(/home/w546901/c_compile/) -bash-4.1$ ./c-api-demo
./c-api-demo: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by /home/r622244/09_Sep_2019/xgboost/lib/libxgboost.so)
./c-api-demo: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by /home/r622244/09_Sep_2019/xgboost/lib/libxgboost.so)
./c-api-demo: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.19' not found (required by /home/r622244/09_Sep_2019/xgboost/lib/libxgboost.so)
./c-api-demo: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.7' not found (required by /home/r622244/09_Sep_2019/xgboost/lib/libxgboost.so)
./c-api-demo: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /home/r622244/09_Sep_2019/xgboost/lib/libxgboost.so)

**Comment by trivialfis** [comment]
@pallabkarmakar Sorry I think that must be a bug in 0.9 release.  We updated the gcc requirement later: https://github.com/dmlc/xgboost/blob/5374f525311f7a825fb9e1be7fd899ea2bc0647b/CMakeLists.txt#L12

The basic requirement for compiling XGBoost (not c api application you are writing) is c++11.  Safest path is to find a compiler that has c++11 support.

**Comment by pallabkarmakar** [comment]
@trivialfis let me try with gcc 5.0 .

**Comment by pallabkarmakar** [comment]
Sure. I will keep you posted. Thanks for your help @trivialfis

**Comment by pallabkarmakar** [comment]
@trivialfis 

After clone latest version and compiled with gcc 5.2.0 .so didn't generated. but didn't get any error. below is the log.

gcc (GCC) 5.2.0
cmake version 3.11.4

======================== LOG ==========================
(/home/w546901/c_compile/) -bash-4.1$ cmake ..
-- The CXX compiler identification is GNU 5.2.0
-- The C compiler identification is GNU 5.2.0
-- Check for working CXX compiler: /home/w546901/c_compile/bin/gcc
-- Check for working CXX compiler: /home/w546901/c_compile/bin/gcc -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /home/w546901/c_compile/bin/gcc
-- Check for working C compiler: /home/w546901/c_compile/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- CMake version 3.11.4
-- xgboost VERSION: 1.0.0
-- Setting build type to 'Release' as none was specified.
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - found
-- Looking for fopen64
-- Looking for fopen64 - not found
-- Looking for C++ include cxxabi.h
-- Looking for C++ include cxxabi.h - found
-- Looking for nanosleep
-- Looking for nanosleep - found
-- Looking for backtrace
-- Looking for backtrace - found
-- backtrace facility detected in default set of libraries
-- Found Backtrace: /usr/include
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- /home/r622244/17_Sep_2019/xgboost/dmlc-core/cmake/build_config.h.in -> /home/r622244/17_Sep_2019/xgboost/dmlc-core/include/dmlc/build_config.h
-- Performing Test SUPPORT_CXX11
-- Performing Test SUPPORT_CXX11 - Success
-- Performing Test SUPPORT_CXX0X
-- Performing Test SUPPORT_CXX0X - Success
-- Performing Test SUPPORT_MSSE2
-- Performing Test SUPPORT_MSSE2 - Success
-- Found OpenMP_C: -fopenmp (found version "4.0")
-- Found OpenMP_CXX: -fopenmp (found version "4.0")
-- Found OpenMP: TRUE (found version "4.0")
-- Performing Test XGBOOST_MM_PREFETCH_PRESENT
-- Performing Test XGBOOST_MM_PREFETCH_PRESENT - Success
-- Performing Test XGBOOST_BUILTIN_PREFETCH_PRESENT
-- Performing Test XGBOOST_BUILTIN_PREFETCH_PRESENT - Success
-- Found OpenMP_C: -fopenmp
-- Found OpenMP_CXX: -fopenmp
-- Found OpenMP: TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: /home/r622244/17_Sep_2019/xgboost/build
======================== END ==========================

**Comment by pallabkarmakar** [comment]
@trivialfis 

While building latest version using gcc 5.2.0 i got lot of errors. 

Some glimpse of error log is 


librabit.a(allreduce_robust.cc.o): In function `_GLOBAL__sub_I_allreduce_robust.cc':
allreduce_robust.cc:(.text.startup+0xc): undefined reference to `std::ios_base::Init::Init()'
allreduce_robust.cc:(.text.startup+0x13): undefined reference to `std::ios_base::Init::~Init()'
librabit.a(allreduce_robust.cc.o):(.data.rel.ro._ZTIN5rabit6engine15AllreduceRobustE[_ZTIN5rabit6engine15AllreduceRobustE]+0x0): undefined reference to `vtable for __cxxabiv1::__si_class_type_info'
collect2: error: ld returned 1 exit status
make[2]: *** [../xgboost] Error 1
make[1]: *** [CMakeFiles/runxgboost.dir/all] Error 2
make: *** [all] Error 2


Compiler version:
 gcc (GCC) 5.2.0

**Comment by pallabkarmakar** [comment]
This is coming during objxgboost build 
[ 95%] Built target objxgboost
[ 96%] Building CXX object CMakeFiles/runxgboost.dir/src/cli_main.cc.o
[ 98%] Linking CXX executable ../xgboost

**Comment by trivialfis** [comment]
Undefined references to standard libraries ...

I searched mu linux and got this one: http://micheleandreoli.org/public/Software/mulinux/news.html

Am I correct?  If so I'm afraid you won't be getting many helpful suggestion here with a 2004 distribution ...

**Comment by pallabkarmakar** [comment]
It would great if i got some inputs . Got so many error , looks like some serious issue at source code. Does it compatible with gcc 5.2.0 ? if not then which version of gcc it supports ? I know it should be >5.0

**Comment by trivialfis** [comment]
@pallabkarmakar We have tests against gcc 5.2.0.  I don't think it's the problem of source code.  Your error message shows linking error inside `stdlib` shipped along with your compiler ...

**Comment by trivialfis** [comment]
@pallabkarmakar Closing as I believe it's due to errors in compiler toolchain.  If you want to play with old distributions for fun, nix or guix is a good way of setting up an isolated environment and build your own toolchains (to me at least, other might argue for more popular choices like docker).
