### ISSUE TITLE
sample_weight crashes the interpreter

### ISSUE THREAD

**Issue by kjanko** [dmlc/xgboost#4869]
Hi all,

today I encountered an issue with xgboost that crashed my python interpreter. I tried to  train a multi-class classifier with a sparse matrix. Without sample_weight, the process goes fine. When I set the parameter to the weights that I generated using sklearn.utils.class_weight, It crashed the interpreter.

Here's a sample code:

```
class_weights = list(class_weight.compute_class_weight('balanced', np.unique(y), y))
# X is a sparse csr_matrix
X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.15, random_state=1338)

xgb = XGBClassifier(n_estimators=2000, max_depth=12,
                    objective='multi:softprob', nthread=4, 
                    seed=1338, gamma=5.5, learning_rate=0.0001,
                   colsample_bytree=0.5, subsample=0.5,
                   num_class=len(np.unique(Y_train))

xgb.fit(X_train, Y_train, sample_weight=class_weights)
```

I'm thinking it could be due to the train test split, which could remove some low-occurrence classes and then we get a size mismatch - however this should not crash the interpreter. I will update the issue as I get more information.

**Comment by trivialfis** [comment]
@kjanko Could you please provide a self-contained script?

**Comment by trivialfis** [comment]
Also XGBoost version.

**Comment by kjanko** [comment]
```
from xgboost.sklearn import XGBClassifier
from scipy import sparse, stats
from scipy.sparse import dok_matrix, csr_matrix, vstack
import numpy as np
from sklearn.utils import class_weight
test_mtx = dok_matrix((10, 10), dtype=np.int)

test_mtx[0, 1] += 1
test_mtx[1, 4] += 3
test_mtx[2, 3] += 7
test_mtx[3, 7] += 5
test_mtx[4, 8] += 5
test_mtx[5, 5] += 5
test_mtx[6, 2] += 5
test_mtx[7, 9] += 5
test_mtx[8, 7] += 15
test_mtx[9, 2] += 21

y = [1, 2, 3, 4, 1, 2, 2, 5, 1, 1]

xgb = XGBClassifier(n_estimators=2000, max_depth=12,
                    objective='multi:softprob', nthread=4, 
                    seed=1338, gamma=5.5, learning_rate=0.0001,
                   colsample_bytree=0.5, subsample=0.5,
                   num_class=len(np.unique(y)))
				   
class_weights = list(class_weight.compute_class_weight('balanced', np.unique(y), y))
				   
xgb.fit(test_mtx, y, sample_weight=class_weights)

```

Here is a minimal, reproducible example.

This is the error

> Kernel error:
> In: c:\users\administrator\desktop\xgboost\include\xgboost\../../src/common/span.h,     line: 489
>         const float &xgboost::common::Span<const float, -1LL>::operator[]<>(long long) const
>         Expecting: _idx >= 0 && _idx < size()

Version 0.82

**Comment by trivialfis** [comment]
@kjanko The weight is per-instance instead of per-class.  Will add a check for that for better diagnostic message.

**Comment by kjanko** [comment]
@trivialfis I see - although it still shouldn't crash the interpreter but return an error message.

**Comment by trivialfis** [comment]
#4872 .

**Comment by trivialfis** [comment]
It should not crash though, seems to be multiple exceptions being thrown due to OpenMP loop.

**Comment by hcho3** [comment]
@trivialfis All exceptions must not be allowed to escape OpenMP regions. Any uncaught exception inside OpenMP loops will cause the whole program to crash. See https://software.intel.com/en-us/blogs/2009/11/05/openmp-and-exceptions.

DMLC-Core offers a wrapper called `dmlc::OMPException` ((link)[https://github.com/dmlc/dmlc-core/blob/d06aceb92be200c9649258da726be6bb8e4d6556/include/dmlc/common.h#L53-L87]), where all exceptions are caught inside the OpenMP region and stored in a class variable.

Usage:
```cpp
dmlc::OMPException omp_exc;
#pragma omp parallel for num_threads(nthread)
for (int i = 0; i < n; ++i) {
  omp_exc.Run([&] {
    // Loop body goes here
  });
}
omp_exc.Rethrow();
```

See (here)[https://github.com/apache/incubator-mxnet/blob/c6bb2cec919851afa04dbeda96bc1cab588c0fba/src/io/iter_image_recordio_2.cc#L346-L362] for an example of `dmlc::OMPException` in the MXNet codebase.

**Comment by trivialfis** [comment]
@hcho3 Thanks for the pointer.  Let me see how can I put it into our `Transfrom` function.

**Comment by hcho3** [comment]
Can we close this now?
