### ISSUE TITLE
GLIBCXX and CXXABI not found by libxgboost.so

### ISSUE THREAD

**Issue by pallabkarmakar** [dmlc/xgboost#4870]
Hi,

I am working on C++ project where I need to use xgboost. I am trying to run C/C++ demo c-api, which is provided with xgboost git hub source code. But while running got below error regarding GLIBCXX and CXXABI not found. However Xgboost and demo/c-api compiled successfully.

============= LOG ===============
./sample: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.7' not found (required by /xgboost/lib/libxgboost.so)
./sample: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /xgboost/lib/libxgboost.so)
./sample: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /xgboost/lib/libxgboost.so)
./sample: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by /xgboost/lib/libxgboost.so)
./sample: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by /xgboost/lib/libxgboost.so)
./sample: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /xgboost/lib/libxgboost.so)
./sample: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.19' not found (required by /xgboost/lib/libxgboost.so)
./sample: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /xgboost/lib/libxgboost.so)
================================

GCC/G++ version : 5.2.0
Cmake version : 3.11.4
Xgbbost version: latest
Compiled demo c-api with G++ -std=c++11

-bash-4.1$ strings /xgboost/lib/libxgboost.so | grep GLIBCXX
GLIBCXX_3.4.10
GLIBCXX_3.4.20
GLIBCXX_3.4.18
GLIBCXX_3.4.9
GLIBCXX_3.4.11
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.19
GLIBCXX_3.4.21
GLIBCXX_3.4

-bash-4.1$ echo $LD_LIBRARY_PATH
/usr/local/lib64/:/xgboost/lib

Let me know if you need anymore details.

**Comment by trivialfis** [comment]
Related to #4865. 

@pallabkarmakar Please find a well maintained distribution. ;-)  Your toolchain is broken.
