### ISSUE TITLE
why split point is not in the scope of the feature value?

### ISSUE THREAD

**Issue by jackyhawk** [dmlc/xgboost#4871]
As for the split point of some feature, it seems that it may be not in the scope of the feature value.
For example, we have one feature which is the similarity between user and item, and it should be between 0~1 ( for some precision reason of sqrt, there would be some similarity just a little bigger that 1,such as 1.000002)

and we found that xgboost choose 2.0 as its split point (and we have scanned all the values for that feature in all the samples, and no one would be bigger that 1.01)

and the split point as follows:
[sim_u_tags-d_tags<2.0] yes=7,no=8,missing=8,gain=134521.0,cover=3099832200.0 

Can someone give some advice, thanks very much?

**Comment by trivialfis** [comment]
@jackyhawk Could you please provide a reproducible script and possibly a sample dataset?

**Comment by trivialfis** [comment]
> gain=134521.0,cover=3099832200.0

That seems unusual.

**Comment by jackyhawk** [comment]
It seems when that feature is missing, then it would assign the split point as 2.0 ( I am confused why it doesn’t choose the max_value of that feature as split point, instead it choose 2.0 as the split point (although 2.0 is much bigger that my max value in my case)

**Comment by trivialfis** [comment]
@jackyhawk It would be nice if you can provide a self-contained reproducible example so we can look into it later when available. ;-)

**Comment by hcho3** [comment]
@jackyhawk It is actually an expected behavior. The split value of 2 was chosen so that the split threshold would be larger than all values present in the training dataset. This way, the only data points that would go to the right child node are ones with missing values.
