### ISSUE TITLE
Loading model from disk uses cpu_predictor instead of gpu_predictor

### ISSUE THREAD

**Issue by sonalipatil** [dmlc/xgboost#4878]
I noticed similar discussion on using XGBoost with R on https://discuss.xgboost.ai . However, with python I am still facing the issue. At the time of training GPU was utilized and at the time of prediction XGBoost is using CPU. Note that I used incremental training. I have tried both scikit-learn wrappers and calling XGBoost api directly. 

My dataset size is very large so I am using np.memmap to load the test data first and then copying the data in batches to the memory and then calling predict_proba function. The following is my code snippet 

`import xgboost as xgb

params = { 'objective' : 'binary:logistic','learning_rate': 0.3,"predictor": "gpu_predictor",
                'max_depth': 6, 'subsample':0.8,'n_estimators':500,'min_child_weight':1, 'tree_method':'gpu_hist',
                'gpu_id': 0, 'nthread': 0, 'verbosity': 3, 'max_bin':16,'random_state':0} 

loaded_model = xgb.XGBClassifier(**params)
		
loaded_model.load_model(saved_model)

while batch_index <tot_size:
  ...
#make a local copy of feature batch
...
    batch_proba2 = loaded_model.predict_proba(features)
`

The same set of parameters were used at the time of training and GPU was getting utilized.

**Comment by sonalipatil** [comment]
Just an update, when I loaded the pickled model for every batch iteration with 'verbosity':3 flag then it started printing out the debug messages that it's running on GPU. I am just bit confused why "watch" command on "nvidia-smi" doesn't show any GPU usage. Is the requirement of loading the model at every iteration intentional ?  Somehow the model gets reset when loaded only once and called at every iteration.

**Comment by trivialfis** [comment]
Labelled as blocking.  I have to get these model io right before 1.0

**Comment by trivialfis** [comment]
For a quick fix, you can set the gpu predictor manually.

**Comment by trivialfis** [comment]
Closing.  See new document for predictor and IO.
