### ISSUE TITLE
XGboost don't support some GPU well.

### ISSUE THREAD

**Issue by appleyuchi** [dmlc/xgboost#4881]
With the **same code and same datasets** in:
https://www.kaggle.com/xhlulu/ieee-fraud-xgboost-with-gpu-fit-in-40s

Kaggle Notebook with  Tesla P100-PCIE-16GB,complete training in less than **40s** 

Colab   Notebook with NVIDIA Corporation GK210GL [Tesla K80] (rev a1):
complete training in **15 minutes.**

What I want to say is:
**Does some GPU support xgboost NOT very well?**

**Comment by trivialfis** [comment]
@appleyuchi That requires serious benchmarking across different GPUs and with different shapes of dataset.  It might be K80 doesn't have enough shared memory for building histogram, I'm not sure.

**Comment by appleyuchi** [comment]
@trivialfis 
Thanks for your replies.
I have used the **same datasets and same code.**
I think it's rigorous and strict comparision.

And NO I/O effect,because all datasets are temporarily stored in memory.
.

**Comment by hcho3** [comment]
@appleyuchi From [this page](https://en.wikipedia.org/wiki/CUDA), you can look up the compute capability of NVIDIA GPUs.

* Tesla K80: **3.7** (Kepler)
* Tesla P100: **6.0** (Pascal)

While XGBoost supports older generation cards, it is likely that you'll see performance improvement when using later generations.

**Comment by appleyuchi** [comment]
@hcho3 
Thanks for your replies.
I have no knowlege on cudn.
Could you tell me which series will supoort XGBoost Well and which will NOT?
Thanks~!

**Comment by rongou** [comment]
We haven't really done benchmarks across different generations of GPUs. You can look at this page (https://en.wikipedia.org/wiki/Nvidia_Tesla) to compare the specs between K80 and P100. Based on clock speed and memory bus width/bandwidth etc., you can see the P100 is a much more capable GPU than the K80, so perhaps the numbers you got are not that surprising.

Based on personal experience, gpu memory bandwidth seems to be the biggest factor for xgboost training performance. The V100 seems to be very fast for xgboost; the P100 is probably close behind. The T4 is a good alternative with much lower cost. Anything older than Pascal would probably be relatively slow (still faster than CPU though :).

**Comment by hcho3** [comment]
@rongou So is it fair to say that P100/V100 are more powerful than K80 or other Kepler cards?

**Comment by rongou** [comment]
@hcho3 yeah in general each new generation should perform better than the last, so V100 > P100 >> K80. The T4 is sort of an exception since it's a low cost card targeted at "inference".

BTW the G4 instance is available now, we probably should switch to that for GPU tests: https://aws.amazon.com/blogs/aws/now-available-ec2-instances-g4-with-nvidia-t4-tensor-core-gpus/

**Comment by hcho3** [comment]
@rongou That's good news! It's cheaper than P2/P3 and also uses new microarchitecture.

@appleyuchi For now, it would be safe to assume that newer NVIDIA cards would outperform older ones.

**Comment by appleyuchi** [comment]
@hcho3
Thank you~!
Got it~!
