### ISSUE TITLE
Was support for HDFS dropped?

### ISSUE THREAD

**Issue by thvasilo** [dmlc/xgboost#4886]
About a year ago when I was last doing distributed XGBoost experiments I was able to build from source with the `USE_HDFS=ON` option so that I could run distributed training from the cli.

I can't find that option in CMake any more and trying to run XGBoost applications causes errors like 

```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hadoop/io/DataOutputBuffer
```

Is there some process I'm missing to build with HDFS support? Is using Spark the only way to run distributed training now?

**Comment by trivialfis** [comment]
The option is in `dmlc-core` instead of XGBoost,  but since `dmlc-core` is submodule so it should be effective.  I'm not sure about the error. @CodingCat Is there additional things we need to do in XGBoost for supporting HDFS in XGBoost?

**Comment by trivialfis** [comment]
I just verified the `USE_HDFS` parameter is effective in compilation.

**Comment by CodingCat** [comment]
> The option is in `dmlc-core` instead of XGBoost, but since `dmlc-core` is a submodule so it should be effective. I'm not sure about the error. @CodingCat Is there any additional things we need to do in XGBoost for supporting HDFS?

as far as I know, no,

**Comment by trivialfis** [comment]
Let me take a closer look tomorrow.

**Comment by thvasilo** [comment]
Possible root cause: https://github.com/dmlc/dmlc-core/pull/262#issuecomment-513555466

Marked as an [issue](https://github.com/dmlc/dmlc-core/issues/552) by @hcho3 back in August.

**Comment by hcho3** [comment]
Closing this, the issue being tracked in https://github.com/dmlc/dmlc-core/issues/552
