### ISSUE TITLE
Is dmlc-core and rabit required to Include while compiling for demo/c-api build

### ISSUE THREAD

**Issue by pallabkarmakar** [dmlc/xgboost#4892]
Hi,

Do we really need to include /dmlc-core/include and /rabit/include to build demo/c-api.

I have included /include directory though and able to compile and run the executable.

I am using xgboost for plane C++ linux project. 

During Xgboost cmake rabit and dmlc-core build was disabled as i only need for linux system.

Could you please help me if those include really required or not?

**Comment by hcho3** [comment]
No, your application does not need to include these headers. XGBoost codebase will include them internally for necessary functionalities.

**Comment by pallabkarmakar** [comment]
@hcho3 
Thanks for your reply. 


Yes i agree with you. dmlc-core and rabit is no longer needed to use xgboost.so in linux based C++ project.
Only following INCLUDE_DIR is sufficient in makefile. However we need to use LIB_DIR and -lxgboost.

INCLUDE_DIR=-I$(XGBOOST_ROOT)/include 


Correct me if my understanding is wrong.

**Comment by hcho3** [comment]
You are right. However, we recommend that you use CMake if possible.
