### ISSUE TITLE
Refactor to eliminate relative include paths into source dir

### ISSUE THREAD

**Issue by codingforfun** [dmlc/xgboost#4893]
There are a lot of places in the code where the following pattern of including paths outside the current dirs directory tree is used.
https://github.com/dmlc/xgboost/blob/82ee2317e80f93465685529e1ab9acff52b683c7/include/xgboost/data.h#L22-L24
https://github.com/dmlc/xgboost/blob/82ee2317e80f93465685529e1ab9acff52b683c7/include/xgboost/gbm.h#L24
I think this is very bad practice and I don’t understand the rational behind this. 
E.g. if you think `span.h` is something considered a private implementation detail than it should get included only by *.cc  files within the src/ tree. 
If you ever need to include this into some of the headers in `include/` it’s probably not a private implementation detail anymore but something you need to share with who ever is using includes from the `include/` dir. In that case `span.h` should also live in `include/`.

This anti-pattern repeats throughout a many sources, not only in xgboost, but also in rabit.

**Comment by trivialfis** [comment]
Yep.  It needs cleaning.

**Comment by hcho3** [comment]
+1
