### ISSUE TITLE
[RFC] Expose C++ headers as part of the CMake target

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#4894]
For more context, see discussion at https://discuss.xgboost.ai/t/is-there-a-c-api-document-and-usage-examples/592/10.

@codingforfun suggested that the C++ headers in XGBoost should be exposed to 3rd-party applications via the CMake target `xgboost`. I initially objected because future refactoring would change C++ interfaces, but @codingforfun replied that API stability is not as important in his use case:

> Also I don’t think your concerns about API stability really matter from the perspective of a project directly accessing the C++ interface.
> * ABI stability – I think this is the number one reason for C-Interfaces. You don’t have that anyway when using C++.  [My note: it means that C++ users will re-compile XGBoost periodically.]
> * **A lot of stuff that can be done in C++ easily is PITA or impossible using the C-Interface. This outweights the need to refactoring for interface changes.** [emphasis mine] Example: Currently we
>    - Derive from DataSource to feed data in memory into XGB
>    - Derive from ObjFunction to define our own objective
>    - Derive from Metric to define our own metric
>    - Derive from dmlc::Stream to get the trained classifier into QByteArray

I'm now persuaded that the C++ headers in XGBoost should be exposed as part of the CMake target, on the condition that we clearly document future possibility of API changes. ("We do not make any guarantee about API stability, so your application may not work with future XGBoost releases".) In our experience, we tend to be less conservative when it comes to changing C++ interfaces, compared to changing C API.

cc @trivialfis @RAMitchell @chenqin @CodingCat @thvasilo Let me know what you think.

**Comment by trivialfis** [comment]
Thanks for bringing this up.  I have the thought to build a clean c++ interface with feature parity with Python.  If someone wants to give it a go I'm happy to help.

**Comment by hcho3** [comment]
@trivialfis This proposal is different from building a Python-like interface in C++. It is a simple change in CMakeLists.txt to include C++ headers in the CMake target `xgboost`. Let me create a separate thread about Python-like interface in C++.

**Comment by trivialfis** [comment]
Cool. Still agreed.  Actually I can submit a PR for that since I wrote most of the CMake  scripts...  As long as we don't promise any compatibility for it.

**Comment by hcho3** [comment]
@trivialfis Thanks. That would be great. Let's address this RFC first, and then we can later tackle #4895.

**Comment by codingforfun** [comment]
I think to make this really usable it’s necessary to first/also fix #4893.
I did patch CMakeLists.txt of XGB in my build process to include the C++ interface, but since of #4893 it requires ugly hacks because otherwise the installed include from `${PREFIX}/include/` aren’t usable.

**Comment by trivialfis** [comment]
@codingforfun Don't worry about that.  Will work on it tomorrow.
