### ISSUE TITLE
[BUG] `DMatrix` loosing feature names when created with `cudf`. 

### ISSUE THREAD

**Issue by VibhuJawa** [dmlc/xgboost#4901]
#### `DMatrix` looses feature names when created with `cudf`

We seem to loose feature names when creating dmatrix from a cudf dataframe.  

This can lead to silent as the order of columns might change. 

#### Example:

```python
import xgboost as xgb
import cudf
import pandas as pd
```

##### Cudf output:

```
xgb.DMatrix(cudf.DataFrame({'x':[1,2,3]}),cudf.DataFrame({'y':[1,2,3]})).feature_names
```
```
['f0']
```

##### Pandas Output
```
xgb.DMatrix(pd.DataFrame({'x':[1,2,3]}),pd.DataFrame({'y':[1,2,3]})).feature_names
```

```
['x']
```

#### Additional Context: 

We can probably modify the `pandas` class that extracts the feature names to work with `cudf` too.

https://github.com/dmlc/xgboost/blob/2fa8b359e06783ed5824824ec8ffb32c1d4e1383/python-package/xgboost/core.py#L289-L292

**Comment by trivialfis** [comment]
Thanks, will look into it.
