### ISSUE TITLE
question about quantile.h

### ISSUE THREAD

**Issue by daiyl0320** [dmlc/xgboost#491]
hi,
   When i run a large data chunk, the program is core and print errmsg as: quantile: too many large chunk. I want to know what is the limit of the large chunk size? And when the program is exit(). It is exit with core file. There may be some bug in xgboost with global variables when destruct.

**Comment by tqchen** [comment]
This is a bug that is supposed to fixed in the master branch. There is no limit on data you can process, the error was triggered by a bug.

Please use the latest version in github. If you still get the error ,please post the dumped message in this issue.

**Comment by daiyl0320** [comment]
Hi, tianqi,
I checkout the latest master branch. The program is exit without core dump, but I find the memory is used much more than the old version training with the same data. Could you explain that what is the relation between the feature number and the memory use. The data i am trying to train is nearly 20GB and the feature number is nearly 1million.

thanks.

**Comment by tqchen** [comment]
closing for now due to inactive status, feel free to reopen
