### ISSUE TITLE
How to prescribe a limit to response value according to its physical meaning?

### ISSUE THREAD

**Issue by melonki** [dmlc/xgboost#4912]
Dear Contributors and Members,
I am trying to apply XGBoost to the assessment of environmental risk, where each variables should be within the zone of reasonableness. For example. the concentration of a certain pollutant should not be less than 0. However, in my model, I got a prediction with few negative values. Is there any way to prescribe a limit to response value when training a model? Or the only thing I can do is change these negative values to zero.

I would greatly appreciate any explanation or suggestions in this matter.

PS: I’m using xgboost 1.0.0.1 in R 3.6.1.

With kind regards,
Melonki

**Comment by hcho3** [comment]
See https://discuss.xgboost.ai/t/how-to-prescribe-a-limit-to-response-value-according-to-its-physical-meaning/1174

**Comment by melonki** [comment]
> See https://discuss.xgboost.ai/t/how-to-prescribe-a-limit-to-response-value-according-to-its-physical-meaning/1174

Got it. Thank you.
