### ISSUE TITLE
sklearn fit silently drops or errors when length of eval_set and sample_weights do not match

### ISSUE THREAD

**Issue by mmccarty** [dmlc/xgboost#4913]
[XGBModel.fit](https://github.com/dmlc/xgboost/blob/master/python-package/xgboost/sklearn.py#L376) packages the `evals` into a list of `DMatrix` objects by iterating over a range generated by the length of the given `eval_set`.  However, when the user provides `eval_set=[(x1, y2), (x2, y2)], sample_weight_eval_set=[weight1]` the `evals` list will have silently dropped the second set.  When the user provides `eval_set=[(x1, y2)], sample_weight_eval_set=[weight1, weight2]` an index exception is raised.

We discovered this when discussing and testing a [PR](https://github.com/dask/dask-xgboost/pull/54) adding `early_stopping` to `dask-xgboost`.  We are wondering what is the right thing to do in this case?  Raise an exception?  Or do nothing?

**Comment by trivialfis** [comment]
@mmccarty Ah I see.  Will fix it.  Thanks for the issue. ;-)

**Comment by trivialfis** [comment]
Just by the way, we adopted that dask interface into xgboost itself lately.

**Comment by mmccarty** [comment]
@trivialfis Thank you!  Looking forward to trying out native dask.

**Comment by trivialfis** [comment]
Yup.  Still some pending PRs for bug squashing since it's relatively new. But stay tuned.

**Comment by trivialfis** [comment]
See https://github.com/dmlc/xgboost/issues/5152 I want to remove the validation data set parameter and replace it with call back functions.
