### ISSUE TITLE
[CI] Jenkin CI server (xgboost-ci.net) down for emergency maintenance

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#4921]
All Jenkins jobs are now failing due to broken SSL connections, so [`git clone` is failing](https://xgboost-ci.net/blue/organizations/jenkins/xgboost/detail/PR-4918/6/pipeline) and also [S3 upload is failing](https://xgboost-ci.net/blue/organizations/jenkins/xgboost-win64/detail/PR-4918/3/pipeline/73). I suspect this has to do with outdated software packages for the worker images we are using.

At any rate, I will need to re-generate the worker images (AMIs), so I'm shutting down the server ~for a few hours~ for a day. I will do my best to bring the server back to normal.

@dmlc/xgboost-committer

**Comment by hcho3** [comment]
**"Wouldn't Docker solve the issue of outdate packages"?** At the Checkout stage, the CI worker uses the system Git to checkout the XGBoost repository. The Docker image is not available yet, since the `Dockerfile` is itself part of the repository. Hence, over time, we are still affected by outdated system packages.

**Comment by trivialfis** [comment]
Thanks for looking into this.

**Comment by hcho3** [comment]
Update: `git clone` is now working correctly.

https://xgboost-ci.net/blue/organizations/jenkins/xgboost/detail/PR-4924/2/pipeline/12

**Comment by hcho3** [comment]
Note to myself: List of software packages to set up Linux workers.
* System-wide update (`apt-get upgrade`)
* Python 3.x
* `awscli` Python package
* Git
* Docker CE
* OpenJDK 8
* CUDA (for GPU only)
* NVIDIA docker (for GPU only)

**Comment by hcho3** [comment]
Update: S3 transfer is now working too.

https://xgboost-ci.net/blue/organizations/jenkins/xgboost-win64/detail/PR-4924/1/pipeline/71/

**Comment by hcho3** [comment]
It looks like the server is back to normal. However, I will keep a close eye on it today and tomorrow to see everything is all right.

Note. As a bonus, the Linux GPU workers are now using shiny new Turing GPUs ([G4 instances](https://aws.amazon.com/ec2/instance-types/g4/))
