### ISSUE TITLE
Xgboost install error with GPU in R

### ISSUE THREAD

**Issue by hsuanmeng** [dmlc/xgboost#4922]
When I use 
mkdir build
cd build
cmake .. -DUSE_CUDA=ON -DR_LIB=ON
make install -j

and I got this error

R-package/CMakeFiles/xgboost-r.dir/flags.make:11: *** missing separator. Stop.
make[1]: *** [CMakeFiles/Makefile2:269: R-package/CMakeFiles/xgboost-r.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

What should I do ?

**Comment by hcho3** [comment]
Which OS is this?

**Comment by hsuanmeng** [comment]
CentOS with version 7.14

**Comment by hcho3** [comment]
@hsuanmeng I cannot reproduce the issue. I just tried the same command inside a [Docker container with CentOS 6](https://github.com/dmlc/xgboost/blob/master/tests/ci_build/Dockerfile.gpu_build#L2), and XGBoost compiles successfully. The issue seems specific to your machine.

**Comment by hcho3** [comment]
Is using Ubuntu an option? Alternatively, a Docker container?

**Comment by hsuanmeng** [comment]
@hcho3 
The environment was built by another partner, so it seem cant not change to Ubuntu. :(
Or do you think is cuda version make it error? my version is 10.0.0

**Comment by hcho3** [comment]
@hsuanmeng I've seen 10.0 cause issues before. Try 9.2 or 10.1.

**Comment by hsuanmeng** [comment]
@hcho3 but I can install python on it with cuda 10.0. hmm very odd.....

**Comment by trivialfis** [comment]
Any update?

**Comment by trivialfis** [comment]
ping @hsuanmeng

**Comment by hsuanmeng** [comment]
@trivialfis I will try to update cuda 10.1 this week, hope I have a good news.

**Comment by trivialfis** [comment]
Just in case, I recently tested this with master branch code on 9.2 and 10.1 with both gcc 7 and 8.  Let me know if you bump into any issue, I will try to reproduce it from my end.

**Comment by haha150** [comment]
i got similar issue with installing xgboost with gpu with cuda version 9.1 and 10.1

```
[ 94%] Building CUDA object src/CMakeFiles/objxgboost.dir/tree/updater_gpu_hist.cu.o
Error: Internal Compiler Error (codegen): "there was an error in verifying the lgenfe output!"

make[2]: *** [src/CMakeFiles/objxgboost.dir/tree/updater_gpu_hist.cu.o] Error 2
make[2]: *** Waiting for unfinished jobs....
src/CMakeFiles/objxgboost.dir/build.make:829: recipe for target 'src/CMakeFiles/objxgboost.dir/tree/updater_gpu_hist.cu.o' failed
CMakeFiles/Makefile2:369: recipe for target 'src/CMakeFiles/objxgboost.dir/all' failed
make[1]: *** [src/CMakeFiles/objxgboost.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

how can i fix it?

running ubuntu 18.04
gcc 6 with cuda 9.1
cmake 3.15

**Comment by trivialfis** [comment]
Maybe try cuda 9.2 or 10.1?

**Comment by haha150** [comment]
I did try with 10.1 and 9.1 as mentioned in my comment...

**Comment by trivialfis** [comment]
@haha150 I usually just do:
``` bash
cmake ../xgboost/ -DUSE_CUDA=ON -DUSE_NCCL=ON -DUSE_OPENMP=ON -DGOOGLE_TEST=ON -DR_LIB=ON -DCMAKE_CXX_FLAGS="-Wall"
makef
```
and everything works.  I use this with multiple versions of Fedora and Ubuntu for over a year by now ...  I can't really help with compiler internal error.  Try posting an issue on nv's form: https://devtalk.nvidia.com/
