### ISSUE TITLE
Monotonicity Implementation changed - creating non-monotonic models

### ISSUE THREAD

**Issue by s-ravichandran** [dmlc/xgboost#4923]
https://github.com/dmlc/xgboost/blob/095de3bf5f9febba9908637197873630021c733a/src/tree/updater_colmaker.cc#L113

The constraints set for monotonicity on each node seem to be set in a different way than in release 0.72 and this is causing non-monotonic models to be built in my case. Upon closer look, it appears that the order in which the constraints on nodes are set has changed. In release 0.72, there was the SetChild method that was called, which had the id of the parent of the nodes in qexpand as the first parameter. However, in the current implementation, the AddSplit method takes in the id of the current node as the parameter. And as far as I can see, there is no change in the implementation logic. Could someone let me know why the function call has been changed with a different argument in the new version?

Thanks!

**Comment by trivialfis** [comment]
Could you provide a reproducible script?

**Comment by trivialfis** [comment]
Looking.

**Comment by s-ravichandran** [comment]
Apologies for the delay in responding. This was due to a gap in understanding in the AddSplit method implementation.
