### ISSUE TITLE
xgboost C api doesn't produce same results as Python

### ISSUE THREAD

**Issue by derrickj12** [dmlc/xgboost#4934]
I have a very simple dataset (30 rows, 32 columns).

I wrote a Python program to load the data and train an XGBoost model, then save the model to disk.

I also compiled a C++ program that uses libxgboost (C api) and loads the model for inference.

When using the SAME saved model, Python and C++ give different results for the same input (a single row of all zeros).

xgboost is 0.90 and I have attached all files (including the numpy data files) here:

https://www.dropbox.com/s/txao5ugq6mgssz8/xgboost_mismatch.tar?dl=0

Here are the outputs of the two programs (the source of which are in the .tar file):

#The Python program
```
$ python3 jl_functions_tiny.py
Loading data
Creating model
Training model
Saving model
Deleting model
Loading model
Testing model
[587558.2]
```

#The C++ program
```
$ ./jl_functions
628180.062500
```

**Comment by trivialfis** [comment]
@derrickj12 You set the missing value to `0.0`:
``` c++
    rc = XGDMatrixCreateFromMat(input, 1, xdim, 0.0, &dmat);
```
Default should be `NaN`.
