### ISSUE TITLE
Windows 32-bit package unavailable on PyPI and PyPI description outdated

### ISSUE THREAD

**Issue by okke-formsma** [dmlc/xgboost#4946]
Hi,

First of all, thanks for XGBoost, it's amazing software.

We were elated when installing xgboost from pypi was working under Windows. This made our development experience much easier. Unfortunately the windows builds have been discontinued according to the pypi page: https://pypi.org/project/xgboost/ 

> Windows users: pip installation may not work on some Windows environments, and it may cause unexpected errors.
> Installation from pip on Windows is therefore currently disabled for further investigation; please install from Github instead.

I can't find a ticket related to this issue on this issue tracker, so I'm uncertain if this is something that will be fixed in the future. Is this on the roadmap somewhere?

**Comment by trivialfis** [comment]
@hcho3 How do I update the project description on PyPI.

**Comment by okke-formsma** [comment]
Just to clarify, this is not just a documentation issue on PyPI; I'm unable to install the windows package for xgboost==0.90

**Comment by trivialfis** [comment]
Oh ... @RAMitchell Could you please help taking a look into this?

**Comment by hcho3** [comment]
@trivialfis I am currently the maintainer of the XGBoost package on pypi.org. Let me update the description.

@okke-formsma The documentation is outdated. Now users of 64-bit Windows are able to run `pip install xgboost`. Unfortunately, we do not plan to support Python 2.6 or 32-bit Windows.

**Comment by hcho3** [comment]
@trivialfis It looks like the [description](https://github.com/dmlc/xgboost/blob/master/python-package/README.rst) was updated after 0.90 release. The next release should have the updated description.
