### ISSUE TITLE
How to provide instance weights in the CLI version?

### ISSUE THREAD

**Issue by ogru** [dmlc/xgboost#4950]
Hello everyone, 

In the CLI version, how do we provide instance weights? 

For example, if the training data is in DMatrix format (Saved as binary), can you do something like:
```xgboost Config.txt weights=myweights.txt```, or should you modify the DMatrix via python?

If there is a better way, please advise.

Many thanks

**Comment by trivialfis** [comment]
@ogru Sorry for late reply, see https://xgboost.readthedocs.io/en/latest/tutorials/input_format.html#instance-weights .
