### ISSUE TITLE
Improve binary serialization for DMatrix::MetaInfo.

### ISSUE THREAD

**Issue by trivialfis** [dmlc/xgboost#4956]
As discussion from @hcho3 and @RAMitchell in #4763, with new objective functions requiring more fields in metainfo, we need to store the binary object in a maintainable way.  Currently we write only the data to this binary file, while in the future we can add a header table for each field, with corresponding offsets.  This way we can lookup the header while reading the binary, and hence easier to maintain compatibility.

WDYT?

**Comment by hcho3** [comment]
I like the idea, given that JSON serialization of DMatrix would be
infeasible due to storage. Do you have an estimate of the amount of effort
your proposal will take?

**Comment by trivialfis** [comment]
For a working PR, A week or two if things go terribly wrong?  But right now I need to sort out a regression bug we have found.

**Comment by hcho3** [comment]
@trivialfis Since you have a lot on your plate, can I try to tackle it this week?

**Comment by trivialfis** [comment]
@hcho3 Sure, feel free to let me know if there's anything I can help.
