### ISSUE TITLE
GCC 8 or 7 with Mac?

### ISSUE THREAD

**Issue by leedrake5** [dmlc/xgboost#4969]
On the [installation instructions](https://xgboost.readthedocs.io/en/latest/build.html), conflicting accounts are given for multithreading on Mac with R:

> First, obtain gcc-8 with Homebrew (https://brew.sh/) to enable multi-threading (i.e. using multiple CPU threads for training). The default Apple Clang compiler does not support OpenMP, so using the default compiler would have disabled multi-threading.
> 
> brew install gcc@8
> Now, clone the repository:
> 
> git clone --recursive https://github.com/dmlc/xgboost
> Create the build/ directory and invoke CMake with option R_LIB=ON. Make sure to add CC=gcc-8 CXX=g++-8 so that Homebrew GCC is selected. After invoking CMake, you can install the R package by running make and make install:
> 
> mkdir build
> cd build
> CC=gcc-7 CXX=g++-7 cmake .. -DR_LIB=ON
> make -j4
> make install

The page recommends installing gcc8 via brew, but then proceeds to use gcc7 in the installation instructions. I've tried both, and each throws an error at 90% that says:

> [ 90%] Building CXX object src/CMakeFiles/objxgboost.dir/tree/updater_sync.cc.o
> [ 90%] Built target objxgboost
> make: *** [all] Error 2

update - been working on this for a couple hours, and 0 progress. Not convinced it is easy to have multi-threading support on Mac with R at this time.

**Comment by trivialfis** [comment]
Technically any version above GCC 5 is fine.  But osx seems more complicated ...  @hcho3 Can we add R test on Travis?

**Comment by hcho3** [comment]
@leedrake5 Can you post the full error log? We are currently looking into ways to enable multithreading when Apple Clang is chosen as the compiler: 

@trivialfis Yes, we should definitely add R tests for OSX.

**Comment by leedrake5** [comment]
I made some terrible mistake, and couldn't get back to my 90% completion (stalled out around 50%). But I did find a way to get Open MP working with MacOS 10.15 Catalina in R. 

For anyone googling this, neither [this](https://www.btskinner.io/code/install-r-with-openblas-and-openmp-on-macos-mojave/) nor [this](https://luispuerto.net/blog/2018/01/12/install-r-100-homebrew-edition-with-openblas-openmp-my-version/) worked. 

To make this work, I had to get headers working in MacOS. First the basics in bash:

```
sudo xcodebuild -license
xcode-select --install
```

And then linking /usr/local/include/ to where Xcode 11.1 in Catalina has moved everything: 

`sudo ln -s /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/* /usr/local/include/
`

Next was installing a bunch of stuff in homebrew:

```
brew cask install xquartz
brew tap adoptopenjdk/openjdk
brew cask install adoptopenjdk9
brew install openblas
brew install llvm
brew install ccache
brew install gcc
brew install libomp
brew install libgit2
brew install openssl
brew install gettext
brew install liblwgeom
brew install gdal
brew install geos
brew install proj
brew install udunits
brew install qt
```

I then used 

`brew install r 
`
to make sure I had openblas support (much faster calculations than base R). Not all of the above brew installs are needed for homebrew R, but they will be for other packages, and best do it before package errors get thrown up later during installation. 

I then installed all the R binaries downloaded from [here](https://cran.r-project.org/bin/macosx/tools/). These all help make R work better, and most crucial is clang-8.0. 

I then modified my makevars file (~/.R/Makevars) to say the following:

> CFLAGS=-isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
> CCFLAGS=-isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
> CXXFLAGS=-isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
> CPPFLAGS="-isystem /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include"
> 
> CC=/usr/local/clang8/bin/clang
> CXX=/usr/local/clang8/bin/clang++
> CXX11=/usr/local/clang8/bin/clang++
> CXX14=/usr/local/clang8/bin/clang++
> CXX17=/usr/local/clang8/bin/clang++
> CXX1X=/usr/local/clang8/bin/clang++
> LDFLAGS=-L/usr/local/clang8/lib
> 
> SHLIB_OPENMP_CFLAGS=-fopenmp
> SHLIB_OPENMP_CXXFLAGS=-fopenmp
> SHLIB_OPENMP_FCFLAGS=-fopenmp
> SHLIB_OPENMP_FFLAGS=-fopenmp
> 
> PKG_LIBS=-L/usr/local/Cellar/gettext/0.18.3.2/lib
> PKG_CXXFLAGS = $(SHLIB_OPENMP_CXXFLAGS)
> PKG_LIBS = $(SHLIB_OPENMP_CFLAGS) $(LAPACK_LIBS) $(BLAS_LIBS) $(FLIBS)

Note that Makevars links to clang8, which was one of the binaries downloaded from CRAN. After this, I installed XGBoost in what might be an unconventional way, but allowed for parallel threading in R using OpenMP:

```
cd xgboost; cp make/minimum.mk ./config.mk; make -j4
R CMD INSTALL R-package
```

where xgboost is the directory you cloned the repository into.

I hope I've got all the steps here - I've been working at this for hours, so its possible I've missed a step. But this is the majority of what needs to be done to get things up and running for OpenMP + Mac OS Catalina.

**Comment by hcho3** [comment]
@leedrake5 Glad to hear that you sorted out the issue. I'm closing this issue, as I suspect the issue is mainly with installing R on Catalina.

**Comment by leedrake5** [comment]
Just an addendum, this process worked on both an iMac Pro with a Xeon processor & a MacBook Pro with a regular i9. I think this install solution will be the most generalizable to Macs in the future. I could never get the official one on the install page to work with either gcc7 or gcc8. 

I suspect cmake requires some special configuration to work - regular old make seems to handle things better.
