### ISSUE TITLE
[jvm-packages] xgboost code should not kill sparkcontext without knowing the reason

### ISSUE THREAD

**Issue by skale1990** [dmlc/xgboost#4970]
Hi, 

we are using this library to train the xgboost model. but whenever any exception comes, below mentioned code kills the shared spark context without any reason-
`rivate[spark] class TaskFailedListener extends SparkListener {

  private[this] val logger = LogFactory.getLog("XGBoostTaskFailedListener")

  override def onTaskEnd(taskEnd: SparkListenerTaskEnd): Unit = {
    taskEnd.reason match {
      case taskEndReason: TaskFailedReason =>
        logger.error(s"Training Task Failed during XGBoost Training: " +
            s"$taskEndReason, stopping SparkContext")
        TaskFailedListener.startedSparkContextKiller()
      case _ =>
    }
  }
}

object TaskFailedListener {

  var killerStarted = false

  private def startedSparkContextKiller(): Unit = this.synchronized {
    if (!killerStarted) {
      // Spark does not allow ListenerThread to shutdown SparkContext so that we have to do it
      // in a separate thread
      val sparkContextKiller = new Thread() {
        override def run(): Unit = {
          LiveListenerBus.withinListenerThread.withValue(false) {
            SparkContext.getOrCreate().stop()
          }
        }
      }
      sparkContextKiller.setDaemon(true)
      sparkContextKiller.start()
      killerStarted = true
    }
  }
}`

Can somebody help me to understand above code?
As per my understanding, the above code killing the sparkcontext for any exception. Since the spark context is getting killed, the whole application is down. Also it affects other spark processing happening with same spark context.

**Comment by CodingCat** [comment]
no, we cannot change this behavior
