### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by Garfield2013** [dmlc/xgboost#4983]
1. I manged to build the "xgboost.dll" on my power full Windows 10 Desktop.
2. I imported the dll into H2O-3 flow
3. When I run "AutoML" with everything else than XGBOOST disabled - It runs only for 5 secs and then generates 14 models (Is that normal)!? The models according to the confusion matrix only makes 7 error out of 834 samples (my training set is 7500 samples)... **This is better/more precise and more than 1.000 times faster than GBM which I use to run with H2O-3 for days! So Bravo to you guys!**

**and now my question:** I get the error below when I select to only run XGBOOST in the menu in H2O-3 flow. I only select the train + validation frames + response column and the click "build model" (I just realized the error also appears in the UI-log in H2O when I run in "AutoML" mode)?

> Btw: I have set the following 2 enviroment variables:
> Name: JRE_HOME + JAVA_HOME
> Value: C:\Program Files\Java\jre1.8.0_211

> java.lang.UnsatisfiedLinkError: ml.dmlc.xgboost4j.java.XGBoostJNI.XGDMatrixCreateFromMat([FIIF[J)I	

> 10-24 21:05:31.201 192.168.0.126:54321   30544  FJ-1-7    INFO: Rebalancing train dataset into 8 chunks.
> 10-24 21:05:31.208 192.168.0.126:54321   30544  FJ-1-7    INFO: Completing model xgboost-ca6b679e-bed4-41a0-9129-9a28f38c8cc5
> 10-24 21:05:31.209 192.168.0.126:54321   30544  FJ-1-7    ERRR: java.lang.UnsatisfiedLinkError: ml.dmlc.xgboost4j.java.XGBoostJNI.XGDMatrixCreateFromMat([FIIF[J)I
> 10-24 21:05:31.209 192.168.0.126:54321   30544  FJ-1-7    ERRR:         at ml.dmlc.xgboost4j.java.XGBoostJNI.XGDMatrixCreateFromMat(Native Method)
> 10-24 21:05:31.209 192.168.0.126:54321   30544  FJ-1-7    ERRR:         at ml.dmlc.xgboost4j.java.DMatrix.<init>(DMatrix.java:183)
> 10-24 21:05:31.209 192.168.0.126:54321   30544  FJ-1-7    ERRR:         at hex.tree.xgboost.XGBoost.hasGPU_impl(XGBoost.java:600)
> 10-24 21:05:31.209 192.168.0.126:54321   30544  FJ-1-7    ERRR:         at hex.tree.xgboost.XGBoost.hasGPU(XGBoost.java:581)
> 10-24 21:05:31.209 192.168.0.126:54321   30544  FJ-1-7    ERRR:         at hex.tree.xgboost.XGBoost.access$000(XGBoost.java:32)
> 10-24 21:05:31.209 192.168.0.126:54321   30544  FJ-1-7    ERRR:         at hex.tree.xgboost.XGBoost$XGBoostDriver.buildModel(XGBoost.java:242)
> 10-24 21:05:31.209 192.168.0.126:54321   30544  FJ-1-7    ERRR:         at hex.tree.xgboost.XGBoost$XGBoostDriver.computeImpl(XGBoost.java:237)
> 10-24 21:05:31.209 192.168.0.126:54321   30544  FJ-1-7    ERRR:         at hex.ModelBuilder$Driver.compute2(ModelBuilder.java:222)
> 10-24 21:05:31.209 192.168.0.126:54321   30544  FJ-1-7    ERRR:         at water.H2O$H2OCountedCompleter.compute(H2O.java:1417)
> 10-24 21:05:31.209 192.168.0.126:54321   30544  FJ-1-7    ERRR:         at jsr166y.CountedCompleter.exec(CountedCompleter.java:468)
> 10-24 21:05:31.209 192.168.0.126:54321   30544  FJ-1-7    ERRR:         at jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:263)
> 10-24 21:05:31.209 192.168.0.126:54321   30544  FJ-1-7    ERRR:         at jsr166y.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:974)
> 10-24 21:05:31.209 192.168.0.126:54321   30544  FJ-1-7    ERRR:         at jsr166y.ForkJoinPool.runWorker(ForkJoinPool.java:1477)
> 10-24 21:05:31.209 192.168.0.126:54321   30544  FJ-1-7    ERRR:         at jsr166y.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104)

**Comment by trivialfis** [comment]
This doesn't seem to be dmlc version of XGBoost.
