### ISSUE TITLE
Release a version for scala-2.12

### ISSUE THREAD

**Issue by WeichenXu123** [dmlc/xgboost#4985]
We need a release version for scala-2.12. So that mleap could also upgrade xgboost dependency and use scala-2.12
https://github.com/combust/mleap/pull/575

Thanks!

**Comment by Habitats** [comment]
Any update on this? 

Or any instructions available for how to build this for Scala 2.12?

**Comment by hcho3** [comment]
The [pom.xml](https://github.com/dmlc/xgboost/blob/master/jvm-packages/pom.xml) already refers to Scala 2.12.
