### ISSUE TITLE
How are you going to support compatibility with dask-cuda?

### ISSUE THREAD

**Issue by sh1ng** [dmlc/xgboost#4988]
At this moment `dask-cuda` team is not going to support pip package, only conda(https://github.com/rapidsai/dask-cuda/issues/166).
Dask and distributed version >= 2 is not compatible with `dask-cuda==0.6.0`(https://github.com/rapidsai/dask-cuda/issues/161). It looks compatible with `dask==1.2.2` `distributed==1.28.1`.

**Comment by trivialfis** [comment]
It's on pip now.  :-)
