### ISSUE TITLE
Impossible to reproduce model results

### ISSUE THREAD

**Issue by kylejn27** [dmlc/xgboost#4989]
Initially an issue on dask-xgboost with setting the `seed` parameter and getting non-deterministic results: https://github.com/dask/dask-xgboost/issues/37

I'm thinking this is a problem with xgboost 0.90 that was fixed in the latest master branch here:
https://github.com/dmlc/xgboost/commit/7e72a12871eaa0ebc46e863dabe8657e3f0557ad#diff-fd53d68e0037d3512896122d1248d969L1128

I built dmlc/xgboost from master and the issue seemed to go away, maybe a release can be cut?

**Comment by hcho3** [comment]
@kylejn27 In #4680, we are discussing about making an interim release. In the meanwhile, you can install the latest master by running

pip3 install https:/``/s3-us-west-2.amazonaws.com/xgboost-nightly-builds/xgboost-1.0.0_SNAPSHOT%2B6ec7e300bd704e0c4ed84b005dfc82d844787ba4-py2.py3-none-manylinux1_x86_64.whl

**Comment by hcho3** [comment]
Closing this, since you said that the problem was resolved in the latest master.

**Comment by kylejn27** [comment]
thanks!
