### ISSUE TITLE
scale_pos_weight feature in xgboost

### ISSUE THREAD

**Issue by DeluxeAnalyst** [dmlc/xgboost#500]
Is there a set way that the weight impacts the predicted probability of each record when doing a logistic evaluation using AUC?

The reason I ask is that our team puts a lot of value on creating a "Gains Table" showing each decile, the average response rate, average predicted response rate, and cumulative response rate. 

When using the scale_pos_weight feature I get better results, but my "Average Predicted Response Rate" becomes something unrealistic in my Gains Table, because the response rate changes from something like .02 for a record (unweighted) to .60 (weighted). The result is that for the top 1st decile, the average predicted response rate is like 60%.

I was wondering if there was some calculation I can do on my own, that would keep the rank order created by the model, but would transform the predicted probability to essentially an "unweighted" probability to make the Gains Table look better. I havnt been able to find a way by looking at each predicted value, both weighted and un-weighted to find a direct correlation between the two numbers.

I know that in each case, the ordering would remain the same and that is what is important, but it would help me quite a bit if my gains table could look more normal. I am trying to get my team on board with using XGBoost, and this is an issue with them. 

Thanks

**Comment by DeluxeAnalyst** [comment]
I have been doing some more research, and I have found an equation that can turn a weighted probability into an unweighted probability, given that you know the new ratio between the rare class and common class. 

My question now becomes how does XGBoost incorporate the scale_pos_weight into the model? Is it oversampling the rare class, if so what proportion is it using? In my case, I had 317 responders, and 44839 non-responders. So my model used "scale_pos_weight = (44839/317)".

Using my equation to "unweight" the probability, I was assuming a new 50-50 proportion between the new classes, but from my testing it doesnt appear that this is the case. 

Do you have any guidance for this?

**Comment by tqchen** [comment]
If you want exact probability, checkout the options in  http://xgboost.readthedocs.org/en/latest/param_tuning.html

**Comment by dmi3kno** [comment]
Is there some hope for scale_pos_weight being available in R implementation as well?

**Comment by tqchen** [comment]
I think you can already use this in R

**Comment by ihadanny** [comment]
Hey, I have a very imbalanced dataset. I'm trying to follow the tuning advice and use scale_pos_weight but not sure how should I tune it.

I can see that RegLossObj.GetGradient does:

if (info.labels[i] == 1.0f) w *= param_.scale_pos_weight

so a gradient of a positive sample would be more influential. However, according to the xgboost paper, the gradient statistic is always used locally = within the instances of a specific node in a specific tree:

    within the context of a node, to evaluate the loss reduction of a candidate split
    within the context of a leaf node, to optimize the weight given to that node

So there's no way of knowing in advance what would be a good scale_pos_weight - it is a very different number for a node that ends up with 1:100 ratio between positive and negative instances, and for a node with a 1:2 ratio...

Any hints? or should I just guess :(

(also here: http://stats.stackexchange.com/questions/243207/xgboost-for-imbalanced-dataset-proper-usage-of-scale-pos-weight)

**Comment by MartinThoma** [comment]
I came here looking for the [documentation of `scale_pos_weight`](http://xgboost.readthedocs.io/en/latest/parameter.html):

> Control the balance of positive and negative weights, useful for unbalanced classes. A typical value to consider: sum(negative cases) / sum(positive cases) See Parameters Tuning for more discussion. Also see Higgs Kaggle competition demo for examples: R, py1, py2, py3

I found it via [What is the proper usage of scale_pos_weight in xgboost for imbalanced datasets?](https://stats.stackexchange.com/q/243207/25741).
