### ISSUE TITLE
Use External Memory  Feature , Cache not save the Memory Used

### ISSUE THREAD

**Issue by zwqjoy** [dmlc/xgboost#5007]
The [ train and test ] files  total (2.8G)
xgboost version is   latest version :  1.0.0-snapshot

The the training is running, I run 4 experiments. 

tree_method:    approx  cacheA   10.44g  |  no cache 9.83g
tree_method:    hist        cacheA   15.03g  |  no cache 13.02g

So what should I do to use the External Memory to save the system memory used.

**Comment by trivialfis** [comment]
Weird.  Will investigate further.
