### ISSUE TITLE
Latest XGBoost incompatible with Python 3.4

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#5020]
Reported in https://discuss.xgboost.ai/t/xgboost-invalid-syntax-async-def-map-local-data/1238

https://github.com/dmlc/xgboost/blob/7663de956c37eb4dd528132214e68ba2851d9696/python-package/xgboost/dask.py#L169

`async def` is introduced in Python 3.5, so it is not compatible with Python 3.4.

We have two choices:
1) Require Python 3.5 and higher; or
2) Remove the use of `async def`.

@trivialfis What's your take on this?

**Comment by hcho3** [comment]
I cast my vote to 1), since Python 3.4 has reached the end of life.

**Comment by trivialfis** [comment]
@hcho3  Sorry for the late reply.  Totally on board with 1).

**Comment by RAMitchell** [comment]
I feel like there will be corporate systems stuck on old versions and 3.4 is not that old.

I prefer supporting it given this might be a case of changing 1 or 2 lines.
https://stackoverflow.com/questions/30191556/coroutine-in-python-between-3-4-and-3-5-how-can-i-keep-backwords-compatibility

**Comment by trivialfis** [comment]
I can try supporting it ..
