### ISSUE TITLE
Monotone constraints error

### ISSUE THREAD

**Issue by JerryX2014** [dmlc/xgboost#5027]
Hello,

I am running xgboost v0.82 on a linux box by using R 3.5.1.

My data has more than 2000 attributes, and I would like to set monotone constraints. Then it popped up the following error message.

![image](https://user-images.githubusercontent.com/10041052/68604298-29acd280-0478-11ea-99c7-27c69d0ce597.png)

However, if I just included the first 1200 attributes with the corresponding 1200 monotone constraints, it run without errors. 

Is there a length limit for the monotone constraints? Is there a way to set it larger.

Thanks!

**Comment by trivialfis** [comment]
Could you share your used tree method?

**Comment by JerryX2014** [comment]
I used the default tree method. 

I found the issue: my monotone constraints had NAs. After I replaced them with zeros, it worked as expected. 

Thanks,
