### ISSUE TITLE
Differentiating between base_score and base_margin

### ISSUE THREAD

**Issue by nalzok** [dmlc/xgboost#5028]
What's the difference between the `base_score` parameter of `xgboost.train` and the `base_margin` attribute of a `xgboost.DMatrix`? The documentation isn't super clear on this topic.

From my understanding, both specify the initial value of the prediction, and the former overrides the latter when both are set, but I suppose there are more differences.

**Comment by RAMitchell** [comment]
I believe one initialises the score globally for all instances, the other allows setting it individually for each training instance. In the second case this would be useful for continuing training from the output of some other kind of model.
