### ISSUE TITLE
SHAP values seem to be computed incorrectly under DART

### ISSUE THREAD

**Issue by Kodiologist** [dmlc/xgboost#5036]
A property of SHAP is that the sum of SHAP values for a case, plus SHAP's computed bias for the model, should equal the prediction for that case. This doesn't seem to obtain under dropout with the DART booster. Here's an example script. If dropout is enabled by setting to `one_drop` to `TRUE`, the SHAP sums will no longer be correct and "Oh no" will be printed. I'm using xgboost 0.90.0.2 and R 3.6.1 on Linux.

```
library(xgboost)

set.seed(10)
d = data.frame(
     x1 = rnorm(10),
     x2 = rnorm(10),
     fold = ifelse((1 : 10) <= 5, 1, 2))
d = transform(d, y =
     sin(x1^2) +
     ifelse(floor(x2 * 10) %/% 2, x2^2, x2^3) +
     rnorm(10))

ivs = c("x1", "x2")

set.seed(20)
fit = xgboost(
    verbose = 0,
    params = list(
        booster = "dart",
        objective = "reg:linear",
        eval_metric = "rmse",
        rate_drop = 0,
        one_drop = FALSE),
    data = as.matrix(subset(d, fold == 1)[, ivs]),
    label = subset(d, fold == 1)$y,
    nthread = 1,
    nrounds = 3)

shaps = as.data.frame(predict(fit,
    newdata = as.matrix(subset(d, fold == 2)[, ivs]),
    predcontrib = T))
result = cbind(shaps, sum = rowSums(shaps), pred = predict(fit,
    newdata = as.matrix(subset(d, fold == 2)[, ivs])))
print(result)

message(if (identical(TRUE, all.equal(result$sum, result$pred, tol = 1e-6)))
       "Looks good"
   else
       "Oh no")
```

CC @slundberg

**Comment by hcho3** [comment]
@Kodiologist Try setting `ntreelimit` to the number of boosting rounds. Otherwise, you'd perform dropout (i.e. a random subset of trees will be selected), which is almost certainly not what you want when performing a prediction.

**Comment by Kodiologist** [comment]
Setting `ntreelimit = 3` in the above code changes the predictions without changing the SHAPs, and the new predictions still aren't equal to the SHAP sums.

**Comment by hcho3** [comment]
The new prediction values were probably the correct ones, given the documented behavior of dropout at prediction time. We need to ensure whether SHAP also honors `ntreelimit` argument.

**Comment by Kodiologist** [comment]
From what I've seen so far, it looks like SHAP computation does indeed use all trees, but it doesn't consider how the trees are affected by the normalization step of DART (`Dart::weight_drop_` in `gbtree.cc`). I say this because if you compare SHAP sums to dumped trees, the SHAP sums agree with the sum of leaves whereas the model predictions don't, because the model predictions use `weight_drop_` (which aren't directly accessible from R). Consider the following example:

```R
d = rbind(c(0, 0), c(1, 2), c(-1, 3), c(0, -4))
y = c(0, 1, 2, 3)
nrounds = 2

set.seed(10)
fit = xgboost(
       nthread = 1,
       params = list(
           booster = "dart",
           objective = "reg:linear",
           eval_metric = "rmse",
           rate_drop = 0,
           one_drop = T,
           base_score = 0),
       data = d,
       label = y,
       nrounds = nrounds)

for (l in xgb.dump(fit))
    message(l)
print(cbind(d,
    shap.sum = rowSums(predict(
        fit, newdata = d, ntreelimit = nrounds, predcontrib = T)),
    pred = predict(
        fit, newdata = d, ntreelimit = nrounds)))
```

This prints:

```
booster[0]
0:leaf=0.360000014
booster[1]
0:leaf=0.360000014
           shap.sum      pred
[1,]  0  0     0.72 0.5538462
[2,]  1  2     0.72 0.5538462
[3,] -1  3     0.72 0.5538462
[4,]  0 -4     0.72 0.5538462
```

The SHAP sums, 0.72, are twice 0.36 as would be expected from the unaltered leaf values, whereas the predictions, 0.5538462, are not.

**Comment by Kodiologist** [comment]
Maybe something like this would work:

```diff
diff --git a/src/predictor/cpu_predictor.cc b/src/predictor/cpu_predictor.cc
index db342138..bfb91ae6 100644
--- a/src/predictor/cpu_predictor.cc
+++ b/src/predictor/cpu_predictor.cc
@@ -289,16 +289,24 @@ class CPUPredictor : public Predictor {
           bst_float* p_contribs =
               &contribs[(row_idx * ngroup + gid) * ncolumns];
           feats.Fill(batch[i]);
+          std::vector<bst_float> this_tree_contribs;
+          this_tree_contribs.resize(ncolumns);
           // calculate contributions
           for (unsigned j = 0; j < ntree_limit; ++j) {
+            std::fill(this_tree_contribs.begin(), this_tree_contribs.end(), 0);
             if (model.tree_info[j] != gid) {
               continue;
             }
             if (!approximate) {
-              model.trees[j]->CalculateContributions(feats, root_id, p_contribs,
+              model.trees[j]->CalculateContributions(feats, root_id, &this_tree_contribs,
                                                      condition, condition_feature);
             } else {
-              model.trees[j]->CalculateContributionsApprox(feats, root_id, p_contribs);
+              model.trees[j]->CalculateContributionsApprox(feats, root_id, &this_tree_contribs);
+            }
+            for (int ci = 0 ; ci < ncolumns ; ++ci) {
+                p_contribs[ci] += this_tree_contribs[ci] *
+                    (IS_DART ? DBTREE.weight_drop_[j] : 1);
             }
           }
           feats.Drop(batch[i]);
```

One would have to give `GBTree` a method that provided weights of 1 for non-DART trees, of course. But even were that change made, there's no clear way to access the relevant `GBTree` instance from this point in the code because the function parameter `model` is a `GBTreeModel`, and `GBTreeModel` instances are member variables of `GBTree`, so it's clear how to get a `GBTreeModel` from the associated `GBTree`, but not the reverse. I don't think I could change this; I don't understand the organization of the code well enough to even know where to start.
