### ISSUE TITLE
Xgboost predicts different values for same row in a sparse matrix, when predicting on different chunks of matrix

### ISSUE THREAD

**Issue by run2** [dmlc/xgboost#5037]
I am using a xgboost MultiClass model trained on Sparse Matrix (csr). When I use the model to predict on a sparse matrix - I get different prediction values for the same rows if I predict on the whole matrix (in one shot) or - on a subset of rows.

So like if I do
``` python
dmx = xgb.DMatrix(sparse,feature_names=modelFeatures)
predictions1 = model.predict(dmx)
```
and then if I do
``` python
indices = [n1,n2,n3,n4,...]
dmx = xgb.DMatrix(sparse[indices],feature_names=modelFeatures)
predictions2 = model.predict(dmx)
````
Then the rows between n and m have very different prediction values between predictions1 and predictions2.

I did read the https://github.com/dmlc/xgboost/issues/2488 - but thats not exactly my case. I cannot find anything else on the net which will answer whats going on.

Any help will be highly appreciated.

Thanks

**Comment by trivialfis** [comment]
@run2 Could you please provide a more complete script that I can run?

**Comment by kvaDrug** [comment]
Please, check this similar issue: https://github.com/dmlc/xgboost/issues/5287

**Comment by trivialfis** [comment]
Feel free to reopen when there's a reproducible sample.
