### ISSUE TITLE
Attribute Error: 'NoneType' object has no attribute 'split'.

### ISSUE THREAD

**Issue by mohita-ajmera** [dmlc/xgboost#5039]
![image](https://user-images.githubusercontent.com/14015331/68910764-f076aa00-0778-11ea-8d10-1f9e884b326b.png)

**Comment by hcho3** [comment]
Can you post your script here? It looks like your XGBoost installation is somehow corrupted? Also what is your Python version?

**Comment by mohita-ajmera** [comment]
I tried it in both python 3.6 and 3.7 and got the same error.
I am using a docker to build this flask application where the installation is done using pip install xgboost while building the image.

Getting error in import itself -
import api.ml_models.prep_data_reactivation as prep
import pickle
import psutil
import xgboost ----> error point

Please suggest.

**Comment by hcho3** [comment]
It looks like the docstring is being stripped away. See https://stackoverflow.com/questions/34939539/python-doc-returning-none. Can you unset `PYTHONOPTIMIZE` environment variable?

**Comment by mohita-ajmera** [comment]
It worked after changing this Python Environment variable PYTHONOPTIMIZE.
Thanks a lot for your suggestion.

**Comment by hcho3** [comment]
No problem. Thanks for using XGBoost.
