### ISSUE TITLE
[jvm-pacakges] why spark xgb must repartitionForTraining dataset to nWorkers partitions?

### ISSUE THREAD

**Issue by timruning** [dmlc/xgboost#5040]
when I train my spark xgb model, I usually  meet the memory overflow  problem. 
I find it is because we must repartition the dataset into nWorkers partitions.
So here is my question:
why xgb must repartitionForTraining ?
How can i solve this problem?
can I set nWorkers to a very big number?
Please help me.

this is the code:
![image](https://user-images.githubusercontent.com/13085553/68926469-900b5b00-07c0-11ea-8afc-c3ed0d814b36.png)

**Comment by trivialfis** [comment]
> why xgb must repartitionForTraining ?

Because spark doesn't allow downstream libraries to obtain all partitions in a worker to carry out allreduce calls.
