### ISSUE TITLE
Parameter min_split_loss should be greater equal to 0

### ISSUE THREAD

**Issue by zhangshd** [dmlc/xgboost#5047]
**xgboost 0.90**

Traceback (most recent call last):
  File "/home/zhangshd/product_env/repos/XGB_train_ql.py", line 424, in <module>
    gpgo.run(max_iter=25,init_evals=2)
  File "/home/zhangshd/anaconda3/envs/tf36/lib/python3.6/site-packages/pyGPGO/GPGO.py", line 192, in run
    self.updateGP()
  File "/home/zhangshd/anaconda3/envs/tf36/lib/python3.6/site-packages/pyGPGO/GPGO.py", line 149, in updateGP
    f_new = self.f(**kw)
  File "/home/zhangshd/product_env/repos/XGB_train_ql.py", line 353, in Search
    early_stopping_rounds=20, xgb_model=None, verbose_eval=100)
  File "/home/zhangshd/anaconda3/envs/tf36/lib/python3.6/site-packages/xgboost/training.py", line 216, in train
    xgb_model=xgb_model, callbacks=callbacks)
  File "/home/zhangshd/anaconda3/envs/tf36/lib/python3.6/site-packages/xgboost/training.py", line 74, in _train_internal
    bst.update(dtrain, i, obj)
  File "/home/zhangshd/anaconda3/envs/tf36/lib/python3.6/site-packages/xgboost/core.py", line 1109, in update
    dtrain.handle))
  File "/home/zhangshd/anaconda3/envs/tf36/lib/python3.6/site-packages/xgboost/core.py", line 176, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: value -2.77556e-17 for Parameter min_split_loss should be greater equal to 0

**Comment by trivialfis** [comment]
@zhangshd Could you please provide the used parameters?

**Comment by zhangshd** [comment]
```

**Comment by zhangshd** [comment]
@trivialfis 
Hi trivialfis,
I used the code below to search best params. The error above may occur when I add `gamma` to the GPGO search space. And it worked well when I remove `gamma` from the search dictionary.
```
def Search(gamma, max_depth, min_child_weight, colsample_bytree, subsample, learning_rate):

    train_metrics_all = []
    val_metrics_all = []
    test_metrics_all = []
    test_pred_all = []

    tree_params = {   "objective":'reg:squarederror',
                      "gamma":gamma,
                      "eval_metric": "rmse",
                      "nthread": 6,
                      "max_depth": int(max_depth),
                      "min_child_weight": int(min_child_weight),
                      "colsample_bytree": colsample_bytree,
                      "subsample": subsample,
                      "eta": learning_rate}

    i = 0
    for train_idx, val_idx in kf.split(X):
        i += 1

        dtrain = xgb.DMatrix(X[train_idx], label=y[train_idx])
        dval = xgb.DMatrix(X[val_idx], label=y[val_idx])
        dtest = xgb.DMatrix(te_X)
        watchlist = [(dtrain, 'train'), (dval, 'val')]
        model = xgb.train(tree_params, dtrain, num_boost_round=5000, evals=watchlist,
                          early_stopping_rounds=20, xgb_model=None, verbose_eval=100)
        
        train_pred = model.predict(dtrain)
        val_pred = model.predict(dval)
        test_pred = model.predict(dtest)
        test_pred_all.append(test_pred)

        train_metrics = CalMetrics(y_true=y[train_idx], y_pred=train_pred)
        val_metrics = CalMetrics(y_true=y[val_idx], y_pred=val_pred)
        test_metrics = CalMetrics(y_true=te_y, y_pred=test_pred)
        
        train_metrics_all.append(train_metrics)
        test_metrics_all.append(test_metrics)
        val_metrics_all.append(val_metrics)

    return np.array(val_metrics_all).mean(axis=0)[0]

from pyGPGO.covfunc import matern32
from pyGPGO.acquisition import Acquisition
from pyGPGO.surrogates.GaussianProcess import GaussianProcess
from pyGPGO.GPGO import GPGO

cov = matern32()
gp = GaussianProcess(cov)
acq = Acquisition(mode='ExpectedImprovement')
param = {
         'gamma': ('cont', [0, 0.5]),
         'max_depth': ('int', [3, 10]),
         'min_child_weight': ('int', [1, 20]),
         'colsample_bytree': ('cont', [0.5, 1]),
         'subsample': ('cont', [0.5, 1]),
         'learning_rate': ('cont', (0.01, 0.15)),
         }

np.random.seed(0)
gpgo = GPGO(gp, acq, Search, param)
gpgo.run(max_iter=25,init_evals=2)
para_result = gpgo.getResult()[0]
print("="*50)
print("Search results: ", gpgo.getResult()[0])
print("="*50)
```

**Comment by zhangshd** [comment]
I think a `gamma` greater than 0 may result in a negative `min_split_loss`. Can this bug be fixed well if I still want to add `gamma` to the params searching space?

**Comment by trivialfis** [comment]
@zhangshd gamma is a alias of `min_split_loss`.  It's used for pre/post pruning.  See our parameter document.
