### ISSUE TITLE
I encountered some problems when training data with gpu

### ISSUE THREAD

**Issue by wangweitong** [dmlc/xgboost#5052]
system ubantu 16.04
gpu  Tesla K80 10G
Train the data with gpu and set the parameter params['gpu_id'] = 0
Params['tree_method'] = 'gpu_hist' But gpu shows that no threads use gpu and training is very slow
Somebody can tell me why?

**Comment by trivialfis** [comment]
@wangweitong Could you please provide the version of XGBoost?  And activity of  command `nvidia-smi`.

**Comment by wangweitong** [comment]
> @wangweitong能否请您提供XGBoost的版本？和活动指挥`nvidia-smi`。

I have successfully resolved the dependencies between the driver and the cuda version. I uninstalled all the dependencies and drivers and installed the cuda10 and 10 drivers.
