### ISSUE TITLE
Questions about xgb.tree.plot

### ISSUE THREAD

**Issue by krystofer** [dmlc/xgboost#506]
Two questions. 

1. For trees of even moderate size the node marks become invisible. How to save the ploted tree in high resolution so one can see what is written on nodes?

2. The option n_first_tree draws only n first trees. Why not the last ones being generated?

**Comment by pommedeterresautee** [comment]
1. You can save trees in a RMarkdown document. Trees are Javascript so it is not printable easily
2. First tree is the one making most of the work. Then, the gain per tree decreases. That's why there is no real interest in seeing the last one without seeing the first ones.

**Comment by krystofer** [comment]
Is it possible to see how much information gain each tree does?

**Comment by pommedeterresautee** [comment]
You can do it easily using the `data.table` produced by the function `xgb.model.dt.tree`.
