### ISSUE TITLE
`monotone_constraints` ignored when `tree_method='approx'`

### ISSUE THREAD

**Issue by djarpin** [dmlc/xgboost#5060]
In XGBoost v0.90, there appears to be a bug where `monotone_constraints` is ignored when `tree_method` is set to "approx".  No warning or errors are thrown and I couldn't find any indication in the documentation that this is intended.  This is particularly difficult to track down because functioning monotonic constraints are not inherently obvious (in most cases) without doing partial dependence plots, and because `tree_method` defaults to "auto", which gets set to "approx" on big datasets (where checking partial dependence plots becomes more time-consuming).

Minimal reproducible example:

```python
import numpy as np
import xgboost as xgb
import matplotlib.pyplot as plt

X = np.array([np.arange(200) / 2.]).T
y = np.concatenate([np.arange(100), np.arange(100, 0, -1)]) + \
    5 * np.random.normal(size=200)

dtrain = xgb.DMatrix(X, label=y)
bst_exact = xgb.train({'tree_method': 'exact', 'monotone_constraints': '(1,0)'}, 
                      dtrain, 2)
bst_approx = xgb.train({'tree_method': 'approx', 'monotone_constraints': '(1,0)'}, 
                       dtrain, 2)

plt.plot(bst_exact.predict(dtrain), c='b', 
         label='prediction')
plt.plot(y, c='r', label='actuals')
plt.plot(X[:, 0], c='g', label='feature value')
plt.legend()
plt.title('monotone_constraints with tree_method=exact')
plt.show()

plt.plot(bst_approx.predict(dtrain), c='b', 
         label='prediction')
plt.plot(y, c='r', label='actuals')
plt.plot(X[:, 0], c='g', label='feature value')
plt.legend()
plt.title('monotone_constraints with tree_method=approx')
plt.show()
```

Which produces the plots:
![image](https://user-images.githubusercontent.com/6025741/69469324-053cda00-0d45-11ea-9977-f2d6628a10a4.png)
![image](https://user-images.githubusercontent.com/6025741/69469325-0a018e00-0d45-11ea-9fc2-3c54e41c6b92.png)

**Comment by hcho3** [comment]
Choice of tree_method is documented here: 
https://xgboost.readthedocs.io/en/latest/tutorials/monotonic.html. I do agree that there should be a warning whenever a training hyperparameter is inapplicable or ignored. See https://github.com/dmlc/xgboost/issues/4211

For now, try setting ‘tree_method’ to ‘hist’.
