### ISSUE TITLE
[CI] Jenkins is down

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#5061]
The Jenkins master node (xgboost-ci.net) has been down (*) for a few days, according to @trivialfis. **Impact: Substantial amount of test suite is rendered unavailable.** I'm re-building the master from scratch. Sorry for inconvenience caused. @dmlc/xgboost-committer 

PS. This seems to be a good opportunity to document all steps it takes to set up the Jenkins master node from scratch. See hcho3/xgboost-devops#6. Also #4958 

(*) I cannot either ping or SSH into the master instance.

**Comment by trivialfis** [comment]
Travis seems also down as there is a permission error.  Will try to resolve it later.

**Comment by trivialfis** [comment]
Travis is fixed in #5062

**Comment by hcho3** [comment]
@trivialfis Thanks for fixing Travis! I'll get Jenkins back up very soon.

**Comment by hcho3** [comment]
Update: Linux pipeline is now back up. I still need to work on the Windows pipeline.

**Comment by trivialfis** [comment]
Okay.  I messed up a little.

**Comment by hcho3** [comment]
@trivialfis I updated https://github.com/hcho3/xgboost-devops/issues/6 to include some details about the Windows pipeline. I'm also closing this issue, as Jenkins is now fully back up.

**Comment by hcho3** [comment]
Sorry, looks like I called it too early. Windows pipeline is still broken.

**Comment by hcho3** [comment]
Fixed in #5078
