### ISSUE TITLE
about gpu training speed

### ISSUE THREAD

**Issue by wangweitong** [dmlc/xgboost#5069]
I use a 10G  k80 gpu to train my data but it‘s performing is not well, and it just use a little storage of gpu,I don't know how to use full of storage,somebody knows that?

**Comment by trivialfis** [comment]
Could you provide your XGBoost version and training parameters?  Also shape and maybe sparsity of your data.

**Comment by wangweitong** [comment]
> 您能否提供您的XGBoost版本和培训参数？还会影响数据的稀疏性。

The data is not sparse, there are only 20 features, but there are many outliers. The xgboost version is 1.0.0

**Comment by trivialfis** [comment]
You can set verbosity to 3 (debugging).  At the end of training XGBoost will print some profiling results.  Could you share the result with us?
