### ISSUE TITLE
Train in python and predict in spark

### ISSUE THREAD

**Issue by rnair56** [dmlc/xgboost#5071]
Thanks for participating in the XGBoost community! We use https://discuss.xgboost.ai for any general usage questions and discussions. The issue tracker is used for actionable items such as feature proposals discussion, roadmaps, and bug tracking.  You are always welcomed to post on the forum first :)

Issues that are inactive for a period of time may get closed. We adopt this policy so that we won't lose track of actionable issues that may fall at the bottom of the pile. Feel free to reopen a new one if you feel there is an additional problem that needs attention when an old one gets closed.

For bug reports, to help the developer act on the issues, please include a description of your environment, preferably a minimum script to reproduce the problem.

For feature proposals, list clear, small actionable items so we can track the progress of the change.

**Comment by rnair56** [comment]
I have a trained Xgb model in python and want to use that for scoring in Spark. I was able to get the Scores in Spark using the threads in the community

Using bridge class for XGboost Spark version >0.8
[(https://github.com/dmlc/xgboost/issues/3689)]

How to train in Python and predict in Spark
[https://discuss.xgboost.ai/t/load-python-trained-model-file-into-xgboost4j-spark/80]

The issue now is, all my prediction scores are exactly same, what can be the reason for this? From a related thread I understand that this can be because of indexing difference between Python and Spark
[https://github.com/dmlc/xgboost/issues/3190]

How do I correct this? I am using a dataframe to train my model in Python which is read from a csv file.

P.S: I am ensuring that the column is same in both Spark and Python

**Comment by trivialfis** [comment]
@hcho3 How difficult would it be to add tests for cross binding model IO in Jenkins? It's a bit worrying that the Scala package being very a thick layer on top of cxx core.  I haven't look into this issue yet, but I will try to get new model IO up fast as possible.

**Comment by trivialfis** [comment]
Closing in favor of https://github.com/dmlc/xgboost/issues/4765 .
