### ISSUE TITLE
Issue with DaskXGBClassifier + Dask '1.0.0-SNAPSHOT'

### ISSUE THREAD

**Issue by John-Brown** [dmlc/xgboost#5073]
This is compiled on a ubuntu machine with CUDA 10 and 8x Tesla GPU's

```python
def main(client):
    dX_train = dd.from_pandas(X_train,npartitions=8)
    dy_train = dd.from_pandas(y_train,npartitions=8)
    
    xgb_param = {
        'objective': 'binary:logistic',
        'silent': 1, 
        'client':client,
        'tree_method': 'gpu_hist', 
        'eval_metric':'auc'}
    
    a = xgboost.dask.DaskXGBClassifier(verbosity=1, **xgb_param)

    a.fit(
        dX_train, 
        dy_train, 
    )
    prediction = a.predict(dX_train[boo+num+dummy_cols ])

    bst = a.get_booster()
    history = a.evals_result()

    print('Evaluation history:', history)
    # returned prediction is always a dask array.
    assert isinstance(prediction, da.Array)
    return bst                  # returning the trained mode
```

```python
with LocalCUDACluster() as cluster:
    with Client(cluster) as client:
        dask_xgb = main(client)
```

Gives the following error 

```bash
AttributeError: 'DataFrame' object has no attribute 'ravel'
```

If I pass `dy_train.values`

I get 

```bash
ValueError: cannot convert float NaN to integer
```

**Comment by trivialfis** [comment]
Great!  Early bug catch.  Will look into it today.

**Comment by trivialfis** [comment]
@John-Brown How did you install dask-cuda?  I'm asking because the one in pip is quite out of date, see: https://github.com/rapidsai/dask-cuda/issues/130

Also, you don't need to set objective for classifier.  In Python this is automatically set.

**Comment by John-Brown** [comment]
@trivialfis 

I built via the directions at:
https://xgboost.readthedocs.io/en/latest/build.html#building-with-gpu-support

**Comment by John-Brown** [comment]
> @John-Brown How did you install dask-cuda? I'm asking because the one in pip is quite out dated, see: [rapidsai/dask-cuda#130](https://github.com/rapidsai/dask-cuda/issues/130)
> 
> Also, you don't need to set objective for classifier. In Python this is automatically set. `client` is not a valid parameter (but maybe I should make it one, see demo/dask for some examples), `silent` is deprecated.

I installed via cloning the repo and pip install .
