### ISSUE TITLE
Error with the labels

### ISSUE THREAD

**Issue by oke-aditya** [dmlc/xgboost#5076]
- Hello XGBoost team.

I am trying to do as follows. 
My environment is the Google Colab enivronment with default XGBoost in it.

```
df = pd.DataFrame(np.arange(12).reshape((4,3)), columns = ['a','b','c'])
label = pd.DataFrame(np.random.randint(2, size=4))

df.head()

label.head()

dtrain = xgb.DMatrix(data, label = label)

param = {'max_depth' : 2, 'eta' : 0.2, 'objective' : 'binary:logistic', 'eval_metric' : 'error'}

num_round = 10

bst = xgb.train(params = param, dtrain = dtrain, num_boost_round=num_round)
```

The following error message is appearing.

XGBoostError: [15:25:10] /workspace/src/objective/regression_obj.cu:65: Check failed: preds.Size() == info.labels_.Size() (5 vs. 4) : labels are not correctly providedpreds.size=5, label.size=4
Stack trace:

Am I doing something wrong here ? What is the exact problem in labels ?

**Comment by oke-aditya** [comment]
- My data
![image](https://user-images.githubusercontent.com/47158509/69818080-075dd780-1222-11ea-8e9a-786500e88b40.png)

- My labels
![image](https://user-images.githubusercontent.com/47158509/69818093-104ea900-1222-11ea-998b-f2de51f9be6b.png)

**Comment by trivialfis** [comment]
@oke-aditya Could you provide the version of XGBoost?  I just tried this on master branch and 0.9, everything seems fine:
One difference in the code is, I set `data` explicitly, while in your example `data` is not defined.

``` python
import pandas as pd
import numpy as np
import xgboost as xgb

df = pd.DataFrame(np.arange(12).reshape((4, 3)), columns=['a', 'b', 'c'])
data = df

label = pd.DataFrame(np.random.randint(2, size=4))

df.head()

label.head()
dtrain = xgb.DMatrix(data, label=label)

param = {
    'max_depth': 2,
    'eta': 0.2,
    'objective': 'binary:logistic',
    'eval_metric': 'error'
}

num_round = 10

bst = xgb.train(params=param, dtrain=dtrain, num_boost_round=num_round)
```

**Comment by oke-aditya** [comment]
Oh! what a small Mistake. Apologies from my side. Should have checked it before. My code is working fine. It was because of data = df. which I missed.

- I was using XGBoost 0.9.0. It worked fine. Absolutely no issues with XGBoost API.

- I was learning it, so had a confusion 👍  Thank you for your time.

**Comment by oke-aditya** [comment]
- Just closing this issue. Thank you for that. Sorry if I wasted your time. :octocat:
