### ISSUE TITLE
Implement Gradient Boosted Feature Selection

### ISSUE THREAD

**Issue by tomtung** [dmlc/xgboost#508]
as described in http://alicezheng.org/papers/gbfs.pdf

Basically it seems like: when measuring the goodness of a tree node split (for learning a regression tree), add a tunable constant penalty if the feature used for splitting hasn't been used by existing trees.

Seems quite simple, and can be a nice alternative for people who use feature importance to select features.

**Comment by tqchen** [comment]
Let us move roadmap issues to #574  so it can be tracked in a more easier way
