### ISSUE TITLE
How 0 and null are handled in XGBooost?

### ISSUE THREAD

**Issue by jianjinlayer6ai** [dmlc/xgboost#5085]
Hi All, 
If I write 0 explicitly in libsvm file, whether DMatrix and XGB can distinguish 0 and null?

In detail, if a feature is float array [10, 0, null, 20], I can write my libsvm as 0:10 1:0 3:20. In this case, 0 and null can be distinguished in libsvm file. After that, DMatrix is created using libsvm file and XGB is trained on DMatrix. May I ask whether DMatrix and XGB can still distinguish 0 and null? If so, could you kindly point out which part of code shows this point? Thank you so much.

**Comment by hcho3** [comment]
Internally, XGBoost uses [CSR representation](https://en.wikipedia.org/wiki/Sparse_matrix#Compressed_sparse_row_(CSR,_CRS_or_Yale_format)) to hold the data matrix. So 0 and missing values will be distinguished.

**Comment by jianjinlayer6ai** [comment]
Hi hcho3, thank you so much for your reply, which is very helpful. 
Could you kindly show me where I can find the implementation in the code? 
My second question is if 0 and missing value can be distinguished in DMatrix, whether they can still be distinguished in XGB training?

**Comment by hcho3** [comment]
Here is the place where CSR representation is stored:
https://github.com/dmlc/xgboost/blob/e3c34c79be05f7833f8fb0228f28745d224d61bc/include/xgboost/data.h#L183-L188

And, yes, XGBoost has a mechanism to handle missing values; in fact, missing value is handled as part of the algorithm. For full description of the algorithm, see my master's thesis at https://drive.google.com/file/d/0B0c0MbnP6Nn-eUNRRkVOOGpkbFk/view
