### ISSUE TITLE
how to make  xgboost to support user-defined file format?

### ISSUE THREAD

**Issue by theseusyang** [dmlc/xgboost#509]
Hi All,

how to make  xgboost to support user-defined file format like csv?

theseus yang

**Comment by BlindApe** [comment]
I think the most interesting feature would be XGDMatrixCreateFromCSC could import the data from three files (for i, p and x components of sparse matrix). This, in practice, double the RAM of your PC.
The xgboost RAM bottleneck is the matrix loading: for R matrix you need 2.x RAM given you need the data  load in R and extra space for data trasnposition, with sparse matrix (CSC) you avoid the trasposition step but need data in R.
With option for load the three components from disk files the data don't need to be in R, so you will double your RAM and extend xgboost limits.

**Comment by theseusyang** [comment]
Hi @BlindApe ,

Thank you for your response, Agree you!
My database is matrix DB, its table structure is sparse matrix,following below:

[
[1,2,3],
[4,5,6],
[7,8,9]
]
It can be effectively avoid xgboots RAM bottleneck when matrix loading.
In xgboost/core.py file, XGDMatrixCreateFromFile invokes  csr = scipy.sparse.csr_matrix(data) to translate  data file to matrix, I now prepare to make  tool to load the data into xgboost, without using  scipy.sparse.csr_matrix(data), so more fast.


theseus yang

**Comment by BlindApe** [comment]
Currently I've other related problem. R integer is 32 bit so sparse matrices are limited to 2^31 (integer are signed) non zero cells. This is only 2147M. 
Reading data from file and loading in C++ directly would avoid this R bottleneck.

**Comment by tqchen** [comment]
Yes, this is an interesting feature that we improved. It is great that we are pushing the limit such that this becomes a bottle neck. This can be done by adding a richer DMatrix loading functions like @BlindApe suggested, possibly using a templated type internally to support richer types.

I will mark this as a Feature TODO List and hopefully we can find time to get it done
@theseusyang  Will you be interested in taking stab on this

**Comment by BlindApe** [comment]
Great, @tqchen.
Sometimes  I feel like an explorer in Amazon...
Really load big matrices in xgboost is now the real frontier of the tool (I speak of R wrapper):

Do you think this could be other 'integer type error'?
The code for reproduce is in the R screen. The server has 256Gb so the crash is before the RAM limit is reached.

![matrix_error](https://cloud.githubusercontent.com/assets/2364186/9981462/10d98dce-5fbe-11e5-82d7-8ace7c3545e5.jpg)

**Comment by tqchen** [comment]
@BlindApe This could happen because the memory resize was done in a drastic way, so usually the program will try to double its memory consumption when things did not fit.

Another frontier we are looking at is more user friendly external memory format(putting data on disk instead loading all of them into memory). With dato's SFrame now opensourced (by @ylow ) , and I heard they will be supporting R. hopefully we can have a better integration with SFrame so you can directly manipulate bigger data in R like dataframe while being able to xgboost without having to worry about memory issue.

**Comment by theseusyang** [comment]
@tqchen Great, I am very interested in  enriching DMatrix loading feature.

**Comment by Superhzf** [comment]
@tqchen  
Hey, does the xgboost Python package supports SFrame now? Suppose I already have a big SFrame whose size is larger than my memory, can I analyze it using Xgboost locally?
