### ISSUE TITLE
[Improvement] Support of discrete vs continuous metadata + AddCutPoint() adaptation

### ISSUE THREAD

**Issue by DoanHuuJacques** [dmlc/xgboost#5096]
Hi,

as per discussed in the close issue thread (https://github.com/dmlc/xgboost/issues/5095), give the possibility to provide per feature whether it's a continuous or discrete.

Indeed, XGBoost learning strategy can be adapted accordingly.
The typical benefit (mentioned in the above issue entry about AddCutPoint() method) is to apply the proper cut point strategy for either discrete or continuous feature, instead of relying on a predefined cardinality threshold (16).

Thanks

**Comment by RAMitchell** [comment]
As of #5251, I think this is resolved such that categorical feature values >16 do not get lost. We can reopen this discussion if there are any further issues with quantile cut points and categorical features.
