### ISSUE TITLE
[Documentation problem] XGBoostClassifier doesn't specify if monotone_constraints are usable

### ISSUE THREAD

**Issue by alexbaron10** [dmlc/xgboost#5099]
https://xgboost.readthedocs.io/en/latest/python/python_api.html#module-xgboost.sklearn

Doesn't specify if monotone constraints are usable (it seems like they are but i'm not entirely sure since it doesn't explicitly specify.

Thanks in advance

EDIT: neither does it appear here:

https://github.com/dmlc/xgboost/blob/master/doc/parameter.rst

**Comment by trivialfis** [comment]
Em.  Let me check all parameters for SKL interface.  It should work as they are all passed into `xgb.train` as part of `**kwargs`.  I wish we can generate these parameters based on c++ code.

**Comment by alexbaron10** [comment]
> Em. Let me check all parameters for SKL interface. It should work as they are all passed into `xgb.train` as part of `**kwargs`. I wish we can generate these parameters based on c++ code.

Thanks for the effort. I've been trying to use them with DART but i can't see if they are working or not either (documentation doesn't specify if they apply when using DART), that's another problem. Maybe a checkable way could be added in the future that tells if monotone_constrains are being used?

**Comment by trivialfis** [comment]
Depends on https://github.com/dmlc/xgboost/pull/5130 .
