### ISSUE TITLE
ValueError: y contains previously unseen labels: [12.0]

### ISSUE THREAD

**Issue by connect2robiul** [dmlc/xgboost#5102]
Code 

```
import xgboost as xgb
classifier = xgb.XGBClassifier(n_estimators=10, max_depth=5, base_score=0.5,objective='multi:softmax', 
                               random_state=42 , num_class = len(y_train.unique()))

classifier.fit(X_train, y_train,eval_set = [(X_valid,y_valid)],verbose=False,early_stopping_rounds = 10)

classifier.fit(X_train, y_train)
y_pred =  classifier.predict(X_test)
```

Error 

```
ValueError                                Traceback (most recent call last)
<ipython-input-62-a4644655ccf6> in <module>
      5 #                              eval_set=[(X_train, y_train), (X_valid, y_valid)])
      6 
----> 7 classifier.fit(X_train, y_train,eval_set = [(X_valid,y_valid)],verbose=False,early_stopping_rounds = 10) #eval_set=[(X_train, y_train), (X_valid, y_valid)])
      8 
      9 classifier.fit(X_train, y_train)

~/anaconda3/lib/python3.7/site-packages/xgboost/sklearn.py in fit(self, X, y, sample_weight, eval_set, eval_metric, early_stopping_rounds, verbose, xgb_model, sample_weight_eval_set, callbacks)
    709                         missing=self.missing, weight=sample_weight_eval_set[i],
    710                         nthread=self.n_jobs)
--> 711                 for i in range(len(eval_set))
    712             )
    713             nevals = len(evals)

~/anaconda3/lib/python3.7/site-packages/xgboost/sklearn.py in <genexpr>(.0)
    709                         missing=self.missing, weight=sample_weight_eval_set[i],
    710                         nthread=self.n_jobs)
--> 711                 for i in range(len(eval_set))
    712             )
    713             nevals = len(evals)

~/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/label.py in transform(self, y)
    255             return np.array([])
    256 
--> 257         _, y = _encode(y, uniques=self.classes_, encode=True)
    258         return y
    259 

~/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/label.py in _encode(values, uniques, encode)
    108         return res
    109     else:
--> 110         return _encode_numpy(values, uniques, encode)
    111 
    112 

~/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/label.py in _encode_numpy(values, uniques, encode)
     47         if diff:
     48             raise ValueError("y contains previously unseen labels: %s"
---> 49                              % str(diff))
     50         encoded = np.searchsorted(uniques, values)
     51         return uniques, encoded

ValueError: y contains previously unseen labels: [12.0]
```

**Comment by trivialfis** [comment]
What's the value of `num_class = len(y_train.unique())`?

**Comment by connect2robiul** [comment]
17 (its int number )

**Comment by hcho3** [comment]
Is it possible to transform your output label so that the classes are represented as 0, 1, 2, ..., `num_class-1`?

**Comment by connect2robiul** [comment]
There are already numbers.

**Comment by hcho3** [comment]
Can you check if there is a gap? The error message says 12 is missing.

**Comment by trivialfis** [comment]
Please provide a reproducible script.  I haven't seen this before.

**Comment by connect2robiul** [comment]
I did not provide the dataset.  sorry.

**Comment by trivialfis** [comment]
We should define a num class and allow skipping XGBoost s label encoder.

**Comment by shivam13juna** [comment]
OH MY GODDD, finally what hcho3 said helped me out. They re-encode. We gotta have this in xgboost, although I had this problem with lightgbm. Apparently all encoded columns are expected to be zero indexed, trainy - 1 sorted me out.

**Comment by Mingkko** [comment]
If I use `eval_set=(val_x,val_y)`,it will report a ValueError just like the author.
Use `eval_set=[(val_x,val_y)]` or `eval_set=[(tra_x,tra_y),(val_x,val_y)]` is OK.
Why it is okay when I use `eval_set=(val_x,val_y)` in LightGBM?

The `train_y` is already number, it's a array.No gap, no "nan".
The objection is "binary".

**Comment by hcho3** [comment]
In XGBoost, `eval_set` must be a list of pairs, where each pair is of form (X, y).

**Comment by NikithaVenkat** [comment]
raise ValueError(label_encoding_check_error)
ValueError: The label must consist of integer labels of form 0, 1, 2, ..., [num_class - 1].

My target variables contain 0 and 1. I am using an ensemble model, so my other target variable contains nulls as well along with 0 and 1. Is that causing the problem?

I have already used use_label_encoder=False, Could you kindly let me know if you know any other solution?

**Comment by trivialfis** [comment]
@NikithaVenkat Could you please open a new issue with a reproducible example we can run?

**Comment by NikithaVenkat** [comment]
> @NikithaVenkat Could you please open a new issue with a reproducible example we can run?

https://github.com/dmlc/xgboost/issues/7809
Done Thanks
