### ISSUE TITLE
CPU optimizations - 'hist' method

### ISSUE THREAD

**Issue by SmirnovEgorRu** [dmlc/xgboost#5104]
Moved discussion from [PR #5008](https://github.com/dmlc/xgboost/pull/5008) to the issue. After the PR - performance drop on CPU is observed. I prepared a plan how to establish optimizations from [PR #4529](https://github.com/dmlc/xgboost/pull/4529) in master branch again.

I tried to split large changes to separate PRs:

|№|Description|Status|
|--|--|--|
|1| Extend Performance Timer to track overall performance of each algorithmic stage for whole training|[**Merged**](https://github.com/dmlc/xgboost/pull/5107)|
|2| Add benchmarks to track performance changes (~3 data sets are enough for the start, it can be extended later)|[**Merged**](https://github.com/dmlc/xgboost-bench/commit/c787a590e0ece4898a65c0026ad9dce21e201876)|
|3| Add nested parallelism in EvaluateSplit function + tests |[**Merged**](https://github.com/dmlc/xgboost/pull/5138)|
|4| Add nested parallelism in BuildHist function + tests |[**Merged**](https://github.com/dmlc/xgboost/pull/5156)|
|5| Add nested parallelism in ApplySplit function + tests |[**Merged**](https://github.com/dmlc/xgboost/pull/5244)|

Expected timelines for creation the all PRs - EOY.

**Comment by trivialfis** [comment]
I would love to see the performance optimization back and sorry for the oversight.  Feel free to ping me if you need any help.

**Comment by hcho3** [comment]
> Add benchmarks to track performance changes (~3 data sets are enough for the start, it can be extended later)

For now, a script that we can run is okay, so that performance results can be re-produced. I plan to design and build an automatic system for performance benchmarking.

**Comment by SmirnovEgorRu** [comment]
All PRs are merged, final results:

Dataset | higgs1m | Letters | Airline-ohe | MNIST | MSRank-30K | Mortgage
-- | -- | -- | -- | -- | -- | --
Before commit https://github.com/dmlc/xgboost/pull/5008, sec | 15.5 | 10.3 | 55.3 | 69.5 | 99.1 | 18.3
After commit https://github.com/dmlc/xgboost/pull/5008, sec | 123.5 | 144.6 | 133.2 | Inf | 332.2 | 53.4 
Current Master, sec | 14.7 | 10.1 | 59.4 | 80.5 | 111.6 | 19.0

Current master is is slightly slower on MNIST data set than it was before, but it can be covered in the next PRs

Thank you all who helped me to refactor the optimizations to have them in the master again (@hcho3, @trivialfis, @RAMitchell ).
