### ISSUE TITLE
[dask] XGBoost label size and pred size does not match

### ISSUE THREAD

**Issue by datainvestor** [dmlc/xgboost#5109]
After trying to train xgboost model:

```
import pandas as pd

from dask.distributed import Client, progress
import joblib
from dask import dataframe as ddf
import numpy as np
from dask_ml.model_selection import train_test_split
from dask_ml.xgboost import XGBClassifier, train, predict
from dask_ml.preprocessing import LabelEncoder


client=Client(threads_per_worker=8,n_workers=1, memory_limit="16GB")
df=ddf.read_parquet("Data.parquet",categories=cats)
Y_column='Tree Level 5 Name'

X_train, X_test, y_train, y_test = train_test_split(df["Store Area"], df[Y_column])
encoder = LabelEncoder()

y_train = encoder.fit_transform(y_train)

est=XGBClassifier()
est.fit(X_train, y_train, eval_metric="logloss")

```

I get the following error:

`XGBoostError: [11:41:24] /workspace/src/objective/multiclass_obj.cu:60: Check failed: preds.Size() == (static_cast<size_t>(param_.num_class) * info.labels_.Size()): SoftmaxMultiClassObj: label size and pred size does not match
`
Not sure what is wrong, I'm using dask for this dataset as its quite big- around 1.1 million observations.

**Comment by trivialfis** [comment]
@datainvestor What's the exact commit of your XGBoost, as the dask interface is quite new.  Also from your code example, you are not using dask interface.

**Comment by datainvestor** [comment]
I updated the code to show the usage of dask.
XGBoost I'm using is coming from dask_ml.xgboost 0.1 package

**Comment by nanffiy** [comment]
@datainvestor

**Comment by trivialfis** [comment]
@datainvestor Can you provide an example dataset we can reproduce?

**Comment by fjgmoya** [comment]
@datainvestor, I has just solved it adding the las "classes" undocummented parameter:

 xgbc.fit(dfxtrain, dfytrain, classes=da.unique(yy).compute())

Surprisely, it works.
Regards

**Comment by hcho3** [comment]
XGBoost now has a built-in Dask API: `xgboost.dask`.
