### ISSUE TITLE
Issues installing Xgboost on Mac - CatalinaOS

### ISSUE THREAD

**Issue by prasadseemakurthi** [dmlc/xgboost#5113]
Commands used 
1. brew install libomp
2. pip3 install xgboost

command: /Users/prasad.seemakurthi/xgboost/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/r1/cys3qrkn49s1jlghjldg3tk40000gq/T/pip-install-_0gsveuo/xgboost/setup.py'"'"'; __file__='"'"'/private/var/folders/r1/cys3qrkn49s1jlghjldg3tk40000gq/T/pip-install-_0gsveuo/xgboost/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /private/var/folders/r1/cys3qrkn49s1jlghjldg3tk40000gq/T/pip-install-_0gsveuo/xgboost/
    Complete output (132 lines):
    ++ pwd
    + oldpath=/private/var/folders/r1/cys3qrkn49s1jlghjldg3tk40000gq/T/pip-install-_0gsveuo/xgboost
    + cd ./xgboost/
    + echo darwin19
    + grep -q darwin
    + LIB_XGBOOST=libxgboost.dylib
    + which g++-5
    /usr/local/bin/g++-5
    + export CC=gcc-5
    + CC=gcc-5
    + export CXX=g++-5
    + CXX=g++-5
    + make clean
    Makefile:31: MAKE [/Library/Developer/CommandLineTools/usr/bin/make] - checked OK
    rm -f -rf build build_plugin lib bin *~ */*~ */*/*~ */*/*/*~ */*.o */*/*.o */*/*/*.o #xgboost
    rm -f -rf build_tests *.gcov tests/cpp/xgboost_test
    if [ -d "R-package/src" ]; then \
    		cd R-package/src; \
    		rm -f -rf rabit src include dmlc-core amalgamation *.so *.dll; \
    		cd /private/var/folders/r1/cys3qrkn49s1jlghjldg3tk40000gq/T/pip-install-_0gsveuo/xgboost/xgboost; \
    	fi
    + make lib/libxgboost.dylib -j4
    Makefile:31: MAKE [/Library/Developer/CommandLineTools/usr/bin/make] - checked OK
    g++-5 -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/learner.o src/learner.cc >build/learner.d
    g++-5 -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/logging.o src/logging.cc >build/logging.d
    g++-5 -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/c_api/c_api.o src/c_api/c_api.cc >build/c_api/c_api.d
    g++-5 -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/c_api/c_api_error.o src/c_api/c_api_error.cc >build/c_api/c_api_error.d
    g++-5 -c -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp src/c_api/c_api_error.cc -o build/c_api/c_api_error.o
    In file included from /usr/local/Cellar/gcc@5/5.5.0_3/include/c++/5.5.0/bits/postypes.h:40:0,
                     from /usr/local/Cellar/gcc@5/5.5.0_3/include/c++/5.5.0/bits/char_traits.h:40,
                     from /usr/local/Cellar/gcc@5/5.5.0_3/include/c++/5.5.0/string:40,
                     from /usr/local/Cellar/gcc@5/5.5.0_3/include/c++/5.5.0/stdexcept:39,
                     from /usr/local/Cellar/gcc@5/5.5.0_3/include/c++/5.5.0/array:38,
                     from /usr/local/Cellar/gcc@5/5.5.0_3/include/c++/5.5.0/tuple:39,
                     from /usr/local/Cellar/gcc@5/5.5.0_3/include/c++/5.5.0/mutex:38,
                     from dmlc-core/include/dmlc/thread_local.h:9,
                     from src/c_api/c_api_error.cc:6:
    /usr/local/Cellar/gcc@5/5.5.0_3/include/c++/5.5.0/cwchar:44:19: fatal error: wchar.h: No such file or directory
    compilation terminated.
    make: *** [build/c_api/c_api_error.o] Error 1
    make: *** Waiting for unfinished jobs....
    g++-5 -c -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp src/logging.cc -o build/logging.o
    g++-5 -c -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp src/c_api/c_api.cc -o build/c_api/c_api.o
    In file included from include/xgboost/data.h:10:0,
                     from src/c_api/c_api.cc:3:
    dmlc-core/include/dmlc/base.h:190:23: fatal error: sys/types.h: No such file or directory
    compilation terminated.
    make: *** [build/c_api/c_api.o] Error 1
    In file included from /usr/local/Cellar/gcc@5/5.5.0_3/include/c++/5.5.0/bits/postypes.h:40:0,
                     from /usr/local/Cellar/gcc@5/5.5.0_3/include/c++/5.5.0/bits/char_traits.h:40,
                     from /usr/local/Cellar/gcc@5/5.5.0_3/include/c++/5.5.0/string:40,
                     from rabit/include/rabit/rabit.h:13,
                     from src/logging.cc:7:
    /usr/local/Cellar/gcc@5/5.5.0_3/include/c++/5.5.0/cwchar:44:19: fatal error: wchar.h: No such file or directory
    compilation terminated.
    make: *** [build/logging.o] Error 1
    g++-5 -c -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp src/learner.cc -o build/learner.o
    In file included from /usr/local/Cellar/gcc@5/5.5.0_3/include/c++/5.5.0/cstdio:42:0,
                     from dmlc-core/include/dmlc/io.h:8,
                     from src/learner.cc:7:
    /usr/local/Cellar/gcc@5/5.5.0_3/lib/gcc/5/gcc/x86_64-apple-darwin17.7.0/5.5.0/include-fixed/stdio.h:78:20: fatal error: _stdio.h: No such file or directory
    compilation terminated.
    make: *** [build/learner.o] Error 1
    + echo -----------------------------
    -----------------------------
    + echo 'Building multi-thread xgboost failed'
    Building multi-thread xgboost failed
    + echo 'Start to build single-thread xgboost'
    Start to build single-thread xgboost
    + make clean
    Makefile:31: MAKE [/Library/Developer/CommandLineTools/usr/bin/make] - checked OK
    rm -f -rf build build_plugin lib bin *~ */*~ */*/*~ */*/*/*~ */*.o */*/*.o */*/*/*.o #xgboost
    rm -f -rf build_tests *.gcov tests/cpp/xgboost_test
    if [ -d "R-package/src" ]; then \
    		cd R-package/src; \
    		rm -f -rf rabit src include dmlc-core amalgamation *.so *.dll; \
    		cd /private/var/folders/r1/cys3qrkn49s1jlghjldg3tk40000gq/T/pip-install-_0gsveuo/xgboost/xgboost; \
    	fi
    + make lib/libxgboost.dylib -j4 USE_OPENMP=0
    Makefile:31: MAKE [/Library/Developer/CommandLineTools/usr/bin/make] - checked OK
    g++-5 -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -DDISABLE_OPENMP -MM -MT build/learner.o src/learner.cc >build/learner.d
    g++-5 -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -DDISABLE_OPENMP -MM -MT build/logging.o src/logging.cc >build/logging.d
    g++-5 -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -DDISABLE_OPENMP -MM -MT build/c_api/c_api.o src/c_api/c_api.cc >build/c_api/c_api.d
    g++-5 -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -DDISABLE_OPENMP -MM -MT build/c_api/c_api_error.o src/c_api/c_api_error.cc >build/c_api/c_api_error.d
    g++-5 -c -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -DDISABLE_OPENMP src/c_api/c_api_error.cc -o build/c_api/c_api_error.o
    In file included from /usr/local/Cellar/gcc@5/5.5.0_3/include/c++/5.5.0/bits/postypes.h:40:0,
                     from /usr/local/Cellar/gcc@5/5.5.0_3/include/c++/5.5.0/bits/char_traits.h:40,
                     from /usr/local/Cellar/gcc@5/5.5.0_3/include/c++/5.5.0/string:40,
                     from /usr/local/Cellar/gcc@5/5.5.0_3/include/c++/5.5.0/stdexcept:39,
                     from /usr/local/Cellar/gcc@5/5.5.0_3/include/c++/5.5.0/array:38,
                     from /usr/local/Cellar/gcc@5/5.5.0_3/include/c++/5.5.0/tuple:39,
                     from /usr/local/Cellar/gcc@5/5.5.0_3/include/c++/5.5.0/mutex:38,
                     from dmlc-core/include/dmlc/thread_local.h:9,
                     from src/c_api/c_api_error.cc:6:
    /usr/local/Cellar/gcc@5/5.5.0_3/include/c++/5.5.0/cwchar:44:19: fatal error: wchar.h: No such file or directory
    compilation terminated.
    make: *** [build/c_api/c_api_error.o] Error 1
    make: *** Waiting for unfinished jobs....
    g++-5 -c -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -DDISABLE_OPENMP src/logging.cc -o build/logging.o
    g++-5 -c -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -DDISABLE_OPENMP src/c_api/c_api.cc -o build/c_api/c_api.o
    In file included from include/xgboost/data.h:10:0,
                     from src/c_api/c_api.cc:3:
    dmlc-core/include/dmlc/base.h:190:23: fatal error: sys/types.h: No such file or directory
    compilation terminated.
    make: *** [build/c_api/c_api.o] Error 1
    In file included from /usr/local/Cellar/gcc@5/5.5.0_3/include/c++/5.5.0/bits/postypes.h:40:0,
                     from /usr/local/Cellar/gcc@5/5.5.0_3/include/c++/5.5.0/bits/char_traits.h:40,
                     from /usr/local/Cellar/gcc@5/5.5.0_3/include/c++/5.5.0/string:40,
                     from rabit/include/rabit/rabit.h:13,
                     from src/logging.cc:7:
    /usr/local/Cellar/gcc@5/5.5.0_3/include/c++/5.5.0/cwchar:44:19: fatal error: wchar.h: No such file or directory
    compilation terminated.
    make: *** [build/logging.o] Error 1
    g++-5 -c -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -DDISABLE_OPENMP src/learner.cc -o build/learner.o
    In file included from /usr/local/Cellar/gcc@5/5.5.0_3/include/c++/5.5.0/cstdio:42:0,
                     from dmlc-core/include/dmlc/io.h:8,
                     from src/learner.cc:7:
    /usr/local/Cellar/gcc@5/5.5.0_3/lib/gcc/5/gcc/x86_64-apple-darwin17.7.0/5.5.0/include-fixed/stdio.h:78:20: fatal error: _stdio.h: No such file or directory
    compilation terminated.
    make: *** [build/learner.o] Error 1
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/r1/cys3qrkn49s1jlghjldg3tk40000gq/T/pip-install-_0gsveuo/xgboost/setup.py", line 42, in <module>
        LIB_PATH = libpath['find_lib_path']()
      File "/private/var/folders/r1/cys3qrkn49s1jlghjldg3tk40000gq/T/pip-install-_0gsveuo/xgboost/xgboost/libpath.py", line 48, in find_lib_path
        'List of candidates:\n' + ('\n'.join(dll_path)))
    XGBoostLibraryNotFound: Cannot find XGBoost Library in the candidate path, did you install compilers and run build.sh in root path?
    List of candidates:
    /private/var/folders/r1/cys3qrkn49s1jlghjldg3tk40000gq/T/pip-install-_0gsveuo/xgboost/xgboost/libxgboost.dylib
    /private/var/folders/r1/cys3qrkn49s1jlghjldg3tk40000gq/T/pip-install-_0gsveuo/xgboost/xgboost/../../lib/libxgboost.dylib
    /private/var/folders/r1/cys3qrkn49s1jlghjldg3tk40000gq/T/pip-install-_0gsveuo/xgboost/xgboost/./lib/libxgboost.dylib
    /Users/prasad.seemakurthi/xgboost/xgboost/libxgboost.dylib
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by hcho3** [comment]
Try installing gcc 9 with `brew install gcc@9`

**Comment by trivialfis** [comment]
While fixing the Travis test, I think most of the problems are matching GCC with xcode.  GCC 9 is currently used in Travis and is the default formula in brew if one runs update.

**Comment by prasadseemakurthi** [comment]
@hcho3  Have tried that but still failing.

**Comment by hcho3** [comment]
Try `CC=gcc-9 CXX=g++-9 pip install xgboost`

**Comment by trivialfis** [comment]
@hcho3 Can this be closed?

**Comment by hcho3** [comment]
Fixed by https://github.com/dmlc/xgboost/pull/5146. Try running

```
git clone --recursive https://github.com/dmlc/xgboost 
mkdir build
cd build
cmake ..
make
```
