### ISSUE TITLE
predict_proba doesn't work with gblinear

### ISSUE THREAD

**Issue by beojan** [dmlc/xgboost#5116]
`predict_proba` fails when the booster is `gblinear` and early stopping is used because `best_ntree_limit` is set, even though `ntree_limit` makes no sense in this case.

**Comment by WDYIE** [comment]
ntree_limit limit the number of trees used in prediction, when it equals 0, this means we do not limit number of trees, this parameter is only valid for gbtree, but not for gblinear

**Comment by hcho3** [comment]
Related: #3789
