### ISSUE TITLE
RNG seeding interface is inconsistent between Python and R

### ISSUE THREAD

**Issue by Kodiologist** [dmlc/xgboost#5121]
It appears that in R, XGBoost's `seed` parameter is ignored and R's built-in seed (set via `set.seed`) has an effect, whereas in Python, the `seed` parameter has an effect (and is set by default), but the seed and random states of both `random`'s and NumPy's RNGs are ignored. Maybe there's a good reason for this inconsistency, but it doesn't seem to be documented. Neither interface's behavior seems to be documented at all.

<details>
<summary>Examples with DART</summary>

I use xgboost master, Python 3.7.5, and R 3.6.1.

A demonstration of Python's behavior is:

```python
import xgboost as xgb

d = xgb.DMatrix('demo/data/agaricus.txt.train')

def f(**kwargs):
    print(xgb.train(
        params = dict(
            objective = 'binary:logistic',
            booster = 'dart',
            one_drop = True,
            **kwargs),
        dtrain = d,
        num_boost_round = 50).predict(d, ntree_limit = 50)[:2])

f()

import random
random.seed(3)
f()
random.seed(4)
f()

import numpy
numpy.random.RandomState(3)
f()
numpy.random.RandomState(4)
f()

f(seed = 3)
```

This prints five copies of `[9.9776614e-01 9.8952930e-04]`, followed by `[9.9804425e-01 7.7316642e-04]`.

A demonstration of R's behavior (with a function `f` just like the one in the Python example) is:

```R
library(xgboost)

d = xgb.DMatrix('demo/data/agaricus.txt.train')

f = function(...)
    print(predict(
        xgb.train(
            params = list(
                objective = 'binary:logistic',
                booster = 'dart',
                one_drop = TRUE,
                ...),
            data = d,
            nrounds = 50),
        newdata = d,
        ntree_limit = 50)[c(1, 2)])

set.seed(3)
f()
set.seed(3)
f()

f(seed = 3)
f(seed = 3)
```

This prints:

```
[1] 0.997079611 0.001121833
[1] 0.997079611 0.001121833
[1] 0.996737778 0.001056993
[1] 0.997706652 0.001064884
```
</details>

**Comment by trivialfis** [comment]
Em.  Like many other functions, R requires specialized implementation of seed.  Will look into it later.  Currently out for travel.

**Comment by trivialfis** [comment]
@Kodiologist @pommedeterresautee @hcho3  Actually I'm not familiar with R's ecosystem.  Is there any reason why C extension has to use those R specialized functions?  Is that a policy on CRAN?

**Comment by hcho3** [comment]
@trivialfis Yes, all R packages should respect the seed set in a R session,
