### ISSUE TITLE
Unknown parameters are silently ignored

### ISSUE THREAD

**Issue by Kodiologist** [dmlc/xgboost#5124]
Thus, for example, if the user misspells a parameter name, they may never notice their mistake.

**Comment by trivialfis** [comment]
I'm working on this with a lots of PRs already been merged.  Should have some loose validation in recent future that can catch typos.  But precise one still need some more work.

**Comment by Kodiologist** [comment]
Cool. Yeah, I think that just checking that the name is a real parameter name will go a long way, and should be much easier to implement than checking whether the parameter values make sense.

**Comment by RAMitchell** [comment]
@trivialfis has literally been working on this for over a year :) We hope to resolve it soon.

**Comment by trivialfis** [comment]
Closed as a duplication of https://github.com/dmlc/xgboost/issues/4211 .
