### ISSUE TITLE
any way to see which features were selected for each tree, level, split?

### ISSUE THREAD

**Issue by h17** [dmlc/xgboost#5132]
Thanks for participating in the XGBoost community! We use https://discuss.xgboost.ai for any general usage questions and discussions. The issue tracker is used for actionable items such as feature proposals discussion, roadmaps, and bug tracking.  You are always welcomed to post on the forum first :)

Issues that are inactive for a period of time may get closed. We adopt this policy so that we won't lose track of actionable issues that may fall at the bottom of the pile. Feel free to reopen a new one if you feel there is an additional problem that needs attention when an old one gets closed.

For bug reports, to help the developer act on the issues, please include a description of your environment, preferably a minimum script to reproduce the problem.

For feature proposals, list clear, small actionable items so we can track the progress of the change.

**Comment by hcho3** [comment]
@h17 Try using [`dump_model()` function](https://xgboost.readthedocs.io/en/latest/python/python_api.html#xgboost.Booster.dump_model).

Example:
```python
bst = xgboost.train(...)
bst.dump_model('./model_dump.txt')
```

**Comment by h17** [comment]
Hello Philip,

This is not what I was asking: I used dump_model but one crucial piece of
information that is missing is which features were chosen via colsample_by*

**Comment by trivialfis** [comment]
@h17 You can't do that.  It's really internal to XGBoost.  You can see `ColumnSampler` in `src/common/random.h`.  It's used all tree method except `approx`.

**Comment by hcho3** [comment]
@trivialfis We could potentially add an Observer to ColumnSampler?

**Comment by trivialfis** [comment]
@hcho3 It will take some efforts to extend the observer for enabling customization via user parameters.  I incline to keep it internal, curious users can look into the code for internal data.

**Comment by hcho3** [comment]
@trivialfis For now, it should be sufficient to dump everything and let the (expert) user filter the dumped output. Let me put together something this weekend.

**Comment by h17** [comment]
That would be ideal to have everything, might also help zooming in on other phenomena later. For what I was looking right now I just need to sum gain for each feature over all instances where it participated after ColumnSampler selection, lets call this gain_opportunity. Then you use this to divide total_gain obtaining another feature importance, i.e. competitiveness=total_gain/gain_opportunity which is in my opinion better than the 5 you have at the moment. I can back this up with many simple examples, but I think the simplest to think about is the following: first tree almost always has highest gain because it gets first cut so to say, so if the feature is not there for that first cut neither of the metrics will capture this.  This can be reduced by ensemble of xgb and other techniques but still measuring competitiveness will reduce noise from the start.
