### ISSUE TITLE
Slowdown observed on 16-GPU DGX-2

### ISSUE THREAD

**Issue by JohnZed** [dmlc/xgboost#5140]
Running the RAPIDS mortgage benchmark with 48 parts on a DGX-2 with 16 GPUs, we see a recent slowdown.

* New = Commit 4ec13613e99aee5332fd9b3a8de74e87973edc9f (https://github.com/rapidsai/xgboost/commits/rapids-0.11-release) - Dec 7
* Old = Commit 7e72a12871eaa0ebc46e863dabe8657e3f0557ad (https://github.com/rapidsai/xgboost/commits/rapids-0.10-release) - Oct 15

New time:  165.6s
Old time: 147.4s

(On the other hand, for a cluster of 5x DGX-1, we see a slight speedup - about 5%).
Have not reproduced these on a smaller node yet.

**Comment by trivialfis** [comment]
@JohnZed Can we close this one?

**Comment by JohnZed** [comment]
Yes, I think this is outdated now - recent perf with DDQDM has been good and should be the baseline going forward.
