### ISSUE TITLE
xgb.plot.tree.R print leaf value

### ISSUE THREAD

**Issue by kennyhelsens** [dmlc/xgboost#515]
The xgb.plot.tree.R function the R package does not print the value for the observation to end in a particular leaf. Now it just prints 'leaf', it would greatly facilitate the interpretation of the trees if these values would be shown in the diagram.

**Comment by pommedeterresautee** [comment]
How do you interpret this value?

**Comment by DeluxeAnalyst** [comment]
You can look at the dump file for the actual values, which are log-odds estimates.

**Comment by pommedeterresautee** [comment]
I just tried the following:
```R
> library("xgboost", lib.loc="~/R/win-library/3.2")
> data(agaricus.train, package='xgboost')
> data(agaricus.test, package='xgboost')
> train <- agaricus.train
> test <- agaricus.test
> bst <- xgboost(data = train$data, label = train$label, max.depth = 2,
+                eta = 1, nthread = 2, nround = 2,objective = "binary:logistic")
[0]	train-error:0.046522
[1]	train-error:0.022263
> # save the model in file 'xgb.model.dump'
> xgb.dump(bst, 'xgb.model.dump', with.stats = TRUE)
[1] TRUE
> 
> # print the model without saving it to a file
> print(xgb.dump(bst))
 [1] "booster[0]"                                  "0:[f28<-1.00136e-005] yes=1,no=2,missing=1"  "1:[f55<-1.00136e-005] yes=3,no=4,missing=3" 
 [4] "3:leaf=1.71218"                              "4:leaf=-1.70044"                             "2:[f108<-1.00136e-005] yes=5,no=6,missing=5"
 [7] "5:leaf=-1.94071"                             "6:leaf=1.85965"                              "booster[1]"                                 
[10] "0:[f59<-1.00136e-005] yes=1,no=2,missing=1"  "1:[f28<-1.00136e-005] yes=3,no=4,missing=3"  "3:leaf=0.784718"                            
[13] "4:leaf=-0.96853"                             "2:leaf=-6.23624"                            
> 
```

The leaf score is sometimes negative.
I don't feel you can interpret it, but I may be wrong.

Kind regards,
Michaël

**Comment by DeluxeAnalyst** [comment]
From my exploration, the leaf scores are log odd estimates. You can turn them into a probability by taking exp(score) / (1+exp(score)). Though this would be only the probability for this given leaf. The final output of the model is determined by adding up all of these leaf scores for a given record across all trees, and then calculating the probability from that, given you are doing a logistic regression problem.

**Comment by krishnateja614** [comment]
How would we know the class of a new test example using this decision tree. I'm using the python package and it ends with leaf score, is there any way to use this score to compute which class the new point might actually belong to?

**Comment by pommedeterresautee** [comment]
Please, have a look to the documentation: https://xgboost.readthedocs.io/en/latest/model.html

**Comment by krishnateja614** [comment]
Thanks for pointing me to this tutorial. Sorry I couldn't find it myself.

**Comment by nishkalavallabhi** [comment]
I am also looking for some help file on how to interpret the leaf nodes and their scores. How should I figure out what class is the leaf node referring to?

**Comment by pommedeterresautee** [comment]
@nishkalavallabhi you can provide a mapping between feature name and feature id to the dump function on both R and Python.
@krishnateja614 I think it s beyond the issues of related to XGBoost, it s more about your understanding of boosting. I can advise you to read Friedman papers if you want to go deeper.

**Comment by nishkalavallabhi** [comment]
@pommedeterresautee  - Thanks. My question was actually more closer to @krishnateja614 's question. I should perhaps start with the reading you mentioned to understand what the leaf node scores signify.
