### ISSUE TITLE
Removing num_roots breaks tree lite.

### ISSUE THREAD

**Issue by trivialfis** [dmlc/xgboost#5164]
Echoing from @sperlingxx , tree lite checks num_roots parameter internally, we should keep maintenance for this parameter in recent future.

**Comment by hcho3** [comment]
@trivialfis Treelite only checks if the number of roots is 1. It can be removed.

**Comment by trivialfis** [comment]
@hcho3  It wasn't too difficult to keep it, we can leave it there and deprecate it along with binary IO when JSON is production ready.  This way we can show a proper warning.
