### ISSUE TITLE
How to use XGBoost to realize the prediction problem of multiple regression? For example, the input is two-dimensional and the output is three-dimensional. The examples I have seen are all unary regression problems.

### ISSUE THREAD

**Issue by LIUJIENANliujienan** [dmlc/xgboost#5168]
Thanks for participating in the XGBoost community! We use https://discuss.xgboost.ai for any general usage questions and discussions. The issue tracker is used for actionable items such as feature proposals discussion, roadmaps, and bug tracking.  You are always welcomed to post on the forum first :)

Issues that are inactive for a period of time may get closed. We adopt this policy so that we won't lose track of actionable issues that may fall at the bottom of the pile. Feel free to reopen a new one if you feel there is an additional problem that needs attention when an old one gets closed.

For bug reports, to help the developer act on the issues, please include a description of your environment, preferably a minimum script to reproduce the problem.

For feature proposals, list clear, small actionable items so we can track the progress of the change.

**Comment by trivialfis** [comment]
On Python, you can use scikit-learn's multi output regressor for convenience.  It builds one model for each output.  For single model multi-target, it's still under development.

**Comment by LIUJIENANliujienan** [comment]
Thank you so much，I did it by “from sklearn.multioutput import MultiOutputRegressor” and obtained what I need.
