### ISSUE TITLE
Loading big sparse matrices from R

### ISSUE THREAD

**Issue by BlindApe** [dmlc/xgboost#517]
I continue dealing with big sparse (more than 2^31 non zero cells) matrices in R. The problem isn't RAM memory but internally sparse matrices use an integer array for indexing, so the limit of 2^31 is reached much before than ram limit.
I compute the three components of the sparse matrix (p, i and x) but instead of call sparseMatrix function (which crash) I store it in a list structure.
Then I changed xgb.DMatrix function adding option for 'list' type of data parameter:

xgb.DMatrix <- function(data, info = list(), missing = 0, ...) {
  if (typeof(data) == "character") {
    handle <- .Call("XGDMatrixCreateFromFile_R", data, as.integer(FALSE), 
                    PACKAGE = "xgboost")
  } else if (is.matrix(data)) {
    handle <- .Call("XGDMatrixCreateFromMat_R", data, missing, 
                    PACKAGE = "xgboost")
  } else if (class(data) == "dgCMatrix") {
    handle <- .Call("XGDMatrixCreateFromCSC_R", data@p, data@i, data@x, 
                    PACKAGE = "xgboost")
  } else if (class(data) == "list") {
    handle <- .Call("XGDMatrixCreateFromCSC_R", data$p, data$i, data$x, 
                    PACKAGE = "xgboost")
  } else {
    stop(paste("xgb.DMatrix: does not support to construct from ", 
               typeof(data)))
  }
  dmat <- structure(handle, class = "xgb.DMatrix")
  
  info <- append(info, list(...))
  if (length(info) == 0) 
    return(dmat)
  for (i in 1:length(info)) {
    p <- info[i]
    xgb.setinfo(dmat, names(p), p[[1]])
  }
  return(dmat)
}

With this work around I thought I will solve the problem, but xgboost sent an error message tell me INTEGER() can't be applied to double type array.

I need to use numeric (double) type for the 'p' and 'i' components in the structure where I store the data because otherwise R replace all values greater than 2^31 with NA.

@tqchen , @hetong007  could you please check in lines 111 and 112 of xgboost_R.cpp and convert the double arrays to integer arrays in the C++ side?

If you can, adding the 'list' option to xgb.DMatrix we will solve the big sparse matrix issue.

Thank you.

**Comment by BlindApe** [comment]
I want to share more experiences in this issue and hope be useful.

344M x 78 matrix with 3000M non zero entries (M = Million)

1) data.table is aprox. 120 Gb. Converting to matrix and then load to xgb reach 256 Gb and crash the R session.

2) sparse.model.matrix takes several hours and then crash (integer exceded), so I wrote a custom sparse model matrix that savesthe components (p, i, x) in three elements of a list. Then I tried the 'tuned' xgb.DMatrix and obtained the message INTEGER() can't be applied to double type array. If I convert the elements of the list to integer, R replaces all values greater then 2^31 with NA.

3) The svmlight way. I write an R optimized procedure to write this super matrix to svmlight format (140 minutes in process and write to disk). The file size in disk is aprox 40 Gb so this was promissing. Then I loaded with xgb.DMatrix and after load only 53 Gb of the RAM was used. Great, xgboost will run without wasted ram (so I could use 5x size matrices than this I thought).
But the problem is TIME. The loading time of this file in xgb.DMatrix was 1094 minutes!

**Comment by tqchen** [comment]
The libsvm parser should now be optimized in the new version, #735  which can comes at 100M /sec

**Comment by tqchen** [comment]
Again it is always great to hear from good experience from you, we could try to start think of direct data.frame integration given good enough proposal.

**Comment by BlindApe** [comment]
Sorry @tqchen , I dind' see this until I find it again to reference in a new PR I read you are working.
Weel, the main problem (for me) with use libsvm format is when you work with extra big dataset as I do, write to a libsvm file is very very expensive.
As I know xgboost use internally column based sparse matrix so why a file format which is row based?
The best plain file format would be in triplets (row, column, value). This is easy of generate from any language and don't need matrix transposition in xgboost so you can use almost 100% or RAM.
2^31 seems to be a wall in some points, as I said in my previous message. Using a input format as list() in R will avoid part of this (the other part is the INTEGER() conversion in C++ side. I think using a plain text file will let you load data from a fresh instance and avoid 2^31 limits.
