### ISSUE TITLE
Error on creating DMatrix from sparse matrix with indices in int64

### ISSUE THREAD

**Issue by kretes** [dmlc/xgboost#5175]
When creating a dmatrix from csr matrix that has more than int32 elements (and therefore uses int64 index) - error is thrown.

you can find the script to reproduce this issue in https://gist.github.com/kretes/c3e96567975a727e6e6971f440a8b0e3

the output in xgboost 0.90 I get is:

```
---------------------------------------------------------------------------
SystemError                               Traceback (most recent call last)
<ipython-input-10-c4eb335ee525> in <module>
----> 1 ds = xgb.DMatrix(csr, y)

/usr/local/lib/python3.5/dist-packages/xgboost/core.py in __init__(self, data, label, missing, weight, silent, feature_names, feature_types, nthread)
    398             self.handle = handle
    399         elif isinstance(data, scipy.sparse.csr_matrix):
--> 400             self._init_from_csr(data)
    401         elif isinstance(data, scipy.sparse.csc_matrix):
    402             self._init_from_csc(data)

/usr/local/lib/python3.5/dist-packages/xgboost/core.py in _init_from_csr(self, csr)
    435         handle = ctypes.c_void_p()
    436         _check_call(_LIB.XGDMatrixCreateFromCSREx(c_array(ctypes.c_size_t, csr.indptr),
--> 437                                                   c_array(ctypes.c_uint, csr.indices),
    438                                                   c_array(ctypes.c_float, csr.data),
    439                                                   ctypes.c_size_t(len(csr.indptr)),

/usr/local/lib/python3.5/dist-packages/xgboost/core.py in c_array(ctype, values)
    215     if isinstance(values, np.ndarray) and values.dtype.itemsize == ctypes.sizeof(ctype):
    216         return (ctype * len(values)).from_buffer_copy(values)
--> 217     return (ctype * len(values))(*values)
    218 
    219 

SystemError: ../Objects/tupleobject.c:71: bad argument to internal function
 ` ``

**Comment by trivialfis** [comment]
From the error it seems `indices` field being problematic, which is column indices instead of row pointer.  In the example there's only 1001 columns, I'm not sure why does it require a int64 array to store it.

**Comment by kretes** [comment]
I believe the fact that int64 is used comes due to the number of values in the data, not columns.
I deliberately set

```
num_rows = int(np.iinfo(np.int32).max / 1000)
num_cols = 1001
```
so that I get slightly more values than int32.

nevermind the reason for an int64 array for indices - it still should be supported, right?

**Comment by RAMitchell** [comment]
Two options here: 

- Create a new API function that accepts CSR with 64-bit column indices, create a new adapter class

- Create a 32 bit copy of the column indices on the python side, perhaps with a warning.

@kretes if you submit a PR for option 2, I would be happy with that.

**Comment by kretes** [comment]
actually the easy-to-introduce workaround for me currently is to use
`DMatrix(csr.todense())`

**Comment by trivialfis** [comment]
Fixed in https://github.com/dmlc/xgboost/pull/6675 .
