### ISSUE TITLE
interaction_constraints with more than 10^5 parameters fail.

### ISSUE THREAD

**Issue by palVJ** [dmlc/xgboost#5179]
Using xgb.train with more than 10^5 parameters and using the parameter interaction_constraints, I get the following error:

Error in xgb.iter.update(bst$handle, dtrain, iteration - 1, obj) :
  [09:54:20] ./dmlc-core/include/dmlc/././json.h:788: Check failed: ch == ',' (101 vs. ,) : Error at Line 0, around ^`+05,100001,100002,100003,100004,100005,100006,100007,100008,100`, JSON array expect ']' or ','. Get 'e' instead

I suspect 100001, 100002 and so on represent feature indices with values more than 100 000.
I tried with feature indices with values less than 100 000, and it worked.

Am I right, and if so, can this be fixed?

**Comment by trivialfis** [comment]
Em.. there's scientific notation in the indices string.  Should be able to fix it.

**Comment by palVJ** [comment]
Using R and input parameter interaction_constraints does not contain
numbers with scientific notation. Seems there is something to do with the
source code, but I may be wrong.

tor. 2. jan. 2020, 16:28 skrev Jiaming Yuan <notifications@github.com>:

**Comment by trivialfis** [comment]
The parameters are passed as string into XGBoost, a quick workaround right now is to disable R's scientific representation used by paste.  Will further investigate a proper solution.
