### ISSUE TITLE
Can I set parameter: 'seed' value when using Python API of xgboost?

### ISSUE THREAD

**Issue by supernovaf117** [dmlc/xgboost#518]
I set the same seed in param dict, but xgb outputs different result each time. This problem didn't happen when I used xgb.conf file to train xgb. By the way, whether is the Python-xgboost slower than direct using xgb.conf when training?

**Comment by tqchen** [comment]
All the language bindings of xgboost should runs at exactly the same speed. For simple models, the result should be reproducible. But there can be indetermism due to floating point rounding errors. see http://xgboost.readthedocs.org/en/latest/faq.html#slightly-different-result-between-runs
