### ISSUE TITLE
Windows "No CUDA toolset found"

### ISSUE THREAD

**Issue by fordicus** [dmlc/xgboost#5184]
**What I am doing**
> Build "https://github.com/dmlc/xgboost.git" with GPU support on Windows

**Trouble**
>I fail at **cmake** stage to **configure** a Visual Studio solution.
I encounter **Performing Test XGBOOST_BUILTIN_PREFETCH_PRESENT - Failed**,
and **No CUDA toolset found**

**Environment**
- Windows 10 x64
- NVCC (NVIDIA CUDA Compiler) release 10.2, V10.2.89
- MSVC (Microsoft Visual C++) 19.24.28314.0 from Visual Studio 16 2019

**cmake command**
>cmake .. -DUSE_CUDA=ON

**cmd.exe prints**
>**C:\workspace\xgboost-gpu\build>nvcc --version**
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:32:27_Pacific_Daylight_Time_2019
Cuda compilation tools, release 10.2, V10.2.89
>
>**C:\workspace\xgboost-gpu\build>cmake .. -DUSE_CUDA=ON**
-- Building for: Visual Studio 16 2019
-- The CXX compiler identification is MSVC 19.24.28314.0
-- The C compiler identification is MSVC 19.24.28314.0
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- CMake version 3.16.2
-- Performing Test XGBOOST_MM_PREFETCH_PRESENT
-- Performing Test XGBOOST_MM_PREFETCH_PRESENT - Success
-- Performing Test XGBOOST_BUILTIN_PREFETCH_PRESENT
**-- Performing Test XGBOOST_BUILTIN_PREFETCH_PRESENT - Failed**
-- xgboost VERSION: 1.0.0
-- **Configured CUDA host compiler**: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe
**CMake Error at C:/Program Files/CMake/share/cmake-3.16/Modules/CMakeDetermineCompilerId.cmake:352 (message):
  No CUDA toolset found.**
**Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.16/Modules/CMakeDetermineCompilerId.cmake:32 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  C:/Program Files/CMake/share/cmake-3.16/Modules/CMakeDetermineCUDACompiler.cmake:72 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:90 (enable_language)**
>
>-- Configuring incomplete, errors occurred!
See also "C:/workspace/xgboost-gpu/build/CMakeFiles/CMakeOutput.log".
See also "C:/workspace/xgboost-gpu/build/CMakeFiles/CMakeError.log".

**log files that would help**
> You may refer to build\CMakeFiles from the link below
> https://drive.google.com/open?id=1KUYmHD7VtBiWfFBvWkPlAwmX42TAzmkl

**Question**
>Why does it fail to locate CUDA toolset while I don't find any problem with Visual Studio and CUDA if I compile a C++ project of my own? Should I downgrade NVCC and MSVC? If so, what is a safe way to do that?

Thanks.

**Comment by trivialfis** [comment]
@RAMitchell

**Comment by trivialfis** [comment]
Probably a due to the fact that we use native CMake cuda language support while you are using the older CUDA CMake module.  I don't think it's XGBoost related, please consider opening an issue on CMake gitlab.  Thanks.
