### ISSUE TITLE
XGBoostError  when  run custom_rmsle.py

### ISSUE THREAD

**Issue by Riario14** [dmlc/xgboost#5185]
macOS Catalina, xgboost 0.90.

> XGBoostError: [16:01:20] src/metric/metric.cc:23: Unknown metric function rmsle

when run demo custom_rmsle.py

**Comment by hcho3** [comment]
To run the custom_rmsle, you will need to compile XGBoost from the latest source, as 0.90 release is not compatible with it.

**Comment by trivialfis** [comment]
@hcho3 Can we set the link of doc to latest release instead of master?  Or a more obvious label that shows one is reading doc in master branch?

**Comment by hcho3** [comment]
<img width="362" alt="Screen Shot 2020-01-06 at 12 37 29 AM" src="https://user-images.githubusercontent.com/2532981/71806098-c759f380-301c-11ea-83c9-7504874968cb.png">

There is the version selector at the bottom right corner of the doc page. I do think that the version can be made clearer. See example at https://cmake.org/cmake/help/v3.12/command/target_link_libraries.html
