### ISSUE TITLE
XGBRanker for Spark API

### ISSUE THREAD

**Issue by polnaranjo** [dmlc/xgboost#5195]
Hi, 

I've been using XGBRanker with scikit-learn API and would like to use it with Spark as well. Is this in the roadmap or will occur any time soon? Thanks.

**Comment by trivialfis** [comment]
@wbo4958

**Comment by trivialfis** [comment]
I thought Scala supports Ranking?

**Comment by CodingCat** [comment]
spark binding already supports it, just pass those obj functions as usual

**Comment by trivialfis** [comment]
Great!
