### ISSUE TITLE
Why there's no gpu_approx?

### ISSUE THREAD

**Issue by xybramble** [dmlc/xgboost#5200]
Currently exact and hist are supported for GPU acceleration. I wonder why there's no approx gpu implementation? It is because of approx algorithm or it's related to kind of GPU features?

**Comment by trivialfis** [comment]
@xybramble Actually we removed `gpu_exact` in latest master branch (and hence next release).  As our experiments show that `hist` method is more efficient in every way.

**Comment by xybramble** [comment]
Actually I wonder if it is possible to implement gpu_approx theoretically? We think of approx because we want to improve the accuracy which did not meet expectations when using gpu_hist.

**Comment by trivialfis** [comment]
@xybramble Theoretically yes, it's possible.  But I would like to know what your dataset looks like that trips over the hist algorithm.

**Comment by RAMitchell** [comment]
I believe the approx algorithm re-computes quantiles dynamically where the 'hist' algorithms compute quantiles upfront and then use them for the rest of the training. I would guess that gpu_hist could be adapted to work well for you depending on the reason why training accuracy is not so great. 

For example you can set the number of bins for quantisation to a larger number if the granularity of the splits is too large. You can also change between loss guided or depth wise training.

**Comment by xybramble** [comment]
@trivialfis My datasets are files of strings. @trivialfis @RAMitchell Thanks a lot.  
Current results of mine show accuracy of approx is higher than hist when setting same rounds and other parameters at CPU version. So maybe it can be expected that approx at GPU version can also get a higher accuracy than hist? Or parameters in cpu hist can be adjusted for a better performance at this condition? Actually I considered adjusting number of bins before but my device didn't support (out of memory) when changed to more rounds..

**Comment by trivialfis** [comment]
Optimization for memory consumption is a priority now, at least for GPU.
