### ISSUE TITLE
When is 1.0 being released finally? FutureWarning: Series.base is deprecated and will be removed in a future version

### ISSUE THREAD

**Issue by adam-ah** [dmlc/xgboost#5205]
This bug has been fixed https://github.com/dmlc/xgboost/issues/4300 over half a year ago on master, but [the last release was almost a year ago](https://pypi.org/project/xgboost/#history).

There have been hundreds of commits on this repo since then; could we please get a release to get all these changes from the past half a year?

**Comment by hcho3** [comment]
There are a few pull requests marked as "Blocking." We are working hard to get 1.0 out. For now, you should look into using the nightly builds. See instructions at https://xgboost.readthedocs.io/en/latest/build.html.
