### ISSUE TITLE
Approve XGBoost logo use

### ISSUE THREAD

**Issue by Crissman** [dmlc/xgboost#5213]
Thank you for adding the Optuna integrated badge to the README.md page.

We would like to use the XGBoost logo on our [optuna.org](https://optuna.org) web page to make it easier for XGBoost users to find the example for using Optuna with XGBoost.

<img width="1118" alt="Screen Shot 2020-01-17 at 17 04 04" src="https://user-images.githubusercontent.com/4338467/72594859-d78e9e80-394b-11ea-84fe-7ec302d2c8b9.png">

Please approve use of the XGBoost logo.

Thanks!

**Comment by trivialfis** [comment]
@tqchen

**Comment by tqchen** [comment]
LGTM to me, leaving for others to object

**Comment by trivialfis** [comment]
@Crissman Go ahead .  :-)
