### ISSUE TITLE
Unit test failing due to floating-point fluctuation

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#5226]
This unit test is currently failing:

https://github.com/dmlc/xgboost/blob/aa9a68010b3bc6ae5d6ee5b60db7cbb3ef5530f0/tests/python-gpu/test_from_columnar.py#L98-L107

See https://xgboost-ci.net/blue/organizations/jenkins/xgboost/detail/PR-5187/8/pipeline/#step-332-log-1167

Fix: use `np.testing.assert_array_almost_equal(decimal=5)` instead of `assert np.array_equal(*)`.

**Comment by trivialfis** [comment]
@RAMitchell is looking into it I believe.  The errq is not deterministic.  I'm currently don't have access to working devices.   Relax the test is necessary.

**Comment by RAMitchell** [comment]
I expect this was fixed in #5229, let's reopen if it happens again.
