### ISSUE TITLE
Passing new argument from python to C++ and making changes in C++ code 

### ISSUE THREAD

**Issue by contactlp** [dmlc/xgboost#5239]
I am new with xgboost. I have been somewhat successful editing xgboost c++ code, but the new argument is hard coded in C++.  I want to pass argument from python to C++. How can I do that ?

I am pretty good with python, so I dont need help there. I am ok in C++, but I dont get how python is passing stuff to C++. I would appreciate if someone help me with that. 

FYI, I have added argument to [ColSample](https://github.com/dmlc/xgboost/blob/master/src/common/random.h#L95) method and then want to access the argument from python.

example:
```
  std::shared_ptr<HostDeviceVector<bst_feature_t>> ColSample(
      std::shared_ptr<HostDeviceVector<bst_feature_t>> p_features, float colsample)
```
to
```
  std::shared_ptr<HostDeviceVector<bst_feature_t>> ColSample(
      std::shared_ptr<HostDeviceVector<bst_feature_t>> p_features, float colsample, 
     std::vector<float> v)
```
Thank you in advance. 
Lav

**Comment by RAMitchell** [comment]
Looks like you are trying to pass in a vector. Is this a hyperparameter?

See the way interaction constraints and monotone constraints are passed in to see how to add vector hyperparameters.

**Comment by contactlp** [comment]
@RAMitchell , yes it is hyperparameter for now as a first expriment.

I was thinking to pass in python like this.

```
xg_reg = xgb.XGBRegressor(
    objective ='reg:linear',
    colsample_bytree = 0.3,
    learning_rate = 0.1,
    max_depth = 5,
    alpha = 10,
    n_estimators = 2,
)
```
to
```
xg_reg = xgb.XGBRegressor(
    objective ='reg:linear',
    colsample_bytree = 0.3,
    learning_rate = 0.1,
    max_depth = 5,
    alpha = 10,
    n_estimators = 2,
   p = [0.3,0.5,0.2]
)
```
Thanks

**Comment by trivialfis** [comment]
It's passed by Python Booster::set_param.  I'm sure you can track down the rest.

**Comment by trivialfis** [comment]
These parameters are passed as string, and in C++ we define a subclass to `XGBoostParameter`, which can restore a vector from string.
