### ISSUE TITLE
OS Error : [WinError -529697949] Windows Error 0xe06d7363 running XGBClassifier with large dataset, CPU Mode

### ISSUE THREAD

**Issue by Shameendra** [dmlc/xgboost#5242]
Getting this error while trying to run XGBClassifier and GridsearchCV for hyperparameter optimization. I have seen this issue being opened but closed and marked resolved but no solution provided. has anyone actually found a soultion to this error?

My dataset :

    X = np array with 350000 rows and 1715 columns (after one hot encoding)
    y = 350000 rows and 1 column (target)

Code:

    X = train.drop(['Breakage'], axis=1,)  #features (read from dataframe)
    y = train['Breakage']    #target (read from dataframe)

    X= X.as_matrix()    #convert to np array
    y= y.as_matrix()    #convert to np array
    y = np.reshape(y,(-1, 1))    #reshape array

    X = X.astype('uint8')  #Change dtype to avoid overcommmit error in windows
    y = y.astype('uint8')  #Change dtype to avoid overcommmit error in windows
 
    #define estimators and learning rate
    model = XGBClassifier()
    n_estimators = [100, 200, 300, 400, 500]
    learning_rate = [0.0001, 0.001, 0.01, 0.1]

    # GRidSearchCV
    param_grid = dict(learning_rate=learning_rate, n_estimators=n_estimators)
    kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=7)
    grid_search = GridSearchCV(model, param_grid, n_jobs=-1, cv=kfold)
    grid_result = grid_search.fit(X,y)

The output error i get is:

    ---------------------------------------------------------------------------
    _RemoteTraceback                          Traceback (most recent call last)
    _RemoteTraceback: 
    """
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\joblib\externals\loky\process_executor.py", line 418, in _process_worker
        r = call_item()
      File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\joblib\externals\loky\process_executor.py", line 272, in __call__
        return self.fn(*self.args, **self.kwargs)
      File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\joblib\_parallel_backends.py", line 567, in __call__
        return self.func(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\joblib\parallel.py", line 225, in __call__
        for func, args, kwargs in self.items]
      File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\joblib\parallel.py", line 225, in <listcomp>
        for func, args, kwargs in self.items]
       File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\model_selection\_validation.py", line 514, in _fit_and_score
         estimator.fit(X_train, y_train, **fit_params)
      File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\xgboost\sklearn.py", line 726, in fit
        missing=self.missing, nthread=self.n_jobs)
      File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\xgboost\core.py", line 404, in __init__
        self._init_from_npy2d(data, missing, nthread)
      File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\xgboost\core.py", line 495, in _init_from_npy2d
    nthread))
    OSError: [WinError -529697949] Windows Error 0xe06d7363
    """

    The above exception was the direct cause of the following exception:

    OSError                                   Traceback (most recent call last)
    <ipython-input-63-8d03f4d93f3b> in <module>
          2 kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=7)
          3 grid_search = GridSearchCV(model, param_grid, n_jobs=-1, cv=kfold)
     ----> 4 grid_result = grid_search.fit(X,y)

    C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\model_selection\_search.py in fit(self, X, y, groups, **fit_params)
        685                 return results
        686 
    --> 687             self._run_search(evaluate_candidates)
        688 
        689         # For multi-metric evaluation, store the best_index_, best_params_ and

    C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\model_selection\_search.py in _run_search(self, evaluate_candidates)
       1146     def _run_search(self, evaluate_candidates):
       1147         """Search all candidates in param_grid"""
    -> 1148         evaluate_candidates(ParameterGrid(self.param_grid))
       1149 
       1150 

    C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\model_selection\_search.py in evaluate_candidates(candidate_params)
        664                                for parameters, (train, test)
        665                                in product(candidate_params,
    --> 666                                           cv.split(X, y, groups)))
        667 
        668                 if len(out) < 1:

    C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\joblib\parallel.py in __call__(self, iterable)
        932 
        933             with self._backend.retrieval_context():
    --> 934                 self.retrieve()
        935             # Make sure that we get a last message telling us we are done
        936             elapsed_time = time.time() - self._start_time

    C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\joblib\parallel.py in retrieve(self)
        831             try:
        832                 if getattr(self._backend, 'supports_timeout', False):
    --> 833                     self._output.extend(job.get(timeout=self.timeout))
        834                 else:
        835                     self._output.extend(job.get())

    C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\joblib\_parallel_backends.py in wrap_future_result(future, timeout)
        519         AsyncResults.get from multiprocessing."""
        520         try:
    --> 521             return future.result(timeout=timeout)
        522         except LokyTimeoutError:
        523             raise TimeoutError()

    C:\ProgramData\Anaconda3\envs\tensorflow\lib\concurrent\futures\_base.py in result(self, timeout)
        430                 raise CancelledError()
        431             elif self._state == FINISHED:
    --> 432                 return self.__get_result()
        433             else:
        434                 raise TimeoutError()

    C:\ProgramData\Anaconda3\envs\tensorflow\lib\concurrent\futures\_base.py in __get_result(self)
        382     def __get_result(self):
        383         if self._exception:
    --> 384             raise self._exception
        385         else:
        386             return self._result

    OSError: [WinError -529697949] Windows Error 0xe06d7363

**Comment by trivialfis** [comment]
Not entirely sure but might be an out of memory.   Could you please help verifying that.  Grid searching with Python is sometimes problematic as Python's garbage collection is lazy, so the constructed DMatrix object is not cleared after each iteration.

**Comment by Shameendra** [comment]
@trivialfis Thanks for the reply. When i Reduce the number of features(columns), then  Grid searching with Python works wiothout errors. So it could indeed be possible that it is an out of memory error(But how do i Confirm that?) Maybe using a GPU helps? I will try to run it using a GPU and update as soon as i get the time to run my code

**Comment by trivialfis** [comment]
One workaround is to force garbage collection by using Python `gc` module at each search iteration.

**Comment by Shameendra** [comment]
Thanks for the tip i will try it and let you know

**Comment by Shameendra** [comment]
Hi @trivialfis I can confirm that it is indeed an out of memory error. when i reduce the number of samples and features, grid search works without errors. I have found some examples of implementing garbage collector with XGBoost and i hope that can solve the issue. Thanks again for the reply.
