### ISSUE TITLE
Improving compatibility with Scikit-learn

### ISSUE THREAD

**Issue by daviddiazvico** [dmlc/xgboost#5254]
According to the [Scikit-learn development guide](https://scikit-learn.org/stable/developers/develop.html#parameters-and-init), the `__init__` method should not do any parameter validation or set any "trailing _" parameter.

In order to have an estimator compatible with the automated hyper-parameter search objects (GridSearchCV, RandomizedSearchCV, skopt.BayesSearchCV, etc.), that should be handled by the `fit` method.

In particular, the validation of `missing` and the instantiation of `_Booster` should be moved from `__init__` to the beginning of `fit` in the sklearn wrapper.

Related PR: #5255 

Thanks!

**Comment by trivialfis** [comment]
PR is merged.  Thanks!  The guide will help a lot in the future.
