### ISSUE TITLE
read csv files from s3 and set the train data label column index failed

### ISSUE THREAD

**Issue by Tesla9999** [dmlc/xgboost#5259]
I am trying to read csv files on s3, need to set the train data label column index, for example run '../xgboot mushroom.aws.conf', in the xgb conf file:
data='s3://bucket/file_name.csv?format=csv&label_column=0'
The '&label_column=0' is giving me trouble, '?format=csv' is working fine and '?format=csv&label_column=0' works for local file.
the error message is:

terminate called after throwing an instance of 'dmlc::Error'
what(): [02:33:54] src/io/s3_filesys.cc:1096:
SignatureDoesNotMatchThe request signature we calculated does not match the signature you provided. Check your key and signing method.

Thanks a lot!

**Comment by allaela1** [comment]
close #kistek/boss-demo#3

**Comment by trivialfis** [comment]
Please consider using more standard libraries for loading remote files. I think we will eventually deprecate the network data reading in XGBoost and recommend users use other data preprocessing tools like spark or dask.
