### ISSUE TITLE
Issue when create java wrapper-- cannot find jni.h

### ISSUE THREAD

**Issue by crazyseabiscuit** [dmlc/xgboost#526]
Hello Guys
I am trying to use xgboost in my java code , so I did the following:
Compiling most recent xgboost pull on Mac , I can run build.sh and can see xgboost is generated in single thread mode.

After that ,I enter java dir and enter create_wrapper.sh but got below error:
-------------------------------------------------------------------------------------------------------------------------------
$ create_wrap.sh 
build java wrapper
g++ -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -fopenmp -fPIC -fPIC -shared -o java/libxgboostjavawrapper.so java/xgboost4j_wrapper.cpp wrapper/xgboost_wrapper.cpp updater.o gbm.o io.o subtree/rabit/lib/librabit.a dmlc_simple.o -pthread -lm  -I/include -I/include/linux -I./java
java/xgboost4j_wrapper.cpp:15:10: fatal error: 'jni.h' file not found
#include <jni.h>
         ^
1 error generated.
In file included from wrapper/xgboost_wrapper.cpp:16:
In file included from wrapper/../src/learner/learner-inl.hpp:17:
In file included from wrapper/../src/learner/./objective.h:67:
In file included from wrapper/../src/learner/objective-inl.hpp:19:
wrapper/../src/learner/../utils/omp.h:15:9: warning: Warning: OpenMP is not
      available,xgboost will be compiled into single-thread code.Use
      OpenMP-enabled compiler to get benefit of multi-threading
      [-W#pragma-messages]
#pragma message("Warning: OpenMP is not available,"\
        ^
1 warning generated.
make: *** [java/libxgboostjavawrapper.so] Error 1
move native lib
mv: rename libxgboostjavawrapper.so to xgboost4j/src/main/resources/lib/libxgboostjavawrapper.so: No such file or directory 
------------------------------------------------------------------------------------------------------------------------------

Regards
Chen

**Comment by yanqingmen** [comment]
hi, Chen. sorry I haven't tested create_wrapper.sh on Mac since I have no OS X environment. Until now the java wrapper may not work properly on OS X. I'll try to add an instruction for OS X recently.

**Comment by playmobil** [comment]
Same issue for me, it seems create_wrapper.sh cannot work properly on Mac OS, could you fix the bug for Mac users recently?

**Comment by damiencarol** [comment]
I had same issue. Check you Java paths. Like jkd path or java home path.

**Comment by terrytangyuan** [comment]
Has this been fixed? @yanqingmen

**Comment by damiencarol** [comment]
@terrytangyuan It is NOT a bug. When using the script _create_wrapper.sh_ one must set the JAVA_HOME env variable. That's all.

**Comment by terrytangyuan** [comment]
@damiencarol Thanks for letting me know! Good to know it's working on Mac.
