### ISSUE TITLE
Documentation about running multiple jobs per GPU

### ISSUE THREAD

**Issue by szkocot** [dmlc/xgboost#5266]
When running the hyperparameter tuning cross-validation pipeline, we were able to finish multiple boosting model training processes on a single GPU. GPU memory and core usage have increased and for smaller models, it seems to scale pretty well. I haven't found anything about it. Is there a chance to make it "official" by documenting this feature?

**Comment by trivialfis** [comment]
I'm not sure why is it a feature.  Independent processes don't interfere each others.  The limitation is we can't run multiple cooperating processes using distributed training on same GPU.
