### ISSUE TITLE
Link to the supplementary material doesn't work

### ISSUE THREAD

**Issue by harupy** [dmlc/xgboost#5273]
[The XGBoost paper](https://www.kdd.org/kdd2016/papers/files/rfp0697-chenAemb.pdf) says a detailed description of the weighted quantile sketch is given in the link below. I tried to open it, but got Not-Found Error.  

http://homes.cs.washington.edu/˜tqchen/pdf/xgboost-supp.pdf

**Comment by trivialfis** [comment]
There is a reference section in the readme.  Use that link.
