### ISSUE TITLE
[XGBClassifier and xgb.Booster] => to and from each other

### ISSUE THREAD

**Issue by Jie-Yuan** [dmlc/xgboost#5286]
[XGBClassifier and xgb.Booster] => to and from each other

**Comment by trivialfis** [comment]
XGBClassifier defines a label encoder from scikit learn to enable both predict and predict_prob .  The encoder doesn't exit on native booster and rely on user to do the feature engineering.

Look into the fit method and I think it should be easy for you to make the conversion, as you have the data to define this encoder.
