### ISSUE TITLE
the leaf info for multi-class model during dump booster is wrong

### ISSUE THREAD

**Issue by yupbank** [dmlc/xgboost#5289]
```
import xgboost as xgb
from sklearn.datasets import make_classification
x, y = make_classification(n_classes=3, n_informative=10)
model = xgb.XGBClassifier(n_estimators=1, max_depth=1).fit(x, y)
booster = model.get_booster()
print(booster.get_dump()[0])
```
 outputs this 
```
0:[f2<-5.2242012] yes=1,no=2,missing=1
	1:leaf=0.119999997
	2:leaf=-0.0128686372
```
here the leaf section doesn't mean anything towards prediction. 
i did try `booster.tree_to_dataframe()` which gives similar makes no sense results

**Comment by trivialfis** [comment]
It's the weight of leaf.  The final prediction is `softmax(sum of weights)` .

**Comment by yupbank** [comment]
I'm not exactly sure what weight it is. since the prediction would be a 3d vector. and the leaf only outputs 1 scalar. 

here it is a 3 class classification

**Comment by trivialfis** [comment]
XGBoost employs 1 stack of trees for 1 class.  So for 3 classes there will be 3 stacks of trees.  Each tree leaf contains a scalar output called weight.  Please refer to the tutorial in our documents for an explanation of tree models.

**Comment by yupbank** [comment]
interesting.. so it's different from the sklearn.tree.DecisionTreeClassifier. Thanks for the clarification.

**Comment by yupbank** [comment]
a follow-up question, how does the stack behave when there is more than 1 estimator?  
`[estimator_1_class_1, estimator_1_class_2, estimator_1_class_3, estimator_2_class_1, estimator_2_class_2, estimator_2_class_3]` 
or

`[estimator_1_class_1, estimator_2_class_1, estimator_1_class_2, estimator_2_class_2, estimator_1_class_3, estimator_2_class_3]`

**Comment by yupbank** [comment]
```
import xgboost as xgb
from sklearn.datasets import make_regression
import numpy as np
x, y = make_regression( n_informative=10)
y = np.vstack([y,y]).T
model = xgb.XGBRegressor(n_estimators=1, max_depth=1).fit(x, y)
assert model.predict(x).shape == y.shape, "prediction should have same shape as fitting"
```

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-36-002dbd19397c> in <module>()
      5 y = np.vstack([y,y]).T
      6 model = xgb.XGBRegressor(n_estimators=1, max_depth=1).fit(x, y)
----> 7 assert model.predict(x).shape == y.shape, "prediction should have same shape as fitting"

AssertionError: prediction should have same shape as fitting

**Comment by trivialfis** [comment]
@yupbank The trees are handled internally in XGBoost.  You don't have to do anything special for it.
