### ISSUE TITLE
Early stopping using xgb.cv in Python

### ISSUE THREAD

**Issue by ivallesp** [dmlc/xgboost#529]
Hello,

I'm trying to set the early stopping parameter while I use xgb.cv:

bst = xgb.cv(plst, dtrain, num_round, evallist, early_stopping_rounds=30)

It crashes and returns me:

TypeError: cv() got an unexpected keyword argument 'early_stopping_rounds'

Is there any way of using early stopping with the cv method?

Thank you

**Comment by aszalucha** [comment]
There is no early stopping for cv in python

**Comment by ivallesp** [comment]
What a pity, it would be a great approach!

**Comment by JamesMorse** [comment]
I'll second the request for early stopping in the cv() method!

**Comment by Far0n** [comment]
How is that supposed to work?
a) Early stopping on each fold independently
b) Early stopping if error last fold stopped deceasing
c) Early stopping if error on average err across all folds stopped deceasing

In my opinion c) makes most sense.

**Comment by JamesMorse** [comment]
Definitely (c).  The point is to stop wasting cycles building more
iterations when it is clear that the optimal number of trees for a given
set of hyper-parameters (shrinkage, min tree depth, row / column sample %,
etc.) has already been reached.  Also, it ought to have a parameter/option
for how many iterations to continue without the average CV error decreasing
below the previous minimum average CV error.  The default probably should
be stop after the first iteration where the average CV error does not
decrease.  Having this feature greatly expedites the CV grid search
process!!

I believe this functionality has already been implemented in the xgboost R
package though -- just not in the Python module.

**Comment by Far0n** [comment]
So be it.

**Comment by terrytangyuan** [comment]
@JamesMorse Are you working on a PR for this? Let others know so the work won't get repeated.

**Comment by Far0n** [comment]
PR created (https://github.com/dmlc/xgboost/pull/602)

**Comment by JamesMorse** [comment]
No, I haven't done any work on it.
