### ISSUE TITLE
Monotonic Constraints - Only Partially Working

### ISSUE THREAD

**Issue by emmanueltsukerman** [dmlc/xgboost#5296]
Full code can be found [here ](https://github.com/emmanueltsukerman/Monotonic-XGBoost-Demo/blob/master/Monotonic%20XGBoost.ipynb).

Basically, I have two features, x_1 and x_2. I constrain x_2 to be monotonic. I take an example 
(a, b) that is classified as "c".  Then I create another example, (a', b). If monotonicity works, then example (a',b) should be classified as "c" as well. But that's not necessarily the case. 

I know that my "monotonic" classifier is different from an unconstrained classifier because it is more likely to output "c", but still it doesn't satisfy the above logic.

Any thoughts on what is happening here?

**Comment by jxucoder** [comment]
why should example (a',b) be classified as "c"?

**Comment by hcho3** [comment]
You constrained x_2 to be monotonic, not x_1. So we don't know how (a, b) and (a', b) are related, since we only changed x_1.
