### ISSUE TITLE
【Python】Floating-point precision of the split node

### ISSUE THREAD

**Issue by XTmingyue** [dmlc/xgboost#5298]
I have encountered an unusual situation: 

A model shows the split point for a particular node as follows:

`4:[f21<166.666702] yes=9,no=10,missing=9`

If I feed in an observation where f21 = 166.6667 the python model incorrectly sends this to the yes node. I've limited the number of floating-point numbers in Python to four decimal places.

**Comment by trivialfis** [comment]
How do you limit floating point precision in Python?

**Comment by Denisevi4** [comment]
It's a problem of model dump. It needs to print those values in the scientific format and with higher precision.

Same thing applies not only to the feature values, but also to the leaf weights.

**Comment by Denisevi4** [comment]
166.6667 < 166.666702

Should be a yes node. Or am I missing something?

**Comment by trivialfis** [comment]
Floating point printing is a very tricky thing, it has round off:
```
In [1]: print('{:.17f}'.format(166.666702))                                                                                                                                                                 
166.66670199999998658
```

**Comment by trivialfis** [comment]
Also 1.0.2 is now out.  Feel free to try to experimental JSON format.
