### ISSUE TITLE
xgboost  when installed has 2 native library paths (duplicated installation paths for xgboost)

### ISSUE THREAD

**Issue by bninopaul** [dmlc/xgboost#5300]
I have an ubuntu os and when I installed `xgboost==0.9` using pip in a virtual environment, I found 2 similar installation paths, is this a bug or an intended configuration?
In my `py3env` environment, I got these 2 paths of xgboost, which one is the right path that `xgboost` is using?
1. `py3env/xgboost/libxgboost.so`
2. `py3env/lib/python3.6/site-packages/xgboost/lib/libxgboost.so`

**Comment by trivialfis** [comment]
Fixed in master branch.  Feel free to reopen the issue if needed.

**Comment by sabgit** [comment]
@trivialfis When can we expect to have the next release from the master branch to the Pypi registry? Thanks

**Comment by trivialfis** [comment]
1.0 should be really close now.  But this fix is not included, estimated time is 2 months after 1.0.
