### ISSUE TITLE
Libsvm with unordered features breaks gpu_hist

### ISSUE THREAD

**Issue by RAMitchell** [dmlc/xgboost#5301]
A libsvm file with a row such as below creates undefined behaviour
`0 1:3400 0:170`
The gpu_hist algorithm assumes that rows of data are ordered by feature. It uses binary search over sparse rows to find specific matrix elements, and the binary search fails due to incorrect ordering. There may be other cases of this assumption inside xgboost that I am not aware of.

The bug is very subtle and manifests in slightly incorrect training results where the algorithm designates elements as missing because the binary search can't find them.

We need some way to detect such cases and log a fatal error, preferably across all xgboost algorithms. We can modify the dmlc parser to check for this case, although it is not strictly wrong according to any specification, or we could detect it somewhere in xgboost constructors.

**Comment by thvasilo** [comment]
I think I may have seen this issue in one of the CPU algorithms (most probably approx) when I was creating libsvm files by hand to test out stuff.

The libsvm format assumes that features are order as well or is that only in XGBoost?

**Comment by RAMitchell** [comment]
The libsvm format checker does seem to indicate that features should be ordered, see at the end of this readme: https://github.com/cjlin1/libsvm/tree/master/tools

I think we can do the validation directly in dmlc parser.
