### ISSUE TITLE
python model thread safety when used in pyspark

### ISSUE THREAD

**Issue by Seanspt** [dmlc/xgboost#5307]
We are using python to build models. In order to get the predictions of  billions of sample, we are using the pickle dumped model with pyspark.
We are aware that xgboost model is not thread safe. So in spark， we load the model each time for each partition as the following code
```python
def mapPartition(p):
    with open(model_path, 'rb') as f:
        model = pickle.load(f)
    # then predict with the loaded model
    # ...
predictions = rdd.mapPartitions(mapPartition)
```
When we set the executor cores num to 4, there is 1 out of 10k chance that the prediction result would be different with running with a single process python script.

However, when we set the executor cores num to 1, the prediction results would perfectly match with the result get with a single process python script.

Yet we do not know the cause of it. And we have to fix the executor cores to 1 and use a lot more memory to run our jobs.

**Comment by trivialfis** [comment]
The prediction function is not thread safe right now,  closing as duplicated with #4841 .
