### ISSUE TITLE
Enable weighted sampling of features

### ISSUE THREAD

**Issue by lutzvdb** [dmlc/xgboost#5308]
In our random forest models (using the R package "ranger") we frequently use weighted sampling of features (argument "split.select.weights", compare official documentation [here](https://cran.r-project.org/web/packages/ranger/ranger.pdf) ). I would like to apply the same logic to xgboost trees, as in my usecase I frequently know which variables play a more important role for a certain forecast period (we do time series analysis). I already utilize feature sampling using colsample_bytree and colsample_bynode, so I would greatly appreciate being able to alter the probabilities for column sampling.

**Comment by hcho3** [comment]
Related: https://github.com/dmlc/xgboost/issues/3754, https://github.com/dmlc/xgboost/issues/4230

**Comment by trivialfis** [comment]
I will look into this.
