### ISSUE TITLE
XGBoost setup.py refers to sklearn instead of scikit-learn

### ISSUE THREAD

**Issue by victornoel** [dmlc/xgboost#5309]
According to the pypi page of sklearn, one should use the name `scikit-learn` to depend on it.

See https://pypi.org/project/sklearn/

**Comment by trivialfis** [comment]
Just out of curious, how do I test installing extra packages locally?

**Comment by victornoel** [comment]
@trivialfis I think you can do something like `pip install /path/to/xgboost/python-package[sklearn]`

**Comment by victornoel** [comment]
@trivialfis or maybe you need to be inside the directory and do `pip install .[sklearn]`, I'm not sure
