### ISSUE TITLE
silent parameter in Python

### ISSUE THREAD

**Issue by ivallesp** [dmlc/xgboost#531]
Hello,

I'm trying to mute the algorithm in Python as the documentation says (with the parameter "silent = 1") but it seems that it does not work. This is the snippet of code I am using:

param = {'bst:subsample': _subsample,
             'bst:colsample_bytree':_colsample_bytree,
             'bst:max_depth':_max_depth,
             'bst:min_child_weight':_min_child_weight,
             'bst:eta':_eta, 
             'bst:max_delta_step':_max_delta_step,
             'bst:gamma':_gamma,
             'bst:lambda':_lambda,
             'bst:alpha':_alpha,
             'nthread':_nthread,
             'silent':1,
             'objective':'binary:logistic',
             'eval_metric': 'auc',}

fit = xgb.train(param, dtrain, num_round, evallist, early_stopping_rounds=5)

Am I doing something bad? is it a bug in the original code?

Thank you,
Iván

**Comment by walterreade** [comment]
`silent: 1` indeed turns off a lot of information, but it does not suppress the evaluation. Try adding `verbose_eval=False` at the end of your `train` arguments.

**Comment by ivallesp** [comment]
Wow! it works, thank you. Now the problem is that it still shows me messages like this:

Will train until eval error hasn't decreased in 5 rounds.
Will train until eval error hasn't decreased in 5 rounds.
Will train until eval error hasn't decreased in 5 rounds.

Could they be removed?

Thank you so much

**Comment by walterreade** [comment]
I believe you'd have to change the   `python-package/xgboost/training.py` file (line 84) to get what you want.

**Comment by ivallesp** [comment]
Ok thank you, I commented this line

**Comment by terrytangyuan** [comment]
@ivallesp Should be silent now by this commit (https://github.com/dmlc/xgboost/commit/610b70b79ee3a6f4d0ad888ef917ef76f87b0cdc)

**Comment by karthiksubramanians** [comment]
Hi, I did not want to open up a new thread for a similar issue.
I have Ubuntu 16.04 x64 with Python 3.6.5
I have xgboost version 0.80 with verbose_eval = False in xgb.train

But it still prints 06:44:39] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 10 extra nodes, 0 pruned nodes, max_depth=4
[06:44:39] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 10 extra nodes, 0 pruned nodes, max_depth=4
[06:44:39] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 10 extra nodes, 0 pruned nodes, max_depth=4
[06:44:39] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 10 extra nodes, 0 pruned nodes, max_depth=4
[06:44:39] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 10 extra nodes, 0 pruned nodes, max_depth=4
[06:44:39] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 10 extra nodes, 0 pruned nodes, max_depth=4

message like this. How could i stop this?
