### ISSUE TITLE
Support of AVX and AVX2 commands

### ISSUE THREAD

**Issue by sh1ng** [dmlc/xgboost#532]
Have you considered it to speed-up the performance?

**Comment by tqchen** [comment]
Yes, the old problem is current version of algorithm is not really vectorized. I will think more on this, to see if we can get a real vectorized version

**Comment by sh1ng** [comment]
I've tried to recompile the project with
* AVX/AVX2 enabled SSE2 disabled
* no SSE2 and AVX at all
(all on ubuntu x64)
and it looks like the performance is the same(I did it by my eyes, not a precise benchmark).
Do you have any kind of reference data set to measure the performance?
