### ISSUE TITLE
When to drop Python 3.5

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#5338]
Python 3.5 is reaching its end-of-life on September this year. I'd like to start a discussion to decide when we should stop supporting Python 3.5.

Personally, I would really love to use f-strings to format strings, and f-string is only available in Python 3.6+.

**Comment by Iqrar99** [comment]
Agree, using f-string is a good decision. I would like to work on this.

**Comment by JohnZed** [comment]
Release 1.1 could be a good time to drop it?  Complete EOL of 3.5 is September this year, so certainly no lead to go that long...

**Comment by trivialfis** [comment]
@hcho3 Let's pin it to 1.2.

**Comment by hcho3** [comment]
1.2 sounds good.

**Comment by hcho3** [comment]
As of #5388, we will require Python 3.6+.
