### ISSUE TITLE
Alphanumeric feature names

### ISSUE THREAD

**Issue by ytsaig** [dmlc/xgboost#534]
The restriction to have feature_names in DMatrix objects be all alphanumeric seems a bit restrictive. In particular not allowing underscore makes it hard to use descriptive feature names that are multi-word. Is it possible to loosen this requirement to exclude only specific characters?

**Comment by sinhrks** [comment]
This was to be safe as first impl (#488). Currently I assume we can use characters other than ``[``, ``]`` and ``<``. 

https://github.com/dmlc/xgboost/blob/master/src/tree/model.h#L405

@tqchen If I understand properly, I will prepare a fix.

**Comment by tqchen** [comment]
I think as long as the feature name convention is compatible with the python symbol(what you can write in python), say ```feature_1```, we are good enough

**Comment by gatapia** [comment]
+1
