### ISSUE TITLE
xgboost 1.0.1 cpu-parallel execution: run ok, but DEBUG FAILS (PyCharm, LiClipse)

### ISSUE THREAD

**Issue by markusmaresch** [dmlc/xgboost#5344]

**Comment by markusmaresch** [comment]
Not sure if this is a bug, expected, or being worked on. 
Debug does NOT work with parallel execution, while simply running DOES. Could be a PyCharm or PyDev issue. The 7-liner below demonstrates it. Run: fine; Debug: not
I can live with workarounds
Thanks !!

xgboost: 1.0.1
PyCharm: Community 2019.3.3
LiClipse: <older version>
macOS: 10.15.3
RUN: works fine
DEBUG: errors (PyCharm)
       File "/Users/<user>/Library/Application Support/JetBrains/Toolbox/apps/
          PyCharm-C/ch-0/193.6494.30/PyCharm CE.app/Contents/plugins/python-ce/
          helpers/pydev/_pydevd_bundle/pydevd_comm.py", line 283, in _on_run
           r = self.sock.recv(1024)
       OSError: [Errno 9] Bad file descriptor
       <and more>
       PyCharm does NOT complete

DEBUG: errors (LiClipse)
       File "/Applications/LiClipse.app/Contents/Eclipse/
                plugins/org.python.pydev.core_7.0.3.201811081803/pysrc/_pydevd_bundle/
                pydevd_comm.py", line 273, in _on_run
           r = self.sock.recv(1024)
       OSError: [Errno 9] Bad file descriptor#
       <and more>
       LiClipse completes after lots of bitching.


from sklearn.model_selection import GridSearchCV
from sklearn.datasets import load_boston
import xgboost as xgb
boston = load_boston()
xgb_model = xgb.XGBRegressor(n_jobs=-1)
clf = GridSearchCV(xgb_model, {'max_depth': [1, 2, 3], 'n_estimators': [102, 105, 107]}, verbose=1, n_jobs=-1)
clf.fit(boston['data'], boston['target'])

**Comment by trivialfis** [comment]
It's not expected.  Honestly I have never encountered bad file descriptor in Python.

**Comment by trivialfis** [comment]
I don't have access to PyCharm.  If anyone here does please help taking a look.  This seems weird as XGBoost doesn't use any Python file descriptor in above example.

**Comment by markusmaresch** [comment]
I am adding the full trace of the PyCharm session. Suspecting it is something with backend LokyBackend !!
[xgb_101_debug_issue.txt](https://github.com/dmlc/xgboost/files/4239416/xgb_101_debug_issue.txt)

**Comment by markusmaresch** [comment]
Pure pdb is also fine: python -m pdb xgb_101_debug_issue.py  ... works as in RUN

**Comment by markusmaresch** [comment]
Suggesting to close. Really is this problem: https://youtrack.jetbrains.com/issue/PY-36882

**Comment by trivialfis** [comment]
Great! You found the issue!
