### ISSUE TITLE
Eval displays 'nan' with 'reg:gamma' objective and 'gblinear' booster

### ISSUE THREAD

**Issue by gorkemozkaya** [dmlc/xgboost#5349]
I noticed the tree evals keep displaying 'nan's with  'reg:gamma' objective and 'gblinear' booster. The default eval metric for "reg:gamma" objective is "gamma-nloglik". Below is the notebook that can reproduce the issue: 
https://github.com/gorkemozkaya/ds_debugging/blob/master/xgboost_gamma_regression.ipynb

**Comment by honzasterba** [comment]
I have also found similar behaviour behaviour. Here is the script used to reproduce.

https://gist.github.com/honzasterba/79bfcb95e6c183479b45218a40b8af3b

 Is this a bug?

**Comment by neemah2o** [comment]
@hcho3 , can you verify if this is a bug?
