### ISSUE TITLE
 function 'XGBoosterSaveJsonConfig' not found

### ISSUE THREAD

**Issue by blenzus** [dmlc/xgboost#5354]
Upgraded XGBoost from latest version to 1.0.0 and then 1.0.1.
Config : Win10 + Anaconda

Running the below command produces the error : 
`xgb.fit(X,y)` : 

> function 'XGBoosterSaveJsonConfig' not found

**Comment by cockroachzl** [comment]
I got the same error in Ubuntu 18.04 and Python 3.6.10. Tried xgboost 1.0.0, 1.0.1, and 1.0.2, all got the same error. However downgrading xgboost version to 0.90 works without issues. Any solution?

**Comment by hcho3** [comment]
It looks like there's more than one installation of XGBoost and you are picking up an old copy of `libxgboost.so`. Try searching for `libxgboost.so` in your system.

**Comment by blenzus** [comment]
> I got the same error in Ubuntu 18.04 and Python 3.6.10. Tried xgboost 1.0.0, 1.0.1, and 1.0.2, all got the same error. However downgrading xgboost version to 0.90 works without issues. Any solution?

The problem was that i had 2 versions of xgboost installed. pip freeze your current env and check the version you're currently using.
