### ISSUE TITLE
Trying to convert a sklearn.multioutput.MultiOutputRegressor for xgboost 1.0.0

### ISSUE THREAD

**Issue by simonefrancia** [dmlc/xgboost#5355]
Hi,
we saw that xgboost was updated at 1.0.0. 
We have developed one model from version 0.9.0 that we would like to convert in order to be compatible with 1.0.0. We tried to use this script
https://github.com/dmlc/xgboost/blob/master/doc/python/convert_090to100.py
but it doesn't work , because our train was done with `sklearn.multioutput.MultiOutputRegressor` that wraps the original `xgboost.XGBRegressor`. This script stopped at line 33 :
```
if not isinstance(old, xgboost.XGBModel):
            raise TypeError(
                'The script only handes Scikit-Learn interface object')
```
How can we resolve this situation? 
Thanks

**Comment by trivialfis** [comment]
@simonefrancia Did you save it in pickle?

**Comment by simonefrancia** [comment]
Yes @trivialfis , the file is pickle but I used joblib.

```joblib.dump(multioutputregressor, MODEL_PATH) ```

**Comment by simonefrancia** [comment]
Yes @trivialfis , the file is pickle but I used joblib.

```joblib.dump(multioutputregressor, MODEL_PATH) ```

**Comment by trivialfis** [comment]
I'm not sure how to restore that wrapper.  It's part of sciki learn not XGBoost. I think even for scikit learn loading a pickle from different version is not supported?  https://scikit-learn.org/stable/modules/model_persistence.html

**Comment by trivialfis** [comment]
That conversation script only handles model defined in XGBoost, external wrappers are quite out of our scope.  My suggestion is save each XGBoost model in native model file by calling `save_model`.  We recommended using pickle for a while then we realized there's no way we can restore the Python bytecode.
