### ISSUE TITLE
Distributed XGBoost Model Using(prediction task)

### ISSUE THREAD

**Issue by vivounicorn** [dmlc/xgboost#536]
@tqchen hi tanqi
I have training data set about 1T and model using data set about 100G，now we can train model with the help of "Distributed XGBoost" but can we use model with "Distributed XGBoost"?
the example: https://github.com/dmlc/wormhole/blob/master/learn/xgboost/run_yarn.sh
../dmlc-core/yarn/run_hdfs_prog.py ../xgboost mushroom.hadoop.conf task=pred model_in=final.model test:data=data/agaricus.txt.test
all model using data （predict） is in local disk.

**Comment by tqchen** [comment]
@vivounicorn  Unfortunately current code do not yet support online prediction. Unless you do it in external memory mode. I know it is a bit dumb. And this is something we should improve in the future.

What you can do is you can run the prediction task using the prediction API. We can also modify the xgboost.dmlc a bit to allow it to predict distributedly

**Comment by vivounicorn** [comment]
@tqchen thanks very much.
