### ISSUE TITLE
How to Explain the XGboost Model

### ISSUE THREAD

**Issue by vivounicorn** [dmlc/xgboost#537]
hi @tqchen sorry to bother again, I have some questions as following:
How to explain the xgboost model result and find the better features when we have many trees?
what's the meaning of every node(yes/no，leaf)？
is there some references?
Example:
![default](https://cloud.githubusercontent.com/assets/3362154/10408873/b15ff6a6-6f3c-11e5-96a5-58edfa9b5051.png)

3qvm

**Comment by tqchen** [comment]
Here is one detailed material about the mode behind xgboost http://xgboost.readthedocs.org/en/latest/model.html

**Comment by vivounicorn** [comment]
ok 3ks alot
