### ISSUE TITLE
[jvm-packages] rabit tracker error "Socket Poll Error:WSAError-code=10022"

### ISSUE THREAD

**Issue by jyk4100** [dmlc/xgboost#5370]
Hi ,

I am trying to use xgboost4j-spark on local machine before testing on cluster. I keep getting into issues 
>     Socket Poll Error:WSAError-code=10022
>     Socket Poll Error:WSAError-code=10022

**settings**
- spark-shell (spark-2.4.5-bin-hadoop2.6)
- xgboost4j-0.90-criteo-20190702_2.11-win64.jar
- xgboost4j-spark-0.90-criteo-20190702_2.11.jar
- akka-actor_2.11-2.3.11.jar
- config-1.2.1.jar

**example (iris data)**
```
// import
import org.apache.spark.ml.feature.{VectorAssembler, VectorIndexer, StringIndexer}
import org.apache.spark.sql.types.{DoubleType, StringType, StructField, StructType, IntegerType}
// data prep
val schema = new StructType().add("sepal_length",DoubleType,true).add("sepal_width",DoubleType,true).add("petal_length",DoubleType,true).add("petal_width",DoubleType,true).add("species",StringType,true)
val iris = spark.read.schema(schema).option("header","true").format("csv").load("path/iris.csv")
val testDF = iris.withColumn("class", when(col("species") === "setosa",1).otherwise(0))
val vectorAssembler = new VectorAssembler().setInputCols(Array("sepal_length", "sepal_width", "petal_length", "petal_width")).setOutputCol("features")
val xgbInput = vectorAssembler.transform(testDF).selectExpr("features", "class")
// model params and training
import ml.dmlc.xgboost4j.scala.spark.{XGBoostClassifier, TrackerConf}
val paramMap = ( List("eta" -> 0.1f, "scale_pos_weight"->10, "objective"->"binary:logistic", "seed" -> 123, "silent" -> 1, "tracker_conf"->TrackerConf(60 * 60 * 1000, "scala"),
					  "missing"->0.0, "lambda"->0.7, "alpha"->0, "max_depth"->3, "min_child_weight"->2.0, "round"->10, "num_workers"->2).toMap )
val initmodel = new XGBoostClassifier(paramMap).setFeaturesCol("features").setLabelCol("class")
val model = initmodel.fit(xgbInput)
```
**error message**
INFO] [02/27/2020 00:15:49.458] [RabitTracker-akka.actor.default-dispatcher-3] [akka://RabitTracker/user/Handler] Tracker listening @ 192.168.8.148:33348
[INFO] [02/27/2020 00:15:49.459] [RabitTracker-akka.actor.default-dispatcher-3] [akka://RabitTracker/user/Handler] Worker connection timeout is 1 hour.
20/02/27 00:15:49 WARN XGBoostSpark: train_test_ratio is deprecated since XGBoost 0.82, we recommend to explicitly pass a training and multiple evaluation datasets by passing 'eval_sets' and 'eval_set_names'
[INFO] [02/27/2020 00:15:50.207] [RabitTracker-akka.actor.default-dispatcher-7] [akka://RabitTracker/user/Handler] Received start signal from DESKTOP-TLIQ86V [rank: 0]
[INFO] [02/27/2020 00:15:50.208] [RabitTracker-akka.actor.default-dispatcher-7] [akka://RabitTracker/user/Handler] Received start signal from DESKTOP-TLIQ86V [rank: 1]
[INFO] [02/27/2020 00:15:50.217] [RabitTracker-akka.actor.default-dispatcher-7] [akka://RabitTracker/user/Handler] Worker 192.168.8.148 (rank: 0) has started.
[INFO] [02/27/2020 00:15:50.222] [RabitTracker-akka.actor.default-dispatcher-3] [akka://RabitTracker/user/Handler] Worker 192.168.8.148 (rank: 1) has started.
[INFO] [02/27/2020 00:15:50.222] [RabitTracker-akka.actor.default-dispatcher-3] [akka://RabitTracker/user/Handler] All workers have started.
Socket Poll Error:WSAError-code=10022
Socket Poll Error:WSAError-code=10022

**Comment by caizd1994** [comment]
I have same problem as yours

**Comment by caizd1994** [comment]
@CodingCat

**Comment by caizd1994** [comment]
@hcho3

**Comment by caizd1994** [comment]
"num_workers" -> 4 改成 1 重启电脑好了，num_workers不能大于local[1]。
change from  "num_workers" -> 4 to 1
and restart  then it work
it seems that int local mode, num_workers must == 1

**Comment by jyk4100** [comment]
tried on windows local and yes num_workers must be 1
