### ISSUE TITLE
evals_result not correct with multiple eval_metrics in python 

### ISSUE THREAD

**Issue by JohanManders** [dmlc/xgboost#538]
When using **one eval_metric** like 'auc' and run xgb.train(param, dtrain, num_round, watchlist, evals_result=evals_result), the evals_result dict contains the right information.

Example output xgb.train one eval_metric:
```
[0]	eval-auc:0.960373	train-auc:0.958228
[1]	eval-auc:0.960373	train-auc:0.958228
```
Content evals_result:
```
{'eval': ['0.960373', '0.960373'], 'train': ['0.95822', '0.95822']}
```
But when using **multiple eval_metrics** like 'auc' and 'logloss', the evals_result takes the wrong data.

Example output xgb.train two eval_metrics:
```
[0]	eval-auc:0.960373	eval-logloss:0.676689	train-auc:0.958228	train-logloss:0.676836
[1]	eval-auc:0.960373	eval-logloss:0.660871	train-auc:0.958228	train-logloss:0.661159
```
Content evals_result:
```
{'eval': ['0.960373', '0.960373'], 'train': ['0.676689', '0.660871']}
```
It puts the **eval-logloss** values in the **train column**

An example screenshot:
![xgb_eval_metrics](https://cloud.githubusercontent.com/assets/14052555/10413117/114179b6-6f9f-11e5-9a7c-4daf7f64118a.png)

**Comment by gusuperstar** [comment]
i met similar issue. is there an answer?

**Comment by gusuperstar** [comment]
i met similar issue. the auc score is always around 0.99. is there an answer?

**Comment by quansie** [comment]
I made some changes to the original XGBoost code to be able to read all the data from evals_result and made a pull request. You can see the code [here](https://github.com/quansie/xgboost/pull/1)

**Comment by alexmonroe87** [comment]
How do you use multiple metrics?

I tried

```
params['eval_metric'] = 'logloss'
params['eval_metric'] = 'auc'
```

But as expected auc overwrote logloss.
