### ISSUE TITLE
Alpine runtime error with java8  library version 0.90

### ISSUE THREAD

**Issue by wanglyCs** [dmlc/xgboost#5381]
Hi, I 'm trying to use dmlc xgboost version 0.90(load model from xgboost spark 0.90) and do some prediction work in alpine docker (v3.8), when I remove the model predict part, it works well. But when I added the xgboost model part, the program crashes with error 
"Inconsistency detected by ld.so: dl-lookup.c: 111: check_match: Assertion `version-&gt;filename == NULL || ! _dl_name_match_p (version-&gt;filename, map)' failed!"

Details about my environment:

Alpine v3.8
Java version 1.8.0_131-b11 
ldd --version
     musl libc (x86_64)
     Version 1.1.19
gcc --version
      gcc (Alpine 6.4.0) 6.4.0
 g++ --version
       g++ (Alpine 6.4.0) 6.4.0
offline model library
    implementation 'ml.dmlc:xgboost4j-spark:0.90'

Any help or suggestions? Having been stuck for about 4days....

Thanks

**Comment by hcho3** [comment]
XGBoost4J from the Maven Central repository contains a shared library (`libxgboost4j.so`) that depends on GLIBC. Since Alpine does not have GLIBC, you will want to build the JAR artifact from the source.
