### ISSUE TITLE
Allow python/R bindings to use an external libxgboost

### ISSUE THREAD

**Issue by dpryan79** [dmlc/xgboost#5386]
Would it be possible to change the R/python bindings so they can use precompiled xgboost libraries? In conda, as an example, we distribute the standard libraries separate from the python and R bindings, since users rarely need all of them. An example patch for the python bindings can be found here, though it should be modified to make it more generic: https://github.com/conda-forge/xgboost-feedstock/blob/master/recipe/0001-conda-Unbundle-libxgboost.-dll-dylib-so.patch

Xref: https://github.com/conda-forge/xgboost-feedstock/pull/47

**Comment by trivialfis** [comment]
It would be very useful for distribution purpose.  I rewrote the Python setup.py script recently, would you like to take a look and see how can we find the library dynamically?

**Comment by trivialfis** [comment]
There are specializations in R package to make it comply to CRAN policy, for examples `stdout/stderr` is forbidden, some math functions are replaced.  Particularly CMake is no usable.

**Comment by trivialfis** [comment]
For Python package this is done in: https://github.com/dmlc/xgboost/pull/6362

**Comment by jakirkham** [comment]
Awesome! Thank you Jiaming 😄

**Comment by dpryan79** [comment]
Thanks!

**Comment by jakirkham** [comment]
Handling the last bit of the associated conda-forge patch in PR: https://github.com/dmlc/xgboost/pull/10643
