### ISSUE TITLE
R package's dependency on DiagrammeR/V8

### ISSUE THREAD

**Issue by hetong007** [dmlc/xgboost#539]
I just recieved an email from Prof Brian Ripley:

> Regrettably DiagrammeR 0.8 added Imports: V8 and hence it and packages depending on it cannot be installed without V8.  Now V8 is a wrapper for v8 which is far from portable (and a pain to install): it is only available for three CPU types, not including Sparc on the CRAN check farm (all the other CRAN machines are x86_64).

> The packages which this most impacts are qgraph and sem.

> Packages

> CDM MVA TAM markovchain xgboost

> suggest a package which depends on DiagrammeR and do not use it conditionally so now fail their checks (see their CRAN check pages later today).  Please correct this ASAP.

> It seem unlikely that any of the dependant packages are using features of DiagrammeR 0.8 which actually depend on V8, as they all worked with earlier versions.  Please consider if DiagrammeR could not use just Enhances: V8 or Suggests: V8 .  (The maintainers of qgraph and sem could consider a weaker dependence on DiagrammeR.)

@pommedeterresautee It seems we might need to explicitly add "suggest [V8](https://cran.r-project.org/web/packages/V8/index.html)". Do you have any suggestion on this modification?

**Comment by pommedeterresautee** [comment]
I will check with DiagrammeR dev if they can make V8 a sugest and let you know.

**Comment by hetong007** [comment]
@pommedeterresautee Thanks! Richard himself (diagrammer author) has also got the email. I believe we could wait for a moment :)

**Comment by quansie** [comment]
Commits checked with the Travis CI build are also failing, because of an error with the package dependencies:

ERROR: dependency ‘V8’ is not available for package ‘DiagrammeR’
* removing ‘/usr/local/lib/R/site-library/DiagrammeR’

**Comment by hetong007** [comment]
`DiagrammeR` on CRAN is fixed now.
