### ISSUE TITLE
Dask DMatrix does not infer feature names from Dask dataframes

### ISSUE THREAD

**Issue by jborchma** [dmlc/xgboost#5394]
So I am very excited about the dask integration with XGBoost and have started playing around with it. However, I have noticed that when using a dask dataframe (with the sklearn API, if that matters) does not pass through the column names from the dataframe. For pandas dataframes it seems to be done in [this](https://github.com/dmlc/xgboost/blob/8d06878bf9b778db68ae98f68d99a3557c7ea885/python-package/xgboost/core.py#L246-L287) private method that is called during the normal DMatrix [instantiation](https://github.com/dmlc/xgboost/blob/8d06878bf9b778db68ae98f68d99a3557c7ea885/python-package/xgboost/core.py#L446-L460). However, something like this is currently missing from the DaskDMatrix [init](https://github.com/dmlc/xgboost/blob/master/python-package/xgboost/dask.py#L145-L177).

This has the effect that all the features are named to `f1`, .., `fn` in the booster object for n features when using the dask functionality. 

This issue is to mainly make you guys aware of this. Do you have plans to work on this at some point and/or have already a plan on how to implement this? Or would a contribution for this be welcome as well?

**Comment by trivialfis** [comment]
Contributions are definitely welcomed!

**Comment by jborchma** [comment]
I was still owing a minimal example, but here is goes:

```
from sklearn import datasets
import pandas as pd
import numpy as np
import dask.dataframe as dd
import xgboost

n_features = 13
random_state=75
n_samples = 100000
n_classes = 2
n_informative = 3
X, y = datasets.make_classification(
    n_features=n_features, 
    n_redundant=3, 
    n_repeated=0, 
    n_informative=n_informative, 
    flip_y=0, 
    n_clusters_per_class=2,
    n_classes=n_classes,
    n_samples=n_samples,
    random_state=random_state
)
train_data = pd.DataFrame(X)
train_data["target"] = y
train_data.columns = train_data.columns.astype(str)
features = [column for column in train_data.columns if column != "target"]

train_dask = dd.from_pandas(train_data, chunksize=10000)

model = xgboost.XGBClassifier()
model.fit(train_dask[features], y=train_dask["target"])
print(model._Booster.feature_names)
```

**Comment by jborchma** [comment]
So, looking further into this and playing around with the code in `dask.py`, I realized I wasn't actually using the dask framework but just the normal pandas/numpy one. Interestingly enough, this ran without any logger output indicating that I wasn't using the right framework.

**Comment by jborchma** [comment]
I think I will close this issue for now since this issue was not really what I though it was.
