### ISSUE TITLE
No module found error after XGBoost installation via Homebrew

### ISSUE THREAD

**Issue by hernandezurbina** [dmlc/xgboost#5411]
Hi, I installed xgboost via Homebrew with the intention to use it inside a Python virtualenv. The installation went smoothly, but when doing "import xgboost" in Python (inside or outside a virtualenv) I receive a "No module named xgboost" error. Did I miss anything during installation? Thanks!

**Comment by hernandezurbina** [comment]
Hi, I installed xgboost via Homebrew with the intention to use it inside a Python virtualenv. The installation went smoothly, but when doing "import xgboost" in Python (inside or outside a virtualenv) I receive a "No module named xgboost" error. Did I miss anything during installation? Thanks!

**Comment by trivialfis** [comment]
@hcho3  Could you please help verifying?

**Comment by hcho3** [comment]
Current Homebrew package only installs the CLI application and not the Python binding. There's an ongoing discussion to include the Python binding as well: https://github.com/Homebrew/homebrew-core/pull/50467.

For now, you can follow steps in https://github.com/dmlc/xgboost/issues/4949#issuecomment-542333666 to install the Python package.

**Comment by hcho3** [comment]
@hernandezurbina We just release XGBoost version 1.1.0, and starting from this release, we publish a Python wheel specifically built for Mac OS: https://pypi.org/project/xgboost/1.1.0/#files. You can install it by running
```
pip install xgboost==1.1.0
```

Note: you should first install libomp by running `brew install libomp`. We currently support Mac OS High Sierra, Mojave, and Catalina.
