### ISSUE TITLE
xgboost example fails on raspberry pi3 

### ISSUE THREAD

**Issue by shomedas** [dmlc/xgboost#5419]
I have installed xgboost successfully(I am able to import xgboost) on raspberry pi3 modelB(with raspbian buster which is 32bit OS) using the commands

git clone --recursive https://github.com/dmlc/xgboost
cd xboost
make -j4
cd python-package; sudo python3 setup.py install

However when I run the code from [xgboost-tutorial](https://machinelearningmastery.com/develop-first-xgboost-model-python-scikit-learn/) it exists with error

/usr/lib/python3/dist-packages/sklearn/externals/joblib.py:1: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
terminate called after throwing an instance of 'std::length_error'
  what():  vector::_M_default_append
Aborted

The same code runs **successfully on my i5 laptop(with ubuntu 16.06, 64bit).**

**My question is how to avoid the std::length_error** for the raspberry pi

**Comment by getBolted** [comment]
Also faced this issue in a docker container running on rpi3b with the following code in a python script:
```
loaded_model = pickle.load(open("500-300.pickle.dat", "rb"))
predict = loaded_model.predict(X)
```
Tried rebuilding container with another base image and another python version, and pre-learned model loading through pickle and xgboost internal `load_model(foo.model)`. Also checked if the model built in 32-bit python, or converting data to float32 will make any sense.

By the way, this code easily runs in a docker container in my Jetson Nano, powered by ARM64 OS.

**Comment by hcho3** [comment]
Closing this, since XGBoost 2.0+ will not support 32-bit systems. See https://github.com/dmlc/xgboost/issues/9035#issuecomment-1578016136 for rationale.
