### ISSUE TITLE
What is the python xgboost.Booster buffer type for a model file?

### ISSUE THREAD

**Issue by SimplyAhmazing** [dmlc/xgboost#542]
I'm trying to instantiate the class `xgboost.Booster` one of the arguments to the constructor is `model_file` which can either be a path to a model file or it can be a memory buffer of the model file. I'm unable figure what the type of this memory buffer is? StringIO, bytearray, etc ?

The relevant source code for interpreting the model file bytecode is here: https://github.com/dmlc/xgboost/blob/master/python-package/xgboost/core.py#L870).

To be more exact, I'm getting an uploaded model file via a POST request and I'm not sure what data format I should convert this In memory file to...

**Comment by tqchen** [comment]
It is bytes

**Comment by jjinstitchfix** [comment]
@tqchen I used bytes but got "underlying buffer is not writable"..
Any suggestion?  PS I can't access the model file directly and it was an input argument.

Here is a sample code to repeat the problem:
```
with open('model_file', 'rb') as f:
    d = f.read()
Booster().load_model(d)
```

**Comment by aldanor** [comment]
@tqchen Same error here, `underlying buffer is not writable`, why does it even have to be writable in the first place? (and which Python type is really expected here)

**Comment by aldanor** [comment]
(I've posted a possible bugfix in #3013)
