### ISSUE TITLE
EmptyEngine:: Allreduce is not supported,use Allreduce_ instead

### ISSUE THREAD

**Issue by Kodiologist** [dmlc/xgboost#5422]
With the R package from the latest stable release (1.0.2) installed from source, the function `xgboost` crashes immediately. I'm running R 3.6.1 on Lubuntu 19.10.

```
$ R --vanilla
> library(xgboost)
> xgboost(nround = 10, data = as.matrix(mtcars), label = with(mtcars, carb * wt + rnorm(length(carb))))
Error in xgb.iter.update(bst$handle, dtrain, iteration - 1, obj) : 
  EmptyEngine:: Allreduce is not supported,use Allreduce_ instead
```

**Comment by trivialfis** [comment]
@hcho3

**Comment by trivialfis** [comment]
@Kodiologist How did you install XGBoost?

**Comment by Kodiologist** [comment]
Bizarrely, I was seeing this on three separate machines, and now I can't reproduce it on any of them. My best guess is that it had something to do with build artifacts left over from installing previous versions of XGBoost, or forgetting to `git submodule update`. Sorry for the noise.

**Comment by trivialfis** [comment]
No problem.  Good to know that it works fine.
