### ISSUE TITLE
Issue about rabbit ConnectTracker

### ISSUE THREAD

**Issue by daiyl0320** [dmlc/xgboost#544]
hi tianqi,
    I use xgboost in a distributed environment, and after I finish the model training, the program core dump when ConnectTracker, I see the code than if tracker.Connect return false, the code will call utils::Socket::Error("Connect"); then the program will be exit(-1), but the program core when program exit,   Is there some bug in global variable dtor?

**Comment by daiyl0320** [comment]
The network is well, which condition can cause the connect  fail?

yonglong
thanks

**Comment by daiyl0320** [comment]
hi，天奇
我们在分布式环境下做了相关测试，将此问题fix了。具体问题如下：
    master用来listen的socket的backlog设置太小（只有16）＋大量job结束的比较集中去connect master会有问题，超过backlog值后，server端会忽略syn的分节导致worker端timeout退出；
通过以下两个方面解决此问题：
1、将rabit socket中listen的backlog默认参数修改为128；
2、为ConnectTracker函数增加connect的retry，若连续5次retry失败则再报错；
测试验证：
在分布式环境中启动149个instance进行xgboost的训练（之前用此数据训练后connect master会core dump），连续测试20次都成功，并确认了部分instances的retry生效。

**Comment by daiyl0320** [comment]
hi，天奇
我们在分布式环境下做了相关测试，将此问题fix了。具体问题如下：
    master用来listen的socket的backlog设置太小（只有16）＋大量job结束的比较集中去connect master会有问题，超过backlog值后，server端会忽略syn的分节导致worker端timeout退出；
通过以下两个方面解决此问题：
1、将rabit socket中listen的backlog默认参数修改为128；
2、为ConnectTracker函数增加connect的retry，若连续5次retry失败则再报错；
测试验证：
在分布式环境中启动149个instance进行xgboost的训练（之前用此数据训练后connect master会core dump），连续测试20次都成功，并确认了部分instances的retry生效。

**Comment by daiyl0320** [comment]
hi，天奇
我们在分布式环境下做了相关测试，将此问题fix了。具体问题如下：
    master用来listen的socket的backlog设置太小（只有16）＋大量job结束的比较集中去connect master会有问题，超过backlog值后，server端会忽略syn的分节导致worker端timeout退出；
通过以下两个方面解决此问题：
1、将rabit socket中listen的backlog默认参数修改为128；
2、为ConnectTracker函数增加connect的retry，若连续5次retry失败则再报错；
测试验证：
在分布式环境中启动149个instance进行xgboost的训练（之前用此数据训练后connect master会core dump），连续测试20次都成功，并确认了部分instances的retry生效。

**Comment by tqchen** [comment]
This is great! Can you create a PR on this to rabit?
