### ISSUE TITLE
Contribute neptune callback

### ISSUE THREAD

**Issue by kamil-kaczmarek** [dmlc/xgboost#5440]
Hi,

I would like to contribute callback that will log `evals_result` (maybe along with other artifacts important for the user) to [Neptune](https://github.com/neptune-ai/neptune-client).

Thanks to this, XGBoost user will be able to start tracking their experiments (i.e. HPO runs), for further analysis and comparison with minimal effort.

Please let me know what do you think? I'm happy to discuss it in more detail and contribute PR :slightly_smiling_face:

Best,
Kamil

**Comment by hcho3** [comment]
XGBoost already has a built-in callback facility. See example https://github.com/dmlc/xgboost/blob/master/demo/aft_survival/aft_survival_viz_demo.py. The env argument has several attributes, the full list available at https://github.com/dmlc/xgboost/blob/cfae247231e4977a78b255810565369c934fe1b5/python-package/xgboost/training.py#L93.

**Comment by hcho3** [comment]
Also, is neptune similar to optuna?

**Comment by kamil-kaczmarek** [comment]
Hi @hcho3,

Thanks for the fast reply.

**Callback**
Yes, I would like to use exactly the attributes that you pointed to. In principle Neptune users can develop such callback in their sources, however, my idea is to facilitate this by making PR with specific callback (in the [callback.py](https://github.com/dmlc/xgboost/blob/master/python-package/xgboost/callback.py) file) that can be imported directly from XGBoost and used right away.

Please let me know what do you think about it?


**Neptune - Optuna**
[Neptune](https://docs.neptune.ai) is quite different from [optuna](https://optuna.readthedocs.io/en/stable/index.html). Optuna is a HPO framework, that lets you automate hyperparameter search.

Neptune in turn, is an experiment management and collaboration tool for ML/RL/DL researchers/specialists. Purpose is to help you keep track of your machine learning experiments, compare them, analyse and share.

**Comment by hcho3** [comment]
@kamil-kaczmarek My suggestion is to include the proposed callback in the Neptune codebase. Here are other two projects that implement their own custom callback to interact with XGBoost:
* Optuna implements `optuna.integration.XGBoostPruningCallback`: https://github.com/optuna/optuna/blob/master/optuna/integration/xgboost.py
* SageMaker Debugger implements `smdebug.xgboost.Hook`: https://github.com/awslabs/sagemaker-debugger/blob/master/smdebug/xgboost/hook.py

**Comment by kamil-kaczmarek** [comment]
Thanks @hcho3 I'll do it in the way you suggest.

Is there a place in XGBoost docs or examples that show such external integrations?

Thanks,
Kamil

**Comment by hcho3** [comment]
@kamil-kaczmarek Not yet. Admittedly, callback feature hasn't been quite well documented. For now, you should look at the two examples I posted earlier, as well as [aft_survival_viz_demo.py](https://github.com/dmlc/xgboost/blob/master/demo/aft_survival/aft_survival_viz_demo.py).

**Comment by kamil-kaczmarek** [comment]
Thanks @hcho3,

I think that I know how to implement it :slightly_smiling_face:

I asked more about a potential place where I can show my use case. I found [awesome-xgboost](https://github.com/dmlc/xgboost/tree/master/demo#awesome-xgboost), where I can add one sentence about my integration. What do you think?

**Comment by hcho3** [comment]
Yes, the demo directory is where you can put your example.

**Comment by kamil-kaczmarek** [comment]
Thanks @hcho3, I'll do it.

**Comment by kamil-kaczmarek** [comment]
Thanks for your help @hcho3, I made PR: #5528

**Comment by hcho3** [comment]
I've merged #5528
