### ISSUE TITLE
 'malloc(): memory corruption'  xgboost4j predictor

### ISSUE THREAD

**Issue by yan-rui** [dmlc/xgboost#5446]
Hi, Im using xgboost4j to build a http service project with spring boot. It get an error like below. 
Here is my env:
`java version "1.8.0_65"

'org.springframework.boot' version '2.2.2.RELEASE'

'io.spring.dependency-management' version '1.0.8.RELEASE'

xbgoost4j 0.82
`
I have 2 model to load in memory 

Here is the error:
*** Error in 'java': malloc(): memory corruption: 0x00007fb91dc09200 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7ef2c)[0x7fba5b715f2c]
/lib64/libc.so.6(__libc_malloc+0x5c)[0x7fba5b7174ec]
/lib64/libstdc++.so.6(_Znwm+0x1d)[0x7fba32bb10cd]
/tmp/libxgboost4j6043009139095700539.so(_ZN7xgboost7DMatrix6CreateEOSt10unique_ptrINS_10DataSourceESt14default_deleteIS2_EERKSs+0xaa)[0x7fba32ef511a]
/tmp/libxgboost4j6043009139095700539.so(XGDMatrixCreateFromMat+0x4f6)[0x7fba32ed10f6]
/tmp/libxgboost4j6043009139095700539.so(Java_ml_dmlc_xgboost4j_java_XGBoostJNI_XGDMatrixCreateFromMat+0x4d)[0x7fba32ec26cd]
[0x7fba450153f4]
======= Memory map: ========
00400000-00401000 r-xp 00000000 ca:02 926105                             /usr/java/jdk1.8.0_65/jre/bin/java
00600000-00601000 rw-p 00000000 ca:02 926105                             /usr/java/jdk1.8.0_65/jre/bin/java
01bb1000-01bd2000 rw-p 00000000 00:00 0                                  [heap]
440000000-4b1280000 rw-p 00000000 00:00 0 
4b1280000-695580000 ---p 00000000 00:00 0 
695580000-7c0000000 rw-p 00000000 00:00 0 
7c0000000-7c050c000 rw-p 00000000 00:00 0 
7c050c000-800000000 ---p 00000000 00:00 0 
7fb8ec000000-7fb8eed13000 rw-p 00000000 00:00 0 
7fb8eed13000-7fb8f0000000 ---p 00000000 00:00 0 
7fb8f4000000-7fb8fc000000 rw-p 00000000 00:00 0 
7fb8fc000000-7fb904000000 rw-p 00000000 00:00 0 
7fb904000000-7fb90bfff000 rw-p 00000000 00:00 0 
7fb90bfff000-7fb90c000000 ---p 00000000 00:00 0 
7fb90c000000-7fb914000000 rw-p 00000000 00:00 0 
7fb914000000-7fb91c000000 rw-p 00000000 00:00 0 
7fb91c000000-7fb924000000 rw-p 00000000 00:00 0 
7fb924000000-7fb927fff000 rw-p 00000000 00:00 0 
7fb927fff000-7fb928000000 ---p 00000000 00:00 0 
7fb928000000-7fb92c000000 rw-p 00000000 00:00 0 
7fb92c000000-7fb934000000 rw-p 00000000 00:00 0 
7fb934000000-7fb93c000000 rw-p 00000000 00:00 0 
7fb93c000000-7fb944000000 rw-p 00000000 00:00 0 
7fb944000000-7fb94c000000 rw-p 00000000 00:00 0 
7fb94c000000-7fb954000000 rw-p 00000000 00:00 0 
7fb954000000-7fb95bfff000 rw-p 00000000 00:00 0 
7fb95bfff000-7fb95c000000 ---p 00000000 00:00 0 
7fb95c000000-7fb964000000 rw-p 00000000 00:00 0 
7fb964000000-7fb96c000000 rw-p 00000000 00:00 0 
7fb96c000000-7fb974000000 rw-p 00000000 00:00 0 
7fb974000000-7fb97bfff000 rw-p 00000000 00:00 0 
7fb97bfff000-7fb97c000000 ---p 00000000 00:00 0 
7fb97c000000-7fb984000000 rw-p 00000000 00:00 0 
7fb984000000-7fb98c000000 rw-p 00000000 00:00 0 
7fb98c000000-7fb994000000 rw-p 00000000 00:00 0 
7fb994000000-7fb99c000000 rw-p 00000000 00:00 0 
7fb99c000000-7fb9a0000000 rw-p 00000000 00:00 0 
7fb9ac000000-7fb9ac021000 rw-p 00000000 00:00 0 
7fb9ac021000-7fb9b0000000 ---p 00000000 00:00 0 
7fb9b0000000-7fb9b0021000 rw-p 00000000 00:00 0 
7fb9b0021000-7fb9b4000000 ---p 00000000 00:00 0 
7fb9b4000000-7fb9b4021000 rw-p 00000000 00:00 0 
7fb9b4021000-7fb9b8000000 ---p 00000000 00:00 0 
7fb9b8000000-7fb9b895b000 rw-p 00000000 00:00 0 
7fb9b895b000-7fb9bc000000 ---p 00000000 00:00 0 
7fb9bc000000-7fb9bc021000 rw-p 00000000 00:00 0 
7fb9bc021000-7fb9c0000000 ---p 00000000 00:00 0 
7fb9c0000000-7fb9c0021000 rw-p 00000000 00:00 0 
7fb9c0021000-7fb9c4000000 ---p 00000000 00:00 0 
7fb9c4000000-7fb9c4966000 rw-p 00000000 00:00 0 
7fb9c4966000-7fb9c8000000 ---p 00000000 00:00 0 
7fb9c8000000-7fb9c8021000 rw-p 00000000 00:00 0 
7fb9c8021000-7fb9cc000000 ---p 00000000 00:00 0 
7fb9cc000000-7fb9cd222000 rw-p 00000000 00:00 0 
7fb9cd222000-7fb9d0000000 ---p 00000000 00:00 0 
7fb9d0000000-7fb9d1364000 rw-p 00000000 00:00 0 
7fb9d1364000-7fb9d4000000 ---p 00000000 00:00 0 
7fb9d4000000-7fb9d52bc000 rw-p 00000000 00:00 0 
7fb9d52bc000-7fb9d8000000 ---p 00000000 00:00 0 
7fb9d9ad9000-7fb9e0000000 r--p 00000000 ca:02 788694                     /usr/lib/locale/locale-archive
7fb9e0000000-7fb9e0021000 rw-p 00000000 00:00 0 
7fb9e0021000-7fb9e4000000 ---p 00000000 00:00 0 
7fb9e4000000-7fb9e4021000 rw-p 00000000 00:00 0 
7fb9e4021000-7fb9e8000000 ---p 00000000 00:00 0 
7fb9e8000000-7fb9e8074000 rw-p 00000000 00:00 0 
7fb9e8074000-7fb9ec000000 ---p 00000000 00:00 0 
7fb9ec000000-7fb9ec021000 rw-p 00000000 00:00 0 
7fb9ec021000-7fb9f0000000 ---p 00000000 00:00 0 
7fb9f0000000-7fba0c000000 rw-p 00000000 00:00 0 
7fba0c000000-7fba0c021000 rw-p 00000000 00:00 0 
7fba0c021000-7fba10000000 ---p 00000000 00:00 0 
7fba10000000-7fba10032000 rw-p 00000000 00:00 0 
7fba10032000-7fba14000000 ---p 00000000 00:00 0 
7fba14000000-7fba14052000 rw-p 00000000 00:00 0 
7fba14052000-7fba18000000 ---p 00000000 00:00 0 
7fba1c000000-7fba1c079000 rw-p 00000000 00:00 0 
7fba1c079000-7fba20000000 ---p 00000000 00:00 0 
7fba24000000-7fba240b0000 rw-p 00000000 00:00 0 
7fba240b0000-7fba28000000 ---p 00000000 00:00 0 
7fba2c000000-7fba2c0b0000 rw-p 00000000 00:00 0 
7fba2c0b0000-7fba30000000 ---p 00000000 00:00 0 
7fba3272d000-7fba32742000 r-xp 00000000 ca:02 786448                     /usr/lib64/libgcc_s-4.8.2-20140120.so.1
7fba32742000-7fba32941000 ---p 00015000 ca:02 786448                     /usr/lib64/libgcc_s-4.8.2-20140120.so.1
7fba32941000-7fba32942000 r--p 00014000 ca:02 786448                     /usr/lib64/libgcc_s-4.8.2-20140120.so.1
7fba32942000-7fba32943000 rw-p 00015000 ca:02 786448                     /usr/lib64/libgcc_s-4.8.2-20140120.so.1
7fba32943000-7fba32951000 r-xp 00000000 ca:02 789565                     /usr/lib64/libgomp.so.1.0.0
7fba32951000-7fba32b50000 ---p 0000e000 ca:02 789565                     /usr/lib64/libgomp.so.1.0.0
7fba32b50000-7fba32b51000 r--p 0000d000 ca:02 789565                     /usr/lib64/libgomp.so.1.0.0
7fba32b51000-7fba32b52000 rw-p 0000e000 ca:02 789565                     /usr/lib64/libgomp.so.1.0.0
7fba32b52000-7fba32c3b000 r-xp 00000000 ca:02 788695                     /usr/lib64/libstdc++.so.6.0.19
7fba32c3b000-7fba32e3a000 ---p 000e9000 ca:02 788695                     /usr/lib64/libstdc++.so.6.0.19
7fba32e3a000-7fba32e42000 r--p 000e8000 ca:02 788695                     /usr/lib64/libstdc++.so.6.0.19
7fba32e42000-7fba32e44000 rw-p 000f0000 ca:02 788695                     /usr/lib64/libstdc++.so.6.0.19
7fba32e44000-7fba32e59000 rw-p 00000000 00:00 0 
7fba32e59000-7fba330ba000 r-xp 00000000 ca:02 524394                     /tmp/libxgboost4j6043009139095700539.so
7fba330ba000-7fba332b9000 ---p 00261000 ca:02 524394                     /tmp/libxgboost4j6043009139095700539.so
7fba332b9000-7fba332c0000 r--p 00260000 ca:02 524394                     /tmp/libxgboost4j6043009139095700539.so
7fba332c0000-7fba332c3000 rw-p 00267000 ca:02 524394                     /tmp/libxgboost4j6043009139095700539.so
7fba332c3000-7fba33484000 rw-p 00000000 00:00 0 
7fba33484000-7fba334c4000 ---p 00000000 00:00 0 
7fba334c4000-7fba336c4000 rw-p 00000000 00:00 0 
7fba336c4000-7fba338c4000 rw-p 00000000 00:00 0 
7fba339d7000-7fba33bd7000 rw-p 00000000 00:00 0 
7fba33bd7000-7fba33dd7000 rw-p 00000000 00:00 0 
7fba33e00000-7fba34000000 rw-p 00000000 00:00 0 
7fba34000000-7fba340f1000 rw-p 00000000 00:00 0 
7fba340f1000-7fba38000000 ---p 00000000 00:00 0 
7fba380f6000-7fba382f6000 rw-p 00000000 00:00 0 
7fba382f6000-7fba384f6000 rw-p 00000000 00:00 0 
7fba384f6000-7fba386f6000 rw-p 00000000 00:00 0 
7fba386f6000-7fba386f9000 ---p 00000000 00:00 0

**Comment by yan-rui** [comment]
Any ideas to solve it ?

**Comment by trivialfis** [comment]
What's your current version of XGBoost?  Also do you have a reproducible example?

**Comment by yan-rui** [comment]
> What's your current version of XGBoost? Also do you have a reproducible example?

Solved. I had a wrong Centos System.
