### ISSUE TITLE
Subsetting rows of xgboost.DMatrix object

### ISSUE THREAD

**Issue by fgnu** [dmlc/xgboost#545]
I am following along to the example [here](https://github.com/dmlc/xgboost/blob/master/demo/guide-python/basic_walkthrough.py). It appears that the `agaricus.txt.train` file that you can get from [here](https://github.com/dmlc/xgboost/tree/master/demo/data) contains some errant labels: 

    In[10]: set(dtrain.get_label())
    Out[10]: {0.0, 1.0, 3.0, 240.0, 722.0, 878.0, 2014.0, 2015.0, 6514.0}

which will cause `xgboost.train` to fail with: 

     xgboost.core.XGBoostError: b'label must be in [0,1] for logistic regression'

 What is the simplest way to subset the `xgboostDMatrix` object. Should I use `xgboost.slice` for this purpose?

**Comment by tqchen** [comment]
Hmm, I guess this could due to the platform and string encoding problem ```\r\n``` vs ```\r``` so the parser did not parse correctly

**Comment by CSJLOVEJX** [comment]
@fgnu  hello， i face the same problem..... could please you tell me how you solved your problem...
My issue is just like this:
        ......
	xgtrain = xgb.DMatrix(train[offset:, :], label=labels[offset:])
......
       	model = xgb.train(plst, xgtrain, num_boost_round = num_rounds, evals = watchlist, early_stopping_rounds=120)

And I am sure that my label contains only 0 and 1, instead:
xgboost.core.XGBoostError: b'label must be in [0,1] for logistic regression'

**Comment by fgnu** [comment]
@CSJLOVEJX IIRC, this was an issue with the `xgboost` installation and not the file itself. I re-installed `xgboost` and the example worked fine for me. Sorry, it has been a while, so I can't be more specific.

**Comment by xxllp** [comment]
I have the same question..
