### ISSUE TITLE
C interface does not allow for rapid prediction due to suspected O(n^2) `ClearExpiredEntries`

### ISSUE THREAD

**Issue by msoos** [dmlc/xgboost#5450]
I am using the python module to create a model that I then load in C++ to make predictions. This actually works, except that the prediction is excruciatingly slow, because of what I think is a cleanup function in C++ that is called after every `XGBoosterPredict` and seems to be O(n^2). Let me elaborate.

I call

```
XGBoosterPredict(
        handles[num],
        dmat,
        0,  //0: normal prediction
        0,  //use all trees
        0,  //do not use for training
        &out_len,
        &out_result
    );
```

Where `dmat` contains a *single row*, about 10-20 thousand times, very rapidly. I cannot do this prediction in one go. Now, running the final executable[Note1], doing `perf record`/`perf report` I am seeing:

```
  85.13%  cryptominisat5  libxgboost.so                       [.] xgboost::PredictionContainer::ClearExpiredEntries
   7.62%  cryptominisat5  libcryptominisat5.so.5.6            [.] CMSat::PropEngine::propagate_any_order_fast<false>
   1.33%  cryptominisat5  libcryptominisat5.so.5.6            [.] CMSat::PropEngine::enqueue<false>
   1.18%  cryptominisat5  libcryptominisat5.so.5.6            [.] CMSat::Searcher::pick_var_vsids_maple
   0.98%  cryptominisat5  libxgboost.so                       [.] xgboost::predictor::CPUPredictor::PredInternal
[...]
```

So the vast majority of the time is spent on clearing expired entries. This is most likely due to how inefficient `erase` for this particular use-case (it could be `O(n^2)` or me calling it `m` times, even `O(m*n^2)`, in this case). If I add the below patch to XGBoost, the 10-20k predictions go down from **taking 12 seconds to about 0.02s** (I am not exaggerating unfortunately):

```
diff --git a/src/predictor/predictor.cc b/src/predictor/predictor.cc
index b20edf88..caa08f05 100644
--- a/src/predictor/predictor.cc
+++ b/src/predictor/predictor.cc
@@ -20,17 +20,17 @@ void PredictionContainer::ClearExpiredEntries() {
     }
   }
   for (auto const& ptr : expired) {
     container_.erase(ptr);
   }
 }
 
 PredictionCacheEntry &PredictionContainer::Cache(std::shared_ptr<DMatrix> m, int32_t device) {
-  this->ClearExpiredEntries();
+  //this->ClearExpiredEntries();
   container_[m.get()].ref = m;
   if (device != GenericParameter::kCpuId) {
     container_[m.get()].predictions.SetDevice(device);
   }
   return container_[m.get()];
 }
 
 PredictionCacheEntry &PredictionContainer::Entry(DMatrix *m) {
```

The predictions do not suffer in quality, seemingly. So my question is... can I just hack the system to call the expiration only once in while? Can you do it for me? Do I have to run this expiration at all? What happens if I don't? I only loose memory? Do I get mispredictions? I don't understand everything here, but the system seems to be designed for doing perhaps millions of predictions in one go, so my use-case is a bit weird, but could be supported, I think?

Note1:  You must set `XGBoosterSetParam(handles[0], "nthread", "1");` right after creation of `BoosterHandle`.  This is super-important or you'll see the OMP waiting for threads in the `perf report` output, and you won't see what's actually causing the speed issue.

**Comment by msoos** [comment]
Some more info, if needed. I have 22 features and I train the model on about 800 data pieces in python. The training is pretty simple:

```
clf = xgb.XGBRegressor(objective ='binary:logistic')
clf.fit(X_train, y_train)
booster = clf.get_booster()
booster.save_model(fname)
```

**Comment by trivialfis** [comment]
@RAMitchell

**Comment by trivialfis** [comment]
For serving tree inference there are tree inference libraries from rapidsai and treelite, also onnx.  If you want to use XGBoost for this purpose, feel free to take a look into https://github.com/dmlc/xgboost/pulls. @RAMitchell and I haven't decided whether should be merge it due to additional maintenance burden.

**Comment by msoos** [comment]
Thanks! That PR Looks good actually, I'd vote for it to be merged :) Also, my setup shows a significantly larger performance hit, approx 100x, not the 1.4x/5.x that is seen there. So there seem to be cases when what's there as a slowdown is not realistic.

As for why I want to use xgboost. Basically, I need to have many different predictors. I'd rather not have 3 different libraries doing the prediction -- xgboost looks pretty darn good to cover everything :)

In the meanwhile, can you please let me know if it's an OK hack for me to just run the `ClearExpiredEntries` only once in a while? It would work for me as a hack... Thanks!

**Comment by trivialfis** [comment]
Yes.  You can hack it, it's only for memory usage concern.  Another way is to use std map instead of hash.  Maybe it's only latency here as if your DMatrix is expired right after prediction, the map will remain at most 1 entry.

**Comment by msoos** [comment]
Oh, okay, thanks a lot! I will then hack it and just delete the `dmat` right after :) Thanks again! I am now closing, as this fixes it for me :)

Mate

**Comment by NorthSummer** [comment]
> I am using the python module to create a model that I then load in C++ to make predictions. This actually works, except that the prediction is excruciatingly slow, because of what I think is a cleanup function in C++ that is called after every `XGBoosterPredict` and seems to be O(n^2). Let me elaborate.
> 
> I call
> 
> ```
> XGBoosterPredict(
>         handles[num],
>         dmat,
>         0,  //0: normal prediction
>         0,  //use all trees
>         0,  //do not use for training
>         &out_len,
>         &out_result
>     );
> ```
> 
> Where `dmat` contains a _single row_, about 10-20 thousand times, very rapidly. I cannot do this prediction in one go. Now, running the final executable[Note1], doing `perf record`/`perf report` I am seeing:
> 
> ```
>   85.13%  cryptominisat5  libxgboost.so                       [.] xgboost::PredictionContainer::ClearExpiredEntries
>    7.62%  cryptominisat5  libcryptominisat5.so.5.6            [.] CMSat::PropEngine::propagate_any_order_fast<false>
>    1.33%  cryptominisat5  libcryptominisat5.so.5.6            [.] CMSat::PropEngine::enqueue<false>
>    1.18%  cryptominisat5  libcryptominisat5.so.5.6            [.] CMSat::Searcher::pick_var_vsids_maple
>    0.98%  cryptominisat5  libxgboost.so                       [.] xgboost::predictor::CPUPredictor::PredInternal
> [...]
> ```
> 
> So the vast majority of the time is spent on clearing expired entries. This is most likely due to how inefficient `erase` for this particular use-case (it could be `O(n^2)` or me calling it `m` times, even `O(m*n^2)`, in this case). If I add the below patch to XGBoost, the 10-20k predictions go down from **taking 12 seconds to about 0.02s** (I am not exaggerating unfortunately):
> 
> ```
> diff --git a/src/predictor/predictor.cc b/src/predictor/predictor.cc
> index b20edf88..caa08f05 100644
> --- a/src/predictor/predictor.cc
> +++ b/src/predictor/predictor.cc
> @@ -20,17 +20,17 @@ void PredictionContainer::ClearExpiredEntries() {
>      }
>    }
>    for (auto const& ptr : expired) {
>      container_.erase(ptr);
>    }
>  }
>  
>  PredictionCacheEntry &PredictionContainer::Cache(std::shared_ptr<DMatrix> m, int32_t device) {
> -  this->ClearExpiredEntries();
> +  //this->ClearExpiredEntries();
>    container_[m.get()].ref = m;
>    if (device != GenericParameter::kCpuId) {
>      container_[m.get()].predictions.SetDevice(device);
>    }
>    return container_[m.get()];
>  }
>  
>  PredictionCacheEntry &PredictionContainer::Entry(DMatrix *m) {
> ```
> 
> The predictions do not suffer in quality, seemingly. So my question is... can I just hack the system to call the expiration only once in while? Can you do it for me? Do I have to run this expiration at all? What happens if I don't? I only loose memory? Do I get mispredictions? I don't understand everything here, but the system seems to be designed for doing perhaps millions of predictions in one go, so my use-case is a bit weird, but could be supported, I think?
> 
> Note1: You must set `XGBoosterSetParam(handles[0], "nthread", "1");` right after creation of `BoosterHandle`. This is super-important or you'll see the OMP waiting for threads in the `perf report` output, and you won't see what's actually causing the speed issue.

Hi, don't know if you are still there, but could you please tell me how to get perf log of the inference process of XGBoost?

**Comment by msoos** [comment]
Hi,

First, I seem to have been slightly off with this issue -- it turns out that I forgot to free some XGBoost stuff and that's the reason why it was slow. In the end, there was  a PR that was merged that fixed this even in the case of late/no freeing.

Related to `perf` please see:

https://perf.wiki.kernel.org/index.php/Tutorial

Basically, I did `perf record --call-graph dwarf [executable]` then I did `perf report --call-graph dwarf`. Perf is amazing and invaluable for this sort of thing. There are many blogs out there, it's worth spending 1-2h reading about it.
