### ISSUE TITLE
memory leak on multi thread by python

### ISSUE THREAD

**Issue by dacson** [dmlc/xgboost#5452]
use "predict" fucntion in multi thread by python interface for long time, you will see the memory increase slowly,

- reproduec environment
  -  OS
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
  - python
Python 3.7.4 (default, Dec 17 2019, 16:30:25) 
[GCC 5.4.0 20160609] on linux
  - xgboost version
 1.0.2
 - full reproduce script 
[test_xgboost.txt](https://github.com/dmlc/xgboost/files/4401315/test_xgboost.txt)

**Comment by trivialfis** [comment]
Ran the script with address sanitizer, all memory leaks point to Python instead of XGBoost so my guess is there's something involved in threading.  Running valgrind massif, might take some time.

**Comment by trivialfis** [comment]
After a simple glance, I think you just have to force Python to do garbage collection:

``` python
import numpy as np
import threading
import os
import psutil
from xgboost import DMatrix, Booster, train
import gc

p = psutil.Process(os.getpid())
# lock = Lock()

param = {'objective': 'multi:softprob',
         'eta': '0.2',
         'max_depth': 11,
         'num_class': 16,
         'eval_metric': 'merror'}

rng = np.random.RandomState(1994)
# X = rng.randn(10000, 10)
# y = rng.randint(low=0, high=10, size=10000)

# m = DMatrix(X, y)

# bst = train(param, num_boost_round=10, dtrain=m)
# bst.save_model('xxxxxx.model')


def process(i, X, bst):
    print(i, 'Create DMatrix')
    before_dmatrix = p.memory_info().rss
    input_data = DMatrix(X)
    after_dmatrix = p.memory_info().rss
    cp = bst.copy()
    print(i, 'Predict')
    before_predict = p.memory_info().rss
    predt = cp.predict(input_data)
    after_predict = p.memory_info().rss
    gc.collect()
    after_gc = p.memory_info().rss
    del predt
    print('Before DMatrix:', before_dmatrix, 'After DMatrix:', after_dmatrix,
          'Before Predict:', before_predict, 'After Predict: ', after_predict,
          'After GC::', after_gc)


def main():
    bst = Booster(param)
    bst.load_model("xxxxxx.model")
    input_feature = rng.randn(10000, 10)
    index = 0
    print('Start')
    while index < 128:
        t1 = threading.Thread(target=process, args=(index, input_feature, bst))
        print('Beg:', p.memory_info().rss)
        t1.start()
        index += 1
        t1.join()
        gc.collect()
        print('End:', p.memory_info().rss)


if __name__ == "__main__":
    main()
```

From profiling, most of the memory are not from XGBoost but from Python:
![Screenshot from 2020-03-30 18-51-35](https://user-images.githubusercontent.com/16746409/77904708-96a1f700-72b7-11ea-9ede-ce7644023a16.png)

**Comment by trivialfis** [comment]
Feel free to reopen if the issue can be confirmed to be XGBoost related.
