### ISSUE TITLE
Segfault in XGBoosterPredict

### ISSUE THREAD

**Issue by Maradonna90** [dmlc/xgboost#5454]
I get a segfault when using a vanilla XGBRegressor on my dataset. I ran a tutorial example from https://machinelearningmastery.com/develop-first-xgboost-model-python-scikit-learn/
The code is in section 6 and the dataset is linked in the intro.

I used gdb to get a trace and it leads to XGBoosterPredict():
0x00007fffb56c4d9d in XGBoosterPredict () from /usr/xgboost/libxgboost.so

Python 3.8.2
Name: xgboost - Version: 1.0.2

**Comment by trivialfis** [comment]
Em .. I can't reproduce.

**Comment by trivialfis** [comment]
How did you install XGBoost?  If you are using the makefiles like that tutorial, could you try `pip install xgboost` instead?

**Comment by Maradonna90** [comment]
I installed it with pip in the first place.
It actually works for me with 1.1.0 Snapshot. I will reinstall 1.0.2 to verify.

**Comment by trivialfis** [comment]
Just a note here, the auc will be a little lower than the one in tutorial as we changed the default parameter.  Changing `max_depth` to 3 and `learning_rate` to 0.1 should reproduce the same auc.

**Comment by Maradonna90** [comment]
Reinstalled pip version and getting segfaults again.

**Comment by trivialfis** [comment]
@Maradonna90 Could you go into your `python3.8/site-packages/` and see how many xgboost are there?  We had a breaking API for `predict` in C.  Right now the only reason I can think of is your python code is calling a old shared library.

**Comment by Maradonna90** [comment]
well there seems to be something funny going on at my end, because I tested it with a docker container and its working there.

**Comment by trivialfis** [comment]
@Maradonna90  If you figured out what's happening please share, this will help others who encountered similar problem.  Issues are indexed by google.

**Comment by Maradonna90** [comment]
I can't really get a hold of it. I think it comes down to my messy global `python3.8/site-packages` so i just made a `venv` as you should actually do.
