### ISSUE TITLE
Eta decay like NNs

### ISSUE THREAD

**Issue by davutpolat** [dmlc/xgboost#546]
Hi all,

is eta decay in every iteration possible  for GBMs ? i mean we set eta = 1.0, and got a parameter such "eta_decay" = 0.9995 , in every iteration eta will be updated eta = eta*eta_decay, 

Regards

**Comment by walterreade** [comment]
Not directly. But here's is an example that effectively duplicates that functionality.

https://www.kaggle.com/ashhafez/springleaf-marketing-response/xgb-learning-rate-eta-decay

**Comment by Far0n** [comment]
I added eta_decay in python, see https://github.com/dmlc/xgboost/pull/563

**Comment by terrytangyuan** [comment]
Closes via #563
