### ISSUE TITLE
Installation error 

### ISSUE THREAD

**Issue by samyip123** [dmlc/xgboost#5468]
when installing the package with pip3 install xgboost==1.0.2 on macos, the following error occured 
`    ERROR: Command errored out with exit status 1:
     command: /Users/ivan/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/xb/ryd49p4s1j144n90lsvst0fr0000gn/T/pip-install-tfrzw69u/xgboost/setup.py'"'"'; __file__='"'"'/private/var/folders/xb/ryd49p4s1j144n90lsvst0fr0000gn/T/pip-install-tfrzw69u/xgboost/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/xb/ryd49p4s1j144n90lsvst0fr0000gn/T/pip-install-tfrzw69u/xgboost/pip-egg-info
         cwd: /private/var/folders/xb/ryd49p4s1j144n90lsvst0fr0000gn/T/pip-install-tfrzw69u/xgboost/
    Complete output (27 lines):
    ++ pwd
    + oldpath=/private/var/folders/xb/ryd49p4s1j144n90lsvst0fr0000gn/T/pip-install-tfrzw69u/xgboost
    + cd ./xgboost/
    + mkdir -p build
    + cd build
    + cmake ..
    ./xgboost/build-python.sh: line 21: cmake: command not found
    + echo -----------------------------
    -----------------------------
    + echo 'Building multi-thread xgboost failed'
    Building multi-thread xgboost failed
    + echo 'Start to build single-thread xgboost'
    Start to build single-thread xgboost
    + cmake .. -DUSE_OPENMP=0
    ./xgboost/build-python.sh: line 27: cmake: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/xb/ryd49p4s1j144n90lsvst0fr0000gn/T/pip-install-tfrzw69u/xgboost/setup.py", line 42, in <module>
        LIB_PATH = libpath['find_lib_path']()
      File "/private/var/folders/xb/ryd49p4s1j144n90lsvst0fr0000gn/T/pip-install-tfrzw69u/xgboost/xgboost/libpath.py", line 50, in find_lib_path
        'List of candidates:\n' + ('\n'.join(dll_path)))
    XGBoostLibraryNotFound: Cannot find XGBoost Library in the candidate path, did you install compilers and run build.sh in root path?
    List of candidates:
    /private/var/folders/xb/ryd49p4s1j144n90lsvst0fr0000gn/T/pip-install-tfrzw69u/xgboost/xgboost/libxgboost.dylib
    /private/var/folders/xb/ryd49p4s1j144n90lsvst0fr0000gn/T/pip-install-tfrzw69u/xgboost/xgboost/../../lib/libxgboost.dylib
    /private/var/folders/xb/ryd49p4s1j144n90lsvst0fr0000gn/T/pip-install-tfrzw69u/xgboost/xgboost/./lib/libxgboost.dylib
    /Users/ivan/anaconda3/xgboost/libxgboost.dylib
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`

**Comment by nscozzaro** [comment]
What worked for me on my Mac (after getting the error) was:
```
brew install gcc@9 libomp
brew install xgboost
pip3 install xgboost
```

**Comment by hcho3** [comment]
@samyip123 Please install CMake.
