### ISSUE TITLE
Repeated Jenkins build.

### ISSUE THREAD

**Issue by trivialfis** [dmlc/xgboost#5470]
I just killed a job on master 13b10a63700035d78c282188e9f4c49226109c02, which ran for 175 times.  @hcho3 Is there any way we can prevent this from happening again?

https://xgboost-ci.net/blue/organizations/jenkins/xgboost/detail/master/175/pipeline/

**Comment by hcho3** [comment]
?? I don’t see the job running “175 times.” The build ID is 175. Are you referring to the build ID? The build ID merely means that there have been 175 commits to the master since we re-built Jenkins from scratch. Notice that jobs associated to the master branch have different git commit IDs.

**Comment by hcho3** [comment]
I looked at the build log and the job was waiting for provision of a EC2 worker. Why did you have to kill it?

**Comment by trivialfis** [comment]
Oh, my bad.  That's what it means.  I got scared.

**Comment by hcho3** [comment]
Got it. Multiple builds are undesirable only if they all refer to the same commit ID.
