### ISSUE TITLE
DMatrix Concatenation

### ISSUE THREAD

**Issue by chester-leung** [dmlc/xgboost#5478]
Hi, is there currently support for DMatrix concatenation? I saw in https://github.com/dmlc/xgboost/issues/60 that there was discussion on adding support for this, but I couldn't find any documentation on it. 

Thanks!

**Comment by trivialfis** [comment]
No, we do support training on batches via external memory though.

**Comment by chester-leung** [comment]
Are there plans to do add support for this?

**Comment by RAMitchell** [comment]
My current view on this is that it would be easy for us to start building a data frame library from DMatrix, instead I want to push this functionality onto external libraries. You could save a preprocessed file to a csv or libsvm and read it into a DMatrix from disk.
