### ISSUE TITLE
[jvm-package] xgboost >1 not published to maven, or anywhere else

### ISSUE THREAD

**Issue by sa-** [dmlc/xgboost#5494]
Hey team,

xgboost jars should be easily accessible for all, but they are not.

Maven central https://mvnrepository.com/artifact/ml.dmlc/xgboost4j only has up to version 0.90

The snapshot repo @ https://raw.githubusercontent.com/CodingCat/xgboost/maven-repo/  is broken as well

https://github.com/CodingCat/xgboost/tree/maven-repo/ml/dmlc/xgboost4j doesn't list 1.0 either

**Comment by hcho3** [comment]
@CodingCat Can we get 1.0 to Maven?

**Comment by hcho3** [comment]
@sa- We are creating our own Maven repository where you can find latest XGBoost4J JARs: #5533.

**Comment by hcho3** [comment]
XGBoost4J 1.0.0 is now available from our Release repository:
```xml
<repository>
  <id>XGBoost4J Release Repo</id>
  <name>XGBoost4J Release Repo</name>
  <url>https://s3-us-west-2.amazonaws.com/xgboost-maven-repo/release/</url>
</repository>
```

SNAPSHOTs are available from our Snapshot repository:
```xml
<repository>
  <id>XGBoost4J Snapshot Repo</id>
  <name>XGBoost4J Snapshot Repo</name>
  <url>https://s3-us-west-2.amazonaws.com/xgboost-maven-repo/snapshot/</url>
</repository>
```

**Comment by sa-** [comment]
Thank you very much!
