### ISSUE TITLE
[RFC] Remove `distcol` updater.

### ISSUE THREAD

**Issue by trivialfis** [dmlc/xgboost#5498]
The updater is long broken: https://github.com/dmlc/xgboost/issues/1832 and all other tree methods are distributed.  So maintaining this updater might not be necessary.

If we want to restore its support,  first thing needed to to is implementing a method for tree updaters to access a buffered node position for running prediction, like what's in the old code (check out linked issue above).  Then we need to re-enable column splitting in `DMatrix`.  Lastly we need to fix the `distcol`.

I'm not eliminating the possibility of spiting data by column in the future, just suggesting we remove the current `distcol`.   From above note, restoring the support might be best done from scratch to fit the more important updaters like histogram based algorithms.

@RAMitchell @hcho3

**Comment by RAMitchell** [comment]
+1

**Comment by hcho3** [comment]
+1. I don't think it works at all.
