### ISSUE TITLE
n_estimator is not being passed forward by XGBRegressor

### ISSUE THREAD

**Issue by mnky9800n** [dmlc/xgboost#5502]
The following code:

```
xgb = xgboost.XGBRegressor(objective='reg:squarederror', n_estimators=20000, learning_rate=0.01, nrounds=20000, num_boost_round=20000)
```

Should be passing forward the number of boosting rounds either with `n_estimators`, `nrounds`, or `num_boost_round`. However it does not and instead uses the default number of rounds.

When dropping the sklearn API and just passing a dict of params

```
params = {'objective':'reg:squarederror', 'num_boost_round':20000}
xgb = xgboost.train(params, dmatrix_train)
```

This also is not using it. Only by declaring it directly:

```
xgb = xgboost.train(params, dmatrix_train, num_boost_round=20000)
```

Does xgboost finally accept the number of boosting rounds that the user specifies.

**Comment by trivialfis** [comment]
It's passed by the function `get_num_boosting_rounds`.

**Comment by trivialfis** [comment]
``` python
import xgboost
import numpy as np

X = np.random.randn(100, 10)
y = np.random.randn(100)

reg = xgboost.XGBRegressor(objective='reg:squarederror', n_estimators=2,
                           learning_rate=0.01)


reg.fit(X, y)
print(len(reg.get_booster().get_dump()))  # 2
```
