### ISSUE TITLE
[Bug report] XGboost 1.0.2 gives 'weight' key error when using "SelectFromModel' of sklearn

### ISSUE THREAD

**Issue by d8veone** [dmlc/xgboost#5503]
Thanks for participating in the XGBoost community! We use https://discuss.xgboost.ai for any general usage questions and discussions. The issue tracker is used for actionable items such as feature proposals discussion, roadmaps, and bug tracking.  You are always welcomed to post on the forum first :)

Issues that are inactive for a period of time may get closed. We adopt this policy so that we won't lose track of actionable issues that may fall at the bottom of the pile. Feel free to reopen a new one if you feel there is an additional problem that needs attention when an old one gets closed.

For bug reports, to help the developer act on the issues, please include a description of your environment, preferably a minimum script to reproduce the problem.

For feature proposals, list clear, small actionable items so we can track the progress of the change.

**Comment by trivialfis** [comment]
Could you please provide a small example?

**Comment by d8veone** [comment]
Hi 

I got the message as below:

KeyError                                  Traceback (most recent call last)
<ipython-input-54-05b04f3cdcc0> in <module>
      1 model = SelectFromModel(xgb_model,prefit=True)
----> 2 X_selected = model.transform(X)
      3 X_selected=pd.DataFrame(X_selected)
      4 print(X_selected.shape)

~/opt/miniconda3/lib/python3.7/site-packages/sklearn/feature_selection/_base.py in transform(self, X)
     75         X = check_array(X, dtype=None, accept_sparse='csr',
     76                         force_all_finite=not tags.get('allow_nan', True))
---> 77         mask = self.get_support()
     78         if not mask.any():
     79             warn("No features were selected: either the data is"

~/opt/miniconda3/lib/python3.7/site-packages/sklearn/feature_selection/_base.py in get_support(self, indices)
     44             values are indices into the input feature vector.
     45         """
---> 46         mask = self._get_support_mask()
     47         return mask if not indices else np.where(mask)[0]
     48 

~/opt/miniconda3/lib/python3.7/site-packages/sklearn/feature_selection/_from_model.py in _get_support_mask(self)
    176                              ' "prefit=True" while passing the fitted'
    177                              ' estimator to the constructor.')
--> 178         scores = _get_feature_importances(estimator, self.norm_order)
    179         threshold = _calculate_threshold(estimator, scores, self.threshold)
    180         if self.max_features is not None:

~/opt/miniconda3/lib/python3.7/site-packages/sklearn/feature_selection/_from_model.py in _get_feature_importances(estimator, norm_order)
     16     importances = getattr(estimator, "feature_importances_", None)
     17 
---> 18     coef_ = getattr(estimator, "coef_", None)
     19     if importances is None and coef_ is not None:
     20         if estimator.coef_.ndim == 1:

~/opt/miniconda3/lib/python3.7/site-packages/xgboost/sklearn.py in coef_(self)
    714                                  .format(self.booster))
    715         b = self.get_booster()
--> 716         coef = np.array(json.loads(b.get_dump(dump_format='json')[0])['weight'])
    717         # Logic for multiclass classification
    718         n_classes = getattr(self, 'n_classes_', None)

KeyError: 'weight'



Here’s a work around :

# define custom class to fix bug in xgboost 1.0.2
class MyXGBClassifier(XGBClassifier):
	@property
	def coef_(self):
		return None

https://machinelearningmastery.com/feature-importance-and-feature-selection-with-xgboost-in-python/ <https://machinelearningmastery.com/feature-importance-and-feature-selection-with-xgboost-in-python/>

**Comment by trivialfis** [comment]
Let me take a look tomorrow.  Thanks for opening an issue. ;-)

**Comment by GuidoBartoli** [comment]
Hi, I also confirm this issue in my environment:
- python 3.6.9
- scikit-learn 0.22.2.post1
- xgboost 1.0.2

It is also reported and explained in detail [here](https://github.com/scikit-learn/scikit-learn/issues/7926) and [here](https://machinelearningmastery.com/feature-importance-and-feature-selection-with-xgboost-in-python/), do you think it could be resolved in the next xgboost release?

Many thanks,
Cheers

**Comment by hcho3** [comment]
@GuidoBartoli Can you try the latest nightly buil and see if the issue is fixed?
* Linux 64-bit: https://s3-us-west-2.amazonaws.com/xgboost-nightly-builds/xgboost-1.1.0_SNAPSHOT%2B4a0c8ef23714754f2a73414cc13fd3ad05ce7fda-py2.py3-none-manylinux1_x86_64.whl
* Windows 64-bit: https://s3-us-west-2.amazonaws.com/xgboost-nightly-builds/xgboost-1.1.0_SNAPSHOT%2B4a0c8ef23714754f2a73414cc13fd3ad05ce7fda-py2.py3-none-win_amd64.whl

**Comment by GuidoBartoli** [comment]
Yep, that works fine, thanks! :)

**Comment by hcho3** [comment]
@GuidoBartoli That's good to know. The fix will be part of the upcoming 1.1.0 release.
