### ISSUE TITLE
Performance patch for GBTree::Predict

### ISSUE THREAD

**Issue by yoori** [dmlc/xgboost#551]
I use BoostLearner::Predict in c++ code (gbtree model type)
And it give bad performance in case when I call BoostLearner::Predict for small data portion
My research show that bottleneck in GBTree::Predict function:
```
 thread_temp.resize(nthread, tree::RegTree::FVec());
    for (int i = 0; i < nthread; ++i) {
      thread_temp[i].Init(mparam.num_feature);
    }
```

It seems possible to remove excess initialization of thread_temp on each call (16 Mb of float's per thread), because GBTree::Pred revert changed FVec values:
```
    if (itop != trees.size()) {
      p_feats->Fill(inst);
      ….
      p_feats->Drop(inst);
    }
```

I suggest next patch:
```
--- xgboost-orig/src/gbm/gbtree-inl.hpp	2015-10-14 12:59:31.000000000 +0300
+++ xgboost/xgboost/src/gbm/gbtree-inl.hpp	2015-10-14 12:27:34.000000000 +0300
@@ -138,9 +138,12 @@
     {
       nthread = omp_get_num_threads();
     }
-    thread_temp.resize(nthread, tree::RegTree::FVec());
-    for (int i = 0; i < nthread; ++i) {
-      thread_temp[i].Init(mparam.num_feature);
+    int prev_thread_temp_size = thread_temp.size();
+    if(prev_thread_temp_size < nthread) {
+      thread_temp.resize(nthread, tree::RegTree::FVec());
+      for (int i = prev_thread_temp_size; i < nthread; ++i) {
+        thread_temp[i].Init(mparam.num_feature);
+      }
     }
     std::vector<float> &preds = *out_preds;
     const size_t stride = info.num_row * mparam.num_output_group;
```
After this patch BoostLearner::Predict initialize thread_temp only on first call or on OMP thread pool extending.
It helped to me, now on one CPU core (Intel(R) Xeon® CPU X5650  @ 2.67GHz, OMP disabled) BoostLearner::Predict give 625000 calls/sec (without patch it give: 120 calls/sec)

M.b it will help someone

**Comment by tqchen** [comment]
Sounds good, can you open a pull request on this? Thanks!

**Comment by yoori** [comment]
Сreated https://github.com/dmlc/xgboost/pull/552

**Comment by dwroy** [comment]
#3237
