### ISSUE TITLE
Weighted quantile sketch algorithm

### ISSUE THREAD

**Issue by VigneshN1997** [dmlc/xgboost#5521]
Hi all,

I wanted to ask if the weighted quantile sketch algorithm implemented in xgboost can be used independently? Like is it possible just to include quantile.h file and create quantiles on given weighted dataset. I have this doubt because in xgboost, for creating quantiles, functions from updater_basemaker-inl.h is used for pushing values into the quantile for creating initial quantiles. Also like for creating quantiles, UpdateSketchCol in updater_histmaker.cc is used which interfaces with Push in updater_basemaker-inl.h. Also like Push() interfaces with quantile.h using PushTemp() which in turn uses the queue structure and levels structure created in quantile.h. I wanted a flow like this (which is not possible currently since I will have to replicate all the above mentioned functions calls for this behaviour):

1. load data, weights, input epsilon
2. for each value in data:
        push data, weight to sketch
3. query the sketch for specific q values (**the query function is not implemented independently** in WXQSummary struct, it is there inside the SetPrune method)

**Comment by trivialfis** [comment]
No, but that would be neat.  For a simpler usage,  see the `CutsBuilder` class in `hist_util.h`.  GPU implementation is on `hist_util.cu`.  You are more than welcomed to refactor it and make it more broadly applicable. ;-)
