### ISSUE TITLE
"label_upper_bound" and "label_lower_bound" can be set, but not gotten

### ISSUE THREAD

**Issue by Kodiologist** [dmlc/xgboost#5525]
As of XGBoost 88b64c8162ccfdda611590df09e0c97b9e9a400c:

```
> library(xgboost)
> d = xgb.DMatrix(as.matrix(rnorm(50)))
> setinfo(d, "label_lower_bound", rnorm(50))
[1] TRUE
> getinfo(d, "label_lower_bound")
Error in getinfo.xgb.DMatrix(d, "label_lower_bound") :
  getinfo: name must be one of the following
    'label', 'weight', 'base_margin', 'nrow'
```

**Comment by hcho3** [comment]
Good catch! I will put out a fix soon. Thanks a lot for trying out this latest feature!

**Comment by Kodiologist** [comment]
No problem. My group is excited to try AFT modeling with COVID-19 data—with luck, we'll have a paper out very soon.

**Comment by hcho3** [comment]
@Kodiologist Great, let me know if there's anything I can help.
