### ISSUE TITLE
Why version 0.9 on spark dos'nt support feature importance? 

### ISSUE THREAD

**Issue by huaxz1986** [dmlc/xgboost#5526]
When I change version 0.82 to version 0.9 on spark , I found that v0.9 dos'nt support getting feature importance like v0.82:

```
xgboostModel.nativeBooster.getFeatureScore()
```

Is there some API to get feature importance?

**Comment by trivialfis** [comment]
What do you mean by doesn't support?  I see the function is still here:
https://github.com/dmlc/xgboost/blob/c90119eb67f09d3f722c428f08d1cde6359b635b/jvm-packages/xgboost4j/src/main/scala/ml/dmlc/xgboost4j/scala/Booster.scala#L254
