### ISSUE TITLE
Append XGBOOST to Python Path

### ISSUE THREAD

**Issue by penguin2121** [dmlc/xgboost#553]
I'm using the portable WinPython distribution, so I don't have the python command available from the cmd prompt to use "python setup.py install" command to install xgboost.  I'm trying to just add sys.path.append() to my files, but I don't know where to direct this to.  I know that I need to direct it to xgboost.py, but I don't see this file anywhere in any of the directories.  Do you need to build this separately?  I've already built the solutions contained in the windows folder.

Thanks!

**Comment by tqchen** [comment]
It is now moved to https://github.com/dmlc/xgboost/tree/master/python-package you need to add path to this place in your file
