### ISSUE TITLE
Fix seed produced different model with CLI on yarn

### ISSUE THREAD

**Issue by SongBiu** [dmlc/xgboost#5536]
I test two model produced CLI on yarn with same params and seed, but the mae of them are different.
What cause it?

**Comment by trivialfis** [comment]
Are you using distributed XGBoost on both side?

**Comment by SongBiu** [comment]
> Are you using distributed XGBoost on both side?

Yes

**Comment by vipinmenon1989** [comment]
Hi, is it possible to set seed in XGBoost CLI (I am new to it, and help file doesn't have much information)
