### ISSUE TITLE
`group_ptr_` is currently disabled with DMatrix slice.

### ISSUE THREAD

**Issue by trivialfis** [dmlc/xgboost#5545]
@RAMitchell 

I see that there's a Python function `mkgroupfold` in `training.py` that uses group info.  The new adapter would throw an error if `group_ptr_` is presented during slicing.

**Comment by RAMitchell** [comment]
Isnt that what the allow groups parameter in the c_api is for? Not sure I understand.

**Comment by trivialfis** [comment]
Em.  That's right. But right now group ptr is still broken when weight is presented.  As for ranking weight is defined per group.

**Comment by trivialfis** [comment]
Another thing that I'm curious is, is per-group weight supported by GPU sketching?

**Comment by trivialfis** [comment]
Also, the newly added fields by aft objective are not handled by slice.
