### ISSUE TITLE
get_fscore causing kernel crash

### ISSUE THREAD

**Issue by jturkewitz** [dmlc/xgboost#558]
I am attempting to use get_fscore but I am getting a kernel crash when doing so:
gbm = xgb.train(params, dtrain, num_trees, evals=watchlist, early_stopping_rounds=50, feval=rmspe_exp_xg, verbose_eval=True)
gbm.get_fscore
Out[2]: <bound method Booster.get_fscore of <xgboost.core.Booster object at 0x100776c18>>

gbm.get_fscore()
It seems the kernel died unexpectedly. Use 'Restart kernel' to continue using this console.
It seems the kernel died unexpectedly. Use 'Restart kernel' to continue using this console.

Training works fine. I have installed xgboost on my mac with pip, then copied the folder to anaconda/lib/python3.4/site-packages
Which might have something to do with it. I tried to install with pip and conda directly, but I had the problems listed below:
(/Users/Jared/anaconda)c-24-118-48-34:anaconda Jared$ conda install pip
Fetching package metadata: ....
Solving package specifications: .................
# All requested packages already installed.
# packages in environment at /Users/Jared/anaconda:
#
pip                       7.1.2                    py34_0  
(/Users/Jared/anaconda)c-24-118-48-34:anaconda Jared$ pip install xgboost
Collecting xgboost
  Using cached xgboost-0.4a23.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/2y/wtyh6ktj3y5d0_j5fw8d6nhm0000gn/T/pip-build-skikajxg/xgboost/setup.py", line 25
        print 'Windows users please use github installation.'
                                                            ^
    SyntaxError: Missing parentheses in call to 'print'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/2y/wtyh6ktj3y5d0_j5fw8d6nhm0000gn/T/pip-build-skikajxg/xgboost
(/Users/Jared/anaconda)c-24-118-48-34:anaconda Jared$ pip install -v xgboost
Collecting xgboost
  Getting page https://pypi.python.org/simple/xgboost/
  1 location(s) to search for versions of xgboost:
  * https://pypi.python.org/simple/xgboost/
  Getting page https://pypi.python.org/simple/xgboost/
  Analyzing links from page https://pypi.python.org/simple/xgboost/
    Found link https://pypi.python.org/packages/source/x/xgboost/xgboost-0.4a12.tar.gz#md5=4d768e034a28590497bb79279f036946 (from https://pypi.python.org/simple/xgboost/), version: 0.4a12
    Found link https://pypi.python.org/packages/source/x/xgboost/xgboost-0.4a13.tar.gz#md5=5f53d51e4305c679192b3cabda2b0dbe (from https://pypi.python.org/simple/xgboost/), version: 0.4a13
    Found link https://pypi.python.org/packages/source/x/xgboost/xgboost-0.4a14.tar.gz#md5=a7c648933a47ae31f869b5c030c17c69 (from https://pypi.python.org/simple/xgboost/), version: 0.4a14
    Found link https://pypi.python.org/packages/source/x/xgboost/xgboost-0.4a15.tar.gz#md5=bcab760af5ac7f20e88bde7426423565 (from https://pypi.python.org/simple/xgboost/), version: 0.4a15
    Found link https://pypi.python.org/packages/source/x/xgboost/xgboost-0.4a18.tar.gz#md5=9f70ca05843afb1d50522530f140d640 (from https://pypi.python.org/simple/xgboost/), version: 0.4a18
    Found link https://pypi.python.org/packages/source/x/xgboost/xgboost-0.4a19.tar.gz#md5=413d55d0534447e77064dbd1ad1ccb48 (from https://pypi.python.org/simple/xgboost/), version: 0.4a19
    Found link https://pypi.python.org/packages/source/x/xgboost/xgboost-0.4a20.tar.gz#md5=88721733e7c7026fa2e95de7165d4b86 (from https://pypi.python.org/simple/xgboost/), version: 0.4a20
    Found link https://pypi.python.org/packages/source/x/xgboost/xgboost-0.4a21.tar.gz#md5=45284beb53f5087e73dcf55ff1c5a026 (from https://pypi.python.org/simple/xgboost/), version: 0.4a21
    Found link https://pypi.python.org/packages/source/x/xgboost/xgboost-0.4a22.tar.gz#md5=cb858cf85fe9f4263e9b523c4900c3f9 (from https://pypi.python.org/simple/xgboost/), version: 0.4a22
    Found link https://pypi.python.org/packages/source/x/xgboost/xgboost-0.4a23.tar.gz#md5=4f8a17ca86995ed51fc1a424618b94db (from https://pypi.python.org/simple/xgboost/), version: 0.4a23
  Using version 0.4a23 (newest of versions: 0.4a23, 0.4a22, 0.4a21, 0.4a20, 0.4a19, 0.4a18, 0.4a15, 0.4a14, 0.4a13, 0.4a12)
  Using cached xgboost-0.4a23.tar.gz
  Downloading from URL https://pypi.python.org/packages/source/x/xgboost/xgboost-0.4a23.tar.gz#md5=4f8a17ca86995ed51fc1a424618b94db (from https://pypi.python.org/simple/xgboost/)
  Running setup.py (path:/private/var/folders/2y/wtyh6ktj3y5d0_j5fw8d6nhm0000gn/T/pip-build-snj8itd3/xgboost/setup.py) egg_info for package xgboost
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/2y/wtyh6ktj3y5d0_j5fw8d6nhm0000gn/T/pip-build-snj8itd3/xgboost/setup.py", line 25
        print 'Windows users please use github installation.'
                                                            ^
    SyntaxError: Missing parentheses in call to 'print'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/2y/wtyh6ktj3y5d0_j5fw8d6nhm0000gn/T/pip-build-snj8itd3/xgboost/setup.py", line 25
        print 'Windows users please use github installation.'
                                                            ^
    SyntaxError: Missing parentheses in call to 'print'
    
    ----------------------------------------
Cleaning up...
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/2y/wtyh6ktj3y5d0_j5fw8d6nhm0000gn/T/pip-build-snj8itd3/xgboost
Exception information:
Traceback (most recent call last):
  File "/Users/Jared/anaconda/lib/python3.4/site-packages/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/Users/Jared/anaconda/lib/python3.4/site-packages/pip/commands/install.py", line 305, in run
    wb.build(autobuilding=True)
  File "/Users/Jared/anaconda/lib/python3.4/site-packages/pip/wheel.py", line 705, in build
    self.requirement_set.prepare_files(self.finder)
  File "/Users/Jared/anaconda/lib/python3.4/site-packages/pip/req/req_set.py", line 334, in prepare_files
    functools.partial(self._prepare_file, finder))
  File "/Users/Jared/anaconda/lib/python3.4/site-packages/pip/req/req_set.py", line 321, in _walk_req_to_install
    more_reqs = handler(req_to_install)
  File "/Users/Jared/anaconda/lib/python3.4/site-packages/pip/req/req_set.py", line 505, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/Users/Jared/anaconda/lib/python3.4/site-packages/pip/req/req_set.py", line 123, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/Users/Jared/anaconda/lib/python3.4/site-packages/pip/req/req_install.py", line 410, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/Users/Jared/anaconda/lib/python3.4/site-packages/pip/utils/__init__.py", line 733, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /private/var/folder

Thank you.

**Comment by sinhrks** [comment]
Might be related to #498 (#487). Loading invalid file name may cause segfault in later part.

Can you provide reproducible example including data?

**Comment by jturkewitz** [comment]
Hi,
My problem seems to have solved itself. I wrote code to reproduce it, I have copied it below, and attempted to run it from spyder 2.3.7 which comes with anaconda. This caused the same kernel crash as before. But then I ran the code in python, and it worked fine. After that I could run it in spyder without the crash, so somehow my system was in a bad state or something. Thanks.

# -*- coding: utf-8 -*-
"""
Created on Sun Oct 25 00:11:45 2015

@author: Jared
"""
#%%
import pandas as pd
import numpy as np
import xgboost as xgb
import random
from sklearn import cross_validation
#%%
rng = np.random.RandomState(4)
random.seed(4)
np.random.seed(4)

def rmspe_exp_xg(y_pred, y_true):
    y_true = y_true.get_label()
    y_true = np.exp(y_true)
    y_pred = np.exp(y_pred)
    rmspe = np.sqrt(np.mean(np.square((y_true - y_pred) / y_true)))
    return "rmspe", rmspe


params = {'max_depth': 2, 'colsample_bytree': 0.9, 'seed': 4,
'subsample': 0.9, 'learning_rate': 0.9}
num_trees = 9
print("Train a XGBoost model")

dates = pd.date_range('20130101',periods=6)
df = pd.DataFrame(np.random.randn(6,5),index=dates,columns=list('ABCDE'))
df['Sales_Log'] = df['E'].map(lambda x: 10 + x)

X_train, X_watch = cross_validation.train_test_split(df, test_size=0.01,random_state=4)


train_data = X_train.values
train_sales_log = X_train['Sales_Log'].values
watch_data = X_watch.values
watch_sales_log = X_watch['Sales_Log'].values

dtrain = xgb.DMatrix(train_data, train_sales_log)
dwatch = xgb.DMatrix(watch_data, watch_sales_log)
watchlist = [(dwatch, 'eval'), (dtrain, 'train')]

gbm = xgb.train(params, dtrain, num_trees, evals=watchlist, early_stopping_rounds=50, feval=rmspe_exp_xg, verbose_eval=True)
imp_dict = gbm.get_fscore()
print(imp_dict)

**Comment by phunterlau** [comment]
@jturkewitz seems not kernel crash but installing from a (kind of) buggy pip version xgboost-0.4a23.tar.gz . It was my bad that print was not python 3 style. It is fixed in #549 , please remove the old pip installation and pip install again (currently 0.4a24):
1. `rm -rf /Users/Jared/anaconda/lib/python3.4/site-packages/xgboost*/`
2. `pip install xgboost`

**Comment by jturkewitz** [comment]
I can confirm I don't have this error after re-installing xgboost.
