### ISSUE TITLE
[FEA][Python] Multi-GPU training with `DeviceQuantileDMatrix` 

### ISSUE THREAD

**Issue by ayushdg** [dmlc/xgboost#5583]
A helpful feature would be if the newly added  `DeviceQuantileDMatrix` could be extended to Multi-GPU/Multi-node training via dask backend.

**Comment by trivialfis** [comment]
It's on the roadmap, but #5516 and #5571 need to be resolved first.

**Comment by brunogasperini** [comment]
This would certainly be very appreciated. Thanks.
