### ISSUE TITLE
[Doc Question] `distcol` removed from `updater` in latest

### ISSUE THREAD

**Issue by aws-patlin** [dmlc/xgboost#5588]
From the [latest documentation](https://xgboost.readthedocs.io/en/latest/parameter.html#parameters-for-tree-booster), it looks like `distcol` is no longer a supported value for `updater`, whereas this is still available in the [release_1.0.0 documentation](https://xgboost.readthedocs.io/en/release_1.0.0/parameter.html#parameters-for-tree-booster). Is this correct? If so, will there be other backwards incompatible changes like this between feature versions?

**Comment by hcho3** [comment]
We clearly mark all breaking changes as part of the release note. As for `distcol`, it has never been tested as part of CI and to my knowledge did not work. See #1832 and #5498.

**Comment by aws-patlin** [comment]
Gotcha, thanks for the answer!
