### ISSUE TITLE
Serializability of xgboost Booster object in the Java wrapper

### ISSUE THREAD

**Issue by pradipto** [dmlc/xgboost#559]
Hi,

I need to wrap the Booster object in a Java wrapper class which needs to be serializable. The scenario is this: 
1. A model is loaded from the saved binary file and held in a Booster object reference inside the wrapper class
2. The wrapper class needs to be sent to multiple Spark instances, all of which expect a serializable Booster object to be referenced from within the Wrapper class.

Any comments/help on this matter is appreciated.

Regards
Pradipto

**Comment by tqchen** [comment]
I guess this is not yet supported, but can be done by utilizing the serialization into byte arrays
