### ISSUE TITLE
[FEA] Implement predict_proba in DaskXGBClassifier

### ISSUE THREAD

**Issue by programmylife** [dmlc/xgboost#5619]
Currently, the DaskXGBClassifier only implements predict(), but we would like to also have access to predict_proba() when using DaskXGBClassifier to match the non-Dask version.

**Comment by harshit-2115** [comment]
Check this 
https://github.com/dmlc/xgboost/issues/5451#issuecomment-617587125

**Comment by JohnZed** [comment]
@trivialfis this is closed by https://github.com/dmlc/xgboost/pull/5986 right?

**Comment by trivialfis** [comment]
Right.
