### ISSUE TITLE
Error when seed exceeds 32-bit integer max

### ISSUE THREAD

**Issue by pplonski** [dmlc/xgboost#5637]
I'm using Xgboost in my [AutoML package](https://github.com/mljar/mljar-supervised). I'm currently adding my package to [automlbenchmark](https://github.com/openml/automlbenchmark) When running the benchmark test I got very strange error about seed value. The error is below. The minimal code example to reproduce the error is below. When I'm using smaller `seed` values every thing works as expected.

```python
import xgboost # 1.0.2 version
import numpy as np

X = np.random.rand(100,4)
y = np.random.randint(0,2,100)
train = xgboost.DMatrix(X, label=y)
model = xgboost.train({"seed": 3657279955}, train)
```

Error message:
```python
---------------------------------------------------------------------------
XGBoostError                              Traceback (most recent call last)
<ipython-input-135-653bcbdd849c> in <module>
----> 1 model = xgboost.train({"seed": 3657279955}, train)

~/Downloads/numerai_datasets/venv/lib/python3.6/site-packages/xgboost/training.py in train(params, dtrain, num_boost_round, evals, obj, feval, maximize, early_stopping_rounds, evals_result, verbose_eval, xgb_model, callbacks)
    207                            evals=evals,
    208                            obj=obj, feval=feval,
--> 209                            xgb_model=xgb_model, callbacks=callbacks)
    210 
    211 

~/Downloads/numerai_datasets/venv/lib/python3.6/site-packages/xgboost/training.py in _train_internal(params, dtrain, num_boost_round, evals, obj, feval, xgb_model, callbacks)
     72         # Skip the first update if it is a recovery step.
     73         if version % 2 == 0:
---> 74             bst.update(dtrain, i, obj)
     75             bst.save_rabit_checkpoint()
     76             version += 1

~/Downloads/numerai_datasets/venv/lib/python3.6/site-packages/xgboost/core.py in update(self, dtrain, iteration, fobj)
   1247             _check_call(_LIB.XGBoosterUpdateOneIter(self.handle,
   1248                                                     ctypes.c_int(iteration),
-> 1249                                                     dtrain.handle))
   1250         else:
   1251             pred = self.predict(dtrain, training=True)

~/Downloads/numerai_datasets/venv/lib/python3.6/site-packages/xgboost/core.py in _check_call(ret)
    187     """
    188     if ret != 0:
--> 189         raise XGBoostError(py_str(_LIB.XGBGetLastError()))
    190 
    191 

XGBoostError: Invalid Parameter format for seed expect int but value='3657279955'
```

**Comment by hcho3** [comment]
Seed should fit into signed 32-bit integer value, which can be at most 2147483647.

**Comment by hcho3** [comment]
@pplonski Do you have a use case that specifically calls for a seed value exceeding 2147483647?

**Comment by pplonski** [comment]
In the [automlbenchmark](https://github.com/openml/automlbenchmark) there are seed values larger than 2147483647.

**Comment by hcho3** [comment]
@pplonski Can you elaborate more on the benefit of 64-bit seeds?

**Comment by pplonski** [comment]
If the package is accepting `int` as a `seed` then there can be situations that will throw such error. I think for consistency reason it will be nice to fix it or at least add to the docs that seed should be 32-bits.

The automlbenchmark package is using 64-bit seed. The Auto-WEKA is one of the packages that it is testing.

**Comment by hcho3** [comment]
For now I'll add a check on the Python side so that error message will be clearer.

**Comment by trivialfis** [comment]
Seed is not saved.

**Comment by hcho3** [comment]
@trivialfis Oops,  my bad. I forgot that generic parameter is not part of the legacy binary format. We could potentially upgrade to 64-bit seed then?

**Comment by hcho3** [comment]
@pplonski https://github.com/dmlc/xgboost/pull/5638 adds the error message.

**Comment by trivialfis** [comment]
@hcho3 

> We could potentially upgrade to 64-bit seed then?

I think so. ;-)
