### ISSUE TITLE
How to choose the local proposal or global proposal  for 'tree_method=approx'

### ISSUE THREAD

**Issue by Pein-hub** [dmlc/xgboost#5646]
In the xgboost paper, 
![image](https://user-images.githubusercontent.com/43956043/81360676-06a16980-910f-11ea-8943-1a9065ea10e1.png)

but i dont know how to select the local or global when the tree_method is approx?
and what is the default proposal when the tree_method is approx?

in the xgboost web,
![image](https://user-images.githubusercontent.com/43956043/81360862-757ec280-910f-11ea-814f-37cfbf18a0cb.png)

which param can achieve？

**Comment by thvasilo** [comment]
For approx AFAIK you can only choose the global proposals. You can choose a different updater such as `updater=grow_local_histmaker` to use local predictions.

Most development is aimed at the `hist` tree method so unless you have a good reason to be using approx I'd recommend using that instead.

**Comment by Pein-hub** [comment]
thank u,
