### ISSUE TITLE
read can not have position excceed buffer length

### ISSUE THREAD

**Issue by dandan0503** [dmlc/xgboost#5650]
hi，
    i train xgboost in python and read use spark ml.dmlc.xgboost4j.scala.XGBoost.loadModel(in: InputStream),but get "read can not have position excceed buffer length" error
    my xgboost is save by xgboost.save_model()
    my spark is 2.4 and xgboost4j-spark 0.90
thank you~

**Comment by trivialfis** [comment]
What's the Python XGBoost version?

**Comment by dandan0503** [comment]
Python XGBoost version is 1.0.2

**Comment by yimingxliu** [comment]
I used :
modelTmp.saveModelAsHadoopFile(xgbModelPath)
xgbModel = XGBoost.loadModelFromHadoopFile(xgbModelPath)
in model training task, it can run successfully;

but in another model predict task, I used:
try{
    xgbModelObj = XGBoost.loadModelFromHadoopFile(xgbModelPath)
    println("xgbModelObj loaded successfully ! ")
}
the task cannot run and output :"AssertError:read can not have position excceed buffer length"

**Comment by trivialfis** [comment]
The binary model format is not forward compatible.  Which means you can load the old model in newer versions, but not the other way around.  Hopefully we can migrate to newer JSON format sooner. ;-)

**Comment by dandan0503** [comment]
Ok, I see. Thank you very much~~

**Comment by ICDI0906** [comment]
> The binary model format is not forward compatible. Which means you can load the old model in newer versions, but not the other way around. Hopefully we can migrate to newer JSON format sooner. ;-)

xgb 0.82 can't read the model generated by 0.80? Looking forward to your reply.

**Comment by trivialfis** [comment]
It can, but not the other way around.

**Comment by ICDI0906** [comment]
thinks, I will have another try.

**Comment by BELKADATA** [comment]
i have same problem AssertError:read can not have position excceed buffer length with i exécute my  flask --app api.py run
