### ISSUE TITLE
AssertError:read can not have position excceed buffer length

### ISSUE THREAD

**Issue by yimingxliu** [dmlc/xgboost#5656]
I used :
modelTmp.saveModelAsHadoopFile(xgbModelPath)
xgbModel = XGBoost.loadModelFromHadoopFile(xgbModelPath)
in model training task, it can run successfully;

but in another following model predict task, I used:
try{
xgbModelObj = XGBoost.loadModelFromHadoopFile(xgbModelPath)
println("xgbModelObj loaded successfully ! ")
}
the task cannot run and output :"AssertError:read can not have position excceed buffer length"

**Comment by yimingxliu** [comment]
<img width="131" alt="hdfs xib model file" src="https://user-images.githubusercontent.com/32118588/81789611-d0ad1c80-9536-11ea-9134-d2e80e1bbd91.png">

**Comment by trivialfis** [comment]
Are you loading a model generated by XGBoost 1.x with XGBoost <= 9.x ?

**Comment by yimingxliu** [comment]
I did not change the version in the pom.xml of the scala project,
But I made a new .jar file recently, I guess maybe the lib file changed
