### ISSUE TITLE
Bug with XGBoost on conda

### ISSUE THREAD

**Issue by cast42** [dmlc/xgboost#566]
The following [code](https://www.kaggle.com/cast42/rossmann-store-sales/xgboost-via-sklearn/) does not run on Kaggle (or under python 3 and anaconda). The error message has to do with line 139 in [training.py](https://github.com/dmlc/xgboost/blob/master/python-package/xgboost/training.py).
Apparently the range is float although it is the result from an integer division:

    res_per_eval = len(res) // len(evals_name)
    for r in range(res_per_eval):

The code on Kaggle runs fine on my own machine locally under OSX, Python 2.7 and Xgboost Version 0.4a14

**Comment by phunterlau** [comment]
not sure it is related to the division operator or your code. since you have installed from pip (0.4a14 is a temp pip version number), do you want to remove the old xgboost, pip install the latest version and see if it fixes the problem?

**Comment by cast42** [comment]
The error is not with 0.4a14 on my system (I runs fine)  but when I run XGboost on conda (Kaggle's environment). This is the message if I run XGBoost on Kaggle's environment:

    Traceback (most recent call last):
       File "../src/script.py", line 106, in early_stopping_rounds=100)
       File "/opt/conda/lib/python3.4/site-packages/xgboost-0.4-py3.4.egg/xgboost/sklearn.py", line 189, in fit
           verbose_eval=verbose)
      File "/opt/conda/lib/python3.4/site-packages/xgboost-0.4-py3.4.egg/xgboost/training.py", line 139, in train
    for r in range(res_per_eval):
    TypeError: 'float' object cannot be interpreted as an integer

The integer division // looks ok but is still strange the error message is about 'float'.For some reason res_per_eval is a float object and it should be int.

Thanks for looking into this.

**Comment by morganmcg1** [comment]
@tqchen I am having the same problem when I call bst.predict using the sklearn wrapper, using ubuntu with python 3.5.3 and xgb 0.4

`bst = xgb.sklearn.XGBClassifier()`
`bst.fit(X_train,y_train.values.ravel())`
`pred = bst.predict(X_test)`

- X_train, X_test and y_train are all dataframes
- The number of rows in X_test is 999 and the size of the dataframe is 3996

> TypeError                                 Traceback (most recent call last)
<ipython-input-92-8be15a9001d3> in <module>()
     40 bst = xgb.sklearn.XGBClassifier()
     41 bst.fit(X_train, y_train.values.ravel())
---> 42 pred = bst.predict(X_test)
     43 pred
     44 #dtrain_df_test.fit(estimator, y['da_imb_margin_interval_-15_15'])

> /home/morgan/py3_kernel/lib/python3.5/site-packages/xgboost/sklearn.py in predict(self, data, output_margin, ntree_limit)
>     359         class_probs = self.booster().predict(test_dmatrix,
>     360                                              output_margin=output_margin,
> --> 361                                              ntree_limit=ntree_limit)
>     362         if len(class_probs.shape) > 1:
>     363             column_indexes = np.argmax(class_probs, axis=1)
> 
> /home/morgan/py3_kernel/lib/python3.5/site-packages/xgboost/core.py in predict(self, data, output_margin, ntree_limit, pred_leaf)
>     838         nrow = data.num_row()
>     839         if preds.size != nrow and preds.size % nrow == 0:
> --> 840             preds = preds.reshape(nrow, preds.size / nrow)
>     841         return preds
>     842 
> 
> TypeError: 'float' object cannot be interpreted as an integer
>
