### ISSUE TITLE
Support restoring a pickled model from an older version

### ISSUE THREAD

**Issue by LenzDu** [dmlc/xgboost#5671]
Hi there, I understand it has been stated that we shouldn't expect to be able to load a pickled model built in older version. But as I looked into the codes in version 0.82 for example, xgboost actually transfers `Booster.handle` to a bytearray and pickle it.

It is already supported to load a model from bytearray in v1.0.2 (#5360), it should be possible to restore a pickled model too since it's also saved as a bytearray

To provide more details, we have different logics to restore a bytearray during `Booster.__setstate__` and `Booster.load_model` (in v1.0.2):

`Booster.__setstate__`:
```python
        if handle is not None:
            buf = handle
            dmats = c_array(ctypes.c_void_p, [])
            handle = ctypes.c_void_p()
            _check_call(_LIB.XGBoosterCreate(
                dmats, c_bst_ulong(0), ctypes.byref(handle)))
            length = c_bst_ulong(len(buf))
            ptr = (ctypes.c_char * len(buf)).from_buffer(buf)
            _check_call(
                _LIB.XGBoosterUnserializeFromBuffer(handle, ptr, length))
            state['handle'] = handle
```

`Booster.load_model`:
```python
        elif isinstance(fname, bytearray):
            buf = fname
            length = c_bst_ulong(len(buf))
            ptr = (ctypes.c_char * len(buf)).from_buffer(buf)
            _check_call(_LIB.XGBoosterLoadModelFromBuffer(self.handle, ptr,
                                                          length))
```

It is `XGBoosterUnserializeFromBuffer` that is raising the error during unpickling. I don't know the difference between `XGBoosterUnserializeFromBuffer` and `XGBoosterLoadModelFromBuffer`, but I guess the latter is newer. If I am not missing something, we should be able to support unpickling If we align this new logics added in #5360 to `__setstate__` as well.

Pickling is still widely used in many scenarios in industry. While we understand pickling is not designed for cross version / platform compatibilities, it's still nice to reduce one more breaking change if that doesn't involve too much efforts. Thanks!

**Comment by trivialfis** [comment]
No.  We discussed the issues here :https://xgboost.readthedocs.io/en/latest/tutorials/saving_model.html  To summarize, there are 2 problems

1 The Python bytecode.  We can't promise loading the byecode back, as that means from now on we basically can not change any python code at all, this is particularly impossible for scikit learn interface.  Also your model will be tied to Python version as pickled byte code can not be safely loaded in different Python version.
2 Internal states of XGBoost.  They are not related to the model, sometimes it might be internal parameter, sometime it might be internal structure of optimizers.


If stability is desired, please use save model.  It's not a XGBoost only case, you might want to do that with all the libraries you are using including Python native libraries like scikit learn.
