### ISSUE TITLE
Issue with XGBoost install on mac catalina 

### ISSUE THREAD

**Issue by millfields99** [dmlc/xgboost#5672]
Hi,
I tried installing xgboost using the brew install xgboost on my macbook pro. I'm pretty new to this but I think I followed the steps in other people's install problems. When I tried importing xgboost I got the following error:
(BTW I did install the conda version 0.90 and it rank OK. I wanted the latest version so went the brew route )

Cannot find XGBoost Library in the candidate path, did you install compilers and run build.sh in root path?
List of candidates:
/Users/farookkhan/Projects/xgboost/python-package/xgboost/libxgboost.dylib
/Users/farookkhan/Projects/xgboost/python-package/xgboost/../../lib/libxgboost.dylib
/Users/farookkhan/Projects/xgboost/python-package/xgboost/./lib/libxgboost.dylib
/Users/farookkhan/opt/miniconda3/xgboost/libxgboost.dylib

**Comment by hcho3** [comment]
@millfields99 We just released XGBoost 1.1.0 and now pre-built binary wheel for Mac OS is available. You can install XGBoost by running
```
pip install xgboost==1.1.0
```

**Comment by anupamhore** [comment]
While installing brew install libomp  I got this error

Download failed: https://homebrew.bintray.com/bottles/libomp-11.1.0.catalina.bottle.tar.gz

How to install xgboost in mac??

**Comment by hcho3** [comment]
Please file an issue at https://github.com/Homebrew/homebrew-core
