### ISSUE TITLE
 [R] compilation failed for package 'xgboost': invalid initialization of non-const reference of type

### ISSUE THREAD

**Issue by ras44** [dmlc/xgboost#5685]
Installing xgboost 1.0.0.1 in RStudio leads to:

```
In file included from amalgamation/xgboost-all0.cc:68:0:
amalgamation/../src/learner.cc: In member function ‘virtual void xgboost::LearnerImpl::SaveModel(xgboost::Json*) const’:
amalgamation/../src/learner.cc:378:24: error: invalid initialization of non-const reference of type ‘xgboost::Json&’ from an rvalue of type ‘<brace-enclosed initializer list>’
     Json& out { *p_out };
                        ^
amalgamation/../src/learner.cc: In member function ‘virtual void xgboost::LearnerImpl::SaveConfig(xgboost::Json*) const’:
amalgamation/../src/learner.cc:441:24: error: invalid initialization of non-const reference of type ‘xgboost::Json&’ from an rvalue of type ‘<brace-enclosed initializer list>’
     Json& out { *p_out };
                        ^
make: *** [amalgamation/xgboost-all0.o] Error 1
ERROR: compilation failed for package ‘xgboost’
```

On the other hand, the following succeeds:
```
packageurl <- "http://cran.r-project.org/src/contrib/Archive/xgboost/xgboost_0.90.0.2.tar.gz"
install.packages(packageurl, repos=NULL, type="source")
```

**Comment by trivialfis** [comment]
What compiler are you using?

**Comment by whheath** [comment]
I'm having the exact same error. Trying to upgrade from 0.71.2
R version 3.4.1 (2017-06-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

gcc version 7.3.1 20180303 (Red Hat 7.3.1-5) (GCC)

**Comment by whheath** [comment]
Had this exact problem trying to upgrade from an earlier version on Centos 7. GCC was version 4.8.5. Fix was to install the devtoolkit with newer gcc here: https://www.softwarecollections.org/en/scls/rhscl/devtoolset-7/

**Comment by ras44** [comment]
We're using CentOS 7 as well, so this is likely the issue.  Thanks for your input @AYellowDart 👍

**Comment by hcho3** [comment]
Indeed XGBoost requires GCC 5+ to compile, because it follows C++11 standard.
https://github.com/dmlc/xgboost/blob/60511a3222cd164da93351c441b5018da7169b76/CMakeLists.txt#L16

**Comment by ras44** [comment]
Thanks, that's useful information.  It might be helpful if that warning message appears when the R installation fails.  Or possibly include the GCC 5 version requirement in `SystemRequirements:` in DESCRIPTION:

https://github.com/dmlc/xgboost/blob/60511a3222cd164da93351c441b5018da7169b76/R-package/DESCRIPTION#L67

**Comment by hcho3** [comment]
The DESCRIPTION file states C++11 as requirement, and GCC 4.x doesn't really support C++11 fully.

**Comment by ras44** [comment]
Thanks- it seems like `SystemRequirements` are not enforced or tested on installation, because when I install it the only error I get is the gcc compile error (not a dependency error).  Maybe that is an issue with R's package management?  What might help resolve this issue is some kind of output indicating that GCC5+ is required.

**Comment by trivialfis** [comment]
We don't require specific compiler, but require language version.  Checking whether the compiler is capable of compiling that language is the job of build tool.  For XGBoost normally it's CMake, but R package uses autotools.

Surely you can add checks in the autotools script for compiler capabilities like whether it can compile with regex etc.  But I don't think anyone here like using autotools.

**Comment by ras44** [comment]
Got it- sounds like it's on autotools then.  Thanks for the additional info.
