### ISSUE TITLE
Error initializing XGBoostClassifier in spark

### ISSUE THREAD

**Issue by Ben-Epstein** [dmlc/xgboost#5688]
Running Spark 2.4.0
XGBoost maven jars 1.0.0

**Code:**
```
import ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier
val xgbClassifier = new XGBoostClassifier()
```
I **did** add the jars `xgboost4j_2.12-1.0.0.jar` and `xgboost4j-spark_2.12-1.0.0.jar` to the Spark submit args, and it's importing fine so that worked.

**The error:**
```
java.lang.NoSuchMethodError: org.apache.spark.ml.param.shared.HasWeightCol.$init$(Lorg/apache/spark/ml/param/shared/HasWeightCol;)V
  at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.<init>(XGBoostClassifier.scala:43)
  at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.<init>(XGBoostClassifier.scala:46)
  ... 58 elided
```

I was following [this](https://xgboost.readthedocs.io/en/latest/jvm/xgboost4j_spark_tutorial.html#build-an-ml-application-with-xgboost4j-spark) tutorial.

What did I do wrong?

Thanks!

**Comment by Data-drone** [comment]
I have the same issue. Does anyone have any clues?

**Comment by Data-drone** [comment]
I think it might be a version thing: ala https://github.com/dmlc/xgboost/issues/4399#issuecomment-492887898
