### ISSUE TITLE
How to Use in Scikit-Learn GridSearchCV

### ISSUE THREAD

**Issue by penguin2121** [dmlc/xgboost#569]
I know there is a scikit.py wrapper interface in the xgboost python directory.  My question is, how do I use it?  All I see are forums where people say to use it, but I don't see any saying how to.

Thanks a ton for your help!

**Comment by phunterlau** [comment]
The official sk-learn example is here https://github.com/dmlc/xgboost/blob/master/demo/guide-python/sklearn_examples.py and fortunately in a recently closed kaggle competition, I made a public script with customized score function which may demonstrate some advanced usage of xgboost grid search function https://www.kaggle.com/phunter/flavours-of-physics/gridsearchcv-with-feature-in-xgboost Hope they can help.
