### ISSUE TITLE
Question about XGBoost distributed training of rabit

### ISSUE THREAD

**Issue by sneaxiy** [dmlc/xgboost#5694]
I am not very familiar with XGBoost distributed training using rabit, and want to ask some questions.

In this ut, does the file `agaricus.txt.train` would be splitted into N pieces logically (where N is the number of workers), and each worker read only part of the file?

https://github.com/dmlc/xgboost/blob/646def51e02d4017ac85065a10ca763e8941d62a/tests/distributed/test_basic.py#L1-L29

What if I want to perform distributed training using several machines instead of multi-processes in local machine? To ensure that (1) each worker reads non-duplicate data, and (2) the data all workers read is exactly the total data in the input file, should I separate the input file into N pieces beforehand and distribute each piece to each worker, or just distribute the total input file to each worker directly?

**Comment by trivialfis** [comment]
Nowadays, use a distributed framework.  XGBoost supports many of them.
