### ISSUE TITLE
predictSingle Error

### ISSUE THREAD

**Issue by amod99** [dmlc/xgboost#5695]
I am getting below error when trying to predict for single example on binary classifier model. 
java.lang.IllegalStateException: Can't invoke predictSingle() because this model outputs multiple values: 0
Below is code :

 Predictor predictor = new Predictor(
                        new java.io.FileInputStream("path-to-model-file"));

 // Create feature vector from sparse representation by map
                FVec fVecSparse = FVec.Transformer.fromMap(
                        new java.util.HashMap<Integer, Double>() {{
                            put(49722683, 0.);
                            put(123455, 1.);
                            put(50000001, 1.3979400086720377);

                        }});        

        double pred = predictor.predictSingle(fVecSparse);

**Comment by amod99** [comment]
Interestingly issue doesnt occur when model is built using version < 1 (release_0.90 )

**Comment by hcho3** [comment]
I don’t see a function named predictSingle in XGBoost API.

**Comment by amod99** [comment]
I am using this https://github.com/komiya-atsushi/xgboost-predictor-java library for generating online prediitions.

**Comment by hcho3** [comment]
It appears that the xgboost-predictor-java library doesn't support the latest XGBoost model format. We made a breaking change for the 1.0.0 version (https://github.com/dmlc/xgboost/pull/5281) that changed how the model is saved.

**Comment by amod99** [comment]
thanks for the update ! , i have opened up issue with java library.

**Comment by trivialfis** [comment]
Please consider using the JSON format.
