### ISSUE TITLE
Python package cannot invoke all threads when "n_jobs=-1" on Linux

### ISSUE THREAD

**Issue by AaronX121** [dmlc/xgboost#5703]
Hi, I encountered one problem when running XGBoost on different platforms (Win10 and Ubuntu 18.04). Setting the argument `n_jobs` as `-1` for **XGBClassifier**, it turns out that XGBoost cannot successfully invoke all threads on Ubuntu (However, manually setting `n_jobs` to the maximum number of threads in CPU works fine). What makes it strange is that exactly the same codes (`n_jobs=-1`) running on Windows 10 succeed in invoking all threads.

I have upgraded XGBoost on both platforms to the latest version `1.1.0`, and the problem still exsits. Below is one script that reproduces the problem.

```
import time
from keras.datasets import mnist
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score

if __name__ == "__main__":

    (X_train, y_train), (X_test, y_test) = mnist.load_data()
    X_train = X_train.reshape(X_train.shape[0], -1)
    X_test = X_test.reshape(X_test.shape[0], -1)

    clf = XGBClassifier(n_estimators=100,
                        learning_rate=0.3,
                        max_depth=6,
                        objective="multi:softmax",
                        booster="gbtree",
                        n_jobs=-1)
    tic = time.time()
    clf.fit(X_train, y_train, eval_metric='logloss')
    toc = time.time()
    y_pred = clf.predict(X_test)
    acc = accuracy_score(y_test, y_pred) * 100.
    print("XGBoost Testing Accuracy: {:.3f} %".format(acc))
    print("Training Time: {:.3f} s".format(toc-tic))
```

Here is one screenshot on `htop` command when running codes above on Ubuntu:
![ubuntu](https://user-images.githubusercontent.com/22359569/82795814-1a86f280-9ea7-11ea-96a5-4c45048fb5a8.png)

Since setting `n_jobs` to the maximum number of threads works fine, it looks like there is no problem related to paralleling. I wonder what makes the difference between two platforms when running exactly the same codes.

**Comment by hcho3** [comment]
Try setting `n_jobs` to 0 and see what happens. This line indicates the default value is 0, not -1:
https://github.com/dmlc/xgboost/blob/21ed1f0c6d90f8a734150130eda1b3426f00c308/include/xgboost/generic_parameters.h#L58-L59

**Comment by trivialfis** [comment]
I think this is inconsistent to DMatrix.

**Comment by hcho3** [comment]
We should accept both 0 and -1 as meaning "all cores."

**Comment by AaronX121** [comment]
* Windows: `-1` and `0` both work
* Ubuntu: only `0` works

Agree that it would be more amiable if `-1` is also recognized as using all threads, which is the custom of Joblib and Sklearn.

**Comment by trivialfis** [comment]
Actually currently we don't do anything if it's set to 0.  We just use whatever default value set by omp.  This way users can set the global parameter for all libraries they use.

**Comment by AaronX121** [comment]
Solved.

**Comment by trivialfis** [comment]
Reopening as a reminder to make xgboost more user friendly.
