### ISSUE TITLE
Wrong plist is printed for the python package

### ISSUE THREAD

**Issue by yurivict** [dmlc/xgboost#5705]
```
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: %%PYTHON_SITELIBDIR%%/xgboost/lib/libxgboost.so
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: %%PYTHON_SITELIBDIR%%/libxgboost.so
===> Error: Plist issues found.
```

**Comment by yurivict** [comment]
It shouldn't even reinstall libxgboost.so, it should use the pre-installed libxgboost.so

**Comment by trivialfis** [comment]
Would you like to open a PR for checking system level installation?

**Comment by trivialfis** [comment]
To resolve this, we need build flag in `setup.py` to let users decide whether do they want to reuse `libxgboost.so` in system path.

**Comment by merleyc** [comment]
Hi @trivialfis ,

I want to learn how to contribute to XGBoost so I'd like to be considered to work on this issue.
I know how to build the shared library:
_**... build]$  make -j$(nproc)**
[ 14%] Built target dmlc
[ 20%] Built target rabit
[ 26%] Built target rabit_mock_static
Scanning dependencies of target objxgboost
[ 28%] Building CXX object src/CMakeFiles/objxgboost.dir/common/quantile.cc.o
[ 93%] Built target objxgboost
[ 94%] Linking CXX shared library ../../lib/libxgboost4j.so
[ 96%] Linking CXX executable ../xgboost
[ 97%] Built target runxgboost
[ 98%] Built target xgboost4j
[100%] Linking CXX shared library ../lib/libxgboost.so
[100%] Built target xgboost_

How can I reproduce this issue? I don't get this issue even when I create a editable installation (_python setup.py develop_).

Thank you!

**Comment by trivialfis** [comment]
Sorry for the long wait.  This is about using `libxgboost.so` from system paths like `/usr/lib64/libxgboost.so` instead of the shared library from `soure-path-to-xgboost/lib`.

**Comment by trivialfis** [comment]
This way, some packaging systems can avoid having 2 identical shared libraries.
