### ISSUE TITLE
No CMAKE_CUDA_COMPILER could be found.

### ISSUE THREAD

**Issue by raphay3l** [dmlc/xgboost#5706]
Hi!

Unable to build GPU support. Please help.

I had tried VS 2017 with CUDA 8.0, 9.0, 10.0, 10.1 and 10.2 and also VS 2019 with CUDA 10.2. I am installing on Windows 10 inside Anaconda Prompt.

Below reports show details of my software and failure report.

![image](https://user-images.githubusercontent.com/13442202/82838698-e9b5b600-9ec4-11ea-9621-c4cbbd40d3a8.png)

![image](https://user-images.githubusercontent.com/13442202/82838647-c3901600-9ec4-11ea-99b4-34e093dbae2f.png)

![image](https://user-images.githubusercontent.com/13442202/82838655-c7bc3380-9ec4-11ea-9f68-433a505a8401.png)

**Comment by hcho3** [comment]
You should be able to install pre-built XGBoost from PyPI, by running:
```
python -m pip install xgboost
```

It supports GPU out of the box.

**Comment by raphay3l** [comment]
Oh. Thanks! Silly me. XGBOOST crew need to make it more obvious in the documentation section. Issue resolved.
