### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by alanpurple** [dmlc/xgboost#5708]
Thanks for participating in the XGBoost community! We use https://discuss.xgboost.ai for any general usage questions and discussions. The issue tracker is used for actionable items such as feature proposals discussion, roadmaps, and bug tracking.  You are always welcomed to post on the forum first :)

Issues that are inactive for a period of time may get closed. We adopt this policy so that we won't lose track of actionable issues that may fall at the bottom of the pile. Feel free to reopen a new one if you feel there is an additional problem that needs attention when an old one gets closed.

For bug reports, to help the developer act on the issues, please include a description of your environment, preferably a minimum script to reproduce the problem.

For feature proposals, list clear, small actionable items so we can track the progress of the change.

branch: master
os: Ubuntu 18.04.4 x64
cuda: 10.2
nccl: 2.6.4
python: 3.8.2 x64
make: GNU Make 4.1 x64
cmake: 3.17.2

```
/repo/xgboost/src/tree/gpu_hist/evaluate_splits.cu(231): error: no instance of function template "cub::DeviceSegmentedReduce::Sum" matches the argument list
            argument types are: (std::nullptr_t, size_t, thrust::device_ptr<xgboost::tree::DeviceSplitCandidate>, xgboost::tree::DeviceSplitCandidate *, int, thrust::transform_iterator<lambda [](size_t)->size_t, thrust::counting_iterator<unsigned long long, thrust::use_default, thrust::use_default, thrust::use_default>, size_t, thrust::use_default>, thrust::transform_iterator<lambda [](size_t)->size_t, thrust::counting_iterator<unsigned long long, thrust::use_default, thrust::use_default, thrust::use_default>, size_t, thrust::use_default>)
          detected during instantiation of "void xgboost::tree::EvaluateSplits(xgboost::common::Span<xgboost::tree::DeviceSplitCandidate, 18446744073709551615UL>, xgboost::tree::EvaluateSplitInputs<GradientSumT>, xgboost::tree::EvaluateSplitInputs<GradientSumT>) [with GradientSumT=xgboost::GradientPair]" 
(246): here
```

**Comment by hcho3** [comment]
Please provide more details, e.g. OS, compiler you are using.

**Comment by alanpurple** [comment]
@hcho3 
updated

**Comment by hcho3** [comment]
Try running `git submodule update --init --recursive`.

**Comment by alanpurple** [comment]
@hcho3 
build succeeded with latest master
