### ISSUE TITLE
Discrepancy in predicted probability using caret xgboost model and xgboost native model.

### ISSUE THREAD

**Issue by sandeshregmi** [dmlc/xgboost#5721]
I used exact same prameters and training dataset to build two classification models:
1. caret's xgbDART
2. xgboost with dart booster
After I scored the new data, the predicted probabilties are very different from two models.
Since caret is just a wrapper my understanding is it uses the same xgboost model. I am not understanding why the outputs are so different. Am I missing something?
Any insight would be appreciated.
Thanks

**Comment by trivialfis** [comment]
I'm not familiar with

**Comment by sandeshregmi** [comment]
Thank you. xgboost version that I have been using is 0.90.0.2

**Comment by trivialfis** [comment]
Could you upgrade to1.1?

**Comment by sandeshregmi** [comment]
just did it to xgboost_1.0.0.2
re-ran the model. still newly scored output is very different compared to caret xgbDART generated. Please let me know if providing my set up helps better.

**Comment by hcho3** [comment]
Can you post your script?

**Comment by hcho3** [comment]
Closing this for now. Feel free to open another issue if you have an example you can share.
