### ISSUE TITLE
 Error when cross compiling, I am trying to compile usable libxgboost.so for a7 single board

### ISSUE THREAD

**Issue by hawkmi** [dmlc/xgboost#5726]
**here is the complier**
```
set(CMAKE_C_COMPILER arm-openstlinux_weston-linux-gnueabi-gcc CACHE PATH "gcc compiler")

set(CMAKE_CXX_COMPILER arm-openstlinux_weston-linux-gnueabi-g++ CACHE PATH "g++ compiler")

set(CMAKE_C_FLAGS "-fstack-protector-all -Werror -Wall -g -fPIC -ffunction-sections -fdata-sections -march=armv7ve -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mcpu=cortex-a7 --sysroot=/opt/st/SDK/sysroots/cortexa7t2hf-neon-vfpv4-openstlinux_weston-linux-gnueabi")

set(CMAKE_CXX_FLAGS "-fstack-protector-all -Werror -Wall -g -fPIC -ffunction-sections -fdata-sections -march=armv7ve -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mcpu=cortex-a7 --sysroot=/opt/st/SDK/sysroots/cortexa7t2hf-neon-vfpv4-openstlinux_weston-linux-gnueabi")
```
**and this is the  infomation when i run cmake ..** 

-- The CXX compiler identification is GNU 8.2.0
-- The C compiler identification is GNU 8.2.0
-- Check for working CXX compiler: /opt/st/SDK/sysroots/x86_64-openstlinux_weston_sdk-linux/usr/bin/arm-openstlinux_weston-linux-gnueabi/arm-openstlinux_weston-linux-gnueabi-g++
-- Check for working CXX compiler: /opt/st/SDK/sysroots/x86_64-openstlinux_weston_sdk-linux/usr/bin/arm-openstlinux_weston-linux-gnueabi/arm-openstlinux_weston-linux-gnueabi-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /opt/st/SDK/sysroots/x86_64-openstlinux_weston_sdk-linux/usr/bin/arm-openstlinux_weston-linux-gnueabi/arm-openstlinux_weston-linux-gnueabi-gcc
-- Check for working C compiler: /opt/st/SDK/sysroots/x86_64-openstlinux_weston_sdk-linux/usr/bin/arm-openstlinux_weston-linux-gnueabi/arm-openstlinux_weston-linux-gnueabi-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- CMake version 3.14.4
-- Performing Test XGBOOST_MM_PREFETCH_PRESENT
-- Performing Test XGBOOST_MM_PREFETCH_PRESENT - Failed
-- Performing Test XGBOOST_BUILTIN_PREFETCH_PRESENT
-- Performing Test XGBOOST_BUILTIN_PREFETCH_PRESENT - Success
-- xgboost VERSION: 1.1.0
-- Setting build type to 'Release' as none was specified.
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - found
-- Looking for fopen64
-- Looking for fopen64 - not found
-- Looking for C++ include cxxabi.h
-- Looking for C++ include cxxabi.h - found
-- Looking for nanosleep
-- Looking for nanosleep - found
-- Looking for backtrace
-- Looking for backtrace - found
-- backtrace facility detected in default set of libraries
-- Found Backtrace: /opt/st/SDK/sysroots/x86_64-openstlinux_weston_sdk-linux/usr/include
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- /home/myusername/code/xgboost/dmlc-core/cmake/build_config.h.in -> include/dmlc/build_config.h
-- Performing Test SUPPORT_MSSE2
-- Performing Test SUPPORT_MSSE2 - Failed
DMLC_ROOT point to /home/myusername/code/xgboost/rabit/../dmlc-core
-- Configuring done
-- Generating done

**Below is the error message after i run make** 

[  1%] Building CXX object dmlc-core/CMakeFiles/dmlc.dir/src/config.cc.o
In file included from /opt/st/SDK/sysroots/x86_64-openstlinux_weston_sdk-linux/usr/include/wchar.h:30,
                 from /opt/st/SDK/sysroots/cortexa7t2hf-neon-vfpv4-openstlinux_weston-linux-gnueabi/usr/include/c++/8.2.0/cwchar:44,
                 from /opt/st/SDK/sysroots/cortexa7t2hf-neon-vfpv4-openstlinux_weston-linux-gnueabi/usr/include/c++/8.2.0/bits/postypes.h:40,
                 from /opt/st/SDK/sysroots/cortexa7t2hf-neon-vfpv4-openstlinux_weston-linux-gnueabi/usr/include/c++/8.2.0/iosfwd:40,
                 from /opt/st/SDK/sysroots/cortexa7t2hf-neon-vfpv4-openstlinux_weston-linux-gnueabi/usr/include/c++/8.2.0/ios:38,
                 from /opt/st/SDK/sysroots/cortexa7t2hf-neon-vfpv4-openstlinux_weston-linux-gnueabi/usr/include/c++/8.2.0/istream:38,
                 from /opt/st/SDK/sysroots/cortexa7t2hf-neon-vfpv4-openstlinux_weston-linux-gnueabi/usr/include/c++/8.2.0/sstream:38,
                 from /home/myusername/code/xgboost/dmlc-core/src/config.cc:4:
/opt/st/SDK/sysroots/x86_64-openstlinux_weston_sdk-linux/usr/include/bits/floatn.h:74:70: error: unknown machine mode ‘__TC__’
 typedef _Complex float __cfloat128 __attribute__ ((__mode__ (__TC__)));
                                                                      ^
/opt/st/SDK/sysroots/x86_64-openstlinux_weston_sdk-linux/usr/include/bits/floatn.h:86:9: error: ‘__float128’ does not name a type; did you mean ‘__cfloat128’?
 typedef __float128 _Float128;
         ^~~~~~~~~~
         __cfloat128
In file included from /opt/st/SDK/sysroots/cortexa7t2hf-neon-vfpv4-openstlinux_weston-linux-gnueabi/usr/include/c++/8.2.0/cwchar:44,
                 from /opt/st/SDK/sysroots/cortexa7t2hf-neon-vfpv4-openstlinux_weston-linux-gnueabi/usr/include/c++/8.2.0/bits/postypes.h:40,
                 from /opt/st/SDK/sysroots/cortexa7t2hf-neon-vfpv4-openstlinux_weston-linux-gnueabi/usr/include/c++/8.2.0/iosfwd:40,
                 from /opt/st/SDK/sysroots/cortexa7t2hf-neon-vfpv4-openstlinux_weston-linux-gnueabi/usr/include/c++/8.2.0/ios:38,
                 from /opt/st/SDK/sysroots/cortexa7t2hf-neon-vfpv4-openstlinux_weston-linux-gnueabi/usr/include/c++/8.2.0/istream:38,
                 from /opt/st/SDK/sysroots/cortexa7t2hf-neon-vfpv4-openstlinux_weston-linux-gnueabi/usr/include/c++/8.2.0/sstream:38,
                 from /home/myusername/code/xgboost/dmlc-core/src/config.cc:4:
/opt/st/SDK/sysroots/x86_64-openstlinux_weston_sdk-linux/usr/include/wchar.h:406:8: error: ‘_Float128’ does not name a type; did you mean ‘_Float32x’?
 extern _Float128 wcstof128 (const wchar_t *__restrict __nptr,
        ^~~~~~~~~
        _Float32x
/opt/st/SDK/sysroots/x86_64-openstlinux_weston_sdk-linux/usr/include/wchar.h:523:8: error: ‘_Float128’ does not name a type; did you mean ‘_Float32x’?
 extern _Float128 wcstof128_l (const wchar_t *__restrict __nptr,
        ^~~~~~~~~
        _Float32x
In file included from /opt/st/SDK/sysroots/cortexa7t2hf-neon-vfpv4-openstlinux_weston-linux-gnueabi/usr/include/c++/8.2.0/cstdlib:75,
                 from /opt/st/SDK/sysroots/cortexa7t2hf-neon-vfpv4-openstlinux_weston-linux-gnueabi/usr/include/c++/8.2.0/ext/string_conversions.h:41,
                 from /opt/st/SDK/sysroots/cortexa7t2hf-neon-vfpv4-openstlinux_weston-linux-gnueabi/usr/include/c++/8.2.0/bits/basic_string.h:6391,
                 from /opt/st/SDK/sysroots/cortexa7t2hf-neon-vfpv4-openstlinux_weston-linux-gnueabi/usr/include/c++/8.2.0/string:52,
                 from /opt/st/SDK/sysroots/cortexa7t2hf-neon-vfpv4-openstlinux_weston-linux-gnueabi/usr/include/c++/8.2.0/bits/locale_classes.h:40,
                 from /opt/st/SDK/sysroots/cortexa7t2hf-neon-vfpv4-openstlinux_weston-linux-gnueabi/usr/include/c++/8.2.0/bits/ios_base.h:41,
                 from /opt/st/SDK/sysroots/cortexa7t2hf-neon-vfpv4-openstlinux_weston-linux-gnueabi/usr/include/c++/8.2.0/ios:42,
                 from /opt/st/SDK/sysroots/cortexa7t2hf-neon-vfpv4-openstlinux_weston-linux-gnueabi/usr/include/c++/8.2.0/istream:38,
                 from /opt/st/SDK/sysroots/cortexa7t2hf-neon-vfpv4-openstlinux_weston-linux-gnueabi/usr/include/c++/8.2.0/sstream:38,
                 from /home/myusename/code/xgboost/dmlc-core/src/config.cc:4:
/opt/st/SDK/sysroots/cortexa7t2hf-neon-vfpv4-openstlinux_weston-linux-gnueabi/usr/include/stdlib.h:152:8: error: ‘_Float128’ does not name a type; did you mean ‘_Float32x’?
 extern _Float128 strtof128 (const char *__restrict __nptr,
        ^~~~~~~~~
        _Float32x
/opt/st/SDK/sysroots/cortexa7t2hf-neon-vfpv4-openstlinux_weston-linux-gnueabi/usr/include/stdlib.h:245:4: error: ‘_Float128’ has not been declared
    _Float128 __f)
    ^~~~~~~~~
/opt/st/SDK/sysroots/cortexa7t2hf-neon-vfpv4-openstlinux_weston-linux-gnueabi/usr/include/stdlib.h:330:8: error: ‘_Float128’ does not name a type; did you mean ‘_Float32x’?
 extern _Float128 strtof128_l (const char *__restrict __nptr,
        ^~~~~~~~~
        _Float32x
dmlc-core/CMakeFiles/dmlc.dir/build.make:62: recipe for target 'dmlc-core/CMakeFiles/dmlc.dir/src/config.cc.o' failed
make[2]: *** [dmlc-core/CMakeFiles/dmlc.dir/src/config.cc.o] Error 1
CMakeFiles/Makefile2:202: recipe for target 'dmlc-core/CMakeFiles/dmlc.dir/all' failed
make[1]: *** [dmlc-core/CMakeFiles/dmlc.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

THANK YOU !

**Comment by hcho3** [comment]
@hawkmi I don't think the error has anything to do with XGBoost. The error is coming from the include `#include <sstream>`. Can you check if you can cross-compile this application:
```cpp
#include <sstream>
#include <iostream>

int main() {
    std::ostringstream oss;
    oss << "Hello" << " " << "world";
    std::cout << oss.str() << std::endl;
    return 0;
}
```

**Comment by lzx20172016** [comment]
you mix use two kinds of c++ libs,they are /opt/st/SDK/sysroots/x86_64-openstlinux_weston_sdk-linux and /opt/st/SDK/sysroots/cortexa7t2hf-neon-vfpv4-openstlinux_weston-linux-gnueabi, you should use one of them.
