### ISSUE TITLE
nthreads not working in R on linux

### ISSUE THREAD

**Issue by oude-gao** [dmlc/xgboost#5736]
Hi, seems like nthreads is not working in the R package for parallel processing on a linux server -- the CPU is always capped at 100%:

sessioninfo():
R version 4.0.0 (2020-04-24)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.6 LTS

Matrix products: default
BLAS:   /usr/lib/atlas-base/atlas/libblas.so.3.0
LAPACK: /usr/lib/atlas-base/atlas/liblapack.so.3.0

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8        LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8   
 [6] LC_MESSAGES=C.UTF-8    LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C           LC_TELEPHONE=C        
[11] LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] xgboost_1.0.0.2

script:
xgb.fit=xgb.train(
  params=params,
  data=xgb.train,
  nrounds=10000,
  nthreads=1,
  early_stopping_rounds=10,
  watchlist=list(val1=xgb.train,val2=xgb.test),
  verbose=0
)

Any thoughts why this happened? I saw a bunch of old issues similar to this opened and closed but none of them actually got quite a good answer.

**Comment by hcho3** [comment]
I think it's because of `nthreads=1` in your script. Try changing this value to a bigger number.

**Comment by trivialfis** [comment]
- There's no `nthreads`, instead it's `nthread`.
- Put it in `params` instead of an argument for `train`.  In 1.1 release, there's parameter validation for R package.  @hcho3 Is there any difficulty on submitting it?

**Comment by hcho3** [comment]
@trivialfis: @hetong007 is working on it.

**Comment by trivialfis** [comment]
Got it, thanks.  Please let me know if there's anything I can help.
