### ISSUE TITLE
Big model size with training continuation

### ISSUE THREAD

**Issue by HughhguH** [dmlc/xgboost#5751]
I am using XGBoost 1.1.0 and I want to apply a XGBoostRegressor on a large dataset.

1. If I train all data in once:

```
xgb_full = xgb.train(hyperparameters,
                     dtrain,
                     num_boost_round=1000,
                     evals=[(dtrain, 'train')],
                     verbose_eval=True)

model=xgb_full.save_model('model_1.model')	
```			

	 

In this case the size of model is 38 MB and I can use this it easily to predict new data.

2. If I split the same data into 100 parts and use xgb_model parameters to train continuously:

```
batch_size = 50
start = 50
xgb_partial = None
for i in range(100):
    xgb_partial = xgb.train(hyperparameters,
                            dtrain[i*start:i*start+batch_size],
                            num_boost_round=1000,
                            evals=[(dtrain[start:start+batch_size], 'train')],
                            verbose_eval=True,
                            xgb_model=xgb_partial)	
			
    model=xgb_partial.save_model('model_1.model')	

```

In this case, the saving model size at each iteration increase and at the end the size is 1,214,000 MB in my case. 

Is it normal or something is not setup properly? Is it a manageable way to regularly update the same model with new data without having a huge size of the model at the end of the training period?

**Comment by hcho3** [comment]
The model size increases because you are adding 1000 trees in each step, leading to 100000 trees. "Training continuation" means that you are adding additional trees on top of the trees already fit.

> a manageable way to regularly update the same model with new data ...

I'm afraid this is not what's happening.
