### ISSUE TITLE
Clang Linker failed when building on Mac in Clion

### ISSUE THREAD

**Issue by Dlng** [dmlc/xgboost#577]
Hi guys,

Below is an error I got when trying to CMAKE on Mac OS 10.10 in Clion IDE. Prior to this I got error of _error: non-type template argument evaluates to 4294945538, which cannot be narrowed to type 'int' [-Wc++11-narrowing]
class DMatrixPage : public DMatrixPageBase<0xffffab02> _, which is fixed by using -Wno-c++11-narrowing option. Any help would be appreciated!

/Applications/CLion.app/Contents/bin/cmake/bin/cmake --build /Users/Weilong/Library/Caches/clion10/cmake/generated/8722b792/8722b792/Debug --target src -- -j 4
[ 20%] [ 40%] [ 60%] [ 80%] Building CXX object CMakeFiles/src.dir/io/dmlc_simple.cpp.o
Building CXX object CMakeFiles/src.dir/io/io.cpp.o
Building CXX object CMakeFiles/src.dir/gbm/gbm.cpp.o
Building CXX object CMakeFiles/src.dir/tree/updater.cpp.o
In file included from /Users/Weilong/Codes/xgboost/src/gbm/gbm.cpp:7:
In file included from /Users/Weilong/Codes/xgboost/src/gbm/./gbtree-inl.hpp:15:
/Users/Weilong/Codes/xgboost/src/gbm/../utils/omp.h:15:9: warning: Warning: OpenMP is not available,xgboost will be compiled into single-thread code.Use OpenMP-enabled compiler to get benefit of multi-threading [-W#pragma-messages]
#pragma message("Warning: OpenMP is not available,"\
        ^
In file included from /Users/Weilong/Codes/xgboost/src/io/io.cpp:9:
In file included from /Users/Weilong/Codes/xgboost/src/io/simple_dmatrix-inl.hpp:22:
In file included from /Users/Weilong/Codes/xgboost/src/io/./simple_fmatrix-inl.hpp:16:
/Users/Weilong/Codes/xgboost/src/io/../utils/omp.h:15:9: warning: Warning: OpenMP is not available,xgboost will be compiled into single-thread code.Use OpenMP-enabled compiler to get benefit of multi-threading [-W#pragma-messages]
#pragma message("Warning: OpenMP is not available,"\
        ^
[100%] Building CXX object CMakeFiles/src.dir/xgboost_main.cpp.o
In file included from /Users/Weilong/Codes/xgboost/src/tree/updater.cpp:8:
In file included from /Users/Weilong/Codes/xgboost/src/tree/./updater_refresh-inl.hpp:15:
/Users/Weilong/Codes/xgboost/src/tree/../utils/omp.h:15:9: warning: Warning: OpenMP is not available,xgboost will be compiled into single-thread code.Use OpenMP-enabled compiler to get benefit of multi-threading [-W#pragma-messages]
#pragma message("Warning: OpenMP is not available,"\
        ^
In file included from /Users/Weilong/Codes/xgboost/src/xgboost_main.cpp:13:
In file included from /Users/Weilong/Codes/xgboost/src/./learner/learner-inl.hpp:17:
In file included from /Users/Weilong/Codes/xgboost/src/./io/../learner/./objective.h:67:
In file included from /Users/Weilong/Codes/xgboost/src/./io/../learner/objective-inl.hpp:19:
/Users/Weilong/Codes/xgboost/src/./io/../learner/../utils/omp.h:15:9: warning: Warning: OpenMP is not available,xgboost will be compiled into single-thread code.Use OpenMP-enabled compiler to get benefit of multi-threading [-W#pragma-messages]
#pragma message("Warning: OpenMP is not available,"\
        ^
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
Linking CXX executable src
Undefined symbols for architecture x86_64:
  "rabit::engine::Allreduce_(void*, unsigned long, unsigned long, void (*)(void const*, void*, int, MPI::Datatype const&), rabit::engine::mpi::DataType, rabit::engine::mpi::OpType, void (*)(void*), void*)", referenced from:
      void rabit::Allreduce<rabit::op::BitOR, unsigned int>(unsigned int*, unsigned long, void (*)(void*), void*) in updater.cpp.o
      void rabit::Allreduce<rabit::op::Max, float>(float*, unsigned long, void (*)(void*), void*) in updater.cpp.o
      void rabit::Allreduce<rabit::op::Sum, float>(float*, unsigned long, void (*)(void*), void*) in xgboost_main.cpp.o
      void rabit::Allreduce<rabit::op::Max, unsigned int>(unsigned int*, unsigned long, void (*)(void*), void*) in xgboost_main.cpp.o
  "rabit::engine::ReduceHandle::Init(void (*)(void const*, void*, int, MPI::Datatype const&), unsigned long)", referenced from:
      rabit::Reducer<xgboost::tree::SplitEntry, &(xgboost::tree::SplitEntry::Reduce(xgboost::tree::SplitEntry&, xgboost::tree::SplitEntry const&))>::Reducer() in updater.cpp.o
      rabit::SerializeReducer<xgboost::utils::QuantileSketchTemplate<float, float, xgboost::utils::WXQSummary<float, float> >::SummaryContainer>::SerializeReducer() in updater.cpp.o
      rabit::Reducer<xgboost::tree::SketchMaker::SKStats, &(xgboost::tree::SketchMaker::SKStats::Reduce(xgboost::tree::SketchMaker::SKStats&, xgboost::tree::SketchMaker::SKStats const&))>::Reducer() in updater.cpp.o
      rabit::Reducer<xgboost::tree::GradStats, &(xgboost::tree::GradStats::Reduce(xgboost::tree::GradStats&, xgboost::tree::GradStats const&))>::Reducer() in updater.cpp.o
  "rabit::engine::ReduceHandle::TypeSize(MPI::Datatype const&)", referenced from:
      void rabit::SerializeReducerFunc_<xgboost::utils::QuantileSketchTemplate<float, float, xgboost::utils::WXQSummary<float, float> >::SummaryContainer>(void const*, void*, int, MPI::Datatype const&) in updater.cpp.o
  "rabit::engine::ReduceHandle::Allreduce(void*, unsigned long, unsigned long, void (*)(void*), void*)", referenced from:
      rabit::Reducer<xgboost::tree::SplitEntry, &(xgboost::tree::SplitEntry::Reduce(xgboost::tree::SplitEntry&, xgboost::tree::SplitEntry const&))>::Allreduce(xgboost::tree::SplitEntry*, unsigned long, void (*)(void*), void*) in updater.cpp.o
      rabit::Reducer<xgboost::tree::SketchMaker::SKStats, &(xgboost::tree::SketchMaker::SKStats::Reduce(xgboost::tree::SketchMaker::SKStats&, xgboost::tree::SketchMaker::SKStats const&))>::Allreduce(xgboost::tree::SketchMaker::SKStats*, unsigned long, void (*)(void*), void*) in updater.cpp.o
      rabit::SerializeReducer<xgboost::utils::QuantileSketchTemplate<float, float, xgboost::utils::WXQSummary<float, float> >::SummaryContainer>::Allreduce(xgboost::utils::QuantileSketchTemplate<float, float, xgboost::utils::WXQSummary<float, float> >::SummaryContainer*, unsigned long, unsigned long, void (*)(void*), void*) in updater.cpp.o
      rabit::Reducer<xgboost::tree::GradStats, &(xgboost::tree::GradStats::Reduce(xgboost::tree::GradStats&, xgboost::tree::GradStats const&))>::Allreduce(xgboost::tree::GradStats*, unsigned long, void (*)(void*), void*) in updater.cpp.o
  "rabit::engine::ReduceHandle::ReduceHandle()", referenced from:
      rabit::Reducer<xgboost::tree::SplitEntry, &(xgboost::tree::SplitEntry::Reduce(xgboost::tree::SplitEntry&, xgboost::tree::SplitEntry const&))>::Reducer() in updater.cpp.o
      rabit::SerializeReducer<xgboost::utils::QuantileSketchTemplate<float, float, xgboost::utils::WXQSummary<float, float> >::SummaryContainer>::SerializeReducer() in updater.cpp.o
      rabit::Reducer<xgboost::tree::SketchMaker::SKStats, &(xgboost::tree::SketchMaker::SKStats::Reduce(xgboost::tree::SketchMaker::SKStats&, xgboost::tree::SketchMaker::SKStats const&))>::Reducer() in updater.cpp.o
      rabit::Reducer<xgboost::tree::GradStats, &(xgboost::tree::GradStats::Reduce(xgboost::tree::GradStats&, xgboost::tree::GradStats const&))>::Reducer() in updater.cpp.o
  "rabit::engine::ReduceHandle::~ReduceHandle()", referenced from:
      rabit::Reducer<xgboost::tree::SplitEntry, &(xgboost::tree::SplitEntry::Reduce(xgboost::tree::SplitEntry&, xgboost::tree::SplitEntry const&))>::~Reducer() in updater.cpp.o
      rabit::Reducer<xgboost::tree::SplitEntry, &(xgboost::tree::SplitEntry::Reduce(xgboost::tree::SplitEntry&, xgboost::tree::SplitEntry const&))>::Reducer() in updater.cpp.o
      rabit::SerializeReducer<xgboost::utils::QuantileSketchTemplate<float, float, xgboost::utils::WXQSummary<float, float> >::SummaryContainer>::~SerializeReducer() in updater.cpp.o
      rabit::Reducer<xgboost::tree::SketchMaker::SKStats, &(xgboost::tree::SketchMaker::SKStats::Reduce(xgboost::tree::SketchMaker::SKStats&, xgboost::tree::SketchMaker::SKStats const&))>::~Reducer() in updater.cpp.o
      rabit::SerializeReducer<xgboost::utils::QuantileSketchTemplate<float, float, xgboost::utils::WXQSummary<float, float> >::SummaryContainer>::SerializeReducer() in updater.cpp.o
      rabit::Reducer<xgboost::tree::SketchMaker::SKStats, &(xgboost::tree::SketchMaker::SKStats::Reduce(xgboost::tree::SketchMaker::SKStats&, xgboost::tree::SketchMaker::SKStats const&))>::Reducer() in updater.cpp.o
      rabit::Reducer<xgboost::tree::GradStats, &(xgboost::tree::GradStats::Reduce(xgboost::tree::GradStats&, xgboost::tree::GradStats const&))>::~Reducer() in updater.cpp.o
      ...
  "rabit::engine::Init(int, char**)", referenced from:
      rabit::Init(int, char**) in xgboost_main.cpp.o
  "rabit::engine::Finalize()", referenced from:
      rabit::Finalize() in xgboost_main.cpp.o
  "rabit::engine::GetEngine()", referenced from:
      rabit::GetRank() in io.cpp.o
      rabit::GetWorldSize() in io.cpp.o
      rabit::GetWorldSize() in updater.cpp.o
      rabit::GetRank() in updater.cpp.o
      rabit::Broadcast(void*, unsigned long, int) in updater.cpp.o
      rabit::TrackerPrint(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in updater.cpp.o
      rabit::IsDistributed() in xgboost_main.cpp.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [src] Error 1
make[2]: *** [CMakeFiles/src.dir/all] Error 2
make[1]: *** [CMakeFiles/src.dir/rule] Error 2
make: *** [src] Error 2

**Comment by phunterlau** [comment]
looks like your clang doesn't support openMP (no, mac clang doesn't support it). So, you might want to turn on no_omp=1 for cmake as in the build.sh using make.

**Comment by Dlng** [comment]
Thanks for your help @phunterlau! That solves the above problem, however, another has emerged, which I couldn't find the answer to on google. ## "/Users/Weilong/Codes/xgboost/subtree/rabit/src/engine_mpi.cc:12:10: fatal error: 'mpi.h' file not found
#include <mpi.h>"

**Comment by phunterlau** [comment]
@Dlng xgboost doesn't have an official `CMakeLists.txt` for supporting cmake as I remember, so I am afraid there are some deeper problems of using it, for example, including mpi location. Do we have any future plans of supporting cmake?
