### ISSUE TITLE
[Experience] Training exactly the same model run to run on Spark

### ISSUE THREAD

**Issue by FelixYBW** [dmlc/xgboost#5775]
Xgboost on Spark actually generates different model run to run, which means if we predict the same dataset, two models from two run with exactly the same parameter and training dataset may give different prediction result. The AUC is slightly different as well.

But it's a big problem for performance optimization because the variances leads to big elapsed time difference. We can hardly know if an optimization can gain performance and how much.

There are 5 reasons for this:
- Spark may split different partitions and RDD order is random
- The partitions are scheduled to different Ranks
- Partitions are assigned to different Rank id
- allreduce_tree is built by different Rank id seq
- Reducer may reduce variable data size each time

So if one would like to generate exact the same model run to run on Spark, Here is how (.diff isn't support, I have to attach png file)

- Add two columns: partid and seqnum. Then use 
     partitionbyrange(N,"partid")     #partition number is the same as partid
     sortWithinPartitions('seqnum')
![image](https://user-images.githubusercontent.com/47296334/84245296-b0329c80-aab9-11ea-8cf5-44ced58095ae.png)

- In datautil.scala, use NodeAffinityRDD to set prefered location for partid. 
      
![image](https://user-images.githubusercontent.com/47296334/84245476-f25bde00-aab9-11ea-8567-e1e661291a2c.png)
![image](https://user-images.githubusercontent.com/47296334/84245629-318a2f00-aaba-11ea-956c-72df214959e7.png)
https://github.com/FelixYBW/xgboost/blob/6a409a1da0263e2b58f439d7e18f25fbca86c280/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/DataUtils.scala#L36

- Assign rankid = task id = partid in dmlc-core/dmlc_tracker/tracker.py
![image](https://user-images.githubusercontent.com/47296334/84246006-ce4ccc80-aaba-11ea-9e77-be894e890145.png)

- Sort Partid before allreduce_tree construction in rabit/src/allreduce_base.cc:AllreduceBase::ReConnectLinks
![image](https://user-images.githubusercontent.com/47296334/84246292-4a471480-aabb-11ea-903c-7170e5fb941f.png)
https://github.com/FelixYBW/rabit/blob/e4546c5081b69fec3f79529d38967b0657f5c210/src/allreduce_base.cc#L474

- Set minimal size of reducer
      https://github.com/dmlc/rabit/pull/139

However, performance variance isn't only from the model's difference. the issued solved by Rabit PR139 is another big reason.

After the two fix, we can get very little run2run variance.

**Comment by hcho3** [comment]
@FelixYBW I thought https://github.com/dmlc/xgboost/pull/4807 would enable deterministic partitioning?

**Comment by FelixYBW** [comment]
@hcho3 deterministic data partitioning fixed the partitions. It has the same function as df.partitionbyrange(N,"partid"). But the rdd row order may still be different.
We also need the other steps to get fixed model.

**Comment by stupidoge** [comment]
Hi @FelixYBW this issue affects not only for spark xgboost, but also any other ML models. Would you mind telling me whether there is a better way to fix model and its output currently? Thanks a lot!
