### ISSUE TITLE
[R] Add more {lintr} linters and run them in CI

### ISSUE THREAD

**Issue by jameslamb** [dmlc/xgboost#5779]
Opening this issue from the discussion in #5778 , specifically https://github.com/dmlc/xgboost/pull/5778#issuecomment-642374166.

As of this writing there is some `{lintr}`  code for linting the R package, but it is disabled https://github.com/dmlc/xgboost/blob/1d22a9be1cdeb53dfa9322c92541bc50e82f3c43/R-package/tests/testthat/test_lint.R#L26.

## How to close this issue

1.  Enable linting in `R-package/tests/testthat/test_lint.R` (or propose an alternative way to run linting checks, such as https://github.com/microsoft/LightGBM/blob/4d43e96bbc10de2937aa70a5829977d46bdb1852/.ci/test.sh#L57
2. Propose additional linters to be added. The list of available linters can be found [here](https://github.com/jimhester/lintr/tree/38279839efe0f685b281e80a77bcea1b04665f33#available-linters)

**Comment by hcho3** [comment]
Consolidating to #5796
