### ISSUE TITLE
fatal error during installation C1189 CUDA Toolkit v11.0

### ISSUE THREAD

**Issue by adwiputra** [dmlc/xgboost#5791]
Hi,

I tried installing the GPU-supported xgboost for R on my Windows 10 with CUDA Toolkit v11.0 + Visual Studio 2019 and got the error message during the installation:
" The version of CUB in your include path is not compatible with this release of Thrust. CUB is now included in
the CUDA Toolkit, so you no longer need to use your own checkout of CUB. Define THRUST_IGNORE_CUB_VERSION_CHECK to ignore this."

It makes me wonder if the current version support the CUDA Toolkit v11.0?

Thanks!

**Comment by hcho3** [comment]
No, XGBoost does not yet support CUDA 11 yet.
