### ISSUE TITLE
Different results for some inputs with saved model on Python vs C++

### ISSUE THREAD

**Issue by nickion** [dmlc/xgboost#5792]
Models created using XGBClassifer() and XGBRFClassifier() with more than a few estimators produce different results for _some_ inputs with Python vs C++. The chance of a different output may depend on the number of estimators. 

For example, with the following model. 

[xgb.model.json.gz](https://github.com/dmlc/xgboost/files/4776292/xgb.model.json.gz)

Python produces `[[0.3540964 0.6459036]]`

```python
model = xgb.XGBClassifier();
model.load_model("xgb.model.json")
row = [[0, 0.227273, 0.304373, 0.179487, 0.249837, 1, 0.0110693,
           0.147591, 0.156816, 0.0793302, 0.177073, 0.142028,
           0.108826, 0.197505, 0.0996755, 0.123671, 0, 0, 0, 0, 0]]
p = model.predict_proba(np.array(row))
print(p)
```

C++ with the same input produces `0.47586`

```c++
#include <iostream>
#include <xgboost/base.h>
#include <xgboost/c_api.h>

int main()
{
    DMatrixHandle dtest;
    BoosterHandle booster;

    xgboost::bst_float x[] =
        {
            0, 0.227273, 0.304373, 0.179487, 0.249837, 1, 0.0110693,
            0.147591, 0.156816, 0.0793302, 0.177073, 0.142028,
            0.108826, 0.197505, 0.0996755, 0.123671, 0, 0, 0, 0, 0
        };

    XGDMatrixCreateFromMat(x, 1, 21, 0, &dtest);

    XGBoosterCreate(0, 0, &booster);

    XGBoosterLoadModel(booster, "../tf/xgb.model.json");

    bst_ulong out_len = 0;
    const float *out_result = 0;

    XGBoosterPredict(booster, dtest, 0, 0, -1, &out_len, &out_result);

    std::cout << out_result[0] << std::endl;

    XGBoosterFree(booster);
    XGDMatrixFree(dtest);

    return 0;
}
```

In contrast, the following input for the model produces the same result for Python and C++:
```
0.0666667, 0.21227, 0.468716, 0.0133111, 0.698243, 1, 0.373252, 
0.43238, 0.899869, 0.761285, 0.296261, 0.539158, 0.618284, 0.436141,
0.837168, 0.776182, 0, 0, 0, 0, 0
```
`[[0.462474 0.537526]]` and `0.537526`

Model creation was done as:
```
model = xgb.XGBClassifier(n_estimators=5, scale_pos_weight=7,
tree_method='hist',
objective="binary:logistic", 
subsample=0.4,
booster="gbtree")
```

Wondering if there's a precision related issue causing different tree paths to be selected in some cases or perhaps I've not configured the model correctly in C++?

**Comment by nickion** [comment]
Apologies, I have just realised that this is my error by having zero for the indicator of a missing value in the input matrix rather than a value that will not occur in the dataset. This affected the first example with the first value being zero but not the others. The trailing zeros in both examples did not cause an issue as these are constant value dummy features that will have been learnt as having no significance.

**Comment by rudyyin** [comment]
I also came across this problem. and I find the demo( https://github.com/dmlc/xgboost/blob/master/demo/c-api/basic/c-api-demo.c ) is not very good because it pass 0.0 to XGDMatrixCreateFromMat as the missing arg. This could miss lead many people because 0.0 is commonly used and many person including me will mistakenly regard this  arg  as “if something is missing, use this arg as default”.  so for this demo, it is better use NaN as miss arg.
