### ISSUE TITLE
guide loss and gamma parameter not consistent when using GPU or not

### ISSUE THREAD

**Issue by xtimbeau** [dmlc/xgboost#5798]
Hi, 
when comparing results between GPU and non GPU boosting, I think there is a problem.
When using lossguide, maxdepth=0 and a gamma (min_split_loss) parameter, it yield a different result for GPU and non GPU relsult. The issue seems to be related to updater_gpu_hist.cu where it seems that's where the gamma (min_split_loss) is used to evaluate the split_loss but only when GPU is used.
As it requires some time, I can provide a reproductible example on request.
XT

**Comment by trivialfis** [comment]
The GPU implementation uses pre-pruning while CPU uses post-pruning, but discrepancy is unexpected.  Let me take a look later.

> When using lossguide, maxdepth=0 and a gamma (min_split_loss) parameter,

There's no `maxdepth`, but `max_depth`.
