### ISSUE TITLE
NCCL_LIBRARY can't be set by user during build

### ISSUE THREAD

**Issue by bjornsen** [dmlc/xgboost#5801]
The recommended multi-GPU build of xgboost `cmake .. -DUSE_CUDA=ON -DUSE_NCCL=ON -DNCCL_ROOT=/path/to/nccl2` assumes a single, fixed directory structure for NCCL. This build pattern doesn't work for anyone who has a non-standard layout.

When I use `cmake .. -DUSE_CUDA=ON -DUSE_NCCL=ON -DNCCL_INCLUDE_DIR=/path/to/nccl2/include -DNCCL_LIBRARY=/apathlesstraveled/to/nccl2/lib/x86_64-linux-gnu`, it fails to build with `Could NOT find Nccl (missing: NCCL_LIBRARY)` despite being the correct library path.

This is because the `NCCL_LIBRARY` is indiscriminately removed from the cmake cache here: https://github.com/dmlc/xgboost/blob/master/cmake/modules/FindNccl.cmake#L37

Please fix `NCCL_LIBRARY` to be user settable.

**Comment by trivialfis** [comment]
The nccl script is in `xgboost/cmake/modules`.  We can add more customization options in there.

**Comment by tanuja3** [comment]
Can I work on this issue?

**Comment by trivialfis** [comment]
You are welcomed.  😀
