### ISSUE TITLE
Error in if ((maximize && score > best_score) || (!maximize && score <  :    missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by iDemirsoy** [dmlc/xgboost#5807]
My goal is to tune my **classification** xgboost and I am using a code for tuning purposes, which I showed in the bottom. It does work when i used following values while looking for optimal nrounds. `[ nrounds = 8000, eval.metric = "logloss" , objective="binary:logistic" ,   early_stopping_rounds = 20,   print_every_n =30,   nfold = 10,   scale_pos_weight =1.55,   params = list(eta = 0.2,   max_depth = 12,  min_child_weight = 3, subsample = 0.5,     colsample_bytree = .4), verbose = 1 ]` 

however, when I wanted to use grid search in next code, it gives me this error 
_**Error in if ((maximize && score > best_score) || (!maximize && score <  :    missing value where TRUE/FALSE needed**_

the code I am using is this. I also tried data.matrix(KC3$Acc) or as.integer(as.character(KC3$Acc)) and as.numeric(as.character(KC3$Acc)). 
Is there any other faster grid search anyone can share? I ve been looking for and couldn't make anything working literally. I cannot share the data because of classified data. 

**_Any help would appreciated deeply! Thank you!_**  

```
# hyperparameter grid
hyper_grid <- expand.grid(
  eta = 0.2,
  max_depth = c(6,12,15) ,
  subsample = 0.5, 
  colsample_bytree = 0.4,
  scale_pos_weight =1.55,
  min_child_weight = c(1, 2, 3, 4),
  gamma=c(.1,1,5,10,100),
  lambda = c(0, 1e-2, 0.1, 1, 100),
  logloss1=0,
  trees1=0
)


# grid search
for(i in seq_len(nrow(hyper_grid))) {
  set.seed(123)                                 # reproducibility 
  m <- xgb.cv(
    data = XFbgboost,
    label = KC3$Acc,
    nrounds = 613,
    objective = "binary:logistic",
    eval.metric = "logloss",
    early_stopping_rounds = 50, 
    print_every_n =30,
    nfold = 10,
    verbose = 1,
    params = list( 
      eta = hyper_grid$eta[i], 
      max_depth = hyper_grid$max_depth[i],
      min_child_weight = hyper_grid$min_child_weight[i],
      subsample = hyper_grid$subsample[i],
      colsample_bytree = hyper_grid$colsample_bytree[i],
      gamma = hyper_grid$gamma[i], 
      lambda = hyper_grid$lambda[i]
    ) 
  )
  hyper_grid$logloss1[i] <- min(m$evaluation_log$test_logloss_mean)
  hyper_grid$trees1[i] <- m$best_iteration
}

```

**Comment by iDemirsoy** [comment]
I think I made mistake starting the lambda from 0 when it clearly takes 1 default. 
I believe that's the mistake however, please let me know if there is better tuning algorithm. I am interested in probability after the fitting the model because I use them to compute something else. Any recommendation for eval_metric for that purpose? and I also have imbalance dataset, 70K 1 and 300K 0. I tried to solve with scale_pos_weight. 
Finally I am currently having train_logloss is way lower than test_logloss. Any recommendation how I can overcome this?

**Comment by hcho3** [comment]
If you want a well-calibrated probability outputs, do not use `scale_pos_weight`. See the discussion in https://discuss.xgboost.ai/t/how-does-scale-pos-weight-affect-probabilities/1790?u=hcho3.
