### ISSUE TITLE
How do you load a XGBoost model saved using dump_model()?

### ISSUE THREAD

**Issue by agcala** [dmlc/xgboost#5817]
After hours of searching I have found no answer of how to recover my model. And training it again is a not an option. It took more than 10 days of training.

So if anybody can give me an answer (that does not include training the model again) I will kindly appreciate. **The model is already saved using dump_model.** So please focus on that.

When I try to use `get_dump()` I receive a cryptic message

> xgboost.core.XGBoostError: [05:27:16]
> C:\Users\Administrator\workspace\xgboost-win64_release_1.1.0\src\learner.cc:506:
> Check failed: mparam_.num_feature != 0 (0 vs. 0) : 0 feature is
> supplied.  Are you using raw Booster interface?

Any ideas of how to do this. **If you cannot recover a model saved with dump_model what is the purpose of the feature then?**

**Comment by trivialfis** [comment]
Not possible with hand written parser.  It's for visualization like plotting the trees, exporting to other formats for other libraries etc.

If you want to have a text model format, try our new JSON model format: https://xgboost.readthedocs.io/en/latest/tutorials/saving_model.html

**Comment by agcala** [comment]
Boomer. Shouldn't that be specified in the documentation for the unsuspected user?

**Comment by trivialfis** [comment]
Sure.  Will open a PR for adding the document.

**Comment by agcala** [comment]
Thank you.
