### ISSUE TITLE
Can I define a new loss function in XGB? 

### ISSUE THREAD

**Issue by shuhaojie** [dmlc/xgboost#5820]
In sklearn.neural_network, there is a loss function dict
`LOSS_FUNCTIONS = {'squared_loss': squared_loss, 'log_loss': log_loss,
                  'binary_log_loss': binary_log_loss}`
I can define a new loss function and add my new loss function in the dict. Is there a similar way in XGB?

**Comment by hcho3** [comment]
Yes, take a look at the example in the demo directory:

* https://github.com/dmlc/xgboost/blob/master/demo/guide-python/custom_objective.py
* https://github.com/dmlc/xgboost/blob/master/demo/guide-python/custom_rmsle.py
* https://github.com/dmlc/xgboost/blob/master/demo/guide-python/custom_softmax.py

**Comment by trivialfis** [comment]
Also there is a tutorial in the doc.

**Comment by shuhaojie** [comment]
> Yes, take a look at the example in the demo directory:
> 
> * https://github.com/dmlc/xgboost/blob/master/demo/guide-python/custom_objective.py
> * https://github.com/dmlc/xgboost/blob/master/demo/guide-python/custom_rmsle.py
> * https://github.com/dmlc/xgboost/blob/master/demo/guide-python/custom_softmax.py

Thanks for the answer. If I'd like to use my customized loss function. I new a .py file (custom_objective.py you given above, for instance) and puts it into the root directory, is that right? And I have a question, how do I make sure my training process uses this newed loss function to train? Any advice？

**Comment by hcho3** [comment]
> puts it into the root directory, is that right?

No, you don't need to put it in the root directory. Try running the demos yourself, and note that they are separate from the Python package directory (`python-package`).

> And I have a question, how do I make sure my training process uses this newed loss function to train? Any advice？

Again, take a look at the demos. Make sure to pass `obj=` option to `xgb.train()`.

**Comment by shuhaojie** [comment]
Hi hcho3, I followed what your advice. Here are a few questions I have
(1)The demo `import xgboost as xgb`, what is this xgboost. The package I installed or the root dictionary(the name of package is also called 'xgboost')
(2)The last line in demo
 ```
bst = xgb.train(param, dtrain, num_round, watchlist, obj=logregobj,
                feval=evalerror)
```
What is the difference between this `train` function and `fit` function(I use `fit` to train in xgb.XGBRegressor or xgb.XGBClassifier)
(3)Is `xgb.train` necessary if I want to custom loss funcion

**Comment by hcho3** [comment]
(1) It is the package you installed.
(2) Take a look at https://github.com/dmlc/xgboost/issues/5786#issuecomment-645574696. This example uses `fit()` function. In XGBoost, you can either use `xgb.train()` or `xgb.XGBRegressor.fit()`.

**Comment by shuhaojie** [comment]
Thanks for the patience, my problem had successfully solved.

**Comment by shuhaojie** [comment]
Hi hcho3, I got an error. Can you help me?Here is my customed loss function
`def mean_harmonic_loss_obj(y_true, y_pred):
    left = np.abs(y_true / (y_true + y_pred) - 0.5)
    right = np.abs(y_true - y_pred) / np.sum(np.abs(y_true - y_pred))
    return 2*np.sum(left * right)` 
And here is how I use it 
`        clf = xgb.XGBRegressor(objective=mean_harmonic_loss_obj)
        clf.fit(standard_x, standard_y)`

`standard_x`, `standard_y` are both `np.ndarry`. And here is the problem
```
 File "D:\anaconda3\envs\python2.7\lib\site-packages\xgboost\core.py", line 1113, in update
    grad, hess = fobj(pred, dtrain)
```
TypeError: 'numpy.float64' object is not iterable`

I see the demo in  #5786 .  `y_true` and` y_pred` are both `np.ndarray` also. Why there is this type of error?

**Comment by trivialfis** [comment]
First, Python 2.7 is not supported, XGBoost should throw an error.  Which XGBoost version are you using?

**Comment by shuhaojie** [comment]
> First, Python 2.7 has already passed end of life, so it is not supported by XGBoost. It should throw an error. Which XGBoost version are you using?

0.82

**Comment by shuhaojie** [comment]
> First, Python 2.7 has already passed end of life, so it is not supported by XGBoost. It should throw an error. Which XGBoost version are you using?

I have switch my default python from 2.7 to 3.1. And xgboost version now is 1.1.1, the problem still exists
