### ISSUE TITLE
NDK build for 32-bit archs fails

### ISSUE THREAD

**Issue by hesamsagha** [dmlc/xgboost#5828]
Compiling xgboost with NDK failes for armeabi-v7a and x86, due to the implicit cast on this line of `c_api.cc`:  
`out = new std::shared_ptr<DMatrix>(dmat->Slice({idxset, len}));`
By adding explicit cast it will be solved:  
`out = new std::shared_ptr<DMatrix>(dmat->Slice({idxset, (std::size_t) len}));`

cmake version: 3.16.3   
ndk version:  21.3.6528147

**Comment by trivialfis** [comment]
Let me fix that.

**Comment by hesamsagha** [comment]
I think a better way it to cast it to `std::size_t`
