### ISSUE TITLE
XGBoost training seems to be stuck for over 1 and 1/2 days at xgbClassifier.fit()

### ISSUE THREAD

**Issue by monicasenapati** [dmlc/xgboost#5830]
Hi, I am new to XGBoost on a distributed set up.  I am training an XGBoost model with around 200,000 rows and 209,538 columns. The data is present in Hadoop HDFS set up on a 16 node cluster. 
My code looks something like this: 
```
 var vectorAssembler = new VectorAssembler().
                                setInputCols(featureCols).
                                setOutputCol("features")]
    val xgbInput = vectorAssembler.transform(trainInput).select("features", "targetColumn") //trainInput is the dataframe that contains all data points I want the model to be trained upon
    println(">>> Step9: Transformed  feature/vector matrix: Training data")
    val xgbParam = Map("eta" -> 0.1f,
      "missing" -> 0,
      "max_depth" -> 6,
      "objective" -> "binary:logistic",
      "num_round" -> 10,
      "num_workers" -> 15,
      "eval_metric" -> "auc")
    println(">>> Step10: Training model")
    val xgbClassifier = new XGBoostClassifier(xgbParam).
                                setFeaturesCol("features").
                                setLabelCol("targetColumn") 
    val xgbClassificationModel = xgbClassifier.fit(xgbInput)
```
And the log file indicates ">>> Step10: Training model" and has been in the same position since last 1 & 1/2 days. 
I run the jar using the following command from the driver:
`spark-submit  --conf spark.dynamicAllocation.enabled=false --name xgboostapp --master spark://vm0:7077 --driver-memory 40G --num-executors 225 --executor-cores 15 --executor-memory 40G  XGBoost-assembly-1.0.jar <input parameters for the jar>`
I want to speed up the process. It shouldn't be taking this long to train. Is there anything I might be missing out on? Any suggestions will be highly appreciated. Thanks!

**Comment by declan-hernon** [comment]
Hello,

I can see in your spark-submit that you have 225 executors each with 15 cores - I think instead you want 15 executors with 15 cores each (Provided there are 15 cores per worker node). Currently the way you have it, Spark is assuming it has 225 * 15 = 3375 cores in its worker nodes - I'm not sure how Spark would behave with this, but it's definitely something you want to fix.

Also, with your executor memory I am assuming that each node has greater than or equal to 40GB.

If you still get problems after changing that, I would suggest looking into Spark's memory fractions - these decide how much memory is used for computation vs your data. I'm not overly familiar with which memory fraction XGBoost tends to work best with, but perhaps someone else on here can answer that.

Something else you could try is setting 'tree_method' to 'hist', 'sampling_method' to 'gradient_based' and 'subsample' to 0.1. You can read more about how these methods work here - https://github.com/dmlc/xgboost/issues/1950 . Essentially, this will find the near-optimal split by bucketing your data using the fast histogram algorithm rather than trying to find the exact/approximate best split.

Hope this helps!

**Comment by monicasenapati** [comment]
Thanks for the suggestions. I corrected the value for num-executors, and it helped to an extent. I will try the rest of them out. By executor memory, do you mean total memory across all 15 worker nodes? For example, if the total RAM for each worker node is 64GB, then the executor memory would take value 15*64GB?

**Comment by declan-hernon** [comment]
The executor memory field is the memory per executor - you could even try setting it directly to 64GB, since I _think_ that the JVM & YARN overhead are included in the executor memory field.

[This article](https://spoddutur.github.io/spark-notes/distribution_of_executors_cores_and_memory_for_spark_application.html) also suggests not having what they call "fat executors" - namely executors that use all cores & memory per worker. To quote:

"**HDFS Throughput:** HDFS client has trouble with tons of concurrent threads. It was observed that HDFS achieves full write throughput with ~5 tasks per executor . So it’s good to keep the number of cores per executor below that number."

Based on this, you may want to try increasing the num_workers/num-executors to 45 and reducing executor-cores to 5 (Also reducing executor memory from 64GB to 21GB).

Sadly I've just noticed that gradient_based subsampling won't work for CPU XGBoost - so instead of my prior suggestion, follow the beneath:

- Set "tree_method" to hist as before
- Set "sampling_method" to "uniform" (Or leave blank, as it's uniform by default)
- Set "subsampling" to 0.5

**Comment by monicasenapati** [comment]
Thanks for the suggestion. I was just about to ask you about sampling_method, since I got an error for sample_type. I was using the parameters below:
val xgbParam = Map("eta"->0.01f,
      "missing" -> 0,
      "max_depth" -> 4,
      "objective" -> "binary:logistic",
      "num_round" -> 100,
      "n_estimators" -> 100,
      "early_stopping_rounds" -> 5,
      "colsample_bytree" -> 0.3,
      "subsample"->0.1,
      "num_workers" -> 525,
      "tree_method" -> "hist",
      "sample_type" -> "gradient_based")

**Comment by trivialfis** [comment]
@monicasenapati 

> "sample_type" -> "gradient_based"

This is only available on `gpu_hist`.

**Comment by monicasenapati** [comment]
Thank you so much for your suggestions. I modified the parameters below: 
 ```
val xgbParam = Map("eta"->0.01f,
      "missing" -> 0,
      "max_depth" -> 4,
      "objective" -> "binary:logistic",
      "num_round" -> 100,
      "n_estimators" -> 100,
      "early_stopping_rounds" -> 5,
      "colsample_bytree" -> 0.3,
      "subsample"->0.5,
      "num_workers" -> 525,
      "tree_method" -> "hist")
```
However, it still takes over 5 days to even start fitting the data frame onto the classifier, i.e. around 5 days for the Rabbit tracker to start. I wanted to confirm if that is the expected speed of XGBoost on Spark?

**Comment by trivialfis** [comment]
Definitely not!  But if that's the case, it seems the problem lies somewhere else than in XGBoost?  As:

>  it still takes over 5 days to even start fitting the data frame onto the classifier

That's not in the area of XGBoost?

**Comment by monicasenapati** [comment]
So I have multiple spark data frames, say df1, df2, df3, df4 and df5 each having 200,050 rows and some columns. I first join them together:
```
var joindf=df1.join(df2, "id")
                .join(df3, "id")
                .join(df4, "id")
                .join(df5, "id")
```
Then I split them into training and test data. After that I start building the feature vectors and perform XGBClassifier.fit as follows:
```
val featureCols=trainInput.columns.toSeq.filterNot(elm => elm == "isPossiblySensitive").toArray
println(">>> Step7: Getting feature columns")
var vectorAssembler = new VectorAssembler().
				setInputCols(featureCols).
  				setOutputCol("features")
val xgbInput = vectorAssembler.transform(trainInput).select("features", "isPossiblySensitive")
println(">>> Step8: Transformed  feature/vector matrix: Training data")
val xgbParam = Map("eta"->0.01f,
      "missing" -> 0,
      "max_depth" -> 4,
      "objective" -> "binary:logistic",
      "num_round" -> 100,
      "n_estimators" -> 100,
      "early_stopping_rounds" -> 5,
      "colsample_bytree" -> 0.3,
      "subsample"->0.5,
      "num_workers" -> 525,
      "tree_method" -> "hist") 
println(">>> Step9: Training model")
val xgbClassifier = new XGBoostClassifier(xgbParam).
                                setFeaturesCol("features").
                                setLabelCol("isPossiblySensitive")
println(">>> Step 10a: Set features and label column for classifier" )
val xgbClassificationModel = xgbClassifier.fit(xgbInput)
println(">>>Step 10b:  To fit model " ) 
```
It takes a very long time from printing the line "`>>> Step 10a: Set features and label column for classifier`" to  the time it starts RabbitTracker and then fit the entire model, i.e. finish executing the line "`val xgbClassificationModel = xgbClassifier.fit(xgbInput)`".

Do you think `.join()` could be an issue?

**Comment by thvasilo** [comment]
Very likely the join is the culprit. If your dataframes have the same columns you should be using `.[union](https://sparkbyexamples.com/spark/spark-dataframe-union-and-union-all/)` not `.join`.

As mentioned this is likely a Spark issue and doesn't have with the XGBoost training being slow. That said, with 200k features, I would expect the training part to be very slow as well.

**Comment by monicasenapati** [comment]
Thanks for confirming @thvasilo ! The reason I do a join is that the data frames have different columns except for the "id" column in common & I require all rows that have the same value in the "id" column. 
Let me figure that out and test how long it takes to train on 200k features. I was wondering if anyone has tried XGBoost on a large number of features, so as to get an idea of the runtime expected.

**Comment by thvasilo** [comment]
I've tried using the [URL dataset](https://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/binary.html#url) which is ~3M data points and ~3.2M features and that used to take ~2 minutes to run with the XGBoost approx method, distributed training with 3 hosts, for 3 rounds and max_depth=5 on the 0.9 release. I expect that to be even faster now.

This is off topic for XGBoost, but It sounds like joins are necessary, and they can be tricky to get right. The Spark optimizer should help some, but take a look at [this tutorial](https://databricks.com/session/optimizing-apache-spark-sql-joins) as well. That should include some optimizations like broadcasting small tables (although I expect the optimizer does that).

**Comment by monicasenapati** [comment]
Thanks @thvasilo  your suggestions have helped me tremendously and I have finally gotten the model to train, with the tracker running. It's still training, but I got the following in the logs now:
```
20/07/14 20:46:58 INFO XGBoostSpark: starting training with timeout set as 1800000 ms for waiting for resources
20/07/14 22:48:21 INFO java.RabitTracker$TrackerProcessLogger: Exception in thread Thread-1:
20/07/14 22:48:21 INFO java.RabitTracker$TrackerProcessLogger: Traceback (most recent call last):
20/07/14 22:48:21 INFO java.RabitTracker$TrackerProcessLogger:   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
20/07/14 22:48:21 INFO java.RabitTracker$TrackerProcessLogger:     self.run()
20/07/14 22:48:21 INFO java.RabitTracker$TrackerProcessLogger:   File "/usr/lib/python2.7/threading.py", line 754, in run
20/07/14 22:48:21 INFO java.RabitTracker$TrackerProcessLogger:     self.__target(*self.__args, **self.__kwargs)
20/07/14 22:48:21 INFO java.RabitTracker$TrackerProcessLogger:   File "/tmp/tracker4236160164047178261.py", line 324, in run
20/07/14 22:48:21 INFO java.RabitTracker$TrackerProcessLogger:     self.accept_slaves(nslave)
20/07/14 22:48:21 INFO java.RabitTracker$TrackerProcessLogger:   File "/tmp/tracker4236160164047178261.py", line 268, in accept_slaves
20/07/14 22:48:21 INFO java.RabitTracker$TrackerProcessLogger:     s = SlaveEntry(fd, s_addr)
20/07/14 22:48:21 INFO java.RabitTracker$TrackerProcessLogger:   File "/tmp/tracker4236160164047178261.py", line 64, in __init__
20/07/14 22:48:21 INFO java.RabitTracker$TrackerProcessLogger:     assert magic == kMagic, 'invalid magic number=%d from %s' % (magic, self.host)
20/07/14 22:48:21 INFO java.RabitTracker$TrackerProcessLogger: AssertionError: invalid magic number=542393671 from 196.**.**.**
20/07/14 22:48:21 INFO java.RabitTracker$TrackerProcessLogger: 
20/07/14 22:48:21 INFO java.RabitTracker: Tracker Process ends with exit code 0
20/07/14 22:48:21 INFO java.RabitTracker$TrackerProcessLogger: Tracker Process ends with exit code 0
20/07/14 22:48:21 INFO XGBoostSpark: Rabit returns with exit code 0.
```

Exit code 0 meaning it was a success, however, do you think I should be worried about "`java.RabitTracker$TrackerProcessLogger: AssertionError: invalid magic number=542393671`" ?

**Comment by trivialfis** [comment]
Yes.  That's an issue.

**Comment by monicasenapati** [comment]
Thank you all for taking the time in answering my questions. I was able to resolve the issues and get it running successfully.
