### ISSUE TITLE
Small correction in AFT Survival documentation

### ISSUE THREAD

**Issue by gary-rentify** [dmlc/xgboost#5838]
Think the left censored label should be `-np.inf` instead of `0.0` in `y_lower_bound`? Model evaluations return `np.nan` otherwise, and `-np.inf` was the value from the original discussion in #4763 
<img width="639" alt="Screen Shot 2020-06-29 at 16 18 07" src="https://user-images.githubusercontent.com/35135513/86024041-62f47b80-ba24-11ea-8c85-8e6f3708ab6e.png">

**Comment by hcho3** [comment]
No, since the survival times are not in log scale. Time to event is always nonnegative.

**Comment by gary-rentify** [comment]
yep, fair, will check things again 👌
