### ISSUE TITLE
xgboost_wrapper feature request (GetParam(s) & GetNumTrees)

### ISSUE THREAD

**Issue by Far0n** [dmlc/xgboost#584]
Hello,

it would be nice to have the following within the C++-Wrapper:
- *XGBoosterGetParam* and/or *XGBoosterGetParams*
- *XGBoosterGetNumTrees*

cheers
Faron

**Comment by tqchen** [comment]
This is hard for current implementation(GetParams). Because the parameters are deeply hidden in the data structure. Will consider add these in next round of refactor

**Comment by Far0n** [comment]
Thx for the feedback @tqchen. Should I close this issue for now?
