### ISSUE TITLE
spark and cli output different model

### ISSUE THREAD

**Issue by SongBiu** [dmlc/xgboost#5840]
I notice that the binary model produced by spark is different from cli and python produce, because it write a int into output stream before call c api which is called by cli and python without any post process.
It cause the model produced by spark can't be loaded by python.

Now I solve it by dropping front 4 bytes in model which produced by spark before load it.
Do you have other solutions?

**Comment by trivialfis** [comment]
Not sure why, but according to @CodingCat this is by design?
