### ISSUE TITLE
Get string dump of a xgboost model binary format without xgboost

### ISSUE THREAD

**Issue by datistiquo** [dmlc/xgboost#5842]
Hey,

I have a xgboost model in the binary format and need its string dump of the decision trees like with model.get_dump().
Is it possible to get this structure right out of the binary model without using the xgboost library?
I am using a system where no xgboost is available, so I have to get the string dump of xgboost from another system with xgboost. So it would be nice if I can directly parse the binary xgboost model to get the decision trees like in get_dump().

Thanky you in advance.

**Comment by trivialfis** [comment]
No.  But latest XGBoost can save model in JSON format, and we have an example parser in demo.  Check it out.
