### ISSUE TITLE
Saving feature names - 'Booster' object has no attribute 'feature_types'

### ISSUE THREAD

**Issue by datistiquo** [dmlc/xgboost#5843]
Hi,

if I follow this issue and follow the advice of @khotilov in https://github.com/dmlc/xgboost/issues/3089 ie:

```
if hasattr(bst, 'feature_names'): bst.set_attr(feature_names = '|'.join(bst.feature_names))

Then after loading that model you may restore the python 'feature_names' attribute:

if bst.attr('feature_names') is not None: bst.feature_names = bst.attr('feature_names').split('|')

```

, I get the error:
`
'Booster' object has no attribute 'feature_types'`

Maybe I miss something in the first place to save the feature names together with the binary format? Where do I "handover" a list of feature names?

**Comment by hcho3** [comment]
The feature names originate from a `DMatrix` (data matrix) object. You need to run `bst.predict()` at least once so that the feature names get transferred from the training `DMatrix` to the `Booster` object.
