### ISSUE TITLE
output of predict_proba() and objective= binary:logistic

### ISSUE THREAD

**Issue by zahs123** [dmlc/xgboost#5850]
hi i would put this in : https://discuss.xgboost.ai but it is quite unresponsive. 

i have a binary classification problem so i am using xgbclassifier. i set the objective function to binary:logistic. Therefore when i employ: predict.proba(x_test) are these probabilites or scores??

**Comment by hcho3** [comment]
The output of `predict_proba()` is probability. However, see https://scikit-learn.org/stable/modules/calibration.html about calibrating the model for accurate probability estimates.

**Comment by NiDHanWang** [comment]
> The output of `predict_proba()` is probability. However, see https://scikit-learn.org/stable/modules/calibration.html about calibrating the model for accurate probability estimates.

But I got soemthing bigger than 1 , this doesn't seem to be probabilites
