### ISSUE TITLE
What`s the difference in feature importance (gain) computation between v0.90 and v1+ ?

### ISSUE THREAD

**Issue by Nerwax** [dmlc/xgboost#5860]
Hello,

I have recently updated the XGBoost version of my ML project and I have noticed that the feature importance (gain) between v0.9 and newest version (v1+) is very different.

The relative importance of a feature changed and the score and gain changed quite a lot. As you can see in the samples showed below, for the same dataset, the feature importance score changed quite a lot (this is the top 20 features only). The only difference between the 2 examples is the XGBoost version.

Does anyone can explain to me what changed so radically in the feature score computation between version 0.90 and v1+ ?

Thanks a lot for the explenation

![image](https://user-images.githubusercontent.com/63595406/86606189-b7907d00-bf75-11ea-9b1b-4ebaf373c4b7.png)
![image](https://user-images.githubusercontent.com/63595406/86606277-cecf6a80-bf75-11ea-9c2c-4302a8438641.png)

**Comment by trivialfis** [comment]
Could you please provide the set of parameters you used?

**Comment by Nerwax** [comment]
Hello, 

Here is the parameters used:
XGBClassifier(base_score=0.5, booster=None, colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints=None,
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=1, num_parallel_tree=1, random_state=42,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method=None, validate_parameters=False, verbosity=None)

**Comment by trivialfis** [comment]
Are you using sklearn interface?

**Comment by Nerwax** [comment]
Hi @trivialfis, yes I am using the Sklearn interface to get the feature importance.

Thanks !

**Comment by trivialfis** [comment]
At XGBoost 1.0.0, we unified the default parameters between sklearn interface and internal default (which is used by other interfaces).  Specifically the `learning_rate` and `max_depth` are changed.  https://github.com/dmlc/xgboost/pull/5130#issuecomment-574489850
