### ISSUE TITLE
DaskXGBRegressor with YarnCluster client seems training only happened on one worker

### ISSUE THREAD

**Issue by dding3** [dmlc/xgboost#5865]
I tried to train DaskXGBRegressor on a yarn cluster with 3 nodes:

```
with YarnCluster(environment=‘environment.tar.gz’,worker_vcores=10, worker_memory=“50GiB”) as cluster:
cluster.scale(3)
with Client(cluster) as client:
main(client)

xgb.dask.train(client,
{‘verbosity’: 1,
‘tree_method’: ‘hist’,
‘n_estimators’: 500,
‘max_depth’: 50,
‘n_jobs’: -1,
‘random_state’: 2,
‘learning_rate’: 0.1,
‘min_child_weight’: 1,
‘seed’: 0,
‘subsample’: 0.8,
‘colsample_bytree’: 0.8,
‘gamma’: 0,
‘reg_alpha’: 0,
‘reg_lambda’: 1},
dtrain,
num_boost_round=500, evals=[(dTrain, ‘train’)])
```
Again, the training dataset has more than 6 million records.

I tried “top” on each node in the cluster, I can find on one node, cpu usage is 100% for a python process while on other two nodes, cpu usage is less than 10% for python process. And there is no error in logs. I am wondering does that mean the training only happened on 1 node and if it’s a expected behavior?

**Comment by trivialfis** [comment]
Certainly no.   But could you please check whether the data is well balanced?

**Comment by dding3** [comment]
> Certainly no. But could you please check whether the data is well balanced?

Thank you for your reply. I am new to Dask, any guidance on how to check if the data is balanced?

**Comment by trivialfis** [comment]
> how to check if the data is balanced?

A bit hacky.  I print the internal DMatrix shape.  As it's internal information so I never tried to expose it to users.  If you just want to verify, you can check the chunks for each worker.

Balancing data on dask is not an easy task from my experience.  The easiest way it to reduce the chunk size to increase granularity, but that can reduce dask op performance, especially on GPU.  I believe there are undergoing work on this.

Closing as it's not XGBoost's specific.
