### ISSUE TITLE
Warning : parameters : {max_leaf_nodes, verbose ) might not be used xgbclassifier

### ISSUE THREAD

**Issue by hanzigs** [dmlc/xgboost#5879]
I have the xgbclassifier with parameters
```
hyperparameters = {'colsample_bytree': 0.5,
 'eta': [0.01,0.02,0.03],
 'gamma': [0.0,0.1,0.2],
 'max_depth': [3,4,5],
 'max_leaf_nodes': [2,3,4],
 'min_child_weight': [1,2,3],
 'n_estimators': [100,200,500],
 'subsample': [0.5,0.6,0.7]}
```
while tuning i get Warning on 
![image](https://user-images.githubusercontent.com/30790120/87219996-9bd90c80-c3a3-11ea-91b5-12a44199cfe7.png)

xgb version is 0.90
May i know whats the warning about? Thanks

**Comment by hanzigs** [comment]
found it, my bad, max_depth and max_leaf_nodes, both not required together.

**Comment by trivialfis** [comment]
First you are not using 0.9.  Only later versions have parameter validation.

Second there s `max_leaves`, but no `max_leaf_node`.

**Comment by hanzigs** [comment]
Yeah, Thanks, I updated the xgboost from 0.90, but I got user denied error, so I thought it was not updated
