### ISSUE TITLE
can no longer import xgboost

### ISSUE THREAD

**Issue by adjgiulio** [dmlc/xgboost#588]
I used to be able to use xgboost no problem under previous versions just doing:
sys.path.append('/.../xgboost-master/wrapper')
import xgboost as xgb

I tried installing the latest version on a RedHat machine:

bash build.sh

then from the python-package folder:
python setup.py install

Both seem to complete successfully.

But when I try to import from Spyder:
import xgboost as xgb

I get:

Traceback (most recent call last):

  File "<ipython-input-6-745aa3a2d734>", line 1, in <module>
    import xgboost as xgb

  File "/home/g/anaconda/lib/python2.7/site-packages/xgboost-0.4-py2.7.egg/xgboost/__init__.py", line 11, in <module>
    from .core import DMatrix, Booster

  File "/home/g/anaconda/lib/python2.7/site-packages/xgboost-0.4-py2.7.egg/xgboost/core.py", line 92, in <module>
    _LIB = _load_lib()

  File "/home/g/anaconda/lib/python2.7/site-packages/xgboost-0.4-py2.7.egg/xgboost/core.py", line 83, in _load_lib
    lib_path = find_lib_path()

  File "/home/g/anaconda/lib/python2.7/site-packages/xgboost-0.4-py2.7.egg/xgboost/libpath.py", line 43, in find_lib_path
    'List of candidates:\n' + ('\n'.join(dll_path)))

XGBoostLibraryNotFound: Cannot find XGBoost Libarary in the candicate path, did you run build.sh in root path?
List of candidates:
/home/g/anaconda/lib/python2.7/site-packages/xgboost-0.4-py2.7.egg/xgboost/libxgboostwrapper.so
/home/g/anaconda/lib/python2.7/site-packages/xgboost-0.4-py2.7.egg/xgboost/../../wrapper/libxgboostwrapper.so
/home/g/anaconda/lib/python2.7/site-packages/xgboost-0.4-py2.7.egg/xgboost/./wrapper/libxgboostwrapper.so

In [7]: sys.path.append('/home/cloudera/Documents/ds/xgboost-master/wrapper')
   ...: import xgboost as xgb

**Comment by phunterlau** [comment]
@adjgiulio can you check if you have these .so files in these directories:
```
/home/g/anaconda/lib/python2.7/site-packages/xgboost-0.4-py2.7.egg/xgboost/libxgboostwrapper.so
/home/g/anaconda/lib/python2.7/site-packages/xgboost-0.4-py2.7.egg/xgboost/../../wrapper/libxgboostwrapper.so
/home/g/anaconda/lib/python2.7/site-packages/xgboost-0.4-py2.7.egg/xgboost/./wrapper/libxgboostwrapper.so
```
and usually you don't need `sys.path.append` after installation if $PYTHONPATH is set.

P.S. are you sure it was not a typo `sys.path.append('/.../xgboost-master/wrapper')` in the path with `/.../`?

**Comment by tqchen** [comment]
The path now should go to xgboost-master/python-package instead of wrapper

**Comment by nitesh458** [comment]
While importing xgboost (installed via. pip install xgboost) i get segmenation fault
import xgboost
Segmentation fault (core dumped)

**Comment by phunterlau** [comment]
@nitesh458 can you manually remove the old installation and re-install? you can do `pip install xgboost` for finding the old installation. You can also remove the old one and install from github by `make xgboost` and go to python dir for installation.

**Comment by aidsj** [comment]
I have same issue with nitesh458.
I used to use the version in pypi and it works fine.
I need to use newer version so i use pip uninstall xgboost to uninstall the old package.
Then i followed the https://github.com/dmlc/xgboost/blob/master/doc/build.md#building-on-ubuntudebian to install.
Everything seems to be all right, however, i can't import xgboost. it give error message:
Segmentation fault (core dumped).
Then i tried delete this and reinstall use pip. Guess what, it gives the same error message.
Any idea how to solve it?

**Comment by phunterlau** [comment]
please manually remove the old pip install by `rm -rf ./anaconda/lib/python2.7/site-packages/xgboost*`

**Comment by nitesh458** [comment]
Hi aidsj, I could solve this problem simply by doing sudo apt-get update and then conda update all..... I wasn't able to run mxnet as well though

**Comment by carlylou** [comment]
Hi, I follow the instructions from http://xgboost.readthedocs.io/en/latest/build.html# installed xgboost well. 

But when I import xgboost, I get this error :

OSError: dlopen(/usr/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/libxgboost.so, 6): Symbol not found: _clock_getres
  Referenced from: /usr/local/opt/gcc/lib/gcc/6/libgomp.1.dylib
  Expected in: /usr/lib/libSystem.B.dylib
 in /usr/local/opt/gcc/lib/gcc/6/libgomp.1.dylib

I google it but I did not find anything related. Please help me. Thanks!!
