### ISSUE TITLE
when use spark xgboost model predict the same sample,  the predict score is not same 

### ISSUE THREAD

**Issue by leidaxia** [dmlc/xgboost#5889]
Hi,  I have trained a model on Spark, and get a model file， but when I  use the model to predict batch sample,   I find  that I predict the two same sample,   the result score is not same,  Im sure the two sample featue value are same,    I cannot find the bug 
我使用spark训练我的xgboost模型，然后获得了一个模型文件，当我使用这个文件进行批处理预测测试样本时，发现两个相同的样本，打分结果却不一样， 我确定这两个样本的特征值都一样，我找不到bug在哪里

![image](https://user-images.githubusercontent.com/20982126/87413640-24061e80-c5fd-11ea-95a2-1dd1575d542c.png)

**Comment by leidaxia** [comment]
![image](https://user-images.githubusercontent.com/20982126/87413728-4435dd80-c5fd-11ea-991c-f982f556da3a.png)

**Comment by hcho3** [comment]
Please post an example code for the bug.
