### ISSUE TITLE
Failed to build R package.

### ISSUE THREAD

**Issue by trivialfis** [dmlc/xgboost#5894]
After #5871 I can't build R package on my local machine with link time error:

```
/usr/bin/ld: ../../R-package/CMakeFiles/xgboost-r.dir/src/init.c.o: in function `R_init_xgboost':
/home/fis/Workspace/XGBoost/xgboost/R-package/src/init.c:83: undefined reference to `R_registerRoutines'
/usr/bin/ld: /home/fis/Workspace/XGBoost/xgboost/R-package/src/init.c:84: undefined reference to `R_useDynamicSymbols'
/usr/bin/ld: ../../R-package/CMakeFiles/xgboost-r.dir/src/xgboost_R.cc.o: in function `XGCheckNullPtr_R':
/home/fis/Workspace/XGBoost/xgboost/R-package/src/xgboost_R.cc:41: undefined reference to `R_ExternalPtrAddr'
/usr/bin/ld: /home/fis/Workspace/XGBoost/xgboost/R-package/src/xgboost_R.cc:41: undefined reference to `Rf_ScalarLogical'
/usr/bin/ld: ../../R-package/CMakeFiles/xgboost-r.dir/src/xgboost_R.cc.o: in function `_DMatrixFinalizer(SEXPREC*)':

...
```

R: 3.6.1
CMake: 3.13.4
GCC: gcc (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008

**Comment by hcho3** [comment]
That's strange. The build works on my machine.
* R: 3.6.3
* CMake: 3.18.0
* GCC: 7.5.0

On the other hand, I launched a VM with Ubuntu 19.10, R 3.6.1, CMake 3.13.4, and GCC 9.2.1, and the issue is reproduced.

This might have to do with CMake version.

**Comment by hcho3** [comment]
Indeed, CMake is the culprit here. I upgrade CMake from 3.13.4 to 3.14.0 on my Ubuntu 19.10 VM, and the build now works.
