### ISSUE TITLE
plot_tree - PermissionError: [Errno 13] Permission denied: 'dot'

### ISSUE THREAD

**Issue by AntonioL** [dmlc/xgboost#5903]
I am using XGBoost library installed via
`` pipenv install xgboost```

The XGBoost library is running within Python 3.7.5 inside a Jupiter notebook.

I am training an XGBoostClassifier.

The following code snippet
```python
xgboost.plot_tree(xgb_model)
pyplot.show()
```
gives this error

```
PermissionError                           Traceback (most recent call last)
 in 
----> 1 xgboost.plot_tree(xgb_model)
      2 pyplot.show()

~/.local/share/virtualenvs/hfb-strategy-AXaWg3wV/lib/python3.7/site-packages/xgboost/plotting.py in plot_tree(booster, fmap, num_trees, rankdir, ax, **kwargs)
    246 
    247     s = BytesIO()
--> 248     s.write(g.pipe(format='png'))
    249     s.seek(0)
    250     img = image.imread(s)

~/.local/share/virtualenvs/hfb-strategy-AXaWg3wV/lib/python3.7/site-packages/graphviz/files.py in pipe(self, format, renderer, formatter, quiet)
    136         out = backend.pipe(self._engine, format, data,
    137                            renderer=renderer, formatter=formatter,
--> 138                            quiet=quiet)
    139 
    140         return out

~/.local/share/virtualenvs/hfb-strategy-AXaWg3wV/lib/python3.7/site-packages/graphviz/backend.py in pipe(engine, format, data, renderer, formatter, quiet)
    242     """
    243     cmd, _ = command(engine, format, None, renderer, formatter)
--> 244     out, _ = run(cmd, input=data, capture_output=True, check=True, quiet=quiet)
    245     return out
    246 

~/.local/share/virtualenvs/hfb-strategy-AXaWg3wV/lib/python3.7/site-packages/graphviz/backend.py in run(cmd, input, capture_output, check, encoding, quiet, **kwargs)
    162 
    163     try:
--> 164         proc = subprocess.Popen(cmd, startupinfo=get_startupinfo(), **kwargs)
    165     except OSError as e:
    166         if e.errno == errno.ENOENT:

/usr/lib/python3.7/subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors, text)
    798                                 c2pread, c2pwrite,
    799                                 errread, errwrite,
--> 800                                 restore_signals, start_new_session)
    801         except:
    802             # Cleanup if the child failed starting.

/usr/lib/python3.7/subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, restore_signals, start_new_session)
   1549                         if errno_num == errno.ENOENT:
   1550                             err_msg += ': ' + repr(err_filename)
-> 1551                     raise child_exception_type(errno_num, err_msg, err_filename)
   1552                 raise child_exception_type(err_msg)
   1553 

PermissionError: [Errno 13] Permission denied: 'dot'

``` 

I do understand the error what I do not understand is where this **dot** file is actually being created. Can you advise in that regard?

Also I am not sure whether it is an xgboost issue but I hope that you can help me in restricting down the issue.

**Comment by achyuthkaranam** [comment]
I'm also facing the same issue...
Can you please tell me how you resolved this issue in detailed manner..

Thank you..

PermissionError                           Traceback (most recent call last)
<ipython-input-46-fdd6a09bf074> in <module>
----> 1 plot_tree(xgb)
      2 fig = plt.gcf()
      3 fig.set_size_inches(100,80)
      4 fig.savefig('tree.png')

/projects/aiops/jupyterhub/lib64/python3.6/site-packages/xgboost/plotting.py in plot_tree(booster, fmap, num_trees, rankdir, ax, **kwargs)
    248 
    249     s = BytesIO()
--> 250     s.write(g.pipe(format='png'))
    251     s.seek(0)
    252     img = image.imread(s)

/projects/aiops/jupyterhub/lib64/python3.6/site-packages/graphviz/files.py in pipe(self, format, renderer, formatter, quiet)
    169         out = backend.pipe(self._engine, format, data,
    170                            renderer=renderer, formatter=formatter,
--> 171                            quiet=quiet)
    172 
    173         return out

/projects/aiops/jupyterhub/lib64/python3.6/site-packages/graphviz/backend.py in pipe(engine, format, data, renderer, formatter, quiet)
    246     """
    247     cmd, _ = command(engine, format, None, renderer, formatter)
--> 248     out, _ = run(cmd, input=data, capture_output=True, check=True, quiet=quiet)
    249     return out
    250 

/projects/aiops/jupyterhub/lib64/python3.6/site-packages/graphviz/backend.py in run(cmd, input, capture_output, check, encoding, quiet, **kwargs)
    162 
    163     try:
--> 164         proc = subprocess.Popen(cmd, startupinfo=get_startupinfo(), **kwargs)
    165     except OSError as e:
    166         if e.errno == errno.ENOENT:

/usr/lib64/python3.6/subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors)
    727                                 c2pread, c2pwrite,
    728                                 errread, errwrite,
--> 729                                 restore_signals, start_new_session)
    730         except:
    731             # Cleanup if the child failed starting.

/usr/lib64/python3.6/subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, restore_signals, start_new_session)
   1362                         if errno_num == errno.ENOENT:
   1363                             err_msg += ': ' + repr(err_filename)
-> 1364                     raise child_exception_type(errno_num, err_msg, err_filename)
   1365                 raise child_exception_type(err_msg)
   1366 

PermissionError: [Errno 13] Permission denied: 'dot'

**Comment by cpattapagala** [comment]
does anyone have a solution to resolve this error?

**Comment by dani-smd** [comment]
> I had to install graphviz via apt-get.
> 
> Closing this issue.
Thanks a lot, you helped me
