### ISSUE TITLE
Include libxgboost4j.dylib (MacOS) in Snapshot JARs

### ISSUE THREAD

**Issue by viktio** [dmlc/xgboost#5906]
Hi guys,

I'm testing your library and comparing the results between Java and Python libraries.
I'm seeing significant differences with the Python library being a lot better on my test data.
The only difference I found was the version of the underlying Xgboost library (the cc classes).
There are some commits for which I'm waiting in the Java version, e.g. 

Fix pruner. (#5335)

* Honor the tree depth.
* Prevent pruning pruned node. https://github.com/dmlc/xgboost/commit/e0509b330734c1d6ee32b843c273a6934df24319#diff-cd7e3f1e4c39ef6c389c09dd7cecddbd

Can you please create a new release to Maven Central with the current version? I would be very grateful!! 

Thank you in advance :)

**Comment by hcho3** [comment]
The XGBoost project hosts a Maven repository. You can get latest releases and snapshots: https://xgboost.readthedocs.io/en/latest/jvm/index.html#access-snapshot-version

**Comment by viktio** [comment]
Thank you, that really helped! I see however that the snapshot Jar doesn't have the /lib/libxgboost4j.dylib, it only has the /lib/libxgboost4j.so file, which enables to run it only on linux, but not on OSX, would it be possible to include also the dylib file in the snapshots? 

Thanks again :)

**Comment by hcho3** [comment]
> would it be possible to include also the dylib file in the snapshots?

Not right now. You should compile from the source for the time being. You can run `mvn package` in the `jvm-packages/` directory.

**Comment by viktio** [comment]
OK, thanks for help and quick responses!
