### ISSUE TITLE
This may not be accurate due to some parameters are only used in language bindings but passed down to XGBoost core.  Or some parameters are not used but slip through this verification. Please open an issue if you find above cases.

### ISSUE THREAD

**Issue by SimZhou** [dmlc/xgboost#5907]
Basically I moved everything to my Linux (centos 8) server, then this pops out:
![image](https://user-images.githubusercontent.com/11748629/87850382-69d72580-c922-11ea-80f7-30085d51961c.png)

(There is no such warnings when I run it on my windows laptop)

However, the param `verbose_eval` seems to be working right...

**Comment by hcho3** [comment]
The `verbose_eval` belongs to the Python function call `xgb.train()`, not in the `param` dictionary.

**Comment by SimZhou** [comment]
> The `verbose_eval` belongs to the Python function call `xgb.train()`, not in the `param` dictionary. See the doc for `xgb.train()`: https://xgboost.readthedocs.io/en/latest/python/python_api.html#xgboost.train

Oh that's it! thx for blustering fast reply haha.

**Comment by trivialfis** [comment]
@hcho3 So far the parameters validation has been working well, do you think it's time for us to drop the experimental tag?

**Comment by hcho3** [comment]
@trivialfis Yes, we can drop the experimental tag. Thanks for implementing it. It is one of the best major improvements we made in user experience recently.

**Comment by trivialfis** [comment]
Thanks, let me submit a PR next week.
