### ISSUE TITLE
Is the L1 calced correct in the xgboost/src/tree/param.h?

### ISSUE THREAD

**Issue by httese** [dmlc/xgboost#5914]
Thanks for participating in the XGBoost community! We use https://discuss.xgboost.ai for any general usage questions and discussions. The issue tracker is used for actionable items such as feature proposals discussion, roadmaps, and bug tracking.  You are always welcomed to post on the forum first :)

Issues that are inactive for a period of time may get closed. We adopt this policy so that we won't lose track of actionable issues that may fall at the bottom of the pile. Feel free to reopen a new one if you feel there is an additional problem that needs attention when an old one gets closed.

For bug reports, to help the developer act on the issues, please include a description of your environment, preferably a minimum script to reproduce the problem.

For feature proposals, list clear, small actionable items so we can track the progress of the change.

**Comment by httese** [comment]
// functions for L1 cost
template <typename T1, typename T2>
XGBOOST_DEVICE inline static T1 ThresholdL1(T1 w, T2 alpha) {
  if (w > + alpha) {
    return w - alpha;
  }
  **if (w < - alpha) {
    return w + alpha;
  }**
  return 0.0;
}

**Comment by hcho3** [comment]
Yes, `sum_grad` is set to zero if it's between `[-alpha, alpha]` range. L1 regularization encourages "sparsity," i.e. small gradient values will produce a zero gain.
