### ISSUE TITLE
Problem with instalation on python 3.8

### ISSUE THREAD

**Issue by AlexanderGolys** [dmlc/xgboost#5924]
While trying to install xgboost using pip on python 3.8 I get this error:

```
ERROR: Command errored out with exit status 1: 'c:\users\exemed\pycharmprojects\test2\venv\venv38\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\exemed\\AppData\\Local\\
Temp\\pip-install-gbr4wub6\\xgboost\\setup.py'"'"'; __file__='"'"'C:\\Users\\exemed\\AppData\\Local\\Temp\\pip-install-gbr4wub6\\xgboost\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.re
ad().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\exemed\AppData\Local\Temp\pip-record-cyiy35un\install-record.txt' --single-version-ext
ernally-managed --compile --install-headers 'c:\users\exemed\pycharmprojects\test2\venv\venv38\include\site\python3.8\xgboost' Check the logs for full command output.
```

On python 3.7 there was no problem. How to fix it?

**Comment by trivialfis** [comment]
@hcho3 I think we don't have Python 3.8 binary right?  Maybe it's time to prepare a release ..

**Comment by hcho3** [comment]
Our Python wheel is tagged with `py3`, so it should be compatible with Python 3.8.

**Comment by trivialfis** [comment]
Got it.  Let me try to reproduce this on Linux later.

**Comment by hcho3** [comment]
Just tried it on my Windows machine and `pip install xgboost` worked as expected with Python 3.8.

@AlexanderGolys Can you try running `pip install -v xgboost` to get more diagnostic logs?

**Comment by trivialfis** [comment]
Also tried on Linux.  Works fine.

**Comment by hcho3** [comment]
@AlexanderGolys Your Python environment might be broken. I had success with Conda:
1. Download Miniconda from https://docs.conda.io/en/latest/miniconda.html
2. In the Command Prompt, run `conda create -n myenv python=3.8` to create a new Python environment.
3. Activate the environment with `conda activate myenv`.
4. Install XGBoost: `python -m pip install xgboost`.
