### ISSUE TITLE
Should `max_depth` be changed with changing number of features?

### ISSUE THREAD

**Issue by sbushmanov** [dmlc/xgboost#593]
This is a follow up question to [#95](https://github.com/dmlc/xgboost/issues/95), which discusses One-Hot-Encoding (OHE) as one of the possible ways to encode categorical variables.

My situation is as follows: I have a biggish data set (~ 1 million rows, ~ 30 features, some of which may be deemed categorical). And I'm trying different encoding schemes for several variables. As of now, the optimal `max_depth` for a model with decent predictions is 12. If I OHE-encode a feature with say 50 levels, theoretically, should the optimal `max-depth` stay exactly the same?

I wouldn't be surprised by answers like "you should search for new optimal parameter", but if so, where should I start? From 12 or 62?

**Comment by pommedeterresautee** [comment]
Deepness purpose is for catching more complex non linear link between features and output. To help you there is a new function in R package to plot the distribution of Deepness in your trees. 

Kind regards, 
Michaël
