### ISSUE TITLE
[R] Cannot set weights per query group when learning to rank

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#5942]
The `setinfo()` currently throws error if the length of the given weight vector is not equal to the number of rows in the data:

https://github.com/dmlc/xgboost/blob/8b1afce316b5b600bd8a8d09c460248b1a26b758/R-package/R/xgb.DMatrix.R#L259-L264

This check is incompatible with learning to rank, since when learning to rank, we assign weights to query groups, not individual data rows. Thus, it's currently not possible to perform weighted ranking in the R package.

**Comment by trivialfis** [comment]
We can remove the check safely as we added checks in c++.  There's a validate method in meta info.
