### ISSUE TITLE
xgb.plot.tree error

### ISSUE THREAD

**Issue by dtfoster** [dmlc/xgboost#595]
Hi,

The xgb.plot.tree function from the example code in the xgboost documentation gives me an error - undefined is not an object (evaluating 'x[0]')
![screen shot 2015-11-03 at 18 02 04](https://cloud.githubusercontent.com/assets/5172426/10916778/10489170-8255-11e5-9e81-65386b893ca7.png)
:

I'm using the latest R package (0.4-2) in RStudio and get the same error on Windows and Mac. 

Thanks,

David

**Comment by pommedeterresautee** [comment]
Have you updated all your packages, in particular DiagrammeR?
What is your OS?

**Comment by dtfoster** [comment]
Hi,

Yes I have the current version of DiagrammeR (0.8.1)

My Mac OS is El Capitan 10.11.1 and Windows is Windows 7 - it doesn't work on either.

Let me know if you need any more info from me - thanks for your help.

David

**Comment by pommedeterresautee** [comment]
Mmmmhhh finally I have the same issue on Windows. Will check the code this week end.

**Comment by pommedeterresautee** [comment]
Don't hesitate to re open the issue if you have an issue with the new function.

**Comment by weedySeaDragon** [comment]
I'm getting the same error, though with different data -- the Titanic data.  (I'm using the data from the Titanic competition to learn xgboost.)  I can show you an output, but it's quite similar to the one posted by dtfoster  (it's a parsing error).

My system: Win 7
all R packages are up to date:
 xgboost - version 0.4-2
 DiagrammeR  version 0.8.1

How can I make sure that I have the merged changes that were to fix this?  Will it require that I build xgboost on my windows system?  *(please O please, say it ain't so.  But if I must, I suppose I can...)*

Thanks!

**Comment by pommedeterresautee** [comment]
Only the version from Github is fixed. 
The Cran version is not updated at all.

**Comment by wangshuailong** [comment]
Got this error too, fixed it by reinstalling from github.
Just follow the document.
```
install.packages("drat", repos="https://cran.rstudio.com")
drat:::addRepo("dmlc")
install.packages("xgboost", repos="http://dmlc.ml/drat/", type="source")
```

**Comment by akrsrivastava** [comment]
Is this fixed on CRAN now? I am getting a similar error when I run xgb.plot.tree from the example code 

![clip](https://cloud.githubusercontent.com/assets/19535249/17734721/a200f714-649b-11e6-8ba8-8fc8a477a5cb.jpg)

I have xgboost ver 0.4-4 and Diagramer ver 0.8.4 installed from CRAN . Rstudio 0.99.903, Windows 10, R 3.3.1

**Comment by pommedeterresautee** [comment]
can you send the code you are using? Is it the one from the example ?

**Comment by akrsrivastava** [comment]
library(xgboost)
library(DiagrammeR)
data(agaricus.train)
str(agaricus.train)
train.data <- agaricus.train
dtrain <- xgb.DMatrix(train.data$data, label = train.data$label)
model <- xgboost(data = dtrain, nrounds = 100, objective = "binary:logistic")
bst <- xgboost(data = train.data$data, label = train.data$label, max.depth = 2,
               eta = 1, nthread = 2, nround = 2, objective = "binary:logistic")
xgb.plot.tree(feature_names = agaricus.train$data@Dimnames[[2]], model = bst)`
`

**Comment by akrsrivastava** [comment]
This is now fixed. I started getting a couple of other errors with xgboost. For e.g. XGDMatrixNumCol_R" not available for .Call() for package "xgboost"

It seemed an installation issue. So I removed xgboost, removed Rtools. Reinstalled Rtools and then again installed xgboost. This fixed the issue.

Thanks.
