### ISSUE TITLE
AssertError:read can not have position excceed buffer length.

### ISSUE THREAD

**Issue by wangfengchao** [dmlc/xgboost#5958]
1. Why is Java API 1.x version backward incompatible?
2.1.x version of the training model, through the Java API 1.0 API when loading the model reported:
![image](https://user-images.githubusercontent.com/10843363/88887832-bfd79180-d26f-11ea-948a-0c1042ce8760.png)

**Comment by thvasilo** [comment]
Potential duplicate of #5863

**Comment by trivialfis** [comment]
This error is quite obscure.  Basically any error might lead to this one.

**Comment by trivialfis** [comment]
Not a maintainer for jvm package.  But what is Java API 1.x?
