### ISSUE TITLE
OS X build instruction to be updated.

### ISSUE THREAD

**Issue by lenguyenthedat** [dmlc/xgboost#596]
I think mainly because `brew install gcc --without-multilib` is now installing `gcc-5.2.0`, we don't need

  ```Makefile
  export CC  = gcc-4.9
  export CXX = g++-4.9
  ```

anymore.

**Comment by phunterlau** [comment]
@lenguyenthedat do you want to submit a PR for this change so it can be merged to the master? I still see someone has issues of building by following the old `build.md` .

**Comment by lenguyenthedat** [comment]
Sure, I will do a final test and open a PR! :+1:

**Comment by lenguyenthedat** [comment]
@phunterlau: I could not get the clang method to work on OS X El Capitan - after a few searches, it is probably related to http://apple.stackexchange.com/questions/193368/what-is-the-rootless-feature-in-el-capitan-really 

I will update a PR for the gcc version only - as it is probably the easiest way to do it right now.

**Comment by phunterlau** [comment]
@lenguyenthedat `build.sh` tries with OpenMP and if it is clang, `build.sh` will turn on `no_omp=1` and try again. Usually the 2nd try works with clang with no problem
