### ISSUE TITLE
Model returns different results for scipy sparse matrix and scipy.sparse.toarray()  numpy ndarray.

### ISSUE THREAD

**Issue by MankaranSingh** [dmlc/xgboost#5960]
I have a pipeLine that includes TfidfVectorizer AND XGBoost model.

```python
class Text2TfIdfTransformer(BaseEstimator):

    def __init__(self):
        self._model = TfidfVectorizer()
        pass

    def fit(self, df_x, df_y=None):
        df_x = df_x.apply(lambda x : clean_text(x))
        self._model.fit(df_x)
        return self

    def transform(self, df_x):
        return self._model.transform(df_x)

xgb_tf_idf = Pipeline(steps=[('tfidf',Text2TfIdfTransformer()),
                         ('xgboost', xgb.XGBClassifier(objective='multi:softmax', n_jobs=8))])
```

now, when I obtain intermediate tfidf result and pass  it to the model:

```python
vec = tfidf.transform(['include stdio h int main'])
arr = vec.toarray()

vec == arr                 # True

xgb_tf_idf .predict(vec)    !=     xgb_tf_idf .predict(arr)       
```

The predict proba method also differs and results are off by a lot. Am I doing something wrong or is this a bug ? 

Thanks

**Comment by trivialfis** [comment]
I remember solving a similar issue before.  `toarray()` returns a dense array with 0 filling missing values.  But for XGBoost 0 is valid value.  So when used with return np array, you need to specify `missing= 0` for XGBoost.

**Comment by MankaranSingh** [comment]
Thanks @trivialfis setting missing  = 0 solved the problem !

Closing the issue.
