### ISSUE TITLE
the xgboost4j get the differenet results when loading a model trained on python?

### ISSUE THREAD

**Issue by ChaosCY** [dmlc/xgboost#5967]
I have use xgboost=0.90 to train a model by python, but when I load the model file through xgboost4j, I got the different prediction, I have no idea why this happend. the maven pom.xml blow:
<dependency>
            <groupId>ml.dmlc</groupId>
            <artifactId>xgboost4j</artifactId>
            <version>0.90</version>
</dependency>
Even I change the version to 1.0+ the problem still appears. 
<dependency>
            <groupId>ml.dmlc</groupId>
            <artifactId>xgboost4j_2.12</artifactId>
            <version>1.0.0</version>
</dependency>
But when I setting the booster='dart', the problem disappear seemingly. I dont know what happend. thanks.

**Comment by hcho3** [comment]
@ChaosCY Can you post your code?
