### ISSUE TITLE
[RFC] 1.2.0 Release

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#5970]
Roadmap: #5734

We are about to release version 1.2.0 of XGBoost. In the next two weeks, we invite everyone to try out the release candidate (RC).

Feedback period: until the end of **August 21, 2020**. No new feature will be added to the release; only critical bug fixes will be added.

@dmlc/xgboost-committer

**Now available**

* **Python package**. RC2 available on PyPI. Try it out with the command
```
python3 -m pip install xgboost==1.2.0rc2
```

* **R package**. RC2 available from [the Releases section](https://github.com/dmlc/xgboost/releases/tag/v1.2.0rc2). Download the tarball file xgboost_1.2.0.1.tar.gz and run
```
R CMD INSTALL xgboost_1.2.0.1.tar.gz
```
[Rendered R manual](https://github.com/dmlc/xgboost/files/5012075/xgboost-manual.pdf)

* **JVM packages**. RC2 available from our Maven repository. Add XGBoost4J as dependency to your Java application.

<details><summary>Show instructions (Maven/SBT)</summary>
<p>

Maven
```xml
<dependencies>
  ...
  <dependency>
      <groupId>ml.dmlc</groupId>
      <artifactId>xgboost4j_2.12</artifactId>
      <version>1.2.0-RC2</version>
  </dependency>
  <dependency>
      <groupId>ml.dmlc</groupId>
      <artifactId>xgboost4j-spark_2.12</artifactId>
      <version>1.2.0-RC2</version>
  </dependency>
</dependencies>

<repositories>
  <repository>
    <id>XGBoost4J Release Repo</id>
    <name>XGBoost4J Release Repo</name>
    <url>https://s3-us-west-2.amazonaws.com/xgboost-maven-repo/release/</url>
  </repository>
</repositories>
```

SBT
```scala
libraryDependencies ++= Seq(
  "ml.dmlc" %% "xgboost4j" % "1.2.0-RC2",
  "ml.dmlc" %% "xgboost4j-spark" % "1.2.0-RC2"
)
resolvers += ("XGBoost4J Release Repo"
              at "https://s3-us-west-2.amazonaws.com/xgboost-maven-repo/release/")
```
</p>
</details>

Starting from 1.2.0, XGBoost4J-Spark supports training with NVIDIA GPUs. To enable this capability, download artifacts suffixed with `-gpu`, as follows:

<details><summary>Show instructions (Maven/SBT)</summary>
<p>

Maven
```xml
<dependencies>
  ...
  <dependency>
      <groupId>ml.dmlc</groupId>
      <artifactId>xgboost4j-gpu_2.12</artifactId>
      <version>1.2.0-RC2</version>
  </dependency>
  <dependency>
      <groupId>ml.dmlc</groupId>
      <artifactId>xgboost4j-spark-gpu_2.12</artifactId>
      <version>1.2.0-RC2</version>
  </dependency>
</dependencies>

<repositories>
  <repository>
    <id>XGBoost4J Release Repo</id>
    <name>XGBoost4J Release Repo</name>
    <url>https://s3-us-west-2.amazonaws.com/xgboost-maven-repo/release/</url>
  </repository>
</repositories>
```

SBT
```scala
libraryDependencies ++= Seq(
  "ml.dmlc" %% "xgboost4j-gpu" % "1.2.0-RC2",
  "ml.dmlc" %% "xgboost4j-spark-gpu" % "1.2.0-RC2"
)
resolvers += ("XGBoost4J Release Repo"
              at "https://s3-us-west-2.amazonaws.com/xgboost-maven-repo/release/")
```
</p>
</details>

**Deprecation notices**
* Starting from this release, XGBoost requires **Python 3.6** or later.
* **CUDA 10.0** or later is now required. (For Windows platform, we require CUDA 10.1.)
* XGBoost4J and XGBoost4J-Spark have fully transitioned to **Spark 3.0.0**. Therefore, **Scala 2.12** is now required, and Scala 2.11 is no longer supported.

TODOs
- [x] Create a new branch release_1.2.0.
- [x] Create Python wheels and upload to PyPI.
- [x] Upload RC1 to our Maven repo.
- [x] Create a tarball for the R package and upload to the Releases section
- [ ] Write release note

## PRs that are back ported to release branch.
- [x] https://github.com/dmlc/xgboost/pull/5980
- [x] https://github.com/dmlc/xgboost/pull/5974
- [x] #5989
- [x] https://github.com/dmlc/xgboost/pull/5986

**Comment by trivialfis** [comment]
Could you please add some docs around how to do each of the listed step as XGBoost's maintainer? (so any XGBoost specific issue, like pypi account, approval etc).

**Comment by hcho3** [comment]
@trivialfis Here are the steps for Python package:

1. Create a new release branch.
2. Push a commit to the branch to update the version number to RC1.
3. Wait until the CI system builds artifacts. Currently, we use Jenkins and Travis CI to build Windows, Mac, and Linux binaries. The binaries are uploaded to https://s3-us-west-2.amazonaws.com/xgboost-nightly-builds/list.html.
4. Now upload the binary wheels using the `twine` module: `python -m twine upload *.whl`. This will require PyPI credentials.

**Comment by trivialfis** [comment]
Got it.  Thanks.

**Comment by hcho3** [comment]
I spent a fair amount of effort to automate building release binaries. What's not automated is to upload them to distribution channels (PyPI, CRAN, Maven Central etc).

**Comment by hcho3** [comment]
TODO: Investigate whether GPU algorithm can be enabled in the JAR artifact. If the JAR file contains CUDA code, will it work on a cluster without a GPU? I will need to test and find out.

**Comment by Craigacp** [comment]
That depends on how the library loading is done. If the GPU binary tries to dynamically load CUDA libraries then you'll get an [UnsatisfiedLinkError](https://docs.oracle.com/en/java/javase/14/docs/api/java.base/java/lang/UnsatisfiedLinkError.html) out of the native loader. You could probe for the presence of the CUDA libraries and then conditionally load the GPU binary, otherwise load the CPU one, but that's tricky (potentially it could catch the UnsatisfiedLinkError, log it, and then say falling back to CPU, but it could fail with UnsatisfiedLinkError for other reasons e.g. lack of OpenMP, which would be confusing). This will blow up the JAR size as you'd need two copies of everything. In most Java projects the CPU and GPU artifacts are different (e.g. https://search.maven.org/search?q=g:com.microsoft.onnxruntime), but this can cause issues in downstream builds as at some point a developer has to choose whether they want a CPU or GPU binary. Fortunately in production you can just drop the GPU one higher up the classpath and it'll load just fine.

**Comment by trivialfis** [comment]
There's a stub library of CUDA linked into XGBoost so link time error should not happen.  But I agree that we should have better tests.

**Comment by hcho3** [comment]
@Craigacp The GPU algorithm uses NCCL to perform allreduce, and including the NCCL library in the JAR file increases its size to 150 MB. Does Maven Central accept this large artifact? cc @CodingCat @sperlingxx

**Comment by Craigacp** [comment]
It does. For example libtensorflow jni GPU for 1.15 is 355 MB.

**Comment by hcho3** [comment]
@Craigacp @wbo4958 Here are the JAR files I built with GPU algorithm enabled:
* https://xgboost-examples.s3-us-west-2.amazonaws.com/xgboost4j_2.12-1.2.0-RC1.jar (142 MB)
* https://xgboost-examples.s3-us-west-2.amazonaws.com/xgboost4j-spark_2.12-1.2.0-RC1.jar (264 KB)

To install:
```
mvn install:install-file -Dfile=./xgboost4j_2.12-1.2.0-RC1.jar -DgroupId=ml.dmlc \
    -DartifactId=xgboost4j_2.12 -Dversion=1.2.0-RC1 -Dpackaging=jar
mvn install:install-file -Dfile=./xgboost4j-spark_2.12-1.2.0-RC1.jar -DgroupId=ml.dmlc \
    -DartifactId=xgboost4j-spark_2.12 -Dversion=1.2.0-RC1 -Dpackaging=jar
```

**Comment by Craigacp** [comment]
The xgboost4j_2.12-1.2.0-RC1.jar loads just fine on Oracle Linux 7 (roughly equivalent to RHEL/CentOS 7). The error message when you try to run on GPU could probably do with prettying up a little though:
```jshell> var booster = XGBoost.train(dmatrix, params, 2, Collections.emptyMap(), null, null);
|  Exception ml.dmlc.xgboost4j.java.XGBoostError: [22:26:24] /workspace/src/gbm/gbtree.cc:459: Check failed: common::AllVisibleGPUs() >= 1 (0 vs. 1) : No visible GPU is found for XGBoost.
Stack trace:
  [bt] (0) /tmp/libxgboost4j12036788363652521596.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x57) [0x7fc89b2dec37]
  [bt] (1) /tmp/libxgboost4j12036788363652521596.so(xgboost::gbm::GBTree::GetPredictor(xgboost::HostDeviceVector<float> const*, xgboost::DMatrix*) const+0x531) [0x7fc89b3c0a91]
  [bt] (2) /tmp/libxgboost4j12036788363652521596.so(xgboost::gbm::GBTree::PredictBatch(xgboost::DMatrix*, xgboost::PredictionCacheEntry*, bool, unsigned int)+0x32) [0x7fc89b3c0cc2]
  [bt] (3) /tmp/libxgboost4j12036788363652521596.so(xgboost::LearnerImpl::UpdateOneIter(int, std::shared_ptr<xgboost::DMatrix>)+0x2c1) [0x7fc89b3f1521]
  [bt] (4) /tmp/libxgboost4j12036788363652521596.so(XGBoosterUpdateOneIter+0x55) [0x7fc89b2e1785]
  [bt] (5) [0x7fc960a8a5d7]


|        at XGBoostJNI.checkCall (XGBoostJNI.java:48)
|        at Booster.update (Booster.java:180)
|        at XGBoost.trainAndSaveCheckpoint (XGBoost.java:202)
|        at XGBoost.train (XGBoost.java:284)
|        at XGBoost.train (XGBoost.java:112)
|        at XGBoost.train (XGBoost.java:83)```

**Comment by hcho3** [comment]
@Craigacp Did you set `tree_method='gpu_hist'`?

**Comment by Craigacp** [comment]
@hcho3 yes, I intentionally set it to use `gpu_hist` to see what the failure mode was on a CPU only machine. I admit I didn't try using the standard CPU algorithm in my quick test.

**Comment by hcho3** [comment]
@Craigacp No, you have to explicitly opt into `gpu_hist`.

**Comment by hcho3** [comment]
Thanks, we can maybe clarify in the message about GPU being unavailable.

**Comment by trivialfis** [comment]
@hcho3 All blocking PRs are merged into master branch.  I will back port  them today.

**Comment by trivialfis** [comment]
Back port PR: https://github.com/dmlc/xgboost/pull/6002

**Comment by trivialfis** [comment]
>  I will back port them today. 

Merged.

**Comment by hcho3** [comment]
Great! I'm preparing RC2 now.

**Comment by hcho3** [comment]
RC2 is now up. I've also uploaded JVM packages `xgboost4j-gpu` and `xgboost4j-spark-gpu` where the GPU algorithm is enabled.

**Comment by JohnZed** [comment]
Maybe change the phrasing to "CUDA 10.0 *or later* is required"? Same with python version?

**Comment by hcho3** [comment]
@JohnZed Fixed.

**Comment by hcho3** [comment]
1.2.0 is now on CRAN.
