### ISSUE TITLE
Maping min_child_weight of xgboost with min_sum_hessian_in_leaf of LightGBM

### ISSUE THREAD

**Issue by QuantHao** [dmlc/xgboost#5987]
Hi, all

When I read both documentation of xgboost and LightGBM, I am very confused about min_child_weight parameter. Based on @trivialfis answer in [#5976 ](https://github.com/dmlc/xgboost/issues/5976), min_child_weight in xgboost represents accumulated Hessian for each leaf, which literally means number of sample for [rmse objective](https://stats.stackexchange.com/a/323459/248610).

However, I find that [min_sum_hessian_in_leaf](https://lightgbm.readthedocs.io/en/latest/Parameters.html#min_sum_hessian_in_leaf) (alias of min_child_weight) in LightGBM is set to 1e-3 as default, while [min_data_in_leaf](https://lightgbm.readthedocs.io/en/latest/Parameters.html#min_data_in_leaf) (alias of min_child_samples) is set to 20 as default.

To me, it seems that min_child_weight in xgboost is a mapping of min_data_in_leaf instead of min_sum_hessian_in_leaf in LightGBM. May I ask is my understanding correct? Thanks so much.

**Comment by QuantHao** [comment]
@thvasilo also mentions this mapping issue at [#5444 ](https://github.com/dmlc/xgboost/issues/5444). Any thoughts?

**Comment by hcho3** [comment]
No, the `min_child_weight` in XGBoost maps to `min_sum_hessian_in_leaf` in LightGBM. It is currently not possible to set the minimum number of samples per node in XGBoost.

For the `reg:squarederror` objective, the Hessian sum happens to match the number of samples, but this equality generally does not hold for other objectives.
