### ISSUE TITLE
plotting my xgboost tree doesn't correspond to feature importances?

### ISSUE THREAD

**Issue by zahs123** [dmlc/xgboost#6000]
my feature importance report shows that the top one is a one hot encoded variable. However when i plot the xgboost model the first node in the tree is not this variable. in fact i cannot see them anywhere. 

what exactly does plot_tree plot? 

e.g.

```
xgb.plot_tree(loaded_model)
plt.show()

```

is it possible to visualize the tree including the one hot encoded variables?

**Comment by hcho3** [comment]
The feature importance measure is over the entire tree ensemble. Your ensemble most likely has multiple trees in it.
