### ISSUE TITLE
Xgboost runs on single core

### ISSUE THREAD

**Issue by Tutufa** [dmlc/xgboost#601]
Hi, Im having a very strange problem,

with this code Im trying to create xgb model:

```python
dtrain = xgboost.DMatrix(x_train, label=y_train)
dtest = xgboost.DMatrix(x_test, label=y_test)
evallist  = [(dtest,'eval'), (dtrain,'train')]

num_round = 100
param = {'bst:max_depth':15, 
         'bst:eta':1, 
         'silent':1, 
         'objective':'multi:softprob',
         'num_class':38}
param['nthread'] = 14
plst = param.items()
plst += [('eval_metric', 'mlogloss')]

bst = xgboost.train( plst, dtrain, num_round, evallist )
```
despite I set nthreads to 14, it uses only one core and idk why

I run it on server through ipython notebook

**Comment by phunterlau** [comment]
do you run xgboost in Mac OS X? if yes, please refer to (python-package/build_trouble_shooting.md) section `Mac OS X (specific)` trouble 0. In short, 

```
clang LLVM compiler on Mac OS X from Xcode doesn't support OpenMP multi-thread. An alternative choice is installing homebrew http://brew.sh/ and brew install g++-5 which provides multi-thread OpenMP support.
```

**Comment by Tutufa** [comment]
@phunterlau no, server runs on freebsd (-:

**Comment by phunterlau** [comment]
@Tutufa that looks like a new situation. Can you check if you have OpenMP and what is `which g++`?

**Comment by why-not** [comment]
XGBoost runs in a single core for me after setting nthreads=-1. I have a 8 core machine and htop shows only one core engaged throughout the run. Let me know how to debug this

So far I installed Xgboost from the source following the steps, this I did after the pip3 install failed to run on multiple cores... 

My Environment: gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10)

Full gcc -v output. 

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.10' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10)

**Comment by hcho3** [comment]
@why-not Can you run the following example and see if all cores are used?
```cpp
int main(void) {
  const int N = 1000000000;
  int sum[8] = {0};
  #pragma omp parallel for num_threads(8)
  for (int i = 0; i < N; ++i) {
    ++sum[omp_get_thread_num()];
  }
  for (int i = 0; i < 8; ++i) {
    std::cout << sum[i] << std::endl;
  }
  return 0;
}
```
Compile it by running `gcc -o main main.cc -fopenmp -O3 -msse2`.

**Comment by hcho3** [comment]
@why-not You should set `nthread=0` to use all available cores.
