### ISSUE TITLE
[CI] Debug failing tests in the master branch

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#6014]
* https://xgboost-ci.net/blue/organizations/jenkins/xgboost/detail/master/425/pipeline/268
* https://xgboost-ci.net/blue/organizations/jenkins/xgboost/detail/master/425/pipeline/272
* https://travis-ci.org/github/dmlc/xgboost/jobs/717683561

**Comment by hcho3** [comment]
I'll try to reproduce https://travis-ci.org/github/dmlc/xgboost/jobs/717683561 on my Macbook.

**Comment by trivialfis** [comment]
Let's see how https://github.com/dmlc/xgboost/pull/6009 is holding up.

**Comment by hcho3** [comment]
@trivialfis Did #6020 fix the failing test in Travis CI?

**Comment by hcho3** [comment]
#6024 should fix the segfault after GPU tests.
