### ISSUE TITLE
Add tests for dtreeviz

### ISSUE THREAD

**Issue by trivialfis** [dmlc/xgboost#6015]
https://github.com/dmlc/xgboost/pull/6013

**Comment by hcho3** [comment]
To new contributors: If you're reading this and interested in writing the test, please comment here. Feel free to ping me with questions. I am available for help.

**Comment by puranjaymohan** [comment]
Hi @hcho3 I would love to work on this

**Comment by hcho3** [comment]
Great! I'm going to assign this issue to you. You should start by reading instructions in https://xgboost.readthedocs.io/en/latest/contrib/unit_tests.html#python-package-pytest. We use pytest to test Python code.

**Comment by puranjaymohan** [comment]
@hcho3 Hi! Sorry for not responding in the last ten days.
I have read the article mentioned by you and also found that dtreeviz is a visualization library.
Please tell me what exactly has to be tested, I mean which functions or something like that.
Thanks

**Comment by hcho3** [comment]
@puranjaymohan I suggest you start with https://github.com/parrt/dtreeviz/blob/master/notebooks/dtreeviz_xgboost_visualisations.ipynb. Aim to extract commands from this notebook and create a standalone Python script that can be automatically run by a test farm (CI).

**Comment by hcho3** [comment]
@puranjaymohan Any updates? Would you like some help?

**Comment by trivialfis** [comment]
Closing due to stalled.  Besides, I think we will try to reduce the number of dependencies in our tests.
