### ISSUE TITLE
'tree_method': 'hist'  is faster  than 'tree_method': 'gpu_hist'

### ISSUE THREAD

**Issue by thinker111** [dmlc/xgboost#6025]
Hi, community

     When I run the following code, the training time is weird since it costs 0.0189s when using 'hist' ,while costing 0.1227s when using 'gpu_hist'.

More info:
OS: win10, anaconda3,RTX2060
And when I run /benchmark/benchmark_tree.py, the training time costs 12.15s when tree_method=gpu_hist ,while costs  30.77s when tree_method=hist

Thanks
```
import sklearn.datasets
import xgboost as xgb
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
import time
from sklearn import preprocessing
X, y = sklearn.datasets.fetch_openml(data_id=31, return_X_y=True)#Arrary
y = preprocessing.LabelEncoder().fit_transform(y)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1 )#, random_state=1 random_state:default=None

start_time=time.time()
param = {'objective': 'multi:softmax', # Specify multiclass classification
         'num_class': 2, # Number of possible output classes
         'tree_method': 'hist' # Use GPU accelerated algorithm
         }

dtrain = xgb.DMatrix(X_train, label=y_train)
dtest = xgb.DMatrix(X_test, label=y_test)
gpu_res = {} 
tmp = time.time()
xgb.train(param, dtrain,  evals=[(dtest, 'test')], evals_result=gpu_res)
print('Total time =%.4f'%(time.time()-start_time))
```

using hist:
[0]     test-merror:0.30800
[1]     test-merror:0.26400
[2]     test-merror:0.26800
[3]     test-merror:0.26000
[4]     test-merror:0.24800
[5]     test-merror:0.23600
[6]     test-merror:0.23600
[7]     test-merror:0.24000
[8]     test-merror:0.24800
[9]     test-merror:0.24400
Total time =0.0189

using gpu_hist:
[0]     test-merror:0.30800
[1]     test-merror:0.26400
[2]     test-merror:0.27200
[3]     test-merror:0.26400
[4]     test-merror:0.25200
[5]     test-merror:0.25600
[6]     test-merror:0.26000
[7]     test-merror:0.26800
[8]     test-merror:0.25600
[9]     test-merror:0.25600
Total time =0.1227

**Comment by RAMitchell** [comment]
Speedup from GPU is only expected on larger datasets.

**Comment by thinker111** [comment]
Thanks,bro!
