### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'feature_names'

### ISSUE THREAD

**Issue by Rupam07** [dmlc/xgboost#6039]
Created an xgboost model saved it in a pickle file and loading it to predict on a new dataset with the same features. 

Cannot perform prediction on the new data gives an error: 

AttributeError: 'DataFrame' object has no attribute 'feature_names'

Code for reference:

num_round = 7000
param_grid = {'tree_method': 'gpu_hist', 
              'max_depth': 3, 
              'learning_rate': 0.01,
              'subsample':0.8,
              'colsample_bytree':0.8,
              'min_child_weight':1,
              'alpha':5,
              'predictor':'gpu_predictor'}
param_grid['nthread'] = 10

dtrain = xgb.DMatrix(trans_train_x, label=train_y)
dtest = xgb.DMatrix(trans_valid_x, label=valid_y)

bst = xgb.train(param_grid, dtrain, num_round)

with open("model.pkl", "wb") as fp:
    pickle.dump(bst, fp)

The trans_train_x and trans_valid_x are one hot encoded train and validation datasets.

**Comment by trivialfis** [comment]
Could you please provide a snippet that I can run?  The data can be simply something from `sklearn.datasets`.

**Comment by Rupam07** [comment]
Sure thank you for getting back. 
We can try using  `sklearn.datasets.fetch_california_housing`  as an example dataset for running the code. 

Also available at : http://lib.stat.cmu.edu/datasets/

**Comment by trivialfis** [comment]
Thanks for replying.  But could you please provide the code that I can run and see the error.  I tried to fill in the blanks but didn't go anywhere.   california_housing is a numeric dataset, which means there's not categorical column for encoding.

If you can't provide the script, can you please post the error backtrace and XGBoost version?

Lastly, this is the result of me filling in the blanks:
``` python
import pickle
import xgboost as xgb
from sklearn.datasets import fetch_california_housing
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.model_selection import train_test_split

train_x, train_y = fetch_california_housing(return_X_y=True, as_frame=True)
print(train_x)
num_round = 7

train_x, valid_x, train_y, valid_y = train_test_split(train_x,
                                                      train_y,
                                                      test_size=0.2,
                                                      random_state=1234)

categorical_cols = ['MedInc',  'HouseAge',  'AveRooms', 'AveBedrms']
le = LabelEncoder()

train_x[categorical_cols] = train_x[categorical_cols].astype(int)  # force it to be categorical.
print(train_x)

train_x[categorical_cols] = train_x[categorical_cols].apply(
    lambda col: le.fit_transform(col))
valid_x[categorical_cols] = valid_x[categorical_cols].apply(
    lambda col: le.fit_transform(col))

ohe = OneHotEncoder(handle_unknown='ignore')

trans_train_x = ohe.fit_transform(train_x)
trans_valid_x = ohe.transform(valid_x)

param_grid = {
    'tree_method': 'gpu_hist',
    'max_depth': 3,
    'learning_rate': 0.01,
    'subsample': 0.8,
    'colsample_bytree': 0.8,
    'min_child_weight': 1,
    'alpha': 5,
    'predictor': 'gpu_predictor'
}
param_grid['nthread'] = 10

dtrain = xgb.DMatrix(trans_train_x, label=train_y)
dtest = xgb.DMatrix(trans_valid_x, label=valid_y)

bst = xgb.train(param_grid, dtrain, num_round)

with open("model.pkl", "wb") as fp:
    pickle.dump(bst, fp)
```

**Comment by Rupam07** [comment]
Sorry, it is a company data and code so cannot share more than what I included above but the traceback for the error is here: 
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-21-507a0aa82c90> in <module>()
----> 1 predictions = prediction(test)
      2 predictions

3 frames
<ipython-input-20-f11f9daeca44> in prediction(df)
      4     with open("/content/drive/My Drive/JNJ/JNJLTP-Mars-v2.pkl", "rb") as fp:
      5         model = pickle.load(fp)
----> 6     predictions = model.predict(df)
      7     return predictions

/usr/local/lib/python3.6/dist-packages/xgboost/core.py in predict(self, data, output_margin, ntree_limit, pred_leaf, pred_contribs, approx_contribs, pred_interactions, validate_features)
   1282 
   1283         if validate_features:
-> 1284             self._validate_features(data)
   1285 
   1286         length = c_bst_ulong()

/usr/local/lib/python3.6/dist-packages/xgboost/core.py in _validate_features(self, data)
   1673         else:
   1674             # Booster can't accept data with different feature names
-> 1675             if self.feature_names != data.feature_names:
   1676                 dat_missing = set(self.feature_names) - set(data.feature_names)
   1677                 my_missing = set(data.feature_names) - set(self.feature_names)

/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py in __getattr__(self, name)
   5272             if self._info_axis._can_hold_identifiers_and_holds_name(name):
   5273                 return self[name]
-> 5274             return object.__getattribute__(self, name)
   5275 
   5276     def __setattr__(self, name: str, value) -> None:

AttributeError: 'DataFrame' object has no attribute 'feature_names'

Also, the xgboost version I am using is: xgboost==0.90. Also, can we may be try with a dataset which has categorical columns because my data is inclusive of numerical as well as categorical columns and a target variable which I am predicting

**Comment by trivialfis** [comment]
Got it.  Please use `DMatrix` for prediction.  If you want to pass the data directly, use `inplace_predict`.

**Comment by Rupam07** [comment]
So, the prediction function I use to predict the new data using the model is: 
*************************************************************************************************
def prediction(df):
    df = df.copy()
    with open("model.pkl", "rb") as fp:
        model = pickle.load(fp)
    predictions = model.predict(df)
    return predictions

predictions = prediction(test)
predictions
This function `prediction` throws the error
*************************************************************************************************
Whereas for intial predictions on validation data the code used is:
*************************************************************************************************
predictions = bst.predict(dtest)
mean_squared_error(valid_y, predictions)
*************************************************************************************************
where the **dtest** variable is a `DMatrix`

**Comment by trivialfis** [comment]
There are 2 ways for predictions:
- First, using `booster.predict`
``` python
df = pd.DataFrame()
dtest = xgboost.DMatrix(df)
predt_vector = booster.predict(dtest)
```

- Second, using `booster.inplace_predict`:
``` python
df = pd.DataFrame()
predt_vector = booster.predict(df)
```

**Comment by trivialfis** [comment]
Sorry, corrected a typo in above snippet.

**Comment by Rupam07** [comment]
Okay what should I change in the prediction function I create in order to predict a new dataset?
Since my trained model is pickled and I am currently using `model.predict(df)` which throws an error

def prediction(df):
df = df.copy()
with open("model.pkl", "rb") as fp:
model = pickle.load(fp)
**predictions = model.predict(df)**
return predictions

**Comment by Rupam07** [comment]
The initial prediction on the validation dataset using the following code works perfectly fine and gives the mean_squared_error as well: 

`predictions = bst.predict(dtest)`
`mean_squared_error(valid_y, predictions)`

The error is when I use the trained model pickle file and try predicting using the same on a new dataset

**Comment by trivialfis** [comment]
Modifying your snippet:

``` python
def prediction(df):
    df = df.copy()
    with open("model.pkl", "rb") as fp:
        model = pickle.load(fp)
        dtest = xgboost.DMatrix(df)
        predictions = model.predict(dtest)
        return predictions
```

or

``` python
def prediction(df):
    df = df.copy()
    with open("model.pkl", "rb") as fp:
        model = pickle.load(fp)
        predictions = model.inplace_predict(df)
        return predictions
```

**Comment by trivialfis** [comment]
Also please use normal `booster.save_model` instead of pickle when possible.  Pickle file is not designed to be stable.

**Comment by Rupam07** [comment]
Ok so I used : 
def prediction(df):
    df = df.copy()
    with open("model.pkl", "rb") as fp:
        model = pickle.load(fp)
        dtest = xgb.DMatrix(df)
        predictions = model.predict(dtest)
        return predictions..astype("int")

And got the following error: 
ValueError                                Traceback (most recent call last)
<ipython-input-28-507a0aa82c90> in <module>()
----> 1 predictions = prediction(test)
      2 predictions

2 frames
<ipython-input-27-5602fcb7e313> in prediction(df)
      5     with open("model.pkl", "rb") as fp:
      6         model = pickle.load(fp)
----> 7     dtest = xgb.DMatrix(df)
      8     predictions = model.predict(dtest)
      9     **return predictions.astype("int")**

/usr/local/lib/python3.6/dist-packages/xgboost/core.py in __init__(self, data, label, missing, weight, silent, feature_names, feature_types, nthread)
    378         data, feature_names, feature_types = _maybe_pandas_data(data,
    379                                                                 feature_names,
--> 380                                                                 feature_types)
    381 
    382         data, feature_names, feature_types = _maybe_dt_data(data,

/usr/local/lib/python3.6/dist-packages/xgboost/core.py in _maybe_pandas_data(data, feature_names, feature_types)
    237         msg = """DataFrame.dtypes for data must be int, float or bool.
    238                 Did not expect the data types in fields """
--> 239         raise ValueError(msg + ', '.join(bad_fields))
    240 
    241     if feature_names is None:

ValueError: DataFrame.dtypes for data must be int, float or bool.
                Did not expect the data types in fields Sales Document Type, Product Hierarchy, Plant Code, Shipping Receiving Point, Customer Purchase Order Type, Sales Document Item Category, Created Date_DayOfMonth, Created Date_DayOfWeek, Created Date_WeekOfYear, Created Date_MonthOfYear, Requested Delivery Date_DayOfMonth, Requested Delivery Date_DayOfWeek, Requested Delivery Date_WeekOfYear, Requested Delivery Date_MonthOfYear, ScenarioName

**Comment by trivialfis** [comment]
So the error message said data type should be int, float or bool.  Can you change it?

``` python
df = df.astype(float)
dtest = xgboost.DMatrix(df)
```

**Comment by Rupam07** [comment]
Sorry I know I am asking too many questions but I really need this thing to work and it is still throwing errors. 

I changed the df.astype(float) 

And the error it throws is :
ValueError: could not convert string to float: 'TA'

**Comment by trivialfis** [comment]
@Rupam07 That's an error from pandas instead of XGBoost I believe.  How did you train the model?  Why is your data containing string?

**Comment by Rupam07** [comment]
I converted all the categorical columns and strings values using one hot encoding but still showing this error there are not additional columns in the data in my knowledge. 

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-40-507a0aa82c90> in <module>()
----> 1 predictions = prediction(test)
      2 predictions

5 frames
<ipython-input-39-b9dc0aa3edb2> in prediction(df)
      1 def prediction(df):
      2     df = df.copy()
----> 3     df = df.astype(float)
     
/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py in astype(self, dtype, copy, errors)
   5696         else:
   5697             # else, only a single dtype is given
-> 5698             new_data = self._data.astype(dtype=dtype, copy=copy, errors=errors)
   5699             return self._constructor(new_data).__finalize__(self)
   5700 

/usr/local/lib/python3.6/dist-packages/pandas/core/internals/managers.py in astype(self, dtype, copy, errors)
    580 
    581     def astype(self, dtype, copy: bool = False, errors: str = "raise"):
--> 582         return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
    583 
    584     def convert(self, **kwargs):

/usr/local/lib/python3.6/dist-packages/pandas/core/internals/managers.py in apply(self, f, filter, **kwargs)
    440                 applied = b.apply(f, **kwargs)
    441             else:
--> 442                 applied = getattr(b, f)(**kwargs)
    443             result_blocks = _extend_blocks(applied, result_blocks)
    444 

/usr/local/lib/python3.6/dist-packages/pandas/core/internals/blocks.py in astype(self, dtype, copy, errors)
    623             vals1d = values.ravel()
    624             try:
--> 625                 values = astype_nansafe(vals1d, dtype, copy=True)
    626             except (ValueError, TypeError):
    627                 # e.g. astype_nansafe can fail on object-dtype of strings

/usr/local/lib/python3.6/dist-packages/pandas/core/dtypes/cast.py in astype_nansafe(arr, dtype, copy, skipna)
    895     if copy or is_object_dtype(arr) or is_object_dtype(dtype):
    896         # Explicit copy, or required since NumPy can't view from / to object.
--> 897         return arr.astype(dtype, copy=True)
    898 
    899     return arr.view(dtype)

ValueError: could not convert string to float: 'TA'

**Comment by trivialfis** [comment]
> I converted all the categorical columns and strings values using one hot encoding but still showing this error

Did you verify it before calling `df.astype(float)`?  By looking into the data?  Sometimes one might make some small bugs like:

``` python

original_df = pd.DataFrame()
encoded = Encoder().fit(original_df)  # <- encoded is the correct dataframe

original_df = original_df.astype(float) # <- using the wrong dataframe here
```

Or there's more categorical data you didn't know about.  Best thing you can do is actually looking into the data by `print`, or do
``` python
for i in range(df.shape[1]):
    print(df.iloc[:, i].dtype)
```

**Comment by Rupam07** [comment]
I think it is the second case that you mentioned that there are more categorical data that I might not know about. So, for the new data that I have to predict on and for which I would use the trained model for predictions. How can I match the features in the trained model and the new data that has additional features as well which I might not know of ? 
So that I can avoid this error

**Comment by trivialfis** [comment]
It's your data, you can verify it or write a script to verify it.

**Comment by trivialfis** [comment]
Closing as the original issue is resolved.  Feel free to open new ones when needed. ;-)

**Comment by Rupam07** [comment]
Thank you for the help 👍
