### ISSUE TITLE
ValueError: feature_names mismatch

### ISSUE THREAD

**Issue by Rupam07** [dmlc/xgboost#6043]
This error is in continuation to the issue #6039 and it throws valueerror after encoding the string and categorical values with one hot encoding in the test dataset. 
Please help me with the same. 

I am building a model and then saving the model to pickle file and now after the save is complete I use it to predict new data. Converting the test data using one hot encoding and then predicting using the same

**Comment by trivialfis** [comment]
So can you match the feature names?

**Comment by Rupam07** [comment]
Yes the feature names are all in the same order and they do match in both test and train data

**Comment by hcho3** [comment]
Try passing `validate_features=False` option to the `predict()` function.

**Comment by Rupam07** [comment]
That worked. Thank you for the help @hcho3 and @trivialfis.

Can you please explain @hcho3 why the error occurred before and how did this change solve it?

**Comment by hcho3** [comment]
I think there is a mismatch in the feature names. You can check by printing out the training and test data matrices.

**Comment by Rupam07** [comment]
So, I check and the train dataset has one additional feature which is the target variable and this is the only change. Also does `validate_features=False` affect the prediction results? Like would the prediction results still be accurate enough with the change?

**Comment by hcho3** [comment]
You should try to match feature names to avoid any potential mistakes, since disabling the name check may accidentally cause the predictor to use wrong features.

> So, I check and the train dataset has one additional feature which is the target variable and this is the only change. 

Did you remove the target variable from the training data matrix? If not, you'll get wrong results silently. Since you were getting an error about mismatched feature names before, it appears that you did not remove the target variable from the data matrix. You should do something like
```
target = df['target']
data = df.drop(columns=['target'])  # Remove the target variable from data matrix
dtrain = xgb.DMatrix(data, label=target) # Create the DMatrix object
```

**Comment by Rupam07** [comment]
So, I did remove the target variable from while training the model 
train_x -> training dataset 

train_y = train_x.pop('target')
train_x, valid_x, train_y, valid_y = train_test_split(train_x, train_y, test_size=0.2, random_state=1234)

categorical_cols = ['a','b','c','d','e','f','g']
le = LabelEncoder()

train_x[categorical_cols] = train_x[categorical_cols].apply(lambda col: le.fit_transform(col))   
valid_x[categorical_cols] = valid_x[categorical_cols].apply(lambda col: le.fit_transform(col))   

ohe = OneHotEncoder(handle_unknown='ignore')

trans_train_x = ohe.fit_transform(train_x)
trans_valid_x = ohe.transform(valid_x)

dtrain = xgb.DMatrix(trans_train_x, label=train_y)
dtest = xgb.DMatrix(trans_valid_x, label=valid_y)

bst = xgb.train(param_grid, dtrain, num_round)

predictions = bst.predict(dtest)
mean_squared_error(valid_y, predictions)

with open("model.pkl", "wb") as fp:
    pickle.dump(bst, fp)

**Comment by Rupam07** [comment]
This is the function that I use with the above pickled model for making predictions on a new dataset with same set of features excluding the target variable.

def prediction(df):
   with open("model.pkl", "rb") as fp:
        model = pickle.load(fp)
    df = df.astype(float)
    dtest = xgb.DMatrix(df)
    predictions = model.predict(dtest,validate_features=False)
    return predictions

**Comment by hcho3** [comment]
Can you print the name of features in both `dtrain` and `dtest`? You can print `dtrain.feature_names` and `dtest.feature_names`.

**Comment by Rupam07** [comment]
Sure, this is the result:

testf = dtest.feature_names
trainf = dtrain.feature_names 

testf == trainf

Result: True

**Comment by hcho3** [comment]
Hmm, can you post the error message from the feature_names mismatched error? I have no idea why you'd get that error.

**Comment by Rupam07** [comment]
So, when I print the `dtest.feature_names` from the `prediction()` function and compare it with the testf and trainf feature it shows False 

dtestf = dtest.feature_names
dtestf == testf
`False`
dtestf == trainf
`False`

Can that be the reason this error is occuring?

**Comment by hcho3** [comment]
Indeed, that is why the error is occurring. Please modify the feature names of `dtest` from the `prediction()` function.
