### ISSUE TITLE
Investigate a viable path to support distributed training on Windows

### ISSUE THREAD

**Issue by zhouyanggang** [dmlc/xgboost#6049]
The log information of the program is as follows:

Tracker started, with env={DMLC_NUM_SERVER=0, DMLC_TRACKER_URI=10.72.55.58, DMLC_TRACKER_PORT=9091, DMLC_NUM_WORKER=1}
11:17:45 363 |- INFO Logging - Starting job: foreachPartition at XGBoost.scala:604
11:17:45 364 |- INFO Logging - Got job 4 (foreachPartition at XGBoost.scala:604) with 1 output partitions
11:17:45 364 |- INFO Logging - Final stage: ResultStage 6 (foreachPartition at XGBoost.scala:604)
11:17:45 364 |- INFO Logging - Parents of final stage: List()
11:17:45 365 |- INFO Logging - Missing parents: List()
11:17:45 365 |- INFO Logging - Submitting ResultStage 6 (MapPartitionsRDD[35] at mapPartitions at XGBoost.scala:489), which has no missing parents
11:17:45 398 |- INFO Logging - Block broadcast_9 stored as values in memory (estimated size 46.9 KiB, free 1995.7 MiB)
11:17:45 399 |- INFO Logging - Block broadcast_9_piece0 stored as bytes in memory (estimated size 20.9 KiB, free 1995.7 MiB)
11:17:45 400 |- INFO Logging - Added broadcast_9_piece0 in memory on DESKTOP-L9UBSFG:51851 (size: 20.9 KiB, free: 1996.1 MiB)
11:17:45 400 |- INFO Logging - Created broadcast 9 from broadcast at DAGScheduler.scala:1200
11:17:45 401 |- INFO Logging - Submitting 1 missing tasks from ResultStage 6 (MapPartitionsRDD[35] at mapPartitions at XGBoost.scala:489) (first 15 tasks are for partitions Vector(0))
11:17:45 401 |- INFO Logging - Adding task set 6.0 with 1 tasks
11:17:45 401 |- INFO Logging - Added task set TaskSet_6.0 tasks to pool test
11:17:45 402 |- INFO Logging - Starting task 0.0 in stage 6.0 (TID 206, DESKTOP-L9UBSFG, executor driver, partition 0, PROCESS_LOCAL, 7738 bytes)
11:17:45 402 |- INFO Logging - Running task 0.0 in stage 6.0 (TID 206)
11:17:45 417 |- INFO Logging - Found block rdd_12_0 locally
11:17:45 436 |- INFO Logging - Code generated in 10.9126 ms
11:17:45 949 |- INFO Logging - Block rdd_35_0 stored as values in memory (estimated size 584.0 B, free 1995.7 MiB)
11:17:45 950 |- INFO Logging - Added rdd_35_0 in memory on DESKTOP-L9UBSFG:51851 (size: 584.0 B, free: 1996.1 MiB)
11:17:45 967 |- INFO Logging - 1 block locks were not released by TID = 206:
[rdd_35_0]
11:17:45 968 |- INFO Logging - Finished task 0.0 in stage 6.0 (TID 206). 1409 bytes result sent to driver
11:17:45 969 |- INFO Logging - Finished task 0.0 in stage 6.0 (TID 206) in 568 ms on DESKTOP-L9UBSFG (executor driver) (1/1)
11:17:45 969 |- INFO Logging - Removed TaskSet 6.0, whose tasks have all completed, from pool test
11:17:45 969 |- INFO Logging - ResultStage 6 (foreachPartition at XGBoost.scala:604) finished in 0.603 s
11:17:45 969 |- INFO Logging - Job 4 is finished. Cancelling potential speculative or zombie tasks for this job
11:17:45 970 |- INFO Logging - Killing all running tasks in stage 6: Stage finished
11:17:45 970 |- INFO Logging - Job 4 finished: foreachPartition at XGBoost.scala:604, took 0.607177 s
11:17:52 349 |- INFO Logging - Removed broadcast_7_piece0 on DESKTOP-L9UBSFG:51851 in memory (size: 16.2 KiB, free: 1996.1 MiB)
11:17:52 353 |- INFO Logging - Removed broadcast_9_piece0 on DESKTOP-L9UBSFG:51851 in memory (size: 20.9 KiB, free: 1996.2 MiB)
11:17:52 353 |- INFO Logging - Removed broadcast_8_piece0 on DESKTOP-L9UBSFG:51851 in memory (size: 19.0 KiB, free: 1996.2 MiB)

I compiled xgboost4j.dll from xgboost1.2.0_RC2 source code, and the compiled jar package was used in my program.

**Comment by trivialfis** [comment]
Should be able to do basic distributed training on Windows now.
