### ISSUE TITLE
Why can't I find the version 0.4 on PyPI?

### ISSUE THREAD

**Issue by SeanCoek** [dmlc/xgboost#6053]
I want to install the old version (0.4) of xgboost, but it is not available on PyPI. Is there other way to install it?

**Comment by hcho3** [comment]
You can checkout the v0.40 tag and compile the source.

**Comment by hcho3** [comment]
@SeanCoek Also can you tell me why you want to use 0.4 version? In what ways does the latest version does not meet your needs?

**Comment by SeanCoek** [comment]
> @SeanCoek Also can you tell me why you want to use 0.4 version? In what ways does the latest version does not meet your needs?

Just make sure there are no compatible problems on my new machine since I use 0.4 version on my old machine.

**Comment by SeanCoek** [comment]
I have checked out the v0.40 source code and there are no **python-package/**, only **R-package/** instead. Where can I find the **setup.py** script and run it to install xgboost?

**Comment by hcho3** [comment]
I'ts under `wrapper/` directory.

**Comment by SeanCoek** [comment]
It works! Thanks a lot.
