### ISSUE TITLE
XGBoostError: Labels must be in sorted order

### ISSUE THREAD

**Issue by narshon** [dmlc/xgboost#6065]
I am experiencing this error when training my model with a dataset:  
```
raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: [12:36:33] /home/conda/feedstock_root/build_artifacts/xgboost_1588600955503/work/src/objective/regression_obj.cu:327: Check failed: last_abs_y <= abs_y: CoxRegression: labels must be in sorted order, MetaInfo::LabelArgsort failed!
```
Environment:
OS - centos 7
Python - 3.6.10

The dataset summary is as follows: -
```
Observations - 2919
Features - 1107
Positive labels - 168 
```

Error occurs during training:
```
bst = xgb.train(params, dtrain, evals=[(dtest, 'test')], evals_result=evals_result,
                        num_boost_round=n_estimators, verbose_eval=False)
```
My params are as below:
```
hyperopt_evals = 5
n_splits = 2
n_estimators = 200
```
I scaled the parameters down so I can get a quicker turn-around for troubleshooting.
Any help to point to where this could be wrong will be highly appreciated.

**Comment by hcho3** [comment]
As the error suggests, you should re-order your training data such that the labels are ordered in the ascending (increasing) order.
