### ISSUE TITLE
[CI] Run R check in GitHub Actions

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#6068]
Currently, GitHub Actions run the unit tests for R, but does not run `R CMD CHECK --as-cran xgboost*.tar.gz`. This check is essential for uploading XGBoost to CRAN.

**Comment by hcho3** [comment]
Note to new contributors: Post a comment here if you'd like to work on this issue. I am available for help and guidance.

**Comment by ahmedkrmn** [comment]
Hi @hcho3,
I want to work on this issue. Any ideas on where to start?

**Comment by hcho3** [comment]
@ahmedkrmn Great! You can start by trying to run the following commands on your machine:
```
cd /path/to/xgboost
make Rcheck
```
