### ISSUE TITLE
If I still need specify gpu_id in parameters if I use LocalCUDACluster?

### ISSUE THREAD

**Issue by showkeyjar** [dmlc/xgboost#6078]
As I know LocalCUDACluster can create dask cluster use cuda devices,

then I can use xgb.dask.train(client, xgb_params, ...) to train distrubuted xgb model on cuda devices

but I also notice that xgboost has it's own gpu parameters, like:

'tree_method': 'gpu_hist', 'gpu_id': 0

so, I'm confused. If I use LocalCUDACluster, do I still need specify gpu parameters? 

If the answer is yes, how can I set to let each model on one cuda device?

thank you!

**Comment by hcho3** [comment]
No, when using LocalCUDACluster, you do not need to set `gpu_id`.

**Comment by showkeyjar** [comment]
ok, thanks! I'll try.

**Comment by showkeyjar** [comment]
so, the continue question is, if I need CUDA Cluster to train mutiple models, train each model on one worker(one gpu), how can I set the xgboost parameter?

**Comment by hcho3** [comment]
I don't think we support that use case in the Dask interface.

**Comment by showkeyjar** [comment]
ok,got it. 

I use client.map to map mutiple model train tasks to CUDA Cluaster,

it sames to work, but some worker errors and closed: concurrent.futures._base.CancelledError
