### ISSUE TITLE
Feature importance using C api

### ISSUE THREAD

**Issue by nishanthballal-9** [dmlc/xgboost#6079]
Is there a working example/demo of a program to calculate feature importance in C programming using C_api?

**Comment by trivialfis** [comment]
Do you mean shap value?

**Comment by nishanthballal-9** [comment]
No. I mean feature importance using weight, cover or gain. These are available in Python, however I am interested in a C script which is able to calculate feature importance.
I've reached until the point of dumping the XGBoost model using XGBoosterDumpModelEx function in C_api. However I need to know of how to access triple pointer arrays and parse the dumped model in text format.

**Comment by hcho3** [comment]
@nishanthballal-9 You will need to parse the output from `XGBoosterDumpModelEx()` function to compute the feature importances. This is what the Python package does:

https://github.com/dmlc/xgboost/blob/a144daf0340357bc8fc39628451319e215b1b905/python-package/xgboost/core.py#L1797-L1832

**Comment by nishanthballal-9** [comment]
I've gone through this. But any support possible on how to do it with triple pointers in C?
How to access the triple pointers and parse it in C as done above?

**Comment by hcho3** [comment]
@nishanthballal-9 The triple pointer is actually a reference to an array of strings (`const char*`). So you should declare a `const char**` variable and treat it as an array reference:
```cpp
const char** sarr;  // reference to an array of strings
bst_ulong length;  // length of the array
int ret = XGBoosterDumpModelEx(booster, "", 1, "text", &length, &sarr);

for (bst_ulong i = 0; i < length; ++i) {
    // Now parse the string sarr[i]
}
```

**Comment by hcho3** [comment]
I opened #6091 to discuss possibility of adding a new API function for returning feature importances in a structured output like JSON.
