### ISSUE TITLE
xgboost\dmlc-core\src\io\local_filesys.cc:86: LocalFileSystem.GetPathInfo: agaricus.txt.train error: No such file or directory

### ISSUE THREAD

**Issue by jiangqi-1** [dmlc/xgboost#6086]
XGBoost installed from source with Visual Sudio 2017 on win10
When running mushroom.conf, it cannot loading the data and report the error above.I wonder why.
Thanks.

**Comment by jiangqi-1** [comment]
I'm using XGBoost 1.3.0

**Comment by hcho3** [comment]
You can obtain agaricus.txt.train from https://github.com/dmlc/xgboost/blob/master/demo/data/agaricus.txt.train.

**Comment by jiangqi-1** [comment]
It doesn't work either.

**Comment by hcho3** [comment]
You should double check mushroom.conf and see if the path is correctly specified.

**Comment by jiangqi-1** [comment]
I'm sure the path is correct.I have tried relative path and absolute path.Neither works.

**Comment by hcho3** [comment]
Make sure to use forward slashes when specifying the path. (Not backslashes)

**Comment by jiangqi-1** [comment]
Tried, but no  use.

**Comment by hcho3** [comment]
Sorry, I'm out of ideas. If you happen to find the cause, please share.

**Comment by wang364** [comment]
# The path of training data
data = "agaricus.txt.train"
Please change the above line as follows to try
data = C:\xgboost\demo\binary_classification\agaricus.txt.train
there is not need ".

**Comment by jiangqi-1** [comment]
No use. Maybe it's not the problem

**Comment by wang364** [comment]
Maybe you can debug step by step to confirm what is the real problem.

**Comment by jiangqi-1** [comment]
Thanks very much

发送自 Windows 10 版邮件应用

发件人: Philip Hyunsu Cho
发送时间: 2020年11月12日 9:58
收件人: dmlc/xgboost
抄送: jiangqi-1; Author
主题: Re: [dmlc/xgboost] xgboost\dmlc-core\src\io\local_filesys.cc:86:LocalFileSystem.GetPathInfo: agaricus.txt.train error: No such file ordirectory (#6086)

Closed #6086.
