### ISSUE TITLE
Number of features in xgb.predict function

### ISSUE THREAD

**Issue by kaushikepi** [dmlc/xgboost#6106]
Trained a XGB Classifier model with 5178 features and saved it as a pickle file. But the issue is when loading the saved xgb model and if I am passing a feature vector of shape less than 5178 (let's suppose 5174) , it still gives list of probabilities for both the class.

Can anyone explain this ?

**Comment by kaushikepi** [comment]
Saved the model as 
```
import _pickle as cPickle
with open(filename,'wb') as f:
       cPickle.dump(xgb_clf, f)

with open(filename, 'rb') as fr:
    xgb_clf = cPickle.load(fr)

xgb_clf.predict_proba(feat_vec_all)
```
shape of feat_vect = (1,5174) 
But xgb_clf was trained on 5178 features

**Comment by kaushikepi** [comment]
Can you help ? @hcho3

**Comment by hcho3** [comment]
Which XGBoost version are you using?

**Comment by kaushikepi** [comment]
version 1.2.0

**Comment by hcho3** [comment]
The last four features are treated as missing values.

XGBoost models have provisions for missing values in the input vector. See https://www.kdd.org/kdd2016/papers/files/rfp0697-chenAemb.pdf for details about how missing values are handled.

**Comment by kaushikepi** [comment]
@hcho3 Thanks for the help. Will read the paper
