### ISSUE TITLE
XGBoost Gives Warning about colsample_by_tree not being used

### ISSUE THREAD

**Issue by neilyboi** [dmlc/xgboost#6118]
Hi! I am running both the XGBoost Classifier and Regressor, and was trying to hyper parameter tune, but am running into the following warning:

```
[15:20:23] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:516: 
Parameters: { colsample_by_tree } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.
```

Here is a reprex of the code:

```
params = {
    'n_estimators': 50,
    'min_child_weight': 7.0,
    'max_depth': 6,
    'gamma': 0.1,
    'subsample': 0.9,
    'colsample_by_tree': 0.5,
    'reg_lambda': 10,
    'learning_rate': 0.01,
    n_jobs_key: -1
}

xgb_reg = xgb.XGBRegressor(**params)
xgb_class = xgb.XGBClassifier(**params)

```

It seems clear that the parameter is not used, because when i set colsample_by_tree to 0, and then do my fitting and predicting I still get valid predictions and a reasonable score on my task, when I should not. Has this not been implemented?

**Comment by hcho3** [comment]
The correct spelling is `colsample_bytree`.
