### ISSUE TITLE
AttributeError: 'DMatrix' object has no attribute 'feature_names'

### ISSUE THREAD

**Issue by Temmplar** [dmlc/xgboost#612]
Why this error: `AttributeError: 'DMatrix' object has no attribute 'feature_names'`, same with `plot_importance`
python 2.7
Ubuntu 14.04 LTS

**Comment by Far0n** [comment]
Suppose you have somthing like:
```
import xgboost as xgb
gbdt = xgb.train(...)
```
- `feature_names` is an attribute of **gbdt**
- `plot_importance` is a function within **xgb**

**Comment by Temmplar** [comment]
@Far0n Thank you! I already solved it, but thanks again for your help.

**Comment by bhushanladde02** [comment]
How?
