### ISSUE TITLE
N_jobs and nthreads not respected when training with scikit RandomizedSearchCV

### ISSUE THREAD

**Issue by davidfstein** [dmlc/xgboost#6134]
I am trying to tune my parameters on a spark cluster. I want to set the number of jobs to 16, but XGBClassifier is using all available threads. Why is xgb not respecting the n_jobs/nthread parameters?

```
x_grid = {
        'n_estimators': xn_estimators,
        'scale_pos_weight': scale_pos_weight,
        'learning_rate': eta,
        'max_depth': max_depth,
        'min_child_weight': min_child_weight,
        'gamma': gamma,
        'subsample': subsample,
        'colsample_bytree': colsample_bytree,
        'reg_alpha': reg_alpha,
        'n_jobs': [16]
    }

model = XGBClassifier()
params = x_grid

X_train, X_test, y_train, y_test = prepro.scipre(filepath)

grid = RandomizedSearchCV(estimator=model, param_distributions=params, n_iter = 100,
            scoring='f1_weighted', n_jobs=16, cv=3, verbose=2, random_state=1)

grid_result = grid.fit(X_train, y_train)
```

**Comment by davidfstein** [comment]
Anyone able to reproduce?

**Comment by trivialfis** [comment]
Just ran it on master, works pretty well ...

**Comment by trivialfis** [comment]
Which version of XGBoost are you using?

**Comment by davidfstein** [comment]
I'm on 1.2.0 and just two classes. I'll try running XGBoost without scikit to see if it makes a difference

**Comment by davidfstein** [comment]
Ok the issue is that I was using grid search's n_jobs in conjunction with XGBClassifier's n_jobs. So the n_jobs were multiplicative. If I don't use grid search's n_jobs, XGB works as expected
