### ISSUE TITLE
Allow empty datasets in `survival:aft` objective and `aft-nloglik` metric

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#6139]
Currently, `survival:aft` objective and `aft-nloglik` metric throws an error when an empty data matrix is passed in. Empty data matrix is a common occurrence when XGBoost is used with Dask, due to quirks in how Dask partitions the data matrix.

The AFT objective and metric should handle empty data matrices like other element-wise objective and metrics, such as `reg:squarederror` and `logloss`.

cc @trivialfis

**Comment by geetikasharma3119** [comment]
Hi @hcho3 
I am trying to use xgboost's dask functionality with the survival AFT model with little success. Could you please point me to a toy example that demonstrates how to use dask for the AFT survival model?

**Comment by trivialfis** [comment]
@geetikasharma3119 Could you please open an issue and share the difficulty that you have?

**Comment by hcho3** [comment]
@geetikasharma3119 I opened #6853 to add a demo for fitting AFT survival model with Dask.
