### ISSUE TITLE
Xgboost Unbiased Learning to Rank Implementation.

### ISSUE THREAD

**Issue by hassaanseeker** [dmlc/xgboost#6143]
I would like to request a feature in regards to the Unbiased Learning to Rank implementation in Xgboost based on the below links:

https://github.com/ULTR-Community/ULTRA/blob/master/README.md
https://github.com/acbull/Unbiased_LambdaMart

**Comment by trivialfis** [comment]
I looked into it a while ago.  Should not be too difficult.

**Comment by Kolyanty** [comment]
I would like to have this objective too. Are there any plans to work on this feature?
