### ISSUE TITLE
Error in installing R version xgboost on a cluster

### ISSUE THREAD

**Issue by gabriellajg** [dmlc/xgboost#6144]
Hello! 

I was trying to install xgboost within R/4.0.0 on a cluster and kept encountering errors. Specifically, when I typed:

install.packages('xgboost', repos='https://cloud.r-project.org')
I got: 
config.status: creating src/Makevars
** libs
Error: C++14 standard requested but CXX14 is not defined
* removing ‘/afs/crc.nd.edu/user/g/gjiang2/R/xgboost’

When I typed:
devtools::install_github('dmlc/xgboost')
I got 
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  Not Found

  Did you spell the repo owner (`dmlc`) and repo name (`xgboost`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.

Would you mind taking a loot at this? 

Thank you very much for your time. 

Gabriella

**Comment by hcho3** [comment]
`C++14 standard requested but CXX14 is not defined`

It appears that your cluster has an old C++ compiler. We require a C++ compiler that supports the C++14 standard. For example any version of GCC later than 5.0 will work.

**Comment by hcho3** [comment]
@gabriellajg Take a look at https://blogs.cornell.edu/jingyi/2020/02/04/rstudio-install-xtensor/#.X22iqWhKj-g
