### ISSUE TITLE
Xgboost libsvm and missings

### ISSUE THREAD

**Issue by mahdi-ghelichi** [dmlc/xgboost#6147]
I need to use libsvm format due to sheer memory issues. First the nans are filled with -999.0 in my pandas dataframes and then they are converted into libsvm using dump_svmlight_file. Then, when I create the Dmatrix by reading the generated libsvm file, I assign 'missing=-999.0'. 
I was wondering if Dmatrix will recognize these -999.0 as missings or it still treats all those zeros as missings.
Basically, the question is, missings= in Dmatrix would work for libsvm or not. I could not find this info in the documentation.

**Comment by hcho3** [comment]
No, it is not possible to set the missing value when importing LIBSVM file. Instead, you should convert your Pandas DataFrame to sparse columns and then export it as a sparse matrix, as follows:
```python
# df = your DataFrame, with NAN representing the missing value
# Convert columns of df into sparse columns and save them to sdf
sdf = df.astype(pd.SparseDtype("float", np.nan))

# Convert sdf into a Scipy sparse matrix
X = sdf.sparse.to_coo()

# Now export the matrix as LIBSVM file
dump_svmlight_file(X, y, ...)
```
