### ISSUE TITLE
convert xgb.DMatrix to dataframe or matrix

### ISSUE THREAD

**Issue by kartik1611** [dmlc/xgboost#6149]
I have a xgb.Dmatrix which I want to convert to dataframe or matrix format, I would like to know if it is possible to convert.

`
data(agaricus.train, package='xgboost')
train <- agaricus.train
dtrain <- xgb.DMatrix(train$data, label=train$label)
class(dtrain)

`
getting error 

![image](https://user-images.githubusercontent.com/37063126/93939797-ffab7a00-fcf0-11ea-8d63-c08ff354dcc6.png)

is it possible to convert to matrix or dataframe format

**Comment by hcho3** [comment]
No, it is not possible to convert `xgb.DMatrix` to matrix or dataframe. You should save the original data source (libsvm/csv) and use it later.
