### ISSUE TITLE
[R] false-positive warning on CRAN

### ISSUE THREAD

**Issue by jameslamb** [dmlc/xgboost#6151]
I was looking at https://cran.r-project.org/web/checks/check_results_xgboost.html tonight (looking for evidence of something while dealing with https://github.com/microsoft/LightGBM/pull/3338#issuecomment-697075287) and I saw that `{xgboost}` has a WARNING on Mac

![image](https://user-images.githubusercontent.com/7608904/93955926-7c048400-fd16-11ea-897f-24aa709ae275.png)

I think this is just because `R CMD check` counts WARNINGs by literally grepping for the string "WARNING". This could be fixed by removing the word "WARNING" from this message: https://github.com/dmlc/xgboost/blob/e033caa3ba62f87cbc12f16af19c2777e73c5679/R-package/configure.ac#L42

I'd be happy to open a PR that does that if you're interested!

**Comment by hcho3** [comment]
@jameslamb Nice catch! Yes, a pull request is welcome. I will review it.
