### ISSUE TITLE
Create a demo for DaskDeviceQuantileDMatrix

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#6153]
DaskDeviceQuantileDMatrix is a nice feature to ingest GPU Dask partitions without making any copy. We should have a demo.

I'd like to get the word out about the native Dask API of XGBoost, and DaskDeviceQuantileDMatrix is one of its best features.

**Comment by trivialfis** [comment]
I will do that today.

**Comment by trivialfis** [comment]
Now that I look at it, it's possible we can do it more efficiently and accurately by improving the initial construction of summary.

**Comment by hcho3** [comment]
Can we put up a small demo first?

**Comment by trivialfis** [comment]
Yup.
