### ISSUE TITLE
Build failure on i386: non-constant-expression cannot be narrowed from type 'xgboost::bst_ulong' (aka 'unsigned long long') to 'xgboost::common::Span::index_type' (aka 'unsigned int') in initializer list

### ISSUE THREAD

**Issue by yurivict** [dmlc/xgboost#6160]
Log: http://beefy10.nyi.freebsd.org/data/113i386-default/549877/logs/xgboost-1.1.1.log

**Comment by hcho3** [comment]
This is fixed in version 1.2.0: https://github.com/dmlc/xgboost/commit/3cae287deadf72c8d07640d1d6a765cbc9ecff88
