### ISSUE TITLE
"TypeError: 'float' object cannot be interpreted as an integer" in training.py line 63 

### ISSUE THREAD

**Issue by vipinsiriah-git** [dmlc/xgboost#6169]
I am on using python 3.6 and working on xgboost 1.2.0, following and I was facing following issue on fitting an instance of XGBClassifier to my training data.

`TypeError: 'float' object cannot be interpreted as an integer`

changing line 63 of training.py locally to the following resolves the issue for me: 

` for i in range(int(start_iteration), int(num_boost_round)):`

but this is a work around, I urge developer to resolve it a the root.

**Comment by trivialfis** [comment]
Did you pass `num_boost_round` as floating point?
