### ISSUE TITLE
We are participating in Hacktoberfest 2020!

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#6171]
Hacktoberfest 2020 (https://hacktoberfest.digitalocean.com/) is an annual event where DigitalOcean send developers free T-shirts if they complete 4 pull requests for open source projects in the month of October. This is a great opportunity to encourage more developers to get into the open source.

Hacktoberfest is a great opportunity for the XGBoost project, as we can ask incoming contributors to address small issues.
For example:
* Improve documentation by fixing typos, improving style, or add additional details
* Add unit tests

@dmlc/xgboost-committer **Please think about issues that will be attractive to first-time contributors, who are not familiar with internals of XGBoost. They should be small and self-contained**. Tag these issues with tags `good first issue` and `hacktoberfest`. For example, see #6070 and #6172. Also feel free to create new issues that are appropriate.

Related: https://github.com/microsoft/LightGBM/issues/3353

References

* https://hacktoberfest.digitalocean.com/
* https://goodfirstissues.com/

**Comment by hcho3** [comment]
Note to maintainers: To prevent spam, mark spammy pull requests as `spam` and close them. https://hacktoberfest.digitalocean.com/details#spam

**Comment by hcho3** [comment]
Hacktoberfest now switched to opt-in: https://hacktoberfest.digitalocean.com/hacktoberfest-update. Per opt-in guidance, I added `hacktoberfest` topic to this repository. The topic will be removed after end of this month.
![Screen Shot 2020-10-02 at 9 38 50 PM](https://user-images.githubusercontent.com/2532981/94983440-aa911480-04f7-11eb-9d10-1333179a9d06.png)

**Comment by hcho3** [comment]
We have received contributions from first-time contributors: #6192, #6197, #6198, #6204, #6200, #6213, #6222, #6254, #6285, #6286, #6289, #6310, #6325

**Comment by terrytangyuan** [comment]
That's great! 🎉
