### ISSUE TITLE
[RFC] Deprecate position arguments and encourage users to use keyword arguments only

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#6172]
This proposal is inspired by [SLEP 009](https://scikit-learn-enhancement-proposals.readthedocs.io/en/latest/slep009/proposal.html) from the scikit-learn project.

I propose that the `xgboost` Python package should gradually force users to pass arguments with keyword arguments only.

## Motivation
Right now, `xgboost` accepts all arguments both as positional and keyword arguments. For example, both of the following are valid:
```python
# positional arguments
bst = xgb.train(params, dtrain, 10, [(dtrain, 'train')], my_custom_obj, my_custom_eval)
# keyword arguments
bst = xgb.train(params=params, dtrain=dtrain, num_boost_round=10, evals=[(dtrain, 'train')],
                obj=my_custom_obj, feval=my_custom_eval)
```
There are a few benefits of using keyword arguments:
* It is clear which argument corresponds to which parameter in the function. In the example above, it is not immediately clear what `10` means in the first invocation, whereas the second invocation makes it clear that `10` corresponds to the `num_boost_round` parameter.
* For functions like `xgb.train()` that accept many parameters, it is less error-prone to use keyword arguments than positional arguments. For example, with positional arguments, you can make the mistake of switching the order of `obj` and `feval`, and the resulting error will likely be cryptic. With keyword arguments, you'd explicitly specify the keywords `obj` and `feval` and avoid the mistake.
* If everyone would use keyword arguments, we would be able to add new parameters in the middle of the function signature rather than at the end. Right now, all new parameters are added at the end of the parameter list to avoid breaking backward compatibility. For example, #5761 attempts to add `features_name` parameter to `plot_importance()`, and currently adding it in the parameter list would break existing scripts that calls `plot_importance()` with positional arguments.

## Proposal
Python 3.0 and later allows Python functions to require keyword arguments only:
```
def func(arg1, arg2, *, arg3, arg4)
```
meaning that `arg3` and `arg4` must be specified as keyword arguments.

We should revise all Python functions in XGBoost to require most or all parameters to be passed as keyword arguments.

## Deprecation path
Simply revising all functions to add `*` will break existing scripts right away, so we should enable a path for smooth transition.
We should start displaying warnings in the next release when positional arguments are detected. 

Matplotlib and scikit-learn have developed a simple solution: a decorator that throws a warning for positional arguments:
```python
@warn_args
def train(params, dtrain, *, num_boost_round=10, evals=(), obj=None, feval=None,
          maximize=False, early_stopping_rounds=None, evals_result=None,
          verbose_eval=True, xgb_model=None, callbacks=None):
```
Calling `xgb.train(params, dtrain, 10, [(dtrain, 'train')], my_custom_obj, my_custom_eval)` will result with a `DeprecationWarning`:
```
Pass num_boost_round=10, evals=[(dtrain, 'train')], obj=my_custom_obj, feval=my_custom_eval as keyword args.
From version 1.6.0 passing these as positional arguments will result in an error.
```
After a few minor releases, we will remove the `@warn_args` decorator so that calling function with positional arguments will fail.

Reference implementation:
* https://github.com/matplotlib/matplotlib/pull/13601 (`@cbook._make_keyword_only`)
* https://github.com/scikit-learn/scikit-learn/pull/13311 (`@warn_args`)

## Note to new contributors

Post a comment here if you'd like to work on this issue. I am available for help and guidance.

**Comment by hcho3** [comment]
@trivialfis Can you review this proposal?

**Comment by trivialfis** [comment]
I would start with `DMatrix` and `SKL` module.  Since for `DMatrix`, we have more and more meta info, but the constructor is untouchable.  Same goes for `SKL` module.

**Comment by jameslamb** [comment]
I really like this idea, and I think that the proposed path of using deprecation warnings over a few releases and then eventually turning those into errors is a good one.

I think the warning should be much more descriptive than the one `scikit-learn` is using. Instead of:

> DeprecationWarning: Should use keyword args: min_samples=5

I think it would be better to have something like

> DeprecationWarning: Should use keyword args: min_samples=5. Starting with xgboost v2.0.0, this warning will become a fatal error.
