### ISSUE TITLE
Wheel support for linux aarch64

### ISSUE THREAD

**Issue by odidev** [dmlc/xgboost#6180]
**Summary**
Installing xgboost on aarch64 via pip using command "pip3 install xgboost" tries to build wheel from source code.

**Problem description**
xgboost doesn't have wheel for aarch64 on PyPI repository. So, while installing xgboost via pip on aarch64, pip builds wheel for same resulting in it takes more time to install xgboost. Making wheel available for aarch64 will benefit aarch64 users by minimizing xgboost installation time.

**Expected Output**
Pip should be able to download xgboost wheel from PyPI repository rather than building it from source code.

@xgboost-team, please let me know if I can help you building wheel/uploading to PyPI repository. I am curious to make xgboost wheel available for aarch64. It will be a great opportunity for me to work with you.

**Comment by RAMitchell** [comment]
Arm support would be nice! You could start by trying to get a travis build working in CI: https://blog.travis-ci.com/2019-10-07-multi-cpu-architecture-support.
