### ISSUE TITLE
n_estimators warning

### ISSUE THREAD

**Issue by hassaanseeker** [dmlc/xgboost#6185]
```
params = {'objective': 'rank:ndcg', 'colsample_bytree': 0.5,
 'eta': 0.325,
 'gamma': 5,
 'max_depth': 8,
 'tree_method': 'exact',
 'min_child_weight': 6.0,
 'n_estimators': 100,
 'subsample': 0.8,
 }

xgb_model = xgb.train(params, train_dmatrix, num_boost_round = 100,
            evals=[(train_dmatrix, 'training'),(valid_dmatrix, 'validation')])
```

[14:38:45] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:516: 
Parameters: { n_estimators } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but passed down to XGBoost core.  Or some parameters are not used but slip through this verification. Please open an issue if you find the above cases.

I am getting the above warning when I run the above train method.

**Comment by trivialfis** [comment]
`n_estimator` is part of the sklearn interface, not in `xgb.train`.   The sklearn interface do some configurations to change `n_estimator` into `num_boost_round` before training.
