### ISSUE TITLE
Reduce compiler warnings for C++

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#6189]
Currently, the C++ compiler generates lots of warnings: https://xgboost-ci.net/blue/organizations/jenkins/xgboost/detail/master/516/pipeline/61. It would be great to reduce the number of warnings.

**Note to new contributors**: Post a comment here if you'd like to work on this issue. Feel free to ping me for help.

**Comment by sgavil** [comment]
Hello, i would like to work on this issue!

**Comment by hcho3** [comment]
@sgavil Great! I'm going to assign this issue to you. Keep in mind that you don't have to eliminate all warnings in a single pull request. It will probably take several pull requests to address all warnings.

**Comment by hcho3** [comment]
See instructions for building XGBoost here: https://xgboost.readthedocs.io/en/latest/build.html#building-on-linux-distributions. Modify the CMake flags as follows:
```
cmake .. -DHIDE_CXX_SYMBOLS=ON
```
in order to show all compiler warnings.

**Comment by sgavil** [comment]
Great! Thank you

**Comment by vcarpani** [comment]
I can also contribute to this, I believe there are enough warnings for 2 different PRs

**Comment by igormp** [comment]
Mind if I jump into that too? GPU-related code has way too many warnings, would be nice to clean up some.

**Comment by hcho3** [comment]
@igormp Great! Yes, your pull request is welcome! Keep in mind that some compiler warnings in the GPU code come from [CUB](https://github.com/nvidia/cub) and [Thrust](https://github.com/nvidia/thrust), so you may also consider submitting pull request there.

**Comment by igormp** [comment]
I've noticed that most warnings (I'd say half of those) come from [dmlc](https://github.com/dmlc/dmlc-core), so maybe some PRs would be welcome there.

**Comment by hcho3** [comment]
@igormp Yes, the compiler warning has been an issue for a while in dmlc. Would you like to take a shot?

**Comment by igormp** [comment]
Sure! It'll try to go through it during this week.

**Comment by BurakBarlas** [comment]
Hi, Can I try to help you in this issue?

**Comment by hcho3** [comment]
@BurakBarlas Yes! Feel free to submit a pull request. Let me know if you need help.

**Comment by pranav-verma001** [comment]
Hello i want to work on this...

**Comment by trivialfis** [comment]
@pranav-verma001 Thanks for volunteering, you can start with https://github.com/dmlc/xgboost/issues/6189#issuecomment-701725173 .  Feel free to ping me if you need any assistance.  ;-)

**Comment by trivialfis** [comment]
@pranav-verma001 I'm not familiar with vscode IDE (I thought that's an editor instead of IDE?).

As for which compiler should you use, both gcc and clang are fine.  Could you please try running the following steps inside the xgboost directory:

``` sh
mkdir build
cd build
cmake .. -DENABLE_ALL_WARNINGS=ON
make -j$(nproc)
```

**Comment by pranav-verma001** [comment]
Okay then tell me which IDE shall I use?
When i run make -j$(nproc) I get the following error:
'make' is not recognized as an internal or external command,
operable program or batch file.

**Comment by pranav-verma001** [comment]
Codeblocks is fine??

**Comment by trivialfis** [comment]
@pranav-verma001 It seems like you are using Windows?

**Comment by pranav-verma001** [comment]
yes windows 10

**Comment by trivialfis** [comment]
Got it.

Assuming you have git installed in full, and you have visual studio IDE, you should have an option `Git Bash Here` in your right click menu in the source code directory.  Open it, then type:

``` sh
mkdir build
cd build
cmake .. -DCMAKE_CONFIGURATION_TYPE=Debug -A x64
cmake --build ./ --config Debug
```

@RAMitchell might be able to provide better suggestion.  I only use Windows to debug compiler specific error ...

**Comment by giladmaya** [comment]
@trivialfis can I pitch in as well?

**Comment by trivialfis** [comment]
Sure!  Let me know if you need any help.

**Comment by trivialfis** [comment]
With the latest XGBoost + CUDA 11.6, most of the warnings are addressed.
