### ISSUE TITLE
convert the text columns to libsvm format using feature hasher from scikit learn ?

### ISSUE THREAD

**Issue by aliabbasjp** [dmlc/xgboost#619]
https://github.com/zygmuntz/phraug/blob/master/csv2libsvm.py links to a code which only works for numeric data , but I have CSV file for machine learning which has mostly text data and most columns have a large cardinality , eg: a column with name of a person. Ideally would like to use the scikit learn's feature hasher or a vectorizer to generate the file in libsvm format hashing the text feature values to appropriate numeric values.

Note:

The graphlab ML library takes inputs with non numeric values in its Sframe and the Sframe is used in the classifiers like xgboost. So it is already doing what I require but it is not opensource and we dont get the numeric table output from the sframe. Most likely graphlab is using some featurehasher internally to keep track of the mappings between the text values and numeric values.

So how to convert the text columns to libsvm format using feature hasher from scikit learn ?

**Comment by tqchen** [comment]
closing this for now as this seems goes beyond scope of the classifier but more of feature scripting question
