### ISSUE TITLE
Have "File /lib/libxgboost4j.dylib was not found inside JAR" exception when run xgbClassifier.fit on mac 

### ISSUE THREAD

**Issue by dding3** [dmlc/xgboost#6196]
I tried to use xgboost4j-spark to train a xgboostclassifier on mac. And I am using the jvm package from snapshot build. Below is related xgboost settings in pom.xml.

        <repository>
            <id>XGBoost4J Snapshot Repo</id>
            <name>XGBoost4J Snapshot Repo</name>
            <url>https://s3-us-west-2.amazonaws.com/xgboost-maven-repo/snapshot/</url>
        </repository>
        <dependency>
            <groupId>ml.dmlc</groupId>
            <artifactId>xgboost4j_2.11</artifactId>
            <version>1.2.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>ml.dmlc</groupId>
            <artifactId>xgboost4j-spark_2.11</artifactId>
            <version>1.2.0-SNAPSHOT</version>
        </dependency>

However I have "File /lib/libxgboost4j.dylib was not found inside JAR" when I called `model.fit()`.  I am wondering if the jvm package works on mac?

**Comment by hcho3** [comment]
The Snapshot build currently only supports Linux. You may obtain artifacts from Maven Central, which do support Mac.

**Comment by hcho3** [comment]
FYI, both 1.1.1 and 1.2.0 versions are available on Maven Central now.

**Comment by dding3** [comment]
Thanks for the update. I found the scala is 2.12 for xgboost 1.2.0 on Maven Central. Is it possible to publish scala 2.11 for xgboost 1.2.0 as well on Maven Central.

**Comment by hcho3** [comment]
@dding3 No, because XGBoost4J-Spark 1.2.0 depends on Spark 3.0, which is exclusively using Scala 2.12.

**Comment by hcho3** [comment]
If you are only using single-node training, you could try building XGBoost4J only with Scala 2.11. I haven't tried it myself so proceed with caution.
