### ISSUE TITLE
xgboost plot tree generates with wrong comparison operator 

### ISSUE THREAD

**Issue by ascoolakash** [dmlc/xgboost#6208]
Thanks for participating in the XGBoost community! We use https://discuss.xgboost.ai for any general usage questions and discussions. The issue tracker is used for actionable items such as feature proposals discussion, roadmaps, and bug tracking.  You are always welcomed to post on the forum first :)

![error](https://user-images.githubusercontent.com/6160311/95210155-31284900-07b9-11eb-8033-b291cc6e86a3.png)
![error](https://user-images.githubusercontent.com/6160311/95210153-31284900-07b9-11eb-8330-62db957865af.png)

Issues that are inactive for a period of time may get closed. We adopt this policy so that we won't lose track of actionable issues that may fall at the bottom of the pile. Feel free to reopen a new one if you feel there is an additional problem that needs attention when an old one gets closed.

For bug reports, to help the developer act on the issues, please include a description of your environment, preferably a minimum script to reproduce the problem.

For feature proposals, list clear, small actionable items so we can track the progress of the change.

![error](https://user-images.githubusercontent.com/6160311/95211015-11ddeb80-07ba-11eb-8ee8-23353a2f48fd.png)

[xgboost_plot_tree_issue.zip](https://github.com/dmlc/xgboost/files/5334344/xgboost_plot_tree_issue.zip)

**Comment by hcho3** [comment]
Please do not file an issue with an empty description.

**Comment by ascoolakash** [comment]
> Please do not file an issue with an empty description.

I added a pdf file with all the descriptions, think that is sufficient. I'm really sorry about the confusion.

By the above flow chart, the model first checking the Total stat and if the Total stat value is greater than 574 it says it's a legendary pokemon else check's the other parameter. After checking the Total stat's it checks the Egg_Group_1_Undiscoverd which is created after using pandas get_dummies function and qualifies a pokemon legendary if it's value greater than 1. Then it checks the Attack stat and classifies legendary pokemon for when their attack value is greater than 83.

**Note:** The comparison symbol given in the flow chart is of opposite nature. It's a bug Xgboost library. 

The code used to create the model and plot tree is below:

from xgboost import XGBClassifier
mdl = XGBClassifier(max_depth=5,n_estimators=100,learning_rate=0.1)
mdl.fit(X_train,y_train)
predictions_xgb = mdl.predict(X_test)
import xgboost as xgb
import matplotlib
xgb.plot_tree(mdl,num_trees=2)
fig = matplotlib.pyplot.gcf()
fig.set_size_inches(20, 10)

**Comment by hcho3** [comment]
I fail to see any bug. XGBoost always uses the same comparison operator "<". So all test nodes in the plot should be of form `[feature] < [threshold]`

**Comment by hcho3** [comment]
>  if the Total stat value is greater than 574 it says it's a legendary pokemon

Not true. That's not what the model does. If the total stat is greater than 574, then **the model predicts a negative score -0.166972861, which indicates a low probability for the legendary pokemon**. (That is, it is more likely that the pokemon is not legendary.)

> it checks the Egg_Group_1_Undiscovered ... qualifies a pokemon legendary if it's value greater than 1.

Also not true. If Egg_Group_1_Undiscovered < 1, then the output is -0.112729825. This is a negative score, so it indicates a low probability for the legendary pokemon. (That is, it is more likely that the pokemon is not legendary.)

**Comment by ascoolakash** [comment]
> I fail to see any bug. XGBoost always uses the same comparison operator "<". So all test nodes in the plot should be of form `[feature] < [threshold]`

In the present case, Total > 574 required, simillary in other case i.e., [feature] > [threshold].
You can check the dataset below:
https://www.kaggle.com/abcsds/pokemon

**Comment by hcho3** [comment]
No, it is not possible to customize the comparison operator in XGBoost. XGBoost always uses the less than ("<") operator.

**Comment by ascoolakash** [comment]
> > if the Total stat value is greater than 574 it says it's a legendary pokemon
> 
> Not true. That's not what the model does. If the total stat is **less** than 574, then **the model predicts a negative score -0.166972861, which indicates a low probability for the legendary pokemon**. (That is, it is more likely that the pokemon is not legendary.) On the other hand, the model asks other questions if the total stat is greater than or equal to 574.
> 
> > it checks the Egg_Group_1_Undiscovered ... qualifies a pokemon legendary if it's value greater than 1.
> 
> Also not true. If Egg_Group_1_Undiscovered < 1, then the output is -0.112729825. This is a negative score, so it indicates a low probability for the legendary pokemon. (That is, it is more likely that the pokemon is not legendary.)

Thanks a lot for the explanation. It helps a lot.

**Comment by hcho3** [comment]
Good luck with your competition! Keep in mind that each tree in XGBoost produces either a positive or a negative number. A positive number signifies a high probability for the positive class, whereas a negative number signifies a high probability for the negative class.
