### ISSUE TITLE
[CI] Jenkins down for an emergency maintenance

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#6214]
Cause: the cost watcher is timing out as CloudTrail keeps throwing `ThrottlingException`.

I took down the Jenkins server to put in a fix. I will try to put it up in a timely manner.

**Comment by hcho3** [comment]
Jenkins is now back up.

Post-mortem: The cost watcher lambda was horribly inefficient. Each call to the cost watcher Lambda function was sending a query to CloudTrail, and CloudTrail has a hard limit of 2 queries per second per AWS account. To avoid querying CloudTrail, I redesigned the cost watcher function as follows: 
1. Every EC2 launch now adds a new entry to a DynamoDB table (this is done by triggering another Lambda function)
2. The cost watcher Lambda now simply queries the DynamoDB table containing the list of EC2 launche and termination events. Querying DynamoDB is a lot more efficient than querying CloudTrail.

**Comment by trivialfis** [comment]
Thanks for maintaining the CI.. It's very confusing that how these things are glued together though ...
