### ISSUE TITLE
Tree prunning end... messages in Python Windows

### ISSUE THREAD

**Issue by JohanManders** [dmlc/xgboost#622]
I don't know if it is a Python or Windows wrapper only thing, but here is my problem:

Every boosting round, I get a message like: ```tree prunning end, 1 roots, 6 extra nodes, 0 pruned nodes ,max_depth=2``` These messages clutter up my terminal and run wild through my evaluation metric printouts. (It also bugs me that the , before max_depth is in the wrong place ;)

I know where it comes from. When using xgb.train(), every boosting round the ```train``` function calls ```bst.update(dtrain, i, obj)``` and the ```update``` function calls ```_check_call(_LIB.XGBoosterUpdateOneIter(self.handle, iteration, dtrain.handle))``` which generates these nice messages.

The message is created in ```src/tree/updater_prune-inl.hpp``` if ```silent == 0```, but I have no idea how to set ```silent``` from Python / Windows. Anyone any idea?

**Comment by sinhrks** [comment]
Specifying ``silent=1`` via params should work.

```
params={'objective': 'multi:softprob', 'silent': 1}
bst = xgb.train(params, dm)
```

**Comment by JohanManders** [comment]
@sinhrks Thanks man! Sorry for that.
