### ISSUE TITLE
Effects of DeviceQuantileDMatrix object on the results (binary classification)

### ISSUE THREAD

**Issue by Kotsakis** [dmlc/xgboost#6227]
Is it possible to document how DeviceQuantileDMatrix is affecting the results?

I had memory issues so i switched to this but my results are off. I did not touch the max_bins parameter though (some insights on that parameter, would be greatly appreciated).

Also, when specifying "missing" parameter in DeviceQuantileDMatrix when cupy is chosen, it should be remade to cp.nan right?

**Comment by trivialfis** [comment]
@Kotsakis Are you using dask interface?  Or it's single node?

> it should be remade to cp.nan right

Not necessary.  As long as it's IEEE floating point nan value: https://en.wikipedia.org/wiki/NaN

**Comment by Kotsakis** [comment]
It is a single node.

**Comment by trivialfis** [comment]
Could you please provide a reproducible script?  I'm asking as we have tests to show the results are the same, but apparently they are not sufficient.

**Comment by Kotsakis** [comment]
I will try to, as soon as possible.

**Comment by hcho3** [comment]
@Kotsakis Any updates?

**Comment by Kotsakis** [comment]
I cannot unfortunately publish a reproducible example.
