### ISSUE TITLE
gpu_hist integer overflows and OOM issues

### ISSUE THREAD

**Issue by RAMitchell** [dmlc/xgboost#6228]
This issue tracks gpu_hist bugs relating to large workloads, uncovered in recent experiments on the mortgage dataset.

- Thrust copy_if has an integer overflow when n_rows*n_cols > 2^31. #6201 implements a workaround by iterating over batches. 

- Memory usage has possibly increased since version 1.0-1.1, leading to OOM on 32gb devices even with the above fix. We should do some analysis of peak memory usage over versions on a large synthetic workload, checking for regressions.

- DaskDeviceQuantileDMatrix has integer overflow bugs related to thrust::inclusive_scan, occurring when dask chunk sizes exceed 2^31.

To prevent this occurring in future we can try unit tests on large sizes, checking for overflow or memory issues. These tests need to be carefully designed to not be flaky (e.g. only run on a machine with sufficient memory) and to run quickly (<1-2 seconds).

**Comment by hcho3** [comment]
@RAMitchell Can we close this now?

**Comment by jamescolless** [comment]
Sorry, just to confirm, does the 2^31-1 limitation also occur in DeviceQuantileDMatrix or only in DaskDeviceQuantileDMatrix?

**Comment by trivialfis** [comment]
Both.  For Dask version, the limitation is for each partition.

**Comment by trivialfis** [comment]
It's fixed in latest master, the fix should go in next release.
