### ISSUE TITLE
ValueError: could not convert string to float: 'Faridabad' appears even though X variable has NO string/object columns

### ISSUE THREAD

**Issue by rahullak** [dmlc/xgboost#6236]
Hello,

I am facing what looks like a weird issue. I get this "ValueError: could not convert string to float: 'Faridabad' " for a X variable that contains only float and int columns.

Here's a code snippet:

``` python
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,random_state=101,test_size=0.1)

print("Xtrain shape",X_train.shape)
print("Ytrain shape",Y_train.shape)

print(X_train.info())

for col in X_train.columns:
    data = X_train[col]
    data = data.values.astype('float')
print("Done")

xgbr = XGBRegressor(learning_rate=0.01,n_estimators=500,max_depth=10,n_jobs=3) 

xgbr.fit(X_train,Y_train)
```
>

So the output here is:

> 
Xtrain shape (26505, 269)
Ytrain shape (26505,)
<class 'pandas.core.frame.DataFrame'>
Int64Index: 26505 entries, 27112 to 13151
Columns: 269 entries, POSTED_BY_Builder to READY_TO_MOVE
dtypes: float64(8), uint8(261)
memory usage: 8.4 MB
Done

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-e8be3586efdd> in <module>
     30 xgbr = XGBRegressor(learning_rate=0.01,n_estimators=500,max_depth=10,n_jobs=3) #
     31 
---> 32 xgbr.fit(X_train,Y_train)
     33 #lr = LinearRegression()
     34 #lr.fit(X_train,Y_train)

c:\users\rahul\anaconda3\envs\tfcontests\lib\site-packages\xgboost\sklearn.py in fit(self, X, y, sample_weight, base_margin, eval_set, eval_metric, early_stopping_rounds, verbose, xgb_model, sample_weight_eval_set, callbacks)
    505                                 base_margin=base_margin,
    506                                 missing=self.missing,
--> 507                                 nthread=self.n_jobs)
    508 
    509         evals_result = {}

c:\users\rahul\anaconda3\envs\tfcontests\lib\site-packages\xgboost\core.py in __init__(self, data, label, weight, base_margin, missing, silent, feature_names, feature_types, nthread)
    440         self.handle = handle
    441 
--> 442         self.set_info(label=label, weight=weight, base_margin=base_margin)
    443 
    444         self.feature_names = feature_names

c:\users\rahul\anaconda3\envs\tfcontests\lib\site-packages\xgboost\core.py in set_info(self, label, weight, base_margin, group, label_lower_bound, label_upper_bound, feature_names, feature_types)
    459         '''Set meta info for DMatrix.'''
    460         if label is not None:
--> 461             self.set_label(label)
    462         if weight is not None:
    463             self.set_weight(weight)

c:\users\rahul\anaconda3\envs\tfcontests\lib\site-packages\xgboost\core.py in set_label(self, label)
    584         """
    585         from .data import dispatch_meta_backend
--> 586         dispatch_meta_backend(self, label, 'label', 'float')
    587 
    588     def set_weight(self, weight):

c:\users\rahul\anaconda3\envs\tfcontests\lib\site-packages\xgboost\data.py in dispatch_meta_backend(matrix, data, name, dtype)
    612         return
    613     if _is_pandas_series(data):
--> 614         data = data.values.astype('float')
    615         assert len(data.shape) == 1 or data.shape[1] == 0 or data.shape[1] == 1
    616         _meta_from_numpy(data, name, dtype, handle)

ValueError: could not convert string to float: 'Faridabad'
<

Note:

1. 'Faridabad' is the name of a city and there is a CITY column in the original dataset. However, the data has been transformed to one-hot-encoded along with some other numerical columns, so that there are NO more any string/object columns.

2. Note the error is in a particular line 614 in the above output. I have executed that particular line for EVERY column in the transformed dataset in my code (see the for loop in the code snippet) and there's NO error. Weirdly the same line executed as part of the xgboost library results in an error about a string, which isn't even in the data fed to the XGBRegressor object!

3. I have restarted the Kernel and even restarted the Jupyter notebook, but the error remains.

4. Environment Specs:

Windows 10. 
4 core CPU. No GPU. 8 GB RAM
Conda v4.4.7
xgboost v1.2.0
pandas v1.1.2
numpy v1.19.1 

Hope I'm not missing something obvious, apologies if that's the case, and thanks in advance for pointing it out!

**Comment by trivialfis** [comment]
One of the columns in your dataframe might be of string type.  Could you please check that?

**Comment by trivialfis** [comment]
Could you please check the `Y_train`?

**Comment by rahullak** [comment]
Yes, that was the issue thank you!
Apparently I had changed the order of columns in the dataset during my tinkering and the Y was getting a different column than intended!

Guess i get the prize for most obvious mistake in the world :/

Thanks again for pointing it out!
