### ISSUE TITLE
Cannot install xgboost with pycharm 

### ISSUE THREAD

**Issue by Rupam07** [dmlc/xgboost#6245]
Hi, 

I tried installing and running xgboost as xgb on PyCharm but facing the same error while downloading and running
I tried downloading it with pip, brew as well as the installer with project interpreter on PyCharm. Please help me with this I am stuck with the issue since forever and need it to be solved asap. 

I can share the details and screenshots if required further. If there are any steps that I can follow that would be helpful.

Thank you!

**Comment by trivialfis** [comment]
Please share the screenshots. ;-)

**Comment by trivialfis** [comment]
And the platform information:
- OS
- PyCharm version
- pip version

**Comment by Rupam07** [comment]
The error message is:
<img width="1308" alt="Screen Shot 2020-10-15 at 7 20 40 PM" src="https://user-images.githubusercontent.com/48689684/96205474-87b12800-0f1b-11eb-8605-9c6c852585b4.png">
I am using Python 3.8
PyCharm Version:
<img width="452" alt="Screen Shot 2020-10-15 at 7 21 27 PM" src="https://user-images.githubusercontent.com/48689684/96205527-a31c3300-0f1b-11eb-8263-1ea7a9a43cc6.png">
Pip version is 20.1.1
Mac OS Catalina

Also, my project interpreter shows xgboost
<img width="736" alt="Screen Shot 2020-10-15 at 7 23 38 PM" src="https://user-images.githubusercontent.com/48689684/96205708-2178d500-0f1c-11eb-85fa-390c0d618bbc.png">

**Comment by trivialfis** [comment]
ping @hcho3

**Comment by hcho3** [comment]
@Rupam07 You should install the OpenMP runtime, by running `brew install libomp`. (This command requires [Homebrew](https://brew.sh/).) That should enable XGBoost to run on your system.

**Comment by Rupam07** [comment]
@hcho3 Thank you that helped!
