### ISSUE TITLE
make fails with error 'fopen64' was not declared in this scope

### ISSUE THREAD

**Issue by beckeroobonsai** [dmlc/xgboost#625]
I am trying to build it on Windows. I have Anaconda installed.  I cloned the xgboost repo from git to a subfolder in the Anaconda folder and typed 'make' inside that folder.  Not sure what is wrong. Anyone else come across this error?

**Comment by phunterlau** [comment]
You might want to use the visual studio solution file from `xgboost/windows` for building the windows binary.

**Comment by beckeroobonsai** [comment]
I don't have access to visual studio. I had a free trial version of it once, but no more. Is there another way to build it without using visual studio?

**Comment by phunterlau** [comment]
solution 1, get visual studio express, it is free https://www.visualstudio.com/en-us/products/visual-studio-express-vs.aspx

solution 2, have you found your xgboost_wrapper.dll anywhere after building, e.g. in xgboost/python-package/xgboost/? In windows platform, the search path for this lib is set to ./windows/Release/ and ../../windows/Release/ (./windows/x64/Release/ and ../../windows/x64/Release/ for 64bit) according to `python-package/xgboost/libpath.py` line 25 https://github.com/dmlc/xgboost/blob/master/python-package/xgboost/libpath.py#L25 since the official support windows build is using visual studio. You might want to copy your xgboost_wrapper.dll to these directory and see if xgboost can find it.

**Comment by beckeroobonsai** [comment]
Hmm. It was a free trial last I downloaded visual-studio. In either case, it should be possible to do the build at the command line without the visual studio IDE.

There was, in fact, no xgboost_wrapper.dll file.

I ran make clean. Then make again.  Now there is  xgboost_wrapper.dll  located at   /Anaconda/xgboost/wrapper/xgboost_wrapper.dll.
Now the command 'python setup.py install' seemed to work.  Thanks for your help.

The next step is getting it to import into ipython.
The instructions lead me to believe this should work:
import sys
sys.path.append('C:/Users/Rebecca/Anaconda/xgboost/wrapper')
import xgboost as xgb

It does not find xgboost.  What am I missing?  Any ideas?

**Comment by phunterlau** [comment]
sounds like your platform problem on make. Since visual studio express is free, can you try compiling with the solution file and see if the problem is still there? that will also help us understanding the compiling in windows platform for make vs visual studio. Thanks.

**Comment by hswater1** [comment]
I see the doc says "The MSVC build for new version is not yet updated". Does it mean I can't use visual studio express to build?

**Comment by tqchen** [comment]
yes, we are still lacking contribution for the cmake builds #746

**Comment by skyjiao** [comment]
I use cygwin to install xgboost but I constantly get this error message:
 ‘fopen64’ was not declared in this scope:
std::FILE *fp = fopen64(fname, flag);

Does anyone know how to fix it?

**Comment by thirdwing** [comment]
@skyjiao You are running into some classical chaos. We suggest you to use `MinGW-w64` not `Cygwin`.

**Comment by skyjiao** [comment]
@thirdwing thx for your response. Since I couldn't get it work after quite a while, I downloaded an elder version 0.4 instead of this weird current version 0.4x and built it with visual studio. Now everything seems working right now. I think the 0.4 release is better for windows users.

**Comment by thirdwing** [comment]
You can pick which version suits your developing environment best.

I can tell you the reason why Cygwin can't compile it. The error is from https://github.com/dmlc/dmlc-core/blob/master/include/dmlc/base.h#L110-L112

The `fopen64()` is from Linux large system support library, it is a specialized version of `fopen()` to open very large files. Most release of GCC (like `MinGW-w64` we suggest) include it, but it seems `Cygwin` doesn't.

**Comment by spinwards** [comment]
I am currently receiving this error on windows 10 using the MinGW-w64 environment recommended here. In addition I tried building in msys2 (after running pacman -S mingw64/mingw-w64-x86_64-make) and in the current git bash distribution without success. It is worth noting the the latest distribution of git bash does not ship with make, so the instructions here: https://xgboost.readthedocs.io/en/latest/build.html#build-the-shared-library so not work.

**Comment by aperfilev** [comment]
Would you kindly append next code:

#if defined(__x86_64__)
#define fopen64 fopen
#endif

in next files:

./dmlc-core/src/io/local_filesys.cc
./dmlc-core/src/io/single_file_split.h
./rabit/include/rabit/internal/utils.h

?

**Comment by chechir** [comment]
Hello, I'm using Windows 10 and Cygwin and got it working as follows: 
cd ~
git clone --recursive https://github.com/dmlc/xgboost
cd xgboost
git submodule init
git submodule update
cp make/mingw64.mk config.mk

#Here I replaced all occurrences of fopen64 to fopen:

find . -type f -exec sed -i 's/fopen64/fopen/g' {} +
make -j4

#Then, I needed to copy and paste the library lib/libxgboost.dll and rename the copied file to libxgboost.so. After this I could run these lines without error:
cd python-package
python setup.py install

Not sure if this is the best approach but worked yesterday (8th-nov-2016)
