### ISSUE TITLE
xgboot model got memory leak when loading model and predicting score

### ISSUE THREAD

**Issue by ACEGuiPeng** [dmlc/xgboost#6250]
#### User Story

As a python developer,I want to use xgboot model to predict score.

#### What happened:

I got memory leak and I could not to release memory manually when I used xgboost model on product servers.

##### prepare

1. got a xgboot model file

2. got python version:3.7.9 develop environment

3. install requirement list

   ```
   scikit-learn==0.23.2
   pandas==1.1.3
   memory_profiler==0.52.0
   ```

4. pip install xgboost-1.3.0_SNAPSHOT+00b0ad1293b4fa74d6aca5da4e9ab7a9d16777f0-py3-none-manylinux2010_x86_64.whl

##### steps to reproduce the behavior:

1. here is my code:

```
import pandas as pd
import xgboost as xgb
from memory_profiler import profile


@profile(precision=4)
def main():
    target_method()


@profile(precision=4)
def target_method():
    data_frame = pd.read_csv("test.csv")
    xgb_model = xgb.XGBClassifier()
    xgb_model.load_model("./best_xgb.model")
    percent = xgb_model.predict_proba(data_frame)
    score = int(round(percent[0][0], 2) * 100)
    print(score)
    del data_frame
    del xgb_model
    del score


if __name__ == '__main__':
    main()
```

2. After run,I got memory leak output:
```
Line #    Mem usage    Increment   Line Contents
================================================
    11  81.0156 MiB  81.0156 MiB   @profile(precision=4)
    12                             def target_method():
    13  81.7109 MiB   0.6953 MiB       data_frame = pd.read_csv("test.csv")
    14  81.7109 MiB   0.0000 MiB       xgb_model = xgb.XGBClassifier()
    15  84.0430 MiB   2.3320 MiB       xgb_model.load_model("./best_xgb.model")
    16  85.1680 MiB   1.1250 MiB       percent = xgb_model.predict_proba(data_frame)
    17  85.1797 MiB   0.0117 MiB       score = int(round(percent[0][0], 2) * 100)
    18  85.1836 MiB   0.0039 MiB       print(score)
    19  85.1836 MiB   0.0000 MiB       del data_frame
    20  85.2148 MiB   0.0312 MiB       del xgb_model
    21  85.2148 MiB   0.0000 MiB       del score


Filename: /mnt/d/Projects/job/xgboost_leak_demo/main.py

Line #    Mem usage    Increment   Line Contents
================================================
     6  81.0156 MiB  81.0156 MiB   @profile(precision=4)
     7                             def main():
     8  85.2148 MiB   4.1992 MiB       target_method()
```

**Comment by trivialfis** [comment]
Is it still increasing when you continue?  The first prediction will allocate a thread local buffer for storing prediction result.  Subsequent prediction will reuse previous buffer.

**Comment by ACEGuiPeng** [comment]
No,it is not increasing in a loop,thanks!And I have other questions:
1. Should I load the model in a global variable once when the app starting？
2. When the buffer memory release to the system？Is there a way to release the memory manually？Because the model predict frequently on product environment.

**Comment by trivialfis** [comment]
> Should I load the model in a global variable once when the app starting？

There's no restriction on how you load the model.

> When the buffer memory release to the system？

When the thread exits.  The memory is allocated by `thread_local`. https://en.cppreference.com/w/cpp/keyword/thread_local

> Is there a way to release the memory manually？

Launch a new thread for prediction.  The memory buffer is managed by c++ runtime.

> Because the model predict frequently on product environment.

In that case, not releasing the memory is beneficial from my perspective.  If you run prediction frequently, then for every prediction you will have to do an extra alloc/free operation, which seems to be wasteful.

**Comment by trivialfis** [comment]
Feel free to close if that answers your questions. :-)

**Comment by ACEGuiPeng** [comment]
Thanks a lot!Best wishes to you.
