### ISSUE TITLE
[FEATURE]  When using cudf, allow predictions to come back on GPU

### ISSUE THREAD

**Issue by pseudotensor** [dmlc/xgboost#6251]
Currently predictions are on the GPU after the _LIB.XGBoosterPredict() call in core.py, but then this is converted to numpy and this forces it to go back to the CPU.  Then some basic reshaping is done.

This is unfortunate since if one could keep the predictions on the GPU, then one could use GPU-based scoring and other operations on the GPU.

I don't see anything complicated in the reshape related code, and it could be all done on the GPU.

**Comment by trivialfis** [comment]
Can you use `inplace_predict`?

**Comment by pseudotensor** [comment]
Thanks.

Main issue is it appears much more limited than predict, e.g. no pred_contribs, etc.

Yet, the normal predict would be easy to make good, at least with some option to choose return type maybe.  It seems very close to being fully cudf return value.

I'm using scikit-learn API, so another reason I don't have choice to use inplace_predict, but that's not a big deal of course.  Main issue is the capability.

**Comment by pseudotensor** [comment]
Also, I'm guessing that for dask_cudf use, if want it to be feature complete, need to be able to return everything predict can but stay on GPU.

**Comment by trivialfis** [comment]
Closing in favor of https://github.com/dmlc/xgboost/issues/6304 .
