### ISSUE TITLE
[Feature request] DMatrix python API support batch input and disk caching

### ISSUE THREAD

**Issue by WeichenXu123** [dmlc/xgboost#6256]
Like DMatrix java interface XGDMatrixCreateFromDataIter:
https://github.com/dmlc/xgboost/blob/4d99c58a5f2a4e586dede954182a30f547f98169/include/xgboost/c_api.h#L170

Which we can use batch iterator to construct a DMatrix, and can set a disk cache directory for caching.

DMatrix Python API should also provide this interface.
This will help reduce memory peak usage when construct DMatrix and xgb training.

**Comment by trivialfis** [comment]
If you are using the `hist` tree method, a CPU equivalent to the second set of callback API should be preferred over the first set.

**Comment by hcho3** [comment]
Related: https://discuss.xgboost.ai/t/why-does-dmatrix-copy-numpy-data-even-when-it-meets-c-contiguous-and-float32-constriants/1901

A batch iterator API for CPU will help lower memory consumption when building a DMatrix from a NumPy array.

**Comment by trivialfis** [comment]
We have that now.
