### ISSUE TITLE
failed to compile 1.2.1 released version (.tar.gz)

### ISSUE THREAD

**Issue by 7starsea** [dmlc/xgboost#6274]
I downloaded 1.2.1 released version from https://github.com/dmlc/xgboost/releases/tag/v1.2.1, however, it fails to compile since some related libs are not included in the released version.

I am hoping that the released version is self-contained for compiling and installing.
(Since usually, we install xgboost from pip which is a released version, however, if we need to build from source in the case when we want to use c-api for inference in real application and want to keep the same version as in training, currently, we could only clone the master branch.)

Thanks.

**Comment by trivialfis** [comment]
Right now cloning is necessary as we have git submodules, while the tar ball generated by github doesn't include these submodules.

**Comment by trivialfis** [comment]
You can checkout the release tag with git.

**Comment by 7starsea** [comment]
Thanks, I will try.

**Comment by trivialfis** [comment]
Feel free to reopen.
