### ISSUE TITLE
[jvm-packages] Flaky test for error handling.

### ISSUE THREAD

**Issue by trivialfis** [dmlc/xgboost#6276]
https://xgboost-ci.net/blue/organizations/jenkins/xgboost/detail/PR-6269/2/pipeline

After some digging, here are a few issues I found:

- When RABIT fail to initialize/shutdown/TrackerPrint, jvm displays the last error from xgboost instead of rabit, or abort due to lack of API guard.  This is partly addressed by https://github.com/dmlc/xgboost/pull/6275
- On the failing test `train throwing exception if feature size of dataset is different on distributed train`, tracker is shutdown before workers, so RABIT can't send the "shutdown" message to tracker and hence cannot finalize gracefully.
- Catching `XGBoostError` in the test is unreliable.  On the other hand, if we disable killing spark context, a `SparkException` is guaranteed to be thrown after a few retries.

**Comment by trivialfis** [comment]
Running:
```
mvn -Dsuites='ml.dmlc.xgboost4j.scala.spark.MissingValueHandlingSuite*' test
```
is deterministically failing on my machine even went back to before merging RABIT.


```
[INFO] 
[INFO] --- scalatest-maven-plugin:1.0:test (test) @ xgboost4j-spark_2.12 ---
Discovery starting.
Discovery completed in 193 milliseconds.
Run starting. Expected test count is: 8
MissingValueHandlingSuite:
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
20/10/23 02:38:20 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Tracker started, with env={DMLC_NUM_SERVER=0, DMLC_TRACKER_URI=192.168.1.102, DMLC_TRACKER_PORT=9091, DMLC_NUM_WORKER=4}
task 1 connected to the tracker
[02:38:25] WARNING: /home/fis/Workspace/XGBoost/xgboost/src/gbm/gbtree.cc:137: Tree method is automatically selected to be 'approx' for distributed training.[02:38:25] WARNING: /home/fis/Workspace/XGBoost/xgboost/src/gbm/gbtree.cc:137: Tree method is automatically selected to be 'approx' for distributed training.
task 2 connected to the tracker
task 0 connected to the tracker
task 3 connected to the tracker
task 1 got new rank 0
task 2 got new rank 1
task 0 got new rank 2
task 3 got new rank 3
[02:38:25] WARNING: /home/fis/Workspace/XGBoost/xgboost/src/gbm/gbtree.cc:137: Tree method is automatically selected to be 'approx' for distributed training.

[02:38:25] WARNING: /home/fis/Workspace/XGBoost/xgboost/src/gbm/gbtree.cc:137: Tree method is automatically selected to be 'approx' for distributed training.
retry connect to ip(retry time 1): [192.168.1.102]
retry connect to ip(retry time 2): [192.168.1.102]
retry connect to ip(retry time 3): [192.168.1.102]
retry connect to ip(retry time 4): [192.168.1.102]
connect to (failed): [192.168.1.102]
Socket Connect Error:Connection refused, rabit is configured to keep process running
terminate called after throwing an instance of 'dmlc::Error'
  what():  Socket Connect Error:Connection refused
Aborted (core dumped)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for XGBoost JVM Package 1.2.0-SNAPSHOT:
[INFO] 
[INFO] XGBoost JVM Package ................................ SUCCESS [  2.001 s]
[INFO] xgboost4j_2.12 ..................................... SUCCESS [ 59.298 s]
[INFO] xgboost4j-spark_2.12 ............................... FAILURE [ 46.776 s]
[INFO] xgboost4j-flink_2.12 ............................... SKIPPED
[INFO] xgboost4j-example_2.12 ............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:48 min
[INFO] Finished at: 2020-10-23T02:38:45+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.scalatest:scalatest-maven-plugin:1.0:test (test) on project xgboost4j-spark_2.12: There are test failures -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :xgboost4j-spark_2.12
```

**Comment by trivialfis** [comment]
@CodingCat Do you have some suggestions to ensure the tracker outliving workers?  Currently @hcho3 and I located it down the the race condition between killing tracker and rabit worker shutdown.

**Comment by CodingCat** [comment]
looking right now

**Comment by CodingCat** [comment]
@trivialfis could you briefly explain why `train throwing exception if feature size of dataset is different on distributed train` is special that track is stopped first? 

my memory might be blur now, but the original idea of that test might be following what we have done in `MissingValueHandlingSuite` ( the difference is that in MissingValueHandlingSuite, the error is from JVM layer )

**Comment by trivialfis** [comment]
@CodingCat Thanks for looking.  Currently there are 2 errors, one is the failing `feature size of dataset ..` test that can be seen on CI.  I do not understand why the tracker is stopped first.  The behavior is not deterministically reproducible either.

Another one is On my machine posted here: https://github.com/dmlc/xgboost/issues/6276#issuecomment-714685475, `MissingValueHandlingSuite` is throwing error during RABIT shutdown.  But this error is more difficult to reproduce.  https://github.com/dmlc/xgboost/issues/6276#issuecomment-714975396 is corresponding to this error.

**Comment by trivialfis** [comment]
Correctness tests are fine, but failure tests are generally not working on machine due to failing to shutdown rabit tracker.

**Comment by CodingCat** [comment]
did we change anything relevant in rabit ?

I think this test has been here for a while, it just start to fail recently?

**Comment by CodingCat** [comment]
the other possibility is that  Spark 3.0 changed something, e.g. whether the threads of tasks are stopped (a)synchronously in local mode

**Comment by trivialfis** [comment]
We recently dropped the single point model recovery.  I think it made the error more reproducible somehow.  But the issue should be here for a while now.

**Comment by CodingCat** [comment]
@trivialfis I don't think that's the case, MissingValueSuite was added long before single point model recovery added in rabit side , it never shows as flaky, 

https://github.com/dmlc/xgboost/blob/release_0.90/jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/MissingValueHandlingSuite.scala

it was added in last April , and never shows as flaky, and rabit recovery thing was added in Aug https://github.com/dmlc/xgboost/commit/5797dcb64e45bd3d19547b53b759d60302ba2278

until Aug to now, it is not flaky either,

I would suggesting check if the "removing single point recovery" introduced anything unexpected, or we could simply pick an earlier version  of rabit (like something in last April and cherry-pick the necessary patches), if anyone wants newer functionality in rabit, they can still go to dmlc/rabit

**Comment by trivialfis** [comment]
@CodingCat I tried looking at  the diff of logging:

Here is the extra error before removing single point model recovery:

```
AssertError:buf should have data from resbuf, rabit is configured to keep process running
buf should have data from resbuf
20/10/26 00:20:59 ERROR Executor: Exception in task 1.0 in stage 6.0 (TID 7)
```

Other backtraces from XGBoost are not reliable as described in front page of this issue.  The error is due to an extra pseudo sync during shutdown, and has nothing to do with the test.   The pseudo sync is removed and these kind of errors are surfacing.

**Comment by trivialfis** [comment]
Similar issue for timeout is also outlined in https://github.com/dmlc/xgboost/pull/6262#issue-506395907 .  So some tests are expected to fail in the future, as previously those tests are not testing what we thought it was testing.  By removing the single point model recovery and 3k lines of code, I'm hoping we can reason about more of these behaviors.

**Comment by trivialfis** [comment]
Workarounded in https://github.com/dmlc/xgboost/pull/6275 .
