### ISSUE TITLE
DMatrix creation takes a big part of training and prediction time

### ISSUE THREAD

**Issue by RukhovichIV** [dmlc/xgboost#6283]
# Description of the problem

We did some measurements and found out that DMatrix creation takes a huge part of any operation in XGBoost with both **pandas DataFrame** and **numpy array** with float32 values.
It takes  **up to 90% of the prediction time** on our datasets and **up to 35% of the training time** on it.

|                  | Pandas.DataFrame |                 | Numpy.ascontigiousarray |                 |                      |
|------------------|------------------|-----------------|-------------------------|-----------------|----------------------|
| operation        | time, s          | dmatrix time, % | time, s                 | dmatrix time, % | numpy improvement, s |
| airline, train    | 36.5497          | 14.6913         | 35.7296                 | 8.8368          | 0.8201               |
| airline, predict  | 5.9467           | 97.6645         | 3.6844                  | 79.7643         | 2.2623               |
| higgs, train      | 14.6953          | 3.2722          | 15.1656                 | 2.9845          | -0.4703              |
| higgs, predict    | 1.0596           | 46.8678         | 1.0114                  | 44.8713         | 0.0482               |
| msrank, train     | 77.4849          | 5.6062          | 74.3278                 | 3.5626          | 3.1571               |
| msrank, predict   | 5.6924           | 68.3226         | 4.3200                  | 56.0864         | 1.3724               |
| mortgage, train   | 19.4234          | 32.4388         | 20.8129                 | 21.7833         | -1.3895              |
| mortgage, predict | 6.3151           | 91.5222         | 4.7360                  | 88.5982         | 1.5791               |

# What can be done

- XGBoost already has the `inplace_predict` method, which allows us to do prediction for data in numpy array without copying it. We'd like to discuss the possibility **to extend** this function with pandas DataFrame.
- If we go deeper into the problem, `inplace_predict` is not the default function and it seems like **most of the XGBoost users are not familiar with it**. Also, for obvious reasons, we can't make a similar function for training, which also works longer than it could be. **Is there a need for copying the input data for every DMatrix object? Is it possible to add the additional `no_copy` flag to avoid copying of the input data in case of usage float32 type?**

**Comment by trivialfis** [comment]
For training with GPU hist and GPU input, you can use `DeviceQuantileDMatrix`, which constructs the histogram index inplace.  This is mostly for better memory consumption instead of speed.  You will notice longer construction time with it, but the overall training time should be faster.

The inplace predict function is still under development.  Expect feature parity in future release. ;-)

> Is there a need for copying the input data for every DMatrix object? 

For hist, no.  A similar object to `DeviceQuantileDMatrix` can be implemented for CPU but AFAIK no one is working on it.  For other tree methods, yes.  Internally XGBoost stores a CSR matrix, so that some algorithms can iterate through the data efficiently.  For example, prediction works on per-row basis, while feature enumeration works on per-column basis.

**Comment by trivialfis** [comment]
Closing in favor of https://github.com/dmlc/xgboost/issues/6304 .

**Comment by ShvetsKS** [comment]
@trivialfis seems it's right place to clarify some points.
Can we consider next options:
1) Is it possible to have `inplace_predict` method as default method for Scikit-Learn API (`XGBClassifier.predict` calls `inplace_predict` inside its implementation)? (Pandas DF can be also supported here in future)

2) When `CPUQuantileDMatrix` is implemented, is it possible to use `CPUQuantileDMatrix` by default in Scikit-Learn API  for `fit` method with 'hist' tree method?

**Comment by trivialfis** [comment]
- Not sure.  Inplace means we can't copy data, not even between host/device. 
- Same.

**Comment by ShvetsKS** [comment]
> * Not sure.  Inplace means we can't copy data, not even between host/device.

Why we need copy of the data and DMatrix construction in Scikit-learn API? User provide numpy array (pandas df) via Scikit-Learn API, why we do extra work?

> * Same.

What is the reason? Similar case: user provide numpy array, why do we have to construct DMatrix internally and spend time on data copy if we can avoid it and construct CPUQuantileDMatrix in case of 'hist' tree method?

**Comment by trivialfis** [comment]
In long term, you are right and that's the plan.  Same goes for dask interface.  Numpy is 1 data source, we have 15 or so.  Some are CPU, some are CUDA.  Maybe there will be SYCL managed non-host device?  Arrow is coming, numba is possible but we haven't declare its support.  These 2 are known heterogeneous.  So simplest case, given a numpy data, cupy weight for training, what do you do? Same goes for prediction for data and base margin.  I don't want another long list of dispatching in Python, especially you can have multiple meta data.

Lastly, I hope the quantile DMatrix objects are interchangeable, so CPU input can be used for GPU training and wise versa.

I wrote the iterative dmatrix with these kind of usage in mind, at least for training.  So before you start working on it, please share your plan.  :-)  I will try to assist.

**Comment by ShvetsKS** [comment]
@trivialfis Thanks a lot for explanations.
Please correct me if I'm wrong.
So in general you doesn't mind if we try to reduce copy of the data in Scikit-learn API for `fit` and `prediction`.? Solution of course should not consist long list of dispatching :)

**Comment by trivialfis** [comment]
Of course I don't mind!  Any improvement is welcomed!!!  Just sometimes I might be difficult to work with as I spent a lots of time refactoring the old codebase and hope that I can focus more on machine learning.  So might object to some solutions.  :-)
