### ISSUE TITLE
stream data real time prediction

### ISSUE THREAD

**Issue by 7starsea** [dmlc/xgboost#6288]
Currently, I would like to use c/c++ api of xgboost in (low-latency) real time prediction, but it seems to me that the c/c++ api is not designed (or optimized) for such use case. 
In my case, I have a float array which will be updated periodically, and each time a prediction is needed,  it seems to me we must create a dmatrix from the float array. I am wondering whether there is a way to avoid dmatrix creation each time.

Thanks.

**Comment by trivialfis** [comment]
Right now no.  As inplace prediction is still new and we haven't exposed the API yet.  But it's on the roadmap.

**Comment by trivialfis** [comment]
Stay tuned for update on inplace prediction.

**Comment by 7starsea** [comment]
> Stay tuned for update on inplace prediction.

Thanks for letting me know this.
