### ISSUE TITLE
How to distinguish between feature true value 0 and 0 of missing values filling?

### ISSUE THREAD

**Issue by wa008** [dmlc/xgboost#6303]
How to distinguish between feature true value 0 and 0 of missing values filling in xgboost? 
does xgboost equal treat them?

Even you filling missing values with other values x, this question also exist.

**Comment by trivialfis** [comment]
Not sure what do you mean.  You can set the missing value in your dataset to values like `NaN`, and tell XGBoost about it by specifying `missing`

**Comment by wa008** [comment]
> Not sure what do you mean. You can set the missing value in your dataset to values like `NaN`, and tell XGBoost about it by specifying `missing`
I get it.
I thought that I can't give `Nan` data to xgboost, that was wrong, thanks very much.
