### ISSUE TITLE
Possible Model IO Issue when Saving XGBoostRegressionModel in Scala Spark

### ISSUE THREAD

**Issue by pancodia** [dmlc/xgboost#6308]
I am training XGBoost Regression using XGBoost4j-Spark version 1.1.1 (patch distribution). I am seeing the following error when trying to save model to a file:

```
2020-10-28 12:40:25 ERROR Booster:730 - [12:40:25] /workspace/src/tree/tree_model.cc:673: Check failed: fi->Read(dmlc::BeginPtr(stats_), sizeof(RTreeNodeStat) * stats_.size()) == sizeof(RTreeNodeStat) * stats_.size() (1900432 vs. 4748784) :
Stack trace:
  [bt] (0) /mnt/tmp/libxgboost4j6080941118636887534.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x57) [0x7f3022339947]
  [bt] (1) /mnt/tmp/libxgboost4j6080941118636887534.so(xgboost::RegTree::Load(dmlc::Stream*)+0x327) [0x7f30225269a7]
  [bt] (2) /mnt/tmp/libxgboost4j6080941118636887534.so(xgboost::gbm::GBTreeModel::Load(dmlc::Stream*)+0xee5) [0x7f3022441065]
  [bt] (3) /mnt/tmp/libxgboost4j6080941118636887534.so(xgboost::gbm::GBTree::Load(dmlc::Stream*)+0x1a) [0x7f302242b34a]
  [bt] (4) /mnt/tmp/libxgboost4j6080941118636887534.so(xgboost::LearnerIO::LoadModel(dmlc::Stream*)+0x420) [0x7f302246d8a0]
  [bt] (5) /mnt/tmp/libxgboost4j6080941118636887534.so(XGBoosterLoadModelFromBuffer+0x4c) [0x7f302233d43c]
  [bt] (6) /mnt/tmp/libxgboost4j6080941118636887534.so(Java_ml_dmlc_xgboost4j_java_XGBoostJNI_XGBoosterLoadModelFromBuffer+0x41) [0x7f3022333191]
  [bt] (7) [0x7f3271018427]
```

After searching online, I found the following discussion which seems related.

> This is a model IO issue (unfortunately).  The model returned by pruner has `process_type=update`.  Putting it into the next training is a full copy with all hyper-parameters.   A quick workaround is setting:
> ``` python
> param_dict['process_type'] = 'default'
>```
> Before the last training.

_Originally posted by @trivialfis in https://github.com/dmlc/xgboost/issues/5376#issuecomment-597792349_

Does `process_type` work in XGBoost4j-spark? I don't see this parameter mentioned in [the API doc](https://xgboost.readthedocs.io/en/latest/jvm/scaladocs/xgboost4j/ml/dmlc/xgboost4j/scala/Booster.html).

BTW, this error occurred when I trained a model with large number of rounds (937) and deep trees (max depth 22). Other smaller models did not have this issue.

**Comment by trivialfis** [comment]
I'm not sure if it applies on scala binding.

**Comment by trivialfis** [comment]
>  am seeing the following error when trying to save model to a file:

The error message shows that you are loading a model.
