### ISSUE TITLE
Missing parameter "approx_contribs" in "predict" method

### ISSUE THREAD

**Issue by cshasha** [dmlc/xgboost#6311]
Hi,

I'm using the latest version of XGBoost (1.2.1), and am trying to use the "approx_contribs" parameter when calling "predict". However, I get the following error:

```
> xgb_model.predict(X_test,approx_contribs=True)
TypeError: predict() got an unexpected keyword argument 'approx_contribs'
```

Looking at the source code, I don't see "approx_contribs" as a parameter. However, it's shown in the API here: https://xgboost.readthedocs.io/en/latest/python/python_api.html

I've tried installing different versions of xgboost but with no luck. What's going on here?

Thanks!

**Comment by trivialfis** [comment]
That's from the `Booster` object.  If you are using scikit learn interface, try `get_booster`.

**Comment by cshasha** [comment]
Ah thanks I see now, sorry!
