### ISSUE TITLE
Xgboost stops improve a model starting from a certain iteration

### ISSUE THREAD

**Issue by sh1ng** [dmlc/xgboost#632]
I've never seen that behavior before. But during a training the output log(silent: 0) looks like 

tree prunning end, 1 roots, 0 extra nodes, 0 pruned nodes ,max_depth=0
tree prunning end, 1 roots, 0 extra nodes, 0 pruned nodes ,max_depth=0
tree prunning end, 1 roots, 0 extra nodes, 0 pruned nodes ,max_depth=0
tree prunning end, 1 roots, 0 extra nodes, 0 pruned nodes ,max_depth=0
tree prunning end, 1 roots, 0 extra nodes, 0 pruned nodes ,max_depth=0
tree prunning end, 1 roots, 0 extra nodes, 0 pruned nodes ,max_depth=0
tree prunning end, 1 roots, 0 extra nodes, 0 pruned nodes ,max_depth=0
tree prunning end, 1 roots, 0 extra nodes, 0 pruned nodes ,max_depth=0
tree prunning end, 1 roots, 0 extra nodes, 0 pruned nodes ,max_depth=0
tree prunning end, 1 roots, 0 extra nodes, 0 pruned nodes ,max_depth=0
tree prunning end, 1 roots, 0 extra nodes, 0 pruned nodes ,max_depth=0
tree prunning end, 1 roots, 0 extra nodes, 0 pruned nodes ,max_depth=0
tree prunning end, 1 roots, 0 extra nodes, 0 pruned nodes ,max_depth=0
tree prunning end, 1 roots, 0 extra nodes, 0 pruned nodes ,max_depth=0
tree prunning end, 1 roots, 0 extra nodes, 0 pruned nodes ,max_depth=0
tree prunning end, 1 roots, 0 extra nodes, 0 pruned nodes ,max_depth=0
tree prunning end, 1 roots, 0 extra nodes, 0 pruned nodes ,max_depth=0
tree prunning end, 1 roots, 0 extra nodes, 0 pruned nodes ,max_depth=0
tree prunning end, 1 roots, 0 extra nodes, 0 pruned nodes ,max_depth=0

from a certain iteration.
Train and val scores remains on a constant level.

Is it a bug?
How can you explain it in terms  of machine learning.
Does it mean that all information been extracted and it's unable to improve a prediction by adding trees?

I'm not ready to provide data, but it contain about 800k records and 20 features.

**Comment by MaximBogun** [comment]
hello what kind of error did you have can you explain?because i have similar issue in java
