### ISSUE TITLE
Same Results with Different Seeds (random_state) in xgboost

### ISSUE THREAD

**Issue by jmq19950824** [dmlc/xgboost#6326]
**Reproductive codes**

import pandas as pd
import numpy as np
import xgboost as xgb
from sklearn import datasets

iris = datasets.load_iris()
X = iris.data[:, :2] # we only take the first two features.
y = iris.target

model_1 = xgb.XGBClassifier(random_state = 1)
model_1.fit(X,y)
p_1 = model_1.predict_proba(X)

model_2 = xgb.XGBClassifier(random_state = 2)
model_2.fit(X,y)
p_2 = model_2.predict_proba(X)

print(all(p_1[:,0] == p_2[:,0]))
print(all(p_1[:,1] == p_2[:,1]))

**result:
True
True**

**Bug: Same Results with Different Seeds (random_state)**
Although model_1 and model_2 are trained with different seeds (i.e., 1 and 2), both models predict the same probability for given dataset. In fact, should **different** models (which are trained with different seeds) generate **different** results?

**Comment by hcho3** [comment]
The `predict_proba()` function might be generating highly certain predictions like `[0 1]` (meaning 100% confidence for the positive class). You should regularize your model to mitigate overfitting. For example, you can set `learning_rate` to a small value, like 0.1 or 0.01.

**Comment by jmq19950824** [comment]
> The `predict_proba()` function might be generating highly certain predictions like `[0 1]` (meaning 100% confidence for the positive class). You should regularize your model to mitigate overfitting. For example, you can set `learning_rate` to a small value, like 0.1 or 0.01.

Thanks for reply. **Indeed I have tried different hyper-parameters and different datasets, but the same problem occurs.**
Besides, in the above case, the probability generated by XGBoost is actually not like [0 1] but like 

[9.99083042e-01, 5.99870109e-04, 3.17052210e-04],
[9.93345141e-01, 3.22490395e-03, 3.42994044e-03]

However, different models (with different random_state) got the completely same prediction probability, which is weired.

**Comment by hcho3** [comment]
@jmq19950824 With default hyperparameters, XGBoost runs deterministically. You can inject randomness by setting the `subsample` hyperparameter to a number less than 1.0. For example, setting `subsample=0.5` will cause XGBoost to fit each tree using only 50% of the training data. (By default, XGBoost uses the entire training data to fit each tree.)

The following script will print `False False`:
```python
import pandas as pd                                                                                                                                         
import numpy as np                                                                                                                                          
import xgboost as xgb                                                                                                                                       
from sklearn import datasets                                                                                                                                
                                                                                                                                                            
iris = datasets.load_iris()                                                                                                                                 
X = iris.data[:, :2] # we only take the first two features.                                                                                                 
y = iris.target                                                                                                                                             
                                                                                                                                                            
model_1 = xgb.XGBClassifier(random_state=1, subsample=0.5)                                                                                                  
model_1.fit(X,y)                                                                                                                                            
p_1 = model_1.predict_proba(X)                                                                                                                              
                                                                                                                                                            
model_2 = xgb.XGBClassifier(random_state=2, subsample=0.5)                                                                                                  
model_2.fit(X,y)                                                                                                                                            
p_2 = model_2.predict_proba(X)                                                                                                                              
                                                                                                                                                            
print(all(p_1[:,0] == p_2[:,0]))                                                                                                                            
print(all(p_1[:,1] == p_2[:,1]))
```

**Comment by jmq19950824** [comment]
@hcho3 Appreciate that! Thank you for explaining the reason for this reproductivity problem. Now this issue could be close
