### ISSUE TITLE
[QUESTION] multi-node multi-GPU training docs

### ISSUE THREAD

**Issue by pseudotensor** [dmlc/xgboost#6328]
https://xgboost.readthedocs.io/en/latest/gpu/index.html#multi-node-multi-gpu-training

This seems to suggest only dask is supported, but 

https://news.developer.nvidia.com/gpu-accelerated-spark-xgboost/
https://rapids.ai/xgboost.html

suggests can do it on spark as well.  Need to update docs?

Is there any real limit on what distributed framework is used?  i.e. I assume one can build xgboost4j for GPUs and use it on any networked systems?  Is dask and its API really required compared to the native API?

**Comment by trivialfis** [comment]
I think the spark package supports MNMG fine when input is from CPU dataframe.

For GPU input support, I think there was effort on upstreaming it: https://github.com/dmlc/xgboost/pull/5950  You might have to reach out to @wbo4958 @CodingCat for details.
