### ISSUE TITLE
Windows installation Fatal Error

### ISSUE THREAD

**Issue by FusionPlant** [dmlc/xgboost#633]
I am a windows user who wanna use this amazing tool.
I followed precisely the instructions here: https://www.kaggle.com/c/otto-group-product-classification-challenge/forums/t/13043/run-xgboost-from-windows-and-python
But every time I just got this:
3>LINK : fatal error LNK1181: cannot open input file '**some directory**\xgboost\windows\x64\Release\\rabit.lib'
And in the end I end up with
========== Build: 2 succeeded, 2 failed, 0 up-to-date, 0 skipped ==========
I have been searching everywhere trying to find a solution, including adding system PATH variables, and use setuptools, but they are not helping this error.

I also tried to walk around this problem by using Anaconda, but no luck so far. The closest I got is when I run a tutorial file "basic_walkthrough.py", I got the following:
File "**somedirectory**\Anaconda2\lib\site-packages\xgboost-0.4-py2.7.egg\xgboost\sklearn.py", line 10, in <module>
    from .compat import (SKLEARN_INSTALLED, XGBModelBase,
ImportError: cannot import name LabelEncoder

I think I have to install it properly in Visual Studio to run it properly. Could someone help me? Thank you so much!

**Comment by FusionPlant** [comment]
It is solved. Just need to comment a line containing "sleep"...

**Comment by modqhx** [comment]
Hey, can you share how you solved this issue? I'm on mac but I am getting the same error:

```
>>> import xgboost
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/xgboost-0.4-py2.7.egg/xgboost/__init__.py", line 13, in <module>
    from .sklearn import XGBModel, XGBClassifier, XGBRegressor
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/xgboost-0.4-py2.7.egg/xgboost/sklearn.py", line 10, in <module>
    from .compat import (SKLEARN_INSTALLED, XGBModelBase,
ImportError: cannot import name LabelEncoder
```

**Comment by FusionPlant** [comment]
When I was compiling xgboost in Visual Studio, there was an warning/error
on a line calling a function named something like "sleep". I commented it
and recompiled xgboost. Everything went nicely after that.

On Wed, Dec 9, 2015 at 12:20 PM, Mudit <notifications@github.com> wrote:

> Hey, can you share how you solved this issue? I'm on mac but I am getting
> the same error:
>
> >>> import xgboost
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/xgboost-0.4-py2.7.egg/xgboost/__init__.py", line 13, in <module>
>     from .sklearn import XGBModel, XGBClassifier, XGBRegressor
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/xgboost-0.4-py2.7.egg/xgboost/sklearn.py", line 10, in <module>
>     from .compat import (SKLEARN_INSTALLED, XGBModelBase,
> ImportError: cannot import name LabelEncoder
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/xgboost/issues/633#issuecomment-163380855>.
>



-- 
Best,
Tailai
