### ISSUE TITLE
Building XGBoost from source - issues

### ISSUE THREAD

**Issue by gokulanv** [dmlc/xgboost#6331]
Hey,

Thanks for the awesome framework.
I am trying to build XGBoost from source by following the [Building-on-Linux-distributions](https://xgboost.readthedocs.io/en/latest/build.html#building-on-linux-distributions).
I want to install XGBoost with -DUSE_DEBUG_OUTPUT=ON to view and debug the Grads and Hessian matrices. 

Is there any better way to build with this option. The documentation only suggests this.

When I run make install, I get the following errors:

**CMakeError.log**

`Performing C SOURCE FILE Test CMAKE_HAVE_LIBC_PTHREAD failed with the following output:
Change Dir: /home/gvikashb/xgboost/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake cmTC_df2e7/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_df2e7.dir/build.make CMakeFiles/cmTC_df2e7.dir/build
gmake[1]: Entering directory `/home/gvikashb/xgboost/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_df2e7.dir/src.c.o
/packages/7x/gcc/gcc-7.2.0/bin/gcc   -DCMAKE_HAVE_LIBC_PTHREAD -o CMakeFiles/cmTC_df2e7.dir/src.c.o -c /home/gvikashb/xgboost/build/CMakeFiles/CMakeTmp/src.c
Linking C executable cmTC_df2e7
/packages/7x/cmake/3.18.4/bin/cmake -E cmake_link_script CMakeFiles/cmTC_df2e7.dir/link.txt --verbose=1
/packages/7x/gcc/gcc-7.2.0/bin/gcc  -DCMAKE_HAVE_LIBC_PTHREAD CMakeFiles/cmTC_df2e7.dir/src.c.o -o cmTC_df2e7 
CMakeFiles/cmTC_df2e7.dir/src.c.o: In function `main':
src.c:(.text+0x2d): undefined reference to `pthread_create'
src.c:(.text+0x39): undefined reference to `pthread_detach'
src.c:(.text+0x45): undefined reference to `pthread_cancel'
src.c:(.text+0x56): undefined reference to `pthread_join'
src.c:(.text+0x6a): undefined reference to `pthread_atfork'
collect2: error: ld returned 1 exit status
gmake[1]: *** [cmTC_df2e7] Error 1
gmake[1]: Leaving directory `/home/gvikashb/xgboost/build/CMakeFiles/CMakeTmp'
gmake: *** [cmTC_df2e7/fast] Error 2

Source file was:
#include <pthread.h>

void* test_func(void* data)
{
  return data;
}

int main(void)
{
  pthread_t thread;
  pthread_create(&thread, NULL, test_func, NULL);
  pthread_detach(thread);
  pthread_cancel(thread);
  pthread_join(thread, NULL);
  pthread_atfork(NULL, NULL, NULL);
  pthread_exit(NULL);

  return 0;
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/gvikashb/xgboost/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake cmTC_e8f50/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_e8f50.dir/build.make CMakeFiles/cmTC_e8f50.dir/build
gmake[1]: Entering directory `/home/gvikashb/xgboost/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_e8f50.dir/CheckFunctionExists.c.o
/packages/7x/gcc/gcc-7.2.0/bin/gcc   -DCHECK_FUNCTION_EXISTS=pthread_create -o CMakeFiles/cmTC_e8f50.dir/CheckFunctionExists.c.o -c /packages/7x/cmake/3.18.4/share/cmake-3.18/Modules/CheckFunctionExists.c
Linking C executable cmTC_e8f50
/packages/7x/cmake/3.18.4/bin/cmake -E cmake_link_script CMakeFiles/cmTC_e8f50.dir/link.txt --verbose=1
/packages/7x/gcc/gcc-7.2.0/bin/gcc  -DCHECK_FUNCTION_EXISTS=pthread_create CMakeFiles/cmTC_e8f50.dir/CheckFunctionExists.c.o -o cmTC_e8f50  -lpthreads 
/packages/7x/binutils/2.29.1/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
gmake[1]: *** [cmTC_e8f50] Error 1
gmake[1]: Leaving directory `/home/gvikashb/xgboost/build/CMakeFiles/CMakeTmp'
gmake: *** [cmTC_e8f50/fast] Error 2

Determining if the fopen64 exist failed with the following output:
Change Dir: /home/gvikashb/xgboost/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake cmTC_0e2a9/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_0e2a9.dir/build.make CMakeFiles/cmTC_0e2a9.dir/build
gmake[1]: Entering directory `/home/gvikashb/xgboost/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_0e2a9.dir/CheckSymbolExists.c.o
/packages/7x/gcc/gcc-7.2.0/bin/gcc    -o CMakeFiles/cmTC_0e2a9.dir/CheckSymbolExists.c.o -c /home/gvikashb/xgboost/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
/home/gvikashb/xgboost/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c: In function ‘main’:
/home/gvikashb/xgboost/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:8:19: error: ‘fopen64’ undeclared (first use in this function); did you mean ‘fopen’?
   return ((int*)(&fopen64))[argc];
                   ^~~~~~~
                   fopen
/home/gvikashb/xgboost/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:8:19: note: each undeclared identifier is reported only once for each function it appears in
gmake[1]: *** [CMakeFiles/cmTC_0e2a9.dir/CheckSymbolExists.c.o] Error 1
gmake[1]: Leaving directory `/home/gvikashb/xgboost/build/CMakeFiles/CMakeTmp'
gmake: *** [cmTC_0e2a9/fast] Error 2

File /home/gvikashb/xgboost/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <stdio.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef fopen64
  return ((int*)(&fopen64))[argc];
#else
  (void)argc;
  return 0;
#endif
}`

**Comment by hcho3** [comment]
It appears that you don't have a working build chain. If you are using Ubuntu, for example, try running
```
sudo apt-get install build-essential
```

**Comment by trivialfis** [comment]
Closing as this is a toolchian issue.  A good way to test this issue is trying writing a test that uses threads with cmake: https://cmake.org/cmake/help/latest/module/FindThreads.html

**Comment by gokulanv** [comment]
Thanks for the help. I will look into this and let you know.
