### ISSUE TITLE
DeviceQuantileDMatrix Improvements

### ISSUE THREAD

**Issue by jamescolless** [dmlc/xgboost#6335]
When training on large amounts of data using a gpu the DeviceQuantileDMatrix is extremely useful in helping to avoid memory issues. In such situations it is however quite unfortunate that it is limited to 2^31-1000 elements (e.g. it cannot handle 10 million samples with 250 features). Is there any way this limitation might be removed?

Similarly it would be great if DeviceQuantileDMatrix was able to be used during external memory training (it seems as if only DMatrix is currently supported).

**Comment by hcho3** [comment]
The Thrust library currently has an integer overflow bug that prevents us from creating DeviceQuantileDMatrix that's larger than 2^31 elements. See #6228.

**Comment by jamescolless** [comment]
I see, thanks! Hopefully that gets resolved soon.

**Comment by hcho3** [comment]
Will be fixed in #6234
