### ISSUE TITLE
External memory improvements

### ISSUE THREAD

**Issue by jamescolless** [dmlc/xgboost#6336]
XGBoost external memory training (https://xgboost.readthedocs.io/en/latest/tutorials/external_memory.html) has been extremely useful when dealing with large dataset sizes, however it has a number of limitations:

- It takes as input a single file. This is suboptimal as typically large datasets are sharded across multiple files, ideally xgboost could consume a list of files to train from and read through them sequentially. 

- It expects that all the columns in the file (other than the label column) are feature columns. This is often annoying as frequently you want to try a particular subset of features, or potentially train to a different response. Currently (unless I misunderstand) doing either of these things requires writing a new file to disk which can often take several hours. Ideally you would be able to specify when constructing the DMatrix from the file on disk which indices correspond to the required features/responses.

**Comment by jamescolless** [comment]
Additionally, it would be great if DeviceQuantileDMatrix was able to be used during external memory training (it seems as if only DMatrix is currently supported).

**Comment by trivialfis** [comment]
That might not be possible for recent future. The DQD is designed to do things inplace.  Copying file from external memory to host memory then to device is very opposite to inplace.

**Comment by trivialfis** [comment]
Actually the ideal case would be a common iterator interface that can be used to iterate through batches of data in random order.  Think of the current external memory as a special case for batches of data read from files.

**Comment by trivialfis** [comment]
Closing this issue as the interface is here now.  But we still need to change internal algorithms to make it useful for training.
