### ISSUE TITLE
QUESTION: adding Dask in repo description

### ISSUE THREAD

**Issue by jameslamb** [dmlc/xgboost#6339]
I've been thinking about https://github.com/dask/community/issues/104 a lot the last few days, and I'd like to propose a small change that I think could help communication about XGBoost's support for Dask.

Given that `xgboost.dask` has been a part of the project for a while, would you consider adding Dask to the repo description, in the list where Spark and Flink are already mentioned?

![image](https://user-images.githubusercontent.com/7608904/98027955-08ed3380-1dd3-11eb-8792-65064af885ca.png)

**Comment by trivialfis** [comment]
Oops.  Mentioned it in readme but forgot the repo description.  Thanks for reminding.

**Comment by hcho3** [comment]
I've added Dask to the repo description. Thanks!
