### ISSUE TITLE
How to control the thread in the predict [R-package]

### ISSUE THREAD

**Issue by Lchiffon** [dmlc/xgboost#634]
Xgboost is great!

I have a small problem about threads of `predict` function in R-package.

- I trained a xgboost model **locally** and saved the model as a .Rdata file
- Load the .Rdata file in a server and predict

- When I predict the answer by something like:
```
 predict(.SD[1,model_local][[1]],newdata=...)
``` 

xgboost will use 32 threads of my server(I hope I can control how many threads I use)

Currently, I add some short training scripts like:
```
data(agaricus.train, package='xgboost')
data(agaricus.test, package='xgboost')
train <- agaricus.train
test <- agaricus.test
bst <- xgboost(data = train$data, label = train$label, max.depth = 2,
               eta = 1, nthread = 4, nround = 2,objective = "binary:logistic")
```

After that, the predict will use 4 threads instead.

**Comment by hetong007** [comment]
Do you mean the `nthread` param for `model_1` will affect the number of threads used when predicting on `model_2`?

**Comment by Lchiffon** [comment]
Yes, that's right.

**Comment by khotilov** [comment]
You may control the number of OpenMP threads by setting the OMP_NUM_THREADS environment variable to a needed value before starting R.
