### ISSUE TITLE
sklearn.py: fit() raises NAN error for eval_set

### ISSUE THREAD

**Issue by joristork** [dmlc/xgboost#635]
I'm not sure why the `eval_set` cannot have nans whereas the `X` parameter can.
**Steps to reproduce**: pass list of `(X, y)` where `X`, `y` are numpy arrays containing some `np.nan` values as `eval_set` to `fit()`.
**Error msg**: `There are NAN in the matrix, however, you did not set missing=NAN`
**Notable code**:
`l.169` in `sklearn.py:25c4fbd`:
```
evals = list(DMatrix(x[0], label=x[1]) for x in eval_set)
```
Adding `missing=self.missing` to that constructor results in another error:
```
/usr/local/lib/python3.5/site-packages/xgboost-0.4-py3.5.egg/xgboost/sklearn.py in get_params(self, deep)
    126     def get_params(self, deep=False):
    127         """Get parameter.s"""
--> 128         params = super(XGBModel, self).get_params(deep=deep)
    129         if params['missing'] is np.nan:
    130             params['missing'] = None  # sklearn doesn't handle nan. see #4725

TypeError: super(type, obj): obj must be an instance or subtype of type
```

**Comment by terrytangyuan** [comment]
Fixed via https://github.com/dmlc/xgboost/commit/7606bf8156289cba0e52bffd79cdbb0482f1ce30
