### ISSUE TITLE
How can i call xgboost model(trained in python) in c++?

### ISSUE THREAD

**Issue by nickhuangxinyu** [dmlc/xgboost#6356]
Assume I have a trained model, and i used save_model to save it down. How can i use it in c++?
Can you give me a demo code?

**Comment by trivialfis** [comment]
In c or c++?

**Comment by nickhuangxinyu** [comment]
c++

**Comment by nickhuangxinyu** [comment]
> In c or c++?

c++

**Comment by trivialfis** [comment]
Our c++ interface is unstable.  If you want to use it, see `tests/cpp/test_learner.cc` `TEST(Learner, JsonModelIO)` for JSON model and `TEST(Learner, BinaryModelIO)` for binary model as examples.
