### ISSUE TITLE
prediction with reg:tweedie on xgboost 0.60.0

### ISSUE THREAD

**Issue by paleyl** [dmlc/xgboost#6359]
I trained xgboost model using the version xgboost4j spark 1.1.1 and serving on a c++ framework using the version 0.60.0 . 
It works fine when I use reg:squarederror or reg:squaredlogerror, but when I use reg:tweedie, the prediction value on c++ turns out to be abnormal. I noticed the tweedie is supported only after 0.90.0, but is there any way that I can just predict using reg:tweedie model on a 0.60.0 version? Because it will cost a lot time to upgrade the c++ code.

**Comment by trivialfis** [comment]
Apply `log` to base_score and use `exp` on output prediction.  But honestly, just upgrade C++ code ...

**Comment by paleyl** [comment]
Figured it out by final_prediction = exp(p - base_score)/2
