### ISSUE TITLE
Compilation errors with RABIT_BUILD_MPI=ON

### ISSUE THREAD

**Issue by juanjgalvez** [dmlc/xgboost#6377]
Trying to build with RABIT_BUILD_MPI=ON fails because the interface of `MPIEngine` and `IEngine` doesn't match for several methods, like `virtual void Allgather`. Seems like the issue is just that the last three arguments of several methods of MPIEngine are no longer used.

EDIT: This is trying to build master on Linux and macOS.

**Comment by hcho3** [comment]
Thanks for reporting the issue. Would you like to take a shot at fixing it?

**Comment by juanjgalvez** [comment]
> Thanks for reporting the issue. Would you like to take a shot at fixing it?

I would be happy to submit a fix. What are the steps for contributing?

**Comment by hcho3** [comment]
You should submit a pull request. See tutorial on submitting pull requests: https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/proposing-changes-to-your-work-with-pull-requests

**Comment by trivialfis** [comment]
We need to discuss what we are going to do about the MPI backend.  It's still relying on old C++ interface.
