### ISSUE TITLE
Error training when using a CSV Location

### ISSUE THREAD

**Issue by gmazzei-chartboost** [dmlc/xgboost#6383]
When a training is done using a csv file.
The following line assumes X is an object that can support the shape property.
https://github.com/dmlc/xgboost/blob/e8884c4637da1439614ed48e06a2dee98548be3d/python-package/xgboost/sklearn.py#L516
In the case of a CSV file, X is a string, therefore giving an error. 
First  X has to be transformed into a DMatrix and maybe that conflicting line should be executed after you have the DMatrix when the csv file is already read and can support the shape method.

**Comment by hcho3** [comment]
The docstring says that `X` must be array-like:
https://github.com/dmlc/xgboost/blob/e8884c4637da1439614ed48e06a2dee98548be3d/python-package/xgboost/sklearn.py#L458-L459

So this is expected and not a bug. To load CSV, use [pandas.read_csv()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html) to obtain a `DataFrame` object and then pass it to `DMatrix` constructor.

**Comment by gmazzei-chartboost** [comment]
That self.n_features_in_ breaks all backwards compatibility. We are in particularly using csv files to do training with large CSV files that otherwise have to be in memory to be an "array-like".
Versions 1.1.1 and before allow to train models "off memory" using a csv files. I think even that the "docstring" says arraylike in all other versions was not used like that until the DMatrix is created.

**Comment by hcho3** [comment]
If you are interested in using CSV files directly, please use `xgb.train()` instead of `XGBRegressor.fit()`. It was never the intention that `XGBRegressor.fit()` should accept a path name.

**Comment by kanekotic** [comment]
is there a way to have a compatible random forest model out of the `xgb.train()` that can be loaded into an `XGBRegressor`. As per what I have understood the `Scikit-Learn API` is an abstraction over the `Learning API` for it to be compatible with sklearn. Are the booster models compatibles enough to move between one and the other without side effects?
