### ISSUE TITLE
Grammatical error Documentaion

### ISSUE THREAD

**Issue by Nikhil1O1** [dmlc/xgboost#6385]
`https://xgboost.readthedocs.io/en/latest/python/python_api.html#xgboost.DMatrix`
I have detected few errors in the above-given link, i can submit a pr but i don't know where to find the above file in the directory.
Please help me
@kashif

**Comment by hcho3** [comment]
You can update the docstrings in https://github.com/dmlc/xgboost/blob/master/python-package/xgboost/core.py#L372

**Comment by Nikhil1O1** [comment]
#6393 
Please look into it
@hcho3
