### ISSUE TITLE
XGBoost installation on AIX7.2 failed with missing file

### ISSUE THREAD

**Issue by bergen288** [dmlc/xgboost#6392]
I am trying to install xgboost_1.2.0.1.tar.gz on AIX7.2 without internet access.  It failed with following fatal error: ```fatal error: execinfo.h: No such file or directory```.  The complete log is attached.  

If I download xgboost-master.zip, unzip it, and trying to install with ```R CMD INSTALL -l /software/R/site-library xgboost-master```, it gives me invalid package name.  I don't have this error with other master packages before.  Any thoughts how to fix my issue?

Thanks.

```
Login=xzhang: Line=48 > R CMD INSTALL -l /software/R/site-library xgboost-master
Warning: invalid package 'xgboost-master'
Error: ERROR: no packages specified
``` 
[make.source.20201113.162847.log](https://github.com/dmlc/xgboost/files/5539479/make.source.20201113.162847.log)

**Comment by hcho3** [comment]
We use git submodules to manage a few dependencies, so the usual download method for the source `xgboost-master.zip` won't work, as it does not include the submodules.

You should try to get `xgboost_1.2.0.1.tar.gz` to work. My suggestion is to extract the tar file and then apply the following patch to the file `src/dmlc-core/include/dmlc/build_config_default.h`:
```diff
--- build_config_default.h	2020-09-01 17:18:05.000000000 -0700
+++ build_config_default.h.new	2020-11-16 19:40:12.000000000 -0800
@@ -16,20 +16,6 @@
   #define fopen64 std::fopen
 #endif
 
-/* default logic for stack trace */
-#if (defined(__GNUC__) && !defined(__MINGW32__)\
-     && !defined(__sun) && !defined(__SVR4)\
-     && !(defined __MINGW64__) && !(defined __ANDROID__))\
-     && !defined(__CYGWIN__) && !defined(__EMSCRIPTEN__)\
-     && !defined(__RISCV__) && !defined(__hexagon__)
-  #ifndef DMLC_LOG_STACK_TRACE
-  #define DMLC_LOG_STACK_TRACE 1
-  #endif
-  #ifndef DMLC_LOG_STACK_TRACE_SIZE
-  #define DMLC_LOG_STACK_TRACE_SIZE 10
-  #endif
-  #define DMLC_EXECINFO_H <execinfo.h>
-#endif
 
 /* default logic for detecting existence of nanosleep() */
 #if !(defined _WIN32) || (defined __CYGWIN__)
```

Then run `R CMD INSTALL .` at the root of the extracted `xgboost/` directory to install XGBoost with the patch applied.

**Comment by bergen288** [comment]
xgboost_1.2.0.1.tar.gz is extracted to /software/R/source/xgboost.  Your patch contents above is saved as build_config_default.h.patch in /software/R/source/xgboost/src/dmlc-core/include/dmlc.  However, my patch is stopped at line 5 with ```patch: 3016-037 Malformed patch at line 5:  #endif``` as shown below.

This is my 1st time to apply patch, so bear with me.  Thanks.

```
Login=xzhang: Line=21 > patch < build_config_default.h.patch
Processing...  Looks like a unified context diff...
The text leading up to this was:
--------------------------
|--- build_config_default.h     2020-09-01 17:18:05.000000000 -0700
|+++ build_config_default.h.new 2020-11-16 19:40:12.000000000 -0800
--------------------------
Patching file build_config_default.h using Plan A...
patch: 3016-037 Malformed patch at line 5:  #endif
```

**Comment by hcho3** [comment]
You should manually delete the highlighted lines.

**Comment by bergen288** [comment]
The highlighted lines are deleted manually.  This time, there is no error for all g++ compiles.  But it failed with the following error.  See attached log.

Thanks.

```
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for 'xgboost' in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/software/R/site-library/00LOCK-xgboost/00new/xgboost/libs/xgboost.so':
  rtld: 0712-001 Symbol _ZNSt18condition_variable10notify_oneEv was referenced
      from module /software/R/site-library/00LOCK-xgboost/00new/xgboost/libs/xgboost.so(), but a runtime definition
      of the symbol was not found.
rtld: 0712-001 Symbol _ZNSt18condition_variable4waitERSt11unique_lockISt5mutexE was referenced
      from module /software/R/site-library/00LOCK-xgboost/00new/xgboost/libs/xgboost.so(), but a runtime definition
      of the symbol was not found.
rtld: 0712-001 Symbol _ZNSt6thread4joinEv was referenced
      from module /software/R/site-library/00LOCK-xgboost/00new/xgboost/libs/xgboost.so(), but a runtime definition
      of the symbol was not found.
rtld: 0712-001 Symbol _ZNSt18condition_variableD1Ev was referenced
      from module /software/R/site-library/00LOCK-xgboost/00new/xgboost/libs/xgboost.so(), but a runtime definition
      of the symbol was not fo
Error: loading failed
Execution halted
ERROR: loading failed
* removing '/software/R/site-library/xgboost'
``` 
[xgboost.log](https://github.com/dmlc/xgboost/files/5554281/xgboost.log)

**Comment by hcho3** [comment]
It appears that the threading library from the Standard C++ is not available on your platform.

**Comment by bergen288** [comment]
My g++ is ```g++ (GCC) 8.3.0```.  Will it help to upgrade gcc/g++ version?

**Comment by hcho3** [comment]
I have no idea. Can you compile a sample program using `std::thread`?

**Comment by bergen288** [comment]
The following is my test code saved as ```my_thread_test.cpp```.  I can compile it successfully with ```g++ -std=c++11 -pthread -o hello my_thread_test.cpp```.  

```
#include <string>
#include <iostream>
#include <thread>

using namespace std;

void task1()
{
    cout << "Hello World\n";
}

void task2()
{
    cout << "Howdy\n";
}

int main()
{
    std::thread t1 = std::thread(task1);
    t1.join();
    std::thread t2 = std::thread(task2);
    t2.join();
    return 0;
}
```
Now, I can run "hello" as below so std::thread should be working fine.

```
Login=xzhang: Line=31 > hello
Hello World
Howdy
```

**Comment by hcho3** [comment]
Also try building a shared lib?

**Comment by bergen288** [comment]
I am not C++ program.  Can you tell me what to do?

Thanks.

**Comment by hcho3** [comment]
Try building this program:
```cpp
#include <string>
#include <iostream>
#include <thread>

using namespace std;

void task1()
{
    cout << "Hello World\n";
}

void task2()
{
    cout << "Howdy\n";
}

void myfunc()
{
    std::thread t1 = std::thread(task1);
    t1.join();
    std::thread t2 = std::thread(task2);
    t2.join();
}
```

The command should be `g++ -std=c++11 -pthread -shared -o hello.so my_thread_test.cpp`.

**Comment by bergen288** [comment]
```g++ -std=c++11 -pthread -shared -o hello.so my_thread_test.cpp``` finished successfully.  Below are files in my current directory:
```
-rwxrwxr-x-    1 xzhang   xzhang        39093 Nov 17 11:21 hello
-rwxrwxr-x-    1 xzhang   xzhang        45657 Nov 17 13:34 hello.so
-rw--------    1 xzhang   xzhang          308 Nov 17 11:21 my_thread_test.cpp
-rwxrwxr-x-    1 xzhang   xzhang          149 Nov 17 13:39 say_hello.py
```
```say_hello.py``` has the following code:
```
#!/bin/python
import ctypes
lib = ctypes.cdll.LoadLibrary('./hello.so')
lib.myfunc()
```
It failed with the following error:
```
Login=xzhang: Line=64 > say_hello.py
Traceback (most recent call last):
  File "say_hello.py", line 5, in <module>
    lib = ctypes.cdll.LoadLibrary('./hello.so')
  File "/opt/freeware/lib64/python3.7/ctypes/__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "/opt/freeware/lib64/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError:        0509-022 Cannot load module ./hello.so.
        0509-026 System error: Cannot run a file that does not have a valid format.
```

**Comment by hcho3** [comment]
I'm out of ideas. Please reach out to IBM support with regards to inability to compile a working shared library and use `std::thread`.
