### ISSUE TITLE
hangs with dask fit on heterogeneous nodes of GPU

### ISSUE THREAD

**Issue by pseudotensor** [dmlc/xgboost#6397]
I get persistent hangs with dask xgboost fit if I ever use nodes with different GPU counts, even if each node runs with dask-cuda-worker and generate 1 process/GPU.  No such problems with intrinsic dask operations

E.g. I have

![image](https://user-images.githubusercontent.com/2249614/99161726-05e32480-26aa-11eb-847d-8bee702b1f8f.png)

nodes have 2, 2, 1, 4 GPUs.  All workers accounted for.  While normal dask operations work fine, xgboost does not.

The client code is stuck here:
```
Current thread 0x0000147efbfff700 (most recent call first):
  File "/home/jon/minicondadai/lib/python3.6/threading.py", line 299 in wait
  File "/home/jon/minicondadai/lib/python3.6/threading.py", line 551 in wait
  File "/home/jon/minicondadai/lib/python3.6/site-packages/distributed/utils.py", line 336 in sync
  File "/home/jon/minicondadai/lib/python3.6/site-packages/distributed/client.py", line 824 in sync
  File "/home/jon/minicondadai/lib/python3.6/site-packages/xgboost/dask.py", line 1080 in fit
```

The dask array handling worked fine, just the fit hangs like this.

for xgboost 1.2 rapids 0.14 Ubuntu 18.04.

Have such cases been tested by xgboost or NVIDIA teams?  I think I don't always get hangs, but they are pretty common.

Here's basic script: https://github.com/dmlc/xgboost/issues/6388#issuecomment-726675852  that @teju85 wrote based on another issue.

But I just have those 4 nodes with different GPU counts, hangs every time even for 1000 rows only.

**Comment by trivialfis** [comment]
Can you try nightly?

**Comment by trivialfis** [comment]
@pseudotensor Any update?  We are about to make 1.3.1 patch release, good chance of fixing remaining dask issues.

**Comment by trivialfis** [comment]
I suspect this is caused by the same issue of https://github.com/dmlc/xgboost/issues/7019 .  Just tested with various node configurations on V100 clusters and they work fine.

**Comment by trivialfis** [comment]
@pseudotensor Could you please rerun this with the workaround found in https://github.com/dmlc/xgboost/issues/7019 ?

**Comment by pseudotensor** [comment]
It doesn't specifically hang with heterogeneous.  But other failures occur in general, will post separately
