### ISSUE TITLE
Unknown composition type using XGBOOST model within predict() statement.

### ISSUE THREAD

**Issue by mfcava** [dmlc/xgboost#6398]
After update XGBOOST package (latest release)  I'm no longer able to start my shiny application. 
The error I'm receiving it's:

```
Warning: Error in : Internal error: Unknown composition type.
69: 
Error : Internal error: Unknown composition type.

```

After some troubleshooting I've identify the the problem is related to the predict() statement in which I use an XgBoost model trained with an older version of the xgboost package.

I'm quite sure that this error is related to this update as, the same application works fine within another machine with the same R (4.0) and Shiny version (1.5). Booth are MacOs based.

**Comment by hcho3** [comment]
Can you post the R application code? We want to make sure whether it's XGBoost that's causing the error.

**Comment by mfcava** [comment]
Got some feedback from tidymodels developers and seems that error is not related to xgboost packages but to hardhat 0.1.5 
Sorry for opening this issue.
