### ISSUE TITLE
How to continue training model based on previously saved xgboost model in R?

### ISSUE THREAD

**Issue by hwu84** [dmlc/xgboost#640]
How to continue training model based on previously saved xgboost model in R? I know there is a method to load saved model and continue training it in console. I just want to know if we can do the same thing in R? Since when nround goes large, it is inefficient to retrain the same model with slightly different round again and again. Can anyone help? Thanks

**Comment by pommedeterresautee** [comment]
If you are looking for the best number of rounds, the easiest way is to train for a high number of rounds and then reduce your prediction to N first trees.

Kind regards,
Michael

**Comment by tonyrajan** [comment]
Regardless of the nround, is it possible to continue training from a previously saved xgboost model in R? 
In the command line Parameters, there are Parameters, Task & Model_in which could facilitate the same. How do we implement the training continuation in R using these parameters?
Thanks,
Tony
