### ISSUE TITLE
precision different between libsvm and csv data format on same dataset

### ISSUE THREAD

**Issue by Yanghello** [dmlc/xgboost#6401]
I train model based on xgboost on dataset mnist, with the follow two data formats, the evalution error is different(libsvm format is higher), may be some bugs in DMatrix or CSVParser class.

`#dtrain = xgboost.DMatrix("mnist.train.csv?format=csv&label_column=0")
#dval = xgboost.DMatrix("mnist.train.csv?format=csv&label_column=0")

dtrain = xgboost.DMatrix("mnist.train")
dval = xgboost.DMatrix("mnist.train")`

data dowload from https://www.kaggle.com/oddrationale/mnist-in-csv,
while data format converting to libsvm use  https://github.com/zygmuntz/phraug/blob/master/csv2libsvm.py

**Comment by hcho3** [comment]
The conversion script treats 0.0 as the missing value, whereas `xgboost.DMatrix` does not.

You should use Pandas to read the CSV file and then replace all zeros with missing
```python
import numpy as np
import pandas as pd

df = pd.read_csv('mnist.train.csv')
df = df.replace(0, np.nan)
X, y = df.iloc[:,1:], df.iloc[:, 0]

dtrain = xgboost.DMatrix(X, label=y, missing=np.nan)
```
