### ISSUE TITLE
xgb.rabit.get_rank() got wrong rank number

### ISSUE THREAD

**Issue by wulikai1993** [dmlc/xgboost#6402]
I ran distributed training on k8s as this [kubeflow example](https://github.com/kubeflow/xgboost-operator/tree/master/config/samples/xgboost-dist)

The `rank` number was got by `extract_xgbooost_cluster_env()` as in https://github.com/kubeflow/xgboost-operator/blob/master/config/samples/xgboost-dist/train.py#L29 

However, `xgb.rabit.get_rank()` got another `rank` number as in https://github.com/kubeflow/xgboost-operator/blob/master/config/samples/xgboost-dist/train.py#L57.

There are two things confusing me:
1. Now that `extract_xgbooost_cluster_env()` had got the `rank` number, why use`xgb.rabit.get_rank()` to get `rank` number again?
2. Why are the two `rank` numbers different?

**Comment by trivialfis** [comment]
@terrytangyuan

**Comment by trivialfis** [comment]
Not being familiar with the kube binding.  Here's a possible explanation after skimming through that example:

The first rank came from k8s cluster, which is the worker id used by k8s.  Internally xgboost also needs a mpi like message passing framework, which is rabit.  So rabit has it's own allreduce tree/ring, which will generate worker id (aka. rank) for its own use.

**Comment by wulikai1993** [comment]
> which will generate worker id (aka. rank) for its own use.

How does rabit allocate rank id to each worker? According to some evns? Is there any docs about this?

**Comment by trivialfis** [comment]
There's no doc around it and it's considered internal.

**Comment by wulikai1993** [comment]
Fine. So there is no official usage example either.

**Comment by trivialfis** [comment]
Reopened for documentation.

**Comment by trivialfis** [comment]
I don't quite understand why are those exposed in samples.  Ideally users should not need to interact with rabit.

**Comment by wulikai1993** [comment]
Users want to use the master node to save model and training logs, while other worker nodes to do training task only. So we need to identify the rank number of each node.
This is something like the `TF_CONFIG` envs variables in distributed TensorFlow.

**Comment by trivialfis** [comment]
There's no master node for xgboost, only workers and a tracker.  The tracker can be ignored as it's only useful for initialing allreduce tree.  You can take a look into our dask interface (which also supports running on k8s when using master branch): https://xgboost.readthedocs.io/en/latest/tutorials/dask.html

**Comment by trivialfis** [comment]
Right now for running on k8s with Python env, I recommend using dask interface.  For further question please open issue on corresponding repo.
