### ISSUE TITLE
Install xgboost_1.2.0.1.tar.gz from RStudio on AWS

### ISSUE THREAD

**Issue by JerryX2014** [dmlc/xgboost#6404]
** System **
Linux system on AWS

**Command in RStudio:**
install.packages('/home/users/xgboost_1.2.0.1.tar.gz',repos = NULL)

**Full messages:**
Installing package into ‘/home/users/R/x86_64-pc-linux-gnu-library/3.5’
(as ‘lib’ is unspecified)
* installing *source* package ‘xgboost’ ...
** package ‘xgboost’ successfully unpacked and MD5 sums checked
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking Backtrace lib... 
checking for backtrace in -lexecinfo... no
checking endian... 
configure: creating ./config.status
config.status: creating src/Makevars
** libs
Makevars:17: -DXGBOOST_STRICT_R_MODE=1
Makevars:17: -DDMLC_LOG_BEFORE_THROW=0
Makevars:17: -DDMLC_ENABLE_STD_THREAD=1
Makevars:17: -DDMLC_DISABLE_STDIN=1
Makevars:17: -DDMLC_LOG_CUSTOMIZE=1
Makevars:17: -DXGBOOST_CUSTOMIZE_LOGGER=1
Makevars:17: -DRABIT_CUSTOMIZE_MSG_
Makevars:17: -DRABIT_STRICT_CXX98_
g++ -std=c++1y  -I"/opt/anaconda3/envs/PY36_R35/lib/R/include" -DNDEBUG -I./include -I./dmlc-core/include -I./rabit/include -I. -DXGBOOST_STRICT_R_MODE=1 -DDMLC_LOG_BEFORE_THROW=0 -DDMLC_ENABLE_STD_THREAD=1 -DDMLC_DISABLE_STDIN=1 -DDMLC_LOG_CUSTOMIZE=1 -DXGBOOST_CUSTOMIZE_LOGGER=1 -DRABIT_CUSTOMIZE_MSG_ -DRABIT_STRICT_CXX98_  -I/opt/anaconda3/envs/PY36_R35/include  -fopenmp -DDMLC_CMAKE_LITTLE_ENDIAN=1 -pthread    -c xgboost_R.cc -o xgboost_R.o
g++ -std=c++1y  -I"/opt/anaconda3/envs/PY36_R35/lib/R/include" -DNDEBUG -I./include -I./dmlc-core/include -I./rabit/include -I. -DXGBOOST_STRICT_R_MODE=1 -DDMLC_LOG_BEFORE_THROW=0 -DDMLC_ENABLE_STD_THREAD=1 -DDMLC_DISABLE_STDIN=1 -DDMLC_LOG_CUSTOMIZE=1 -DXGBOOST_CUSTOMIZE_LOGGER=1 -DRABIT_CUSTOMIZE_MSG_ -DRABIT_STRICT_CXX98_  -I/opt/anaconda3/envs/PY36_R35/include  -fopenmp -DDMLC_CMAKE_LITTLE_ENDIAN=1 -pthread    -c xgboost_custom.cc -o xgboost_custom.o
gcc -std=gnu99 -I"/opt/anaconda3/envs/PY36_R35/lib/R/include" -DNDEBUG -I./include -I./dmlc-core/include -I./rabit/include -I. -DXGBOOST_STRICT_R_MODE=1 -DDMLC_LOG_BEFORE_THROW=0 -DDMLC_ENABLE_STD_THREAD=1 -DDMLC_DISABLE_STDIN=1 -DDMLC_LOG_CUSTOMIZE=1 -DXGBOOST_CUSTOMIZE_LOGGER=1 -DRABIT_CUSTOMIZE_MSG_ -DRABIT_STRICT_CXX98_  -I/opt/anaconda3/envs/PY36_R35/include   -fpic  -I/opt/anaconda3/envs/PY36_R35/include  -c xgboost_assert.c -o xgboost_assert.o
gcc -std=gnu99 -I"/opt/anaconda3/envs/PY36_R35/lib/R/include" -DNDEBUG -I./include -I./dmlc-core/include -I./rabit/include -I. -DXGBOOST_STRICT_R_MODE=1 -DDMLC_LOG_BEFORE_THROW=0 -DDMLC_ENABLE_STD_THREAD=1 -DDMLC_DISABLE_STDIN=1 -DDMLC_LOG_CUSTOMIZE=1 -DXGBOOST_CUSTOMIZE_LOGGER=1 -DRABIT_CUSTOMIZE_MSG_ -DRABIT_STRICT_CXX98_  -I/opt/anaconda3/envs/PY36_R35/include   -fpic  -I/opt/anaconda3/envs/PY36_R35/include  -c init.c -o init.o
g++ -std=c++1y  -I"/opt/anaconda3/envs/PY36_R35/lib/R/include" -DNDEBUG -I./include -I./dmlc-core/include -I./rabit/include -I. -DXGBOOST_STRICT_R_MODE=1 -DDMLC_LOG_BEFORE_THROW=0 -DDMLC_ENABLE_STD_THREAD=1 -DDMLC_DISABLE_STDIN=1 -DDMLC_LOG_CUSTOMIZE=1 -DXGBOOST_CUSTOMIZE_LOGGER=1 -DRABIT_CUSTOMIZE_MSG_ -DRABIT_STRICT_CXX98_  -I/opt/anaconda3/envs/PY36_R35/include  -fopenmp -DDMLC_CMAKE_LITTLE_ENDIAN=1 -pthread    -c amalgamation/xgboost-all0.cc -o amalgamation/xgboost-all0.o
In file included from amalgamation/../src/metric/elementwise_metric.cc:7:0,
                 from amalgamation/xgboost-all0.cc:14:
amalgamation/../src/metric/elementwise_metric.cu: In constructor ‘xgboost::metric::EvalEWiseBase<Policy>::EvalEWiseBase() [with Policy = xgboost::metric::EvalRowRMSE]’:
amalgamation/../src/metric/elementwise_metric.cu:328:3: error: converting to ‘xgboost::metric::ElementWiseMetricsReduction<xgboost::metric::EvalRowRMSE>’ from initializer list would use explicit constructor ‘xgboost::metric::ElementWiseMetricsReduction<EvalRow>::ElementWiseMetricsReduction(EvalRow) [with EvalRow = xgboost::metric::EvalRowRMSE]’
   EvalEWiseBase() = default;
   ^
amalgamation/../src/metric/elementwise_metric.cu: In lambda function:
amalgamation/../src/metric/elementwise_metric.cu:365:73: note: synthesized method ‘xgboost::metric::EvalEWiseBase<Policy>::EvalEWiseBase() [with Policy = xgboost::metric::EvalRowRMSE]’ first required here 
 .set_body([](const char* param) { return new EvalEWiseBase<EvalRowRMSE>(); });
                                                                         ^
amalgamation/../src/metric/elementwise_metric.cu: In constructor ‘xgboost::metric::EvalEWiseBase<Policy>::EvalEWiseBase() [with Policy = xgboost::metric::EvalRowRMSLE]’:
amalgamation/../src/metric/elementwise_metric.cu:328:3: error: converting to ‘xgboost::metric::ElementWiseMetricsReduction<xgboost::metric::EvalRowRMSLE>’ from initializer list would use explicit constructor ‘xgboost::metric::ElementWiseMetricsReduction<EvalRow>::ElementWiseMetricsReduction(EvalRow) [with EvalRow = xgboost::metric::EvalRowRMSLE]’
   EvalEWiseBase() = default;
   ^
amalgamation/../src/metric/elementwise_metric.cu: In lambda function:
amalgamation/../src/metric/elementwise_metric.cu:369:74: note: synthesized method ‘xgboost::metric::EvalEWiseBase<Policy>::EvalEWiseBase() [with Policy = xgboost::metric::EvalRowRMSLE]’ first required here 
 .set_body([](const char* param) { return new EvalEWiseBase<EvalRowRMSLE>(); });
                                                                          ^
amalgamation/../src/metric/elementwise_metric.cu: In constructor ‘xgboost::metric::EvalEWiseBase<Policy>::EvalEWiseBase() [with Policy = xgboost::metric::EvalRowMAE]’:
amalgamation/../src/metric/elementwise_metric.cu:328:3: error: converting to ‘xgboost::metric::ElementWiseMetricsReduction<xgboost::metric::EvalRowMAE>’ from initializer list would use explicit constructor ‘xgboost::metric::ElementWiseMetricsReduction<EvalRow>::ElementWiseMetricsReduction(EvalRow) [with EvalRow = xgboost::metric::EvalRowMAE]’
   EvalEWiseBase() = default;
   ^
amalgamation/../src/metric/elementwise_metric.cu: In lambda function:
amalgamation/../src/metric/elementwise_metric.cu:373:72: note: synthesized method ‘xgboost::metric::EvalEWiseBase<Policy>::EvalEWiseBase() [with Policy = xgboost::metric::EvalRowMAE]’ first required here 
 .set_body([](const char* param) { return new EvalEWiseBase<EvalRowMAE>(); });
                                                                        ^
amalgamation/../src/metric/elementwise_metric.cu: In constructor ‘xgboost::metric::EvalEWiseBase<Policy>::EvalEWiseBase() [with Policy = xgboost::metric::EvalRowMPHE]’:
amalgamation/../src/metric/elementwise_metric.cu:328:3: error: converting to ‘xgboost::metric::ElementWiseMetricsReduction<xgboost::metric::EvalRowMPHE>’ from initializer list would use explicit constructor ‘xgboost::metric::ElementWiseMetricsReduction<EvalRow>::ElementWiseMetricsReduction(EvalRow) [with EvalRow = xgboost::metric::EvalRowMPHE]’
   EvalEWiseBase() = default;
   ^
amalgamation/../src/metric/elementwise_metric.cu: In lambda function:
amalgamation/../src/metric/elementwise_metric.cu:377:73: note: synthesized method ‘xgboost::metric::EvalEWiseBase<Policy>::EvalEWiseBase() [with Policy = xgboost::metric::EvalRowMPHE]’ first required here 
 .set_body([](const char* param) { return new EvalEWiseBase<EvalRowMPHE>(); });
                                                                         ^
amalgamation/../src/metric/elementwise_metric.cu: In constructor ‘xgboost::metric::EvalEWiseBase<Policy>::EvalEWiseBase() [with Policy = xgboost::metric::EvalRowLogLoss]’:
amalgamation/../src/metric/elementwise_metric.cu:328:3: error: converting to ‘xgboost::metric::ElementWiseMetricsReduction<xgboost::metric::EvalRowLogLoss>’ from initializer list would use explicit constructor ‘xgboost::metric::ElementWiseMetricsReduction<EvalRow>::ElementWiseMetricsReduction(EvalRow) [with EvalRow = xgboost::metric::EvalRowLogLoss]’
   EvalEWiseBase() = default;
   ^
amalgamation/../src/metric/elementwise_metric.cu: In lambda function:
amalgamation/../src/metric/elementwise_metric.cu:381:76: note: synthesized method ‘xgboost::metric::EvalEWiseBase<Policy>::EvalEWiseBase() [with Policy = xgboost::metric::EvalRowLogLoss]’ first required here 
 .set_body([](const char* param) { return new EvalEWiseBase<EvalRowLogLoss>(); });
                                                                            ^
amalgamation/../src/metric/elementwise_metric.cu: In constructor ‘xgboost::metric::EvalEWiseBase<Policy>::EvalEWiseBase() [with Policy = xgboost::metric::EvalPoissonNegLogLik]’:
amalgamation/../src/metric/elementwise_metric.cu:328:3: error: converting to ‘xgboost::metric::ElementWiseMetricsReduction<xgboost::metric::EvalPoissonNegLogLik>’ from initializer list would use explicit constructor ‘xgboost::metric::ElementWiseMetricsReduction<EvalRow>::ElementWiseMetricsReduction(EvalRow) [with EvalRow = xgboost::metric::EvalPoissonNegLogLik]’
   EvalEWiseBase() = default;
   ^
amalgamation/../src/metric/elementwise_metric.cu: In lambda function:
amalgamation/../src/metric/elementwise_metric.cu:385:82: note: synthesized method ‘xgboost::metric::EvalEWiseBase<Policy>::EvalEWiseBase() [with Policy = xgboost::metric::EvalPoissonNegLogLik]’ first required here 
 .set_body([](const char* param) { return new EvalEWiseBase<EvalPoissonNegLogLik>(); });
                                                                                  ^
amalgamation/../src/metric/elementwise_metric.cu: In constructor ‘xgboost::metric::EvalEWiseBase<Policy>::EvalEWiseBase() [with Policy = xgboost::metric::EvalGammaDeviance]’:
amalgamation/../src/metric/elementwise_metric.cu:328:3: error: converting to ‘xgboost::metric::ElementWiseMetricsReduction<xgboost::metric::EvalGammaDeviance>’ from initializer list would use explicit constructor ‘xgboost::metric::ElementWiseMetricsReduction<EvalRow>::ElementWiseMetricsReduction(EvalRow) [with EvalRow = xgboost::metric::EvalGammaDeviance]’
   EvalEWiseBase() = default;
   ^
amalgamation/../src/metric/elementwise_metric.cu: In lambda function:
amalgamation/../src/metric/elementwise_metric.cu:389:79: note: synthesized method ‘xgboost::metric::EvalEWiseBase<Policy>::EvalEWiseBase() [with Policy = xgboost::metric::EvalGammaDeviance]’ first required here 
 .set_body([](const char* param) { return new EvalEWiseBase<EvalGammaDeviance>(); });
                                                                               ^
amalgamation/../src/metric/elementwise_metric.cu: In constructor ‘xgboost::metric::EvalEWiseBase<Policy>::EvalEWiseBase() [with Policy = xgboost::metric::EvalGammaNLogLik]’:
amalgamation/../src/metric/elementwise_metric.cu:328:3: error: converting to ‘xgboost::metric::ElementWiseMetricsReduction<xgboost::metric::EvalGammaNLogLik>’ from initializer list would use explicit constructor ‘xgboost::metric::ElementWiseMetricsReduction<EvalRow>::ElementWiseMetricsReduction(EvalRow) [with EvalRow = xgboost::metric::EvalGammaNLogLik]’
   EvalEWiseBase() = default;
   ^
amalgamation/../src/metric/elementwise_metric.cu: In lambda function:
amalgamation/../src/metric/elementwise_metric.cu:393:78: note: synthesized method ‘xgboost::metric::EvalEWiseBase<Policy>::EvalEWiseBase() [with Policy = xgboost::metric::EvalGammaNLogLik]’ first required here 
 .set_body([](const char* param) { return new EvalEWiseBase<EvalGammaNLogLik>(); });
                                                                              ^
In file included from amalgamation/../src/objective/rank_obj.cc:16:0,
                 from amalgamation/xgboost-all0.cc:23:
amalgamation/../src/objective/rank_obj.cu: In static member function ‘static void xgboost::obj::NDCGLambdaWeightComputer::GetLambdaWeight(const std::vector<xgboost::obj::ListEntry>&, std::vector<xgboost::obj::LambdaPair>*)’:
amalgamation/../src/objective/rank_obj.cu:317:67: error: wrong number of template arguments (0, should be 1)
       std::stable_sort(labels.begin(), labels.end(), std::greater<>());
                                                                   ^
In file included from /usr/include/c++/4.8.2/bits/stl_tree.h:63:0,
                 from /usr/include/c++/4.8.2/map:60,
                 from ./dmlc-core/include/dmlc/registry.h:9,
                 from amalgamation/../src/metric/metric.cc:6,
                 from amalgamation/xgboost-all0.cc:13:
/usr/include/c++/4.8.2/bits/stl_function.h:222:12: error: provided for ‘template<class _Tp> struct std::greater’
     struct greater : public binary_function<_Tp, _Tp, bool>
            ^
In file included from ./include/xgboost/logging.h:14:0,
                 from ./include/xgboost/generic_parameters.h:8,
                 from ./include/xgboost/metric.h:12,
                 from amalgamation/../src/metric/metric.cc:7,
                 from amalgamation/xgboost-all0.cc:13:
amalgamation/../src/tree/updater_histmaker.cc: In member function ‘virtual void xgboost::tree::GlobalProposalHistMaker::CreateHist(const std::vector<xgboost::detail::GradientPairInternal<float>, std::allocator<xgboost::detail::GradientPairInternal<float> > >&, xgboost::DMatrix*, const std::vector<unsigned int>&, const xgboost::RegTree&)’:
amalgamation/../src/tree/updater_histmaker.cc:702:39: error: wrong number of template arguments (0, should be 1)
                             std::less<>{});
                                       ^
./include/xgboost/base.h:60:72: note: in definition of macro ‘XGBOOST_PARALLEL_SORT’
 #define XGBOOST_PARALLEL_SORT(X, Y, Z) __gnu_parallel::sort((X), (Y), (Z))
                                                                        ^
In file included from /usr/include/c++/4.8.2/bits/stl_tree.h:63:0,
                 from /usr/include/c++/4.8.2/map:60,
                 from ./dmlc-core/include/dmlc/registry.h:9,
                 from amalgamation/../src/metric/metric.cc:6,
                 from amalgamation/xgboost-all0.cc:13:
/usr/include/c++/4.8.2/bits/stl_function.h:231:12: error: provided for ‘template<class _Tp> struct std::less’
     struct less : public binary_function<_Tp, _Tp, bool>
            ^
In file included from amalgamation/xgboost-all0.cc:69:0:
amalgamation/../src/learner.cc: In member function ‘virtual void xgboost::LearnerConfiguration::SaveConfig(xgboost::Json*) const’:
amalgamation/../src/learner.cc:372:24: error: invalid initialization of non-const reference of type ‘xgboost::Json&’ from an rvalue of type ‘<brace-enclosed initializer list>’
     Json& out { *p_out };
                        ^
amalgamation/../src/learner.cc: In member function ‘virtual void xgboost::LearnerIO::SaveModel(xgboost::Json*) const’:
amalgamation/../src/learner.cc:646:24: error: invalid initialization of non-const reference of type ‘xgboost::Json&’ from an rvalue of type ‘<brace-enclosed initializer list>’
     Json& out { *p_out };
                        ^
make: *** [amalgamation/xgboost-all0.o] Error 1
ERROR: compilation failed for package ‘xgboost’
* removing ‘/home/users/R/x86_64-pc-linux-gnu-library/3.5/xgboost’
Warning in install.packages :
  installation of package ‘/home/users/xgboost_1.2.0.1.tar.gz’ had non-zero exit status

**Comment by hcho3** [comment]
XGBoost requires a recent C++ compiler that supports the C++14 standard: for example, GCC 5+.

**Comment by JerryX2014** [comment]
Got you. Thanks!
