### ISSUE TITLE
Question about save_name parameter.

### ISSUE THREAD

**Issue by hwu84** [dmlc/xgboost#641]
I tried to use the save_period and save_name parameter in R. Suppose I have 100 round and save_period = 20, save_name = "model", it seems that every 20 round, xgboost will write the model into same file "model"? and I only have the latest model at the end? 
Can I save the model every 20 round and write them to separate 5 model files?
Thanks

**Comment by pommedeterresautee** [comment]
In the current implementation it is not possible but why you would want such feature?
In predict() function you have a parameter ntreelimit to limit the number of tree to use.

If I answered your question, please close the issue.

Kind regards,
Michael

**Comment by hwu84** [comment]
@pommedeterresautee Thank you so much!
