### ISSUE TITLE
Libsvm, missings and zeros

### ISSUE THREAD

**Issue by mahdi-ghelichi** [dmlc/xgboost#6420]
If I write zeros into libsvm, would the xgb be able to distinguish zero and Nan in this case?
Assume [4, 0, Nan, 12] is writen as 0:4 1:0 3:12 in libsvm.
Does xgb treats the Nan (which has disappeared in libsvm) as actual missing or not?
I assume that the 0 will be treated like an actual zero in this case (and not a missing).

**Comment by hcho3** [comment]
That's correct, XGBoost will distinguish between 0 and missing values.
