### ISSUE TITLE
[RFC] 1.3.0 Release Candidate

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#6422]
Roadmap: #6031

We are about to release version 1.3.0 of XGBoost. In the next two weeks, we invite everyone to try out the release candidate (RC).

Feedback period: until the end of **December 7, 2020**. No new feature will be added to the release; only critical bug fixes will be added.

@dmlc/xgboost-committer

**Now available**

**Python package**. RC1 available on PyPI. Try it out with the command
```
python -m pip install xgboost==1.3.0rc1
```

* **R package**. RC1 available from [the Releases section](https://github.com/dmlc/xgboost/releases/tag/v1.3.0rc1). Download the tarball file xgboost_1.3.0.1.tar.gz and run
```
R CMD INSTALL xgboost_1.3.0.1.tar.gz
```

* **JVM packages**. RC1 available from our Maven repository. Add XGBoost4J as dependency to your Java application.

<details><summary>Show instructions (Maven/SBT)</summary>
<p>

Maven
```xml
<dependencies>
  ...
  <dependency>
      <groupId>ml.dmlc</groupId>
      <artifactId>xgboost4j_2.12</artifactId>
      <version>1.3.0-RC1</version>
  </dependency>
  <dependency>
      <groupId>ml.dmlc</groupId>
      <artifactId>xgboost4j-spark_2.12</artifactId>
      <version>1.3.0-RC1</version>
  </dependency>
</dependencies>

<repositories>
  <repository>
    <id>XGBoost4J Release Repo</id>
    <name>XGBoost4J Release Repo</name>
    <url>https://s3-us-west-2.amazonaws.com/xgboost-maven-repo/release/</url>
  </repository>
</repositories>
```

SBT
```scala
libraryDependencies ++= Seq(
  "ml.dmlc" %% "xgboost4j" % "1.3.0-RC1",
  "ml.dmlc" %% "xgboost4j-spark" % "1.3.0-RC1"
)
resolvers += ("XGBoost4J Release Repo"
              at "https://s3-us-west-2.amazonaws.com/xgboost-maven-repo/release/")
```
</p>
</details>

Starting from 1.2.0, XGBoost4J-Spark supports training with NVIDIA GPUs. To enable this capability, download artifacts suffixed with `-gpu`, as follows:

<details><summary>Show instructions (Maven/SBT)</summary>
<p>

Maven
```xml
<dependencies>
  ...
  <dependency>
      <groupId>ml.dmlc</groupId>
      <artifactId>xgboost4j-gpu_2.12</artifactId>
      <version>1.3.0-RC1</version>
  </dependency>
  <dependency>
      <groupId>ml.dmlc</groupId>
      <artifactId>xgboost4j-spark-gpu_2.12</artifactId>
      <version>1.3.0-RC1</version>
  </dependency>
</dependencies>

<repositories>
  <repository>
    <id>XGBoost4J Release Repo</id>
    <name>XGBoost4J Release Repo</name>
    <url>https://s3-us-west-2.amazonaws.com/xgboost-maven-repo/release/</url>
  </repository>
</repositories>
```

SBT
```scala
libraryDependencies ++= Seq(
  "ml.dmlc" %% "xgboost4j-gpu" % "1.3.0-RC1",
  "ml.dmlc" %% "xgboost4j-spark-gpu" % "1.3.0-RC1"
)
resolvers += ("XGBoost4J Release Repo"
              at "https://s3-us-west-2.amazonaws.com/xgboost-maven-repo/release/")
```
</p>
</details>

**Breaking changes**:
* Starting from 1.3.0 release, XGBoost no longer supports MacOS 10.13 (High Sierra).

**Known issue**:
* Python packaging does not yet work with MacOS 11.0 (Big Sur): https://github.com/pypa/packaging/pull/319. Users of Big Sur cannot use the binary wheel and will need to build XGBoost from the source.

### Outstanding patches that should make it into the 1.3.0 release:
To be merged after RC1:
- [x] #6423
- [x] #6358
- [x] #6434
- [x] #6439
- [x] #6441
- [x] #6459
- [x] #6455
- [x] #6342 
- [x] #6461
- [x] #6466
- [x] #6467
- [x] #6475

**Comment by trivialfis** [comment]
Is there an update on github release page?

**Comment by 7starsea** [comment]
I hope that the hidden api `XGBoosterPredictFromDense` could be included in the file c_api.h and we can clearly document that `cache_id` must be zero currently.
As I learned from python api `inplace_predict`, `XGBoosterPredictFromDense` is very useful for multiple threads prediction in c/cpp application.

**Comment by trivialfis** [comment]
It will be in the next release.

**Comment by terrytangyuan** [comment]
> "Starting from 1.3.0 release, XGBoost no longer supports MacOS 10.13 (High Sierra)."

This won't be a deprecation notice though since we are dropping the support in this release.

**Comment by hcho3** [comment]
@trivialfis I put up the release page for 1.3.0 RC1.
@terrytangyuan Thanks. Revised it to say "Breaking changes."

**Comment by hcho3** [comment]
Should #6342 be part of 1.3.0? @trivialfis
