### ISSUE TITLE
R package build stuck at CRAN installation

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#6424]
hey @hcho3  I have a very similar issue with installing the latest xgboost on my RStudio server on AWS EC2. 
The compilation stops and is stuck for hours at one point forcing me to Stop my EC2 instance everytime. 

I have detailed my issue at https://stackoverflow.com/questions/64946612/xgboost-installation-stuck-on-rstudio-server-on-aws-ec2. However from whatever Googling I did, it seems the issue is about gcc version or something. I am complete newbie when it comes to aws, rstudio server, linux, everything. Please help ..

_Originally posted by @sherlockyGH in https://github.com/dmlc/xgboost/issues/6421#issuecomment-731731370_

**Comment by hcho3** [comment]
@sherlockyGH I have no idea why `install.packages('xgboost')` fails to work on your machine. Can you try building XGBoost using CMake as follows?
```
git clone --recursive https://github.com/dmlc/xgboost
cd xgboost
mkdir build
cd build
cmake .. -DR_LIB=ON
make -j$(nproc)
make install
```

**Comment by hcho3** [comment]
Also, make sure you are using sufficiently powerful EC2 instance. If you are using small instance like T2.micro, XGBoost may fail to build due to exhausted memory or CPU credit.

**Comment by sherlockyGH** [comment]
hey, thanks for reaching out. 

```
`rstudio@ip-172-31-35-26:~$ sudo apt install cmake
Reading package lists... Done
Building dependency tree       
Reading state information... Done
cmake is already the newest version (3.10.2-1ubuntu2.18.04.1).
0 upgraded, 0 newly installed, 0 to remove and 70 not upgraded.
rstudio@ip-172-31-35-26:~$ cd xgboost
rstudio@ip-172-31-35-26:~/xgboost$ cd build
rstudio@ip-172-31-35-26:~/xgboost/build$ cmake .. -DR_LIB=ON
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.13 or higher is required.  You are running version 3.10.2


-- Configuring incomplete, errors occurred!
```

I tried the above commands you gave. This is what it says, even though I have the latest cmake installed. Can you help with this  ?

**Comment by hcho3** [comment]
@sherlockyGH Please follow instructions from https://apt.kitware.com/ to obtain the latest CMake (3.19.0).

Also, please let us known what kind of EC2 instance you are using.

**Comment by sherlockyGH** [comment]
@hcho3 Yes, I have been using a t2.micro (free tier!) . Now I'm not sure of the GHz rating for this, but yes you are right it is a very basic one. 

I am surprised, xgboost installation works well on my 1.8GHz i5 MacAir as well as a 8yr old HP Pavillion i3, but not on this t2.micro. 

However, I will still try getting the latest CMake and get back in case the commands you gave worked.

**Comment by hcho3** [comment]
@sherlockyGH It probably has to do with memory consumption.

**Comment by sherlockyGH** [comment]
@hcho3 hey, surprisingly the installation worked when I followed your commands for installation. 

Do you think it was because of the 1.3.0 version vs 1.2.0.1 version ? 

Also, models on t2.micro seem to be running almost twice as fast as compared to my MacBook Air 2017 8GB (which also has the CRAN 1.2.0.1 version)!

**Comment by hcho3** [comment]
@sherlockyGH No, I think the hang was caused by the limited memory that's available on t2.micro. The CMake build uses less memory than the CRAN installation (`install.packages('xgboost')`) because the latter uses what we call amalgamation, which is a giant file that combines lots of C++ files together. GCC consumes lots of memory as it tries to compile the amalgamation. On the other hand, GCC has no issues building smaller individual C++ source files, which is what happens when you build XGBoost using CMake.

**Comment by sherlockyGH** [comment]
Got it. 
CMake to the rescue if ever in future such an issue persists with any other heavy library; or when I run out of cash to rent a higher EC2! 

Thank you so much for resolving my issue; I had been head banging for a long time over this. 
Also, I hope posting this discussion link on my query on stackoverflow is fine by you; it will help others who get directed to SO before Git by their web search for this issue. 

Thanks again!

**Comment by hcho3** [comment]
No problem. Personally I highly recommend that you upgrade to EC2 instance with more memory. XGBoost will need more memory as you increase the data size. Typically you'll need ~3 GB of memory if your input is 1 GB.

**Comment by sherlockyGH** [comment]
Absolutely @hcho3 I totally agree with you. I will definitely be upgrading on-demand instances for xgboost, given its memory hungry nature (and of R in general). That was the very reason I had to choose cloud over purchasing new $KKK Apple RAM! And this was after I burnt out my i3 on HP 4GB using the H2O package consistently! : )

Thanks again.
