### ISSUE TITLE
AUC Check failed when I do the rank task using distributed xgboost

### ISSUE THREAD

**Issue by andong0323** [dmlc/xgboost#6428]
When I use distributed xgboost with xgboost operator, I get the error:
src/metric/rank_metric.cc:135: Check failed: !auc_error AUC: the dataset only contains pos or neg samples
This occurs when I set the eval_metric: ["auc"], but when I set the eval_metric: ["ndcg"], the error doesn't occur.

Each worker has one piece of data following the format https://xgboost.readthedocs.io/en/latest/tutorials/input_format.html#embedding-additional-information-inside-libsvm-file

I also test the data by this way: every worker only has one qid，each qid data has positive samples and negetative samples, this error still occurs.

**Comment by trivialfis** [comment]
Could you please provide a reproducible script?

**Comment by andong0323** [comment]
Today I deeply check this problem, I split the file step by step until the error occurs. When I use the below file, this error occurs reproducibly.
[train_part0.zip](https://github.com/dmlc/xgboost/files/5596515/train_part0.zip)
![auc_error](https://user-images.githubusercontent.com/37055147/100225839-ca721100-2f59-11eb-9022-005cbe91f81a.jpg)
When I use the same data using ndcg eval_metric, the error does not occur.
![2](https://user-images.githubusercontent.com/37055147/100226065-250b6d00-2f5a-11eb-936c-2a63c3c72a16.jpg)

The code is just using xgboost operator like this example:
https://github.com/kubeflow/xgboost-operator/blob/master/config/samples/xgboost-dist/train.py

**Comment by trivialfis** [comment]
This is fixed in 1.4
