### ISSUE TITLE
'Long vectors not supported yet' error, predicting

### ISSUE THREAD

**Issue by BlindApe** [dmlc/xgboost#643]
Error en xgb.Booster(modelfile = bst$raw) : 
  long vectors not supported yet: ../include/Rinlinedfuns.h:137

My model has 10000 trees and depth 18. Is related to this?

**Comment by fakyras** [comment]
predict(xgmod, newdata=dtest)
Error in xgb.Booster(modelfile = bst$raw) : 
  long vectors not supported yet: ../../src/include/Rinlinedfuns.h:137

experiencing same issue
nrounds=100k, depth=10

Could we at least get what is causing it?

**Comment by BlindApe** [comment]
I guess is a problem loading a big tree in a intermediate structure, probably integer exceeded o similar.

**Comment by tqchen** [comment]
This was due to R's raw version limit, limiting the model size to be within 32 bit..
