### ISSUE TITLE
Why is the SO file in the Pypi package so large?

### ISSUE THREAD

**Issue by BrannonKing** [dmlc/xgboost#6430]
Installing xgboost through pip requires a 150MB download and extracts to a 416MB installation. That seems huge for a single library. It's obviously distributing a statically-linked file. However, what have we linked in to make it that large? Does it need to be that large? Is it just one or two libraries filling that space? Is there some symbols or strings that should be stripped from the SO file?

**Comment by hcho3** [comment]
@BrannonKing This is mostly due to the static linking of [NCCL](https://github.com/NVIDIA/nccl), which is needed for accessing NVIDIA GPUs in the context of multi-process distributed training.

**Comment by hcho3** [comment]
If the binary size is a concern, you may opt out of the GPU capability, by installing from the source:
```
pip install xgboost --no-binary :all:
```

**Comment by LowinLi** [comment]
> If the binary size is a concern, you may opt out of the GPU capability, by installing from the source:
> 
> ```
> pip install xgboost --no-binary :all:
> ```

by do this , i have a long error info like that

```
...
subprocess.CalledProcessError: Command '['cmake', 'xgboost', '-GUnix Makefiles', '-DUSE_OPENMP=1', '-DUSE_CUDA=0', '-DUSE_NCCL=0', '-DBUILD_WITH_SHARED_NCCL=0', '-DHIDE_CXX_SYMBOLS=1', '-DUSE_HDFS=0', '-DUSE_AZURE=0', '-DUSE_S3=0', '-DPLUGIN_LZ4=0', '-DPLUGIN_DENSE_PARSER=0', '-DUSE_SYSTEM_LIBXGBOOST=0']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/llw/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7yngw8rm/xgboost_dae79e9c8fe64df6b78be1b2f3b1b590/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7yngw8rm/xgboost_dae79e9c8fe64df6b78be1b2f3b1b590/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"
```

**Comment by trivialfis** [comment]
Just tested the command, seems fine.

**Comment by LowinLi** [comment]
> Just tested the command, seems fine.
it worked in mac(python3.8) but failed in ubuntu(python3.8)

cat /proc/version
```
Linux version 5.3.0-59-generic (buildd@lcy01-amd64-025) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #53~18.04.1-Ubuntu SMP
```

**Comment by trivialfis** [comment]
Could you please open a new issue and post a full log?  I'm using Ubuntu and don't have issue with it when using virtual env or conda.

**Comment by LowinLi** [comment]
> Could you please open a new issue and post a full log? I'm using Ubuntu and don't have issue with it when using virtual env or conda.

I upgrade my cmake version from 3.5 to 3.13, and  install success. thanks!
