### ISSUE TITLE
[jvm-packages] How to set tracker_conf in Java for classifier "ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier"?

### ISSUE THREAD

**Issue by XudongWang97** [dmlc/xgboost#6437]
Hi, geeks

I have sweeped the relevant docs and source code, but I didn't figure out how to set `trackerConf` for xgboost4j-spark `ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier` in Java. 

For example, one can set params for `XGBoostClassifier` in Java by following code:
```java
XGBoostClassifier xgbClassifier = new XGBoostClassifier()
    .setLabelCol(labelColumn)
    .setFeaturesCol(featureColumn)
    .setPredictionCol(predictionColumn)
    .setProbabilityCol(probabilityColumn)
    .setTreeMethod(treeMethod)
    ...
```
but I didn't find a function named `setTrackerConf` or something like this. Is there any way to set `trackerConf` for the classifier?

Thanks

**Comment by hcho3** [comment]
Take a look at this example: https://github.com/dmlc/xgboost/blob/d7b45fbcafcce8295a94858a996482fdb9091f3e/jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/RabitRobustnessSuite.scala#L32-L41

**Comment by XudongWang97** [comment]
I see, but my leader request me to implement by pure Java codes. A Java solution is still appreciated. I would report on this issue when I have any progress. 

Thanks

**Comment by hcho3** [comment]
`TrackerConf` is a Scala class: https://github.com/dmlc/xgboost/blob/cc581b3b6b49958a56b440de2f5d4769b8fdd193/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala#L53-L57

You should be able to use it from Java, although I'm not sure about exact details.

**Comment by XudongWang97** [comment]
All right, this work for me.

Thanks!

```java
...
import ml.dmlc.xgboost4j.scala.spark.TrackerConf;
...

...
XGBoostClassifier xgbClassifier = new XGBoostClassifier()
    .setLabelCol(labelColumn)
    .setPredictionCol(predictionColumn)
    ...
    ...
    .set("trackerConf", new TrackerConf(60 * 60 * 1000L, "scala"));
```
