### ISSUE TITLE
Error when creating Dmatrix from dynamic multidimensional array

### ISSUE THREAD

**Issue by YannickLecroart** [dmlc/xgboost#6440]
Hi,

In my code I have created a dynamic array that I fill with data from a Xtensor array as you can see below:

```
float **x_train_data;

x_train_data = new float*[x_train_rows]; // create rows 
	for (int row = 0; row < x_train_rows; row++)
		x_train_data[row] = new float[x_train_cols]; // create columns 

//fill x train data 
for (int i = 0; i < x_train_rows; i++)
	for (int j = 0; j < x_train_cols; j++)
		x_train_data[i][j] = x_train(i, j);
```

Now I am trying to create a DMatrix from that array:

```
DMatrixHandle h_train;
XGDMatrixCreateFromMat((float *)x_train_data, x_train_rows, x_train_cols, -1, &h_train); 
```

But I get the following error in Visual Studio 2017:

`error LNK2001: unresolved external symbol XGDMatrixCreateFromMat`

Could you please help me out and tell me if I am doing something wrong?

Thanks in advance.

**Comment by trivialfis** [comment]
Could you please share jow did you install xgboost and what's the installed version?

**Comment by YannickLecroart** [comment]
The issue came from my Visual Studio solution. I fixed it.
