### ISSUE TITLE
predict() without eval_metric

### ISSUE THREAD

**Issue by Roffild** [dmlc/xgboost#6442]
Why is it impossible to use the model without editing the parameters?
```python
import pathlib
import xgboost, numpy

# Loading a model from another code:
m=xgboost.Booster(params={'objective': 'binary:logitraw', 'booster': 'gbtree', 'eta': 0.3, 'max_depth': 12, 'eval_metric': ['error', 'mae']})
m.load_model(pathlib.Path(r"xf15785f420fe02ba64912281312847ec.model"))

# I need to decide whether to continue train or not?
# So I want to keep the parameters.

# But predict() requires you to reset eval_metric:
m.set_param({"eval_metric": None}) # This doesn't work!

d=numpy.random.random(582).tolist()
d=numpy.array([d])
t=xgboost.DMatrix(d)

p=m.predict(t, validate_features=False)
print(p)
```
```
xgboost.core.XGBoostError: [18:43:09] C:\Users\Administrator\workspace\xgboost-win64_release_1.2.0\src\metric\metric.cc:49: Unknown metric function ['error', 'mae']
```

**Comment by hcho3** [comment]
Why do you need the line `m.set_param({"eval_metric": None})`? What happens when you remove it? To my knowledge, `predict()` does not require you to call `set_param`.

**Comment by Roffild** [comment]
> Why do you need the line `m.set_param({"eval_metric": None})`? What happens when you remove it? To my knowledge, `predict()` does not require you to call `set_param`.

`m.set_param({"eval_metric": None})` should override the option, but it doesn't and the error appears. Without this, there is also an error.

`set_param` is unnecessary if you load the model without parameters. But if the parameters are already set and you need to get a simple `predict()` result?

**Comment by Roffild** [comment]
```c++
  void SetParam(const std::string& key, const std::string& value) override {
    this->need_configuration_ = true;
    if (key == kEvalMetric) {
      if (std::find(metric_names_.cbegin(), metric_names_.cend(),
                    value) == metric_names_.cend()) {
        metric_names_.emplace_back(value);
      }
    } else {
      cfg_[key] = value;
    }
  }
```
and
```python
m.set_param({"eval_metric": None})
```
It looks like the check for eval_metric ignores new values and None.
