### ISSUE TITLE
Is XGBoost supported on x86 (32 bit)

### ISSUE THREAD

**Issue by aviks** [dmlc/xgboost#6443]
Some users of the Julia binding have reported [errors on running XGBoost on linux x86](https://github.com/dmlc/XGBoost.jl/runs/1468010885?check_suite_focus=true). It is of course possible that the issue is in the binding itself, rather than the library, but before I investigate, I wanted to ask if xgboost itself is supported on 32bits. The reason I ask is that it looks to me that the travis/appveyor/jenkins tests run only 64 bit.

**Comment by hcho3** [comment]
No, we do not officially support 32-bit, in the sense that we only run tests for 64-bit.
