### ISSUE TITLE
Is there not a JVM API call for predict_proba?

### ISSUE THREAD

**Issue by gsaxena888** [dmlc/xgboost#6444]
I'ma Java developer that's new to XGBoost. I tried to find an API in Java for predict_proba but couldn't find one. Does that not exist?

**Comment by trivialfis** [comment]
Predict proba is a wrapper for begin compatible with Python scikit learn library.  Maybe we can lower it down it C++.

**Comment by Craigacp** [comment]
This predict method (https://github.com/dmlc/xgboost/blob/master/jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/Booster.java#L357) gives the probabilities of each class in the batch that you pass in via the DMatrix. That's what I use to get the probability distributions and it works just fine.

**Comment by gsaxena888** [comment]
Cool thanks -- I'll test that out! @Craigacp
