### ISSUE TITLE
AttributeError: 'Booster' object has no attribute 'get_booster'

### ISSUE THREAD

**Issue by stromal** [dmlc/xgboost#6449]
https://github.com/dmlc/xgboost/issues/3894#issue-380237582
Still have this issue at ```xgboost                   1.2.0dev.rapidsai0.16  cuda10.2py37_2    rapidsai```

code
```xgb_model.get_booster().get_score(importance_type="gain")```

ERROR
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-93-094caba0c384> in <module>
----> 1 xgb_model.get_booster().get_score(importance_type="gain")

AttributeError: 'Booster' object has no attribute 'get_booster'
```

**Comment by hcho3** [comment]
No need to use `get_booster()` here, since `xgb_model` is already a `Booster` type. Use:
```python
xgb_model.get_score(importance_type="gain")
```
