### ISSUE TITLE
AttributeError: module 'cudf' has no attribute 'DataFrame'

### ISSUE THREAD

**Issue by pseudotensor** [dmlc/xgboost#6451]
When cudf is installed but one has no conda, one gets this.  So cudf gets imported, but it's some minimal version.  The xgboost `_is_cudf_df` function is not aware of this apparently, and uses an invalid try-except.  One should try-except on the attribute as well.

```
  File "/home/jon/h2oai.fullcondatest/h2oaicore/models.py", line 7275, in xgboost_model_fit
    self.model.fit(X, y, sample_weight=sample_weight, **kwargs_fit)
  File "/home/jon/.pyenv/versions/3.6.5/lib/python3.6/site-packages/xgboost/sklearn.py", line 871, in fit
    for i in range(len(eval_set))
  File "/home/jon/.pyenv/versions/3.6.5/lib/python3.6/site-packages/xgboost/sklearn.py", line 871, in <genexpr>
    for i in range(len(eval_set))
  File "/home/jon/.pyenv/versions/3.6.5/lib/python3.6/site-packages/xgboost/core.py", line 438, in __init__
    feature_types=feature_types)
  File "/home/jon/.pyenv/versions/3.6.5/lib/python3.6/site-packages/xgboost/data.py", line 508, in dispatch_data_backend
    if _is_cudf_df(data):
  File "/home/jon/.pyenv/versions/3.6.5/lib/python3.6/site-packages/xgboost/data.py", line 320, in _is_cudf_df
    return isinstance(data, cudf.DataFrame)
AttributeError: module 'cudf' has no attribute 'DataFrame'


```

```
def _is_cudf_df(data):
    try:
        import cudf
    except ImportError:
        return False
    return isinstance(data, cudf.DataFrame)
```

**Comment by trivialfis** [comment]
> When cudf is installed but one has no conda, one gets this. So cudf gets imported, but it's some minimal version. 

Could you please show me how to reach this?

**Comment by pseudotensor** [comment]
I reached it by running xgboost like normal, but not in conda.  One would normally expect that pyenv or some other env would work.  But instead it had cudf to import but no attributes.  I don't know exactly how I reached it.  If I 

FYI a work-around is:

```
sed -i 's/return isinstance(data, cudf.Series)/return isinstance(data, cudf.Series) if hasattr(cudf, "Series") else False/g' $spackagespath/xgboost/data.py && \
sed -i 's/return isinstance(data, cudf.DataFrame)/return isinstance(data, cudf.DataFrame) if hasattr(cudf, "DataFrame") else False/g' $spackagespath/xgboost/data.py
```
for site-packages path `$spackagespath`.

But in general even if one can import the various data.py modules, that does not mean is the correct package, installed correctly, etc.  Safer to check has the expected attribute for all data.py cases.

**Comment by trivialfis** [comment]
Probably related to https://github.com/dmlc/xgboost/pull/5873/files#diff-bf11fe0b3133c5b20253ea67b82c3e576513c8079f3be355fc323e3e903d989c .  It's actually fixed in latest branch and probably in 1.3.

**Comment by trivialfis** [comment]
Can you try it out?

**Comment by pseudotensor** [comment]
Ah cool, yes, I'm currently in process of trying out latest 1.3.0RC via master head as of today.  I suppose 1.3.0 release is likely within less than week, given history of RC -> release windows in past?

**Comment by pseudotensor** [comment]
What about the Series case?  I don't see fix for that in that PR.

**Comment by trivialfis** [comment]
> likely within less than week

Dec 7 if everything goes well.

> What about the Series case? I don't see fix for that in that PR.

Not yet, I can patch the series too, but so far we you can see from the linked discussion, we don't know where's this stub defined.  Surely we can just patch for everything, but that doesn't seem to be viable.  ;-(

**Comment by trivialfis** [comment]
Closing this as I don't think this is a bug in xgboost, what we can do is working around bugs somewhere we don't know if it exists as we haven't seen case with series.  But the best option would be identifying the bug in import in the future.
