### ISSUE TITLE
Load DMatrix from file and feature_names

### ISSUE THREAD

**Issue by Roffild** [dmlc/xgboost#6452]
```python
import pathlib, pandas, xgboost
psave=pathlib.Path(r"xgb_load_test.xgb")
data=pandas.DataFrame({"first": [778, 786], "two": [234, 56], "result": [0, 1]})
d1=xgboost.DMatrix(data.drop(columns="result"), data["result"])
d1.save_binary(psave)
d2=xgboost.DMatrix(psave)
print(d1.feature_names)
print(d2.feature_names)
```
```
['first', 'two']
['f0', 'f1']
```

**Comment by hcho3** [comment]
Currently the binary format for DMatrix does not preserve the feature names. You may want to use alternative formats if you need to preserve feature names.

**Comment by Roffild** [comment]
feature_names are saved in binary format.

**Comment by hcho3** [comment]
> feature_names are saved in binary format

No, it does not. Take a look at https://github.com/dmlc/xgboost/blob/927c316aeb0a948e9635c1ffe54d5e6ed25f6797/src/data/simple_dmatrix.cc#L200

**Comment by trivialfis** [comment]
Looking into it.

**Comment by trivialfis** [comment]
On latest branch this is actually saved, along with feature types.  But after loading the DMatrix back from binary, they got reset from Python constructor.

**Comment by hcho3** [comment]
> On latest branch this is actually saved

Can you point me where this happens? I thought only feature types were being saved.

**Comment by hcho3** [comment]
My bad. Here is the place where feature names are saved:

https://github.com/dmlc/xgboost/blob/512b464cfa109bbd8c4bb88eaf418060656ee8a1/src/data/data.cc#L184-L185
