### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by nickcorona** [dmlc/xgboost#6453]
Broken links under code examples for binary classification and regression.

**Comment by hcho3** [comment]
Which links are broken? Please be more specific.

**Comment by nickcorona** [comment]
> Which links are broken? Please be more specific.
code examples for binary classification and regression.

**Comment by hcho3** [comment]
Can you provide the link? Which page are you referring to?

**Comment by hcho3** [comment]
Fixed by #6455
