### ISSUE TITLE
dask scikit-learn API: TypeError: fit() got an unexpected keyword argument 'callbacks'

### ISSUE THREAD

**Issue by pseudotensor** [dmlc/xgboost#6468]
Is there planned support for dask to have callbacks?   When using things like Optuna I hit:

```
  File "/home/jon/h2oai.fullcondatest/h2oaicore/models.py", line 1512, in objective
    model.fit(X, y, sample_weight=sample_weight, callbacks=[pruning_callback], **kwargs_fit)
  File "/home/jon/minicondadai/lib/python3.6/site-packages/xgboost/core.py", line 421, in inner_f
    return f(**kwargs)
TypeError: fit() got an unexpected keyword argument 'callbacks'
```

@trivialfis

**Comment by hcho3** [comment]
It is already supported:
https://github.com/dmlc/xgboost/blob/fb56da5e8b95f3fa0a797a4b2bd073d13e28ed3b/tests/python/test_with_dask.py#L647-L671

**Comment by pseudotensor** [comment]
Is the scikit-learn API not supporting it?  I'm using latest 1.3.0 master.

**Comment by hcho3** [comment]
Not yet, currently, you'd need to use `xgb.dask.train()` to use the `callbacks` argument.

**Comment by hcho3** [comment]
Also, Optuna's pruning callback function doesn't yet work with xgboost.dask: #6323

**Comment by pseudotensor** [comment]
Ok, so even if I tried to use native API for Optuna, it would fail some other way.

**Comment by hcho3** [comment]
That's right, until #6323 is resolved.

**Comment by pseudotensor** [comment]
Is the Optuna calback code complicated?  I'll have to check it out.

**Comment by trivialfis** [comment]
I will submit a PR on optuna next week.  We haven't done any test on using dask interface with optuna.

**Comment by pseudotensor** [comment]
Awesome, thanks @trivialfis !

**Comment by trivialfis** [comment]
Closed by https://github.com/dmlc/xgboost/pull/6471
