### ISSUE TITLE
Throw an error when the user attempts to use AUC/AUCPR for wrong tasks

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#6474]
AUC and AUCPR metrics in XGBoost can be used only for binary classification and ranking tasks. XGBoost should throw an error when the user attempts to use AUC / AUCPR for other tasks.

**Comment by trivialfis** [comment]
Can we extend it to multi class?

**Comment by hcho3** [comment]
FYI Scikit-learn implements AUC for multi-class by averaging: https://scikit-learn.org/stable/modules/generated/sklearn.metrics.roc_auc_score.html

**Comment by trivialfis** [comment]
AUC supports multi-class classification.  For AUCPR, there's a check:

```
    CHECK_EQ(preds.Size(), info.labels_.Size())
        << "label size predict size not match";
```

So I think we can close this one now.
