### ISSUE TITLE
ISSUE - Inconsistency detected by ld.so

### ISSUE THREAD

**Issue by krishna7189** [dmlc/xgboost#6479]
The latest version is causing an issue:-
>>> import xgboost as xgb
Inconsistency detected by ld.so: dl-version............

**Comment by hcho3** [comment]
Hello, the latest release (1.3.0) had a bug that rendered XGBoost unusable on CentOS and Debian. #6482 will fix it. You can try the patched XGBoost by downloading the wheel from the following link: https://xgboost-examples.s3-us-west-2.amazonaws.com/xgboost-1.3.0-py3-none-manylinux2010_x86_64.whl

**Comment by pdxjohnny** [comment]
Is there an eta on `post0`?

**Comment by hcho3** [comment]
@pdxjohnny As soon as #6482 is merged.

**Comment by hcho3** [comment]
@pdxjohnny The `1.3.0.post0` version is now available on PyPI: https://pypi.org/project/xgboost/1.3.0.post0/#files. It contains the hot fix (#6482) and should not crash upon import.

**Comment by pdxjohnny** [comment]
Thank you!
