### ISSUE TITLE
Add `set_base_margin()` method to `DaskDMatrix`

### ISSUE THREAD

**Issue by stephenpardy** [dmlc/xgboost#6484]
Currently the DaskDMatrix object does not have the capability to set the initial guess for individual data using `set_base_margin` as is done with the non-Dask version.

Is there anything preventing this method (and others such as `set_weight`) being added to the DaskDMatrix?

**Comment by hcho3** [comment]
You can pass `base_margin` argument in the constructor of `DaskDMatrix`.
