### ISSUE TITLE
parameter "verbose_eval" does not work

### ISSUE THREAD

**Issue by pngingg** [dmlc/xgboost#6492]
`bst = xgb.train(param, dtrain, num_round, evals=watchlist, verbose_eval=10)`

The output will skip the info of iterations 10, 20, 30, ... 
The output is like [1],...[9],[11],...,[19],[21],...

Perhaps the "!=" should be "==" in callback.py [line 624]:
`if (epoch % self.period) != 0 or self.period == 1:`
![image](https://user-images.githubusercontent.com/22881524/101873345-be28bd80-3bc1-11eb-8c13-e6f544ae8efd.png)

**Comment by trivialfis** [comment]
Fixed by https://github.com/dmlc/xgboost/pull/6499
