### ISSUE TITLE
Partial installation of xgboost - for inference only

### ISSUE THREAD

**Issue by akazakci** [dmlc/xgboost#6493]
Hi,
I have a use case where I only need to do inference with an xgboost model, and I have limited space to install the Xgboost itself.

Is there a way to reduce the size of Xgboost installation by skipping some modules /dependencies?

Thank you

**Comment by hcho3** [comment]
See https://discuss.xgboost.ai/t/partial-installation-for-inference-is-it-possible/2001/2
