### ISSUE TITLE
Bundle libomp.dylib in macosx wheel?

### ISSUE THREAD

**Issue by pavlin-policar** [dmlc/xgboost#6494]
We are trying to distribute xgboost in another package, and we've come across the problem that xgboost doesn't bundle the dynamic library into the mac wheel. I understand this is written in the instructions, and we have no problems installing libomp via brew.

However, I did also notice that you do bundle the dynamic libraries with the linux wheels [here](https://github.com/dmlc/xgboost/blob/master/Jenkinsfile#L201). Here, you use auditwheel, which is not available on OSX. However, for macs, there's [delocate](http://github.com/matthew-brett/delocate), which does the same thing. I patched the xgboost mac wheel easily using their instructions, and it worked perfectly. Why not bundle the mac `libomp.dylib` in the mac wheel as well? Is there some specific reason for this?

**Comment by markotoplak** [comment]
Link to the the other's project PR: biolab/orange3#5116

**Comment by hcho3** [comment]
The reason is that the `delocate` utility is in its alpha stage (see its readme). On the other hand, the `auditwheel` tool has been extensively tested and is supported as part of a Python standard ([PEP 513](https://www.python.org/dev/peps/pep-0513/), [PEP 571](https://www.python.org/dev/peps/pep-0571/)).

For this reason, we do not plan to release Mac wheels with `libomp` bundled. You are however free to create your own wheel with `libomp`; proceed with your own risk.

**Comment by pavlin-policar** [comment]
The alpha warning message was written seven years ago, and it seems the authors forgot to remove it. They've now removed it https://github.com/matthew-brett/delocate/commit/d34654e898a5586d646a454746a20edb12296ff9 and the package is marked as stable.

I understand you may still be hesitant to use it, since nobody seems to have noticed the alpha warning or bothered asking the authors what's up. On the other hand, judging from the commit history, the package seems very stable with almost no changes in the past year.

**Comment by hcho3** [comment]
Thanks for the update. We would like to keep the current packaging at this time being, since we just release 1.3.0. We may revisit the decision later.

**Comment by hcho3** [comment]
Also, there is the dreaded error
```
OMP: Error #15: Initializing libiomp5.dylib, but found libiomp5.dylib already initialized
```
from #1715, indicating the presence of multiple copies of OpenMP runtime being loaded. I do not want to risk getting another error of this kind, thus I currently do not support bundling OpenMP runtime in the Mac wheel.

**Comment by pavlin-policar** [comment]
Thanks for the response! I understand. It would be great if this was added to future releases.

**Comment by hcho3** [comment]
@pavlin-policar We will need to find a way to bundle OpenMP runtime without causing the error
```
OMP: Error #15: Initializing libiomp5.dylib, but found libiomp5.dylib already initialized
```

Otherwise, it won't happen.

**Comment by pavlin-policar** [comment]
I see, I'm looking at the issue now. That would be very problematic for us as well. Our users are not all tech-savy, so we really want to make it as easy as possible to install and run Orange. An error message like this would be a nightmare.

Would static linking solve this issue?

**Comment by hcho3** [comment]
> Would static linking solve this issue or are there problems with that as well?

No, since that will also require static linking with the standard C++ library as well (`-static-libgcc -static-libstdc++`). This may cause whole sort of other issues, e.g. security vulnerability fix not being applied to the XGBoost binary. I really do not want to travel this road.

**Comment by hcho3** [comment]
@pavlin-policar If the ease of installation is the priority, you should consider using Conda to install XGBoost:
```
conda install -c conda-forge py-xgboost
```
which will also automatically take care of installing OpenMP runtime inside the Conda virtual environment.

**Comment by pavlin-policar** [comment]
>No, since that will also require static linking with the standard C++ library as well (-static-libgcc -static-libstdc++). This may cause whole sort of other issues, e.g. security vulnerability fix not being applied to the XGBoost binary, or some standard functions not working at all. I really do not want to travel this road.

I see, that's unfortunate. And it seems like there is no really good way around this...

> If the ease of installation is the priority, you should consider using Conda to install XGBoost

Thanks for the suggestion, we may do that!
