### ISSUE TITLE
stepwise saving

### ISSUE THREAD

**Issue by cyrix333** [dmlc/xgboost#650]
Hi,
I am using xgboost with R under windows.
If the model is to big ( more than installed memory 16 GB ) R chrashes ( I get an c++ error ) . Some calculation took some hours so it would be great if e.g. all 5 minutes / x steps (depending on the settings) the calculated model could be automatically saved.

Thanks !!

**Comment by pommedeterresautee** [comment]
Hi,

May be the content of this issue may help?
https://github.com/dmlc/xgboost/issues/641

Kind regards,
Michaël

**Comment by cyrix333** [comment]
Hi Michael,
to reduce the number of trees ends with a "not so good" model.

**Comment by pommedeterresautee** [comment]
Not always the case (overfitting) but my point was that the parameters you are looking for are exposed in the question.

Kind regards,
Michaël
