### ISSUE TITLE
Save feature names in the C++ booster object

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#6520]
Currently, the `feature_names` field of the Python `Booster` object is lost after performing round-trip serialization (save and then load):
```python
import xgboost as xgb
import numpy as np

X_train = np.random.rand(5,10)
y_train = np.random.rand(5,1)
dtrain = xgb.DMatrix(X_train, label=y_train)

params = {'objective': 'reg:squarederror'}
bst = xgb.train(params, dtrain, 2, evals=[(dtrain, 'train')])

bst.save_model('test.model')
print(bst.feature_names)  # prints ['f0', 'f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f9']

bst_loaded = xgb.Booster(model_file='test.model')
print(bst_loaded.feature_names)  # prints None
```

This leads to some confusing behavior, e.g. broken feature validation (#4854).

TODOs:
- [ ] Save the feature names in the C++ booster object, so that the feature names are serialized along with the rest of the model. This way, `save_model()` will not lose the feature names.
- [ ] Remove the generation of placeholder feature names like `f0`, `f1` etc. We should only save the legitimate feature names from the data frame libraries such as Pandas and cuDF.

cc @trivialfis

**Comment by hcho3** [comment]
For the sake of backward compatibility, I suggest saving the feature names as a Booster attribute, like what we currently do with other scikit-learn attributes:
https://github.com/dmlc/xgboost/blob/d6386e45e8ed19c238ee06544dabbcbf56e02bbc/python-package/xgboost/sklearn.py#L446

So we'd have
```python
json_str = json.dumps(feature_names)
bst.set_attr(feature_names=json_str)
```

**Comment by hcho3** [comment]
I can think of two alternatives.

1. Use Booster attributes

For the sake of backward compatibility, I suggest saving the feature names as a Booster attribute, like what we currently do with other scikit-learn attributes:
https://github.com/dmlc/xgboost/blob/d6386e45e8ed19c238ee06544dabbcbf56e02bbc/python-package/xgboost/sklearn.py#L446

So we'd have
```python
json_str = json.dumps(feature_names)
bst.set_attr(feature_names=json_str)
```

2. Save feature names as part of the C++ Learner object.

This is cleaner than 1), but we may not be able to save feature names in the legacy binary serializer.

**Comment by trivialfis** [comment]
I vote for second option:

> Save feature names as part of the C++ Learner object.

**Comment by hcho3** [comment]
@trivialfis Are you okay with losing feature names when the binary serializer is used?

**Comment by trivialfis** [comment]
@hcho3 I'm fine with that.  Debugging the binary format is just too painful.

**Comment by trivialfis** [comment]
Here are some expectations:

- Users should be able to set the feature names manually, including adding/removing/modifying feature names.
- Users should be able to enable/disable validation.  When disabled, there should not be any overhead in prediction.
- The feature name generation should be kept as an independent internal function used by features like plotting or score calculation.
- XGBoost should not force the use of feature name in prediction.  For example if users train a model with dataframe, then supplying a ndarray for prediction should be fine.  We can still check the number of features between model and dataset.
