### ISSUE TITLE
Shouldn't the custom java eval code for classification use 0.5f instead of 0.0f for the value to separate positive/negative cases?

### ISSUE THREAD

**Issue by gsaxena888** [dmlc/xgboost#6526]
In https://github.com/dmlc/xgboost/blob/master/jvm-packages/xgboost4j-example/src/main/java/ml/dmlc/xgboost4j/java/example/CustomObjective.java, the custom eval function logic for classification uses 0.0f as the value to seperate positive class from negative class. Shouldn't it instead be 0.5f? Please see code excerpt below:

```
 for (int i = 0; i < nrow; i++) {
        if (labels[i] == 0f && predicts[i][0] > 0) {
          error++;
        } else if (labels[i] == 1f && predicts[i][0] <= 0) {
          error++;
        }
      }
```
FYI: I'm new to both machine learning & XGBoost, so maybe I'm misunderstanding things....

**Comment by hcho3** [comment]
The `predicts` array contains the margin score that's not transformed by the sigmoid function: https://github.com/dmlc/xgboost/blob/8ad22bf4e7971baaf4c5f4b525dcd7c767bb5c6b/jvm-packages/xgboost4j-example/src/main/java/ml/dmlc/xgboost4j/java/example/CustomObjective.java#L97

So the 0 in the code corresponds to the 0.5 probability threshold.
