### ISSUE TITLE
TypeError: Not supported type for data.<class 'dask.dataframe.core.DataFrame'>

### ISSUE THREAD

**Issue by pseudotensor** [dmlc/xgboost#6530]
```
  File "/opt/h2oai/dai/cuda-10.0/lib/python3.6/site-packages/xgboost/sklearn.py", line 660, in predict
    missing=self.missing, nthread=self.n_jobs)
  File "/opt/h2oai/dai/cuda-10.0/lib/python3.6/site-packages/xgboost/core.py", line 505, in __init__
    enable_categorical=enable_categorical)
  File "/opt/h2oai/dai/cuda-10.0/lib/python3.6/site-packages/xgboost/data.py", line 572, in dispatch_data_backend
    raise TypeError('Not supported type for data.' + str(type(data)))
TypeError: Not supported type for data.<class 'dask.dataframe.core.DataFrame'>
```

@trivialfis new problem after various dask updates.  Why would dask not be supported for dask!

Same kinds of tests I've shared before, just passing dask frame in.  used to work fine.

**Comment by hcho3** [comment]
@pseudotensor The sklearn's predict function `XGBModel.predict()` does not accept Dask DataFrame, according to the docstring here:
https://github.com/dmlc/xgboost/blob/380f6f4ab89840678758ee4a978ea72232bbe1d4/python-package/xgboost/sklearn.py#L645-L646

Please use `xgb.dask.predict` instead:
https://github.com/dmlc/xgboost/blob/380f6f4ab89840678758ee4a978ea72232bbe1d4/python-package/xgboost/dask.py#L915-L940

**Comment by pseudotensor** [comment]
@hcho3 I'm not choosing which predict to use.  I'm just using the dask model and running model.predict.

**Comment by hcho3** [comment]
@pseudotensor Can you post a reproducible script?

**Comment by pseudotensor** [comment]
Ya checking.  I think it is indeed a mis-use.  So will close.  Sorry about that.

**Comment by hcho3** [comment]
No problem. Thanks again for taking time to testing XGBoost extensively.

**Comment by trivialfis** [comment]
After https://github.com/dmlc/xgboost/pull/6519 the dask interface predict function will have exact match to the single node version.  From there we can eliminate possible function resolution error.
