### ISSUE TITLE
XGBoost 1.3.0.post0 pip install needs to be run from working directory otherwise feature_name_mismatch error occurs.

### ISSUE THREAD

**Issue by bojake** [dmlc/xgboost#6538]
If I run my script as in "/home/foo/bar/this/path/mypython.py" from a directory that is not "/home/foo/bar/this/path" then xgboost crashes with this exception trace:

  File "/opt/conda/lib/python3.7/site-packages/xgboost/sklearn.py", line 658, in predict
    validate_features=validate_features)
  File "/opt/conda/lib/python3.7/site-packages/xgboost/core.py", line 1472, in predict
    self._validate_features(data)
  File "/opt/conda/lib/python3.7/site-packages/xgboost/core.py", line 2048, in _validate_features
    data.feature_names))
ValueError: feature_names mismatch:

This is on Windows and Linux, in a conda environment/shell, outside of conda, and in a container. It is reproducible.

If I run "mypython.py" from the directory it lives in, then xgboost errors do not occur. Only when I run as noted above does the error occur.

python                    3.7.3                h0371630_0    defaults
numpy                     1.19.4                   pypi_0    pypi
pandas                    1.1.4                    pypi_0    pypi
scikit-learn              0.23.2                   pypi_0    pypi
scipy                     1.5.4                    pypi_0    pypi

**Comment by trivialfis** [comment]
Could you please create a sample script that I can run?

**Comment by bojake** [comment]
This was user error (me). Sorry for the red herring.
