### ISSUE TITLE
order of features matters

### ISSUE THREAD

**Issue by cyrix333** [dmlc/xgboost#654]
Hi there,
I cant believe it .. maybe its too late or its really like that

I have 10 features ( cols with data ) and the RMPSE depends on
the position and the numer of features ( less features will give a better RMPSE - value )

here is a lis, first colunm is the RMPSE value second the coloumn title

```R
#0.24 c("Store","DayOfWeek","Open","Promo","Assortment", "StoreType" )
#0.22 c("Store","DayOfWeek","Open","Promo","Assortment", "StoreType", "year" )
#0.22 c("Store","DayOfWeek","Open","Promo","Assortment", "StoreType", "month" )
#0.31 c("Store","DayOfWeek","Open","Promo","Assortment", "StoreType", "month", "CompetitionDistance" )
#0.27 c("Store","DayOfWeek","Open","Promo","Assortment", "StoreType", "CompetitionDistance" )
#0.23 c("Store","DayOfWeek","Open","Promo","Assortment", "StoreType", "Day" )
#0.27 c("Store","DayOfWeek", "Promo","Assortment", "StoreType", "Day" )
#0.25 c("Store","DayOfWeek", "Assortment", "Day" )
#0.35 c("Store","DayOfWeek", "Day" )
#0.36 c("Store", "Day", "Promo" )

#0.19 c("Store","DayOfWeek","Promo","Assortment","Day" )                          
#0.19 c("Store","DayOfWeek","Promo","Assortment","Day" )    check next line all features are the same just the position changed !                      

#0.31 c("Store","Day","Promo","Assortment","DayOfWeek" )

#0.24 c("Store", "Day", "Promo", "Assortment" )
```

I am using R with windows
is this really true ?! does the position has so much influence ?! .. still cant belive it 
the gradient will point to the smallest / highest position .. so if more features in the model it sould be better also the position of the features  should not have influence .. or am I wrong ?!

**Comment by tqchen** [comment]
This can happen when there is a tie
