### ISSUE TITLE
[FEATURE] convert dask -> non-dask model

### ISSUE THREAD

**Issue by pseudotensor** [dmlc/xgboost#6547]
https://github.com/rapidsai/cuml/issues/3140#issuecomment-729934809

Related to this general issue, I think xgboost team does a much better job and ensures dask can be pickled etc.

But I encountered some differences between non-dask and dask trees that makes reading them incompatible.  Specifically we have poor accuracy when trying to read the tree structure to do predictions, but only for dask models.

I know xgboost can be used with treelite etc.  Is it expected that dask models can be used too?

In general, if there is any complication, is there a way to convert a dask model (sckit and raw API) into non-dask form so non-dask tools can be used?

@trivialfis

**Comment by hcho3** [comment]
@pseudotensor I don't see any technical hurdle in converting Dask model to an ordinary XGBoost model JSON file. We already have a callback function to serialize model at every boosting iteration:
https://github.com/dmlc/xgboost/blob/2231940d1d08f5aca23cf53d922642996a098d44/tests/python/test_with_dask.py#L1017-L1033

**Comment by trivialfis** [comment]
Could you please share the script that prediction is different?

**Comment by trivialfis** [comment]
Prediction difference is serious bug, so far I haven't been able to reproduce it.  But if you have a MRE I will not hesitate to fix it and push another patch release.

**Comment by pseudotensor** [comment]
Yes, @trivialfis , I'm not saying exactly that the predictions are off, just the way we access the tree structure via the internal format leads to very different predictions between dask and non-dask.  I'll get a repro of some kind ASAP.

**Comment by trivialfis** [comment]
To answer the original question, the booster returned by dask train function is exactly the same with single node.  But if you want to convert the pickled model between skl interfaces of dask and single node, I don't think that's possible at this point.  They are different Python classes and pickle stores Python bytecode.

**Comment by pseudotensor** [comment]
I think it was deduced that the primary problem here is that the dask model does not use ntree_limit so predictions can be off if trying to actually select the best_iterations model.  If that is solved, this issue is no longer needed, so I'll close.  Thanks!

**Comment by pseudotensor** [comment]
Actually, re-opening.  dask is heavily feature incomplete, esp. for scikit-learn API.  But most critically dask cannot do pred_contribs etc.  So would be good to be able to convert to non-dask so can apply normal operations during prediction time.

@hcho3 , thanks, I'll try your suggestion.

**Comment by pseudotensor** [comment]
Also, the non-sklearn dask API also fails to work for pred_contribs etc. even though supposed to work, so this also becomes important for trying to have that working.

**Comment by pseudotensor** [comment]
FYI this seems to work:
```
import pandas as pd
import xgboost as xgb
def fun():
    from dask.distributed import Client, wait
    from dask_cuda import LocalCUDACluster

    with LocalCUDACluster() as cluster:
        with Client(cluster) as client:

            import xgboost as xgb
            import dask_cudf

            import pickle
            (model, X, y, kwargs) = pickle.load(open("xgbissue6469.pkl", "rb"))
            X = pd.read_csv("creditcard.csv")
            print(X.columns)
            target = 'default payment next month'
            y = X[target]
            X = X.drop(target, axis=1)
            import dask.dataframe as dd
            X = dd.from_pandas(X, chunksize=250).persist()
            y = dd.from_pandas(y, chunksize=250).persist()
            valid_X = kwargs['eval_set'][0][0]
            valid_y = kwargs['eval_set'][0][1]
            valid_X = dd.from_pandas(valid_X, chunksize=250).persist()
            valid_y = dd.from_pandas(valid_y, chunksize=250).persist()
            #kwargs['eval_set'] = [(valid_X, valid_y)]
            kwargs.pop('eval_set', None)
            kwargs.pop('eval_metric', None)
            model = xgb.dask.DaskXGBClassifier(**model.get_params())
            model.fit(X, y, **kwargs)
            #preds = xgb.dask.predict(client=client, model=model.get_booster(), data=X, pred_contribs=True).compute()
            #print(preds.shape)
            bst = xgb.XGBClassifier(model.get_params())
            bst = xgb.Booster()
            bst.load_model('0001.model')
            dpredict = xgb.DMatrix(X.compute())
            preds_contribs = bst.predict(dpredict, pred_contribs=True)
            print(preds_contribs.shape)

if __name__ == '__main__':
    fun()
```

Oddly, the sklearn way did not work:

```
import pandas as pd
import xgboost as xgb
def fun():
    from dask.distributed import Client, wait
    from dask_cuda import LocalCUDACluster

    with LocalCUDACluster() as cluster:
        with Client(cluster) as client:

            import xgboost as xgb
            import dask_cudf

            import pickle
            (model, X, y, kwargs) = pickle.load(open("xgbissue6469.pkl", "rb"))
            X = pd.read_csv("creditcard.csv")
            print(X.columns)
            target = 'default payment next month'
            y = X[target]
            X = X.drop(target, axis=1)
            import dask.dataframe as dd
            X = dd.from_pandas(X, chunksize=250).persist()
            y = dd.from_pandas(y, chunksize=250).persist()
            valid_X = kwargs['eval_set'][0][0]
            valid_y = kwargs['eval_set'][0][1]
            valid_X = dd.from_pandas(valid_X, chunksize=250).persist()
            valid_y = dd.from_pandas(valid_y, chunksize=250).persist()
            #kwargs['eval_set'] = [(valid_X, valid_y)]
            kwargs.pop('eval_set', None)
            kwargs.pop('eval_metric', None)
            model = xgb.dask.DaskXGBClassifier(**model.get_params())
            model.fit(X, y, **kwargs)
            #preds = xgb.dask.predict(client=client, model=model.get_booster(), data=X, pred_contribs=True).compute()
            #print(preds.shape)
            bst = xgb.XGBClassifier(model.get_params())
            #bst = xgb.Booster()
            bst.load_model('0001.model')
            #dpredict = xgb.DMatrix(X.compute())
            #preds_contribs = bst.predict(dpredict, pred_contribs=True)
            preds_contribs = bst.predict(X.compute(), pred_contribs=True)
            print(preds_contribs.shape)

            print("here")

if __name__ == '__main__':
    fun()

```

gives

```
/home/jon/minicondadai/lib/python3.6/site-packages/xgboost/core.py:419: FutureWarning: Pass `objective` as keyword args.  Passing these as positional arguments will be considered as error in future releases.
  format(", ".join(args_msg)), FutureWarning)
/home/jon/minicondadai/lib/python3.6/site-packages/xgboost/sklearn.py:472: UserWarning: Loading a native XGBoost model with Scikit-Learn interface.
  'Loading a native XGBoost model with Scikit-Learn interface.')
Traceback (most recent call last):
  File "/data/jon/h2oai.fullcondatest3/dask_cudf_scitkit_predcontribs2.py", line 45, in <module>
    fun()
  File "/data/jon/h2oai.fullcondatest3/dask_cudf_scitkit_predcontribs2.py", line 39, in fun
    preds_contribs = bst.predict(X.compute(), pred_contribs=True)
  File "/home/jon/minicondadai/lib/python3.6/site-packages/xgboost/sklearn.py", line 1003, in predict
    return column_indexes
UnboundLocalError: local variable 'column_indexes' referenced before assignment

Process finished with exit code 1
```

I would assume this `UnboundLocalError` is a new bug, since I'm not doing anything super crazy.  Should I file an issue? @hcho3  @trivialfis

**Comment by pseudotensor** [comment]
`/home/jon/minicondadai/lib/python3.6/site-packages/xgboost/sklearn.py:472: UserWarning: Loading a native XGBoost model with Scikit-Learn interface.`  I assume new bug, since this is just a warning and it should have worked.

**Comment by trivialfis** [comment]
Could you please help taking a look into https://github.com/dmlc/xgboost/pull/6582 ?
