### ISSUE TITLE
How to set missing value in xgb4j in python?

### ISSUE THREAD

**Issue by xxxxsk** [dmlc/xgboost#6549]
I also encountered a similar problem，i have a model file already, and the model has no default missing value specified. When i load the model with spark 2.4.7 in pyspark, I cannt set missing successfully,this is my code:

```
model_path = '***.model'
scala_xgb = spark.sparkContext._jvm.ml.dmlc.xgboost4j.scala.XGBoost
jbooster = scala_xgb.loadModel(model_path)

N_CLASS = 2
xgb_cls_model = JavaWrapper._new_java_obj(
        "ml.dmlc.xgboost4j.scala.spark.XGBoostClassificationModel",
        "xgbc", N_CLASS, jbooster)

jpred = xgb_cls_model.transform(test._jdf)

pred = DataFrame(jpred, spark)
```

I tried 
```
xgb_cls_model.setMissing(np.nan)
```
 and it did not work. How can i set the missing value?
Thank you!

**Comment by trivialfis** [comment]
I don't think xgboost supports pyspark.

**Comment by xxxxsk** [comment]
> I don't think xgboost supports pyspark.

well，I submit jars of xgboost4j.  I use java class in python and I don't know how to set the missing

**Comment by hcho3** [comment]
Calling `setMissing` should work, although we do not officially support calling XGBoost4J from Python. Please try using Scala instead.
