### ISSUE TITLE
ValueError: y contains previously unseen labels

### ISSUE THREAD

**Issue by raimondo82** [dmlc/xgboost#6557]
Hello,

I am trying to convert simple categorical features into numerical values, but I am getting this value error: can you help me?

Many thanks!!
![Screenshot (19)](https://user-images.githubusercontent.com/66557496/103229150-8486df00-4943-11eb-94fd-19507d7ed6ce.png)
![Screenshot (20)](https://user-images.githubusercontent.com/66557496/103229154-86e93900-4943-11eb-8722-93fca8e2a554.png)
![Screenshot (21)](https://user-images.githubusercontent.com/66557496/103229155-881a6600-4943-11eb-8eb4-23f4ee0e3073.png)
![Screenshot (22)](https://user-images.githubusercontent.com/66557496/103229158-894b9300-4943-11eb-8aae-5fcc5e599660.png)

**Comment by hcho3** [comment]
The error is not related to XGBoost. It is coming from scikit-learn. Please use [one of the suggested methods for asking questions related to scikit-learn](https://scikit-learn.org/stable/faq.html?highlight=finding%20help#what-s-the-best-way-to-get-help-on-scikit-learn-usage).
