### ISSUE TITLE
how to replace 'gpu_hist' to 'hist' from a saved model in xgboost version 0.90

### ISSUE THREAD

**Issue by TooTouch** [dmlc/xgboost#6558]
I want to get shap values by applying `TreeExplainer` in SHAP. However, I saw that a saved model using `gpu_hist` in version 0.90 could not apply SHAP `TreeExaplainer` in https://github.com/slundberg/shap/issues/452.

I think that this issue was resolved in xgboost 1.0.0. 

At first, I used `convert_090to100.py` and loaded a saved model in version 1.0.0. However, it didn't work when I applied SHAP `TreeExplainer`. 

**How can I resolve this problem?**

Also, I used `gpu:binary:logistic` for training model. But, this parameter was deprecated in xgboost 1.0.0. Therefore, I replaced `gpu:binary:logistic` to `binary:logistic` as follows. The revised model was loaded and predicted same values. 

**Is the wrong approach?**

```python
temp = open('../saved_model/xgb_kfold_0.model','rb')
lines = temp.readlines()
print(len(lines[0]))
lines[0][:200]
```

```python
lines[0] = lines[0].replace(b'\x00\x00\x00\x80\x19\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x13\x00\x00\x00\x00\x00\x00\x00gpu:binary:logistic',
                            b'\x00\x00\x00\x80\x19\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0f\x00\x00\x00\x00\x00\x00\x00binary:logistic')
```

```python
new_model = open('replace.model','wb')
for line in lines:
    new_model.write(line)
new_model.close()
```

**Comment by hcho3** [comment]
> it didn't work when I applied SHAP TreeExplainer.

Can you be more specific? What kind of error did you run into?

**Comment by TooTouch** [comment]
Jupyter notebook kernel is died.

![image](https://user-images.githubusercontent.com/37654013/103258396-1dffd080-49d8-11eb-8f4a-b0c4e16ebfd3.png)

**Comment by hcho3** [comment]
@TooTouch What kind of error message did you get in the terminal console (in which you launched the Jupyter notebook)?

**Comment by TooTouch** [comment]
Any kind of error message was not appeared. 

This is `apply_shap.py`.

```python
import xgboost as xgb
import shap 

model = xgb.XGBClassifier()
model.load_model('../notebook/xgboost_native_model_from_replace.pkl-0.bin')

explainer = shap.TreeExplainer(model)
print(explainer)
```

**Comment by hcho3** [comment]
@TooTouch Did upgrading to 1.0.0 solve the crash? Also, you may want to try training a new model with 1.0.0 and see if that solves the problem.

**Comment by Namo-Bang** [comment]
@hcho3 I have same problem. Is there any way to get same result with version 0.90 from version 1.0.0? I have to reproduce the model trained with v0.90.

**Comment by TooTouch** [comment]
@hcho3  I also have to reproduce the model trained with v0.90. This is why I did try to use `convert_090to100.py` for converting model that trained with v0.90 to model with v1.0.0.

**Comment by trivialfis** [comment]
The parameter is not saved so nothing to replace.  You will have to train the model again.  Sorry for the inconvenience.
