### ISSUE TITLE
Facing installation problem on windows x32 bit python

### ISSUE THREAD

**Issue by munitech4u** [dmlc/xgboost#657]
I am trying to build using the MS Visual c++ 2010 and encountering below errors: with 1 success and 2 fails.

Installation log:

1>------ Rebuild All started: Project: rabit, Configuration: Debug Win32 ------
2>------ Rebuild All started: Project: xgboostjavawrapper, Configuration: Debug Win32 ------
1>  engine.cc
2>  xgboost_wrapper.cpp
1>  allreduce_robust.cc
2>c:\users\munitech4u\downloads\compressed\xgboost-0.4a29\xgboost\src\learner\learner-inl.hpp(181): warning C4244: 'argument' : conversion from 'uint64_t' to 'unsigned int', possible loss of data
2>c:\users\munitech4u\downloads\compressed\xgboost-0.4a29\xgboost\src\learner\learner-inl.hpp(182): warning C4244: 'argument' : conversion from 'uint64_t' to 'size_t', possible loss of data
2>c:\users\munitech4u\downloads\compressed\xgboost-0.4a29\xgboost\wrapper\xgboost_wrapper.cpp(410): warning C4244: 'argument' : conversion from 'uint64_t' to 'unsigned int', possible loss of data
2>c:\users\munitech4u\downloads\compressed\xgboost-0.4a29\xgboost\wrapper\xgboost_wrapper.cpp(410): warning C4244: 'argument' : conversion from 'uint64_t' to 'unsigned int', possible loss of data
1>  allreduce_base.cc
2>CL : warning : lgamma function was not available until VS2013, poisson regression will be disabled
2>  engine_empty.cc
2>  updater.cpp
1>c:\users\munitech4u\downloads\compressed\xgboost-0.4a29\xgboost\subtree\rabit\src\allreduce_base.cc(203): error C3861: 'sleep': identifier not found
1>  Generating Code...
3>------ Rebuild All started: Project: xgboost_wrapper, Configuration: Debug Win32 ------
4>------ Rebuild All started: Project: xgboost, Configuration: Debug Win32 ------
3>  xgboost_wrapper.cpp
3>c:\users\munitech4u\downloads\compressed\xgboost-0.4a29\xgboost\src\learner\learner-inl.hpp(181): warning C4244: 'argument' : conversion from 'uint64_t' to 'unsigned int', possible loss of data
3>c:\users\munitech4u\downloads\compressed\xgboost-0.4a29\xgboost\src\learner\learner-inl.hpp(182): warning C4244: 'argument' : conversion from 'uint64_t' to 'size_t', possible loss of data
4>  xgboost_main.cpp
2>  io.cpp
4>c:\users\munitech4u\downloads\compressed\xgboost-0.4a29\xgboost\src\learner\learner-inl.hpp(181): warning C4244: 'argument' : conversion from 'uint64_t' to 'unsigned int', possible loss of data
4>c:\users\munitech4u\downloads\compressed\xgboost-0.4a29\xgboost\src\learner\learner-inl.hpp(182): warning C4244: 'argument' : conversion from 'uint64_t' to 'size_t', possible loss of data
3>c:\users\munitech4u\downloads\compressed\xgboost-0.4a29\xgboost\wrapper\xgboost_wrapper.cpp(410): warning C4244: 'argument' : conversion from 'uint64_t' to 'unsigned int', possible loss of data
3>c:\users\munitech4u\downloads\compressed\xgboost-0.4a29\xgboost\wrapper\xgboost_wrapper.cpp(410): warning C4244: 'argument' : conversion from 'uint64_t' to 'unsigned int', possible loss of data
3>CL : warning : lgamma function was not available until VS2013, poisson regression will be disabled
3>  engine_empty.cc
3>  updater.cpp
3>  io.cpp
4>CL : warning : lgamma function was not available until VS2013, poisson regression will be disabled
4>  updater.cpp
2>  dmlc_simple.cpp
2>  gbm.cpp
2>c:\users\munitech4u\downloads\compressed\xgboost-0.4a29\xgboost\src\gbm\gbtree-inl.hpp(162): warning C4244: 'argument' : conversion from 'int64_t' to 'size_t', possible loss of data
2>c:\users\munitech4u\downloads\compressed\xgboost-0.4a29\xgboost\src\gbm\gbtree-inl.hpp(163): warning C4244: 'argument' : conversion from 'int64_t' to 'unsigned int', possible loss of data
2>c:\users\munitech4u\downloads\compressed\xgboost-0.4a29\xgboost\src\gbm\gbtree-inl.hpp(297): warning C4244: 'argument' : conversion from 'const int64_t' to 'unsigned int', possible loss of data
2>c:\users\munitech4u\downloads\compressed\xgboost-0.4a29\xgboost\src\gbm\gbtree-inl.hpp(299): warning C4244: 'argument' : conversion from 'const int64_t' to 'unsigned int', possible loss of data
2>c:\users\munitech4u\downloads\compressed\xgboost-0.4a29\xgboost\src\gbm\gbtree-inl.hpp(301): warning C4244: 'argument' : conversion from 'const int64_t' to 'unsigned int', possible loss of data
2>c:\users\munitech4u\downloads\compressed\xgboost-0.4a29\xgboost\src\gbm\gbtree-inl.hpp(303): warning C4244: 'argument' : conversion from 'const int64_t' to 'unsigned int', possible loss of data
2>c:\users\munitech4u\downloads\compressed\xgboost-0.4a29\xgboost\src\gbm\gbtree-inl.hpp(323): warning C4244: 'argument' : conversion from 'const int64_t' to 'unsigned int', possible loss of data
2>c:\users\munitech4u\downloads\compressed\xgboost-0.4a29\xgboost\src\gbm\gbtree-inl.hpp(324): warning C4244: 'argument' : conversion from 'const int64_t' to 'unsigned int', possible loss of data
2>c:\users\munitech4u\downloads\compressed\xgboost-0.4a29\xgboost\src\gbm\gbtree-inl.hpp(326): warning C4244: 'argument' : conversion from 'const int64_t' to 'unsigned int', possible loss of data
2>c:\users\munitech4u\downloads\compressed\xgboost-0.4a29\xgboost\src\gbm\gbtree-inl.hpp(345): warning C4244: 'argument' : conversion from 'const int64_t' to 'unsigned int', possible loss of data
2>c:\users\munitech4u\downloads\compressed\xgboost-0.4a29\xgboost\src\gbm\gbtree-inl.hpp(346): warning C4244: 'argument' : conversion from 'const int64_t' to 'unsigned int', possible loss of data
2>c:\users\munitech4u\downloads\compressed\xgboost-0.4a29\xgboost\src\gbm\gbtree-inl.hpp(348): warning C4244: 'argument' : conversion from 'const int64_t' to 'unsigned int', possible loss of data
2>c:\users\munitech4u\downloads\compressed\xgboost-0.4a29\xgboost\src\gbm\gbtree-inl.hpp(485): warning C4244: 'return' : conversion from 'const int64_t' to 'size_t', possible loss of data
2>  xgboost4j_wrapper.cpp
2>c1xx : fatal error C1083: Cannot open source file: '....\java\xgboost4j_wrapper.cpp': No such file or directory
2>  Generating Code...
4>  io.cpp
4>  dmlc_simple.cpp
4>  gbm.cpp
4>c:\users\munitech4u\downloads\compressed\xgboost-0.4a29\xgboost\src\gbm\gbtree-inl.hpp(162): warning C4244: 'argument' : conversion from 'int64_t' to 'size_t', possible loss of data
4>c:\users\munitech4u\downloads\compressed\xgboost-0.4a29\xgboost\src\gbm\gbtree-inl.hpp(163): warning C4244: 'argument' : conversion from 'int64_t' to 'unsigned int', possible loss of data
4>c:\users\munitech4u\downloads\compressed\xgboost-0.4a29\xgboost\src\gbm\gbtree-inl.hpp(297): warning C4244: 'argument' : conversion from 'const int64_t' to 'unsigned int', possible loss of data
4>c:\users\munitech4u\downloads\compressed\xgboost-0.4a29\xgboost\src\gbm\gbtree-inl.hpp(299): warning C4244: 'argument' : conversion from 'const int64_t' to 'unsigned int', possible loss of data
4>c:\users\munitech4u\downloads\compressed\xgboost-0.4a29\xgboost\src\gbm\gbtree-inl.hpp(301): warning C4244: 'argument' : conversion from 'const int64_t' to 'unsigned int', possible loss of data
4>c:\users\munitech4u\downloads\compressed\xgboost-0.4a29\xgboost\src\gbm\gbtree-inl.hpp(303): warning C4244: 'argument' : conversion from 'const int64_t' to 'unsigned int', possible loss of data
4>c:\users\munitech4u\downloads\compressed\xgboost-0.4a29\xgboost\src\gbm\gbtree-inl.hpp(323): warning C4244: 'argument' : conversion from 'const int64_t' to 'unsigned int', possible loss of data
4>c:\users\munitech4u\downloads\compressed\xgboost-0.4a29\xgboost\src\gbm\gbtree-inl.hpp(324): warning C4244: 'argument' : conversion from 'const int64_t' to 'unsigned int', possible loss of data
4>c:\users\munitech4u\downloads\compressed\xgboost-0.4a29\xgboost\src\gbm\gbtree-inl.hpp(326): warning C4244: 'argument' : conversion from 'const int64_t' to 'unsigned int', possible loss of data
4>c:\users\munitech4u\downloads\compressed\xgboost-0.4a29\xgboost\src\gbm\gbtree-inl.hpp(345): warning C4244: 'argument' : conversion from 'const int64_t' to 'unsigned int', possible loss of data
4>c:\users\munitech4u\downloads\compressed\xgboost-0.4a29\xgboost\src\gbm\gbtree-inl.hpp(346): warning C4244: 'argument' : conversion from 'const int64_t' to 'unsigned int', possible loss of data
4>c:\users\munitech4u\downloads\compressed\xgboost-0.4a29\xgboost\src\gbm\gbtree-inl.hpp(348): warning C4244: 'argument' : conversion from 'const int64_t' to 'unsigned int', possible loss of data
4>c:\users\munitech4u\downloads\compressed\xgboost-0.4a29\xgboost\src\gbm\gbtree-inl.hpp(485): warning C4244: 'return' : conversion from 'const int64_t' to 'size_t', possible loss of data
3>  dmlc_simple.cpp
4>  Generating Code...
3>  gbm.cpp
3>c:\users\munitech4u\downloads\compressed\xgboost-0.4a29\xgboost\src\gbm\gbtree-inl.hpp(162): warning C4244: 'argument' : conversion from 'int64_t' to 'size_t', possible loss of data
3>c:\users\munitech4u\downloads\compressed\xgboost-0.4a29\xgboost\src\gbm\gbtree-inl.hpp(163): warning C4244: 'argument' : conversion from 'int64_t' to 'unsigned int', possible loss of data
3>c:\users\munitech4u\downloads\compressed\xgboost-0.4a29\xgboost\src\gbm\gbtree-inl.hpp(297): warning C4244: 'argument' : conversion from 'const int64_t' to 'unsigned int', possible loss of data
3>c:\users\munitech4u\downloads\compressed\xgboost-0.4a29\xgboost\src\gbm\gbtree-inl.hpp(299): warning C4244: 'argument' : conversion from 'const int64_t' to 'unsigned int', possible loss of data
3>c:\users\munitech4u\downloads\compressed\xgboost-0.4a29\xgboost\src\gbm\gbtree-inl.hpp(301): warning C4244: 'argument' : conversion from 'const int64_t' to 'unsigned int', possible loss of data
3>c:\users\munitech4u\downloads\compressed\xgboost-0.4a29\xgboost\src\gbm\gbtree-inl.hpp(303): warning C4244: 'argument' : conversion from 'const int64_t' to 'unsigned int', possible loss of data
3>c:\users\munitech4u\downloads\compressed\xgboost-0.4a29\xgboost\src\gbm\gbtree-inl.hpp(323): warning C4244: 'argument' : conversion from 'const int64_t' to 'unsigned int', possible loss of data
3>c:\users\munitech4u\downloads\compressed\xgboost-0.4a29\xgboost\src\gbm\gbtree-inl.hpp(324): warning C4244: 'argument' : conversion from 'const int64_t' to 'unsigned int', possible loss of data
3>c:\users\munitech4u\downloads\compressed\xgboost-0.4a29\xgboost\src\gbm\gbtree-inl.hpp(326): warning C4244: 'argument' : conversion from 'const int64_t' to 'unsigned int', possible loss of data
3>c:\users\munitech4u\downloads\compressed\xgboost-0.4a29\xgboost\src\gbm\gbtree-inl.hpp(345): warning C4244: 'argument' : conversion from 'const int64_t' to 'unsigned int', possible loss of data
3>c:\users\munitech4u\downloads\compressed\xgboost-0.4a29\xgboost\src\gbm\gbtree-inl.hpp(346): warning C4244: 'argument' : conversion from 'const int64_t' to 'unsigned int', possible loss of data
3>c:\users\munitech4u\downloads\compressed\xgboost-0.4a29\xgboost\src\gbm\gbtree-inl.hpp(348): warning C4244: 'argument' : conversion from 'const int64_t' to 'unsigned int', possible loss of data
3>c:\users\munitech4u\downloads\compressed\xgboost-0.4a29\xgboost\src\gbm\gbtree-inl.hpp(485): warning C4244: 'return' : conversion from 'const int64_t' to 'size_t', possible loss of data
3>  Generating Code...
4>     Creating library C:\Users\munitech4u\Downloads\Compressed\xgboost-0.4a29\xgboost\windows\Debug\xgboost.lib and object C:\Users\munitech4u\Downloads\Compressed\xgboost-0.4a29\xgboost\windows\Debug\xgboost.exp
4>io.obj : error LNK2019: unresolved external symbol "class rabit::engine::IEngine \* __cdecl rabit::engine::GetEngine(void)" (?GetEngine@engine@rabit@@YAPAVIEngine@12@XZ) referenced in function "int __cdecl rabit::GetRank(void)" (?GetRank@rabit@@YAHXZ)
4>updater.obj : error LNK2001: unresolved external symbol "class rabit::engine::IEngine \* __cdecl rabit::engine::GetEngine(void)" (?GetEngine@engine@rabit@@YAPAVIEngine@12@XZ)
4>xgboost_main.obj : error LNK2001: unresolved external symbol "class rabit::engine::IEngine \* __cdecl rabit::engine::GetEngine(void)" (?GetEngine@engine@rabit@@YAPAVIEngine@12@XZ)
4>updater.obj : error LNK2019: unresolved external symbol "public: __thiscall rabit::engine::ReduceHandle::~ReduceHandle(void)" (??1ReduceHandle@engine@rabit@@QAE@XZ) referenced in function "public: __thiscall rabit::SerializeReducer<struct xgboost::utils::QuantileSketchTemplate<float,float,struct xgboost::utils::WXQSummary<float,float> >::SummaryContainer>::~SerializeReducer<struct xgboost::utils::QuantileSketchTemplate<float,float,struct xgboost::utils::WXQSummary<float,float> >::SummaryContainer>(void)" (??1?$SerializeReducer@USummaryContainer@?$QuantileSketchTemplate@MMU?$WXQSummary@MM@utils@xgboost@@@utils@xgboost@@@rabit@@QAE@XZ)
4>updater.obj : error LNK2019: unresolved external symbol "public: void __thiscall rabit::engine::ReduceHandle::Init(void (__cdecl_)(void const *,void *,int,class MPI::Datatype const &),unsigned int)" (?Init@ReduceHandle@engine@rabit@@QAEXP6AXPBXPAXHABVDatatype@MPI@@@ZI@Z) referenced in function "public: __thiscall rabit::Reducer<struct xgboost::tree::SplitEntry,&public: static void __cdecl xgboost::tree::SplitEntry::Reduce(struct xgboost::tree::SplitEntry &,struct xgboost::tree::SplitEntry const &)>::Reducer<struct xgboost::tree::SplitEntry,&public: static void __cdecl xgboost::tree::SplitEntry::Reduce(struct xgboost::tree::SplitEntry &,struct xgboost::tree::SplitEntry const &)>(void)" (??0?$Reducer@USplitEntry@tree@xgboost@@$1?Reduce@123@SAXAAU123@ABU123@@Z@rabit@@QAE@XZ)
4>updater.obj : error LNK2019: unresolved external symbol "public: __thiscall rabit::engine::ReduceHandle::ReduceHandle(void)" (??0ReduceHandle@engine@rabit@@QAE@XZ) referenced in function "public: __thiscall rabit::Reducer<struct xgboost::tree::SplitEntry,&public: static void __cdecl xgboost::tree::SplitEntry::Reduce(struct xgboost::tree::SplitEntry &,struct xgboost::tree::SplitEntry const &)>::Reducer<struct xgboost::tree::SplitEntry,&public: static void __cdecl xgboost::tree::SplitEntry::Reduce(struct xgboost::tree::SplitEntry &,struct xgboost::tree::SplitEntry const &)>(void)" (??0?$Reducer@USplitEntry@tree@xgboost@@$1?Reduce@123@SAXAAU123@ABU123@@Z@rabit@@QAE@XZ)
4>updater.obj : error LNK2019: unresolved external symbol "public: void __thiscall rabit::engine::ReduceHandle::Allreduce(void *,unsigned int,unsigned int,void (__cdecl_)(void _),void *)" (?Allreduce@ReduceHandle@engine@rabit@@QAEXPAXIIP6AX0@Z0@Z) referenced in function "public: void __thiscall rabit::Reducer<struct xgboost::tree::SplitEntry,&public: static void __cdecl xgboost::tree::SplitEntry::Reduce(struct xgboost::tree::SplitEntry &,struct xgboost::tree::SplitEntry const &)>::Allreduce(struct xgboost::tree::SplitEntry *,unsigned int,void (__cdecl_)(void _),void *)" (?Allreduce@?$Reducer@USplitEntry@tree@xgboost@@$1?Reduce@123@SAXAAU123@ABU123@@Z@rabit@@QAEXPAUSplitEntry@tree@xgboost@@IP6AXPAX@Z1@Z)
4>updater.obj : error LNK2019: unresolved external symbol "void __cdecl rabit::engine::Allreduce_(void *,unsigned int,unsigned int,void (__cdecl_)(void const _,void *,int,class MPI::Datatype const &),enum rabit::engine::mpi::DataType,enum rabit::engine::mpi::OpType,void (__cdecl_)(void _),void *)" (?Allreduce_@engine@rabit@@YAXPAXIIP6AXPBX0HABVDatatype@MPI@@@ZW4DataType@mpi@12@W4OpType@612@P6AX0@Z0@Z) referenced in function "void __cdecl rabit::Allreduce<struct rabit::op::Max,float>(float *,unsigned int,void (__cdecl_)(void _),void *)" (??$Allreduce@UMax@op@rabit@@M@rabit@@YAXPAMIP6AXPAX@Z1@Z)
4>xgboost_main.obj : error LNK2001: unresolved external symbol "void __cdecl rabit::engine::Allreduce_(void *,unsigned int,unsigned int,void (__cdecl_)(void const _,void *,int,class MPI::Datatype const &),enum rabit::engine::mpi::DataType,enum rabit::engine::mpi::OpType,void (__cdecl_)(void *),void *)" (?Allreduce_@engine@rabit@@YAXPAXIIP6AXPBX0HABVDatatype@MPI@@@ZW4DataType@mpi@12@W4OpType@612@P6AX0@Z0@Z)
4>updater.obj : error LNK2019: unresolved external symbol "public: static int __cdecl rabit::engine::ReduceHandle::TypeSize(class MPI::Datatype const &)" (?TypeSize@ReduceHandle@engine@rabit@@SAHABVDatatype@MPI@@@Z) referenced in function "void __cdecl rabit::SerializeReducerFunc_<struct xgboost::utils::QuantileSketchTemplate<float,float,struct xgboost::utils::WXQSummary<float,float> >::SummaryContainer>(void const *,void *,int,class MPI::Datatype const &)" (??$SerializeReducerFunc_@USummaryContainer@?$QuantileSketchTemplate@MMU?$WXQSummary@MM@utils@xgboost@@@utils@xgboost@@@rabit@@YAXPBXPAXHABVDatatype@MPI@@@Z)
4>xgboost_main.obj : error LNK2019: unresolved external symbol "void __cdecl rabit::engine::Finalize(void)" (?Finalize@engine@rabit@@YAXXZ) referenced in function "void __cdecl rabit::Finalize(void)" (?Finalize@rabit@@YAXXZ)
4>xgboost_main.obj : error LNK2019: unresolved external symbol "void __cdecl rabit::engine::Init(int,char \* \* const)" (?Init@engine@rabit@@YAXHQAPAD@Z) referenced in function "void __cdecl rabit::Init(int,char \* \* const)" (?Init@rabit@@YAXHQAPAD@Z)
4>C:\Users\munitech4u\Downloads\Compressed\xgboost-0.4a29\xgboost\windows\Debug\xgboost.exe : fatal error LNK1120: 9 unresolved externals
3>     Creating library C:\Users\munitech4u\Downloads\Compressed\xgboost-0.4a29\xgboost\windows\Debug\xgboost_wrapper.lib and object C:\Users\munitech4u\Downloads\Compressed\xgboost-0.4a29\xgboost\windows\Debug\xgboost_wrapper.exp
3>  xgboost_wrapper.vcxproj -> C:\Users\munitech4u\Downloads\Compressed\xgboost-0.4a29\xgboost\windows\Debug\xgboost_wrapper.dll
========== Rebuild All: 1 succeeded, 3 failed, 0 skipped ==========

**Comment by phunterlau** [comment]
have you tried with Visual Studio 2013 and 64 bits? since 32 bit only supports 2GB memory and there are many other limits anyway.

**Comment by munitech4u** [comment]
I can not build a 64 bit version, as my machine is 32 bit.

**Comment by chrisormandy** [comment]
munitech4u, try opening this file project explorer:
allreduce_base.cc

then find the reference at line 203, and comment out (i.e. put // before) the sleep()

just open the file, and do a search for the phrase 'sleep' and comment that out.

**Comment by munitech4u** [comment]
Tried that, here is the log
Generating Code...
2>     Creating library C:\Users\munitech4u\Downloads\Compressed\xgboost-0.4a29\xgboost\windows\Debug\xgboost.lib and object C:\Users\munitech4u\Downloads\Compressed\xgboost-0.4a29\xgboost\windows\Debug\xgboost.exp
2>io.obj : error LNK2019: unresolved external symbol "class rabit::engine::IEngine * __cdecl rabit::engine::GetEngine(void)" (?GetEngine@engine@rabit@@YAPAVIEngine@12@XZ) referenced in function "int __cdecl rabit::GetRank(void)" (?GetRank@rabit@@YAHXZ)
2>updater.obj : error LNK2001: unresolved external symbol "class rabit::engine::IEngine * __cdecl rabit::engine::GetEngine(void)" (?GetEngine@engine@rabit@@YAPAVIEngine@12@XZ)
2>xgboost_main.obj : error LNK2001: unresolved external symbol "class rabit::engine::IEngine * __cdecl rabit::engine::GetEngine(void)" (?GetEngine@engine@rabit@@YAPAVIEngine@12@XZ)
2>updater.obj : error LNK2019: unresolved external symbol "public: __thiscall rabit::engine::ReduceHandle::~ReduceHandle(void)" (??1ReduceHandle@engine@rabit@@QAE@XZ) referenced in function "public: __thiscall rabit::SerializeReducer<struct xgboost::utils::QuantileSketchTemplate<float,float,struct xgboost::utils::WXQSummary<float,float> >::SummaryContainer>::~SerializeReducer<struct xgboost::utils::QuantileSketchTemplate<float,float,struct xgboost::utils::WXQSummary<float,float> >::SummaryContainer>(void)" (??1?$SerializeReducer@USummaryContainer@?$QuantileSketchTemplate@MMU?$WXQSummary@MM@utils@xgboost@@@utils@xgboost@@@rabit@@QAE@XZ)
2>updater.obj : error LNK2019: unresolved external symbol "public: void __thiscall rabit::engine::ReduceHandle::Init(void (__cdecl*)(void const *,void *,int,class MPI::Datatype const &),unsigned int)" (?Init@ReduceHandle@engine@rabit@@QAEXP6AXPBXPAXHABVDatatype@MPI@@@ZI@Z) referenced in function "public: __thiscall rabit::Reducer<struct xgboost::tree::SplitEntry,&public: static void __cdecl xgboost::tree::SplitEntry::Reduce(struct xgboost::tree::SplitEntry &,struct xgboost::tree::SplitEntry const &)>::Reducer<struct xgboost::tree::SplitEntry,&public: static void __cdecl xgboost::tree::SplitEntry::Reduce(struct xgboost::tree::SplitEntry &,struct xgboost::tree::SplitEntry const &)>(void)" (??0?$Reducer@USplitEntry@tree@xgboost@@$1?Reduce@123@SAXAAU123@ABU123@@Z@rabit@@QAE@XZ)
2>updater.obj : error LNK2019: unresolved external symbol "public: __thiscall rabit::engine::ReduceHandle::ReduceHandle(void)" (??0ReduceHandle@engine@rabit@@QAE@XZ) referenced in function "public: __thiscall rabit::Reducer<struct xgboost::tree::SplitEntry,&public: static void __cdecl xgboost::tree::SplitEntry::Reduce(struct xgboost::tree::SplitEntry &,struct xgboost::tree::SplitEntry const &)>::Reducer<struct xgboost::tree::SplitEntry,&public: static void __cdecl xgboost::tree::SplitEntry::Reduce(struct xgboost::tree::SplitEntry &,struct xgboost::tree::SplitEntry const &)>(void)" (??0?$Reducer@USplitEntry@tree@xgboost@@$1?Reduce@123@SAXAAU123@ABU123@@Z@rabit@@QAE@XZ)
2>updater.obj : error LNK2019: unresolved external symbol "public: void __thiscall rabit::engine::ReduceHandle::Allreduce(void *,unsigned int,unsigned int,void (__cdecl*)(void *),void *)" (?Allreduce@ReduceHandle@engine@rabit@@QAEXPAXIIP6AX0@Z0@Z) referenced in function "public: void __thiscall rabit::Reducer<struct xgboost::tree::SplitEntry,&public: static void __cdecl xgboost::tree::SplitEntry::Reduce(struct xgboost::tree::SplitEntry &,struct xgboost::tree::SplitEntry const &)>::Allreduce(struct xgboost::tree::SplitEntry *,unsigned int,void (__cdecl*)(void *),void *)" (?Allreduce@?$Reducer@USplitEntry@tree@xgboost@@$1?Reduce@123@SAXAAU123@ABU123@@Z@rabit@@QAEXPAUSplitEntry@tree@xgboost@@IP6AXPAX@Z1@Z)
2>updater.obj : error LNK2019: unresolved external symbol "void __cdecl rabit::engine::Allreduce_(void *,unsigned int,unsigned int,void (__cdecl*)(void const *,void *,int,class MPI::Datatype const &),enum rabit::engine::mpi::DataType,enum rabit::engine::mpi::OpType,void (__cdecl*)(void *),void *)" (?Allreduce_@engine@rabit@@YAXPAXIIP6AXPBX0HABVDatatype@MPI@@@ZW4DataType@mpi@12@W4OpType@612@P6AX0@Z0@Z) referenced in function "void __cdecl rabit::Allreduce<struct rabit::op::Max,float>(float *,unsigned int,void (__cdecl*)(void *),void *)" (??$Allreduce@UMax@op@rabit@@M@rabit@@YAXPAMIP6AXPAX@Z1@Z)
2>xgboost_main.obj : error LNK2001: unresolved external symbol "void __cdecl rabit::engine::Allreduce_(void *,unsigned int,unsigned int,void (__cdecl*)(void const *,void *,int,class MPI::Datatype const &),enum rabit::engine::mpi::DataType,enum rabit::engine::mpi::OpType,void (__cdecl*)(void *),void *)" (?Allreduce_@engine@rabit@@YAXPAXIIP6AXPBX0HABVDatatype@MPI@@@ZW4DataType@mpi@12@W4OpType@612@P6AX0@Z0@Z)
2>updater.obj : error LNK2019: unresolved external symbol "public: static int __cdecl rabit::engine::ReduceHandle::TypeSize(class MPI::Datatype const &)" (?TypeSize@ReduceHandle@engine@rabit@@SAHABVDatatype@MPI@@@Z) referenced in function "void __cdecl rabit::SerializeReducerFunc_<struct xgboost::utils::QuantileSketchTemplate<float,float,struct xgboost::utils::WXQSummary<float,float> >::SummaryContainer>(void const *,void *,int,class MPI::Datatype const &)" (??$SerializeReducerFunc_@USummaryContainer@?$QuantileSketchTemplate@MMU?$WXQSummary@MM@utils@xgboost@@@utils@xgboost@@@rabit@@YAXPBXPAXHABVDatatype@MPI@@@Z)
2>xgboost_main.obj : error LNK2019: unresolved external symbol "void __cdecl rabit::engine::Finalize(void)" (?Finalize@engine@rabit@@YAXXZ) referenced in function "void __cdecl rabit::Finalize(void)" (?Finalize@rabit@@YAXXZ)
2>xgboost_main.obj : error LNK2019: unresolved external symbol "void __cdecl rabit::engine::Init(int,char * * const)" (?Init@engine@rabit@@YAXHQAPAD@Z) referenced in function "void __cdecl rabit::Init(int,char * * const)" (?Init@rabit@@YAXHQAPAD@Z)
2>C:\Users\munitech4u\Downloads\Compressed\xgboost-0.4a29\xgboost\windows\Debug\xgboost.exe : fatal error LNK1120: 9 unresolved externals
========== Rebuild All: 0 succeeded, 2 failed, 0 skipped ==========
