### ISSUE TITLE
We need a choice between float32 and float64.

### ISSUE THREAD

**Issue by Roffild** [dmlc/xgboost#6572]
I am trying to convert a forest to a simple Alglib format where the entire forest is stored in a double (float64) array. But because of float32, the wrong leaves are triggered.

```
float64 = 0.366326530612243 (YES)
float32 = 0.366326541 (NO)
338:[f171<0.366326541] yes=483,no=484,missing=483
```

Video cards support float64, but calculations slow down several times.

**Comment by hcho3** [comment]
No, we do not plan to support float64 in the foreseeable future. As you point out, double-precision arithmetic is significantly slower than single-precision on GPUs, and there is no significant benefit for the increased precision.
