### ISSUE TITLE
DumpModel does not support multiclass.

### ISSUE THREAD

**Issue by Roffild** [dmlc/xgboost#6574]
DumpModel only dumps one value instead of an array in 'leaf'.

```
{'nodeid': 61, 'leaf': -0.0772727281}
```

1.3.1

**Comment by hcho3** [comment]
This is expected, because in XGBoost, each tree always yields a single scalar output. To determine prediction for a multi-class classifier, we divide the trees into C groups (C = number of classes) and compute the partial sum of outputs for each group.
