### ISSUE TITLE
Add option to treat all missing values as zeros

### ISSUE THREAD

**Issue by keithdlandry** [dmlc/xgboost#6580]
Has anybody made progress on this? I think this is the right approach. Sparse matrices are meant to hold zeros not missing values.

.
.
.

My understanding is that when training with sparse input matrix and a special "missing" value is specified (say `Float.NaN`) at the same time, XGBoost will first go through the non-zero entries of the sparse matrix and remove any entry that takes that value from the sparse data structure; afterwards, any "empty" entries in the training matrix will be interpreted by XGBoost as missing values.

I'd image if there are only a couple of non-missing zero values, one would be able to circumvent this behaviour by explicitly setting their values to `0.0` in the sparse matrix.

As @nedStackAdapt mentioned, for sparse matrices, the semantics is typically that the "empty" entries represents `0`s, not missing values. To solve this issue, I wonder if we can ask the users to explicitly declare a value they would like XGBoost to consider as missing without removing them from the sparse matrix's internal structure?

_Originally posted by @zhangxiubo in https://github.com/dmlc/xgboost/issues/4601#issuecomment-506293779_

**Comment by hcho3** [comment]
> Sparse matrices are meant to hold zeros not missing values.

This is not the case always. In some applications, missing values are distinguished from zeros.

I do think that there should be an option to tweak the XGBoost algorithm to treat all missing values in a sparse matrix as if they are zeros.

**Comment by zhangxiubo** [comment]
Would it be possible for XGBoost to support representing both zeros as the "empty" elements and missing values in the same sparse matrix?

**Comment by hcho3** [comment]
> Would it be possible for XGBoost to support representing both zeros as the "empty" elements and missing values in the same sparse matrix?

Probably not. Users will be asked choose between two options:
1) the missing values in a sparse matrix represent actually missing values; or
2) the missing values in a sparse matrix represent zeros.

This is to make the implementation somewhat feasible.

**Comment by trivialfis** [comment]
> Probably not.

I agree.

**Comment by hcho3** [comment]
Currently only Option 1 is supported. Are we not going to support Option 2?

**Comment by trivialfis** [comment]
I don't think it's profitable.  To treat missing values as 0, we have 2 paths to go:

1. Fill in those 0s in DMatrix construction and we get a dense DMatrix.  This doesn't save much memory so users might just put in a dense matrix instead.
2. We change all the internal algorithms that interact with `DMatrix` and let them restore those 0s on the run.  I don't see that happening in foreseeable future. ;-)

**Comment by hcho3** [comment]
Got it. Closing as "won't fix"
