### ISSUE TITLE
[R] Is the package for R>=3.3.0?

### ISSUE THREAD

**Issue by hbaniecki** [dmlc/xgboost#6581]
Hi, a possible improvement: `xgboost` [CRAN entry](https://cran.r-project.org/web/packages/xgboost/index.html) shows `R>=3.3.0` which may not be true because none of these versions is actually tested with CI https://github.com/dmlc/xgboost/blob/master/.github/workflows/r_tests.yml.

**Comment by hcho3** [comment]
We are not aware of any incompatibility that requires a newer R version. See https://github.com/dmlc/xgboost/pull/6414#discussion_r527905172:

> I think that it's better for libraries to only have floors / ceilings on major versions (like >=1.0) unless they know about a specific incompatibility with some minor version. That makes your package work for the largest number of possible users.

**Comment by jameslamb** [comment]
Yes, I feel that you shouldn't move the floor up until you know that there is an incompatibility or extra maintenance burden caused by it.

**Comment by hbaniecki** [comment]
I agree. The aim of the issue was to extend CI tests to other R versions. Anyway, this can be closed if not desired.
