### ISSUE TITLE
XGBoost GPU error on WSL2 (using tree_method = 'gpu_hist')

### ISSUE THREAD

**Issue by BenWynne-Morris** [dmlc/xgboost#6585]
I've run into an error trying to get XGBoost GPU working on WSL2, which also resulted in a black screen for the second monitor.

```
Attempting to train XGBoost with tree method of gpu_hist causes the following error:
[23:10:50] task [xgboost.dask]:tcp://127.0.0.1:45075 got new rank 0
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  for_each: failed to synchronize: cudaErrorUnknown: unknown error
```

**Environment**
- Microsoft Windows 10 Pro Insider Preview
- Version 2004 (Build 21277)
- Windows Subsystem Linux 2 - Ubuntu 20.04 
- NVIDA Driver 465.21 / CUDA 11.0
-  xgboost 1.3.0dev.rapidsai0.17  
-  cuda11.0py37_0

Here is how I installed my Rapids environment:
```
$ conda create -n rapids-0.17 python=3.7
$ conda activate rapids-0.17
$ conda install -c rapidsai -c nvidia -c conda-forge \
   -c defaults rapids-blazing=0.17 python=3.7 cudatoolkit=11.0
```

**Performance**
WSL2 is generally working quite well since installation a couple of weeks ago:
- I've been able to train some machine learning algorithms (e.g. kmeans) on WSL2 with Python + Dask + Cuda
- I've also been able to train XGBoost on WSL2 with Python + Pandas (i.e. CPU); but so far not on the GPU (with or without Dask)

**Code**
Code example was taken from https://medium.com/rapids-ai/a-new-official-dask-api-for-xgboost-e8b10f3d1eb7
Example data source: `$ wget https://archive.ics.uci.edu/ml/machine-learning-databases/00280/HIGGS.csv.gz`

The key code bit below that seems to cause the crash is 'tree_method': 'gpu_hist'

Here is the code I ran:
```
from dask.distributed import Client
from dask_cuda import LocalCUDACluster
cluster = LocalCUDACluster()
client = Client(cluster)
import xgboost as xgb
import dask_cudf
fname = './data/HIGGS.csv'
colnames = ["label"] + ["feature-%02d" % i for i in range(1,29)]
dask_df = dask_cudf.read_csv(fname, header=None, names=colnames)
X = dask_df[dask_df.columns.difference(['label'])]
y = dask_df['label']
dtrain = xgb.dask.DaskDMatrix(client, X, y)
params = {'tree_method': 'gpu_hist'}
output = xgb.dask.train(client, params, dtrain, num_boost_round=100)
```

This issue has been moved from https://github.com/rapidsai/cudf/issues/7101 at the suggestion of @kkraus14

**Comment by trivialfis** [comment]
For now please use Linux natively.  We don't have plan on supporting WSL, at least not on regular CI pipeline.

**Comment by trivialfis** [comment]
Closing as duplication of https://github.com/dmlc/xgboost/issues/5869 .

**Comment by BenWynne-Morris** [comment]
> For now please use Linux natively. We don't have plan on supporting WSL, at least not on regular CI pipeline.

OK, thanks for  the clarity.  Disappointing.

**Comment by trivialfis** [comment]
@BenWynne-Morris  Not much to be disappointed about from my opinion.   The WSL is created to mimic native Linux as much as possible so things should "just work".  I don't see why a machine learning library should treat it as a separated platform.  XGBoost supports Windows and you can use that too.

**Comment by trivialfis** [comment]
> he WSL is created to mimic native Linux as much as possible so things should "just work"

From that point, the concept of "support" is non-exist, if xgboost doesn't work, then it's a bug in WSL and related components.

**Comment by BenWynne-Morris** [comment]
"XGBoost supports Windows and you can use that too."
@trivialfis Sure, but I was hoping to train XGBoost on the GPU using RAPIDS.  Unfortunately, RAPIDS doesn't work on Windows, (only on native Linux and WSL2 Linux).  Other machine learning packages are working with RAPIDS on my WSL2 setup, it's just XGBoost where I haven't been able to get things working.  It's looking like I'll need to create a dedicated Linux machine for this project, as you suggest.  I was just hoping to use WSL2 instead (since I need to keep the Windows installation for my work).  
Thanks anyway.
