### ISSUE TITLE
 [R] custom metrics in xgb.cv

### ISSUE THREAD

**Issue by hectep** [dmlc/xgboost#659]
The issue is related to  #333
I'm trying to implement the same  quadratic weighted kappa in xgb.cv
The code is:
```
evalerror <- function(preds, dtrain) {
      library(Metrics)
      labels <- getinfo(dtrain, "label")
      err <- ScoreQuadraticWeightedKappa(as.numeric(labels),as.numeric(preds))
      return(list(metric = "kappa", value = err))
}

param <- list(  objective           = "reg:linear",
                nthread             = 4,
                eta                 = 0.05,
                max_depth           = 100,  
                subsample           = 0.6,
                min_child_weight    = 2, 
                colsample_bytree    = 0.6,
                eval_metric         = "rmse"
           
)

cv <- xgb.cv(data = dtrain, nfold = 5, maximize = TRUE, feval = evalerror, 
             nround = 200, 
             early.stop.round = 10,  print.every.n = 10)
```
But after the first round it returns this error:
```
[0]	train-kappa:NaN+NA	test-kappa:NaN+NA
Error in if ((maximize && score > bestScore) || (!maximize && score <  : 
  missing value where TRUE/FALSE needed
```
Do i miss something obvious here?

**Comment by terrytangyuan** [comment]
It's possible that you label/pred contains NA. Could you print those out to see if it's true? It would be better if you can provide a reproducible example. What's the output of str(dtrain)?

**Comment by hectep** [comment]
No, there is no NA in the label.
Here is both data and the script attached. I believe i'm missing something obvious and not related to the xgb package.
Thanks for your time, Terry!


[prudential.zip](https://github.com/dmlc/xgboost/files/83602/prudential.zip)

**Comment by gauravchawla03** [comment]
preds and labels should be in integer form. Try as.integer instead of as.numeric, it wont show error.
