### ISSUE TITLE
XGBoost4J release supporting scala 2.13

### ISSUE THREAD

**Issue by JamesTreleaven** [dmlc/xgboost#6596]
An XGBoost4J release supporting Scala-2.13 would be terrific.  Even a estimate of when such support might be coming would really help me out.

Thanks.

**Comment by hcho3** [comment]
No concrete estimate yet. We are short-handed right now, especially for the JVM and R packages.

**Comment by hcho3** [comment]
Also, Spark 3.0 is built with Scala 2.12. The policy is that XGBoost uses the version of Scala that's used by Spark.

**Comment by hamsummit** [comment]
Hi is there any update to this issue or its timeline? Seems like Spark 3.2 is now supporting Scala 2.13 at least.

Personally this is the only dependency blocking my project from upgrading to 2.13, so would appreciate an update on if it's still not planned for a while.

**Comment by trivialfis** [comment]
@wbo4958 Could you please take a look when you are available?

**Comment by wbo4958** [comment]
This is no a high-priority issue, let's keep it here and will check it when I got time.

**Comment by MohammadForouhesh** [comment]
Any update on supporting scala 2.13 yet?

**Comment by dotbg** [comment]
Duplicates https://github.com/dmlc/xgboost/issues/8650

**Comment by hcho3** [comment]
Support for Scala 2.13 was added in #9099
