### ISSUE TITLE
xgboost Windows installation problems with Anaconda

### ISSUE THREAD

**Issue by beckeroobonsai** [dmlc/xgboost#661]
I downloaded the xgboost package and built it with visual studio, following the instructions for a 64bit system here: https://github.com/dmlc/xgboost/tree/master/windows.   

The import xgboost statement only worked in jupyter notebook environment once I appended sys.path to include the folder containing the xgboost_wrapper.dll file. 
For me, this required typing 
sys.path.append('C:\\Anaconda3\\Lib\\site-packages\\xgboost-0.4-py3.5.egg\\xgboost')

I tried a very simple bit of code to see if xgboost was running correctly. Typing
test = xgboost.XGBClassifier()
gave the following error:
AttributeError                            Traceback (most recent call last)
< ipython-input-23-6d2dcfcc7a24 > in < module >()
----> 1 test = xgboost.XGBClassifier()

AttributeError: module 'xgboost' has no attribute 'XGBClassifier'
 

The functions of xgboost do not appear to be getting correctly imported or linked to.
The output of dir(xgboost)  was strangely only 
['__ doc__', '__ loader__', '__ name__', '__ package__', '__ path__', '__ spec__']

What am I missing to get xgboost to work?  Any advice on what else to check would be greatly appreciated.

**Comment by phunterlau** [comment]
have you tried deleting the old installation and re-do the install from today's github repo? XGBClassifier is defined in the python-package/xgboost/sklearn.py and should come from the .sklearn package.
