### ISSUE TITLE
External Memory Usage with GPU still out of memory with large data size

### ISSUE THREAD

**Issue by PeterPanonGit** [dmlc/xgboost#6629]
I have a relatively large data set that has ~3000 features and ~100 million rows. I tried to use External Memory for GPU but it still out of memory and I have to set subsample to a very small number in order for it to fit into the 16G GPU memory.

Since I don't want to use a very small subsample number, I wonder if it is possible for me to change the page size in order for the data to fit into the GPU memory. Based on my understanding, page size is defined as a constant here: 
https://github.com/dmlc/xgboost/blob/master/include/xgboost/data.h#L545

The DMatrix::Create() method has page_size argument but the c_api for constructing DMatrix from file did not allow users to change the page size:
https://github.com/dmlc/xgboost/blob/master/src/c_api/c_api.cc#L163

If I reduce the page size, would it help to make the data fit into the GPU memory? What would be the potential issues of changing the page size besides potentially making it to run slower?

@trivialfis @rongou

**Comment by rongou** [comment]
The page size is only used during the quantile generation phase. The final, sampled ELLPACK matrix still needs to fit in GPU memory. When I tested on a 16GB GPU (https://arxiv.org/abs/2005.09148) I was able to fit 500 features and 85 million rows with a 0.1 sampling rate. A rough estimate for you dataset is probably around 0.014 sampling rate? An easy way out is to go with multiple GPUs, or distributed training using Spark.

**Comment by trivialfis** [comment]
> or distributed training using Spark.

Or dask.  ;-)

**Comment by trivialfis** [comment]
A bit more clarification.   There's a limit on scaling when using gpu based external memory, the choice was made to avoid copying data as `external memory -> host -> gpu` for each leaf expansion, which is quite costly.

**Comment by PeterPanonGit** [comment]
Cool. Thanks a lot for the explanation!
