### ISSUE TITLE
Access violation (python, windows)

### ISSUE THREAD

**Issue by tataraidze** [dmlc/xgboost#663]
I tried to use xgboost in python (Windows 7 x64, Anaconda 64-bit, IPython 3.4). But I got strange errors. Somtimes it was strange label values (I'm sure that they were ok) - "XGBoostError: b'SoftmaxMultiClassObj: label must be in [0, num_class), num_class=38 but found -2147483648 in label", somtimes it was "access violation" error. The error was changed without any changes in code. Meanwile, python demos work fine.
![1](https://cloud.githubusercontent.com/assets/16029326/11511321/88f51d3e-9879-11e5-9ff6-9381756024d8.png)
![2](https://cloud.githubusercontent.com/assets/16029326/11511320/88f42a8c-9879-11e5-8d73-0d18d356e565.png)

**Comment by emuchogu** [comment]
Fixed the issue by moving the path reference for MinGW-W64 to the front of the PATH system variable.
Cleaned, rebuilt and re-installed xgboost. Problem solved.
