### ISSUE TITLE
fail to compile xgboost 1.3 with GPU and following on windows 10

### ISSUE THREAD

**Issue by xtimbeau** [dmlc/xgboost#6634]
Hi to all,
I failed at compiling xgboost 1.3 and more recent with gpu on windows 10. My config is CUDA 10.2 or CUDA 11.2, visual studio community 2019, with v140 avalaible. I succeed in compiling xgboost 1.2.1 with this setup and this command
```
cmake .. -G"Visual Studio 16 2019" -A x64 -DR_LIB=ON -DUSE_CUDA=ON -DGPU_COMPUTE_VER=75 -T v140,cuda=10.2
cmake --build . --target install --config Release
```
When I clone more recent version (1.3.3 for instance), the process stops on gpu_predictor.cu with the following message (I did the submodule init and update)
```
7 errors detected in the compilation of "C:/Users/82261/AppData/Local/Temp/tmpxft_00006b84_00000000-7_gpu_predictor.cpp1.ii".
  gpu_predictor.cu
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\BuildCustomizations\CUDA 10.2.targets(764,9): error MSB3721: La commande ""C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin\nvcc.exe" -gencode=arch=compute_75, 
code=\"sm_75,compute_75\" -gencode=arch=compute_75,code=\"compute_75,compute_75\" --use-local-env -ccbin "E:\Program Files\VC\bin\amd64" -x cu  -I"E:\github\xgboost-1.3.3-GPU\cub" -I"E:\github\xgboost-1.3.3-GPU\include" -I"E:\ 
github\xgboost-1.3.3-GPU\dmlc-core\include" -I"E:\github\xgboost-1.3.3-GPU\rabit\include" -I"E:\github\xgboost-1.3.3-GPU\gputreeshap" -I"E:\github\xgboost-1.3.3-GPU\build\dmlc-core\include" -I"C:\Program Files\NVIDIA GPU Compu 
ting Toolkit\CUDA\v10.2\include"     --keep-dir x64\Release -maxrregcount=0  --machine 64 --compile -cudart static --expt-extended-lambda --expt-relaxed-constexpr -lineinfo -Xcompiler="/EHsc -Ob2 -openmp /utf-8"    -D_WINDOWS  
-DNDEBUG -D_CRT_SECURE_NO_WARNINGS -D_CRT_SECURE_NO_DEPRECATE -DXGBOOST_USE_CUDA=1 -DTHRUST_IGNORE_CUB_VERSION_CHECK=1 -DDMLC_LOG_CUSTOMIZE=1 -DXGBOOST_MM_PREFETCH_PRESENT=1 -D__USE_XOPEN2K8 -DDMLC_CORE_USE_CMAKE -DDMLC_USE_CX 
X11=1 -DXGBOOST_STRICT_R_MODE=1 -DXGBOOST_CUSTOMIZE_GLOBAL_PRNG=1 -DDMLC_LOG_BEFORE_THROW=0 -DDMLC_DISABLE_STDIN=1 -DRABIT_CUSTOMIZE_MSG_ -DRABIT_STRICT_CXX98_ -D"CMAKE_INTDIR=\"Release\"" -DWIN32 -D_WINDOWS -DNDEBUG -D_CRT_SE 
CURE_NO_WARNINGS -D_CRT_SECURE_NO_DEPRECATE -DXGBOOST_USE_CUDA=1 -DTHRUST_IGNORE_CUB_VERSION_CHECK=1 -DDMLC_LOG_CUSTOMIZE=1 -DXGBOOST_MM_PREFETCH_PRESENT=1 -D__USE_XOPEN2K8 -DDMLC_CORE_USE_CMAKE -DDMLC_USE_CXX11=1 -DXGBOOST_ST 
RICT_R_MODE=1 -DXGBOOST_CUSTOMIZE_GLOBAL_PRNG=1 -DDMLC_LOG_BEFORE_THROW=0 -DDMLC_DISABLE_STDIN=1 -DRABIT_CUSTOMIZE_MSG_ -DRABIT_STRICT_CXX98_ -D"CMAKE_INTDIR=\"Release\"" -D_MBCS -Xcompiler "/EHsc /W3 /nologo /O2 /Fdobjxgboost 
.dir\Release\objxgboost.pdb /FS /Zi  /MT /GR" -o objxgboost.dir\Release\gpu_predictor.obj "E:\github\xgboost-1.3.3-GPU\src\predictor\gpu_predictor.cu"" s'est arrêtée avec le code 1. [E:\github\xgboost-1.3.3-GPU\build\src\objxg 
boost.vcxproj]

```
the first error (of the 7 errors) is 
`C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include\thrust/detail/type_traits.h(436): error : incomplete type is not allowed [E:\github\xgboost-1.3.3-GPU\build\src\objxgboost.vcxproj]`
the second
`E:\github\xgboost-1.3.3-GPU\gputreeshap\GPUTreeShap/gpu_treeshap.h(946): error : no instance of overloaded function "thrust::reduce_by_key" matches the argument list [E:\github\xgboost-1.3.3-GPU\build\src\objxgboost.vcxproj]`

When I compile without CUDA, everything is fine. Compiling without R_LIB does not change anything. CUDA 10.2 and 11.2 bring the same errors for 1.3.3 but work fine for 1.2.1
Any hints ?

**Comment by trivialfis** [comment]
@RAMitchell

**Comment by RAMitchell** [comment]
It looks like our continuous integration currently tests visual studio 2017. Can you try this version?

**Comment by xtimbeau** [comment]
@RAMitchell 
Thank's a lot. It worked. Visual Studio 2017 with either CUDA 10.2 or 11.2 is compiling successfully the package.
I tried others combinations (VS19, VS15, CUDAx) but apparently not that one ! May be the doc should reflect this as it is not true before 1.3.

**Comment by trivialfis** [comment]
Good to know that's solved.  I don't think we will document that as we usually workaround various compiler bugs.  If you find a way to workaround this one please open a PR.

**Comment by trivialfis** [comment]
I tried CUDA 10.2 with vs19 but without R_LIB and it works pretty well.  Feel free to reopen or open a new one if additional information is available.
