### ISSUE TITLE
xgboost cross validation in Pyspark ( Jupyterhub ) error 

### ISSUE THREAD

**Issue by pawncrusher** [dmlc/xgboost#6637]
using xgboost in spark jar files: 

- cudf-0.9.2-cuda10-1.jar , 
- xgboost4j_2.x-1.0.0-Beta5.jar ,
- xgboost4j-spark_2.x-1.0.0-Beta5.jar

spark.sparkContext.addPyFile("s3://mfin1awssubprod-dev-emr2r-bootstrap01/jupyter/nagveks_adm/xgboost/xgboost4j-spark_2.x-1.0.0-Beta5.jar")

input train dataset is a dense vector with nulls

+-----+--------------------+
|label|            features|
+-----+--------------------+
| 4800|[1.0,107043.0,224...|
| 7500|[1.0,106132.0,225...|
| 7400|[1.0,92942.0,2538...|
|15000|[1.0,21054.0,2527...| ......

Code:

from ml.dmlc.xgboost4j.scala.spark import XGBoostRegressor , XGBoostRegressionModel
from pyspark.ml.evaluation import RegressionEvaluator
from pyspark.ml.tuning import CrossValidator, ParamGridBuilder, CrossValidatorModel

xgb = XGBoostRegressor(
    featuresCol="features",
    labelCol="label",
    predictionCol="prediction",
    objective="reg:linear")

paramGrid = ParamGridBuilder()\
     .addGrid(xgb.maxDepth, [3,5,6]) \
     .addGrid(xgb.eta, [0.10,0.15]) \
     .addGrid(xgb.minChildWeight, [3.0]) \
     .addGrid(xgb.numRound, [10]) \
     .addGrid(xgb.numEarlyStoppingRounds, [10]) \
     .addGrid(xgb.maximizeEvaluationMetrics, [True]) \
     .build()

crossval = CrossValidator(estimator=xgb,
                          estimatorParamMaps=paramGrid,
                          evaluator=RegressionEvaluator(),
                          numFolds=2) 

xgb_model = crossval.fit(input_data_train)

Error:

fit() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File 

"/mnt2/yarn/usercache/nagveks_adm/appcache/application_1608320475747_0603/container_1608320475747_0603_01_000001/pyspark.zip/pyspark/ml/base.py", line 132, in fit
    return self._fit(dataset)

  File 

"/mnt2/yarn/usercache/nagveks_adm/appcache/application_1608320475747_0603/container_1608320475747_0603_01_000001/pyspark.zip/pyspark/ml/tuning.py", line 304, in _fit

    for j, metric, subModel in pool.imap_unordered(lambda f: f(), tasks):

  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 735, in next
    raise value

  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 119, in worker

    result = (True, func(*args, **kwds))

  File 

"/mnt2/yarn/usercache/nagveks_adm/appcache/application_1608320475747_0603/container_1608320475747_0603_01_000001/pyspark.zip/pyspark/ml/tuning.py", line 304, in <lambda>
    for j, metric, subModel in pool.imap_unordered(lambda f: f(), tasks):

  File 

"/mnt2/yarn/usercache/nagveks_adm/appcache/application_1608320475747_0603/container_1608320475747_0603_01_000001/pyspark.zip/pyspark/ml/tuning.py", line 52, in singleTask
    index, model = next(modelIter)

  File 

"/mnt2/yarn/usercache/nagveks_adm/appcache/application_1608320475747_0603/container_1608320475747_0603_01_000001/pyspark.zip/pyspark/ml/base.py", line 62, in __next__
    return index, self.fitSingleModel(index)

  File 

"/mnt2/yarn/usercache/nagveks_adm/appcache/application_1608320475747_0603/container_1608320475747_0603_01_000001/pyspark.zip/pyspark/ml/base.py", line 106, in fitSingleModel
    return estimator.fit(dataset, paramMaps[index])

TypeError: fit() takes 2 positional arguments but 3 were given

Not passing 3 arguments in .fit, not sure why I am getting this error.

**Comment by trivialfis** [comment]
Closing as pyspark is not supported.
