### ISSUE TITLE
XGBRegressor returning NaN for feature importances

### ISSUE THREAD

**Issue by ldulude-cmb** [dmlc/xgboost#6639]
Running an XGBRegressor model through sklearn and asking for feature importances, and I'm getting all NaNs as a result. The data I'm using is proprietary, so I can't post it, but I can't see anything different about it vs. other datasets I've used. The variables involved all range from 0 to 10, and there are 7 features. The model has an R2 value of about 0.45, and looking at the correlations and charts of each feature vs. the outcome variable, I can see that there is a connection between them, so I don't think it's an issue of something wrong with the data. The one thing I did notice is that if I leave the data unweighted, I get feature importances, so I think the issue has to do with the weight.

Here's what I'm running:

```
self.model = XGBRegressor(objective = 'reg:squarederror',
                         booster = 'gbtree',
                         n_estimators = 1000,
                         learning_rate = .005,
                         subsample = .5,
                         max_depth = 4,
                         min_child_weight = 10,
                         tree_method = 'hist',
                         colsample_bytree = .5,
                         random_state = self.seed)

self.model.fit(self.df_features, self.df_labels, sample_weight = self.df_modelweight)
model_imp = self.model.feature_importances_
```

I've also tried changing that last line to `self.model.get_booster().get_score(importance_type='weight')` per [this post](https://datascience.stackexchange.com/questions/19882/xgboost-how-to-use-feature-importances-with-xgbregressor), but it doesn't change what I get.

Versioning:
```
System:
    python: 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\me\Anaconda3\python.exe
   machine: Windows-10-10.0.18362-SP0

Python dependencies:
          pip: 20.2.4
   setuptools: 50.3.1.post20201107
      sklearn: 0.23.2
        numpy: 1.19.2
        scipy: 1.5.2
       Cython: 0.29.21
       pandas: 1.1.3
   matplotlib: 3.3.2
       joblib: 0.17.0
threadpoolctl: 2.1.0

Built with OpenMP: True
```

**Comment by trivialfis** [comment]
Cou you pl provide a sample script that I can run?

**Comment by ldulude-cmb** [comment]
Try it with [this data](https://docs.google.com/spreadsheets/d/1Ofp3d6Uz_DLLxfRV0z_OnqQTFLkffyykujr5mSS00Hw/edit?usp=sharing); the 7 IV variables are the features

```
model = XGBRegressor(objective = 'reg:squarederror',
                         booster = 'gbtree',
                         n_estimators = 1000,
                         learning_rate = .005,
                         subsample = .5,
                         max_depth = 4,
                         min_child_weight = 10,
                         tree_method = 'hist',
                         colsample_bytree = .5,
                         random_state = self.seed)

model.fit(IVs, DV, sample_weight = weight)
model_imp = model.feature_importances_
```

**Comment by ldulude-cmb** [comment]
Please let me know if I can provide any other information!

**Comment by trivialfis** [comment]
You set the `min_child_weight` too high, no split is found during training, so none of the feature has been used.
