### ISSUE TITLE
[RFC] Drop CUDA 10.0 support

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#6642]
CUDA 10.0 was released in September 2018, and many GPU packages such as RAPIDS has recently dropped support for CUDA 10.0.

Proposal. XGBoost should drop support for CUDA 10.0 and require CUDA 10.1 or later.

This is to simplify development and also reduce the workload on our testing server.

@dmlc/xgboost-committer

**Comment by hcho3** [comment]
cc @JohnZed @kkraus14 @canonizer for visibility

**Comment by terrytangyuan** [comment]
+1 for upgrading CUDA

**Comment by trivialfis** [comment]
@hcho3 I think this release would be a good time for dropping cuda 10.x. ;-)

**Comment by kkraus14** [comment]
+1 to dropping CUDA 10.x generally but that may be a bit aggressive :)
