### ISSUE TITLE
xgboost Quality calculation in xgb.model.dt.tree

### ISSUE THREAD

**Issue by dtfoster** [dmlc/xgboost#665]
The documentation describe Gain as being given by the following formula

![](http://i.stack.imgur.com/kBsh8.png)

However, using this definition, the Quality column in the xgb.model.dt.tree is incorrect (see http://stackoverflow.com/questions/33654479/how-is-xgboost-quality-calculated/34042413#34042413)

The issue seems to be in three places

1. The value for reg_lambda is not 0 by default as given in the documentation, but is actually 1
2. The factor of a half is not applied when calculating the gain, so Quality is double what you would expect
3. Gamma is used to determine whether to invoke pruning, but is not involved in the Gain calculation itself, as the formula suggests.

I think that either the documentation needs to be changed to match the code or vice versa - not sure which is the correct way to go.

Cheers,

David

**Comment by pommedeterresautee** [comment]
Here default value seems to be 0.5 https://github.com/dmlc/xgboost/issues/364

**Comment by pommedeterresautee** [comment]
@tqchen is there something special I need to change in `xgb.model.dt.tree`? (I am just taking numbers from the model dump).

**Comment by dtfoster** [comment]
It's the model dump that this issue refers to, rather than xgb.model.dt.tree.

**Comment by pommedeterresautee** [comment]
@dtfoster I agree but may be I can do the missing computation in dt.tree

**Comment by tqchen** [comment]
I think the gain calculation can be relected to this, however, since this is a relative measure, it is also fine in current state as a relative measure.
