### ISSUE TITLE
Dask arrays without distributed?

### ISSUE THREAD

**Issue by Hoeze** [dmlc/xgboost#6652]
Hi, I'd like to run the XGBRegressor with dask arrays (from xarray zarr dataset) on a Ray cluster.
However, when running:
```python
model = xgboost.XGBRegressor()
model.fit(x_train.data, y_train.data)
```
I just get this error message:
`TypeError: Not supported type for data.<class 'dask.array.core.Array'>`

Is there a simple way to achieve this?
- I am using `dask.config.set(scheduler=ray_dask_get)` as scheduler for dask.
- I want to avoid setting up a dask.distributed cluster 
- I want to avoid loading the whole dataset into memory

**Comment by hcho3** [comment]
No, currently we do not support training with a Dask array unless you set up a `distributed` cluster.

**Comment by trivialfis** [comment]
You will have to load the dataset into memory if using xgboost.

**Comment by Hoeze** [comment]
Thanks for your answers and making this a feature request :)

**Comment by trivialfis** [comment]
We can probably integrate it with the internal `IterativeDMatrix` .
