### ISSUE TITLE
Exception handling in OpenMP regions

### ISSUE THREAD

**Issue by ldesreumaux** [dmlc/xgboost#6664]
According to the OpenMP specification:
    
> A throw executed inside a parallel region must cause execution to resume within the same parallel region, and the same thread that threw the exception must catch it.

Any exception that reaches the end of a parallel region uncaught will cause the program to abort.

LightGBM uses [exception collectors](https://github.com/microsoft/LightGBM/blob/0c71be74b14cd616ee588fe789e89d85bd8aa7d9/include/LightGBM/utils/openmp_wrapper.h#L27) to capture the exceptions and rethrow them outside the parallel regions, in the main thread. They seem to be used in all the parallel regions that allocate memory to prevent crashes due to uncaught bad_alloc exceptions.

In DMLC, there is also an [exception collector](https://github.com/dmlc/dmlc-core/blob/21cc7de0dc9fd6acb796e1be6181fa8e6b6c8f41/include/dmlc/common.h#L53) class, but it does not seem to be used in XGBoost to handle bad_alloc exceptions in OpenMP regions.

It would be great if XGBoost could handle these exceptions in the same way as LightGBM.

I can try to submit a contribution regarding this issue if you agree on the need for it.

**Comment by trivialfis** [comment]
Thanks for the suggestions.  We covered some of the regions but still many are left.  Feel free to open a PR and ping me for review.  ;-)

**Comment by trivialfis** [comment]
There are some utility functions in `common/threading_utils.h` if that helps.
