### ISSUE TITLE
Sparse Dataset with Int32 DType leads to implicit XGBoost Transformation?

### ISSUE THREAD

**Issue by tdboyle-mm** [dmlc/xgboost#6671]
I think that there is a bug occurring within the training of an XGBoost model when the dataset used is Sparse and has Int32 data types. I have created a reproducible example of a one feature simple model and it is clear to see that some sort of transformation is being applied (possible when Int32 is being converted internally to Float32). All leaf values and predictions are identical but the split is significantly different. 

This might not be an issue in a single instance, but our workflow requires saving binary versions of both our model and DMatrix to be used in other applications (R, Python, Java). This creates issues if a model/DMatrix is used with a dataset that wasn't explictly cast to the same data types. I wanted to raise this issue to determine whether or not this is a bug or a feature. I've attached versioning information and a reproducible code sample.

```
import xgboost
import numpy as np
import pandas as pd
import scipy
from scipy.stats import truncnorm

n,p = 3, 0.00025
target = pd.DataFrame({'target': np.random.binomial(n, p, 99750)})

def get_truncated_normal(mean=0, sd=1, low=0, upp=10): ### UDF to help create 
    return truncnorm(
        (low - mean) / sd, (upp - mean) / sd, loc=mean, scale=sd)
  
X0 = get_truncated_normal(mean=1.294, sd=.35, low=1, upp=2.5)
target_append = pd.DataFrame({'target': X0.rvs(250)})

target_final = target.append(target_append)
  
X1 = get_truncated_normal(mean=14, sd=3, low=7, upp=18)

RVS = np.rint(X1.rvs(100000))

feature1_float32 = pd.DataFrame({'feature1': np.float32(RVS)})
feature1_int32 = pd.DataFrame({'feature1': np.int32(RVS)})
feature1_int64 = pd.DataFrame({'feature1': np.int64(RVS)})
feature1_sparse_float32 = scipy.sparse.csr_matrix(feature1_float32)
feature1_sparse_int32 = scipy.sparse.csr_matrix(feature1_int32)
feature1_sparse_int64 = scipy.sparse.csr_matrix(feature1_int64)

DMat_Dense_Float32 = xgboost.DMatrix(feature1_float32, label = target_final)
DMat_Sparse_Float32 = xgboost.DMatrix(feature1_sparse_float32, label = target_final)

DMat_Dense_Int32 = xgboost.DMatrix(feature1_int32, label = target_final)
DMat_Sparse_Int32 = xgboost.DMatrix(feature1_sparse_int32, label = target_final)

DMat_Dense_Int64 = xgboost.DMatrix(feature1_int64, label = target_final)
DMat_Sparse_Int64 = xgboost.DMatrix(feature1_sparse_int64, label = target_final)

single_model_params = {    
            'max_depth' : 1,
            'booster' : 'gbtree',
            'objective' : 'count:poisson',
            'reg_alpha' : 0,
            'subsample' : 1,
            'min_child_weight' : 1,
            'colsample_bytree' : 1,
            'colsample_bylevel' : 1,
            'colsample_bynode' : 1,
            'reg_lambda' : 0,
            'max_delta_step' : 0.7,
            'sampling_method' : 'uniform',
            'gamma' : 0,
            'eta' : 1,
            'tree_method': 'hist',
            'seed' : 10
         }

model_int32_dense = xgboost.train(params = single_model_params, dtrain = DMat_Dense_Int32, num_boost_round = 1)
model_int32_sparse = xgboost.train(params = single_model_params, dtrain = DMat_Sparse_Int32, num_boost_round = 1)

model_int64_dense = xgboost.train(params = single_model_params, dtrain = DMat_Dense_Int64, num_boost_round = 1)
model_int64_sparse = xgboost.train(params = single_model_params, dtrain = DMat_Sparse_Int64, num_boost_round = 1)

model_float32_dense = xgboost.train(params = single_model_params, dtrain = DMat_Dense_Float32, num_boost_round = 1)
model_float32_sparse = xgboost.train(params = single_model_params, dtrain = DMat_Sparse_Float32, num_boost_round = 1)
  
pred_dense_int32 = model_int32_dense.predict(DMat_Dense_Int32)
pred_sparse_int32 = model_int32_sparse.predict(DMat_Sparse_Int32)

pred_dense_int64 = model_int64_dense.predict(DMat_Dense_Int64)
pred_sparse_int64 = model_int64_sparse.predict(DMat_Sparse_Int64)

pred_dense_float32 = model_float32_dense.predict(DMat_Dense_Float32)
pred_sparse_float32 = model_float32_sparse.predict(DMat_Sparse_Float32)

print("Int32 Diff: ", sum(abs(pred_dense_int32-pred_sparse_int32)))
print("Int64 Diff: ", sum(abs(pred_dense_int64-pred_sparse_int64)))
print("Float32 Diff: ", sum(abs(pred_dense_float32-pred_sparse_float32)))

pred_test = model_int32_sparse.predict(DMat_Sparse_Int64)
print("Int64 vs Int32 Diff: ", sum(abs(pred_test-pred_sparse_int64)))

print("Int32 Dense Model: ", model_int32_dense.get_dump())
print("Int32 Sparse Model: ", model_int32_sparse.get_dump())

print("Int64 Dense Model: ", model_int64_dense.get_dump())
print("Int64 Sparse Model: ", model_int64_sparse.get_dump())

print("Float32 Dense Model: ", model_float32_dense.get_dump())
print("Float32 Sparse Model: ", model_float32_sparse.get_dump())
```

OUTPUT:
```
Int32 Diff:  0.0
Int64 Diff:  0.0
Float32 Diff:  0.0
Int64 vs Int32 Diff:  28.10639262199402
Int32 Dense Model:  ['0:[feature1<17] yes=1,no=2,missing=2\n\t1:leaf=-0.49197951\n\t2:leaf=-0.493029118\n']
Int32 Sparse Model:  ['0:[f0<2.38220739e-44] yes=1,no=2,missing=2\n\t1:leaf=-0.49197951\n\t2:leaf=-0.493029118\n']
Int64 Dense Model:  ['0:[feature1<17] yes=1,no=2,missing=2\n\t1:leaf=-0.49197951\n\t2:leaf=-0.493029118\n']
Int64 Sparse Model:  ['0:[f0<17] yes=1,no=2,missing=2\n\t1:leaf=-0.49197951\n\t2:leaf=-0.493029118\n']
Float32 Dense Model:  ['0:[feature1<17] yes=1,no=2,missing=2\n\t1:leaf=-0.49197951\n\t2:leaf=-0.493029118\n']
Float32 Sparse Model:  ['0:[f0<17] yes=1,no=2,missing=2\n\t1:leaf=-0.49197951\n\t2:leaf=-0.493029118\n']
```
As you can see, the splitting value of the Int32 Dense Model is different than the Int32 Sparse Model. Similarly, if we use a model that was trained using Int32 data and predict it with a DMatrix contained Int64 data, the predictions will be different.

Versioning:

name: databricks-ml
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - absl-py=0.9.0=py37_0
  - asn1crypto=1.3.0=py37_1
  - astor=0.8.0=py37_0
  - backcall=0.1.0=py37_0
  - backports=1.0=pyhd3eb1b0_2
  - bcrypt=3.2.0=py37h7b6447c_0
  - blas=1.0=mkl
  - blinker=1.4=py37_0
  - boto3=1.12.0=py_0
  - botocore=1.15.0=py_0
  - c-ares=1.17.1=h27cfd23_0
  - ca-certificates=2020.10.14=0
  - cachetools=4.1.1=py_0
  - certifi=2020.11.8=py37h06a4308_0
  - cffi=1.14.0=py37h2e261b9_0
  - chardet=3.0.4=py37h06a4308_1003
  - click=7.0=py37_0
  - cloudpickle=1.4.1=py_0
  - configparser=3.7.4=py37_0
  - cpuonly=1.0=0
  - cryptography=2.8=py37h1ba5d50_0
  - cycler=0.10.0=py37_0
  - cython=0.29.15=py37he6710b0_0
  - decorator=4.4.1=py_0
  - dill=0.3.1.1=py37_1
  - docutils=0.15.2=py37_0
  - entrypoints=0.3=py37_0
  - flask=1.1.1=py_1
  - freetype=2.9.1=h8a8886c_1
  - future=0.18.2=py37_1
  - gast=0.3.3=py_0
  - gitdb=4.0.5=py_0
  - gitpython=3.1.0=py_0
  - google-auth=1.11.2=py_0
  - google-auth-oauthlib=0.4.1=py_2
  - google-pasta=0.2.0=py_0
  - grpcio=1.27.2=py37hf8bcb03_0
  - gunicorn=20.0.4=py37_0
  - h5py=2.10.0=py37h7918eee_0
  - hdf5=1.10.4=hb1b8bf9_0
  - icu=58.2=he6710b0_3
  - idna=2.8=py37_0
  - intel-openmp=2020.0=166
  - ipykernel=5.1.4=py37h39e3cac_0
  - ipython=7.12.0=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - isodate=0.6.0=py_1
  - itsdangerous=1.1.0=py37_0
  - jedi=0.17.2=py37_0
  - jinja2=2.11.1=py_0
  - jmespath=0.10.0=py_0
  - joblib=0.14.1=py_0
  - jpeg=9b=h024ee3a_2
  - jupyter_client=5.3.4=py37_0
  - jupyter_core=4.6.1=py37_0
  - kiwisolver=1.1.0=py37he6710b0_0
  - krb5=1.16.4=h173b8e3_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hf484d3e_1007
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libpq=11.2=h20c2e04_0
  - libprotobuf=3.11.4=hd408876_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - libuv=1.40.0=h7b6447c_0
  - lightgbm=2.3.0=py37he6710b0_0
  - lz4-c=1.8.1.2=h14c3975_0
  - mako=1.1.2=py_0
  - markdown=3.1.1=py37_0
  - markupsafe=1.1.1=py37h14c3975_1
  - matplotlib-base=3.1.3=py37hef1b27d_0
  - mkl=2020.0=166
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.15=py37ha843d7b_0
  - mkl_random=1.1.0=py37hd6b4f25_0
  - ncurses=6.2=he6710b0_1
  - networkx=2.4=py_1
  - ninja=1.10.2=py37hff7bd54_0
  - nltk=3.4.5=py37_0
  - numpy=1.18.1=py37h4f9e942_0
  - numpy-base=1.18.1=py37hde5b4d6_1
  - oauthlib=3.1.0=py_0
  - olefile=0.46=py37_0
  - openssl=1.1.1h=h7b6447c_0
  - packaging=20.1=py_0
  - pandas=1.0.1=py37h0573a6f_0
  - paramiko=2.7.1=py_0
  - parso=0.7.0=py_0
  - patsy=0.5.1=py37_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=py37_1001
  - pillow=7.0.0=py37hb39fc2d_0
  - pip=20.0.2=py37_3
  - plotly=4.12.0=pyhd3eb1b0_0
  - prompt_toolkit=3.0.3=py_0
  - protobuf=3.11.4=py37he6710b0_0
  - psutil=5.6.7=py37h7b6447c_0
  - psycopg2=2.8.4=py37h1ba5d50_0
  - ptyprocess=0.6.0=pyhd3eb1b0_2
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.19=py37_0
  - pygments=2.5.2=py_0
  - pyjwt=1.7.1=py37_0
  - pynacl=1.3.0=py37h7b6447c_0
  - pyodbc=4.0.30=py37he6710b0_0
  - pyopenssl=19.1.0=pyhd3eb1b0_1
  - pyparsing=2.4.6=py_0
  - pysocks=1.7.1=py37_1
  - python=3.7.6=h0371630_2
  - python-dateutil=2.8.1=py_0
  - python-editor=1.0.4=py_0
  - pytorch=1.7.0=py3.7_cpu_0
  - pytz=2019.3=py_0
  - pyzmq=18.1.1=py37he6710b0_0
  - readline=7.0=h7b6447c_5
  - requests=2.22.0=py37_1
  - requests-oauthlib=1.3.0=py_0
  - retrying=1.3.3=py37_2
  - rsa=4.0=py_0
  - s3transfer=0.3.3=py37_1
  - scikit-learn=0.22.1=py37hd81dba3_0
  - scipy=1.4.1=py37h0b6359f_0
  - setuptools=45.2.0=py37_0
  - simplejson=3.17.0=py37h7b6447c_0
  - six=1.14.0=py37h06a4308_0
  - smmap=3.0.4=py_0
  - sqlite=3.31.1=h62c20be_1
  - sqlparse=0.4.1=py_0
  - statsmodels=0.11.0=py37h7b6447c_0
  - tabulate=0.8.3=py37_0
  - tk=8.6.8=hbc83047_0
  - torchvision=0.8.1=py37_cpu
  - tornado=6.0.3=py37h7b6447c_3
  - tqdm=4.42.1=py_0
  - traitlets=4.3.3=py37_0
  - typing_extensions=3.7.4.3=py_0
  - unixodbc=2.3.7=h14c3975_0
  - urllib3=1.25.8=py37_0
  - wcwidth=0.1.8=py_0
  - websocket-client=0.56.0=py37_0
  - werkzeug=1.0.0=py_0
  - wheel=0.34.2=py37_0
  - wrapt=1.11.2=py37h7b6447c_0
  - xz=5.2.4=h14c3975_4
  - zeromq=4.3.1=he6710b0_3
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - astunparse==1.6.3
    - azure-core==1.9.0
    - azure-storage-blob==12.6.0
    - databricks-cli==0.14.0
    - diskcache==5.1.0
    - docker==4.4.0
    - gorilla==0.3.0
    - horovod==0.20.3
    - joblibspark==0.3.0
    - keras-preprocessing==1.1.2
    - koalas==1.4.0
    - mleap==0.16.1
    - mlflow==1.12.1
    - msrest==0.6.19
    - opt-einsum==3.3.0
    - petastorm==0.9.7
    - pyarrow==1.0.1
    - pyyaml==5.3.1
    - querystring-parser==1.2.4
    - seaborn==0.10.0
    - spark-tensorflow-distributor==0.1.0
    - tensorboard==2.3.0
    - tensorboard-plugin-wit==1.7.0
    - tensorflow-cpu==2.3.1
    - tensorflow-estimator==2.3.0
    - termcolor==1.1.0
    - xgboost==1.2.1
prefix: /databricks/conda/envs/databricks-ml`

**Comment by trivialfis** [comment]
There's an issue with numpy dtype.  When the type is `int32`, numpy returns a pointer to float instead of copying it to a integer memory buffer.
