### ISSUE TITLE
[ci] Docker Hub Rate

### ISSUE THREAD

**Issue by trivialfis** [dmlc/xgboost#6673]
Quoting from https://www.docker.com/increase-rate-limits?utm_source=docker&utm_medium=web%20referral&utm_campaign=increase%20rate%20limit&utm_budget=  :

> On November 20, 2020, rate limits anonymous and free authenticated use of Docker Hub went into effect. Anonymous and Free Docker Hub users are limited to 100 and 200 container image pull requests per six hours. 

We hit the limit on master branch: https://xgboost-ci.net/blue/organizations/jenkins/xgboost/detail/master/734/pipeline .   I'm not sure how many pulls per-run on our CI, opening the issue for further investigation.

**Comment by hcho3** [comment]
Our Jenkins CI server internally caches the containers, so we only have to pull the base container infrequently.

**Comment by trivialfis** [comment]
Closing as we won't have that kind of traffic for some time.
