### ISSUE TITLE
[XGBoost-CI] Test JVM on OS windows&ubuntu failing in github but passing in Centos 7

### ISSUE THREAD

**Issue by merleyc** [dmlc/xgboost#6674]
I sent a [PR#6666](https://github.com/dmlc/xgboost/pull/6666) but I have 2 tests passing in my machine but failing in the PR.
The tests use the same command line.
Tests:
_XGBoost-CI / Test JVM on OS windows-latest (pull_request) Failing after 6m — Test JVM on OS windows-latest_
_XGBoost-CI / Test JVM on OS ubuntu-latest (pull_request) Failing after 2m — Test JVM on OS ubuntu-latest_

Command line:
_cd jvm-packages;   mvn test -B -pl :xgboost4j_2.12_

Please see the screenshot where this test passes in my Centos 7:
![image](https://user-images.githubusercontent.com/10016650/106847858-9fe0ba80-6664-11eb-928a-6e83591449e3.png)

Why do these tests are failing in github but passing my machine?
Thanks!

**Comment by trivialfis** [comment]
> Why do these tests are failing in github but passing my machine?

I don't know, happens from time to time with different reasons, dependency, floating point errors etc.  Feel free to ping me on your PR, I will reply in there.  Thanks for the optimization!

Let's make the Jenkins tests pass first: https://xgboost-ci.net/blue/organizations/jenkins/xgboost/detail/PR-6666/1/pipeline
