### ISSUE TITLE
xgboost.dll: doesn't exist or not a regular file

### ISSUE THREAD

**Issue by talhaanwarch** [dmlc/xgboost#6684]
I am trying to install xgboost on windows machine using following command. Every thing work well until the last step where I got the error. 
`error: can't copy 'build\temp.win-amd64-3.7\Release\xgboost\lib\xgboost.dll': doesn't exist or not a regular file`
because there is not any file `xgboost.dll` exist in the directory. 
```
git clone --recursive https://github.com/dmlc/xgboost
cd xgboost
git submodule init
git submodule update
mkdir build
cd build
cmake .. -G"Visual Studio 16 2019" -T v140,cuda=10.1 -DUSE_CUDA=ON
cmake --build . --target xgboost --config Release
cd ../python-package/
python setup.py install --use-cuda
```
I tried to even set `include_package_data=False` but still, I got the same error

**Comment by trivialfis** [comment]
Can you confirm your cmake build was successful?  Also check the file in xgboost source directory:  `xgboost/lib/xgboost.dll`.  I just tried it on Windows 10, it works fine.

> python setup.py install --use-cuda

`--use-cuda` flag was not necessary as you have already built the shared library using cmake before running install.  But it should have nothing to do with the error you saw.

**Comment by talhaanwarch** [comment]
There is not any folder `lib` in `xgboost`. Yes, cmake was successful.

**Comment by talhaanwarch** [comment]
This is the log of `cmake .. -G"Visual Studio 16 2019" -T v140,cuda=10.1 -DUSE_CUDA=ON`. In case it might help
```
(base) C:\Users\TAC\xgboost\build>cmake .. -G"Visual Studio 16 2019" -T v140,cuda=10.1 -DUSE_CUDA=ON
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
-- The CXX compiler identification is MSVC 19.0.24245.0
-- The C compiler identification is MSVC 19.0.24245.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- CMake version 3.19.4
-- Performing Test XGBOOST_MM_PREFETCH_PRESENT
-- Performing Test XGBOOST_MM_PREFETCH_PRESENT - Success
-- Performing Test XGBOOST_BUILTIN_PREFETCH_PRESENT
-- Performing Test XGBOOST_BUILTIN_PREFETCH_PRESENT - Failed
-- xgboost VERSION: 1.4.0
-- Configured CUDA host compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe
-- The CUDA compiler identification is NVIDIA 10.1.243
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/bin/nvcc.exe - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- CMAKE_CUDA_ARCHITECTURES: 75-real;75-virtual;70-real;70-virtual;61-real;61-virtual;60-real;60-virtual;52-real;52-virtual;50-real;50-virtual;35-real;35-virtual;
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Found OpenMP_C: -openmp (found version "2.0")
-- Found OpenMP_CXX: -openmp (found version "2.0")
-- Found OpenMP: TRUE (found version "2.0")
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - not found
-- Looking for fopen64
-- Looking for fopen64 - not found
-- Looking for C++ include cxxabi.h
-- Looking for C++ include cxxabi.h - not found
-- Looking for nanosleep
-- Looking for nanosleep - not found
-- Looking for backtrace
-- Looking for backtrace - not found
-- Could NOT find Backtrace (missing: Backtrace_LIBRARY Backtrace_INCLUDE_DIR)
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Searching 16 bit integer - Using unsigned short
-- Check if the system is big endian - little endian
-- C:/Users/TAC/xgboost/dmlc-core/cmake/build_config.h.in -> include/dmlc/build_config.h
-- Found PythonInterp: C:/Anaconda3/python.exe (found version "3.7.9")
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/TAC/xgboost/build
```

**Comment by talhaanwarch** [comment]
and when i try to run
`cmake --build . --target xgboost --config Release -- /MP.` it give following error
```
MSBUILD : error MSB1001: Unknown switch.
Switch: /MP.

For switch syntax, type "MSBuild -help"
```
Thats why I it like this `cmake --build . --target xgboost --config Release`. just adding this , in case it help

**Comment by trivialfis** [comment]
Can you try removing the `--target xgboost`:

```
cmake --build ./ --config Release
```

**Comment by talhaanwarch** [comment]
> Can you try removing the `--target xgboost`:
> 
> ```
> cmake --build ./ --config Release
> ```

it will take couple of hours, because I am unable to append `-- /MP.`. I will update once it finished

**Comment by trivialfis** [comment]
Couple of hours for compiling?  Have your tried this:

```
cmake --build ./ --config Release --parallel 16
```
Replace 16 with the number of cores your device has.

**Comment by talhaanwarch** [comment]
I did as you suggested but `xgboost/python-package/build/temp.win-amd64-3.7/Release/` is empty

**Comment by trivialfis** [comment]
Could you please check the file in xgboost source directory: xgboost/lib/xgboost.dll ?  Please notice that it's the source directory not build directory.

**Comment by talhaanwarch** [comment]
as already told there is no lib folder, please check list of folders in the image attached
![image](https://user-images.githubusercontent.com/37379131/107183925-74adf080-6a01-11eb-85d1-3998d84c733f.png)

**Comment by trivialfis** [comment]
@talhaanwarch How about the executable xgboost/xgboost.exe ?

**Comment by talhaanwarch** [comment]
No, there is not any such file `xgboost.exe` in the entire folder

**Comment by trivialfis** [comment]
Em, then I don't know what's happening.  My usual build command for Windows looks like this:

```
mkdir build
cd build
cmake .. -A x64 -DUSE_OPENMP=ON -DUSE_CUDA=ON
cmake --build ./ --config Release --parallel 12
```

I'm not sure what's the difference between our systems.

**Comment by hcho3** [comment]
We provide a pre-built binary wheel for Windows platform. You may install it by running
```
python -m pip install xgboost==1.3.3
```
You should be able to access the GPU functionality out of the box.
