### ISSUE TITLE
xgboost.loadModel lead to memory leak

### ISSUE THREAD

**Issue by ninesky110** [dmlc/xgboost#6691]
environment:
jdk:1.8
scala:2.11.11
play framework
--------------------------------
I want use a http request to reload the xgboost model, but the memory keeps increasing when I call the http request.

The requested method is as follows：

 ```
private def getModelMap(confPath: String): Map[String, Booster] = {
    if (!config.has(confPath)) {
      log.warn(s"${confPath} not found in config file, ignore loading xgboost model from file")
      return Map.empty
    }
    if (!config.get[Boolean](confPath + "." + "enabled")) {
      log.info(s"XGBoost is not enabled in config, ignore loading")
      return Map.empty
    }

    val basePath = config.get[String](confPath + "." + "base_path")
    val versionNameMap = getVersionFileNameMap(confPath)

        val modelMap = versionNameMap.flatMap {
          case (version, name) =>
            val modelPath = basePath + File.separator + version + File.separator + name
            try {
              val model = XGBoost.loadModel(modelPath)
              Some(version -> model)
            } catch {
              case NonFatal(e) =>
                log.error(s"Unable to load xgboost $modelPath, ${e.getMessage}", e)
                None
            }
        }

        if (modelMap.isEmpty) {
          throw new InternalErrorException("No valid xgboost model found, plz check your application.conf")
        }

        modelMap
  }
```

**Comment by trivialfis** [comment]
Could you please provide a reproducible example?  The script you provided is not running a loop or anything that can accumulate memory usage.  I tried using native xgboost to load a model 1000 times and no memory increase is found.  Also, we run sanitizer on our CI.

**Comment by ninesky110** [comment]
> Could you please provide a reproducible example? The script you provided is not running a loop or anything that can accumulate memory usage. I tried using native xgboost to load a model 1000 times and no memory increase is found. Also, we run sanitizer on our CI.

https://github.com/ninesky110/rankTestModel  I built a demo to test  load xgboost model and it can reload model through post request. I tested the memory changes  importing the model as shown below：
![image](https://user-images.githubusercontent.com/38121533/110466811-2b8cb180-8111-11eb-9fd4-f05245221190.png)
![image](https://user-images.githubusercontent.com/38121533/110466835-347d8300-8111-11eb-8e32-29e5e2231536.png)

**Comment by ninesky110** [comment]
> Could you please provide a reproducible example? The script you provided is not running a loop or anything that can accumulate memory usage. I tried using native xgboost to load a model 1000 times and no memory increase is found. Also, we run sanitizer on our CI.

Please help me solve this problem if it is convenient for you, best wishes to you

**Comment by trivialfis** [comment]
Could you please add a readme file and simplify it down to strictly model loading?  I don't know what to do looking at 300 lines of code.  cc @hcho3 @wbo4958

**Comment by wbo4958** [comment]
@ninesky110 which xgboost version did you test? I remember there was a xgboost native bug freeing the model handle before, which can cause mem-leak.

can you try the latest xgboost?

**Comment by trivialfis** [comment]
Closing as stalled.  Feel free to reopen if there's a reproducible example.
