### ISSUE TITLE
[FEA] Allow users to pass in feature names for monotonicity or interaction constraints.

### ISSUE THREAD

**Issue by stephenpardy** [dmlc/xgboost#6704]
Hi! I love the monotonicity and interaction constraints in XGBoost, but the current method of specifying them relies on long text strings of all the features. An example for monotone constraints:
`"(0,1,1,0,0,-1...)"` 
Not only can this get long if you have a lot of features, but often you want only a few features constrained with the rest zeros. Further, this method of passing in the constraints is not flexible if you are fitting many models with different feature subsets or features in different orders.

One awesome addition to make this easier would be to allow users pass in constraints as a dictionary:
`{"X1": 1, "X10" -1, ...}` where the keys are feature names and the values are the constraints (and features not present could be assigned the default of `0`). 

The caveat here is that the user must then pass in a dataset that has column names (either a DMatrix or DataFrame-like object).

A few lines of code during the `fit` and `train` methods would then convert this dictionary into the usual string list that is passed to the underlying tree builder using the column names in the data. If the user passes data that does not contain the features, an error could raised.

I am happy to provide some dummy code if it would help.

**Comment by trivialfis** [comment]
In my opinion, the constraints should be part of `DMatrix` like labels instead of string parameter.  But more suggestions are welcomed.

**Comment by stephenpardy** [comment]
Adding them to `DMatrix` would definitely take care of the use case here, as long as the arguments were also passed through the SKlearn interface (as is done with the `base_margin` and `weight` parameters). 

I do wonder if it makes sense though, I think of the monotonicity and interaction constraints as parameters of the _model_ not of the data.

**Comment by giladmaya** [comment]
I agree with @stephenpardy 

@trivialfis - Can I work on this feature?

**Comment by trivialfis** [comment]
Thanks for the offer.   Of course, feel free to ping me for questions and PR reviews.

**Comment by trivialfis** [comment]
@csetzkorn that error is not from xgboost.

**Comment by csetzkorn** [comment]
Thanks I also tried:

`{'max_depth': '10', 'num_round': '10', 'objective': 'count:poisson', 'tree_method': 'exact', 'seed': 42, 'eval_metric': 'rmse', 'updater': 'grow_monotone_colmaker', 'monotone_constraints': {'SomeColumn': -1}}`

Same error but as @trivialfis says most likely more a sagemaker issue:

```
sagemaker_algorithm_toolkit.exceptions.UserError: Hyperparameter monotone_constraints: value {'SomeColumn': -1} not in range [-1, 0, 1]
Hyperparameter monotone_constraints: value {'SomeColumn': -1} not in range [-1, 0, 1]
```
