### ISSUE TITLE
Python build: --use-system-libxgboost cannot find library

### ISSUE THREAD

**Issue by adamjstewart** [dmlc/xgboost#6706]
Hi, I'm a developer for the [Spack](https://spack.io) package manager. Unlike other package managers, Spack installs each package to a different directory, allowing users to install multiple versions of the same library. I'm working on overhauling our build recipes for `xgboost` and `py-xgboost` and noticed the following difficulties:

1. `python setup.py build` does not accept the `--use-system-libxgboost` flag, even though the build phase is where we decide whether or not to build the C++ library
2. `setup.py` cannot find `libxgboost.(so|dylib)` at build-time, as it is in a custom location
3. `xgboost/libpath.py` cannot find `libxgboost.(so|dylib)` at run-time, as it is in a custom location

I can get around issue 1 by only running `python setup.py install`, but all other Python packages in Spack have a 2-phase installation process with `python setup.py build && python setup.py install`. I can get around issues 2 and 3 by patching the source code to tell it where the library is found, but this is fragile if the code changes from version to version. I can get around all 3 issues by building the entire xgboost library when I build the Python bindings, but that leads to a lot of code duplication between the two Spack packages.

Some suggestions for how this could be fixed:

3. Add a `--use-system-libxgboost` flag to the `build` phase. This should be fairly easy and non-controversial.
4. Change the `--use-system-libxgboost` flag to optionally accept a path at which the library can be found
5. Store the path passed to `--use-system-libxgboost` at build-time and write it to `xgboost/libpath.py` so it can be found at run-time

There are also a couple of alternatives we could use:

6. Search `LIBRARY_PATH` at build-time and `(DY)?LD_LIBRARY_PATH` at run-time like other C/C++ libraries do
7. Allow users to pass in a directory in `setup.cfg` or `site.cfg`. This is how NumPy handles non-Python dependencies like BLAS/LAPACK.

I've numbered each issue and suggestion separately so it will be easier to comment on them.

**Comment by trivialfis** [comment]
Thanks for the detailed description and solutions.  I'm open to sol 3, 4, 5.  Would you like to open a PR?

**Comment by adamjstewart** [comment]
I'll see what I can do!

**Comment by trivialfis** [comment]
That certainty looks like an interesting new package manager.  I have been using nix and conda and some others.  I should try Spack too.

**Comment by adamjstewart** [comment]
Yes, Spack has the CLI of Homebew/Conda and the functional hashing nature of nix. If you're interested, I can add you as a maintainer for our `xgboost`, `py-xgboost`, and `r-xgboost` packages. You don't have to be a Spack expert, it just gives us someone to ping when a user reports build issues or wants to modify the recipe. I'll also be a maintainer, so I can handle Spack-specific questions.

**Comment by trivialfis** [comment]
Thanks for the offer!  I'm currently on vacation and just checking emails occasionally.  Will try it later.

**Comment by adamjstewart** [comment]
P.S. Is there a way to build the R library with an external xgboost lib, similar to Python?

**Comment by trivialfis** [comment]
Sadly no.  The R package is tailored to CRAN policy.

**Comment by trivialfis** [comment]
@adamjstewart Hi sorry for the late reply.  I'm trying out spack.  Out of curiosity, for dynamic languages like Python (and any others) that lack of the ability for encoding module paths, is there a general solution for package managers instead of patching libraries one by one?

**Comment by trivialfis** [comment]
If not, is there a general pattern that package developers should use?

**Comment by adamjstewart** [comment]
For dynamic languages like Python, it's kind of a nightmare. Spack makes heavy use of RPATH because it allows users to install multiple versions of the same library, and you don't want to have the wrong version of a dependency in your `LD_LIBRARY_PATH` because it can break ABI compatibility. Since Python does not support RPATH, we have [a few hacks in place](https://github.com/spack/spack/pull/21149) to make it more reliable.

From a packaging standpoint, it's pretty hit or miss. There are many packages like yours that I've seen that fail to find the correct library at run-time without something like `LD_LIBRARY_PATH` being set. The packages that do things "right" (in my opinion) are packages like Numpy (and packages that depend on numpy and ask it where to find BLAS/LAPACK). Numpy allows users to explicitly specify the location of libraries in a `site.cfg` file (see [here](https://github.com/numpy/numpy/blob/main/site.cfg.example) for an example). This file is then installed along with the rest of the library so that it can be queried at run-time. This is nice because it doesn't involve hacking any of the source code.

**Comment by trivialfis** [comment]
Closing in favor of https://github.com/dmlc/xgboost/issues/9376 .
