### ISSUE TITLE
XGBoost can't find the right split with nthread = 3

### ISSUE THREAD

**Issue by fsimond** [dmlc/xgboost#671]
Hi,

I've made a very simple problem where xgboost seems not able to find the right split when nthread = 3

You can find the code here:
https://www.kaggle.com/fsimond/springleaf-marketing-response/digging-into-springleaf-data

When I run the code locally (with xgboost 0.4-2 (latest version on CRAN)), I don't get the same results as in Kaggle. (You can see the result I obtain here: https://www.kaggle.com/forums/f/15/kaggle-forum/t/17704/bug-in-xgboost/100387)

The split is always made between 0 and 1, and therefore there is no distinction between 1 and 2 ....

Thanks for your help and for your work,
Florian

**Comment by tqchen** [comment]
Thanks for reporting this, I am traveling and will look into this. @hetong007 @terrytangyuan can you check if you can reproduce the problem as well?

**Comment by hetong007** [comment]
@fsimond Can you please try to install the latest version from github, and see if the problem still exists? On my windows local machine, I cannot see any difference between `nthread=1` and `nthread=3`.

To install from github, please refer to the instruction here: https://github.com/dmlc/xgboost/tree/master/R-package

**Comment by terrytangyuan** [comment]
I will check later on my Mac too. Travelling as well.

**Comment by terrytangyuan** [comment]
@fsimond I got the same result as in https://www.kaggle.com/fsimond/springleaf-marketing-response/digging-into-springleaf-data/notebook and setting different nthreads does not give me different results. Let us know if you still encounter the same issue after getting the most recent version from Github. Thanks.

**Comment by fsimond** [comment]
@hetong007 @terrytangyuan
Ok so I tried on another machine (Linux this time). Same problem with the latest version on CRAN.
I installed the latest version from github and... it works :)
I guess the latest version on CRAN has a (serious?) bug in it...

**Comment by terrytangyuan** [comment]
@fsimond I am glad it is working again. Yeah there might be a bug that's fixed in dev version. Most people actually just install xgboost from Github instead of CRAN.
