### ISSUE TITLE
{ n_estimators } might not be used.

### ISSUE THREAD

**Issue by anks7190** [dmlc/xgboost#6710]
Hi , I am getting { n_estimators } might not be used warning while training data.
And the Xgboost is traianing only 10 rounds the default number. 
How can I increase the number of trees .
Thanks

**Comment by trivialfis** [comment]
Please check out the document from `train` function.

**Comment by anks7190** [comment]
I tried adding num_boost_round also . 
Now getting this  -> "parameters: { num_boost_round } might not be used.

**Comment by anks7190** [comment]
Okay , silly mistake . I was passing the num_boosr_rounds in params . It should be passed separately.
