### ISSUE TITLE
[jvm-packages] The reproducibility of distributed training and consistency with Python version

### ISSUE THREAD

**Issue by dspetukhov** [dmlc/xgboost#6715]
Hello!

Recently I started to use XGBoost4J-Spark 1.1.2 compiled with Scala 2.11.12 and I faced a number of problems which should be addressed I guess.

The main question I have is related to the reproducibility of results when training with more than one worker.
As far as I understood, training with one worker ("num_workers" -> 1) allows to get reproducible results every time the fit method is started, which coincide absolutely exactly with Python version.
When training on two workers, the results are reproducible, but they are noticeably worse than training on one worker, and this is a fundamentally important note for Kaggle-like tasks.
When training on three or more workers, the training speed increases significantly, but the results are absolutely not reproducible, moreover, they can be either better or significantly worse than the training results on one worker.
Setting the seed, using repartition to the number of workers or setting needDeterministicRepartitioning to true does not help to ensure reproducibility of results.

So the question is: is there any possibility to ensure consistency with Python library and provide fast training process (utilizing Spark features without setting useExternalMemory to true, and numWorker to 1)?  

Also, I have another question. Is there any possibility to track the training process similar to the Python version? I did not find such possibility and examples.

**Comment by hcho3** [comment]
It's difficult, since XGBoost does not have control over how the data gets partitioned among multiple workers. Spark handles the partitioning.

**Comment by dspetukhov** [comment]
Ok, thanks for the answer.
So if Spark partitioning is not deterministic, then xgboost4j output will always be different?
I have found in some sources (like [https://www.dezyre.com/article/how-data-partitioning-in-spark-helps-achieve-more-parallelism/297](https://www.dezyre.com/article/how-data-partitioning-in-spark-helps-achieve-more-parallelism/297)) that Spark utilizes different approaches to partitioning. Looks like it might solve the problem with determinism.

**Comment by hcho3** [comment]
I'm not an expert on Spark, so I have no idea.
