### ISSUE TITLE
Does monotone_constraints work with num_parallel_tree ?

### ISSUE THREAD

**Issue by flippercy** [dmlc/xgboost#6716]
I am building a random forest via xgboost using the method described at https://xgboost.readthedocs.io/en/latest/tutorials/rf.html . Does the monotone_constraints still work in this scenario (num_boost_round = 1 and num_parallel_tree = number of trees in the random forest)?

Thank you.

**Comment by hcho3** [comment]
Yes, the monotone constraint should work when num_parallel_tree is enabled.
