### ISSUE TITLE
Eval displays 'nan' with 'reg:gamma' objective and 'gbtree' booster

### ISSUE THREAD

**Issue by honzasterba** [dmlc/xgboost#6723]
seems to be related to #5349, but was not fixed by the fix

script to reproduce:

```python
import xgboost as xgb
dtrain = xgb.DMatrix("matrix.part0")
param = {
    'booster': "gbtree",
    'tree_method': "approx",
    'max_depth': 6, 
    "objective": "reg:gamma",
    "lambda": 1.0,
    'gamma': 0.0, 
    'nthread': 16
}
num_round = 50
bst = xgb.train(param, dtrain, num_round, [(dtrain, "train")])
```

script output:
```
[0]	train-gamma-nloglik:nan
[1]	train-gamma-nloglik:nan
[2]	train-gamma-nloglik:nan
[3]	train-gamma-nloglik:nan
[4]	train-gamma-nloglik:nan
[5]	train-gamma-nloglik:nan
[6]	train-gamma-nloglik:nan
[7]	train-gamma-nloglik:nan
[8]	train-gamma-nloglik:nan
[9]	train-gamma-nloglik:nan
...
```

data and script attached
[nan_metrics.zip](https://github.com/dmlc/xgboost/files/6028259/nan_metrics.zip)

tested with: 1.2.0 and 1.3.3, same result

**Comment by trivialfis** [comment]
I need to restore the estimation on dispersion.

**Comment by trivialfis** [comment]
For now please use gamma deviance instead, it should be a good metric as the objective is actually derived from it with log link.

**Comment by trivialfis** [comment]
Your data contains 0.  You need to do some per-processing to remove them.
