### ISSUE TITLE
xgboost4j dependency bloat

### ISSUE THREAD

**Issue by phraktle** [dmlc/xgboost#6724]
The complete dependency tree for xgboost4j is quite large and seems to include items such as `scalatest` and `scala-compiler` which presumably sould not be a runtime dependency (only used while building xgboost4j).

```
+--- ml.dmlc:xgboost4j_2.12:1.3.1
|    +--- com.typesafe.akka:akka-actor_2.12:2.5.23
|    |    +--- org.scala-lang:scala-library:2.12.8
|    |    +--- com.typesafe:config:1.3.3
|    |    \--- org.scala-lang.modules:scala-java8-compat_2.12:0.8.0
|    |         \--- org.scala-lang:scala-library:2.12.0 -> 2.12.8
|    +--- org.scalatest:scalatest_2.12:3.0.5
|    |    +--- org.scala-lang:scala-library:2.12.4 -> 2.12.8
|    |    +--- org.scalactic:scalactic_2.12:3.0.5
|    |    |    +--- org.scala-lang:scala-library:2.12.4 -> 2.12.8
|    |    |    \--- org.scala-lang:scala-reflect:2.12.4 -> 2.12.8
|    |    |         \--- org.scala-lang:scala-library:2.12.8
|    |    +--- org.scala-lang:scala-reflect:2.12.4 -> 2.12.8 (*)
|    |    \--- org.scala-lang.modules:scala-xml_2.12:1.0.6
|    |         \--- org.scala-lang:scala-library:2.12.0 -> 2.12.8
|    +--- com.esotericsoftware:kryo:4.0.2
|    |    +--- com.esotericsoftware:reflectasm:1.11.3
|    |    |    \--- org.ow2.asm:asm:5.0.4 -> 7.3.1
|    |    +--- com.esotericsoftware:minlog:1.3.0
|    |    \--- org.objenesis:objenesis:2.5.1
|    +--- org.scala-lang:scala-compiler:2.12.8
|    |    +--- org.scala-lang:scala-library:2.12.8
|    |    +--- org.scala-lang:scala-reflect:2.12.8 (*)
|    |    \--- org.scala-lang.modules:scala-xml_2.12:1.0.6 (*)
|    +--- org.scala-lang:scala-reflect:2.12.8 (*)
|    +--- org.scala-lang:scala-library:2.12.8
|    \--- commons-logging:commons-logging:1.2
```

**Comment by trivialfis** [comment]
Is there a way to split up build time dependencies and runtime dependencies?

**Comment by phraktle** [comment]
https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#dependency-scope

**Comment by trivialfis** [comment]
@phraktle Thanks for raising the issue and providing the reference, would you like to open a PR?

**Comment by phraktle** [comment]
I’m not familiar with the project enough to decide the correct scope of dependencies, but if you do know which ones are needed only for compilation/tests, the change itself should be trivial in the `pom.xml`.

**Comment by CodingCat** [comment]
thanks @phraktle , scalatest should be in test scope for sure, 

IIRC, removing org.scala-lang:scala-library, etc. might be a kind of breaking change, 

since we include scala library in xgb, any application built with xgb-scala can be triggered by `java -cp` as scala libs are in classpath, if we remove this, users are supposed to include those library in class path explicitly to make main function recognizable

but I personally think it is ok, feel free to open to PR

**Comment by phraktle** [comment]
I took a quick hack at it in a PR, but reviewing dependency scopes would be better performed by a maintainer (one who understands why various dependencies are there in the first place and is able to build the project locally – I can't claim either :).

**Comment by wbo4958** [comment]
Since the PR merged, better to close this issue. @trivialfis

**Comment by phraktle** [comment]
Was this ever released?

**Comment by hcho3** [comment]
We will release 1.5.0 to Maven Central shortly.

**Comment by hcho3** [comment]
@phraktle 1.5.0 is now available on Maven Central.
