### ISSUE TITLE
Sklearn Evaluation Metric compability

### ISSUE THREAD

**Issue by Arritmic** [dmlc/xgboost#6725]
Hello,
I am training several models using Sklearn classifiers and XGBoost. I need the last version of Sklearn because I am using other package which depends on that version. I would like to include XGBoost, but I am getting the next warning:
` 
 WARNING: /home/conda/feedstock_root/build_artifacts/xgboost_1607604574104/work/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.`

I am working in a conda environment with the next configuration:

>   active environment : DMP
>   active env location : /home/arritmic/anaconda3/envs/DMP
>   shell level : 1
>   user config file : /home/arritmic/.condarc
>   populated config files : /home/arritmic/.condarc
>   conda version : 4.9.2
>   conda-build version : 3.18.11
>   python version : 3.8.3.final.0
>   virtual packages : __cuda=11.2=0
>                           __glibc=2.31=0
>                           __unix=0=0
>                           __archspec=1=x86_64
>   base environment : /home/arritmic/anaconda3  (writable)
>   channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
>                           https://repo.anaconda.com/pkgs/main/noarch
>                           https://repo.anaconda.com/pkgs/r/linux-64
>                           https://repo.anaconda.com/pkgs/r/noarch
>   package cache : /home/arritmic/anaconda3/pkgs
>                             /home/arritmic/.conda/pkgs
>   envs directories : /home/arritmic/anaconda3/envs
>                              /home/arritmic/.conda/envs
>    platform : linux-64
>   user-agent : conda/4.9.2 requests/2.24.0 CPython/3.8.3 Linux/5.8.0-43-generic ubuntu/20.04.2 glibc/2.31

Some of the libraries installed and related to XGBoost:

> _libgcc_mutex                0.1                      conda_forge    conda-forge
> _openmp_mutex             4.5                       1_gnu    conda-forge
> _py-xgboost-mutex          2.0                      cpu_0    conda-forge
>   scikit-image                   0.17.2                 py36h284efc9_4    conda-forge
>   scikit-kinematics           0.8.5                    pypi_0    pypi
>   scikit-learn                    0.23.1                  pypi_0    pypi
>   scipy                             1.5.4                    pypi_0    pypi
>   xgboost                        1.1.1                     pypi_0    pypi

But when I have installed it, it shown this:
`
Requirement already satisfied: xgboost in /home/arritmic/anaconda3/envs/DMP/lib/python3.6/site-packages (1.3.0)
Requirement already satisfied: numpy in /home/arritmic/anaconda3/envs/DMP/lib/python3.6/site-packages (from xgboost) (1.19.5)
Requirement already satisfied: scipy in /home/arritmic/anaconda3/envs/DMP/lib/python3.6/site-packages (from xgboost) (1.5.4)
`

Thanks in advance.
A

**Comment by trivialfis** [comment]
Hi @Arritmic , it's just a warning for users updating xgboost.  You can safely ignore it or do either one of:
- specify the evaluation metric you want.
- provide `disable_default_eval_metric` as parameter.

**Comment by Arritmic** [comment]
Thannk you @trivialfis . I guessed it, and it is not disturbing finally my results, but I wanted to share it just in case it could be useful.
And thanks for the extra information which I would take into account.

:)

**Comment by GeorgePearse** [comment]
I'm trying to use cohen_kappa_score as the eval_metric but I'm receiving an error 
```
xgb_clf = xgb.XGBClassifier()

eval_set = [(train_sorted_embeddings, train_sorted_labels), (validation_sorted_embeddings, validation_sorted_labels)]
xgb_clf.fit(train_sorted_embeddings, train_sorted_labels, eval_set=eval_set, eval_metric=cohen_kappa_score)
```

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-138-e3584d322a6a> in <module>
      2 
      3 eval_set = [(train_sorted_embeddings, train_sorted_labels), (validation_sorted_embeddings, validation_sorted_labels)]
----> 4 xgb_clf.fit(train_sorted_embeddings, train_sorted_labels, eval_set=eval_set, eval_metric=cohen_kappa_score)

~/environments/behold-explain/lib/python3.6/site-packages/xgboost/core.py in inner_f(*args, **kwargs)
    504         for k, arg in zip(sig.parameters, args):
    505             kwargs[k] = arg
--> 506         return f(**kwargs)
    507 
    508     return inner_f

~/environments/behold-explain/lib/python3.6/site-packages/xgboost/sklearn.py in fit(self, X, y, sample_weight, base_margin, eval_set, eval_metric, early_stopping_rounds, verbose, xgb_model, sample_weight_eval_set, base_margin_eval_set, feature_weights, callbacks)
   1259             verbose_eval=verbose,
   1260             xgb_model=model,
-> 1261             callbacks=callbacks,
   1262         )
   1263 

~/environments/behold-explain/lib/python3.6/site-packages/xgboost/training.py in train(params, dtrain, num_boost_round, evals, obj, feval, maximize, early_stopping_rounds, evals_result, verbose_eval, xgb_model, callbacks)
    194                           evals_result=evals_result,
    195                           maximize=maximize,
--> 196                           early_stopping_rounds=early_stopping_rounds)
    197     return bst
    198 

~/environments/behold-explain/lib/python3.6/site-packages/xgboost/training.py in _train_internal(params, dtrain, num_boost_round, evals, obj, feval, xgb_model, callbacks, evals_result, maximize, verbose_eval, early_stopping_rounds)
     80             break
     81         bst.update(dtrain, i, obj)
---> 82         if callbacks.after_iteration(bst, i, dtrain, evals):
     83             break
     84 

~/environments/behold-explain/lib/python3.6/site-packages/xgboost/callback.py in after_iteration(self, model, epoch, dtrain, evals)
    432             for _, name in evals:
    433                 assert name.find('-') == -1, 'Dataset name should not contain `-`'
--> 434             score = model.eval_set(evals, epoch, self.metric)
    435             score = score.split()[1:]  # into datasets
    436             # split up `test-error:0.1234`

~/environments/behold-explain/lib/python3.6/site-packages/xgboost/core.py in eval_set(self, evals, iteration, feval)
   1751             for dmat, evname in evals:
   1752                 feval_ret = feval(self.predict(dmat, training=False,
-> 1753                                                output_margin=True), dmat)
   1754                 if isinstance(feval_ret, list):
   1755                     for name, val in feval_ret:

~/environments/behold-explain/lib/python3.6/site-packages/sklearn/utils/validation.py in inner_f(*args, **kwargs)
     61 
     62 
---> 63 def assert_all_finite(X, allow_nan=False):
     64     """Throw a ValueError if X contains NaN or infinity.
     65 

~/environments/behold-explain/lib/python3.6/site-packages/sklearn/metrics/_classification.py in cohen_kappa_score(y1, y2, labels, weights, sample_weight)

~/environments/behold-explain/lib/python3.6/site-packages/sklearn/utils/validation.py in inner_f(*args, **kwargs)
     61 
     62 
---> 63 def assert_all_finite(X, allow_nan=False):
     64     """Throw a ValueError if X contains NaN or infinity.
     65 

~/environments/behold-explain/lib/python3.6/site-packages/sklearn/metrics/_classification.py in confusion_matrix(y_true, y_pred, labels, sample_weight, normalize)

~/environments/behold-explain/lib/python3.6/site-packages/sklearn/metrics/_classification.py in _check_targets(y_true, y_pred)

~/environments/behold-explain/lib/python3.6/site-packages/sklearn/utils/validation.py in check_consistent_length(*arrays)
    314     if force_all_finite:
    315         if not hasattr(spmatrix, "data"):
--> 316             warnings.warn("Can't check %s sparse matrix for nan or inf."
    317                           % spmatrix.format)
    318         else:

~/environments/behold-explain/lib/python3.6/site-packages/sklearn/utils/validation.py in <listcomp>(.0)
    314     if force_all_finite:
    315         if not hasattr(spmatrix, "data"):
--> 316             warnings.warn("Can't check %s sparse matrix for nan or inf."
    317                           % spmatrix.format)
    318         else:

~/environments/behold-explain/lib/python3.6/site-packages/sklearn/utils/validation.py in _num_samples(x)
    253         Data type of result. If None, the dtype of the input is preserved.
    254 
--> 255     copy : boolean
    256         Whether a forced copy will be triggered. If copy=False, a copy might
    257         be triggered by a conversion.

TypeError: Expected sequence or array-like, got <class 'xgboost.core.DMatrix'>

**Comment by GeorgePearse** [comment]
^ Turned out that was actually well documented. eval_metric has moved from .fit to the initialization. 

```
xgb_clf = xgb.XGBClassifier(eval_metric=cohen_kappa_score)

eval_set = [(train_sorted_embeddings, train_sorted_labels), (validation_sorted_embeddings, validation_sorted_labels)]
xgb_clf.fit(train_sorted_embeddings, train_sorted_labels, eval_set=eval_set)
```

**Comment by trivialfis** [comment]
It was moved after 1.5 and is pending for 1.5.1 release, so I guess you are compiling from the master branch?

**Comment by trivialfis** [comment]
Moving the parameter was to have better compatibility with scikit-learn utilities.  Otherwise, grid search might split up the string "mlogloss" as input data ...
