### ISSUE TITLE
Building python version

### ISSUE THREAD

**Issue by modqhx** [dmlc/xgboost#673]
Hi, I have issues with building the python version. In my python subdirectory,
```
sudo python setup.py install

Traceback (most recent call last):
  File "setup.py", line 26, in <module>
    description=open(os.path.join(CURRENT_DIR, 'README.md')).read(),
IOError: [Errno 2] No such file or directory: 'README.md'
```
Is it suppose to be README.rst?

**Comment by terrytangyuan** [comment]
Yes, quick fix would be changing to rst. I'll make the change as well.

**Comment by modqhx** [comment]
Great! I was thinking about make a pull request. Thanks tho :)

**Comment by terrytangyuan** [comment]
Thanks! You are welcome to do it next time then. :-)

**Comment by modqhx** [comment]
Sure! :+1:

**Comment by phunterlau** [comment]
oops, my bad that I changed it to RST because of pip installation, and I forgot to change the original one. Thanks for fixing.
