### ISSUE TITLE
CRAN Version 1.3.2.1 too many libgomp events

### ISSUE THREAD

**Issue by meztez** [dmlc/xgboost#6732]
During one of your predictions app deployment we observed 3x performance regression on k8s pods that uses CPU/mem limits when using xgboost R CRAN version 1.3.2.1.

Using perf top we observed that was a lot of events generated by libgomp compared to the previous version when load testing the code.

1.3.2.1
```console
$ perf top -p 7425 -d 60 -a
PerfTop: 3716 irqs/sec kernel: 0.6% exact: 0.0% lost: 0/0 drop: 0/0 [4000Hz cpu-clock:pppH], (target_pid: 7425)
------------------------------------------------------------------------------------------------------------------------------------------------------------
14.99% libgomp.so.1.0.0 [.] 0x000000000001d122
 3.65% libR.so [.] 0x0000000000223685
 3.49% libR.so [.] 0x0000000000224901
 2.06% libR.so [.] 0x0000000000191a13
 1.50% libR.so [.] 0x000000000018f6ec
```

1.2.0.1
```console
PerfTop: 0 irqs/sec kernel: 0.0% exact: 0.0% lost: 0/0 drop: 0/0 [4000Hz cpu-clock:pppH], (target_pid: 16548)
------------------------------------------------------------------------------------------------------------------------------------------------------------
4.93% libR.so [.] 0x0000000000223685
 4.52% libR.so [.] 0x0000000000224901
 2.16% libR.so [.] 0x0000000000191a13
 1.91% libR.so [.] 0x000000000018f6ec
 1.51% libR.so [.] 0x00000000002248dc
 1.17% libR.so [.] 0x0000000000132754
 1.16% libR.so [.] 0x0000000000227b21
```

I'm reporting in case someone else encounter the same issue and I will update this after:
 - use the latest dev version and compare
 - identify the commit that introduced or fixed the regression

My hypothesis is that using limit on k8s pod cpu/mem introduce an overhead to each malloc and it gets compounded when you do it a lot.

This issue could also have been reported differently, or it is related to something that was already observed, but I could not find anything.

**Comment by trivialfis** [comment]
I think we made it parallel by default in the last release.   A quick workaround would be setting the `nthread` parameter.

**Comment by meztez** [comment]
We set OMP_NUM_THREAD=1. The team mentioned that they read the release news and set nthread. I will that this is the case.

**Comment by meztez** [comment]
They set nthread on each model using during package load :
```r
xgboost::`xgb.parameters<-`(model, list(nthread = 1))
```

**Comment by meztez** [comment]
So. We first investigated this issue because we identified degraded timing on a k8s service deployment that uses xgboost R library extensively. All containers of this particular workload set OMP_NUM_THREADS=1.

I think this is due to an operation cost overhead for libgomp.so because we enforce container cpu/memory limitation.

Our solution was to built xgboost R library from source using -DUSE_OPENMP=OFF the timing issues went away. In our specific workload, there is no benefit to threading.

We also experimented with data.table R package built with env variable R_NO_OPENMP=1.  Our workload also uses this heavily. We did not observe any significant difference.

```docker
# Compile xgboost without OPENMP supports to avoid nthreads timing issues
RUN apt-get -qq -y install cmake
RUN git clone --recursive https://github.com/dmlc/xgboost
WORKDIR /src/xgboost
RUN git submodule init
RUN git submodule update
RUN mkdir build
WORKDIR /src/xgboost/build
RUN cmake .. -DR_LIB=ON -DUSE_OPENMP=OFF
RUN make -j$(nproc)
RUN make install
```
