### ISSUE TITLE
Inaccessible nodes in generated trees

### ISSUE THREAD

**Issue by trevoryann** [dmlc/xgboost#6733]
Sometimes the generated trees in the model contain nodes that are not accessible, increasing model files unnecessarily

All of the nodes in a tree should be accessible from the root node, but sometimes a node will have no left or right children that refer to the node.

e.g.
node 0: left_child = 1, right_child = 2
node 1: left_child = -1, right_child = -1
node 2: left_child = -1, right_child = -1
node 3: left_child = -1, right_child = -1

node 3 is not accessible from the root

This can be seen clearly using the json encoded model (as demonstrated below), but I have also seen this issue within the binary model files.

```
import json

import numpy as np
import xgboost as xgb

sample_count = 1000
feature_count = 100

# make dataset

np.random.seed(0)

X = np.random.randn(sample_count, feature_count)
y = np.random.choice(2, sample_count)

dtrain = xgb.DMatrix(X, y)

param = {
    'eta': 0.1,
    'objective': 'binary:logistic',
    'nthread': 1,
    'eval_metric': 'logloss',
    'gamma': 0.1,
}

bst = xgb.train(param, dtrain, num_boost_round=50)

model_filename = 'model0.json'
bst.save_model(model_filename)
with open(model_filename, 'rt') as f:
    m = json.load(f)

trees = m['learner']['gradient_booster']['model']['trees']

for tid, t in enumerate(trees):
    node_count = len(t['left_children'])
    left_children = set(nid for nid in t['left_children'])
    right_children = set(nid for nid in t['right_children'])
    all_children = left_children | right_children
    expected = set(range(1, node_count))
    if not expected <= all_children:
        print('tree:', tid, 'node_count:', node_count,
              'inaccessible node ids:', expected - all_children)
```

output:
```
tree: 22 node_count: 73 inaccessible node ids: {72, 71}
tree: 23 node_count: 35 inaccessible node ids: {17, 18}
tree: 33 node_count: 81 inaccessible node ids: {61, 62}
tree: 36 node_count: 55 inaccessible node ids: {53, 54}
tree: 37 node_count: 59 inaccessible node ids: {53, 54}
tree: 44 node_count: 45 inaccessible node ids: {19, 20}
tree: 45 node_count: 77 inaccessible node ids: {67, 68, 53, 54}
tree: 47 node_count: 51 inaccessible node ids: {49, 50}
```

**Comment by trivialfis** [comment]
These are pruned nodes.

**Comment by trevoryann** [comment]
I suspected this was the case. The issue is then minor - there is a very slight increase in the size of the model file when this happens (which is infrequent), but there is no impact on predictions.

**Comment by trivialfis** [comment]
I want to convert all tree methods to use pre-pruning.  But that will be another topic.  Closing.
