### ISSUE TITLE
incorrect install interface, result the package is not relocatable

### ISSUE THREAD

**Issue by kangsheng89** [dmlc/xgboost#6734]
https://github.com/dmlc/xgboost/blob/1fa6793a4efdf0d41b012fcdf8b3931530464e51/CMakeLists.txt#L206  

This line of INSTALL_INTERFACE is wrong and not relocatable. This will result that INTERFACE_INCLUDE_DIRECTORIES set as hardcoded path based on CMAKE_INSTALL_PREFIX from Build Machine

please refer to this https://cmake.org/cmake/help/latest/manual/cmake-packages.7.html#creating-relocatable-packages

preferable to use as:
$<INSTALL_INTERFACE:$<INSTALL_PREFIX>/include>

**Comment by trivialfis** [comment]
Thanks for pointing that out @kangsheng89 .  Would you like to open a PR for addressing the issue?

**Comment by kangsheng89** [comment]
@trivialfis please review the changes! Thanks

**Comment by trivialfis** [comment]
Thanks for the PR!

**Comment by kangsheng89** [comment]
Welcome!!
