### ISSUE TITLE
R Package Saved Model Predicted Time

### ISSUE THREAD

**Issue by mrkaye97** [dmlc/xgboost#6736]
(This is a question and not a bug)

I noticed that saving `xgboost` objects via `saveRDS` or `save` in R instead of `xgb.save` results in dramatically slowed down predict times after loading the model. See this `reprex`:

``` r
library(microbenchmark)
library(xgboost)
library(tidyverse)

predictors <- iris %>%
  select(-Species) %>%
  as.matrix()

label <- iris$Species

local_model <- xgboost(
  data = predictors,
  label = label,
  nrounds = 500,
  verbose = FALSE
)

## save it
saved_local_model <- local_model
tmp <- tempfile(fileext = '.rda')
saveRDS(saved_local_model, file = tmp)
rm(saved_local_model)

## model from Rdata file
saved_local_model <- readRDS(file = tmp)

## benchmark predictions
## local model
microbenchmark({
  predict(
    local_model,
    predictors,
    type = 'prob'
  )
})
#> Unit: microseconds
#>                                                     expr     min       lq
#>  {     predict(local_model, predictors, type = "prob") } 371.657 419.4635
#>     mean   median       uq     max neval
#>  446.813 436.2275 458.3055 861.918   100

## saved local model
microbenchmark({
  predict(
    saved_local_model,
    predictors,
    type = 'prob'
  )
})
#> Unit: microseconds
#>                                                           expr     min       lq
#>  {     predict(saved_local_model, predictors, type = "prob") } 946.445 1110.667
#>      mean   median      uq      max neval
#>  1246.239 1197.307 1359.86 2203.484   100
```

<sup>Created on 2021-02-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I was wondering why this happens. I realize that using `xgb.save` is certainly the best way to go and fixes this issue, but I'm just curious about why this is happening. Thanks!

**Comment by hcho3** [comment]
When `readRDS` is used, XGBoost executes one extra step of deserialization, to convert the bytes from RDS into a full XGBoost Booster object. This extra step is part of the `predict` function. You can avoid this overhead by preemptively performing the deserialization step as follows:
```R
saved_local_model <- readRDS(file = tmp)
saved_local_model <-  xgb.Booster.complete(saved_local_model)
predict(
    saved_local_model,
    predictors,
    type = 'prob'
  )
```

**Comment by hcho3** [comment]
Also, we highly recommend that you use `xgb.save` to save your model, so that it can be safely read in future versions of XGBoost. See https://www.rdocumentation.org/packages/xgboost/versions/1.3.2.1/topics/a-compatibility-note-for-saveRDS-save

**Comment by mrkaye97** [comment]
Awesome, thanks a bunch @hcho3!

Re: docs about using `xgb.save` -- I saw that too and have been using `xgb.save` over `saveRDS`. What's the reason for this change?

**Comment by hcho3** [comment]
@mrkaye97 Parts of the model (Booster) object contain internal representation that's not portable across multiple versions of XGBoost. The `xgb.save` method filters out such bits to obtain a portable model file, so that it can be read from future versions. On the other hand, `saveRDS` is indiscriminate and saves all the bits, rendering the resulting artifact incompatible with future versions.

**Comment by mrkaye97** [comment]
Gotcha, thanks again @hcho3!
