### ISSUE TITLE
Pip install version is different than the one on the git repo

### ISSUE THREAD

**Issue by amro-pydev** [dmlc/xgboost#674]
Hi,

I installed the xgboost using pip command at the beginning. When I was trying to get the variable best_ntree_limit to get the best iteration in training. I got an error message saying it doesn't exist. when I checked the code in my packages, I found it doesn't really exist. When I checked online in the repo it exists. It seems like there is a version difference between the final one in the repo and one pointed to by pip tool.

Regards,
Amr

**Comment by terrytangyuan** [comment]
Yes, the pip version may not be the most updated. You can install the one on the repo if you want.

**Comment by phunterlau** [comment]
I will update the pip since best_ntree_limit is a good new feature

**Comment by amro-pydev** [comment]
That was really fast. Thanks for the reply.

-Amr

**Comment by amro-pydev** [comment]
HI Hongliang,

Is it now updated in the pip? I'm not able to build the downloaded version on MAC.

-Amro

**Comment by phunterlau** [comment]
updated PyPI with the latest xgboost github #678
