### ISSUE TITLE
[CI] Build and upload xgboost4j.dll in GitHub Actions

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#6748]
Following up with https://github.com/dmlc/xgboost/pull/6630#issuecomment-790702133. Currently, we already run our CI on GitHub Actions which builds and tests XGBoost4J for the Windows platform. The byproduct `xgboost4j.dll` should be uploaded to a S3 bucket, so that later we can include it in the official Maven JAR release.

cc @Craigacp

**Comment by Craigacp** [comment]
I did check the Windows build over the weekend, and adding the jar is sufficient to make the single node tests pass. I'm not sure if it's worth making xgboost4j-spark check it's platform and intentionally fail if it's Windows, as the tests do not pass there.

**Comment by bluelu** [comment]
I can confirm that adding the jar is sufficient. Would be great if the windows dll could be finally integrated by default. Thank you! :)
