### ISSUE TITLE
Can I use XGBoost in classification problem with soft label rather than true labels?

### ISSUE THREAD

**Issue by Liumucan** [dmlc/xgboost#6750]
Hi! I want to use XGBoost as a student model in the framework of knowledge distillation.
So I wonder if I can use XGBoost in classification problem with soft label rather than true labels.
I have tried to adjust the objective function but still not work.
Thanks for you excellent work and hope for help!

**Comment by trivialfis** [comment]
You will have to define a custom objective function.  See https://github.com/dmlc/xgboost/blob/master/demo/guide-python/custom_softmax.py for an example.
