### ISSUE TITLE
Custom early stopping algorithm

### ISSUE THREAD

**Issue by zzzbobml** [dmlc/xgboost#6758]
Is there a way to customize the early stopping policy?
I'd be interested to use the evaluation function of all trees up until the current iteration to make a decision as to proceed in the training or not, but I could not find anything in the documentation.

**Comment by trivialfis** [comment]
You can define your own callback function for early stopping:

https://xgboost.readthedocs.io/en/latest/python/callbacks.html
https://github.com/dmlc/xgboost/blob/master/demo/guide-python/callbacks.py

**Comment by zzzbobml** [comment]
Thank you, the example is a bit clearer.
If I wanted to define my own early stopping policy, presumably I would need to define something like 
`class my_early_stopping(xgb.callback.TrainingCallback)
`
How would I tell xgboost to stop training if a certain condition has reached?

**Comment by trivialfis** [comment]
Please see the interface of `xgboost.callback.TrainingCallback`, you can get access to the model itself in all methods including `after_iteration`.  With the model you can run prediction by `model.predict`.

**Comment by trivialfis** [comment]
See doc string of https://github.com/dmlc/xgboost/blob/4f75f514ce48936e654c6baddccb7fb864e16af2/python-package/xgboost/callback.py#L273 .
