### ISSUE TITLE
R documentation: Construction of dtrain is inconsistent and can be shortened.

### ISSUE THREAD

**Issue by ReeceGoding** [dmlc/xgboost#6768]
The following pattern is often seen in [the R documentation](https://cran.r-project.org/web/packages/xgboost/xgboost.pdf):
```R
data(agaricus.train, package='xgboost')
train <- agaricus.train
dtrain <- xgb.DMatrix(train$data, label=train$label)
```
By my count, this is used in the docs for `dim.xgb.DMatrix`, `dimnames.xgb.DMatrix`, `getinfo`, `print.xgb.DMatrix`, `setinfo`, `slice`, `xgb.DMatrix`, and `xgb.DMatrix.save`. It is also found for a `dtest` variable in `predict.xgb.Booster`'s docs.

However, the following pattern is instead found in the docs for `xgb.create.features` (and again in the construction of`new.dtrain`),  `xgb.cv`, and `xgb.train`:
```R
data(agaricus.train, package='xgboost')
dtrain <- xgb.DMatrix(agaricus.train$data, label = agaricus.train$label)
```
Most commonly, this second pattern is also used for a `dtest` variable as well, making the full block:
```R
data(agaricus.train, package='xgboost')
data(agaricus.test, package='xgboost')

dtrain <- xgb.DMatrix(agaricus.train$data, label = agaricus.train$label)
dtest <- xgb.DMatrix(agaricus.test$data, label = agaricus.test$label)
```
I suggest that these should be made consistent.

The shortest solution that I know is to use:
```R
data(agaricus.train, package='xgboost')
data(agaricus.test, package='xgboost')
dtrain <- with(agaricus.train, xgb.DMatrix(data, label = label))
dtest <- with(agaricus.test, xgb.DMatrix(data, label = label))
```
and its equivalent for the shorter cases:
```R
data(agaricus.train, package='xgboost')
dtrain <- with(agaricus.train, xgb.DMatrix(data, label = label))
```
The only issue that I can see with my suggestion is that R tells me that the following returns `FALSE`:
```R
train <- agaricus.train
dtrain2 <- xgb.DMatrix(train$data, label = train$label)
identical(dtrain, dtrain2)
```
However, I think that is just because the external pointers for the two variables disagree. The fact that `all.equal(dtrain, dtrain2)` is `TRUE` suggests that the issue is very minor.

If we're happy with this, it shouldn't take me long to make a pull request changing the docs to the `with` version.

**Comment by trivialfis** [comment]
Thanks for the detailed issue and PR.
