### ISSUE TITLE
[jvm-packages] SIGSEGV for predict function in XGBoost4J 

### ISSUE THREAD

**Issue by qinglong1230** [dmlc/xgboost#6780]
We are trying to run xgboost4j for model inference in a cascading job and encounter an error below. It looks very similar to 
https://github.com/dmlc/xgboost/issues/3768

But there is no suggested fix for the issue. I tried both 0.90 and 0.82 and had the same problem below.

```
A fatal error has been detected by the Java Runtime Environment:

SIGSEGV (0xb) at pc=0x00007f158fe8cbe6, pid=76871, tid=0x00007f1591397700

JRE version: OpenJDK Runtime Environment (8.0_232) (build 1.8.0_232-ga-1)
Java VM: OpenJDK 64-Bit Server VM (25.232-b1 mixed mode linux-amd64 compressed oops)
Problematic frame:
V  [libjvm.so+0x64ebe6]  jni_SetFloatArrayRegion+0x76

Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
```

**Comment by trivialfis** [comment]
The current xgboost version is 1.3 and 1.4 is coming.  Please use them.  I believe the issue is fixed.
