### ISSUE TITLE
What label= should be for the regression model?

### ISSUE THREAD

**Issue by Roffild** [dmlc/xgboost#6786]
```python
mylbl = numpy.array([[0.], [0.], [1.], [0.], [1.]], dtype=numpy.float32)
mylbl.ndim == 2
```

xgboost.DMatrix(label=)
* `label : list, numpy 1-D array or cudf.DataFrame, optional
            Label of the training data.`
* `label=None`
`xgboost.core.XGBoostError: src/objective/regression_obj.cu:57: Check failed: preds.Size() == info.labels_.Size() (61872 vs. 0) :  labels are not correctly providedpreds.size=61872, label.size=0, Loss: binary:logistic`
* `label=mylbl` - OK

catboost.Pool(label=)
* `label : list or numpy.ndarrays or pandas.DataFrame or pandas.Series, optional (default=None)
            Label of the training data.
            If not None, giving 1 or 2 dimensional array like data with floats.`
* `label=None`
`File "catboost\core.py", line 976, in _build_train_pool
    raise CatBoostError("Label in X has not been initialized.")`
* `label=mylbl` - OK

lightgbm.Dataset(label=)
* `label : list, numpy 1-D array, pandas Series / one-column DataFrame or None, optional (default=None)
            Label of the data.`
* `label=None` - OK
* `label=mylbl`
`File "lightgbm\basic.py", line 93, in list_to_1d_numpy
    raise TypeError("Wrong type({0}) for {1}.\n"
TypeError: Wrong type(ndarray) for label.
It should be list, numpy 1-D array or pandas Series`

Can you accept a single standard?

Parameter description is incorrect.

**Comment by Roffild** [comment]
https://github.com/dmlc/xgboost/issues/6786
https://github.com/catboost/catboost/issues/1623
https://github.com/microsoft/LightGBM/issues/4115

**Comment by trivialfis** [comment]
For training you need to pass labels, for prediction it's not needed.

What's your expectation?

**Comment by Roffild** [comment]
Used training.

**Comment by trivialfis** [comment]
## When is label required
Other than survival training which uses `label_upper_bound` and `label_lower_bound`, `label` is required for training.  It can be any data type supported by xgboost.

## What data type does xgboost accept

We don't have a complete document on supported data types yet so on the latest it's required to be "array like", but looking into https://github.com/dmlc/xgboost/blob/8825670c9c10c3c72c4f8e499c6ce43b1f51dcd3/python-package/xgboost/data.py#L684 should provide some hints.

## What shape should the label array have
Column vector with the size of number of training samples.

**Comment by trivialfis** [comment]
Feel free to reopen if there's further question.

**Comment by Roffild** [comment]
I am iterating over the parameters. It's easier for me to set label. Algorithm-level error is preferred over global error.

In the description 1D array. But for regression there must be ND.

**Comment by trivialfis** [comment]
> But for regression there must be ND.

What do you mean by that?
