### ISSUE TITLE
how to show feature importance in pyspark xgboost？

### ISSUE THREAD

**Issue by forrestneo** [dmlc/xgboost#6812]
i need to know ，the offical document doesnot have this content

**Comment by trivialfis** [comment]
I don't think xgboost has official support for Pyspark.

**Comment by forrestneo** [comment]
> I don't think xgboost has official support for Pyspark.

i get a method

import re 
str1 = FeatureScoreMap = preModel.nativeBooster.getScore("","gain")
file_path ="./importance.csv"
file  = open(file_path,"w+")
print(str1,file = file)
file.close()
f1 = open(file_path)
line = f1.readline()
data=line.replace(',','\n').replace('->',',').replace('Map(','').replace(')','').replace('f','')
file  = open(file_path,"w+")
print(data,file = file)
file.close()
data = pd.read_csv(file_path,header=None,names=["feature","weight"])
data
