### ISSUE TITLE
Speed up dask tests.

### ISSUE THREAD

**Issue by trivialfis** [dmlc/xgboost#6816]
https://github.com/microsoft/LightGBM/pull/4088#issuecomment-810711965

**Comment by jmoralez** [comment]
Hi. I'd be happy to give this a go, just have a couple of questions on the scope.
1. Should this target only the tests that take in a `client` fixture or every test that builds a cluster?
2. The main component is creating a cluster fixture that lives throughout the tests. What should the client be?
    * A fixture that uses the cluster fixture.
    * Define `client = Client(cluster)` in every test.
    * Use the `with Client(cluster) as client` context manager in every test.
    * Something else

**Comment by trivialfis** [comment]
Closing since the bottleneck is hypothesis tests.  Thanks for the PR @jmoralez
