### ISSUE TITLE
WARNING: C:\Users\Administrator\workspace\xgboost-win64_release_1.0.0\src\learner.cc:328:  Parameters: { n_estimators } might not be used.    This may not be accurate due to some parameters are only used in language bindings but   passed down to XGBoost core.  Or some parameters are not used but slip through this   verification. Please open an issue if you find above cases.

### ISSUE THREAD

**Issue by 100ravSingh** [dmlc/xgboost#6837]
Thanks for participating in the XGBoost community! We use https://discuss.xgboost.ai for any general usage questions and discussions. The issue tracker is used for actionable items such as feature proposals discussion, roadmaps, and bug tracking.  You are always welcomed to post on the forum first :)

Issues that are inactive for a period of time may get closed. We adopt this policy so that we won't lose track of actionable issues that may fall at the bottom of the pile. Feel free to reopen a new one if you feel there is an additional problem that needs attention when an old one gets closed.

For bug reports, to help the developer act on the issues, please include a description of your environment, preferably a minimum script to reproduce the problem.

For feature proposals, list clear, small actionable items so we can track the progress of the change.

**Comment by hcho3** [comment]
Closing this, as it lacks the description of what went wrong.

**Comment by trivialfis** [comment]
The parameter is only used in sklearn interface, on native interface see the document of `train` method.
