### ISSUE TITLE
We are taking baby steps to migrate from xgboost 0.72 to 0.90 version  . please help us in resolving below queries: 1) Would there be any challenge if I run grid search on 0.90 version and do training with those tuned hyper parameter on 0.72 version? 2) Is there any way to know at which nth round  the early stopping feature stopped in 0.90 version for regression and classification  cross validation? 

### ISSUE THREAD

**Issue by rinisin13** [dmlc/xgboost#6838]
Thanks for participating in the XGBoost community! We use https://discuss.xgboost.ai for any general usage questions and discussions. The issue tracker is used for actionable items such as feature proposals discussion, roadmaps, and bug tracking.  You are always welcomed to post on the forum first :)

Issues that are inactive for a period of time may get closed. We adopt this policy so that we won't lose track of actionable issues that may fall at the bottom of the pile. Feel free to reopen a new one if you feel there is an additional problem that needs attention when an old one gets closed.

For bug reports, to help the developer act on the issues, please include a description of your environment, preferably a minimum script to reproduce the problem.

For feature proposals, list clear, small actionable items so we can track the progress of the change.

**Comment by trivialfis** [comment]
Please directly migrate to 1.3 or 1.4(about to be released).

But to answer your questions:
1. Should be fine.
2. There's an attribute called best_iteration.

**Comment by rinisin13** [comment]
@trivialfis : Thanks for answering this. We are still with spark 2.3.1 version. 
Is there any backward compatibility support, If we want to migrate 1.3/1.4 version?

**Comment by trivialfis** [comment]
1. Yes, you can load old models from the new version, but not the other way around.
2. I don't know.  @wbo4958 may have better insight.

**Comment by wbo4958** [comment]
Yeah, the jvm maintainer decided not to support backward from 1.0 release. I don't know, if there are many users who still work on spark 2.4, I can make xgboost backward compatibility.

**Comment by CodingCat** [comment]
Spark 2.4 is releasing the last version in few weeks and then EOL..not
seeing keep investing a dying version is efficient
