### ISSUE TITLE
Release changes for the ability to send enable_categorical to DaskDMatrix

### ISSUE THREAD

**Issue by bhavana3** [dmlc/xgboost#6839]
I am trying to use xgboost-dask 1.3.3 version and see that the enable_categorical feature support is not enable while making the call to xgb.dask.DaskDMatrix. I also identified changes are made to master and merged. As the release version wouldn't support this and blocks users, I wanted to understand when the release of these changes are planned?

**Comment by trivialfis** [comment]
Category data support is not in distributed training yet.  As documented this parameter is experimental.  See https://github.com/dmlc/xgboost/issues/6503 for progress.

In 1.4 (about to be released), the parameter is available in Dask DMatrix, but setting it to true will raise an error.

**Comment by bhavana3** [comment]
Thank you. Are the only supported dtypes are - int, float, bool for distributed training?

**Comment by trivialfis** [comment]
Yup.  But basic support for distributed training should come soon.  Stay tuned.
