### ISSUE TITLE
load xgboost source code 

### ISSUE THREAD

**Issue by zyq11223** [dmlc/xgboost#6844]
Could you share how to load the xgboost source code with vscode ? I wanna improve my coding style, and participate in to contribute to the source code

**Comment by trivialfis** [comment]
Just like loading any other project?

**Comment by zyq11223** [comment]
> Just like loading any other project?

Missing Headers...

**Comment by zyq11223** [comment]
> Just like loading any other project?

include/xgboost/base.h
has problems: 
    identifier "constexpr" is undefined,
    expected a ';'

**Comment by zyq11223** [comment]
> > Just like loading any other project?
> 
> include/xgboost/base.h
> has problems:
> identifier "constexpr" is undefined,
> expected a ';'

solved by change c++ standard to c++11

**Comment by trivialfis** [comment]
Can you run `cmake` ?

**Comment by trivialfis** [comment]
For general c++ projects, you may want to take a look into language server protocol: https://microsoft.github.io/language-server-protocol/
