### ISSUE TITLE
Add support for pandas nullable types in feature matrix

### ISSUE THREAD

**Issue by freddyaboulton** [dmlc/xgboost#6851]
I would like to use [pandas nullable types](https://pandas.pydata.org/docs/user_guide/integer_na.html) with xgboost. Currently, xgboost will raise a ValueError if any of the features use the new nullable pandas types. 

Repro with xgb `1.2.1` and pandas `1.2.3`:

```python
from xgboost import XGBClassifier
import pandas as pd
import pytest

for dtype in ['Int64', 'Float64', 'boolean']:
    
    xgb = XGBClassifier()

    # ValueError if only features use nullable types
    df = pd.DataFrame({"a": pd.Series([True, False, True, False], dtype=dtype),
                       "b": pd.Series([4, 5, 6])})
    y = pd.Series([1, 0, 1, 0])
    
    with pytest.raises(ValueError):
        xgb.fit(df, y)


# No ValueError if use "old" types
for dtype in ['int', 'float', 'bool']:
    
    df = pd.DataFrame({"a": pd.Series([True, False, True, False], dtype=dtype)})
    y = pd.Series([1, 0, 1, 0])

    xgb = XGBClassifier()
    xgb.fit(df, y)
```

As a user, I would like this feature so I can build a data processing pipeline using the latest pandas capabilities.

Thank you!

**Comment by trivialfis** [comment]
Took a quick look.  I think a better way is to work on https://github.com/dmlc/xgboost/pull/5667 so that we can have masked arrays.

**Comment by freddyaboulton** [comment]
Thanks for taking a look @trivialfis ! So a feature matrix with pandas nullable types will be converted to a masked array? What's the status of #5667 ?

**Comment by trivialfis** [comment]
> So a feature matrix with pandas nullable types will be converted to a masked array?

That's what I'm hoping and I suspect that's how it's implemented for nullable arrays.

> What's the status of #5667 ?

I assigned myself to work on it based on the existing work by @zhangzhang10 .  But arrow can trunk the data in an arbitrary way so it's a bit messy, I will try to follow up.

**Comment by Ark-kun** [comment]
XGBoost still fails when encountering nullable floating-point dtypes.

**Comment by gsheni** [comment]
@Ark-kun I believe this now works
```python
from xgboost import XGBClassifier
import pandas as pd
import pytest

xgb = XGBClassifier()

# ValueError if only features use nullable types
df = pd.DataFrame({"a": pd.Series([True, False, True, False], dtype='boolean'),
                   "b": pd.Series([4, 5, 6, None], dtype='Int64'),
                   "c": pd.Series([1.23, 4.58, 3.14, 83.12], dtype='Float64')})
y = pd.Series([1, 0, 1, 0])
xgb.fit(df, y)
```
