### ISSUE TITLE
Json saved model fails to reproduce results

### ISSUE THREAD

**Issue by Abhinavfreecodecamp** [dmlc/xgboost#6859]
Hi Team,

I have worked with xgb classifier for past 2-3 years and since then my goto save and load model mechanism was pickle, recently I upgraded my xgb to 1.3.3 and since xgb recommended way to save and reload model is through JSON mechanism, I tried this and it failed miserably, I have mentioned below results of some experiments and their results.

The following table contains probability bucket and %user in the bucket when scored using JSON saved model, in-memory model, pickle saved.

prob bucket | JSON SAVED | IN-Memory | Pickle saved
(0.00,0.001 | 100.00 | 100.00 | 100.00
(0.001,0.002 | 58.49 | 47.79 | 47.79
(0.002,0.003 | 48.10 | 21.90 | 21.90
(0.003,0.004 | 37.02 | 13.76 | 13.76
(0.004,0.005 | 32.67 | 10.08 | 10.08
(0.005,0.006 | 30.02 | 7.90 | 7.90
(0.006,0.007 | 28.48 | 6.46 | 6.46
(0.007,0.008 | 27.28 | 5.44 | 5.44
(0.008,0.009 | 26.30 | 4.65 | 4.65
(0.009,0.01 | 25.51 | 4.00 | 4.00
(0.01,0.02 | 24.87 | 3.47 | 3.47
(0.02,0.03 | 20.82 | 1.39 | 1.39
(0.03,0.04 | 18.47 | 0.77 | 0.77
(0.04,0.05 | 16.98 | 0.50 | 0.50
(0.05,0.06 | 15.92 | 0.34 | 0.34

We can see even a 12% difference in 1st bucket and it keeps getting worse. I have no idea why it is scoring so differently. For now, I am using pickle as it is providing me the same results.

xgb version = 1.3
python version = 3.6

**Comment by trivialfis** [comment]
Could you please share a reproducible script?

**Comment by trivialfis** [comment]
It would be great to have at least the set of parameters that you are using.

**Comment by trivialfis** [comment]
The issue you are describing is quite serious.   I tried to reproduce it with `sklearn.datasets.fetch_covtype` on 1.3 but counldn't observe the difference.

**Comment by trivialfis** [comment]
Also, could you please try 1.4 if you have early stopping enabled?  I suspect the difference comes from `best_iteration` not being restored after loading the model.  Before 1.4, users need to call `booster.attr` for getting those attributes back.  After 1.4 they are loaded automatically.

**Comment by Abhinavfreecodecamp** [comment]
@trivialfis 

model.save_model('models/xgb_cl11.json') # saving model script

model = xgb.XGBClassifier() # loading model
model.load_model("models/xgb_cl11.json") 

predictions_with_treatment = model.predict_proba(data)

**Comment by trivialfis** [comment]
I'm doing something similar.  I will share my script a bit later, currently on phone.  See if you can tweet it into reproducing the issue.

**Comment by Abhinavfreecodecamp** [comment]
@trivialfis 

I am getting these same numbers multiple times so yes I can reproduce this issue.

**Comment by trivialfis** [comment]
@Abhinavfreecodecamp Thanks for sharing.  Could you try this with `X, y` replaced with own data:

``` python
import xgboost as xgb
import numpy as np
from sklearn.datasets import fetch_covtype


def main():
    # Please replace it with your data
    X, y = fetch_covtype(return_X_y=True)
    y -= 1

    cls = xgb.XGBClassifier(
        use_label_encoder=False, tree_method="hist", n_estimators=100
    )
    cls.fit(X, y, eval_set=[(X, y)])

    in_memory = cls.predict_proba(X)

    cls.save_model("model.json")
    cls.save_model("model.bin")

    from_json = xgb.XGBClassifier()
    from_json.load_model("model.json")
    from_bin = xgb.XGBClassifier()
    from_bin.load_model("model.bin")

    from_json.save_model("json_to_binary.bin")
    from_bin.save_model("binary_to_binary.bin")

    with open("json_to_binary.bin", "rb") as jfd, open(
        "binary_to_binary.bin", "rb"
    ) as bfd, open("model.bin", "rb") as ofd:
        from_json = jfd.read()
        from_bin = bfd.read()
        origin = ofd.read()
        # bit identical
        assert from_json == from_bin
        assert origin == from_json

    cls = xgb.XGBClassifier()
    cls.load_model("model.json")
    with_json = cls.predict_proba(X)
    cls.save_model("model-1.json")

    with_json_1 = cls.predict_proba(X)
    np.testing.assert_allclose(with_json, with_json_1)

    np.testing.assert_allclose(in_memory, with_json)


if __name__ == "__main__":
    assert xgb.__version__ == "1.3.3" or xgb.__version__ == "1.4.0"
    main()
```

**Comment by Abhinavfreecodecamp** [comment]
@trivialfis it worked fine without any error but I was able to produce this error.

**Comment by trivialfis** [comment]
Hmm ..  if you want me to debug further I will have to get access to your code.  I can't guess what's happening.

**Comment by Abhinavfreecodecamp** [comment]
@trivialfis I am not at liberty to share code as it is proprietary, I am sharing model object.

xgb_cl11_treatment = xgb.XGBClassifier(silent=False,
                learning_rate=0.1,
                 n_jobs=40,
                 n_estimators=600,
                 random_state=7,
                 max_depth=10,
                 eval_metric='binary:logistic',
                 objective = 'binary:logistic'
                 )

eval_set = [(train_data_treatment,train_target_treatment),(cv_data_treatment, cv_target_treatment)]

xgb_cl11_treatment.fit(train_data_treatment,train_target_treatment,eval_metric = 'logloss',
           eval_set = eval_set, early_stopping_rounds = 50)

**Comment by trivialfis** [comment]
@Abhinavfreecodecamp Got it.  Could you please be more specific on your previous comments:

> But currently, I am not able to reproduce it. Even I have the exact number from the past experiment.

So currently you can't reproduce it with your code, or with my code, or neither of them can be used to reproduce.

If you can't reproduce it with my code and your code still shows the error, then I suspect it's the `early_stopping_rounds`.  Could you please try 1.4 as suggested in https://github.com/dmlc/xgboost/issues/6859#issuecomment-819504120 ?

**Comment by Abhinavfreecodecamp** [comment]
@trivialfis It Worked fine with 1.4 and got the same numbers with 1.3 with booster.attr Thank you so much :)

**Comment by trivialfis** [comment]
No problem.  Thanks for raising the issue, it will help others who search for similar problems.
