### ISSUE TITLE
AttributeError: 'module' object has no attribute 'XGBClassifier'

### ISSUE THREAD

**Issue by ajkl** [dmlc/xgboost#686]
Successfully built multi-thread xgboost on Ubuntu 14.04. 
Using python 3.4.
Install of python package went fine.
I get no errors on import xgboost.
But when I try to use the XGBRegressor or XGBClassifier I get the "module object has no attribute" error.
What debug info will be helpful ?

**Comment by terrytangyuan** [comment]
Which version are you using? Could you try the most recent version?

**Comment by AniSkywalker** [comment]
I am still facing the issue. I have installed from both Conda-forge,Github, using pip. Strangely i can run in interpreter and ipython. When I am calling from Pycharm or console, it throws the error. I am using Anaconda and I have only one version of python(3.6.2).

**Comment by petercuichen** [comment]
@AniSkywalker Check whether one of your own package or pyfile named xgboost, that could cause conflict.
