### ISSUE TITLE
[BUG] xgb.cv() auc metric computation in v1.4.0 release with tree_method='gpu_hist' broken

### ISSUE THREAD

**Issue by btong04** [dmlc/xgboost#6865]
Tested xgb.cv() method against various scoring metrics on both CPU and GPU for classification models. Using xgboost version 1.4.0 release from pip produced unexpected results with metric='auc'. Other metrics such as ['aucpr', 'logloss', 'map'] appears to be consistent. 
![xgb_1 4 0_release_auc_issues](https://user-images.githubusercontent.com/23238612/114915422-893baa00-9df1-11eb-8d06-f576a0664baa.PNG)

Running the same code under xgboost version 1.3.3 produced consistent results for CPU/GPU scoring with metric='auc' as to be expected. 
![xgb_1 3 3_release_auc_okay](https://user-images.githubusercontent.com/23238612/114915418-880a7d00-9df1-11eb-82cd-b71c57567e44.PNG)

Attached is a notebook and sample data to reproduce the issue:
[xgb_cv_v1.4.0_auc_metric_on_gpu_broken.zip](https://github.com/dmlc/xgboost/files/6320274/xgb_cv_v1.4.0_auc_metric_on_gpu_broken.zip)

**Comment by trivialfis** [comment]
The `cub::DeviceRadixSort` is not stable.

**Comment by hcho3** [comment]
@trivialfis According to https://groups.google.com/g/cub-users/c/1iXn3sVMEuA, the CUB's radix sort is stable.

**Comment by trivialfis** [comment]
For binary case (this issue), the result is different between runs, I narrowed it down the the `Argsort`.  If radix sort is stable, then my guess is somewhere it uses floating point which generates instability.
