### ISSUE TITLE
Does the predicted value of pairwise:rank has any meaning between different groups?

### ISSUE THREAD

**Issue by appierys** [dmlc/xgboost#689]
Hi,
I am wondering if the output value of `predict` has any meaning between different groups when pairwise:rank is used?

For example, if the labels are 0, and 1. Is it meaningful to select a threshold T so that we could assume that any instance has a predicted value greater than T probably has a label 1 ?

Thanks!

**Comment by tqchen** [comment]
NO the rank is ranked within each group, you can treat each group as a list in the rank setting
