### ISSUE TITLE
R: models can get de-serialized redundantly multiple times

### ISSUE THREAD

**Issue by david-cortes** [dmlc/xgboost#6896]
In the R version, the booster model objects store the underlying C++ objects as raw bytes plus a pointer to an in-memory object.

When one de-serializes a booster object (e.g. by restarting the R session or through `saveRDS` and `readRDS`), the pointer then becomes null, and when the time comes to use the C++ object, the object gets reconstructed from the raw bytes.

However, the pointer does not get updated in the original R object, which means the C++ object will get restored on each function call which is slow and uses more memory. Example:
```r
library(xgboost)
data(mtcars)
xgb_data <- xgb.DMatrix(as.matrix(mtcars[,-1]), label=mtcars[,1,drop=TRUE])
model <- xgb.train(list(objective="reg:squarederror"), xgb_data, nrounds=10)
saveRDS(model, file.path(tempdir(), "model.rds"))
model_new <- readRDS(file.path(tempdir(), "model.rds"))
print(model_new$handle)
```
```
<pointer: (nil)>
attr(,"class")
[1] "xgb.Booster.handle"
```
```r
pred <- predict(model_new, xgb_data)
print(model_new$handle)
```
```
<pointer: (nil)>
attr(,"class")
[1] "xgb.Booster.handle"
```

Would be better if this pointer were to be put in an R environment (e.g. `model$cpp_obj <- as.environment(list(handle=a_restored_handle))`), as then it would be updated by reference instead, keeping the pointer to the de-serialized object in the same object from which a function like `predict` is called and de-serializing only once during the object's lifetime in the R session.

**Comment by hcho3** [comment]
You can call `.complete()` method in order to amortize the cost of deserialization: https://www.rdocumentation.org/packages/xgboost/versions/1.4.1.1/topics/xgb.Booster.complete

Example:
```R
bst <- readRDS("xgb.model.rds")
bst <- xgb.Booster.complete(bst) 
# Now use bst without incurring the cost of deserialization
```

**Comment by david-cortes** [comment]
> You can call `xgb.Booster.complete()` method in order to amortize the cost of deserialization: https://www.rdocumentation.org/packages/xgboost/versions/1.4.1.1/topics/xgb.Booster.complete
> 
> Example:
> 
> ```r
> bst <- readRDS("xgb.model.rds")
> bst <- xgb.Booster.complete(bst) 
> # Now use bst without incurring the cost of deserialization
> ```

I realize it's possible, but would still be more handy to update the booster object in-place instead. Would you accept such a PR, or is there something that would break if the pointer were to be updated in-place?

**Comment by trivialfis** [comment]
@david-cortes I'm not sure, but if you have some code you can try running the tests.  PRs are welcomed.  Feel free to ping me if you need any help.
