### ISSUE TITLE
Using 'sample_weight_eval_set' - AssertionError assert len(sample_weight_eval_set) == len(eval_set) - Lengths are equal

### ISSUE THREAD

**Issue by ericvoots** [dmlc/xgboost#6897]
Hi,

I am getting the following error when using sample weights for the eval_set

"File "/usr/local/lib/python3.8/dist-packages/xgboost/sklearn.py", line 903, in fit
    train_dmatrix, evals = self._wrap_evaluation_matrices(
  File "/usr/local/lib/python3.8/dist-packages/xgboost/sklearn.py", line 259, in _wrap_evaluation_matrices
    assert len(sample_weight_eval_set) == len(eval_set)
AssertionError"

However, i checked the number observations and they are equal:

number of training observations:  1510809
number of training weights 1510809
number of cv observations:  149251
number of cv weights:  149251

Here is my training code

```
model_xgb = XGBClassifier(max_depth=20,
                              learning_rate=0.01,
                              min_child_weight=4,
                              colsample_bytree=0.5,
                              subsample=0.5,
                              scale_pos_weight=5,
                              n_estimators=400,
                              objective='binary:logistic'
                              )


    model_xgb.fit(train_x, 
                  train_y,
                  eval_set=[(cv_x, cv_y)],
                  eval_metric='auc',
                  early_stopping_rounds=25,
                  verbose=True,
                  sample_weight=weights,
                  sample_weight_eval_set=cv_weights)

    print('model fitted')
```

Let me know if there is additional information needed.  Thank you.

**Comment by trivialfis** [comment]
Hi, please pass them as lists:

``` python
clf.fit(X, y, sample_weight=weight, eval_set=[(valid_X, valid_y)], sample_weight_eval_set=[valid_weight])
```
