### ISSUE TITLE
DMatrix with multiprocessing deadlock

### ISSUE THREAD

**Issue by colinfang** [dmlc/xgboost#6898]
v1.4 on linux

```python
from multiprocessing.pool import Pool
import numpy as np
import xgboost as xgb


def worker():
    rng = np.random.default_rng(1)
    data = rng.random((100, 2))
    label = rng.integers(2, size=100)
    # It only works if `nthread = 1`
    dtrain = xgb.DMatrix(data, label=label, nthread=2)


def main():
    pool = Pool(1)
    r = pool.apply_async(worker)
    r.get()
    pool.close()
    pool.join()
    worker()

if __name__ == '__main__':
    main()
    # The 2nd time it deadlock
    main()
    print('done')
```

This hangs. Is this a known issue or am I doing it wrong?

**Comment by trivialfis** [comment]
This is known.  It's a bug somewhere inside openmp runtime.  A similar issue is here: https://github.com/dmlc/xgboost/issues/6617 .

The best option is to send an issue to gcc development team, but might take some efforts to create a reproducible example.

**Comment by trivialfis** [comment]
I haven't verified `libomp` from llvm, should try to do so later.  If you have experiment result feel free to share.

**Comment by trivialfis** [comment]
Closing as the bug is in underlying runtime instead of xgboost.
