### ISSUE TITLE
Can you provide a easy-to-use c++ interface?

### ISSUE THREAD

**Issue by nickhuangxinyu** [dmlc/xgboost#6902]
XGBoost is a great tool!

but i think its c++ interface is not so easy to use.

can you provide a interface for python save_model output?

I think CatBoost has a easy interface, its usage is:

in python:
model.save_model(path, format='cpp')

then it generate a cpp header file.

when i want to use the model, i only need to include the header file.

Can you kindly consider to add a interface?

Thanks very much!

**Comment by trivialfis** [comment]
Can you try treelite?

**Comment by 7starsea** [comment]
for c++ exmaple, please goto demo/c-api/c-api-demo.c.

however the c-api-demo.c is **old**.

**Comment by 7starsea** [comment]
> Can you try treelite?

Hello, could you please provide an example for XGBoosterPredictFromDense (the main issue for me is how provide the parameter _char const *values_)?

(My typical use case is online real-time prediction, predict one row at a time)
Thanks.

**Comment by trivialfis** [comment]
I am currently away from computer.  Predict function for xgboost is designed to handle large datasets.  For your use case (online, low latency), https://github.com/dmlc/treelite might be a good fit.  @hcho3 maintains both projects.

**Comment by 7starsea** [comment]
Thanks for your information and I will go and give it a shot.
