### ISSUE TITLE
[R-package] remove dependency on {magrittr}

### ISSUE THREAD

**Issue by jameslamb** [dmlc/xgboost#6904]
I've noticed that the R package has an `Imports`-level dependency on `{magrittr}`: https://github.com/dmlc/xgboost/blob/8760ec48277b345aaaa895b82570c25566fc0503/R-package/DESCRIPTION#L65

It seems that that library is only being used for the pipe operator (`%>%`), and all the uses of that operator are internal to the R package.

Would you be open to a pull request that factors out this dependency? I don't believe that the `%>%` is providing any functional benefit, and removing `{magrittr}` might have the following benefits:

* faster continuous integration runs
* faster installs for users
* lower risk of installation issues from source / CRAN (though to be fair `{magrittr}` is very lightweight)
* lower risk of installation issues for the conda package (https://github.com/conda-forge/xgboost-feedstock/blob/91db3d16c18dcd78baee02c58dc3e5273ca53770/recipe/meta.yaml#L140)
* reduce the cost of `{magrittr}`'s reverse dependency checks

Thanks for your time and consideration.

**Comment by kadyb** [comment]
This may be of interest to you. The new R version 4.1.0, which is scheduled for release on May 18, is expected to have a native pipe operator `|>`. 

> R now provides a simple native forward pipe syntax |>. The simple form of the forward pipe inserts the left-hand side as the first argument in the right-hand side call. The pipe implementation as a syntax transformation was motivated by suggestions from Jim Hester and Lionel Henry. This feature is experimental and may change prior to release. 

https://stat.ethz.ch/R-manual/R-devel/doc/html/NEWS.html

**Comment by hcho3** [comment]
I approve the move to eliminate the dependency on `{magrittr}`.

**Comment by jameslamb** [comment]
Ok thanks, I'll prepare a PR.

And thanks for the link @kadyb . To be clear though, I'm not proposing replacing `%>%` with the new base R pipe, as that would require pushing all `{xgboost}` users to upgrade up to R 4.1.0 when it's released.

I'm proposing replacing code like this:

```r
weights <- which(model_text_dump == "weight:") %>%
    {model_text_dump[(. + 1):length(model_text_dump)]} %>%
    as.numeric
```

with code like this

```r
weight_indx <- which(model_text_dump == "weight:")
weights <- as.numeric(
    model_text_dump[(weight_indx + 1):length(model_text_dump)]
)
```

**Comment by ReeceGoding** [comment]
I had a similar idea after submitting my PR that removed the magrittr dependency in the documentation a few weeks ago. What made me quit was the graphing code. For example, the pipes in xgb.plot.multi.trees.R seem quite natural. There are quite a few places where the pipes could be removed, but that's what made me give up on the idea. Any replacement that I could think of for them made the code much uglier.
