### ISSUE TITLE
Use array interface for numpy array inputs

### ISSUE THREAD

**Issue by sheecegardezi** [dmlc/xgboost#6908]
Code to reproduce:

using following  version
xgb.__version__= 1.4.0
System: Ubuntu 20.04 LTS

```
import xgboost as xgb
from sklearn.metrics import mean_squared_error
import pandas as pd
import numpy as np
from sklearn.datasets import load_boston
boston = load_boston()
data = pd.DataFrame(boston.data)
data.columns = boston.feature_names
X, y = data.iloc[:,:-1],data.iloc[:,-1]
xg_reg = xgb.XGBRegressor(objective ='reg:squarederror', colsample_bytree = 0.3, learning_rate = 0.1, max_depth = 5, alpha = 10, n_estimators = 10)
xg_reg.fit(X,y)
preds = xg_reg.predict(X)
rmse = np.sqrt(mean_squared_error(y, preds))
print("RMSE: %f" % (rmse))
```
Following warning is received: 
```
~venv/lib64/python3.6/site-packages/xgboost/data.py:115: UserWarning: Use subset (sliced data) of np.ndarray is not recommended because it will generate extra copies and increase memory consumption
  "memory consumption")
```

**Comment by hcho3** [comment]
This is expected behavior, since you are using a sliced array (`data.iloc[:,:-1]`) as an input to `DMatrix`. The program will work; just keep in mind that the array will be copied and load to increased memory usage.

**Comment by JoseLlorensRipolles** [comment]
Hey @sheecegardezi , 

Althought this issue is closed, I thought I would add that you can make the array contiguous with 
`X = np.ascontiguousarray(X)`
Which will improve memory usage and avoid the warning. 

Would you consider adding this fix for uncontiguous arrays to XGboost @hcho3?  I would like to do it if so. Thank you very much in advance.

**Comment by GiuseppeLaurenza** [comment]
> Hey @sheecegardezi ,
> 
> Althought this issue is closed, I thought I would add that you can make the array contiguous with
> `X = np.ascontiguousarray(X)`
> Which will improve memory usage and avoid the warning.

Hi, it something to do with our data or a modification that XGBoost should do?

**Comment by rteuwens** [comment]
I know for a fact my own code is not slicing any numpy arrays, but my terminal is being inundated with this `UserWarning ` message, nonetheless. I am, however, using xgboost in conjunction with sklearn's SearchCV methods, making use of the [TimeSeriesSplit](https://github.com/scikit-learn/scikit-learn/blob/15a949460dbf19e5e196b8ef48f9712b72a3b3c3/sklearn/model_selection/_split.py#L735) class for the CV (an operation which is quite common).

This one, as expected, is the culprit and is yielding the sliced array xgboost is warning about:
https://github.com/scikit-learn/scikit-learn/blob/15a949460dbf19e5e196b8ef48f9712b72a3b3c3/sklearn/model_selection/_split.py#L881-L888

Attempts to suppress the warning have, thus far, also been unsuccessful.

Given how common the interaction is with the sklearn library, is there a way to address this?
Is there perhaps a fix out there already?

**Comment by trivialfis** [comment]
I plan to use array interface for numpy array inputs, through which we can reliable consume sliced data.

**Comment by hcho3** [comment]
@trivialfis Do you need some help with this?

**Comment by trivialfis** [comment]
@hcho3 Feel free to work on it.  We have in place predict that accepts numpy array interface, the DMatrix csr ctor is also using it.

**Comment by JoseLlorensRipolles** [comment]
> Hi, it something to do with our data or a modification that XGBoost should do?

Something you have to do with your data. The warning is right, if you pass a non-contiguous array, xgboost makes a contiguous copy of it (increasing the memory needed), while if your array is contiguous from the beginning, the copy is not needed ([data.py](https://github.com/dmlc/xgboost/blob/e41619b1fc6152d4392896c6caf9a0dc960c5558/python-package/xgboost/data.py#L118)). Everything will work fine, it is just a heads up that extra memory will be used.

Try converting your arrays before using them. For example: 

X_test = np.ascontiguousarray(X_test)
preds = xg_reg.predict(X_test)

Or 

X_train =  np.ascontiguousarray(X_train)
y_train = np.ascontiguousarray(y_train)
xg_reg.fit(X_train,y_train)

Depending on were you have the error.
