### ISSUE TITLE
`XGBoostError: XGBoost Library (libxgboost.dylib) could not be loaded` on Apple Silicon (ARM)

### ISSUE THREAD

**Issue by clstaudt** [dmlc/xgboost#6909]
While `>pip install xgboost` works without error, the installation is broken. Note the following part of the error message:

`Did find:\n\t/Users/cls/miniforge3/envs/packaging-measurement/lib/python3.8/site-packages/xgboost/lib/libxgboost.dylib: mach-o, but wrong architecture`

```
iPython 3.8.8 | packaged by conda-forge | (default, Feb 20 2021, 15:50:57) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.22.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import xgboost
---------------------------------------------------------------------------
XGBoostError                              Traceback (most recent call last)
<ipython-input-1-e528dc1a32ff> in <module>
----> 1 import xgboost

~/miniforge3/envs/packaging-measurement/lib/python3.8/site-packages/xgboost/__init__.py in <module>
      7 import os
      8 
----> 9 from .core import DMatrix, DeviceQuantileDMatrix, Booster
     10 from .training import train, cv
     11 from . import rabit  # noqa

~/miniforge3/envs/packaging-measurement/lib/python3.8/site-packages/xgboost/core.py in <module>
    193 
    194 # load the XGBoost library globally
--> 195 _LIB = _load_lib()
    196 
    197 

~/miniforge3/envs/packaging-measurement/lib/python3.8/site-packages/xgboost/core.py in _load_lib()
    176     if not lib_success:
    177         libname = os.path.basename(lib_paths[0])
--> 178         raise XGBoostError(
    179             'XGBoost Library ({}) could not be loaded.\n'.format(libname) +
    180             'Likely causes:\n' +

XGBoostError: XGBoost Library (libxgboost.dylib) could not be loaded.
Likely causes:
  * OpenMP runtime is not installed (vcomp140.dll or libgomp-1.dll for Windows, libomp.dylib for Mac OSX, libgomp.so for Linux and other UNIX-like OSes). Mac OSX users: Run `brew install libomp` to install OpenMP runtime.
  * You are running 32-bit Python on a 64-bit OS
Error message(s): ['dlopen(/Users/cls/miniforge3/envs/packaging-measurement/lib/python3.8/site-packages/xgboost/lib/libxgboost.dylib, 6): no suitable image found.  Did find:\n\t/Users/cls/miniforge3/envs/packaging-measurement/lib/python3.8/site-packages/xgboost/lib/libxgboost.dylib: mach-o, but wrong architecture\n\t/Users/cls/miniforge3/envs/packaging-measurement/lib/python3.8/site-packages/xgboost/lib/libxgboost.dylib: mach-o, but wrong architecture']
```

**Comment by hcho3** [comment]
As the wheel filename `xgboost-1.4.1-py3-none-macosx_10_14_x86_64.macosx_10_15_x86_64.macosx_11_0_x86_64.whl`, we currently only supports MacOS with x86_64 CPU architecture. Apple Silicon is not supported. See #6408

**Comment by hcho3** [comment]
Try:
```
pip install xgboost --no-binary xgboost
```

**Comment by cb0207** [comment]
@hcho3 can build XGBoost successfully by
```
pip install xgboost --no-binary xgboost -v
```
Import xgboost well also, let you know if any further issue. 👍 

env:
- python 3.9.6
- macOS 12.0

**Comment by hassaanhameed786** [comment]
same issue after trying this 
`pip install xgboost --no-binary xgboost -v`



XGBoostError: 
XGBoost Library (libxgboost.dylib) could not be loaded.
Likely causes:
  * OpenMP runtime is not installed
    - vcomp140.dll or libgomp-1.dll for Windows
    - libomp.dylib for Mac OSX
    - libgomp.so for Linux and other UNIX-like OSes
    Mac OSX users: Run `brew install libomp` to install OpenMP runtime.

  * You are running 32-bit Python on a 64-bit OS

Error message(s): ["dlopen(/Users/muhammadhassaan/Downloads/Da

**Comment by hcho3** [comment]
@hassaanhameed786 Please install the OpenMP runtime by running `brew install libomp`.

**Comment by hassaanhameed786** [comment]
@hcho3  yes i tried to install `libomp` solved` by following this 
`!conda install -c conda-forge py-xgboost -y`

[https://stackoverflow.com/questions/65752489/error-when-importing-xgboost-on-apple-m1](url)

**Comment by hcho3** [comment]
@hassaanhameed786 What kind of environment are you using? Are you using a Jupyter notebook? Are you using Conda? Try to provide as much information as you can.

**Comment by harishankar-bcindia** [comment]
100 % this will work for Mac users:
brew install libomp

**Comment by Karashan** [comment]
`conda install py-xgboost` solved this problem for me. The pip version (2.1.1) would just introduce this error to my virtual environment under MacOS 15.0.1 (M1 Pro chip).

**Comment by ifeanyiokpala** [comment]
brew install libomp is not working on my Mac m2. zsh: command not found: brew

**Comment by ifeanyiokpala** [comment]
Sorted! I think my brew was in a different path.
if anyone is having such challenge try this: 

export PATH=/opt/homebrew/bin:$PATH

**Comment by LucaMatarazzo** [comment]
> 100 % this will work for Mac users: brew install libomp

This does not work for me. I installed xbgoost using `pip install xgboost`, then I ran `brew install libomp`, but whenever I try to import I still get

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/[...]/.venv/lib/python3.9/site-packages/xgboost/__init__.py", line 6, in <module>
    from . import tracker  # noqa
  File "/Users/[...]/.venv/lib/python3.9/site-packages/xgboost/tracker.py", line 9, in <module>
    from .core import _LIB, _check_call, make_jcargs
  File "/Users/[...]/.venv/lib/python3.9/site-packages/xgboost/core.py", line 269, in <module>
    _LIB = _load_lib()
  File "/Users/[...]/.venv/lib/python3.9/site-packages/xgboost/core.py", line 222, in _load_lib
    raise XGBoostError(
xgboost.core.XGBoostError: 
XGBoost Library (libxgboost.dylib) could not be loaded.
Likely causes:
  * OpenMP runtime is not installed
    - vcomp140.dll or libgomp-1.dll for Windows
    - libomp.dylib for Mac OSX
    - libgomp.so for Linux and other UNIX-like OSes
    Mac OSX users: Run `brew install libomp` to install OpenMP runtime.

  * You are running 32-bit Python on a 64-bit OS

Error message(s): [ [...]
Reason: tried: '/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file), '/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file)"]`

I am on MacOS 15.0, using a M3 Pro chip. I am working inside a venv and cannot use conda to install.

**Comment by leduy-it** [comment]
> > 100 % this will work for Mac users: brew install libomp
> 
> This does not work for me. I installed xbgoost using `pip install xgboost`, then I ran `brew install libomp`, but whenever I try to import I still get
> 
> ```
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/[...]/.venv/lib/python3.9/site-packages/xgboost/__init__.py", line 6, in <module>
>     from . import tracker  # noqa
>   File "/Users/[...]/.venv/lib/python3.9/site-packages/xgboost/tracker.py", line 9, in <module>
>     from .core import _LIB, _check_call, make_jcargs
>   File "/Users/[...]/.venv/lib/python3.9/site-packages/xgboost/core.py", line 269, in <module>
>     _LIB = _load_lib()
>   File "/Users/[...]/.venv/lib/python3.9/site-packages/xgboost/core.py", line 222, in _load_lib
>     raise XGBoostError(
> xgboost.core.XGBoostError: 
> XGBoost Library (libxgboost.dylib) could not be loaded.
> Likely causes:
>   * OpenMP runtime is not installed
>     - vcomp140.dll or libgomp-1.dll for Windows
>     - libomp.dylib for Mac OSX
>     - libgomp.so for Linux and other UNIX-like OSes
>     Mac OSX users: Run `brew install libomp` to install OpenMP runtime.
> 
>   * You are running 32-bit Python on a 64-bit OS
> 
> Error message(s): [ [...]
> Reason: tried: '/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file), '/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file)"]
> ```
> 
> I am on MacOS 15.0, using a M3 Pro chip. I am working inside a venv and cannot use conda to install.
> 
> **EDIT**: solved, the problem was I originally installed homebrew with Rosetta active in the terminal, hence it was saving the dynamic library in the wrong location (`/usr/local/opt/` instead of `/opt/homebrew/opt/`). To solve I simply uninstalled homebrew, deactivated Rosetta from terminal (search for terminal app in finder, click and press cmd+I, untick "Open using Rosetta") and then reinstalled homebrew. Then, running `brew install libomp` solves the issue.

you save my day. I forgot the problem that I turned on the Rosseta mode.

**Comment by johnstan** [comment]
> `conda install py-xgboost` solved this problem for me. The pip version (2.1.1) would just introduce this error to my virtual environment under MacOS 15.0.1 (M1 Pro chip).

This solved it for me too!

**Comment by devOzdemir** [comment]
`pip install xgboost ` and `brew install libomp` worked for me on my m4 pro mac, jupyter notebook
