### ISSUE TITLE
xgboost is not learning.

### ISSUE THREAD

**Issue by Foreist** [dmlc/xgboost#6910]
![image](https://user-images.githubusercontent.com/46616734/116376845-9756e500-a84b-11eb-81e4-a52a46ddf1e2.png)

Even if you search for an error, nothing is found.
The version is 1.4.1.
Is it a bug?

**Comment by Foreist** [comment]
I installed xgboost with pip, but the pass comes out as conda.

**Comment by Foreist** [comment]
Moved libxgboost from pip path to conda.

**Comment by trivialfis** [comment]
Maybe cleaning up the environment can help.
