### ISSUE TITLE
R documentation hasn't been updated in 1.4.1.1?

### ISSUE THREAD

**Issue by ReeceGoding** [dmlc/xgboost#6914]
A number of edits have been made to the R documentation in the past month or so. However, the only changes that I can find on either [the pdf on CRAN](https://cran.r-project.org/web/packages/xgboost/xgboost.pdf) or the documentation on my own 1.4.1.1 installation are updates to the upload dates and version numbers. I cannot, for example, find [March 19th's documentation changes](https://github.com/dmlc/xgboost/commit/c2b6b806004d6ecf4ad4c25229bb8e426833cfba).

Is this my misunderstanding of the versioning or do we have some sort of build problem?

**Comment by hcho3** [comment]
See #6915
