### ISSUE TITLE
n_thread not working 

### ISSUE THREAD

**Issue by 1a1a11a** [dmlc/xgboost#6916]
Hi there, 
     This is a great repo! I am following the C API and tutorial and I try to set the number of threads to 1 with ` safe_call(XGBoosterSetParam(learner->booster, "nthread", "1"));` but it still uses all the cores, I do not see anything wrong, I have attached my code, can you help me with it? 

```
  safe_call(XGBoosterSetParam(booster, "booster", "gbtree"));
  safe_call(XGBoosterSetParam(booster, "nthread", "1"));
  safe_call(XGBoosterSetParam(booster, "objective", "reg:squarederror"));


  for (int i = 0; i < N_TRAIN_ITER; ++i) {
    safe_call(XGBoosterUpdateOneIter(booster, i, train_dm));
  }
```

Thank you!

**Comment by trivialfis** [comment]
Could you please attach a more self-contained code example?  The use of thread might be coming from the creation of DMatrix instead of training.

**Comment by 1a1a11a** [comment]
Hi @trivialfis, thank you for you reply! This is very helpful! I looked into the places where it could have use multiple threads, and I notice that when predict, it uses the max number of threads (https://github.com/dmlc/xgboost/blob/a2ecbdaa31d6850ed7343d2fc4e11d21b6582745/src/predictor/cpu_predictor.cc#L184) 
now I set the environment `OMP_NUM_THREADS` and make it to use one thread. :)

**Comment by trivialfis** [comment]
Hmm .. no, if you have specified `nthread`, xgboost calls `omp_set_num_threads` so `omp_get_max_threads` will return 1.

**Comment by 1a1a11a** [comment]
Thank you! Let me try to make a minimal example in the next few days and see what I did wrong.

**Comment by trivialfis** [comment]
Closing due to stalled.
