### ISSUE TITLE
Order of dumped trees for multi class models

### ISSUE THREAD

**Issue by ashish01** [dmlc/xgboost#692]
XGBoost is great. Thanks for creating this amazing piece of software. I am trying to create a lean runtime which reads the dumped text model and then produces the same 1:1 output for predict_proba. In this context I have a few questions

* For multi class classification (with say n_classes = 5, num_rounds = 100) dumped model contains 500 boosters. Probably 100 boosters per class. What is the order in which they are dumped? Are boosters for same class printed contagiously? Something like (class_0_booster_0), (class_0_booster_1),... (class_0_booster_99),... (class_1_booster_0),   

* Parsing the text model is not very hard and we can represent a booster with this tree data structure

````python
class Node:
    def eval(self, features):
        if self.isLeaf:
            return self.threshold
        else:
            if features[self.feature] < self.threshold:
                return self.children[0].eval(features)
            else:
                return self.children[1].eval(features)
````

This of course assumes that features is a dense vector with no missing values. Is the code correctly calculating the output of single booster given features?

* Once we have all the boosters loaded is the final score just sum of all the individual boosters

````python
class Classifier:
    def eval(self, features):
        result = self.bias
        for booster in self.boosters:
            result += booster.eval(features)
        return result
````
This this code correctly calculating the final value of the classifier?

* Is the value of the bias printed anywhere in the dumped model?

**Comment by tqchen** [comment]
- The order of booster, is  (class_0_booster_0), (class_1_booster_0), ...
- The formula you used is correct
