### ISSUE TITLE
how can i install xgboost if my gcc complier dont support c++14?

### ISSUE THREAD

**Issue by nickhuangxinyu** [dmlc/xgboost#6921]
Hi, thanks for your attention.

I read the doc, it tolds me install command is:

```
git clone ....
make -j4
```

but for some reasons, i cant use c++14 in my server(c++11 is ok)

how can i install its old version?

can you list the command?

Thanks very much!

**Comment by trivialfis** [comment]
Use a package manager like conda that are mostly self-contained.

**Comment by trivialfis** [comment]
The latest xgboost package on conda is still 1.3.3.  1.4 hasn't been merged yet: https://github.com/conda-forge/xgboost-feedstock/pull/73  But you can build XGBoost by yourself using compilers from conda.

Also, there's a rapidsai distribution of XGBoost: https://anaconda.org/rapidsai/rapids-xgboost which is close to 1.4
