### ISSUE TITLE
there is a way that can convert dump_model file to The structure of trees

### ISSUE THREAD

**Issue by Pacerzhujiang0112** [dmlc/xgboost#6924]
I saw your work about #3291, I want to know there is a way that can convert dump_model file to The structure of trees?

**Comment by hcho3** [comment]
It was a small prototype that I made a while back and is very much incomplete. In general, it's best to always keep the original model file and not rely on the output of dump_model.

**Comment by Pacerzhujiang0112** [comment]
> It was a small prototype that I made a while back and is very much incomplete and nonfunctional. That's why the experimental feature was removed from the latest Treelite, as I couldn't get it to work well enough. In general, it's best to always keep the original model file and not rely on the output of dump_model.

OK，thanks a lot，your work is great！

**Comment by trivialfis** [comment]
You can consider the JSON model: https://github.com/dmlc/xgboost/tree/master/demo/json-model .
