### ISSUE TITLE
Bug in XGBoost >=1.4: Check failed: typestr.size() == 3 (2 vs. 3) 

### ISSUE THREAD

**Issue by kyleengel** [dmlc/xgboost#6925]
I ran into this error and found a slackoverflow post on the topic: https://stackoverflow.com/questions/67095097/xgboosterror-check-failed-typestr-size-3-2-vs-3-typestr-should-be

I haven't done much digging but it looks like it has to do with macOS Big Sur, using XGBoost in a sklearn `Pipeline`, and XGBoost version >= 1.4.

**Comment by trivialfis** [comment]
It's an error parsing numpy array interfaec: https://numpy.org/doc/stable/reference/arrays.interface.html .  Not sure which data part returns a wrong `typestr`.  It's required to have 3 characters.  It would be great to have a reproducible example.

**Comment by trivialfis** [comment]
@kyleengel Could you please share an example script that we can run?  I tried to complete the snippets from SO but couldn't reproduce the issue.  Also, it would be great to have versions of numpy and pandas.

**Comment by kyleengel** [comment]
Sure, no problem. I did a little bit of digging and it's related to `bool` column(s) in the design matrix. It seems like `bool` columns were acceptable pre-1.4, but no longer after 1.4.

Here are my installed versions:
* Pandas: `1.2.3`
* Numpy: `1.20.2`
* XGBoost: `1.4.1`

I'm running on Mac OS but I can also reproduce on Ubuntu 18.04.

Here's a reproducible example:

```python
# Reproducible example for https://github.com/dmlc/xgboost/issues/6925
import pandas as pd
import xgboost as xgb
from sklearn.datasets import make_classification


# Create a fake multi-class classification dataset
n_classes = 4
X, y = make_classification(n_samples=1000, n_features=20, n_informative=8, n_classes=n_classes, random_state=420)
X = pd.DataFrame(X, columns=[f"feature_{i}" for i in range(X.shape[1])])

# Default classifier
clf = xgb.XGBClassifier(use_label_encoder=False)

# This works
clf.fit(X, y, eval_metric="mlogloss")
_ = clf.predict_proba(X)

# Adding a bool feature results in the error
X_with_bool = X.copy()
X_with_bool.loc[:, "bool_feature"] = X_with_bool.loc[:, "feature_0"] > 0
clf.fit(X_with_bool, y, eval_metric="mlogloss")

try:
    clf.predict_proba(X_with_bool)
except xgb.core.XGBoostError as e:
    print(e)

# Converting to numpy will result in the same error
X_numpy_with_bool = X_with_bool.to_numpy()  # the numpy array is dtype=object because of mixed types now
clf.fit(X_numpy_with_bool, y, eval_metric="mlogloss")

try:
    clf.predict_proba(X_numpy_with_bool)
except xgb.core.XGBoostError as e:
    print(e)


# Forcing all types to be float fixes the bug
X_numpy_all_float = X_numpy_with_bool.astype(float)
X_pandas_all_float = X_with_bool.astype(float)

# Numpy X
clf.fit(X_numpy_all_float, y, eval_metric="mlogloss")
_ = clf.predict_proba(X_numpy_all_float)

# Pandas X
clf.fit(X_pandas_all_float, y, eval_metric="mlogloss")
_ = clf.predict_proba(X_numpy_all_float)
```

**Comment by trivialfis** [comment]
Thanks, that's super helpful.  Created a PR https://github.com/dmlc/xgboost/pull/6927 with explanation for the error.
