### ISSUE TITLE
xgboost cannot recognize alternative installations of libomp

### ISSUE THREAD

**Issue by aeftimia** [dmlc/xgboost#6931]
Homebrew generally needs admin privileges to be installed and while most packages, including libomp, can be installed manually, xgboost has no way to recognize alternative installations. This means xgboost in its current form cannot be used on a mac without admin privileges.

**Comment by FelixYBW** [comment]
Did you try to set LD_LIBRARY_PATH or even LD_PRELOAD? it looks not xgboost's issue, it's how dynamic library is loaded.

**Comment by aeftimia** [comment]
I was able to fix the issue with install_name_tool What should I be doing with LD_LIBRARY_PATH and LD_PRELOAD? I did some googling, but it's not obvious how to use them. I'm currently trying to reinstall xgboost with LD_LIBRARY_PATH set to my custom lib location (it was not set before). I'm still not sure how to use LD_PRELOAD. Could you post an example?

**Comment by trivialfis** [comment]
Maybe you can consider using conda?  OpenMP is a language, switching its standard library can be tricky.

Maybe @hcho3 has better insight on Mac.

**Comment by trivialfis** [comment]
I think it's best to avoid pulling this kind of trick.

**Comment by hcho3** [comment]
Yes, if you do not have an admin privilege, it's best to install XGBoost using Conda:
```
conda install -c conda-forge py-xgboost
```
