### ISSUE TITLE
[XGBoost4J-Spark] Reason why spark_xgboost must evaluate training dataset?

### ISSUE THREAD

**Issue by FelixYBW** [dmlc/xgboost#6932]
From current Spark code (Flink does this also), the training process will evaluate the training dataset alwasy no matter we enable earlyStop or evaluation or not. Does it impact the training process? I didn't see this happenned on dask distributed training by default.

 SXGBoost.trainAndSaveCheckpoint(  **watchesmap("train")**, params, numRounds, **watchesmap**, metrics, obj, eval,
          earlyStoppingRound = numEarlyStoppingRounds, prevBooster, externalCheckpointParams)

@hcho3 any insight?

**Comment by trivialfis** [comment]
I'm open to having it as optional, could you please open a PR?

**Comment by FelixYBW** [comment]
Sure.
