### ISSUE TITLE
xgboost python and R outputs differ when sampling hyperparameters are introduced

### ISSUE THREAD

**Issue by jyk4100** [dmlc/xgboost#6941]
Hello

I get identical predicted probabilities from xgboost classifiers trained on same data and same hyperparameters on R and Python. However, when sampling related hyperparameters are added, I start to see that output differs.

**settings**
- windows machine
- python 3.8.3 (anaconda distribution) & xgboost 1.4.1
- R 4.0.2 & xgboost_1.4.1.1

**R code**
```
iris = fread("https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv")
iris[, c("class") := ifelse(iris$species == "setosa", 1, 0)] ## create dummy class

## define and train model
set.seed(123)
model = xgboost(data=data.matrix(iris[, c("sepal_length", "sepal_width", "petal_length", "petal_width")]),
                label=train$class, verbose=0, 
                objective="binary:logistic", tree_method="approx", scale_pos_weight=1,
                nround=10, eta=0.3, gamma=5, max_depth=6, min_child_weight=1, lambda=0.5, alpha=0.5, 
                sampling_method="uniform", colsample_bytree=1.0, subsample=1.0)

## tabulate predictions
preds = round(predict(model, data.matrix(iris[, c("sepal_length", "sepal_width", "petal_length", "petal_width")])), 5)
table(preds)
```

**Python code**
```
iris = pd.read_csv("https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv")
iris['class'] = iris['species'].apply(lambda x: 1 if x == 'setosa' else 0) ## toy example

## define and train model
features = ["sepal_length", "sepal_width", "petal_length", "petal_width"]
param = {'objective': 'binary:logistic', 'tree_method':'approx','scale_pos_weight':1,
         'n_estimators':10, 'eta':0.3, 'gamma':5, 'random_state':123, 
         'max_depth':6, 'min_child_weight':1, 
         'reg_lambda':0.5, 'reg_alpha':0.5,
         'sampling_method':'uniform', 'colsample_bytree':1.0, 'subsample':1.0}
model = XGBClassifier(**param)
model.fit(iris[features].values, iris['class'])

## tabulate predicted prob
preds = pd.Series(model.predict_proba(iris[features].values)[:,1]).round(5)
preds.astype(str).value_counts()
```

With the above code snipet, colsample_bytree and subsample is set to 1.0. There is no sampling and R and Python model outputs are consistent. 

**R (colsample_bytree=1.0, subsample=1.0)**
```
> table(preds)
preds
0.03662 0.95171 
    100      50 
```
**Python (colsample_bytree=1.0, subsample=0.8)**
```
0.03662    100
0.95171     50
dtype: int64
```

However, once I start to set non default, less than 1 values, for the sampling hyperparameters, I see outputs differ. For example, when I change colsample_bytree to 0.7 only (keeping other parameters same) I get different results as below.

**R (colsample_bytree=0.7, subsample=1.0)**
```
0.04464 0.07019 0.09411 0.15894 0.85324 0.88889 0.93571 
     90       3       6       1       5       1      44 
```
**Python (colsample_bytree=0.7, subsample=1.0)**
```
0.0369     93
0.95078    45
0.06652     7
0.91216     5
```
Not sure if such is expected behavior or not. I updated my xgboost packages to 1.4.1 to rule out version and machine issue. I tested and saw similar patterns compare outputs from xgboost 1.3.1 on  R/windows and xgboost 1.2.1 on Python/Unix.

adding another example,

**R (colsample_bytree=1.0, subsample=0.8)**
```
0.04696 0.93423 
    100      50 
```
**Python (colsample_bytree=1.0, subsample=0.8)**
```
0.0448     99
0.93084    50
0.07157     1
```

**Comment by trivialfis** [comment]
The R package uses random engine from R runtime, other packages use rng from c++ standard library.
