### ISSUE TITLE
How to change DMLC_TRACKER_PORT=9092 in code ？

### ISSUE THREAD

**Issue by HenryBao91** [dmlc/xgboost#6943]
I want to use the popular one pipine，that XGBoost + LR . And  my compute engine is  Spark 2.4.3 . I used `ml.dmlc.xgboost4j.scala.spark._`  . But I meet a difficult problem， below this:

`Tracker started, with env={DMLC_NUM_SERVER=0, DMLC_TRACKER_URI=10.10.20.153, DMLC_TRACKER_PORT=9092, DMLC_NUM_WORKER=2}`

When my xgboost code runs on Spark Cluster,  the DMLC_TRACKER_PORT is 9092 which is conflict with my kafka cluster communication port 9092， so it came to errors. I can't  find any  papers about how to solve this problem.I find where is a python file： track.py  in  `xgboost4j_2.11-1.0.0.jar`， I can rewrite this file . But when I run `sbt assembly` to build my project， it still runs on DMLC_TRACKER_PORT=9092 . I think  we can  change this  port  in code settings， But I don't know how to realize it. I need help. By the way ：
```
Spark=2.4.3
Scala=2.11.8
xgboost4j-spark=1.0.0
```
Errors ：
```
[root@test]# sh xgbDemo.sh
WARN	2021-05-06 16:04:09,937	1	org.apache.spark.SparkConf	[main]	The configuration key 'spark.yarn.executor.memoryOverhead' has been deprecated as of Spark 2.3 and may be removed in the future. Please use the newkey 'spark.executor.memoryOverhead' instead.
dataSet size is : 10000
Tracker started, with env={DMLC_NUM_SERVER=0, DMLC_TRACKER_URI=10.66.120.15, DMLC_TRACKER_PORT=9092, DMLC_NUM_WORKER=2}
retry connect to ip(retry time 1): [10.66.120.15]
retry connect to ip(retry time 1): [10.66.120.15]
retry connect to ip(retry time 2): [10.66.120.15]
retry connect to ip(retry time 2): [10.66.120.15]
retry connect to ip(retry time 3): [10.66.120.15]
retry connect to ip(retry time 3): [10.66.120.15]
retry connect to ip(retry time 4): [10.66.120.15]
retry connect to ip(retry time 4): [10.66.120.15]

connect to (failed): [10.66.120.15]
Socket Connect Error:Connection refused, rabit is configured to keep process running
failed in ReconnectLink Socket Connect Error:Connection refused
ERROR	2021-05-06 16:04:46,170	36234	XGBoostSpark	[Executor task launch worker for task 40]	XGBoosterworker 0 has failed 0 times due to
ml.dmlc.xgboost4j.java.XGBoostError:
	at ml.dmlc.xgboost4j.java.Rabit.checkCall(Rabit.java:53)
	at ml.dmlc.xgboost4j.java.Rabit.init(Rabit.java:75)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.ml$dmlc$xgboost4j$scala$spark$XGBoost$$buildDistributedBooster(XGBoost.scala:361)
at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$16.apply(XGBoost.scala:468)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$16.apply(XGBoost.scala:461)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:801)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:801)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD$$anonfun$7.apply(RDD.scala:337)
	at org.apache.spark.rdd.RDD$$anonfun$7.apply(RDD.scala:335)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1165)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1156)
	at org.apache.spark.storage.BlockManager.doPut(BlockManager.scala:1091)
	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1156)
	at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:882)
	at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:335)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:286)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by trivialfis** [comment]
@wbo4958 might have some insight.

**Comment by HenryBao91** [comment]
> @wbo4958 might have some insight.

Really ？This problem has been bothering me for a long time. @wbo4958  Have you meet this problem ? Could you give me some methods to solve this problem ? Thank you very much . I'm looking forward to your reply.

**Comment by wbo4958** [comment]
Seems there is not an easy way to change it like a parameter thing, but you can change it in your code, see here https://github.com/dmlc/dmlc-core/blob/main/tracker/dmlc_tracker/tracker.py#L141 .

but interesting, the code tries to bind the port from 9091. if the port is occupied, it will try to bind next port. 
``` python
        for port in range(port, port_end):
            try:
                sock.bind((hostIP, port))
                self.port = port
                break
            except socket.error as e:
                if e.errno in [98, 48]:
                    continue
                else:
                    raise
```

**Comment by HenryBao91** [comment]
> Seems there is not an easy way to change it like a parameter thing, but you can change it in your code, see here https://github.com/dmlc/dmlc-core/blob/main/tracker/dmlc_tracker/tracker.py#L141 .
> 
> but interesting, the code tries to bind the port from 9091. if the port is occupied, it will try to bind next port.
> 
> ```python
>         for port in range(port, port_end):
>             try:
>                 sock.bind((hostIP, port))
>                 self.port = port
>                 break
>             except socket.error as e:
>                 if e.errno in [98, 48]:
>                     continue
>                 else:
>                     raise
> ```


Thank you for your reply. I find this，I have two  bigdata cluster，I run my code on the a cluster， DMLC_TRACKER_PORT=9097， but  on the b cluster，DMLC_TRACKER_PORT=9092， then it come to errors. When  9092 port  is occupied， it doesn't try to bind next port but try again this port.  I find this python file： track.py in `xgboost4j_2.11-1.0.0.jar` ， but I code with Scala. Even though I change it in   `xgboost4j_2.11-1.0.0.jar`  ，then  I run  `sbt assembly`  to build and package my project， it will re-download the jar.  I  don't  know what should  I do.  Please help me. Thanks

**Comment by wbo4958** [comment]
So you mean you have the XGBoost source code, and you want to change the python code and compile your own jars? If yes,

You need to run the below commands firstly

``` console
git submodule init
git submodule update
```
and you can change the code in dmlc-core/tracker/dmlc_tracker/tracker.py and then compile the xgboost. You can refer to this page https://xgboost.readthedocs.io/en/latest/build.html

**Comment by HenryBao91** [comment]
> So you mean you have the XGBoost source code, and you want to change the python code and compile your own jars? If yes,
> 
> You need to run the below commands firstly
> 
> ```
> git submodule init
> git submodule update
> ```
> 
> and you can change the code in dmlc-core/tracker/dmlc_tracker/tracker.py and then compile the xgboost. You can refer to this page https://xgboost.readthedocs.io/en/latest/build.html

Not really.  I can  change  `tracker.py`  in  `xgboost4j_2.11-1.0.0.jar` directly  or change `dmlc-core/tracker/dmlc_tracker/` and compile it. But  I'm not  so understand that  my project is a  spark project  with sbt .  I need to add config in build.sbt :
```
    libraryDependencies ++= Seq(
      "org.apache.spark" %% "spark-core" % "2.4.3"  ,
      "org.apache.spark" %% "spark-sql" % "2.4.3"  ,
      "org.apache.spark" %% "spark-mllib" % "2.4.3" ,
      "ml.dmlc" %% "xgboost4j-spark" % "1.0.0",
      "ml.dmlc" %% "xgboost4j" % "1.0.0)
```
So it'll re-download these xgboost4j-spark jars , what should I do so that I can use the compiled jar in my spark project?
Thanks.

**Comment by wbo4958** [comment]
I mean you need to compile and install your own xgboost jars from source code. then compile your application jars with xgboost dependency. that should work.

**Comment by HenryBao91** [comment]
> I mean you need to compile and install your own xgboost jars from source code. then compile your application jars with xgboost dependency. that should work.

I see. And I‘ll try it.Thank you again.

**Comment by wbo4958** [comment]
I don't thinks this issue is related with tracker PORT.

with the log "Tracker started, with env={DMLC_NUM_SERVER=0, DMLC_TRACKER_URI=10.56.28.15, DMLC_TRACKER_PORT=9092, DMLC_NUM_WORKER=2}", which has indicated that the tracker has binded to 9092 successfully.

**Comment by trivialfis** [comment]
The default port number is changed to 0.  Feel free to reopen if the issue persists.
