### ISSUE TITLE
TypeError: Singleton array array(<xgboost.core.DMatrix object at xxx>, dtype=object) cannot be considered a valid collection

### ISSUE THREAD

**Issue by Alxe1** [dmlc/xgboost#6945]
Use xgboost for grid search, the code is in below:

```
from sklearn.model_selection import GridSearchCV, train_test_split
from xgboost.sklearn import XGBClassifier
import xgboost as xgb

X_train, y_train, X_test, y_test = train_test_split(X, y, test_size=0.3)
d_train = xgb.DMatrix(X_train)

param_list = {'gamma': [0.05, 0.1]}
xgbc = XGBClassifier()
gsearch = GridSearchCV(estimator=xgbc, param_grid= param_list, scoring='roc_auc')

gsearch.fit(d_train, y_train)
```

But in the last step, the error occured: `TypeError: Singleton array array(<xgboost.core.DMatrix object at xxx>, dtype=object) cannot be considered a valid collection`.

the package version:
xgboost=0.82
sklearn=0.20.3
scipy=1.2.1

**Comment by trivialfis** [comment]
Hi, if you are using the sklearn interface, then you don't need to construct `DMatrix` object.
