### ISSUE TITLE
Discrepancy between plot_tree() and get_dump() in splitting conditions

### ISSUE THREAD

**Issue by freeIsa** [dmlc/xgboost#6953]
Hello everyone,
I was looking into a simple XGB regressor I trained, having only binary variables as predictors. I ran  `xgb.get_booster().get_dump()` to get the details about the trees constituting the model, then I used `plot_tree()` on the first tree to visualize it.
When comparing the textual description of the first tree (obtained from `get_dump()`) with the plot, everything was the same, except for the split condition: in the get_dump() output, all conditions were `feature_x < 1 `, whereas in the plot they were rendered as `feature_x < 0.5`.

Of course, being all binary features, the two representations are equivalent, but I found it odd to see this discrepancy.
Is there a reason I am missing for the different representations?
Thanks a lot!

**Comment by freeIsa** [comment]
I tried to produce a minimal example:

```
xgb = XGBRegressor()
xgb.fit(subsample[['var1', 'var2', 'var3', 'var4']], subsample['target'])

model_struct = xgb.get_booster().get_dump() # model representation

tree = 4 # choose one tree in [0, n_estimators-1]
print(model_struct[tree])
plot_tree(xgb, num_trees=tree);
```

using this dummy dataset (`subsample` DataFrame in the above code):

```
   var1  var2  var3  var4    target
0     0     0     0     1  0.229347
1     0     1     0     0  0.169938
2     1     1     1     0  0.564481
3     0     0     1     0  0.129589
4     0     1     0     0  0.128731
5     0     0     0     0  0.180067
6     0     1     0     0  0.456656
7     0     1     1     1  0.085240
8     0     1     1     0  0.133199
9     0     1     0     1  0.136993
```
The output of the print statement is 
```
0:[var1<1] yes=1,no=2,missing=1
	1:[var3<1] yes=3,no=4,missing=3
		3:leaf=-0.0144737167
		4:leaf=-0.0353773832
	2:leaf=0.0050489367
```
and here is the plot:
![xgb_output](https://user-images.githubusercontent.com/61782307/117948787-c2dcd380-b311-11eb-8bcd-520a4d7acbcf.png)

**Comment by trivialfis** [comment]
I will look into it.

**Comment by trivialfis** [comment]
Which version of XGBoost are you using?  I'm running latest xgboost and it works fine.

**Comment by freeIsa** [comment]
I checked, it's version 1.3.3. 
I have just run `pip install --upgrade xgboost`, which installed version 1.4.2, but I still get the same behaviour.

**Comment by trivialfis** [comment]
That's strange.  Could you please try making sure there's no other installation of xgboost in your python `site-packages`, also no other `libxgboost.so` are found?

Here's my code, I just tried to guess it from your snippet.  Feel free to point it out if it doesn't match yours.
``` python
import numpy as np
import pandas as pd
import xgboost as xgb
from matplotlib import pyplot as plt

data = [
    0,    0,     0,     1,  0.229347,
    0,    1,     0,     0,  0.169938,
    1,    1,     1,     0,  0.564481,
    0,    0,     1,     0,  0.129589,
    0,    1,     0,     0,  0.128731,
    0,    0,     0,     0,  0.180067,
    0,    1,     0,     0,  0.456656,
    0,    1,     1,     1,  0.085240,
    0,    1,     1,     0,  0.133199,
    0,    1,     0,     1,  0.136993,
]

array = np.asarray(data).reshape(10, len(data) // 10)
subsample = pd.DataFrame(array, columns=["var1", "var2", "var3", "var4", "target"])


reg = xgb.XGBRegressor()
reg.fit(subsample[['var1', 'var2', 'var3', 'var4']], subsample['target'])

model_struct = reg.get_booster().get_dump()  # model representation

tree = 4                        # choose one tree in [0, n_estimators-1]
print(model_struct[tree])
xgb.plot_tree(reg, num_trees=tree)
plt.show()
```

**Comment by freeIsa** [comment]
It looks like it may be a type problem. Running your code as-is in my virtual environment, I get the same result from plot_tree and from the print statement (i.e. splitting condition set to 0.5). The only difference I could find is that in your code the predictors have `float64` type, whereas in mine they are coded as `uint8`.

**Comment by trivialfis** [comment]
Can you cast the type and try again?

**Comment by trivialfis** [comment]
If it works then feel free to close the issue

**Comment by freeIsa** [comment]
To sum up: I checked that when the input is provided as `uint8`, the result of `reg.get_booster().get_dump()` will display integer split values (e.g. `[var1<1]`); if the same input is provided as `float64`, printing the tree structure will result in float split values (e.g. `[var1<0.5]`). Both ways, the `plot_tree` method will use float split conditions.

In turns, it looks like this is an effect of the `dump_format` parameter in `get_dump()` -- if set to 'text', as per default, integer values are printed; if set to 'dot', as it is when called within `plot_tree()`, float values are printed, so I assume the formatting operation also changes the type of input data in the process.

In my opinion, the results should be coherent across "dump_format" options, but I realize this is not a big deal as both representations are still correct.

**Comment by trivialfis** [comment]
When the input is provided as int, xgboost will recognize it as some kind of discrete value as perform the cast during plot.
