### ISSUE TITLE
xgboost build failed in x86 release

### ISSUE THREAD

**Issue by Livius90** [dmlc/xgboost#6959]
I tried to build c-api demo from master source in x86 release in Visual Studio 2019 cmake in Windows 10, but it seems to me xgboost is not able to build to 32bit (x86) architect config, now. If i start the building in x64 release it works fine. Can you fix the compiler errors in x86 build?

```
Error C2398: Element '4': conversion from 'xgboost::bst_ulong' to 'size_t' requires a narrowing conversion, xgboost\src\c_api\c_api.cc 738	
Error_C2397: conversion from 'uint64_t' to '_Ty' requires a narrowing conversion, xgboost\src\gbm\gbtree.cc 234
```

**Comment by hcho3** [comment]
Feel free to submit a pull request. However, keep in mind that XGBoost does not support 32-bit platforms. That is, we don't run tests for 32-bit platforms.

**Comment by Livius90** [comment]
Ok, a pull request #6964 was made for it and the Jenkins testing has no any failed checking.
