### ISSUE TITLE
Seg Fault when calling fit on XGBClassifier

### ISSUE THREAD

**Issue by mahadafzal** [dmlc/xgboost#6965]
I keep running into Seg Faults when calling fit on an XGBClassifier instance. The inputs are np arrays with the X array being encoded text using a BERT tokenizer. Could someone help me point in the right direction? Thank you!

**Comment by hcho3** [comment]
Can you post your code? Also what is the version of XGBoost you are using?

**Comment by mahadafzal** [comment]
https://github.com/mahadafzal/BERT-XGBoost/blob/2c2eaffba0df2bd9ec0da5a19b4793bc3cd128c0/xgbert.py#L37-L133

I am using version 1.5.2

I've had experience with PyTorch but haven't really used the XGBoost library before, so any help would be much appreciated!

**Comment by hcho3** [comment]
Can you check the dimension of the data array used in XGBClassifier.fit? The crash may be due to running out of memory.

**Comment by mahadafzal** [comment]
It is a 2d array, (4536 x 1), where 4536 is the number of training sentences. I use the same setup with a LinearSVC classifier and it works fine.

**Comment by trivialfis** [comment]
Could you please share the data too?  Maybe with fusing.

**Comment by mahadafzal** [comment]
I am not allowed to share the data publicly, but I was able to solve the issue. It was a preprocessing error on my end causing the program to run out of memory. Thank you for the help!
