### ISSUE TITLE
ia there any way to use gpu for speedup?

### ISSUE THREAD

**Issue by fayeshine** [dmlc/xgboost#697]
can the parallel algorithms port to gpu? do we have any theoretical possibility?

**Comment by damiencarol** [comment]
@fayeshine the library already use OpenMP. Does this lib already use GPU? no ?

**Comment by fayeshine** [comment]
it seems it does not use gpu.
However if it can use openmp, there should be a way to use it on GPU? Am I correct?

**Comment by damiencarol** [comment]
Some resources here : http://stackoverflow.com/questions/28962655/can-openmp-be-used-for-gpus

**Comment by tqchen** [comment]
related to #436
