### ISSUE TITLE
what():  AUC: the dataset only contains pos or neg samples

### ISSUE THREAD

**Issue by mahdiman** [dmlc/xgboost#698]
I'm trying to train a multi-class classifier using xgboost, here is my code:

import numpy as np
import sys
import xgboost as xgb
if **name** == "**main**":

```
if len(sys.argv) < 3:
    print 'Args: '
    print '1- train data'
    print '2- test data'
    exit()

# train
data = np.load(sys.argv[1])
trainF = data['features']
trainL = data['labels']
data.close()

# test
data = np.load(sys.argv[2])
testF = data['features']
testL = data['labels']
data.close()

dtrain = xgb.DMatrix(trainF, label = trainL)
dtest = xgb.DMatrix(testF, label = testL)


param = {'bst:max_depth':2, 'bst:eta':1, 'silent':1, 'objective':'multi:softmax'}
param['num_class'] = 20
param['nthread'] = 2
param['eval_metric'] = 'auc'
evallist  = [(dtest,'eval'), (dtrain,'train')]
num_round = 10
plst = param.items()

bst = xgb.train( plst, dtrain, num_round, evallist)
bst.save_model('0001.model')
```

the trainF and testF are numpy matrices containing feature vectors and trainL and testL are numpy arrays containing labels for train and test, the feature vectors contain only of zeros and ones. can any one tell me why it's wrong to have a dataset of only zeros and ones?

**Comment by tqchen** [comment]
The AUC metric is only designed for binary classifiers
