### ISSUE TITLE
R: xbg + foreach + doParallel

### ISSUE THREAD

**Issue by wingedskull** [dmlc/xgboost#6981]
Hello
Sorry for reporting one more issue, decided no to do it the same day :)
After installing foreach + doParallel trying to run xgboost causes message:
> Parameters: { "maxdepth" } migh... (you know)

**Comment by trivialfis** [comment]
Could you please provide a more detailed setup and an example code that we can debug?

**Comment by wingedskull** [comment]
Hi again
Sending zipped file. Number of loops in it is set to 1 now, so no long runs.
R: a couple of last night builds with gpu support.

xgb was installed first. Then, later - foreach and doParallel through pip. Tried to run - appeared messages.
Re-installed even newer night build for xgb. - Nothing changed. For the moment keeping everything as-is, none of libraries removed till your comments.

Regards
:: The same data file, just in CSV

**Comment by hcho3** [comment]
Are you using e-mail to reply? GitHub ignores e-mail attachments. Please use your web browser to upload files to this issue thread.

**Comment by wingedskull** [comment]
[R-issue.zip](https://github.com/dmlc/xgboost/files/6527246/R-issue.zip)
Here it goes

**Comment by trivialfis** [comment]
I think the correct name of that parameter is `max_depth`, not `maxdepth`.

**Comment by wingedskull** [comment]
Yes. My mistake. But maybe it indicates that its is reasonable to set alias "maxdepth" too?
I guess that I am not the only person writing it this way.
Thanks

**Comment by trivialfis** [comment]
Let's avoid inventing words.  :-). I think the warning is sufficient for now.
