### ISSUE TITLE
can't load dask model from non-dask model

### ISSUE THREAD

**Issue by pseudotensor** [dmlc/xgboost#6991]
Related to https://github.com/dmlc/xgboost/issues/6547 and the related PR: https://github.com/dmlc/xgboost/pull/6582/files, something changed so the code fragment I shared there no longer works.  The shape of predictions gets messed up.

I noticed this: 47b62480af9fefaca3116488c29126265773e2b4 specifically https://github.com/dmlc/xgboost/commit/47b62480af9fefaca3116488c29126265773e2b4#diff-56b261597819799111ec46ab93abbf3532f591a08e0cb40da89b652874b6367eR1801

So models loaded from raw booster lose the n_classes_ attribute.  This leads to no warning or anything, just uses the `_cls_predict_proba()` function with `n_classes_` of None, and then garbage shape of predictions.

A work-around is to load the model and then set model.n_classes_ back to the known value, but seems xgboost should do this.  Also, seems bad to just pass through and get unexpected shape.

I don't think this is related to strict_shape parameter, but I cannot be sure.

FYI @trivialfis

**Comment by trivialfis** [comment]
I tried to come up with a reproducible example by modifying this test: https://github.com/dmlc/xgboost/blob/cf06a266a8256e55a0644ae48d02ce71bb1e020e/tests/python/test_with_dask.py#L1370

So far I can't reproduce your issue.  The following script is modified from the test with `predict` changed to `predict_proba`.

``` python
from sklearn.datasets import load_digits
import xgboost as xgb
import tempfile
import pickle
import os
import numpy as np
from dask import array as da
from distributed import LocalCluster, Client


def main(client):
    X_, y_ = load_digits(return_X_y=True)
    X, y = da.from_array(X_), da.from_array(y_)
    cls = xgb.dask.DaskXGBClassifier(n_estimators=10)
    cls.client = client
    cls.fit(X, y)
    predt_0 = cls.predict_proba(X)

    with tempfile.TemporaryDirectory() as tmpdir:
        path = os.path.join(tmpdir, "model.pkl")
        with open(path, "wb") as fd:
            pickle.dump(cls, fd)

        with open(path, "rb") as fd:
            cls = pickle.load(fd)
        predt_1 = cls.predict_proba(X)
        np.testing.assert_allclose(predt_0.compute(), predt_1.compute())

        path = os.path.join(tmpdir, 'cls.bin')
        cls.save_model(path)

        cls = xgb.dask.DaskXGBClassifier()
        cls.load_model(path)
        assert cls.n_classes_ == 10
        predt_2 = cls.predict_proba(X)

        np.testing.assert_allclose(predt_0.compute(), predt_2.compute())

        # Use single node to load
        cls = xgb.XGBClassifier()
        cls.load_model(path)
        assert cls.n_classes_ == 10
        predt_3 = cls.predict_proba(X_)

        np.testing.assert_allclose(predt_0.compute(), predt_3)


if __name__ == "__main__":
    with LocalCluster() as cluster:
        with Client(cluster) as client:
            main(client)
```

**Comment by pseudotensor** [comment]
The work-around of setting n_classes_ after loading the pickle works fine.

**Comment by trivialfis** [comment]
Do you have a reproducible example?

**Comment by pseudotensor** [comment]
No, but maybe it's related to some other things like the mix between how some things are set, and that ruins things.  Not sure.  Have other issues that are more important, like dask prediction issue: https://github.com/dmlc/xgboost/issues/7004
