### ISSUE TITLE
CPU performance better than GPU 

### ISSUE THREAD

**Issue by superfan123** [dmlc/xgboost#6993]
I use same code/data/KPI and train XGB model, CPU(dual xeon 2690 V3) model perform better than GPU(GTX 1070) in term of GINI. (system is Ubuntu 20.4, XGB is V1.14 from Rapids) 
CPU Gini is 0.30792, GPU Gini is 0.30667. So this is material difference.
I can reproduce my GPU/CPU results with no problem, so both model results are not affected by any system random issue.
Is anybody experience the same issue? 
Also GPU didn't speedup the training at all.
BTW, I also set single_precision_hist to False.

**Comment by trivialfis** [comment]
It depends on the size of your data and inputs.  Would you like to share your datasets so we know where to optimize?

**Comment by superfan123** [comment]
Sorry this is a private dataset. But in general should I expect the CPU and GPU results be same? Or should I use a GPU with ECC memory? I noticed two system can get different results even they run the same dataset and exactly same setting.

**Comment by trivialfis** [comment]
They will have slightly different results due to implementation differences and floating-point errors.

It would still be a great source of info if you can share some properties of your datasets, for example, sparsity, shape.

**Comment by superfan123** [comment]
the dataset has 5 million records with 35 columns. Less than 5 percent missing value and very low sparsity. most of the column are double float.  The difference start right out of the gate from first tree.

**Comment by trivialfis** [comment]
Thanks for sharing, that should be finished within a second right?

**Comment by superfan123** [comment]
No. The GPU will fit the model, just a little bit weak than the CPU fitted model. The GPU model has 108 booster and CPU model has 162 booster.

**Comment by mzq20180601** [comment]
I am facing the same question...

**Comment by trivialfis** [comment]
Small variance in the result is expected due to different hardware instructions and floating point errors.
