### ISSUE TITLE
The algorithm clarification

### ISSUE THREAD

**Issue by sh1ng** [dmlc/xgboost#700]
Hi @tqchen!
It'd be nice for everyone who wants to participate in the project understands technical details of the implementation. May be we should create a wiki page that will give some clues and will help a newcomers easily dive in the project.

I'll start with two questions:
* Why do we delete all data with second derivative equals zero? https://github.com/dmlc/xgboost/blob/master/src/tree/updater_colmaker-inl.hpp#L142
* It always uses sparse matrix implementation even for dense matrices. Doesn't it result in additional overhead?

**Comment by tqchen** [comment]
Sorry for the delayed reply. I like the idea of a wiki page, actually, a discussion thread(issue) and a page in the documentation that links to the issue might be equally good.

To answer your question. The zero derivative normally means it contributes no weight to objective, thus getting deleted, this is more like a protocol callers for outside to "delete" some of the entries.

The special data structure(which is sparse) is needed even for dense matrices for tree construction, so it won't in-ccur additional overhead.
 
There is a cleanup effort on new refactor, which comes with clear docs on all interfaces, hope this helps to make understanding the code and using it easier https://github.com/dmlc/xgboost/tree/brick
