### ISSUE TITLE
CentOS 7 xgboost install error

### ISSUE THREAD

**Issue by mvishruth** [dmlc/xgboost#7008]
while installing install.packages("xgboost") I'm running into this error.

`* installing *source* package ‘xgboost’ ...
** package ‘xgboost’ successfully unpacked and MD5 sums checked
** using staged installation
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking Backtrace lib...
checking for backtrace in -lexecinfo... no
checking endian...
configure: creating ./config.status
config.status: creating src/Makevars
** libs
Makevars:17: -DXGBOOST_STRICT_R_MODE=1
Makevars:17: -DDMLC_LOG_BEFORE_THROW=0
Makevars:17: -DDMLC_ENABLE_STD_THREAD=1
Makevars:17: -DDMLC_DISABLE_STDIN=1
Makevars:17: -DDMLC_LOG_CUSTOMIZE=1
Makevars:17: -DXGBOOST_CUSTOMIZE_LOGGER=1
Makevars:17: -DRABIT_CUSTOMIZE_MSG_
g++ -std=c++11  -I"/opt/R/3.6.3/lib/R/include" -DNDEBUG -I./include -I./dmlc-core/include -I./rabit/include -I. -DXGBOOST_STRICT_R_MODE=1 -DDMLC_LOG_BEFORE_THROW=0 -DDMLC_ENABLE_STD_THREAD=1 -DDMLC_DISABLE_STDIN=1 -DDMLC_LOG_CUSTOMIZE=1 -DXGBOOST_CUSTOMIZE_LOGGER=1 -DRABIT_CUSTOMIZE_MSG_  -I/usr/local/include -fopenmp -DDMLC_CMAKE_LITTLE_ENDIAN=1 -pthread   -O3 -mtune = native -march = native -fPIC -c xgboost_R.cc -o xgboost_R.o
g++: error: =: No such file or directory
g++: error: native: No such file or directory
g++: error: =: No such file or directory
g++: error: native: No such file or directory
g++: error: unrecognized command line option ‘-mtune’; did you mean ‘-mtune=’?
g++: error: unrecognized command line option ‘-march’; did you mean ‘-march=’?
make: *** [/opt/R/3.6.3/lib/R/etc/Makeconf:173: xgboost_R.o] Error 1
ERROR: compilation failed for package ‘xgboost’
* removing ‘/opt/R/3.6.3/lib/R/library/xgboost’
`

**Comment by trivialfis** [comment]
We don't have the `-mtune` nor the `-march` in our compilation flags.  Could you try to find out who's adding those flags?

**Comment by trivialfis** [comment]
Maybe you are adding some environment variables like `CPPFLAGS`.  Try to clear them out.

**Comment by mvishruth** [comment]
@trivialfis how and where should I find the flags to clear them can you help me. the only command i am running is. 
install.packages("xgboost") in R

**Comment by trivialfis** [comment]
Type `env` in your terminal then it will return a list of environment variables.

**Comment by mvishruth** [comment]
MANPATH=/krb5/man:
XDG_SESSION_ID=26989
HOSTNAME=hc9t08474
SELINUX_ROLE_REQUESTED=
TERM=xterm
SHELL=/bin/bash
DISTVER=CentOS7
HISTSIZE=1000
SSH_CLIENT=16.116.142.154 51404 22
VMvendor=vmware
SELINUX_USE_CURRENT_RANGE=
QTDIR=/usr/lib64/qt-3.3
QTINC=/usr/lib64/qt-3.3/include
V1CLOUD=y
SSH_TTY=/dev/pts/0
QT_GRAPHICSSYSTEM_CHECKED=1
HISTFILESIZE=1000
http_proxy=proxy.houston.hpecorp.net:8080
USER=muthyalv
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.axa=01;36:*.oga=01;36:*.spx=01;36:*.xspf=01;36:
TMOUT=7200
MAIL=/var/spool/mail/muthyalv
PATH=/krb5/bin/64:/opt/krb5/sbin/64:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/muthyalv/bin:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.275.b01-0.el7_9.x86_64/jre/bin:/usr/X11R6/bin:/sbin:/usr/sbin:/usr/bin:/opt/pb/bin:/opt/perf/bin:/bin:/usr/local/bin:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.275.b01-0.el7_9.x86_64/jre/bin:/home/muthyalv/.local/bin:/home/muthyalv/bin
PWD=/home/muthyalv
JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.232.b09-0.el7_7.x86_64
LANG=en_US.UTF-8
VERSION=7
SELINUX_LEVEL_REQUESTED=
DISTRO=CENTOS
https_proxy=proxy.houston.hpecorp.net:8080
CLOUD=y
HISTCONTROL=ignoredups
SHLVL=1
HOME=/home/muthyalv
VM=y
DIST=CentOS
LOGNAME=muthyalv
QTLIB=/usr/lib64/qt-3.3/lib
CLASSPATH=.:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.275.b01-0.el7_9.x86_64/jre/jre/lib:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.275.b01-0.el7_9.x86_64/jre/lib:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.275.b01-0.el7_9.x86_64/jre/lib/tools.jar
SSH_CONNECTION=16.116.142.154 51404 16.200.25.36 22
LESSOPEN=||/usr/bin/lesspipe.sh %s
ARCH=x86_64
XDG_RUNTIME_DIR=/run/user/121567889
V2CLOUD=y
COMPANY=HPE
HISTTIMEFORMAT=%Y%m%d-%H%M%S:
_=/usr/bin/env

**Comment by trivialfis** [comment]
Sorry, I can't be sure who's adding those flags in your environment.  You will have to debug it yourself.  If I were you I would try to look at things like which gcc is being invoked, or try to install XGBoost from its repository.

**Comment by trivialfis** [comment]
Also, if the gcc doesn't come from centos, it may be wrapped by another script.

**Comment by mvishruth** [comment]
anybody who has finished installing xgboost on centos7?
