### ISSUE TITLE
[XGBoost4J-Spark] Model trained on Spark has much lower AUC than the one on pandas/dask/modin using some dataset

### ISSUE THREAD

**Issue by FelixYBW** [dmlc/xgboost#7014]
Root cause is still not identified.  But it's not because of null values, because there is no null value in the dataset. missing is set to 0.0.
I encountered the issue on Mortgage (AUC 0.50 vs. 0.92) and RecSys (AUC 0.63 vs. 0.78) dataset. 
Interestingly with our arrow+xgboost optimization, the model is the same as pandas. So it's very possible due to the Sparse vs. Dense data format. 

Does anyone have the same issue?

**Comment by trivialfis** [comment]
@wbo4958 Do you have any insight?

**Comment by FelixYBW** [comment]
It's solved. Spark output probability and prediction but Pandas etc. output probability. I wrongly compare roc_auc_score(prediction) vs. roc_auc_score(probability).  If I compare probability on both side, the score is very close.

probability=df.select(F.col("label"),(vector_to_array("probability")[1]).alias("pred")).toPandas()
