### ISSUE TITLE
xgboost fails with categorical input

### ISSUE THREAD

**Issue by PeiYiTan** [dmlc/xgboost#703]
[cxy.txt](https://github.com/dmlc/xgboost/files/69836/cxy.txt)

Attached data file contains 10,000 observations, and 2 variables: a target Y (0, 1), and a nominal input XC(1, 2, 3,…20).  

I am getting the following errors from xgboost with and without assigning XC as factor.  

traindata<-read.csv("cxy.csv")
y<-traindata[,c("y")]
x<-traindata[,c("xc")]
trainMatrix <- data.matrix(x, rownames.force = NA)
bst<-xgboost(data=trainMatrix, label=y, max.depth=1, eta=0.1, nrounds=1, objective="binary:logistic")
Error in xgb.DMatrix(data, label = label) : 
 REAL() can only be applied to a 'numeric', not a 'integer'

xc<-as.factor(traindata[,c("xc")])
ctrainMatrix <- data.matrix(xc, rownames.force = NA)
bst<-xgboost(data=ctrainMatrix, label=y, max.depth=1, eta=0.1, nrounds=1, objective="binary:logistic")
Error in xgb.DMatrix(data, label = label) : can not open file "1"

**Comment by pommedeterresautee** [comment]
I think you first need to convert your categorical variable in several binary variables for instance by using one hot encoding. You should find code example in the vignettes. Categorical variables are not managed directly by xgboost.

**Comment by PeiYiTan** [comment]
I want to treat the xc as a true categorical variable. I only want to create 1 split from a max.depth=1 tree to see which xc categories are assigned to left or right branch. Can you please show me the work around code that can accomplish what I intend to do?

**Comment by PeiYiTan** [comment]
OK. now I understand xgboost does not handle one single categorical variable with more than 2 categories.
