### ISSUE TITLE
memory is no efficent when I use large feature_index

### ISSUE THREAD

**Issue by listentowindy** [dmlc/xgboost#704]
hi, I use a 10000row data to train gbdt, the max feature index in my file is 2147483647, but there is really less than 1000 feature (my feature is hash by 2147483647, but not start from 1).
But the xgboost use more than 100G memory, just like it is not sparse format. How can I use the sparse format to train my model?

**Comment by pommedeterresautee** [comment]
If you are in R you need to use the Matrix package with a sparse Matrix.

**Comment by listentowindy** [comment]
I use the command line. So what should I do?

**Comment by pommedeterresautee** [comment]
I think LibSVM should be the format to use.
http://xgboost.readthedocs.org/en/latest/input_format.html

**Comment by SantyagoSeaman** [comment]
My current matrix consists of 100K rows and 15K columns of sparse data. dcgMatrix did not created at all. I don't know why because creation process worked more then 5 hours without any results and I stopped it. Anyway, using ordinary matrix (that takes near 50G of RAM) xgboost works absolutely perfect.

**Comment by BlindApe** [comment]
libsvm format will be a pain for loading: # 517
I've worked with sparsed matrices bigger than this without problems.

**Comment by listentowindy** [comment]
In My data, there is about 30 non-zeor values average  in each row . And I have already use libsvm format, just list '1.89    617:39.9978 994:601325 1408:0.000275634 2011:14512 2149:1 3188:1 3316:6.43605 3497:5747 3714:0.00955723 3884:19 5010:0 5231:1020.96 5241:10.4656 5562:0 5689:1 6438:1146'.

**Comment by listentowindy** [comment]
could someone help me？

**Comment by tqchen** [comment]
The program do assumes you remaps the features, so a reprocessing is needed to make the feature dimension more compact
