### ISSUE TITLE
deadlock/hanging when fitting XGBClassifier using multiprocessing after running lgb.train or xgb.train

### ISSUE THREAD

**Issue by z7ye** [dmlc/xgboost#7044]
Running into deadline when fitting XGBClassifier in a multiprocess after running `lgb.train(params={}, train_set=lgb_ds)` or ` xgb.train(params={}, dtrain=xgb_ds)` first.

Scenario 1: running `lgb.train(params={}, train_set=lgb_ds)` first, then fit XGBClassifier in a multiprocess

```
import numpy as np
import xgboost as xgb
import lightgbm as lgb

from sklearn.datasets import load_iris

from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier

iris_dataset = load_iris(return_X_y=True)
X, y = iris_dataset
lgb_ds = lgb.Dataset(data=X, label=y)
est = lgb.train(params={}, train_set=lgb_ds)

X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.3, random_state=42)
clf = XGBClassifier(n_estimators=250, n_jobs=-1)

import multiprocessing

process = multiprocessing.Process(
            target=clf.fit,
            args=(X, y))
process.start()
process.join()
```

Scenario 2: running `xgb.train(params={}, dtrain=xgb_ds)` first, then fit `XGBClassifier` in a multiprocess

```
import numpy as np
import xgboost as xgb
from sklearn.datasets import load_iris

from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier

iris_dataset = load_iris(return_X_y=True)
X, y = iris_dataset

xgb_ds = xgb.DMatrix(data=X, label=y.astype(np.int))
est = xgb.train(params={}, dtrain=xgb_ds) 

X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.3, random_state=42)

clf = XGBClassifier(n_estimators=250, n_jobs=-1)

import multiprocessing

process = multiprocessing.Process(
            target=clf.fit,
            args=(X, y))
process.start()
process.join()
```

The weird thing is that 
- if I run `clf.fit(X, y)`, the deadlock will be gone. 
- if I use `clf = XGBClassifier(n_estimators=250, n_jobs=-1)`, no hang. 
- `xgb.train(params={'n_jobs': -1}, dtrain=xgb_ds)`, no hang either.

Note: This issue only appears if I run `lgb.train(params={}, train_set=lgb_ds)` or ` xgb.train(params={}, dtrain=xgb_ds)` before running 
```
process = multiprocessing.Process(
            target=clf.fit,
            args=(X, y))
process.start()
process.join()
```
Does someone know what was the cause pls?

Environment

- Python='3.7'
- xgboost='1.2.1'
- lightgbm='3.0.0'
- sklearn='0.23.2'

**Comment by trivialfis** [comment]
OpenMP doesn't play well with Python processing: https://github.com/dmlc/xgboost/issues/6898

**Comment by trivialfis** [comment]
Closing as this is a known issue in libgomp with fork.  Considering using spawn instead.
