### ISSUE TITLE
Error while loading model:basic_string::resize

### ISSUE THREAD

**Issue by COLLEENCAI** [dmlc/xgboost#7056]
filemodel = 'xgboostModel.trail04.save'

Saved the model using the following 
with open(filemodel, 'wb') as f:
            pickle.dump(model, f)

I am able to run the following lines to make prediciton
with open(filemodel, 'rb') as f:
    xgb_srm = pickle.load(f)
pred= xgb_srm.predict(dtrain)

However, when I do and receive XGBoostError: basic_string::resize
param = {'colsample_bylevel': 0.5, ...}
model=xgb.Booster(param)
model.load_model(filemodel)

![image](https://user-images.githubusercontent.com/9628057/123214391-016ebd80-d47c-11eb-9ecc-21ec2a1d9e60.png)

Could you please have a look? Thanks!

**Comment by hcho3** [comment]
You cannot load a pickle file with `load_model`. Please use `save_model` first to obtain a file that can be later loaded with `load_model`.
