### ISSUE TITLE
Problem in downloading XGBoost in Windows

### ISSUE THREAD

**Issue by manojthampy** [dmlc/xgboost#7058]
Thanks for participating in the XGBoost community! We use https://discuss.xgboost.ai for any general usage questions and discussions. The issue tracker is used for actionable items such as feature proposals discussion, roadmaps, and bug tracking.  You are always welcomed to post on the forum first :)

Issues that are inactive for a period of time may get closed. We adopt this policy so that we won't lose track of actionable issues that may fall at the bottom of the pile. Feel free to reopen a new one if you feel there is an additional problem that needs attention when an old one gets closed.

For bug reports, to help the developer act on the issues, please include a description of your environment, preferably a minimum script to reproduce the problem.

For feature proposals, list clear, small actionable items so we can track the progress of the change.

**Comment by manojthampy** [comment]
Hi,

Facing problem in downloading xgboot  and mu OS is windows 10 : showing below error msg  appear in jyuter

**Comment by manojthampy** [comment]
Hi,

Facing problem in downloading xgboot and mu OS is windows 10 : showing below error msg appear in jyuter note book

Collecting xgboost
  Using cached xgboost-1.4.2.tar.gz (716 kB)
Requirement already satisfied: numpy in c:\users\13213\anaconda3\lib\site-packages (from xgboost) (1.19.2)
Requirement already satisfied: scipy in c:\users\13213\anaconda3\lib\site-packages (from xgboost) (1.5.2)
Building wheels for collected packages: xgboost
  Building wheel for xgboost (setup.py): started
  Building wheel for xgboost (setup.py): finished with status 'error'
  Running setup.py clean for xgboost
Failed to build xgboost
Installing collected packages: xgboost
    Running setup.py install for xgboost: started
    Running setup.py install for xgboost: finished with status 'error'

**Comment by hcho3** [comment]
Can you run
```
conda list -f pip
```
and paste the output?
