### ISSUE TITLE
How XGBClassifier save and load model?

### ISSUE THREAD

**Issue by kelvict** [dmlc/xgboost#706]
When I try to use 
```
clf = XGBClassifier()
clf._Booster.load_model('..')
```
AttributeError: 'NoneType' object has no attribute 'load_model'

**Comment by walterreade** [comment]
`clf.load_model('..')` should work

**Comment by kelvict** [comment]
I am sorry that I could not find method load_model in A XGBClassifier.

**Comment by brickerino** [comment]
Try like:

clf = XGBClassifier()
booster = Booster()
booster.load_model('./model.xgb')
clf._Booster = booster

clf.predict(...)

**Comment by huangynn** [comment]
@brickerino 

Thank you, but when I use your method

booster = Booster()
booster.load_model('baxi_dadou.xgb')
![image](https://user-images.githubusercontent.com/12636388/37319982-84f2e112-26ac-11e8-9643-f553daf0f25b.png)

Is there something wrong ?

**Comment by huangynn** [comment]
I figured it out.
cause what i previously used if dump_model, which only save the raw text model.
but load_model need the result of save_model, which is in binary format

**Comment by maomao1994** [comment]
https://xgboost.readthedocs.io/en/latest/python/python_intro.html
