### ISSUE TITLE
TeX is not rendered in docs

### ISSUE THREAD

**Issue by yankov** [dmlc/xgboost#708]
TeX formulas are not rendering in the docs. Example: https://github.com/dmlc/xgboost/blob/master/doc/model.md  

If you guys use a specific browser extension to see those, that should be probably mentioned.

**Comment by walterreade** [comment]
Github markdown doesn't support Tex (without hacks).

e.g.,

http://www.r-bloggers.com/rendering-latex-math-equations-in-github-markdown/

**Comment by tqchen** [comment]
it is rendered in  http://xgboost.readthedocs.org/en/latest/model.html
