### ISSUE TITLE
XGBRanker fit vs predict wrt groups/queryIds behavior 

### ISSUE THREAD

**Issue by joshidp** [dmlc/xgboost#7080]
Hi,

Thanks for your great work.

I am trying to understand the XGBRanker implementation.  I have following queries, please help me in understanding these concepts better.

Query1: During training fit call , XGBRanker asks for the 'groups' parameter, does this mean the scoring is independent for each group?

Query2: During the predict call,  XGBRanker  doesn't ask for the 'groups' parameter, only features, how XGBRanker identifies which query group scoring learning has to be used?

Thanks for your help.

```

# creating dummy ranking data
import numpy as np
groups = [60, 50, 32, 22, 22 , 22 , 20, 12]
labels = []
features = []
for group in groups:
  label_group = list(np.argsort(np.argsort(np.random.randn(group))))
  labels = labels + label_group
  for label in label_group:
    features.append([label+10, np.random.randn(), np.random.randn()]) 
features = np.stack(features)


# fitting a ranking model

import xgboost as xgb
import pandas

model = xgb.XGBRanker(
        objective="rank:pairwise",
        max_depth= 10,
        n_estimators=1000,
         verbosity=2)

ranker = model.fit(X=features,
        y=labels, group=groups)
model.predict(features)
```

**Comment by trivialfis** [comment]
XGBoost implements lambda mart, which is a pairwise learning to rank algorithm, so it needs to construct pairs between samples within the same query group to calculate evaluation metrics like ndcg.  Similarly during the calculation of objective (which is derived from those metrics) requires groups to construct pairs.  But for prediction, we don't need the group information as we are only walking through the model without calculating those metrics.

**Comment by joshidp** [comment]
Thanks for the explanation
