### ISSUE TITLE
Influence of zero entries in data file on result.

### ISSUE THREAD

**Issue by brickerino** [dmlc/xgboost#709]
If i add zero entries in input test file, it causes some perturbation of result.
For example,
this 
1 0:1 3:4 10:1
canges to this
1 0:1 1:0 2:0 3:4 10:1
and then resulting probability for this sample changes too.

I made xgb model in python, then exported it and tested with standalone application. Probabilities were not the same, as in python script, but quite near, the biggest change was like from 0.99 to 0.97.

I tested 0.4.0 release and master branch. Both have this problem.

**Comment by tqchen** [comment]
The main reason is that the unpresented entries are treated as missing while zero are treated as zero, they should not have big impact in general

**Comment by brickerino** [comment]
Then we have a semantic problem, because in python script zero entries do exist, and in order to get the same result with the same model and data in standalone application i should except them and consider all zeros as missing values. Is it ok?

**Comment by tqchen** [comment]
yes, this normally won't pose as problem
