### ISSUE TITLE
Unable to resume training with models saved with checkpoint

### ISSUE THREAD

**Issue by JSAnandEOS** [dmlc/xgboost#7119]
Hello,

I'm currently training an XGBoost (v1.3.0, Python) model using XGBRegressor on a very large dataset (6 million rows x 54 features) with 250 trees, and after taking ~5 hours to train, Python is suddenly killed due to a memory error. In order to diagnose what's happening I tried using a checkpoint callback function to save every 10th iteration as a separate model, using the following code:

```
 check_point = TrainingCheckPoint(directory=tmpdir, iterations=10, name='xgb_250_n_estimators_temp_pkl', as_pickle = True)

 xgb_model = XGBRegressor(**other_params)

xgb_model.fit(X_train, y_train, early_stopping_rounds = 15, eval_metric = 'mae', eval_set = [[X_val, y_val]], callbacks = [check_point])

```

However, when I try loading the saved model I get the following error:

```
test = XGBRegressor()

test.load_model('xgb_250_n_estimators_temp_pkl_10.pkl')
```

```
---------------------------------------------------------------------------
XGBoostError                              Traceback (most recent call last)
<ipython-input-18-535fccee232c> in <module>
----> 1 test.load_model('xgb_250_n_estimators_temp_pkl_10.pkl')

~/miniconda3/envs/esa_dte/lib/python3.9/site-packages/xgboost/sklearn.py in load_model(self, fname)
    465         if not hasattr(self, '_Booster'):
    466             self._Booster = Booster({'n_jobs': self.n_jobs})
--> 467         self._Booster.load_model(fname)
    468         meta = self._Booster.attr('scikit_learn')
    469         if meta is None:

~/miniconda3/envs/esa_dte/lib/python3.9/site-packages/xgboost/core.py in load_model(self, fname)
   1713             # assume file name, cannot use os.path.exist to check, file can be
   1714             # from URL.
-> 1715             _check_call(_LIB.XGBoosterLoadModel(
   1716                 self.handle, c_str(os.fspath(fname))))
   1717         elif isinstance(fname, bytearray):

~/miniconda3/envs/esa_dte/lib/python3.9/site-packages/xgboost/core.py in _check_call(ret)
    186     """
    187     if ret != 0:
--> 188         raise XGBoostError(py_str(_LIB.XGBGetLastError()))
    189 
    190 

XGBoostError: basic_string::_M_replace_aux
```

Why does this error happen? Curiously, this doesn't happen if ```as_pickle = False```, and the model can be read as normal. However, the json file that's produced doesn't contain any information about the number of trees or any other parameter when loaded into XGBRegressor, so acquiring diagnostic information about the model is not possible. 

Also, I'm still not too sure about how to reuse the checkpoint model when resuming training. Hypothetically, if I wanted to train a 250 tree model, and after the 220th iteration was saved as a checkpoint before Python crashes, I would need to specify the old model in the XGBRegressor fit, using ```xgb_model```. But what would ```n_estimators``` need to be set to: 250 (the original desired number) or 30 (the number of remaining trees)? Also, does XGBoost know how many trees are present in a checkpointed model, even if it was saved with ```as_pickle = False```?

**Comment by trivialfis** [comment]
Hi, with `as_pickle`, you should load the model as follow:

```
with open("model.pkl", "rb") fd
    model = pickle.load(fd)
```

The `load_model` function implemented in xgboost is exlusively for loadding file saved by `model.save_model`.

**Comment by JSAnandEOS** [comment]
Thanks. I'll try that.

What should ```n_estimators``` be set to in order to resume training to the original target of 250 trees after creating a checkpoint at 220 trees: 250 or 30?

**Comment by trivialfis** [comment]
Hi, I added a demo in https://github.com/dmlc/xgboost/pull/7121 .  The fix is not related if you don't change the hyper-parameters in training continuation.  Hope that helps.

**Comment by trivialfis** [comment]
Closing as the original question is answered and there's now a demo for training continuation.  Feel free to open new issues if you have more questions.
