### ISSUE TITLE
Limit or constraints of data

### ISSUE THREAD

**Issue by leoknuth** [dmlc/xgboost#7122]
When I use XGBoost to train data, is there any limit of data? Specially I am confused about two issues.

1. What are the recommended ranges of data? C++ int range aka -2147483647 ~ 2147483648?
2. When different features are in different orders of magnitude. Does XGBoost do normalization internally?

**Comment by trivialfis** [comment]
> What are the recommended ranges of data?

We use float32 to represent all data.

> When different features are in different orders of magnitude. Does XGBoost do normalization internally?

No, that should be part of feature engineering.

**Comment by leoknuth** [comment]
> We use float32 to represent all data.

When data exceeds float32 range, how they are processed in XGBoost? Treated as 2^31 or -(2^31 - 1)?

**Comment by leoknuth** [comment]
Is it recommended to normalize data to keep all features in similar levels before using XGBoost?

**Comment by trivialfis** [comment]
> When data exceeds float32 range, how they are processed in XGBoost? Treated as 2^31 or -(2^31 - 1)?

Truncated according to floating-point rules.

> Is it recommended to normalize data to keep all features in similar levels before using XGBoost?

Not required.  The gain is calculated from gradient which is in turn calculated from prediction and labels.  But if you have huge variance in your data it's advised to do some pre-processing first. Otherwise, the floating errors can be significant.

**Comment by leoknuth** [comment]
Thanks!
