### ISSUE TITLE
Relationship between tree numbers, tree depth and feature numbers?

### ISSUE THREAD

**Issue by leoknuth** [dmlc/xgboost#7123]
If I have n features, how many tree estimators should I use in XGBoost? What is the recommended tree depth? 
If n is small e.g. n <= 10?
If n is large e.g. n >= 100?

**Comment by trivialfis** [comment]
> If I have n features, how many tree estimators should I use in XGBoost?

Unrelated.

> What is the recommended tree depth?

We don't have a recommendation on this hyper-parameter.  It's data dependent.  Also if you are training for multiple boosting iterations, then each base model can be simple.  If you are training random forests then you might want deeper trees.  Feel free to use some hyper-parameter tuning libraries like sklearn and optuna.
