### ISSUE TITLE
Floating point precision issue

### ISSUE THREAD

**Issue by leoknuth** [dmlc/xgboost#7124]
Hello, I have some questions about floating point precision.
1. Is there any option for users to choose float32 or double64 when using XGBoost?
2. When I dump the model to a json file, I found that the `split_condition` values seem to have 9 effective digits. Are the last 2 digits meaningless since XGBoost uses float32 in training and prediction?

**Comment by trivialfis** [comment]
> Is there any option for users to choose float32 or double64 when using XGBoost?

Unforunatebly, other than histgram precision there's no such option for switching.

> When I dump the model to a json file, I found that the split_condition values seem to have 9 effective digits. 

This relates to floating point printing.  XGBoost utilizes the algorithm implemented in https://github.com/ulfjack/ryu for saving model into JSON. (not for `model.get_dump()`, but for `model.save_model()`).
