### ISSUE TITLE
BUG? - Predict for Multi-Classification - Hard limit to 3 classifications

### ISSUE THREAD

**Issue by bfoxconlabs** [dmlc/xgboost#7125]
https://github.com/dmlc/xgboost/blob/master/R-package/R/xgb.Booster.R#L430L432

When a multi-classification predict is run with `reshape=TRUE`, the output is different than in previous commits.

These lines of code seem to limit the output to just 3 classifications (3 columns), even if n_groups > 3.

Is this intended?

**Comment by trivialfis** [comment]
Thanks for raising the issue.  My bad, will fix it.
