### ISSUE TITLE
EarlyStopping can incorrectly detect metric improvement with positive tolerance

### ISSUE THREAD

**Issue by MarkGuryanov** [dmlc/xgboost#7136]
Hello!

The logic of class [`xgboost.callbacks.EarlyStopping`](https://github.com/dmlc/xgboost/blob/92ae3abc972c100a11d7e75fb6dbeebdb7cefd1e/python-package/xgboost/callback.py#L471) determining whether the metric improved seems to be incorrect if parameter `abs_tol` is graeter than 0. Namely, its private method [`_update_rounds`](https://github.com/dmlc/xgboost/blob/92ae3abc972c100a11d7e75fb6dbeebdb7cefd1e/python-package/xgboost/callback.py#L536) defines two helper functions, [`maximize`](https://github.com/dmlc/xgboost/blob/92ae3abc972c100a11d7e75fb6dbeebdb7cefd1e/python-package/xgboost/callback.py#L541) and [`minimize`](https://github.com/dmlc/xgboost/blob/92ae3abc972c100a11d7e75fb6dbeebdb7cefd1e/python-package/xgboost/callback.py#L544), which erroneously determine the event of metric improvement.

In case when metric is intended to be maximized, the following code decides whether it has improved (became greater than previous best):
```python
def maximize(new, best):
    return numpy.greater(get_s(new) + self._tol, get_s(best))
```
This function returns `True` if `new + tol > best`, but if `tol > 0`, this can be true even when `new <= best` (for example, `new == best - tol/2` so `new + tol == best + tol/2 > best`), but obviously this is not the case of metric improvement.

Similarly, when metric is intended to be minimized, the following code decides whether it has improved (became less than previous best):
```python
def minimize(new, best):
    return numpy.greater(get_s(best) + self._tol, get_s(new))
```
This function returns `True` if `best + tol > new`, but again, in case `tol > 0` and (as an example) `new == best + tol/2` this condition is true, but `new` is actually worse (greater) than `best`.

This means that when new metric value is slightly worse (not more than `abs_tol`) than previous best, `EarlyStopping` considers it as improvement and saves this value as new best (which is actually worse). And this can result in boosting slightly worsening the model each iteration, but `EarlyStopping` will consider it as an improvement, thus skipping the moment when the model was truly best and yielding incorrect `best_iteration` and so on.

Fortunately, this behavior can be fixed by substituting `+` with `-` in these two helper methods, so it becomes:
* `maximize`: improves if `new - tol > best` (so `new > best + tol`);
* `minimize`: improves if `best - tol > new` (so `new < best - tol`).

**Comment by trivialfis** [comment]
Related: https://github.com/dmlc/xgboost/pull/7066  I will add a min delta.

**Comment by trivialfis** [comment]
Hi, I have opened a PR: https://github.com/dmlc/xgboost/pull/7137 could you please help review it?

**Comment by MarkGuryanov** [comment]
Hi @trivialfis!
Yes, I'm looking into it now.
