### ISSUE TITLE
Xgboost takes up lot of space in docker container

### ISSUE THREAD

**Issue by santhisenan** [dmlc/xgboost#7162]
I am trying to install xgboost in a docker container. However, xgboost is currently taking up more than 500MB in the container.

I have a python 3.8 base container and I am trying to install xgboost using `pip install --no-cache-dir xgboost`. To reproduce, build a container using the below Dockerfile.

```docker
FROM python:3.8-slim-buster AS final-image

RUN apt-get update \
    && pip install --no-cache-dir xgboost
```

**Is there a way to reduce the amount of space taken up the xgboost package?** 

![image](https://user-images.githubusercontent.com/14852343/128592518-562d14b9-0599-47e8-82cc-a01cef133d9c.png)

**Comment by hcho3** [comment]
Try: `pip install --no-binary xgboost xgboost`, which will download the source package `xgboost.tar.gz` and build it on the fly.

The binary package is large because it is built with GPU support.

**Comment by santhisenan** [comment]
Thank you for your reply.

Using the method you suggested, I was able to reduce the disk space used by xgboost to **just 8 MB**.

![image](https://user-images.githubusercontent.com/14852343/128601547-941ab829-13bd-442a-8034-0cd18e3fbabe.png)

Updated Dockerfile:
```
FROM python:3.8-slim-buster AS final-image

RUN apt-get update \
    && apt-get install -y --no-install-recommends cmake build-essential

RUN pip install --no-cache-dir --no-binary xgboost xgboost \
    && apt-get purge -y --auto-remove cmake build-essential gcc \
    && rm -rf /var/lib/apt/lists/*
```
