### ISSUE TITLE
No Support for Build with runtime Library as MD on MSVC?

### ISSUE THREAD

**Issue by mohitk08** [dmlc/xgboost#7163]
Does XGBOOST not support MD runtime Library on MSVC?

I see that we force static runtime for MSVC by calling msvc_use_static_runtime() from cmake/Utils.cmake
e.g.
https://github.com/dmlc/xgboost/blob/master/CMakeLists.txt#L158
https://github.com/dmlc/xgboost/blob/master/CMakeLists.txt#L332
https://github.com/dmlc/xgboost/blob/master/src/CMakeLists.txt#L32

With my limited understanding, this creates issue with applications as default runtime is MD and hence resulting into link errors.

I am wondering if other c++ users face this issue regularly?

Please suggest a way out.

**Comment by trivialfis** [comment]
@RAMitchell Do you have any insight?

**Comment by RAMitchell** [comment]
We can deal with it if someone demonstrates an issue, I think this is fairly normal as it doesn't depend on having a local runtime. It would be an issue if you linked xgboost.lib with an application built differently.

**Comment by mohitk08** [comment]
I am using XGBOOST as a static c++ library i.e. BUILD_STATIC_LIB = ON

When I try to build my application with linking against this xgboost.lib, I get runtime Library mismatch errors.

While debugging this, I found the forceful use of static runtime Library in cmake of xgboost. Hence pointed it out.

Please let me know if you need any further information

**Comment by hcho3** [comment]
We should implement a CMake option that's similar to `DMLC_FORCE_SHARED_CRT` in dmlc-core:
```cmake
dmlccore_option(DMLC_FORCE_SHARED_CRT "Build with dynamic CRT on Windows (/MD)" OFF)
```
https://github.com/dmlc/dmlc-core/blob/5eaff7643a88949c81af1e5de11945632920bf96/CMakeLists.txt#L25

**Comment by hcho3** [comment]
#7277 should fix this.
