### ISSUE TITLE
XGBoost4J: Exporting to, then importing a model from stream results in wrong model format exception

### ISSUE THREAD

**Issue by PossessedC0bra** [dmlc/xgboost#7168]
Hi there!

I'm currently having issues with exporting and importing an XGBoost model to/from a Stream. I export the model to a `ByteArrayOutputStream` with the `saveModel` method on `ml.dmlc.xgboost4j.java.Booster` :
https://github.com/dmlc/xgboost/blob/3f38d983a671632bfb0dbdcdead6f2aa408a06f2/jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/Booster.java#L393-L396

At a later point i try to import the previously exported model again from an `InputStream `using the `loadModel` method on `ml.dmlc.xgboost4j.java.XGBoost`:
https://github.com/dmlc/xgboost/blob/3f38d983a671632bfb0dbdcdead6f2aa408a06f2/jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/XGBoost.java#L56-L65

Altough the Stream contains the exact same data the import fails with the following exception:
```
Caused by: ml.dmlc.xgboost4j.java.XGBoostError: [16:24:54] D:\a\xgboost\xgboost\src\learner.cc:785: Check failed: fi->Read(&tparam_.objective): BoostLearner: wrong model format
	at ml.dmlc.xgboost4j.java.XGBoostJNI.checkCall(XGBoostJNI.java:48)
	at ml.dmlc.xgboost4j.java.Booster.loadModel(Booster.java:81)
	at ml.dmlc.xgboost4j.java.XGBoost.loadModel(XGBoost.java:64)
	...
```

I recently upgraded from version 1.3.1 to 1.4.1. I never encountered this problem with version 1.3.1. I noticed an entry in the changelog mentioning changes to the export/importing of models ([jvm] Add ability to load booster direct from byte array (#6655)). Might i be using the new API wrong?

**Library version:** XGBoost4J 1.4.1

**Comment by trivialfis** [comment]
I think this might be relevant? https://github.com/dmlc/xgboost/pull/7067

**Comment by PossessedC0bra** [comment]
> I think this might be relevant? #7067

I can confirm the mentioned pull request solves my issue. Thanks for your quick response!
