### ISSUE TITLE
how the validationObjectiveHistory Array generate in distribute envrionment

### ISSUE THREAD

**Issue by ICDI0906** [dmlc/xgboost#7169]
how the validationObjectiveHistory and trainObjectiveHistory Array generate in a distributed environment?

**Comment by trivialfis** [comment]
Please checkout the code in https://github.com/dmlc/xgboost/blob/0ed979b0960e5f307a78fc7e059a272235aacea6/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostRegressor.scala#L195 .
