### ISSUE TITLE
torch.Tensor as input for xgboost.DMatrix

### ISSUE THREAD

**Issue by 7starsea** [dmlc/xgboost#7172]
As pytorch is growing and popular, I hope the `data` argument for `xgboost.DMatrix` and `inplace_predict` could accept `torch.Tensor` as input.

**Comment by trivialfis** [comment]
If you are using GPU then you can use dlpack https://pytorch.org/docs/stable/dlpack.html with torch and cupy.  XGBoost accepts cupy array.  Otherwise I think it's unlikely that we have torch in our CI for integration tests.
