### ISSUE TITLE
is xgboost support android platform? using java api or C api

### ISSUE THREAD

**Issue by CodeBuilderPRML** [dmlc/xgboost#7178]

**Comment by trivialfis** [comment]
Unfortunately no.  Feel free to try it out and share your result.

**Comment by CodeBuilderPRML** [comment]
> Unfortunately no. Feel free to try it out and share your result.

so we can't compile it with ndk to generate c++ so for android directly? Because some header files cannot be found in android platform?

**Comment by trivialfis** [comment]
I have never tried, nor do we have Android on our CI hence "not supported".  It may or may not work.

**Comment by CodeBuilderPRML** [comment]
> I have never tried, nor do we have Android on our CI hence "not supported". It may or may not work.

ok, i got it, thank u very much.
