### ISSUE TITLE
Kernel dies when creating DMatrix 

### ISSUE THREAD

**Issue by rrpelgrim** [dmlc/xgboost#7191]
My kernel dies without an error message when trying to create an XGBoost DMatrix using:

```
# Create the XGBoost DMatrix
dtrain = xgb.DMatrix(X_train, y_train)
```

I’ve tried the following without any luck:
- deleting libiomp5.dylib as per [this thread](https://datascience.stackexchange.com/questions/33964/python-xgboost-killing-kernel)
- including import os os.environ['KMP_DUPLICATE_LIB_OK']='True' at the top of the notebook as per [this thread](https://github.com/dmlc/xgboost/issues/1715)
- updating libomp using brew install libomp
- reinstalling my mambaforge package manager

I'm working on an M1 Macbook Pro and wonder if that might be the issue. My colleague is able to run this code without a problem on a non-M1 machine.

**MRE**

```
# create dummy data
d = {
  'y': [1, 0, 0, 1], 
  'x1': [1, 2, 3, 4],
  'x2': [5, 6, 7, 8],
  'x3': [9, 0, 1, 2]}

df = pd.DataFrame(data=d)
 
# create train/test splits
X, y = df.iloc[:, 1:], df["y"]
X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.25, shuffle=True, random_state=2)

# Create the XGBoost DMatrix
dtrain = xgb.DMatrix(X_train, y_train)
```

I'm working with:
- a 2020 M1 Macbook Pro
- Python: 3.9 / 3.8
- XGBoost: 1.4.2 / 1.2.0
- Pandas: 1.3.1
- Numpy: 1.21.2

I've followed the steps in[ this article](https://towardsdatascience.com/install-xgboost-and-lightgbm-on-apple-m1-macs-cb75180a2dda) to install xgboost (python and all dependencies through mambaforge, then xgboost from pip)

NOTE: I've tried downgrading XGBoost. v 1.2.0 creates the DMatrix but fails with the same behaviour (no error message, kernel dies) when calling xgb.train(params,dtrain).

Is this a known issue on M1? Is there a workaround?

**Comment by rrpelgrim** [comment]
OK, thanks for the update @hcho3. Is there any roadmap for when you will be testing/rolling out support for XGboost on M1?

**Comment by trivialfis** [comment]
Not at the moment.  Github action doesn't have M1 instance https://github.com/actions/virtual-environments/issues/2187 and AFAIK none of the active maintainers has one.

**Comment by rrpelgrim** [comment]
Ok, thanks for this. I will find another way to workaround it then.
--
*Richard Pelgrim*
+31 (0)6 374 807 31
code: github.com/rrpelgrim/portfolio
blog: richardpelgrim.medium.com
