### ISSUE TITLE
Inference latency of predict() when deployed in docker/kubernetes

### ISSUE THREAD

**Issue by danielgreff** [dmlc/xgboost#7194]
Hi, I am having the following problem: a deployed (Kubernetes using Docker) python service containing a XGB model stalls and leads to large (>1sec) latencies - this can't be reproduced locally running the service on a MacbookPro 2018. 

Detailed description: I have a python service which is running a XGB model on every call. When initializing the service I load the trained models into a dictionary from where the models can then be accessed during a predict. The models are trained using the Learning API and stored as JSON files (trained with version 1.3.3). The predict code is implemented something like this:

`    # Touchdown
    td_clf = models['drive_outcome']['touchdown']
    td_prob_bin = td_clf.predict(DMatrix(to_predict[:, :-1]))
    td_prob = float(td_prob_bin)`

Throughout the service there are multiple other XGB models being used in a similar manner and generally the predict latency is around 5ms for the whole service. The problem arises when this service is deployed to a Kubernetes cluster to perform predictions in real time. The service is packaged within the following docker:
```

FROM python:3.9.6-slim-buster

EXPOSE 6001
WORKDIR /american_football

ENV PYTHONPATH=..
ARG arg_league
ENV LEAGUE=$arg_league

RUN apt-get update && apt-get install make
RUN pip install 'xgboost==1.3.3' 'numpy==1.20.3' grpcio-tools graypy requests
# Service
....
# Extra
....
CMD ["python", "-u", "./model_services/predict_states/predict_states_service.py"]
```

This docker image is being deployed to a Kubernetes cluster running AWS machines with amd64 architecture. The latencies detected were first measured using Grafana and later verified using cProfile (default timer) and logging the time spent to excecute the service.

The weird points are:
- this only occurs in the service running XGB, other services which run solely numpy do not suffer from these latencies, although they are all running on the same nodes within the cluster
- this is not the first request (so its not an initialization issue), but any random request after a given pod excecuting the service had already responded to multiple previous requests with low latency
- locally I have not managed to replicate this issue (same python and xgboost versions)
- the profiler reports the time being spent in xgb.core functions
```

1126 function calls (1102 primitive calls) in 1.337 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        8    0.685    0.086    0.686    0.086 /usr/local/lib/python3.9/site-packages/xgboost/data.py:132(_from_numpy_array)
        8    0.647    0.081    0.648    0.081 /usr/local/lib/python3.9/site-packages/xgboost/core.py:1385(predict)
        1    0.000    0.000    1.337    1.337 /american_football/model_services/predict_states/predict_states_model.py:28(predict_states)
        8    0.000    0.000    0.001    0.000 /usr/local/lib/python3.9/site-packages/xgboost/core.py:192(ctypes2numpy)
        8    0.000    0.000    0.686    0.086 /usr/local/lib/python3.9/site-packages/xgboost/core.py:435(__init__)
       33    0.000    0.000    0.000    0.000 {built-in method numpy.array}
        2    0.000    0.000    0.000    0.000 /usr/local/lib/python3.9/site-packages/numpy/lib/arraysetops.py:138(unique)
        9    0.000    0.000    0.000    0.000 /american_football/model_services/predict_states/predict_states_model.py:297(construct_lookup_state)
        2    0.000    0.000    0.000    0.000 /usr/local/lib/python3.9/site-packages/numpy/lib/arraysetops.py:310(_unique1d)
       16    0.000    0.000    0.000    0.000 /usr/local/lib/python3.9/site-packages/numpy/core/_internal.py:249(__init__)
```

I don't know if anybody has some tips to what I could try? Improve the profiling somehow to determine what is happening?  The service has one worker, two designated CPUs in the cluster and I have already tried limiting the nthread of the os to 1. 
Hope somebody has an idea. Thanks for reading this wall.

**Comment by trivialfis** [comment]
Sorry but I don't think the xgboost developers here can help with deployment issues ...  When you try to reproduce the issue locally, could you please check that xgboost is receiving the exact same data?  From your profiling result, `from_numpy_array` is taking lots of time, so I suspect there are differences in the input data (like some libraries on the cluster is different and accidentally produces data with `object` type, just an example).

Also, you may want to test `inplace_predict`, which doesn't construct a DMatrix and consumes the data directly.

**Comment by danielgreff** [comment]
Thank you for your response. Yes we are passing the same data to the local version as to the deployed version. Also the payloads which cause this issue can't reproduce this issue, it seems to be input independent. I have tried your suggestion of using `inplace_predict` but it did not help with the issue, I am still seeing these spikes in latency.

What is interesting is that I can reproduce a similar latency spike coming just from `core/predict()` (this is using the Sklearn Boosters). To me this suggests that the function is hanging when it is calling the C API. What do you think? Could it be due to the CPU architecture of the node we are using? 

I know you said that you can't help with deployment issues as there are so many different variables, but they strange issue is like I said that this is only happening to us with services using XGBoost. Is there anything else you suspect that could be happening?

```

1167 function calls (1139 primitive calls) in 1.194 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
       12    1.190    0.099    1.191    0.099 /opt/conda/lib/python3.6/site-packages/xgboost/core.py:1141(predict)
       12    0.000    0.000    0.001    0.000 /opt/conda/lib/python3.6/site-packages/xgboost/core.py:168(ctypes2numpy)
        1    0.000    0.000    1.194    1.194 /american_football/model_services/predict_states/predict_states_model.py:28(predict_states)
       12    0.000    0.000    0.000    0.000 /opt/conda/lib/python3.6/site-packages/xgboost/core.py:437(_init_from_npy2d)
       22    0.000    0.000    0.000    0.000 {built-in method numpy.zeros}
       12    0.000    0.000    0.001    0.000 /opt/conda/lib/python3.6/site-packages/xgboost/core.py:323(__init__)
        8    0.000    0.000    0.000    0.000 /american_football/model_services/predict_states/predict_states_model.py:297(construct_lookup_state)
        1    0.000    0.000    0.403    0.403 /american_football/model_services/common/model_predict.py:174(predict_times)
        2    0.000    0.000    0.294    0.147 /american_football/model_services/common/model_predict.py:256(exp_timeout_points)
       33    0.000    0.000    0.000    0.000 {built-in method numpy.array}
       12    0.000    0.000    0.000    0.000 {built-in method builtins.max}
        1    0.000    0.000    0.392    0.392 /american_football/model_services/common/model_predict.py:20(predict_outcomes)
        3    0.000    0.000    0.392    0.131 /opt/conda/lib/python3.6/site-packages/xgboost/sklearn.py:771(predict_proba)
        9    0.000    0.000    0.800    0.089 /opt/conda/lib/python3.6/site-packages/xgboost/sklearn.py:387(predict)

```

**Comment by czzmmc** [comment]
@danielgreff I'm suffering the same situation when doing prediction on kubernetes. No idea what is happening. I've tried inplace_predict() which did not work for me. If you find something, please DM me.

**Comment by trivialfis** [comment]
Internally XGBoost utilizes openmp.  There were some issues about the thread scheduling around different libc and openmp.  Could you please check that XGBoost is using the right number of threads for each prediction?
