### ISSUE TITLE
The tree_method param changes when loading a model from file

### ISSUE THREAD

**Issue by nlathia** [dmlc/xgboost#7196]
👋 Hi team, is it expected for a model's params to change when loading a model? Specifically, the `tree_method` param changes from `"exact"` to `"auto"`. The closest I could find in the docs is:

> XGBoost saves the trees, some model parameters like number of input columns in trained trees, and the objective function, which combined to represent the concept of “model” in XGBoost

Is it expected for `tree_method` to not be persisted/loaded?

**Environment**
- macOS Catalina 10.15.7
- Python 3.8.7
- xgboost==1.4.2, scikit-learn==0.24.2

**Example**

```
# Creates some fake data
>>> from sklearn.datasets import make_classification
>>> X_train, y_train = make_classification(
        n_samples=50,
        n_features=5,
        n_redundant=0,
        n_informative=3,
        n_clusters_per_class=1,
    )

# Train a model
>>> model = xgb.XGBClassifier(use_label_encoder=False)
>>> model.fit(X_train, y_train)
**>>> model.get_params()["tree_method"]**
**'exact'**

# Save and load back
>>> model.save_model("example.json")
>>> nmodel = xgb.XGBClassifier(use_label_encoder=False)
>>> nmodel.load_model("example.json")

# tree_method is set to auto now
**>>> nmodel.get_params()["tree_method"]
'auto'**
```

**Comment by trivialfis** [comment]
Hi Neal,  the `exact` is a result of auto-selection.  If you have specificed the tree method like

``` python
clf = xgb.XGBClassifier(tree_method="hist")
```

Then `load_model` should give you the same tree method.  Note that the behaviour is sklearn interface specific, for other interfaces saving model generally discard all training parameters.  For details, please see: https://xgboost.readthedocs.io/en/latest/tutorials/saving_model.html

**Comment by trivialfis** [comment]
Feel free to reopen or open a new issue if you have further questions.

**Comment by nlathia** [comment]
Thanks!
