### ISSUE TITLE
[xgboost4j] large model cause bad_alloc error

### ISSUE THREAD

**Issue by panxhong** [dmlc/xgboost#7200]
Code File: xgboost/jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/XGBoost.java

public static Booster loadModel(InputStream in) throws XGBoostError, IOException {
        int size;
//      byte[] buf = new byte[1<<20];    large model will cause "bad_alloc" error
        byte[] buf = new byte[in.available()];  // Modify to this will solve the problem
        ByteArrayOutputStream os = new ByteArrayOutputStream();
        while ((size = in.read(buf)) != -1) {
            os.write(buf, 0, size);
        }
        in.close();
        return Booster.loadModel(buf);
    }

I am curious about why the size of buf need to be limitted  to 1 << 20 ?

**Comment by hcho3** [comment]
The issue was fixed in https://github.com/dmlc/xgboost/pull/7067
