### ISSUE TITLE
Apparently successful build on Jetson Nano, but run yields "cudaErrorLaunchFailure: unspecified launch failure"

### ISSUE THREAD

**Issue by matthiaslein** [dmlc/xgboost#7201]
Hi all

I am trying to use my Jetson Nano’s GPU for XGBoost training. According to the instructions [here](https://xgboost.readthedocs.io/en/latest/build.html), I have downloaded the source and compiled successfully. According to [these](https://github.com/dmlc/xgboost/issues/4355) instructions, I have configured the build like this:

cmake .. -DUSE_CUDA=ON -DUSE_OPENMP=ON -DGPU_COMPUTE_VER=53

After installation, I can use the library with OpenMP, but not with CUDA. I’m getting the following error message:

terminate called after throwing an instance of ‘thrust::system::system_error’
what(): parallel_for failed: cudaErrorLaunchFailure: unspecified launch failure
Aborted (core dumped)

I’m wondering if I’m building xgboost the right way?

My system is based on an unmodified JP46 image from NVIDIA and the full stack-trace is here:

Traceback (most recent call last):
  File "./thirty-doml.py", line 114, in <module>
    my_model = xgboost_sklearn_api(X_fold_train, y_fold_train,
  File "./thirty-doml.py", line 84, in xgboost_sklearn_api
    xgb_skl_model.fit(X_t, y_t,
  File "/home/pikube-deployer/python/.venv/lib/python3.8/site-packages/xgboost/core.py", line 498, in inner_f
    return f(**kwargs)
  File "/home/pikube-deployer/python/.venv/lib/python3.8/site-packages/xgboost/sklearn.py", line 779, in fit
    self._Booster = train(
  File "/home/pikube-deployer/python/.venv/lib/python3.8/site-packages/xgboost/training.py", line 188, in train
    bst = _train_internal(params, dtrain,
  File "/home/pikube-deployer/python/.venv/lib/python3.8/site-packages/xgboost/training.py", line 81, in _train_internal
    bst.update(dtrain, i, obj)
  File "/home/pikube-deployer/python/.venv/lib/python3.8/site-packages/xgboost/core.py", line 1667, in update
    _check_call(_LIB.XGBoosterUpdateOneIter(self.handle,
  File "/home/pikube-deployer/python/.venv/lib/python3.8/site-packages/xgboost/core.py", line 213, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: [10:49:58] /home/pikube-deployer/xgboost/src/tree/updater_gpu_hist.cu:767: Exception in gpu_hist: [10:49:58] /home/pikube-deployer/xgboost/src/c_api/../data/../common/common.h:45: /home/pikube-deployer/xgboost/src/tree/gpu_hist/row_partitioner.cuh: 139: cudaErrorLaunchFailure: unspecified launch failure
Stack trace:
  [bt] (0) /home/pikube-deployer/python/.venv/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x3aa3c4) [0x7f730363c4]
  [bt] (1) /home/pikube-deployer/python/.venv/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(dh::ThrowOnCudaError(cudaError, char const*, int)+0x1c8) [0x7f73039548]
  [bt] (2) /home/pikube-deployer/python/.venv/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(void xgboost::tree::RowPartitioner::UpdatePosition<__nv_dl_wrapper_t<__nv_dl_tag<void (xgboost::tree::GPUHistMakerDevice<xgboost::detail::GradientPairInternal<double> >::*)(int, xgboost::RegTree*), &xgboost::tree::GPUHistMakerDevice<xgboost::detail::GradientPairInternal<double> >::UpdatePosition, 1u>, xgboost::EllpackDeviceAccessor, xgboost::RegTree::Node, xgboost::FeatureType, xgboost::common::Span<unsigned int, 18446744073709551615ul> > >(int, int, int, __nv_dl_wrapper_t<__nv_dl_tag<void (xgboost::tree::GPUHistMakerDevice<xgboost::detail::GradientPairInternal<double> >::*)(int, xgboost::RegTree*), &xgboost::tree::GPUHistMakerDevice<xgboost::detail::GradientPairInternal<double> >::UpdatePosition, 1u>, xgboost::EllpackDeviceAccessor, xgboost::RegTree::Node, xgboost::FeatureType, xgboost::common::Span<unsigned int, 18446744073709551615ul> >)+0x21c) [0x7f731c3d2c]
  [bt] (3) /home/pikube-deployer/python/.venv/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(xgboost::tree::GPUHistMakerDevice<xgboost::detail::GradientPairInternal<double> >::UpdateTree(xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*, xgboost::DMatrix*, xgboost::RegTree*, dh::AllReducer*)+0xf84) [0x7f731c955c]
  [bt] (4) /home/pikube-deployer/python/.venv/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(xgboost::tree::GPUHistMakerSpecialised<xgboost::detail::GradientPairInternal<double> >::Update(xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*, xgboost::DMatrix*, std::vector<xgboost::RegTree*, std::allocator<xgboost::RegTree*> > const&)+0x130) [0x7f731ca098]
  [bt] (5) /home/pikube-deployer/python/.venv/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(xgboost::gbm::GBTree::BoostNewTrees(xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*, xgboost::DMatrix*, int, std::vector<std::unique_ptr<xgboost::RegTree, std::default_delete<xgboost::RegTree> >, std::allocator<std::unique_ptr<xgboost::RegTree, std::default_delete<xgboost::RegTree> > > >*)+0x1ac) [0x7f72eefe74]
  [bt] (6) /home/pikube-deployer/python/.venv/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(xgboost::gbm::GBTree::DoBoost(xgboost::DMatrix*, xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*, xgboost::PredictionCacheEntry*)+0x37c) [0x7f72ef1b1c]
  [bt] (7) /home/pikube-deployer/python/.venv/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(xgboost::LearnerImpl::UpdateOneIter(int, std::shared_ptr<xgboost::DMatrix>)+0x368) [0x7f72f13d40]
  [bt] (8) /home/pikube-deployer/python/.venv/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(XGBoosterUpdateOneIter+0x84) [0x7f72e257e4]

Stack trace:
  [bt] (0) /home/pikube-deployer/python/.venv/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x5252fc) [0x7f731b12fc]
  [bt] (1) /home/pikube-deployer/python/.venv/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(xgboost::tree::GPUHistMakerSpecialised<xgboost::detail::GradientPairInternal<double> >::Update(xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*, xgboost::DMatrix*, std::vector<xgboost::RegTree*, std::allocator<xgboost::RegTree*> > const&)+0x62c) [0x7f731ca594]
  [bt] (2) /home/pikube-deployer/python/.venv/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(xgboost::gbm::GBTree::BoostNewTrees(xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*, xgboost::DMatrix*, int, std::vector<std::unique_ptr<xgboost::RegTree, std::default_delete<xgboost::RegTree> >, std::allocator<std::unique_ptr<xgboost::RegTree, std::default_delete<xgboost::RegTree> > > >*)+0x1ac) [0x7f72eefe74]
  [bt] (3) /home/pikube-deployer/python/.venv/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(xgboost::gbm::GBTree::DoBoost(xgboost::DMatrix*, xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*, xgboost::PredictionCacheEntry*)+0x37c) [0x7f72ef1b1c]
  [bt] (4) /home/pikube-deployer/python/.venv/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(xgboost::LearnerImpl::UpdateOneIter(int, std::shared_ptr<xgboost::DMatrix>)+0x368) [0x7f72f13d40]
  [bt] (5) /home/pikube-deployer/python/.venv/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(XGBoosterUpdateOneIter+0x84) [0x7f72e257e4]
  [bt] (6) /usr/lib/aarch64-linux-gnu/libffi.so.6(ffi_call_SYSV+0x64) [0x7f89c69d28]
  [bt] (7) /usr/lib/aarch64-linux-gnu/libffi.so.6(ffi_call+0xc8) [0x7f89c6a698]
  [bt] (8) /usr/lib/python3.8/lib-dynload/_ctypes.cpython-38-aarch64-linux-gnu.so(_ctypes_callproc+0x21c) [0x7f82107ab4]

terminate called after throwing an instance of 'thrust::system::system_error'
  what():  parallel_for failed: cudaErrorLaunchFailure: unspecified launch failure
Aborted (core dumped)

The exact sequence to build:
git clone --recursive https://github.com/dmlc/xgboost
cd xgboost
mkdir build
cd build
export CUDACXX=/usr/local/cuda-10.2/bin/nvcc
cmake .. -DUSE_CUDA=ON -DUSE_OPENMP=ON -DGPU_COMPUTE_VER=53
make -j4
cd ../python-package/
python setup.py install --use-cuda --use-openmp

Any help would be appreciated!

**Comment by trivialfis** [comment]
Closing due to stalled.
