### ISSUE TITLE
Feature weights for XGBRanker 

### ISSUE THREAD

**Issue by joshidp** [dmlc/xgboost#7202]
Hi,

Thanks for your great work.

I would like to know how can we set feature weights for XGBRanker ?

I am aware that you would want the data to guide the model rather than enforcing it but one logical case for this is when you have limited data and would like to try helping the process through your subject matter expertise.

Thanks

**Comment by trivialfis** [comment]
``` python

ranker = xgb.XGBRanker(tree_method="gpu_hist") # hist and exact also work
# feature_weights = ...
ranker.fit(X, y, qid=qid, feature_weights=feature_weights)
```
