### ISSUE TITLE
XGBoost External Memory option

### ISSUE THREAD

**Issue by bhavana3** [dmlc/xgboost#7203]
Hi,

I am trying to see if i can use XGBoost External Memory option for production, Could someone help to understand if this feature is still only for experimentation. Would it support any format (CSV, txt etc)?

Any other suggestions if input data (more than 384 GB) is unable to load into RAM (384 GB) for xgboost?

**Comment by trivialfis** [comment]
It's still only experimental.  But we are making lots of progress recently, see a new demo: https://github.com/dmlc/xgboost/blob/master/demo/guide-python/external_memory.py .
