### ISSUE TITLE
Message error with XGboost : WARNING : amalgation/../src/learner.cc:573 :

### ISSUE THREAD

**Issue by fabien-tell** [dmlc/xgboost#7204]
Hello,
I got this message in XGboost. I don't know what it means.
Thanks

WARNING : amalgation/../src/learner.cc:573 :
Parameters : {«importance»} might not be used
this may not be acurate due to some parameters are only used in langage binding but passe down to XGBoost core. Please open an issue if you find above cases.

**Comment by trivialfis** [comment]
Hi, it means you have passed a parameter called "importance", which doesn't actually exist in XGBoost.

**Comment by fabien-tell** [comment]
Thank you,
However, I do not remember having passed it. Here is my code : 
`library(xgboost)

# Define the control for CV
trControl <- trainControl(method = "cv",number = 10, search = "random")

# tuning parameters

tune_grid <- expand.grid(
  nrounds = 100,
  eta = c(0.3,0.6,0.9), # test over different values of eta
  max_depth = c(2, 3, 5,10,50), # test over different values of depth
  gamma = c(0,2,4,10,50), # test over different values of gamma
  colsample_bytree = 1,
  min_child_weight = 1,
  subsample = 0.5
)



Xboost_mtry <- train(Dep_Block~.,
    data = df_gene_Block,
    method = "xgbTree",
    metric = "Kappa",
    trControl = trControl,
    importance = TRUE, tuneGrid = tune_grid,
    #nthreads = no_cores, 
    preProcess= c("center", "scale")) 


print(Xboost_mtry)
plot(Xboost_mtry)


`

**Comment by trivialfis** [comment]
Could you please share a more complete snippet?  I see

``` R
metric = "Kappa",
trControl = trControl,
importance = TRUE, tuneGrid = tune_grid,
#nthreads = no_cores,
preProcess= c("center", "scale"))
```

I can't be entirely sure what exactly is being called here.

**Comment by fabien-tell** [comment]
Hello,
I'm sorry being so stupid, you're right. I apologize for wasting your time. Next time, I will read my code ten times before asking a question.
I toggled importance to FALSE and now it works. 
BTW, how can I retrieve (to save it) the accuracy value.
Thanks

**Comment by trivialfis** [comment]
No worries.  Feedback helps us understand where we can improve our API.

For saving the evaluation results, you can try:
```
bst <- xgb.train()
bst$evaluation_log  # save this
```
