### ISSUE TITLE
Unable to use v1.1.1.1 XGB models on v0.6.4.1 

### ISSUE THREAD

**Issue by LordRudolf** [dmlc/xgboost#7207]
Hello,

I am having an XGB model built via xgboost version 1.1.1.1 (on Microsoft R Open v 4.0.2). I need to use it for new predictions but the new prediction API is using an older R version: Microsoft R Open v3.4.4 which is also limited to older xgboost version; in this case, v0.6.4.1. The model file has been migrated from the R versions using the .rds file extension, indicating the workspace format version = 2. 

When trying to make a prediction from model build on v1.1.1.1 via xgboost.predict function from xgboost v0.6.4.1 I am facing the following error code with the error trace:

```
 Error in xgb.Booster(modelfile = bst$raw) : 
  [14:14:55] amalgamation/../src/gbm/gbm.cc:20: Unknown gbm type 
8. xgb.Booster(modelfile = bst$raw) 
7. xgb.Booster.check(object, saveraw = FALSE) 
6. predict.xgb.Booster(modelFit, newdata, ntreelimit = modelFit$niter) 
5. predict(modelFit, newdata, ntreelimit = modelFit$niter) at xgbDART.R#208
4. method$prob(modelFit = modelFit, newdata = newdata, submodels = param) 
3. probFunction(method = object$modelInfo, modelFit = object$finalModel, 
    newdata = newdata, preProc = object$preProcess) 
2. predict.train(test_model, df, type = "prob") 
1. predict(test_model, df, type = "prob") 
```

There is no option upgrading the R version of the API. Also, retraining the model on the older xgboost version would be costly. Therefore, is there any other workaround? E.g., converting newer version models or adjust older version predict function?

**Comment by trivialfis** [comment]
Unfortunately that's quite impractical.  My recommendation is just to upgrade xgboost.
