### ISSUE TITLE
Conditional jump or move depends on uninitialised value(s)

### ISSUE THREAD

**Issue by EdvardD** [dmlc/xgboost#7209]
Hello folks,

I’m trying to use C API inference and getting the valgrind error “Conditional jump or move depends on uninitialised value(s)” on the model initialization.

I put together an MWE:
Here is the simple model trained with scikit-learn and C++ inference code: https://pastebin.com/WYua9BEz.
And the valgrind error: https://pastebin.com/gq4cwewj.

Setup
Ubuntu 20.04, linux kernel 5.4.0-77-generic, xgboost from master (commit 9c6e791), I compiled the binary with clang++ 8.0.1-9.

Interesting thing is that the error doesn’t appear when I compile with g++ 9.3.0.

I’m wondering if I do something wrong or if it’s a known issue?

**Comment by trivialfis** [comment]
Is it coming from dmlc parameters initialization?  If so then it's fine.

**Comment by EdvardD** [comment]
Here is the stack of calls:
main
XGBoosterLoadModel
xgboost::LearnerIO::LoadModel
xgboost::obj::RegLossObj<xgboost::obj::LogisticClassification>::LoadConfig
xgboost::FromJson<xgboost::obj::RegLossParam>
dmlc::parameter::ParamManager::RunInit
dmlc::parameter::ParamManager::RunUpdate

So it looks like coming from parameters initialization.

**Comment by trivialfis** [comment]
I think valgrind has some issues with static memory initialized at load time.  We will probably remove the dmlc parameter struct at some point.  For now, you can safely ignore such warnings.
