### ISSUE TITLE
XGBoost4J: model predicts different probabilities depending on number of training samples

### ISSUE THREAD

**Issue by rebsp** [dmlc/xgboost#7210]
### Steps to reproduce
We have trained a binary classifier on a numerical feature vector of size `(3_900_000, 686)`. The training happened with the Python XGBoost library and the sklearn-API (`XGBClassifier`). If we load the model with XGBoost4J in our Java environment, we get different predictions compared to loading the model in Python and predicting with the same input vector. The worst part is that the probabilities are not just a bit off but it is actually flipping from predict 1 to predict 0.

Probability of class 1 with large model in Java:
![image](https://user-images.githubusercontent.com/6863864/132208569-866381c9-a8da-4d42-afea-3ee5af710521.png)
Probability of class 1 with large model in Python:
![image](https://user-images.githubusercontent.com/6863864/132208832-3626188a-d842-4dda-bdea-f62c7ff88dc6.png)

If we repeat the model training with the same parameters but fewer rows (e. g. `(1_000_000, 686)`) the probabilities match between Java and Python.

Probability of class 1 with small model in Java:
![image](https://user-images.githubusercontent.com/6863864/132208907-3b0f23fd-504b-4131-a7f4-63cb75da21ef.png)
Probability of class 1 with small model in Python:
![image](https://user-images.githubusercontent.com/6863864/132208977-a4ef41ca-3987-448d-b068-546f06f5093e.png)

Unfortunately I cannot hand out a sample code example because of IP restrictions, but I could provide the two models through DM's or email for debugging purposes if need be.

For validation purposes, we have converted the model into [ONNX format](https://onnxruntime.ai/docs/reference/api/java-api.html) and tested again. This time the models yield the same results independent of training sample size, thus confirming our assumption that the XGBoost4J library is the culprit.

### Environment
* OS
  tested with Windows 10, Ubuntu 18.04
* Python
  tested with 3.7.10, 3.8.10
* XGBoost
  1.4.1
* Java SDK
  Liberica 11.0.11 (LTS)

Thanks for looking into this, much appreciated!

**Comment by rebsp** [comment]
possibly related to https://github.com/dmlc/xgboost/issues/7103#issuecomment-879587422 ?

> This numerical error in the inference stage is more serious when the data size is pretty large, e.g., m = 10000000.

**Comment by trivialfis** [comment]
Thanks for opening the issue.  Will look into it.

**Comment by trivialfis** [comment]
Could you please share your model with me?  I have my email address in my github profile.

**Comment by trivialfis** [comment]
Since you did not share your jvm code, here is my guess.   I think it might be the case that you created the `DMatrix` in java without specifying the `missing` parameter in the constructor.  Could you please try to create a DMatrix in this way:

``` java
DMatrix X = new DMatrix(arr, 1, arr.length, Float.NaN);
```

**Comment by trivialfis** [comment]
It should also be reproducible with a smaller model.  The jvm packages have constructors that implicitly specify the missing value to be 0, which seems to be odd to me. (I'm just getting familiar with jvm package, actually, I just looked up how to use maven to debug this issue ...)

On Python and R, the default missing value should be `NaN` since 0 is a meaningful value for XGBoost (tree splitting at 0).  If 0 is specified as a missing value, then all 0s in the input will be removed during the construction of DMatrix, hence the wrong output.

**Comment by trivialfis** [comment]
If your model doesn't split at 0, then the output is probably the same.

**Comment by rebsp** [comment]
Hi @trivialfis 

I just did some checks and it the `missing` parameter is indeed what caused our problems. It just so happened to be that it only impacted the large model which split at 0.
Thanks for helping us out, much appreciated! 

Issue can be closed.
