### ISSUE TITLE
Building as R package?

### ISSUE THREAD

**Issue by david-cortes** [dmlc/xgboost#7223]
The installation instructions for R for building from source in linux indicate to use the CMake system:
https://xgboost.readthedocs.io/en/latest/build.html#installing-the-development-version-linux-mac-osx

XGBoost however is also available through CRAN, which requires a different package structure (e.g. without a subfolder `R-package`) as it should be an installable R package file (.tar.gz) that would work through R's own build system.

Other packages such as lightgbm have a script to autogenerate an installable R package (https://github.com/microsoft/LightGBM/blob/master/build-cran-package.sh). Does XGBoost happen to have something similar? If so, is it documented somewhere?

**Comment by hcho3** [comment]
You can run `make Rbuild` at the root directory.

**Comment by david-cortes** [comment]
Thanks, would be good to add it to the docs.
