### ISSUE TITLE
How do I get Feature orders from xgboost pickle model

### ISSUE THREAD

**Issue by nivedangowda** [dmlc/xgboost#7229]
I am trying to get predictions using my xgboost pickle model using the new data but getting the error "ValueError: Feature shape mismatch"

The reason for this is I need to pass the feature names exactly in the same order model was built. For that I am using the following code but it's not working:-

    feature_order= model_pkl.get_booster().feature_names
    X_new = X_new[feature_order]
    Y_static = model_pkl.predict(X_new)

feature_order is returning "None" it was working in the xgboost version 1.1.1. But Now I am using the xgboost version 1.4.2.

Can you guys please help me in getting the feature order from my xgboost pickle model? So that I can pass my data also in the same order and not run into the error?

**Comment by trivialfis** [comment]
Could you please check that the `feature_names` is not `None`?

**Comment by trivialfis** [comment]
> feature_order is returning "None" i

NVM.  I see.  In the latest XGBoost we removed the feature name generation.  If you trained the model with numpy instead of pandas dataframe the booster won't have feature names in it.

**Comment by trivialfis** [comment]
You can still assign the feature names by yourself for both `DMatrix` and `Booster`.

**Comment by nivedangowda** [comment]
Hi  trivialfis Thanks for your response. 

Can you please be more specific with a code or something on how I can assign feature names for both DMatrix and Booster?

**Comment by trivialfis** [comment]
For scikit-learn interface (the one that you are using)

``` python
# Replace the feature names as needed, this is just an example, `feature_names` is a Python attribute
my_feature_names = [str(i) for i in range(model_pkl.n_features_in_)]
model_pkl.get_booster().feature_names = my_feature_names
```

For native interface:

``` python
Xy = xgb.DMatrix(X, y, feature_names=my_feature_names)
# booster will have `my_feature_names`, so is the `DMatrix` Xy
booster = xgb.train({}, Xy, ...)
assert booster.feature_names
```

**Comment by nivedangowda** [comment]
I guess you are assuming that i have built my model passing the numpy array but that is not true rather my model is built using GridsearchCV as follows:-

x = data_best_features.drop(['target'],axis=1)
Y = data_best_features['target']

# train and test split using train_testt_spilt
X_train, X_test, y_train, y_test = train_test_split(x, Y, test_size=0.25, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

parameters = {'nthread':[8], #when use hyperthread, xgboost may become slower
              'objective':['reg:linear'],
              'learning_rate': [0.3,0.4,0.5,0.7,0.8,0.9,0.1], #so called `eta` value
              'max_depth': [5,6,7,8,9,10,11,12,13,14,15],
              'min_child_weight': [1,2,3,4,5,6],
              'silent': [1],
              'subsample': [0.4,0.5,0.6,0.7,0.8],
              'colsample_bytree': [0.4,0.5, 0.6, 0.7, 0.8],
              'n_estimators': [500,700,900]}

xgb_grid = GridSearchCV(xgb.XGBRegressor(),
                        parameters,
                        cv = 2,
                        n_jobs = 5,
                        verbose=True)

xgb_grid.fit(X_train, y_train)

model = xgb_grid.best_estimator_
model.fit(X_train,y_train)

May be using GridsearchCV is a problem?

**Comment by trivialfis** [comment]
You can still assign the feature names after fit.  In before XGBoost generates pseudo feature names we just removed the process.

``` python
model.fit(X_train,y_train)
model.get_booster().feature_names = my_feature_names
```
