### ISSUE TITLE
Most important Features' NAME

### ISSUE THREAD

**Issue by benedettapedica** [dmlc/xgboost#7256]
I'm having some troubles understanding how to display the name (or the index) of features my model is selecting during the fit. 
I'm using scikit-learn function for selecting features and training an XGBoost model.
This is my code: 
``` python
from sklearn.feature_selection import SelectFromModel
thresholds = sort(optimised_XGBoost.feature_importances_)
for thresh in thresholds:
     # select features using threshold
    selection = SelectFromModel(optimised_XGBoost, threshold=thresh, prefit=True)
    select_X_train = selection.transform(X_train)
    # train model
    selection_model = XGBClassifier(use_label_encoder =False)
    selection_model.fit(select_X_train, Y_train)
    # eval model
    select_X_test = selection.transform(X_test)
    predictions = selection_model.predict(select_X_test)
    accuracy = accuracy_score(Y_test, predictions)
    print("Thresh=%.3f, n=%d, Accuracy: %.2f%%" % (thresh, select_X_train.shape[1], accuracy*100.0))
```
How can I display the n features that at each cycle my model is selecting?
I tried with  the function get_support but it says that is not working with XGBoost model.

**Comment by trivialfis** [comment]
I tried the latest XGBoost with tree model, `get_support` works and `feature_importances_` is accessed by sklearn internally.
