### ISSUE TITLE
Dealing with link-functions (here: objective = "count:poisson“)

### ISSUE THREAD

**Issue by FranziskaMaria** [dmlc/xgboost#7264]
Dear all! I’m using xgboost for poisson distributed data in my master thesis. Unfortunately, I cannot find any literature that describes what exactly happens when I set objective = "count:poisson“ in xgb.train. I have shortly summarized what I suppose could happen in this case - see [XGBoost.pdf](https://github.com/dmlc/xgboost/files/7231156/XGBoost.pdf). Could you please tell me, whether this is true?

**Comment by trivialfis** [comment]
Hi, I haven't looked into the slides in detail yet.  The link function is the canonical link I believe you are correct.  But could you please check the sign of the first-order gradient?

**Comment by trivialfis** [comment]
NVM.  The sign is correct.

**Comment by trivialfis** [comment]
Closing the issue now since I think both gradient and hessian are correct. (aside from weighted data).
