### ISSUE TITLE
[Task] XGBoost supports rapids plugin

### ISSUE THREAD

**Issue by wbo4958** [dmlc/xgboost#7268]
[Rapids plugin](https://github.com/NVIDIA/spark-rapids) is a Spark plugin which accelerates Spark with GPUs. With spark-rapids, most of the Spark operators can be run on GPU, and the final result can also reside in GPU. At the same time, XGBoost library has supported building DMatrix or DeviceQuantileDMatrix directly from GPU memory. So spark-rapids can accelerate XGBoost from End to End.

Since we have https://github.com/dmlc/xgboost/pull/7195 (which supports cudf on xgboost4j) merged, I'd like to add spark-plugin support for xgboost4j-spark-gpu.

Our goal should be support both CPU and GPU pipeline in xgboost4j-spark-gpu. 

To achieve this, we need to do,

- [x] Add DeviceQuantileDMatrix for scala supporting
- [x] Unlink everything in xgboost4j-spark-gpu
- [x] Add XGBoostClassifier train on GPU supporting
- [x] Add XGBoostClassifier transform  on GPU supporting
- [x] Add XGBoostRegression train on GPU supporting
- [x] Add XGBoostRegression transform  on GPU supporting
- [x] Add unit tests

**Comment by benjamincitrin** [comment]
It looks like this was finished in v1.6.0

**Comment by wbo4958** [comment]
Yes, it's done. Let me close this issue.
