### ISSUE TITLE
Single node 'gpu_hist' is not reproducible

### ISSUE THREAD

**Issue by debinqiu** [dmlc/xgboost#7295]
XGBoost model is still not reproducible on single device with tree_method = 'gpu_hist'. If the DMatrix is loaded into the single gpu device, the model is replicated in the sense that every time you train the model, the result will be the same because the DMatrix is cached in the device as I observed. However, if you use another device, or load DMatrix again, the model will be slightly different from the previous one.

**Comment by trivialfis** [comment]
> or load DMatrix again

Hi, could you please share an example script that the training is not reproducible?

**Comment by debinqiu** [comment]
@trivialfis Thanks for the quick response. Sorry, I can't share the data and don't have the method to generate such data. It does not always happen because on some data I can 100% replicate my result, so I think it may be due to a special case on some features. 
The following is my sample code and observation (result is not real but for demonstration purpose). Although the auc is very close, but they are not exactly the same. 

xgboost version :1.4.2

params = {'eta':0.05, 'max_depth':6, 'alpha':50.0, 'lambda':10.0, 'objective':'binary:logistic', 'eval_metric':'auc',
                  'tree_method':'gpu_hist'
}
for gpu_id in [0,1,2,3]:
        params.update({'gpu_id':gpu_id})
        xgbmodel = xgb.train{params, xgb.DMatrix(train_data, label = y), 1000)
        y_pred = xgbmodel.predict(xgb.DMatrix(train_data))
        auc = roc_auc_score(y, y_pred) 
        print(gpu_id, auc)

>>>
0 0.62433
1  0.62427
2 0.62437
3 0.62396

I will try to test some other simulated data to see if I can produce similar issue. I will update it once I have it.

**Comment by trivialfis** [comment]
Feel free to open a new issue if you have a reproducible example.
