### ISSUE TITLE
Confusion about parameters sklearn API(reg_lambda : float (xgb's lambda) and reg_alpha : float (xgb's alpha))

### ISSUE THREAD

**Issue by Peishen-Jia** [dmlc/xgboost#731]
for sklearn api,
reg_alpha : float (xgb's alpha)
        L2 regularization term on weights
reg_lambda : float (xgb's lambda)
        L1 regularization term on weights

while in xgboost doc,
lambda [default=1]
L2 regularization term on weights
alpha [default=0]
L1 regularization term on weights

isn't it confusing?

**Comment by tqchen** [comment]
Both arguments are correct and equivalent to each other
