### ISSUE TITLE
save the best model using early stop

### ISSUE THREAD

**Issue by JunWorks** [dmlc/xgboost#732]
```{r, echo =F}
clf <- xgb.train(params = param, data = dtrain.1,
               nrounds = 3500, watchlist=list(validation1=dcv), early.stop.round = 100, 
               verbose = T, print.every.n = 10, maximize = T)

```
Is there a way to save the best model while using early stop?

**Comment by terrytangyuan** [comment]
@JunWorks So as you can see [here] (https://github.com/dmlc/xgboost/blob/master/R-package/R/xgb.train.R#L223), if you provide `save_period ` and `save_name `, you will save the model before early stopping breaks the loop.
