### ISSUE TITLE
Parameter tuning with Cross Validation and early stopping 

### ISSUE THREAD

**Issue by eduardcmp** [dmlc/xgboost#7328]
Hello,

I am performing hyperparameter tuning and I want to use early stopping. For this prupose I’ve created a parameter grid and I’m looping over it and using the built-in method xgb.cv

This method accepts early stopping but I’m wondering how it uses it internally. I’m afraid it doesn’t split the data in train, val and test for each of the K-folds as it should be done and instead it only splits it in train and test as it’s usually done for CV.

Thanks in advance

**Comment by trivialfis** [comment]
> This method accepts early stopping but I’m wondering how it uses it internally.

It updates all folds for each iteration until early stopping criteria are met.  The score is calculated as mean and std.
