### ISSUE TITLE
[jvm-packages] Rabit tracker and clients have issues in containerized environments

### ISSUE THREAD

**Issue by arunbhat** [dmlc/xgboost#7352]
Rabit tracker does not work well in setups where each compute node is inside a Linux container with a virtual network interface that goes through a bridge. Nodes then appear to all have the same IP. For example in a spark cluster with 2 nodes (1 driver, 1 executor), both the containers that have spark installed have the same ip address. The underlying hosts do have unique ip addresses. We see these errors in the executors

retry connect to ip(retry time 1): [10.0.3.103]
retry connect to ip(retry time 2): [10.0.3.103]
retry connect to ip(retry time 3): [10.0.3.103]
retry connect to ip(retry time 4): [10.0.3.103]

It would be very beneficial to be able to lookup the tracker_uri from an environment variable. We were able to get over that by modifying tracker.py to provide the right address to slave_envs. After this change, the tracker now goes into an infinite loop in assign_rank since the executor ip address is the address of the gateway and hence nerr in the following piece of code is always > 0
``` python
 for r in conset:
                self.sock.sendstr(wait_conn[r].host)
                self.sock.sendint(wait_conn[r].port)
                self.sock.sendint(r)
            nerr = self.sock.recvint()
            if nerr != 0:
                continue
```
We were able to get over this too by modifying allreduce_base.cc to lookup the executor hostname from an environment variable. This follows the design pattern in spark where a custom host name can be used. See [here](https://github.com/apache/spark/blob/e5b01cd823990d71c3ff32061c2998a076166ba8/core/src/main/scala/org/apache/spark/util/Utils.scala#L1045). Basically the executor host name is passed from the executor to the driver when the rabit tracker connection is established. Please see the attached diffs below after we got it working. Obviously this covers just the happy path and some defensive checks and generalizing will need to be done.

The diffs are based off of v1.1.1 as that version supports scala 2.11. Would be great if the change is applied to the latest branches that support scala 2.11 and scala 2.12.

[finalDiff2.log](https://github.com/dmlc/xgboost/files/7384995/finalDiff2.log)

**Comment by trivialfis** [comment]
So it's about the design of the networking interface f https://github.com/dmlc/xgboost/pull/6869#pullrequestreview-641381474 .

**Comment by wbo4958** [comment]
@arunbhat 

I just had a PR to fix this issue by specifying the rabit tracker host IP
``` scala
val hostIP = xx.xx.xx.xx
"tracker_conf" -> TrackerConf(0L, "python", hostIp)
```

The PR will be shipped in 1.6.0 release.

**Comment by trivialfis** [comment]
Aside from the fix by @wbo4958 , the tracker also uses port 0 to obtain available ports from the system.  The issue should be fixed now.  Feel free to reopen if it persists.

**Comment by arunbhat** [comment]
Thanks! Is the PR this [one](https://github.com/dmlc/xgboost/pull/7808/files)? Are changes needed in allreduce_base.cc too? And how exactly is the hostIp set (not sure which configuration file and where to set it). We would need to automate the setting of the host-ip in our clusters (where the workers run inside containers).
