### ISSUE TITLE
SEGFAULT on MacOS with scikit-learn==1.0.0

### ISSUE THREAD

**Issue by PrimozGodec** [dmlc/xgboost#7355]
xgboost segfaults in combination with scikit-learn==1.0.0 and works fine with scikit-learn==0.24

Steps to reproduce:
1. Install `scikit-learn==1.0.0` and `xgboost==1.5.0`
2. Run this simple script
   ```
    import numpy as np
    import xgboost
    
    x = np.random.random((150, 4))
    y = np.random.randint(0, 3, 150)
    
    learner = xgboost.XGBClassifier()
    learner.fit(x, y)
   ```

I found out that scikit-learn brings its own version of libomp library together with the package. It is stored in `sklearn/.dylibs/libomp.dylib`. When I remove it from sklearn segfault does not happen. When libomp is present in sklearn and I remove a global version from the computer xgboost does not work since it cannot find the library. It shows that xgboost is actually not using the libomp library from scikit-learn but there must be some coincidence.

When downgrading scikit-learn to 0.24 it still ships its own version of libomp but the segfaul does not happen.

**Comment by trivialfis** [comment]
Any chance this is the same issue with https://github.com/dmlc/xgboost/issues/7039 ?

**Comment by PrimozGodec** [comment]
I am not sure. From what can I read there downgrading limpomp to 11 helped. In my case, it does not. 
Also, the mentioned issue was opened before scikit-learn=1.0.0 was released. My issue started to appear after scikit-learn==1.0.0 release (Sep 24). As I mentioned, with an older version of scikit-learn everything works fine.
