### ISSUE TITLE
leaf index

### ISSUE THREAD

**Issue by ICDI0906** [dmlc/xgboost#7363]
how can I get the leaf index in a distribution environment?

**Comment by ICDI0906** [comment]
Thanks for your reply~But when I use the function predictLeaf, I found the size of the index array is different from n_estimator, Specifically, for binary classification, the size of the index array is equal to 2 * n_estimator, for multi-class classification, it is equal to classNum * n_estimator + 2,  do you know why? looking forward to your reply!

**Comment by trivialfis** [comment]
The strict shape of predict leaf output is actually 4 dim, but java/scala don't have a canonical n-dim array implementation like numpy on Python, as a result xgboost4j returns concatenated dimensions.
