### ISSUE TITLE
check for validate parameters when initiate?

### ISSUE THREAD

**Issue by yitang** [dmlc/xgboost#739]
Hi, thanks for providing this amazing package.

I've been moving from R to Python, and get lost in the different naming for same paramteres. also, I noticed that when initiate a xgboost model, it won't check for validate paramters, for example,

```
bst = xgb.Booster({'lala':4}) 
cv_res = xgb.cv({'lala':4}, dtrain)
```

both work fine. And I can't find how the "lala" parameter is used after reading the source code.

Not checking validate parameters leaves a door for user making bugs when move between different xgboost wrappers. Previously I was using the sklearn wrapper and the regularisation parameters is called "learning_rate", and in the `xgb.cv`, the name is "eta". I didn't aware of this bug until I saw someone else's code and the program has been running for 30 hours...

Yi

**Comment by Far0n** [comment]
Hey yitang,

this is a good suggestion. 

As a side note: it doesn't matter if u call your param "eta" or "learning_rate" in the python wrapper. It is not documented (at least I'm not aware of), but the core part of xgb just scans the params for known names.

**Comment by ivallesp** [comment]
In the same line, I would like to say that I found important differences in the result when naming the boosting parameters with the prefix "bst:". What's wrong with that? I also tried to add a parameter with a mistake and no error was returned...

**Comment by tqchen** [comment]
@ivallesp bst prefix is deprecated in the newest version. If you find it anywhere in the doc, please point it out and send a PR to fix it. Thanks so much
