### ISSUE TITLE
Row Indices in dtrain [R]

### ISSUE THREAD

**Issue by acamachodepass** [dmlc/xgboost#740]
I am writing a custom evalerror function for xgb.cv.

evalerror signature's parameters are: function(preds, dtrain)

I need to now the row indices of the parameter dtrain, since it is a sample of the whole train data.

getinfo(object, ...) does not provide this information.

How can I get the required indices?

**Comment by tqchen** [comment]
Row indices are not stored in the sliced DMatrix as far as I recall. But I recall that R package support attach certain arrays to a DMatrix and get the slice when slice was called, @hetong007 can you confirm?

**Comment by hetong007** [comment]
There are two ways to do so:

1. Use this not exported function: https://github.com/dmlc/xgboost/blob/master/R-package/R/utils.R#L133
2. Assign an `attr` to your dtrain before feeding it to the training function, an example: https://github.com/dmlc/xgboost/issues/513

**Comment by acamachodepass** [comment]
Using attr as in #513 solves the problem.

The number of rows of dtrain slice can either be obtained using:
a) getinfo(dtrain, 'nrow'),
b) not exported function xgb.numrow(dtrain) inside evalerror(.) https://github.com/dmlc/xgboost/blob/master/R-package/R/utils.R#L133.

xgb.numrow <- function(dmat) {
  nrow <- .Call("XGDMatrixNumRow_R", dmat, PACKAGE="xgboost")
  return(nrow)
}
