### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by kidman99** [dmlc/xgboost#7400]
Step 1. cmake .. -G"Visual Studio 16 2019" -A x64  -DUSE_CUDA=ON -DBUILD_WITH_CUDA_CUB=ON

Step 2. cmake --build . --target xgboost --config Release

Step 3. python setup.py install --use-cuda

I got the following error:

INFO:xgboost install_lib:Installing shared library: build\temp.win-amd64-3.8\Release\xgboost\lib\xgboost.dll
error: can't copy 'build\temp.win-amd64-3.8\Release\xgboost\lib\xgboost.dll': doesn't exist or not a regular file

Could anyone please advise how this can be resolved?

Thanks!

**Comment by trivialfis** [comment]
Hi, first how did you obtain the source code?  If you are using git, then you need to execute:

``` sh
git clone --recursive https://github.com/dmlc/xgboost.git
```
notice the recursive parameter.

Secondly, the cmake steps are not necessary unless you want to modify the c++ source code, otherwise `step 3` should be able to handle everything.
