### ISSUE TITLE
XGBoost error : Check failed: layer_end == 0 (190 vs. 0) : Linear booster does not support prediction range

### ISSUE THREAD

**Issue by marboe123** [dmlc/xgboost#7460]
```
Error in predict.xgb.Booster(model_n, my_matrix) : 
C:\Users\Administrator\workspace\xgboost-win64_release_1.5.0\src\gbm\gblinear.cc:67: Check failed: layer_end == 0 (190 vs. 0) : Linear booster does not support prediction range.
```
I receive the error above after I do predict for a XGBoost model with booster = "gblinear" in R. I intend to predict probabilities for a binary target variabele.

I receive the error at the last line of this code:

```
      model_n <- xgb.train(data = xgb_trainval,
                         booster = "gblinear",
                         objective = "binary:logistic",
                         nrounds = 300,
                         eval_metric = "auc",
                         early_stopping_rounds = 30,
                         print_every_n = 100,
                         watchlist = list(train = xgb_trainval, val = xgb_val)
    )

my_matrix <- as.matrix(my_df)
my_matrix <- xgb.DMatrix(data = my_matrix)
predict(model_n, my_matrix)
```

my_df is a dataframe with a one-hot-encoded factor and 4 numerical variables.

The process xgb.train is running fine with reporting of the AUC's.

Initially I had used the same code with booster = "gbtree" and the identical data. This was running correctly and did not give any errors with predict.

Any idea what could be the cause?

Thanks a lot!

**Comment by marboe123** [comment]
Thank you.

I suppose it is no solution to delete `early_stopping_rounds = 30,` from model_n in my code above, since I receive the error below in that case:

```
Error in names(x) <- value : 
  'names' attribute [1] must be the same length as the vector [0]
```

Is it an unusual combination of commands that I use since I receive these errors?

**Comment by marboe123** [comment]
Do you mean that could run the code if I install an older version of xgboost? 

I try to install xgboost version 13.0 from the downloaded tar.gz file using this command in R 4.1.0 :

`install.packages("C:/xgboost_v13/xgboost-1.3.0.tar.gz", repos = NULL, type="source")`

Although this gives these errors:

```
Installing package into ‘C:/Users/myname/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
Warning in untar2(tarfile, files, list, exdir, restore_times) :
  failed to copy 'xgboost-1.3.0/jvm-packages/xgboost4j-gpu/../xgboost4j/src' to 'xgboost-1.3.0/jvm-packages/xgboost4j-gpu/src'
Warning in untar2(tarfile, files, list, exdir, restore_times) :
  failed to copy 'xgboost-1.3.0/jvm-packages/xgboost4j-spark-gpu/../xgboost4j-spark/src' to 'xgboost-1.3.0/jvm-packages/xgboost4j-spark-gpu/src'
Warning in untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
ERROR: cannot extract package from 'C:/xgboost_v13/xgboost-1.3.0.tar.gz'
Warning in install.packages :
  installation of package ‘C:/xgboost_v13/xgboost-1.3.0.tar.gz’ had non-zero exit status

```
Do you know what can be the cause?

Thanks a lot!

**Comment by marboe123** [comment]
Thank you trivialfis. As a temporary solution I did indeed succeed to run the code  in xgboost 1.2.0.1.tar.gz from here:

https://cran.r-project.org/src/contrib/Archive/xgboost/

**Comment by marboe123** [comment]
Thank you trivialfis.

I currently use xgboost with GPU support (r_gpu_win64) from this link:

https://s3-us-west-2.amazonaws.com/xgboost-nightly-builds/list.html

Will this fix also be included in the next r_gpu_win64?

**Comment by trivialfis** [comment]
Yes, I'm preparing a patch release.
