### ISSUE TITLE
（spark4j-spark）The number of num_workers cannot be increased (the maximum can be set to 4), the cluster queue limits Executor Cores: Maximum is 4， Is there any way to increase the number of num_worker, hope to increase to 10 or 20

### ISSUE THREAD

**Issue by greenary-John** [dmlc/xgboost#7461]
backround：
xgboost version 0.82
spark version 2.3.4

Driver Memory:
13g
Num Executors:
1000
Executor Memory:
14g
Executor Cores:
4

param：
spark.hadoop.parquet.enable.summary-metadata=false 
spark.executor.extraJavaOptions="-XX:MaxDirectMemorySize=2048m" 
spark.yarn.executor.memoryOverhead=2048 
spark.driver.maxResultSize=2048 
spark.dynamicAllocation.enabled=true 
spark.shuffle.service.enabled=true 
spark.dynamicAllocation.minExecutors=16 
spark.dynamicAllocation.maxExecutors=1024 
spark.dynamicAllocation.initialExecutors=16

If you need additional information, I will be more than happy to provide

**Comment by trivialfis** [comment]
I don't think that's an error from xgboost.  Feel free to correct me if I'm wrong @wbo4958 .

**Comment by wbo4958** [comment]
For cpu training pipeline, the num_worker should be less equal than the maximum total spark tasks. So you can set to any value according your cluster env.

**Comment by trivialfis** [comment]
Feel free to reopen if there's any further question.

**Comment by greenary-John** [comment]
我的队列资源CPU,内存充足，Num Executors也可以动态调整，但唯一是限制了Executor Cores最大为4
我不清楚是不是因为这个原因造成了我num_workers无法增大，超过4
Num Executors:也可以动态调整，到700-800也可以，为什么num_workers，不能超过4这是xgboost设计的问题吗？
我想确认的是一点：是不是num_workers必须小于Executor Cores？

**Comment by wbo4958** [comment]
The cluster should meet the requirement that `The total number of alive cpu cores >= numWorkers * sc.conf.getInt("spark.task.cpus", 1)`

The total number of alive cpu cores can be simply equal to `(total executors * exector cores)` if there is no extra job running on your cluster
