### ISSUE TITLE
（spark4j-spark）ExecutorLostFailure (executor 1827 exited caused by one of the running tasks) Reason: Container:container_**: on host: ****.bj marked as failed. Exit status: 255. Diagnostics: [2021-11-22 20:58:26.551]container-launch with exit code: 255

### ISSUE THREAD

**Issue by greenary-John** [dmlc/xgboost#7462]
detail：
ExecutorLostFailure (executor 1827 exited caused by one of the running tasks) Reason: Container:container_**: on host: **.bj marked as failed. Exit status: 255. Diagnostics: [2021-11-22 20:58:26.551]container-launch with exit code: 255
[2021-11-22 20:58:26.553]Container exited with a non-zero exit code 255. Error file: prelaunch.err.
Last 4096 bytes of prelaunch.err :
Last 4096 bytes of stderr :
log4j:WARN Continuable parsing error 45 and column 23
log4j:WARN The content of element type "log4j:configuration" must match "(renderer*,throwableRenderer?,appender*,plugin*,(category|logger)*,root?,(categoryFactory|loggerFactory)?)".
AssertError:maxdf must be smaller than FDSETSIZE

[2021-11-22 20:58:26.559]Container exited with a non-zero exit code 255. Error file: prelaunch.err.
Last 4096 bytes of prelaunch.err :
Last 4096 bytes of stderr :
log4j:WARN Continuable parsing error 45 and column 23
log4j:WARN The content of element type "log4j:configuration" must match "(renderer*,throwableRenderer?,appender*,plugin*,(category|logger)*,root?,(categoryFactory|loggerFactory)?)".
AssertError:maxdf must be smaller than FDSETSIZE

backround：
xgboost version 0.82
spark version 2.3.4

Driver Memory:
13g
Num Executors:
1000
Executor Memory:
14g
Executor Cores:
4

param：
spark.hadoop.parquet.enable.summary-metadata=false
spark.executor.extraJavaOptions="-XX:MaxDirectMemorySize=2048m"
spark.yarn.executor.memoryOverhead=2048
spark.driver.maxResultSize=2048
spark.dynamicAllocation.enabled=true
spark.shuffle.service.enabled=true
spark.dynamicAllocation.minExecutors=16
spark.dynamicAllocation.maxExecutors=1024
spark.dynamicAllocation.initialExecutors=16

If you need additional information, I will be more than happy to provide

**Comment by trivialfis** [comment]
> xgboost version 0.82

Unfortunately, it has been deprecated for a long time now, please upgrade XGBoost.  Also, please provide a reproducible example similar to the one described in https://stackoverflow.com/help/minimal-reproducible-example .

Feel free to reopen if there's a reproducible example or any further questions.
