### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by bolongcheng** [dmlc/xgboost#7463]
[line 42](https://github.com/dmlc/xgboost/blob/d33854af1b4f783c5230bb21aff7234b16f409f7/python-package/xgboost/training.py#L42) in `xgboost/training.py`

```
"Bost `feval` and `custom_metric` are supplied......
```
Bost -> Both ?

**Comment by trivialfis** [comment]
Good catch!  Would you like to open a PR for the fix?

**Comment by bolongcheng** [comment]
Sure. I can do that.
