### ISSUE TITLE
Compilation error under Visual Studio above version 15.0

### ISSUE THREAD

**Issue by GinkoBalboa** [dmlc/xgboost#7464]
Hi, 

After a recent change in the function declaration given here:

https://github.com/dmlc/xgboost/blob/d33854af1b4f783c5230bb21aff7234b16f409f7/src/data/array_interface.h#L471

The compilation fails under Visual Studio versions greater than 15.0.

Elaborate on the error is given here:

[Link to compile error C3615](https://docs.microsoft.com/sr-cyrl-rs/cpp/error-messages/compiler-errors-2/compiler-error-c3615?view=msvc-150)

VS complains because of **constexpr** declared function has in its body a not valid constexpr context. 

When I remove the **constexpr** specifier the code compiles (tested in VS 2019 with v142) also compiles under Linux (Ubuntu 20.04).

Regards

**Comment by trivialfis** [comment]
That's weird.  We are testing xgboost on github action with 2019.

**Comment by trivialfis** [comment]
Anyway, I opened a PR https://github.com/dmlc/xgboost/pull/7466 .  Feel free to try it out.

**Comment by GinkoBalboa** [comment]
Thanks for the fix, it compiles now. I agree it was a weird bug, however, now it is gone.
