### ISSUE TITLE
Kernel dies when using "gpu_hist"

### ISSUE THREAD

**Issue by renjiege** [dmlc/xgboost#7477]
The following code works fine when the model is trained with CPU: 
`xgboost = XGBClassifier(max_depth=3, n_estimators=300, learning_rate=0.1)`

but it faills with GPU (jupter kernell dies): 
`xgboost = XGBClassifier(max_depth=3, tree_method='gpu_hist', n_estimators=300, learning_rate=0.1)`
The training data is a 20808x5314541 sparse matrix (tfidfvectorized matrix). So I guess it is a memory issue?

My XGboost version is 0.81 and the CUDA version is 11.0. GPU is Nvidia RTX 3080 10GB. Do I need to increase my GPU memory to make it work? I wonder if there is a workaround?

**Comment by trivialfis** [comment]
> So I guess it is a memory issue

That's very likely.

> My XGboost version is 0.81

Please upgrade XGBoost to the latest.  The memory consumption should be better for these extremely wide and sparse datasets, but still we haven't spend effort on optimizing them on GPU.

**Comment by renjiege** [comment]
Thanks @trivialfis. I will give the latest version a shot.

**Comment by trivialfis** [comment]
Latest xgboost should have reasonable memory consumption with sparse datasets.  Feel free to reopen if the issue persists.
