### ISSUE TITLE
Docs: Use uppercase omega for overall model complexity cost, lowercase omega for per tree complexity cost

### ISSUE THREAD

**Issue by vertexcite** [dmlc/xgboost#7480]
Documentation suggestion:
For https://github.com/dmlc/xgboost/blob/master/doc/tutorials/model.rst, use lowercase omega for per tree complexity cost, and uppercase omega for overall model complexity cost.  Currently, uppercase omega used for both.  

Similarly, https://raw.githubusercontent.com/dmlc/web-data/master/xgboost/model/step_fit.png should have :math:`\Omega(\theta)` (i.e. uppercase omega for overall model complexity cost: function applied to parameters theta, not individual tree f).

**Comment by hcho3** [comment]
Thanks for your suggestion. Would you be willing to submit a pull request?

**Comment by vertexcite** [comment]
@hcho3 Apologies for missing your reply until now.  I've created a pull request for the .rst doc.  Do you know how the image https://raw.githubusercontent.com/dmlc/web-data/master/xgboost/model/step_fit.png  was produced?

**Comment by trivialfis** [comment]
Closed by https://github.com/dmlc/xgboost/pull/7532
