### ISSUE TITLE
Mistake in "Intro to Boosted Trees"?

### ISSUE THREAD

**Issue by claudio525** [dmlc/xgboost#7485]
I believe there is a mistake in the objective functions for a tree at timestep t
![image](https://user-images.githubusercontent.com/45545396/143496267-ac4e005b-ddd2-441c-ab5c-621642ccb10d.png)
the regularization term in the top line in both cases is a sum over t. However since this is the objective function for the single tree at timestep t, this should just be the regularization term for that tree (not all previous ones), from my understanding. 
The 2nd line in both cases is correct, i.e. the regularization term is just for the current tree at timestep t

If someone can confirm that my understanding is correct and this is actually a mistake then I'm happy to put in a PR for this.

**Comment by hcho3** [comment]
>  since this is the objective function for the single tree at timestep t, this should just be the regularization term for that tree 

No, the objective function covers all the trees. In the second line, we still have the regularization terms for all t trees; they are just hidden inside the "constant."
