### ISSUE TITLE
xgboost performance and lib’s size depends on path to src folder

### ISSUE THREAD

**Issue by makart19** [dmlc/xgboost#7490]
During xgboost evaluation I discovered that xgboost performance and lib’s size depends on path to src folder.
The performance difference can be up to 10% (depending on HW and dataset).

For example: 

    xgboost built path: /tmp/test_of_xgboost/xgboost
    libxgboost.so size: 5486952
    year ds exec time: 118(sec)

    xgboost built path: /tmp/test_of_xgboost/xgboost_1.4.2_path_123456789
    libxgboost.so size: 5491048
    year ds exec time: 127(sec)

Please find reproducer and files with experiments' result with year_prediction_msd dataset (https://archive.ics.uci.edu/ml/datasets/yearpredictionmsd) in attached test_of_xgboost.zip
To launch main.py you need to place YearPredictionMSD.txt into <extract_folder>/data

System info:

    Ubuntu 20.04
    Intel(R) Xeon(R) CPU E3-1585L v5 @ 3.00GHz

xgboost tag: v1.4.2

Build cmd:

    mkdir _build
    cd _build
    cmake ..
    make -j8

from cmake:

-- The CXX compiler identification is GNU 9.3.0
-- The C compiler identification is GNU 9.3.0

[test_of_xgboost.zip](https://github.com/dmlc/xgboost/files/7614748/test_of_xgboost.zip)

**Comment by trivialfis** [comment]
Thanks for opening the issue.  That's interesting to know. ;-)

lib size is expected considering the debug symbols in the final object.  Perf on the other hand is strange, maybe register usage?  Anyway, you can try to run `strip libxgboost.so` to remove the debug symbols.  Other than that, I don't think there is much that can be done by the devs here ...
