### ISSUE TITLE
DaskDeviceQuantileDMatrix hangs with empty partitions unlike DaskDMatrix with Dask-cuDF inputs

### ISSUE THREAD

**Issue by beckernick** [dmlc/xgboost#7494]
DaskDMatrix appears to be robust to empty partitions, in that a DMatrix created from a Dask-cuDF Dataframe with an empty partition can still be used for training. From the following test, it looks like DaskDeviceQuantileDMatrix may not be robust to empty partitions. When I run the minimal reproducer below, my process appears to hang during the `train` call (and underlying `dispatched_train` Dask task).

As I don't always know if any partitions might be empty without introspecting my data (which could be expensive depending on where the data resides and the upstream task graph), it would be great if DaskDeviceQuantileDMatrix were also robust to empty partitions.

On a DGX-1 with the environment listed below, this script produces the following output:

```python
from dask.distributed import Client
from dask_cuda import LocalCUDACluster

import xgboost as xgb
import dask_cudf
import cudf


dxgb_gpu_params = {
    "tree_method": "gpu_hist",
    "objective": "reg:squarederror"
}

def create_data():
    mult = 100

    df = cudf.DataFrame(
        {"a": [1,2,3,4,5.1] * mult,
         "b": [10,15,29.3,30,31] * mult,
         "y": [10,20,30,40.,50] * mult,
        })
    empty = df.iloc[:0]

    ddf = dask_cudf.concat(
        [dask_cudf.from_cudf(empty, npartitions=1)]
        + [dask_cudf.from_cudf(df, npartitions=3)]
        + [dask_cudf.from_cudf(df, npartitions=3)]
    )
    return ddf


def train(use_quantile_dmatrix=False):
    if use_quantile_dmatrix:
        dtrain = xgb.dask.DaskDeviceQuantileDMatrix(
            client,
            ddf[ddf.columns.difference(["y"])],
            ddf[["y"]]
        )
    else:
        dtrain = xgb.dask.DaskDMatrix(
            client,
            ddf[ddf.columns.difference(["y"])],
            ddf[["y"]]
        )

    bst = xgb.dask.train(
        client, dxgb_gpu_params, dtrain, evals=[(dtrain, "train")]
    )
    
    
if __name__ == "__main__":
    cluster = LocalCUDACluster(CUDA_VISIBLE_DEVICES="0,1", dashboard_address=':8889')
    client = Client(cluster)
    
    ddf = create_data()
    ddf = ddf.persist()
    
    print(ddf.map_partitions(len).compute())
    
    train(use_quantile_dmatrix=False) # succeeds
    train(use_quantile_dmatrix=True) # hangs
```

```
python xgb-test.py
distributed.preloading - INFO - Import preload module: dask_cuda.initialize
distributed.preloading - INFO - Import preload module: dask_cuda.initialize
0      0
1    167
2    167
3    166
4    167
5    167
6    166
dtype: int64
[18:31:46] task [xgboost.dask]:tcp://127.0.0.1:43853 got new rank 0
[18:31:46] task [xgboost.dask]:tcp://127.0.0.1:43077 got new rank 1
[0]	train-rmse:22.94910
[1]	train-rmse:16.09862
[2]	train-rmse:11.29306
[3]	train-rmse:7.92200
[4]	train-rmse:5.55722
[5]	train-rmse:3.89835
[6]	train-rmse:2.73466
[7]	train-rmse:1.91835
[8]	train-rmse:1.34570
[9]	train-rmse:0.94400
[18:31:46] task [xgboost.dask]:tcp://127.0.0.1:43853 got new rank 0
[18:31:46] task [xgboost.dask]:tcp://127.0.0.1:43077 got new rank 1

... hangs ...
```

Subset of Environment:
```
grep "xgb\|dask\|rapids"
# packages in environment at /home/nicholasb/conda/envs/rapids-21.12:
cucim                     21.12.00a211201 cuda_11_py38_gfb85f01_29    rapidsai-nightly
cudf                      21.12.00a211201 cuda_11_py38_g74ac6ed5e0_290    rapidsai-nightly
cudf_kafka                21.12.00a211201 py38_g74ac6ed5e0_290    rapidsai-nightly
cugraph                   21.12.00a211201 cuda11_py38_g4b8c1330_95    rapidsai-nightly
cuml                      21.12.00a211201 cuda11_py38_ge9fb48c01_115    rapidsai-nightly
cusignal                  21.12.00a211201 py37_gc36c013_9    rapidsai-nightly
cuspatial                 21.12.00a211201 py38_g5cf96c5_12    rapidsai-nightly
custreamz                 21.12.00a211201 py38_g74ac6ed5e0_290    rapidsai-nightly
cuxfilter                 21.12.00a211201 py38_gdc06524_10    rapidsai-nightly
dask                      2021.11.2          pyhd8ed1ab_0    conda-forge
dask-core                 2021.11.2          pyhd8ed1ab_0    conda-forge
dask-cuda                 21.12.00a211201         py38_47    rapidsai-nightly
dask-cudf                 21.12.00a211201 cuda_11_py38_g74ac6ed5e0_290    rapidsai-nightly
dask-snowflake            0.0.2              pyhd8ed1ab_0    conda-forge
libcucim                  21.12.00a211201 cuda11_gfb85f01_29    rapidsai-nightly
libcudf                   21.12.00a211201 cuda11_g74ac6ed5e0_290    rapidsai-nightly
libcudf_kafka             21.12.00a211201 g74ac6ed5e0_290    rapidsai-nightly
libcugraph                21.12.00a211201 cuda11_g4b8c1330_95    rapidsai-nightly
libcuml                   21.12.00a211201 cuda11_ge9fb48c01_115    rapidsai-nightly
libcumlprims              21.12.00a211123 cuda11_g69b561e_7    rapidsai-nightly
libcuspatial              21.12.00a211201 cuda11_g5cf96c5_12    rapidsai-nightly
librmm                    21.12.00a211201 cuda11_g0acbd51_31    rapidsai-nightly
libxgboost                1.5.0dev.rapidsai21.12      cuda11.2_0    rapidsai-nightly
ptxcompiler               0.1.0            py38hb739d79_0    rapidsai-nightly
py-xgboost                1.5.0dev.rapidsai21.12  cuda11.2py38_0    rapidsai-nightly
rapids                    21.12.00a211118 cuda11.2_py38_gc907bab_64    rapidsai-nightly
rapids-xgboost            21.12.00a211118 cuda11.2_py38_gc907bab_64    rapidsai-nightly
rmm                       21.12.00a211201 cuda11_py38_g0acbd51_31_has_cma    rapidsai-nightly
ucx                       1.11.2+gef2bbcf      cuda11.2_0    rapidsai-nightly
ucx-proc                  1.0.0                       gpu    rapidsai-nightly
ucx-py                    0.23.0a211123   py38_gef2bbcf_34    rapidsai-nightly
xgboost                   1.5.0dev.rapidsai21.12  cuda11.2py38_0    rapidsai-nightly
```

Full environment:
<details>
conda list
# packages in environment at /home/nicholasb/conda/envs/rapids-21.12:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
abseil-cpp                20210324.2           h9c3ff4c_0    conda-forge
aiohttp                   3.8.1            py38h497a2fe_0    conda-forge
aiosignal                 1.2.0              pyhd8ed1ab_0    conda-forge
anyio                     3.4.0            py38h578d9bd_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
argon2-cffi               21.1.0           py38h497a2fe_2    conda-forge
arrow-cpp                 5.0.0           py38hc3077b4_18_cuda    conda-forge
arrow-cpp-proc            3.0.0                      cuda    conda-forge
asn1crypto                1.4.0              pyh9f0ad1d_0    conda-forge
async-timeout             4.0.1              pyhd8ed1ab_0    conda-forge
async_generator           1.10                       py_0    conda-forge
attrs                     21.2.0             pyhd8ed1ab_0    conda-forge
aws-c-auth                0.6.8                hfef2836_0    conda-forge
aws-c-cal                 0.5.12               h70efedd_7    conda-forge
aws-c-common              0.6.17               h7f98852_0    conda-forge
aws-c-compression         0.2.14               h7c7754b_7    conda-forge
aws-c-event-stream        0.2.7               hb80ed28_31    conda-forge
aws-c-http                0.6.10               h58a30cf_2    conda-forge
aws-c-io                  0.10.13              he836878_5    conda-forge
aws-c-mqtt                0.7.9                h042a236_0    conda-forge
aws-c-s3                  0.1.27              h4f4cd48_12    conda-forge
aws-c-sdkutils            0.1.1                h7c7754b_4    conda-forge
aws-checksums             0.1.12               h7c7754b_6    conda-forge
aws-crt-cpp               0.17.9               hc7d31a4_1    conda-forge
aws-sdk-cpp               1.9.154              h77f1c7e_0    conda-forge
babel                     2.9.1              pyh44b312d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
bleach                    4.1.0              pyhd8ed1ab_0    conda-forge
blosc                     1.21.0               h9c3ff4c_0    conda-forge
bokeh                     2.4.0            py38h578d9bd_0    conda-forge
boost                     1.74.0           py38h2b96118_4    conda-forge
boost-cpp                 1.74.0               h312852a_4    conda-forge
brotli                    1.0.9                h7f98852_6    conda-forge
brotli-bin                1.0.9                h7f98852_6    conda-forge
brotlipy                  0.7.0           py38h497a2fe_1003    conda-forge
brunsli                   0.1                  h9c3ff4c_0    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
c-blosc2                  2.0.4                h5f21a17_1    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
cachetools                4.2.4              pyhd8ed1ab_0    conda-forge
cairo                     1.16.0            h6cf1ce9_1008    conda-forge
certifi                   2021.10.8        py38h578d9bd_1    conda-forge
cffi                      1.15.0           py38h3931269_0    conda-forge
cfitsio                   3.470                hb418390_7    conda-forge
charls                    2.2.0                h9c3ff4c_0    conda-forge
charset-normalizer        2.0.8              pyhd8ed1ab_0    conda-forge
click                     8.0.3            py38h578d9bd_1    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.7.2              pyhd8ed1ab_1    conda-forge
cloudpickle               2.0.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
colorcet                  3.0.0              pyhd8ed1ab_0    conda-forge
cryptography              3.4.8            py38h3e25421_1    conda-forge
cucim                     21.12.00a211201 cuda_11_py38_gfb85f01_29    rapidsai-nightly
cudatoolkit               11.2.72              h2bc3f7f_0    nvidia
cudf                      21.12.00a211201 cuda_11_py38_g74ac6ed5e0_290    rapidsai-nightly
cudf_kafka                21.12.00a211201 py38_g74ac6ed5e0_290    rapidsai-nightly
cugraph                   21.12.00a211201 cuda11_py38_g4b8c1330_95    rapidsai-nightly
cuml                      21.12.00a211201 cuda11_py38_ge9fb48c01_115    rapidsai-nightly
cupy                      9.6.0            py38h177b0fd_0    conda-forge
curl                      7.80.0               h2574ce0_0    conda-forge
cusignal                  21.12.00a211201 py37_gc36c013_9    rapidsai-nightly
cuspatial                 21.12.00a211201 py38_g5cf96c5_12    rapidsai-nightly
custreamz                 21.12.00a211201 py38_g74ac6ed5e0_290    rapidsai-nightly
cuxfilter                 21.12.00a211201 py38_gdc06524_10    rapidsai-nightly
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cyrus-sasl                2.1.27               h230043b_5    conda-forge
cytoolz                   0.11.2           py38h497a2fe_1    conda-forge
dask                      2021.11.2          pyhd8ed1ab_0    conda-forge
dask-core                 2021.11.2          pyhd8ed1ab_0    conda-forge
dask-cuda                 21.12.00a211201         py38_47    rapidsai-nightly
dask-cudf                 21.12.00a211201 cuda_11_py38_g74ac6ed5e0_290    rapidsai-nightly
dask-snowflake            0.0.2              pyhd8ed1ab_0    conda-forge
datashader                0.11.1             pyh9f0ad1d_0    conda-forge
datashape                 0.5.4                      py_1    conda-forge
debugpy                   1.5.1            py38h709712a_0    conda-forge
decorator                 5.1.0              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
distributed               2021.11.2        py38h578d9bd_0    conda-forge
dlpack                    0.5                  h9c3ff4c_0    conda-forge
entrypoints               0.3             py38h32f6830_1002    conda-forge
expat                     2.4.1                h9c3ff4c_0    conda-forge
faiss-proc                1.0.0                      cuda    conda-forge
fastavro                  1.4.7            py38h497a2fe_1    conda-forge
fastrlock                 0.8              py38h709712a_1    conda-forge
fiona                     1.8.20           py38hbb147eb_2    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.13.1            hba837de_1005    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.28.2           py38h497a2fe_0    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
freexl                    1.0.6                h7f98852_0    conda-forge
frozenlist                1.2.0            py38h497a2fe_1    conda-forge
fsspec                    2021.11.1          pyhd8ed1ab_0    conda-forge
gdal                      3.3.2            py38h81a01a0_3    conda-forge
geopandas                 0.9.0              pyhd8ed1ab_1    conda-forge
geopandas-base            0.9.0              pyhd8ed1ab_1    conda-forge
geos                      3.9.1                h9c3ff4c_2    conda-forge
geotiff                   1.7.0                h08e826d_2    conda-forge
gettext                   0.19.8.1          h73d1719_1008    conda-forge
gflags                    2.2.2             he1b5a44_1004    conda-forge
giflib                    5.2.1                h36c2ea0_2    conda-forge
glog                      0.5.0                h48cff8f_0    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
greenlet                  1.1.2            py38h709712a_1    conda-forge
grpc-cpp                  1.42.0               h7e358d9_0    conda-forge
hdf4                      4.2.15               h10796ff_3    conda-forge
hdf5                      1.12.1          nompi_h2750804_102    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
icu                       68.2                 h9c3ff4c_0    conda-forge
idna                      3.1                pyhd3deb0d_0    conda-forge
imagecodecs               2021.8.26        py38hb5ce8f7_1    conda-forge
imageio                   2.9.0                      py_0    conda-forge
importlib-metadata        4.8.2            py38h578d9bd_0    conda-forge
importlib_metadata        4.8.2                hd8ed1ab_0    conda-forge
importlib_resources       5.4.0              pyhd8ed1ab_0    conda-forge
ipykernel                 6.5.1            py38he5a9106_0    conda-forge
ipython                   7.30.0           py38h578d9bd_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.6.5              pyhd8ed1ab_0    conda-forge
jbig                      2.1               h7f98852_2003    conda-forge
jedi                      0.18.1           py38h578d9bd_0    conda-forge
jinja2                    3.0.3              pyhd8ed1ab_0    conda-forge
joblib                    1.1.0              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   h36c2ea0_0    conda-forge
json-c                    0.15                 h98cffda_0    conda-forge
json5                     0.9.5              pyh9f0ad1d_0    conda-forge
jsonschema                4.2.1              pyhd8ed1ab_0    conda-forge
jupyter-server-proxy      3.2.0              pyhd8ed1ab_0    conda-forge
jupyter_client            7.1.0              pyhd8ed1ab_0    conda-forge
jupyter_core              4.9.1            py38h578d9bd_1    conda-forge
jupyter_server            1.12.1             pyhd8ed1ab_0    conda-forge
jupyterlab                3.2.4              pyhd8ed1ab_0    conda-forge
jupyterlab-nvdashboard    0.6.0                    pypi_0    pypi
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_server         2.8.2              pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        1.0.2              pyhd8ed1ab_0    conda-forge
jxrlib                    1.1                  h7f98852_2    conda-forge
kealib                    1.4.14               h87e4c3c_3    conda-forge
kiwisolver                1.3.2            py38h1fd1430_1    conda-forge
krb5                      1.19.2               hcc1bbae_3    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
lerc                      3.0                  h9c3ff4c_0    conda-forge
libaec                    1.0.6                h9c3ff4c_0    conda-forge
libblas                   3.9.0           12_linux64_openblas    conda-forge
libbrotlicommon           1.0.9                h7f98852_6    conda-forge
libbrotlidec              1.0.9                h7f98852_6    conda-forge
libbrotlienc              1.0.9                h7f98852_6    conda-forge
libcblas                  3.9.0           12_linux64_openblas    conda-forge
libcucim                  21.12.00a211201 cuda11_gfb85f01_29    rapidsai-nightly
libcudf                   21.12.00a211201 cuda11_g74ac6ed5e0_290    rapidsai-nightly
libcudf_kafka             21.12.00a211201 g74ac6ed5e0_290    rapidsai-nightly
libcugraph                21.12.00a211201 cuda11_g4b8c1330_95    rapidsai-nightly
libcuml                   21.12.00a211201 cuda11_ge9fb48c01_115    rapidsai-nightly
libcumlprims              21.12.00a211123 cuda11_g69b561e_7    rapidsai-nightly
libcurl                   7.80.0               h2574ce0_0    conda-forge
libcusolver               11.3.2.107           hc875929_0    nvidia
libcuspatial              21.12.00a211201 cuda11_g5cf96c5_12    rapidsai-nightly
libdap4                   3.20.6               hd7c4107_2    conda-forge
libdeflate                1.8                  h7f98852_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.10               h9b69904_4    conda-forge
libfaiss                  1.7.0           cuda112h5bea7ad_8_cuda    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 11.2.0              h1d223b6_11    conda-forge
libgcrypt                 1.9.4                h7f98852_0    conda-forge
libgdal                   3.3.2                h6acdded_3    conda-forge
libgfortran-ng            11.2.0              h69a702a_11    conda-forge
libgfortran5              11.2.0              h5c6108e_11    conda-forge
libglib                   2.70.1               h174f98d_0    conda-forge
libgomp                   11.2.0              h1d223b6_11    conda-forge
libgpg-error              1.42                 h9c3ff4c_0    conda-forge
libgsasl                  1.10.0               h5b4c23d_0    conda-forge
libhwloc                  2.3.0                h5e5b7d1_1    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
libkml                    1.3.0             h238a007_1014    conda-forge
liblapack                 3.9.0           12_linux64_openblas    conda-forge
libllvm11                 11.1.0               hf817b99_2    conda-forge
libnetcdf                 4.8.1           nompi_hb3fd0d9_101    conda-forge
libnghttp2                1.43.0               h812cca2_1    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libntlm                   1.4               h7f98852_1002    conda-forge
libopenblas               0.3.18          pthreads_h8fe5266_0    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libpq                     13.5                 hd57d9b9_0    conda-forge
libprotobuf               3.18.1               h780b84a_0    conda-forge
librdkafka                1.6.1                hc49e61c_1    conda-forge
librmm                    21.12.00a211201 cuda11_g0acbd51_31    rapidsai-nightly
librttopo                 1.1.0                h1185371_6    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libspatialindex           1.9.3                h9c3ff4c_4    conda-forge
libspatialite             5.0.1                h5cf074c_8    conda-forge
libssh2                   1.10.0               ha56f1ee_2    conda-forge
libstdcxx-ng              11.2.0              he4da1e4_11    conda-forge
libthrift                 0.15.0               he6d91bd_1    conda-forge
libtiff                   4.3.0                h6f004c6_2    conda-forge
libutf8proc               2.6.1                h7f98852_0    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libuv                     1.42.0               h7f98852_0    conda-forge
libwebp                   1.2.1                h3452ae3_0    conda-forge
libwebp-base              1.2.1                h7f98852_0    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxgboost                1.5.0dev.rapidsai21.12      cuda11.2_0    rapidsai-nightly
libxml2                   2.9.12               h72842e0_0    conda-forge
libzip                    1.8.0                h4de3113_1    conda-forge
libzlib                   1.2.11            h36c2ea0_1013    conda-forge
libzopfli                 1.0.3                h9c3ff4c_0    conda-forge
llvmlite                  0.37.0           py38h4630a5e_1    conda-forge
locket                    0.2.0                      py_2    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
mapclassify               2.4.3              pyhd8ed1ab_0    conda-forge
markdown                  3.3.6              pyhd8ed1ab_0    conda-forge
markupsafe                2.0.1            py38h497a2fe_1    conda-forge
matplotlib-base           3.5.0            py38hf4fb855_0    conda-forge
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
mistune                   0.8.4           py38h497a2fe_1005    conda-forge
msgpack-python            1.0.3            py38h1fd1430_0    conda-forge
multidict                 5.2.0            py38h497a2fe_1    conda-forge
multipledispatch          0.6.0                      py_0    conda-forge
munch                     2.5.0                      py_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
nbclassic                 0.3.4              pyhd8ed1ab_0    conda-forge
nbclient                  0.5.9              pyhd8ed1ab_0    conda-forge
nbconvert                 6.3.0            py38h578d9bd_1    conda-forge
nbformat                  5.1.3              pyhd8ed1ab_0    conda-forge
nccl                      2.11.4.1             hdc17891_0    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
nest-asyncio              1.5.1              pyhd8ed1ab_0    conda-forge
networkx                  2.6.3              pyhd8ed1ab_1    conda-forge
nodejs                    14.17.4              h92b4a50_0    conda-forge
notebook                  6.4.6              pyha770c72_0    conda-forge
nspr                      4.32                 h9c3ff4c_1    conda-forge
nss                       3.72                 hb5efdd6_0    conda-forge
numba                     0.54.1           py38h4bf6c61_0    conda-forge
numpy                     1.20.3           py38h9894fe3_1    conda-forge
nvtx                      0.2.3            py38h497a2fe_1    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.4.0                hb52868f_1    conda-forge
openssl                   1.1.1l               h7f98852_0    conda-forge
orc                       1.7.1                h68e2c4e_0    conda-forge
oscrypto                  1.2.1              pyhd3deb0d_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.3.4            py38h43a58ef_1    conda-forge
pandoc                    2.16.2               h7f98852_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
panel                     0.12.4             pyhd8ed1ab_0    conda-forge
param                     1.12.0             pyh6c4a22f_0    conda-forge
parquet-cpp               1.5.1                         1    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
partd                     1.2.0              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
pexpect                   4.8.0            py38h32f6830_1    conda-forge
pickleshare               0.7.5           py38h32f6830_1002    conda-forge
pillow                    8.4.0            py38h8e6f84c_0    conda-forge
pip                       21.3.1             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h36c2ea0_0    conda-forge
pooch                     1.5.2              pyhd8ed1ab_0    conda-forge
poppler                   21.09.0              ha39eefc_3    conda-forge
poppler-data              0.4.11               hd8ed1ab_0    conda-forge
postgresql                13.5                 h2510834_0    conda-forge
proj                      8.1.0                h277dcde_1    conda-forge
prometheus_client         0.12.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.22             pyha770c72_0    conda-forge
protobuf                  3.18.1           py38h709712a_0    conda-forge
psutil                    5.8.0            py38h497a2fe_2    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptxcompiler               0.1.0            py38hb739d79_0    rapidsai-nightly
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
py-xgboost                1.5.0dev.rapidsai21.12  cuda11.2py38_0    rapidsai-nightly
pyarrow                   5.0.0           py38hb90f683_18_cuda    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pycryptodomex             3.11.0           py38h497a2fe_1    conda-forge
pyct                      0.4.6                      py_0    conda-forge
pyct-core                 0.4.6                      py_0    conda-forge
pydeck                    0.5.0              pyh9f0ad1d_0    conda-forge
pyee                      8.1.0              pyh9f0ad1d_0    conda-forge
pygments                  2.10.0             pyhd8ed1ab_0    conda-forge
pyjwt                     2.3.0              pyhd8ed1ab_0    conda-forge
pynvml                    11.0.0             pyhd8ed1ab_0    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.6              pyhd8ed1ab_0    conda-forge
pyppeteer                 0.2.6              pyhd8ed1ab_0    conda-forge
pyproj                    3.1.0            py38h3701b11_4    conda-forge
pyrsistent                0.18.0           py38h497a2fe_0    conda-forge
pysocks                   1.7.1            py38h578d9bd_4    conda-forge
python                    3.8.12          hb7a2778_2_cpython    conda-forge
python-confluent-kafka    1.6.0            py38h497a2fe_1    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytz                      2021.3             pyhd8ed1ab_0    conda-forge
pyviz_comms               2.1.0              pyhd8ed1ab_0    conda-forge
pywavelets                1.2.0            py38h6c62de6_1    conda-forge
pyyaml                    6.0              py38h497a2fe_3    conda-forge
pyzmq                     22.3.0           py38h2035c66_1    conda-forge
rapids                    21.12.00a211118 cuda11.2_py38_gc907bab_64    rapidsai-nightly
rapids-xgboost            21.12.00a211118 cuda11.2_py38_gc907bab_64    rapidsai-nightly
re2                       2021.11.01           h9c3ff4c_0    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
requests                  2.26.0             pyhd8ed1ab_1    conda-forge
rmm                       21.12.00a211201 cuda11_py38_g0acbd51_31_has_cma    rapidsai-nightly
rtree                     0.9.7            py38h02d302b_3    conda-forge
s2n                       1.3.0                h9b69904_0    conda-forge
scikit-image              0.18.1           py38h51da96c_0    conda-forge
scikit-learn              1.0.1            py38h1561384_2    conda-forge
scipy                     1.7.3            py38h56a6a73_0    conda-forge
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setuptools                59.4.0           py38h578d9bd_0    conda-forge
shapely                   1.8.0            py38hb7fe4a8_0    conda-forge
simpervisor               0.4                pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.8                he1b5a44_3    conda-forge
sniffio                   1.2.0            py38h578d9bd_2    conda-forge
snowflake-connector-python 2.7.0            py38h8914348_2    conda-forge
snowflake-sqlalchemy      1.3.2              pyhd8ed1ab_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
spdlog                    1.8.5                h4bd325d_0    conda-forge
sqlalchemy                1.4.27           py38h497a2fe_0    conda-forge
sqlite                    3.37.0               h9cd32fc_0    conda-forge
streamz                   0.6.3              pyh6c4a22f_0    conda-forge
tblib                     1.7.0              pyhd8ed1ab_0    conda-forge
terminado                 0.12.1           py38h578d9bd_1    conda-forge
testpath                  0.5.0              pyhd8ed1ab_0    conda-forge
threadpoolctl             3.0.0              pyh8a188c0_0    conda-forge
tifffile                  2021.11.2          pyhd8ed1ab_0    conda-forge
tiledb                    2.3.4                he87e0bf_0    conda-forge
tk                        8.6.11               h27826a3_1    conda-forge
toolz                     0.11.2             pyhd8ed1ab_0    conda-forge
tornado                   6.1              py38h497a2fe_2    conda-forge
tqdm                      4.62.3             pyhd8ed1ab_0    conda-forge
traitlets                 5.1.1              pyhd8ed1ab_0    conda-forge
treelite                  2.1.0            py38hdd725b4_0    conda-forge
treelite-runtime          2.1.0                    pypi_0    pypi
typing-extensions         4.0.1                hd8ed1ab_0    conda-forge
typing_extensions         4.0.1              pyha770c72_0    conda-forge
tzcode                    2021e                h7f98852_0    conda-forge
tzdata                    2021e                he74cb21_0    conda-forge
ucx                       1.11.2+gef2bbcf      cuda11.2_0    rapidsai-nightly
ucx-proc                  1.0.0                       gpu    rapidsai-nightly
ucx-py                    0.23.0a211123   py38_gef2bbcf_34    rapidsai-nightly
unicodedata2              13.0.0.post2     py38h497a2fe_4    conda-forge
urllib3                   1.26.7             pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
websocket-client          1.2.1            py38h578d9bd_0    conda-forge
websockets                9.1              py38h497a2fe_0    conda-forge
wheel                     0.37.0             pyhd8ed1ab_1    conda-forge
widgetsnbextension        3.5.2            py38h578d9bd_1    conda-forge
xarray                    0.20.1             pyhd8ed1ab_0    conda-forge
xerces-c                  3.2.3                h9d8b166_3    conda-forge
xgboost                   1.5.0dev.rapidsai21.12  cuda11.2py38_0    rapidsai-nightly
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h7f98852_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.7.2                h7f98852_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
yarl                      1.7.2            py38h497a2fe_1    conda-forge
zeromq                    4.3.4                h9c3ff4c_1    conda-forge
zfp                       0.5.5                h9c3ff4c_8    conda-forge
zict                      2.0.0                      py_0    conda-forge
zipp                      3.6.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h36c2ea0_1013    conda-forge
zstd                      1.5.0                ha95c52a_0    conda-forge
</details>

**Comment by trivialfis** [comment]
Thanks for opening the issue.  Will look into it next week.

**Comment by trivialfis** [comment]
I tried to fix this from xgboost, but seems to be quite non-trivial.  I fixed the training, but for prediction, there are some other errors.  For instance, having cudf.DataFrame output obtained by copying cupy array while keeping the input index:
```
cupy/_core/core.pyx:1338: in cupy._core.core.ndarray.__getitem__
    ???
cupy/_core/_routines_indexing.pyx:50: in cupy._core._routines_indexing._ndarray_getitem
    ???

>   ???
E   IndexError: Index 0 is out of bounds for axis 0 with size 0

```
or simply copy empty cupy array:
```
../../../.anaconda/envs/rapids-dev/lib/python3.8/site-packages/cudf/core/dataframe.py:239: in __init__
    new_df = self._from_arrays(data, index=index, columns=columns)
../../../.anaconda/envs/rapids-dev/lib/python3.8/site-packages/cudf/core/dataframe.py:5854: in _from_arrays
    num_cols = len(data[0])
cupy/_core/core.pyx:1338: in cupy._core.core.ndarray.__getitem__
    ???
cupy/_core/_routines_indexing.pyx:50: in cupy._core._routines_indexing._ndarray_getitem
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
>   ???
E   IndexError: Index 0 is out of bounds for axis 0 with size 0

cupy/_core/_routines_indexing.pyx:418: IndexError
```

I will submit a fix for xgboost, but I think a better solution might be having some logic in dask to handle empty partitions, which seems to be more scalable.

**Comment by trivialfis** [comment]
Reopening as failed test on master: https://xgboost-ci.net/blue/organizations/jenkins/xgboost/detail/master/1116/pipeline .

**Comment by trivialfis** [comment]
Fixed as part of https://github.com/dmlc/xgboost/pull/7514 .
