### ISSUE TITLE
Prediction time is different

### ISSUE THREAD

**Issue by lantianguhong** [dmlc/xgboost#7497]
[addison output]$ ./load_module demo.bin
364:us
[addison output]$ ./load_module demo.bin
45806:us
[addison output]$ ./load_module demo.bin
43777:us
[addison output]$ ./load_module demo.bin
12382:us
[addison output]$ ./load_module demo.bin
517:us
[addison output]$ ./load_module demo.bin
45806:us
[addison output]$ ./load_module demo.bin
358:us

why is the prection time is different in the same module and datas? I use c-api to run my module，and I find such a problem.

the following is my code:
    const int row = 10;
    const int columns = 8;
    const int dmats_len = 1;
     /// prepare data
    float uin_data[row][columns] = {
                1.000000,6.000000,0.000000,0.000000,3.131165,2.236895,0.000000,0.000000,
                1.000000,1.000000,0.000000,65.555556,2.570237,3.281464,0.000000,0.000000,
                1.000000,0.000000,0.000000,72.295082,6.318274,6.699986,0.000000,0.000000,
                1.000000,5.000000,0.000000,95.230352,0.546545,-0.286531,0.000000,0.000000,
                1.000000,1.000000,0.000000,91.889576,25.490396,24.128544,0.000000,0.000000,
                1.000000,3.000000,0.000000,87.582618,-4.219917,-5.545919,0.000000,0.000000,
                1.000000,0.000000,0.000000,82.626780,1.570202,2.155064,0.000000,0.000000,
                1.000000,2.000000,0.000000,97.375919,5.886034,5.260321,0.000000,0.000000,
                1.000000,0.000000,0.000000,86.431846,-9.393253,-8.060214,0.000000,0.000000,
                1.000000,1.000000,0.000000,80.509578,13.203328,12.971694,0.000000,0.000000
    };
    const char* modulename = argv[1]; /// module name
    const float *f;                   /// output data
    bst_ulong out_len;                /// output len
    BoosterHandle h_booster;          /// booster handler
    DMatrixHandle h_test[dmats_len];  /// dmats matrices
    /// create matrix content from dense matrix
    safe_xgboost(XGDMatrixCreateFromMat((float *) uin_data, row, columns, -1, &h_test[0]));
    safe_xgboost(XGBoosterCreate(h_test, dmats_len, &h_booster));
    // load module
    safe_xgboost(XGBoosterLoadModel(h_booster, modulename));
    long t1 = CurrentMicroTime();
    // prediction
    safe_xgboost(XGBoosterPredict(h_booster, h_test[0], 0, 0,0,&out_len,&f));
    long t2 = CurrentMicroTime();
    // time
    printf("%ld:us\n", t2 - t1);

    XGDMatrixFree(h_test[0]);
    XGBoosterFree(h_booster);

**Comment by trivialfis** [comment]
That's likely caused by the operation system, thread scheduling, dynamic module loading, memory allocation etc.  They are not necessarily the same.
