### ISSUE TITLE
Assigning iteration and ntree_limit to the model before training

### ISSUE THREAD

**Issue by augustkx** [dmlc/xgboost#7502]
Hi,
How can I set the XGBClassifier to stop after a certain number of iteration? I mean according to the iteration number I have got from previous training(with early stop), through clf.best_iteration. 

And also how can I use clf.best_ntree_limit for training a new model?

Thanks in advance!

**Comment by trivialfis** [comment]
`n_estimator` parameter sounds like the right option.

**Comment by augustkx** [comment]
Thanks for the quick reply. But how about the iteration?

**Comment by trivialfis** [comment]
```
clf_previous = XGBClassifier().fit()

clf_new = XGBClassifier(n_estimator=clf_previous.best_iteration).fit()
```

**Comment by augustkx** [comment]
> ```
> clf_previous = XGBClassifier().fit()
> 
> clf_new = XGBClassifier(n_estimator=clf_previous.best_iteration).fit()
> ```

Ah, I see. Then I should ask what does clf.best_ntree_limit correspond to?

**Comment by trivialfis** [comment]
It corresponds to the number of trees instead of the number of iterations.  It's trickier to use since you need to take the number of classes and the size of forest into consideration and is deprecated.  One extra benefit of using iteration is that it aligns with model slicing:

``` python
sliced = clf.get_booster()[: iteration]
```

**Comment by augustkx** [comment]
I see. Thank you!

**Comment by augustkx** [comment]
> It corresponds to the number of trees instead of the number of iterations. It's trickier to use since you need to take the number of classes and the size of forest into consideration and is deprecated. One extra benefit of using iteration is that it aligns with model slicing:
> 
> ```python
> sliced = clf.get_booster()[: iteration]
> ```
Thank you. Good point. But  when I used the sliced for prediction, the output is not binary anymore. I am doing a binary classification task. So I need to turn the results to binary with the 0.5 threshold?

**Comment by trivialfis** [comment]
The result from slicing is a `Booster` object, the predict function is actually `predict_proba`, the `XGBClassifier` wraps the `Booster` object and turns the prediction into binary [0, 1] in `predict` function.
