### ISSUE TITLE
Make deepcopy compatible with pickle

### ISSUE THREAD

**Issue by yitang** [dmlc/xgboost#751]
Hi, I wonder if there is a way to make a copy of trained xgboost model in python?

I tried to use the `deepcopy` from the copy module but an error. 

Here is a minimal reproducible code. Note the `deepcopy` works fine with `sklearn`.

```python
import xgboost as xgb
import numpy as np
import copy

clf = xgb.XGBClassifier()
copy.deepcopy(clf) # Okay
X=np.array([[0,1,2,3], [0,1,2,3]])
y=np.array([0,1])
clf.fit(X,y)
copy.deepcopy(clf) # error

from sklearn.linear_model import RidgeClassifier
clf = RidgeClassifier()
clf.fit(X, y)
copy.deepcopy(clf) # Okay
```

This is the error I got

    TypeError                                 Traceback (most recent call last)
    <ipython-input-44-686b0a861939> in <module>()
    ----> 1 copy.deepcopy(clf) # error
    
    /usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/copy.py in deepcopy(x, memo, _nil)
        180                             raise Error(
        181                                 "un(deep)copyable object of type %s" % cls)
    --> 182                 y = _reconstruct(x, rv, 1, memo)
        183 
        184     # If is its own copy, don't memoize.
    
    /usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/copy.py in _reconstruct(x, info, deep, memo)
        296     if state:
        297         if deep:
    --> 298             state = deepcopy(state, memo)
        299         if hasattr(y, '__setstate__'):
        300             y.__setstate__(state)
    
    /usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/copy.py in deepcopy(x, memo, _nil)
        153     copier = _deepcopy_dispatch.get(cls)
        154     if copier:
    --> 155         y = copier(x, memo)
        156     else:
        157         try:
    
    /usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/copy.py in _deepcopy_dict(x, memo)
        242     memo[id(x)] = y
        243     for key, value in x.items():
    --> 244         y[deepcopy(key, memo)] = deepcopy(value, memo)
        245     return y
        246 d[dict] = _deepcopy_dict
    
    /usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/copy.py in deepcopy(x, memo, _nil)
        164             copier = getattr(x, "__deepcopy__", None)
        165             if copier:
    --> 166                 y = copier(memo)
        167             else:
        168                 reductor = dispatch_table.get(cls)
    
    TypeError: __deepcopy__() takes 1 positional argument but 2 were given

Thanks

**Comment by tqchen** [comment]
could due to deep copy's implementation was not standard https://github.com/dmlc/xgboost/blob/master/python-package/xgboost/core.py#L646 you can add a memo argument to the functions, it would be great if you can send a PR to fix this

**Comment by yitang** [comment]
It takes me long time to figure out what's wrong and fix it as I am not experienced in Python/C++. Hopefully someone has the same needs fix it sooner. I've found a workaround so this issue is urgent.

**Comment by tqchen** [comment]
It should be quite easy, by changing the line i mentioned to standard deepcopy function required by python

**Comment by yitang** [comment]
@bzEq Thanks!
