### ISSUE TITLE
[Vote] Centralized Places for Links to Resources Tutorials Blogposts

### ISSUE THREAD

**Issue by tqchen** [dmlc/xgboost#754]
There has been a lot of use-cases on xgboost now and unfortunately it is quite hard to catch up with all of them. We only have a few in https://github.com/dmlc/xgboost/blob/master/doc/index.md#highlight-solutions that is not up to date.

I hope we can create something like https://github.com/josephmisiti/awesome-machine-learning/blob/master/README.md as a complete list of resources(tutorials, blogposts, interviews, examples, and industry usecases) related to xgboost, and help the community to quickly discover what is wanted, this is a vote on where we should put it.

1. xgboost/demo/README.md
     - So user will see it when they see code examples, also add a explicit link to it.
2. xgboost/resources/README.md
     - A dedicated folder to 
3. xgboost/doc/resources.md

**Comment by tqchen** [comment]
@terrytangyuan @pommedeterresautee @hetong007 @phunterlau

**Comment by phunterlau** [comment]
We can also think of adding an 'awesome-xgboost' page to our future dmlc.ml website (which is currently under construction, I need to push the offshore dev team one more time) We can start collecting some awesome ones for this page, and later on the website backend can import the .md file.

**Comment by pommedeterresautee** [comment]
Regarding idea of @phunterlau it makes sense to group everything in the same place (easier for the users).
I vote for option 1 which is the most natural place I expect to find examples/good practices.

**Comment by terrytangyuan** [comment]
That's a very good idea. I have no problem with a web page for this but eventually we'll import them to demo, which I think is a better place. Resources still sound confusing to me, e.g. sounds like resources need for the program itself instead of learning resources. Demo would be more intuitive to me.

**Comment by tqchen** [comment]
Let us use demo/README.md then, given the opinions we collected so far.

@terrytangyuan can you lead the effort on bring it together? We will need to create some kind of index in the beginning, and add the resources we know to it. Thanks!
