### ISSUE TITLE
Different train result between xgboost>=1.4.0 and xgboost<=1.3.3

### ISSUE THREAD

**Issue by idiomer** [dmlc/xgboost#7542]
I had a py-script to train a xgboost model. When I run the script (without earlystop) with different xgboost version(0.90 and 1.5.1), the AUC results show obvious difference(+0.3% val_AUC).

Therefore, I tested the script on lots of xgboost version, including 0.90, 1.0.0, 1.2.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0, 1.5.1.  It show that xgboost>=1.4.0 return exactly same results  and xgboost<=1.3.3 return another same results  (ALL version are cpu-based)

I had read the release about 1.4.0, but I couldn't find out the reason.  Could you help me to understand what happened on xgboost>=1.4.0 ?  

Below is the train/val result  on xgboost>=1.4.0 and xgboost<=1.3.3
![image](https://user-images.githubusercontent.com/17400651/148382501-31534345-a451-4006-82b7-cf5f0abcff22.png)

Here is the Code:
```python
params = {
    'booster':'gbtree',
    'objective':'binary:logistic',
    'tree_method':'approx',
    'eta':0.1,
    'gamma':0.1,
    'max_depth':5,
    'lambda':1,
    'subsample':1,
    'colsample_bytree':1,
    'min_child_weight':10,
    'eval_metric':'auc',
    'seed':0
}

df = pd.read_parquet('../data/my_trainset/ver=v6/dt=20220106/', columns=ALL_COLUMNS)
train_data, val_data = df[df['dt'] <= args.split_dt], df[df['dt'] > args.split_dt]
print(f'len(df) = {len(df)}, len(df.columns) = {len(df.columns)}, len(train_data) = {len(train_data)}, len(val_data) = {len(val_data)}')
del df; gc.collect()

dtrain = xgb.DMatrix(train_data[FEATURE_COLUMNS], train_data[LABEL_COLUMNS[0]]); del train_data; gc.collect()
dval = xgb.DMatrix(val_data[FEATURE_COLUMNS], val_data[LABEL_COLUMNS[0]]); del val_data; gc.collect()


evals_result = dict()
evallist = [(dtrain, 'train'), (dval, 'val')]
bst = xgb.train(
    params, dtrain, evals=evallist,
    num_boost_round=50, early_stopping_rounds=None,
    evals_result=evals_result, verbose_eval=1)
```

**Comment by trivialfis** [comment]
We have these changes from time to time, mostly caused by floating-point differences.

**Comment by idiomer** [comment]
All the inputs and params are same. Before 1.4.0, the results are **exactly** the same. It doesn't seems like caused by floating-point differences.   So does xgboost>=1.4.0

**Comment by trivialfis** [comment]
We have rewritten the AUC from scratch in 1.4.0 https://github.com/dmlc/xgboost/pull/6747, which causes some differences.  The math is the same for binary classification, but the implementation differs from the old one.

**Comment by trivialfis** [comment]
There's also a small difference in the latest master branch where we changed the floating point in evaluation metrics from 32bit to 64bit.

**Comment by idiomer** [comment]
I had conformed that `We have rewritten the AUC from scratch in 1.4.0 #6747`.  The different models predicted exactly the same scores, and the AUC of xgboost<=1.3.3  are same with sklearn.

thanks for your help !
