### ISSUE TITLE
`max_depth=0` doesn't work since 1.5.0

### ISSUE THREAD

**Issue by Azureblade3808** [dmlc/xgboost#7543]
According to doc, `max_depth=0` means no limit on depth when `grow_policy` is `lossguide` and `tree_method` is `hist`.

See this sample code:
```python
import numpy as np
import xgboost as xgb

x = np.array([[0], [1], [2], [3]])
y = np.array([0, 1, 2, 3])

model = xgb.XGBRegressor(
    n_estimators=1,
    eta=1,
    tree_method="hist",
    grow_policy="lossguide",
    reg_lambda=0,
    max_leaves=128,
    max_depth=0,
).fit(x, y)
assert np.array_equal(model.predict(x), y)
```

The trained model is expected to have one single tree, 4 leaves with depth of 2. The final assertion passes with 1.3.1 and 1.4.2, but fails with 1.5.0 and 1.5.1. When it fails, the single tree in the model has depth of 1.

**Comment by hcho3** [comment]
Thanks for reporting the bug. #7551 should fix it.
