### ISSUE TITLE
Did not find document about passsing label to matrix of XGBoost JVM Package

### ISSUE THREAD

**Issue by Litchilitchy** [dmlc/xgboost#7555]
I found the JVM package quick start example of creating data matrix at [official doc](https://xgboost.readthedocs.io/en/stable/jvm/java_intro.html)
```java
float[] data = new float[] {1f,2f,3f,4f,5f,6f};
int nrow = 3;
int ncol = 2;
float missing = 0.0f;
DMatrix dmat = new DMatrix(data, nrow, ncol, missing);

// and a DMatrix could be called by train method
Booster booster = XGBoost.train(dmat, params, nround, watches, null, null);
```
However, the doc says the JVM package DMatrix usage is the same with Python package, in Python, there is a label parameter
```python
dtrain = xgb.DMatrix(data, label=label)
```
But I could not find any in JVM package, how to set the label?

**Comment by trivialfis** [comment]
For java, it's more common to use setter/getter, see https://xgboost.readthedocs.io/en/stable/jvm/javadocs/index.html .

**Comment by trivialfis** [comment]
Also, there are some examples here: https://github.com/dmlc/xgboost/tree/master/jvm-packages/xgboost4j-example , which might help.  Feel free to open PRs for more documents and examples. ;-)
