### ISSUE TITLE
setup.py does not find the DLL on windows 

### ISSUE THREAD

**Issue by d07RiV** [dmlc/xgboost#756]
The VS project seems to be configured to build the library in `windows/x64/Release/xgboost_wrapper.dll`, but setup.py only checks `windows/release/xgboost_wrapper.dll`. Moving it to a different directory works, of course.

**Comment by phunterlau** [comment]
I think setup.py checks both according to <https://github.com/dmlc/xgboost/blob/master/python-package/xgboost/libpath.py>

```
            dll_path.append(os.path.join(curr_path, '../../windows/x64/Release/'))
            dll_path.append(os.path.join(curr_path, './windows/x64/Release/'))
```

**Comment by d07RiV** [comment]
Sorry I didn't realize I was trying to install it on a 32-bit python version :)
