### ISSUE TITLE
Question on the second-order gradient of hinge-loss.

### ISSUE THREAD

**Issue by Liam0205** [dmlc/xgboost#7580]
https://github.com/dmlc/xgboost/blob/5b1161bb64424ee4fc240255dbdaf547bb05975e/src/objective/hinge.cu#L61

seems to be 0 for `h`, considering that `l = max(0, 1 - y\cdot\hat y)`.

**Comment by trivialfis** [comment]
I think it's more or less a workaround.  XGBoost can't use 0 hessian objectives so 1 is a safe step size.
