### ISSUE TITLE
Number of threads used by predict.xgb.Booster (in R) cannot be specified and depends on previous runs

### ISSUE THREAD

**Issue by jiho** [dmlc/xgboost#7583]
In my environment (reduced to the `xgboost` relevant packages):

```
> library("xgboost")
> devtools::session_info()
─ Session info 
 setting  value
 version  R version 4.1.2 (2021-11-01)
 os       Ubuntu 20.04.3 LTS
 system   x86_64, linux-gnu
 ui       RStudio
 date     2022-01-20
 rstudio  2021.09.1+372 Ghost Orchid (server)

─ Packages 
 package     * version date (UTC) lib source
 jsonlite      1.7.3   2022-01-17 [1] CRAN (R 4.1.2)
 Matrix        1.4-0   2021-12-08 [4] CRAN (R 4.1.2)
 xgboost     * 1.5.0.2 2021-11-21 [1] CRAN (R 4.1.2)

> parallel::detectCores()
[1] 72
```

I see no way of setting `nthread` for `predict()`. I was seeing weird changes in timing of prediction and investigated with the following minimal example:

```R
# make up fake data
set.seed(1)

n <- 10^3
train <- data.frame(x1=rnorm(n), x2=rnorm(n))
train$y <- 1*train$x1^2 + 2*train$x2^2 + runif(n)
train <- as.matrix(train)

n <- 5*10^5
test <- data.frame(x1=rnorm(n), x2=rnorm(n))
test <- as.matrix(test)

save(train, test, file="data.Rdata")
```

Then run each section below in a **new R session** to make sure the run is not influenced by past state. This is important.

### Train single threaded -> predict single threaded

```R
library("xgboost")
load("data.Rdata")
m1 <- xgb.train(
  params=list(eta=0.05, max_depth=4, nthread=1),
  data=xgb.DMatrix(train[,1:2], label=train[,3]),
  nrounds=1000, verbose=FALSE)
system.time(predict(m1, newdata=test))
system.time(predict(m1, newdata=test))
```
which gives
```
> system.time(predict(m1, newdata=test))
   user  system elapsed 
  6.988   0.018   5.139 
> system.time(predict(m1, newdata=test))
   user  system elapsed 
  7.199   0.015   5.029 
```
and overall 100% CPU usage (peaking at ~200% but I suppose this is the overhead of switching between R and the C backend).

### Train multi-threaded -> predict multi-threaded

```R
load("data.Rdata")
library("xgboost")
m5 <- xgb.train(
  params=list(eta=0.05, max_depth=4, nthread=5),
  data=xgb.DMatrix(train[,1:2], label=train[,3]),
  nrounds=1000, verbose=FALSE)
system.time(predict(m5, newdata=test))
system.time(predict(m5, newdata=test))
```
gives
```
> system.time(predict(m5, newdata=test))
   user  system elapsed 
  6.820   0.045   1.119 
> system.time(predict(m5, newdata=test))
   user  system elapsed 
  7.237   0.011   1.126 
```
and CPU ~500% (with some peaks higher).

### Train single then multi-threaded -> predict multi-threaded

```R
load("data.Rdata")
library("xgboost")
m1 <- xgb.train(
  params=list(eta=0.05, max_depth=4, nthread=1),
  data=xgb.DMatrix(train[,1:2], label=train[,3]),
  nrounds=1000, verbose=FALSE)
m5 <- xgb.train(
  params=list(eta=0.05, max_depth=4, nthread=5),
  data=xgb.DMatrix(train[,1:2], label=train[,3]),
  nrounds=1000, verbose=FALSE)
system.time(predict(m1, newdata=test))
system.time(predict(m5, newdata=test))
system.time(predict(m1, newdata=test))
system.time(predict(m5, newdata=test))
```
gives
```
> system.time(predict(m1, newdata=test))
   user  system elapsed 
  6.939   0.016   1.125 
> system.time(predict(m5, newdata=test))
   user  system elapsed 
  6.912   0.017   1.095 
> system.time(predict(m1, newdata=test))
   user  system elapsed 
  7.052   0.052   1.105 
> system.time(predict(m5, newdata=test))
   user  system elapsed 
  6.899   0.012   1.098 
```
and ~500% CPU usage.

### Train multi then single-threaded -> predict single-threaded

```R
load("data.Rdata")
library("xgboost")
m5 <- xgb.train(
  params=list(eta=0.05, max_depth=4, nthread=5),
  data=xgb.DMatrix(train[,1:2], label=train[,3]),
  nrounds=1000, verbose=FALSE)
m1 <- xgb.train(
  params=list(eta=0.05, max_depth=4, nthread=1),
  data=xgb.DMatrix(train[,1:2], label=train[,3]),
  nrounds=1000, verbose=FALSE)
system.time(predict(m1, newdata=test))
system.time(predict(m5, newdata=test))
system.time(predict(m1, newdata=test))
system.time(predict(m5, newdata=test))
```
gives
```
> system.time(predict(m1, newdata=test))
   user  system elapsed 
  6.934   0.012   5.081 
> system.time(predict(m5, newdata=test))
   user  system elapsed 
  6.865   0.016   4.898 
> system.time(predict(m1, newdata=test))
   user  system elapsed 
  6.816   0.007   4.982 
> system.time(predict(m5, newdata=test))
   user  system elapsed 
  6.906   0.019   4.931 
```
and 100% CPU usage

### Train multi, then single, then multi-threaded -> predict multithreaded

```R
load("data.Rdata")
library("xgboost")
m5 <- xgb.train(
  params=list(eta=0.05, max_depth=4, nthread=5),
  data=xgb.DMatrix(train[,1:2], label=train[,3]),
  nrounds=1000, verbose=FALSE)
m1 <- xgb.train(
  params=list(eta=0.05, max_depth=4, nthread=1),
  data=xgb.DMatrix(train[,1:2], label=train[,3]),
  nrounds=1000, verbose=FALSE)
m5 <- xgb.train(
  params=list(eta=0.05, max_depth=4, nthread=5),
  data=xgb.DMatrix(train[,1:2], label=train[,3]),
  nrounds=1000, verbose=FALSE)
system.time(predict(m1, newdata=test))
system.time(predict(m5, newdata=test))
system.time(predict(m1, newdata=test))
system.time(predict(m5, newdata=test))
```
```
> system.time(predict(m1, newdata=test))
   user  system elapsed 
  7.288   0.154   1.116 
> system.time(predict(m5, newdata=test))
   user  system elapsed 
  6.925   0.042   1.119 
> system.time(predict(m1, newdata=test))
   user  system elapsed 
  6.910   0.024   1.130 
> system.time(predict(m5, newdata=test))
   user  system elapsed 
  6.714   0.031   1.103 
```
and ~500% CPU usage.

So, irrespective of the `nthread` setting in the model object, `predict()` seems to use a number of threads defined by the **last trained model**.

## Predict from saved model -> depends on the second ran model!

After of the steps above, serialize models to disk using R's format:
```R
save(m1, m5, file="models.Rdata")
```
and then restart before running each following section

```R
library("xgboost")
load("data.Rdata")
load("models.Rdata")
system.time(predict(m1, newdata=test))
system.time(predict(m5, newdata=test))
system.time(predict(m1, newdata=test))
system.time(predict(m5, newdata=test))
```
gives
```
> system.time(predict(m1, newdata=test))
   user  system elapsed 
  6.982   0.015   5.045 
> system.time(predict(m5, newdata=test))
   user  system elapsed 
  6.747   0.015   1.161 
> system.time(predict(m1, newdata=test))
   user  system elapsed 
  7.160   0.012   1.137 
> system.time(predict(m5, newdata=test))
   user  system elapsed 
  7.355   0.012   1.130 
```
with CPU usage matching the times.

But 

```R
library("xgboost")
load("data.Rdata")
load("models.Rdata")
system.time(predict(m5, newdata=test))
system.time(predict(m1, newdata=test))
system.time(predict(m5, newdata=test))
system.time(predict(m1, newdata=test))
```
gives
```
> system.time(predict(m5, newdata=test))
   user  system elapsed 
  6.943   0.009   1.179 
> system.time(predict(m1, newdata=test))
   user  system elapsed 
  6.966   0.013   5.115 
> system.time(predict(m5, newdata=test))
   user  system elapsed 
  7.063   0.017   5.068 
> system.time(predict(m1, newdata=test))
   user  system elapsed 
  7.117   0.009   5.034 
```

So the number of threads used depends on the **second** model that is evaluated, not the first, for a reason I cannot fathom (it may be distantly linked to #4877).

## Why bother?

There are a few use cases where this is problematic:
- train a big model multithreaded, do some small tests single threaded to free CPU for other tasks, evaluate the big model -> it runs single threaded (slooow).
- predict from several models and parallelise at the level of this higher loop -> fails because of competing request for cores/threads
- train with no `nthread` parameter -> no way to control the number of threads used by `predict()`
- ...

---

Let me know if I can do something more.

I would also welcome pointers towards a workaround. I suppose that it is linked with some state of the C backend which is preserved after training or the (second!) run of evaluation. Any way to reset that before evaluation, so that the number of threads is actually defined by the `nthread` parameter stored in the model object?

**Comment by trivialfis** [comment]
Hi, thanks for opening an issue with such details, we really appreciate issues like this. ;-)

Could you please try:
``` R
booster <- xgb.train(....)  # train a model with multiple threads
xgb.parameters(booster) <- list(nthread = 1)
```
and run the prediction again? Also, when persisting a model, please use:
```
xgb.save(booster)
```
This function saves the model only while all the other parameters are discarded. Besides, the format is stable. See https://xgboost.readthedocs.io/en/stable/tutorials/saving_model.html for details.

**Comment by jiho** [comment]
Glad to help.

### Setting `nthread` through `xgb.parameters()` -> works

Setting `nthread` in the parameters works as expected
```r
load("data.Rdata") # from above
library("xgboost")
m5 <- xgb.train(
  params=list(eta=0.05, max_depth=4, nthread=5),
  data=xgb.DMatrix(train[,1:2], label=train[,3]),
  nrounds=1000, verbose=FALSE)
system.time(predict(m5, newdata=test))
xgb.parameters(m5) <- list(nthread = 1)
system.time(predict(m5, newdata=test))
```
gives
```
> system.time(predict(m5, newdata=test))
   user  system elapsed 
  7.090   0.018   1.162 
> xgb.parameters(m5) <- list(nthread = 1)
> system.time(predict(m5, newdata=test))
   user  system elapsed 
  7.023   0.042   5.163 
```
but
```
> m5$params
$eta
[1] 0.05

$max_depth
[1] 4

$nthread
[1] 5

$validate_parameters
[1] TRUE

```
So `nthread` is not changed there. I am looking in the wrong place?

### Serialising with `xgb.save()` -> resets parameters ... but

```r
load("data")
library("xgboost")
m1 <- xgb.train(
  params=list(eta=0.05, max_depth=4, nthread=5),
  data=xgb.DMatrix(train[,1:2], label=train[,3]),
  nrounds=1000, verbose=FALSE)
m5 <- xgb.train(
  params=list(eta=0.05, max_depth=4, nthread=5),
  data=xgb.DMatrix(train[,1:2], label=train[,3]),
  nrounds=1000, verbose=FALSE)
xgb.save(m1, "m1.xgb")
xgb.save(m5, "m5.xgb")
# restart R
load("data.Rdata")
library("xgboost")
m1 <- xgb.load("m1.xgb")
m5 <- xgb.load("m5.xgb")
system.time(predict(m1, newdata=test))
system.time(predict(m5, newdata=test))
xgb.parameters(m1) <- list(nthread=1)
xgb.parameters(m5) <- list(nthread=5)
system.time(predict(m1, newdata=test))
system.time(predict(m5, newdata=test))
```
gives
```
> m1$params
NULL
> system.time(predict(m1, newdata=test))
   user  system elapsed 
 11.587   0.022   0.305 
> system.time(predict(m5, newdata=test))
   user  system elapsed 
 12.612   0.013   0.222 
```
which is the timing on all cores, and
```
> xgb.parameters(m1) <- list(nthread=1)
> xgb.parameters(m5) <- list(nthread=5)
> system.time(predict(m1, newdata=test))
   user  system elapsed 
  6.964   0.014   1.067 
> system.time(predict(m5, newdata=test))
   user  system elapsed 
  7.097   0.040   1.080 
```
but that is the timing on 5 cores, for both models, instead of a different timing for each!

### Setting `nthread` with `xgb.parameters()` -> affects all the evaluation of all models!

Intrigued I tried to apply this to a completely different model

```r
m_other <- xgb.train(
  params=list(eta=0.05, max_depth=4, nthread=1),
  data=xgb.DMatrix(train[,1:2], label=train[,3]),
  nrounds=10, verbose=FALSE)
xgb.save(m_other, "m_other.xgb")
# restart R
load("data.Rdata")
library("xgboost")
m1      <- xgb.load("m1.xgb")
m5      <- xgb.load("m5.xgb")
m_other <- xgb.load("m_other.xgb")

xgb.parameters(m_other) <- list(nthread=1)
system.time(predict(m1, newdata=test))
system.time(predict(m5, newdata=test))

xgb.parameters(m_other) <- list(nthread=5)
system.time(predict(m1, newdata=test))
system.time(predict(m5, newdata=test))

xgb.parameters(m_other) <- list(nthread=10)
system.time(predict(m1, newdata=test))
system.time(predict(m5, newdata=test))
```
and sure enough
```
> xgb.parameters(m_other) <- list(nthread=1)
> system.time(predict(m1, newdata=test))
   user  system elapsed 
  7.322   0.023   5.229 
> system.time(predict(m5, newdata=test))
   user  system elapsed 
  7.153   0.028   4.907 
> 
> xgb.parameters(m_other) <- list(nthread=5)
> system.time(predict(m1, newdata=test))
   user  system elapsed 
  7.291   0.052   1.088 
> system.time(predict(m5, newdata=test))
   user  system elapsed 
  6.806   0.032   1.082 
> 
> xgb.parameters(m_other) <- list(nthread=10)
> system.time(predict(m1, newdata=test))
   user  system elapsed 
  7.439   0.015   0.589 
> system.time(predict(m5, newdata=test))
   user  system elapsed 
  7.334   0.013   0.772 
```

This shows that setting the number of threads through `xgb.parameters()` on any `xgb.Booster` object actually sets it for the evaluation of any other object. This gives me a work around for now but seems very weird...

I understand that, underneath there is a xgboost C-level which the R process communicates with (through JSON strings as far as I can see), so it would be understandable to set parameters affecting the whole C level. But doing it indirectly through a model object that is an entity in the R world is disconcerting. Maybe this should go through global options in R, or through an explicit "boosting engine" object that is affected by the existing functions (and this is documented for each function) but can also be modified through dedicated functions?

**Comment by trivialfis** [comment]
> Setting nthread in the parameters works as expected
Great!

> So nthread is not changed there. I am looking in the wrong place?

No.  Personally I haven't used this attribute before.  The parameters are stored inside c++ code so I think the R list is out of sync after setting the parameters.  If you are familiar with designing R libraries feel free to suggest an alternative solution.  Right now for R package I usually use `xgb.config(booster)` to inspect the parameters, which is querying the c++ library so it's always synced.

Regarding the global level change of threads, we are working to address that, some PRs have already been merged: https://github.com/dmlc/xgboost/pull/7537 https://github.com/dmlc/xgboost/pull/7519 but more work needs to be done to completely remove the global variable.  The expected end result is `nthread` will be local to each booster.

**Comment by jiho** [comment]
I can confirm that, in 1.6.0.1 in R, setting `nthread` on `xgb.Train` has the expected result in `predict`(i.e. the behaviour that depends on the previous execution disappears).

Changing this through `xgb.parameters()` before prediction works as expected.

Setting it through `model$params$nthread` still does nothing.

**Comment by hcho3** [comment]
`model$params` is meant to be read-only. Parameters should be set using `xgb.parameters <-`.

**Comment by jiho** [comment]
OK thanks. Apparently `nthread` is not supported by `predict.xgb.Booster()`. I assume that if one wants to change the number of threads between training and inference, the one as to do something like
```
model <- xgboost(..., nthread=10)
xgb.parameters(model) <- list(nthread=1)
predict(mode, newdata=...)
```
right?

Would you welcome a pull requests that adds `nthread` as an argument to predict (and just calls `xgb.parameters()` within `predict.xgb.Booster()`?

**Comment by trivialfis** [comment]
> then one has to do something like

Yes.

> Would you welcome a pull requests that adds nthread as an argument to predict

Thank you for the offer. Could you please be more specific about the difference between using a setter instead of an additional parameter?  The `predict` function for XGBoost is thread-safe, embedding a parameter setter inside it might cause a race condition.

**Comment by jiho** [comment]
> Thank you for the offer. Could you please be more specific about the difference between using a setter instead of an additional parameter? The `predict` function for XGBoost is thread-safe, embedding a parameter setter inside it might cause a race condition.

Just convenience
```
model <- xgboost(..., nthread=10)
predict(mode, newdata=..., nthread=1)
```
instead of 
```
model <- xgboost(..., nthread=10)
xgb.parameters(model) <- list(nthread=1)
predict(mode, newdata=...)
```
but I don't know enough about the xgboost engine under the hood to not mess it up. So I'll just use `xgb.parameters()` 😉
