### ISSUE TITLE
Weight parameter not used while using xgboost aft

### ISSUE THREAD

**Issue by SymbolAnkit** [dmlc/xgboost#7587]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/35793585/150510237-e1f6b39e-e557-4743-804b-f886e8965b2a.png)
Thanks for participating in the XGBoost community! We use https://discuss.xgboost.ai for any general usage questions and discussions. The issue tracker is used for actionable items such as feature proposals discussion, roadmaps, and bug tracking.  You are always welcomed to post on the forum first :)

Issues that are inactive for a period of time may get closed. We adopt this policy so that we won't lose track of actionable issues that may fall at the bottom of the pile. Feel free to reopen a new one if you feel there is an additional problem that needs attention when an old one gets closed.

For bug reports, to help the developer act on the issues, please include a description of your environment, preferably a minimum script to reproduce the problem.

For feature proposals, list clear, small actionable items so we can track the progress of the change.

**Comment by trivialfis** [comment]
Hi, there's no "weight" parameter.  If you are referring to sample weights or feature weights,  please use the `DMatrix` or `fit` method depending on which interface you are using.

**Comment by SymbolAnkit** [comment]
Hi,
we have used IPCW estimator by giving extra weight to subjects which are not censored (this is per subject). we want to use this weight in the gradient and hessian as does by the xgboost, how ever when we are passing the same as matrix throgh xgboost aft we are getting the above warning message.
Kindly suggest, how we can incorporate

**Comment by trivialfis** [comment]
Could you please share your code?

**Comment by trivialfis** [comment]
> we want to use this weight in the gradient and hessian 

That's usually done by:
``` python
weight = np.array(...)
Xy = xgb.DMatrix(X, y, weight=weight)
xgb.train({"tree_method": "gpu_hist"}, Xy, num_boost_round=10)
```

The error message indicates that, the downstream library is doing some like:
```
weight = np.array(...)
Xy = xgb.DMatrix(X, y)
xgb.train({"tree_method": "gpu_hist", "weight": weight}, Xy, num_boost_round=10)
```
