### ISSUE TITLE
pandas.Int64Index is deprecated

### ISSUE THREAD

**Issue by trivialfis** [dmlc/xgboost#7593]
```
compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index
```
```
data.py:267: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):
```

```
>>> import pandas as pd
>>> pd.__version__
'1.4.0'
```

**Comment by freddyaboulton** [comment]
Thank you @trivialfis . Saw this on my CI pipeline tests as well.

**Comment by NikitaRubocki** [comment]
Would love some help, per the PR it seems like this issue has been resolved, but I am running Python 3.8, pandas 1.4.0, and XGBoost 1.5.2 and receiving this error still:

> 
python3.8/site-packages/xgboost/data.py:262: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.                                                                                                                                                                         elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):

**Comment by trivialfis** [comment]
We haven't made the release yet.  You can install nightly if needed.

**Comment by serkannpolatt** [comment]
> Biraz yardım isterim, Halkla İlişkiler'e göre bu sorun çözülmüş gibi görünüyor, ancak Python 3.8, pandas 1.4.0 ve XGBoost 1.5.2 kullanıyorum ve hala bu hatayı alıyorum:
> 
> > 
> 
> python3.8/site-packages/xgboost/data.py:262: FutureWarning: pandas.Int64Index kullanımdan kaldırıldı ve gelecekteki bir sürümde pandalardan kaldırılacak. Bunun yerine pandas.Index'i uygun dtype ile kullanın. elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):
### ### 


bendede bu hata veriyor daha bugün karşılaştım
