### ISSUE TITLE
import error (compatibility with the M1 chip?)

### ISSUE THREAD

**Issue by shizuchanw** [dmlc/xgboost#7596]
I have import errors for `XGBoost`, and I checked this issue with `runipy`. The result looks like this: 
<img width="585" alt="Screen Shot 2022-01-23 at 11 44 28 PM" src="https://user-images.githubusercontent.com/50822201/150743092-7d973627-7359-4410-b5d5-66be870d1f25.png">

However, I have `libomp` installed on my laptop. I reinstalled it and checked again, and there was still this import error. 

I was able to import both packages on my old laptop (with Intel chip), but I have import error on my new laptop (with the M1 chip). Therefore, I was wondering whether this error was caused by the compatibility with the M1 chip, since the path changed for my brew and all packages installed with brew from `/usr/local/bin/brew` to `/opt/homebrew`. Would this be the reason that XGBoost can't find the libomp package?

**Comment by shizuchanw** [comment]
@JiaxiangBU

**Comment by hcho3** [comment]
See https://github.com/dmlc/xgboost/issues/6408. We currently do not support Apple Silicon.

**Comment by trivialfis** [comment]
Closing as duplicated to https://github.com/dmlc/xgboost/issues/6408

**Comment by hcho3** [comment]
@shizuchanw You may have a better luck with using Conda to install XGBoost on Apple Silion:
```
conda install -c conda-forge xgboost
```
which will install XGBoost built with `osx-arm64` architecture.
