### ISSUE TITLE
after "bash build.sh" How to install xgboost

### ISSUE THREAD

**Issue by superfan123** [dmlc/xgboost#76]
I'm new to python and new to ubuntu. 
After "bash build.sh" I saw a program "xgboost". Then how to install the model ?
I have "import xgboost as xgb" in my py program but looks like they didn't find it.
I got "ImportError: No module named xgboost"
Thanks for you help.

**Comment by shdut** [comment]
How can I use it only by c++?

**Comment by tqchen** [comment]
check out instruction in the https://github.com/dmlc/xgboost/blob/master/doc/README.md if you mean CLI version. If you mean use the c++ class, you will need to read the interface of modules in xgboost
