### ISSUE TITLE
Incremental learning error?

### ISSUE THREAD

**Issue by HL-Liu** [dmlc/xgboost#7600]
I am using 'update' with 'refresh' updater. I got the following warning message: 
WARNING: ..\src\gbm\gbtree.cc:82: DANGER AHEAD: You have manually specified `updater` parameter. The `tree_method` parameter will be ignored. Incorrect sequence of updaters will produce undefined behavior. For common uses, we recommend using `tree_method` parameter instead.
[23:04:12] WARNING: ..\src\learner.cc:576: 
Parameters: { "silent" } might not be used.

  This could be a false alarm, with some parameters getting used by language bindings but
  then being mistakenly passed down to XGBoost core, or some parameter actually being used
  but getting flagged wrongly here. Please open an issue if you find any such cases.

What does that mean? Should I not using tree_method?

**Comment by trivialfis** [comment]
Hi, this is a 2 part warning message.

> You have manually specified updater parameter. The tree_method parameter will be ignored

If you have specifed the `updater`, then `tree_method` should not be specified.

> Parameters: { "silent" } might not be used.

There's no `silent` parameter is latest xgboost.
