### ISSUE TITLE
(R) Cannot predict on CSR data

### ISSUE THREAD

**Issue by david-cortes** [dmlc/xgboost#7610]
In the R interface, it is not possible to use the predict function on sparse CSR data like in the other interfaces, which greatly reduces the usability of sparse data support as then any single-row prediction for sparse data would become `O(ncols)` rather than `O(nnz)` or `O(nnz*log(nnz))`.

The R interface uses `Matrix` for sparse matrix classes - the package matrix has classes `dgRMatrix` for CSR format and `dsparseVector` for single-row CSR data, but currently the predict function takes only CSC (`dgCMatrix`).
```r
library(xgboost)
library(Matrix)
data(mtcars)
X <- as.matrix(mtcars[, -1])
y <- mtcars[, 1]
model <- xgboost(as(X, "CsparseMatrix"), y, nrounds=5, verbose=0)
predict(model, as(X, "RsparseMatrix"))
```
```
Error in xgb.DMatrix(newdata, missing = missing) : 
  xgb.DMatrix does not support construction from S4
```

vs.
```python
from xgboost import XGBRegressor
from scipy.sparse import csr_matrix
from sklearn.datasets import load_boston
X, y = load_boston(return_X_y=True)
model = XGBRegressor(n_estimators=5).fit(X, y)
pred = model.predict(csr_matrix(X))
```
(which works correctly)

**Comment by trivialfis** [comment]
Hi thank you for the issue.  Would you like to open a PR for the feature?

**Comment by david-cortes** [comment]
> Hi thank you for the issue. Would you like to open a PR for the feature?

Ok, will probably work on it later this week.

**Comment by trivialfis** [comment]
Thank you!  Looking forward to it.
