### ISSUE TITLE
M1 Pro only using 6 cores

### ISSUE THREAD

**Issue by Coesyn** [dmlc/xgboost#7614]
Using XGBoost on M1 is great and it uses all 8 cores, 4e cores and 4p cores. When I move over to the M1 Pro it only uses 6 cores, 2e cores and 4p cores. Therefore training is slower on the M1 Pro. Tried changing the n_jobs and it still only works on 6 cores. 

I am using the same code on each machine. I have even tried different python versions and XGBoost versions (both 1.5.0 and 1.5.1. Using native arm version from conda-forge.

**Comment by hcho3** [comment]
None of the XGBoost developers has an M1 machine.

Can you build and run the following C++ program on your M1 pro and see if it uses all 8 cores?

```cpp
#include <cstddef>
int main() {
  int n = 1000000000;
  float* a = new float[n];
  float* b = new float[n];
  float* c = new float[n];
#pragma omp parallel for num_threads(8)
  for (int i = 0; i < n; ++i) {
      a[i] = b[i] + c[i];
  }
  delete [] a;
  delete [] b;
  delete [] c;
  return 0;
}
```

**Comment by Coesyn** [comment]
Apologies for the delay. When looking at the CPU history, there is a spike on all CPU cores.

**Comment by Coesyn** [comment]
Done some more testing, and it seems that the algorithm speeds up when going from `nthread` 1 to 4, then it slows down again when increasing from 5 upwards. When using -1 for default it also goes really slow. Is this a limitation of the algorithm, or should `nthread` be used optimised for the specific code running?

**Comment by hcho3** [comment]
I am not familiar with M1 Pro, so can't say much. On Intel chips, you tend to get a linear speed-up until `nthread` reached the number of physical cores.

**Comment by trivialfis** [comment]
That depends on a few things.

- Are you using xgboost inside a hyper-parameter tunning framework?  If so is that framework running in parallel for multiple models?  That might create thread contention.

- The hardware.  But the efficiency of parallelism is highly dependent on the hardware, including memory bandwidth and the CPU itself.  For some benchmarks on x86 (Intel CPU from GCP), XGBoost can scale to 48 and sometimes 96 threads (96 is enabled by hyper-threading I believe).    I don't have a mac device so can't be sure about its efficiency.

**Comment by Coesyn** [comment]
Thanks for the reply. I have just tried on a ryzen processor and experiencing similar performance. It must be down to the way in which I am implementing the code. 

I'm new to python and so will look at what I can do to improve things. Thanks for the help I am happy to close this off as it doesn't seem mac specific.

**Comment by leedrake5** [comment]
I know this is closed - but seeing the same thing on a Mac Studio with the M1 Ultra. XGBoost appears to use only the 4 efficiency cores, leaving the 16 performance cores untouched. This must relate to something unusual about Mac's ARM architecture and the current version of XGBoost. As noted by @Coesyn, it works fine on a regular M1 processor. It's the derivatives of that processor (achieved by fusing dyes) that are affected.

**Comment by Francyrad** [comment]
I know also that this is closed, but i had a program with another code called Rebound. I was not able to scale my simulation to 10x, i only got 1x with OpenMP. Is there a solution to the problem?
