### ISSUE TITLE
R interface could use inplace prediction

### ISSUE THREAD

**Issue by david-cortes** [dmlc/xgboost#7616]
The Python interface where possible uses `inplace_predict`, which is fater than creating a `DMatrix` object for making predictions. The R interface OTOH always uses `DMatrix`, which requires 2 redundant copies of the data. It should be possible to use functions such as `XGBoosterPredictFromDense` in the R interface too, avoiding an extra data copy, and wrapping them should be even simpler since R does not support as many array configurations as numpy (e.g. no strided array views).

**Comment by trivialfis** [comment]
Do you think we should add a parameter for the predict function to use inplace prediction optionally?  The prediction using `DMatrix` can be cached as we can use its memory address as the cache key so it's not always slower than inplace prediction.

**Comment by david-cortes** [comment]
> Do you think we should add a parameter for the predict function to use inplace prediction optionally? The prediction using `DMatrix` can be cached as we can use its memory address as the cache key so it's not always slower than inplace prediction.

Bu whether it's cached or not, it first needs to produce a data copy when it casts the `double` R array to a `float` vector, and then when it copies that `float` vector to the DMatrix that's being created.

**Comment by trivialfis** [comment]
Would you like to work on the interface?  :-). The R package can use a lot of help.

**Comment by david-cortes** [comment]
I'll pass on this specific feature.
