### ISSUE TITLE
Bug? Incremental training: new model contains both updated trees and trees of input model

### ISSUE THREAD

**Issue by HL-Liu** [dmlc/xgboost#7635]
Using trees_to_dataframe(), I saw the new model contains 20 trees while the input model "xgb_Model_laststage" contains 10 trees. The updated trees are numbered from 10 to 20 and the trees from 0-10 are exactly the same as those of "xgb_Model_laststage".

My code is below:
  xgb_Params_final = xgb_Params.copy()
  xgb_Params_final['process_type'] = 'update'
  xgb_Params_final['updater'] = 'refresh'
  xgb_Params_final['refresh_leaf'] = True
  xgb_Params_final['silent'] = False
  xgb_Model_final = xgb.train(
                  xgb_Params,
                  dtrain=dm_train,
                  # num_boost_round=xgb_Model_laststage.best_ntree_limit,
                  feval=ff_eval,
                  maximize=True,
                  # evals=[(dm_test, 'test')],
                  # verbose_eval=1,
                  xgb_model=xgb_Model_laststage
                  )

**Comment by trivialfis** [comment]
The `refresh` updater must refresh all the trees, which is a limitation for now.

**Comment by HL-Liu** [comment]
> 

Thanks for answering. I know this limitation. But the new model contains 2 times of trees (refreshed and original) and I guess, in prediction, they will be all used, as there is no parameter to tell from which tree to start (also not in line with the concept of "boosting"). This is for sure wrong but not only a limitation, right?

**Comment by trivialfis** [comment]
Closing as stalled.
