### ISSUE TITLE
Error when using EarlyStopping callback during CV

### ISSUE THREAD

**Issue by PayamDiba** [dmlc/xgboost#7637]
When I use early stopping callback in xgboost.cv (python) I get error, here is a snapshot of my script:

self.early_stopper_ = xgb.callback.EarlyStopping(rounds = 50, min_delta = 1e-2)
result = xgb.cv(
                params = params,
                dtrain = data_train,
                num_boost_round = self.max_round_,
                seed = seed,
                nfold = 3,
                metrics = params['eval_metric'],
                callbacks = [self.early_stopper_],
            )

I get the following error:

> return int(self.cvfolds[0].bst.attr("best_iteration"))
> TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by trivialfis** [comment]
Could you please share your xgboost version?

**Comment by PayamDiba** [comment]
I am using version 1.5.0

**Comment by trivialfis** [comment]
Could you please share a reproducible example?  I can't reproduce it.

**Comment by PayamDiba** [comment]
I think I found the problem, I am calling xgboost.cv in a "for loop", it turns out that I have to re-define EarlyStopping callback at the beginning of each loop:

for param in all_params:
     early_stopper = xgb.callback.EarlyStopping(rounds = 50, min_delta = 1e-2) ## should be defined in each loop
     result = xgb.cv(
                        params = param,
                        dtrain = data_train,
                        num_boost_round = self.max_round_,
                        seed = seed,
                        nfold = 3,
                        metrics = params['eval_metric'],
                        callbacks = [early_stopper],
                        )

**Comment by trivialfis** [comment]
Good catch!  The callbacks are not copied in cv.

**Comment by trivialfis** [comment]
```
    callbacks = [] if callbacks is None else copy.copy(list(callbacks))
```

**Comment by PayamDiba** [comment]
I think deep copy is needed, i.e. copy.deepcopy(list(callbacks)), or I might be wrong?!

**Comment by trivialfis** [comment]
I'm not sure if we should run deepcopy, if your callback has states then changes to states will be lost after training.  For instance, I use callbacks to add extra logging or save a copy of the booster

**Comment by PayamDiba** [comment]
For some reason, shallow copy does not work for me when I am trying to use early stopping callback, but deep copy works:
```
self.early_stopper_ = xgb.callback.EarlyStopping(rounds = early_stopping_round, min_delta = early_stopping_tol)
for params in allParDicts:
            results = xgb.cv(
                params = params,
                dtrain = data_train,
                num_boost_round = self.max_round_,
                seed = seed,
                nfold = 3,
                metrics = params['eval_metric'],
                callbacks = [copy.deepcopy(self.early_stopper_)]
            )
```

**Comment by trivialfis** [comment]
I will document the behavior that states in callbacks are not preserved during training.
