### ISSUE TITLE
Makefile:29: dmlc-core/make/dmlc.mk: No such file or directory make: *** No rule to make target 'dmlc-core/make/dmlc.mk'. 

### ISSUE THREAD

**Issue by enedene** [dmlc/xgboost#764]
There is a problem with compiling. It must have been introduced recently, as I successful in installing xgboost a week ago.

`git clone https://github.com/dmlc/xgboost.git`
`cd xgboost`
`make`

returns:
`Makefile:29: dmlc-core/make/dmlc.mk: No such file or directory`
`make: *** No rule to make target 'dmlc-core/make/dmlc.mk'.  Stop.`

**Comment by tqchen** [comment]
We need a recursive clone, see https://xgboost.readthedocs.org/en/latest/build.html#building-on-ubuntu-debian

**Comment by enedene** [comment]
Thank you. I was not aware of a change.

**Comment by brickerino** [comment]
Could you please update wormhole making rules accordingly? It uses just 'clone' and gets the same error.

**Comment by brendano** [comment]
I just got the same error.  I was following the directions listed on dmlc/wormhole which led to the error.  Good thing I found this otherwise I would have given up trying to get started.

**Comment by firstboy0513** [comment]
# in wormhole home directory
cd ./repo/xgboost
cp -rf ../dmlc-core/* dmlc-core/

# git clone your rabit and complier it
cd ./repo/xgboost
git clone https://github.com/dmlc/rabit.git
cd ./rabit && make && cd -


g++ -std=c++0x -Wall -O3 -msse2 -Wno-unknown-pragmas -funroll-loops -Iinclude -Idmlc-core/include -Irabit/include -fPIC -DDISABLE_OPENMP -shared -o lib/libxgboost.so build/learner.o build/logging.o build/c_api/c_api.o build/c_api/c_api_error.o build/common/common.o build/data/data.o build/data/simple_csr_source.o build/data/simple_dmatrix.o build/data/sparse_page_dmatrix.o build/data/sparse_page_raw_format.o build/data/sparse_page_source.o build/gbm/gblinear.o build/gbm/gbm.o build/gbm/gbtree.o build/metric/elementwise_metric.o build/metric/metric.o build/metric/multiclass_metric.o build/metric/rank_metric.o build/objective/multiclass_obj.o build/objective/objective.o build/objective/rank_obj.o build/objective/regression_obj.o build/tree/tree_model.o build/tree/tree_updater.o build/tree/updater_colmaker.o build/tree/updater_histmaker.o build/tree/updater_prune.o build/tree/updater_refresh.o build/tree/updater_skmaker.o build/tree/updater_sync.o dmlc-core/libdmlc.a -lm -fopenmp -lglog

ld: library not found for -lgomp
clang: error: linker command failed with exit code 1 (use -v to see invocation)

And now I known my mac g++ is clang, it can not support openmp.

**Comment by thirdwing** [comment]
@firstboy0513  What about trying `brew install clang-omp`?

**Comment by firstboy0513** [comment]
Thanks @thirdwing , A good advise to use clang-omp, but now some symbols links error, I'll try to re-complie it later.
```
clang-omp++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -DDISABLE_OPENMP -shared -o lib/libxgboost.so build/learner.o build/logging.o build/c_api/c_api.o build/c_api/c_api_error.o build/common/common.o build/data/data.o build/data/simple_csr_source.o build/data/simple_dmatrix.o build/data/sparse_page_dmatrix.o build/data/sparse_page_raw_format.o build/data/sparse_page_source.o build/gbm/gblinear.o build/gbm/gbm.o build/gbm/gbtree.o build/metric/elementwise_metric.o build/metric/metric.o build/metric/multiclass_metric.o build/metric/rank_metric.o build/objective/multiclass_obj.o build/objective/objective.o build/objective/rank_obj.o build/objective/regression_obj.o build/tree/tree_model.o build/tree/tree_updater.o build/tree/updater_colmaker.o build/tree/updater_histmaker.o build/tree/updater_prune.o build/tree/updater_refresh.o build/tree/updater_skmaker.o build/tree/updater_sync.o dmlc-core/libdmlc.a -pthread -lm  -fopenmp -lglog
clang-3.5: warning: argument unused during compilation: '-pthread'
Undefined symbols for architecture x86_64:
  "__ZN5rabit6engine10Allreduce_EPvmmPFvPKvS1_iRKN3MPI8DatatypeEENS0_3mpi8DataTypeENSA_6OpTypeEPFvS1_ES1_", referenced from:
      __ZN7xgboost11LearnerImpl13LazyInitModelEv in learner.o
      __ZNK7xgboost6metric13EvalEWiseBaseINS0_21EvalPoissionNegLogLikEE4EvalERKNSt3__16vectorIfNS4_9allocatorIfEEEERKNS_8MetaInfoEb in elementwise_metric.o
      __ZNK7xgboost6metric13EvalEWiseBaseINS0_9EvalErrorEE4EvalERKNSt3__16vectorIfNS4_9allocatorIfEEEERKNS_8MetaInfoEb in elementwise_metric.o
      __ZNK7xgboost6metric13EvalEWiseBaseINS0_11EvalLogLossEE4EvalERKNSt3__16vectorIfNS4_9allocatorIfEEEERKNS_8MetaInfoEb in elementwise_metric.o
      __ZNK7xgboost6metric13EvalEWiseBaseINS0_8EvalRMSEEE4EvalERKNSt3__16vectorIfNS4_9allocatorIfEEEERKNS_8MetaInfoEb in elementwise_metric.o
      __ZNK7xgboost6metric14EvalMClassBaseINS0_16EvalMultiLogLossEE4EvalERKNSt3__16vectorIfNS4_9allocatorIfEEEERKNS_8MetaInfoEb in multiclass_metric.o
      __ZNK7xgboost6metric14EvalMClassBaseINS0_14EvalMatchErrorEE4EvalERKNSt3__16vectorIfNS4_9allocatorIfEEEERKNS_8MetaInfoEb in multiclass_metric.o
...
ld: symbol(s) not found for architecture x86_64
clang-3.5: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [lib/libxgboost.so] Error 1
make: *** [repo/xgboost/xgboost] Error 2
```

**Comment by thirdwing** [comment]
@firstboy0513 Have you `make clean_all`?
