### ISSUE TITLE
Why is XGBoost 'auc' score different from sklearn 'roc-auc-score'?

### ISSUE THREAD

**Issue by Jing25** [dmlc/xgboost#7656]
Hi there,

I found that the xgboost 'auc' score is a different from the sklearn 'roc_auc_score'. Is this difference expected? Did I do something wrong or is there a bug? My XGBoost version is '1.4.2', sklearn version is '1.0.2'

<img width="705" alt="image" src="https://user-images.githubusercontent.com/27107288/153993322-d2a9c2ed-b32b-45ba-a529-4f16119e86d6.png">

Thank you!

**Comment by trivialfis** [comment]
Most of the time caused by floating-point errors.

**Comment by Jing25** [comment]
> Most of the time caused by floating-point errors.

Got it. Thank you for your reply! I will close this then.
