### ISSUE TITLE
Using/Adding `feature_weights` in R

### ISSUE THREAD

**Issue by hetong007** [dmlc/xgboost#7657]
I received a feature request via email from Prof. Tibshirani:

```
I am an avid user of the  superb  XGBoost pkg in R.

A question: the python version has a feature_weights argument that I find very useful. This option does not appear to be available in R. Would it be possible to
add this to the R pkg?

thanks!

sincerely

Rob Tibshirani
```

My questions are:
- If the R package indeed has this feature, how would one use it?
- If it doesn't have it yet, could we have it in R?

Thanks!

**Comment by trivialfis** [comment]
It's just a meta info like labels and weights.

**Comment by tibshirani** [comment]
That would be great!

**Comment by tibshirani** [comment]
I would just like to pass a vector of non-negative weights, of length the number of columns in the feature matrix.

**Comment by tibshirani** [comment]
I have a new research project for which the feature_weights in xgboost are essential. Thank you for adding this to your
prioritize list. Is this something that is likely to happen relatiively soon? o/w is it simple enough that I  could ask a grad student who knows python (not me) to create a local version with feature_weights?

**Comment by hetong007** [comment]
I think it is relatively easy to enable it by someone familiar with R. Basically one can add the below condition branch in this function: https://github.com/dmlc/xgboost/blob/master/R-package/R/xgb.DMatrix.R#L255

```R
...
if (name == "feature_weights") {
    if (sum(info) != ncol(object))
        stop("The number of feature weights must equal to the number of columns in the input data")
    .Call(XGDMatrixSetInfo_R, object, name, as.numeric(info))
    return(TRUE)
}
...
```

@trivialfis Please correct me if this is not true.

**Comment by trivialfis** [comment]
Looks right, I will work on it tonight.

**Comment by tibshirani** [comment]
Wonderful!  Thanks so much

rob
