### ISSUE TITLE
Failed to load model using C wrapper

### ISSUE THREAD

**Issue by saturosfz** [dmlc/xgboost#766]
I saved the model with python using bst.save_model, and load the model in C using XGBoosterLoadModel, but the loading crashes. The C api is in x86, and I tried to save the model under x86 and x64, but didn't work. The loading works under python. I used xgboost 0.47 release version. Anyone who knows the problem or lets me know how to use C wrapper? It seems there is no intruction for it. Thank you!

**Comment by pommedeterresautee** [comment]
Old bug, no answer. Closing
