### ISSUE TITLE
[QST][Quantile Dmatrix building] is it possible to build DMatrix based on Array data in GPU

### ISSUE THREAD

**Issue by wbo4958** [dmlc/xgboost#7677]
For now, XGBoost4j-spark-gpu passes the separate features columns' cuda array interface to JNI to construct quantile DMatrix. It requires doing the transformation at the RDD level instead of Dataset level, which will result in the later operations (like udf) running on CPU instead of GPU. 

So my question is if we can add a new function to build the quantile DMatrix based on Array column which contains all feature columns.

**Comment by trivialfis** [comment]
Summarizing offline conversation:

> So my question is if we can add a new function to build the quantile DMatrix based on Array column which contains all feature columns.

Yes, it's possible.  But it's best to do it in spark instead of in XGBoost since XGBoost is not really designed for preprocessing features.
