### ISSUE TITLE
Adam optimizer in XGBoost

### ISSUE THREAD

**Issue by lohitslohit** [dmlc/xgboost#7681]
Is it possible to use Adam optimizer in XGBoost classification?

**Comment by trivialfis** [comment]
I don't think so.

**Comment by lohitslohit** [comment]
Why it is not possible Bro.

**Comment by trivialfis** [comment]
xgboost uses second-order gradient for optimization (Newton).  Please consult the reference paper for details.

**Comment by lohitslohit** [comment]
okay Thank you bro.
