### ISSUE TITLE
NVIDIA RAPIDS XGBoost 1.5.2 with GPU error in AcceleratingXGBoostonGPUClusterswithDask.py

### ISSUE THREAD

**Issue by Scheel** [dmlc/xgboost#7697]
I'd greatly appreciate help with 
**Problem**: getting undefined symbol XGProxyDMatrixSetDataCudaArrayInterface
AttributeError
/opt/conda/envs/rapids/lib/libxgboost.so: undefined symbol: XGProxyDMatrixSetDataCudaArrayInterface

**Running xgboost 1.5.2** from docker container rapidsai/rapidsai with

cudf version 0.19.2
dask version 2021.04.0
dask_curd version 0.19.2
numpy version 1.20.2
pendas version 1.2.4
sklearn version 0.23.1
xgboost version 1.5.2

**OS**: Windows 11 (insider version) WSL2 Ubuntu 20.04
2 GPUs:
Wed Feb 23 19:03:01 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.39.01    Driver Version: 511.23       CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:06:00.0  On |                  N/A |
| 20%   41C    P8    16W / 225W |    775MiB / 11264MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  On   | 00000000:0A:00.0 Off |                  N/A |
| 27%   30C    P8    10W / 225W |      0MiB / 11264MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+----------------------------------------------------------------------------

Error thrown on dxgb.train:
    early_stopping_rounds = 5
    Xy = dxgb.DaskDeviceQuantileDMatrix(client, X, y)
    Xy_valid = dxgb.DaskDMatrix(client, X_valid, y_valid)
    # train the model
    booster = dxgb.train(
        client,
        {
            "objective": "binary:logistic",
            "eval_metric": "error",
            "tree_method": "gpu_hist",
        },
        Xy,
        evals=[(Xy_valid, "Valid")],
        num_boost_round=1000,
        early_stopping_rounds=early_stopping_rounds
    )["booster"]

**Exception has occurred: AttributeError
/opt/conda/envs/rapids/lib/libxgboost.so: undefined symbol: XGProxyDMatrixSetDataCudaArrayInterface
  File "/rapids/notebooks/ralph/AcceleratingXGBoostonGPUClusterswithDask.py", line 99,** in main
    early_stopping_rounds=early_stopping_rounds
  File "/rapids/notebooks/ralph/AcceleratingXGBoostonGPUClusterswithDask.py", line 124, in <module>
    main(client)[date=2022-02-23 timezone="America/New_York"]

**Comment by trivialfis** [comment]
Thank you for opening the issue, I will reply in https://github.com/rapidsai/dask-cuda/issues/864 instead.
