### ISSUE TITLE
make on Windows has failed

### ISSUE THREAD

**Issue by lizsz** [dmlc/xgboost#771]
Windows 7x64 Ultimate

Makefile:32: no file name for `include'
g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fopenmp -MM -MT build/c_api/c_api.o src/c_api/c_api.cc >build/c_api/c_api.d
g++ -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fopenmp -c src/c_api/c_api.cc -o build/c_api/c_api.o 
In file included from src/c_api/c_api.cc:14:0:
src/c_api/../common/thread_local.h:80:3: error: 'mutex' in namespace 'std' does not name a type
src/c_api/../common/thread_local.h: In member function 'void xgboost::common::ThreadLocalStore<T>::RegisterDelete(T*)':
src/c_api/../common/thread_local.h:70:5: error: 'unique_lock' is not a member of 'std'
src/c_api/../common/thread_local.h:70:22: error: 'mutex' is not a member of 'std'
src/c_api/../common/thread_local.h:70:39: error: 'mutex_' was not declared in this scope
src/c_api/../common/thread_local.h:70:45: error: there are no arguments to 'lock' that depend on a template parameter, so a declaration of 'lock' must be available [-fpermissive]
src/c_api/../common/thread_local.h:70:45: note: (if you use '-fpermissive', G++ will accept your code, but allowing the use of an undeclared name is deprecated)
src/c_api/../common/thread_local.h:72:5: error: 'lock' was not declared in this scope
src/c_api/../common/thread_local.h: In member function 'void xgboost::common::ThreadLocalStore<T>::RegisterDelete(T*) [with T = XGBAPIThreadLocalEntry]':
src/c_api/../common/thread_local.h:45:7:   instantiated from 'static T* xgboost::common::ThreadLocalStore<T>::Get() [with T = XGBAPIThreadLocalEntry]'
src/c_api/c_api.cc:381:63:   instantiated from here
src/c_api/../common/thread_local.h:70:5: error: 'lock' was not declared in this scope
make: *** [build/c_api/c_api.o] Error 1

**Comment by tqchen** [comment]
Please Check out the instruction on how to build in Windows on the
documentation page.

**Comment by thirdwing** [comment]
I think you are using a MinGW with win32 threading model. Please try the one with posix threading.

**Comment by Jayhello** [comment]
how to solve this question?
