### ISSUE TITLE
How to specify CUDA ARCH while building xgboost?

### ISSUE THREAD

**Issue by jiapei100** [dmlc/xgboost#7713]
It looks by default, to **cmake** **xgboost**, it would build for **ALL cuda architectures**.
Where and how to specify a particular **cuda architecture** just for my native computer, say **sm_75** **ONLY**?

Cheers

**Comment by trivialfis** [comment]
Please see this CMake option: https://github.com/dmlc/xgboost/blob/04fc575c0eef61eac71de11f0d4c610e4458ebdc/CMakeLists.txt#L54

It was added before CUDA language support was added in CMake.  In the long term I think we will migrate to modern CMake builtin option.
