### ISSUE TITLE
Build xgboost 0.90 fails with errors in included c++ header files; using gcc8 as instructed in installation doc

### ISSUE THREAD

**Issue by victor-luu191** [dmlc/xgboost#7717]
I need to build xgboost 0.90 from source code. I followed the [instruction](https://xgboost.readthedocs.io/en/release_0.90/build.html#building-on-osx) in the doc but failed to build.

Make fails at the step "building CXX object" with error messages as below
![Screen Shot 2022-03-04 at 11 25 42 AM](https://user-images.githubusercontent.com/5740261/156858669-28aef05c-4500-413b-9492-f5b4332b5c35.png)

**Comment by victor-luu191** [comment]
I have just resolved this by using a newer version of gcc, gcc-13. So the build [instruction](https://xgboost.readthedocs.io/en/release_0.90/build.html#building-on-osx) for xgboost 0.90 is outdated. Hope somebody can update it.

**Comment by hcho3** [comment]
I'm afraid we don't support 0.90 any more. It was released almost 2 years ago. Is there a particular reason to use 0.90 specifically, rather than use the latest version (1.5.0) ?

**Comment by victor-luu191** [comment]
Hi, it is a dependency issue as my project requires specifically 0.90 to be compatible with other packages we need.

**Comment by trivialfis** [comment]
I can't be entirely sure whether your gcc is correctly configured since the error seems to be internal to gcc.  But since you have already found a workaround I will close this issue now.  Hopefully it can help others who encountered the same issue.
