### ISSUE TITLE
[Bug]: Training with sparse data on a GPU results in bad model performance

### ISSUE THREAD

**Issue by JovanVeljanoski** [dmlc/xgboost#7729]
Hi, 

I believe I've stumbled on a bug when training an `xgboost.XGBClassifier` model on a GPU using sparse data. 
If I train a model on a CPU, i get a certain score (precision, f1 etc..). Using the same hyperparameters (mostly defaults), training a model on the GPU i get substantially worse performance (worse f1, worse precision etc..). 

I tracked it to be somehow related to passing `scipy.sparse._csr.csr_matrix` as a training data. I include a working example below:

```python
import xgboost
import numpy as np
from sklearn.metrics import classification_report

print(xgboost.__version__)
print('')

X = np.load('./Xtrain.npy', allow_pickle=True).item()
y = np.load('./ytrain.npy', allow_pickle=True)

booster_cpu = xgboost.XGBClassifier(learning_rate=0.1, 
                                    max_depth=7, 
                                    n_estimators=1000, 
                                    objective='binary:logistic', 
                                    tree_method='hist', 
                                    use_label_encoder=False, 
                                    eval_metric='logloss')
booster_cpu.fit(X, y)
pred_cpu = booster_cpu.predict(X)


booster_gpu = xgboost.XGBClassifier(learning_rate=0.1, 
                                    max_depth=7, 
                                    n_estimators=1000, 
                                    objective='binary:logistic', 
                                    tree_method='gpu_hist', 
                                    use_label_encoder=False, 
                                    eval_metric='logloss')
booster_gpu.fit(X, y)
pred_gpu = booster_gpu.predict(X)

print('Predictions via the CPU model')
print(classification_report(y, pred_cpu))
print(' ')
print('Predictions via the GPU model')
print(classification_report(y, pred_gpu))
```

This returns 

```
1.5.1

Predictions via the CPU model
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     95269
           1       0.98      0.90      0.94      4731

    accuracy                           0.99    100000
   macro avg       0.99      0.95      0.97    100000
weighted avg       0.99      0.99      0.99    100000

 
Predictions via the GPU model
              precision    recall  f1-score   support

           0       0.97      0.73      0.83     95269
           1       0.10      0.62      0.17      4731

    accuracy                           0.72    100000
   macro avg       0.54      0.67      0.50    100000
weighted avg       0.93      0.72      0.80    100000
```

If the data is converted to a dense numpy array, i.e. `X = X.toarray()` the issue disappears, i.e, i get equivalent results when using the CPU and GPU on my machine. 

### Notes:
 - When training on the CPU i use `tree_method='hist'`
 - Training on the sparse data on GPU takes <2 seconds, but on the same dense version of the data a bit over 15 seconds. On the CPU side, in both cases the training takes the same amount of time (roughly 33 seconds). Maybe this is also an indication of a bug. 

###  Additional information
 - OS: Ubuntu 20.04.1 LTS
 - GPU: GeForce RTX 2080 SUPER
 - Environment: everything installed via conda (xgboost, together with all cuda related libraries via the conda-forge channel)
 - xgboost version: 1.5.1

[data.zip](https://github.com/dmlc/xgboost/files/8246351/data.zip)

**Comment by trivialfis** [comment]
Thank you for raising the issue. As a quick workaround, please call `X.sort_indices()` before passing it to XGBoost.

**Comment by JovanVeljanoski** [comment]
Thank you!
