### ISSUE TITLE
Make on Windows fails

### ISSUE THREAD

**Issue by inoddy** [dmlc/xgboost#773]
I have in the past compiled on Windows OK but today I get this with RRO:

* installing *source* package 'xgboost' ...
** libs
cp -r ../../src .
cp -r ../../rabit .
cp -r ../../dmlc-core .
cp -r ../../include .
cp -r ../../amalgamation .
g++ -m64 -std=c++0x -I"C:/PROGRA~1/Microsoft/MRO/R-3.2.3/include" -DNDEBUG -I.//include -I.//dmlc-core/include -I.//rabit/include -I./ -DXGBOOST_STRICT_R_MODE=1 -DDMLC_LOG_BEFORE_THROW=0 -DDMLC_ENABLE_STD_THREAD=0 -DDMLC_DISABLE_STDIN=1 -DDMLC_LOG_CUSTOMIZE=1 -DXGBOOST_CUSTOMIZE_LOGGER=1 -DRABIT_CUSTOMIZE_MSG_ -DRABIT_STRICT_CXX98_    -I"c:/applications/extsoft/include"  -fopenmp -pthread   -O2 -Wall  -mtune=core2 -c xgboost_R.cc -o xgboost_R.o
xgboost_R.cc:2:26: fatal error: dmlc/logging.h: No such file or directory
compilation terminated.
make: *** [xgboost_R.o] Error 1

**Comment by thirdwing** [comment]
You are using devtools, right?

This should be the same problem  with #760 .

**Comment by inoddy** [comment]
Yes devtools. Yes same issue as #760. I didn't realise that RMarkdown was relevant to my problem.

I tried the fix

devtools::install_git('git://github.com/dmlc/xgboost',subdir='R-package', args='--recursive')

but that produced the same error plus a new warning

In addition: Warning message:
`args` is deprecated 

So I'm still stuck.
Rtools33

**Comment by thirdwing** [comment]
I think the easiest solution for your situation is

```r
install.packages("drat", repos="https://cran.rstudio.com")
drat:::addRepo("dmlc")
install.packages("xgboost", type = "source")
```

Let me know if it doesn't work.

**Comment by inoddy** [comment]
That worked - but did it install the latest xgboost from github? It printed the line

trying URL 'https://cran.revolutionanalytics.com/src/contrib/xgboost_0.4-2.tar.gz'

so it looks to me to be the CRAN rather than the github version and all I did was compile it

**Comment by thirdwing** [comment]
Sorry for this. I forgot to update the version number.

It is the weekly build host at http://dmlc.ml/drat/

You can install it by

```r
drat:::addRepo("dmlc")
install.packages("xgboost", repos="http://dmlc.ml/drat/", type="source")
```

**Comment by inoddy** [comment]
That worked. It installed

trying URL 'http://dmlc.ml/drat/src/contrib/xgboost_0.4-2.tar.gz'

Thanks for the speedy replies!
