### ISSUE TITLE
Slow/Unconsistent inplace prediction latencies using Xgboost Python Package

### ISSUE THREAD

**Issue by mhv777** [dmlc/xgboost#7734]
Xgboost: 1.5.2
Numpy: 1.21.5

Hello, I ran into a surprising issue when benchmarking prediction performance using the inplace_predict method.
When iterating and calling the inlace_predict method over and over, latencies spanned from a 3-4 milliseconds to more than 90ms. (This happened for the same input on all predictions)

I have a saved model in json format, and my data consists of really sparse vectors. My aim is to score a single vector in the fastest way possible, without resorting to onnx/etc.

Example below

```
import time
import numpy as np
import xgboost as xgb

bst = xgb.Booster()
bst.load_model("xgb.json")
times = []
indexes = [8, 131, 144, 149, 178, 183, 1136, 1922, 1924]
vec = np.zeros(8880, order="C")
vec[:] = np.nan
for index in indexes:
    vec[index] = 1
data = np.array([vec])
for i in range(5):
    st = time.time()
    pred = bst.inplace_predict(data)
    en = time.time()
    times.append(en - st)

print("Average time to predict", sum(times) / len(times))
print("Time for first pred", times[0])
print("Time for second pred", times[1])
print("Time for third pred", times[2])

-- Results --
Average time to predict 0.034766340255737306
Time for first pred 0.0038080215454101562
Time for second pred 0.0037903785705566406
Time for third pred 0.0651845932006836
```

What surprised me the most was that the issue seems to be solved by adding a ``time.sleep(1)`` before calling the inplace_predict again.

I'd appreciate any guidance as to why this happens, or if there's anything I'm doing wrong. Thanks

**Comment by trivialfis** [comment]
I can't be entirely sure, for a single sample prediction, the time is likely to be dominated by memory and thread allocation, which means the time is being spent in the language runtime or the OS kernel.  We will have to run time profiling to debug this.

**Comment by trivialfis** [comment]
I'm not familiar with the internal of jupyter.

**Comment by mhv777** [comment]
Just in case anyone stumbles upon this, the issue was that the ``inplace_predict`` method was using all available threads by default. In my local Mac this worked fine but when running inside an EC2 instance my guess is thread allocation (or something of the sort) took too much time compared to the actual prediction.

This was solved by setting ``bst.set_param({'nthread': 1})``
