### ISSUE TITLE
R package does not install when the OpenMP library is in a non-standard place

### ISSUE THREAD

**Issue by cmarquardt** [dmlc/xgboost#7757]
Hello,

I'm trying to install XGBoost from the current CRAN package version (1.5.2.1) on MacOS Catalina 10.15.7 with a Hombrew-installed libomp. 

The installation fails in my case because my Homebrew installation - and thus libomp - is in a non-standard place (`/opt/brew` rather than `/usr/local`). The reason for the failure is that the `configure.ac` of the R package does not make use  of existing variables such as `CPPFLAGS` or `LDFLAGS` when testing if  it is supported. However,  the R build environment provides those; using them in `configure.ac` for compiling the test program works fine and solves the problem in my case.

I believe this might also be an issue on Macs with an ARM processor; as far as I know, Homebrew installs itself in `/opt/homebrew` in that case, and the XGBoost installation should fail in a similar way.
  
Is there any reason why these R-provided environment variables are not used in the `configure.ac`? If not, do you accept a pull request?

Many thanks,

   Christian.

**Comment by hcho3** [comment]
Yes, feel free to submit a pull request.
