### ISSUE TITLE
xgboost_R.cc:2:26: fatal error: dmlc/logging.h: No such file or directory

### ISSUE THREAD

**Issue by flyingdisc** [dmlc/xgboost#776]
Latest commit 25 January 2016, R, 
devtools::install_git('git://github.com/dmlc/xgboost', subdir='R-package') 

There is no /dmlc folder in the /include folder. 
In the xgboost_R.cc, 
#include &lt;dmlc/logging.h&gt;
#include &lt;dmlc/omp.h&gt;

Am I missing something? 
Thanks a lot.

**Comment by thirdwing** [comment]
`devtools` doesn't support the submodule in github.

So if you really need the latest version, please clone the repo to your computer and build it.

For weekly updated version, please try the following code.

```r
install.packages("drat", repos="https://cran.rstudio.com")
drat:::addRepo("dmlc")
install.packages("xgboost", repos="http://dmlc.ml/drat/", type="source")
```

**Comment by flyingdisc** [comment]
@thirdwing, thank you.

**Comment by davidfjr3** [comment]
@thirdwing  I'he the same issue.. but your solution does not work in my case.. take a look, please:


> devtools::install_git('git://github.com/dmlc/xgboost', subdir='R-package')
Downloading git repo git://github.com/dmlc/xgboost
Installing xgboost
"C:/Users/djunior/Documents/R/R-3.2.3/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/djunior/AppData/Local/Temp/Rtmp0mIt87/file192c314d417b/R-package" --library="C:/Users/djunior/Documents/R/R-3.2.3/library" --install-tests 

* installing *source* package 'xgboost' ...
** libs

*** arch - i386
cp -r ../../src .
cp -r ../../rabit .
cp -r ../../dmlc-core .
cp -r ../../include .
cp -r ../../amalgamation .
g++ -m32 -std=c++0x -I"C:/Users/djunior/DOCUME~1/R/R-32~1.3/include" -DNDEBUG -I.//include -I.//dmlc-core/include -I.//rabit/include -I./ -DXGBOOST_STRICT_R_MODE=1 -DDMLC_LOG_BEFORE_THROW=0 -DDMLC_ENABLE_STD_THREAD=0 -DDMLC_DISABLE_STDIN=1 -DDMLC_LOG_CUSTOMIZE=1 -DXGBOOST_CUSTOMIZE_LOGGER=1 -DRABIT_CUSTOMIZE_MSG_ -DRABIT_STRICT_CXX98_    -I"d:/RCompile/r-compiling/local/local323/include"  -fopenmp -pthread   -O2 -Wall  -mtune=core2 -c xgboost_R.cc -o xgboost_R.o
xgboost_R.cc:2:26: fatal error: dmlc/logging.h: No such file or directory
compilation terminated.
make: *** [xgboost_R.o] Error 1
Warning: running command 'make -f "Makevars.win" -f "C:/Users/djunior/DOCUME~1/R/R-32~1.3/etc/i386/Makeconf" -f "C:/Users/djunior/DOCUME~1/R/R-32~1.3/share/make/winshlib.mk" CXX='$(CXX1X) $(CXX1XSTD)' CXXFLAGS='$(CXX1XFLAGS)' CXXPICFLAGS='$(CXX1XPICFLAGS)' SHLIB_LDFLAGS='$(SHLIB_CXX1XLDFLAGS)' SHLIB_LD='$(SHLIB_CXX1XLD)' SHLIB="xgboost.dll" ' had status 2
ERROR: compilation failed for package 'xgboost'
* removing 'C:/Users/djunior/Documents/R/R-3.2.3/library/xgboost'
Error: Command failed (1)
> 
> 
> install.packages("drat", repos="https://cran.rstudio.com")
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/drat_0.1.0.zip'
Content type 'application/zip' length 70295 bytes (68 KB)
downloaded 68 KB

package ‘drat’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\djunior\AppData\Local\Temp\Rtmp0mIt87\downloaded_packages
> drat:::addRepo("dmlc")
> install.packages("xgboost", repos="http://dmlc.ml/drat/", type="source")
trying URL 'http://dmlc.ml/drat/src/contrib/xgboost_0.4-4.tar.gz'
Content type 'application/octet-stream' length 384404 bytes (375 KB)
downloaded 375 KB

* installing *source* package 'xgboost' ...
** libs

*** arch - i386
Warning: running command 'make -f "Makevars.win" -f "C:/Users/djunior/DOCUME~1/R/R-32~1.3/etc/i386/Makeconf" -f "C:/Users/djunior/DOCUME~1/R/R-32~1.3/share/make/winshlib.mk" CXX='$(CXX1X) $(CXX1XSTD)' CXXFLAGS='$(CXX1XFLAGS)' CXXPICFLAGS='$(CXX1XPICFLAGS)' SHLIB_LDFLAGS='$(SHLIB_CXX1XLDFLAGS)' SHLIB_LD='$(SHLIB_CXX1XLD)' SHLIB="xgboost.dll" ' had status 127
ERROR: compilation failed for package 'xgboost'
* removing 'C:/Users/djunior/Documents/R/R-3.2.3/library/xgboost'

The downloaded source packages are in
        ‘C:\Users\djunior\AppData\Local\Temp\Rtmp0mIt87\downloaded_packages’
Warning messages:
1: running command '"C:/Users/djunior/Documents/R/R-3.2.3/bin/x64/R" CMD INSTALL -l "C:\Users\djunior\Documents\R\R-3.2.3\library" C:\Users\djunior\AppData\Local\Temp\Rtmp0mIt87/downloaded_packages/xgboost_0.4-4.tar.gz' had status 1 
2: In install.packages("xgboost", repos = "http://dmlc.ml/drat/", type = "source") :
  installation of package ‘xgboost’ had non-zero exit status

**Comment by khotilov** [comment]
Try to reinstall Rtools and make sure to set up its environment variables during the installation.

**Comment by emmating** [comment]
@davidfjr3 I have the same problem as yours, how do you fix the problem?

**Comment by davidfjr3** [comment]
Windows soluction

	
	1) Download and install cygwin shell
		 https://cygwin.com/install.html
		
		 
	2) So here's what I did to finish a 64-bit build on Windows:			
			2.1) Download and install MinGW-64: http://sourceforge.net/projects/mingw-w64/
								
			2.2) On the first screen of the install prompt make sure you set the Architecture to x86_64 and the Threads to win32
			2.3) I installed to C:/mingw64 (to avoid spaces in the file path) so I added this to my PATH environment variable: C:/mingw64/mingw64/bin
			2.4) I also noticed that the make utility that is included in bin/mingw64 is called mingw32-make so to simplify things I just renamed this to make
			2.5) Open a Windows command prompt and type gcc. You should see something like "fatal error: no input file"
			2.6) Next type make. You should see something like "No targets specified and no makefile found"
			2.7) Type git. If you don't have git, install it and add it to your PATH.
			   install git: https://git-scm.com/download/win
	
		source (python version): http://stackoverflow.com/questions/33749735/how-to-install-xgboost-package-in-python-windows-platform/35119904#35119904
		 
		 
	3) on cygwin shell:
	
		3.1 cd C:/Users/user/Desktop/package
		3.2 git clone --recursive https://github.com/dmlc/xgboost
		3.3 cd xgboost
		3.4 git submodule init
		3.5 git submodule update
		3.6 cd dmlc-core
		3.7 make -j4
		
			if you get a error in the step 3.7 like:
			
			Makefile:83: recipe for target 'data.o' failed
			make: *** [data.o] Error 1
			
			skip to the step 4
		
		3.8 cd ../rabit
		3.9 make lib/librabit_empty.a -j4
		3.10 cd ..	
		3.11 cp make/mingw64.mk config.mk
		3.12 make -j4			
		
		source: http://xgboost.readthedocs.io/en/latest/build.html#r-package-installation
		



	4) if step 3 was successful (no errors) skip to the step 5
	   else, delete the folder 'xgboost' of the step 3 and on cygwin shell do:
		
		4.1 cd C:/Users/user/Desktop/package
		4.2 git clone --recursive https://github.com/dmlc/xgboost
		4.3 cd xgboost

		(New) 4.3.1: git checkout 9a48a40				
		(New) 4.3.2: git checkout -b 9a48a40		
		( source: https://github.com/dmlc/xgboost/issues/1267 )
		
		4.4 git submodule init
		4.5 git submodule update
		4.6 cd dmlc-core
		4.7 make -j4
		
			Remark: The same error msg is showed, however go to the step 4.8 end run each until 4.12 and finish the step 4.
				    In my case, after run the step 4 the step 5 works fine.
		
		4.8 cd ../rabit
		4.9 make lib/librabit_empty.a -j4
		4.10 cd ..	
		4.11 cp make/mingw64.mk config.mk
		4.12 make -j4			
		
		
	Obs: This guy gives another soluction that I don't try because the step 4 works for me.
		https://www.kaggle.com/c/grupo-bimbo-inventory-demand/forums/t/22662/xgboost-and-windows-10/130070
		
		
		
	5) In R console
		library(devtools)
		setwd('C:/Users/user/Desktop/package/xgboost')
		install('R-package')
		library(xgboost)
				
		source: http://xgboost.readthedocs.io/en/latest/build.html#r-package-installation

**Comment by davidfjr3** [comment]
@emmating 

	Windows soluction

	
	1) Download and install cygwin shell
		 https://cygwin.com/install.html
		
		 
	2) So here's what I did to finish a 64-bit build on Windows:			
			2.1) Download and install MinGW-64: http://sourceforge.net/projects/mingw-w64/
								
			2.2) On the first screen of the install prompt make sure you set the Architecture to x86_64 and the Threads to win32
			2.3) I installed to C:/mingw64 (to avoid spaces in the file path) so I added this to my PATH environment variable: C:/mingw64/mingw64/bin
			2.4) I also noticed that the make utility that is included in bin/mingw64 is called mingw32-make so to simplify things I just renamed this to make
			2.5) Open a Windows command prompt and type gcc. You should see something like "fatal error: no input file"
			2.6) Next type make. You should see something like "No targets specified and no makefile found"
			2.7) Type git. If you don't have git, install it and add it to your PATH.
			   install git: https://git-scm.com/download/win
	
		source (python version): http://stackoverflow.com/questions/33749735/how-to-install-xgboost-package-in-python-windows-platform/35119904#35119904
		 
		 
	3) on cygwin shell:
	
		3.1 cd C:/Users/user/Desktop/package
		3.2 git clone --recursive https://github.com/dmlc/xgboost
		3.3 cd xgboost
		3.4 git submodule init
		3.5 git submodule update
		3.6 cd dmlc-core
		3.7 make -j4
		
			if you get a error in the step 3.7 like:
			
			Makefile:83: recipe for target 'data.o' failed
			make: *** [data.o] Error 1
			
			skip to the step 4
		
		3.8 cd ../rabit
		3.9 make lib/librabit_empty.a -j4
		3.10 cd ..	
		3.11 cp make/mingw64.mk config.mk
		3.12 make -j4			
		
		source: http://xgboost.readthedocs.io/en/latest/build.html#r-package-installation
		



	4) if step 3 was successful (no errors) skip to the step 5
	   else, delete the folder 'xgboost' of the step 3 and on cygwin shell do:
		
		4.1 cd C:/Users/user/Desktop/package
		4.2 git clone --recursive https://github.com/dmlc/xgboost
		4.3 cd xgboost

		(New) 4.3.1: git checkout 9a48a40				
		(New) 4.3.2: git checkout -b 9a48a40		
		( source: https://github.com/dmlc/xgboost/issues/1267 )
		
		4.4 git submodule init
		4.5 git submodule update
		4.6 cd dmlc-core
		4.7 make -j4
		
			Remark: The same error msg is showed, however go to the step 4.8 end run each until 4.12 and finish the step 4.
				    In my case, after run the step 4 the step 5 works fine.
		
		4.8 cd ../rabit
		4.9 make lib/librabit_empty.a -j4
		4.10 cd ..	
		4.11 cp make/mingw64.mk config.mk
		4.12 make -j4			
		
		
	Obs: This guy gives another soluction that I don't try because the step 4 works for me.
		https://www.kaggle.com/c/grupo-bimbo-inventory-demand/forums/t/22662/xgboost-and-windows-10/130070
		
		
		
	5) In R console
		library(devtools)
		setwd('C:/Users/user/Desktop/package/xgboost')
		install('R-package')
		library(xgboost)
				
		source: http://xgboost.readthedocs.io/en/latest/build.html#r-package-installation
