### ISSUE TITLE
Build issue: fatal error: cub/cub.cuh: No such file or directory

### ISSUE THREAD

**Issue by lfdmn** [dmlc/xgboost#7762]
Hi,

Does cub need to be built prior to xgboost?

I'm following the build [from source instructions](https://xgboost.readthedocs.io/en/latest/build.html)
```bash
git clone --recursive https://github.com/dmlc/xgboost
cd xgboost
mkdir build && cd build
CC=/usr/bin/gcc-8 CXX=/usr/bin/g++-8 cmake .. -DUSE_CUDA=ON -DBUILD_WITH_CUDA_CUB=ON

...
fatal error: cub/cub.cuh: No such file or directory
 #include <cub/cub.cuh>
          ^~~~~~~~~~~~~
```
Thanks,
-Damien

**Comment by trivialfis** [comment]
Hi, which CUDA version are you using?

**Comment by trivialfis** [comment]
Please consider using the latest CUDA.  cub is not integrated into CUDA 10.x.
