### ISSUE TITLE
Distributed learning issue on Databricks cluster

### ISSUE THREAD

**Issue by ChrisB831** [dmlc/xgboost#7787]
Hi All,

Apologies if this is the wrong place to flag this issue, please remove if so. I am having trouble distributing XGboost training on a Databricks cluster.

I have attached the Databricks notebook (exported as html) that details the problem but essentially….
[XGBoost distribution issue vGithub.zip](https://github.com/dmlc/xgboost/files/8427738/XGBoost.distribution.issue.vGithub.zip)
[XGBoost distribution issue vGithub.zip](https://github.com/dmlc/xgboost/files/8427740/XGBoost.distribution.issue.vGithub.zip)

1. I took the dummy dataset and code that Databricks use to demo an XGBoost regressor (https://docs.databricks.com/applications/machine-learning/train-model/xgboost.html)
2. I cut out ALL but two features month and hour
3. I converted to one hot and vectorised, then built a model to predict a continuous label
4. The undistributed model trained on a single node, gave different predictions for different input features sets. The distributed model trained on 2 nodes, gave the same predicted value for different input features. 

Clearly this isn’t working as expected but I’m not sure if the issues lies with my deployment, XGBoost or the Databricks implementation of XGBoost.

Has anyone else experienced this ?

Cheers
Chris

**Comment by wbo4958** [comment]
AFAIK, the Databricks xgboost pyspark solution is based on XGBoost python packages. Maybe @trivialfis can help on that.

BTW, at the same time, could you set the num_round = 100 to see?

**Comment by trivialfis** [comment]
That package is not open sourced and I'm not sure how to reproduce the error on my local machine.

**Comment by ChrisB831** [comment]
wbo4958
Just tried the runs with num_rounds set to 100 and still get the same issues unfortunately!

**Comment by wbo4958** [comment]
@ChrisB831, please file an issue for databricks

**Comment by ChrisB831** [comment]
wbo4958. I have done.
The response I get is "I got feedback from Engineering that this has nothing to do with distributing XGBoost and has to do with encoding on customer's data set. This needs to be addressed by ML-SME who can go over the theory and usage of this package."

Which seems a bit strange considering that all I am doing is encoding two nominal fields into one-hot encodings, pretty standard stuff. Also it works when I don't distribute but doesn't when I do????

**Comment by trivialfis** [comment]
I don't think we can resolve this issue without having access to the code. @wbo4958 is working on the pyspark interface, will close related issues until the support is in place.
