### ISSUE TITLE
git clone the latest version but not v0.47

### ISSUE THREAD

**Issue by yilaguan** [dmlc/xgboost#779]
when I try to use this package using git clone command lines in ubuntu, but find the version is v0.4 rather than v0.47. Can you please answer this questions?

**Comment by berzjackson** [comment]
It seems they simply forgot to update the version number during the last release.
I suggest adding a script that can keep the version numbers from different corners of the project in sync. A reasonable candidate would be https://github.com/peritus/bumpversion.

**Comment by berzjackson** [comment]
Just realized that the git tag is incorrect as well. Should be v0.47 instead of 0.47. These are minor issues, but can be confusing when someone expects everything is in consistency.

**Comment by tqchen** [comment]
Sounds a  valid suggestion, we will switch to the versioning without the v in next release, thanks
