### ISSUE TITLE
How to get regression coefficients from XGB regression model?

### ISSUE THREAD

**Issue by prashanthin** [dmlc/xgboost#7799]
Hi team,

I am curious to know how/whether we can get regression coefficients values and intercept from XGB regressor model? Or how to interpret relative effect in regression model variables to target like coefficients in linear regression? 

Thanks,
Prashant

**Comment by trivialfis** [comment]
If you are using gblinear with Python, feel free to look into `XGBRegressor.intercept_` and `coef_` properties. Also `gblinear` supports feature importance.  Hope that helps.
