### ISSUE TITLE
Issue in installing xgboost on mac using Canopy

### ISSUE THREAD

**Issue by juvleo** [dmlc/xgboost#780]
I am using Canopy (Version 1.5.5 64bit) on a Mac.  Trying to get xgboost to work but keep having these errors.  I followed the steps at https://github.com/dmlc/xgboost/blob/master/doc/build.md
Specifically, 
1. I opened Terminal, typed: git clone --recursive https://github.com/dmlc/xgboost
cd xgboost; cp make/minimum.mk ./config.mk; make -j4
2. In Terminal, I typed: cd python-package; sudo python setup.py install
I did not see any obvious errors in this process (attached), only some warnings.

But when I run "import xgboost as xgb" in Canopy, the following occur:
import xgboost as xgb

ImportError                               Traceback (most recent call last)
<ipython-input-118-745aa3a2d734> in <module>()
----> 1 import xgboost as xgb

/Users/Shang/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/xgboost/__init__.py in <module>()
     11 from .core import DMatrix, Booster
     12 from .training import train, cv
---> 13 from .sklearn import XGBModel, XGBClassifier, XGBRegressor
     14 from .plotting import plot_importance, plot_tree, to_graphviz
     15 

/Users/Shang/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/xgboost/sklearn.py in <module>()
      8 from .training import train
      9 
---> 10 from .compat import (SKLEARN_INSTALLED, XGBModelBase,
     11                      XGBClassifierBase, XGBRegressorBase, LabelEncoder)
     12 

ImportError: cannot import name LabelEncoder 

Any help would be appreciated. I can provide more details.
Thank you.

Attached is the installation process in Terminal.
[xgboost_install.txt](https://github.com/dmlc/xgboost/files/102893/xgboost_install.txt)

**Comment by phunterlau** [comment]
install scikit-learn firstly

**Comment by juvleo** [comment]
I did already install scikit-learn, but thanks it is working now.
The solution was that I needed to restart Canopy...
