### ISSUE TITLE
Different prediction results between Java and Python xgboost libraries

### ISSUE THREAD

**Issue by patmira** [dmlc/xgboost#7805]
I am trying to use xgboost4j library to predict same results as that of Python library.
Java library: `xgboost4j`
Python library: `XGBoost: 1.5.2`

I have an xgboost model (json file), following are the ways I am trying to use xgboost library to predict the results:

Python:
```
tmp_matrix = [[0.216456419, 0.831728468, 0.0, 0.0, 2.423917378, 0.0, 0.0, 667.0, 1092.0],
            [0.205964113, 0.514636123, 4.4, 5.043425117, 0.0, 2.88713876, 0.4, 942.0, 820.0],
            [0.256054706, 0.699235358, 4.8, 1.945910149, 0.0, 0.0, 0.0, 767.0, 1051.0]]
tmp_df = pd.DataFrame(data=tmp_matrix, columns=ranking_features_v2)
tmp_df_predictions = model2.predict(tmp_df)
```
Outcome: `[1.6198376, 2.4502726, 1.6700827]`

Java
```
float[][] data = new float[][]{
        { 0.216456419f, 0.831728468f, 0f, 0f, 2.423917378f, 0f, 0f, 667f, 1092f },
        { 0.205964113f, 0.514636123f, 4.4f, 5.043425117f, 0f, 2.88713876f, 0.4f, 942f, 820f },
        { 0.256054706f, 0.699235358f, 4.8f, 1.945910149f, 0f, 0f, 0f, 767f, 1051f }
};
DMatrix dmat = new DMatrix(flatten(data), 3, 9);
Booster booster = XGBoost.loadModel("xgboost_model.json");
float[][] output2 = booster.predict(dmat);
System.out.println(Arrays.toString(flatten(output2)));
```
Outcome: `[0.35003328, 2.3232524, 0.8820881]`

Can someone please help address this issue?   
Example files to reproduce the issue will be provided upon request.

**Comment by hcho3** [comment]
Please specify the `missing` argument when constructing the DMatrix, as follows:
```java
DMatrix dmat = new DMatrix(flatten(data), 3, 9, Float.NaN);
```
See the [documentation](https://xgboost.readthedocs.io/en/latest/jvm/javadocs/ml/dmlc/xgboost4j/java/DMatrix.html#DMatrix-float:A-int-int-float-).

**Comment by patmira** [comment]
> Please specify the `missing` argument when constructing the DMatrix, as follows:
> 
> ```java
> DMatrix dmat = new DMatrix(flatten(data), 3, 9, Float.NaN);
> ```
> 
> The `missing` value must be set to NaN so that the Java package produces the same result as the Python package.

Thanks, that worked.
