### ISSUE TITLE
ValueError: The label must consist of integer labels of form 0, 1, 2, ..., [num_class - 1].

### ISSUE THREAD

**Issue by NikithaVenkat** [dmlc/xgboost#7809]
raise ValueError(label_encoding_check_error)
ValueError: The label must consist of integer labels of form 0, 1, 2, ..., [num_class - 1].

My target variables contain 0 and 1. I am using an ensemble model, so my other target variable contains nulls as well along with 0 and 1. Is that causing the problem?

I have already used use_label_encoder=False, Could you kindly let me know if you know any other solution?

Sample code:
xgb1 = xgboost.XGBClassifier(n_estimators=50, max_depth=5, use_label_encoder=False, eval_metric='logloss')

fit function
 def fit(self, X, y):

        all_feature_columns = set()
        self.feature_sets = []

        for model_detail in self.model_details:
            model = model_detail['model']

            # Keep a record of all the features used in all the models
            feature_columns = model._feature_columns(X)
            self.feature_sets.append(feature_columns)
            all_feature_columns.update(feature_columns)

            print(f'\tTraining model {self.model_details.index(model_detail)}')

            # Ensemble models expect a dataframe of y values since each model could have a different target column
            try:
                this_y = y[model.response_column]
            except ValueError:
                raise ValueError("Ensemble models must have a dataframe passed in for y "
                                 "with a response column for each model")

            model.fit(X, this_y)

        # Make sure this set is sorted so it is always in the same order
        self.feature_columns = sorted(list(all_feature_columns))

        return self

**Comment by trivialfis** [comment]
> target variable contains nulls as well along with 0 and 1. Is that causing the problem?

Might be.  sklearn still validates the input values.  Also, XGBoost doesn't support sparse labels so even if you can get around the sklearn error, there will be a XGBoost error afterward.

**Comment by trivialfis** [comment]
Feel free to reopen if there's a more specific feature request.
