### ISSUE TITLE
Could we make monotone_constraints applicable to gblinear?

### ISSUE THREAD

**Issue by flippercy** [dmlc/xgboost#7814]
Hi @hcho3 , @terrytangyuan:

Is it possible to make monotone_constraint applicable to gblinear so the direction of every variable in the final linear model can be controlled? It is a common requirement from regulators.

Thank you!

**Comment by hcho3** [comment]
Marking this as a feature request. Enabling monotone constraints for gblinear will involve significant amount of engineering effort.

**Comment by flippercy** [comment]
Thank you @hcho3. We observed that in high dimension space, the model returned by gblinear sometimes performed better than glmnet. Not sure of the reasons for it.

In highly regulated industries, people still prefer linear models with coefficients under complete control. So I will be very grateful if this feature can be added in the future.

**Comment by trivialfis** [comment]
The feature request is duplicated to https://github.com/dmlc/xgboost/issues/6545 . Let's focus the discussion in one issue.
