### ISSUE TITLE
Unusual state of dask workers and tasks when using  `DaskXGBRegressor.predict`

### ISSUE THREAD

**Issue by gcaria** [dmlc/xgboost#7818]
```python
import dask.dataframe as dkf
import pandas as pd
import numpy as np
import xgboost as xgb

x = dkf.from_pandas(pd.DataFrame(np.random.rand(10,50), columns=[str(i) for i in range(50)]), npartitions=1)
y = dkf.from_pandas(pd.DataFrame(np.random.rand(10), columns=['y']), npartitions=1)

model = xgb.dask.DaskXGBRegressor()
model.fit(x, y)  
model.predict(x).compute()
```

Running this MRE I see in the dask dashboard that the single `Booster` task is still present, and that the workers' memory is still occupied after the cell has finished the computation (that is, I can run other cells in the notebook I'm using).
It is hard to see the workers memory consumption for such a small dataframe, but this is clearer using a much larger one.

Something else that I find unusual, is that even though only one task is displayed in the dashboard, several workers are used for the computations. Does this mean there are nested `compute` calls going on?

![Screen Shot 2022-04-19 at 10 50 03 am](https://user-images.githubusercontent.com/44147817/163969026-90b622fc-f054-4279-95a4-ff195c1b4279.png)

**Comment by trivialfis** [comment]
Could you please share the version of xgboost/dask you are using?  Also, could you please try the latest xgboost (1.6)?

**Comment by gcaria** [comment]
I have just run the MRE with updated `dask` (2022.04.1) and `xgboost` (1.6) and I can see the same problem.

**Comment by SultanOrazbayev** [comment]
Hmm, I tried it with these versions:

```python
import dask; print(dask.__version__) #2022.01.0
import xgboost; print(xgboost.__version__) #1.6.1
```

And not sure I can reproduce the error (dashboard seems clear):

```python
from distributed import Client
client = Client()

import dask.dataframe as dkf
import pandas as pd
import numpy as np
import xgboost as xgb

x = dkf.from_pandas(pd.DataFrame(np.random.rand(10,50), columns=[str(i) for i in range(50)]), npartitions=1)
y = dkf.from_pandas(pd.DataFrame(np.random.rand(10), columns=['y']), npartitions=1)

model = xgb.dask.DaskXGBRegressor()
model.fit(x, y)  
model.predict(x).compute()
```

**Comment by trivialfis** [comment]
I can't reproduce that either. Considering the script is not guarded by `if __name__ == "__main__":` nor there's any call to construct a client object, can I assume it's a snippet from a jupyter notebook? If so then the task might be some stalled states in the notebook environment. Consider restarting the environment/workers.

Feel free to reopen if the issue persists.
