### ISSUE TITLE
about the input data of xgboost model

### ISSUE THREAD

**Issue by luoruisichuan** [dmlc/xgboost#782]
Mr. Chen,
     I use xgboost train the model, the command is 
bst <- xgboost(data = x, label = y, max.depth = 2, eta = 1, nround = 10, objective = "binary:logistic")

the x is a matrix, and head(x) is
 BBBFCALLING     BBBFCALLED        BBFCALLING      BBFCALLED       BFCALLING
  "  34"                      "  26"                        "  62"                    "  43"                   "  46"   
  " 223"                     " 290"                        " 326"                  " 243"                 " 430"   
 " 108"                      " 254"                        " 111"                   " 117"                "  89"   
 "  71"                       "  80"                         "  37"                    "  86"                  "  72"   
 " 297"                      " 535"                        " 274"                     " 462"                " 340"   
  "  23"                      "  33"                           "  21"                       "   8"                  "  43"  
the y is also a matrix , and head(y) is
 [,1]
  "1" 
 "1" 
 "1" 
 "0" 
 "1" 
  "1" 

but when I execute the command ,then the error imformation  happern, as this
"Error in xgb.DMatrix(data, label = label) : can not open file "  34"  "
 what is the problem ?  and what are the requrements of the imput data ?

thanks for your help very much!

**Comment by pommedeterresautee** [comment]
Is it a Matrix of numeric? Or character?
You need to provide a matrix of numeric type.

Kind regards,
Michaël
