### ISSUE TITLE
How to col-sampling with weight？

### ISSUE THREAD

**Issue by hihaluemen** [dmlc/xgboost#7825]
Now I have a requirement to weight the features of the input data. But i don't know how to col-sampling with weight？
For example, I have a input data like this
X_data = array([[0.18367105, 0.16241563, 0.20352988, 0.90231236],
                        [0.06338786, 0.50989827, 0.06611807, 0.39955355],
                        [0.15928815, 0.14450292, 0.9441908 , 0.34934211]]);

and a feature weight, 
weight = [0.1, 0.5, 0.2, 0.4];

the label is 
label = [0, 1, 0];

dtrain = xgb.DMatrix(X_data, label)

How to col-sampling with weight？

**Comment by hcho3** [comment]
Take a look at https://github.com/dmlc/xgboost/blob/master/demo/guide-python/feature_weights.py. You should pass `feature_weights` when building the DMatrix.
