### ISSUE TITLE
Can I retreive the AUC from the xgboost train object

### ISSUE THREAD

**Issue by myloginid** [dmlc/xgboost#783]
Hi,

This is more of a question and not a bug and maybe a feature request.

xgboost prints the train and valid auc's / rmse's etc on the screen. Can we have a way to retrieve the auc or rmse from the train object? Currently  the print/summary dosent have this. Also the object has only raw data and the call. It does not have the metrics. Can you pls add this feature.

clf = xgb.train(  
    data                = dtrain, 
    nround              =300, 
    nthread             = 5, 
    objective           = "binary:logistic", 
    booster             = "gbtree",
    eval_metric         = "auc",
    max_depth           = 10, #changed from default of 8
    eta                 = peta,
    colsample_bytree    = pcolsample_bytree,
    subsample           = psubsample,
    min_child_weight    = pmin_child_weight,
    verbose             = 1,  #1
    early.stop.round    = 150
)

Thanks,
Manish

**Comment by terrytangyuan** [comment]
You can put the things you want to retrieve in `watchlist`. We currently have `evals_result` but somehow forgot to return it. Not sure about the best way to do it yet in order to be backward compatible. Feel free to submit a PR or work on a forked copy to get those info just to achieve your own purposes up quickly.

**Comment by myloginid** [comment]
Thanks for taking this as a feature request. 
Note -  I am using R and not Python. In R also this feature is not available.

**Comment by terrytangyuan** [comment]
Okay I see. If it's Python, you can actually use the sklearn wrapper and there's a function `eval_result` you can use to get those values. https://github.com/dmlc/xgboost/blob/master/python-package/xgboost/sklearn.py#L381
