### ISSUE TITLE
New CRAN submission with bugs fixed

### ISSUE THREAD

**Issue by hetong007** [dmlc/xgboost#784]
I received an email from Prof. Ripley saying

> This concerns packages
> 
> Bmix EMCC MCMCglmm MVR TraMineR depmix depmixS4 geepack lcd lm.br
> nadiv rbamtools rmetasim xgboost
> 
> The manual says
> 
>   Most R header files can be included within C++ programs, and they
>   should *not* be included within an extern "C" block (as they include
>   C++ system headers).
> 
> yet you seem to have done so (in some cases via indirect inclusion of headers).  This is causing installation failures with some recent C++ compilers (and in some cases that was reported previously).
> 
> Note too that it is bad practice to include C headers such as <math.h> in C++ code: you should always use the C++ equivalent such as <cmath>.
> 
> Please correct ASAP.

I suggest that we make a new submission with it fixed and all the new improvements to CRAN.

**Comment by tqchen** [comment]
Let us do a quick fix on the previous CRAN packages, to remove the extern C blocks in the xgboost_R.h

The current version of xgboost need more work to be carefully tested before submit to CRAN due to compatiblity of c++11 compilers

**Comment by terrytangyuan** [comment]
BTW, have you increased the version number for R package before submitting it? It's hard for users to tell whether the version they installed is most up-to-date.
