### ISSUE TITLE
Sklearn API + GridSearchCV: PerformanceWarning: DataFrame is highly fragmented

### ISSUE THREAD

**Issue by edikedik** [dmlc/xgboost#7842]
Greetings,

I'm using a `GridSearchCV` with `XGBClassifier`, passing a `DataFrame` with categorical data (dtype="category").

However, [this line](https://github.com/dmlc/xgboost/blob/bef1f939ceb964283f17f1f4cff3234ca18d3bc8/python-package/xgboost/data.py#L314), while replacing -1.0 values with `NaN`, triggers a `pd.PerformanceWarning: DataFrame is highly fragmented`. 

Since `GridSearchCV` runs in parallel, this causes quick IO overflow. I can't simply filter the warning out using python's built-in tools, supposedly for the same reason (assuming `_transform_pandas_df` is called for each new `XGBClassifier` instance).

Thus, I don't know any way to avoid the warning. I will be grateful for any ideas. Thanks!

**Comment by trivialfis** [comment]
Hi @edikedik , are you using categorical data or nullable type?

**Comment by trivialfis** [comment]
Maybe copying the dataframe and performing the operations inplace would be better?

**Comment by edikedik** [comment]
Hi @trivialfis,
Thanks for reaching out.

I have the categorical data types in my `DataFrame`.

I've failed to reproduce the problem with the code below. It **doesn't** trigger any warnings.

```python
import numpy as np
import pandas as pd
import xgboost as xgb
from sklearn.model_selection import GridSearchCV

grid = {
    'learning_rate': [0.05, 0.1, 0.5],
}

x = np.random.randint(0, 10, (100, 10))
y = np.random.randint(0, 1, 100)
x = pd.DataFrame(x).astype('category')
y = pd.DataFrame(y)

# Create one CV fold by indices
idx_in = np.random.randint(0, len(x), 10)
idx_out = np.setdiff1d(np.arange(len(x)), idx_in)

cls = xgb.XGBClassifier(enable_categorical=True, tree_method='approx')
cv = GridSearchCV(cls, grid, n_jobs=-1, refit=False, cv=[(idx_in, idx_out)])

cv.fit(x, y)
```

However, the main difference between the above and what I do is that my `x` goes through some preprocessing pipeline, and then I'm calling the `GridSearchCV` as `cv.fit(x.copy(), y.copy())`, which **does** trigger the warning. Again, I verified that all my variables are of the "category" type. Quite obscure!

**Comment by trivialfis** [comment]
XGB now copies the df as a whole, should be able to avoid the warning.  You can get nightly build after the CI finishes the job.

**Comment by nerubenstein** [comment]
I'm still having this error from L314 in data.py with xgboost version 1.6.1.

**Comment by johan-lorentzon** [comment]
Hi,

I'm also still having this issue when running xgboost 1.6.1, from data.py line 323.

`df_features` has dtypes `category` and `float`.

```
estimator = (
    xgb.XGBRegressor(
        objective='survival:cox',
        tree_method='hist',
        enable_categorical=True,
    )
)

estimator.fit(df_features, df_outcomes)
```
