### ISSUE TITLE
Reinstallation with `pip install xgboost==X` fails due to RAM shortage (?)

### ISSUE THREAD

**Issue by KWiecko** [dmlc/xgboost#7847]
For an AWS Linux micro instance (1GB RAM) the following commands will lead to "Killed" message and failure in pip install process

1. python3 -m venv test_venv
2. source test_venv/bin/activate
3. pip3 install xgboost==1.4.2  # This will install xgboost==1.4.2 successfully
4. pip3 install xgboost==1.5.2  # This will install xgboost==1.5.2 successfully
5. pip3 install xgboost==1.4.2  # This will not install xgboost==1.4.2 and will simply print "Killed" to console

The only way to work around this problem is to either use --no-cache-dir or call `pip3 cache purge` before last `pip3 install` call

Once an instance with more RAM is created (e.g. 2GB or RAM) this problem no longer occurs

**Comment by trivialfis** [comment]
I'm not sure how a xgboost developer can help here? That seems to be a pip memory usage issue.

**Comment by KWiecko** [comment]
I posted this as a sanity check / info - I spent few hours figuring that out and wanted to save others the misery.

**Comment by trivialfis** [comment]
Ah, got it.  Thank you for sharing!

**Comment by trivialfis** [comment]
Let's hope that others who search for the error will find this issue useful.
