### ISSUE TITLE
ml.dmlc.xgboost4j.java.NativeLibLoader initXGBoost. SEVERE: Failed to load xgboost4j library from jar for platform linux/aarch64. java.io.FileNotFoundException: File /lib/linux/aarch64/libxgboost4j.so was not found inside JAR.

### ISSUE THREAD

**Issue by TomasZhang19** [dmlc/xgboost#7869]
I used maven to compile and package a xgboost4j demo project to a JAR file on an ARM machine. When I run the JAR, I got the error message:
ml.dmlc.xgboost4j.java.NativeLibLoader initXGBoost. SEVERE: Failed to load xgboost4j library from jar for platform linux/aarch64. 
ml.dmlc.xgboost4j.java.DMatrix <clinit>. SEVERE: Failed to load native library
java.io.FileNotFoundException: File /lib/linux/aarch64/libxgboost4j.so was not found inside JAR.

How can I acquire or make a libxgboost4j.so file of aarch64?

**Comment by wbo4958** [comment]
can you check where libxgboost4j.so is in by

``` bash
jar tf xgboost.jar  | grep libxgboost4j
```

**Comment by TomasZhang19** [comment]
there is only a libxgboost4j.so in the path "/lib/linux/x86_64". But in the error message,  there should be a libxgboost4j.so in the path "/lib/linux/aarch64".

**Comment by wbo4958** [comment]
@hcho3,  https://github.com/dmlc/xgboost/issues/7869#issuecomment-1120665120 reminds me which arches are supported by xgboost official release? looks like we're only supporting x86 platform?

**Comment by wbo4958** [comment]
@TomasZhang19, if you compiled the xgboost locally on the Arm platform, it should be working.

**Comment by hcho3** [comment]
@wbo4958 That's right, we currently only support x86_64.

**Comment by TomasZhang19** [comment]
> @TomasZhang19, if you compiled the xgboost locally on the Arm platform, it should be working.

@wbo4958 
Thank you. In my xgboost4j demo project, I use the ml/dmlc/xgboost4j_2.12/xgboost4j_2.12-1.5.2.jar. Did you mean that I should compile the xgboost on the ARM platform and get a new xgboost4j_2.12-1.5.2.jar? if so, then what files do I need and how can I compile it?

**Comment by wbo4958** [comment]
@trivialfis, can xgboost be built in ARM platform

**Comment by trivialfis** [comment]
It can.  We have arm package for Python.

**Comment by TomasZhang19** [comment]
> It can. We have arm package for Python.

@trivialfis   How can I build xgboost4j_2.12-1.5.2.jar on ARM platform?

**Comment by hcho3** [comment]
@TomasZhang19 Take a look at https://xgboost.readthedocs.io/en/latest/build.html#building-jvm-packages

**Comment by TomasZhang19** [comment]
> @TomasZhang19 Take a look at https://xgboost.readthedocs.io/en/latest/build.html#building-jvm-packages

Thank you. It does work.
