### ISSUE TITLE
Is there a mistake in the Python Package Introduction?

### ISSUE THREAD

**Issue by SzeYeung1** [dmlc/xgboost#7878]
In the [Setting Parameters](https://xgboost.readthedocs.io/en/stable/python/python_intro.html#setting-parameters) section of the Python Package Introduction of XGBoost documentation, the code for specifing validations set to watch performance goes like this:

`evallist = [(dtest, 'eval'), (dtrain, 'train')]`

I followed this code and found early stopping rounds did not work, as it was targeting the train score rather than the eval score. It seems that the order should be reversed:

`evallist = [(dtrain, 'train'), (dtest, 'eval')]`

**Comment by hcho3** [comment]
Thanks for spotting the mistake! Would you like to submit a pull request?

**Comment by SzeYeung1** [comment]
Sure. Honoured to make a small contribution to XGBoost as my first ever pull request. The [pull request](https://github.com/dmlc/xgboost/pull/7905) has made.
