### ISSUE TITLE
size limits in xgb.DMatrix for Python

### ISSUE THREAD

**Issue by kevin-hilton** [dmlc/xgboost#7880]
I'm running into an error that I think is related to this issue that was fixed for the R implementation but not for Python:

https://github.com/dmlc/xgboost/issues/156

This is the error I'm getting:

`	File "/usr/local/lib/python3.8/site-packages/xgboost/core.py", line 1913, in predict
	_check_call(
	File "/usr/local/lib/python3.8/site-packages/xgboost/core.py", line 218, in _check_call
raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: [21:35:42] ../src/c_api/c_api_utils.h:119: Check failed: std::accumulate(shape.cbegin(), shape.cend(), 1, std::multiplies<>{}) == chunksize * rows (-1719635071 vs. 2575332225) :
Stack trace:
[bt] (0) /usr/local/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x9733d) [0x7f344024833d]
[bt] (1) /usr/local/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0xae21f) [0x7f344025f21f]
[bt] (2) /usr/local/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(XGBoosterPredictFromDMatrix+0x4a0) [0x7f344024bea0]
[bt] (3) /usr/lib/x86_64-linux-gnu/libffi.so.7(+0x6d1d) [0x7f35c167fd1d]
[bt] (4) /usr/lib/x86_64-linux-gnu/libffi.so.7(+0x6289) [0x7f35c167f289]
[bt] (5) /usr/local/lib/python3.8/lib-dynload/_ctypes.cpython-38-x86_64-linux-gnu.so(_ctypes_callproc+0x777) [0x7f35c1698f27]
[bt] (6) /usr/local/lib/python3.8/lib-dynload/_ctypes.cpython-38-x86_64-linux-gnu.so(+0x8fb4) [0x7f35c168dfb4]
[bt] (7) /usr/local/lib/libpython3.8.so.1.0(_PyObject_MakeTpCall+0x87) [0x7f35c27331b7]
[bt] (8) /usr/local/lib/libpython3.8.so.1.0(_PyEval_EvalFrameDefault+0x4ba0) [0x7f35c2794490]`

I get this error whenever I try to run on a DMatrix (dense) with more elements than about 2,147,483,647, which is the maximum value for a 32-bit signed integer.

Based on the issue I linked above, I believe that changing the data type for the indeces of the DMatrix to an int64 for the Python package would fix this issue as it did for the R package.

**Comment by trivialfis** [comment]
Thank you for raising the issue, will fix it.

**Comment by kevin-hilton** [comment]
Thanks for the quick response, this will really help unblock me!

**Comment by trivialfis** [comment]
You can get the nightly build once the tests on the master branch are finished.

**Comment by kevin-hilton** [comment]
Thank you! Any idea when the release will be with this fix?

**Comment by trivialfis** [comment]
Unfortunately, it will probably take some time. We just make the 1.6.1 days before and this bug is quite rare.

**Comment by trivialfis** [comment]
This is what the nightly build for: https://xgboost.readthedocs.io/en/stable/install.html#id1 ;-)
