### ISSUE TITLE
Add grow_policy='lossguide' with tree_method='exact'

### ISSUE THREAD

**Issue by yonil7** [dmlc/xgboost#7883]
Add ability to use `grow_policy='lossguide'` with `tree_method='exact'` (currently supported only if tree_method is set to hist, approx or gpu_hist)

BTW, currently this params combination works without error but `max_leaves` param is ignored (`max_depth` is used instead)

**Comment by hcho3** [comment]
Apologies, we do not plan to add the lossguide policy to the exact method.
