### ISSUE TITLE
Setting AdaBoostClassifier's base_estimator=xgb.XGBClassifier will get error. How to solve it

### ISSUE THREAD

**Issue by matrixIszzl** [dmlc/xgboost#790]
**For example the code is following:**
clf = AdaBoostClassifier(
            n_estimators=20,
            # algorithm='SAMME.R',
            learning_rate=0.05,
            base_estimator=xgb.XGBClassifier(n_estimators=50, scale_pos_weight=0.1, max_depth=8,
                            objective='binary:logistic', learning_rate=0.02,
                            gamma=0.1, min_child_weight=3, reg_lambda=1000,
                            subsample=0.7, colsample_bytree=0.4))
clf.fit(X_train, y_train, sample_weight=None)

**I got the error : AttributeError: 'list' object has no attribute 'take'.**
**when I debugged, the postion of the error  :**
y_predict = self.classes_.take(np.argmax(y_predict_proba, axis=1),axis=0)  (*__boost_real in weight_boosting.py *_)
so I modified the code as : (because type(XGBClassifier.classes_) is list, and other classifiers in sklearn  such as ExtraTreesClassifier is ndarray):
y_predict = self.classes_.take(np.argmax(y_predict_proba, axis=1), axis=0)
to ==>
y_predict = np.array(self.classes_).take(np.argmax(y_predict_proba, axis=1), axis=0)

Now the code will run normally. But the problem occurs in **predict_proba function** (**sklearn.py**)
Note the def predict_proba(self, data, output_margin=False, **ntree_limit=0**)
I modified **the _boost_real in weight_boosting.py** again:
y_predict_proba = estimator.predict_proba(X)
to ==>
if estimator.**class**.**name** == 'XGBClassifier':
            y_predict_proba = estimator.predict_proba(X, ntree_limit=estimator.n_estimators)
        else:
            y_predict_proba = estimator.predict_proba(X)

But the problem occurs again (**all the item in y_predict_proba is always 0.5, it seems the XGBClassifier doesn't work!**)

So is there an elegant solution? Please help

**Comment by pommedeterresautee** [comment]
Old bug, no answer, closing
