### ISSUE TITLE
Load pretrain weight for XGBClassifier, "XGBoostError : BoostLearner: wrong model format" in exactly same version of xgboost

### ISSUE THREAD

**Issue by HuangChiEn** [dmlc/xgboost#7909]
I have pretrained an xgboost classifier and save it by the most safety way I though ( official method : clf.save_model(xxx.json) ).

Unfortunately, I have encounter the bug while loading the weight, and the bug info is described as follows:
![image](https://user-images.githubusercontent.com/52521165/168557566-e630bf6b-9428-465c-a6dd-558a35827aac.png)

To be honest, it's not surprising. I believe the back-competition port is very hard to implement for most of the open-source.
That's why most of the people prefer to use the "same version" while pip install the dependencies.

However, both of the xgboost version is "exactly the same" (see the below screen shot). I can successful to load the model in local host, but encountered the above issue to the online jupyter note env.

pip list version of local host:
![image](https://user-images.githubusercontent.com/52521165/168556898-de90b815-9b3d-4948-af10-e178dd359b8f.png)

pip list version of online jupyter notebook env:
![image](https://user-images.githubusercontent.com/52521165/168557029-9a5f8333-05be-43ff-a7f9-7d6b35ff444c.png)

By the way, seems the canonical format to save the xgboost should change to pickle or joblib ~
https://stackoverflow.com/questions/43691380/how-to-save-load-xgboost-model

**Comment by trivialfis** [comment]
XGBoost is backward compatible. Could you share your model? Or is there a way to reproduce the error?

**Comment by trivialfis** [comment]
Also, could you please verify that the model is the same on your jupyter environment and there's no transmition error? I'm asking as we are still testing models from 0.9. https://github.com/dmlc/xgboost/blob/master/tests/python/test_model_compatibility.py

**Comment by hcho3** [comment]
Also ensure that the local and online machines have the same processor architecture. There could be an issue with endianness.

**Comment by HuangChiEn** [comment]
> XGBoost is backward compatible. Could you share your model? Or is there a way to reproduce the error?



> Also ensure that the local and online machines have the same processor architecture. There could be an issue with endianness.

That't the point i can not confirm, since the online jupyter enviroment is provided by the competition host (seems use the docker to built the jupyterlab). So I still save the model in pickle format to deal with that.

**Comment by HuangChiEn** [comment]
> XGBoost is backward compatible. Could you share your model? Or is there a way to reproduce the error?



> 



> XGBoost is backward compatible. Could you share your model? Or is there a way to reproduce the error?

Since i already deleted it. I can retrain the model after the competition end. It may be helpful for the competition test.

**Comment by trivialfis** [comment]
I will close this now. If the issue persists with the latest xgboost please feel free to reopen.
