### ISSUE TITLE
"Check failed: _count >= 0" issue in scala-spark distributed XGBoost training (v 0.90)

### ISSUE THREAD

**Issue by sans-k73** [dmlc/xgboost#7929]
Hi Team,

I'm facing the following issue with XGBoost v0.90 scala-spark distributed training. 

**[00:20:49] Tree method is automatically selected to be 'approx' for distributed training.
terminate called after throwing an instance of 'dmlc::Error'
  what():  [00:20:57] /xgboost/src/common/./span.h:403: Check failed: _count >= 0:
Stack trace:
  [bt] (0) /tmp/hadoop-mapr/nm-local-dir/usercache/<use_case_name>/appcache/application_<app_id>/container_e298_<app_id>_01_000067/tmp/libxgboost4j1134276781596650078.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x22) [0x7f4ff99f9f82]
  [bt] (1) /tmp/hadoop-mapr/nm-local-dir/usercache/<use_case_name>/appcache/application_<app_id>/container_e298_<app_id>_01_000067/tmp/libxgboost4j1134276781596650078.so(xgboost::common::Span<xgboost::Entry const, -1l>::Span(xgboost::Entry const*, long)+0xd7) [0x7f4ff9a1c967]
  [bt] (2) /tmp/hadoop-mapr/nm-local-dir/usercache/<use_case_name>/appcache/application_<app_id>/container_e298_<app_id>_01_000067/tmp/libxgboost4j1134276781596650078.so(xgboost::SparsePage::operator[](unsigned long) const+0x7f) [0x7f4ff9a1ca1f]
  [bt] (3) /tmp/hadoop-mapr/nm-local-dir/usercache/<use_case_name>/appcache/application_<app_id>/container_e298_<app_id>_01_000067/tmp/libxgboost4j1134276781596650078.so(+0x1eb4cd) [0x7f4ff9b414cd]
  [bt] (4) /lib64/libgomp.so.1(+0x16405) [0x7f4ff9746405]
  [bt] (5) /lib64/libpthread.so.0(+0x7ea5) [0x7f508a030ea5]
  [bt] (6) /lib64/libc.so.6(clone+0x6d) [0x7f508993db0d]**
  
  

The model is of Classification type and has both numerical and categorical features. Spark ML's StringIndexer, OneHotEncoder and VectorAssembler is used to transform the dataset before training. The dataset has about 2 million samples. 

One of the categorical feature has some distinct values with very low count. As a result I believe not all workers are able to receive an instance of the feature, due to which the error is thrown.

I understand that an issue similar to this has been raised in the past and has been addressed in https://github.com/dmlc/xgboost/pull/4045 ("fix the issue with infrequent feature") for v0.82 release. However, this issue seems to appear in the 0.90 version that I'm using.

Reducing the number of workers as a workaround to this issue is not favorable for my use case, considering the maximum distributed training capability to be leveraged for the trainings, and also because the reduced number to be configured for the workers would be dynamic everyday depending on the data in the categorical feature on that day.

Please help me to resolve this issue and let me know if any further information is required. Thanks in advance !

**Comment by trivialfis** [comment]
Could you please use 1.6.1? 0.9 is no longer supported.
