### ISSUE TITLE
Ability to save models from xgb.cv

### ISSUE THREAD

**Issue by vykhand** [dmlc/xgboost#793]
Dear developers, 

I believe I am speaking on behalf of many Kaggle competitors when saying we would _love_ to have a feature to save models trained by xgb.cv. 
Currently one has to re-run xgb.train in order to get a model. It would be lovely to also be able to save all k best models trained on the different folds.

Would you consider adding this feature?  I was looking into adding it myself for the R package, but can't figure out the best place to add it yet, would you at least kindly point me to this place?

Best regards and cheers for the wonderful package.

Andrey

**Comment by leblancfg** [comment]
Agreed. I don't think there's any way around this, at least in its current R implementation. I believe most people use the caret package to hypertune with CV, but I find it's still clunky in terms of data types, etc.
