### ISSUE TITLE
Input contains NaN, infinity or a value too large for dtype('float32').

### ISSUE THREAD

**Issue by ooghry** [dmlc/xgboost#7941]
Hello,
I'm trying to run Optuna with XGBoost and after some trails with `validation-mlogloss around 1` I get big `validation-mlogloss` and some errors:
(I don't know Optuna or XGBoost cause this)
```
[16:38:51] WARNING: ../src/learner.cc:627:
Parameters: { "colsample_bytree", "subsample" } might not be used.

  This could be a false alarm, with some parameters getting used by language bindings but
  then being mistakenly passed down to XGBoost core, or some parameter actually being used
  but getting flagged wrongly here. Please open an issue if you find any such cases.


[0]     validation-mlogloss:25.48270
[1]     validation-mlogloss:22.83236
[2]     validation-mlogloss:36.84136
[3]     validation-mlogloss:36.84136
[4]     validation-mlogloss:36.84136
[5]     validation-mlogloss:36.84136
[6]     validation-mlogloss:36.84136
[7]     validation-mlogloss:36.84136
[8]     validation-mlogloss:36.84136
[9]     validation-mlogloss:36.84136
[W 2022-05-25 16:39:27,208] Trial 0 failed because of the following error: ValueError("Input contains NaN, infinity or a value too large for dtype('float32').")
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/optuna/study/_optimize.py", line 213, in _run_trial
    value_or_values = func(trial)
  File "optuna_xgboost.py", line 67, in objective
    return sklearn.metrics.log_loss(valid_y, bst.predict(dvalid))
  File "/usr/local/lib/python3.7/site-packages/sklearn/metrics/_classification.py", line 2379, in log_loss
    y_pred = check_array(y_pred, ensure_2d=False)
  File "/usr/local/lib/python3.7/site-packages/sklearn/utils/validation.py", line 800, in check_array
    _assert_all_finite(array, allow_nan=force_all_finite == "allow-nan")
  File "/usr/local/lib/python3.7/site-packages/sklearn/utils/validation.py", line 116, in _assert_all_finite
    type_err, msg_dtype if msg_dtype is not None else X.dtype
ValueError: Input contains NaN, infinity or a value too large for dtype('float32').
Traceback (most recent call last):
  File "optuna_xgboost.py", line 75, in <module>
    study.optimize(objective, n_trials=100, )
  File "/usr/local/lib/python3.7/site-packages/optuna/study/study.py", line 409, in optimize
    show_progress_bar=show_progress_bar,
  File "/usr/local/lib/python3.7/site-packages/optuna/study/_optimize.py", line 76, in _optimize
    progress_bar=progress_bar,
  File "/usr/local/lib/python3.7/site-packages/optuna/study/_optimize.py", line 163, in _optimize_sequential
    trial = _run_trial(study, func, catch)
  File "/usr/local/lib/python3.7/site-packages/optuna/study/_optimize.py", line 264, in _run_trial
    raise func_err
  File "/usr/local/lib/python3.7/site-packages/optuna/study/_optimize.py", line 213, in _run_trial
    value_or_values = func(trial)
  File "optuna_xgboost.py", line 67, in objective
    return sklearn.metrics.log_loss(valid_y, bst.predict(dvalid))
  File "/usr/local/lib/python3.7/site-packages/sklearn/metrics/_classification.py", line 2379, in log_loss
    y_pred = check_array(y_pred, ensure_2d=False)
  File "/usr/local/lib/python3.7/site-packages/sklearn/utils/validation.py", line 800, in check_array
    _assert_all_finite(array, allow_nan=force_all_finite == "allow-nan")
  File "/usr/local/lib/python3.7/site-packages/sklearn/utils/validation.py", line 116, in _assert_all_finite
    type_err, msg_dtype if msg_dtype is not None else X.dtype
ValueError: Input contains NaN, infinity or a value too large for dtype('float32').
```

```
python : 3.7
xgboost : 1.6.1
optuna : 2.10.0
sklearn-learn : 1.0.2
```

**Comment by ooghry** [comment]
My code is [here](https://gist.github.com/ooghry/a7bb18b375f913104a4e959299ef0d13) (sorry it's messy)

**Comment by trivialfis** [comment]
Hmm .. that's gblinear.

**Comment by vitorglemos** [comment]
I also had a similar problem in XGboost. In my case, the problem was caused by a bad format in one line of my data. Did you check if everything is ok?

**Comment by ooghry** [comment]
@vitorglemos  All my column is numeric and I'm using `dtype` parameter with `read_csv` and applying `fillna`. Is there anything else I can think of?
Is it possible that this happened because of the type of columns I specified? (I have shared the code.)

You are welcome to dig into my [data](https://drive.google.com/file/d/1ZUIgAnDp3svGcfxYQDcr-iv0QGFZYwtP/view?usp=sharing)

**Comment by vitorglemos** [comment]
@ooghry[ooghry](https://github.com/ooghry) I just ran your code with your data. It ran normally but my xgboost version is different (1.2.0).  Did you test with this version?

**Comment by ooghry** [comment]
@vitorglemos Sorry for the delay. I run 200 trails of `gblinear` on version `1.2.0` with no error.
I will try again with `1.5.*` and `1.6.*` in the following days.

**Comment by ooghry** [comment]
I just got the error after 40 trails on version `1.5.2`
```
[I 2022-06-15 17:30:42,421] Trial 40 finished with value: 1.066675928681359 and parameters: {'lambda': 5.85269736275417e-05, 'alpha': 0.3504886325741485}. Best is trial 2 with value: 1.0580027750861625.
[0]	validation-mlogloss:1.08179
[1]	validation-mlogloss:15.24863
[2]	validation-mlogloss:14.31767
[3]	validation-mlogloss:13.95880
[4]	validation-mlogloss:13.88373
[5]	validation-mlogloss:14.29573
[6]	validation-mlogloss:36.84127
[7]	validation-mlogloss:36.84127
[8]	validation-mlogloss:36.84127
[9]	validation-mlogloss:36.84127
[W 2022-06-15 17:31:55,571] Trial 41 failed because of the following error: ValueError("Input contains NaN, infinity or a value too large for dtype('float32').")
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/optuna/study/_optimize.py", line 213, in _run_trial
    value_or_values = func(trial)
  File "<ipython-input-10-3f11d5a6b48f>", line 40, in objective
    return sklearn.metrics.log_loss(valid_y, bst.predict(dvalid))
  File "/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py", line 2379, in log_loss
    y_pred = check_array(y_pred, ensure_2d=False)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py", line 800, in check_array
    _assert_all_finite(array, allow_nan=force_all_finite == "allow-nan")
  File "/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py", line 116, in _assert_all_finite
    type_err, msg_dtype if msg_dtype is not None else X.dtype
ValueError: Input contains NaN, infinity or a value too large for dtype('float32').
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-12-fa795112d661> in <module>()
      5     pruner=optuna.pruners.MedianPruner(n_warmup_steps=50), direction="minimize"
      6 )
----> 7 study.optimize(objective, n_trials=200, )

8 frames
/usr/local/lib/python3.7/dist-packages/optuna/study/study.py in optimize(self, func, n_trials, timeout, n_jobs, catch, callbacks, gc_after_trial, show_progress_bar)
    407             callbacks=callbacks,
    408             gc_after_trial=gc_after_trial,
--> 409             show_progress_bar=show_progress_bar,
    410         )
    411 

/usr/local/lib/python3.7/dist-packages/optuna/study/_optimize.py in _optimize(study, func, n_trials, timeout, n_jobs, catch, callbacks, gc_after_trial, show_progress_bar)
     74                 reseed_sampler_rng=False,
     75                 time_start=None,
---> 76                 progress_bar=progress_bar,
     77             )
     78         else:

/usr/local/lib/python3.7/dist-packages/optuna/study/_optimize.py in _optimize_sequential(study, func, n_trials, timeout, catch, callbacks, gc_after_trial, reseed_sampler_rng, time_start, progress_bar)
    161 
    162         try:
--> 163             trial = _run_trial(study, func, catch)
    164         except Exception:
    165             raise

/usr/local/lib/python3.7/dist-packages/optuna/study/_optimize.py in _run_trial(study, func, catch)
    262 
    263     if state == TrialState.FAIL and func_err is not None and not isinstance(func_err, catch):
--> 264         raise func_err
    265     return trial
    266 

/usr/local/lib/python3.7/dist-packages/optuna/study/_optimize.py in _run_trial(study, func, catch)
    211 
    212     try:
--> 213         value_or_values = func(trial)
    214     except exceptions.TrialPruned as e:
    215         # TODO(mamu): Handle multi-objective cases.

<ipython-input-10-3f11d5a6b48f> in objective(trial)
     38         pruning_callback = optuna.integration.XGBoostPruningCallback(trial, "validation-mlogloss")
     39         bst = xgb.train(param, dtrain, evals=[(dvalid, "validation")], callbacks=[pruning_callback])
---> 40         return sklearn.metrics.log_loss(valid_y, bst.predict(dvalid))

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py in log_loss(y_true, y_pred, eps, normalize, sample_weight, labels)
   2377     p. 209.
   2378     """
-> 2379     y_pred = check_array(y_pred, ensure_2d=False)
   2380     check_consistent_length(y_pred, y_true, sample_weight)
   2381 

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py in check_array(array, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features, estimator)
    798 
    799         if force_all_finite:
--> 800             _assert_all_finite(array, allow_nan=force_all_finite == "allow-nan")
    801 
    802     if ensure_min_samples > 0:

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py in _assert_all_finite(X, allow_nan, msg_dtype)
    114             raise ValueError(
    115                 msg_err.format(
--> 116                     type_err, msg_dtype if msg_dtype is not None else X.dtype
    117                 )
    118             )

ValueError: Input contains NaN, infinity or a value too large for dtype('float32').
```

**Comment by trivialfis** [comment]
Hi, the error seems to be coming from sklearn data validation instead of XGBoost. Could you please verify your data?

**Comment by ooghry** [comment]
@trivialfis 

> Could you please verify your data?

I don't know if it's my language barrier or because I'm not an ML expert. Sorry, I have no idea what you ask.

**Comment by SiminTan** [comment]
I got the same error using xgboost+optuna.
But using lightgbm+optuna successfully completed the parameter tuning task for same dataset.

**Comment by SiminTan** [comment]
I have solved my problem and I hope my answer is not too late.
The cause of the problem was the combination of parameters in xgboost. I had the following list of parameters, and the problem arose when I gradually set the parameter value of subsample to 1.


def objective(trial):
    # dmatrix
    dtrain=xgb.DMatrix(X_fit,y_fit)
    dvalid=xgb.DMatrix(X_val,y_val)
    # params
    params = {
    'booster': 'gbtree',
    'metric':'auc',
    'eval_metric':'auc',
    'max_depth':5,
    'min_child_weight':100,
    # 'lambda':100,
    'gamma':0.1,
    'subsample': trial.suggest_categorical('subsample', [1.0]),
    'colsample_bytree': trial.suggest_categorical('colsample_bytree', [0.6,0.8,0.9]),
    'scale_pos_weight':1,
    'tree_method':'hist',
    'nthread':32,
    'eta':0.02
    }

When I remove the value 1, for example：
'subsample': trial.success_categorical('subsample', [0.2,0.3,0.5,0.8]), the problem is solved.

**Comment by CSU-Tan** [comment]
I have solved my problem and I hope my answer is not too late.
The cause of the problem was the combination of parameters in xgboost. I had the following list of parameters, and the problem arose when I gradually set the parameter value of subsample to 1.

def objective(trial):
# dmatrix
dtrain=xgb.DMatrix(X_fit,y_fit)
dvalid=xgb.DMatrix(X_val,y_val)
# params
params = {
'booster': 'gbtree',
'metric':'auc',
'eval_metric':'auc',
'max_depth':5,
'min_child_weight':100,
# 'lambda':100,
'gamma':0.1,
'subsample': trial.suggest_categorical('subsample', [1.0]),
'colsample_bytree': trial.suggest_categorical('colsample_bytree', [0.6,0.8,0.9]),
'scale_pos_weight':1,
'tree_method':'hist',
'nthread':32,
'eta':0.02
}

When I remove the value 1, for example：
'subsample': trial.success_categorical('subsample', [0.2,0.3,0.5,0.8]), the problem is solved.

**Comment by ooghry** [comment]
@CSU-Tan Thank you for your reply.
I do not have access to the server from which the error occurred, and currently I do not have a problem on Google Colab, so I close the issue.

**Comment by yusiyohpolimi** [comment]
There is a similar issue once again, and also using an estimator with sklearn RFE is MUCH slower than before with the latest updates. I was shocked due to the changes in the last 12 hours.

**Comment by trivialfis** [comment]
I'm confused, what's changed in the last 12 hours

**Comment by aicooks** [comment]
I have encountered a similar situation and don't know how to solve it.(My version of xgboost is 1.7.5)
The following is the information I reported an error.
ValueError                                Traceback (most recent call last)
Cell In[5], line 26
     24 train_XGB = -time.time()
     25 # y_train = y_train.reset_index(drop=True)
---> 26 XGB(X_train, y_train, normalize=False, save_model='/SE_identification/classification_models_1/xgb_model.pickle', save_param='/SE_identification/classification_models_1/xgb_parametres.pickle')
     27 train_XGB += time.time()
     28 print('XGB')

File ~/project/anomaly_identification-main/functions/classification.py:217, in XGB(X, y, n_calls, normalize, file, save_model, save_param)
    214     bayes_model.set_params(**params)
    215     return -np.mean(cross_val_score(bayes_model, X, y, cv=5, n_jobs=-1, scoring="neg_mean_absolute_error"))
--> 217 res_bayes_model = gbrt_minimize(objective, space, n_calls=n_calls, random_state=0)
    220 model = XGBClassifier(n_estimators=res_bayes_model.x[0],
    221                       max_depth=res_bayes_model.x[1],
    222                       eta=res_bayes_model.x[2],
   (...)
    225                       random_state=0,
    226                       silent=True)
    228 model.fit(X, y)

File ~/.conda/envs/py10_12.4/lib/python3.10/site-packages/skopt/optimizer/gbrt.py:197, in gbrt_minimize(func, dimensions, base_estimator, n_calls, n_random_starts, n_initial_points, initial_point_generator, acq_func, acq_optimizer, x0, y0, random_state, verbose, callback, n_points, xi, kappa, n_jobs, model_queue_size, space_constraint)
    195 if base_estimator is None:
    196     base_estimator = cook_estimator("GBRT", random_state=rng, n_jobs=n_jobs)
--> 197 return base_minimize(
    198     func,
    199     dimensions,
    200     base_estimator,
    201     n_calls=n_calls,
    202     n_points=n_points,
    203     n_random_starts=n_random_starts,
    204     n_initial_points=n_initial_points,
    205     initial_point_generator=initial_point_generator,
    206     x0=x0,
    207     y0=y0,
    208     random_state=random_state,
    209     xi=xi,
    210     kappa=kappa,
    211     acq_func=acq_func,
    212     verbose=verbose,
    213     callback=callback,
    214     acq_optimizer="sampling",
    215     space_constraint=space_constraint,
    216     model_queue_size=model_queue_size,
    217     n_jobs=n_jobs,
    218 )

File ~/.conda/envs/py10_12.4/lib/python3.10/site-packages/skopt/optimizer/base.py:333, in base_minimize(func, dimensions, base_estimator, n_calls, n_random_starts, n_initial_points, initial_point_generator, acq_func, acq_optimizer, x0, y0, random_state, verbose, callback, n_points, n_restarts_optimizer, xi, kappa, n_jobs, model_queue_size, space_constraint)
    331 next_x = optimizer.ask()
    332 next_y = func(next_x)
--> 333 result = optimizer.tell(next_x, next_y)
    334 result.specs = specs
    335 if eval_callbacks(callbacks, result):

File ~/.conda/envs/py10_12.4/lib/python3.10/site-packages/skopt/optimizer/optimizer.py:570, in Optimizer.tell(self, x, y, fit)
    567         y = list(y)
    568         y[1] = log(y[1])
--> 570 return self._tell(x, y, fit=fit)

File ~/.conda/envs/py10_12.4/lib/python3.10/site-packages/skopt/optimizer/optimizer.py:615, in Optimizer._tell(self, x, y, fit)
    613 with warnings.catch_warnings():
    614     warnings.simplefilter("ignore")
--> 615     est.fit(self.space.transform(self.Xi), self.yi)
    617 if hasattr(self, "next_xs_") and self.acq_func == "gp_hedge":
    618     self.gains_ -= est.predict(np.vstack(self.next_xs_))

File ~/.conda/envs/py10_12.4/lib/python3.10/site-packages/skopt/learning/gbrt.py:93, in GradientBoostingQuantileRegressor.fit(self, X, y)
     89     regressor.set_params(alpha=q)
     91     regressors.append(regressor)
---> 93 self.regressors_ = Parallel(n_jobs=self.n_jobs, backend='threading')(
     94     delayed(_parallel_fit)(regressor, X, y) for regressor in regressors
     95 )
     97 return self

File ~/.conda/envs/py10_12.4/lib/python3.10/site-packages/joblib/parallel.py:1918, in Parallel.__call__(self, iterable)
   1916     output = self._get_sequential_output(iterable)
   1917     next(output)
-> 1918     return output if self.return_generator else list(output)
   1920 # Let's create an ID that uniquely identifies the current call. If the
   1921 # call is interrupted early and that the same instance is immediately
   1922 # re-used, this id will be used to prevent workers that were
   1923 # concurrently finalizing a task from the previous call to run the
   1924 # callback.
   1925 with self._lock:

File ~/.conda/envs/py10_12.4/lib/python3.10/site-packages/joblib/parallel.py:1847, in Parallel._get_sequential_output(self, iterable)
   1845 self.n_dispatched_batches += 1
   1846 self.n_dispatched_tasks += 1
-> 1847 res = func(*args, **kwargs)
   1848 self.n_completed_tasks += 1
   1849 self.print_progress()

File ~/.conda/envs/py10_12.4/lib/python3.10/site-packages/skopt/learning/gbrt.py:9, in _parallel_fit(regressor, X, y)
      8 def _parallel_fit(regressor, X, y):
----> 9     return regressor.fit(X, y)

File ~/.conda/envs/py10_12.4/lib/python3.10/site-packages/sklearn/ensemble/_gb.py:486, in BaseGradientBoosting.fit(self, X, y, sample_weight, monitor)
    480     self._clear_state()
    482 # Check input
    483 # Since check_array converts both X and y to the same dtype, but the
    484 # trees use different types for X and y, checking them separately.
--> 486 X, y = self._validate_data(
    487     X, y, accept_sparse=["csr", "csc", "coo"], dtype=DTYPE, multi_output=True
    488 )
    490 sample_weight_is_none = sample_weight is None
    492 sample_weight = _check_sample_weight(sample_weight, X)

File ~/.conda/envs/py10_12.4/lib/python3.10/site-packages/sklearn/base.py:581, in BaseEstimator._validate_data(self, X, y, reset, validate_separately, **check_params)
    579         y = check_array(y, **check_y_params)
    580     else:
--> 581         X, y = check_X_y(X, y, **check_params)
    582     out = X, y
    584 if not no_val_X and check_params.get("ensure_2d", True):

File ~/.conda/envs/py10_12.4/lib/python3.10/site-packages/sklearn/utils/validation.py:979, in check_X_y(X, y, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, multi_output, ensure_min_samples, ensure_min_features, y_numeric, estimator)
    962     raise ValueError("y cannot be None")
    964 X = check_array(
    965     X,
    966     accept_sparse=accept_sparse,
   (...)
    976     estimator=estimator,
    977 )
--> 979 y = _check_y(y, multi_output=multi_output, y_numeric=y_numeric)
    981 check_consistent_length(X, y)
    983 return X, y

File ~/.conda/envs/py10_12.4/lib/python3.10/site-packages/sklearn/utils/validation.py:989, in _check_y(y, multi_output, y_numeric)
    987 """Isolated part of check_X_y dedicated to y validation"""
    988 if multi_output:
--> 989     y = check_array(
    990         y, accept_sparse="csr", force_all_finite=True, ensure_2d=False, dtype=None
    991     )
    992 else:
    993     y = column_or_1d(y, warn=True)

File ~/.conda/envs/py10_12.4/lib/python3.10/site-packages/sklearn/utils/validation.py:800, in check_array(array, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features, estimator)
    794         raise ValueError(
    795             "Found array with dim %d. %s expected <= 2."
    796             % (array.ndim, estimator_name)
    797         )
    799     if force_all_finite:
--> 800         _assert_all_finite(array, allow_nan=force_all_finite == "allow-nan")
    802 if ensure_min_samples > 0:
    803     n_samples = _num_samples(array)

File ~/.conda/envs/py10_12.4/lib/python3.10/site-packages/sklearn/utils/validation.py:114, in _assert_all_finite(X, allow_nan, msg_dtype)
    107     if (
    108         allow_nan
    109         and np.isinf(X).any()
    110         or not allow_nan
    111         and not np.isfinite(X).all()
    112     ):
    113         type_err = "infinity" if allow_nan else "NaN, infinity"
--> 114         raise ValueError(
    115             msg_err.format(
    116                 type_err, msg_dtype if msg_dtype is not None else X.dtype
    117             )
    118         )
    119 # for object dtype data, we only check for NaNs (GH-13254)
    120 elif X.dtype == np.dtype("object") and not allow_nan:

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
