### ISSUE TITLE
XGBoostError: sklearn needs to be installed in order to use this module

### ISSUE THREAD

**Issue by edc-ff** [dmlc/xgboost#7944]
Hey all,

I'm getting the error in the title while trying to run the following code:
```
from xgboost import XGBRegressor
xgb = XGBRegressor()
```

I'm currently using a fresh environment with:
```
scikit-learn                           1.1.1
xgboost                                1.6.1
````

For environment managing I'm using miniconda 4.12.0.
My current machine is a mac with Monterey OS and Apple M1 chip.

I've already tried recreating the environment and installing the libraries in different order, but it didn't solve the issue.

Any suggestions?

Thanks.

**Comment by trivialfis** [comment]
Could you please try to run this on your environment and share the result with us:

``` python
    from sklearn.base import (
         BaseEstimator as XGBModelBase,
         RegressorMixin as XGBRegressorBase,
         ClassifierMixin as XGBClassifierBase
    )
    from sklearn.preprocessing import LabelEncoder

    try:
        from sklearn.model_selection import (
            KFold as XGBKFold,
            StratifiedKFold as XGBStratifiedKFold
        )
    except ImportError:
        from sklearn.cross_validation import (
            KFold as XGBKFold,
            StratifiedKFold as XGBStratifiedKFold
        )
```

**Comment by edc-ff** [comment]
Thanks, that helped me find out the issue.

In brief, I was starting an iPython shell from within the environment. For some reason, xgboost was available in the iPython shell, but the same didn't happen for sklearn.

Everything is working fine now, thanks and sorry for jumping the gun!

**Comment by trivialfis** [comment]
Excellent!
