### ISSUE TITLE
Issue install R package xgboost in raspberry pi 3B+

### ISSUE THREAD

**Issue by phisanti** [dmlc/xgboost#7961]
I am trying to install the xgboost package for R in a `raspberry pi 3B+` running on `ubuntu 22.04`. I was able to install the package from source, however, when I run the command `library(xgboost)` it seems is not available. I then read that I need to run the command `R CMD INSTALL ..` in the xgboost/R-package folder but couldn't install. I also tried the classic `install.packages('xgboost')` but it always get's stuck on the same line (see image). I thought it could be a problem with the RAM memory so I opened a 2GB extra swapfile but that didn't change anything. Thus, I would appreciate any help to solve the issue.

I only need it for loading models and predict, so there might be some work around if anyone comes up with.

![image](https://user-images.githubusercontent.com/33370667/171356491-c63f13a8-2445-4110-b4c7-d85e773d8452.png)

**Comment by hcho3** [comment]
It takes a while to compile the amagalmation file (amagalmation/xgboost-all.o). How long have you waited?

**Comment by phisanti** [comment]
This is the method that I followed. In my original post I said I installed the package from source so I did this:
```bash
mkdir build
cd build
cmake .. -DR_LIB=ON
make -j$(nproc)
make install
```

which was successfully installed. Then I go to R and run "library(xgboost)" it does not find the library. Then I tried:

```bash
cd xgboost/R-package
R CMD INSTALL .
```

Maybe I did something wrong during the `cmake `installation and that is why is not detected but I can re-install it and send a screenshot so you can see if I followed the procedure properly.

**Comment by hcho3** [comment]
Can you post the full log of the CMake installation?

**Comment by phisanti** [comment]
Here it is:
![image](https://user-images.githubusercontent.com/33370667/171372935-7754a3f9-d061-4f39-b9f6-7abb28501bf0.png)
![image](https://user-images.githubusercontent.com/33370667/171372982-f6ac1f7c-fd25-4276-ae6c-4d78fc0e0fdd.png)
![image](https://user-images.githubusercontent.com/33370667/171373037-90cad2df-7968-4585-bd62-439a15bfe708.png)

**Comment by hcho3** [comment]
You didn't run `make install` after `make -j$(nproc)`?

**Comment by phisanti** [comment]
@hcho3 you are completely right. Now it's running perfectly. Sorry for the mistake. Thanks for the help!

**Comment by hcho3** [comment]
Glad it worked!
