### ISSUE TITLE
Compilation Error from install_git

### ISSUE THREAD

**Issue by trazom21** [dmlc/xgboost#797]
Hi,

Thanks for this awesome package ! 

When I try to install xgboost using the command: _devtools::install_git('git://github.com/dmlc/xgboost',subdir='R-package')_, the compilation fail with an error: xgboost_R.cc:2:26: fatal error: dmlc/logging.h: No such file or director

Best

C.

**Comment by tqchen** [comment]
Try to install from drat repo instead, follow instruction here https://github.com/dmlc/xgboost/tree/master/R-package

**Comment by trazom21** [comment]
Thanks,
Finally I forked it. And compile directly on my own computer. Works fine.
C.
