### ISSUE TITLE
When parsing JSON model with integer value in a number field, get "Invalid cast, from Integer to Number"

### ISSUE THREAD

**Issue by negatratoron** [dmlc/xgboost#7970]
After fixing #7949 there's still one issue with JSON parsing after formatting.  I took a JSON model that I saved, and piped it through `jq`.  This had the effect of rewriting all numbers from exponential notation to decimal notation (e.g. `5E0` to `5`).  JSON doesn't distinguish between integers and decimals (https://www.json.org/json-en.html) so the reformatting is valid.

Expected behavior: `XGBoosterLoadModelFromBuffer` can parse integers in the JSON document as numbers.

Actual behavior: Rewriting any numbers as integers gives the error "error in XGBoosterLoadModelFromBuffer... Invalid cast, from Integer to Number"

Steps to reproduce: Take a valid JSON model.  Rewrite any field that is a number (https://xgboost.readthedocs.io/en/stable/tutorials/saving_model.html) as an integer.  Attempt to load the model.

---

Could either add a check to https://github.com/dmlc/xgboost/blob/6426449c8be17856984caeb9892831e3e1e27037/src/tree/tree_model.cc#L916 like the Boolean check and allow JSON Integers as Numbers

or modify this function to allow that conversion globally (seems right to me) https://github.com/dmlc/xgboost/blob/6426449c8be17856984caeb9892831e3e1e27037/include/xgboost/json.h#L583

**Comment by trivialfis** [comment]
That's expected. Please don't modify the JSON model in this way.  We support loading only models generated by XGBoost.

**Comment by trivialfis** [comment]
To elaborate on the issue, the JSON model has a couple of requirements like reproducible results for floating-point values, which can only be obtained with the encoder/decoder inside XGBoost. If one of them is changed then the floating-point serialization will no longer be exact.

**Comment by negatratoron** [comment]
All right, thanks for the information!
