### ISSUE TITLE
num_class not found while using multi:softprob in XGBoost on GPU

### ISSUE THREAD

**Issue by shubhampal1** [dmlc/xgboost#7972]
Hello, 

I have been trying to use Xgboost on  GPU. I am able to do binary classification but the moment I specify number of clusters and use multi:softprob then I get an error " __init__() got an unexpected keyword argument 'num_class' " .

Let me know if there are some additional steps I need to take. I am using a data bricks notebook on GPU cluster.

**Comment by trivialfis** [comment]
Could you please share the XGBoost version and a reproducible script?
