### ISSUE TITLE
Compiling on Win 10 64 bit with MinGW fails

### ISSUE THREAD

**Issue by jraju9** [dmlc/xgboost#798]
Hello XGB Team,

Thanks for the great package.. Can you please help me resolve this issue? When I try to compile the package using MinGW, I get the following errors.

![make error](https://cloud.githubusercontent.com/assets/6312103/12737890/1fba8c96-c92a-11e5-9896-bee113601261.png)

Thanks,
Jai

**Comment by tqchen** [comment]
seems due to inconsistency of mkdir command https://github.com/dmlc/xgboost/blob/master/Makefile#L97 

Try to remove -p, see also instruction here  http://xgboost.readthedocs.org/en/latest/build.html

**Comment by jraju9** [comment]
Dear Tqchen, 

Thank you very much for your response. I tried a couple things (removing -p, make clean_all, clone the whole directory and build) none of them seem to be working. Can you please look at this error and help?

Also, if I need to just build the libxgboost.dll, is there a target I can call and not include all the other distributions?

Very thankful for your support.
Jai

![image](https://cloud.githubusercontent.com/assets/6312103/12772315/24acd9aa-c9fe-11e5-8ee2-64cd6071cb72.png)

**Comment by tqchen** [comment]
The first line in your error message indicate that a subdir build already exists. 
So it is likely you can remove the mkdir command and solve the problem.

**Comment by thirdwing** [comment]
@jraju9 I think there won't be this kind of errors if you follow our updated building instructions.
