### ISSUE TITLE
Fit pd.DataFrame is 5x slower than fitting a ndarray

### ISSUE THREAD

**Issue by diegolovison** [dmlc/xgboost#7984]
Fit `pd.DataFrame` is 5x slower than fitting a `ndarray`

slow code
```python
xgb_model = XGBRegressor(random_state=self.seed, n_jobs=1)
xgb_model.fit(X_train, y_train)
xgb_pred = xgb_model.predict(X_test)
```
faster code
```python
xgb_model = XGBRegressor(random_state=self.seed, n_jobs=1)
xgb_model.fit(X_train.to_numpy(), y_train.to_numpy())
xgb_pred = xgb_model.predict(X_test.to_numpy())
```

```
xgboost-1.6.1
pandas-1.4.0
numpy-1.19.2
```

**Comment by trivialfis** [comment]
Could you please share the size of your data and its column types?

**Comment by diegolovison** [comment]
All float numbers
12x16000

**Comment by trivialfis** [comment]
Yeah, that makes sense. We have to check pandas data type column by column: https://github.com/dmlc/xgboost/blob/bb47fd8c496ccd25e6499f722f0d9f2ee3965500/python-package/xgboost/data.py#L340

**Comment by trivialfis** [comment]
For small and wide dataset, please just use numpy instead.
