### ISSUE TITLE
ValueError: Found input variables with inconsistent numbers of samples: [741488, 317781]

### ISSUE THREAD

**Issue by delaila-sys** [dmlc/xgboost#7988]
xgb_grid.fit(training_data,testing_data)
ValueError                                Traceback (most recent call last)
<ipython-input-32-74bb155fde81> in <module>
----> 1 xgb_grid.fit(training_data,testing_data)

~\AppData\Roaming\Python\Python38\site-packages\sklearn\utils\validation.py in inner_f(*args, **kwargs)
     70                           FutureWarning)
     71         kwargs.update({k: arg for k, arg in zip(sig.parameters, args)})
---> 72         return f(**kwargs)
     73     return inner_f
     74 

~\AppData\Roaming\Python\Python38\site-packages\sklearn\model_selection\_search.py in fit(self, X, y, groups, **fit_params)
    674             refit_metric = 'score'
    675 
--> 676         X, y, groups = indexable(X, y, groups)
    677         fit_params = _check_fit_params(X, fit_params)
    678 

~\AppData\Roaming\Python\Python38\site-packages\sklearn\utils\validation.py in indexable(*iterables)
    290     """
    291     result = [_make_indexable(X) for X in iterables]
--> 292     check_consistent_length(*result)
    293     return result
    294 

~\AppData\Roaming\Python\Python38\site-packages\sklearn\utils\validation.py in check_consistent_length(*arrays)
    253     uniques = np.unique(lengths)
    254     if len(uniques) > 1:
--> 255         raise ValueError("Found input variables with inconsistent numbers of"
    256                          " samples: %r" % [int(l) for l in lengths])
    257 

ValueError: Found input variables with inconsistent numbers of samples: [741488, 317781]

**Comment by trivialfis** [comment]
The error is raised from sklearn instead of XGBoost. Please check your input data for consistent X and y.
