### ISSUE TITLE
AttributeError when fitting DaskXGBClassifier on scipy.sparse matrix

### ISSUE THREAD

**Issue by rrpelgrim** [dmlc/xgboost#7990]
I'm running into the same issue as this closed issue: https://github.com/dmlc/xgboost/issues/7454

I'm running:
XGBoost: 1.5.1
Dask/Distributed: 2022.05.0
Python: 3.9.10
MacOS (M1 machine)

Reproducer
```python
import dask.dataframe as dd
import dask_ml.feature_extraction.text
import pandas as pd
import sklearn.datasets
from dask.distributed import Client
from xgboost.dask import DaskXGBClassifier

if __name__ == "__main__":

    with Client():
        # Create Dask DataFrame from sklearn 20newsgroups dataset
        bunch = sklearn.datasets.fetch_20newsgroups()
        df = dd.from_pandas(
            pd.DataFrame({"text": bunch.data, "target": bunch.target}), npartitions=25
        )

        # Create features with dask-ml's `HashingVectorizer``
        vect = dask_ml.feature_extraction.text.HashingVectorizer()
        X = vect.fit_transform(df["text"])

        # Format classification labels
        y = df["target"].to_dask_array()

        # Train XGBoost classifier
        clf = DaskXGBClassifier()
        print(f"{X = }")
        print(f"{y = }")
        clf.fit(X, y)  # Results in `AttributeError: divisions not found`
```

**Comment by ncclementi** [comment]
@trivialfis I just tried this installing xgboost =1.6.1 from pip (conda version is not available https://github.com/conda-forge/xgboost-feedstock/issues/89) and things hang in the last step (it was in that state for a long time, it never stopped), see gif below. 

![Screen Shot 2022-06-14 at 5 07 54 PM](https://user-images.githubusercontent.com/7526622/173689905-685ad8e4-d2f4-465b-b4b0-a695c95227b1.png)

results in 

![hang](https://user-images.githubusercontent.com/7526622/173689940-be6a8e96-fc92-4c7c-ab57-7b2333065798.gif)

environment:
```
python=3.9
xgboost=1.6.1
dask/distributed=2022.6.0  I also tried 2022.5.0
dask-ml=2022.5.27
pandas=1.4.2
sklearn=1.1.1
```

**Comment by trivialfis** [comment]
Hi, XGBoost is training and it's not stuck. It's just the data is unusually wide and as the result the computation is slow. (especially the communication of histogram). For such small dataset I think it's better to use single node training.

**Comment by trivialfis** [comment]
Closing in favor of https://github.com/dmlc/xgboost/issues/7997 . Thank you for the comments.

**Comment by rrpelgrim** [comment]
Thanks @trivialfis and @ncclementi. I had run `conda update xgboost` but clearly that wasn't pulling the latest version of xgboost.
