### ISSUE TITLE
Building XGBoost from source takes forever

### ISSUE THREAD

**Issue by sametsoekel** [dmlc/xgboost#8004]
I followed up the [official tutorial ](https://xgboost.readthedocs.io/en/latest/build.html#installing-r-package-with-gpu-support) to build XGboost from source with GPU support for R.

Followed this way;

```
git clone --recursive https://github.com/dmlc/xgboost
cd xgboost
mkdir build
cd build
cmake .. -DUSE_CUDA=ON -DBUILD_WITH_CUDA_CUB=ON -DR_LIB=ON
make -j4 
make install
```

It took about 5 seconds to run including the `cmake` code to get there. But  `make -j4` and later part takes ~**2 hours** to run.

I have no problem with it working after installed, works like charm. 

Thanks in advance.

**Comment by trivialfis** [comment]
You can try to match the number of cores used with the number of cores available on your machine by changing `-j4` to `-j$(nproc)`. Also, you can select the GPU arch by specifying the CMake argument https://github.com/dmlc/xgboost/blob/637e42a0c07741a95eb3dd7833126f27e9f87c8f/CMakeLists.txt#L54
