### ISSUE TITLE
failure to build on CUDA 10.1

### ISSUE THREAD

**Issue by xlla** [dmlc/xgboost#8006]
I want to build from source to enable cuda features but failure to build c_api.cu.o
branch : v1.6.1,
clang: 10.0
cuda: 10.1

error log here
<pre>
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:3654:7: error: exception specification of overriding function is more lax than base
      version
class __shared_ptr_emplace : public __shared_weak_count { 
      ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:4327:25: note: in instantiation of template class
      'std::__1::__shared_ptr_emplace<xgboost::data::CudfAdapter, std::__1::allocator<xgboost::data::CudfAdapter> >' requested here
::new ((__hold2.get())) _CntrlBlk(__a2, __1::forward< _Args> (__args)...); 
                        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:4706:27: note: in instantiation of function template specialization
      'std::__1::shared_ptr<xgboost::data::CudfAdapter>::make_shared<std::__1::basic_string<char, char_traits<char>, allocator<char> > &>' requested here
return shared_ptr< _Tp> ::make_shared(__1::forward< _Args> (__args)...); 
                          ^
/Users/xlla/git/xgboost/src/c_api/c_api.cu:102:15: note: in instantiation of function template specialization 'std::__1::make_shared<xgboost::data::CudfAdapter, std::__1::basic_string<char,
      char_traits<char>, allocator<char> > &>' requested here
auto x = std::make_shared< T> (json_str); 
              ^
/Users/xlla/git/xgboost/src/c_api/c_api.cu:132:8: note: in instantiation of function template specialization 'InplacePreidctCuda<xgboost::data::CudfAdapter>' requested here
return InplacePreidctCuda< xgboost::data::CudfAdapter> (handle, c_json_strs, c_json_config, p_m, out_shape, out_dim, out_result); 
       ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:3563:20: note: overridden virtual function is here
protected: virtual ~__shared_weak_count(); 
                   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:3654:7: error: exception specification of overriding function is more lax than base
      version
class __shared_ptr_emplace : public __shared_weak_count { 
      ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:4327:25: note: in instantiation of template class
      'std::__1::__shared_ptr_emplace<xgboost::data::CupyAdapter, std::__1::allocator<xgboost::data::CupyAdapter> >' requested here
::new ((__hold2.get())) _CntrlBlk(__a2, __1::forward< _Args> (__args)...); 
                        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:4706:27: note: in instantiation of function template specialization
      'std::__1::shared_ptr<xgboost::data::CupyAdapter>::make_shared<std::__1::basic_string<char, char_traits<char>, allocator<char> > &>' requested here
return shared_ptr< _Tp> ::make_shared(__1::forward< _Args> (__args)...); 
                          ^
/Users/xlla/git/xgboost/src/c_api/c_api.cu:102:15: note: in instantiation of function template specialization 'std::__1::make_shared<xgboost::data::CupyAdapter, std::__1::basic_string<char,
      char_traits<char>, allocator<char> > &>' requested here
auto x = std::make_shared< T> (json_str); 
              ^
/Users/xlla/git/xgboost/src/c_api/c_api.cu:144:8: note: in instantiation of function template specialization 'InplacePreidctCuda<xgboost::data::CupyAdapter>' requested here
return InplacePreidctCuda< xgboost::data::CupyAdapter> (handle, c_json_strs, c_json_config, p_m, out_shape, out_dim, out_result); 
       ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:3563:20: note: overridden virtual function is here
protected: virtual ~__shared_weak_count(); 
                   ^
2 errors generated.
src/CMakeFiles/objxgboost.dir/build.make:971: recipe for target 'src/CMakeFiles/objxgboost.dir/c_api/c_api.cu.o' failed
make[2]: *** [src/CMakeFiles/objxgboost.dir/c_api/c_api.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....

</pre>

the build command is 
<pre>
/usr/local/cuda/bin/nvcc  -ccbin=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DDMLC_CORE_USE_CMAKE -DDMLC_LOG_CUSTOMIZE=1 -DDMLC_USE_CXX11=1 -DTHRUST_IGNORE_CUB_VERSION_CHECK=1 -DXGBOOST_BUILTIN_PREFETCH_PRESENT=1 -DXGBOOST_MM_PREFETCH_PRESENT=1 -DXGBOOST_USE_CUDA=1 -DXGBOOST_USE_NCCL=1 -D_MWAITXINTRIN_H_INCLUDED -D__USE_XOPEN2K8 -I/Users/xlla/git/xgboost/include -I/Users/xlla/git/xgboost/dmlc-core/include -I/Users/xlla/git/xgboost/rabit/include -I/Users/xlla/git/xgboost/cub -I/Users/xlla/git/xgboost/gputreeshap -I/Users/xlla/git/xgboost/build/dmlc-core/include -isystem=/usr/local/include -O3 -DNDEBUG --generate-code=arch=compute_61,code=[compute_61,sm_61] -Xcompiler=-fPIC --expt-extended-lambda --expt-relaxed-constexpr "-Xcompiler=-Xclang -fopenmp" -Xfatbin=-compress-all -lineinfo -std=c++14 -x cu -c /Users/xlla/git/xgboost/src/c_api/c_api.cu -o CMakeFiles/objxgboost.dir/c_api/c_api.cu.o
</pre>

**Comment by trivialfis** [comment]
The required CUDA version is 11.x for 1.6.1.
