### ISSUE TITLE
Error running in Java: /lib/xgboost4j.dll was not found inside JAR

### ISSUE THREAD

**Issue by jiacheliu3** [dmlc/xgboost#802]
Hi! 

Thanks for the great tool. I'm trying out xgboost for Kaggling but came across this problem with the demo.

I imported the projects as Existing Maven projects since I saw pom.xml. When running any of the classes an IOException occur saying I don't have the xgboost4j.dll. I found the dll nowhere in the package from git. May I know how I'm supposed to generate the dll and where to put it please?

I'm using windows so I can't run the sh or make commands. Just wondering if there is a solution without a kernel. Thanks!

**Comment by alaeddinms** [comment]
Hi, Have you managed to solve this problem? thanks.

**Comment by ZLSANG** [comment]
@jiacheliu3  Hi, did you solve it now? I met the same question as you do? If you  have solved it, please tell me how to do it. 
thanks!
