### ISSUE TITLE
`PkgResourcesDeprecationWarning` when importing library

### ISSUE THREAD

**Issue by brunoguindani** [dmlc/xgboost#8024]
I'm using the latest XGBoost version (1.6.1). After upgrading to Ubuntu 22.04, when importing the library, I obtain the following warnings:
```
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 1.16.0-unknown is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 2.22.1ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 0.1.43ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 1.1build1 is an invalid version and will not be supported in a future release
  warnings.warn(
```
Python version is 3.10.4. Updating XGBoost via PIP has no effect. (In case this is relevant, my Numpy and Scipy versions are 1.21.5 and 1.8.0 respectively.)

**Comment by trivialfis** [comment]
Closing as it's already fixed.

**Comment by SHAWZHANG360** [comment]
I  also have this problem.
my python:3.9.7   numpy:1.22.0   scipy:1.7.3
when i finsish install xgboost , "PkgResourcesDeprecationWarning: mpy is an invalid version and will not be supported in a future release"
