### ISSUE TITLE
Poor performance of XGBRegressor for xgboost version >1.0.2

### ISSUE THREAD

**Issue by wowhhh** [dmlc/xgboost#8033]
### Describe the bug
Hi. I used **XGBRegressor** in my program but I noticed that its memory increased when adopting higher versions of xgboost.
As shown in the following experiment results, this model performs best if we use xgboost<=1.0.2.

My question is that why does such a library version perform better? Are there any issues in newer versions?

The detailed information is as follows:

Memory | Version 
-- | --
130.74 | 1.5.1
130.13 |  1.4.2
127.14 |  1.3.3
102.06 |  1.2.1
102.26 |  1.1.1
62.39 |  1.0.2
62.293 |  0.90
### Steps/Code to Reproduce
[train.csv](https://github.com/dmlc/xgboost/files/8991904/train.csv)

```python
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import tracemalloc

train_data = pd.read_csv('train.csv', parse_dates=True, index_col=['date_time'])
from sklearn.model_selection import train_test_split

features = ['deg_C', 'relative_humidity', 'absolute_humidity', 'sensor_1', 'sensor_2', 'sensor_3', 'sensor_4', 'sensor_5']
labels = ['target_carbon_monoxide', 'target_benzene', 'target_nitrogen_oxides']

train_data = train_data.reindex(np.random.permutation(train_data.index))

X = train_data[features]
y = train_data[labels]

X_train, X_valid, y_train, y_valid = train_test_split(X, y)
from xgboost import XGBRegressor
tracemalloc.start()
model_nitrogen = XGBRegressor(n_estimators=500, max_depth=50, learning_rate=0.1)

model_nitrogen.fit(X_train, y_train['target_nitrogen_oxides'])
current, peak = tracemalloc.get_traced_memory()
print("Current memory usage is {",current /1024/1024,"}MB; Peak memory was :{",peak / 1024/1024,"}MB")
tracemalloc.stop()
# Validation predictions
predicted_nitrogen = model_nitrogen.predict(X_valid)
```
### Expected Results
Similar memory usage for the different XGBoost versions or better performance for higher XGBoost versions.
### Actual Results
According to the above experiment results, when the XGBoost version is higher than 1.0.2, the performance of the model is worse.
### Others
1: sklearn version is 1.0.1
2: I noticed that when changing max_depth to 3, the memory usage is stable in different versions.

**Comment by trivialfis** [comment]
max_depth=50 is too deep. In practice, we can't grow to this size as if the tree is dense then the number of nodes will exceed the size of `int32_t`. As for the memory usage, we started some optimization on CPU for better computation performance, which involves more caching and the use of double buffers, etc. These techniques cost memory usage.

**Comment by trivialfis** [comment]
Closing in favor of https://github.com/dmlc/xgboost/issues/7690 .
