### ISSUE TITLE
Xgboost 1.6.x predict proba bug

### ISSUE THREAD

**Issue by yinzhedfs** [dmlc/xgboost#8034]
Hello, I found that the probability of prediction is different between the **Xgboost 1.6.x** sklearn interface and the native interface(**model.predict_proba** and **model._Booster.predict**), and the probability distribution is also very different.

![image](https://user-images.githubusercontent.com/7501580/176142931-a38b9b27-3a51-4a13-a940-94acd71d792a.png)

![image](https://user-images.githubusercontent.com/7501580/176144052-80b5be27-07da-4797-87fa-87443db4cde5.png)

**Comment by trivialfis** [comment]
Could you please provide a reproducible example?

**Comment by trivialfis** [comment]
An initial guess, are you using early stopping?

**Comment by yinzhedfs** [comment]
> An initial guess, are you using early stopping?

Yes, I used early stopping. But without using early stopping, the sklearn_proba and native_proba are equal. I'm wondering why.

**Comment by trivialfis** [comment]
Apologies for the confusion. Sklearn interface uses the result from early stopping automatically by specifying the `iteration_range` in the `predict` function, while the native interface always uses the full model, and users have to specify the parameter manually.

**Comment by yinzhedfs** [comment]
> Apologies for the confusion. Sklearn interface uses the result from early stopping automatically by specifying the `iteration_range` in the `predict` function, while the native interface always uses the full model, and users have to specify the parameter manually.

Thanks, I tested the 0.90 version and also reproduced this problem. Will this problem be fixed and updated?

**Comment by trivialfis** [comment]
@yinzhedfs It's not exactly a problem. It's just the convention used in different interfaces, if we "fix" it by changing one of the interfaces to adopt the convention of the other one, it might be a very confusing breaking change. However, I agree that we should align the behavior across all interfaces: https://github.com/dmlc/xgboost/issues/8035 .
