### ISSUE TITLE
XGB on GPU 

### ISSUE THREAD

**Issue by VEZcoding** [dmlc/xgboost#8041]
Hey! I am writing because I am kind of confused about CPU and GPU. 

I want to use XGB on GPU but it is somewhat a 300x slower than on CPU. I made two classifiers: 
clf_XGB_gpu = xgb.XGBClassifier(n_estimators = 2000, predictor = 'gpu_predictor', tree_method = 'gpu_hist', gpu_id = 0, ntrheads = -1)
clf_XGB_cpu = xgb.XGBClassifier(n_estimators = 2500, use_label_encoder=False, n_jobs=-1)

I am using GridSearch funrtion with Scikit-learn 

grid_search = GridSearchCV(estimator=pipeline, param_grid=param_grid, cv=10, scoring=custom, verbose=3)

For CPU pipeline it takes 0.1s for 1 iteration of grid search 1/10, while for GPU it takes 3s, which is extensively slower. I was under assumption that GPU performance should be at least 4x4 faster.  When I check the GPU usage it says that its taking 1gb of memory on each GPU. 

Do I have anything wrong in the parameters?

**Comment by trivialfis** [comment]
Your dataset is probably too small. When we use GPU it usually means there are at least millions of samples. Otherwise the GPU might be starving.

**Comment by VEZcoding** [comment]
AH! Okay my data is 800x 5400 (at most), but I was told that GPU grid search would be a lot faster no matter the size of the data. I made it work somehow but I got the error "XGB not compiled with GPU support and I maybe solved this with https://github.com/conda-forge/xgboost-feedstock/issues/26 , but now it gives me AttributeError: 'XGBClassifier' object has no attribute 'gpu_id', which I don't know how to approach.

**Comment by VEZcoding** [comment]
Hey I fixed the gpu_id error, it was a problem in conda enviroment, had to install it with pip package. Now I made it work with all my GPUs (every GPU is using around 400mb of memory, but its still super slow. I am kind of not getting how the amount of sample a bottle neck in the process. Isn't GPU perfect for GRID search? because you can use a lot of cuda (like 1000) processors for each combination of the parameter?

**Comment by trivialfis** [comment]
Unfortunately, that's not how it works.

The nvidia-smi might show that the GPU is being utilized but it's not.  Feel free to take a look into the code.
