### ISSUE TITLE
Serializing Booster objects seems to forget 'best_ntree_limit' (python)

### ISSUE THREAD

**Issue by arranger1044** [dmlc/xgboost#805]
I've trained a `Booster` model in python, using a validation set and enabling early stopping.
While still in memory, I am able to access the attribute 'best_ntree_limit' indeed.
However, after I serialize the object with the method `save_model`to file, and then I try to load it back with:

    model = xgb.Booster(model_file=model_path)

an Exception is thrown when I try to access  'best_ntree_limit':

        131 
        132     if early_rounds > 0:
    --> 133         preds = model.predict(xgb_matrix, ntree_limit=model.best_ntree_limit)
        134     else:
        135         preds = model.predict(xgb_matrix)

    AttributeError: 'Booster' object has no attribute 'best_ntree_limit'

This does not happen while I am serializing/deserializing using python's `pickle`. Am I doing something wrong?

**Comment by tqchen** [comment]
This is expected behavior for current version, as best_ntree_limit is a language specific property that is not stored in the model object. And save_model saves an language invariant model that can be loaded by other languages

**Comment by arranger1044** [comment]
Thanks @tqchen, I guess it could be helpful to write it in the docs (maybe I missed it).

**Comment by tqchen** [comment]
Thanks for the suggestion. would you like to open a PR to add these information to the docs?

Thanks!

**Comment by cyfy** [comment]
you can get the "best_iteration" by using "bst.attributes()", then 
       bst.best_ntree_limit = (bst.best_iteration + 1) * num_parallel_tree

where bst equal your model
