### ISSUE TITLE
Official xgboost4j-spark API for Python and R

### ISSUE THREAD

**Issue by yvonne-by** [dmlc/xgboost#8053]
Just to double-check, is there an existed official xgboost4j-spark API that is still active and stable and can be used in Python (PySpark) and R environments? I know that there are two PRs https://github.com/dmlc/xgboost/pull/4656 and https://github.com/dmlc/xgboost/pull/5658 introduced how to make XGBoost support PySpark. I also noticed that https://github.com/dmlc/xgboost/pull/8020 initialize the integration on PySpark, which is still in draft. So in my understanding, the answer to my question is NO for both environments, and the publish time won't be in the near future (e.g. 3 months). Please correct me if I am wrong. Thanks.

**Comment by hcho3** [comment]
PySpark integration is still work in progress. You should watch #8020 for an initial version.
