### ISSUE TITLE
metric/auc.cc  BinaryPRAUC  error

### ISSUE THREAD

**Issue by fallbernana123456** [dmlc/xgboost#8056]
In file included from amalgamation/xgboost-all0.cc:17:0:
amalgamation/../src/metric/auc.cc: In function ‘std::tuple<double, double, double> xgboost::metric::BinaryPRAUC(xgboost::common::Span<const float, 18446744073709551615ul>, xgboost::linalg::VectorView<const float>, xgboost::common::OptionalWeights)’:
amalgamation/../src/metric/auc.cc:200:64: error: converting to ‘std::tuple<double, double, double>’ from initializer list would use explicit constructor ‘constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements = {float, float, float}; <template-parameter-2-2> = void; _Elements = {double, double, double}]’
     return {1.0f, 1.0f, std::numeric_limits<float>::quiet_NaN()};
                                                                ^
git clone  https://github.com/dmlc/xgboost.git
git submodule update --recursive
make -j4

gcc 5.2
cmake-3.24

**Comment by trivialfis** [comment]
Hi, do you have access to a newer version of gcc? On our CI GCC 8.4.0 is used.

**Comment by fallbernana123456** [comment]
I try gcc 12.1.0, The error no longer appears，  but  cannot stat ‘/opt/software/AnyQ-master/build/third_party/xgboost/src/xgboost/lib/*’: No such file or directory
 I try gcc 8.4.0

**Comment by trivialfis** [comment]
I don't know what's the software environment on your machine. Could you please post the complete log?

**Comment by fallbernana123456** [comment]
git submodule update --recursive
cd dmlc-core ;  make; 
libdmlc.a  is fail
cd dmlc-core ; mkdir build ; cd build ; cmake .. ;make -j4 
libdmlc.a  is ok
cd rabit ;make 
rabit/lib/librabit.so is fail
git clone https://github.com/dmlc/rabit.git
cd rabit ;make 
rabit/lib/librabit.so is ok

**Comment by fallbernana123456** [comment]
> I don't know what's the software environment on your machine. Could you please post the complete log?
log had delete.
later i will try on  gcc 12.1.0  and post the log to you
