### ISSUE TITLE
Enable two-factor authentication on PyPI release pipeline

### ISSUE THREAD

**Issue by phunterlau** [dmlc/xgboost#8058]
Recently `PyPI` starts to require two-factor authentication for certain `critical` projects for security reasons and `xgboost` is one of them.  Besides feeling glad on the impact of many projects, I am wondering if this two-factor authentication can be incorporated in the `PyPI` release pipeline as early. `PyPI` has provided hardware security keys http://pypi.org/security-key-giveaway/  but we need to figure out if we want a hardware key for corresponding personnel. The `PyPI` help page has some alternative solution and this one requires software-only https://pypi.org/help/#totp Thanks.

**Comment by trivialfis** [comment]
Thank you for the notice. I'm not in the eligible regions for USB key but I have enabled 2FO on my account using software solution.  @hcho3 @RAMitchell you might need to enable this as well in case I'm not around for submitting pypi packages.

@phunterlau Could you please share the pypi test account with us?

**Comment by hcho3** [comment]
I am using Authy to enable 2FA on my myPI account.

**Comment by phunterlau** [comment]
The `PyPI` maintainer list shows @hcho3 has enabled 2FA and the release pipeline seems fine. I think we can close this issue for now. Please let me know if any problems. Thanks.

**Comment by trivialfis** [comment]
@phunterlau Thank you for checking the current status.  @hcho3 and I help maintain the pypi package during release and it would be great to have access to the test account https://test.pypi.org/project/xgboost/ . Can we chat offline about the current status of that account when you are available? You can reach me by email jm.yuan@outlook.com

**Comment by phunterlau** [comment]
@trivialfis Sounds good. I just sent the Test PyPI invitation to your `PyPI` . @hcho3 's PyPI email was not verified so I can't send now.
