### ISSUE TITLE
Question: When python API `xgboost.DMatrix` `data` argument is a libsvm file path, how to specify the number of features ?

### ISSUE THREAD

**Issue by WeichenXu123** [dmlc/xgboost#8062]
Question: When DMatrix data argument is a libsvm file path, how to specify the number of features ?
Thank you.

**Comment by WeichenXu123** [comment]
CC @trivialfis Thanks!

**Comment by WeichenXu123** [comment]
Do we need to set `num_feature` param additionally in this case ?

**Comment by WeichenXu123** [comment]
@trivialfis 
> The number of features is guessed from the data.

This might cause issue when the end features values in all rows are zero.
and suppose we split the training worker into multiple parts in distributed training, then each part DMatrix might infer different num_feature .

**Comment by trivialfis** [comment]
Let's not use the file parser if possible. Since we are integrating with data processing libraries and frameworks like pyspark, I think eventually XGBoost will remove the parser entirely and focus on machine learning instead. (others might disagree, but I think the parser is really out of scope for XGBoost).

**Comment by WeichenXu123** [comment]
@trivialfis 

OK.
How to use the DMatrix iteration input API without the file parser ？

**Comment by trivialfis** [comment]
Maybe this demo can help: https://github.com/dmlc/xgboost/blob/0bdaca25cae7ef8e12c85f032dea7ec4f0269552/demo/guide-python/external_memory.py#L37 

I will work on the data input after the initial pyspark PR. Could you please wait for a bit while for the external memory support? (or I can work on it).

**Comment by WeichenXu123** [comment]
> Maybe this demo can help:
> 
> https://github.com/dmlc/xgboost/blob/0bdaca25cae7ef8e12c85f032dea7ec4f0269552/demo/guide-python/external_memory.py#L37
> 
> I will work on the data input after the initial pyspark PR. Could you please wait a bit for the external memory support? (or I can work on it).

Appreciate your help on data iterator / external memory support !

But according to the demo, https://github.com/dmlc/xgboost/blob/0bdaca25cae7ef8e12c85f032dea7ec4f0269552/demo/guide-python/external_memory.py#L37
It still requires file (libsvm or csv format ) as input ?

**Comment by trivialfis** [comment]
You can define the iterator however you like, just return the batches in the `next` function, whether the batch is loaded from a file or fetched from a remote cluster is orthogonal to XGBoost.

**Comment by WeichenXu123** [comment]
> You can define the iterator however you like, just return the batches in the `next` function, whether the batch is loaded from a file or fetched from a remote cluster is orthogonal to XGBoost.

Understood. Thank you.
