### ISSUE TITLE
Scores mismatch in multiple runs

### ISSUE THREAD

**Issue by anmolsinghal28** [dmlc/xgboost#8075]
I am using a pipeline based on xgboost4j- spark 0.90 version with spark 2.4.1 and trying to train a classification model. With the same data and same parameter config along with a seed value as well i am getting slightly deviating results for each run that i do. Is this the expected behaviour?

**Comment by trivialfis** [comment]
Please upgrade to the latest XGBoost. If the issue persists with the latest version please share a reproducible example. Thank you!
