### ISSUE TITLE
rabit.a not found, win64, py27

### ISSUE THREAD

**Issue by rohan-11** [dmlc/xgboost#808]
Hi,

This is regarding the installation process.

I am sort of stuck in the last step to build xgboost target, but i keep stumbling on this error:

> g++: error: rabit/lib/librabit.a: No such file or directory

I tried making in root of rabit, but that gives an error:

>  error: 'inet_ntop' was not declared in this scope

Any help would be much appreciated.

**Comment by tqchen** [comment]
Follow instruction here http://xgboost.readthedocs.org/en/latest/build.html#building-on-windows
