### ISSUE TITLE
Apply dmatrix iteration iterface in PySpark xgboost and support external memory mode

### ISSUE THREAD

**Issue by WeichenXu123** [dmlc/xgboost#8083]
Apply dmatrix iteration iterface in PySpark xgboost and support external memory mode.

**Comment by WeichenXu123** [comment]
@trivialfis When will you create first PR "Apply dmatrix iteration iterface in PySpark xgboost " ? If you are busy, I can help to create PR. Thank you.

**Comment by trivialfis** [comment]
@WeichenXu123 Thank you for the work. Feel free to continue the work on external memory. I just didn't want to have too many conflicts between the implementation of ext memory and the quantile dmatrix. (See the WIP iterator in https://github.com/dmlc/xgboost/pull/8088 ).

**Comment by WeichenXu123** [comment]
@trivialfis To reduce conflicts, I would like to wait https://github.com/dmlc/xgboost/pull/8088 merged first. :)

**Comment by trivialfis** [comment]
I need to apply the quantile dmatrix to spark as well.

**Comment by trivialfis** [comment]
I agree. I kept the feature here mostly for experimental support.

**Comment by trivialfis** [comment]
But quantile DMatrix can still be used for reducing memory usage without sacrificing performance.
