### ISSUE TITLE
ERROR DURING PREDICTION - Invalid missing value: null

### ISSUE THREAD

**Issue by kishoremarodia** [dmlc/xgboost#8089]
**Command**: y_pred = regressor.predict(df_Test)

**Output**:
XGBoostError                              Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_26796/2506740906.py in <module>
----> 1 y_pred = regressor.predict(df_Test)
      2 sns.heatmap(df_Test.isnull(),yticklabels=False,cbar=False)

C:\ProgramData\Miniconda3\lib\site-packages\xgboost\sklearn.py in predict(self, X, output_margin, ntree_limit, validate_features, base_margin, iteration_range)
   1047         if self._can_use_inplace_predict():
   1048             try:
-> 1049                 predts = self.get_booster().inplace_predict(
   1050                     data=X,
   1051                     iteration_range=iteration_range,

C:\ProgramData\Miniconda3\lib\site-packages\xgboost\core.py in inplace_predict(self, data, iteration_range, predict_type, missing, validate_features, base_margin, strict_shape)
   2100             from .data import _ensure_np_dtype
   2101             data, _ = _ensure_np_dtype(data, data.dtype)
-> 2102             _check_call(
   2103                 _LIB.XGBoosterPredictFromDense(
   2104                     self.handle,

C:\ProgramData\Miniconda3\lib\site-packages\xgboost\core.py in _check_call(ret)
    201     """
    202     if ret != 0:
--> 203         raise XGBoostError(py_str(_LIB.XGBGetLastError()))
    204 
    205 

**XGBoostError: [16:08:05] c:\\administrator\workspace\xgboost-win64_release_1.6.0\src\c_api\c_api_utils.h:159: Invalid missing value: null**

**REmarks**
Please note - All categorical values were transformed, null were imputed for training the model. RandomizedSearchCV was used for hyper paremeter tuning

**Comment by trivialfis** [comment]
Hi, could you please share what is the value of `regressor.missing`?

**Comment by trivialfis** [comment]
@kishoremarodia Please use `np.nan` instead of null for missing values (in data and for parameter).

**Comment by kishoremarodia** [comment]
In my training and testing data, there are 0 nulls, all were taken care as part of data cleansing. I used RANDOMSEARCHCV to come up with best parameters and then used that to FIT the model. But when m using the model to predict values from test data, coming up with this issue

**Comment by kishoremarodia** [comment]
> 

Issue resolved after using np.nan in HYPERPARAMETER. Somehow i made nan as None. Thanks for help.

**Comment by kishoremarodia** [comment]
Issue resolved after using np.nan in HYPERPARAMETER. Somehow i made nan as None. Thanks for help.
