### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [dmlc/xgboost#81]
[An extra null pointer check is not needed in functions](http://dietmar-kuehl.de/mirror/c++-faq/freestore-mgmt.html#faq-16.8 "Do I need to check for NULL before delete p?") like the following.
* [BoostLearner](https://github.com/tqchen/xgboost/blob/103c59434365c210283af1cc3c22261a6ecaa85c/src/learner/learner-inl.hpp#L34 "Destructor for BoostLearner")
* [BoostLearnTask](https://github.com/tqchen/xgboost/blob/caa068f82083047ea5bb4779146035c4f8a2e61e/src/xgboost_main.cpp#L94 "Destructor for BoostLearnTask")
* [FMatrixS](https://github.com/tqchen/xgboost/blob/cb2f2ca29dec516ad19bb2e74cece0d6289a3356/src/io/simple_fmatrix-inl.hpp#L26 "Destructor for FMatrixS")

**Comment by tqchen** [comment]
Since this do not have things to do with correctness, and explicit check was not too bad for readable purpose(hinting that we expect NULL ptr). I am closing this issue for now.

**Comment by elfring** [comment]
Would it be nice to [improve efficiency](http://en.cppreference.com/w/cpp/language/delete "Reconsider usage of 'delete'?") also for this software here?

**Comment by tqchen** [comment]
In our case, most of delete happens very infrequently (one class per usage of training). I agree that if this happens very frequently considering remove it will help. Thanks
