### ISSUE TITLE
parametr as array

### ISSUE THREAD

**Issue by gugatr0n1c** [dmlc/xgboost#810]
Hi,

I did parameters hyper tuning and found optimal setting for my dataset:

eta: 0.002
max_depth: 9
subsample: 70
...

Then I did as follows:
for each tree I generated from uniform distribution unique setting of parameters like:
eta from [0.0015, 0.0025] -> 0.0023
max_depth [8, 10] -> 10
subsamble [55, 85] -> 56
..
so each tree can be unique in this sence...but all very close to hypertuned values...

Can be possible to set instead of scalar, which is fixed for every tree, array of values and than for each tree just take value from array?
(Than we can plug-in pre-generated arrays of values for each parameter).

On my dataset this improved accuracy of final model..  speed is same (some trees are bigger, some trees are smaller)..

Actually now I am doing next experiment... trying to even change booster.. and results are promising as well... (running 3000 epoches... 2500 are trees, 500 gblinear - randomly chosen)... model is faster and more accurate (20 percent of regression do some time saving). Or even cost function (I do not tried this, because MAE is not supporting yet for regression).

Thanx for consideration...

**Comment by pommedeterresautee** [comment]
Old question, no answer, closing
