### ISSUE TITLE
Xgboost pyspark: Support pyspark Sparse Vector

### ISSUE THREAD

**Issue by WeichenXu123** [dmlc/xgboost#8108]
Xgboost pyspark: Support pyspark Sparse Vector

**Comment by WeichenXu123** [comment]
@trivialfis 

@xiangrui hope xgboost 2.0 can support this on databricks. 
The feature requires a `unwrap_udt` API which now only available on databricks.
Can we add this feature now ? I will checking whether it is on databricks environment and if yes  then imports the databricks-specific `unwrap_udt` function.

Btw, when apache/spark 3.4 comes out, `unwrap_udt` API will be added and then apache/spark can also support this feature.

**Comment by WeichenXu123** [comment]
@trivialfis

> Can we add this feature now ? In the code it can check whether it is on databricks environment and if yes then import the databricks-specific unwrap_udt function.

What do you think ?

**Comment by trivialfis** [comment]
https://github.com/dmlc/xgboost/issues/8108#issuecomment-1192705836 sounds good

**Comment by trivialfis** [comment]
hi @WeichenXu123 is it possible for us to use `mapInArrow` instead of `mapInPandas`? What's the current status of the API and does it support device memory? https://arrow.apache.org/docs/cpp/memory.html#devices

**Comment by WeichenXu123** [comment]
> hi @WeichenXu123 is it possible for us to use `mapInArrow` instead of `mapInPandas`? What's the current status of the API and does it support device memory? https://arrow.apache.org/docs/cpp/memory.html#devices

CC @hyukjin.kwon

**Comment by WeichenXu123** [comment]
Got reply from @HyukjinKwon:

> 
it should support
although nobody tested it
because it exposes the native PyArrow batch instances
if that supports, it should work

We can try it as a follow-up optimization.



[6:26](https://databricks.slack.com/archives/DJ0AR42B1/p1660213594575069)
because it exposes the native PyArrow batch instances
[6:26](https://databricks.slack.com/archives/DJ0AR42B1/p1660213600313039)
if that supports, it should work




[6:26](https://databricks.slack.com/archives/DJ0AR42B1/p1660213594575069)
because it exposes the native PyArrow batch instances
[6:26](https://databricks.slack.com/archives/DJ0AR42B1/p1660213600313039)
if that supports, it should work
