### ISSUE TITLE
Xgboost spark: Support XGBRanker

### ISSUE THREAD

**Issue by WeichenXu123** [dmlc/xgboost#8110]
Xgboost spark: Support XGBRanker

**Comment by WeichenXu123** [comment]
@trivialfis @wbo4958 Do you have time to add this feature ? :)

**Comment by WeichenXu123** [comment]
@wbo4958 Do you have time to implement this feature ? @mengxr hopes this feature to go into xgboost 2.0.
Thanks!

**Comment by wbo4958** [comment]
Hi @WeichenXu123,  I am pretty busy recently. I can't guarantee that I can make it in xgboost 2.0

**Comment by WeichenXu123** [comment]
@dbczumar Heads-up: I might need to spend some additional time to work on this because of above reason. :)

**Comment by WeichenXu123** [comment]
@trivialfis I have a question, in XGBRanker distributed training, shall we ensure each group training examples being put in the same worker data split ?

**Comment by trivialfis** [comment]
Apologies for missing the thread.

>  And does training examples need to be sorted by "qid" first ?

yes.

> shall we ensure each group training examples being put in the same worker data split

No

**Comment by wbo4958** [comment]
@WeichenXu123 @trivialfis Sorry, I didn't see https://github.com/dmlc/xgboost/pull/8172 has sorted the qid first? please correct me.

**Comment by trivialfis** [comment]
Users can have it sorted. Otherwise there will be an error in c++.

**Comment by silpara** [comment]
I don't see any documentation but SparkXGBRanker class is implemented at https://github.com/dmlc/xgboost/blob/master/python-package/xgboost/spark/estimator.py. Is it ready for use?

**Comment by trivialfis** [comment]
Opened a PR for the doc https://github.com/dmlc/xgboost/pull/8692 .

It's currently experimental.
