### ISSUE TITLE
Why use GraphViz rather than a pip-installable library?

### ISSUE THREAD

**Issue by jorislimonier** [dmlc/xgboost#8119]
Why use GraphViz rather than a pip-installable library?

The company I work for uses a firewall, which makes installing Graphviz quite a hustle. I need to contact the helpdesk, ask for admin validation in order to install [GraphViz](https://graphviz.org/).

It is my understanding that GraphViz is an external software, that is not installable with pip, but I would be happy to be corrected on that.

Thank you for your time.

**Comment by hcho3** [comment]
Do you have a recommendation for an alternative? Feel free to submit a pull request to use another software for the visualization.

**Comment by hcho3** [comment]
@jorislimonier Does your company allow the use of Conda? You can install Graphviz easily with
```
conda install -c conda-forge graphviz python-graphviz
```

**Comment by jorislimonier** [comment]
> @jorislimonier Does your company allow the use of Conda? 

Yes, that would probably do, although it is less convenient to have to install Conda specifically for one visualization of one package.

> Do you have a recommendation for an alternative?

No, I don't have the bandwidth to develop an easy-to-use alternative unfortunately. Graphviz it is
