### ISSUE TITLE
Prediction with individual trees under random forest mode

### ISSUE THREAD

**Issue by ZiyueXu77** [dmlc/xgboost#8120]
I am testing the random forest mode (num_parallel_tree > 1) and trying to figure out how exactly the voting part works. But there seems to be some issue with my code in extracting individual trees and doing inference with them.
The issue being:
With the suggested "slice: xgb.Booster = bst[tree_num]", I am not able to get a single tree from the forest, because in this case, the index correspond to the entire forest and will cause error "IndexError: Layer index out of range".
So I created another param with "num_parallel_tree = 1" and reload the mode under this setting. This time it seems I am able to load the individual trees, but the prediction result looks strange (the numbers do not align - two trees RF for binary classification under 'binary:logistic' objective):
RF prediction [0.8286496  0.33924362 0.6791787  0.6545023  0.26696008]
Tree 0 prediction [0.6791787 0.4722508 0.6791787 0.6791787 0.3882806]
Tree 1 prediction [0.6955269  0.36457646 0.5        0.4722508  0.36457646]
Theoretically, the RF predication probability should be between Tree 0 and 1 if using soft voting (just from "correctness" point of view, though bagging may not help logistic regression much)  
I wonder if I made any mistakes and what's the correct way of using the trees in such scenario?

**Comment by ZiyueXu77** [comment]
I think I figured it out: the soft voting is not on the predicted probability value, but on the margin, then the probability will be calculated via sigmoid. In this way, the random forest bagging process will be (almost - margin pre-divided by num_parallel_tree) identical to boosting ("sum of margins"), and hence easier for calculation.
It will be best if someone can confirm this.

**Comment by trivialfis** [comment]
I think you are right.
