### ISSUE TITLE
Is there a reason why libxgboost.a is output to the source directory?

### ISSUE THREAD

**Issue by negatratoron** [dmlc/xgboost#8122]
It's done on this line: https://github.com/dmlc/xgboost/blob/master/CMakeLists.txt#L252

That's confusing to me.  I noticed this while trying to pull both XGBoost and another project dependent on it into a superproject using `FetchContent` for XGBoost and `ExternalProject_Add` for the other project (which does not use CMake).  I have given `ExternalProject_Add` the build command:

    BUILD_COMMAND ${CMAKE_COMMAND} -E env "CXXFLAGS=-I${xgboost_SOURCE_DIR}/include" "LDFLAGS=-L${xgboost_BINARY_DIR}/dmlc-core\ -L${xgboost_SOURCE_DIR}/lib" $(MAKE)

to call `make` directly on the other project and give it environment variables so that it can find `libxgboost.a` and `libdmlc.a`.  It works, I'm just wondering if you currently think outputting the static library to the source directory is correct.

Thanks!

**Comment by trivialfis** [comment]
Just a convention in XGBoost that we put the shared libraries in that directory for easy packaging with other language bindings.

You can always run cmake install to put the library else where.
