### ISSUE TITLE
Usage question: how to force saved model to use GPU for predictions?

### ISSUE THREAD

**Issue by asheetal** [dmlc/xgboost#8124]
I trained an xgboost model using GPU (I verified using nvidia-smi)
I then saved it to disk as a pickle file

Later I load the pickle model to  query and make predictions. But now it always uses CPU. How do I make use of GPU for a pre-saved model build on GPU?

**Comment by trivialfis** [comment]
For now, you can set the parameter `predictor` to `gpu_predictor`. (we might change that after 2.0, but this should unblock your work).

**Comment by asheetal** [comment]
I am using the github version 2.0.0.dev. Seems this did not really make any difference
```
xgb_model_from_disk.predictor = 'gpu_predictor'
```

**Comment by trivialfis** [comment]
Are you using the scikit learn interface? If so, then you need to call the `set_params` method

**Comment by asheetal** [comment]
Yes scikit interface. If I use set_params. I get a different error
```
xgb_model_from_disk = pickle.load(open(outputfilename, "rb"))
xgb_model_from_disk.set_param({"predictor": "gpu_predictor"})
```
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [8], in <cell line: 2>()
      1 #xgb_model_from_disk.predictor = "gpu_predictor"
----> 2 xgb_model_from_disk.set_param({"predictor": "gpu_predictor"})

AttributeError: 'XGBClassifier' object has no attribute 'set_param'
```

**Comment by trivialfis** [comment]
`set_params` vs `set_param`.  It's a standard scikit-learn function. To set the predictor: `model.set_params(predictor="gpu_predictor")`

**Comment by asheetal** [comment]
Thank you so much. This helped. I can now see GPU utilization on predict
