### ISSUE TITLE
Troubles with building xgboost package for Python on Windows

### ISSUE THREAD

**Issue by mehdiBarch** [dmlc/xgboost#814]
Hello

I have problems to install Python xgboost package on Windows.
I guess I have followed all the instructions but here is what I get:

C:\Users\Mehdi\xgboost>make -j4
Un sous-répertoire ou un fichier -p existe déjà.
Une erreur s'est produite lors du traitement de : -p.
Un sous-répertoire ou un fichier build existe déjà.
Une erreur s'est produite lors du traitement de : build.
g++ -m64 -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iincl
ude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -MM
 -MT build/learner.o src/learner.cc >build/learner.d
La syntaxe de la commande n'est pas correcte.
Makefile:97: recipe for target 'build/logging.o' failed
make: *** [build/logging.o] Error 1
make: *** Waiting for unfinished jobs....
Makefile:97: recipe for target 'build/common/common.o' failed
make: *** [build/common/common.o] Error 1
g++ -m64 -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Ii
nclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp
-c src/learner.cc -o build/learner.o
In file included from dmlc-core/include/dmlc/registry.h:14:0,
                 from include/xgboost/./gbm.h:11,
                 from include/xgboost/learner.h:16,
                 from src/learner.cc:7:
dmlc-core/include/dmlc/./parameter.h:254:43: warning: 'xgboost::__make__LearnerM
odelParamParamManager__' defined but not used [-Wunused-variable]
   static ::dmlc::parameter::ParamManager &__make__ ## PType ## ParamManager__ =
 \
                                           ^
src/learner.cc:102:1: note: in expansion of macro 'DMLC_REGISTER_PARAMETER'
 DMLC_REGISTER_PARAMETER(LearnerModelParam);
 ^
dmlc-core/include/dmlc/./parameter.h:254:43: warning: 'xgboost::__make__LearnerT
rainParamParamManager__' defined but not used [-Wunused-variable]
   static ::dmlc::parameter::ParamManager &__make__ ## PType ## ParamManager__ =
 \
                                           ^
src/learner.cc:103:1: note: in expansion of macro 'DMLC_REGISTER_PARAMETER'
 DMLC_REGISTER_PARAMETER(LearnerTrainParam);

Anay idea on what I have done wrong?

Thanks

**Comment by KaneMerrillR** [comment]
Will you please tell me what fixed this? I am getting the same error.

**Comment by thirdwing** [comment]
This is due to some commands in Windows is not compatible with Linux, like `mkdir`.

Please follow the new building instructions in https://github.com/dmlc/xgboost/blob/master/doc/build.md#building-on-windows

To avoid similar problems, we suggest using a bash on Windows.

**Comment by mehdiBarch** [comment]
I agree, mkdir command launched from Windows prompt (when executing 'make') does not work.
I finally started over with installing MSYS2.
From MSYS2 prompt I installed mingw (using 'pacman -S' command).
Then I followed the instructions to build xgboot:
- Clone from github repository
- Copy config.mk file
...
- Add the repository where to find 'Make' to the system PATH 
If the command 'Make' has another name then use an alias.

Execute command 'make' in MSYS2 prompt or mingw prompt (I do not remember). This time it should be fine and  will create xgboost.exe at the root repository ../xgboost

Finally, you have to go to python-package folder and execute the last instructions.

Hope this will be ok for you.

**Comment by KaneMerrillR** [comment]
Thanks guys. I will keep trying. I think the problem has more to do with limited knowledge on my part than anything else.

**Comment by KaneMerrillR** [comment]
Thanks for the help guys. I have MSYS2 installed, was able to run make but I get the following error when trying to run the python setup after make runs:

$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools

Any thoughts or help you could provide would be greatly appreciated.

**Comment by mehdiBarch** [comment]
I had the same problem. It comes from the fact that you have two distinct 'python.exe'.
At this step, you need to remove from System PATH the path to the command 'make' you had previously.
Setuptools should already be installed on your 'usual' Python version (Anaconda?) and it should work.
The problem  one in Anaconda and another one that has been installed with mingw I suppose.

**Comment by KaneMerrillR** [comment]
I am using Anaconda, now I get this error:
$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 19, in <module>
    LIB_PATH = libpath['find_lib_path']()
  File "xgboost/libpath.py", line 44, in find_lib_path
    'List of candidates:\n' + ('\n'.join(dll_path)))
XGBoostLibraryNotFound: Cannot find XGBoost Libarary in the candicate path, did you install compilers and run build.sh in root path?
List of candidates:
C:\Users\kmerrill\xgboost\python-package\xgboost\libxgboost.dll
C:\Users\kmerrill\xgboost\python-package\xgboost\../../lib/libxgboost.dll
C:\Users\kmerrill\xgboost\python-package\xgboost\./lib/libxgboost.dll
C:\Users\kmerrill\xgboost\python-package\xgboost\../../windows/x64/Release/libxgboost.dll
C:\Users\kmerrill\xgboost\python-package\xgboost\./windows/x64/Release/libxgboost.dll


Did I mess up the make step?

**Comment by mehdiBarch** [comment]
I had this kind of issue too but not when I reinstalled using MSYS prompt. I actually do not know what fixed this. Do you have xgboost.exe in the repository /xgboost? If not it means the 'make' command did not succeed

**Comment by KaneMerrillR** [comment]
Yea, my make just seems to be building a couple of files in the build folder (cli_main.d and cli_main.o) but not creating a .exe. I will try to find someone who I can give access to my computer to, to try and help me figure this out I don't need to keep bugging you. Thanks guys.
