### ISSUE TITLE
Optional NCCL installation for PyPi wheel

### ISSUE THREAD

**Issue by trivialfis** [dmlc/xgboost#8140]
Hi all, the XGBoost binary wheel size recently [exceeded](https://xgboost-ci.net/blue/organizations/jenkins/xgboost/detail/master/49/pipeline/) 200MB limit set by PyPi. I propose we remove the static linking of NCCL in our binary wheel to reduce the size.  https://github.com/dmlc/xgboost/pull/7930 helped enable training distributed GPU without NCCL and as a result, XGBoost can work on MNMG without NCCL, albeit might suffer some performance loss. We can optionally emit a warning for users to install NCCL as a runtime dependency and `dlopen` the shared object when it's needed.

## Alternative

- Compile our own nccl with a smaller set of supported archs.  I removed the `sm_35` and `sm_50` from NCCL build, the striped static library is of size `190M	build/lib/libnccl_static.a`. I'm not sure if this can actually help in the long term.
- Reduce the number of GPU archs supported by XGBoost.
- Maybe submit a feature request for nccl to share a binary wheel on PyPi?

Related: https://github.com/cupy/cupy/issues/4850

**Comment by trivialfis** [comment]
cc @RAMitchell @hcho3

**Comment by hcho3** [comment]
Why is this closed?

**Comment by trivialfis** [comment]
@RAMitchell worries that the performance hit might be too much and a simple warning is not sufficient for asking users to install nccl (which is indeed not an easy task for pip users).

**Comment by trivialfis** [comment]
We will have to find other options.
