### ISSUE TITLE
TypeError: type object argument after ** must be a mapping, not tuple

### ISSUE THREAD

**Issue by PolarSprings** [dmlc/xgboost#8177]
TypeError Traceback (most recent call last)
in
6 },
7
----> 8 clf = xgb.XGBRegressor(**param_grid)

TypeError: type object argument after ** must be a mapping, not tuple

Code is as follows:

```
param_grid={
    'max_depth':5,
    'eta':0.1,
    'gamma':0,
    'min_child_weight':10
},

clf = xgb.XGBRegressor(**param_grid)
```

I am passing the params as a dictionary with **, why does it throw the error?

**Comment by trivialfis** [comment]
Removing the `,` after the definition of `param_grid` should solve the issue.
