### ISSUE TITLE
sparkxgb turn to python package xgboost can load

### ISSUE THREAD

**Issue by BoostMom** [dmlc/xgboost#8182]
I use sparkxgb and xgboost4j-spark-0.90.jar trained a model in spark environment.

Now I need to deploy a server in python for xgboost model inference. I wonder if there is a method I can just use the trained model by sparkxgb or I have to retrain the model by python xgboost package.

Thanks all kind reply~~

Now I used python xgboost==1.16.1 load the model it raize error!
Traceback (most recent call last):
  File "/Users/shujuanzhao/Documents/2022proj/qd_dm_proj/canton_fair/gjh_search_svr/search/qu/xgboost_inference.py", line 5, in <module>
    bst.load_model('../model/test_save_model')  # load data
  File "/anaconda3/lib/python3.9/site-packages/xgboost/core.py", line 2249, in load_model
    _check_call(_LIB.XGBoosterLoadModel(
  File "/anaconda3/lib/python3.9/site-packages/xgboost/core.py", line 203, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: [17:09:18] /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-3.7/xgboost/src/learner.cc:866: Check failed: fi->Read(&mparam_, sizeof(mparam_)) == sizeof(mparam_) (0 vs. 136) : BoostLearner: wrong model format
Stack trace:
  [bt] (0) 1   libxgboost.dylib                    0x0000000132296845 dmlc::LogMessageFatal::~LogMessageFatal() + 117
  [bt] (1) 2   libxgboost.dylib                    0x000000013236d574 xgboost::LearnerIO::LoadModel(dmlc::Stream*) + 2052
  [bt] (2) 3   libxgboost.dylib                    0x000000013229f766 XGBoosterLoadModel + 694
  [bt] (3) 4   libffi.7.dylib                      0x000000010b397ead ffi_call_unix64 + 85
  [bt] (4) 5   ???                                 0x0000000305926a10 0x0 + 12978383376

**Comment by wbo4958** [comment]
@BoostMom, The model trained by XGBoost-JVM-Spark before 1.6.1 can't be loaded directly by XGBoost Python package. If you really would like to do that, you can

``` scala
val nativeModelPath = "/tmp/nativeModel"
xgbClassificationModel.nativeBooster.saveModel(nativeModelPath)
```
