### ISSUE TITLE
GPU errors during multiple Optuna trials

### ISSUE THREAD

**Issue by cmunch1** [dmlc/xgboost#8198]
I keep getting XGB GPU errors after a few Optuna trials. I tried my code in Windows, Ubuntu, and on Paperspace Gradient, with various GPUs, and same results.

So I tried a public notebook on Kaggle that apparently worked in the past (and unrelated to my data), and it appears to trigger the same errors after a few trials:
https://www.kaggle.com/code/tunguz/tps-mar-2021-xgb-gpu-le-optuna

**Comment by trivialfis** [comment]
Could you please share the version of xgboost and optuna?

**Comment by trivialfis** [comment]
also, could you please share the error trace? I'm running the notebook right now, but haven't seen the error yet.

**Comment by trivialfis** [comment]
Ah, could you please limit the max_depth to 29?  With 1.6.2, this can be 30. Fixed in https://github.com/dmlc/xgboost/pull/8098 .
