### ISSUE TITLE
I MEETING A PROBLEM:

### ISSUE THREAD

**Issue by trianbin** [dmlc/xgboost#8205]
Parameters: { "scoring" } might not be used.

  This could be a false alarm, with some parameters getting used by language bindings but
  then being mistakenly passed down to XGBoost core, or some parameter actually being used
  but getting flagged wrongly here. Please open an issue if you find any such cases.

**Comment by trivialfis** [comment]
There's no parameter named "scoring" in xgboost. Please visit the documentation page for a complete set of parameters.
