### ISSUE TITLE
ERROR: No matching distribution found for xgboost==1.6.1 for python 3.6

### ISSUE THREAD

**Issue by yanirmr** [dmlc/xgboost#8207]
Hi,

I tried to run collect xgboost==1.6.1 in the Ubunto environment of Python 3.6 (of Github action).

I run the lines:
         `python -m pip install --upgrade pip`
          `pip install -r requirements.txt`
          `pip install -e .`

The requirements include the xgboost==1.6.1.

As a result, I received traceback as follows:

`python -m pip install --upgrade pip`
`Requirement already satisfied: pip in /opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages (21.3.1)`
`ERROR: Could not find a version that satisfies the requirement xgboost==1.6.1 (from versions: 0.4a12, 0.4a13, 0.4a14, 0.4a15, 0.4a18, 0.4a19, 0.4a20, 0.4a21, 0.4a22, 0.4a23, 0.4a24, 0.4a25, 0.4a26, 0.4a27, 0.4a28, 0.4a29, 0.4a30, 0.6a1, 0.6a2, 0.7.post3, 0.7.post4, 0.71, 0.72.1, 0.80, 0.81, 0.82, 0.90, 1.0.0rc1, 1.0.0rc2, 1.0.0, 1.0.1, 1.0.2, 1.1.0rc1, 1.1.0rc2, 1.1.0, 1.1.1, 1.2.0rc1, 1.2.0rc2, 1.2.0, 1.2.1rc1, 1.2.1, 1.3.0rc1, 1.3.0.post0, 1.3.1, 1.3.2, 1.3.3, 1.4.0rc1, 1.4.0, 1.4.1, 1.4.2, 1.5.0rc1, 1.5.0, 1.5.1, 1.5.2)
ERROR: No matching distribution found for xgboost==1.6.1`
`

**Comment by hcho3** [comment]
XGBoost 1.6.1 does not support Python 3.6. We require Python 3.7+.
