### ISSUE TITLE
Compilation error from git - same as issue #797

### ISSUE THREAD

**Issue by vykhand** [dmlc/xgboost#821]
Dear all,

I got the same issue as #797 ? Does anyone know how to resolve it?

I got it on 3 separate machines, Win7 x64, centos x64, and ubuntu 14  server x64, when installing from my own git(vykhand/xgboost) and from dmlc as well. I fetched changes to my own git just now and tested it again. No luck. 
Here are the commands I am running :

![image](https://cloud.githubusercontent.com/assets/498481/12989686/a22f2d38-d106-11e5-9389-dd9a1876551e.png)

Here is the error message :
![image](https://cloud.githubusercontent.com/assets/498481/12989567/54b96438-d106-11e5-9d2e-6db598a64f5d.png)

Drat installation works. But would like to install form github in order to test changes to R package

**Comment by tqchen** [comment]
You can follow the manual clone , but with an recursive option

**Comment by tqchen** [comment]
@hetong007 @thirdwing Maybe we should consider remove intstall_git instruction, which seems does not include recursive cloning as well, but instead give an instruction to do recursive clone and install manually

**Comment by thirdwing** [comment]
That should be removed. CRAN version and drat version should be enough for R users.

**Comment by tqchen** [comment]
This instruction is for developers like @vykhand who like to test their local changes

**Comment by tqchen** [comment]
@thirdwing can you help adding this advanced build instruction? Thanks!

**Comment by vykhand** [comment]
Hi @tqchen, what do you mean by "You can follow the manual clone , but with an recursive option", can you point me to some step-by-step to do this?

**Comment by thirdwing** [comment]
Hi, @vykhand ,

Please try the following lines:

```bash
git clone --recursive https://github.com/dmlc/xgboost
cd xgboost
make Rbuild
R CMD INSTALL xgboost_0.4-3.tar.gz
```

**Comment by vykhand** [comment]
Hi @thirdwing, thank you, that worked!
