### ISSUE TITLE
what "xgboost  missing = nan " means

### ISSUE THREAD

**Issue by tngks66** [dmlc/xgboost#822]
i don`t know that when i set xgboost(data, label, para, missing = nan) , what missing = nan means.
just missing = nan means that filling NA into the NAN? or filling empty valu into the NAN?

**Comment by Far0n** [comment]
You specify your *nan* value this way. Let's say you did something like data.fillna(-999), you would call
xgboost(data, label, para, missing = -999)

**Comment by tngks66** [comment]
so you mean that if i set the missing= 100, NA fills in 1000?

**Comment by Far0n** [comment]
No, xgb does not change the data at all. It just treats the specified *missing* value as a special one.

**Comment by tngks66** [comment]
hmm.... could you please make concrete the special one? i don`t understand

**Comment by tngks66** [comment]
is it means that missing = nan is treating NA to nan ?

**Comment by Far0n** [comment]
Let's say you have the following numpy array: data = [1,2, np.nan, 4]. Xgb will complain about the np.nan within that array if you call DMatrix(data). So, what you do is replacing np.nan by an arbitrary value, let's say "-999". Hence data becomes: data_new = [1,2, -999, 4]. Now you tell xgb, that you encoded missing values by "-999": DMatrix(data_new, missing=-999).

**Comment by tngks66** [comment]
sorry for my ignorance... i don`t know np.nan and numpy array ... i`m R user

**Comment by terrytangyuan** [comment]
@tngks66 So say you data has 99999, which in real life means this data is missing for your problem, if you set `missing = 99999 `, xgb will treat this special value as missing value. It will treat 99999 as NA.

**Comment by qianrenliang** [comment]
good explains
