### ISSUE TITLE
Julia version of XGBoost broken for Macs (except for recent OS >=10.15).

### ISSUE THREAD

**Issue by compleathorseplayer** [dmlc/xgboost#8223]
Julia implementation of XGBoost is broken for Macs not bought within the past couple of years (OS < 10.15, e.g. Mojave)

[This is apparently due to compilation issues of a c++ library]

Does anyone know of an alternative implementation of xgboost which is available for Julia?

I teach large (>200)  classes and few students have the latest laptops, so I cannot use xgboost for my classes as things stand.

Thanks for any help or advice.

**Comment by hcho3** [comment]
Fixed in https://github.com/JuliaPackaging/Yggdrasil/pull/5430.
