### ISSUE TITLE
Predict with `QuantileDMatrix`

### ISSUE THREAD

**Issue by ldesreumaux** [dmlc/xgboost#8224]
With the current codebase, it is not possible to use `Learner::Predict` with a `QuantileDMatrix` to get leaf indices, feature contributions or feature interactions. The following error is raised:
https://github.com/dmlc/xgboost/blob/7ee10e3dbdd81f8dc00bf34da34c90dd8e7b244f/src/data/iterative_dmatrix.h#L115-L118

Is there any plan to support these prediction types?

**Comment by trivialfis** [comment]
Yes, we are still working on this. For now, my priority is to make sure it can work with both CPU and GPU data: https://github.com/dmlc/xgboost/pull/8215 .
