### ISSUE TITLE
ml.dmlc.xgboost4j.java.XGBoostError: [12:24:38] /workspace/src/c_api/c_api_utils.h:240: Check failed: feature_map.Size() == n_features (13 vs. 19)

### ISSUE THREAD

**Issue by Dipak-Kharat** [dmlc/xgboost#8228]
Hi Team, After upgrading spark version from 3.0.3 to 3.2.2 , mleap from 0.19.0 to 0.20.0 and xgboost4j version from 1.3.1 to 1.5.2. We are getting error  **ml.dmlc.xgboost4j.java.XGBoostError: [12:24:38] /workspace/src/c_api/c_api_utils.h:240: Check failed: feature_map.Size() == n_features (13 vs. 19)**   while running training job. 
we are running spark scala code for training job and as xgboost is internally required python so we even updated python version to 3.9. Still we are getting same error message.
 could you please help , thanks in advance !!

**Comment by wbo4958** [comment]
can you describe your testing script and configuration?

**Comment by wbo4958** [comment]
@Dipak-Kharat 
can you provide your testing script and configuration?

**Comment by trivialfis** [comment]
Closing as stalled.
