### ISSUE TITLE
[jvm-packages] ml.dmlc.xgboost4j.scala.Booster cannot be cast to ml.dmlc.xgboost4j.scala.Booster

### ISSUE THREAD

**Issue by wbo4958** [dmlc/xgboost#8236]
When running xgboost iris example in notebook with underlying spylon-kernel, it will suffer the class casting issue.

``` console
java.lang.ClassCastException: ml.dmlc.xgboost4j.scala.Booster cannot be cast to ml.dmlc.xgboost4j.scala.Booster
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainDistributed(XGBoost.scala:418)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:202)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:34)
```

Same issues with https://github.com/dmlc/xgboost/issues/4218, https://github.com/dmlc/xgboost/issues/5186, https://github.com/dmlc/xgboost/issues/7599
## Repro

Env: spark 3.1.1, xgboost 2.0.0-snapshot

Install the below packages in your terminal

``` bash
conda create -n jupyter python==3.9

conda activate jupyter
pip install jupyterlab                                                                                                                                                                                             
pip install notebook

pip install spylon-kernel

python -m spylon_kernel install --user --name spark-scala
```

launch the notebook by

``` bash
SPARK_HOME=XXX jupyter notebook
```

### init kernel

``` python
%%init_spark
import os

m2dir = os.path.expanduser('~/.m2/repository')

xgboost_v = '2.0.0-SNAPSHOT'

launcher.jars = [
    xgboost4j-gpu_2.12-{xgboost_v}.jar,
    xgboost4j-spark-gpu_2.12-{xgboost_v}.jar,
]
```

### iris demo
``` scala
import org.apache.spark.sql.types._
import ml.dmlc.xgboost4j.scala.spark.{XGBoostClassificationModel, XGBoostClassifier}
val schema = new StructType(Array(
  StructField("sepal length", DoubleType, true),
  StructField("sepal width", DoubleType, true),
  StructField("petal length", DoubleType, true),
  StructField("petal width", DoubleType, true),
  StructField("class", DoubleType, true)))

val rawInput = spark.read.schema(schema).csv("/home/bobwang/data/iris/csv")

rawInput.show()
val features = Array("sepal length", "sepal width", "petal length", "petal width")

val xgbParam = Map(
  "objective" -> "multi:softprob",
  "num_class" -> 3,
  "num_round" -> 100,
  "tree_method" -> "hist",
  "num_workers" -> 1)

val xgbClassifier = new XGBoostClassifier(xgbParam)
  .setFeaturesCol(features)
  .setLabelCol("class")

val xgbClassificationModel = xgbClassifier.fit(rawInput)
```

**Comment by wbo4958** [comment]
The driver side loads the Booster with `scala.reflect.internal.util.ScalaClassLoader$URLClassLoader@11e637ea`, while the executor side loads the Booster with `org.apache.spark.util.MutableURLClassLoader@31add175`. So it can't do the casting even for the same class since they are loaded by different classloader.

**Comment by wbo4958** [comment]
I tested by not using notebook + spylon, and submitted the application by spark-submit, and it can work, since both of sides loads Booster by `org.apache.spark.util.MutableURLClassLoader@31add175`

**Comment by wbo4958** [comment]
I did the test running XGBoost on spark-shell  and it can work well.

Both Boosters are load by `scala.reflect.internal.util.ScalaClassLoader$URLClassLoader@5e76eb5a`

**Comment by wbo4958** [comment]
I found a workaround by changing to 

``` python
launcher.conf.spark.driver.extraClassPath = [
    xgboost4j-gpu_2.12-{xgboost_v}.jar,
    xgboost4j-spark-gpu_2.12-{xgboost_v}.jar,
]
```

I don't think this is the xgboost-specific issue. Instead, it may be the spark's limitation. Just close this issue.

**Comment by gerashegalov** [comment]
I demonstrated this issue with https://github.com/gerashegalov/spark-rapids-examples/blob/rero6404/examples/XGBoost-Examples/taxi/notebooks/scala/taxi-gpu.ipynb

> I don't think this is the xgboost-specific issue. Instead, it may be the spark's limitation. Just close this issue.

I strongly suspect that this is a xgboost4j-specific issue related to https://github.com/dmlc/xgboost/blob/a68580e2a7d84d7206165ab1f3c911886d45dcba/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/PreXGBoost.scala#L60

the fact that it only works with extraClassPath means that xgboost4j is only usable as a Spark-internal jar as opposed to a user jar provided by --jars or --packages spark-submit options.

**Comment by wbo4958** [comment]
@gerashegalov, The ServiceLoader way to load PreXGBoostProvider was introduced by 1.6.x and there are same issues  https://github.com/dmlc/xgboost/issues/4218, https://github.com/dmlc/xgboost/issues/5186, https://github.com/dmlc/xgboost/issues/7599 which happened in every old XGBoost, which means all of them don't have ServiceLoader way.

And if w/o running xgboost on notebook + spylon, there is no any issue for `spark-submit --jars xgboost.jar` and `spark-shell --jars xgboost.jar`
