### ISSUE TITLE
ImportError: cannot import name LabelEncoder

### ISSUE THREAD

**Issue by zhengt2015** [dmlc/xgboost#824]
when I tried to run the multiclass demo I could not import xgboost and it gave me the error: ImportError: cannot import name LabelEncoder

Could you help me with this? I am new to Python. Thank you.

**Comment by phunterlau** [comment]
Please install scikit-learn

**Comment by ivallesp** [comment]
Launch in your console `pip install scikit-learn`

**Comment by jamartinh** [comment]
This does not solve the problem.

**Comment by ivallesp** [comment]
what probably happens is that you have the Scikit-learn version outdated. You can update it launching in your shell: `pip install --upgrade scikit-learn`

**Comment by hashamMunir** [comment]
even upgrade is unable to import LabelEncoder. I am having the same issue. please any suggestion

**Comment by phunterlau** [comment]
@hashamMunir can you verify if you can `import sklearn` on your python?
