### ISSUE TITLE
Question about building with NCCL

### ISSUE THREAD

**Issue by WeichenXu123** [dmlc/xgboost#8252]
The doc say:

https://xgboost.readthedocs.io/en/stable/build.html

> Enabling distributed GPU training
> 
> By default, distributed GPU training is disabled and only a single GPU will be used. To enable distributed GPU training, set the option USE_NCCL=ON. Distributed GPU training depends on NCCL2, available at [this link](https://developer.nvidia.com/nccl). Since NCCL2 is only available for Linux machines, distributed GPU training is available only for Linux.
> 
> mkdir build
> cd build
> cmake .. -DUSE_CUDA=ON -DUSE_NCCL=ON -DNCCL_ROOT=/path/to/nccl2
> make -j4
> 

But I does not add `-DUSE_NCCL=ON` and build the package it can still run with multiple GPU cores (testing by xgboost spark).
Do I miss something ?

**Comment by WeichenXu123** [comment]
CC @trivialfis Thank you!

**Comment by trivialfis** [comment]
@rongou Recently enabled GPU training without nccl federated training. But that might cause significant performance lost on GPU clusters.

**Comment by WeichenXu123** [comment]
> @rongou Recently enabled GPU training without nccl federated training. But that might cause significant performance lost on GPU clusters.

Understood.
Btw, for the official xgboost package release on pypi, does it build with NCCL ? @trivialfis

**Comment by trivialfis** [comment]
Yes. It's built with NCCL.
