### ISSUE TITLE
Issues about sample_weight

### ISSUE THREAD

**Issue by deathwingssins** [dmlc/xgboost#8261]
I am using XGBoost to train a data set with sample weights. If I multiply sample weights by a constant (for example, multiply all sample weights by 10, 100, 1000 and so on), I get totally different results with exact same parameters and random_state, I think that while multiplying/dividing sample weights with a constant, results should not change. Is there any mistake? How can I get the same results?

**Comment by trivialfis** [comment]
The resulting model would be different. Scaling has different effects on different algorithms that use the weight, along with floating point error, the model is very likely to differ with different scales of weight. Please standardize the value.
