### ISSUE TITLE
1.7.0 Release Roadmap

### ISSUE THREAD

**Issue by trivialfis** [dmlc/xgboost#8282]
Hi everyone, we are delighted to announce a new release 1.7.0 in the upcoming weeks. Previously we planned for a 2.0.0 as a milestone, but with the exciting addition of the PySpark interface, we decided to make a 1.7.0 instead to share some new features and bug fixes earlier.

Roadmap: https://github.com/dmlc/xgboost/projects/4

@dmlc/xgboost-committer Please add your items here by editing this post. Let's ensure that

* Each item has to be associated with a ticket
* Major design/refactoring are associated with an RFC before committing the code
* Blocking issue must be marked as blocking
* Breaking change must be marked as breaking

For other contributors who have no permission to edit the post, please comment here about what you think should be in 1.7.0.

**Comment by trivialfis** [comment]
cc @WeichenXu123

**Comment by WeichenXu123** [comment]
From my side no new ticket to be added for 1.7.0 :)

**Comment by wbo4958** [comment]
please add https://github.com/dmlc/xgboost/pull/8283 and https://github.com/dmlc/xgboost/pull/8271 into 1.7.0 Thx

**Comment by trivialfis** [comment]
Debugging Rhub build errors:
```
 1 xgboost 1.7.0.1 NNN       0b8d79f 0b8d79f debian… ~3h     2022-10-19 01:02:22
 2 xgboost 1.7.0.1 preperror 7e40754 6968cb8 linux-… ~6h     2022-10-19 00:20:33
 3 xgboost 1.7.0.1 E         7e40754 6e70c90 fedora… ~2h     2022-10-19 00:20:33
 4 xgboost 1.7.0.1 ENNN      7e40754 9976c70 window… ~13m    2022-10-19 00:20:33
 5 xgboost 1.7.0.1 preperror 7e40754 afa4448 ubuntu… ~2h     2022-10-19 00:20:33
```
