### ISSUE TITLE
compile xgboost4j with scala 2.11

### ISSUE THREAD

**Issue by biaochen** [dmlc/xgboost#8293]
My env has spark 2.4.5 with scala 2.11, so I'd build xgboost4j.jar / xgboost4j-spark.jar with scala 2.11.
But under jvm-packages dir, the pom has dependency with scala 2.12.
Pls kindly tell how to achieve this. thx.

**Comment by wbo4958** [comment]
The latest XGBoost doesn't support spark 2.x and scala 2.11.
