### ISSUE TITLE
Seems getting info of 'group' slot doesn't works (in R) 

### ISSUE THREAD

**Issue by BlindApe** [dmlc/xgboost#83]
> require(xgboost)
> data(agaricus.train, package='xgboost')
> train <- agaricus.train
> group = rep(seq(1:3), length.out =  length(train[[1]]))
> dtrain <- xgb.DMatrix(data = train$data, label = train$label, group = group)
> # works
> 
> labels <- getinfo(dtrain, 'label')
> head(labels)
> [1] 1 0 0 1 0 0
> # doesn't works
> 
> groups <- getinfo(dtrain, 'group')
> Error en .local(object, ...) : xgb.getinfo: unknown info name group
> # low level works
> 
> labels <- .Call("XGDMatrixGetInfo_R", dtrain, 'label', PACKAGE = "xgboost")
> head(labels)
> [1] 1 0 0 1 0 0
> # low level doesn't works
> 
> groups <- .Call("XGDMatrixGetInfo_R", dtrain, 'group', PACKAGE = "xgboost")
> Error: unknown field group
> # explicit setinfo
> 
> setinfo(dtrain, 'group', group)
> [1] TRUE
> groups <- .Call("XGDMatrixGetInfo_R", dtrain, 'group', PACKAGE = "xgboost")
> Error: unknown field group

**Comment by pommedeterresautee** [comment]
@tqchen any change for getinfo "group" ?
I just tried with no success (by modifying the R source code) :-(

```R
> getinfo(dtrain, 'group')
Error in getinfo.xgb.DMatrix(dtrain, "group") : 
  [16:58:17] ../..//amalgamation/../src/c_api/c_api.cc:488: Unknown float field name group

Stack trace returned 10 entries:
[bt] (0) /home/benesty_local/R/x86_64-pc-linux-gnu-library/3.4/xgboost/libs/xgboost.so(_ZN4dmlc15LogMessageFatalD1Ev+0x36) [0x7fc23a9d9996]
[bt] (1) /home/benesty_local/R/x86_64-pc-linux-gnu-library/3.4/xgboost/libs/xgboost.so(XGDMatrixGetFloatInfo+0x10e) [0x7fc23a9e04fe]
[bt] (2) /home/benesty_local/R/x86_64-pc-linux-gnu-library/3.4/xgboost/libs/xgboost.so(XGDMatrixGetInfo_R+0x51) [0x7fc23a9d6671]
[bt] (3) /usr/lib/R/lib/libR.so(+0xd2d3c) [0x7fc263f52d3c]
[bt] (4) /usr/lib/R/lib/libR.so(Rf_eval+0x7c5) [0x7fc263f8fab5]
[bt] (5) /usr/lib/R/lib/libR.so(+0x1136a6) [0x7fc263f936a6]
[bt] (6) /usr/lib/R/lib/libR.so(Rf_eval+0x5a0) [0x7fc263f8f890]
[bt] (7) /usr/lib/R/lib/libR.so(+0x112538) [0x7fc263f92538]
[bt] (8) /usr/lib/R/lib/libR.so(Rf_eval+0x5a0) [0x7fc263f8f890]
[bt] (9) /usr/lib/R/lib/libR.so(Rf_eval+0x5a0) [0x7fc263f8f890]
```

**Comment by pommedeterresautee** [comment]
linked to
https://github.com/dmlc/xgboost/issues/1431
https://github.com/dmlc/xgboost/issues/574 (closure solution)
