### ISSUE TITLE
https://github.com/dmlc/xgboost/tree/master/windows  is not available. So how to install xgboost in windows?

### ISSUE THREAD

**Issue by Karamcse** [dmlc/xgboost#831]
I followed below link for installing xgboost in windows. But I can't find windows folder for installing xgboost.

https://www.kaggle.com/c/otto-group-product-classification-challenge/forums/t/13043/run-xgboost-from-windows-and-python

And also I installed through python_packages using python setup.py install. I am getting below error.
D:\xgboost-master\python-package\xgboost\libxgboost.dll
D:\xgboost-master\python-package\xgboost\../../lib/libxgboost.dll
D:\xgboost-master\python-package\xgboost\./lib/libxgboost.dll
D:\xgboost-master\python-package\xgboost\../../windows/x64/Release/libxgboost.dll
D:\xgboost-master\python-package\xgboost\./windows/x64/Release/libxgboost.dll

**Comment by tqchen** [comment]
see https://xgboost.readthedocs.org/en/latest/build.html#building-on-windows

**Comment by dagley11** [comment]
I followed instructions and get the following error when building with make on Windows 64-bit.  FYI, I aliased mingw32-make -> make to get things workings.  Any ideas? 

```cmd
A subdirectory or file -p already exists.
Error occurred while processing: -p.
The syntax of the command is incorrect.
Makefile:97: recipe for target 'build/objective/regression_obj.o' failed
make: *** [build/objective/regression_obj.o] Error 1
make: *** Waiting for unfinished jobs....
A subdirectory or file build already exists.
Error occurred while processing: build.
Makefile:97: recipe for target 'build/learner.o' failed
make: *** [build/learner.o] Error 1
Makefile:97: recipe for target 'build/logging.o' failed
make: *** [build/logging.o] Error 1
The syntax of the command is incorrect.
Makefile:97: recipe for target 'build/objective/rank_obj.o' failed
make: *** [build/objective/rank_obj.o] Error 1
```

**Comment by thirdwing** [comment]
@dagley11 You are running into a very classical problem on Windows.

In Windows CMD, `mkdir` doesn't have the `-p` option, which is quite annoying.

The simplest solution is using another shell on Windows.

If you have install git from `https://git-for-windows.github.io` or  `https://git-scm.com`, you already have a standard bash shell.

Running `make` in that shell shouldn't have such errors.

**Comment by dagley11** [comment]
@thirdwing Yes, you were right!  Works now in Git Bash shell. Thank you very much!!

**Comment by OnkarDeshpande** [comment]
@thirdwing  I am facing the following error: 
`A subdirectory or file -p already exists.
Error occurred while processing: -p.
A subdirectory or file build already exists.
Error occurred while processing: build.
The syntax of the command is incorrect.
g++ -m64 -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -MM -MT build/learner.o src/learner.cc >build/learner.d
The syntax of the command is incorrect.
mingw32-make: *** [build/logging.o] Error 1
mingw32-make: *** Waiting for unfinished jobs....
mingw32-make: *** [build/common/common.o] Error 1
mingw32-make: *** [build/c_api/c_api_error.o] Error 1
g++ -m64 -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -c src/learner.cc -o build/learner.o`


As guided by you i had downloaded git bash from the link you mentioned and also deleted previous folder of xgboost before giving the `mingw32-make -j4` command.

**Comment by thirdwing** [comment]
@OnkarDeshpande From your error log, I am afraid you are still using Windows CMD.

**Comment by OnkarDeshpande** [comment]
@thirdwing I'm attaching a screenshot of the error. Please have a look at it.  I'm using git bash, yet getting the same error. 

![screenshot](https://cloud.githubusercontent.com/assets/17825435/13804111/30a583ea-eb70-11e5-9919-6297766bb73d.PNG)

**Comment by thirdwing** [comment]
@OnkarDeshpande You are still facing the `mkdir` problem. Let me try to find a good way to handle it.

**Comment by OnkarDeshpande** [comment]
@thirdwing  Yes, I'm still facing the issue. Thanks in advance for helping! :)
