### ISSUE TITLE
Need a clarification in the rank example.

### ISSUE THREAD

**Issue by leocnj** [dmlc/xgboost#832]
In the rank example, I saw the below sentence. However, from reading online introductions about learning to rank (LTR), I learned that LadmdaRank is in fact a pair-wise ranking method too. Will you please clarify which exact LTR method is now provided inside the xgboost. Also, do you have a plan to provide the ladmdaMART implementation in near future?

> The model used in XGBoost for ranking is the LambdaRank, this function is not yet completed. Currently, we provide pairwise rank.

**Comment by tqchen** [comment]
It is already supported in https://github.com/dmlc/xgboost/blob/master/src/objective/rank_obj.cc#L319 However, we did not observe significant improvement over pairwise version
