### ISSUE TITLE
Incomplete CPU utilization with M1 Pro, M1 Max, and M1 Ultra architectures

### ISSUE THREAD

**Issue by leedrake5** [dmlc/xgboost#8320]
I've seen bits of this problem discussed elsewhere, [most notably here](https://github.com/dmlc/xgboost/issues/7614). The issue appears to be related to the ways Apple has changed it's CPU architecture, but it make the nthreads argument somewhat meaningless on these systems. 

To illustrate, I'm using the XGBoost tutorial for reproducible code:

```
require(xgboost)
data(agaricus.train, package='xgboost')
data(agaricus.test, package='xgboost')
train <- agaricus.train
test <- agaricus.test

bstSparse <- xgboost(data = train$data, label = train$label, max.depth = 2, eta = 1, nthread = -1, nrounds = 200000, objective = "binary:logistic")
```

Note nthreads=-1 is used, this should use up all 20 cores. But instead, the following pattern emerges:

<img width="819" alt="Screen Shot 2022-10-07 at 9 33 32 AM" src="https://user-images.githubusercontent.com/1229542/194593201-80230819-a4be-469d-9a63-a864efbd4db1.png">

All efficiency cores are fully utilized, while a fraction of performance cores are used. Out of 16 performance cores, nthread left 6 idle and used around 50-60% of the others. 

[I think the issue is how Mac arranges these cores](https://eclecticlight.co/2022/04/25/how-macos-manages-m1-cpu-cores/) - rather than laying them out they instead nest the performance cores within efficiency cores in some (but not all) of their chips:

> To simplify the management of cores, macOS divides them functionally into clusters of 2-4 cores of the same type. Unfortunately, numbering of cores at a system level, as shown by tools such as powermetrics, and as displayed in Activity Monitor is different. For consistency with the latter, I here follow its core numbering, but number clusters in accordance with the system. The three chips have the following functional clusters as of macOS Monterey 12.3.1:

> 1. the original M1 has one cluster of each type of core, E0 and P0, each containing 4 cores of the same type;
> 2. M1 Pro and Max have one cluster of 2 E cores (E0), and two clusters each containing 4 P cores (P0, P1);
> 3. M1 Ultra has one cluster of 4 E cores (E0), and four clusters each containing 4 P cores (P0, P1, P2, P3).

> All cores within any given cluster are run at the same frequency, and generally (but not always) have their load balanced within the cluster. There are occasions when load is distributed more unevenly, and in exceptional cases, certain threads may be allocated to only one core within a cluster.

If we set nthread to 1 and run the model simultaneously 20 times, we can see full CPU utilization:

```
require(parallel)
makeForkCluster(detectCores())

pbapply::pblapply(rep(1, 20), function(x) xgboost(data = train$data, label = train$label, max.depth = 50, eta = 1, nthread = x, nrounds = 200000, objective = "binary:logistic"), cl=20)
```
 
<img width="819" alt="Screen Shot 2022-10-07 at 9 54 57 AM" src="https://user-images.githubusercontent.com/1229542/194596452-2d76f820-b6d1-4017-915b-3e3c8968680d.png">

My suspicion is that XGBoost can only see the 4 efficiency cores given how they are listed in MacOS as the top level cluster. MacOS is then letting some (but not all) of the CPU requests move over to the second tier of performance core clusters. This leads to suboptimal performance on the pro-tier Macs. The effect is more noticeable the more completely the chips are stacked. However it should be possible to let nthread engage the full system's CPU, as the somewhat crude example above shows.

**Comment by hcho3** [comment]
XGBoost uses the OpenMP runtime (`libomp`) to make use of CPU cores. Have you run into a similar issue with other ML libraries, such as scikit-learn?

**Comment by hcho3** [comment]
Also, have you tried explicitly setting `nthread=20`? Do you get the same result as `nthread=-1`?

**Comment by leedrake5** [comment]
> Also, have you tried explicitly setting `nthread=20`? Do you get the same result as `nthread=-1`?

Yes, exact same results. Same is true for virtually every integer I throw at nthread. It can make a floor, but the ceiling is set somewhere else. 

> XGBoost uses the OpenMP runtime (libomp) to make use of CPU cores. Have you run into a similar issue with other ML libraries, such as scikit-learn?

Looking into reproducible versions now. Though I directed the query here because I was able to find [others who had no problem using OpenMP on these architectures](https://developer.apple.com/forums/thread/698990).

**Comment by hcho3** [comment]
@leedrake5 Here is the logic for detecting the number of available cores:
https://github.com/dmlc/xgboost/blob/fffb1fca522da1524350b1a563580f2e4e115ef4/src/common/threading_utils.h#L242-L249

Can you run this C++ program and post the output?
```cpp
#include <iostream>
#include <omp.h>

int main() {
  std::cout
    << omp_get_num_procs() << " "
    << omp_get_max_threads() << " "
    << omp_get_thread_limit() << std::endl;
  return 0;
}
```
(To build: `clang++ -o test test.cc -lomp -Xclang -fopenmp`, assuming you have `libomp` installed from Homebrew.)

**Comment by leedrake5** [comment]
Just a note that XGBoost in python has the same behavior. Will try the C++ program. next.

```
import xgboost as xgb
dtrain = xgb.DMatrix('~/GitHub/xgboost/demo/data/agaricus.txt.train')
param = {'max_depth':20, 'eta':1, 'objective':'binary:logistic' }
num_round = 20000
bst = xgb.train(param, dtrain, num_round)
```
<img width="819" alt="Screen Shot 2022-10-07 at 12 07 10 PM" src="https://user-images.githubusercontent.com/1229542/194622014-89975a97-a9e0-4909-ba29-a0b5a6fa7ff7.png">

**Comment by leedrake5** [comment]
> (To build: clang++ -o test test.cc -lomp -Xclang -fopenmp, assuming you have libomp installed from Homebrew.)

For whatever reason  this simply doesn't work, so I found an alternative openmp verifier [here](https://web.njit.edu/~shahriar/class_home/HPC/hello_omp.c) and ran with it. 

```
#include <omp.h>
#include <stdio.h>
#include <stdlib.h>

int main (int argc, char *argv[]) 
{
int nthreads, id;

/* Fork a team of threads giving them their own copies of variables.
   Make the values of nthreads and id private to each thread */

#pragma omp parallel private(nthreads, id)
  {

  /* Obtain thread number */
  id = omp_get_thread_num();
  printf("Hello World from thread = %d\n", id);

  /* Only master thread does this */
  if (id == 0) 
    {
    nthreads = omp_get_num_threads();
    printf("Number of threads = %d\n", nthreads);
    }

  }  /* All threads join master thread and disband */
    return 0;
}
```

And then ran it this way:

```
/opt/homebrew/opt/llvm/bin/clang $LDFLAGS -fopenmp hello_omp.c
./a.out
```

With the following output: 

```
Hello World from thread = 8
Hello World from thread = 0
Hello World from thread = 2
Hello World from thread = 15
Hello World from thread = 11
Hello World from thread = 13
Hello World from thread = 12
Hello World from thread = 10
Hello World from thread = 9
Hello World from thread = 18
Hello World from thread = 6
Hello World from thread = 5
Hello World from thread = 3
Hello World from thread = 1
Hello World from thread = 17
Number of threads = 20
Hello World from thread = 16
Hello World from thread = 7
Hello World from thread = 14
Hello World from thread = 4
Hello World from thread = 19
```

Nothing creative is on this Mac - OpenMP is installed with `brew install libomp`. So not sure where the problem may be. OpenMP clearly works, but perhaps there is some reference that isn't working the same in arm64 Macs as it does on Intel? My M1 MacBook has no issue using XGBoost, it's quite fast. But a Mac Studio just can't use anything except the efficiency cores (though it does use all of them with nthread=-1).

**Comment by hcho3** [comment]
Unfortunately none of the XGBoost developers own M1 devices. Marking this as "help wanted".

**Comment by hcho3** [comment]
@leedrake5 Can you modify the C program to print out the value of `omp_get_num_procs()` and `omp_get_max_threads()`?

**Comment by leedrake5** [comment]
Yes. Modified this way: 

```
#include <omp.h>
#include <stdio.h>
#include <stdlib.h>

int main (int argc, char *argv[])
{
int nthreads, id;

/* Fork a team of threads giving them their own copies of variables.
   Make the values of nthreads and id private to each thread */

#pragma omp parallel private(nthreads, id)
  {

  /* Obtain thread number */
  id = omp_get_thread_num();
  printf("Hello World from thread = %d\n", id);

  /* Only master thread does this */
  if (id == 0)
    {
    nthreads = omp_get_num_threads();
    printf("omp_get_num_threads = %d\n", nthreads);
    
    nthreads = omp_get_max_threads();
    printf("omp_get_max_threads = %d\n", nthreads);
      
    nthreads = omp_get_num_procs();
    printf("omp_get_num_procs = %d\n", nthreads);
    }

  }  /* All threads join master thread and disband */
    return 0;
}
```

WIth this output: 

```
Hello World from thread = 16
Hello World from thread = 6
Hello World from thread = 1
Hello World from thread = 19
Hello World from thread = 2
Hello World from thread = 18
Hello World from thread = 3
Hello World from thread = 10
Hello World from thread = 17
Hello World from thread = 7
Hello World from thread = 9
Hello World from thread = 15
Hello World from thread = 4
Hello World from thread = 11
Hello World from thread = 13
Hello World from thread = 14
Hello World from thread = 5
Hello World from thread = 12
Hello World from thread = 8
Hello World from thread = 0
omp_get_num_threads = 20
omp_get_max_threads = 20
omp_get_num_procs = 20
```

Beginning to wonder if the the "efficiency cores" are blocking performance cores somehow. There's clearly no issue with omp functions identifying the correct number of threads.

**Comment by hcho3** [comment]
> Beginning to wonder if the the "efficiency cores" are blocking performance cores somehow. 

This could be it. I just found https://developer.apple.com/forums/thread/674456

**Comment by trivialfis** [comment]
> Using dynamic scheduling ameliorates the problem; not sure if XGBoost uses it

rarely.  It's specified per-kernel.

**Comment by hcho3** [comment]
Maybe distributed training with a local Dask cluster would produce a better scaling on M1s.

**Comment by trivialfis** [comment]
Not sure. There's communication cost (we support tcp sockets only at the moment). It's a new CPU arch, I expect that it will take time for system software like libomp to take time to mature.  This is an interesting issue, but it's beyond what an ml library should handle I think.

**Comment by hcho3** [comment]
@trivialfis What would be the effect if we changed the default mode of OpenMP loops to `dynamic`? Would the overhead of a work-stealing queue be too excessive?

**Comment by trivialfis** [comment]
We will have to benchmark it loop by loop.

**Comment by leedrake5** [comment]
> Beginning to wonder if the the "efficiency cores" are blocking performance cores somehow.

Can confirm this is true - looks like Dropbox was somehow blocking almost half the cpu - quitting it enabled full utilization

...which led to the next problem, an error with OpenMP:

```
OMP: Error #13: Assertion failure at kmp_dispatch.cpp(1298).
OMP: Hint Please submit a bug report with this message, compile and run commands used, and machine configuration info including native compiler and operating system versions. Faster response will be obtained by including all program sources. For information on submitting this issue, please see https://bugs.llvm.org/.
zsh: abort R
```

I will send the bug to them.

**Comment by leedrake5** [comment]
Hopefully concluding note - libomp on brew was updated to version 15, and when I set nthread=16, it uses only performance cores. Been running for some time now without any issue. This might be settled on the OpenMP side but will report any issues I run across. 

<img width="847" alt="Screen Shot 2022-10-21 at 4 32 20 PM" src="https://user-images.githubusercontent.com/1229542/197297965-4b49364f-0e60-4c4f-9185-7d07754bbf32.png">

**Comment by leedrake5** [comment]
Unfortunately the issue is still present, but more intermittent than before. However I'm convinced it needs to be fixed on llvm's side.

**Comment by leedrake5** [comment]
Adding here in case it is helpful, starting to get failures at nthread=1. Increasingly worried that these new chips are incapable of CPU-based learning with OpenMP without big changes. 

```
OMP: Error #13: Assertion failure at kmp_dispatch.cpp(1298).
OMP: Hint Please submit a bug report with this message, compile and run commands used, and machine configuration info including native compiler and operating system versions. Faster response will be obtained by including all program sources. For information on submitting this issue, please see https://bugs.llvm.org/.
```

**Comment by hristog** [comment]
Sounds like it'd be fair to close this issue then? Or have I misunderstood?

**Comment by trivialfis** [comment]
Thank you all for the thorough investigation. Hopefully openmp can work flawlessly on m1 pro soon. I will close this for now, feel free to open new issues if there's anything we can do in XGBoost.

**Comment by leedrake5** [comment]
The latest llvm project (e.g. libomp) [release candidate 16](https://reviews.llvm.org/D139373) fixes the kmp.dispatch error.

**Comment by trivialfis** [comment]
Great news !

**Comment by praateekmahajan** [comment]
Realized a similar-but-opposite issue. It seems like irrespective of `n_jobs` argument, it's always using all the cores?
Posted in discuss here https://discuss.xgboost.ai/t/xgboost-measuring-n-jobs-speedup-python-scikit-learn-interface/3347/2

**Comment by guoyaol** [comment]
I am running into this problem again, with llvm 16.0.6
OMP: Error #13: Assertion failure at kmp_dispatch.cpp(1298).

**Comment by kaizenjinco** [comment]
For unknown reasons, I'm running into this problem, only two efficient cores are utilized when I train the model ...

**Comment by kaizenjinco** [comment]
> Hopefully concluding note - libomp on brew was updated to version 15, and when I set nthread=16, it uses only performance cores. Been running for some time now without any issue. This might be settled on the OpenMP side but will report any issues I run across.
> 
> <img alt="Screen Shot 2022-10-21 at 4 32 20 PM" width="847" src="https://user-images.githubusercontent.com/1229542/197297965-4b49364f-0e60-4c4f-9185-7d07754bbf32.png">

I have installed libomp but XGBoost still be handle on the efficiency cores ... Can you give me some hints or intructions.

**Comment by kaizenjinco** [comment]
I ended up this problem by using docker with Ubuntu ARM, the problem may came from both OpenMP and LLVM and I can push CPU usage to around 800% (M1 Pro - 10 cores). Although the result not as good as expected but it may at least 20x faster. I hope Apple Silicon will be more stable and can be fully utilized in the future :(

**Comment by leedrake5** [comment]
@kaizenjinco I'm sorry, lost track of this thread. I typically use this in R, and I suspect it has to do with their implementation - Linear only works with nthread=1, but no problems with Tree or Dart boosters. But it is very sensitive still, I find myself having to run linear models on different machines.
