### ISSUE TITLE
Feature Importance Aggregated to Feature

### ISSUE THREAD

**Issue by DarioS** [dmlc/xgboost#8322]
Currently, one importance score is output for feature-factor level combinations because of one-hot encoding. Could there be an option to calculate one score per feature, to make it compatible with CRAN's randomForest `importannce()`?

**Comment by trivialfis** [comment]
Not at the moment, unfortunately. We are working on categorical data (Python only right now) support so in the future one hot encoding in R will not be necessary.

**Comment by DarioS** [comment]
Awesome. I just chanced upon the [version 2.0 Roadmap task list](https://github.com/dmlc/xgboost/projects/2#card-81924609) and I see that true categorical support is on the way!

**Comment by trivialfis** [comment]
Closing in favor of https://github.com/dmlc/xgboost/issues/7899 .
