### ISSUE TITLE
[R] CRAN warning: use of prototypes in init.c

### ISSUE THREAD

**Issue by jameslamb** [dmlc/xgboost#8329]
Looking at https://cran.r-project.org/web/checks/check_results_xgboost.html, I noticed two similar warnings in the check results for `{xgboost}` 1.6.0.1 tonight.

```text
Result: WARN
    Found the following significant warnings:
     init.c:51:33: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
```

Flavors: [r-devel-linux-x86_64-debian-clang](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-clang/xgboost-00check.html), [r-devel-linux-x86_64-fedora-clang](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-clang/xgboost-00check.html)

and

```text
Result: WARN
    Found the following significant warnings:
     init.c:51:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
```

Flavors: [r-devel-linux-x86_64-debian-gcc](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-gcc/xgboost-00check.html), [r-devel-linux-x86_64-fedora-gcc](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-gcc/xgboost-00check.html)

Just wanted to report it in case you have't seen it.

### How to test this

In case you aren't aware, it's probably possible to replicate these checks (and then test potential fixes) on R Hub.

<details><summary>how to do that with the {rhub} R package (click me)</summary>

Build the source distribution of the R package, then you can submit it like this:

```r
EMAIL <- "YOUR-EMAIL"  # otherwise, logs will be emailed to the maintainer indicated in R-package/DESCRIPTION
PACKAGE_TARBALL <- "xgboost_1.6.0.1.tar.gz"

result <- rhub::check(
    path = PACKAGE_TARBALL
    , email = EMAIL
    , check_args = c(
        "--as-cran"
    )
    , platforms = c(
        "debian-clang-devel"
        , "debian-gcc-devel"
        , "fedora-clang-devel"
        , "fedora-gcc-devel"
    )
    , env_vars = c(
        "R_COMPILE_AND_INSTALL_PACKAGES" = "always"
        , "_R_CHECK_FORCE_SUGGESTS_" = "true"
        , "_R_CHECK_CRAN_INCOMING_USE_ASPELL_" = "true"
    )
)
```

</details>

It's also possible to run those checks in Docker, using the same images R Hub uses (https://github.com/r-hub/rhub-linux-builders).

Here's an example of how LightGBM does that: https://github.com/microsoft/LightGBM/blob/c5391c9701122a0779937f380a4108b5276e14fa/.github/workflows/r_package.yml#L213

**Comment by trivialfis** [comment]
Thank you for sharing, will look into the warnings.
