### ISSUE TITLE
Bunch of CPU tests are timing out

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#8334]
https://buildkite.com/organizations/xgboost/analytics/suites/xgboost-pytest-cpu/runs/4025651f-449b-4765-bf89-ba34f3f9af0c

**Comment by trivialfis** [comment]
@RAMitchell Requiring timeout on CI might not be reliable, this test took https://buildkite.com/organizations/xgboost/analytics/suites/xgboost-pytest-cpu/tests/152530677/executions/6641351944 almost 9 minutes while it finishes within 50 seconds on my local machine.

**Comment by hcho3** [comment]
I wonder why the CI machine is slower. We don't run multiple test jobs on each worker. https://github.com/dmlc/xgboost/blob/29595102b997aee96223afb258e5c3c2158e7cf1/tests/buildkite/infrastructure/aws-stack-creator/metadata.py#L72

**Comment by hcho3** [comment]
Let me try to reproduce the timeout on EC2.

**Comment by RAMitchell** [comment]
Maybe adding timeouts is a mistake. We might have too many false negatives. I can create a PR to remove them.
