### ISSUE TITLE
How to use xgboost to regress a bounding box?

### ISSUE THREAD

**Issue by starimpact** [dmlc/xgboost#834]
hi, I know xgboost can do classification and regression, but likely, it just supports one dimensional label.
Is it possible to make xgboost support multidimensional label, like the boundingbox?
Furthermore, is it easy to improve xgboost to make it support classification and regression concurrently, like to `Joint Cascade Face Detection and Alignment` [http://home.ustc.edu.cn/~chendong/JointCascade/ECCV14_JointCascade.pdf](url)

**Comment by tqchen** [comment]
You are asking about vector output, which is partially supported in the multi-class classification. Though the current tree builder is not vector tree.

One easy way is simply use a separate model for each dimension

**Comment by korkinof-aig** [comment]
Any plans for adding vector trees in the future?
