### ISSUE TITLE
Is the float array the only support input for xgboost4j?

### ISSUE THREAD

**Issue by ycy3675001** [dmlc/xgboost#8353]
Hello, there. I am trying to feed a mixed type of features, e.g., boolean, int, float, into DMatrix format in xgboost4j. But I found that unlike the python package, xgboost4j only supports the float array as the input for DMatrix.  Is there any way that I can use a mixed type of features in xgboost4j like in the python package?

**Comment by trivialfis** [comment]
The python package transforms the data into float internally, either with help from libraries like numpy or in xgboost c++ code. But in the end, XGBoost treats all data as floating point.

**Comment by ycy3675001** [comment]
> 

Yes, I got it. Thank you for your reply.
