### ISSUE TITLE
[BUG] Wrong prediction when changing column order of pandas DataFrame

### ISSUE THREAD

**Issue by SuperBo** [dmlc/xgboost#8357]
When we change the columns order of pandas.DataFrame, xgboost still uses inplace_prediction and don't do column swapping to transform into the original order. This leads to wrong prediction result. This can be reproduced with the following scripts.

```python
import xgboost
import pandas as pd

from sklearn.datasets import load_diabetes

# Load dataset
data = load_diabetes()
X = pd.DataFrame(data['data'], columns=data['feature_names'])
X_swap_columns = X[['age', 'sex', 'bmi', 'bp', 's6', 's5', 's4', 's3', 's2', 's1']]
y = data['target']

# Train model
regressor = xgboost.XGBRegressor()
regressor.fit(X, y)

# Assertion
assert (regressor.predict(X) == regressor.predict(X_swap_columns)).all()
```

One more problem is that when I use different columns name, Xgboost doesn't warn me like the old versions.

I am using XGBoost version 1.6.2

**Comment by trivialfis** [comment]
Thank you for raising the issue! Opened a PR to validate the features.
