### ISSUE TITLE
How can I use GPU for train and CPU for predict?

### ISSUE THREAD

**Issue by lhy2749** [dmlc/xgboost#8362]
I want to use GPU-device for training the model, like `{"max_depth": 9, ..., "tree_method": "gpu_hist", "gpu_id": 0}`, and use `model.save_model("./xgboost.model")` to save the model. When predict the data, use `model = xgb.XGBClassifier() model.load_model("./xgboost.model")` to load the model, but i got different result between by using GPU and CPU. How i could get the same result?

**Comment by hcho3** [comment]
The result should not be different. Can you post the script and model so that we can diagnose the bug?

**Comment by trivialfis** [comment]
It won't be exactly the same due to floating point errors. But the difference should be small.
