### ISSUE TITLE
Can not find the supplement of the xgboost publication

### ISSUE THREAD

**Issue by Jogala** [dmlc/xgboost#8363]
Hi, 

I am reading "XGBoost: A Scalable Tree Boosting System", see [https://arxiv.org/abs/1603.02754](https://arxiv.org/abs/1603.02754).

The link to the supplement is dead:

https://homes.cs.washington.edu/~tqchen/pdf/xgboost-supp.pdf

I can also not find any link to the supplmenent in the "README" here on github.

Thanks in adavance.

**Comment by trivialfis** [comment]
I think the APPENDIX should cover all the proofs.
