### ISSUE TITLE
How to use root median squared error as objective function?

### ISSUE THREAD

**Issue by odiseo1982** [dmlc/xgboost#837]
Hi!! Sorry if this is not the place for this comment but I couldn't use the google group. I'll like to know how to define a customized objective function for a regression problem in R. I'm interested in using root median squared error, instead of RMSE, or some other meassures using percentiles. I tried defining objective function using numerical derivatives through numDeriv R package, but couldn't make it work. Any help is greatly appreciated.

Thanks!

**Comment by pommedeterresautee** [comment]
Check the documentation. Closing
