### ISSUE TITLE
reduce float precision does not reduce training time

### ISSUE THREAD

**Issue by ACatAC** [dmlc/xgboost#8376]
I have a pandas dataframe that I use to create a DMatrix:

```
x_train = df.iloc[idx0:idx1, :]
x_test = df.iloc[idx1:, :]

sample_weights = compute_sample_weight(class_weight="balanced", y=y_train)
dmat_train = xgb.DMatrix(x_train, y_train, feature_names=x_train.columns)

dmat_test = xgb.DMatrix(x_test, y_test, feature_names=x_test.columns)
```

I thought that reducing the float precision in the dataframe would speed up the training time, but it did not.
Is this expected?

**Comment by trivialfis** [comment]
Yes, it's expected. XGBoost treats all data as 32-bit float internally.
