### ISSUE TITLE
XGBoost supplement is not available, link dead

### ISSUE THREAD

**Issue by Jogala** [dmlc/xgboost#8383]
Hi,

I am reading "XGBoost: A Scalable Tree Boosting System", see https://arxiv.org/abs/1603.02754.

The link to the supplement is dead:

https://homes.cs.washington.edu/~tqchen/pdf/xgboost-supp.pdf

Previous issues requesting the supplement got the following answers:
- "you will find the link in the reference section of the README", which is not the case.
- "I think the APPENDIX should cover all the proofs." Which appendix are you talking about? Why don't you provide a link?

If the an article is refernecing the supplementary material, then this supplement has to be aviable!
So could you please provide a link to the supplementary material?

Thanks in adavance.

**Comment by trivialfis** [comment]
> "I think the APPENDIX should cover all the proofs." Which appendix are you talking about? Why don't you provide a link?

At the end of the paper you linked.
![Screenshot from 2022-10-24 22-49-59](https://user-images.githubusercontent.com/16746409/197556161-c2f9cf52-27af-4a88-bd4f-edc65898ce10.png)

**Comment by Jogala** [comment]
Ah I see where that confusion comes from:

The paper on the ACM homepage does not include the Appendix.

https://dl.acm.org/doi/pdf/10.1145/2939672.2939785

But the paper on arxiv  does include the appendix. 

https://arxiv.org/pdf/1603.02754.pdf

**Comment by trivialfis** [comment]
Got it, thank you for sharing! Hopefully, others who met the same issue will find this thread useful.
