### ISSUE TITLE
PMML support for XGBoost

### ISSUE THREAD

**Issue by RishiSadhir** [dmlc/xgboost#839]
Are there any plans to support PMML export? The r2pmml package in R is able to export boosted trees created via the GBM package so I would assume this wouldn't be so difficult of a task.

**Comment by jtenini** [comment]
Yes please! Being able to export as PMML would be an excellent addition.

**Comment by pommedeterresautee** [comment]
linked to https://github.com/dmlc/xgboost/issues/196

**Comment by tqchen** [comment]
I think we will enable support to dump to json as a optional support. PMML can come later after this. However, note xgboost's tree is specialized to handle missing values and being different from normal ones

**Comment by vruusmann** [comment]
I've started the [JPMML-XGBoost] (https://github.com/jpmml/jpmml-xgboost) project, which provides a Java library and a command-line application for converting XGBoost model files to PMML files. The converter can do linear regression and binary classification, and the correctness of results is verified by asserting that XGBoost and PMML yield the same predictions.

The most difficult part of my R work was the generation of "feature maps". I couldn't find any ready to use solutions for that (or did I miss something obvious?), so I developed [two utility functions `genDMatrix(y, df_X, file)` and `genFMap(df_X, file)`] (https://github.com/jpmml/jpmml-xgboost/blob/master/src/main/R/util.R). Perhaps they should be included to the official `xgboost` package?

**Comment by a100297** [comment]
while it's not exactly PMML, I have an [example project](https://github.com/tonydifranco/xgboostjson) that converts xgboost models to a javascript object for embedding in node.js or web apps.

This would be much more cleanly implemented directly in [tree_model.cc](https://github.com/dmlc/xgboost/blob/master/src/tree/tree_model.cc) with an argument added to the `get_dump` method (python) or `xgb.dump` function (R) to switch between text and json dumps.

**Comment by vruusmann** [comment]
@a100297 Have you tested your implementation for correctness? XGBoost is doing all the evaluations using 32-bit floating-point numeric type, which is AFAIK unavailable in JavaScript. You cannot simply replace 32-bit floats with 64-bit floats, there has to be some carefully designed and tested bridge layer between them.

**Comment by tonydifranco** [comment]
@vruusmann I have done some minimal testing and the results were identical.  Let me clarify though, this **sample** project only converts the model dump (which is a string stream) into a javascript representation and doesn't access the c++ object directly.  Ideally, this would be implemented directly in the supported API's.

**Comment by vruusmann** [comment]
@a100297 The string dump contains rounded float values. Today, if you want to have a correct XGBoost re-implementation, then you need to extract 32-bit floats from binary model files, and carefully convert/translate them to whatever float type is available in your runtime environment.

My intention is not to downplay your idea and current work. Just sharing my experience.

The 32-bit/64-bit float representation issue affects approximately 1-3% of data records. Maybe that kind of  error rate is acceptable for your use case. This error can be demonstrated already using the Iris dataset - there was one specific split value (maybe `3.5`) that has different `float` and `double` representations - when evaluating in `float` mode this value is sent to the left, and when evaluating in `double` mode this value is sent to the right.

**Comment by tonydifranco** [comment]
@vruusmann thanks, appreciate your feedback and I completely agree with you.  I would love for someone to implement this (i.e. javascript conversion) directly instead of using the dumps.  maybe I'll have time in the future.

**Comment by SergeiOnenko** [comment]
@vruusmann hello! I have a problem while converting xgboost into pmml-file. 
It says "Error in .convert(tempfile, file, converter, converter_classpath, verbose) : 127"
My feeling is the problem is with wrong java or it's in an inappropriate folder, but I still cannot google the solution or even verify my guess. So, how do I fix the problem?
