### ISSUE TITLE
Set category type to column of boolean type

### ISSUE THREAD

**Issue by yananchen1989** [dmlc/xgboost#8396]
Hello, 

I have a pandas dataframe where some of the columns are boolean type, which contains True, False and None.
In this case, should I manually set them into category type ?
something like this:
`X['tf'] = X['tf'].astype("category")`
Or I need to one hot encode them ?

which would be better choice, thanks.

**Comment by trivialfis** [comment]
For versions before 1.7, just pass them as it's. For XGBoost after 1.7 (under rc test as of writing), you can try the experimental support for categorical data and use the `astype("category")`, whether it's a better option, however, depends on your specific dataset and tuning.
