### ISSUE TITLE
Installation issue: errors while making rabit (on Windows)

### ISSUE THREAD

**Issue by FACE1E55** [dmlc/xgboost#840]
As I understood from some installation guides, latest versions of xgboost  require rabit "made".
I tried  mingw32-make with the following results:
[console output.txt](https://github.com/dmlc/xgboost/files/135834/console.output.txt),
as well as MVSC 2013 with these errors
![mvsc](https://cloud.githubusercontent.com/assets/16034663/13137977/1b14eb90-d62d-11e5-9588-91f26a545546.jpg)

What should I do to resolve it?

**Comment by thirdwing** [comment]
No thoughts on VS errors.

But for MINGW error, it is actually due to some recent updates in mingw-w64.

There is no `ssize_t` type in previous version of mingw-w64, but now it has, so there will be some conflicts.

You can just try to comment out this line https://github.com/dmlc/rabit/blob/master/src/socket.h#L31

It should be changed into something like:

```cpp
#ifndef _SSIZE_T_DEFINED
#define _SSIZE_T_DEFINED
typedef int ssize_t;
#endif 
```

**Comment by tqchen** [comment]
@thirdwing can you open a PR to rabit to resolve this issue? Also if the instruction is followed and the mingw64.mk is copied to root folder as config.mk The rabit build should result in a dummy build that skips this step

**Comment by FACE1E55** [comment]
@thirdwing Thank you, this step helped to resolve first of the errors: 
the second one is regarding net_ntop
`src/././socket.h:76:52: error: 'inet_ntop' was not declared in this scope&buf[0], buf.length());`
the third one relates to sleep
`src/allreduce_base.cc:206:16: error: 'sleep' was not declared in this scope sleep(1);`
At the same time, newer mingw-w64 won't install due to `Cannot download repository.txt [0]`

@tqchen I'm glad to see you are involved. I've tried some manipulations with mingw64.mk and config.mk, but it had no results. Could you please clarify, how should I proceed.

Instead of mingw, I also tried cygwin, but unfortunately the result was exactly the same.

**Comment by thirdwing** [comment]
Please wait for a minute. I am updating the building instructions on Windows.

**Comment by thirdwing** [comment]
@FACE1E55 I think you are using an old GCC, maybe 4.7 or even older.

If you can't upgrade it, try to add `#include <unistd.h>`.

This might help, but I am not sure.

**Comment by FACE1E55** [comment]
@thirdwing I am using an old version of GCC for sure. 
I'm afraid, `#include <unistd.h>` is already there.
Now I think it's no use continuing this with an old compiler on windows
