### ISSUE TITLE
max_cat_to_onehot default value

### ISSUE THREAD

**Issue by iuiu34** [dmlc/xgboost#8404]
hi,
which is the default value for `max_cat_to_onehot`? And why is not explicit in the [documentation](https://xgboost.readthedocs.io/en/latest/parameter.html)?

Same for `max_cat_threshold`

**Comment by trivialfis** [comment]
Hi, you can find them here https://github.com/dmlc/xgboost/blob/0db903b4714ea2eb5cca8c61c4eb108874c3ec2e/src/tree/param.h#L114

We are exploring the best default and they might change in the future with more and more parameters being added to the combination.

**Comment by trivialfis** [comment]
Will close this issue now. We won't document the default value until it's no longer experimental. Users are encouraged to tune those parameters since they are highly dataset-dependent. Thank you for opening the issue.
