### ISSUE TITLE
BUG: xgboost 1.7 no longer has attribute rabit

### ISSUE THREAD

**Issue by mvashishtha** [dmlc/xgboost#8406]
See modin-project/modin#5171 for context-- https://github.com/modin-project/modin depends on xgboost and uses xgboost.rabit, but as of xgboost 1.7, xgboost no longer has `rabit`, which modin uses here: https://github.com/modin-project/modin/blob/5825856a4ee19ff0dd5d1beaf6090bf601d0b411/modin/experimental/xgboost/utils.py#L95-L102

AFAICT this is a breaking change that according to semantic version should not have gone into xgboost 1.7.

**Steps to reproduce**:

```shell
pip install xgboost==1.6
python -c "import xgboost; print(xgboost.rabit)"
pip install xgboost==1.7
python -c "import xgboost; print(xgboost.rabit)"
```

I'm on:

- macOS Monterey 12.4
- MacBook Pro (16-inch, 2019)
- Processor: 2.3 GHz 8-core intel core i9
- Memory: 16 GB 2667 MHz DDR4
- Python: 3.10.6

**Comment by hcho3** [comment]
Just filed #8407 to add back `xgboost.rabit`. Once that's merged, we'll make patch release 1.7.1.

**Comment by hcho3** [comment]
@mvashishtha We are about to release 1.7.1 to restore `xgboost.rabit`. Can you test it and see if it fixes Modin? (You can download the new Python wheel here.](https://buildkite.com/organizations/xgboost/pipelines/xgboost-ci/builds/631/jobs/018436ad-a660-4a77-bd9c-87d9625528ed/artifacts/018436c2-428c-444f-88ec-45e9a87fe360)

**Comment by hcho3** [comment]
Great! We'll go ahead and release 1.7.1

**Comment by trivialfis** [comment]
Thank you all!
