### ISSUE TITLE
Example gpu_training.py fails with rapids-22.10

### ISSUE THREAD

**Issue by anthls** [dmlc/xgboost#8419]
After installing rapids 22.10 into a clean conda environment using the command as per:
[https://rapids.ai/start.html#get-rapids](url)
which was:
`conda create -n rapids-22.10 -c rapidsai -c nvidia -c conda-forge rapids=22.10 python=3.8 cudatoolkit=11.5`

I attempted to run the example code here (which is linked to in the rapids documentation):
[https://github.com/dmlc/xgboost/blob/master/demo/dask/gpu_training.py](url)
but received this error:
`ubuntu@localhost:~/script$ conda activate rapids-22.10`
`(rapids-22.10) ubuntu@localhost:~script$ python ./gpu_training.py`
`2022-11-04 08:08:48,131 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize`
`2022-11-04 08:08:48,131 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize`
`2022-11-04 08:08:48,134 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize`
`2022-11-04 08:08:48,134 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize`
`Using DaskQuantileDMatrix`
`Traceback (most recent call last):`
`  File "./gpu_training.py", line 77, in <module>`
`    from_ddqdm = using_quantile_device_dmatrix(client, X, y)`
`  File "./gpu_training.py", line 53, in using_quantile_device_dmatrix`
`    dtrain = dxgb.DaskQuantileDMatrix(client, X, y)`
`AttributeError: module 'xgboost.dask' has no attribute 'DaskQuantileDMatrix'`

**Comment by trivialfis** [comment]
Hi, are you running the demo on the master branch but using xgboost 1.6 or an earlier version? Please upgrade XGBoost to 1.7 or use the demo from an older release.

**Comment by trivialfis** [comment]
`DaskQuantileDMatrix` is only available in 1.7.
