### ISSUE TITLE
Question: How do I use class weights in xgboost?

### ISSUE THREAD

**Issue by dianjunren** [dmlc/xgboost#842]
Hi 

First of all, let me thank you guys for your hardwork to make the xgboost available to us. it's such a great tool!

I am using xgboost in R. I came across a binary classification problem with a sampled data from an extremely imbalanced dataset. After downsampling the non-events, and keeping all events, there are case weights associated to event (weight = 1) and non-event (weight = 10). I read that the xgboost supports case weights through data format libsvm, but I could not find more exampled to learn and practice. 

My question:
1) is that possible that the xgboost can directly supports the case weights like 
    mdl <- xgboost(data, label, class.weights = XXXX, ...), rather than relying on libsvm format?

2) Would you please give me some examples in R how to use the LIBSVM format to implement case.weights? 

Thank you very much for your help!

Eric

**Comment by tqchen** [comment]
here is an example https://github.com/dmlc/xgboost/blob/master/demo/kaggle-higgs/higgs-train.R#L17

**Comment by tqchen** [comment]
@hetong007 we should put another example to the basic feature walkthourgh

**Comment by dianjunren** [comment]
Thank you. I will take a look at the example!

**Comment by handongfeng** [comment]
how to set scale_pos_weight for multiple classes problem? thanks
