### ISSUE TITLE
Socket failed to connect on FreeBSD.

### ISSUE THREAD

**Issue by yurivict** [dmlc/xgboost#8425]
```
[ RUN      ] Socket.Basic 
/disk-samsung/freebsd-ports/misc/xgboost/work/xgboost-1.7.1/tests/cpp/collective/test_socket.cc:34: Failure
Expected equality of these values:
  Connect(MakeSockAddress(StringView{addr}, port), &client)
    Which is: system:47
  std::errc{}
    Which is: 4-byte object <00-00 00-00>
/disk-samsung/freebsd-ports/misc/xgboost/work/xgboost-1.7.1/tests/cpp/collective/test_socket.cc:70: Skipped
Skipping IPv6 test
[  FAILED  ] Socket.Basic (0 ms)
```

Version: 1.7.1
clang-14
FreeBSD 13.1

**Comment by trivialfis** [comment]
Hmm, the socket failed to connect on FreeBSD. We don't have any linux specifc code in the socket module, need to find a bsd box for testing.

**Comment by trivialfis** [comment]
I got the message `address family not supported by protocol family connect` from `connect` failure. Any suggestion? I'm not sure why it fails on freebsd, currently we run tests on linux and macos.

**Comment by yurivict** [comment]
Same failure in the version 1.7.6

**Comment by trivialfis** [comment]
Closing as resolved.
