### ISSUE TITLE
Sparse matrices w/ sklearn api

### ISSUE THREAD

**Issue by dagley11** [dmlc/xgboost#843]
I'm getting very different scores when using a scipy.sparse.csr_matrix as an input vs a Pandas Data Frame for XGBRegressor.fit()  I checked this behavior against scikit-learn using random forests and my scores did not deviate, so the issue is not with the sparse matrix.  Any ideas?

**Comment by tqchen** [comment]
xgboost is optimized for sparse matrix treating non-presenting entries as misisng, while sklearn does not. and it really depends on what preprocessing was done to pandas data frame.

**Comment by GlebYarnykh** [comment]
Having same issue. I have sparse dataset of user clicks on websites, and when I fit XGBclassifier (xgb sklearn wrapper) with src matrix I get way worse results than if doing with standard numpy.

My data is basically 1/0 (visited/nonvisited).

I still do not understand why results differ so much

**Comment by bryan-woods** [comment]
This was also noted in #1238. There is definitely a problem with sparse matrixes in the latest sklearn API.

**Comment by tqchen** [comment]
https://github.com/dmlc/xgboost/issues/1583
