### ISSUE TITLE
Hash-Pinning Dependencies

### ISSUE THREAD

**Issue by joycebrum** [dmlc/xgboost#8438]
To contextualization, the [Pinned Dependencie Check](https://github.com/ossf/scorecard/blob/2cbf5afd5460b51fd40939f8c44b32543b1a0bcb/docs/checks.md#pinned-dependencies) is a Scorecard Check to help you to identify dependencies that are not pinned by hash.

I've seen that changing the dependencies to be hash-pinned would be a troublesome work for you to do, considering that there are lots of dependencies to change and that it would be a manual job.

I would like to help you on this update. Let me know if it's OK for you that I open a PR with the changes to hash-pinning the dependencies.

**Comment by trivialfis** [comment]
For most of the dependencies we have package manager like conda to help. Maybe for c++ libraries we need a better way to handle

**Comment by joycebrum** [comment]
One thing that might be important to notice is that the scorecard just parses through Dockerfiles, shell scripts, and GitHub workflows to check dependencies, so project dependencies wouldn't be a problem.

Most of the Pinned-Dependencies that Scorecard pointed out are in `tests/ci_build`, `.github/workflows` and in `Dockerfiles`.

**Comment by trivialfis** [comment]
Sounds good! Let me know if there's anything I can help.

**Comment by joycebrum** [comment]
@trivialfis can you help me understand one thing? Is the https://github.com/dmlc/xgboost/blob/master/doc/requirements.txt the requirements for the project itself, or only for the https://github.com/dmlc/xgboost/blob/master/.github/workflows/main.yml ?

I'm asking because scorecard is complaining about the workflow main have these dependencies which are not hash-pinned but, if it is dependencies for the project itself I'm not sure if pinning it will be a good idea.

**Comment by trivialfis** [comment]
That's for `read the docs` service used to host online documentation and I believe it's managed by pip with packages stored on pypi. I think we don't need to hash the dependencies if they are managed by well-known package managers right?

**Comment by joycebrum** [comment]
Since it is used in workflows it can represent a possible vulnerability because, depending on the workflow permissions, an external Github Action could modify your code. Also, for Python, Pip’s hash-checking mode ensures that the downloaded file matches a known SHA256 hash (stored in the project), thus any attempted package substitution attack must compromise both server and client ([Microsoft, 2021](https://azure.microsoft.com/en-us/resources/3-ways-to-mitigate-risk-using-private-package-feeds/)), what makes this type of attacks extremely difficult.

Since the downside of changing it to hash pinned would be that it would not be automaticaly updated, I've first verified if the dependabot was able to correctly update python dependencies and hashes, which I could confirm in this issue https://github.com/dependabot/dependabot-core/issues/1587.

If you rather use any other dependency update tool mentioned in [Dependency Update Tool Check](https://github.com/ossf/scorecard/blob/main/docs/checks.md#dependency-update-tool), let me know that I can configure them instead, even openning a specific issue for that to not "mix subjects".

**Comment by trivialfis** [comment]
Apologies for my ignorance of security issues. I read the whitepaper you referenced:

> Using a single feed is strongly recommended for the Python Package Index

We are using a single feed here I think, there's no extra index.

> Even with this configuration, if your feed allows public packages to override private
packages, a substitution attack may still be possible

We don't have private packages either.


Sorry for the many questions that I have. I'm trying to understand how this will work in the future (hopefully we can apply it to other projects as well).
- Does everyone write hashes for their direct dependencies in CI scripts? Doesn't seem to scale well ...
- Hashing seems to apply to direct dependency but not indirect dependencies? Can a dependency manager like pip or its source of packages (pypi) verify that everything is correctly referenced?
- What should we do about the `setup.py` used by Python setuptools?
- Is there a more automated tool that applies to secure dependency management, for both public projects like this one and private projects?
-  What if a language doesn't support multi-version dependencies, The environment can only have one version of a specific package: `error if: A <- {C_0.0.0, B.2.0.0}, B.2.0.0 < C_0.0.1} (C is different)` We can't pin the version in this case and have to allow dependency solver to do its work.

**Comment by joycebrum** [comment]
No worries about the questions, all your questions are totally reasonable and I also have take some time to read some materials regarding hash-pinning dependencies in python projects to see if it would really make sense to xgboost project or not, so nothing of this was obvious for me too 😄 . And sorry if the answer is too big 😥 .

> Does everyone write hashes for their direct dependencies in CI scripts? Doesn't seem to scale well ...

No, it is not worth it to always pin your dependencies. Take a look at this [blog post](https://www.promptworks.com/blog/pin-all-dependencies) from promptworks, for example. It talks about specifically version pinned, but it shows when you should pin and when you should not. 

That's why I asked if the doc/requirements.txt file was used as the xgboost dependency or just for documentations/workflows, because since xgboost is a library, its dependencies should not be pinned. This is less of a security risk, and more like insurance that your docs build will not fail in the future if a new, incompatible version of one of these dependencies is released.

When we talk about hash pinning, it is just a step further of version pinned, whether you will not accept any package with that version flag, but the one that has one of the previously specified SHAs. But this doesn’t need to be done manually. 

To do it in a more scalable way, we use [pip-compile](https://pypi.org/project/pip-tools/) that automatically generates the version pinning and the hashes (when using `--generate-hashes` flag), which makes this work much more feasible. Besides that, you can add this command (`pip-compile --generate-hashes requirements.in`) to the makefile to make it even more automated.

For xgboost I've tried the approach of creating one [docs/requirements.in](https://github.com/joycebrum/xgboost/blob/master/doc/requirements.in) that compiles to the [doc/requirements.txt](https://github.com/joycebrum/xgboost/blob/master/doc/requirements.txt) requirements file using pip-compile.

When you need to add a new dependency, you can add it to the requirements.in file and recompile the requirements.txt file.

But regarding workflows for CI tests, the [npm best practices](https://github.com/ossf/package-manager-best-practices/blob/main/published/npm.md#lockfiles-and-commands) (for example), are to not pin project’s dependencies used in integration tests workflows, if the project is a library, to test various dependency ranges and catch problems earlier.  

Considering that, I think I should focus on github dependencies mentioned in the actions and the ones that are not related to the project.

> Hashing seems to apply to direct dependency but not indirect dependencies? Can a dependency manager like pip or its source of packages (pypi) recursively verify that everything is correctly referenced?

Using pip-compile to generate the hashes for all installed dependencies, for example, it goes through all the indirect dependencies too.

> What should we do about the setup.py used by Python setuptools? It downloads dependencies, anyone who uses xgboost (this project) will use that to find indirect dependencies recursively.

The subdependencies of a library should not be pinned, to ensure maximum compatibility with other packages that might share those dependencies. Therefore, project's dependencies are not in scope for the issue. The dependencies we should pin are only the ones used in Github Workflows. 

> Is there a more automated tool that applies to secure dependency management, for both public projects like this one and private projects? (nix comes to mind, but I'm not an expert on security ...)

I only know about the Dependency Update Tools for managing version updates, like dependabot, which understands the requirements.in/.txt formats and will automatically update version/hash pins.

> What if a language doesn't support multi-version dependencies (like Python), The environment can only have one version of a specific package: error if: A <- {C.0, B.2}, B.2 <- {C.1} (C is different) We can't pin the version in this case and have to allow dependency solver to do its work.

That's the main reason why subdependencies of libraries **should never** be pinned (either version or hash pinned). Here we are only considering pinning dependencies used or referred in action workflows that could represent a risk to the github project and compromise it somehow. The project's dependencies (which the users rely on) should be defined in a way that covers the greatest amount of versions as possible.

The main thing that the hash pinning check is trying to solve for workflows is introducing determinism: if we are not version/hash pinned, we can't really reason that the build workflow is secure or will succeed, because it might become compromised or broken when a new version is published. 

If we also [enable the Dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates) in this PR or in a future discussion, it would automatically update both the versions and hashes, let me know if you are interested in that.

**Comment by joycebrum** [comment]
I created a DRAFT for you to be able to see what changes I'm working on and question wheter they really should or should not be pinned, mostly the ones that are also xgboost library dependencies and that the users rely on
