### ISSUE TITLE
Target `federated_proto` is not installed, resulting in missing library dependency missing

### ISSUE THREAD

**Issue by gnaggnoyil** [dmlc/xgboost#8439]
When `PLUGIN_FEDERATED` is set to `ON`, target `federated_proto` is built and linked to the main `xgboost` target. However, no installation rule is specified for `federated_proto`. Thus, on a Linux platform, when `BUILD_SHARED_LIBS` is set to `ON`, the installed `libxgboost.so` will link with `libfederated_proto.so` but cannot find it in its installation path.

Steps to reproduce:

```
cd xgboost && mkdir build && cd build
cmake -DPLUGIN_FEDERATED=ON -DBUILD_WITH_CUDA_CUB=ON -DUSE_CUDA=ON -DUSE_NCCL=ON \
    -DCMAKE_INSTALL_PREFIX=install -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release ..
cmake --build . --config Release
cmake --install . --config Release
ldd install/lib/libxgboost.so | grep federated
```

The output for the last command will then be
```
        libfederated_proto.so => not found
```
which is not expected.

This issue can be constantly reproduced with current master(8e76f5f). My environment is Archlinux, with all packages installed from official repository and having version as of date 2022-11-07. Required packages are installed using `pacman -S base-devel cmake cuda nccl grpc`. CUDA version is 11.8 and GCC version is 12.2.

**Comment by trivialfis** [comment]
@rongou Could you please help take a look when you are available?

**Comment by rongou** [comment]
In my environment I'm seeing both `libdmlc.so` and `libfederated_proto.so` as `not found`.

**Comment by rongou** [comment]
Never mind, `libdmlc.so` is indeed copied, just need to run `ldconfig` for it to show up. I think I have a fix for `libfederated_proto.so`, sending a PR.
