### ISSUE TITLE
Trouble when importing xgboost

### ISSUE THREAD

**Issue by mehdiBarch** [dmlc/xgboost#844]
When I try to import xgboost after building I get the following error.
Does anyone know where it can come from?
Thanks

---------------------------------------------------------------------------
WindowsError                              Traceback (most recent call last)
<ipython-input-1-a31cf591fdb6> in <module>()
---> 13 import xgboost as xgb

C:\Users\Mehdi\Anaconda2\lib\site-packages\xgboost-0.4-py2.7.egg\xgboost\__init__.py in <module>()
      9 import os
     10 
---> 11 from .core import DMatrix, Booster
     12 from .training import train, cv
     13 try:

C:\Users\Mehdi\Anaconda2\lib\site-packages\xgboost-0.4-py2.7.egg\xgboost\core.py in <module>()
     81 
     82 # load the XGBoost library globally
---> 83 _LIB = _load_lib()
     84 
     85 def _check_call(ret):

C:\Users\Mehdi\Anaconda2\lib\site-packages\xgboost-0.4-py2.7.egg\xgboost\core.py in _load_lib()
     75     if len(lib_path) == 0:
     76         return None
---> 77     lib = ctypes.cdll.LoadLibrary(lib_path[0])
     78     lib.XGBGetLastError.restype = ctypes.c_char_p
     79     return lib

C:\Users\Mehdi\Anaconda2\lib\ctypes\__init__.pyc in LoadLibrary(self, name)
    441 
    442     def LoadLibrary(self, name):
--> 443         return self._dlltype(name)
    444 
    445 cdll = LibraryLoader(CDLL)

C:\Users\Mehdi\Anaconda2\lib\ctypes\__init__.pyc in __init__(self, name, mode, handle, use_errno, use_last_error)
    363 
    364         if handle is None:
--> 365             self._handle = _dlopen(self._name, mode)
    366         else:
    367             self._handle = handle

WindowsError: [Error 126] Le module spécifié est introuvable

**Comment by Karan-Bhatti** [comment]
MehdiBarch i am facing a similar issue. How have you managed to resolve it?

**Comment by mehdiBarch** [comment]
Hi Karan-Bhatti,

I don't really know why but after I restarted my computer the issue was fixed and I was able to import xgboost.
