### ISSUE TITLE
[Python-packages] save_model ignored parameters with numpy.int32 type

### ISSUE THREAD

**Issue by seanslma** [dmlc/xgboost#8458]
When the model parameter data type is numpy.int32 the parameters are not saved due to `numpy.int32` not being JSON serializable. 

If these parameters are a part of the model, we should convert the value type from `numpy.int32` to `int` so they can be included in the saved model parameters.

```
site-packages/xgboost/sklearn.py:722:
    warnings.warn(str(k) + ' is not saved in Scikit-Learn meta.', UserWarning)
UserWarning: n_estimators is not saved in Scikit-Learn meta.
UserWarning: max_depth    is not saved in Scikit-Learn meta.
UserWarning: reg_alpha    is not saved in Scikit-Learn meta.
UserWarning: reg_lambda   is not saved in Scikit-Learn meta.
```

**Comment by trivialfis** [comment]
Thank you for raising the issue. I'm thinking about not saving those training hyper-parameter in save model function since they are not related to the model itself but rather for the training algorithm and has no use after training

**Comment by seanslma** [comment]
Thanks for the clarification. 
Makes sense not to save these parameters.
I was confused by the warnings because I did not realise these parameters are actually not part of the model. 
It would be great to update the warning message or avoid raising warning so the users will not be confused.

**Comment by trivialfis** [comment]
The issue still needs to be addressed instead of leaving it as a warning.

**Comment by giladmaya** [comment]
Is this issue up for grabs?
