### ISSUE TITLE
Pandas 8-bit nullable integer type not supported

### ISSUE THREAD

**Issue by andreostrovsky** [dmlc/xgboost#8466]
#7760 added support for Pandas nullable integer types. Yet it only added support for `Int16`, `Int32`, and `Int64`; not `Int8`. Is there a reason this was excluded?

Pandas has a commonly used function to reduce DataFrame size `to_numeric(series, downcast='integer')`, which reduces the specified series to the smallest nullable integer type that fits the data, including `Int8`.

Currently, users need to then explicitly convert `Int8` columns to `Int16` so as to avoid xgboost error `DataFrame.dtypes for data must be int, float, bool or category. ...`

Using:
- xgboost 1.7.1
- pandas 1.5.1

**Comment by trivialfis** [comment]
At the time I just tried to implement support for whatever was listed by the pandas' doc about nullable type.
