### ISSUE TITLE
issue xgb.plot.tree

### ISSUE THREAD

**Issue by antoinemrcr** [dmlc/xgboost#847]
Hello,
I am using xgb with Rstudio, and I have installed DiagrammeR.
I have an issue while trying to plot a tree : instead of having a tree, I get a kind of html script, like that :
Gain: 14.1299)-->|< 13.0085|0-165>Leaf];0-95(67)-->|>= 3.93113|0-168>Leaf];0-95(67
Cover: 1549.5
Gain: 15.9918)-->|< 3.93113|0-167>Leaf];0-96(977)-->|>= -3.44202|0-170>Leaf];0-96(977
Cover: 153.5
Gain: 9.96063)-->|< -3.44202|0-169>Leaf];0-97(254)-->|>= -1.00136e-005|0-172>Leaf];0-97(254
Does someone know how to fix this ?

Thank you

**Comment by pommedeterresautee** [comment]
Use last version of xgboost from Github.
