### ISSUE TITLE
[FEA]Custom Sample Method Request

### ISSUE THREAD

**Issue by ysq151944** [dmlc/xgboost#8477]
I want to use custom sample method in training, so it would be great if xgb api could:

1. provide a param like "obj" or "custom_metric"

OR

2.  provide a param looks like "samples" to receive np.ndarray that carries the exact indices of dtrain.  
For example:
np.array([[1, 3, 5, 7, 9], [2, 4, 6, 8, 10], [1, 2, 3, 4, 5]]) provides 3 samples to fit the model.

I personally prefer the second one as some sample methods are too complicated to be abstracted into a simple function.

**Comment by ysq151944** [comment]
> Thank you for rasing the issue. The simplest way to achieve what you want is to define your custom objective function and set the hessian to 0 for disabled samples.

Hi, I don't understand why set the hessian to 0 for disabled samples works. 

Do you mean that I should set sampling_method='gradient_based' and then set g = h = 0 for disabled samples?

**Comment by trivialfis** [comment]
Don't set sampling for XGBoost if you were to have your own sampling strategy.

> Hi, I don't understand why set the hessian to 0 for disabled samples works.

XGBoost is based on the newton method, 0 hessian for a sample implies that the sample won't contribute to the optimization.
