### ISSUE TITLE
Does xgboost PySpark support categorical feature split ?

### ISSUE THREAD

**Issue by yananchen1989** [dmlc/xgboost#8482]
Hello, it seems that xgboost -pyspark https://xgboost.readthedocs.io/en/stable/tutorials/spark_estimator.html has not talked about whether it supports categorical features. 

Besides, I also haven't found it in https://xgboost.readthedocs.io/en/latest/jvm/xgboost4j_spark_tutorial.html, where the Iris dataset example only has numeric features.

Does it support that ?

Thanks.

**Comment by trivialfis** [comment]
Not yet. The progress for categorical feature support is being tracked here: https://github.com/dmlc/xgboost/issues/7899 .
