### ISSUE TITLE
Release 1.7.2 for fix "Make QDM optional based on cuDF check"

### ISSUE THREAD

**Issue by WeichenXu123** [dmlc/xgboost#8490]
We need a patch release 1.7.2 that containing fix https://github.com/dmlc/xgboost/pull/8471
Thank you!

**Comment by WeichenXu123** [comment]
CC @trivialfis @hcho3 Thank you!

**Comment by trivialfis** [comment]
Will open a new issue and make a couple of backports. At the same time, feel free to visit the github project for the patch release and make suggestions.

**Comment by WeichenXu123** [comment]
@trivialfis Thank you!
