### ISSUE TITLE
Performance comparison report with regard to processing categorical features?

### ISSUE THREAD

**Issue by yananchen1989** [dmlc/xgboost#8495]
Hi, as we know, when processing categorical features, the traditional method is one-hot encoding, https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html

as from 1.6 and 1.7 on, xgboost now supports directly split in categorical space.

I would like to know is there any performance comparison with regard to these different lines of processing ? for example on some public kaggle dataset ?
Do they perform the same level ?

Thanks.

**Comment by trivialfis** [comment]
We have some initial benchmarks, but are still working on parameter tuning for finalizing the default set of parameters. Will publish them once ready. The issue is tracked at https://github.com/dmlc/xgboost/issues/7899 .
