### ISSUE TITLE
Question about predictions

### ISSUE THREAD

**Issue by ivihrov** [dmlc/xgboost#85]
Hi Tianqi,
Thank you for this great utility! It works incredible fastly.
I have next question. I need to imlement prediction for constructed model via other programming language. I already did it for gbm model from R package 'gbm' and sum of all trees (all selected tree leafs)  I should add to initial value. 
In xgboost model dump I don't see  the initial value. Does it mean that initial value equals 0? Thanks.

**Comment by EEthinker** [comment]
Hi Tianqi, I really appreciate your amazing work on XGBoost! I am still not clear about the meaning of the base_score and margin. How does it affect the training process?
