### ISSUE TITLE
can somebody give a detailed tutorial about deploying xgboost on yarn

### ISSUE THREAD

**Issue by wenmin-wu** [dmlc/xgboost#851]
I have deployed xgboost on a single machine, in order to accelerate the model training I try to deploy xgboost on yarn. I can't find a detailed tutorial about how to deploy xgboost on yarn. 

One special problem to me: The gcc version in the cluster is 4.4.7 20120313 (Red Hat 4.4.7-4) (GCC), I want to know how can I run xgboost on yarn without upgrading all the gcc version in the cluster?

**Comment by tqchen** [comment]
Try the option ship-libcxx
