### ISSUE TITLE
Issue with max_delta_step when using XGBRegressor with "count:poisson" as objective

### ISSUE THREAD

**Issue by ahmed-touati** [dmlc/xgboost#853]
When I use XGBRegressor (the sklearn wrapper) with "count:poisson" as objective, I obtained 
`XGBoostError: PoissonRegression: need to set max_delta_step`
So I sat  max_delta_step to 0.7 as mentioned in the doc of parameters:
"max_delta_step is set to 0.7 by default in poisson regression (used to safeguard optimization)"
It works but the problem that I obtained poor performance and convergence comparing to the case when I use directly the API xgboost.train() and without setting value max_delta_step.
Could you have any idea about this huge difference of performance ? please

Thank you in advance

**Comment by tqchen** [comment]
Interesting, I have no idea on what happens, perhaps what you can do is look into the routine that calls into xgb.train(since all calls of sklearn api redirects into it) and see what was the difference in terms of configurations parameters
