### ISSUE TITLE
Can you please share the code to identify feature importances in YARN(HDFS) Implementaion?

### ISSUE THREAD

**Issue by astrude** [dmlc/xgboost#855]
I also want to know if I want to use Grid search for Hyper parameter optimization from SKLearn, How do I do that? How can we implement Sklearn using YARN? Thanks in advance!

**Comment by tqchen** [comment]
To answer your question about feature importance. The model is compatible between difference languages as well as distributed version, so you can load the model using any single machine API you like and visualize the feature importance

**Comment by tqchen** [comment]
The grid search with sklearn is not yet possible, currently only CLI version is enabled. We will see if we can enable python version later

**Comment by astrude** [comment]
Thanks a lot for the input. Able to extract feature importance for my assignment. :)
