### ISSUE TITLE
what is the path used by ./xgboost to find the libhdfs.so.0.0.0

### ISSUE THREAD

**Issue by wenmin-wu** [dmlc/xgboost#856]
the hadoop version in our cluster is CDH, so there is no libhdfs.so.0.0.0 file under `/usr/lib/hadoop/lib/native/` directory. So I compile the hadoop-hdfs-project using cmake to get the libhdfs.so file for xgboost making. After I had successfully maked the xgboost, and run it on yarn. It come out with the following error:
./xgboost: error while loading shared libraries: libhdfs.so.0.0.0: cannot open shared object file: No such file or directory
I want to know how I can add the libhdfs.so.0.0.0 file to the yarn environment ?

**Comment by wenmin-wu** [comment]
add `-f ${libhdfs.so.0.0.0_path}` to ship this file

**Comment by antant-shenzhen-2013** [comment]
I have the same problem here. DO you mean  add option -f when `dmlc-submit`?

**Comment by antant-shenzhen-2013** [comment]
@superbobry I follow your script to compile .so files. 
BUT when `dmlc-submit`

> /home/luwl/github/xgboost/dmlc-core/tracker/dmlc-submit\
>             --cluster=yarn --num-workers=4 --worker-cores=4 --worker-memory=16G --queue=root.ad\
>             -f /usr/lib/hadoop/lib/native/libhdfs.so.0.0.0\
>             /home/luwl/github/xgboost/xgboost /home/luwl/github/xgboost/demo/distributed-training/mushroom.aws.conf.small\
>             nthread=4\
>             data=hdfs://nameservice1/user/luwl/dsp/data/xgboost/small-train\
>             eval[test]=hdfs://nameservice1/user/luwl/dsp/data/xgboost/small-test\
>             model_dir=hdfs://nameservice1/user/luwl/dsp/model/ctr-xgboost-model-small

many containers show the following errors:
> Container: container_e06_1510835833211_1431884_01_000009 on nfjd-hadoop02-node355.jpushoa.com_8041
> 
> LogType:stderr
> Log Upload Time:Fri Jan 26 14:41:19 +0800 2018
> LogLength:0
> Log Contents:
> 
> LogType:stdout
> Log Upload Time:Fri Jan 26 14:41:19 +0800 2018
> LogLength:32
> Log Contents:
> Usage: launcher.py your command


any suggestion?
