### ISSUE TITLE
Cross validation does not  print any results out 

### ISSUE THREAD

**Issue by alexander-rakhlin** [dmlc/xgboost#857]
I mean, during cross-validation demos in cross_validation.py pass but do not output anything like:

 [iteration]  metric_name:mean_value+std_value   

xgboost version 0.47 on Ubuntu 
Tried both pip install and manual install, no effect

xgb.train(), on contrary, prints its progress

**Comment by pommedeterresautee** [comment]
recent version prints these values.
Bug related to an old version, closing.
