### ISSUE TITLE
Keep optional dependecy on sklearn

### ISSUE THREAD

**Issue by tqchen** [dmlc/xgboost#858]
The python API has been evolved and add some good features. 
However, some changes also introduces explicit dependency on sklearn, and currently xgboost is not able to run when sklearn is not installed.

The original goal of compact.py is to make dependency on sklearn optional and only on sklearn.py , while making rest of API only depend on numpy and scipy. This can help users who may not yet have sklearn available, as well as making shipping to distributed version easy.

I think would like to correct this, as well as add a test env excluding the dependencies making sure basic tests pass. 

@terrytangyuan can you look into this?

**Comment by terrytangyuan** [comment]
Sounds good. I'll look into this soon.
