### ISSUE TITLE
Improper counting of category columns

### ISSUE THREAD

**Issue by roshkins** [dmlc/xgboost#8586]
https://github.com/dmlc/xgboost/blob/15a88ceef0f60d461925bb5133716ab67de6ca8e/python-package/xgboost/data.py#L677

If I have columns, some categorical, some not, the `i` value improperly indexes `cat_codes` since i is incremented even if the column is not categorical.

I have a suggested fix, which is to keep count of non-categorical columns and subtract it from `i`. I'll create a PR for this issue.

**Comment by trivialfis** [comment]
Hi, thank you for raising the issue. Have you tested the code? https://github.com/dmlc/xgboost/blob/15a88ceef0f60d461925bb5133716ab67de6ca8e/python-package/xgboost/data.py#L750 When column is numeric, the cat_codes contains an empty list.

**Comment by trivialfis** [comment]
Closing due to lack of response. Feel free to reopen if there's new info.
