### ISSUE TITLE
[R] compilation failure with missing libexecinfo on Alpine Linux 3.17

### ISSUE THREAD

**Issue by bastistician** [dmlc/xgboost#8595]
Related to #5232.

Alpine Linux >= 3.17 [no longer provides libexecinfo](https://gitlab.alpinelinux.org/alpine/aports/-/commit/50795a14dee639ce2dcc836e2b2baca9bad4a1b1).
Without that, installation of the xgboost R package 1.6.0.1 from CRAN fails as follows:

```
* installing *source* package 'xgboost' ...
** package 'xgboost' successfully unpacked and MD5 sums checked
** using staged installation
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking Backtrace lib... 
checking for backtrace in -lexecinfo... no
checking endian... 
configure: creating ./config.status
config.status: creating src/Makevars
** libs
Makevars:17: -DXGBOOST_STRICT_R_MODE=1
Makevars:17: -DDMLC_LOG_BEFORE_THROW=0
Makevars:17: -DDMLC_ENABLE_STD_THREAD=1
Makevars:17: -DDMLC_DISABLE_STDIN=1
Makevars:17: -DDMLC_LOG_CUSTOMIZE=1
Makevars:17: -DXGBOOST_CUSTOMIZE_LOGGER=1
Makevars:17: -DRABIT_CUSTOMIZE_MSG_
g++ -std=gnu++14 -I"/usr/include/R" -DNDEBUG -I./include -I./dmlc-core/include -I./rabit/include -I. -DXGBOOST_STRICT_R_MODE=1 -DDMLC_LOG_BEFORE_THROW=0 -DDMLC_ENABLE_STD_THREAD=1 -DDMLC_DISABLE_STDIN=1 -DDMLC_LOG_CUSTOMIZE=1 -DXGBOOST_CUSTOMIZE_LOGGER=1 -DRABIT_CUSTOMIZE_MSG_  -O2 -fomit-frame-pointer  -fopenmp -DDMLC_CMAKE_LITTLE_ENDIAN=1 -pthread -fvisibility=hidden -fpic  -O2 -fomit-frame-pointer -D__MUSL__ -flto -c xgboost_R.cc -o xgboost_R.o
In file included from ./dmlc-core/include/dmlc/././base.h:336,
                 from ./dmlc-core/include/dmlc/./logging.h:16,
                 from ./dmlc-core/include/dmlc/common.h:14,
                 from xgboost_R.cc:4:
./dmlc-core/include/dmlc/build_config_default.h:27:29: fatal error: execinfo.h: No such file or directory
   27 |     #define DMLC_EXECINFO_H <execinfo.h>
      |                             ^
compilation terminated.
make: *** [/usr/lib/R/etc/Makeconf:176: xgboost_R.o] Error 1
ERROR: compilation failed for package 'xgboost'
* removing '/tmp/lib/xgboost'
```

A rather minimal Dockerfile to reproduce is

```Dockerfile
FROM alpine:3.17
ENV TZ=UTC
RUN apk add --no-cache R R-dev R-doc g++
RUN R -s -e 'install.packages("xgboost", repos = "https://cloud.R-project.org/")'
```

FWIW, I have worked around this problem in my own build of R (in which I set `CXXFLAGS += -D__MUSL__`) by patching the CRAN package as follows:

```diff
--- orig/src/dmlc-core/include/dmlc/build_config_default.h
+++ patched/src/dmlc-core/include/dmlc/build_config_default.h
@@ -18,6 +18,7 @@
 
 /* default logic for stack trace */
 #if (defined(__GNUC__) && !defined(__MINGW32__)\
+     && !defined(__MUSL__)\
      && !defined(__sun) && !defined(__SVR4)\
      && !(defined __MINGW64__) && !(defined __ANDROID__))\
      && !defined(__CYGWIN__) && !defined(__EMSCRIPTEN__)\
```

However, this is no general solution as [`__MUSL__` is not defined by default in musl](<https://www.openwall.com/lists/musl/2013/03/29/13>).

**Comment by hcho3** [comment]
We'd need to detect if execinfo.h is unavailable and set the macro definition DMLC_LOG_STACK_TRACE=0 in CXXFLAGS.

**Comment by hcho3** [comment]
Would you like to file a pull request to update configure.ac ?

**Comment by bastistician** [comment]
Sorry, I cannot provide a PR at this time.

**Comment by trivialfis** [comment]
@bastistician no worries, thank you for raising the issue.

@hcho3 Seems all we need to do is to add the DMLC macro to https://github.com/dmlc/xgboost/blob/43a647a4ddd6dd0b5cdbb26d265f5598b86404e2/R-package/configure.ac#L13 ?

**Comment by zamazan4ik** [comment]
*quite offtopic*

By the way, in the topic starter's build log, I see `-flto` flag but cannot find there it configured in xgboost sources. Could anyone point me out - where LTO is enabled?

**Comment by asross** [comment]
Any updates on this / any chance there could be a musl wheel @hcho3?

**Comment by hcho3** [comment]
Not yet. None of core developers use Alpine Linux. Would love to get some help.

**Comment by bastistician** [comment]
I think your and @trivialfis' initial suggestion of defining `DMLC_LOG_STACK_TRACE=0` via configure still applies. In addition, the configure script needs to check if `fopen64` is available (it is not in musl) and otherwise define `DMLC_USE_FOPEN64=0`.

The patch below works for me (note that it is based on a checkout of the R package from CRAN, so paths are relative to the "R-package" directory in this repository, I suppose). I am not that fluent in autoconf, so please check, also regarding your code style. Just to be sure, someone should verify that fopen64 is still used if it is available. Remember to regenerate the configure script based on this patch (I have a different version of autoconf installed, so didn't include the diff here, which would be unnecessarily large).

```diff
diff --git a/configure.ac b/configure.ac
index ae6c7c4..9e4af7f 100644
--- a/configure.ac
+++ b/configure.ac
@@ -22,10 +22,17 @@ CPPFLAGS=`"${R_HOME}/bin/R" CMD config CPPFLAGS`
 LDFLAGS=`"${R_HOME}/bin/R" CMD config LDFLAGS`
 AC_LANG(C++)
 
+DMLC_DEFS=""
+
 ### Check whether backtrace() is part of libc or the external lib libexecinfo
 AC_MSG_CHECKING([Backtrace lib])
 AC_MSG_RESULT([])
-AC_CHECK_LIB([execinfo], [backtrace], [BACKTRACE_LIB=-lexecinfo], [BACKTRACE_LIB=''])
+AC_CHECK_LIB([execinfo], [backtrace],
+             [BACKTRACE_LIB=-lexecinfo],
+             [BACKTRACE_LIB=''; DMLC_DEFS="$DMLC_DEFS -DDMLC_LOG_STACK_TRACE=0"])
+
+### Check whether fopen64 is available
+AC_CHECK_FUNC(fopen64, [], [DMLC_DEFS="$DMLC_DEFS -DDMLC_USE_FOPEN64=0"])
 
 ### Endian detection
 AC_MSG_CHECKING([endian])
@@ -72,5 +79,6 @@ AC_SUBST(OPENMP_CXXFLAGS)
 AC_SUBST(OPENMP_LIB)
 AC_SUBST(ENDIAN_FLAG)
 AC_SUBST(BACKTRACE_LIB)
+AC_SUBST(DMLC_DEFS)
 AC_CONFIG_FILES([src/Makevars])
 AC_OUTPUT
diff --git a/src/Makevars.in b/src/Makevars.in
index eff731a..d626733 100644
--- a/src/Makevars.in
+++ b/src/Makevars.in
@@ -16,7 +16,7 @@ ifeq ($(R_OSTYPE)$(WIN),windows)
 endif
 $(foreach v, $(XGB_RFLAGS), $(warning $(v)))
 
-PKG_CPPFLAGS=  -I$(PKGROOT)/include -I$(PKGROOT)/dmlc-core/include -I$(PKGROOT)/rabit/include -I$(PKGROOT) $(XGB_RFLAGS)
+PKG_CPPFLAGS=  -I$(PKGROOT)/include -I$(PKGROOT)/dmlc-core/include -I$(PKGROOT)/rabit/include -I$(PKGROOT) @DMLC_DEFS@ $(XGB_RFLAGS)
 PKG_CXXFLAGS= @OPENMP_CXXFLAGS@ @ENDIAN_FLAG@ -pthread $(CXX_VISIBILITY)
 PKG_LIBS = @OPENMP_CXXFLAGS@ @OPENMP_LIB@ @ENDIAN_FLAG@ @BACKTRACE_LIB@ -pthread
 
```

**Comment by asross** [comment]
@bastistician if you could make this a PR that would be incredibly helpful, I know pretty much nothing about C build pipelines but we have an app that runs on Alpine and I can't deploy any code using XGBoost to it :(

**Comment by pat-s** [comment]
Building also works if `CXXFLAGS` are appended with the following arg: `-DDMLC_USE_FOPEN64=0`.

Nevertheless I agree that the configure script should be fixed upstream so that users don't have to account for this locally.

**Comment by bastistician** [comment]
So I've now spent some time to submit the changes as a formal PR (#11025) that also includes the re-generated `configure` file. Works for me on both Ubuntu and Alpine Linux. Note that the original idea of adding `-DDMLC_LOG_STACK_TRACE=0` to the `AC_CHECK_LIB()` wasn't quite right as that would have disabled stack traces whenever `libexecinfo` wasn't used.

**Comment by bastistician** [comment]
While this was fixed here on GitHub: it would be great to get the release on CRAN patched as well. On Alpine Linux, the standard `install.packages("xgboost")` still fails with the reported error. Thanks!
