### ISSUE TITLE
[CI] cudaErrorInsufficientDriver returned from cudaGetDevice

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#8619]
https://github.com/dmlc/xgboost/blob/c6a8754c62496e43452e6edf49eb0eb89ffcdc70/tests/cpp/helpers.cc#L632

This line is currently failing in the CI due to a driver issue. It's part of the GTest with RMM
Until the CI machine can be updated with the latest driver, we'll disable the GTest with RMM.

**Comment by trivialfis** [comment]
Is this still an issue?

**Comment by hcho3** [comment]
Not sure, we need to try re-enabling gtest with rmm and see if it works
