### ISSUE TITLE
how can I port the model in c++?

### ISSUE THREAD

**Issue by awen111** [dmlc/xgboost#862]
I trained the model using python, but I want to port the model in my application developed using c++. what can i do? are there any documents about that? or an example tourist about c++ development ? all the existing examples are for python, R, or JAVA, Julia, no c++.

**Comment by thirdwing** [comment]
Maybe you can check the C API in https://github.com/dmlc/xgboost/blob/master/src/c_api/c_api.cc

**Comment by drag0** [comment]
@awen111 
I trained XGBoost model with Python and then generated C++ code from XGBoost's raw model dump. Here is my code: https://github.com/drag0/xgb2cpp
