### ISSUE TITLE
Hist Tree Method Discrepancies

### ISSUE THREAD

**Issue by amzn-choeric** [dmlc/xgboost#8622]
Hello. I am opening this issue on behalf of someone. Basically, they are wondering if there is anything within the roadmap/if it was possible to not have varying prediction results for the "hist" tree method based off the number of workers used in a training job. From what I can see from past issues on here and the code itself, this seems to be expected behavior. However, I believe they wanted further insight from someone on here.

Please let me know if any further specifics are needed for this inquiry.

**Comment by trivialfis** [comment]
Hi, the training result varies based on the number of workers. However, once the model is trained, the inference should be consistent and independent of the number of workers. Could you please share what is your expectation?

**Comment by amzn-choeric** [comment]
They were basically expecting to see the same prediction results from a model generated from one training job with 16 instances and another one generated with just 1 instance. In other words, their concern was with the inconsistency between two models generated from two different jobs with a different number of instances with all other configurations kept the same (no subsampling of course) as opposed to inference on the same model with varying number of workers.

As you have noted, I have communicated that this is expected behavior. I think they just wanted additional confirmation from someone on here and for me to ask for them if their original expectation is practical/feasible through changes within this library. It does not seem like it from my perspective, but I am also not as familiar with some specifics as some others might be.

**Comment by atahmasb** [comment]
@trivialfis as @amzn-choeric mentioned we see discrepancy between predictions during inference when we train two models using the exact data and configuration for a regression task. The only change is the number of instances we use for training. Basically every time we a train a new model using the same data and configuration on multiple instances we get different predictions.  The discrepancy is significant, for some data points, the discrepancy in predictions is more than 4000%. Is this expected behaviour?

**Comment by trivialfis** [comment]
Thank you for the clarification. The significance is highly data-dependent. Decision trees are quite sensitive to the change in the gain function (and the histogram approximation of it). With one small change in the floating point number, we can grow an entirely different decision tree, which will in turn change all the following trees to be grown.

For distributed training, the primary source of discrepancy is the sketching algorithm used to calculate the quantile of data, which is used for the histogram bins. Sketching is an approximate algorithm and depends on the number of workers for merge operations. Unless there's new research into this area it's expected to have this discrepancy. Having said that, suggestions are welcomed!

**Comment by amzn-choeric** [comment]
Thanks for the confirmation!
