### ISSUE TITLE
what does CalcDelta and CalcDeltaBias based on of class GBLinearTrainParam

### ISSUE THREAD

**Issue by joseph-chan** [dmlc/xgboost#865]
Dear TianQi:
The GBLinearTrainParam defines calcDelta and CalcDeltaBias as following:
   // given original weight calculate delta
 inline double CalcDelta(double sum_grad, double sum_hess, double w) const {
    if (sum_hess < 1e-5f) return 0.0f;
    double tmp = w - (sum_grad + reg_lambda \* w) / (sum_hess + reg_lambda);
    if (tmp >=0) {
      return std::max(-(sum_grad + reg_lambda \* w + reg_alpha) / (sum_hess + reg_lambda), -w);
    } else {
      return std::min(-(sum_grad + reg_lambda \* w - reg_alpha) / (sum_hess + reg_lambda), -w);
    }
  }
 inline double CalcDeltaBias(double sum_grad, double sum_hess, double w) const {
      return - (sum_grad + reg_lambda_bias \* w) / (sum_hess + reg_lambda_bias);
  }

what was the foudamental theory based on ? could you explain a little more?

**Comment by tqchen** [comment]
These are update rule derived from coordinate wise descent update
