### ISSUE TITLE
[CI] Test failure with nightly pyspark.

### ISSUE THREAD

**Issue by trivialfis** [dmlc/xgboost#8655]
https://buildkite.com/xgboost/xgboost-ci/builds/1243#01859cdb-c576-4b6c-a2cc-43434b71992a

Maybe I should revert the changes to the conda environment?

**Comment by trivialfis** [comment]
Seems to be affecting 1.7 as well: https://buildkite.com/xgboost/xgboost-ci/builds/1265 .

**Comment by hcho3** [comment]
I'm investigating now. It's weird that the CI only fails on branches but not on pull requests. Ugh...

**Comment by trivialfis** [comment]
@hcho3 Thank you for looking into it. Let me know if there's anything I can help.

I tried to run the CI script on my local machine but couldn't reproduce it. Do you know how to reproduce the issue?

**Comment by hcho3** [comment]
@trivialfis Try this instead:
```
tests/ci_build/ci_build.sh cpu docker -it tests/ci_build/build_via_cmake.sh
tests/ci_build/ci_build.sh cpu docker -it tests/ci_build/test_python.sh cpu
```

**Comment by trivialfis** [comment]
all pyspark tests passed ...

**Comment by hcho3** [comment]
On my machine I reproduced the failure. Can you try clearing the Docker cache on your machine?
```
docker rm -vf $(docker ps -aq)
docker rmi -f $(docker images -aq)
docker volume prune -f
```

**Comment by hcho3** [comment]
Probably. See https://stackoverflow.com/questions/61267495/exception-in-thread-main-java-lang-nosuchmethoderror-java-nio-bytebuffer-flip

**Comment by trivialfis** [comment]
seems fine:
javac -version
javac 1.8.0_352

**Comment by trivialfis** [comment]
I think it's an issue with the nightly pyspark binary. I downgraded the pyspark to 3.3.1 and the error disappears. We might want to disable tests with sparse input for now.

cc @WeichenXu123 .

**Comment by trivialfis** [comment]
Opened a PR to skip the tests for now: https://github.com/dmlc/xgboost/issues/8655

**Comment by hcho3** [comment]
@WeichenXu123 

Is `pyspark-3.4.0.dev0.tar.gz` hosted by Databricks? Was it compiled using Java 8?

https://github.com/dmlc/xgboost/blob/badeff1d747c2b7035bb89b73c1d3436a6b1af7f/tests/ci_build/conda_env/linux_cpu_test.yml#L42-L45
