### ISSUE TITLE
xgboost integration with sklearn-evaluation for visualization

### ISSUE THREAD

**Issue by idomic** [dmlc/xgboost#8656]
Any plans on integrating with [sklearn-evaluation](https://github.com/ploomber/sklearn-evaluation)?
It has more capabilities (bug fixes + new features) and is well-maintained.
Happy to assist!

This will allow users to get out of the box visualizations

**Comment by trivialfis** [comment]
Hi, since XGBoost has a sklearn estimator interface, is there anything we need to do to support sklearn-evaluation?
