### ISSUE TITLE
CRAN packages not using the correct compiler in configure scripts

### ISSUE THREAD

**Issue by trivialfis** [dmlc/xgboost#8663]
That is

C50 Cubist GPBayes RDieHarder RPostgreSQL RcppGSL RhpcBLASctl Rmixmod
Rrdrand SimInf SymTS eaf excursions fRLR ff float getip git2r gsl gslnls
hdf5r island memuse mmap ore poismf randtoolbox rayrender rgeolocate
rmatio rnetcarto rngWELL scrypt survSNP xgboost

These show

checking for gcc... gcc

even on platforms using clang as the compiler.  Please re-read

https://cran.r-project.org/doc/manuals/r-devel/R-exts.html#Configure-and-cleanup

There need be no 'gcc' compiler, it might be faked (macOS) or very old
(Solaris).  The aim of a configure script is to test things using the
same setup as will be used to compile code in the package.

In several cases you are using a C compiler in configure but a C++
compiler to compile the code: they usually have access to different
headers.  Looks like this is the case in at least

GPBayes RcppGSL Rmixmod fRLR ff rayrender xgboost

The logs showing

        checking for gcc option to accept ISO C89... none needed

need configure rebuilt with a modern autoconf, which will check C11 (and
that or C17 are the default in all the current compilers we know of --
however, that old autoconf test will fail when C23 comes into use).

Please correct before 2023-01-26 to safely retain your package on CRAN.

--
Brian D. Ripley,                  [ripley@stats.ox.ac.uk](mailto:ripley@stats.ox.ac.uk)
Emeritus Professor of Applied Statistics, University of Oxford

**Comment by hcho3** [comment]
Since we've had trouble getting R tests working on XGBoost 1.7, I am skeptical that we'd be able to make the fix in time. We should prepare for the possibility of having XGBoost pulled from CRAN.

**Comment by trivialfis** [comment]
I think I can give it a go, at least for 1.6

**Comment by hcho3** [comment]
Maybe we should consider using an alternative distribution mechanism, like R-universe.

**Comment by trivialfis** [comment]
I think it's fine, working on other distributions is not less time consuming than fixing the issues on CRAN. I will take another look into the tests today and see how much work is needed.

**Comment by jameslamb** [comment]
I agree with @trivialfis , it is really worth trying to stay on CRAN. And especially for `{xgboost}`... if `{xgboost}` is removed from CRAN, all of these other packages will have to either quickly release a new version not depending on `{xgboost}` or also be removed:

<img width="1767" alt="Screen Shot 2023-01-12 at 10 21 59 AM" src="https://user-images.githubusercontent.com/7608904/212123183-05e6351d-b289-4043-936b-9be21abfe9f6.png">

(https://cran.r-project.org/web/packages/xgboost/index.html)

As annoying as it is to get these "fix this warning or we evict you in two weeks" emails from them. I know...I'm currently working on the second "fix something small to stay on CRAN" release LightGBM has had to do in the last month 😫 .

I can look into this today or tomorrow too if you'd like some additional help!

**Comment by jameslamb** [comment]
I think I already see at least one possible issue.

`{xgboost}` isn't getting information about the C and C++ compilers from R's configuration.

It's just relying on environment variables `CC` and `CXX`.

https://github.com/dmlc/xgboost/blob/72ec0c54841c03f9c7a81b72137234f2519273ab/R-package/configure.ac#L43

I think that'll need to change to something like this:

https://github.com/microsoft/LightGBM/blob/23403a7c2c4d38961506968291f13c3f344ccb6f/R-package/configure.ac#L16-L28

That's recommended in "Writing R Extensions": https://cran.r-project.org/doc/manuals/R-exts.html#Configure-and-cleanup

I won't be able to investigate and test that until about 10 hours from now, so just posting in case you're working on it right now and it's helpful.

**Comment by trivialfis** [comment]
I'm aiming to publish the 1.7 release:
- https://github.com/dmlc/xgboost/pull/8667
- https://github.com/dmlc/xgboost/pull/8668
- Still working on the configure script. The references shared by @jameslamb are incredibly helpful!

**Comment by hcho3** [comment]
@trivialfis Can we publish a patched version of 1.6 first, to be safe? As I recall there were unresolved test failures related to 1.7.

**Comment by trivialfis** [comment]
@hcho3 I will give 1.7 another try after all backports are made. If it fails then I will backport https://github.com/dmlc/xgboost/pull/8669 to 1.6 and submit it to CRAN. This way we don't upset the CRAN maintainers by making too many updates. What do you think?

**Comment by hcho3** [comment]
If you think we can pass all tests with 1.7, go ahead
