### ISSUE TITLE
Large multiclass classification

### ISSUE THREAD

**Issue by mikkelam** [dmlc/xgboost#870]
I have a large amount of classes: 4000 in my dataset of 800k lines of 65k features, very sparse and mostly binary features.
My question is, can XGBoost handle this efficiently?
Is there any feature hashing built into XGBoost?

**Comment by pommedeterresautee** [comment]
Best way to manage is to get some features shared by several class and some feature specific to one class.
There is no hashing implemented in XGBoost.

I close the issue because it is an old one.
Don t hesitate to reopen it if required.
