### ISSUE TITLE
Result discrepancy

### ISSUE THREAD

**Issue by kaushalkrishna2000** [dmlc/xgboost#8705]
Hello all,

I am facing a discrepancy in xgboost prediction using gpu.

Kaggle link: https://www.kaggle.com/code/kaushalkrishna2000/gpu-vs-cpu-xgb-house-price-prediction

Please help .

Thanks

**Comment by trivialfis** [comment]
Hi, could you please be more specific on the issue? Others are usually not very motivated to look through the notebook and make guesses about what's the question and expectations. ;-)
