### ISSUE TITLE
XGBRanker with sample_weight makes python interpreter died and restarted.

### ISSUE THREAD

**Issue by xbanke** [dmlc/xgboost#8708]
Sorry for submitting this issue. I really donot know how to solve this problem.
As the doc said, in ranking jobs, the `sample_weight` is assigned to each group but each data point, so I think the shape of sample_weight should be the same with `group`. But this make python iterpreter died and auto restarted when I run `fit`.
With some tracking, the problem maybe happend to the function `self._create_dmatrix`. It looks like that the shape of `sample_weight` needed to be the same with `y`.
Also, I tried with the shape of sample_weight equal to labels `y`, it raises `XGBoostError: [13:02:51] ../src/data/data.cc:683: Check failed: group_ptr_.size() == weights_.Size() + 1 (34 vs. 1001) : Size of weights must equal to number of groups when ranking group is used.`

```py
# python version: 3.9
# xgboost version: 1.7.3

import numpy as np
import pandas as pd
import xgboost as xgb

N = 1000
dates = pd.date_range('20100101', periods=N)
X = pd.DataFrame(np.random.randn(N, 5), columns=list('ABCDE'), index=dates)
y = pd.Series(np.random.randint(0, 10, size=N), index=dates, name='label')
group = X.groupby(dates + pd.offsets.MonthEnd(0)).size()
sample_weight = pd.Series(np.arange(len(group)), index=group.index)  # shape equal to group

ranker = xgb.XGBRanker(objective='rank:pairwise', max_depth=3, learning_rate=0.1, booster='gbtree', tree_method='hist', n_jobs=4, n_estimators=50, enable_categorical=False, random_state=42)

ranker.fit(X=X, y=y, group=group, sample_weight=sample_weight, verbose=True)  # it died here without any error info

```

**Comment by xbanke** [comment]
when to release the next version?

**Comment by trivialfis** [comment]
Soon.
