### ISSUE TITLE
Results not same after updating xgboost

### ISSUE THREAD

**Issue by hwu84** [dmlc/xgboost#871]
Hi,

I used the version from 2015 November all the time and yesterday I updated xgboost to latest version. However, when I try to reproduce the same procedure (same seed), the output different a lot. It is a binary classification task, the old version has optimal train-auc:0.99, test-auc:0.937 and the latest version has optimal train-auc:0.984, test-auc: 0.892.  Test auc different a lot I think. This performance drop happened to all my 14 datasets.
Any idea? 
Thanks!

**Comment by tqchen** [comment]
The random number generator changed since the brick update, so the results that relies on PRNG might be not reproducible

**Comment by tqchen** [comment]
This is mainly due to change of PRNG to c++11 standard, I do not know the exact reason of performance drop. But it could due to the fact that the experiment was random number sensitive.

**Comment by hwu84** [comment]
@tqchen Thanks for reply Tianqi. Problem solved. I think it might because change of PRNG influence colsample_bytree. Since there are only 7 features in my datasets, changing colsample_bytree from 0.7 to 1 fix the problem. Now the mean auc is within standard error.

**Comment by tqchen** [comment]
Glad it works our for you! Thanks for using xgboost

**Comment by hwu84** [comment]
My pleasure. This is a fantastic package!!
