### ISSUE TITLE
Python: cannot load model from v1.5.2 with newer versions

### ISSUE THREAD

**Issue by hombit** [dmlc/xgboost#8728]
I have a model created and saved with Python package v1.5.2 at PowerPC. Now I can load the model with the same version of the package at all platforms I tried (ppc, x86_64, arm, macOS and Linux), but cannot do it with any newer version. Resaving the model on a different platform doesn't help.

### Code to reproduce

```python
import xgboost

model = xgboost.XGBClassifier()
model.load_model("xgb.ubj")
```

### Data

xgb.ubj: https://drive.google.com/file/d/1KaFC-AFBluTO1CJLD1XAFZEQrUnRpkAx/view?usp=share_link

### Error

1.6.2 and 1.7.3 give the same message:

```
c_api/c_api.cc:1073: Check failed: str[0] == '{' (b vs. {)
```

### Traceback
<details>
  <summary>Expand</summary>
```
File .../python3.10/site-packages/xgboost/sklearn.py:777, in XGBModel.load_model(self, fname)
    775 if not hasattr(self, "_Booster"):
    776     self._Booster = Booster({"n_jobs": self.n_jobs})
--> 777 self.get_booster().load_model(fname)
    778 meta_str = self.get_booster().attr("scikit_learn")
    779 if meta_str is None:
    780     # FIXME(jiaming): This doesn't have to be a problem as most of the needed
    781     # information like num_class and objective is in Learner class.

File .../python3.10/site-packages/xgboost/core.py:2441, in Booster.load_model(self, fname)
   2437 if isinstance(fname, (str, os.PathLike)):
   2438     # assume file name, cannot use os.path.exist to check, file can be
   2439     # from URL.
   2440     fname = os.fspath(os.path.expanduser(fname))
-> 2441     _check_call(_LIB.XGBoosterLoadModel(
   2442         self.handle, c_str(fname)))
   2443 elif isinstance(fname, bytearray):
   2444     buf = fname

File .../python3.10/site-packages/xgboost/core.py:279, in _check_call(ret)
    268 """Check the return value of C API call
    269
    270 This function will raise exception when error occurs.
   (...)
    276     return value from API calls
    277 """
    278 if ret != 0:
--> 279     raise XGBoostError(py_str(_LIB.XGBGetLastError()))

XGBoostError: [09:34:14] .../build/temp.macosx-11.0-arm64-cpython-38/xgboost/src/c_api/c_api.cc:1073: Check failed: str[0] == '{' (b vs. {) :
Stack trace:
  [bt] (0) 1   libxgboost.dylib                    0x000000015e876534 dmlc::LogMessageFatal::~LogMessageFatal() + 124
  [bt] (1) 2   libxgboost.dylib                    0x000000015e894c6c XGBoosterLoadModel::$_1::operator()() const + 620
  [bt] (2) 3   libxgboost.dylib                    0x000000015e894668 XGBoosterLoadModel + 640
  [bt] (3) 4   libffi.dylib                        0x00000001a4af6050 ffi_call_SYSV + 80
  [bt] (4) 5   libffi.dylib                        0x00000001a4afeaf4 ffi_call_int + 1208
  [bt] (5) 6   _ctypes.cpython-310-darwin.so       0x0000000104a4d044 _ctypes_callproc + 868
  [bt] (6) 7   _ctypes.cpython-310-darwin.so       0x0000000104a47974 PyCFuncPtr_call + 212
  [bt] (7) 8   Python                              0x0000000102845238 _PyObject_MakeTpCall + 136
  [bt] (8) 9   Python                              0x000000010293ed8c call_function + 272
```
</details>

**Comment by hcho3** [comment]
@hombit XGBoost did not start supporting UBJSON format until version 1.6.0. (See the [release note for v1.6.0.](https://github.com/dmlc/xgboost/releases/tag/v1.6.0)). So your `xgb.ubj` file is actually a JSON file, not UBJSON.

When training a new model using v1.5.2, please use the JSON format (by using the `.json` file extension).

**Comment by hombit** [comment]
@hcho3 renaming the file didn't help, I still have the same error loading the file

**Comment by hcho3** [comment]
@hombit Is it possible to re-train your model, and then save it using the JSON format?

**Comment by hombit** [comment]
@hcho3 I can, it will take some time. But how can I save it ot the different format in v1.5 if it wasn't even supported?

**Comment by hcho3** [comment]
@hombit JSON was supported staring v1.5 already. 

Can you try renaming `xgb.ubj` to `xgb.model`?

**Comment by hombit** [comment]
> @hombit JSON was supported staring v1.5 already.
> 
> Can you try renaming `xgb.ubj` to `xgb.model`? My guess is that your model file might have been using the old binary format.

This works, thank you!

**Comment by hcho3** [comment]
No problem. Next time, you shouldn't use `.ubj` extension  when you're saving models from XGBoost 1.5
