### ISSUE TITLE
[RFC] Require C++17 standard.

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#8737]
Related: https://github.com/microsoft/LightGBM/issues/5691

It appears that a future version of R may require the R package to use C++17. This is a sign that C++17 is being widely adopted.

My proposal is to require C++17 standard to build XGBoost.

Supporting factors
* Sufficiently modern C++ compilers support C++17, such as GCC 5+ and Visual Studio 2019+.
* The disruption should be minimal, since our CI already tests XGBoost with C++17 (this is necessary for the RMM plugin).

On the side of the CI, I will need to re-build the Windows worker to use Visual Studio 2019 (right now it's using 2017).

@dmlc/xgboost-committer

**Comment by rongou** [comment]
Sounds great! I've run into cases where I wish I could use C++17 features. :)

**Comment by trivialfis** [comment]
That would indeed be a welcomed change. One concern is the binary distribution with the latest c++ runtime, not sure how well it works on older platforms.

**Comment by trivialfis** [comment]
Here are the things we can potentially remove if c++-17 is set as the default:
- dmlc::any
- linalg::apply
- string view
- Conjunction

Some other utilities are not yet removable:
- span, we need host device annotation.
- parallel sort. The std version doesn't allow the number of threads to be specified.

Additionally, we might consider the following changes:
- Specify the c standard for our c API as well.
- Consider using the polymorphic allocator.
