### ISSUE TITLE
xgboost .fit call gets stuck with error corrupted size vs. prev_size

### ISSUE THREAD

**Issue by Prerna1** [dmlc/xgboost#8738]
xgboost .fit call get stuck with error corrupted size vs. prev_size (no other stack trace) on GPU instances. However, the same code works fine on non GPU instances.

**Comment by trivialfis** [comment]
Could you please share a reproducible example and the version of xgboost you are using?

**Comment by Prerna1** [comment]
This is happening with a specific dataset which we cannot share as it is confidential. We have tried this xgboost version 0.90 and 1.6.2, we are seeing same issues with both

**Comment by trivialfis** [comment]
Unfortunately, in that case, we won't be able to debug it. Will close this issue now and see if there's any new issue mentioning segfault in the future.
