### ISSUE TITLE
Warn user to use `tree_method='gpu_hist'` with GPU DataFrames

### ISSUE THREAD

**Issue by sarahyurick** [dmlc/xgboost#8743]
Hi, I was wondering if there is any interest in adding a warning for users who are working with GPU DataFrames (i.e., cuDF) but haven't specified `tree_method='gpu_hist'` (and thus end up training the model on CPUs)?

cc @ayushdg

**Comment by trivialfis** [comment]
Hi, thank you for raising the issue.

I'm not sure whether that's necessary. It's a legitimate use case to have input device different from xgboost device. I don't have a strong preference for this.

**Comment by sarahyurick** [comment]
Okay, just wanted to ask. Thanks!
