### ISSUE TITLE
Support for individual tree predictions mapped to label space

### ISSUE THREAD

**Issue by andermi** [dmlc/xgboost#8744]
As described [here](https://stackoverflow.com/questions/74062129/how-to-get-individual-trees-prediction-value-for-xgboost-regressor),
please add documentation (or add an api function) for how to get each tree's prediction in label space for the regressor in order to do residual analysis with the labels per tree

**Comment by trivialfis** [comment]
Hi, I opened https://github.com/dmlc/xgboost/pull/8752 , hope that helps!
