### ISSUE TITLE
Invalid Parameter format for num_class expect int but value='0'

### ISSUE THREAD

**Issue by helloworld104** [dmlc/xgboost#8745]
Using XGBoost 1.6.0 on Linux Mint 20.3,
I loaded my pre-trained models using joblib, and faced this error: 

File "/home/testing/.local/lib/python3.8/site-packages/xgboost/core.py", line 203, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: Invalid Parameter format for num_class expect int but value='0'

**Comment by trivialfis** [comment]
could you please show me how to reproduce it?

**Comment by trivialfis** [comment]
NVM.

Pickled model is not stable across xgboost versions or python versions as described in https://xgboost.readthedocs.io/en/stable/tutorials/saving_model.html
