### ISSUE TITLE
xgboost 1.7.3  set tracker_conf  parameter error

### ISSUE THREAD

**Issue by beijinggao** [dmlc/xgboost#8759]
xgboost 1.7.3  set tracker_conf  parameter to use scala not in effect，but the actual use is still python,
![image](https://user-images.githubusercontent.com/7404433/217170891-c4400736-d3a3-4a5d-9ef2-875d6f6f7214.png)

![image](https://user-images.githubusercontent.com/7404433/217172166-56598925-8f33-45c7-aa93-0524fca4c1c6.png)

**Comment by trivialfis** [comment]
@wbo4958

**Comment by trivialfis** [comment]
The tracker conf is removed.
