### ISSUE TITLE
xgboost4j worker lost issue

### ISSUE THREAD

**Issue by yananchen1989** [dmlc/xgboost#8764]
Hi there. 
I run xgboost4j on spark cluster via databricks.
![image](https://user-images.githubusercontent.com/26405281/217616357-6ebeb10a-eef4-4781-ab08-a546ec46ddaf.png)

Most time it runs smoothly but occasionally it crashed with error message:

> Tracker started, with env={DMLC_NUM_SERVER=0, DMLC_TRACKER_URI=10.249.34.197, DMLC_TRACKER_PORT=34551, DMLC_NUM_WORKER=8}
> ExecutorLostFailure (executor 3 exited unrelated to the running tasks) Reason: worker lost
> 	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:3029)
> 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2976)
> 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2970)
> 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
> 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
> 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
> 	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2970)
> 	at org.apache.spark.scheduler.DAGScheduler.handleTaskCompletion(DAGScheduler.scala:2603)
> 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:3235)
> 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:3179)
> 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:3167)
> 	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
> 	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:1152)
> 	at org.apache.spark.SparkContext.runJobInternal(SparkContext.scala:2657)
> 	at org.apache.spark.rdd.RDD.$anonfun$collect$1(RDD.scala:1036)
> 	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:165)
> 	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:125)
> 	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
> 	at org.apache.spark.rdd.RDD.withScope(RDD.scala:419)
> 	at org.apache.spark.rdd.RDD.collect(RDD.scala:1034)
> 	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainDistributed(XGBoost.scala:414)
> 	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:202)
> 	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:34)
> 	at org.apache.spark.ml.Predictor.fit(Predictor.scala:151)
> 	at $line1baf3d527264425cadc39f1f45def75f29.$read$$iw$$iw$$iw$$iw$$iw$$iw.$anonfun$res2$1(command-4298799828331999:46)
> 	at scala.runtime.java8.JFunction1$mcVI$sp.apply(JFunction1$mcVI$sp.java:23)
> 	at scala.collection.immutable.List.foreach(List.scala:431)
> 	at $line1baf3d527264425cadc39f1f45def75f29.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-4298799828331999:15)
> 	at $line1baf3d527264425cadc39f1f45def75f29.$read$$iw$$iw$$iw$$iw$$iw.<init>(command-4298799828331999:108)
> 	at $line1baf3d527264425cadc39f1f45def75f29.$read$$iw$$iw$$iw$$iw.<init>(command-4298799828331999:110)
> 	at $line1baf3d527264425cadc39f1f45def75f29.$read$$iw$$iw$$iw.<init>(command-4298799828331999:112)
> 	at $line1baf3d527264425cadc39f1f45def75f29.$read$$iw$$iw.<init>(command-4298799828331999:114)
> 	at $line1baf3d527264425cadc39f1f45def75f29.$read$$iw.<init>(command-4298799828331999:116)
> 	at $line1baf3d527264425cadc39f1f45def75f29.$read.<init>(command-4298799828331999:118)
> 	at $line1baf3d527264425cadc39f1f45def75f29.$read$.<init>(command-4298799828331999:122)
> 	at $line1baf3d527264425cadc39f1f45def75f29.$read$.<clinit>(command-4298799828331999)
> 	at $line1baf3d527264425cadc39f1f45def75f29.$eval$.$print$lzycompute(<notebook>:7)
> 	at $line1baf3d527264425cadc39f1f45def75f29.$eval$.$print(<notebook>:6)
> 	at $line1baf3d527264425cadc39f1f45def75f29.$eval.$print(<notebook>)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:747)
> 	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1020)
> 	at scala.tools.nsc.interpreter.IMain.$anonfun$interpret$1(IMain.scala:568)
> 	at scala.reflect.internal.util.ScalaClassLoader.asContext(ScalaClassLoader.scala:36)
> 	at scala.reflect.internal.util.ScalaClassLoader.asContext$(ScalaClassLoader.scala:116)
> 	at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:41)
> 	at scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:567)
> 	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:594)
> 	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:564)
> 	at com.databricks.backend.daemon.driver.DriverILoop.execute(DriverILoop.scala:219)
> 	at com.databricks.backend.daemon.driver.ScalaDriverLocal.$anonfun$repl$1(ScalaDriverLocal.scala:225)
> 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
> 	at com.databricks.backend.daemon.driver.DriverLocal$TrapExitInternal$.trapExit(DriverLocal.scala:1003)
> 	at com.databricks.backend.daemon.driver.DriverLocal$TrapExit$.apply(DriverLocal.scala:956)
> 	at com.databricks.backend.daemon.driver.ScalaDriverLocal.repl(ScalaDriverLocal.scala:225)
> 	at com.databricks.backend.daemon.driver.DriverLocal.$anonfun$execute$13(DriverLocal.scala:634)
> 	at com.databricks.logging.Log4jUsageLoggingShim$.$anonfun$withAttributionContext$1(Log4jUsageLoggingShim.scala:33)
> 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
> 	at com.databricks.logging.AttributionContext$.withValue(AttributionContext.scala:94)
> 	at com.databricks.logging.Log4jUsageLoggingShim$.withAttributionContext(Log4jUsageLoggingShim.scala:31)
> 	at com.databricks.logging.UsageLogging.withAttributionContext(UsageLogging.scala:205)
> 	at com.databricks.logging.UsageLogging.withAttributionContext$(UsageLogging.scala:204)
> 	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionContext(DriverLocal.scala:59)
> 	at com.databricks.logging.UsageLogging.withAttributionTags(UsageLogging.scala:240)
> 	at com.databricks.logging.UsageLogging.withAttributionTags$(UsageLogging.scala:225)
> 	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionTags(DriverLocal.scala:59)
> 	at com.databricks.backend.daemon.driver.DriverLocal.execute(DriverLocal.scala:611)
> 	at com.databricks.backend.daemon.driver.DriverWrapper.$anonfun$tryExecutingCommand$1(DriverWrapper.scala:615)
> 	at scala.util.Try$.apply(Try.scala:213)
> 	at com.databricks.backend.daemon.driver.DriverWrapper.tryExecutingCommand(DriverWrapper.scala:607)
> 	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommandAndGetError(DriverWrapper.scala:526)
> 	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommand(DriverWrapper.scala:561)
> 	at com.databricks.backend.daemon.driver.DriverWrapper.runInnerLoop(DriverWrapper.scala:431)
> 	at com.databricks.backend.daemon.driver.DriverWrapper.runInner(DriverWrapper.scala:374)
> 	at com.databricks.backend.daemon.driver.DriverWrapper.run(DriverWrapper.scala:225)
> 	at java.lang.Thread.run(Thread.java:750)

here is config of the cluster:
![image](https://user-images.githubusercontent.com/26405281/217616713-5712b748-f749-4bcd-82b6-5d25cc7650c9.png)

**Comment by yananchen1989** [comment]
the code in the notebook cell:

```
import org.apache.spark.ml.evaluation.BinaryClassificationEvaluator 
import ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier

val evaluator = new BinaryClassificationEvaluator()
                    .setLabelCol("label")
                    .setRawPredictionCol("probability")
                    .setMetricName("areaUnderROC")

val file_path = "gs://definity-aw-prod-dswork-pidc/temp/dac/dac_dense/dac_df_assemble_dense_4000000m_raw"

val df_assemble_dense = spark.read.parquet(file_path)

println(df_assemble_dense.count())
// for (ite <- List(1,2,3,4,5)){

val Array(training_valid_Data, testData) = df_assemble_dense.randomSplit(Array(0.9, 0.1))
val Array(trainingData, validData) = training_valid_Data.randomSplit(Array(0.9, 0.1))
println(trainingData.count(), validData.count(), testData.count())

val xgbParam = Map("eta" -> 0.1f,
      // "missing" -> -999,
      "objective" -> "binary:logistic",
      // "num_class" -> 2,
      "num_round" -> 2000,
      "num_workers" -> 8,
      "max_depth" -> 7,
      "max_bin" -> 64,
      "min_child_weight" -> 0.2,
      "subsample" -> 0.7,
      "colsample_bytree" -> 0.7,
      "eval_metric" -> "auc",
      "max_cat_to_onehot" -> 10,
      "max_cat_threshold" -> 1000,
      "num_early_stopping_rounds" -> 50,
      "maximize_evaluation_metrics" -> true,
      "eval_sets" -> Map("validation" -> validData),
      "enable_categorical" -> true
      )

val xgbClassifier = new XGBoostClassifier(xgbParam)
      .setFeaturesCol("features_assemble_dense") //df_assemble_dense.columns.filter(! _.equals("label"))
      .setLabelCol("label")
      .setHandleInvalid("keep")

val model = xgbClassifier.fit(trainingData)

val predictions_test = model.transform(testData)
val predictions_valid = model.transform(validData)
val predictions_train = model.transform(trainingData)

val auc_test = evaluator.evaluate(predictions_test)
val auc_valid = evaluator.evaluate(predictions_valid)
val auc_train = evaluator.evaluate(predictions_train)

println(s"summary $ite:  auc ==> $auc_train $auc_valid $auc_test")
```

**Comment by trivialfis** [comment]
Closing due to stalled. Feel free to reopen if there's further information like worker log.
