### ISSUE TITLE
[spark] Set DMatrix `enable_categorical` to True if user provide `feature_types` param

### ISSUE THREAD

**Issue by WeichenXu123** [dmlc/xgboost#8766]
If user provide `feature_types` param, we should set `enable_categorical` to True when constructing DMatrix.

**Comment by WeichenXu123** [comment]
@trivialfis Is my understanding correct ? I will file PR for it once you confirmed it.

**Comment by trivialfis** [comment]
Correct. Please submit a PR.

**Comment by WeichenXu123** [comment]
@trivialfis Thank you!
