### ISSUE TITLE
R package github-actions fail when depending on precompiled tarball

### ISSUE THREAD

**Issue by cmatKhan** [dmlc/xgboost#8792]
I am trying to set up my CI for a package which depends on the precompiled linux_gpu R tarball.

The error is this:

```
  ✖ Failed to build xgboost 1.7.2.1
  Error: 
  ! error in pak subprocess
  Caused by error in `stop_task_build(state, worker)`:
  ! Failed to build source package 'xgboost'
  Full installation output:
  * installing *source* package ‘xgboost’ ...
  staged installation is only possible with locking
  ** using non-staged installation
  ** libs
  make: Nothing to be done for 'all'.
  ** R
  ** data
  ** demo
  ** inst
  ** byte-compile and prepare package for lazy loading
  ** help
  *** installing help indices
  ** building package indices
  ** installing vignettes
  ** testing if installed package can be loaded
  Error: Error: package or namespace load failed for ‘xgboost’ in library.dynam(lib, package, package.lib):
   shared object ‘xgboost.so’ not found
  Error: Error: loading failed
  Execution halted
```

[according to someone at Posit](https://community.rstudio.com/t/github-actions-with-remote-url-in-description/159838/6?u=chasem) (formerly Rstudio), the cause is this:

> But the package is not prepared for this, and the shared library will not be included in the built package, so when pak tried to  call R CMD INSTALL on it, that fails because of the missing .so file.

Any recommendations on how to set up github-actions for an R package -- preferably with modifications to the gh-actions scripts provided by `usethis` -- which depends on the precompiled-with-gpu tarballs?

**Comment by hcho3** [comment]
@cmatKhan Is it possible for you to run `R CMD INSTALL ./xgboost_r_gpu_linux.tar.gz` from the command line?

**Comment by cmatKhan** [comment]
Yes -- the problem is specifically with `pak` it turns out. I was getting help on the Posit board, also -- here is the resolution:

https://community.rstudio.com/t/github-actions-with-remote-url-in-description/159838/9?u=chasem

Basically, github actions uses `pak` and `pak` somehow isn't installing the tarball. However, it works through `renv` and with `install.packages`, so it isn't really a problem with the tarbal, but with `pak`.

**Comment by hcho3** [comment]
Good to hear that the issue was resolved.
