### ISSUE TITLE
Is FM (factorization machines) available in xgboost?

### ISSUE THREAD

**Issue by jaguerrerod** [dmlc/xgboost#8794]
I received this answer from chatGPT about fm in xgboost:

![image](https://user-images.githubusercontent.com/90916454/218570423-8497abba-af8f-4118-ac84-0608da8d35eb.png)

I don't find in documentation fm booster.
Is really chatGPT right?

**Comment by hcho3** [comment]
No, XGBoost does not implement Factorization Machines. It seems like ChatGPT got this one wrong.
