### ISSUE TITLE
[bug] Inconsistent predictions between binary:logitraw and binary:logistic

### ISSUE THREAD

**Issue by ysq151944** [dmlc/xgboost#8799]
win10(21H1, 19043.2251)
python 3.11.0
xgboost 1.7.1

``` python
import numpy as np
import xgboost as xgb


train_X = np.random.randn(10000, 100)
train_y = np.random.randint(0, 2, 10000)

test_X = np.random.randn(3000, 100)
test_y = np.random.randint(0, 2, 3000)

dtrain = xgb.DMatrix(train_X, train_y)
dtest = xgb.DMatrix(test_X, test_y)

param_model = {
    'max_depth': 100,
    "booster": "gbtree",
    'eta': 0.1,
    'gpu_id': 0,
    'tree_method': 'gpu_hist',
    'max_bin': 128,
    'seed': 43,
    'grow_policy': 'lossguide',
}


def train_and_pred(objective):
    param_model['objective'] = f'binary:{objective}'
    return xgb.train(param_model, dtrain, 160).predict(dtest)


preds_logitraw = train_and_pred('logitraw')
proba_logitraw = 1 / (1 + np.exp(-preds_logitraw))
preds_logistic = train_and_pred('logistic')

print(proba_logitraw)
print(preds_logistic)

```
```
[0.546458   0.4377375  0.44825116 ... 0.4022763  0.6350505  0.59346294]
[0.27821076 0.38410345 0.4975099  ... 0.71143335 0.5986237  0.5419562 ]

```

shouldn't the two arrays be exact the same after transforming the raw output of logitraw?

**Comment by ysq151944** [comment]
I thought the final predictions after transformation should be exact the same(like predict_proba and predict in sklearn), yet the results above doesn't approve it.

**Comment by trivialfis** [comment]
That's a quirk in the base score with prediction transform. the `logitraw` is mostly here as a legacy. If you want raw output from logistic, you can use `booster.predict(dtest, output_margin=True)` instead of `logitraw`.

But to answer the question here, the following snippet should resolve the issue, notice the `base_score`.
``` python
import numpy as np
import xgboost as xgb

rng = np.random.RandomState(1994)

train_X = rng.randn(10, 100)
train_y = rng.randint(0, 2, 10)

test_X = rng.randn(2, 100)
test_y = rng.randint(0, 2, 2)

dtrain = xgb.DMatrix(train_X, train_y)
dtest = xgb.DMatrix(test_X, test_y)

param_model = {
    "max_depth": 32,
    "booster": "gbtree",
    "eta": 0.1,
    "gpu_id": 0,
    "tree_method": "gpu_hist",
    "max_bin": 128,
    "seed": 43,
    "grow_policy": "lossguide",
}


def train_and_pred(objective):
    param_model["objective"] = f"binary:{objective}"
    return xgb.train(param_model, dtrain, 1).predict(dtest)


param_model["base_score"] = 0.0
preds_logitraw = train_and_pred("logitraw")
proba_logitraw = 1 / (1 + np.exp(-preds_logitraw))

param_model["base_score"] = 0.5
preds_logistic = train_and_pred("logistic")

print(proba_logitraw)
print(preds_logistic)
```

**Comment by ysq151944** [comment]
> That's a quirk in the base score with prediction transform. the `logitraw` is mostly here as a legacy. If you want raw output from logistic, you can use `booster.predict(dtest, output_margin=True)` instead of `logitraw`.
> 
> But to answer the question here, the following snippet should resolve the issue, notice the `base_score`.
> 
> ```python
> import numpy as np
> import xgboost as xgb
> 
> rng = np.random.RandomState(1994)
> 
> train_X = rng.randn(10, 100)
> train_y = rng.randint(0, 2, 10)
> 
> test_X = rng.randn(2, 100)
> test_y = rng.randint(0, 2, 2)
> 
> dtrain = xgb.DMatrix(train_X, train_y)
> dtest = xgb.DMatrix(test_X, test_y)
> 
> param_model = {
>     "max_depth": 32,
>     "booster": "gbtree",
>     "eta": 0.1,
>     "gpu_id": 0,
>     "tree_method": "gpu_hist",
>     "max_bin": 128,
>     "seed": 43,
>     "grow_policy": "lossguide",
> }
> 
> 
> def train_and_pred(objective):
>     param_model["objective"] = f"binary:{objective}"
>     return xgb.train(param_model, dtrain, 1).predict(dtest)
> 
> 
> param_model["base_score"] = 0.0
> preds_logitraw = train_and_pred("logitraw")
> proba_logitraw = 1 / (1 + np.exp(-preds_logitraw))
> 
> param_model["base_score"] = 0.5
> preds_logistic = train_and_pred("logistic")
> 
> print(proba_logitraw)
> print(preds_logistic)
> ```

thanks, that's help a lot
