### ISSUE TITLE
linear regression

### ISSUE THREAD

**Issue by superfan123** [dmlc/xgboost#88]
Had a wonderful experience with xgboost classification, now I'm working on regression with Kaggle afsis competition.
I try to use linear regression to predict target variable Ca,P.. (All continuous variable.)
Here is my R code

xgmat <- xgb.DMatrix(Xm, label=Ca)  # original Ca has negtive value and I use exp(Ca) to transform it.
param <- list("booster"="gblinear",
              "objective" = "reg:linear",
              "lambda" = 0.5,
              "alpha" = 0.5,
              "eval_metric" = "rmse",      # rmse is the eval on Kaggle 
              "silent" = 1,
              "nthread" = 4)
watchlist <- list(eval = xgmat, train = xgmat)
nround = 90

bst = xgb.train(param, xgmat, nround, watchlist );

I got the following message
[0] eval-rmse:-nan  train-rmse:-nan
[1] eval-rmse:nan   train-rmse:nan
[2] eval-rmse:nan   train-rmse:nan

Where should I change?
Thanks.

**Comment by Matrixsun** [comment]
what mean of "standardize"? or what is the rules of "standardize"?  how to "standardize"?

Thanks

**Comment by Matrixsun** [comment]
maybe i get the answer.it work when i ues  "np.arrary"
