### ISSUE TITLE
How can I obtain the number of nodes for each tree in XGBoost?

### ISSUE THREAD

**Issue by PowderL** [dmlc/xgboost#8808]
I wanted to get the number of nodes for each tree in XGBoost models, but I failed to find an API I could obtain it directly.  Are there already APIs that can achieve this?  If not, is there a new plan for adding an API to do this?

**Comment by trivialfis** [comment]
There's no such API. However, as a quick solution, one can always inspect the model dump or the exported JSON model.

**Comment by PowderL** [comment]
Actually, I wanted to get the total number of nodes in the tree. You are right, we can obtain the total number of nodes according to the model dump. But I have to iterate the JSON model to calculate the total number of nodes. It should be more convenient if an API can achieve this.

**Comment by trivialfis** [comment]
You can get number of nodes from the JSON model by accessing the tree param.
