### ISSUE TITLE
I can't build java wrapper

### ISSUE THREAD

**Issue by skybenefit** [dmlc/xgboost#881]
1. I got **libxgboost.dll** from https://github.com/dmlc/xgboost via windows commad line
   I got  **xgboost_wrapper.dll** from https://github.com/dmlc/xgboost/tree/0.47/windows via   VisualStudio 2013
2. I opend project xgboost/java/xgboost4j 
   Add _xgboost_wrapper.dll_ аnd _libxgboost.dll_  in the folder xgboost4j\src\main\resources\lib
3. In the  class Initializer.java 
   In the line 
   `public static final String[] libNames = new String[] {"xgboost_wrapper"};`
   I changed value **_libNames_**  
   1) from _xgboost4j_ to _xgboost_wrapper_ and then run unitTest
   2) from _xgboost4j_ to _libxgboost_ and then run unitTest
   
   Both throw _java.lang.UnsatisfiedLinkError: org.dmlc.xgboost4j.wrapper.XgboostJNI.XGDMatrixCreateFromFile(Ljava/lang/String;I[J)I
   at org.dmlc.xgboost4j.wrapper.XgboostJNI.XGDMatrixCreateFromFile(Native Method)
   at org.dmlc.xgboost4j.DMatrix.<init>(DMatrix.java:62)_
   
   I need to learn build java wrapper, because I need run application on Windows and Unix system.
   Please, help me.
4. I tried to build _xgboost4j_wrapper.cpp_ to _xgboost4j_wrapper.dll_
   
   ```
   xgboost\java>
   cl xgboost4j_wrapper.cpp 
   -I%JAVA_HOME%\include 
   -I%JAVA_HOME%\include\win32
   -IC:\Users\User\Desktop\dmlc\xgboost\include -MD -LD
   ```
   
   But I got 
   _xgboost4j_wrapper.obj : error LNK2019: unresolved external symbol XGBoosterDumpModel     referenced in function Java_org_dmlc_xgboost4j_wrapper_XgboostJNI_XGBoosterDumpModel
   xgboost4j_wrapper.dll : fatal error LNK1120: 26 unresolved externals_

**Have you any idea?
How can I use xgboost from Java?**

**Thank you for your future ideas.**

**Comment by pommedeterresautee** [comment]
Bug related to an old version, closing.
