### ISSUE TITLE
Predict with PredictionType::kContribution is 100x slower

### ISSUE THREAD

**Issue by hmchen-github** [dmlc/xgboost#8817]
I modified this the `demo/c-api/inference/inference.c` file and changed the `\"type\": 0` to 2 (kContribution) here

https://github.com/dmlc/xgboost/blob/master/demo/c-api/inference/inference.c#L148

With N_SAMPLES=256000,

The prediction of type 0 takes  0.213612 seconds. (prediction only)
The prediction of type 2 takes 23.667558 seconds. (prediction + contribution)
The prediction of type 3 takes 0.202612 seconds. (prediction + approx contribution)

1) Why calculating the contribution is 100x slow?
2) What's the difference between contribution and approx contribution? Given the speed difference is so big, should I always use type 3?

**Comment by RAMitchell** [comment]
Prediction contributions uses a shapley value algorithm, which is expensive. They can be computed using the GPU by enabling the "gpu_predictor" parameter.
