### ISSUE TITLE
How cli version xgboost do incremental training on incremental data

### ISSUE THREAD

**Issue by MrRace** [dmlc/xgboost#8821]
From the [CLI/binary_classification](https://github.com/dmlc/xgboost/tree/master/demo/CLI/binary_classification) , it show me how to use incremental training. The sentence：
```
However, beware that the training and evaluation data specified in mushroom.conf should not change when you use this function.
```
mean the `xgboost mushroom.conf model_in=0002.model num_round=2 model_out=continue.model` just use the same train data and do more num_round. Therefore if I have new data and want to do incremental training for the new train data. How should I set ?
Just change the `data` parameter in config ?
```
# incremental training data
data = "part2.train.csv?format=csv&label_column=0" 
```
Is it right？ Do i need to change other parameters？ for example the  `num_round` should be changed？
Thanks a lot!

**Comment by trivialfis** [comment]
There's no robust incremental training for gradient boosting trees yet. The model input is for continuous training with the same data.
