### ISSUE TITLE
Support multiple eval_metric in SparkXGB

### ISSUE THREAD

**Issue by mzzhang95** [dmlc/xgboost#8825]
Hey guys, I find that SparkXGB estimators do not support multiple evaluation metrics because of the following validation: https://github.com/dmlc/xgboost/blob/master/python-package/xgboost/spark/core.py#L317

In single node xgboost, PARAM eval_metric could be a list of strings. Could you please also enable multiple eval_metric for SparkXGB models?

**Comment by mzzhang95** [comment]
Created a PR here. https://github.com/dmlc/xgboost/pull/8826

**Comment by trivialfis** [comment]
thank you for the pr!
