### ISSUE TITLE
JVM is restarted when System.load("lib/linux/aarch64/libxgboost4j.so")

### ISSUE THREAD

**Issue by ngocnam1202** [dmlc/xgboost#8827]
I'm building the jar file for xgboost4j that supports Linux aarch64.
According to [this document](https://xgboost.readthedocs.io/en/stable/build.html), I can build the shared object now, and my jar file also contains that shared object at `lib/linux/aarch64/libxgboost4j.so`

To test the jar, I use it as a library in my application and call `new ml.dmlc.xgboost4j.java.DMatrix("");` 
It will call `XGBoostJNI` >>> `NativeLibLoader.initXGBoost()` >>> `System.load(temp);`
The problem is JVM will be restarted when exec `System.load(temp);`

**First time**
<img width="1224" alt="image" src="https://user-images.githubusercontent.com/16237017/220251954-da233a5b-c2b4-463b-ae1e-047772450080.png">

**After installing libgomp**
No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
<img width="1413" alt="image" src="https://user-images.githubusercontent.com/16237017/220252074-7a0eddb1-676b-4b53-8da0-1bbc8608e468.png">

**After running ulimit -c unlimited**
<img width="1413" alt="image" src="https://user-images.githubusercontent.com/16237017/220252615-51c94351-c391-4d9d-8c76-b37818089ad7.png">

**Running java with  -XX:+CreateCoredumpOnCrash**
<img width="1413" alt="image" src="https://user-images.githubusercontent.com/16237017/220252848-2302e411-47cd-4f08-9c30-71d3507a8772.png">

[hs_err_pid286.log](https://github.com/dmlc/xgboost/files/10789788/hs_err_pid286.log)
[hs_err_pid338.log](https://github.com/dmlc/xgboost/files/10789789/hs_err_pid338.log)
[hs_err_pid357.log](https://github.com/dmlc/xgboost/files/10789790/hs_err_pid357.log)

**Comment by trivialfis** [comment]
This is the definition of the split function:
``` c++
inline std::vector<std::string> Split(const std::string& s, char delim) {
  std::string item;
  std::istringstream is(s);
  std::vector<std::string> ret;
  while (std::getline(is, item, delim)) {
    ret.push_back(item);
  }
  return ret;
}
```

I don't think there's anything obvious there that can cause a segfault. Maybe the c++ tool chain (along with glibc) is not correctly configured?

**Comment by trivialfis** [comment]
Closing due to lack of response. Feel free to reopen if there's further available information.
