### ISSUE TITLE
Can we update xgboost4j dependency with latest spark version ?

### ISSUE THREAD

**Issue by WeichenXu123** [dmlc/xgboost#8829]
Can we update xgboost4j dependency with latest spark version ?

The spark version 3.1.1 is pretty old.

**Comment by WeichenXu123** [comment]
CC @trivialfis @wbo4958

**Comment by wbo4958** [comment]
May I ask what's the motivation for upgrading spark dependency? I suppose xgboost is using the public APIs of spark, which suppose xgboost can run on any spark 3.x version. Please correct me

**Comment by WeichenXu123** [comment]
good point !
Unfortunately latest spark version brings breaking change. See https://github.com/dmlc/xgboost/pull/8831

**Comment by WeichenXu123** [comment]
We can improve CI to test against multiple spark versions instead of upgrading dependent spark version
