### ISSUE TITLE
1.7.4 artifacts missing in maven central

### ISSUE THREAD

**Issue by asolimando** [dmlc/xgboost#8833]
Artifacts for 1.7.4 version seems to be missing in Maven Central: https://mvnrepository.com/artifact/ml.dmlc/xgboost4j

Since the 1.7.4 tag is there and 1.7.4 has been released according to https://github.com/dmlc/xgboost/releases, shouldn't the artifacts be available?

Thanks!

**Comment by trivialfis** [comment]
not yet. Still working on some of the packages. https://github.com/dmlc/xgboost/issues/8803 will be closed once all packages are uploaded.
