### ISSUE TITLE
Issues with compiling the evaluation step in the vertex ai custom pipeline

### ISSUE THREAD

**Issue by Fayepasvouri** [dmlc/xgboost#8843]
Hi guys!

In my custom pipeline with xgboost model I get an error which is not clear in the logs. 

This is the pipeline: 
```
@dsl.pipeline(name="faye-pipe",
description="A basic pipeline with ti components", 
              pipeline_root='gs://faye-test-bucket/faye-pipeline')

def ti_pipeline():
    data_preparation = preprocessing_step()
    train = xgboost_train_model(
        data_preparation.outputs["dataset_features"],
        data_preparation.outputs["dataset_target"],
    )
    evaluation = eval_model(
        train_dataset=data_preparation.outputs["dataset_features"],
        target_dataset=data_preparation.outputs["dataset_target"],
        xgb_model=train.outputs["model"],
    )

compiler.Compiler().compile(
  pipeline_func=ti_pipeline, 
  package_path="faye_pipe.json"
)
```
The first two steps, the preprocessing step and the training step succeed. When i add print statements in the evaluation steps, all print statements come out successfully, meaning that the code works fine. However, it fails in evaluation step with the following logs which I do not understand in order to troubleshoot:

[KFP Executor 2023-02-24 10:56:07,971 INFO]: Loading KFP component "eval_model" from /tmp/tmp.F2eTpAh65Z/ephemeral_component.py (directory "/tmp/tmp.F2eTpAh65Z" and module name "ephemeral_component")

And also this one:

Tearing down training program.

Could you please assist? 

Thanks a lot

**Comment by trivialfis** [comment]
Unfortunately, I'm not familiar with the library you are using and can't guess what's happening with the snippet you provided. It would be great if you have something more concrete for us to run.

**Comment by Fayepasvouri** [comment]
@trivialfis Hello! I think the problem is related to the region selected... i used us-central1 and the metrics could not be compiled... if i remove the metrics, it works... so i need to switch to europe.

**Comment by trivialfis** [comment]
Good to know!
