### ISSUE TITLE
Memory doubles / runs OOM when training with many boosting rounds

### ISSUE THREAD

**Issue by afogarty85** [dmlc/xgboost#8844]
The issue:

With a large number of training rounds, my training is typically crashing around the 10k boosting round mark as my machine suddenly goes OOM. The image below denotes the sudden change whereby the system is using only roughly half of available memory and nearly doubles in size.

<img width="873" alt="compute_change" src="https://user-images.githubusercontent.com/49048309/221364419-07255ede-804f-46c6-baf0-9814da7e9039.png">

What I have found so far:

I can train successfully with fewer boosting rounds, but using higher boosting rounds yields this explosion in memory comes around the 9k-10k mark.

Environment:

```
xgb version: 1.7.4
NVIDIA-SMI 525.60.02    Driver Version: 526.98       CUDA Version: 12.0
WSL Ubuntu VSCode
```

I am using XGBoost GPU training on a data set of shape: `(9178989, 34)` which is comprised mostly of categorical features.

My parameters for training are:

```
param = {
        'objective': 'binary:logistic',
         'learning_rate': 0.05,  # 0.01 a bit too slow
         'max_depth': 8,
         'grow_policy': 'lossguide',
         'sampling_method': 'gradient_based',
         'eval_metric': 'logloss',
         'reg_lambda': 5,
         'colsample_bytree': 1.0,
         'tree_method': 'gpu_hist',
         "predictor": "gpu_predictor",
         'subsample': 0.5,
         'scale_pos_weight': scale_pos_weight
         }
```

I am using the xgb API data set as follows:

```
xg_train = xgb.DMatrix(data=X_train,
                       label=y_train,
                       feature_types=featureTypes,
                       enable_categorical=True)
```

I ran a few other follow on tests in-case it is helpful:

```
# boosting rounds, crashes with:
10000, 8000

# boosting rounds, does not crash:
<= 6000
```

**Comment by trivialfis** [comment]
Hi, could you please share the shape (and potentially sparsity) of your dataset so that I can run some tests myself?

**Comment by trivialfis** [comment]
NVM. I missed this line:

> I am using XGBoost GPU training on a data set of shape: (9178989, 34) which is comprised mostly of categorical features.

Let me try to reproduce it later.

**Comment by trivialfis** [comment]
Just a side note, I tried WSL before and it uses significantly more memory than a normal Linux installation https://github.com/microsoft/WSL/issues/4166 . Could you please try a normal Linux distribution first? I don't have a Windows machine that has such memory size.

**Comment by afogarty85** [comment]
Thank you for the feedback and insight; I think we can probably close this and attribute it to WSL; I ran the same training / code on the windows system and suffered no errors!

**Comment by afogarty85** [comment]
FWIW / interesting: I can run `xgb.cv` for 10k+ boosting rounds without issue in WSL, go figure.

**Comment by trivialfis** [comment]
Thank you for sharing, I don't think XGBoost would take that much memory all of a sudden, especially if you are using GPU. Would love to learn more about the WSL usage pattern.
