### ISSUE TITLE
python question:What is the relationship between leaf value ,predict value of per booster  and the model predict value? 

### ISSUE THREAD

**Issue by Jarye0612** [dmlc/xgboost#8849]
Hello,when I run the following code,predict the same sample x1, why p1(model predict) not equal to p2(sum of predict value per booster )?and why individual_preds[5](predict value of  5th booster) not equal to x1 leaf value in the 5th tree graph(xgb.plot_tree(num_trees=5))?
this problem has been bothering me for days,hoping for some guidance and help.

``` python
import pandas as pd
import numpy as np
x=pd.DataFrame(np.random.random((100, 10)),columns=[ 'x{}'.format(i) for i in range(10)])
y=pd.Series(np.random.random(100))
bst=xgb.XGBRegressor(max_depth=2, learning_rate=0.12, n_estimators=90,random_state=2, objective='reg:squaredlogerror')
bst.fit(x, y)
p1=bst.predict(x.iloc[[1], :])
individual_preds = []
for tree_ in bst.get_booster():
    individual_preds.append(
        tree_.predict(xgb.DMatrix(x.iloc[[1], :]))[0]
    )
p2=np.sum(individual_preds)
p5=xgb.plot_tree(bst, num_trees=5)
print('p1=',p1,'p2=',p2)
print("individual_preds[5]=",individual_preds[5],'tree5 x1 leaf value need to compute according to the p5 graph')
x.iloc[[1], :]
```

**Comment by trivialfis** [comment]
The base score needs to be specified. See https://github.com/dmlc/xgboost/blob/master/demo/guide-python/individual_trees.py .

**Comment by Jarye0612** [comment]
@trivialfis thanks, but i don't fully understand:
1. when i run  https://github.com/dmlc/xgboost/blob/master/demo/guide-python/individual_trees.py :
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\PycharmProjects\\local_test\\../data/agaricus.txt.train'

2.how to change in my code to let the p1(model predict) equal to p2(sum of predict value per booster )
i change my code as the following,but p1 not equal p2:
import pandas as pd
import numpy as np
import xgboost as xgb
x=pd.DataFrame(np.random.random((100, 10)),columns=[ 'x{}'.format(i) for i in range(10)])
y=pd.Series(np.random.random(100))
bst=xgb.XGBRegressor(base_score=0.5,max_depth=2, learning_rate=0.12, n_estimators=90,random_state=2, objective='reg:squaredlogerror')
bst.fit(x, y)
p1=bst.predict(x.iloc[[1], :])
individual_preds = []
for tree_ in bst.get_booster():
    individual_preds.append(
        tree_.predict(xgb.DMatrix(x.iloc[[1], :]))[0]
    )
p2=np.sum(individual_preds)+0.5
p5=xgb.plot_tree(bst, num_trees=5)
print('p1=',p1,'p2=',p2)
print("individual_preds[5]=",individual_preds[5],'tree5 x1 leaf value need to compute according to the p5 graph')
x.iloc[[1], :]
