### ISSUE TITLE
Pytest timeout for TestGPUPredict::test_inplace_predict_cupy_specified_device

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#8856]
In #8853, I disabled a pytest (`tests/python-gpu/test_gpu_prediction.py::TestGPUPredict::test_inplace_predict_cupy_specified_device`) because it was timing out with >20s. We should either relax the timeout requirement or revise the test so that it runs faster.

**Comment by trivialfis** [comment]
I think that's probably an issue, the test should be pretty quick (<4 sec on my machine).

**Comment by trivialfis** [comment]
The test was re-enabled.
