### ISSUE TITLE
abs_tol still in doc help despite being replaced with min_delta

### ISSUE THREAD

**Issue by nsaguirre11** [dmlc/xgboost#8862]
Ran into some confusion earlier with this -- looks like the early stopping tolerance was changed from abs_tol to min_delta, but in https://github.com/dmlc/xgboost/blob/master/python-package/xgboost/callback.py, it still refers to abs_tol. I'd change this myself, but I wasn't totally sure if there had been any changes that would have made it interchangeable or not.

```
            es = xgboost.callback.EarlyStopping(
                rounds=2,
                abs_tol=1e-3,
                save_best=True,
                maximize=False,
                data_name="validation_0",
                metric_name="mlogloss",
            )
```

**Comment by hcho3** [comment]
Yes, that's a typo. Can you submit a pull request to change the docstring?

**Comment by trivialfis** [comment]
apologies for the oversight. Please help fix it.
