### ISSUE TITLE
Prediction much slower when upgrading to 1.7.3

### ISSUE THREAD

**Issue by sniper343** [dmlc/xgboost#8865]
I recently tried updating from 0.82 to 1.7.3. However, when I use 0.82 and 1.7.3 to predict, the prediction speed of version 1.7.3 is much slower.
The following table is the time consumed by different batches for predict：

![image](https://user-images.githubusercontent.com/29256683/222673534-d82d695c-85b5-4a7c-81db-bac58324896f.png)

Here's the code to save model:

```
import xgboost

# read data
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
data = load_iris()
X_train, X_test, y_train, y_test = train_test_split(data['data'], data['target'], test_size=.2)

dtrain = xgboost.DMatrix(X_train, label=y_train)
# params = {'max_depth':3, 'eta':1, 'objective':'reg:squarederror', 'eval_metric':'rmse'}
params = {'max_depth':3, 'eta':1, 'objective':'reg:linear', 'eval_metric':'rmse'}
bst = xgboost.train(params, dtrain, 10, [(dtrain, 'train')])

bst.save_model('0001_082.model')
```
Here's the code to predict:

```
import xgboost

import numpy as np
import datetime
# os.environ['OMP_NUM_THREADS'] = "1"

bst = xgboost.Booster()
bst.set_param({'nthread': 1})
bst.load_model('/home/luban/0001_082.model')

total_time = 0
np.random.seed(7)
for i in range(1000):
    X_test = np.random.uniform(-1, 10, size=(1000,4))
    dmat = xgboost.DMatrix(X_test)
    start = datetime.datetime.now().timestamp()
    pred = bst.predict(dmat)
    end = datetime.datetime.now().timestamp()
    total_time += end - start

print("time: ", total_time)
print(pred)
```

I use python 3.8.10 and use pip to install different versions of xgboost.I also tried to build and install from source, but the result is the same.

**Comment by marktodisco** [comment]
I haven't narrowed in on the exact version where the regression occurred, but I recently upgraded from `1.6.2` to `1.7.6` and noticed similar issues.

**Comment by trivialfis** [comment]
I can't reproduce the slow down on my machine when comparing 1.7.x with 1.6.x. Using the original script shared in this issue, the time spent on `DMatrix` is not considered.

I recommend the `inplace_predict` function, which avoids the construction of `DMatrix` altogether:
``` python
import xgboost

import numpy as np
import datetime

bst = xgboost.Booster()
bst.set_param({"nthread": 1})
bst.load_model("./0001_082.model")

total_time = 0.0
np.random.seed(7)
for i in range(1000):
    X_test = np.random.uniform(-1, 10, size=(1000, 4))

    start = datetime.datetime.now().timestamp()
    pred = bst.inplace_predict(X_test)
    # dmat = xgboost.DMatrix(X_test)
    # pred = bst.predict(dmat)
    end = datetime.datetime.now().timestamp()
    total_time += end - start

print("time: ", total_time)
```

Aside, there are fast inference libraries out there for model deployment that focus on streaming prediction (instead of batch prediction in XGBoost).
