### ISSUE TITLE
No clear way to save best model

### ISSUE THREAD

**Issue by MightyStud** [dmlc/xgboost#8868]
From XGBoost docs it states that when saving model, it saves the last model not the best model when using early stopping.
* You can get the best score using `bst.best_score` .
* You can get the iteration of that score using `bst.best_iteration`
* You can predict/evaluate using the best model by `bst.predict(Test_data, ntree_limit=bst.best_ntree_limit)`

I can only save the last model using `bst.save_model('name.xgb)`,
however I can't save the best model.

https://github.com/dmlc/xgboost/blob/36ad160501251336bfe69b602acc37ab3ec32d69/doc/python/python_intro.rst#early-stopping

_If early stopping occurs, the model will have two additional fields: `bst.best_score`, `bst.best_iteration`. Note that  will return a model from the last iteration, not the best one._

**Comment by trivialfis** [comment]
Could you please try to use a callback https://xgboost.readthedocs.io/en/stable/python/python_api.html#xgboost.callback.EarlyStopping ?
