### ISSUE TITLE
[R] How to specify the number of threads in `predict.xgb.Booster()`?

### ISSUE THREAD

**Issue by kadyb** [dmlc/xgboost#8869]
I see that we can specify the number of threads in [train()](https://cran.r-project.org/web/packages/xgboost/xgboost.pdf#Rfn.xgb.train.1) using `nthread` parameter, but can it be done in [predict()](https://cran.r-project.org/web/packages/xgboost/xgboost.pdf#Rfn.predict.xgb.Booster.1)? Currently all threads are used by default.

**Comment by trivialfis** [comment]
Hi, you can set the parameter on the booster.

**Comment by kadyb** [comment]
Thanks! Maybe you could add a separate `nthread` argument to `predict()`? Now when we save the model with `xgb.save()` (without parameters), all threads will be used for prediction.

**Comment by trivialfis** [comment]
The following snippet is extracted from the document of `xgb.parameters<-` function:

``` md
#' data(agaricus.train, package='xgboost')
#' train <- agaricus.train
#'
#' bst <- xgboost(data = train$data, label = train$label, max_depth = 2,
#'                eta = 1, nthread = 2, nrounds = 2, objective = "binary:logistic")
#'
#' xgb.parameters(bst) <- list(eta = 0.1)
```

**Comment by kadyb** [comment]
Are you sure this setting is being used? It seems that all threads are used.

```r
library("xgboost") # 1.7.3.1

n = 10000
data = data.frame(y = sample(0:1, n, replace = TRUE),
                  x1 = rnorm(n), x2 = rnorm(n), x3 = rnorm(n))
data = as.matrix(data)
train = xgb.DMatrix(data[, -1], label = data[, 1])
params = list(objective = "multi:softprob", nthread = 12)
mdl = xgb.train(train, nrounds = 5, params = params, num_class = 2)
xgb.save(mdl, "test.model")

mdl = xgb.load("test.model")
xgb.parameters(mdl) = list(nthread = 2)
n = 100000000
newdata = data.frame(x1 = rnorm(n), x2 = rnorm(n), x3 = rnorm(n))
newdata = as.matrix(newdata)
pred = predict(mdl, newdata) # check `top` here
```

![test](https://user-images.githubusercontent.com/35004826/223578673-e0455904-eb1f-46fd-9153-f9084c6b3769.png)

**Comment by kadyb** [comment]
I probably found the cause. I actually used R matrix, but I guess you automatically convert it to `xgb.DMatrix` and that uses all threads by default. This way everything is ok:

```r
newdata = data.frame(x1 = rnorm(n),x2 = rnorm(n), x3 = rnorm(n))
newdata = xgb.DMatrix(as.matrix(newdata), nthread = 2)
pred = predict(mdl, newdata)
```

**Comment by trivialfis** [comment]
Thank you for the testing!  We keep the predict function to be stateless so that it can be thread safe (one can call inference in many threads with different data). Adding a parameter there will cause race condition.

**Comment by trivialfis** [comment]
Thank you for the suggestion @kadyb , please open a PR for the note.

**Comment by kadyb** [comment]
PR here: https://github.com/dmlc/xgboost/pull/8886
