### ISSUE TITLE
question about gblinear in R

### ISSUE THREAD

**Issue by tngks66** [dmlc/xgboost#888]
i set a (booster = "gblinear" and objective = "reg:linear") . data(a) feature have two numeric and three categorical(no order).
i make model (xgb.a <- xgboost( data = a, booster = "gblinear", objective = "reg:linear" ....etc)
and i make xgb.importance model ( imfor_a <- xgb.importance( model = xgb.a,......etc)
imfor_a have two feature ( feature of a and weight). 
i don`t know about that if feature are categorical, what weight means.
in the process( gblinear algorithm ) is dummy coding  applied? or do weight have other means?? 
help

**Comment by khotilov** [comment]
One should take care of encoding categorical features before feeding data to xgboost. 
When categoricals are one-hot-encoded beforehand, weights would corresponds to weights of specific category levels.
