### ISSUE TITLE
Property best_iteration not reflecting the best iteration when trained without early stopping

### ISSUE THREAD

**Issue by flaviopereira-maersk** [dmlc/xgboost#8880]
I think I found what I consider to be an issue related to the _best_iteration_ property of a fitted model. When training a model without early stopping, the _best_iteration_ property gets filled with the last iteration number, even though it may not be the best iteration. This can be misleading, as it implies that the last iteration was the best iteration, even when that's not the case.

To find the true best iteration, one can perform an _argmin_ on the evals_result list of RMSEs after the training is complete. This will reveal that there are better iterations than the last one - which is the one stored in the best_iteration property. The workaround for this issue is to use _early_stopping_rounds_ with a value greater than or equal to _num_estimators_.

One potential improvement to this issue would be to make the _best_iteration_ property always have the iteration number where the _eval_metric_ was the best. This would make the property more informative and accurate and would help avoid confusion and errors caused by relying on the last iteration number as the best iteration.

Also, docs say the _best_iteration_ property only has a value when early stopping is active, which is not true.

**Comment by trivialfis** [comment]
Thank you for raising the issue. Let me take a closer look into it.
