### ISSUE TITLE
features_cols param requires enabling use_gpu in pyspark 

### ISSUE THREAD

**Issue by yananchen1989** [dmlc/xgboost#8885]
hi, I am using xgboost 1.7.4 in pyspark distributional training.

Here is the code:
```
df_assemble_dense_train_, df_assemble_dense_test = df_ix_oht_l_train.randomSplit([0.8, 0.2])

training_valid_data = df_assemble_dense_train_.withColumn("validationIndicatorCol", rand(1) >= 0.9)
xgbm = SparkXGBClassifier(
          features_col= [x.name for x in training_valid_data .schema if x.name != "label"]
          label_col= "label",
          n_estimators = 3000, 
          max_depth = 7,
          max_bin  = 256,
          learning_rate = 0.1,
          min_child_weight = 0.2,
          subsample = 0.7,
          colsample_bytree = 0.7,
          # reg_alpha  = 0,
          # reg_lambda =0,
          num_workers = 15,
          max_cat_to_onehot = 10,
          max_cat_threshold = 1000,
          eval_metric="auc",
          early_stopping_rounds = 50,
          # missing=None,

          maximize_evaluation_metrics = True,
          validation_indicator_col="validationIndicatorCol"
)

# train and return the model
model = xgbm.fit(training_valid_data)
```

ERROR:

> ValueError                                Traceback (most recent call last)
> <command-1261956356550631> in <module>
>      27 
>      28     # train and return the model
> ---> 29     model = xgbm.fit(training_valid_data)
>      30 
>      31     predictions_test = model.transform(df_assemble_dense_test)
> 
> /databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_pyspark.py in patched_method(self, *args, **kwargs)
>      28             call_succeeded = False
>      29             try:
> ---> 30                 result = original_method(self, *args, **kwargs)
>      31                 call_succeeded = True
>      32                 return result
> 
> /databricks/spark/python/pyspark/ml/base.py in fit(self, dataset, params)
>     159                 return self.copy(params)._fit(dataset)
>     160             else:
> --> 161                 return self._fit(dataset)
>     162         else:
>     163             raise TypeError("Params must be either a param map or a list/tuple of param maps, "
> 
> /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.8/site-packages/xgboost/spark/core.py in _fit(self, dataset)
>     645     def _fit(self, dataset):
>     646         # pylint: disable=too-many-statements, too-many-locals
> --> 647         self._validate_params()
>     648         label_col = col(self.getOrDefault(self.labelCol)).alias(alias.label)
>     649 
> 
> /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.8/site-packages/xgboost/spark/estimator.py in _validate_params(self)
>     228 
>     229     def _validate_params(self):
> --> 230         super()._validate_params()
>     231         if self.isDefined(self.qid_col):
>     232             raise ValueError(
> 
> /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.8/site-packages/xgboost/spark/core.py in _validate_params(self)
>     287         if self.getOrDefault(self.features_cols):
>     288             if not self.getOrDefault(self.use_gpu):
> --> 289                 raise ValueError("features_cols param requires enabling use_gpu.")
>     290 
>     291             get_logger(self.__class__.__name__).warning(
> 
> ValueError: features_cols param requires enabling use_gpu.

It seems that for param : features_col, I can not pass in with a list of feature columns names. 
It works only when I assemble the feature columns into dense vector.
However, I find that in the doc https://github.com/dmlc/xgboost/blob/master/doc/tutorials/spark_estimator.rst
saying that 

> the "features" column(s) must be pyspark.ml.linalg.Vector type or spark array type or a list of feature column names.

Am I miss something ? Thanks.

**Comment by trivialfis** [comment]
This is an XGBoost extension for GPU acceleration. On CPU, the convention established by the spark-ml library is used, where all features are stored in a single dataframe column

**Comment by yananchen1989** [comment]
> 

thanks.

**Comment by erikhuck** [comment]
@trivialfis @yananchen1989  so wait how do you actually solve the problem? How does the code need to change. I'm getting the same error and I pass in a spark DataFrame into fit, specifying which column is the class (a string) and which columns are features with a list. See my code:
```
import pyspark.sql as psql
import xgboost.spark
spark = psql.SparkSession.builder.getOrCreate()
df = spark.read.parquet('dataset.parquet')
train, test = df.randomSplit([0.9, 0.1], seed=0)
label_name = 'label'
feature_names = [x.name for x in df.schema if x.name != label_name]

classifier = xgboost.spark.SparkXGBClassifier(
  features_col=feature_names,
  label_col=label_name,
  num_workers=2,
  device="cuda",
)
classifier.fit(train)
```

**Comment by wbo4958** [comment]
@erikhuck, If your node has only 1 GPU, you need to set `num_workers=1`.  I just tried your code to train a model on the iris dataset, it can work.

**Comment by erikhuck** [comment]
@wbo4958 I really appreciate your help!
