### ISSUE TITLE
Feature names not captured for Arrow table inputs

### ISSUE THREAD

**Issue by braaannigan** [dmlc/xgboost#8910]
Thanks for implementing support for Arrow table inputs.

I can fit a model with an Arrow table from Polars and that part works well. However, the feature column names are not captured correctly.

For example, this model fits really well...
```python
import numpy as np
import polars as pl
import xgboost as xgb

N = 1000
K = 3
df = pl.DataFrame(np.random.standard_normal((N, K))).with_columns(
    pl.when(pl.col("column_0") > 0).then(1).otherwise(0).alias("target")
)
model = xgb.XGBClassifier(objective="binary:logistic")

model.fit(df.select(pl.col(pl.Float64)).to_arrow(), df["target"])

df.hstack([pl.Series("pred", model.predict(df.select(pl.col(pl.Float64)).to_arrow()))])
```

but when I try to do anything with the feature names I get this exception:
```python
model.feature_names_in_
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[2], line 1
----> 1 model.feature_names_in_

File /path/site-packages/xgboost/sklearn.py:1231, in XGBModel.feature_names_in_(self)
   1229 feature_names = self.get_booster().feature_names
   1230 if feature_names is None:
-> 1231     raise AttributeError(
   1232         "`feature_names_in_` is defined only when `X` has feature names that "
   1233         "are all strings."
   1234     )
   1235 return np.array(feature_names)

AttributeError: `feature_names_in_` is defined only when `X` has feature names that are all strings.

```
However, the feature names are all string.

Any thoughts?

**Comment by trivialfis** [comment]
Could you please try to use pandas for now? I think we might be removing the code added in https://github.com/dmlc/xgboost/pull/7512 and simply convert arrow into numpy array as done in https://github.com/dmlc/xgboost/pull/8653 .

cc @xwu99

**Comment by braaannigan** [comment]
@trivialfis @xwu99 FWIW you could use Polars to handle these kinds of issues as it can take an Arrow table with zero-copy and has methods in place for iterating over them even if they are in chunks
