### ISSUE TITLE
pyspark xgboost model persistence issue

### ISSUE THREAD

**Issue by yananchen1989** [dmlc/xgboost#8924]
xgboost 1.7.4
spark 3.2.1

I tried to use the demo codes to save and load back model, which is in pyspark.

here is the doc:
https://xgboost.readthedocs.io/en/stable/tutorials/spark_estimator.html#model-persistence
what is the `SparkXGBRankerModel` ? Looks like a typo ?

On the other hand, the saved model cannot be loaded back with the new classifier instance.

```
from xgboost.spark import SparkXGBClassifier 

xgbm = SparkXGBClassifier(
                  features_col= "features_assemble_dense",
                  label_col= "label",
                  n_estimators = 3000, 
                  max_depth = 7,
                  max_bin  = 256,
                  learning_rate = 0.1,
                  min_child_weight = 0.2,
                  subsample = 0.7,
                  colsample_bytree = 0.7,
                  # reg_alpha  = 0,
                  # reg_lambda =0,
                  num_workers = 15,
                  max_cat_to_onehot = 10,
                  max_cat_threshold = 1000,
                  eval_metric="auc",
                  early_stopping_rounds = 50,
                  # missing=None,
                  maximize_evaluation_metrics = True,
                  validation_indicator_col="validationIndicatorCol"
        )
model_ = xgbm.load("gs://definity-aw-prod-dswork-pidc/temp/dynamic_time_frame/model_persistence/bst_{}".format(2000))
```
error:

> AssertionError                            Traceback (most recent call last)
> <command-964544889692840> in <module>
>      22                   validation_indicator_col="validationIndicatorCol"
>      23         )
> ---> 24 model_ = SparkXGBClassifier.load("gs://definity-aw-prod-dswork-pidc/temp/dynamic_time_frame/model_persistence/bst_{}".format(2000))
> 
> /databricks/spark/python/pyspark/ml/util.py in load(cls, path)
>     461     def load(cls, path):
>     462         """Reads an ML instance from the input path, a shortcut of `read().load(path)`."""
> --> 463         return cls.read().load(path)
>     464 
>     465 
> 
> /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.8/site-packages/xgboost/spark/model.py in load(self, path)
>     177         load model.
>     178         """
> --> 179         _, pyspark_xgb = _SparkXGBSharedReadWrite.loadMetadataAndInstance(
>     180             self.cls, path, self.sc, self.logger
>     181         )
> 
> /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.8/site-packages/xgboost/spark/model.py in loadMetadataAndInstance(pyspark_xgb_cls, path, sc, logger)
>     115         :return: a tuple of (metadata, instance)
>     116         """
> --> 117         metadata = DefaultParamsReader.loadMetadata(
>     118             path, sc, expectedClassName=get_class_name(pyspark_xgb_cls)
>     119         )
> 
> /databricks/spark/python/pyspark/ml/util.py in loadMetadata(path, sc, expectedClassName)
>     655         metadataPath = os.path.join(path, "metadata")
>     656         metadataStr = sc.textFile(metadataPath, 1).first()
> --> 657         loadedVals = DefaultParamsReader._parseMetaData(metadataStr, expectedClassName)
>     658         return loadedVals
>     659 
> 
> /databricks/spark/python/pyspark/ml/util.py in _parseMetaData(metadataStr, expectedClassName)
>     674         className = metadata['class']
>     675         if len(expectedClassName) > 0:
> --> 676             assert className == expectedClassName, "Error loading metadata: Expected " + \
>     677                 "class name {} but found class name {}".format(expectedClassName, className)
>     678         return metadata
> 
> AssertionError: Error loading metadata: Expected class name xgboost.spark.estimator.SparkXGBClassifier but found class name xgboost.spark.core.SparkXGBClassifierModel

**Comment by trivialfis** [comment]
I think `SparkXGBRankerModel` is indeed a typo, it's for learning to rank, not for regression.

To load a model, you need to use a model class: `SparkXGBRegressorModel` is returned by the estimator class `SparkXGBRegressor.fit` method.

**Comment by yananchen1989** [comment]
@trivialfis thanks.

model from `SparkXGBRegressor.fit` with training data is tested and and be used for loading the saved model. Therefore, it seems that `fit` operation is a necessary stage before loading.

**Comment by trivialfis** [comment]
？ The fit method produces a model, which can be loaded later.
