### ISSUE TITLE
`SparkXGBRankerModel cannot be imported from xgboost.spark`

### ISSUE THREAD

**Issue by mhmotamedi** [dmlc/xgboost#8939]
Similar to `SparkXGBClassifierModel` and `SparkXGBRegressorModel`, I'm attempting to import `SparkXGBRankerModel` from `xgboost.spark`. Nevertheless, facing the error: _`SparkXGBRankerModel cannot be imported from xgboost.spark`_
Currently, I am using `xgboost = {version= "==1.7.3"}`.

**Comment by trivialfis** [comment]
Hi, could you please share the full error trace? We have one import guard : https://github.com/dmlc/xgboost/blob/9b6cc0ed07519040c677ce2f1ff64d170b0f428e/python-package/xgboost/spark/__init__.py#L6 , the error message is different from what you have shared. I'm not sure where is the  error coming from.

**Comment by mhmotamedi** [comment]
I've already installed pyspark==3.1.3 and  xgboost==1.7.3 on my venv. However I am not able to import `SparkXGBRankerModel`. Here is the error:
```
pip list | grep "pyspark\|xgboost"
pyspark                  3.1.3
xgboost                  1.7.3
python
Python 3.8.16 (default, Mar  6 2023, 10:51:55) 
[Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from xgboost.spark import SparkXGBClassifierModel, SparkXGBRegressorModel
>>> from xgboost.spark import SparkXGBRankerModel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'SparkXGBRankerModel' from 'xgboost.spark' (/Users/pqz206/.local/share/virtualenvs/xgboost_core-x9p-cubB/lib/python3.8/site-packages/xgboost/spark/__init__.py)
```

**Comment by trivialfis** [comment]
Apologies, this is fixed in https://github.com/dmlc/xgboost/pull/8692 .

For now, as a workaround please use:
``` python
from xgboost.spark.estimator import SparkXGBRankerModel
```
