### ISSUE TITLE
Cannot load pyspark xgboost model from S3 bucket

### ISSUE THREAD

**Issue by mhmotamedi** [dmlc/xgboost#8945]
Successfully saved the pyspark-xgboost model on S3 bucket which creates two following subfolders: `xgboost.model/metadata/` and `xgboost.model/model/`. However, I was not able to load and reuse the sparkxgboost model from s3 bucket! I have a suspicion that the training data, which contains null values, may be somehow connected to this problem. I already set the `missing` parameter to 0.0.
```
Saving the trained model into path:
s3://<bucket_name>/model/xgboost/model/xgboost.model
trained_model.write().overwrite().save(path_to_output_model)
Loading a pre-trianed model from path:
s3://<bucket_name>/model/xgboost/model/xgboost.model
[Stage 0:>                                                          (0 + 1) / 1]                                                                                
[Stage 1:>                                                          (0 + 1) / 1]                                                                            
[Stage 3:>                                                          (0 + 1) / 1]
                                                            
--- Logging error ---
Traceback (most recent call last):
  File "/tmp/tmp.TQLrz32MjV", line 843, in predict
    model = model.load(path_to_xgb_model)
  File "/opt/spark/python/lib/pyspark.zip/pyspark/ml/util.py", line 332, in load
    return cls.read().load(path)
  File "/opt/conda/lib/python3.8/site-packages/xgboost/spark/model.py", line 226, in load
    _, py_model = _SparkXGBSharedReadWrite.loadMetadataAndInstance(
  File "/opt/conda/lib/python3.8/site-packages/xgboost/spark/model.py", line 121, in loadMetadataAndInstance
    DefaultParamsReader.getAndSetParams(pyspark_xgb, metadata)
  File "/opt/spark/python/lib/pyspark.zip/pyspark/ml/util.py", line 559, in getAndSetParams
    instance.set(param, paramValue)
  File "/opt/spark/python/lib/pyspark.zip/pyspark/ml/param/__init__.py", line 405, in set
    value = param.typeConverter(value)
  File "/opt/spark/python/lib/pyspark.zip/pyspark/ml/param/__init__.py", line 213, in toString
    raise TypeError("Could not convert %s to string type" % type(value))
TypeError: Could not convert <class 'NoneType'> to string type
```

**Comment by trivialfis** [comment]
@WeichenXu123 Could you please help take a look?

**Comment by wbo4958** [comment]
@mhmotamedi could you tell how to repro this issue? with some minor dataset. That can help. Thx

**Comment by WeichenXu123** [comment]
> I have a suspicion that the training data, which contains null values,

This shouldn't be training data issue, it is issue when loading param values.

Could you print the param name that causes the issue ? You can do it by running following patching code

```
import pyspark.ml.param

def _param_value_to_string(value):
        if isinstance(value, str):
            return value
        elif type(value) in [np.string_, np.str_, np.unicode_]:
            return str(value)
        else:
            raise ValueError()

pyspark.ml.param.TypeConverters = _param_value_to_string
```
and then rerun your code.

**Comment by wbo4958** [comment]
Hi @WeichenXu123 

May I ask how this code work?

``` python
import pyspark.ml.param

def _param_value_to_string(value):
        if isinstance(value, str):
            return value
        elif type(value) in [np.string_, np.str_, np.unicode_]:
            return str(value)
        else:
            raise ValueError()

pyspark.ml.param.TypeConverters = _param_value_to_string
```

**Comment by wbo4958** [comment]
> Because in spark estimator.set, it will check the error type raised from value conversion routine, if error type is value error, in `set` function it will raise refined error message containing param name.

@WeichenXu123  Thx. But what I'm wondering is how to run the following code you pasted ?

``` python
import pyspark.ml.param

def _param_value_to_string(value):
        if isinstance(value, str):
            return value
        elif type(value) in [np.string_, np.str_, np.unicode_]:
            return str(value)
        else:
            raise ValueError()

pyspark.ml.param.TypeConverters = _param_value_to_string
```

**Comment by WeichenXu123** [comment]
> > Because in spark estimator.set, it will check the error type raised from value conversion routine, if error type is value error, in `set` function it will raise refined error message containing param name.
> 
> @WeichenXu123 Thx. But what I'm wondering is how to run the following code you pasted ?
> 
> ```python
> import pyspark.ml.param
> 
> def _param_value_to_string(value):
>         if isinstance(value, str):
>             return value
>         elif type(value) in [np.string_, np.str_, np.unicode_]:
>             return str(value)
>         else:
>             raise ValueError()
> 
> pyspark.ml.param.TypeConverters = _param_value_to_string
> ```

Sorry, my code is wrong, the last line of above code should be

```
pyspark.ml.param.TypeConverters.toString = _param_value_to_string
```
