### ISSUE TITLE
xgboost.spark.SparkXGBClassifier vs xgboost.spark.estimator SparkXGBClassifier

### ISSUE THREAD

**Issue by mhmotamedi** [dmlc/xgboost#8965]
I noticed that there are two options to import the xgboost estimators such as SparkXGBRegressor, SparkXGBClassifier, SparkXGBRanker:

1- from `xgboost.spark` import (
            SparkXGBClassifier,
            SparkXGBRanker,
            SparkXGBRegressor,
        ) 

2- from `xgboost.spark.estimator` import (
            SparkXGBClassifier,
            SparkXGBRanker,
            SparkXGBRegressor,
        ) 

It seems both approaches can be used for training the model (.fit). I wonder why we have this redundancy in the library. 

I wonder if the following way of importing spark_xgb estimators (`from xgboost.spark import SparkXGBClassifier`) and model (`from xgboost.spark.estimator import  SparkXGBClassifierModel`) makes sense. Currently, I did not notice any problems with that. 

```
from **xgboost.spark** import SparkXGBClassifier,

model = SparkXGBClassifier.fit(train_dataset, model_kwargs)
model.save(path_to_model_output)

from xgboost.spark.estimator import  SparkXGBClassifierModel

pretrianed_model = SparkXGBClassifierModel.load(path_to_model_output)
pretrianed_model.transform(new_dataset)
```

**Comment by trivialfis** [comment]
The `estimator` is a submodule of the `spark` module: https://github.com/dmlc/xgboost/blob/cff50fe3efc92edb691a4ce6e710c6909525b23d/python-package/xgboost/spark/__init__.py#L9 Please use the `spark` module when possible.

**Comment by mhmotamedi** [comment]
@trivialfis Makes sense. May I ask why `SparkXGBRankerModel` is missing from `xgboost.spark`? Is there a reason the SparkXGBRankerModel is only available in the `xgboost.spark.estimator` submodule and not `xgboost.spark` itself?

**Comment by trivialfis** [comment]
It was an oversight when ranker is implemented. It's fixed in the latest
