### ISSUE TITLE
enable_categorical in R.

### ISSUE THREAD

**Issue by nipnipj** [dmlc/xgboost#8969]
How can we use `enable_categorical` functionality in R?

**Comment by nipnipj** [comment]
> It's not implemented for R yet.

Are there differences between this functionality and using binary dummy variables? Maybe in computational time, or prediction performance.

**Comment by trivialfis** [comment]
I'm currently on my phone, you can find an introduction from xgboost s document, under the tutorials section.

**Comment by trivialfis** [comment]
Closing, the R support is tracked in https://github.com/dmlc/xgboost/issues/7899 .
