### ISSUE TITLE
Poetry 1.4.1 installation issue with xgboost 1.7.4

### ISSUE THREAD

**Issue by ralscha** [dmlc/xgboost#8987]
We are installing xgboost with Poetry. 
This works great with Poetry 1.3.2. 
But with Poetry 1.4.1 we longer can't install xgboost on Windows. 
The following error occurrs

```  
• Installing xgboost (1.7.4): Failed

  _WheelFileValidationError

  ['In C:\\Users\\use\\AppData\\Local\\pypoetry\\Cache\\artifacts\\22\\a3\\4d\\c286bdc72bd13f47699a5ebe1b4d9c0ec4565215cae93511681d43f34d\\xgboost-1.7.4-py3-none-win_amd64.whl, xgboost-1.7.4+36ad160501251336bfe69b602acc37ab3ec32d69.data/data/xgboost/vcomp140.dll is not mentioned in RECORD']

  at ~\AppData\Roaming\pypoetry\venv\Lib\site-packages\installer\sources.py:289 in validate_record
      285│                         f"In {self._zipfile.filename}, hash / size of {item.filename} didn't match RECORD"
      286│                     )
      287│
      288│         if issues:
    → 289│             raise _WheelFileValidationError(issues)
      290│
      291│     def get_contents(self) -> Iterator[WheelContentElement]:
      292│         """Sequential access to all contents of the wheel (including dist-info files).
      293│

  • Installing prj (0.1.0 C:/ws/home/project/core/shared/prj)

```

**Comment by trivialfis** [comment]
hmm , Windows + poetry .. Unfortunately, we don't have any active contributor who uses this combination of platforms. Some help from others would be appreciated. ;-)

**Comment by dimbleby** [comment]
presumably caused by this code https://github.com/dmlc/xgboost/blob/0d3da9869cfab02f7d61984d6b1e37973d087c48/tests/ci_build/insert_vcomp140.py?  which adds that file to the wheel but does not mention it in the RECORD

**Comment by trivialfis** [comment]
Thank you for sharing, let me learn more about how to build the wheel properly.

**Comment by trivialfis** [comment]
@hcho3 We might need to incorporate that script into the setup process, along with Linux and macos builds so that the setuptools recognize them. But then the setuptools seems to be being sunset now?

**Comment by trivialfis** [comment]
@hcho3 For Linux, can we link libgomp statically?
``` sh
$ g++ --print-file-name=libgomp.a
```
```
/usr/lib/gcc/x86_64-linux-gnu/11/libgomp.a
```

**Comment by hcho3** [comment]
@trivialfis Let's not make it complicated. Setuptools are being sunset, so I'd rather not modify the setup script; we should instead adopt scikit-build or other modern alternatives.

As for libgomp, we already bundle libgomp into the Linux binary wheel using auditwheel, which should update the RECORD file appropriately. So the issue is affecting Windows only.

The simple fix is to fix insert_vcomp140.py to update RECORD.

**Comment by hcho3** [comment]
Hi everyone, I submitted #8991 to fix the binary wheel. Now the `RECORD` file will have an entry corresponding to `vcomp140.dll`. I tested the fix locally on my Windows machine and Poetry was able to install the fixed wheel.
