### ISSUE TITLE
Zeroes get sent to missing node in R (intended?)

### ISSUE THREAD

**Issue by DexGroves** [dmlc/xgboost#899]
Hey all,

Not sure if this is intended behavior or not, but it seems strange. For numerics that can take on the value of exactly zero it seems like the zeroes are treated as missing and have extra mobility to choose the left or right node. This causes unusual splits. Here's an example, where -1 and 1 go to the left node, but zero goes to the right node.

https://gist.github.com/DexGroves/9e5dbd42142ba7f9e8b3

![xgweird](https://cloud.githubusercontent.com/assets/10374782/13425513/312a80cc-df9f-11e5-83a1-7a8f688ce523.png)

On the CRAN version, this is the same for both sparse and dense matrices. The version I installed from github today only behaves this way for sparse matrices, but has different undesirable behavior in that my choice of sparse or dense encoding actually changes the resultant model structure (as long as there are zeroes).

https://gist.github.com/DexGroves/279e5307bfd4673d4db3

**Comment by khotilov** [comment]
"No-value" elements or zeros in sparse format data are treated as missing values in xgboost.
It's better not to use sparse format when zeros are actually meaningful numbers, especially when they don't contribute much to sparsity.

**Comment by DexGroves** [comment]
That behavior is a bug. The predictor in the example gains nothing from sparsity, but if it was sharing a design matrix with other truly sparse columns then its zeroes should not be getting special treatment. This isn't as simple as refit without sparsity for real applications.

What is also concerning is that the scores from an xgboost model are dependent on how one encodes their scoring data, which is unequivocally bad. Data is data is data. At least, xgboost should refuse to score on a matrix of the opposite class to the one on which it was trained.

**Comment by tqchen** [comment]
By using dense matrix, you always get the "correct" behavior in the most recent version.

Normally in the  sparse matrix case, the non-presenting columns can either be interpreted as "missing" or 
"zero". XGBoost handles both case correctly, as long as you consistently encode the sparse matrix.
