### ISSUE TITLE
 Top contributing features per id in xgboost model? 

### ISSUE THREAD

**Issue by msdw** [dmlc/xgboost#900]
Hi,

Using Xgboost (thanks for this great package), I have in output top features order by importance.
I would like this information per id/line. Why ? For business, it could be very interesting to know the top contributing features of the score by id/line to qualify interest/problem of customer.

what do you think about my ask ?
How to have these informations?
Thanks for your return.
M.

**Comment by khotilov** [comment]
What does "by id/line" means in your question? Are you asking about how to find out which features contributed most to a prediction for an individual case?

**Comment by msdw** [comment]
Hi,

 

Sorry for my late answer.

Yes, in my mind, I would like to know which features contributed most to a prediction for an individual case.

Is it possible to have this kind of contribution ?

 

De : Vadim Khotilovich [mailto:notifications@github.com] 
Envoyé : vendredi 4 mars 2016 04:24
À : dmlc/xgboost <xgboost@noreply.github.com>
Cc : M. ACHE <msdw@free.fr>
Objet : Re: [xgboost] Top contributing features per id in xgboost model? (#900)

 

What does "by id/line" means in your question? Are you asking about how to find out which features contributed most to a prediction for an individual case?

—
Reply to this email directly or view it on GitHub <https://github.com/dmlc/xgboost/issues/900#issuecomment-192080058> .  <https://github.com/notifications/beacon/AERBSDh4esDdhB2svFJU0ea4aAQu34kKks5pp6WygaJpZM4HnWI1.gif> 



---
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
https://www.avast.com/antivirus

**Comment by khotilov** [comment]
It's the easiest to do with linear models (e.g., you can try if gblinear booster would work for you). Feature's coefficient * value would signify its contribution to an individual case.

For nonlinear models it usually not that straightforward to do. Some workarounds exist. E.g., for an individual case, for every single feature try replacing its current value with something like a median, mode, or different binary level, etc, and note the change in prediction score as the magnitude of the individual influence. However, when an outcome is significantly affected by feature interactions, this outlined simple approach might be not sufficient.
