### ISSUE TITLE
Build xgboost with GPU support failed, with cmake and vs2022

### ISSUE THREAD

**Issue by sstww** [dmlc/xgboost#9003]
DELL precision 7560 laptop computer with Windows 10 and NVIDIA RTX A2000 GPU. 
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.0
CMake 3.26.1
NVIDIA cuDNN library is installed: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.0\bin

This is the code and error message: 
cmake .. -G "Visual Studio 17 2022" -A x64 -DUSE_CUDA=ON -DR_LIB=ON
C:\Users\userA\xgboost\build>cmake .. -G "Visual Studio 17 2022" -A x64 -DUSE_CUDA=ON -DR_LIB=ON
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19044.
-- CMake version 3.26.1
-- xgboost VERSION: 2.0.0
-- Configured CUDA host compiler: C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Tools/MSVC/14.35.32215/bin/Hostx64/x64/cl.exe
CMake Warning at C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCUDACompiler.cmake:15 (message):
  Visual Studio does not support specifying CUDAHOSTCXX or
  CMAKE_CUDA_HOST_COMPILER.  Using the C++ compiler provided by Visual
  Studio.
Call Stack (most recent call first):
  CMakeLists.txt:144 (enable_language)

CMake Error at C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:501 (message):
  No CUDA toolset found.
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:8 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:53 (__determine_compiler_id_test)
  C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCUDACompiler.cmake:307 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:144 (enable_language)

-- Configuring incomplete, errors occurred!

**Comment by trivialfis** [comment]
```
CMake Error at C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:501 (message):
No CUDA toolset found.
```
How did you install CUDA?

**Comment by sstww** [comment]
Yes, I showed the path and version of the cuda installation:

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.0

**Comment by sstww** [comment]
Can anyone help please? I can't imaging that it is a vey unique problem.

**Comment by trivialfis** [comment]
It's indeed not reproducible on may laptop, on which I have both the latest VS and CUDA.

Could you please isolate issue by working with a simple CMake script that simply calls `enable_language` with CUDA, and check whether the configuration can proceed? I doubt that this is a XGBoost issue as the CMake script is quite simple and standard.

**Comment by trivialfis** [comment]
Feel free to reopen if there's further information.

**Comment by SiqingHe** [comment]
i meet this question too! hope a solution to this problem

**Comment by SiqingHe** [comment]
solved ,  it maybe because the visual stuido Integration,
copy the files in 
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\extras\visual_studio_integration\MSBuildExtensions
to
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\BuildCustomizations
and it works

**Comment by Tires** [comment]
In my system the target path was:
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\BuildCustomizations
