### ISSUE TITLE
DMatrix vs. QuantileDMatrix training times

### ISSUE THREAD

**Issue by dthiagarajan** [dmlc/xgboost#9013]
I recently upgraded from xgboost==1.4.2 in Python to xgboost==1.7.4 in Python, and I'm trying to train XGBoost regression with `tree_method='hist'` on a dataset I was previously training on, but I noticed that the training times are much slower. I isolated the difference to the fact that XGBoost was previously using a `DMatrix` for training, and it is now using a `QuantileDMatrix` for training, both on CPU. 

For each boosting iteration, with the `DMatrix`, it takes 4-5 seconds, vs. with the `QuantileDMatrix`, it takes 80-90 seconds per boosting iteration. Is this expected?

When I looked at the verbose logs, I saw in the 1.4.2 version's training:
```
Tree method is selected to be 'hist', which uses a single updater grow_quantile_histmaker.
tree pruning end, 6 extra nodes, 0 pruned nodes, max_depth=2
```
but in 1.7.4 version's training, I only saw:
```
Tree method is selected to be 'hist', which uses a single updater grow_quantile_histmaker.
```
and now the message about tree pruning. Is this discrepancy expected in the new version?

**Comment by trivialfis** [comment]
The trainign slow down is not expected, could you please share some information about your data? Including the shape, the sparsity and the type (classification/regression/ranking/survival).

The reduced logging is expected. We changed from post-pruning to pre-pruning.

**Comment by dthiagarajan** [comment]
Sure! I'm doing distributed training for regression, with 20170140 samples distributed across 2 nodes, and 1 worker per node. Each sample has 960 features.

Is there some metric I can print to figure out the sparsity that you're looking for?

**Comment by trivialfis** [comment]
> Is there some metric I can print to figure out the sparsity that you're looking for?

The total number of valid values divided by the total number of values. If you are using dense matrix and there's no nan/inf, feel free to ignore this question.

Could you please share how do you perform distributed training as well? Are you using dask, or are you using some custom scripts that control the distributed training?

**Comment by dthiagarajan** [comment]
Ah okay, I'm using a dense matrix (`np.ndarray`), but it is pretty sparse (roughly 30% of values are 0).

**Comment by dthiagarajan** [comment]
> Could you please share how do you perform distributed training as well? Are you using dask, or are you using some custom scripts that control the distributed training?
I'm using a custom script to control distributed training, through `rabit`.

**Comment by trivialfis** [comment]
Let me take a look later today. For 20170140 sample with 960 features, 3-4 seconds seems a bit too efficient and doesn't feel reasonable to me. Maybe something is missing? A rough calculation, your dataset has size of about 144GB given entries are stored in float32. I would expect xgboost CPU to take much longer than 3 seconds to train an iteration.

**Comment by dthiagarajan** [comment]
Interesting, thanks! Here's the parameters I'm using - I'm specifically going via the `sklearn` interface with `XGBRegressor` in each version.
```
{"verbosity": 3, "tree_method": "hist", "random_state": 2020, "max_depth": 13, "n_estimators": 500, "learning_rate":  0.05, "min_child_weight": 1, "colsample_bytree": 1, "subsample": 1}
```

**Comment by dthiagarajan** [comment]
A related question - during distributed training in previous versions, is there additional memory being used over time? I notice that even with 144GB of data, on a machine with 200GB of RAM, my training fails after ~60 iterations, and I'm trying to understand why.

**Comment by trivialfis** [comment]
> it takes ~15 minutes to construct the QuantileDMatrix

That's too long (not expected). The construction of `QuantileDMatrix` should take lesser time than the first iteration with DMatrix. The long duration of the first iteration using DMatrix is just XGBoost is constructing a `QuantileDMatrix` internally at the first iteration. We are now exposing the QDM to Python in order to skip the construction of `DMatrix`, which is a CSR matrix and takes up more memory than the original dataset. Granted, QDM is parsing Python data, which can be slightly slower, but that by this much.

> each iteration takes around 1-2 seconds,

This varies a lot based on the dataset and the choice of parameter. For instance, if it's over-regularized and XGBoost cannot find any tree split, then it would be extremely fast, even though no useful work can be done. From experience, I find it suprising that CPU hist is this fast.

> A related question - during distributed training in previous versions, is there additional memory being used over time?

The model itself, note that the tree grows exponential in depth (approximately 2^depth nodes) in depthwise grow policy is used (the default). In addition, for many datasets, XGBoost tend to grow deeper trees at later iteration.

I will try to reproduce something with dask.

**Comment by dthiagarajan** [comment]
Thanks for the quick response!

This is how I'm constructing the `QuantileDMatrix` (explicitly) in the new version (1.7.4):
```python3
train_dmatrix = QuantileDMatrix(data=x, label=y, weight=w)
```

and in the old version, I'm doing it through the `lambda` in `XGBModel`, so probably
```python3
lambda **kwargs: DMatrix(nthread=self.n_jobs, **kwargs),
```

looking at it now, maybe the missing `nthread` could be the issue for the construction time. I'm going to try that and see if that fixes the construction time being slow.

**Comment by dthiagarajan** [comment]
> This varies a lot based on the dataset and the choice of parameter. For instance, if it's over-regularized and XGBoost cannot find any tree split, then it would be extremely fast, even though no useful work done.

Is it possible to log this? I have verbosity set to 3, so I'm assuming I'd see a message if XGBoost didn't find a split, but I'm not 100% sure.

**Comment by dthiagarajan** [comment]
Hm even when I pass `nthread=None` explicitly, I still see that it takes 10-15 minutes to construct the `QuantileDMatrix`.

**Comment by trivialfis** [comment]
The default behavior is to use all available threads on the system, which might lead to thread thrashing.

> Is it possible to log this?

No, I usually just inspect the output model in JSON format. `XGBRegressor.save_model("model.json")`. Python has a builtin `json` module that can be used to print a nice formatted file with indentation as a post-processing step.

I built a model using dask with 512 features and 20170140 samples along with `hist` (no other parameters). The time is logged by a training callback. The result is the opposite of what you are describing:

** DMatrix
```
before training: 2023-04-08 01:49:07.989152
before training: 2023-04-08 01:49:10.842017
Iteration: 119.48173689842224
[0]	Train-rmse:138.17903	Valid-rmse:138.17903
Iteration: 119.4821093082428
Iteration: 23.645052671432495
[1]	Train-rmse:121.30954	Valid-rmse:121.30954
Iteration: 23.645132780075073
Iteration: 22.381161212921143
[2]	Train-rmse:107.49895	Valid-rmse:107.49895
Iteration: 22.381171941757202
Iteration: 22.872804403305054
[3]	Train-rmse:96.43525	Valid-rmse:96.43525
Iteration: 22.87283730506897
Iteration: 22.20122003555298
[4]	Train-rmse:87.48283	Valid-rmse:87.48283
Iteration: 22.201245307922363
Iteration: 22.041008234024048
...
[14]	Train-rmse:41.02198	Valid-rmse:41.02198
Iteration: 21.110426902770996
Iteration: 22.071842908859253
After training: 2023-04-08 01:55:06.804832 Duration: 358.8156809806824
Iteration: 22.071651935577393
After training: 2023-04-08 01:55:06.805071 Duration: 355.9630558490753
[15]	Train-rmse:38.67975	Valid-rmse:38.67975
```

** QDM
```
before training: 2023-04-08 01:59:01.082276
before training: 2023-04-08 01:59:01.112346
Iteration: 197.6475682258606
Iteration: 197.64757323265076
[0]	Train-rmse:138.14889	Valid-rmse:138.20948
Iteration: 12.813523054122925
Iteration: 12.813514709472656
[1]	Train-rmse:121.29901	Valid-rmse:121.38152
Iteration: 11.781853675842285
Iteration: 11.781880140304565
[2]	Train-rmse:107.30816	Valid-rmse:107.38201
Iteration: 10.780174255371094
Iteration: 10.780189275741577
[3]	Train-rmse:96.42107	Valid-rmse:96.48631
Iteration: 9.975093364715576
Iteration: 9.975070238113403
[4]	Train-rmse:87.12752	Valid-rmse:87.19046
Iteration: 9.441370248794556
Iteration: 9.441391944885254
...
[14]	Train-rmse:40.55680	Valid-rmse:40.62325
Iteration: 10.069728136062622
After training: 2023-04-08 02:04:00.863677 Duration: 299.75133442878723
Iteration: 10.069887399673462
After training: 2023-04-08 02:04:00.864204 Duration: 299.7819299697876
[15]	Train-rmse:38.11030	Valid-rmse:38.17659
```

**Comment by trivialfis** [comment]
This is my simple script, I'm sure yours is much more sophisticated and has other complexity that I can't reproduce. The data is already cached before running any of the actual test.
```
from time import time
import os

import numpy as np
from datetime import datetime
from dask_ml.datasets import make_regression
from dask_ml.model_selection import train_test_split
from distributed import Client, LocalCluster, Worker, wait
from dask import array as da
import xgboost as xgb
from xgboost import dask as dxgb


def main(client: Client, is_qdm: bool) -> None:
    s = time()
    x_path = "/home/jiamingy/Others/dask_tmp/X"
    y_path = "/home/jiamingy/Others/dask_tmp/y"

    if os.path.exists(x_path):
        X = da.from_npy_stack(x_path)
        y = da.from_npy_stack(y_path)
    else:
        X, y = make_regression(n_samples=20170140, n_features=512, chunks=400000)
        X, y = client.persist([X.astype(np.float32), y.astype(np.float32)])
        da.to_npy_stack(x_path, X)
        da.to_npy_stack(y_path, y)

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.3, random_state=1
    )
    X_train, X_test, y_train, y_test = client.persist(
        [X_train, X_test, y_train, y_test]
    )
    wait([X_train, X_test, y_train, y_test])
    e = time()
    print("Finished generation:", e - s)

    print("before ctor:", datetime.now())
    s = time()

    class TimeIt(xgb.callback.TrainingCallback):
        def __init__(self) -> None:
            self.duration = None
            self.iter_duration = time()

        def after_iteration(self, model, epoch: int, evals_log) -> bool:
            """Run after each iteration.  Return True when training should stop."""
            print("Iteration:", time() - self.iter_duration)
            self.iter_duration = time()
            return False

        def before_training(self, model):
            self.duration = time()
            print("before training:", datetime.now())
            return model

        def after_training(self, model):
            self.duration = time() - self.duration
            print("After training:", datetime.now(), "Duration:", self.duration)
            return model

    if is_qdm:
        Xy = dxgb.DaskDMatrix(client, X_train, y_train)
        Xye = dxgb.DaskDMatrix(client, X_test, y_test)
    else:
        Xy = dxgb.DaskQuantileDMatrix(client, X_test, y_test)
        Xye = dxgb.DaskQuantileDMatrix(client, X_test, y_test, ref=Xy)
    print("after ctor:", datetime.now())

    result = dxgb.train(
        client,
        {"tree_method": "hist"},
        Xy,
        num_boost_round=16,
        evals=[(Xy, "Train"), (Xye, "Valid")],
        callbacks=[TimeIt()]
    )
    print(result["history"])

    e = time()
    print("Duration:", e - s, "Is QDM: ", is_qdm)


if __name__ == "__main__":
    with LocalCluster(
        n_workers=2, local_directory="/home/jiamingy/Others/dask_tmp"
    ) as cluster:
        with Client(cluster) as client:
            with client.as_current():
                main(client, True)
                main(client, False)
```

**Comment by trivialfis** [comment]
apologies for deleting some of the comments, found a mistake. Will post again.

**Comment by dthiagarajan** [comment]
No worries! Your help is much appreciated :)

**Comment by trivialfis** [comment]
I can reproduce the difference, about twice slower for each iteration when qdm is used instead of plain DMatix in the distributed setting. Will take a deeper look next Monday.

**Comment by dthiagarajan** [comment]
Great, thanks for the heads up!

Re: the memory usage, is there any way I can save memory when constructing the DMatrix from dense numpy array? e.g. would constructing from a sparse array be better? I calculated the sparsity for my dataset and it is 60% (i.e. 60% of values are 0).

**Comment by trivialfis** [comment]
0 is considered a valid value for xgboost. A decision tree can split on 0, categorical or numerical.

The QDM is the way to save memory, see https://github.com/dmlc/xgboost/pull/8050#issuecomment-1180868339 . HIGGS is a dense matrix stored in numpy, the memory usage is combined with both the original input array with XGBoost memory consumption. With QDM, XGBoost consumes only a fraction of the memory of the original input. I will look into the performance issue after the weekend. I can't reproduce it on local mode.

At the moment, our biggest bottleneck on CPU memory is actually on other HPO libraries, they make copies of data during DataFrame slicing, and index arrays with the same size of the training dataset.

**Comment by dthiagarajan** [comment]
Hi @trivialfis, just wanted to follow up here - let me know if I can help repro something on my end!

**Comment by dthiagarajan** [comment]
Also, I've noticed that with training times for each iteration (even with DM), the first couple iterations take very little time (1-2 seconds per iteration), but by the ~50th iteration or so, the iterations will take almost 10x longer. Is that expected?

**Comment by trivialfis** [comment]
> No worries. Is each iteration of XGBoost training expected to be slower when using QDM vs. DM?

They should be about the same.

>  the iterations will take almost 10x longer. Is that expected?

That depends on the dataset as mentioned in https://github.com/dmlc/xgboost/issues/9013#issuecomment-1500495150 .

**Comment by trivialfis** [comment]
Hi, could you please share how many evaluation matrices are you suing during training? My initial suspicion is that the slow down is caused by evaluation instead of training. The prediction performance on QDM is not as good as the DM.

**Comment by dthiagarajan** [comment]
I have 1 evaluation matrix, but it's just the training dataset (i.e. I'm evaluating my training dataset), and I'm evaluating every iteration.

I wanted to take advantage of prediction staging, so I construct a DM (in both the old and new version) the first time I evaluate on that dataset, and every iteration after I use that same DM instance to evaluate.

In terms of metrics, I compute metrics outside of the XGBoost API, i.e. I get the predictions from the XGBoost API as a numpy array, and then I compute my own metrics separately. My timing estimates are mostly independent of how long these metrics take to compute (I use the same implementation for metric computation between using the old and new XGBoost versions).

**Comment by dthiagarajan** [comment]
Let me also run without any evaluation when using QDM vs. DM for training to compare.

**Comment by dthiagarajan** [comment]
Even without any evaluation, I see
* for DM, each iteration in the beginning takes 2-3 seconds
* for QDM, each iteration in the beginning takes 25-30 seconds

**Comment by trivialfis** [comment]
Hi, apologies for the many questions. I got a little bit confused, if you are using the sklearn interface:
- Are you calling `regressor.get_booster().predict` for prediction with `DMatrix`?
- If so, are you using `QuantileDMatrix` for the prediction?
- If so, this is a duplicated `DMatrix/QuantileDMatrix` since for training, XGBoost also creates a `DMatrix/QuantileDMatrix`.
- If so, I think the slowdown comes from prediction for evaluation metric. I can reproduce the slowdown and pinpoint it down to prediction for evaluation (although I'm using the metrics inside XGBoost, but the general procedures are the same).

I will work on optimizing the prediction for QDM in the coming days.

**Comment by dthiagarajan** [comment]
No worries! Appreciate the thoroughness.
> Are you calling regressor.get_booster().predict for prediction with DMatrix?
Yep, I'm doing that in both versions, and I'm explicitly constructing a `DMatrix`, and not a `QuantileDMatrix`.

> If so, are you using QuantileDMatrix for the prediction?
No, I'm explicitly constructing a `DMatrix`.

**Comment by trivialfis** [comment]
Just to be sure, both of your experiments using `DMatrix` and `QuantileDMatrix` are using 1.7.4 right?

**Comment by dthiagarajan** [comment]
Ah, no:
- the experiment with `DMatrix` is using 1.4.2
- the experiment using `QuantileDMatrix` is using 1.7.4
but in both cases, I'm still explicitly constructing the `DMatrix` and running prediction using `regressor.get_booster().predict`.

**Comment by trivialfis** [comment]
Hmm, then I suspect something different than the QDM is causing the regression. From my experiments, they are the same in terms of training speed using 1.7.4. (actually QDM is slightly faster)

**Comment by dthiagarajan** [comment]
Interesting, so you're expecting that training with QDM on 1.7.4 would be slightly faster than training with DM on 1.4.2?

I've reproduced the iteration times I was seeing with DM/1.4.2 and QDM/1.7.4, without any evaluation or any other callbacks, in the data setting described above. Maybe it's how I'm setting the parameters? Here's the parameter set I use for initializing the XGBRegressor:
```
        "tree_method": "hist",
        "random_state": 2020,
        "max_depth": 13,
        "n_estimators": 500,
        "learning_rate": 0.05,
        "min_child_weight": 1,
        "colsample_bytree": 1,
        "subsample": 1,
```
and I'm using these parameter settings in both versions.

**Comment by trivialfis** [comment]
I will try to reproduce it. XGBoost doesn't have the CI resource to run benchmarks continuously, so this type of regression might need me to bisect the commits. Get back to this ASAP.

**Comment by dthiagarajan** [comment]
Awesome, thanks so much! Is there anything off the top of your head that you think might be reasonable for me to inspect on my end? e.g. is there any sort of logging I can enable from the C API to get more timings that might give a better sense of what specifically is slower during the training?

**Comment by trivialfis** [comment]
Nothing yet. I'm surprised by the result as well.

**Comment by dthiagarajan** [comment]
Is there any feature in the library that I can use to profile where the most time is being spent during the training for each setting (1.4.2 + DM, 1.7.4 + QDM)?

**Comment by trivialfis** [comment]
You can set the `verbosity` to 3 to see the log.

**Comment by trivialfis** [comment]
I can only reproduce the slowdown in evaluation with an additional validation matrix. My guess at the moment is that you have the training matrix duplicated for evaluation somehow. I'm not entirely sure of the exact cause. Looking forward to your profile result.

The "de-duplication" happens here: https://github.com/dmlc/xgboost/blob/191d0aa5cfac87cfc122ebbe8b14da4177309d13/python-package/xgboost/sklearn.py#L561 for sklearn interface.

**Comment by dthiagarajan** [comment]
When you say reproduce the slowdown, are you seeing similar discrepancies in time for each iteration? Like 10-20x time for each iteration?

I'm not passing any `eval_sets`, but let me step through the code locally and see what it's passing through.

**Comment by trivialfis** [comment]
No, I don't see such discrepancies between 1.4 and 1.7 using DM, nor between QDM and DM using 1.7.

**Comment by dthiagarajan** [comment]
Got it. And when you say with the additional validation matrix, you mean when passing something for `eval_sets`, right?

**Comment by trivialfis** [comment]
yes, when using `train_test_split` and passing the test dataset into `eval_sets`, there's a slowdown caused by evaluation on QDM. However, if only passing the training dataset, the performance is similar if not faster.  The slowdown doesn't occur to the training dataset because the prediction used for evaluation is calculated along with training.

**Comment by trivialfis** [comment]
Both are a few seconds per-iteration, but I'm using only half of the features (512) as yours due to the memory limit on my device.

My dataset is generated by `dask_ml.datasets.make_regression` for distributed training, and by `sklearn.datasets.make_regression` for single node.

**Comment by dthiagarajan** [comment]
I'm able to reproduce it being very slow with 512 features as well. Here's what I'm running:

```python3
class ProgressCallback(TrainingCallback):
    def __init__(self) -> None:
        super().__init__()

    def before_iteration(self, model, epoch, evals_log) -> bool:
        self.epoch_start_time = time.time()
        return False

    def after_iteration(self, model, epoch, evals_log) -> bool:
        logger.info(f"Epoch {epoch} finished in {time.time() - self.epoch_start_time:.3f} seconds.")
        return False

TOTAL_SAMPLES = 20170140
train_x, train_y = make_regression(n_samples=TOTAL_SAMPLES // 2, n_features=512)
progress_cb = ProgressCallback()
cbs = [progress_cb]

model = XGBRegressor(n_estimators=500, tree_method="hist", random_state=2020, max_depth=13, learning_rate=0.05, min_child_weight=1, colsample_bytree=1, subsample=1, verbosity=3)
model.fit(
    x=train_x,  # type: ignore[arg-type]
    y=train_y,  # type: ignore[arg-type]
    w=np.ones_like(train_y),
    callbacks=cbs,
)
```

and the output looks like:
```
[18:39:50] ======== Monitor (0): HostSketchContainer ========
[18:39:50] AllReduce: 1.89345s, 1 calls @ 1893446us

[18:39:50] MakeCuts: 1.89517s, 1 calls @ 1895170us

[18:39:50] ======== Monitor (1): HostSketchContainer ========
[18:39:50] AllReduce: 2.68894s, 1 calls @ 2688936us

[18:39:50] MakeCuts: 2.69069s, 1 calls @ 2690689us

[18:39:50] INFO: external/xgboost/src/gbm/gbtree.cc:179: Tree method is selected to be 'hist', which uses a single updater grow_quantile_histmaker.
...
[2023-04-18 18:41:20,459][INFO][train.py:32 after_iteration][Rank 0/2] Epoch 0 finished in 90.297 seconds.
[18:44:01] INFO: external/xgboost/src/gbm/gbtree.cc:179: Tree method is selected to be 'hist', which uses a single updater grow_quantile_histmaker.
[2023-04-18 18:42:41,555][INFO][train.py:32 after_iteration][Rank 0/2] Epoch 1 finished in 81.051 seconds.
[18:44:01] INFO: external/xgboost/src/gbm/gbtree.cc:179: Tree method is selected to be 'hist', which uses a single updater grow_quantile_histmaker.
[18:44:01] INFO: external/xgboost/src/gbm/gbtree.cc:179: Tree method is selected to be 'hist', which uses a single updater grow_quantile_histmaker.
[2023-04-18 18:44:01,682][INFO][train.py:32 after_iteration][Rank 0/2] Epoch 2 finished in 80.074 seconds.
[18:44:01] INFO: external/xgboost/src/gbm/gbtree.cc:179: Tree method is selected to be 'hist', which uses a single updater grow_quantile_histmaker.
[18:44:01] INFO: external/xgboost/src/gbm/gbtree.cc:179: Tree method is selected to be 'hist', which uses a single updater grow_quantile_histmaker.
[2023-04-18 18:45:20,883][INFO][train.py:32 after_iteration][Rank 0/2] Epoch 3 finished in 79.181 seconds.
[18:44:01] INFO: external/xgboost/src/gbm/gbtree.cc:179: Tree method is selected to be 'hist', which uses a single updater grow_quantile_histmaker.
[18:44:01] INFO: external/xgboost/src/gbm/gbtree.cc:179: Tree method is selected to be 'hist', which uses a single updater grow_quantile_histmaker.
[2023-04-18 18:46:39,311][INFO][train.py:32 after_iteration][Rank 0/2] Epoch 4 finished in 78.401 seconds.
[18:44:01] INFO: external/xgboost/src/gbm/gbtree.cc:179: Tree method is selected to be 'hist', which uses a single updater grow_quantile_histmaker.
[18:44:01] INFO: external/xgboost/src/gbm/gbtree.cc:179: Tree method is selected to be 'hist', which uses a single updater grow_quantile_histmaker.
[2023-04-18 18:47:57,020][INFO][train.py:32 after_iteration][Rank 0/2] Epoch 5 finished in 77.690 seconds.
[18:44:01] INFO: external/xgboost/src/gbm/gbtree.cc:179: Tree method is selected to be 'hist', which uses a single updater grow_quantile_histmaker.
[18:44:01] INFO: external/xgboost/src/gbm/gbtree.cc:179: Tree method is selected to be 'hist', which uses a single updater grow_quantile_histmaker.
```

**Comment by dthiagarajan** [comment]
Is there any chance this could be related to using `rabit` for distributed communication vs. Dask?

**Comment by trivialfis** [comment]
Internally, XGBoost always uses rabit for CPU communication. Dask is just there to setup the environment and does the preprocessing.

**Comment by trivialfis** [comment]
Could you please post the log at the end as well?

**Comment by dthiagarajan** [comment]
Ah, I cut off the run. Let me rerun it again and get the final log messages.

**Comment by trivialfis** [comment]
Hi, reading https://github.com/dmlc/xgboost/issues/9013#issuecomment-1513697799 , I think XGBoost `XGBRegressor` doesn't have a parameter called `w` in the `fit` function. The appropriate one is `sample_weight`, Let me test with your script.

**Comment by dthiagarajan** [comment]
Ah sorry, I had updated the script locally but not here. I updated in the comment above.

**Comment by trivialfis** [comment]
I ran the script on 1.4. and 1.7, the result seems to favor 1.7. Here is a snippet of the log, complete log is attached at the end.
## 1.4
```
[14:08:41] ======== Monitor: Learner ========
[14:08:41] Configure: 0s, 1 calls @ 0us

[14:08:41] EvalOneIter: 0.004776s, 500 calls @ 4776us

[14:08:41] GetGradient: 8.01906s, 500 calls @ 8019056us

[14:08:41] PredictRaw: 0.01103s, 500 calls @ 11030us

[14:08:41] UpdateOneIter: 1586.51s, 500 calls @ 1586514767us

[14:08:41] ======== Monitor: GBTree ========
```
## 1.7
```
[14:53:39] ======== Monitor (0): Learner ========
[14:53:39] Configure: 0.000147s, 1 calls @ 147us

[14:53:39] EvalOneIter: 0.006888s, 500 calls @ 6888us

[14:53:39] GetGradient: 4.61226s, 500 calls @ 4612258us

[14:53:39] PredictRaw: 0.010866s, 500 calls @ 10866us

[14:53:39] UpdateOneIter: 1144.43s, 500 calls @ 1144427722us
```

[log-1.4.txt](https://github.com/dmlc/xgboost/files/11283042/log-1.4.txt)
[log-1.7.txt](https://github.com/dmlc/xgboost/files/11283058/log-1.7.txt)

**Comment by trivialfis** [comment]
This might be a machine-dependent issue. CPU performance is not very portable, meaning the performance can change dramatically on different CPU models or on different RAM. (memory bandwidth is important to scaling) @hcho3 observed that XGBoost on some cloud platforms scales poorly with the number of threads (so poor that using distributed processes has better performance than using multiple threads)

**Comment by dthiagarajan** [comment]
I see, thanks for all the info. I realize the script I sent you is single-process, but even when I run single-process I see times slower than yours, which probably means something related to differences in our CPU model  / different RAM. The logs I sent you were for running with two workers distributed via `rabit`.

**Comment by trivialfis** [comment]
Let me try multi-node configuration later. Need some setup work for such tests. Do you observe slowdown on 1.7 compared to 1.4 on single node as well?

**Comment by dthiagarajan** [comment]
Interestingly, I don't see the slowdown on 1.7 compared to 1.4. I see an average of 9 seconds per iteration vs. 3-4 seconds per iteration between 1.4 and 1.7, respectively.

Is there a chance that the MPI communication is adding a large overhead for me? Is there a way I can measure how much time is specifically being used for distributed communication during the ExpandTree block?

**Comment by dthiagarajan** [comment]
One other thing - I also tried running distributed with two workers on a single node, so that the MPI could handle communication smartly and potentially eliminate any extra time added due to cross-node communication, but 
- I still see the same slowdown
- The time per iteration is similar in this setting (two workers on one node) in both versions as the time per iteration on multi-node (one worker per node, two nodes)

**Comment by trivialfis** [comment]
> Is there a chance that the MPI communication is adding a large overhead for me? Is there a way I can measure how much time is specifically being used for distributed communication during the ExpandTree block?

Unfortunately, we don't have the facility for this profiling. I will try to do some measuring by instrumenting the code. Good to narrow down the issue. Thank you for the investigation!

**Comment by dthiagarajan** [comment]
Hi @trivialfis, I saw your PR in #9096, and I'm trying to understand what the fix is in there - would you mind explaining?

Thanks for your help!

**Comment by trivialfis** [comment]
That's for the slowdown in evaluation, I haven't work on the distributed training yet.

**Comment by dthiagarajan** [comment]
Ah okay, no worries!

**Comment by dthiagarajan** [comment]
Hi @trivialfis, just wanted to follow up here. Did you have any chance to profile distributed training and see what might be causing the slowdown for me?

**Comment by trivialfis** [comment]
I can't reproduce the slowdown between 1.4 and 1.7 even in multi-node. I launched 12 workers and counted the number of allreduce calls (the most used communication primitive in xgboost), on 1.4 it's 709 calls and on 1.7 it's 584 calls when trained with 64 rounds. I don't have any new guess for the issue.

**Comment by trivialfis** [comment]
Unfortunately, there's no easy way to do that. However, if you want to do it in the hard way, here's the entry point for allreduce call:
https://github.com/dmlc/xgboost/blob/85988a3178b0059d714e12466c7446a3bf765470/rabit/src/allreduce_base.cc#L451

**Comment by dthiagarajan** [comment]
Hi @trivialfis, would you expect a performance regression when using Intel CPUs vs. AMD CPUs?

**Comment by trivialfis** [comment]
I don't know. Out of curiosity, have you bisected it using git?

**Comment by dthiagarajan** [comment]
Hi @trivialfis, we found a potential fix for the issue
* In version 1.4.2, we noticed the CPU usage saturated pretty consistently
* In version 1.7.4, we noticed the CPU usage did not saturate. However, when we explicitly set `n_jobs` to the number of cores on each node (where there's 1 worker per node in the distributed world), then we do see CPU usage saturate.

After setting `n_jobs` explicitly, I do see a similar result to you (a few seconds per iteration on both 1.4.2 and 1.7.4). I'm now scaling up to my original training problem and seeing if the time per iteration still remains the same with reduced memory usage.

Thanks for all your help! Will follow up once I have a result.

**Comment by trivialfis** [comment]
That's interesting! By default, XGBoost uses all available threads. One issue is that it has to take into account the scheduler of the container and OpenMP environment variables. If explicitly setting the number of threads fixes the issue for you, it would be great if you can share some more info about your environment so that we can improve the configuration logic.

**Comment by dthiagarajan** [comment]
Sounds good! I think there's a chance that for the 1.7.4 tests I've been running, the build for XGBoost that I've been using has not had MPI support, so let me also try building with MPI support, and running without `n_jobs` specified.

An unrelated question - I expose an interface to call prediction so that I can evaluate the model periodically. Is it possible/allowed to pass the `QuantileDMatrix` directly to prediction?

**Comment by trivialfis** [comment]
We haven't built Xgboost with MPI for a long time, it might be very broken. 1.4 is not enabled with MPI

Yes, you can pass it for prediction. Do note that test matrix must be constructed with training matrix as reference, otherwise the result is wrong. Also, the performance is likely to suffer significantly if you use a non-training matrix and without the recent performance fix in the master branch.

**Comment by dthiagarajan** [comment]
Got it. So suppose I do 
```
train_qdm = QuantileDMatrix(data=train_x, label=train_y, weight=train_w...)
model._Booster = train(params, train_qdm, ...) 
```
Would this be correct when calling evaluation?
```
test_qdm = QuantileDMatrix(data=test_x, label=test_y, weight=test_w, ref=train_qdm...)
train_predictions = model.get_booster().predict(data=train_qdm, validate_features=True)
test_predictions = model.get_booster().predict(data=test_qdm, validate_features=True)
```

**Comment by trivialfis** [comment]
Correct, might be slow on CPU. Actually that's the default for sklearn estimators like XGBRegressor.

**Comment by dthiagarajan** [comment]
Cool, I will try this! Thank you!

**Comment by dthiagarajan** [comment]
Wait sorry, wanted to clarify - which parts of that snippet might be slow on CPU? The QDM reation? Or the actual prediction call? Or both?

**Comment by trivialfis** [comment]
The actual prediction call. This PR https://github.com/dmlc/xgboost/pull/9096 mitigates the issue, but it's still sitting at the master branch.

**Comment by dthiagarajan** [comment]
Got it, thanks!

**Comment by dthiagarajan** [comment]
Is there a way that I can implement in-place prediction to also have staged prediction? I initially wanted to use the DMatrix interface to stage predictions, as I evaluate periodically, but I'm worried that might be incurring too expensive of a memory cost.

**Comment by trivialfis** [comment]
You can do some plumbing starting with: https://github.com/dmlc/xgboost/blob/a1fad72ab382fead287b4de13e79dc4ae4466893/demo/guide-python/individual_trees.py#L18

But for all these efforts, one might implement it in XGBoost. I haven't got the time to do it myself, but should be able to assist if anyone is interested in the feature.

**Comment by dthiagarajan** [comment]
Nice, thanks for the reference! Will take a look.

**Comment by dthiagarajan** [comment]
I will close this issue now, as the training times are similar for me. Thank you for your help!
