### ISSUE TITLE
Regression in pyspark fit time for columnar input + spark-rapids + gpu

### ISSUE THREAD

**Issue by eordentlich** [dmlc/xgboost#9016]
In some recent benchmarking with spark-rapids I noticed slower performance than past recorded runs with early pre-release pyspark api versions for a particular parquet format data set.  In looking back through past results, the slow down seemed to actually have happened a while back.   After building and profiling a couple of these past versions, I think I narrowed it down to this change: https://github.com/dmlc/xgboost/pull/8284/files#diff-e02cb86420040cfdaa950d0f5b5d1d50149a7df9c03d13e23b2c7c4f9426d762R249
It seems converting  other non-feature columns (like labels) to Numpy here (vs simply leaving them as pd.Series) can lead to significant slow downs (nearly 50% longer time for subset of mortgage data set) when `feature_cols is not None`, when running with spark-rapids gpu accelerated data loading + gpu_hist, reading from columnar parquet format.

@wbo4958 Can you take a look?  (cc. @trivialfis )

**Comment by wbo4958** [comment]
Hi @eordentlich, Thx for your detailed finding. I will take a look at it today. Thx
