### ISSUE TITLE
XGBoost 2.0 Model Format and Backwards Compatibility

### ISSUE THREAD

**Issue by nviets** [dmlc/xgboost#9017]
Hello! Will the xgboost model format and backwards compatibility change when 2.0 is released? I've been following your tracker, but didn't see compatibility covered. Sorry if this has been address elsewhere.

https://github.com/dmlc/xgboost/projects/2

**Comment by trivialfis** [comment]
Hi, the roadmap is here https://github.com/dmlc/xgboost/issues/7547
