### ISSUE TITLE
Different proba between 0.90 and 1.6.2

### ISSUE THREAD

**Issue by asnashafiq** [dmlc/xgboost#9019]
1. I have an sklearn xgboost classifier trained in v 0.90. 
2. I used [convert_090to100.py](https://github.com/dmlc/xgboost/blob/v1.0.0/doc/python/convert_090to100.py) to save the model in binary format in the 0.90 env
3. I loaded the binary file into a classifier in the 1.6.2 env using the code below
```python
xgb = xgboost.XGBClassifier()
xgb.load_model('<binary file>.bin')
```

For the same input, the result of `predict_proba()` is different between the 2 xgboost versions. The probabilities are not the same, although the shape of the result is correct.

How can I get the same probabilities in the newer version of xgboost using the saved model?

**Comment by hcho3** [comment]
Is it possible to share your model file? It will be helpful in diagnosing the cause of prediction mismatch.
