### ISSUE TITLE
What is the maximum number of folds in cross-validation?  (xgb.cv function in R)

### ISSUE THREAD

**Issue by yuanyuanli66** [dmlc/xgboost#902]
I am trying to do Leave-one-out cross-validation using xgb.cv function by setting nfold to the sample size (over 2000). However, it crashes R program. My objective function is 'multi:softprob'. I have also tried sample size -1, -2, .... -10. Sometimes, I get "Error in folds[[i]] : subscript out of bounds". 

After I set nthread=1, R software no longer crashes.  I am always getting "Error in folds[[i]] : subscript out of bounds" error, unless I set nfolds into a small number (i.e. 50). 

Would you please shed some lights on how the cross-validation works in the package? Thanks!

**Comment by khotilov** [comment]
Make sure to set stratified=FALSE

The xgb.cv design is not really optimal for LOO kind of CV, as it creates as many xgb.Booster's as there are folds, and then runs boosting iterations for all of them. Memory consumption might become an issue. For LOO CV, I would personally just run a simple four-line loop to train and predict in each fold.
