### ISSUE TITLE
[CI] Run CI for 32-bit arch

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#9035]
Related: #8964

Idea: Use Docker to run i386 image. TVM is using this approach: https://ci.tlcpack.ai/blue/organizations/jenkins/tvm-i386/detail/unity-merge-backup-04-13/1/pipeline

**Comment by barracuda156** [comment]
@hcho3 BTW, is it possible to set up CI for `ppc` on Linux?

**Comment by hcho3** [comment]
Sorry, I am afraid not. I don't have ready access to ppc.

**Comment by barracuda156** [comment]
Qemu can emulate `ppc`, which certainly works for Linux: https://blog.r-project.org/2020/05/29/testing-r-on-emulated-platforms
(I have no idea if that can be used with CI though.)

**Comment by trivialfis** [comment]
I think cran has dropped 32 bit test

**Comment by barracuda156** [comment]
> I think cran has dropped 32 bit test

CRAN is useless in this sense, I was referring to GH CI.

**Comment by trivialfis** [comment]
This basically removes any remaining motivation for us to maintain a 32 bit compatible code base.

**Comment by barracuda156** [comment]
@trivialfis If I understand correctly, 32-bit CI is available: https://github.com/kokkos/kokkos/commit/e5490e1e11ece175ec16588c5a3062ece2fe1b33#diff-5ba24b49194839f21a65bdf8a8dc5649df41e9c086b69c560c2ed3a788920061
This is not `ppc`, but `i386` is good enough for 32-bit testing.

**Comment by hcho3** [comment]
Thanks for the pointer. I'll get back to setting up i386 CI eventually. For now I have other priorities.

**Comment by hcho3** [comment]
After careful discussion with core developers, we decided that we will not set up a 32-bit CI. Furthermore, apart from pull request #8964 (which we will try to merge), we will not make further effort to support 32-bit systems, including i386 and ppc. Now that CRAN no longer requires a passing test with 32-bit systems, we no longer have motivation for maintaining 32-bit compatible code base.

**Comment by barracuda156** [comment]
I see. Well, hope, that PR you have referred to above gets merged, and at least on purpose 32-bit support is not removed.

Once #8964 is merged, I will see if I can improve tests results on my end (we can test both ppc and i386).
