### ISSUE TITLE
installation error on windows: WindowsError: [Error 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by egallego** [dmlc/xgboost#908]
Hi,

I am installing xgboost on windows (Windows 7-64bit) following the instructions given in: http://stackoverflow.com/questions/33749735/how-to-install-xgboost-package-in-python-windows-platform/35480673#35480673 and http://xgboost.readthedocs.org/en/latest/build.html#building-on-windows.

It does the process correctly, generating the "xgboost.exe" file on the xgboost folder and the  "libxgboost.dll" in the xgboost\lib folder. Python installation also presents no errors during the process. 

However, when I try to import on python I get the following error:

```
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import xgboost
  File "C:\Python27\lib\site-packages\xgboost-0.4-py2.7.egg\xgboost\__init__.py", line 11, in <module>
    from .core import DMatrix, Booster
  File "C:\Python27\lib\site-packages\xgboost-0.4-py2.7.egg\xgboost\core.py", line 83, in <module>
    _LIB = _load_lib()
  File "C:\Python27\lib\site-packages\xgboost-0.4-py2.7.egg\xgboost\core.py", line 77, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])
  File "C:\Python27\lib\ctypes\__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 193] %1 is not a valid Win32 application
```
I am using MinGW-64 as compiler and Cygwin shell to define the istructions. Any suggestions?

**Comment by ShashkovS** [comment]
The same for me on windows 10 x64, git x64 and mingw x64.
Compilation runs without errors.

**Comment by tqchen** [comment]
hmm, seems this also happens for @thirdwing  when doing mxnet installations. Let us wait and see if we can progress on https://github.com/dmlc/xgboost/pull/893 to get a MSVC build back

**Comment by Towhid1** [comment]
same problem like @egallego . I used mingw-64 and git bash . Is there any solution for windows user. :(

**Comment by tommycon** [comment]
I'm having the same issues, the installation seems to have run fine. Everything is where it should be however I'm getting "WindowsError: [Error 193] %1 is not a valid Win32 application"

**Comment by linjinjin123** [comment]
@egallego @ShashkovS @tqchen @Towhid1 @tommycon 
Hi, there. I have the same issues and I solve it by install the python 64bit version. Now I can successfully import xgboost. You can try this way. =)

**Comment by tqchen** [comment]
msvc is added #1327

**Comment by danelee2601** [comment]
@linjinjin123  Thanks a lot haha you made my day!!
