### ISSUE TITLE
Inefficient Casting Grad and Hess to c_float for Custom Obj in Python API

### ISSUE THREAD

**Issue by bridgream** [dmlc/xgboost#9089]
I recently notice a performance issue in my project, and I realize it relates to these two lines of code, which cast grad and hess returned by custom obj to c_float (float32): https://github.com/dmlc/xgboost/blob/v1.7.5/python-package/xgboost/core.py#L1950-L1951

The problem is that, if grad and hess are not np.float32, casting using `c_array` is very inefficient (at least on my platform) compared with numpy `astype`:

```python
import ctypes

import numpy as np
from xgboost.core import c_array

data = np.ones(10_000_000, dtype="float64")

%timeit data.astype("float32")
34.5 ms ± 370 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
%timeit c_array(ctypes.c_float, data)
1.78 s ± 42.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

On the other hand, if the grad and hess are already np.float32, then casting using `c_array` is decently efficient (although still slower than `astype` with `copy=False`): 

```python
data = data.astype("float32")
%timeit data.astype("float32")
34 ms ± 2.28 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
%timeit data.astype("float32", copy=False)
194 ns ± 0.609 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
%timeit c_array(ctypes.c_float, data)
3.04 µs ± 44.1 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
```

I'm thinking of two solutions:
1. Since the grad and hess are expected to 1-D numpy arrays according to [documentation](https://xgboost.readthedocs.io/en/stable/tutorials/custom_metric_obj.html), maybe we can just call `astype` with `copy=False`. 
2. Raise a PerformanceWarning if grad and hess are not float32.

**Comment by trivialfis** [comment]
Thank you for raising the issue. We are likely to change some underlying API functions for custom objectives for https://github.com/dmlc/xgboost/issues/9043 . Will link this issue and check performance.
