### ISSUE TITLE
[CI] ELF load command address/offset not properly aligned

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#9092]
https://buildkite.com/xgboost/xgboost-ci/builds/2318#0187b326-d760-4d4d-9dc0-15a31faf3dcd

```
    raise XGBoostError(
E   xgboost.core.XGBoostError:
E   XGBoost Library (libxgboost.so) could not be loaded.
E   Likely causes:
E     * OpenMP runtime is not installed
E       - vcomp140.dll or libgomp-1.dll for Windows
E       - libomp.dylib for Mac OSX
E       - libgomp.so for Linux and other UNIX-like OSes
E       Mac OSX users: Run `brew install libomp` to install OpenMP runtime.
E
E     * You are running 32-bit Python on a 64-bit OS
E
E   Error message(s): ['libgomp-a34b3233.so.1.0.0: ELF load command address/offset not properly aligned']
```

**Comment by trivialfis** [comment]
seems to be flaky? Not reproducible anymore.

**Comment by hcho3** [comment]
Yeah I couldn't reproduce it on my machine either.

**Comment by hcho3** [comment]
I found the cause. Patchelf 0.18.0, which came out 2 days ago, is causing `ELF load command` error. The cause is yet unknown.
* https://github.com/mayeut/patchelf-pypi/issues/87
* https://github.com/NixOS/patchelf/issues/492

The Docker image `quay.io/pypa/manylinux2014_x86_64` is re-built once in every few days, and the image produced on April 24 contained the buggy Patchelf 0.18.0.

The bug is not active now, as the latest  `quay.io/pypa/manylinux2014_x86_64` image uses Patchelf 0.17.2, which is not affected by the bug.

**Comment by hcho3** [comment]
Closing for now. I will keep monitoring https://github.com/NixOS/patchelf/issues/492 and  mayeut/patchelf-pypi#87 closely for the next few days.
