### ISSUE TITLE
Calculate importance gain in y prediction

### ISSUE THREAD

**Issue by Zt-Wan** [dmlc/xgboost#9095]
Is there any way I can calculate importance gain on the testset ?
I notice that in the source code, xgboost use enumeratesplit & updateenumerate to calculate gain & find optimal split at the smae time. 
What model.get_score() does is just summing up those gains. But what should I do if I want to calculate the gain on the testset?

**Comment by trivialfis** [comment]
Use predict function from booster to calculate SHAP value.

**Comment by Zt-Wan** [comment]
shap value shows how the feature affect y_hat, but what i actually want is how the feature affect the loss : y -  y_hat
Like booster.get_score(importance_type='gain') , its gain means how the feature decrease average loss,

**Comment by trivialfis** [comment]
Feel free to reopen if there are further questions.
