### ISSUE TITLE
How to call predict at best iteration when using num_parallel_tree > 1

### ISSUE THREAD

**Issue by mordoobadi** [dmlc/xgboost#910]
I am trying to use an xgboost model with num_parallel_tree greater than 1 but I am not sure how to choose the ntreelimit to get predictions for the best iteration. 

I normally use this to calculate preditions for the training data:
train_preds <- predict(model, dtrain, ntreelimit=model$bestInd)

I then calculate the training error based on the predictions, but the calculated training error is much larger than model$bestScore that I get from the model when I use num_parallel_tree > 1. 

How should I choose the ntreelimit when calling predict?

**Comment by catena** [comment]
This might work:
`best_ntreelimit = model$bestInd * num_parallel_tree`

**Comment by mordoobadi** [comment]
Thanks. I will give it a try.

**Comment by tyokota** [comment]
I have the same issue in R. I tried doing what was suggested above, then it then did not choose the best iteration. Is it model$bestInd * num_parallel_tree? The Python read me suggests using 'bst.best_ntree_limit'. Does this exist in R somewhere?
