### ISSUE TITLE
Explicitly indicate categorical feature name in Scikit-Learn interface for XGBoost

### ISSUE THREAD

**Issue by JoaquinAmatRodrigo** [dmlc/xgboost#9109]
Hello everyone,

I have a question regarding the treatment of categorical features in my data. I was wondering if there is a way to explicitly indicate a list of feature names that should be treated as categorical in the model training process.

Currently, I am aware of the enable_categorical=True argument, which allows for automatic detection of categorical features based on pandas dtypes. However, the categorical encoding in pandas may not be consistent across different datasets, which could cause issues when deploying the model in production.

I would greatly appreciate any insights or suggestions on how to explicitly indicate categorical features to ensure consistency in the model's encoding process.

Thank you very much for your help!

**Comment by trivialfis** [comment]
There's a feature types parameter that can be used with array instead of dataframe.

**Comment by JoaquinAmatRodrigo** [comment]
I overlooked it. Thank you very much @trivialfis!
