### ISSUE TITLE
Monotonic Constraints can not be used inside an Scikit-Learn Pipeline without additional processing

### ISSUE THREAD

**Issue by edgBR** [dmlc/xgboost#9113]
Dear colleagues,

I have the following dataframe:

| feat1 | feat2 | feat3 | target |
|-------|-------|-------|--------|
| 0.1   | 0     | 1     | 0.01   |
| 0.4   | 0     | 2     | 0.02   |
| 1.1   | 1     | 3     | 0.05   |
| 1.2   | 1     | 4     | 0.1    |

I have the following scikit learn pipeline:

```python
numeric_transformer = Pipeline(
        steps=[
            ("imputer", SimpleImputer(strategy="constant",
             fill_value=-1, add_indicator=True)),
            # originally: ("imputer", SimpleImputer(strategy="mean")),
            ("scaler", StandardScaler()),
            ("variance_selector", VarianceThreshold(threshold=0.03))
        ]
    )

logging.info("Defining categorical transformer: one-hot encoding")
categorical_transformer = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="constant", fill_value="missing")),
        ("onehot", OneHotEncoder(handle_unknown="ignore"))]
)

preprocessor = ColumnTransformer(
    transformers=[
        ("numeric_transf", numeric_transformer, numerical_features),
        ("categorical_transf", categorical_transformer, one_hot_features)],
    remainder='drop')


```

And the following configuration for XGBoost:

```python

mono_pos_values = [1] * len(args.keys_pos_contraints)
        dic_mono_constraints = dict(
             zip(args.keys_pos_contraints, mono_pos_values))

param_grid_clf = {
                'n_estimators': args.clf_n_estimators,
                'max_depth': args.clf_max_depth,
                'max_bin': args.clf_max_bin,
                'learning_rate': args.clf_learning_rate,
                'gamma': args.clf_gamma,
                'colsample_bytree': args.clf_colsample_bytree,
                'colsample_bylevel': args.clf_colsample_bylevel,
                'reg_alpha': args.clf_reg_alpha,
                'reg_lambda': args.clf_reg_lambda,
                'subsample': args.clf_subsample,
                'random_state': args.random_seed,
                'tree_method': 'hist',  # cpu: 'hist' | gpu: 'gpu_hist'
                'objective': 'binary:logistic',
                'eval_metric': 'logloss',
                'monotone_constraints': dic_mono_constraints
                #non-indicated features will be considered as 0.
                # For clf, I expect to apply this to the predict_proba function
            }
```
When creating my pipeline as:

```python
        model = xgb.XGBClassifier(**param_grid_clf)
        clf = Pipeline(
            [
                # now preprocessor is an independent pipeline
                ('preprocessor', preprocessor),
                ('estimator', model)
            ]
        )
```

I get the following error:

`ValueError: Constrained features are not a subset of training data feature names`

The only way we have found to fix this is to split our scikit learn pipeline in 2 and use the column name after the preprocessor.fit_transform() which is ['numeric_transf__tgt_period']

However this seems suboptional as we end up ditching the purpose of having an scikit learn pipeline.

Would it be possible for someone to look into this?

**Comment by edgBR** [comment]
Okay but then this loses completely the point of using the scikit learn API. Is there any other work around?

**Comment by edgBR** [comment]
Hi @trivialfis ,

Thanks for the support.

Let me try to explain myself better as I think I have not done a good job before:

1. The pipeline I have has a set of input features that I predefine.
2. Some of this features might be dropped by the variance selector. In future it might be another method.
3. The monotonic constraint is applied to a feature that its always there (tgt_period). Tgt period never gets dropped. However after it goes through the column transformer of the preprocessor step this feature becomes "name_of_numeric_transformer_feature". In my case numeric_trans_tgt_period.
4. If I use the original feature name (tgt_month) in the motonic constraint parameter it does not work. If I use the output name from the numeric transformer "numeric_transf__tgt_period" it also does not work. If I split my pipeline in 2 steps (one for the column transformer and another for the model) it works. The input to the model then is a pandas data frame with columns coming from the Column transformer: preprocessor.get_features_names_out().
5. If I understand the documentation about monotonic constraints correctly.  If I refer to the monotonic constraint with a dictionary where I set up the position of the column. This can make the model to put the constraint in a different feature as the column order for my feature changes (because some features are dropped by the variance selector).

Is my statement in 5 correct or did I misunderstood?

**Comment by trivialfis** [comment]
>  If I refer to the monotonic constraint with a dictionary where I set up the position of the column

I think you meant tuple? If so,

> This can make the model to put the constraint in a different feature as the column order for my feature changes (because some features are dropped by the variance selector).

Yes.

> If I use the output name from the numeric transformer "numeric_transf__tgt_period" it also does not work. 

Could you please check why it doesn't work? Any chance there's an unexpected change of name? Here's a simple example I extracted from the tests:
``` python
import numpy as np
import pandas as pd
import xgboost as xgb


def make_mc():
    number_of_dpoints = 1000
    x1_positively_correlated_with_y = np.random.random(size=number_of_dpoints)
    x2_negatively_correlated_with_y = np.random.random(size=number_of_dpoints)

    x = np.column_stack(
        (x1_positively_correlated_with_y, x2_negatively_correlated_with_y)
    )
    zs = np.random.normal(loc=0.0, scale=0.01, size=number_of_dpoints)
    y = (
        5 * x1_positively_correlated_with_y
        + np.sin(10 * np.pi * x1_positively_correlated_with_y)
        - 5 * x2_negatively_correlated_with_y
        - np.cos(10 * np.pi * x2_negatively_correlated_with_y)
        + zs
    )
    return x, y


params = {
    "tree_method": "hist",
    "grow_policy": "lossguide",
    "monotone_constraints": {"feature_0": 1, "feature_1": -1},
}

reg = xgb.XGBRegressor(**params)
x, y = make_mc()

feature_names = ["feature_0", "feature_1"]
xdf = pd.DataFrame(x, columns=feature_names)
reg.fit(xdf, y)
```

**Comment by trivialfis** [comment]
As a side note, some sklearn estimators/transformers return numpy array instead of pandas dataframe, in which case, the feature name would be loss.

**Comment by edgBR** [comment]
Hi @trivialfis,

That example works, and it is actually precisely what I am doing:

```python
clf_preprocessor = clf['preprocessor']
clf_preprocessor.fit(data_train)

data_train_processed = pd.DataFrame(clf_preprocessor.transform(data_train),
                                            columns=list(
                                            clf_preprocessor.get_feature_names_out()))

clf_model = clf['estimator'].fit(data_train_processed, target_train)
```

However this seems a bit inconvenient, and as mentioned before, it ditch the purpose of wrapping xgboost into a pipeline. In principle if a set up scikit learn to return pandas output this should be fixed, but by doing that I will have to set sparse=False in one hot encoder which will cause the matrix size to explode.

You mentioned before about writing a wrapper, would you be so kind to give more additional indications on this?

**Comment by trivialfis** [comment]
In order for XGBoost to select/constrain the features based on their names, one needs to first ensure XGBoost knows what are the names of the features right? With an array or CSR input, this is not possible since it doesn't contain names for the columns. Within the pipeline, XGBoost doesn't know which column is `numeric_transf__tgt_period`.

The categorical tree in xgboost can help remove the use of the one-hot encoder, see https://xgboost.readthedocs.io/en/stable/tutorials/categorical.html for details. In this case, you still need to make sure the input to XGBoost is stored in pandas. Similar to the column name issue, array and CSR don't have the type of the columns (categorical or numerical).

**Comment by trivialfis** [comment]
Feel free to reopen if there's further info.

**Comment by swademb** [comment]
Sometimes we really want to use sparse output with, say, one-hot encoding - but this results in the loss of the names of all features and then we can't set `monotone_constraints` by name.

A workaround is to use the _tuple_ specification of the monotone constraints instead. But we'll need to get the order of the columns prior to reaching the classifier first, e.g. something like:

```python
preprocessor = ColumnTransformer(
    # preprocessing with selectors, transformers, etc...
)

xgb_pipeline = make_pipeline(
    preprocessor,
    xgb.XGBClassifier(
        objective='binary:logistic',
        # whatever other arguments we are using here
        # but don't set monotone_constraints yet
    )
)

# get the column names after pre-processing but before classifier
X_tform = xgb_pipeline['columntransformer'].fit_transform(X)
tform_features = xgb_pipeline['columntransformer'].get_feature_names_out()

# now set monotone constraints by finding the names in the pre-processed data
# and constructing a tuple
is_incr = np.isin(tform_features, ['length', 'height']).astype(int)
xgb_pipeline['xgbclassifier'].monotone_constraints = tuple(is_incr.tolist())

# Now we can fit!
```

One caveat is that if the pre-processed column names change, e.g. when doing cross-validation and a category disappears (or appears); then we're back to failing.

**Comment by trivialfis** [comment]
XGBoost natively supports categorical features, including the use of OHE.
