### ISSUE TITLE
An error with horizontal federated learning demo

### ISSUE THREAD

**Issue by Jonathan-Doe** [dmlc/xgboost#9116]
Trying to run a horizontal federated learning demo on my local machine. During the last step: `submit_job horizontal-xgboost` i receive an error message: 

> Error: App horizontal-xgboost in deploy_map doesn't exist for job horizontal-xgboost

Am I doing something wrong? All the previous steps seemed to work in the correct way.

**Comment by rongou** [comment]
Ah I think I broke it when I moved it under the `horizontal` directory. Sending a fix.
