### ISSUE TITLE
Why negative gain exists ?

### ISSUE THREAD

**Issue by Zt-Wan** [dmlc/xgboost#9143]
I think all the gain in one tree should be non-negative because if it's negative, the xgboost would not split it. But when I run get_score by each tree in a model, I find some gain may be negative. How should I interpret this case?

like the following picture, when I get the gain in first tree, the gain for f37 is 0.28, but when I get the gain for f37 in the first 100 trees, it becomes 0.135

![image2023-5-8_11-2-40](https://user-images.githubusercontent.com/57814768/236731432-a325bcb9-7185-446f-a904-b5916793e099.png)

**Comment by trivialfis** [comment]
The `gain` is normalized by the number of splits created by this feature. To prevent the normalization, use `total_gain` instead.

**Comment by Zt-Wan** [comment]
Does the number of splits means the value I get from get_score(importance_type==weight) ?

**Comment by trivialfis** [comment]
yes.
