### ISSUE TITLE
xgb.cv gives Error in strsplit(score, “\\+|:”)[[1]][[2]] : subscript out of bounds

### ISSUE THREAD

**Issue by hack-r** [dmlc/xgboost#917]
This occurred with both the CRAN and current drat versions of xgboost.

http://stackoverflow.com/questions/35817921/xgb-cv-from-rs-xgboost-package-gives-error-in-strsplitscore-12

This model ran fine until I tried to use the early.stop.round argument.

If you'd like to reproduce this the data is available from Kaggle Santander competition.

```
pacman::p_load(Matrix, xgboost)

set.seed(1234)

train <- read.csv("train.csv")
test  <- read.csv("test.csv")

##### Removing IDs
train$ID <- NULL
test.id <- test$ID
test$ID <- NULL

##### Extracting TARGET
train.y <- train$TARGET
train$TARGET <- NULL

##### 0 count per line
count0 <- function(x) {
  return( sum(x == 0) )
}
train$n0 <- apply(train, 1, FUN=count0)
test$n0 <- apply(test, 1, FUN=count0)

##### Removing constant features
cat("\n## Removing the constants features.\n")
for (f in names(train)) {
  if (length(unique(train[[f]])) == 1) {
    cat(f, "is constant in train. We delete it.\n")
    train[[f]] <- NULL
    test[[f]] <- NULL
  }
}

##### Removing identical features
features_pair <- combn(names(train), 2, simplify = F)
toRemove <- c()
for(pair in features_pair) {
  f1 <- pair[1]
  f2 <- pair[2]

  if (!(f1 %in% toRemove) & !(f2 %in% toRemove)) {
    if (all(train[[f1]] == train[[f2]])) {
      cat(f1, "and", f2, "are equals.\n")
      toRemove <- c(toRemove, f2)
    }
  }
}

feature.names <- setdiff(names(train), toRemove)

train <- train[, feature.names]
test <- test[, feature.names]

train$TARGET <- train.y


train <- sparse.model.matrix(TARGET ~ ., data = train)

dtrain <- xgb.DMatrix(data=train, label=train.y)
watchlist <- list(train=dtrain)

param <- list(  objective           = "binary:logistic", 
                booster             = "gbtree",
                #eval_metric         = "auc",
                eta                 = 0.02,
                max_depth           = 6,
                subsample           = 0.9,
                colsample_bytree    = 0.85
)

clf <- xgb.cv(      params              = param,  
                    nfold               = 3,
                    data                = dtrain, 
                    nrounds             = 500, 
                    verbose             = 1,
                    watchlist           = watchlist,
                    maximize            = T,
                    early.stop.round    = 5,
                    metrics             = "auc"
)

[0] train-auc:0.818707+0.002202 test-auc:0.806059+0.005250
Error in strsplit(score, "\\+|:")[[1]][[2]] : subscript out of bounds
```

**Comment by hack-r** [comment]
I figured out that it's the combination of metrics and early.stop.round that doesn't work. This is probably a bug, but it's easy to work around.

**Comment by AbhishekSinghVerma** [comment]
@hack-r It will be great help, if you put the solution here as well. I am getting same problem and I see you have removed question from SO as well.

**Comment by hack-r** [comment]
Hi AbhishekSinghVerma ,

Sure, I will see if I can go back and figure out what my solution to 
this was and post it. I think there must have been a downvote on SO that 
made me delete it. I pissed off some high-reputation users in the R tag 
by always answering questions quickly for several months and they 
started downvoting all of most posts and harassing me on there. Drama.

Jason/
/

**Comment by AbhishekSinghVerma** [comment]
For the future recipient of this error. To get rid of this error in R; you need to make sure segregating parameters `param` and cross validation function `xgb.cv()` parameters neatly.

`param1 <- list("objective" = "reg:linear",
                       "eval_metric" = "rmse",
                       "max_depth" = 15,
                       "eta" = 0.03,
                       "gamma" = 0,
                       "subsample" = currentSubsampleRate,
                      "colsample_bytree" = currentColsampleRate,
                       "min_child_weight" = current_min_child_weight,
                       "alpha" = 0.1)

         xgboostModelCV <- xgb.cv(data=train_matrix, label=output_train, nrounds = 500, nfold = 5,
                                 verbose = F, early.stop.round=5, prediction=T, param=param1, missing = NaN)`

If you move alpha from param to CV like trying: 
`xgboostModelCV <- xgb.cv(data=train_matrix, label=output_train, nrounds = 500, nfold = 5,
                                 verbose = F, early.stop.round=5, prediction=T, param=param1, missing = NaN, "alpha"=0.1)`

will result in this error.
