### ISSUE TITLE
[python-package] Unable to extract contributions from SparkXGBClassifier

### ISSUE THREAD

**Issue by CarlaFernandez** [dmlc/xgboost#9175]
**What I'm doing**
I create a SparkXGBClassifier and set the parameter `pred_contrib_col="contrib"` to hopefully be able to extract feature contributions during the `transform` step.

**Actual results**
The contributions column is not being returned. 

**Expected results**
A new column `contrib` should appear in the transformed dataset, showing feature contributions and the bias term.

**Reproducible example**:
I'm using the titanic dataset from [kaggle](https://www.kaggle.com/competitions/titanic/data?select=train.csv).
```python
from xgboost.spark import SparkXGBClassifier
from pyspark.ml.feature import VectorAssembler, StringIndexer, OneHotEncoder
from pyspark.ml import Pipeline
from pyspark.sql.types import *

schema = StructType(
    [
        StructField("PassengerId", DoubleType()),
        StructField("Survived", DoubleType()),
        StructField("Pclass", DoubleType()),
        StructField("Name", StringType()),
        StructField("Sex", StringType()),
        StructField("Age", DoubleType()),
        StructField("SibSp", DoubleType()),
        StructField("Parch", DoubleType()),
        StructField("Ticket", StringType()),
        StructField("Fare", DoubleType()),
        StructField("Cabin", StringType()),
        StructField("Embarked", StringType()),
    ]
)

titanic = (
    spark.read.option("header", "true")
    .schema(schema)
    .csv("titanic.csv")
    .na.fill(0)
    .na.fill("Nulo")
)

indexers = [
    StringIndexer(inputCol=c, outputCol=c + "_index", handleInvalid="keep")
    for c in ["Sex", "Embarked"]
]
ohe = OneHotEncoder(
    inputCols=[indexer.getOutputCol() for indexer in indexers],
    outputCols=[f"{indexer.getInputCol()}_onehot" for indexer in indexers],
)

vectorAssembler = (
    VectorAssembler()
    .setInputCols(["Sex_onehot", "Embarked_onehot", "Pclass", "Age", "Fare"])
    .setOutputCol("features")
)

xgboost = SparkXGBClassifier(
    pred_contrib_col="contrib",
    features_col="features",
    label_col="Survived",
    missing=0.0,
    prediction_col="prediction",
    seed=42,
)

pipeline = Pipeline(stages=[*indexers, ohe, vectorAssembler, xgboost])

fitted_pipeline = pipeline.fit(titanic)
# here the following warning is thrown, I don't know if it's important:
#         UserWarning: Loading a native XGBoost model with Scikit-Learn interface.
#         warnings.warn("Loading a native XGBoost model with Scikit-Learn interface.")

fitted_pipeline.transform(titanic).toPandas()
```

These are the new columns that appear after the transform:
![image](https://github.com/dmlc/xgboost/assets/9136877/7bb28ac6-794f-4418-b7af-a809462abf55)

As you can see, there is not trace of the "contrib" column.

**Environment**
XGBoost version 1.7.5 on Python 3.10, Windows 10.

Any help is much appreciated

**Comment by wbo4958** [comment]
@CarlaFernandez, It Seems 1.7.5 has not cherry-picked the pred_contrib feature, can you try the latest master branch?

But you raised a good issue that xgboost spark doesn't support pred_contrib_col, why it didn't throw an exception? I will file a PR to fix it.

**Comment by CarlaFernandez** [comment]
Sure, I'll try it next monday!
Regarding the support of pred_contrib_col, after your PR will we be able to
use this feature? Or will it just raise an exception? It's an important
feature for us. Thank you so much!

**Comment by wbo4958** [comment]
@CarlaFernandez, The latest xgboost has already supported pred_contrib_col, so you can use it directly.

**Comment by CarlaFernandez** [comment]
Hello again @wbo4958 , sorry for the late response and thanks for looking into this!

I've been able to install the latest version of xgboost from the master branch, and indeed I can now obtain feature contributions by setting the `pred_contrib_col` parameter. 

I observe the output contributions after transforming are encapsulated in double arrays. This is an example of the schema returned by the transform:
```
root
 |-- PassengerId: double (nullable = false)
 |-- contributions: array (nullable = true)
 |    |-- element: array (containsNull = true)
 |    |    |-- element: double (containsNull = true)
```
Is this expected behaviour? I've used the Scala API before and the contributions where directly an Array(Double), even for the multiclass case.

Regarding multiclass, I also have a question. Currently, I'm not able to set `objective="multi:softprob"` for a SparkXGBClassifier, since apparently it's not yet supported. Do you have any roadmap for when this feature will be available?

Thank you!

**Comment by wbo4958** [comment]
@CarlaFernandez Yes, it's expected. You can refer to https://xgboost.readthedocs.io/en/stable/prediction.html

**Comment by wbo4958** [comment]
Once I had a PR to refactor the jvm package about the prediction, for some reason, it's been closed. I think, it's the time to bring it back.

**Comment by CarlaFernandez** [comment]
Thank you @wbo4958 , I don't know how I missed that documentation page before 🤯. I will refer to it for future development using SparkXGBClassifier.
For my part, all doubts are resolved, I'm closing this issue since I think the refactor of the JVM package should be in an issue/PR of its own.
