### ISSUE TITLE
[pyspark] Do we need to re-consider the pyspark variables naming?

### ISSUE THREAD

**Issue by wbo4958** [dmlc/xgboost#9177]
When databricks contributed the xgboost pyspark solution to the xgboost community, we made the decision to use the lowercase with words separated by underscore naming to unify the parameters. But we still can't unify all the parameters, 

for example, featureCol/labelCol ... are camel naming, while base_margin_col/qid_col/pred_contrib_col  ... are the different naming.

So I file this issue to suggest moving the parameters only for "xgboost.pyspark wrapper" back to camel naming to follow spark way. And as to the xgboost parameters, let's just keep them in the xgboost way.

This's going to be a breaking change if we decide to support that. @WeichenXu123 @trivialfis any thoughts on this?

**Comment by wbo4958** [comment]
My bad. xgboost pyspark has supported all the camel naming.

**Comment by WeichenXu123** [comment]
@wbo4958 

I think currently it only supports `xx_xx_xx` style naming for all params. See https://github.com/dmlc/xgboost/blob/6274fba0a534cf1dec73725a6ee421a22e288b38/python-package/xgboost/spark/core.py#L581

I suggest to avoid breaking change.
