### ISSUE TITLE
R multiple quantiles bug

### ISSUE THREAD

**Issue by rspadim** [dmlc/xgboost#9179]
When using quantile regression in R with a list of quantiles like c(0.1,0.5,0.9) it just return the first quantile (0.1 in my example) prediction. 
this report is to check a bug with multiple quantiles regression
Thansk

**Comment by trivialfis** [comment]
Hi, the list input is not yet supported for R.

**Comment by trivialfis** [comment]
Prefer https://github.com/dmlc/xgboost/issues/1433 and https://github.com/dmlc/xgboost/issues/9475 instead.
