### ISSUE TITLE
Floating point exception after DMatrix.save_binary() with GPUs

### ISSUE THREAD

**Issue by sjhermanek** [dmlc/xgboost#9195]
Due to some peculiarity of my setup and the dataset I'm using I observed that if I first write out a DMatrix using `.save_binary()` and later on load it back, I'm getting some nice memory savings (i.e. use different machines for the DMatrix construction and training tasks  -- a high memory one versus one with many cores).

The interesting part is that this works well for CPU based training, but I'm intermittently running into an error with GPU training:
- Generate DMatrix on machine A (with CPUs), then load back and train on machine B with CPUs - this works.
- Generate DMatrix on machine A, then load back and train on machine B with GPU - this does not work.
- Generate DMatrix on machine B, then load back and train on the same machine B with GPU - this does not work if it's a new Python run. It does work if it's within the same run.
 
For cases where it does not work I'm getting a "Floating point exception." and the program aborts without any other error message. 

Do you have any guidance on how to resolve this?

**Comment by trivialfis** [comment]
I'm not sure the cause yet. But have you considered using `QuantileDMatrix` for GPU training?

**Comment by sjhermanek** [comment]
I have, but this doesn't let me cache it to disk because it's not SimpleDMatrix (probably should have a warning about what makes such a SimpleDMatrix).

I can share a sanitized code example tomorrow but I think you get the gist.

**Comment by trivialfis** [comment]
Indeed. But it can help save a significant amount of memory, especially if your input is on CPU (like numpy/pandas). In addition, it's used by default in the sklearn interface.

**Comment by trivialfis** [comment]
I can't reproduce this with 2.0. Feel free to reopen if the issue persists.

> I can share a sanitized code example tomorrow but I think you get the gist.

This would be great!
