### ISSUE TITLE
Python sklearn interface: early_stopping_rounds documentation is misleading

### ISSUE THREAD

**Issue by mfeurer** [dmlc/xgboost#9198]
I think the documentation of `early_stopping_rounds` in the sklearn interface is contradictory. [Here](https://github.com/dmlc/xgboost/blob/720a8c3273a844679e1edf11bd87297331f19d58/python-package/xgboost/sklearn.py#L384) it states that:
> The method returns the model from the last iteration, not the best one, use a callback y:class:`xgboost.callback.EarlyStopping` if returning the best model is preferred.

while [later on in the predict method](https://github.com/dmlc/xgboost/blob/720a8c3273a844679e1edf11bd87297331f19d58/python-package/xgboost/sklearn.py#L1122) it states:
> Predict with `X`.  If the model is trained with early stopping, then :py:attr:`best_iteration` is used automatically.  For tree models, when data is on GPU, like cupy array or cuDF dataframe and `predictor` is not specified, the prediction is run on GPU automatically, otherwise it will run on CPU.

Now I don't know which one is correct, and it would be great if this could be unified.

**Comment by trivialfis** [comment]
Hi, thank you for raising the issue, do you have suggested edits?

Here's my attempt to clarify the doc. The early stopping returns the full boosting tree models with all the trees, but the prediction method by default uses only the optimal number of them. A user can use all the trees if he wishes by specifying the iteration range parameter. In contrast, if the best model is returned instead of the full model, then a user can only use the best number of trees according to early stop.

**Comment by mfeurer** [comment]
Hey, would this clarification be for the constructor or for the fit method? However, after sleeping over this issue for a few days and also reading your answer, I guess the documentation is not as misleading as when I first read it. Nevertheless, here's my suggestion:

```python
The method returns the model from the last iteration.

If returning the best model is preferred use early stopping via a callback (y:class:`xgboost.callback.EarlyStopping`).
```
and 
```python
Predict with X. If the model is trained with early stopping, then :py:attr:best_iteration is used automatically, otherwise, the model from the last iteration is used. 

For tree models, when data is on GPU, like cupy array or cuDF dataframe and predictor is not specified, the prediction is run on GPU automatically, otherwise it will run on CPU.
```

**Comment by trivialfis** [comment]
Thank you for the suggestions! I opened a PR https://github.com/dmlc/xgboost/pull/9304 , would you like to take a look?
