### ISSUE TITLE
The build status badges show outdated information

### ISSUE THREAD

**Issue by dotbg** [dmlc/xgboost#9225]
Please, replace travis CI and Jenking build status badges with the buildkite ones. 
Refer to the [documentation for details](https://buildkite.com/docs/integrations/build-status-badges)
Unfortunately, the `pipeline's status badge` is located `on the Pipeline Settings page` so I can not create a pull request myself.

Just two files should be changed:
README.md:
```
[![Build Status](https://github.com/dmlc/dmlc-core/workflows/continuous%20build/badge.svg)](https://github.com/dmlc/dmlc-core/actions)
```
and 
jvm-packages/README.md
```
[![Build Status](https://travis-ci.org/dmlc/xgboost.svg?branch=master)](https://travis-ci.org/dmlc/xgboost)
```

**Comment by trivialfis** [comment]
Thank you for raising the issue @dotbg ! Do you have some bandwidth for moving some of the installation documents into `doc/install.rst` or `doc/jvm/java_intro.rst` (or anywhere you see fit)? I think we should remove the outdated readme file under the jvm-package directory, or at least reduce it down to a single link to our documentation page.

**Comment by hcho3** [comment]
I filed #9232 to replace the outdated build badges.

**Comment by dotbg** [comment]
this issue can be closed. @trivialfis I think rearranging the docs has to become another issue. let's do that separately.
