### ISSUE TITLE
libxgboost.so is almost 300MB large on x86_64 platform

### ISSUE THREAD

**Issue by aronbrand** [dmlc/xgboost#9269]
The size of the libxgboost.so file in the x86_64 platform is huge, around 300MB. In comparison entire xgboost .whl package in the macOS platform, is only 1.6MB in size. 

This large size is causing significant problems, especially on embedded platforms.

xgboost was obtained from: https://pypi.org/project/xgboost/#files

**Comment by trivialfis** [comment]
Partly caused by restriction by pypi where we need to statically link everything, partly caused by the need to enable support for different CUDA compute capability.

**Comment by trivialfis** [comment]
You might need a different distribution method other than pypi. I'm not sure if the conda-forge build has CPU only build (@hcho3 ), you might also find https://github.com/NixOS/nixpkgs to be interesting.

**Comment by trivialfis** [comment]
Just confirmed the conda CPU build doesn't contain any GPU code. The version is a little bit behind though. Will look into keeping it up-to-date.

**Comment by couzhei** [comment]
`conda install -c conda-forge py-xgboost-cpu` will do the job if you happen to be using conda.
