### ISSUE TITLE
How to use `validate_parameters`?

### ISSUE THREAD

**Issue by moygit** [dmlc/xgboost#9273]
What does `validate_parameters` actually do? Using [this example](https://github.com/dmlc/xgboost/blob/master/demo/guide-python/spark_estimator_examples.py) from the Python demos I've tried adding a nonsense parameter with `validate_parameters` set to `True` and then to `False`, and the results are identical in the two cases: I don't get a warning in either case and I get an entry in `arbitrary_params_dict` in both cases. Ideally xgboost should error if `validate_parameters` is True and it gets a nonsense param.

**Comment by trivialfis** [comment]
There should be a warning message similar to:
```
[01:19:29] WARNING: /home/jiamingy/workspace/xgboost_dev/xgboost/src/learner.cc:753: 
Parameters: { "foo" } are not used.
```

**Comment by moygit** [comment]
Weird. I get the warning when I run it on my laptop, but when I run it on Databricks it seems to swallow the warning. Thanks @trivialfis . I'll go ahead and close.
