### ISSUE TITLE
porting to visual studio and MS-MPI v7 

### ISSUE THREAD

**Issue by giuliohome** [dmlc/xgboost#928]
I've noticed that the new release has MinGW support on Windows.
Should I try to build XGBoost with Visual Studio, is it correct to use the new [Microsoft MPI v7](https://www.microsoft.com/en-us/download/details.aspx?id=49926)?

Am I supposed to change the syntax like that (after a fork)?
```c++
...
  MPI_Allreduce(MPI_IN_PLACE, sendrecvbuf, count, *dtype, *op, MPI_COMM_WORLD);
  //MPI::COMM_WORLD.Allreduce(MPI_IN_PLACE, sendrecvbuf, count, *dtype, *op);
...
MPI_Type_commit(dtype); //  dtype->Commit();
...
// transform enum to MPI data type
inline MPI_Datatype GetType(mpi::DataType dtype) {
//inline MPI::Datatype GetType(mpi::DataType dtype) {
  using namespace mpi;
  switch (dtype) {
    case kChar: return MPI_CHAR; //MPI::CHAR;
    case kUChar: return MPI_BYTE; //MPI::BYTE;
    case kInt: return MPI_INT; //MPI::INT;
...
MPI_Type_contiguous(type_nbytes / sizeof(long), MPI_LONG, dtype);
// *dtype = MPI::LONG.Create_contiguous(type_nbytes / sizeof(long));  // NOLINT(*)
...
  /*! \brief get rank of current node */
  virtual int GetRank(void) const {
	  int ret_rank;
	  MPI_Comm_rank(MPI_COMM_WORLD, &ret_rank);
	  return ret_rank; // MPI::COMM_WORLD.Get_rank();
  }
```
Am I missing a quick configuration setting to switch from C to C++ syntax for the MPI lib in MSVC?

**Comment by anhvoms** [comment]
I've posted the answer on the official forum of the MS-MPI team, but cross-posting in case others come here looking for the answer:

The MPI C++ binding is deprecated as of MPI 3.0 (please refer to http://www.mpi-forum.org/docs/docs.html for the latest MPI standard document). The MPI C++ binding is no longer supported by MS-MPI. I'm sorry for any inconvenience this might cause. For a quick and simple explanation of why the C++ binding was removed from the MPI standard, please refer to this blog post http://blogs.cisco.com/performance/the-mpi-c-bindings-what-happened-and-why

The C binding should continue working within a C++ program. Let us know if you have compilation problems

Thanks

Anh

**Comment by tqchen** [comment]
If you like, you can contribute an update to https://github.com/dmlc/rabit to use the MPI C API instead.

**Comment by tqchen** [comment]
Another solution is simply build the rabit library.

If you are only looking for a single machine version though. MPI is not needed, simply build with the dummy library, rabit_empty will do

**Comment by tqchen** [comment]
@giuliohome The MSVC build is removed mainly because we want to switch to CMake for easier maintainace. See https://github.com/dmlc/xgboost/issues/746 
 
There is a proposal PR here https://github.com/dmlc/xgboost/pull/893

**Comment by giuliohome** [comment]
Thank you very much for the clarification!
