### ISSUE TITLE
jvm was crashed without any log when i use xgboost4j:0.9 to load a model that trained by spark3?

### ISSUE THREAD

**Issue by YpandaGit** [dmlc/xgboost#9296]
i don't know why , it was ok when the model was trained by spark2. Can anybody help?

**Comment by wbo4958** [comment]
xgboost4j:09 was built on spark 2.x, we can't guarantee it can work with spark3. If you'd like to run xgboost on spark3. please update the xgboost4j dep to the latest.

**Comment by trivialfis** [comment]
XGBoost binary model is not forward compatible.
