### ISSUE TITLE
Unable to install this Github master branch as library to Databricks environment

### ISSUE THREAD

**Issue by Yutong-Gao506** [dmlc/xgboost#9297]
Hi,

I was trying to use `pred_contrib_col` parameter of `SparkXGBRegressor`, and I found this issue here mentioning the similar problem https://github.com/dmlc/xgboost/issues/9175

It seems that this issue has been fixed in the current master branch, but not for the latest PyPi release (1.7.5). I tried to install `python-package` of this github repo as a library to my Databricks environment, but the `CMake` version is not compatible.

This feature is very important to us because we want to calculate the SHAP value for this model and the current SHAP library doesn't support `SparkXGBRegressor`. 

Can you please help with this issue? Appreciate any guidance on installation.

Thanks!!!

**Comment by hcho3** [comment]
Have you tried installing the nightly version? https://xgboost.readthedocs.io/en/stable/install.html#id1

**Comment by Yutong-Gao506** [comment]
Thank you for your reply!
To install the latest version, should I download the [xgboost-2.0.0.dev0+c2f0486d376df882d7aac2096be1dcaf9edb7188-py3-none-manylinux2014_x86_64.whl](https://s3-us-west-2.amazonaws.com/xgboost-nightly-builds/master/xgboost-2.0.0.dev0%2Bc2f0486d376df882d7aac2096be1dcaf9edb7188-py3-none-manylinux2014_x86_64.whl) and replace the previous pypi xgboost? Thanks!

**Comment by hcho3** [comment]
Yes, that's the right one.

**Comment by Yutong-Gao506** [comment]
Thanks, but using this whl file, I cannot import SparkXGBRegressor.
Can you please help with this issue?

**Comment by jaceklaskowski** [comment]
Hey @Yutong-Gao506 👋

I honestly don't know where to ask these questions but since they're based on this one I'll go ahead and ask them here. Sorry for hijacking this thread.

How did you "I tried to install python-package of this github repo as a library to my Databricks environment"? What were the commands? Did you do them in a python notebook?

**Comment by jaceklaskowski** [comment]
@hcho3 How to know which package to use from the nightly builds at https://s3-us-west-2.amazonaws.com/xgboost-nightly-builds/list.html?prefix=master/. How are the system identifiers collected for the file names of these nightly build packages?

**Comment by hcho3** [comment]
@jaceklaskowski You should look for the git commit hash. You can get it by running command `git log`.
