### ISSUE TITLE
XGBOOST TRAINING WITH M2 MAX GPU

### ISSUE THREAD

**Issue by eacarebebek** [dmlc/xgboost#9314]
Hello. I have Mac PRO with M2 MAX Chipset. I want to use XGBoost Regressor with GPU. I am getting "XGBoost version not compiled with GPU support" error. I could not solve NVIDIA Cuda Toolkit problem. How can i enable my gpu for training?

**Comment by trivialfis** [comment]
I don't think it has a nvidia GPU?

**Comment by eacarebebek** [comment]
I searched little bit and i think its causing by cuda support. If i am wrong sorry :)

**Comment by trivialfis** [comment]
We don't support apple GPU at the moment.
