### ISSUE TITLE
code change

### ISSUE THREAD

**Issue by celestinoxp** [dmlc/xgboost#9322]
I recently ran into a bug and lost a lot of time figuring out which features were involved.

the problem is here, because it only alerts that there are features with the same names, but it doesn't say which ones (in my case it was necessary to know that)

xgboost\core.py", line 1155, in feature_names
     `raise ValueError('feature_names must be unique')`
ValueError: feature_names must be unique

I propose that this code be changed to
 ```
duplicates = [name for name in feature_names if feature_names.count(name) > 1] #new line
raise ValueError('feature_names must be unique. Duplicates found: {}'.format(duplicates)) #line changed
```

Thus, it is possible to know which features have the same names, and avoid wasting time...

more details: https://github.com/pycaret/pycaret/issues/3615

I'm using Windows 11
Anaconda
python 3.10
xgboost 1.7.6

**Comment by trivialfis** [comment]
Thank you for the suggestion! Would you like to open a PR for the improved error message?

**Comment by celestinoxp** [comment]
> Thank you for the suggestion! Would you like to open a PR for the improved error message?

no thanks, if you find this post useful, can you update the code?

**Comment by trivialfis** [comment]
Got it. I will update the feature validation code.
