### ISSUE TITLE
min_child_weight is not used for Tweedie objective function

### ISSUE THREAD

**Issue by yellowzijian** [dmlc/xgboost#9324]
Description:
When using R to perform Tweedie regression, I have encountered an issue regarding the `min_child_weight` parameter. After specifying this parameter in the list of parameters passed to the `xgb.train` or `xgboost` function, it seems that the value provided for `min_child_weight` is not utilized during the training process. This behavior appears to be specific to the R implementation, as I believe the parameter is successfully utilized in a similar procedure using Python.

WARNING from R:
[10:14:45] WARNING: src/learner.cc:767: 
Parameters: { "mini_child_weight" } are not used.

**Comment by houlk8503** [comment]
The warning raises because you have a spelling error. The correct parameter name should be 'min_child_weight', but what you write down the in R script, as reflected in your warning message, is 'mini_child_weight' (it starts with 'mini', not  'min').

**Comment by trivialfis** [comment]
@houlk8503 Thank you for pointing that out.
