### ISSUE TITLE
Not contains `libxgboost4j.so` in the xgboost4j-gpu_2.12-2.0.0-SNAPSHOT.jar

### ISSUE THREAD

**Issue by NvTimLiu** [dmlc/xgboost#9332]
Not contains `libxgboost4j.so` in the xgboost4j-gpu_2.12-2.0.0-SNAPSHOT.jar 
- `libxgboost4j.so` was in the GPU version of xgboost4j-`gpu`_2.12 jar weeks ago, (since 20230606 or so)
-  `libxgboost4j.so` exists in the `CPU` version of xgboost4j_2.12 jar

Download xgboost4j-gpu_2.12-2.0.0-SNAPSHOT.jar jar from [SNAPSHOT repo]
(https://s3-us-west-2.amazonaws.com/xgboost-maven-repo/snapshot) as below

```
mvn -B dependency:get -DremoteRepositories=https://s3-us-west-2.amazonaws.com/xgboost-maven-repo/snapshot  -Dtransitive=false -Dartifact=ml.dmlc:xgboost4j-gpu_2.12:2.0.0-SNAPSHOT:jar

ls

-rw-rw-r--  1    306M Jun  3 21:36 xgboost4j-gpu_2.12-2.0.0-20230603.213634-496.jar
-rw-rw-r--  1    101K Jun  6 03:06 xgboost4j-gpu_2.12-2.0.0-20230606.030622-501.jar
-rw-rw-r--  1    101K Jun 26 03:21 xgboost4j-gpu_2.12-2.0.0-SNAPSHOT.jar
```

XGBoost train on `GPU` will fail as below:

```
java.io.FileNotFoundException: File /lib/linux/x86_64/libxgboost4j.so was not found inside JAR.
at ml.dmlc.xgboost4j.java.NativeLibLoader.createTempFileFromResource(NativeLibLoader.java:285)
at ml.dmlc.xgboost4j.java.NativeLibLoader.loadLibraryFromJar(NativeLibLoader.java:228)
at ml.dmlc.xgboost4j.java.NativeLibLoader.initXGBoost(NativeLibLoader.java:168)
at ml.dmlc.xgboost4j.java.XGBoostJNI.<clinit>(XGBoostJNI.java:34)
```

**Comment by NvTimLiu** [comment]
@wbo4958 please help to take a look, thanks

**Comment by wbo4958** [comment]
Seem the xgboost gpu jars has some issues from 06/05 https://s3-us-west-2.amazonaws.com/xgboost-maven-repo/list.html?prefix=snapshot/ml/dmlc/xgboost4j-gpu_2.12/2.0.0-SNAPSHOT/ 

@hcho3 could you help to check it?

**Comment by wbo4958** [comment]
@dotbg Would you help to check this issue?

**Comment by dotbg** [comment]
I'll have a look.
