### ISSUE TITLE
Large datasets in R / Nvidia H100s cause unexpected memory overflow error

### ISSUE THREAD

**Issue by wwang-walleye** [dmlc/xgboost#9334]
We are encountering an issue training on H100s in R that occurs only after the dataset exceeds a certain degree of size. The interesting part is the stack trace ... clearly the data set we're building is nowhere near the 80GB of VRAM in the GPU, but it attempts to allocate some obscene amount of memory that alludes to some kind of integer overflow in the memory allocation.

I'll note that this does _not_ happen when I use an identical environment with A100 GPUs instead.

I'm at a loss for how to debug this further, so any help would be greatly appreciated!

- OS: Rocky 9.1
- Driver Version: 530.30.02
- CUDA Version: 12.1
- R Version: 4.2.3
- XGBoost Version: 1.7.6, also reproduced on 2.0 nightly build

Reproducible code:

```
require(xgboost)

params <- list(
    tree_method="gpu_hist",
    eta=0.01,
    max_depth=4
)

# The below code runs fine with n=2e6, but fails with n=3e6
n <- 3e6
X <- matrix(rnorm(1000 * n), ncol=1000)
y <- rnorm(n)
wt <- runif(n)
dmat <- xgb.DMatrix(X, label=y, weight=wt)
bst <- xgb.train(params, dmat, nround=100, watchlist=list(train=dmat), verbose=TRUE, print_every_n=10)
```

Resulting Stacktrace:

```Error in xgb.iter.update(bst$handle, dtrain, iteration - 1, obj) : 
  [18:33:59] ../src/tree/updater_gpu_hist.cu:802: Exception in gpu_hist: [18:33:59] ../src/c_api/../data/../common/device_helpers.cuh:431: Memory allocation error on worker 0: Caching allocator
- Free memory: 47579791360
- Requested memory: 18446744073698093311

Stack trace:
  [bt] (0) ~/rlib/xgboost/libs/xgboost.so(+0x58c8a3) [0x7fe50c06c8a3]
  [bt] (1) ~/rlib/xgboost/libs/xgboost.so(dh::detail::ThrowOOMError(std::string const&, unsigned long)+0x381) [0x7fe50c071db1]
  [bt] (2) ~/rlib/xgboost/libs/xgboost.so(+0x59b984) [0x7fe50c07b984]
  [bt] (3) ~/rlib/xgboost/libs/xgboost.so(thrust::detail::normal_iterator<thrust::device_ptr<float> > thrust::cuda_cub::inclusive_scan_by_key<thrust::detail::execute_with_allocator<dh::detail::XGBCachingDeviceAllocatorImpl<char>&, thrust::cuda_cub::execute_on_stream_base>, thrust::detail::normal_iterator<thrust::device_ptr<xgboost::

Enter a frame number, or 0 to exit   

1: xgb.train(params, dmat, nround = 100, watchlist = list(train = dmat), verbose = TRUE, print_every_n = 10)
2: xgb.iter.update(bst$handle, dtrain, iteration - 1, obj)

```

**Comment by trivialfis** [comment]
Thank you for raising the issue, let me debug this next week.

**Comment by trivialfis** [comment]
Interesting, I couldn't reproduce it in other setups either. Will try to access a h100 instance.

**Comment by trivialfis** [comment]
Reproduced on h100. Will debug it.

**Comment by trivialfis** [comment]
`thrust::inclusive_scan_by_key` is overflowing due to size larger than INT_MAX.
