### ISSUE TITLE
can you add robust train functions?

### ISSUE THREAD

**Issue by showkeyjar** [dmlc/xgboost#9339]
I suggest a new feature that can robust train xgboost model.

it offten crashed caused by out of memory, when I train xgb model use big size data.

so, I have to adjust tree model size(hyperparameters) or data size as common tips.

this process wastes a lot of time, and it's the most error I'll deal with daily.

I wish xgb framework can add a function call robust_train:

it can estimate memory usage, and check if memory is enough, before next boost

if memory is not enough and loss is reach threshold, then save model, otherwise continue next boost.

or your guys guide me how to achieve this function?

**Comment by trivialfis** [comment]
That really depends on how you train your model and where the memory is being used. For instance, if you are doing hyper-parameter tuning, the `train_test_split` from sklearn might be used as part of the cross validation process, which might create a new copy of data. If you are doing it in multiple threads, then you will have number of copies equal to the number of threads.

The feature you mentioned is similar to checkpointing, which can be achieved through `xgboost.callback.TrainingCheckPoint`. You can define your own policy on when to checkpoint based on you specific use case.

**Comment by showkeyjar** [comment]
thanks, I'll try TrainingCheckPoint policy.

**Comment by trivialfis** [comment]
If you are using the `hist/gpu_hist` tree method, the `XGBRegressor/Classifier/Ranker` should use much lesser memory than normal.
