### ISSUE TITLE
xgboost.dask.train (cpu) high memory usage when increasing max_depth

### ISSUE THREAD

**Issue by ncclementi** [dmlc/xgboost#9342]
We are trying to understand memory usage for xgboost.dask.train and what is the expected behavior as max_depth increases.  

Running a LocalCluster in my laptop mac m1 - 16GB memory
dask version = 2023.6.0
xgboost version = 1.7.6

Notes: I tried to run max_depth 20 and it killed my laptop. 

Reproducer (fabricated example, to showcase problem)

```python
import dask
import xgboost
from dask.distributed import Client
from distributed.diagnostics import MemorySampler

client = Client()
ms = MemorySampler()

dtypes = {}

for i in range(40):
    dtypes["f-%d" % i] = float
    
for i in range(40):
    dtypes["i-%d" % i] = int
    
df = dask.datasets.timeseries(
    start="2000-01-01",
    end="2001-01-01",
    dtypes=dtypes,
    partition_freq="4d",
    freq="10s",
)

df = df.persist()  # this is a 1.9GiB dataset 
X = df.drop("i-1", axis=1)
y = df["i-1"]

d_train = xgboost.dask.DaskDMatrix(
    None, X, y, enable_categorical=True
)


#this will give the curve corresponding to 18 but you can run it with different values and get the plot below
with ms.sample("md_18"):

    model = xgboost.dask.train(
        None,
    {
            "max_depth": 18, 
        },
        d_train,
        evals=[(d_train, "train")],
    )
    
ms.plot(align=True, grid=True)   
```

![md_6-12-18](https://github.com/dmlc/xgboost/assets/7526622/eb8d718d-92ec-438d-8494-21671138bf61)

We noticed that if we include `num_parallel_trees` things are different, but it's not clear to us why, note that the cases for 18 and 20 were taking too long to finish, so we cut them off (they were over 10 min on the 7th iteration)

```python
    model = xgboost.dask.train(
        None,
    {
            "max_depth": 18, 
            "num_parallel_tree": 100, 
        },
        d_train,
        evals=[(d_train, "train")],
    )
```

`num_parallel_trees = 100`
![md_12-18-20_npt100](https://github.com/dmlc/xgboost/assets/7526622/615ea1b8-2f8e-41f7-9583-66daeb596603)

**Comment by trivialfis** [comment]
Hi, thank you for raising the issue. The size of the tree grows exponentially with the depth, along with all the cache. I can submit a patch to limit the size of the cache when the tree grows too deep. But the computation performance will degrade once we reach the limit.

**Comment by mrocklin** [comment]
My guess is that *some* limit makes sense, the question probably then becomes "what is a sensible limit?" Some ideas that come to mind:

1.  An arbitrary value that seems quite large.  I don't know this space well, but maybe 1-10 GBs?
2. The size of the data that you're training on
3. Half the memory of the machine that you're on
4. Something else?

I'm curious, what do you all use for GPUs?

**Comment by trivialfis** [comment]
Thank you for the suggestions! I'm thinking about the size of the dataset as well. Seems to be a reasonably choice.

The GPU implementation is just a hard-coded limit: https://github.com/dmlc/xgboost/blob/f4798718c7729ed351471231bb13e0d4862551af/src/tree/updater_gpu_hist.cu#L75 .

**Comment by trivialfis** [comment]
I'm working on it, among other things.

>  Will 2.0 support it and when we can try it in master version

I don't have an eta. We need to redesign the cache for the parallel histogram builder. Should be possible for 2.0.

**Comment by WeichenXu123** [comment]
@trivialfis 

In our test, we found GPU memory consumption is much higher than CPU mode training, with the same config,

e..g, for depth=12 in our customer's case,

We found each training worker it consume about 2GB memory (CPU mode training), but if using GPU training, it consumes **GPU memory** about 16GB,

Is it because of https://github.com/dmlc/xgboost/issues/9342#issuecomment-1610445686 ?

**Comment by trivialfis** [comment]
I can't be sure. This has to be analyzed case by case.

**Comment by trivialfis** [comment]
> In our test, we found GPU memory 

@WeichenXu123 Would you like to share you test configuration?

**Comment by WeichenXu123** [comment]
```
{'featuresCol': 'features',
 'labelCol': 'rz_flag',
 'missing': -999.0,
 'num_workers': 2,
 'use_gpu': True,
 'tree_method': 'gpu_hist',
 'random_state': 0,
 'verbose': False,
 'colsample_bytree': 0.5960816259940614,
 'gamma': 0.21803116689213928,
 'learning_rate': 0.1219825540164903,
 'max_depth': 12,
 'min_child_weight': 1,
 'n_estimators': 1000,
 'reg_alpha': 1.2691477824047968,
 'reg_lambda': 0.10557685766746369,
 'subsample': 0.7126118163775655,
 'arbitrary_params_dict': {}}
```

**Comment by trivialfis** [comment]
Could you please share the shape and the sparsity of the data as well?

**Comment by WeichenXu123** [comment]
@trivialfis 
The dataset has about 11 million records, and feature number is 86 , the dataset is very dense, very few missing values, thank you!

**Comment by trivialfis** [comment]
@WeichenXu123 Are you using the rapids plugin (whether the spark dataframe is backed by cudf)?

**Comment by trivialfis** [comment]
A back-of-envelop calculation, assuming 4-byte per element with `float32`, each worker has `1e8 / 2` number of samples:
``` python
1e8//2 * 86 * 4 / 1024 / 1024 / 1024
```
That's 16GB of memory. There is room for improvement, but not a lot. I thought about using a more compressed representation for dense data, but I don't think it's going to reduce it down to 2GB of memory.

> We found each training worker it consume about 2GB memory (CPU mode training),

CPU is more aggressive when compressing dense data, which might be a contributing factor.

**Comment by trivialfis** [comment]
The memory spike is at data construction, subsequent memory usage seems to be reasonable.

![Screenshot from 2023-07-13 16-57-43](https://github.com/dmlc/xgboost/assets/16746409/092470b0-d89a-4e09-bc9a-0ba0cd937271)

**Comment by WeichenXu123** [comment]
@trivialfis 

> Hi, thank you for raising the issue. The size of the tree grows exponentially with the depth, along with all the cache. I can submit a patch to limit the size of the cache when the tree grows too deep. But the computation performance will degrade once we reach the limit.

How much performance decreasement once reaching limit ?

**Comment by trivialfis** [comment]
> How much performance decreasement once reaching limit ?

For CPU, I don't know. Will have to profile it after having a prototype. I'm not specialized in performance optimization.

GPU is already bounded. Nothing needs to be done in there.

**Comment by WeichenXu123** [comment]
@trivialfis 

> GPU is already bounded. Nothing needs to be done in there.

How much performance decreasement once reaching limit in GPU mode?


https://github.com/dmlc/xgboost/blob/f4798718c7729ed351471231bb13e0d4862551af/src/tree/updater_gpu_hist.cu#L75

Is this the GPU bound you mentioned ? ** Can we make it configurable **  ? The bound value is not memory usage size right ? Can we make it to be a config that measured by GPU memory usage limit ? It will be easier to use .

**Comment by trivialfis** [comment]
> Why this PR is related to this ticket ? How the overflow affect memory usage ?

That was an incorrect reference, GitHub doesn't remove the reference even if it's changed.

> Is this the GPU bound you mentioned ? Can we make it configurable ? The bound value is not memory usage size right ? Can we make it to be a config that measured by GPU memory usage limit ? It will be easier to use .

Maybe at some point in the future with a different feature request. I usually avoid exposing internal configurations that are not strictly related to machine learning.
