### ISSUE TITLE
Estimated `base_score` unavailable as attribute (Python)

### ISSUE THREAD

**Issue by BenModulusLabs** [dmlc/xgboost#9347]
If the base score isn't specified at model creation time, then it is estimated.  However, the estimated value isn't available after training:

```python
import numpy as np
import pandas as pd

n_trees = 10
n_samples = 1000
n_float_features = 4

X = 100 * np.random.rand(n_samples, n_float_features)
y = np.random.rand(len(X))

from xgboost import XGBRegressor
model = XGBRegressor(n_estimators=n_trees, max_depth=8, learning_rate=1)
model.fit(X, y)
preds = model.predict(X)
booster = model.get_booster()

assert model.base_score is None
```

The assertion above passes.

However, when summing the predictions of individual trees and comparing to the results of `model.predict()`, it is clear that the `base_value` is non-zero (and hence of importance):

```python
from xgboost import DMatrix
X_dmatrix = DMatrix(X)
individual_preds = [tree.predict(X_dmatrix) for tree in booster]

(sum(individual_preds) - model.predict(X))
```

Outputs:
```
array([4.5      , 4.5      , 4.5      , 4.5      , 4.5      , 4.5      ,
       4.5000005, 4.5      , 4.5      , 4.5000005, 4.5      , 4.5      ,
       4.5      , 4.5      , 4.5000005, 4.5000005, 4.4999995, 4.4999995,
       4.5      , 4.4999995, 4.5      , 4.5000005, 4.5      , 4.5000005,
       4.5      , 4.5000005, 4.5000005, 4.5      , 4.5      , 4.5      ,
...
```

There is a [discussion on this topic](https://discuss.xgboost.ai/t/how-to-get-base-score-from-trained-booster/3192).

Thanks for your help or clarification!

**Comment by trivialfis** [comment]
Hi, the feature was recently added and is not yet available for release branches. In addition, the `model.base_score` will continue to be `None` as discussed in https://github.com/dmlc/xgboost/pull/8634. In summary, the Python attribute `base_score` is a user parameter according to the sklearn interface and should not be changed by the library itself. To see the configured base score, you either have to use the `save_config` like what's shown in the discussion or save the model as JSON and find the value.
