### ISSUE TITLE
[feature request] Handling special values, infinity

### ISSUE THREAD

**Issue by lcrmorin** [dmlc/xgboost#9357]
It is not exactly a problem that would be encountered with a modern data-stack and good data quality management practices. However, I've found myself having to handle the problem of having multiple special values different times recently.

What I mean by this: over the year and given some outdated tools as a constraint, the data engineers in my team used different missing values to deal with different problems. This includes, but is not limited to: some strings like 'missing', 'infinity', 'eps', some sentinel values like 999, 9999, and things closer to infinity like 1e12 or what would count as np.Inf. 

It would be nice if xgboost would better handle those different kinds of special values. Currently the solutions require specific handling, imputation to more sentinel values, use of np.nantonum to remove infinity values ... etc.

I was thinking about the following for tree methods:

- some way to specify the special values (maybe as a parameter as in the [optbinning](http://gnpalencia.org/optbinning/binning_process.html) package)
- allow +/- np.Inf by default
- handling of special values internally; missing values could be handled as a category, and +/- infinity could be handled as high numbers for splits (infinity > x always True wathever is x). 
- This might generally require or imply the handling of mixed data types

Let me know if this make sense / could be prioritized.

**Comment by trivialfis** [comment]
What's the advantage of using a machine learning library over a data manipulation library like pandas to process the data?

**Comment by lcrmorin** [comment]
I've found it to complexify the data pipeline by putting it in two places (the old data pipeline and the python one). Currently my way to go is to input all missing values to nan, build additional 0/1 columns to flag each of the special values and set infinite values to +/- 1e12. 

It has some impact in terms of learning (multiplication of the columns, so less likely to select the main columns when randomising columns) - I am not sure about the final performance though - explainability (now we need to agregate multiple explanation columns).

**Comment by lcrmorin** [comment]
Well, some of the special values are difficult to avoid.  In the long run, it might be generally cleaner to have the ML library handle mixed type than complexify the data eng. pipeline / the explainability code and possibly the client facing interface.

**Comment by trivialfis** [comment]
XGBoost can handle arbitrary missing values, and the algorithm can choose tree split with missing in mind. The data pipeline just needs to unify the representation of missing, most common way of doing that is encoding it as NaN. For other value, you can use the `missing` parameter of `DMatrix`

**Comment by lcrmorin** [comment]
I am under the impression that the special values present different behaviors, notably sentinel values that are imputed to +/- 999999. I undestand that the way to go would be to used an unique np.nan for all values and a second columns where special values are encoded as categoricals.

**Comment by trivialfis** [comment]
Apologies for the many questions.

> Thanks for your feed-back. I am under the impression that the special values present different behaviors, notably sentinel values that are imputed to +/- 999999.

I don't quite understand what you mean by this. XGBoost doesn't impute value, it learns the tree with gradient resided in the missing entries, which means the algorithm can handle missing value by itself.

> I undestand that the way to go would be to used an unique np.nan for all values and a second columns where special values are encoded as categoricals.

I don't quite understand this either. ;-( . What do you mean by special value, why is it special? Why is special value categorical? Not sure what "used an unique np.nan for all values" mean, did you mean using `np.nan` to represent all missing value?

**Comment by trivialfis** [comment]
Closing due to stalled. Feel free to reopen if there's further information.

**Comment by mahishah19** [comment]
Hello, I am facing the same issue and wondering what all did you guys do to handle such special cases where some numbers mean a particular thing and can not all be binned together. 
Thank you
