### ISSUE TITLE
Support np arrays for Vertical Federated Learning

### ISSUE THREAD

**Issue by edumugi** [dmlc/xgboost#9360]
Experimenting with the federated plugin (#8424) in a vertical environment I noticed that giving data as a numpy array to the DMatrix is not supported yet.

It should be a really easy fix since we only need to support the _data_split_mode_ arg in the **_from_numpy_array** function.

Steps would be:

- Add new arg _data_split_mode_ to **_from_numpy_array** in file python-package/xgboost/data.py
- Read _data_split_mode_ from config in function **XGDMatrixCreateFromDense** inside file src/c_api/c_api.cc

Should I open a PR for these changes?

**Comment by trivialfis** [comment]
The federated learning support is still working in progress. cc @rongou .

**Comment by rongou** [comment]
Yes, feel free to send @trivialfis and me a PR.

**Comment by trivialfis** [comment]
Thank you for the feature!
