### ISSUE TITLE
Quantile Regression in Python

### ISSUE THREAD

**Issue by kinkade-aumni** [dmlc/xgboost#9368]
I am interested in this walkthrough:
* https://xgboost.readthedocs.io/en/latest/python/examples/quantile_regression.html#sphx-glr-python-examples-quantile-regression-py

However, I am unable to find version 2.0.0 anywhere. I also cannot find the example itself on the repo. Would appreciate guidance.

**Comment by trivialfis** [comment]
Hi, 2.0 is still being worked on at the master branch. Out of curiosity, how did you get to that link? We set the default link to `stable` instead of `latest`. If there's a way for us to prevent people randomly bumping into unreleased document that can help prevent many confusions.

**Comment by kinkade-aumni** [comment]
I specifically googled "XGBoost Quantile Regression" and it was the first available link. 

Is there some way i can download the 2.0.0-dev branch and work with it?

**Comment by trivialfis** [comment]
Yes, https://xgboost.readthedocs.io/en/latest/install.html#nightly-build .

**Comment by kinkade-aumni** [comment]
Thank you. Is there a timeline on when version 2.0.0 will be fully released?

**Comment by trivialfis** [comment]
Not yet, but we should be able to get into RC within two months.

**Comment by kinkade-aumni** [comment]
Thank you for the details.
