### ISSUE TITLE
Submit(YARN) stuck, unable to continue

### ISSUE THREAD

**Issue by recallee** [dmlc/xgboost#937]
- present situation :
------
sh run_yarn_test.sh
2016-03-08 12:14:12,625 INFO start listen on 10.1.115.22:9104
16/03/08 12:14:14 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
16/03/08 12:14:14 WARN hdfs.BlockReaderLocal: The short-circuit local reads feature cannot be used because libhadoop cannot be loaded.
16/03/08 12:14:14 INFO client.RMProxy: Connecting to ResourceManager at /10.2.6.101:8032
16/03/08 12:14:14 INFO hdfs.DFSClient: Created HDFS_DELEGATION_TOKEN token 82948901 for midas_online on 10.2.6.102:8020
16/03/08 12:14:15 INFO dmlc.Client: Got dt for hdfs://10.2.6.102; Kind: HDFS_DELEGATION_TOKEN, Service: 10.2.6.102:8020, Ident: (HDFS_DELEGATION_TOKEN token 82948901 for midas_online)
16/03/08 12:14:25 INFO dmlc.Client: jobname=DMLC[nworker=2]:xgboost,username=midas_online
16/03/08 12:14:25 INFO dmlc.Client: Submitting application application_1456915997356_565539
16/03/08 12:14:26 INFO impl.YarnClientImpl: Submitted application application_1456915997356_565539
Application application_1456915997356_565539 finished with state FINISHED at 1457410505309
Available queues:
root.midas_online
……

16/03/08 12:16:27 INFO impl.YarnClientImpl: Killed application application_1456915997356_565646
16/03/08 12:16:27 INFO dmlc.Client: interruption received, kill application
16/03/08 12:16:27 INFO impl.YarnClientImpl: Killed application application_1456915997356_565646

------

- the code submit to YARN :

../../dmlc-core/tracker/dmlc-submit --cluster=yarn --num-workers=2 --worker-cores=2\
    ../../xgboost mushroom.hadoop.conf nthread=2\
    data=/user/midas_online/dolphinmlp/cpc-ranker/yichun.li/agaricus.txt.train\
    eval[test]=/user/midas_online/dolphinmlp/cpc-ranker/yichun.li/agaricus.txt.test\
    model_dir=/user/midas_online/dolphinmlp/cpc-ranker/yichun.li/model

Looking forward to your answer
Thank you very much

**Comment by tqchen** [comment]
please check the user log your have on the client side, using yarn logs command, it is likely you did not specify the path correctly with hdfs:// prefix

**Comment by recallee** [comment]
I have tried the path with "hdfs://"  before,  still unable to continue


Suspicious problems found in the YARN client log :

-------
Container: container_1456915997356_566829_01_000002 on hadoop-070.hm_10030
============================================================================
LogType: stderr
LogLength: 520
Log Contents:
Traceback (most recent call last):
  File "./launcher.py", line 68, in <module>
    main()
  File "./launcher.py", line 63, in main
    ret = subprocess.call(args=sys.argv[1:], env=env)
  File "/usr/lib64/python2.6/subprocess.py", line 478, in call
    p = Popen(*popenargs, **kwargs)
  File "/usr/lib64/python2.6/subprocess.py", line 639, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.6/subprocess.py", line 1228, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

LogType: stdout
LogLength: 0
Log Contents:

……
……

16/03/08 12:35:13 DEBUG ipc.Client: Negotiated QOP is :auth
16/03/08 12:35:13 DEBUG ipc.Client: Negotiated QOP is :auth
16/03/08 12:35:13 DEBUG ipc.Client: IPC Client (1854196745) connection to hadoop-034.hm/10.2.70.41:10030 from appattempt_1456915997356_566829_000001: starting, having connections 7
16/03/08 12:35:13 DEBUG ipc.Client: IPC Client (1854196745) connection to hadoop-076.hm/10.2.6.166:10030 from appattempt_1456915997356_566829_000001: starting, having connections 7
16/03/08 12:35:13 DEBUG ipc.Client: IPC Client (1854196745) connection to hadoop-034.hm/10.2.70.41:10030 from appattempt_1456915997356_566829_000001 sending #38
16/03/08 12:35:13 DEBUG ipc.Client: IPC Client (1854196745) connection to hadoop-076.hm/10.2.6.166:10030 from appattempt_1456915997356_566829_000001 sending #37
16/03/08 12:35:13 DEBUG ipc.Client: IPC Client (1854196745) connection to hadoop-034.hm/10.2.70.41:10030 from appattempt_1456915997356_566829_000001 got value #38
16/03/08 12:35:13 DEBUG ipc.ProtobufRpcEngine: Call: startContainers took 38ms
16/03/08 12:35:13 INFO dmlc.ApplicationMaster: onContainerStarted Invoked
16/03/08 12:35:13 DEBUG ipc.Client: IPC Client (1854196745) connection to hadoop-076.hm/10.2.6.166:10030 from appattempt_1456915997356_566829_000001 got value #37
16/03/08 12:35:13 DEBUG ipc.ProtobufRpcEngine: Call: startContainers took 43ms
16/03/08 12:35:13 INFO dmlc.ApplicationMaster: onContainerStarted Invoked
16/03/08 12:35:13 DEBUG ipc.Client: IPC Client (1854196745) connection to hadoop-175.hm/10.2.70.15:10030 from appattempt_1456915997356_566829_000001: closed
16/03/08 12:35:13 DEBUG ipc.Client: IPC Client (1854196745) connection to hadoop-175.hm/10.2.70.15:10030 from appattempt_1456915997356_566829_000001: stopped, remaining connections 6
16/03/08 12:35:14 DEBUG ipc.Client: IPC Client (1854196745) connection to /10.2.6.101:8030 from midas_online sending #39
16/03/08 12:35:14 DEBUG ipc.Client: IPC Client (1854196745) connection to /10.2.6.101:8030 from midas_online got value #39
16/03/08 12:35:14 DEBUG ipc.ProtobufRpcEngine: Call: allocate took 2ms
16/03/08 12:35:14 WARN dmlc.ApplicationMaster: KILLED_EXCEEDED_PMEM
16/03/08 12:35:14 INFO dmlc.ApplicationMaster: [DMLC] Task 0 exited with status 1 Diagnostics:Exception from container-launch: 
org.apache.hadoop.util.Shell$ExitCodeException: 
	at org.apache.hadoop.util.Shell.runCommand(Shell.java:505)
	at org.apache.hadoop.util.Shell.run(Shell.java:418)
	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:650)
	at org.apache.hadoop.yarn.server.nodemanager.LinuxContainerExecutor.launchContainer(LinuxContainerExecutor.java:279)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:300)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:81)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)

main : command provided 1
main : user is midas_online
main : requested yarn user is midas_online

Container exited with a non-zero exit code 1
-------

**Comment by tqchen** [comment]
You can read the log on what is happening.

The error says no such file or directory, please check if xgboost is indeed compiled, so that the submitted place indeed corresponds to xgboost path, if the error was no such file is presented. There is another error KILLED_EXCEEDED_PMEM, you can add more physical memory by specifying worker-memory

**Comment by recallee** [comment]
The job runs successfully  !!

but I found a possible bug ...
maybe...  

xgboost/dmlc-core/tracker/dmlc_tracker/launcher.py :

Maybe bug : if not os.path.exist(fname)  
Maybe correct: if not os.path.exists(fname)  

it leads to error:

-----------
LogType: stderr
LogLength: 334
Log Contents:
Traceback (most recent call last):
  File "./launcher.py", line 81, in <module>
    main()
  File "./launcher.py", line 74, in main
    unzip_archives(env['DMLC_JOB_ARCHIVES'].split(':'), env)
  File "./launcher.py", line 11, in unzip_archives
    if not os.path.exist(fname):
AttributeError: 'module' object has no attribute 'exist'

LogType: stdout
LogLength: 0
Log Contents:

**Comment by tqchen** [comment]
Hmm, this means os.path.exist may not actually exist on your running
machine.. Can you look a bit into it?

For reference, launcher is used to setup env variables correctly before
running the program

Tianqi

On Tue, Mar 8, 2016 at 1:47 AM, recallee <notifications@github.com> wrote:

> The job runs successfully !!
>
> but I found a possible bug ...
> maybe...
>
> xgboost/dmlc-core/tracker/dmlc_tracker/launcher.py :
>
> Maybe bug : if not os.path.exist(fname)
>
> Maybe correct: if not os.path.exists(fname)
>
> it leads to error:
> ------------------------------
>
> LogType: stderr
> LogLength: 334
> Log Contents:
> Traceback (most recent call last):
> File "./launcher.py", line 81, in
> main()
> File "./launcher.py", line 74, in main
> unzip_archives(env['DMLC_JOB_ARCHIVES'].split(':'), env)
> File "./launcher.py", line 11, in unzip_archives
> if not os.path.exist(fname):
> AttributeError: 'module' object has no attribute 'exist'
>
> LogType: stdout
> LogLength: 0
> Log Contents:
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/xgboost/issues/937#issuecomment-193692043>.
>



-- 
Sincerely,
------------------------------------------------
Tianqi Chen
Computer Science & Engineering, University of Washington

**Comment by edi-bice** [comment]
I was running into the same launcher.py error while running this way:

./dmlc-core/tracker/dmlc-submit --cluster=yarn --num-workers=9 --worker-cores=4 ./xgboost ~/xgboost-old/snowman.hadoop.conf nthread=2 data=hdfs:///user/ebice/loaffsvm10M/part-00000 eval[test]=hdfs:///user/ebice/loaffsvm10M/part-00000 model_out=hdfs:///tmp/oaff.model2

Specifying full path to xgboost executable resolved the issue for me:

./dmlc-core/tracker/dmlc-submit --cluster=yarn --num-workers=9 --worker-cores=4 /home/ebice/xgboost/xgboost ~/xgboost-old/snowman.hadoop.conf nthread=2 data=hdfs:///user/ebice/loaffsvm10M/part-00000 eval[test]=hdfs:///user/ebice/loaffsvm10M/part-00000 model_out=hdfs:///tmp/oaff.model2

**Comment by edi-bice** [comment]
FYI - the hdfs path spec above used to work but now it doesn't for me - had to specify namenode host as well.
