### ISSUE TITLE
Data used for prediction at each leaf

### ISSUE THREAD

**Issue by geomeday** [dmlc/xgboost#9371]
I am currently working with the R version of a project and need assistance with accessing the data used for prediction at each leaf. I would like to retrieve the information on the data employed within a specific cover for further analysis. My goal is to enhance the existing functionality by gaining access to this internal function, alongside the 'Cover' data, which is already available.

Example code in R:
data(agaricus.train, package='xgboost')

bst <- xgboost(data = agaricus.train$data, label = agaricus.train$label, max_depth = 2,
               eta = 1, nthread = 2, nrounds = 2,objective = "binary:logistic")

(dt <- xgb.model.dt.tree(colnames(agaricus.train$data), bst))

(dt <- xgb.model.dt.tree(model = bst))

Output is:
    Tree Node  ID                 Feature         Split  Yes   No Missing      Quality      Cover
 1:    0    0 0-0               odor=none -9.536743e-07  0-1  0-2     0-1 4000.5310100 1628.25000
 2:    0    1 0-1         stalk-root=club -9.536743e-07  0-3  0-4     0-3 1158.2120400  924.50000
 3:    0    2 0-2 spore-print-color=green -9.536743e-07  0-5  0-6     0-5  198.1738280  703.75000
 4:    0    3 0-3                    Leaf            NA <NA> <NA>    <NA>    1.7121772  812.00000
 5:    0    4 0-4                    Leaf            NA <NA> <NA>    <NA>   -1.7004405  112.50000
 6:    0    5 0-5                    Leaf            NA <NA> <NA>    <NA>   -1.9407086  690.50000

I would greatly appreciate any guidance or assistance in locating the appropriate internal function or alternative method that can provide the desired leaf data for prediction within the R version. Thank you in advance for your support!

**Comment by trivialfis** [comment]
I can't reca the exact name at the moment, but there's a parameter similar to `pred_leaf` in the predict function.
