### ISSUE TITLE
How to view the final result for distributed computing

### ISSUE THREAD

**Issue by yilaguan** [dmlc/xgboost#938]
Hi，When I use distributed xgboost, I can get the global accuracy, but I find the final result model can not access as the final model of single machine xgboost. And the dumped tree appears to be too short compared to the single mode for same input data. Can you tall me how to get the entire tree and probability distribution of prediction result in distributed xgboost? 
the pred.txt is below:
booster[0]:
0:[odor=none] yes=1,no=2
        1:[spore-print-color=green] yes=3,no=4
                3:leaf=1.85965
0.954672
0.00686907
0.954672
0.954672
0.954672
0.954672
0.954672
0.308975
0.308975
0.954672
0.954672
0.954672
0.954672
0.116715
0.954672
0.954672
0.308975
0.954672
0.954672
0.954672
0.954672
0.954672
0.954672
0.954672
0.954672
0.954672
0.954672

the dump.nice.txt is 
booster[0]:
0:[odor=none] yes=1,no=2
        1:[spore-print-color=green] yes=3,no=4
                3:leaf=1.85965
                4:[stalk-surface-below-ring=scaly] yes=7,no=8
                        7:leaf=0.808511
                        8:leaf=-1.98531
        2:[stalk-root=club] yes=5,no=6
                5:[bruises?=bruises] yes=9,no=10
                        9:leaf=-1.98104
                        10:leaf=1.77778
                6:[stalk-root=rooted] yes=11,no=12
                        11:leaf=-1.95062
                        12:leaf=1.90175
booster[1]:
0:[odor=none] yes=1,no=2
        1:[spore-print-color=green] yes=3,no=4
                3:leaf=0.994744
                4:[gill-size=broad] yes=7,no=8
                        7:leaf=-1.15275
                        8:leaf=-0.0386054
        2:[bruises?=bruises] yes=5,no=6
                5:[gill-spacing=close] yes=9,no=10
                        9:leaf=-0.127376
                        10:leaf=-6.87558
                6:leaf=1.1457

the dump.raw.txt is

booster[0]:
0:[f28<2] yes=1,no=2,missing=2
        1:[f108<2] yes=3,no=4,missing=4
                3:leaf=1.85965
                4:[f66<2] yes=7,no=8,missing=8
                        7:leaf=0.808511
                        8:leaf=-1.98531
        2:[f55<2] yes=5,no=6,missing=6
                5:[f20<2] yes=9,no=10,missing=10
                        9:leaf=-1.98104
                        10:leaf=1.77778
                6:[f59<2] yes=11,no=12,missing=12
                        11:leaf=-1.95062
                        12:leaf=1.90175
booster[1]:
0:[f28<2] yes=1,no=2,missing=2
        1:[f108<2] yes=3,no=4,missing=4
                3:leaf=0.994744
                4:[f38<2] yes=7,no=8,missing=8
                        7:leaf=-1.15275
                        8:leaf=-0.0386054
        2:[f20<2] yes=5,no=6,missing=6
                5:[f35<2] yes=9,no=10,missing=10
                        9:leaf=-0.127376
                        10:leaf=-6.87558
                6:leaf=1.1457

**Comment by tqchen** [comment]
The model saved by distributed training mode can be directly loaded in single machine mode and do all the things you can

**Comment by yilaguan** [comment]
Thank you your answer, but I find the size of distributed model is small and single machine model is bigger than distributed model.
the size of single model       the size of distributed model
    7.5MB                                            1.46KB

So, when I load distributed training mode directly in single machine mode, I can not predict test dataset with probability.
the dump.raw.txt in distributed training mode is also smaller than single machine ones. The program location is ../demo/distributed-training/run_yarn.sh, and mushroom.hadoop.conf is also in here. The config of mushroom.hadoop.conf is below:

# General Parameters, see comment for each definition
# choose the booster, can be gbtree or gblinear
booster = gbtree
# choose logistic regression loss function for binary classification
objective = multi:softprob

# Tree Booster Parameters
# step size shrinkage
eta = 0.15
# minimum loss reduction required to make a further partition
gamma = 1.0
# minimum sum of instance weight(hessian) needed in a child
min_child_weight = 1
# maximum depth of a tree
max_depth = 300
num_class = 257
# Task Parameters
# the number of round to do boosting
num_round = 50
# 0 means do not save any model except the final round model
save_period = 1
# evaluate on training data as well each round
# eval_train = 1
# The path of validation data, used to monitor training process, here [test] sets name of the validation set
# eval[test] = "agaricus.txt.test"

# Plz donot modify the following parameters
# The path of training data, with prefix hdfs
#data = hdfs:///data/
# The path of model file
#model_out = 
# split pattern of xgboost
dsplit = row
# evaluate on training data as well each round
eval_train = 1

**Comment by tqchen** [comment]
please check out the most recent version of tutorial here https://xgboost.readthedocs.org/en/latest/tutorial/aws_yarn.html

**Comment by tqchen** [comment]
I noticed you are using multi-class classification on a binary dataset, which may not make sense

**Comment by yilaguan** [comment]
I used multi-class classification on myself multi-classification dataset. The logs of precess of distributed xgboost is the same of single machine. And I find the time of distributed xgboost training will slower than single machine. I want to know whether some step I forget.
The distributed xgboost I used now is not latest.

**Comment by tqchen** [comment]
It is possible for distributed setting to be slower, especially if it is a small dataset that fit into single machine. I would recommend to use the latest version of xgboost since there could be problems that get fixed

**Comment by yilaguan** [comment]
I follw your advice to install the latest version of xgboost, but when I use myself dataset in run_aws.sh, which have 257 classification, and change some paramaters, a error throw to me:
Container: container_1457405676167_0087_01_000009 on longzhou-hdp3.lz.dscc_12040_1457509813547
================================================================================================
LogType:stderr
Log Upload Time:Wed Mar 09 15:50:13 +0800 2016
LogLength:132
Log Contents:
terminate called after throwing an instance of 'dmlc::ParamError'
  what():  Required parameter num_feature of int is not presented

Can you tell me num_feature's means? And whether set this paramter to mushroom.aws.conf?

**Comment by tqchen** [comment]
Hmm, this usually is automatically setted by the learner as in here https://github.com/dmlc/xgboost/blob/master/src/learner.cc#L195. 

It is the number of feature dimension you  will specify in the data. Please check if this also happens in single machine version, if you can provide a reproducible toy example, we can look into it.

You can also set it manually to the maximum feature dimension you have

**Comment by yilaguan** [comment]
Thank you! I follow your advice to set myself num_feature in here [https://github.com/dmlc/xgboost/blob/master/src/learner.cc#L195.](url). The distributed xgboost also can run, but it takes longer time than single machine. By the way, the final model builded by distributed xgboost is a folder, which is composed of 10 model. For example, mushroom.final.model is a folder, which include:
171264 2016-03-10 10:23 test/mushroom.final.model/0001.model
396844 2016-03-10 10:27 test/mushroom.final.model/0002.model
643232 2016-03-10 10:32 test/mushroom.final.model/0003.model
907044 2016-03-10 10:37 test/mushroom.final.model/0004.model
1185832 2016-03-10 10:43 test/mushroom.final.model/0005.model
1479164 2016-03-10 10:48 test/mushroom.final.model/0006.model
1779840 2016-03-10 10:53 test/mushroom.final.model/0007.model
2086636 2016-03-10 10:58 test/mushroom.final.model/0008.model
2398256 2016-03-10 11:03 test/mushroom.final.model/0009.model
2718228 2016-03-10 11:08 test/mushroom.final.model/0010.model
when I used final.model in single machine to load, I do not know which one I needed. The parameter I used is below:
--cluster=yarn --num-workers=2 --worker-cores=4

First , I use mushroom.final.model to load , but a error throw to me. It is 
xgboost.core.XGBoostError: [14:08:09] src/learner.cc:224: Check failed: (fi->Read(&mparam, sizeof(mparam))) == (sizeof(mparam)) BoostLearner: wrong model format

Second, I know the model is not a folder name, so I choose 0001.model randomly to load. The python code is below:
dtest = xgb.DMatrix('save_test_data.txt')
bst = xgb.Booster({'nthread':4})
bst.load_model('final.model/0001.model')
ypred = bst.predict(dtest)

when the program run ypred=bst.predict(dtest), a error also throw to me:

  File "/usr/local/lib/python2.7/dist-packages/xgboost-0.4-py2.7.egg/xgboost/core.py", line 97, in _check_call
    raise XGBoostError(_LIB.XGBGetLastError())
xgboost.core.XGBoostError: Required parameter num_class of int is not presented

Finally, I do not know where to set num_class. I guess the localtion is the same num_feature, and change num_class=257 in here: [ https://github.com/dmlc/xgboost/blob/master/src/learner.cc#L261.](url). But it also give me the same error:
  File "/usr/local/lib/python2.7/dist-packages/xgboost-0.4-py2.7.egg/xgboost/core.py", line 97, in _check_call
    raise XGBoostError(_LIB.XGBGetLastError())
xgboost.core.XGBoostError: Required parameter num_class of int is not presented

Can you tell me how I load the model?

**Comment by tqchen** [comment]
The folder is because you set model_folder, and seems you ask xgboost to save model each iteration.

What you said is absolutely abnormal to me and I have no idea on what is going on your side. Please first confirm the following things
- Does original binary classification example works on your case
- Does multi-class classification works on single machine(including model save/load).

The most helpful thing might be provide a toy example that reproduce your errors, so we can look into it. Another thing that you can possibly do is to check where does the error thrown out, and when does this happen.

**Comment by yilaguan** [comment]
Hi, I follow what you advice to do two things, and the result is below:
(1) When I run original binary classification example on my case, everything is ok, and the model can be save, load and prediction.
(2)Multi-class classification can work nurmality on single machine save and load , but when I predict use the model loaded, there is a error throw:
xgboost.core.XGBoostError: Required parameter num_class of int is not presented

On single machine, when I used program:
        dtrain = xgb.DMatrix('agaricus.txt.train')
	dtest = xgb.DMatrix('agaricus.txt.test')
	param = {'bst:max_depth':20, 'bst:eta':0.15, 'objective':'multi:softprob', 'silent':1}
	param['nthread'] = 4
	param['num_class'] = 2
	evallist  = [(dtest,'eval'), (dtrain,'train')]
	num_round = 10
	bst = xgb.train(param ,dtrain, num_round, evallist)
	bst.save_model('simple.model')
	bst.dump_model('dump.raw.txt')
        ypred = bst.predict(dtest)

and everything is ok.
But after I use program:

        dtest = xgb.DMatrix('agaricus.txt.test')
        bst = xgb.Booster({'nthread':4})
	bst.load_model('simple.model')
	ypred = bst.predict(dtest)

there is throw a error to me:

  File "/home/yilaguan/xgboost.py", line 574, in xgboost_distribution
    ypred = bst.predict(dtest)
  File "/usr/local/lib/python2.7/dist-packages/xgboost-0.4-py2.7.egg/xgboost/core.py", line 889, in predict
    ctypes.byref(preds)))
  File "/usr/local/lib/python2.7/dist-packages/xgboost-0.4-py2.7.egg/xgboost/core.py", line 97, in _check_call
    raise XGBoostError(_LIB.XGBGetLastError())
xgboost.core.XGBoostError: Required parameter num_class of int is not presented

The error occured, when I use your provide data in /demo/data/agaricus.txt.train and /demo/data/agaricus.txt.test.

**Comment by tqchen** [comment]
thanks, please let me look into it

**Comment by tqchen** [comment]
Thanks for being patient and look into it. This is indeed a bug introduced in the newest refactor that was missed by the regresion test. I have created https://github.com/dmlc/xgboost/pull/961 to fix this.

Sorry about the trouble caused.

On the speedside, it is quite common for distributed version to be slower when working with small dataset, and usually single machine is enough.

**Comment by pommedeterresautee** [comment]
Fixed
