### ISSUE TITLE
Handle UTF-8 paths correctly on Windows platform

### ISSUE THREAD

**Issue by gump996** [dmlc/xgboost#9406]
I've got an error while using xgb.load() to load a JSON model file which was saved by xgb.save().
Like this: 
Error in xgb.Booster.handle(modelfile = modelfile) 
I found that if the model file path did not contain Chinese characters and it will work perfect!
The version of xgboost package is 1.7.5.1.
By the way, if I use xgb.save() with the extension 'model' and load the model file, it also works.
Hoping this issue will be fixed in the future release.

**Comment by trivialfis** [comment]
It seems to be a R-specific issue.

**Comment by trivialfis** [comment]
Nope, it works fine on my system (ubuntu 22.04) with R 4.1.2. Maybe it's the system locale configuration.

**Comment by gump996** [comment]
I've tried it on 2 different computers running Windows 10 and 11 with R 4.1.2, 
but I've still got the same error.

**Comment by hcho3** [comment]
The issue is specific to Windows. When opening files with Windows, we need to build `std::filesystem::u8path` object (to represent a UTF-8 string) and pass it to `std::ifstream`. See https://gitlab.com/inkscape/inkscape/-/merge_requests/3784.
