### ISSUE TITLE
`xgboost.dask.train` gets stuck indefinitely if worker holding data from `DaskDMatrix` restarts

### ISSUE THREAD

**Issue by hendrikmakait** [dmlc/xgboost#9420]
Similar to #9419, the current design of `DaskDMatrix` is problematic because it records the workers storing the individual partitions of the dataset. If a worker left, but enough workers are around to satisfy 
https://github.com/dmlc/xgboost/blob/7579905e187fbbc2cec48299f7ea36a0365ba4d8/python-package/xgboost/dask.py#L85
(.e.g., because the worker restarted and returned with a new address or there are additional workers), then `xgboost.dask.train` starts the training phase and pins a training task to the worker that already left the cluster. This will cause the task to transition into the `no-worker` state where it will remain indefinitely and `xgboost.dask.train` will get stuck.

**Reproducer:**

```python3
import dask.array as da
import xgboost as xgb 

from distributed import Nanny
from distributed.utils_test import gen_cluster


@gen_cluster(client=True, Worker=Nanny)
async def test_worker_restarted(c, s, a, b):
    dx = da.random.random((300, 10)).rechunk(chunks=(10, None))
    dy = da.random.random((300,)).rechunk(chunks=(10,))
    d_train = await xgb.dask.DaskDMatrix(
        c, dx, dy,
    )
    await c.restart_workers([a.worker_address])
    await xgb.dask.train( 
        c,
        {},
        d_train,
        evals=[(d_train, "train")],
    )
```
Versions:

* `dask=2023.7.1`
* `distributed=2023.7.1`

A possible fix for #9419 and this issue would be to replace `wait_for_workers` with a check that the expected workers are around, and raise an error if not.

**Comment by pangjac** [comment]
Hi @hendrikmakait @trivialfis , may I know which (oldest) stable version includes this fix ? I am using xgboost 2.1.4 version and got the same issue.
PS. If there is a list that map the fixed issues to stable released version, please let me know, I can double check the mapping issue list. Thanks for the help!

**Comment by trivialfis** [comment]
I don't think there's a robust fix for all potential resilience issues. We need help from the upstream as XGBoost itself is just a wrapper: https://github.com/dask/distributed/issues/8624 .

**Comment by trivialfis** [comment]
That said, we have some new mitigation in 3.0 https://github.com/dmlc/xgboost/pull/10985 to prefer an error over a hang.
