### ISSUE TITLE
Segmentation fault for QuantileDMatrix with data iterator on master

### ISSUE THREAD

**Issue by lukezli** [dmlc/xgboost#9439]
Hi all,

First - thanks so much for maintaining such a great and useful project!

When trying to run xgb 2.0.0 via various nightly releases of master on ubuntu 22.0.4, I can't seem to load data to a QuantileDMatrix via a data iterator (https://xgboost.readthedocs.io/en/latest/python/examples/quantile_data_iterator.html). Whenever there are too many files / too much data, I get a segmentation fault. This doesn't occur when the number of files/rows are smaller. This also doesn't occur in the prod releases of xgboost on my same data/machine, for example xgb 1.7.6.

I'm sorry I can't give an easy-to-reproduce example, as it only occurs when the number of files/rows read in is quite large (many millions of rows split up into hundreds/thousands of files).

**Comment by trivialfis** [comment]
Hi, thank you for raising the issue, any chance that it's running out of memory?

**Comment by lukezli** [comment]
Unfortunately I don't think so. I was worried that was the case so I partitioned swap space ~4x larger than what's necessary for 1.7.6 to run successfully.

**Comment by trivialfis** [comment]
Let me take a closer look later.

**Comment by trivialfis** [comment]
Could you please share some details about the machine you are using along with the shape of the dataset?
- Size of memory, including swap
- Shape of the dataset, including rows and  columns
- Sparsity of the dataset
- Training parameters

**Comment by trivialfis** [comment]
The initial test shows no change in memory usage between versions. Trying to reproduce it on aws.

I'm using a numpy input without any categorical feature, could you please confirm that you are using similar a setup?

**Comment by lukezli** [comment]
Hi,

No categorical features, but I do read in and pass in my input as a pandas dataframe:

        df = pd.read_csv(f"{datadir}/{self._file_paths[self._it]}", header=None)
        X = df.iloc[:,2:-1]
        y = np.array(df.iloc[:,-1])

        input_data(data = X, label = y)

I'm not sure if this will help, but sometimes, instead of segmentation fault, I get the following error:

Traceback (most recent call last):
    Xy = xgb.QuantileDMatrix(it)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/xgboost/core.py", line 703, in inner_f
    return func(**kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/xgboost/core.py", line 1498, in __init__
    self._init(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/xgboost/core.py", line 1559, in _init
    _check_call(ret)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/xgboost/core.py", line 276, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: [04:35:41] /workspace/src/data/iterative_dmatrix.cc:262: Check failed: rbegin == Info().num_row_ (5052385 vs. 5051521) :
Stack trace:
  [bt] (0) /home/ubuntu/.local/lib/python3.10/site-packages/xgboost/lib/libxgboost.so(+0x3f2b5a) [0x7f616cbf2b5a]
  [bt] (1) /home/ubuntu/.local/lib/python3.10/site-packages/xgboost/lib/libxgboost.so(+0x3f9a8f) [0x7f616cbf9a8f]
  [bt] (2) /home/ubuntu/.local/lib/python3.10/site-packages/xgboost/lib/libxgboost.so(+0x3fb3f8) [0x7f616cbfb3f8]
  [bt] (3) /home/ubuntu/.local/lib/python3.10/site-packages/xgboost/lib/libxgboost.so(+0x3a6f27) [0x7f616cba6f27]
  [bt] (4) /home/ubuntu/.local/lib/python3.10/site-packages/xgboost/lib/libxgboost.so(XGQuantileDMatrixCreateFromCallback+0x2b0) [0x7f616c96c2a0]
  [bt] (5) /lib/x86_64-linux-gnu/libffi.so.8(+0x7e2e) [0x7f61d96f3e2e]
  [bt] (6) /lib/x86_64-linux-gnu/libffi.so.8(+0x4493) [0x7f61d96f0493]
  [bt] (7) /usr/lib/python3.10/lib-dynload/_ctypes.cpython-310-x86_64-linux-gnu.so(+0xa3e9) [0x7f61d92873e9]
  [bt] (8) /usr/lib/python3.10/lib-dynload/_ctypes.cpython-310-x86_64-linux-gnu.so(+0x9a00) [0x7f61d9286a00]

**Comment by trivialfis** [comment]
I have reproduced the error. Python recycled its object id, which invalidates the cache in XGBoost data iterator.

**Comment by lukezli** [comment]
Thanks, looks like it's no longer crashing on newest version of master! Appreciate the prompt response and fix!

Any place I can go to buy the xgboost devs a coffee for their hard work?

**Comment by trivialfis** [comment]
You are welcomed!
