### ISSUE TITLE
[FEA] Relax the hard dependency on NCCL

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#9442]
Currently we specify NCCL as a hard dependency when we distribute XGBoost via Conda and pip (*). This means that CPU users have to install NCCL, costing extra bandwidth and storage.

Here are some ideas for relaxing the hard dependency on NCCL: 

1. Distribute separate packages for CPU and GPU versions. This way, the GPU version can carry NCCL dependency while the CPU version can drop the dependency. The disadvantage is that users no longer get access to `gpu_hist` automatically after running `pip install xgboost`.

2. Lazily load NCCL via dlopen. This was discussed previously in https://github.com/dmlc/xgboost/issues/8140 but the idea was rejected due to unfavorable tradeoffs.

3. Refactor parts of XGBoost into a separate library. This method could overcome some disadvantages of Option 2, but has higher engineering cost due to the refactor.

4. Create a shim library that handles lazy loading, using https://github.com/yugr/Implib.so

As we discuss alternatives, we need to be careful of the following:

* Extra code complexity due to the use of opaque library handles
* Performance degradation due to redirection via function pointers
* Complex logic for locating `libnccl.so` correctly.
* Any other undefined behavior due to lazy initialization of NCCL

Note: The status quo is okay, since NCCL can be installed on a CPU-only machine. The only disadvantage of the status quo is the extra download, using bandwidth and disk space.

(*) For pip distribution, we statically link NCCL into the binary wheel. This increases the size of the binary considerably. Note, however, that some of the alternatives, such as Option 3, will still necessitate static linking, since pip does not facilitate import of C++ library dependencies.

**Comment by trivialfis** [comment]
Closed by https://github.com/dmlc/xgboost/pull/9796 .
