### ISSUE TITLE
R test fail on Windows with file reading.

### ISSUE THREAD

**Issue by trivialfis** [dmlc/xgboost#9453]
```
     Error ('test_dmatrix.R:75:3'): xgb.DMatrix: saving, loading
     Error in `xgb.DMatrix(paste(tmp_file, "?format=libsvm", sep = ""), silent = TRUE)`: [13:41:35] amalgamation/../dmlc-core/src/io/input_split_base.cc:173: Check failed: files_.size() != 0U (0 vs. 0) : Cannot find any files that matches the URI pattern C:\Users\USERQE~1\AppData\Local\Temp\RtmpghqYlb/working_dir\RtmpoTEARg\file144c5440cb0.libsvm
     Backtrace:
         ▆
      1. └─xgboost::xgb.DMatrix(...) at test_dmatrix.R:75:2
     
     [ FAIL 1 | WARN 2 | SKIP 1 | PASS 1331 ]
```

Same result on R-winbuilder and rhub.

**Comment by trivialfis** [comment]
@hcho3 Do you have something on top of your mind? The full log is here: https://builder.r-hub.io/status/original/xgboost_2.0.0.1.tar.gz-56976f4b6c984e4f9a2e142a6055c6f7

**Comment by trivialfis** [comment]
I can't reproduce it on my windows laptop.

**Comment by hcho3** [comment]
`USERQE~1` seems suspicious

**Comment by trivialfis** [comment]
@hcho3 New result, I tried to print out the path in dmlc core, but looks like gibberish  https://artifacts.r-hub.io/xgboost_2.0.0.1.tar.gz-cb1c9670df984eda8f332fafe981ae32/xgboost.Rcheck/tests/testthat.Rout.fail

**Comment by hcho3** [comment]
We need to ensure that the R package properly normalizes the path, by calling `normalizePath` on the path string. It will substitute `~` on Linux and expand short paths like `USERQE~1` on Windows

**Comment by trivialfis** [comment]
hmm, I didn't know that there's a thing called short path. Thank you for sharing, I will try to normalize the path

**Comment by hcho3** [comment]
Yeah, short paths are a legacy from DOS
