### ISSUE TITLE
Using regular quotation marks "" for all non-system header files

### ISSUE THREAD

**Issue by WojciechMigda** [dmlc/xgboost#947]
I was recently partaking in the top coder competition where I was using xgboost to solve the problem. The trick is that the solution had to be bundled as a single source file. As expected, I was using amalgamation for that. The only downside regarding xgboost was that many of the xgboost's own header files are #included with angle brackets, which make it hard for amalgamation software to distinguish between library and system header files.
My proposal is to perform library-wide replacement of angle brackets with regular double quotation marks for all xboost header files. If you agree with that I can do necessary changes myself and submit relevant pull request.

**Comment by tqchen** [comment]
I liked the idea of amalgamation, and https://github.com/dmlc/xgboost/tree/master/amalgamation provides some good starting point of what to be included.

However, I do want to keep the style of current include structure, to distinguish between xgboost/dmlc library header and source headers.

One thing to check the header is that ```<xgboost/xxx.h>``` and ```<dmlc/xxx.h>``` are always the project internal headers. This indeed need a bit hack of amalgamation tool.

MXNet has as simple and similar amalgamation tool which can be potentially adapted.

https://github.com/dmlc/mxnet/blob/master/amalgamation/amalgamation.py
