### ISSUE TITLE
Deprecate the command line interface.

### ISSUE THREAD

**Issue by trivialfis** [dmlc/xgboost#9471]
Currently, the CLI  is rarely used as the vast majority of the users want access to the ecosystem of other language bindings. Even basic things like cross-validation are quite difficult to perform using the CLI.

For inference, there are low-latency options like inplace_predict with proper C API, not to mention third-party libraries like FIL that focus on model deployment.

I propose that we move on and deprecate the CLI in order to focus on more promising features.

**Comment by saxena-vinayak36** [comment]
can anyone tell me how to merge my pr with this?

**Comment by saxena-vinayak36** [comment]
I think I can contribute to this.

**Comment by trivialfis** [comment]
H @saxena-vinayak36 i, this issue has already been closed.
