### ISSUE TITLE
XGBoost makes every output printed twice

### ISSUE THREAD

**Issue by Sion1225** [dmlc/xgboost#9487]
Hello! 
I just installed newest XGBoost.

When I use XGBoost, It makes every output printed twice.

example code
```
import xgboost

print("AAA")
```
output
```
AAA
AAA
```

I checked this problem in not only windows terminal(python ver: 3.9.0) but also WSL2 Ubuntu(python ver: 3.10.12).

Please anyone teach about the solution for this problem.

Thank you.

**Comment by trivialfis** [comment]
That's novel. I don't know how it happens can never seen it before.

**Comment by Sion1225** [comment]
Sorry for interrupt it was my setting miss
