### ISSUE TITLE
How can i use C interface to get same prediction value as Python?

### ISSUE THREAD

**Issue by FanChangchun123** [dmlc/xgboost#9496]
Hi, expert!
Fisrt i get python trained model, and put some input into model to get prediction.
Then i use C interface to load the trained model,  and put same input into model. For some input get the same prediction as python ,but others not.

**Comment by FanChangchun123** [comment]
@WeichenXu123 @trivialfis python xgboost version is 1.5.2, and C xgboost version is 1.5.1

**Comment by trivialfis** [comment]
Please share a reproducible example. In addition, please upgrade to the latest XGBoost.

**Comment by FanChangchun123** [comment]
I found the reason. The booster function get_dump return 32-float value text, can it be

**Comment by FanChangchun123** [comment]
I found the reason. The booster function get_dump return 32bit-float value text, is there any ways to get 64bit-float value of leaf node or split node value?

**Comment by trivialfis** [comment]
No, the value is stored in 32-bit `float`. If you want bit-by-bit equivalent representation, consider saving the model in the `ubj` format or the `json` format (`json` format requires using the parser in XGBoost to reproduce the floating point). See https://github.com/dmlc/xgboost/blob/master/demo/json-model/json_parser.py

**Comment by FanChangchun123** [comment]
I get value by get_booster().trees_to_dataframe(), the split value is stored in 64-bit float, but when i print it ,it seems to be 32-bit float.I want to know the value getted by get_booster().trees_to_dataframe() is the real value?

**Comment by trivialfis** [comment]
The value has gone through serialization from binary to decimal and back to binary, which may lose precision:

``` python
print("{:.15f}".format(12.7))
>>> 12.699999999999999
```

Use the `save_model` instead.
