### ISSUE TITLE
Factors

### ISSUE THREAD

**Issue by BlindApe** [dmlc/xgboost#95]
How do the factor variables treated?
Transformed to numeric in the levels (by order of them)?
Onehot encoding?
Used as categorical and performing categorical splitting?

**Comment by ekerazha** [comment]
@tqchen LightGBM recently got support for Categorical Features. For columns with many categorical values (thousands), where one-hot-encoding is hard, I got massive improvements. xgboost, without categorical features support, is not even a possibility.
