### ISSUE TITLE
Gblinear gives NaN as prediction in R

### ISSUE THREAD

**Issue by pawelgodula** [dmlc/xgboost#950]
Hello. I am currently doing Homedepot challenge on Kaggle, and I encountered an error, which I descibred in my post on Kaggle forum. Since no one responded there, maybe you know what is going on?
	
Hello

I am buidling my XGBoost in R, and wanted to experiment with XGBoost linear booster (so far i was using tree booster). The code is the following:

```
ntrees <- 100
seed <- 1777
param <- list(  objective           = "reg:linear", 
                booster             = "gblinear",
                eval_metric         = "rmse"
                #eta                 = 0.1, 
                #max_depth           = 5,
                #subsample           = 0.9, 
                #colsample_bytree    = 1)

set.seed(seed)

feature.names <- setdiff(colnames(train), c("product_uid", "id", "product_title", "search_term", "relevance", "product_description"))

tra <- train[,feature.names]
dtrain <- xgb.DMatrix(data=data.matrix(tra),label=train$relevance)  

model_1 <- xgb.train(   params              = param, 
                    data                = dtrain, 
                    nrounds             = ntrees, 
                    verbose             = 1)

test_relevance <- predict(model_1, data.matrix(test[,feature.names]))
test_relevance  NaN           NaN  1.150361e+00  4.391110e+00  1.197555e+00           NaN  2.279827e+00 ...
```
Anyone has any idea why model with "gblinear" booster returs NaN as prediction? When I change the booster to "gbtree" everything goes back to normal and there are no NAs in the prediction.

And a more general question: what is your experience of using linear booster vs tree booster? Which one yields better results?

**Comment by tim-scharf** [comment]
pretty sure gblinear cannot withstand missing values in the inputs.. check your training data and verify it's clean.  Your `param` list looks fine

**Comment by khotilov** [comment]
I think gblinear treats missing values as zeros. @tqchen, is that correct?

@pawelgodula:
I'm not sure what exactly your train dataset is, but from a brief look at that Homedepot challenge I might guess it has lots of features extracted from text. I guess a lot of them would be quite correlated between each other. In this case I would strongly advise to add some regularization (alpha or/and lambda parameters). Non-regularized linear models tend to be rather unreliable in such situations. 

Also, you may want to check out model's coefficients with xgb.dump to see whether some of them are NaN, NA or Inf's.

**Comment by tqchen** [comment]
Yes, gblinear simply treat missing value as zero

**Comment by tim-scharf** [comment]
thanks for correcting me guys -
