### ISSUE TITLE
xgboost on Windows/Python: DOES NOT COMPILE/RUN!

### ISSUE THREAD

**Issue by fryasdf** [dmlc/xgboost#952]
Hi.

Ive burned some hours now on trying to get xgboost to run on Windows.

1) Ran "pip install xgboost"
-> package exists but install routine is broken

2) Tried to compile using mingw, after executing "make" I get
-> error message "sorry, unimplemented, 64 bit Support not compiled in"

3) Figured out that I Need a Special Version of mingw called mingw64. Downloaded it from http://mingw-w64.org (winBuilds). Tried to make: "command not found: make". Tried to use commands like "make", "rm", ... from mingw32 
-> error message: "sorry, unimplemented, 64 bit Support not compiled in"

4) Followed the advice on this [SE post](http://stackoverflow.com/questions/17988904/compile-64-bit-binary-with-mingw-dev-c) download Dev-c++, copied the mingw64 subfolder to c:\mingw64, tried to compile again 
-> Compilation is fine but then linking is broken: In the line "Import xgboost as xgb" I get the error "Module not found".

5) Followed this [SE post](http://stackoverflow.com/questions/10411709/windowserror-error-126-when-loading-a-dll-with-ctypes), downloaded DependencyChecker, saw that the xgboost.dll has two Problems: arch is x86 in all referred dlls (while it should be something like x64 or so I guess...) and libomp-1.dll cannot be found...

6) Downloaded the binaries from [here](https://www.kaggle.com/c/otto-group-product-classification-challenge/forums/t/13043/run-xgboost-from-windows-and-python) but python is not able to locate the dll and DependencyChecker reports even more errors...

7) Thinking about coding it myself to save me some time ... ;-)

Can somebody help?

THX in advance....

**Comment by thirdwing** [comment]
Please tell us you are on 32 bit or 64 bit system first.

**Comment by fryasdf** [comment]
Im using 64 bit Windows 7 Enterprise Service Pack 1.

**Comment by KobaKhit** [comment]
Same here. And the links to windows files in [tutorial here](https://github.com/dmlc/xgboost/tree/master/python-package) are broken

**Comment by Bolaka** [comment]
For 64 bit windows, using [TDM-GCC](http://tdm-gcc.tdragon.net/download) compiler with OpenMP option enabled works and the xgboost build is successful.

**Comment by matt32106** [comment]
Is there a procedure somewhere describing the steps to compile xgboost with TDM?

**Comment by Bolaka** [comment]
@matt32106 follow http://dnc1994.com/2016/03/installing-xgboost-on-windows/

**Comment by redpanda08** [comment]
Hello, 

I have followed the threads above but I have received the error below : 
build/learner.d g++,exe: error: CreateProcess: No such file or directory 
Makefile: 97: recipe for target ' build/learner.o' failed mingw32-make: *** [build/learner.o] Error 1

I have installed tdm-gcc and ticked the OpenMP option.

Can you please help? 

Thanks,
Minyu

**Comment by Bolaka** [comment]
@redpanda08 Did you make copy a copy of **mingw32-make** under TDM-GCC/bin folder?
![make](https://cloud.githubusercontent.com/assets/1235941/16239563/f6dbf5a6-3802-11e6-8963-738731742146.png)

**Comment by redpanda08** [comment]
Hi Bolaka,

Yes. I can see a copy of  mingw32-make in the folder (see the screenshot below).

Can you please let me know step-by-step exactly what you have done?

Thank you!

![image](https://cloud.githubusercontent.com/assets/7215220/16242623/3994d9f2-37eb-11e6-8d5a-6093c1b94f9d.png)

**Comment by redpanda08** [comment]
This is the actual error that I have received:

![image](https://cloud.githubusercontent.com/assets/7215220/16242724/bf14a7d8-37eb-11e6-9266-e3e4185fdb40.png)

**Comment by thirdwing** [comment]
What do you have in PATH environment variable?

**Comment by redpanda08** [comment]
@thirdwing 

Hi,

My path variable is ..\tdm_gcc\bin

**Comment by thirdwing** [comment]
Can you try the absolute path, like "C:/tdm_gcc/bin"?

**Comment by redpanda08** [comment]
@thirdwing I have tried the absolute path. The error message returned is the same as before :(

**Comment by redpanda08** [comment]
Any ideas how to make this work?
