### ISSUE TITLE
XGBOOST Custom Splitting Criterion

### ISSUE THREAD

**Issue by simonprovost** [dmlc/xgboost#9550]
Dear Authors,

Is there a way to custom the split criterion of trees? IF not, where should we start digging down after forking XGBOOST please? Is it Python based ? or Cython based?

Cheers,

**Comment by trivialfis** [comment]
It's c++/cuda based. https://github.com/dmlc/xgboost/blob/master/src/tree/split_evaluator.h

**Comment by simonprovost** [comment]
Superb! Cheers for the promptness, will update later if ever we do struggle with something but after a skim-read it looks very-doable!

Have a great day, thanks again!
