### ISSUE TITLE
libxgboost4j.dylib can support macOS Catalina version=10.15.7?

### ISSUE THREAD

**Issue by hanfengatonline** [dmlc/xgboost#9563]
Hi guys,I run the xgboost4j-spark_2.12:1.7.6 on my mac (macOS Catalina version=10.15.7),when i NativeLibLoader.initXGBoost(); here come the "java.lang.UnsatisfiedLinkError: /private/var/folders/6q/0gvrc70n05d7zq13jmmmd4180000gp/T/libxgboost4j2931869458125363367.dylib: dlopen(/private/var/folders/6q/0gvrc70n05d7zq13jmmmd4180000gp/T/libxgboost4j2931869458125363367.dylib, 1): Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv
  Referenced from: /private/var/folders/6q/0gvrc70n05d7zq13jmmmd4180000gp/T/libxgboost4j2931869458125363367.dylib (which was built for Mac OS X 13.0)
  Expected in: /usr/lib/libc++.1.dylib
", is the mac system versoin not support libxgboost4j2931869458125363367.dylib, thanks for reply！

**Comment by hcho3** [comment]
It seems that libxgboost4j.so is built with MacOS Ventura, and it's using a C++ function that's not available in earlier versions of MacOS. I opened #9569 to keep track of the issue.

**Comment by hanfengatonline** [comment]
thanks, linux is ok
@hcho3
