### ISSUE TITLE
[CI] Set up CI for Intel/M1 Macs on GitHub Actions

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#9569]
The current setup leaves a lot to be desired:
* I have to use my personal laptop (Macbook Pro 2019, Intel) to manually build libxgboost4j.so. Since the laptop is running MacOS Ventura, the resulting binary may use APIs that aren't available on older MacOS. See https://github.com/dmlc/xgboost/issues/9563.
* Users of Apple Silicon (M1/M2) are left to build the JVM package from the source, which is not entirely straightforward.

Proposal
* Set up GitHub Actions to build libxgboost4j.so for Intel Mac.
* ~Use MacStadium to build libxgboost4j.So for Apple Silicon. It will require 89 USD/month. Let's ask users if they are willing to provide the extra funding.~
* NEW: Use GitHub Actions to set up CI for M1 Mac. Note that this is not free. Calculation for the estimated cost is provided below.

**Comment by hcho3** [comment]
Opened #9570 to request for funding.

**Comment by hcho3** [comment]
To set up CI for M1 macs, we need to subscribe to GitHub Teams plan for organization. The plan charges $ 4 per organization member. Enabling this plan for the DMLC organization would be very expensive, as the org has more than 200 members.

So to save costs, we'd need to create a separate org and create a mirror repo that mirrors the XGBoost repo.

**Comment by zupo** [comment]
You don't need to subscribe to GitHub Teams plan. Write to support. https://github.com/OceanSprint uses `macos-latest-xlarge` paid runners, but we don't pay for Teams plan.

**Comment by hcho3** [comment]
@zupo Thanks for the pointer. For now, we decided to purchase a Mac mini to run CI jobs and thus won't be needing paid runners.
