### ISSUE TITLE
XGboost train gives different models on macOS M1 and linux x86 (rounding issues)

### ISSUE THREAD

**Issue by hbraux** [dmlc/xgboost#9584]
**_How to reproduce_**

Install following dependencies with conda
```
name: xgboost
dependencies:
  - python=3.10
  - numpy
  - pandas
  - xgboost
```

Run this python code
```
import numpy as np
import xgboost as xgb
import pandas as pd
import os
from xgboost import XGBClassifier
np.random.seed(1) # set seed
data = pd.DataFrame(np.random.uniform(0, 1, size=(1000, 10)), columns=list('ABCDEFGHIJ'))
labels = pd.DataFrame(np.random.randint(0, 2, size=(1000, 1)))
model = xgb.train({"max_depth": 10, "objective": "binary:logistic"}, xgb.DMatrix(data, labels), 10)
model.dump_model("/tmp/xgb.txt")
os.system("cksum /tmp/xgb.txt")
```

Results:
* on Linux-amd86 or (Docker) Linux-arm64 : 2890519757 63052
* on Darwin-arm64: 2605054718 63053

Some differences in output files:
```
604c604
< 										126:leaf=-0.121010035
---
> 										126:leaf=-0.121010028
687c687
< 										144:leaf=-0.00315875001
---
> 										144:leaf=-0.00315874931
870c870
< 										188:leaf=0.018444676
---
> 										188:leaf=0.0184446722
1011c1011
< 										130:leaf=0.118573852
---
> 										130:leaf=0.118573859
1015c1015
< 										131:leaf=-0.00310669467
..
```

As a consequence, the predict gives different results on a mac laptop and in the CI, and the unit tests prepared on Mac fail in CI.

**Comment by trivialfis** [comment]
That's not unexpected, given different hardware and software environments it's quite easy to have different results with floating points

**Comment by hbraux** [comment]
I don't fully agree and don't find any clue showing that python / numpy  behave differently on different hardware.

**Comment by hcho3** [comment]
GCC and Clang handle floating points differently. For example, see https://stackoverflow.com/questions/49471943/floating-point-arithmetic-varies-between-g-and-clang.

Currently, we use GCC for the Linux binary and Apple Clang for the MacOS binary.

**Comment by hbraux** [comment]
I understand. Thank you.
