### ISSUE TITLE
Proposal: adding a section in the documentation for privacy-preserving XGBoost

### ISSUE THREAD

**Issue by bcm-at-zama** [dmlc/xgboost#9598]
Hello XGBoost community, and congratulations for what you are building, it's awesome.

We at [Zama](https://www.zama.ai) are working on making a privacy-preserving ML open source library, providing the same kind of APIs than sklearn, torch, or... XGBoost, with the important difference that data are encrypted through the whole inference process, i.e., never decrypted. It's possible, thanks to so-called Fully Homomorphic Encryption. Our library is called [Concrete ML](https://github.com/zama-ai/concrete-ml). 

Of course, we have an XGB implementation working over encrypted data, see eg [this example](https://github.com/zama-ai/concrete-ml/blob/main/docs/advanced_examples/XGBClassifier.ipynb). We have also deployed it in an [Hugging Face Space](https://huggingface.co/spaces/zama-fhe/encrypted_sentiment_analysis).

The reason to make this issue was to ask you if we could add a link to our project in your documentation. Maybe over a new "Privacy Preserving Prediction",  below the current [Prediction](https://xgboost.readthedocs.io/en/stable/prediction.html), or some other place you would tell me? The goal is to increase the visibility of the library, and encourage more users to go for privacy-preserving solutions, which is a must for some sensible data. 

If you're good with it, I can prepare some PR. Thank you.

**Comment by trivialfis** [comment]
cc @rongou

**Comment by rongou** [comment]
I think so far the documentation is mostly about features in XGBoost itself. There are tons of external integration points that we can't possibly cover. That being said, I'm ok with adding a pointer to your work, something along the line of "for privacy preserving prediction, see Concrete ML". Probably shouldn't add a complete example, as it could quickly go out of date.

We are also looking at FHE for federated learning, especially with GPU acceleration (see [blog post](https://developer.nvidia.com/blog/accelerated-encrypted-execution-of-general-purpose-applications/)).

**Comment by bcm-at-zama** [comment]
Great, thanks a lot. So, should I make a PR (you would tell me where to add the few new lines) or I let you take care of everything? I think the links https://github.com/zama-ai/concrete-ml/blob/main/docs/advanced_examples/XGBClassifier.ipynb and https://github.com/zama-ai/concrete-ml/blob/main/docs/advanced_examples/XGBRegressor.ipynb will be permanent, or you have https://docs.zama.ai/concrete-ml/built-in-models/tree. 

Anyway: thanks a lot for consideration and quick answer, I'm always amazed by open-source community

**Comment by rongou** [comment]
A PR would work. Do you have some kind of landing page to provide a high level overview?

**Comment by bcm-at-zama** [comment]
Sure, let me prepare a PR. Which file to you want me to modify / where should I add the links, please? 

For the landing page, I was thinking about:
- our GitHub: https://github.com/zama-ai/concrete-ml
- our documentation: https://docs.zama.ai/concrete-ml
but if you want to precisely link to somewhere speaking about XGB, the previously cited examples would make sense as well.

**Comment by rongou** [comment]
Probably this file: https://github.com/dmlc/xgboost/blob/master/doc/prediction.rst

The docs page should be good.

**Comment by trivialfis** [comment]
Let's add the document to the `doc/tutorials/` instead. ;-)

**Comment by bcm-at-zama** [comment]
Hello @rongou. Yes, done in #9604, thanks.

**Comment by bcm-at-zama** [comment]
Regarding your other proposal @trivialfis, if you propose us to have a Concrete ML example in doc/tutorials/ and @rongou is fine with it, of course, we will! Tell us, thank you

**Comment by trivialfis** [comment]
I thought you wanted to add a full tutorial for using it. But if that's a brief introduction with links to your repository for more info, then the current PR is fine.

**Comment by bcm-at-zama** [comment]
@trivialfis : actually, it's also an excellent suggestion, and my colleague https://github.com/jfrery told me he volunteered to do such a tutorial. It will come, in another PR than #9604

**Comment by trivialfis** [comment]
Hi, both PRs are now merged, thank you for the nice work! Is there anything else XGBoost needs to do?

**Comment by bcm-at-zama** [comment]
Hello @trivialfis . Yes, we'll close this issue with https://github.com/dmlc/xgboost/pull/9614. We just missed to add the new tutorial in the index. Cheers
