### ISSUE TITLE
typo in the arxiv paper

### ISSUE THREAD

**Issue by udibr** [dmlc/xgboost#960]
Thank you for the epic paper!
"apware" should be "aware"

**Comment by Sandy4321** [comment]
But where is link to paper and title

**Comment by udibr** [comment]
sorry, http://arxiv.org/pdf/1603.02754v1.pdf

**Comment by tqchen** [comment]
Thanks for the catch! The paper is still in submission, so we will be update the preprint together with the feedbacks in a few month
