### ISSUE TITLE
doctests failing with new version of xgboost

### ISSUE THREAD

**Issue by rohan472000** [dmlc/xgboost#9606]
**Problem description:**

The doctest for the main() function in the [xgboost_regressor.py
](https://github.com/TheAlgorithms/Python/blob/master/machine_learning/xgboost_regressor.py) is failing. The expected outputs are not the same as the actual outputs.

**Steps to reproduce the problem:**

- Clone the [Repo](https://github.com/TheAlgorithms/Python) repository from GitHub.
- Navigate to the `machine_learning/xgboost_regressor.py` directory.
- Run the .py file with latest version of xgboost.

**Expected output:**

      Mean Absolute Error : 0.30957163379906033
      Mean Square Error  : 0.22611560196662744

**Actual output:**

     Mean Absolute Error : 0.3089678116585885
     Mean Square Error  : 0.21783275170643127

couple of more doctest are failing, which i didn't mentioned here, you can find out by running that .py file.

I have tried using latest version of XGBoost as it was correct with previous version. I have also tried changing the parameters of the XGBoost model, but this does not resolve the problem.

I believe that this is a bug in the XGBoost code. I would appreciate it if you could investigate this issue and come with some solution.

Thank you for your time and consideration.

**Comment by hcho3** [comment]
The default behavior of XGBoost has changed as of 2.0 version. As noted in the [release note](https://github.com/dmlc/xgboost/releases/tag/v2.0.0), XGBoost now uses the `hist` tree method as the default, whereas previously it used `approx` or `exact` methods. The changed behavior is intentional and not a bug.

You have several options to account for the new default:
* Explicitly specify `tree_method="approx"` or `tree_method="exact"` in your doc tests. OR
* Update the doc tests to change the expected outputs.

Are these suggestions reasonable for your use case?

**Comment by hcho3** [comment]
@triviafis I think we also made some changes to the `approx` and `exact` methods. Is it reasonable to expect the identical outputs for the revised `approx` and `exact`?

**Comment by hcho3** [comment]
Update. I just tried running the doctest and it looks like setting `tree_method` explicitly doesn't fix the doctest.

**Comment by rohan472000** [comment]
> Update. I just tried running the doctest and it looks like setting `tree_method` explicitly doesn't fix the doctest.

Yeah

**Comment by hcho3** [comment]
Update: I had to add one more parameter to make the test pass:
```python
xgb = XGBRegressor(verbosity=0, random_state=42, tree_method="exact", base_score=0.5)
```
@rohan472000 

Explanation: The defaults for `tree_method` and `base_score` have changed. For explanation about `base_score`, see the `Automatically estimated intercept` section of [the release note](https://github.com/dmlc/xgboost/releases/tag/v2.0.0).

**Comment by rohan472000** [comment]
@hcho3 ok...I'm checking with base_score=0.5

**Comment by rohan472000** [comment]
Thanks @hcho3 , its working.
