### ISSUE TITLE
[CI] Failing tests are not reported accordingly on Windows.

### ISSUE THREAD

**Issue by trivialfis** [dmlc/xgboost#9618]
https://buildkite.com/xgboost/xgboost-ci-windows/builds/3566#018adc46-b6b7-423a-937c-4f35bbb67575

**Comment by hcho3** [comment]
I need to study how exit codes work in PowerShell.

**Comment by trivialfis** [comment]
> I need to study how exit codes work in PowerShell.

Or write Python instead. ;-)
