### ISSUE TITLE
XGBoost not aware of CPU limit set by cgroups v2 

### ISSUE THREAD

**Issue by zhegata** [dmlc/xgboost#9622]
When running XGBoost in a containerized environment, where cgroups **v1** is used, the library is correctly aware of the CPU limits set by the cgroup and spawns the appropriate amount of threads to do its calculations.

But when running in an environment where cgroups **v2** is used, XGBoost no longer recognized the limits. Instead, it's using the host machine's core count as a reference for how many threads to spawn. This almost definitely results in needless context switching. In one of our cases, we are seeing about ~300 times slower processing.

I believe this is the code that does not work with the new cgroups API: https://github.com/dmlc/xgboost/blob/4d7a187cb0ebc2194abc1efe0aaee6f06af937c5/src/common/threading_utils.cc#L34-L35

As a comparison, in a simple python:3.11-based container running in the cgroups-v2-environment, the "/sys/fs/cgroup" structure looks like this (I've removed the non-cpu "files" for readability):
```
/sys/fs/cgroup/cpu.idle
/sys/fs/cgroup/cpu.max
/sys/fs/cgroup/cpu.max.burst
/sys/fs/cgroup/cpu.pressure
/sys/fs/cgroup/cpu.stat
/sys/fs/cgroup/cpu.uclamp.max
/sys/fs/cgroup/cpu.uclamp.min
/sys/fs/cgroup/cpu.weight
/sys/fs/cgroup/cpu.weight.nice
/sys/fs/cgroup/cpuset.cpus
/sys/fs/cgroup/cpuset.cpus.effective
/sys/fs/cgroup/cpuset.cpus.partition
/sys/fs/cgroup/cpuset.mems
/sys/fs/cgroup/cpuset.mems.effective
```

For now, we have solved our issue by manually setting the OMP_NUM_THREADS and OMP_THREAD_LIMIT environment variables to the number of threads appropriate for our use case. But it would be nice if XGBoost can once again handle this on its own.

**Comment by trivialfis** [comment]
Could you please share how you use cgroup? What specific commands/system calls are you using to construct the subgroup?

**Comment by zhegata** [comment]
Our processes are running in Kubernetes v1.25.11 with **containerd** as container runtime and **systemd** as the cgroup driver. We use the resource limit feature that Kubernetes provides out of the box, so the cgroups are constructed by the container runtime.

As additional context - we recently upgraded our Kubernetes cluster to v1.25, which brought the cgroups v2 as a default setting. Kubernetes v1.24 and below are using cgroups v1 by default.

**Comment by trivialfis** [comment]
Hi, could you please help review https://github.com/dmlc/xgboost/pull/9651 ?
