### ISSUE TITLE
xgboost register objective macro

### ISSUE THREAD

**Issue by karl-gardner** [dmlc/xgboost#9627]
I have been digging through the source code and came across the XGBOOST_REGISTER_OBJECTIVE macro in objective.h:

https://github.com/dmlc/xgboost/blob/4d7a187cb0ebc2194abc1efe0aaee6f06af937c5/include/xgboost/objective.h#L154
 
and wondering what the purpose of this macro is? Is this to basically register a new loss object on the heap dynamically with new? Since the macro is used in combination with the .set_body() function it seems like this creates a new Objective function object (inheriting from ObjFunction) dynamically on the heap with new. Thanks in advance!

**Comment by trivialfis** [comment]
It's a factory method, give it the name of the objective and the function to create it, you can call `ObjFunction::Create` with the name afterward.

**Comment by trivialfis** [comment]
Feel free to reopen if there are further questions.
