### ISSUE TITLE
Customize objective function in XGBoost

### ISSUE THREAD

**Issue by fangwenji** [dmlc/xgboost#9629]
Hi, I'm currently trying to modify the objective function used for the regression task in XGBoost. I would like to ask how can I customize the objective function to deal with a sample with multiple feature vectors, for example, to calculate the average or max of the model output from three features as the final prediction.

I implemented a demo as follows:

```
def custom_objective(y_pred, y_true):
    # How can I get the average or maybe max of the model output of the three input features? 
    ... ... 
    return gradient, hessian 

# Example data: 100 samples, 3 feature vectors each of size 5
X = np.random.randn(100, 3 * 5)
y = np.random.randn(100)

parameters = {"objective": custom_objective,
              "n_estimators": 100,
              "eta": 0.3,
              "lambda": 1,
              "gamma": 0,
              "max_depth": None,
              "verbosity": 2}

    
model = xgb.XGBRegressor(**parameters)
model.fit(X, y)
```

Thank you so much for your time!

**Comment by trivialfis** [comment]
Feel free to reopen if there are further questions.
