### ISSUE TITLE
error : xgboost.core.XGBoostError: std::bad_alloc

### ISSUE THREAD

**Issue by recallee** [dmlc/xgboost#963]
my libsvm is : 
0 0:10004 300005:1 502898:1 1000010:1 1100005:1 1201681:1 1300069:1 1400050:1 1500158:1 15:5 16:26210 17:590 18:92 19:92 20:92 21:92 22:50 23:1237 24:4 25:113 29:0.37210010351594774 30:162 31:0 32:110 33:323 34:0 35:9 36:0 3800000:1 3900000:1 4000000:1 4100000:1 4200010:1 4300005:1 4401681:1 4500069:1 4600050:1 4702898:1 47:5 48:2334 49:714 51:91 52:91 53:91 54:92 55:50 56:0 57:0 58:34 59:32.037138791474284 62:0.5883996493038575 63:4123 64:37 65:0.008974048023284017 66:0 67:0.0 79:2.0 80:5.95553018657 81:8.0 82:0.0 83:54.0 84:1.0 85:0 9000016:1 9100002:1 4177197833204390623:1 9300000:1

**Comment by tqchen** [comment]
XGBoost do requires you to remap the sparse features to compact indices, so index like 4177197833204390623 will blow up the memory
