### ISSUE TITLE
Demo for C-API

### ISSUE THREAD

**Issue by karl-gardner** [dmlc/xgboost#9632]
I have recently built the newest version of xgboost from source with intention to use the c-api. I used the following commands as in the documentation (https://xgboost.readthedocs.io/en/stable/build.html#building-on-linux-and-other-unix-like-systems):

cd xgboost
mkdir build
cd build
cmake ..
make -j$(nproc)

These commands build the makefile and run make to compile the shared object library in xgboost/lib/libxgboost.so. Now, I am checking out the demo for the c-api in xgboost/demo/c-api and it uses a CMakeLists.txt file to run a demo with the c-api. However, running the cmake -S . -B build will give me an error and not find the library with find_package(). I am looking at the submodules in c-api/basic and in the CMakeLists their it says "xgboost is built as static libraries, all cxx dependencies need to be linked into the executable" inside of a comment. Thus, it is saying it is a static library (.a file) and not a dynamic library (libxgboost.xo) as I have built. Is this demo for a previous version and not up to date since it is saying it is a static library?

Thanks,

Karl

**Comment by trivialfis** [comment]
After building XGBoost, you need to run `make install` to install all relevant files into a common path. Examples are: `/usr/`, `/home/my-home/.local`, or `~/.anaconda/envs/my-env`. Otherwise, CMake doesn't know where to look for XGBoost in your project. See https://cmake.org/cmake/help/v3.0/variable/CMAKE_PREFIX_PATH.html .

**Comment by karl-gardner** [comment]
Hello trivialfis,

Thanks for the response. I ended up seeing this in the "C API Tutorial" section of the documentation and got it to work. However, in the "Building from source" section in the documentation it doesn't actually say to install. Anyways, got it to work!

Karl Gardner

**Comment by trivialfis** [comment]
It's more a system-specific behavior, if you were using Windows then I don't know how to get shared library work. XGBoost won't make specific suggestion, you need to search for terms like "how to find shared library on Linux with CMake" instead of "how to find XGBoost".
