### ISSUE TITLE
Compiler Warning when Creating DMatrix from 2D array

### ISSUE THREAD

**Issue by karl-gardner** [dmlc/xgboost#9639]
Hello, I am trying to create a DMatrix from a 2D array in the c-api as in the tutorials with XGDMatrixCreateFromMat: https://xgboost.readthedocs.io/en/stable/tutorials/c_api_tutorial.html#sample-examples-along-with-code-snippet-to-use-c-api-functions

and I am getting a warning. Here I give the source code and the warning/error. 

demo.c:

```
#include <stdio.h>
#include <stdlib.h>
#include <xgboost/c_api.h>

#define safe_xgboost(call) {                                            \
int err = (call);                                                       \
if (err != 0) {                                                         \
  fprintf(stderr, "%s:%d: error in %s: %s\n", __FILE__, __LINE__, #call, XGBGetLastError()); \
  exit(1);                                                              \
}                                                                       \
}

int main(int argc, char** argv) {

    const float data[6][3] = { {1, 2, 3}, {2, 4, 6}, {3, -1, 9}, {4, 8, -1}, {2, 5, 1}, {0, 1, 5} };
    DMatrixHandle dmatrix;
    safe_xgboost(XGDMatrixCreateFromMat(data, 6, 3, -1, &dmatrix));
     return 0;
}
```

Compiler Warning:

/home/karl_gardner/c_api_test/demo.c:17:37: warning: passing argument 1 of ‘XGDMatrixCreateFromMat’ from incompatible pointer type [-Wincompatible-pointer-types]
   17 | safe_xgboost(XGDMatrixCreateFromMat(data, 6, 3, -1, &dmatrix));
      |                                     ^~~~
      |                                     |
      |                                     const float (*)[3]
/home/karl_gardner/c_api_test/demo.c:6:12: note: in definition of macro ‘safe_xgboost’
    6 | int err = (call);                                                       \
      |            ^~~~
In file included from /home/karl_gardner/c_api_test/demo.c:3:
/usr/local/include/xgboost/c_api.h:227:49: note: expected ‘const float *’ but argument is of type ‘const float (*)[3]’
  227 | XGB_DLL int XGDMatrixCreateFromMat(const float *data,

It seems as if the 2D matrix is an array of pointers and their is a warning that the function accepts just a pointer. Will this be ok to run the program?

Thanks,

Karl Gardner

**Comment by trivialfis** [comment]
You have created a 2-dim C array using `[6][3]`. Instead of this, you should use 1-dim memory buffer `[6 * 3]`. Please consider taking a look into how numpy does array indexing.

**Comment by trivialfis** [comment]
Feel free to reopen if there are further questions.
