### ISSUE TITLE
column_matrix.h included by .cu files

### ISSUE THREAD

**Issue by hliuca** [dmlc/xgboost#9662]
It looks column_matrix.h is for CPU. In this file, there is function,

/** @brief Set the i^th element to be a valid element (instead of missing). */
    void SetValid(typename LBitField32::index_type i) { missing.Clear(i); }

This function is a host function. When column_matrix.h is included by a .cu file, this host function, SetValid, will call a device version function, missing.Clear.

Not sure if my understanding is correct. Thanks.

**Comment by trivialfis** [comment]
There are interpolations between CPU and GPU data structures so that XGBoost can use CPU with GPU inputs and vice versa.

**Comment by hliuca** [comment]
Thanks.
