### ISSUE TITLE
error building on mac,  'omp.h' file not found with <angled> include

### ISSUE THREAD

**Issue by reneix** [dmlc/xgboost#9663]
I'm building xgboost from source on mac 10.15, getting error:  'omp.h' file not found with <angled> include
I think error caused by not finding omp.h from installation dir, but adding CFLAGS="-I/opt/local/include/libomp"  not work
there is omp.h in /opt/local/include/libomp
please help, thanks

system: 10.15, install openmp from macport(brew not support 10.15 anymore)
xgboost: 2.0.0
dmlc-core:0.6.0
command: make CFLAGS="-I/opt/local/include/libomp" 

(base) zhaochao@zhaochaodeMacBook-Pro build % make CFLAGS="-I/opt/local/include/libomp" 
Consolidate compiler generated dependencies of target dmlc
[  1%] Building CXX object dmlc-core/CMakeFiles/dmlc.dir/src/data.cc.o
In file included from /Users/zhaochao/Downloads/xgboost-2.0.0/dmlc-core/src/data.cc:12:
In file included from /Users/zhaochao/Downloads/xgboost-2.0.0/dmlc-core/src/data/disk_row_iter.h:19:
In file included from /Users/zhaochao/Downloads/xgboost-2.0.0/dmlc-core/src/data/./libsvm_parser.h:19:
In file included from /Users/zhaochao/Downloads/xgboost-2.0.0/dmlc-core/src/data/./text_parser.h:11:
/Users/zhaochao/Downloads/xgboost-2.0.0/dmlc-core/include/dmlc/omp.h:11:10: error: 'omp.h' file not found with
      <angled> include; use "quotes" instead
#include <omp.h>
         ^~~~~~~
         "omp.h"
In file included from /Users/zhaochao/Downloads/xgboost-2.0.0/dmlc-core/src/data.cc:12:
In file included from /Users/zhaochao/Downloads/xgboost-2.0.0/dmlc-core/src/data/disk_row_iter.h:19:
In file included from /Users/zhaochao/Downloads/xgboost-2.0.0/dmlc-core/src/data/./libsvm_parser.h:19:
/Users/zhaochao/Downloads/xgboost-2.0.0/dmlc-core/src/data/./text_parser.h:33:30: error: use of undeclared identifier
      'omp_get_num_procs'
    int maxthread = std::max(omp_get_num_procs() / 2 - 4, 1);
                             ^
/Users/zhaochao/Downloads/xgboost-2.0.0/dmlc-core/src/data/./text_parser.h:114:17: error: use of undeclared
      identifier 'omp_get_max_threads'
  int nthread = omp_get_max_threads();
                ^
3 errors generated.
make[2]: *** [dmlc-core/CMakeFiles/dmlc.dir/src/data.cc.o] Error 1
make[1]: *** [dmlc-core/CMakeFiles/dmlc.dir/all] Error 2
make: *** [all] Error 2

**Comment by hcho3** [comment]
XGBoost is currently tested with Homebrew but not with Macports. Are you able to upgrade to MacOS 12?

**Comment by reneix** [comment]
I'm afraid not ... will try brew first, thanks
