### ISSUE TITLE
xgboost/jvm-packages mvn build fail

### ISSUE THREAD

**Issue by vienous** [dmlc/xgboost#9669]
code : release_2.0.0
os : CentOS Linux release 7.6.1810 (Core) 
cmake:  3.18.2
gcc : gcc version 8.3.1 20190311 (Red Hat 8.3.1-3) (GCC) 

<img width="1899" alt="image" src="https://github.com/dmlc/xgboost/assets/16508257/23cd9bfd-697a-4647-8603-7236c5efe5a0">

<img width="1534" alt="image" src="https://github.com/dmlc/xgboost/assets/16508257/91474be0-c547-4d54-a59e-678504de3dcd">

**Comment by hcho3** [comment]
I am not able to reproduce the issue with the Docker image `centos:centos7`. How did you install GCC 8? I tried using devtoolset-8 and XGBoost built successfully.

**Comment by hcho3** [comment]
Never mind, the build fails with `release_2.0.0` branch. (I was using `master` branch earlier.) Let me fix it.

**Comment by hcho3** [comment]
@vienous Can you try using the patch in #9670 ?

**Comment by vienous** [comment]
> I am not able to reproduce the issue with the Docker image `centos:centos7`. How did you install GCC 8? I tried using devtoolset-8 and XGBoost built successfully.
i change gcc to  : gcc version 9.3.1 20200408 (Red Hat 9.3.1-2) (GCC) , then build success
