### ISSUE TITLE
is_categorical_dtype(dtype) errors from xgboost

### ISSUE THREAD

**Issue by mlauronen** [dmlc/xgboost#9672]
I am using stable xgboost 2.0 in Python 3.9 and getting deprecation future and user warnings from 
- xgboost/data.py
- xgboost/core.py 

---------------------------------------------------------------------------------------------------------------

/home/mika/Data/Trading/devel/tests/keras/.venv/lib/python3.9/site-packages/xgboost/data.py:335: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check isinstance(dtype, pd.SparseDtype) instead.
if is_sparse(dtype):
/home/mika/Data/Trading/devel/tests/keras/.venv/lib/python3.9/site-packages/xgboost/data.py:338: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
is_categorical_dtype(dtype) or is_pa_ext_categorical_dtype(dtype)
/home/mika/Data/Trading/devel/tests/keras/.venv/lib/python3.9/site-packages/xgboost/data.py:384: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
if is_categorical_dtype(dtype):
/home/mika/Data/Trading/devel/tests/keras/.venv/lib/python3.9/site-packages/xgboost/data.py:359: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
return is_int or is_bool or is_float or is_categorical_dtype(dtype)
/home/mika/Data/Trading/devel/tests/keras/.venv/lib/python3.9/site-packages/xgboost/data.py:520: FutureWrning: is_sparse is deprecated and will be removed in a future version. Check isinstance(dtype, pd.SparseDtype) instead.
if is_sparse(data):
/home/mika/Data/Trading/devel/tests/keras/.venv/lib/python3.9/site-packages/xgboost/core.py:160: UserWarning: [15:48:59] WARNING: /workspace/src/objective/regression_obj.cu:209: reg:linear is now deprecated in favor of reg:squarederror.
warnings.warn(smsg, UserWarning)
/home/mika/Data/Trading/devel/tests/keras/.venv/lib/python3.9/site-packages/xgboost/data.py:335: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check isinstance(dtype, pd.SparseDtype) instead.
if is_sparse(dtype):
/home/mika/Data/Trading/devel/tests/keras/.venv/lib/python3.9/site-packages/xgboost/data.py:338: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
is_categorical_dtype(dtype) or is_pa_ext_categorical_dtype(dtype)
/home/mika/Data/Trading/devel/tests/keras/.venv/lib/python3.9/site-packages/xgboost/data.py:384: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
if is_categorical_dtype(dtype):
/home/mika/Data/Trading/devel/tests/keras/.venv/lib/python3.9/site-packages/xgboost/data.py:359: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
return is_int or is_bool or is_float or is_categorical_dtype(dtype)

---------------------------------------------------------------------------------------------------------------

**Comment by hcho3** [comment]
We are working on patch release 2.0.1 that will fix the warning. Stay tuned

**Comment by trivialfis** [comment]
This has been fixed by https://github.com/dmlc/xgboost/pull/9557 , we will make a new patch release once the build issue on macos is sorted out.
