### ISSUE TITLE
zsh: floating point exception (core dumped)

### ISSUE THREAD

**Issue by StudyingLover** [dmlc/xgboost#9690]
I run my demo ,but meet a mistake `zsh: floating point exception (core dumped)`

Because my code and data involve confidential projects in the laboratory, so I cannot provide reproducible data and code now. If it is necessary , plesse inform me .

Besides , I write a demo , there is no issue.
```
import xgboost
import numpy as np
from scipy import stats

np.random.seed(114514)
X = np.random.randn(100, 3)  
y = stats.bernoulli.rvs(0.5, size=100)  

params = {
    "device": "cuda"
}

Xy = xgboost.DMatrix(X, y)

model = xgboost.train(params, Xy)

test_array = np.random.randn(1, 3)
dtest = xgboost.DMatrix(test_array)
pred = model.predict(dtest)
print(pred)
```

**Comment by trivialfis** [comment]
> If it is necessary , plesse inform me

We need a way to reproduce the error in order to fix it.
