### ISSUE TITLE
[jvm-packages] Replace JNI with Java Native Access

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#9697]
**Problem**
Currently, XGBoost4J uses Java Native Interface (JNI) to call the native code in `libxgboost4j.so`. JNI has served our needs so far, but its use causes a tight coupling with the particular JDK that XGBoost4J was built with.

For example, when building XGBoost4J on Mac mini M1, I used Azul JDK 8 (*):
```
$ export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/
$ mkdir build
$ cd build
$ cmake .. -GNinja -DJVM_BINDINGS=ON -DUSE_OPENMP=OFF
```
This leads to a binary that has a hard dependency on `libjvm.dylib`:
```
$ otool -L libxgboost4j.dylib

libxgboost4j.dylib:
        @rpath/libxgboost4j.dylib (compatibility version 0.0.0, current version 0.0.0)
        @rpath/libjvm.dylib (compatibility version 1.0.0, current version 1.0.0)
        /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1500.65.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.100.3)
```

As a result, when I try to load the binary on another MacOS machine without Azul JDK 8, the import fails with an error:
```
$ java -version   # This machine has OpenJDK 21
openjdk version "21" 2023-09-19
OpenJDK Runtime Environment Homebrew (build 21)
$ python -c "import ctypes; ctypes.cdll.LoadLibrary('./libxgboost4j.dylib')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/phcho/mambaforge/lib/python3.10/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/Users/phcho/mambaforge/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(./libxgboost4j.dylib, 0x0006): Library not loaded: @rpath/libjvm.dylib
Reason: tried: '/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/jre/lib/server/libjvm.dylib' (no such file)  ...
```
The error message suggests a tight coupling of XGBoost4J with a particular JDK. **The coupling makes it difficult for us to distribute pre-built binaries targeting the MacOS Apple Silicon platform.** Users may have installed Azul JDK 8 (whose support is due to end in 2026), OpenJDK 11, or OpenJDK 21 (the latest version).

**Proposal**. Replace JNI with [Java Native Access (JNA)](https://github.com/java-native-access/jna). JNA works like `ctypes` in Python, so we would be able to call functions directly from `libxgboost.so`. JNA is used by many java software such as IntelliJ IDEA, and it is tested with multiple versions of JDK and platforms. The removal of JNI stub code will also reduce the boilerplate in the code base.

**Alternatives**. We can tell users to install a particular JDK as we have done so far. So for example, users of MacOS Apple Silicon will be asked to install Azul JDK 8.

@trivialfis  @wbo4958 @WeichenXu123 @Craigacp @drnguyen @terrytangyuan Your feedback will be highly appreciated.

(*) OpenJDK 8 supports Intel only and is not available for Apple Silicon.

**Comment by Craigacp** [comment]
I think that error is something we could fix by changing how it's compiled. There are plenty of other native libraries which don't have that issue (e.g. ONNX Runtime's Java API), so it's definitely fixable.

From the benchmarks I've seen (e.g. https://github.com/zakgof/java-native-benchmark) JNA is substantially slower than JNI as it's more dynamic. Java 22 introduces a new FFI which is comparable in speed to JNI and much easier to use, that's going to be the future of these things so moving an existing JNI binding to something else that isn't the new FFI seems suboptimal.

**Comment by hcho3** [comment]
@Craigacp I am currently trying to set up a CI/CD pipeline for M1-native XGBoost4J binaries. Can you give me any points for building native libs without such tight coupling with a particular JDK?

>  Java 22 introduces a new FFI which is comparable in speed to JNI and much easier to use

That's great to hear!

**Comment by hcho3** [comment]
Interesting, there is no need for linking `libjvm.so` or `libawt.dylib`, according to https://github.com/microsoft/onnxruntime/pull/2873

**Comment by terrytangyuan** [comment]
If other projects can use JNI without issues, we should stick with it.

**Comment by hcho3** [comment]
@Craigacp Just filed https://github.com/dmlc/xgboost/pull/9698 to remove the dependency on libjvm.

**Comment by Craigacp** [comment]
It's been fine in ONNX Runtime for years so I would expect it to cause trouble here unless there's something very odd in how xgboost4j works it'll be good. As you can see from the other issue cmake and jni have a rather complicated interaction at times and it can be pretty system specific.

**Comment by hcho3** [comment]
@Craigacp Thanks to your input, we were able to release XGBoost 2.0.1 with native support for Apple Silicon. Thank you!

**Comment by Craigacp** [comment]
@hcho3 Happy to help. I hit the same issue with it tightly linking to the JDK a few weeks ago when onboarding someone new with an Apple Silicon laptop, but I didn't have time to run it down. I'm glad you got it all working, the new release will be very helpful.
