### ISSUE TITLE
[R] xgb.plot.tree in the CRAN version is broken

### ISSUE THREAD

**Issue by thirdwing** [dmlc/xgboost#970]
@hetong007 Please upload the latest version to CRAN.

**Comment by hetong007** [comment]
Do you mean the latest version on Github? I think it is not ready for cran, according to:

- http://win-builder.r-project.org/QBz8X1l3K38V/00check.log
- http://win-builder.r-project.org/3yqlR2XPps1a/00check.log

Issues are mainly from vignette and visualization part.

**Comment by thirdwing** [comment]
I mean the CRAN version is broken.

```
> install.packages("xgboost", repos="https://cran.rstudio.com")
> require(xgboost)
Loading required package: xgboost
> data(agaricus.train, package='xgboost')
> data(agaricus.test, package='xgboost')
> train <- agaricus.train
> test <- agaricus.test
> bst <- xgboost(data = train$data, label = train$label, max.depth = 2,
+ eta = 1, nthread = 2, nround = 2, objective = "binary:logistic")
[0]	train-error:0.046522
[1]	train-error:0.022263
> xgb.plot.tree(feature_names = agaricus.train$data@Dimnames[[2]], model = bst)
Error in as.character(tools:::httpdPort) : 
  cannot coerce type 'closure' to vector of type 'character'
```

**Comment by hetong007** [comment]
I see.

@pommedeterresautee , can you please check the issue? It seems the function `xgb.plot.tree` has been modified a while ago, so it is a bit difficult for me to track the changes and compare the code.

**Comment by thirdwing** [comment]
The latest version works well and I have upload a new drat version.

**Comment by pommedeterresautee** [comment]
@hetong007 The Cran version uses old code for old version of the lib used to display trees.
It has been rewritten since for the last version of the viz lib.
I am not aware of issues on the Github version of Xgboost.

If any, let me know.

Kind regards,
Michaël

**Comment by thirdwing** [comment]
The github version works well, so we need to let it pass `R CMD check` soon.

**Comment by tqchen** [comment]
@thirdwing Are you suggesting we should try a CRAN submit? Last time I checked I managed to fixed all the c++ side problems

**Comment by vinhdizzo** [comment]
Hi, I'm using the CRAN version of xgboost (0.4-3) as of 4/14/2016, and am seeing something like the following displayed when I use `xgb.plot.tree`.  Just wanted to check if this issue is the same reason I'm seeing it:
```
parse error with graph LR;0-0(DataItemID_000380)-->|>= 2.1261e+009|0-2>DataItemID_000023];0-0(DataItemID_000380
Cover: 17661.8
Gain: 454.037)-->|< 2.1261e+009|0-1>DataItemID_001270];0-1(DataItemID_001270)-->|>= 1.55943e+008|0-4>YS_RegAgencyInquiries];0-1(DataItemID_001270
Cover: 17156.8
...
```

That is, I don't see any diagrams, just a bunch of these texts.  I get similar results both on Windows and Linux.  Let me know, thanks!

**Comment by vinhdizzo** [comment]
Hi, I was able to update my xgboost on the the Linux server to the weekly version, and I am now able to see the trees plotted by `xgb.plot.tree`.  Thank you.

**Comment by heroxbd** [comment]
Hitting this bug with CRAN version.   Any updates?
