### ISSUE TITLE
[jvm-packages] JARs for 2.0.0 not published to Maven Central

### ISSUE THREAD

**Issue by marcphilipp** [dmlc/xgboost#9701]
Are the JVM packages going to be published to Maven Central like past releases?

**Comment by trivialfis** [comment]
Yes, we are preparing the 2.0.1 release to address some build failures on macos. Once everything is sorted out, we will publish the maven release.

**Comment by trivialfis** [comment]
Yes, we are preparing the 2.0.1 release to address some build failures on macos. Once everything is sorted out, we will publish the maven release.

**Comment by marcphilipp** [comment]
@trivialfis Thanks for the quick reply! Should we close this issue then?

**Comment by trivialfis** [comment]
@marcphilipp Feel free to reopen if there are further questions.

**Comment by hcho3** [comment]
XGBoost4J is now available on Maven Central: https://repo1.maven.org/maven2/ml/dmlc/xgboost4j_2.12/2.0.1/
