### ISSUE TITLE
sklearn api: XGBRanker categorical error for score

### ISSUE THREAD

**Issue by polidore** [dmlc/xgboost#9718]
If I create an XGBRanker model with `enable_categorical=True`, it will work fine for fit and predict, but if I run score with the same dataset, it will give this error: 

```
ValueError: DataFrame.dtypes for data must be int, float, bool or category. When categorical type is supplied, The experimental DMatrix parameter`enable_categorical` must be set to `True`.  
```

Seems new in XGBoost 2.0

**Comment by trivialfis** [comment]
Hi, is your input dataframe containing categorical data?

**Comment by polidore** [comment]
yes, but it includes categorical data for fit and predict and I don't get
this error there. I have enabled categorical when instantiating the
XGBRanker.

**Comment by trivialfis** [comment]
Thank you for finding that issue, I have opened a PR for the fix: https://github.com/dmlc/xgboost/pull/9753 . It will be part of the next patch release.

**Comment by polidore** [comment]
Thanks!
