### ISSUE TITLE
Handling zero weights in column sampling

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#9733]
In https://discuss.xgboost.ai/t/feature-weights-and-sampling/3410/1, features with zero weights still get sampled by the column sampler.

**Comment by trivialfis** [comment]
It's a weird tradeoff, given 3 features and 0.7 sampling rate, `floor(3 * 0.7) = 2`.  In the given example, the sampling rate is effectively limited to 0.3. How to check the weight being consistent with sampling rate might be more involved.

**Comment by trivialfis** [comment]
I'm not sure if I want to fix this, seems like a user error and an edge case that weight is zero.
