### ISSUE TITLE
[Python] Scikit-learn interface doesn't take categorical `y`

### ISSUE THREAD

**Issue by david-cortes** [dmlc/xgboost#9739]
In current versions of scikit-learn, one can use classes like `LogisticRegression` with a categorical  `y` variable, and the object will then keep account of which classes it had and use them in the outputs:
```python
import numpy as np, pandas as pd
from sklearn.linear_model import LogisticRegression

m = 100
rng = np.random.default_rng(seed=123)
X = pd.DataFrame({
    "col1" : rng.standard_normal(size=m),
    "col2" : rng.standard_gamma(1, size=m),
})
y = pd.Series(
    rng.choice(['a', 'b'], size=m, replace=True)
).astype("category")
model = LogisticRegression().fit(X,y)
model.classes_  
```
```
array(['a', 'b'], dtype=object)
```
```python
model.predict(X[:5])
```
```
array(['b', 'b', 'b', 'a', 'b'], dtype=object)
```

But the scikit-learn interface for xgboost doesn't allow such inputs:
```python
from xgboost import XGBClassifier
xgb_model = XGBClassifier().fit(X,y)
```
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[3], line 2
      1 from xgboost import XGBClassifier
----> 2 xgb_model = XGBClassifier().fit(X,y)

File ~/anaconda3/lib/python3.11/site-packages/xgboost/core.py:620, in require_keyword_args.<locals>.throw_if.<locals>.inner_f(*args, **kwargs)
    618 for k, arg in zip(sig.parameters, args):
    619     kwargs[k] = arg
--> 620 return func(**kwargs)

File ~/anaconda3/lib/python3.11/site-packages/xgboost/sklearn.py:1440, in XGBClassifier.fit(self, X, y, sample_weight, base_margin, eval_set, eval_metric, early_stopping_rounds, verbose, xgb_model, sample_weight_eval_set, base_margin_eval_set, feature_weights, callbacks)
   1435     expected_classes = np.arange(self.n_classes_)
   1436 if (
   1437     self.classes_.shape != expected_classes.shape
   1438     or not (self.classes_ == expected_classes).all()
   1439 ):
-> 1440     raise ValueError(
   1441         f"Invalid classes inferred from unique values of `y`.  "
   1442         f"Expected: {expected_classes}, got {self.classes_}"
   1443     )
   1445 params = self.get_xgb_params()
   1447 if callable(self.objective):

ValueError: Invalid classes inferred from unique values of `y`.  Expected: [0 1], got ['a' 'b']
```

**Comment by trivialfis** [comment]
I can't speak for other people, but we would like to draw a clear line between preprocessing and machine learning. For scikit-learn interface, you need the `LabelEncoder` to handle this type of label, potentially integrating it into a `Pipeline` object to keep your data pipeline consistent across training and testing, for an example of how to use the pipeline to integrate data engineering and ML estimators, see https://github.com/dmlc/xgboost/blob/6b98305db4e09cece005ab16f9c61a3fac34258e/demo/guide-python/cat_pipeline.py#L98 (and many other scikit-learn examples).

From my own perspective (maybe wrong), I think those integrated preprocessor in ML estimators are more or less legacy in scikit-learn, they are expanding the preprocessing module significantly and independent of estimators.

**Comment by trivialfis** [comment]
The module choice give us (and users) some flexibility when composing features from libraries:
- They can use CPU for preprocessing and GPU for model training.
- They can use distributed frameworks. When distributed computing is involved, the encoder is implemented very differently.
- They can choose other encoders, potentially much more efficient.

**Comment by david-cortes** [comment]
But those `pd.Categorical` are just numpy `uint` arrays behind the scenes, just with extra metadata.

**Comment by trivialfis** [comment]
> But those pd.Categorical are just numpy int arrays behind the scenes, just with extra metadata and syntactic sugar.

If the training data is `["a", "b", "c"]`, the test data is `["a", "c"]`, then the integer indexes might be `[0, 1,  2]` and `[0, 1]` respectively. See the `"c"` can mapped differently. We want a dedicated encoder to handle these types of issues (it's not trivial if you go down that path), along with all the other things that are related to encoding (like how to sort the data to obtain the mapping in the first place), and then let users compose based on their requirements.

To me, it's a separation of responsibility and flexible composibility. It's not very nice at first since users might need to worry about some more things instead of having a one-stop shop, but when the pipeline grows, it's quite important to know which component is doing exactly what and swap out components.

**Comment by david-cortes** [comment]
Thanks for the examples.

I would have said that the answers to all those questions are very simple by handling them the same way R would, but from some testing, it seems that scikit-learn itself does indeed do its own processing later on in e.g. `Estimator.score` if passed strings instead of factors, or factors with different levels, or something else, so there is additional processing needed.

And from a look at how scikit-learn processes new `y`, it looks like it'd be hard to re-use their functions/classes in a way in which the actual post-processed data could be passed to xgboost's core library, even if relying on their `Estimator` classes and following their idosynchrasies.
