### ISSUE TITLE
[Spark/Flink] Serialization under Kyro

### ISSUE THREAD

**Issue by tqchen** [dmlc/xgboost#974]
Related to https://github.com/dmlc/xgboost/issues/972

One way to avoid this, is to explicitly serialize Booster before return, and doing the samething when broadcasting. The modification can be very straight-forward.

In mapPartition return ```booster.toByteArray()``` instead.
During prediction, broadcast the byteArray, and explicit construct the Booster from there

**Comment by tqchen** [comment]
Another choice is simply make the Booster KyroSerializable, which might be a good option. @CodingCat

**Comment by CodingCat** [comment]
I prefer to add a kyroserializer in the next release

**Comment by tqchen** [comment]
Sounds good

**Comment by CodingCat** [comment]
resolved by #979
