### ISSUE TITLE
Question about Boosting Iteration Logic in XGBoost’s Training Loop 

### ISSUE THREAD

**Issue by linjunhe** [dmlc/xgboost#9741]
Why is the `version` variable incremented twice within the loop in the [provided code snippet](https://github.com/dmlc/xgboost/blob/80390e6cb69c4f478217179bede451f7f8dd0b56/src/cli_main.cc#L229)? As a result, `version` is **always an even number** at the beginning of each iteration? Then the number of boosting iterations is actually half of the specified `param_.num_round`?

```
// load in data.
...

// initialize the learner.
...

// start training.
int32_t version = 0;
for (int i = version / 2; i < param_.num_round; ++i) {
    if (version % 2 == 0) {
	    learner_->UpdateOneIter(i, dtrain);
	    version += 1;
	}
	...
    version += 1;
}

// save model
...
```

Why don't we simply use the following logic? Why do we need the `version` variable? What's it for?
```
// load in data.
...

// initialize the learner.
...

// start training.
for (int i = 0; i < param_.num_round; ++i) {
    learner_->UpdateOneIter(i, dtrain);
}

// save model
...
```

or

```
// load in data.
...

// initialize the learner.
...

// start training.
for (int i = 0; i < param_.num_round/2; ++i) {
    learner_->UpdateOneIter(i, dtrain);
}

// save model
...
```

**Comment by trivialfis** [comment]
That's some weird logic that pre-dates my involvement in XGBoost. My best guess is due to the removed resilience support in rabit.

**Comment by trivialfis** [comment]
We have deprecated the CLI now (2.1.0), so I think it's unlikely someone will cleanup the code there. Similar logic in other places is all removed.

**Comment by linjunhe** [comment]
Where can I find the updated training logic now that the CLI has been deprecated in version 2.1.0? @trivialfis

**Comment by trivialfis** [comment]
The Python package would be a good place to start: https://github.com/dmlc/xgboost/blob/be20df8c23c063f9b5ff242e66c29ebd66578ca6/python-package/xgboost/training.py#L178

**Comment by linjunhe** [comment]
Thanks!
