### ISSUE TITLE
Docs for "Contributing" have outdated instructions

### ISSUE THREAD

**Issue by david-cortes** [dmlc/xgboost#9744]
The docs for xgboost have a section about "Contributing":
https://xgboost.readthedocs.io/en/stable/contrib/coding_guide.html#python-coding-guideline

It mentions that code linting can be done with `pylint` and `cpplint` using a `make` command:
```
cd /path/to/xgboost/
make lint
```

But under the new build system, there is no top-level makefile, so it throws:
```
make: *** No rule to make target 'lint'.  Stop.
```

**Comment by trivialfis** [comment]
Thank you for raising the issue, let me make some updates.

**Comment by david-cortes** [comment]
@trivialfis It seems the C++ linter only makes checks, but doesn't auto-format. Is there some tool to auto-fix C++ linting?

**Comment by trivialfis** [comment]
`clang-format` works most of the time. We don't enforce it since it will introduce too many unnecessary changes. I myself have `clangd` setup with language server protocol, so it's mostly automatic when writing code.
