### ISSUE TITLE
[jvm-package] Test XGBoost4J GPU with Scala 2.13

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#9760]
Currently, the CI tests XGBoost4J with Scala 2.13, but without support for GPU algorithms. Now that Spark-Rapids supports Scala 2.13 (starting from the 23.12 snapshot version), we should start testing XGBoost4J GPU with Scala 2.13 too.

**Comment by eordentlich** [comment]
As well as XGBoost4j Spark GPU .   @wbo4958

**Comment by wbo4958** [comment]
I'm working on that.
