### ISSUE TITLE
[jvm-package] Upload XGBoost4J with Scala 2.13 to Maven Central

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#9765]
#9099 added support for Scala 2.13 to XGBoost4J, but I forgot to upload `xgboost4j_2.13-2.0.1.jar` (and other artifacts) to Maven Central. I will do this by end of this week.

cc @dotbg @wbo4958

**Comment by dotbg** [comment]
thanks a lot!

**Comment by hcho3** [comment]
XGBoost 2.0.2 is now available on Maven Central:
* https://repo1.maven.org/maven2/ml/dmlc/xgboost-jvm_2.12/2.0.2/
* https://repo1.maven.org/maven2/ml/dmlc/xgboost-jvm_2.13/2.0.2/
* https://repo1.maven.org/maven2/ml/dmlc/xgboost4j_2.12/2.0.2/
* https://repo1.maven.org/maven2/ml/dmlc/xgboost4j_2.13/2.0.2/
