### ISSUE TITLE
The procedure entry point could not be located in the dynamic link library libxgboost.dll

### ISSUE THREAD

**Issue by eeriee** [dmlc/xgboost#977]
I install the xgboost package in python on Windows based on the answer from Disco4Ever in [http://stackoverflow.com/questions/33749735/how-to-install-xgboost-package-in-python-windows-platform]
After I run *_import xgboost as xgb *_ in python 3.5, this error appears. 
![error](https://cloud.githubusercontent.com/assets/12132133/13727863/b8a7e78a-e93e-11e5-80d4-ab8c1cbf7631.PNG)

**Comment by LazerFazer** [comment]
I'm having the same problem, Windows 10 x64, python 3.4. Trying to run the xgboost.exe gives the same problem, so I doubt it's a python issue

**Comment by LazerFazer** [comment]
I've identified the offending DLL. It is indeed libstdc++-6.dll. On my machine, the dll provided by anaconda2 was being loaded (found in c:\anaconda2\scripts\LIBSTDC++-6.DLL), which didn't have the following referenced and required functions:

_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE4findEPKcyy
_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE4findEcy
_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE5rfindEPKcyy
_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE5rfindEcy
_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7compareEPKc
_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7compareERKS4_
_ZNKSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEE3strEv

**Comment by EvenOldridge** [comment]
Thank you.  I had exactly this issue.  Copying the file to the site-packages directory didn't fix it, but I took a risk (after backing up the old one) and overwrote the anaconda script version.

I'm a little concerned that some other functionality is going to crap out because the file sizes were so different (8MB vs 1.3MB) but so far it seems to work.

**Comment by longmumin** [comment]
I have the same problem with you guys. Could you share the solutions?  Copying the file to the site-packages directory didn't fix the issue.

**Comment by longmumin** [comment]
Yeah. The bug has been fixed. According to @TalhaAsmal ,you have to copy the libstdc++-6.dll to Anaconda3\Scripts, it will work.

**Comment by StrikerRUS** [comment]
Another possible solution (not tested properly):
add this to `CMakeLists.txt`

```
if(MINGW)
    set(CMAKE_EXE_LINKER_FLAGS ${CMAKE_EXE_LINKER_FLAGS} -static-libstdc++)
endif()
```

**Comment by tlmyasirs** [comment]
I  was getting the error for compiling a code with MinGW,  which is written in Visual studio and StrikerRUS's fix worked for me
