### ISSUE TITLE
How to calculate xG for a single shot in a local match?

### ISSUE THREAD

**Issue by SMSadegh19** [dmlc/xgboost#9771]
Hi. How can I calculate xG with your model for a single goal chance in a local match.
There is no data available for our game. Only video of the game is available. I want to watch the video and manually write the data and then, use your model to calculate xG of that.

**Comment by trivialfis** [comment]
I think you are opening the issue on a wrong repo. Feel free to reopen if this isn't the case.

**Comment by SMSadegh19** [comment]
Where can I find solution to my problem if this repo is not the right one?
Can you help me?
