### ISSUE TITLE
How long does it take for the latest master branch to be released as a release branch?

### ISSUE THREAD

**Issue by xiangguanlan** [dmlc/xgboost#9783]
I trained a model using the 1.7.6 branch and used xgboost4j for online prediction. However, due to high concurrent requests, a deadlock occurred in the predict method, resulting in a coredump issue. Now, there have been commits in the master branch to address the multi-threading safety issue. I would like to know approximately how long it will take for a release package to be available in the master branch.

**Comment by trivialfis** [comment]
Which specific commit are you referring? Is it part of 2.0?

**Comment by trivialfis** [comment]
I don't recall we have anything related to deadlock, there's a new inplace prediction, is that what you are referring to?

**Comment by xiangguanlan** [comment]
yes, it's inplace_predict

**Comment by trivialfis** [comment]
We don't have an eta. Currently, XGBoost follows a feature-based release instead of time-based. You are free to use the nightly build.

**Comment by xiangguanlan** [comment]
ok，thanks for your response.
