### ISSUE TITLE
XGBoost using SKLearn interface error: Falling back to prediction using DMatrix due to mismatched devices.

### ISSUE THREAD

**Issue by melhzy** [dmlc/xgboost#9791]
XGBoost error:
XGBoost using SKLearn interface and training model on a multi-GPU Ubuntu 20.04 computer.

xgboost/core.py:160: UserWarning:

WARNING: /workspace/src/common/error_msg.cc:58: Falling back to prediction using DMatrix due to mismatched devices. This might lead to higher memory usage and slower performance. XGBoost is running on: cuda:2, while the input data is on: cpu.
Potential solutions:
- Use a data structure that matches the device ordinal in the booster.
- Set the device for booster before call to inplace_predict.

This warning will only be shown once.

----------------------------------------------------------------------------------------------------------------------
I'm not entirely sure about the extent of the impact this error has on performance, but it's really annoying to always see this warning pop up during my training process.

**Comment by trivialfis** [comment]
If you don't want to see the warning during prediction/evaluation, here are potential solutions:
- Use a data structure that supports GPU. For instance, on distributed system with dask, this can be `dask_cudf.DataFrame` or `da.Array` backed by `cupy`. On a single-GPU instance (since you are using sklearn interface), use `cupy` or `cudf`.
- Disable warning from XGBoost by using the `verbosity` parameter.

**Comment by melhzy** [comment]
> If you don't want to see the warning during prediction/evaluation, here are potential solutions:
> 
> * Use a data structure that supports GPU. For instance, on distributed system with dask, this can be `dask_cudf.DataFrame` or `da.Array` backed by `cupy`. On a single-GPU instance (since you are using sklearn interface), use `cupy` or `cudf`.
> * Disable warning from XGBoost by using the `verbosity` parameter.

I have used
`import cupy as cp
cp.cuda.Device(gpu_id).use()
X_train, y_train = cp.array(X_train).get(), cp.array(y_train).get()
X_test, y_test = cp.array(X_test).get(), cp.array(y_test).get()`

But still seeing the same error message. Any idea?

**Comment by trivialfis** [comment]
I think the get function returns a CPU numpy array.

**Comment by trivialfis** [comment]
Feel free to reopen if there are further questions.

**Comment by qa-aleksejs-fomins** [comment]
Where can I see the intended way to use XGBoost on GPU?
I also get this error.
Would you be so kind to contribute a basic python script for running XGBoost on a GPU where the X and Y are passed to the function as intended?

**Comment by trivialfis** [comment]
@qa-aleksejs-fomins 

``` python
import cupy as cp
import xgboost as xgb
from sklearn.datasets import make_regression

X, y = make_regression()

reg = xgb.XGBRegressor()
reg.fit(X, y)

# No warning, reg and X are on CPU
reg.predict(X)

# Put X into GPU
X = cp.array(X)
# Put reg to GPU
reg.set_params(device="cuda")
# No warning, both on GPU
reg.predict(X)

# Warning, reg is on CPU, but X on GPU
reg.set_params(device="cpu")
reg.predict(X)

X = cp.asnumpy(X)
reg.set_params(device="cuda")
# Warning, reg is on GPU, but X on CPU
reg.predict(X)
```

**Comment by qa-aleksejs-fomins** [comment]
@trivialfis Thanks a lot, this clarifies things

**Comment by Ritu-code17** [comment]
from sklearn.model_selection import train_test_split
import cupy as cp
# Split data into train and validation sets for early stopping
X_train, X_val, y_train, y_val = train_test_split(train_data_selected, target_df_cleaned['target'], test_size=0.2, random_state=42)

# Convert numpy arrays or pandas DataFrames to cupy arrays
X_train_gpu = cp.asarray(X_train).get()
y_train_gpu = cp.asarray(y_train).get()
X_val_gpu = cp.asarray(X_val).get()
y_val_gpu = cp.asarray(y_val).get()

# Define early stopping parameters
eval_set = [(X_train_gpu, y_train_gpu), (X_val_gpu, y_val_gpu)]

import xgboost as xgb
from sklearn.model_selection import GridSearchCV

# Define hyperparameters
xgb_param_grid = {
    'n_estimators': [500, 1000],
    'max_depth': [5, 10],
    'learning_rate': [0.01, 0.1],
    'colsample_bytree': [0.8, 1],
    'subsample': [0.7, 1],
    'gamma': [0, 0.1],
    'min_child_weight': [5, 10],
    'reg_lambda': [10, 50],
    'reg_alpha': [1, 10],
    'scale_pos_weight': [1,9,11],  # 92:8 imbalance
    'eval_metric':['logloss'],
    'random_state': [42]
}

# Initialize XGBoostClassifier
xgb_model = xgb.XGBClassifier(tree_method = "hist", device = "cuda", early_stopping_rounds=10)

# Perform GridSearchCV
xgb_grid_search = GridSearchCV(estimator=xgb_model, param_grid=xgb_param_grid, cv=5, scoring='roc_auc', verbose=0)

xgb_grid_search.fit(X_train, y_train,eval_set=eval_set, verbose=False)

This worked for me.........

**Comment by anonymousTechpreneur** [comment]
from sklearn.model_selection import train_test_split
import cupy as cp
# Split data into train and validation sets for early stopping
X_train, X_val, y_train, y_val = train_test_split(train_data_selected, target_df_cleaned['target'], test_size=0.2, random_state=42)

# Convert numpy arrays or pandas DataFrames to cupy arrays
X_train_gpu = cp.asarray(X_train).get()
y_train_gpu = cp.asarray(y_train).get()
X_val_gpu = cp.asarray(X_val).get()
y_val_gpu = cp.asarray(y_val).get()

# Define early stopping parameters
eval_set = [(X_train_gpu, y_train_gpu), (X_val_gpu, y_val_gpu)]

import xgboost as xgb
from sklearn.model_selection import GridSearchCV

# Define hyperparameters
xgb_param_grid = {
    'n_estimators': [500, 1000],
    'max_depth': [5, 10],
    'learning_rate': [0.01, 0.1],
    'colsample_bytree': [0.8, 1],
    'subsample': [0.7, 1],
    'gamma': [0, 0.1],
    'min_child_weight': [5, 10],
    'reg_lambda': [10, 50],
    'reg_alpha': [1, 10],
    'scale_pos_weight': [1,9,11],  # 92:8 imbalance
    'eval_metric':['logloss'],
    'random_state': [42]
}

# Initialize XGBoostClassifier
xgb_model = xgb.XGBClassifier(tree_method = "hist", device = "cuda", early_stopping_rounds=10)

# Perform GridSearchCV
xgb_grid_search = GridSearchCV(estimator=xgb_model, param_grid=xgb_param_grid, cv=5, scoring='roc_auc', verbose=0)

xgb_grid_search.fit(X_train, y_train,eval_set=eval_set, verbose=False)

This worked for me.........

**Comment by CamiloMartinezM** [comment]
@Ritu-code17 Aren't you still training on cpu when you do `.fit(X_train, y_train, ...)` in the end?

**Comment by satyrmipt** [comment]
This warning impacts performance significantly when your model on CUDA. Please note that this warning is activated not only when you train model on GPU with data on CPU but also when you apply model (predic, predict proba) and your test data on CPU.  It impacts this stage too! Hence eval_sets have to be moved to GPU too.

I'm not sure if you have to move to GPU sample_weights iterable (if you have one as model.fit parameter), but it's easy to make such test.

**Comment by trivialfis** [comment]
It's best to use one device consistently. PyTorch has a similar requirement, but for PyTorch, it's an error instead of a warning.

**Comment by melhzy** [comment]
I ended up by using XGBoost native API. The performance is MUCH More faster than sklearn implementation.

**Comment by satyrmipt** [comment]
> I ended up by using XGBoost native API. The performance is MUCH More faster than sklearn implementation.

Want to say you managed to use XGBoost native API together with sklearn's GridSearchCV?!
