### ISSUE TITLE
ValueError: X has 66 features, but StandardScaler is expecting 96 features as input.

### ISSUE THREAD

**Issue by tszjqgs** [dmlc/xgboost#9794]
working on a model prediction based on a saved xgboost model , one pre requisite step is to do scale transform .
scaler = models_saved['scaler']
data_scaled = scaler.transform(prediction_df) 

and I got this ValueError: X has 66 features, but StandardScaler is expecting 96 features as input.

but the tricky part is even after I loaded the model pickle file and print the scaler information , all I can see is the dimension number information : print(scaler.n_features_in_) , but not the actual needed scaler features. so it become a real road blocker for me . since the original training feature information is not well documented , I am not sure how to reverse engineer the current prediction data to make it work with this scaler transform step before the prediction can be made 

so in this case is there a way to at least skip this error and make it to the step of prediction ?

Thanks all

**Comment by trivialfis** [comment]
I don't quite understand the question based on your description. Please provide more context than this two lines of code
```
scaler = models_saved['scaler']
data_scaled = scaler.transform(prediction_df)
```
However, if you can't figure out the pipeline yourself, I doubt that anyone can. Only thing comes to mind that might be helpful is that XGBoost saves feature names in model if input is a DF, along whether there's categorical data.

**Comment by tszjqgs** [comment]
情况就是之前有人已经开发好了模型，训练好了，我这边接手，然后利用这个模型进行预测。预测之前有一个scaler transform 的步骤，遇到了数据结构对不上，scaler 预期是96个feature ，但是现在用来预测输入的数据只有60多个。但这个scaler 貌似是模型里面保存的，就是说以前预训练时候保存的结果。这个您提到的保存feature 名字是如何能看到呢？我只能看到纬度是96个，但是如何把96个feature名字？
from Alimail iPhone
 ------------------Original Mail ------------------
Sender:Jiaming Yuan ***@***.***>
Send Date:Fri Nov 17 16:44:34 2023
Recipients:dmlc/xgboost ***@***.***>
CC:tszjqgs ***@***.***>, Author ***@***.***>
Subject:Re: [dmlc/xgboost] ValueError: X has 66 features, but StandardScaler is expecting 96 features as input. (Issue #9794)

I don't quite understand the question based on your description. Please provide more context than this two lines of code
scaler = models_saved['scaler']
data_scaled = scaler.transform(prediction_df)

However, if you can't figure out the pipeline yourself, I doubt that anyone can. Only thing comes to mind that might be helpful is that XGBoost saves feature names in model if input is a DF, along whether there's categorical data.

**Comment by trivialfis** [comment]
Let me do a quick summary so that others can follow:

> My predecessor trained a model without leaving proper documents.

This attribute may help: https://xgboost.readthedocs.io/en/stable/python/python_api.html#xgboost.XGBRegressor.feature_names_in_ 

If it doesn't, then I don't think there's much to explore here, just train the model again.
