### ISSUE TITLE
Java dependencies issue

### ISSUE THREAD

**Issue by xtello** [dmlc/xgboost#9797]
Hello,

I'm trying to use XGBoost in our Java app (Java 17) using Maven (i initially needed to use Gradle but the issue is worse there). When i build, i get the error: 

`Could not resolve dependencies for project com.example:test-maven:jar:1.0-SNAPSHOT: Failed to collect dependencies at ml.dmlc:xgboost4j_2.13:jar:2.0.2: Failed to read artifact descriptor for ml.dmlc:xgboost4j_2.13:jar:2.0.2: The following artifacts could not be resolved: ml.dmlc:xgboost-jvm_${scala.binary.version}:pom:2.0.2 (absent): ml.dmlc:xgboost-jvm_${scala.binary.version}:pom:2.0.2 was not found in https://repo.maven.apache.org/maven2`

Maven config i use:
```
    <properties>
        <scala.binary.version>2.13</scala.binary.version>
        <!--  <scala.binary.version>2.11</scala.binary.version>-->
    </properties>

    <dependencies>
        <dependency>
            <groupId>ml.dmlc</groupId>
            <artifactId>xgboost4j_${scala.binary.version}</artifactId>
            <version>2.0.2</version>
            <!--  <version>1.1.2</version>  builds with scala binary 2.11 but dynamic lib NOT built for Apple silicon  -->
        </dependency>
        <dependency>
            <groupId>ml.dmlc</groupId>
            <artifactId>xgboost4j-spark_${scala.binary.version}</artifactId>
            <!--  <version>1.1.2</version>-->
            <version>2.0.2</version>
        </dependency>
    </dependencies>
```

The issue seems to be in https://repo.maven.apache.org/maven2/ml/dmlc/xgboost4j_2.13/2.0.2/xgboost4j_2.13-2.0.2.pom where the Maven can't seem to expand variable `${scala.binary.version}` in this external POM even if i declare it in my POM
<img width="750" alt="image" src="https://github.com/dmlc/xgboost/assets/26663207/33d9f578-abc3-476b-a81e-45d4d4f9b3ae">

Thanks in advance!
Xavier

**Comment by hcho3** [comment]
The issue has been fixed in the latest patch release (2.0.3).
