### ISSUE TITLE
Changing xgboost internal parameters, in new and old versions

### ISSUE THREAD

**Issue by dacian-dataheroes** [dmlc/xgboost#9806]
I'm in a situation where I have to change the leaf values of an xgboost model. I saw they are represented internally by "split_conditions" / base_weights".  The motivation is that I want to compute the leaf values in a custom way. 

The method I use right now is to dump the model into a json, change the json, then load the model back. Something like:
```python
b_raw = booster.save_raw(raw_format="json")
b_json["learner"]["gradient_booster"]["model"]["trees"][tree_idx]["split_conditions"] = new_split_conditions
xgb.Booster(model_file=bytearray(json.dumps(b_json, cls=NpEncoder).encode()))
```

Firstly, I wanted to ask: Is there an easier method for this? It's working, but it seems ugly.

Secondly, `save_raw(raw_format = "json")` is introduced in version 1.6.0. Before that there's only saving as a bytearray. Is there a way to change the conditions before 1.6.0? I'm interested in something starting from 1.4.0.

**Comment by dacian-dataheroes** [comment]
>  custom C++ objective. 

The main idea was to compute the leaf values on another dataset. I didn't found a way to train on some dataset and compute the values on another, so I tried to overwrite them directly. 

> Sort of, one can save it in a JSON file first

Is there an example / can you provide an example? I'm looking for something in memory (like save_raw).

**Comment by trivialfis** [comment]
> Is there an example / can you provide an example? I'm looking for something in memory (like save_raw).

``` python
booster.save_model("model.json")

import json

with open("model.json", "r") as fd:
    model = json.load(fd)
```

https://github.com/dmlc/xgboost/blob/master/demo/json-model/json_parser.py

**Comment by trivialfis** [comment]
Feel free to reopen if there are further questions.
