### ISSUE TITLE
Redundant `Tree method is selected to be 'hist', which uses a single updater grow_quantile_histmaker` INFO in the std output (C++ code base)

### ISSUE THREAD

**Issue by mikbuch** [dmlc/xgboost#9819]
With Python, I keep getting this INFO when running XGBoost fit:

```
[16:04:51] INFO: /tmp/build/80754af9/xgboost-split_1619724447847/work/src/gbm/gbtree.cc:176: Tree method is selected to be 'hist', which uses a single updater grow_quantile_histmaker.
[16:04:51] INFO: /tmp/build/80754af9/xgboost-split_1619724447847/work/src/tree/updater_prune.cc:101: tree pruning end, 58 extra nodes, 12 pruned nodes, max_depth=6
```

Grid search:
```
    gr = GridSearchCV(estimator=gbm,
                      param_grid=gbm_param_grid,
                      # scoring='neg_log_loss',
                      scoring=roc_auc_scorer,
                      cv=2,
                      # n_jobs=-1,
                      verbose=0)
```

How to turn off this message from C++ scripts, and why it is there in the first place?

**Comment by trivialfis** [comment]
I thyyou have set the verbosity of XGB estimator to 2 somewhere.

**Comment by mikbuch** [comment]
Thak you for your reply @trivialfis . It turned out that the issues was due to the XGBoost v. 1.7 . With 2.0 the output is no longer present. Sorry for bothering you with this issue. Maybe someone else will find it useful, that you only need to upgrade the module and the problem will be resolved.

**Comment by trivialfis** [comment]
We set the default to `hist` in 2.0 so there's no selecting, I'm not sure why there's a message for pruning.

The message is only shown when `verbosity` is set to greater than 1 while the default value is 1. Please check the parameter configuration.

**Comment by mikbuch** [comment]
For 2.0 it works. For 1.7 there is still output despite setting all verbosity to 0. I can provide an example, but I am not sure whether it makes much sense to try to fix an older version.

**Comment by trivialfis** [comment]
Excellent that 2.0 works for you! Let's revisit this when there are further issues.
