### ISSUE TITLE
Visual Studio not associating source files for debugging

### ISSUE THREAD

**Issue by mpiraino** [dmlc/xgboost#9838]
I am trying to setup the repository in Visual Studio but I am encountering an issue where the tests are not associated with source files. The result is that I am not able to use the debugger in test explorer.

System: Windows 11
Visual Studio 17 2022

Steps:
```
git clone --recursive git@github.com:dmlc/xgboost.git
cd xgboost
mkdir build
cd build
cmake -DGOOGLE_TEST=ON -DUSE_DMLC_GTEST=ON .. -G"Visual Studio 17 2022" -A x64
```

Error:
========== Starting test discovery ==========
No test is available in C:\Users\user\repos\xgboost\lib\xgboost.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
Could not locate debug symbols for 'C:\Users\user\repos\xgboost\build\testxgboost.exe'. To make use of '--list_content' discovery, ensure that debug symbols are available or make use of '<ForceListContent>' via a .runsettings file.
Could not locate debug symbols for 'C:\Users\user\repos\xgboost\build\dmlc-core\test\unittest\Release\dmlc_unit_tests.exe'. To make use of '--list_content' discovery, ensure that debug symbols are available or make use of '<ForceListContent>' via a .runsettings file.
Test Adapter for Google Test: Test discovery starting...
Test Adapter for Google Test: Test discovery starting...
Warning: Couldn't find the .pdb file of file 'C:\Users\user\repos\xgboost\build\testxgboost.exe'. You will not get any source locations for your tests.
Warning: Couldn't find the .pdb file of file 'C:\Users\user\repos\xgboost\build\dmlc-core\test\unittest\Release\dmlc_unit_tests.exe'. You will not get any source locations for your tests.
Warning: Could not find source location for test Any.basics
Warning: Could not find source location for test Any.cover

**Comment by trivialfis** [comment]
Honestly, I'm not sure what I can help there. We are using the normal CMake build, however MSVC is dealing with it is beyond our scope.

**Comment by trivialfis** [comment]
Feel free to reopen if there are further questions.
