### ISSUE TITLE
[jvm-packages] Is there a way to derive feature importance on Apache SPARK using JVM package?

### ISSUE THREAD

**Issue by astrude** [dmlc/xgboost#985]
I am currently able to save the model and derive the feature score in python. But it'd be really great if we can derive feature importance in SPARK itself

**Comment by CodingCat** [comment]
for saving the model, you can call `saveModelAsHadoopFile` API of XGBoostModel after the training is done (see the example code here: https://github.com/dmlc/xgboost/tree/master/jvm-packages)

for deriving the feature score, we do not have API in xgboost4j-spark for now....

**Comment by CodingCat** [comment]
I just added a getter in XGBoostModel https://github.com/dmlc/xgboost/pull/988, so that you can call booster to access the Booster instance in the model and then call the low-level APIs, e.g. getFeatureScore

**Comment by CodingCat** [comment]
resolved by https://github.com/dmlc/xgboost/pull/988

**Comment by astrude** [comment]
Thanks CodingCat. That was helpful :)
