### ISSUE TITLE
Fail to build xgboost.federated plugin

### ISSUE THREAD

**Issue by yan-gao-GY** [dmlc/xgboost#9858]
Hi, I tried to install the plugin `xgboost.federated` following the instruction here (https://github.com/dmlc/xgboost/tree/master/plugin/federated), but I got an error as below:  

``` CMake Error at CMakeLists.txt:12 (xgboost_target_properties): Unknown CMake command "xgboost_target_properties". ``` 

I have updated CMake, and installed gRPC. Then I ran these commands:

``` 
mkdir build 
cd build 
cmake .. -GNinja \ 
-DPLUGIN_FEDERATED=ON \ 
-DUSE_CUDA=ON\ 
-DUSE_NCCL=ON 
ninja 
cd ../python-package 
pip install -e . 
```
The error appeared when running `cmake`. Could you please indicate me how to fix this error? What's the correct way to install this plugin? Thanks a lot!

**Comment by trivialfis** [comment]
which cmake version are you using?

**Comment by yan-gao-GY** [comment]
3.27.9

**Comment by yan-gao-GY** [comment]
Oh I forgot to mention that I ran it on macbook.

**Comment by trivialfis** [comment]
I don't have a mac, have to wait for @hcho3 .

**Comment by yan-gao-GY** [comment]
Yes, I didn't pass the cuda and nccl arguments

**Comment by trivialfis** [comment]
Closing as we haven't been able to reproduce. For reference, the missing command shared in the issue is defined here: https://github.com/dmlc/xgboost/blob/033a666900a2b58f72a3050e63b02f1681e4f609/cmake/Utils.cmake#L165 .
