### ISSUE TITLE
Newest 2.0.2 XGBoost is missing in Conda

### ISSUE THREAD

**Issue by EmperorTransisthor** [dmlc/xgboost#9859]
Hi,
Just as title says, I can install newest XGBoost release using pip (XGBoost 2.0.2), however Conda has 1.7.6 only. When will this package be updated in conda repo?

**Comment by trivialfis** [comment]
Please track the progress in https://github.com/conda-forge/xgboost-feedstock/pull/132 .

**Comment by EmperorTransisthor** [comment]
I see, is someone working on the failing branch (https://github.com/conda-forge/xgboost-feedstock/pull/132/checks?check_run_id=18776240513)?

**Comment by trivialfis** [comment]
I was informed about some nice progress recently, but can't be sure. cc @jakirkham

**Comment by hcho3** [comment]
XGBoost 2.0.3 is now available on Conda: https://anaconda.org/conda-forge/xgboost
