### ISSUE TITLE
Unable to build the shared library file on windows system.

### ISSUE THREAD

**Issue by OnkarDeshpande** [dmlc/xgboost#986]
# rookie alert

I am trying to build using the command `mingw32-make -j4` on git bash according to [documentation](http://xgboost.readthedocs.org/en/latest/build.html#building-on-windows). I am getting the following error:

`A subdirectory or file -p already exists.
Error occurred while processing: -p.
A subdirectory or file build already exists.
Error occurred while processing: build.
The syntax of the command is incorrect.
g++ -m64 -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -MM -MT build/learner.o src/learner.cc >build/learner.d
The syntax of the command is incorrect.
mingw32-make: *** [build/logging.o] Error 1
mingw32-make: *** Waiting for unfinished jobs....
mingw32-make: *** [build/common/common.o] Error 1
mingw32-make: *** [build/c_api/c_api_error.o] Error 1
g++ -m64 -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude -DDMLC_ENABLE_STD_THREAD=0  -Idmlc-core/include -Irabit/include -fopenmp -c src/learner.cc -o build/learner.o
`

GCC version 4.7.0 installed on my 64bit system. 
`gcc -dumpmachine` command throws `x86_64-w64-mingw32`
Git bash is downloaded from [this link](https://git-for-windows.github.io/)  referring to the [comment](https://github.com/dmlc/xgboost/issues/831). Yet `-p` and `make`command are not recognized.
Please help.

**Comment by Maxceem** [comment]
Are you sure you are running make command from Git bash and not just from usual cmd? Because I had an error like you when run in cmd insted of Git Bash.

**Comment by thirdwing** [comment]
The reason for this error is the `mkdir` in Windows doesn't have `-p` option.

**Comment by OnkarDeshpande** [comment]
@thirdwing , @Maxceem   Yes,I am using Git bash on windows. I have attached the screenshot with this comment.  Please help. I'm still not able to find a fix to this problem...
![screenshot](https://cloud.githubusercontent.com/assets/17825435/13815828/1eec28b0-ebb2-11e5-8000-79d56dedcb66.PNG)

**Comment by Maxceem** [comment]
That was what helped me. I've tried a lot of things before finally compiled this library so I don't know what actually made the difference.

I'll tell you two things which I did out of docimentation:
1. I updated to the last version of git downloaded from here https://git-scm.com/download/win - 64-bit Git for Windows Setup.for my Windows 10 x64. 

2. I've installed MinGw64 separatly from here https://sourceforge.net/projects/mingw-w64/. And then added c:\mingw64\mingw64\bin\ (in my case) to the system path variable.

**Comment by OnkarDeshpande** [comment]
@Maxceem Yes. That is exactly what I had done on my system. I have installed Git 2.7.3 same as the link that you have provided. However the link for mingw64 is giving me an error saying "repository.txt not found". But i have downloaded it from a different location. Could you tell me how exactly can I verify if the correct version is installed in my system? 
If you look at the title bar, it clearly says MINGW64. The logo is also for Git Bash 2.7.3
I have updated the system path variable, which in my case was c:\mingw\bin .
I had renamed the file mingw32-make.exe to make.exe

**Comment by Maxceem** [comment]
Sorry. I don't know how to verify that correct versions are installed on your system, I even don't know what correct versions are :-)
Here is what I have:
```
$ mkdir --version
mkdir --version
mkdir (GNU coreutils) 8.24

$ bash --version
bash --version
GNU bash, version 4.3.42(5)-release (x86_64-pc-msys)

$ make --version
make --version
GNU Make 4.1
Built for x86_64-w64-mingw32

$ gcc --version
gcc --version
gcc.exe (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 5.3.0
```
My git bash window looks similar, though it doesn't have an icon:
![gitbash](https://cloud.githubusercontent.com/assets/146016/13819225/c06f1244-ebd3-11e5-84fe-b1d302e5231b.png)

It was started by an icon which references the next path "C:\Program Files\Git\git-bash.exe" --cd-to-home.

I've also renamed mingw32-make.exe to make.exe, though I needed it in the end.

The error you have now was my first on this road.

**Comment by OnkarDeshpande** [comment]
@Maxceem  the mkdir and bash version are the same, make version is  
`GNU Make 3.82
Built for x86_64-w64-mingw32`

and gcc version is 
`gcc.exe (niXman's build) 4.7.0
Copyright (C) 2012 Free Software Foundation, Inc.`

Dont know what exactly is going wrong here.
