### ISSUE TITLE
[jvm-packages] compile against different versions of spark

### ISSUE THREAD

**Issue by CodingCat** [dmlc/xgboost#987]
spark is coming with the 2.0 version which introduces several incompatible changes over the previous version

one of the issues is that the user will not upgrade to spark 2.0 immediately and sometimes, they just cannot upgrade due to various reasons.....

xgboost4j-spark shall upgrade with the pace of spark but also needs to ensure that the current users who will not upgrade to spark 2.0 are not excluded....

We need to introduce several profiles in maven, against spark 1.6,1.6.1, 2.0, and scala 2.10, 2.11.....etc.

**Comment by enragedginger** [comment]
+1

**Comment by lubinsu** [comment]
+1
