### ISSUE TITLE
[Python] Warning when passing SciPy sparse arrays

### ISSUE THREAD

**Issue by david-cortes** [dmlc/xgboost#9878]
SciPy has recently introduced classes for sparse objects that are named 'array', such as 'csr_array', which have the same structure as the corresponding 'matrix' like 'csr_matrix', but default to performing operations like elementwise multiplication instead of matrix multiplication the same way numpy arrays do compared to numpy matrices.

From what I understand, these sparse arrays are meant to supercede sparse matrices in the future.

Currently, passing one of these objects to xgboost will result in a warning:
```python
from scipy.sparse import csr_array, random
import xgboost as xgb
mat = random(100, 10, .1, format="csr")
mat = csr_array(mat)
dm = xgb.DMatrix(data=mat)
```
```
UserWarning: Unknown data type: <class 'scipy.sparse._csr.csr_array'>, trying to convert it to csr_matrix
  warnings.warn(
```

**Comment by trivialfis** [comment]
Based on its definition, seems they are quite similar, if not the same:
``` python
class csr_array(_csr_base, sparray):
    pass

csr_array.__doc__ = _csr_base.__doc__

class csr_matrix(spmatrix, _csr_base):
    pass

csr_matrix.__doc__ = _array_doc_to_matrix(_csr_base.__doc__)
```
