### ISSUE TITLE
Handling Categorical Data with PySpark API

### ISSUE THREAD

**Issue by mhmotamedi** [dmlc/xgboost#9894]
Dear Team! I’m curious if there are any plans to enhance the _xgboost Pyspark API_ by incorporating valuable features like **_enable_categorical_** and introducing partition-based splits parameters such as **_max_cat_to_onehot_** and **_max_cat_threshold_**. If such enhancements are in the horizon, could you share any expectations regarding the _**version**_ in which these features might become available? Thank you!

**Comment by trivialfis** [comment]
I would like to get it done in this version, but then I can't make the promise since I have other things on hand.

**Comment by trivialfis** [comment]
Closing in favor of https://github.com/dmlc/xgboost/issues/8398 .
