### ISSUE TITLE
Better organize scripts for CI and maintenance tasks

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#9896]
Currently, we update the version number manually (e.g. #9895). There should a script to automate the process.

**Comment by trivialfis** [comment]
I think we have one https://github.com/dmlc/xgboost/blob/master/tests/ci_build/change_version.py .

**Comment by hcho3** [comment]
Thanks. I renamed the issue. We have lots of scripts and Dockerfiles build up over time, and we should try to organize them better.
