### ISSUE TITLE
Auc ,I use normal dataset,but

### ISSUE THREAD

**Issue by Heipiao** [dmlc/xgboost#990]
[03:30:49] src/metric/rank_metric.cc:131: Check failed: sum_npos > 0.0 && sum_nneg > 0.0 AUC: the dataset only contains pos or neg samples
terminate called without an active exception
Aborted (core dumped)

**Comment by tqchen** [comment]
You need to make dataset with 0/1 labels.

**Comment by Heipiao** [comment]
The labels is 0/1,should i banlance the number of 0 and 1?

**Comment by tqchen** [comment]
No, you do not have to, but the result suggested that the testdata contains all 0 or all 1s.

**Comment by Heipiao** [comment]
Thank you,I know it 

发自我的 iPhone
