### ISSUE TITLE
C++ exceptions are catched in C-linkage functions with callbacks

### ISSUE THREAD

**Issue by david-cortes** [dmlc/xgboost#9911]
XGBoost provides functions with C linkage that take callbacks, such as `XGQuantileDMatrixCreateFromCallback`, which takes functions `reset` and `next`.

If a C++ exception inheriting from `std::exception` is thrown inside one of those functions supplied as callbacks, the exception will be called inside the call to `XGQuantileDMatrixCreateFromCallback` instead of propagating to the outside, which is quite unexpected for a function that is offered with C linkage, given that C functions wouldn't catch C++ exceptions.

**Comment by hcho3** [comment]
Uncaught C++ exceptions thrown from functions with C linkage will cause the program to crash. This is why all C API functions have wrappers that catches all C++ exceptions and convert them into an error code. For example:
https://github.com/dmlc/xgboost/blob/252e018275195b5e6a7fc49f069dccb2ec2d8c46/src/c_api/c_api.cc#L243-L256

> C functions wouldn't catch C++ exceptions

This is true in general. However, uncaught C++ exceptions will cause undesirable crashes, so for the case of XGBoost, all C linkage functions will catch all C++ exceptions.

**Comment by david-cortes** [comment]
It does however result in a rather unintended side effect: if the user wishes to catch a custom C++ exception from outside of the call to e.g. `XGDMatrixCreateFromCallback` (in order to e.g. trigger something when that custom exception is encountered), then that exception will not be catchable unless it's a class that wouldn't inherit from `std::exception`.

**Comment by hcho3** [comment]
@trivialfis How does the current `DataIterProxy` handle errors from the data iterator? Does the data iterator return an error code? Does the proxy check the error code from the data iterator?

**Comment by david-cortes** [comment]
> @trivialfis How does the current `DataIterProxy` handle errors from the data iterator? Does the data iterator return an error code? Does the proxy check the error code from the data iterator?

It returns an error code, and will set the `.what()` of the exception to `XGBGetLastError`.

**Comment by hcho3** [comment]
We have two alternatives, none of which is quite perfect:

* The status quo: exceptions from the data iterator are caught and translated into error codes. Disadvantage: users have to use `XGBGetLastError` to recover the error message; the expressiveness of C++ exception is lost.
* Allow the data iterator to throw C++ exceptions. Disadvantage: uncaught C++ exceptions will cause the whole program to crash. According to [the C++ standard](https://en.cppreference.com/w/cpp/error/terminate), `std::terminate` will be called when an exception is throw and not caught.

**Comment by david-cortes** [comment]
I think the ideal behavior would be that C++ exceptions thrown by the user's callback would be left uncatched, while C++ exceptions like `std::bad_alloc` generated otherwise during the normal course of the function (**not** from the user callback) would get catched and translated to error return codes like it currently does, so that it'd behave like a C function.

But I think it might be quite tricky to implement such a system.

**Comment by hcho3** [comment]
> C++ exceptions thrown by the user's callback would be left uncatched

There will be the risk of users forgetting to catch custom C++ exceptions leading to crashes. Is this risk acceptable?

**Comment by david-cortes** [comment]
> There will be the risk of users forgetting to catch custom C++ exceptions leading to crashes. Is this risk acceptable?

I don't think that should be a concern when offering a C interface - that is, C functions are not supposed to be aware of C++ exceptions, so I would guess that a user passing C++ functions should in turn be aware of the need to catch C++ exceptions, whether in an external try-catch, or in an internal one with a corresponding error code return.

> This can be done by having users throw a subclass of a pre-defined exception class, e.g. `DataIterException`.

It's currently possible to throw an object from an arbitrary class not inheriting from `std::exception`, which is then catchable from outside of the callback. So there's a workaround, even if not the most ideal.

Perhaps a better alternative could be to let the user specify a custom return code in case of failure.

**Comment by hcho3** [comment]
We can revise the exception handling logic to handle data iterator exceptions separately:

Before:
```cpp
try {
   // ...
} catch (dmlc::Error& e) {
   // Log error and return error code
} catch (std::exception& e) {
   // Log error and return error code
}
```

After:
```cpp
try {
  // ...
} catch (xgboost::DataIterException& e) {
 throw e;  // Re-throw
} catch (dmlc::Error& e) {
  // Log error and return error code
} catch (std::exception& e) {
  // Log error and return error code
}
```

**Comment by trivialfis** [comment]
I think @hcho3 is right that C++ exception cannot propagate through a function with C linkage. C++ is a different language than C just like Python is a different language than C. So, imagine you are writing Java/Python instead of C++, the error handling should work the same.

If the `next`/`reset` function for the callback has C linkage (as it should), XGBoost can't catch exceptions from it in `XGDMatrixCreateFromCallback` either, just like XGBoost can't catch java exception.

**Comment by hcho3** [comment]
For the R package, you can probably have a try / catch block to wrap the call to XGDMatrixCreateFromCallback, since we use a C++ compiler to build the glue code for the R package. So it might be okay for the callback function to throw an exception, as long as the R package glue code catches it.

**Comment by trivialfis** [comment]
Feel free to reopen if there are further questions.
