### ISSUE TITLE
Generic parameter for device

### ISSUE THREAD

**Issue by lcrmorin** [dmlc/xgboost#9920]
I have looked in the discussion forum / documentation and couldn't find the generic approach for an adaptative device approach. Basically I want to write generic code that use GPU when available (knowing that I don't have access to GPU all the time and sometimes I run on CPU). As I understand it the way to go is to specify device="cuda" so that when I don't have GPU it will fail to use this parameters and default to cpu. Maybe it could be better to have an 'auto' option that use what is available and set it as default option.

**Comment by trivialfis** [comment]
If I understand correctly, you want an option that uses GPU as default but falls back to CPU if GPU is not available.

I don't think XGBoost needs such an option as builtin, users can check the availability of GPUs themselves and make the choice that suits their use cases, here are available options:
- `nvidia-smi` command line.
- `cuda-python`: https://nvidia.github.io/cuda-python/overview.html
- `cupy`
- python nvml: https://pypi.org/project/pynvml/

**Comment by lcrmorin** [comment]
I think the default behavior should be "all-terrain", that is using the best hardware when available. (Wheter it is GPU by default and falling back to CPU when it is not available or a CPU by default that upgrade to GPU when available is up to interpretation).

I'd say there is 3 kinds of users: people with CPU only, people with CPU+GPU that naturally want to use GPU and people with CPU+GPU that want to only use CPU. It is not entirely clear why someone with CPU+GPU would want to train on CPU alone. Maybe I am missing some point and the trade off between CPU and GPU is not that trivial. But I feel like this last population is rather small. 

Currently the default behavior will cater to people with CPU and people with CPU+GPU that don't want to use GPU. I am suggesting the default behavior should tend to use best hardware when available. 

You are right that it probably can be handled out of xgb with an if statement. But I feel like this is what default parameters are for.

**Comment by trivialfis** [comment]
> But I feel like this is what default parameters are for.

I'm afraid the default parameter is to get things started for most people with the least surprise principle instead of being optimal. As a result, the default is usually the most conservative option.

Lastly, we would like to keep the parameters simple and let third party frameworks to handle it.

**Comment by lcrmorin** [comment]
Ok then. As someone that have access to a GPU I had a bit of a suprise that it would not use it by default and that I had to change a parameter manually for it to work.

**Comment by trivialfis** [comment]
Feel free to reopen if there are further questions.
