### ISSUE TITLE
Dumps from multi-quantile models include only first quantile

### ISSUE THREAD

**Issue by david-cortes** [dmlc/xgboost#9926]
ref https://github.com/dmlc/xgboost/pull/9924

Trying to get a model text dump from a multi-output model (`"multi_strategy" : "multi_output_tree"`) will produce an error, but if one tries to get a dump from a multi-quantile model, it will output only the leafs of the first quantile:

```python
import numpy as np, xgboost as xgb
rng = np.random.default_rng(seed=123)
X = rng.standard_normal(size=(100,3))
y = rng.standard_normal(size=100)
dm = xgb.DMatrix(data=X, label=y)
model = xgb.train(
    dtrain=dm,
    params={
        "tree_method" : "hist",
        "objective" : "reg:quantileerror",
        "quantile_alpha" : [0.1, 0.5, 0.9],
        "max_depth" : 2
    },
    num_boost_round=1
)
xgb.plot_tree(model)
```
![image](https://github.com/dmlc/xgboost/assets/11860098/1cf8761c-b47c-49ac-a0eb-454269c86810)

These leaves match with the first quantile:
```python
import json
base = float(
    json.loads(model.save_raw("json").decode())
    ["learner"]
    ['learner_model_param']
    ['base_score']
)
pred = model.predict(dm, output_margin=True)
np.unique(pred[:,0]) - base
```
```
array([-0.5326223 , -0.4631673 , -0.40180442,  0.01188996], dtype=float32)
```

But they do not match with the rest of the quantiles:
```python
array([-0.18282221,  0.0202435 ,  0.04176801,  0.12941198], dtype=float32)
```

**Comment by trivialfis** [comment]
It's still working in progress, the vector leaf. We can safely ignore it for now.

**Comment by trivialfis** [comment]
Closing in favor of https://github.com/dmlc/xgboost/issues/9043
