### ISSUE TITLE
feature`s class in xgboost package

### ISSUE THREAD

**Issue by tngks66** [dmlc/xgboost#993]
i try to analyze data by using "xgboost packages".
but i have something to ask.
there is some feature(class = factor, a lot of levels).
i want to dummy coding because this have many levels.
but i don`t know  about how different Depending on the class of feature
1. after dummy coding, feature(born by dummy coding)`s class is 
   factor(level = 0,1)
2. after dummy coding, feature(born by dummy coding)`s class is 
   numeric( consist of 0,1)

**Comment by khotilov** [comment]
xgboost cannot currently directly handle categorical features. They need to be converted into numeric dummies.
