### ISSUE TITLE
`gblinear` booster treats categorical features as numeric

### ISSUE THREAD

**Issue by david-cortes** [dmlc/xgboost#9936]
Booster type `gblinear` will use categorical features as numeric, which in most cases would not make sense given the data types.

Would be better to produce an error in this type of booster when the data contains categorical features, as otherwise the results are quite misleading and very unlikely to be what the user expects:
```python
import numpy as np, pandas as pd, xgboost as xgb
rng = np.random.default_rng(seed=123)
y = rng.standard_normal(size=100)
X = rng.integers(10, size=(100,3))
X = pd.DataFrame(X).astype("category")
model = xgb.XGBRegressor(booster="gblinear", enable_categorical=True).fit(X, y)
model.coef_
```
```
array([0.0126906 , 0.00228535, 0.0170959 ])
```

**Comment by trivialfis** [comment]
I will add an error.
