### ISSUE TITLE
FieldEntry ctor specialisation syntax error in macro DECLARE_FIELD_ENUM_CLASS

### ISSUE THREAD

**Issue by rpopescu** [dmlc/xgboost#9972]
The syntax for declaring the specialisation of `FieldEntry` in macro `DECLARE_FIELD_ENUM_CLASS` is valid with GCC in C++17 standards compliance mode, but not C++20.
To be more precise, GCC up to 10.5 accepts the syntax in C++20 mode; from 11 onwards, this causes an error.
https://godbolt.org/z/K8fGc98jq
The fix is to simply replace in the macro the ctor declaration from `FieldEntry<EnumClass>() {` to `FieldEntry() {` which compiles in both 17 and 20 mode.

**Comment by trivialfis** [comment]
Thank you for opening the issue, would you like to open a PR?

**Comment by rpopescu** [comment]
thank you for handling this so quickly!
