### ISSUE TITLE
[jvm-packages] build xgboost4j fail ,no jni.h

### ISSUE THREAD

**Issue by leoli2012** [dmlc/xgboost#998]
hi, i want build XGBoost4J on my machine. i did below steps
1 git clone --recursive https://github.com/dmlc/xgboost
2. cd jvm-packages
3. ./create_jni.sh
after a moment, report error messages:
----------------------------------------------------------------------------------------------------
make[1]: Leaving directory `/home/liyong/test/xgboost/rabit'
g++ -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -I/include -I./java -I/include/linux -shared -o jvm-packages/lib/libxgboost4j.so jvm-packages/xgboost4j/src/native/xgboost4j.cpp build/logging.o build/learner.o build/common/common.o build/metric/metric.o build/metric/rank_metric.o build/metric/elementwise_metric.o build/metric/multiclass_metric.o build/objective/multiclass_obj.o build/objective/objective.o build/objective/rank_obj.o build/objective/regression_obj.o build/data/sparse_page_dmatrix.o build/data/sparse_page_source.o build/data/sparse_page_writer.o build/data/simple_csr_source.o build/data/data.o build/data/sparse_page_raw_format.o build/data/simple_dmatrix.o build/tree/updater_prune.o build/tree/tree_updater.o build/tree/updater_histmaker.o build/tree/updater_refresh.o build/tree/updater_sync.o build/tree/updater_skmaker.o build/tree/updater_colmaker.o build/tree/tree_model.o build/gbm/gbtree.o build/gbm/gblinear.o build/gbm/gbm.o build/c_api/c_api.o build/c_api/c_api_error.o dmlc-core/libdmlc.a rabit/lib/librabit.a -pthread -lm  -fopenmp -lrt  -lrt
In file included from jvm-packages/xgboost4j/src/native/xgboost4j.cpp:18:0:
jvm-packages/xgboost4j/src/native/./xgboost4j.h:2:17: fatal error: jni.h: No such file or directory
 #include \<jni.h\>

seems jni.h fil not exist. but why?

**Comment by leoli2012** [comment]
i have found the reason, my machine jdk version is openjdk, after uninstall openjdk and install jdk1.8 from oracle, build xgboost4j successed.

**Comment by leoli2012** [comment]
by the way, what's the main purpose of create_jni.sh ? can i  mvn package directly without run create_ini.sh first ?

**Comment by CodingCat** [comment]
even with OpenJDK, you can set JAVA_HOME to your OpenJDK directory, that shall work

create_jni.sh builds the native libs, and copies the native libraries and test resource files to the directory

**Comment by tqchen** [comment]
@CodingCat Maybe we need a instruction in the installation part to explain what create_jni.sh does

**Comment by CodingCat** [comment]
![image](https://cloud.githubusercontent.com/assets/678008/13820601/7f697280-eb74-11e5-845a-a7b7a8bbf622.png)

yeah, I feel so....on the TODO list today

**Comment by CodingCat** [comment]
FYI, now, it only requires to run `mvn package` under jvm-packages directory to build XGBoost4J....
