### ISSUE TITLE
Quantile regression example QuantileDMatrix construction

### ISSUE THREAD

**Issue by OzoneReloaded** [dmlc/xgboost#9989]
https://github.com/dmlc/xgboost/blame/0798e36d733eb56313870b3fb301490f71c9ac78/demo/guide-python/quantile_regression.py#L52C8-L52C8

```
    X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=rng)
    # We will be using the `hist` tree method, quantile DMatrix can be used to preserve
    # memory.
    # Do not use the `exact` tree method for quantile regression, otherwise the
    # performance might drop.
    Xy = xgb.QuantileDMatrix(X, y)
    # use Xy as a reference
    Xy_test = xgb.QuantileDMatrix(X_test, y_test, ref=Xy)
```

Hello! I was running this example and noticed that `Xy` uses **X** and **y** for creating QuantileDMatrix instead of **X_train** and **y_train**. I think it leads to overfitting of the model as it uses the whole data to train and the subset of it as test

**Comment by trivialfis** [comment]
My bad, it's a mistake.
