### ISSUE TITLE
xgboost.core.XGBoostError: b'colsample_bytree=0 is too small

### ISSUE THREAD

**Issue by s-lund** [dmlc/xgboost#999]
The problem has been reported before but the reporting user closed the issue.

The full error message is this: 
xgboost.core.XGBoostError: b'colsample_bytree=0 is too small that no feature can be included'

The value I put into the colsample_bytree is: 0.83

I am using ubuntu 15.10. / Python 3.5 / xgboost-0.4a30 (I tested 0.4a25 and had the same problem)
the problem also occurred on Linux Mint (17.3 I think).

Any help would be welcome.

**Comment by s-lund** [comment]
When I set "colsample_bytree=1" I get this:

tree prunning end, 1 roots, 2 extra nodes, 0 pruned nodes ,max_depth=1
[0]	train-error:0,756000	eval-error:0,712798
Traceback (most recent call last):
  File "/home/sven/PycharmProjects/BaseML/ML/Geolife_ML_start.py", line 826, in <module>
    only_predict=False, model_selection=False, short=False, speedtest=False)
  File "/home/sven/PycharmProjects/BaseML/ML/Geolife_ML_start.py", line 750, in Prediction
    model_selection=model_selection, short=short, speedtest=speedtest)
  File "/home/sven/PycharmProjects/BaseML/ML/Geolife_ML_start.py", line 662, in GBC
    gbm = xgb.train(param, dtrain, num_round, watchlist, early_stopping_rounds=50)
  File "/home/sven/.local/lib/python3.5/site-packages/xgboost/training.py", line 194, in train
    score = float(msg.rsplit(':', 1)[1])
ValueError: could not convert string to float: '0,712798'


The problem occurres in xgb.train not in xgb.XGBClassifier

**Comment by tqchen** [comment]
please try to install from latest version from github

**Comment by s-lund** [comment]
That actually did the trick. Thank you for the help. 
Do you have an idea where the error comes from? Would be nice to install XGBoost just with pip3.
